### ISSUE TITLE
[RDF] You are not in this instance's group.

### ISSUE THREAD

**Issue by Feryk** [WoWManiaUK/Redemption#1000]
[+] Using the latest WoW-Mania custom client?
 -  Yes

[+] What are the steps to reproduce the problem?
 - Queue for RDF Heroic and work your way through the given dungeon.

[+] How should this be working?
 - You should be able to complete the dungeon fully without being kicked out.

[+] What is broken?
 - Part of the way through the dungeon, all members of the party receive the message "You are not in this instance's group...." and are eventually kicked after 60 seconds.  Upon re-entering the dungeon with the instance teleport tool, you will find that the dungeon has been reset.

[+] Screenshots?
 - http://i.imgur.com/3iMBbCB.jpg

**Comment by Plege** [comment]
i can confiorm this happening in raid situations also. usually it happened to me after a wipe when reentering the raid. it teleports you out after 60 seconds. all players leave the raid and it has to be reformed to reenter properly
