### ISSUE TITLE
[Quest] Stunning View.

### ISSUE THREAD

**Issue by efdede** [WoWManiaUK/Redemption#1001]
Doing this quest : http://www.wowhead.com/quest=13160/stunning-view

In order to do this quest i need to be transformed to a Lithe Stalker. I tried relogging, abandon and retaking quest. But the Eye of Dominion i need using to transform provides text instead of transforming me. The transformation is required in order to "heave" the gargoyles.

![image](https://cloud.githubusercontent.com/assets/25913500/24322962/ef7d6ade-116d-11e7-8226-186135171eb2.png)

**Comment by elagen** [comment]
i can confirm that http://www.wowhead.com/object=193058/eye-of-dominion when used turns you into a mob so you can properly kill the http://wotlk.openwow.com/npc=31012

i have managed to kill the Gargoyles without using the eye of dominion so the quest can be completed
