### ISSUE TITLE
[Quest] Where Can It Be?

### ISSUE THREAD

**Issue by wrthigpen** [WoWManiaUK/Redemption#1002]
Was running quest Where can it be in Sholazar basin.  Over a period of 2-3 days, non-consecutive, had killed 40-60 mobs, animal mobs and dig site mobs, and ring had not dropped.  Abandoned and reacquired quest, then killed 10-15 additional mobs with no drop.  Character name: Ubee.  WoW-Mania login name: wrthigpen.  Submitted ticket and was assisted by one of the GM's.  Date of completion of quest:  03/25/2017.

**Comment by fvicaria** [comment]
Please follow the procedure described below before creating a new issue:
[How to Properly Report an Issue](https://github.com/wow-mania/Redemption/wiki/How-to-Properly-Report-an-Issue)

This will help developers identify and fix the issue quicker. Incorrectly or unclear reports will simply be deleted.


Please post link to quest.

**Comment by fvicaria** [comment]
Fill in the correct details if you think this is a proper issue.
