### ISSUE TITLE
Test of strenth

### ISSUE THREAD

**Issue by ghostspawn** [WoWManiaUK/Redemption#1003]
Shaman quest ..test of strength the toon Rok'alim cannot be found ..

**Comment by Feryk** [comment]
http://www.wowhead.com/quest=1151/test-of-strength
http://www.wowhead.com/npc=4499/rokalim-the-pounder
http://imgur.com/a/3RXbS

He spawn properly.  His pathing is from the Northwest to Southeast edge of Thousand Needles, just keep your eye open for him.

**Comment by fvicaria** [comment]
Thank you for the help. :)
