### ISSUE TITLE
[Quest] Twilight of the Dawn Runner

### ISSUE THREAD

**Issue by Ackpfft** [WoWManiaUK/Redemption#1004]
In the quest, I was able to retrieve the cargo on the tower, but unable to interact with Ithania to "rescue" her. I dropped and retook the quest multiple times, logged out and cleared my cache and nothing seemed to work. A GM completed the quest for me.

**Comment by fvicaria** [comment]
http://www.wowhead.com/quest=9437/twilight-of-the-dawn-runner
