### ISSUE TITLE
[Dungeon] Jammal'an the Prophet in Sunken Temple

### ISSUE THREAD

**Issue by Readerlady** [WoWManiaUK/Redemption#1005]
To kill Jammal'an the Prophet one must kill all the guardian mini bosses up above the ring. I have killed them all but the wall that protects Jammal's room does not come down as is should. Thus I can not get to him to kill Jhim to complete the quest by looting his head.  http://www.wowhead.com/npc=5710/jammalan-the-prophet#comments

**Comment by DarkestDuck** [comment]
Still broken
