### ISSUE TITLE
[Shaman] Far Sight mounted speed

### ISSUE THREAD

**Issue by Feryk** [WoWManiaUK/Redemption#1011]
[+] Using the latest WoW-Mania custom client?
 - Yes

[+] What are the steps to reproduce the problem?
 - Mount and then cast Far Sight.

[+] How should this be working?
 - Casting Far Sight should dismount you and you should not be able to move at mounted speeds.

[+] What is broken?
 - Casting Far Sight will dismount you and allow you to continue moving at mounted speeds.  This will cause the player to seem to be speed hacking.

**Comment by fvicaria** [comment]
I am pretty sure this is also fixed in the PTR. If you could give it a try there and confirm it would help.

**Comment by Feryk** [comment]
I'll hop in there as soon as I can.

**Comment by Feryk** [comment]
Fixed in Dev.
