### ISSUE TITLE
[Item] Conjured Mana Strudel

### ISSUE THREAD

**Issue by Feryk** [WoWManiaUK/Redemption#1012]
[+] Using the latest WoW-Mania custom client?
 -  Yes

[+] What are the steps to reproduce the problem?
 - Conjure and then Use a Conjured Mana Strudel.

[+] How should this be working?
 - The Strudel should recover 640 mana and 750 health per second.

[+] What is broken?
 - It seems that the amount of mana being recovered is around 150-200 per second instead of 640.

[+] Video:
 - https://youtu.be/I4-dKLjJ65o

**Comment by fvicaria** [comment]
Also probably fixed in the PTR.

**Comment by Feryk** [comment]
Will test this there as well as soon as I can. :)

**Comment by Feryk** [comment]
This is still happening in Dev.
