### ISSUE TITLE
[Quest] Battling the elements

### ISSUE THREAD

**Issue by Celism** [WoWManiaUK/Redemption#1013]
This is a quest out of Son's of Hodir quest line. 
I am supposed to kill 10 seething revenants,.
While i kept killing them, the counted was stuck to 0/10 slain.
I sent a ticket, a very helpful GM with the name: psygoa helped me out but it is something you might need to look after for everyone else trying to do this quest.
Ty a lot have fun all

**Comment by fvicaria** [comment]
http://www.wowhead.com/quest=12967/battling-the-elements
