### ISSUE TITLE
[Quest] The Battle For Crusader's Pinnacle

### ISSUE THREAD

**Issue by zaybrie** [WoWManiaUK/Redemption#1015]
While trying to do this quest for the questing hub, the mobs spawn all at once killing the NPC's and is impossible to kill with a group as there are a bunch of 80 elites group up. They despawn after a while, but you can't do anything but wait. After dying once the questing hub appeared and then quickly disappeared.

**Comment by Feryk** [comment]
Could you message me in-game: Feryk.  I'm actually having an issue finding Father Gustav to begin the first quest in this chain.

Chain:
 - http://www.wowhead.com/quest=13139
 - http://www.wowhead.com/quest=13141
 - http://www.wowhead.com/quest=13157

**Comment by Plege** [comment]
i can confirm that during the quest http://www.wowhead.com/quest=13141 the spawn rate of the attacking waves is a bit too high, this makes it quite hard to keep the friendly forces alive and if they die the quest fails / resetts.

**Comment by fvicaria** [comment]
Increased the delay between waves. Max I can do.

**Comment by wowgamer1980** [comment]
Also the the banner has so little life (doesn't suppose to) and it doesnt heal you as much as it suppose to so you die.. I have done this quest many times in official and the banner had a lot of life and you weren't dying because the banner healed you.
