### ISSUE TITLE
[Quest] Fortunate Misunderstanding

### ISSUE THREAD

**Issue by dipzlot** [WoWManiaUK/Redemption#1016]
Quest is located in Sholazar Basin The npc to start the escort quest has the option to begin the escort quest, but clicking the option does not do anything. There are multiple spawn's of the npc around the area as well and they do not start the escort quest either. Quest was previously noted as fixed in 1/25/2017, but does not work as of 3/28/2017

**Comment by fvicaria** [comment]
http://www.wowhead.com/quest=12570/fortunate-misunderstandings

**Comment by Plege** [comment]
ok this is a weird one. basically it's not working as the injured guys teleport away once the dialog is done but they teleport all to the same island no clue why 
![grafik](https://cloud.githubusercontent.com/assets/24266043/24546906/981d2fdc-160d-11e7-8639-c07f02267ef2.png) needs to be tweaked some more

**Comment by fvicaria** [comment]
Just tested in PTR and it works.
