### ISSUE TITLE
[Achievment] Giddy Up!

### ISSUE THREAD

**Issue by tsuff** [WoWManiaUK/Redemption#1019]
I have the pony for my Argent grunt and it uses it as supposed to. But for some reason i`m missing the
http://www.wowhead.com/achievement=891/giddy-up
achievment.

**Comment by Emcitementz** [comment]
That's a skill and you need to buy it from the riding trainer.
That's the second false issue from you, please ask in world chat or even write a ticket before posting anything here if you're not sure of what you're saying, that will help us a lot.

**Comment by tsuff** [comment]
no its the girdle u buy from the vendor for the grunt to ride

**Comment by tsuff** [comment]
sry it was pony up i ment
