### ISSUE TITLE
[Quest] Testing the Vessel

### ISSUE THREAD

**Issue by tsuff** [WoWManiaUK/Redemption#1020]
The quest 
http://www.wowhead.com/quest=3123/testing-the-vessel
not working. I`ve killed owl beasts targeted their boddies and clicked  [Beast Muisek Vessel] quest item. It says Invalid target.

**Comment by Emcitementz** [comment]
You need to kill the wolves, select them and use the quest item in order to progress.
That's also said in the quest.
