### ISSUE TITLE
Inscription Recipes missing

### ISSUE THREAD

**Issue by redhawk816** [WoWManiaUK/Redemption#1022]
I linked a guildie my Inscription and he saw recipes that when I opened it, were not there. 

His view:  
![17622798_10158391525940058_1905704226_o 1](https://cloud.githubusercontent.com/assets/23039881/24473938/9a184976-1490-11e7-8ee9-a6ab6bac3360.jpg)

My view:
![wowscrnshot_032817_155848](https://cloud.githubusercontent.com/assets/23039881/24473960/aea1fd7e-1490-11e7-97d1-8e10b11cb410.jpg)

Several are missing!!! wth?

**Comment by Plege** [comment]
It  has been known to happen, that when you share your profession the receiver that clicks the link sees more recepies than the player sending the link has available.

**Comment by fvicaria** [comment]
Maybe different filtering. Let me know if it happens again and send me the name of the char so I can copy it.
