### ISSUE TITLE
Deep freeze no damage?

### ISSUE THREAD

**Issue by Cyoss** [WoWManiaUK/Redemption#1026]
Sooo My deep freeze don't do any damage. 
It stuns, and work fine with fingers of frost.. but no damage. Hope this will get fixed soon :)
(Can't remember if it does damage to players original)

**Comment by VA-L** [comment]
http://prntscr.com/eqftq4

**Comment by VA-L** [comment]
![screenshot_18](https://cloud.githubusercontent.com/assets/11377592/24519407/53ad1cb4-1585-11e7-81c9-36f582836ae7.png)

**Comment by Cyoss** [comment]
It doesnt deal damage yo

**Comment by VA-L** [comment]
![screenshot_19](https://cloud.githubusercontent.com/assets/11377592/24519496/acc5c63e-1585-11e7-9216-28c19a7fce1f.png)
Clearer?

**Comment by Cyoss** [comment]
i dont get it... it says "Permanently stun immune target" WITH 1469 to 1741 base damage... Aint it supposed  to deal something between those numbers?

**Comment by VA-L** [comment]
Nope, those values aren't a reference.
