### ISSUE TITLE
[Quest] Mutiny on the Mercy 

### ISSUE THREAD

**Issue by Jibb94** [WoWManiaUK/Redemption#1027]
You are supposed to kill mutinous sea dogs (http://www.wowhead.com/npc=25026/mutinous-sea-dog) to get 5 barells of blasting powder (http://www.wowhead.com/item=34387/barrel-of-blasting-powder)  but the mutinous sea dogs don't seem to spawn. 

quest: http://www.wowhead.com/quest=11527/mutiny-on-the-mercy

**Comment by fvicaria** [comment]
Thanks for taking the time. We are aware of this. It happens after you create a character sometimes or cancel an action.
However this repository is for server-side issues.
We will be acting on this.

**Comment by fvicaria** [comment]
The issue is that they fall from the boat much like the NPCs on the skyrider in Icecrown.

**Comment by elagen** [comment]
This is working - for the best result - wait for the boat to stop and then you can attack them properly and complete the quest
