### ISSUE TITLE
AH item bug

### ISSUE THREAD

**Issue by GMBoomboom** [WoWManiaUK/Redemption#1029]
Auction house items that are sold are not always received

**Comment by Plege** [comment]
did you wait a few minutes and make sure you did the quick buy option? because if you bid and someone outbid you that's one reason, the other is that it takes a while sometimes even after buy out

**Comment by fvicaria** [comment]
Please enter a specific case or we have no chance of debugging much less fixing.

Need character name, item name. if it is on mail or not, etc.
