### ISSUE TITLE
[Quest] Rallying the Troops

### ISSUE THREAD

**Issue by Zan511** [WoWManiaUK/Redemption#1030]
Greetings.
A very simple quest, not working the way it should. The quest asks the player to mark 5 Grizzly Hills Giants, and then Slay 5 Iron Rune Avengers. There are a lot of Giants in the area (~18) and out of all those, only 1 worked. The debuff lasts on the Giants for about 1 minute, the cooldown of the item provided "Shard of the Earth" is 30 seconds. I tested all of them again, but with no avail; even the one that worked for me before didn't count again (After 30 mins of the first try). This quest is at the start of a quest-chain required for Loremaster of Northrend (3rd quest out of 8).
Please, give it a whirl and see how it goes.
Cheers.

**Comment by fvicaria** [comment]
http://wotlk.openwow.com/quest=12070

**Comment by fvicaria** [comment]
Works perfectly.
![image](https://cloud.githubusercontent.com/assets/9414661/24561545/08da37a2-163f-11e7-9542-f48928210aba.png)
