### ISSUE TITLE
[Quest] Filling the Cages

### ISSUE THREAD

**Issue by Zan511** [WoWManiaUK/Redemption#1031]
Greetings.
This quest in Grizzly Hills, part of a quest-chain for the achievements: "Guru of Drakuru" and "Loremaster of Northrend" isn't working properly.
The quest asks the player to speak to the NPC "Budd" and take him to where trolls are so he can tag them and then the player puts said troll in a cage. The NPC doesn't seem to be working properly where he does absolutely nothing but chat. He has a spell "Tag Troll" but it's not working. He doesn't sense any Trolls nearby which is super weird, and he doesn't do anything.
Please look into it. Thank you.
Cheers.

**Comment by fvicaria** [comment]
Please add quest/npc/item references when possible (openwow and wowhead only). Check 

[How to Properly Report an Issue](https://github.com/wow-mania/Redemption/wiki/How-to-Properly-Report-an-Issue)

This will help developers identify and fix the issue quicker. Incorrectly or unclear reports will simply be deleted.

**Comment by Zan511** [comment]
What about wow-mania armory?

**Comment by fvicaria** [comment]
Also goo but equivalent to wotlk.openwow.com

**Comment by fvicaria** [comment]
http://wotlk.openwow.com/quest=11984

**Comment by Jibb94** [comment]
I can second this issue and I'll help here.  When you accept the quest you have to first talk to Budd (http://www.wowhead.com/npc=26422/budd) he becomes your companion.  Then you must travel to the troll village to the south and order Budd to attack the trolls but that command doesn't seem to function.  Budd will walk up to the trolls but will not initiate combat.

Quest: http://www.wowhead.com/quest=11984/filling-the-cages

**Comment by fvicaria** [comment]
Works fine. He talks and you throw the cage.

**Comment by Jibb94** [comment]
I know this is closed but to help Zan I just did the quest and can confirm it works.  The cage calls for a troll to be "stunned" but in fact you can use the cage on non stunned trolls.  Hope this helps!

**Comment by fvicaria** [comment]
Yes maybe some effect and condition missing
