### ISSUE TITLE
[Quest] Convocation at Zol'Heb

### ISSUE THREAD

**Issue by dothie** [WoWManiaUK/Redemption#1032]
i called the player to prophet Zol'heb, and asked him to do the quest so i could see what happens.
The summon was fine but whit the attack around 80% the prophet freezes, The player was not able to attack  The prophet anymore

**Comment by fvicaria** [comment]
http://www.wowhead.com/quest=12730/convocation-at-zolheb

**Comment by fvicaria** [comment]
Works perfectly.

![wowscrnshot_040117_170012](https://cloud.githubusercontent.com/assets/9414661/24580252/cf319626-16fc-11e7-9f04-6fbdc0ced2df.jpg)
![wowscrnshot_040117_170035](https://cloud.githubusercontent.com/assets/9414661/24580254/d32e41ac-16fc-11e7-9378-6de727e60537.jpg)
