### ISSUE TITLE
Quest: The Thirsty Goblin

### ISSUE THREAD

**Issue by exinfernus** [WoWManiaUK/Redemption#1033]
Quest giver Marin Noggenfogger was not giving out quest, GM gave me quest manually to resolve issue. Chain is not working Marin is not accepting Laden Dew Gland.

**Comment by exinfernus** [comment]
![wowscrnshot_040117_161551](https://cloud.githubusercontent.com/assets/26839936/24579909/93bd784a-16f6-11e7-9fb8-50730bc54c38.jpg)

**Comment by VA-L** [comment]
You've already done it, that's the reason.

**Comment by exinfernus** [comment]
Thats impossible, Marin does not sell me noggerfogger and untill a GM gave me the quest I have not even been to hinterlands.

**Comment by exinfernus** [comment]
Hi VA-L


I think I would have remembered if i done this quest line. I cannot buy the elixirs and i have not completed the chain on any character.


Kind regards


________________________________
