### ISSUE TITLE
[Custom] Chainmail Lich King set procs not working properly possibly?

### ISSUE THREAD

**Issue by seridwyn** [WoWManiaUK/Redemption#1034]
Chain mail set proc for two pieces is supposed to give you the form of the iron dwarves granting crit this only procs when the armor is put on or you log in and does not proc again the 8 peices set proc grants form of the vrykul giving haste and also only procs when the amor is put on or you log in and does not proc again i am unsure if this is intentional or if its meant to proc with melee attacks like deathbringerswill does if it is meant to proc with melee having it fixed would be most amazing

**Comment by Plege** [comment]
I can confirm that during 100 autohits neither the 4 Piece nor the 8 Piece procc occured except the exact moment i put them on.

**Comment by elagen** [comment]
While Equiping 4 Set
![wowscrnshot_040417_163415](https://cloud.githubusercontent.com/assets/22685042/24665324/f5526808-1954-11e7-9584-fe4c2c390d3e.jpg)

While i have 6 peices on out of 8 - the Valkyrie proc is going off
![wowscrnshot_040417_163431](https://cloud.githubusercontent.com/assets/22685042/24665381/23982ca2-1955-11e7-8949-df84b18d36a4.jpg)
