### ISSUE TITLE
[Quest] Monitoring the Rift: Cleftcliff Anomaly

### ISSUE THREAD

**Issue by Readerlady** [WoWManiaUK/Redemption#1037]
http://www.wowhead.com/quest=11576/monitoring-the-rift-cleftcliff-anomaly
I can use the Arcanometer when standing in the cave entrance and it seems to work. Dirt falls from the roof above even. The quest however does not complete.

**Comment by Plege** [comment]
if you watch the video in http://www.wowhead.com/quest=11576/monitoring-the-rift-cleftcliff-anomaly you'll see that there is no cave involved. it's on the coast and it works fine
