### ISSUE TITLE
RDF party bug

### ISSUE THREAD

**Issue by TheSale** [WoWManiaUK/Redemption#1039]
I queue for rdf lvl 62 druid as healer/dps,
dungeon pop up I join in middle of dungeon and I get healer role, BUT 2 of us have healer role icon,
so 2 healers 2 dps 1 tank... 
Okay I respec in feral and go dps, everything fine, then we wipe, THEN SHAMAN LEADER CANT ENTER DUNGEON, then ROQUE STAND NEXT TO US..... wtf..... 

I will attach photo where you can see recount of people who was in dungeon and then in chat you can see roque talking
![wowscrnshot_040217_232648](https://cloud.githubusercontent.com/assets/20323863/24591205/12d12464-17fc-11e7-9666-a3092cd31693.jpg)

I dont have ss from dungon, where I see roque standing next to me he write in party but he is not in a party.
after I ask roque to leave and he said he dont want, I ask them to kick me from party,it is okay but I fucking lose 1 hour of my life coz this bug :/

**Comment by fvicaria** [comment]
When you learn how to write a bug report without cursing I will take you seriously.
