### ISSUE TITLE
[Quest] Secrets of the Ancients

### ISSUE THREAD

**Issue by AtlasRedux** [WoWManiaUK/Redemption#1041]
Magic-Bound Ancients doesn't give quest-items, making it impossible to finish the quest.

**Comment by Plege** [comment]
http://wotlk.openwow.com/quest=11910

**Comment by Plege** [comment]
literally the first one i killed 
![grafik](https://cloud.githubusercontent.com/assets/24266043/24598377/5dfb242c-184b-11e7-8775-260a8853fe88.png)

might have had some bad luck. reopen if the problem persists

**Comment by Feryk** [comment]
I was also able to find the drops - https://youtu.be/KlKEPGeHJfo
