### ISSUE TITLE
NPC Captain Kendall is missing Confirmed

### ISSUE THREAD

**Issue by GMBoomboom** [WoWManiaUK/Redemption#1042]
NPC Captain Kendall is missing from Ice crown

**Comment by fvicaria** [comment]
It's there.

![image](https://cloud.githubusercontent.com/assets/9414661/24603909/a129fc96-185a-11e7-89ec-acd2377d4f4b.png)

**Comment by GMBoomboom** [comment]
Thats weird, he wasnt there when i checked or went to .go creature
