### ISSUE TITLE
NPC Goramosh doesn't drop quest item

### ISSUE THREAD

**Issue by idl0r** [WoWManiaUK/Redemption#1043]
Hi, "[Goramosh](https://www.wow-mania.com/armory/?npc=26349) should actually drop "[Goramosh's Strange Device](https://www.wow-mania.com/armory/?item=36746)" and according to those data it should be a 100% drop. I killed that NPC like 15 times and he never dropped it.

I need that quest as a pre-quest series for a daily at the end https://www.wow-mania.com/armory/?quest=12372

**Comment by VA-L** [comment]
Thanks for the report, it is well described.
But ... take a look at it -> http://fr.wowhead.com/npc=26349/goramosh#english-comments

**Comment by idl0r** [comment]
Oh, damn. I'll try that in a bit and report back. Thanks!

**Comment by idl0r** [comment]
Yup. That's it. Works. Thanks and sorry!
