### ISSUE TITLE
Quest Cold Hearted not working

### ISSUE THREAD

**Issue by kainus** [WoWManiaUK/Redemption#1044]
The quest Cold Hearted in The Stormpeaks can not be completed. The quest starts in Brunnhildar Village at Briljana. You are to fly to Dun Niffelem and liberate a captive proto drake. The quest is doable up to this point. Once you mount the drake you have to free other drakes and prisoners encased in ice below but you have no pitch control to go up or down so most of the prisoners you have to liberate are out of range no matter how close you get to them the ones that are in range no credit is given at all for breaking the ice and freeing them. The other drakes you are to free nothing happens at all when you target them and use the mounted drakes spell to free them. Toon currently on this quest is Grimone I had a GM complete it on my other toon Goldmane.

**Comment by fvicaria** [comment]
You do. Use space bar and x button. It's a bit tricky to unlock the movement to start with but you will get used to it.

**Comment by kainus** [comment]
What about not getting credit for the prisoners that I have freed and nothing happening when I try to free the drakes ?

**Comment by fvicaria** [comment]
I will check it again now.

**Comment by kainus** [comment]
The space bar x button worked for the flight problem but still no credit for freeing anything.

**Comment by fvicaria** [comment]
![image](https://cloud.githubusercontent.com/assets/9414661/24649396/cf93b7a6-191e-11e7-9cbd-6eea04865add.png)
It works

**Comment by kainus** [comment]
That screen shot is in the village the quest I am on is in Dn Niffelem and you are on a proto drake to do it.

**Comment by fvicaria** [comment]
Dude! Go read the quest description. You need to deliver the prisoner.
The quest works. End of story.

**Comment by kainus** [comment]
Got it now thai I am able to get close to them I see them in the drakes claws when I free them.
