### ISSUE TITLE
[Quest] Protect Kanati Greycloud

### ISSUE THREAD

**Issue by warcrafter3001** [WoWManiaUK/Redemption#1046]
I accepted the quest, he yelled theyre coming, and then the quest completed, no things came to attack, it just completed. Not a huge issue the quest did give me completion, but it was a bit of a let down not to defend the camp.

**Comment by Feryk** [comment]
Is the name of the quest suppose to be "Protect Kanati Greycloud"?  Is this the one? http://www.wowhead.com/quest=4966/protect-kanati-greycloud

**Comment by Feryk** [comment]
Chain to being quest: http://www.wowhead.com/quest=4881/assassination-plot
