### ISSUE TITLE
Overall server class DPS issue

### ISSUE THREAD

**Issue by IPTVKings** [WoWManiaUK/Redemption#1047]
I was checking out some of the retail videos and in comparison to the server raid dps done by each class seems to be off by nearly 6-7k I've never seen any other class besides warrior to hit above 10k up close to 13k dps fully BiS. I've seen both casters and ranged having either BiS or LK set + paid weapon that don't even come close to this much dps showing in the video below.

https://www.youtube.com/watch?v=7P03rfYbISQ
https://www.gamefaqs.com/boards/534914-/55886296

Understandably there is also the fact that maybe the player in wow-mania is not as good as a retail player, however out of 25 people there will at least be someone who knows how to play their own class, yet their dps is not a match even though they both have same spec, same gear and rotations. 

I don't know if there's an issue with each class talents or the dps has been nerfed.

**Comment by elagen** [comment]
Can you link your DPS meter of what is happening??

we raid weekly and i test alot - there are no dps issues - from what i can see - we have ranged dps that are close to BiS pulling more then 15k dps so i dont see a problem
