### ISSUE TITLE
[Raid] Black Temple

### ISSUE THREAD

**Issue by Unstoppablee** [WoWManiaUK/Redemption#1048]
I've done this instance lately on Redemption, and we were bugged in here.
We actually didn't know boss sequence so with Elagen and Anthon we tested it again on Dev to see what will happen.
We killed same on Red. first 2 bosses easily, then we freed Akama, and then we were at Spirit of Udalo, and we wiped. After wipe we could not start fight again. We made ticket, GM came and killed him. The door opened and we killed 2 more bosses after doors. After that we were at council (last boss before Illidan), we killed em, and gone back to talk to Akama, but we could not do that. Came back to Ilidans door and council was alive, we killed em again. GM teleported us to Illidan, but we could not start fight without Akama.

We wiped on Spirit of Udalo on dev. server on purpose to check it, and same happened.
We had to GM kill him. 

I think that's it.
Sorry for lack of english.

**Comment by elagen** [comment]
while doing https://wotlk-twinhead.twinstar.cz/?npc=23410 after wiping the boss does not reset / respawn properly 

![wowscrnshot_040517_160250](https://cloud.githubusercontent.com/assets/22685042/24713357/59df7950-1a1d-11e7-83dc-4baae12a3534.jpg)

this is how the boss looks and stays like it after the raid has wiped
