### ISSUE TITLE
Raid Loot

### ISSUE THREAD

**Issue by Ford577** [WoWManiaUK/Redemption#1050]
Originally a forum post, I was told to post it here. Due to the post, it might already be being looked at, but I wanted to be sure. https://wow-mania.com/forum/viewtopic.php?f=21&t=704

It is very common to get doubles/triples of the same loot drops in raids.

![raidloot](https://cloud.githubusercontent.com/assets/26547820/24717629/1ccaa3bc-1a01-11e7-8a01-78707242672d.jpg)

Within a span of two weeks worth of ICC's  I can account for at least three different instances of getting multiple same loot drops on a boss. Our Ruby sanctum runs always have at least one double item on the boss. Though I am having issues finding retails exact loot statistics on the internet, I can attest to never having this issue on retail with janitor agreeing that it is not an intended situation. If it would help I can start taking more screenshots of when double drops happen other than the one I already have.

**Comment by Feryk** [comment]
Did this happen in 10, 25, HC or Norm?

**Comment by Feryk** [comment]
If this is 25-man, this is normal.  However, this should not be happening in 10-man raids and normal dungeons.  Was this a 10-man raid?

**Comment by Ford577** [comment]
It was not a 10 man raid, no. You can't get three items in a 10 man, only 2. Though you are telling me getting triple loot drops is normal for a 25 man?

**Comment by Ford577** [comment]
I won't deny it isn't possible, I just don't believe it is as probable as it currently is

**Comment by Feryk** [comment]
Per the upstream code, it is possible: https://github.com/TrinityCore/TrinityCore/commit/ca280dbe051f2d9c43bbda128a6aa6bc19d8149f

 +    uint8 maxDuplicates;                                    // Max amount of items with the same entry that can drop (default is 1; on 25 man raid mode 3)

**Comment by Ford577** [comment]
Okay I understand your point, but even still the probability of getting 3 of the same item has to be extremely low, shouldn't it be? I can do some number crunching later if needed. I can happen but virtually never should happen. This is the third time it has happened within about 5 weeks

**Comment by Ford577** [comment]
Even getting double loots should be much more rare than it is I feel

**Comment by fvicaria** [comment]
I will close this for now as it just seems a bad wave. I have not seen anything impossible or wrong here.
If it continues for another week or two please reopen.

**Comment by IPTVKings** [comment]
I stand witness that one time we did 25 out of 9/12 bosses dropped double loot essentially thats where we stopped the raid cause people got pissed and left. 
in the coding part there should be % probability of double or triple loot drop. if i had to guess its probably set to 25%-50%

**Comment by Grindall** [comment]
xD I'm not sure why you believe that this is normal, but I'll give some statistics.
http://www.wowhead.com/npc=36626/festergut#drops:mode=n25
There are a chance at 16 pieces of loot minus the shadowfrost shard, primo saronite, and blood from festergut. Honestly, based on the statistics of the loot I am not 100% sure how the game chooses what loot to drop. The website I linked has different drop percentages for the possible loot drop, but they don't add up to 100%.
However, even if you do simple statistics to make it close to what it might be, if you think that each of the 16 items have an equal chance of dropping (which I know they don't, but the item's drop chances should be close enough for this example) then you are looking at 6.25% chance to get a certain item. In this case, use the Unclean surgical gloves. In 25 man mode you have 3 items that are guaranteed to drop. So, using the estimated statistic of having a 6.25/100 chance of getting the gloves, the chance of getting 3 of them to drop on the same boss is 244.14/1,000,000. Expressed as a percent, .0244% chance of this happening. 

Is it possible? yeah, completely. Is it probable? No. Should it be considered "normal"? No. Even the chance of double loots is ridiculously low. Taking the chance from the same boss using the same 6.25% drop rate, you get 39.06/10000, or .39% chance of this actually happening. For this to be happening weekly or even biweekly it would be hard to believe, yet it is.

**Comment by fvicaria** [comment]
All those values are wrong. They are not as per 3.3.5a.
Check wotlk.openwow.com

**Comment by Grindall** [comment]
okay, so 17%
http://wotlk.openwow.com/item=50703
that is still 4913/1000000 aka .49%

**Comment by Grindall** [comment]
look, I'm just trying to help. I know it isn't supposed to be happening as much as it is, I made a forum post about it, janitor himself told me he agreed with me and told to make a github about it, then you are telling me it isn't an issue. Maybe you should talk to janitor instead of me. I'm not claiming to know the coding of the game works in the game, I'm not a dev. I'll just leave it be and you can do with it what you want.
