### ISSUE TITLE
[Raid] Ulduar XT-002 Deconstructor

### ISSUE THREAD

**Issue by Ford577** [WoWManiaUK/Redemption#1051]
Hitbox
The hitbox is far too small. As a melee, you have to be standing on top of the boss in order to hit him. Furthermore, the hitbox for the heart is extremely awkward...you have to be standing in just the right position or it is unhittable.
Heart
When attempting heard mode, when you pop the heart for the first time it doesn't trigger hard mode. It instead resets the boss to full hp when it is killed. When you kill it the second time it triggers hard mode.
Adds
Far too many adds spawn. There should be 2 Pummelers that spawn during the  heart phases (10 man--25 is unconfirmed), but normally you get around 10.
https://www.youtube.com/watch?v=BHcFWPUBpr4 @ 1:20
Wiping
should you happen to wipe on the fight, when you come back to do the fight again the heart no longer spawns, and, thereby, no more adds spawn either. He still does the vocals and animation for the heart phase as well as becomes  untargetable; however, no heart spawns.

**Comment by elagen** [comment]
Hard mode

Heartbreak: Activated when killing the Exposed Heart, engaging hard mode and healing the boss to full: The heart of the XT-002 Deconstructor has been severed, removing the combat limitations of the XT-002 Deconstructor. Damage increased by 15%. Health increased by 50%. (25-man: 15% damage and 60% health) XT-002 will no longer summon adds or have exposed heart phases, but any adds summoned during the breaking of the heart will need to be dealt with.

That is after killing the heart is how it should be - it will heal the boss back to 100%

-------------------------------------------------------------------------------

With the Hitbox - That is Confirmed that the hit box is too small - in the Video you see people standing outside the Legs and still hitting the boss - this is not happening on the boss fight

You Can see me standing under the boss which is the furthest place you can stand to hit the boss
![wowscrnshot_040617_092655](https://cloud.githubusercontent.com/assets/22685042/24745417/98ab23ce-1aad-11e7-8f74-92542d481a6c.jpg)

Here is where im standing in the video and as you can see i can NOT hit the boss
![wowscrnshot_040617_092649](https://cloud.githubusercontent.com/assets/22685042/24745448/ac842f26-1aad-11e7-943f-f51ce57b5036.jpg)

The Boss hitbox should be bigger yes
