### ISSUE TITLE
[Raid] Ulduar Iron Council

### ISSUE THREAD

**Issue by Ford577** [WoWManiaUK/Redemption#1053]
The majority of the issues are with Stormcaller, so I'll link his abilities. 
http://wowwiki.wikia.com/wiki/Assembly_of_Iron

 Overload -deals 25,000 nature damage on heroic or 20,000 nature damage on normal to all targets within 20 yards of Brundir. Brundir generates the emote "Stormcaller Brundir begins to Overload!" while casting. While casting gains the Stormshield effect which deals 250 nature damage and grants immunity to stun effects.

- This ability likes to pick and choose when it wants to work. Most of the time it spawns a targetable, invisible, killable npc called overload visual. When it does this, overload doesn't occur.

 Lightning Whirl (1 dead) - Deals 5655 to 6345 nature damage on heroic or 3770 to 4230 nature damage on normal per bolt. Fires multiple bolts per second and needs to be interrupted as quickly as possible.

- I believe this mechanic works; however, the timer is off. It will only occur _maybe once during the entire encounter when it should occur every 10-30ish seconds.
https://www.youtube.com/watch?v=vBPyfOnf18g and example: first occurs at 2:28 (as seen by the raid damage) second occurrence is at 2:40

Stormshield (2 dead) Brundir also becomes immune to stun effects once Steelbreaker and Runemaster Molgeim are dead, as he is not previously. Stun effects against him before this are affected by diminishing returns however. 

- Does not work at all/always works...basically you are never able to stun Brundir, when you should be able to while the first two bosses are alive.

**Comment by Ford577** [comment]
I forgot to add the most important bit--his pathing. Stormcaller randomly wonders around the room despite who has aggro. Often, this is through a wall, making killing him extremely difficult.

**Comment by elagen** [comment]
there are a few points here

With https://wotlk-twinhead.twinstar.cz/?npc=32857 (Stormcaller Brundir) when the Targeted person is close to him with the aggro Stormcaller does run away from the raid 

![wowscrnshot_040617_101203](https://cloud.githubusercontent.com/assets/22685042/24746892/8cc74240-1ab2-11e7-8494-f4408c3214dd.jpg)

![wowscrnshot_040617_101209](https://cloud.githubusercontent.com/assets/22685042/24746912/93533fc4-1ab2-11e7-99bb-b3ef16976262.jpg)

As you can see first i am Next to him and then in the Second Screenshot you see him move accross the room

-------------

I Can confirm that Stormcaller Brundir can be stunned and while the First 2 bosses are up he can NOT be stunned

When Brundir gets http://www.wowhead.com/spell=64187/stormshield After 2 of the bosses are dead he then should be immune to Stuns - not before

While doing this ecounter http://www.wowhead.com/spell=63483/lightning-whirl Was not used when 1 boss was killed

Also during the encounter Brundir does http://www.wowhead.com/spell=63485/lightning-tendrils which he goes into the air and Targets a player and follows then around the room - this is Half Happening during the ecounter 

He is Targetting a player and Going to the spot where they was standing so you can move around the room and completely avoid him moving towards you from where u was standing
