### ISSUE TITLE
[Quest] Gaffer Jacks

### ISSUE THREAD

**Issue by Katherwind** [WoWManiaUK/Redemption#1055]
The fishing quest: " Gaffer Jacks"  in Darkshore is not dropping the items when fishing (in the ocean).  
Tried logging in and out, trying again the next day and the items still aren't dropping.  I have heard of at least 3 people having the same issue.  

www.wowhead.com/quest=1579/gaffer-jacks
www.wowhead.com/item=6717/gaffer-jack

**Comment by hotdoggidy** [comment]
Standing on the coast of Auberdine, in Darkshore, the map has a large portion of the coast highlighted where a player should be able to fish up Gaffer Jacks if they have the quest. The player must have at least lvl 30 fishing to pick up the quest from "Wizbang Cranktoggle" (http://wotlk.openwow.com/npc=3666)

tested on Frostmourne with 150 succesful casts. all @ lvl 75+ fishing (max for zone). Not a single Gaffer jack looted.
