### ISSUE TITLE
[Spell] Insanity, by Herald Volazj

### ISSUE THREAD

**Issue by Synathy** [WoWManiaUK/Redemption#1056]
Am I using our client?: Yes
Am I using the latest Launcher?: Yes, WoW-Mania 2.0.6, game launched using "Launcher.exe".

Did I include the steps to reproduce the problem?
Fighting Herald Volazj down to about 60% health left or 30% health left should make him cast Insanity (57496). Once he finish casting, you shall get one of these debuffs (Insanity's id 57508, 57509, 57510, 57511 or 57512, dependant of which phase you get in) and see **a clone with your name** and the other's clones unless you're alone.

Did I include the description of how it should work?
The actual bug is getting your **own** clone in your own phase. As a player, once entering your **own** phase of Insanity, you **shouldn't** get a clone with **your** name.

> Whenever one of the players kills all 4 images assigned to him, he will phase out seeing another of his friends fighting, and will be able to give a hand. When all 20 images are dead, Volazj will become attackable again, and in fact will attack. From now on it's rinse and repeat fight.

Upvoted by 43 (6th april 2017, 4 am), written by ArgentSun on 2008/10/10 (Patch 3.0.2), www.wowhead.com/npc=29311/herald-volazj#comments:id=401534

The situation is during a 5 player fight which equals 4 clones per player for a total of 20 clones.

Did I include the description of what is happening?
Refer in the steps to reproduce the bug.

Did I include NPC/Item/Spell names (or IDs) from wowhead.com or Armory?
Herald Volazj: http://www.wow-mania.com/armory/?npc=29311
Castable "Insanity": http://www.wow-mania.com/armory/?spell=57496
Phase 16 "Insanity": http://www.wow-mania.com/armory/?spell=57508
Phase 32 "Insanity": http://www.wow-mania.com/armory/?spell=57509
Phase 64 "Insanity": http://www.wow-mania.com/armory/?spell=57510
Phase 128 "Insanity": http://www.wow-mania.com/armory/?spell=57511
Phase 256 "Insanity": http://www.wow-mania.com/armory/?spell=57512
I am aware that I do NOT know the IDs of the clone's NPCs.

**Comment by elagen** [comment]
The only bug there might be is 1 extra clone - but that is not a problem 

When going into the insanity phase you DO get a clone of ur extact character with your name 

Insanity - At around 66 and 33 percent health, Herald Volazj becomes invulnerable and applies a debuff to the entire party. Similar in nature to phasing, each individual member sees hostile copies of their original party. Clones have about 4k hp each and must all be killed. Once an individual player's copies are dead, you lose the Insanity debuff and can begin assisting other members to kill their own hostile clones.

http://wowwiki.wikia.com/wiki/Herald_Volazj

that is how it should be
