### ISSUE TITLE
[Spell] Focus Magic

### ISSUE THREAD

**Issue by philoudu16** [WoWManiaUK/Redemption#1057]
Since this morning, focus magic (http://wotlk.openwow.com/spell=54648) counts as a debuff when i buff a party member. It still procs (i get extra crit when the buffed member crits) but trigger happy dispellers can easily remove it if they are not careful (or special mobs, or aoe dispels etc).

On this photo I fm'ed a fellow mage and asked him to fm me to check if it was only on my end.
![image](https://cloud.githubusercontent.com/assets/23452669/24746274/cdb9fcf6-1ab8-11e7-98e7-161ad0c42277.png)

(The client was started via the launcher and the issue is new.)

**Comment by philoudu16** [comment]
Soulstone resurrection is seen as a debuff aswell (less of a problem since it can not be removed by any dispel).

**Comment by philoudu16** [comment]
Not sure if related (and if fixed on dev) but shaman totems were buffing enemies as well.

**Comment by fvicaria** [comment]
Yes. :)

**Comment by philoudu16** [comment]
Okay :) thanks for the quick fix! :)
