### ISSUE TITLE
Quest dont works

### ISSUE THREAD

**Issue by sperezm97** [WoWManiaUK/Redemption#1058]
I do not work with the Blasted Lands missions, I matched them in gray color as if I lacked some mission requirement or as if it were incomplete.
This is the list of missions:
To boar'sVitality
Infallible mind
Snickerfang jowls
The decisive Striker
Vultore's virgor

**Comment by fvicaria** [comment]
Get one by one. You can collect all items but you need to get and deliver one by one.
