### ISSUE TITLE
a flight Master bug

### ISSUE THREAD

**Issue by sperezm97** [WoWManiaUK/Redemption#1059]
the flight master of Wintersrping doesnt work.

**Comment by elagen** [comment]
https://github.com/WoWManiaUK/Redemption/wiki/How-to-Properly-Report-an-Issue

**Comment by elagen** [comment]
If you are Ally --> Everlook, Winterspring --> these are the 2 routes that connect Everlook to other flight paths --> Talonbranch Glade, Felwood & Moonglade

If you are Horde --> Everlook, Winterspring --> these are the routes that connect Everlook to other flight paths --> Moonglade & Orgrimmar, Durotar & http://wow.gamepedia.com/Bloodvenom_Post
