### ISSUE TITLE
[Quest] Barbaric Battlements

### ISSUE THREAD

**Issue by efdede** [WoWManiaUK/Redemption#1060]
Trying to finish : http://mmo4ever.com/wow/quest.php?id=2751

I got all the required items but can't finish the quest.
![wowscrnshot_040617_231518](https://cloud.githubusercontent.com/assets/25913500/24775915/0fff58e8-1b1f-11e7-9583-f8f3194ae120.jpg)

**Comment by Feryk** [comment]
Could not reproduce: https://youtu.be/VyihKmYCxbM

Please try simply abandoning the quest and re-taking it.  If this continues, please open a GM ticket in-game.
