### ISSUE TITLE
[Spell] Death Coil

### ISSUE THREAD

**Issue by LimitlessPain** [WoWManiaUK/Redemption#1061]
Sorry for noticing this late, but in a previous milestone (34) Death Coil underwent an update (#910) that was pushed through due to insufficient info on the matter, and I would like to take the opportunity to report and repair it.

The tooltip of death coil is flawless in game, as such the amount it is supposed to heal is 300% of the damage done. /Tooltips are part of the 3.3.5a patch (or a previous one) and as such are a 100% more reliable than openwow./

However there is a problem with death coil even now which is **the amount it heals is received twice instead of once**. This issue was present back when the healed amount was reduced, which would explain the matter with full healing as the total sum would be 600% of damage healed. Right now due to the issue it heals for 200% (instead of the intended 100%).

**Death Coil - SpellID: 47860**

I have taken a screenshot but cant upload it due to some error.
Extract from combat log (as it appears):
[caster] casts Death Coil at [target].
[caster]'s Death Coil heals [caster] for [amount].
[caster]'s Death Coil heals [caster] for [amount].
[caster]'s Death Coil hits [target] for [amount] Shadow.

Take note that even combat log lists 2 healing effects.

After conducting a couple of tests I finally scored a critical shot with death coil, and I got the following result:
(combat log)
[caster] casts Death Coil at [target].
[caster]'s Death Coil heals [caster] for [amount.1]. - healing amount **same as standard hit** damage.
[caster]'s Death Coil heals [caster] for [amount.2]. - healing amount **corresponding with critical** damage.
[caster]'s Death Coil hits [target] for [amount.2] Shadow. (Critical)

From the 2 heals only 1 is corresponding to the critical amount, the other is the same as a non-critical hit.

**Comment by Feryk** [comment]
Which spell rank is your Death Coil?

**Comment by Feryk** [comment]
At Rank 6, Death Coil says it heals for 300% of the damage done.  I ran a quick test on this and hit a target for 339, but was only healed for 251+376, which is about 185% of the damage that it did.

**Comment by LimitlessPain** [comment]
Ranks make no difference on the healing you are supposed to receive as its always 300% - supposed to be.
I conducted tests with 0 spellpower and no buffs. The damage I get is always 880 and I get healed for 880 +880. Except when critting as that time I hit for 1320, and got healed for 1320+880.
It is supposed to be 880 or 1320 at the moment as its set to heal for 100%, but it heals twice making it 200% total (not the case if it crits).
I did the test on the boss dummy multiple times getting the same damage and healing all the time (rank 6 btw).
Take note that affliction talents influence the damage and healing done.

**Comment by LimitlessPain** [comment]
Summing up whats wrong with Death Coil:

Death Coil should **heal the caster for 300% of the damage done**,

but **the healing done by it is received twice** (appearing in combat log twice too).

The duplicate healing effect should be removed, the healed value should be 3 times the damage done.
(without modifiers to healing done/received)

**Comment by LimitlessPain** [comment]
The spell was modified again, but its still not working as intended.

Am I supposed to make a new post for it again?

Regardless,
As I have said on multiple occasions death coil should heal the caster for 300% of the damage done on patch 3.3.5a. Not 100%, that is Retail - after NERF in later patch.

The double healing effect doesn't work either as a solution.
Reason:
Death Coil crits
![wowscrnshot_051317_004211e](https://cloud.githubusercontent.com/assets/25713713/26019736/16aec848-3778-11e7-9a67-8276a088fe96.jpg)
1320 does not under any circumstance equal 440+660
I have mentioned this previously, only one of the healing effects are corresponding to the actual damage dealt in case of crits.

The way it should look like is:
1320 damage done, 3960 points healed
![wowscrnshot_051317_004211ex](https://cloud.githubusercontent.com/assets/25713713/26019794/a01ba574-3778-11e7-84e8-655458ce50f3.jpg)
The in-game tooltip is the correct one for 3.3.5a patch.
