### ISSUE TITLE
[Raid] Rotface

### ISSUE THREAD

**Issue by philoudu16** [WoWManiaUK/Redemption#1062]
During the Rotface encounter, the boss should occasionnaly turn towards a random raid member, and after a cast timer, starts spraying a cone in front of him (ie towards the random raid member he chose) as u can see in https://www.youtube.com/watch?v=v0St5xnlifM. 
This is a link to 10nm version of the spell i believe http://wotlk.openwow.com/spell=69507.

However, on the server, the spray cone is constantly towards the tank member. The boss turns around correctly to face a random raid member, but he still sprays in a cone towards the tank, which makes the fight easier than intended.

**Comment by Feryk** [comment]
http://world-of-warcraft.alteredgamer.com/wow-raiding/83050-raiding-icecrown-citadel-rotface-25-and-10-man-regular-mode/

"Rotface also regularly does a Slime Spray. He will target a random raid member and turn toward them, then do a cone AoE of slime in that direction."

Confirmed: https://youtu.be/45D8UXp-vNQ

It looks like Rotface is properly turning towards the random non-taunt player.  However, the Slime Spray still hits the player with the most aggro.

**Comment by Feryk** [comment]
Still broken in Dev.

**Comment by Feryk** [comment]
Slime Spray was cast a few times but was only directed towards the tank.  This instance is different however, as Rotface never turns towards another party member. https://youtu.be/YvEIVkptuKE

**Comment by Feryk** [comment]
There are a few upstream posts about this.

https://github.com/TrinityCore/TrinityCore/issues/2947
https://github.com/TrinityCore/TrinityCore/issues/6596

6596 might provide some relief:

`// Slime Spray - temporary here until preventing default effect works again
// added on 9.10.2010
    case 69508:
    {
            if (caster)
            {
                    caster->SetFacingToObject(target);
                    caster->CastSpell(target, triggerSpellId, true, NULL, NULL, caster->GetGUID());
            }
            return;
    }
// Summon Templar, Trigger
        case 24745:`

**Comment by VA-L** [comment]
> There are a few upstream posts about this.

TrinityCore/TrinityCore#2947
TrinityCore/TrinityCore#6596

6596 might provide some relief:

Please don't suggest things when you don't exactly know what they do.
We know what to do. Plus, this is from 2010.

**Comment by Feryk** [comment]
Rotface no longer casts Slime Spray with the latest dev. fix.

**Comment by AdultswimKoda** [comment]
Still turns towards the raid  visual glitch
