### ISSUE TITLE
[raid] Lady Deathwisper

### ISSUE THREAD

**Issue by Unstoppablee** [WoWManiaUK/Redemption#1063]
We were in ICC 10 nm when we realized that we can't kill this boss. When we damage bosses mana, it resets from 50% to 100% or from 0% to 100%, and over and over again. Some people told me that boss also stuck at 0% and still have shield. Also got this same issue from people in icc10hc and icc25nm. 
On second try we did it in icc10nm, but others give up.

Feryk helped me to test it on dev in icc10nm and we got same results. 

http://www.wowhead.com/npc=36855/lady-deathwhisper

**Comment by Feryk** [comment]
Confirmed: https://youtu.be/I_6Pzi6B9Kk

I think the issue here is that her spells use too much mana and the game just resets it when she hits a low amount.  Looking at Retail videos, her mana goes down very little at a time: https://www.youtube.com/watch?v=VNAX1wqfSHU

**Comment by elagen** [comment]
I can confirm that when testing this boss - i had done pure dps NO GM spells - when i Got to 0% on the mana shield -- the mana shield HAD reset going back to 100%

http://www.wowhead.com/spell=70842/mana-barrier

**Comment by philoudu16** [comment]
Somehow we managed to get through this evening after a few resets... I remember some adds spawning shortly before she entered p2, so maybe she doesnt bug out if the dps is low enough. (this may not be true at all but if it works, it can at least save a few raids before a fix is pushed)
