### ISSUE TITLE
[Spell] Vile Gas

### ISSUE THREAD

**Issue by LimitlessPain** [WoWManiaUK/Redemption#1064]
In ICC 10 heroic mode (and probably 25 hc too) the
**Vile Gas**, (ID 72272?)
that is cast from time to time at Rotface's (ID: 36627) encounter, has **wrong flags** as it should only be able to hit players,
but currently it can hit pets and moreover totems, making them an effective death zone if anyone near them is hit by vile gas,
as they receive damage from their own debuff and an additional 4 from the totems effectively one-shoting any player in the vincinity.
Totems are supposed to be ignored by any and all AoE effects.

**Comment by philoudu16** [comment]
I happen to have a screen shot of some recount data if needed:
http://imgur.com/a/KpzlY
