### ISSUE TITLE
[Talent] Improved Faerie Fire/Misery stacking the hit bonus

### ISSUE THREAD

**Issue by philoudu16** [WoWManiaUK/Redemption#1065]
The priest's misery and the druid's improved fire are both debuffs that increase the target's chance to get hit by spells by 3% (which results in giving casters 3% extra hit rating against this target). These two talents should not stack since 3.0.2. (http://www.mmo-champion.com/threads/612981-Patch-3-0-2-On-Debuffs-Buffs-and-Raid-Stacking).
However I wanted to test if the two talents did on the server so i did some tests on a raid boss level target dummy with a friend (for which u need a total of 17% hit rating to not get a single miss).

With my mage's 11.8% hit rating (own talents including) and his lock's 12.9% hit rating, we both casted over 400 spells each on a target that had both the debuffs and none of us had a single miss.
However including the debuffs on the dummy i should have missed about 2.2% of my spells and the lock should have missed 1.1% of his, so we should have had around 13 misses total.
I know, it's stats and rng, so we may be two very lucky ppl. But 0.978^400*0.989^400 = 0.000001637 which is the probability we would both miss 0 times. I doubt we're that lucky somehow...

So I guess they do stack, which they should not.

Link to the two spells (talented):
http://wotlk.openwow.com/spell=33602
http://wotlk.openwow.com/spell=33198

**Comment by elagen** [comment]
The Spells are Simular even with Improved Faerie Fire - but u will only Gain 3% hit Rating not 6% if you are talking about that 

With nothing On the Dummy
![wowscrnshot_041117_101159](https://cloud.githubusercontent.com/assets/22685042/24901633/9f6a3984-1e9f-11e7-9229-8f9f0646a1c3.jpg)

With Misery on the Dummy 
![wowscrnshot_041117_101209](https://cloud.githubusercontent.com/assets/22685042/24901670/b57b396c-1e9f-11e7-8cba-184fece1765c.jpg)

With Misery and Faerie Fire 
![wowscrnshot_041117_101217](https://cloud.githubusercontent.com/assets/22685042/24901683/bcd54dec-1e9f-11e7-8cdc-5dfb021b73c8.jpg)

as you can see on the left of my screen i have mage nuggets and when u target a mob / boss / npc with any increased buff / debuff that will update and not ur character sheet

**Comment by philoudu16** [comment]
I have Magenuggets as well and indeed it will not show +6% because it SHOULD not stack. 
If you really want i'll go hit a dummy 1000 more times with misery + faerie fire, if you think 0.000001637 is too high of a probability.

**Comment by philoudu16** [comment]
I'm pretty stubborn but not quite enough for 1000 hits, so i stopped at 600:
![image](https://cloud.githubusercontent.com/assets/23452669/24917965/0f3cc3f0-1edf-11e7-9a73-dcd67447a742.png)

Now let's do the maths together:
With no hit bonus at all, you have 83% chance to hit this target dummy. I have 11.34% extra hit. If the two spells did not stack (which they shouldn't), i would have a total of 14.34% extra hit which is what magenuggets shows. This means i have a total chance of 97.34% to hit the dummy. I have hit the dummy 601 times with no miss. If you have ever followed any probability lessons, you will know that the probability of this happening is 0.9734^601=1.0392492e-7 = 0.0000001039... which is roughly one chance in 10 million, and if you had to that my previous tests, it gets it down to very roughly one chance in about 500 billion.
This is absurdly improbable.

So what is most likely happening is that the debuffs are stacking. This would get my hit up to 17.34% which is above hit cap, hence me not missing a single spell.

**Comment by elagen** [comment]
i have also tested this with a boomkin and a Shadow priest - i think RNG plays a lot in this as i will list my results
This is with 8.73% hit Rating

200 Hits without any buff

1st Try - 17 Miss
2nd Try - 18 Miss

200 Hits With Missery

1st Try - 13 Miss
2nd try - 8 Miss

200 Hits With Faerie Fire

1st Try - 9 Miss
2nd Try - 13 Miss

200 Hits With Misery and Faerie Fire
1st Try - 7 Miss
2nd Try - 10 Miss

i do not disagree with you but conducting 2 tests when i Finished the first test i waited 10 mins before starting the Second test

**Comment by philoudu16** [comment]
I guess i'll start raiding under hit cap then when i see we have a shadow priest and boomkin, since the RNG gods seem to be on my side :D
