### ISSUE TITLE
[Item] Ymirjar Lord's Plate

### ISSUE THREAD

**Issue by Grindall** [WoWManiaUK/Redemption#1066]
the second bonus of the prot warrior is a bit bugged.
"Your Bloodrage ability no longer costs health to use, and now causes you to absorb damage equal to 20% of your maximum health. Lasts until cancelled."
Both abilities work, but the damage absorption only lasts 10 seconds instead of until cancelled. The spell buff you get for 10 seconds when you cast bloodrage is called "Stoicism".
http://wow-mania.com/armory/?spell=70845
spell id 70845

**Comment by Grindall** [comment]
please note that this is different from the other t10 warrior bonus ticket as the other one is for fury

**Comment by Feryk** [comment]
https://wow-mania.com/armory/?itemset=-274

**Comment by Feryk** [comment]
Confirmed: https://youtu.be/G4UsLwMEiMs

**Comment by Grindall** [comment]
I'm confused as to why this is closed?

**Comment by elagen** [comment]
http://www.wowhead.com/spell=70844/item-warrior-t10-protection-4p-bonus#comments

It's the same as it was on retail
