### ISSUE TITLE
[Hunter] Pet spawns with ~75% HP when dismounting

### ISSUE THREAD

**Issue by idl0r** [WoWManiaUK/Redemption#1067]
This issue might be related to #994. Each time I dismount, my Pet spawns with about 75% HP. It has some points in increased life but no 25%. Also, it should spawn with 100%, even if it has increased life through some skill points.

My current pet even spawns with just 67% of it's total HP.
![wowscrnshot_040117_152822](https://cloud.githubusercontent.com/assets/32827/24798003/240b1f3c-1b94-11e7-907a-3f8a469a2e9c.jpg)
![wowscrnshot_040117_152826](https://cloud.githubusercontent.com/assets/32827/24798004/240ddb46-1b94-11e7-935c-3c73333a88a8.jpg)
![wowscrnshot_040117_152830](https://cloud.githubusercontent.com/assets/32827/24798005/240e3abe-1b94-11e7-8bf7-e2c193cffbf6.jpg)

**Comment by Feryk** [comment]
Fix confirmed: https://youtu.be/Qq5ZvP4V1uU

**Comment by idl0r** [comment]
Looks good. Thanks!

**Comment by idl0r** [comment]
Oh, btw. the "Cower" ability (last from right) seems to be saved.
