### ISSUE TITLE
[Dungeon] Halls of Reflection

### ISSUE THREAD

**Issue by philoudu16** [WoWManiaUK/Redemption#1068]
During the waves part of the Halls of Reflection dungeon(where u have priests, mages, mercenaries, hunters and footmen activate), this fight seems to sometimes reset (with none of my party members dying). I have no clue what causes it, and it happened to me a few times at different moments in the fight. Last time i remember it happening, it was on wave 9, and this time it was on wave 7. Both those times were on heroic mode, so i am not sure if the same happens in the normal version of the dungeon.
If anyone could confirm with their own experience, it would be appreciated (and will probably help the devs find where the problem is).

**Comment by Feryk** [comment]
How long do each of your waves last?  I have tested this in HC a few times and have not run into this issue.  Do your fights normally last a while?

**Comment by philoudu16** [comment]
Nah they went pretty fast, and it doesn't happen all the time. I noticed this time just before it reset that the mercenary shadowstep and evaded a shot... Might be related, might not.

**Comment by philoudu16** [comment]
This time it was very shortly after the wave had spawned so i dont think it's the individual wave timer. However we did three man Falric after two dps died on wave 4. So it could be a timer issue on the whole fight duration.

**Comment by fvicaria** [comment]
Is this still an issue? is it reproducible?
