### ISSUE TITLE
[Itemset] Ymirjar Lord's Plate

### ISSUE THREAD

**Issue by Feryk** [WoWManiaUK/Redemption#1069]
https://wow-mania.com/armory/?itemset=-274

Per https://github.com/WoWManiaUK/Redemption/issues/1066, the default behavior of the Protection 4P Bonus (http://www.wowhead.com/spell=70844/item-warrior-t10-protection-4p-bonus) is to last 10 seconds, as this is what happens on Retail.  However, the description of the bonus on WoW-Mania states 'until canceled'.

[+] The description of the bonus on the set should be modified to say:

"(4) Set: Your Bloodrage ability no longer costs health to use, and now causes you to absorb damage equal to 20% of your maximum health. Lasts for 10 seconds."

**Comment by hotdoggidy** [comment]
It's labeled the same as in retail. If people want to read into it too much they can waste their time at a dummy and argue all day and night about "it should last until i cancel it" but then where does it stop? an hour later? a day? a week? technically if i dont "cancel" it it should always be up from the first time i use it right?

Elemental Mastery for Shaman has a similar tooltip: 
"**When activated your next Lightning bolt, chain lightning or lava burst spell becomes an instant cast spell.** In addition, you gain 15% spell haste for 15 sec. Elemental mastery shares a cooldown with nature's swiftness"
When you use Elemental mastery u get 2 buffs for 15 sec, 1 causes ur next spell (listed above) to be instant, the other gives spell haste. If u wait for instant the buff to run out you can no longer cast your spell as an instant. Even though the tooltip says nothing about a duration.

This is the same kind of READING issue someone must have had with the prot 4-set. They read it how THEY want to hear it. NOT how it was meant to be read.

I dont think this change is necessary. if a player is confused about it WoW-mania has a knowledgeable and willing community.
