### ISSUE TITLE
[Item] Conjured Mana Strudel

### ISSUE THREAD

**Issue by idl0r** [WoWManiaUK/Redemption#1070]
Hi,

we were just in a hero dungeon (I am not sure if that's related) and got some [Conjured Mana Strudel](http://www.wowhead.com/item=43523/conjured-mana-strudel) and it doesn't reg as many mana as the description says. We tried it with several guys and it seemed to only work for the mage. In my case, Hunter, Level 80, around 11k mana and description says it will regenerate 19200 but it ended at around 75% when I started to use it as of around 45%. I am not sure if that's broken only inside of dungeons. I also don't know if hp regeneration is also affected.

**Comment by philoudu16** [comment]
I tested it out a little on my mage, and the amount of mana i seem to get out of them (when i check mana regen on my char sheet) seems to vary with my total mana pool. So they may currently be giving a certain % of mana per second instead of a fixed value.

**Comment by Feryk** [comment]
https://wow-mania.com/armory/?item=43523

I set my mana to 19200 and drained it normally before using a Conjured Mana Strudel.  After waiting the full 30 seconds, my mana had nto been completely filled.

https://youtu.be/kjky7XA4WlM

**Comment by idl0r** [comment]
Works. Thank you!
