### ISSUE TITLE
[Profession] Skinning in Heroic Dungeons Doesn't Work

### ISSUE THREAD

**Issue by idl0r** [WoWManiaUK/Redemption#1071]
Hi,

skinning in all? heroic dungeons I was in didn't work while it worked in normal mode.

**Comment by Feryk** [comment]
Normal HFR: http://i.imgur.com/iqQiqPn.jpg
Heroic HFR: http://i.imgur.com/T4Z8nvc.jpg

**Comment by Feryk** [comment]
![wowscrnshot_040817_113750](https://cloud.githubusercontent.com/assets/25799466/24830244/e0bf119a-1c4f-11e7-8e6b-1af4f128d594.jpg)

**Comment by idl0r** [comment]
Works. Thanks!
