### ISSUE TITLE
[Profession] Skinning Problem

### ISSUE THREAD

**Issue by Ebonlox** [WoWManiaUK/Redemption#1072]
My wife and I spent about an hour playing today, both on our Skinning characters. We were able to go through the motions of skinning beasts, but never got any leather or hide for our efforts. Dozens of attempts including Re-logging and Client restarts with no success.

**Comment by Feryk** [comment]
- What this within Normal or Heroic dungeons?
 - Was it in normal zones?
 - Which zone were you in?
 - What was the name of the mobs?

**Comment by fvicaria** [comment]
We are aware of this and will be fixed by tomorrow morning.

**Comment by Feryk** [comment]
I wasn't sure where this issue happened at exactly, so I tested in Dun Morogh, Durotar, Desolace, Hellfire Peninsula and Dragonblight and found Fel Hide, Light, Heavy and Borean Leather.

**Comment by Ebonlox** [comment]
I was in Howling fjord. My wife was in ungoro crater. She was trying all
manner of dinosaurs. I tried a few chimarae just to see if it was a local
problem with her. It was exactly the same where i was.
