### ISSUE TITLE
[Hunter] Pet abilities locked after dismount

### ISSUE THREAD

**Issue by idl0r** [WoWManiaUK/Redemption#1075]
Hi,

this is a regression, might be caused by #1067. All pet abilities are locked each time you unmount.

**Comment by Feryk** [comment]
Could you let me know what you mean by "locked"?  I tested this with a couple of mounts/dismounts and did not see any problems: https://youtu.be/1y20sHrLtZw

**Comment by Feryk** [comment]
We'll need more information to be able to properly test this issue.  If you can provide screenshots and detailed information about what's broken, feel free to open a new bug.

**Comment by idl0r** [comment]
I will post a screenshot later this evening. But what I mean ist, the ability Buttons like Growl etc. are locked. You have to right-click first to enable it, each time you dismount. That wasn't the case before the last update. It used to save the state when mounting and restored it when dismounting.

**Comment by fvicaria** [comment]
I have just checked also and all abilities are enabled fine after dismount. Closing wow delete cache and disable addons just as a test.

**Comment by idl0r** [comment]
Deleting the cache didn't help. See the attached image
![1075](https://cloud.githubusercontent.com/assets/32827/24874461/0cf99cf4-1e25-11e7-834a-a43ec4627ee8.png)

**Comment by fvicaria** [comment]
I will try again and get back to you.

**Comment by idl0r** [comment]
Hm, the right one (I forgot the name) will be saved, just those three left ones aren't.

**Comment by idl0r** [comment]
@fvicaria ping

**Comment by fvicaria** [comment]
Can you try this on the PTR server please?
I had a couple of people saying they had the same problem but only with some pets not all.
Send me a message on skype and I can join you there.

Skypename: wow-mania.com

**Comment by fvicaria** [comment]
This is a very minor issue. I had a look and I will park it for now. I will come back when I have more time.

**Comment by idl0r** [comment]
Oh, btw. the "Cower" ability (last from right) seems to be saved.
I can reproduce it on Dev with the pet "[Cavedweller Worg](https://www.wow-mania.com/armory/?npc=30164)"
