### ISSUE TITLE
[Quest] A Pawn on the Eternal Board

### ISSUE THREAD

**Issue by tsuff** [WoWManiaUK/Redemption#1076]
In quest http://www.wowhead.com/quest=8519/a-pawn-on-the-eternal-board you are supposed to watch a battle in the end of wich after a short conversation your quest should complete but it is not. Sry if my explanation is a bit hazy but in short that is what should happen.

**Comment by Feryk** [comment]
Confirmed: https://youtu.be/7DJDk56ycq4

While this is a confirmed bug, please open a ticket in-game and a GM should be able to complete this for you manually.

**Comment by tsuff** [comment]
Already taken care off, thank you. I`m only trying to help posting it too (even with that explanation).
