### ISSUE TITLE
 [Glyph] Glyph of Ice Block

### ISSUE THREAD

**Issue by Drogger** [WoWManiaUK/Redemption#1077]
spell effect - Your Frost Nova cooldown is now reset every time you use Ice Block.
This is failing to proc.

**Comment by elagen** [comment]
Confirmed that when you have http://wow-mania.com/armory/?item=42744 

and you use http://wow-mania.com/armory/?spell=42917 (frost nova) - when this is on cooldown
and you use http://wow-mania.com/armory/?spell=45438 (ice Block) - this should Reset the cooldown on your frost nova

this is NOT happening - the Frost nova is still on Cooldown
