### ISSUE TITLE
[Spell] Mage - Cone of Cold

### ISSUE THREAD

**Issue by SatteliteJim** [WoWManiaUK/Redemption#1078]
Hello ive been trying to talk to ingame gm about this bug/glitch, game master actually sent me here to post so here i am. ive had some issues with cone of cold i tried different positions ,while jumping,while facing the ground etc   , but this cone of cold only appears in the left of my mage character never in front of my character , visual defect i think ?i almost forgot the spell hits the target even tho it only shows on the left side of my char

**Comment by Anthonhed** [comment]
Could you please add spell id's and how it should work, check https://github.com/WoWManiaUK/Redemption/wiki/How-to-Properly-Report-an-Issue so you know how to properly report an issue

**Comment by elagen** [comment]
This is just a visual Defect - it looks like it only hits the left of the animation when casted - but it is still hitting the mobs like it should as if it was standing just to the right
