### ISSUE TITLE
[Raid] Ulduar Kologarn

### ISSUE THREAD

**Issue by philoudu16** [WoWManiaUK/Redemption#1079]
This issue is related to the Kologarn encounter in Ulduar : http://www.wowhead.com/g00/npc=32930/kologarn
He will randomly pick up a target with his right arm using the Stone Grip ability (http://www.wowhead.com/spell=64290/stone-grip). The other raid members need to kill the arm to free the gripped player.
However, on the server, when the arm is killed, the players will be dropped at the feet of the boss, in a small zone you can not get out of, instead of in front of the torso of the boss where you pull from.

**Comment by VA-L** [comment]
Is it when you really killed it or when you do the required damages to release the concerned player?

**Comment by philoudu16** [comment]
Good point, the arm was only releasing the player when we killed it, rather than after taking 150k damage as it should be on 10 nm.

**Comment by elagen** [comment]
I can confirm that when a player is Stone Gripped http://www.wowhead.com/spell=62166/stone-grip

The are does need to Take 150,000 Damage to Release the Player in 10 Man
In 25 Man The Arm needs to Take 450,000 Damage to Release the Player(s) 

As philoudu16 - Atm you need to KILL the arm to Release the people Gripped when it only needs to take a certain amount of Damage to Release the target
