### ISSUE TITLE
[Raid] Gothik the Harvester - Invisible attackers

### ISSUE THREAD

**Issue by Feryk** [WoWManiaUK/Redemption#1080]
From https://github.com/WoWManiaUK/Redemption/issues/1074, there was a report of someone taking damage from unknown sources.  While testing the gate issue in 1074, we found the invisible attackers.

https://youtu.be/32jWB522HI4

**Comment by Feryk** [comment]
They still seem to be spawning invisible to normal players: https://youtu.be/RFIGlFihgsc

**Comment by philoudu16** [comment]
Either this is fixed already (on red) or it does not happen every time. This time the fight happened exactly as it should ( no invis mobs, and the gates opening when the boss reaches ~30%)
