### ISSUE TITLE
[Quest] A lesson to Fear

### ISSUE THREAD

**Issue by squalllh1989** [WoWManiaUK/Redemption#1082]
In the quest : http://www.wowhead.com/quest=11282/a-lesson-in-fear , you have to kill 3 mob and then Impale their coprse with the banner, but Ulf the Bloodletter never spawned, as i sit there wait for him for 1 hour and no trace of him arround the area which he should be, the other 2 do spawn, but dispapear after a while for no reason ( they suppose to be stand there is no one kill them, right ?)

**Comment by fvicaria** [comment]
![image](https://cloud.githubusercontent.com/assets/9414661/24879082/90c2f4d8-1e2d-11e7-887e-8b7e8acdf52f.png)
