### ISSUE TITLE
unknown bug which give 95% chance on dodge and parry

### ISSUE THREAD

**Issue by Kairaska** [WoWManiaUK/Redemption#1083]
so while i was playing i just notice that the mob barely hit me. after i check my stat it tells me that i have 95% chance on dodge and parry. 
not only it show some number but i try to fight a skull lvl mob and they can't hit me as well.
this miss chance also happen on new character i created.
sure if you death it will be fixed.
but if i enter battle to some mob it will be bugged again.
this is kinda ruining the fun.
maybe someone can fix it or figure what happen.
![wow bug](https://cloud.githubusercontent.com/assets/27282848/24907686/6adfb0d4-1ee7-11e7-8d6a-e1396e3d33ed.png)

**Comment by Anthonhed** [comment]
Have this bug happen to any other player?
Does it happen everytime you go in combat?
