### ISSUE TITLE
[Monster] Private Hendel

### ISSUE THREAD

**Issue by rotgurd** [WoWManiaUK/Redemption#1084]
Am I using our client? **Yes**
Am I using the latest Launcher? (Note: don't even open issue if not) **Yes**

Did I include the steps to reproduce the problem? **Yes**
1st test - above 8x tries
Impossible to kill it, because it keep reseting.
I tried to use my max fireball range to start it, when he starts to run I tried finish with Fire Blast.. miss.
Even tried to hold him in position with Frost Nova, miss too.

2nd test - beside the npc
I tried to stay beside him (as the Gm asked to test), still resets without running.

![immortal](https://cloud.githubusercontent.com/assets/27322347/24937788/74cd57a0-1f09-11e7-83ac-abf90973a975.jpg)

As far I know this not a quested npc, I just randonly tried to kill it. And for my surprise it was bugged lol.

**Comment by Anthonhed** [comment]
What is the NPC ID

**Comment by fvicaria** [comment]
You are not supposed to kill it. He will surrender and enter evade mode.
You need the quest.
http://www.wow-mania.com/armory/?npc=4966#ends
