### ISSUE TITLE
Hunter pet small on lvl 80

### ISSUE THREAD

**Issue by Skyler1** [WoWManiaUK/Redemption#1085]
Hey to Janitor and GM'S i logged in this morning seeing that my hunter pet is small again like on level 10 but its level 80 all of the stats is still the same but the size is whey off. i logged off and back in and it was fine again maybe a small bug but just wanted you to know have a great day your truly Darkhunter

**Comment by fvicaria** [comment]
I need images and more details so we can try to reproduce it

**Comment by elagen** [comment]
https://github.com/WoWManiaUK/Redemption/wiki/How-to-Properly-Report-an-Issue

**Comment by fvicaria** [comment]
I need more info on this. I cannot reproduce.
