### ISSUE TITLE
[Professions] All professions give gold

### ISSUE THREAD

**Issue by 10centsoviet** [WoWManiaUK/Redemption#1087]
Milling plants does not result in expected pigments, but results in a (relatively) large sum of gold. Tested with Mageroyal and Silverleaf, resulted in 5g45s28c each time (both attempts were identical). Was milling off and on most of the day yesterday and had no issue with it, but as of aprox. 12:00 server time, results have been only gold. Will edit or reply with more tests (of both previously mentioned plants and new plants).

**Comment by Anthonhed** [comment]
Is this the same as the enchanting bug?

**Comment by Anthonhed** [comment]
This is a known bug, it applies to all proffesions and it's being fixed at this moment

**Comment by Anthonhed** [comment]
Milling, prospecting etc gives gold.

**Comment by philoudu16** [comment]
According to what I've seen and heard, openable containers (like daily quest reward bags, rare northrend mob bags etc) seem to be affected too.
