### ISSUE TITLE
Disenchant reward gold instead of enchanting material

### ISSUE THREAD

**Issue by squalllh1989** [WoWManiaUK/Redemption#1088]
After the restart at 12:00 ST today (13/4/2017), when i use disenchant on item, it turn into gold, not enchanting material, and what ever level the item is, low or high, it still turn to 5 gold, 45 silver, 28 copper. Some low level enchanter already know this and started to abuse this bug to get easy gold on their level, while high level enchanter lost their green, blue item that they have to farm hard to get material to leveling their profession or enchanting their gear.

**Comment by Anthonhed** [comment]
This goes with an already open issue https://github.com/WoWManiaUK/Redemption/issues/1087
