### ISSUE TITLE
Icecrown mob bug

### ISSUE THREAD

**Issue by iskense** [WoWManiaUK/Redemption#1092]
there is a njorndar mob can you can not target nor deal damage to him. He is locate in njorndar village in icecrown. location (27.45 , 38.31)

thank for hard work

**Comment by Anthonhed** [comment]
Please log the issue properly https://github.com/WoWManiaUK/Redemption/wiki/How-to-Properly-Report-an-Issue
*Include NPC ID from WoWHead*

**Comment by fvicaria** [comment]
![image](https://cloud.githubusercontent.com/assets/9414661/25062049/07256444-21bc-11e7-88fa-109fecaead53.png)
Found and fixed in dev. Thank you.
