### ISSUE TITLE
[Quest] The Focus on the beach

### ISSUE THREAD

**Issue by squalllh1989** [WoWManiaUK/Redemption#1093]
This quest require me to kill captain emmy marlin  near the ley line focus on the beach in dragon blight,  (http://www.wowhead.com/npc=26762/captain-emmy-malin) the quest item, Ley Line Focus Control Ring (http://www.wowhead.com/item=36751/ley-line-focus-control-ring) should have drop with the rate of 85%, and i killed her 5 times already and still no quest item drop. (after the 2nd try, i already think there is something wrong with the drop rate, so i decided to make a ticket, and a gm require me to come and kill him again, still no loot, he ask me to put the problem here with screen shot of the quest log and the loot also) the screen shot here is on the 4th try, the last one is the 5th try's loot.
![wowscrnshot_041517_001823](https://cloud.githubusercontent.com/assets/27235989/25050654/e0129c3a-2172-11e7-93f1-c88c3c8ba6c8.jpg)

![wowscrnshot_041517_001835](https://cloud.githubusercontent.com/assets/27235989/25050659/e5cf880e-2172-11e7-8143-ee045fe2afc2.jpg)

![wowscrnshot_041517_001944](https://cloud.githubusercontent.com/assets/27235989/25050663/eadfc228-2172-11e7-847f-882a99582cb9.jpg)

![wowscrnshot_041517_001951](https://cloud.githubusercontent.com/assets/27235989/25050665/eeb4d8fc-2172-11e7-8159-f52e1283273d.jpg)

![wowscrnshot_041517_002631](https://cloud.githubusercontent.com/assets/27235989/25050667/f5d636b2-2172-11e7-89e1-688bee9740e2.jpg)

**Comment by squalllh1989** [comment]
I got it on the 6th try, maybe i was just unlucky ?

**Comment by hotdoggidy** [comment]
Tested on Frostmourne and dropped 1st kill. Tested on Redemption also dropped 1st kill. Cannot reproduce.
