### ISSUE TITLE
[Quest]  The Fate of Flanis

### ISSUE THREAD

**Issue by firehawk2k2** [WoWManiaUK/Redemption#1094]
Quest ID#10583

NPC ID#21727  "Flanis Swiftwing" does not have the option to receive the quest item ID# 30658 [Flanis' Pack]

**Comment by hotdoggidy** [comment]
Flanis Swiftwing with no interaction for quest.
![wowscrnshot_041517_051645](https://cloud.githubusercontent.com/assets/23442126/25063510/d1ee9406-219a-11e7-9d71-ba12b91ba9a4.jpg)

**Comment by hotdoggidy** [comment]
might be cuz hes still alive? just to compare. here is the Horde equivalent. "dead"
![wowscrnshot_041517_052009](https://cloud.githubusercontent.com/assets/23442126/25063523/3f20faf0-219b-11e7-840b-9ce4d2b6f506.jpg)

**Comment by hotdoggidy** [comment]
https://www.youtube.com/watch?v=1W8xJavnB_w 

1:30 into video. Shows Flanis "dead".

**Comment by firehawk2k2** [comment]
I did not notice his health, alive/dead, Will try again soon.
