### ISSUE TITLE
[Quest] It Rolls Downhill

### ISSUE THREAD

**Issue by JFoxxo** [WoWManiaUK/Redemption#1095]
In this quest, [Drakuru] in Zul'Drak (Voltarus) wants you to use a [Scepter of Suggestion] to control a [Blight Geist] and have it harvest [Blight Crystals]. Normally, after controlling the geist you click the command to have them harvest a crystal, and they do so. However, currently they aren't responding to the command to harvest a crystal and simply do nothing. I've tried it a few times but each time I encounter the same problem. 

Thank you! My Username in-game is [JFoxxo], and my main character [Foxxo], in case you need to contact me for further details.

**Comment by fvicaria** [comment]
Quest works. Just stay by the ramp.
