### ISSUE TITLE
Stranglethorn Fishing Extravaganza

### ISSUE THREAD

**Issue by Jangluur** [WoWManiaUK/Redemption#1096]
Hey GM's, the STV Fishing Extravaganza is broken, or at least is for me? I was able to catch the 40 Tastyfish in time and headed to Booty Bay, but the fishing master who runs the event has the same textbox as before the event started (which has no clickable links on it, just flavour-text about the next Sundays event (which is his 24/7 text)), and so I cant turn in anything or complete the contest. This achievement (Master Angler of Azeroth I believe its called) is the last one before I get "Salty", and would love it for a solution to this bug to be found :) Cheers

**Comment by fvicaria** [comment]
Please add the link to the NPC and the quest.

Please follow the procedure described below before creating a new issue:
[How to Properly Report an Issue](https://github.com/wow-mania/Redemption/wiki/How-to-Properly-Report-an-Issue)

This will help developers identify and fix the issue quicker. Incorrectly or unclear reports will simply be deleted.
