### ISSUE TITLE
[Achievement] Zombie Fest

### ISSUE THREAD

**Issue by Readerlady** [WoWManiaUK/Redemption#1097]
To complete this achievement you must kill 100 zombies in less than 1 minute. http://www.wowhead.com/achievement=1872/zombiefest
To do this you have to round up all the respawned ones from the first part and kill them as you kill the others after the third boss. The first ones DO NOT Respawn EVER. No matter what.

**Comment by Anthonhed** [comment]
Did you kill the 2nd boss?
§ After the 2nd boss DIES the zombies in the beginning (before you enter into the inn) will stop respawning.

**Comment by Readerlady** [comment]
We pulled the second boss into the building but did not kill it waiting for the respawns. We waited well over three minutes. We used the usual strat 
from retail.
