### ISSUE TITLE
[Quest] Parts for the Job

### ISSUE THREAD

**Issue by AtlasRedux** [WoWManiaUK/Redemption#1099]
Droprate seems to be way off.
According to Lightheaded/WoWHead it's supposed to be around 50%.
It feels like it is 5%. Though I don't have exact statistics on it, it's definitely not correct ACCORDING to Lightheaded/WoWHead.
Though they might be wrong as well of course.

**Comment by elagen** [comment]
i Have just done this Quest with no problem http://wow-mania.com/armory/?quest=11309

The Drops are lower then what wow head says http://wow-mania.com/armory/?item=33611

http://wow-mania.com/armory/?npc=24291
