### ISSUE TITLE
[Spell] Spell Reflection-Warrior

### ISSUE THREAD

**Issue by hotdoggidy** [WoWManiaUK/Redemption#1100]
Spell reflection (spell=23920) lasts 5 seconds and should reflect the first spell cast at the warrior before dissipating. Currently on Red it lasts 5 seconds but reflects ALL spells cast for the duration. 

Tested with duel. 4 spells cast at the warrior with spell reflection active, all 4 spells returned damage. 

http://www.wowdb.com/spells/23920-spell-reflection

**Comment by fvicaria** [comment]
Please use our Armory or Wowhead as references.
