### ISSUE TITLE
[Raid] Vault of Archavon Masterloot problem on fire boss

### ISSUE THREAD

**Issue by squalllh1989** [WoWManiaUK/Redemption#1101]
The fire boss in VOA have problem, when you use masterloot to kill it, you can't pick up the loot.

![wowscrnshot_041917_160104](https://cloud.githubusercontent.com/assets/27235989/25172160/5c6943f6-251a-11e7-8adc-2cce4a0e631e.jpg)

**Comment by fvicaria** [comment]
Fix is in the PTR. Feel free to test it.
