### ISSUE TITLE
[talent] Nature's Guardian

### ISSUE THREAD

**Issue by dontfkwithpvp** [WoWManiaUK/Redemption#1102]
Resto Shaman talent is not working at all

**Comment by elagen** [comment]
Please next time  Read https://github.com/WoWManiaUK/Redemption/wiki/How-to-Properly-Report-an-Issue FIRST

i have Tested the Talent Nature's Guardian http://wow-mania.com/armory/?spell=30886 Works

![wowscrnshot_042117_131605](https://cloud.githubusercontent.com/assets/22685042/25277061/1209752a-2695-11e7-9cdb-aa139ba3a66d.jpg)
