### ISSUE TITLE
Sons of Hodir Reputation bugged

### ISSUE THREAD

**Issue by Tegiz** [WoWManiaUK/Redemption#1105]
Hi, Right now i am on the quest "Krolmir, Hammer of Storms" and i can't complete it due to me not having the required reputation able to do it. I have to do a quest from King Jokkum to be able to get the required reputation but there is no quest from him. Watch the Gyazo and you will see what i mean.

https://gyazo.com/e0cc4bb181c34fa8876a18f913a4450d 
https://gyazo.com/ee61f0cef19f72c76ec0a2a63f6e4f57
https://gyazo.com/9f86a13abafa791acc60966cd8969388

I Hope you can resolve this issue! :)

**Comment by fvicaria** [comment]
Not a big you probably missed or drop a quest along the way. Raise a ticket and ask a GM to help.
