### ISSUE TITLE
[Quest] Flight of the Wintergarde Defender

### ISSUE THREAD

**Issue by Drewnei** [WoWManiaUK/Redemption#1106]
I was able to obtain 7/10 on this quest relatively easily, but now I am unable to pick up any more villagers because they all despawn when I fly down to them.

**Comment by Anthonhed** [comment]
Please log the bug corectly including NPC Id's and quest ID https://github.com/WoWManiaUK/Redemption/wiki/How-to-Properly-Report-an-Issue
