### ISSUE TITLE
[Quest] Into Hostile Territory

### ISSUE THREAD

**Issue by BleakSenpai** [WoWManiaUK/Redemption#1110]
http://www.wow-mania.com/armory/?quest=12325 The quest
http://www.wow-mania.com/armory/?npc=27317 The NPC Urik

Gryphon Commander Urik is supposed to supply the player with a gryphon after they talk to him, unfortunately the NPC has nothing else to offer but to say that the gryphon riders are near him. Regardless, the riders cannot be spoken to, and once you ride the Gryphons near them, nothing happens and you can't control them.
Here's a screenshot of the player trying to do the quest but unable:- http://imgur.com/a/TvV85

Cheers.

**Comment by fvicaria** [comment]
Duplicate #46
