### ISSUE TITLE
[Quest] Twilight of the Dawn Runner

### ISSUE THREAD

**Issue by halgameguru** [WoWManiaUK/Redemption#1111]
Twilight of the Dawn Runner - Dustwallow Marsh, Horde Quest. 
Quest giver and turn in are same NPC in Brackenwall Village: NPC - Balandar Brightstar
Has 2 completion requirements: Recover lost cargo, Rescue Ithania from North Point Tower
Recover Lost Cargo works fine
Rescue Ithania from North Point Tower does not work. Ithania cannot be interacted with. You can left click to select NPC, and voice greeting plays, but there is no interaction to progress the quest. No chat window or change to mouse pointer on Hover. Right click does nothing.

**Comment by halgameguru** [comment]
UPDATE:
reacquired quest, went to her, she was now kneeling rather than standing. Could click on her and proc the chat window. Quest still did not progress, and second Horde player with me could not interact with her afterwards. She was now standing up and not responsive to right-click

**Comment by fvicaria** [comment]
I will check this in the morning.

**Comment by Anthonhed** [comment]
Confirmed on red
