### ISSUE TITLE
Wintergrasp Wall Cannons

### ISSUE THREAD

**Issue by Dusticles** [WoWManiaUK/Redemption#1113]
These cannons xseem to be healing drastically fast when dismounting them... making them a 1 shot attempt or nothing at all. To make matters worse, a elemental shaman could easily dismount cannons and thunderstorm people off the platform giving the turret enough time to heal in the matter of 1-3 seconds of healing to full again; making elemental shamans immortal on these cannons if done right.

**Comment by fvicaria** [comment]
As is.
