### ISSUE TITLE
Wintergrasp vehicles EXA. Seige Engines

### ISSUE THREAD

**Issue by Dusticles** [WoWManiaUK/Redemption#1114]
Seige engines appear to be sharing the same bug of tenacity as players do who keep these perks even after having an overwhelming force on their side overpowering the other...but as well as that there is a big issue with these turrets on top of them... being they can bypass the immunity sheild of graveyards, in a sense spawn camping at its finest without repercussion. Can this be fixed so that Vehicles all together cannot kill a immunity shield player at the graveyard?

**Comment by fvicaria** [comment]
Same as the other issue.
