### ISSUE TITLE
Wintergrasp Cannons #2

### ISSUE THREAD

**Issue by Dusticles** [WoWManiaUK/Redemption#1116]
Heya is it alright to increase the spawn rate of tower cannons by 2 mins? This would make ground troops more vital in defenses. Thank you :3

**Comment by fvicaria** [comment]
I will look into this one.

**Comment by fvicaria** [comment]
Is the position still getting worse with time?

**Comment by Dusticles** [comment]
the position does get worse after breaching the first wall...Not because of now dealing with 4 turrets but at the rate those 4 turrets operate over time even with deaths of turrets.

**Comment by Dusticles** [comment]
Also  fvicaria, referring to the *players in wintergrasp* issue I'll make some video evidence for ya to show to ya what i mean by what I typed.
