### ISSUE TITLE
[Quest] Victory Nears...

### ISSUE THREAD

**Issue by Nyssrogh** [WoWManiaUK/Redemption#1117]
Hello!

I Have a little problem about this Quest, because it's Inaccessible. (At least for me)
I Browsed WoWHead, and some folk said this quest should be accessible no problem, but this is not the case somehow.
This Quest also starts a Quest Chain, and without it, the "Might of Dragonblight" Achievement is not possible to complete.

**Comment by fvicaria** [comment]
http://www.wowhead.com/quest=12034/victory-nears

**Comment by elagen** [comment]
I can confirm that for this quest you need to speak to http://www.wowhead.com/npc=26415/senior-sergeant-juktok to complete the Quest and this can not be completed
