### ISSUE TITLE
[Dungeon] The Culling of Stratholme (HC)

### ISSUE THREAD

**Issue by AtlasRedux** [WoWManiaUK/Redemption#1118]
Arthas is behind on his supposed position when entering the town.
This causes other events to be very delayed, waiting for triggers. Makes it harder to get the mount.
Not sure how long it's been going on. For a while according to others.
Guess it's a movement trigger that doesn't hit or the event happens to quickly after another.

**Comment by elagen** [comment]
The timer starts as soon as the first wave spawns like it should
