### ISSUE TITLE
[Quest] A Fall From Grace

### ISSUE THREAD

**Issue by FargleBargle** [WoWManiaUK/Redemption#1119]
Quest instructions are to interact with a rope in the bell tower at the Scarlet Onslaught base in Dragonblight in order to distract the High Abbot's bodyguards.  Pulling the bell rope does not lure the body guards away and the High Abbot's dialogue option will not appear.

**Comment by elagen** [comment]
I can confirm that High abbot Landgen dialog does not appear http://www.wowhead.com/npc=27245/high-abbot-landgren

**Comment by Readerlady** [comment]
I know this has been closed, fixed in dev. and in release 37. Dialog worked fine for me so did the rope pulling. When I go to turn in the quest it has a yellow ? saying it is complete but the "complete" button is not clickable. I have four screen shots to show this at http://imgur.com/a/qpnI8
