### ISSUE TITLE
[Dungeon] Dire Maul - Ironbark

### ISSUE THREAD

**Issue by Nebucadnezza** [WoWManiaUK/Redemption#1120]
![wowscrnshot_042517_192534](https://cloud.githubusercontent.com/assets/28018484/25401283/3e5d145a-29ed-11e7-866a-617c2d59af15.jpg)
![wowscrnshot_042517_192636](https://cloud.githubusercontent.com/assets/28018484/25401284/3e60a890-29ed-11e7-88b6-267e925f8f39.jpg)
As you can see Ironbark is in his usual place in the gardens of the East Wing in Dire Maul, but you can't talk to him to initiate the opening of the door (the door seen in the second screenshot, which is merely 200 yards away from him at the back of the garden). Im pretty sure without him opening the door there is no other access to the Boss behind the door. Thank you to Bleak for your help in negating the door :)

**Comment by Plege** [comment]
http://wowwiki.wikia.com/wiki/Old_Ironbark

After you kill Zevrim Thornhoof you can talk to Old Ironbark and choose the option for him to beat down the door. he then moves over and smashes the door down. Could not reprodice the problem.
