### ISSUE TITLE
[Quest] Call of Water

### ISSUE THREAD

**Issue by EmilynLegioIX** [WoWManiaUK/Redemption#1122]
Hello!

I would like to report a bug I'm having with the "Call of Water" quest, (part 1 of 3) - Corrupt Manifestation's Bracers (Shaman's quest line for Healing Stream Totem). I reached the place where I am supposed to defeat the water elemental, but there is no aggressive mob around to start the quest.

Thank you for your time!  :)

**Comment by Plege** [comment]
![grafik](https://cloud.githubusercontent.com/assets/24266043/25444594/f7eeaaa0-2aab-11e7-9330-5774d328c9ee.png)

for me it was one in the back left that was attackable

**Comment by BleakSenpai** [comment]
The NPC's should be attack-able. This needs to be fixed.

**Comment by BleakSenpai** [comment]
The NPC required is in Permanent invisibility http://wow-mania.com/armory/?spell=8203.
This needs to be removed so the player can kill the NPC, otherwise it can't be completed.

**Comment by fvicaria** [comment]
I have just done all the quests in order and it works fine.
![image](https://cloud.githubusercontent.com/assets/9414661/26259553/6ee9d0b8-3cc1-11e7-9f6b-49f189eb590d.png)
