### ISSUE TITLE
[Spell] Spell Reflection

### ISSUE THREAD

**Issue by KyptAMaN** [WoWManiaUK/Redemption#1124]
Spell Reflection is bugged, once again, instead of fixing it, u make it even worse, not reflecting properly and no animation, i've done tickets when it was reflecting for a whole 5 secs, now that is broken af, i made ticket and they(some gm) send me here, idk if it will change anything, cuz this is a shame, wtv.. hope u can actually fix it.

Thanks.

**Comment by Plege** [comment]
can you please give more detail on what exactly is not working besides the animation? what is it not reflecting properly? How should it be?

**Comment by Anthonhed** [comment]
https://github.com/WoWManiaUK/Redemption/wiki/How-to-Properly-Report-an-Issue

**Comment by elagen** [comment]
OK number 1 IT is WORKING as intended relfecting 1 SPELL as it should
and number 2 there is no Animation which is being fixed
