### ISSUE TITLE
[QUEST] Sniffing Out the Perpetrator #12910

### ISSUE THREAD

**Issue by ke5hxf** [WoWManiaUK/Redemption#1125]
[http://www.wowhead.com/quest=12910/sniffing-out-the-perpetrator](http://www.wowhead.com/quest=12910/sniffing-out-the-perpetrator)

Players accept the quest and nothing happens. The mount besides Khaliisi [http://www.wowhead.com/npc=29855/khaliisi](url) is assumed to be the mount you are supposed to ride. Nothing moves or is mount-able. As I am writing this, I am second in line to do this quest, which makes it reproducable.

Quest is NOT doable and cannot continue in the quest line.

![wowscrnshot_042717_050119](https://cloud.githubusercontent.com/assets/26459414/25478600/6895b87e-2b07-11e7-8483-0b9f582f65a1.jpg)

latest launcher : used
confirmed by player Beffertje (was already here and talking to a GM, who advised to create this issue on github Bleak)

**Comment by Beffertje** [comment]
thanks alot dude to make this my github is bugged like hell no idee why :D

**Comment by BleakSenpai** [comment]
Tested. You cannot mount the NPC.

**Comment by ke5hxf** [comment]
Informed this is in Dev, closing.
