### ISSUE TITLE
Dalaran Helicopter Speed Bug

### ISSUE THREAD

**Issue by Vaggosdragos** [WoWManiaUK/Redemption#1127]
Greetings,
Rogue Sprint + Helicopter on Dalaran seem to bug and when you dismount, you still have the increased speed. Most likely, it reverts back to normal if you ride another mount .
(I think Sprint must end while you are still on the chopper)

**Comment by elagen** [comment]
Confirmed that when you have Sprint on and you Dismount from the Hammerhead your sprint stays on when it has expired
