### ISSUE TITLE
Mutiny on the Mercy

### ISSUE THREAD

**Issue by DeeBlaize** [WoWManiaUK/Redemption#1129]
**Mutiny on the Mercy** [quest=11527] in the Howling Fjord is the second in the line of four quests to obtain the _Shield of the Aesirites_.  To complete this quest, the player must go down into the hold of the Mercy and battle the mutinous gunners for 5 Barrels of Blasting Powder [item=34387].  Unfortunately, there are NO mutinous gunners (aka Mutinous Sea Dogs [npc=25026]) no matter how many times you reload, drop quest and re-accept, log out and re-log, or any combination thereof.

This quest must be completed to unlock one of only three Kalu'ak dailies.

http://www.wowhead.com/quest=11527/mutiny-on-the-mercy
http://www.wowhead.com/npc=25026/mutinous-sea-dog
http://www.wowhead.com/item=34387/barrel-of-blasting-powder

http://www.wowhead.com/faction=1073/the-kaluak#quests:0-10+1+2

**Comment by elagen** [comment]
With this what i have experienced you have to wit for the boat to stop then pick up the quest and the adds will be there - this is a platform issue but the adds are there for Mutiny on the Mercy

![wowscrnshot_042817_113425](https://cloud.githubusercontent.com/assets/22685042/25525417/b05e9b62-2c06-11e7-870a-29992de6b964.jpg)

**Comment by ghostlynx-helios** [comment]
Just tried, abandoned.  Waited til boat had stopped at pickup point.  accepted quest and went to hold to check.  Not there

**Comment by fvicaria** [comment]
HI there.
This is a known issue they are not respawning on the boat. We will try to offer an alternative.

**Comment by JoyfulPangolin** [comment]
Why is this closed?  It is still not working at all.

**Comment by tvshadowz** [comment]
Hi there JoyfulPangolin!

If this is still an issue please fill out another report and I will test it asap tomorrow. Apologies about the confusion. 

Thanks for the  report!
