### ISSUE TITLE
[Raid] Rotface

### ISSUE THREAD

**Issue by philoudu16** [WoWManiaUK/Redemption#1131]
This post is about the Rotface encounter in ICC: http://www.wowhead.com/npc=36627/rotface

Two issues here:

- Rotface gets deselected when he casts Slime Spray (http://wotlk.openwow.com/spell=69507). What I mean is you have Rotface ass target before the slime spray, and you have to reclick / tab target the boss once he's casting it. Not a massive deal but not extremely convenient.

- Secondly it seems like #1064 was not 100% fixed: the mages mirror images can still get the Vile Gas debuff dealing damage to players around them, as you can see on this recount data:
![image](https://cloud.githubusercontent.com/assets/23452669/25525882/5b68d040-2c11-11e7-8adc-0f60a1cb4f1e.png)
(Vile gas : http://www.wowhead.com/spell=72272/vile-gas which triggers http://www.wowhead.com/spell=69244/vile-gas)

**Comment by elagen** [comment]
We wont be fixing the issue with the rotface target

i have tried so many time to replicate vile gas on mirror images and pets and i can not reproduce

**Comment by philoudu16** [comment]
In this case please use the correct tags like "won't fix" instead of "fixed confirm on dev" so people know that the issue will not be fixed. This will help you as well since this post, for instance, would not exist if i knew you were not able to fix or even replicate it ;)

**Comment by fvicaria** [comment]
The first issue is too small for us at the moment to spend time on it.
The second just does not exist and could not be reproduce in dev.
