### ISSUE TITLE
[Spell] Victory rush bug

### ISSUE THREAD

**Issue by schwacknkill** [WoWManiaUK/Redemption#1133]
Victory rush can be used after killing a mob but the buff doesn't show on your character giving the 20 second timer.
![victory rush](https://cloud.githubusercontent.com/assets/28144544/25527264/6537cd98-2c5b-11e7-853b-6c93c23fe778.png)

**Comment by elagen** [comment]
This spell can be used When highlighted in your action bar - but does not show in your buff bar
