### ISSUE TITLE
[Spell] Slam proc bug

### ISSUE THREAD

**Issue by schwacknkill** [WoWManiaUK/Redemption#1134]
When slam proc's in Fury for an instant cast slam, my slam spell button doesn't show the proc (the spell border doesn't glow gold)
![slam](https://cloud.githubusercontent.com/assets/28144544/25527597/c731b79c-2c5c-11e7-80ea-2e331a40b553.png)

**Comment by elagen** [comment]
thats because its an instant cast - it wont show highlighted
