### ISSUE TITLE
[Quest] Captives at Deatholme

### ISSUE THREAD

**Issue by ghostlynx-helios** [WoWManiaUK/Redemption#1138]
Quest Captives at Deatholme not functioning, escapees already standing and cannot interact with.
http://ptr.wowhead.com/quest=9164/captives-at-deatholme

**Comment by Anthonhed** [comment]
Please log this issue corectly... check the guide :)

**Comment by elagen** [comment]
https://github.com/WoWManiaUK/Redemption/wiki/How-to-Properly-Report-an-Issue

**Comment by elagen** [comment]
i can confirm that with http://www.wowhead.com/quest=9164/captives-at-deatholme this is not working properly - As mentioned the npc can NOT be interacted with 

http://www.wowhead.com/npc=16208/apothecary-enith
http://www.wowhead.com/npc=16206/apprentice-varnis
http://www.wowhead.com/npc=16209/ranger-vedoran

![wowscrnshot_043017_094527](https://cloud.githubusercontent.com/assets/22685042/25562962/e3f975da-2d89-11e7-8196-73f20e5543e4.jpg)
