### ISSUE TITLE
Bag will often be closed automatically

### ISSUE THREAD

**Issue by idl0r** [WoWManiaUK/Redemption#1139]
Hi,

it often happens that the bag (when opened) will be closed automatically. It also seems to affect several people. All people I know ingame are affected by this bug. You have your bag open and it will just be closed. Sometimes several times within a few seconds and sometimes slower.

**Comment by fvicaria** [comment]
Do you have any addons?
In what scenario would that happen?

**Comment by idl0r** [comment]
I have quite a lot of addons. I'll ask my friends to see which one has less addons so we can figure it out.
It happens randomly but often (if not always) it affects several people at once.

**Comment by Vaggosdragos** [comment]
I believe this happened because you are using "Bagnon" addon. It happens to me as well sometime, try deactivating that and see if the problem persists.

**Comment by idl0r** [comment]
I do use ArkInventory, some of my friends are using indeed Bagnon but we both have those issues. Must be something else I guess.

**Comment by fvicaria** [comment]
Please let me know if this is happening with no addons. I will close this for now.
