### ISSUE TITLE
[Quest] Home of the Bear-man

### ISSUE THREAD

**Issue by squalllh1989** [WoWManiaUK/Redemption#1142]
http://www.wowhead.com/quest=13930/home-of-the-bear-men
This quest should be completed when the wolvar orphan is summoned under the tree at arround 50.8, 42.5 in grizzy hills, but it didn't.
![wowscrnshot_050117_102311](https://cloud.githubusercontent.com/assets/27235989/25571312/abf48876-2e58-11e7-937c-e05f20ccfe40.jpg)
![wowscrnshot_050117_102124](https://cloud.githubusercontent.com/assets/27235989/25571317/b0b97aa6-2e58-11e7-802e-a7f7ce3ef7b1.jpg)

**Comment by Plege** [comment]
i can confirm the quest does not complete when standing with the orphan at the tree.
When standing at the tree Grizzly Hills 50.8 / 42.8 or on the Island around the tree, the quest should complete once the orphan is summoned.

**Comment by fvicaria** [comment]
![image](https://cloud.githubusercontent.com/assets/9414661/25581121/af4a14da-2e7d-11e7-869f-b25cb78f2c54.png)

**Comment by squalllh1989** [comment]
lol then it just got a wrong cord, well thank you then
