### ISSUE TITLE
[Quest] A Fall From Grace

### ISSUE THREAD

**Issue by drewhawk13** [WoWManiaUK/Redemption#1144]
This quest in Dragonblight is bugged. I have attempted to complete this quest multiple times with the same result. I have absolutely no issues accepting or going through the motions of the quest. Everything works as it should. The problem I have is that it is saying complete in my quest log but the NPC (Agent Sully), I am supposed to turn it into, doesn't recognize that I have completed it. I have abandoned it multiple times and have done everything exactly how multiple sources say to do it. 
![wowscrnshot_050117_030021](https://cloud.githubusercontent.com/assets/28250872/25574342/7cf7d0c4-2e1b-11e7-90d2-9624621a572e.jpg)

**Comment by elagen** [comment]
i can confirm that there is a Complete issue when you go to hand in the quest

**Comment by Yarien62** [comment]
I know this quest was closed but it still continue to bug... Impossible to finish this quest and i haven't 2 Npc spawn when i go outside the church.
