### ISSUE TITLE
[Quest] You Scream, I Scream...

### ISSUE THREAD

**Issue by squalllh1989** [WoWManiaUK/Redemption#1145]
http://www.wowhead.com/quest=29119/you-scream-i-scream
This quest is in the quest line of Orcish orphan, in children's week, it should be given by Orcish Orphan after completing "Lordaeron Throne Room" (http://www.wowhead.com/quest=1800/lordaeron-throne-room) and will open up "A Warden of the Horde"(http://www.wowhead.com/quest=5502/a-warden-of-the-horde), the problem is: I already completed "Lordaeron Throne Room" and the other quest in the quest line of orish orphan, but the orphan didn't give me this quest, so i'm stuck here and can't complete the line for the reward, which is needed for the archive.
The quest line data was taken from https://vanilla-twinhead.twinstar.cz/?quest=915

**Comment by elagen** [comment]
i can confirm that when completing http://wowwiki.wikia.com/wiki/Quest:You_Scream,_I_Scream..._(Old)

it should give you the next part of the quest 
Alliance : http://www.wowhead.com/quest=558/jainas-autograph
Horde : http://www.wowhead.com/quest=925/cairnes-hoofprint

and these quest are NOT becoming available

**Comment by squalllh1989** [comment]
well for me, i didn't given the quest  http://wowwiki.wikia.com/wiki/Quest:You_Scream,_I_Scream..._(Old) , and the quest http://www.wowhead.com/quest=925/cairnes-hoofprint still given to me, so the quest line still stuck.

**Comment by fvicaria** [comment]
Have you done: http://www.wow-mania.com/armory/?quest=910
Unless you do this one you the quest won't open for you.
