### ISSUE TITLE
[Quest] Just Following Orders

### ISSUE THREAD

**Issue by foxtoopia12** [WoWManiaUK/Redemption#1147]
http://www.wowhead.com/quest=12540/just-following-order
I've done relogging and deleting cache folder and I think this quest is bugged. Basically, you have to talk to NPC and then it summons a mob. There are five NPCs, I've talked to them all, and I still can't progress. I need to complete this quest in order to change my reputation side from Frenzyheart Tribe to The Oracles.
![image](https://cloud.githubusercontent.com/assets/28296117/25615065/5e3d46d8-2f5f-11e7-843e-2e5ff7b46f53.png)
This is the NPC that wowhead guides us to progress.
![image](https://cloud.githubusercontent.com/assets/28296117/25615086/816bc3dc-2f5f-11e7-9688-5edc091c8d23.png)
The NPC doesn't summon any mobs to progress.
![image](https://cloud.githubusercontent.com/assets/28296117/25615095/93115124-2f5f-11e7-9176-a929a0b64d2d.png)

Please fix this. Thank you.

**Comment by fvicaria** [comment]
This was a reset issue. Shoul be fixed on Wednesday.
In the meantime find another NPC, there are 7 of those in the area. Chances are it was not used yet and it will work.
