### ISSUE TITLE
[BM Hunter] Can't tame a Wasp

### ISSUE THREAD

**Issue by Garryth** [WoWManiaUK/Redemption#1148]
Hello,

I'm a BM Hunter with the beast mastery skill to tame exotics.
I've tamed Sköll and others.

But when I tried to tame Qirot or a Hive'Zara Wasp from the Ruins of Ahn'Qiraj 20man raid my tame ability said I was targetting an invalid target.

http://www.wow-petopia.com/look.php?id=silithidflyerskinwhite
http://www.wowhead.com/pet=44/wasp

These wasps should be tamable in wotlk.
The reason I'ld like these specific is for the white skin.

I've also tried to tame the Hive Queens in Scholazar Basin with the same result.
Invalid target.

**Comment by fvicaria** [comment]
Please send the npc id from our Armory. Wowhead is not a wotlk database.
Some wasps are tamable and some are not. If I don't know which one you tried I have to assume you went for one that is not.
