### ISSUE TITLE
[QUEST] The Sum is Greater than the Parts

### ISSUE THREAD

**Issue by ke5hxf** [WoWManiaUK/Redemption#1149]
The Sum is Greater than the Parts 
[http://www.wowhead.com/quest=13043/the-sum-is-greater-than-the-parts](url)

Players are to mount and take control of Nergeld
[http://www.wowhead.com/npc=30403/nergeld](url)

using his abililties 
Punch 
[http://www.wowhead.com/spell=56746/punch](url)
Roar
[http://www.wowhead.com/spell=56748/roar](url)
Stomp
[http://www.wowhead.com/spell=56747/stomp](url)
Chained Grip
[http://www.wowhead.com/spell=60540/chained-grip](url)

defeat Dr. Terrible
[http://www.wowhead.com/npc=30404/dr-terrible](url)

This quest has several bugs in it. 
1. The Vargul Assailant [http://ptr.wowhead.com/npc=30471/vargul-assailant](url) spawn and spread out to the outside walls, then drift up to the floor above. Some slide back down, but none are able to leave the 'walls' 
2. Unable to properly 'steer' Nergeld.
3. Dr. Terrible , when the ability Stomp is used, is knocked out of the room, he 'floats' to the floor above.
3a. When the ability Chained grip is used, Dr. Terrible Evades.
4. Once you run up to Dr. Terrible to attack, the Punch ability does not show any damage. The only ability that shows damage is Stomp.
5. Once the Dr. Terrible walks back to his 'spot' his health is reset.
6. If you move your mount backwards, Dr. Terrible and his Hounds reset to their original standing place and all health is reset.

This quest is NOT able to be completed, therefore the quest line can NOT be advanced.

Launcher is being used.
Wow-mania Client is used.
Search of Git-hub showed no other reports of this type.
 
Edit:
The [SPELL] Controlling Nergeld
[http://www.wowhead.com/spell=56699/controlling-nergeld](url)
stays as a buff to the player even once outside the cave/area where Nergeld is located. It adds no extra abilities, just as a note, probably due to the incompletion of the quest.

**Comment by Anthonhed** [comment]
Please don't use wowhead as reference, us our armory :) http://wow-mania.com/armory

**Comment by ke5hxf** [comment]
Quote from your 'How to Properly Report an Issue' page:
[https://github.com/WoWManiaUK/Redemption/wiki/How-to-Properly-Report-an-Issue](url)


Please include links to reputable sources to confirm your statements. The acceptable list is:

http://wotlk.openwow.com/
http://www.wowhead.com/


please adjust this to show us noobs how its dun right

**Comment by fvicaria** [comment]
While wowhead is ok for NPC and spell IDs it is not always accurate for Quest as it is as per retails (aka Legion) and we are frozen at wotlk 3.3.5a.
So the best option now that openwow has closed is our Armory.

**Comment by elagen** [comment]
i have just done this quest and completed the quest with some minor problems - but waiting a few seconds longer u can complete http://wow-mania.com/armory/?quest=13043
The only problem i have encountered there is a platform issue 
![wowscrnshot_050417_090712](https://cloud.githubusercontent.com/assets/22685042/25695106/ba8d79ee-30a9-11e7-8843-8c70b2564629.jpg)
This has not Stopped Dr. Terrible - http://wow-mania.com/armory/?npc=30404
![wowscrnshot_050417_090742](https://cloud.githubusercontent.com/assets/22685042/25695091/ab8a9b16-30a9-11e7-8b52-4de18653cc63.jpg)
As you can see i Killed and Completed the quest 
![wowscrnshot_050417_091008](https://cloud.githubusercontent.com/assets/22685042/25695135/d3279a3e-30a9-11e7-8ad3-e305254024d2.jpg)

**Comment by fvicaria** [comment]
I am applying new maps to the server tomorrow. It fixed the issue.
