### ISSUE TITLE
Wintergrasp Workshop tagging from Graveyard

### ISSUE THREAD

**Issue by Furiouz84** [WoWManiaUK/Redemption#1150]
Westpark Workshop, Horde were waiting with immunity on graveyard, me alive on workshop couldnt tag it. Should not be possible.

So normally if they wont leave Westpark Workshop Graveyard I should tag the workshop to ally side. Unless they jump over then we have to fight for the rights...

please fix this

**Comment by Furiouz84** [comment]
hey jan, did I do something wrong on Github? greez

2017-05-05 12:39 GMT+02:00 Janitor <notifications@github.com>:

**Comment by fvicaria** [comment]
Hey please contact Pleger or Elagen in-game if you see it happen again. We can arrange a time to test this again. I can maybe join also.

**Comment by Furiouz84** [comment]
alright, will do!

2017-05-05 21:37 GMT+02:00 Janitor <notifications@github.com>:

**Comment by Furiouz84** [comment]
Did screenie as well if it helps,

http://i68.tinypic.com/vgpo9s.jpg

2017-05-06 2:31 GMT+02:00 Z84Zero . <brainbuster21@gmail.com>:
