### ISSUE TITLE
[Quest] Flight of the Wintergarde Defender

### ISSUE THREAD

**Issue by pallydude** [WoWManiaUK/Redemption#1151]
This quest is currently bugged for me - the helpless villagers spawn, then despawn almost immediately and cannot be picked up while using the provided gryphon.

**Comment by elagen** [comment]
https://github.com/WoWManiaUK/Redemption/wiki/How-to-Properly-Report-an-Issue

**Comment by fvicaria** [comment]
Works. Player is in a bad phase.

**Comment by elagen** [comment]
I have just Done this quest and havent had a problem to complete this quest

**Comment by pallydude** [comment]
I realize this - but to my original ticket, the GM told me to come here and log a bug. So I did. I will go open another ticket in game.

**Comment by fvicaria** [comment]
Yes. Apologies for that. That is what they are instructed to do but sometimes the issue is not on the quest itself. It happened way before when you missed a quest that would modify your phase.
Open the ticket and I will complete for you.

**Comment by pallydude** [comment]
Thanks very much - I have an open ticket waiting. I do appreciate both the politeness and professionalism of your staff in these cases. Excellent customer service. :)
