### ISSUE TITLE
Arctic fur loot in RDF

### ISSUE THREAD

**Issue by TheSale** [WoWManiaUK/Redemption#1152]
In some dungeons there is a chance for drop of an Arctic fur, now I dont know is it bug, or that is how it should work in my opinion it should not, from some odd reason Anyone could need on arctic fur.
I have screenshot where warrior won NEED roll over me who dont have skinning or leatherworking, and I have both, also few min after roque won and  he also dont have ether of those professions.

I think that only 425+ skill leatherworker should be able to need on that,
Same as damaged necklace for JWC or glyph book for insc

Ninjing items for ``friend`` or for ``AH spec`` is not fair
I who need have to skinn 50 or more beasts to get 1 arctic fur, or to trade 3 stacks of borean leather (10x heavy borean leather) to get 1 arctic fur

![wowscrnshot_050517_170508](https://cloud.githubusercontent.com/assets/20323863/25753926/a46dada4-31bd-11e7-87b4-c27e3c6419ba.jpg)

**Comment by fvicaria** [comment]
As is per 3.3.5a
