### ISSUE TITLE
[Spell] Slime Spray (Rotface)

### ISSUE THREAD

**Issue by LimitlessPain** [WoWManiaUK/Redemption#1156]
Rotface's (http://www.wowhead.com/npc=36627) Slime Spray has been fixed recently, but is not working as it should.
When Rotface casts **Slime Spray** (http://www.wowhead.com/spell=69508)
he does target a random raid member, but he should only target the raid member as long as he does his casting of the spell.
After the casting is over, Rotface should be facing the last position of his target while he channels the spray,
but at the moment if the the target moves, Rotface too turns towards it, making it impossible to dodge it.

Take note of my previous post upon the spell casting of NPCs (#1155) before handling this issue, as it may not be the case after that bug is fixed.

**Comment by fvicaria** [comment]
Talk to Elagen or Pleger and maybe we can test it on dev.
