### ISSUE TITLE
[Quest] Captives At Darkholme 

### ISSUE THREAD

**Issue by laurana21** [WoWManiaUK/Redemption#1157]

**Comment by laurana21** [comment]
http://www.wowhead.com/quest=9164/captives-at-deatholme

Item "restorative draught"does nothing when right clicking a targeted captive, nor does right clicking on a captive. Possibly incendental, the draught cannot be dragged and dropped to the action bar.

**Comment by fvicaria** [comment]
NPCs fixed.
