### ISSUE TITLE
Fury Warrior T10 4-set bonus 

### ISSUE THREAD

**Issue by wrezee** [WoWManiaUK/Redemption#1158]
Fury Warrior T10 4-set bonus is 2 charges of "Bloodsurge". (Instant slam)

When u use 1 slam, it directly consumes both charges of "Bloodsurge".

Consuming both charges at once makes the 4-set bonus unnecessary to have.

Is this meant to be?

**Comment by fvicaria** [comment]
Please follow the procedure described below before creating a new issue:
[How to Properly Report an Issue](https://github.com/wow-mania/Redemption/wiki/How-to-Properly-Report-an-Issue)

This will help developers identify and fix the issue quicker. Incorrectly or unclear reports will simply be deleted.
