### ISSUE TITLE
[Quest] Two Halves Become One

### ISSUE THREAD

**Issue by stigwir** [WoWManiaUK/Redemption#1159]
Western Plaguelands quest from NPC found on upper floor of Felstone Field Farm,no mather how much mobs you kill quest item named Good Luck Charm will not drop :S Had to ask GM for a help with this one,please fix it when you can
![1](https://cloud.githubusercontent.com/assets/27915577/25773228/864777b6-327a-11e7-844a-e9747de9d3df.png)

**Comment by fvicaria** [comment]
You can only get it from Jabbering Ghoul. The one holding a pitch fork.
![image](https://cloud.githubusercontent.com/assets/9414661/25773681/ba29e79a-3279-11e7-8ab2-55f7c29c9ce0.png)
