### ISSUE TITLE
[Bugg]Launched in air for no reason

### ISSUE THREAD

**Issue by stigwir** [WoWManiaUK/Redemption#1160]
I keep getting launched in air for no reason in map Eastern Plaguelands,also had same problem in dungeon Blackrock Deapths,no idea what I have done to get that bugg
![1](https://cloud.githubusercontent.com/assets/27915577/25781094/c633da1c-3334-11e7-92fe-8a9a1a6a41a7.png)

**Comment by fvicaria** [comment]
Please give exact coords and specify if you have our client and patches
