### ISSUE TITLE
[Item] Schematic: Blue Firework

### ISSUE THREAD

**Issue by Wolch** [WoWManiaUK/Redemption#1161]
http://www.wow-mania.com/armory/?item=18649

I try to learn the Schematic: Blue Firework but get an error "You can never use this item". My engineering skill is 189. 
![wowscrnshot_050717_195800](https://cloud.githubusercontent.com/assets/28511078/25783240/824889d8-3361-11e7-948d-6e87acf9eee7.jpg)

**Comment by elagen** [comment]
That is Because http://www.wow-mania.com/armory/?item=18649 is sold by the Ally - so it seems to be only usable by ally and Horde can NOT learn this pattern
