### ISSUE TITLE
[Dungeon] Sunken Temple

### ISSUE THREAD

**Issue by DarkestDuck** [WoWManiaUK/Redemption#1162]
In order to reach [Jammal'an the Prophet](http://www.wowhead.com/npc=5710/jammalan-the-prophet#comments) 6 defenders should be killed and then magical shield should be removed. But after killing them it is still there.

Few months ago the same issue was closed as a fixed (https://github.com/WoWManiaUK/Redemption/issues/1005). Was not this fix transferred from dev?

**Comment by elagen** [comment]
Confirmed that when killing the 6 Npc's around the are the force field should be down but the Force field stays up and active

![wowscrnshot_050817_100106](https://cloud.githubusercontent.com/assets/22685042/25797472/462ed8c0-33d5-11e7-9f0d-80df4b0eb46c.jpg)

http://wow-mania.com/armory/?npc=5714
http://wow-mania.com/armory/?npc=5715
http://wow-mania.com/armory/?npc=5717
http://wow-mania.com/armory/?npc=5716
http://wow-mania.com/armory/?npc=5712 
http://wow-mania.com/armory/?npc=5713
