### ISSUE TITLE
[ Spell ] Victory Rush

### ISSUE THREAD

**Issue by Creedpt** [WoWManiaUK/Redemption#1163]
Class: Warrior 
Spell : Victory Rush http://www.wowhead.com/spell=34428/victory-rush

Does not heal when used!

**Comment by Anthonhed** [comment]
Victory rush does not heal in WotLK

**Comment by Creedpt** [comment]
Yes it does sir. The values changes between the builds ( server build )
![sem titulo](https://cloud.githubusercontent.com/assets/28602927/25952518/d6782208-3658-11e7-82f5-37b65eff89ce.jpg)

**Comment by Anthonhed** [comment]
according to the WoW-Mania's armory it does not heal in WotLK http://wow-mania.com/armory/?spell=34428 The healing effect was added in Cataclysm.

**Comment by elagen** [comment]
Patch 4.0.1
Victory Rush is a level 10 warrior ability. It is an instant attack that deals damage and heals for 30% of maximum health. It can only be used within 20 seconds after landing a Killing Blow on an enemy that yields experience or honor.

**Comment by Anthonhed** [comment]
Always use WoW-Mania's Armory as the source for spells etc :)
