### ISSUE TITLE
[Talent] Death knight - Dancing Rune Weapon

### ISSUE THREAD

**Issue by hauruckk** [WoWManiaUK/Redemption#1164]
hello
Dancing rune weapon have problem with doing 50% of the damage of death knights attacks. it only does 10% with exception of melee auto attacks.
![wowscrnshot_051017_215933](https://cloud.githubusercontent.com/assets/28604882/25912584/0716344a-35cd-11e7-9cda-e925e4f26888.jpg)
This is the damage done of death strike 
![wowscrnshot_051017_215941](https://cloud.githubusercontent.com/assets/28604882/25912649/43660808-35cd-11e7-8a7f-899d9225495d.jpg)
and this is the damage the death strike did and you can see how little is the damage of other abilities compared to melee auto attacks
its almost 10% of the damage and for normal melee auto attacks it does its intended 50% the rest doesn't work.

**Comment by fvicaria** [comment]
Can you please show me where it states that it should do 50% of the damage in 3.3.5a please
