### ISSUE TITLE
[Core] Some spells not in the GCD

### ISSUE THREAD

**Issue by Manspiderp** [WoWManiaUK/Redemption#1165]
As an example of the bug in the Ymirheim npc's, I'll link the "Ymirheim Chosen Warrior"s in this case.
As a mage, I should be able to polymorph them, making them useless for the time they are affected. In the case of theses npc's, they are not.
The Chosen warriors will continue to cast their abilities, regardless of cooldowns.
http://www.wowhead.com/npc=31258/ymirheim-chosen-warrior#abilities

For example, the jump attack they perform (http://www.wowhead.com/spell=61227/jump-attack) can be used without hindrance and used on a ridiculously short cooldown. In retail, they would use it on entering combat, which would be once per fight. 

Furthermore, the cleave ability (hhttp://www.wowhead.com/spell=15496/cleave#used-by-npc) is used too many times. 

Note that wowhead did not put in the cooldown timer, which can be the result of being unsure of the cooldown or just not recording it correctly.

I would suggest putting the "jump attack" ability once per fight (or on a relatively long cooldown) and the "Cleave" ability on a 5-10 second cooldown, or reducing the damage of the abilities.

Every single one of the npcs in that area works basically the same. No cooldowns, being able to auto attack and use abilities through polymorph and stuns.

**Comment by elagen** [comment]
With the Spells used by http://wow-mania.com/armory/?npc=31258

the Cleave does 110% weapon Damage http://wow-mania.com/armory/?spell=15496 **With no GCD**

The Jump Attack does 850% weapon damage http://wow-mania.com/armory/?spell=61227 **With no GCD**

**Comment by Noahcoke** [comment]
I can be confirmed that their behavior towards being polymorphed (no matter which kind of polymorph) is odd. But still i tried it on several of the mentioned npcs, it wasnt the same on all of them. 
Some of them continued to attack me with all their abilites. Others just used a spell called Poisoned Spear (http://www.wowhead.com/spell=50255/poisoned-spear) without going for me directly.

**Comment by Noahcoke** [comment]
Here the one that used all his abilties: 
https://gyazo.com/3cd98a7f28f74e1dbcd5f8b6b891b3b8

This one was the one with the Spear only:
https://gyazo.com/666ee07ac25a92b6d2002f33d20cabe1

**Comment by fvicaria** [comment]
These are all NPC abilities. I will check the script. They will not be in the cooldown system anyways.
