### ISSUE TITLE
[Quest] Jagged Shards

### ISSUE THREAD

**Issue by Readerlady** [WoWManiaUK/Redemption#1167]
I have completed the quest by collecting all the shards. I can see the ? and the quest giver from a distance but as soon as I get close to the Blackwatch area he phases out. I have screen shots of him standing there with his ? above his head and then I move a little closer and he's gone. 

http://www.wowhead.com/quest=13136/jagged-shards
http://www.wowhead.com/npc=30708/crusader-olakin-sainrith

**Comment by elagen** [comment]
If u can upload screenshots that would be great - but i cant Get the phase issue

**Comment by Readerlady** [comment]
Will do.

**Comment by Readerlady** [comment]
http://imgur.com/a/ex0yR

**Comment by iggapres** [comment]
I have quite the same problem.
The NPC (Crusader Olakin Sainrith) has been taken away by the bone drake when I turned in a previous quest.
At that time, the item "Jagged Shard" (http://www.wowhead.com/item=43242/jagged-shard) dropped but I could not begin the quest (same issue as https://github.com/WoWManiaUK/Redemption/issues/759).
Now I have all the 10 Jagged Shards, but  Olakin an I are not in the same phase anymore.
GM did not want to help me and directed me here.
