### ISSUE TITLE
[Spell] Blizzard

### ISSUE THREAD

**Issue by TheGreyMouser** [WoWManiaUK/Redemption#1170]
Perhaps it is actually working as intended on this server, but on every other server I have played on, Nostralrius, Feenix,  (Blizzard Retail since early BC) and a couple others i cant remember... and according to wowhead.. [http://www.wowhead.com/spell=190356/blizzard] (http://www.wowhead.com/spell=190356/blizzard)  I looked this up on wow-mania and found http://www.wow-mania.com/armory/?spell=10 

Was this an intentional change on wow-mania or an over sight?

**Comment by Noahcoke** [comment]
If you have skilled the given Talent "Improved Blizzard" (http://wowwiki.wikia.com/wiki/Improved_Blizzard) it will still apply the slow effect. The automatic slow effect, without the talent was added later in cataclysm with patch 4.0.1, when the talent got removed aswell.

**Comment by Mellchiril** [comment]
The slow effect applied to Blizzard is a talent in the Frost talent tree. Without that particular talent, you will not have a slow effect on your Blizzard.
My question hereby is: Are you a frost mage and do you have talent points in Improved Blizzard?

**Comment by elagen** [comment]
http://www.wowhead.com/spell=62602/blizzard#changelog this is before Patch 4.0.1 (Cata) and there is no slow affect until you talent into it Thank you
