### ISSUE TITLE
[Quest] Jammmal'an The Prophet -Shield Doesnt Go Down

### ISSUE THREAD

**Issue by laurana21** [WoWManiaUK/Redemption#1171]
Quest Jammal'an The Prophet (ID: 1446) . Ran through Sunken Temple 2 times, both times killing all 6 guardian trolls. Shield did not go down either time.

http://www.wowhead.com/quest=1446/jammalan-the-prophet#see-also

**Comment by elagen** [comment]
The shield is coming Down what you have to do First is Run downstairs and do the Altar of Hakkar first where you have the Statues here is the Order

![stsecretcircle](https://cloud.githubusercontent.com/assets/22685042/25987443/f5b347e0-36eb-11e7-8f12-bfc4f6e1ca8a.jpg)

Here is the Shield down after doing the Altar 
![wowscrnshot_051217_082009](https://cloud.githubusercontent.com/assets/22685042/25987459/028f60a2-36ec-11e7-8589-d72138249254.jpg)

**Comment by laurana21** [comment]
thanks :)
