### ISSUE TITLE
[Quest] Demonic Crystal Prisons

### ISSUE THREAD

**Issue by Dusticles** [WoWManiaUK/Redemption#1172]
[Quest] Demonic Crystal Prisons] Ya seek out and slay painmaster, once you turn in this quest [Npc] Spirit of Ar'tor ] spawns; in this scenario on this server, he does not. So you aren;t able to do [Quest] Lohn'goron, Bow of the Torn-heart ] and [Quest] The Cipher of Damnation - Ar'tor's Charge] into [Quest] The Cipher of Damnation - The second fragment recovered]

**Comment by fvicaria** [comment]
http://www.wowhead.com/quest=10528/demonic-crystal-prisons

**Comment by elagen** [comment]
Confirmed that when doing the quest http://wow-mania.com/armory/?npc=21292#starts

the NPC http://wow-mania.com/armory/?npc=21318 should be there to give the next series of quests starting with http://wow-mania.com/armory/?quest=10537

But he is NOT there to start the next line of quests
