### ISSUE TITLE
[Quest] Building A Perimeter

### ISSUE THREAD

**Issue by nhorvat** [WoWManiaUK/Redemption#1173]
You get the quest item, but when you use it at targeted locations, nothing happens!

**Comment by elagen** [comment]
https://github.com/WoWManiaUK/Redemption/wiki/How-to-Properly-Report-an-Issue

**Comment by fvicaria** [comment]
http://www.wowhead.com/quest=10240/building-a-perimeter

**Comment by elagen** [comment]
Confirmed that when Doing the Quest you use http://wow-mania.com/armory/?item=28725 to activate the Runes

http://wow-mania.com/armory/?npc=19866
http://wow-mania.com/armory/?npc=19867
http://wow-mania.com/armory/?npc=19868

BUT when using the Activation Device on the rune's nothing is happening
