### ISSUE TITLE
[Quest] You'll Need a Bear

### ISSUE THREAD

**Issue by Elovena** [WoWManiaUK/Redemption#1174]
For the quest _[80] You'll Need a Bear_ you need to speak with **Brijana** outside Brunnhildar Village. You can see her at certain distance but whenever you get any closer she **disappears** so as her bear and other 3 bears near by her. You can target it but when the distance decreases you cannot. Questline cannot be completed if you cannot return the _You'll Need a Bear_ quest obviously. 

Is it because I'm playing with Worgen or something else? Hope you can fix it!

**Comment by fvicaria** [comment]
http://www.wow-mania.com/armory/?quest=12972

**Comment by fvicaria** [comment]
Most likely you skipped something along the quest line and got out of phase.
Please open a ticket and a GM will help you complete it.

**Comment by elagen** [comment]
i have done this quest and it all seems ok to me - i can not Reproduce the phase issue you are describing the only time it will start to phase is when having completed http://www.wowhead.com/quest=12924/forging-an-alliance

but in this case you are saying it phases earlier and have done the quest i can not get it to phase out
In the Village
![wowscrnshot_051417_125019](https://cloud.githubusercontent.com/assets/22685042/26033432/4883acda-38a4-11e7-9bc5-19794faa6bbb.jpg)

By the Npc
![wowscrnshot_051417_125023](https://cloud.githubusercontent.com/assets/22685042/26033437/51326baa-38a4-11e7-91d6-c537620d837d.jpg)

**Comment by fvicaria** [comment]
Thanks this was really helpful and should server as a guide to others.
