### ISSUE TITLE
Cenarion Circle Reputation Issues

### ISSUE THREAD

**Issue by Josephinw** [WoWManiaUK/Redemption#1176]
There seem to be some general issues with grinding the Cenarion Circle reputation. The quest [Encrypted Twilight Texts](http://www.wowhead.com/quest=8319/encrypted-twilight-texts) is at the moment only giving 250 rep when it should be giving 500. In the comment section [here](http://www.wowhead.com/quest=8319/encrypted-twilight-texts#comments) where it says it was increased from 250 to 500 in some 2.X patch and [here](http://www.wowhead.com/faction=609/cenarion-circle#comments) where it says 250 texts = 12500 rep which equals out to 500 rep per quest turnin in patch 3.3.2.
Next there also seems to be an issue with the turnin of the item [Abyssal Crest](http://www.wowhead.com/item=20513/faded-abyssal-crest) (no longer in retails current patches), where it only gives 75 but seems to be supposed to give 150 according to the comments which says it was increased as of patch 2.2. I cant find any more current comments to support this though.
Finally, the mobs are supposed to be giving rep all the way up until exalted according to the information given [here](http://www.wowhead.com/faction=609/cenarion-circle#comments), but are now stopping after hitting revered.

I know it says differently in the [wiki](http://wow-mania.com/armory/?faction=609) this server has created but I don't think that the information in there is necessarily correct. For example it is incorrect when it says "These stop yielding reputation when you reach the end of friendly for Twilight Avenger and Twilight Geolord" which in fact gave rep until the end of honored, meaning either the information given in the wiki is incorrect (seems to be purely Vanilla based) or there is that issue at least on the server.

**Comment by Noahcoke** [comment]
Please add the wowhead website links to the Npcs and Items you are referring to. It makes it easier for us to check it.

**Comment by Josephinw** [comment]
They are linked in the wiki

**Comment by Noahcoke** [comment]
Those are only the links for the wow-mania wiki, not wowhead.

**Comment by Josephinw** [comment]
Didn't really think it would matter since they still have the same ID and map locations but here: 
[Twilight Avenger](http://www.wowhead.com/npc=11880/twilight-avenger)
[Twilight Geolord](http://www.wowhead.com/npc=11881/twilight-geolord)

**Comment by Noahcoke** [comment]
https://github.com/WoWManiaUK/Redemption/wiki/How-to-Properly-Report-an-Issue 
Thank you. I will have a look.

**Comment by fvicaria** [comment]
The reason for this is that at the moment Reputation Gain is x1 not x2.
I will look into changing that to x2 and what sort of consequences that may cause.

**Comment by Josephinw** [comment]
According to this website (https://wotlk-twinhead.twinstar.cz/?quest=8319)it is supposed to be 500 rep for the Encrypted Twilight Texts in WotLK though.

**Comment by fvicaria** [comment]
We need to go by our Armory. This link is from another server not in the least reliable.
Unfortunately the other reliable link was wotlk.openwow.com but they shut down.
I will see if I find another one. WoWHead and WoWWiki are always updated to the latest version so they are no good. Our Armory was based on opewow.

**Comment by Josephinw** [comment]
Well your Armory isnt even correctly matched to the server which makes it a questionable source.

**Comment by Josephinw** [comment]
http://wowwiki.wikia.com/wiki/Patch_2.2.0 In this patch note it says that the Cenarion Circle had their acquisition rate significantly increased, which means they went from the 250 rep per quest turnin in Vanilla to something higher, probably 500 which is noted in the comments from the wowhead links above.

**Comment by fvicaria** [comment]
As I can't find any official info yet I have only updated the ones I found some vague details on 
Quest 8319 and 8361 will now give 250 rep or 500 if x2
