### ISSUE TITLE
[Spell] Flaxweave Underlay doesn't add agility

### ISSUE THREAD

**Issue by idl0r** [WoWManiaUK/Redemption#1177]
Hi,

the spell "[Flexweave Underlay](http://wow.qasl.de/aowow/?spell=55002)" (engineering 380) doesn't add the mentioned agility onto my cloak. The parachute however will be added as described.
![flexweave_underlay](https://cloud.githubusercontent.com/assets/32827/26036364/995e9240-38dc-11e7-9236-c94d534e1c14.png)
![cloak](https://cloud.githubusercontent.com/assets/32827/26036365/995f1de6-38dc-11e7-9016-8aa439403905.png)

**Comment by idl0r** [comment]
Looking at wowhead http://www.wowhead.com/spell=55002/flexweave-underlay it seems like the description is simply wrong and the actual functionality is correct.

**Comment by fvicaria** [comment]
To test in dev clear cache.
