### ISSUE TITLE
[Quest] Redemption

### ISSUE THREAD

**Issue by laurana21** [WoWManiaUK/Redemption#1178]
Quest "Redemption (ID 5742}" given by Tirion Fordring in Eastern Plaguelands. It does not give an option via speech bubble to forward his story. Standing there waiting does not work either.

http://www.wowhead.com/quest=5742/redemption

**Comment by fvicaria** [comment]
You will need to finish all lower level quests offered by him first.

**Comment by laurana21** [comment]
I've already done his kill quests

**Comment by Noahcoke** [comment]
Works fine now on dev. Did his first quest Carrion Grubbage (http://www.wowhead.com/quest=5544/carrion-grubbage) and afterwards could finish the Redemption quest by using the speech bubble option.
