### ISSUE TITLE
[Quest] Gather the Orbs

### ISSUE THREAD

**Issue by Josephinw** [WoWManiaUK/Redemption#1179]
The quest [Gather the Orbs](http://www.wowhead.com/quest=10859/gather-the-orbs) is doable but the totem you drop from [Orb Collecting Totem](http://www.wowhead.com/item=31668) is hostile and decides to attack you sometimes. Not really a big issue but slightly annoying.

**Comment by Noahcoke** [comment]
Please add all NPCs and the exact questline that are needed to talk to/complete in order to reach "Gather the Orbs".

**Comment by Josephinw** [comment]
I think that [this](http://www.wowhead.com/quest=10565/the-stones-of-vekhnir) is the starting quest from this [guy](http://www.wowhead.com/npc=21496). The issue is from a quest that is a part of a longer chain of quests that gets unlocked from different guys, but from what I can tell that should be the very start of it.

**Comment by Noahcoke** [comment]
It happens as described. For me i could not even finish the quest, since the Totem did not do what it was supposed to do. 
https://gyazo.com/72e5921b2cee32a79f644d9a7296ccaf

**Comment by Josephinw** [comment]
You have to stand close to the pink floating orb to be able to pick them up with the totem, not sure you were close enough to any. Either way, its not supposed to be hostile.
