### ISSUE TITLE
[Quest] The Smallest Creatures

### ISSUE THREAD

**Issue by Josephinw** [WoWManiaUK/Redemption#1180]
The quest [The Smallest Creatures](http://www.wowhead.com/quest=10720/the-smallest-creatures) from [Rexxar](http://www.wowhead.com/npc=21984) works but the cancel spell is lacking meaning you have to run and get the Marmot killed in some way, which feels rather cruel.

The quests leading up to this one are:
1. The questchain starting with [Thunderlord Clan Artifacts](http://www.wowhead.com/quest=10524/thunderlord-clan-artifacts) that you get from the dropped item [Thunderlord Clan Artifact](http://www.wowhead.com/item=30431). The item can drop from the following ogres (and raptor): [Bladespire Shaman](http://www.wowhead.com/npc=19998), [Bladespire Brute](http://www.wowhead.com/npc=19995), [Bladespire Raptor](http://www.wowhead.com/npc=20728), [Bladespire Cook](http://www.wowhead.com/npc=20334), [Bladespire Champion](http://www.wowhead.com/npc=21296)
2. The questchain starting with [The Spirits Have Voices](http://www.wowhead.com/quest=10718/the-spirits-have-voices) from [Garm Wolfbrother](http://www.wowhead.com/npc=21950).
3. [Baron Sablemanes Poison](http://www.wowhead.com/quest=10749/baron-sablemanes-poison) from [Baron Sablemane](http://www.wowhead.com/npc=22103).

**Comment by fvicaria** [comment]
There is no cancel it's a timer of 6 minutes.
