### ISSUE TITLE
HoR Bug at escape lk last wall

### ISSUE THREAD

**Issue by TheSale** [WoWManiaUK/Redemption#1182]
This occurred many times for me, wipe after we break trough last wall, Jaina survive last wave of mobs with 1%, LK keep hiting her and kill eventually before she leave cave, but boat appears and cast animation fire to cave, and then stick with loot chest (that cant be looted) and portal, but last phase reset, so we have to do it over again.
That would be 1 bug
Second bug is when we try again, and do it without issues, BUT boat is already standing there, after we get out of cave and lk start choaking Jaina, there is no boat to shoot down lk so it all goes like that for few seconds, and then lk start doing some damage to us no matter if we are on boat already, and kill us fast, and again its reseted.

**Comment by fvicaria** [comment]
Can anyone try to reproduce this in PTR?
