### ISSUE TITLE
T9 set bonus

### ISSUE THREAD

**Issue by My3i** [WoWManiaUK/Redemption#1183]
Hello im a Hunter and a while ago i brouth 4 pieces of the T9 set.
But the 4 set bonus dosn't work.  The bonus should proc on all ranged attacks and give my pet 600 AP for 15 sec. As me and GM Bleak found out it really dosn't work.
I tryed attacking a dummy in Ogrimar 100 times to see if the chance is reaaallly low (like 1% or something)
and it still didnt prok. 
As instructed by GM Bleak and GM Metaxa i am reporting the problem here.
Hope to be fixed soon and that i helped.
Have a great day!

**Comment by BleakSenpai** [comment]
I've confirmed this in Dev and Red.

**Comment by Noahcoke** [comment]
https://gyazo.com/5978f84637c1240cbbd07b0bbfe5aa3f
Works fine on dev.
