### ISSUE TITLE
Tears Of The Moon quest

### ISSUE THREAD

**Issue by Praiven** [WoWManiaUK/Redemption#1184]
Priestess A'moora in The temple of the Moon at Darnassus wants you to bring her Lady Sathrah's Silvery Spinnerets.

Silvery Spinnerets: 0/1 

My problem and a possible bug is that Lady Sathrah won't even spawn at the location the quest gives you to go, thus not being able to kill her!
That's what I thought in the first place, but after walking the whole Teldrassil to find any missed quest-givers I found her East of the indicated quest point.

Thanks for your time and hope you fix it soon!

**Comment by fvicaria** [comment]
![image](https://cloud.githubusercontent.com/assets/9414661/26152633/96e9d766-3aff-11e7-9dd4-b44825f2eca2.png)
