### ISSUE TITLE
Resto Druid Omen of Clarity Talent.

### ISSUE THREAD

**Issue by Donerschaap** [WoWManiaUK/Redemption#1186]
I know this has been posted before but now at 17/05/2017 Omen of Clarity doesn't seem to ever proc when I'm healing and because it's a big healing boost I really would like to see it fixed. In 2 whole days I haven't seen it proced once.

Thanks for the effort,

Donerschaap

**Comment by Noahcoke** [comment]
Worked fine for me on autoattacks, dmg spells and healing effects. 
https://gyazo.com/aa417d4531350f3f04a409b3e0b63dab
https://gyazo.com/4973c88459b1eba45407e1107d2e215c
https://gyazo.com/999cbf2a914f54976724424be1a2eaf8

It just took some spells/autoattacks.
