### ISSUE TITLE
Rotface in  ICC

### ISSUE THREAD

**Issue by Bouront** [WoWManiaUK/Redemption#1188]
During is poison cone attack he becomes non-targetable, so far done this with 2 different runs, not an issue if you are melee but if your range it resets casting and becomes an annoyance.

**Comment by fvicaria** [comment]
If he was non-targetable melees could not hit it either. You just lose focus on some phase changes you have to refocus.

**Comment by Bouront** [comment]
Its not an issue for melee due to the fact that they are soo close and hitting an ability they reacquire the closest target namely the boss, been watching alot of guides on the fight and at no stage does the player lose target with the boss. Thats the reason I said if you are melee you don't have an issue but as a caster doing a spell that requires time if he becomes non-targetable your cast is cancelled. I've been both tank and caster and both cases lost the boss for 2 seconds as tank and lost a cast as caster, doing my rotation it completely screws it.

**Comment by Bouront** [comment]
https://www.youtube.com/watch?v=atOSEVcPOZc&ytbChannel=10SecondsTillEnrage is 1 of many videos where the player NEVER loses target with the boss, yet the groups i've went into that fight with have ALWAYS lost target.
