### ISSUE TITLE
[Spell] Death Coil

### ISSUE THREAD

**Issue by LimitlessPain** [WoWManiaUK/Redemption#1190]
The spell was modified again, but it's still not working as intended.

As I have said death coil should heal the caster for 300% of the damage done on patch 3.3.5a.
http://wow.gamepedia.com/Death_Coil_(warlock_ability)#Patches_and_hotfixes
- Hotfix (2009-04-30): "The Warlock ability Death Coil now heals you for 300% of the damage done, up from 100%."
This dates before 3.2.0 patch.

Utilizing the double healing effect doesn't work as a solution sadly.
Reason:
Death Coil crits (screenshot)
https://cloud.githubusercontent.com/assets/25713713/26019736/16aec848-3778-11e7-9a67-8276a088fe96.jpg
1320 does not equal 440+660
I have mentioned this previously, only one of the healing effects are corresponding to the actual damage dealt in case of crits, totaling less than 100% of damage done received as healing - on current settings.

**Death Coil** (http://www.wow-mania.com/armory/?spell=47860)
(The spell was recently removed from wowhead database completely.)

I posted the screenshot originally in the previous issue (#1061) - after it was closed though.

**Comment by fvicaria** [comment]
Sorry I spent a lot of time on this one and it just can't be fixed at this current point.
I will keep it in mind and include it when we solve the other general spell mechanism issue.

**Comment by LimitlessPain** [comment]
For the time being, if at least the healing effect could be restored to 150% from the current 50% with the double, it would be much appreciated. It would still give around 3 times amount of healing mostly which can come handy in some situations and is also closer to the original.

Thanks.
