### ISSUE TITLE
Illidan Stormrage phase 2 elementals enrage mechanic not working.

### ISSUE THREAD

**Issue by xandror** [WoWManiaUK/Redemption#1191]
"Charge/Enrage: If any raid member is farther away than 25 yards from *both* Blades, one of the Flames charges that player and enrages, wiping the raid" 

This is occurring even when everyone is well within 25 yards of a blade.

**Comment by elagen** [comment]
I can confirm that when the Elementals are down the boss should drop down but he stays in the air

The Elementals spawn during the air phase http://www.wowhead.com/npc=22997/flame-of-azzinoth when they are killed Illidan should come down

Also when Wiping on the Fight Akama Does not Reset properly http://www.wowhead.com/npc=23089/akama As the Adds he fights should not be there when Illidan is reset 

The Mobs Akama fights during the fight Illidan are  - These do NOT reset when Illidan is being Reset

Illidan - http://www.wowhead.com/npc=22917/illidan-stormrage

**Comment by fvicaria** [comment]
Please re-check this with the current implementation in dev.

**Comment by elagen** [comment]
During the Fight if you are Within 30 Yards of the Elemental's they do not charge towards you - when theya re a certain Distance away from the Warglaves they do Enrage so they have to be tanked at the Warglaves on the side they Spawn and Everyone to be on the Meshing in the Center so no one is outside the 30 yard zone 

i can not get them to Charge inside of the 30 Yard zone - Sorry i can not Reproduce
