### ISSUE TITLE
Escape from Durnholde part 3

### ISSUE THREAD

**Issue by Ammoniel** [WoWManiaUK/Redemption#1192]
Hello,
On the part 3 of the quest, after i get the quest from Thrall, i can't interact again with him to make him start walking.
First time it work
![wowscrnshot_051917_125529](https://cloud.githubusercontent.com/assets/28805752/26245754/4bd8f6c6-3c9e-11e7-9e65-08508556359b.jpg)
ed, but he was stucked in a wall. I reseted the dungeon and this issue appeared.

**Comment by Noahcoke** [comment]
I am testing it right now, since i know it. But keep this in mind please the next time: 
https://github.com/wow-mania/Redemption/wiki/How-to-Properly-Report-an-Issue
It makes it easier for us to check the described issue and fixing it. :)

**Comment by Noahcoke** [comment]
It worked fine for me after i killed the enemy npcs in the area around thrall. He walked outside and i could finish the part inside the prison. 
https://gyazo.com/600cd4abe00683c00cd29413c8ad04e5
Still: I could see him moving through walls after he picked up his armor or other enemy npcs that spawn inside the wall.
