### ISSUE TITLE
[Quest] The Fate of Flanis

### ISSUE THREAD

**Issue by mstrdbz** [WoWManiaUK/Redemption#1194]
Quest ID#10583

NPC ID#21727 "Flanis Swiftwing" does not have the option to receive the quest item ID# 30658 [Flanis' Pack]
NPC should be dead to allow completion of quest.  In-game he is alive.
![image](https://cloud.githubusercontent.com/assets/28831028/26279284/1167729c-3d75-11e7-939c-417a4c7fa1f9.png)

**Comment by Noahcoke** [comment]
Please link the wowhead website link of the quest and the npc. That will make it easier to check the issue.
Thank you

**Comment by mstrdbz** [comment]
Link to Quest: [The Fate of Flanis](http://www.wowhead.com/quest=10583/the-fate-of-flanis)
Link to NPC: [Flanis](http://www.wowhead.com/npc=21727/flanis-swiftwing)

**Comment by Plege** [comment]
I confirm that Flanis is lying on the floor but still alive. He does not have the interaction option to claim Flani's Pack (http://www.wowhead.com/item=30658/flanis-pack) so the quest can not be completed.

Flanis should be dead on the floor and an interaction should be possible to claim Flani's Pack.
As shown in this tutorial https://www.youtube.com/watch?v=ozYDvYowcMM

**Comment by fvicaria** [comment]
http://www.wow-mania.com/armory/?quest=10583
http://www.wow-mania.com/armory/?npc=21727
