### ISSUE TITLE
New Legion x-mog bug.

### ISSUE THREAD

**Issue by jisub2da** [WoWManiaUK/Redemption#1195]
Hi I have purchased a legendary x-mog from the new wow-mania mall legion x-mog weapon vendor.  The item name is The Star's Design and it does not seem to appear as a x-mog option at Warpweaver Hashom.
I asked the GM about it, and he asked me to post the issue up here.

**Comment by Noahcoke** [comment]
https://gyazo.com/e09611b53d970f2f4ac7916b614d0e16
Worked fine for me. Did u download the latest patch? Version 2.0.8 is the newest atm.

**Comment by jisub2da** [comment]
:( yes i do have 2.0.8 patch. I believe it was Mataxa who looked into the issue for me at the time.

**Comment by jisub2da** [comment]
![xmog](https://cloud.githubusercontent.com/assets/28831061/26281324/f79f07ae-3e36-11e7-9e1f-7b8f099ca049.jpg)
