### ISSUE TITLE
[Quest] Return of the High Chief

### ISSUE THREAD

**Issue by Zilthuras** [WoWManiaUK/Redemption#1196]
**Location:** Dragonblight, Icemist Village

![sem titulo](https://cloud.githubusercontent.com/assets/28836063/26281800/c91757de-3df9-11e7-9574-e50ed25198fe.jpg)

**Normal Behaviour:** This quest involves defeating a single elite Under-king Anub'et'kan that after being defeated spawns an object named "Anub'et'kan's Carapace" that stays spawned for a while to allow the players involved in the quest to pick up the necessary item to complete the quest.

**What is happening:** The object despawns after the first player loots the object not allowing any others to do the same.

**Addicional behaviour:** I don't know if this is restricted to my character or not but after this happened the first time I can no longer interact with the object when attempting to redo the quest, instead recieving a message that "That is already being used".
Also the crystal to start the event seems to take a bit longer to respawn than it should, NPCs and the elite all respawn but the crystal only does so a fair bit later.

![sem titulo1](https://cloud.githubusercontent.com/assets/28836063/26281839/1926ec0c-3dfb-11e7-8df7-e50ef66dbb5d.jpg)

Edit: adding link for the quest on Wowhead, http://www.wowhead.com/quest=12069/return-of-the-high-chief

**Comment by fvicaria** [comment]
http://www.wow-mania.com/armory/?quest=12069

**Comment by fvicaria** [comment]
Quest is not sharable or re-doable.
![image](https://cloud.githubusercontent.com/assets/9414661/26282180/d000191e-3e03-11e7-89e8-d12d385f9e47.png)

Always use our Armory as your source of reference.

**Comment by Zilthuras** [comment]
I never completed the quest the first time, I abandoned and attempted to do it again, so I don't quite understand what you're saying, that after failing once I can no longer accept the quest and try it again?
you can see in the SS that I have the quest in my log, this happened yesterday while doing it with a friend.

Still doesn't change the fact that the main reason for this post is still true, the object despawns after a single player picks up the item and it should not do so.

**Comment by fvicaria** [comment]
I will have a look

**Comment by fvicaria** [comment]
Not shareable mean you cannot share and the object respawn time is done for one player not for a group.
If someone uses the other needs to wait for it to respawn again. If it is dependant on a kill too bad. You have to kill again as many times as there are people.

**Comment by Zilthuras** [comment]
I don't wish to enter a contest here, but I have done this quest before on retail, and played long enough to know what the Not sharable tag means.

**Comment by fvicaria** [comment]
Not going to get into it either. Once the object is used it will into hang around waiting for another player to use it also. It will despawn. I have changed the time to respawn from 10min to 2min.
I will look into the quest itself when I have a minute.
