### ISSUE TITLE
Haircut and Facial Hair

### ISSUE THREAD

**Issue by Aattrox** [WoWManiaUK/Redemption#1198]
There is a problem with some haircuts and with the Facial hair named "Braided Mustache" from dwarves ..  some parts are missing from this Facial hair style . 
![wowscrnshot_052217_144155](https://cloud.githubusercontent.com/assets/28839846/26283640/f05f3704-3e34-11e7-935f-eafc80508218.jpg)

**Comment by elagen** [comment]
I cant find any source on what extra needs for the facial hair 

Patch 6.0.2 (14-October-2014): Barber Shop now provides additional character facial-customization options.
Patch 3.2.0 (04-Aug-2009): Tauren now have the option of changing skin tone by visiting the Barber Shop.

This is the only thing i can find **if u can find how Facial hair is suppose to be in patch 3.3.5a** other then that i think u might have Experienced Draenor and Wotlk is not like that with most of the features

**Comment by g0sy** [comment]
@elagen He is refering to the screenshot. If you follow the mustache on the dwarf, it cut's off mid-way, then continues after the void.

**Comment by elagen** [comment]
ahh now i see - its like the Undead with the missing spine

**Comment by fvicaria** [comment]
This will have to wait for a complete update on the textures on the client.
Also since this is not a server-side issue I will close it.
I will make sure all textures are working when we do a client update.
