### ISSUE TITLE
[Quest] Where Dragons Fell #13359

### ISSUE THREAD

**Issue by Beffertje** [WoWManiaUK/Redemption#1199]
the npc is not there where is supost to stay and there is no quest to ( becos of the npc is not there ) 
![wowscrnshot_052217_125518](https://cloud.githubusercontent.com/assets/28094698/26307985/8e9edfb0-3ef7-11e7-8ae3-a5039d781aaa.jpg)
![wowscrnshot_052217_125530](https://cloud.githubusercontent.com/assets/28094698/26307986/8ea332fe-3ef7-11e7-9b25-bc52dd22ec1b.jpg)

quest link http://www.wowhead.com/quest=13398/where-dragons-fell

npc link   http://www.wowhead.com/npc=32423/matthias-lehner

**Comment by dothie** [comment]
i checked all the places whit that npc, they are there but invissible for player

**Comment by dothie** [comment]
![wowscrnshot_052217_143000](https://cloud.githubusercontent.com/assets/26550083/26308869/4787efdc-3efb-11e7-8c70-d9dd8bd2cce2.jpg)

**Comment by elagen** [comment]
Confirmed that when doing all previous Quests to the Quest line after doing http://www.wowhead.com/quest=13349/cradle-of-the-frostbrood 

Matthias should appear and he does not so you can NOT continue with the next quest
http://www.wowhead.com/npc=32423/matthias-lehner

**Comment by Zeevee92** [comment]
hi,
i've the same problem, i can't see him 
![wowscrnshot_103017_150618](https://user-images.githubusercontent.com/32412813/32175161-57cf2844-bd84-11e7-9cc0-73968d13f82e.jpg)
