### ISSUE TITLE
[quest] blinding the eyes in the Sky #13313

### ISSUE THREAD

**Issue by Beffertje** [WoWManiaUK/Redemption#1200]
Missing quest the noc do kot show the quest

**Comment by fvicaria** [comment]
Please follow the procedure described below before creating a new issue:
[How to Properly Report an Issue](https://github.com/wow-mania/Redemption/wiki/How-to-Properly-Report-an-Issue)

This will help developers identify and fix the issue quicker. Incorrectly or unclear reports will simply be deleted.
