### ISSUE TITLE
[Quests] In Shadow Labyrinth

### ISSUE THREAD

**Issue by xeylo** [WoWManiaUK/Redemption#1201]
Hi!

The quests "The Codex of Blood" and "The Soul Devices" in Shadow Labyrinth does not work right now; the quest items that need to be looted are not in the dungeon.

**Comment by Noahcoke** [comment]
Please attach the link to wowhead of the quests to your comment. Its making it easier for us to check the issue properly. :-)

**Comment by elagen** [comment]
i can confirm that the Quests are working 

http://www.wowhead.com/quest=10091/the-soul-devices
![wowscrnshot_052317_092354](https://cloud.githubusercontent.com/assets/22685042/26345102/c90bffa0-3f99-11e7-8804-9a614d3dfefc.jpg)
The Soul Devices can be looted and Complete

http://www.wowhead.com/quest=29643/the-codex-of-blood
![wowscrnshot_052317_092428](https://cloud.githubusercontent.com/assets/22685042/26345192/057560e4-3f9a-11e7-9660-1774cbc91e1a.jpg)
The Codex can be Read and Completed the quest - so you can pick up the next quest
