### ISSUE TITLE
Leatherworking (Apprentice) lack of a starter skill

### ISSUE THREAD

**Issue by AlanEnB** [WoWManiaUK/Redemption#1204]
After purchased, profession Leatherworking (Apprentice) lack of a starter skill to make Light Leather.
Supposed to be a total of 6 starter skills, but was only given 5.

Tested on both Alliance and Horde, both sides newbies who brought Leatherworking (Apprentice) as a profession is lack of this starter skill. This starter skill is especially crucial as it's the foundation to turn Ruined Leather Scraps into Light Leather.

**Comment by fvicaria** [comment]
As is. You get the skill to 450. You still have to learn all the spells.

**Comment by AlanEnB** [comment]
Recipe not available for purchase. It's missing from the given trainer when you first purchased Leatherworking as one of your profession.

**Comment by fvicaria** [comment]
I will check.

**Comment by fvicaria** [comment]
Can you send me the spell id please?

**Comment by AlanEnB** [comment]
Spell id : Light Leather

It's suppose to be given to you by default when you first purchase Leatherworking profession.

The following are skill 1 given by default whenever someone chosen Leatherworking:

Light Leather
Light Armor Kit
Handstitched Leather Boots
Handstitched Leather Bracers
Handstitched Leather Cloak
Handstitched Leather Vest

My newbie druid was given everything by Leatherworking NPC except Light Leather missing.

**Comment by BleakSenpai** [comment]
Anyone having this problem should just "Right-click" on their "Ruined Leather Scraps", it will turn into "Light Leather" in groups of 4 scraps to 1 Light leather.
