### ISSUE TITLE
[Quest] Honor is for the weak

### ISSUE THREAD

**Issue by Zilthuras** [WoWManiaUK/Redemption#1205]
**Location:** Icecrown, Weeping Quarry

**Link:** http://www.wowhead.com/quest=13170/honor-is-for-the-weak

**Normal Behaviour:** Use a shade (31110) to kill the quest targets, Restless Lookout (30951), with it's ability called "Assassinate Restless Lookout" (58563).

**What is happening:** the targets for the quest are regenerating health since they are technically out of combat, since the Shade is in a diferent "realm", making it take far longer to complete and becoming quite annoying.

**Possible solution:** just allow the shade to one-shot the Restless Lookout to avoid messing with the mobs out of combat health regen?

**Comment by elagen** [comment]
i Have done this quest before and Retested but i cannot reproduce the issue u are describing - if it continue's for you 
you can Move out of the Shade form and manual attack them with your Character that will also count as kills towards the quest  - Sorry for any inconvenience but i can not reproduce your situation
