### ISSUE TITLE
[Quest] in the Argent tournament

### ISSUE THREAD

**Issue by Gryfter** [WoWManiaUK/Redemption#1209]
So I turned in the quest the Black Knight's Orders there are three follow up quests to this Black Knights Fall > Black Knight's Curse . Black Knights Fate. The quest giver has a yellow ! but wont actually give the quest.
1. Yes I use the Launcher 2. Yes I've cleared my cache ( multiple times ) 3. Ticketed it in game and this is what they told me to do.

**Comment by fvicaria** [comment]
![image](https://cloud.githubusercontent.com/assets/9414661/26394653/803477f4-4065-11e7-84fd-fc9225b26cf7.png)
