### ISSUE TITLE
[Quest] Gahz'ridian

### ISSUE THREAD

**Issue by laurana21** [WoWManiaUK/Redemption#1210]
Quest ID : 3161
Nothing ornaments show on the minimap when you equip the helmet, and no ornaments on the surface to otherwise pick up

http://www.wowhead.com/quest=3161/gahzridian

**Comment by Plege** [comment]
Can not reproduce. they are sprinklet all over Tanaris just need to look all over. a Bit scarce but they are definetly there.

**Comment by Plege** [comment]
![grafik](https://cloud.githubusercontent.com/assets/24266043/26392544/44dfb9e6-4067-11e7-9454-48e7114a20e1.png)

**Comment by laurana21** [comment]
thank you :)
