### ISSUE TITLE
[Quest] Elixir of Agony

### ISSUE THREAD

**Issue by tonguella** [WoWManiaUK/Redemption#1214]
Apothecary Lydon in Tarren Mill wants 4 items; all of which are in my inventory - Mudsnout mixture, Strong Troll's Blood Elixir, 5 Daggerspine Scales, 5 Torn Fin Eyes. I have the items, my quest log shows "Complete", as does my map. Lydon shows not complete. Thus, I can't turn in the quest

**Comment by fvicaria** [comment]
Drop the quest and ask a GM to remove the quest from you log.
Then you should be able to retake it and complete it.
This can happen when you get multiple quests at once that require the same items.
