### ISSUE TITLE
[Raid] Trial of the Crusader

### ISSUE THREAD

**Issue by Plege** [WoWManiaUK/Redemption#1216]
If you enter Trial of the Crusader the door out gets barred instantly and not just during the encounters as it should. so if you enter in 25 mode but you want to go 10 man you need to be teleported out or hearth to dala and fly back.

The doors should only be barred during the encounters.

Regards
Pleg

**Comment by Noahcoke** [comment]
https://gyazo.com/3d1be50ed943d27cf94c539130685900
As described.
