### ISSUE TITLE
[NPC] Matthias Lehner

### ISSUE THREAD

**Issue by Beffertje** [WoWManiaUK/Redemption#1218]
http://www.wowhead.com/npc=32497/matthias-lehner

missing npc Matthias lehner 
![wowscrnshot_052517_111734](https://cloud.githubusercontent.com/assets/28094698/26444313/3e510c8a-413c-11e7-91a1-30111104586f.jpg)

**Comment by Noahcoke** [comment]
https://gyazo.com/79dff342d2feed7b706d1c3495faf85d
Fix confirmed.
