### ISSUE TITLE
[Dungeon] Dire Maul East

### ISSUE THREAD

**Issue by laurana21** [WoWManiaUK/Redemption#1219]
Whip Lashers [NPC 13022]  , lvl 53-54 Non-Elites spawn seemingly at random and in great numbers, and hit extremely hard for non-elites. Consecration + Retribution aura should wipe them out almost instantly when I'm level 69. however, I died to them several times,while having no problem at all with the elites. I will provide a link with vanilla gaming below,as openwow seems to be down,and the wowhead entry has them at level 37 (aparrently a MoP lowering}

http://db.vanillagaming.org/?npc=13022

**Comment by Noahcoke** [comment]
I fought them on my mage (lvl80) now and they hit me for 300-350 dmg. Seems fine for me. Non-elite monsters inside dungeons are always a bit stronger than the normal ones you can find outside.

**Comment by laurana21** [comment]
i know they are stronger, but did they respawn out of nowhere for you as well...and like 15+ at a time?
