### ISSUE TITLE
[Raid] Trial of the Crusader Anub'Arak

### ISSUE THREAD

**Issue by Plege** [WoWManiaUK/Redemption#1220]
During the Anub'arak encounter he goes underground and spikes apear that chase players one at a time until they get stuck or kill the chased player. once they get stuck or killed a player they should target a new one and chase that one until stuck or kill and so on until the phase is over.

Now the bug is, that they stay in the same spot after they kill a player and don't retarget, making the phase much too easy after one player dies. to my knowledge they properly retarget if they get stuck in a frost patch not after a kill however.

During the encounter there are frost orbs to be killed so they fall to the ground as a safety zone in the underground phase of the encounter. As usual those mechanics and pathing things have an anchor or what it is called (the elementals usually only visible to a gm) during this encounter however everyone can see those bodies so it might be a relatively simple visibility issue of purely estetic nature.

https://www.wow-mania.com/armory/?npc=34564

Regards 
Pleg

**Comment by fvicaria** [comment]
What is the id of the spikes?

**Comment by Noahcoke** [comment]
It worked fine for me on the first icy ground. The spikes stopped as intended and came back up again after few seconds to chase me. After the first stop no icy ground would stop the spikes anymore. They would just ignore them and continue chasing. Even spawning new ones during the chasing phase wouldnt help.
