### ISSUE TITLE
Northrend Quest line

### ISSUE THREAD

**Issue by sirheath** [WoWManiaUK/Redemption#1222]
The quest giver is High Executor Anselm. The subquest giver is Captian Harker. 
Part 4 of Reports from the field. I unstuck and got teleaported to Trisfall when i went back the Bat Handler would not allow a second flight to the ship nor could i abandon and pick it back up as i already completed the previous quests

**Comment by elagen** [comment]
**https://github.com/WoWManiaUK/Redemption/wiki/How-to-Properly-Report-an-Issue**

**Comment by Plege** [comment]
cannot reproduce. even after unstuck i can go back to the windrunner and pick the flight option again. alternatively you can swin to the boat and do whatever you need to do there
