### ISSUE TITLE
Halls of Reflection. Last Boss, Ghouls. 

### ISSUE THREAD

**Issue by Noahcoke** [WoWManiaUK/Redemption#1223]
I just did that dungeon and on the last phase when you have to escape lich king doesnt spawn as many ghouls as shown before via DBM. There was always only 1 ghoul being spawned, while it should have been several at once. 

http://www.wowhead.com/npc=36940/raging-ghoul
http://www.wowhead.com/npc=37226/the-lich-king (ID as he can be found in HoR)

**Comment by Plege** [comment]
I can confirm that there are 3 kinds of adds the LK spawns during the escape in HoR, Lumbering Abominations (https://www.wow-mania.com/armory/?npc=37069), risen witch doctors (https://www.wow-mania.com/armory/?npc=36941) and raging ghouls (https://www.wow-mania.com/armory/?npc=36940).

The first two Abominations and Witch Doctors spawn in the corect amoun. However the Raging Ghouls did not spawn at all not one at any time during the escape. this makes the encounter quite easy to beat as it is at the moment.

Regards
Pleg

**Comment by Anthonhed** [comment]
I can still confirm that no raging ghouls is spawning
