### ISSUE TITLE
Transmog Issue

### ISSUE THREAD

**Issue by Warlloxx** [WoWManiaUK/Redemption#1224]
Issue: 
Artifact item -Skull of Man'ari - After being purchased from the transmog shop, does not allow for a transmog.

Further details:
Using latest update on the server.
I have an offhand weapon for this offhand artifact xmog.
The option to transmog the item simply doesn't come up when speaking to the appropriate xmog npc.

**Comment by Warlloxx** [comment]
![wowscrnshot_052517_221846](https://cloud.githubusercontent.com/assets/28966686/26471418/79b57a88-4199-11e7-8bee-2b9ae8098674.jpg)
![wowscrnshot_052517_221859](https://cloud.githubusercontent.com/assets/28966686/26471421/7c92181a-4199-11e7-8b1b-12a131134798.jpg)
![wowscrnshot_052517_221905](https://cloud.githubusercontent.com/assets/28966686/26471423/80204a42-4199-11e7-87b0-d85adb784f74.jpg)

**Comment by fvicaria** [comment]
Fixed in dev. We should release Wednesday at the latest.

![image](https://cloud.githubusercontent.com/assets/9414661/26490700/5740a7b4-4204-11e7-8f37-39b27edee184.png)
