### ISSUE TITLE
DK ghoul

### ISSUE THREAD

**Issue by Godzila1234** [WoWManiaUK/Redemption#1225]
After the new update and patch 2.0.8b i tested the issue i reported earlier https://github.com/WoWManiaUK/Redemption/issues/1193#event-1090502072 and the first bug still apears,
After you die in WSG/WG so you get autoress and summon of the pet and dismount the pet dies. The Pet dont die after dismount if you havent died at least once or out of battleground time. I have screenshots if need.
Thank you for your attention and work!

**Comment by Plege** [comment]
I tried this issue on my DK during WG. I tried it before I died and after, the issue you describe cannot be reproduced. In case we did something wrong or you experience it again please make a video and upload so we can further investigate. Until further proofe is given I'll close this issue.

Regards,
Pleg

**Comment by Godzila1234** [comment]
The bug appears  after few games not at once, if restart the client the bug desapear and shows again after some time 3-4 games or so, i have screenshots but will try to make video too. When i have the video will make in game ticket because i gues could be problem of my dk only or my account because the same issue appears on my warlock that is on the same account. Plus i havent heard complains from other players but maybe because they dont play so much battlegrounds in row
