### ISSUE TITLE
Wintergrasp Spirit healer

### ISSUE THREAD

**Issue by Dusticles** [WoWManiaUK/Redemption#1228]
The alliance base on the losing side's Spirit Healer does not ressurrect players after countdown.

**Comment by fvicaria** [comment]
When that happens just use the dialog to move GY.

**Comment by elagen** [comment]
i can confirm that the http://www.wowhead.com/npc=31842/dwarven-spirit-guide at the Ally base does NOT resurrect the dead when the Timers goes to 0
