### ISSUE TITLE
[Quest] The Purification of Quel'Delar

### ISSUE THREAD

**Issue by grieptoo** [WoWManiaUK/Redemption#1231]
According to the quest text you have to speak to a Warden of the Sunwell. Then you should be sent to Sunwell. This does not work. The Warden of the Sunwell's response does nothing.

**Comment by Noahcoke** [comment]
Please add the questlink of wowhead to your comment. 
https://github.com/wow-mania/Redemption/wiki/How-to-Properly-Report-an-Issue

**Comment by fvicaria** [comment]
The quest works. There is an NPC there to talk to you.

**Comment by Noahcoke** [comment]
Npc was there, option to get teleported inside the sunwell works. Quest could be completed.
