### ISSUE TITLE
[Quest] Flight of the Wintergarde Defender

### ISSUE THREAD

**Issue by Kurekur** [WoWManiaUK/Redemption#1233]
[http://www.wow-mania.com/armory/?quest=12237](http://www.wow-mania.com/armory/?quest=12237)

Players must use Wintergarde Gryphon Whistle [http://www.wow-mania.com/armory/?item=37287](http://www.wow-mania.com/armory/?item=37287) 
to call Wintergarde Gryphon [http://www.wow-mania.com/armory/?npc=27258](http://www.wow-mania.com/armory/?npc=27258) .
On this gryphon players have to fly rescue Helpless Wintergarde Villagers [http://www.wow-mania.com/armory/?npc=27336](http://www.wow-mania.com/armory/?npc=27336) or [http://www.wow-mania.com/armory/?npc=27315](http://www.wow-mania.com/armory/?npc=27315) 
and bring them back to Wintergarde Gryphon Station [http://www.wow-mania.com/armory/?search=wintergarde+gryphon+station#objects](http://www.wow-mania.com/armory/?search=wintergarde+gryphon+station#objects).

The problem is that NPCs Helpless Wintergarde Villager [http://www.wow-mania.com/armory/?npc=27336](http://www.wow-mania.com/armory/?npc=27336) or [http://www.wow-mania.com/armory/?npc=27315](http://www.wow-mania.com/armory/?npc=27315) are not in the location, or I have seen two of them (tried to search them several times), but they disappeared before I could get to them.

**Comment by fvicaria** [comment]
The quest works. The issue is you are missing some requirement. You may have skipped a quest which puts you in the wrong phase.

**Comment by fvicaria** [comment]
![image](https://cloud.githubusercontent.com/assets/9414661/26529011/b5298ea2-43af-11e7-8091-023394a3cc15.png)
