### ISSUE TITLE
[Quest] Fortunate Misunderstandings (Sholazar Basin)

### ISSUE THREAD

**Issue by Legadin** [WoWManiaUK/Redemption#1234]
For the quest "Fortunate Misunderstandings" and begin the reputation with the Oracles, we need to escort a "Injured Rainspeaker Oracle" which doesn't seem to want to move ! There is two of them, none is moving.

**Comment by elagen** [comment]
https://github.com/WoWManiaUK/Redemption/wiki/How-to-Properly-Report-an-Issue

**Comment by fvicaria** [comment]
It worked fine for me. Drop the quest and try to get it again. Also clear cache.
