### ISSUE TITLE
Cant hear other peoples emotes

### ISSUE THREAD

**Issue by Blavaga** [WoWManiaUK/Redemption#1235]
Me and multiple people have been having a problem on the server when we type lol, we cannot hear laughter, or someone else cannot hear another persons emotes, we can still hear our own, but not other peoples voice emotes. I was wondering if there was going to be a fix for this anytime soon?

**Comment by elagen** [comment]
Make sure in your sound settings that Emote sounds are on and Turn up the ingame Volume - Make sure that is done first and see what happens

![wowscrnshot_052917_073226](https://cloud.githubusercontent.com/assets/22685042/26538838/0d3c54e4-4441-11e7-87f8-a38aa936e8da.jpg)

![wowscrnshot_052917_073231](https://cloud.githubusercontent.com/assets/22685042/26538856/1c4137f2-4441-11e7-8dba-31d7f2c979de.jpg)

**Comment by Blavaga** [comment]
I already did this and so have multiple people, we still cannot hear anybodies emotes.

**Comment by fvicaria** [comment]
This is a client issue. Make sure you have our client fully patched and have setup you setting accordingly.
