### ISSUE TITLE
 [Quest] The Assassination of Harold Lane (id: 11892)

### ISSUE THREAD

**Issue by furkanaltur34** [WoWManiaUK/Redemption#1236]
While in combat with mob, using quest item must be summon some animals for aid but it isnt.

**Comment by fvicaria** [comment]
Please follow the procedure described below before creating a new issue:
[How to Properly Report an Issue](https://github.com/wow-mania/Redemption/wiki/How-to-Properly-Report-an-Issue)

This will help developers identify and fix the issue quicker. Incorrectly or unclear reports will simply be deleted.

**Comment by fvicaria** [comment]
http://www.wowhead.com/quest=11892/the-assassination-of-harold-lane

**Comment by elagen** [comment]
i can confirm that http://www.wowhead.com/item=35293/cenarion-horn#comments this object from the quest calls forth a stampede that takes harold lane to 50% - This is not happening

**Comment by fvicaria** [comment]
Select the Alliance Landing option and you will be revived.

**Comment by Freakster1** [comment]
Hello Team,

Verified the quest the horn is not working.

 [Cenarion Horn]

Nothing happens to harald.

Tested as allaince char

Thanks
Freak

**Comment by Phantomyzed** [comment]
there is a 2nd option to do the quest since i failed few times with the horn i got one of the mammoths and killed him with that mammoth and it counted it as a quest completed.

**Comment by captainloozer** [comment]
Quest item is confirmed still bugged.

https://www.youtube.com/watch?v=dZqlxqbrJaY

**Comment by VA-L** [comment]
- Harold Lane is now stunned for 5 seconds when the item is used (Found what spell was used here)
- During that time, Stampede Mammoth, Caribous, Rhinos will spawn and run through him and cause him to loose 50% of his life (like it should be)
- The quest item is now only usable once during the fight (Using it twice will not do anything)
- The quest item is now only usable on Harold Lane.

Up to test.
