### ISSUE TITLE
[Quest] Orgrim's Hammer

### ISSUE THREAD

**Issue by nhorvat** [WoWManiaUK/Redemption#1237]
http://www.wowhead.com/quest=13224/orgrims-hammer

As you can see on screenshot, I have the quest mentioned above, but there is no NPC to turn it in.
NPC link: http://www.wowhead.com/npc=30824/sky-reaver-korm-blackscar
http://wow-mania.com/armory/?npc=30824

![wowscrnshot_053017_162231](https://cloud.githubusercontent.com/assets/1204798/26588164/c9b0c34e-4554-11e7-8db0-6d5e3229278b.jpg)

**Comment by fvicaria** [comment]
This is a know issue. NPC will reappear.

**Comment by nhorvat** [comment]
Nevermind, I spent only 5 hours here waiting. Will reappear when? Server restart? More info please!

**Comment by nhorvat** [comment]
Another day. Still no respawn!
