### ISSUE TITLE
[Quest]  Patching Up

### ISSUE THREAD

**Issue by Eirolla** [WoWManiaUK/Redemption#1238]
http://www.wowhead.com/quest=11894/patching-up

**Comment by furkanaltur34** [comment]
it says Requires Geyser Fields Steam Vent all time

**Comment by fvicaria** [comment]
You are not in the correct position.

**Comment by furkanaltur34** [comment]
its badly scripted quest ..

**Comment by Rushor** [comment]
made the spots better now. some were correct, some were wrong. this is all working now.

https://i.imgur.com/ZAFPPOa.jpg

**Comment by Rushor** [comment]
i do this because the quest is one of the pre quests to battle for the undercity
