### ISSUE TITLE
Ret pala talent

### ISSUE THREAD

**Issue by muhabayern21** [WoWManiaUK/Redemption#1240]
i have just noticed that Pursuit of Justice talent doesnt work. It doesnt reduce disarm effect. i tested vs warr which has 10 sec disarm, even with talent still 10 sec it should reduce 50%.

**Comment by Anthonhed** [comment]
I just tested this and it works good, used Dismantle on a Paladin that had that talent, reduced the time from 10 to 5 seconds. 

Make sure to check that you have that talent ;)
