### ISSUE TITLE
Mailbox issue.

### ISSUE THREAD

**Issue by Vaggosdragos** [WoWManiaUK/Redemption#1241]
When I send something that takes more than 1 slots via mailbox between characters of the same account, any other actions done before logging off from the sender gets cancelled.

For example: I put some gems on my sender character, moved around some items in my invetory and bank, sent a mail with full slots and then I relogged. Upon coming back, any action i had earlier done was rollbacked.

**Comment by ghostlynx-helios** [comment]
Attempting mailing between three characters.  Items disappear from inventory and mail appears sent as normal.  Logging on to receiving character show no items in mail, log back into sending character and items are back in inventory.

**Comment by fvicaria** [comment]
THis is a known issue we are working on. Not server but db related.
In the meantime mail one item at the time.
