### ISSUE TITLE
[QUEST] Draconis Gastritis

### ISSUE THREAD

**Issue by furkanaltur34** [WoWManiaUK/Redemption#1242]
http://www.wowhead.com/quest=11280/draconis-gastritis

**Comment by g0sy** [comment]
What seems to be the problem here?

**Comment by elagen** [comment]
https://github.com/WoWManiaUK/Redemption/wiki/How-to-Properly-Report-an-Issue

**Comment by furkanaltur34** [comment]
Whelp's not comes to meat.

**Comment by fvicaria** [comment]
You need to do that to the drakes already on the floor not the whelps
