### ISSUE TITLE
[Quest] GAMBLING DEBT 

### ISSUE THREAD

**Issue by furkanaltur34** [WoWManiaUK/Redemption#1243]
http://www.wowhead.com/quest=11464/gambling-debt 
"Silvermoon" Harry must be friendly after a fight, but i killed him

**Comment by furkanaltur34** [comment]
http://www.wowhead.com/npc=24539/silvermoon-harry

**Comment by Freakster1** [comment]
Hello Team,

This is a confirm issue Silvermoon Harry shouldn't die once he becomes low he pays the debt.

As he gives other quest.

To become friendly with silvermoon harry.

i did following chain quest 
1. Orfas the kamgua
2. The dead rise
3. Elder Atuik and Kamuga
4. Sindorai scying crystals

Once i ask him to pay debt he changes to unfriendly and dies when at 50% he should change to normal.

Confirmed issue

Thank you
Freak

**Comment by Freakster1** [comment]
Hello Team,

This quest also has one more bug the silvermoon harry gives quest item " ["Silvermoon" Harry's Debt]"
to people who dont have quest and directly comes in their inventory even if they dont have quest.

Thanks 
Freak
