### ISSUE TITLE
[QUEST]  The Frozen Heart of Isuldof

### ISSUE THREAD

**Issue by furkanaltur34** [WoWManiaUK/Redemption#1244]
http://www.wowhead.com/quest=11512/the-frozen-heart-of-isuldof
A bear named Hozzer must be sleep. in cave 
http://www.wowhead.com/npc=24547/hozzer

**Comment by fvicaria** [comment]
![image](https://cloud.githubusercontent.com/assets/9414661/26675043/4d8d7a34-46ba-11e7-849a-2f94bad71c36.png)

**Comment by furkanaltur34** [comment]
"bear must be sleeping"

**Comment by fvicaria** [comment]
check the video on wowhead or youtube.
