### ISSUE TITLE
missimg vpte points

### ISSUE THREAD

**Issue by Grafta** [WoWManiaUK/Redemption#1245]
I had 2598 vote points
I was sent 1878
max vote points per toon =1000
logged on to another toon as advised by weeble no points received
so I am missing 720 + 878 points

any help would be greatly appreciated as that is a lot of voting time

**Comment by fvicaria** [comment]
Contact support please.

**Comment by Grafta** [comment]
this is under support on website which is where weeble asked me to submit do I need to skype?

**Comment by fvicaria** [comment]
yes please. Skypename: wow-mania.com

**Comment by Grafta** [comment]
thank you

**Comment by Kharlah** [comment]
It appears to be happening.  Last 4 days haven't received my vote points
