### ISSUE TITLE
Feature Request: Ability to see what vote points succeed.

### ISSUE THREAD

**Issue by zinthose** [WoWManiaUK/Redemption#1247]
This is a low priority request in my opinion but I wanted to express my idea in the hopes that other players can better see how the vote system works and possibly indicate when "expected" delivery is.  

I know it is out of your hands since it is the vote sites that report back but the ability to have a log to view to show us when we screwed up and forgot to log in or the site is taking longer to report than usual ect. ect.

**Comment by fvicaria** [comment]
The vote points can be seen in the currency tab.
We have no way of predicting what you will definitely get on the next day as we depend on third party response.
Check the guide on how to vote on the forum and if you have any questions feel free to send me a message on skype.

Skypename: wow-mania.com
