### ISSUE TITLE
[Quest] The Calling

### ISSUE THREAD

**Issue by laurana21** [WoWManiaUK/Redemption#1249]
The Calling (ID 8315)
When you get to the bones of glakkarond, and attempt to draw the glyphs, when the bar gets to the end, you get an error message "you dont have a target" no wasps spawn and no Qiraji Emissary Spawns

http://www.wowhead.com/quest=8315/the-calling

**Comment by Freakster1** [comment]
Hello Team,

I verified the quest "The calling " we cannot complete it as the item " [Glyphs of Calling]" it initiates drawing in sand but and end it fails so there is a problem with provided item.

But it is a confirmed issue.

Thanks
Freak

**Comment by fvicaria** [comment]
Can you give me the coordinates please or some image

**Comment by fvicaria** [comment]
There is an issue with the spell.
I have added a temporary work-around to allow people to continue the quest chain.
The Emissary is now roaming the area and does not need to be summoned.
