### ISSUE TITLE
Assassination rogue: Overkill

### ISSUE THREAD

**Issue by Calerionthefirst** [WoWManiaUK/Redemption#1252]
The talent Overkill doesn't seem to work like it's supposed to. As soon as i enter stealth i get a buff (overkill). When i leave stealth it stays on as a buff and doesn't has a timer or any additional energy regen.
It should get a 20sec timer and additional energy regen (30%).

Calerion.
![screenshot_1](https://cloud.githubusercontent.com/assets/29158893/26751803/bb12cba2-4842-11e7-8506-c026052b72e4.png)
![screenshot_2](https://cloud.githubusercontent.com/assets/29158893/26751805/c2193a8a-4842-11e7-92cc-98a5976b23ba.png)

**Comment by lolleroman** [comment]
Confirmed.
