### ISSUE TITLE
[Spell] Lava Lash 25% bonus is not working

### ISSUE THREAD

**Issue by CrossFireBGD** [WoWManiaUK/Redemption#1253]
Shaman spell Lava Lash doesn't benefit from flametongue buff on offhand weapon.
Glyph of Lava Lash change tooltip of spell Lava Lash properly ingame (shown bonus 25% -> 35%)
but bonus itself is not applied.
Tested naked on SW training dummy lvl 80 with OFFHAND fist weapon http://wow-mania.com/armory/?item=50184 and glyph of Lava Lash http://wow-mania.com/armory/?item=41540
since i play on 5760 x 1080 resolution i  will provide source images and cropped ones
test 1 no flametongue :
http://imgur.com/niRPmdw
http://imgur.com/aHm0Vlu
test 2 with flametongue : 
http://imgur.com/ltBNZaB
http://imgur.com/5U0dDE3
glyph on :  
http://imgur.com/ZowtBUC
http://imgur.com/9nMZ1YK
source images
http://imgur.com/cFDHlO5
http://imgur.com/hJVCSw4
http://imgur.com/Y4RyJI6
http://imgur.com/FlNDsq1
http://imgur.com/DfkdRao
http://imgur.com/dsOifO2

**Comment by elagen** [comment]
i Cant seem to reproduce what the situation is - Lava Lash

i am getting the Damage bonuses from http://wow-mania.com/armory/?spell=60103  - Which if flametounge is Enchanted on the Offhand you gain 25% extra damage from lava lash

with that i am also getting the Extra 10% damage from the Glyph aswell

**Comment by CrossFireBGD** [comment]
i don't want to be rude but i retested right now with http://www.wow-mania.com/armory/?item=44241
and http://www.wow-mania.com/armory/?item=50184 and bonus is NOT applied 
issue is still there on redemtion
can you tell me at least how did u test this bug and with what weapon ?

**Comment by elagen** [comment]
The test is the exact same as red so it easier for us to test with tier items and weapons with no glyph on testing the damage then glyph testing the damage

**Comment by CrossFireBGD** [comment]
I see, i must explain this in detail.
Lava Lash damage varies with weapon damage variance, not every hit is the same, that's core mechanic of white hits. But bonus should increase that damage further.
My test was naked with only http://wow-mania.com/armory/?item=50184
My off hand weapon damage range is 305-500 with 769 AP so Lava Lash non crit without flametongue should hit in min/max range 305-500 average 400 and IT DOES , my recount shows min/max damage 335-486 on average 416.
But when i apply flametongue it should hit for at least 25% more so range of hits should be from min/max 381-625 and average 500 and this is not happening, with flametongue buff i also hit 335-490 average 416 which should not be possible. First absolutely minimal hit should be 381 and absolutely maximal hit should be 625 and average ~500 but Lava Lash hits the same as flametongue off. 
I am sorry for this wall of text but this is complicated mechanic, its hard to test fast, especially if you don't know what to look for. can I ask you to retest it again with more detail. i have tested this for the last 2 days with 6 weapons and bug is present on redemtion

**Comment by CrossFireBGD** [comment]
Hello again, i have spent some time testing with gear and results are the same.
I am 100% sure that bonus is not working. You have closed this issue prematurely.
Further proof:
no proc trinkets or totems only static gear
Geared No FT 
Lava Lash 30 normal hits - min 697 - avg 785 - max 880
Lava Lash 13 critical hits  - min 1423 - avg 1619 - max 1788
<a href="http://imgur.com/LpPumpL"><img src="http://i.imgur.com/LpPumpL.jpg" title="source: imgur.com" /></a>

Geared YES FT
Lava Lash 29 normal hits - min 693 - avg 793 - max 881
Lava Lash 21 critical hits  - min 1437 - avg 1644 - max 1806
<a href="http://imgur.com/SNazVug"><img src="http://i.imgur.com/SNazVug.jpg" title="source: imgur.com" /></a>
As you see they are identical, bonus is not applied. I have tried with off hand weapons,  one-handed weapons, maces and result is the same.
I will gladly demonstrate this issue ingame if you don't believe me. 
I would also want to post this on forum so that more shaman players can see the issue and test it.
This is not a game breaking bug for shamans but it is still a bug which should be ACKNOWLEDGED.
