### ISSUE TITLE
[Spell] Hungering Cold 

### ISSUE THREAD

**Issue by zyklonb** [WoWManiaUK/Redemption#1254]
Hungering cold is not working properly, it only freezes opponent for 5 seconds. It's supposed to be 10
https://youtu.be/HAqN1ODt71c

**Comment by elagen** [comment]
https://github.com/WoWManiaUK/Redemption/wiki/How-to-Properly-Report-an-Issue

**Comment by elagen** [comment]
http://www.wowhead.com/spell=61058/hungering-cold as you can see here is says Enemies within 10 yards are trapped in ice, preventing them from performing any action for 6 sec.

**Comment by zyklonb** [comment]
Hungering Cold	4.2.0 (Tue Aug 16 2011) Build 14107
Hungering Cold	4.2.0 (Tue Aug 16 2011) Build 14040
Hungering Cold	4.2.0 (Tue Aug 16 2011) Build 14002
Hungering Cold	4.1.0 (Thu May 05 2011) Build 13914
Hungering Cold	Before Build 13914

**Comment by fvicaria** [comment]
I will re-check it today
