### ISSUE TITLE
Sindragosa Unchained Magic.

### ISSUE THREAD

**Issue by Forrestxz** [WoWManiaUK/Redemption#1257]
Casters and healers don't share this debuff, but get one each. Or in 25-man, three each.

Unchained magic is currently random to every caster in the raid. In 25 man scenarios, there's even a chance that no healer gets it, or every possible healer gets it. 3 casters 3 healers getting unchained in 25m. 1 caster 1 healer in 10m. 

**How it currently works**: https://github.com/TrinityCore/TrinityCore/issues/5401

A Holy Priest using Circle of Healing on the raid with unchained magic. Circle of Healing (With glyph) should heal 6 people in 1 cast. During unchained magic, if you cast circle of healing you will get 6 stacks at once. The script considers circle of healing to be 6 separate casts because it healed 6 people. This also goes for every healer.

**How it should work:** Every cast, regardless of what it is, even CHANNELING spells, should all be giving 1 stack at the end of its cast. Nothing should be giving more than 1 because it heals more people. 

Quote:"My understanding is that while you have the Unchained Magic debuff, anything that you cast will cause a stack of Instability to build up. As a disc priest, I can confirm that Renew, Prayer of Mending, and Power Word: Shield will build stacks. Pain Suppression will also build stacks. I have been told that a mage's Blink will also build stacks. So regardless of whether you are a healer or a dps caster, any spell that is cast will create one stack of Instability (not just healing spells for healers and dps spells for dps). However, channeled spells will not build more stacks".

http://www.wowhead.com/spell=69762/unchained-magic#comments

**Comment by Noahcoke** [comment]
I can confirm this also for spells that are debuffs and proc later on. Just as it is with Living Bomb of mages (http://www.wowhead.com/spell=44457/living-bomb). It adds one stack upon casting and another stack when its finished and explodes. Same goes for Heroism (http://www.wowhead.com/spell=32182/heroism)/Bloodlust (http://www.wowhead.com/spell=204361/bloodlust) of shamans. Casting those will add 9 (with a 10man group) or 24 (in 25man group) stacks upon casting.
