### ISSUE TITLE
[Raid] Volatile Ooze/Gas Cloud attacking same target 

### ISSUE THREAD

**Issue by Forrestxz** [WoWManiaUK/Redemption#1259]
During the Professor encounter on heroic, there's a chance that both oozes may target 1 person, resulting in a guaranteed wipe during the transition.

Issue and solutions also posted here.
https://github.com/TrinityCore/TrinityCore/issues/8680

**Comment by fvicaria** [comment]
This is not forbidden. There is a chance of happening.
