### ISSUE TITLE
[Raid] Prince Keleseth movement bug.

### ISSUE THREAD

**Issue by Forrestxz** [WoWManiaUK/Redemption#1260]
Prince Keleseth's cast range should be a lot bigger as a caster.

**How it works:** Keleseth is right at melee range on whoever's tanking it and keeps following it around when the tank moves. This makes it really hard for melee DPS to swap to Keleseth when he activates due to the orbs taking damage and falling.

**How it should work:** Tank should be collecting orbs before Keleseth activates, once it does activate, tank should be ready to run out of range tanking it from far away keeping the orbs on him while the raid can safely swap to Keleseth.

**Demonstration (0:20)**: https://www.youtube.com/watch?v=0SBoGZEf3Dk

**Comment by Plege** [comment]
I can confirm that Keleseth follows the tank around making it hard to avoid orbs getting killed when aoe happens. if Keleseth uses his attacks at a higher rank (as he is casting anyway) this might make the encounter more retail like and more organized.
