### ISSUE TITLE
[Raid] Sindragosa Tomb Bug.

### ISSUE THREAD

**Issue by Forrestxz** [WoWManiaUK/Redemption#1262]
**How tombs currently work during air phase:** If tombs aren't freed fast enough after the air phase, the players in the tombs get a debuff called Asphyxiation (http://www.wowhead.com/spell=71665/asphyxiation#comments) which kills them if not freed.

**How tombs currently work during phase 2:** Regardless of the time the person is in tomb, Asphyxiation never occurs, which basically means that 1 tomb could be used throughout the whole fight to reset (http://www.wowhead.com/spell=70127/mystic-buffet) Mystic buffet stacks. This makes the encounter incredibly easy to deal with Mystic buffet as well as killing the boss.

**How tombs SHOULD work during phase 2:** Same as every other (http://www.wowhead.com/spell=70157/ice-tomb#comments) Ice tomb, if the tomb isnt killed within 20 seconds, the tombed player gets asphyxiation, just like in the other phase if they're tombed. 

**Phase Two
All Phase One abilities, plus: Mystic Buffet**

http://wowwiki.wikia.com/wiki/Sindragosa_(tactics)

**Comment by Noahcoke** [comment]
Can confirm that. It is working like that for quite a long time already.

**Comment by Noahcoke** [comment]
I tested the fight. The suffocation debuff only applies on the tombs in air phase, but not on the ones in 2nd/lase phase.
