### ISSUE TITLE
[Icecrown Citadel - The Lich King] Timers for all Spells with fixes

### ISSUE THREAD

**Issue by keidian** [WoWManiaUK/Redemption#1263]
The Lich King (Normal and Heroic] timers for almost every ability are offset making it hard for raid leaders to announce abilities and this brings up several issues. Some timer offset also cause the encounter to be a lot different from what it's supposed to be like in terms of timers interfering with each other. This can be seen for example that The Lich King is casting Vile Spirits only once per outside frostmourne phase in Heroic mode instead of twice.

I am going to suggest fixes to the timers so they're correct according to DBM and BigWigs which were both 100% during the time of retail and there's enough proof of it on Youtube. I am assuming that your LK script is pretty much default TC, which is according to our raid attempts correct because the timers are wrong "exactly the way they should be wrong". 

# Phase 1 Timers

## Necrotic Plague Initial Timer [Line 559]:
At the moment: `events.ScheduleEvent(EVENT_NECROTIC_PLAGUE, urand(30000, 33000), 0, PHASE_ONE);`
Should be        : `events.ScheduleEvent(EVENT_NECROTIC_PLAGUE, urand(27000, 27500), 0, PHASE_ONE);`

## Necrotic Plague Repeating Timer [Line 941]:

At the moment: `events.ScheduleEvent(EVENT_NECROTIC_PLAGUE, urand(30000, 33000), 0, PHASE_ONE);`
Should be        : `events.ScheduleEvent(EVENT_NECROTIC_PLAGUE, urand(30000, 30500), 0, PHASE_ONE);`

## Infest Repeating Timer [Line 933]:
At the moment: `events.ScheduleEvent(EVENT_INFEST, urand(21000, 24000)`
Should be        : `events.ScheduleEvent(EVENT_INFEST, urand(22000, 22500)`

## Soul Reaper Repeating Timer [Line 950}
Should be `events.ScheduleEvent(EVENT_SOUL_REAPER, urand(30000, 30500), 0, PHASE_TWO_THREE);`

# Phase 1,5 Timers (First Transition Phase) 
From now on I will only post the correct timers and lines and hope that you will insert them

## Raging Spirit Initial Timer [Line 829]:
Should be: `events.ScheduleEvent(EVENT_SUMMON_RAGING_SPIRIT, 6000, 0, PHASE_TRANSITION);`

## Pain and Suffering Repeating Timer [Line 969]
Should be `events.ScheduleEvent(EVENT_PAIN_AND_SUFFERING, urand(1000, 2500), 0, PHASE_TRANSITION);`

## Defile Initial Timer [Line 832] 
Should be `events.ScheduleEvent(EVENT_DEFILE, 98000, 0, PHASE_TWO);`

## Val'Kyr Initial Timer [Line 830] 
Should be ` events.ScheduleEvent(EVENT_SUMMON_VALKYR, 80000, 0, PHASE_TWO);`

## Infest Initial Timer [831]
Should be `events.ScheduleEvent(EVENT_INFEST, 74000, 0, PHASE_TWO);`

## Soul Reaper Initial Timer [833]
Should be `events.ScheduleEvent(EVENT_SOUL_REAPER, 100000, 0, PHASE_TWO);`

# Phase 2 Timers 

## Defile Repeating Timer [958]
Should be `events.ScheduleEvent(EVENT_DEFILE, urand(32000, 32500), 0, PHASE_TWO_THREE);`

## Val'Kyr Repeating Timer [998]
Should be `events.ScheduleEvent(EVENT_SUMMON_VALKYR, urand(44500, 45000), 0, PHASE_TWO);`

# Phase 2.5 Timers (Second Transition Phase) 

## Defile Initial Timer [846]
Should be  `events.ScheduleEvent(EVENT_DEFILE, 98000, 0, PHASE_THREE);`

## Harvest Soul(s) Initial Timer [849]
Should be `events.ScheduleEvent(IsHeroic() ? EVENT_HARVEST_SOULS : EVENT_HARVEST_SOUL, 74000, 0, PHASE_THREE);`

# Phase 3 Timers 

## Vile Spirits Repeating Timer [1008]
Should be `events.ScheduleEvent(EVENT_VILE_SPIRITS, urand(30000, 30500), EVENT_GROUP_VILE_SPIRITS, PHASE_THREE);`

That's mostly it for now, if you merge all those timers with your core The Lich King encounter will become a lot smoother experience and it will feel more Blizzlike. If you want me to do more timer updates for other bosses such as Sindragosa (which is all over the place) then just comment on this post and I will do it.

**Comment by lolleroman** [comment]
Can confirm.
