### ISSUE TITLE
[(HC) Icecrown Citadel - The Lich King] Vile Spirits engaging during Harvest Soul

### ISSUE THREAD

**Issue by keidian** [WoWManiaUK/Redemption#1264]
Vile Spirits during the Lich King encounter are not supposed to engage while he's casting Harvest Soul. (can be seen here https://www.youtube.com/watch?v=xYhVIIlJhNk&t=17m58s) Instead they should become passive and engage after the group exits the Frostmourne room. If you consider #1263 legit and merge it with the core it also will collaborate to this issue because then The Lich King will properly cast Vile Spirits in a correct sequence according to Harvest souls.

**Comment by Forrestxz** [comment]
Indeed, happened in our 10 heroic run. Wiped us a few times, vile spirits running into us during the harvest soul cast. We got through it after really thinking it through with positioning, actually a gamebreaking bug, impossible to avoid deaths.
