### ISSUE TITLE
[Talent - Shaman - Restoration]  Nature's Guardian

### ISSUE THREAD

**Issue by keidian** [WoWManiaUK/Redemption#1265]
Whenever you drop below 30% health this talent should proc for 10 seconds but it just doesen't proc at all.

**Comment by fvicaria** [comment]
What spell are you talking about?

**Comment by keidian** [comment]
http://wow-mania.com/armory/?spell=30886

**Comment by Freakster1** [comment]
Hello Team,

I have verified the talent however i found that it is working but doesnt have 100 % chance to occur , sometimes it occurs and sometimes it doesn't.

I have verified by changing talents to 3 , 4 and 5 and found the skill working.

Request to kindly consider it tweaking if u think it should occur 100% or else it is working.

Thanks and Regards,

Freakster

**Comment by fvicaria** [comment]
This is statistical. If you throw a coin 5 times and get 5 heads is the coin rigged?
