### ISSUE TITLE
[Icecrown Citadel - Sindragosa] Timers for all Spells with fixes

### ISSUE THREAD

**Issue by keidian** [WoWManiaUK/Redemption#1267]
As for The Lich King, Sindragosa too, is all over the place. This is severly bugging the encounter by some weird event such as an Icy Grip occuring right before a Frost breath which never happened on retail causing random unavoidable deaths to people. Here are the correct timers.

# Frost Breath repeating timer [462]
Should be `   events.ScheduleEvent(EVENT_FROST_BREATH, urand(22000, 22500), EVENT_GROUP_LAND_PHASE);`

# Unchained Magic repeating timer [467]
Should be `events.ScheduleEvent(EVENT_UNCHAINED_MAGIC, urand(30000, 30500), EVENT_GROUP_LAND_PHASE);`

# Ice Tomb repeating timer [506]
Should be `events.ScheduleEvent(EVENT_ICE_TOMB, urand(16000, 16500));`

# Icy Grip Initial Timer (after event_land) [530]
Should be ` events.ScheduleEvent(EVENT_ICY_GRIP, urand(35000, 35500), EVENT_GROUP_LAND_PHASE);`

# Unchained Magic Initial Timer (after event_land) [529]
Should be ` events.ScheduleEvent(EVENT_UNCHAINED_MAGIC, urand(14500, 15000), EVENT_GROUP_LAND_PHASE);`

# Frost Breath Initial Timer (after event_land) [528]
Should be `events.ScheduleEvent(EVENT_FROST_BREATH, urand(22000, 22500), EVENT_GROUP_LAND_PHASE);`

# Icy Grip Reschedule Timer (phase_2) [539]
Should be `events.RescheduleEvent(EVENT_ICY_GRIP, urand(34500, 35000));`

This should fix most game breaking issues with Sindragosa. I will soon submit a post for Professor Putricide too.

**Comment by Forrestxz** [comment]
Confirmed, timers make the encounter messy as hell completely overlapping spells they shouldnt like Ice Tomb on top of Blistering Cold. Sindragosa breath right after Blistering cold.
