### ISSUE TITLE
Dual Talent Spec of Paladin

### ISSUE THREAD

**Issue by foxtoopia12** [WoWManiaUK/Redemption#1268]
I have retribution paladin. I buy him dual talent spec and I choose holy as my offspec. This is my gear and stat as ret paladin
![image](https://user-images.githubusercontent.com/28296117/26985839-82616930-4d6f-11e7-92c4-b4d1b1956ff4.png)
With that bonus healing of 1076, I can hit noncrit of Flash of Light for about 1.8k-1.9k and hit noncrit of Holy Light for about 6k.
Noncrit of Flash of Light
![image](https://user-images.githubusercontent.com/28296117/26985917-c615f8da-4d6f-11e7-9193-10ddb186cf3a.png)
Noncrit of Holy Light
![image](https://user-images.githubusercontent.com/28296117/26985951-d830f812-4d6f-11e7-86ff-e40741ae03ec.png)

Meanwhile, when I change to my offspec, i.e. Holy Paladin with following gear (bonus healing of 1811), I can only hit noncrit of FoL for 1.3k and noncrit of HL for 2.7k. I don't use Divine Plea and I don't think my healing as holy paladin represents the amount of my bonus healing.
Gear and stat as holy paladin
![image](https://user-images.githubusercontent.com/28296117/26986030-144b9140-4d70-11e7-9c15-daa473aa2a04.png)
Noncrit of Flash of Light
![image](https://user-images.githubusercontent.com/28296117/26986077-3a6de51c-4d70-11e7-9856-7b86670b362f.png)
Noncrit of Holy Light
![image](https://user-images.githubusercontent.com/28296117/26986088-44fdf8b4-4d70-11e7-8cd7-50018b9b7992.png)
I have no idea what's happening but I think that this shouldn't be happening and I should be able to heal as many as I heal as ret paladin. Please check on this and fix. Thanks in advance.

**Comment by Freakster1** [comment]
Hello Team ,

 i have verified the issue on my paladin i didn't find any issues in dual talents nor in healing, however from my side i feel there is no issue in paladin talents or healing.

i have kept my main talents as retribution and off as holy however i have verified with retri items and holy items too couldn't find any issue.

Thanks and Regards,

Freak

**Comment by foxtoopia12** [comment]
How can you reject my post just by reading one post that confirms that there's no problem with paladin healing in my character?
