### ISSUE TITLE
[Quest] The Scarlet Apocalypse

### ISSUE THREAD

**Issue by TheGreyMouser** [WoWManiaUK/Redemption#1269]
when trying to complete this quest, the lich king is actually inside the platform he is supposed to be standing on.  By going to the side, you can get the quest panel to open by clicking while jumping, but it will not complete as you are to far from NPC.  
http://imgur.com/a/QmpAg
http://imgur.com/4dAm8Nw

**Comment by Anthonhed** [comment]
I can confirm this issue after I leveled a DK myself
