### ISSUE TITLE
[Quest] Mystery of the Infinite

### ISSUE THREAD

**Issue by Damorka** [WoWManiaUK/Redemption#1270]
As quest requested I have put hourglas on the sand and defended it with my future self. At the end the hourglas revealed Nozdormu. Unfortunately the quest is not compleated in questlog and cannot be turned in. Screenshot to prove that quest was compleated

![wow_2017_06_10_13_20_36_473](https://user-images.githubusercontent.com/29342225/27006149-5d183fdc-4e2d-11e7-889e-5b036f4ee7d7.jpg)

**Comment by Anthonhed** [comment]
Please include ID's and explain a little more thanks!
https://github.com/WoWManiaUK/Redemption/wiki/How-to-Properly-Report-an-Issue

**Comment by elagen** [comment]
i have just Done both Quests without any problem i can not reproduce the Non completion
