### ISSUE TITLE
(Quest) You'll Need A Bear, Sons of Hodir quest chain

### ISSUE THREAD

**Issue by HarryOger** [WoWManiaUK/Redemption#1271]
I am unable to proceed with the quest chain as the NPC I need to talk to,  Brijana, disappears before I can get in range to talk to her (phasing related?)

**Comment by HarryOger** [comment]
![wowscrnshot_061017_160253](https://user-images.githubusercontent.com/26450404/27006912-586ce1d6-4df6-11e7-8468-58fadb8d2117.jpg)
![wowscrnshot_061017_160300](https://user-images.githubusercontent.com/26450404/27006913-586e5c78-4df6-11e7-84f4-3f1a5b9b180b.jpg)
![wowscrnshot_061017_160435](https://user-images.githubusercontent.com/26450404/27006919-8892a8be-4df6-11e7-877d-ce949be44e77.jpg)

http://www.wowhead.com/quest=12972/youll-need-a-bear

**Comment by Noahcoke** [comment]
That issue was posted some time ago already. It couldnt be reproduced. Please follow the steps recommended there. 
https://github.com/WoWManiaUK/Redemption/issues/1174

**Comment by HarryOger** [comment]
I have followed the quest chain ( http://wowwiki.wikia.com/wiki/The_Sons_of_Hodir_quest_chain) up to the Need a Bear quest.  As you can see in the SS attached I have the disguise buff referenced in https://github.com/WoWManiaUK/Redemption/issues/1174.   Is the relevant phasing related to the quest chain from the drop item for http://wowwiki.wikia.com/wiki/Quest:A_Spark_of_Hope.  This item already dropped and the following quest http://wowwiki.wikia.com/wiki/Quest:Forging_an_Alliance is in my log.
![wowscrnshot_061017_170034](https://user-images.githubusercontent.com/26450404/27007170-5f74fa7e-4dfe-11e7-89ed-099f9c99979a.jpg)

**Comment by Noahcoke** [comment]
I also meant the step that suggests to write a ticket and ask a gm to complete it for you. If we can not reproduce the bug, we cant confirm/fix it either.

**Comment by HarryOger** [comment]
I started by writing a ticket and the GM told me to come here.

**Comment by fvicaria** [comment]
The quests individually work. The issue is the phasing due to skipping one or more along the way.
We need to know the exact sequence the player did to cause the issue.
