### ISSUE TITLE
Unresolved issue https://github.com/WoWManiaUK/Redemption/issues/1271

### ISSUE THREAD

**Issue by HarryOger** [WoWManiaUK/Redemption#1272]
This was closed with the issue unresolved.  The only suggestion given was to follow the relevant quest chain which I had already done.   If needed I can re supply the links and screen shots related to the issue with the Sons Of Hodir quest chain.
I have followed the quest chain ( http://wowwiki.wikia.com/wiki/The_Sons_of_Hodir_quest_chain) up to the Need a Bear quest. As you can see in the SS attached I have the disguise buff referenced in #1174. Is the relevant phasing related to the quest chain from the drop item for http://wowwiki.wikia.com/wiki/Quest:A_Spark_of_Hope. This item already dropped and the following quest http://wowwiki.wikia.com/wiki/Quest:Forging_an_Alliance is in my log.
![wowscrnshot_061017_170034](https://user-images.githubusercontent.com/26450404/27007314-fac194ba-4e03-11e7-8435-1f4920e920bd.jpg)

**Comment by HarryOger** [comment]
After talking to a GM again who helped me complete the above quest I now have a similar issue with the next step: Cold Hearted http://www.wowhead.com/quest=12856/cold-hearted
![wowscrnshot_061017_180505](https://user-images.githubusercontent.com/26450404/27007425-09f4b1fc-4e08-11e7-91af-5211d6c9c9f9.jpg)

**Comment by fvicaria** [comment]
It works.
