### ISSUE TITLE
[Quest] Whispers of the Raven God

### ISSUE THREAD

**Issue by StarrZappa11** [WoWManiaUK/Redemption#1273]
Unable to complete this quest, will not give credit towards the 4th Prophecy. I've attached a screenshot below to show you the Raven God does appear, but I am not given credit. I do have the buff as well for the ravenspeech.
![whispers of raven god](https://user-images.githubusercontent.com/29348748/27008299-e77ad8ac-4e3b-11e7-8c6c-1bcf03f6ef0e.png)

**Comment by Anthonhed** [comment]
You will need to take them in order, 1,2,3,4 to be able to get anything for the forth.
I just did this in that order and it worked just fine.
Cannot reproduce, closed

**Comment by StarrZappa11** [comment]
Just did your directions and am still not receiving credit for the fourth prophecy. Please advise.
