### ISSUE TITLE
[Skin] Dreadtusk - "Testing the Antidote"

### ISSUE THREAD

**Issue by hotdoggidy** [WoWManiaUK/Redemption#1274]
The quest can be completed as designed. This issue is strictly covering the SKIN on the boar. 

quest=10255
Dreadtusk npc=16992
Hulking helboar npc=16880
Felboar npc=21878

During the quest "testing the antidote" in Hellfire Peninsula, the player is meant to use an antidote to expunge Fel energy from some nearby "Hulking Helboars". This **SHOULD** transform them into "Dreadtusks" which have a black and green skin similar to "Felboars", gain BEAST as type and **SHOULD** be tameable by hunters. 

Currently on Redemption the Hulking Helboars do not change color or type when the antidote is used and they CANNOT be tamed. (still demons)

Taming the Dreadtusk during this quest is the only way for hunters to get a Boar with the black and green Felboar skin. This method was used alot in retail ever since the release of the quest in TBC.

Source 1: http://www.wowhead.com/npc=16992/dreadtusk#objective-of
Source 2: https://www.youtube.com/watch?v=RQqvmFCeFSI

Dreadtusk on Redemption, still black and red, still has "Demon" type.
![wowscrnshot_061017_212027](https://user-images.githubusercontent.com/23442126/27008300-c5fc2d7a-4e22-11e7-80c3-25283768cc34.jpg)

What Dreadtusks should look like. same skin as Felboars but no Demon type.
![206456-dreadtusk](https://user-images.githubusercontent.com/23442126/27008315-378896d6-4e23-11e7-814e-6cb7f27aa140.jpg)

**Comment by elagen** [comment]
According to sources that i have been reading these pets are not Tameable in pre-patches to 4.0.3

2010/12/03 (Patch 4.0.3)		
Well, with the new model, these are tamable :D

This is according to your Source 1 Website - and this is Patch 3.3.5a

2nd source is http://www.wowhunterpets.info/pets/dreadtusk - i do not know how accurate this is but again  this webstie says that the pet can NOT be tamed

Spawn Information
Is This Pet Elite? NO
Is This Pet A Quest Spawn? YES
Is This Pet A Rare Spawn? NO
Is This Pet Tameable? NO

**Comment by fvicaria** [comment]
As is. Model not available in WotLK and not tamable.
