### ISSUE TITLE
[Quest] Whispers of the Raven God

### ISSUE THREAD

**Issue by StarrZappa11** [WoWManiaUK/Redemption#1275]
Unable to receive credit for the fourth prophecy. Received an answer earlier explaining to recomplete the quest and do it in chronological order, this did not work. Please advise.

**Comment by elagen** [comment]
i can confirm that when Testing this quest that http://www.wowhead.com/object=184969/the-fourth-prophecy

i can not Activate this to complete the Quest

**Comment by fvicaria** [comment]
You need to have the following buff
http://www.wow-mania.com/armory/?spell=37466
The following NPC's will give it to you while fighting:

http://www.wow-mania.com/armory/?npc=19988
http://www.wow-mania.com/armory/?npc=19989
http://www.wow-mania.com/armory/?npc=19990
