### ISSUE TITLE
[Enchant] Black Magic Proc 

### ISSUE THREAD

**Issue by liam5413** [WoWManiaUK/Redemption#1276]
http://www.wow-mania.com/armory/?item=44495

Black magic back in patch 3.3.5 was considered the best in slot enchant for feral druids that are BiS geared or close to it. It would proc from shred, mangle and infected wounds. However on redemption this does not seem to be the case and BM cannot proc at all by feral druids. It would be great if i could get my BiS enchantment back like it was on retail. Thanks :)

forums posts from 3.3.5 wotlk back in 2009 - 

http://www.wowhead.com/forums&topic=167534.1#p2279252

**Comment by elagen** [comment]
i can confirm that Black Magic can proc Through some of the Druid abilities while in cat form

This may be pointless but..
As a feral druid, I have personally observed all of these abilities proc this enchant:
Shred
Mangle (both)
Maul

**Comment by Noahcoke** [comment]
Not working as intended yet, did not proc at all.
