### ISSUE TITLE
Missing mining nodes in Bloodmyst Isle

### ISSUE THREAD

**Issue by Yarien62** [WoWManiaUK/Redemption#1277]
Hi, (sorry in advance for my bad english..)

The nodes are the following :
- Copper Vein : only 3 nodes instead of 124
- Tin Vein : 0 nodes instead of 50
- Silver Vein : 0 nodes instead of 25

Source : http://www.wowhead.com/bloodmyst-isle#show:vein
Thank you in advance for the check :)

**Comment by fvicaria** [comment]
Where are your numbers from?
WoWhead is not wotlk compliant.
