### ISSUE TITLE
[Icecrown Citadel - Professor Putricide] Timers for all spells with fixes

### ISSUE THREAD

**Issue by keidian** [WoWManiaUK/Redemption#1280]
As in all previous posts, here's the correct timers for Putricide.

# Unstable Experiment Initial Timer [264]
Should be `events.ScheduleEvent(EVENT_UNSTABLE_EXPERIMENT, urand(29500, 30000));`

# Unstable Experiment Repeating Timer [611]
Should be `events.ScheduleEvent(EVENT_UNSTABLE_EXPERIMENT, urand(37500, 38000));`

# Malleable Goo Initial Timer [524]
Should be `events.ScheduleEvent(EVENT_MALLEABLE_GOO, urand(24500, 25000));`

# Malleable Goo Repeating Timer [647]
Should be `events.ScheduleEvent(EVENT_MALLEABLE_GOO, urand(24500, 25000));`

# Choking Gas Bomb Initial Timer [525]
Should be `events.ScheduleEvent(EVENT_CHOKING_GAS_BOMB, urand(14500, 15000));`

# Choking Gas Bomb Repeating Timer [652]
Should be `  events.ScheduleEvent(EVENT_CHOKING_GAS_BOMB, urand(34500, 35000));`

While picking up the right timers I noticed how fucked up the Putricide encounter is on default TrinityCore and how much of Initial timers are simply missing or conditions for different heroic mode timers etc. which also causes DBM to bug, however those timers are the most crucial once that cause problems.

**Comment by fvicaria** [comment]
@keidian If you wish to join our test team you are welcome. Just contact me or Elagen and we go from there.

**Comment by keidian** [comment]
@fvicaria Sure, you can add my skype I guess kaden_91
