### ISSUE TITLE
Halls of reflection/Wave glitch

### ISSUE THREAD

**Issue by ben2578** [WoWManiaUK/Redemption#1281]
During the wave phase, in the middle of battle everything just disappear, wave stop progressing. Doors are still lock prevent players from getting out as well. This happens too after a wipe, preventing players from entering the ring.

**Comment by fvicaria** [comment]
I need more info on this one.
When does it happen? Is it all the time or on specific conditions? 
Does it block you from finishing the dungeon?

**Comment by ben2578** [comment]
I do notice it happens when 1 party member dc or die. also after we killed Falric it happens. 

And yes, it block players from finishing the dungeon.  As the dungeon do not progress anymore, it just reset to wave 1/10 with no mobs.

I've only completed it twice with a very good party, we progress very quickly through the wave phase. ( Was the only two times it did not happened.)

**Comment by Noahcoke** [comment]
Did you do Halls of Reflection via Random Dungeon Finder or manually?
