### ISSUE TITLE
Vile spirits in Frostmourne.

### ISSUE THREAD

**Issue by lolleroman** [WoWManiaUK/Redemption#1282]
On heroic lichking Vile spirits seem like they lose their script after the first time. When they respawn they aggro right away without the script telling them to. also the movement changes to buggy up and down movement which causes them to move even faster that they are supposed to.

They arent supposed to aggro you even if you attack them, the script should tell them when to attack.

Here is an example of how they are supposed to move while coming down (the aggro is still bugged in this example)

https://www.youtube.com/watch?v=1ta1QoXED1Q

Here is an example what they do after they respawn.

https://www.youtube.com/watch?v=nVC3PD_KQF4

**Comment by Forrestxz** [comment]
Confirmed, tested on PTR with Midna.
