### ISSUE TITLE
[Quest] Reclaimed Treasures

### ISSUE THREAD

**Issue by GMWeeble** [WoWManiaUK/Redemption#1284]
The quest Reclaimed Treasures 
http://www.wowhead.com/quest=2342/reclaimed-treasures
http://www.wowhead.com/quest=1360/reclaimed-treasures

The Chest you loot inside the cave is not there. 

This video shows where it should be. 

https://www.youtube.com/watch?v=quxw3hl-J8c

**Comment by fvicaria** [comment]
![image](https://user-images.githubusercontent.com/9414661/27124642-aa076336-50e9-11e7-9207-d5a4f46a1d78.png)
![image](https://user-images.githubusercontent.com/9414661/27124742-e75db9c4-50e9-11e7-9219-e5baea8982d1.png)
