### ISSUE TITLE
[Quest] The Drakkensryd

### ISSUE THREAD

**Issue by HiImBean** [WoWManiaUK/Redemption#1285]
Area: Storm Peaks, Temple of Storms (NPCs are riding proto-drakes around in the air around the temple)
-NPC ID = 29694
-You are supposed to jump from proto-drake to proto-drake killing the  Hyldsmeet Drakerider (the jumping works but the Drakerider's are what the bug is about) but almost all of them are Evading and out of range, when they are clearly not out of range. (the quest is do-able but keep in mind it takes well over an hour to get all 10 kills depending on if you are lucky enough to encounter non-bugged NPCs).
-Attempted on 13/6/2017
-I've had multiple people in my guild tell me they have had the same issue as well as people in world chat that I have asked.
-http://www.wowhead.com/quest=12886/the-drakkensryd

**Comment by fvicaria** [comment]
Works

**Comment by HiImBean** [comment]
It "works" but it takes like an hour to do a quest, just because it works doesn't mean it should be fixed so that it isn't bugged to hell...

**Comment by fvicaria** [comment]
I will check it.
