### ISSUE TITLE
[Raid] Trial of the Crusader

### ISSUE THREAD

**Issue by GMWeeble** [WoWManiaUK/Redemption#1286]
Any NPC in the raid (First 4) Are bugging trough the floor  jumping up and down from the first floor to the floor by Anub'arak. The Bosses or adds are then out of line of sight and is not able to be attacked.

This has happend 25 Normal and 10 Normal

**Comment by Forrestxz** [comment]
Confirmed, happens during other raids as well, must be a pathing issue.
