### ISSUE TITLE
Valkyrs on Lichking

### ISSUE THREAD

**Issue by lolleroman** [WoWManiaUK/Redemption#1288]
They fly on different directions even if the group is stacked. And they teleport forward if they are stunned.

**Comment by Noahcoke** [comment]
Also the ground where the fight happens on acts in a weird way. When moving out for transition phase every mob drop through the ground and glitch their way up again. (Also Lich King does that.) Mages blinking will make them fall through the ground.

**Comment by keidian** [comment]
Can confirm

**Comment by Anthonhed** [comment]
I will close this issue because it's the same as https://github.com/WoWManiaUK/Redemption/issues/1291 and that one is more in-depth
