### ISSUE TITLE
[Icecrown Citadel - Sindragosa] Ice Tomb Asphyxiation in phase 2

### ISSUE THREAD

**Issue by keidian** [WoWManiaUK/Redemption#1289]
In the Sindragosa encounter in phase 2 Asphyxiation is happening instantly. It should happen after 20 seconds

**Comment by Forrestxz** [comment]
confirmed

**Comment by elagen** [comment]
http://www.wowhead.com/spell=71665/asphyxiation

**Comment by keidian** [comment]
Asphyxiation is instantly applied the moment Sindragosa entombs her target in phase 2, it should happen after 20 seconds not instantly.
