### ISSUE TITLE
[Icecrown Citadel - Professor Putricide] Mutated Plague and Unbound Plague

### ISSUE THREAD

**Issue by keidian** [WoWManiaUK/Redemption#1290]
# Mutated Plague Issue [ID: 72451]
- It doesen't deal damage to the tank nor the raid
## How it should work: 
- During Phase 3, every 10 seconds Putricide puts one stack of this debuff on his target (=the tanks). Every 3 seconds, each Mutated Plague stack deals shadow damage to the whole raid according to the following list: 1-2 stacks ~500 dmg, 3 stacks ~1,200 dmg, 4 stacks ~2,900 dmg, 5 stacks ~7000 dmg. Each target affected by Mutated Plague deals this damage independently. Whenever a target with the debuff dies or loses his/her stack in any other way, Putricide will be healed for 300,000 per stack of debuff that target had.

# Unbound Plague Issue [ID: 70911]
- It is removed by Cloak of Shadows (31224) even though no ability should be able to remove it

**Comment by Forrestxz** [comment]
Confirmed, both 10/25 heroic.

**Comment by Brayton-mania** [comment]
The mutated Plague should heal Putricide for: 
- Value: 120,000
- Value: 680,000 - 25 Player (Legacy)
- Value: 200,000 - 10 Player Heroic (Legacy)
- Value: 840,000 - 25 Player Heroic (Legacy)

http://www.wowhead.com/spell=72745/mutated-plague

**Comment by keidian** [comment]
@Brayton-mania That is only when he kills his target with the stacks though

**Comment by keidian** [comment]
Unbound Plague still is removed by Cloak of Shadows. Mutated Plague is now working in Dev
