### ISSUE TITLE
[Icecrown Citadel - The Lich King] Val'Kyr Shadowguard 

### ISSUE THREAD

**Issue by keidian** [WoWManiaUK/Redemption#1291]
How it should work 
- Val'kyrs spawn in the air (Working)
- They fly towards a player and pick them up exactly where the player was standing (not working)
- ^Instead players get grabbed to the position the Val'Kyr initially spawned on
- Upon letting go of the player by dying or being on 50% HP (heroic) they kind of throw the player 3-6yds infront of them instead of releasing them right under them how it should be
- Upon being stunned the Val'kyr stays still but upon exploration of the stun the Val'kyr teleports to the position that it would've been at if it wasn't stunned 

#1288 Is the same issue but this post explains it more in-depth.

All of the above described makes the second phase of 25 Man heroic impossible for the raid to kill because Val'kyrs always fly in a different direction and stunning them is useless. 
https://www.youtube.com/watch?v=CVLSV7EL3Hc&t=6m This is what it looks like when done properly

### Edit
The Val'Kyr do fly towards a player but not 100% the exact same position as the player (they stop like 5yds infront of the player)I think this is because it's hitbox is too big) so it causes the Val'kyrs to spread and fly towards different directions. Playing around with model_.info combat_reach would help. I'd at least reduce the current value by 50%.

**Comment by Forrestxz** [comment]
Confirmed
