### ISSUE TITLE
[Icecrown Citadel - Sindragosa] Unchained Magic

### ISSUE THREAD

**Issue by keidian** [WoWManiaUK/Redemption#1293]
## How it should work:
- In 10 Man Sindragosa casts Unchained magic on 2 casters 
- In 25 Man Sindragosa casts Unchained magic on 6 casters

## How it currently works
- In 10 Man Sindragosa casts Unchained magic on 1 caster
- In 25 Man Sindragosa casts Unchained magic on 3 casters

**Comment by Plege** [comment]
I thought it was supposed to be 6 as well but on this video from Paragon against sindy 25 hc you see ony 3 players get unchained at two separate occasions.
![image](https://user-images.githubusercontent.com/24266043/27220853-d495f13c-5286-11e7-89bd-ef82108662d5.png)
![image](https://user-images.githubusercontent.com/24266043/27220869-e3a3f02a-5286-11e7-8f03-95d750d1d6c6.png)

**Comment by keidian** [comment]
This was a bug on retail, read the description of the video. It was hotfixes afterwards. Unchained could only affect spellcasters so paragon ran only 3 healers and rest melee/hunters. In this case sindy should cast the 3 remaining unchained on melees with mana

**Comment by Plege** [comment]
:-P right.. should have read description earlier i guess.. never do. thanks for pointing it out

**Comment by Forrestxz** [comment]
The way it should work is 3 unchained on healers, 3 casters. Atleast 3 healers and 3 casters should be getting unchained 100% of the time. Unchained magic prioritiez players using spells such as rets and considers them casters.

**Comment by keidian** [comment]
@Forrestxz Please links a reliable source because I can't find anything about 3 Healers mandatory being targeted. I think It is 6 random spellcasters.
