### ISSUE TITLE
[Quest] Shutting Down Manaforge Coruu

### ISSUE THREAD

**Issue by StarrZappa11** [WoWManiaUK/Redemption#1296]
Unable to complete this quest as Sunfury Technicians run through the walls instead of towards the Manaforge to repair. I'm unable to chase them down quick enough nor attach a screenshot since they get through the walls too quickly. The timer continues to reset, but I'm unable to see who's doing this as they're running through the walls/outside of the area.

Please help, and thank you for looking into this.

**Comment by Noahcoke** [comment]
Please add the wowhead link of the quests and involved npcs, thank you.

**Comment by StarrZappa11** [comment]
http://www.wowhead.com/quest=10330/shutting-down-manaforge-coruu

http://www.wowhead.com/npc=20218/sunfury-technician
