### ISSUE TITLE
[Quest] Washed Ashore

### ISSUE THREAD

**Issue by Dragonfly414** [WoWManiaUK/Redemption#1297]
http://www.wowhead.com/quest=3524/washed-ashore

I am looking for this item - Sea Creature Bones (http://www.wowhead.com/item=12242/sea-creature-bones)
Found 1 creature with a little wheel. If I click on it, there is a text box opening, but nothing else.
Can't complete the quest.

Maybe also check up for the next quest??

**Comment by Noahcoke** [comment]
I did the quest and was able to complete it. I clicked the corpse with the wheel and could collect the item. No text box, just if i would have looted a corpse.  
Maybe you were at the wrong corpse?
