### ISSUE TITLE
Dead in Ebon Hold

### ISSUE THREAD

**Issue by dlaynet** [WoWManiaUK/Redemption#1300]
I was killed on Death Knight Dragon Quest "An End To All Things..." I tried retrieving my corpse several times but died instantly from ballistia arrows. I tried looking for a spirit healer further away with no avail. So I just logged out and went to bed. I woke up this morning and logged in. I was still dead but now I am in Ebon Hold with now way of retrieving corpse. No grave stone on the map even if I could get down to it. Can you please just rez me at ebon hold, so I can repair my mangle body and attempt to finish the dragon quest?

**Comment by fvicaria** [comment]
Please open a ticket for this.

**Comment by dlaynet** [comment]
i thought this was a ticket. sorry
