### ISSUE TITLE
[Quest] It's all fun and games

### ISSUE THREAD

**Issue by Garrrrly** [WoWManiaUK/Redemption#1302]
Well, about this quest, it's not really any fun at all, I checked other issues about it and everyone it's talking about "can't hit/target the Eye", I don't even have an Eye to target!

http://imgur.com/a/7cNF1

**Comment by elagen** [comment]
with this quest the Ocular  is above the Shadow Vault 

![wowscrnshot_061917_070822](https://user-images.githubusercontent.com/22685042/27271732-44182fe6-54be-11e7-9cb6-dd1238206e62.jpg)

![wowscrnshot_061917_070830](https://user-images.githubusercontent.com/22685042/27271739-4a8a2460-54be-11e7-8ad9-905970a27dcf.jpg)
