### ISSUE TITLE
[Quest] Fortunate Misunderstandings (oracles reputation)

### ISSUE THREAD

**Issue by galivon** [WoWManiaUK/Redemption#1303]
I accepted a Quest from Injured Rainspeaker and then i talked to him and told him that i am ready to escort him and nothing happens.

It is one of important chain Q to get started earning oracles rep. (daily Q, etc...)

I tryed to abadon and accept again, relog and some simlar things.

Thank you for your time.

**Comment by fvicaria** [comment]
Works. If you have an issue open a ticket.
