### ISSUE TITLE
Quest line of Battered Hilt

### ISSUE THREAD

**Issue by Daxko89** [WoWManiaUK/Redemption#1306]
During the quest line of Battered Hilt,upon finishing a quest "Thalorien Dawnseeker" at NPC Halduron Brightwing at map Isle of Quel'Danas,supposed to pop up next quest line called "The Purification of Quel'Delar,which doesn't happen.Becoming unable to proceed with quest chain of Battered Hilt.All traces that i have been on that quest were gone.After making a ticket to GM,he succeed to retrieve the quest  at the point i stopped.Next bug happened immediately after tried to click at guard and pressing " I'm ready to enter Sunwell" , nothing happened.Entered by myself into instance,and instead of instance i finished into the "old town" which surrounds the instance,which resulted no mobs,no NPC around me,only the building.Came back to the instance side again with flight mount and entered successfully.After obtaining the item "restored quel'delar" ,chain quest is leading to Icecrown at Quel'delar's rest ,NPC Caladis Brightspear,quest doesn't show up at that NPC at all.At that point quest was bugged completely.

**Comment by fvicaria** [comment]
Works. Search for NPC to complete your quest.
