### ISSUE TITLE
[Quest] Torch Catching

### ISSUE THREAD

**Issue by tsuff** [WoWManiaUK/Redemption#1307]
When I accepted [http://www.wowhead.com/quest=11657/torch-catching](url) for the 1st time, I received a Juggling torch and  [Unlit Torches]. The  [Unlit Torches] should light another torch when you use the 1st one, but nothing happens when u use it.

**Comment by Noahcoke** [comment]
Confirmed on Dev now. I only receive http://www.wowhead.com/item=34833/unlit-torches but nothing happens once i try to use them near a bonfire, as instructed.

**Comment by squalllh1989** [comment]
i pray for god that this issues can be solves in 4 days so i can get the last achivement of mid summer this year :v

**Comment by fvicaria** [comment]
Open a ticket and I GM can complete it for you.

**Comment by squalllh1989** [comment]
It seem the quest is doable now, just harder than it should, as no shadow of the torch is on the floor where it should land, you have to watch and calculate yourself by your sense. Also, for some reason, the flame of failure (which affect to you if you failed to catch the torch and are near where the torch drop to the ground) is some time bugged, it do 300 damage to my dk, which is in blood tanking spec, but do 32k damage to my fire mage (which instally kill me everytime i failed to catch the torch), but yeah, with effort you still can complete this yourself without gm 's help and that enable you to get the juggler achivement.
