### ISSUE TITLE
Felhunter's Fel intelligence bug

### ISSUE THREAD

**Issue by SvalaTheWarlock** [WoWManiaUK/Redemption#1309]
Hello,
i have an issue with my felhunter's buff, it doesn't work.
even if i am clear of buffs like divine spirit (spirit buff from priest) and arcane intelligence (intellect from mage) and even i have no buff at all (even self like fel armor) when i click the fel intelligence on my felhunter action bar. its make the noice and the red casting effect but nothing happend no state change. no buff icon not anything.
i will appreciated if u check this out and solve the issue.

Have a great day,
Svala

**Comment by Forrestxz** [comment]
Just tested it right now, not sure what you mean mate.


![wowscrnshot_062117_124127](https://user-images.githubusercontent.com/29176303/27378009-38cf95da-567f-11e7-8133-f52f552f365f.jpg)

**Comment by SvalaTheWarlock** [comment]
that's weird because it doesnt work for me test it again now
