### ISSUE TITLE
[Warrior] Tier 10 DPS bonus not working. 

### ISSUE THREAD

**Issue by Forrestxz** [WoWManiaUK/Redemption#1310]
Tooltip
"You have a 20% chance for your Bloodsurge and Sudden Death talents to grant 2 charges of their effect instead of 1, reduce the global cooldown on Execute or slam by 0.5 sec, and  for the duration to be increased by 100%."

http://www.wow-mania.com/armory/?itemset=-272

How it should work - When your 4 piece tier procs, you should be able to use Slam twice before your buff runs out, basically giving you 2 charges of Slam instead of 1.

How it currently works - Tooltip shows that you have 2 procs of Slam, however all of the slam procs disappear after using it once, basically you get to use it once and not twice whenever it procs.

**Comment by fvicaria** [comment]
duplicate
