### ISSUE TITLE
[Raid] ICC - Harvest Souls [HC]

### ISSUE THREAD

**Issue by keidian** [WoWManiaUK/Redemption#1314]
## What's broken: 
When Warlocks spam their demonic teleport  spell (if their teleporter is in range) while The Lich King is casting Harvest Souls there's a split second delay of the Harvest Soul debuff disappearing and the moment you get teleported into frostmourne. Basically Warlocks are able to teleport out of this phase and completely ignoring it.

Confirmed on Redemption.

**Comment by Forrestxz** [comment]
Confirmed on Redemption.

**Comment by fvicaria** [comment]
Please retest in Red.

**Comment by keidian** [comment]
Still isn't fixed in Dev
