### ISSUE TITLE
[Achievement] Extinguishing Kalimdor, Extinguishing Eastern Kingdoms

### ISSUE THREAD

**Issue by lilxmousey** [WoWManiaUK/Redemption#1316]
As per the Midsummer Fire Festival, a Horde player can extinguish Alliance bonfires in zones but clicking on the '?' that a bonfire gives, like any other questgiver.

However I have had multiple issues with a few of the bonfires, including Bloodmyst Isle and Loch Modan. The '?' is present on the map, but there is nowhere to click. A few of the '?' in a couple of the fires are a bit hidden, but these ones are inaccessible for me at all, preventing me from earning the achievement.

**Comment by StarrZappa11** [comment]
I'm having the same issue as well, but with extinguishing the fire in Silverpine Forest.

**Comment by squalllh1989** [comment]
Not sure about ally's side, Horde side got many ppl have completed this, but yes, those fire are hard to extinguishing, there appear to be like 2-3 fire overlap, but it's still doable, just need to find a good place to stand and click it.
