### ISSUE TITLE
[Raid] ICC - valithria dreamwalker

### ISSUE THREAD

**Issue by elagen** [WoWManiaUK/Redemption#1319]
The Adds / Mobs that should be spawn on valithria dreamwalker should spawn from Either Side and they do not spanw after the First 4 Mobs are killed

http://www.wowhead.com/npc=36789/valithria-dreamwalker

**Comment by Noahcoke** [comment]
Not fixed yet. In addition, even after the firts 4 initial enemies are killed, no adds would spawn at all.

**Comment by Forrestxz** [comment]
Confirmed on Redemption.
