### ISSUE TITLE
Dawn of Light and Taking back Archerus still continue to bug

### ISSUE THREAD

**Issue by Korserva** [WoWManiaUK/Redemption#1320]
Dawn of Light bugged 6/24/17, and Taking Back Archerus bugged (no quest turn in; Phases player into the phase AFTER "The Battle For the Ebon Hold" ) immediately after a GM fixed Dawn of Light.  I am a Worgen and noticed in an earlier quest to kill the night elf npc that it also tried to give me the Horde npc to kill quest.  Perhaps it is something within the Worgen race that is disrupting the phases?

**Comment by fvicaria** [comment]
If you do all quest correctly it won't. I have run this from beginning to end with no problem and so have done many others. I will check if there is a specific issue for Worgen.
