### ISSUE TITLE
[Quest] It's All Fun and Games [Icecrown]

### ISSUE THREAD

**Issue by lFerret** [WoWManiaUK/Redemption#1323]
Ebon Blade questline starting quest does not seem to be spawning the 'Ocular' at all or in the proper spot. Have checked several times over a few days for it, abandoned and restarted the quest many times as well. Does not appear to be working. Cheers

**Comment by fvicaria** [comment]
Quest works fine. Please check the video for the quest.
![image](https://user-images.githubusercontent.com/9414661/27534998-d2ae153e-5a60-11e7-9896-9a971d7c6c1b.png)
