### ISSUE TITLE
 [Quest] Twilight of the Dawn Runner

### ISSUE THREAD

**Issue by squalllh1989** [WoWManiaUK/Redemption#1324]
This quest (http://www.wowhead.com/quest=9437/twilight-of-the-dawn-runner) has 2 objective: 
- reclaim the Dawn Runner Cargo (which work)
-  Rescue Ithania from North Point Tower (which didn't work)
The trouble here is Ithania, who you need to rescue from the tower, doesn't move, and just stand there in the tower.

**Comment by fvicaria** [comment]
Works Somebody must have messed up with the NPC. I will reset it.
