### ISSUE TITLE
Netherwing Ledge: Quest: the great netherwing egg hunt.

### ISSUE THREAD

**Issue by Savage514** [WoWManiaUK/Redemption#1326]
The quest: http://www.wowhead.com/quest=11049/the-great-netherwing-egg-hunt
Could not been started.

Description: After the quest chain offered by Mordenei 
NPC -> http://www.wowhead.com/npc=22113/mordenai

After the chain he should give you a quest to fly to netherwing ledge. 
Quest: http://www.wowhead.com/quest=11013/in-service-of-the-illidari

This quest won't be given... Reputation with Netherwing remains on Neutral and there are no other quests or daily's to be accepted. 
Faction -> http://www.wowhead.com/faction=1015/netherwing

**Comment by fvicaria** [comment]
![image](https://user-images.githubusercontent.com/9414661/27676594-768aeb18-5ca6-11e7-8cf8-30c9e8c04f37.png)


Works fine. You also need to have riding skill 300.

**Comment by Savage514** [comment]
been speaking with two GM ingame about this, never spoke about riding skill 300, diddnt find it on wowhead at that time. but you are right. my apologies about the thread.

thanks for the answer.

Kind regards, Savage
