### ISSUE TITLE
[Quest] More Torch Tossing

### ISSUE THREAD

**Issue by Wolch** [WoWManiaUK/Redemption#1327]
Seems like now this one does not work http://www.wowhead.com/quest=11926/more-torch-tossing. The red arrows, that should indicate which target to hit, do not appear.

**Comment by Katherwind** [comment]
Confirming that this quest did not work for me either.  The red arrows disappear after one target.

**Comment by Darmicus** [comment]
I can also confirm this does not work on any of my characters, in any city.

**Comment by squalllh1989** [comment]
Happend to me also, this quest is newly bugged, it worked before, but not now.
