### ISSUE TITLE
[Quest] An Innocent Disguise

### ISSUE THREAD

**Issue by ingelinge40** [WoWManiaUK/Redemption#1328]
When changed in the crawler and listen to the conversation it did not complete the conversation, the conversation keeps going on but thats all
![wowscrnshot_062917_221825](https://user-images.githubusercontent.com/25806660/27708612-d13fd5e6-5d19-11e7-8442-ebbafbe0c160.jpg)

**Comment by squalllh1989** [comment]
Seem this is newly bugged, this quest worked fine for me when i tried to do this at the first day of mid summer event.
