### ISSUE TITLE
[Event] K3 spawn event for Garm Invader and Snowblind Follower

### ISSUE THREAD

**Issue by ClavosThePally** [WoWManiaUK/Redemption#1331]
On live this are over here has these mobs as well, but they are meant to continuesly spawn and run to their doom as the little turret totems would kill them if they get to close
![wowscrnshot_063017_145421](https://user-images.githubusercontent.com/26167121/27736518-c65c6136-5da4-11e7-908a-0d0a86124370.jpg)
They also would be ignoring players unless provoked.

The little landmines would also stop them.
![wowscrnshot_063017_145447](https://user-images.githubusercontent.com/26167121/27736519-c65f77ae-5da4-11e7-8f19-fe6bd90e877b.jpg)

It's not something gamebreaking here, but this is something that would be nice if it mirrored live WoW.

**Comment by Forrestxz** [comment]
This is a bug on almost EVERY server, haven't seen it working properly almost ANYWHERE. Not a gamebreaking bug at all indeed.

**Comment by ClavosThePally** [comment]
I did not know that, well, good to know it's not just us

**Comment by fvicaria** [comment]
This is not a priority at the moment. I will look at it when I have some spare time.
Thanks for reporting.

**Comment by Kitzunu** [comment]
@Rushor smt you can look at?

**Comment by Rushor** [comment]
yes. almost done

**Comment by Rushor** [comment]
![I](https://i.imgur.com/DBtrtIT.jpg)
![I](https://i.imgur.com/4b6NsrN.jpg)
 Add this big K3 event https://github.com/WoWManiaUK/Redemption/issues/1331 https://www.youtube.com/watch?v=7GjDaJfRd5M&feature=youtu.be
