### ISSUE TITLE
Jewel Crafting daily and Kirin Tor rp

### ISSUE THREAD

**Issue by Ebonlox** [WoWManiaUK/Redemption#1335]
The Dalaran Jewel crafting daily quests from Timothy Jones are only rewarding 32 Kirin Tor rep per turn in. I thought it should be 150 rep (or thereabouts). Screen Shot of my most recent turn in submitted. 
![jc kirin tor rep bug](https://user-images.githubusercontent.com/26630927/27762280-1297cb2e-5e3d-11e7-8159-3e6ad61ff5de.jpg)

**Comment by fvicaria** [comment]
Link me the quest please.

**Comment by squalllh1989** [comment]
Not sure which shipment quest you did, but i think those quest only give out 25 rep like this quest:  http://www.wowhead.com/quest=12960/shipment-wicked-sun-brooch

**Comment by Ebonlox** [comment]
http://www.wow-mania.com/armory/?quest=12960

I was going by this post from the wow-mania site showing 150 rep. All of the JC dailies are 150 rep according to wow-mania armory. I figured the database associated with the server would be a more accurate reference than wowhead. No worries if this is not the case. Just thought I'd point out a a possible bug. Thanks for the prompt attention.
