### ISSUE TITLE
[Quest] Flight of the Wintergarde Defender

### ISSUE THREAD

**Issue by arklev** [WoWManiaUK/Redemption#1337]
The quest has problem once you mount the gryphon the Villagers disappear and cannot be picked up.
Some sort of different phasing , also in the comment from wow head it says they need to run around but all I saw was them lying around and respawing then dieing right away.

Link: http://www.wowhead.com/quest=12237/flight-of-the-wintergarde-defender

**Comment by fvicaria** [comment]
Quest works. This is due to a phase issue caused by a missing quest. Ask GM to move you into the correct phase.
