### ISSUE TITLE
Hunter pet autocast

### ISSUE THREAD

**Issue by MK8o8** [WoWManiaUK/Redemption#1338]
I have disabled pet ability, Growl on the pet toolbar. When I mount and dismount, Growl autocast is enabled again, but ability on pet toolbar still says disabled. Ability in the spellbook shows the ability set to autocast.

The ability should not be reset to autocast every time the pet is dismissed/summoned, but at least make the toolbar icon show that it is set to autocast.

![image](https://user-images.githubusercontent.com/29690470/27775473-2d7ed3d6-5f57-11e7-8079-e4fb62cf1f8e.png)

**Comment by Noahcoke** [comment]
Confirmed on dev as described.
