### ISSUE TITLE
Elemental mote drop rate from mining outland nodes

### ISSUE THREAD

**Issue by TheGreyMouser** [WoWManiaUK/Redemption#1339]
The drop rate for elemental motes is extremely low compared to blizzard.  WoW-mania = aprox 10% drop rate per wow-mania armory vs http://www.wowhead.com/item=22573/mote-of-earth#mined-from-object which is MUCH higher.  In other words, there are not enough motes dropping to support the professions that require them.  Blacksmithing, leatherworking, jewelcrafting, enchanting and alchemy all require these materials. 
A good example is enchanting needing a Primal Might to level up.  Primal Might is made by alchemy and requires elemental (10 motes each) earth, fire, air, water, mana.  With the current bottleneck, some of these items are very hard to get and in high demand.

**Comment by TheGreyMouser** [comment]
Additional...
Drop rate seems better in Netherstorm, but nearly non-existent in other areas.

**Comment by Noahcoke** [comment]
Which other areas are you referring to in particular?

**Comment by fvicaria** [comment]
Fixed. There was an issue in Khorium veins only.

**Comment by TheGreyMouser** [comment]
All outland areas.  Fel iron and adamantite and khorium nodes in outland zones, except netherstorm, did not seem to be dropping motes of earth or fire.  I believe I managed to find 2 motes from 1 node in zangamarsh after mining maybe 10 to 15 nodes enroute.   Just saying that seems to be very low compared to blizzlike.   Apparently Janitor found an issue with knorium nodes and fixed it.  Still the other nodes seem rather low compared to what usually drops.  See...  http://www.wowhead.com/item=22573/mote-of-earth#mined-from-object
<http://www.wowhead.com/item=22573/mote-of-earth#mined-from-object>


<http://www.wowhead.com/item=22573/mote-of-earth#mined-from-object>

vs
<http://www.wowhead.com/item=22573/mote-of-earth#mined-from-object>

<http://www.wowhead.com/item=22573/mote-of-earth#mined-from-object>http://wow-mania.com/armory/?item=22573#mined-from-object


<http://www.wowhead.com/item=22573/mote-of-earth#mined-from-object>

[http://wow.zamimg.com/images/wow/icons/large/inv_elemental_mote_earth01.jpg]<http://www.wowhead.com/item=22573/mote-of-earth#mined-from-object>

Mote of Earth - Item - Wowhead<http://www.wowhead.com/item=22573/mote-of-earth#mined-from-object>
www.wowhead.com
Mote of Earth is used for crafting. It is crafted, looted and sold by NPCs. In the Elemental Trade Goods category. An item from World of Warcraft: The Burning Crusade.

This might be working as intended, but seems a bit low to support professions requiring these items.

Drop rate from mobs seems to be right where it should be.

Northrend elemental materials from mining seems to be much higher drop rate.  Again, this may be working as intended..

Thanks for fast reply.

Gary


________________________________
