### ISSUE TITLE
Dungeon-Culling of Stratholme

### ISSUE THREAD

**Issue by iEulo** [WoWManiaUK/Redemption#1343]
This dungeon it's in the Caverns of Time. It's the dungeon where we can meet Arthas. This dungeon seems to face some problems. Some friend of mine helped me with 2 instructions : don't talk to the gnome & do not talk to Arthas while you're mounted. Nearly after the entrance there is a gnome, which you can talk to, but you better not (!). After a while, you can meet Arthas too, it seems that you can speak with him, just to tell him that you're ready ! ..aaand nothing happens, even if you told to him that you're ready, seems that he's not. After you told him that you're ready, you are not able to talk to him again. Everything seems stable,nothing moves. I followed these instructions, even following them or not, the completion of the dungeon seems impossible. Meanwhile, without the completion of this dungeon, achievement-hunters and tailors will face some serious in-game progression problems. Without the completion of this dungeon, the achievement of the Northrend Dungeonmaster is impossible. Also, all tailors won't be able to recive a cloak recipe from the Tailors in Dala.

**Comment by fvicaria** [comment]
Works. Do the necessary quest to be able to talk to NPCs.
