### ISSUE TITLE
[Dungeon] Halls of Stone - Tribunal of the Ages

### ISSUE THREAD

**Issue by hotdoggidy** [WoWManiaUK/Redemption#1344]
This encounter is started by speaking with Brann Bronzebeard in the Hall of the Highfather wing of the dungeon. Brann leads the group to the engagement where he attempts to unlock secrets of the Makers. During the engagement, waves of adds spawn against the players instead of a normal dungeon boss. 

Currently on Redemption the adds that spawn can be ignored by standing next to Brann, where their agro range does not trigger. Making the encounter a lazy afk instead of a wave-wave fight. 

IDs for wave adds:
Dark Rune Stormcaller (npc=27984)
Dark Run Protector (npc=27983)
Brann Bronzebeard (npc=119890)

Screenshot taken from the side of Bronzebeard during the encounter. Waves all stacked up at spawn location just outside the Library.
![wowscrnshot_070417_190143](https://user-images.githubusercontent.com/23442126/27875186-3098437e-6167-11e7-8904-637f9041e41b.jpg)

Once the fight is over the wave adds stay alive but can be easily bypassed with a dungeon group teleport trick or by walking passed them in a space to one side of their stack.

**Comment by Forrestxz** [comment]
Still not fixed on Dev.

**Comment by fvicaria** [comment]
Check again please.
