### ISSUE TITLE
[Item] Ephemeral Snowflake'

### ISSUE THREAD

**Issue by kutte92** [WoWManiaUK/Redemption#1345]
hey,
this item should give 11 Mana per heal spell, but only gives it once, i have to put it back in my bag and back on my char for one 11 mana procc.

i talked with gm, and he got the same problem

**Comment by Noahcoke** [comment]
Confirmed as described on dev.

**Comment by fvicaria** [comment]
Please send link to where you got this info from. As far as I can see the item is fine.

**Comment by kutte92** [comment]
ingame mana gain message, it tells +11 mana only once for the first heal

**Comment by fvicaria** [comment]
Still cannot see anything wrong with item.
It will heal once. Per target you heal.

**Comment by tpalasz** [comment]
This item is not working.
Tooltip says:
"You gain 11 mana each time u heal a target with one of your spells".
If I put a Rejuvenation on target - this item should give mana with every tick. If I put a Wild Growth on few targets - this item should give mana with every tick on any target.

I was doing HoR Normal and i got like 33 mana from this item (entire instance).
I have done some testing - this items procs once when i equip it. After 11 mana i have to unequip and equip again.

**Comment by Rushor** [comment]
maybe

```
-- [Item] Ephemeral Snowflake
REPLACE INTO spell_proc_event VALUES (71567, 0, 0, 0, 0, 0, 0, 1+2, 0, 0, 400);
```

**Comment by Rushor** [comment]
seem to work https://i.imgur.com/wJDJ9Gk.png
