### ISSUE TITLE
Quest "They grow up so fast"

### ISSUE THREAD

**Issue by marthyjane** [WoWManiaUK/Redemption#1347]
Apparently Goblins are not able to do this quest as the hatch-ling will not give a quest.  It worked on my druid but both of my goblin characters  are not given quests after receiving the hatch-ling.

**Comment by fvicaria** [comment]
All races are allowed to do this quest.

Check requirements:
http://www.wow-mania.com/armory/?quest=13906

**Comment by marthyjane** [comment]
Have you tried to do this quest with goblins?  My goblins can't do it I have a lvl 58 and 70.  No problem with my druid.  Please test it for yourself.

**Comment by fvicaria** [comment]
As I said do all the required quests...
![image](https://user-images.githubusercontent.com/9414661/27918848-174389c2-6268-11e7-85ce-4f85822aa567.png)

**Comment by marthyjane** [comment]
I can't do the quests when the hatchling won't give me quests to do which means I can't get the baby teeth.

**Comment by fvicaria** [comment]
I spoke with a GM and you r description of the issue is way off. You can't do the dailies. So the issue is not this quest you mentioned at all. 
I will correct the dailies.

**Comment by marthyjane** [comment]
Fair enough 
Thank you

**Comment by marthyjane** [comment]
Still doesn't work
I click on the hatchling and I just get text saying "Hatching looks at you as if trying to determine if your  its mother or not"
Does not offer a quest (daily).
