### ISSUE TITLE
Sapphire of Sky chest missing for quest "The Relics of Wakening"

### ISSUE THREAD

**Issue by CrackersCandy2** [WoWManiaUK/Redemption#1351]
The chest that contains the Sapphire of Sky (http://www.wowhead.com/item=3407/sapphire-of-sky) is not in the spot it's supposed to be in. I have watched videos and ran all around Ban'ethil Barrow Den to no avail. I've gotten all the pieces to the quest except for this one, rendering it impossible to complete.

![wowscrnshot_070617_185413](https://user-images.githubusercontent.com/29964238/27937659-54684b9c-627e-11e7-9e13-1a49c539cc99.jpg)

**Comment by fvicaria** [comment]
![image](https://user-images.githubusercontent.com/9414661/27947530-20836ac6-62ee-11e7-9980-50613a2ba355.png)
