### ISSUE TITLE
[Icecrown Citadel - Sindragosa] Unchained Magic & Beacon of Light

### ISSUE THREAD

**Issue by Forrestxz** [WoWManiaUK/Redemption#1353]
Beacon of Light (http://www.wow-mania.com/armory/?spell=53563#modified-by) heals are giving an extra stack of Unchained Magic (http://www.wow-mania.com/armory/?spell=69762).

What's currently happening: I heal 1 person with Unchained Magic without Beacon of Light, i get 1 stack (Working properly).

I heal 1 person with Unchained Magic WITH Beacon of light on someone else, Im getting 2 stacks per cast.

How it should be: Beacon of Light heals shouldn't be giving an extra stack of Unchained Magic. Healing 1 person also heals the Beacon of Light as the same time but the script shouldn't consider it as a different spell cast, it's still 1 spell being casted yet the beacon of light heals are awarding an extra stack.

**Comment by fvicaria** [comment]
You can confirm your own issue. :)

**Comment by elagen** [comment]
I would like to Add the on the Unchained magic Explosion on HC mode is more then 8 or 10 yards the Explosion hits people when they are 15 Yards away

**Comment by keidian** [comment]
@Elagen Unchained is supposed to be 20yds range. What you're reporting is false.

There's various sources stating that. (Mmo champ/ wowwikia/ retail videos
