### ISSUE TITLE
[Raid] Icecrown Citadel - Sindragosa (Blistering Cold)

### ISSUE THREAD

**Issue by elagen** [WoWManiaUK/Redemption#1355]
on Blistering cold the Tank who Sindragosa has targetted on Blistering cold should NOT be pulled in and he is

http://www.wowhead.com/spell=70123/blistering-cold

As you can see here at 43 seconds in the Video The tank on Sindragosa is NOT being pulled in

https://www.youtube.com/watch?v=37s42egqnls

**Comment by Forrestxz** [comment]
Is this a new bug? Didnt see this happen before on Red.

**Comment by fvicaria** [comment]
If this is happening I see no way to fix it as the spell is a range spell and I cannot exclude the tank.
