### ISSUE TITLE
[Dungeon] Culling of Stratholme - Arthas

### ISSUE THREAD

**Issue by elagen** [WoWManiaUK/Redemption#1356]
there is a Problem with Arthas and his path finding when doing the First Roleplay with arthas he should then walk inside Statholme and he does not - he stops outside 

http://www.wowhead.com/npc=26499/arthas

here is where he stops 
![wowscrnshot_070717_101137](https://user-images.githubusercontent.com/22685042/27951625-79f657c6-62fd-11e7-9597-5355def823a2.jpg)

here is where he should stop
![wowscrnshot_070717_101147](https://user-images.githubusercontent.com/22685042/27951636-7f616aac-62fd-11e7-87db-fd650e9100ec.jpg)

**Comment by LooneyBin** [comment]
Not only that.
But after killing the 2 first bosses, then he (Arthas) stops walking(cant talk with him), and just stand there for a bit. 
Then he suddenly starts running off, and that repeats several times through the dungeon.

Aint a major issue, just thought you could look into it while looking at his pathing.

**Comment by Noahcoke** [comment]
Confirmed on red.
