### ISSUE TITLE
[Spell] Engineering - Goblin Mortar

### ISSUE THREAD

**Issue by Wolch** [WoWManiaUK/Redemption#1357]
I can't this skill http://www.wow-mania.com/armory/?spell=12716
My engineering skill is 229, and I have done the quet for Goblin Engineering specialization. But when I try to create Goblin Mortar I get an error "You can't do that yeat"

**Comment by fvicaria** [comment]
Works.
![image](https://user-images.githubusercontent.com/9414661/27983979-86cb8b2c-63c2-11e7-83d6-2b9538512d82.png)


Check all requirements and conditions here:
http://www.wow-mania.com/armory/?spell=12716#conditions

A little research before posting can save developers and testers a lot of time.
