### ISSUE TITLE
[Quest] Leading the Charge + Watts My Target

### ISSUE THREAD

**Issue by StarrZappa11** [WoWManiaUK/Redemption#1360]
I'm noticing several issues while trying to complete this quest. First, the green shield does not actually protect you when being attacked, the buff is there but the count never goes down for me. Second, the Gargoyle Ambusher ( http://www.wowhead.com/npc=32188/gargoyle-ambusher ) is killable, but much more difficult than in retail. Third, the plane's flight path is too high most of the route causing a low kill rate since I cannot see them on the ground from so far above.

Please help, thank you for your time.

Both of these quests are effected due to the above issues:
http://www.wowhead.com/quest=13380/leading-the-charge
http://www.wowhead.com/quest=13381/watts-my-target

Video of Leading the Charge flight path:
https://www.youtube.com/watch?v=nnJMLBD4oHs

**Comment by fvicaria** [comment]
I have tried the quest and is doable. I will look into the Gargoyle and try to make it slightly easier.

**Comment by StarrZappa11** [comment]
Quest is doable, yes. I'm still experiencing all the same problems as above and the quest seems easiest to complete while on the ground single killing them. This is not how this quest should be, and I've died another 5 times while trying to complete after this was closed.

**Comment by Brunnr** [comment]
Unfortunately this quest vehicle is still bugged, without the shield working or being able to put out fires (neither ability does anything), the gargoyles easily destroy the plane. You can kill the elites on the ground, but the gargoyles and elite dragons are too high up, making the quest completion unlikely.
