### ISSUE TITLE
Flight of the Wintergarde Defender 

### ISSUE THREAD

**Issue by LOCAL0001** [WoWManiaUK/Redemption#1361]
This quest doesnt work, ive talked to an ingame GM about getting me phased in properly but that didnt work either ive only been able to do 4 of the 10 people needed to complete the quest.  Every time  I see a person required for the quest they just disappear and i am not able to pick the up on the gryphon.  I do hope this bug is fixed because wintergarde is possibly one of my favorite questing areas

**Comment by fvicaria** [comment]
Works. Please search before posting a new issue. This is dues to a missing quest at some point.

**Comment by LOCAL0001** [comment]
i tried to get a gm to phase me in and that didnt work so what am i supposed to do?
