### ISSUE TITLE
Wow-Mania - Bugged Quests

### ISSUE THREAD

**Issue by Tallrasha** [WoWManiaUK/Redemption#1362]
Hello. I have problem with some 60lvl quests that are bugged.  I'm orc warrior named ''Kiro''. 

When Smokey Sings, I get violent
A Pawn on the Eternal Board
Breastplate of the chromatic Flight
Legplates of the chromatic Defier
Breastplate of Bloodthirst
Cap of the Scarlet Savant
Fiery plate gauntlets
Leggins of Arcana

Thanks for help..

**Comment by fvicaria** [comment]
Please follow the procedure described below before creating a new issue:
[How to Properly Report an Issue](https://github.com/wow-mania/Redemption/wiki/How-to-Properly-Report-an-Issue)

This will help developers identify and fix the issue quicker. Incorrectly or unclear reports will simply be deleted.
