### ISSUE TITLE
[Talent] Mage - Brain Freeze

### ISSUE THREAD

**Issue by hotdoggidy** [WoWManiaUK/Redemption#1363]
Brain Freeze (spell=190447)
Frostbolt (spell=116)
Frostfire bolt (spell=70616)

**Brain Freeze** talent in the frost tree for mages should give chilling spells (like frostbolt and frostfire bolt) a 15% chance to proc a free, instant cast  **Fireball** or **Frostfire bolt**.

Currently on Redemption it seems Frost mages will only get this talent to proc 1 time. 

Tested with 400 **Frostbolts**. 
After initial 100 casts i only got **Brain Freeze** to proc 1 time. I went to trainer and respecced in hopes it was something silly like that.
After respec and another 100 casts, **Brain Freeze** procced within the first 5 casts of **Frostbolt** but never again.
Respecced and tested again 2 more times with same result. **Brain Freeze** procced within first 4-5 casts and never again.

It seems the talent is being treated as a 1 time effect, only proccing when the mage specs/respecs into it. Not sure why that would be the case but its definitely not a passive 15% chance for all chill spells. At least not permanently.

**Comment by hotdoggidy** [comment]
Test 2: 100 frostbolts on re-log
A re-log has the same effect of a respec. 1 proc for a free, instant cast fireball or frostfire bolt upon logging into the character. 

This leads me to believe there is some kind of internal cooldown on the talent preventing it from proccing again until the mage either loses the talent with respec or loses connection to the realm with a relog.

**Comment by Noahcoke** [comment]
Confirmed as described on dev. Procs just once. Fingers of Frost (same chance to proc) occurs more often.

**Comment by Fuzzykitten37** [comment]
Confirmed Brain Freeze as described above only will proc once. and Fingers of Frost has an issue as well. When Fingers of Frost happens only the first stack counts the target as frozen. The last stack you cannot use Deep Freeze nor does Ice Lance have enhanced dmg.

**Comment by seridwyn** [comment]
can confirm this glad to see a report already open it is still not working properly i see one proc every time i log in but thats it
