### ISSUE TITLE
[Talent] Improved Stormstrike

### ISSUE THREAD

**Issue by Anthonhed** [WoWManiaUK/Redemption#1364]
The tallent Improved Stormstrike(http://wow-mania.com/armory/?spell=51522) for shamans should make the Stormstrike(http://wow-mania.com/armory/?spell=17364) ability to have a **100%** chanse to give back **20%** off the base mana.

After I have tested on redemption I can conclude that this is not the case, it sometimes gives back mana and sometimes not, so it isn't 100% chanse.

**Comment by fvicaria** [comment]
There is absolutely no mention to giving mana back on this spell. Please show me the source of your information.

**Comment by Anthonhed** [comment]
used wrong link; http://wow-mania.com/armory/?spell=51522

**Comment by fvicaria** [comment]
Cannot reproduce this.
There are two spells one with 50% and another with 100% there are also level and other requisites to be filled.
