### ISSUE TITLE
Grimtotem Spying

### ISSUE THREAD

**Issue by Soshisen** [WoWManiaUK/Redemption#1365]
When the secret notes are picked up the quest tracking HUD does not report they are completed. If you go into the quest log it shows that they are completed. If you untrack then retrack the quest it will show as completed. I am not using an addon for quests. Here is the link for the quest itself: http://www.wow-mania.com/armory/?quest=5064

**Comment by hotdoggidy** [comment]
Does this prevent the quest from being completed/turned in?

**Comment by Soshisen** [comment]
No, the quest completes fine

Sent using the mail.com mail app

**Comment by fvicaria** [comment]
This is a client update issue. Used to happen even in retail. There is no known fix for this.
It also happens when you pick up multiple quests that requires the same items. It will lose track of how many you have. You need to pick one quest at a time.
