### ISSUE TITLE
[Quest] Death's Gaze

### ISSUE THREAD

**Issue by StarrZappa11** [WoWManiaUK/Redemption#1366]
Unable to complete this quest as there are no orbs the three locations. It looks as though the stand is there in some locations but missing the orb at the top, and I'm also unable to select just the stand itself to get the credit.

Any help would be greatly appreciated, thank you.

http://www.wowhead.com/quest=13120/deaths-gaze

**Comment by fvicaria** [comment]
You place the orb.
![image](https://user-images.githubusercontent.com/9414661/27991978-52c5673a-6480-11e7-9905-4a5bb35f6d4b.png)

**Comment by StarrZappa11** [comment]
Hi, I'm not even seeing those types of stands, these are the only ones I'm seeing.

![image](https://user-images.githubusercontent.com/29348748/27993294-c51fc1f0-6475-11e7-99e2-5e04f65e7898.png)

Since the close of this ticket I've abandoned and picked the quest up 3 different times and still nothing. Nothing's even sparkling anywhere in these locations for me.
