### ISSUE TITLE
Bugged Quests

### ISSUE THREAD

**Issue by Tallrasha** [WoWManiaUK/Redemption#1368]
Hello. I have some quests i cannot complete without your help. 
[http://www.wow-mania.com/armory/?quest=5166](url) and 
[http://www.wow-mania.com/armory/?quest=5167](url). 
There are scales and carapace from dragonkin in UBRS, but there are no such dragons plus Rend Blackhand with his dragon is bugged aswell. There is also 5 quests in Naxxramas folder. The problem is, that these old Naxx quests were made for lvl 60 and now in 80's Naxx frozen rune doesen't drop. So i doubt it can be fixed:
[http://www.wow-mania.com/armory/?quest=9237](url)
[http://www.wow-mania.com/armory/?quest=9235](url)
[http://www.wow-mania.com/armory/?quest=9236](url)
[http://www.wow-mania.com/armory/?quest=9234](url)
[http://www.wow-mania.com/armory/?quest=9033](url)

Thanks for help. I hope now i wrote my issue correctly.

**Comment by fvicaria** [comment]
No. You should log quests individually and explain the problem exactly. You bundled a lot of quest and NPCs together using the word bugged without saying how.

**Comment by Tallrasha** [comment]
I'm sorry I'm new with this. First 2 quests are missing the same: I need to collect lots of stuff, but i cannot get Chromatic Carapace because it drops only from Gyth (mount of Rend Blackhand in UBRS) and he just didn't show up. And also Brilliant Chromatic Scales drops from whelps and dragonspawns. They are missing too..

Breastplate of the Chromatic Flight: 1 Chromatic Carapace
                                                       10 Brilliant Chromatic Scales
                                                       10 Blood of Heroes
                                                       10 Frayed Abomination Stitchings

Legplates of the Chromatic Defier: 1 Chromatic Carapace.
                                                     10 Brilliant Chromatic Scales
                                                     10 Blood of Heroes
                                                      5 Skin of Shadow

**Comment by fvicaria** [comment]
What's wrong with Blackhand?

**Comment by Tallrasha** [comment]
Ok i have just been there and this time he was ok. Last time he stuck...Anyway before he come, there should be several waves of chromatic whelps and dragonspawns i need for Brilliant Chromatic Scales. I have seen only 2 whelps...

**Comment by Noahcoke** [comment]
Can you please add the wowhead link of your quests. The one you added are not working for me.

**Comment by Tallrasha** [comment]
Breastplate of the Chromatic Flight
http://www.wowhead.com/quest=5166/breastplate-of-the-chromatic-flight
Legplates of the Chromatic Defier
http://www.wowhead.com/quest=5167/legplates-of-the-chromatic-defier

Naxxramas (quests for the old Nax.)
http://www.wowhead.com/quest=9237/glacial-cloak
http://www.wowhead.com/quest=9235/icebane-bracers
http://www.wowhead.com/quest=9236/icebane-breastplate
http://www.wowhead.com/quest=9234/icebane-gauntlets
http://www.wowhead.com/quest=9033/echoes-of-war

**Comment by Noahcoke** [comment]
For the two quests: Kill blackhand slowly, so you dont skip the phase and he dismounts the dragon. 

The other quests for Naxxramas cant be done anymore if they were created for the old version.

**Comment by fvicaria** [comment]
Blackhand is fixed. For the quests collect material but only get one quest at a time.
