### ISSUE TITLE
[Quest] The hunter and the Prince

### ISSUE THREAD

**Issue by iggapres** [WoWManiaUK/Redemption#1369]
http://www.wowhead.com/quest=13361/the-hunter-and-the-prince

Some reports have been made on this quest, however it seems the problem is not the same.

The stone appears when taking the quest.
I embodies Arthas and have to fight Illidan.

The problem is, on technique 1 (parry), Arthas should regen 25% percent of its mana, which does not happen, then he runs OOM after the first attack and dies soon after, being hit by Illidan.

**Comment by ingelinge40** [comment]
Received tickets over the same problem
