### ISSUE TITLE
[Quest] Jagged Shards

### ISSUE THREAD

**Issue by iggapres** [WoWManiaUK/Redemption#1370]
I have quite the same problem as #759.

The NPC (Crusader Olakin Sainrith) has been taken away by the bone drake when I turned in a previous quest.
At that time, the item "Jagged Shard" (http://www.wowhead.com/item=43242/jagged-shard) dropped but I could not begin the quest.

Now I have all the 10 Jagged Shards, but Olakin an I are not in the same phase anymore.

GM did not want to help me and directed me here.

**Comment by fvicaria** [comment]
Just done the quest and it worked fine. Please read instructions on the bug you referred and watch the video. If however you got into a bad phase create a ticket and ask a GM to help.
