### ISSUE TITLE
[Quest] A Fall From Grace

### ISSUE THREAD

**Issue by Biboup** [WoWManiaUK/Redemption#1371]
Hi,

The quest "A Fall From Grace"  : http://www.wowhead.com/quest=12274/a-fall-from-grace
is bugged and thus cannot be completed.
After talking to Agent Skully in New Hearthglen (Dragonblight), the morph is effective (it is bugged if you are still mounted though) and Onslaught Footmen/Raven Priest will be friendly. There is a bug with Onslaught Warhorses still being aggressive.
Ringing the bell in the abbey sucessfully pulls the Abbot's Bodyguards and completes the 1st quest objective. After speaking with the Abbot and going outside of the abbey, TWO Abbot will spawn and tell you to follow him. After you listen to the speach of both, they will jump from the cliff and the 2nd quest objective will be completed, but it is impossible to give the quest back to Agent Skully (white interrogation mark).

**Comment by squalllh1989** [comment]
I know that this is closed, but the problem here still continue, the knight attack us when abbot go outside, then after i finish the talk with him end up as he jump down from the cliff, i can't turn in the quest.

**Comment by fvicaria** [comment]
I will re-check

**Comment by b3simmons** [comment]
I had the same issue as well. I even dropped the quest, killed the knight that aggroes then re-took the quest and did the whole thing before the knight respawned and caused the issue and it still wouldn't complete for me.

**Comment by alexkobe8** [comment]
Seems still bugged, can't turn in my quest!! :(
