### ISSUE TITLE
[Quest Item] Dr. Terrible's "Building a Better Flesh Giant"

### ISSUE THREAD

**Issue by iggapres** [WoWManiaUK/Redemption#1373]
Hi,

I'm using the WM client and the last launcher.

This report is a about a quest item in icecrown.

[Dr. Terrible's "Building a Better Flesh Giant"](http://www.wowhead.com/item=42772/dr-terribles-building-a-better-flesh-giant) should be dropped by [Apprentice Osterkilgr](http://www.wowhead.com/npc=30409/apprentice-osterkilgr).

On WoW head, comments say that Apprentice Osterkilgr should be killed slowly to say a few sentences about the Doctor's plans. It also has to be killed while having the quest [Deep in the Bowels of the Underhalls](http://www.wowhead.com/quest=13042/deep-in-the-bowels-of-the-underhalls) given by the Bone Witch.
Unfortunately, I killed it too fast the first time, while doing this quest and I turned it in.
Now, after more than 10 kills, still no drop.

A GM asked me to post a ticket, here it is.

I don't think it is really a bug, but ...

**Comment by fvicaria** [comment]
Works perfectly.

**Comment by iggapres** [comment]
Ok, it works, I do not deny it, but as stated in my first post, it seems there are requirements for the object to drop. Requirments I do not meet anymore as I turned in the quest given by the Bone Witch.

What's your advice to me? keep farming the mob until the item drops?

Or will I never be able to complete this quest chain? Thus I will never be able to do the achievement and thus, I will not be able learn the tailor recipe that is linked to this achievement. So sad after doing all the other quests in the other northrend regions...

Sorry if my english isn't clear enough :/
