### ISSUE TITLE
[Item] Set warrior 4 set proc not working

### ISSUE THREAD

**Issue by Phantomyzed** [WoWManiaUK/Redemption#1374]
its not truelly confirmed a guy reported me that his 4 set proc is not working... Posting this in case it can be tested and confirmed if its 100% not procing or just he has some bug issue

**Comment by Lazypeonwowmania** [comment]
I can confirm that the 4 set on the fury warrior is broken as of right now . gives you the GC reduction but when it gives you the second charge of slam, you use it once and both procs go away .

**Comment by fvicaria** [comment]
This report means nothing to me. What set? what tier? what spell?

**Comment by Lazypeonwowmania** [comment]
Im responding to the warrior set being broke.  It's the tier 10 set . The
sanctified pieces give the same 4 set bonus as the regular t10. The bonus
of the two free slam procs. It shows us that we have 2 free slams available
but when you use one they both go away .

**Comment by Phantomyzed** [comment]
yes my bad i forgot to mention about the T10 warrior set.... (4) Set: You have 20% chance for your Bloodsurge and Sudden Death talents to grant 2 charges of their effect instead of 1, reduce the global cooldown on Execute or Slam by 0,5 sec, and for the duration of the effect to be increased by 100%.

**Comment by Wardoc** [comment]
Set bonus in question:  http://wow-mania.com/armory/?spell=70847
Spell in question:  http://www.wowhead.com/spell=1464/slam

It does give 2 stacks of buff called Slam! but one slam consumes both of them instead of letting you Slam twice like you are supposed to.

**Comment by Wardoc** [comment]
Heres a post about Warrior 4set on TC github https://github.com/TrinityCore/TrinityCore/issues/493
Here is a fix made by Shauren: https://github.com/TrinityCore/TrinityCore/commit/4d260a54aebbdabdb9982e297d1e5086f8a68fa9

**Comment by Forrestxz** [comment]
Confirmed as Wardoc wrote.

You should be able to slam twice during the proc, not for 1 slam to consume 2 stacks, maintaining same damage per slam.

**Comment by tvshadowz** [comment]
Report Summary Confirmation: 

Whilst wearing "Ymirjar Lord's" set (item set 272) there is the chance of receiving 2 stacks of "Bloodsurge" (Talent id 46195 CHECK THIS MAY NOT BE CORRECT). 

Each stack of Bloodsurge should give 1 instant spell cast of "Slam" (spell id 1464). 

Bug:
When a player has 2 stacks of blood surge and slam is used, both stacks are used. 

What should happen is that when a player has 2 stacks of bloodsurge and slam is used, only 1 stack of bloodsurge should be consumed allowing for the player to cast the spell twice instantly. 

This has been tested and confirmed. Please ask for any more information

**Comment by captainloozer** [comment]
I've found two things so far while testing this today:

First, it seems random but sometimes I would randomly receive only 1 stack of the "Slam!" but, other times I would receive two. 

Second, regardless of whether I received one stack or two, the buff would be removed if I used slam 1 time.  Even with the second stack, I would not be able to cast slam a second time before the buff was removed.

The Spell ID For the Slam! buff is http://www.wow-mania.com/armory/?spell=46916

Below is a video of the current behavior, showing with 1 stack and 2 that it is removed upon using slam once as reported in the OP.

https://youtu.be/8Pd-W_22IX8

**Comment by Lazypeonwowmania** [comment]
Josh we receive two charges of slam because of our talents . Blood surge of
I'm not mistaken . It's a chance we get two procs of our free slam instead
of two . At the moment out second proc is bugged and won't stay when you
use the first one . But we have a double dam on the first slam to make up
for it .

**Comment by Lazypeonwowmania** [comment]
Instead of one *

**Comment by captainloozer** [comment]
Lazypeonwowmania,

Thank you for clarifying that for me.  I haven't played warrior in ages so I was unaware that a single proc was from talents. 

So from what I've seen here and what I know now, when warriors are lucky enough to received the double stack of Slam!, the second charge is still lost when using the first slam.

**Comment by Wardoc** [comment]
The two charges come from the tier 10 4set bonus not our talents, blood surge only gives 1 stack of Slam! buff not 2, that is what the tier 10 4 set bonus does, the set bonus also shortens the gcd after the slam, which is working as intended.

**Comment by Lazypeonwowmania** [comment]
Lmao I knew wardoc was about to rip me a new one . As soon as I sent this I
remember that it was the t10 4 set that gave us the two charges . Lol got
em tho . Lol
