### ISSUE TITLE
[Quest] Emergency Protocol : Section 8.2 , Paragraph D

### ISSUE THREAD

**Issue by Shirayanne** [WoWManiaUK/Redemption#1377]
Hello ! 
I was doing my quests in the Borean Tundra, trying to get the achievment, when this quest decided not to work. It's my last one to have my achievment. Basically, we need to scuttle 3 flying machine wrecks that are lying around in water. The Southern one is the one that doesn't work. When trying to do it, it says "Required Southern Flying Machine " while I'm in front of it. I've tried to drop the quest and do it again, still no. I've tried many different positions, still nothing as shown in theses screenshots.
![wowscrnshot_071117_022829](https://user-images.githubusercontent.com/30067943/28053904-e2558cfc-65e0-11e7-89f3-4f0121da1313.jpg)
![wowscrnshot_071117_022834](https://user-images.githubusercontent.com/30067943/28053903-e254ff58-65e0-11e7-9833-037fa0fe7052.jpg)
![wowscrnshot_071117_022839](https://user-images.githubusercontent.com/30067943/28053905-e2587638-65e0-11e7-936f-243da56dca0a.jpg)
![wowscrnshot_071117_022843](https://user-images.githubusercontent.com/30067943/28053906-e25c193c-65e0-11e7-8b0c-1fa3bfb97a43.jpg)
I've made an online request and the GM Asmodea answered me. He/She told me the quest was broken and asked me to file an issue here. So, that's what I just did! 

Hope you can fix this, 
With lots of joy in my heart, 
Shirayanne

**Comment by fvicaria** [comment]
I have just done this quest in Redemption and it worked flawless.
![image](https://user-images.githubusercontent.com/9414661/28055848-a5a2326a-6612-11e7-8737-5d5374c1dd1c.png)
![image](https://user-images.githubusercontent.com/9414661/28055807-72b58730-6612-11e7-83f4-209b09f87208.png)
![image](https://user-images.githubusercontent.com/9414661/28055819-827f5aba-6612-11e7-8d98-42b9a2b8afa4.png)
![image](https://user-images.githubusercontent.com/9414661/28055837-97a9c88a-6612-11e7-83c6-7be662ff278b.png)
