### ISSUE TITLE
The Storm King's Vengeance

### ISSUE THREAD

**Issue by alxstad** [WoWManiaUK/Redemption#1378]
every time I get onto the giant it bugs out and I cant use any of his spells and then after reloading or anything like that, I no longer have any abilities on my bars. And then you get stuck with the buff where the game thinks you are riding him but you aren't.

**Comment by fvicaria** [comment]
Works fine for me.
![image](https://user-images.githubusercontent.com/9414661/28056140-b06d7816-6613-11e7-80e3-42571c8b74f3.png)

**Comment by fvicaria** [comment]
Works fine in Redemption.
![image](https://user-images.githubusercontent.com/9414661/28056170-d08521ee-6613-11e7-83c5-c1c924ffaaea.png)

**Comment by alxstad** [comment]
I don't know, I tried doing it at least 4 times..
