### ISSUE TITLE
Permanently flagged for pvp

### ISSUE THREAD

**Issue by jovianstar** [WoWManiaUK/Redemption#1379]
Ever since doing quests in the Hinterlands (A) I've been flagged for pvp.  Despite contacting 3 separate gms, they have been unable to resolve the issue.  The summer event probably didn't help either - which was apparently known to sometimes cause a similar issue.

I was a protection paladin and thought that the spec/use of talents in this zone might have caused the problem.

Things I've tried:
*enabling/disabling pvp flag, logging in an inn, then clearing the cache
*deleting everything locally related to this character
*disabling and deleting all addons (these were not being used when I was levelling at the time)
*respeccing to a different tree.

notes:
*I am using the client downloaded from wow-mania site
*I am also using addons downloaded from the site (I wasn't when this bug first occurred)
*I have been unable to locate any similar bugs that have been reported
*I haven't tried to replicate the bug

**Comment by fvicaria** [comment]
This is a character issue. Probably due to either FFA area or bounty. Create a ticket.

**Comment by jovianstar** [comment]
Thanks for the response but after creating 3 tickets i'm no further forward. 

    On Tuesday, 11 July 2017, 13:10, Janitor <notifications@github.com> wrote:
 

 Closed #1379.—

**Comment by wow-mania** [comment]
What is the character name? Just try to get killed by the opposite faction and wait 5 min at the spirit healer. It should fix it.

**Comment by jovianstar** [comment]
Thanks, that hasn't been suggested yet.  I'll give it a go. 

    On Tuesday, 11 July 2017, 15:36, Janitor <notifications@github.com> wrote:
 

 What is the character name? Just try to get killed by the opposite faction and wait 5 min at the spirit healer. It should fix it.—
