### ISSUE TITLE
Anub'arak. Transition phase. Spikes. 

### ISSUE THREAD

**Issue by Noahcoke** [WoWManiaUK/Redemption#1380]
How it is supposed to be: 
When the boss submerges into the ground, he will use the ability http://de.wowhead.com/spell=67574/von-anubarak-verfolgt on one random player and will chase that player. When he chose a target he will use http://www.wowhead.com/spell=65922/pursuing-spikes on that player. The spikes will also chase the player with increasing speed. The player is supposed to stand on an icy area to stop those spikes. Before the player is dead or he blocked the spikes by standing on an icy area, anub arak wont choose a new target. 

How it is happening:
Anub'arak will switch the target after 2 or 3 seconds not matter what happened, but without resetting the speed. Therefore since its unpredictable which player will be targetted next, that player will be chased by a very fast spiking anub'arak and will die.

**Comment by Forrestxz** [comment]
Confirmed on Red.
