### ISSUE TITLE
[Talent] Frost mage, Fingers of Frost stacks

### ISSUE THREAD

**Issue by Fuzzykitten37** [WoWManiaUK/Redemption#1382]
The talent Fingers of Frost shows two stacks of the buff but after you consume the first stack the last stack no longer acts as if the target is frozen. I noticed this with Deep Freeze - Not being able to use it with only 1 stack up, It also will consume both stacks if used with Fingers of Frost. Ice Lance- It does the bonus damage with first stack of buff but not second. 

http://www.wowhead.com/spell=228598/ice-lance 

I will post a screen shot of the single stack of FoF and Deep Freeze not being available to cast soon

**Comment by Fuzzykitten37** [comment]
![wowscrnshot_071217_023532](https://user-images.githubusercontent.com/29960115/28106780-d6b147ae-66aa-11e7-839f-6fa112d9b522.jpg)

**Comment by hotdoggidy** [comment]
check #1342 + #833 i dont know if its a big problem or something that will cause issues elsewhere but it doesnt seem like its fixable atm.

**Comment by elagen** [comment]
After going through all the patch notes in Wrath there is nothing saying that Deep Freeze acts as the 2nd charge of fingers of frost the only notes i can find is 

Just to clarify the tooltip for anyone perhaps with wishful thinking and who also noticed the grammatical ambiguity: Once you do your "boosted"  Ice Lance you will receive no further benefit for a single charge of Fingers of Frost. In other words the 25% bonus Ice Lance damage does not apply to repeated applications of Ice Lance throughout the 15 seconds for that single charge of FoF.

i have been looking through mage guides - videos all with Wrath 3.3.5a and i can not find where deep freeze acts as a 2nd charge with fingers of frost

**Comment by hotdoggidy** [comment]
Related issue just started this week (after ICC reset) Deep Freeze cannot be cast even with BOTH stacks of FoF available.

**Comment by hotdoggidy** [comment]
i have a screenshot but i cant put it in here for some reason.

**Comment by hotdoggidy** [comment]
thats talking about a SINGLE charge of FoF, when a player tries to cast multiple ice lances with 1 charge up; it should only do the bonus damage for the FIRST ice lance casted with only 1 charge. 

Since its only talking about a single charge (2nd charge) of FoF, that note is evidence to the fact that ice lance should have bonus damage on both charges, meaning FoF should have its effect with both charges. hence, Deep freeze should be castable with EITHER charge of FoF and Ice lance should have bonus damage on BOTH charges.

**Comment by squalllh1989** [comment]
I'm sorry elagen pls that don't need to be research, you can read the fucking text of the skill which is said that "Gives your Chill effects a 7% chance to grant you the Fingers of Frost effect, which treats your next 2 spells cast as if the target were Frozen. Lasts 15 sec" (http://wow-mania.com/armory/?spell=44543)
now please come to your sense that when the target is frozen, deep freeze can be cast and ice lance does triple the damage. It is said that it won't be fix, there is nothing we can do about that, but saying something like that is destroying our report about bug.

**Comment by elagen** [comment]
Ok first of all, to learn about the big we need to do the fucking research to have it just like retail was back in 3.3.5a so the reports I find helps us more to understand, it might be the case of 2 deep freeze it might not be, and if u have so much input why don't u help to find the proper way for deep freeze to work and how it should, if u don't want to then don post negative shit here

**Comment by squalllh1989** [comment]
ok, it's totally my fault, so calm down, i just want to say that the angry you get when you see my post is what i got when i see your post. I don't wanna mean anything negative, and if there is in my previous post, then i'm sorry but i don't mean that, what i wanna say is: the talent should work the way the text said, not 2 stack display and 1 stack work (sound really like the 4 t10 pieces of warrior, with 2 stack of slam and 1 slam consume 2 stack)

**Comment by elagen** [comment]
The warrior t10 4 piece is not an easy fix itself, if deep freeze works the same as I said then again it is not an easy to apply we have been at it for months and still we are working hard to fix them both

**Comment by tvshadowz** [comment]
This issue will be closed and reopened due to poor service from collaborators.

**Comment by tvshadowz** [comment]
If you'd like to comment, politely, on the new issue made please follow this link.

https://github.com/WoWManiaUK/Redemption/issues/1463

Please keep in mind that testers need as much information as possible to make sure the issue reported is tested accurately and fixed properly. But, in any way, does this require rude language or insults from staff or players.
