### ISSUE TITLE
[Quest] The Drakkensryd

### ISSUE THREAD

**Issue by StarrZappa11** [WoWManiaUK/Redemption#1385]
Unable to complete this quest as I cannot kill the Hyldsmeet Drakerider. I am able to harpoon myself from drake to drake, but every time I cast a spell at the target it says "Evade". Please help, thank you.

Hyldsmeet Drakerider - http://www.wowhead.com/npc=29694/hyldsmeet-drakerider
Quest - http://www.wowhead.com/g00/quest=12886/the-drakkensryd?i10c.referrer=https%3A%2F%2Fwww.google.com%2F

![image](https://user-images.githubusercontent.com/29348748/28147407-2b17e264-674e-11e7-82c4-c1286d3005f7.png)

**Comment by wow-mania** [comment]
Quest works. Keep trying.
