### ISSUE TITLE
[Quest] If He Cannot Be Turned

### ISSUE THREAD

**Issue by MK8o8** [WoWManiaUK/Redemption#1387]
#1321 
It is my understanding that this was supposed to be fixed in rev 39 from my previous ticket, #1321 and I see that we are now on rev 42. I attempted this quest again but have the same issue.

![image](https://user-images.githubusercontent.com/29690470/28240216-e8a98f64-6931-11e7-839f-67953f1dfcd4.png)

**Comment by wow-mania** [comment]
Send me the link to the NPCs that you say are "underpowered". I will check them.

**Comment by MK8o8** [comment]
http://www.wow-mania.com/armory/?npc=29860

**Comment by wow-mania** [comment]
Just checked the quest and completed it no problem. The point of the quest is for you to kill it not the NPC helpers. By the look of it you can't even keep the aggro on you.
I have modified a little bit more to make the other two NPCs last a little longer but this will not change the fact that you are the one supposed to kill him. The other NPCs are there for moral support only.
You will have to wait for the next restart. But as I said there won't be a lot of change from what is there now.
