### ISSUE TITLE
TOC 10 heroic aka Trial of the Grand Crusader last boss did not reset. 

### ISSUE THREAD

**Issue by xandror** [WoWManiaUK/Redemption#1388]
Our 10 man heroic toc 10 group wiped on phase 3 of the final boss. The boss did not reset after everyone died and people continued to die from the poison DOT as we came back in. Weeble attempted to reset the boss but no matter what he tried, the boss was unattackable.

**Comment by fvicaria** [comment]
Please follow the procedure described below before creating a new issue:
[How to Properly Report an Issue](https://github.com/wow-mania/Redemption/wiki/How-to-Properly-Report-an-Issue)

This will help developers identify and fix the issue quicker. Incorrectly or unclear reports will simply be deleted.

**Comment by Forrestxz** [comment]
Yes please do a more detailed format with links.

This is confirmed though, once you wipe on Anub'arak the boss encounter doesn't reset.
