### ISSUE TITLE
[Quest] If He Cannot Be Turned.... again

### ISSUE THREAD

**Issue by MK8o8** [WoWManiaUK/Redemption#1389]
In response to #1387 ,
Here's the combat log for this quest. How is he soloable when General Lightsbane has 88k HP and hits for 3-4k each? I only have 12k HP as a fresh lvl 80 and die in 3-4 hits. In retail, the NPC, Vile, is supposed to tank him while you dps. If you don't believe me, feel free to watch me attempt this quest and then explain to me how I'm doing it wrong...

![image](https://user-images.githubusercontent.com/29690470/28244793-e44d3e02-69a9-11e7-8d05-e6ed2e24e72b.png)

**Comment by wow-mania** [comment]
Quest works and will not be changed. Please do not reopen.
