### ISSUE TITLE
[Spell] Paladin - Hammer of Justice

### ISSUE THREAD

**Issue by vexation47** [WoWManiaUK/Redemption#1391]
Hammer of Justice: Stuns the target for 6 seconds and interrupts non-player spell casting for 3 seconds.

The first half works, but bosses that are immune to stuns are immune to the interrupt portion as well.  Blizzard added this specifically for bosses that are immune to stun, because if they weren't immune they would be stunned :)

**Comment by LooneyBin** [comment]
http://www.wow-mania.com/armory/?spell=10308

**Comment by elagen** [comment]
Can you give more examples of what you are trying to interrupt? what bosses - what spells?

**Comment by vexation47** [comment]
Lady Deathwhisper, Devourer of Souls, Mammoth boss in Gun'drak, etc.

As I said it seems to be bosses that are immune to stun are immune to the interrupt as well.  To be honest I'm not sure if the interrupt mechanic is present or not.  I cant really test it on npcs that arn't immune to stun because they just get stunned.

**Comment by fvicaria** [comment]
As is.
