### ISSUE TITLE
[Quest] The Black Knight's Fall

### ISSUE THREAD

**Issue by ingelinge40** [WoWManiaUK/Redemption#1394]
The npc  need to summon the Black Knight buthe is just telling that he need to summoBut  does not do it
![wowscrnshot_071717_215727](https://user-images.githubusercontent.com/25806660/28287351-9dcf0bf2-6b3b-11e7-9467-b9185be9053d.jpg)

**Comment by fvicaria** [comment]
Quest works fine if you have all requisites. Try removing the quest and adding it again.
