### ISSUE TITLE
[Quest] The Last Line Of Defense

### ISSUE THREAD

**Issue by ingelinge40** [WoWManiaUK/Redemption#1395]
you cant enter the cannon
I have tried with gm on and of and visible 
![wowscrnshot_071717_230147](https://user-images.githubusercontent.com/25806660/28289783-47d8eae8-6b44-11e7-98d3-de129a02a4e0.jpg)

**Comment by Pdh362** [comment]
I'm encountering the same problem - some cannons have attached within the towers, others are mounted properly, but none of them will interact with either a right mouse click, or the 'interact with' key binding.

**Comment by loopty** [comment]
I also had a problem with cannons not appearing at all.
