### ISSUE TITLE
Quest "Keeping Pace"

### ISSUE THREAD

**Issue by cathyr1** [WoWManiaUK/Redemption#1396]
Hello! I have found a bugged quest named "Keeping Pace" in Shimmering Flats. NPC Zamek has a blue questionmark over his head but he do nothing when I speak to him. Also Rizzle´s plans are on the ground but nothing happens when I click on it. So the quest cannot be completed. Can you please check and fix this? Thanks a lot.

**Comment by fvicaria** [comment]
Please follow the procedure described below before creating a new issue:
[How to Properly Report an Issue](https://github.com/wow-mania/Redemption/wiki/How-to-Properly-Report-an-Issue)

This will help developers identify and fix the issue quicker. Incorrectly or unclear reports will simply be deleted.

**Comment by fvicaria** [comment]
Quest works fine. 

![image](https://user-images.githubusercontent.com/9414661/28355864-bd0b0750-6c5d-11e7-9325-04b634a39177.png)
