### ISSUE TITLE
[Raid] Ruby Sanctum

### ISSUE THREAD

**Issue by Braytonx** [WoWManiaUK/Redemption#1398]
Pet's are going infront or at the sides of halion while they should be behind halion and following them this results in pets being killed by halion. Pets are also dieing from the flames that the meteor strike spawn.
(http://www.wow-mania.com/armory/?spell=75879#.)

This is a screenshot from paragons first halion 25 heroic kill where you can clearly the the pet behind halion in the middle of the meteor strike but not dieing from it.
![pet](https://user-images.githubusercontent.com/30273450/28340148-03a6b618-6c0f-11e7-9f31-317c04bb269c.png)

This is the paragon video where you can see the pets are staying behind halion even tho the boss is being rotated (2:25-4:05)[https://www.youtube.com/watch?v=cpbIWfLwp-8](url)

**Comment by Forrestxz** [comment]
Confirmed, happened in our raid.

**Comment by tvshadowz** [comment]
Can confirm this is still happening in dev. Any updates will be posted.

**Comment by fvicaria** [comment]
Pets go for the back unless being the victim. Please re-test when dev is up.
