### ISSUE TITLE
Hunter Auto attack

### ISSUE THREAD

**Issue by elagen** [WoWManiaUK/Redemption#1399]
Arokh 

Hey! i Found more information about the hunter's autoshot bug. Everytime when hunter's get either knockup, knockback, stun or other CC spell it stops working( this happened also during some Rhc dungeons and raid bosses ).

(i have been asked t Post here)

**Comment by Critias14** [comment]
I can confirm this.

**Comment by tvshadowz** [comment]
Fixed in dev.

**Comment by captainloozer** [comment]
Tested with hunter autoattacking a druid.  Druid used typhoon to push the hunter back. Hunter still shoots without having to re-initiate the autoattack sequence.

Confirmed fixed in dev.
