### ISSUE TITLE
Green protodrake Mission-Chain

### ISSUE THREAD

**Issue by JeremiahSeagraves** [WoWManiaUK/Redemption#1400]
Hello!
I'd like to report the first (and don't know if any of the subsequent quests) quest of the chain of quests from the Freenzyhearts at Sholazar, The first mission, in which you got to kill "Pitch" a panther at Sholazar in order to get the Freenzy's to talk with you doesn't seem to work, I killed Pitch and the Freenzy (Gekek) just said somethings but didn't offer me the quest.

So, the bug that I wanted to report is that one. Moreover, I'd like to be sure that all the quest chain in order to get the Egg from which you can get the Rains of the Green Protodrake really are not bugged.

Thanks,
Char name: Jerryxhunt

**Comment by JeremiahSeagraves** [comment]
Apparently, the first quest is this one: [](http://www.wowhead.com/quest=12654/the-part-time-hunter)

**Comment by JeremiahSeagraves** [comment]
Apparently, the first quest is this one [http://www.wowhead.com/quest=12654/the-part-time-hunter](http://www.wowhead.com/quest=12654/the-part-time-hunter)

**Comment by fvicaria** [comment]
Quest worked fine for me. Drop it and get it again. Maybe you killed it too fast?

![wowscrnshot_072017_090220](https://user-images.githubusercontent.com/9414661/28407103-d57a1c36-6d2a-11e7-904d-7191bb3d0fb6.jpg)
![wowscrnshot_072017_090539](https://user-images.githubusercontent.com/9414661/28407108-d7ca3214-6d2a-11e7-8dbb-9c5a324fd41f.jpg)
