### ISSUE TITLE
[QUEST] Escape From Durnholde: Thrall's Destiny

### ISSUE THREAD

**Issue by Megjag** [WoWManiaUK/Redemption#1401]
*I noticed there was a closed issue for this same bug, but there was no solution posted and I have been trying to complete this quest for some time now (at least a week and a half).

**Quest Location:**
Thrall, who is in the basement of Durnholde Keep in the Caverns of Time dungeon.

**What should happen:**
You should be able to take the quest from Thrall, and then speak to him again to manually start the quest interaction. You're supposed to follow Thrall out of Durnholde, killing the mobs that attack, to keep him safe until he reaches Tarren Mill, where you have to fight a boss to complete the quest and become attuned to The Black Morass.

**What is actually happening:**
When I take the quest from Thrall, the quest interaction does not begin. Thrall remains motionless as if the encounter did not begin. The first time I took the quest I was able to talk to Thrall to start the encounter, but I am unable to now.

**What may have happened:**
As far as I can tell, the quest bugs when a user attempts to re-do it. Starting the quest worked fine the first time I did it, but I had to abandon it when Thrall clipped through the world. When I left and reentered the dungeon to reset it, I was no longer able to speak with Thrall. I have tried redoing the quest, resetting the dungeon, etc. with nothing working.

**When:**
This began probably a week and half - two weeks ago. I initially logged a ticket, but was told to report the bug here. 

**WoWHead:**
http://www.wowhead.com/quest=29599/escape-from-durnholde

I have the achievement for this dungeon, as the very first time (the time before the bug was encountered) I ran through it, I was not doing the quests. I only had to re-do the dungeon to get attuned for the Black Morass.

**Comment by fvicaria** [comment]
Correct quest link:
