### ISSUE TITLE
Stranglethorn Vale Fishing Tournament

### ISSUE THREAD

**Issue by Gwapo24** [WoWManiaUK/Redemption#1402]
Hello, the STV fishing tournament is not working correctly on time at all.

I went to STV and the tastyfish schools had already spawned at 1330 server time and gave me time enough to fish up 40 tastyfish.  I went to turn in the 40 tastyfish at 1400 ST right after he announced that the fishing event was starting and he gave me a message that the event was over and a winner had already been found.   Nobody else was in sight or no winner message had been given at all.  This has happened to me for two weeks and it cannot be completed leaving only one fishing event to people that want to get the Salty title.  Thanks for your time in looking into this and good luck in trying to fix it.

**Comment by fvicaria** [comment]
Please follow the procedure described below before creating a new issue:
[How to Properly Report an Issue](https://github.com/wow-mania/Redemption/wiki/How-to-Properly-Report-an-Issue)

This will help developers identify and fix the issue quicker. Incorrectly or unclear reports will simply be deleted.

I need quest, NPC, items links and ids please.

**Comment by Gwapo24** [comment]
Dearly sorry about that, here is some more info:

http://www.wowhead.com/npc=15077/riggle-bassbait, Riggle Bassbait is the NPC.

http://wow-mania.com/armory/?quest=8193 is the quest, Master Angler.

http://wow-mania.com/armory/?achievement=306 is the achievement that you get from winning, Master Angler of Azeroth.

http://wow-mania.com/armory/?item=19807 is the fish x40 that you fish up in STV to win the event.

http://www.wowhead.com/object=180248/school-of-tastyfish is where they are fished out of, School of Tastyfish.

Hope this helps in the investigation a lot better.  The event is supposed to start at 1400 ST but it has shown that the Schools of Tastyfish are spawning as early as 1300 ST so that you can fish them early.  I don't know why the NPC has completed message at the beginning of the event tho.

**Comment by Gwapo24** [comment]
I was in ICC at around 1320 ST when someone in /world chat said Hon won the STV fishing event.  I went to STV at around 1409 and the NPC http://www.wowhead.com/npc=15077/riggle-bassbait showed that there was a winner already.  It seems that the timing is off on the event still and did not start at 1400 ST.
