### ISSUE TITLE
Sindragosa's tombs go away with [Death Coil]

### ISSUE THREAD

**Issue by 20tebuscar** [WoWManiaUK/Redemption#1404]
When sindragos change to the phase two, and she use [Ice Tomb] (http://www.wow-mania.com/armory/?spell=69712#see-also) on the person that was marked by  [Frost Beacon] (http://www.wow-mania.com/armory/?spell=70126) he become the "tomb".

Inssue:
-If one warlock use [Death Coil] (http://www.wow-mania.com/armory/?spell=47860) on the tomb, it go away like someone in fear. 
-The person inside the tomb stay in the same place and immune on all(visual bug?), but if the orthers hide behinde him, they receve damage from the [Frost Bomb] (http://www.wow-mania.com/armory/?spell=69845). It's like the tomb wans't there.

So, I can conclusion:
- The person inside the tomb, staty in the same place, where he was "frozen", and imunne to all like it's suppoused.
- If the tomb walk away, the others people lose the "protection" to hide, and then receve all damage from [Frost Bomb]

**Comment by fvicaria** [comment]
Modified immunity. It will take effect on next restart.
