### ISSUE TITLE
 Issue with the bloody elf.

### ISSUE THREAD

**Issue by gracjanox** [WoWManiaUK/Redemption#1407]
I can not create a bloody elf on my account, but how do you create a new one it does not work what do I do? This is not a problem with pather only account.
Maybe the administrator could fix it somehow?
I do not know whether I could contact him here or on some other site.

**Comment by fvicaria** [comment]
This is not a server-side issue.
Contact support directly via email or skype.

**Comment by gracjanox** [comment]
Or maybe you have an email?
