### ISSUE TITLE
Stranglethorn Vale Fishing Contest cont'd

### ISSUE THREAD

**Issue by Gwapo24** [WoWManiaUK/Redemption#1408]
https://github.com/WoWManiaUK/Redemption/issues/1402 is the link to the past issue with the STV fishing contest not working at correct times.

Sunday at around 1320 ST, I was in ICC and a couple of people had said that the STV fishing event had already found a winner.  After the raid, at around 1409 ST, I went to STV and the NPC http://www.wowhead.com/npc=15077/riggle-bassbait had said there already was a winner for this week.

So the event is not going off at 1400 ST like it should, but maybe at around 1300 ST and it still needs to be adjusted or the fish have still spawned early and people are fishing early to turn them in as soon as it starts.  Hope this helps in solving this.

**Comment by fvicaria** [comment]
The event goes from 13:00 to 15:00 what is the issue? There can be a winner at 13:01 or a winner at 14:59.

**Comment by Gwapo24** [comment]
It starts at 1400 ST, the calendar even shows this also.

**Comment by fvicaria** [comment]
It was at the wrong time on the server. It has been fixed now but it will only take effect for next week.

**Comment by Gwapo24** [comment]
Ok, thanks for the update, so now is it set to start at 1300 ST or 1400 ST?
