### ISSUE TITLE
Making Goblin Mortar

### ISSUE THREAD

**Issue by Meneltel** [WoWManiaUK/Redemption#1409]
Goblin Mortar, engineering 205. Have all of the components, but "I cant make it yet" is what I am told. My skill is above that (213) but still cant make it. Please look into it. I know it existed in Vanilla or early TBC (I used it at that time when I played retail). thank you. http://db.vanillagaming.org/?item=10577

**Comment by fvicaria** [comment]
works. please search before posting new issues.
