### ISSUE TITLE
Quest - The Fallen Sisters [11314]

### ISSUE THREAD

**Issue by tvshadowz** [WoWManiaUK/Redemption#1410]
The quest "The Fallen Sisters" id 11314 is currently unable to be completed. 

Area: Howling Fjord - coordinates 51,26

During the quest the item "Lurielle's Pendant" id 33606 is used on "Chill Nymphs" id 23678 seven times to complete the quest. Currently when the Pendant is used on the Nymphs it aggros them but does not free them as the quest requires. 

When the Pendant is used it should turn the nymph friendly and they should despawn. 

Useful links:
http://www.wowhead.com/quest=11314/the-fallen-sisters
http://www.wowhead.com/item=33606/lurielles-pendant
http://www.wowhead.com/npc=23678/chill-nymph

Please let me know if any more information is needed.

**Comment by fvicaria** [comment]
Fixed. Should be in Redemption on next restart.

**Comment by JoyfulPangolin** [comment]
The Chill Nymphs do not despawn after turning friendly.  The quest item will not work unless the Chill Nymphs are attackable.
