### ISSUE TITLE
Invincible's Reins unable to be used in Dalaran.

### ISSUE THREAD

**Issue by Forrestxz** [WoWManiaUK/Redemption#1413]
The mount which has a 100% drop chance off Lich King 25 Heroic can't be used in Dalaran.

http://wow-mania.com/armory/?spell=72284

It's considered a ground mount AND a fly mount though here it seems to be registered as a Fly mount only so it's unable to be used in Dalaran for anyone who gets it.

**Comment by fvicaria** [comment]
As is for now. A more general solution is being considered.
