### ISSUE TITLE
[ADDON] Augmented Virtual Reality 

### ISSUE THREAD

**Issue by furkanaltur34** [WoWManiaUK/Redemption#1414]
https://www.wowace.com/projects/avr and ,
https://www.wowace.com/projects/avr-encounters
these addons re blocked by blizzard cuz of they re too op for retail,
https://www.engadget.com/2010/05/20/blizzard-to-break-the-avr-mod-in-patch-3-3-5/ that's a new for that broke. 

Memory offset for World of Warcraft 3.3.5.12340

00510089 | 75 | 90 |
0051008A | 15 | 90 |
 
That's i found solution for fixing this addon but it's not legal fix for players. Because players need to do memory editing and its being hacking. 

Waiting for your answers.

**Comment by fvicaria** [comment]
Not appropriate for this repository. Not going to do anything about this.
