### ISSUE TITLE
[Anub'Arak ToC 10/25] Nerubian Burrowers

### ISSUE THREAD

**Issue by Forrestxz** [WoWManiaUK/Redemption#1415]
During the Anub'Arak Encounter on ToC 10/25, killing the Frost Spheres (http://www.wowhead.com/npc=34564) spawns a frost patch on the ground called PERMAFROST (http://wow-mania.com/armory/?spell=67856)

**Permafrost - Freezes the ground in a small area, preventing most creatures from burrowing through it and reducing movement speed over the area by 20% (80% on heroic).** 

When the Nerrubian Burrowers spawn (4 on 25 man, 2 on 10 man), they should be tanked on top of Permafrost to avoid SUBMERGE/BURROW (http://wow-mania.com/armory/?spell=67322).

HOW IT SHOULD WORK: Basically, when tanked on top of frost patches (Permafrost) they can't burrow underground and respawn again with full HP, so they should be killed when they spawn.

HOW IT WORKS: Adds being tanked on top of frost patches (Permafrost), they still Submerge/Burrow underground, come back up in 15-20 seconds and this time there are the new adds which spawn + the old adds which burrowed resulting into too many adds up.

**Comment by Fuzzykitten37** [comment]
I can confirm this I just did ToC10 on Redemption. Its not every time but it does still happen even if there is frost under the mob.

**Comment by keidian** [comment]
Confirmed. Happens in 25hc

**Comment by Forrestxz** [comment]
It happens pretty much every time adds don't die fast enough, they burrow. As long as they're on patch, they should NEVER burrow regardless of time.
