### ISSUE TITLE
character "dead" but still being attacked 

### ISSUE THREAD

**Issue by axxerano** [WoWManiaUK/Redemption#1417]
My Character Narkotic lagged out whilst being attacked so i exited the game and logged back in. so now i am stuck being attacked whilst dead and unable to release
![wowscrnshot_072517_173711](https://user-images.githubusercontent.com/30442127/28583153-0d948c4e-7160-11e7-85d3-0b1e5114a472.jpg)

**Comment by fvicaria** [comment]
Open a ticket for thi.

**Comment by axxerano** [comment]
how?
