### ISSUE TITLE
Old hillsbrand quest

### ISSUE THREAD

**Issue by StefanelStan** [WoWManiaUK/Redemption#1418]
The food "Old hillsbrand" (http://www.wowhead.com/quest=10282/old-hillsbrad) is not working correct for some of the people. I have taken it but the NPC inside does not have the dialog to close the quest. Instead it has the option to offer incendiary bombs.

What it should do:  take the quest from Andormu and close it inside "old hillsbrand foothills from inside escape from durnholde dungeon by talking with Erozion NPC.

How it is bugged : Erozion does not have the option to close the quest but it simply gives me the bombs to use them. I have completed the dungeon and when it respawned 2nd time (next to the final boss) is still gives me the option to choose the incendiary bombs.

I have spoken with some people : it worked for them but for others it behaves as I described.

**Comment by babbadook** [comment]
i still do have the same problem as readen above

**Comment by Ashercraft** [comment]
Tried doing this quest with my wifetoday.  We had the same issue.  Erozion just gives you bombs, but the quest never updates, there's no completion dialog, and he just stands there with the yellow (?) on top of his head.  Our characters are both level 74

**Comment by fvicaria** [comment]
I will re-check. Can you tell me exactly which quest you are on and which ones you have completed. Screenshots and links will help also.
