### ISSUE TITLE
Quest "Favor for Krazek"

### ISSUE THREAD

**Issue by NightSeekerr** [WoWManiaUK/Redemption#1422]
The quest wants you to get 4 loads of Lesser Bloodstone Ore from Drywhisker Gorge (a cave) in Arathi Highlands. I'm a miner, I've been there, and there was no Lesser Bloodstone Ore.

**Comment by fvicaria** [comment]
![image](https://user-images.githubusercontent.com/9414661/28618024-b72a78dc-71fa-11e7-9416-66a40d91c330.png)


They are there. Search a little harder. There are 29 of them.

**Comment by NightSeekerr** [comment]
I just checked again and there really were there. That's interesting because I've checked the entire cave twice before and there weren't any...
