### ISSUE TITLE
Lockpick Skill bugged !!!

### ISSUE THREAD

**Issue by Adonja** [WoWManiaUK/Redemption#1423]
Hello recently i send message (ticket) to GM and i inform about my Lock pick skill i have 104 raised and im supposed to increase it until 170 in westfalls as it mentiones in guide which i found on google that Rogue can increase skills 100/170 in Westfalls in some tower.So i went there and cant do anything i mean chest is there on top of the tower but im not able to do anything to click on it and start my training i tried everything so please if u get chance can u solve the problem and let me know if its possible to raise my skill

Thank you for your time and patience while reading so long message
Have a good one
<3

**Comment by fvicaria** [comment]
Just go to other regions. If you see that you are not increasing it open a ticket and a GM will help.

**Comment by Adonja** [comment]
I did i send the ticket to GM and she told me that i need to post here my issue.
