### ISSUE TITLE
[Quest] Taretha's Diversion

### ISSUE THREAD

**Issue by StefannelA** [WoWManiaUK/Redemption#1424]
Quest name : Taretha's Diversion
Quest Location : Escape from Durnholde dungeon
Link : http://www.wowhead.com/quest=29598/tarethas-diversion

Issues : 

1. Upon completing Old Hillsbrad quest (http://www.wowhead.com/quest=10282/old-hillsbrad) the player receives next quest in chain (Taretha's Diversion from NPC Erozion). If the player accepts the quest then aborts it, the NPC Erozion does not have the option to pickup this quest (Taretha's Diversion) again even after relog or instance reset (so once it's aborted, it cannot be picked up again; not even by sharing from another player (I tried this with a friend )). NPC Erozion does have the yellow exclamation mark above the head but does not have the option to select this quest.
2. While doing Taretha's Diversion and planting all 5 bombs (so putting the quest at Complete stage) Thrall does not have the option to turn in this quest and pick up next one in chain ( Escape from Durnholde http://www.wowhead.com/quest=29599/escape-from-durnholde). The only option shown by Thrall is to start the event and from that point the yellow question mark dissappears.

**Comment by Pitypalaty** [comment]
Exact description. I have the same problem, completed the quest, planted all the bombs, escorted Thrall through the entire "dungeon", but nothing happens in the end. Please do something about it, without it i can't go on with the keeper of times quest, so i can't acces Black Morass ---> can't do master of elixir quest.
Thanks in advance.

**Comment by tvshadowz** [comment]
Both Issues stated are confirmed:

The NPC Andormu (20130) does not currently regive the quest Old Hillsbrad (10282) once it has been abandoned. 

After quest completion of Taretha's Diversion (29598) Thrall does have a question mark above the NPC however as previously described the option to turn in the quest and obtain the next is unavailable (see screenshot). 

![wowscrnshot_080317_002338](https://user-images.githubusercontent.com/30256554/28899530-86d5edee-77e3-11e7-9364-a596a789823f.jpg)

**Comment by fvicaria** [comment]
Quest is not repeatable so if you drop it you lose it.
I will try to by-pass this but for now it will be as-is.

**Comment by Pitypalaty** [comment]
That sucks..... I don't really want to start alchemy again on another
character.... When can i expect the solution, or something which helps me
through this situation? thanks in advance!

2017-08-16 12:38 GMT+02:00 Janitor <notifications@github.com>:

**Comment by fvicaria** [comment]
It should work after restart. 
Open a ticket and ask a GM to remove the quest from you, this way you can re do it.
