### ISSUE TITLE
Hunter pet / Raptor Issue

### ISSUE THREAD

**Issue by Maxhunter5** [WoWManiaUK/Redemption#1425]
When I tamed 3 different raptors and experienced the same 2 issues than other hunter players on Redemption realm, made me think that I should report these issues.

Issue 1: Raptor keeps attacking or getting attacked when there is no enemies around, like in the no where..

Issue 2: Raptor keeps running even when remaining in position (like standing).

I know its not a big problem but it is actually very annoying, and lets say there is alot of hunters out there who would wish a raptor as their companion.

Lets fix this Wow Mania! Thanks for your time.

**Comment by fvicaria** [comment]
duplicate. please search before posting.
