### ISSUE TITLE
Sunken Temple bug (barrier)

### ISSUE THREAD

**Issue by cathyr1** [WoWManiaUK/Redemption#1426]
There is a bug in Sunken Temple near boss Jammal'an http://www.wow-mania.com/armory/?npc=5710. The barrier that blocks the way to him cannot be removed even when killed all 6 troll bosses so it is not possible to face the boss. There is a quest - link http://www.wow-mania.com/armory/?quest=1446.
![barrier](https://user-images.githubusercontent.com/30184491/28734585-fa7f2c7a-73e1-11e7-83cb-bd8823e5f23c.png)

**Comment by elagen** [comment]
to Get the barrier down u need to go Down stairs and Kill the Boss when u Active the Snake idols

![stsecretcircle](https://user-images.githubusercontent.com/22685042/28751550-5cfe2506-7502-11e7-95e8-0618d49e9316.jpg)
