### ISSUE TITLE
Quest bugged in Sunken temple (The God Hakkar)

### ISSUE THREAD

**Issue by cathyr1** [WoWManiaUK/Redemption#1427]
There is another bug in Sunken Temple - the quest http://www.wow-mania.com/armory/?quest=3528. There is an item http://www.wow-mania.com/armory/?item=10662 that should drop from the boss when he dies but it does not.

**Comment by Noahcoke** [comment]
Worked for me. I used the egg, the boss got summoned, killed it and it dropped the needed essence.  
https://gyazo.com/55dbf26826b8c9e728da2af7ce50f9d7

Even though the bossfight itself isnt working as intended. After using the egg (http://www.wow-mania.com/armory/?item=10465) an event should start with waves of enemies. Only after extinguishing all flames in the corners of the room the boss should spawn.

However here he spawned right after using the egg. 

Quest is doable though.

**Comment by Noahcoke** [comment]
I just reread your issue. The item you linked doesnt drop from the boss directly. The boss only drops the essence shown in the gif i linked. That essence you have to use on the egg you have in your inventory.
