### ISSUE TITLE
[Icecrown Citadel - Professor Putricide] Unbound Plague removed by Cloak of Shadows

### ISSUE THREAD

**Issue by keidian** [WoWManiaUK/Redemption#1429]
Spell 70911 shouldn't be removeable by rogue's cloak of shadows 31224. This allows players to avoid one of the most important mechanics on the encounter.

**Comment by Forrestxz** [comment]
Confirmed

**Comment by captainloozer** [comment]
Confirmed fixed in dev.  Cloak of shadows does not remove Unbound Plague.

![cloak](https://user-images.githubusercontent.com/9828794/29496885-fa9fb4c8-85a1-11e7-9f1a-e9aca3be21cc.PNG)
