### ISSUE TITLE
[Quest] Absholutely... This Will Work!

### ISSUE THREAD

**Issue by ingelinge40** [WoWManiaUK/Redemption#1430]
~When giving the potion, the prisoner did not respond and the quest is not getting marked as complete

**Comment by Noahcoke** [comment]
Please follow these instruction when reporting an issue: 
https://github.com/WoWManiaUK/Redemption/wiki/How-to-Properly-Report-an-Issue

It helps us to solve it.

**Comment by tvshadowz** [comment]
Hi there Ingelinge40!

Please follow the rules of how bugs should be reported here http://www.wow-mania.com/forums/topic/71 . This helps us testers greatly and allows for fast and efficient fixes. 

For instance; please insert the area of the bug into the title within brackets, add any links of quests or items from wow-head and describe what should be happening and what is currently happening. 

Thanks for the report! We really appreciate your participation in making the server the best it can be :)
