### ISSUE TITLE
Will of the Forsaken doesn't work on warlock Fear

### ISSUE THREAD

**Issue by zxlol** [WoWManiaUK/Redemption#1431]
When I duel a warlock in my party and he fears me, I can't use Will of the Forsaken and it states 
"You can't do that while feared"
The warlock had either a rank 1 or rank 2 fear, but rank 1 should work. 
Sorry for no more info, but I can't think of anything else.

**Comment by Forrestxz** [comment]
Will test it this evening, thanks.

**Comment by tvshadowz** [comment]
http://www.wowhead.com/spell=7744/will-of-the-forsaken

**Comment by tvshadowz** [comment]
Fear rank 1 doesn't allow will of the forsaken to be cast to debuff. However max ranked fear does allow will of the forsaken to be cast.

**Comment by tvshadowz** [comment]
After a long struggle which involved many server crashes and restarts this was fixed in dev thanks to the brilliant @fvicaria
