### ISSUE TITLE
[Icecrown Citadel - Sindragosa] Asphyxiation

### ISSUE THREAD

**Issue by forrestxyz** [WoWManiaUK/Redemption#1432]
#1289 

**SOME** Ice tombs (70157) in the second phase  [<35% HP phase, **NOT** air phase] still getting instant Asphyxiation (71665)

**Comment by keidian** [comment]
Doesen't happen on every Ice tomb, was mostly every 2nd Ice tomb, we can't properly reproduce.

**Comment by Forrestxz** [comment]
Indeed, seems like every 2nd tomb.

**Comment by tvshadowz** [comment]
Hi all! 

Below are screenshots of the current fight with Sindragosa and the effect "Asphyxiation". 

![sindragosa test](https://user-images.githubusercontent.com/30256554/29428789-5d513e66-8386-11e7-896a-96c117869233.png)

**Comment by philoudu16** [comment]
My guess would be the asphyxiation of the first tomb is affecting ppl in the second tomb (the asphyxiation delay should be 20s and the tombs every 20s..). So first tomb comes down, no asphyxiation, after 20s, a second tomb appears and the asphyxiation from the first tomb happens, affecting ppl who have just been tombed.
(it's just a guess, hope it can help you solving the issue)

**Comment by tvshadowz** [comment]
Haha yes, this issue has been fixsd in dev and hopefully will be released soon :)

**Comment by tvshadowz** [comment]
This was tested again on dev whilst sindragosa was on 17% hp. All tombs made gave the asphyxiation debuff after 20 seconds.

**Comment by nyhmii** [comment]
How did you fix this? :S please help :)?

**Comment by tvshadowz** [comment]
Nyhmii, this fix has been deployed onto the live server.

**Comment by nyhmii** [comment]
I mean, I'm a new developer. How do it Fix this for my own lan server?

**Comment by tvshadowz** [comment]
This is not appropriate for this forum.
