### ISSUE TITLE
[Item set] Chainmail Lichking set - Iron Dwarf and Vrykul effects not working

### ISSUE THREAD

**Issue by seridwyn** [WoWManiaUK/Redemption#1434]
i opened a report on this some time ago and it said it was fixed in dev but my set still doesn't work right  the effect only procs when you equip the set NOT during combat as i think its supposed to i have uploaded a shot of the set and the specific wording of the effects which states you only get the effect for thirty seconds which is why i believe it only procs the one time when you equip it. I would like to see this fixed or perhaps my set transfered or refunded in some way if it cant be as the lack of that effect cuts down the sets effectiveness greatly thank you for your time on this ~ Seridwyn
![wowscrnshot_080117_021550](https://user-images.githubusercontent.com/26843402/28818881-4d8d0fd2-7661-11e7-9c64-c16212d93c6c.jpg)

**Comment by Noahcoke** [comment]
How long ago did you post that issue? If you see the label "Fixed in Dev" it doesnt mean its fixed on the redemption server aswell. Maybe it didnt get applied yet.

**Comment by seridwyn** [comment]
i posted the fist report roughly thee months ago

**Comment by tvshadowz** [comment]
Heya Seridwyn, sorry for the late response. Which set buffs are you talking about? The ones that have a chance to proc, the ones that the set grants or all of them? 

Thanks :)

**Comment by seridwyn** [comment]
specifically the form of the iron dwarves and the speed of the vrykul effects i was told these are supposed to proc in combat randomly however they only proc when you equip the set

**Comment by tvshadowz** [comment]
The item set should proc the Iron Dwarf morph + aim buff and the Vrykul morph + Speed buff during combat.

**Comment by fvicaria** [comment]
Won't fix this now. This needs client update.
