### ISSUE TITLE
[Item?] gas clouds in wintergrasp

### ISSUE THREAD

**Issue by havocisback** [WoWManiaUK/Redemption#1435]
there are gas clouds that spawn in the fire zone of wintergrasp that you can extract using the zapthrottle mote extractor there should be 4 that spawn at a time however there is only 1 that spawns at a time

**Comment by tvshadowz** [comment]
Thanks Havocisback for the report! If you could please follow these steps (http://www.wow-mania.com/forums/topic/71) about reporting a bug it would be very helpful for us.

For instance please include links to items mentioned, specific spawn points if known or any details or links about what should be happening in the future. 

Thanks again!

**Comment by havocisback** [comment]
zapthrottle mote extractor is http://www.wowhead.com/item=23821/zapthrottle-mote-extractor
gas cloud is http://www.wowhead.com/npc=32522/cinder-cloud
and the map of the spawn locations and respawn timers is here https://wotlk-twinhead.twinstar.cz/?npc=32522

**Comment by havocisback** [comment]
so all 5 spawn points should be spawning every 5 minutes

**Comment by tvshadowz** [comment]
Tested in dev and confirmed, 2 spawn points were observed but not the intended 5.

**Comment by fvicaria** [comment]
There are 5 but only 2 at a time are visible. As is.
