### ISSUE TITLE
[Quest] The Hunter and the Prince(icecrown)

### ISSUE THREAD

**Issue by xtremer98** [WoWManiaUK/Redemption#1437]
In this quest you play as Arthas to defeat Illidan the bug is that when you parry with your spell you dont recover 25% of your mana and you cant defeat Illidan, the second part of the bug is that sometimes there are 2 or 3 illidans at the same time not just 1.

**Comment by Critias14** [comment]
I can only work on half of the bug, please specify the spell you use and maybe the talents that effect it. The more information you give the sonner we can work on it :)

**Comment by tvshadowz** [comment]
Hi there Xtremer98!

If you could please follow this link (http://www.wow-mania.com/forums/topic/71) and add the necessary information for us testers that would be very helpful. 

For instance please include quest ids and npc ids if necessary. 

Thanks!

**Comment by tvshadowz** [comment]
Hi there Xtremer98!

Please follow the rules of how bugs should be reported here http://www.wow-mania.com/forums/topic/71. This helps us testers greatly and allows for fast and efficent fixes. 

For instance; please insert the area of the bug into the title within brackets, add any links of quests or items from wow-head and describe what should be happening and what is currently happening. 

Thanks for the report! We really appreciate your participation in making the server the best it can be :)
