### ISSUE TITLE
(Warlock)  [Fel Armor] - Don't increases spell power by equal to 30% of your Spirit. 

### ISSUE THREAD

**Issue by 20tebuscar** [WoWManiaUK/Redemption#1441]
Skill [Fel Armor] -  Increases spell power by 180 plus additional spell power equal to 30% of your Spirit. Also regenerate 2% of maximum health every 5 sec (http://www.wow-mania.com/armory/?spell=47893).

The  "additional spell power equal to 30% of your Spirit" it's not working.

I tested removing the set with spirit, also the all parts, and changed some gems to 20 spirit, but the spell power is the same with or without spirit in my "body".

**Comment by tvshadowz** [comment]
This is working as intended.

As seen in the image below 180 + (30% of 169 = 50) = 230

![test](https://user-images.githubusercontent.com/30256554/29037743-e2c4a2b4-7b9c-11e7-9666-ff33a7e4b308.png)
