### ISSUE TITLE
(Warlock ) [Improved Imp] - Talent is not working.

### ISSUE THREAD

**Issue by 20tebuscar** [WoWManiaUK/Redemption#1442]
[Improved Imp] - Increases the effect of your Imp's Firebolt, Fire Shield, and Blood Pact spells by 30%. (http://www.wow-mania.com/armory/?spell=18696).

[Blood Pact] - Increases party and raid members' health by 1330 (http://www.wow-mania.com/armory/?spell=47982).

With both working together, it's assumed the bonus of health it's like:

1330+30% = 1729

By the way, the buff still remains at 1330.

**Comment by tvshadowz** [comment]
This seems to be working correctly.

From the image below you can observe that as the talent points increase, so do the effects of blood pact. 

If you're having trouble with the buff please reset the buff and use it again. 

Thanks!

![test done](https://user-images.githubusercontent.com/30256554/28900940-ac9d9cd0-77ec-11e7-967a-ecf8a917494e.png)
