### ISSUE TITLE
 [Quest] Test Flight: Ruuan Weald 

### ISSUE THREAD

**Issue by iggapres** [WoWManiaUK/Redemption#1444]
http://www.wowhead.com/quest=10712/test-flight-ruuan-weald

Hi,

2 bug reports have been made on this quest already (#760, #766)  but I do not have the same problem.

After being launched and having activated the item, we land but far from the pool of Ruuan Weald (actual landing position if 57,39 instead of 61,39 approx).
Walking or flying to the end NPC (O'Mally Zapnabber) does not validate and the '?' is still silver. Unable to turn the quest in.

In the quest log, the use of the item is validated, but the flight itself is not.

**Comment by tvshadowz** [comment]
This has been confirmed in dev. In the image below you see in the quest log that the item has been used but the quest tracker says the opposite. In addition, the quest should land you in Ruuan Weald but lands you far away from it with the coordinates 57,40.

![wowscrnshot_080317_173022](https://user-images.githubusercontent.com/30256554/28932539-be017b42-7871-11e7-8968-db7f68b73f70.jpg)

**Comment by fvicaria** [comment]
![image](https://user-images.githubusercontent.com/9414661/29452034-d1d25d4e-83fc-11e7-9acc-3e32a05f622b.png)

Seems to me working on dev.

**Comment by captainloozer** [comment]
I just tested this and saw on the screen that I received credit for launching but in the quest log I did not.  I did receive credit for using the quest item while in the air.

![test](https://user-images.githubusercontent.com/9828794/29487804-ffa9579a-84c4-11e7-9317-042e31212f87.PNG)
![test2](https://user-images.githubusercontent.com/9828794/29487805-01609fda-84c5-11e7-8218-a867d2ecba9b.PNG)
