### ISSUE TITLE
(Quest) Valkyrion Must Burn

### ISSUE THREAD

**Issue by robersonv** [WoWManiaUK/Redemption#1445]
Hi, I found an issue in the quest http://www.wowhead.com/quest=12953/valkyrion-must-burn

After I get it I recieve the Incendiary Harpoons, but when I went to the Valkyrion Harpoon Gun, only 1 of the 4 that I found could be "used". Unfortunately, when I tried to use that one nothing happens.

**Comment by fvicaria** [comment]
Works

**Comment by dmtryzhkv** [comment]
it doesn't work. at this date. there are 4 harpoons and no matter how many times I restart quest none of them are mountable.

**Comment by fvicaria** [comment]
I tried all 4 cannons and they all work. This could be an issue with the script after people use it.
I will re-check

![image](https://user-images.githubusercontent.com/9414661/30814869-4f317336-a209-11e7-99b8-e737366aea2a.png)
