### ISSUE TITLE
Shaman Call of Water quest last part of the chain

### ISSUE THREAD

**Issue by s-scoltock** [WoWManiaUK/Redemption#1446]
Part of a chain

Quest description

Defeat the Corrupt Manifestation of Water and place the Corrupted Manifestation's Bracers along with the Remaining Drops of Purest Water on the Brazier of Everfount in Silverpine Forest.
items to find/deliver:
1x Corrupt Manifestation's Bracers
1x Remaining Drops of Purest Water
Along the coast of Silverpine, west of the Sepulcher, you will find a shrine that has become tainted by the plague. The spirits there no longer speak to our people and it will be up to you to defeat the manifestation and cleanse the pool.
Take the elemental's bracers, along with the remaining drops of Brine's potion, and place them on the brazier. The ritual should be enough to summon a pure spirit for you to communicate with.
Bring me proof the task is done, and I will reward you with your totem.

Problem

When I arrived at the area there were 8 Corrupted Manifestation's which I wasn't able to interact with.  When I took the septa (which should allow me to see a Corrupted Manifestation to fight) nothing happened.  A GM sorted me out (although I did end up with an extra quest for Call of the water)

**Comment by tvshadowz** [comment]
This is working as it should in retail. The corrupted manifestation to the left of the minor manifestation is the only one that should be targetable once the sapta is used. 

Take a look at this video of a retail server - https://www.youtube.com/watch?v=O54K1CHUP2o&t=513s

Thanks for the report!
