### ISSUE TITLE
[Quest] Rediscovering your Roots

### ISSUE THREAD

**Issue by tonguella** [WoWManiaUK/Redemption#1448]
After receiving a Razorthorn Flayer Gland, and using it on a Ravager, I get it as a pet, with the pet bar. But when I stand on  Razorthorn Dirt Mound and click the pet ability "Expose Razorthorn Root", the Ravager does not expose the root. The other pet commands, such as attack and follow, function correctly. But with this problem, it is not possible to complete the quest

**Comment by tvshadowz** [comment]
Hi there tonguella,

could you please follow this link http://www.wow-mania.com/forums/topic/71 and add additional information that we need to test/fix this issue. For instance, please include quest links and item links. 

Thanks!

**Comment by tonguella** [comment]
Sorry, here's more details: 
Quest Giver: Marnah -  http://www.wowhead.com/npc=24975/marnah  - in Isle of Quel'Danas, Shattered Sun Offensive
Quest: http://www.wowhead.com/quest=11521/rediscovering-your-roots
Area: Razorthorn Rise is just north of Veil Reskk, between Hellfire Peninsula and Shattarah. (53,13)
Mob not Working Correctly: Razorthorn Ravager - http://www.wowhead.com/npc=24922/razorthorn-ravager
Pet Ability that doesn't work: Expose Razorthorn Root
Item Not Received: Razorthorn Root - http://www.wowhead.com/item=34254/razorthorn-root
Date occurred: 3 August
Other players verify? Yes, 3 total - Cosette a Blood Elf Paladin, Tonguella a human Paladin, and Lucero a Night Elf Priest
Already Logged? Not as far as I can tell, a search came up empty

**Comment by tvshadowz** [comment]
The ability "expose razorthorn root" which is used to retrieve the razorthorn roots does not work near multiple razorthorn dirt mounds.

**Comment by captainloozer** [comment]
Confirmed fixed on dev

![root](https://user-images.githubusercontent.com/9828794/29497130-2fe1c134-85a8-11e7-8e7a-2c0fd1a1e276.PNG)
