### ISSUE TITLE
[Icecrown Citadel - Deathbringer Saurfang] Blood beast

### ISSUE THREAD

**Issue by Braytonx** [WoWManiaUK/Redemption#1453]
Warrior cleave 47520 is doing full dmg on the Blood beasts that are summoned by Deathbringer Saurfangs.
While these adds should have 95% reduced dmg taken from AoE spell : http://www.wowhead.com/spell=72723/resistant-skin

Warrior's being able to cleave them removes a big part of the encounter since the blood beasts die way to quick like this the dmg of the blood beasts are also to low but I can't find a proper link with the precise dmg they should be doing (they should 1 shot all casters and sometimes a plate wearing dps).

**Comment by Braytonx** [comment]
on 3:20 you can see a ranged dps being 1 shotted by a blood beast (marked with star) on 25 heroic on the PoV person's raid frame you can see a warlock going from 100% to 0% in 1 hit. A couple seconds later you can see another person being 1 shot this time marked with a triangle.

[https://www.youtube.com/watch?v=r8roJtPMguY](url)

**Comment by keidian** [comment]
I will fix it soon, as soon as Janitor is back

**Comment by keidian** [comment]
Not too sure wether Cleave is considered an Area of effect spell or not. Can you find a source that proofs warriors shouldn't be doing much cleave damage?

**Comment by keidian** [comment]
I think resistant Skin should only affect spells such as blizzard / rain of fire / hurricane. Also should the adds be taunt immune?

**Comment by Braytonx** [comment]
[https://www.youtube.com/watch?v=kKBUJj8FdiI&t=2s](url)

This is a feral druid PoV where you can clearly see he is not swiping the blood beasts on his recount you also see a warrior doing 14k ish DPS and since the cat is not cleave it's 95% sure the warr doesn't cleave either.

**Comment by Braytonx** [comment]
I just did DBS 25 HC blood beast was enraged and i had mark on me it only hit me for 2.7k.

http://imgur.com/a/fnuBO

**Comment by keidian** [comment]
Alright, We'll buff it so when the add is enraged on 25hc it'll oneshot casters.

**Comment by soundmeow** [comment]
Particularly it seems Blood Beasts [Resistant Skin](http://www.wowhead.com/spell=72723/resistant-skin) doesn't apply to targeted multi target AoE's.
Tested with a hunter - Multi-Shot deals full damage, whilst Volley functions properly. I'm going to assume that Swipe(Bear), Swipe(Cat), Seal of Command & Heart Strike are also not being reduced.

Beasts should be tauntable. Also the 300% increased damage buff on the beasts should have the potential to one shot anything but a tank - just thought i'd mention that.

Refference: http://wowwiki.wikia.com/wiki/Deathbringer_Saurfang
