### ISSUE TITLE
Supplies to Auberdine.

### ISSUE THREAD

**Issue by venusazalea** [WoWManiaUK/Redemption#1454]
Trying to do Supplies to Auberdine, but the guy won't move. I've talked to a GM who says it's working properly, but it isn't. I have accepted the quests and been sitting here for a few minutes. The guy never talks or moves. Hope it gets fixed. Thanks in advanced!

![wowscrnshot_080517_144238](https://user-images.githubusercontent.com/30756753/28997838-5f390414-79ec-11e7-803e-21edd8e7f062.jpg)

**Comment by tvshadowz** [comment]
Hey Venusazalea, in future could you please follow these steps on how to report a bug http://www.wow-mania.com/forums/topic/71 . 

With this report could you please link the quest id from wow-head as it helps us testers. Thanks :)

**Comment by tvshadowz** [comment]
Hi there Venusazalea!

Please follow the rules of how bugs should be reported here http://www.wow-mania.com/forums/topic/71 . This helps us testers greatly and allows for fast and efficient fixes. 

For instance; please insert the area of the bug into the title within brackets, add any links of quests or items from wow-head and describe what should be happening and what is currently happening. 

Thanks for the report! We really appreciate your participation in making the server the best it can be :)
