### ISSUE TITLE
[Quest] Help Tavara

### ISSUE THREAD

**Issue by kkittinger** [WoWManiaUK/Redemption#1455]
Accepted quest and found Tavara, tried healing with Bandages,  Gift of Naaru and Lesser Heal and quest does not complete. I have abandon the quest 3 times and still unable to complete.

Quest if given by Guvan at Azure Watch.

**Comment by tvshadowz** [comment]
Heya Kkittinger, could you please follow these steps about reporting a bug here http://www.wow-mania.com/forums/topic/71. 

With this report could you please link the quest id by linking the quest from wow-head. Thanks.

**Comment by kkittinger** [comment]
http://www.wowhead.com/quest=9586/help-tavara

What is supposed to happen: Heal Tavara
What actually happens: Nothing does not complete when using Bandages, Gift of Naaru or Less Heal.
Date you actually have see the problem August 5th, 2017
Did you ask someone (mod or player) to confirm? help ticket during Games and GM contacted me to for more information and based off discussions was told to open this ticket.

**Comment by kkittinger** [comment]
clicked on wrong button

**Comment by tvshadowz** [comment]
This is working as intended in dev. I used the gift of naru and completed the quest.
