### ISSUE TITLE
Lost - Signet Ring of the Bronze Dragonflight

### ISSUE THREAD

**Issue by Tallrasha** [WoWManiaUK/Redemption#1456]
Hello. I probably deleted by mistake this ring http://www.wow-mania.com/armory/?item=21197. I got it from Anachronos when i turned reputation with Brood of Nozdormu to friendly. Now I've turned reputation to honored and because I don't have the ring I cannot continue with the quest (changing the ring) to http://www.wow-mania.com/armory/?item=21198. Is there any chance to reget the ring so I can continue with this q please?

**Comment by tvshadowz** [comment]
Please contact a game master in game.

**Comment by Tallrasha** [comment]
I already did. He gave me the quest again, but without the ring i cannot complete it. Then he sent to this page..

**Comment by tvshadowz** [comment]
Do you remember which GM you spoke to?

Also the ring can be gained from three quests seen here http://www.wowhead.com/item=21205/signet-ring-of-the-bronze-dragonflight#reward-from-q so if all else fails you may have to do one of those to gain the ring back. 

This is not a bug or a server issue as you have either deleted or banked the item yourself, sorry.
