### ISSUE TITLE
[Enchant] Flexweave Underlay

### ISSUE THREAD

**Issue by Dsouth2** [WoWManiaUK/Redemption#1457]
When the engineer skill Flexweave Underlay is applied to  [Ice Striker's Cloak] the agility bonus does not apply.

**Comment by Forrestxz** [comment]
Confirmed.

**Comment by fvicaria** [comment]
With...
![image](https://user-images.githubusercontent.com/9414661/29454731-27472c1a-8406-11e7-9ae6-f0996d036767.png)
Without...
![image](https://user-images.githubusercontent.com/9414661/29454761-454321ec-8406-11e7-99d1-5d2183a852ae.png)
