### ISSUE TITLE
Quest Trial of the Sea Lion broken

### ISSUE THREAD

**Issue by kainus** [WoWManiaUK/Redemption#1458]
You can get the half of the pendant in the sludge fin in the Barrens but there is no chest or air vent at the location off the coast of Silverpine Forest. I went to the location supplied by Carbonite then backed up I was in the correct location by googling the quest and checking various databases and a video of the quest.

**Comment by Ergaro** [comment]
Did it (Horde) a couple of weeks ago. The chest is there, but it is hard to find (maybe it's not it the right place?). I remember there could be a problem with the vent though (it could be missing or not in the same place as chest, not sure).

BTW - should swimming into a vent restore Your breath? If yes, it's not working...
