### ISSUE TITLE
Dun Niffelum

### ISSUE THREAD

**Issue by Friskyswag** [WoWManiaUK/Redemption#1459]
There is a daily in Dun Niffelum that I just unlocked, I am currently friendly with the sons of hodir. There is a giant trumpet like cornucopia looking object that has a blue ! that I am unable to click on if I am on the ground or flying. Basically I am unable to accept this daily, I wish I knew the name of it because here I am trying to describe it lol. Anyways I want to get to exalted as fast as possible and while I know I can run dungeons for Triumph I would like to do the dailies as well. If you could fix this so I could accept this quest I would greatly appreciate it.

**Comment by Forrestxz** [comment]
Could you be more specific with the details before writing a report?

Try to name as many of the items/NPCs as you can.

**Comment by tvshadowz** [comment]
Hi there Babbadook!

Please follow the rules of how bugs should be reported here http://www.wow-mania.com/forums/topic/71 . This helps us testers greatly and allows for fast and efficient fixes. 

For instance; please insert the area of the bug into the title within brackets, add any links of quests or items from wow-head and describe what should be happening and what is currently happening. 

Thanks for the report! We really appreciate your participation in making the server the best it can be :)
