### ISSUE TITLE
[Quest] Collection of Goods

### ISSUE THREAD

**Issue by Adesik1988** [WoWManiaUK/Redemption#1460]
http://www.wowhead.com/quest=7642/collection-of-goods

Paladin must collect : Stratholme Holy Water x 5 http://www.wowhead.com/item=13180/stratholme-holy-water.

When going to Stratholme, crates where should be Stratholme Holy Water is sparkling but I cannot do with it any action. Help please

**Comment by tvshadowz** [comment]
This is confirmed, the highlighted boxes are unable to be interacted with. 

![wowscrnshot_080717_192050](https://user-images.githubusercontent.com/30256554/29040050-8fe35096-7ba5-11e7-9802-795c79c3d027.jpg)

**Comment by fvicaria** [comment]
![image](https://user-images.githubusercontent.com/9414661/29454847-a0384faa-8406-11e7-9dd3-896f0e3aa05e.png)
