### ISSUE TITLE
quest the master's touch  bugged

### ISSUE THREAD

**Issue by babbadook** [WoWManiaUK/Redemption#1461]
when you wanne go to black morass you need to do prequest . one of it is this one the master's touch . when you have to free thrall you need to killl the luitenant in order to do that you have to plant the exploisens in the barrles . but that's the thing when you do that the camps will not cach fire so means can't complete qst and npc in dungeon wount let you complete it . hope you know what i 'm trying to ssay ty for youre time reading and hope for a solution . or contact ingame .

**Comment by tvshadowz** [comment]
Hi there Babbadook!

Please follow the rules of how bugs should be reported here http://www.wow-mania.com/forums/topic/71 . This helps us testers greatly and allows for fast and efficient fixes. 

For instance; please insert the area of the bug into the title within brackets, add any links of quests or items from wow-head and describe what should be happening and what is currently happening. 

Thanks for the report! We really appreciate your participation in making the server the best it can be :)
