### ISSUE TITLE
Pet ALWAYS staying by your side

### ISSUE THREAD

**Issue by stealer0517** [WoWManiaUK/Redemption#1462]
In retail wow your pet would run to your left side when you'd move, but as long as you are in the same spot, or move within a certain distance your pet would stay in the same spot.
Here is how it should work: https://youtu.be/my6Olm7iXAs
Here is how it currently works: https://youtu.be/6vrtYNvVoMY

**Comment by tvshadowz** [comment]
Hi there Stealer0517, 

unfortunately this is not a bug that stops an individual from using something in the game. It is a visual bug and will be looked at but will not be of priority.
