### ISSUE TITLE
Pet focus always starting at 0 when summoned

### ISSUE THREAD

**Issue by stealer0517** [WoWManiaUK/Redemption#1464]
Whenever you dismount/use call pet the pet always spawns with 0 focus regardless of it's focus prior to being dismissed. 
How it should work: When you mount and your pet is at 50 focus points when you dismount it should be at 50 focus points
How it works currently: When you mount with your pet at 50 when you dismount it spawns at 0 and slowly regens
Bonus since this is kinda related: focus regen is way to slow, but I could make a separate bug for that.

**Comment by Forrestxz** [comment]
Confirmed, this is only triggered with certain mounts however.

**Comment by stealer0517** [comment]
Do you know which mounts aren't affected?
Also it happens when you manually dismiss and summon your pet manually.

**Comment by tvshadowz** [comment]
Hi there Stealer0517, 

unfortunately the topic that hunter pets don't start at the exact focus that they were dismissed at isn't necessarily a game stopping bug so wont be fixed. In addition, pet focus regen should be 5 per second which isn't fast as you say. 

Thanks for the report and helping the server be the best that it can be :)

**Comment by stealer0517** [comment]
This is very aggravating though, and makes my pet effectively useless since he never takes aggro away from the target until it's dead.

**Comment by tvshadowz** [comment]
Growl is a 15 focus costing ability of majority of pets which taunts the target. Spending 3 seconds in combat for your pet to taunt does not make your pet useless, sorry.

**Comment by stealer0517** [comment]
Growl doesn't take aggro at low levels since they do so little damage. 
It also makes charge useless since they never get the FP to do them.

**Comment by tvshadowz** [comment]
Sorry this is a minor issue that does not break mechanics of the game. You are able to work around this "issue" and does not make pets useless. 

This will not be changed.
