### ISSUE TITLE
[Talent] Retri Paladin. Divine Purpose

### ISSUE THREAD

**Issue by Wyrwinerka** [WoWManiaUK/Redemption#1465]
Divine Purpose gives Hand of Freedom effect to remove any stun from me or my friend. When im stuned i can't use it, when i should. When my friend have Hand of Freedom, he can be stuned, when he shouldnt be.

Can you try to fix it? :) Thank you!

This is link to simmilar issue! http://forum.warmane.com/showthread.php?t=317327

**Comment by Forrestxz** [comment]
False, hand of freedom does NOT make you immune to stuns while it is up.

First application of hand of freedom DURING a stun will remove all the stuns when applied but it does not make you IMMUNE to stuns while its up.

First part of the report is correct, must be tested.

**Comment by tvshadowz** [comment]
Hand of Freedom removes and grants immunity to movement impairing effects for 6 seconds. Whilst The Divine purpose talent is present HoF has a 100% chance to remove any stun effects on the target. 

HoF with Divine purpose is not meant to grant immunity from stuns, just remove them. 

This is working as intended.

Thanks for the report :)
