### ISSUE TITLE
[Quest] Time for Answers, Icecrown

### ISSUE THREAD

**Issue by Taneral** [WoWManiaUK/Redemption#1466]
Quest: Time for Answers

NPC: Matthias Lehner

Location: The Court of Bones, Icecrown

Issue: Unable to locate NPC. Map pinpoints him at the crossroads in the Court of Bones, but NPC is not there. I have looked for NPC while phased in the Argent Tournament quests and while not phased.

**Comment by fvicaria** [comment]
There are various versions of the NPC for each quest. Please specify the exact quest and the ones you successfully completed as they are a chain.

Please follow the procedure described below before creating a new issue:
[How to Properly Report an Issue](https://github.com/wow-mania/Redemption/wiki/How-to-Properly-Report-an-Issue)

This will help developers identify and fix the issue quicker. Incorrectly or unclear reports will simply be deleted.

**Comment by tvshadowz** [comment]
Heya Taneral, 

in future please follow the steps posted by Fvicaria when reporting a bug otherwise the issue report will be met with the same response and closed.

Thanks!

**Comment by tvshadowz** [comment]
Hey Taneral, 

unfortunately we require information on pre quests and additional informational information for this bug report. Until then this bug will be closed. 

Thanks!
