### ISSUE TITLE
[Raid] BT Mother Shahraz

### ISSUE THREAD

**Issue by CrustyMuffin** [WoWManiaUK/Redemption#1467]
Her "Demonic Energy" ability isn´t working properly.
http://wowwiki.wikia.com/wiki/Mother_Shahraz
Instead of doing the 3k damage per second, she does 10-30k damage per second.

**Comment by tvshadowz** [comment]
Hi there CrustyMuffin, 

Unfortuneatly I could not find any spell named "Demonic Energy" used by Mother Shahraz. However I did go ahead and test the combat anyway and didn't find any overtuned spell. 

The only spell I could believe you are linking to is "Vile Beam" which from the screenshot below is only doing 2.5k damage. 

You may be confusing the damage from sabre slash. 

Thanks for the report!

**Comment by tvshadowz** [comment]
![wowscrnshot_081617_171825](https://user-images.githubusercontent.com/30256554/29373693-ed4a4ee4-82a6-11e7-9886-55f74526f6a2.jpg)

Here's the screenshot, sorry

**Comment by CrustyMuffin** [comment]
She only uses that ability if 4 or mor player´s are in the group. I have i give you the wow-wiki about all her abilities. During the fight she teleport 3 player´s to the same place and give them the debuff. She will not use it if you solo it.

**Comment by tvshadowz** [comment]
Hi CrustyMuffin! 

I do apologise as I did only test it with two people. I'll be retesting this issue asap with 5 people. 

Thanks for the additional information!

**Comment by tvshadowz** [comment]
After testing this with 5 characters I did experience being teleported but did not experience a debuff called "Demonic energy". 

If you could screenshot this issue in the future and post it here I would extremely grateful but for now I can't seem to reproduce this issue. 

Thanks for the report.
