### ISSUE TITLE
[Dungeon] Oculus ; emerald drake

### ISSUE THREAD

**Issue by CrustyMuffin** [WoWManiaUK/Redemption#1468]
The abilities "Dream Funnel" and "Leeching Poison" can´t be used after a time, even the Boss or the player´s are targeted or in range, during the fight with Ley-Guardian Eregos.
http://www.wowhead.com/npc=27692/emerald-drake#abilities

**Comment by CrustyMuffin** [comment]
We found the problem. If someone in a ruby drake uses the ability "Evasive Maneuvers", he will make himself and the boss dodge all spells.

**Comment by Forrestxz** [comment]
That's how it works on most servers as well, this includes Friendly spells not being able to be used during Evasive Maneuvers.

Can you find any sources yourself regarding this being a bug 100% or not?

**Comment by tvshadowz** [comment]
Hi CrustyMuffin! 

I believe BatuMania is correct in saying that it is a part of the phase that the boss is immune from spells. I think you may have to kill the adds spawned by the boss to then kill him. 

Thanks for the report!
