### ISSUE TITLE
[Quest] The chain gun and you

### ISSUE THREAD

**Issue by justnc1992** [WoWManiaUK/Redemption#1470]
The quest "the chain gun and you" in Dragonblight is bugged. 
When you click on the chain gun a hotbar should appear, you get a 5min buff but nothing else happens.

**Comment by fvicaria** [comment]
works. also please search before posting new issues.

**Comment by justnc1992** [comment]
doesn't work, i've been trying for a week now

**Comment by fvicaria** [comment]
I will re-check when I have a chance but check all the pre-reqs. Use our armory NOT wowhead.com or any other source.

**Comment by justnc1992** [comment]
okay, but i did all the pre-reqs.

**Comment by tvshadowz** [comment]
Hi there Justnc1992!

Please follow this link http://www.wow-mania.com/forums/topic/71 on how to appropriately report a bug. Please place the issue in brakets in the title of your issue, as well as linking items, quests and spells from our armoury here http://www.wow-mania.com/armory/ .

This helps us greatly when it comes to testing and fixing issues with the server. 

Thanks again for the report and your participation in making the server the best that it can be. :)

**Comment by tvshadowz** [comment]
Please provide the appropriate links, details etc and I will test this asap.

**Comment by tvshadowz** [comment]
Hi there Justnc1992!
As you can see from the screenshot below taken on the dev server today the quest is working as intended. Sorry for your experience, please make sure your game client is up to date and you have done other routine checks. 

![wowscrnshot_081617_131125](https://user-images.githubusercontent.com/30256554/29362595-94c08d1e-8284-11e7-8eb3-a73132caf9ac.jpg)

Thanks for the report!

**Comment by ManiaLightmare** [comment]
Not sure how the dev got it working, but I have the same issue as the original report.  You get the "buff" as though you are in the chain gun, but you aren't and no soldiers run.  
I use the launcher and I'm up-to-date.  Tried relogging which did not help.  Had same issue with another character.  Required GM assistance
