### ISSUE TITLE
[Pet] Fel Hunter

### ISSUE THREAD

**Issue by Necrosiss** [WoWManiaUK/Redemption#1472]
Felhunter and his Spellock skill. Sending you again to link about passive stance. Whenever you use Spellock(manualy clicking the spell or hotkey, auto-cast off), on a player or mobs on a passive stance pet should use the skill (ofcouse if in range) and still FOLLOW you no matter what, but he doesnt. Fel after you use a skill start to go to the target. Below link to a skill, as u can read there it put you to a mele combat but its normal thing. You used something on player/mob so it makes be in combat. It doesnt say AT ALL ANYWHERE that pet will start to attack. Again passive stance, pets should do w/e Warlocks tell them.

wowwiki.wikia.com/wiki/Passive

http://www.wow-mania.com/armory/?spell=19647
http://wowwiki.wikia.com/wiki/Spell_Lock  <-- 2nd source, read about "Note". Says it put caster to mele combat, nowhere is written same on wow mania armory, pet will go to target and mele attack him.

**Comment by Braytonx** [comment]
If a pet is on passive and you command it to do any spell on a non-friendly target it will start combat with that person you would have to recall it after the spell.

**Comment by Necrosiss** [comment]
Exaclly as you said, it will start a combat with that person. That doesn't mean at all, pet should start mele attack the target. Am i wrong?

**Comment by Braytonx** [comment]
they would after you told your pet to cast a spell on them.

**Comment by Braytonx** [comment]
the devour magic one doesn't let it attack if i remember it correctly sicne it isn't an offensive spell

**Comment by Necrosiss** [comment]
Well i can be wrong. Anyway worth check.

**Comment by tvshadowz** [comment]
This was tested on the Redemption server with a Warlock player known as "Femdot" and was found to be bugged. This will be observed again on the test realm and further action will be decided upon. 

Thanks for the report!

**Comment by tvshadowz** [comment]
Update 21:14

Fix unsuccessful in dev
