### ISSUE TITLE
[Skill] Death coil

### ISSUE THREAD

**Issue by Necrosiss** [WoWManiaUK/Redemption#1473]
About this skill in Warlock class, as you can read below in the link it clearly stay that skill should heal you x300% dmg done by that skill. Unfortunatly i know there was post about that skill heals double on warlocks and yes it still happen. But instead to fix problem of double healing the skill got reduce to almost nothing to heal. Simply math 790 x 300% = 2370, this number are just taken from the skill description. Now add spell power modify resilliance and other stuff but usualy more or less that skill hit the target around 1000+. From what i tested when i deal 1000+ damage i get heal less than 1000 its not even 100% of the heal i shoul get. When you add to that Warlock Demon Armor http://www.wow-mania.com/armory/?spell=47889 then you will get around 1k heal. This skill suppose to heal almost the same amount of heal to Warlock as Healtstone http://www.wow-mania.com/armory/?item=36892 .

http://www.wow-mania.com/armory/?spell=47860

**Comment by kyo1950** [comment]
I can confirm this since ive tested death coils heals on a dummy

**Comment by Forrestxz** [comment]
Confirmed, tested on Red.

**Comment by captainloozer** [comment]
I was able to reproduce this issue.  Even though, strangely, I was healed twice when getting a critical strike against the enemy, neither heal nor both combined equaled the 300% amount of damage that was done.  

![deathcoil crit](https://user-images.githubusercontent.com/9828794/29421822-ddc5d52a-833b-11e7-8141-8286f880512f.png)

**Comment by captainloozer** [comment]
After testing again, even though I did not get a critical strike, death coil once again healed me twice, but the combined total does not equal 300% of damage done.

![deathcoilnoncrit](https://user-images.githubusercontent.com/9828794/29421932-33b4013c-833c-11e7-8cbc-fc68913799bd.PNG)

**Comment by captainloozer** [comment]
From testing done today, my findings are as follows:

When death coil does damage to the target, it heals twice for exactly the amount of damage done, in other words 200%.  So the healing is up from 100%, but still does not do the entire 300% healing described in the tooltip.

![image](https://user-images.githubusercontent.com/9828794/29686532-ec9fa3b6-88de-11e7-86d7-d6729cc4b009.png)
