### ISSUE TITLE
The Storm Kings Vengeance quest in Zul Drak

### ISSUE THREAD

**Issue by Supermac7176** [WoWManiaUK/Redemption#1476]
I could not complete this because when controlling the giant called Gymer, i would grab hold of a scourge from the ground then throw it down onto other scourge killing any nearby ones but my kill quote would not increase and the second part of the quest involved killing 3 other bosses in the area but their health never went down to them being killed and so i could go no further and was forced to ask a GM for assistance.

**Comment by tvshadowz** [comment]
Hi there Supermac7176!

Please follow this link http://www.wow-mania.com/forums/topic/71 on how to appropriately report a bug. Please place the issue in brakets in the title of your issue, as well as linking items, quests and spells from our armoury here http://www.wow-mania.com/armory/ .

This helps us greatly when it comes to testing and fixing issues with the server. 

Thanks again for the report and your participation in making the server the best that it can be. :)
