### ISSUE TITLE
[Talent] Retribution Paladin. Divine Purpose. BUGed Talent.

### ISSUE THREAD

**Issue by Wyrwinerka** [WoWManiaUK/Redemption#1477]
Hi, i have problem with Divine Purpose Talent. Talent gives me an opurtnitty to get out of any stun effect by using Hand of Freedom. When im using it, when im stuned (Cheap Shot or so) it shows me that i can't use it while im stuned. Plus it should make me immune for stuns, but it not doing it. Can you fix this problem?

LINK:
http://forum.warmane.com/showthread.php?t=317327

Gromoslaw

**Comment by tvshadowz** [comment]
Hand of Freedom removes and grants immunity to movement impairing effects for 6 seconds. Whilst The Divine purpose talent is present HoF has a 100% chance to remove any stun effects on the target.

HoF with Divine purpose is not meant to grant immunity from stuns, just remove them.

This is working as intended.

Thanks for the report :)
