### ISSUE TITLE
Fel Armor and LightweaveEmbroidery bug

### ISSUE THREAD

**Issue by Igotpooedon** [WoWManiaUK/Redemption#1478]
Hello, 

There IS a bug that has not yet been fixed and that is  when you have Fel Armor as warlock 
http://www.wow-mania.com/armory/?spell=47893
and you also have Lightweave embroidery enchant on your back
http://www.wow-mania.com/armory/?spell=55642

That Lightweave Embroidery procs from the health-tick you get from Fel armor.

This makes this back enchant pretty bad for warlocks since i can proc when you're not in combat.

//Anton

I've also talked with Gm Saintz and she said that i should report it here since it's not supposed to do like this.

**Comment by Braytonx** [comment]
I can confirm this is happening.

@Igotpooedon  I've been canceling the buff and reapplying it 3 sec before the fight to make sure I still have the buff so you can atleast use it properly for now.

**Comment by fvicaria** [comment]
Use workaround mentioned.

**Comment by Braytonx** [comment]
The workaround would only work before the encounter the bug stops you from getting the full potential of the enchants.

For example on PP you get targeted by the green ooze and as a warlock should do you port it to maximize travel distance this will result in the ooze taking about 10+ sec if done properly in these 10 seconds the enchants can proc by your fel armor and you practicly lose the enchant value for 1 and a half minute in fight. 
I really hope you will reconsider fixing this bug cuz it is not just this enchant that can proc from it as @forrestxyz mentioned. It can make a warlock lose about 2k dps in total if you have multiple procs and some bad RNG.

**Comment by fvicaria** [comment]
I will take a look at it tomorrow.

**Comment by Braytonx** [comment]
and?
