### ISSUE TITLE
[NPC] The Behemouth is missing 

### ISSUE THREAD

**Issue by TheGreyMouser** [WoWManiaUK/Redemption#1479]
http://www.wowhead.com/npc=8924/the-behemoth  is missing from outside blackrock depths.

**Comment by tvshadowz** [comment]
Thank you for this report! I'll look at this issue asap :)

**Comment by tvshadowz** [comment]
As of 11.13pm GMT on RED he hasn't spawned. I will have someone check the database to see whether he does spawn. 

I believe because of population differences that the spawn time will be increased as compared to blizzlike realms. 

Thanks!
