### ISSUE TITLE
[Quest] An Apexis Relic

### ISSUE THREAD

**Issue by Calebrimbor** [WoWManiaUK/Redemption#148]
http://www.wow-mania.com/armory/?quest=11058

First you'll have to gather a Apexis Shard(http://www.wow-mania.com/armory/?item=32569) from  various mobs near the quest giver. Once obtained you'll need to locate an Apexis Monument(http://wow.zamimg.com/uploads/screenshots/normal/260213-an-apexis-relic.jpg) and stand on the platform underneath one of the four crystals surrounding the Monument. Then click on the crystal to activate an event.

Nothing happens when clicking the crystal.

**Comment by wow-mania** [comment]
Can this be retested please.
