### ISSUE TITLE
Lupus Pupus

### ISSUE THREAD

**Issue by Supermac7176** [WoWManiaUK/Redemption#1481]
The quest called " Lupus Pupus " in Borean Tundra is bugged and cannot be completed because you have to throw some drugged meat at oil stained Wolves in order for them to eject a piece of micro film in their droppings to be collected and returned with other micro film to the quest giver but when you target and throw the meat to the Wolves, nothing happens, they just carry on walking about so you can never retrieve the micro film.

**Comment by tvshadowz** [comment]
Hi there Supermac7176! 

Please follow this link http://www.wow-mania.com/forums/topic/71 on how to appropriately report a bug. Please place the issue in brakets in the title of your issue, as well as linking items, quests and spells from our armoury here http://www.wow-mania.com/armory/ . For instance one fix on this post is "[Quest] Lupus Pupus". 

This helps us greatly when it comes to testing and fixing issues with the server. 

Thanks again for the report and your participation in making the server the best that it can be. :)
