### ISSUE TITLE
Jagged Shards

### ISSUE THREAD

**Issue by Supermac7176** [WoWManiaUK/Redemption#1483]
The quest called Jagged Shards in Icecrown has a bug where you are tasked to retrieve 10 pieces of jagged shards from the corpses of ghouls in the Fleshwerks and take them to Crusader Olakin on top of the Blackwatch where he stands next to Darkrider Arly, a gnome Death Knight on a horse but even though i have gathered the 10 shards needed, Crusader Olakin is not standing at the Blackwatch with Arly, she is the only one there.

**Comment by tvshadowz** [comment]
Hi there Supermac7176!

Please follow this link http://www.wow-mania.com/forums/topic/71 on how to appropriately report a bug. Please place the issue in brakets in the title of your issue, as well as linking items, quests and spells from our armoury here http://www.wow-mania.com/armory/ .

This helps us greatly when it comes to testing and fixing issues with the server. 

Thanks again for the report and your participation in making the server the best that it can be. :)
