### ISSUE TITLE
Finish me !

### ISSUE THREAD

**Issue by Supermac7176** [WoWManiaUK/Redemption#1484]
I have completed the quest called " Finish me ! " in Icecrown where a dying soldier asks you to kill 5 of his dying friends and report to High Captain Justin bartlett aboard the Skybreaker gunship, however once i finished this task and reported in, Bartlett is not sat in his captains chair on the gunship and i cannot hand in the quest.

**Comment by tvshadowz** [comment]
Hi there Supermac7176!

Please follow this link http://www.wow-mania.com/forums/topic/71 on how to appropriately report a bug. Please place the issue in brakets in the title of your issue, as well as linking items, quests and spells from our armoury here http://www.wow-mania.com/armory/ .

This helps us greatly when it comes to testing and fixing issues with the server. 

Thanks again for the report and your participation in making the server the best that it can be. :)
