### ISSUE TITLE
(NPC) Darkmaster Gandling

### ISSUE THREAD

**Issue by Tallrasha** [WoWManiaUK/Redemption#1485]
Darkmaster Gandling in Scholomance does not drop Helm of Valor http://www.wow-mania.com/armory/?item=16731. I have been there over 50 times now. He drop every possible item and other helmets about 5 times each but never Helm of Valor. I need it to finish long chain of quests. I contacted GM in game and he sent me here. Can you please look at it?

**Comment by tvshadowz** [comment]
Hi there Tallrasha!

Please follow this link http://www.wow-mania.com/forums/topic/71 on how to appropriately report a bug. Please place the issue in brakets in the title of your issue, as well as linking items, quests and spells from our armoury here http://www.wow-mania.com/armory/ .

This helps us greatly when it comes to testing and fixing issues with the server. 

For this report the only thing I could ask for is the quest that you need the helm for, then this report would have all we need :D

Thanks again for the report and your participation in making the server the best that it can be. :)

**Comment by Tallrasha** [comment]
I need it for this q http://www.wow-mania.com/armory/?quest=9013.

**Comment by Tallrasha** [comment]
I finally got Helm of Valor. So it seems Darkmaster Gandling does drop it after all. I was probably just very unlucky. Sorry for bother, I'm closing this issue..
