### ISSUE TITLE
[Quest] Brutal Armor

### ISSUE THREAD

**Issue by ChinookUT** [WoWManiaUK/Redemption#1486]
http://www.wow-mania.com/armory/?quest=1838

After collecting all four ingredients, the quest when tracked was marked as completed, but the quest giver [Thun'grim Firegaze](http://www.wow-mania.com/armory/?npc=5878) did not change from a white question mark to a gold question mark, therefore it couldn't be turned in.  I was able to turn it in with the assistance of a GM.

**Comment by Tallrasha** [comment]
It happens sometimes. All I do is abandon the quest and take it again. then it works...

**Comment by ChinookUT** [comment]
This is the first occasion I've encountered along these lines in about 40 levels of questing, so I'm not sure.  My first worry is, and I'm not sure of the answer offhand, "On the WoW Mania server, when you abandon a quest, does it destroy the related quest items"?  A quest like that is an awful lot to redo for just a possibility that it will work the second time around.

In any event, I realize an obscure class quest is definitely not a priority, especially when a GM can be used for a workaround.  I just wanted to post the relevant details and let the rest of you make the decision of whether or not to do anything with it.

Have a great day.  :)

**Comment by tvshadowz** [comment]
Heya ChinookUT,

I just tested this report on the Redemption server and saw it is working fine. Here's a screenshot of it working: 

![test](https://user-images.githubusercontent.com/30256554/29341073-27eaf3ce-821a-11e7-9459-2297ebf393e8.png)

If you are having issues with turning in quests etc please make sure you have our game client and relevant patches installed along with troubleshooting your issue by dropping the quest and picking it backup as Tallrasha suggests or reloading your cache. 

Thanks for your report! 
![test](https://user-images.githubusercontent.com/30256554/29341073-27eaf3ce-821a-11e7-9459-2297ebf393e8.png)

**Comment by ChinookUT** [comment]
Thanks for looking at it mate.  Not a client, patch or cache issue, I assure you.  If it happens again I'll try retaking the quest.
