### ISSUE TITLE
Skinning Dredge Striker (worms) in Silithus loot issue

### ISSUE THREAD

**Issue by TheGreyMouser** [WoWManiaUK/Redemption#1488]
Worm mobs in Silithus are dropping light leather when skinned.  These mobs are level 50 and higher, and should be dropping thick and rugged leather when skinned.

**Comment by Forrestxz** [comment]
Could you post a screenshot of this happening?

If so, yes level 50 mobs and higher should be giving Rugged and Thick Leather.

**Comment by tvshadowz** [comment]
A screenshot is nt necessary as I will be testing this.
