### ISSUE TITLE
[Quest] [77] Securing the Bait

### ISSUE THREAD

**Issue by AtlasRedux** [WoWManiaUK/Redemption#1489]
Sometimes trying to pick up the hatchlings just causes them to disappear without being actually picked up, sometimes one single hatchling can be picked up multiple times, sometimes not at all. It's weird.

Quest : http://www.wow-mania.com/armory/?quest=12605
Primordial Hatchling mob and item bugged : http://www.wow-mania.com/armory/?item=38600

**Comment by tvshadowz** [comment]
Hi there AtlasRedux! 

Please follow this link http://www.wow-mania.com/forums/topic/71 on how to appropriately report a bug. Please place the issue in brakets in the title of your issue, as well as linking items, quests and spells from our armoury here http://www.wow-mania.com/armory/. 

This post is almost perfect, could you please make sure you link us to the quest and item in question.

This helps us greatly when it comes to testing and fixing issues with the server. 

Thanks again for the report and your participation in making the server the best that it can be. :)

**Comment by AtlasRedux** [comment]
Issue update with additional info.

**Comment by tvshadowz** [comment]
Hi there AtlasRedux!

This has been confirmed on the dev server. 

Thanks for the report!
