### ISSUE TITLE
[quest] Lord Illidan Stormrage

### ISSUE THREAD

**Issue by iggapres** [WoWManiaUK/Redemption#1491]
This is the quest : http://www.wowhead.com/quest=11108/lord-illidan-stormrage
It's the quest you get when reaching Exalted reputation with Netherwing Faction. Giver by [Overlord Mor'ghor](http://www.wowhead.com/npc=23139/overlord-morghor)

During this quest Illidan comes to see the new "hero" (you) but discovers you're a deceiver.
Illidan stuns you, asks the Overlord to kill you, and leaves.
Then, a blue dragon (Yarzill the Merc) appears and asks you to climb on its back.

At this point, you jump on the dragon's back, and here comes the bug: the dragon disappears and the game is stuck.
It seems to be server side (ouch!). I've done it twice and had the same behaviour twice (it was around 10:15 AM and 10:40 AM, 2017/08/16).
I don't want to try it once more, I don't like the idea of crashing server...

**Comment by tvshadowz** [comment]
Hi there Iggapres! 

When this was tested in dev the outcome you describe was not reproduced. You may need to delete your cache or make sure your game client is up to date. 

However unfortunately for now we can only apologise that you experienced this issue. 

Thank you for the report!

**Comment by iggapres** [comment]
Hi,
Thank you for the answer.
Deleting the cache solved the problem (I still don't understand why).
Sorry for the fuzz.

**Comment by tvshadowz** [comment]
Hi there Iggapres!

That's completely fine! We really appreciate your participation in making the server the best it can be. And afterall, it's better to test something that is working rather than not testing something that's broken ;D

Thanks for the report!
