### ISSUE TITLE
[Pet] Voidwalker + [Spell] Consume Shadows

### ISSUE THREAD

**Issue by tvshadowz** [WoWManiaUK/Redemption#1493]
This issue was submitted in report [1471](https://github.com/WoWManiaUK/Redemption/issues/1471) however was closed due to explanation issues. 

http://www.wow-mania.com/armory/?spell=697 - Summon Voidwalker
http://www.wow-mania.com/armory/?spell=47988 - Consume Shadows

This is the issue at the moment:

1. If the Warlock has the pet on "follow", is running and Consume Shadows is cast, the pet was continously attempt to cast Consume Shadows losing mana but unsuccessfully casting the spell. 

What should happen: When the warlock is running with the pet on "follow", the pet should stop and channel the spell. 

**The following issue happens to all pets with a castable ability.** 

2. If the Warlock has the pet on "stay" and Consume Shadows is cast, the pet will run off in a different direction into a wall leading to its death. 

What should happen: Whilst the pet is on "stay", the Voidwalker should channel the spell in the space is was told to stay. 

This issue was found by @necrosiss with help of @metaxa and @gmsaintz.

**Comment by BatuMania** [comment]
You aren't allowed to confirm your own posts as Janitor stated.

**Comment by BatuMania** [comment]
Pretty sure Janitor said you can't confirm your own posts.

**Comment by tvshadowz** [comment]
Hi there Forrestxyz! 

If you check out post 1471 as linked in the report, this bug was not only observed by me but two other Game Masters at different points! Since this is irrelevant to the post and does not contribute any additional information I'll be removing these two comments in a couple of hours. 

Thanks! :)

**Comment by captainloozer** [comment]
After some recent changes were done by Janitor, I have tested the consume shadows spell while having the voidwalker on follow and while on stay.  Both produced the intended results of the pet staying put and casting the spell properly. Confirmed working on dev.

**Comment by captainloozer** [comment]
Update:  It seems that everything is working properly except having the voidwalker on STAY.  As long as the voidwalker has enough mana to channel the spell, he will stay as intended.  If the void walker does not have enough mana to cast the spell, and is on STAY, he will run away in the direction he is facing until he despawns due to exceeded maximum distance from the warlock.

**Comment by fvicaria** [comment]
As is.
