### ISSUE TITLE
[Quest] The Conquest Pit: Death Is Likely

### ISSUE THREAD

**Issue by MihailoVasovic** [WoWManiaUK/Redemption#1494]
The issue is when i kill Horgreen Hellcleave i dont recieve quest completion.
I tried to kill him 4 times, and same thing happened every time.

**Comment by tvshadowz** [comment]
Hi there MihailoVasovic!

In future could you please link any quests or npcs via our armory to help us testers and prevent your issue being closed due to insufficient information. 

Thanks for the report!

**Comment by captainloozer** [comment]
I was not able to reproduce this issue.  Upon killing Horgreen Hellcleave, I instantly received credit and was able to turn the quest in.

![12430completed](https://user-images.githubusercontent.com/9828794/29416464-c4ce237a-832b-11e7-9e0b-5fa45ea59e93.PNG)

**Comment by tvshadowz** [comment]
This was tested whilst I was there.
