### ISSUE TITLE
I have a problem regarding a quest.

### ISSUE THREAD

**Issue by Pitypalaty** [WoWManiaUK/Redemption#1496]
I wrote a ticket already, and got closed too, we found a solution, but i need the help of a GM in-game to solve it fully, please contact me (this was the instruction from a dev). My characters name is Pitypalaty

Thanks in advance!

**Comment by fvicaria** [comment]
Please follow the procedure described below before creating a new issue:
[How to Properly Report an Issue](https://github.com/wow-mania/Redemption/wiki/How-to-Properly-Report-an-Issue)

This will help developers identify and fix the issue quicker. Incorrectly or unclear reports will simply be deleted.

**Comment by tvshadowz** [comment]
Hey Pitypalaty! 

As fvicaria has said, follow the  link and check how bug reports should be made to help us testers out. 

For example:
Title - "[quest,spell etc.] Name of quest,spell etc"

Description - Make sure you link items and quests used in the report from either the WoW-Mania armory or WoW-Head. 

Thank you for your participation in making the server the best it can be! :)
