### ISSUE TITLE
"Taretha's diversion" quest

### ISSUE THREAD

**Issue by Pitypalaty** [WoWManiaUK/Redemption#1498]
Quest link: http://www.wowhead.com/quest=10283/tarethas-diversion

First of all, it's a personal issue, only on one of my characters (Pitypalaty is the characters name as well)

I wanted to do Master of Elixirs quest, which directed me to a Keeper of Time quest, called Taretha's Diversion. When i got the quest and entered, did everything i needed to do (planted bombs, escorted Thrall) but i couldn't turn in the quest at Erozion in the end in the village. I can see the exclamation mark above his head, but that's all, i can't turn in the quest tho, there is not even a ch I asked a GM on WoW-Mania Discord channel, and he told me to try to drop and redo the quest, which didn't help at all.
After i opened a ticket, one of you guys told me to ask a GM to remove the quest from me, and after a restart, i will be able to take the quest again, and do it without any problem, hopefully.
So i want to ask one of you, or any GM to contact me in-game and remove the quest from me, so i'll be able to take it again and complete it so i can move on to Black Morass, and will be able to complete my Master of Elixirs quest.

Character name: Pitypalaty (contact Pilly if you can't reach the other one)

Thank you in advance!

**Comment by Pitypalaty** [comment]
How will i know if someone removed the quest from me btw? Since you closed it the issue without reply :)

**Comment by fvicaria** [comment]
Create a ticket. When your ticket is answered ask them to do ".quest remove 10283" on you.

**Comment by tvshadowz** [comment]
Aha I see your issue! Here on GitHub we deal with bug reports and issues rather than helping out individual issues. 

To contact a GM in game please open a ticket and a GM will contact you directly.
