### ISSUE TITLE
[Quest] Blood Infusion

### ISSUE THREAD

**Issue by CrustyMuffin** [WoWManiaUK/Redemption#1499]
During both fights, in 10 and 25 man, the ability "Blood Mirror" didn´t give me the "Gushing Wound" debuff that is needed to complete the quest. I had my Shadow´s Edge equipped during the whole encounter.
http://de.wowhead.com/shadowmourne-guide#shadowmourne-blood-infusion

**Comment by CrustyMuffin** [comment]
i forgot the mention that the bossfight is Bloodqueen in the icecrown citadel

**Comment by fvicaria** [comment]
Works. Check with other players that got it successfully.
