### ISSUE TITLE
[Quest] Taking Back Acherus

### ISSUE THREAD

**Issue by Blindsay2003** [WoWManiaUK/Redemption#1500]
after gating back to ebon hold, the quest stop working, could not speak to highlord Darion Morgaine, Gamemaster Morbius attempted to help me with the issue however after him forcing the reward I could no longer continue the quest line which should have gone on to The battle for ebon hold, I'm not sure where the quest broke but I am relatively sure the gate did not put me into the instance it was supposed to, instead it just put me back into ebon hold pre battle of light hope or whatever it is, the quest right before this one, The Light of Dawn

**Comment by Blindsay2003** [comment]
It did not put me into ebon hold pre quest, it put me into ebon hold post instance, it looks like its a problem the spell gate, I should have been put directly into Battle for ebon hold instance instead of ebon hold proper

**Comment by tvshadowz** [comment]
Hi there Blindsay2003! 

Please take a look at [How to properly report a bug] (https://github.com/WoWManiaUK/Redemption/wiki/How-to-Properly-Report-an-Issue). We need bug reports to have links to quests, items and clearly show what is happening and what should be happening. 

Thanks for the report!

**Comment by Blindsay2003** [comment]
So in other words your not fixing it and i have to restart the dk and hope
the quest works properly this time

**Comment by fvicaria** [comment]
It works!

**Comment by fvicaria** [comment]
1000 dks did the quest fine and for some reason, yours is "broken" because of the quest.
If he completed the quest for you why are you still whining?
You don't have to start a new char. 
But yes you are right we do nothing here...

**Comment by Blindsay2003** [comment]
I'm "whining" because forcing a reward on part of a quest dose not fix the
quest when you never got into the instance you are supposed to be in in the
first place and now my DK's starting quest line is unfinishable but like I
said before yall don't give a fuck so what dose it matter, in fact why dose
reporting a bug matter at all if this is how you all respond to them.

**Comment by fvicaria** [comment]
You are right I should not be talking to you at all.
You are the only one being disrespectful here.
I WAS willing to go take a look until you start swearing and being disrespectful, now feel free to do whatever.

**Comment by Blindsay2003** [comment]
if that was the case you would not have started with, closing the ticket
and "It works!" and then proceeding belittle someone. So go back to
whatever porn you were watching so you can finish masterbatting into your
mothers underwere.

**Comment by fvicaria** [comment]
:) Bye!

**Comment by Blindsay2003** [comment]
have fun with your incest porn.

**Comment by Blindsay2003** [comment]
Oh yes by all mean delete all of that so people don't see what a douche you are, oh wait they already know, but seriously I should thank you seeing as you have brought me to a realization, playing on this server is a pointless waste of time and really should not be done by anyone. so Thank you for showing what a bad owner looks like.
