### ISSUE TITLE
[Quest] Sons of Hodir

### ISSUE THREAD

**Issue by roxysocks** [WoWManiaUK/Redemption#1501]
While doing the quest chains for the Sons of Hodir I got to the quest "In Memoriam" and it would no longer let me talk the NPCs (Njormeld, King Jokkum, Lillehoff). It gave me the sword icon and would only let me attack them even though I am friendly in reputation. A GM tried to help me, but we weren't able to get the sword icon to disappear. They ended up turning the quests in for me, but now I am not able to get the new ones because it will only let me attack. This started happening today, Aug. 17, 2017. 
Also the daily "Hot and Cold" does not give the quest item "Essence of Ice" http://www.wowhead.com/item=42246

http://www.wowhead.com/faction=1119/the-sons-of-hodir#quests

**Comment by philoudu16** [comment]
go in the rep tab -> sons of hodir -> untick 'at war'

**Comment by tvshadowz** [comment]
Hi there Roxysocks! 

As Philoudu16 has said, please make sure your reputation with the faction you converse with doesn't have "at war" checked. When I  get a chance, I'll check this after you can confirm that this is not the issue. 

Thanks for the report! :)

**Comment by roxysocks** [comment]
Okay, that ended up working. Thank you so much!
