### ISSUE TITLE
[Spell] Retribution aura and Moonkin aura don't stack

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#1503]
Retribution aura (https://wotlk.evowow.com/?spell=10299) and Moonkin aura (https://wotlk.evowow.com/?spell=24907) are intended to stack (as they're entirely different boosts and given by two different classes).

Issue: currently i cannot stack them in my party, whenever the moonkin is shapeshifted, the paladin's aura turns off and cannot be reactivated, Moonkin aura entirely overwrites Retribution.

Note: I suspect it could have something to do with the moonkin having Improved Moonkin form (https://wotlk.evowow.com/?spell=48396) talented, (may be needed to take this talent to reproduce bug)
Because it gives the same 3% haste buff as the retribution talent Swift Retribution (https://wotlk.evowow.com/?spell=53648). Oddly the paladin in group is Holy and does NOT have that haste talent and the auras still don't stack. (even if he did, the auras are supposed to stack, only the 3% haste effects aren't)

**Comment by captainloozer** [comment]
Hello Dranah, and thank you for your report!

I have tested this issue on dev and can confirm the following:  

As a Holy paladin (or any paladin that does not have Swift Retribution (53648) talented, while in a group with a moonkin, you will not be able to activate Retribution Aura.  If the paladin has retribution aura already active, it will remain active until toggled off or to another aura.  Afterwards, going back to Retribution Aura is not possible.

However, after testing with a Retribution paladin with the Swift Retribution talented with all 3 points, giving the entire 3% haste buff, the aura becomes possible to activate again alongside Moonkin Aura (24907), while the haste benefits do not stack, as intended.

**Comment by captainloozer** [comment]
Janitor just made some changes on the dev server and I was able to test again and confirm that this is now working as intended.  As a paladin without the Swift Retribution talent in any way, I was able to swap back and forth between Retribution Aura and other auras and receive the buffs as expected while being under the influence of the Moonkin Aura.

**Comment by forrestxyz** [comment]
This is wrong, they shouldnt be stacking. 

http://www.warcrafthuntersunion.com/2009/05/list-of-what-raid-buffs-stack-and-do-not-stack/

**Comment by forrestxyz** [comment]
Swift Retribution and Moonkin aura are NOT meant to stack.

http://www.warcrafthuntersunion.com/2009/05/list-of-what-raid-buffs-stack-and-do-not-stack/
