### ISSUE TITLE
Hunter pet

### ISSUE THREAD

**Issue by Ptipaco** [WoWManiaUK/Redemption#1505]
im with my hunter seondary spec as a Marksmanship  i use a wind Serpent and it not allow me to put talent point in it

**Comment by tvshadowz** [comment]
Hi there Pitpaco!

Could you please follow this link on how to properly report a bug https://github.com/WoWManiaUK/Redemption/wiki/How-to-Properly-Report-an-Issue . 

This helps us test bugs and deploy fixes to the public quicker and easier. 

Thanks for the report!
