### ISSUE TITLE
[NPC] Pusillin - Dire maul east

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#1506]
Pusillin (http://www.wowhead.com/npc=14354)
The way it's intended to work is that each time you speak to him, he yells something silly and runs forward to the end of road you're on, and once you reach him after clearing the way, you speak to him again and he moves forward again... a total of 5 times until he reaches his destination.

Issue: Pusillin resets to his starting position after each running session before you'd have a chance to reach him, and you have to keep walking back to the entrance to talk to him again. Also worth mentioning that his pathing is chaotic, flying through the air towards the other side of the platform and such.

**Comment by fvicaria** [comment]
Works as is. Just keep him in sight.
