### ISSUE TITLE
[Quest]WANTED: Murkdeep

### ISSUE THREAD

**Issue by gasccpedro** [WoWManiaUK/Redemption#1509]
http://www.wow-mania.com/armory/?quest=4740

I accepted this quest and went to the location on the map. There I slayed the Murkdeep ( http://www.wow-mania.com/armory/?npc=10323 ) as requested and the quest was not completed... I've since returned multiple times to the location and slayed the existing monsters, he never showed up again...
I have also abandoned and retaken the quest and nothing changed...

**Comment by GmSaintz** [comment]
I can verify that the creature Murkdeep - id10323 is not there. There are 0 spawned when I check, even after a restart.

**Comment by tvshadowz** [comment]
Hi there Gasccpedro! 

Please make sure when doing the quest that the existing mobs at the camp are killed allowing for murkdeep to spawn. I will test this in the morning.

**Comment by GmSaintz** [comment]
After further testing, I can confirm that "Murkdeep" does spawn after killing all surrounding mobs in that area. 

Kill the warrriors, and a group of 3 mobs will spawn on the shore. Kill those, and 2 more will come for you to fight. Then Murkdeep will spawn to complete the quest.
