### ISSUE TITLE
The Hunter and the Prince

### ISSUE THREAD

**Issue by Supermac7176** [WoWManiaUK/Redemption#1511]
The Hunter and the Prince quest in Icecrown has a bug where once you start the quest, you take the place of Arthas Menethil and have to face off against Illidan Stormrage, you have a 4 button interface to use, the 1st button parry's attacks by Illidan and when a parry is successful, returns 25% mana back to Arthas to continue fighting, the 2nd button does 20000 damage to Illidan, the 3rd button kicks Illidan and knocks him back and the 4th button does a leaping attack which causes 400,000 damage to Illidan.

The problem is that when you use the 1st button to parry attacks to regain mana, Arthas does nothing at all and cannot parry any attacks from Illidan and therefore cannot regain any mana to fight and defeat Illidan and so the quest cannot be completed.

**Comment by tvshadowz** [comment]
Hi there Supermac7176!

Please follow this link on how to properly report an issue:

https://github.com/WoWManiaUK/Redemption/wiki/How-to-Properly-Report-an-Issue
