### ISSUE TITLE
[QUEST]The First and the Last

### ISSUE THREAD

**Issue by s-scoltock** [WoWManiaUK/Redemption#1512]
After handing in the previous quest to King Varian Wrynn he gives a quest to go and find Master Mathias Shaw.

When I try and interact with him I can't

**Comment by tvshadowz** [comment]
Hi there Scoltock!

Could you link the quest please,

Thanks!

**Comment by captainloozer** [comment]
Hi S-scoltock,

Unfortunately I was not able to reproduce this issue.  Try logging out and back in and see if that fixes your problem.  If you can include any more information about the problem, feel free to post again.

![image](https://user-images.githubusercontent.com/9828794/29497218-cf42e900-85a9-11e7-8db6-f0dbee9bddd8.png)
