### ISSUE TITLE
[Dungeon] Dire Maul

### ISSUE THREAD

**Issue by Kiyomi1793** [WoWManiaUK/Redemption#1515]
The "Whip Lashers" cause A LOT of damage and it's impossible to heal through it. This whole dungeon is impossible to complete because of this issue. I've noticed this on 2 different toons during multiple dungeon queues... http://www.wowhead.com/npc=13022/whip-lasher

**Comment by tvshadowz** [comment]
Hi there Kiyomi! 

The damage that is caused by the npcs is dependent on level and gear. It is possible to do this dungeon the whip-lasher group should be pulled on their own rather than with an additional group. 

Thanks!
