### ISSUE TITLE
[Dungeon] Azjol-Nerub

### ISSUE THREAD

**Issue by Kiyomi1793** [WoWManiaUK/Redemption#1516]
So there are 2 big problems with this dungeon:

1. Hadronox (http://www.wowhead.com/npc=28921/hadronox). Sometimes he doesn't even climb up the ramp (like he's supposed to do when you kill the large Anub'ar Crushers). 

Other times, he DOES climb up.. but the little mobs that spawn to attack him (like they do when he is below in the tunnels) keep spawning constantly. Because of this we can't use any AoEs because they will also attack our tank and wipe out the whole party. 

Also, more than half the time, his life keeps regenerating which makes him impossible to kill.

2. Anub'Arak (http://www.wowhead.com/npc=29120/anubarak). Fighting him usually goes very well. It's when the whole team wipes out and tries to kill him again that it bugs. He remains STUCK under ground. We can target him, but he isn't visible. He never surfaces, so we can't kill him. It makes completing the dungeon impossible.

**Comment by fvicaria** [comment]
Can we test this in dev please. There were some changes in the core that may have solved this.

**Comment by tvshadowz** [comment]
Hi there! Here's what I found:

The mobs prior to Hadronox will sometimes all despawn (including the boss) and then randomly all respawn again. 

I could not find the issue with Anub'Arak being stuck in the ground after dying to him.

Thanks for the report!

**Comment by tvshadowz** [comment]
This was tested on live and no issues were found. 

Thanks for the report!

**Comment by ManiaLightmare** [comment]
Did this dungeon on 16SEP2017 and both issues occurred. 

1. Hadronox never climbed the web after killing the bugs at the top.  When attempting to kill him anyway, he'll almost always despawn.

2. Anub'Arak went underground with only a rogue left.  Other bugs despawned. Combat ended. Rogue used jumper cables on my druid.  As soon as I rez'd, an "invisible" Anub'Arak cast pound and killed me.
