### ISSUE TITLE
[NPC Spell] Devour Humanoid - Fleshreapers in ICC

### ISSUE THREAD

**Issue by captainloozer** [WoWManiaUK/Redemption#1517]
Vengeful Fleshreapers in ICC have a spell called Devour Humanoid which stuns the target for roughly 6 seconds (NPC can be stunned to interrupt it).  Devour humanoid should not be cast unless the target was first hit by leaping face maul, as can be seen on the armory, the spell is triggered by the leap.

http://www.wow-mania.com/armory/?npc=37038
http://www.wow-mania.com/armory/?spell=71163
http://www.wow-mania.com/armory/?spell=71164

There is supposed to be a minimum range the fleshreaper has to be away from the target in order for them to cast leaping facemaul (5-30 yards according to the armory).  What prevented this from happening was that the raid was supposed to stack up so that all the fleshreapers were in melee range and this would stop them from jumping to people and using devour humanoid.

At the time of testing https://github.com/WoWManiaUK/Redemption/issues/1508 on dev, the leap and devour was working properly. 

Additionally, per issue https://github.com/WoWManiaUK/Redemption/issues/1508, the fleshreaper pathing was also fixed on dev, at the time of testing, but they're now not coming down from the pipe again.  They will aggro the players and will cast devour humanoid at ranged, but stay on the pipes instead of jumping down.  Intended behavior is when either attacked or a player steps on one of the two invisible traps, they triggered to leap to the target and cast devour humanoid.

**Comment by tvshadowz** [comment]
![testtt](https://user-images.githubusercontent.com/30256554/29625437-9631a6b6-8823-11e7-9390-6ab9a2addb50.png)

**Comment by captainloozer** [comment]
Tested yesterday, fleshreapers aren't casting either spell, leap or devour, anymore.  Fleshreapers on the pipes don't patrol at all, and will not jump down from the pipe.

**Comment by captainloozer** [comment]
Tested today, Leaping Face Maul was only casted once when far enough range away from me to cast it.  Devour humanoid was immediately casted aftwards, then neither were casted again as long as I stayed in melee range. 

![image](https://user-images.githubusercontent.com/9828794/29687597-90d2a62e-88e2-11e7-908d-74eac984e6d6.png)
