### ISSUE TITLE
[Quest] It's All Fun and Games (Horde)

### ISSUE THREAD

**Issue by JoyfulPangolin** [WoWManiaUK/Redemption#1518]
The Ocular was not present when I attempted to do this quest and did not spawn.  Also, the Knights of the Ebon Blade NPCs are present at the Shadow Vault below and should be phased out until completing "If He Cannot Be Turned".

**Comment by tvshadowz** [comment]
Hi there JoyfulPangolion! 

Please use this link on how to properly make a report to help us testers and devs out.

https://github.com/WoWManiaUK/Redemption/wiki/How-to-Properly-Report-an-Issue

Thanks for the report!
