### ISSUE TITLE
[Quest]The Deadliest Trap Ever Laid

### ISSUE THREAD

**Issue by grigtsiouv** [WoWManiaUK/Redemption#1519]
So the quest http://www.wowhead.com/quest=11101/the-deadliest-trap-ever-laid  (Aldor side) is bugged. I take the quest from Commander Arcus http://www.wowhead.com/npc=23452/commander-arcus , i fight the Dragonmaw Forces, and Commander Arcus even yells "Victory... etc". However, the quest isnt marked as complete, so i cant turn it in.

Also, the NPCs i was supposed to kill didnt attack me by their own, i had to attack them with my gun for them to engage.

**Comment by tvshadowz** [comment]
Hi there Grigtsiouv!

I believe the quest is bugged because of the fact that the npcs dont attack you or the guards at the start of the phase. 

Thanks for the report!
