### ISSUE TITLE
[Dungeon] The Culling of Stratholme

### ISSUE THREAD

**Issue by tvshadowz** [WoWManiaUK/Redemption#1521]
Dungeon: http://www.wowhead.com/the-culling-of-stratholme

When you speak to Arthas at the start after accepting and completing the quest at the start then he does nothing and the phase does not start.

**Comment by fvicaria** [comment]
You need to have the quest from Chromie.

**Comment by tvshadowz** [comment]
Yeah that's the quest you get after the completing the quest prior.

**Comment by fvicaria** [comment]
Please retest with the quest from Chromie active in your logbook. The person talking to Arthas need to have it.
