### ISSUE TITLE
AV/BG Bug?

### ISSUE THREAD

**Issue by hevmak** [WoWManiaUK/Redemption#1522]
BUG?**  I was in Alterac Valley and I died in combat. I was then sent in spirit form to IBGY. During my Resurrection time the Graveyard was contested by the other team. Seeing this I went to my body to resurrect after the time was up. It wouldn't let me after a moment of attempting I went to another Graveyard. There was no spirit guide. I tried every GY and even tried reloading UI I went back to IBGY when we controlled it again and there was a guide. The second I rezzed it kicked me and gave me deserter. I wouldn't be THAT frustrated with it, if we weren't winning.

**Comment by fvicaria** [comment]
I will check the spirit guide locations.
