### ISSUE TITLE
[NPC] Bodley

### ISSUE THREAD

**Issue by Tallrasha** [WoWManiaUK/Redemption#1524]
Bodley http://www.wow-mania.com/armory/?npc=16033 is missing. He is suppose to stand on the balcony in front of Blackrock Spire entrance. He is not there for more than two days now. 
I need to return him this q http://www.wow-mania.com/armory/?quest=8967. 
He went missing by the time you were fixing this quest few days ago..thank you

**Comment by fvicaria** [comment]
![image](https://user-images.githubusercontent.com/9414661/29659459-435b6d8a-88b6-11e7-9546-00e9f50b6cb7.png)
