### ISSUE TITLE
[Quest] Flight of the Wintergarde Defender

### ISSUE THREAD

**Issue by NightSeekerr** [WoWManiaUK/Redemption#1528]
The quest requires you to save 10 villagers, while flying on a gryphon. Problem is the villagers don't spawn properly (they spawn and disappear immediately). 

Link for the quest: http://www.wow-mania.com/armory/?quest=12237

Link for the questgiver: http://www.wow-mania.com/armory/?npc=27317

How to reproduce the problem: Accept the quest, use the http://www.wow-mania.com/armory/?item=37287 to summon the gryphon. Jump on it and try to rescue the helpless villagers in the Carrion Fields.

P.S. I am using the client and the latest Launcher.

**Comment by fvicaria** [comment]
Works. Please check requirements and any missing previous quest that may have left you in a bad phase. If necessary open an in-game ticket.
This has been explained in previously raised issues.
