### ISSUE TITLE
[Quest] The Deadliest Trap Ever Laid

### ISSUE THREAD

**Issue by cathyr1** [WoWManiaUK/Redemption#1530]
Hello! This quest is bugged - when killing all the dragonmaws NPC yells they are defeated but quest is not completed.

![quest](https://user-images.githubusercontent.com/30184491/29748825-41a5d06a-8b1e-11e7-8791-450db63ba677.png)

**Comment by fvicaria** [comment]
Were you doing that in a group?

**Comment by cathyr1** [comment]
I did it alone, it is for 70 and I´m 80. Many of the quests that are for group are doable solo. I did plenty of them in the past.

**Comment by fvicaria** [comment]
Yes, that is not what I was looking for. Sometimes members of the group do not get the quest completed. Did the NPC not offer the completion or was it gray?

**Comment by cathyr1** [comment]
Questionmark was grey when I reached the NPC to that I have to return it.

**Comment by tvshadowz** [comment]
The Dragonmaw NPCs that are suppose to attack do not automatically attack. Without the attacking phase commander arcus just says "victory" and walks back to his original position without completing the quest.

**Comment by fvicaria** [comment]
Both sides fixed now.

**Comment by tvshadowz** [comment]
Aldor side- 

The dragonmaw  npcs have 1 or 2 spawns that are too late. And Commander Arcus doesn't walk back in place so you can't turn in the quest.

**Comment by fvicaria** [comment]
I've just done it again and all works correctly. I have changed a bit the timer on the spawns.

![image](https://user-images.githubusercontent.com/9414661/29764851-b8135c7e-8bd0-11e7-8881-a76cf24e3189.png)

**Comment by cathyr1** [comment]
Thank you much for working on this. Can you just please let me know when I can do the quest to be sure it is working? I´m Aldor side. Thanks.

**Comment by fvicaria** [comment]
We should push it tomorrow or Wednesday at the latest.
Would you be interested in joining our testing team? We reward players that do :P

**Comment by cathyr1** [comment]
Thanks for your offer. If you are Janitor, I will contact you later on Skype where we can discuss it. I´ll have many questions about that :)

**Comment by cathyr1** [comment]
Unfortunately the quest is still not working when tried today, about 10 mins ago.
The riders are moving now and attacking NPCs, but Commander Arcus returns to his position before fight ends and when he yells the quest is not completed.

**Comment by fvicaria** [comment]
I have checked a few times and it was working. You need to help him and stay close. I will try again when I have a sec.
