### ISSUE TITLE
[Ulduar] The Siege - Demolisher

### ISSUE THREAD

**Issue by neoandre** [WoWManiaUK/Redemption#1531]
Only the driver gets proper interface in the demolisher.
The turret does not work, thus making the demolisher unusuble and Hard mode impossible to do.
- The passenger should have the following abilities:
[**Mortar**]—Fires a miniature explosive blast, dealing Fire damage to all enemies in the target area. An imprecise hit can do as little as 5,000 damage, while a direct hit will do upwards of 120,000 damage. Does approximately 2,300 siege damage to buildings. (1 sec cooldown)
[**Anti-Air Rocket**] —Fires an explosive missile that explodes on contact with air targets. (0.25 sec cooldown)
[**Grab Crate**] —Use your hook and chain to grab the targeted crate. Grab the targeted crate to pick up Liquid Pyrite off the ground, which reloads the demolisher by 25 Pyrite
[_Increased Speed_] (25 pyrite)—Injects liquid pyrite into the engines, increasing movement speed by 100%. Lasts 20 sec.
[**Load into Catapult**]—Load yourself into the catapult arm, using yourself as ammunition. (30 sec cooldown)
- When entering the turret from the driver's seat You get out of the vehicle

**Comment by fvicaria** [comment]
Please follow the procedure described below before creating a new issue:
[How to Properly Report an Issue](https://github.com/wow-mania/Redemption/wiki/How-to-Properly-Report-an-Issue)

This will help developers identify and fix the issue quicker. Incorrectly or unclear reports will simply be deleted.

**Comment by fvicaria** [comment]
http://www.wowhead.com/npc=33167/salvaged-demolisher-mechanic-seat

**Comment by forrestxyz** [comment]
Hardmode can be zerged down with the Limited pyrite you have since Pyrite collecting is also bugged.

**Comment by captainloozer** [comment]
I did Ulduar on Red yesterday, I also experienced this.  You can at least leave the demolisher if you so choose, even though there aren't any vehicle UI buttons present.

If you get inside a siege engine as a passenger however, you don't even have a way to leave it aside from logging out.

**Comment by fvicaria** [comment]
Please re-test in dev I have made some modification on the core that may solve it.

**Comment by captainloozer** [comment]
In the siege engine, as a passenger, I don't have any new action bars and no way to exit the vehicle without logging out.  The red arrow icon that usually exists to hop out is not present and it doesn't show that there is a passenger in the mini vehicle icon on the right side so the driver can not eject the passenger either.

![image](https://user-images.githubusercontent.com/9828794/30241138-1c1c2c16-9543-11e7-8994-bf73410fd0a4.png)

However, as the driver, I am able to click the passenger's seat in the mini vehicle icon, even if someone is already in it, and I can get the new action bar that way, as the driver.  The passenger is still bugged

![image](https://user-images.githubusercontent.com/9828794/30241156-6013951c-9543-11e7-961e-65478f3e395d.png)

As a passenger in the demolisher, I am able to get in and out of the vehicle just fine, but no extra actions are available, specifically the one that loads me into the catapult.  It visually shows me in it already, however, the driver doesn't have the option to shoot the passenger.

Driver:

![image](https://user-images.githubusercontent.com/9828794/30241177-aff334e8-9543-11e7-9f9c-4e451daf9c4b.png)


Passenger:
![image](https://user-images.githubusercontent.com/9828794/30241180-bb1aa9f0-9543-11e7-83b0-d435e031a73c.png)

**Comment by fvicaria** [comment]
Can this be re-tested in dev please.
