### ISSUE TITLE
[Quest] 5 repeatable quests in Blasted Lands

### ISSUE THREAD

**Issue by cathyr1** [WoWManiaUK/Redemption#1532]
Hello! There are bugged quests in Blasted Lands. In screenshot you see their names. Even when collected all necessary items and quests are marked as "completed", the questionmarks are grey so the quests cannot be returned to these NPCs. I tried delete Cache but did not help.
![1](https://user-images.githubusercontent.com/30184491/29750883-0f1fd4c2-8b48-11e7-90d5-1cbbabf9cf03.png)
![2](https://user-images.githubusercontent.com/30184491/29750889-287c6282-8b48-11e7-9769-897a8397cf06.png)

**Comment by fvicaria** [comment]
Please search before posting. This has been covered before. Do one quest at a time. You can collect items for all at once but only take one at a time.

**Comment by cathyr1** [comment]
Thanks for your information. Just what time please? 1 per day?

**Comment by fvicaria** [comment]
No, you can do all of them one after the other. Just pick one at a time. This is an issue with the tracking of items you have.
