### ISSUE TITLE
[Quest] Someone Else's Hard Work Pays Off

### ISSUE THREAD

**Issue by cathyr1** [WoWManiaUK/Redemption#1534]
Hello! There is a bugged escort quest inside Mana Tombs - link http://www.wow-mania.com/armory/?quest=10218.

We just did this and noone has it completed. I personally stayed close to NPC when it finished. He just dissapeared after we killed boss but quest is not completed.

**Comment by fvicaria** [comment]
The issue was that the NPC was a little too weak, not distance. If he dies the quest fails.
I made it a little stronger.

![image](https://user-images.githubusercontent.com/9414661/29767320-e7890504-8bd9-11e7-9af7-2cb8dd06e227.png)

**Comment by cathyr1** [comment]
He hasn´t died, he survived the entire escort. Then told the same as on your image and dissapeared but quest was not completed.
