### ISSUE TITLE
[Quest] What the Cold Wind Brings...

### ISSUE THREAD

**Issue by cathyr1** [WoWManiaUK/Redemption#1536]
There should be a regular event in front of Warsong Hold when NPCs are facing waves of the undead. As a last one in these waves comes the boss http://www.wow-mania.com/armory/?npc=25453 and when defeated he drops off his carapace. When looted, it provides an item begins a quest http://www.wow-mania.com/armory/?item=34777.

However this event doesn´t happen here so it is impossible to complete this quest atm.

**Comment by fvicaria** [comment]
What doesn't happen? Where is the point where it doesn't work?

**Comment by fvicaria** [comment]
I have added the object at the location shown in the image. It will have a respawn time of 30min. Same as the event. This is a work around for now.

![image](https://user-images.githubusercontent.com/9414661/29768453-2eb6a31a-8bde-11e7-87ed-bb35f72fa244.png)
