### ISSUE TITLE
Lolzbringer is glithcing Once More :) 

### ISSUE THREAD

**Issue by Wyrwinerka** [WoWManiaUK/Redemption#1537]
Hey, Its Me Ozy/fechtmistrz.
I was Report Lolzbringer for many Times, Here are the Proves :) 
![wowscrnshot_082817_200326](https://user-images.githubusercontent.com/30754890/29786780-c746ce72-8c2c-11e7-87ed-eb3cd81d7522.jpg)
![wowscrnshot_082817_200334](https://user-images.githubusercontent.com/30754890/29786778-c744b376-8c2c-11e7-914f-fa83741e7aa9.jpg)
![wowscrnshot_082817_200337](https://user-images.githubusercontent.com/30754890/29786779-c745cab8-8c2c-11e7-9b5d-d1a5954c64d1.jpg)

**Comment by tvshadowz** [comment]
Please report this to a Game Master in game. This area is for bug reports.

**Comment by Wyrwinerka** [comment]
Em, i wasn't creating any posts for Lolzbringer, cuz always im talking with
Metaxa and guys. :/

2017-08-28 20:11 GMT+02:00 Shadowz <notifications@github.com>:
