### ISSUE TITLE
Skinning Loot Table of Core Hounds (Molten core)

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#1539]
Core Hounds in Molten Core (http://www.wowhead.com/npc=11671) have incorrect skinning loot tables.

These lvl 61 elite mobs currently drop Ruined Leather Scraps (http://www.wowhead.com/item=2934) or Light Leather (http://www.wowhead.com/item=2318) when skinned. 
Those are level 5 skinning loot, and these are lvl 61 elites, which should drop a load of valuable level 60 leathers i.eg. Rugged leather (http://www.wowhead.com/item=8170) and rugged hide (http://www.wowhead.com/item=8171) instead.

**Comment by captainloozer** [comment]
Hi Dranah, and thank you for your report.

You are correct in that Ancient Core Hounds should not drop Ruined Leather Scraps from skinning.  However, I believe they should have 100% drop chance on Core Leather (http://www.wow-mania.com/armory/?item=17012) instead of Rugged leather or Hides.  I will test this and confirm.

**Comment by captainloozer** [comment]
I was not able to reproduce this issue on Dev.   Ancient Core Hounds correctly dropped core leather when skinned.

![image](https://user-images.githubusercontent.com/9828794/29795862-b1f9c146-8c13-11e7-8481-07140f8827b6.png)

If you are able to provide more information on how to reproduce this issue please feel free to submit another ticket.  As always, Dranah, thank you for your report!

**Comment by Dranah** [comment]
I was talking about Core Hounds though, not Ancient Core hounds.... the wowhead ID I linked belongs to that type of mob as well. Ancient ones do drop their core leathers properly.

**Comment by captainloozer** [comment]
You're right, I misunderstood.  I'll check those in that area soon.  For now I'm reopening this.
