### ISSUE TITLE
Magisters terrace instance

### ISSUE THREAD

**Issue by Igotpooedon** [WoWManiaUK/Redemption#1540]
Hi, there is currently a bug at this instance.
The [NPC] Wretched Skulker / Bruiser do abnormous amount of damage they can do up to 30k damage and they come in packs so they pretty much one shot you.

the [NPC] Wretched Skulker / Bruiser  are located in the same room as the first boss.

**Comment by captainloozer** [comment]
Hello Igotpooedon, and thank you for your report.

It certainly sounds like the name is relevant here with what you're explaining.  However, I'd like to have more information before I try to test this.

What difficulty of the instance were you attempting?  Normal or Heroic?
What were you using to determine how much damage was done to you?  Combat logs?  Addons?  Do you have screenshots of this happening?

**Comment by captainloozer** [comment]
Below is a video of my encounter with these mobs on normal mode.  As show, they hit normally for lvl 70 elites.  

https://youtu.be/QcnVsSf06FM

**Comment by captainloozer** [comment]
Below is my ecounter on Heroic mode.  As you can see, they hit much harder on heroic, but no where near 30k damage, or "one shot".  I died in the video because I pulled them all, obviously.  This is working as intended on dev, cannot reproduce.

https://youtu.be/PemqK74blCE

**Comment by Igotpooedon** [comment]
I beg to disagree I just tried myself just now and here are some pics.
 this is not working as intended.
http://imgur.com/a/OsKdU
http://imgur.com/a/4CJhe

**Comment by Dranah** [comment]
@Igotpooedon 
These mobs drink a green potion that greatly increases their damage output while it's active, thus their enormous hits are a mechanism, not a bug.
They're intended to be kited through that.

**Comment by philoudu16** [comment]
Exactly what Dranah said.
When they have low hp, they drink a potion that multiplies their damage by 20.
I thought it was bugged too when trying to run that dungeon, so did some research and yeah it's not a bug.
Only two options are kiting, or bursting them down fast enough so they dont have the time to hit you once they get the buff.

**Comment by tvshadowz** [comment]
Hi all!

Just to clear things up, here is the spell called "Drink Fel infusion" which is what causes the dramatic spell increase. 

http://www.wowhead.com/spell=44505/drink-fel-infusion

Thanks for everyone contributions! :)
