### ISSUE TITLE
[QUEST] Unexpected Results

### ISSUE THREAD

**Issue by Katherwind** [WoWManiaUK/Redemption#1541]
As requested by GM Mobius tonight, I am submitting a report detailing issues I had with the following quest tonight:

http://www.wowhead.com/quest=8488/unexpected-results

The quest is given by Apprentice Mirveda in Eversong Woods.  The objective of the quest is to protect  the npc from a scourge ambush.  

What is supposed to happen:  3 mobs spawn including ( http://www.wowhead.com/npc=15958/gharsul-the-remorseless) .  Killing Gharsul is supposed to trigger quest completion.

What actually happened: 
(1) All three mobs continued to spawn after they were killed in an endless loop until they overwhelmed the npc and she died and the quest was marked as failed.
(2) I abandoned the quest, retook the quest and started it again.  Again the mobs continued to respawn after they were killed.  I got overwhelmed with too many mobs and died. Again, quest was marked as failed. I resurrected and ran back to the quest area and Gharsul was still attacking Mirveda.  I killed Gharsul.  The kill did not update the quest since it was already marked as failed.
(3) I abandoned the quest for the second time but this time Mirveda would not offer me the quest. Logging off and on did not resolve the issue. I submitted a ticket and the GM was able to help me complete the quest by killing and respawning Apprentice Mirveda several times:  once to get her to offer me the quest again and another after mobs were killed to get her to show the question mark for quest completion.  

I believe others may be having similar issues with the quest because I saw several people hanging around the area at different times.

**Comment by fvicaria** [comment]
Worked totally fine.
![image](https://user-images.githubusercontent.com/9414661/29826451-3b9747fa-8ccf-11e7-8fc3-a0c14e96f65d.png)
