### ISSUE TITLE
[Storm Peaks] Problems with zone phasing - Brunnhildar Village

### ISSUE THREAD

**Issue by Xantoni** [WoWManiaUK/Redemption#1543]
I was doing the quest chain of the Brunnhildar to get some reputation with the Sons of Hodir after this, and i encounter a problem while doing You'll need a bear (ID: 12972). As soon as I enter the zone named Valley of the Ancient Winters and I leave the Brunnhildar Village i phase out, then the NPC to who you have to give the quest, and the provider of the next one, disappears. I've tried to come from other zones to see if this solves that.

By the way, I would like to add that in some videos i found out that the NPC appears when you get to the Valley of the Ancient Winters, and not before this happens. I leave a video in which you will be able to see this: https://www.youtube.com/watch?v=XVvzXIc9mNw (it's another WoW version but i found other videos that happens the same in WotLK, but this one had the better quality).

Hope you fix this and thanks for your help!

Saintz will confirm this since he was helping me last night.

EDIT: NPC name - Brijana

**Comment by fvicaria** [comment]
THis is due to missing or not completing a particular quest in the chain. Please raise a ticket and ask a GM to correct your phase or complete the quest for you.

**Comment by Xantoni** [comment]
I already asked to a GM and he said to report the bug here. Sorry for not commenting it.

**Comment by fvicaria** [comment]
Yes, that is the correct procedure, the GM is instructed to no complete unless there is a confirmed issue but in this case, the issue is elsewhere. Sorry for the confusion.
