### ISSUE TITLE
[Item] Skull of Man'ari

### ISSUE THREAD

**Issue by liam5413** [WoWManiaUK/Redemption#1544]
The item - Skull of Man'ari - which is purchased from the artifact weapon vender in the mall is not equipable and not able to be transmoged to a weapon or off-hand. Would be nice if this could get fixed so i didn't waste 2 transmog token :) thank you.

**Comment by tvshadowz** [comment]
Hi Liam!

I'll check this asap. Could you tell me your class please as this may be essential to testing. 

Thanks!

**Comment by liam5413** [comment]
hey,

 my class is druid and possibly also priest

Thanks

**Comment by fvicaria** [comment]
Works.
![capture](https://user-images.githubusercontent.com/9414661/29913293-a9a3b392-8e2c-11e7-9f8e-7aaa92ab90d8.PNG)

**Comment by liam5413** [comment]
hi, 

I dont want to equip the item i want to transmog it to a weapon i already have which you cant do atm, so if i cant transmog it and i cant even equip it then i dont understand how it works. Maybe i am missing something, i am trying to transmog at warpweaver hashom in the wow-mania mall and when i try the skull item isnt an option to transmog. thank you.

**Comment by tvshadowz** [comment]
Hi Liam! 

After further investigation I can see that when you try to equip the item "Skull of Man'air" (105141) the error "cannot dual wield" shows on classes that cannot dual wield. 

I think there is an issue with the weapon as it seems to be acting like a offhand weapon.

**Comment by fvicaria** [comment]
I am not doing any work on this sorry. If needed ask for a refund for the transmog tokens.
