### ISSUE TITLE
[Quest] Captives at Deathholme

### ISSUE THREAD

**Issue by Katherwind** [WoWManiaUK/Redemption#1545]
http://www.wowhead.com/quest=9164/captives-at-deatholme

As of last night (8/30/17) this quest was bugged for me  (Alisavia).  The objective of the quest is to rescue several people in Deatholme in the Ghostlands:

Apothecary Enith (http://www.wowhead.com/npc=16208/apothecary-enith)
Apprentice Varnis  (http://www.wowhead.com/npc=16206/apprentice-varnis)
Ranger Vedoran (http://www.wowhead.com/npc=16209/ranger-vedoran)

You are provided with the following item: 
http://www.wowhead.com/item=22628/renzithens-restorative-draught 

The npcs are located in various areas in Deatholme and are supposed to be unconscious and you are to revive them with the restorative draught.  I believe clicking on or talking with the npc completes the objective.

I tried this quest several times and each time the NPCs were standing up (instead of laying down unconscious)  and I was unable to interact with them in any way.  I tried relogging, clearing my cache, dropping the quest and retaking it,  all with the same result.  As such, I am unable to complete this quest.  

This is the last quest I need to complete the zone so I hope it can be fixed soon.

**Comment by captainloozer** [comment]
Hi Katherwind, and thank you for taking the time to report this.

Before we get too far into testing this, you mentioned that the NPCs were standing up last night.  Could you check again today and see if it is still like this?  It's possible that someone may have come by before you and completed the quest first and the NPCs just needed time to reset.  

Once you can confirm for me that this is still a problem, we may can do something to get this fixed.  For now, I'll test the quest on the development server and see if we also have the problem there.

**Comment by fvicaria** [comment]
NPC needs to be reset, that's all. Somebody left the quest half way through.
Please re-try.

**Comment by Katherwind** [comment]
Today at approximately 1:20 pm EDT I went back and checked.  The first NPC (Apothecary Enith) was still standing up and I was unable to interact with her in any way. 
It seems to me that the quest is bugged as it appears the NPC is not resetting after someone interacts with her.   Unless this bug is fixed, I will be unable to complete the quest without GM assistance.
Should I wait for a fix or put in a ticket to speak with a GM?
- Katherwind 

    On Thursday, August 31, 2017 1:12 PM, Josh <notifications@github.com> wrote:
 

 Hi Katherwind, and thank you for taking the time to report this.Before we get too far into testing this, you mentioned that the NPCs were standing up last night. Could you check again today and see if it is still like this? It's possible that someone may have come by before you and completed the quest first and the NPCs just needed time to reset.Once you can confirm for me that this is still a problem, we may can do something to get this fixed. For now, I'll test the quest on the development server and see if we also have the problem there.—
