### ISSUE TITLE
[Quest] Meet Lieutenant Icehammer

### ISSUE THREAD

**Issue by ManiaLightmare** [WoWManiaUK/Redemption#1547]
[Quest](http://www.wowhead.com/quest=11427/meet-lieutenant-icehammer)

A griffon does not appear at all when you accept the quest.

[Youtube Example of how it should work](https://www.youtube.com/watch?v=8ddCYM5l--s)

**Comment by fvicaria** [comment]
As is. Just fly to the other NPC. Quests changed after 3.3.5a.

**Comment by ManiaLightmare** [comment]
The link to quest was supposed to be to the mania site.  I grabbed the wrong one while researching.
[Quest](http://www.wow-mania.com/armory/?quest=11427)
Sorry for the confusion.

"When you're ready I'll place you on the back of one of our gryphons and zip you right to him! "

The video posted was from Aug 2008 which pre-dates patch 3.3.5a which was released the end of June 2010

**Comment by fvicaria** [comment]
OK I will try to add this feature but for now, the quest is perfectly doable just by flying to the NPC

**Comment by fvicaria** [comment]
By the way, on the video, the person is flying his own gryphon

**Comment by ManiaLightmare** [comment]
If he was, he wouldn't be able to fly through the keep or get a parachute.

Agreed that its doable without the feature.  You can go by ground, or depending on quest progression use the plane in the water.  If you have a flying mount, of course you can fly yourself there.

**Comment by fvicaria** [comment]
I will try to sort this.
