### ISSUE TITLE
[Quest] A Fall From Grace

### ISSUE THREAD

**Issue by alexkobe8** [WoWManiaUK/Redemption#1548]
Seems to be still bugged! :(

Mobs attack him and can't turn in my quest! :((

**Comment by tvshadowz** [comment]
Hi there Alexkobe! 

Could you please fill out an issue report here with what is currently happening so we are able to test the issue. I understand you have reported this before however we do need an updated report. 

Thanks!

**Comment by alexkobe8** [comment]
Hi!


Well i saw the topic of the quest, and it is still the same, npces around are attacking. But the thing is i can't turn in my quest! It says it's complete but still I can't turn it in! :(


I just want to finish the quest [A Fall From Grace] and keep on going 😊

________________________________
Från: Shadowz <notifications@github.com>
Skickat: den 1 september 2017 08:03:31
Till: WoWManiaUK/Redemption
Kopia: alexkobe8; Author
Ämne: Re: [WoWManiaUK/Redemption] [Quest] A Fall From Grace (#1548)


Hi there Alexkobe!

Could you please fill out an issue report here with what is currently happening so we are able to test the issue. I understand you have reported this before however we do need an updated report.

Thanks!

**Comment by tvshadowz** [comment]
Thats fine, please fill out another bug report describing what is going on. 

Thanks!
