### ISSUE TITLE
[Quest] Steamtank Surprise

### ISSUE THREAD

**Issue by ManiaLightmare** [WoWManiaUK/Redemption#1551]
http://www.wow-mania.com/armory/?quest=12326

If you get out of the steamtank at any point prior to completion.  A "friendly" steamtank will continue to attack you.  This continues even if you get in another vehicle.  There is no way back into the one you left originally.

As a hunter, you can feign death and it drives itself back to where it came from.  It doesn't continue to try and attack at this point but is unusable.

There is also a minor issue in that the seigetank's main attack, ice cannon, is supposed to do triple damage to scourge affected by ice prison (the tanks other offensive ability).  It does not appear to be modified at all when they are trapped.

[Ice Cannon](http://www.wow-mania.com/armory/?spell=49315)
[Ice Prison](http://www.wow-mania.com/armory/?spell=49333)

Since the area doesn't have the level of npc swarm as in retail, this really doesn't matter much.  They all die in about 2 hits anyway.

**Comment by captainloozer** [comment]
Hi ManiaLightmare, and thank you for your report!

I have tested the issues you have reported and can confirm that you are correct in that the tank will attack you if you exit before the quest is complete.  You are also correct in that the damage delt by Ice Cannon is not properly scaled against targets that are affected by ice prison.  

Below is a video capture of my findings.  Both claims are confirmed.

https://youtu.be/M1FY2Ab7yDQ

**Comment by fvicaria** [comment]
Spell and attack after dismount fixed.

**Comment by captainloozer** [comment]
Steam tank returns to it's original location if exited during the quest.  Confirmed fixed.
