### ISSUE TITLE
(SPELL) Conjure Mana Gem 

### ISSUE THREAD

**Issue by monyam** [WoWManiaUK/Redemption#1556]
Am I using our client? yes i am
Am I using the latest Launcher? yes

How spell should work: Conjure a mana gem and place it in bag. 
how the spell is working: alert appears in screen. "You can only carry 1 mana gem"

Be descriptive and precise.
Conjure Mana Gem does not conjure a mana gem.  Keep saying i can only carry 1, even though I have none. 
Relogs doesn't work. 
I recently did a race change from Blood Elf to Troll

Spell: http://www.wow-mania.com/armory/?spell=10054

I ahve spoken with a GM who told me to post here. We tried various thing in order to fix it.

**Comment by fvicaria** [comment]
Please follow the procedure described below before creating a new issue:
[How to Properly Report an Issue](https://github.com/wow-mania/Redemption/wiki/How-to-Properly-Report-an-Issue)

This will help developers identify and fix the issue quicker. Incorrectly or unclear reports will simply be deleted.

**Comment by fvicaria** [comment]
Test: Needs confirming.

**Comment by tvshadowz** [comment]
Hi there Monyam! 

Please make sure you don't already have a mana gem in your bank as this is what causes the error you're experiencing.

If you continue to experience this issue please comment here again and I will reopen the issue and contact you in game for more details :) 

Thanks! :D

**Comment by monyam** [comment]
Thank you! That was the cause. Now I feel kinda dumb. Must have thought it
was a different kind when I put it there

Den 2. sep. 2017 11.53 PM skrev "Shadowz" <notifications@github.com>:

**Comment by tvshadowz** [comment]
Haha that's absolutely fine, we all make the same mistake! 

Have a great day :)
