### ISSUE TITLE
(Quest) Call of Air - Draeni

### ISSUE THREAD

**Issue by ManiaLightmare** [WoWManiaUK/Redemption#1559]
http://www.wow-mania.com/armory/?quest=9554

"And when you're ready, I will fly you back down to the Exodar."

Upon accepting the quest, You should be able to speak to him again and Susurrus should cast a feather fall/flight type buff on you.  He does not have this option.

Does not impede you from completing, but wanted to log the descrepency

**Comment by tvshadowz** [comment]
Hi there ManiaLightmare! 

We do prioritise issues that are game breaking and stop individuals from completing quests which is why this issue will be closed. However, I will test and update the issue here and if we have enough time we will attempt a fix. 

Thank you for the report!

**Comment by tvshadowz** [comment]
You are correct. 

Susurrus should give you the option after accepting the quest however he does not.
