### ISSUE TITLE
[Quest] Everfrost

### ISSUE THREAD

**Issue by cathyr1** [WoWManiaUK/Redemption#1560]
Hello! There should be a quest http://www.wow-mania.com/armory/?quest=13420 in Storm Peaks that begins with an item http://www.wow-mania.com/armory/?item=44725. This item is contained in an Everfrost Chip. However, despite there should be plenty of these Chips (look at screenshot), I haven´t found any despite multiple times crossed the entire area.
![obr1](https://user-images.githubusercontent.com/30184491/30001731-d2ec6f7a-9096-11e7-9460-660837b71b9a.png)
![obrazek](https://user-images.githubusercontent.com/30184491/30001732-d83b59e6-9096-11e7-9608-5bd5b4a89e5f.png)

**Comment by fvicaria** [comment]
There are twenty of them at any time. We can look into increasing this but as for now it is "as is".

**Comment by cathyr1** [comment]
I´m sorry, you were right. They are just much smaller than expected and hidden in the trees. I found 3 when crossed the area again but experienced another problem. All 3 dropped another item = http://www.wow-mania.com/armory/?item=44729 instead of http://www.wow-mania.com/armory/?item=44725 despite I have marked this quest as not yet completed and the npc http://www.wow-mania.com/armory/?npc=32594 doesn´t offer the repeatable one so I should never done this before.

Do you have any hint? Or it is standard that a quest item drops only by lower chance?

Thanks a lot.
