### ISSUE TITLE
[QUEST] Supplies to Auberdine

### ISSUE THREAD

**Issue by Krenzy** [WoWManiaUK/Redemption#1561]
Hi My name is Mark, 
I found an unscripted quest.
It's name is Supplies to Auberdine.
Feero Ironhand need an excort, but he did not start moving, just stay.

Thanks for your work

**Comment by fvicaria** [comment]
Please follow the procedure described below before creating a new issue:
[How to Properly Report an Issue](https://github.com/wow-mania/Redemption/wiki/How-to-Properly-Report-an-Issue)

This will help developers identify and fix the issue quicker. Incorrectly or unclear reports will simply be deleted.

**Comment by tvshadowz** [comment]
Hi Krenzy!

As Fvicaria has said, please follow the linked provided and update this within the hour otherwise this issue will be closed and you will have to reopen another with adequate information. 

Thanks for the report!

**Comment by fvicaria** [comment]
Works fine!
![image](https://user-images.githubusercontent.com/9414661/30002128-a377dca4-9099-11e7-8207-9c95b84b59ae.png)

**Comment by fvicaria** [comment]
I have reduced the respawn time. Also I found an issue with the reset. Please re-test in dev. It should be OK now.
