### ISSUE TITLE
Barberchair error

### ISSUE THREAD

**Issue by vadii** [WoWManiaUK/Redemption#1563]
I posted the same issue yesterday, but you closed it without solving the problem, so here it is AGAIN:

The game crashes when I use the barberchair. This is how you can reproduce the error:
1) create a male troll with bald hair
2) use any barbershop chair

If you need help with reproducing the error let me know, but **dont close the issue without solving it**, it is very unprofessional!

![report_error](https://user-images.githubusercontent.com/25843989/30002178-f262666e-90a2-11e7-8479-8a5c046859fa.png)

**Comment by fvicaria** [comment]
This is a client issue. I will be fixed with the new client release within 2 weeks. In the meantime, you can just re-customize your character.  Just go to mall and use NPC.

**Comment by vadii** [comment]
OK, thanks for the info!
