### ISSUE TITLE
[Item] Champion's Purse

### ISSUE THREAD

**Issue by neoandre** [WoWManiaUK/Redemption#1564]
Item 45724 - [Champion's Purse](http://www.wowhead.com/item=45724/champions-purse) does not drop any Champion's Seals ([item 241](http://www.wowhead.com/currency=241/champions-seal)).
It should have around 50% chance of dropping 1 to 2 Champion's Seals (prior to 4.0.1) or 100% chance of dropping 1 (after 4.0.1).

**Comment by fvicaria** [comment]
This is 3.3.5a not 4.0.1
As is.

**Comment by fvicaria** [comment]
I have updated the chance. It was indeed too low. Set to 5)%
