### ISSUE TITLE
Savory Deviate Delight Not Working as intended

### ISSUE THREAD

**Issue by Lazypeonwowmania** [WoWManiaUK/Redemption#1567]
when i use my savory deviate delight i get the fliped out debuff on my screen which is only a 5 min cooldown instead of an hour . also i dont transform ether .

**Comment by captainloozer** [comment]
Hello Lazypeonwowmania, and thank you for your report.

While I was not able to reproduce this on the test realm, I have seen this issue myself on Redemption as recent as last week.  This issue may have already been fixed and is just waiting to be pushed to live side.  We will wait and see what Janitor says.

**Comment by fvicaria** [comment]
If it is ok in dev it is because it has been fixed.
Need to wait for deploy next Wednesday

**Comment by captainloozer** [comment]
As of right now on Dev:

![image](https://user-images.githubusercontent.com/9828794/30006683-6d6f2e4e-90c3-11e7-9308-a9267dad9cb5.png)
