### ISSUE TITLE
[Ulduar] Thorim's encounter always bugs the first time.

### ISSUE THREAD

**Issue by philoudu16** [WoWManiaUK/Redemption#1569]
Every time I've tried doing Thorim in Ulduar, the first try has been a guaranteed wipe, due to him using his "summon lightning orb" spell:
http://www.wowhead.com/spell=62391/summon-lightning-orb#comments
http://www.wowhead.com/npc=32865/thorim

As you can read in the comments (or in wowwiki:http://wowwiki.wikia.com/wiki/Thorim_(tactics) ), this spell should only be casted if everyone dies in the arena or if you take too long to reach Thorim. So far, every time I've been in Ulduar, when ppl in the gauntlet are just about to reach the second miniboss, this giant lightning orb insta kills them (not sure how long the orb takes to reach that point so I'm not sure exactly when the orb is summoned), even though every one in the arena is alive. So my guess would be the server thinks the combat has started way before it actually has (and thorim summons the orb as soon as you engage him, since he thinks 5 minutes have passed).

This means the first attempt is always a wipe, and running back + the repairs is kind of a pain tbh (and it's hard enough to find enough ppl willing to run ulduar as it is).

Do note that this only happens the first time. After that we've always needed to kill the mobs in the arena before the fight resets for some reason. (this would be consistent with my theory of the server thinking the fight starts way before it actually has)

**Comment by fvicaria** [comment]
You have a specific time to engage Thorin if that does not happen he will cast the spell. He needs to be in Phase 2 by that time or he will cast it.

**Comment by tvshadowz** [comment]
I'm currently not receiving this issue however it will be tested again to confirm.

**Comment by philoudu16** [comment]
I know you should have exactly 5 minutes to reach him or he casts his spell, the problem is it seems like he casts it as soon as we engage the mobs in the arena (which engages the encounter).

I dont know if doing some other boss before him or wiping on an encounter before him can make his timer start. Or maybe his timer starts when you attack a mob in the corridor leading to the arena for some reason...

**Comment by fvicaria** [comment]
The event will start when http://www.wowhead.com/npc=32872/runic-colossus and http://www.wowhead.com/npc=32873/ancient-rune-giant are both dead.
As you said 5min after that.

**Comment by philoudu16** [comment]
Not sure we're talking about the same "event start". The lightning bolt happened before we reached ancient rune giant. And the 5 min timer should start as soon as we enter in cbt with a mob in the arena (or when we pull the lever).

But it's no biggie, I'll try stay in the arena next time i'm in Ulduar, and i'll stay focused on Thorim to try and see exactly when he summons his orb.
