### ISSUE TITLE
[quest] Magic Carpet Ride, get to getry

### ISSUE THREAD

**Issue by Nocowlevel** [WoWManiaUK/Redemption#1570]
Chain of quests, cant seem to turn it the quest (Gorge the Corpsegrinder at Garrosh's Landing) at this stage for both my characters. Same for get to getry

http://www.wow-mania.com/armory/?quest=11636
http://www.wow-mania.com/armory/?quest=11703

**Comment by fvicaria** [comment]
Works fine. Tested in Redemption. Try dropping it and getting it again. If that fails, ask a gm to remove the quest from you (it will clean your server-side log).
![image](https://user-images.githubusercontent.com/9414661/30049659-60f93f50-9213-11e7-9195-a6d22c385d06.png)
![image](https://user-images.githubusercontent.com/9414661/30049696-8045287e-9213-11e7-9aaf-395549cddead.png)
