### ISSUE TITLE
[Quest] Relic of the Earthen Ring

### ISSUE THREAD

**Issue by tvshadowz** [WoWManiaUK/Redemption#1572]
http://www.wowhead.com/quest=14111/relic-of-the-earthen-ring

4 Totems should be traded for the Totem of the Earthen Ring item. However, currently the 4 totems are taken and the new totem is not provided to players.

**Comment by captainloozer** [comment]
Confirmed fixed in dev

![image](https://user-images.githubusercontent.com/9828794/30076802-c0f0dd74-923f-11e7-99aa-4d79e90d0404.png)
