### ISSUE TITLE
[Dungeon] Azjol-Nerub

### ISSUE THREAD

**Issue by squalllh1989** [WoWManiaUK/Redemption#1576]
This dungeon (http://www.wowhead.com/azjol-nerub) currently have some bug:
- The first encounter with Krik'thir the Gatewatcher (http://www.wowhead.com/npc=28684/krikthir-the-gatewatcher) : this boss have 3 other watcher with him, which is Watcher Silthik (http://www.wowhead.com/npc=28731/watcher-silthik), Watcher Narjil (http://www.wowhead.com/npc=28729/watcher-narjil), and Watcher Gashra(http://www.wowhead.com/npc=28730/watcher-gashra) along with 2 mob with each of them, make 3 group, before the gate watcher, they are subject of the archivement "Watch Him Die"(http://www.wowhead.com/achievement=1296/watch-him-die), they are not spawn there, which make the archivement can't be done for now. About this archivement, at the point of like 2-3 week later they are still there, the archivement work, but when you sucessful did the archive (kill the Gatewatcher with all 3 other watcher alive), the gate behind him didn't open, after you clean out all the other watcher and mob.
- The second encounter with Hadronox (http://www.wowhead.com/npc=28921), there are normally 3 pack of mob up near the gate where nerubian trash keep spawning, when you kill them all, Hadronox will start move up, web the gate to stop trash mob to spawn, which stop him to heal from his Leech Poison (http://www.wowhead.com/spell=53030/leech-poison), this is the normal and easy way to kill him, but currently those mob are randomly apear and phase out, most of the time they phase out, so we can't acually kill them, which forced us to come stright to hadronox and kill him in the way of doing the archivement "Hadronox Denied" (http://www.wowhead.com/achievement=1297/hadronox-denied), and even worse is Hadronox also randomly phase out, so for now, most of player are forced to skip it, run away from trash mob chase behind pass it or either try to burn him fast with all they have before it phase out randomly again.

The good thing is, the last fight with Anub'arak (http://www.wowhead.com/npc=29120/anubarak):this boss work perfectly in all fight i have done since the last time updated which make the other 2 fight bugged (before, the 2 first fight work perfectly, but Anub'arak randomly reset him self in the midle of the fight)

So, basicly what i wanna say is: please fix the 2 first fight, but also please keep the fix at last fight that prevent the random reset of Anub'arak, thank you very much.

**Comment by fvicaria** [comment]
Thank you for the report. That helps.

**Comment by captainloozer** [comment]
Krik'thir The Gatewatcher, Adds missing

![image](https://user-images.githubusercontent.com/9828794/30337798-1552d20e-97af-11e7-9d4e-5fb5df184663.png)
****

Boss should be accompanied by 
http://www.wow-mania.com/armory/?npc=28730
http://www.wow-mania.com/armory/?npc=28729
http://www.wow-mania.com/armory/?npc=28731

And each of those named NPC's should be flanked by one of each
http://www.wow-mania.com/armory/?npc=29335
http://www.wow-mania.com/armory/?npc=28734

In order to get http://www.wow-mania.com/armory/?achievement=1296, all three named NCP's must be alive when the boss dies.

Currently on dev, Hadronox and his mobs up top are doing the respawn loop again.

https://www.youtube.com/watch?v=rskk9LWEWuA

**Comment by Dranah** [comment]
I'd like to add that Anub'arak isn't fully working as intended either.
Here's a video where you can see the proper rate of adds spawning when Anub submerges: https://www.youtube.com/watch?v=hCO3sn6qZS4
Roughly 2 small or 2 big adds come at each wave, with 4-5 sec intervals.

Issue: currently, as soon as Anub submerges, about 20-25 (rough estimation) Nerubian Ambushers are released on the party at once, together with 2 bigger adds. Note, this is on normal difficulty.

**Comment by squalllh1989** [comment]
This bug still happening, just did 1 run of this 1 hour before.

**Comment by VA-L** [comment]
- Fixed Krik'thir the Gatewatcher groups of adds.
- Fixed Hadronox first group of adds spawn.
- Fixed Hadronox second & third groups of adds spawn.
- Fixed Hadronox movements, the boss was despawning once the second crusher was killed.
- Fixed Anub'arak's number of adds during the 75%/50%/25% phases.
- Fixed Anub'arak's reset while the boss was executing his last phase (25%).

Those fixes are now up to test.

**Comment by squalllh1989** [comment]
All boss / achivement / fix tested, work perfectly, especially the dramatic reduce in number of add during anub fight, this make thing much easier than the hell of add before
