### ISSUE TITLE
[Quest] Seeds of the Blacksouled Keepers 

### ISSUE THREAD

**Issue by MihailoVasovic** [WoWManiaUK/Redemption#1577]
http://www.wow-mania.com/armory/?quest=11319 seems to be bugged. When I try to use http://www.wow-mania.com/armory/?item=33607 on Spore, it says Invalid target.

**Comment by squalllh1989** [comment]
Did you use the item on a normal spore before killed it ? you must kill the spore before use the quest item on it, i have done it many time in the past, didn't have any problem with this quest, unless it's newly bugged.
As stated in the quest description: "I'll give you one of the cores from the ice elementals. **Once you've destroyed a spore, use the ice crystal to freeze it and keep it from regenerating.**"

**Comment by fvicaria** [comment]
@squalllh1989 Would you like to join our test team?
If yes, can you contact me or @tvshadowz? 
We can explain a little more what it is all about and the benefits.

**Comment by fvicaria** [comment]
Works perfectly.
Once again Github is not the place for players to get info on how to do the quest. Please research first, watch the videos, read the comments or even ask in world chat.
If you come here on the first problem you find you will waste the time of testers and developers on false issues.

**Comment by squalllh1989** [comment]
@fvicaria Sorry for the late response, sorry but how should i contact you two ? on skyper or ?

**Comment by tvshadowz** [comment]
Heya Squalllh1989, I currently head the test team and if you'd like to contact me at shadowz@wow-mania.com I'd be happy to help. :)
