### ISSUE TITLE
Frenzyheart Questline; [Playing Along] quest

### ISSUE THREAD

**Issue by Nyrina** [WoWManiaUK/Redemption#1579]
Cant pick up [Playing Along] quest from Tracker Gekgek after killing Pitch. "!" appears above his head but when talking to him nothing is listed

**Comment by squalllh1989** [comment]
Unless this quest is newly bugged, the way i have done this before is get the quest that require you to kill Pitch as an objective, The Part-time Hunter (http://www.wowhead.com/quest=12654/the-part-time-hunter), then when to kill Pitch (http://www.wowhead.com/npc=28097/pitch), then after i killed him and loot the quest item Pitch's Remains (http://www.wowhead.com/item=38703/pitchs-remains) from him, i was able to get the quest Playing Along (http://www.wowhead.com/quest=12528/playing-along) normally.

**Comment by tvshadowz** [comment]
This issue is confirmed. The quest icon appears about the npc's head but is not available after killing Pitch.

**Comment by tvshadowz** [comment]
In the first screenshot you can see that the quest icon is not there before Pitch is killed which is correct. 
![wowscrnshot_090717_194423](https://user-images.githubusercontent.com/30256554/30179675-22cca8ea-9405-11e7-96c1-1a1f6a56c6a9.jpg)

In this screenshot you can see after killing Pitch the icon appears but no quest can be obtained.
![wowscrnshot_090717_194443](https://user-images.githubusercontent.com/30256554/30179676-22cd356c-9405-11e7-8798-b527bf1013ee.jpg)

**Comment by fvicaria** [comment]
Kill him and respawn

**Comment by tvshadowz** [comment]
Does not allow for the quest to be obtained.

**Comment by fvicaria** [comment]
NPC needed reset. That was all.
![image](https://user-images.githubusercontent.com/9414661/30200077-64701d96-946d-11e7-9830-9abfa6cf0137.png)
