### ISSUE TITLE
[Quest] Filling the Cages

### ISSUE THREAD

**Issue by sebri00atomik** [WoWManiaUK/Redemption#1580]
http://www.wow-mania.com/armory/?quest=11984

When attempting to have Budd stun the trolls using the ability "Tag Troll", user is unable to as the ability will not work no matter how close to a troll the user is or what position the user is in. This renders the quest impossible to complete.

**Comment by fvicaria** [comment]
Works perfectly. Please search before posting a new issue. This makes developers and testers waste their time with invalid issues that the player could have done a minimum research and solve it by himself.
![image](https://user-images.githubusercontent.com/9414661/30150859-fba43432-93a4-11e7-964a-d71875ca62b6.png)

**Comment by tvshadowz** [comment]
Just to confirm, there is no need to cast "Tag Troll" as the player is able to capture the troll without doing so.
