### ISSUE TITLE
[Quest] Devourer of Souls

### ISSUE THREAD

**Issue by ManiaLightmare** [WoWManiaUK/Redemption#1582]
[Quest](http://www.wow-mania.com/armory/?quest=1716)

This quest is incorrectly flagged with a prerequisite of [Gakin's Summons](http://www.wow-mania.com/armory/?quest=1717)

Gakin's Summons should be optional.  Is is meant as a breadcrumb quest to guide gnome warlocks to Stormwind for their demon quests.  Otherwise human (or other) warlocks questing around Westfall/Darkshire would have to know to go to Ironforge to pick up a quest that sends them back to the trainer area they normally use in Stormwind.

See also: [http://wowwiki.wikia.com/wiki/Warlock_quests](http://wowwiki.wikia.com/wiki/Warlock_quests)

**Comment by fvicaria** [comment]
As is.
