### ISSUE TITLE
[Quest] Kickin' Nass and Takin' Manes

### ISSUE THREAD

**Issue by Raixxu** [WoWManiaUK/Redemption#1583]
http://www.wowhead.com/quest=12630/kickin-nass-and-takin-manes
When you start this quest, a person called ''Nass'' should appear and he should come with you, but he doesn't appear at all. There is an option to call Nass if he's missing, but that doesn't bring him to you either.
Am I using our client? 
-Yes
Am I using the latest Launcher? 
-Yes
Did I include the steps to reproduce the problem? 
-Yes
Did I include the description of how it should work? 
-Yes
Did I include the description of what is happening? 
-Yes
Did I include NPC/Item/Spell names (or IDs) from wowhead.com or Armory? 
-Yes, NPC name = ''Stefan Vadu''

![untitled](https://user-images.githubusercontent.com/31671535/30181897-286e06ee-9415-11e7-8efb-5298c46a2283.png)

**Comment by Raixxu** [comment]
[http://www.wowhead.com/quest=12630/kickin-nass-and-takin-manes](url)

**Comment by GmSaintz** [comment]
I am able to confirm the issue. Quest ID 12630 [Kickin' Nass and Takin' Manes] "Stefan in Ebon Watch wants you to use Nass to collect 10 hair samples from withered trolls" Nass does not spawn and you are unable to recover from Stefan as well.

**Comment by fvicaria** [comment]
![image](https://user-images.githubusercontent.com/9414661/30200544-4f9a4d90-946f-11e7-87cd-df0f34610d9e.png)
Works perfectly fine. Tested in Redemption.
