### ISSUE TITLE
[Quest] The Champion of Anguish

### ISSUE THREAD

**Issue by sebri00atomik** [WoWManiaUK/Redemption#1584]
http://www.wow-mania.com/armory/?quest=12948

Vladof was killed in group of two, quest did not complete. Quest was abandoned and re-attempted, and still did not complete after killing boss. Hunter pet was present during both attempts, it initiated combat on one attempt, it did not initiate on the second attempt.

**Comment by captainloozer** [comment]
Thanks for the report Sebri00atomik.  

I can confirm that this quest is working on dev as intended.

![image](https://user-images.githubusercontent.com/9828794/30240841-9082d844-953d-11e7-983f-4946f6e90ef1.png)
