### ISSUE TITLE
[Spell] Omen of Clarity

### ISSUE THREAD

**Issue by wowmania-Kindly** [WoWManiaUK/Redemption#1585]
Hello! :)
Omen of Clarity
I had a feeling this druid restoration tree talent wasnt functioning, so i tested a little. (i know its not a big test but i think it shows my point)
Instant cast HoTs:
100casts of Rejuvenation: 0procs
100casts of Lifebloom: 0procs
50casts of Wild Growth 0procs

Non-Instant cast Direct Heals:
100casts of Regrowth: 4 procs
100 casts of Nourish: 6 procs
50 casts of Healing Touch: 4 procs

Instant cast DoT: (still resto spec)
50casts of moonfire: 4procs

i read over forums for 3.3.5 info on the proc-rate. posts said they measured it at roughly 6%
i also see that this issue has been discussed before, but the tests done to see if clearcasting procs on healing, looks to be done by cast-time- Direct healing spell.
as resto druids dont use cast time-Direct heals often, its pretty much not working for them if i am right :/
hope you have time to look at this, and thanks for all the work you put in on the server :)
-kind regards Kindly 80 druid

**Comment by keidian** [comment]
I am playing resto druids and in a 5 minute fight my omen procs around 5-6 times. I am pretty sure it's working as intended.

**Comment by wowmania-Kindly** [comment]
cool! have you seen it proc from Instant-cast hots? i still havent :S

**Comment by captainloozer** [comment]
Confirmed working on dev.   Gained clearcasting after 8 casts of rejuvenation.

![image](https://user-images.githubusercontent.com/9828794/30240896-a495932a-953e-11e7-892b-4da7f051d976.png)

**Comment by Haponita** [comment]
It stopped working as intended again. This time it is not activated by any healing spells, either instant or with casting time. Please re-open this issue. Thank you
