### ISSUE TITLE
[Quest] Battle of the Crimson Watch

### ISSUE THREAD

**Issue by cathyr1** [WoWManiaUK/Redemption#1587]
Hello. It seems this quest http://www.wow-mania.com/armory/?quest=10781 is bugged. I tried it now twice, each time killed all waves including last boss but quest is not completed. Can you check this please?
![obrazek](https://user-images.githubusercontent.com/30184491/30242952-f1faff30-95a0-11e7-8691-2e3471dc07c9.png)

**Comment by captainloozer** [comment]
Hi Cathyr1, and thank you for your report.  

Unfortunately I was not able to reproduce this issue, as I received credit upon killing Torloth the Magnificent.  Below I have posted a video of me doing this.

https://youtu.be/brN-PXIVL9Q

If you are able to provide more information on how to reproduce this problem, please feel free to post again and we'll take another look at it.
