### ISSUE TITLE
[Boss] Professor Putricide 25HC - Transition Phase

### ISSUE THREAD

**Issue by hotdoggidy** [WoWManiaUK/Redemption#1588]
During transition phases @ 80% and 35% PP spawns both (green and orange) oozes simultaneously and players receive a debuff that forces them to attack a single ooze. The phase is supposed to be a coordination check for the raid. 

Today in 25hc we prepared to stack for the transitions but BOTH of the oozes de-spawned as they began to target players. This made both transitions mechanic-less nuke phases on the boss while he was "stunned" collecting mixtures at the table.

Not sure if this was an isolated event. Just figured id list it here.

Professor Putricide npc=36678
Volatile Ooze (green) npc=37697
Ooze Variable spell=70352
Gas Cloud (orange) npc=37562
Gas Variable spell=70353

**Comment by fvicaria** [comment]
This has already been fixed in dev. It will be released Tuesday.

**Comment by keidian** [comment]
On our 25 heroic in the first transition only the ooze despawned, the ooze was there. In the second transition both oozes despawned.

**Comment by fvicaria** [comment]
Nothing has changed there so whatever you "found" has been there for at least 2 months now.

**Comment by BatuMania** [comment]
This has started happening this week, there is no way this has been like this for months.
