### ISSUE TITLE
[Quest] If Valgarde Falls...

### ISSUE THREAD

**Issue by ManiaLightmare** [WoWManiaUK/Redemption#1589]
http://www.wow-mania.com/armory/?quest=11243

The invaders do not seem to be scripted properly.  Normally they spawn in packs of 3 or 4 near continuously and rush the Valgarde Defenders.  Currently there seems to be only a maximum of 8 invaders total that spawn and most do not move from their spawn position.

The major problem with only 8 is that the quest requires you to kill 12 which means, at best, one person can get 8 kills and would have to wait for respawn which is about 5 minutes for the remaining 4.

**Comment by fvicaria** [comment]
OK there are 57 of all them in the world. I have no idea why you said 8.
Check the quest details.

![image](https://user-images.githubusercontent.com/9414661/30250572-842cd192-9648-11e7-9ab1-998534e0cc72.png)

You can kill any of those.

**Comment by ManiaLightmare** [comment]
Not sure why mobs in Stormpeaks would count considering its the entry quest for Howling Fjord.  
The Wild Worg are in the horde entry area of Vengeance Landing so I wouldn't count those either.

"Get to the front gate and help the guards defend the city against the invading monsters!"
