### ISSUE TITLE
Elixir potion conflict

### ISSUE THREAD

**Issue by kolci** [WoWManiaUK/Redemption#1591]
Hi. While having an elixir up, I was unable to dring any potion at all. The game just said: "You cannot dring that yet". 
The potions were not on CD, though one potion was "greyed out" - as it cannot be used, and another was "bright" - as it can be used. Neither of them were usable.
**After removing elixir buff** and waiting for a few minutes, **I was able to drink potions**.
Elixirs should not conflict with potions. Thanks

The elixir used: Week trolls blood elixir.
The potions (not) used: Minor rejuvenation potion, Healing potion.
Using launcher 2.0.8b. Relog, clear cache do not work.

**Comment by fvicaria** [comment]
I have just tried them and worked fine.
