### ISSUE TITLE
[Raid] ICC - Blood Prince Council

### ISSUE THREAD

**Issue by Plege** [WoWManiaUK/Redemption#1593]
During the BPC encounter kinetic bombs keep dropping from the ceiling towards the floor. If they do reach the floor they explode knocking players back and causing damage.

The orbs can be dealt with by damaging them with ranged attacks, not to destroy but to knock them back up in the air.

A destruction specced warlock can use chaosbolt (http://www.wow-mania.com/armory/?spell=59172) to kill the orbs making the encounter significantly easier.

The kinetic bombs should indestructible and only managable rather than killable.

Regards, Pleger

**Comment by captainloozer** [comment]
Hi Plege and thank you for your report.

Unfortunately I was not able to reproduce this issue on the dev server.  It may have already been fixed and is simply waiting to be pushed to the live realm (Redemption).
