### ISSUE TITLE
[Raid] ICC - Valithria Dreamwalker

### ISSUE THREAD

**Issue by Plege** [WoWManiaUK/Redemption#1594]
During the Dreamwalker (http://www.wow-mania.com/armory/?npc=36789) encounter several waves of adds spawn.

One of them is the Risen Archmage, he casts a spell  (SPELL_COLUMN_OF_FROST = 70704 / SPELL_COLUMN_OF_FROST_DAMAGE = 70702) that has a knock back component and is aimed onto the ground under a random players in the raid.

The problem arises if the raidmember under which the spell is cast stands too close to valithria herself. The knock back will throw the wounded dragon across the room. the boss should not move and should be knock back immune.

Regards, Pleger

**Comment by fvicaria** [comment]
Sorry, there has not been any change in ICC for the last month and it all has been working fine. So unless it's a show stopper I am not doing anything about it. ICC is now closed.

**Comment by captainloozer** [comment]
I can confirm that this does happen, and it happens often.  The spell is Column of Frost and it is only cast on the 25 man difficulty.  If any player is standing anywhere near Dreamwalker (and this is necessary to kill suppressors), the collumn is placed on the ground and if it his the boss she flies away.  If this happens twice she is usually knocked into the floor or through the wall and the raid is forced to wipe.  

http://www.wow-mania.com/armory/?spell=70702

I've included a video of this happening on dev.

https://youtu.be/1z09EL3qGBM

**Comment by BatuMania** [comment]
This could be fixed if only the spell (SPELL_COLUMN_OF_FROST = 70704 / SPELL_COLUMN_OF_FROST_DAMAGE = 70702) would simply not affect Dreamwalker or as captainloozer said, just make it immune to any form of knockback

**Comment by captainloozer** [comment]
With my latest test (about an hour ago) on 25 man difficulty, Risen Archmages were no longer casting Column of Frost.  While this makes the fight somewhat easier, it also eliminates the chance of this bugging out the fight as well.

**Comment by fvicaria** [comment]
There was absolutely no change on those. The only change was on Valithria immunity

**Comment by captainloozer** [comment]
I will check again shortly.

**Comment by captainloozer** [comment]
Just tested again, after a few minutes one of the Risen Archmages casted Column of Frost near her and she took off.

![image](https://user-images.githubusercontent.com/9828794/30287534-1729f586-96eb-11e7-926e-a2590d0cae28.png)

**Comment by captainloozer** [comment]
Some new info I just found, several spell ID's for column of frost, including:

http://www.wow-mania.com/armory/?spell=72020
http://www.wow-mania.com/armory/?spell=71746
http://www.wow-mania.com/armory/?spell=72019
http://www.wow-mania.com/armory/?spell=72020

Perhaps providing the boss NPC immunity to all 4 will do the trick.

**Comment by captainloozer** [comment]
Tested again after recent changes on dev server.  I assume Janitor applied one or all of the above IDs to the boss npc's immunity list and she no longer flies in the air after having column of frost cast under her.  I tested this twice, both times she stayed put.
