### ISSUE TITLE
[Quest] The Fallen Sisters - Howling Fjord

### ISSUE THREAD

**Issue by jrbowler** [WoWManiaUK/Redemption#1596]
Quest: http://www.wowhead.com/quest=11314/the-fallen-sisters
Relevant NPC: http://www.wowhead.com/npc=23678/chill-nymph
Quest Item: http://www.wowhead.com/item=33606/lurielles-pendant

When trying to use the quest item on the appropriate NPCs, "Invalid Target" error message is displayed. 
![issue](https://user-images.githubusercontent.com/12320337/30271274-4cc35d3a-96b5-11e7-9d8d-1e992992b1b0.jpg)

**Comment by fvicaria** [comment]
Pretty sure this works.

**Comment by BleakSenpai** [comment]
The quest works when the NPCs respawn to being hostile, but the NPCs won't respawn to being hostile again after using the quest item. All of them were Friendly, had to kill them and respawn them for the quest to be doable. This bug happens a lot on many different quest as well.

**Comment by fvicaria** [comment]
OK. This is probably caused by players not completing the quest properly. 
I will try to fix NPC.

**Comment by captainloozer** [comment]
![image](https://user-images.githubusercontent.com/9828794/30284839-b1aaa114-96e1-11e7-9808-87dcbcc00878.png)

After using the quest item, the chill nymph ran away and depsawned.  

![image](https://user-images.githubusercontent.com/9828794/30284806-9cadc1a6-96e1-11e7-8c72-e854e9f49b63.png)

Also worth noting, I noticed the map incorrectly shows where the chill nymphs are.  On this map you can see where the quests say they should be, but really they are at my current position.  Where the map says they should be, you will only find Frost Nymphs.
