### ISSUE TITLE
[Quest] Shred the Alliance

### ISSUE THREAD

**Issue by AnetteHansen** [WoWManiaUK/Redemption#1597]
Shred the Alliance. Not able to mount the shredders, so not possible to do this quest.
http://www.wowhead.com/quest=12270/shred-the-alliance#comments

**Comment by captainloozer** [comment]
![image](https://user-images.githubusercontent.com/9828794/30284498-b3d06cb8-96e0-11e7-8505-670e72605813.png)

![image](https://user-images.githubusercontent.com/9828794/30284565-db4fc216-96e0-11e7-8056-b7b3148a9fdd.png)

Confirmed working on dev.
