### ISSUE TITLE
The last line of Defense - no mana regen

### ISSUE THREAD

**Issue by bogey2230** [WoWManiaUK/Redemption#1598]
18:18 server time, 9/11
   Upon trying to complete ' The Last line of Defense ' the cannon were displaced not on top of the towers but along the base ( off the ground but along the base of the wooden base uptop the tower). A person can complete the 100 kill part of the quest but the mana regen to use the ' reckoning bomb ' to kill the larger mobs ( Dragons ). Contacted a GM in-game which reset one cannon to be placed properly but still could not regen mana to use the Reckoning Bomb.

Was told by GM in-game to submit a report

'cal'

**Comment by captainloozer** [comment]
Hi bogey2230, and thank you for your report.  

I can confirm that the reckoning bomb doesn't work, even when mana is full, however, the quest can still be completed by simply using the "number 1 ability" on the action bar and just killing the smaller spider mobs.  For now, you should be able to complete the quest that way.

**Comment by captainloozer** [comment]
I will edit this comment and post links to the vehicle ability IDs and the vehicle object ID as soon as I can get back on the dev server to test again.

**Comment by fvicaria** [comment]
Please test in dev.
Canons keep being moved by players. That has been fixed in dev.

**Comment by captainloozer** [comment]
Canon moving confirmed fix as well as the mana bar.  After Janitor switched the energy bar to mana it regens properly and Reckoning bomb works.
