### ISSUE TITLE
Quest: A dip in the Moonwell bugged?

### ISSUE THREAD

**Issue by Wrathllama** [WoWManiaUK/Redemption#1599]
Qhile controlling the robot, going to collect water fromt he moonwell pushing the spell button to collect water doesnt work, have a gander into please!

**Comment by captainloozer** [comment]
Hi, Wrathllama, and thank you for your report.

In the future, please link all relevant quests, items, npcs, and spells from approved sources such as the wow-mania armory or wowhead.  This helps developers and testers tremendously when trying to reproduce the issues.

http://wow-mania.com/armory/?quest=9433

**Comment by captainloozer** [comment]
Unfortunately, I was not able to reproduce this issue on the dev server.  Try logging out and back, deleting your cache, or abandoning the quest and picking it back up and see if that fixes your problem.  If you are able to provide more information on how to reproduce your problem, feel free to post again.

![image](https://user-images.githubusercontent.com/9828794/30300284-7af7c222-9719-11e7-9688-2aa048365e54.png)
