### ISSUE TITLE
[Quest] Vanquish the Raven God

### ISSUE THREAD

**Issue by boohe91** [WoWManiaUK/Redemption#1600]
the quest  [Vanquish the Raven God] is bugged 
i have the [Essence-Infused Moonstone] 
and i went into Sethekk Halls Heroic 5 man
when i went to use [Essence-Infused Moonstone] 
to summon Anzu for the quest it wont summon him
 no matter how many times i try it casts it but just dosnt summon him
i cleared the entire room and tried not clearing the room 
either way it wont work

**Comment by fvicaria** [comment]
I am pretty sure this works. Check all conditions.

**Comment by boohe91** [comment]
i tryed this 15 mins b4 i made this damn post it DOSNT owrk

**Comment by fvicaria** [comment]
If you are going to start cursing at least learn how to spell. 
I checked in dev and it works. I will check in Red when I have a chance.

**Comment by boohe91** [comment]
look come join me ingame deathtracker im standing in the instance right now

**Comment by boohe91** [comment]
https://github.com/WoWManiaUK/Redemption/issues/1601 new post with screenshots

**Comment by captainloozer** [comment]
Working on Dev

https://youtu.be/ccfjSjAKjrE
