### ISSUE TITLE
[Quest] Vanquish the Raven God

### ISSUE THREAD

**Issue by boohe91** [WoWManiaUK/Redemption#1601]
the quest [Vanquish the Raven God] is bugged
i have the [Essence-Infused Moonstone]
and i went into Sethekk Halls Heroic 5 man
when i went to use [Essence-Infused Moonstone]
to summon Anzu for the quest it wont summon him
no matter how many times i try it casts it but just dosnt summon him
i cleared the entire room and tried not clearing the room
either way it wont work

PS dont close something that needs to be fixed i have all requiremets MET and it will not work
dont beleave me join my damn group char name deathtracker ill be waiting in the halls

**Comment by boohe91** [comment]
![wowscrnshot_091217_205410](https://user-images.githubusercontent.com/31642537/30322370-9c0739f0-97fc-11e7-8de4-8d726a2542c5.jpg)
![wowscrnshot_091217_205412](https://user-images.githubusercontent.com/31642537/30322373-9c13d6e2-97fc-11e7-972e-9e9dfbeae449.jpg)
![wowscrnshot_091217_205413](https://user-images.githubusercontent.com/31642537/30322372-9c0df24a-97fc-11e7-8cf5-63955314599e.jpg)
![wowscrnshot_091217_205414](https://user-images.githubusercontent.com/31642537/30322371-9c0c0782-97fc-11e7-9a3b-cbbe773cf76a.jpg)
![wowscrnshot_091217_205415](https://user-images.githubusercontent.com/31642537/30322375-9c3d05b2-97fc-11e7-88a9-10d4947f67c4.jpg)
![wowscrnshot_091217_205416](https://user-images.githubusercontent.com/31642537/30322374-9c3cd894-97fc-11e7-865d-175abd69c74a.jpg)
![wowscrnshot_091217_205417](https://user-images.githubusercontent.com/31642537/30322376-9c3fa68c-97fc-11e7-9f4f-3e97f910ed7a.jpg)

**Comment by fvicaria** [comment]
Do not create repeated issues. I said I was going to look at it.

**Comment by boohe91** [comment]
but u closed the other one

**Comment by fvicaria** [comment]
![image](https://user-images.githubusercontent.com/9414661/30325806-1ad0d988-97be-11e7-9921-9d4fc63fa48a.png)
It works for me.
Do not open another one.
I will ask another dev to test.

**Comment by boohe91** [comment]
whatever ill just abandon the quest  works for u yer wont work for me in any way shape or form go figure

**Comment by captainloozer** [comment]
Working on Dev

https://youtu.be/ccfjSjAKjrE
