### ISSUE TITLE
Wintergrasp

### ISSUE THREAD

**Issue by TheRealFionn** [WoWManiaUK/Redemption#1603]
Since the patch we are unable to cap Wintergrasp on the alliance side.  Verified three different times.  No horde players were present.  I even started the match on the top of the building to see if people were loging in alts and hiding them in the stacks.  12 Ally players with 0 horde and the slide bar will not move.

**Comment by TheRealFionn** [comment]
I do not know if the horde can cap it as they have been starting with it.  Since we won I will have that answer for you in about 45 minutes.

**Comment by TheRealFionn** [comment]
Ally cannot cap SR nor EP.  BT and WP takes two ally to cap and if left alone they will go back to the horde like they have people there.  Even if they do not.

**Comment by fvicaria** [comment]
I am looking into it.

**Comment by TheRealFionn** [comment]
Was just trying be thorough.

**Comment by fvicaria** [comment]
Fixed.
