### ISSUE TITLE
[NPC] The Lurker Below

### ISSUE THREAD

**Issue by WhitephoenixTheBunny** [WoWManiaUK/Redemption#1604]
On Serpent Shrine Caverns, the fish boss, The Lurker Below is bugged; this boss is untargetable, so we cant kill him.

**Comment by fvicaria** [comment]
https://www.wowhead.com/npc=21217/the-lurker-below

**Comment by WhitephoenixTheBunny** [comment]
Sorry, i explain wrong myself... we fished him, but after he comes out water, we cant target him, he stand he front of us a seconds, we try target him, and he goes away

**Comment by fvicaria** [comment]
We are working on it on the test server.

**Comment by captainloozer** [comment]
Tested a couple of times, each time I didn't catch anything, the boss didn't spawn.  The first time I didn't catch anything I got the achievement for fishing him up, but he didn't spawn at all.

**Comment by fvicaria** [comment]
I have made some changes on this.
Please check again.

**Comment by captainloozer** [comment]
Same thing.  It seems when I fish up a regular fish, the pool despawns and then comes back shortly after.  Any time I catch "nothing", where apparently the boss is supposed to spawn, the pool stays.  I was not able to fish him up after about 10 minutes of fishing.  I've included a short clip of my fishing trip, but honestly it was just ten minutes of that, repeated.

https://youtu.be/GTKQzEjeW0E

**Comment by WhitephoenixTheBunny** [comment]
![wowscrnshot_091617_155656](https://user-images.githubusercontent.com/31921098/30516705-85d2f45e-9b3e-11e7-994e-1985232f88b0.jpg)

dead

**Comment by captainloozer** [comment]
![image](https://user-images.githubusercontent.com/9828794/30520879-ca27ab1c-9b7b-11e7-8e98-c5ba6c807f5d.png)


Confirmed fixed in dev
