### ISSUE TITLE
[Bug] It is possible to get Unbound Plague from Professor Putricide in ICC 25 nm.

### ISSUE THREAD

**Issue by MailOrdered** [WoWManiaUK/Redemption#1605]
![wowscrnshot_091217_133006](https://user-images.githubusercontent.com/29909872/30384716-4e9cd92a-9862-11e7-8f83-556d0a806736.jpg)

I do not know how and I do not know why, but one member in or 25nm raid complained of having Unbound plague and, as my recount shows, he did indeed take damage from it. You'll notice that both the chat instance welcome and the icon on the minimap say we are in 25 nm. It was my understanding that this was a purely heroic spell.

The numbers in Recount are a little screwy because someone talked to Tyrian or something and we had a combat bug the whole raid. I believe this is a separate issue, but it is relevant none the less.

**Comment by fvicaria** [comment]
This is fixed in dev already.
