### ISSUE TITLE
[Bug] Alliance PVP NPCs yell "For the Horde!" when attacking

### ISSUE THREAD

**Issue by MailOrdered** [WoWManiaUK/Redemption#1606]
![wowscrnshot_090817_182655](https://user-images.githubusercontent.com/29909872/30385252-d6e64c48-9863-11e7-9b9c-e8158e9d983c.jpg)

Specifically, Senior Demolitionist Legoso says it when Ally are on attack.

Not big, but still.

**Comment by fvicaria** [comment]
Fixed in dev.
