### ISSUE TITLE
Southsea Freebooters shooting through sap

### ISSUE THREAD

**Issue by Wulfsg** [WoWManiaUK/Redemption#1607]
I noticed that while I was out killing Southsea Freebooters for the quest "Southsea Shakedown" in Tanaris, if you sap them to kill the target next to them, they can still shoot, while not losing the sapped debuff. I did pull aggro on them when I started fighting the mob next to it, a Southsea Pirate, but normally this means that once the debuff wears off, they will attack me, it prevents me from stealthing even while they're still debuffed, etc. Generally they don't perform actions, however.

**Comment by captainloozer** [comment]
Hi Wulfsg, and thank you for your report.

Unfortunately, on my rogue, I was not able to reproduce this issue.  After sapping a freebooter, I drug several mobs very close to them and entered combat but the frebooters remained sapped and did not attack me.  I was also able to enter stealth again after I finished combat and the freebooter remained sapped.  If you can provide any more information about how to reproduce this issue, please feel free to submit another report.
