### ISSUE TITLE
Forests edge of elwynn forest

### ISSUE THREAD

**Issue by Magixxar** [WoWManiaUK/Redemption#1608]
Most of the camps there do not have riverpaws in them. Most are just bare, if not always bare.

Thanks in advance!

**Comment by captainloozer** [comment]
![image](https://user-images.githubusercontent.com/9828794/30407655-276b42d0-98bf-11e7-9019-dec907eafbdb.png)

![image](https://user-images.githubusercontent.com/9828794/30407668-31c06c9c-98bf-11e7-9f02-73cb5ef3348f.png)
![image](https://user-images.githubusercontent.com/9828794/30407670-3d0ff310-98bf-11e7-987a-ba4b5adc89c7.png)

Several camps not respawning.  These screens were taken from Red after waiting over 10 minutes for respawns.

**Comment by squalllh1989** [comment]
Confirm.
These camp which contain Riverpaw Outrunner (http://www.wow-mania.com/armory/?npc=478),  Riverpaw Runt (http://www.wow-mania.com/armory/?npc=97), and maybe a rare mob, Gruff Swiftbite (http://www.wow-mania.com/armory/?npc=100) are objective of Riverpaw Gnoll Bounty(http://www.wow-mania.com/armory/?quest=11)
Tested more than 2 hours after captainloozer, 5 out of 6 camp is not getting respawned, still empty.
![wowscrnshot_091417_100632](https://user-images.githubusercontent.com/27235989/30410496-a436108a-9935-11e7-8b4f-52f4b9f5ad12.jpg)
![wowscrnshot_091417_100637](https://user-images.githubusercontent.com/27235989/30410511-b00aaa38-9935-11e7-9290-60b3711f6d78.jpg)
![wowscrnshot_091417_100640](https://user-images.githubusercontent.com/27235989/30410514-b261afe8-9935-11e7-8ba5-d8b25abea361.jpg)
![wowscrnshot_091417_100646](https://user-images.githubusercontent.com/27235989/30410517-b7d77aca-9935-11e7-94fa-1711bc1ad703.jpg)
![wowscrnshot_091417_100652](https://user-images.githubusercontent.com/27235989/30410519-b9dc3158-9935-11e7-8110-5350dd40b6dc.jpg)
![wowscrnshot_091417_100659](https://user-images.githubusercontent.com/27235989/30410520-bbacd992-9935-11e7-89f3-1bdd09122a61.jpg)

Seem only 1 camp at 26, 86 respawn normally, those are wandering arround got respawned, also, but the other camp are not.

**Comment by captainloozer** [comment]
Came back 3 hours later, camps still abandoned.  Def confirmed.

**Comment by tvshadowz** [comment]
Hi there Squalllh1989,

Please email me at shadowz@wow-mania.com if you wish to talk about joining the test team :)
