### ISSUE TITLE
[Quest] "the enemies of light" is buged

### ISSUE THREAD

**Issue by anzo31** [WoWManiaUK/Redemption#1616]
Okay I got to the quest: "the enemies of life" and found out the mobs spawn wired but just tough is was a bit buged so I  just kill them but found out that it did't count for t he quest. They also don't do the magic thing or only some do and some do not but most of all the quest is not getting count even if I kill them all.
I had contact at GM and he told me it was working but I got back and tired again for the 5th time and it still doesn't work so he told me to report it here. I have taking a screen shot to give you an idea what I mean when I saw "spawn 
![wowscrnshot_091517_094403](https://user-images.githubusercontent.com/8068585/30472077-6bdfa338-99fb-11e7-9e67-5deb7f9ff2de.jpg)
wired"

**Comment by fvicaria** [comment]
Please follow the procedure described below before creating a new issue:
[How to Properly Report an Issue](https://github.com/wow-mania/Redemption/wiki/How-to-Properly-Report-an-Issue)

This will help developers identify and fix the issue quicker. Incorrectly or unclear reports will simply be deleted.

Please link at least the quest.

**Comment by anzo31** [comment]
Well i tought it was what I did I follow what the gm said and how shall I link the quest here

**Comment by fvicaria** [comment]
Also I have just logged and they look ok to me:

![Uploading image.png…]()

**Comment by anzo31** [comment]
Oh sorry  im new on the server and this is my first bug report but here it is: http://www.wow-mania.com/armory/?quest=11792

**Comment by anzo31** [comment]
Well it will not be a problem if it will count when killing them but its no

**Comment by fvicaria** [comment]
OK, I could not find the ques in the bug description. The name was wrong. :)
That's why we ask links + description

**Comment by anzo31** [comment]
okay its that one I linked and I remember you shall kill thos guys and stop them in doing the cult thing but they are not doing the thing and it dosen't count when you kill them ether.

**Comment by anzo31** [comment]
That wired that they look fine for you. I even use your guys launcher hmm could it have something to do with wish one of the tow there is you use maybe? I mean there is one name "wow" and one name "launcher"

**Comment by fvicaria** [comment]
There are two circles. You were right. One of them they were off.
I fixed the script also so they should be OK after restart.
Thanks for reporting.

**Comment by anzo31** [comment]
OKay and thanks for the help

**Comment by squalllh1989** [comment]
This quest is "Enemies of the Light" not "the enemies of life" lol

**Comment by captainloozer** [comment]
NPC's spawning where they should with the correct animations.

![image](https://user-images.githubusercontent.com/9828794/30515603-df56300c-9af0-11e7-94bf-b155100ecd2f.png)

**Comment by captainloozer** [comment]
Pulled them and ran away and they returned to different spots.

![image](https://user-images.githubusercontent.com/9828794/30515621-5010ad4a-9af1-11e7-8590-28f3328c1703.png)

**Comment by captainloozer** [comment]
@anzo31 After reading over your original post a few times, I can't help but wonder if you're trying to get quest completion credit by killing them or by some other means.  The quest is completed when they drop an item called Cultist Communique, which is looted from them after killing them.  It's not 100% drop rate so you may need to kill several of them before you get it.  

http://www.wow-mania.com/armory/?item=35122

While the mobs may not return to the correct place after killing them or aggroing them, the quest is working 100%.  I'm marking this fixed in dev since I am able to confirm that the quest is working fine, despite the cosmetic problems.  

If I am misunderstanding your issue, please correct me and we will continue to work on it.  But for now, if your issue is that you can't complete the quest, please follow my advice.

**Comment by anzo31** [comment]
They didt drop the thing no and I lonely put this up because the quest didt work and will help you guys by letting you know the time it got fixed I was on a other quest but if you read the whole thread you  will see there were a problem and it got fixed
