### ISSUE TITLE
[Quest] On Ruby Wings

### ISSUE THREAD

**Issue by squalllh1989** [WoWManiaUK/Redemption#1620]

**Comment by fvicaria** [comment]
@
Please follow the procedure described below before creating a new issue:
[How to Properly Report an Issue](https://github.com/wow-mania/Redemption/wiki/How-to-Properly-Report-an-Issue)

This will help developers identify and fix the issue quicker. Incorrectly or unclear reports will simply be deleted.

**Comment by squalllh1989** [comment]
Sorry, i mistakely press the create topic before enter the text, so i'm editing it :(
