### ISSUE TITLE
[Quest] On ruby wings

### ISSUE THREAD

**Issue by squalllh1989** [WoWManiaUK/Redemption#1621]
This quest (http://www.wow-mania.com/armory/?quest=12498) is current have a bug on objective "Scythe of Antiok".

The way it should work: you use the Ruby Beacon of the Dragon Queen (http://www.wow-mania.com/armory/?item=38302) to call forth and control a Wyrmrest Vanquisher (http://www.wow-mania.com/armory/?npc=27996), use it ablity to kill 30 Wastes Scavenger (http://www.wow-mania.com/armory/?npc=28005), and engage Grand Necrolord Antiok (http://www.wow-mania.com/armory/?npc=28006) with Thiassi the Lightning Bringer (http://www.wow-mania.com/armory/?npc=28018) on his aid. Antiok has a shield Shroud of Lightning (http://www.wow-mania.com/armory/?spell=50494) that make him immune to all damage. You must kill Thiassi the Lightning Bringer first to broke his shield, and then defeat him on foot (get out of the Wyrmrest Vanquisher and fight on your own). After you killed him, he drop the Scythe of Antiok (http://www.wow-mania.com/armory/?item=38305) which you loot to complete the quest.
What is happening: After you killed Thiassi the Lightning Bringer, Antiok's shield (Shroud of Lightning) does not disapear, render him still immune to all damage, so you can't do anything to him, with or without the Wyrmrest Vanquisher.

- First picture: you can see that Thiassi the Lightning Bringer just got killed
![wowscrnshot_091517_205456](https://user-images.githubusercontent.com/27235989/30485698-6ed91954-9a58-11e7-9609-a4885528d8a7.jpg)

- Second picture, Antiok  still having the shield
![wowscrnshot_091517_205512](https://user-images.githubusercontent.com/27235989/30485717-7dcdfab0-9a58-11e7-9841-fbe6399c54bb.jpg)

-Third picture, the combat log show out that the attack on him fail because he is immune
![wowscrnshot_091517_205535](https://user-images.githubusercontent.com/27235989/30485759-975479be-9a58-11e7-84fc-d3c5b3c23009.jpg)

**Comment by captainloozer** [comment]
Confirmed fixed on dev

![image](https://user-images.githubusercontent.com/9828794/30516345-c237fa94-9b01-11e7-8893-b16191e7ef4f.png)


https://youtu.be/H5c96yZBO5M

**Comment by squalllh1989** [comment]
work perfectly now.

**Comment by Zeevee92** [comment]
This issue was still there toaday

**Comment by squalllh1989** [comment]
Maybe it's back ? will try to test it out asap

**Comment by squalllh1989** [comment]
Will reopen this so some one can test this out later and confirm if it is currently work or not

**Comment by Narjhan** [comment]
Is this quest bugged again?  I am having the exact same issue today.

**Comment by AviiNL** [comment]
For anyone coming across this issue and using azerothcore, from the world database table `creature_template_addon`, delete the row `(28006,0,0,0,0,0,3,'50494')` so the aura is not permanently attached to the npc..
