### ISSUE TITLE
AH bug/payment receive issue

### ISSUE THREAD

**Issue by OFFICALNOX** [WoWManiaUK/Redemption#1622]
I will start with this has happened several times sofar almost several times on a daily basis i do not know of any particular ways to reproduce this experience, i was having this issue prior to adding addons in, and the issue continues even after so i do not believe it would be a addon related issue the fact that this issue has happened to a friend of mine also makes me believe this is more then just a personal issue especially when he described pretty much to the word the issue im having. My issue can best be described as a AH mailbox collection issue i guess when i sign in or when ever i usually get several AH transactions coming in fairly constantly so theres times ill just be lazy n let several stack n times i clear them soon, but when i try to collect it shows the letter from the AH naming the buying with the timer with how long should be left until said acution arrives but it stays at 00:00 n doesnt change and doesnt produce money from the item purchased i was sent a letter assuring me the AH n mailing system was in working order this morning but literally seconds after reading it i had 2 payments to collect both were ready from me just waking up so things had all night to come in and i received the first payment then when i shift clicked the next one to auto loot it no money came just turned the order darkened color and made it look like a dead piece of mail until it auto deletes, i just spoke n talked to a GM n confirmed i can start streaming on here so imma be streaming every minute im on from now on so ill be able to catch n record this error happening for your review shortly n add it to this thread if possible.

**Comment by OFFICALNOX** [comment]
![wowscrnshot_091517_123523](https://user-images.githubusercontent.com/31995564/30500354-c8f654b0-9a12-11e7-82f5-ecf3e9baaca6.jpg)

as you can tell the amount should of been collected yet it wasnt theres no gold awaiting my collection and rather then a delivery timer theres a timer until the mail is deleted .

**Comment by OFFICALNOX** [comment]
![wowscrnshot_091517_124302](https://user-images.githubusercontent.com/31995564/30500513-853b1ba6-9a13-11e7-9f67-545853882c89.jpg)


this is how collecting the gold screen should look for a sale of the EXACT SAME ITEM

**Comment by fvicaria** [comment]
Send an email to support@wow-mania.com to get a refund on your gold.

**Comment by OFFICALNOX** [comment]
im not worried about a few gold, but there is a obvious issue here my concern is addressing and fixing this issue would take more time to screen shot every sale then its worth, just fix it kindly <3
