### ISSUE TITLE
[Raid] Ulduar - Corridors of Ingenuity

### ISSUE THREAD

**Issue by Nimsy** [WoWManiaUK/Redemption#1624]
In level 2 hallway called Corridors of Ingenuity their are multiple types of bots such as Sappers (http://www.wowhead.com/npc=34193) and Mechanics (http://www.wowhead.com/npc=34184). Untargetable adds will spawn behind players and begin to kill the players as they kill the adds in the hallway. Eventually killing everyone in the instance. The tram at the end of the hallway is also not usable.

**Comment by captainloozer** [comment]
Can confirm that there are no more infinitely spawning untargetable mobs, but the tram still isn't working.  When I arrived on the gauntlet side, I saw the tram arrive, and perform the "Doodad_UI_Train_Turnaround01" animation but then the tram just sits there forever and won't go back to the other side.  I cannot interact with the terminal outside the tram either.

In GM mode I can interact with the Doodad and it will cause the turnaround animation on the tracks but it won't make the tram move.
