### ISSUE TITLE
Guild Perks Request

### ISSUE THREAD

**Issue by Nimsy** [WoWManiaUK/Redemption#1625]
In Cataclysm wow released Guild perks which were gained through achievements guilds completed. It helped motivate people to do old content and such as a guild. I was wondering if in time you guys could add it as a feature in wow mania. I feel it would be a fun exciting way to bring back some life into older content in the game.
Perks such as:
http://www.wowhead.com/achievement=4912
http://www.wowhead.com/spell=83958
http://www.wowhead.com/achievement=5201
http://www.wowhead.com/achievement=5144
http://www.wowhead.com/achievement=5015
http://www.wowhead.com/achievement=4945
http://www.wowhead.com/achievement=4943
http://www.wowhead.com/achievement=5812

You could use perks designed for the cataclysm achievments and apply them to the Lich King ones. Such as applying http://www.wowhead.com/item=71033 to http://www.wowhead.com/achievement=5022 . Or possibly  http://www.wowhead.com/spell=83951 to http://www.wowhead.com/achievement=5015 .  Also http://www.wowhead.com/spell=83944 to http://www.wowhead.com/achievement=5019. 
And http://www.wowhead.com/spell=78633 to http://www.wowhead.com/achievement=5016. 
Hopefully that helps give you an idea.I feel it would be really awesome and cool way to add new fun things to do with stuff we already have available. :)

**Comment by fvicaria** [comment]
I will keep this in mind for the next client update. Thanks.
