### ISSUE TITLE
authenticator bug

### ISSUE THREAD

**Issue by boohe91** [WoWManiaUK/Redemption#1627]
i know i have sent an email to support about my accounts but i thought i would let you know what i did to see if it dose it to you before it happens to another person

step 1 
type the code in to the app
step 2 
turn off time based switching
step 3 
try and log into your account and enter the authenticator code 

if it dose the same as what it did to me u wont be able to get into your in-game account at all

**Comment by fvicaria** [comment]
Not the place for this kind of thing.

**Comment by boohe91** [comment]
ok sorry

**Comment by fvicaria** [comment]
The Authenticator is a third party tool, not ours. Send an email to support and we will clear it for you.

**Comment by boohe91** [comment]
i have i just thought ide give u a heads up
