### ISSUE TITLE
[mount] cindermane charger and celestial steed

### ISSUE THREAD

**Issue by Ezzraeil** [WoWManiaUK/Redemption#1628]
There are some mounts that should be work as ground mount and flying mount together like "Cindermane Charger" or " Celestial Steed" , i mean it should be possible to use them as flying mount and also as ground mount in Dalaran or any capital cities, but they count just as flying mount and its not possible to use them as ground mount in Dalaran or capital cities.

**Comment by fvicaria** [comment]
As is. This is an unfortunate side-effect of making the mount available to fly in Azeroth.
