### ISSUE TITLE
[Quest] Guided by Honor

### ISSUE THREAD

**Issue by ManiaLightmare** [WoWManiaUK/Redemption#1629]
[Quest](http://www.wow-mania.com/armory/?quest=11289)

After completion of the quest, [Cleric of the Crusade](http://www.wow-mania.com/armory/?npc=24233) should reveal himself as Tirion Fordring and a dialog ensues.

While not necessary for quest progression, it gives story line details and explains how he gets Ashbringer.

Ref: [Link](http://wowwiki.wikia.com/wiki/Quest:Guided_by_Honor)

**Comment by fvicaria** [comment]
I can't see any of that here
https://www.wowhead.com/quest=11289/guided-by-honor#videos:id=85620

Can you show me where you saw this dialog.

**Comment by fvicaria** [comment]
Found it.
https://www.wowhead.com/quest=11289/guided-by-honor#comments:id=329409

**Comment by ManiaLightmare** [comment]
Also, if you watch the second video (GitGud), just before it ends, you see the "Cleric" start the dialog.

**Comment by fvicaria** [comment]
Since there has been no more progress on this quest and it is completable I will close it.
If I ever get more info I will add to it.

**Comment by ManiaLightmare** [comment]
Not sure if it would be of any help, but the [comment here](http://www.wowhead.com/npc=24233/cleric-of-the-crusade#comments:id=364857) lists the dialog that would ensue after turning in the quest.

Based on [this bug](https://github.com/TrinityCore/TrinityCore/issues/16855) with TrinityCore it appears it might be missing for everyone.  It does however list the table entries that contain the dialog which may also be helpful to an ambitious dev.
