### ISSUE TITLE
[Quest] The Drakkensryd

### ISSUE THREAD

**Issue by squalllh1989** [WoWManiaUK/Redemption#1630]
This quest (http://www.wow-mania.com/armory/?quest=12886) is the part of the quest chain that you must do to gain rep with The son of hodir, a faction sell all the best shoulder enchantment for pve in the game, if you are not an inscription.
- What should happen: you use the Hyldnir Harpoon (http://www.wow-mania.com/armory/?item=41058) provided to target a Hyldsmeet Proto-Drake(http://www.wow-mania.com/armory/?npc=29625) and use your harpoon. This will launch you to the back of the drake, where you and its rider,  a Hyldsmeet Drakerider(http://www.wow-mania.com/armory/?npc=29694) will fight. When you defeat your opponent, she die and fall. You continue jumping from dragon to dragon using until you've killed all ten, and when you're done, use your harpoon on a Column Ornament(http://www.wow-mania.com/armory/?npc=29754). That will get you into the temple itself, so you can turn in to Thorim.
- What is happening: there is no Hyldsmeet Proto-Drake fly arround, the Hyldsmeet Drakerider keep falling from the air to the ground and fade out, so the quest can't be done.
![wowscrnshot_091717_175842](https://user-images.githubusercontent.com/27235989/30520204-1636773e-9bd3-11e7-93be-575e26f29c81.jpg)
![wowscrnshot_091717_175843](https://user-images.githubusercontent.com/27235989/30520205-19807c5a-9bd3-11e7-8719-28413f585d5f.jpg)

This quest seem to be newly bugged, as i have done this normally before on at least 4 diffent char.

**Comment by fvicaria** [comment]
Please delete cache, and ask a GM to remove the quest from you. This has been fixed and is working.

**Comment by fvicaria** [comment]
I confirmed it. I will check why this is back

**Comment by fvicaria** [comment]
![image](https://user-images.githubusercontent.com/9414661/30520295-7d6bea1e-9ba2-11e7-8b7b-0219d9df151a.png)

**Comment by squalllh1989** [comment]
Still got some fall down happen and some of the Hyldsmeet Drakerider are bugged out evade everything , but it's working now, quest is doable again.
