### ISSUE TITLE
1ste boss Blackwing Lair isn't killable

### ISSUE THREAD

**Issue by Pitmaster** [WoWManiaUK/Redemption#1631]
There are no links to the Blackwing Lair in Wow-Mania Armory.
I want to do http://www.wow-mania.com/armory/?quest=8288 and therefor have to kill http://www.wow-mania.com/armory/?npc=12017. But the first boss in this raid isn't killable. He stops at 1/449k.

So, I can't take this quest. But I need it to get http://wow-mania.com/armory/?item=21025

Help!
Pitmaster

**Comment by captainloozer** [comment]
Hi Pitmaster, and thank you for your report.

Are you correctly using the orb to mindcontroll Razorgore and destroy the eggs first?
