### ISSUE TITLE
hunter pet issue

### ISSUE THREAD

**Issue by huntrezz** [WoWManiaUK/Redemption#1632]
I took my pet to icc  to use for a raid it was the elite cat from scholar basin he got glitched on the boat  boss  in icc  could not  make him follow me  nor could I dismiss him went half instance with him not there I recalled him later on and he showed up after icc put him in stables in dalaran  went on my way  he disappeared this has happened two times before this is third time I put him in stables and he disappears  please help sick of  faming days to reget this pet :) ty

**Comment by squalllh1989** [comment]
This problem, for short, is the disapear of hunter pet randomly, especially when you store exotic pet in stables, respect to other spec than BM. It happen long before and not related to icc.

**Comment by fvicaria** [comment]
This is a very strange and random issue. I do not know how to fix it at this time.

**Comment by Critias14** [comment]
Yes, the losing of the pet is unrelated to the ICC 3rd boss. My tip is to enter the ship on mount, when the ship takes off your pet will glide away.. when the battle starts you should be able to call him again. Another thing you can do is to dismiss pet for the 3rd boss and just call him again after. 

For stable issues i recommend to be very carefull when changing speccs. Also id recommend keeping 1 spot open in your stables, so you can manualy put 1 pet in the empty slot and take the pet out that you want to use. 

Hope this helps ;)

**Comment by fvicaria** [comment]
This has been fixed partially on last build.
