### ISSUE TITLE
ZUL AMAN MOUNT

### ISSUE THREAD

**Issue by Tjckto** [WoWManiaUK/Redemption#1633]
Mount simply dosen't drop.

**Comment by squalllh1989** [comment]
There is no mount drop from Zul'Aman in WOTLK, the only thing you can get from there is a companion, Mojo (http://www.wowhead.com/item=33993/mojo), please check your information before report.

**Comment by Dranah** [comment]
pretty sure there's that warbear from timed run on WOTLK as well... it's only meant to drop from the bonus cache if you complete timed run tho

**Comment by fvicaria** [comment]
Can you send a link to a reference that confirms that?

**Comment by squalllh1989** [comment]
@Dranah no it's not, in WOTLK there is no mount there, priority to patch 3.0, "Amani War Bear" is avaible by doing the timed event of zul'aman, and later in cata,  "Amani Battle Bear" is added when Zul'Aman was revamped for Cataclysm.
http://www.wowhead.com/item=33809/amani-war-bear
Reference: https://wow.gamepedia.com/Amani_War_Bear
http://www.warcraftmounts.com/mounts/amaniwarbear.php
About the timed event: https://wow.gamepedia.com/Zul%27Aman_timed_event
So, again, there is no mount from zul'aman in WOTLK, double check your information before please.
