### ISSUE TITLE
NPC - High Captain Justin Bartlett missing

### ISSUE THREAD

**Issue by jrbowler** [WoWManiaUK/Redemption#1634]
This NPC should be inside the main room of the Skybreaker in Icecrown, but he is not. Reported to a GM and he said he could not teleport to the NPC, but he does exist somewhere in the game. His proposition was that the NPC got stuck somewhere while the Skybreaker patrolled.

NPC: 
http://www.wowhead.com/npc=30344/high-captain-justin-bartlett

Quests affected at this time for me: 
http://www.wowhead.com/quest=13225/the-skybreaker
http://www.wowhead.com/quest=13231/the-broken-front

**Comment by fvicaria** [comment]
SHould be OK after the restart.
