### ISSUE TITLE
Authenticator Ignored

### ISSUE THREAD

**Issue by ManiaLightmare** [WoWManiaUK/Redemption#1635]
The latest client (2.1.0) seems to ignore the authenticator being enabled.

It let me log in leaving it blank as well as putting just "123" in the client field.

Normally, if you leave it empty and try to log in, a second prompt comes up asking for the authenticator code.  If you put a bad value in, it will fail authentication.

Edit: For clarity, the second prompt never comes up if you leave the authenticator field blank, nor does it care if you put a bad value in.  If your user/pwd are good, it authenticates you.

**Comment by ManiaLightmare** [comment]
This may be related to a different issue where I keep "losing" the fact there is an authenticator attached to my account.

See my [forum post](https://www.wow-mania.com/forum/viewtopic.php?f=18&t=1024&p=3211#p3211)

If you'd rather, this can be closed and a different bug opened; however, my client does have the authenticator field showing it allows me to log in without it.

[Authenticator Field Showing in Client](https://ibb.co/j1q64Q)

[Authenticated without adding code](https://ibb.co/dPQOjQ)

**Comment by fvicaria** [comment]
Again this is a third party app. If you do not like it just don't use it.
