### ISSUE TITLE
Gnomergan Teleport Bug

### ISSUE THREAD

**Issue by Voormas2** [WoWManiaUK/Redemption#1636]
The Teleport to Gnomergan in Booty Bay does not work. Me and my friend both got the Goblin Transponder but upon entering the portal nothing happened. Several people in World Chat commented that it used to work, so it seems to be the result of a later build. 

http://www.wowhead.com/item=9173/goblin-transponder
![transponder](https://user-images.githubusercontent.com/32066544/30544459-d6153532-9c86-11e7-9b08-10573aaedbe9.png)

**Comment by captainloozer** [comment]
In order for the transponder to work, the player must have first completed 

http://www.wow-mania.com/armory/?quest=2841

Which opens this quest chain:

http://www.wow-mania.com/armory/?quest=2842
http://www.wow-mania.com/armory/?quest=2843

The last quest rewards http://www.wow-mania.com/armory/?item=9173

Upon completing all three quests, I received the transponder and entered the teleporter but it did not take me anywhere.  Confirmed in dev.

The Transpolyporter [Object ID: 142172] for Booty Bay.

The Gnomeregan Train Depot Transpolyporter [Object ID: 142176]

**Comment by fvicaria** [comment]
Fixed in Redemption.
