### ISSUE TITLE
[Quest] Taretha's Diversion

### ISSUE THREAD

**Issue by elzix** [WoWManiaUK/Redemption#1637]
I am at Thrall, but cannot turn in quest: http://www.wow-mania.com/armory/?quest=10283

Quest Log shows complete: http://jmp.sh/RPu5M1E

No quest to turn in: http://jmp.sh/9h0Gcjo

**Comment by elzix** [comment]
Running out of the keep: http://jmp.sh/jW7c25n

**Comment by elzix** [comment]
Thralls Quest: Escape from Durnholde: https://www.wow-mania.com/armory/?quest=10284

Quest Log shows complete, but no quest to turn in: http://jmp.sh/QVFPY8H

**Comment by fvicaria** [comment]
Something wrong here.. You reporting one quest and then complaining that the other one further in line does not work. How did you get to the next one then? They are a quest line.
I am pretty sure Escape from Durnholde works. You have to stay close to him and defend him from other NPCs.
Please clean up your comments and description as it is I have no idea of what is working and where exactly is failing.

**Comment by fvicaria** [comment]
I have done all the quests in the order and they all worked fine.

**Comment by fvicaria** [comment]
I found an issue in the sequence. It will be fixed in next update.
