### ISSUE TITLE
Pathing Issue

### ISSUE THREAD

**Issue by ManiaLightmare** [WoWManiaUK/Redemption#1638]
I'm not 100% sure "Pathing" is the right classification so feel free to adjust it to be more clear.

When you agro a mob, if you move towards them but stop before he gets to you, the mob will run through you and end up behind you.  I tested that it does not occur if you stand still or strafe to one side or the other.  Only forward.

**Steps to reproduce:**
Stand at range of a mob.  
Use some ability to agro the mob.
Once he starts running, move forward about 10-25% of the distance between you and the mob (I don't have an exact distance, but it doesn't seem to occur if you just walk a couple steps and stop)
Stop moving before the mob reaches you and wait
Once the mob gets to you, he'll run through you.

Other things to note:
The type of mob doesn't seem relevant.  Beasts, undead and humanoid all did the same thing.
Doesn't seem to matter if you are casting or hitting him with melee attacks as he passes through you.
Terrain didn't matter.  I could reproduce on the flat ice in Kaskala as well as uneven areas.
I have noticed if I just move a few steps, sometimes the mob will stop on top of you.

**Comment by fvicaria** [comment]
Is is.

**Comment by fvicaria** [comment]
Changed this to 0.5m.
Let me know if it improves.

**Comment by ManiaLightmare** [comment]
Is this something that requires a new patch or server restart I'd need to wait to test it?

**Comment by fvicaria** [comment]
Yes, it needed a restart which happened this morning.

**Comment by ManiaLightmare** [comment]
It does seem better.  Still happens, but I've noticed its harder to reproduce.

[Example of where the mob ends up](https://ibb.co/k0vTm5)
Reproduction Steps:  
Pulled from max lightening bolt range (30 yrds for this toon).  
Once the bolt hit and mob started running, I ran forward about 5 steps and stopped and waited for mob to stop moving. 
Grabbed screenshot.
