### ISSUE TITLE
Tamed Ancient Core Hound Pets

### ISSUE THREAD

**Issue by ManiaLightmare** [WoWManiaUK/Redemption#1639]
Couple things with the core hound as a hunter pet. 

1.  Core hound does not seem to scale in size properly.  At level 80 he is about around 50% the size of other pets.  Applies to any of the variety of core hound skins.
[Level 80 Core hound pet](https://ibb.co/bFq14Q)
[Level 80 Core hound pet alt skin](https://ibb.co/jxjNB5)
[Level 80 Wolf pet](https://ibb.co/gTBPPQ)
[Level 80 Bear pet](https://ibb.co/i6iFW5)

2.  [Ancient Core Hound](http://www.wow-mania.com/armory/?npc=11673) seems to change skins when you enter the [Argent Vangard](http://wowwiki.wikia.com/wiki/Argent_Vanguard)/Valley of Echoes area of Icecrown.  He takes on the appearance of like the green skinned core hound like [Uvuros](http://www.wow-mania.com/armory/?npc=21102).  Does not seem to affect a tamed [The Kurken](http://www.wow-mania.com/armory/?npc=17447).  

[Appearance just before entering the Argent Vanguard](https://ibb.co/mG8ojQ)
[Appearance once in The Argent Vanguard and Valley of Echos](https://ibb.co/nrKuPQ)

**Comment by fvicaria** [comment]
This probably will require client update and we will not do it at this point.

**Comment by Rushor** [comment]
case CREATURE_FAMILY_CHIMAERA:
            case CREATURE_FAMILY_DEVILSAUR:
            case CREATURE_FAMILY_SPIDER:
            case CREATURE_FAMILY_CORE_HOUND:
            case CREATURE_FAMILY_RHINO:

are bigger now
