### ISSUE TITLE
[Spell] Glyph of Power Word: Shield

### ISSUE THREAD

**Issue by Nephylia** [WoWManiaUK/Redemption#1641]
Spell: http://www.wow-mania.com/armory/?spell=55672
Currently healing for the half amount of what it should.
Proof:
![wowscrnshot_091917_123942](https://user-images.githubusercontent.com/29392650/30588627-c09a6a0e-9d37-11e7-8fc3-2c9840c4bc01.jpg)
According to the pws Formula my shields with 3989 SP and 2nd T10 bonus should absorb:
((2230+(3989x(0,8068+0,4)))x1,05x1,04x1,15)+5%=9288,049
According to that the glyph should be healing for 1857,6 (20% of 9288)
At the moment the glyph is absorbing 13.77% instead of 20%.
The PW:S Absorb is correct, so that is only the glyph.

**Comment by fvicaria** [comment]
NO work will be done on this anymore.
It is what it is now.

**Comment by Nephylia** [comment]
Are you kidding??? So u don't wanna properly working classes, But u wanna have sh*tty custom mounts??? What is this? I didn't check it yet, but i am pretty sure it is also affecting pvp aswell which makes it a disadvantaged class aswell.

**Comment by fvicaria** [comment]
No I am no kidding. A lot of work was put on it already and it works reasonably way.  
Yes, it is Blizzlike not Blizzard. We have done what we can do for now.

**Comment by Nephylia** [comment]
No you didn't do all you can, u just declined without even trying. I didn't ask you to change anything on PW:S, which might be really hard to fix. I just asked to fix the glyph, that's it.

**Comment by fvicaria** [comment]
Stop talking out of your ass please. We have been working for months on this. Feel free to find a better server.

**Comment by Nephylia** [comment]
wow so infantile...
i just don't get what's so hard to just look into it. u don't even have to set it on prio, i know there are more important bugs out there, like warrior tier 10, but just fix it one day....
