### ISSUE TITLE
[Quest] Springing the Trap

### ISSUE THREAD

**Issue by cathyr1** [WoWManiaUK/Redemption#1642]
Hello! Please check this quest http://www.wow-mania.com/armory/?quest=11969. I´ve tried it 2 times but in both attempts not succesfully completed. I summoned Keristrasza, she takes me on her back and fly to a position where Malygos freezes her. After that both dissapeared but quest is not completed.

**Comment by cathyr1** [comment]
closing - 3rd attempt was successful. You probably have to stay just under the flying Malygos to get it.

**Comment by fvicaria** [comment]
Hi there,
Check here https://github.com/WoWManiaUK/Redemption/issues/593
This issue has been logged multiple times. You are right, there is a sweet spot to stay to get credit. :P
