### ISSUE TITLE
[Dungeon] Zul'aman

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#1644]
Hello,
Issue1:
I'm not sure what type of bug this qualifies as, but upon engaging either 
Hex lord Malacrass(http://wowwiki.wikia.com/wiki/Hex_Lord_Malacrass_(original)) 
or Zul'jin(http://wowwiki.wikia.com/wiki/Zul%27jin_(tactics)) 
in Zul'aman(http://wowwiki.wikia.com/wiki/Zul%27Aman_(original))
there seems to be an issue with the encounter not resetting. The boss leaves combat, returns to his place, but if someone releases , teleports out or the raid wipes, and tries to go back inside, they get a message "Unable to zone in when an encounter is still in progress." 

I don't know if the other bosses trigger a similar issue because I didn't try re-entering raid after those. The bug is gone after some hours, soft reset I presume, but that takes ages and you cannot continue the instance until then.

Issue2:

Hex Lord Malacrass(http://wowwiki.wikia.com/wiki/Hex_Lord_Malacrass_(original)) positioning is incorrect, he should stand together with his adds at the back of the room, instead of standing with the berserker trash adds in the center. This leads to extra trash mob engaging together with the boss and his own adds.

**Comment by fvicaria** [comment]
Can someone test this, please.

**Comment by Dranah** [comment]
I dunno what you mean by speed, but my raid was level 70ish, nobody did more dps than is intended for this content. If that helps.

**Comment by Hulkster-WowMania** [comment]
Hex Lord Positioning is confirmed.  As shown, he is standing behind one of the berserkers but should be standing int he back with the other adds.

![image](https://user-images.githubusercontent.com/9828794/30655843-bedbb482-9df7-11e7-8ccc-7d68e8ad1e5c.png)
![image](https://user-images.githubusercontent.com/9828794/30655897-e6d1d71e-9df7-11e7-8b42-206207246478.png)


He should be here, as show

![image](https://user-images.githubusercontent.com/9828794/30655908-ed6b7044-9df7-11e7-967b-c869a180258e.png)

**Comment by Hulkster-WowMania** [comment]
I can also confirm that after engaging him and dying, releasing, and running back in has been fixed.  I was able to enter the instance again without any error.

**Comment by Hulkster-WowMania** [comment]
I did not experience the issue where I could not get back into the instance.  Fight resets properly so it was either fixed before I could test or I cannot reproduce.  

The only other issue I could find other than his positioning was his weapon model.  I will try to find out what the resource is and supply the ID with a link.

![image](https://user-images.githubusercontent.com/9828794/30659395-46001ee8-9e03-11e7-9ab4-4be06533ac7a.png)

**Comment by Hulkster-WowMania** [comment]
![image](https://user-images.githubusercontent.com/9828794/30661179-c7095126-9e08-11e7-8af3-709ee48ea452.png)
