### ISSUE TITLE
Invisible Barrier

### ISSUE THREAD

**Issue by ManiaLightmare** [WoWManiaUK/Redemption#1649]
There seems to be an invisible barrier right outside Stormwind's Mage Tower that blocks taller characters (Draeni on Elekks).  If you try to ride down the spiral ramp, or up to the entryway you will be blocked as though there was an archway there.  Strangely if you jump while moving forward, you can slip through it.  It also does not block if you dismount and walk.  

[Location](https://ibb.co/gDbkzQ)

Nothing critical.  You can dismount and go through or wait to mount until you are past it.

**Comment by fvicaria** [comment]
THis is just a quirk in the map. Absolutely nothing we can do about it.

@ManiaLightmare If you would like to join our test team let me know. We offer some incentives.
Just send me or Shadowz a message on skype or email.
