### ISSUE TITLE
Culling of Stratholme bonus boss despawns while looting

### ISSUE THREAD

**Issue by ClavosThePally** [WoWManiaUK/Redemption#1650]
So, we've last sunday done the culling of stratholme on our alt characters.
This was done without the LFG tool, we walked over manually.

Due to this being primarely alts, we weren't as fast as usual, but eventually, we reached the optional boss just in time (we left arthas back in the middle section where he tells us to rest)

After we barely beat the optional boss, we loot him, however, during this time, on voicechat a discussion took place on who should roll for it and who had it last time, I was the last one to click.

During this time as everone clicked need or pass, enough time passed for the optional boss to despawn (which you can see in the screenshot after Shadezx rolled need).
Due to me clicking need so late, nobody got the bonus loot due to the boss being forced to despawn after we already killed him. (my click never registered)

At this point I am not even asking for a compensation for one of us to actually get it after all, but I am asking for this bug to be resolved.

Below is a screenshot showing the chatlog with the GM, our chat log showing us earning the achievement and clicking need plus my achievement on the bottom of the screen as proof.
(pay no attention to the chat itself, Shadezx was the only one not talking on voicechat so he had to type ingame, and as we were waiting to see if the issue would resolve itself, we started being silly in /s)

![wowscrnshot_091817_000659](https://user-images.githubusercontent.com/26167121/30642150-061c112c-9e0a-11e7-972f-ad9e490fe652.jpg)

**Comment by fvicaria** [comment]
Send me the link to wowhead.com for the boss and I will check. You have a short time to loot it but I will check if it is correct or not.

**Comment by ClavosThePally** [comment]
http://www.wowhead.com/npc=32273/infinite-corruptor
Here you go

**Comment by ClavosThePally** [comment]
In response to your edit, a corpse saying "The process is finally complete! My work here is done," and then despawning (still as corpse) while the dragon he was influencing already despawned from us freeing him but he is considered corrupted sounds like a bug to me.

**Comment by fvicaria** [comment]
Corpse decay time is 5min which is correct. I will check the script for any other issue.

**Comment by Hulkster-WowMania** [comment]
Can confirm the 5 minute despawn timer on corpses does not apply here.  I captured my encounter where I pulled with one minute left.  Killed him with seconds left on the timer.  Had time to check the corpse and once the timer was over the corpse despawned, taking the loot with it.

https://youtu.be/dvhE_1gGvM4

**Comment by Hulkster-WowMania** [comment]
Confirmed fixed in dev.  As shown in the video, boss was killed and looted prior to the timer completing.  After the timer was done, the loot roll stayed up and the corpse was still there.  After the roll, I was awarded the mount.

https://youtu.be/E0OPaWeBwPQ
