### ISSUE TITLE
Warlock pets.

### ISSUE THREAD

**Issue by Braytonx** [WoWManiaUK/Redemption#1652]
Felhunter:
The Felhunters stats aren't correct this is what it has on WoW-Mania: https://imgur.com/a/djsi0 .
This is what it should be (taken from Gamer-District where the pet stats and damage are correct): https://imgur.com/a/j2HOX .

The Felhunters shadowbite here says it has a 6 sec Cooldown http://www.wow-mania.com/armory/?spell=54053.
On Wowhead, WoWwiki and wow.gamepedia it shows it has no Cooldown and just a GCD, in neither of the sites it shows any changes to the Cooldown on the spell: http://www.wowhead.com/spell=54049/shadow-bite .

Felguard:
The stats of the felhunter aren't right wich results in really low pet damage. This are the current stats the felguard has on WoW-Mania: https://imgur.com/a/wUl6o.

This are the stats the felguard should have (taken from Gamer-District where the pet stats and damage are correct): https://imgur.com/a/Ga40C.

**Comment by Dranah** [comment]
The first and the third paragraph is legit issue on like 90% of privates, 
however the middle section (felhunter shadow bite) is not broken, the wowhead spell is simply outdated... the 6sec cd version is the original and intended WOTLK version of the spell.
With the affliction talent "improved felhunter" 2/2, that cooldown is reduced to 2seconds, which allows the pet for an affliction warlock to functionally spam the ability.

**Comment by fvicaria** [comment]
Sorry for just closing this. We are working on the issue. 
Next time please do not reference other servers here. That is meaningless to us.

**Comment by fvicaria** [comment]
Should be fixed now.
