### ISSUE TITLE
not being able to queue and/or join wintergrasp

### ISSUE THREAD

**Issue by Beefface** [WoWManiaUK/Redemption#1653]
as the title says, sometimes you can't queue and it works (without being in the raid party) and sometimes it doesn't work and you can't rank up or get rewards. other times you can queue and again it works or doesn't work randomly. Couple of times i had i joined the raid group and a second later i automatically left the raid group for whatever reason. a lot of people seem to be having this problem.

**Comment by squalllh1989** [comment]
Yeah currently the join of WG is weird, sometime i can join the raid normally, sometime when i speak to the mage in dalaran to queue for WG, it didn't do anything, and when i was do something else, i got a pop up ask if i wanna join WG queue and the battle, and i got WG status on how many seige ally and horde got in WG, how long till the battle end while i didn't join the battle and are far away from WG. A lot of people when join the battle, didn't get into the raid, and if they got invited by the current WG raid leader into the raid or not, at the end of the battle, they didn't have the reward.

**Comment by fvicaria** [comment]
This is an area issue. I will correct in the next update.
