### ISSUE TITLE
Phase merge at the Argent Vanguard

### ISSUE THREAD

**Issue by squalllh1989** [WoWManiaUK/Redemption#1654]
At the argent vanguard, there should be nerubian mob arround as the objective of the quest "Curing The Incurable" (http://www.wow-mania.com/armory/?quest=13040) and "Defending The Vanguard" (http://www.wow-mania.com/armory/?quest=13039), but they didn't, the phase their is now have a bunch of nerubian and dragon frost brood that spawn extreamly quick, and is the objective of "The Last Line Of Defense"(http://www.wow-mania.com/armory/?quest=13086) instead. This phase should only be happen when the player accept the quest "The Last Line Of Defense", not before they accept it and should disapear after they completed it and turn it in.
In my screenshot below you should see, my character just start the argent crusader quest line, with 3 quest "Curing The Incurable", "Defending The Vanguard" and "Scourge Tactics" (http://www.wow-mania.com/armory/?quest=13008) but the phase arround got a swarm of nerubian trash and frost brood fly arround. I tested try to kill those trash, but they spawn extreamly fast and didn't count for the quest i'm currently do.
![wowscrnshot_092117_030807](https://user-images.githubusercontent.com/27235989/30668979-d3833d58-9e86-11e7-9d8b-255a936e78ea.jpg)

**Comment by squalllh1989** [comment]
The same problem also affect the quest "The Restless Dead" (http://www.wow-mania.com/armory/?quest=13110), "The Purging Of Scourgeholme" (http://www.wow-mania.com/armory/?quest=13118) and "The Scourgestone" (http://www.wow-mania.com/armory/?quest=13122).
- Normally: You will go kill a "Reanimated Crusader" (http://www.wow-mania.com/armory/?npc=30202) which drop "Scourgestone" (http://www.wow-mania.com/armory/?item=43169) and then use the Holy Water (http://www.wow-mania.com/armory/?item=43153) on their corpse, this will give you credit for all 3 quest, 100% get credit for a kill, 100% get a Scourgestone drop, and 100% useable item on their corpse to get credit without any chance of fail, miss.
- The way it is right now: there are double the number of "Reanimated Crusader" there (normally they go alone, now they are 2 each pack), 1 of them will give the credit for the kill, drop the stone, and when you use holy water on the corpse leave behind after kill it, you get the credit for your quest -> which lead me to belive this is the right mob (http://www.wow-mania.com/armory/?npc=30202), but the other didn't give out credit for the kill, didn't drop the stone, and when you use holy water on it corpse, you didn't get credit -> which lead me to belive this is another mob (http://www.wow-mania.com/armory/?npc=31043). These 2 mob got the same name, but diffent ID, diffent drop.
What i think here is: there is 2 phase here, 
+The first one is there when you didn't complete the quest "The Last Line Of Defense"(http://www.wow-mania.com/armory/?quest=13086) so you can't get "The Restless Dead", "The Purging Of Scourgeholme" and "The Scourgestone", so those mob won't give you anything to do those quest.
+The second one is when you completed the quest "The Last Line Of Defense" so they will give you credit for those quest.
Finally, all of this lead me to think that the problem here is the merge of 2 diffent phase, just like the problem that is happening in Ruby Santum now which i reported [here](https://github.com/WoWManiaUK/Redemption/issues/1643).

**Comment by fvicaria** [comment]
This is a map and phase issue. Players get into it by missing quests that are not necessarily needed but essential to put them in the correct phase.
I will try to improve this.
