### ISSUE TITLE
[Quest] Flight of the Wintergarde Defender

### ISSUE THREAD

**Issue by Karlusdark** [WoWManiaUK/Redemption#1656]
The quest "Flight of the Wintergarde Defender" is practically impossible so complete because the Helpless villagers that need to be rescued phase out when I get near them in the Carrion Fields, making me unable to pick them up. I was told by the GM to open a ticket here although it has been opened before.

**Comment by fvicaria** [comment]
You are missing a quest. Search here. This has been explained a few times.

**Comment by fvicaria** [comment]
This is a map and phase issue. Players get into it by missing quests that are not necessarily needed but essential to put them in the correct phase.

**Comment by Erikud** [comment]
Could you please link where is explained the solution?
