### ISSUE TITLE
Return of the High Chief

### ISSUE THREAD

**Issue by Shadowclaw95** [WoWManiaUK/Redemption#1657]
Greetings. I probably found another bugged quest and this quest is "Return of the High Chief" at Icemist Village in Dragonblight. To complete the quest you have to kill a certain NPC (Anub'et'kan) and grab a Piece of husk. After killing him, I click ok the corpse to loot the quest item and it says "The item is already being used" and prevents me from looting.

**Comment by fvicaria** [comment]
Can someone confirm this in dev. I am pretty sure it is a case of a double-click which locks the loot.

**Comment by Hulkster-WowMania** [comment]
Working fine on dev.  Video of me doing the quest below:

https://youtu.be/vrYTbHFC2JY
