### ISSUE TITLE
Use of trinket in Macro

### ISSUE THREAD

**Issue by ManiaLightmare** [WoWManiaUK/Redemption#1659]
If you create a macro to use a skill and trinket together, the trinket will not get used and the UI reports "Interrupted"

I test with different classes with the same results.  If you have a target, the cast seems to interrupt the trinket use as though it has a cast time.  If you do not have a target, the trinket is used normally.

Tested separately with:  
Hunter:
[Foresight's Anticipation](http://www.wow-mania.com/armory/?item=38070)
Druid
[Vengeance of the Illidari](http://www.wow-mania.com/armory/?item=28040)
[Will of the Red Dragonflight](http://www.wow-mania.com/armory/?item=38073)

**A few simplified examples:**
#showtooltip Steady Shot
/use 13
/cast Steady Shot

#showtooltip Steady Shot
/use Foresight's Anticipation
/cast Steady Shot

#showtooltip Wrath
/use 13
/cast Steady Shot

**Comment by Hulkster-WowMania** [comment]
Hi @ManiaLightmare, and thank you for your report.  

I personally use a similar macro and I don't have this problem.  I will test your specific scenario in case it's an issue with a particular class, spell, or trinket.  Below is the one I use.  (Will pop any trinkets you have on CD, use wings on CD, and also disables error sounds and text for the duration of the macro.

#showtooltip Judgement of Light
/console Sound_EnableSFX 0
/use 14
/use 13
/cast Avenging Wrath
/cast Judgement of Light
/console Sound_EnableSFX 1
/script UIErrorsFrame:Hide()

**Comment by fvicaria** [comment]
As is. Sorry but since there are workarounds for every macro option I will not spend time on it.
This is interpreted by the client itself and not the server. Remember that this is a client written in 2010 so only macros that worked then will work now.

**Comment by ManiaLightmare** [comment]
I understand not wanting to work on it. 
 /use in macros was supported in vanilla.
I'm fairly sure it worked before too which is why I reported it.

**Comment by fvicaria** [comment]
What I am trying to say is that macros are translated in the client itself. 
Even if there are certain combinations that fail I will not be able to fix it.
Not that I don't want to, but simply not possible.

Try different sequence, or "do nothing" steps in between. You may make it work.

**Comment by ManiaLightmare** [comment]
The macro Hulkster posted is pretty much exactly what I would use.  If it's working for them, it must be specific to me.  Double checked it wasn't addons by removing all of them.  

If I get some time today, I'll try pulling down a fresh copy of the client.  Maybe something got out of whack.

**Comment by ManiaLightmare** [comment]
Update:  Pulled a fresh client.  Same issue.  Even with a fresh macro.
/use 13
/cast Wrath

The only thing that works is I can cast an instant spell and then /use a trinket.  Doesn't help for anything with a cast time though and you lose the benefit of the trinket buff on the first cast.

Not sure what to make of it, but I'll just skip macros with trinkets.
