### ISSUE TITLE
[Quest] The Chain Gun And You

### ISSUE THREAD

**Issue by Karlusdark** [WoWManiaUK/Redemption#1660]
For the quest The Chain Gun And You [The Chain Gun And You](http://www.wowhead.com/quest=12457/the-chain-gun-and-you) you are instructed to rescue 8 [Injured 7th legion soldiers](http://www.wowhead.com/npc=27788/injured-7th-legion-soldier) using a [7th Legion Chain Gun](http://www.wowhead.com/npc=27714/7th-legion-chain-gun). There is an issue where when I try to enter the Chain Gun in order to save the soldiers it just make a buff called "Chain Gun Commander" (couldn't find anything about this buff) but nothing else, the spell bars don't change to the cannon ones an there is no vehicle bar present, just the buff.

**Comment by fvicaria** [comment]
Should be OK after restart.
