### ISSUE TITLE
Val'anyr Hammer of Kings

### ISSUE THREAD

**Issue by daddy0217** [WoWManiaUK/Redemption#1661]
Unless I unequip and re-equip the weapon, the "Blessing of Ancient Kings" bubble proc doesn't happen. This has only been this way for a short amount of time.

**Comment by Hulkster-WowMania** [comment]
Hi @daddy0217 and thank you for your report. 

http://www.wowhead.com/spell=64415/valanyr-hammer-of-ancient-kings-equip-effect

Proc chance should be 10%.  Recording video proof now.

**Comment by Hulkster-WowMania** [comment]
Hi @daddy0217 and thank you for your report. 

As shown in the video below, once Val'anyr has proc'd the internal cooldown is not reset until the weapon is unequipped then re-equipped.  3 minutes of continuous flash of light, there wasn't a single proc.  At 3 minutes into the video the weapon was taken off, put back on, and then immediately proc'd once healing started again.  Afterwards, not a single one.

https://youtu.be/n-MabKmsz_o

Item in question:  http://www.wow-mania.com/armory/?item=46017
Spell aura from proc - http://www.wow-mania.com/armory/?spell=64415

Proc chance should be 10%.

**Comment by BatuMania** [comment]
The absorb of it is also bugged. This is the same issue as previous Disc priests.

If the damage surpasses the amount of the shield, shield will disappear and no damage will be absorbed. 

You shouldnt have to be re-equipping the weapon however to reset its internal cooldown.

**Comment by fvicaria** [comment]
As is.

**Comment by Hulkster-WowMania** [comment]
@BatuMania 

That may be, but what I don't understand is why it is procs when he takes it off and puts it back on, since he was healing me, and not himself.

**Comment by BatuMania** [comment]
Yeah I just rewatched it, not sure honestly maybe from his trinket (Abacus). Has to be tested in a raid environment regardless.
