### ISSUE TITLE
[Spell] Shadow blast - Ahn'kahar Spell Flinger

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#1662]
Hello,
inside the dungeon, Ahn'kahet: The Old Kingdom (http://www.wowhead.com/ahnkahet-the-old-kingdom)
resides a type of mob called Ahn'kahar Spell Flinger (http://www.wowhead.com/npc=30278)
with an ability that should hit like a truck, Shadow blast (http://www.wowhead.com/spell=56698)

How it should work: it's intended to deal 65% of target's maximum health (80% on heroic) at a 6second cast time, being interruptible.
Issue: currently this ability hits for an exact amount of 43-46 damage on normal mode (i haven't tested heroic)

**Comment by Hulkster-WowMania** [comment]
Hi @Dranah  and thank you for your report.

I can confirm this.  Sometimes it seems that the shadow blast his for 25 damage.
![image](https://user-images.githubusercontent.com/9828794/30748108-d9741ebe-9f74-11e7-91bd-42b11a2e2737.png)


Sometimes it doesn't hit at all, as if he stops the cast early to start casting shadow sickle instead.
![image](https://user-images.githubusercontent.com/9828794/30748147-f6493a7e-9f74-11e7-85af-552ae3c7361a.png)

**Comment by fvicaria** [comment]
I am almost sure I will not be able to do anything about this one.
There isn't enough reliable info on the spell for 3.3.5a.

**Comment by Dranah** [comment]
I guess nobody will mourn if this stays broken, as it makes the first half of the instance laughably easy. 
It's just funny when you see the 6sec big bang cast end and you're like "oh shit..." and... bam no damage, nothing xD
Perhaps you could just increase the raw damage number, like from 45 to 4,5k so the mobs aren't completely useless. That's probably less work than working out the original script, but would more or less match the intended damage on normal version against a 10k~ish health tank.

**Comment by fvicaria** [comment]
Yes I will look into some alternatives

**Comment by fvicaria** [comment]
The workaround will just make NPC stronger. I cannot change spell.

**Comment by Hulkster-WowMania** [comment]
Heroic mode melee attacks, not catastrophic but definitely much harder hitting.  Should be fine for a heroic geared tank.

![image](https://user-images.githubusercontent.com/9828794/30775306-72fbcad2-a056-11e7-91cc-33f561153d67.png)

Normal mode hits

![image](https://user-images.githubusercontent.com/9828794/30775323-ab326276-a056-11e7-8081-4b1b17f6ce60.png)
