### ISSUE TITLE
[Quest] Assault by Air (Alliance)

### ISSUE THREAD

**Issue by ManiaLightmare** [WoWManiaUK/Redemption#1663]
[Quest](http://www.wow-mania.com/armory/?quest=13309)

At the end of the flight, you character is ejected from the plane over the [quest giver area](http://www.wow-mania.com/armory/?npc=31808).  The problem is that you don't have the parachute buff and plummet to your death.

**Comment by fvicaria** [comment]
This is probably bad timing. Try again.  It is supposed to do it near the flying ship.

**Comment by ManiaLightmare** [comment]
Happened last time I did it.  It's a daily, so I'll check tomorrow to rule out dumb luck.

**Comment by fvicaria** [comment]
Please re-test in dev.

**Comment by Hulkster-WowMania** [comment]
Confirmed, wen't ker-splat.

https://youtu.be/wHbBHFWckkk

**Comment by Hulkster-WowMania** [comment]
Confirmed fixed in dev for alliance side quest.
