### ISSUE TITLE
[Quest] Aces High!

### ISSUE THREAD

**Issue by ManiaLightmare** [WoWManiaUK/Redemption#1664]
[Quest](http://www.wow-mania.com/armory/?quest=13413)

Vehicle/Drake ability [Revivify ](http://www.wow-mania.com/armory/?spell=57090) is supposed to award a combo point and but instead clears them.  It does correctly give you a stackable buff "Revivify"

[Life Burst](http://www.wow-mania.com/armory/?spell=57143) is the heal ability that should consume the combo points.

**Comment by fvicaria** [comment]
Need to be retested in dev.

**Comment by Hulkster-WowMania** [comment]
Tested in dev, working as intended.

https://youtu.be/DyuVQ_DocEs

**Comment by fvicaria** [comment]
This is what is live in Redemption we can close this one.

**Comment by fvicaria** [comment]
Please re-test as I have cleaned up the code a bit after the fix.

**Comment by Hulkster-WowMania** [comment]
Tested again today.  Confirmed still working.

**Comment by ManiaLightmare** [comment]
Just curious if it matters that it was the quest version and not the daily.  Not sure if you get a different "vehicle" with the original quest vs the daily.
