### ISSUE TITLE
[Quest] Alpha Worg

### ISSUE THREAD

**Issue by cathyr1** [WoWManiaUK/Redemption#1665]
Hello! Please check this quest http://www.wow-mania.com/armory/?quest=11324. It seems to be bugged. The boss http://www.wow-mania.com/armory/?npc=24277 seems to be no there or we cannot see him even with eagle eyes buff. And this buff also can dissapear without posibility to refresh it.

**Comment by fvicaria** [comment]
He walk around the area, no fixed point.
![image](https://user-images.githubusercontent.com/9414661/30774404-df351910-a079-11e7-86f3-e58a761635ae.png)

**Comment by Dmw1981** [comment]
This is STILL broken
