### ISSUE TITLE
[Quest] The Clutches of Evil

### ISSUE THREAD

**Issue by cathyr1** [WoWManiaUK/Redemption#1666]
Hello. There is another bugged quest in Howling Fjord: http://www.wow-mania.com/armory/?quest=11157. This one starts a very long chain, the NPC http://www.wow-mania.com/armory/?npc=23749 should give this quest without any prequests but unfortunately this quest cannot be obtained atm. Can you please fix this? Thanks a lot.

**Comment by fvicaria** [comment]
YOu need to complete:
https://www.wowhead.com/quest=11501/news-from-the-east
and
https://www.wowhead.com/quest=11291/to-westguard-keep
before being offered this quest.
They are not part of the quest line but as always there are some quests that will open new lines for you.
