### ISSUE TITLE
[Quest] Brew of the Month Club

### ISSUE THREAD

**Issue by squalllh1989** [WoWManiaUK/Redemption#1668]
[This quest](http://www.wow-mania.com/armory/?quest=12421) is currently bugged, the end NPC: [Ray'ma <Brew of the Month Club>](http://www.wow-mania.com/armory/?npc=27489) doesn't have the option to turn in the quest.

**Comment by squalllh1989** [comment]
Hm, it seem the one being sold outside of ogrimmar is bugged, can't be turn in, you have to buy the membership form from Ray'ma himself to be able to turn in the quest

**Comment by fvicaria** [comment]
You can only buy it from Blix Fixwidget and Ray'ma.
I have tried both in Redemption and they worked.

**Comment by squalllh1989** [comment]
Well the problem is Blix Fixwidget is selling 3 diffent Brew of the Month Club submit form, i tried buy the first one, accept the quest, and can't turn it in to Ray'ma. After reported, i tried refund the item and buy it from Ray'ma, the later time it worked for me, just saying in case some one got the same problem as me.

**Comment by fvicaria** [comment]
I saw that. I will check if any of them fails and remove.
