### ISSUE TITLE
[Quest] It Goes to 11...

### ISSUE THREAD

**Issue by cathyr1** [WoWManiaUK/Redemption#1669]
Hello. There is a bug when doing quest http://www.wow-mania.com/armory/?quest=11421. This bug means the Dragonflayer Longhouse cannot be destroyed. All other buildings and mobs are completed after 1 hit but this one cannot be completed despite multiple hits from any Harpoon Gun.
![obr](https://user-images.githubusercontent.com/30184491/30782712-db598b50-a137-11e7-85c2-f41681c64561.png)

**Comment by cathyr1** [comment]
Did it at last. There should be hit just one special point in the front and bottom of the building. But it should work for any point anyway I think.

**Comment by fvicaria** [comment]
Thanks I will check.
