### ISSUE TITLE
[Quest] Anatoly Will Talk

### ISSUE THREAD

**Issue by Naigio** [WoWManiaUK/Redemption#167]
Quest: Anatoly Will Talk
As soon as I hit either the horse or Tatjana with the tranquilizer provided to me by the quest giver, she simply falls down to the floor, the horse despawns and she quickly follows, pls help.

**Comment by GMLucetta** [comment]
http://www.wow-mania.com/armory/?quest=12330

Players have to hit Tatjana (http://www.wow-mania.com/armory/?npc=27627) while she is sat on her horse (http://www.wow-mania.com/armory/?npc=27626) with a Tranquilizer Dart (http://www.wow-mania.com/armory/?item=37665) which is provided. Once Tatjana is tranquilized (http://www.wow-mania.com/armory/?npc=27632) players are supposed to get on her horse and go back to the quest giver. 

This is not working as intended. Once Tatjana or the horse are hit with the dart both of them despawn making the quest impossible to complete.

**Comment by GMLucetta** [comment]
Confirmed. I've managed to reproduce. Issue is labeled as 'Confirmed' on the Bug Tracker.

@Testers: Please add all details such as links etc.

**Comment by vikingjunior** [comment]
this is still bugged, abandoned the quest,did it again, and the horse still despawns as tatjana falls to the ground
