### ISSUE TITLE
[NPC] "Honest" Max 

### ISSUE THREAD

**Issue by ManiaLightmare** [WoWManiaUK/Redemption#1670]
["Honest" Max <Slightly Used Flying Mounts>](http://www.wow-mania.com/armory/?npc=30464)

Max does not seem to be offering a loaner amount now.  This worked prior to 2.1.x as I got one with my death knight.  
[Screenshot](https://preview.ibb.co/hCH88k/Wo_WScrn_Shot_092417_094523.jpg)

I tested with my hunter and druid, both of whom have 225 riding.

If you have expert riding skill (225), at least level 77 but not cold weather flying skill, he should have an option of "I accept".  He was added in patch 3.0.2 to allow players to continue questing in zones that require flying.

If you accept the loaner mount you will get one of the following depending on faction.
[Loaned Gryphon Reins (Alliance) ](http://www.wow-mania.com/armory/?item=44221)
or
[Loaned Wind Rider Reins (Horde)](http://www.wow-mania.com/armory/?item=44229)

I don't have a screen shot of when it worked prior to 2.1.x patch, but [here is a video](https://www.youtube.com/watch?v=IlAidK1Vvlg) someone posted from 2008 showing the additional option of "I accept"

**Comment by fvicaria** [comment]
Works fine... I tested alliance and horde in Redemption.

1. You have to have riding 225 or higher
2. You have to be 77 or higher
and
3. You cannot have Cold Weather Flying
4. You cannot have the item in your bag

![image](https://user-images.githubusercontent.com/9414661/30798404-753e1dfa-a1d1-11e7-96f3-67bee8dbd351.png)

**Comment by ManiaLightmare** [comment]
Not sure what's going on then.  The only thing different from when my DK had one (aside from a new patch) is I eventually got cold weather flying for that toon.  My hunter and druid both have 225 riding.  The are both level 80 and neither have the item.

**Comment by fvicaria** [comment]
I was by that spot today for a while and saw a few players getting the loan also.
I will do more tests with DK and new characters.

**Comment by ManiaLightmare** [comment]
I even tried a "pristine" 2.1.2 client to make sure it wasn't some addon issue.  For your test, try having 1 character on the account with cold weather trainer and test with another.  That's the only thing I can think of  (other than the client just doesn't like me)
