### ISSUE TITLE
The Drakkensryd

### ISSUE THREAD

**Issue by izlandor** [WoWManiaUK/Redemption#1671]
The quest "The Drakkensryd" where you are sent to kill dragonriders surrounding a tower in Storm peaks.
Most of the mobs are not attackable, being either evading or "to far away"

SOME of the mobs are attackable, but far from enough.
The quest can be completed, but usually by waiting for attackable mobs to spawn again.

This quest is quite important due to it being in line for Sons of Hodir

**Comment by fvicaria** [comment]
Works.

**Comment by squalllh1989** [comment]
It's true that a lot of target mob in this quest are evading that cause a lot of trouble doing it, but it's still manage able.

**Comment by izlandor** [comment]
Yes. I am aware of that it is doable. However having sometimes compete with several other players cause it to be near impossible. With an only option of leaving and hope for better luck at an other time.


Skickat från min Huawei Mobile

-------- Ursprungligt meddelande --------
Ämne: Re: [WoWManiaUK/Redemption] The Drakkensryd (#1671)
Från: squalllh1989
Till: WoWManiaUK/Redemption
Kopia: izlandor ,Author


It's true that a lot of target mob in this quest are evading that cause a lot of trouble doing it, but it's still manage able.
