### ISSUE TITLE
[NPC] Abedneum (Halls of Stone)

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#1672]
Hello,
there's some invisible mob in the room where Brann Bronzebeard event (http://www.wowhead.com/npc=28234/tribunal-of-the-ages) takes place. 
Aggroes to the party when you go over to open the chest after the event ends, cannot be seen or targeted but he appears to take damage from Retribution aura. 
According to Recount, his name is "Abedneum", supposedly the same guy that talks in /yell during the event. Minor issue, but annoying.

**Comment by Hulkster-WowMania** [comment]
From what I can tell, this is emulating the random laser shots that would normally happen.  Even on retail, there's no way you could avoid this damage.

**Comment by Dranah** [comment]
no no it's definitely not like the laser shots, he aggroed after the event was completed, chest was looted... it's just an invisible dude meleeing (mostly the healer) for 500-1k damage

**Comment by Dranah** [comment]
https://imgur.com/JujMH5m here's a screen, the dude is just meleeing my butt while he talks :D 

You can see from the phrases this is past the waves of fight, at this point you should just chill and listen to the story before moving on to last boss. Now the problem is, this guy will follow you everywhere (even if you port out-in), so if you don't have a reflective damage source (i.eg. ret aura), you gonna have to finish the instance with him attacking your healer.

**Comment by fvicaria** [comment]
The Abedneum, is the computer. It is supposed to do damage on you as the security levels increase. The melee damage is just one of the types of damage.

I made a small change. Please re-test.

**Comment by Hulkster-WowMania** [comment]
This was way after the fight is over

![image](https://user-images.githubusercontent.com/9828794/30867865-bd22f6fa-a2a2-11e7-9b62-edbf4520e6c9.png)
