### ISSUE TITLE
Brewfest daily

### ISSUE THREAD

**Issue by redhawk816** [WoWManiaUK/Redemption#1673]
http://wow-mania.com/armory/?npc=24497  When I talk to him and start "more work", Each loop back with the keg should award 2 Brewfest tokens http://wow-mania.com/armory/?item=37829 and add 30 seconds to the ram mount buff, for a total of 15 minutes http://www.wowhead.com/brewfest-guide#daily-quests.  I am not receiving any tokens and no time is being added (that I can see) when I return with a keg.

**Comment by fvicaria** [comment]
Can you link the quest you are talking about, please?

**Comment by squalllh1989** [comment]
@redhawk816: from the link you link (http://www.wowhead.com/brewfest-guide#daily-quests) i can see you checked information about the event: 
Daily Ram Race: Awards 2  Brewfest Prize Token per turn-in
Start & End: Ram Master Ray or Neill Ramstein

But, unfortunate, those daily ram race is added at a later patch, so it won't happen here in wow mania :)

**Comment by Echinaceax** [comment]
> @redhawk816: from the link you link (http://www.wowhead.com/brewfest-guide#daily-quests) i can see you checked information about the event: Daily Ram Race: Awards 2 Brewfest Prize Token per turn-in Start & End: Ram Master Ray or Neill Ramstein
> 
> But, unfortunate, those daily ram race is added at a later patch, so it won't happen here in wow mania :)

I thought the same until researching  today 
the thing redhawk816 was reporting wasnt the 4.2 Brew For Brewfest quest https://wowpedia.fandom.com/wiki/Brew_For_Brewfest, they were talking about the Gossip given every 18hours  
![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/cd093eec-34cb-4bdb-adf7-0c7cc6796ece)
 
![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/1f903008-8aab-409d-ad59-2a0387a92bbe)
