### ISSUE TITLE
[Qruest] "That Which Creates Can Also Destroy" Bugged

### ISSUE THREAD

**Issue by anzo31** [WoWManiaUK/Redemption#1674]
The Qreust: "http://www.wow-mania.com/armory/?quest=12459"

I use the item to get the First Dragon down Frost Wyrm but when is weaken it just land on the ground and when I try to attack it keep say "out of range" 
![wowscrnshot_092617_152323](https://user-images.githubusercontent.com/8068585/30862553-bc430f8c-a2ce-11e7-86c9-591cf556dedc.jpg)

**Comment by fvicaria** [comment]
YOu need to start combat by shooting or casting (non-melee). It worked for me but I will improve it a bit.

**Comment by Hulkster-WowMania** [comment]
Tested on dev, was able to use the quest item to weaken the frost wyrm, then used a ranged attack to aggro him.  The then came down to melee range where I could attack and kill him

![image](https://user-images.githubusercontent.com/9828794/30879944-97f897b2-a2c6-11e7-9dc5-6d35595ca4e7.png)

**Comment by anzo31** [comment]
OKay I will go and check if I can do it now I will reply when I found out
