### ISSUE TITLE
Lucid Nightmare

### ISSUE THREAD

**Issue by Jagern** [WoWManiaUK/Redemption#1675]
The Lucid Nightmare mount is glowing orange instead of purple ish like it should be.
![wowscrnshot_092617_214015](https://user-images.githubusercontent.com/32306956/30880619-7875420e-a303-11e7-847e-5c92eec1ac94.jpg)
This is what it looks like for me
![11602](https://user-images.githubusercontent.com/32306956/30880685-b470f6d6-a303-11e7-8643-862bb478be6b.jpg)
This is how it should look

http://www.wowhead.com/item=151623/lucid-nightmare

**Comment by fvicaria** [comment]
As is.
I will check if there is another texture.
