### ISSUE TITLE
[Quest] Mutiny on the Mercy

### ISSUE THREAD

**Issue by mtne** [WoWManiaUK/Redemption#1677]
http://www.wowhead.com/quest=11527/mutiny-on-the-mercy

There should be mobs in the lower decks of the ship (those who have rebelled), which drop the gundpowder, but there are none. Which makes the quest undoable. Waited on the boat to do about full five cycles and searched it from top to the bottom, but found none.

**Comment by fvicaria** [comment]
Should be OK after restart

**Comment by mtne** [comment]
Thank you. Something which might turn out to be useful - during  doing the following quests, I found this comment: http://www.wowhead.com/quest=11529/sorlofs-booty#comments:id=833398
"
If you have the glitch, read this:

I found a way to avoid the glitch, and I think I know the cause of the glitch. DO NOT AT ANY TIME USE A FLYING MOUNT DURING THIS QUEST! I could not do this after two hours trying, then I stopped using my flying mount because my mouse had a glitch. I abandoned the quest, then, I acually swam onto the island that the boat docks at(38,75), walked up the ramp, re-accepted the quest. This won't look like it works at first. Walk to the cannon(front of the ship), and as soon as the boat stop, begin firing. At some point, sorlof will appear, if you have been firing enough. Keep firing until he is down, but DO NOT USE A FLYING MOUNT to get the booty, it seems to cause it to phase. Instead, Jump off the boat, and get the booty. the SWIM back to the island that the boat docks at(38,75), wait for the boat to come round, walk up the ramp, and turn in the quest. Jump off the boat. 

Flying onto the ship causes sorlof to phase. 
Flying off the ship causes sorlof's booty to phase.
"
Although I tried to get off and on the ship by foot, this could have something to do with it. Seems like blizzard did not cover the possibility of people just rudely flying on the ship and not orderly waiting in a line for the boarding.

**Comment by cellosgame** [comment]
http://www.wow-mania.com/armory/?quest=11527 

I have done everything that was stated above. I swam out to the ship. Turned in the previous quest to get Munity on the Mercy. Went down to the hold while the ship was in place there were no mobs. I have been waiting for an hour and stilll nothing. I believe this quest is still broken.

Thanks,
Baluc
