### ISSUE TITLE
[NPC] Banshee Soulclaimer

### ISSUE THREAD

**Issue by ManiaLightmare** [WoWManiaUK/Redemption#1678]
[Banshee Soulclaimer](http://www.wow-mania.com/armory/?npc=29646)

When they die, they will continue to perform their "dying" animation until their corpse/jewelry despawns.

If you have 2 very near each other, the second one doesn't seem to do it.

Not sure if this applies to all banshee npcs or just this one.

**Comment by Hulkster-WowMania** [comment]
Confirmed on dev

https://youtu.be/c-YqKXT8f3I

**Comment by fvicaria** [comment]
This is a client issue. There is nothing we can do. It will happen on some npcs (random) and only the first time it dies, after it respawns it doesn't happen again.
I  reduced the respawn time a bit.
