### ISSUE TITLE
[Item] Keg-Shaped Treasure Chest

### ISSUE THREAD

**Issue by squalllh1989** [WoWManiaUK/Redemption#1679]
This item currently is missing [Brewfest Prize Token](http://www.wow-mania.com/armory/?item=37829) from it loot table.
-  [Here](http://www.wow-mania.com/armory/?item=54535#contains) is what it currently contain in wow mania.
- [Here](http://www.wowhead.com/item=54535/keg-shaped-treasure-chest#contains) is what it should contain
I can see that you added the eof in it to replace the token, and boost the number of people which join the event's queue, but the lose of the token from the daily first queue clear make people (like me) having trouble of getting enought token to do what i want in the event, as we have limited time until it's gone. It's on my own suggest that it will be nice to add the token to the keg's loot table too, thank you very much.

**Comment by fvicaria** [comment]
As is. The items are as per 3.3.5a not retail as it is now.
