### ISSUE TITLE
[Ulduar] XT- Hearbreak bug

### ISSUE THREAD

**Issue by Nimsy** [WoWManiaUK/Redemption#1681]
Issues with XT (10man and 25man Version)
http://www.wowhead.com/npc=33293

When you fight XT she drops her heart (http://www.wowhead.com/spell=65737) which you can kill to send her into hard mode. However, after so many seconds it is supposed to go back into its body allowing you to kill it on normal mode. Currently her heart will not go back into her body, which forces you to attempt to kill her in hard mode. It caused many issues with this weeks XT kill weekly quest.

**Comment by fvicaria** [comment]
Please confirm this.

**Comment by Hulkster-WowMania** [comment]
Confirmed fixed in dev.  Did not kill the heart, fight continued as normal.
