### ISSUE TITLE
[Quest] Hurley Blackbreath

### ISSUE THREAD

**Issue by Brunnr** [WoWManiaUK/Redemption#1682]
http://www.wow-mania.com/armory/?quest=4126

Entering the Grim Guzzler, and destroying the 3 kegs which are in the same side room as Coren Direbrew during Brewfest causes Hurley and his henchmen to appear, but they are invalid targets and can't be killed. You must kill them to get the quest objective to drop.

**Comment by fvicaria** [comment]
Can someone confirm this please.

**Comment by fvicaria** [comment]
Works fine in dev. Only thing adjusted was mobs positions.
