### ISSUE TITLE
stuck at Emerald forest

### ISSUE THREAD

**Issue by zzbowzz** [WoWManiaUK/Redemption#1683]
i'm stuck at Emerald forest, where i was killed by an wasp and then it said something about me not being in an group and now i'm dead & stuck so i can't teleport or walk anywhere.

**Comment by fvicaria** [comment]
Not the correct place for this.  Create a ticket and a GM will move you.

**Comment by zzbowzz** [comment]
i'm sorry kinda new to the game, but how do i create a ticket? sorry for asking but i couldn't find it at the website

**Comment by fvicaria** [comment]
what is your char name?
