### ISSUE TITLE
[Quest] Sniffing Out the Perpetrator

### ISSUE THREAD

**Issue by Dananjaa** [WoWManiaUK/Redemption#1685]
When accepting the quest, you should be able to mount 'frostbite', the pet of the questgiver. This is not possible, also not when I was not mounted when accepting the quest or trying to mount.  (Help of a gamemaster, who killed off the pet, was not sufficient to solve the problem)

**Comment by fvicaria** [comment]
Please follow the procedure described below before creating a new issue:
[How to Properly Report an Issue](https://github.com/wow-mania/Redemption/wiki/How-to-Properly-Report-an-Issue)

This will help developers identify and fix the issue quicker. Incorrectly or unclear reports will simply be deleted.

**Comment by fvicaria** [comment]
A: https://www.wowhead.com/quest=12910/sniffing-out-the-perpetrator
H: https://www.wowhead.com/quest=12855/sniffing-out-the-perpetrator

**Comment by fvicaria** [comment]
Cannot reproduce in dev.
