### ISSUE TITLE
[Quest] Honoring a Hero

### ISSUE THREAD

**Issue by goldstinger** [WoWManiaUK/Redemption#1687]
This quest is part of the Harvest Festival seasonal, for horde side.

[Quest](http://www.wow-mania.com/armory/?quest=8150)
[Associated Item (Grom's Tribute)](http://www.wow-mania.com/armory/?item=19851)

After picking up the quest from Javnir Nashak from outside Orgrimmar, and fly to the quest marker location inside of Ashenvale to use Grom's Tribute at Grom Hellscream's Monument, it starts a cast with the item. After the cast finishes, it throws back a Failed error, with the error message "You can't do that yet", and also removes the item from your inventory. The quest does not progress, or do anything else after the cast and the item is gone from the inventory.

Screenshots below to paint the image of what's going on.

[Map Location](https://i.imgur.com/M1KmxJX.jpg)
[Quest Log](https://i.imgur.com/0tKUtGQ.jpg)
[Confirmation of Proper Location & Stone](https://i.imgur.com/S4mCqr2.jpg)
[Confirmation of Item in bag](https://i.imgur.com/GWX8AXr.jpg)
[Using the Item](https://i.imgur.com/66eG4Jl.jpg)
[Error Message](https://i.imgur.com/JTQmwCA.jpg)

**Comment by fvicaria** [comment]
I cannot reproduce it. 
![image](https://user-images.githubusercontent.com/9414661/31044097-7782a35e-a5c0-11e7-9e54-213fb48b3f39.png)


Try to do it at the steps. Since you already lost the item open a ticket and ask for a GM to complete for you.

**Comment by squalllh1989** [comment]
Hm, i can complete this on horde side without problem at all.

**Comment by goldstinger** [comment]
@fvicaria that's alliance side, not horde side. Horde side quest and associated item was linked in the original post.

@squalllh1989 in further research it says all types of tributes failed when looking at the combat log. [Screenshot here](https://i.imgur.com/jqgqNqW.png). Looking over that, I see nothing regarding Goblins, and I assume it's the same for Worgens on alliance side. Seasonals & events have had issues for Goblins & Worgens in the past, so it's just an assumption on my part.

**Comment by squalllh1989** [comment]
oh, that make sense too, the event is not designed for goblin and worgen as there is no such race in wotlk, that should be the problem, i will try this out when i have chance.

**Comment by fvicaria** [comment]
It should be for all races. I will try with a Worgen
