### ISSUE TITLE
[Quest] Steamtank Surprise

### ISSUE THREAD

**Issue by cathyr1** [WoWManiaUK/Redemption#1688]
Hello! There´s another bugged alliance quest on The Carrion Fields: http://www.wow-mania.com/armory/?quest=12326. When I use "Dropp Off Gnome" ability at the Plague Wagon, the engineer do nothing instead of sabotage that wagon. Every time there is just written Evade when door open and nothing happens. So the quest cannot be completed.
![obrazek](https://user-images.githubusercontent.com/30184491/31045154-5b6636be-a5dd-11e7-963b-24d0dc872afc.png)

**Comment by fvicaria** [comment]
I have just done the quest and it seems to work fine.
You need to drop gnome near the Plague wagon.
Some may not give you credit, if that happens, move to the next one.
![image](https://user-images.githubusercontent.com/9414661/31045266-a3c5626e-a5d7-11e7-8bef-ffca11438279.png)

![image](https://user-images.githubusercontent.com/9414661/31045273-b17b7902-a5d7-11e7-8e30-b708013d4cfd.png)

**Comment by squalllh1989** [comment]
Just completed the quest without any problem.
![wowscrnshot_093017_181300](https://user-images.githubusercontent.com/27235989/31045480-21ef85a2-a60f-11e7-9c30-3b7fbf72784a.jpg)
![wowscrnshot_093017_181923](https://user-images.githubusercontent.com/27235989/31045481-23772aba-a60f-11e7-8854-9451fba8a0e4.jpg)
