### ISSUE TITLE
Problems with all the ghosts in forgotten shore, Dragonblight.

### ISSUE THREAD

**Issue by Zeevee92** [WoWManiaUK/Redemption#1689]
Hi,
i want to report a bug, like said in the title, for the ghosts in fogotten shore, dragonblight.
They don't take my pet agrro at all, they totally ignore him, both in defence and aggressive. When i feign death they just loose all my aggro and go back on patrol even if my pet is still attacking them. They also totally ignore my traps, they walk over and pass by, without activate them. 
I spoke with thw Gm and he told me to write to you. 
Hope i was helpful for your work, 
thanks for the work.
have a good day

**Comment by fvicaria** [comment]
Thanks for the report. I will check it. Some mobs may indeed ignore the pet that is normal. I will check if this is the case for this one. In the meantime can you link the mob and also check the wiki on how to post an issue so it is easier for developers and testers to verify and fix them.

**Comment by squalllh1989** [comment]
Confirmed in dev, all the mob in the area is ghost (undead), they completely ignore hunter pet's agro, if hunter feign death they go off combat and regen, they also ignore all the trap, walk over but didn't active them.

**Comment by fvicaria** [comment]
Can you send me a link to one of the mobs, also to one that works correctly?

**Comment by squalllh1989** [comment]
There are a lot of mob that have this problem in the area, expample: [Forgotten Captain](http://www.wow-mania.com/armory/?npc=27220) or [Forgotten Peasant](http://www.wow-mania.com/armory/?npc=27226)

**Comment by fvicaria** [comment]
This is the correct behaviour for those NPCs. Your pet can't see them.

**Comment by squalllh1989** [comment]
lol that make sense, so pet can't see ghost as you do, so they can't do anything to them :)
