### ISSUE TITLE
[Quest] The Chain Gun And You

### ISSUE THREAD

**Issue by cathyr1** [WoWManiaUK/Redemption#1690]
There is another quest that I have problem with http://www.wow-mania.com/armory/?quest=12457. Here you can see how it should work: https://www.youtube.com/watch?v=JxdWf1O9k0o. But on my screenshot you can see that when I click on the gun, just the buff appears but I cannot control the gun.

I tried bring my horde character and kill the cannons for respawn. However, they were evade so maybe there is the problem. I also restarted the game and deleted cache, but the problem persist. I think you can just respawn the cannons, it may help.
![obrazek](https://user-images.githubusercontent.com/30184491/31045559-82cb99c0-a5e6-11e7-9687-64324fe085f4.png)

**Comment by fvicaria** [comment]
Works perfectly in Redemption. I have just tried. You must have done the quest before on that character or dropped it. Ask a GM to remove it from you.

**Comment by cathyr1** [comment]
I did all quests and now have only this chain in this map. Still not working. When I click cannon, only buff appears but I cannot control it. How could it work to you?

**Comment by cathyr1** [comment]
Now ok right now one cannon changed and it is finally controllable.

**Comment by fvicaria** [comment]
I think the reason for the issue is that the cannons were being attacked by the mobs and eventually dying. When they came back they had the boarding issue.
