### ISSUE TITLE
[NPC] Svala Sorrowgrave

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#1693]
Inside Utgarde Pinnacle (http://www.wowhead.com/utgarde-pinnacle)
the first boss, Svala Sorrowgrave (http://www.wowhead.com/npc=26668)
has an ability Ritual of the Sword (http://www.wowhead.com/spell=48276) which should have a 25sec duration, as per the link and the DBM timer.

Description: one party member gets teleported to svala's altar, stunned until the three adds channeling are killed. If the time runs out, a sword falls on the person's head, leaving a strong dot that will most certainly kill them.

Issue: on this server, the sword falls way too soon, your party gets nuked by the sword, while the timer on DBM shows you should still have plenty of time left.
I did it with two different parties, at two different time of the day, so it cannot be lag (also that would affect the DBM timer as well.)

**Comment by fvicaria** [comment]
Fixed in dev.
