### ISSUE TITLE
[Quest] Sorlof's Booty

### ISSUE THREAD

**Issue by Wolch** [WoWManiaUK/Redemption#1694]
http://www.wowhead.com/quest=11529/sorlofs-booty
The player needs to kill Sorlof while on the ship (shoot from the canon). But when I was on the ship I could not see Sorlof, the ship was in a different phase. Mobius was with me trying to figure out waht was wrong, he can confirm this.

**Comment by fvicaria** [comment]
Fixed. This is a visibility issue.

**Comment by GMWeeble** [comment]
Quest " http://wow-mania.com/armory/?quest=11529 " Using the cannon to kill Sorlof does not work.
Issue seems to be that the veiwdistance/phasedistance/whateverdistance is to short to see and get kill credit for him. So in other words you cannot see him to and kill him with "The Big Gun" From the boat

**Comment by fvicaria** [comment]
Fixed.
