### ISSUE TITLE
Plans: Goblin Rocket Boots not working

### ISSUE THREAD

**Issue by monyam** [WoWManiaUK/Redemption#1698]
I am using the client of wowmania, with the latest launcher.
Steps to reproduce: get plan, try to use it.
How it should work: use plan, get to know how to make it.

What happens: Nothing. I click on the plans and nothing happens.

**Comment by fvicaria** [comment]
Please follow the procedure described below before creating a new issue:
[How to Properly Report an Issue](https://github.com/wow-mania/Redemption/wiki/How-to-Properly-Report-an-Issue)

This will help developers identify and fix the issue quicker. Incorrectly or unclear reports will simply be deleted.

**Comment by fvicaria** [comment]
Just tested in redemption and they work fine.
Please check requirements and other possible causes before posting.

**Comment by monyam** [comment]
well the one i have doesn't work...  gm said to post here..
