### ISSUE TITLE
[Quest] The Lich King's Last Stand

### ISSUE THREAD

**Issue by Dusticles** [WoWManiaUK/Redemption#1699]
I have personally defeated the Lich king 5 times now, resulting in tickets through the five kills on Lich King, today I have abandoned the quest then repicked it up as suggested by a certain gm, (don't remember his name) but to no avail the quest still will not complete on his death, I am wielding Shadowmourne each kill, I did repick up the quest, and I have killed him on both normal and Heroic 25 man. Can this be invesigated into?
 I feel others around me have this quest completed, but in my experience it does not. The four items named Jaina's Locket, Arthas' Training Sword, Badge of the Silver Hand, and Blood of Silvanas I beleive will not be able to be turned in until this quest is completed.

**Comment by fvicaria** [comment]
Contact me via Skype. I will sort it for you. The quest works. A GM should have it removed from you and added back.

**Comment by LooneyBin** [comment]
Quest still not working.
Got the quest Friday 22 December, and killed 25 HC LK the following day (23 Dec), and still couldnt complete my quest.

**Comment by fvicaria** [comment]
Quest works. Sorry, you will have to add more info and if possible a video.

**Comment by fvicaria** [comment]
Talk to val and you can check it on dev with him.

**Comment by squalllh1989** [comment]
I just check this in dev and it didn't work, maybe you should have a look on this. Some people in redemtion have this issue as well.
![wowscrnshot_011918_145222](https://user-images.githubusercontent.com/27235989/35140334-7478ddb6-fd29-11e7-8ac3-71ff13577f99.jpg)
![wowscrnshot_011918_145629](https://user-images.githubusercontent.com/27235989/35140344-7b13b632-fd29-11e7-8f2f-3c0d6a41337d.jpg)
![wowscrnshot_011918_145744](https://user-images.githubusercontent.com/27235989/35140361-8596c4b4-fd29-11e7-8e2a-a6b41597023b.jpg)
![wowscrnshot_011918_145716](https://user-images.githubusercontent.com/27235989/35140368-899574b6-fd29-11e7-9251-59edaf32ebd4.jpg)

**Comment by LooneyBin** [comment]
![wowscrnshot_010518_220949](https://user-images.githubusercontent.com/28490335/35144111-d7810576-fd03-11e7-88f3-84fed03e44b1.jpg)
![wowscrnshot_011018_223400](https://user-images.githubusercontent.com/28490335/35144112-d7aa79e2-fd03-11e7-8596-67febfbfe600.jpg)
one as tank on 25 hc LK, not completed.
one as dps on 25 norm LK, not completed.

Got the Box, which gives the quest for the items on first kill, but the quest for killing LK (The Lich Kings Last Stand), still cant complete it after killing him several times now.
killed him on 25 normal and heroic, as tank and dps, and nothing seem to work.

**Comment by VA-L** [comment]
Fixed on dev tomorrow.
