### ISSUE TITLE
[NPC] Thassarian and High Captain Justin Bartlett

### ISSUE THREAD

**Issue by anzo31** [WoWManiaUK/Redemption#1700]
Well after i complete the 5 quest I have take from the ship the two quest givers that gave me them is not longer there. See I dunno if is a bug or something else so I could use some help that im close to lv 80
![wowscrnshot_100217_020736](https://user-images.githubusercontent.com/8068585/31060734-a442eeb8-a718-11e7-9dba-77fc50dca3b8.jpg)
![wowscrnshot_100217_021551](https://user-images.githubusercontent.com/8068585/31060733-a43b6f4e-a718-11e7-8134-2b9c43f8c8cb.jpg)

**Comment by GMWeeble** [comment]
This issue does still happen. Also on the Horde ship. They fall trough the ship and teleporting to the NPC puts you on the ship  where they should be.

**Comment by fvicaria** [comment]
as mentioned this is a core issue we cannot do anything about it. needs to wait for restart
