### ISSUE TITLE
[ITEM] not working

### ISSUE THREAD

**Issue by monyam** [WoWManiaUK/Redemption#1701]
I am using the current client, along with the latest launcher update. 

My char: lvl 23 belf, priest. 
Engineering skill: 225
Required skill for plan: 130
Other requirements: Engineering

How to reproduce: 
Get the plans in link. https://wotlk-twinhead.twinstar.cz/?item=7192
Try to use it. Nothing happens. No text on screen as if it doesn't register the input. 

What's supposed to happen:
Click on the plan. Begin to learn new engineering skill.
What happens:
![wowscrnshot_100217_144716](https://user-images.githubusercontent.com/31564844/31077952-b187480e-a780-11e7-897a-70face306c15.jpg)

!
some GM's have the same problem with the plans.

**Comment by fvicaria** [comment]
DO NOT LINK REFERENCE FROM OTHER SERVERS HERE!

Also search before posting.

By the way the item works!

**Comment by monyam** [comment]
well.. it doesn't work. gg

**Comment by fvicaria** [comment]
It does. You are doing it wrong.
![image](https://user-images.githubusercontent.com/9414661/31081483-f65bf15c-a783-11e7-990c-7111a123281e.png)

**Comment by fvicaria** [comment]
Also please do not open new issues one day after I have closed the same one.

**Comment by monyam** [comment]
GM told me to... jeez

**Comment by monyam** [comment]
also it's the wrong one u use...
the one i link to is for engineering 130

**Comment by fvicaria** [comment]
I will check your character.

**Comment by fvicaria** [comment]
You are saying the plans doesn't work, not the actual boots?

**Comment by monyam** [comment]
yes. the plans

**Comment by monyam** [comment]
as i stated

**Comment by fvicaria** [comment]
Apologies then. I thought it was the boost. I will check now.

**Comment by fvicaria** [comment]
This item is not valid anymore.
It does not use plans to learn, taught by trainers in Ratchet, Gadgetzan and Dalaran at skill level 130

![image](https://user-images.githubusercontent.com/9414661/31082242-5157d75e-a786-11e7-93a0-c0ad16c7011b.png)

**Comment by monyam** [comment]
ok
