### ISSUE TITLE
[Quest] We Have the Power (alliance)

### ISSUE THREAD

**Issue by cathyr1** [WoWManiaUK/Redemption#1702]
Hello! I don´t know why but I can´t loot one of the necessary items: http://www.wow-mania.com/armory/?item=36857 that should drop from http://www.wow-mania.com/armory/?npc=26409. I´ve killed him 5 times (ofc including restart and delete cache) but this item simply never dropped from him, while the second one did on the first try. The quest is http://www.wow-mania.com/armory/?quest=12131.
![obrazek](https://user-images.githubusercontent.com/30184491/31097834-014cc2e8-a7c1-11e7-9948-9d5c6f954ee9.png)

**Comment by fvicaria** [comment]
There is a 67% chance. 5 times should be enough in most cases. But it is not impossible.
You can throw a coin and get 5 heads in a row. :)
