### ISSUE TITLE
Val'anyr shield from Holy paladins heals don't appear!

### ISSUE THREAD

**Issue by Aattrox** [WoWManiaUK/Redemption#1703]
When **Val'anyr** is used by holy paladins the shield don't appear anymore and when it appears its only on that holy paladin who wear the **val'anyr** don't works on AoE heals.

**Comment by Kilju** [comment]
Works fine for my holy paladin. Guild member has a same problem as you though.

**Comment by squalllh1989** [comment]
Confirmed in dev, something is wrong with this, based on wow head, [the Val'anyr's shield](http://www.wowhead.com/spell=64415/valanyr-hammer-of-ancient-kings-equip-effect) should proc at 10% chance, but with my test, it proc in the first 10 sec once, then no more proc in the next 10 min spam holy light.

**Comment by Hulkster-WowMania** [comment]
I've done some testing with this as well.  100% confirmed that overhealing won't proc the hammer so if you're spamming holy light for 10 min on a full health target, it'll never proc.

**Comment by squalllh1989** [comment]
I did the spam with a mob hitting me, but yeah, this need some more test to check it out

**Comment by fvicaria** [comment]
Can I have the link to the item and the spell please.

**Comment by fvicaria** [comment]
This is a general core issue. I am not going to treat it separately here.
