### ISSUE TITLE
Teron Gorefiend, I am

### ISSUE THREAD

**Issue by cellosgame** [WoWManiaUK/Redemption#1704]
http://www.wow-mania.com/armory/?quest=10645

So i started the quest. Karsius came up i went to attack him per comments on the quest. After i tried to attack him he sped forward to where i was originally and the spirits behind him and him killed me so fast. 

I rezzed went back to drop the quest and restart it. Nothing happend he wasn't there. I tried for 3 days in a row and nothing.

There is an issue with the pet/NPC it having too low of health as well.

Thanks, 
Cellosgame / Baluc in Game

**Comment by fvicaria** [comment]
Yes the NPC was left in a bad state. It's fixed now.

**Comment by GMWeeble** [comment]
Quest Npc. Karsius seem to be in another phase when entering Gorefiend to fight him. Players unable to do the quest.

**Comment by fvicaria** [comment]
Working fine on dev.
Will wait for someone else to test.

**Comment by squalllh1989** [comment]
Work fine for me, you have to cast the 3rd ability (Touch of darkness) while in gorefriend to start pull agro on him and fight him.

**Comment by GMWeeble** [comment]
Tester in red or dev only?
