### ISSUE TITLE
The pufification of quel'delar 

### ISSUE THREAD

**Issue by DropBear85** [WoWManiaUK/Redemption#1706]
http://www.wow-mania.com/armory/?quest=24553

After making sure I'm in a raid group I speak with the npc to send me in and i load up in the correct spot but the raid is active and I'm blocked by a wall witha boss behind me (M'uru). After speaking with GM Amytis he refused to help in any way other than refer me here 

I'm using the launcher 
I've logged in and out 
restarted the launcher 
changed raid size and groups 
reset the instances

**Comment by fvicaria** [comment]
The quest works. There is an NPC there to auto-completes the quest for you. You don't have to go into the raid.

**Comment by DropBear85** [comment]
can you tell the name and location of the npc please as I can't see any extra npcs at the entrace area
