### ISSUE TITLE
[Item] Charred Twilight Scale

### ISSUE THREAD

**Issue by redhawk816** [WoWManiaUK/Redemption#1712]
The normal version of this item does not proc.  I have yet to see it proc once in the past 2 hrs in heroic 10m ICC.

**Comment by squalllh1989** [comment]
just tested with my mage in redemtion, it proc like normal, can you give out more information about what class are you playing that it give no proc ?
![wowscrnshot_100717_232808](https://user-images.githubusercontent.com/27235989/31309841-34585810-abb7-11e7-8bdf-8f85aa248abf.jpg)
![wowscrnshot_100717_232805](https://user-images.githubusercontent.com/27235989/31309846-377ebfb6-abb7-11e7-881a-f32031fce4ef.jpg)

**Comment by redhawk816** [comment]
Blood Elf Shadow priest.  Was in ICC 10m Heroic.  Only saw it proc twice.  It usually procs several times during a single boss fight.  I just tested at the dummies and it does not proc as it should.

**Comment by fvicaria** [comment]
Cannot reproduce.

**Comment by squalllh1989** [comment]
Confirmed in redeemtion, today i did a rdf hc with a character named " Jalone", a blood elf priest which have both [Dislodged Foreign Object(hc)](http://www.wow-mania.com/armory/?item=50348) and [Charred Twilight Scale](http://www.wow-mania.com/armory/?item=54572) in The Nexus, i target him and watch his buff the whole time in the run, and in the whole run which last nearly 20 min, he got none proc from both of his trinket, so this item got a problem with at least blood elf priest.
