### ISSUE TITLE
Ashen Band of Endless Courage

### ISSUE THREAD

**Issue by Tasmanijak** [WoWManiaUK/Redemption#1713]
My ingame name is Fullcool i have this ring from the ashen verdict reputation exalted [Ashen Band of Endless Courage] and it does not ever proc for me.  And on the other acc my ingame Panny its a heler there i have  [Ashen Band of Unmatched Wisdom] and that also dosent proc.
 [Ashen Band of Unmatched Wisdom] shold proc 285 spel power but it dosen't
 [Ashen Band of Endless Courage] shold proc 2400 armor but it dosen't

**Comment by fvicaria** [comment]
3% chance. Correct.
