### ISSUE TITLE
[Quest] Fueling the Demolishers

### ISSUE THREAD

**Issue by NightSeekerr** [WoWManiaUK/Redemption#1714]
As requested by admin Psygoa I'm reporting the issue. 

You accept the quest from http://www.wowhead.com/npc=31108 at the Alliance camp next to the Sunken Ring in Wintergrasp. You gather 10/10 http://www.wow-mania.com/armory/?item=43314. But when you return to finish the quest, you find out the quest giver isn't responding (he doesn't have yellow question mark and you cannot complete the quest).

Link for the quest: http://www.wowhead.com/quest=13197/fueling-the-demolishers

I use the client and the latest Launcher.

**Comment by fvicaria** [comment]
You can only deliver that quest when your faction owns Wintergrasp.
