### ISSUE TITLE
Attacked when not flagged PVP 

### ISSUE THREAD

**Issue by Tashier** [WoWManiaUK/Redemption#1716]
I was attacked in zangermarsh while not being flagged for PVP and not anywhere near the pvp area.   I double checked my flagged when i was attacked and it didn't appear until after i released.  Im not running any addons which would atomatically flag me.   the other player was belligerant and while not admitting to running a hack told me i " couldn't prove" he was.   There was no reason he should have been able to attack me

**Comment by Mobius14** [comment]
Can you be more specific about what zones? When i test it without any addon the pvp flag is very responsive when im even 1 step in the zone. (the addons don't trigger your pvp but they can interfere with what you see on your screen.. if you are flagged or not) 

Please specify in detail so our dev/test team can reproduce or solve the issue :) 

kind regards

**Comment by Tashier** [comment]
I was in the murkblood area doing the poison quest when i was attacked .  He should not have been able to attack me as i checked my flag was not on.  gm says it had to be but i detest pvp and don't flag.  I m aware of the pvp areas in zanger and hellfire but i believe you also have to intentionally flag to participate in those.  Even my log showed him attacking me before it gave me the popup " you ar now flagged PVP

**Comment by fvicaria** [comment]
Free for all zone.

**Comment by Tashier** [comment]
zangermarsh isn't a ffa zone neither is the murkblood quest area

**Comment by Tashier** [comment]
So if zangermarsh is a FFA PVP area why isn't there any sort of notification for being flagged PVP?  Players join PVE servers because they don't WANT to PVP  pve servers are extremely difficult to find anymore and to think you've found one only to be randomly flagged in an unmarked area.. kinda defeats the purpose of playing on a pve server.  At least do your players the courtesy of telling them they're entering a ffa pvp area so they can leave it.  from what ive read on the forums zangermarsh is only ffa pvp in " unnamed areas" I was in a named quest area.  I did not show flagged until after i retaliated.  so be be PVP attackable but have no flag or no warning hardly seems to be in the spirit of true pvp and more supportive of the gank fest of other servers.

**Comment by Tashier** [comment]
and are there any other ffa areas i need to be aware of so i can decide if i want to continue to play here before i waste any more of my time
