### ISSUE TITLE
Item: Dislodged Foreign Object (heroic) doesn't activate 

### ISSUE THREAD

**Issue by BabaJag1** [WoWManiaUK/Redemption#1717]
(Equip: Your harmful spells have a chance to increase your spell power by 121 and an additional 121 every 2 sec for 20 sec.) this Spellpower Buff doesn't activate on my Human Spriest. Tested it on Training dummy.

**Comment by squalllh1989** [comment]
Confirmed in redeemtion, today i did a rdf hc with a character named " Jalone", a blood elf priest which have both [Dislodged Foreign Object(hc)](http://www.wow-mania.com/armory/?item=50348) and [Charred Twilight Scale](http://www.wow-mania.com/armory/?item=54572) in The Nexus, i target him and watch his buff the whole time in the run, and in the whole run which last nearly 20 min, he got none proc from both of his trinket, so this item got a problem with at least blood elf priest.

**Comment by BabaJag1** [comment]
@fvicaria Works for me again thank you for fix 👍
