### ISSUE TITLE
Innkeeper Allison

### ISSUE THREAD

**Issue by Ulnar** [WoWManiaUK/Redemption#1718]
Innkeeper Allison in Stormwind is running on the spot. You can still interact with her.

**Comment by squalllh1989** [comment]
Confirmed, [the NPC](http://www.wow-mania.com/armory/?npc=6740) is having the animation of running instead of stand still.
![wowscrnshot_100917_110109](https://user-images.githubusercontent.com/27235989/31324882-66aaa7e8-ace1-11e7-9e24-d2f060d38ba1.jpg)

**Comment by fvicaria** [comment]
Fixed. Thanks.
