### ISSUE TITLE
[Spell] Dancing Rune Weapon

### ISSUE THREAD

**Issue by AyrStormborn** [WoWManiaUK/Redemption#1719]
Hello, good day to you, dear staff member,

Mobius, helped me in-game today and instructed me to create this post. This report has been made based on extensive hours of research. Due to the relevance of its nature, I beg it's paid the due attention. 

First of all: I do use the client, I do use the launcher, I do have the latest patch and this is not a personal bug. 

Now, addressing the problem itself: the damage boost that should be applied by Dancing Rune Weapon (http://www.wow-mania.com/armory/?spell=49028) is not functioning correctly. Our insight is that it's only dealing 50% of melee damage but only 10% of any other damaging spell, creating an overall loss of 40% damage for the blood death knight compared to the intended value of the spell. 

1- Steps to reproduce the problem: Testing damage unbuffed on the same dummy using the exact same rotation of spells. 
There are some screenshots that will showcase this testing process:
![wowscrnshot_100917_160420](https://user-images.githubusercontent.com/32645381/31346433-9c236ea6-ad08-11e7-8e57-5ed1dbfd944a.jpg)
![wowscrnshot_100917_160544](https://user-images.githubusercontent.com/32645381/31346434-9c267fa6-ad08-11e7-996c-5ebdfe122c95.jpg)
![wowscrnshot_100917_160608](https://user-images.githubusercontent.com/32645381/31346432-9c172f7e-ad08-11e7-84a2-edf7ad6e6810.jpg)
![wowscrnshot_100917_160720](https://user-images.githubusercontent.com/32645381/31346435-9c44d474-ad08-11e7-86e2-e14eaf204593.jpg)

There, you can see how the full rotation with every single buff available renders a 12% damage increase associated with melee swings. This however, is NOT how the skill should work. It should be applied to every offensive spell.

2- How do I know for a fact that the damage is not being increased properly on spells? 
I tried to check the % damage corresponding to the DRW when only using melee swings for the duration of the buff. Here is the result: 
![wowscrnshot_100917_162734](https://user-images.githubusercontent.com/32645381/31346621-383a427e-ad09-11e7-835e-6aacff7fce10.jpg)
![wowscrnshot_100917_162740](https://user-images.githubusercontent.com/32645381/31346620-3834475c-ad09-11e7-9ec1-d90ba57615b3.jpg)
Those screenshots show how out of a 2k DPS based on melee swings only, 788 came directly from the DRW. If this very same effect was operating properly on every single offensive spell cast by the death knight, (in other words, operating as intended), the damage shown to be applied by DRW in the previous screenshots would be a lot higher. 

To prove this, I decided to test my damage excluding DRW buff. It's remarkable how insignificant the lack of the buff proved to be: 
![wowscrnshot_100917_165214](https://user-images.githubusercontent.com/32645381/31346930-3dbfc3bc-ad0a-11e7-8472-f89733790e93.jpg)
![wowscrnshot_100917_165220](https://user-images.githubusercontent.com/32645381/31346932-3dca9fc6-ad0a-11e7-9b9e-cf7c358cb807.jpg)
((((( Important: notice there is a 4% of the time in which there was no damage applied due to server lag, estimated correcting that 4% is 6,45k dps.))))

As it's shown, the difference in between a rotation with active DRW and without it is clear proof that the dmg buff is NOT being applied on any skill other than melee swings. (You can know by comparing damage 

In summary: DRW should echo every offensive spell cast by the death knight dealing 50% of the damage.  (For more info on patch notes: http://wowwiki.wikia.com/g00/wiki/Dancing_Rune_Weapon?i10c.encReferrer=aHR0cHM6Ly93d3cuZ29vZ2xlLmVzLw%3D%3D).
However, the actual functioning of the spell at the moment is increasing by 50% melee damage. This is a terribly huge loss in dps for the blood death knight and has been reported here before and disregarded by the developers due to a misunderstanding of the spell functioning and current patch notes. (It's true that in Legion patches it does only copy melee swings, but we play in a WoTLK server, not legion, thus WoWhead current description of the skill is UNACCURATE and the Wow-Mania armoury one should be applied.)

Due to all this, I beg you to fix this problem and properly adjust the damage boost since it renders an extremely fun and engaging class and spec completely crippled, forcing players to play a hindered class without it's main, signature skill or simply rolling another spec for the dps pve death knight.

Once again I would like to state and make clear that this post has been created with the assistance of many players as well as a GM to whom I exposed all these facts before creating the report.

I dearly appreciate your attention. I hope that my research was detailed enough and I expect a prompt solution to this problem. Huge thanks and have a lovely day.

Kind regards, 
Your fellow player Arnorolith.

**Comment by fvicaria** [comment]
Can anyone one confirm this? I am pretty sure the formulas are correct and the damage is as it should but I will wait for confirmation from one of the testers.

**Comment by AyrStormborn** [comment]
In case it helps shed light on this, many players agree with what I posted. This was reported in the past and disregarded based on the same certainty that everything works properly. But I would LOVE to know that such certainty is 100% confirmed by reliable methods before closing this post again since, as it's been stated, we are dealing with a potential bug in a signature spell and an enormous potential loss of damage.

Remember: out of 2k melee swing dps, DRW deals 788 dps. Out of nearly 8k dps with every skill, DRW deals 1,2k. That means that out of around 6k dps produced by abilities, 418 dps is due to DRW. That is in no way shape or form a 50% echo of the death knight abilities. 
And, then again, this is not the way the spell is meant to function in the current patch.

I hope this additional comment helped clarify the point and make sure the exact maths are thoroughly tested. 
Also, if possible, I would like to see the evidence supporting whichever conclusion you arrived to. I was asked for a detailed post by the team, I ask for a detailed answer, please.

Thank you very much, again.

**Comment by Plege** [comment]
This sounds like a complex issue and will take time confirming, thanks for the very detailed description of the issue. I will take some time to look into it today or tomorrow.

**Comment by Plege** [comment]
I got to test Dancing Rune Weapon (DRW) today and here is what i found:

How it Should Work: DRW should copy all DK cast spells (with a few exeptions like army of the dead) and melee attacks with a damage multiplier of 50%, apply diseases and attack the DK's target.

How it works on WoWMania: DRW copies all DK spells and melee attacks but the damage multiplier is not applied correctly to all of them. to clarify this i made a spreadsheet listing damage done by the DK and comparing it to the damage by DRW (using no cooldown and infinite runic power (cheats) i can guarantee a 100% uptime of DRW) this means the damage of DRW should be very close to 50% of the DK's damage for every spell and melee swing.

[Dancing Rune Weapon.xlsx](https://github.com/WoWManiaUK/Redemption/files/1375752/Dancing.Rune.Weapon.xlsx)

As you can see in this spreadsheet all the tested abilities and autohits were coppied by DRW and diseases were applied. However the damage multipliers are not always on point. In the last column you can see the percentage offset to the expected value (negative values meaning the damage was too low and should be increased). The multiplier is off by a huge amount for some spells and diseases up to 90% this needs to be fixxed. also interestin is that the amount of ticks for the diseases cast by DRW is much lower than expected, it seems the tick rate needs to scale as well as the damage per tick for those.

Conclusion: 
-Application of Spells and diseases works as intended
-Damage multiplier (50% of DK's damage) is not working correctly
-Disease tick rate is much different from the DK's

Disclaimer: I have no idea what the actual Blood DK's rotation looks like so other important spells might be bugged as well. This is just proof that the there are buggs with DRW with damage scaling and tick rate of diseases. 

Regards,
Pleger

**Comment by AyrStormborn** [comment]
I would like to thank you deeply, from me and all the friends who helped out when reporting this, for the thorough examination of the issue and the effort you put in.
I hope this is considered evidence enough to fix this problem and, hopefully, we will be able to play our Blood DK to its awesome maximum potential after the next patch is uploaded.

About your disclaimer: the spells shown in the spreadsheet are the most important ones. In my personal experience, the damage loss of Heart Strike is the most important one since it represents nearly a 50% of the overall damage when properly used, so I'd ask for special love when fixing that specific scaling due to its relevance towards the overall dmg output.

Again, huge thanks and props for your work. I'll keep an eye on this thread so as to know when would the fix be implemented. I eagerly await for it, along with my fellow Blood DKs.

Kind regards,
Arnorolith

**Comment by Hulkster-WowMania** [comment]
Easily confirmed, melee hits are working fine, but as you can see, my DK's Icy Touch hit for 3968 damage but the rune weapon's icy touch only hit for 400 damage, which is roughly 10% instead of 50%.  Other offensive spells and abilities yielded the same results.  The dot applied by rune weapon's frost fever is also doing 10% of regular damage.

http://www.wow-mania.com/armory/?spell=49028

![image](https://user-images.githubusercontent.com/9828794/31500558-4e5b7b42-af2d-11e7-882b-ac295a4702ae.png)

![image](https://user-images.githubusercontent.com/9828794/31500565-55d69c8a-af2d-11e7-9f6e-4f3311d08067.png)

**Comment by Mobius14** [comment]
what is the status of this bug/report?

**Comment by AyrStormborn** [comment]
I've waited for a couple of days before answering, Mobius, in hope that the person in charge would answer. However, despite how much its relevance has been emphasized and the fact that it has already been confirmed, there is no sign of progress in the resolution of this issue.

**Comment by Plege** [comment]
As soon as a fix is worked out I'm happy to recheck and confirm if working properly. Depending on the complexity of a fix, other issues pending (reported on github or server issues) and a bunch of other factors time varies until a bug can be fixxed and confirmed.

**Comment by Mobius14** [comment]
The milestone is set on 47, that milestone is set to release on the 1st of november. My question about the status was to reasure this report would stay on radar.

**Comment by fvicaria** [comment]
Please test it now in dev.
