### ISSUE TITLE
Fishing up Mr. Pinchy does not trigger ahcievment

### ISSUE THREAD

**Issue by DipSpitt** [WoWManiaUK/Redemption#1720]
At apprx. 2200 server time I successfully fished up Mr. Pinchy (http://www.wow-mania.com/armory/?item=27388#contained-in-item) while working towards my "Salty" (http://www.wow-mania.com/armory/?achievement=1516)

Fishing him up is supposed to proc the "Mr. Pinchy's Magical Crawdad Box" Achievement (http://www.wowhead.com/achievement=726/mr-pinchys-magical-crawdad-box#comments) but it did not.

I use up to date client and launcher.

**Comment by squalllh1989** [comment]
Hello DipSpitt, thank you for take your time to report the problem you found here and help us to improve the server. Hower, you must be mistaken about the problem you reported here: Fishing up Mr. Pinchy didn't give you the archivement ["Mr. Pinchy's Magical Crawdad Box"](http://www.wow-mania.com/armory/?achievement=726), you need to use [Mr. Pinchy](http://www.wow-mania.com/armory/?item=27388) to [make a wish](http://www.wow-mania.com/armory/?spell=33060), the wish can give you one of many effect, only when you get a companion from the wish, the [Magical Crawdad Box](http://www.wow-mania.com/armory/?item=27445) and use it to get your [Magical Crawdad](http://www.wow-mania.com/armory/?spell=33050) that you get your archivement, You should notice that [Mr. Pinchy](http://www.wow-mania.com/armory/?item=27388) have only 3 charge with the cooldown of 2 days, so if you used all 3 charge and didn't get your companion from those 3, you will have to fish up another [Mr. Pinchy](http://www.wow-mania.com/armory/?item=27388) and keep trying again. I have already did this on my main character in the game, so i am sure that this is working properly. If you still have any other problem in this, please feel free to commend below, i will try to help you to my best.
