### ISSUE TITLE
Missing pets

### ISSUE THREAD

**Issue by msbodhy** [WoWManiaUK/Redemption#1722]
On my hunter two of my pets  have gone missing a sliver back gorila and a devilsaur. I was in a dungeon and did use "call stabled pet" ability to switch pets at that time i noticed two are missing, I didn't pay attention to it since there was a lag spike at the time so displays might have a delay in that case, but  after when  i finished dungeon, i went to stable master to exchange a pet and noticed that those two are really missing. Erasing  chache didn't solve the issue ,also Gm couldn't help with this problem so i hope you can figure out what happened and solve it so it doesn't happen again.

**Comment by Mobius14** [comment]
Using [call stabled pet] is something not to take lightly. You can loose pets when, for example, your current pet is dismissed and you use [call stabled pet] to get a pet out. A dismissed pet will not exchange spots with the stabled pet you pick. (I think this is what happened to you)

My advice is also to allways have max. 4 pets (1 active 3 in stable 1 slot free) If you use [call stabled pet] you can then manually exchange the active pet to the empty slot and pick your new pet. Also I recommend doing this when changing talentspecs. (change spec when all pets are stabled and after that take 1 out) 

I hope this helps you out. 

Kind regards,

Game Master 
Mobius

**Comment by msbodhy** [comment]
That is sure useful information.

**Comment by Echinaceax** [comment]
just a liitle update 
a GM asked me to check this out on how a hunter can lose their pet fully when pet switching 

5 pets all alive (using pet carrier)
https://i.gyazo.com/c926ec5b2dbb9d9cb5cb647e9a64b61c.mp4
5 pets all alive (using stable master)
https://i.gyazo.com/a81554fb510e8edd58e5ba2bd5c1fd75.mp4

reproduce is
dead pets cant be stabled (that make sense in my opinion) 

Dead pet (using stable master)
https://i.gyazo.com/8872288f4ec3b51c2b160d3ec204365a.mp4

Dead pet (using pet carrier)
https://i.gyazo.com/3ffd746bc65011a770137ed3c52aa66a.mp4

hunters make sure your pets are alive first ❤️
