### ISSUE TITLE
[Quest] valkyrion must burn bug

### ISSUE THREAD

**Issue by anzo31** [WoWManiaUK/Redemption#1724]
The Quest: http://www.wow-mania.com/armory/?quest=12953
Issues: You cant use the gun that you shoot the valkyrion down with. When you go over and click on the gun you dont jump in them. Then is say "spell not ready yet" and got the quest item in my bag.
![wowscrnshot_101217_045421](https://user-images.githubusercontent.com/8068585/31476943-75a23d54-af09-11e7-910e-6a6c289a1fd0.jpg)

**Comment by fvicaria** [comment]
Fixed.
