### ISSUE TITLE
Cache of the Ley-Guardian unlootable

### ISSUE THREAD

**Issue by halendia** [WoWManiaUK/Redemption#1725]
Twice this has happened to me now, but seemingly if you die during the fight vs. Ley Guardian Eregos in the Oculus, you are unable to loot the cache which drops if you queue Random Heroic. It shows up in the loot window but with autoloot the window opens briefly and closes automatically, opening the chest without autoloot on and attempting to retrieve the item also closes the window but adds nothing to your inventory while the cache remains in the chest.

A more specific description of what happened:
I queued Random heroic with 2 friends. We fought Eregeos with 4 amber and an emerald drake, I played emerald and accidentally killed myself with one of my spells, the boss was around 10% HP. My character died from fall damage on the first floor where you enter the instance. I waited until the boss was dead and we rolled for the loot that dropped, I won a frozen orb and an abyss crystal from the boss (they were added to my inventory), so I assumed that even though I fell very far away I was still eligible for loot. Everyone left the party so I released spirit and ran in myself. I flew back up with my dragon and the lootbox still contained a cache which I attempted to loot unsuccessfully.

![wowscrnshot_101217_112641](https://user-images.githubusercontent.com/32733181/31489222-503687d2-af40-11e7-89bb-d0a4a316e9e8.jpg)

**Comment by fvicaria** [comment]
Were you in RDF or a pre-made group?

**Comment by halendia** [comment]
We were 3 people, 1 tank (me) and 2 DPS queueing for daily random heroic. The healer and 3rd DPS were recruited automatically through the dungeon finder. So partly premade.

**Comment by halendia** [comment]
I suppose from the way you explained it it is "working as intended". Still seems a bit off, but thank you.

**Comment by fvicaria** [comment]
Yes. The only possible bug here is if you had the aura before dying and then it disappeared.

**Comment by squalllh1989** [comment]
This problem is happen in retail as well, the cache is only lootable for your party member when all party member is still in the party, if some one leave the group before you loot the cache from the chest, it will become unlootable, the only way to avoid this is go for the chest and loot it right away before some one in the group leave.
In retail the gm will sent the person who got this problem the cache after they open a ticket, i will leave this as to Janitor to decide what he will chose to solve this or leave this as it, because it's exactly the same problem like in retail (still nice if we can solve this problem tho)

**Comment by squalllh1989** [comment]
This is some info you may wanna read about what happen in retail, if it could help a bit to decide: http://www.wowhead.com/item=52676/cache-of-the-ley-guardian#comments

**Comment by squalllh1989** [comment]
And regardness of how you premade the party or not, it will be lootable for you if you or your party chose to queue "random", not "specific for the oculus", and all your party member still in the party after they killed the guardian.

**Comment by fvicaria** [comment]
No. This is a RDF loot. So it will NOT be lootable to those that did not join it. That much is correct.

**Comment by squalllh1989** [comment]
I think you must have misunderstood my explain then, this is the case:
- you or your party queue for a "random heroic dungeon" through the RDF system
- You get a "Heroic - The oculus" from the random queue, you and your party join and clear it (killed last boss)
- Here is where the problem begin:
+ If no one in your party leave the group yet, you and all who queued for "random" from the RDF system will be able to loot the cache (who are in the group but queue for a specific for the oculus heroic won't be able to loot the cache)
+ If at least one of the member in the group leave the group (which make your party do not have 5 people - a full party), no one in the group can loot the cache anymore, regardness of you queue for a "random" or not
=> You **must quickly loot the chest for your cache before some one in the party leave** or you won't be able to get your cache anymore, this is the problem

**Comment by fvicaria** [comment]
OK. But this is not his issue. He had a mixed group, not all had the aura to start with.

**Comment by halendia** [comment]
We all had the aura because we queued random. Everyone else got the cache but me, because I died and released after loot rolls, and by the time I re-entered the instance I was alone. I think @squalllh1989 is on to something.

**Comment by fvicaria** [comment]
I may try to look into this but since the issue was on 3.3.5a. There will no official fix.
