### ISSUE TITLE
Heroic resets in "Raid Info" and Calendar mismatched

### ISSUE THREAD

**Issue by halendia** [WoWManiaUK/Redemption#1726]
"Raid Info" claims Gundrak lock "Expired", Calendar claims it expires tomorrow.
![wowscrnshot_101217_114150](https://user-images.githubusercontent.com/32733181/31489939-ac5b29c6-af42-11e7-9be3-6275ca07d415.jpg)
![wowscrnshot_101217_114157](https://user-images.githubusercontent.com/32733181/31489940-ac741b16-af42-11e7-8c46-33bfc5a332b1.jpg)

Similar issue on alt character, where expired Icecrown Citadel lock shows up at a later date in the Calendar.
![wowscrnshot_101217_114725](https://user-images.githubusercontent.com/32733181/31490126-3acde27a-af43-11e7-8270-e898beae38a6.jpg)
![wowscrnshot_101217_114739](https://user-images.githubusercontent.com/32733181/31490128-3ae3499e-af43-11e7-99cc-f812bb1352aa.jpg)

**Comment by fvicaria** [comment]
Also a visual refresh issue. I will check.

**Comment by Mobius14** [comment]
Allways check [raid info] for accurate raidlock info.

**Comment by halendia** [comment]
@Mobius14 I do always do :)

**Comment by fvicaria** [comment]
I could not reproduce this. Please close the client and delete cache.
