### ISSUE TITLE
Power Word: Fortitude buff displays incorrect value

### ISSUE THREAD

**Issue by halendia** [WoWManiaUK/Redemption#1727]
Spell Power Word: Fortitude with talent [Improved Power Word: Fortitude ](http://www.wow-mania.com/armory/?spell=14767) applies the correct value but displays the wrong one among active buffs.
![wowscrnshot_101217_120319](https://user-images.githubusercontent.com/32733181/31490953-fa391da8-af45-11e7-96c3-db682e3b5416.jpg)

Buff description claims it only gives 165 stamina, which is incorrect.
![wowscrnshot_101217_120331](https://user-images.githubusercontent.com/32733181/31490954-fa4ef948-af45-11e7-91ca-f9d1578f3a20.jpg)

**Comment by fvicaria** [comment]
This is visual. Can be cash issue or spell rank.

**Comment by fvicaria** [comment]
@halendia If you wish to join our test team we always need some help. Just contact me or Hulkster in-game. or via Skype.

**Comment by squalllh1989** [comment]
Confirmed on dev.
- Before buff and talent (basic stat) - 65 stamina
  Basic spell info display: +165 stamina
![wowscrnshot_101217_172234](https://user-images.githubusercontent.com/27235989/31491674-47190404-af72-11e7-8170-f48e72412a9b.jpg)
- No talent and buffed - 230 stamina (correct) display buff: +165 stamina (correct)
  Buff display: +165 stamina (correct)
![wowscrnshot_101217_172303](https://user-images.githubusercontent.com/27235989/31491704-5c009b0c-af72-11e7-9322-6455417b19fd.jpg)
- Talented stat - 67 stamina (correct)
  Spell info display: +214 stamina
![wowscrnshot_101217_172341](https://user-images.githubusercontent.com/27235989/31491816-d444c944-af72-11e7-8d81-68695752bd06.jpg)
- Talented buff - 290 stamina [= (65 (basic stat) + 214 (talented spell buff))*104% (talent increase on stamina)]
 Buff display: +165 stamina (incorrect, should be +214 stamina like the info in spell book show)
![wowscrnshot_101217_172358](https://user-images.githubusercontent.com/27235989/31492064-acfb42cc-af73-11e7-8dc8-99aadd6a289a.jpg)

**Comment by fvicaria** [comment]
Is this really just is just a visual issue?

**Comment by squalllh1989** [comment]
yes, this is just a visual bug, the spell is working correctly
