### ISSUE TITLE
UBRS: Solakar Flamewreath

### ISSUE THREAD

**Issue by zinikh** [WoWManiaUK/Redemption#1728]
the event father flame in UBRS to summon the boss Solakar Flamewreath does not work, we can loot the crystal to get the "held in off hand" item but the mobs and boss do not spawn.

**Comment by Hulkster-WowMania** [comment]
Solakar Flamewreath is spawned at the end of the "Father Flame" event in the Upper Blackrock Spire Rookery. You need to "use" or loot "Father Flame" to start the event, where 6 waves of mobs starts coming towards you, last wave being Solakar Flamewreath.  This also causes the quest for priests 'Anthions Parting Words' and follow-ups to be impossible.

Currently, when you press on or loot "Father Flame" nothing happens, event is not triggered and you can't get access to Solakar boss.

Father Flame Offhand - http://wow-mania.com/armory/?item=13371
Father Flame Object (where the offhand is looted from) - http://wow-mania.com/armory/?object=175245
Solakar Flamewreath - http://wow-mania.com/armory/?npc=10264
