### ISSUE TITLE
[Quest] Get to Getry

### ISSUE THREAD

**Issue by mephorash** [WoWManiaUK/Redemption#1731]
http://www.wow-mania.com/armory/?quest=11703

Players have to turn this quest (Get to Getry) in to "Shadowstalker Getry" (http://www.wow-mania.com/armory/?npc=25729). Then he should give the next quest "Foolish Endeavors" (http://www.wow-mania.com/armory/?quest=11705). After starting the quest "Foolish Endeavors", "Shadowstalker Getry" should move down the tower, and an event should start. After the quest is completed and the event ends "Shadowstalker Getry" should reset itself and move back to the top of the tower he was standing at the start of the quest "Foolish Endeavors". While "Shadowstalker Getry" is at anywhere except top of the tower, he should not take in the quest "Get to Getry" or start the quest "Foolish Endeavors".

What currently happens is, after the event of the quest "Foolish Endeavors", "Shadowstalker Getry" doesn't reset itself and move back to the tower, so the players cannot turn in "Get to Getry" or start "Foolish Endeavors". Thus, these quests are doable only once after every server reset.

**Comment by fvicaria** [comment]
This happens when players abandon the quest half-way through, unfortunately.

**Comment by mephorash** [comment]
Yes, a GM just reset "Shadowstalker Getry" and after i completed the quest, he went back up to the tower.

**Comment by fvicaria** [comment]
I need to check fix for the case when players abandon it.
