### ISSUE TITLE
[Quest] The killing time don't work

### ISSUE THREAD

**Issue by mosaik31** [WoWManiaUK/Redemption#1732]
in this quest should open a portal that teleports to undercity, but that does not happen without getting me to finish the quest.
I would like to point out this problem ... thank you!

**Comment by fvicaria** [comment]
Please follow the procedure described below before creating a new issue:
[How to Properly Report an Issue](https://github.com/wow-mania/Redemption/wiki/How-to-Properly-Report-an-Issue)

This will help developers identify and fix the issue quicker. Incorrectly or unclear reports will simply be deleted.
