### ISSUE TITLE
[quest] The killing time

### ISSUE THREAD

**Issue by mosaik31** [WoWManiaUK/Redemption#1733]
the players after accepting the quest from the king of stormwind should cross a portal open to jain that teleports under (http://www.wowhead.com/quest=13371/the-killing-time) to conclude the quest "The killing time ".
But this does not happen because the portal does not open and does not allow the telecast to undercity and then the end of the quest

**Comment by fvicaria** [comment]
Duplicate #1227 
Please search before posting.
