### ISSUE TITLE
[Dungeon] Utgarde Pinnacle Boss: Svala Sorrowgrave

### ISSUE THREAD

**Issue by Wyrwinerka** [WoWManiaUK/Redemption#1734]
Hi. There is a problem with boss Svala Sorrograve. When she reaches 50% of HP, she should use Ritual of The Sword Abilitty wich cousing that one of party members is teleported on middle of pedestal, then 3 ghosts are appirng and holds him in middle, until sword fall down and kill or just done its cooldown. The problem is that Svalla is not using tat Ab correctly. She is teleporting one of dung members and summoning ghosts, but shes not immune and Sword is not apearing to kill. It couses the Achivment: The Incredible Hulk undoneable. Can you fix it? Thank you

Gromoslaw.

**Comment by fvicaria** [comment]
It is very unlikely that we will be doing anything on this one. Although we recognize that there are differences from the retail version it does works quite well and the differences do not affect the mechanics of the fight or the completion of the dungeon.
Having said that, I will take a look and see what can be done.
Thanks for the report.
