### ISSUE TITLE
[Quest] Springing the Trap

### ISSUE THREAD

**Issue by AnotherMoron** [WoWManiaUK/Redemption#1735]
http://www.wow-mania.com/armory/?quest=11969

At the end of the event started by using "Raelorasz' Spark" (http://www.wow-mania.com/armory/?item=44950) it dosen't mark the quest objective "Malygos lured" as completed after "Malygos" (http://www.wow-mania.com/armory/?npc=26310) and "Keristrasza" (http://www.wow-mania.com/armory/?npc=26237) dissapear

**Comment by fvicaria** [comment]
Works. Please search before posting. There are plenty of info on this quest on the previous issues.
