### ISSUE TITLE
[Spell] Ice Lance

### ISSUE THREAD

**Issue by Headlinerko** [WoWManiaUK/Redemption#1737]
Hello,

Let's say im fighting at max range (in my case 36 yd) and I just got Frostbite proc on creep and it's frozen. I immediately cast Ice lance but my Water's Elemental waterbolt (or party member's spell) is already in air and breaking the freeze effect just after my projectile is released. The problem is that my Ice Lance still does bonus (tripple) damage even if there's no freeze effect on its impact. It's giving me a little bit advanntage.

In general I would say that spell damage is calculated at the time of projectile release instead of projectile impact.

**Comment by fvicaria** [comment]
Please follow the procedure described below before creating a new issue:
[How to Properly Report an Issue](https://github.com/wow-mania/Redemption/wiki/How-to-Properly-Report-an-Issue)

This will help developers identify and fix the issue quicker. Incorrectly or unclear reports will simply be deleted.

**Comment by Headlinerko** [comment]
What exactly is unclear?

**Comment by fvicaria** [comment]
What is the item? What is the spell? I need links, please.
