### ISSUE TITLE
[Dungeon] Halls of Stone - Invisible, invincible NPC Abedneum hitting player until out of instance

### ISSUE THREAD

**Issue by kolci** [WoWManiaUK/Redemption#1739]
In [Halls of Stone](https://wow.gamepedia.com/Halls_of_Stone), there is an [NPC called Abedneum](https://wow.gamepedia.com/Abedneum), which keeps hitting a player from the moment it appears (triggered by quest from [Bronzebeard](https://wow.gamepedia.com/Brann_Bronzebeard)), to the moment a player leaves the instance.
He is hitting with melee attacks, not for much, but its anoying.

Notes: [Reading a bit more about the encounter](https://wow.gamepedia.com/Tribunal_of_Ages), it is not much blizzlike.

**Comment by fvicaria** [comment]
As is.
This is the computer defences.

**Comment by kolci** [comment]
Could it be done, so the computer defences only defend in its area (room: [Tribunal of the Ages](https://wow.gamepedia.com/The_Tribunal_of_Ages)) and not the entire instance? For example, it follows player as far as the [Forge of Wills ](https://wow.gamepedia.com/Forge_of_Wills) (where the [Sjonnir The Ironshaper boss ](https://wow.gamepedia.com/Sjonnir_The_Ironshaper) is).

**Comment by fvicaria** [comment]
I will check this today.
