### ISSUE TITLE
Rogue glyph missing

### ISSUE THREAD

**Issue by Godzila1234** [WoWManiaUK/Redemption#1741]
In the armory website there is Glyph of Envenom, but in the game is nowhere to be found i have full inscription from reasurch and from books and don`t have it neater could be found on AH.
Thank you for your attention and good job!
Have a nice day!
http://www.wow-mania.com/armory/?item=45908

**Comment by fvicaria** [comment]
This glyph is not part of 3.3.5a anymore.
