### ISSUE TITLE
Paladin Guarded by the light

### ISSUE THREAD

**Issue by stwarlord** [WoWManiaUK/Redemption#1745]
Hi
It seems Divine plae is not refreshing when you fund guarded by the light passives.
You must wait 1 mins no matter what.

**Comment by fvicaria** [comment]
Please follow the procedure described below before creating a new issue:
[How to Properly Report an Issue](https://github.com/wow-mania/Redemption/wiki/How-to-Properly-Report-an-Issue)

This will help developers identify and fix the issue quicker. Incorrectly or unclear reports will simply be deleted.

**Comment by stwarlord** [comment]
Hi,
I'm using launcher and fully updated client. One of the paladin skill named Divine Plea is not working correctly.
Divine Plea (Paladin Skill) - http://www.wow-mania.com/armory/?spell=54428

As you can read description below "Guarded by the light" passive talent is not refresing duration of that skill. 
Guarded By the light (Paladin Passive Talent) - http://www.wow-mania.com/armory/?spell=53583

Reduces spell damage taken by 2147483647% and gives a 50% chance to refresh the duration of your Divine Plea when you hit an enemy. In addition, your Divine Plea spell is 50% less likely to be dispelled.
