### ISSUE TITLE
[Quest] Disclosure

### ISSUE THREAD

**Issue by fragygr** [WoWManiaUK/Redemption#1746]
After accepting the quest Disclosure from Overlord Dracuru, he gives you a Scepter of domination, it suppose to open the way for the upper chamber, you half to take the blue teleport but this time it doesn't take you to the ground area it supposed to teleport you to the upper chamber, this never happens and there is no other way to go to the upper chamber and so no way to finish the quest. Thank you.

**Comment by fvicaria** [comment]
Please follow the procedure described below before creating a new issue:
[How to Properly Report an Issue](https://github.com/wow-mania/Redemption/wiki/How-to-Properly-Report-an-Issue)

This will help developers identify and fix the issue quicker. Incorrectly or unclear reports will simply be deleted.

**Comment by fragygr** [comment]
I'm sorry for the inconvenience.
- I use the search engine of the site and I didn't find another issue for disclosure quest.
- I discover the problem with my Death knight "Firebringer" Character, There was another player in the area, that I didn't remember the name of his/her character, he or she has the same problem, I don't know if he or she opened a ticket.
- I don't have addons except quest helper that help with the quests so I believe that it's not a addon problem.
- Yes I am using WOW - Mania.
- I am using the latest version of the launcher, the one that is in the site right now, I have just download it this week with the patch for 2.1.2.
- I have describe above the steps that I follow.
- Also I describe what it should happen from internet search, there is also a video on youtube https://www.youtube.com/watch?v=UEq8fEz8UOo.
Thank you again for your time, if I can do something that I can help to solve the problem please inform me on me e-mail. Fragygr@hotmail.com
P/S Forgive my English.

**Comment by fvicaria** [comment]
Can someone test this in dev?

**Comment by fvicaria** [comment]
Go back to the green teleporter and you will get back to Overload Drakuru.
I have just done the quest fine.
