### ISSUE TITLE
[Minor] Dalaran Inn

### ISSUE THREAD

**Issue by Hajzlopuc** [WoWManiaUK/Redemption#1747]
Hello,

as a Horde player I shouldn't be able to enter Alliance Inn, I should be ported out as soon as I try to enter but now I'm able to move there freely. 

http://puu.sh/y0xRj/962b81642e.jpg

**Comment by fvicaria** [comment]
This is working fine on dev. I will re-test tomorrow after the update.
Thanks.

**Comment by fvicaria** [comment]
Works fine in red after restart.

**Comment by Hajzlopuc** [comment]
Does not seems so for me

http://puu.sh/y1191/c56df331b9.jpg

**Comment by fvicaria** [comment]
What is your char name? I will get a gm to go check with you.
I tried this morning and it was working on my chars.

**Comment by Hajzlopuc** [comment]
Kokotka
