### ISSUE TITLE
[Quest] The killling time

### ISSUE THREAD

**Issue by AnotherMoron** [WoWManiaUK/Redemption#1748]
http://www.wow-mania.com/armory/?quest=13371

A portal is supposed to appear to send you a staged version of tirisfal glades, where you can find Broll Bearmantle (http://www.wow-mania.com/armory/?npc=32376) and Valeera Sanguinar (http://www.wow-mania.com/armory/?npc=29607).

But no portal appears and when I go to tirisfal glades by myself Broll Bearmantle isn't there to turn in the quest. (The marker was on the right spot but no one to turn in the quest)

**Comment by fvicaria** [comment]
Please follow the procedure described below before creating a new issue:
[How to Properly Report an Issue](https://github.com/wow-mania/Redemption/wiki/How-to-Properly-Report-an-Issue)

This will help developers identify and fix the issue quicker. Incorrectly or unclear reports will simply be deleted.


Duplicate #1227
