### ISSUE TITLE
[Quest] Conquest Pit: Bear Wrestling!

### ISSUE THREAD

**Issue by tpalasz** [WoWManiaUK/Redemption#1750]
Hello,
when attempting to do the quest Conquest Pit: Bear Wrestling! (http://www.wowhead.com/quest=12427), the mob simply disappears when you kill it, no corpse, no kill credit, though you do get experience for the kill. Re-tried multiple times, tried disbanding party, etc.

Unsure if the other quests in the pit chain are behaving the same way (since i couldn't get past this one) but i'll leave the links here anyway, if you may look into them.
http://www.wowhead.com/quest=12428
http://www.wowhead.com/quest=12429
http://www.wowhead.com/quest=12430
http://www.wowhead.com/quest=12431

**Comment by tpalasz** [comment]
New information: we were in party. Only the person who deal killing blow can complete this and next quest in chain. Other party members cant complete, need to repeat quest.

**Comment by fvicaria** [comment]
Yes that is a known issue of some group quests unfortunately. Not specific to this quest.
I will close this and try to sove it at a core level.

**Comment by tpalasz** [comment]
Thank you!
