### ISSUE TITLE
[Item] The Horseman's Reins - flying animation

### ISSUE THREAD

**Issue by axcyqt** [WoWManiaUK/Redemption#1751]
The flying animation of the Horseman mount is bugged. When flying, it looks like its just running like retarded since the legs move with the speed of light.

**Comment by fvicaria** [comment]
Please follow the procedure described below before creating a new issue:
[How to Properly Report an Issue](https://github.com/wow-mania/Redemption/wiki/How-to-Properly-Report-an-Issue)

This will help developers identify and fix the issue quicker. Incorrectly or unclear reports will simply be deleted.

**Comment by fvicaria** [comment]
Tested and works fine.
Close client and delete cache.
If the problem continues, open a ticket or contact me via Skype.

**Comment by squalllh1989** [comment]
Confirmed in dev, [The Horseman's Reins](http://www.wow-mania.com/armory/?item=37012) work good and look cool on ground, but in the air, his animation of walking is very fast, look just like he swimming in the air, kind of crazy and not cool at all (tested with client updated, deleted cache to retry multiple time)

**Comment by fvicaria** [comment]
You probably got the wrong spell for some reason. Which one is the active spell when you see that?

**Comment by squalllh1989** [comment]
Not sure what happen, but now it's good now, the animation in the air is good and look cool, kind of weird,   everything is the same as before, but after i go out for dinner and get back, it's good again :D.
