### ISSUE TITLE
Headless horseman dungeon broke

### ISSUE THREAD

**Issue by DragonsDeadFlame** [WoWManiaUK/Redemption#1752]
I put together a group for the headless horseman dungeon on my holy priest Healingclaws, with Azmodes, Mcximus, Trycton, and 1 other, none of us had done headless horseman today, we queued up for the dungeon, all 5 of us took our turns summoning and killing the headless horseman after we killed him the 5th time, the dungeon still didnt complete so we didnt get the maniac points or the loot bag, we requed but none of us could summon the horseman again, i opened a ticket with a gm but the said they couldnt do anything untill i submitted a ticket here

**Comment by ingelinge40** [comment]
I have  see them do it and try myself but nothing happend it did not complete

**Comment by fvicaria** [comment]
We need to confirm this with an independent group.

**Comment by squalllh1989** [comment]
Doesn't have any problem with all of my char, get the mp and bag right away, and 2 eof when open the bag.
