### ISSUE TITLE
[Quest] Shutting Down Manaforge Coruu id 10321

### ISSUE THREAD

**Issue by Meshanda** [WoWManiaUK/Redemption#1753]
http://www.wowhead.com/quest=10321/shutting-down-manaforge-coruu

During the event of that quest we must defend a control console. 
The problem is that on retail you have the time to select the mob and attack them, however on the server, the npc that spawns during the event cancel it as soon as they reached the center of the room.

They should instead begins a cast as seen here (leaving time to the player to attack them)  :  
http://www.wowhead.com/quest=10321/shutting-down-manaforge-coruu#videos:id=95062

**Comment by fvicaria** [comment]
Can you tell me the name of the mob or its link?

**Comment by fvicaria** [comment]
It works fine. This is a chance event. You have to stay there and keep killing the mobs until the credit is given. It will take no more than half a dozen until you are given credit.

**Comment by squalllh1989** [comment]
work fine, the mob that come to abort the shutdown didn't have cast time visible, but it seem they still casting.
