### ISSUE TITLE
[Quest] Incoming Gumdrop

### ISSUE THREAD

**Issue by GMAltax** [WoWManiaUK/Redemption#1755]
The quest: http://www.wow-mania.com/armory/?quest=8355d

GM altax here I have two people reporting this Quest in game and both time I had tested it and found out it is indeed bug. SO I told both to repport it but I dont think they did.

So you shall walk over and do / train on the [npc] Takvash del Kissel   Id: 6826 
But nothings happen when you do so.
![wowscrnshot_101917_125624](https://user-images.githubusercontent.com/32928677/31768028-bd742646-b4cd-11e7-9cac-e246ca1f04e4.jpg)

**Comment by squalllh1989** [comment]
Confirmed, [this quest](http://www.wow-mania.com/armory/?quest=8355) and [the horde version](http://www.wow-mania.com/armory/?quest=8358) both didn''t work, nothing happen aftter you do /train at the quest giver.
