### ISSUE TITLE
[Item] Magic Broom

### ISSUE THREAD

**Issue by squalllh1989** [WoWManiaUK/Redemption#1756]
- [Magic Broom](http://www.wow-mania.com/armory/?item=37011) should changes depending on your Riding skill and location, but currently, when you use it, you got a +0% speed ground mount only, even if you have artisan flying and cold weather flying. (tested in northen, at krasus's landing as well as some other place where you can use any fly mount without any trouble).

**Comment by ManiaLightmare** [comment]
For what it's worth, I can confirm the item is not scaling for any of my characters that have it either.
