### ISSUE TITLE
[Quest] The Storm King's Vengeance

### ISSUE THREAD

**Issue by GMAltax** [WoWManiaUK/Redemption#1758]
Quest: http://www.wow-mania.com/armory/?quest=12919

There is a bug where when players use the knock back ability it make so the action bar on Gymer id=29647 not work/respond. Then players get stock on him or they are not on him but they still got the aura.

I had investigate the Issue to confirmed in game that this is happening. The player I were look at were fighting Thrym id=29895 and use the knock back ability that the action bar stop responds.

Report sign by:
Gamemaster Altax

**Comment by fvicaria** [comment]
Gymer has no hability called throw back. Please link the actual spell or hability name. I tried all 4 Gymer's hability and they work.
I did the quest fine.
