### ISSUE TITLE
[Item] Headless Horseman's Mount

### ISSUE THREAD

**Issue by ManiaLightmare** [WoWManiaUK/Redemption#1760]
[Headless Horseman's Mount](http://www.wow-mania.com/armory/?spell=48023)

The mount does not work anywhere that restricts flying.  It should function as both a ground or flying mount depending on where you.

**Comment by Meshanda** [comment]
And it doesn't work in Azeroth, would be very nice if we could use it there.

**Comment by fvicaria** [comment]
Same issue as magic broom
