### ISSUE TITLE
Words of Power (Quest)(Northrend)

### ISSUE THREAD

**Issue by Samaell1990** [WoWManiaUK/Redemption#1761]
Words of Power(quest) is not working, when you kill the 3 moobs :
High Priest Naferset
High Priest Talet-Kha
High Priest Andorath
they don't drop the quest item's :
High Priest Naferset's Scroll
High Priest Talet-Kha's Scroll
High Priest Andorath's Scroll
instead they just disappear(their corpses) rely fast, and you'r not able to loot them at all.
p.s. The quest is bugged for the horde and the alliance.
Location Temple city of En'kilah, Borean Tundra.

http://www.wow-mania.com/armory/?quest=11640

**Comment by fvicaria** [comment]
Done the quest twice with no problems.
![image](https://user-images.githubusercontent.com/9414661/31821569-7b37da54-b59d-11e7-92ae-b7d5d35f1632.png)

**Comment by Samaell1990** [comment]
I try to do it 30min ago and it wasn't working i asked a gm for help and he told me to report the bug here so i did.

**Comment by fvicaria** [comment]
Thanks a lot. I will try in Redemption now to be sure.

**Comment by fvicaria** [comment]
I confirmed the issue in Redemption. We have a scheduled restart in a few minutes hoping it will solve it.
