### ISSUE TITLE
Problems with dailies in the Valiant's charge quests

### ISSUE THREAD

**Issue by Bartok14** [WoWManiaUK/Redemption#1763]
My issue is that I have completed the quests for argent tournament. I have achieved a champion status with Silvermoon after completing the valiant's charge quest with the associated dalies. the issue is that I am supposed to be able to pick up the valiant's charge quest for the other race's that are there. Unfortunately I picked up the quest for orgrimar and the associated dailies are not there and i can't get them to work. Subsequently upon dropping the quest and repicking it up this did not solve the issue. On top of that I can't pick up the valiant's charge quest for the other race's in the tent. Any help with fixing this would be greatly appreciated as I wanted to buy the mounts associated with the quests. Thanks!

**Comment by squalllh1989** [comment]
I don't know how did these quest work in retail, need some one that acually play retail to have a word on this, but this is how wow mania currently work, and i have done all of these with my main char (a bloodelf mage):
- After you finish your daily with your home city (silvermoon) and become your city's champion (champion of silvermoon city), you unlock the quest for ogrimmar.
-After you finish your daily with ogrimmar  and become champion of ogrimmar, you unlock the quest for senjin (or it is other city, i don't remember exactly).
So what is happening here is: you unlock them one by one, after you finish being champion of one city, you move to next city.
What we need to know here is: is this the right way that it should work, or all other city's daily should be unlock and can be done at the same time after you become champion/variant of your city ?

**Comment by Bartok14** [comment]
The way you have described it is the correct way that it should be done. You originally do the line of quests for you race city, then you are allowed to become a valiant for the other cities one at a time so for me i became a champion of Silvermoon, which means i can now do the valiant's charge quest for one other city, and then once i finish with that city you can move on to the next. My issue is with once i have become a champion of Silvermoon i go to the Orgrimmar guy and try to become a champion with him, I start the quest and it tells me i owe him 25 valiant seals, but there are suppossed to be daily quests that pop up when i accept the quest "the valiant's charge" which allows you to get those valiants seals. In this case they are not popping up. I have tried dropping and picking up the quest to no avail and on top of this I can't pick up the quest from any of the other race's. So essentially I am stuck.

**Comment by Bartok14** [comment]
Seems to be working now, thanks for the help.
