### ISSUE TITLE
[Quest] Fire Brigade Practice

### ISSUE THREAD

**Issue by cathyr1** [WoWManiaUK/Redemption#1764]
Hello. This seasonal quest http://www.wow-mania.com/armory/?quest=11360 is not working for me. I did succesfully the event and extinguished many fires but got 0 completed for this quest. I´m on alliance side.

If anyone will not reproduce please show me the video and I´ll then do exactly the same as you.

Thanks.

**Comment by fvicaria** [comment]
Works fine. Please check with other players.

**Comment by nimavf** [comment]
It worked completely fine for me.
Got the quest, went to the spot where it was shown by the built-in quest helper on the map.
Got a water bucket and throw it to the burning ogre. Repeated it 5 times and it got completed.
I guess you are probably trying on a wrong fire.
Check the screen shots.
![wowscrnshot_102117_125653](https://user-images.githubusercontent.com/14857593/31850513-080c31c4-b660-11e7-97c6-acee4d69632e.jpg)
![wowscrnshot_102117_125715](https://user-images.githubusercontent.com/14857593/31850515-108d16ec-b660-11e7-9e4e-cc946a447f67.jpg)
![wowscrnshot_102117_125734](https://user-images.githubusercontent.com/14857593/31850517-145404f2-b660-11e7-801d-b110d1a70a45.jpg)
![wowscrnshot_102117_125811](https://user-images.githubusercontent.com/14857593/31850521-1e191b62-b660-11e7-8788-8b92a0ebbdd1.jpg)
![wowscrnshot_102117_125826](https://user-images.githubusercontent.com/14857593/31850522-21e0bbec-b660-11e7-8a0f-88c14a37cdc5.jpg)

**Comment by cathyr1** [comment]
Thanks much, this works fine. I was extinguishing the flames on the buildings Yesterday.
