### ISSUE TITLE
Missing quest mobs

### ISSUE THREAD

**Issue by msbodhy** [WoWManiaUK/Redemption#1765]
The Quest : "http://www.wow-mania.com/armory/?quest=11527 " in the fjords doesn't work properly there should be 5 quest related mobs  but when i came there there where only 2 and after i killed them they didn't re spawn.
![wowscrnshot_102017_213115](https://user-images.githubusercontent.com/32671420/31838832-c3c0fc42-b5de-11e7-9a12-90c304b885cd.jpg)

**Comment by GMAltax** [comment]
This is confirmed.

GMAltax
![wowscrnshot_102017_214930](https://user-images.githubusercontent.com/32928677/31839273-ac539fa4-b5e0-11e7-91d2-e342e6df6ddf.jpg)

**Comment by fvicaria** [comment]
Wait for respawn.  The quest works.

**Comment by GMAltax** [comment]
Hmm wired I try testing it again but it dos not seem that they respwan
