### ISSUE TITLE
[Quest] Forging a Head

### ISSUE THREAD

**Issue by Omegus08** [WoWManiaUK/Redemption#1766]
Quest asks you to go to the frozen lake and mine stormforged eyes from the dead bodies there using a quest item 'Diamond tipped pickaxe'. I go to the body, use the item, cast bar fills and cooldown initiates as though it has complete but no loot window or item appears. repeated on each of the dead bodies multiple times as I lapped the quest area but not once did a loot window appear. GM requested I raise here, please assist.
![wowscrnshot_102017_214952](https://user-images.githubusercontent.com/32968741/31841522-c35d8e48-b5e1-11e7-8fcb-770bec978526.jpg)
Cooldown initiates:
![wowscrnshot_102017_214957](https://user-images.githubusercontent.com/32968741/31841525-c5777e46-b5e1-11e7-9de8-ab0bda13e9f7.jpg)
Quest Details:
![wowscrnshot_102017_215853](https://user-images.githubusercontent.com/32968741/31841553-e3e6e1be-b5e1-11e7-9d39-06540eb43a16.jpg)

**Comment by fvicaria** [comment]
http://www.wow-mania.com/armory/?quest=12985

**Comment by fvicaria** [comment]
Fixed in dev.

![image](https://user-images.githubusercontent.com/9414661/31850557-25d5e3b2-b64c-11e7-8f8a-099df73b12ef.png)

**Comment by Omegus08** [comment]
hmmm seems like i'm mining the wrong things here. The quest states 'dead iron giants' as shown in my pic. But above a smaller stormforged dwarf is shown to be giving the loot. Also, the blue area on the map indicated by the quest does not have burning elementals (as in confirmed pic), only frozen ones. Indeed there are blazing elementals nearby but I cannot find any dwarves there, nor is it over a frozen pond as shown in the pic above. Ive tried on the storm giants but no change, if i could get a map screenshot of the above pics location I can recreate and complete quest.
