### ISSUE TITLE
Mount + Buff macro not castable

### ISSUE THREAD

**Issue by Hajzlopuc** [WoWManiaUK/Redemption#1767]
Hello,

I want to use following macro to buff up before mounting. With just one click, it should cast buff and start mounting simultaneously. I had been using that for like 10 years with every class (on Blizz realms).

It just doesn't work here at all. It gets me on my mount, but never casts a buff.

```
/cast Arcane Intellect (or any buff depending on class)
/cast Mount
```

Any possible fix or help would be greatly appreciated.

**Comment by fvicaria** [comment]
Hi there, thanks for the report but certain combinations of commands do not work.
Try some alternatives or separate them into two macros.
