### ISSUE TITLE
[Quest] Hunting for Ectoplasm

### ISSUE THREAD

**Issue by Nimbulas** [WoWManiaUK/Redemption#1769]
On the part where you need to get 12 Scorched Ectoplasm, Frozen Ectoplasm and Stable Ectoplasm i cant use the [Ectoplasmic Distiller] I have the rocket fuel wich you get from the bag at the beginning of the quest. 
When i try to use the item i get a message that reads: "The spell is not available to you".
Can you take a look at it please.

**Comment by fvicaria** [comment]
Please follow the procedure described below before creating a new issue:
[How to Properly Report an Issue](https://github.com/wow-mania/Redemption/wiki/How-to-Properly-Report-an-Issue)

This will help developers identify and fix the issue quicker. Incorrectly or unclear reports will simply be deleted.

**Comment by fvicaria** [comment]
The item does not work on purpose. There is an issue with the spell. You can kill the needed NPCs without using the item.
