### ISSUE TITLE
Rogue Subtlety perks bugged

### ISSUE THREAD

**Issue by Godzila1234** [WoWManiaUK/Redemption#1771]
1. The perk Slaughter from the shadows doesn`t affect the energy cost of Hemorrhage as it said but the energy cost with the perk is still 30 energy.;
2. The perk Cheat Death in the same section doesn`t appear to work too;
Thank you and have a nice day!

**Comment by fvicaria** [comment]
Should be OK after the update. I could not find anything wrong with Slaughter.

**Comment by Godzila1234** [comment]
Yes Slaughter is fine the original cost of Hemorrague is 35 so with perk is 30... thanks!
