### ISSUE TITLE
The Drakensryd

### ISSUE THREAD

**Issue by Ravenshowl** [WoWManiaUK/Redemption#1775]
You can jump to a drake, but you can't turn and face your enemy and therefore attack her. So you can't complete it. They enemies seems to fall of at random spots, but you can't kill them anyway. 
This is really a major let down, because that means you can't get to Sons of Hodir and get your shoulder enchant (and other stuff).
The picture should be full of possible drakes you could mount, but as you can see, they are really sparse.
![wowscrnshot_102117_223841](https://user-images.githubusercontent.com/32970766/31855694-b116c45a-b6b0-11e7-9c18-fb9dfee82ace.jpg)

**Comment by fvicaria** [comment]
HI there, please try different NPC, they do work, just need to find the correct one.
