### ISSUE TITLE
Random Number Stacks

### ISSUE THREAD

**Issue by Noonlight** [WoWManiaUK/Redemption#1776]
Hello, i was instructed by GM "Agreeable" To relay information about the issue i presented to him/her.

I open guild bank, notice that a few of the items (chestpiece weps etc) are stacked up to and above 2k.  
Which is odd because armor and weps shouldn't stack obviously, also, i throw in a random gem, and it proceeds to stack up to and above 2k, once withdrawn the item returns to normal.

Haven't been able to take advantage of the situation, and i'm not sure if it's my "Gatherer" addon thats messing the bank up, i got the addon from wow manias addon zip.

My guild members have also noticed this phenomena, yet they don't have the Gatherer addon.

Thank you for your consideration, have a good one!

**Comment by fvicaria** [comment]
Can you send me some screenshots, please.
Can anyone confirm this? If this is just visual I will not worry about it.

**Comment by Noonlight** [comment]
No longer seem to be having this issue, thanks!

**Comment by Noonlight** [comment]
![staks](https://user-images.githubusercontent.com/32998802/31867224-168b1e96-b727-11e7-9fae-153352322e88.jpg)

**Comment by Noonlight** [comment]
But heres a screen shot of what it looked like
