### ISSUE TITLE
Transmog Can Not Be Undone

### ISSUE THREAD

**Issue by Ackpfft** [WoWManiaUK/Redemption#1778]
I transmogged (sp?) my chest and weapon and decided it looked terrible. I went back to same vendor and chose "Undo All Transmog" and it worked fine, but when I logged out and back on again the transmogs came back. I tried several more times at the vendor with the same results. I cleared cache, but nothing worked.

**Comment by fvicaria** [comment]
You have to save the character with ".save" or or at the NPC

**Comment by Ackpfft** [comment]
I didn't see that option, so I will give it a whirl and thank you for
taking the time.

**Comment by Ackpfft** [comment]
I just did what you suggested and .saved after undoing the transmog. I also
selected "save set" from the NPC afterwards and when I logged out and back
in again the transmogs popped back on. I don't understand this at all, but
I guess I'm going to have to get used to it.

**Comment by fvicaria** [comment]
Send me a message on Skype or support@wow-mania.com with the name of your char and I will clear your transmogs for you.
