### ISSUE TITLE
[Quest] Sniffing Out the Perpetrator cat not spawning

### ISSUE THREAD

**Issue by stealer0517** [WoWManiaUK/Redemption#1779]
http://www.wowhead.com/quest=12910/sniffing-out-the-perpetrator
There should be a cat next to Khaliisi that you can jump onto after accepting the quest that runs to the cave.
I've been back a few times this week and I haven't seen the cat once.
You can however fly to the cave and finish the other part of the quest by killing the guy in there. 
But you cannot get the first part completed to turn the quest into Brann

**Comment by fvicaria** [comment]
Tiger is there. You are probably in the wrong phase.

![image](https://user-images.githubusercontent.com/9414661/31863984-f1421cf8-b74d-11e7-85ac-9aa500574503.png)

**Comment by stealer0517** [comment]
Then how do I get into the right phase? 
There's no other quests around here.

**Comment by stealer0517** [comment]
New problem.
I can't get onto the cat, and the lady won't talk to me so there's no option to get onto the cat from there.

**Comment by fvicaria** [comment]
Yes I found an issue with it. Open a ticket and ask a GM to complete it for you.
Thanks for the report.

**Comment by fvicaria** [comment]
Fixed. Try again please

**Comment by stealer0517** [comment]
Now the cat is back to not being here.

**Comment by fvicaria** [comment]
![image](https://user-images.githubusercontent.com/9414661/31864410-da5a37b2-b754-11e7-8829-ba1a047f2575.png)

**Comment by stealer0517** [comment]
![wowscrnshot_102217_121842](https://user-images.githubusercontent.com/6968045/31864449-2e31d5c0-b723-11e7-8336-4d941c9415ef.jpg)

**Comment by fvicaria** [comment]
Delete cache

**Comment by stealer0517** [comment]
Tried with a copy that i havent used before and the cat still wasn't there.
Amytis finished the quest for me though.

**Comment by fvicaria** [comment]
Cache is not per character.

**Comment by stealer0517** [comment]
After going AFK for a little bit the cat is here now.
But I meant to say I was using a new copy of a client that I hadn't used before.
