### ISSUE TITLE
Quest: Springing The Trap

### ISSUE THREAD

**Issue by cmschroeder** [WoWManiaUK/Redemption#1780]
Was trying to complete Springing the Trap (http://www.wowhead.com/quest=11969/springing-the-trap), but the quest wouldn't change to completed status at the end.

I used the spark at the signal fire to call Keristrasza. She tosses the corpse of Saragosa at the doorstep of the Nexus and then sets it on fire (while taunting Malygos). Keri then tosses me in the saddle and we circle around the Nexus platforms and eventually descend back to the ground on the opposite side from where we took off. When we land, the script continues, but I'm attacked by a Crazed treant (the KoS variant) and a Spellweaver dragonkin. While I'm battling them, Malygos and Keri exchange pleasentries, Keri is frozen in an ice-tomb, and then both dragons despawn. Quest doesn't get triggered to completed.

Psygoa helped me with the quest and eventually marked it as completed and asked me to log it here.

**Comment by fvicaria** [comment]
Hi there,
Please search here before posting.
This quest works you just need to follow the tips from the previous reports.

**Comment by cmschroeder** [comment]
See [#593](https://github.com/WoWManiaUK/Redemption/issues/593). Apparently there's a specific set of coordinates you must be standing on before the quest will work. IMO, not worth repeating to complete.
