### ISSUE TITLE
[Quest] Stranglethorn Fever

### ISSUE THREAD

**Issue by Pais2017** [WoWManiaUK/Redemption#1781]
I went to the NPC, Doctor Unbagwa, who requests a Gorilla Fang to begin the quest. Upon giving him the requested item, he goes into the summoning phase of the quest and never comes out. 

![wowscrnshot_102317_212108](https://user-images.githubusercontent.com/33046311/31922055-8086338c-b838-11e7-87e5-046a7380d1d0.jpg)

**Comment by AgreeableNZ** [comment]
Can confirm this one i've had the NPC get stuck casting about 3 times in the last two days .die .revive seems to remedy it

**Comment by fvicaria** [comment]
Wait by the NPC. This will force it to attack and brak cast.
