### ISSUE TITLE
Broken freezing trap

### ISSUE THREAD

**Issue by msbodhy** [WoWManiaUK/Redemption#1782]
I noticed an issue with freezing traps in the ares which change after competing one or more quests, for example shadow  vault in ice crown or valley of ancient winter in storm peaks. when the mobs walk over the trap it disappears .i reckon it does activate but they don't get trapped. You can clearly see the trap right by this mobs legs and it didn't  get trapped.
![wowscrnshot_102417_134056](https://user-images.githubusercontent.com/32671420/31941458-347a967e-b8c2-11e7-9f7e-ff509bae0dc3.jpg)

**Comment by fvicaria** [comment]
Can someone test and confirm/dismiss this one, please.

**Comment by Mobius14** [comment]
I can confirm the issue. Tested it in shadowfault where i found that ONLY explosive trap worked. Combat log showed no resists for my traps and traps indeed faded when stepped on.  When tested outside shadowfault in Icecrown all traps worked properly.
