### ISSUE TITLE
blueleaf tubers

### ISSUE THREAD

**Issue by k1ll3r** [WoWManiaUK/Redemption#1783]
quest is bugged when you summone the pet it is suppose to go and dig the tuber but he just follows you

**Comment by fvicaria** [comment]
Quest works perfectly. Read instructions.

**Comment by k1ll3r** [comment]
yeah right tryed it 2 times and it doest go dig the tuber he just follows me guess i`m the problem ?

**Comment by fvicaria** [comment]
I have just done it.
