### ISSUE TITLE
Firesoul

### ISSUE THREAD

**Issue by Tasmanijak** [WoWManiaUK/Redemption#1785]
That is a dager from Ulduar. There is a issue with the transmoging other stuf  to Firesoul.
One gm alrdy tested in game and he said that it dosen't even show for a dager Firesoul to transmog.

**Comment by Mobius14** [comment]
Please be more specific in your report 
[https://github.com/wow-mania/Redemption/wiki/How-to-Properly-Report-an-Issue](url)

**Comment by Mobius14** [comment]
I still managed to test the issue and its pretty straightforward. 

Firesoul is a MAIN hand weapon, it will only be available to transmog MAIN hand weapons with it. 

Kind regards, 

Game Master 
Mobius
