### ISSUE TITLE
[Transmogrification] Cannot Transmog High Warlord Pig Sticker

### ISSUE THREAD

**Issue by Kurioss** [WoWManiaUK/Redemption#1786]
Iv been trying and wanting to transmog my polearm for a while now, and i want it to be High warlord pig sticker, iv transmoged it once before, but now it seems like i cant anymore.

Maybe a bug after newest patch. I dont know but i would really want this transmog.
Help me out!
![untitled](https://user-images.githubusercontent.com/33106831/32029173-16535352-b9f3-11e7-92cc-54c14c5a2c7c.png)

**Comment by Mobius14** [comment]
Pleas be more specific in your report, what item are you trying to mog for example?

**Comment by Kurioss** [comment]
I am trying to Transmog my main hand weapon [Distant Land] its a Two-hand Staff, i have also tryed to Transmog my main hand weapon [Bloodfall] Its a two-hand Polearm. To the Two-hand Polearm [High warlod pig sticker] the when i equip the weapon i want to Transmog and then go to talk with the Transmogrifier and go into Main hand weapon to transmog, my [High warlord Pig stick] is not showing up as u can see in the picture above. iv been trying this on two differant character (A paladin, with an Two-hand Axe) for a while, and it does not work for both of them.

**Comment by Mobius14** [comment]
Tested it: polearm to polearm and doesnt show up as transmog indeed.

**Comment by fvicaria** [comment]
Staff and Polearms have different slots id.

**Comment by Kurioss** [comment]
I tried with both Staff and Polearm, and it did not work with both the weapons.

**Comment by fvicaria** [comment]
I tried both ways and it worked fine.

![image](https://user-images.githubusercontent.com/9414661/32220693-9abd814a-be2a-11e7-8d67-fd1595a3f7c2.png)
![image](https://user-images.githubusercontent.com/9414661/32220727-b8f89c94-be2a-11e7-9d7d-a9436ac7915b.png)

**Comment by Kurioss** [comment]
It works with Polearm to Staff and Staff to Polearm. but not with [High Warlord Pig Sticker], try Transmog the specific weapon [High Warlord Pig Sticker] with a [Distant Land] as an example.

**Comment by fvicaria** [comment]
I will try it.
