### ISSUE TITLE
[Achievement] Volunteer Work

### ISSUE THREAD

**Issue by Daxko89** [WoWManiaUK/Redemption#1788]
"When Jedoga flies up above she will call for a volunteer, simply do not kill the volunteer, let it walk into the circle and sacrifice itself, you should just then heal the tank through the enrage"
This is how is done.What doesn't work is when volunteer is going for sacrifice,its stands there for endless time.Sacrifices doesn't happen at all.In that way achievement can't be obtained.

Achievement: Volunteer work ID:2056
Dungeon: Ahn'kahet: The Old Kingdoms 
Boss: Jedoga Shadowseeker
Note:achievement obtained only in Heroic mode.

**Comment by Daxko89** [comment]
Second day in a row trying ,confirming the bug above.

**Comment by squalllh1989** [comment]
Confirmed, the volunteer didn't sacrifice, he just stand there doing nothing, you are forced to killl the volunteer to continue the enrage, this make the achievement undoable

**Comment by fvicaria** [comment]
Fixed in dev. Needs testing.
