### ISSUE TITLE
[Quest]An Embarrassing Incident

### ISSUE THREAD

**Issue by Geralde92** [WoWManiaUK/Redemption#1789]
Quest Name: An Embarrassing Incident
Quest Items to receive: 1- Vic's Keys

When i try digging up the dirt mounds for the quest instead of getting the item the only thing that spawns is Siltslither Eel. So i figured kill it and I should still get the item but you don't. So I killed them for an hour thinking that it just has a low drop rate and still nothing so then I put in a ticket for the issue and a GM is working with me to resolve the problem.

**Comment by squalllh1989** [comment]
[This quest](http://www.wow-mania.com/armory/?quest=12699) work, just really low drop rate, i have done this before. Also, what happened when a gm work with you to resolve the problem ?

**Comment by squalllh1989** [comment]
In case you insist that it didn't work, i just do this quest again on redemtion with one of my chars, here is the result in 2nd mud loot (must be very lucky :D)
![wowscrnshot_102717_211513](https://user-images.githubusercontent.com/27235989/32108504-1eaa68e6-bb5c-11e7-83e7-de53eceebfcb.jpg)
![wowscrnshot_102717_211534](https://user-images.githubusercontent.com/27235989/32108506-20823aae-bb5c-11e7-9883-8966f1ec0bd1.jpg)
