### ISSUE TITLE
The Drakkensryd Quest in Storm Peaks is bugged

### ISSUE THREAD

**Issue by aherdman** [WoWManiaUK/Redemption#1790]
The Drakkensryd quest, which is part of the Sons of Hodir rep chain isn't working properly for me.  If you are unmounted and start the quest, the quest giver will place you on a proto drake and it will automatically fly you to the storm temple, where protodrakes and protodrake riders are circling the skies in the a pack.  Your mission is to use the harpoon given and to use it to move from drake to drake. Once on a drake, you must engage in combat with the rider.  Repeat 10 times.

My issue is that every time I try to attack a rider, they evade.  I have also noticed that riders are spawning in one particular point near the Storm Temple, without drakes and simply fall to their death. If you ride by one as it spawns, you will be hit by it.  Everything is working except for the fact that I cannot attack any rider.  

Another player friend was able to stand on the temple and take out riders, but they do not count for credit and I was unable to do so when in the quest.

I am fully geared T9 and do not think the 100% evasion rate on every attack is normal.  

Use the Hyldnir Harpoon to defeat 10 Hyldsmeet Drakeriders at the Temple of Storms.
Hyldsmeet Drakerider Defeated (10)
Provided item:
Hyldnir Harpoon

Description:
This is it. You've passed all the tests of the Hyldsmeet... all but one. You've risen among our sisters' best and fiercest.
The final test is at hand. The Drakkensryd - the true test of a Hyldnir's worth and warrior spirit. It'll be you, your riding drake, a chained harpoon and a score of your sisters vying for dominance.
Show no quarter. None will be expected.

http://www.wowhead.com/quest=12886/the-drakkensryd

**Comment by squalllh1989** [comment]
try other mob, there are some that worked, some that are bugged, but you can manage to get it done.
Also, please search before made your thread, this problem already reported many time, and how to solve the evade bug is also said. I will close this for now, feel free to comment below if you still didn't get your problem solved later

**Comment by aherdman** [comment]
Sorry, a GM directed me to report this....


But it's all good now.

**Comment by squalllh1989** [comment]
no problem, it's good that you report the bug here so we can confirm it before janitor take a look and fix those bug, but it's better that you can check if it's reported before first :)
