### ISSUE TITLE
Mutiny on the Mercy(Quest)

### ISSUE THREAD

**Issue by Samaell1990** [WoWManiaUK/Redemption#1791]
You take the quest "Mutiny on the Mercy"
http://www.wowhead.com/quest=11527/mutiny-on-the-mercy from "Captain Ellis"
http://www.wowhead.com/npc=24910/captain-ellis#screenshots:id=94020
on the board of the ship "Mercy" in NW corner in Howling Fjord and then you must go below the deck and there must be 4-5 moobs (Mutinous Sea Dog)
http://www.wowhead.com/npc=25026/mutinous-sea-dog
![](http://wow.zamimg.com/uploads/screenshots/normal/179935-mutiny-on-the-mercy.jpg)
those undead vermin must drop a quest item "Barrel of Blasting Powder"
http://www.wowhead.com/item=34387/barrel-of-blasting-powder
but the moobs are not spawned 
![wowscrnshot_102717_221222](https://user-images.githubusercontent.com/16347593/32121709-6dd96b10-bb66-11e7-9ef4-17d3afd604c6.jpg)
![wowscrnshot_102717_221235](https://user-images.githubusercontent.com/16347593/32121713-71da0d1e-bb66-11e7-81f4-0736ad2e3a1d.jpg)
and you cant get the quest items and finish the quest.
The GM Saintz checked the problem and confirmed it so i'm reporting it here.
:)

**Comment by fvicaria** [comment]
THe mobs fall through the ship sometimes. They can be found in other stationary ships also.
