### ISSUE TITLE
[Quest]Corrupted Sabers

### ISSUE THREAD

**Issue by squalllh1989** [WoWManiaUK/Redemption#1792]
[This quest](http://www.wow-mania.com/armory/?quest=4506) has 2 objective:
- Go to the corrupted moonwell (at 34.2, 52.3 in felwood), use the [Winna's Kitten Carrier](http://www.wow-mania.com/armory/?item=12565) to release the cat, the cat will corrupt by the tained water there, become bigger like a tiger.
- Take the big cat back to [Winna](http://www.wow-mania.com/armory/?npc=9996) and turn in the quest
What is wrong here:
When the big cat is taken back to Winna, the quest didn't complete, you can't turn it in. In the screenshot below you can see the big cat (corrupted kitten, mark with a cross) is taken back to winna and stand right next to her, but the quest isn't completed.
![wowscrnshot_102817_225940](https://user-images.githubusercontent.com/27235989/32136107-d0d26c30-bc33-11e7-8b12-d6f3ba8ec908.jpg)

**Comment by Mobius14** [comment]
Tested and confirmed in redemption.

**Comment by Mobius14** [comment]
Tested again.. 

To turn in the quest you have to talk to the corrupted saber when you are near Winna Hazzard. That will trigger the complete.
