### ISSUE TITLE
Deterrence spell broken (Hunter)

### ISSUE THREAD

**Issue by egzonqt** [WoWManiaUK/Redemption#1793]
I think this spell is kinda broken it doesnt work 100 % as it really should warriors and paladins can break it hopefully u can check it

**Comment by Mobius14** [comment]
[https://github.com/wow-mania/Redemption/wiki/How-to-Properly-Report-an-Issue](url)

Please be more specific in what you are reporting. 

"doesn't work 100% as it really should" 
-What exactly do you mean by this, how does it work atm and how whould it work?
"warriors and paladins can break it" 
-How? 


Kind regards

Game Master
Mobius

**Comment by squalllh1989** [comment]
He must be talking about [Deterrence](http://www.wowhead.com/spell=19263/deterrence) the defensive cooldown of hunter, but yeah, you should explain more about it, how do you know that it didn't work, what situation happen make you think this, etc, you can't just say "I think this stuff is broke" without anything to prove it and expect the dev to work day and night to try it out.

**Comment by egzonqt** [comment]
Ok let me be more specific on this As we are doing arenas per daily bases even trying it in duels literally u can even kill the hunter when he has Deterrence on him it doesnt work on 2v2 it doesnt work on duels  
We've tested it with my arena partner what im saying is A warrior with bladestorm and a  paladin with wings do dmg as there isnt any deterrence on 
Idk how more specific can i be idk a SS or a video

**Comment by Mobius14** [comment]
I have tested the deterence spell and could not reproduce the bug. In my opinion the reason damage is still done when using deterence is by bleeds (applied before) and overpower ability of the warrior. 

![wowscrnshot_103017_124649](https://user-images.githubusercontent.com/30232036/32170196-f9bb6e12-bd73-11e7-848b-abde72b5f6c3.jpg)
[All is parried here.]

![wowscrnshot_103017_125115](https://user-images.githubusercontent.com/30232036/32170226-1b61a194-bd74-11e7-88cd-c39389b7122f.jpg)
[Deep wounds applied still ticks]

![wowscrnshot_103017_125307](https://user-images.githubusercontent.com/30232036/32170247-2bf37bae-bd74-11e7-966e-3c73c26c00a9.jpg)
[Overpower cannot be dodged parried or blocked]

My conclusion is that Deterence works as it should, only dot's and special abilities of certain classes can still get through (as they should) 

If you still feel Deterence is not working as it should please reply with screenshots of logs etc. 

Kind regards
Mobius

**Comment by squalllh1989** [comment]
Tested this on paladin's wing as you say before, deterence work as it should, parry all attack from the paladin even when he has wing on, the reason you get your damage on must be the seal of vengean still doing dot
![wowscrnshot_103017_193602](https://user-images.githubusercontent.com/27235989/32171208-f2d997fa-bda9-11e7-8a1d-9e87b7ed30ef.jpg)

**Comment by squalllh1989** [comment]
So with both case of warrior and paladin tested, i can say that the spell currently has no problem, if you still have problem with this spell, feel free to comment below, and will be much better with a screenshot or a log so we know exactly the situation to try to reproduce the bug, mean while, this problem will remain closed, thank you very much.
