### ISSUE TITLE
Rogue Assasination talent dont work

### ISSUE THREAD

**Issue by Godzila1234** [WoWManiaUK/Redemption#1794]
The talent Fleet footed doesnt increase the movement speed at all ... people with simple Tusker vitality enchant can outrun the rogue, what about the paladins that have same talent that work....

**Comment by Hajzlopuc** [comment]
I actually tried that. Made a talent reset and a macro to print your current speed while moving.
It seems to work fine for me. It actually returns 16% (instead of 15) more movespeed.

http://puu.sh/y9JiI/054dad238a.jpg - with talent
http://puu.sh/y9Jjb/8450766875.jpg - without talent

**Comment by Godzila1234** [comment]
Ye with the macro you can see exactly, seems i cant just feel the diff wo it.
Thank you for your assistance and good work!
Wish you all the best!

**Comment by Hajzlopuc** [comment]
It's not that much noticable. Base movement speed is 7 yard per second. Yours with the talent is 8.05 yards per second (115%). People who run meta gem or tuskars vitality have 108% = 7.56 yard per second. 
Let's say warrior with tuskars enchant (108%) is chasing you (115%). After 10 second you are 80.5 yards further and warrior is 75.6. He is still at melee range (5yd) and can still attack you. You actually need little more than 10 seconds of running to avoid his melee range (5yd)

**Comment by Mobius14** [comment]
Thanks for sorting the issue :)
