### ISSUE TITLE
[Quest] The Drakkensryd

### ISSUE THREAD

**Issue by cathyr1** [WoWManiaUK/Redemption#1796]
This quest http://www.wow-mania.com/armory/?quest=12886 is bugged. You cannot hit the mobs on the dragons. They are still evading.  At start I did 4 somehow but now about half an hour tried many dragons and no success, just evade.
![obr](https://user-images.githubusercontent.com/30184491/32144457-77c48282-bcb9-11e7-95d8-5a0f72439f3b.png)

**Comment by fvicaria** [comment]
Works.
