### ISSUE TITLE
[Quest] Everfrost

### ISSUE THREAD

**Issue by cathyr1** [WoWManiaUK/Redemption#1797]
Hello! The problem with quest http://www.wow-mania.com/armory/?quest=13420 is persisting. I have 2 characters - one with friendly reputation, the other one has exalted. I have never found any http://www.wow-mania.com/armory/?item=44724 with neither one nor the other one. Always found only http://www.wow-mania.com/armory/?item=44729 like hundred times.

**Comment by squalllh1989** [comment]
Confirmed, [Everfrost Chip](http://www.wow-mania.com/armory/?item=44725) should have 19% of drop from it container (named Everfrost Chip too, that can be found in The Valley of Winter, Thunderfall, or Fjoin's anvil in the stormpeak) but after about 30 min loot, all i can find is only [Everfrost Powder](http://www.wow-mania.com/armory/?item=44729)
![wowscrnshot_103017_185031](https://user-images.githubusercontent.com/27235989/32169553-98cd7c28-bda3-11e7-9ffa-f5b85e0970c3.jpg)

**Comment by cathyr1** [comment]
Hello! Is this already fixed on Redemption? It still doesn´t work for me.

**Comment by fvicaria** [comment]
Yes. Objects are there.
![image](https://user-images.githubusercontent.com/9414661/32391094-c49852ce-c0c8-11e7-93c0-3339069cf755.png)

There are 18 of them hidden. Not that easy to find.

**Comment by cathyr1** [comment]
This is ok, I found some of them but the problem is that only Everfrost Powder drops, not Everfrost Chip.

**Comment by fvicaria** [comment]
You need to have the quest.

**Comment by cathyr1** [comment]
This item http://www.wow-mania.com/armory/?item=44724 that I need to drop begins the quest. I cannot obtain it elsewhere.

**Comment by fvicaria** [comment]
I got the chip on the first try just now.

![image](https://user-images.githubusercontent.com/9414661/32403873-9db0db8a-c13c-11e7-9529-a834688f804b.png)

**Comment by cathyr1** [comment]
I´m trying this every day, each one multiple times but never found it. Maybe its contained only in one special Everfrost Chip?

**Comment by fvicaria** [comment]
The quest is not repeatable if you have already done it on that character you will not get again and get only the powder. I tested on 3 characters now and it is correct.

**Comment by fvicaria** [comment]
What is your char name? I will come to you.

**Comment by cathyr1** [comment]
Mortana. I was already in Dalaran, but flying there.
