### ISSUE TITLE
[NPC] Gruff Swiftbite

### ISSUE THREAD

**Issue by GMWeeble-Mania** [WoWManiaUK/Redemption#1798]
NPC Gruff Swiftbite http://www.wow-mania.com/armory/?npc=100 (Low lvl Rare near Hogger) Has one spawned in each camp. There should be only one at a time when there is now 5-6.

**Comment by squalllh1989** [comment]
Confirmed, i found 5 Gruff Swiftbite walking arround several camp, there are too many exist at a time for a rare mob. In the pictures below i marked each one with a diffent mark
![wowscrnshot_103017_185653](https://user-images.githubusercontent.com/27235989/32169788-84846eb0-bda4-11e7-97d3-fe9bd27da8d8.jpg)
![wowscrnshot_103017_185700](https://user-images.githubusercontent.com/27235989/32169791-862c1a10-bda4-11e7-9e41-95381b2a3e5b.jpg)
![wowscrnshot_103017_185736](https://user-images.githubusercontent.com/27235989/32169794-87c6ffc0-bda4-11e7-8718-c25f275972c6.jpg)
