### ISSUE TITLE
[Quest] A Fall from Grace

### ISSUE THREAD

**Issue by Samaell1990** [WoWManiaUK/Redemption#1799]
You can complete the quest
![wowscrnshot_103017_130543](https://user-images.githubusercontent.com/16347593/32168024-a30188ae-bd73-11e7-822c-8cc5dcc102af.jpg)
but then there is a glitch that prevents you to complete it and the question mark is gray instead of yellow
![wowscrnshot_103017_130536](https://user-images.githubusercontent.com/16347593/32168066-c990516c-bd73-11e7-9a35-a1da1cbd8daa.jpg)
and when you finish the 2 tasks from the quest it doesn't tell you object complete(maybe that's the problem).

**Comment by fvicaria** [comment]
You need to stay close to NPC at the point he jumps the cliff

**Comment by squalllh1989** [comment]
Confirmed this, i stay close to him until he jump off the cliff, got the quest completed, but still can't turn it in
![wowscrnshot_103017_191412](https://user-images.githubusercontent.com/27235989/32170298-93210e2c-bda6-11e7-8dd1-5960c1b9e803.jpg)
![wowscrnshot_103017_191352](https://user-images.githubusercontent.com/27235989/32170299-94bfe42e-bda6-11e7-8286-0c7a69bc336b.jpg)
