### ISSUE TITLE
Transmogging 'One-Hand' item to a 'Main Hand' item

### ISSUE THREAD

**Issue by goldminers** [WoWManiaUK/Redemption#1801]
I opened a ticket and Weeble asked to post as an issue here.

My current equipped main hand weapon is Bonebreaker Scepter, and it is a 'One-hand' item. I am trying to transmog the item into the Aurastone Hammer. The Aurastone Hammer is a 'Main Hand' item.

I attempt to use the transmogifier npc in Dalaran, and select the Main Hand option. Unfortunately, the Aurastone Hammer is not an option on this panel.

Weeble believed that the issue is the fact that my equipped item is a 'One-hand', and the transmog item is 'Main Hand'

**Comment by Mobius14** [comment]
Dear player. 

This is correct, you can only transmog main hand>main hand etc.

**Comment by goldminers** [comment]
I don't understand.

I see people transmogging clothing items with fishing poles, or thrown items as two handers. How are they doing this?
