### ISSUE TITLE
[Quest] Get Kraken!

### ISSUE THREAD

**Issue by NightSeekerr** [WoWManiaUK/Redemption#1802]
By the advice of admin Psygoa I report a problem I have with the daily quest "Get Kraken!" The quest requires you to hurl 6 spears at the North Sea Kraken in Hrothgrar's Landing and to slay 3 Kvaldir Deepcallers. There is no problem slaying the Deepcallers but when you hurl spears at the North Sea Kraken it doesn't count them. The spears connect and deal damage, but for some reason they don't count and it remains "Hurl Spears at North Sea Kraken: 0/6". I've tried the entire procedure about 5 times.

Questgiver: http://www.wowhead.com/npc=35094/crusader-silverdawn

I use the Launcher and latest Client.

**Comment by Mobius14** [comment]
![wowscrnshot_110117_113758](https://user-images.githubusercontent.com/30232036/32271300-9eef564c-bef9-11e7-8ec9-17f68553a3ff.jpg)

As you can see I did not have the same issue. However I did notice some harpoons missed when Kraken submerged again.

**Comment by fvicaria** [comment]
I will improve the odds a bit. I also got some misses.

**Comment by NightSeekerr** [comment]
https://i.imgur.com/viWwF0U.jpg
https://i.imgur.com/3FQKD1E.jpg

I'm glad you don't have the same issue, but I'm still having it.

**Comment by fvicaria** [comment]
I will be updated when the server restarts. It has been fixed and applied. It just needs a restart.
