### ISSUE TITLE
[Quest] The Forsaken Blight and You: How Not to Die

### ISSUE THREAD

**Issue by datedz** [WoWManiaUK/Redemption#1803]
I was doing this quest on a **hunter** and I noticed that when I aggro'd the monsters to kill them, my pet wouldn't get any aggro and they would just attack me. It was strange, but I didn't think anything of it as I could kill them with the use of my traps too. However when I did this, they didn't recognize my traps at all and the monsters were in free will at melee range. This made them extremely hard to kill, so I decided since I know if I feign death the aggro goes onto my pet, I did just that. however, the monsters reset and my pet was still left there happy as can be and I was nearly dead from one monster. I didn't see a previous issue on this and this wouldn't really be an issue for any other classes except for hunters and potentially warlocks to maybe its just not reported a lot. I was able to complete the quest however, as in the water when I aggro'd the monsters they wouldn't swim up to me and would stay on the ocean floor, still not being affected from my pets constant taunts. 

I put an ingame ticket to Saintz and he suggested that I go here and submit the issue to you guys. I also asked around if this was suppose to happen as it was kinda clever humour with the monsters being ghosts not triggering anything. My ingame name is Boryz as well idk if that's important but thought id let this issue be sent in. thanks. (:

**Comment by fvicaria** [comment]
That is as is. The pet will not see the ghost.
