### ISSUE TITLE
Masophet the Black

### ISSUE THREAD

**Issue by tiger921** [WoWManiaUK/Redemption#1804]
The NPC Masophet the Black that is needed to complete Dar'Khan's Lieutenants is missing. have been looking for hoim for 2 days now. also tried /tar Masophet the Black

**Comment by fvicaria** [comment]
Please follow the procedure described below before creating a new issue:
[How to Properly Report an Issue](https://github.com/wow-mania/Redemption/wiki/How-to-Properly-Report-an-Issue)

This will help developers identify and fix the issue quicker. Incorrectly or unclear reports will simply be deleted.

**Comment by fvicaria** [comment]
Fixed.

**Comment by fvicaria** [comment]
The creature only appears during the event.
