### ISSUE TITLE
[Quest] The Balance of Light and Shadow

### ISSUE THREAD

**Issue by Pais2017** [WoWManiaUK/Redemption#1806]
This NPC in Eastern Plaguelands is not showing. I have obtained the eyes of Divinity and Shadow and have obtained the quest "The Balance of Light and Shadow".  Failed it due to connection issues. Abandoned. She's supposed to be on a 2 hour respawn timer but has been camped and is not spawning so I can accept the quest again.

**Comment by fvicaria** [comment]
https://www.wowhead.com/quest=7622/the-balance-of-light-and-shadow
https://www.wowhead.com/npc=14494/eris-havenfire#comments
https://www.wowhead.com/item=18646/the-eye-of-divinity
https://www.wowhead.com/spell=23108/blessing-of-nordrassil
