### ISSUE TITLE
[Talent] Brain Freeze

### ISSUE THREAD

**Issue by Hajzlopuc** [WoWManiaUK/Redemption#1808]
Hello,

frost mage talent Brain Freeze id=44549 does not work properly.
There should be a 15% chance to proc the instant bolt but in reality there is just 1 proc ever (and it never happen again for a session).  Session resets with logout or respec. 

I already found this issue here, closed with fixed and tweaking labels.
I was wondering if you could show me the script.

**Comment by squalllh1989** [comment]
please do search before making new one, this problem already reported, but thank you for let us know that this still didn't work property, will test this out asap.

**Comment by Hajzlopuc** [comment]
> I already found this issue here, closed with fixed and tweaking labels.
> I was wondering if you could show me the script.

**Comment by Hajzlopuc** [comment]
On armory I have noticed that there is 50 minute cooldown. Is it also like that on live server?

http://www.wow-mania.com/armory/?spell=44549
http://puu.sh/yfbRo/0814ea85aa.png

**Comment by fvicaria** [comment]
I will look into it. Thanks for the report.

**Comment by Hajzlopuc** [comment]
Thank you very much for your time. I would appreciate if you could also look at issue id [1807](https://github.com/WoWManiaUK/Redemption/issues/1807) mainly on my last comment because it got insta-closed.

**Comment by fvicaria** [comment]
WIll do.
