### ISSUE TITLE
[Quest] The fallen sister

### ISSUE THREAD

**Issue by squalllh1989** [WoWManiaUK/Redemption#1809]
How [this quest](http://www.wow-mania.com/armory/?quest=11314) supose to work is: you attack [Chill Nymph](http://www.wow-mania.com/armory/?npc=23678), lower their hp to about 30%, then there will be a message pop out that the nymph become weak, then you use the quest item, [Lurielle's Pendant](http://www.wow-mania.com/armory/?item=33606) on it.
What is wrong: the Chill Nymph become friendly to me, so i can't attack them, that make the quest undoable. Note: this quest work perfectly before, i have done this like 8-10 times at least on many diffrent char, but not atm.
![wowscrnshot_110517_142035](https://user-images.githubusercontent.com/27235989/32412779-3448bd6c-c235-11e7-85ed-ba245803bfb2.jpg)

**Comment by fvicaria** [comment]
Quest works just fine. The spell has a chance to work or not so you have to apply it multiple times.
