### ISSUE TITLE
Vesperon not working as intended (10 man)

### ISSUE THREAD

**Issue by ClavosThePally** [WoWManiaUK/Redemption#1810]
Today me and my guild started raiding the Obsidium Sanctum.
When we got to the third and final dragon before the real boss, his mechanics were not working as intended.

When he would open the portal everyone would suddenly get 9 stacks of twilight torment.
all the lower geared people would die instantly for attacking with that debuff on them.

Trying to go inside the portal instantly closes the portal as well and the single person that went inside then has no chance of fighting the mob there on his own and practically instantly dies.

We were not able to finish this boss.

**Comment by Plege** [comment]
when testing this i was unable to reproduce the issue, stacks increased at a steady rate as they should, if the problem persists please add additional information and reopen. a video or pictures would help
