### ISSUE TITLE
(Quest) The Totem of Kar'dash

### ISSUE THREAD

**Issue by ingelinge40** [WoWManiaUK/Redemption#1811]
The brutes must be killed and the npc   start to walk , The npc  don't respond in any way   
![wowscrnshot_110617_012021](https://user-images.githubusercontent.com/25806660/32420818-0c533934-c291-11e7-9e0a-dcf6f06de3cc.jpg)

**Comment by fvicaria** [comment]
Quest works fine you need to raise your reputation with the Kurenai first.
