### ISSUE TITLE
(Camp) Sholazar Basin, Rainspeaker Canopy is bugged.

### ISSUE THREAD

**Issue by eivalm** [WoWManiaUK/Redemption#1812]
Hey 

 My char name is Lolzy and Im doing every quest in sholazar and want to start farming rep with the Oracles. However im missing 6 quests and ive checked the whole map but i have no other quest. I can't remember how many i did if any at all in the camp, but i think i did some quest there. i know there is suppose to be like atleast 5-6 quest before you start getting daily quest. At the moment there are no more quest for me there, ive even tried tried to reset the my faction by killing Artruis the Heartless but even that option is bugged. I have no option to talk to him before i kill Heartless and after it shows he has a quest but when i talk to either of them (cause ive tried both) none of them let me pick it up, the option to pick it up does not show. So even tho the quest thingy over their head show, it's like they don't have it.

**Comment by squalllh1989** [comment]
Hello eivalm.
The quest chain for rep with the 2 faction in Sholazar Basin, the frenzy heart and the oracle, work fine, i have done it with my mage (my main char, the only char that i care about rep), here is what you should do to make it work: 
- Go to [Tamara Wobblesprocket](http://www.wow-mania.com/armory/?npc=28568) and get the quest [The Part-time Hunter](http://www.wow-mania.com/armory/?quest=12654), go kill [Pitch](http://www.wow-mania.com/armory/?npc=28097) and loot his remain, after you do that, you will see a frenzyheart that stand near it give out the start of their rep chain, [Playing Along](http://www.wow-mania.com/armory/?quest=12528)
- Do your chain, in these chain, you will be introduce with both faction, first you will get frenzyheart rep, then your rep will switch to the oracle, don't worry if you wanna get frenzyheart rep, those step are a must, YOU MUST DO THE WHOLE CHAIN BEFORE ACTUALLY CAN CHOSE ONE FACTION YOU LIKE AND FOCUS ON GET THEIR REP. Just keep do the chain until it leed you to the quest.
This is how the chain look like:
+) Once you kill Pitch, the frenzyheart part of the chain start:
[Playing Along](http://www.wow-mania.com/armory/?quest=12528)
[The Ape Hunter's Slave](http://www.wow-mania.com/armory/?quest=12529)
[Tormenting the Softknuckles](http://www.wow-mania.com/armory/?quest=12530)
[Wasp Hunter's Apprentice](http://www.wow-mania.com/armory/?quest=12533)
[The Sapphire Queen](http://www.wow-mania.com/armory/?quest=12534)
[Flown the Coop](http://www.wow-mania.com/armory/?quest=12532)
[The Underground Menace](http://www.wow-mania.com/armory/?quest=12531)
[Mischief in the Making](http://www.wow-mania.com/armory/?quest=12535)
[A Rough Ride](http://www.wow-mania.com/armory/?quest=12536)
[Lightning Definitely Strikes Twice](Lightning Definitely Strikes Twice)
[The Mist isn't Listening](http://www.wow-mania.com/armory/?quest=12538)
[Hoofing It](http://www.wow-mania.com/armory/?quest=12539)
[Just following orders](http://www.wow-mania.com/armory/?quest=12540)
+) After you finish the Frenzy Heart side. You get the Oracle side start with Gorloc 's new quest:
[Fortunate Misunderstandings](http://www.wow-mania.com/armory/?quest=12570)
[Make the Bad Snake go away](http://www.wow-mania.com/armory/?quest=12571)
[Gods like shiny things](http://www.wow-mania.com/armory/?quest=12572)
[Making Peace](http://www.wow-mania.com/armory/?quest=12573)
[Back so soon](http://www.wow-mania.com/armory/?quest=12574)
[The Lost Mistwhisper Treasure](http://www.wow-mania.com/armory/?quest=12575)
[Forced Hand](http://www.wow-mania.com/armory/?quest=12576)
[Home Time](http://www.wow-mania.com/armory/?quest=12577)
[Angry Gorloc](http://www.wow-mania.com/armory/?quest=12578)
[Lifeblood of the Mosswalker Shrine](http://www.wow-mania.com/armory/?quest=12579)
+) Final Quest: [Hero's Burden](http://www.wow-mania.com/armory/?quest=12581) - this is the end of the chain, where you choose your faction that you wanna get rep with first, this quest is a daily quest, you can do it 1 each day to swap your faction from frenzyheart to oracle or the other way.
After doing all of this, you are finally be able to do the daily quest to rinse your rep, have fun

**Comment by squalllh1989** [comment]
If you still have a problem after, please comment below, until then, i will keep this close since i was able to get through all of this without problem
