### ISSUE TITLE
Quest - Where Dragons Fell - 

### ISSUE THREAD

**Issue by Zeevee92** [WoWManiaUK/Redemption#1814]
Hi, 
there's a problem with NPC Matthias Lehner [http://www.wowhead.com/npc=32423/matthias-lehner](url)
he's not where he should be for Where Dragons Fell [http://www.wowhead.com/quest=13398/where-dragons-fell](url)
Thanks
![wowscrnshot_103017_150618](https://user-images.githubusercontent.com/32412813/32451313-d230c93e-c316-11e7-9afe-cabca8360353.jpg)

**Comment by fvicaria** [comment]
You can only see him if you have successfully completed:
http://www.wow-mania.com/armory/?quest=13397

**Comment by Zeevee92** [comment]
i've completed that quest, but it doesn't appear

**Comment by fvicaria** [comment]
I will re-check in a bit.

**Comment by fvicaria** [comment]
Confirmed and fixed in dev. It was missing the horde requirement.

**Comment by Zeevee92** [comment]
Thanks so much :)
