### ISSUE TITLE
Item Level?  Not an issue but...

### ISSUE THREAD

**Issue by TheGreyMouser** [WoWManiaUK/Redemption#1815]
So each item has an item level.  Some instances such as heroic require a set item level.  My question is... where is my overall average item level?  Which slots count toward that average?
Perhaps something could be put on character info panel to show the avg item level?  Or maybe there is a script?

**Comment by fvicaria** [comment]
Check your gear score. There are addons for it. Ask in world chat and people will recommend their favourite ones

**Comment by Hajzlopuc** [comment]
You can use a macro if you don't want to use any addon.
It prints average item level of your target  (or your average item level if you have no target)

`/run local t,c,u,k=0,0,UnitExists("target")and"target"or"player"for i=1,18 do k=GetInventoryItemLink(u,i)if i~=4 and k then t=t+select(4,GetItemInfo(k))c=c+1 end end c=c>0 and print(t/c)`
