### ISSUE TITLE
Magic Carpet Ride

### ISSUE THREAD

**Issue by Richig84** [WoWManiaUK/Redemption#1817]
Hello. I have seen that this quest has been up for fixes before.
But for me the problem is that Kelthusad keeps killing me before the carpet ride is over.

I have tried to abandon and reset the quest a couple of times and I see a rnd pattern.
It seem that the aggro range is some how depending on this quest.

My conclusion is based on that I first tried it at lvl 68 and got aggrod right as the magic carpet fly over kelthuzad. And when I tried It again at lvl 69 I almost got away before the second spell hit me.

Maby this could be it. I will test it again when i hit 70 and see if it goes better.

If you are going to trie it for yourself try it out with a low lvl caracter.

Thx for a awsome job with the server

/Richard

**Comment by GMWeeble** [comment]
Yes, Kel'Thusad does target me at level 69, but with no gear he has still only hit me once and I have not died. Issue can be avoided by just walking to the quest NPC.

**Comment by Richig84** [comment]
Hi. Thx for the fast reply.
walking to the NPC did not work for me
But I tried the quest again and this time it worked. He aggrod me way later than before and only hit me once.

thx again for quick service
