### ISSUE TITLE
A Dip in the Moonwell

### ISSUE THREAD

**Issue by EdwardMoore130** [WoWManiaUK/Redemption#1818]
Unable to collect water sample using the provided robot.
Quest Location Thousand Needles

[A Dip in the Moonwell.docx](https://github.com/WoWManiaUK/Redemption/files/1455224/A.Dip.in.the.Moonwell.docx)

**Comment by fvicaria** [comment]
Please follow the procedure described below before creating a new issue:
[How to Properly Report an Issue](https://github.com/wow-mania/Redemption/wiki/How-to-Properly-Report-an-Issue)

This will help developers identify and fix the issue quicker. Incorrectly or unclear reports will simply be deleted.

**Comment by EdwardMoore130** [comment]
Understood. I'm creating a WoW Mania Reporting Folder since I'm a newb. Looks like I have some studying to do. Thans for the information. 

    On Wednesday, November 8, 2017 4:13 PM, GMWeeble <notifications@github.com> wrote:
 

 Closed #1818.—

**Comment by GMWeeble** [comment]
![wowscrnshot_110817_222622](https://user-images.githubusercontent.com/21371874/32575451-59aa2946-c4d4-11e7-888c-4860db0e744d.jpg)
