### ISSUE TITLE
weapons(daggers) from website

### ISSUE THREAD

**Issue by something1989** [WoWManiaUK/Redemption#1819]
hello.
i buy weapons(daggers) from website... i cannot use abilities with them... on every ability show me require weapons/daggers... when i equip normal weapons which i buy in AH i can use every spell. please fix it... 
thanks

**Comment by fvicaria** [comment]
Please follow the procedure described below before creating a new issue:
[How to Properly Report an Issue](https://github.com/wow-mania/Redemption/wiki/How-to-Properly-Report-an-Issue)

This will help developers identify and fix the issue quicker. Incorrectly or unclear reports will simply be deleted.
