### ISSUE TITLE
maniac weapons

### ISSUE THREAD

**Issue by something1989** [WoWManiaUK/Redemption#1821]
hello.
I do use the client, I do use the launcher, I do have the latest patch and this is not a personal bug
i buy from website shop [www.wow-mania.com/armory/?item=92003](url) and [www.wow-mania.com/armory/?item=92000](url). with that daggers i cannot use any rogue ability. when i equip normal daggers which drop in wow i can use every spell. 
thanks

[http://www.imgup.cz/image/L4PS](url)
[http://www.imgup.cz/image/L4Py](url)
[http://www.imgup.cz/image/L4P4](url)

**Comment by GMWeeble** [comment]
![wowscrnshot_110817_224957](https://user-images.githubusercontent.com/21371874/32576499-6d8dc230-c4d7-11e7-9f3e-4a93a8e7ac12.jpg)
![wowscrnshot_110817_224959](https://user-images.githubusercontent.com/21371874/32576505-70c9c494-c4d7-11e7-9eb5-c1f8822b249b.jpg)
They are working fine for me.
