### ISSUE TITLE
Crystalized Life in Borean Tundra - herbalism

### ISSUE THREAD

**Issue by TheGreyMouser** [WoWManiaUK/Redemption#1823]
wow-mania armory states 20% drop rate from gold clover and tiger lily.  However after farming these herbs (aprox 15 or so nodes) not even 1 crystallized life has dropped.  Can you confirm drop rate?  Thanks in advance

**Comment by fvicaria** [comment]
Can you send the link to the items please.

**Comment by TheGreyMouser** [comment]
http://www.wow-mania.com/armory?item=37704

**Comment by bogey2230** [comment]
![crystal life 1](https://user-images.githubusercontent.com/25446816/32635238-6c648000-c57d-11e7-97e3-cca7c21752bf.png)
![crystal life 2](https://user-images.githubusercontent.com/25446816/32635240-6e5a6c76-c57d-11e7-8761-19d01fd70056.png)
Pic 1
I hovered my mouse over the right side on the columns, which brought up a smaller box which states; Stack of 1 8% / Stack of 2 8% / Stack 3 8%.
Pic 2
I hovered my mouse over the right side of the columns, which brought up a smaller box which showed 7% for Stack 1-3.
Using my druid, which has  herbalism at 465, I farmed herbs in Borean Tundra starting at 17:75:49 - I farmed 50 nodes - ending at 18:33:17

Here are the results;
Goldclover - 21 nodes - 5 drops of Crystalized Life - 1 Frost Lotus
Tiger Lily    - 18 nodes  - 4 drops of Crystalized Life - 1 Frost Lotus
FireThorn   - 11 nodes  - 2 drops of Crystalized Life - 1 Frost Lotus

50 nodes - 11 drops of Crystalized Life - 22%

**Comment by fvicaria** [comment]
Thanks a lot for that.
