### ISSUE TITLE
Transmog

### ISSUE THREAD

**Issue by Atonment** [WoWManiaUK/Redemption#1824]
Hello
i bought "Scepter Of Sergeras" for xmog and i transmoged my staff only to find that the scepter of sergeras is on the other way around on my back so i talked to a GM about getting my xmog tokens back to get another staff so i bought "Warden's Crown" which also happened to be bugged and was the other way around, and i talked to a GM again to my xmog tokens back and i went and untransmoged my staff, relogged and the old transmog still showed up, i cleared cashe more than once , tried .save and all of the stuff i've read here and nothing seems to help, so bascily i am reporting two issues here the staffs being the other way and the transmog not being untransmoged
Thank You.
![wowscrnshot_111017_195806](https://user-images.githubusercontent.com/33552092/32671826-884f9474-c651-11e7-8b67-a65edabbd7e6.jpg)

**Comment by fvicaria** [comment]
Send an email to support and we will sort it.
