### ISSUE TITLE
[Spell] Eruption - Heigan Dance (Naxxramas)

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#1825]
Hello,

I'd like to report Heigan the Unclean's (http://www.wowhead.com/npc=15936) Eruptions (http://www.wowhead.com/spell=29371) happening with irregular time intervals. Note, according to wowhead, this spell is not directly cast by Heigan, but the "plague fissures" on the floor.

How it's intended to work: time between eruptions in phase1 is meant to be long (about 10seconds), in phase2 short, about 3-4 seconds. 
How it works at the moment: could not find a regular pattern, the first few eruptions happen with the regular 10sec interval, then it changes to 5seconds between the next ones, then 3seconds, then 2, then 4, sometimes it's 10,10,10, then suddenly 2,2,2, it cannot be followed. This is all in phase1. Phase2 is regular 5seconds, which is slower than intended,  but at least not random.

On another note, sometimes the whole room erupts, instead of 3/4, with the safe zone erupting half second early, or half second late, compared to the other three.
I did not experience lag these days, it's the spell being random.

**Comment by Plege** [comment]
The Issue has been confirmed and will wait for a fixx.
The explosions are not in regular intervals in P1 making the  Heigan dance near impossible.
Thanks for the report
