### ISSUE TITLE
[Spell] Hateful Strike - Patchwerk (Naxxramas)

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#1826]
Hello,

I'd like to report Patchwerk's (http://www.wowhead.com/npc=16028) Hateful Strike (http://www.wowhead.com/spell=41926), for hmmm, how to say, I guess being too friendly.

How it's supposed to work: Strikes the person who is 2nd on aggro on 10man, strikes the person with the higher health among the 2nd and 3rd threat on 25man.

How it works at the moment: same as the above, except it **ignores all targets that are not tank specced, making it essentially "missing" from the fight when not using an offtank**.

As long as there are players in "tank mode" (bear form, righteous fury active, frost presence/defensive stance), that are not main-tanking (second or third on aggro), they'll be hit by hateful strikes as intended, if there are no such targets, or they already died, Patchwerk stops casting Hateful strikes. If there's only one offtank on 25man, he will receive every Hateful strike, regardless of health values because non-tanks are never eligible to be hit by it.

**Comment by Dranah** [comment]
This is bugged again(or still) on 10man mode on redemption
Reopen for further testing

**Comment by fvicaria** [comment]
Why re-open if it has been confirmed?

**Comment by Dranah** [comment]
because it's bugged ._.
