### ISSUE TITLE
[Spell] Hunter's Deterrence ability

### ISSUE THREAD

**Issue by KyptAMaN** [WoWManiaUK/Redemption#1827]
Am pretty sure this spell is bugged, am getting hit with non hitable spells, and the spell says is 100% deflective.. i know theres some spells that can break through it like for ex: Overpower, Chaos Bolt, Cheapshot, Shiv, Runestrike and Engineering pyro-rocket. 
But these are the only spells who can hit through Deterrence.. other than that it should either parry or deflect 100% !!

Please take a look into that.. 
Ty.

**Comment by squalllh1989** [comment]
Please attach an screenshot with log for this, we already tested this out and find nothing bugged here, 100% defective for attack, spell, not for the stack effect from spell (paladin seal of corruption, etc)

**Comment by L0dos** [comment]
![1](https://user-images.githubusercontent.com/33573664/32689989-d3969366-c6ff-11e7-9624-06d65d482975.jpg)
![2](https://user-images.githubusercontent.com/33573664/32689991-d61ba270-c6ff-11e7-95a1-a0efc12b48ff.jpg)
![3 2](https://user-images.githubusercontent.com/33573664/32689992-d912cdb4-c6ff-11e7-8159-c302f5127bf1.jpg)
![4 2](https://user-images.githubusercontent.com/33573664/32689994-db82568c-c6ff-11e7-8f7d-696ed34915f7.jpg)
![5](https://user-images.githubusercontent.com/33573664/32689995-dcde57ba-c6ff-11e7-8f90-445efa3b7117.jpg)

**Comment by L0dos** [comment]
![combat log start](https://user-images.githubusercontent.com/33573664/32690003-01d13754-c700-11e7-8a01-f649a732f2db.jpg)
![combat log follow up](https://user-images.githubusercontent.com/33573664/32690007-043a0412-c700-11e7-891c-899379b200c1.jpg)

**Comment by L0dos** [comment]
Det is bugged for a more than a year now and i proved it to Metaxa with Reven last year but who gives a fuck to Lodos anyways.Also pet's agressive stance is bugged.Wasn't going to post or anything and just talk it out with Mobius but i wanted to help the guy who created this and Shamel posted me this link from FB.

**Comment by Hajzlopuc** [comment]
Maybe it just deflects spells and attacks from the front and does not deflect those from behind. Have you tried to test it from different directions?
How parry stat in wow works is that you can only parry frontal attacks. 
But deterrence should be an exeption since patch 3.2 and should parry spells and attacks from behind as well as in front.

Maybe something to start with? (Just my wild guess)

**Comment by Midnaa** [comment]
Spirit burst is also going through deterrence (70503, ability from Vile Spirits in the lich king encounter)

**Comment by Mobius14** [comment]
reopening the issue so test-team can look into this please
