### ISSUE TITLE
Valithria Dreamwalker

### ISSUE THREAD

**Issue by Bartok14** [WoWManiaUK/Redemption#1828]
Hello, my guild is having an issue with Valithria Dreamwalker bugging out now on two of our raids in the past month. The issue as it happened tonight was that the encounter was started without everyone being in the room. As a result we all died. Mobs went through the door and killed the rest of our raid. Upon re-entering the raid we were still in combat and it seems the adds kept spawning inside without the boss fight resetting. We think either one of the mobs is bugged and goes into a wall trying to still kill the group and as a result continuously spawn more and more adds. we also think that there may be a chance that the adds when pulled through the door might be activating sindrigosa's gauntlet as there seem to be spiders that make there way to the ground floor attacking all the npcs at lights hope. Can you please look into fixing this issue as this is the second time we have lost a raid group to it bugging out. 
Thanks,
Bartok.

**Comment by Mobius14** [comment]
cannot reproduce the circumstances about which you talk. I would recomend contacting a GM in game when you encounter a wipe on a ninja pull (which would/could result in the issue you posted)
