### ISSUE TITLE
[Warlock - Spell] Drain Soul

### ISSUE THREAD

**Issue by Midnaa** [WoWManiaUK/Redemption#1829]
The spell Drain Soul (http://www.wow-mania.com/armory/?spell=47855) reads out as: "If the target is at or below 25% health, Drain soul causes four times the normal damage." This is working, however the problem is **if you **start channeling **on 26% Max HP**** and the target falls below 25% HP it's not ticking for four times the normal damage**, you have to recast Drain Soul in order for the effect to work.

How it currently works:

- You cast Drain soul at 26% HP and target falls below 25% HP ---> Drain Soul is **NOT** doing x4 the normal damage

How it should work:

- You cast Drain soul at 26% and target falls below 25% HP ---> Drain Soul ticks for x4 the normal damage after the target is **AT OR BELOW 25% HP**

The source for this is the tooltip for the spell because it states no other conditions and mentions no recasting or anything similar.

**Comment by Hajzlopuc** [comment]
Hello, I am pretty sure it works as intended. Spell damage is calculated at the beginning of the cast exactly how it should be. It means you need to start channeling when target is already below 25%, but if there is a situation that target is healed to full, you are still doing full (4x) damage. 
I had been playing a ton of affli lock on offi and this is something I remember exactly.

**Comment by BatuMania** [comment]
Yeah this is definitely a false report, it's working as intended.
Your spell is always measured as when it's first casted. If you Drain on 26%, your whole drain will be as if you're draining from 26% on.

**Comment by Midnaa** [comment]
You are correct, I will close this report.
