### ISSUE TITLE
Quest: Fortunate Misunderstandings.

### ISSUE THREAD

**Issue by Naigio** [WoWManiaUK/Redemption#183]
So after helping the Injured Rainspeaker Oracle and readying up to go home, I attempt furiously and vigorously to press the option to start the escort part of the quest.
I attempted to do this on all the different Injured Rainspeaker Oracles around, I tried relogging & abandoning to no avail.
So I'm left without being able to complete the objective effectively.

http://www.wow-mania.com/armory/?quest=12570

**Comment by Calebrimbor** [comment]
Closing the issue, this quest will be added to [Project](https://github.com/wow-mania/Redemption/projects/2).

**Comment by Kalasbyxan** [comment]
Reported same issue from player.

**Comment by fvicaria** [comment]
Works.
