### ISSUE TITLE
[Mount] Invincible's Reins.

### ISSUE THREAD

**Issue by BatuMania** [WoWManiaUK/Redemption#1830]
It was marked as fixed, yet nothing has been done as usual.

Invincible's Reins can't be used anywhere except Northrend to fly with.
It should be considered as a ground mount AND flying mount.

This is the same issue as the Headless Horseman mount which got fixed.

Make Invincible be usable in Dalaran.

**Comment by cathyr1** [comment]
Invincible was usable in the old world but now it is no longer. Please at least change this back.

**Comment by BatuMania** [comment]
Why 'atleast', let em change it to the way it should be :)

**Comment by Mobius14** [comment]
In that case.. at least report the issue properly on github ;) 

[https://github.com/WoWManiaUK/Redemption/wiki/How-to-Properly-Report-an-Issue](url)
