### ISSUE TITLE
Transfer MP points between characters 11/11

### ISSUE THREAD

**Issue by bogey2230** [WoWManiaUK/Redemption#1831]
11:30AM on 11/11, I tried to transfer MP from Zakath to Beldurnik, about 96 of them. Using the website the MP's were shown to be moved from one character to another. Logged in, no mail on Beldurnik and MP's were missing from Zakath. Tried using a character ' Macros ' to move MP's to Beldurnik about 100 of them, website shown they had been transferred, logged in to Beldurnik - no mail and MP's were missing from Macros
Tried moving 2 MP's from Beldurnik to Macros, website again showed they had been moved, logged in and no mail on Macros.
Will continue to logged into characters to see if any mail has shown

**Comment by fvicaria** [comment]
NOt an issue for here. Send email to support.
