### ISSUE TITLE
[NPC] Vicious Golden King

### ISSUE THREAD

**Issue by WhitephoenixTheBunny** [WoWManiaUK/Redemption#1832]
Hello

My friend Astrea (name in game), cant create account here, and he need report a bug, so he asked me to report for him. He bought a pvp mount, but the size of the mount its smaller than usual and the sound its an horse sound and not a lion sound. 
After he open a ticket in-game, that was told him to report here.

Thank you

![astrea mount](https://user-images.githubusercontent.com/31921098/32704780-cee4dd06-c802-11e7-8dd0-4ddb8b04d594.jpg)

**Comment by fvicaria** [comment]
This is fixed in dev but it requires client update so it will probably take a couple of weeks until release.

**Comment by WhitephoenixTheBunny** [comment]
Thank you :)
