### ISSUE TITLE
[Achievement] Volunteer Work 

### ISSUE THREAD

**Issue by 907akcrazycraig** [WoWManiaUK/Redemption#1833]
http://www.wowhead.com/achievement=2056/volunteer-work  is bugged the Twlight Volunteer's are suppose to be sacrficed by http://www.wow-mania.com/armory/?npc=29310 but the encounter comes to a standstill during that phase of the encounter

**Comment by Plege** [comment]
Confirmed. The boss fails to sacrifice the voluinteer and enrage, she gets stuck in the air and the encounter cannot be completed.
