### ISSUE TITLE
[Quest] Cold Hearted

### ISSUE THREAD

**Issue by Nooblerone** [WoWManiaUK/Redemption#1834]
You are supposed to free a Dragon and get 3 prisoners free aswell. The dragon isnt able to change hight. therefore you're not able to reach any other then 3 specific prisoners. the dragon moves so slow its acutally rediculous. after he senses his freedom he should move fast and fly home within seconds. It took him 5 minutes to fly (!!) and you have to do that 3 times...

**Comment by fvicaria** [comment]
Works. Please search before posting new issues it will save your time and the developer's

**Comment by Nooblerone** [comment]
sure, I might just spend 30 mins on that quest and whispering with a GM about it on accident. Makes sense. Your attitude is toxic...

**Comment by Hajzlopuc** [comment]
Try to change dragon if the one you are riding is slow. Some of them were slow yeah, but majority of them was fast (at least for me) and I could find them and do the quest pretty fast.
