### ISSUE TITLE
[Talent] Bloodsurge - Warrior (Fury) 

### ISSUE THREAD

**Issue by rexxo** [WoWManiaUK/Redemption#1837]
Hi Everyone, in the last couple of days i've been testing the warrior talent Bloodsurge (http://www.wow-mania.com/armory/?spell=46915), it is supposed to have a 20% chance of proc while you're using Heroic Strike, Whirlwind or Bloodthirst. I had the feeling it wasn't like described so i started testing it on a dummy a couple of days ago. My tests have been made with my warrior (4t10 pieces on), i didn't check if eventually  removing the tier bonus would change anything. After 630 total spells, the talent has been activated only 63 times, which is exactly 10% and not 20%, also the talent look a bit dodgy, most of the times it shows the talent will stand just 5 seconds, but some other times it shows it will last 10 (guess this is something changed by the t10 bonus). Actually we already know the t10 is bugged (since a while now) and if i am correct, as a warrior with 4t10 pieces, we're actually doing 25% of the slam that we should do... i'm free and would love to help for more testing!

Talent 5 sec
![5 sec talent](https://user-images.githubusercontent.com/33596646/32769912-95fe252e-c915-11e7-9d7d-4ef5eaaba6ec.jpg)

Talent 10 sec
![10 sec talent](https://user-images.githubusercontent.com/33596646/32769914-9624e420-c915-11e7-9d6e-06d6c53837f4.jpg)

Total amount of Slams over 630 spells
![slam amount](https://user-images.githubusercontent.com/33596646/32769913-9610cca6-c915-11e7-9775-cc170fb33d95.jpg)

**Comment by fvicaria** [comment]
Is this not a repeat of #1374?

**Comment by rexxo** [comment]
no, i am not talking about the t10 bonus, i am talking about the talent itself http://www.wow-mania.com/armory/?spell=46915, it supposed to have a 20% chance of activation, but it looks to be just 10%
