### ISSUE TITLE
[Item] The RP-GG

### ISSUE THREAD

**Issue by Hajzlopuc** [WoWManiaUK/Redemption#1838]
Hello,

http://www.wow-mania.com/armory/?item=42986
these rockets you can pick up in Wintergrasp around workshops do damage to players. 
They should not damage players at all, just vehicles. There are many people abusing this lately, just camping and firing rockets forward, oneshotting people who just teleported in.

And they shouldn't be able to be picked up if the workshop isn't yours and if the battle is not happening right now.

**Comment by GMWeeble** [comment]
Yes, this item does damage to players.

**Comment by squalllh1989** [comment]
I already reported this problem before about the fact that it shouldn't be picked up before or after wintergasp end also.

**Comment by fvicaria** [comment]
Show me where it says it is not supposed to damage players.

**Comment by Hajzlopuc** [comment]
I didn't find anything what directly says : These don't do damage to players.
But I've tried and found these so far:

https://www.gamefaqs.com/boards/534914-world-of-warcraft/49406157
http://puu.sh/ylZkv/dd03a9a31e.png

http://www.wowhead.com/item=42986/the-rp-gg#comments
http://puu.sh/ylZIk/81b554a884.png

http://wowwiki.wikia.com/wiki/Wintergrasp
http://puu.sh/ylZGd/5e64d88923.jpg

**Comment by fvicaria** [comment]
I will try to see what I can do. I have something already in the PTR

**Comment by Hajzlopuc** [comment]
I have got reply from Blizzard Support

http://puu.sh/ymxQa/e9e3d3d77d.png
http://puu.sh/ymxU7/25d6f258d8.png

**Comment by fvicaria** [comment]
Thanks for that. It was very useful and fast.
I have now uploaded the changes to Redemption.
Check it please.

**Comment by Hajzlopuc** [comment]
From what I have seen last day, it is fixed.
