### ISSUE TITLE
[Quest] Time for Answers

### ISSUE THREAD

**Issue by Ravenshowl** [WoWManiaUK/Redemption#1839]
I've completed the quest 'Where Dragons Fell' and the next quest in line is 'Time For Answers'. I flew to hand in the quest but he is not there. I've searched far and wide, and it is where he should be. At cord: 49 - 73. After talking with a GM and convincing him, that I could not see him, he asked me to open a github. He could see him, but I could NOT. He helped me through the quest to the next one through his magic abilities (GM power).

I open this 'issue' if any one should happen to have the same problem. 

The problem may be because the area is also used for some tournament quests. As I stood and waited for Arthas-little-boy-self the area suddently shifted to tournament quest area, with me NOT having the quest for it. 

Then I picked up the quest I looked first after the boy, then he wasn't there, I took the tournament quest, solved it, but he were still not there, not mean while the quest was active or after. But after solving the quest I re-returned and mean while wating, as said, the area shifted into quest area.

**Comment by GMWeeble** [comment]
Player's (GM off) Does put you in the wrong phase. I am not sure if there is a lot of quests that you need to do to be put in the right one, but this issue also happens at quest http://www.wowhead.com/quest=13361/the-hunter-and-the-prince
But there not even GM's are able to see the stone.
