### ISSUE TITLE
[Macro] Wrong Script

### ISSUE THREAD

**Issue by Callabero** [WoWManiaUK/Redemption#1840]
Hello there, this will be abit complicated so please read carefully.
Ive a macro
#showtooltip Charge
/cast Charge
/cast Intercept

This macro works only with a talent called http://www.wow-mania.com/armory/?spell=57499.
The problem is that if i use this macro, i use both spells at single press. U shouldnt be able to use intercept, while charge is ready, or while u are charging someone (still in effect).  Simply now it works like this https://imgur.com/a/wqYxq
As u can see both spells were used. Ive played wotlk retail and 2 other servers that u trust, where it didnt work like this. As i said u shouldnt be able use intercept while charge is ready just like here https://imgur.com/a/oTzv3. Its a rly similiar script to shield bash macro, where u on first press equip weapons, and on 2nd press u use a spell. 

If you dont understand it correctly, please type me here or ingame on my character Callabero, ill try to explain.

Thank you in advance for fixing this issue

Respect
Callabero

**Comment by fvicaria** [comment]
This is "as is". A lot of macros will either not work on 3.3.5a or it is possible to find a workaround that will work. I will not spend time on this as it is a bottomless pit. Sorry.

**Comment by Hajzlopuc** [comment]
Try something like this

`#showtooltip
/castsequence reset=15 Charge, Intercept
`

it cast Charge at first press and Intercept on second press. After 15s since first press, it resets and allows you to Charge again. Let me know if it works the way you wanted. IGN Kokotka

**Comment by Callabero** [comment]
Hello, i already found macro with same principe, Thank you anyways.
