### ISSUE TITLE
[Quest] The Savior of Kalimdor #8802

### ISSUE THREAD

**Issue by Unstoppablee** [WoWManiaUK/Redemption#1841]
Today with friends I was in **"Temple of Ahn'Qiraj"** and we cleared whole instance. Last boss dropped an item **"Eye of C'Thun"** who actually starts a quest named **"C'Thun's Legacy"**. This quest have to be turned to an NPC inside of ToA and after that you get another quest (#8802) that you have to deliver to **"Anachronos"** in Tanaris (Cavern of Time). When I got there I could not talk to that NPC, I could just kill it. GM Saintz completed quest for me, and said that is probably phase problem, also he tested quest for himself. 

This is kinda rare quest so probably will not be priority, but would be appreciated to be fixed, and easier for GM's so they don't have to bother with tickets on this topic. 

**Instance:** http://www.wowhead.com/temple-of-ahnqiraj
**Quest Item:** http://www.wowhead.com/item=21221/eye-of-cthun
**Quest:** http://www.wowhead.com/quest=8802/the-savior-of-kalimdor
**NPC:** http://www.wowhead.com/npc=15192/anachronos

**Comment by GmSaintz** [comment]
I can confirm this on Redemption, I tried to do the quest as well and you cannot talk to "Anachronos"- http://www.wowhead.com/npc=15192/anachronos - to turn the quest in. -http://www.wowhead.com/quest=8802/the-savior-of-kalimdor

**Comment by fvicaria** [comment]
NPC and Caverns of Time chain have many quests and dependencies. You will not be able to talk to Anachronos until you got the pre-quests done.

**Comment by fvicaria** [comment]
I re-opened this. There may be some other issue here but what I said above still stand.

**Comment by fvicaria** [comment]
![image](https://user-images.githubusercontent.com/9414661/32826538-abb3f44a-c9e0-11e7-81f2-58115a49bda3.png)
Required.
