### ISSUE TITLE
Lich King trouble.

### ISSUE THREAD

**Issue by lothraine** [WoWManiaUK/Redemption#1842]
Right after i finished "When Dragons Fell" [http://wowwiki.wikia.com/wiki/Quest:Where_Dragons_Fell] from Matthias Lehner in Sindragosa's Fall, the Lich King appeared. He was targetable, i could attack him and he did not reset
![wowscrnshot_111517_050053](https://user-images.githubusercontent.com/18270256/32816643-73c76c9c-c9c2-11e7-97d4-c33b03d2b790.jpg)

With enough given time i could probably have killed him. I contacted the GM [Saintz], he came checked the issue and told me to post it here.
Also, during the time i attacked the Lich King, Sindragosa flew over a few times. She was also targetable/attackable.

**Comment by GmSaintz** [comment]
I had time to test this after our ticket. Unfortunately I was not able to reproduce the issue. I think what may have happened is that you were stuck in the end phase of the quest and/or a cache issue. If you had left the area and came back they would have been gone. My apologies!
