### ISSUE TITLE
HoR HC

### ISSUE THREAD

**Issue by Pais2017** [WoWManiaUK/Redemption#1845]
We completed the dungeon. The attached screenshot shows that we cleared the last ice wall before the timer ran out. The ship even spawned, however, there were no steps leading up to it. We submitted a ticket and were summoned up to the deck of the ship via GM Summons, but were unable to loot the chest. 
![horhc1](https://user-images.githubusercontent.com/33046311/32950725-0474d3be-cb6d-11e7-8839-611a8d7554a8.jpg)

**Comment by fvicaria** [comment]
This has been reported before but it is very hard to reproduce, some timing or positioning of the player may cause it.
