### ISSUE TITLE
light of the dawn quest

### ISSUE THREAD

**Issue by boohe91** [WoWManiaUK/Redemption#1847]
took the quest hit im ready the quest bugged out the fighters and quest guy reset 
i tried logging and abandoning the quest a few times in the end a gm named Psygoa helped me finish it as i coudent get it to start at all

Psygoa asked me to report this on here

**Comment by ingelinge40** [comment]
I have rest Darion a few time  he opens the tekst but does not respond at all.
I have taken the quest myself and  it  did  not  start up in anyway.
I added een ss  , this is what happens nothing more
![wowscrnshot_111917_053825](https://user-images.githubusercontent.com/25806660/32987596-8c7a6d08-ccf0-11e7-8380-6be6bf0cc674.jpg)

**Comment by boohe91** [comment]
ty for adding that

**Comment by fvicaria** [comment]
Yes, it can get stuck sometimes.  The first option in the menu is wrong. You should try to clieck on "I am ready!" I am fixing this now.
Ask a GM to complete it for you.
