### ISSUE TITLE
[Talent] Pursuit of Justice

### ISSUE THREAD

**Issue by cathyr1** [WoWManiaUK/Redemption#1848]
Hello! I made a ticket No. #1715 in the past describing the problem of non-working talent http://www.wow-mania.com/armory/?spell=26022 in some situations. Despite it is closed, the problem still persists - for paladin surely, you can also try rogue with talent Fleet Footed http://www.wow-mania.com/armory/?spell=31209. I don´t have a rogue so cannot try this one but maybe this problem will be there also.

This talent isn´t working after you leave dragon, demolisher, cannon etc. but also when you land on skyship (Skybreaker in Icecrown "works") and then you return to surface and dismount. Your speed will be also slowed to 100 % instead of 115 % as it should be. Only help is relog.

**Comment by fvicaria** [comment]
As is.  It will not work on mounts you do not own.
Also please do not create new issues if a closed one exists. If necessary and proven not fixed or regressed I will reopen. This pollutes the repository and makes collecting info more difficult.

**Comment by cathyr1** [comment]
Sorry, don´t understand what you mentioned. I´m always testing only my own mounted and especially ground speed and it is broken. About the new ticket, I posted my answer to that previous one about 9 days ago but I got no answer there and thus opened this new one.

**Comment by fvicaria** [comment]
It may be a side effect of mounting other vehicles. I will re-check. The talent itself works it's the aura that is cleared.

**Comment by fvicaria** [comment]
@cathyr1 Would you like to join the test team? We need more people and you seem to contribute here a lot... may as well get recognized and rewarded :)

**Comment by cathyr1** [comment]
To issue: Please check this and fix. It is annoying when e.a. doing mounted dailies for Argent Tournament and then must relog before even que up random HC or in Wintergrasp / Isle of Conquest after leaving vehicle or cannon do not benefit from this important talent. And there are many more situations in that this is really a problem.

To testing: What does it involve?

**Comment by fvicaria** [comment]
I found the issue and it will be fixed in the next update. It was a side-effect to stop some speed hacks.

@cathyr1 Add us to Skype: wow-mania.com and we can talk more. Nothing much more than what you are doing here only a little more focused.
