### ISSUE TITLE
[Quest] ID: 11984 Filling the Cages

### ISSUE THREAD

**Issue by Kjlucy** [WoWManiaUK/Redemption#1849]
Hi,

I came across a bug while trying to complete this quest in Grizzly Hills.

Wowhead:  http://www.wowhead.com/quest=11984/filling-the-cages
NPC:  http://www.wowhead.com/npc=26422/budd

You should be able to direct the npc to sap mobs, via pet bar buttons.  However its not working.  The other pet buttons are, attack follow etc.  I have tried with and without addons installed.

I have also tested this quest on retail to make sure I was doing it right, and I was.

Hope you can help and let me know if you need any further info

**Comment by fvicaria** [comment]
Just tried and it works.

**Comment by fvicaria** [comment]
![image](https://user-images.githubusercontent.com/9414661/33008647-cb700e92-cdcb-11e7-86e9-c297064f817c.png)
