### ISSUE TITLE
Oh Noes, the Tadpoles!

### ISSUE THREAD

**Issue by Prettiful** [WoWManiaUK/Redemption#1850]
Oh Noes, the Tadpoles! is a quest in Borean Tundra, Northrend that has been buggy today. Each time I open a catch, supposedly full of tadpoles, nothing happens. The tadpoles do not run away, they don't disappear, they don't count towards my quest and they don't change appearance. Sometimes they also appear to not even be in cages, just in a clump in the middle of nowhere. I was wondering if there was a way to fix this.

Thanks,

Deathcometou (DK on Redemption)

**Comment by fvicaria** [comment]
![image](https://user-images.githubusercontent.com/9414661/33008447-fce26e94-cdca-11e7-8a3a-2cb1a9b1e8d4.png)
