### ISSUE TITLE
[Quest] Ursoc, The Bear God

### ISSUE THREAD

**Issue by roleplay1** [WoWManiaUK/Redemption#1853]
When talking to the npc Tur Ragepaw  he comes with you as healer to help you to defeat Ursoc.
When you are in combat  another Ursoc spawns sometimes 3 or  4 , When that happens the npc  stop to help you and run away. Killing the spawns of Ursoc  is not helping cause the npc Tur Ragepaw is stopped working

**Comment by fvicaria** [comment]
That is because people spawn it and leave it. A GM must go and kill them all.

**Comment by fvicaria** [comment]
http://www.wowhead.com/quest=12249/ursoc-the-bear-god
