### ISSUE TITLE
Betrayal

### ISSUE THREAD

**Issue by Prettiful** [WoWManiaUK/Redemption#1854]
The quest in Zul'Drak is bugged. It does not allow the player to pick up Drakuru's head after the player kills him. I managed to kill him after quite a while, using the trolls, and afterwards immediately died from nothing that was even reported in the combat report chat display. Then, I was ported across the map and the game wanted me to re-kill Drakuru. I was wondering if there was a way to fix this?

Thanks,

Deathcometou (DK - Redemption)

**Comment by fvicaria** [comment]
You are required to do at the very least 50% of the damage or you will not get it.
