### ISSUE TITLE
Noggenfogger Elixir

### ISSUE THREAD

**Issue by 907akcrazycraig** [WoWManiaUK/Redemption#1856]
This quest doesn't seem to be accessible from Marin Noggenfogger http://www.wow-mania.com/armory/?npc=7564 , http://www.wowhead.com/quest=2605/the-thirsty-goblin, your suppose to do the quest line for http://www.wow-mania.com/armory/?item=8529

**Comment by Hajzlopuc** [comment]
There is a prereq.
It starts with 

http://www.wow-mania.com/armory/?quest=2605

**Comment by fvicaria** [comment]
![image](https://user-images.githubusercontent.com/9414661/33117065-0624719c-cf5f-11e7-9ccb-00fce362d70d.png)
