### ISSUE TITLE
Walking mobs

### ISSUE THREAD

**Issue by Varnosh** [WoWManiaUK/Redemption#1858]
Hello,
I'd like to report that patrolling mobs keep patrolling even when they're engaged into a fight.
They're attacking alright, even casting when they're casters, but they keep walking along their patrol path casually as if nothing too sweaty was happening.

I play tank, so I like to pull mobs to a safe place (sometimes several at a time) so I can finish them off before pulling more. But these patrol guys are a pain in the class (warrior).

This is a recurring problem that I faced during my leveling. It happened with Razorbacks in the Barrens, Venture Co. Wirkers in Stonetalon, pirates in Tanaris, Syndicate rogues in Southshore...

I believe this is a glitch of some sort, since mobs are supposed, once pulled, to chase and attack their attacker.

**Comment by fvicaria** [comment]
PLease link mobs from Armory or wowhead.com
