### ISSUE TITLE
Gargoyle Ambusher

### ISSUE THREAD

**Issue by Icytalon** [WoWManiaUK/Redemption#1859]
Hello there :)
In IceCrown there is packs of Gargoyle Ambusher, they are aggressive locate players or me at least from a long distance very fast casting spell and it hits for 5~8k each who would survive that? I am dying from them like 10 times per day while doing my dailies.
Please look into that I have a screen shot with a combat log it may help. and thank you for reading my issue, Have a good day.
<img src='https://i.imgur.com/QdIFcgF.jpg' />

**Comment by fvicaria** [comment]
As is. The gargoyles are part of a quest. Just keep away from them.
