### ISSUE TITLE
Horde Ship

### ISSUE THREAD

**Issue by Icytalon** [WoWManiaUK/Redemption#1860]
Hello there 
there is a problem with Horde Ship in Icecrown it's all about sudden instant death and counts as fall damage while walking on it the instant death happen the most neat Brother Keltan NPC I even take a fall damage if I jump on it, could you please look into it I'll be thankful. have a good day.
<img src='https://i.imgur.com/M4Qe73W.jpg' />

**Comment by GMWeeble** [comment]
I was not able to take damage from jumping.

**Comment by GMWeeble** [comment]
https://gyazo.com/21574ec1b314d0458c05bc7134e8e653

**Comment by fvicaria** [comment]
This is a specific tile on the map that may have a problem. Most of the journey is fine.
SOme particular locations you just can't jump.
I will not worry about this one unless it starts happening in other places.
Thanks for reporting.
