### ISSUE TITLE
[NPC] Items are missing

### ISSUE THREAD

**Issue by Callabero** [WoWManiaUK/Redemption#1861]
Hello there,

NPC called http://www.wowhead.com/npc=19662/aaron-hollman doesnt sell blacksmithing recipes.
Proof: https://imgur.com/a/ZnndO

**Comment by Icytalon** [comment]
these NPCs are selling limited supply recipes , as long as a player bought it from him the cooldown starts to appear again with the npc so I advice you to come back check him after an hour or more because I bet someone bought the scroll you're looking for.

**Comment by fvicaria** [comment]
Which item do you think it is missing?

**Comment by Callabero** [comment]
Icytalon, if someone bought those items, it would show them anyways and be darker picture. They didnt even appear.

Fcicaria, I talk about those 4 Blacksmithing recipes that NPC should sell.

**Comment by fvicaria** [comment]
They are all there.

**Comment by GMWeeble** [comment]
Items sold to NON GM characters https://gyazo.com/1e6f5e6b3af8e1b4880aed712318ba34

Items sold to GM Characters https://gyazo.com/7fb64bc78e35f96172a54bd70ca6c342   https://gyazo.com/37020e54a63f74f734eb338ed4e23867

**Comment by GMWeeble** [comment]
I will reopen and wait for a confirm on the respawntimer.

**Comment by fvicaria** [comment]
Items are there.

**Comment by fvicaria** [comment]
![image](https://user-images.githubusercontent.com/9414661/33143508-fafb3ae6-cfb1-11e7-82bb-b8a29fdc457a.png)

**Comment by squalllh1989** [comment]
@Callabero  You should try it out to buy all of those limited recipe, then close the trade and talk to the npc again, you won't see them there at all, the answer you get from Icytalen is the correct answer.
