### ISSUE TITLE
[Spell]Charge/Intercept

### ISSUE THREAD

**Issue by Callabero** [WoWManiaUK/Redemption#1862]
Hello there,

U shouldnt be able to use Charge in Middle-Intercept and Intercept in Middle-charge, u might be able to use it after those 2 spells reaches their place
This is how it isnt supposed to work (recorded on wow-mania)
https://www.twitch.tv/videos/203441424

**Comment by GMWeeble** [comment]
Is there anywhere you can find us a statement from blizzard about this? That would help.

**Comment by Callabero** [comment]
Not from blizzard, since its more prot spec problem. I may give proof from other server that has scripts of blizzard wotlk and I dont know a thing that doesnt work there. There it works as indeed,

**Comment by fvicaria** [comment]
I don't see any disadvantage (or advantage) you may get from this

**Comment by Callabero** [comment]
Fvicaria, I play minely prot pvp, and those who want or play prot pvp use macro
#showtooltip
/castsequence reset=14 Charge, Intercept

Im sure u know about spamming spells 24/7 in pvp, U just use 2 charges for a single use because ur spamming it.

**Comment by fvicaria** [comment]
Just wait for weeble's reply from Blizzard.

**Comment by fvicaria** [comment]
Just confirmed that this was the case in 3.3.5a so we will not change.

**Comment by Callabero** [comment]
Can you send me where did u find it please? Its not like i believe you, Im the type who wants to see it with ones own eyes.

**Comment by Hajzlopuc** [comment]
Hello,

for example 

https://us.battle.net/forums/en/wow/topic/1253416447
> **But it makes me both Charge and Intercept as a Prot Warrior.**


thread date is Dec 6, 2010 that means it's from WotLK because the third expansion set, Cataclysm, was released on December 7, 2010.
