### ISSUE TITLE
Professions

### ISSUE THREAD

**Issue by Igotpooedon** [WoWManiaUK/Redemption#1864]
Hi, How come some Grandmaster professions require lvl 60 while others require lvl 65?

**Comment by squalllh1989** [comment]
http://wowwiki.wikia.com/wiki/Profession
Gathering profession (Herbalism, Mining, Skinning, require level 55 to train grandmaster, while non-gathering (all other primary profession) require level 65 to train grandmaster.
But, this is not where you asking for those thing, this is only for reporting bug you found in the game to help developer fix the server, please ask this on the forum, thank you very much.
