### ISSUE TITLE
[Core] 1x blizzlike mob xp not working

### ISSUE THREAD

**Issue by magicwin** [WoWManiaUK/Redemption#1865]
Hello! The 1x blizzlike xp rate is not working for mobs. For example, at the starting area when I was level 1 and I killed a level 1 mob, I should be getting 50 xp but instead I am only getting 25 xp which is 0.5x xp rate. The formula for mob exp is as follows:
XP = (Char Level * 5) + 45, where Char Level = Mob Level, for mobs in Azeroth
XP = (Char Level * 5) + 235, where Char Level = Mob Level, for mobs in Outland
XP = (Char Level * 5) + 580, where Char Level = Mob Level, for mobs in Northrend
This is taken from the wow wiki: http://wowwiki.wikia.com/wiki/Formulas:Mob_XP

Please look into this matter, thank you very much!!

**Comment by fvicaria** [comment]
You have to go to the NPC to set to x1 otherwise you get the server default which is x2.
This has been tested and proven correct for a long time.
So if you still think it is wrong please attach screenshots and describe exactly on what XP you are set to and which day of the week it is. There are many factors here that will affect your XP.
Send me all the info and I will be happy to read it. As it is stated I will not spend time on it.

**Comment by magicwin** [comment]
Hello! Thanks for replying. I am aware that the default xp rate is 2x and i have changed my xp rate at the NPC to 1x. It is on a friday. Attached are the screenshots of xp i have received on both 1x xp rate and 2x xp rate to show the difference. I have tested this on at least 2 starting areas namely night elf and human. Please help look into this again. Thank you so much!!

![wowscrnshot_112517_010012](https://user-images.githubusercontent.com/12128913/33219406-11d3448a-d17d-11e7-94b9-7fc20d53a431.jpg)
![wowscrnshot_112517_010128](https://user-images.githubusercontent.com/12128913/33219415-14ef7cb0-d17d-11e7-9b24-1e91e7335298.jpg)
![wowscrnshot_112517_010518](https://user-images.githubusercontent.com/12128913/33219417-17da6048-d17d-11e7-9310-5c26459075c7.jpg)
![wowscrnshot_112517_010557](https://user-images.githubusercontent.com/12128913/33219420-1a8a7f58-d17d-11e7-9dac-7ca056a66dbe.jpg)

**Comment by fvicaria** [comment]
So server default is 50 you set to x1 and get 25. Is that right?

**Comment by fvicaria** [comment]
I am checking it now.

**Comment by magicwin** [comment]
No, server default is x2 xp rate and i get 100 xp. When i set it to x1 xp rate, i only get 25xp. Thank you very much for checking!

**Comment by fvicaria** [comment]
Confirmed and fixed in dev. Thanks a lot.
