### ISSUE TITLE
[Spell] Spell Reflection

### ISSUE THREAD

**Issue by Callabero** [WoWManiaUK/Redemption#1866]
http://wowwiki.wikia.com/wiki/Spell_Reflection at warrior doesnt reflect multiple spells as it should, reflect buff disappears when (we say shaman casts lightning bolt) a NPC/player finishes cast that has is flying also in the air.
https://www.youtube.com/watch?v=dHp3Cm5AiLw&t=135s Video isnt from wotlk sadly i cant find any clip where its clearly visible, anyways if u take a look at first link, there was no such a change as single spell reflect. Check 1:40

**Comment by fvicaria** [comment]
Spell reflect will reflect 1 spell only. Please use Armory links only or in the worst case wowhead.com.

**Comment by Callabero** [comment]
Since tbc-current expansion spell reflect was never reflecting only 1 spell. Where did u get that it should reflect just 1 spell? since on other unknown server where reflect works as indeed says the same. https://imgur.com/a/ozyxV

**Comment by wow-mania** [comment]
Send me the actual date from wotlk.


Regards,

Janitor
wow-mania.com<http://wow-mania.com/>
The best WotLK server

Skype: wow-mania.com<http://wow-mania.com/>
[1496666926534_468x60.gif]

________________________________

**Comment by Callabero** [comment]
which date do you mean about wotlk?

**Comment by fvicaria** [comment]
Where did you get that info from?
Send me the link to the spell from a wotlk 3.3.5a source

**Comment by Callabero** [comment]
https://wotlk-twinhead.twinstar.cz/?spell=23920 Description of a spell doesnt change,
heres other proof that it reflects multiple spells (now on wotlk) https://www.youtube.com/watch?v=_uJVfRQW1ms&t=343s time 6:45 reflects mages frost bolt with icelance (shatter)

**Comment by fvicaria** [comment]
"The next spell"

**Comment by Callabero** [comment]
And video where warrior reflects 2 spells on 3.3.5a version is ignored? -_-

**Comment by fvicaria** [comment]
Yes, totally ignored. I don't know who made the video, which server, etc. I need written info.

**Comment by Callabero** [comment]
I write message on skype, since ive to say name of a server.

**Comment by fvicaria** [comment]
I don't care what other servers do. I have given info on the spell description. It does what says on the tin. This is as 3.3.5a unless I see otherwise.

**Comment by Callabero** [comment]
Yes, description says "a spell" but server is and was the only 1 that had copied retail database on their server. There was and there isnt until now any spell bug.  I play wow 10 years and ive started on retail wotlk. It worked as i say here and as u can see in video i sent here. U dont need believe, but think about it. Insteed of rejecting all proofs ive given.

**Comment by fvicaria** [comment]
You have not given any reliable proof. Videos from Youtube from unreliable sources will not be used as evidence. I have also played for over 10 years and can tell you that the spell is correct.
Feel free to send a mail to Blizzard and wait for the answer.
