### ISSUE TITLE
[Quest] Absholutely... Thish Will Work!

### ISSUE THREAD

**Issue by Harbenger** [WoWManiaUK/Redemption#1868]
You are to use the quest item given on the vrykul prisoner.  However when I arrive in the prison the vrykul was dead, I waited for respawn, but when trying to use the quest item on it, the vrykul dies before the chaneneling time completes to use the item.  I tried it 3 times and requested GM help.

GM Psygoa responded and we tried it a few times with him/her respawning the vrykul and it dies before the channeling time completes everytime.  He asked me to report it here

**Comment by fvicaria** [comment]
Please follow the procedure described below before creating a new issue:
[How to Properly Report an Issue](https://github.com/wow-mania/Redemption/wiki/How-to-Properly-Report-an-Issue)

This will help developers identify and fix the issue quicker. Incorrectly or unclear reports will simply be deleted.

**Comment by fvicaria** [comment]
http://www.wow-mania.com/armory/?quest=11330
