### ISSUE TITLE
Sewer Beast Bugged

### ISSUE THREAD

**Issue by AgentMaineMeta** [WoWManiaUK/Redemption#1869]
After reaching lvl 50 I went to stormwind to tame the unique silver crocilisk Sewer Beast.
Ever since taming him, i've been unable to feed him, all spells respond as being "Evaded" by him, and he will not attack anything nore follow me. I've tried loging out and loging in, exitting the entire game, restarting, all that. Nothing is working.

**Comment by fvicaria** [comment]
Send me a skype message or email with your character name and I will copy it and test it.
