### ISSUE TITLE
[Quest] Hints Of A New Plague ID 657 (A)

### ISSUE THREAD

**Issue by sarahsmiles21** [WoWManiaUK/Redemption#1870]
Cannot Speak To NPC Kinelory

http://www.wowhead.com/quest=657/hints-of-a-new-plague
![wowscrnshot_112417_221005](https://user-images.githubusercontent.com/33974105/33227640-6ed4226c-d164-11e7-9e7c-39e83d13a440.jpg)

**Comment by fvicaria** [comment]
Check on dev and on Redemption and it could not be reproduced. Maybe some quest dependency missing or NPC reset issue.
