### ISSUE TITLE
[Hunter Pet] Devilsaur beeing out of range

### ISSUE THREAD

**Issue by Trattfan** [WoWManiaUK/Redemption#1874]
Sometimes when I send my http://www.wowhead.com/pet=39/devilsaur in for an attack it just stands behind the npc/boss but doesn't attack, auto or spells. When i try to use the spells manually (http://www.wowhead.com/spell=17253/bite, http://www.wowhead.com/spell=54680/monstrous-bite) it says that my pet is out of range. 

This doesn't happend on every boss or mob enough times to sink my DPS. 
Sometimes it can be fixed by clicking follow and then sending it in again, however this doesn't always work. 

Had no problems with my previous pet(http://www.wowhead.com/npc=3809/ashenvale-bear) so I think it's Devilsaur specific.

**Comment by fvicaria** [comment]
Cannot reproduce. This is a core issue and can help sometimes. Not specific to a particular pet.

**Comment by Trattfan** [comment]
If you want it reproduced you could join me in a dungeon so i could show you. 

Does core issue mean that it's "in the game"? 
Hasn't happend once with cats, bear, wolfs or normal raptors, only the devilsaur.
