### ISSUE TITLE
RAID. KARAZHAN. fiery warhorse in karazhan.

### ISSUE THREAD

**Issue by mahtaaaa** [WoWManiaUK/Redemption#1878]
hi.
i`ve worked on the key to karazhan for a week to get my guild to come and farm for this mount. 
but as we attacked the midnight to get the master to show up. he didn't came and the midnight died. there was no loot and the instance was locked on us for a week.
i dont want to do this next week just to ashamed my self. 
also in the wow mania website the drop rate for the mount is 99 witch is awesome if its true.
please help me get that mount.
sincerely. mahta

**Comment by fvicaria** [comment]
What level were you?

**Comment by mahtaaaa** [comment]
Hi. Im lvl 80 human rogue.

**Comment by fvicaria** [comment]
This is due to over DPS. The dungeon was not made for level 80. You have to slowly dps the NPCs or it will skip phases.
