### ISSUE TITLE
Scourge Tactics

### ISSUE THREAD

**Issue by Vuneny1** [WoWManiaUK/Redemption#1879]
The quest "Scourge Tactics" (http://www.wowhead.com/quest=13008/scourge-tactics) isn't working on the Redemption server. In the "Valley of Echoes" which is located in the region of Icecrown, near the Argent Vanguard should be NPC's called "Webbed Crusaders". After you kill them you should actually free that webbed crusader which should count for your quest, since you need to free 8 of them.
The link for the quest is included so there is the quest giver also.
I used the help of the GM called Amytis and now I am here to report the issue with the quest.
Thank you!

**Comment by fvicaria** [comment]
FFS search first!! It's 3 issues below.
