### ISSUE TITLE
Gnomish Shrink Ray is bugged.

### ISSUE THREAD

**Issue by Herkumer521** [WoWManiaUK/Redemption#1880]
The Gnomish Shrink Ray is bugged for my friend and I. I contacted Psygoa and tested it with them. When I use the ray, nothing will happen but the item will start its 5 minute cool down indicating that I used it.

**Comment by fvicaria** [comment]
Please follow the procedure described below before creating a new issue:
[How to Properly Report an Issue](https://github.com/wow-mania/Redemption/wiki/How-to-Properly-Report-an-Issue)

This will help developers identify and fix the issue quicker. Incorrectly or unclear reports will simply be deleted.

**Comment by fvicaria** [comment]
http://www.wowhead.com/item=10716/gnomish-shrink-ray
http://www.wowhead.com/spell=13006/shrink-ray
