### ISSUE TITLE
[Quest] Territorial Trespass

### ISSUE THREAD

**Issue by roleplay1** [WoWManiaUK/Redemption#1882]
When you put the  egg the broodmother  shows up thorium yells to watch out text is following ending  that you  have come up to thorium. But  the  quest will not complete so you can't deliver
![wowscrnshot_112817_030625](https://user-images.githubusercontent.com/25806660/33298993-dbc76050-d3e9-11e7-8745-9aa15e571392.jpg)

**Comment by fvicaria** [comment]
Quest works. Please search before posting a new issue #1871
