### ISSUE TITLE
Quest not working properly:  Learning to communicate

### ISSUE THREAD

**Issue by wreyno2** [WoWManiaUK/Redemption#1884]
The quest in the borean tundra: Learning to communicate is not working as it should. It states to kill the elemental at the bottom of the sea and target her body and use the quest item which is a shell. but when you do this, nothing happens. Please fix as needed.

**Comment by fvicaria** [comment]
Please follow the procedure described below before creating a new issue:
[How to Properly Report an Issue](https://github.com/wow-mania/Redemption/wiki/How-to-Properly-Report-an-Issue)

This will help developers identify and fix the issue quicker. Incorrectly or unclear reports will simply be deleted.

**Comment by fvicaria** [comment]
![image](https://user-images.githubusercontent.com/9414661/33368613-11f8c492-d4ea-11e7-89a7-5bb00093600e.png)

Works just fine.
