### ISSUE TITLE
[Quest] The Mist Isn't Listening

### ISSUE THREAD

**Issue by Wolch** [WoWManiaUK/Redemption#1885]
http://www.wowhead.com/quest=12538/the-mist-isnt-listening
Need to kill the mobs for the quest, but cannot attack them. They are hostile, but when I try to attack I get the message "Invalid target".
![wowscrnshot_112917_194110](https://user-images.githubusercontent.com/28511078/33387066-63929e38-d53d-11e7-9760-795b45912038.jpg)

**Comment by fvicaria** [comment]
This is a faction issue due to some quests missing.
I will try to sort it in a general way.
