### ISSUE TITLE
Legendary Artifact Weapon ( Eagle's Rebirth )

### ISSUE THREAD

**Issue by Unstoppablee** [WoWManiaUK/Redemption#1890]
Hi! I bought the legendary weapon from the mall vendor ( Eagle's Rebirth 2H - Staff ) and i noticed that the Blade part of the weapon is pointing towards the ground wich is wrong way.
Also I will apologize because I could not find ID of weapon anywhere.

![on char](https://user-images.githubusercontent.com/26930686/33407511-5b8b6c1e-d57a-11e7-848c-c4f14de12f67.png)

I did make a ticket ingame and i had chat with GM Weeble and he told  me to report this in Github and it will be sorted. 

I also took Proof from Retail WoW that it is seriously pointing the wrong way. under the text is the Right Model of the weapon.

![right model in retail](https://user-images.githubusercontent.com/26930686/33407579-ad2f8366-d57a-11e7-95d0-7d0b909caa19.PNG)

thx for reading.

**Comment by fvicaria** [comment]
Nothing we can do about it. This is how the old client renders the new item brought from other expansions.
