### ISSUE TITLE
Broken proc of a weapon

### ISSUE THREAD

**Issue by Phantomyzed** [WoWManiaUK/Redemption#1892]
http://www.wow-mania.com/armory/?item=46017 this mace is buged and procs only if u switch weapons, relog or die then respawn otherwise no metter how long u heal it wont proc only if u switch it with other weapon then switch it back and continue heal but the bubble will only refresh as long as the buff from the proc exist which is 15sec when the buff expires it wont proc

**Comment by Hajzlopuc** [comment]
[Look here](https://github.com/WoWManiaUK/Redemption/issues/1877)

**Comment by Phantomyzed** [comment]
oh ty Hajzlopuc didnt know that it was posted already :)
