### ISSUE TITLE
Quest:  Mending Fences

### ISSUE THREAD

**Issue by ooger** [WoWManiaUK/Redemption#1894]
First of all, the dwarves don't get aggro on the giants after throwing the boulder at the giant.  I finally killed them on my paladin and when I went to throw a rock at Fjorn the game wouldn't let me.  I logged off last night after submitting a ticket and since it said the wait time was long I logged off and today when I logged on, Fjorn was gone but the quest was unfinished and it looked like it was ready for the next step in gaining rep with sons of hodir.  The step where you take control of the giant and throw snowballs at the fire revenants.  But no other quests and the current quest is incomplete.

**Comment by fvicaria** [comment]
They won't aggro if the giant is far away.
You have to aggro the giant and move it to the dwarves so they can help you.

![image](https://user-images.githubusercontent.com/9414661/33475381-2418d968-d676-11e7-8437-639f7d915492.png)

**Comment by ooger** [comment]
Ok, but I still can't find Fjorn to kill him to complete the quest and go on to the next quest in the chain.
