### ISSUE TITLE
[Item] Schematic : Field Repair Bot 110G

### ISSUE THREAD

**Issue by Ewacy** [WoWManiaUK/Redemption#1895]
Are the loot tables for "Schematic : Field Repair Bot 110G" working correctly (http://www.wowhead.com/item=34114/schematic-field-repair-bot-110g) .  According to Wowhead comments it should drop fairly often to as a drop which only engineers can see.  By now i have killed atleast 600 of the mobs and by any logic it shouldv already be dropped.

**Comment by fvicaria** [comment]
Checked and confirmed correct. Drop chance is 1.4% so keep trying.
