### ISSUE TITLE
Achievement  [Guru of Drakuru]

### ISSUE THREAD

**Issue by AnetteHansen** [WoWManiaUK/Redemption#1896]
Hi

I have tried to do  [Guru of Drakuru] achievement (http://www.wowhead.com/quest=30120/cleansing-draktharon) 3 times now. I get the mojos as normal on normal mode. When i summon the quest giver with the items needed at the braiser, it starts as it is suppose to, but then LK goes the wrong way instead of starting the long conversation with the questgiver and it bugs out. 
https://gyazo.com/f3ef30e94b9df11290a0698c2cd52603 Picture of LK going the wrong way.
This video shows where LK is suppose to stand and how it is completed.https://www.youtube.com/watch?v=SOoyaSdG6i4

**Comment by fvicaria** [comment]
Can you clarify this better?
What can't you get in HC? Can you link it please?

**Comment by AnetteHansen** [comment]
Hey Janitor

Sorry for the bad explanation on the first github issue. I have edit it now
and linked a video of how it should get completed.
Let me know if i can do anything else



2017-12-01 19:26 GMT+01:00 Janitor <notifications@github.com>:
