### ISSUE TITLE
Anzu

### ISSUE THREAD

**Issue by WhitephoenixTheBunny** [WoWManiaUK/Redemption#1898]
hello
After Summoning Anzu in Sethekk Halls, he didn't show up... the last time i'd summon him wasa 2 or 3 days ago.
thx

**Comment by Unstoppablee** [comment]
I will confirm this on Redemption. It happens from time to time that you are not able to summon boss at all. You kill or skip first boss, after you will clear trash in the room, and try to summon Raven Lord (Anzu), it does cast, but nothing is happening after. After 1 min you are able to try it again, but nothing will happen.
I've reported this in game many times, GM's helped by removing my ID. And pointed me to GitHub.

Boss: http://www.wowhead.com/npc=23035/anzu
Instance: http://www.wowhead.com/sethekk-halls

Thanks.

**Comment by fvicaria** [comment]
Tested again and it works. Unless you have an old instance id.
