### ISSUE TITLE
Aldor shoulder inscription not working as intended

### ISSUE THREAD

**Issue by TheGreyMouser** [WoWManiaUK/Redemption#1899]
I leveled aldor rep to enchant heirloom shoulder slot items.  The enchantment applies just fine to the item, which remains "account bound" but when mailing item, it generates a "You can not mail soulbound items".  This is not the way it is on blizzard.  You can mail heirlooms regardless of enchantments as long as the enchantment level requirement is met, it will work.   Example..  +15 agil on balanced heartseaker will work as intended.  +20 agil (require item level 35+) will not word.  Also as intended. 
Thanks for looking into this.  The item in question is on my Fafhrd character.

**Comment by fvicaria** [comment]
Any modification done to the item makes it soulbound, gem, enchant, transmog, damaged etc.

**Comment by TheGreyMouser** [comment]
Sorry, but you are incorrect.  Adding a gem or enchant does NOT cause an item to become soulbound. Especially an account bound heirloom item.    I don't think you can mail transmogged items, since they become soul bound, but those are not heirloom items.  Damage does not make the item soul bound either, you just cant mail or auction them until repaired.

**Comment by fvicaria** [comment]
It does here in our core. I am not 100% sure 3.3.5a wasn't like this either. I would need to research it.

**Comment by TheGreyMouser** [comment]
ok, thanks.  Can you remove the enchant from the heirloom shoulders on Fafhrd?  Tattered dreadmist mantle I think.   Not worried about the dust or inscription.

**Comment by fvicaria** [comment]
Sure. I will send you a new one.

**Comment by TheGreyMouser** [comment]
ok thanks.   Let me know what you find out about those inscriptions.  Everyone I have found only requires that item level requirment be met.  IE.. level 1 enchants on heirlooms.

**Comment by fvicaria** [comment]
Can you link the spells or items please.

**Comment by TheGreyMouser** [comment]
http://www.wow-mania.com/armory?item=38880 (scroll of enchant weapon - agility)
http://www.wow-mania.com/armory?item=42944 (Balanced Heartseeker - heirloom dagger)

**Comment by TheGreyMouser** [comment]
I found this.. on wowhead comments, if this helps.


http://www.wowhead.com/item=28881/inscription-of-discipline#comments

[http://wow.zamimg.com/images/wow/icons/large/spell_holy_sealofwisdom.jpg]<http://www.wowhead.com/item=28881/inscription-of-discipline#comments>

Inscription of Discipline - Item - World of Warcraft<http://www.wowhead.com/item=28881/inscription-of-discipline#comments>
www.wowhead.com
Inscription of Discipline is a level 64 permanent item enhancement. It is sold by Scribe Saalyn. In the Item Enhancements (Permanent) category.




________________________________

**Comment by fvicaria** [comment]
She does sell the item...
![image](https://user-images.githubusercontent.com/9414661/33530123-59fd359e-d872-11e7-9a4c-7a3e34499c94.png)
