### ISSUE TITLE
[Quest] Collection Of Goods ID 7642

### ISSUE THREAD

**Issue by sarahsmiles21** [WoWManiaUK/Redemption#1900]
Cannot interact with the supply crates where stratholme holy water is found. tried resetting and relogging didnt work. succsessfully completed an earlier quest requiring stratholme holy water

http://www.wowhead.com/quest=7642/collection-of-goods

**Comment by fvicaria** [comment]
I cannot reproduce this. 
Make sure you have all the pre-quests as per your link, that you are a paladin. :)

**Comment by sarahsmiles21** [comment]
You cannot get this quest without doing the previous ones
