### ISSUE TITLE
[Spell] Leatherworking - Light Leather

### ISSUE THREAD

**Issue by ResFount** [WoWManiaUK/Redemption#1902]
http://www.wow-mania.com/armory/?spell=2881

When you skin certain beasts sometimes they drop Ruined Leather Scraps ( http://www.wow-mania.com/armory/?item=2934 ) and with the spell "Light Leather" ( http://www.wow-mania.com/armory/?spell=2881 ) you can turn them into Light Leather ( http://www.wow-mania.com/armory/?item=2318 ). Trainer should teach you the spell ("Light Leather") when you first learn leatherworking profession.

But trainer doesn't teach Light Leather spell. As I read from other posts with right clicking on Ruined Leather Scraps you can create Light Leather but it doesn't give any profession skill.

**Comment by fvicaria** [comment]
As is. You don't get skill up from it. If that is what you are after.

**Comment by ResFount** [comment]
It was like that in Wotlk-Retail. It is a bug and I reported a gm in game. Gm told me to write here and I'm doing it. This is what I am after.

**Comment by fvicaria** [comment]
OK, I will check it.
