### ISSUE TITLE
Ahn'Kahet: The Old Kingdom

### ISSUE THREAD

**Issue by Necko23** [WoWManiaUK/Redemption#1903]
Achievement "Volunteer Work" is bugged.
![wowscrnshot_120217_162425](https://user-images.githubusercontent.com/34190680/33517095-13e0bd3c-d77e-11e7-9fb9-97c531b64848.jpg)
We've been sitting for around 5-10 minutes. We did make a ticket and someone (hopefully) started working on resolving the issue. As you can see volunteer just stands there, and nothing happens. We were going for the "Glory of the Hero" achievement.

**Comment by fvicaria** [comment]
That is not how it works I am afraid. You log the issue and we go check, test, and if confirmed fixed. There is no real-time fixing. :)

**Comment by Necko23** [comment]
No worries. We'll get into it once it's fixed.
