### ISSUE TITLE
Dungeon Finder minimal requirments bug.

### ISSUE THREAD

**Issue by DebowyMocny** [WoWManiaUK/Redemption#1904]
![wowscrnshot_120217_180837](https://user-images.githubusercontent.com/24268721/33517971-b43a1026-d78d-11e7-8510-936b86650cb7.jpg)
There is a fatal issue with dungeon finder. 
Normally it should allow me to queue to heroic dungeons (Except toc, fos, pos, hor) when i have at least 180 average iLvL.
On this server i have 191,1 average iLvL and dungeon finder still doesent allow me to choose any heroic dungeon saing, i need to obtain better gear. I made restart, of game and relog.

I attached a screenshot
https://s33.postimg.org/e00qoq8wd/Wo_WScrn_Shot_120217_180837.jpg

**Comment by fvicaria** [comment]
The level is not updated realtime. It is daily
