### ISSUE TITLE
Quest: "It's All Fun and Games" not working

### ISSUE THREAD

**Issue by Boobarnes** [WoWManiaUK/Redemption#1906]
Tried this today (2 Dec 2017) at about 23:00 server time, and nothing worked, though it's worked on my 4 other 80s. I shot the Ocular repeatedly for zero damage. Normally if you attack, it attacks back, but I was up close and all around it, and nothing happened. Tried firing the special gun from different angles & positions, but nothing worked. Then someone else confirmed they had same problem.

**Comment by Boobarnes** [comment]
thanks for fixing it

**Comment by lastbullet00** [comment]
Not working again, the Ocular doesn't take any damage from using the item.
