### ISSUE TITLE
Stranglethorn Fever quest broken

### ISSUE THREAD

**Issue by LordArcadia** [WoWManiaUK/Redemption#1907]
The quest in Stranglethorn Vale, Stranglethorn Fever, is currently bugged.  The NPC, Witch Doctor Unbagwa, will not speak to the player.  He seems to be stuck in casting animation.
Note that Unbagwa is not the quest giver or the turn-in.  To do the quest, the player must seek out Unbagwa and speak to him.  He will request a Gorilla Fang.  Then an event will be triggered that will allow the player to complete the quest objective.  Since Unbagwa will not speak to the player at all, the quest cannot be done.
My toon put up a GM Ticket about this issue, and the responding GM directed me to post about the issue here.  He also gave me the final quest item so I can complete the quest without the NPC being fixed, so the issue is resolved for me, but not for anyone else.

**Comment by fvicaria** [comment]
It's fixed now. I will check the reset of the NPC next.
