### ISSUE TITLE
Raven Lord Shettek Halls

### ISSUE THREAD

**Issue by 3mz0** [WoWManiaUK/Redemption#1908]
Got the summoning item , and trying on Heroic, but  cant summon The raven lord in the instance.
in the quest chain it worked, and some days later i summoned the boss once but usually nothing happens when i try it.

**Comment by fvicaria** [comment]
Works. You can only summon it once.

**Comment by squalllh1989** [comment]
I though normally you can summon it one each day ? If it can only be summoned once, then the rein will be super hard core :v

**Comment by fvicaria** [comment]
The respawn time is a different issue. I have not checked that. I have only confirmed that the path and behavior are correct.
