### ISSUE TITLE
Pusillin and the Crescent Key

### ISSUE THREAD

**Issue by shulasassi** [WoWManiaUK/Redemption#1909]
Pusillin the demon imp, located in Dire Maul east, disappears from the dungeon. you are supposed to interact and chase him several times, then do battle. when he dies, he's supposed to drop the Crescent Key. you need the Key to enter the other 2 wings of Dire Maul. 

now, you talk to him twice, and he runs away and disappears. he does not go to his designated spot where you can fight him, he pretty much disappears from the dungeon, making acquisition of the key impossible.

this was working right at one time; several of my toons have acquired the key, albeit many months ago.

i've tried multiple characters, all with the same result. i am using the newest Launcher(2.1.3) and have all the latest patches.

http://www.wowhead.com/npc=14354/pusillin
http://www.wowhead.com/item=18249/crescent-key#comments

**Comment by fvicaria** [comment]
You have to keep up with him... He will try to lose you. If he gets too far from you he will despawn and you have to start over.

**Comment by shulasassi** [comment]
i'm running as fast as my toon can go. i killed everything on this level first, so i could chase him without having to stop and fight every few meters. 
first chase (chase_pusillin1), he runs down the hall, then floats back to his original spawn spot. he's supposed to wait for you (on solid ground lol), you talk to him, and he runs away for chase# 2.
second chase, (chase_pusillin2) same thing, he runs down the hall, then floats thru the air back to his original spot.
third chase, he floats across to the big hallway, and is supposed to run to the deck in the Hidden Reach. all I find there are alot of lashers that respawn very quickly, (chase_pusillin3), but no Pusillin.
 in retail he's always on solid ground, i've never seen him hop through open air.

maybe his despawn timer has changed?
thank you for your attention <3screenshots attached.


    On Monday, December 4, 2017, 5:27:34 AM CST, Janitor <notifications@github.com> wrote:  
 
 
You have to keep up with him... He will try to lose you. If he gets too far from you he will despawn and you have to start over.

**Comment by squalllh1989** [comment]
I can confirm on this, as i already tried to get the key myself. I can get the key after all the effort, but the imp is buggy as hell, he is suppose to run and we have to chase him, but how do we do it if he keep float in the air and go through wall >.<. The only posible way to do it is to sit ide at where the chase start, as he will back to that spot after a long wait time, and you have to wait there 3 times for 3 round of chase, or you must clear all mob in the dungeon first and track him down in the chase with warlock 's demon track with a hope that he is at some where you can hit at the end. I finally get my key some how (sorry i can't remember exactly, i will try to test it again in some time soon when dev is up)

**Comment by fvicaria** [comment]
I have personally done this yesterday.
It's not buggy. It has 2 points where it will accept a gossip dialog and you have to talk to him before he leaves. You just have to be faster.
