### ISSUE TITLE
[Quest] Mutiny on the Mercy 

### ISSUE THREAD

**Issue by Noahcoke** [WoWManiaUK/Redemption#1910]
For the quest http://www.wowhead.com/quest=11527/mutiny-on-the-mercy you are on a ship and have to go under deck to kill 5 ghouls where each drops one of the needed items. 

While doing it i saw that there are only 4 of those ghouls (http://www.wowhead.com/npc=25026/mutinous-sea-dog). So you are forced to wait for them to respawn for that one missing item. In addition the respawn time is very long, i had to wait at least 20 minutes (i am writing this while still waiting).

Maybe its possible to add one more of those npcs and reduce the respawn time. 

Update: 2hrs later another player in worldchat asked about that quest being bugged, apparently the needed npcs still didnt respawn. 

Sincerely,
Noah

**Comment by fvicaria** [comment]
The mobs sometimes fall through the ground of the boat that moves. There is another boat docked with the needed mobs.

Also, next time search before creating a new issue.
