### ISSUE TITLE
quest:the drakkensryd

### ISSUE THREAD

**Issue by larian** [WoWManiaUK/Redemption#1911]
wel the problem here is the fact u cant attack any mobs when u jump from dragon to dragon....and a lot of mobs just falling to their deaths (looks funny but still)...so cant complete the quest

**Comment by squalllh1989** [comment]
Hi @larian , thank you for reporting the problem you had to help improving the server.
About the problem you have here, the quest [The Drakkensryd](http://www.wow-mania.com/armory/?quest=12886) work, just try another mobs, ignore the mobs that evade, this problem already have many time reported, you can take a look at some report over [here](https://github.com/WoWManiaUK/Redemption/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+Drakkensryd+), you should search before make a new report, and you should report in proper form to help the developer and tester quickly confirm and solve the problem. Thank you for helping, hope you can solve your problem soon.
Best regard.
