### ISSUE TITLE
Lich King Set

### ISSUE THREAD

**Issue by basbro** [WoWManiaUK/Redemption#1913]
Recently purchased lich king set on my shaman. As many know the Leather set and Mail set do not have the correct stats. All I ask is these stats be fixed so I can properly play my character. I am enhance shaman which means all my stats need to be attack power. (Some are spell power and all of the set bonus is spell power based). Also two of the procs for the set bonus ONLY proc when I use ghost wolf which means less DPS for me (by about 2k). All I ask is that I know this is being worked on. I paid a lot for this to actually be an issue. I can even tell you which pieces need fixed. 

An issue I have with this though is these sets would be SPEC specific so an ENHANCE shaman should not buy the Mail set.

**Comment by fvicaria** [comment]
Not a server issue. Please contact me via Skype.
