### ISSUE TITLE
[Quest] Frost Infusion

### ISSUE THREAD

**Issue by Magabro** [WoWManiaUK/Redemption#1916]
When completing the Frost Infusion quest for Shadowmourne, paladins can take 28,000 damage ticks from Frost Infusion buff when the damage should be 2,000.

With Raid buffs, gear, and flasks, I have 570 Frost resistance and 50,000 hit points.  This tick damage is unhealable and has prevented completion of the quest 3 times now.

Game masters have said they "cannot help" with this issue in game....

![wowscrnshot_120717_123118](https://user-images.githubusercontent.com/34353250/33738164-5015eb1a-db4d-11e7-8f25-68970a3bdce4.jpg)
![wowscrnshot_120717_123121](https://user-images.githubusercontent.com/34353250/33738168-520337b6-db4d-11e7-9750-f3416d68d956.jpg)
![wowscrnshot_120717_123125](https://user-images.githubusercontent.com/34353250/33738171-5410418e-db4d-11e7-89f0-26cac35f9659.jpg)

**Comment by fvicaria** [comment]
Sorry quest works and many have done. I am not looking into it.

**Comment by Magabro** [comment]
Did you look at the screen shots? i am taking 28k tick damage you see this correct?

**Comment by ManiaLightmare** [comment]
[Frost Infusion Quest](http://www.wow-mania.com/armory/?quest=24757)
[Frost Infusion](http://www.wow-mania.com/armory/?spell=72292)
[Mystic Buffet](http://www.wow-mania.com/armory/?spell=70127)

Are you sure you aren't getting stacks of mystic buffet causing the Frost Infusion aura to amplify?

**Comment by Magabro** [comment]
Yes I am sure that is not happening, We weren't even in that phase of the fight when I died.  You can see in the screenshots there are no mystic buffet stacks hitting me

**Comment by ManiaLightmare** [comment]
Right.  I'm guessing the issue is also not that its absorbing more than 4 breaths since that would take too long to match the numbers.  Since the spell appears right in the armory, my best guess would be its getting applied with some sort of multiplier for some reason.   How many stacks did you have before it started doing the 28k base damage per second?

**Comment by Magabro** [comment]
At 4 breathes the debuff becomes frost infused weapon and you stop taking the frost infusion tick damage.  This issue occurred at 3 breathes.

**Comment by fvicaria** [comment]
The spells match the Armory. There is no multiplier.

**Comment by ManiaLightmare** [comment]
Which  leads back to how could a spell that should do at most (537 x 3) damage per second be ticking for almost 30k.  Strange.

**Comment by fvicaria** [comment]
I will look into this. Apologies to you Magabro but my first reaction will always be to doubt the player. This may be a case of a spell being proportional to your spell power which would explain why DKs and warriors can do it no problem.

**Comment by Magabro** [comment]
Thank you Janitor.  

For additional information to help:  In the gear i was wearing I have 967 spell power and 390 base frost resistance (570 with raid buffs, resistance flask, and frost aura).

If you need any more information or if I can help to test/solve please let me know.

**Comment by fvicaria** [comment]
I have a potential fix for that. It's in dev now. I will try to push tomorrow morning.

**Comment by Magabro** [comment]
Thank you!.  Any idea what the issue was?
