### ISSUE TITLE
Time for answers (part 1 of 3)

### ISSUE THREAD

**Issue by Blasphemiah** [WoWManiaUK/Redemption#1919]
When I get to the desgnated place where the little ghost is supposed to be to talk to him, he is simply not there. I have looked up a video guide just in case he was hidden somehow, but no, the little guy is simply not there. I have abandoned the quest and taken it again, but the issue persists.

![sin titulo](https://user-images.githubusercontent.com/33109088/33785144-1ad11106-dc64-11e7-9646-935f4fafb255.png)

**Comment by fvicaria** [comment]
Same issue. You missed something and is in the wrong phase.

**Comment by Blasphemiah** [comment]
Humm something like? I'm just doing the quests in the order I'm given, less than 30 to get the icecrown achievement :-s

**Comment by fvicaria** [comment]
Ask a GM to complete this one for you. I will investigate it a bit more.
