### ISSUE TITLE
Fringe Science Benefits (part 2 of 2)

### ISSUE THREAD

**Issue by Blasphemiah** [WoWManiaUK/Redemption#1920]
While trying to do that quest, there is no npc to shoot at below 
![sin titulo](https://user-images.githubusercontent.com/33109088/33786174-585c0cf2-dc68-11e7-8f0e-ed197856669e.png)
and when the gargoyles attack your plane bullets just go through them and don't injure them, so they kill you in god mode

**Comment by fvicaria** [comment]
You are probably in the wrong phase they are there.

**Comment by Blasphemiah** [comment]
In the wrong phase? I see them when I'm on foot, but it's only when i do the quest on the plane that there is no no one to be seen. I have also tried and bomb all over the area just in case they are too far to be detected from up high, but i hit nothing.

**Comment by fvicaria** [comment]
I have just done it and it works.  You have to target the gargoyles and wait for troops on the ground and switch to the bomber seat.

![image](https://user-images.githubusercontent.com/9414661/33787359-c261d2b6-dc64-11e7-8e22-508c06dab7f6.png)
![image](https://user-images.githubusercontent.com/9414661/33787365-cc31dfb6-dc64-11e7-91e9-aba239fe69bc.png)
