### ISSUE TITLE
Redridge mystic

### ISSUE THREAD

**Issue by Igotpooedon** [WoWManiaUK/Redemption#1921]
hey, the monster redridge mystic's lightning bolt has more range then the normal lightning bolt or is this mob casting a diffrent kind of lightning bolt? normal lightning lot has 30 range while they can cast 35+

**Comment by fvicaria** [comment]
Can you please add link to the armory for the NPC.

Please follow the procedure described below before creating a new issue:
[How to Properly Report an Issue](https://github.com/wow-mania/Redemption/wiki/How-to-Properly-Report-an-Issue)

This will help developers identify and fix the issue quicker. Incorrectly or unclear reports will simply be deleted.

**Comment by fvicaria** [comment]
https://www.wowhead.com/spell=9532/lightning-bolt

Please research before posting an issue on a hunch or guess. That wastes dev time.
