### ISSUE TITLE
Issue with warlock pet quest. Tome of the Cabal

### ISSUE THREAD

**Issue by Grisweld** [WoWManiaUK/Redemption#1922]
When I was horde I started and finished http://www.wowhead.com/quest=1798/seeking-strahad, went and tried to get the quest http://www.wowhead.com/quest=1802/tome-of-the-cabal and it will not give me the quest now that I am ally. Not sure what went wrong when I switched from horde to ally.

**Comment by fvicaria** [comment]
Char may be messed up. Open a ticket. The quest works.

**Comment by Grisweld** [comment]
I did open the ticket since a gm asked me to. he said to open the issue here and he will give me the quest afterwards gm was Altax who is not online atm

**Comment by fvicaria** [comment]
Yes but the issue is not the ques. Something got messed up when changing faction. Ask GM to look in here and see that it has been authorized.

**Comment by Grisweld** [comment]
Np thank you very much.
