### ISSUE TITLE
Worgen Death knight 's Racial Form

### ISSUE THREAD

**Issue by egzonqt** [WoWManiaUK/Redemption#1923]
The racial on worgens its broken as u can see dks on this server using it and doing dmg so its like using a travel form and doing dmg , no hamstring or spell that reduce movement breaks that thing so  u just put worgen form its like permanent hand of freedom no stuns and etc , everytime he uses attacking spell automatically should be out of it but here its not , u can see people abusing it , i already had GM asmodeaa to watch me while i was dueling him and he directed me here 
u can test it if u need any strong proof i might make a video out of it , but its a serious issue affecting pvpers especially those that want progress in 2s 
Thanks

**Comment by squalllh1989** [comment]
Confirmed, worgen racial form not broke when you used an attack ablity on deathknight class, this giving worgen deathknight a huge advance, especially in out door pvp.

**Comment by fvicaria** [comment]
Is this only for DK? Or the racial is broken on other classes also.? Give me an example of situation so I can reproduce it.

**Comment by egzonqt** [comment]
Well exactly its like being a dk with a druids travel form thats the point that i wanted to make and my report is only for dks as i havent seen any warrior doing bladestorm in that form , basically u could see the dk playing as  a mage throwing shadow dots and running away with stun immune and immune to being slown

**Comment by squalllh1989** [comment]
i only found the problem on DK only

**Comment by egzonqt** [comment]
Hmm Aye  cool that means u'll fix that , thank you one more time ^^

**Comment by fvicaria** [comment]
I will do my best.

**Comment by fvicaria** [comment]
Can you send me the link to the dk spell you are using

**Comment by squalllh1989** [comment]
Well i used every single attack spell i can use at that level, like [Blood Strike](http://www.wowhead.com/spell=52374/blood-strike), [Plague Strike](http://www.wowhead.com/spell=61600/plague-strike), [Icy Touch](http://www.wowhead.com/spell=52372/icy-touch), [Death Coil](http://www.wowhead.com/spell=47541/death-coil)

**Comment by fvicaria** [comment]
They should all break the Worgen form now on dev.

**Comment by squalllh1989** [comment]
Confirmed, attack spells are now break the worgen form when used in dev.

**Comment by lastbullet00** [comment]
This issue is up again:
![image](https://user-images.githubusercontent.com/34487562/35575090-33fba8cc-05e4-11e8-90f9-5030cd155fbb.png)

**Comment by lastbullet00** [comment]
![image](https://user-images.githubusercontent.com/34487562/35575112-47f8032a-05e4-11e8-8ab6-0475380a91ed.png)
