### ISSUE TITLE
Grinning Reaver not longer Flying "Legion Mount"

### ISSUE THREAD

**Issue by GunpowderGuru** [WoWManiaUK/Redemption#1924]
Hey,
I got the legion Mount "Grinning Reaver" and after the last Update he cant Fly anymore.
You can Mount him now in the  Towns but he won´t fly in Northrend and Outlands.

Anyone else have this Problem? 
Greetings

**Comment by fvicaria** [comment]
This is not a bug. It is not made to fly on purpose.

**Comment by GunpowderGuru** [comment]
https://www.youtube.com/watch?v=YRbLqOWPTTw

Use: Teaches you how to summon this mount. The capabilities of this mount depend on your Riding skill and location.

It can fly on the Retail and it worked the whole time. So i think its a bug yaeh

--

**Comment by fvicaria** [comment]
THis is not Legion. We imported the mount as a ground mount. It was causing too much problem before.
