### ISSUE TITLE
Grinning Reaver doesn´t fly anymore.

### ISSUE THREAD

**Issue by GunpowderGuru** [WoWManiaUK/Redemption#1925]
Hi,
Last one got closed but there is still the Problem.
I got the Legion Mount "Grinning Reaver" and it used to can fly.

"Reins of the Grinning Reaver - This is a special donation-only mount for level 70 and up. Flies in Northrend and Outland. It requires Riding (300) and it is BOP."

Since the last update via Launcher my Reaver can´t fly anymore.  I wouldn´t have payed so much pounds if it was just a Groundmount. And in it´s description it says clearly that it can fly... 

So before closing this Issue take care of it....

**Comment by fvicaria** [comment]
Please do not open issues that have been close. Send me a message on skype or email.

**Comment by GunpowderGuru** [comment]
Then say me where i can find you email address...

**Comment by fvicaria** [comment]
how about the website?

support@wow-mania.com
