### ISSUE TITLE
 mail becoming empty

### ISSUE THREAD

**Issue by 27starch** [WoWManiaUK/Redemption#1926]
i have mail sent form a toon that got deleted that ended up becoming empty 
have the letters stating the item in the subject  but the letter is empty  with no attachments on a few toons
at first i didnt think much of it only i think it was a small bug were i got the items and it just didnt delete letter on its own which it normally does like it does with sold items in the ah you still have to delete the incoming payment letters 

but as i was looking for my heirloom gear i had and using my addon altoholic which told me it was in this one toons mail box  but all i seen was the empty letter which i believe the problem is caused by the sender been deleted or that its been awhile,, i still have 9 days left before this empty letter gets deleted on its 30 time limit

i did talk to a gm and he heard of this happening before but we mostly did augured mostly about the fact you can mail enchanted heirloom pieces

**Comment by fvicaria** [comment]
Well, this is not a bug. You should never delete the char before collecting the mail from that char. I am sorry but whatever you sent is lost.

**Comment by 27starch** [comment]
didnt have to on retail

**Comment by 27starch** [comment]
the name would be lost would say from "unknown" but the items would still be there granted this isnt retail but it was like that then back on retail and that is why i have brought this up

**Comment by 27starch** [comment]
the mail is still there its the contents that has gone

**Comment by fvicaria** [comment]
because until you retrieve it the owner is the sender which you deleted.

**Comment by 27starch** [comment]
nymdorl, would be the deleted toon now i did made an other with the same name at lv 10 which i deleted as well 

if it dont work i am not going to worry about it i was mainly trying to point something out since i did this often on retail and was surprised to be the first to have done this on here
