### ISSUE TITLE
[Quest] Ursoc, the bear god

### ISSUE THREAD

**Issue by squalllh1989** [WoWManiaUK/Redemption#1927]
The quest [Ursoc, the bear god](http://www.wow-mania.com/armory/?quest=12236) currently have trouble with the npc despawn:
- What should happen: you talk to the npc [Tur Ragepaw](http://www.wow-mania.com/armory/?npc=27328) to start the event, he will lead you to ursoc's den, summon [Ursoc](http://www.wow-mania.com/armory/?npc=26633), after kill Ursoc, you can use the item on his corpse to complete the quest, Tur Ragepaw will finish his dialog and then despawn.
- What acually happen: after finish his event, Tur Ragepaw didn't despawn, which cause the quest to stuck for other player that come after some one already finish it (Tur Ragepaw is there, so the server won't spawn a one, which mean the player come after can't start his event, can't summon Ursoc to kill and use the quest item on his corpse to get credit).

**Comment by fvicaria** [comment]
YOu don't handle the quest back to Tur Ragepaw so it should be fine. I don't know what you are talking about.

**Comment by squalllh1989** [comment]
Well, the problem here is: to start the event of summoning ursoc, you need Tur Ragepaw at his spawn place, and his event of summoning ursoc not triggered, but if there is already another player that summoned him, Tur Ragepaw won't despawn from that, and just stand there, so there won't be another Tur Ragepaw spawn, so no one else can do that quest, until a server reset or a gm kill him, that will be very anoying. Well you could try to do the quest 2 times, one after another without killing Tur Ragepaw after the first one, you should find out that you can't do the quest the 2nd time.

**Comment by fvicaria** [comment]
Try in dev now please

**Comment by squalllh1989** [comment]
Thank you, it is fixed now
