### ISSUE TITLE
[Quest] Magic Carpet Ride

### ISSUE THREAD

**Issue by Boobarnes** [WoWManiaUK/Redemption#1928]
Yes, I am using updated launcher and client.

Magic Carpet Ride is a simple quest in Warsong Hold where you talk to Yanni, who gives you a magic carpet to ride down to the misty coast to start a quest chain on the beach. This used to work for my past toons where I flew w/o being attacked, but several people have reported in world chat lately (including 9 Dec 2017), and I experienced myself a couple weeks ago, that Kel'Thuzad attacks you as you pass over him. I was reduced to 1% health, so I was able to complete it; others have been killed and tried the quest repeatedly w/o luck.

Quest description, comments, etc here: http://www.wowhead.com/quest=11636/magic-carpet-ride#screenshots

Thank you.

**Comment by fvicaria** [comment]
I have just done this quest and it works. Yes, if you happen to fly close to Kel'Thuzad he will hit you. You need to be prepared. I have changed the path slightly so he only hits you once.

**Comment by squalllh1989** [comment]
Well the problem here is Kel'Thuzad shoudn't hit those that fly across him in this quest at all, the quest's description also said it's a " safe travel to the coast", well it's not safe at all if your current hp is lower than 5616 (which is the amount that Kel'Thuzad hit me once for)
