### ISSUE TITLE
[Spell] Warrior 4 piece set bonus

### ISSUE THREAD

**Issue by CrustyMuffin** [WoWManiaUK/Redemption#1929]
I know this issue has been posted many times but it is still not fixed even though your list of changes from your previous patch says otherwise. The issue is, that the 4-piece set bonus from T10 for fury warriors (http://www.wow-mania.com/armory/?item=51225) gives you a 20% chance, that you will get 2 stack of "Bloodsurge" (http://www.wow-mania.com/armory/?spell=46913), which makes your "Slam" ability(http://www.wow-mania.com/armory/?spell=47475) an instant instead of a cast. The problem is, that when you get 2 stack of "Bloodsurge", your "Slam" ability consumes 2 stacks instead of 1.

**Comment by squalllh1989** [comment]
Still not fixed, after test out in dev, 1 use of ["Slam"](http://www.wow-mania.com/armory/?spell=47475) still consume 2 stack of ["Bloodsurge"](http://www.wow-mania.com/armory/?spell=46913) instead of 1

**Comment by fvicaria** [comment]
I have applied some changes. Please re-test.

**Comment by squalllh1989** [comment]
Still not working,  1 use of "Slam" still consume 2 stack of "Bloodsurge" instead of

**Comment by fvicaria** [comment]
You realize it's only a 20% chance? So 4 in every 5 will consume both.

**Comment by squalllh1989** [comment]
yes i know  it's 20% chance to genegrade 2 stack of "Bloodsurge" instead of 1, and what i tested was using slam when there is 2 stack of it proc, and 1 use of slam consume all 2 stack instead of use and and left me 1 more stack unused.

**Comment by squalllh1989** [comment]
![wowscrnshot_121217_224434](https://user-images.githubusercontent.com/27235989/33893626-79ed1cb6-df8e-11e7-9da1-c5cec09d0bfc.jpg)

**Comment by squalllh1989** [comment]
Confirmed, this is now working in dev
