### ISSUE TITLE
[Quest] Salvaging Life's Strength

### ISSUE THREAD

**Issue by dominichello** [WoWManiaUK/Redemption#1930]
[Quest](http://www.wowhead.com/quest=12805/salvaging-lifes-strength)
The quest requires you to Kill Lifeblood elements, near the Sundered Shard. 
Upon killing the elemental's you then need to use a Lifeblood gem to channel the corpses and collect their energy.

Once the channelling stops, nothing is registered to the quest / confirmation fails to happen.

**Comment by fvicaria** [comment]
https://www.wowhead.com/quest=12805/salvaging-lifes-strength

**Comment by squalllh1989** [comment]
Quest confirmed to be fixed on dev, the channel is counted now.
![wowscrnshot_121217_021629](https://user-images.githubusercontent.com/27235989/33849207-8a20cf12-dee2-11e7-94b8-cc1a3816613c.jpg)
