### ISSUE TITLE
Achievements. Argent Tournament. 

### ISSUE THREAD

**Issue by Noahcoke** [WoWManiaUK/Redemption#1931]
I was told to open an issue about this. 
It is about the achievement connected to the argent tournament called "Exalted Champion of the Alliance" (http://www.wowhead.com/achievement=2770/exalted-champion-of-the-alliance) and the ones as requirement called "Exalted Champion of Darnassus, Exodar ...". There is one for each city. 

In order to get those achievements you need to finish the quest "The Valiant's Charge" (http://www.wowhead.com/quest=13718/the-valiants-charge) for each city. This requires you to do 4 dailies each day for 5 day, so 25 days in total for every city. Second requirement is to be exalted with the cities. 

After having done those dailies for each city you are getting rewarded with the achievement "Champion of the Exodar" (http://www.wowhead.com/achievement=2778/champion-of-the-exodar) for example. 

Now the issue i encountered is that i am Exalted with each city and have done those dailies for every city, yet not getting rewarded with the corresponding achievement listed above. 

Also the achievements "Exalted Champion of..." only shows that i met the requirement to be exalted but not having done the dailies. Here is a picture: https://gyazo.com/b59f856006d8cc8385eee14e421a367c & https://gyazo.com/e59d3bdfdb41a1ef67d9b2aefe38f147

**Comment by GMWeeble** [comment]
issue happens when you change faction.

**Comment by fvicaria** [comment]
In that case, it needs a GM to complete.
