### ISSUE TITLE
[Quest] All Along the Watchtowers

### ISSUE THREAD

**Issue by GMWeeble** [WoWManiaUK/Redemption#1933]
Using the quest item " http://wow-mania.com/armory/?item=12815 " doest not complete the quest objectives. The quest tracker NPC is very small/invisible not sure if that could be the issue.

**Comment by squalllh1989** [comment]
Confirmed, the quest [All Along the Watchtowers](http://wow-mania.com/armory/?quest=5098) is currently bugged, the quest item can't be use. This was used to work before.
