### ISSUE TITLE
[Quest]Disrupt Their Reinforcements

### ISSUE THREAD

**Issue by wrthigpen** [WoWManiaUK/Redemption#1934]
Quest "Disrupt Their Reinforcements".  Click on portal to detonate rune stones.  Bar at bottom of screen goes across, then character says "I need to target something first" and detonation fails.  I do have runestones and primers required for detonation.  Using proper client and starting client with current launcher.

Username:  bthigpen
Character: Bulgogi
I have logged off and back on.  Another player (Charys) detonate portals but was unsuccessful.

**Comment by squalllh1989** [comment]
Confirmed, after use the quest item, the gate is not detonated, instead you get a message say "You need to target something first". This quest used to work good before also.
