### ISSUE TITLE
[Quest] Anatoly will talk

### ISSUE THREAD

**Issue by squalllh1989** [WoWManiaUK/Redemption#1935]
[This quest](http://www.wow-mania.com/armory/?quest=12330) is currently have problem: 
- What should happen: You use the quest item [Tranquilizer Dart](http://www.wow-mania.com/armory/?item=37665) on [Tatjana](http://www.wow-mania.com/armory/?npc=27627), she will fall off her horse, [Tatjana's Horse](http://www.wow-mania.com/armory/?npc=27626), you ride on the horse, it will automaticly run back to [Sasha]([url](http://www.wow-mania.com/armory/?npc=26935), then your quest is completed and you can turn it in.
- What is acually happen now: after use the quest item [Tranquilizer Dart](http://www.wow-mania.com/armory/?item=37665) on [Tatjana](http://www.wow-mania.com/armory/?npc=27627), some time she doesn't fall off, some time she does but after you try to jump on the horse, it work like a rental mount, doesn't automatic run back to [Sasha]([url](http://www.wow-mania.com/armory/?npc=26935), and if you manually control it to run back, the quest isn't completed so you can't turn it in.

**Comment by dominichello** [comment]
@fvicaria  I noticed this was marked as closed with Release 50 which was 12 days ago.
However i attempted to do it today and it still has issues.  Should i open a new ticket ? Or will the fix filter in sometime in the future.

**Comment by fvicaria** [comment]
I tested and it was working perfectly. I will check in the morning.

**Comment by dominichello** [comment]
@fvicaria Cheers ! i feel anxious some times reporting bugs with stuff i know you guys have seen before / attempted to fix already. I feel it must just be me, doing something wrong with the quest usually.

**Comment by fvicaria** [comment]
Please always report and don't feel discouraged if we dismiss it, basically that's our first reaction sometimes.
Unfortunately, a lot of players don't bother doing a minimum research before posting what ends up being invalid issues and wasting dev time.

**Comment by squalllh1989** [comment]
Just trying to finish the quest again in redemtion, still not working, Tatjana is kind of unconsious on the horse, i can ride on the horse and control it like a mount. Manually go to Sasha didn't complete the quest.
![wowscrnshot_122817_225623](https://user-images.githubusercontent.com/27235989/34415635-66f5b83e-ec22-11e7-8544-2af9ce68c6ec.jpg)

**Comment by squalllh1989** [comment]
And after i jump off the horse, it follow me like a pet xD
![wowscrnshot_122817_225722](https://user-images.githubusercontent.com/27235989/34415658-83e21be0-ec22-11e7-812f-6c915fc692d3.jpg)

**Comment by fvicaria** [comment]
Then something did not apply correctly. 
Can you try on dev now, please?

**Comment by squalllh1989** [comment]
Well yeah, it's kind of buggy, some time it didn't work. I tried today in redemtion, the first time it didn't work, when i jump in the horse it just stand there doing nothing. Then i give up, leave that and go do other quest, after a while i came back and jump on the horse and it work :)
