### ISSUE TITLE
[Quest] Tonight We Dine In Havenshire [id:12679]

### ISSUE THREAD

**Issue by Wolruht** [WoWManiaUK/Redemption#1937]
The quest "tonight we dine in Havenshire" cannot be completed if you finish the DK quest that makes the lich king move down to the base camp (dont remember the quest name for this one). Basically during the first round of DK quests there are archers by the base camp that are shooting at Havenshire but they disappear during later quests. The Saronite Arrows (id:39160) that you need to pick up in Havenshire only spawn when these archers are there.
http://www.wowhead.com/quest=12679/tonight-we-dine-in-havenshire
http://www.wowhead.com/item=39160/saronite-arrow

**Comment by fvicaria** [comment]
THis is a phase issue you missed some quest along the way.
