### ISSUE TITLE
[Quest Item] Cracked Silithid Carapace drop issue

### ISSUE THREAD

**Issue by Callabero** [WoWManiaUK/Redemption#1938]
http://www.wow-mania.com/armory/?item=5877#dropped-by
Website says it should have 100% drop. Ive killed more than 50 mobs and still nothing. It shouldnt drop by any quest chain, its just drop that creates a quest chain. I stuck at this quest more than 2 days

**Comment by Callabero** [comment]
Just dropped.

**Comment by fvicaria** [comment]
The percentages are wrong on the Armory should be: 12%, 0.3%, 8% and 4%
