### ISSUE TITLE
Quest: Leave no one behind

### ISSUE THREAD

**Issue by Blasphemiah** [WoWManiaUK/Redemption#1939]
After saving Crusader Jonathan and leading back safely to the crusader base, he gives his thankyou speech, sits down where he belongs, but it wouldn't count and the quest ins't completed 
![sin titulo](https://user-images.githubusercontent.com/33109088/33958285-42052ba2-e044-11e7-8277-1bb2e24f2ec3.png)

I tried saving him several times, dropped and took the quest again, but it keeps not counting.

**Comment by fvicaria** [comment]
I have done the quest and it worked fine. Try not to let the NPCs you are saving get into combat or they lose their aura.

![image](https://user-images.githubusercontent.com/9414661/33982250-c367072a-e0a7-11e7-9316-0c6e2537f26a.png)
![image](https://user-images.githubusercontent.com/9414661/33982262-cedd193c-e0a7-11e7-8832-0eb652d89e72.png)
![image](https://user-images.githubusercontent.com/9414661/33982278-dcbb94e8-e0a7-11e7-92ee-c116faee15a2.png)

**Comment by jarvik76** [comment]
I had the same issue.  I found that it was actually being mounted that was causing the issue.  If the player is mounted when they approach the base, the scripts run and the speeches are given, but the log does not update and the player is given the error "You are mounted".
If player is not mounted, it works as expected

**Comment by Rushor** [comment]
updated and fixed once ptr is restarted. credit should also be given on mount then
