### ISSUE TITLE
[Quest] Salvaging Life's Strength

### ISSUE THREAD

**Issue by dominichello** [WoWManiaUK/Redemption#1942]
Seems the issue still persists same as [#1930](https://github.com/WoWManiaUK/Redemption/issues/1930)

Abandond quest before 2.1.4 was updated, re accepted quest, tried to complete. Still would not collect energy. Tried will all mods disabled, too no avail. 

"[Quest](http://www.wowhead.com/quest=12805/salvaging-lifes-strength) requires you to Kill Lifeblood elements, near the Sundered Shard.
Upon killing the elemental's you then need to use a Lifeblood gem to channel the corpses and collect their energy.

Once the channelling stops, nothing is registered to the quest / confirmation fails to happen."

**Comment by dominichello** [comment]
@fvicaria may i ask why this was closed when the bug still exists ? Unless i've missed something or my client failed to update, which i don't think it did. 
Was this not pushed too 2.1.4? Apologies in advanced if i am wrong.

**Comment by fvicaria** [comment]
The fix is being deployed this morning.

**Comment by dominichello** [comment]
@fvicaria thanks for the swift reply, i really appreciate it ! keep up the good work.
