### ISSUE TITLE
Foolish endeavors NPCs dissapearing right before killing Varidus

### ISSUE THREAD

**Issue by stealer0517** [WoWManiaUK/Redemption#1945]
http://www.wowhead.com/quest=11705/foolish-endeavors
When doing this quest the NPC walks down just fine and the talking works fine. But after you get out of the bubble trap you can't kill the boss, all the NPCs just despawn when the boss is at low health.
Also shadowstalker whatever doesn't ever do anything, and doesnt get out of the bubble at the same time you do. But shortly after he does that's when the NPCs despawn, so it may be related.

**Comment by fvicaria** [comment]
I have just done the quest and it worked fine. Maybe it got stuck for some reason or you did not do more than 50% of the damage.

![image](https://user-images.githubusercontent.com/9414661/33982608-04e40210-e0a9-11e7-9306-9e17a3a8749b.png)
