### ISSUE TITLE
[Raid]Ruby Sanctum Halion

### ISSUE THREAD

**Issue by CrustyMuffin** [WoWManiaUK/Redemption#1946]
When we fought against Halion (http://www.wowhead.com/npc=39863/halion#article) yesterday i´ve notice a number of bugs. 
The first one is just an optical bug but a bug nonetheless. The "Shadow Pulsars" (aka. Shadow Orbs) could be seen outside of a fight and even when Halion hadn´t spawned yet.
 The 2nd bug happened to us after the phase trasition at 75%. Players that went to the shadow realm could be seen in the physikal realm, but not all players could see them. Raid members got also affected by Halion abilities even though the were in the physikal realm. A similar thing happened in the 3rd phase, with then 2 dragons. People in physikal realm got killed by the "Twillight Cutter" from the shadow realm, which they couldn´t see. Players on both sides getting damage from both "Flame Breath" and "Dark Breath, other getting damage from the AoE they couldn´t see either etc.
I hope the informations given are enough to fix it. If you need more details, i´m willing to write a more detailed report.

**Comment by fvicaria** [comment]
YOU are supposed to be in both realm so that is not a bug.

**Comment by CrustyMuffin** [comment]
We were, that is the bug. We split our group like we should. We fought 2 bosses at the same time instaed of 2 "seperate" one.

**Comment by StefanelStan** [comment]
The key part of Halion encounter is as follows :
On phase 3, the boss is present on Phisical realm but also on shadow realm. On phisical realm he casts fire breath and meteor strike while on shadow realm he hascs shadow breath and twilight cutters.
These 2 realms are separate from eachothers like 2 different instances. The players/boss/skills from shadow realm should not be visible/present on fire realm and vice versa.
The bug described is that physical realm players/boss can interract with shadow realm and the other way around.
No work on RS in the last 3 months you say ?

**Comment by fvicaria** [comment]
This has been fixed and is only pending a test in Redemption now.

**Comment by StefanelStan** [comment]
I have spoken with other players from server and they said this bug was fixed like 3 months ago but the bug reappeared last week/this week.

**Comment by fvicaria** [comment]
Yes. There were some changes about a week or two ago.  We have reverted some code and add some other fixes. Should be good now.

**Comment by Hypobaricsole08** [comment]
IF you Tank Hallon in Physical realm you are not affected with the Twilight cutters or the boss but the dps and healers that havent moved to the Shadow realm yet are affected with both Shadow and Physical bosses mechanics the Twilight cutters are appearing in the Physical realm and i could see them running away from the cutters in Physical and hitting the boss while i (who was tanking the Physical realm) could see them running around the invisable boss (for me) with the cutters after their ass.
