### ISSUE TITLE
[NPC] Vyragosa - Pathing

### ISSUE THREAD

**Issue by ManiaLightmare** [WoWManiaUK/Redemption#1947]
[Vyragosa](http://www.wow-mania.com/armory/?npc=32630)

Vyragosa [path](https://ibb.co/fesdfR) sends him through the mountains.

Into the mountain at entrance to [Uldis ](http://wowwiki.wikia.com/wiki/Uldis) (south side of the temple of storms) and out the other side.
Through the mountain above [The Frigid Tomb](http://wowwiki.wikia.com/wiki/Frigid_Tomb) and out the other side.

**Comment by fvicaria** [comment]
Have you actually seen this happen or you are assuming from a 2d map?

**Comment by ManiaLightmare** [comment]
I was chasing her this morning for the kill and saw her do it twice.  That path "map" I made was just to show you where she was going.  

She's quite fast so it wasn't hard to confirm what I was seeing.

**Comment by fvicaria** [comment]
I could not see any of the coords going into the mount. Took me 1h checking them all.

**Comment by ManiaLightmare** [comment]
Odd.  In retail, she has 2 possible loops.  Not sure if that matters.  I wouldn't want to waste your time on something trivial like this.  Just wanted to mention it.  She has plenty of open space flight time for people to kill her.  Likewise, she moves pretty quickly so she's not missing inside either mountain she passes through for long.

**Comment by fvicaria** [comment]
I will make sure I did not miss anything but the loop should be a lot bigger than the one you drew anyways.

**Comment by ManiaLightmare** [comment]
That was my thought.  Perhaps she was missing the coordinates to make her fly further north before turning, so she cut the corners early.  Assuming it all works by following a path of coordinates x,y,z
