### ISSUE TITLE
[ITEM] Ephemeral Snowflake

### ISSUE THREAD

**Issue by Bartok14** [WoWManiaUK/Redemption#1948]
Ok so I know that this issue has been reported in the past and confirmed and it says on the ticket that this issue won't be fixed, however, there is no description as to why it won't be fixed. 

The trinket itself won't proc any noticeable mana regen, I have been checking on recount for some time and never see any mana regen from this trinket. On the other ticket they don't understand how this trinket it supposed to work. So the way it is supposed to work is that for every tick of a heal, whether it be judgement of light or a hot tick or a normal heal spell this trinket is supposed to restore 11 mana, However. what wasn't mentioned in the last ticket was that there is an internal global cooldown on this trinket of 0.33 seconds meaning that there is a maximum value of 165 MP5 from this trinket (11mana * 15 procs/5 seconds)

This trinket is amazing for Druids, Paladins and, Resto Shamans due to the fact that we always have a bunch of heals on the screen.  If you could please give this issue another look we would really appreciate it, Or if you are planning on closing this issue again, can you please give us a reason as to why it won't be fixed. Thank you.

**Comment by fvicaria** [comment]
I have found a few reports on the Blizzard site that the HoT never worked. I will keep looking but if that was the case we can't do anything about it.

**Comment by fvicaria** [comment]
I have an attempt hack-fix. Let's see if it works.

**Comment by Bartok14** [comment]
Really? cause on wowhead there are people that have data showing it proccing when it was suppossed to so I'm not sure how it wouldn't have been working on retail. Has this trinket been fixed with your hack? I was thinking that You could also just make the MP5 static so thats it's not reliant on the heal ticks for it to generate the 11 mana you could maybe program it to give 11 mana every 0.33 seconds like it was supposed to do. Or program it to give the average MP% that people on retail saw which was about 125 MP5.

**Comment by fvicaria** [comment]
Works.
![image](https://user-images.githubusercontent.com/9414661/34104126-2c9fdacc-e3e7-11e7-80db-1a6a865623e2.png)

**Comment by VA-L** [comment]
- It's now working. 
![image](https://user-images.githubusercontent.com/11377592/34109345-8922fb0a-e403-11e7-8699-0be13c8e31a6.png)

Up to test !

**Comment by Bartok14** [comment]
This is still not working on server as it is supposed to, can you please use a paladin and judge of light a target while having 10 people attacking it, if you aren't seeing this proc every .33 seconds it's not working correctly
