### ISSUE TITLE
"I Disenchanted my Enchanting Skill!" - Profession Booster Bug.

### ISSUE THREAD

**Issue by Warlloxx** [WoWManiaUK/Redemption#1949]
I lost my ability to enchant. Here is what happened:
1. I removed my enchanting skill.
2. I removed my Tailoring skill.
3. I purchased 600MP from the site.
4. I purchased Enchanting skill from the profession booster 
5. My Enchanting Skill was maxed, however, the ability disappeared from my spellbook.
6. Disenchanting still exists, and also still works.

After all of this, I also attempted to purchase Engineering. This, also, did not appear.
![wowscrnshot_121417_234424](https://user-images.githubusercontent.com/28966686/34019893-f0f6bf92-e128-11e7-9a34-c4317cd3c9e8.jpg)

NB: 
I have tried regular re-logging.
I have tried logging off, deleting cache and logging back in using WoWMania Launcher. 
![wowscrnshot_121417_233322](https://user-images.githubusercontent.com/28966686/34019503-3367567c-e127-11e7-9fb7-ef36fa770f8a.jpg)

**Comment by Plege** [comment]
Pretty sure you need to go to an enchanting trainer and buy some spells so they will appear in your spellbook

**Comment by Warlloxx** [comment]
I have just taken your advice, and it did not appear to work. 
![wowscrnshot_121417_234905](https://user-images.githubusercontent.com/28966686/34019971-638af122-e129-11e7-9e53-d0d6b4e14d10.jpg)

**Comment by fvicaria** [comment]
The boost is to BOOST the skill not create it. You first need to have enchanting and then boost it.
You will need to open a ticket to fix it

**Comment by Warlloxx** [comment]
I had the skills when I first tried to use the boost. But it just said "You already known two professions", or something similar to that. So, what can I do now?
