### ISSUE TITLE
[Item] Crashin' Thrashin' Racer

### ISSUE THREAD

**Issue by hotdoggidy** [WoWManiaUK/Redemption#1952]
item=54343

Using the remote grants the player control over a small crasher they can use to race other players and crash into them.

Currently on redemption the racers do not actually collide. Instead, they pass through each other at any angle with no contact.

This makes the item a bit less fun but also removes any chance of players achieving "Crashin' & Thrashin'" (achievement=1295) during Winter Veil world event.

**Comment by fvicaria** [comment]
Can you try this in Dev please.

**Comment by hotdoggidy** [comment]
sure thing

**Comment by hotdoggidy** [comment]
nevermind, i dont have any characters on Dev anymore.

**Comment by squalllh1989** [comment]
sorry i wanna test this out but it kinda too late today for me, so i will have to get some sleep first :D

**Comment by squalllh1989** [comment]
Tested and working in dev, gonna try on redemtion now

**Comment by squalllh1989** [comment]
Nah, the racing slam spell didn't work on redemtion, so, not yet

**Comment by fvicaria** [comment]
Not on redemption yet. :)
