### ISSUE TITLE
Fa-la-la-la-Ogri'la

### ISSUE THREAD

**Issue by Momomarie** [WoWManiaUK/Redemption#1953]
I completed this but it did not give me the achievement.  I turned my mount into a reindeer and completed the Bomb Them Again! quest.

**Comment by squalllh1989** [comment]
This is working, i just did this 30 sec ago before i go to sleep at redemtion
![wowscrnshot_121617_045136](https://user-images.githubusercontent.com/27235989/34061981-fb855ffa-e21c-11e7-8fc9-b7efd4135eaf.jpg)

**Comment by squalllh1989** [comment]
To make sure that you will get the achivement, you should make sure that you still having the "Flying reindeer" buff (which i marked in the picture below). If you didn't have it, remove the festival buff and reuse your event item.
![4](https://user-images.githubusercontent.com/27235989/34063386-528fc1a8-e224-11e7-8714-7c4999544fd2.png)
