### ISSUE TITLE
[Transmog] Fist weapon

### ISSUE THREAD

**Issue by Bartok14** [WoWManiaUK/Redemption#1956]
The item Fist of Molten Fury does not show up in the transmog menu. Also I know regular weapons get sheathed when you canst spells, but it seems my fist transmog of the main hand weapon disappears completely. Was wondering if this is supposed to be the case or if there is a workaround cause it kind of sucks we can transmog first weapons onto our main hand and shields as a paladin but as soon as we cast a spell they disappear entirely.

**Comment by fvicaria** [comment]
There is no way to change the way the weapon looks since they may require animation that WotLK client does not have. I will check the first issue if you send me the item you are trying to transmog.  They may be incompatible.

**Comment by Bartok14** [comment]
I'm trying to transmog Bulwark of Smouldering Steel to look like First of Molten Fury

**Comment by squalllh1989** [comment]
I don't really know requirement and condition of transmog, but based on test,  [Fist of Molten Fury](http://www.wow-mania.com/armory/?item=32945) only show up in the list if you attempt to transmog another fist weapon to look like it (in my test, i used [Keleseth's Seducer](http://www.wow-mania.com/armory/?item=50710) and it work) and won't show up if you try to transmog a shield to look like it. The same case happen when trying to transmog item to look like [Claw of Molten Fury](Claw of Molten Fury), it will only show up in the list if you are trying to transmog a main hand fist weapon, like [Black Bruise](http://www.wow-mania.com/armory/?item=50692).

**Comment by Bartok14** [comment]
Is this the way its supposed to work cause I see some people that xmog their shoulders to look like an axe so I thought you were supposed to transmog whatever item you wanted essentially.
