### ISSUE TITLE
[Npc] Witch Doctor Unbagwa

### ISSUE THREAD

**Issue by GMWeeble** [WoWManiaUK/Redemption#1957]
This is the quest NPC for " http://www.wow-mania.com/armory/?quest=348 " When someone completes the quest the quest npc " http://www.wow-mania.com/armory/?npc=1449 " Gets stuck in the current state "Summoning the quest NPC's" And will not allow any other players to start the summoning again. Killing and respawning the NPC fixes it but if there is any permanent fix that would be great.

**Comment by squalllh1989** [comment]
NPC is good, i tested in dev with 2 char, after i got 1 char completed the quest, i come to the npc with the quest again, with the item need for summon it, and he still summon the gorilla needed like normal.
First picture: completed quest with 1st char (summoned gorillas, killed all 3 of them, looted quest item from the 3rd gorilla)
![wowscrnshot_121717_081506](https://user-images.githubusercontent.com/27235989/34075750-0d578640-e303-11e7-841e-65effd26d409.jpg)
After that: come with the quest on 2nd char, and still be able to summon the gorillas normally, there is no "stuck" on the npc's state:
![wowscrnshot_121717_081712](https://user-images.githubusercontent.com/27235989/34075763-4c392986-e303-11e7-959c-bfa19ca45fdc.jpg)
![wowscrnshot_121717_081718](https://user-images.githubusercontent.com/27235989/34075764-4dd4a464-e303-11e7-9787-87166b08621b.jpg)
![wowscrnshot_121717_081748](https://user-images.githubusercontent.com/27235989/34075765-4f1afab2-e303-11e7-85a4-d95e540e5611.jpg)

**Comment by squalllh1989** [comment]
If you still insis that the npc is bugged, please provide more information about how the npc got stuck, because i can't reproduce the bug with the information you provide.

**Comment by GMWeeble** [comment]
https://gyazo.com/a6961d5b5dbda43392566201e171d538

The npc I made a new char gave the quest and leveld up. So unless there are some quests before I NEED to do. Same issue other players has.

**Comment by squalllh1989** [comment]
maybe it happen in redemtion 2 days ago, but not in dev. Did you test it on redemtion ? Because i test it out in dev and have no problem at all.

**Comment by GMWeeble** [comment]
Test it on Red. The issue is on there with the players.

**Comment by VA-L** [comment]
@GMWeeble , you should test it by yourself on dev and give us your feedback.

**Comment by fvicaria** [comment]
The only way for the NPC to get stuck is if player DCs or die maybe.
I tried many times and if done correctly it just works.

**Comment by GMWeeble** [comment]
Then the issue must only be bugged on red with players interacting with it. 
" https://gyazo.com/afbd3629f4c1ea11af07d5cee595c3cf " After I added the quest and reloged.

**Comment by GMWeeble** [comment]
And again after I killed and respawned him for a player
" https://gyazo.com/6f39111ba718e6a67d0bb9381717d4e6 "

**Comment by VA-L** [comment]
It was indeed bugged.

- NPC now despawns correctly.

**Comment by fvicaria** [comment]
There was nothing to fix here.
