### ISSUE TITLE
[QUEST] The Storm King's Vengeance

### ISSUE THREAD

**Issue by dominichello** [WoWManiaUK/Redemption#1958]
I've seen that this quest has been reported a couple of times, and someone did report a similar [problem](https://github.com/WoWManiaUK/Redemption/issues/1758)

When Mounted his grab skill picks up a target, But then while slamming it to the ground with Button 4, killing the enemies with an AOE blast, but the kills are not accredited to the quest kills. 

This subsequently makes the quest take for ever, as you have to kill all 100 mobs 1 by 1, gave up after 10 or so.

**Comment by squalllh1989** [comment]
Confirmed, quest [The Storm King's Vengeance](http://www.wow-mania.com/armory/?quest=12919), vehice [Gymer](http://www.wow-mania.com/armory/?npc=29884#controlled-abilities) have 4th ablity [Gymer's Throw](http://www.wow-mania.com/armory/?spell=55421) designed to clear the undead horde arround, has massive damage and large aoe, but currently those which killed on this ablity does not count toward the quest's objective, force user to use 1st ablity,[ Gymer's Smash](http://www.wow-mania.com/armory/?spell=55426) to kill mob one by one, which is really slow (it took 3-4 smash for normal mob to kill one)

**Comment by GMWeeble** [comment]
Also when doing this quest I am not sure how it happens but you get stuck with the Gymer's buff making you stuck in phase with no NPC

**Comment by dominichello** [comment]
My party member also experienced the phase bug. As we were doing it at the same time.

**Comment by mpayton87** [comment]
Im currently having the same problem, the buff wont go away and now NPCs are not loading properly
