### ISSUE TITLE
Quest: Filling the Cages

### ISSUE THREAD

**Issue by Blasphemiah** [WoWManiaUK/Redemption#1959]
Budd's Tag Troll skill doesn't work, so the quest can't be completed. When you press the skill button, the NPC does a grunt noise but doesnt move or responds to the order.

**Comment by fvicaria** [comment]
Works, I have posted screenshots many times.

**Comment by IvanLlanas** [comment]
Sorry, it may work for you but not for me, and others as I can read.
I've already seen your successful screenshots, ok, that means it may work in some cases, but, for me, Budd only does ok "Stay" and "Follow", it does not "Attack" nor "Tag Troll", he just does "Huh!".
One detail: once you tell him to "Attack" the Attack button stays flashing forever.
