### ISSUE TITLE
Cold Weather Flying missing at Wind Rider Sabamba in Borean Tundra

### ISSUE THREAD

**Issue by kolci** [WoWManiaUK/Redemption#1960]
[Wind Rider Sabamba](http://www.wowhead.com/npc=35135/wind-rider-sabamba) in Borean Tundra is supposed to train [Cold Weather Flying](http://wowwiki.wikia.com/wiki/Cold_Weather_Flying). I can only train the [Artisan Riding](http://www.wowhead.com/spell=34091/artisan-riding) from this NPC.

**Comment by fvicaria** [comment]
Not on 3.3.5a

**Comment by kolci** [comment]
Strange. Then the automatic letter players get in northrend is not teling the truth.
![flyingnt_copy](https://user-images.githubusercontent.com/27676282/34363124-a5f2655a-ea79-11e7-8a4c-9927b9933deb.jpg)

**Comment by fvicaria** [comment]
I will recheck. Thanks for that

**Comment by Silver894** [comment]
Hello. I wanted to point the same thing, but from Alliance side. Our flight trainer is Maigra Keenfeather.
The letter she sends also points at that she suppose to teach Cold Weather Flight as well.

![FLIGHT](https://user-images.githubusercontent.com/73012328/96329771-019ef980-1061-11eb-9213-21ffb42aa972.png)

GM told me to put this here and ask you you need me to open a "new issue".
