### ISSUE TITLE
Quest info missing from mobs' tooltips

### ISSUE THREAD

**Issue by Qbix-xx** [WoWManiaUK/Redemption#1961]
I'm having an issue with tooltips that appear when you put mouse cursor over a monster. 

It should contain quest name and progress when you have a quest related to that monster but in 90% cases it doesn't. I've heard that I'm not the only one who has this issue. It's not a problem with addons (I checked), game itself should be showing that but it's not. It's not a major issue but (for me) it's super annoying during leveling process.

No idea what's causing the problem so I'm posting it here. Here's screenshot of what I mean:

![obraz](https://user-images.githubusercontent.com/4621780/34082751-759fddcc-e364-11e7-9bbf-25595c984cdf.png)

**Comment by fvicaria** [comment]
Interface issue. Reset your client.
