### ISSUE TITLE
[Loot] Blood-Queen Lana'thel

### ISSUE THREAD

**Issue by GMWeeble** [WoWManiaUK/Redemption#1962]
Killing the boss while it is in the air makes the boss unlootable.
Loot icon is there but rightclicking doest not make any loot appear.

**Comment by VA-L** [comment]
I'm on it.

**Comment by VA-L** [comment]
- Added a security that prevents the blood queen from dying in the air.

Up to test.

**Comment by fvicaria** [comment]
Deployed to Red.
