### ISSUE TITLE
[Quest] Fools Endeavor (ID: 11705)

### ISSUE THREAD

**Issue by Whurdabeef** [WoWManiaUK/Redemption#1966]
At the end of the fight with Varidus The Flenser after defeating him all 3 npcs disappear and quest does not proceed. Hav tried abandoning the quest and restarting it, have tried relogging and reloading. Wrote ticket on it first time, GM Saintz reset it and had me try again to no avail.

**Comment by fvicaria** [comment]
I have tried this and it worked fine. Are you doing more than 50% of the damage?

**Comment by Whurdabeef** [comment]
Yes I am. But as soon as I defeat, all 3 NPCs disappear and the quest does
not complete. Have tried it three times with the same result. Currently
have a ticket in for it again but have been waiting for about an hour and a
half for a ticket response.

**Comment by fvicaria** [comment]
I have just done the quest again and it worked. Ignore the ads and go for Varidus only.
