### ISSUE TITLE
[QUEST] Gluttonous Lurkers

### ISSUE THREAD

**Issue by dominichello** [WoWManiaUK/Redemption#1967]
[Quest ID 12527](http://www.wowhead.com/quest=12527/gluttonous-lurkers)

Collect the rats, Feed to Basilisk. Feed 5 to engorge, then harvest Basilisk too collect crystals. 

All works fine, apart from random a quirk, mounting (only tested with flying mount) then collecting the rats, caused " you are mounted" to appear in red, but still collected the rat. However it did not de-spawn, i could the spam click the same rat to collect lots very quickly.  Useful..but not intended.

**Comment by VA-L** [comment]
- The rats now despawn even if collected when mounted (whether it's in the air or not).

Up to test.
