### ISSUE TITLE
[Quest] The Relic's Emanation

### ISSUE THREAD

**Issue by Noahcoke** [WoWManiaUK/Redemption#1968]
Hello,

this quest is one of the many dailies you can do to earn reputation for the Ogri'la faction. (http://www.wowhead.com/quest=11080/the-relics-emanation)

You are supposed to memorize a certain pattern of colors and imitate it. It worked for the last week or so but today it did not anymore.
 It works like that: 
It shows you the pattern of the colors afteward you have to rightclick the same colors in the right order. (Each round one more color to memorize)

The issue: When it is up to you to click the certain color you can click but nothing happens. You can see that here: https://gyazo.com/be661d24f9c9dbb5ec29926707b9dff0

Sincerely,
Noah

**Comment by fvicaria** [comment]
Reverted breaking code.
