### ISSUE TITLE
[Quest] The Relic's Emanation

### ISSUE THREAD

**Issue by GmIchigo** [WoWManiaUK/Redemption#197]
http://www.wow-mania.com/armory?quest=11080.In this quest your are suppose to Gain Apexis emanations from an Apexis Relic But no matter what you do you can not obtain it.

**Comment by ThaydeGM** [comment]
I can confirm that this quest is not functioning properly. The player is unable to gain the emanations from http://www.wow-mania.com/armory/?object=185890.
