### ISSUE TITLE
[Quest] The Spider God

### ISSUE THREAD

**Issue by Vildhjarta** [WoWManiaUK/Redemption#1972]
For this quest you must enter the dungeon Zul Farrak and around the boss Theka the Martyr is a Tablet of Theka, upon reading said tablet, a continue or second page option should be available with the Spider God's name being on the second but alas only the first page can be accessed, please help.

**Comment by fvicaria** [comment]
Reverted breaking code.

**Comment by Vildhjarta** [comment]
Sorry what do you mean by reverted breaking code?

**Comment by Vildhjarta** [comment]
Is that better?
