### ISSUE TITLE
[Spell] Apexis Vibrations/Emanations/Enlightenment

### ISSUE THREAD

**Issue by goldstinger** [WoWManiaUK/Redemption#1974]
This is a bug regarding the spells "Apexis Emanations" (http://www.wow-mania.com/armory/?spell=40625), "Apexis Enlightenment" (http://www.wow-mania.com/armory/?spell=40626), and "Apexis Vibrations" (http://www.wow-mania.com/armory/?spell=40623).

These spells are obtained as buffs during the quests "An Apexis Relic" (http://www.wow-mania.com/armory/?quest=11058), and "The Relic's Emancipation" (http://www.wow-mania.com/armory/?quest=11080), as quest goals, although players can obtain these buffs outside of the quests, and are encouraged through quest dialogue to do so outside of the quests.

The quest is normally done at 32,63 in Blade's Edge Mountains, and requires you to play a makeshift game of "Simon Says" with some crystals. You have to right click the "Apexis Relic" game object while you have an "Apexis Shard" (http://www.wow-mania.com/armory/?item=32569) in your inventory. Once done, it starts up a game of Simon Says with 4 nearby game objects named "Red Cluster", "Green Cluster", "Blue Cluster" and "Yellow Cluster". The Apexis Relic zaps the clusters in order, and you have to repeat the order done by the Apexis Relic by right clicking on the correct clusters. After a bit of back and forth, you get the above buffs, Apexis Vibrations, Apexis Emanations, and Apexis Enlightenment from doing well at the minigame.

The issue happens when a player has one or more of these buffs. Each buff increases movement speed by 15%, but it's only supposed to be active within Blade's Edge Mountains. For me, I used WoW-Mania's Mall Teleport Stone (http://www.wow-mania.com/armory/?item=90044) to get to the mall and to Shattrah, but the buffs stayed on me. Using a hearthstone to get to Dalaran also kept the buffs on me.

When I noticed the issue, I tried removing the buffs by right clicking on them, but the effects of the buffs stayed on my character. I tried relogging and also exiting the game client and restarting it, but the effects persisted. This happens the exact same way, both inside and outside of Blade's Edge Mountains.

Tried opening a ticket which was answered by Saintz, and reproduced the entire Simon Says game and showed myself removing the buffs, but the effects of the buffs continued to exist, despite removing them. A GM had to manually remove the buff effects both times. Was done as a level 80 Goblin Hunter, it was brought up that it might have to do with being a Goblin.

**Comment by VA-L** [comment]
- Made a security that prevents players to keep those buffs outside of the Blade's Edge Mountains.

Up to test.

**Comment by fvicaria** [comment]
Can someone confirm this one? It was working last week. I reverted the changes that could potentially have caused it.

**Comment by fvicaria** [comment]
Fixed on the dev.
Including speed buff is now removed after you leave the area.

**Comment by squalllh1989** [comment]
Confirmed, the buff is now auto removed when you leave blade's edge mountain.
