### ISSUE TITLE
[Quest] A time worn coffer

### ISSUE THREAD

**Issue by dominichello** [WoWManiaUK/Redemption#1976]
[Quest ID 12691](http://www.wowhead.com/quest=12691/a-timeworn-coffer)

Farmed Sholazar Guardians in Maker's Overlook for at least 5 days in a row.
Quest item [Huge Stone Key](http://www.wowhead.com/item=39227/huge-stone-key), has never dropped.

Not sure if bugged or extremely unlucky.

**Comment by dominichello** [comment]
*update* literally as submitted killed the next mob..it dropped. Sorry for wasting time... God dam game :)

**Comment by VA-L** [comment]
Nothing wrong with it, 10% chance of loot.
