### ISSUE TITLE
[Quest] The Spider God

### ISSUE THREAD

**Issue by Vildhjarta** [WoWManiaUK/Redemption#1977]
For this quest (http://www.wowhead.com/quest=2936/the-spider-god) you must enter the dungeon Zul Farrak (http://www.wowhead.com/zulfarrak) and around the boss Theka the Martyr (http://www.wowhead.com/npc=7272/theka-the-martyr) a Tablet of Theka (http://www.wowhead.com/object=142715/tablet-of-theka) can be found. Upon reading said tablet, a continue or second page option should be available with the Spider God's name being on the second but alas only the first page can be accessed, please help.

Also would like to add that without the quest the second page should not be available anyways but with the quest it should be, and I have the quest but still nothing.

**Comment by fvicaria** [comment]
I don't understand what is the issue here.
It works as it should

![image](https://user-images.githubusercontent.com/9414661/34228673-5ef699b4-e5c9-11e7-9dd7-07fb716f75c4.png)

**Comment by Vildhjarta** [comment]
I don't get the completed part. If it worked the way it should. I wouldn't be here. I'll try dropping the quest and trying again.

**Comment by Vildhjarta** [comment]
Ok so it worked after dropping the quest and trying again. Also I used a flying mount inside the dungeon on the first time and it may have bugged it or something. I didn't use a flying mount the second time and it worked fine just like your screenshot. Sorry for the inconvenience.
