### ISSUE TITLE
[Boss]Mage-Lord Urom (The Oculus)

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#1980]
Hello,

Inside The Oculus dungeon (http://www.wowhead.com/the-oculus), the 3rd boss is Mage-Lord Urom (http://www.wowhead.com/npc=27655).
He is glitched in the way that when he teleports to the center of the spiral thing to do his AOE (empowered arcane explosion, http://www.wowhead.com/spell=51110) he evades , drops aggro and resets to full health. This almost always happens, sometimes already during his cast, sometimes only after the AOE hits.
On top of that, if you manage to kill him while he's still casting the explosion, he dies floating in the center and cannot be looted. So you would kind of prefer leaving him on low health and waiting for him to come back, but then he evades and resets instead. So far I only managed to do this boss with bursting him down before the explosion, or giving up on loot and killing him in the center while he casts.

**Comment by Dranah** [comment]
oh and I forgot , this is the teleport spell he uses http://www.wowhead.com/spell=51112/teleport

**Comment by VA-L** [comment]
I wanted to only fix the issues described here but i went for an almost full rework.

- Prevent players from attacking Mage-Lord-Urom during the first 3 platforms.
- No more drops of aggro.
- Mage-Lord-Urom can't die during his air phase (He will stay at 1hp if he should have died).
- Correctly timed the alerts messages.
- Mage-Lord Urom will now stay in the air correctly when teleporting to the center.

Up top test.

**Comment by squalllh1989** [comment]
everything above work perfectly, but there is still a problem: i stuck in combat in the encounter with Mage-Lord-Urom even after he teleport from 1 platform to another (No more drops of aggro, 2nd fix above i think), this is giving me trouble that i can't use the Essence to call the drake and get to him to continue the fight (i have to enable gm fly mode to get to him to continue the test) so basicly player will just stuck here.

**Comment by VA-L** [comment]
Oh, my bad.
Should be good now.

Up to test.

**Comment by VA-L** [comment]
Should be good now.

Up to test.

**Comment by VA-L** [comment]
Added some more securities : 

- If **Mage Lord Urom** evades during the first platforms phase, he will now despawn and respawn at the first one.
- If **Mage Lord Urom** evades on the last platform (the center one), he will also despawn and respawn at the first one (that is to prevent any shortcuts with the boss evading and skipping phases).
- The combat should also drop when he teleports to another platform.

Up to test.

**Comment by nimavf** [comment]
![wowscrnshot_122417_215156](https://user-images.githubusercontent.com/14857593/34328465-c329980e-e8f4-11e7-9e93-e42a404cfe8a.jpg)

![wowscrnshot_122417_220734](https://user-images.githubusercontent.com/14857593/34328560-dc3e45ae-e8f6-11e7-846d-3a54b5eb4f2f.jpg)

**Mage Lord Urom** Resets to full HP after teleport.
The combat doesn't get cleared when he teleports to another platform.

**Comment by VA-L** [comment]
> Mage Lord Urom Resets to full HP after teleport.

That's normal.

**Comment by squalllh1989** [comment]
Confirmed, Mage-Lord Urom is now working all good, the combat drop when he teleport to other platform, allow you to call your drake again now
