### ISSUE TITLE
[Quest] Spirit Totem

### ISSUE THREAD

**Issue by wrthigpen** [WoWManiaUK/Redemption#1982]
Loot drop rate and item drop rate really bad.  Up to 30% of all bears killed dropped nothing at all and about 7% of spiders killed dropped nothing.  On Blizzard's servers, this quest can be completed by killing any spider and any bear in Western Plague Lands.  I have killed over 90% of all bears, spiders, and all the birds of prey and have only gotten 4 spider eyes and 4 black claws.  Starting on 2nd round of killing bears, spiders, and birds of prey, I have gotten only 2 more thick black claws and no more eyes.  Please look into the drop rates for this and all quests.

**Comment by fvicaria** [comment]
Please follow the procedure described below before creating a new issue:
[How to Properly Report an Issue](https://github.com/wow-mania/Redemption/wiki/How-to-Properly-Report-an-Issue)

This will help developers identify and fix the issue quicker. Incorrectly or unclear reports will simply be deleted.

**Comment by fvicaria** [comment]
Some of the creatures will have only a 2% chance so unless you link me the exact creature you are killing I will close this one "as is".

**Comment by VA-L** [comment]
http://www.wowhead.com/quest=8412/deprecated-spirit-totem#comments

Retail players have also complained about this quest, the drop rate is fine as it is then.
