### ISSUE TITLE
[Object] Nethercite Deposit

### ISSUE THREAD

**Issue by Wolch** [WoWManiaUK/Redemption#1983]
http://www.wowhead.com/object=185877/nethercite-deposit
The ammount of ore is too low, one deposit should give 2-4 orse while now it gives only 1 most ofthe time.
The number of nodes is also very small, there should be much more of them. I've been trying to farm it for the quest for 2 hours now, and I still don't have the necessary amount (34/40).

**Comment by nimavf** [comment]
Nethercite Deposites not clickable with GM-Off.

**Comment by fvicaria** [comment]
you char may be messed up :)

**Comment by fvicaria** [comment]
This is fixed. Your problem is the char.

**Comment by squalllh1989** [comment]
Tested and it work normally. Please make sure that you full filled your condition to mine the ore: "Players who have not completed the quest Neutral 15 [70] Blood Oath of the Netherwing or are not currently disguised as a Dragonmaw fel orc may not collect Nethercite Ore from Nethercite Deposits. It requires a mining skill of 350 to obtain the quest, and to mine Nethercite Veins." ([from wowwiki](http://wowwiki.wikia.com/wiki/Nethercite_Deposit))
