### ISSUE TITLE
[Quests] The Dragonmaw Races Quest Chain

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#1984]
Hello,

This evening, I've spent some time working on my Netherdrake reputation and I came across this unique and interesting quest line that is the Dragonmaw Races. After getting a hang on the concept, I managed to win the first race (1) and got a message from the opponent racer saying: 'Pumpkins? Oh how the mighty have fallen... I am certain the other riders will prove to be much more challenging.' (1). Proud of myself, I expected the quest to be completed, but oddly enough, I didn't get credit for it... I thought I might have made a mistake during the race and tried to follow him closer and finish ahead of him. Second win gave me the credit, but I don't think it's due to these changes, since I got the exact same message (1). Getting the credit seemed to be a matter of luck... Strange.

Not too bothered about it, I continued on with the chain, managing to win the second one (2) and got the credit. That proved that the way I've been doing the races was correct. On trying the third race (3), the same not-getting-the-credit-bug happened, but I retried once more and managed to get my credit. Fourth race (4) worked correctly (maybe I was lucky to get my credit on the first try though...).

When the issue became more problematic is when I won the fifth race (5). Once again, no credit... I thought I would only have to try again to get the credit, as I did with races 1 and 3, but a second win didn't make it. So I tried again, and again. And after my fourth time getting the message: 'Well it looks like it's just you and the captain now, grunt. Good luck! You're gonna need it!' (5), I decided to make an in-game ticket. considering the ~5 minutes of somewhat exhausting concentration required to win the race + the 5-10 minutes needed for the NPC to respawn so that I can try again. 

The WoW-Mania GM 'Saintz' then answered my ticket and investigated the issue with me. After a few questions, he asked me to do the race again (5). After having him watch me during the whole race, and once again winning against Wing Commander Mulverick, I still didn't get the credit. However, Saintz, having observed all of this, thought I should have indeed got the credit for the performance I gave. After having verified that I am using the WoW-Mania Launcher and Client, he kindly gave me the credit for the quest. He then said that if the 6th race (6) didn't work, I should abandon the quest, logout, clear my cache through the WoW-Mania Launcher and retry the quest. 

Not too surprisingly, after having won the 6th race (6), I did not properly get credit for it. I then abandoned the quest, logged out, cleared cache, as told by Saintz, and tried again. I managed to win again, but still didn't get the credit. Not eager to retry pointlessly over and over, I made another ticket requesting to talk with Saintz again. He then examined the issue once more, now fully aware of the situtation, and gave me the credit for the quest, as it could not be completed normally.

After these exchanges with Saintz, he asked me to make a ticket here, which is why I created this. If you need anymore information on the situation (e.g.: PC specs, etc.) I'll gladly provide it. Sorry if this post was a bit too lengthy... :P

Thank you for reading this and working towards making the WoW-Mania server a better place!

Kindly,
Oganku

Referenced links
1. http://www.wowhead.com/quest=11064/dragonmaw-race-the-ballad-of-oldie-mcold
2. http://www.wowhead.com/quest=11067/dragonmaw-race-trope-the-filth-belcher
3. http://www.wowhead.com/quest=11068/dragonmaw-race-corlok-the-vet
4. http://www.wowhead.com/quest=11069/dragonmaw-race-wing-commander-ichman
5.  http://www.wowhead.com/quest=11070/dragonmaw-race-wing-commander-mulverick
6. http://www.wowhead.com/quest=11071/dragonmaw-race-captain-skyshatter

**Comment by VA-L** [comment]
Alright, seems like all the races have the same problem. I'll look at it closely.
Thank you for reporting :)

**Comment by VA-L** [comment]
No credit was given for each quest on the end, indeed.

**All of those quests are now fixed.**

Up to test !

**Comment by squalllh1989** [comment]
[This quest](http://www.wowhead.com/quest=11064/dragonmaw-race-the-ballad-of-oldie-mcold)
is seem a little buggy to me, i keep getting knock off from my mount randomly while follow [Murg "Oldie" Muckjaw](http://www.wowhead.com/npc=23340/murg-oldie-muckjaw), and my quest failed, but after a few retry, i suddenly got a "quest completed" when i was about to start, with Murg "Oldie" Muckjaw is dead, only his mount walk from the start, and another mount is returning, well kind of confuse to me.

**Comment by squalllh1989** [comment]
[Dragonmaw Race: Trope the Filth-Belcher](http://www.wowhead.com/quest=11067/dragonmaw-race-trope-the-filth-belcher) work good

**Comment by squalllh1989** [comment]
[Dragonmaw Race: Corlok the Vet](http://www.wowhead.com/quest=11068/dragonmaw-race-corlok-the-vet#comments) work good

**Comment by squalllh1989** [comment]
Sorry i'm a noob, can some one test from the 4th to the 6th race please, i can't pass the 4th :v
