### ISSUE TITLE
[Faction] Oracle/Frenzyheart Switch

### ISSUE THREAD

**Issue by Noahcoke** [WoWManiaUK/Redemption#1985]
As seen in the title this is about the two factions you can find in Sholazar Basin. After doing some quests you can choose for which of these two factions you want to farm reputation/do dailies. There will be a beginning questchain you have to complete before unlocking those dailies. 

After having completed the questchain you have the option to switch the factions. (The other one will turn automatically to hated). 

If you want to switch you have to kill a certain NPC called Artruis the Heartless (www.wowhead.com/npc=28659). Next to him are two npcs, one of the Oracle Faction and one being part of the Frenzyhearts. (It should look like this https://gyazo.com/07fc8302db41e93af844e9a6e9124119) 

If he reaches 30% the two npcs will unfreeze and you have to kill the one that you dont want to do dailies anymore for. (Kill oracle guy to switch back to frenzyheart, vise versa.) 

After killing one of the npcs, you can kill Atruis. The remaining npc will offer you a quest now. (Looks like this: https://gyazo.com/54d91a9bd6e1d003e07168232cfe570f) 

This is where the issue starts: When you talk to the npc to accept the quest, there is no quest to take. (https://gyazo.com/3f981d53427229992d19cfb53fd6e751) 

http://www.wowhead.com/forums&topic=72652/how-to-switch-from-frenzyheart-tribe-to-the-oracles This forum link suggests this as the only option to switch. Therefore it isnt possible at the moment. 
Smth to add: The third comment here also states that the "!" should be blue, even tho as seen in the screenshot it is yellow. Indicating the switch should only be possible once a day. Even after waiting for the daily reset, it did not work yet. 

Sincerely,
Noah

**Comment by fvicaria** [comment]
What is the NPC and the ques that it should offer? I got confused.

**Comment by Noahcoke** [comment]
Ye i forgot to mention that sorry. 
Npc: http://www.wowhead.com/npc=28668/zepik-the-gorloc-hunter
Quest: http://www.wowhead.com/quest=12582/frenzyheart-champion

**Comment by dominichello** [comment]
Did this Quest line no problems a few weeks back, currently farming oracle rep. 
But something could have broken since then.

**Comment by VA-L** [comment]
> Did this Quest line no problems a few weeks back, currently farming oracle rep.
But something could have broken since then.

It's not about the quest line itself, it's about switching to ther other faction when you're already in one of them.

**Comment by squalllh1989** [comment]
I did this before. Maybe your problem come from here: You must finish all the quest line that introduce those two faction before you can actually use that quest to chose the side you want (and the first time you finish it, it will be this quest at the end, which give you the chance to chose your side before you actually start your grinding). Many people didn't know this and just wanna chose the side they want in the midle of the quest line, that won't work. The quest line will start with the frenzyheart, then swap you to the oracle when you are honored to frenzyheart, just to introduce you to those two faction. I already write a long and detail guide about this to reply some one confused before. You can read it [here](https://github.com/WoWManiaUK/Redemption/issues/1812)

**Comment by squalllh1989** [comment]
I will repeat it here in case some one wanna do the chain also:
The quest chain for rep with the 2 faction in Sholazar Basin, the frenzy heart and the oracle, work fine, i have done it with my mage (my main char, the only char that i care about rep), here is what you should do to make it work: 
- Go to [Tamara Wobblesprocket](http://www.wow-mania.com/armory/?npc=28568) and get the quest [The Part-time Hunter](http://www.wow-mania.com/armory/?quest=12654), go kill [Pitch](http://www.wow-mania.com/armory/?npc=28097) and loot his remain, after you do that, you will see a frenzyheart that stand near it give out the start of their rep chain, [Playing Along](http://www.wow-mania.com/armory/?quest=12528)
- Do your chain, in these chain, you will be introduce with both faction, first you will get frenzyheart rep, then your rep will switch to the oracle, don't worry if you wanna get frenzyheart rep, those step are a must, YOU MUST DO THE WHOLE CHAIN BEFORE ACTUALLY CAN CHOSE ONE FACTION YOU LIKE AND FOCUS ON GET THEIR REP. Just keep do the chain until it leed you to the quest.
This is how the chain look like:
+) Once you kill Pitch, the frenzyheart part of the chain start:
[Playing Along](http://www.wow-mania.com/armory/?quest=12528)
[The Ape Hunter's Slave](http://www.wow-mania.com/armory/?quest=12529)
[Tormenting the Softknuckles](http://www.wow-mania.com/armory/?quest=12530)
[Wasp Hunter's Apprentice](http://www.wow-mania.com/armory/?quest=12533)
[The Sapphire Queen](http://www.wow-mania.com/armory/?quest=12534)
[Flown the Coop](http://www.wow-mania.com/armory/?quest=12532)
[The Underground Menace](http://www.wow-mania.com/armory/?quest=12531)
[Mischief in the Making](http://www.wow-mania.com/armory/?quest=12535)
[A Rough Ride](http://www.wow-mania.com/armory/?quest=12536)
[Lightning Definitely Strikes Twice](http://www.wow-mania.com/armory/?quest=12537)
[The Mist isn't Listening](http://www.wow-mania.com/armory/?quest=12538)
[Hoofing It](http://www.wow-mania.com/armory/?quest=12539)
[Just following orders](http://www.wow-mania.com/armory/?quest=12540)
+) After you finish the Frenzy Heart side. You get the Oracle side start with Gorloc 's new quest:
[Fortunate Misunderstandings](http://www.wow-mania.com/armory/?quest=12570)
[Make the Bad Snake go away](http://www.wow-mania.com/armory/?quest=12571)
[Gods like shiny things](http://www.wow-mania.com/armory/?quest=12572)
[Making Peace](http://www.wow-mania.com/armory/?quest=12573)
[Back so soon](http://www.wow-mania.com/armory/?quest=12574)
[The Lost Mistwhisper Treasure](http://www.wow-mania.com/armory/?quest=12575)
[Forced Hand](http://www.wow-mania.com/armory/?quest=12576)
[Home Time](http://www.wow-mania.com/armory/?quest=12577)
[Angry Gorloc](http://www.wow-mania.com/armory/?quest=12578)
[Lifeblood of the Mosswalker Shrine](http://www.wow-mania.com/armory/?quest=12579)
+) Final Quest: [Hero's Burden](http://www.wow-mania.com/armory/?quest=12581) - this is the end of the chain, where you choose your faction that you wanna get rep with first, this quest is a daily quest, you can do it 1 each day to swap your faction from frenzyheart to oracle or the other way.
- After doing all of this, you are finally be able to do the daily quest to rinse your rep, have fun
Now after you have read all of it, you must now notice that only when you finish the chain, you will be able to chose side one time each day using that quest. Don't worry, a lot of people got this mistake, not only you (and those including me, i was trying to chose the side midway of my progress too, before reliaze that i was doing wrong)

**Comment by squalllh1989** [comment]
I will close it for now, if you already finish the whole chain and still have the problem, please report here again.

**Comment by Noahcoke** [comment]
Sorry then for not doing a better research. 
Thanks for the help.
