### ISSUE TITLE
Territorial Trespass not working correctly

### ISSUE THREAD

**Issue by HiArt99** [WoWManiaUK/Redemption#1987]
I am attempting to do the Sons of Hodir quest chain. I am up to Territorial Trespass, but even though I place the egg Veranus isn't lured. I am using the latest client/laucher. I have aboned the quest (several times) and logged out and cleared the cache. All add-ons disabled. I raised a support ticket and Amytis asked me to raise an issue

**Comment by fvicaria** [comment]
Works. Search before posting new issues please.
