### ISSUE TITLE
[Quest] Will of the Titans

### ISSUE THREAD

**Issue by dominichello** [WoWManiaUK/Redemption#1988]
Attacking with Soo-holu doesnt seem to generate rage and so skills 2 and 3 are un-usable. The Quest is still complete-able, it just has to be done with the melee swing.

**Comment by squalllh1989** [comment]
Please follow the procedure described below before creating a new issue:
[How to Properly Report an Issue](https://github.com/wow-mania/Redemption/wiki/How-to-Properly-Report-an-Issue)

This will help developers identify and fix the issue quicker. Incorrectly or unclear reports will simply be deleted.

**Comment by squalllh1989** [comment]
The quest [Will of the Titans](http://www.wow-mania.com/armory/?quest=12705): You can obtain a [Tainted Crystal](http://www.wow-mania.com/armory/?item=39266) from killing frenzyheart mob at the target area. You can use it at 33.6, 75 to summon and control [Soo-holu](http://www.wow-mania.com/armory/?npc=28115) and use it to hasten your quest progress. 
- What should happen: using [Wide Swipe](http://www.wow-mania.com/armory/?spell=52331) will genegrade "Warth" to use [Swift Paws](http://www.wow-mania.com/armory/?spell=52358) and [Flurry of Claws](http://www.wow-mania.com/armory/?spell=53032)
- What acually happen: using [Wide Swipe](http://www.wow-mania.com/armory/?spell=52331) not genegrade any "Warth", so [Swift Paws](http://www.wow-mania.com/armory/?spell=52358) and [Flurry of Claws](http://www.wow-mania.com/armory/?spell=53032) are currently unusable.
The quest still can be complete through using [Wide Swipe](http://www.wow-mania.com/armory/?spell=52331) alone or just grin the number of mob without summoning vehice (that's the way you do it when you have bad luck and the [Tainted Crystal](http://www.wow-mania.com/armory/?item=39266) didn't drop at all) but it will be great help to hasten the progress of the quest, as it require you to kill a fairly large amount of mob.

**Comment by VA-L** [comment]
- The vehicle is now using the correct ressource (Energy).
- All the abilities are now usable (if one of them doesn't work as intended, i'll look at it but for now, it should atleast be usable) and [Wide Swipe](http://www.wow-mania.com/armory/?spell=52331) correctly gives energy.

Up to test.

**Comment by dominichello** [comment]
@squalllh1989  Ill try better in the future to include more detailed write ups. Thanks for confirming the bug.

**Comment by squalllh1989** [comment]
@dominichello Thank you very much, that will hasten the progress of test / confirm / fix the bug that are reported a lot.

**Comment by squalllh1989** [comment]
Need some one with more retail experience on this, i can't find something useful to see what the vehice shoud work like. But at least, now the 2 ablity are useable.
