### ISSUE TITLE
"Call to Arms" quest daily

### ISSUE THREAD

**Issue by Karen64** [WoWManiaUK/Redemption#1989]
the NPC "Alliance Brigader General" should give you the quest called "Call to Arms" it´s a daily one, i remember this because i played Vanilla and TBC and this NPC gives you that quest which is bugged atm, and there is a achievement for doing those dailys.

Karen :3
![wowscrnshot_122217_173158](https://user-images.githubusercontent.com/34811586/34327009-7c4ba316-e898-11e7-92a4-488446f6c661.jpg)

**Comment by Karen64** [comment]
btw i guess in horde side too ^^;

**Comment by fvicaria** [comment]
This quest has been deprecated.

**Comment by Karen64** [comment]
then it dosnt work in RBG?

**Comment by fvicaria** [comment]
They do work you just need to kill during the event (not any time).

**Comment by squalllh1989** [comment]
The "Call to arms" has been merge in to the battle ground themself. Each day, one of the battle ground will be chosen, if you enter that battle ground and win, you get your bonus from that, as that is the focus of today's war. If you don't know what is the focus of today, press H (default keybind to pvp interface) and you can see, one of the battle ground will have "Call to arm" after their name.
