### ISSUE TITLE
[Quest] [80] The Drakkensryd

### ISSUE THREAD

**Issue by Thrombor2017** [WoWManiaUK/Redemption#1990]
Hello, the quest "The Drakkensryd" (Taken from "Gretta the Arbiter" in the Storm Peaks) looks bugged:

**Objectives :** 
Use the [Hyldnir Harpoon] to defeat 10 Hyldsmeet Drakeriders at the Temple of Storms. Use the Hyldnir Harpoon on a Column Ornament to exit the Drakkensryd and speak to Thorim when you've succeeded.

**Issue :** When jumping on an drake with an enemy rider on it, we can't kill the rider, he will "evade" every hits or spells.

**Steps to reproduce the problem:**

1 - Make sure you are not already mounted.
2 - Then take the quest from Gretta the Arbiter, you will be mounted on a blue proto drake wich will bring you around the Temple of Storms. 
3 - Now use the Harpoon provided by the quest to "jump" on a drake with a rider already on it.
4 - Here is the issue, you can't fight the rider like you are supposed to.

Description of the quest and how it should work : http://wowwiki.wikia.com/wiki/Quest:The_Drakkensryd

I provide you a video found on Youtube showing how it should work : https://www.youtube.com/watch?v=c9i4SD9IeeY

**Comment by fvicaria** [comment]
Quest works. Please search before opening new issue.

**Comment by Thrombor2017** [comment]
Quest doesn't work. why would i have wrote a report otherwise ? Justed tested it once again and stuck at the same point mentioned in my report.

**Comment by Dranah** [comment]
Quest is bugged, but doable. Not all the riders evade, just many, which makes it a pain in the ass to complete , but as long as it's doable, I suppose devs have more important things in focus.

**Comment by Thrombor2017** [comment]
Ok, thank you.

**Comment by VA-L** [comment]
The quest is indeed doable but this is fixed as much as possible.
The issue is related to some weird movements from the drakes not updating correctly the position of the riders which result in an "Out of range" error most of the time.


> Keep jumping until you find working rider
That's the way to go.
