### ISSUE TITLE
[Quest] Abduction 

### ISSUE THREAD

**Issue by TheManiax** [WoWManiaUK/Redemption#1991]
Quest [abduction](http://www.wowhead.com/quest=11590/abduction)
Whats supposed to happen is that you have to attack the NPC [Beryl Sorcerer](http://www.wowhead.com/npc=25316/beryl-sorcerer) and at approximately 25% HP, you can use the  [Arcane Binder](http://www.wowhead.com/item=34691/arcane-binder) you were provided to capture him.
The issue is that the NPC is friendly and can not be attacked.

**Comment by squalllh1989** [comment]
Fix confirmed, the  Beryl Sorcerer is now attackable, the quest work good now.
![wowscrnshot_122517_183834](https://user-images.githubusercontent.com/27235989/34339192-f4c470ce-e9a2-11e7-8f29-1763d5c8d6be.jpg)
![wowscrnshot_122517_183852](https://user-images.githubusercontent.com/27235989/34339193-f5f445fa-e9a2-11e7-8f90-1d723609fc60.jpg)
