### ISSUE TITLE
[Quest] Steamtank Surprise

### ISSUE THREAD

**Issue by dominichello** [WoWManiaUK/Redemption#1993]
Searched the Closed Issues found similar [Report](https://github.com/WoWManiaUK/Redemption/issues/1551)
- Release 45 on 6 Sep

When riding the Steamtank the x3 damage that is meant to be applied by [Ice Prison](http://www.wow-mania.com/armory/?spell=49333) still does not seem to affect the damage of [Ice Cannon](http://www.wow-mania.com/armory/?spell=49315) when used in combo. 

Damage before Buff:
![wowscrnshot_122517_001627](https://user-images.githubusercontent.com/34451144/34329921-c83aec42-e90a-11e7-8e06-e1cab60ae8f0.jpg)

Damage with Buff Applied:
![wowscrnshot_122517_001809](https://user-images.githubusercontent.com/34451144/34329925-d6aadb48-e90a-11e7-834e-68500f7ae597.jpg)

Quest is still complete-able all other skills work correctly.

**Comment by VA-L** [comment]
Seems like the old issue is back too, the tank will also attack you if you exit it during the quest.

**Comment by fvicaria** [comment]
Fixed as much as possible. 
I could not find any info on the actual effect of these spells. 

- If you dismount tank dies now.
- It will also despawn after you deliver the troop so that needs to be your last action.
