### ISSUE TITLE
Hunter mob loot problem

### ISSUE THREAD

**Issue by Swista** [WoWManiaUK/Redemption#1994]
So this issue seems a bit odd to me.
Basically, i'm a level 80 hunter, and i wanted to level my engineering, and i would go out and farm linen cloth at low level spots, and i put my pet on aggressive while i was looting, and i discovered that whatever my pet killed i was unable to loot, which seemed weird to me, considering a hunter without pet is really slow at killing multiple mobs, since we don't have too many AoE abilities like Druids or other classes, so it seemed only fair if we could use our pets to help us farm.

Note: I'm unsure if blizzard disabled looting your pets loot or gain exp from it's kills, but lets be fair, if you let your level 25 pet on aggressive against level 25 mobs, whilst you're afk, so you can just exp farm while afk, then your pet is gonna die and give you no exp... I see no point in not fixing this, it doesnt give hunters an advantage it just lifts us up to same farming capabilities as druids.

**Comment by TheManiax** [comment]
It is working as it should.

**Comment by squalllh1989** [comment]
This is to prevent afk with pet in agrosive mode to auto attack and farm while you away. To get your loot and exp, you must do damage to the mob too, not only your pet
