### ISSUE TITLE
Shadowmoon Valley Quest Item not getable after you deleted accidentally

### ISSUE THREAD

**Issue by Galagus420** [WoWManiaUK/Redemption#1995]
Hello , today as I was working towards Loremaster of Outland, i had a quest in which i needed an item called Spectrecles , a set of glasses which made me able to see the mobs i was supposed to kill, i did the quest and deleted the quest item afterwards, a few quests ahead on that quest chain i needed them again to be able to see some other mobs, the problem is the npc which is supposed to give me other in case of deleting doesn't give others, the npc is called Chief Apothecary Hildagard. Reporting this so it gets fixed so people trying to do this in the future in case they do the same mistake as me are able to do it. Thank you, Galagus.

**Comment by fvicaria** [comment]
As is some quests are cannot be retaken.
Ask a GM to remove it from you.
