### ISSUE TITLE
[NPC] Chief Apothecary Hildagard

### ISSUE THREAD

**Issue by Galagus420** [WoWManiaUK/Redemption#1997]
Hello, while trying to do the loremaster of outland achievement, i started to quest in Shadowmoon Valley, one of the first quests in Shadowmoon Valley is Spectrecles (http://wow-mania.com/armory/?quest=10625#.) given by Chief Apothecary Hildagard (http://wow-mania.com/armory/?npc=21772#abilities)  in Shadowmoon Village , in this quest you are given a pair of glasses called Spectrecles (http://wow-mania.com/armory/?item=30719)  that you must use to be able to see the adds you are supposed to kill , after completing this quest i still had the glasses in my bag and i deleted them thinking i wouldn't need them again. A few quests after in that quest chain, i had three quests given by The Ancient Shadowmoon Spirit (http://wow-mania.com/armory/?npc=21797) in The Altar of Shadows( http://wow-mania.com/armory/?quest=10634  ; http://wow-mania.com/armory/?quest=10635 ; and http://wow-mania.com/armory/?quest=10636). I was having trouble in finding the mobs needed so i tourned to google, and i am supposed to wear the Spectrecles to be able to see the adds needed for those quests aswell. In case of someone who deletes the glasses, the npc from the first quest , Chief Apothecary Hildagard, is supposed to give other ones to you , however in the server she doesn't do that how she is supposed to. After requesting the assistance of GM Amytis and him giving me the glasses and trying to delete the quest from me and me getting it back i wasn't keeping the glasses after delivering it like the first time and even when trying to do the first quest and not delivering it so i would still have the glasses and trying to see the adds from the other Divination quests, i couldn't see the adds. I would like to see this fixed so Chief Apothecary Hildagard can give other Spectrecles in gase of deleting so other people don't go through this much trouble in case of deleting the item like me. Thank you.
Galagus

**Comment by fvicaria** [comment]
Please open a ticket in-game for this and ask for the glasses.

**Comment by fvicaria** [comment]
Missing gossip added.
