### ISSUE TITLE
[Boss] A tribute to Insanity (10 player)

### ISSUE THREAD

**Issue by squalllh1989** [WoWManiaUK/Redemption#1998]
- What should happen: after kill [Anub'arak](http://www.wow-mania.com/armory/?npc=34564#drops-3) with 50/50 attempt left (not wipe a single time in the raid), you will get a [Argent Crusade Tribute Chest](http://www.wowhead.com/object=195665/argent-crusade-tribute-chest) for that.
- What acually happen: after kill [Anub'arak](http://www.wow-mania.com/armory/?npc=34564#drops-3) with 50/50 attempt left, you didn't get a tribute chest for that, as if you only have lower than 24 attempt remain.
As you can see here in the screenshot below:
- The first one show that anub is dead, we got 50/50 unsucessful attempt left and i just got "A tribute to Insanity (10 player)"
![wowscrnshot_122617_035705](https://user-images.githubusercontent.com/27235989/34342928-34710e2c-e9f2-11e7-84d1-8940eae723c3.jpg)
- The second one show that we got no tribute chest bonus
![wowscrnshot_122617_035659](https://user-images.githubusercontent.com/27235989/34342943-c1efe41c-e9f2-11e7-9540-485845ce1bd7.jpg)
After a while waiting for ticket response, we got Amytis come to help us, he can see the chest with gm on, and he only see 2 x  Trophy of the Crusade and 1 x  Crusader Orb (just like we only have 24 and below attempt left) inside.

**Comment by VA-L** [comment]
- The chest now appears correctly.
- Correct loots are inside.

Up to test.

**Comment by TheManiax** [comment]
The chest appears fine but it gives double [Trophy of the Crusade](http://www.wowhead.com/item=47242)
Means I got 4x Trophy of the Crusade from the chest
Here is the loot from 10HC mode
![wowscrnshot_122617_204420](https://user-images.githubusercontent.com/14857593/34361407-129db740-ea7f-11e7-9296-02e940ae7be7.jpg)
![wowscrnshot_122617_204422](https://user-images.githubusercontent.com/14857593/34361408-12c63c7e-ea7f-11e7-8191-37bde6bf80f7.jpg)
![wowscrnshot_122617_204423](https://user-images.githubusercontent.com/14857593/34361409-12efcefe-ea7f-11e7-951d-a87dffa4931f.jpg)

**Comment by fvicaria** [comment]
This has not been deployed yet.

**Comment by squalllh1989** [comment]
Oh sorry then, we just get A tribute to Insanity (25 player) like 23 hours ago and the chest appear, so i think it was deployed :)

**Comment by fvicaria** [comment]
Sorry, it may have been deployed then. I was not sure.
