### ISSUE TITLE
[Glyph] Glyph of Siphon Life

### ISSUE THREAD

**Issue by Necrosiss** [WoWManiaUK/Redemption#1999]
Hello I just tested that glyph on dummy in Orgrimmar. Orginal talent says http://www.wow-mania.com/armory/?spell=63108, but after you equip above glyph http://www.wow-mania.com/armory/?item=42469 , nothing get change. 40% + 25% should heal back 65% and Corruption still heal the same amount with or without glyph. Could please take a look on it? 

Regards, Necrosiss.

**Comment by fvicaria** [comment]
Please do not reference other servers here.  Edit your description please.

Please follow the procedure described below before creating a new issue:
[How to Properly Report an Issue](https://github.com/wow-mania/Redemption/wiki/How-to-Properly-Report-an-Issue)

This will help developers identify and fix the issue quicker. Incorrectly or unclear reports will simply be deleted.

**Comment by Necrosiss** [comment]
Sorry, didnt notice that the link to talent was from other server database, fixed. And yes, im using fully client and all them time from launcher. Problem nonexist in current issues so guess now everything is fine.
