### ISSUE TITLE
[Spell] Slam (Warrior)

### ISSUE THREAD

**Issue by LooneyBin** [WoWManiaUK/Redemption#2000]
So, the T10 4 set bonus for fury warrior got fixed today, thanks for that.
But, now there's a new problem, Slam cant be cast while moving.

What should happen: 
When Bloodsurge http://www.wow-mania.com/armory/?spell=46915 Procs, we should have a instant cast of Slam, moving or not.

What is actually happening:
on Bloodsurge proc, then Slam require us to stand still, which it shouldnt do.

Slam: http://www.wow-mania.com/armory/?spell=47475
Bloodsurge: http://www.wow-mania.com/armory/?spell=46915

It's like the game atm, isent taking into account that we have no cast time on Slam on Bloodsurge proc, and thus think we're trying to cast a normal slam with the 1.5 sec cast time.

Have tested this on the Org Dummies both with 4 x t10, and without the 4 set bonus... and Slam is behaving the same in both cases, so it's not the Tier bonus that isent working, it's Slam in itself.

**Comment by VA-L** [comment]
The cast while moving thing about Slam was added at the 4.0.1 patch or around it, just to let you know that it was implemented at the start of Cataclysm not at WOTLK.
You can also know that by reading some comments about it on wowhead from the 4.0.1 patch time.

**Comment by LooneyBin** [comment]
you totaly miss the point here.

The instant cast part of Bloodsurge, that doesnt work if we're moving. we have to stand still to CAST A INSTANT skill, that's what isent working.

**Comment by LooneyBin** [comment]
and just to explain further.

Bloodsurge: Your Heroic Strike, Bloodthirst, and Whirlwind hits have a 20% chance of making your next Slam instant for 5 sec.
http://www.wow-mania.com/armory/?spell=46915

So atm, with that talent procced, then we have to stand still to use our slam, and it's instant cast.

that's not how it's supposed to work, with Bloodsurge procced (giving us a instant slam), then we should be able to move while using our slam once(or twice if using 4 T10 and get the double proc).

**Comment by Plege** [comment]
the issue was reported to be blizzlike by one of our devs, this is why the issue was closed. Please remember that pure logic doesn't always apply if you want us to look further into this issue provide proofe that slam was actually castable while moving during the Slam instant aura being active on the 3.3.5a patch being live. Pretty much the only way to do that is a POV video of a warrior casting instant slams while moving on a verfiable retail 3.3.5a server.

**Comment by LooneyBin** [comment]
and i say again, you're missing the point.
Slam: in 3.3.5a have a 1.5 sec cast time, UNLESS you as fury, get a Bloodsurge proc, then it becomes instant, meaning no cast time.
http://www.wow-mania.com/armory/?spell=47475   <-- Slam skill, taken from your armory.
http://www.wow-mania.com/armory/?spell=46915   <-- Bloodsurge talent, again from your armory.


what VA-L apparently think i mean, is that the 4.0.1 Slam, which have no cast time at all, this isent the issue, ofc we on a 3.3.5a server, shouldn't be using skills from other patches.
http://www.wowhead.com/spell=1464/slam   <-- 4.0.1 slam skill from Wowhead

if a warrior is trying to use Slam normally, with the 1.5 sec cast time, then ofc he have to stand still, all fine and good.
But when you get a Bloodsurge proc, making Slam instant, then you should be able to move while using said proc, and that you cant do atm, and that is the problem i'm trying to point out here.

Do rogues have to stand still to use Sinister strike?
Do paladins have to stand still to use Judgement?
Do mages have to stand still to use Ice Lance?
Do hunter have to stand still to use Arcane Shot?

it's the same with instant slam, it should be useable while moving, WHEN you have a Bloodsurge proc ofc.


https://www.youtube.com/watch?v=kLQEXOXObTA&t=277s

This is from retail, so doesnt get more legit then that.

look at around the 4:00, he gets a Bloodsurge proc, and use slam while moving around the mob.

**Comment by ragehoof72343** [comment]
Just like Looneybin said. http://www.wow-mania.com/armory/?spell=46915<-- bloodsurge. When it procs means ur next slam is instant and also it means that u can use it while moving. i have made a video hope it helps       https://www.youtube.com/watch?v=RxNYqPQEJys&feature=youtu.be

**Comment by calvinidea1** [comment]
Devs.... Show me ANY OTHER instant Melee attack that can NOT be performed while moving?

You are saying that SLAM, and ONLY SLAM, has this limitation? =/= logic

**Comment by VA-L** [comment]
You guys are right, i misunderstood your point on this issue.
It's gonna be investigated.

**Comment by LooneyBin** [comment]
Thanks VA-L.  :)  much appreciated that you'd look into it.

**Comment by ragehoof72343** [comment]
https://www.youtube.com/watch?v=kLQEXOXObTA  look around 3:00-4:00 min....when the http://www.wow-mania.com/armory/?spell=46915 proced he used http://www.wow-mania.com/armory/?spell=47475  while moving
