### ISSUE TITLE
[Boss] Heigan the Unclean

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#2001]
I saw a fix was applied after my previous bug report on this matter, so I re-tested the fight today and while it does show an improvement on the intervals, it produces a new bug now and it still doesn't resemble the intended dance at all. 
Heigan the Unclean's (http://www.wowhead.com/npc=15936) Eruptions (http://www.wowhead.com/spell=29371) happen now as follows, where t=0 is the pull:
t=15
t=25 (these are okay so far)
t=35 and t=36 (proper 10sec interval, but double splash)
t=45 and t=46 (proper 10sec interval, but double splash)
t=55 t=56 and t=58 (triple splash?!)
t=65 t=66 and t=68 (triple splash...)
t=75 t=76 t=79 t=80 (quadro splash)
t=85 t=86 t=90 t=90 (quadro splash)
So as the fight progresses, there are more than 1 sequence of eruptions running on a 10sec timer, as it appears. Luckily they don't all hit the same segment of the room.
Phase2 is still the old way, regular 5sec splashes which is way too slow (intended is about ~3s for p2)

**Comment by Keader** [comment]
Eruptions is casted by Plague Fissure objects.
They have 10 sec cooldown in each 29371 (Eruption) cast.
I cant reproduce your issue, for me is always 10 sec interval.

**Comment by fvicaria** [comment]
Can someone test this in dev.

**Comment by Keader** [comment]
Yes, i can confirm it in Dev realm.

**Comment by Dranah** [comment]
just tested after update, beautiful scripts!!! blizzlike!!!!
