### ISSUE TITLE
[Boss] Trial of the Crusader - Anub'arak

### ISSUE THREAD

**Issue by hotdoggidy** [WoWManiaUK/Redemption#2002]
During the encounter Anub'arak submerges frequently, hiding himself from the raid. 
During this "Submerge" phase, the boss targets random members of the group and chases them down, firing spikes up through the ground as he moves. 
These spikes cause massive damage and should 1-hit kill players if it reaches them. 
To avoid this mechanic, raid members must stand on frozen patches on the floor to deny Anub'arak his attack. Once deflected, the boss will re-target another member and continue on his chase.
This phase lasts 40 seconds.

Currently on Redemption the boss submerges correctly, chases correctly and is deflected by the frozen patches as designed.

Damage dealt by spikes does not seem to be consistent. Some spikes deal massive damage, some do none at all.

However, if the raid group stacks as 1 the boss will NOT use his spikes upon reaching his target. Furthermore, he will continuously target random members as long as they are stacked, dealing no damage for the duration of the phase.

https://www.youtube.com/watch?v=NHbllPPuA1M&t=9s

**Comment by VA-L** [comment]
I noticed this bug while testing this [issue](https://github.com/WoWManiaUK/Redemption/issues/1998), i actually thought it was because i've tested it solo ... Well, it turned out nope.

Thanks for reporting, i'm on it.

**Comment by CrustyMuffin** [comment]
There is also an other issue with this boss. If you wipe during the 2nd or 3rd phase, he´ll bug. When we wiped during the 2nd phase, he´ll stay underground and won´t be able to attack, target or fight him. When we wiped during the 3rd phase, he would keep his "Leeching Swarm" (http://www.wowhead.com/spell=66118/leeching-swarm) ability active, even after the fight.

**Comment by VA-L** [comment]
- Adds now despawn correctly when Anub evades.
- Anub resets correctly when evading during his underground phase.
- Attempts are now correctly decreased if players failed.
- Anub will no longer keep changing targets (it was also not doing anything else) during his underground phase. (players stacking themselves issue)
