### ISSUE TITLE
[Spell] Blessing of Ancient Kings - Not absorbing spell damage

### ISSUE THREAD

**Issue by xclaw800** [WoWManiaUK/Redemption#2003]
The item Val’anyr Hammer of Ancient King’s recently was fixed to proc properly and do absorbs and apply the shields to players recently but there is a specific problem with the shields that are being applied. 
The shields for the blessing of ancient kings is absorbing all forms of physical damage and the overheal coding seems to be proper but there is no absorption from the shields when spell damage is put on targets.
 For example in the frostmourne phase of lich king heroic on multiple runs of 10 and 25 man the shields remained on the target and faded from time not damage reduction and during that time no absorbs were recorded. 
The same issue comes when infest is applied to a target. When this happens the shields remain on all targets and do no absorbs or shielding against the spell.
 I believe at the minimum it does not shield against shadow damage and seeing as that is a large portion of end game content raid damage it would be great for this to be fixed. Looking into frost, fire and nature spell damage also would be a fix to all relevant raid content.
 Thank you for the continued work on this issue.

**Comment by VA-L** [comment]
![image](https://user-images.githubusercontent.com/11377592/34379947-696b8078-eafe-11e7-9d21-8826b63fb323.png)

This is how it works here as well, i've tested it on lich king with a full absorb shield capacity (20.000) and the pain and suffering (for example, that's a shadow spell) was absorbed by the shield.

**Comment by xclaw800** [comment]
Thank you for looking into it. I know you have closed the issue but is it possible that the shields aren’t absorbing the damage if the damage is higher than the shield applied. This was a previous issue with power ward shield.

**Comment by fvicaria** [comment]
Overheal should be working also. If you have any screenshot that may help also.

**Comment by Plege** [comment]
The Val'anyr issue is confirmed.
Testing was done under the following circumstances:

- A duel between two characters (mage and priest)

- priest was damaged to 50% health to avoid overheals that wouldn't result in an effective shield

- the mage cast damaging spells of each class on the priest that healed himself continuosly with the val'anyr procc active

- in a last step the mage was switched with a warrior to test another damage school (physical)

The results:
For the mage tests there was no absorbs whatsoever on any of the spells arcane, fire or frost

When attacked by physical class attacks the absorbs were present as they should

Rank 1 spells were used as well to avoid overkill on the shields but when testing with physical attacks it became apparent that overkill of the shield did not prevent it from absorbing damage as was the case with disc shields

Here some numbers to show no overheal was present, the shield vanished without absorbing damage repeatetly and the shield worked properly for physical attacks.

Testing with arcane mage (no overheal no absorbs)
Pflotsch's Flash Heal heals Pflotsch for 5364.(Critical)
Pflotsch gains 11 Mana from Pflotsch's Replenished.
Pflotsch gains Pflotsch's Protection of Ancient Kings.
Pflotsch gains 395 Health from Pflotsch's Blessed Healing.
Pflotsch gains 11 Mana from Pflotsch's Replenished.
Pflotsch's Protection of Ancient Kings is refreshed on Pflotsch.
Pflotsch's Protection of Ancient Kings fades from Pflotsch.
Yeyewata's Arcane Blast hits Pflotsch for 11697 Arcane.(Critical)
Pflotsch's Flash Heal heals Pflotsch for 3560.
Pflotsch gains 11 Mana from Pflotsch's Replenished.
Pflotsch gains Pflotsch's Protection of Ancient Kings.
Pflotsch's Blessing of Ancient Kings fades from Pflotsch.
Pflotsch's Protection of Ancient Kings fades from Pflotsch.
Yeyewata's Arcane Blast hits Pflotsch for 6210 Arcane.

Duel aggainst warrior (no overheal but absorbs present also partial ones)
Pflotsch's Protection of Ancient Kings fades from Pflotsch.
Turrok's melee swing hits Pflotsch for 615 Physical.(533 Absorbed)
Pflotsch's Flash Heal heals Pflotsch for 3482.
Pflotsch gains 11 Mana from Pflotsch's Replenished.
Pflotsch gains Pflotsch's Protection of Ancient Kings.
Pflotsch gains 391 Health from Pflotsch's Blessed Healing.
Pflotsch gains 11 Mana from Pflotsch's Replenished.
Pflotsch's Protection of Ancient Kings is refreshed on Pflotsch.
Pflotsch's Flash Heal heals Pflotsch for 3545.
Pflotsch gains 11 Mana from Pflotsch's Replenished.
Pflotsch's Protection of Ancient Kings is refreshed on Pflotsch.
Pflotsch's Protection of Ancient Kings fades from Pflotsch.
Turrok's melee swing hits Pflotsch for 292 Physical.(1111 Absorbed)
Pflotsch gains 391 Health from Pflotsch's Blessed Healing.
Pflotsch gains 11 Mana from Pflotsch's Replenished.
Pflotsch gains Pflotsch's Protection of Ancient Kings.
Pflotsch's Protection of Ancient Kings fades from Pflotsch.
Turrok's melee swing hits Pflotsch for 2234 Physical.(58 Absorbed) (Critical)

Also important to note that the spell taken from wow mania armory states physical attacks school (noted by Elagen) http://wow-mania.com/armory/?spell=64411

Regards 
Pleger

**Comment by Plege** [comment]
the spelldamage schools are now all absorbed, overhealing does not give an effective shield anymore the spell will only procc of effective healing
