### ISSUE TITLE
Feign Death breaking mob chains

### ISSUE THREAD

**Issue by xeored** [WoWManiaUK/Redemption#2006]
The Hunter ability Feign Death seems to be causing groups of mobs to become unlinked to each other after resetting, allowing individual mobs to be pulled out of groups once feign death has been used on them.

**Comment by TheManiax** [comment]
I tested this on Dev and the whole pack of the mob is being pulled after I used [Feign Death](http://www.wowhead.com/spell=5384/feign-death)
I close the issue.
If you have more informations on this, Please follow the procedure described below for creating a new issue:
[How to Properly Report an Issue](https://github.com/wow-mania/Redemption/wiki/How-to-Properly-Report-an-Issue)

This will help developers identify and fix the issue quicker. Incorrectly or unclear reports will simply be deleted.
