### ISSUE TITLE
[Quest] Gadgetzan Water Survey

### ISSUE THREAD

**Issue by JackAquastar** [WoWManiaUK/Redemption#2007]
In the mission in Tanaris "Gadgetzan Water Survey", I was unable to fill the untapped dowsing widget in the Sandsorrow Watch water hole while standing inside. I reported the problem and a GM tried to assist. The GM was also unable to fill the dowsing widget as well. GM ended up giving me the filled dowsing widget.

**Comment by fvicaria** [comment]
Please follow the procedure described below before creating a new issue:
[How to Properly Report an Issue](https://github.com/wow-mania/Redemption/wiki/How-to-Properly-Report-an-Issue)

This will help developers identify and fix the issue quicker. Incorrectly or unclear reports will simply be deleted.

**Comment by fvicaria** [comment]
Quest works just find the correct position. The GM was wrong to complete it for you.

![image](https://user-images.githubusercontent.com/9414661/34394535-bdea9d66-eb51-11e7-92f1-7c6b236a4252.png)
