### ISSUE TITLE
[Spell] Killing Spree

### ISSUE THREAD

**Issue by Wardoc** [WoWManiaUK/Redemption#2008]
Its supposed to hit 5 times but if the target is further away and you teleport to them it doesnt hit at all.

How it is on wow-mania: https://www.youtube.com/watch?v=VBBChmFlQgo&feature=youtu.be
you can see in the video only 2 assaults vent through.

How its supposed to work: https://www.youtube.com/watch?v=FBWQKNkLN1k&feature=youtu.be
On single target it does the correct ammount of assaults, this is how its supposed to work even on multiple targets. it shouldnt be skipping hits recardless of how far you teleport for the next hit.

**Comment by Wardoc** [comment]
http://wow-mania.com/armory/?spell=51690 is the spell im referring to.

**Comment by Plege** [comment]
works now even with several targets apart from eachother will attack 5
