### ISSUE TITLE
Winterfall runners

### ISSUE THREAD

**Issue by whatapro** [WoWManiaUK/Redemption#2011]
Quest ask you to find the patrol inside wintergrasp in order to take winterfall crate, but nobody appears. I waited them a lot of time and no fulborgs arrived. Wowhead says that they patrol the road from timbermaw hold to lake keltheril.

http://www.wowhead.com/quest=28469/winterfall-runners

**Comment by fvicaria** [comment]
Quest works fine. They move along the road. Please research before posting an issue as this consumes developer time.
![image](https://user-images.githubusercontent.com/9414661/34433482-97dae366-ec77-11e7-8e10-305ee402bc3a.png)
