### ISSUE TITLE
[Spell] Ice Block

### ISSUE THREAD

**Issue by Dredziarz** [WoWManiaUK/Redemption#2012]
Hej, 
i wanted to do this issue few weeks ago but i hadn't free time for it.

I found the bug in the Ice Block mage's skill. 
It should work that: Encases you in a block of ice, protecting you from all attacks and damage for 10 sec, but during that time you cannot attack, move, or cast spells.  
-Apply Aura: Immunity (Physical)
-Apply Aura: Immunity (All)

Acctualy it work like it don't work because Ice block don't protect me from damage for example:
-explode of Festergut after earned 3 stacks of buff on himself
-explode from Ozzes on Proffesor. 
and many many other damage on raids.

I'm sorry for my english but i'm sure you will understand what i wanted to share with you.

**Comment by LooneyBin** [comment]
http://www.wow-mania.com/armory/?spell=45438

skill he's refering to.

**Comment by Dredziarz** [comment]
Ok guys, but please check it's work bad on ICC bosses, let's check it
please.


<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Wolny
od wirusów. www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

2017-12-29 12:53 GMT+01:00 LooneyBin <notifications@github.com>:

**Comment by squalllh1989** [comment]
Does the fix push to redeemtion yet ? Because last night on our icc25hc festergut, i still have big damage that reduce me under 20% hp with 2 stack of spore while in iceblock

**Comment by squalllh1989** [comment]
And anyone know if active iceblock make you imune to mystic buffer (sindy aoe in phase 2) or not, because when i active then remove iceblock in 2-3 sec, the mystic buffer still stay with it stack (was at 7 when i active iceblock, them after i active then remove iceblock, the next tick of mysticbuffer still stack up to 8 like normal)

**Comment by Keader** [comment]
yes, iceblock shoul remove all sindragosa debuffs
