### ISSUE TITLE
lots of bugs in northrend questing 

### ISSUE THREAD

**Issue by naightsky** [WoWManiaUK/Redemption#2013]
Words of power quest name you get the scrolls from the 2 npc's but the last one just vanishes after killing him *high Priest Naferset* Also it would be nice if the north sea thug when killed would drop the shipment of animal parts also. Quest in the gnomer area in northren fizz crank air strip the gun given works but the quest stays 0/5 so you can not complete it. Still looking for launch box  and nedar not to be found in the location. Is anyone else having these problems.. 12/29/17

**Comment by fvicaria** [comment]
This is not a proper report. "lots of bugs" :)

Please follow the procedure described below before creating a new issue:
[How to Properly Report an Issue](https://github.com/wow-mania/Redemption/wiki/How-to-Properly-Report-an-Issue)

This will help developers identify and fix the issue quicker. Incorrectly or unclear reports will simply be deleted.

**Comment by naightsky** [comment]
I understand but i hope you at least looked at what i had to say it would be nice if these where fixed because the high priest quest leads to a nice 2h axe i asked a gm and he told me to post on here so i did i but i wish it was just about that problem instead of having to name a few more i only posted to help improve the game because like many i do enjoy this x pack even with the wow mania touch keeping it from being orginal

________________________________

**Comment by wow-mania** [comment]
Check the procedure.
I will not waste my time if you don't bother reading the instructions for 2 minutes.


Regards,

Janitor
wow-mania.com<http://wow-mania.com/>
The best WotLK server

Skype: wow-mania.com<http://wow-mania.com/>
[1496666926534_468x60.gif]

________________________________
