### ISSUE TITLE
[Achivement] With a little help from my friend

### ISSUE THREAD

**Issue by squalllh1989** [WoWManiaUK/Redemption#2015]
- [This achivement](http://www.wow-mania.com/armory/?achievement=252) is done by: Get into the PX-238 Winter Wondervolt machine (in the midle of dalaran) to get transformed to a  Little Helper, then earn 50 honorable kill as the Little Helper (being killed will make you lost the  Little Helper form and you will have to get it again from the PX-238 Winter Wondervolt machine. The achivement work perfectly from the start of winterveil event.
- What that it is happening NOW: the PX-238 Winter Wondervolt machine no longer work, you won't get transformed when you enter it, that cause the achivement undoable.

**Comment by fvicaria** [comment]
Which part is not working? The machine?

**Comment by StarrZappa11** [comment]
the machine is not working.

**Comment by fvicaria** [comment]
This works fine in dev for some reason.

**Comment by Plege** [comment]
The machine is working properly on dev

**Comment by squalllh1989** [comment]
Can you please push this as soon as posible to redemtion ? It's only 2 more day before winterveil end, it's pointless to push it after that.

**Comment by fvicaria** [comment]
Too risky to rush an update for this. I will extend the event for 2 days if needed.

**Comment by squalllh1989** [comment]
that will work too, thank you for consider that :)
