### ISSUE TITLE
[Boss] Thaddius

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#2018]
Hello,
I'd like to report an issue with the instance not resetting properly after wiping or dcing on Thaddius (http://www.wowhead.com/npc=15928/thaddius) or his mini bosses Feugen and Stalagg ( http://www.wowhead.com/npc=15930/feugen, http://www.wowhead.com/npc=15929/stalagg) inside Naxxramas. When you get teleported out, you aren't allowed back inside, says "Encounter is still in progress", I cannot tell why.
 I made a ticket the first time and GM helped me, but it keeps happening again, not every time but 2 out of 3 tries and i don't wanna keep making tickets every time. Doesn't seem to matter which stage of the fight you're in, whether you die to falling into slime, mini bosses, or Thaddius himself kills you, it can still occur. 
Hope you can look into this, thank you
PS: bug doesn't go away even after 1-1,5hour passed

**Comment by Keader** [comment]
i will check it tomorrow

**Comment by Keader** [comment]
Added a new protection too, if thadius stuck in combat, he will evade after 10 sec
