### ISSUE TITLE
[Item] Smokywood Pastures Gift Pack

### ISSUE THREAD

**Issue by roleplay1** [WoWManiaUK/Redemption#2021]
After completing the  quest  you receive  a package  from Great-father Winter
But the package is empty

http://www.wowhead.com/quest=6962/treats-for-great-father-winter

**Comment by roleplay1** [comment]
after  trying the  q  several times it gave  some items

**Comment by fvicaria** [comment]
http://www.wow-mania.com/armory/?item=17727#contains

It's a chance to get those. So yes, it can happen you get nothing. 
I will add some 100% items to it. :)
I am too nice...
