### ISSUE TITLE
[Spell] Summon Gargoyle (talent)

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#2022]
Hello,
I'd like to report Unholy dk's end talent, the Summon Gargoyle spell (http://www.wowhead.com/spell=49206/) for not beginning to attack properly when summoned in a static melee position.
The Ebon Gargoyle it spawns is an uncontrollable pet that should immediately begin attacking the target of the death knight when it is summoned.

How it works at the moment: 
If the DK is static in melee range of his target when he casts it (i.eg. not running inside still), the Gargoyle will not begin to attack or do anything until it is forced to move, it just stands next to the death knight. The death knight must move around until the Gargoyle following him is forced to move a bit as well, and only then he recognizes the target to attack.
The main problem with this is that the duration of the spell is the same 30sec regardless of when the gargoyle finally starts attacking, so even though you can trigger him to attack via movement, you lose precious seconds while he wasn't attacking, thus his total damage will be always lower than intended.

**Comment by VA-L** [comment]
- The gargoyle now attacks directly.

Up to test.

**Comment by Dranah** [comment]
Re-tested this today on Redemption and the Gargoyle still refuses to attack in a stationary fight. You still have to move around to trigger him doing anything.

**Comment by fvicaria** [comment]
@Val: Can you re-check this please.

**Comment by Dranah** [comment]
this works in dev but wasn't applied to Redemption yet

**Comment by TheManiax** [comment]
@fvicaria  Still not working on Redemption.

**Comment by Dranah** [comment]
I have to reopen this because I found the reason it was only seeming to work on Dev. (wrong method of testing)
Basically it's working only when the debuff aura of the Summon Gargoyle effect is already present on the target when you summon the gargoyle. (for example, if there are two unholy dks in a raid, the first one whose gargoyle is summoned will not start attacking, but the second who casts will - same happens if you are spam using the ability to test on dev, you will find it working 99% of the time because you didn't wait for the previous aura to expire)
But it needs to work without the aura already present as well. (that's how it is used on Redemption)

**Comment by fvicaria** [comment]
This has been confirmed by you.

**Comment by Dranah** [comment]
It is the other way around, the fix not working 99% of time in actual situations on Redemption.

**Comment by fvicaria** [comment]
So you managed to confirm on the 1% that was and missed the 99%? :)

**Comment by Dranah** [comment]
Exactly.

**Comment by Keader** [comment]
I can make gargoyle always attack DK target, is good 4you?

**Comment by Dranah** [comment]
yes that would be the point, to make him start attacking without having to dance around until he finally notices theres a target

**Comment by Keader** [comment]
Fixed to Blizzlike Behavior.
If DK has no pet, Gargoyle will stay attacking target of spell
If DK has pet, DK will follow attack pet command.

**Comment by Dranah** [comment]
Very nice. 
- Gargoyle now descends from above as the tooltip suggests "flies into the area" and acquires his target immediately
- Having an active pet bar (your ghoul) allows you to make gargoyle switch target
