### ISSUE TITLE
[Quest] It Rolls Downhill

### ISSUE THREAD

**Issue by Shadowmalroc** [WoWManiaUK/Redemption#2023]
Character-Draenei Shaman
Area-Zuldrak
Quest-It Rolls Downhill (given by Drakuru)
I have ensorcelled choker and have followed instructions on it's use. When I use the Scepter on the blight geist while wearing the disguise, the mini action bar appears to control the geist. The geist will follow me when required but will not accept the command to harvest any blight crystals.
I have tried abandoning the quest a few times but the quest will not work for me.

**Comment by fvicaria** [comment]
I am pretty sure the quest works. Please search and read previous reports on the same quest.

**Comment by fvicaria** [comment]
Done it just now on Redemption.

![image](https://user-images.githubusercontent.com/9414661/34469164-c349ed12-ef10-11e7-84dd-46e103ff8dd4.png)
