### ISSUE TITLE
[Quest] A Distraction for Akama

### ISSUE THREAD

**Issue by cathyr1** [WoWManiaUK/Redemption#2025]
This will be quite hard to explain correctly. The quest http://www.wow-mania.com/armory/?quest=10985 can sadly be skipped. I´ve completed the previous one http://www.wow-mania.com/armory/?quest=10949 and so did another player. We were out of the group, each of us solo. He took the quest http://www.wow-mania.com/armory/?quest=10985 and completed that while I was near, but without the quest. When he finishted then I wanted to do it myself but the NPC http://www.wow-mania.com/armory/?npc=18528 offered me the next quest http://www.wow-mania.com/armory/?quest=10958 so the previous one was simply skipped.

The proof is  a screenshot below that NPC offers me continue but my addon EVERYQUEST shows that the previous one is not completed.

Don´t know if that is a game mistake but all I need is to complete this quest and obtain the neck reward. I´m afraid the only way now is that GM gives me that quest manually and complete it for me or some fix that will turn the quest offered by NPC to the correct one.
![obr](https://user-images.githubusercontent.com/30184491/34470778-904a3ee8-ef39-11e7-93bf-268ff6e5258d.png)

**Comment by fvicaria** [comment]
Well, try again after NPC has reset. You should have done as a group. Now you will have to wait for NPC to reset. Re-open issue if you still have a problem.

**Comment by fvicaria** [comment]
NOt sure what happened to you but this just works for me.
Ask a GM to remove the previous quest and add it back.  Go deliver it and it should work.

![image](https://user-images.githubusercontent.com/9414661/34471341-c0cf78e4-ef3e-11e7-96b6-e981dc841271.png)

**Comment by roleplay1** [comment]
The  q is as rewarded in the  questlog that is probaly he can't take

**Comment by fvicaria** [comment]
obviously.
