### ISSUE TITLE
[Spell] Being feard by DeathCoil even tho Berzerk

### ISSUE THREAD

**Issue by Kurioss** [WoWManiaUK/Redemption#2026]
While i was doing pvp i was wondering how i got feared all the time even tho i had berserk on. Because my Berserk is supose to remove and make me immune to all fear effects for the time duration.

![berzerk](https://user-images.githubusercontent.com/33106831/34471215-bfbd64de-ef43-11e7-8341-7c2d81d6c8a7.png)

but as you can see, i have used my berserk on this picture and i still get fear.

![feared](https://user-images.githubusercontent.com/33106831/34471219-da7bd6ac-ef43-11e7-98ec-c0ca60c59685.png)

and here is the Death Coil saying causes the enemy target to run in Horror! which in my opinion is fear. or am i wrong?

![deathcoil](https://user-images.githubusercontent.com/33106831/34471238-3d5c0a6c-ef44-11e7-9fe6-fb3698fcfd38.png)

**Comment by Keader** [comment]
Death coil is not a fear.
Is a horror effect, berserk make you immune to fears...
Is not a bug :)
