### ISSUE TITLE
[Quest] Bitter Departure (Part 2 of 2)

### ISSUE THREAD

**Issue by LilWeirdOne** [WoWManiaUK/Redemption#2027]
After picking up the second part of the quest, you are asked to lead Injured Goblin Miner to K3. However, once he's prompted with the "i am ready..." He does not followed.

**Comment by fvicaria** [comment]
I have just done the quest and it works fine.
![image](https://user-images.githubusercontent.com/9414661/34482387-94542b40-efaf-11e7-8937-7264447e81fa.png)
