### ISSUE TITLE
[Trial of the Crusader] Anub'arak

### ISSUE THREAD

**Issue by GMWeeble** [WoWManiaUK/Redemption#2028]
Attempting the last boss for Trial of the Crusader "Anub'Arak" and failing will remove all Heroic attempts from 50/50 to 0/50. It looks like the players are still targetable by Anub'Arak when they are dead and he keeps reseting over and over quickly until he reaches 0 attempts and then despawns.

**Comment by fvicaria** [comment]
Duplicate
