### ISSUE TITLE
[NPC] Blackheart The Inciter

### ISSUE THREAD

**Issue by sarahsmiles21** [WoWManiaUK/Redemption#2029]
Was with a guild group doing Shadow Labyrinth. At Blackheart the Inciter, we found he would randomly despawn, and respawn at full health. We tried 3 times to kill him, same results...each time it happened randomley, one time we had him down to 30k health, another, within a minute after pulling him

**Comment by fvicaria** [comment]
These bosses are not made for level 80s if you over dps they skip phases and may bug.

**Comment by sarahsmiles21** [comment]
Just so you no....the group was 68-77

**Comment by fvicaria** [comment]
Should be OK now.
