### ISSUE TITLE
[Talent/Buff] Rampage and Leader of the pack

### ISSUE THREAD

**Issue by Kurioss** [WoWManiaUK/Redemption#2030]
I have been very curious about Leader Of The Pack and Rampage, I play feral druid all day everyday and i love it. But its frustrating when people gain more dps because some buffs stack when they shouldnt. Like Rampage and Leader of the Pack. when i play my feral i only gain the Leader of the Pack buff which is 5% increased crit chanse, while warriors and paladins gain both Leader of the Pack and Rampage. which is 5% crit chanse with from both buffs (10% total increased crit chanse). i think this is alot and not fair aspecially for me as a fearl thats already a weak class on this expansion. could you please look in to it and maybe fix it or atleast let ferals also gain both buffs, so it becomes a fair and equal stat for everyone.

Thanks :)

23% crit without leader of the pack or rampage.
![image](https://user-images.githubusercontent.com/33106831/34491450-bd398c56-efe3-11e7-95a8-ea1c2e57745a.png)

28% crit with leader of the pack and without rampage. (5% crit increased from one buff)
![image](https://user-images.githubusercontent.com/33106831/34491464-ce9841cc-efe3-11e7-93b6-38c85e5bb14a.png)

33% crit with both leader of the pack and Rampage. (10% crit increased from both buffs)
![image](https://user-images.githubusercontent.com/33106831/34491580-4399fbfa-efe4-11e7-94da-6401e2f5f04a.png)

not in party with anyone got 52%crit (no leader of the pack or Rampage not in group with anyone)
![image](https://user-images.githubusercontent.com/33106831/34491605-5efeba8e-efe4-11e7-9f6f-57b7adf1f4e6.png)

Currently in group with warrior, still 52% crit (still dont gain any rampage buff)
![image](https://user-images.githubusercontent.com/33106831/34491658-8fbff84a-efe4-11e7-8d84-9252bc82daf1.png)

Now 70% crit gain 5% crit from leader of the pack and 3% from agility bonus from Cat from.
![image](https://user-images.githubusercontent.com/33106831/34491690-b4444c3e-efe4-11e7-80eb-a399a25353e3.png)

still dont gain the extra 5% from rampage like other classes do. :(

**Comment by Kurioss** [comment]
i have also tried with other classes like Death Knight, Shaman, Hunter, Paladin, Warrior ofc, and even mage....

**Comment by Keader** [comment]
Hello my friend.
It's a bug. Leader of the Pack and Rampage should not stack. Independent of class.
i will take a look on it more soon possible.

**Comment by Keader** [comment]
Fixed in dev :)
