### ISSUE TITLE
Redundant.

### ISSUE THREAD

**Issue by Wardoc** [WoWManiaUK/Redemption#2033]
My testing metohology was flawed.

**Comment by fvicaria** [comment]
I am sorry this has been fixed and confirmed recently. So unless you provide a lot more info than a single image I am not looking into it again.

**Comment by Wardoc** [comment]
Yes the hits have been fixed not the lack of the damage aura.

**Comment by Wardoc** [comment]
different issues

**Comment by Wardoc** [comment]
What would you want me to provide? http://wow-mania.com/armory/?spell=51690 says "and increasing all damage done by 20% for the duration." and its doing as much as my weapon damage, instead of 20% more, it shouldn't even be possible to hit 0.6k with the 20% buff.
