### ISSUE TITLE
[Item] Scarab Bag

### ISSUE THREAD

**Issue by cathyr1** [WoWManiaUK/Redemption#2034]
I hope I´m doing right by creating new issue (if not, I can reopen the previous one). You have recently fixed an object in issue #2005 so the Scarab Coffers are now inside Ruins of Ahn´Qiraj. However, these coffers do not contain the item that is necessary for completing class quests. This missing item is http://www.wow-mania.com/armory/?item=21156#contained-in-object. It should have 100 % drop. I had 6 keys and opened 6 different coffers with no drop of this item.

**Comment by fvicaria** [comment]
They won't unless you have the quest.

**Comment by cathyr1** [comment]
Thanks for quick response. I´ll go now pick the quest and try it again.

**Comment by cathyr1** [comment]
OK you were right, the scarabs now drops even from normal mobs. So you can close this issue. Thanks for your help.
