### ISSUE TITLE
[Quest] The Scepter of Celebras

### ISSUE THREAD

**Issue by NightSeekerr** [WoWManiaUK/Redemption#2035]
Quest takes place in Maraudon dungeon. 
Questgiver: http://www.wow-mania.com/armory/?npc=13716
Quest: http://www.wow-mania.com/armory/?quest=7046

When you accept the quest the NPC should start doing a ritual. However, that does not happen. Instead the NPC tells you: "If you wish to restart the ritual, please abandon our first attempt and then speak to me again." You abandon the quest, reaccept it and same thing happens.

I use the Launcher.

**Comment by fvicaria** [comment]
I will check this one.

**Comment by fvicaria** [comment]
Do NOT use link from other servers please.

**Comment by NightSeekerr** [comment]
Sorry but that's the database I use the most because it always pops up on google and is the most accurate I've used. I didn't even know it was a server. Also in wowhead.com there isn't a link for this questgiver and in this quest doesn't even exist in the armory data base.

**Comment by fvicaria** [comment]
Can someone confirm this in dev please.
