### ISSUE TITLE
[Spell] Sapphiron's Life Drain

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#2036]
Hello,
I'd like to report Sapphiron (http://www.wowhead.com/npc=15989) not casting his Life Drain http://www.wowhead.com/spell=28542 as intended.
Note, I tested only 10man so far, I can't speak for the 25man version.

How it should work: Life Drain should be cast in every ground phase (every ~24seconds if you can believe old guides), on 2 targets (10man mode) or 5 targets (25m).
How it works right now: Sapphiron casts Life Drain for the first time on 3 targets on 10man mode (instead of the intended two), but then he never casts it again through the entire fight.

**Comment by Keader** [comment]
i will take a look tomorrow.
ty for your report 👍

**Comment by Keader** [comment]
Fixed
