### ISSUE TITLE
[Quest] Sorlof's Booty

### ISSUE THREAD

**Issue by GMWeeble** [WoWManiaUK/Redemption#2039]
Quest " http://wow-mania.com/armory/?quest=11529 " Using the cannon to kill Sorlof does not work. 
Issue seems to be that the veiwdistance/phasedistance/whateverdistance is to short to see and get kill credit for him. So in other words you cannot see him to and kill him with "The Big Gun" From the boat

**Comment by goldfingyr** [comment]
You can "fake" it this way: Fly to the target area (where the ship makes its stops) and locate Sorlof. Then enter the ship and fire like crazy. Sorlof will likely die, but you wouldn't know as you can't see it. Get on shore before the ship leaves the last stop and search for Sorlof. Loot him to lessen the respawn timer. wait for him to disappear. On the ground, previously hidden under his corpsm you should now find a golden pile. That will be his bounty. Loot it and be happy.
