### ISSUE TITLE
[Quests] [Get the Message] and [Capture More Dispatches] in Icecrown

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#2040]
I have tried doing both [Get the Message] (1) and [Capture More Dispatches] (2), which have the same objective and take place in Icecrown. After taking a bit of time trying to find the enemies (which are actually flying...), I managed to shoot one and the body fell down. I followed the body to the ground and then 2 scenarios can happen. 

1. If the body falls from too high up and I'm too slow to go click it on the ground it simply disappears and I have to go back up a little to make it 're-fall'. 
2. If the body falls from lower or if I'm fast enough, I get to click the body as if to loot it, but nothing actually happens. I don't get any item or credit towards the 6 dispatches required in order to complete the quest. 

Am I doing something wrong or is there something not working with the quest?

Thanks for your help,
Oganku

References:

(1) http://www.wowhead.com/quest=13314/get-the-message
(2) http://www.wowhead.com/quest=13333/capture-more-dispatches

**Comment by fvicaria** [comment]
Corpse decay time increased.

**Comment by WhitephoenixTheBunny** [comment]
I toke both quest, i could make at the same time, i didnt need loot mob, they will count as "capture" after the corpse vanish, and it vanish in 5 sec, if the fall its to high, it will vanish in the fall, on the last one, the corpse was "glitched" and felt 3 times until it count for the quest.

**Comment by fvicaria** [comment]
If it counted that is what it is. If you can complete it is fixed.

**Comment by fvicaria** [comment]
![image](https://user-images.githubusercontent.com/9414661/34641607-808af13c-f2fe-11e7-9fd5-a2b03630a9b6.png)
You just need to approach the corpse.
