### ISSUE TITLE
[Spell] Hunter's Deterrance

### ISSUE THREAD

**Issue by Ashamedlol** [WoWManiaUK/Redemption#2042]
Spell: http://www.wow-mania.com/armory/?spell=19263 

Issue: Functions randomly in PvP, never works on Bosses in PvE (Always get hit even though you're supposed to have 100% parry and 100% deflect) and is important in both (Lich King Vile Spirits soaking  or Distraction Shot -> Deterrence in PvE -- Surviving in PvP).

Proof of Dysfunction:
![sxob-ybitdceb4l5islq6w](https://user-images.githubusercontent.com/16576459/34595420-7c1bc118-f1e0-11e7-8df9-80e13b553c82.png)

**Comment by VA-L** [comment]
![image](https://user-images.githubusercontent.com/11377592/34613931-f5749ae0-f22f-11e7-98e7-6f9d8652d84c.png)

You do know that you learn to parry things from the class trainer ?
If you don't learn it, you'll not be able to parry anything.

**Comment by Ashamedlol** [comment]
![ywmopik5ri6jl2hx63vnfq](https://user-images.githubusercontent.com/16576459/34614469-48618dee-f23a-11e7-9bf6-6596bd27c2b9.png)

Doesn't explain it. try the Vile Spirits from Lich King as well please :).

**Comment by Ashamedlol** [comment]
Before Deterrance:
![mwl4a588soydzny7sooj3w](https://user-images.githubusercontent.com/16576459/34614910-b59e310e-f23b-11e7-8390-efb17f68776f.png)

During Deterrance:
![7pntbmq2reqxxjy3ey1d2g](https://user-images.githubusercontent.com/16576459/34614998-f01ce1cc-f23b-11e7-96bd-a9c753078139.png)

It's increasing the parry chance by 90%, not 100%.

**Comment by VA-L** [comment]
> Doesn't explain it. try the Vile Spirits from Lich King as well please :).

Detterance doesn't give the ability to parry/dodge/deflect aoe spells.

> It's increasing the parry chance by 90%, not 100%.

95% is the cap for the client, the visual % will not show anything higher than that even though it's considering that you have 100%. (Try with only 1% or even less Parry %, it's still gonna show 95%).

**Comment by Ashamedlol** [comment]
Doesn't seem to be working on the single-target part for me then, could you try a 5man level 80 dungeon boss if possible? It only works on normal NPCs for me.

**Comment by Ashamedlol** [comment]
Also, at the same time, it shouldn't be parrying or dodging from the back since you can only dodge or parry frontal attacks.

**Comment by VA-L** [comment]
> Also, at the same time, it shouldn't be parrying or dodging from the back since you can only dodge or parry frontal attacks.

![image](https://user-images.githubusercontent.com/11377592/34619149-7a120d94-f241-11e7-89d8-4c3fd3f7908f.png)

**Comment by VA-L** [comment]
![image](https://user-images.githubusercontent.com/11377592/34619341-1a08066e-f242-11e7-8f87-21194b73c417.png)
And for this part, i believe you only get hit by the knock back effect from the spell and not by the physical effect (Bone Slice from Marrow which is a pure melee damage spell gets parried).

**Comment by Ashamedlol** [comment]
I tested it again:
Aggro Attempt 1: I walked to the boss and used Deterrance, I parried and dodged everything.
Aggro Attempt 2: I attacked the boss with Serpent Sting -> Chimaera Shot, then used Deterrance, he hit me with everything.

It has something to do with attacking, it seems.

**Comment by Ashamedlol** [comment]
Deterrance after attacking:
![sy9sbgimtjo6dczezy7xda](https://user-images.githubusercontent.com/16576459/34639673-1fc43036-f2ed-11e7-9372-a9b6254f20f3.png)
Deterrance without attacking (walking to boss, aggroing then Deterrance):
![wdxdqyhotvgsocbxp6gnra](https://user-images.githubusercontent.com/16576459/34639679-35122ce0-f2ed-11e7-8334-810df11263d2.png)

**Comment by Ashamedlol** [comment]
And about AoE, if it's Environmental such as Consecration, Death and Decay and Toxic Waste, it goes through Deterrence but channeled spells DO NOT go through it (such as Vile Spirits).
![l_0eolemrlkvsvwruecsdw](https://user-images.githubusercontent.com/16576459/34639803-9f1b329c-f2ef-11e7-9368-46ee388cda35.png) (Ick's Explosive Barrage from PoS, Toxic Waste goes through which is intended).

![erq2k0pzrtsprydfamkeag](https://user-images.githubusercontent.com/16576459/34639807-bcd490c6-f2ef-11e7-9b5a-c0cc13dd8d64.png) (A Hunter's Volley.)

**Comment by HDArokh** [comment]
Im confirming also deterrence not working properly , hunters in retail were able to taunt the boss with distracting shot and right after use deterrence to survive approx 5-10 second depending from how far away the distracting shot is made. but in WoW-Mania Redemption it is not working. Heres some screenshots from combat log from my alt hunter Keirah on LK10hc fight.

first picture as like VA-L tested on Lord Marrowgar , not doing anything just using deterrence and it works but why would hunters use deterrence on start of fight when theres no emergency to taunt the boss? 

![only dete](https://user-images.githubusercontent.com/35156397/34645824-0fb95068-f360-11e7-86a3-138a4ec28f81.PNG)

Next Picture however from normal Mid combat situation fight when everything goes ok untill u actually have to taunt the boss and u have dealt damage to the boss. the deterrence aint working for some sudden reason. 

![shoot and dete](https://user-images.githubusercontent.com/35156397/34645845-a15d09ce-f360-11e7-9bf8-4e8f0b2cfc26.PNG)

So it is clear it is not working properly. Also to confirm that hunters were used as Emergency taunter's for boss fights here's video from World first LK25hc kill from Paragon. Paragon is a finnish guild and im also a Fin so lemme translate u what they say inside last frostmourne room phase and u can see that Boss berserk timer goes off. Translation from time 16:45 - 17:10 video time.
https://www.youtube.com/watch?v=RSeVCw3hVgQ

käytä auramastery iha varmuude vuoks = use auramastery just in case

auramastery pääl = auramastery used , and right at same time u hear this wich is not translated in the video. -----> Se tappaa kuplan läpi sitte = u know it kills trough Paladins bubble then.

kuka tauntaa ???? = Who taunts then ?? 

hunu tauntaa = Hunter taunts

( raid grp 5 hunter third from top ) Usso tauntaa , Usso tauntaa = Usso taunts, Usso taunts

Viis = 5 seconds

Minä tauntaan! = Usso confirms and says -> I TAUNT!  

after they get out Usso is using Distracting shot and  deterrence to  taunt and '' tank '' the boss without any problems  for the last 7-12 sec untill LK starts final roleplay.

Hope this info helps.

**Comment by Ashamedlol** [comment]
Bump incase it was forgotten, it's still broken.

**Comment by VA-L** [comment]
> Bump incase it was forgotten, it's still broken.

It wasn't forgotten, i've made some deep tests about it.
I've made a fix.

Up to test.
