### ISSUE TITLE
Reins of the Crimson Water Strider

### ISSUE THREAD

**Issue by WhitephoenixTheBunny** [WoWManiaUK/Redemption#2044]
This mount, Reins of the Crimson Water Strider, http://www.wow-mania.com/armory/?item=87791, should be avaible to walk on water, but it doesn't work. I used it at SW entrance, non-battelgound area.
![wowscrnshot_010518_140831](https://user-images.githubusercontent.com/31921098/34612557-5009238a-f222-11e7-888d-3f40c30a7bd9.jpg)

**Comment by fvicaria** [comment]
As is. All imported mounts don't necessarily work as they do in the later clients. They work as normal wotlk mounts.
