### ISSUE TITLE
[NPC] Earthmender Wilda

### ISSUE THREAD

**Issue by sarahsmiles21** [WoWManiaUK/Redemption#2045]
Cannot interact with this NPC to take her quest. She is in a pool of water at the back of Coilskar Cistern, i don't know if thats her proper location, but when i swim down to here, canot talk to her. a comment on wowhead suggested killing The Keeper of The Cistern,which I did, but with no change. I exited the game, deleted cache and relogged, still could not interact with her.

http://www.wowhead.com/npc=21027/earthmender-wilda

**Comment by VA-L** [comment]
- NPC moved to her correct position.
- You can now interact correctly with her.
- Added a security.

Up to test.

**Comment by squalllh1989** [comment]
Npc is tested and interactable now.
![wowscrnshot_010618_153528](https://user-images.githubusercontent.com/27235989/34638286-ec5d24a6-f2fa-11e7-9c3e-cf3ecc24fc1e.jpg)
![wowscrnshot_010618_153531](https://user-images.githubusercontent.com/27235989/34638287-ef4c5a2e-f2fa-11e7-8d8c-691e98b3c692.jpg)
![wowscrnshot_010618_154905](https://user-images.githubusercontent.com/27235989/34638288-f2aa61b6-f2fa-11e7-8a34-e0ee62c34837.jpg)
