### ISSUE TITLE
[Quest] Of Thistleheads And Eggs

### ISSUE THREAD

**Issue by sarahsmiles21** [WoWManiaUK/Redemption#2046]
The eggs you're supposed to open are non-interactable. I exited, deleted cache, and restarted. same result.

http://www.wowhead.com/quest=10547/of-thistleheads-and-eggs

**Comment by VA-L** [comment]
Also, keep in mind that you need to find the right egg to complete the quest :)

**Comment by sarahsmiles21** [comment]
TY, and yeah..i know the chain well! Appreciate all you do :)

**Comment by VA-L** [comment]
> UpDate: As of this posting, the eggs are still not interactable. i abandoned and retook the quest with the same result. if the above comment wasnt direct at me, please disregard.

This is fixed in the PTR at the moment, not on Redemption.

**Comment by squalllh1989** [comment]
Fix confirmed to be working on dev.
![wowscrnshot_010618_152846](https://user-images.githubusercontent.com/27235989/34638159-9dcd8116-f2f8-11e7-9bd2-b10067a67244.jpg)
