### ISSUE TITLE
[NPC] Neltharaku

### ISSUE THREAD

**Issue by sarahsmiles21** [WoWManiaUK/Redemption#2048]
Neltharaku randomly despawns. I used /target Neltharaku to find him, when I finally did, he despawned 3 times before i could finally talk to him. 

http://www.wowhead.com/npc=21657/neltharaku

**Comment by fvicaria** [comment]
It is there and it does not despawn, it just keeps moving. If you don't initiate the dialog in time he is gone.
![image](https://user-images.githubusercontent.com/9414661/34637940-e0b7ccf6-f2b8-11e7-86c1-cae9592c3e66.png)

**Comment by squalllh1989** [comment]
well what happen is you /target Neltharaku and found him while both you and he is still moving, after 3 sec he go out of the /target range (out of your sight) then you lost your target at him, not that he despawn.

**Comment by fvicaria** [comment]
The NPC will stop if you start the dialog. Same way I did in the image.
