### ISSUE TITLE
[Spell] Glyph of Felguard

### ISSUE THREAD

**Issue by Nagasraka** [WoWManiaUK/Redemption#2049]
The attack power bonus from the Glyph of Felguard http://www.wow-mania.com/armory/?spell=56246 is not applying the bonus from the glyph to my pets attack power.

Screenshot with no Glyph:
![wowscrnshot_010618_144906](https://user-images.githubusercontent.com/35170493/34640860-ccc482ae-f2f2-11e7-8bb6-698a8e62583c.jpg)

Screenshot with Glyph:
![wowscrnshot_010618_150510](https://user-images.githubusercontent.com/35170493/34640882-0baf5a16-f2f3-11e7-8242-7362ccf92be1.jpg)

That's a further 516 Attack Power my Felguard doesn't have on my current gear.

**Comment by Keader** [comment]
I have fix for this ready, i just need find xd

**Comment by Keader** [comment]
Fixed

**Comment by Keader** [comment]
Note for testers:

Like all glyphs, effect start when you change map or relog or summon a new pet (or summon mount/remove mount).
If you use a warlock if a full talent points, you will notice a "wrong value ( > 20% )" in attack power.
It's not wrong, glyph change base attack power amount, so it will affect other talents that give attack power too.
If you want make a clean test, with without any talent and use .cast in summon felguard spell.

In my tests, Attack Power without glyph was:  334,with glyph: 400... (334 + [334*0,2] ) = 400.8, core will truncate it back to 400.
