### ISSUE TITLE
Howling Fjord Quest "It Goes to 11..."

### ISSUE THREAD

**Issue by dandancanfly** [WoWManiaUK/Redemption#2050]
On the [Howling Fjord Quest "It Goes to 11..."](http://www.wowhead.com/quest=11421/it-goes-to-11#comments), I was unable to complete the "Dragonflayer Longhouse Destroyed" criteria, I shot the red roof on the large house on the right many times, as did my friend, and we were unable to complete it. We reached out to a GM who completed the quests for us (thanks!!!). He mentioned there were issues on this github that are marked complete, and requested I submit a new bug report. This is a screenshot from another report, but it's the same roof we fired 10+ shots each at:

![image](https://user-images.githubusercontent.com/11138461/34641295-cabb9a38-f2cf-11e7-995d-237c68d58e4b.png)

Here are the related issues, in case that's helpful
https://github.com/WoWManiaUK/Redemption/issues/1669
https://github.com/WoWManiaUK/Redemption/issues/162

**Comment by fvicaria** [comment]
Try harder it works. I have just tested. :)
