### ISSUE TITLE
[Talent] Warlock - Fel Vitality

### ISSUE THREAD

**Issue by hotdoggidy** [WoWManiaUK/Redemption#2051]
A guildie recently dual specc'd Demon/Demon in preparation of the Felguard Glyph fix. #2049 

He noticed when swapping between talents his mana pool was increasing over and over again. After checking the specs, Fel Vitality (http://wow-mania.com/armory/?spell=18744) seemed to be the only overlapping mana effect possible as they were in both specs when he swapped. 

Not sure if this talent is what is causing the issue. Just thought it would be a good starting point.

Video of guildie showing me the mana bug.
https://youtu.be/yeC6EMFIHn0

**Comment by Keader** [comment]
i have a fix for this too o.o

**Comment by Keader** [comment]
fixed
