### ISSUE TITLE
Burning Blade Cultis Imp minion

### ISSUE THREAD

**Issue by Igotpooedon** [WoWManiaUK/Redemption#2052]
Hello, im doing the horde version of the fire totem quest and im trying to get the "reagent pouch" which you get from killing the Burning blade cultis which are located in a cave north from Razor hill in Durotar.
Their Imp minions have at lvl 10 1.1k-1.5k hp and 2.6k-3k mana and hit for like 50 damage which is ALOT at this lvl. 
Clearly this is a bug .

//Anton

**Comment by TheManiax** [comment]
Please follow the procedure described below before creating a new issue:
[How to Properly Report an Issue](https://github.com/wow-mania/Redemption/wiki/How-to-Properly-Report-an-Issue)

This will help developers identify and fix the issue quicker. Incorrectly or unclear reports will simply be deleted.

**Comment by squalllh1989** [comment]
Please at least place a link to the quest you are doing, at the very very least, the quest 's name.
