### ISSUE TITLE
[Spell] Exorcism and [Talent] Art of War

### ISSUE THREAD

**Issue by Magabro** [WoWManiaUK/Redemption#2053]
Hello,

Currently, Paladin spells Exorcism and Flash of Light which are cast instantly (0s cast time with Retribution talent Art of War) are resetting the melee swing timer.  When these spell are cast instantly the melee swing timer should not reset.

Sources:
http://suicidalzebra.blogspot.com/2009/02/undocumented-31-info-and-question.html
https://github.com/TrinityCore/TrinityCore/issues/1765

To recreate this issue:
1) Make a Paladin with Art of War Talent
2) Start attacking a target dummy (preferably with a very slow weapon to help see the issue) and note your attack speed
3) Wait for Art of War to proc from a melee critical strike
4) Cast instant Exorcism or Flash of Light (consuming the Art of War proc) and watch for you melee swing.  You will see the next swing after the cast is delayed because your melee swing timer is reset.
5) Use other Paladin instant cast spells in the same fashion such as Consecration and notice they do not reset the melee swing timer

**Comment by fvicaria** [comment]
Any reference must be from Blizzard or at most WoWHead.com the one you sent has no credibility and no mention if he was talking about a beta or a released version.

**Comment by Keader** [comment]
fixed

**Comment by TheManiax** [comment]
I didn't confirm the bug at the first place
But if it was really, Then it is fixed on Dev at the moment
