### ISSUE TITLE
[Raid] Auto mute in raid

### ISSUE THREAD

**Issue by squalllh1989** [WoWManiaUK/Redemption#2054]
You must have know that almost in all raid, especially pug raid, masterloot is used to distribute loot, and to make it faster and more clear, some addon can be used, like musou's loot tracker has a function of raid rolling blind on equipped item, it anounce which number raid members is, then roll a random number between, allow raid leader to raid roll clear and fair to everyone (example: in a 10 man raid, raid member given number 1 to 10, then roll 1-10, if it rolled 3, the person given number 3 will get the item). This was make it so easy and fast before, lessen the stress of leading a raid, but not anymore, for recently there is change in the system that will mute you if you do more than 3 line of raid warning, and you must wait 30 sec to talk again. I don't know what purposes this change is for, but it is sp much anoying to do masterloot if you tense to do it fast to push on the raid. Therefore, i make this topic here, wish for a change in the system that can make it back like before, or at least make the restrictions conditions 3 times more than now (at the moment you will get 30s mute if do more than 3 line of raid warning, please at least make it so you get mute 30s if do more than 9 line of raid warning in 10-15s. To be honest, raid leader or asistant is the raid's guide, they must chat and anounce a lot, so mute  because they anounce something should not been done in the first place.
Sincerely.

**Comment by fvicaria** [comment]
I don't understand what you are asking.
What changed exactly?
As far as I know nothing changed in this area.

**Comment by squalllh1989** [comment]
Well, before, when used the addon, i can state you all 25 people with the number before rolling, example:
**[Raid warning]#1: person A, #2: person B ...etc... to #25 person Z** these list is split into diffrent line continiously and anounce in raid warning, then after that the addon will do a roll 1-25, so everyone in the raid know which is their number, and who win after the roll.
But now, it didn't work anymore, because i can only auto state out to #8 which is line 3 to max, then you got muted and can't talk for 30 sec. If there is nothing change in this area, then maybe it's a side bug or effect from some change
Well i will try to provide a screenshot of this problem so it will be easier to understand

**Comment by fvicaria** [comment]
Addons get corrupted with time.  Delete all and res-install. We have not changed anything that would cause that.

**Comment by squalllh1989** [comment]
well that's not a problem with addon, because not only me but other people have that too, they got muted after 3 line of raid warning and have to wait 30 sec to be able to chat again. Usually that mute isn't a big problem and it can use to prevent spam, but it become anoying when you are masterlooter and doing loot distribution

**Comment by fvicaria** [comment]
OK this may be the flood warning. It blocks you if you send to much stuff on the channel
I will fix this. This is config not core. I will close this. It will be fixed in the next hour in Redemption.

**Comment by squalllh1989** [comment]
Thank you very much, it will be much more comfortable.

**Comment by fvicaria** [comment]
Delete cache and re-try please. It should be OK now.

**Comment by Unstoppablee** [comment]
For example before you could link Recount for top 10 dps, and you don't get muted. 
In last 2 months you are getting muted after 4 - 5 lines of text. Basically you can link top 4 - 5 dps, and get muted for 30 sec. 
Will test it tonight to confirm is it working fine now. 
Thank you.

**Comment by fvicaria** [comment]
This has been fixed this week.
