### ISSUE TITLE
[Shapeshift][Druid] Tree of Life powershifting 

### ISSUE THREAD

**Issue by Hajzlopuc** [WoWManiaUK/Redemption#2056]
Hello,

powershifting in a druid's Tree Form [ID 33891](http://www.wow-mania.com/armory/?spell=33891) currently does not remove any slows and roots. Powershifting in any other form (Bear [ID 9634](http://www.wow-mania.com/armory/?spell=9634), Cat [ID 768](http://www.wow-mania.com/armory/?spell=768), Travel [ID 783](http://www.wow-mania.com/armory/?spell=783)) works as intended and removes slows and roots properly.
While I was testing that, I also found something that might help you investigate the issue. The thing is if I powershift in any form except Tree Form, it shows in combat log that the buff is refreshed (buff fades, then its gained again at the same time) but when I powershift in Tree Form, buff just stays on me and it's not technically reapplied.
https://puu.sh/yWdcj/10db17fd0c.jpg

How to powershift?
Make a following macro (exclamation mark is important):
`/cast !Tree of Life
`

**Comment by fvicaria** [comment]
do not use macros as a way to reproduce any issue.
We do not "have to" support any macros at all.

**Comment by Hajzlopuc** [comment]
But it's not about macro, it's about spell itself. And the only way how to powershift is with macro because of blizzard's desing. How come that Bear, Cat and Travel powershift macros work and the Tree one does not work.

**Comment by Keader** [comment]
Is not...
Spell without macro works fine to me xD

**Comment by Hajzlopuc** [comment]
Yes because you cannot powershift without macro.
Okay if I make a fix by myself would you implement that?

**Comment by fvicaria** [comment]
Feel free to suggest one. The spell works it has been tested.

**Comment by Keader** [comment]
https://github.com/TrinityCore/TrinityCore/commit/57672fdf259d1106420e6a2c91f6f1b65b00fbc9

**Comment by Hajzlopuc** [comment]
Works now. Thank you!
