### ISSUE TITLE
Item lost its 2h resell/trade without reason, and becomes non-interactable

### ISSUE THREAD

**Issue by Arkhirion** [WoWManiaUK/Redemption#2057]
Item was Venerable Dal'Rend's Sacred Charge.

The item in question had 1h58 minutes left to be sold to a vendor for it's full price when I logged off for some chores, though when I logged back in later that day, that time limit was removed. 

Going back to a vendor to sell it, due to changing my mind, resulted in the item becoming non-interactable. I could not move it, equip it, or buff it (via enchants or poisons or what not). Hovering over it only sometimes showed its' tooltip.

I had a chat with a GM who told me to report this issue to this website, so here it is.
Though due to privacy reasons will not state its name.

**Comment by fvicaria** [comment]
None of the items bought with MP are refundable after you logout. The game just not understand that and it will not hold the information. You log out you lose it.
This is only respected for the original NPC and currency which in this case was honor.

**Comment by Arkhirion** [comment]
I can make peace with the fact that it loses its refundable status upon logging out. 

However there's a second problem regarding it, where the item became inaccesable after trying to sell it. which is mostly what I wish to address.

**Comment by fvicaria** [comment]
I will check that.
