### ISSUE TITLE
[Quest] The Cudgel of Kar'desh

### ISSUE THREAD

**Issue by cathyr1** [WoWManiaUK/Redemption#2058]
Hello! It is impossible to obtain the quest http://www.wow-mania.com/armory/?quest=13431 atm from the NPC http://www.wow-mania.com/armory/?npc=22421. It was available some time ago when Nightbane was bugged but now when is possible to kill dragon, this quest cannot be obtained as it is marked by grey questionmark.
![aa](https://user-images.githubusercontent.com/30184491/34651385-f647644c-f3cf-11e7-8a05-51a1c8c65479.png)

**Comment by fvicaria** [comment]
The error is that the quest is available. It has been deprecated.

The correct version is: http://www.wowhead.com/quest=10901/the-cudgel-of-kardesh

**Comment by cathyr1** [comment]
You mean the quest should be no longer in the game even in WOTLK? I though it was removed in Cata.

**Comment by fvicaria** [comment]
This is the correct version
http://www.wow-mania.com/armory/?quest=10901
The one you mentioned is deprecated.
