### ISSUE TITLE
[Spell] Arcane Power - Presence of Mind

### ISSUE THREAD

**Issue by MagikG** [WoWManiaUK/Redemption#2059]
### There are **2** issues with these spells:

**1**- When I press Arcane Power my Presence of Mind goes on 10 seconds cooldown for no reason.

**2**- When I use Presence of Mind I can't use Arcane Power.

Since Arcane Power got no casting time, and is not even a damaging spell, it's a buff, is looking like Presence of Mind is treating Arcane Power like he got more than 10 secs casting or something close to it.
I hope you can fix it, keep the good work !

**Comment by Hajzlopuc** [comment]
Intended.
https://us.battle.net/forums/en/wow/topic/2522162857

**Comment by fvicaria** [comment]
@Hajzlopuc:  If you are interested to join the test team let me know on Skype.

**Comment by MagikG** [comment]
It's not intended, since in that topic was not answered by any GM confirming that.
Why can't you use two spell together when they are talent dependent, Arcane power is already instant don't need Pom to use anyway, if they were mutual CD you could just use one of them and not 10 sec from each other, this makes no sense.

**Comment by Keader** [comment]
Yes, is intended.

Arcane Power:

> CastingTime (Id 1) = 0,00
> RecoveryTime: 120000 ms, CategoryRecoveryTime: 15000 ms
> StartRecoveryCategory = 0, StartRecoveryTime = 0,00 ms
> Duration: ID (8)  15000, 0, 15000
> Interrupt Flags: 0x00000000, AuraIF 0x00000000, ChannelIF 0x00000000
>   Ex Caster Aura Spell (12043) Presence of Mind

Presence of Mind:

> CastingTime (Id 1) = 0,00
> RecoveryTime: 120000 ms, CategoryRecoveryTime: 1500 ms
> StartRecoveryCategory = 0, StartRecoveryTime = 0,00 ms
> Duration: ID (21)  -1, 0, -1
> Interrupt Flags: 0x0000000C, AuraIF 0x00000000, ChannelIF 0x00000000
>   Ex Caster Aura Spell (12042) Arcane Power


Se last line in both cases...
Ex Caster means: Spell cant be used or hit a target with XXX aura

**Comment by squalllh1989** [comment]
http://www.wowhead.com/spell=12042/arcane-power#comments

By ShiroMage (562 – 4·6) on 2009/02/11 (Patch 3.0.9) |   |  
As of 3.0.9, the Arcane power tolltip now says that damage is increased by 20%, and mana cost increased by 20%.

This spell also has a shared CD now with PoM, as said above.

Once AP is used, a 15 second CD will be set on PoM.
