### ISSUE TITLE
[Boss] Gothik The Harvester invisible adds

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#2060]
Hello,
I'd like to report a bug with adds transferring between the two sides when fighting Gothik The Harvester(http://www.wowhead.com/npc=16060).

During the phase1 of the fight, when adds are spawning, Unrelenting death knights (http://www.wowhead.com/npc=16125) spawn properly on the Living side, but when you kill them, they don't appear visible on the Undead side. They should spawn as Spectral Death knights (http://www.wowhead.com/npc=16148) on the other side, and should be killed again.
What happens instead is that you see their beams landing on the undead side, with no add spawning underneath, and a phantom damage begins hitting one of your raid members on that side a few seconds after.
So basically they are there, they aggro and attack a chosen target and hit quite hard (5-10k on cloth), but you cannot see them, cannot target them, their damage does not show up on Recount or combat log.
The only sign of them being there is the phantom damage coming out of nowhere on a certain character, even though there are no adds up. Clothies tend to die, and the damage they take according to the death log does not match the amount their health values fall, as shown on the screenshot below:
https://imgur.com/mJUfAXq
On this you can see the mage Xori's health go from 10k to 0 over 1,17 seconds without any other incoming damage than 2x~500 from the small adds' Arcane Explosion. It doesn't add up. 

I took a while to identify the source at all, but as there are not a single Spectral Death knights attackable during the whole fight, those invisible NPCs can only be them. The phantom damage begins every time after Wave4 (the first wave with Knights) and always on the Undead side and lasts until Gothik is killed and encounter is over. Luckily, it appears that only those aggro to your raid which land relatively close to the group, so if you don't move around there will be only 1 or 2 knights murdering your casters, instead of all of the bugged spawns.

**Comment by Dranah** [comment]
I found another mob which does not appear on the Undead side, it is the Spectral Rider (http://www.wowhead.com/npc=16150) spawned after Unrelenting Riders. 
Each Unrelenting Rider http://www.wowhead.com/npc=16126) from the living side should spawn as a separate Spectral Horse http://www.wowhead.com/npc=16149 and Spectral Rider on the dead side, but only the Spectral Horses are coming over properly at the moment. 
The Spectral Rider also seems to be there invisibly as the knights I reported above , and these can be damaged by reflective dmg, such as Retribution aura, so I found them on Recount as that, even though they weren't present during the fight (weren't visible that is), and did not take damage from any other effect than the Retribution aura on the priest they melee'd.
Oddly, the knights I reported above weren't even damaged by that.

**Comment by Keader** [comment]
i cant reproduce it.
All npcs is visible to me.

**Comment by Keader** [comment]
New info: "this issue only happens in 25 man".
Need a new confirm.

**Comment by Keader** [comment]
Fixed :)
