### ISSUE TITLE
Shamans improved Windfury Talent not working.

### ISSUE THREAD

**Issue by Vucko88** [WoWManiaUK/Redemption#2061]
Shamans ability Windfury totem says in Mania-Armory that it adds 16% mele haste. [[spell=29193]](url)
And in Enhance talent tree is talent that adds 2x2% = 4%, [[spell=29193]](url) speed increase on Windfury Totem.
Getting in total Windfury totem to speed up mele haste by 20%. 

However, when windfury totem is droped/activated on ground, and you mouse over on your buffs (uper right corner near map, it says that the mele haste is improved by 16% instead of 20%.

And i was told that is just "visual bug", however after some testing ive started to think it is an actual bug.
Explanation:
My mele haste is 2x one handed weapon with speeds 2,80 and 2,80.
When totem is activated, it speeds up my mele haste to 2,33 and 2,33. 
<a href="https://ibb.co/dSCH6m"><img src="https://preview.ibb.co/jrHjmm/Wow_2018_01_08_21_13_18_34.jpg" alt="Wow_2018_01_08_21_13_18_34" border="0"></a><br /><a target='_blank' href='https://imgbb.com/'>free upload no registration</a><br />
Now doing math:
2,80 - 16% (0,448) = 2,35 
2,80 - 20% (0,56) = 2,24 - this is how much it should be when points are put in talent tree.

Also did testing with two handed weapon [item=2026] (basic, bought in SW infront of AH)
Speed is 3,70
3,70 - 16% (0,592) = 3,108
3,70 - 20% (0,74) = 2,96
But when i drop my 20% totem it speeds up my haste to 3,08(3,1) instead of 2,9
<a href="https://ibb.co/fPF1z6"><img src="https://preview.ibb.co/jks3CR/Wow_2018_01_08_21_26_25_69.jpg" alt="Wow_2018_01_08_21_26_25_69" border="0"></a>
**_now i know this bug, is like really un-important its such small difference, but still i felt i need to tell you about it._**

**Comment by Hajzlopuc** [comment]
My math says something different.
http://wowwiki.wikia.com/wiki/Attack_speed

Formula is:

Attack speed / (1 + AS%/100)

2.80/ (1+ 20/100) = 2.80/ 1.20 = 2.33
3.70/ (1+ 20/100) = 3.70/ 1.20 = 3.08

I would say it's all correct.

**Comment by squalllh1989** [comment]
Attack_speed = "current attack speed" / (("Percent increase or decrease" / 100) + 1 )
Those are work correctly.
