### ISSUE TITLE
[Item] Wolfshead Helm

### ISSUE THREAD

**Issue by iggapres** [WoWManiaUK/Redemption#2063]
This crafted item (http://www.wowhead.com/item=8345/wolfshead-helm) should have a nice special feature:

> Equip: When shapeshifting into Cat form the Druid gains 20 energy, when shapeshifting into Bear form the Druid gains 5 rage.

This never happens.

**Comment by fvicaria** [comment]
Unless you show me screenshots with you in cat form before and after you equip this and the stats no changed I will close this one also.

**Comment by iggapres** [comment]
Sorry to bother you with bug reports. I thought you wanted your server to be better...

**Comment by fvicaria** [comment]
Post how to reproduce the issue and info.
We do not go after hunches.
