### ISSUE TITLE
[Core] Fleeing Movement

### ISSUE THREAD

**Issue by Jagern** [WoWManiaUK/Redemption#2065]
Want to report the fear bug as it is really annoying, if you dont know what it is its simply, when you fear someone you cant see where they run during the fear, you see them as lagging (running in place or just completly disappearing) and then suddenly teleporting somewhere when fear ends, as far as i know this is every fear in the game. and the warrior fear, it clearly states that when feared you should stand still, but it doesent allways work like that, pets run away every time, players only some of the time,

**Comment by fvicaria** [comment]
Please follow the procedure described below before creating a new issue:
[How to Properly Report an Issue](https://github.com/wow-mania/Redemption/wiki/How-to-Properly-Report-an-Issue)

This will help developers identify and fix the issue quicker. Incorrectly or unclear reports will simply be deleted.

**Comment by Jagern** [comment]
u mean spell id's? or multiple issues ?

**Comment by fvicaria** [comment]
Can you describe how to reproduce this with clear steps, please? Maybe screenshots.

**Comment by VA-L** [comment]
- Tested lock's fear against a player not moving -> fine
- lock's fear against a player moving -> fine, sometimes he runs in place but that's for 1 sec and then, he continues the path.
- Tested a warrior charge against a feared player that didn't move -> fine
- Tested a warrior charge against a feared player that was moving before the fear -> fine
- Tested the warrior fear against a non moving player -> the player is standing still while feared
- Tested the warrior fear against a moving player -> the player is standing still too.

**Comment by VA-L** [comment]
Tested lock's fear against a player not moving -> fine
lock's fear against a player moving -> fine, sometimes he runs in place but that's for 1 sec and then, he continues the path.
Tested a warrior charge against a feared player that didn't move -> fine
Tested a warrior charge against a feared player that was moving before the fear -> fine
Tested the warrior fear against a non moving player -> the player is standing still while feared
Tested the warrior fear against a moving player -> the player is standing still while feared too.

**Comment by Midnaa** [comment]
This is a movement generator issue, try fearing and after 4s do a scatter shot on them

**Comment by VA-L** [comment]
That is a generic issue.
Happens with disoriented effects (like Scatter Shot), fear effects and even particular stun effects (like Cyclone).
The disoriented/feared **player** will have normal movements on his screen.
The **caster** of the disoriented/fear spell will see weird movements animations from the disoriented/feared **player** on his screen.
