### ISSUE TITLE
when flying erbs in the mini map dont show up 

### ISSUE THREAD

**Issue by berantheus** [WoWManiaUK/Redemption#2066]
when you look for erbs you have to be at almost ground level if your just a little ways up they don't show up at all and its even worse in the outlands and northrend you have to move 10 yards forward and wait 5 to 10 seconds to even see an erb its not like retail at all! your mini map is almost worthless for finding erbs and I noticed ore is way better so something is wrong with erbs appearing and also the erbs in northrend are so scarce on retail there are 5 to 10 times as many erbs

**Comment by fvicaria** [comment]
![image](https://user-images.githubusercontent.com/9414661/34767514-35f3c62c-f5f0-11e7-90c3-0809cc5c3fd6.png)
They do show up.
If your complaint is missing nodes in certain areas please be specific.
Also this is not retail this is 3.3.5a so I need info for the same version.

**Comment by GMWeeble** [comment]
There is a small delay for anything to spawn. Players, Nodes. That could be the issue?

**Comment by Dranah** [comment]
Yes they take longer time to show up since the delay, I noticed that as well. It makes gathering professions  painful cause if you fly too fast, you'll pass them before they appear.

**Comment by berantheus** [comment]
im talking about outlands and northrend and im saying they don't show up when your up in the air a ways also im saying theres a 10 sec delay on all erbs showing up even when your flying at nearly ground level also as far as ice crown I searched for 2 hours yesterday and found 4 erb nodes now I know this isn't retail but there should be a lot more nodes as there are 10x the amount of ore nodes

**Comment by berantheus** [comment]
I also noticed in your mini map fvicaria that your right beside the erb node and that's my point exactly! erbs should show up in the mini map quite a ways before your right over the top of them on your mini map or you will fly right over them and they will be gone before you ever see them on your map and my other point is that ore nodes are a little slow to show up but there much better to see at a distance on your mini map than erbs

**Comment by fvicaria** [comment]
As is for now. Get an addon for prospecting professions it will help. We also improved the spawn nodes. If a specific mineral/herb is not right let me know and I can check.

**Comment by ManiaLightmare** [comment]
It also helps to search close to ground level.  If you are over about 30-40 yards up, detection is far less likely.  Flying low to the ground and it picks them up at a distance better.

Using a node I already found.  Flew up until it was not on mini-map.  Then lowered to the point just before it showed.  I also sat over 10 seconds to rule out any delay.
Stationary above a node.  Not visible on minimap: [https://ibb.co/b5ogrm](https://ibb.co/b5ogrm)

Stationary above same node, but lower.  Visible on minimap: [https://ibb.co/h3XkHR](https://ibb.co/h3XkHR)

**Comment by fvicaria** [comment]
We had some unusual delays lately. We are looking into it.
You should also increase the minimap range to max and from time to time stop for a couple of seconds.
