### ISSUE TITLE
[Quest] Tirion's Gambit

### ISSUE THREAD

**Issue by Uncle1** [WoWManiaUK/Redemption#2069]
I'm doing the Quest http://www.wowhead.com/quest=13364/tirions-gambit and i searched Tirion for around of 10 minutes and i didnt found him, so i searched where is supossed to be. When i know the place of the NPC Spawn i went there and waited around of 30 minutes for him spawn. The NPC never appeared.

**Comment by Unstoppablee** [comment]
I would say make it atleast 10m. Give us some challenge. :P 
We are trying to make it as much as it is possible - Blizzlike!
