### ISSUE TITLE
[BOSS] - Valithria Dreamwalker

### ISSUE THREAD

**Issue by VA-L** [WoWManiaUK/Redemption#2071]
- Fixed an edge case that happened last night on the **first pull** of this boss where the encounter starts and there are still some players outside of the room, if those in the room died, the adds will then move to the ones outside (causes also mobs passing through walls if players managed to go to the entrance of the instance) and attack them and during all of this, they will also start attacking the NPC [Crok Scourgebane](http://www.wowhead.com/npc=33762/crok-scourgebane) and it will require a GM action because the adds will keep spawning since this NPC can't be killed, he uses [Icebound Armor](http://www.wowhead.com/spell=70714/icebound-armor) at ~10% that prevents him to die and the adds will keep attacking him anyway.

Thanks to **Magabro** for all the informations provided.

**Comment by Unstoppablee** [comment]
Thank you for fixing this finally.

**Comment by Unstoppablee** [comment]
Was in 25nm on Redemption, apparently this is working fine now. (Not sure if it update on red happened.)
Nice Job V-AL.
