### ISSUE TITLE
[Talent / Aura] Swift Retribution and Sanctified Retribution

### ISSUE THREAD

**Issue by xclaw800** [WoWManiaUK/Redemption#2073]
For the talent tree choices of Swift Retribution and Sanctified Retribution for Retribution Paladins the tooltip clearly states for Swift that “Your auras also increases casting, ranged and melee attack speeds by X%”
And for Sanctified that “all damage caused by friendly targets affected by ANY of your Auras is increased by 3%.”

The issue in game is that the effects will only work if the paladin is on Retribution aura when the effects should take place if the paladin were on ANY OF THEIR AURAS. This can hinder gameplay especially in 10 man raids in a large way. 

I have tested this very easily on my holy paladin by simply casting a holy light when a paladin is on ret aura and my holy light will cast at 1.2 seconds. Then when the paladin switched to a different aura my cast goes up to 1.3 seconds because the 3% haste buff is no longer up. 

Without a boomkin or arcane Mage in the raid essentially this makes ret Paladins forced to use an inferior aura and then swap to other aura’s for protection or pushback reduction making a ret paladin’s job harder especially in 10 mans. It also prevents the ret paladin from having a resistance on the whole time and for raid cooldowns to be used by an extra paladin via aura mastery rather than them not getting to swap auras because it’s mid fight and other Paladins have that aura on.

If you have any questions I’m willing to do further testing to get this fixed because as someone who assigns auras every raid he is in this has gotten quite frustrating.

**Comment by Hajzlopuc** [comment]
It works for me

Without any aura - 2.43s cast time
https://puu.sh/z09Up/d0493198ab.jpg

With aura - 2.36s cast time
https://puu.sh/z09Yj/27d7c65d02.jpg
https://puu.sh/z09UQ/06635105bc.jpg
https://puu.sh/z09UZ/09ef209cf1.jpg
https://puu.sh/z09WX/f6d64c4b8b.jpg
https://puu.sh/z09Xu/727a956c52.jpg

**Comment by Keader** [comment]
Issue is: Talent work if you not add retribution aura.
After you add retribution aura first time, talent only will work with retribution aura until you relog.
