### ISSUE TITLE
[Icecrown Citadel - Professor Putricide] Unbound Plague 

### ISSUE THREAD

**Issue by Midnaa** [WoWManiaUK/Redemption#2074]
**How it does work**: 

- Unbound Plague is currently resetting its ticking timer each time it jumps but it shouldn't 
- Unbound Plague simply vanishes when a player is dying with it
- Unbound Plague can be removed by Cloak of Shadows in 10HC **(not in 25hc)**

**How it should work:**

- Unbound Plague should never reset its ticking timer so no matter how often it jumps it must tick at least 60 times
- There's 2 ways to go about this. I've done some research and according to retail posts (mmo champ)  when the player with Unbound Plague dies Professor Putricide would recast the plague within 10 seconds with the duration it had on the player. In my opinion we should make it so the plague simply force jumps to the nearest target when the player dies. How it works right now essentially means that it can be abused by always letting the player die thus not having to deal with the mechanic. **However there is no valid info on this so we might aswell keep it as it is.**
- Unbound shouldn't be removeable in any way in 10HC

Currently all guilds doing this boss stack up with the plague completely negating its effect since it never ticks because it is spam jumping and resetting its ticking timer. 
If you were to stack on retail players would eventually start getting oneshot by it because of http://www.wowhead.com/spell=70953/plague-sickness

http://www.wowhead.com/spell=70911/unbound-plague This is the spell the boss casts, however I am not sure if this is also the aura that is on the player. Aura on 10Hc seems to be 72855 and on 25hc 72856

This issue needs to be tested with a  lot of players because http://de.wowhead.com/spell=70955/unbound-plague-bounce-protection will distort the results if there's too little players.

**Comment by philoudu16** [comment]
Still resetting it's tick timer every time it jumps.

**Comment by Keader** [comment]
Someone can test it?

**Comment by philoudu16** [comment]
Just tested this on dev:
On the first plague, we only got hit by 27 ticks total instead of 60, which means the tick timer is still resetting everytime the plague jumps.

**Comment by flumby** [comment]
Tested today with Zun. If you keep passing it from player to player you hardly ever get hit by it.

**Comment by Keader** [comment]
Unbound Plague Dispel is not PP issue, is Cloak of Shadow issue (#2275)

**Comment by Keader** [comment]
Backing Fixed in Dev Tag, because 2º bug is fixed.
Tick reset issue, i give 2 options to janitor, i'm waiting he decide.
I realy think this reset is blizzlike behavior, change search spell to 1100 ms (instead 500 ms) will make players get 1 tick before plague jump to other player.
But this edit will make aura stay 1100 ms before jump always... and i dont think is a good call because of 200 of damage zzzz

**Comment by Keader** [comment]
@Zunrin or @Dranah can test if someone die with plague, PP will cast other in +- 10 sec please?

Tick reset is correct behavior, we cant do nothing about it.
And dispel stuff will be handled by other issue (#2275)

**Comment by Dranah** [comment]
Tick reset is not the correct behavior. The 1100 ms solution is worse than what we have atm.
If you can't fix it, THEN we can't do anything about it, but if you can, please do so.

**Comment by Keader** [comment]
I cant.
Spell System dont support change a aura owner.
And still, i never saw blizzard change a aura owner, it dont make sense.
I realy dont think that in retail this tick timer dont reset...
And everything here is about 200 of damage...

**Comment by Dranah** [comment]
UPDATE:
- PP now properly recasts Unbound Plague if the original target suicides (fixed)
- Unbound Plague can no longer be removed by Cloak of Shadows (fixed)
- Stacking multiple players and chain-bouncing the plague can still prevent it from ticking (need fix)
