### ISSUE TITLE
Respown

### ISSUE THREAD

**Issue by sejosv** [WoWManiaUK/Redemption#2075]
![wowscrnshot_011318_140649](https://user-images.githubusercontent.com/35399078/34906304-59bdb7ca-f86b-11e7-8f6a-8d5fc616def9.jpg)

I seen this bug few days, please respown:

- Henze Faulk  (the tome of divinity)
- Messenger (the defias brotherhood)

Thank you.

**Comment by fvicaria** [comment]
Please follow the procedure described below before creating a new issue:
[How to Properly Report an Issue](https://github.com/wow-mania/Redemption/wiki/How-to-Properly-Report-an-Issue)

This will help developers identify and fix the issue quicker. Incorrectly or unclear reports will simply be deleted.
