### ISSUE TITLE
[Item]  Tiny Abomination in a Jar

### ISSUE THREAD

**Issue by TheManiax** [WoWManiaUK/Redemption#2079]
The items [[Tiny Abomination in a Jar]](http://www.wowhead.com/item=50706/tiny-abomination-in-a-jar) and [[Tiny Abomination in a Jar]](http://www.wowhead.com/item=50351/tiny-abomination-in-a-jar) gives aura  [[Mote of Anger]](http://www.wowhead.com/spell=71432/mote-of-anger) which is meant to fade after you un-equip the item.
Currently the aura stays on the player after un-equip.

**Comment by fvicaria** [comment]
This should have been covered in a previous fix. No?

**Comment by Keader** [comment]
nope, scripted items is not covered by previous fix
