### ISSUE TITLE
[NPC] Gluttonous Abomination

### ISSUE THREAD

**Issue by TheManiax** [WoWManiaUK/Redemption#2080]
The NPC [Gluttonous Abomination](http://www.wowhead.com/npc=37886/gluttonous-abomination) (One of the adds from Valithria Dreamwalker encounter in ICC) is meant to spawn worms when it dies.
But currently there is no worm after it dies. (No matter what Difficulty you are on)
I can't find the proper link for worms on wowhead though.

**Comment by VA-L** [comment]
- Gluttonous Abominations now correctly spawn the worms (they will attack the players if any, otherwise, they'll attack Valithria).

Up to test !
