### ISSUE TITLE
[Boss] Grobbulus 25man mode slime spray (Naxxramas)

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#2081]
Hello, 
I'd like to report Grobbulus' (http://www.wowhead.com/npc=15931) Slime Spray http://www.wowhead.com/spell=28157 ability not spawning oozes properly on 25man mode.
"Enemies hit by Slime Spray summon a Fallout Slime."
On 10man the Fallout Slimes (http://www.wowhead.com/npc=16290) spawn as intended, 1 for each target hit by spray, on 25man not a single ooze spawns, no matter how many targets are hit. This makes the 25man version much easier than intended.

**Comment by VA-L** [comment]
- Fallout slimes now spawn from grobbulus's slime spray in 25 mode.
- Fallout slimes will now also do the right periodically damages in 10/25 modes.
