### ISSUE TITLE
[Quest] Delivering the Message

### ISSUE THREAD

**Issue by dimalopes** [WoWManiaUK/Redemption#2082]
the quest (delivering the message) in shadowstorm / outland is bugged,
After doing the escorting and the guy do what he has to do, he says that hes job was done and I have to go back to the captain, after that nothing happens. So i cant complete the quest.

**Comment by fvicaria** [comment]
Please follow the procedure described below before creating a new issue:
[How to Properly Report an Issue](https://github.com/wow-mania/Redemption/wiki/How-to-Properly-Report-an-Issue)

This will help developers identify and fix the issue quicker. Incorrectly or unclear reports will simply be deleted.

**Comment by fvicaria** [comment]
https://www.wowhead.com/quest=10406/delivering-the-message
