### ISSUE TITLE
[Talent] Missile Barrage procs

### ISSUE THREAD

**Issue by philoudu16** [WoWManiaUK/Redemption#2083]
At max rank, Missile Barrage (http://www.wow-mania.com/armory/?spell=44401) should have a 40% chance of procing on Arcane Blast (http://www.wow-mania.com/armory/?spell=42894), making the next arcane missiles to fire much faster.

However at the moment, it seems to check twice per Arcane Blast.
As you can see on this screenshot, it somehow procced twice on the same blast:
![wowscrnshot_011418_021319](https://user-images.githubusercontent.com/23452669/34925098-7243e192-f9a7-11e7-8a6e-3cd7055c725e.jpg)
This means that instead of having 1 chance out of 7 of not having a missile barrage proc after 4 blasts, you have about 1 chance out of 60 of not having a proc, which means arcane mages barely ever have to use arcane barrage (the typical mage rotation is blast*4 and then if you have a proc you use arcane missiles and if not you use arcane barrage).

**Comment by TheManiax** [comment]
The double "missile barrage" on the floating combat text shows only once in combat log.
But the chance to get the proc is obviously much more than 40% as the player has reported.

**Comment by Keader** [comment]
We have some fix conflicting with it, causing this high proc chance.
I spend 3 hours and i cant find what is causing it :/

**Comment by philoudu16** [comment]
I know that on Sindragosa, you used to get two stacks of unchained magic, one for the damage part, and one for the arcane blast debuff (which increases arcane damage but increases mana cost of the next blast).
Could it be the same issue?

**Comment by fvicaria** [comment]
Please retest

**Comment by philoudu16** [comment]
Retest on dev or on live?

**Comment by Keader** [comment]
I made a new fix, test it now (about proc chance).
About dual proc, looks like a visual issue only, combat log shows just 1 proc.

**Comment by philoudu16** [comment]
I don't seem to have a toon on the PTR :/

**Comment by TheManiax** [comment]
Proced 37% for me in 100 casts.
Due to RNG I confirm its fixed.
