### ISSUE TITLE
Transmog issues.

### ISSUE THREAD

**Issue by Malteman** [WoWManiaUK/Redemption#2084]
I have bought Phoenix´s Rebirth on my main char Malteman. But when i try too transmog it cant find it even yhough it is in my bag.

Can you please help me.

**Comment by TheManiax** [comment]
Please follow the procedure described below before creating a new issue:
[How to Properly Report an Issue](https://github.com/wow-mania/Redemption/wiki/How-to-Properly-Report-an-Issue)

This will help developers identify and fix the issue quicker. Incorrectly or unclear reports will simply be deleted.

**Comment by fvicaria** [comment]
If you can't find it in your bag is because your client is not up to date. Contact support via Skype or email please and I will help you there.
