### ISSUE TITLE
[Quest] Anatoly will talk

### ISSUE THREAD

**Issue by GerardBunsink** [WoWManiaUK/Redemption#2085]
Hello,

During the quest Anatoly will talk, Tatjana needs to be tranquilized. However, I've already come back a few times just to find her lying on the ground, without her horse and tranquillizer does not work. Do I need to wait for a server restart, or is this a recurring problem?

Thanks in advance.

**Comment by fvicaria** [comment]
Yes somebody messed up and did not complete the quest.
We will have a restart shortly.

**Comment by GerardBunsink** [comment]
Ok, thanks for replying!
