### ISSUE TITLE
[Transmog] Phoenix Rebirth

### ISSUE THREAD

**Issue by Malteman** [WoWManiaUK/Redemption#2086]
I have the latest patch but my http://www.wowhead.com/item=50034/zods-repeating-longbow still cant be transmoged with http://wow.zamimg.com/uploads/screenshots/normal/532458-marksmanship-hunter-artifact.jpg.
Can you plz help me get my set complete.

Best Regards Malteman
MM Hunter 
![wowscrnshot_011518_114606](https://user-images.githubusercontent.com/35443842/34939018-a80d94ba-f9ea-11e7-852e-8012241a5d37.jpg)
As you can see it cant be found in the meny at the transmogrifier.

**Comment by fvicaria** [comment]
Transmog with what? Please send me all the info in the support email.
I need screenshot of what you want to transmog with, what you have equipped etc.

**Comment by Malteman** [comment]
There updated the post abit Janitor...

**Comment by Malteman** [comment]
Can you fix it? otherwise i want my 250 Maniac points back ;)

**Comment by fvicaria** [comment]
It will be fixed on next update.

**Comment by Malteman** [comment]
Ok and how long is the waiting time for that?

**Comment by fvicaria** [comment]
Actually it will be on the next restart. So it will be a few days at the most.
Besides where did you get the figure of 250MP from? :)
2 transmog tokes for the item 
5 MP to transmog.

**Comment by Malteman** [comment]
Sry too say it but it is 5 tokens and 50 MP/ token. So yes 250

**Comment by fvicaria** [comment]
Even if it is 5 and not 2, still 5 tokens and 5 MPs. And it is fixed anyways if you checked.

**Comment by Malteman** [comment]
Sry too say it got 2.1.4 and still dosent work. The bow cant be found when you talk too the transmogefier

**Comment by fvicaria** [comment]
![image](https://user-images.githubusercontent.com/9414661/34977529-c499cdc6-fa92-11e7-8570-b29b2cc09541.png)
Point, set match!
