### ISSUE TITLE
[Bug] Refresh GCD issue

### ISSUE THREAD

**Issue by Clickclackz** [WoWManiaUK/Redemption#2087]
Hi,
there is  bug with the fake cast... when you fake cast for example a frostbolt and you cut it and inmediately cast another frostbolt the gcd doesnt refresh so you must wait that internal gcd to cast another frostbolt. Shouldnt be like that.
this happens to all casts with all classes. 
I dont know if i xplain myself well cause my english sucks.

thank you.

**Comment by fvicaria** [comment]
Can someone check this please.

**Comment by fvicaria** [comment]
Tested and cannot reproduce. Please check your latency or keyboard settings.

**Comment by Hajzlopuc** [comment]
I was able to reproduce it. It's capped on following video. I suggest you watch it at 0.75 speed if it is too fast.

https://www.youtube.com/watch?v=v1KoGbn5Re8

The thing is when I cut the cast, GCD should reset and I should be able to cast another spell _immediately_. There should be no errors like 'I can't cast that yet' or 'That's still recharging'. You can clearly see (and hear) that another cast went off only when GCD was fully finished (GCD is represented by a little moving dot under my horizontal cast bar)

**Comment by TheManiax** [comment]
This is how it should work: 
If a spell with casting time is interrupted before it has finished casting, the global cooldown is canceled. This allows you to immediately begin casting a new spell, be it the same spell or another.

**Comment by fvicaria** [comment]
Send me an example of a spell.
I have tried this on my mage and it does work.

**Comment by Clickclackz** [comment]
The guy put a vid and you can see it super clear.

2018-01-17 17:02 GMT+01:00 Janitor <notifications@github.com>:

**Comment by fvicaria** [comment]
I cannot see his delay or anything else I need.
I can see that I did try and it works for me.

**Comment by Clickclackz** [comment]
can you log and i xplain you how? XD cause im with this issue 3 days and
still nobody get it? XD

2018-01-17 17:14 GMT+01:00 Janitor <notifications@github.com>:

**Comment by TheManiax** [comment]
I exactly know what you are talking about @Clickclackz 
It is tested with 9ms latency again
And there is not "spell is not ready"
You can cast right after canceling the first cast
So its ok.
I will remove the "confirm".

**Comment by Clickclackz** [comment]
Janitor is not OK man, try to cast a frost bolt and then block for example.
you cant until gcd gone. Please its bugued all can say it to you lol.

2018-01-17 18:05 GMT+01:00 Maniax <notifications@github.com>:

**Comment by Clickclackz** [comment]
look the video, he is casting roots, cancelling it and then is like char
stuck until gcd gone. This shouldnt happen.

2018-01-17 18:07 GMT+01:00 Pablo Sc <pablo.salinas.carballal@gmail.com>:

**Comment by TheManiax** [comment]
How we tested was:
Start Casting Fireball
Canceling the first cast at 0.2 second (By hitting Esc)
Then start casting the second fireball RIGHT after hitting Esc
And that worked with 9ms latency
Anything you can add to this so we can reproduce?

**Comment by fvicaria** [comment]
We will keep looking but from our point of view there is not an issue with the code but a result of latency.
I will see what can be done to improve it.

**Comment by Clickclackz** [comment]
do it faster. Just cast move and cast. You will see char stuck. Should be
instant the next cast (instant the cast spell).
We must wait until gcd gone.
And is not latency problem under my point of view.

2018-01-17 18:26 GMT+01:00 Janitor <notifications@github.com>:

**Comment by fvicaria** [comment]
Please re-test in dev.

**Comment by TheManiax** [comment]
Awesome fix!

**Comment by Hajzlopuc** [comment]
So it was actually broken regardless of the latency?
Nice work, thank you guys!

**Comment by TheManiax** [comment]
It took the team really much time and effort.
And I really appreciate our awesome Dev team to fix this.
#2077 Feel free to give us more feedback when it is applied to Redemption.
Thanks for the report.

**Comment by Clickclackz** [comment]
Nice work guys. Thenk you
