### ISSUE TITLE
[Icecrown Citadel - Professor Putricide] Unbound Plague not spreading

### ISSUE THREAD

**Issue by MailOrdered** [WoWManiaUK/Redemption#2089]
Unbound Plague appears to be unable to spread after it picks its target. As a result, this target is guaranteed death. This problem occurred multiple times in icc 25hc with the targeted player plainly stacking in their group yet dying anyway.

I've uploaded a video to youtube for evidence at the following link:
https://youtu.be/IxwI4CwZOqs

Summarized: Ano dies from the plague while he has been in direct contact with the rest of the melee.

**Comment by TheManiax** [comment]
I tested with only 2 char
And the debuff was not jumping

**Comment by fvicaria** [comment]
You need more as one will be marked and the tank.

**Comment by Magabro** [comment]
The plague is able to jump to the tank. Two characters should be enough to test this

**Comment by fvicaria** [comment]
Please re-check in dev.

**Comment by TheManiax** [comment]
- The starting spot is changed and need a quick fix (PP need to be at table when starting)
- The plague is jumping normaly (So the reported issue is actually fixed)
- The damage from plague is reseting after each jump (The damage should go higher after each tick, But when it jumps, the damage goes down like its the first tick)
