### ISSUE TITLE
Deleting post? why?

### ISSUE THREAD

**Issue by Clickclackz** [WoWManiaUK/Redemption#2090]
Why you deleting post about the fake cast bug? We posted this bug 2 times or 3 and you deleting it saying nothing. I dont get it.

**Comment by squalllh1989** [comment]
It didn't got deleted, it is closed, and mark as "Invalid or as it" which mean it's working right.
You can see both of your post here at the closed topic: https://github.com/WoWManiaUK/Redemption/issues?q=is%3Aissue+is%3Aclosed

And the direct link to them (to prove that they are not deleted if you can't find them in the closed issue in the link that i give you)
https://github.com/WoWManiaUK/Redemption/issues/2087
https://github.com/WoWManiaUK/Redemption/issues/2077
