### ISSUE TITLE
[Ability] Slam

### ISSUE THREAD

**Issue by Magabro** [WoWManiaUK/Redemption#2092]
Hello wow-mania,

After testing with a Fury specced warrior and running the math, it appears that the warrior ability Slam is bugged and doing about x2 as much damage as expected.

http://www.wow-mania.com/armory/?spell=47475 Slam does weapon damage plus 250

Fury warrior has talents to increase slam damage and critical hit damage as follows:
http://www.wow-mania.com/armory/?spell=56932  Unending Fury increase slam damage by 10%
http://www.wow-mania.com/armory/?spell=16494 Impale increase critical hit damage by 20%
http://www.wow-mania.com/armory/?item=41398 Relentless Earthsiege Diamond increase critical hit damage by 3% (gives a final crit multiplier of 100% + 20% + 3% = 123%

So the damage calculation for normal Slam hit should be:
Slam Damage = (Weapon Damage + 250) x 1.1

Damage for Slam Critcal hit should be:
Slam Critical Hit = (Weapon Damage + 250) x (1 + 1.23) x 1.1

What we are seeing with 100% armor penetration warrior is:
Highest melee attack = 4700
Highest expected Slam = **5,445**
Highest recorded Slam attack = **12,824**

Highest Melee Critical strike = 9,364
Highest expected Slam Critical strike = **12,142**
Highest Slam Critical strike = **24,575**

One possible theory for the issue, Slam is using Attack Power to calculate the damage instead of Weapon damage.

![melee crit](https://user-images.githubusercontent.com/34353250/35000166-888670e0-fa98-11e7-8af2-4d76a0133302.PNG)

![slam crit](https://user-images.githubusercontent.com/34353250/35000176-8ce7876e-fa98-11e7-8628-33286e2e3254.PNG)

**Comment by fvicaria** [comment]
They will be NO more work on slam. It is what it is.

**Comment by Braytonx** [comment]
This is quite a huge bug since it changes the way fury warrior works in wotlk.

**Comment by Midnaa** [comment]
Same for Seal of vengeance, can anyone report that?

**Comment by Dranah** [comment]
I can confirm Slam is doing unreal damage, it is currently hitting harder than any other warrior spell I have.
As if Shadowmourned fury warrs weren't OP enough.

**Comment by TheManiax** [comment]
Its making like double damage
What I can help you with is:

- The issue is not from T10 4 set bounes
- Its not from talents either
- I tested without any talent and without T10 4 set bounes

**Comment by VA-L** [comment]
- Slam is now doing the right damages.

Up to test.

**Comment by Magabro** [comment]
Slam Damage = (Weapon Damage + 250) * (1 + 0.10 ) * ( 1 - % armor reduction )
Weapon damage = 460 - 483
% Armor Reduction for Level 80 Attacker versus Level 83 Heroic Training Dummy (10,673 Armor) = 41.2%

Slam Damage = (WD + 250) * (1 + 0.10) * (1-0.412)

Greatest Expected Slam = 474
Greatest Recorded Slam = 536

**Comment by VA-L** [comment]
The damages are the same as it was weeks/months ago, it's back to normal.

**Comment by Magabro** [comment]
Just finished 25 Heroic ICC with guild and Slam appears to be having correct damage now.  I believe this can be closed.
