### ISSUE TITLE
[Quest] Mending Fences

### ISSUE THREAD

**Issue by plazmyk** [WoWManiaUK/Redemption#2093]
Getting "invalid target" when trying to use Thorims Charm on Fjorn. It worked fine on the giants though.

**Comment by GMWeeble** [comment]
Quest " http://www.wowhead.com/quest=12915/mending-fences " 
Using the quest item with a boulder " http://www.wowhead.com/item=41505/thorims-charm-of-earth " does not work. Error message "Invalid Target"

**Comment by VA-L** [comment]
- Fjorn will now be able to be targeted by the quest item.

**Comment by plazmyk** [comment]
It still doesn't work.

**Comment by VA-L** [comment]
![image](https://user-images.githubusercontent.com/11377592/35032558-8d0863e2-fb67-11e7-9e40-3172f8214755.png)

**Comment by VA-L** [comment]
> It still doesn't work.

![image](https://user-images.githubusercontent.com/11377592/35032582-a05eed1c-fb67-11e7-986d-cf18a71e5e88.png)
