### ISSUE TITLE
[Transmogrification] Xmog disappearance after failing to equip an item

### ISSUE THREAD

**Issue by Asaprockyzx** [WoWManiaUK/Redemption#2094]
Hello

Well this is not easy to explain but i'll do my best.

When you switch from warrior Fury spec to Protection => you won't have this talent http://www.wowhead.com/spell=46917/titans-grip 
As a result your Two-handed weapon which was equipped in your off hand will be automatically sent to your backpack. But if you have no empty slots in your backpack, your weapon will be automatically sent to your mailbox.

Well if you had a transmog on that weapon before what i just said occures, you will lose your transmog on that specific weapon.

This could also happen when you are in Arms spec and you want to switch stances and equip/unequip 2handed / 1handed+shield

This happened to me today at midday when i was on fury and i went protec as a consequence my Cryptmaker lost the Sharpened Obsidian Edged Blade's transmog.

https://www.noelshack.com/2018-03-3-1516143651-wowscrnshot-011618-225825.jpg

I wish that you find a fix to this bug because if it will keep happening, we'll be losing a lot of MP's.

**Comment by fvicaria** [comment]
Ho would yo be unable to equip an item in the first place if you need to equip the item to transmog it?
It's unlikely that we can fix this. Same will happen if you change faction or race.

**Comment by WhitephoenixTheBunny** [comment]
Btw, u can create a set, no need to re-xmog everytime. Save MP :)

**Comment by LooneyBin** [comment]
the solution is easy tbh.
change gear before swapping spec.
dont fill your bags, leave atleast 1 bag slot free.
