### ISSUE TITLE
[Spells] Damage over Time spell's tick timer

### ISSUE THREAD

**Issue by Hajzlopuc** [WoWManiaUK/Redemption#2095]
Hello,

there is an issue with how reapplying a DoT spell reset (or actually doesn't reset) tick timer. When you reapply the DoT, tick timer should reset as well. It means if I reapply the DoT every GCD, not a single tick should go off. In the video I basically spammed corruption and it's clear to see that it didn't reset the tick timer and damage still went off. It applies to all DoTs generally not just corruption.

https://www.youtube.com/watch?v=3xXv7gC3_0Q

It's basically the thing listed [here on Tri-Core](https://github.com/TrinityCore/TrinityCore/issues/17961) and there should also be a fix for that. Can you check it please?

**Comment by fvicaria** [comment]
This has been looked at once. Unlikely that anything new will come up.

**Comment by Hajzlopuc** [comment]
I leveled a lock in Dev realm to level 4 to get the Corrupion spell, can confirm it's fixed in Dev now. 
Thank you!
