### ISSUE TITLE
Transmog issues with Phoenix´s Rebirth

### ISSUE THREAD

**Issue by Malteman** [WoWManiaUK/Redemption#2096]
OK this is hard too explain. 
First all hail Janitor that fixed so i can transmog that bow =D.

Now too the issue.
When i auto shoot or use any talent shoot, my character lifts the bow up in the air.
It looks more like a mage now then a hunter. During Volly the bow isnt showen at all
![wowscrnshot_011718_055214](https://user-images.githubusercontent.com/35443842/35026510-c419d9d6-fb4b-11e7-8aee-5058e09a7806.jpg)
i would love too shoot normaly again and not like a mage =D.

**Comment by TheManiax** [comment]
#2086 
@fvicaria

**Comment by Malteman** [comment]
That post is fixed. its the mechanics of the bow that is alittle bit off.

**Comment by fvicaria** [comment]
As is. This is a transmog and the way it looks in wotlk cannot be changed.
