### ISSUE TITLE
[ Ulduar - Kologarn ]

### ISSUE THREAD

**Issue by Bartok14** [WoWManiaUK/Redemption#2098]
I realise that with this boss there was an issue already stated where his arms were switched and you may have rolled him back on 'live' to reverse this, so maybe some of these things aren't supposed to be working.

1) He did not seem to pick anyone up at all during the fight, perhaps we DPS him down too quickly.
2) Even though we killed both arms they ended up respawning during the fight. 
3) Even though at some point during the fight we had both arms down so it was just his torso, we did not receive an achievement for killing him on hard mode. 
4) After you kill the boss his body falls onto the platform to form a bridge. If you got in there afterwards like past an hour after his body making the bridge will disappear, but you can still cross the gap you just won't see anything below you. Just a visual glitch.

The fight worked decently well so just the visual glitch afterwards and the boss picking up people and the achievement. Not really a big deal at this point.

**Comment by VA-L** [comment]
- There's no hard mode on Kologarn
- He does pick someone up unless his right arm dies.
- Both arms are meant to respawn during the fight, that's why you also have an achievement that require to kill both arms and kologarn's torso in 12 seconds.
- All the achievements are working correctly.

**Comment by Bartok14** [comment]
Okay sorry if I got my information wrong. Work in progress.

**Comment by Bartok14** [comment]
The visual glitch with his body was correct though, that did happen to me after entering the raid about 2 hours after we left.
