### ISSUE TITLE
[Boss] The Iron Council-Ulduar

### ISSUE THREAD

**Issue by Bartok14** [WoWManiaUK/Redemption#2099]
This fight seemed to work really well for the most part just a couple of minor things.

1) Stormcaller Brundir seems to not hold agro onto any tank and simply runs around the room in random directions casting all over the place, Not sure if this is how it is supposed to work. 
2) There were issues with the spawn location of the bosses after a wipe some were standing near the door or in different places. 
3) After you kill the bosses Bronzebeard and another dwarf come into the room, after a couple of hours if you come back you will see them in the middle of the room and then they run like crazy to get back to the computer for the quest, kinda funny bug :) .

This fight was fine just those small issues and again not sure about number 1 and was pleasantly surprised that we managed to get the achievement and the hard mode quest started for Algalon :)

**Comment by Keader** [comment]
Bug 1 - fixed.
Bug 2 - i cant reproduce.
Bug 3 - is not possible fix without cost alot to server. I dont think that it's irritating enough to pay so high cost in server performance :)

**Comment by Bartok14** [comment]
Thanks for working on these issues I really appreciate it.

**Comment by Keader** [comment]
All fix work in dev, we need wait a tester confirm it to enter in next update

**Comment by Keader** [comment]
@Dranah please try reproduce positional issue now ^^

**Comment by Dranah** [comment]
will reopen until further testing

**Comment by fvicaria** [comment]
This has been released now.
