### ISSUE TITLE
[NPC] Obsidian Sanctum infinite emblem of triumphs

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#2102]
Hello,
I'd like to report a bug related to Sartharion's mini twilight drakes, Shadron (http://www.wowhead.com/npc=30451), Tenebron (http://www.wowhead.com/npc=30452) and Vesperon (http://www.wowhead.com/npc=30449).
As mini-bosses, all of these NPCs award Emblems of Triumph (http://www.wowhead.com/item=47241) when killed, whether you do any of the hardmode on Sartharion (1 drake, 2 drake or 3 drakes up) or kill them separately.
However, doing Sarth with drakes up allows you to respawn the drakes if you wipe/dc or just run out of the instance, alas reset the encounter. When that happens, the next time you engage Sartharion and kill the drakes during the encounter again, they still award you emblems of triumphs, although they shouldn't, and it is possible to farm them infinitely.
How it should work: Each drake should award only 1 emblem, upon their first deaths, and none on the follow-up deaths.

**Comment by fvicaria** [comment]
Thanks for that.

**Comment by fvicaria** [comment]
I have just checked and this is how it is supposed to work. Just a quirk of 3.3.5a. We will not be changing the behavior in this case.

**Comment by hotdoggidy** [comment]
same case as minibosses in RS. they will respawn with trash eventually and are each worth 1 frost. since they dont drop anything else i assumed it was as designed.

**Comment by fvicaria** [comment]
Yes not sure if we can do anything about it. I will re-check.

**Comment by Keader** [comment]
Tested again today and i cant reproduce it anymore
Please let me know if has some reproduce steps and i will fix it.
