### ISSUE TITLE
[Boss] Vazruden

### ISSUE THREAD

**Issue by LadyMariann** [WoWManiaUK/Redemption#2104]
Trying to do quest "Weaken the Ramparts" Vazruden seems to be stuck in a loop.
When killing Vazruden the dragon do not take off but stays on ground. If attacking dragon again. Vazruden attacks again. Same over and over.
Cannot complete quest. Also every time you kill Vazruden it gives you 50 rep. with Thrallmar. So could be abused in rep. farming.

**Comment by Dranah** [comment]
I encountered this bug when I was leveling too, but if you damage Nazan to 90% before bursting down Vazruden, this does not happen and the dragon flies properly.
The rep farm is real though.

**Comment by fvicaria** [comment]
http://www.wow-mania.com/armory/?quest=9575
