### ISSUE TITLE
Twilight portals (Obsidian Sanctum)

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#2105]
Hello,
I'd like to report Tenebron( http://www.wowhead.com/npc=30452) and Vesperon (http://www.wowhead.com/npc=30449) twilight portals having some issues. 
1. The portal disappears after one person uses it, preventing anyone else to enter afterwards.
2. There is no "return" portal on the shadow side.
3. There are two different bugs present about the eggs whether you fight Tenebron alone, or engaged together with Sartharion.
- Tenebron alone: 
A few seconds after entering her portal to kill the eggs, the eggs inside disappear, a few seconds later appear again and so on. It feels similar to the past issue with Hadronox and his adds phasing in and out in Azjol-nerub. Note, you do not get phased back out to your comrades, just the eggs disappear and reappear over and over and it's rather hard to kill any of them this way.
Furthermore, the eggs which you fail to kill over a given span of time (about 15seconds after Tenebron casts Hatch eggs), should hatch as whelps and leave the portal, attacking the party in normal phase. This does not ever happen when fighting Tenebron , though she keeps on casting hatch eggs, whelps never come.
- Tenebron engaged together with Sartharion:
The major difference is that when Tenebron is engaged by Sartharion as the first drake who lands, her eggs appear in the normal phase to begin with, instead of being in the shadow phase until they are supposed to hatch and leave as whelps. They just spawn around Sartharion and the eggs themselves begin attacking your raid.

**Comment by TheManiax** [comment]
**Tenebron**:
1. When you enter the shadow realm using the portal, There is no portal to get back to twilight realm (There should be a one to get back)
2. If you don't kill the disciple fast enough, you will be stuck in the shadow realm. (If you kill it fast enough, you will get teleported to twilight realm and you can finish off the mini boss)
**Vesperon**:
1. When you enter the shadow realm using the portal, There is no portal to get back to twilight realm (There should be a one to get back)
2. If you kill the eggs, you will be stuck in shadow realm.
3. If you don't kill the eggs, They will fade out and you will be stuck in shadow realm.
So in this case the only way to do this mini boss at the moment is not to use the portal at all and just DPS it down fast.

**Comment by Dranah** [comment]
All good @TheManiax  except Vesperon is the one with the disciple, and Tenebron has the eggs.

**Comment by VA-L** [comment]
Planning to rewrite it when i get back home.
I've also encountered a new issue.

- If you manage to kill the disciples, sometimes it's gonna pull the whole room.

I don't know why and how it happens for the moment.
**Soon™**

**Comment by VA-L** [comment]
- Portals are now usable multiple times during the allowed interaction.
- Players will be ported out if they don't kill the disciples in time regarding Vesperon and Shadron.
- The right exit portal has been added on Tenebron's encounter, whether he's engaged alone or with Sartharion.
- Players will be correctly ported out when cliking on the exit portal of Tenebron.
- Eggs spawned when Tenebron is engaged with Sartharion will no longer attack players and be correctly phased in the twilight realm.
- Whelps will now get out of the twilight realm and attack players if they don't kill the eggs in time.
- Fixed a crash happening with Whelps spawn.
- Whelps will now despawn after 30s of inactivity.

Up to test.

**Comment by TheManiax** [comment]
- **Tenebron:**
Works fine.
- **Vesperon:**
The aura  _[Twilight Torment] ID:57935_ needs a timer or a condition to be removed on Vesperon's Death or leaving the instance. Currently if you don't kill the disciple inside, the debuff will stay on you for ever until you die.
- **Shardron:**
Is not reported yet, but doesn't have any mechanic, Its currently tank and spank only. We will report and fix it in another report when nothing else is up.
- **Sartharion Hard Mode:**
Works fine.
I will confirm the fix since it is doable already.
