### ISSUE TITLE
Presence of Mind - Conjure Mana Gem

### ISSUE THREAD

**Issue by philoudu16** [WoWManiaUK/Redemption#2106]
When you dont have a mana sapphire in your inventory, you can cast presence of mind so your conjure mana gem becomes instant. But for some reason when your sapphire has 1 or 2 charges left, using presence of mind won't make conjure mana gem instant.

Links to the spells : 
Conjure Mana Gem : http://www.wow-mania.com/armory/?spell=27101
Presence of Mind : http://www.wow-mania.com/armory/?spell=12043

It's not a big deal if this doesn't get fixed, it's just nice to be able to cast it Conjure Mana Gem on the run while clearing trash or running to a boss and not having to stop to cast it.

**Comment by Hajzlopuc** [comment]
Hello,

It looks like it's intended.
I found this:
https://www.mmo-champion.com/threads/798629-Presence-of-Mind-Conjure-Mana-Gem

> `If you have a gem with a charge on it, it wont let you. If you have no gem, it will work`

**Comment by philoudu16** [comment]
Ok my bad then and thanks for the macro! :)
