### ISSUE TITLE
[NPC] Sunreaver Guardian Mage

### ISSUE THREAD

**Issue by GMWeeble** [WoWManiaUK/Redemption#2107]
The -Male- Npc is casting " http://www.wowhead.com/spell=54029/trespasser " continuously on players "Horde side" if they get close. 
http://www.wowhead.com/npc=29255/sunreaver-guardian-mage

**Comment by GMWeeble** [comment]
So it looks like both.

**Comment by fvicaria** [comment]
Just checked on Redemption now and it is all OK

**Comment by GMWeeble** [comment]
Still needs fix.

**Comment by fvicaria** [comment]
Should be OK now

**Comment by GMWeeble** [comment]
Still not okay. Unless you have the fix on Dev.

**Comment by GMWeeble** [comment]
Still not fixed Sunreaver Guardian Mage still is casting " http://www.wowhead.com/spell=54029/trespasser " over and over-

**Comment by fvicaria** [comment]
It's fixed in Red.

**Comment by GMWeeble** [comment]
Yeahh, sorry but now the female guard is doing same as the male one. Male seems to be fine.

**Comment by fvicaria** [comment]
I added some delay
