### ISSUE TITLE
[Boss] Razorgore the Untamed

### ISSUE THREAD

**Issue by Bartok14** [WoWManiaUK/Redemption#2109]
During the server event today we were trying to do blackwing lair. There is a bug where you can't stop mind controlling Razorgore and the button for releasing him does not work.

**Comment by Bartok14** [comment]
Figured out eventually that if you logout and back in it  stops mind controlling the boss and works out alright.

**Comment by VA-L** [comment]
This one has been fully rewritten.

- Razorgore and all the summoned adds will now despawn if he evades.
- Eggs will now respawn when razorgore evades.
- Right Mind Control spell added.
- Prevent players to use the orb one more time while the MC is channeled.
- If the channeling player has a pet, it will be dismissed.
- If Razorgore dies during P1, players will die and Razorgore will despawn (and respawn), summoned adds will despawn too.
- When Razorgore successfully dies (P2), all the adds will despawn.
- Razorgore gets in combat correctly when the channeling is canceled.
- The 3 mobs around the [Orb of domination](http://www.wowhead.com/object=177808/orb-of-domination) will respawn when Razorgore evades.
- Adds will start spawning 30 seconds after the first egg has been destroyed (was 45).
- Blackwing warlocks's rain of fire and shadowbolts can no longer hit Razorgore while he's not under the MC.
- Razorgore can no longer stun himself with the [Calm Dragonkin](http://www.wowhead.com/spell=19872/calm-dragonkin).
- Text has been added when razorgore nukes the room.
- 3 texts have been added when razorgore destroys an egg.

Up to test.
