### ISSUE TITLE
[Talent] Blood of the North

### ISSUE THREAD

**Issue by Magabro** [WoWManiaUK/Redemption#2110]
The Death Knight Talent "Blood of the North" http://www.wow-mania.com/armory/?spell=54637  Is applying an incorrect amount of flat damage to the Frost Strike ability http://www.wow-mania.com/armory/?spell=49143

Blood of the North talent increases Frost Strike damage by 3%/6%/10% at ranks 1/2/3 respectively.
Currently rank 3/3 is showing a 19.6% increase in flat damage.

Currently Frost Strike tooltip reads:
Frost Strike with 0/3 Blood of the North = 55% weapon damage + 138
With 1/3 Blood of the North = 56.65% weapon damage + 144   **(4.3% increase in flat damage)**
With 2/3 Blood of the North = 58.30% weapon damage + 154   **(11.6% increase in flat damage)**
With 3/3 Blood of the North = 60.5% weapon damage + 165     **(19.6% increase in flat damage)**

Frost Strike tooltip should read:
Frost Strike with 0/3 Blood of the North = 55% weapon damage + 138
With 1/3 Blood of the North = 56.65% weapon damage + **142**
With 2/3 Blood of the North = 58.30% weapon damage + **146**
With 3/3 Blood of the North = 60.5% weapon damage + **151**

I can only confirm the tooltip shows incorrect values.  Likely the flat damage is also applying incorrectly.

**Comment by Keader** [comment]
Looks correct to me, because it scale with all SpellMods (all talents already applied and remade the calculation)
