### ISSUE TITLE
[Item] Transmog

### ISSUE THREAD

**Issue by nhockey** [WoWManiaUK/Redemption#2112]
When transmogrifying a staff on my character to the [Deadwood Keeper](http://www.wow-mania.com/armory/?item=150200); when the staff is on my back it appears to be upside down. When held in the hand the right end points away from me as most staves do. But on my back the head of the staff is down by my... tail? The item of the staff is 150200 and was purchased in the wow-mania mall. 

Here you can see the enchanted "glow" on the head of the staff...
![wowscrnshot_011818_172049](https://user-images.githubusercontent.com/436149/35124615-bb7f4868-fc74-11e7-9d6e-98ff3ce1561c.jpg)
And here you can see that the head of the staff seems to be at the bottom...
![wowscrnshot_011818_172042](https://user-images.githubusercontent.com/436149/35124622-c18c260e-fc74-11e7-8312-754cb3581b9f.jpg)

**Comment by fvicaria** [comment]
There will be no work done on transmogs. They are imported from another client and are as-is.
