### ISSUE TITLE
[Spell] Acclimation

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#2113]
Hello,
I'd like to report a bug regarding Acclimation (http://wowwiki.wikia.com/wiki/Acclimation) talent in the frost dk tree not proccing of all the spell damage sources that should proc it.
It was rather difficult to find reliable information of how it worked back in the day, as I could not find even a WOWhead link for the talent anymore, but according to most forum discussions on wowhead, mmo champions and other places, Acclimation is meant to proc off aura spell ticks (such as Sapphiron's, Loken's or Blood Queen Lanathel's) as well as DoTs, aoe and channeled spell ticks in addition to regular single target and direct damage spells. 
The tooltip itself does not specify "direct damage" or anything at all, means it should proc off any source that does spell damage to the death knight. Discussions of players on official sites also suggest it literally procs off any kind of spell damage, making it very easy to keep it stacked to max as long as there's any source of spell damage going on, be it just a rogue poisoning you or such.

According to my tests made, the talent works as follows at the moment:
- procs as intended from direct, single target damage spells (for example shadow bolt)
- procs as intended from direct damage AOE effect spells (Arcane Explosion)
- procs as intended from spellpower based channeled area effect spells (tested Rain of fire and Hurricane)
- does NOT proc from any ranged AP based area spell effects (Volley - it does pure arcane damage and should proc it!, Explosive trap - pure fire damage, Immolation trap - same)
- procs as intended from channeled, single target spells (Mind flay)
- does NOT proc from boss auras, though it should (tested on Sapphiron)
- does NOT proc from DoT ticks, though it should (tested Curse of Agony, Shadow word: pain, corruption and vampiric touch)
- does NOT proc from channeled AOE DOT effect such as Hellfire ticks
- procs as intended from non-channeled AOE DOT effect such as shaman's Magma totem
- procs as intended from Ground AOE DOT effects such as Dks' Death and Decay (except for hunter's Explosive trap detailed above)
- procs as intended from reflective damage spells (shaman's Lightning shield)

This essentially makes the talent lose half of its utility. It is useless on most raid fights that it was originally designed for, where you take constant persistant spell damage at all times, as well as in PVP when countering spellcasters who DoT or hunters, whose spell damage entirely bypasses this at the moment. And generally its uptime suffers everywhere due to certain spell types not proccing it.

**Comment by fvicaria** [comment]
Please read this: 
[How to Properly Report an Issue](https://github.com/wow-mania/Redemption/wiki/How-to-Properly-Report-an-Issue)

Use only links to our armory and as a last resort use wowhead.com

**Comment by Dranah** [comment]
mania armory hasn't ever worked for me, I can't find anything there
I try to gather wowhead links for everything i can to help but that's the most I can do

**Comment by fvicaria** [comment]
Then this is YOUR problem locally as it works just fine.

**Comment by Dranah** [comment]
Update after testing on dev: procs off Hellfire now, still not procced by DOTs, hunter spells, boss auras (sapphiron's frost aura and chill blizzard)

**Comment by Keader** [comment]
I think that it's incorrect.
Acclimation has:

```
Interrupt Flags: 0x00000000, AuraIF 0x00000000, ChannelIF 0x00000000
Proc flag 0x00020000, chance = 30, charges - 0
=================================================
  17 Taken magic spell damage
=================================================
```

Taken Magic Spell Damage means: Proc with direct spell damages.
To proc with DOT should has: `PROC_FLAG_TAKEN_PERIODIC (0x00080000)`
And to Proc with AOE should has: `PROC_FLAG_TAKEN_AOE_SPELL_HIT (0x00002000)`

Have you any proof that it should proc with dots or aoe?
because based only in dbc (blizzard game file), is correct now.

**Comment by Dranah** [comment]
The original WOTLK talent no longer exists on blizzard, so all I have is player feedback from official retail websites, such as WoWhead.
Here's an example:
http://www.wowhead.com/forums&topic=88587/acclimation-why-the-lack-of-love
A topic created by blizzard players back in 2009. First poster speaks of how useful acclimation is on Loken fight "I've once take 6k from H Loken's Nova, and about 200 from his aura" which clearly implies the spell must be proc'd during Loken fight in Halls of Lightning. Loken has an AOE nova, and an AOE aura, either of them MUST proc it, currently after testing on Redemption, none of them do, you don't ever get any stacks on that encounter here. Among replies on his post, at least 3 more posters mention how much they love this talent on Loken, as it is constantly stacked to 3/3.
Next one:
http://www.arenajunkies.com/topic/49827-death-knight-frost-pvp-1952/
A topic about pvpers discussing frost talents, also back in 2009. There's a bit of disagreement whether or not rogue poisons are intended to proc Acclimation. One guy claims they "shouldnt" but there are two people who have actually seen it proc off Deadly poison in action. Which is a DOT, that uses attack power coefficients. Therefore it is expected to be proc'd off all  DOTs and those hunter ranged attacks that use spell damage as well.
Another:
https://www.mmo-champion.com/threads/650065-thoughts-on-acclimation
One of the posters clearly states "before 3.1 there are maybe 3 fights where its worthwhile, unless you can't beat saph, i'd say dont worry about it" implying Sapphiron is one of the fights where it is actually useful. Sapphiron has a chill blizzard AOE and a frost aura, currently NONE of them proc it on Redemption at all, you never get a single stack. Its quite contradictory when retail players claim it is very useful there.
Another reply in this post mentions that in Ulduar, it is only useful for "Ignis, XT, Iron Council, Hodir, Mimiron". None of these encounters contain any direct spell damage, except maybe certain adds on Mimiron, so it is safe to assume that the talent would be procced by Hodir's stacking frost DOT or falling ice AOEs, as well as the ground fires on Ignis. None of these effects proc Acclimation on redemption.

Lastly, it IS already procced by "certain" dot or aoe effects. It can proc off Magma Totem, but not Explosive Trap. It can proc off Rain of Fire, Hurricane, now even Hellfire, but not Sapphiron's Chill blizzard. It can proc off Mind flay, but not Drain soul. It can proc off Blood Queen Lanathel's aura, but not those of Sapphiron or Loken. This is inconsistent, it cannot be that half DOT/AOE spells can proc it and other half can't. Every comment from retail players suggest that it is NOT only direct spells (as well as the tooltip - its always specified when something only proc off direct spells but this one isn't) and it already procs off a bunch of non-direct spells, so i simply don't understand why the others do not proc it.

**Comment by Keader** [comment]
Now will proc with Hunters Spells and Loken AOE.

**Comment by Dranah** [comment]
Update: All spell damage that is checked as a hit can now proc Acclimation, including ground/area spells, spells that use ranged weapon and rogue's instant/wound poison. Periodic debuff ticks cannot and should not. This now works as intended.
