### ISSUE TITLE
[Argent Tournament - Quest Indicator Visual Glitch]

### ISSUE THREAD

**Issue by Bartok14** [WoWManiaUK/Redemption#2123]
There is a visual glitch with the exclamation points over the NPC's heads in the Argent Tournament tent where they will always show even if you can't start a quest with them because you are becoming a valiant with the other main cities of the horde side.

**Comment by squalllh1989** [comment]
Confirmed, the quest mark is kind of mess on this section, the npc got all the blue mark for the daily quest over on there head on both the npc and the mini map, even if you can take the quest or not, this make you have to check the npc one by one to know if they really have a quest for you.

**Comment by fvicaria** [comment]
Can you add links and images please.

**Comment by Bartok14** [comment]
![image](https://user-images.githubusercontent.com/32959403/35176677-b7aa03ac-fd48-11e7-9303-8a3b1e224daf.png)

As you can see I am currently on the Valiant's quest for Undercity. 
![image](https://user-images.githubusercontent.com/32959403/35176731-d756791a-fd48-11e7-9bef-e72b3d2d0559.png)
The Sunreaver Quests I can't even do anymore and they still appear as dailies to complete. Also you can see that even though I can't click on the quest for Troll and Tauren that the Exclaimation Mark still appears yellow overtop of their head.
![image](https://user-images.githubusercontent.com/32959403/35176755-ff7aa628-fd48-11e7-95b3-0d28b5bda34f.png)

![image](https://user-images.githubusercontent.com/32959403/35176760-07e63eda-fd49-11e7-85e2-e92b90c27b01.png)

![image](https://user-images.githubusercontent.com/32959403/35176767-1490a738-fd49-11e7-92f0-cd183ba31463.png)

And the Same thing happens with these two NPC's in the other tent. 

I'm honestly not sure what some of these quests are anymore but the other ones for the troll and tauren valiant quests are:
http://www.wowhead.com/quest=13708/valiant-of-senjin
http://www.wowhead.com/quest=13694/a-valiant-of-thunder-bluff

If you haven't done any of these quests then all of quest markers appear above their heads even before you finish the Valiant's quests with the tournament which is required to start doing the valiants quests with the individual races. I have already completed the Silvermoon and Orgrimar quest lines so that's why they don't appear over their heads.

**Comment by Bartok14** [comment]
Here's another screenshot of what it looks like before I have completed my dailies, keep in mind that I have already done the valiants quest chain with blood elves, undead, and orcs. 
![image](https://user-images.githubusercontent.com/32959403/35192874-fc07b9f2-fe67-11e7-8f6f-f37c07088681.png)

**Comment by fvicaria** [comment]
Although this is purely a visual issue and does not affect either the completion of any quest nor the functionality of the NPC I decided to have a quick goal at it.
If this fails I will be closing it as is.

Please re-check.
