### ISSUE TITLE
[Mage - Arcane] Arcane Blast stacks dropping after one stack

### ISSUE THREAD

**Issue by justincormier** [WoWManiaUK/Redemption#2124]
Issue started within the last 24 hours. Arcane Mage's Arcane Blast will only stack once, and will drop off once a second Arcane Blast is cast. You can continue to cast Arcane Blast and the first will create the buff, the second cast will drop the buff, the third cast will create the buff, the fourth cast will drop the buff and so on.

**Comment by TheManiax** [comment]
This is already fixed on Dev
Will be applied to Redemption as soon as possible
Thanks for the report.
