### ISSUE TITLE
Combustion on Halion10hc

### ISSUE THREAD

**Issue by Ezzraeil** [WoWManiaUK/Redemption#2128]
Hello, we were doing RS10hc, Combustion debuff was getting dispelled instantly automatically Sometimes, it was completely randomly. I even checked my recount too see if anyone was dispelling or not and there were no dispel on recount addon. and also no cleansing totem from shaman.

**Comment by Keader** [comment]
My guess? Felhunter dispelling :)

**Comment by TheManiax** [comment]
If you can provide more information, maybe I can reproduce it.
Felhunter auto dispel can cause that, But that will show up in recount.

**Comment by Ezzraeil** [comment]
if recount shows it then it wasn't Felhunter.
