### ISSUE TITLE
Switching from Scryers to Aldor

### ISSUE THREAD

**Issue by philoudu16** [WoWManiaUK/Redemption#2129]
A few years ago, I chose to side for the Scryers in Shattrath: I pledged alegiance to them  through Khadgar's quest and worked my reputation all the way to exalted. Recently, I decided to switch sides and farmed over a thousand of Dreadfang Venom Sacs to turn this quest (http://www.wowhead.com/g00/quest=10019/more-venom-sacs) over a hundred times. Now I have finally reached neutral reputation with the Aldor. As you can read in the comments, it's the only way to reach neutral with them from hated and be able to turn in the mark of KilJaeden to reach higher level of reputations.

But when trying to speak to Adyen the Lightwarden who had an exclamation mark above his head (the marks quest) at Aldor Rise, I realised he was still hostile to me. I checked the reputation tab and I cannot unmark the "at war" box which is greyed out for me. With the help of a GM I tried all the usual fixing stuff, like clearing cache, making sure I ran the launcher as admin with read and write rights on the folders, resetting the NPC etc... and none of this worked.

I also checked in the center of Dalaran and there is no quest to switch sides from one faction to the other.

**Comment by fvicaria** [comment]
I need your char name.

**Comment by philoudu16** [comment]
Char name is Zunrin

**Comment by fvicaria** [comment]
Just checked and your standing with Aldor is currently -3935

**Comment by philoudu16** [comment]
Thanks! That solved the issue :)
