### ISSUE TITLE
[NPC] Toxic Tunnel (Naxxramas)

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#2130]
Hello,
I'd like to report a bug related to the "Toxic Tunnel" http://www.wow-mania.com/armory/?npc=16400 located between Grobbulus and Gluth. These Toxic tunnel mobs are currently unattackable, untargetable, but they attack you and get you stuck in combat. You can only damage them with reflective damage such as Retribution aura. Their toxic gases seem to be cast on you properly. http://www.wow-mania.com/armory/?spell=28370
How it should work: These npcs should be visible, targetable, and attackable, so that you can clear the tunnel. If you leave the tunnel without killing them, they should drop combat and reset.

**Comment by Bartok14** [comment]
To my knowledge there aren't supposed to be mobs in that tunnel. You are supposed to take ticking damage from the green ooze that lines the tunnel however.

**Comment by VA-L** [comment]
> To my knowledge there aren't supposed to be mobs in that tunnel. You are supposed to take ticking damage from the green ooze that lines the tunnel however.

Indeed but players shouldn't keep combat while passing the tunnel anyway.
Fixed on dev tomorrow.

**Comment by Dranah** [comment]
I could be mistaken about that, as I found this to be a hostile NPC in the database, who can attack players directly. But if they are passive NPCs who only spawn their gasses, then they should not attack or get you in combat at all, and they should take no reflective damage from Ret aura/ thorns either.

**Comment by VA-L** [comment]
![image](https://user-images.githubusercontent.com/11377592/35183956-ad230838-fdee-11e7-8b9a-c4e345f33935.png)

Unable to see them even with CTRL+V, means they're not selectable and not attackable.
Fixed, up to test.

**Comment by Dranah** [comment]
confirmed, only gas damage now, no combat or something melee-ing you
