### ISSUE TITLE
[Spell] Lava Burst

### ISSUE THREAD

**Issue by vexation47** [WoWManiaUK/Redemption#2134]
I have noticed today that its actually not critting 100% of the time with flame shock up anymore. \

I can also confirm with 2 other Shamans that the crit damage is a bit lower too.

**Comment by fvicaria** [comment]
Should be ok after restart.

**Comment by TheManiax** [comment]
[lava-burst](http://www.wowhead.com/spell=51505/lava-burst)
[flame-shock](http://www.wowhead.com/spell=188389/flame-shock)
**How it should work**:  If your Flame Shock is on the target, Lava Burst will deal a critical strike.
