### ISSUE TITLE
[SPELL] Hunter's Mark

### ISSUE THREAD

**Issue by elagen** [WoWManiaUK/Redemption#2135]
I think there is a bug with the Hunter's Mark http://wow-mania.com/armory/?spell=53338 as it is not giving the 500 extra Attack power

Without Hunter's Mark
![wowscrnshot_012118_102506](https://user-images.githubusercontent.com/22685042/35193085-a13b42fe-fe95-11e7-90cd-2c6c37f8324f.jpg)

With Hunter's Mark
![wowscrnshot_012118_102513](https://user-images.githubusercontent.com/22685042/35193088-ac898dd2-fe95-11e7-941d-f49628d4ec42.jpg)

Tectonic_Attack_Power is the addon i am using that Tracks current attack power when buffed is shows the current attack power when buffed and unbuffed

**Comment by goldstinger** [comment]
If I recall correctly, Hunter's Mark increases attack power to ranged attacks by 500 in relations to damage. It does not actually increase your character's attack power.

A better suited way to figuring out if its bugged or not, is maybe to run some base line dps diagnostics using recount, considering it looks like you also have that addon.
