### ISSUE TITLE
Portal to inner Maraduon not working

### ISSUE THREAD

**Issue by borkeejedan** [WoWManiaUK/Redemption#2139]
So i've started the meta achievement http://www.wowhead.com/achievement=913/to-honor-ones-elders . Got through all of it except http://www.wow-mania.com/armory/?achievement=910 since the portal to the dungeon is not working. It's not clickable can't go through it either. If in-game screenshots are needed let me know and i will provide them

**Comment by TheManiax** [comment]
http://www.wowhead.com/achievement=910/elders-of-the-dungeons
You need to find the elders inside different dungeons and honor them.
I may be able to reproduce it if you provide more information.
What portal are you talking about?
