### ISSUE TITLE
Invincible Reins [Item / Mount]

### ISSUE THREAD

**Issue by xclaw800** [WoWManiaUK/Redemption#2140]
The item / Mount http://www.wowhead.com/item=50818/invincibles-reins

Clearly states it requires only level 20 apprentice riding. This has been the case since wotlk was released and therefore this is how it should be coded. 

When you are in a non flying area it may be used as a ground mount only. When you can fly it will be allowed to fly again.

 Even if this requires a remount I would much like for this to be working as intended.

Thank you and let me know if you have any questions.

**Comment by TheManiax** [comment]
https://github.com/WoWManiaUK/Redemption/issues/1413
Duplicate.
