### ISSUE TITLE
[Spell] Lava Burst fails to crit as described

### ISSUE THREAD

**Issue by MailOrdered** [WoWManiaUK/Redemption#2141]
The spell [Lava Burst] says: 

> You hurl molten lava at the target, dealing 1323 to 1685 Fire damage. If your Flame Shock is on the target, Lava Burst will deal a critical strike.

As of last patch, however, lava burst does not care if you have flame shock on the target and instead defaults to your regular crit percentage. Having one non-crit on a target afflicted by flame shock proves that it's broken, so the bug is easily reproducible. I've linked a youtube video as evidence in case we're lazy.

https://youtu.be/HJZxDYXBcJw

**Comment by fvicaria** [comment]
THis has been fixed and needs server restart. Check before creating new issues please.
Please follow the procedure described below before creating a new issue:
[How to Properly Report an Issue](https://github.com/wow-mania/Redemption/wiki/How-to-Properly-Report-an-Issue)

This will help developers identify and fix the issue quicker. Incorrectly or unclear reports will simply be deleted.
