### ISSUE TITLE
SPELL lava burst

### ISSUE THREAD

**Issue by larian** [WoWManiaUK/Redemption#2142]
hello,

just wanted to inform u that lava burst isn't always dealing a crittical strike when target is affected by flame shock...had a feeling it didn't when i was raiding and later tested it out on training dummy's
![ele1](https://user-images.githubusercontent.com/34296326/35201359-df41c0d4-ff1a-11e7-8813-ee0a0fca3f82.jpg)
![ele2](https://user-images.githubusercontent.com/34296326/35201360-e199615c-ff1a-11e7-878f-4c6b21c9ebd8.jpg)

even tho the dmg in the log seems to be exactly the same this was on 2 occasions...and for a spell that sais it should always crit its already a lot of dmg missing.

can u look into this plz

hope i provided u enough info to work with

tnx in advance

firefoxy

**Comment by GMWeeble** [comment]
Already 2 posts about it.

**Comment by larian** [comment]
wel sorry for trying to be helpfull
