### ISSUE TITLE
[Mount]  Dread Raven

### ISSUE THREAD

**Issue by TheManiax** [WoWManiaUK/Redemption#2147]
Graphic needs  fix.

**Comment by fvicaria** [comment]
DO not confirm your own issue.
Also how about more info? Image and links?

**Comment by TheManiax** [comment]
![wowscrnshot_012218_223234](https://user-images.githubusercontent.com/14857593/35238955-54921e02-ffc4-11e7-933e-28004ecf8609.jpg)
http://www.wow-mania.com/armory/?item=109013
I checked with another tester before I confirm it :)
