### ISSUE TITLE
wow problem on loading... was ok before this new patch

### ISSUE THREAD

**Issue by mauriciodv7** [WoWManiaUK/Redemption#2148]
Hello there

I have a problem with wow... when it loads and load the char it crash... this was not happening before todays patch...

![1d8691dd-1737-4eaf-b18c-6286307f419f](https://user-images.githubusercontent.com/35744701/35299672-97d9c7dc-004b-11e8-8ab3-69a1dde55376.jpg)

**Comment by fvicaria** [comment]
This is not a server issue. It's a local issue.
