### ISSUE TITLE
Quest Bug WinterSpring

### ISSUE THREAD

**Issue by RavenDarkCloud** [WoWManiaUK/Redemption#2150]
Winterspring Quest, Your suposed to hunt down Winterfell runners to get a supply crate off them and turn mission in , however, They dont seem to be respawning in there normal location, and the map Quest indication to show for the area your to look in seems to be bugged as well. Been looking for them for a couple hours, just in case there registered path go wonky i check all the roads and sections off the side of the roads but came up empty, if it could be looked into, it'd be apreciated greatly.
Ty,

**Comment by RavenDarkCloud** [comment]
ok found the buggers, and hopefully Place this on forums or something for future Questers as well.
![inkedwowscrnshot_012318_224129_li](https://user-images.githubusercontent.com/35549718/35315104-9455d20c-0098-11e8-871d-d094621c5285.jpg)
![runners path wintergrasp](https://user-images.githubusercontent.com/35549718/35315113-9dda48a8-0098-11e8-9826-799264ad12ab.jpg)
![winter fell runner path](https://user-images.githubusercontent.com/35549718/35315116-a2a78aee-0098-11e8-8984-dc1740160fdb.jpg)

**Comment by fvicaria** [comment]
Please follow the procedure described below before creating a new issue:
[How to Properly Report an Issue](https://github.com/wow-mania/Redemption/wiki/How-to-Properly-Report-an-Issue)

This will help developers identify and fix the issue quicker. Incorrectly or unclear reports will simply be deleted.
