### ISSUE TITLE
[NPC]-Spirit Healer-Wintergrasp

### ISSUE THREAD

**Issue by Bartok14** [WoWManiaUK/Redemption#2151]
The Spirit Healer in Wintergrasp located on the very western edge, when you are assaulting the fort does not seem to resurrect your character at all. The timer simply refreshes every every 30 seconds so you have to fly to another location. The area is called the chilled quagmire.

**Comment by fvicaria** [comment]
Use the dialog

**Comment by fvicaria** [comment]
![image](https://user-images.githubusercontent.com/9414661/35336458-5e1db5a6-0110-11e8-8e9e-30058acd8717.png)

Working fine in dev.
