### ISSUE TITLE
bugged quest

### ISSUE THREAD

**Issue by bipin2802** [WoWManiaUK/Redemption#2152]
after killing Lick king with SM i got unsealed chest which dropped several items to complete quest out of which 1 item [jaina's locket](http://www.wow-mania.com/armory?item=51318) cant be turned in and i cant get portal making locket i m still on quest Lick king's last stand and i still have that item in my inventory. this is quest which should be turned in but there is no jaina there (http://www.wow-mania.com/armory/?quest=24916).
![wowscrnshot_012418_192241](https://user-images.githubusercontent.com/35769669/35335608-08469a22-013c-11e8-94db-1b3c29e8934d.jpg)

**Comment by fvicaria** [comment]
Please follow the procedure described below before creating a new issue:
[How to Properly Report an Issue](https://github.com/wow-mania/Redemption/wiki/How-to-Properly-Report-an-Issue)

This will help developers identify and fix the issue quicker. Incorrectly or unclear reports will simply be deleted.

**Comment by fvicaria** [comment]
Quest works. If you waited too long and the raid ID expired you will have to do it again.

**Comment by bipin2802** [comment]
Can u explain how did i turn other items and was not able to only this one, and my raid ID is still there  it will expire on this reset which is tomorrow

**Comment by fvicaria** [comment]
You tell me. Many others have done it just fine.
I will check if there is a spawntime issue with that NPC.

**Comment by bipin2802** [comment]
thats the thng thats happening to me in this quest line, i wasnt able to loot shards, last 3 raids i took GM assist to give me shards from bosses

**Comment by fvicaria** [comment]
What is the char name?

**Comment by bipin2802** [comment]
still have raid ID for 25nm on which i killed LK with SM and it will reset tomorrow. charcter name Divinebip online atm.

**Comment by LooneyBin** [comment]
after well over a month, then i finally got the same quest completed tonight (6 x 25 hc lk kills, and same on norm).
