### ISSUE TITLE
Missing Heirloom Item

### ISSUE THREAD

**Issue by TheGreyMouser** [WoWManiaUK/Redemption#2153]
I seem to be missing a tattered dreadmist mantle.  I have one on the Fafhrd character in bags, but that one became soulbound when I applied a shoulder enchant.  It doesn't affect the BoA status in blizzard. However, on wow-mania it does.  So a staff member duplicated me a new tattered dreadmist mantle.  That is the one I can't seem to find now.   Is it possible to remove the enchant on the item on Fafhrd so I can mail it to my new alts? Or locate the missing item?
Thanks in advance.

**Comment by fvicaria** [comment]
This is not a server-side issue.
If you damage, enchant, or change in any way an item it becomes soulbound.
Send me a message on skype or email and I will try to help you.
