### ISSUE TITLE
[Raid] Vanquisher Marks of Sanctification

### ISSUE THREAD

**Issue by CrustyMuffin** [WoWManiaUK/Redemption#2157]
Our guild has done icecrown citadel 10  and 25 man on normal and heroic difficulty and what we noticed is, that nearly 80-100% of all Sanctification Marks were "Vanquisher Marks of Sanctification" (http://www.wowhead.com/item=52025/vanquishers-mark-of-sanctification). Today on our ICC 25 hc all marks were Vanquisher´s.

**Comment by Hypobaricsole08** [comment]
And all the Heroic Marks from ICC 25 Heroic are Vanquishers too, 0% Conquers or Protection marks in the last 1month or so.

**Comment by CrustyMuffin** [comment]
I talked with some guys from Harbingers Disciples and they had that issue too. That problem happens mostly on 25 heroic

**Comment by ragehoof72343** [comment]
In icc 25 heroic 1-2 vanquisher mark(heroic)  droping every week.also normal marks too

**Comment by fvicaria** [comment]
This is called probability. If you toss a coin 5 times and get 5 heads do you say it is fixed? :)

**Comment by Munja357** [comment]
It's not normal when you see vanq marks droping for last 5 weeks!

**Comment by fvicaria** [comment]
Well now it's not a raid anymore, now it's 5 weeks. Why was that not mentioned in the report?
I will check.

**Comment by HDArokh** [comment]
ya we got the same problem at HD's.  25hc raids, during 5 weeks full 12 / 12 clears  every single wing boss drops Vanq hc marks for the past 5 weeks. Reason why we havent reported this earlier because we werent sure is this just bad luck or something but this is getting ridiculouss.

**Comment by CrustyMuffin** [comment]
Sorry forgot to write that it happened to us over the last few weeks and that we aren´t the only on facing that issue.

**Comment by TheManiax** [comment]
I will do some tests to check the drop rates in action, Janitor will check the codes again as well.
If it is bugged, I will re-open the issue.
Thanks for informations.

**Comment by TheManiax** [comment]
You can not rely on 2x nm run and 2x hc run but still.
All marks are being dropped, here is the result:

- 25nm-First run:
DBS: 2x NM-conq
PP: 2x NM-vanq
BQ: 1x NM-vanq  +  1x NM-conq
Sind: 1x NM-vanq +  1x NM-conq
LK: 1x NM-prot  +  1x NM-conq
- 25nm-sec run:
DBS: 1x NM-prot + 1x NM-van
PP: 1x NM-conq + 1x NM-prot
BQ: 1x NM-vanq + 1x NM-conq
Sind: 1x NM-vaq + 1x NM-conq
LK: 2x NM-conq
**Total drops:
NM vanq: 7
NM conq: 10
NM prot: 4**
--------------------
- 25HC-First run:
DBS: 2x NM-vanq
PP: 2x HC-vanq 
BQ: 1x HC-prot + 1x NM-vanq
Sind: 1x HC-conq + 1x NM-pro + 1x NM-vanq
LK: 2x NM-prot + 1x NM-conq + 1x HC-conq

- 25HC-Sec run:
DBS: 2x HC-vanq
PP:1x NM-prot + 1x HC-vanq
BQ:1x NM-prot + 1x HC-conq
Sind: 2x NM-vanq + 1x NM-conq
LK:2x NM-vanq + 1x HC-vanq + 1x NM-prot
**Total drops:
NM vanq: 8
HC vanq: 6
NM conq: 2
HC conq: 3
NM prot: 5
HC prot: 1**

**Comment by Munja357** [comment]
But still you have agree that vanq mark drop rate is incresed on 25hc, maybe you can do few more runs and see.

**Comment by fvicaria** [comment]
I think it is good enough. Thanks for that.

**Comment by CrustyMuffin** [comment]
14 out of 24 marks are Vanquisher´s, that´s not normal. The issue is more severe on heroic. Please try out more times on heroic and you´ll see what we mean.

**Comment by Dranah** [comment]
Gonna do a big test later this evening with val's new fixes

**Comment by fvicaria** [comment]
Has been fixed today.

**Comment by VA-L** [comment]
Alright,

I've made a fix for it and id 8 runs 25HC to test it.

For 8 runs 25 HC :

- 104 marks overall
- 58 NM marks
- 46 HC Marks (18 Vanq HC / 12 Prot HC / 15 Conq HC)

I think this is good enough.
For 4 runs, i had 6 Vanq HC / 6 Prot HC / 9 Conq HC so the drop rate is equal for each now, it just depends of the chance.

**Comment by squalllh1989** [comment]
This problem has come back again, we do 3 icc25hc each week, and for 3 week we only seen 1 heroic protector's mark, all the other heroic mark is vanquiser, can you look over this again please.

**Comment by wow-mania** [comment]
Nothing changed here. This is a statistical and probability issue hence why people think sometimes is fixed and sometimes is magically broken again. I can give you guys another placebo dose of "it's fixed now". :)

**Comment by Hypobaricsole08** [comment]
Ive done about 2-3 ICC 25HC every week on different toons and different guilds + 2 pug runs and ive only seen normal marks and Vanquisher hc marks drop, im a big fan of that since my toons use them 😝 but for those using conq and prot hc marks i feel bad for since belive it or not they havent droped for the past 3 weeks.

**Comment by Keader** [comment]
I search about it, and everything is correct. Has correct chances.
Only creatureid 39168 i found a error, 39168 was duplicated mark loot (already send a fix to janitor)
I will search if has some hack in code changing items change anyway.

**Comment by squalllh1989** [comment]
hope that this will be solved soon, because when you see only 1 of like 30 heroic mark drop is protector, 29 other is vanquiser and no conquerer that's not fun and everyone will of course think that something is wrong for sure.

**Comment by Dranah** [comment]
I don't think people are seeing ghosts because this bug was also fixed by Val back then, and like most of his fixes recently, it's likely that this has been reverted by a random update too.
(val explained to me that he made most of his fixes in general mechanisms, which can be messed up by core updates)
So it was not a placebo effect, Val had actually fixed this back then (the results he got on his last test match the intended rates), but much like his other fixes, this seems gone too.
