### ISSUE TITLE
[NPC] HighElf Model Eyes (IDs inside)

### ISSUE THREAD

**Issue by IvoireThePaladin** [WoWManiaUK/Redemption#2159]
What they look like with the original 3.3.5a client:
![2888o](https://user-images.githubusercontent.com/29024329/35473978-cbcdedf4-0355-11e8-83f6-97ba238805a1.jpg)

What they look like with WoW-Mania's 2.2.1 client:
![2888](https://user-images.githubusercontent.com/29024329/35474001-42ec2f72-0356-11e8-8aa6-0bec6deac3a1.jpg)

NPC's effected (That I was able to check, I think there is a HighElf in Honor Hold):

Badlands:
2888 - Garek
17097 - Advisor Sarophas

EPL:
11704 - Kriss Goldenlight
11706 - Adon
10304 - Aurora Skycaller
8563 - Woodsman
8565 - Pathstrider
8564 - Ranger
12322 - Quel'Lithien Protector
10824 - Ranger Lord Hawkspear

**Comment by fvicaria** [comment]
As-is. We will not be fixing this anytime soon.

**Comment by IvoireThePaladin** [comment]
Okay, don't gotta be a jerk about it.

**Comment by fvicaria** [comment]
I have not but I can if you press the wrong button.
