### ISSUE TITLE
Polymorph spell not working as intended.

### ISSUE THREAD

**Issue by TheGreyMouser** [WoWManiaUK/Redemption#2160]
Polymorphed mobs are still shooting, casting, attacking and causing damage, even in "sheep" form.
Noted on Defias in westfall and Freebooters in Tanaris.  Polymorph is also causing other targets nearby to aggro but that may be normal.

**Comment by TheManiax** [comment]
http://www.wowhead.com/npc=7856/southsea-freebooter
http://www.wowhead.com/npc=594/defias-henchman
http://www.wowhead.com/npc=449/defias-knuckleduster
http://www.wowhead.com/npc=589/defias-pillager
http://www.wowhead.com/npc=6180/defias-raider

**Comment by Keader** [comment]
ready to test 👍

**Comment by Magabro** [comment]
Tested on Southsea Freebooter.  Appears to be working on dev.
![wowscrnshot_012818_141552](https://user-images.githubusercontent.com/34353250/35487881-e1a1f6ee-0435-11e8-94d3-8ff2790620d7.jpg)

**Comment by Magabro** [comment]
Tested also on Southsea Freebooters.  Seems fixed
![wowscrnshot_012818_142334](https://user-images.githubusercontent.com/34353250/35487986-eb39843c-0436-11e8-82dc-1ae90bb00a78.jpg)
