### ISSUE TITLE
[Quest] Elune's Blessing

### ISSUE THREAD

**Issue by HDArokh** [WoWManiaUK/Redemption#2162]
#I tried to do the quest with my friend and we noticed that the Dog ( Omen ) that u need to kill was already at the spot , it was targetable but we couldnt hit it or anything, we tried to swap new one next to that one but didint work. i made Ticket to GM's and Amytis checked it. he used commands to kill it but after that this happened ( screenshot under ).
![1](https://user-images.githubusercontent.com/35156397/35476291-01e7bb8a-03b6-11e8-8e5c-934eebaa894d.jpg)

dog is dead in this picture as u can see but then when u walk close to it this happens ....... 

![2](https://user-images.githubusercontent.com/35156397/35476301-1806ba9c-03b6-11e8-8083-adaec9474e42.jpg)

the dog starts hitting u and u cant kill it so ...... GG.

**Comment by Magabro** [comment]
Tested this with 3 characters.  First time completed as normal. no issue.
Second time i summoned Omen with 1 char then logged and swapped to another char.  No issue and was able to complete quest.
Third time we spammed rockets to summon as many Omen as possible.  Only 1 came at a time and no issues caused.

If you have additional information that may have caused your problem please provide but at this point we cannot reproduce the bug you experienced :(

**Comment by HDArokh** [comment]
nah i just arrived there and the Dog was bugged there so =/ , currently u cant spawn new one because the old one is dead there hitting ppl who ever goes close. might just need to remove that bugged one.

**Comment by TheManiax** [comment]
I suggest you to try it again after a while.
A server restart will reset it properly for sure.

**Comment by HDArokh** [comment]
ya will try thx for fast reply

**Comment by HDArokh** [comment]
ok server crashed about few Hours ago , tried again and it was working. apparently just small bug.
