### ISSUE TITLE
[Spell] - Reflecting Succubus Seduction will make her charmed

### ISSUE THREAD

**Issue by VA-L** [WoWManiaUK/Redemption#2163]
Currently when warlock's succubus is casting [Seduction](http://www.wowhead.com/spell=6358/seduction) and a warrior [reflects](http://www.wowhead.com/spell=23920/spell-reflection) this, the channel breaks but the succubus gets charmed even though it was broken.

![inkedwowscrnshot_012718_235009_li](https://user-images.githubusercontent.com/11377592/35477588-4ad52660-03c6-11e8-8f2d-76c98d413c83.jpg)

Warlock's succubus shouldn't get charmed if [seduction](http://fr.wowhead.com/spell=6358/seduction) gets reflected, the channel should break without any consequences for the succubus.

**Comment by Dranah** [comment]
The spell is now properly reflected and the Succubus doesn't get charmed anymore.
