### ISSUE TITLE
[Talent/Buff] Rampage

### ISSUE THREAD

**Issue by Loktard** [WoWManiaUK/Redemption#2164]
If two fury warriors are in a group/raid group and one of them is switching to a non fury offspecc and back into his fury specc again his Rampage buff will not overwrite the buff of the other warrior instead he gets a double buff. It's only affecting the specc switching warrior other party members do not benefit from it.
The bug is easy to spot, the specc switching warrior will have two Rampage buff icons. It's also not just a visual bug the crit stat is increased.

http://www.wowhead.com/spell=184367/rampage

**Comment by Dranah** [comment]
Works fine on dev now.
