### ISSUE TITLE
[Quest] A Mammoth Undertaking

### ISSUE THREAD

**Issue by takeo87** [WoWManiaUK/Redemption#2166]
After ride the mammoth it go back and the player loss the controll

**Comment by fvicaria** [comment]
Please follow the procedure described below before creating a new issue:
[How to Properly Report an Issue](https://github.com/wow-mania/Redemption/wiki/How-to-Properly-Report-an-Issue)

This will help developers identify and fix the issue quicker. Incorrectly or unclear reports will simply be deleted.

**Comment by TheManiax** [comment]
[A Mammoth Undertaking]( http://www.wowhead.com/quest=12607/a-mammoth-undertaking)
Player has to use Provided [Mammoth Harness](http://www.wowhead.com/item=38627) to Bring a [Shattertusk Mammoth](http://www.wowhead.com/npc=28379/shattertusk-mammoth) to [Zootfizzle](http://www.wowhead.com/npc=28374) at Dorian's Outpost.

**Comment by fvicaria** [comment]
Same issue as #2161 - needs generic fix.
