### ISSUE TITLE
cant buy friendly tabard of the kirin tor

### ISSUE THREAD

**Issue by mekono** [WoWManiaUK/Redemption#2167]
hi i cant buy friendly tabard of the kirin tor even though i have 859/6000 friendly rep with the kirin tor, what should i do?
![untitled](https://user-images.githubusercontent.com/35908516/35492219-925d2452-0479-11e8-96e8-1640defdf588.jpg)

**Comment by fvicaria** [comment]
You need 3000 rep. I sorted it for you.
