### ISSUE TITLE
[Boss] Freya-Ulduar

### ISSUE THREAD

**Issue by Bartok14** [WoWManiaUK/Redemption#2168]
So tonight me and my guild worked our way up to Freya on Ulduar. I'll start by saying thanks to all the Developers who helped fixing any issues along the way. I'm going to report more on Ulduar next week when I have a chance to review how some of the fights are supposed to work (Mainly the first boss on hardmode), but for the most part all the bosses we killed today seemed to be working fine.  

At any rate the previous issue with Freya that I posted does indeed seem to be corrected, as you can now see the sunlight beams without any issue. Thank you very much for that. There are still two issues with the fight however that I saw today.

1)Solar Flare is cast on way to many raid members. If you look at any older videos from people doing the quest on retail, 10 man should have Solar Flare being cast on a single member of the raid, whereas I believe on 25 man there should be a maximum of 3 beams being cast. 
Link's to some videos for review:
https://youtu.be/HJ1gxZZSRtI
https://youtu.be/w2w2973jfBo

As you can see from this picture on 10 man it is being cast way too often usually with a minimum of 4 casts and a max i think tonight i saw of 7. 
https://media.discordapp.net/attachments/319713049768493057/407377855572344842/unknown.png?width=960&height=405
The fight was still doable on hard mode, we just had to change our strategy and no one was allowed to stack at any point because if you do then 3 beams on top of the same person is pretty much a guaranteed wipe since it will tick for 12 k damage instead of 4 k. This no stacking did make the fight more difficult when we had to coordinate with the mushrooms, I imagine that 25 man would be really hard to do since there aren't many places to stand when 4-5 mushrooms got Solar Flare's on them. Again the fight was doable but you may want to fix this so that it's more realistic towards what it was like on retail. I should mention that this did make the fight more fun though :)

2) Issue 2 is that adds will continue to spawn even after phase 2 begins. It's supposed to work where as soon as you kill the 6 waves of adds that she will not spawn more and will be focused on throwing out get seed pods. We only saw her do this once I think, when she is supposed to do it more often. Having her spawn adds in phase 2 could get really tough if she spawns a guardian spirit as then everyone has to stack for the mushrooms and also dodge the pods. 

Thanks for working on the issues, sorry I had to bring you more this week.

**Comment by fvicaria** [comment]
Haven't we gone through this one before?

**Comment by fvicaria** [comment]
reopen #2136 we cannot continue fixing issues and have them returning with different details.

**Comment by Bartok14** [comment]
Hey Janitor, I wasn't trying to report issues with the fight that were already known. Last week when I reported the original post it was that I couldn't have known about these two issues, the reason being that we didn't see the spell Solar Flare being cast, so we couldn't have known that there were too many casts going off at once. The second issue we couldn't have known because we could not make it to phase 2 last week as we were wiping on the fight due to solar flare not having a visual indication. Sorry for any confusion as to when I posted this topic. I'm going to make a forum post about suggesting perhaps that you update the suggestions for making a topic. The reason for this is that I had received an email today that said I was supposed to re open the original post on Github today, and I don't have the authority to do that. Also I'm not sure if you and the other Developers read closed topics if I post further information on them. If you could clarify for me in the future what you want me to do. 

My current plan is to continue posting any NEW issues that I find in Ulduar, after the previous fixes have been implemented. Do you want me to make a new topic about this? Or will you see any new issues that I submit to closed topics?

**Comment by Keader** [comment]
It's no Solar Flare btw ^^

**Comment by Bartok14** [comment]
In the matter of whether the ability is sunbeam or solar flare to the best of my knowledge it's called Solar Flare. Sunbeam is the ability that Freya Casts during the regular 10 and 25 man attempts. Elder Brightleaf will cast Solar Flare which is the aoe dot that stays in place for about 8 seconds or so. Since you don't kill him on the hard mode attempt it allows Freya to cast both Sunbeam and Solar Flare. I've marked the image here so that you can distinguish the difference in the animations.

![ulduar freya solar flare marked](https://user-images.githubusercontent.com/32959403/35550417-4aa5948e-0558-11e8-8e3b-4e888da7939b.png)


A link to both abilities can be found here as well as a link to Elder Brightleaf:
http://www.wowhead.com/spell=64087/solar-flare
http://www.wowhead.com/npc=32915/elder-brightleaf#abilities
http://www.wowhead.com/spell=62872/sunbeam#used-by-npc
