### ISSUE TITLE
[Item] Battered Hilt

### ISSUE THREAD

**Issue by GMWeeble** [WoWManiaUK/Redemption#2170]
Item " http://wow-mania.com/armory/?item=50379 " Worgens are not able to roll or start the quest. goblins are able to do it for the Horde version.

**Comment by fvicaria** [comment]
What is the quest? The item does not tell us anything.

**Comment by Hajzlopuc** [comment]
http://wow-mania.com/armory/?quest=14443 
item should start this quest

**Comment by VA-L** [comment]
The issue was that worgens were not able to press the "Need" button on the roll window.
This is fixed.

**Comment by Dranah** [comment]
Worgen can now press need on the drop, accept and finish the quest as well.
