### ISSUE TITLE
[NPC] Flamewalker Imp

### ISSUE THREAD

**Issue by patrickhousley** [WoWManiaUK/Redemption#2172]
The Flamewalker Imp does not appear to be working correctly in outlands. It begins to cast when engaged but then the walking script takes back over, so it seems.

http://www.wowhead.com/npc=19136/flamewaker-imp

**Comment by squalllh1989** [comment]
Confirmed.
-  If you engaged in combat from distant, the mob only cast 1 fireball, then doesn't cast it again, and it doesn't even wanna walk to attack you, just stand there look at you.
- If you are warrior and you charge to it, it will hit you with melee hit and doesn't ever cast firebolt, if you run away it will just sit there watch you go away.
- If you walk to it and melee it, it will start attack you with melee hit and will chase you when you try to run away, doesn't ever cast firebolt again.

**Comment by fvicaria** [comment]
This is as-is. Imp will cast fireball only once if you are not at melee range (5-40m).
