### ISSUE TITLE
[Mob] Bonechewer Evoker

### ISSUE THREAD

**Issue by patrickhousley** [WoWManiaUK/Redemption#2173]
The Bonechewer Evoker npms only cast fireball once and then stand still until their evade script kicks in.

http://www.wowhead.com/npc=19701/bonechewer-evoker

**Comment by squalllh1989** [comment]
Doesn't know what you mean, this mob working good for me, they cast fireball when they can, until their mana run out, and chase after you and melee hit when they are out of mana

**Comment by squalllh1989** [comment]
I will close it for now, if you can please explain more about how to reproduce your situation to make it like so.
