### ISSUE TITLE
[NPC] Thrall-Old Hillsbrad Foothills

### ISSUE THREAD

**Issue by Bartok14** [WoWManiaUK/Redemption#2176]
Two issues I found with this instance. Only the first one is a real issue, the other still works just not as intended as far as I can tell.

1.

 - Due to lvl 80 running this raid and the ability to fly inside you can skip most of the mobs when you get to the castle after planting the [Incendiary Bombs](http://www.wowhead.com/item=25853). 
 - When you talk to [Thrall](http://www.wowhead.com/npc=17876/thrall) in the basement and he goes to get his gear from the front right room on the main floor, he will then start running through the walls of the castle and you don't know where he goes to, essentially a pathing error I think.
 - Because you don't know where he goes and also don't have to kill the mobs he can sometimes end up dead if you don't get to him fast enough.

2. 

 - [Incendiary Bombs Planting](http://www.wowhead.com/spell=32744/planting-incendiary-bomb) work well enough to get to thrall, however the counter at the top of the screen will tick as soon as you right click on a barrel and also once you are done planting the incendiary bomb. 
 - Can also place multiple incendiary bombs on the same barrel. I'm pretty sure you are supposed to go to different [barrels](http://www.wowhead.com/object=182589/barrel) to plant all 5.

If you need screenshots let me know but if you run it once I'm sure you will see the issues.

**Comment by fvicaria** [comment]
Should be quick to solve.

**Comment by fvicaria** [comment]
All issue solved except the movement path. There are some map issues that I don't know how to solve.

**Comment by Sugarconepk** [comment]
Went through the dungeon normally, while the incendiary barrels work as they should now, the pathing error is still there, however.

**Comment by fvicaria** [comment]
Pathing cannot be fixed. Just stay close or ahead of Thrall killing the mobs.

**Comment by Sugarconepk** [comment]
If it's any help, thrall leaves from the left side of the exit, through the wall after he's done walking around the spot.

**Comment by fvicaria** [comment]
I may try to change the path again but it did not help last time I tried.

**Comment by fvicaria** [comment]
As I said there is no more fixing to do here. The map is the issue and it can't be fixed.
The workaround is to kill all guards along his path out before you go talk to him.

**Comment by Bartok14** [comment]
The only other thought I might have on this is that maybe it's a server wide issue. In some instances and raids, especially if there is a gauntlet involved it seems sometimes that some of the mobs are able to run through the walls. If you initiate any type of gauntlet in a raid and someone isn't in the room, the mobs essentially run through the walls trying to get to that person. It has happened in a few areas of the server. So maybe it just might be an issue where the mobs are able to pass through barriers which the players aren't able to.
