### ISSUE TITLE
Worgen image bug

### ISSUE THREAD

**Issue by magnobk** [WoWManiaUK/Redemption#2178]
After downloading the game and starting to play, I noticed that in the creation and in the game all Worgen has no image, appearing in place a small cube checkered in the colors blue and white, please help me.

Below is a print screen of the problem.

[](url)http://prntscr.com/i8q3oo

**Comment by Hajzlopuc** [comment]
Have you downloaded all wow-mania patches via Launcher? Should be version 2.2.2 now.

**Comment by magnobk** [comment]
I didn't know it was necessary to download the other patches for this know it was necessary to download the other patches for this

**Comment by Hajzlopuc** [comment]
Launcher.exe should download them all for you up to last patch which is 2.2.2 now. Please run the launcher, let it download and patch, then run a game and try again with Worgen. Login screen should look like this with the latest patch: https://puu.sh/zepJb/4fbbf5c93a.png

**Comment by GMZinius** [comment]
For notes: Fixed here #3392
