### ISSUE TITLE
[Quest] Scarlet Diversions (5096)

### ISSUE THREAD

**Issue by IvoireThePaladin** [WoWManiaUK/Redemption#2183]
http://www.wowhead.com/quest=5096 (EPL - 40.9 , 51.9)
http://www.wowhead.com/item=12807

I was able to burn the tent but I wasn't, for the life of me, able to find the quest trigger. The item kept giving me an "Requires Scarlet Crusade Forward Camp" error. I tried using it all over the camp and checked a video ( https://youtu.be/_9jV2sj97m4?t=1m36s ) about the quest which shows where the banner gets placed and tried it there but was unsuccessful.

![wowscrnshot_020118_221021](https://user-images.githubusercontent.com/29024329/35714792-c2682da6-079c-11e8-85f9-ff274c42e2d4.jpg)
As you can see i'm directly on top of the spawn point and getting the error.

I contacted a GM at this point and they asked me to clean the client cache and remove my addons in addition to making sure I was using the current wow-mania custom MPQ files (2.2.2, unmodified) which I complied with. I was then instructed to post here.

**Comment by squalllh1989** [comment]
Maybe you should try harder, "for the life of you" >.<. The quest work. **You can place the banner at the tent after you burned it**. Here is some screenshot i take when i test this out, you can use them if you got stuck some where in the progress.

![wowscrnshot_020218_133017](https://user-images.githubusercontent.com/27235989/35719775-9e0861ca-081d-11e8-80a1-a826cca04992.jpg)
![wowscrnshot_020218_133042](https://user-images.githubusercontent.com/27235989/35719782-a220f3ee-081d-11e8-9c39-df90e6659e50.jpg)
![wowscrnshot_020218_133045](https://user-images.githubusercontent.com/27235989/35719783-a52e2d22-081d-11e8-9a18-dfa078fb4f9a.jpg)
![wowscrnshot_020218_133051](https://user-images.githubusercontent.com/27235989/35719785-a7719380-081d-11e8-8b2c-3d09a90a4be0.jpg)
![wowscrnshot_020218_133058](https://user-images.githubusercontent.com/27235989/35719786-a923ef52-081d-11e8-87e9-0a1aa1a0997f.jpg)
![wowscrnshot_020218_132923](https://user-images.githubusercontent.com/27235989/35719794-b04d51ce-081d-11e8-8fb4-9aa22fbd57cf.jpg)

**Comment by IvoireThePaladin** [comment]
Oh, You have to be super quick to get credit. I know some quests can have really strict requirements on positioning (like the rift reading in The Nexus) but I didn't expect needing to do it so quickly after burning the tent. Thanks for showing me and sorry for wasting your time..
