### ISSUE TITLE
[Item] Everfrost Chip

### ISSUE THREAD

**Issue by Amadine** [WoWManiaUK/Redemption#2184]
Hi.
In Storm Peaks there spawn objects called "Everfrost Chips". When opened they have a chance to give a grey merchant fodder item and - if your faction with Sons of Hodir is friendly or higher (comments on wowhead) - a quest item also called "Everfrost Chip". The first of those you get starts a quest and after that it's a "blue ?" type of q you can repeat until rep is maxed.

I opened about 20+ of these Everfrost Chips and never got the q starter item. My faction is currently at friendly. 

Could you please check if it really works as intended?
Thank you

**Comment by fvicaria** [comment]
Please follow the procedure described below before creating a new issue:
[How to Properly Report an Issue](https://github.com/wow-mania/Redemption/wiki/How-to-Properly-Report-an-Issue)

This will help developers identify and fix the issue quicker. Incorrectly or unclear reports will simply be deleted.

**Comment by fvicaria** [comment]
This is the item related to the following 

Quest:
https://www.wowhead.com/quest=13420/everfrost

Item:
https://www.wowhead.com/item=44725/everfrost-chip

Object:
https://www.wowhead.com/object=193997/everfrost-chip


You need to be at least Friendly with SoH and not have done the above quest before or item will not drop. The chance is around 19%.

**Comment by fvicaria** [comment]
Fixed conditions. Working fine in dev now.

**Comment by fvicaria** [comment]
It's fixed in our Public Test Realm (PTR) and should be pushed to live in the next restart/update.

**Comment by Amadine** [comment]
Thank you very much!
