### ISSUE TITLE
Containing the Rot - Rot Reistant Organ Drop rate

### ISSUE THREAD

**Issue by xssxtricky** [WoWManiaUK/Redemption#2186]
Hi i believe there is an issue with the second half of the quest which is a quest item drop. The first part of the quest is a kill quest *Infected Wildlife slain 15* I had the quest item drop after 200 mob kills. I have spoken with other players on the server and this looks like a common issue where most where around 100 or more. I would just ask that the drop rate on Rot Resistant Organ be upped a bit. This quest starts a chain and i honestly spent more time killing these mobs then i ever did on retail.

http://www.wowhead.com/quest=12100/containing-the-rot

Also there was 1 other post here about this. The creator of the post closed the post when it dropped on his 4th day trying for it. Imo worth looking into.

**Comment by fvicaria** [comment]
As explained the drop rate is about 2%, meaning ON AVERAGE you would need to kill about 50 to get one.
On average doe not mean you kill 50 and get exactly get 1. You could kill 100 and still have nothing.

You do not say a coin is "rigged" if you throw it twice and get 2 heads do you?
