### ISSUE TITLE
[Spell] Shadron's portal (Obsidian Sanctum)

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#2187]
Hello,
I'm reporting Shadron's (Sartharion's second drake) missing portal based on consulting with Val. 

How it should work:
Shadron (http://www.wow-mania.com/armory/?npc=30451)
- When engaged alone, he should spawn a portal after about 30seconds, just like the other two drakes, and gain the Gift of Twilight (http://www.wow-mania.com/armory/?spell=57835) buff which increases his shadow damage and makes him immune to attacks.
- In order to remove this buff and be able to kill him, players must enter his portal and kill the acolyte found there
- When engaged together with Sartharion, after his portal spawns, a different buff is applied (http://www.wow-mania.com/armory/?spell=58766) not on himself, but on Sartharion, increasing fire damage done, and make him immune to attacks, until the acolyte inside the portal is slain.

How it works at the moment:
No portals are spawned, immunity buffs aren't used, neither alone, nor when engaged with Sarth.

**Comment by fvicaria** [comment]
Keep one issue per boss or spell

**Comment by flumby** [comment]
Shadron Fight Alone
Portals already there but do not activate after 30 seconds. No buff is given to the boss and seems mostly just a tank and spank with the odd cast of ground void.

Also the other dragons dont get immune to damage during the portal phase which is only working on the other two dragons.

**Comment by flumby** [comment]
When you engage the boss with Shadron alive, the boss seems to get a buff of increase health by 25% but thats it, no damage buff occurs.

**Comment by Dranah** [comment]
Yup he doesn't do his special still. No change yet

**Comment by fvicaria** [comment]
The change was about the spawn and buff

**Comment by fvicaria** [comment]
Behaviour now is exactly as for the other dragons.

**Comment by Dranah** [comment]
Umm, Shadron still does not activate his portal at all. Neither alone, nor with Sarth.
He does an emote time to time, "You are easily bested!" with nothing happening (i'm not sure what it's meant to indicate cuz according to WOWWiki, it is an "unused" emote.)

**Comment by fvicaria** [comment]
Found the issue. Should work now.

**Comment by flumby** [comment]
Nice one Janitor.

Sent from my iPhone

On 21 Feb 2018, at 11:23, Dranah <notifications@github.com<mailto:notifications@github.com>> wrote:


Still uses the same functionless emote and portals/immunities dont activate.

**Comment by Dranah** [comment]
no change

**Comment by fvicaria** [comment]
Well this is just not possible.
I will have to check it with you.

**Comment by Keader** [comment]
I'm stolen this issue (Janitor told me to do haha)
Fixed, can be tested in next restart.

**Comment by flumby** [comment]
So I have now retested this and I can state the following, this being one by my self:
Fighting Shadron Individually:
 - Boss activates portal and you have to fight an npc when in.
**Fighting Shadron with Sarth:**
 - The boss gets an increased health by 25%. 
 - The player gets increased fire damage taken
 - Shadron also activates his portal here and inside killing an npc again.

**Comment by Keader** [comment]
Looks like have weird behavior, i will remove some Val codes tomorrow.

**Comment by Dranah** [comment]
UPDATE:
- Shadron now opens his portal, BUT:
1. the first portal comes very late (1minute into the fight) instead of 15-20seconds after the drake is engaged (alone or by sarth). The follow-up portals should be coming after 1minute interval (if you havent killed the drake somehow yet). Note, this affects every portal now (vesperon and tenebron too), the first opening should be quite soon.
2. No portals are opened at all when someone is soloing the raid. It requires at least 2 players in combat for the portals to work (not only Shadron, again tenebron and vesperon ones too), which is not intended. (people on retail still complained expansions later too, that soloing shadron needs insane DPS, as you are required to kill him before the portal is opened, as it makes him immune and you cannot take the portal to dispel it)
3. Portal despawns really quick if not taken, also if someone takes them, it closes for other people very soon. You have maybe 10seconds to enter, afterwards it becomes inactive again and you're left with the buff on the boss, he never opens the portal again.
How it should work: the portal stays open as long as the add inside is alive. If it is killed, the boss opens next portal 1minute later.
4. Portal kicks you off after a rather short time, if you haven't finished the add yet (low dps or such), you get teleported out, portal is inactive and you're stuck with the buff on the boss.
5. If you do kill the add inside, the moment he dies and you're teleported out, Shadron gains a "will of sartharion" 25% health buff (this is the buff that should be present when you're doing Sarth+3d), god knows WHY, and the entire instance is pulled (every trash pack + the other two drakes), except for Sarth.
6. Shadron's immunity doesn't - fully - work. It makes him immune to most attacks, but debuffs that deal damage upon being applied (i.eg. Faerie fire feral, Moonfire, Devouring plague for shadow priest etc) still bypass his shield (the DOT ticks afterwards don't, only the initial damage)
4. When killing the add inside the portal,

**Comment by Keader** [comment]
rdy to test again

**Comment by Dranah** [comment]
Update:
- Fixed problem with whole instance getting pulled when you kill the mob inside portal
- Fixed problem with not getting portal when soloing
- Fixed problem with immunity buff getting bypassed
- Fixed problem with portal despawning after ~10seconds

Remaining problems
1. First portal is still very late. Should be around 15-20sec after pull (or 15-20sec after drake is engaged, when doing 3d), and then next ones with 1min intervals.
2. Portal becomes inactive after first person enters, others are unable to follow
3. Portal no longer kicks you off after you entered, but the mob inside despawns after 10-15seconds and you are stuck in the shadow realm with no exit portal or mob to kill (the buff persists outside on Shadron with no means to remove)
Note this occurs on 3d as well, on both Shadron and Vesperon disciples, when you enter to kill them, 10-15sec after you engage add, he will disappear and you won't be able to get out or remove the buff outside. (it looks similar to what happens to Tenebron's eggs, for those it is intended because they hatch outside as whelps if you don't kill them within 15sec... but the other two type of adds shouldn't behave like this. Also there should be an exit portal for you to leave shadow realm whenever you please.
4. Oh ya, there is generally no exit portal inside

**Comment by Keader** [comment]
After next restart is ready to test again

**Comment by Dranah** [comment]
Update:
- Fixed problem with portal becoming inactive after one person uses
- Fixed problem with exit portal missing and players getting stuck inside
- Fixed problem with mob despawning shortly after being engaged
- Fixed problem with Sartharion's portal being active by default

Remaining problems:

1. Portal timers are now shorter, but still not good at all. It must be 15-20sec before FIRST cast, and then 1min interval for next ones. Currently it is 30sec-30sec-30sec. Too slow for the first cast, way too soon for the follow-up ones. This problem affects all 3 kind of portals (vesperon/tenebron/shadron)
2. This is a new bug: Wiping or resetting encounter before killing the add that is already spawned inside the portal leads to that add not despawning. 
When you engage boss again, it is being there as a "second" add, which is not only an extra attacker inside, but the portal only allows you to kill 1 of the adds and then kicks the raid out, with the portal becoming inactive so you can't re-enter, but Shadron retains the immunity buff because of the add still inside.
3. Shadron's death does not despawn the add inside portal and does not remove immunity from Sarth

**Comment by Keader** [comment]
Fixed i think
Need be retested after next restart

**Comment by Keader** [comment]
Let me know the results dranah :)

**Comment by Dranah** [comment]
Update:

- Fixed problem with add inside portal not despawning after reseting/wiping encounter
- Fixed problem with Shadron's death not despawning add inside/removing immunity from Sartharion on 3d
- Subsequent portal casts now happen with proper 1min intervals

Remaining problems:
1. First portal is still cast rather late (30sec instead of 15-20s). 
This may seem irrelevant tweaking issue, but as there are 45sec intervals between the drakes landing and the average life span of a drake even without the raid being over-geared is barely 50-60seconds, this can make a difference. An icc geared raid can easily take out the drakes before their portal is used at all, right now.
2. Wipe/reset on Sartharion encounter doesn't despawn lava blazes and twilight whelps
3. This is something i simply forgot to report earlier: /spell=57557 triggered by /spell=56916?
"Pyrobuffet" is missing from the fight, this is the mechanism that should prevent the raid sitting outside Sarth's platform to dodge the lava waves. 
How it should work: Whenever a player leaves Sartharion's platform during the encounter, this nasty debuff is stacked on them every 8(?) seconds or so.

**Comment by Keader** [comment]
First Portal Fixed.
2 and 3 dont belong of this ticket.
is Shartharions bugs, need a Shartation issue.
