### ISSUE TITLE
[Pet] Warlock imp spell power coefficients

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#2189]
Hello,
This problem arose recently since the updates, it was working fine before.
Warlock imp's spells : 
Fire bolt (http://www.wow-mania.com/armory/?spell=47964) 
Fire Shield (cant find rank7 on armory so i'll link a lower: http://www.wow-mania.com/armory/?spell=8317) 
don't receive their bonus damage from the owner's spell power, their damage is same as when the warlock is naked.

How it works atm:
Firebolt deals the same average ~500 damage that is base damage after talents and glyph for destro lock, regardless of what the warlock has equipped. Same ~500 damage with 0 spell power on warlock as with 2500 spell power.
Same goes for his Fire shield, that deals the base 40-50 damage on reflect, with both 0 spell power as with 2500 spell power on the warlock.
Oddly, the bonus damage displayed on the imp's character sheet is correctly modified as the warlock equips gear, but the damage doesn't appear on the spells, so it is the spells coefficient that may be broken.

How it should work:
Firebolt should receive +71.43% from the bonus damage that the imp inherits from the owner and Fire Shield should receive about +1% of bonus damage per hit.

**Comment by fvicaria** [comment]
Unlikely that we will be doing any changes here but I will take a look.

**Comment by Dranah** [comment]
Firebolt now scales with the warlock's spell power as intended. Fire shield still doesn't, but that doesn't really affect gameplay.

**Comment by Midnaa** [comment]
Is affecting Death knight gargoyle too, doing 159 damage as best in slot dk...

**Comment by fvicaria** [comment]
Send me the actual spell and I can check.

**Comment by Midnaa** [comment]
51963
