### ISSUE TITLE
[Boss] Algalon

### ISSUE THREAD

**Issue by HDArokh** [WoWManiaUK/Redemption#2191]
I did Ulduar 10man Algalon fight with guildiess, We killed Algalon and looted the chest. after 5 sec looting the chest ( loot got done )   Algalon starts hitting ppl again with 35% hp left.  u try kill him, he stays at 1 hp and is unkillable and u have to wipe to get rid of him. after everyone run back he was still there with full hp. We started the fight again killed it again and got new loot. 

so problem is = Algalon Farmable with single raid ID and getting tons of loot.

**Comment by hotdoggidy** [comment]
http://wow-mania.com/armory/?npc=32871 (BOSS)

**Comment by HDArokh** [comment]
ah y that timer dissapeared after we killed him first time, on the second kill with same ID that timer wasnt there either.

**Comment by fvicaria** [comment]
You mean it respawns after 5 minutes?

**Comment by HDArokh** [comment]
no right after we wipe, the boss '' resets ''

**Comment by Midnaa** [comment]
The boss is still hostile faction after being defeated... he needs to be friendly after defeat

**Comment by Keader** [comment]
I'm waiting Dev's up to test algalon 💃

**Comment by HDArokh** [comment]
Algalon still bugged after fix.

**Comment by Keader** [comment]
I cant reproduce
