### ISSUE TITLE
[Boss] Cthun -  Dark Glare 

### ISSUE THREAD

**Issue by KrzysztofKarate** [WoWManiaUK/Redemption#2192]
# ISSUE:

**How spell should work:**
Dark Glare is a spell casted by Cthun (eye) every 75 seconds and lasting for 35. It deals 78750 to 101250 Shadow damage to all enemies in front of the caster. While casting this beam cthun slowly rotates 180 degrees (in 35 second window) clockwise or counterclockwise.

**This is how this spell looks like:**
https://c1.staticflickr.com/1/57/197612789_aa02629869_z.jpg?zz=1

**Here at 70s you can see how it should work:**
https://www.youtube.com/watch?v=hU1E-kyw8O4&t=70s

**What is the issue:**
On server redemption when Cthun(eye) begins to cast it he freezes and no animation is displayed (looks like spell was being casted in a single place - however it kills in completly different spots around cthun, which makes me sure that the beam is in fact rotating, just without any visual effects).

**Why this issue makes such big difference:**
This issue makes Dark Glare impossible to avoid (50% to be killed each time it is casted) and it 1-shoots 80 lvl geared players. While raiding 60 lvl raid with friends this can be really painful to discover that it is nearly impossible to kill last boss due to bug after a few hours spent to get to him.

**Steps to reproduce the problem:**
1) Fight C'Thun in the Temple of Ahn'Qiraj
2) Wait for him to cast 'Dark Glare' during the first phase of encounter

-----------------------------------------------------------------------------------------------
# POSSIBLE SOLUTIONS:

The problem itself is pretty straight forward, however I made some research that may help you fix it.

Apparently this bug used to be pretty common on blizzlike servers (Atlantiss for example). I have found topics with example code fixing it (I assume that as all servers base on wow source code, so solutions may be the same or very similar):

**Example topic with possible solution:**
https://community.atlantiss.eu/index.php?/topic/15483-npc-eye-of-cthun-dark-glare-rotation/

**Code on github written by him that may fix it:** 
https://gist.github.com/gecko32/3333dab5669ab2699a1aabdb298a31fa

Have a nice day,
Krakatau

**Comment by TheManiax** [comment]
- The animation is fixed.
--------------
**How it is working:**
- Deals ~40000 to ~60000 Shadow damage to all enemies around caster.

**How it should work:**
- Deals 78750 to 101250 Shadow damage to all enemies in front of the caster.

**Comment by Keader** [comment]
1 - Please dont remove Fixed in Dev Tag, original issue is fixed.
2 - Is not around of target, is a cone area with (24 y) in front of caster. Blame blizzard for it.

```
Effect 0: Id 2 (SPELL_EFFECT_SCHOOL_DAMAGE)
BasePoints = 43749 to 56250
Targets (24, 0) (**TARGET_UNIT_CONE_ENEMY_24**, NO_TARGET)
Radius (Id 12) 100,00
```

**Comment by KrzysztofKarate** [comment]
@TheManiax I agree with @Keader  its not around caster for sure. I was in a party with other player and only 1 person was killed at the time. Mechanics of the spell was working correctly. Only issue was that the beam was not visible to the players. @Keader do you know when this update will be pushed to server so I can verify ?

**Comment by Keader** [comment]
Need confirm with Janitor, i guess tomorrow or 1 day after xD

**Comment by KrzysztofKarate** [comment]
@Keader thanks!

**Comment by TheManiax** [comment]
@Keader  @KrzysztofKarate 
That's true.
I checked the first script again.
The beam was rotating, just not showing the proper animation.
