### ISSUE TITLE
[Item] Meta Gem requirements

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#2193]
Hello,
I found a problem with Meta Gems not being properly activated when the required colors are socketed into "extra sockets" on items that did not have socket slots before.
1) Belt via http://www.wow-mania.com/armory/?item=41611 eternal belt buckle
2) Bracers or Gloves via Socket Bracer http://www.wow-mania.com/armory/?spell=55628 or Socket Gloves http://www.wow-mania.com/armory/?spell=55641 (Blacksmith-only)

I tested the 2 most common DPS metas, Chaotic Skyflare http://www.wow-mania.com/armory/?item=41285 and Relentless Earthsiege http://www.wow-mania.com/armory/?item=41398
- Chaotic Skyflare requires 2 blue gems to activate
- Relentless Earthsiege requires one 
- Blue gems aren't normally socketed by DPS specs, only for the purpose of activating the meta, so you will only have the minimum required amount in your gear.

How it works atm:
- When 1 of the blue gems required for meta activation are placed into an "extra socket", the meta becomes visually active (light colored), which can confuse players into thinking their meta works, but you don't actually receive the stats (21 crit for Chaotic, 21 agi for Relentless, respectively).
- If the blue gems required for the metas to activate are relocated into any other, regular socket, you will receive the 21 crit / 21 agi as intended.
Note: Did no tests on the critical damage portion, assuming if one part of the stats is not given as intended, then the other is the same.

How it should work:
- Metas should become active AND actually grant their stats to you no matter which socket slot you use to place the colors for activation. They should not ignore extra sockets.

**Comment by Keader** [comment]
I cant reproduce your issue using eternal belt buckle.

Meta before equips: https://i.imgur.com/S9y9fJR.jpg
With 1 Blue Gem: https://i.imgur.com/DWyUeUn.jpg
With 2 Blue Gem: https://i.imgur.com/ZcEcdk9.jpg

**Comment by Dranah** [comment]
I told you, the visual does not matter, it shows active, but you don't get the stat.

**Comment by Keader** [comment]
Check my spell crit

**Comment by Dranah** [comment]
strange, can you try with a belt that did not have sockets originally? maybe it counts if it did

**Comment by Dranah** [comment]
https://imgur.com/uNeBcTg inactive meta 20627 health
https://imgur.com/uhREGMi active meta with a blue spirit gem added to belt, https://imgur.com/mV5TlNe
still 20627, did not receive stamina
The belt i socketed had no sockets originally.

**Comment by squalllh1989** [comment]
Confirmed this problem, the meta look like it's actived, but it didn't
The helm with a meta unactived, no belt, 653 agi:
![wowscrnshot_020518_205843](https://user-images.githubusercontent.com/27235989/35808239-bba9f102-0ab7-11e8-8c9a-87bea0463990.jpg)
![wowscrnshot_020518_205846](https://user-images.githubusercontent.com/27235989/35808241-bde1e876-0ab7-11e8-89a2-bec4d7016bbd.jpg)

After equipt a cloth belt that give no agi, originally not have gem slot, used a eternal belt bucker, add a nightmare tear with +10 all stat, now i have 663 agi (+10 agi from the tear). It should be 684 agi (+10 agi from the tear, +21 agi from the meta actived)
![wowscrnshot_020518_205853](https://user-images.githubusercontent.com/27235989/35808358-14ce70d2-0ab8-11e8-9729-c1467d891810.jpg)
![wowscrnshot_020518_205856](https://user-images.githubusercontent.com/27235989/35808360-166b55b8-0ab8-11e8-9e50-5378dabab477.jpg)

**Comment by Keader** [comment]
Removing my signature.
I'm still working on this, but if other dev want assume, feel free.

**Comment by Keader** [comment]
Fixed.
I will pass to janitor tomorrow morning.

**Comment by Magabro** [comment]
Confirmed in Dev.  Completing the socket bonus of my meta gem using the eternal belt buckle granted my character the meta gem stats.

![wowscrnshot_021018_090306](https://user-images.githubusercontent.com/34353250/36064701-7dbe16d6-0e43-11e8-952f-a71d5fe95297.jpg)

![wowscrnshot_021018_090318](https://user-images.githubusercontent.com/34353250/36064705-887ce7e6-0e43-11e8-9acb-412c6fe24cc0.jpg)

**Comment by Dranah** [comment]
Maga tested wrong belt, this still needs fix

**Comment by TheManiax** [comment]
The fix is not applied to Dev yet
@Keader needs to pass it to janitor

**Comment by TheManiax** [comment]
I confirm a well.
Working on dev.
Can be closed.

**Comment by Keader** [comment]
Janitor will close when update red.
