### ISSUE TITLE
[Boss] Grobbulus

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#2195]
Hello,
I'd like to report Grobbulus' slime spray http://www.wow-mania.com/armory/?spell=28157 acting up in synergy with Mutating Injection http://www.wow-mania.com/armory/?spell=28169
This issue began recently and may be slightly influenced with the levels of server lag, as normally there is a bit of time between the two spells being cast by the boss. But it can happen also when there is no delay.

How it works at the moment:
Grobbulus visually turns towards his targets of Mutating Injection when he debuffs them and 1-2 seconds after uses his Slime Spray, which is meant to be hitting frontally (only the main tank). 
However Grobbulus considers his visual position to calculate where the spray hits, rather than where he is "actually" facing, so the Spray hits the raid behind, instead of the main tank in front. That results in instant wipe.

How it should work:
Grobbulus' slime spray should always hit towards the 1# threat person (typically main tank), because that's his actual "front side", no matter how spell visuals make him look.

**Comment by Midnaa** [comment]
There's a core issue related to this affecting all breath type spells. The damage should go where the boss is looking when the cast finishes, how it works rn the damage will go where the cast starts. Even if you turn a dragon away from a raid, if he started casting facing the raid it will always hit the raid.

**Comment by VA-L** [comment]
- Grobbulus will no longer turn during his mutated injection.
- Living Poison Oozes on Patchwerk's alley will now explode if someone is close to them (1yd).

**Comment by Dranah** [comment]
UPDATE:
- Grobbulus turning is back to normal, he turns behind for mutating injection but it no longer affects where the spray goes. Spray will always be cast on a frontal cone around the main tank (or whoever is 1# aggro). 
- Ooze traps at Patchwerk now explode and damage players correctly.
