### ISSUE TITLE
[Core] Colision Height

### ISSUE THREAD

**Issue by philoudu16** [WoWManiaUK/Redemption#2199]
If you kill a Monstrous Kaliri while it is in the air, the corpse of the mob will drop to the ground, but you will be unable to loot it (the loot icon when you hover over the corpse is not greyed out, and there is no error message) . However if you wait for the mob to fly down and then kill it, you will be able to loot it.
I couldnt think of another flying mob to test it on but I believe the same issue would probably happen.

Link to the mob:
http://www.wowhead.com/npc=23051/monstrous-kaliri (spawns in Skettis in Terokkar Forest)

**Comment by fvicaria** [comment]
Try disabling auto-loot also.
This should be fixed after the update Wednesday.

**Comment by philoudu16** [comment]
This is without auto loot.

Arcane Serpent in Coldarra (Borean Tundra), Emerald Skytalon in the Emerald Dragonshrine (Dragonblight), Imperial Eagle in Grizzly Hills have the same issue. (Those are the only mobs I've found for now that fly, have low enough hp that I can burst them down and that actually drop anything.)

I feel it's like a range issue, as if the mob falls to the ground client side but not server side, so the client believes you are able to loot the mob, but on the server you are too far away and when you click nothing happens (I guess the range check for the "you are too far away" warning also happens client side).

**Comment by WhitephoenixTheBunny** [comment]
Tested on mobs referencied. When killed in air I'm not avaible to loot.

**Comment by fvicaria** [comment]
The issue itself has been fixed and tested. Why did you remove the label?

**Comment by TheManiax** [comment]
It is still bugged Janitor
Guid 5230001 and 5230004 are already on the ground
![wowscrnshot_020618_004839](https://user-images.githubusercontent.com/14857593/35829285-9d777d9c-0ad7-11e8-9d26-6b08d0f4c637.jpg)
Not a good choice to reproduce the bug
Try for example 86131 , you will not be able to loot it no matter how many times you kill it
![wowscrnshot_020618_005108](https://user-images.githubusercontent.com/14857593/35829359-e0e27528-0ad7-11e8-9bea-01b1e7f43128.jpg)

**Comment by fvicaria** [comment]
l will try to fix this generically.

**Comment by TheManiax** [comment]
It is generally fixed on Dev.
Tested on 5 different kind of flying NPC.
Double Confirm.
