### ISSUE TITLE
Bug with Glyph Might of the Grizzlemaw

### ISSUE THREAD

**Issue by Maxiboy3** [WoWManiaUK/Redemption#2201]
Well simpel ? bourght Glyph of Might of the Grizzlemaw But i got the look of Guardian of the Glade :(

Gonna leave a link for you to see 

http://www.wowhead.com/acquiring-claws-of-ursoc-guardian-druid-artifact

**Comment by WhitephoenixTheBunny** [comment]
![unknown](https://user-images.githubusercontent.com/31921098/35814112-22896d38-0a8d-11e8-9479-39b5deecdb0d.png)

**Comment by Midnaa** [comment]
Guardian of the Glade = Glyph of grizzlemaw on retail theyre mixed up for some reason

**Comment by fvicaria** [comment]
As-is now. We are not changing at this stage. This is purely visual.

**Comment by fvicaria** [comment]
"Fixed" in dev in the sense that the item will have the correct name so you don't get a surprise when you use it. But the applied glyph itself will show the other name.
