### ISSUE TITLE
Artifact's upside down

### ISSUE THREAD

**Issue by Jagern** [WoWManiaUK/Redemption#2202]
Hey, 

there is a visual bug with some of the artifact weapons that they are upside down, its just visual but it still bothers me and probably many others, 

i dont know all the weapons that are like this since i dont have mp to buy them all but heres a picture of the one i have.

![1q](https://user-images.githubusercontent.com/32306956/35814289-fbaf1006-0a95-11e8-9cda-4af8e1354371.png)

![2q](https://user-images.githubusercontent.com/32306956/35814300-03dcb21a-0a96-11e8-8563-30969699c215.png)

this was the only picture i could find but you can clearly see its the other way around

**Comment by fvicaria** [comment]
As is all imported items are displayed the best way possible. We will not change it. Sorry.
