### ISSUE TITLE
scryers reputation stuck in 'at war'

### ISSUE THREAD

**Issue by larian** [WoWManiaUK/Redemption#2203]
hi,i dont know if this is the same issue as nightseekerr were he stated he cant talk to scryers FP guy in shadowmoon despite being exalted with them.but the thing is that despite doing the quest city of light (http://www.wow-mania.com/armory/?quest=10211) ,wich in turns let u choose a faction aldor or scryers.i chose the scryers because i had a lot of signets/arcane tomes to turn in from while i was lvl'ing.Now the issue here is that for some reason i'm still "at war'" with the scryers despite haveing honnored reputation with them.so even there name bars are green to me i can still attack them,and not turn in or pick up any quests.
![scryers](https://user-images.githubusercontent.com/34296326/35828671-b74fcba0-0ac0-11e8-8ccc-3e511798012f.jpg)
i talkd to a GM(think it was weeble) ingame involving this issue and he removed the mark in the 'at war box' for me and then everything was fine.i could turn in quests,marks etc...but as soon as i left shattrath,joind in RDF or logd of and came back in shattrath later,the box is markd again. and i cant remove the mark myself.

would realy appreciate it if u could look into this.i'm a bit of an achievment hunter so its a bit frustrating,also it makes other achievments bit more difficult,the quests in each zone for example since u cant pick up the quests in netherstorm who are related to the scryers either.and the aldor 1ce ofc since i got hatted rep with them.

thanks in advance

**Comment by fvicaria** [comment]
open ticket for that

**Comment by larian** [comment]
like i said in my post i already did and talkd to weeble,he removed it manualy but everytime i go dungeon/out of shattrath of w/e it automaticly comes back

**Comment by GmSaintz** [comment]
Unfortunately, we were un-able to figure out what may be causing the issue for the player. After completing City of Light (http://www.wow-mania.com/armory/?quest=10211) It opens 2 quests to the player, "Allegiance to the Scryers" (http://www.wow-mania.com/armory/?quest=10552) and "Allegiance to the Aldor" (http://www.wow-mania.com/armory/?quest=10551). In this case the Player chose the Scryers and completed the necessary quest (10552), in which case he/she should no longer be "At-War" with Scryers.

**Comment by fvicaria** [comment]
What is the char name?

**Comment by larian** [comment]
firefoxy
