### ISSUE TITLE
[Item] Sealed chest

### ISSUE THREAD

**Issue by StefanelStan** [WoWManiaUK/Redemption#2204]
There seems to be an issue with LK Sealed Chest.
Item link :  http://www.wow-mania.com/armory/?item=51315
**Description of item** : This item is a "hidden" item which appears ONLY for those that are at http://www.wowhead.com/quest=24748/the-lich-kings-last-stand quest. The item can be looted only once by those people (so once you looted it and completed the quest that is started by chest, you cannot loot it again). The chest is NOT visible by master looter (unless he/she isdoing the SM quest to kill LK).
**Issue :** 2 people were on the same stage of quest (to kill LK after ShadowMourne) and neither of them could loot the chest. I have tried to loot it over and over again and it would not go in my inventory.
I know this item works fine when 1 person is on quest but it seems to be somewhat broken when 2 ppl are on the quest at the same stage.
When this situation happens (2 ppl at the same stage) both of them should be able to loot the chest (link to this situation http://www.wowhead.com/item=51315/sealed-chest#comments:id=1093741 ).
Thank you.

**Comment by TheManiax** [comment]
When you click on the chest in loot window, Nothing will happen
No matter if it is free for all or group loot
The sealed chest is not lootable if 2 player in raid have Quest 24748 active

**Comment by fvicaria** [comment]
Not sure what can be done here.

**Comment by GMWeeble** [comment]
Issue might not be because of 2 players. Can be issue with the quest.
