### ISSUE TITLE
[NPC] Risen Zombie (Zombiefest! - Culling of Stratholme)

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#2205]
Hello,

I'd like to report a couple of problems regarding these zombies (http://www.wow-mania.com/armory/?npc=27737) that affect the completion of the achievement Zombiefest! http://www.wowhead.com/achievement=1872

How it works right now:

1. Zombies stop respawning when you kill the first boss, Meathook. 
2. Zombies have normal 100% movement speed which means you can't outrun/kite them without speed boosts or snares.

How it should work:
1. Zombies should not stop respawning until the second boss, Salramm http://www.wow-mania.com/armory/?npc=26530 is dead.
2. Zombies should move REALLY slow, making it possible to easily kite them with your normal run speed
https://www.youtube.com/watch?v=leHoVmyQ5Wk >> here's a video showing just how damn slow they are meant to be

**Comment by Dranah** [comment]
Just to be clear, this issue is no priority, as the achievement is still doable - even though you only get one shot at it and in completely not the intended way - but that doesn't mean it shouldn't be reported and fixed someday.

**Comment by Dranah** [comment]
I'm reopening this as Keader inquired more bugs to fix!

**Comment by Keader** [comment]
I cant find anything in code that can make zombies stop spawn when Meathook died.
Has 186 zombies in Culling map, same of trinity.
I cant find anything wrong in code or db.

**Comment by Rushor** [comment]
is this still an issue then pls reopen, i can fix that :)

**Comment by Rushor** [comment]
@jarvik76 can you pls explain what is not working curretly?

**Comment by jarvik76** [comment]
"1.  Zombies stop respawning when you kill the first boss, Meathook."

**Comment by Rushor** [comment]
okay i don't see a reason aswell now why they do not respawn :O

**Comment by Rushor** [comment]
i will adjust the speed for now.

**Comment by jarvik76** [comment]
The problem with this is that it blocks out the achievement, which in turns blocks the significant "Glory of the Hero" achievement.
Maximum at the moment that is possible without the respawn being fixed seems to be about 85. Is there any chance of some investigative time being put into this?
