### ISSUE TITLE
[Quest] The Fallen Sisters

### ISSUE THREAD

**Issue by Sunwolfenemy** [WoWManiaUK/Redemption#2206]
In Howling Fjord, the quest "The Fallen Sisters" requires the player to use Lurielle's Pendant on Chill Nymphs.  The Nymphs should be hostile prior to the pendant being used.  Unfortunately, they seem to be stuck in friendly mode which makes them invalid targets.  Thank you for your attention. :)

**Comment by TheManiax** [comment]
Quest: [The fallen sisters](http://www.wowhead.com/quest=11314/the-fallen-sisters)
NPC: [Chill Nymph](http://www.wowhead.com/npc=23678/chill-nymph)

**Comment by TheManiax** [comment]
![wowscrnshot_020618_230840](https://user-images.githubusercontent.com/14857593/35880519-6a8d0728-0b93-11e8-8b35-5c17707700e6.jpg)
![wowscrnshot_020618_230826](https://user-images.githubusercontent.com/14857593/35880540-72f14eb0-0b93-11e8-982c-249a0f0d1b54.jpg)
