### ISSUE TITLE
[Dungeon] The Crown Chemical Co 

### ISSUE THREAD

**Issue by philoudu16** [WoWManiaUK/Redemption#2210]
This issue is about the dungeon of the Fool for Love event. In this dungeon, you need to pick up a quest in order to be able to attack the boss. However on Redemption, when you use rdf, you enter the dungeon the wrong side of a door which you cannot open from that side. You therefore cannot engage the boss which stays friendly.

Three solutions for this issue (no clue which is easier to implement):
- Move the quest giver to where you enter through rdf so you are able to pick the quest up
- Leave the door open so people can reach the quest giver
- Move the teleport point of rdf to the very entrance of SFK

Do note that the dungeon is doable if you enter manually (which would be quite time consuming for allies), and you only get the Heart Shaped Box through rdf (so you can get it atm if you queue rdf, teleport out, fly to Silverpine Forest, enter manually and do the dungeon).

**Comment by fvicaria** [comment]
I need this to be confirmed independently. It was working fine.

**Comment by Unstoppablee** [comment]
After server restart this is working fine. 
Door is opened and you can take the quest.

THank you.

**Comment by Unstoppablee** [comment]
After 3 - 4 times being in instance with different groups and ppl, doors are opened sometimes, and sometimes are closed.
We need more details about this issue in order to fix it.

**Comment by squalllh1989** [comment]
Confirmed this problem, you enter the event queue at the same side with the boss, the quest giver which give you daily quest to start the fight is in another side of the door along with the npc which is needed to open the door. Some time the door open itself, then people can take the quest and start the encounter event, some time it won't open so can't start the event.

**Comment by fvicaria** [comment]
What is the quest for this? Links please

**Comment by squalllh1989** [comment]
The quest for this (which you took from npc in dungeon) is: [You've Been Served](http://www.wow-mania.com/armory/?quest=14488) taken from [Investigator Fezzen Brasstacks](http://www.wow-mania.com/armory/?npc=38208). The problem here is: not that the quest or the npc not work, just the rdf system that take you in a place where the npc that give you that quest (You've Been Served) is behind a door that you can't open from your side, but the npc's side.

**Comment by squalllh1989** [comment]
if you walk into the dungeon manually, there will be no problem for that at all.
