### ISSUE TITLE
[Item] Heart Shaped Box

### ISSUE THREAD

**Issue by philoudu16** [WoWManiaUK/Redemption#2211]
When completing the Fool for Love event dungeon through rdf, you receive a Heart Shaped Box (http://www.wowhead.com/item=54537/heart-shaped-box). 
These boxes should at least contain Love Tokens (http://www.wowhead.com/item=49927/love-token) and has a very small chance of giving you the Big Love Rocket.
However in my dungeon group yesterday, the box was empty for all of us. So I asked a GM to give himself some boxes to test it out, and indeed, they were all empty for him too.

**Comment by Unstoppablee** [comment]
![wowscrnshot_020718_090022](https://user-images.githubusercontent.com/26930686/35905158-5360af70-0be6-11e8-80ce-6e8b2180aa34.jpg)

I can confirm that Box is empty.
