### ISSUE TITLE
[Talent] Soul Link

### ISSUE THREAD

**Issue by Necrosiss** [WoWManiaUK/Redemption#2213]
Hello, I just find out that Soul Link skill doesnt affect warlock pet. When you use it, Warlock and pet should get a buff on them, the problem is you can see buff only on Warlock not on the pet. Could you please check that for me.

Thanks you, Necrosiss.

[Edit] If I good think that damage reduction from 100%, Soul Link -20% share with pet, my resilliance 1357 -28.79% that give 48.79% redcution damage on my character, I feel like im getting around 80% or around. It seems like one of them resilliance or soul link is fully ignore by damage by others or they dont stack proply to reduce my damage taken.

**Comment by Dranah** [comment]
- Soul Link and Resilience damage mitigation stacks multiplicatively, which means Resilience reduces your damage taken by 28,79%, and the remaining 71,21% is reduced further by 20% by Soul link. That results you taking 56,97% of the original damage and our testers confirmed this works.
- Tests showed that both Soul link and resilience work properly and also in conjunction with each other. 
- Soul Link buff not appearing on pet is only a visual problem.
This thread can be closed.
