### ISSUE TITLE
[Item] Shaman Tier 10 shoulders

### ISSUE THREAD

**Issue by TheManiax** [WoWManiaUK/Redemption#2216]
The **visual effect on shaman T10 shoulder** (shown below) is **resetting PvP timer** for players (probably being counted as spell)

![154173](https://user-images.githubusercontent.com/14857593/35925962-4986c63c-0c3c-11e8-9395-6e28ea9fd9b2.jpg)

This includes all T10 shoulders for all 3 available specs
Here is the list of shaman Tier 10 shoulders:

1. [Frost Witch's Shoulderpads](http://www.wowhead.com/item=50845/frost-witchs-shoulderpads)
2. [Sanctified Frost Witch's Shoulderpads](http://www.wowhead.com/item=51204/sanctified-frost-witchs-shoulderpads)
3. [Sanctified Frost Witch's Shoulderpads](http://www.wowhead.com/item=51235/sanctified-frost-witchs-shoulderpads)
4. [Frost Witch's Spaulders](http://www.wowhead.com/item=50839/frost-witchs-spaulders)
5. [Sanctified Frost Witch's Spaulders](http://www.wowhead.com/item=51194/sanctified-frost-witchs-spaulders)
6. [Sanctified Frost Witch's Spaulders](http://www.wowhead.com/item=51245/sanctified-frost-witchs-spaulders)
7. [Frost Witch's Shoulderguards](http://www.wowhead.com/item=50834/frost-witchs-shoulderguards)
8. [Sanctified Frost Witch's Shoulderguards](http://www.wowhead.com/item=51199/sanctified-frost-witchs-shoulderguards)
9. [Sanctified Frost Witch's Shoulderguards](http://www.wowhead.com/item=51240/sanctified-frost-witchs-shoulderguards)

- Other items with such visual effects may have such an issue but I can't think of any specific Item for now, So if any one can name any, I would be happy to check it.
-  The go around till it gets fixed, is to unequip the shoulder and wait for 5 minutes.

**Comment by fvicaria** [comment]
Probably won't be able to do anything about it. This is client-side.
