### ISSUE TITLE
Flirt With Disaster

### ISSUE THREAD

**Issue by Felzak** [WoWManiaUK/Redemption#2217]
The Flirt With Disaster achievement for the Love Is In The Air event is not working.

**Comment by fvicaria** [comment]
Saying it is not working does not explain anything.

Please follow the procedure described below before creating a new issue:
[How to Properly Report an Issue](https://github.com/wow-mania/Redemption/wiki/How-to-Properly-Report-an-Issue)

This will help developers identify and fix the issue quicker. Incorrectly or unclear reports will simply be deleted.
