### ISSUE TITLE
Skinning at Dun Morogh

### ISSUE THREAD

**Issue by ayman110229** [WoWManiaUK/Redemption#2218]
Creatures that are supposed to be skinnable are not. Bears and wolves and whatnot.

**Comment by TheManiax** [comment]
Make sure you are using wow mania launcher.

**Comment by ayman110229** [comment]
I am

**Comment by fvicaria** [comment]
Please follow the procedure described below before creating a new issue:
[How to Properly Report an Issue](https://github.com/wow-mania/Redemption/wiki/How-to-Properly-Report-an-Issue)

This will help developers identify and fix the issue quicker. Incorrectly or unclear reports will simply be deleted.
