### ISSUE TITLE
Flying Mount in Northren

### ISSUE THREAD

**Issue by Desslok32210** [WoWManiaUK/Redemption#2219]
Unable to mount my flying mount in Northren on my character Desskcch. Receive a message stating wrong zone. I've paid all of my mounting fees. I may have paid them in the wrong order. Need someone to check my character Desskcch. 
Don't know if this has anything to do with it but I've been trying to install add-ons and I don't have the Add-on tab in the character menu.

Thanks for looking into my problem.

**Comment by TheManiax** [comment]
Which mount are you trying to use and which zone are you in?
You may also add an screenshot showing your location please.

**Comment by Desslok32210** [comment]
Anywhere in Northren 
I tied both flying mounts I have. 1 purchased in  Outland and 1 from Norhtren.

**Comment by Desslok32210** [comment]
I have a Tawny Wind Rider and Swift Red Wind Rider
![wowscrnshot_020718_135230](https://user-images.githubusercontent.com/36240764/35935475-9cdc1c7a-0c0e-11e8-924c-1ed47d8442b0.jpg)

**Comment by fvicaria** [comment]
This is clearly a client issue.  Contact support.
Make sure your client version is 2.2.3

**Comment by Desslok32210** [comment]
Thanks for your help in this matter.
