### ISSUE TITLE
[Spell] Soul Link

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#2220]
Hello,
We discovered a bug of different nature while testing warlock ability Soul Link's http://www.wow-mania.com/armory/?spell=19028 behavior.
- How it works: It appears to hit the pet twice (for the intended value but two times)
The owner receives the proper 20% reduction, but the transfered damage is received twice by the pet (also displayed twice on combat log)
- How it should work: it should only hit the pet once.
![image](https://user-images.githubusercontent.com/31132743/35938262-da02aa12-0c48-11e8-9c82-a75eb4c065d9.png)

**Comment by Unstoppablee** [comment]
![wowscrnshot_020718_203735](https://user-images.githubusercontent.com/26930686/35938359-1cfbb5c0-0c49-11e8-9d11-404ee3c83457.jpg)

**Comment by Keader** [comment]
Only happens with spell damage
