### ISSUE TITLE
[Talent/Spell] Improved Healthstone - Ritual of Souls

### ISSUE THREAD

**Issue by LimitlessPain** [WoWManiaUK/Redemption#2221]
The warlock talent **Improved Healthstone** in demonology
(Increases the amount of Health restored by your Healthstone by X%.)
http://www.wow-mania.com/armory/?spell=18692 (Rank 1 - 10%)
http://www.wow-mania.com/armory/?spell=18693 (Rank 2 - 20%)

does not apply to the healthstone wells created by **Ritual of Souls**
http://www.wow-mania.com/armory/?spell=29893 (Rank 1 - Master Healthstone)
http://www.wow-mania.com/armory/?spell=58887 (Rank 2 - Fel Healthstone)

as such the amount of health restored by _Fel Healthstones_ acquired through the Soulwell created by _Ritual of Souls_ only gives the unmodified **4280** health
instead of **5136** created through _Create Healthstone_ spell (which benefits form the talent (20%)).
/http://www.wow-mania.com/armory/?spell=47878 (Rank 8 - Fel Healthstone)/

**Comment by Dranah** [comment]
https://imgur.com/9Fm3s3f - healthstone created via Soulwell

https://imgur.com/YH2V0Ef - healthstone created via Create Healthstone

I've checked on combat log that they heal for as much as it is shown on them in your bags.
For whatever odd reason, all Fel Healthstones you consume are displayed as Master Healthstone in your combat log as well.

**Comment by Keader** [comment]
Fix done, ready to test

**Comment by Magabro** [comment]
Appears fixed.  2/2 improved healthstone healed for 20% more on group members also
![wowscrnshot_010318_093544](https://user-images.githubusercontent.com/34353250/36043156-2fe71310-0d83-11e8-9916-e7d472d571e3.jpg)
