### ISSUE TITLE
[Spell] Shadow Bite spell power coefficient

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#2222]
Hello,
I'd like to report warlock Felhunter's Shadow Bite http://www.wow-mania.com/armory/?spell=54053 for not scaling with spell power.
It's the same issue as I reported last week on imp's firebolt, they probably broke with the same update back then. I just forgot to check the felpuppy's damage when I was reporting that one :/

How it works right now: 
- Spell does not scale with the spell damage bonus the pet receives from the owner.
On my tests it does the same base 112-159 damage it has after affliction talent with 0 spell power on the warlock as with 2100. (with no dots on target)
Note: Applying Shadow DOTs to the target properly increases the spell's damage by 15% each.

How it should work: 
- It should receive 42,9% of the spell damage the pet inherits.
With a warlock that has ~2,1k spell power, the pet's bonus damage is +315. Adding the 42,9% of that to the base damage, the expected damage on dummy would be 247-294 (with no dots on target)

**Comment by Midnaa** [comment]
Also affects 50589
