### ISSUE TITLE
[Pet] Toxic Wasteling

### ISSUE THREAD

**Issue by philoudu16** [WoWManiaUK/Redemption#2223]
The toxic wasteling is a pet obtainable during the Love is in the Air event in the special dungeon.
This familiar is unique since he should kill critters that are close to you, and increase in size as he kills them.

However on Redemption, he simply acts like any other familiar and simply follows you around. (tested it on squirrels, rabbits and the "ninja turtles" in Dalaran, and the glacier penguins close to the argent tournament)

I looked around to try find an id for the mechanic that makes him kill other critters, or for whatever makes him bigger, but I was unable to find them.

**Link to the item and to the summoning spell:**
http://www.wowhead.com/item=50446/toxic-wasteling
http://www.wowhead.com/spell=71840/toxic-wasteling

**Link to a video of the pet eating critters:**
https://www.youtube.com/watch?v=kQ9LfidZox0

**Comment by fvicaria** [comment]
This was fixed yesterday. You have a 6% chance of it dropping from [Heart Shaped Box](http://www.wowhead.com/item=54537/heart-shaped-box)

**Comment by philoudu16** [comment]
It drops fine, it just doesn't interact with critters as it should, which makes it less unique. I do understand if it's too much work for the devs for just a familiar though :)

**Comment by fvicaria** [comment]
I will re-check

**Comment by fvicaria** [comment]
Found the issue. It will be fixed on next restart.
Thanks for that.

**Comment by philoudu16** [comment]
Nice! Thanks for the fix :)
