### ISSUE TITLE
[Boss] Cthun - dark glare

### ISSUE THREAD

**Issue by KrzysztofKarate** [WoWManiaUK/Redemption#2226]
Issue partially fixed by @Keader.

Previously there was no animation. It was fixed and now is only mismatch for animation and hitbox. Unfortunetly it still makes fight very difficult as far as you can't know direction he will be heading -> beggining spot for dark glare to be casted.

I confirm that there is fixed animation, however, hitbox is 90 degrees forward to the animation in the rotation direction (mismatch of hitbox and animation).

**Comment by Keader** [comment]
Blame Blizzard for it.
It's a cone area in front of cast, is not exactly front of cast.

> Effect 0: Id 2 (SPELL_EFFECT_SCHOOL_DAMAGE)
> BasePoints = 43749 to 56250
> Targets (24, 0) (**TARGET_UNIT_CONE_ENEMY_24**, NO_TARGET)
> Radius (Id 12) 100,00

Nothing that we can do, is blizzlike behavior :/
