### ISSUE TITLE
[Quest] the valiant's charge

### ISSUE THREAD

**Issue by Reivus-Eleanoris** [WoWManiaUK/Redemption#2227]
http://www.wowhead.com/quest=13593/valiant-of-stormwind
http://www.wowhead.com/quest=13718/the-valiants-charge

I completed «Valiant of Stormwind» quest, it completed weirdly as the textbox did not close. Then, the following quest «the valiant's charge» did not appear. I have done every other cities on this character and I am well on my way on my other (except that the last city quest is working)

I use the launcher, deleted my cache, I'm on 2.2.3 patch as it should be

The GM did reset the NPC without results

**Comment by fvicaria** [comment]
Need to remove quest and re-do it

**Comment by Reivus-Eleanoris** [comment]
I cannot abandon quest as the problem is not having access to it in the first place or the completed one before

**Comment by fvicaria** [comment]
I mean these:
http://wow-mania.com/armory/?quest=13684
http://wow-mania.com/armory/?quest=13593

As you can see they are the pre-reqs for [The Valiant's Charge](http://wow-mania.com/armory/?quest=13718#conditions)

![image](https://user-images.githubusercontent.com/9414661/36017770-04b2fc52-0d71-11e8-84f2-fb772fc5289e.png)

Ask a gm to remove from you and go do it again.

I have just tried and they work fine.

![image](https://user-images.githubusercontent.com/9414661/36017785-16d5246e-0d71-11e8-8dba-c0dc2308f20e.png)
