### ISSUE TITLE
[Boss] Broggok-The Blood Furnace

### ISSUE THREAD

**Issue by Bartok14** [WoWManiaUK/Redemption#2229]
Was doing the instance on Heroic. Got to Broggok and noticed the door wasn't closed while I was pulling the switch. None of the adds spawned, and cannot attack Broggok.
Here is the screenshot:
![image](https://user-images.githubusercontent.com/32959403/36017308-31f08fda-0d45-11e8-92b4-1158055b5594.png)

**Comment by TheManiax** [comment]
http://www.wowhead.com/npc=17380/broggok

**Comment by Bartok14** [comment]
![image](https://user-images.githubusercontent.com/32959403/36018131-9fa82f1c-0d48-11e8-9999-3922fde9b9a5.png)

Another Screen shot to show you what I am seeing

**Comment by fvicaria** [comment]
![image](https://user-images.githubusercontent.com/9414661/36018898-49aa7a20-0d75-11e8-888a-9a740cf34386.png)

Cannot reproduce this in dev.

Please leave dungeon and clear instance ID
