### ISSUE TITLE
[Boss] Auriaya - Ulduar

### ISSUE THREAD

**Issue by philoudu16** [WoWManiaUK/Redemption#2231]
During the encounter with Auriaya in Ulduar, she will summon a Feral Defender. This defender should spawn the first time with nine stacks of Feral Essence, increasing his damage done by 50% per stack. When you kill him, he will lose one of those stacks, and will respawn about thirty seconds later, until he has no stacks left.
At the moment however, he seems to spawn with no stack at all so he deals very little damage, and never respawns which makes one of the achievements ("Nine Lives") impossible.

Link to Auriaya, the Defender and the buff:
http://www.wowhead.com/npc=33515/auriaya
http://www.wowhead.com/npc=34035/feral-defender
http://www.wowhead.com/spell=64455/feral-essence

**Comment by Keader** [comment]
- Added missing spells
- Fixed Feral Defender and added all missing spells
- Fixed Sanctum Sentry respawn/added missing spells
- Fixed spells timers
- Fixed some wrong db datas
- Updated codestyle and cleanup
- Scripted all spells related with this fight
- Fixed sanctum sentry number (2 - 10 man, 4 - 25 man)

**Comment by Dranah** [comment]
UPDATE:
- Cats are fixed, counted all 9, achie works too.
Auriaya's spells also seem fine except one.
- "Sentinel Blast" which is her channeled must-interrupt ability, seems to break on any damage done to Auriaya, rather than requiring a regular interrupt (kick pummel etc). This needs fix.

**Comment by Dranah** [comment]
- sentinel blast no longer breaks on random damage (fixed)
