### ISSUE TITLE
[NPC] Dame Evniki Kapsalis- Argent Tournament

### ISSUE THREAD

**Issue by Bartok14** [WoWManiaUK/Redemption#2233]
I finally finished getting exalted with all the Horde races and then got exalted with the Argent Crusade today. This allows you to unlock the items for purchase from Dame Evniki Kapsalis. The problem with her as opposed to the other Argent Crusade vendors is that there is no confirmation message that pops up when you try to purchase anything, and you can't refund items from her unlike all the other argent crusade vendors. I accidentally right clicked while I was scrolling through her items, and the argent crusade tabbard went into my inventory and I couldn't do anything about it. There was no confirmation message or refund available, and now I am out 50 Champion Seals :(

**Comment by fvicaria** [comment]
Only specific items will have. This is the same for every NPC.
