### ISSUE TITLE
[Spell] Hunter's Auto-Shot (Side Steady-Shot)

### ISSUE THREAD

**Issue by Ashamedlol** [WoWManiaUK/Redemption#2234]
When swapping targets while in middle of Steady Shot cast (while Global Cooldown is progressing), there are no autoshots occuring if you cast Steady Shot more.

What occurs from swapping:

![jwg8cmsrqd6342d9-hikoa](https://user-images.githubusercontent.com/16576459/36060773-9de2c776-0e58-11e8-9ce5-8d8d0f721e7a.png)

(No autoshots from steady shots, due to target swap).
What it should do:
![c7sjjw3arxcxfxmh-yglcq](https://user-images.githubusercontent.com/16576459/36060777-a9cdb1ae-0e58-11e8-9e23-ad79543ca512.png)

(Autoshots in between of Steady Shots, without them it's a dps loss).

Spell ID: http://www.wow-mania.com/armory/?spell=49052.

**Comment by Keader** [comment]
i have a idea what can be.
i will check

**Comment by TheManiax** [comment]
Auto attack is a command, When you are casting steady shot and you command to do auto attack on another target, you will get erorr "Another action is in progress"
So you actually didn't complete the auto attack command this way.
I will remove the confirmed tag untill we find some info that how it should really work.
@Ashamedlol  If you have any reliable info, please link so we can see.
Feel free to send in-game mail to maniax to get in contact as well.

**Comment by Ashamedlol** [comment]
If you look at it, I was attacking the same target, it's just when I swapped targets once, it stopped casting auto-shoot (auto attack).

The combat log shows what's happening right now, and what happens if I use a macro or press escape and rightclick again, but it delays the dps if done like that.

**Comment by HDArokh** [comment]
@TheManiax  http://wowwiki.wikia.com/wiki/Auto_Shot  

hope thats enough info ^^

**Comment by TheManiax** [comment]
@Ashamedlol Had no issue for reproducing, just wasn't sure if it is a bug in first place or not :)
@HDArokh That's true
You are both true
It should be fixed
Putting tag back for @Keader to change the codes

**Comment by Keader** [comment]
https://www.youtube.com/watch?v=ysV3ebFl1Ks
this is a deep bug in spell system
i called some help xD

**Comment by Keader** [comment]
Tested and working :)
