### ISSUE TITLE
[Boss] ICC's Lady Deathwhisper

### ISSUE THREAD

**Issue by Ashamedlol** [WoWManiaUK/Redemption#2237]
Issue: 
The mechanic of Reanimated Adherent + Reanimated Fanatic does not exist: 
When a Cult Adherent/Empowered Adherent or Cult Fanatic/Deformed Fanatic casts Dark Martyrdom and is left out, a reanimated version of them spawns: A Reanimated Adherent gains a buff called  [Adherent's Determination] which causes him to be almost immune to magical damage (99% reduction), while the Reanimated Fanatic gains [Fanatic's Determination] which causes him to be almost immune to physical damage (99% reduction). This mechanic does not exist right now as when the Dark Martyrdom goes through, the adds just die and don't respawn the reanimated version of themselves.

This also renders the achievement known as Full House to being broken.

NPC IDs: http://www.wow-mania.com/armory/?npc=37949 (Cult Adherent) - http://www.wow-mania.com/armory/?npc=38136 (Empowered Adherent) - http://www.wow-mania.com/armory/?npc=38010 (Reanimated Adherent)

http://www.wow-mania.com/armory/?npc=37890 (Cult Fanatic) - http://www.wow-mania.com/armory/?npc=38135 (Deformed Fanatic) - http://www.wow-mania.com/armory/?npc=38009 (Reanimated Fanatic).

Spell IDs: http://www.wow-mania.com/armory/?spell=72500 (Dark Martyrdom) / http://www.wow-mania.com/armory/?spell=71235 (Fanatic's Determination) / http://www.wow-mania.com/armory/?spell=71234 (Adherent's Determination).

Achievement: http://www.wow-mania.com/armory/?achievement=4535 (Full House).

**Comment by Dranah** [comment]
To my best knowledge, Empowered/Deformed adds don't use Dark Martyrdom, only the regular Cult ones. Other than that the report is correct.

**Comment by Keader** [comment]
Fixed
I will send to Janitor tomorrow morning.

**Comment by Dranah** [comment]
fixed and achi works

**Comment by Ashamedlol** [comment]
1) Adds are doing nothing after being stunned while casting Dark Matyrdom.
2) The reanimated adds are not recieving the buff they're supposed to recieve:  [Adherent's Determination] /  [Fanatic's Determination] based on what type.

**Comment by fvicaria** [comment]
Fixed in dev also.
