### ISSUE TITLE
[Loot] Ulduar Hard mode loots

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#2241]
Hello,
There is a problem with ulduar hard mode loot tables.

1. It is currently not 100% chance to get a hardmode loot.
The bosses where I produced this so far was Iron Council and Hodir on 10man and Hodir on 25man.
How it should work:
When boss is killed hard mode style, it should ALWAYS award at least one item from the hard mode loots on top of the normal loot level.
How it works right now:
Sometimes only the regular 219 (10man) or 226 ( 25man) loots drop. Quest items such as Archivum Data Disc and the Sigils always drop as intended.
Proof: https://imgur.com/jupLIQx Iron Council 10 hardmode, you can see the achievement, the data disc, but both items ilvl 219
This does not always happen, sometimes you get the hardmode piece. So it's just not guaranteed, but it should be.

2. Getting 25man loot on 10man.
I've tested this on XT-002.
You can see on this screen that I received ilvl 239 wrist (which is xt's 25 hardmode loot) when completing his 10man hard mode: https://imgur.com/VuI5CE9

**Comment by fvicaria** [comment]
Fixed.
Let me know if there is any other boss with this issue.

**Comment by Dranah** [comment]
i'll take a look at other bosses when i have the time
