### ISSUE TITLE
[Spell] Bite

### ISSUE THREAD

**Issue by HDArokh** [WoWManiaUK/Redemption#2244]
Bite Spell from pets
http://www.wow-mania.com/armory/?spell=52474

Combat log from pet.
![pet combat log](https://user-images.githubusercontent.com/35156397/36097357-4e8034c8-1003-11e8-8409-9ca42c43a048.jpg)

as u can see the Bite damage is way lower than the normal autoattack hits.

**Comment by fvicaria** [comment]
I will take a look.

**Comment by fvicaria** [comment]
Please re-test on dev.
