### ISSUE TITLE
[Spell] Earthliving

### ISSUE THREAD

**Issue by AliWings** [WoWManiaUK/Redemption#2245]
I think there's a problem with Earthliving Weapon http://www.wow-mania.com/armory/?spell=51994

I'm far from being an expert of how scaling is calculated but the HoT part of the spell seems not to be scaling from Bonus Healing at all. I tried with my full gear that gives me about 3.4k bonus healing and then without any gear (besides a weapon), the HoT remained at 179 per tick.

I am not entirely sure when I noticed this issue, but it seems that happened since last patch update. Thanks for your time and attention!

**Comment by fvicaria** [comment]
I will look into it. If confirmed it is an easy fix.
