### ISSUE TITLE
[Map] Ring of valor - Main Elevators

### ISSUE THREAD

**Issue by Jagern** [WoWManiaUK/Redemption#2247]
there was a report on this arena a while ago but it still isnt working properly, players seam fine but pets bug out every time im in this arena, as a warlock im kinda fucked without my pet,

the thing is, when the elevator goes up the pet dont go up with it, and it stays down there untill i resummon it, there are a few exeptions where it comes up but doing arena and getting this is rng based since u will most likelly lose without pet.

what i suggest is just disable the arena untill it works fully

**Comment by TheManiax** [comment]
This has been tested before we open this arena
All pets were being teleported up without any problem
We will check to see if the bug is back
Is there any info you can add about those exceptions or how to reproduce it?

**Comment by fvicaria** [comment]
There are workarounds to be used. A lot of players do it fine.
There will not be any further work done on this for now.
