### ISSUE TITLE
[Achievement] Sartharion - Gonna Go When the Volcano Blows

### ISSUE THREAD

**Issue by philoudu16** [WoWManiaUK/Redemption#2248]
When killing Sartharion without getting hit by Lava Strike (an aoe projectile fired by the Fire Cyclones surrounding the "island" on which the encounter happens), you should be awarded the achievement "Gonna Go When the Volcano Blows".
However his achievement seems to be unavailable at the moment.

http://www.wowhead.com/npc=28860/sartharion
http://www.wowhead.com/achievement=2047/gonna-go-when-the-volcano-blows-10-player

**Comment by flumby** [comment]
Confirmed this works in Dev.

**Comment by fvicaria** [comment]
Please always add additional info such as a screenshot for the benefit of the player. Also feel free to marke it confirmed.
