### ISSUE TITLE
[Spell] Feral Druid Dash Not Working with Feral Swiftness Talent

### ISSUE THREAD

**Issue by Kaninchenbun** [WoWManiaUK/Redemption#2252]
Ive noticed over the course of leveling when I take Feral Swiftness [ID24866] 2/2 which increases move speed by 30% and use the Druid Dash [ID1850] which is 50% move speed, the Dash actually does nothing but give me a white trail to let me know its activated.  So to recap when I run the talent Feral Swiftness, and use the Ability Dash the move speed doesn't increase at all.

**Comment by fvicaria** [comment]
Visual issue only.

**Comment by Kaninchenbun** [comment]
Its not a visual issue, I don't move any faster while Dash is active. The movement speed stays the same.
