### ISSUE TITLE
[Boss] Lady Deathwhisper - RP

### ISSUE THREAD

**Issue by philoudu16** [WoWManiaUK/Redemption#2253]
Since last fix on Lady Deathwhisper, you can trigger her rp multiple times.
No issue gameplay wise, but it's quite annoying and really loud when you have a raid of 25 people all triggering her rp multiple times. Especially since you can trigger it during the encounter too.

Lady Deathwhisper:
http://www.wowhead.com/npc=36855/lady-deathwhisper

**Comment by fvicaria** [comment]
What rp?

**Comment by fvicaria** [comment]
Should be fixed in dev.
