### ISSUE TITLE
Problem with allowed limits of guild bank. (items per day)

### ISSUE THREAD

**Issue by TheGreyMouser** [WoWManiaUK/Redemption#2254]
I am guild master of Wrath of the Lich Kinkys.  Some members report being unable to pull a netherweave bag from tab4.  Permission is 1 item per day, per member, excluding members under "restrictions" rank.
I have double checked tab permissions a few times and they are in fact, set to 1 item per day.  Any ideas what might be going on?  1 member stated he had not pulled any item for 3 days, well beyond the 1 per day limit.
Thanks in advance.

**Comment by fvicaria** [comment]
I could not reproduce locally.
What is the guild name and who is the GM. I will check this later.

**Comment by TheGreyMouser** [comment]
Thanks.. Guild name is "Wrath of the Lich Kinkys" I am guild master on Amagezing alt.  Problem seems to be intermittent.  Not affecting all members or ranks.

I am wondering if it has something to do with the users, maybe not having up to date files, or screwy add ons.  Anything you could tell me to pass along to them would be helpful.

Thanks.

PS.. I don't suppose you would consider reducing the cast time to form a netherweave bag would you?   I make about 100 a week to give away to guild members... Just hoping I guess.  :o)


________________________________

**Comment by fvicaria** [comment]
I will join the guild and re-test it.
Can you give me your char name also or a particular char that see this happen.

**Comment by TheGreyMouser** [comment]
One of the GM seems to be really power tripping (I know you heard it before), however...

1 world chat contained references to masturbation, Asmodeaa did nothing

2 also contained reference to incest (father/ son) Asmodeaa did nothing

I made a joke that contained the word queef and got muted.  What is worse, Asmodeaa blatently lied and said it was after a warning, which was never sent.   I don't mind the mute as much as I do him claiming he warned first, when he clearly did not.


What I actually said was "I had my ex gf so broken in, when she queefed it echoed.  No swear words.

Also.. saying alliance is a bunch of pussies has nothing to do with the word "pussy" as it relates to female anatomy.  It is a common term for wimps, is used on teen tv shows on YTV, and is a common expression for well.. a 'fraidy cat.


I won't be posting this in forum or discussing it in game chat, but thought you should know.  Nobody likes a tight ass that looks for reasons to mute.


Gary Balkam

aka Amagezing

________________________________
