### ISSUE TITLE
Lady Deathwhisper Full House Achievement

### ISSUE THREAD

**Issue by wissamkawass** [WoWManiaUK/Redemption#2256]
Lady deathwhisper doesn't spawn all the adds, there's an add she doesn't spawn i'm not sure what the name is but u can't do the achievement unless she spawn all 5 kinds of adds. please fix it so we can do Glory of The Icecrown Raider.

**Comment by fvicaria** [comment]
Unless you tell me exactly which NPC you think is missing I cannot do anything about it.

I recommend you read this: 
Please follow the procedure described below before creating a new issue:
[How to Properly Report an Issue](https://github.com/wow-mania/Redemption/wiki/How-to-Properly-Report-an-Issue)

This will help developers identify and fix the issue quicker. Incorrectly or unclear reports will simply be deleted.

**Comment by fvicaria** [comment]
Tested and working anyways.

**Comment by wissamkawass** [comment]
the name of the NPC's are reaminated cult adherent and reaminated cult fanatic and they do not spawn which they should

**Comment by wissamkawass** [comment]
can you see this or should i open a new ticket?

**Comment by wissamkawass** [comment]
yeah they aren't appearing after we kill the NPC's lady deathwhisper is not rebirthing them

**Comment by Dranah** [comment]
you must not kill the npcs, they suicide
