### ISSUE TITLE
[Quest]Jaina's locket

### ISSUE THREAD

**Issue by squalllh1989** [WoWManiaUK/Redemption#2258]
The quest work properly, but there is a problem with it:
- When you open [Unsealed Chest](http://www.wow-mania.com/armory/?item=51316), you get some item from there, which you can use to turn in at the npc that appear for reward. You won't get given any quest, but you can turn in the item to the npc to get the quest completed and get your reward.
- The problem is: when you turn in [Muradin's Lament](http://www.wow-mania.com/armory/?quest=24917) before [Jaina's Locket](http://www.wow-mania.com/armory/?quest=24916), [Jaina's Locket](http://www.wow-mania.com/armory/?quest=24916) will be unable to turn in when muradin is saying his dialog (the yellow question mark above jaina disapear until muradin finish his dialog), then the quest will be avaible again to turn in. But, if you didn't notice it and just turn in all quest in your sight and leave icc, without notice that [Jaina's Locket](http://www.wow-mania.com/armory/?quest=24916) isn't turned in (so you still have the item, [Jaina's Locket](http://www.wow-mania.com/armory/?item=51318) in your bag), for sometimes, when you come back to icc, muradin and jaina isn't there anymore, so you can't turn in the quest and get your reward. (This is the trouble i have, need to go after the raid so i turn in all quest in my sight then leave icc without notice that there is 1 quest i haven't turned in yet, later log in, found that out but can't solve it)

**Comment by fvicaria** [comment]
As-is this is available while the raid id is valid. You will need to do it again if you leave.
