### ISSUE TITLE
[Boss] Lady Deathwhisper - adds spawning

### ISSUE THREAD

**Issue by Munja357** [WoWManiaUK/Redemption#2259]
On 25hc Lady Deathwhisper adds are spawning too fast, can you take a look, because its really hard to do LDW now.

**Comment by fvicaria** [comment]
As is.

**Comment by Munja357** [comment]
No, adds are supposed to spawn for example every 40 seconds, and they are spawning every 20 seconds now, thats problem.

**Comment by fvicaria** [comment]
I will check.

**Comment by Munja357** [comment]
Ty

**Comment by Munja357** [comment]
Btw, im not sure how is it on 25nm or 10hc/nm, maybe you can check that too.

**Comment by fvicaria** [comment]
p1 45-60s 
p2 45
As-is.

**Comment by Munja357** [comment]
Well, last night on 25hc, and today on 2nd 25hc adds was spawning every 20-25 seconds, which is not normal.

**Comment by philoudu16** [comment]
You might not be used to the adds that appear after casting dark martyrdom. Until the fix, adds would just die after casting it. Now, that ability works properly and the adds who complete the cast respawn as reanimated adherents/fanatics.

**Comment by TheManiax** [comment]
What we changed recently here, is adherent and fanatic going to empowered form as intended
We didn’t change the timers
But I will check tomorrow to make sure

**Comment by Munja357** [comment]
Small update, on 25nm adds was spawning normaly.

**Comment by fvicaria** [comment]
Cool, ty.

**Comment by TheManiax** [comment]
The issue is that in 25hc mode, DBM is detecting NM timers
So players are thinking that adds are spawning too fast
I don't know how the addon distinguish the difficulty on the boss to set the proper timer bars
At the moment, the DBM addon uses wrong difficulty timer bars

**Comment by Keader** [comment]
DBM is not always correct.
Lady was scripted using sniff by Sirikfoll (sniff = copy of blizzard server comunication with client), is more precise tool possible.

**Comment by squalllh1989** [comment]
Work correctly i think, add apear each 45 sec in both phase 1 and 2

**Comment by MailOrdered** [comment]
@fvicaria Can you guys link me to the wiki page or something where it says 45 seconds? I've been running around and all I can find are videos showing it at 1 min and the wow wiki saying: 

> After 5 seconds of combat and every 60 seconds thereafter 3/7 (10/25 player) adds spawn. In 10 player, 3 adds spawn alternatively from the three gates on the left and right side. In 25 player, 3 adds spawn on each side every time, and a seventh add of a random type spawns on the stairs. The three gates on the left side of the room always spawn two fanatics and one adherent, the right side gates one fanatic and two adherents. All types of adds can be CC'd.

I might be able to calm down my raid leader if you could direct me to something. Thanks.

**Comment by TheManiax** [comment]
@MailOrdered
Scroll down the same page you are linking and watch the 25hc video

**Comment by MailOrdered** [comment]
Thanks.
