### ISSUE TITLE
[Dungeon] Jammal'an the prophet

### ISSUE THREAD

**Issue by StefanelStan** [WoWManiaUK/Redemption#2260]
Issue : Force field around Jammal'an boss in sunken temple is not going down even if all 6 guardians from balconies are dead.
Link: http://www.wowhead.com/npc=5710/jammalan-the-prophet#comments
The top comment says : " All 6 of these trolls must be defeated before Jammal'an can be fought because they form a shield which protects the area Jammal'an resides in". All 6 mini bosses (Zul'lor, Gasher, Hukku, Loro, Zolo, and Mijan) have been killed  but the force field is still active. I have done this 3 times already.
This boss is required for quest http://www.wowhead.com/quest=1446/jammalan-the-prophet#comments
Thanks

**Comment by philoudu16** [comment]
Confirmed:

**At the moment**, activating the statues in the right order (which summons Atal'alarion) is also what triggers the shield.

**How it should work:**
Killing the six trolls on the top floor (Zul'lor, Gasher, Hukku, Loro, Zolo, and Mijan) is what should trigger the shield.

**Comment by flumby** [comment]
When I ran this completing it in order (apart from Hakkar) I was able to complete this dungeon, I have not tested this with not killing atal’alarion.  Will go through the dungeon again without killing the boss which could be triggering the shield.

**Comment by flumby** [comment]
Confirmed

**Comment by StefanelStan** [comment]
It's hard to say the ID of the forcefield. I have opened up a ticket and GM Metaxa came to the dungeon and deactivated the shield. Maybe he knows. Thanks.

**Comment by fvicaria** [comment]
Also works just fine. Jesus, need to improve the quality of issues logged by testers :)

Go to Pit of Refuse, activate all 6 statues, kill boss and the force field will be down.

**Comment by philoudu16** [comment]
Do your own research before blaming the testers...

As I said just above, and as **EVERY** source available on internet says, **killing the six trolls** on the top floor (Zul'lor, Gasher, Hukku, Loro, Zolo, and Mijan) is what should trigger the shield. The statues on the bottom floor should have **NOTHING** to do with the shield... The only purpose of the statues is to summon Atal'alarion, which is a completely **OPTIONAL** boss.

If you want to check the sources:
http://www.wowhead.com/npc=5710/jammalan-the-prophet#comments (top comment if sorted by rating, written before the cata rework)
http://wowwiki.wikia.com/wiki/Temple_of_Atal%27Hakkar_(original)#Walkthrough (this is the version of sunken temple before the cata rework)
https://wow.gamepedia.com/Temple_of_Atal%27Hakkar#Notes
http://www.almarsguides.com/wow/instances/sunkentemple.cfm

**Comment by StefanelStan** [comment]
@fvicaria I have posted all the details and how this dungeon should work on 335, including links on how it should work (if you would just follow the link and read the comment, you would have your answer of how this should work).
@fvicaria Not everything is "working as intended". Some people work on finding the defects, gather information and links on how it should work, post them accordingly.

**Comment by fvicaria** [comment]
Do not reopen. I have done it and it works.

**Comment by StefanelStan** [comment]
OMG.
The statues are not related to the force field! Sunken Temple has 2 levels: the upper side where you deal with 6 mini-bosses/trolls that once killed, release the force field that block Shadow of Eranikus + Jalmal'an and an lower side, which contain 6 serpent statues which upon activation relase an optional boss (a big troll).
Both of us + WOWHEAD are trying to explain you this mechanism. Can you please link WHERE you read that activating the 6 serpent statues will deactivate the 2 force fields? We have posted links that backup our words. Can you do the same ?
Thanks

**Comment by Dranah** [comment]
To clear up confusion, it is left "as-is" which means its "good enough" for now ,because it's doable just fine, even if not the exact same way as blizzard. Doesn't mean it is perfect but it is minor difference that isn't gonna be fixed atm because its too much hassle.

**Comment by fvicaria** [comment]
With time I will try to add the same functionality that currently relies on the statues to the mini-bosses.

**Comment by StefanelStan** [comment]
@Dranah  yes, I agree; it works partially BUT here is where the bug is:
1. Once all 6 trolls are dead (the balcony trolls), 2 force fields should be deactivated. One forcefield blocks Jammal'an and another forcefield blocks Shadow of Eranikus, which is the final boss/achievment boss.
The 2nd forcefield does go down but the first one stays up.
2. How would some1 doing this dungeon know that he/she has to kill the bottom side as well to lower it?
I've done this 3 times, wasted 45 minutes trying to get to jammal'an. 
By ALL means, if you put a big warning sign saying "you have to clear the bottom area as well" to get to that boss, then it's fine. But there is no warning sign.

**Comment by flumby** [comment]
I thought so, so I was right :P

Sent from my iPhone

On 17 Feb 2018, at 14:16, Stefannel <notifications@github.com<mailto:notifications@github.com>> wrote:


OMG.
The statues are not related to the force field! Sunken Temple has 2 levels: the upper side where you deal with 6 mini-bosses/trolls that once killed, release the force field that block Shadow of Eranikus + Jalmal'an and an lower side, which contain 6 serpent statues which upon activation relase an optional boss (a big troll).
Both of us + WOWHEAD are trying to explain you this mechanism. Can you please link WHERE you read that activating the 6 serpent statues will deactivate the 2 force fields? We have posted links that backup our words. Can you do the same ?
Thanks
