### ISSUE TITLE
PG Restored to a previous version

### ISSUE THREAD

**Issue by Pixellone** [WoWManiaUK/Redemption#2261]
I left my pg on level 73 with some chain quests done, after a while AFK I found my PG as it was before playing today.
Talked to GM Psygoa and he suggested me to open an issue here.

Tnx

P.S. I lost money, items, and more... it seems like a restored backup version of the PG
PG Name: Pizzocalabro

**Comment by fvicaria** [comment]
Unless you can give more info and tell me what client you have nothing I can do about it. Send info to support@wow-mania.com
