### ISSUE TITLE
[Spell] Unchained Magic (Sindragosa)

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#2263]
Hello,
After some research I have to report target priority of Unchained Magic http://www.wow-mania.com/armory/?spell=69762

How it works right now: 
- The debuffs are cast completely randomly on 2 / 6 (10/25man) targets that possess a mana bar.

How it should work:
According to all relevant sources, this is an intelligent debuff, which should prioritize targets based on their **talent specs**

1. It should be cast on 1 healer and 1 caster dps on 10man and 3-3 on 25man as long as it finds targets that meet this criteria. (choosing by talent spec, not gear or activity)
This ensures that it isn't possible to debuff all healers at once.

2. If there are fewer than the required casters present in the raid, it will begin targetting other mana users (hunters, retris, enhas). 
This was a hotfix by blizzard as the pioneer raids were abusing the buff by not bringing caster dps and thus Sindragosa only debuffed their healers. Since then, other mana users are eligible as secondary targets, but based on all video and commentary sources, no physical dps ever receives the debuff as long as there are enough caster dps present (warlock, mage, shadow priest, elemental or balance druid)

**Comment by fvicaria** [comment]
Targets are as-is.

**Comment by Dranah** [comment]
Please work on this one

**Comment by Dranah** [comment]
Just to clear up things, because my wording may have been unclear, the spell has two components with the following priorities:
Unchained 1: Targets always caster (1 on 10man, 3 on 25man) > If no casters, targets healer > If no caster, no healer, then targets other mana user
Unchained 2: Targets always healer (1 on 10man, 3 on 25man) > If no healer, targets caster > If no healer, no caster, then targets other mana user

Caster specs: Warlock, Mage, Spriest, Boomie, Elemental
Healer specs: Holy pally, Holy priest, Disc priest, Resto druid, Resto shaman
Other mana user specs: Retri, Enha, Hunters, Prot pally

Some additional sources:
Wowhead:
By Jinxed (2,616 – 3·28) on 2010/08/10 (Patch 3.3.5)
Casters and healers don't share this debuff, but get one each. Or in 25-man, three each.

Here's a blue post apologizing for accidentally two healing getting hit on 10man (no precedent before) because the spell bugged out on patch 4.0 and began ignoring elemental shams:
https://blue.mmo-champion.com/topic/127674-sindragosa-unchained-magic-bug-/

Here's another https://www.mmo-champion.com/threads/708127-sindragosa-10-man-heroic-(we-need-help)
 _It only targets more than one healer in 10 man if all your caster DPS are dead. It's a smart targeting spell: one caster DPS and one healer are the targets. Which means if you only have one caster... the poor son of a bitch constantly has unchained magic. Like my mage._ 


You can watch a dozen retail Sindragosa kill videos and without exception, each round of unchained goes on 1 healer - 1 caster (10man), or 3heals-3caster( 25man). No flaws in this system.
As long as there are enough casters (dps or heals), you will NEVER see the debuff on a hunter or enha.

The only case when a hunter can be target for Unchained magic is when there aren't enough targets (2/6) with caster dps and healers combined. This is how retail guilds first killed Sindragosa, using only 3 healers on 25man, with an army of hunters max DPSing, because only the 3 healers would receive the buff.

Blizzard made a silent fix to prevent this from becoming a practice, allowing other mana users to be secondary targets if the raid is completely lacking on casters/healers.

**Comment by Dranah** [comment]
PS: dead or tombed players cannot receive unchained magic, which is the most common reason for the debuff needing to go on someone it normally wouldn't.
