### ISSUE TITLE
Issues with Shaman Healing totem.

### ISSUE THREAD

**Issue by Grisweld** [WoWManiaUK/Redemption#2264]
At Max rank a Majority of the people I have spoken to including myself are having issues with our healing stream totem healing for much less then what it was in the past. The healing tics we are seeing range from 39-50 per 2 secs which is lower then what they have been in the past and really hinders the usage of the healing stream totem.

**Comment by Grisweld** [comment]
Was this issue resolved or just closed the topic?

**Comment by fvicaria** [comment]
Sorry. There was some code reverted this morning. So it should be back to what is was.

**Comment by Grisweld** [comment]
Ok thank your for a quick response :) and hopefully a quick fix :)
