### ISSUE TITLE
[Raid] Frostmourne Room (Lich King)

### ISSUE THREAD

**Issue by CrustyMuffin** [WoWManiaUK/Redemption#2265]
I know that you closed a ticket about it a few days ago but our guild had this problem for the past few weeks too. We did icc 10nm yesterday and it happened again, so it´s obviously not working. The issue is, that during the Lich king encounter (http://www.wowhead.com/npc=36597/the-lich-king) on pretty much every difficulty the Lich King enrages and intantly kills every healer that get´s dragged into Frostmourne regardless of current health. It never happens to any other role except healers, so there must be a problem about the healer version of Frostmourne. I know you´ve already tested it and think it´s working as it should but please check it again.

**Comment by fvicaria** [comment]
If as-is.

**Comment by CrustyMuffin** [comment]
how can this be? It was never like this a few weeks back.

**Comment by fvicaria** [comment]
Exactly nothing changed. I can re-check but unlikely.

**Comment by CrustyMuffin** [comment]
how is people instantly dying considered "working as-is"?

**Comment by CrustyMuffin** [comment]
please do

**Comment by fvicaria** [comment]
No, I consider you have an opinion about the problem that not necessarily matches the facts. As I said I will re-check.

**Comment by CrustyMuffin** [comment]
thanks
