### ISSUE TITLE
Kalu'Ak Fishing Derby

### ISSUE THREAD

**Issue by t2krieger** [WoWManiaUK/Redemption#2266]
The Kalu'Ak Fishing Derby happens every saturday between 14:00-15:00, where the first person to catch and bring a "blacktip shark" to Elder Clearwater, in Dalaran, gets rewarded.

Simply fish pools (schools) in Northrend until you catch a Blacktip Shark. Technically found anywhere Pygmy Suckerfish can be caught, but the catch rate is higher from pools.
Anyways, this was the second time I tried the event, but the shark simply can't be fished, normally it would take around 10-15 minutes of fishing to loot it, but I tried for the entire hour of the event (twice), not getting any shark.

Kalu'ak Fishing Derby short info :
Duration : 1 hour
Location : Northrend
Time : Each Saturday, 14:00-15:00 server time
Objective : Catch Blacktip Shark
How to : Once the derby begins you should fish along shores, pools, rivers all over northrend fishing School of Fish.
Complete : Return to Dalaran to Elder Clearwater near daily fishing quest giver Marcia Chase.

Some usefull info :
It can be fished with any fishing skill (req. 1 skill)
It can be fished at any school of fish in northrend.
Even if you dont win you get a Bag of fishing treasures for catching the shark.

Thanks.

**Comment by fvicaria** [comment]
What do you mean it can't be fished? Chances go from 0.01% to 0.1%... this means you have ON AVERAGE to try between 1,000 to 10,000 times.
To ASSERT that it can be done you need to come back to me saying you tried at least 5 times that.
Would you say a coin is rigged if you threw it 3 times and got 3 heads?

If you don't provide me numbers I have no other choice but to close this issue.
