### ISSUE TITLE
Shaman Totems Still not correctly healing

### ISSUE THREAD

**Issue by Grisweld** [WoWManiaUK/Redemption#2267]
Shaman totems are still broken. the healing being done by the healing stream totem is still ineffective.

**Comment by TheManiax** [comment]
[Healing Stream Totem](http://www.wow-mania.com/armory/?spell=5394)

- **How it should work:**
According to Blizzard Patch notes;
Patch 1.11.0 (2006-06-20): Healing done now scales with bonus healing from gear. Mana cost reduced.
- **How it works:** 
The amount healed by the totem is constant and not scaling with Healing Bonus on gear.
