### ISSUE TITLE
[Icecrown Citadel] - Lady Deathwisper adds spawn time

### ISSUE THREAD

**Issue by Kurioss** [WoWManiaUK/Redemption#2268]
Me and my guild just confirmed that the adds spawn time on Lady Deathwisper is off, adds spawned every 45 seconds, when they are suppose to spawn every 60 seconds which is blizzlike. We had a GM comming and telling us that we where wrong even tho we showed him that it was not a correct timer. 

![image](https://user-images.githubusercontent.com/33106831/36345927-d09f4054-1434-11e8-8026-ff9cc7b55f72.png)

It mentions clearly that at the start of the encounter it takes 5 seconds for the adds to spawn, that is correct and it does on the server, but as soon as the adds spawn it should take 60 seconds for the next set of adds to spawn, but on wow mania it takes 45 seconds, even with good dps this is hard to veary difficult to accomplish. 

The GM Amatry was watching us doing the fight and said it was 45 seconds, he can confirm it was 45 seconds but he did not want to do anything about it because Amatry was sure blizzlike is45 seconds but its not.

**Comment by fvicaria** [comment]
Please do not open the same issue when the previous one was closed.

**Comment by philoudu16** [comment]
Checked youtube retail videos: timers should be 45s on 10hc and 25hc, 60s on 10nm and 25nm.
