### ISSUE TITLE
[Npc] Daggertail Lizard missing

### ISSUE THREAD

**Issue by Feloxis94** [WoWManiaUK/Redemption#2269]
Hello, in the region of Crystal Spine in Blade edge mountains, theyre is suppose to be red warp stalker called Daggertail Lizard, but after swooping the entire area, they are none of them and i have checked the wow head to see where they were spawning but nothing, i taught they were cloaked soo because im a hunter i use track hiddens but to no result, i think they are just missing from the server. pls check it out :)

**Comment by fvicaria** [comment]
They have removed some point during TBC and came back on Cata.
I can add them no problem.

**Comment by Magabro** [comment]
FYI i believe these are minions that phase.  Half the time they are invisible and half the time they are visible.  so With 1 pass it is likely you didnt see them in the area cause they were not visible.

**Comment by Feloxis94** [comment]
Pls add them, it would be awesome for me and the other hunters out there and i now that for a  time warp stalker can be invisible but i have scout this area for half a hour and trust me they are not there.

**Comment by fvicaria** [comment]
They have been added. It will be on after the next update.

**Comment by Feloxis94** [comment]
By thye way now that im thinking, In a chain quest of the Shartari sky guard in Skettis you need to summon 4 elite beast and kill them, one of them is Gezzarak the huntress, she is also a warp stalker , the only black one except of the pet of the horde npc on dalaran, she is a gold elite but not tamable. Is it possible for you to make her become tamable by hunters ?
