### ISSUE TITLE
[Spell] Magma totem

### ISSUE THREAD

**Issue by squalllh1989** [WoWManiaUK/Redemption#2272]
[Magma totem](http://www.wow-mania.com/armory/?spell=58734)
How it should work:
According to Blizzard Patch notes;
Patch 3.0.8 (2009-01-20): The damage and scaling has been increased and no longer generates threat.
Patch 1.11.0 (20-Jun-2006): This totem now receives increased damage from effects that increase the Shaman’s spell damage.
=> The totem's damage should be scaling with Spell power bonus from gear.
How it works:
The damage done by the totem is constant and not scaling with Spell power Bonus on gear.
Test the totem:

1st test: the totem does 426 fire damage without any gear (no gear at all, only the totem relic which give no bonus, spell power bonus damage stat is 160)
![wowscrnshot_021918_190606](https://user-images.githubusercontent.com/27235989/36377389-9bee667a-15a9-11e8-8305-f0375d57c776.jpg)

2nd test:  After equipt the mail lich king set, spell power bonus stat is now 1530, but the totem still does  426 fire damage.
![wowscrnshot_021918_190729](https://user-images.githubusercontent.com/27235989/36377659-7ce60b9c-15aa-11e8-8dc2-a19ca5971a15.jpg)

I do the same test to [Searing Totem](http://www.wow-mania.com/armory/?spell=58704):

1st test: Without any gear, spell power bonus damage stat is 160, Searing totem does 133 fire damage
![wowscrnshot_021918_190847](https://user-images.githubusercontent.com/27235989/36377750-cde558fe-15aa-11e8-926a-aba71053ab38.jpg)

2nd test: After equipt the mail lich king set, spell power bonus stat is now 1530, Searing totem now does 410 fire damage
![wowscrnshot_021918_190822](https://user-images.githubusercontent.com/27235989/36377808-0301879c-15ab-11e8-9a19-00bc7bb14223.jpg)

=> Searing totem is scaling with bonus spell power from gear, but it seem magma totem doesn't, while they should both does.

**Comment by Magabro** [comment]
Just tested on Dev server.  Magma totem damage increased as spellpower gear was equipped.  Appears fixed.

![wowscrnshot_021918_094014](https://user-images.githubusercontent.com/34353250/36390947-5a6a8ac6-1559-11e8-9ea4-946535ea3d60.jpg)
