### ISSUE TITLE
[Dungeon] Sunken Temple (or The Temple of Atal'Hakkar)

### ISSUE THREAD

**Issue by squalllh1989** [WoWManiaUK/Redemption#2273]
- How it should work: There will be a force field that block 2 area, [Jammal'an the prophet](http://www.wow-mania.com/armory/?npc=5710)'s area and the area where the last boss, [Shade of Eranikus](http://www.wow-mania.com/armory/?npc=5709) stand. 
After kill 6 troll mini bosses ([Zul'lor](http://www.wow-mania.com/armory/?npc=5716), [Gasher](http://www.wow-mania.com/armory/?npc=5713), [Hukku](http://www.wow-mania.com/armory/?npc=5715), [Loro](http://www.wow-mania.com/armory/?npc=5714), [Zolo](http://www.wow-mania.com/armory/?npc=5712), and [Mijan](http://www.wow-mania.com/armory/?npc=5717)), the force field where [Jammal'an the prophet](http://www.wow-mania.com/armory/?npc=5710) stand will be remove.
After kill [Jammal'an the prophet](http://www.wow-mania.com/armory/?npc=5710), the force field where  [Shade of Eranikus](http://www.wow-mania.com/armory/?npc=5709) stand will be remove, and 2 dragon ([Dreamscythe](http://www.wow-mania.com/armory/?npc=5721) & [Weaver](http://www.wow-mania.com/armory/?npc=5720)) will spawn at the room in the midle of the temple.
When you pull [Shade of Eranikus](http://www.wow-mania.com/armory/?npc=5709), his 4 lesser dragon ([Dreamscythe](http://www.wow-mania.com/armory/?npc=5721), [Weaver](http://www.wow-mania.com/armory/?npc=5720), [Morphaz](http://www.wow-mania.com/armory/?npc=5719), [Hazzas](http://www.wow-mania.com/armory/?npc=5722) will come to him if they are alive.
- How it is working right now: 
+The force field that block the room where [Jammal'an the prophet](http://www.wow-mania.com/armory/?npc=5710) is NOT broken after kill all 6 of the troll that channeling the shield. To actually broke it and get in the room, you must active the statue at the 2nd floor and kill [Atal'alarion](http://www.wow-mania.com/armory/?npc=8580) which is a optional boss and got nothing to do with the force field.
+There is no force field block the room where [Shade of Eranikus](http://www.wow-mania.com/armory/?npc=5709) stand from the start, so you don't have to kill anything else, you just go to him and kill him, and you are done, all other boss can be skip. When pull him, the 4 dragon that should come to aid him doesn't come.

**Comment by fvicaria** [comment]
Sorry I have already explained that this will remain as-is.
Deactivate the 6 snake statues and the field will go down.
If and when we have time we may change the mechanism.
This was clearly specified here: #2260

**Comment by squalllh1989** [comment]
Sorry it seem that i misunderstand you after read the few comment up front, which make me remember about this and do some research and retest.
It's ok to let it remain like this, there isn't any big problem at all, just need to state clearly that this is isn't working properly (the problem stated is true) but it won't be fix at this point. I understand that there are a lot more important problem arround that need to get priority over something that doesn't affect much on the progress.

**Comment by fvicaria** [comment]
The functionality implemented in dev.
Now when you kill the 6 bosses the forcefield will come down also.
Statues remain as an alternative also.
