### ISSUE TITLE
[Boss] Malygos-The Eye of Eternity

### ISSUE THREAD

**Issue by Bartok14** [WoWManiaUK/Redemption#2274]
The is an issue with The Eye of Eternity raid on phase 1 everyone after a little bit of time is supposed to fly up into the air and start taking dmg from the aoe. Some people are supposed to be able to damage him from what I remember and healing needs to go off during this part of the phase. 
1) Currently in phase 1 no one gets sent up into the air so this part of the fight isn't working as intended. Instead everyone just stays on the platform and after about 10 seconds we start taking damage then. Rest of the fight seems to be working as intended.

**Comment by fvicaria** [comment]
There is an issue already for Malygos. Even though it may not be the same issue we deal with it as one.
I will attach this to the existing report.
