### ISSUE TITLE
[Spell/Rogue] Cloak of Shadows dont work properly

### ISSUE THREAD

**Issue by Keader** [WoWManiaUK/Redemption#2275]
Cloak of Shadows should not remove spells like: Unbound Plague
And should remove spells like: Chilled to the bone and Swarm Shadows (Blood Queen)

**Comment by BatuMania** [comment]
Since when is Cloak removing Plague? Thought this was fixed months ago

**Comment by Keader** [comment]
Idk since when...
But was removing
