### ISSUE TITLE
[Quest]weaponsmith specialisation

### ISSUE THREAD

**Issue by agochhu** [WoWManiaUK/Redemption#2276]
I did "the way of the weaponsmith" quest, managed to make all weapon needed but can't validate the quest.
![image](https://user-images.githubusercontent.com/36667156/36427457-86a4882c-164d-11e8-96a7-86cfc766278c.png)

**Comment by fvicaria** [comment]
Ask a gm to remove ques and re-do it.
This usually happens when you do multiple quests that requires same items.
