### ISSUE TITLE
Argent tournament daily quest

### ISSUE THREAD

**Issue by gerard911** [WoWManiaUK/Redemption#2279]
There's a bug with the daily quest in argent tournament ground "Learning the reins" once you equipped your lance and you try to ride the horse, instead of mounting it it summons another one which you cannot ride and then you are bugged and cannot take any action.

**Comment by fvicaria** [comment]
Pretty sure it works.
Drop the quest and retake. Make sure you have all pre-reqs done.

Also ready this:
Please follow the procedure described below before creating a new issue:
[How to Properly Report an Issue](https://github.com/wow-mania/Redemption/wiki/How-to-Properly-Report-an-Issue)

This will help developers identify and fix the issue quicker. Incorrectly or unclear reports will simply be deleted.

**Comment by fvicaria** [comment]
Known issue. Some bad code got pushed on today's update. It affects all vehicles.
Should be fixed in 1h or so.
