### ISSUE TITLE
The Hunter and the Price

### ISSUE THREAD

**Issue by Sexeh** [WoWManiaUK/Redemption#2280]
http://www.wowhead.com/quest=13361/the-hunter-and-the-prince
Arthas is just watching Ilidan to disappear

**Comment by fvicaria** [comment]
Please follow the procedure described below before creating a new issue:
[How to Properly Report an Issue](https://github.com/wow-mania/Redemption/wiki/How-to-Properly-Report-an-Issue)

This will help developers identify and fix the issue quicker. Incorrectly or unclear reports will simply be deleted.
