### ISSUE TITLE
[Warrior] Recklessness

### ISSUE THREAD

**Issue by LooneyBin** [WoWManiaUK/Redemption#2281]
There's currently a problem for warriors using Recklessness, the skill activate, but we dont get the 100% crit, and the charges on the skill doesn't go down aswell.

http://www.wow-mania.com/armory/?spell=1719

How it should work:
Special ability attacks have an additional 100% chance to critically hit but all damage taken is increased by 20%.

How it actually works:
You maintain you normal crit chance on skills like Whirlwind, Bloodthirst etc.
So currently Recklessness is not working as intendet.

**Comment by fvicaria** [comment]
Since when?
Send me screenshots if possible.

**Comment by ragehoof72343** [comment]
will post a video soon

**Comment by ragehoof72343** [comment]
https://youtu.be/w2sxzUdAoRE   here is the video. In this video u can see that i am attacking the target and i poped recklessness. But didnt get any crit and Charges on the skill dont go down as well  
  http://www.wow-mania.com/armory/?spell=1719

**Comment by fvicaria** [comment]
Since when?

**Comment by ragehoof72343** [comment]
i noticed this bug today

**Comment by Unstoppablee** [comment]
Tested multiple times on my warrior. It is not working.
No one complained about it yesterday. Can it be after latest restart today around 11 AM?

**Comment by fvicaria** [comment]
I can put yesterday's build on dev.

**Comment by Unstoppablee** [comment]
Do it. I will need your assistance there.
