### ISSUE TITLE
Dk Frost KM

### ISSUE THREAD

**Issue by Donigala** [WoWManiaUK/Redemption#2282]
there is a graphic error on this spell.

Its everytime up the proc icon but the proc doesn't work

**Comment by ragehoof72343** [comment]
thats not graphic issue thats a spell issue.....everytime http://www.wowhead.com/spell=51128/killing-machine   procs but it dont crit at all plus it dont go down as well the same problem like the recklessness buff bug

**Comment by Unstoppablee** [comment]
Devs are aware of problem, and they are working on fix. 
Please be patient.

**Comment by Donigala** [comment]
Sorry for this my English is so bad so I can't explain the problem
properly, typing rage hoof!

Il 22 feb 2018 1:45 PM, "ragehoof72343" <notifications@github.com> ha
scritto:

**Comment by fvicaria** [comment]
Same issue as #2281
