### ISSUE TITLE
[Talent] Santified Retribution and [Skill] Retribution Aura

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#2283]
Hello,
I'd like to report a recurring rollback issue for Retribution paladins that use the talent "Sanctified Retribution" http://www.wow-mania.com/armory/?spell=31869 in conjunction with Retribution Aura http://www.wow-mania.com/armory/?spell=54043
Having the retri aura buffed by this talent on yourself seems responsible for triggering a loop of rollbacks.
- Your character gets saved on a specific location where you logged off with the bugged aura on yourself.
- Everything you do afterwards gets rolled back (items, kills, gear status etc. and you always start from the very same position) upon next relog.
- Removing ret aura or resetting the talent can both disable the issue
This bug only affects the paladin.

**Comment by Magabro** [comment]
I confirmed this issue is occurring on live and dev servers.  When a paladin has Sanctified retribution talented and logs out with retribution aura active, subsequent logouts will roll the character back until retribution aura is removed or the talent is removed.

**Comment by Keader** [comment]
WTF? o.O

**Comment by xclaw800** [comment]
This is the fix that caused it possibly. https://github.com/WoWManiaUK/Redemption/issues/2073

**Comment by Keader** [comment]
Not related, same spell, but no idea wtf this issue is.

**Comment by fvicaria** [comment]
There was no rollback.
Can you please confirm this in dev, please.
It probably was never fixed.

**Comment by fvicaria** [comment]
This has been fixed today.
