### ISSUE TITLE
<Fortunate Misunderstandings> Malfunctioning

### ISSUE THREAD

**Issue by Frammit** [WoWManiaUK/Redemption#2285]
Hello, I am having issues with the quest "Fortunate Misunderstandings" in Scholozar Basin. I checked the closed tickets on github and saw that people have posted about this problem before, and it's been reported as fixed, but it seems to be doing the same thing as before.

The NPC "Injured Rainspeaker Oracle" will give me the quest, but when I click "I am ready to travel to your village now" nothing happens.

To qualify for this quest, you must complete the quest "Just Following Orders" from "High-Shaman Rakjak"

So far, I have: 
 - Abandoned quest, logged out and back in, and reaccepted
 - Cleared Cache
 - Double-checked that the launcher and client are up-to-date
 - Spoken with all five "Injured Rainspeaker Oracle"s

And I still can't seem to get it to work. Thank you for your help.

EDIT: Formatting errors

**Comment by fvicaria** [comment]
Pretty sure this quest works fine if you have all pre-requisites.
Check on our Armory.
I will check in dev and update here shortly.

**Comment by Frammit** [comment]
I just checked on the Armory and the only prerequisite is "Just Following Orders," which I've completed and confirmed by checking to make sure the Frenzyheart are all hostile.

**Comment by fvicaria** [comment]
![image](https://user-images.githubusercontent.com/9414661/36639349-e57b8e78-1a02-11e8-9e43-30624d6054a7.png)
![image](https://user-images.githubusercontent.com/9414661/36639352-f7e9d8ee-1a02-11e8-84f4-f2aead26bd94.png)
![image](https://user-images.githubusercontent.com/9414661/36639356-04b4601c-1a03-11e8-8d27-225044571ffb.png)
![image](https://user-images.githubusercontent.com/9414661/36639362-17ba14c2-1a03-11e8-9415-e8495c21d31b.png)
![image](https://user-images.githubusercontent.com/9414661/36639366-25fade7c-1a03-11e8-8299-160326666360.png)
and there he goes...
![image](https://user-images.githubusercontent.com/9414661/36639373-397be7c0-1a03-11e8-9ca2-c009fa317500.png)

![Uploading image.png…]()

That doesn't mean that you are not right and it doesn't have a problem. Just that it is working in most cases.
What is your race? and char name?

**Comment by Frammit** [comment]
Goblin warrior, level 77, named Frammit. I've now also tried doing it on a different computer, and I've tried doing it over at least once or twice a day with no luck.

**Comment by Frammit** [comment]
I asked around in world chat and someone suggested clicking the "I am ready to go to your village" button and going to the village anyway even if the NPC doesn't move, and that didn't work. Someone also suggested aggroing a mob near the NPC to get them to move but that also didn't work.

Since this seems to be a goblin / worgen issue, I would assume if I could be in a group with a non-goblin character on the same quest, they could initiate it by clicking "I am ready to go to your village" and I can still get credit.

**Comment by fvicaria** [comment]
I will check the quest for Worgen and Goblin today. Thanks

**Comment by fvicaria** [comment]
Finally found the issue. It will be fixed for next update.
