### ISSUE TITLE
Chain quest to "Champion of allance"

### ISSUE THREAD

**Issue by Sarnjo** [WoWManiaUK/Redemption#2286]
I [found](http://www.wowhead.com/quest=13667/the-argent-tournament#comments), in this link the described task sequence to be done for the initial factions to get the "Champion of Alliance". 

5.The Valiant's Charge and complete the daily quests are listed below [Valiant's Seals] to continue. (25 seals at 5 per day)
7. The Valiant's Challenge

After completing "The Valiant's Challenge", the following quests are the champion of the quests (steps five and seven).

After fulfilling these conditions, I won [Champion of Darnassus] and [Champion of Exodar]. According to the description in the first comment after the 7th point, you should be able to access the factions that I have not finished. My question is why I do not have access to the 3 factions?

**Comment by fvicaria** [comment]
Quests work.
Check requirements on our armory.
