### ISSUE TITLE
Quest: Mutiny of the Mercy

### ISSUE THREAD

**Issue by Saplu** [WoWManiaUK/Redemption#2288]
There spawns only one quest mob at a time on the Captain Ellis' ship.
You need to kill five to complete the quest.
Also, the internet tells me that there should be some 8-9 mobs spawning at a time.

The quest is doable, but frustrating because of the waiting between spawns.

**Comment by fvicaria** [comment]
Please search before posting a new issue.
The quest works. Sometimes the mobs fall from the boat but you will find more on other docked boats.
