### ISSUE TITLE
<Foolish Endeavors> Malfunctioning

### ISSUE THREAD

**Issue by kavky** [WoWManiaUK/Redemption#2289]
Hello, I am unble to complete "Foolish Endeavors" in Borean Tundra. The quest involves a roleplay event in with Shadowstalker Getry, Varidus the Flenser, and High Overlord Saurfang. After the rp Saurfang kills the mobs and Varidus drops his invulnerability shield allowing players to attack. When Varidus reaches about 10% of his health he along with Saurfang and the questgiver Getry all disappear. The quest log does not record him as dead and I am unable to turn in the quest to Garrosh because it remains incomplete. I have abandoned and restarted the quest, ticketed and talked to a GM who told me to report the issue here.

**Comment by fvicaria** [comment]
Works. Search before posting.
