### ISSUE TITLE
[Boss] Razorgore - BWL

### ISSUE THREAD

**Issue by Zunrin** [WoWManiaUK/Redemption#2293]
Razorgore is the first boss of BWL.
During the encounter, you need to mind control Razorgore with an orb to destroy the eggs, while waves of adds spawn.

There seemed to be an issue with Razorgore's behaviour though:
- If there were adds up, Razorgore would randomly start walking towards the adds without the person controlling him being able to do anything at all.
- If no adds were up, the fight would reset randomly, respawning all the eggs.

So it seems like even when under mind control, Razorgore tries to attack enemies, and if no enemies are up, he would simply reset. So to do the encounter, we needed a GM to help tanking the mobs, since we had to keep them alive to avoid the fight resetting (we had no trouble killing them, but keeping 40 mobs alive hitting a ret paladin hurts).

Also phase two (where adds stop spawning, and you can kill the boss safely), started before we finished destroying all the eggs (only about half the eggs were destroyed)

**Comment by fvicaria** [comment]
No more work will be done here.
