### ISSUE TITLE
[Quest] Torek's Assault

### ISSUE THREAD

**Issue by cathyr1** [WoWManiaUK/Redemption#2294]
Hello. I have problems with escort quest in Ashenvale http://www.wow-mania.com/armory/?quest=6544. The NPC sometimes don´t even offers quest, sometimes can´t move when I take quest so I have to respawn him by killing by alliance char. And when I finally completed the escort, it is´t marked as completed, you can see on the screenshot.
![obrazek](https://user-images.githubusercontent.com/30184491/36645586-69bb79ba-1a6b-11e8-89f9-5569c9031eb0.png)

I have game client, version 2,2,7 and starting game only via launcher.

**Comment by squalllh1989** [comment]
Not sure what happen to the quest when you did it, but i find it work flawlessly in dev, so maybe a temporary bad state of npc that make the quest buggy, should be good at next server restart

![wowscrnshot_022618_112113](https://user-images.githubusercontent.com/27235989/36653401-8073fb60-1ae7-11e8-8e78-16a81be4246c.jpg)
![wowscrnshot_022618_112223](https://user-images.githubusercontent.com/27235989/36653403-825c5454-1ae7-11e8-975c-0ea894692d50.jpg)
