### ISSUE TITLE
[Warlock] Issue with minion controls

### ISSUE THREAD

**Issue by NightSeekerr** [WoWManiaUK/Redemption#2295]
I have my minion (Voidwalker) summoned. I use "Eye of Kilrogg". I cancel the Eye. My minion control bar doesn't reappear. Pictures:

Picture 1: https://i.imgur.com/MFtb0y3.jpg    -   Everything is fine.
Picture 2: https://i.imgur.com/op6P16y.jpg    -   I use "Eye of Kilrogg"
Picture 3: https://i.imgur.com/CcZP8Pk.jpg    -   No minion controls

I use the Launcher.

**Comment by squalllh1989** [comment]
Confirmed, this happening when used Eye of Kilrogg while having any kind of minion, after cancel the spell or the spell run out of time and finish, the cast bar disapear, need to resummon to get pet control bar back.

**Comment by Keader** [comment]
Fixed.
Should be up to test in next reset.

**Comment by Keader** [comment]
I tested it and is working in dev.
@WhitephoenixTheBunny if you click in protrait, eye is despawned but cast still is active. If you move (or use ESC button), cast will be stopped and pet bar will appear.
I cant stop this cast, right now is better that we can have 💃
