### ISSUE TITLE
Talent: Leader of the pack//Talent: Rampage

### ISSUE THREAD

**Issue by wowmania-Kindly** [WoWManiaUK/Redemption#2296]
Hello again :)

I have noticed that the druid feral Talent "Leader of the pack" does not effectively overwrite the fury Warrior talent: Rampage
Since Leader of the pack has the atached talent Improved leader of the pack, it should be removing rampage and give all in the raid its benefits instead.
When i stood With a fury Warrior in Group, he had his rampage, i had my leader of the pack.
When i invited another player, he got leader of the pack initially, however when i shifted to tauren form and back to cat, he was stuck With rampage.
In both cases, all players should have leader of the pack and not rampage whenever i am in cat or bearform.

I hope i made an acceptable post, ty for Your effort on the server!
-Kindly

**Comment by Keader** [comment]
What is the pratical change?
Both buffs give exactly same crit value.

**Comment by wowmania-Kindly** [comment]
The change is that Leader of the pack is Connected to Improved leader of the pack. With 2 Points in that you get a selfhealing proc of 4% of Your total Health and 8% of Your Maximum mana, With an internal cooldown of 6seconds. this procs on any melee or ranged attack Critical hit

**Comment by Dranah** [comment]
Yep feral one has an extra effect which is a unique buff to the melee/ranged. It should overwrite rampage

**Comment by Keader** [comment]
Please someone remember me about this tomorrow
Janitor is sleeping already xD

**Comment by Keader** [comment]
Ok, fixed.
Leader of the pack will have priority now.

**Comment by Magabro** [comment]
Tested with Whitepheonix.  Leader of the pack buff overrode the warriors rampage buff when druid was in cat and bear forms.  Rampage buff returned only when druid was not shapeshifted.  Appears fixed.

**Comment by wowmania-Kindly** [comment]
Cooool, thanks alot guys, that was fast! :)
