### ISSUE TITLE
[Spell] Summon Felhunter issue

### ISSUE THREAD

**Issue by AliWings** [WoWManiaUK/Redemption#2297]
Hello,

I've been having an issue with Summon Felhunter http://www.wow-mania.com/armory/?spell=691 spell since yesterday, after the spellcast its over the Felhunter is not summoned and the soulstone just goes back into my bags. 
I contacted ingame GM and was advised to use wowmania launcher, which I always do, delete cache and then relog into the game, I followed those instructions and the issue persists. I opened a ticket again and was advised to report the issue here. I don't know if you need my character's name, but its "Alirion" lvl 80 Blood Elf Warlock.

I don't know if this helpful but here are a few images of whats happening:
https://imgur.com/a/rZehF

**Comment by squalllh1989** [comment]
I can summon the felhunter normally without having any trouble, maybe the problem is with only your characters, i suggest you contact wow mania supporter on skyper to get your situation check.

**Comment by Dranah** [comment]
I received the same result. This is a personal bug of your character.
