### ISSUE TITLE
Watts My Target...icecrown quest bugged

### ISSUE THREAD

**Issue by biff30** [WoWManiaUK/Redemption#2299]
there are two quests in icecrown involving a plane and a bombing run while defending yourself from gargoyles.  The two quests are:  Watts My Target and Leading the Charge.  Neither quest allows you to defend yourself from the flying gargoyles.  One is unable to 'hit' a gargoyle with the planes missiles.  Thus the gargoyles blow you out of the sky everytime.  I have attempted these quests many times over the past few weeks with the same results.

**Comment by TheManiax** [comment]
Please follow the procedure described below before creating a new issue:
[How to Properly Report an Issue](https://github.com/wow-mania/Redemption/wiki/How-to-Properly-Report-an-Issue)

This will help developers identify and fix the issue quicker. Incorrectly or unclear reports will simply be deleted.

**Comment by fvicaria** [comment]
As is.
