### ISSUE TITLE
[Quest] Valliant of Silvermoon 

### ISSUE THREAD

**Issue by moontouched** [WoWManiaUK/Redemption#2301]
Hello,
I seem to be having an issue with the Argent Tournament daily quests. After talking with a GM (Psygoa), he/she told me to create an issue here.

   1. Begin and end the questline for Aspirant (http://www.wow-mania.com/armory/?quest=13678);
   2. Get the quest "A Valiant of Orgrimmar" (http://www.wow-mania.com/armory/?quest=13691);
   3. Complete the quest up to "The Valiant's Challenge", getting the "Champion of Orgrimmar" title (which i did not get);
   4. Take "A Champion Rises" (http://www.wow-mania.com/armory/?quest=13736);
   5. Deliver to Justicar Mariel Trueheart (http://www.wow-mania.com/armory/?npc=33817) and get the Argent Squire companion
    At this point, apart from being able to do the daily quests, as champion, with Eadric the Pure (http://www.wow-mania.com/armory/?npc=33759), the player can now choose another city and do the quests to become a champion of that city.
    As soon as the player delivers the quest at this point, ONLY the Silvermoon city's quest giver offers  "The Valiant of Silvermoon";
    After completing the same steps for Silvermoon, as described for Orgrimmar, no other quests are available. The player cannot start the quests (the NPCs does not offer them for some reason): 
"Valiant of Sen'jin" http://www.wow-mania.com/armory/?quest=13708
"Valiant of Thunder Bluff" http://www.wow-mania.com/armory/?quest=13709
"Valiant of Undercity" http://www.wow-mania.com/armory/?quest=13710
 
Server: Redemption
Using wow-mania client: yes
Using last version: yes
Character: Moontouched
Race: Goblin

**Comment by fvicaria** [comment]
I am pretty sure they work. I will check if there is any race issue.
