### ISSUE TITLE
RS 25n Loot Bug

### ISSUE THREAD

**Issue by Consumer23** [WoWManiaUK/Redemption#2302]
Sunday 25.02, We were doing 25nRS what happend
is we killed the boss and i forgot do to ML and told everyone to pass but
the trinket ''Charred Twilight Scale'' droped and i had the trincket and 
it buged and nobody can take it here are the link to prove it 
http://prikachi.com/images.php?images/713/9273713j.jpg
http://prikachi.com/images.php?images/844/9275844m.jpg
http://prikachi.com/images.php?images/845/9275845D.jpg
Dopeelf is the winner of the trink

**Comment by fvicaria** [comment]
Please follow the procedure described below before creating a new issue:
[How to Properly Report an Issue](https://github.com/wow-mania/Redemption/wiki/How-to-Properly-Report-an-Issue)

This will help developers identify and fix the issue quicker. Incorrectly or unclear reports will simply be deleted.
