### ISSUE TITLE
The Black Knight's Orders quest

### ISSUE THREAD

**Issue by Shr8awy** [WoWManiaUK/Redemption#2304]
im facing problem in The Black Knight's Orders quest that i have collected (1. Stolen tournament invitation, 2. Black Knight's order) But Black Knight's Gryphon taken is not visible for me and i cant collect it

**Comment by TheManiax** [comment]
Please follow the procedure described below before creating a new issue:
[How to Properly Report an Issue](https://github.com/wow-mania/Redemption/wiki/How-to-Properly-Report-an-Issue)

This will help developers identify and fix the issue quicker. Incorrectly or unclear reports will simply be deleted.
