### ISSUE TITLE
[Quest] Get Kraken! (Argent Tournament)

### ISSUE THREAD

**Issue by Unstoppablee** [WoWManiaUK/Redemption#2305]
In this quest you need to kill 3 x Kvaldir Deepcaller and to throw 6 spears on Kraken.

You need to target Kraken and use quest item (spear), but when you do that you just receive message "Invalid target"

Please check what is happening here, it's been like this last 3 days.
Thanks.
![wowscrnshot_030118_014417](https://user-images.githubusercontent.com/26930686/36821235-2e48987a-1cf2-11e8-9045-f6ce8ff08054.jpg)

**Comment by GMWeeble** [comment]
Let another tester confirm the issue.

**Comment by TheManiax** [comment]
http://www.wowhead.com/quest=14108/get-kraken

**Comment by fvicaria** [comment]
Works.

**Comment by fvicaria** [comment]
![image](https://user-images.githubusercontent.com/9414661/36834384-a8c0a83a-1d2a-11e8-9665-176f3e8fa3ee.png)


![image](https://user-images.githubusercontent.com/9414661/36834352-91af0bbe-1d2a-11e8-8664-20fc351f02a1.png)

**Comment by TheManiax** [comment]
Give error: Invalid target on Redemption.

**Comment by Unstoppablee** [comment]
4 days of testing this on Red. :P 
I'm curious how no one else complained about it.

**Comment by fvicaria** [comment]
Did you see the images I posted? It works.

**Comment by Unstoppablee** [comment]
I don't know what to say. I completed this so many times before. Last 4 days I'm unable to do it, due problem I posted here. @TheManiax have same problem as I do. 

Thanks.

**Comment by fvicaria** [comment]
Keep trying on the next boat etc.
It usually takes 2 or 3 rounds to complete it.
