### ISSUE TITLE
[Quest] Teron Gorefiend - Lore and Legend

### ISSUE THREAD

**Issue by larian** [WoWManiaUK/Redemption#2306]
the quest makes u go to altar of shadows and talk to a ancient orc spirit.how ever there is no orc to be seen.and yes i am wearing the spectracles provided for the quest.also i try'd to take em off and ecuip them again wich doesn't help.abandoning quest and retake it didn't help either
![lore and legend](https://user-images.githubusercontent.com/34296326/36821723-b60e4208-1cf4-11e8-8cec-6898ecd39f6a.jpg)

**Comment by TheManiax** [comment]
http://www.wowhead.com/quest=10644/teron-gorefiend-lore-and-legend

**Comment by fvicaria** [comment]
Works
