### ISSUE TITLE
[Quest] Collection of Goods

### ISSUE THREAD

**Issue by khastehh** [WoWManiaUK/Redemption#2307]
when you get to the stratholme you can obtain all the items except the holy water that you can see the box but you cant retrieve it there appears no wheelwork icon on the item . 

Khaste.

**Comment by TheManiax** [comment]
http://www.wowhead.com/quest=7642/collection-of-goods

**Comment by khastehh** [comment]
still having the problem

**Comment by fvicaria** [comment]
Pretty sure it works as it should. We will check in the PTR.

**Comment by TheManiax** [comment]
The quest works fine.
The crates that are sparkling are not the one you should try to open.
The correct crates to look for, look like the Image in the bottom of this post.
They have a red cross on them and there are only 3 of them in Stratholme.
![image](https://user-images.githubusercontent.com/14857593/36852070-1ae8ae6c-1d80-11e8-9213-9f7356935f52.png)
![image](https://user-images.githubusercontent.com/14857593/36852048-0ead808c-1d80-11e8-8a78-bc7ce1d5c230.png)

**Comment by Rushor** [comment]
fixed https://gyazo.com/d23c79f937074b6181e4b10cf3dcd1bb
