### ISSUE TITLE
[Quest] It Rolls Downhill

### ISSUE THREAD

**Issue by ghost** [WoWManiaUK/Redemption#2309]
Night Elf Level 75.

Latest client, cache cleared, have appropriate quest buff (Ensorcelled Choker/Scourge Disguise)

Begin questline with [[Unliving Choker](http://www.wowhead.com/item=38660/unliving-choker)] and progress to part 6/9 [[So Far, So Bad](http://www.wowhead.com/quest=12669/so-far-so-bad)], get quest [It Rolls Downhill](http://www.wowhead.com/quest=12673/it-rolls-downhill) from [Overlord Drakuru](http://www.wowhead.com/npc=28503/overlord-drakuru).

After '[taming](http://www.wowhead.com/item=39157/scepter-of-suggestion)' a [Blight Geist](http://www.wowhead.com/npc=28750/blight-geist), you are meant to be able to use it's only ability "Harvest Blight Crystal" to obtain [Harvested Blight Crystal](http://www.wowhead.com/item=39159/harvested-blight-crystal), however the Blight Geist does nothing when you click it.

Additionally, after 1 minute (which is meant to be the duration of the Geist being under your control) it continues to follow you, but you lose the pet bar, however you can recast [Scepter of Suggestion] on it again to bring the pet bar back, proper behaviour should be the Blight Geist going on it's way after 1 minute.

![wowscrnshot_030318_025806](https://user-images.githubusercontent.com/36994865/36908229-c5b8a1da-1e8e-11e8-9634-a754094a406c.jpg)
![wowscrnshot_030318_025902](https://user-images.githubusercontent.com/36994865/36908255-d7f92f5e-1e8e-11e8-9eaa-2d11e1d87750.jpg)

Note that completion of [It Rolls Downhill] is a requirement of the parent quest [So Far, So Bad], so this halts the progression of the whole questline.

*EDIT* After removing the Scourge Disguise, and even abandoning the quest. Blight Geists that you tried to 'tame' still follow you as hostiles but do not attack.
![wowscrnshot_030318_032007](https://user-images.githubusercontent.com/36994865/36909320-cb8b15c2-1e91-11e8-9973-b4cb551dc032.jpg)

**Comment by fvicaria** [comment]
Works

**Comment by Echinaceax** [comment]
### This still has issues 

Players have to stand on the bridge and chose the [Blight Geist](http://www.wowhead.com/npc=28750/blight-geist), nearest one on the crystals coz the npcs dont have correct pathing to each crystal in their range

**Comment by fvicaria4drest** [comment]
Pretty sure this works. It's tricky but it works. Please re-try.

**Comment by Echinaceax** [comment]
> Pretty sure this works. It's tricky but it works. Please re-try.

I did check it out and video'd it to 😄 

Blight Geist path goes to where there is no crystal (thats when it works)
https://i.gyazo.com/1d3a08ac28c46749b5738592bf931b6e.mp4

This does work with a workaround, but not fixed

**Comment by mfranca0009** [comment]
All set 👍

**Comment by Echinaceax** [comment]
Confirmed fixed in PTR 

https://i.gyazo.com/d11213a6f175be366a4a59fb857d93e7.mp4
