### ISSUE TITLE
[Quest] Fervor of the Frostborn

### ISSUE THREAD

**Issue by GMLucetta** [WoWManiaUK/Redemption#231]
http://www.wow-mania.com/armory/?quest=12874

Players are to talk to http://www.wow-mania.com/armory/?npc=29732 in order to have him transport them elsewhere. He gives the dialogue option but clicking on it does nothing.

**Comment by BleakSenpai** [comment]
The quest is bugged again. Please check.

**Comment by BleakSenpai** [comment]
The NPC http://www.wow-mania.com/armory/?npc=29732 has an option to click, when clicked, the player will automatically mount a White Bird, and the bird will fly the player over to the destination where the quest can be completed.
Unfortunately, the "Option" offered by the NPC when clicked does nothing, thus the player can't get the mount to fly over.
![fjorlin](https://cloud.githubusercontent.com/assets/24768369/26214102/e2551256-3c03-11e7-8b27-9fd9382c9acd.jpg)
