### ISSUE TITLE
[Boss] King Ymiron - Utgarde Pinnacle - Bane

### ISSUE THREAD

**Issue by Zunrin** [WoWManiaUK/Redemption#2312]
- How it should work:
Bane should not be interruptable, instead ppl should dispel / steal the buff from him, or just wait it out.

- How it works at the moment:
Bane is interruptable.

Bane:
http://www.wowhead.com/spell=48294/bane

**Comment by Keader** [comment]
Fixed :)

**Comment by Zunrin** [comment]
I did a bit of reading on Ymiron, and the adds he spawns (avenging spirits) should apply a stacking debuff when they melee a player:
http://www.wowhead.com/npc=27386/avenging-spirit

**Comment by Keader** [comment]
i will look tomorrow morning.

**Comment by Keader** [comment]
Fixed Zunrin, up to test in next restar :)
