### ISSUE TITLE
[Spell] Fel intelligence/Prayer of Spirit/Divine spirit/Arcane intellect/Arcane Brilliance

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#2314]
Hello,
I'd like to report these spells for their effects not stacking the way is intended.
http://www.wow-mania.com/armory/?spell=57567
http://www.wow-mania.com/armory/?spell=48074
http://www.wow-mania.com/armory/?spell=48073
http://www.wow-mania.com/armory/?spell=42995
http://www.wow-mania.com/armory/?spell=43002

How it works right now:

Current "stacking priority" is Divine Spirit/Prayer of Spirit > Fel Intelligence > Arcane intellect/Arcane brilliance.
This is wrong because 
- Priest Spirit buff on the raid prevents Fel intelligence from being applied at all, making you unable to receive the intellect bonus if you don't have a mage present (mostly a problem in 10mans).
- Fel intelligence active prevents mages from applying Arcane intellect/Brilliance, which would give a stronger intellect buff than fel intelligence does

How it should work: 

These buffs should be able to co-exist on the raid members with only the strongest bonuses present being applied. (similar problem to Misery / Imp Faerie fire on debuffs, they have both effects that shouldn't add, and effects that should)
- The Fel intelligence buff's intellect portion should still be given to the raid when a stronger priest buff is present, as it is a different effect. (only the SPIRIT portion should be overwritten)
- Arcane intellect/Arcane brilliance should be able to overwrite the INTELLECT portion of the fel intelligence buff and raid members should still receive spirit from it

**Comment by Keader** [comment]
holy shit.
Is possible fix, but i will need sometime to do it.
Because: Mechanic that take care of it is fucked. And i cant find why. So i need make little spellscripts to fix it for each "bigs" buffs

**Comment by Dranah** [comment]
you wanted "fun" spell bugs, i gave you one :D

**Comment by Keader** [comment]
hahaha right

**Comment by Zunrin** [comment]
I believe the misery/imp ff was fixed a couple months ago, so checking how that was fixed might inspire you :)

**Comment by Dranah** [comment]
It was only a few weeks ago and it was more like a workaround... nobody could actually fix their behavior but we made it effectively "look like" it works.
Even now, if a priest already has misery on target, and a druid applies IFF, they still have 6% hit chance for a few seconds until the priest reapplies misery, because val put into misery application script that it erases its 3% hit when it checks that FF is already on target, but it only checks when the priest applies it. But in a real raid situation, this won't get you fewer misses because of how frequently priests reapply the buff.

**Comment by Keader** [comment]
You are correct, but has no way to fix it in current state of core.
Is missing a mechanic that dont allow 2 spells with same efffect stack, and has no way to fix this issue without it.
I lost 8 hours trying alot of ways fix it, without success.
