### ISSUE TITLE
[Quest] Klaven's Tower

### ISSUE THREAD

**Issue by GMWeeble** [WoWManiaUK/Redemption#2315]
Pickpocketing [Malformed Defias Drone](http://wow-mania.com/armory/?npc=7051) works fine and you get [Defias Tower Key](http://wow-mania.com/armory/?item=7923).

Issue is opening the box. Trying to open the box does not work. It will say it is locked.

**Comment by fvicaria** [comment]
You need to lockpick the box not use the key.
Please do homework before logging issues.
