### ISSUE TITLE
[Spell] Improved leader of the pack internal cooldown

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#2317]
Hello,
I'd like to report feral druids' improved leader of the pack http://www.wow-mania.com/armory/?spell=34300) internal cooldown being shared by raid members instead of being a personal cooldown.

How it should work:
The healing effect should have a separate 6second cooldown on each target affected by the buff, preventing them to receive the heal again for 6sec after landing a critical.

How it works right now:
The healing effect has a global, raidwide 6sec cooldown, meaning when one melee benefits from the heal, NONE of the targets in the raid can receive a heal for the next 6seconds.

This makes the healing output of the buff reduced to barely 10% of the intended values when in a raid with 10 melee/hunter units that are sharing the effect of the spell. Not to mention that every proc is stolen by the rogues, as they have the fastest attacks.

**Comment by Dranah** [comment]
No change.

**Comment by Keader** [comment]
I put some comments inside of spell script, i will wait janitor build to test it

**Comment by Keader** [comment]
Yeah i forgot to remove 1 thing in DB
Now is working, tested today morning.

**Comment by Dranah** [comment]
Yep works fine now!
