### ISSUE TITLE
[Boss] Sartharion - Obsidian Sanctum

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#2318]
Hello,
I'm moving problems here from the other thread that belong to Sartharion http://www.wow-mania.com/armory/?npc=28860 fight, not Shadron specifically.

1. Wipe/reset on Sartharion encounter doesn't despawn lava blazes and twilight whelps
2. /spell=57557 
"Pyrobuffet" is missing from the fight, this is the mechanism that should prevent the raid sitting outside Sarth's platform to dodge the lava waves.
How it should work: Whenever a player leaves Sartharion's platform during the encounter, this nasty debuff is stacked on them every 8(?) seconds or so, damaging and killing them eventually.

**Comment by Keader** [comment]
Ready to test

**Comment by Dranah** [comment]
Update:
- Lava Blazes and Twilight whelps now properly despawn (fixed)

Remaining problems:
- The 3 drakes don't reset properly after attempt on hardmode. Sometimes they retain the 25% health buff (will of sartharion), sometimes Vesperon doesn't return to his spot at all, stays on the platform with Sarth until engaged and wiped again.
- Pyrobuffet is now cast when you are on the outer part of the dungeon, but it doesn't cover the whole area that it should, such as the small islands leading towards Sartharion's isle. 
It should be cast everywhere where the Fire Walls cannot reach. (same range as where Sartharion reset if the person with aggro tries to drag him outside)

**Comment by Keader** [comment]
Reset issue fixed.
Pyrobuffet issue is in boundary system, is not sartharion issue, has nothing that i can do about it.
