### ISSUE TITLE
[Boss] The Tribunal of Ages - Halls of Stone

### ISSUE THREAD

**Issue by Bartok14** [WoWManiaUK/Redemption#2319]
During this encounter there appears to be an invisible mob that goes around the room and starts attacking the group. It seems by the chat bubble that it is the NPC (the computer) that is in a conversation with Bronzebeard. This isn't how I remember the fight from retail back in the day. The main problem is that you can get stuck in combat for the rest of the instance and you can't attack the mob in any way that I know of. 
![image](https://user-images.githubusercontent.com/32959403/37016763-dd4a7126-20db-11e8-8eac-612c3f434cbf.png)

**Comment by fvicaria** [comment]
That is as-is. It is the computer defense.
