### ISSUE TITLE
[Spell/Proc] Dislodged Foreign Object

### ISSUE THREAD

**Issue by xclaw800** [WoWManiaUK/Redemption#2320]
The item is supposed to proc on dots such as affliction spells like curses, corruption, unstable affliction etc. it is currently only proccing on direct spells like shadowbolt, incinerate etc. This is making the items effectiveness worse with a longer ramp up time.

**Comment by xclaw800** [comment]
It seems to be related to a trinity core bug: https://github.com/TrinityCore/TrinityCore/issues/6297

**Comment by Zunrin** [comment]
Just to be sure people understand the issue correctly, the item should be able to proc when CASTING the dot. Not actually when the dot ticks:
http://www.wowhead.com/item=50353/dislodged-foreign-object#comments for the reference.
(at the moment it doesn't proc at all when using curses, corruption, etc...)

**Comment by Magabro** [comment]
Corruption casts are not proccing DFO. 
Corruption ticks are not proccing DFO
Corruption casts are not proccing Charred Twilight Scale.  
Corruption ticks ARE proccing CTS

DFO reads "your harmful spells"
http://www.wow-mania.com/armory/?item=50353
CTS reads "your damaging spells"
http://www.wow-mania.com/armory/?item=54588

**Comment by Magabro** [comment]
Corruption DoT ticks are now proccing DFO.  The initial cast of Corruption is not proccing DFO.
Believe this is backwards and the ticks should not proc the trinkets but the initial casts should.

**Comment by Keader** [comment]
No, Corruption is a dot, this is the only proc flag that allow dots proc items.
Current spell proc system dont allow me fix more.

**Comment by Zunrin** [comment]
If it's not possible to make it proc only on dot casts and not on dot ticks, then it's probably closer to blizzlike if it doesn't proc at all on dots imo. (especially for dots you don't even need to cast to refresh them)

**Comment by Keader** [comment]
this part is not possible...
or not proc with dots (cast or dot damage) or proc with dots damage (like charred).

**Comment by Keader** [comment]
Well, i'm lefting proccing with tick dot.
Looks more fair, since our proc system dont support  the proper fix.
