### ISSUE TITLE
Boss: Mimiron 10 Hardmode

### ISSUE THREAD

**Issue by wowmania-Kindly** [WoWManiaUK/Redemption#2321]
Hey again! :)
When we went through phase transition between phase 1 and 2, suddenly all fire was exstinguished and then VX-001 never spawned.
When we tried to reset the raid nothing happened. 
After some time the selfdestruct mechanism started casting and kept on casting for much longer than normal.
When we again tried to reset the encounter the pillar that appears in phase transitions was stuck in the middle, the vehicle was not present in the room and the button for hardmode was not usable.
i hope my post is acceptable, and ty for Your work on the server! 
-Kindly

**Comment by fvicaria** [comment]
I will take a look tomorrow.
