### ISSUE TITLE
[Boss] Gluth zombies

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#2322]
Hello,
I'd like to report Gluth's http://www.wow-mania.com/armory/?npc=15932 zombies http://www.wow-mania.com/armory/?npc=16360 for not engaging properly when being outranged.
The problem is they have the regular 30yard~ aggro range, they don't aggro to the raid or to Gluth if you stand further than that from the point where they spawn (where gluth originally stands).
So if you pull Gluth to the door, the zombies will just stand still where they spawn and don't do anything.

**Comment by Keader** [comment]
Test if is working.
If not, please let me know a repro steps.

**Comment by Dranah** [comment]
Zombies now aggro no matter how far I stand, so it looks correct.
