### ISSUE TITLE
[Core] Auction House - Cannot list items with charges

### ISSUE THREAD

**Issue by Wolch** [WoWManiaUK/Redemption#2325]
http://www.wowhead.com/item=20831/heavy-golden-necklace-of-battle
For some reason can't post this item on AH, get an error: "You cannot auction an item with used charges".
But all the charges are there, none was used.
Tried to clear cache and disable Auctioneer addon, nothing helped. GM also could not help me with this problem.
![wowscrnshot_030818_142310](https://user-images.githubusercontent.com/28511078/37149537-6c5fe440-22df-11e8-8fa6-a0407e98fbe7.jpg)
![wowscrnshot_030818_142344](https://user-images.githubusercontent.com/28511078/37149538-6c81850a-22df-11e8-9bdf-6fea16a165bb.jpg)

**Comment by fvicaria** [comment]
Create a new one and check if you have the same issue.

**Comment by fvicaria** [comment]
This is a well-known retail issue. I will try to sort it for tomorrow.
