### ISSUE TITLE
[Boss] Lady Deathwhisper

### ISSUE THREAD

**Issue by squalllh1989** [WoWManiaUK/Redemption#2326]
- How it should work: [Lady Deathwhisper](http://www.wow-mania.com/armory/?npc=36855) 's [Dominate Mind](http://www.wowhead.com/spell=71289/dominate-mind) should NOT be casted on the current tank that is having her aggro.
- How it is working right now: [Lady Deathwhisper](http://www.wow-mania.com/armory/?npc=36855) can cast [Dominate Mind](http://www.wowhead.com/spell=71289/dominate-mind) on the tank that is holding her aggro, completely wipe out his aggro on her after the spell ended. This is very nasty, as in heroic mode she can't be taunted, the case is doomed when 1 tank has 5 stack of [Touch of Insignificance](http://www.wowhead.com/spell=71204/touch-of-insignificance) and can't gain any more aggro from her, then the 2nd tank took over and be mind controled when tanking her.
Some people say that maybe for a moment the tank's aggro drop and lady mind control him, i'm sure that it's not the case as for several time i was watching the aggro table, which the nearest aggro next to the tank is at 80%, then lady cast dominate mind on the tank and start going rampage on the dps, if the other tank can't take over (maybe because he can't gain enough threat in time, or he just got 5 stack of [Touch of Insignificance](http://www.wowhead.com/spell=71204/touch-of-insignificance) already) then it's a doom case, as after the mind control end, the tank lost all of his aggro.

**Comment by fvicaria** [comment]
It's unlikely that any more work will be done here.

**Comment by fvicaria** [comment]
Fixed. It was a one-line fix.
