### ISSUE TITLE
[Spell] Deep Freeze

### ISSUE THREAD

**Issue by KyptAMaN** [WoWManiaUK/Redemption#2327]
So this got real.. i know u rly dont care about pvp but here we go..

So now, theres a bug with frost mages with the spell  [Deep Freeze] .. soooo everyitme they get the procc of deep freeze and they cast it on for example bladestorm, icebound fortitude, wich are abilities that make u immune to deep freeze , u will get damage from 5k till 11k (at least 11k was the highest i got LOL) 

Ok so idk if u will fix it or na, but if u dont beleive me, test it urself (wich u should do, since its ur job to prevent these types of bugs)

Theres a screen shot so u can check the combat log dmg ;)

It is a really retarded bug and ppl will start to abuse it if u dont act fast.
![image](https://user-images.githubusercontent.com/25290746/37184588-f5ee3e2e-2333-11e8-8ced-1164ff3cc04d.png)

**Comment by TheManiax** [comment]
I do care a lot for PvP bugs and I will be happy to check if you report them.
But that doesn't mean you can report bugs like that.
You have to follow the procedures: [How to Properly Report an Issue](https://github.com/wow-mania/Redemption/wiki/How-to-Properly-Report-an-Issue).

-----------------------------
[![image](https://user-images.githubusercontent.com/14857593/37191698-856d30ea-2376-11e8-8439-78515b48618c.png)](http://wowwiki.wikia.com/wiki/Deep_Freeze)

**Comment by Keader** [comment]
Issue is real.
Deep Freeze damage should NEVER be applied on players.
Like you linked Nima, should be applied to targets permanently immune to stuns, players only can be temporary immune.
This damage is applied only to bosses and immune creatures.

**Comment by Dranah** [comment]
This now works as intended, a bladestorming warrior will not take damage, bosses do.

**Comment by KyptAMaN** [comment]
That works vs bosses, not players, are u kidding me? deep freeze was never a dmg thing at pvp LOL. 
Please know ur facts .

**Comment by Keader** [comment]
Btw Kryp, not need be so rude.

**Comment by Dranah** [comment]
I have no idea what this guy's issue is, he clearly didn't understand my post. We acknowledged that it should not damage players and fixed it. However as a tester I also need to make sure that the fix did not break other parts of the spell and therefore test the boss portion too. That part is having issues.

**Comment by TenKdoToLami** [comment]
So the Deep Freeze is inherently still bugged towards bosses? With no intention of fixing? Had some attempts on pveing as forst mage and it does not crit accordingly to the Shatter bonus. Can provide data if anybody reads this

**Comment by Echinaceax** [comment]
> So the Deep Freeze is inherently still bugged towards bosses? With no intention of fixing? Had some attempts on pveing as forst mage and it does not crit accordingly to the Shatter bonus. Can provide data if anybody reads this

We read all reports old and new @TenKdoToLami 

This is an old report from 2018, we have the same developers and the same core, so im guessing that if the issue couldnt be fixed for Bosses back then, then it still can't now.

This report was for this spell in PvP and that part was fixed.

I suggest @TenKdoToLami you make a new report for the PvE part of this please, and we will take a look, thanks
