### ISSUE TITLE
[Boss] Ignis the Furnace Master - Slag Pot

### ISSUE THREAD

**Issue by Zunrin** [WoWManiaUK/Redemption#2328]
**What should happen:**
During the encounter, he periodically casts Slag Pot on a random member, teleporting him to his slag pot, making the target unable to hit the boss and dealing damage. If the target survives, then he gets a haste buff.

**What's happening:**
Slag Pot does not teleport the player, and the player is able to continue casting normally. The damage part and the buff you get surviving the spell work.

Links:
http://www.wowhead.com/npc=33118/ignis-the-furnace-master
http://www.wowhead.com/spell=62717/slag-pot

**Comment by fvicaria** [comment]
Please retest on dev
