### ISSUE TITLE
[Boss]Mimiron HM - Flame cap

### ISSUE THREAD

**Issue by Zunrin** [WoWManiaUK/Redemption#2329]
**What should happen:**
Every 30 seconds, on hard mode, new flame "spawners" appear close to random members in the raid. Every second, these flames should move towards the closest player and leave a flame patch. Some of Mimiron's abilities will remove the flame patches and spawners. When above a certain number of patches on the ground is reached, no new spawners should appear (but the spreading should continue). (source: http://www.wowhead.com/achievement=3189/firefighter-25-player#comments and https://www.mmo-champion.com/threads/674455-Mimiron-HM-10-Need-Advice) The only numbers I could find for this cap was 60 in a MMOC comment, and 50 in Sunwell's core.

**What's happening:**
New "spawners" continue appearing every 30s, even if the room is litterally covered with fire.
![wowscrnshot_030918_174913](https://user-images.githubusercontent.com/23452669/37219355-6703de0e-23c3-11e8-85c0-f477042f8895.jpg)
On this screenshot, the new "spawner" at the bottom spawned about two seconds earlier. It's hard to tell exactly how many fire patches are on the ground since they all overlap but I'd guess over 200.

**Comment by Zunrin** [comment]
According to Tankspot, the fire's wont even spread if you reach fire cap:
https://www.youtube.com/watch?v=Jee971qfSMQ @4:20

**Comment by Zunrin** [comment]
Just checked Ensidia's world firist video, and it looks like when there's a lot of fire on the floor (for instance from the middle of p3 until the first frost bomb removes patches at the start of p4), dire won't even spread.

**Comment by Dranah** [comment]
I'd like to add that mimiron's flames currently ignore fire resistance values. They cannot be resisted nor fully nor partially.

**Comment by Keader** [comment]
Spell has attribute: SPELL_ATTR4_IGNORE_RESISTANCES
That's why can be resisted.
Btw up to test

**Comment by Zunrin** [comment]
The flame cap seems to be working great :+1: 

Just one final issue, when you defeat mimiron, you stay stuck in combat. I feel it might be due to the "computer" mob (probably the same kind of issue as #2319, except the computer doesnt actually hit you on mimiron but still follows you around)

**Comment by Keader** [comment]
not reported in original issue.

**Comment by Zunrin** [comment]
Yeah i know it's my bad, I only just noticed :/ can't tell for sure if it was an issue before (I used to wipe to reset the fight)
