### ISSUE TITLE
[Quest] Gnomish Engineering. 

### ISSUE THREAD

**Issue by Noahcoke** [WoWManiaUK/Redemption#2330]
Hello, i was told to open a new issue about this.

i wanted to go for the gnomish engineering specialization (http://www.wowhead.com/quest=29477/gnomish-engineering) and checked wowhead for the necessary questline. The mentioned npcs (also the ones of follow up quests) didnt provide any starting quest or other options to help receiving the specialization. 

Wowhead/Wowwiki are stating, that the starting quest should be obtainable by any engineering trainer there is. None of those i checked (Stormwind, Ironforge, Dalaran, Ratchet) had a quest for me though. 
After talking to a GM, he found out that i apparently already got that ability. Yet i couldnt learn any of the Plans that you need gnomish eng. for. 

I got that profession via MP, so i guess it might have something to do with that.

**Comment by fvicaria** [comment]
![image](https://user-images.githubusercontent.com/9414661/37244730-38f536d0-2485-11e8-857d-9df976a57860.png)

**Comment by Noahcoke** [comment]
But how am i supposed to obtaine it then?

**Comment by Noahcoke** [comment]
Hey,

The issue i am having is that i am stuck with the gnomish engineering spec but at the same time i cant "use" it.

The mentioned GM checked my ability database where it states that i have the spec and yet i cant use the corresponding items like Iceblade Arrows (http://de.wowhead.com/item=52021/eisklingenpfeil)

I hope this makes it clear what i meant.

**Comment by fvicaria** [comment]
Unless you give me the exact steps and explain why this is wrong I will keep closing it.

**Comment by GMWeeble** [comment]
Narain Soothfancy. Tanaris - Steamwheedle Port. There is a book. You can unlearn the spec for 150 gold.

**Comment by Noahcoke** [comment]
The book didnt have any option to use when clicking it.

**Comment by Noahcoke** [comment]
And if i could explain why its wrong i already would have added it.

**Comment by GMWeeble** [comment]
That is because you do not have the spell. 
You should be able to get the quest then. If not it is bugged.

**Comment by Noahcoke** [comment]
Apparently it is, since i cant take any quest nowhere.

**Comment by Noahcoke** [comment]
And i am pretty sure it has something to do with the MP way of getting the profession, since a friend of mine got the profession in the usual way and could do the gnomish quest.
