### ISSUE TITLE
[Quest] The Battle for Arathi Basin!

### ISSUE THREAD

**Issue by NightSeekerr** [WoWManiaUK/Redemption#2332]
The quest requires you to assault the farm, blacksmith, lumber mill and mine in Arathi Basin when they are controlled by the enemy. I've assaulted the blacksmith and farm while they are under Horde control a few times now and it doesn't count on the quest. It stays 0/1 Blacksmith Assaulted.

Link for the quest: http://www.wow-mania.com/armory/?quest=8105

I use the Launcher.

**Comment by fvicaria** [comment]
Quest requires you to assault all 4 in a single battle

![image](https://user-images.githubusercontent.com/9414661/37246218-29b4635e-249d-11e8-8253-fd6ee04dcce2.png)

**Comment by NightSeekerr** [comment]
You are wrong. It took me a while but here's the proof:

https://i.imgur.com/3ciWXtU.jpg - I assault the mine.
https://i.imgur.com/cz9ENSh.jpg - I assault the blacksmith.
https://i.imgur.com/iLIwzqe.jpg - I assault the lumber mill.
https://i.imgur.com/hy0oKDZ.jpg - I assault the farm.

I assaulted all 4 in a single Arathi Basin battle, while all were Horde controlled. 

Now will you re-open the issue or should I make a new one? :)
