### ISSUE TITLE
[Quest] Relic of the Earthen Ring

### ISSUE THREAD

**Issue by netyoda** [WoWManiaUK/Redemption#2333]
http://www.wowhead.com/quest=14111/relic-of-the-earthen-ring

I have all 4 totems in my bag, Gotura Fourwinds is showing as a yellow ? on the map, but greyed out of his head.

When I converse, the "continue" option on the quest is also greyed out, so I cannot complete the quest.

I have queried this with others shamans and they haven't had a problem with it.

![image](https://user-images.githubusercontent.com/3975474/37252490-4626d0fc-252a-11e8-8e1b-c36da760bb4e.png)

Account : netyoda
Toon : Tanta
CL35 Tauren Shaman

**Comment by fvicaria** [comment]
This is not a problem with the quest.
It's known issue with the core also present with the retail version at the time.
The client fails to track how many items you have if you get them before the quest itself.
Ask a GM to complete the quest for you, and reward if needed.
