### ISSUE TITLE
[QUEST] Unexpected Results

### ISSUE THREAD

**Issue by Pelzpeter** [WoWManiaUK/Redemption#2334]
I am submitting this after GM Psygoa asked me to. I have problems with the quest Unexpected Results.
http://www.wowhead.com/quest=8488/unexpected-results
You get this quest from Apprentice Mirveda and you have to defeat the attacking scourge units.
Killing Gharsul the Remorseless did not complete the quest and after abandoning it I am not able to try again. This is nearly the same problem that was mentioned by Katherwind. https://github.com/WoWManiaUK/Redemption/issues/1541

A week or two ago I did this quest with another character without a problem.

**Comment by fvicaria** [comment]
I have done this quest twice in sequence with 2 characters to test if NPC was having some issue.
All work ok. If you still can't complete it just drop it and get it again.
