### ISSUE TITLE
Squire David bug

### ISSUE THREAD

**Issue by Rakann** [WoWManiaUK/Redemption#2336]
Squire David at the Argent Tournament in Icecrown does not have the option to summon an opponent during "The valiant's challenge" quest.

http://www.wowhead.com/quest=13731/the-valiants-challenge
http://www.wowhead.com/npc=33447/squire-david

**Comment by fvicaria** [comment]
Please send quest link and npc link if applicable

Please follow the procedure described below before creating a new issue:
[How to Properly Report an Issue](https://github.com/wow-mania/Redemption/wiki/How-to-Properly-Report-an-Issue)

This will help developers identify and fix the issue quicker. Incorrectly or unclear reports will simply be deleted.

**Comment by fvicaria** [comment]
Can someone explain this better and reproduce it?

**Comment by fvicaria** [comment]
This is incorrect. Please do your homework before posting issues as it consumes the dev/testers time for nothing.

The NPC will only show the option if you have one of the following quests:
https://www.wowhead.com/quest=13679/the-aspirants-challenge (Alliance)
https://www.wowhead.com/quest=13680/the-aspirants-challenge (Horde)

**Comment by Rakann** [comment]
And I just linked  you the quest link.

http://www.wowhead.com/quest=13731/the-valiants-challenge

It's "VALIANT"S" and "ASPIRANT'S". They both are the same, only that the
Valiant's challenge is after you do a lot more dailies than the first one.
You should probably " consume the dev/testers time " in a better manner.
It's irrelevant now anyway since i changed factions and lost all progress

**Comment by fvicaria** [comment]
I checked and it works.
