### ISSUE TITLE
[Rogue] Cheat Death

### ISSUE THREAD

**Issue by BatuMania** [WoWManiaUK/Redemption#2338]
How it should work: When you get to the point of death, so an attack which would otherwise kill you WOULDN'T. It'll reduce you to 10% of your hp instead of lethality and all damage taken is reduced by 90% for 3 seconds.

How it works: Cheat death procs but doesn't do anything, the attack which would kill you just kills you and there's no damage reduction on proc.

http://www.wowhead.com/spell=31230/cheat-death#comments

This link's updated to current retail but the comments from previous patches + tooltip of the spell now is almost the same.

**Comment by Keader** [comment]
Up to test 💃

**Comment by Dranah** [comment]
The death prevention works now (absorbs full damage that would go below 10% health), but the 90% damage reduction afterwards does not. Which means you pretty much die in the next moment.

**Comment by Dranah** [comment]
Still nope.

**Comment by Dranah** [comment]
Good now.
