### ISSUE TITLE
[Boss] The Assembly of Iron - Ulduar

### ISSUE THREAD

**Issue by Zunrin** [WoWManiaUK/Redemption#2340]
**What should happen:**
When you kill one of the three bosses, the other two's hp resets to 100% and they gain an ability.

**Wht is currently happening:**
When we were killing the bosses in the order Stormcaller Brundir -> Runemaster Molgeim -> Steelbreaker, the last boss was reseting twice, immediately and after about 10s after Molgeim dies (but he gained his ability immediately). This means people will use their cooldowns for nothing, and you lose 10 second of dps (doing the bosses in this order makes the last phase a dps race)

http://www.wowhead.com/npc=32867/steelbreaker

**Comment by Keader** [comment]
Reproduce steps?

**Comment by Zunrin** [comment]
No clue what was causing it exactly, I thought it would just be doing the bosses in this order since it happened in both our tries, but I can't seem to reproduce it either... we must have been really unlucky on those two tries I guess.
Next time I'm in Ulduar, I'll try and see exactly when he resets his hp (if it happens) and what happened at that moment.

**Comment by Keader** [comment]
Basic rule: With no reproduce steps is impossible fix.
