### ISSUE TITLE
[Quests] Icecrown - Kibli Killohertz

### ISSUE THREAD

**Issue by Necko23** [WoWManiaUK/Redemption#2342]
Icecrown
Aldu'thar: The Desolation Gate
You can get 3 quests from NPC Kibli Killohertz: "Leading the Charge", "Watts my Target", "Static Shock Troops: the Bombardment". Your task is to kill given enemies with an airplane which you also mount by yourself once you speak to NPC Karen No. I am unable to finish these quests. My rockets literally go through Gargoyles. I've tried it a few times, didn't work. After that I closed the game, deleted cache once I've opened Launcher, that had no results. I abandoned all of the quests above, closed the game, deleted cache again, logged in, retook the quests but that did not work as well. I've contacted GM Psygoa, we weren't successful in fixing this. I cannot record the following event because my PC is not that strong. However if it'll help, I'll take tons of screenshots while I'm trying to finish these quests.
P.S. I also tried doing quests 1 by 1, since they share some enemies that you have to kill, that did not work as well.

**Comment by fvicaria** [comment]
Target them then shoot.
![image](https://user-images.githubusercontent.com/9414661/37553128-753d29b6-29b9-11e8-9777-b25f3df04c38.png)
