### ISSUE TITLE
Heated Battle

### ISSUE THREAD

**Issue by Phillanthropy** [WoWManiaUK/Redemption#2343]
http://www.wow-mania.com/armory/?quest=12448 Players are supposed to kill http://www.wow-mania.com/armory/?npc=27685 http://www.wow-mania.com/armory/?npc=27686 http://www.wow-mania.com/armory/?npc=27531
http://www.wow-mania.com/armory/?npc=27751 is supposed to help the player, but his guards don't spawn and help the player as intended
This issue was previously resolved but it seems to have occurred again.

**Comment by fvicaria** [comment]
Just tested and the NPCs are assisting.
Quest works as it should.
![image](https://user-images.githubusercontent.com/9414661/37553332-084c9a08-29be-11e8-88d9-ba48306b0dce.png)
