### ISSUE TITLE
Halion - Losing Buffs when changing realm

### ISSUE THREAD

**Issue by Zunrin** [WoWManiaUK/Redemption#2344]
**How it should work:**
People should not lose any buffs when changing from physical to shadow realm or vice versa.

**How it's currently working:**
When changing realm, some buffs (like Focus Magic, Vigilance, Soulstone etc) get removed when switching phase (not 100% sure if this is happening when the buffed player switches phase, when the buffer switches, or when either switches)

(This might be happening in other instances where phasing happens... the ones I can think of where the players are in different phases are Old Kingdom's last boss, Valithria's encounter in ICC, the first boss in Sunwell Plateau, Obsidian Sanctum, Algalon in Ulduar)

**Comment by Zunrin** [comment]
http://wow-mania.com/armory/?spell=54646 Focus Magic
http://wow-mania.com/armory/?spell=50720 Vigilance
http://wow-mania.com/armory/?spell=20707 Soulstone

I'm probably missing some buffs that are also affected by this issue so if you know of any, do add them in a comment.

**Comment by Keader** [comment]
I realy think it's indeed

**Comment by Zunrin** [comment]
If you meant intended, answer is no.
https://www.warcraftmovies.com/movieview.php?id=163849 at 1:44 and 3:13, the mage keeps Focus Magic

**Comment by Keader** [comment]
Oh, i know what cause it.
And i dont think that we can fix it xD

**Comment by Midnaa** [comment]
It's because the buff origin has to exist in the same phase as the receiver, else you could soulstone a whole raid and get inside an instance without running a warlock...

**Comment by Keader** [comment]
It's same root cause of DOTs cant make damage if player die or relog.
This spells depends of caster in same phase and alive :/

**Comment by Dranah** [comment]
Isnt it possible to make the buffs depend on casting being in raid, rather than in same phase?
