### ISSUE TITLE
[Quest] "A visit to the doctor"

### ISSUE THREAD

**Issue by Tarmuyi** [WoWManiaUK/Redemption#2345]
After freeing Patches, doctor Sabnok appears. After killing him, the mob despawns without giving credit for the kill. I've confirmed this bug with a GM monitoring me, after doing it 3 times.

**Comment by fvicaria** [comment]
Quest works fine.
![image](https://user-images.githubusercontent.com/9414661/37565983-e5e95972-2aaa-11e8-80de-97ca8a9e1755.png)

Who was the GM? :P
