### ISSUE TITLE
[Spell] Invisibility

### ISSUE THREAD

**Issue by Zunrin** [WoWManiaUK/Redemption#2348]
**How it should work:**
When using Invisibility, mages should lose 10% threat per second while fading, and once completely invisible, they should be removed fromall threat lists, wiping their threat completely.

**How it currently works:**
Threat is not completely removed when turning completely invisible.

A short example: On Deathbringer Saurfang, when blood beasts spawn, ranged dps nuke them down, as a mage you often get aggro on them. So sometimes I use Invisibility to get away. Once completely invisible, I expect to have lost aggro so I remove the invisible buff, but I instantly regain aggro on the beast, and get one shot.

**Comment by Dranah** [comment]
Just leaving a note: 35009 is the spell ID responsible for the threat reduce ticks every 1second.

**Comment by Zunrin** [comment]
We are not being targetted, but there should be a threat wipe.

For reference:
https://www.youtube.com/watch?v=2yS_fC9ti9w @1:32
https://www.youtube.com/watch?v=j1FNb69vWQI @5:19

Still no threat wipe on dev.

**Comment by Dranah** [comment]
Threatwipe works now if invisibility is untalented.
Threatwipe does not work when talented into Prismatic Cloak 54354

**Comment by Keader** [comment]
@Dranah you are in discord? i need talk to you about it xD

**Comment by Keader** [comment]
New fix made, please test tomorrow when janitor build it xD
