### ISSUE TITLE
[Spell] Mirror Image

### ISSUE THREAD

**Issue by Zunrin** [WoWManiaUK/Redemption#2349]
**How it should work:**
When using mirror image, your threat should be "hidden" for 30s. Once the 30s are over, you should get all the threat back from before, plus the additionnal threat you got during the duration.

**How it currently works:**
When you cast mirror image, your threat is currectly hidden. However once the 30 seconds are over, rather than getting all your aggro back, the threat is simply wiped.

Only fix this if you successfully fix Invisibility, or mages may have great issues with threat. 

Link:
http://www.wowhead.com/spell=55342/mirror-image

**Comment by Dranah** [comment]
A little correction >> the hidden threat works for the 30sec duration, however there is an unintended threatwipe at the end, when it expires. Instead of regaining all your threat that gathered in silence, it is wiped to zero.

@Keader move the threatwipe effect from mirror image ability to invisibility and it should be all good :D

**Comment by Zunrin** [comment]
Threat is still being wiped when the effect ends.

**Comment by Keader** [comment]
Any proof that it should be temporary?

**Comment by Zunrin** [comment]
It isn't working 100% as intended.

If you ever wipe your threat while mirror image is active (either with invisibility, or because the boss wipes his threat eg lady deathwhisper on transition or when she mind controls you) then when mirror image ends you will simply have 4 million threat.
The same issue is present with Fade. (http://www.wowhead.com/spell=586/fade)

**Comment by Keader** [comment]
Nothing that i can do about it anymore.

**Comment by Dranah** [comment]
Then please revert the fix. An unintended threatwipe is better than an unintended 4million threat.
