### ISSUE TITLE
Kalu'ak Daily Reputation - Howling Fjord Daily Quest

### ISSUE THREAD

**Issue by Longbows** [WoWManiaUK/Redemption#2351]
The Howling Fjord Kalu'ak Reputation Chain is not working as intended.  The chain can begin in two ways, one is Lunk-tusk outside Westguard Keep and if the chain is started at this point the daily does open up continuously for the character going forward.  
If the other option is chosen, and the quest chain is started at Orfus of Kamagua at the Ancient Lift the daily reputation is only available once and does not become available again once the quest chain is complete and the first daily is completed.  If you go back to Lunk-tusk if the second option is chosen hovering the mouse over Lunk-tusk shows an exclamation point indicating that there should be a quest available, but alais there is not one available as the second path was chosen.  The daily quest should be available every day in the Howling Fjord if starting the quest from either Lunk-tusk or Orfus of Kamagua.

Thank you.

**Comment by fvicaria** [comment]
Please follow the procedure described...

**Comment by fvicaria** [comment]
If you don't provide me with the exact problem I cannot do anything about it.
Which quest do you think is missing? Which NPC? etc.

**Comment by fvicaria** [comment]
As-is. There is only one chain starting with:
http://www.wow-mania.com/armory/?quest=11573
Both NPCs will offer the same starting quest and there is no difference after you get there.

http://www.wow-mania.com/armory/?npc=25233
http://www.wow-mania.com/armory/?npc=23804

We are as 3.3.5a, even though wowhead.com is retail it still shows identical to our Armory.

**Comment by Longbows** [comment]
Sorry I am on the opposite side of the pond.

I'm currently doing the daily Kalu'ak quests on three characters all have completed http://www.wow-mania.com/armory/?quest=11573.  
The character I started the quest chain here: http://www.wow-mania.com/armory/?npc=25233 is working as intended.
Two characters are locked out of daily quests in Howling Fjord as I started the quest chain here: 
http://www.wow-mania.com/armory/?npc=23804#starts
The two characters that are locked out of the http://www.wow-mania.com/armory/?quest=11472 after completing it once.  Now the npc for the daily quest http://www.wow-mania.com/armory/?npc=24810 just says, "Many changes come to the land and water: you, them... much change.  Kamagua's way of life is threatened by these changes.  What will you do?"
It's been about four days since the two characters initially completed http://www.wow-mania.com/armory/?quest=11472 and it has not become available again.
