### ISSUE TITLE
Ghost Wolf = Human

### ISSUE THREAD

**Issue by netyoda** [WoWManiaUK/Redemption#2352]
Since 2.2.10 patch, my Tauren Shammy's Ghost Wolf form now shows him as a moustachioed Human

**Comment by fvicaria** [comment]
Add image or npc info please

**Comment by netyoda** [comment]
Oops, apologies, lack of coffee

Account : netyoda
Toon : Tanta
Tauren Shaman

![wolf](https://user-images.githubusercontent.com/3975474/37703794-80871a68-2cff-11e8-8fc3-fc5cc4962038.jpg)
![tauren](https://user-images.githubusercontent.com/3975474/37703795-80b56e40-2cff-11e8-9515-740d1d3530f8.jpg)

**Comment by fvicaria** [comment]
Fixed in dev. Thank you.

**Comment by netyoda** [comment]
Thank YOU!
