### ISSUE TITLE
[Icecrown] Death's Rise

### ISSUE THREAD

**Issue by Necko23** [WoWManiaUK/Redemption#2353]
After talking a bit more with GM Psygoa, he gave me an advice to report the 'issue' here.
Note from the Grand Admiral - It's a "Binds when picked up" item. You can get it from Icecrown, Onslaught Harbor, from Scarlet Onslaught Trunk, and ONLY from those trunks. Here's the thing, in order for you to open trunks, you need to get Scarlet Onslaught Trunk Key which is a quest item for quest "Intelligence Gathering". You get keys only then. I wasn't aware of that eairler, so I cannot get Note from the Grand Admiral. It is important to me since I am trying to achieve Loremaster. I have also tried partnering with a Rogue, but that didn't help. Rogue can lockpick them, but since he has to loot then, it doesn't help, as I said, item is "Binds when picked up".
Here's additional link which will hopefully help even a little bit:
WoWHead Note: http://www.wowhead.com/item=40666/note-from-the-grand-admiral
WoWHead Key: http://www.wowhead.com/item=40652/scarlet-onslaught-trunk-key
WoWHead Trunk: http://www.wowhead.com/object=191543/scarlet-onslaught-trunk
If I can provide you with any additional info let me know.

With thanks,
Dudley.

**Comment by fvicaria** [comment]
What is the issue?  I need to know... 1. How it is supposed to happen, 2. How it is working now, etc


Please follow the procedure described below before creating a new issue:
[How to Properly Report an Issue](https://github.com/WoWManiaUK/Redemption/wiki/How-to-Properly-Report-an-Issue)

This will help developers identify and fix the issue quicker. Incorrectly or unclear reports will simply be deleted.

**Comment by fvicaria** [comment]
![image](https://user-images.githubusercontent.com/9414661/37714124-a873d410-2d10-11e8-8af5-5707a8ca1ae8.png)

**Comment by Necko23** [comment]
No buddy, you cannot get those keys without the quest. They're QUEST ITEMS

**Comment by fvicaria** [comment]
Exactly. You need to get the quest. Do you have the quest?

**Comment by Necko23** [comment]
I already did it. As I said : "you need to get Scarlet Onslaught Trunk Key which is a quest item for quest "Intelligence Gathering". You get keys only then. I wasn't aware of that eairler, so I cannot get Note from the Grand Admiral."

**Comment by fvicaria** [comment]
Then there is no bug. You messed up and didn't do it when you should.
This place is for bugs only. As far as I understand there is none here.

**Comment by Necko23** [comment]
I wasn't aware of that at all. I talked to GM Psygoa for quite some time. He's the one who told me to report it here

**Comment by fvicaria** [comment]
Yes sorry for the misunderstanding. We fix issues only. Try getting the first quest again (if it is re-doable)

**Comment by Necko23** [comment]
Sorry for wasting your time. It isn't, so that's that I guess. Thank you anyhow!
