### ISSUE TITLE
[Boss] Ulduar's Auriaya

### ISSUE THREAD

**Issue by Ashamedlol** [WoWManiaUK/Redemption#2354]
Defeating the Feral Defender (http://www.wow-mania.com/armory/?npc=34035) that's summoned by Auriaya's spell [Activate Feral Defender] (http://www.wow-mania.com/armory/?spell=64447) does not give you the Achievement [Nine Lives] (http://www.wow-mania.com/armory/?achievement=3076) after defeating her.

http://www.wow-mania.com/armory/?achievement=3077 25man version.

**Comment by Ashamedlol** [comment]
http://www.wow-mania.com/armory/?achievement=3077 25man version.

**Comment by fvicaria** [comment]
Working in dev. Please re-test.
