### ISSUE TITLE
[Boss] Ulduar's Iron Council (Stormcaller Brundir)

### ISSUE THREAD

**Issue by Ashamedlol** [WoWManiaUK/Redemption#2355]
Interupting Stormcaller Brundir's  Chain Lightning (http://www.wow-mania.com/armory/?spell=63479) and Lightning Whirl (http://www.wowhead.com/spell=61915/lightning-whirl) all the time does not give you the achievement "Can't Do That While Stunned" (http://www.wow-mania.com/armory/?achievement=2947),
even if left last.

ID of Stormcaller Brundir: http://www.wow-mania.com/armory/?npc=32857
25man version: http://www.wow-mania.com/armory/?achievement=2948

**Comment by fvicaria** [comment]
Unless you have the requirements it won't happen.

**Comment by Ashamedlol** [comment]
What requirements?
