### ISSUE TITLE
Kalu'ak Daily Reputation - Howling Fjord Daily Quest

### ISSUE THREAD

**Issue by Longbows** [WoWManiaUK/Redemption#2357]
Resubmission with detailed description of issue.

I'm currently doing the daily Kalu'ak quests on three characters all have completed http://www.wow-mania.com/armory/?quest=11573.
The character I started the quest chain here: http://www.wow-mania.com/armory/?npc=25233 is working as intended.
Two characters are locked out of daily quests in Howling Fjord as I started the quest chain here:
http://www.wow-mania.com/armory/?npc=23804#starts
The two characters that are locked out of the http://www.wow-mania.com/armory/?quest=11472 after completing it once. Now the npc for the daily quest http://www.wow-mania.com/armory/?npc=24810 just says, "Many changes come to the land and water: you, them... much change. Kamagua's way of life is threatened by these changes. What will you do?"
It's been over five days since the two characters initially completed http://www.wow-mania.com/armory/?quest=11472 and it has not become available again.

With the two characters that are locked out of the daily, when visiting http://www.wow-mania.com/armory/?npc=25233 an exclamation point appears when hovering the mouse over the npc indicating a quest available, but there is none.

**Comment by TheManiax** [comment]
@Longbows 
Are the two stuck characters both Alliance?

**Comment by squalllh1989** [comment]
You need to start by talking to Orfus which starts a long quest chain and leads to Scalawag Point. Complete [Street "Cred"](http://www.wow-mania.com/armory/?quest=11509) then head over to the north ship in the same area and complete [Swabbin' Soap](http://www.wow-mania.com/armory/?quest=11469). Once that is done, you have access to [The Way to His Heart...](http://www.wow-mania.com/armory/?quest=11472) daily quest.

**Comment by squalllh1989** [comment]
This is the list of the quest i just completed to make the daily avaible to me (maybe some is not needed, i just complete them all to make sure i cleared the way to the quest :), hope this will help you to get the daily quest you want
![wowscrnshot_032418_012851](https://user-images.githubusercontent.com/27235989/37847279-d9ee0508-2f02-11e8-941b-946eb00a76a9.jpg)
