### ISSUE TITLE
[Boss] Ulduar's Kologarn

### ISSUE THREAD

**Issue by Ashamedlol** [WoWManiaUK/Redemption#2358]
The boss's Right Arm (http://www.wow-mania.com/armory/?npc=32934) is on the Left, Left Arm (http://www.wow-mania.com/armory/?npc=32933) is on the Right which causes confusion, and when you kill the arm(s), rubble creatures spawn, however, if you kill 5-6+ arms, it doesn't count towards the Achievement [Rumble and Roll] which asks you to spawn at least 25 rubble creatures (5 rubble creatures spawn when an arm is down so 5 arms total, 6 for safety).

Achievement: http://www.wow-mania.com/armory/?achievement=2959 / http://www.wow-mania.com/armory/?achievement=2960

**Comment by squalllh1989** [comment]
1) The right arm is on the right, the left arm is on the left, at the right place (the side is of the boss, not your side, how do you call your own arm ? the one on YOUR left is the left arm, right ? not the one on the left of people stand before you.
![wowscrnshot_032318_155922](https://user-images.githubusercontent.com/27235989/37820738-2b8ffeec-2eb4-11e8-806b-0764b075c052.jpg)

2) The achivement work for me, didn't know what happen to your case, but here is mine:
![wowscrnshot_032318_160523](https://user-images.githubusercontent.com/27235989/37820748-32a99e2c-2eb4-11e8-8672-46f1236483bd.jpg)
