### ISSUE TITLE
[Raid]Twin Val'kyr

### ISSUE THREAD

**Issue by squalllh1989** [WoWManiaUK/Redemption#2359]
- How it should work: The 2 Val'kyr is share hp with each other and will both die at the same time
- What actually happen: some time their hp is not share together, 1 died before the other. After 1 died, the portal with her colour vanish, so you will do very tiny dps to the other that still alive, since you has the debuff of her colour, which reduce damage from her elemen and reduce your damage to her. If at that moment she cast twin's pact to heal up herself then you will never be able to down her and end up wide at berserk
![wowscrnshot_032318_104815](https://user-images.githubusercontent.com/27235989/37848330-51b0caaa-2f06-11e8-83c4-b4a7c673130c.jpg)

Real case: dark Val'kyr is death, light Val'kyr is alive, the whole raid has light debuff as we are dps the dark boss before, then dark portal vanish, the light boss cast the twin's pact and heal herself, we can't deal with her as all of our damage to her is greatly reduced

**Comment by Keader** [comment]
It was caused by Aimed Shot / Mortal Strike in Valkyr
It cause health desync when valkyr cast heal spell.

**Comment by squalllh1989** [comment]
oh so that's the problem, make sense now

**Comment by BatuMania** [comment]
This isnt how it should be however.

**Comment by TheManiax** [comment]
Not Mortal strike, nor Aimed shot is causing the issue to happen any more
So I assume it is fixed.
