### ISSUE TITLE
[Talent] Honor Among Thieves

### ISSUE THREAD

**Issue by Guus18** [WoWManiaUK/Redemption#2362]
Honor among Thieves doesn't work. It is a sublety talent and it should give me a combo point when someone in my group critically hits of heals but it does not do that. Will you check this for me?

**Comment by fvicaria** [comment]
Please follow the procedure described below before creating a new issue:
[How to Properly Report an Issue](https://github.com/wow-mania/Redemption/wiki/How-to-Properly-Report-an-Issue)

This will help developers identify and fix the issue quicker. Incorrectly or unclear reports will simply be deleted.

**Comment by TheManiax** [comment]
[Honor Among Thieves](http://www.wow-mania.com/armory/?spell=51701)
**How it should work:** When anyone in your group critically hits with a damage or healing spell or ability, you have a 100% chance to gain a combo point on your current target. This effect cannot occur more than once every second.
**How it works:** There won't be any combo point rewarded in-case any of your party member does a critical damage or heal.

**Comment by TheManiax** [comment]
Still no combo point rewarded when a party member hits a critical strike as damage or healing spell.

**Comment by Keader** [comment]
Fix made, but idk if janitor build it :(

**Comment by Keader** [comment]
Yeah now is builded.
Tested today and working in dev \o/

**Comment by Guus18** [comment]
Thank you guys!
