### ISSUE TITLE
The Foot of the Citadel

### ISSUE THREAD

**Issue by antonvidin** [WoWManiaUK/Redemption#2363]
Hello team,

I was playing on WOW Mania (Redemption server) when I bumped into a bugged quest (referred in the title). I logged a ticket to an in-game GM - Weeble. The GM checked the quest and confirmed it was bugged - you do not receive the required drop (the head of Gorax). I killed him three times and the mob was either unlootable or granted a normal loot - no head of Gorax was there. I'm grateful for Weeble's prompt response and I do hope you manage to fix this quest. 

P.S. WOW Mania is one of the best servers I've ever played. Keep up the good work and continue improving the WOW experience on Mania's servers. 

Thank you!

Sincerely yours,

Anton Vidin

Lok'tar ogar

**Comment by fvicaria** [comment]
Please follow the procedure described below before creating a new issue:
[How to Properly Report an Issue](https://github.com/wow-mania/Redemption/wiki/How-to-Properly-Report-an-Issue)

This will help developers identify and fix the issue quicker. Incorrectly or unclear reports will simply be deleted.

**Comment by Zunrin** [comment]
The quest log is there for a reason.

"Kill Force-Commander Gorax, place the Challenge From the Horde upon his corpse, kill The Hand of Kargath, and then bring the Head of the Hand of Kargath to Nazgrel in Thrallmar."

**Comment by squalllh1989** [comment]
You simple does the quest wrong, and the gm also seem to doesn't understand how the quest work, this is how you do the quest: 
1)Kill Force-Commander Gorax
2) place the "Challenge From the Horde" (quest item provided to you) upon his corpse
3)kill The Hand of Kargath, which come with 2 adds, after you do that, then loot his corpse and get his head and bring it back to turn in the quest.
