### ISSUE TITLE
[NPC Dialogue] The Defias Brotherhood quest

### ISSUE THREAD

**Issue by Austerror** [WoWManiaUK/Redemption#2365]
[Dialogue] The Defias Traitor (NPC), during [The Defias Brotherhood] escort quest, will say $n instead of the mob or player name.

For example, he says "$n incoming! Get ready to fight!"

This is just the NPC dialogue that is effected and doesn't effect the quest in any way.

**Comment by fvicaria** [comment]
http://www.wow-mania.com/armory/?quest=155
