### ISSUE TITLE
[Spell] Hammer of Justice

### ISSUE THREAD

**Issue by Ashamedlol** [WoWManiaUK/Redemption#2366]
The second part of the spell isn't working on bosses, only works on NPCs, as the spell states "interrupts non-player spellcasting for 3 sec." you should be able to interupt specific spells such as Lady Deathwhisper's Frostbolt, Devourer of Soul's Phantom Blast and list goes on.

It was removed in Cataclysm, as it says "Cataclysm Patch 4.0.1 (2010-10-12): No longer interrupts non-player spellcasting. " on https://wow.gamepedia.com/Hammer_of_Justice so it should be working on wotlk.

Spell ID: http://www.wow-mania.com/armory/?spell=10308

**Comment by Keader** [comment]
i have a idea how fix it.
I will check when i back of uni

**Comment by TheManiax** [comment]
Works on NPCs now
But not on bosses
i.e.
Couldn't interrupt LDW's frostbolt

**Comment by Keader** [comment]
lul i dont send fix to janitor yet hahah

**Comment by Keader** [comment]
Idk if janitor build, so wait i confirm if is builded before test it please xD

**Comment by Keader** [comment]
Now is working @TheManiax , can you test now

**Comment by Ashamedlol** [comment]
![index](https://user-images.githubusercontent.com/16576459/38033608-b5a03ada-32a0-11e8-89ab-93aad8ac8e34.png)
Working as intended now.

**Comment by Keader** [comment]
Dont close yet, janitor will close when he update to redemption.
