### ISSUE TITLE
[Dungeon] Trial of the champion

### ISSUE THREAD

**Issue by squalllh1989** [WoWManiaUK/Redemption#2367]
In the trial of the champion, there is a bug atm as if you encounter the 2nd boss is [Edric the pure](http://www.wowhead.com/npc=35119/eadric-the-pure)
- How it should work: You need to clear all 3 pack of add before Edric engage you and you can fight him, after defeat him you can have the loot and talk to [Jaeren sunsworn](http://www.wowhead.com/npc=35004/jaeren-sunsworn) to start the next fight
- How it actually happen now: You can engage Edric right away if you go near him, damage him before clear all the add there (he should not be damageable while the add is still alive, but he is) . Then after you defeat Edric and clear all the add, the bug happen that you can't talk to Jaeren sunsworn to start the fight anymore, that make the group stuck there with an uncompleted dungeon in rdf hc (i got this bug in rdf hc today and retested it in test realm, can be reproduce, not a random bug).

**Comment by Dranah** [comment]
I can confirm Eadric can be ninja-pulled before his adds are cleared 
This is often not even done intentionally, pulling his adds with i.eg. Howling Blast as a DK tank will engage Eadric too.

**Comment by Keader** [comment]
Fixed.
Up to test in dev already.
