### ISSUE TITLE
Get Kraken! quest issue

### ISSUE THREAD

**Issue by Momomarie** [WoWManiaUK/Redemption#2368]
Icecrown:Get Kraken! quest:
I have done this quest many times before with no problem but in the past 5 or so times that I received this quest, I’m not able to completed it.  I would click on the flaming spears icon and then on the target and I would get a “You can’t do that yet”.  I’m not mounted and I have the target selected.  I have the latest Launcher 2.2.10.  Aymelek watched me try it and suggested me to open a report on GitHub.
Thanks,
Momomarie

**Comment by fvicaria** [comment]
Works!

**Comment by Momomarie** [comment]
I just tried it and it’s still giving me a “You can’t do that yet” on the Deepcallers and a Invalid Target on the Kraken.
