### ISSUE TITLE
[Quest] Lost Thunderbrew Recipe

### ISSUE THREAD

**Issue by GMLucetta** [WoWManiaUK/Redemption#237]
http://www.wowhead.com/quest=4134/lost-thunderbrew-recipe

Players have to enter Black Rock Depths and get to the Grim Guzzler, once there they have to break open casks in order to cause http://www.wowhead.com/npc=9537/hurley-blackbreath to come running in for the quest to kill him. 

When the kegs are broken http://www.wowhead.com/npc=9537/hurley-blackbreath doesn't appear so the quest cannot be completed.

**Comment by Ackpfft** [comment]
Yup! I had to have a GM complete that quest for me a couple days ago.
