### ISSUE TITLE
Hood of Blinding Eyes. SQUARES

### ISSUE THREAD

**Issue by emphysema1** [WoWManiaUK/Redemption#2371]
http://www.wowhead.com/item=87051/hood-of-blind-eyes, is making floating squares. like the other helms and shoulders like this are all making Squares instead of the real animation it should be making.

**Comment by squalllh1989** [comment]
Did you update your client to lastest version yet ? those item are not in wotlk, if you didn't update your client it will be like that

**Comment by TheManiax** [comment]
Would be nice if both of you share a screenshot of how you see it @squalllh1989  @emphysema1

**Comment by fvicaria** [comment]
Fixed but will need client update.

**Comment by emphysema1** [comment]
![wowscrnshot_032718_175608](https://user-images.githubusercontent.com/36346883/37999381-32898d8a-31e8-11e8-8d5c-baed30872c24.jpg)

**Comment by emphysema1** [comment]
![wowscrnshot_032718_175607](https://user-images.githubusercontent.com/36346883/37999387-3d40dda0-31e8-11e8-8884-9008da7e1d12.jpg)

**Comment by emphysema1** [comment]
I just had a gm tell me it wasn't right as squares

**Comment by emphysema1** [comment]
by the way its all the items like this animation as well so pls fix those as well, helms shoulders

**Comment by fvicaria** [comment]
Did you stop for a second to read what I wrote?

**Comment by emphysema1** [comment]
now there are no animation at all?
