### ISSUE TITLE
[Spell] Master's Call on Hunter ; [Spell] Deathgrip on Death Knight ; [Spell] Anti Magic Zone

### ISSUE THREAD

**Issue by KyptAMaN** [WoWManiaUK/Redemption#2372]
Ok so these are 3 of some bugs that are annoying at pvp.

Master's Call should remove ALL movement imparing effects or roots, and its not atm.

Deathgrip has no minimium range, and it says "target is to close" wich is wrong, and its an instant cast aswell.

Anti Magic Zone is absorbing only like 4k spell dmg and it should absorb 19k/20k .

Just take a look at it please and would be great if  this was fixed, ty.

**Comment by fvicaria** [comment]
Another thing that is annoying is people not following the instructions when logging issues... 

Please follow the procedure described below before creating a new issue:
[How to Properly Report an Issue](https://github.com/wow-mania/Redemption/wiki/How-to-Properly-Report-an-Issue)

This will help developers identify and fix the issue quicker. Incorrectly or unclear reports will simply be deleted.

**Comment by KyptAMaN** [comment]
why u want me to follow the things so hard? ffs i think i was clear about the 3 spells that are bugged, Master's Call (hunter)  ; Deathgrip and Anti Magic Zone (DK) .

is that an issue? jeez.. am just tryin to do what some ppl dont even bother . lmao.

**Comment by fvicaria** [comment]
So putting crap here with no explanation or steps and missing every single point requested in the link better how?

**Comment by squalllh1989** [comment]
@KyptAMaN : Please specify how we can reproduce the bug that you mention, don't take it just like you are doing a favor to the dev and tester and it provide you nothing and it's only your act of good. Sorry to say that the way you are doing your report is terrible without any respect. You can try to read other report here and find out how you should make it.
About your report, sorry but i need more information to figure out what you are talking about:
- Deathgrip is working fine for me, able to grip in melee range.
- About Master's Call, in what situation that you find out that it didn't remove the slow ? and what slow that it didn't remove ? If you can provide a screenshot with the log that you tested out that will be great help.
- Anti Magic Zone: same as Master's Call, can you explain the situation that make you think it's bugged out ? and a screenshot with the log will be great help, too
