### ISSUE TITLE
[Quest] Gather the Orbs

### ISSUE THREAD

**Issue by cathyr1** [WoWManiaUK/Redemption#2374]
Found a bugged quest in Blade Edge: http://www.wow-mania.com/armory/?quest=10859.  Used the totem http://www.wow-mania.com/armory/?item=31668 multiple times, collected many orbs but none of them counts, still 0/15.

**Comment by fvicaria** [comment]
![image](https://user-images.githubusercontent.com/9414661/38135516-816ec74c-3410-11e8-9c81-31704f28ab9a.png)

There is a chance that you won't find an orb when you plant the totem. About 1 in 4 but it may vary.

**Comment by WhitephoenixTheBunny** [comment]
![image](https://user-images.githubusercontent.com/31921098/38136368-d7d15870-3415-11e8-969a-6c6ee2e3572c.png)
I got all at the 1st time

**Comment by cathyr1** [comment]
How did you achive that? I put so many totems but no orb collection counts. I saw the video where the orbs are randomly moving through this area while in the game all of them are still on the one place. Maybe this could be the problem.
![wowscrnshot_033018_133539](https://user-images.githubusercontent.com/30184491/38136555-755a5d72-341f-11e8-805d-db86e9d84155.jpg)
![wowscrnshot_033018_133551](https://user-images.githubusercontent.com/30184491/38136560-79c51bc2-341f-11e8-9a99-514c644cdf1b.jpg)
