### ISSUE TITLE
Missing relentless vendor in dala.

### ISSUE THREAD

**Issue by Wardoc** [WoWManiaUK/Redemption#2375]
Theres supposed to be a relentless vendor who sells rele gear for arena points and no rating in underbelly.

http://wow-mania.com/armory/?npc=33927

**Comment by gamer100** [comment]
The Npc is at his place,

**Comment by fvicaria** [comment]
NPC is there
![image](https://user-images.githubusercontent.com/9414661/38143579-13fbca4c-3439-11e8-9183-4cb430260ae7.png)
