### ISSUE TITLE
Relentless vendor missing.

### ISSUE THREAD

**Issue by Wardoc** [WoWManiaUK/Redemption#2376]
As i said in the last post theres supposed to be a Relentless gladiator vendor in Dalaran, you said the npc is there but its selling wrathful, theres supposed to be a separate vendor that sells relentless set. cant really prove it because you only allow to link to this servers db which shows this vendor as the rele vendor.

**Comment by Wardoc** [comment]
https://gyazo.com/06a214d75189753f5f2c098bcab141da
This is how its supposed to be.

**Comment by fvicaria** [comment]
1. the vendor is not missing
2. it has the items it had on 3.3.5a

**Comment by Wardoc** [comment]
No it has Hateful gladiator's on it which isnt supposed to be there.

**Comment by Wardoc** [comment]
What happened in wotlk was every time there was a new season they would update the vendors, theres supposed to be a vendor for the last 3 seasons, Furious, Relentless, and Wrathful. every other 3.3.5a server has this as well.

**Comment by fvicaria** [comment]
if you go to the Armory and enter the item you are looking for you will see that there are a few vendors selling Relentless gear.

**Comment by Wardoc** [comment]
Both the Tanaris and Netherstorm vendors are no where to be found, and those are the only ones that sell them for arena points instead of EoFs.

**Comment by fvicaria** [comment]
I will check. They may have fallen underground.
