### ISSUE TITLE
Transmog weapon Bow Ravenguard doesnt work/glitched

### ISSUE THREAD

**Issue by vandam93** [WoWManiaUK/Redemption#2377]
I got the Ravenguard transmog [http://www.wow-mania.com/armory/?item=150211#links](http://www.wow-mania.com/armory?item=150211)

The issue is that its glitched, The auto attack animations of this skin dont work properly, after the first shot my character stays still and doesnt move either the cord or the bow what so ever! but im still doing damage and i see the arrows flying...

And i cant remove it from my bow, I tryed to remove it at the npc it works for a bit but when i relog it comes back...i was so annoyed with this that i destroyed the transmog item in order to see if it helps...dumb of me

Looking forward for a fix or remove it completly from my bow!  pls

using wow mania launcher with the 2.2.10 version

MC: Northflux

**Comment by vandam93** [comment]
?? at least say something...whats wrong what should i do, maybe? im still playing with a bugged bow and no1 helps me the gm told me to make a post here, so i did and not even an answer...at least say something or help me dont just close the post whithout saying nothing!

**Comment by fvicaria** [comment]
I will check it tomorrow morning but usually visual issues with transmog are not fixable unless they are effects. Can you post a screenshot, please?

**Comment by vandam93** [comment]
No Problem, not a big issue for me anymore just hit 80 will just change weapon. 

Take your time to fix it dont bother or waste your time on me

Sorry for being a little salty :+1:
