### ISSUE TITLE
Guest not working.

### ISSUE THREAD

**Issue by Troelsjj** [WoWManiaUK/Redemption#2378]
Hello there,

While fighting my way through Thousand Needles i stumpeled upon a mob that dropped me "Assassination Note". Picked it up and started the quest but the next quest, Protect Kanati Greycloud, that i got after turning "Assassination Note" in don't work. I was very disapointed, but then figured you guys probably didn't know. Therefore i decided to make this post :)

Kinds regards,
Gloggerino

**Comment by WhitephoenixTheBunny** [comment]
Quest item: http://www.wow-mania.com/armory/?item=12564#starts-quest
Chain quest: http://www.wow-mania.com/armory/?quest=4881

**Comment by fvicaria** [comment]
Please follow the procedure described below before creating a new issue:
[How to Properly Report an Issue](https://github.com/wow-mania/Redemption/wiki/How-to-Properly-Report-an-Issue)

This will help developers identify and fix the issue quicker. Incorrectly or unclear reports will simply be deleted.

**Comment by WhitephoenixTheBunny** [comment]
![image](https://user-images.githubusercontent.com/31921098/38165472-b5a940b8-350b-11e8-9c93-5b05f6adcee0.png)
Working fine to me.
