### ISSUE TITLE
[Boss] Ignis the Furnace Master - Heating up

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#2379]
Hello,
I'd like to report a problem with Ignis' /npc=33118 adds, Iron constructs http://www.wow-mania.com/armory/?npc=33121, beginning to heat /spell=65667/ up and then become molten /spell=62373, regardless of standing in the Scorch radius or not.
There are three spells at play here, 
one that Ignis casts (spell ID 63474), which triggers 
some damage that damages the tanks frontally (ID 63473) and 
results in a ground-dot (ID 62549), which then damages players who walk inside it, and should heat up constructs which do so.

How it works atm: 
- When an Iron Construct activates, and you drag it inside an already existing Scorch /spell=62549 effect on the ground, it will not begin to heat up by entering the area radius.
- When Ignis casts Scorch /spell=63474 afterwards, it triggers all constructs to heat up without hitting them, no matter where they are - inside or outside a Scorch's radius or even in the water - they will begin to heat up and become molten.
The trigger for heating up seems to be Ignis casting Scorch, no matter where the constructs are positioned, which is incorrect.

How it should work:
- Iron constructs should begin to heat up only when the tank drags them inside a Scorch area on the ground
- Iron constructs should not begin to heat up regardless of where they are by Ignis casting Scorch, the trigger should be the effect on the ground.

Addendum:
- Earlier problem with Slag pot not (always) teleporting players to the pot still exists, but conditions are unknown for now. https://github.com/WoWManiaUK/Redemption/issues/2328

**Comment by Dranah** [comment]
Update on slag pot issue:
- Dire bear form shapeshift being active prevents the boss from being able to pick up the druid

The problem however happens on other specs too, which is still under testing why.

**Comment by Keader** [comment]
Note to my self: Check it before weekend

**Comment by Dranah** [comment]
additional issues under testing (unconfirmed):
- adds still gaining stacks after becoming molten
- molten effect threatwipe and stun
- scorch effect needing to be dispelled when used on water area

**Comment by Keader** [comment]
rdy to test in next restart

**Comment by Dranah** [comment]
UPDATE:
- Iron Construct heat behavior is now corrected, they start heating when entering scorch areas (fixed)
- They no longer gain additional stacks of heat once theyre turned Molten (fixed)
- Threat wipe and stun still missing when adds become Molten (tweaking issue)
- Scorch effect is still not being dispelled (or suppressed - that could be a workaround) when overlaying with water (need fix)

**Comment by Keader** [comment]
Sniff dont show any stun when adds become Molten (but show threat wipe).
What Scorch Effect do you mean? Scorch has 3 effects zzzzzz

**Comment by Dranah** [comment]
- the GROUND effect of scorch must be fully dispelled when it lands on water (the entire thing, including visual, ground DOT on players and the heat stacking effect)
- scorch effect that does frontal damage to the tank when ignis casts it still does its damage

**Comment by Dranah** [comment]
UPDATE:
- Threat wipe when adds gain "Molten" effect is now fixed
- Scorch effect is now properly dispelled if the tank is standing in the water (though half of it can overlay with water if the tank is just outside on the edge of the pool - but i guess this is the best it can get)
- Ignis can now pick up shapeshifted druids for slag pot (fixed)
There is still no information or reproduce steps for slag pot having issues on other classes, so i'll leave the tweaking label.
