### ISSUE TITLE
[Boss] XT-002 Deconstructor

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#2380]
Alright, you want new topic, new topic it is xD
XT-002 Deconstructor /npc=33293, Ulduar.

New problems:

1) Damage done to heart /npc=33329 is not transferred to XT. (or only a negligible portion of it)
I have no idea when this broke, cuz it worked fine on dev when Keader rescripted the fight. Now XT simply continues from about same health as you left him before exposure, even if you do a ton of damage to the heart.

2) Gravity Bombs on hard mode /?spell=63024
After about 2 minutes into the hard mode after breaking the heart, XT simply stops casting gravity bombs. Light bombs keep rotating as normal, but not a single gravity bomb for the next 7minutes until he enrages.

3) Consumption /spell=28865/ and Void zone /spell=64203 damage (hard mode)
Void zones should do 5k damage per tick on 10man, 7,5k on 25man, before mitigated. They do a tiny portion of that now, about 800-1000 damage on 10man, 25 untested.
I'm actually confused as to why this void zone effect is called consumption at us, it seems to be two different spell ids with two different damage values to them. Either way the value on spell 64203 is the correct one for 10man,

**Comment by Dranah** [comment]
Update on issue 2) It seems that he casts 4 gravity bombs as per normal and then stops using the ability overall.

**Comment by Keader** [comment]
Fixed.
Waiting janitor pass me the files to send to PTR.
