### ISSUE TITLE
[Spell + Boss] Vanish on Bloodqueen

### ISSUE THREAD

**Issue by vexation47** [WoWManiaUK/Redemption#2381]
Vanish removes the bite on the rogue if the rogue is bitten.  It's kind of lame because Vanish is a legit cooldown for Assassination, wouldn't mind having Overkill (30% more energy generation) during a bite.

**Comment by fvicaria** [comment]
Please follow the procedure described below before creating a new issue:
[How to Properly Report an Issue](https://github.com/wow-mania/Redemption/wiki/How-to-Properly-Report-an-Issue)

This will help developers identify and fix the issue quicker. Incorrectly or unclear reports will simply be deleted.


Personal point of view or comments are also irrelevant when reporting an issue.

**Comment by vexation47** [comment]
Am I using our client? (Note: don't even open issue if not) : Yes
Am I using the latest Launcher? (Note: don't even open issue if not) : Yes
Did I include the steps to reproduce the problem? Yes
Did I include the description of how it should work? Yes
Did I include the description of what is happening? Yes
Did I include NPC/Item/Spell names (or IDs) from wowhead.com or Armory? No....sorry....
Be descriptive and precise.
DO NOT log multiple issues in one (each boss/item/quest must have its own issue).

**Comment by Zunrin** [comment]
This also happens with mages' mirror image (and probably hunter's feign death, any spell that gets you out of combat).

http://www.wowhead.com/spell=70867/essence-of-the-blood-queen is the buff.

**Comment by fvicaria** [comment]
AS-IS
