### ISSUE TITLE
[Quest] Teron Gorefiend, I am...

### ISSUE THREAD

**Issue by cathyr1** [WoWManiaUK/Redemption#2382]
This quest seems bugged http://www.wow-mania.com/armory/?quest=10639. When I transformed in Teron Gorefiend, his opponent http://www.wow-mania.com/armory/?npc=21877 hasn´t appeared.
![wowscrnshot_040118_204836](https://user-images.githubusercontent.com/30184491/38176475-d8a4b392-35ef-11e8-824f-515ae9e3ecca.jpg)

**Comment by fvicaria** [comment]
works

**Comment by cathyr1** [comment]
Tried 2 more times now and hasn´t get the quest. The opponent attacked my character instead of ghost and he killed him more quickly than I was able to kill him in ghost. He should attack only ghost, no character. Also mana of the ghost is low and he has no autoattack. I got multiple wasted deaths :( That really spoils my playing.
