### ISSUE TITLE
Hand of Illidari transmog problem

### ISSUE THREAD

**Issue by MilanBruno** [WoWManiaUK/Redemption#2383]
okay so i just got my hand of Illidari transmog and the off handed one weapon is faceing inside out,and when its sheated weapons stand on sides insded of on the back..so pls if you can sole this problem 
here are some screenshots

![wowscrnshot_040118_224447](https://user-images.githubusercontent.com/37986450/38177494-e9196746-3602-11e8-9294-cc5b7db557b9.jpg)
![wowscrnshot_040118_224454](https://user-images.githubusercontent.com/37986450/38177500-035fe260-3603-11e8-8676-884febacc48a.jpg)

**Comment by fvicaria** [comment]
There is no issue. You need to get the correct MH, OF and transmog with an appropriate item. Check rules on the forum.
