### ISSUE TITLE
[Boss] Alagalon the Observer-Ulduar

### ISSUE THREAD

**Issue by Bartok14** [WoWManiaUK/Redemption#2385]
Hey there is a bug that has been persistent for 2 weeks in a row now. Once you defeat Algalon he drops the chest but then the fight reengages and you can't kill him and you are in combat. It makes it difficult to do the loot because you are in combat again and can't open the chest. Just thought I'd let you know.

**Comment by Keader** [comment]
without reproduce steps we cant fix it my friend.

**Comment by Bartok14** [comment]
I don't actually think we did anything outside of the ordinary. We had a party of 10 do the fight each week. Once we killed him he dropped the chest and then becomes hostile again. Maybe just try killing him on the PTR realm to see if its working correctly cause I'm not sure why he agroes after we kill him.

**Comment by Zunrin** [comment]
Do you remember what your raid compo was?
(it may well be a specific ability causing it because i'm having trouble reproducing the issue)

**Comment by fvicaria** [comment]
One issue per boss. I closed the other.

**Comment by Keader** [comment]
I only can fix issues that i can reproduce

**Comment by Keader** [comment]
Is better keep the other open xd

**Comment by Zunrin** [comment]
^
