### ISSUE TITLE
[Boss] Algalon the Observer - Ulduar

### ISSUE THREAD

**Issue by Zunrin** [WoWManiaUK/Redemption#2386]
Making a new post for the boss to list all the issues concerning the boss and its adds.
http://www.wow-mania.com/armory/?npc=32871 (Algalon)
http://www.wow-mania.com/armory/?npc=33089 (Dark Matter)
http://www.wow-mania.com/armory/?npc=32955 (Collapsing Star)

1) Collapsing Stars evading:
When ever you deal damage to a star or apply any effect to it, it will evade and go back to its initial spot and will stop evading once it reaches its initial position (same thing happens to critters which may also be a bug)

2) Collapsing Stars not losing hp
If you damage a Collapsing Star (or apply any effect to it), it will not lose the 1%hp/s it should lose. If you do not damage them then they will gradually die as intended. This is probably due to them evading.

3) Dark Matter adds not respawning
The Dark Matter in the void realm do not respawn after the fight resets. This means you can kill them on a first try, making your next tries more easy.

4) Boss reengaging when defeated
I was unable to reproduce this issue on dev, but every time I've defeated Algalon on Redemption in a normal raiding group (and for every one else i know), the boss started attacking again once defeated (#2385)

**Comment by Keader** [comment]
Keeping it open, since has more issues here

**Comment by Keader** [comment]
Boss reengaging has any change of DOT in boss while he change to friendly?
Someone can try reproduce?

**Comment by Zunrin** [comment]
I tried and that was not the issue (with fire mage dots at least).
I tried haunt too but it was not it either.

**Comment by Keader** [comment]
try with warlock and priest
Mage dots is so meeh

**Comment by Zunrin** [comment]
I was still unable to reproduce :/ 
Even with enough damage for the dots to get algalon to 0% (since he turns untargetable at ~2%) he was not bugging out

**Comment by Bartok14** [comment]
In terms of our raid composition I can't remember the first raid, but the second raid we had a disc priest a warrior tank and paladin tank and a holy paladin, we also had 3 ret paladins for dps, a hunter, a mage and can't remember the last one.

**Comment by Ashamedlol** [comment]
A bug I've noticed: If you kill finish (kill) the boss while he's casting Big Bang, it won't consider it killed for people in the group as if the boss casted Big Bang and Ascend to the Heavens right after and "wiped" the group, even though you all are alive.

**Comment by Keader** [comment]
After next restart, please check if is fixed.

**Comment by squalllh1989** [comment]
Confirmed that these problem has been fixed:
- Collapsing Stars evading: Not evading anymore.
- Collapsing Stars not losing hp: losing hp again.
- Boss reengaging when defeated: does not reengaging in all of my test.
Problem still persis:
- Dark Matter adds not respawning: After kill all of the dark matter add in the black hole realm, they still didn't respawn for the rest of the fight.

**Comment by Keader** [comment]
@squalllh1989
If i remember right, they should not respawn in the middle of fight.
They should respawn if fight wipe (and it is fixed).
Did you have any prof of respawn in middle of fight?

**Comment by squalllh1989** [comment]
no i did't, i just follow and test the problem that the reporter report. I will try and look into this then.
