### ISSUE TITLE
[Calendar] Create Guild Event 

### ISSUE THREAD

**Issue by Bartok14** [WoWManiaUK/Redemption#2387]
Just wanted to let you know that the calendar doesn't seem to be allowing you to choose the correct time that you input. I think it needs an update  due to daylight savings. Tried to put in 3 am server time for guild event and it kept saying 4 am. Had to put in 2 am server time for it to correctly display 3 am. Not a major issue just thought I would let you know.

**Comment by fvicaria** [comment]
You have to options. Change the clock time on the client to match the server not your local or make it clear it is server time in the message. I will take a look at it but unlikely that we can do anything about it.
