### ISSUE TITLE
[Quest] Stunning View

### ISSUE THREAD

**Issue by Shadowmalroc** [WoWManiaUK/Redemption#2389]
After doing the previous quests to this one, I could no longer use the Orb of Dominion to control a Lithe Stalker to complete the quest Stunning View.

**Comment by fvicaria** [comment]
Please follow the procedure described below before creating a new issue:
[How to Properly Report an Issue](https://github.com/wow-mania/Redemption/wiki/How-to-Properly-Report-an-Issue)

This will help developers identify and fix the issue quicker. Incorrectly or unclear reports will simply be deleted.
