### ISSUE TITLE
The Grand (Admirals) Plan

### ISSUE THREAD

**Issue by Shadowmalroc** [WoWManiaUK/Redemption#2390]
When doing the daily quest Intelligence Gathering, when I open one of the chests there are the documents and also the drop for The Grand (Admirals) Plan. I have tried to pick up this quest 2 days in a row and can not get the dropped quest to stay in my bag. I can seem to pick it up but it is not in my bag when I look.

**Comment by fvicaria** [comment]
Please follow the procedure described below before creating a new issue:
[How to Properly Report an Issue](https://github.com/wow-mania/Redemption/wiki/How-to-Properly-Report-an-Issue)

This will help developers identify and fix the issue quicker. Incorrectly or unclear reports will simply be deleted.

**Comment by fvicaria** [comment]
It's a 20% chance. Please do you research before posting an issue.

**Comment by Shadowmalroc** [comment]
The comment on Github states it is a 20% drop. Yes, I appreciate that and It didn't appear both days I tried it until the fifth time I opened a chest, therefore 20%. The issue is when it is available from the chest It looks like I am picking it up (and it disappears from the chest) but it never appears in my bags. This happened 2 days in a row, I will try again today.


Cheers


/ken


________________________________

**Comment by fvicaria** [comment]
20% means ON AVERAGE.
You would have to do a lot more than 5 times to raise the probability of it being wrong.
Would you say a coin is rigged if you got 3 or 4 heads in a row?

**Comment by Shadowmalroc** [comment]
Well the drop rate is neither here nor there, the point is it dropped twice for me within the chest, and it appeared that i could pick it up, but on 2 occasions it was not in my bag after doing so. Because it was the fifth chest on both occasions, the quest was complete so I couldn't try again until the next day.


________________________________

**Comment by fvicaria** [comment]
OK I will check also if there is a problem with picking up the item.

**Comment by Shadowmalroc** [comment]
Hi, I managed to pick up this quest today. I don't know why it wouldn't before. I thought at first that maybe I needed to do some other quest before I could get it, but everywhere I checked basically said it drops doing "Intelligence Gathering" quest, which I could get no problem.


Thanks


Ken

________________________________
