### ISSUE TITLE
[Item] Ith'rix's Hardened Carapace

### ISSUE THREAD

**Issue by cathyr1** [WoWManiaUK/Redemption#2392]
This item http://www.wow-mania.com/armory/?item=34777#contained-in-object is permanently missing in the game. It should be in front of Warsong Hold in Borean Tundra. It starts a quest http://www.wow-mania.com/armory/?quest=11632. So this quest cannot be obtained.

**Comment by fvicaria** [comment]
It just says in the link that is contained in the described object. Please check conditions.

**Comment by fvicaria** [comment]
![image](https://user-images.githubusercontent.com/9414661/38332047-e7f5703e-384c-11e8-897e-79ed294b3517.png)
