### ISSUE TITLE
Kalu'ak Daily Reputation - Howling Fjord Daily Quest (Won't Refresh After 1st Time Completing Daily Quest)

### ISSUE THREAD

**Issue by Longbows** [WoWManiaUK/Redemption#2396]
I have two characters I've completed http://www.wow-mania.com/armory/?quest=11573 with and now the two characters are locked out of http://www.wow-mania.com/armory/?quest=11472 after completing the first daily quest.  After completing the daily quest once, the daily does not refresh for them and now the npc for the daily quest http://www.wow-mania.com/armory/?npc=24810 just says, "Many changes come to the land and water: you, them... much change. Kamagua's way of life is threatened by these changes. What will you do?"  Been two weeks since the characters finished the quest chain and still the Howling Fjord Daily has not become available again.

Adding Original Post Below:  (Because it is important, if you start http://www.wow-mania.com/armory/?quest=11573 from http://www.wow-mania.com/armory/?npc=25233 it works as intended and have done the daily multiple times on one character with no issue and has now reached exhalted.  Have two other characters that cannot do the Howling Fjord Kalu'ak daily quest as they started the quest chain with this npc http://www.wow-mania.com/armory/?npc=23804#starts and bypassed talking to http://www.wow-mania.com/armory/?npc=25233 first.  Completed the quest chain and did exactly one daily quest (which the dev confirmed worked, but needs to confirm that the daily becomes available in day two and see if it re-appears when the dailies get refreshed) and it has not become available on either of the other two characters, many days later.)

Original Post:
I'm currently doing the daily Kalu'ak quests on three characters all have completed http://www.wow-mania.com/armory/?quest=11573.
The character I started the quest chain here: http://www.wow-mania.com/armory/?npc=25233 is working as intended.
Two characters are locked out of daily quests in Howling Fjord as I started the quest chain here:
http://www.wow-mania.com/armory/?npc=23804#starts
The two characters that are locked out of the http://www.wow-mania.com/armory/?quest=11472 after completing it once. Now the npc for the daily quest http://www.wow-mania.com/armory/?npc=24810 just says, "Many changes come to the land and water: you, them... much change. Kamagua's way of life is threatened by these changes. What will you do?"
It's been over five days since the two characters initially completed http://www.wow-mania.com/armory/?quest=11472 and it has not become available again.
With the two characters that are locked out of the daily, when visiting http://www.wow-mania.com/armory/?npc=25233 an exclamation point appears when hovering the mouse over the npc indicating a quest available, but there is none.

**Comment by fvicaria** [comment]
When you finish quest 11573 you automatically rewarded with quest 11504. You cannot get the quest any other way. So either by mistake or on purpose you refused the next quest when offered at completion of the previous one. As I have said in the previous issue this is AS-IS.
I have just tried again the chain and it worked fine.

Also read the condition at the start:
![image](https://user-images.githubusercontent.com/9414661/38352499-4ddd7d7a-38ab-11e8-812a-4781b331b81b.png)

They are both available before you finish the first one in the chain but if you do it first you, in fact, break the chain.

**Comment by fvicaria** [comment]
Although the error was yours, ask a GM to remove both quests from you so you can start again.
