### ISSUE TITLE
[Quest] WANTED: Boss Grog'ak

### ISSUE THREAD

**Issue by moontouched** [WoWManiaUK/Redemption#2400]
Hello,
i stumbled accross the following issue today:
I'm not able to take the quest "WANTED: Boss Grog'ak" ( http://www.wowhead.com/quest=9820/wanted-boss-grogak ) from the Wanted poster in Zabra'jin, Zangarmarsh.
The Wanted poster ( http://www.wowhead.com/object=182165/wanted-poster ) offers only the quest Wanted : Chieftain Mummaki ( http://www.wowhead.com/quest=10117/wanted-chieftain-mummaki ).
Cannot currently obtain the "Mysteries of the Marsh" achievement ( http://www.wowhead.com/achievement=1190/mysteries-of-the-marsh ) due to the lack of quests caused by this issue.

I'm using the latest version of the Launcher 2.3.0
Race: Goblin
Class: Mage
Level: 80
Character name: Moontouched

**Comment by fvicaria** [comment]
![image](https://user-images.githubusercontent.com/9414661/38409318-e58c77ca-3978-11e8-93f2-ab08c522e13e.png)

**Comment by moontouched** [comment]
Okay, you have it, I don't! 
That's still an issue, no?

**Comment by moontouched** [comment]
![wowscrnshot_040618_215839](https://user-images.githubusercontent.com/36900407/38439367-0ace63b4-39e6-11e8-96d4-236a69d1218d.jpg)
![wowscrnshot_040618_215853](https://user-images.githubusercontent.com/36900407/38439369-0b9e9ae8-39e6-11e8-8ba9-03548ecaf030.jpg)
![wowscrnshot_040618_215923](https://user-images.githubusercontent.com/36900407/38439372-0c872416-39e6-11e8-98b5-5f72da16c3a0.jpg)

**Comment by moontouched** [comment]
You can see that i clearly DONT have the quest available!

**Comment by moontouched** [comment]
It could be a Goblin-related issue, just like the Argent tournament daily quests.
Please do not keep closing my threads before even trying to find the issue.
