### ISSUE TITLE
[Spell] Explosive Trap

### ISSUE THREAD

**Issue by Ashamedlol** [WoWManiaUK/Redemption#2401]
Using Explosive Trap on the place where the enemy is standing makes the trap disappear, using Explosive Trap and making an enemy walk to it also makes the trap disappear and does nothing.

This happens in PvE AND PvP.

Spell ID: http://www.wow-mania.com/armory/?spell=49067

**Comment by Ashamedlol** [comment]
1) Use Explosive Trap on someone standing, it'll disappear right way.
2) Use Explosive Trap on a spot, tell someone to walk to you, it'll disappear with no effect.

**Comment by Aristo14** [comment]
Never had this issue in raids, ill see what it does during raid.

**Comment by fvicaria** [comment]
Tested in dev and it works perfectly fine. Maybe it was fixed with the other changes.

**Comment by Aristo14** [comment]
Tested all traps during duel: 

all except explosive trap seem to work but also all are not visible to the oponent.
