### ISSUE TITLE
[Boss] Trial of the Champion's Eadric The Pure

### ISSUE THREAD

**Issue by Ashamedlol** [WoWManiaUK/Redemption#2404]
Whenever the boss casts Hammer of Justice (66863 / 66940) and shouts "Hammer of the Righteous!"
he starts casting Hammer of the Righteous (66867) which does the following:
"Hammer of the Righteous - Unlimited range - 2.5 sec cast
Hurls a hammer that strikes an enemy for 18200 Holy damage. If the target is not affected by Hammer of Justice, this Hammer may be caught and thrown back at the caster."

The part where if you get dispeled and end up picking up the hammer does not work here, it just gets you damaged by the spell damage anyway.

Videos showing how it works: https://www.youtube.com/watch?v=7ABTsKlCjQo (Normal spell, no dispel)
https://youtu.be/7ABTsKlCjQo?t=1m2s (1 minutes 2 seconds into past video, Priest dispels the Warrior's Hammer of Justice and Warrior picks up the Hammer of the Righteous after it finishes casting, being able to use the same spell at the boss and damaging it).

**Comment by Ashamedlol** [comment]
Still doesn't work, got hit 16k after removing Hammer of Justice.

**Comment by fvicaria** [comment]
I will re-check

**Comment by Ashamedlol** [comment]
Any news on this? It's still bugged and would be tough for a new group cloth user to take 16k-18k direct damage.

**Comment by fvicaria** [comment]
We can re-open and Keader can take a look.

**Comment by Keader** [comment]
Can you test if fix works?

**Comment by Ashamedlol** [comment]
All attempts have worked, including a normal cleanse and a bubble.
