### ISSUE TITLE
[Quest] WANTED: Boss Grog'ak - second edition

### ISSUE THREAD

**Issue by moontouched** [WoWManiaUK/Redemption#2405]
Hello,
i stumbled accross the following issue today:
I'm not able to take the quest "WANTED: Boss Grog'ak" ( http://www.wowhead.com/quest=9820/wanted-boss-grogak ) from the Wanted poster in Zabra'jin, Zangarmarsh.
The Wanted poster ( http://www.wowhead.com/object=182165/wanted-poster ) offers only the quest Wanted : Chieftain Mummaki ( http://www.wowhead.com/quest=10117/wanted-chieftain-mummaki ).
Cannot currently obtain the "Mysteries of the Marsh" achievement ( http://www.wowhead.com/achievement=1190/mysteries-of-the-marsh ) due to the lack of quests caused by this issue.

I'm using the latest version of the Launcher 2.3.0
Race: Goblin
Class: Mage
Level: 80
Character name: Moontouched

![wowscrnshot_040618_215839](https://user-images.githubusercontent.com/36900407/38439641-1065f958-39e7-11e8-99ed-b35ae214bd38.jpg)
![wowscrnshot_040618_215853](https://user-images.githubusercontent.com/36900407/38439643-112933d2-39e7-11e8-8b78-444dd5a7017c.jpg)
![wowscrnshot_040618_215923](https://user-images.githubusercontent.com/36900407/38439645-126788e8-39e7-11e8-87b3-f7b9efd741ff.jpg)

You can clearly see that i do not have that quest available.
Please do not close my issue before fixing it.

**Comment by moontouched** [comment]
If you'd like any additional information, i'll be online in wow-mania the next 3 hours.
Feel free to contact me on niki_jakovlev@abv.bg aswell.

**Comment by fvicaria** [comment]
The quest has no requirement and it is available to all after level 58. The only potential issue is that the quest was taken in the past an dropped or not counted for some reason.
Open a ticket and ask a GM to remove it from your history and then check if it becomes available to you. If not he can give it to you.
