### ISSUE TITLE
[QUEST] [ALLIANCE] Emergency Protocol: Section 8.2, Paragraph D

### ISSUE THREAD

**Issue by furkanaltur34** [WoWManiaUK/Redemption#2407]
Quest ( http://www.wow-mania.com/armory/?quest=11796 ) goal is: There's have 3 crashed airplanes, Questgiver wants to mark them with "Emergency Torch" ( http://www.wow-mania.com/armory/?item=35224 ) 
Problem is: I cant torch the Southern Wreck, coordinate (59,7 39,2)

**Comment by fvicaria** [comment]
There are two crashes on the south. Just pick the other one.
