### ISSUE TITLE
[NPC] "They Grow Up So Fast" quest bugged

### ISSUE THREAD

**Issue by b0bh00d** [WoWManiaUK/Redemption#2408]
Reference: http://www.wowhead.com/quest=13906/they-grow-up-so-fast

My level 80 toon, "Baylock", has all the required materials to complete the quest "They Grow Up So Fast" in his inventory.  However, the quest-giver (Mor'vek in the Un'Goro Crater) has a silver question mark over his head, and trying to complete the quest gives me a greyed-out "Continue" button.

I've tried moving all quest items into the same bag, I've tried having the hatchling summoned and stored.  Everything worked fine for the daily questions for the past 20 days, but completing the quest is not possible.

**Comment by fvicaria** [comment]
Quest works. Get materials for individual quests. DO NOT get multiple quest that require the same material.
I advise to drop and retake the quest.
