### ISSUE TITLE
[BOSS] Yogg-Saron

### ISSUE THREAD

**Issue by master941201** [WoWManiaUK/Redemption#2410]
In Ulduar 10man (Maybe Ulduar 25man too) the last boss ''Yogg-sarun'' is bugged cause the Constrictor Tentacles that he summons in Phase 2 are friendly target for some reason (when they are suppose to be normal enimy targets) and at some point it summoned both friendly target and enemy Constrictor Tentacles and both off them was holding  the same person.
In total before the raid ended we had 7 people being grabbed and we didnt have a chance cause the Constrictor Tentacles was non-attackable.

**(BOSS)**
http://wowwiki.wikia.com/wiki/Yogg-Saron_(tactics)
In phase two its says that it should be killed asap and that they are killable, bur like i said it wouldnt allow us too hit them **(''The tentacles should all be killed as quickly as possible.
Ranged focus on the Crusher Tentacles
Melee focus on the Corruptor Tentacles
Constrictor Tentacles can be ignored until they grab someone, then they can be nuked quickly by a few damage dealers'').**

Im using the laucher and i have the lastest update.
Thanks in advance, screenshots are down below.
 
![wowscrnshot_040818_002621](https://user-images.githubusercontent.com/38086163/38460912-304604e2-3ac4-11e8-83b4-59ec028c8aa5.jpg)
![wowscrnshot_040818_002623](https://user-images.githubusercontent.com/38086163/38460915-35504376-3ac4-11e8-8c41-9a0954e66a46.jpg)

**Comment by Ashamedlol** [comment]
Can confirm, Constrictor Tentacles are unattackable right now and Yogg'saron attempts to dps them after everyone dies which is even more messed up.

**Comment by Keader** [comment]
lul, someone fucked something.
Waiting janitor get back my access to take a look on it.

**Comment by Keader** [comment]
In next reset, please check if is fixed in dev.

**Comment by squalllh1989** [comment]
Didn't tested the fix, i put the label on wrong thread.

**Comment by Keader** [comment]
And what you're waiting for?

**Comment by Ashamedlol** [comment]
Phase 2 has no tentacles, no brain portals, just Sara constantly casting spells and once you reach 40 sanity or wipe she will cast at no one and the fight won't reset on wiping.

**Comment by Keader** [comment]
Still Wonder who break it

**Comment by Keader** [comment]
Test now.

**Comment by Ashamedlol** [comment]
Now hostile, fixed.
