### ISSUE TITLE
[QUEST] The Battle For The Undercity (Alliance)

### ISSUE THREAD

**Issue by Gittyhubbers** [WoWManiaUK/Redemption#2411]
Quest: http://www.wow-mania.com/armory/?quest=13377 The Battle For The Undercity
Pre quest: http://www.wow-mania.com/armory/?quest=13371 Killing Time

I completed the prequest and got ported by Jaina to outside the Undercity. 
While there I was supposed to click on Broll Bearmantle to start the next quest (The Battle For The Undercity) but my dungeon finder queue popped. 
After completing the dungeon I was ported back to Stormwind instead with no way of getting back to the questgiver to start the quest.
I believe it is in a phased zone so I can't simply ride there and start it again.
Nobody in Stormwind will give me the quest as I have "completed" those steps, and I don't have it in my questlog to abandon and restart.

Character: Aiylana. Alliance lv80 Paladin.

**Comment by fvicaria** [comment]
As-is some quests cannot be re-taken once started.
