### ISSUE TITLE
[Quest] Gaining the Advantage

### ISSUE THREAD

**Issue by Wolch** [WoWManiaUK/Redemption#2413]
http://www.wowhead.com/quest=11875/gaining-the-advantage
The quest item (http://www.wowhead.com/item=35229/nether-residue) should be mined from Outland nodes, but it does not drop.

**Comment by fvicaria** [comment]
http://www.wow-mania.com/armory/?item=35229#gathered-from-object

**Comment by Wolch** [comment]
Have you read what I wrote? It should be mined from ore nodes! I am a MINER, I cannot gather herbs!!!

**Comment by fvicaria** [comment]
I read what you wrote and it was wrong. In 3.3.5a this item was not mined.
