### ISSUE TITLE
[QUEST][ALLIANCE] "Burn Skorn, Burn!"

### ISSUE THREAD

**Issue by furkanaltur34** [WoWManiaUK/Redemption#2414]
Links for quest: http://www.wow-mania.com/armory/?quest=11247
Quest item: http://www.wow-mania.com/armory/?item=33321
When you try to burn with torch,

Northwest Longhouse Set Ablaze --- Doesnt work.
Northeast Longhouse Set Ablaze --- Doesnt work.
Barracks Set Ablaze --- Doesnt work

**Comment by fvicaria** [comment]
![image](https://user-images.githubusercontent.com/9414661/38484846-c657b1ae-3bcf-11e8-8783-6f546b126e1e.png)

![image](https://user-images.githubusercontent.com/9414661/38484901-ee4c5f2a-3bcf-11e8-993a-d24e0efe6b1b.png)

![image](https://user-images.githubusercontent.com/9414661/38485026-57ea8ab0-3bd0-11e8-989d-f4fe08c17ade.png)

All work.

Please check videos or try different locations before opening issues.

**Comment by furkanaltur34** [comment]
when i tried to do this quest didnt worked, sorry for faulty post @fvicaria
