### ISSUE TITLE
Cannot create forum account

### ISSUE THREAD

**Issue by b0bh00d** [WoWManiaUK/Redemption#2415]
I need to talk about a bugged quest, but I cannot create a forum account.  The "Captcha" on the page for creating a forum account is saying that it expired on 2018-03-31, so there no way for me to enter a "Confirmation code" -- I don't have one, and can't generate it.

![image](https://user-images.githubusercontent.com/4536448/38506740-ef7b6c80-3bd7-11e8-8782-eeb786d22aa0.png)

**Comment by fvicaria** [comment]
How the hell is this a server issue?
