### ISSUE TITLE
Digging for Prayer Beads

### ISSUE THREAD

**Issue by icswcshadow** [WoWManiaUK/Redemption#2417]
The quest "Digging for Prayer Beads" seems to not work. This quest in Honor Hold requires you to get a Silk Thread to trade it for a "Fei Fei Doggy Treat" to give to the NPC "Fei Fei", however nothing is happening when you have the Treat. A blue question mark (or exclamation point) should appear over Fei Fei and when you interact with Fei Fei he's supposed to search for the stash where the "Draenei Prayer Beads" are located.

**Comment by squalllh1989** [comment]
The quest ["Digging for Prayer Beads"](http://www.wow-mania.com/armory/?quest=10916) working good, you don't need to interact with [Fei Fei](http://www.wow-mania.com/armory/?npc=20206) to get the quest item

![wowscrnshot_041318_120840](https://user-images.githubusercontent.com/27235989/38717857-a9e2ed8a-3f13-11e8-8b00-cf3788dc026f.jpg)
![wowscrnshot_041318_120844](https://user-images.githubusercontent.com/27235989/38717860-aca9c1b0-3f13-11e8-8829-824628d3dc56.jpg)
![wowscrnshot_041318_120847](https://user-images.githubusercontent.com/27235989/38717861-aeabee02-3f13-11e8-8068-5af00529340a.jpg)
![wowscrnshot_041318_120445](https://user-images.githubusercontent.com/27235989/38717867-b4106fb2-3f13-11e8-9a79-c87a05fcaa23.jpg)
![wowscrnshot_041318_120501](https://user-images.githubusercontent.com/27235989/38717871-b5d15cc6-3f13-11e8-8cd3-4be3f5ffd39e.jpg)

Maybe you can use google and youtube to search for how to complete the quest if you can't find your way work.

**Comment by squalllh1989** [comment]
in the case you confuse how you not need to interact the npc Fei Fei but still able to get the quest item, watch this video guide, which i find after 1 click of google search: https://www.youtube.com/watch?v=r2o8IjcKLMo

**Comment by squalllh1989** [comment]
Well, still, the quest that fei fei give should be enable after you get this quest, but it's not nesessary.
