### ISSUE TITLE
[NPC] Riggle Bassbait

### ISSUE THREAD

**Issue by gamer100** [WoWManiaUK/Redemption#2418]
http://www.wow-mania.com/armory/?quest=8193
The npc Riggle Bassbait is not at his place  so they cant  do  event

**Comment by fvicaria** [comment]
He is there only for two hours on a Sunday. From 12-2 check server time.

**Comment by squalllh1989** [comment]
anyway, the npc is [Riggle Bassbait <Fishmaster>](http://www.wow-mania.com/armory/?npc=15077), what you link in the first post is not the npc link, but the event he hold, [Master Angler](http://www.wow-mania.com/armory/?quest=8193)

**Comment by squalllh1989** [comment]
Well maybe the cause of this is that the npc is linked to other event that happen at another time ? Not sure about this tho, just my guess.
![2](https://user-images.githubusercontent.com/27235989/38780171-c797e2aa-40fc-11e8-8f30-6d11a5dbdfe5.png)

**Comment by fvicaria** [comment]
Good catch!
