### ISSUE TITLE
[Quest] Pushed Too Far (Stormpeaks)

### ISSUE THREAD

**Issue by Necko23** [WoWManiaUK/Redemption#2419]
Here's link to quest: http://www.wowhead.com/quest=12869/pushed-too-far
So what's wrong here is that Wyrms actually regenerate whenever you attack - making it impossible to kill. However there is a way to get by this quest - you can do that by killing Wyrms on your own without using Eagle which is the whole point of that quest.
I'll post a few screenshots of that happening, hopefully it'll help you understand how it is happening.
Screenshots: https://imgur.com/a/G5hBF
If I can provide you with any additional info please let me know!

Thanks in advance,
Dudley.

**Comment by fvicaria** [comment]
Although this can be easily done as is using both abilities in combination I have increased the regen time.

![image](https://user-images.githubusercontent.com/9414661/38783384-30aaa07e-40f9-11e8-95ab-f42408b843f4.png)
