### ISSUE TITLE
[Spell] Corpse Explosion

### ISSUE THREAD

**Issue by KyptAMaN** [WoWManiaUK/Redemption#2420]
Its not working, at all.. take a look into it

ty.

**Comment by fvicaria** [comment]
Please follow the procedure described below before creating a new issue:
[How to Properly Report an Issue](https://github.com/wow-mania/Redemption/wiki/How-to-Properly-Report-an-Issue)

This will help developers identify and fix the issue quicker. Incorrectly or unclear reports will simply be deleted.
