### ISSUE TITLE
Smoldering Ember Wyrm Sound Effects and flying mechanics

### ISSUE THREAD

**Issue by belrog** [WoWManiaUK/Redemption#2421]
the sound effects of the mount Smoldering Ember Wyrm is not working at all , it's like he's muted and this issue is the same for anyone who purchased the mount its sound effects are go and its flight mechanics are a bit glitchy .

**Comment by fvicaria** [comment]
As-is.

**Comment by belrog** [comment]
if sound were fine i would not have reported it ?! the dragon sound effects are not there while in flight and if you do /mountspecial it does not make a sound and its not just mine like i mentioned  , it only makes sound when you summon it and its footsteps when ur walking on ground other than that its muted , i saw this mount on retail and i know the difference .

**Comment by fvicaria** [comment]
This is not retail is a 10-year old client and we import what we can and it will always have limitations.

**Comment by belrog** [comment]
I know its not a retail version and i do appreciate your effort for
improving the game , i have only submitted this threat as recommended by an
in-game GM and have came to accept it how things are , first i thought it
was just a bug and i suggested that it would be fixed if possible , anyway
thanks you for reply .

best regards

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
