### ISSUE TITLE
[Spell] Power Word: Shield

### ISSUE THREAD

**Issue by Hajzlopuc** [WoWManiaUK/Redemption#2422]
Hello,

I would like to report an issue with priest's spell [Power Word: Shield](http://www.wow-mania.com/armory/?spell=48066). Currently this spell allows to absorb way too much damage. 

The base spell power ratio is 0.807.
With talent [Borrowed Time](http://www.wow-mania.com/armory/?spell=52800) ratio changes to 1.207 
Furthermore there is one more talent which improves PW:S - [Improved Power Word: Shield](http://www.wow-mania.com/armory/?spell=14769)

With both talents maxed, it should makes us formula like this right?:

[Base Value + (Spell power * 1.207)] * 1.15 = Final value of the shield

In my case while testing, I had 2359 spell power and both talents maxed.
So formula for me should look like this:
[2230 + (2359 * 1.207)] * 1.15 = 5838

But I have absorbed more than 14k damage with a single shield while testing. Shield is currently almost 250% (2.46x) stronger than it should be. I would say it's really huge and it makes priest much easier to play than it's intended.

![image](https://user-images.githubusercontent.com/32883164/38908594-509c17e0-42c1-11e8-9316-537e0dc14683.png)
![image](https://user-images.githubusercontent.com/32883164/38908607-63cdeba4-42c1-11e8-8741-24a6015b9f32.png)

EDIT:
Further test: 
0 talents, 2359 Spell power.
I should absorb [2230 + (2359*0.807)] = 4133 dmg
I've absorbed 11k
https://puu.sh/A5tog/e4f6fa9be5.jpg
https://puu.sh/A5toI/7f57b068e8.jpg

One more test:
0 talents. 0 spell power.
I should absorb 2230 damage (just a base value)
I have absorbed 2233
https://puu.sh/A5tvN/ad3c4f0be0.jpg

I guess the base value and talents are correct and it's something wrong with the spell power ratio.

**Comment by fvicaria** [comment]
Work as-is.

**Comment by medmonlolz** [comment]
This issue with PWD is from long time its just not normal the amount of dmg can PWD absorb instead of 7-8 it absorbs like 20k please re-check it as it plays a big role in both spheres pve and pvp

**Comment by Hajzlopuc** [comment]
It's definitely not fun to fight priests with 2.5x stronger bubble than it should be. Could you look into this once more please?

**Comment by KyptAMaN** [comment]
I knew it was bugged.. But its nice to see other ppl making these type of reports.. Well done Hajz.. And i totally agree with ya, and ive been saying that from long time. 

Cheers.

**Comment by Zunrin** [comment]
Just to add a few precisions, a couple more talents on the disc tree increase the amount of the shield (Twin Disciples 5/5 -> +5% and Focused Power 2/2 -> +2%).

Without taking all those talents into consideration, the spell power coefficient for PW:S is currently **3.748 instead of 0.8068**.
(Burrowed Time is correctly boosting the spell power coeff by 40%)

**Comment by Zunrin** [comment]
Update: This only seems to affect PVE damage. When taking damage from another player, the correct amount of damage is absorbed.

**Comment by Dranah** [comment]
More precisely, affects all damage you absorb when in PVE mode (not flagged, fighting NPCs or bosses).
In PVP "mode", all damage you take (also from NPCs you aggro) will be absorbed the correct total amount. (the shield behaves as intended whenever you're flagged for duel or pvp)

**Comment by Hajzlopuc** [comment]
Not true. Just absorbed over 11k from some warrior.

![image](https://user-images.githubusercontent.com/32883164/38954299-9110e432-4351-11e8-9376-b0631bd9a002.png)

**Comment by Dranah** [comment]
Corrected my post, it doesn't work in all pvp situations, just in duels. Regular hostile pvp, it's also broken. Odd.

**Comment by Keader** [comment]
Val shit.
Fixed.

**Comment by BatuMania** [comment]
#1278
#1287

**Comment by squalllh1989** [comment]
Since we fix the amount of absob, can we please fix the [shield's glyph](http://www.wow-mania.com/armory/?item=42408) also ? It's currently heal the shielded target by 5% of how much it absob, should be at 10%

**Comment by squalllh1989** [comment]
And with what @BatuMania linked, we are now has the spell back to how much it should absob, with the problem of it doesn't scale with icc buff, and the amount of heal it does with it's glyph reduced to 50%, so now the spell's effectiveness got affected a lot.

**Comment by Zunrin** [comment]
I can't do any testing atm, but do note that the 30% buff should get applied at the end (so in ICC with all talents: (2230+(SPx(0.8068+0.4)))x1.05x1.04x1.15x1.3) and not like described in #1278 and #1287. Those two posts were from the same guy, using non retail footage where major issues are present...

**Comment by Zunrin** [comment]
Oh and the glyph should actually be 20% (not 10% or 5%)

**Comment by Keader** [comment]
Make a new issue about glyph Zunrin ^^

**Comment by Zunrin** [comment]
Unable to test anything right now, i'll test and post accordingly in a week :P

**Comment by Dranah** [comment]
After testing this just today, the spell scales almost perfectly with ICC buff. 
There appears to be a 2-3% difference in expected value vs actual value in absorb, which may be due to the Focused Power (4%) effect not scaling properly, that is still under testing.
