### ISSUE TITLE
[Spell] Priest - Improved Devouring Plague double dipping from debuffs

### ISSUE THREAD

**Issue by Zunrin** [WoWManiaUK/Redemption#2426]
Similar to #2423.

Improved Devouring Plague is benefiting twice from any debuff on the target. For instance with no debuffs on the target, it was dealing 1999 damage, and with curse of elements (13% spell damage debuff) it was dealing 2552 (=1999*1.13*1.13) damage instead of 1999*1.13=2259.
The spell is not benefiting twice from buffs however.

Link to the spell: http://www.wow-mania.com/armory/?spell=63626

**Comment by fvicaria** [comment]
Are you serious? Are you complaining about a difference of less than 1% in final damage?
