### ISSUE TITLE
[Spell] Judgement + Seal of Righteousness

### ISSUE THREAD

**Issue by Maesna** [WoWManiaUK/Redemption#2427]
Greetings!

The issue I have found is that all 3 judgements with Seal of righteousness active (http://www.wow-mania.com/armory/?spell=21084) proc this Seal 2x, according to combat log- one before judgement damage and another one after, it should proc only 1x.

http://www.wow-mania.com/armory/?spell=20187

http://www.wow-mania.com/armory/?spell=53408
http://www.wow-mania.com/armory/?spell=20271
http://www.wow-mania.com/armory/?spell=53407

Reproduce steps:

-Be a paladin
-Buff yourself with Seal of righteousness
-Use whatever of 3 judgements.
-See result:
(I used all 3 judgements)
![image](https://user-images.githubusercontent.com/38591719/39087440-65c25660-45a1-11e8-9fec-0651c1f0e448.png)

**Comment by Porkeatingcrusader** [comment]
The seal is supposed to proc on a weapon swing. Each time your weapon hits the target, it should add holy damage from the seal. When you unleash a judgment (as you did three times) it will add additional damage according to the seal that was used. In your combat log example, it looks like you swung your weapon 6 times to produce 6 procs of Seal of Righteousness, and you judged 3 times to produce 3 procs of Judgment of Righteousness. Appears to be working as intended.

**Comment by Dranah** [comment]
@Porkeatingcrusader 
The seal procs on any melee attack.
Judgement does not necessarily trigger a weapon swing (as it can be used from longer range), and it should only proc the seal damage once, in addition to the judgement damage which depends on which seal you're using. So casting a judgement will result in a judgement of righteousness doing X damage, and a seal of righteousness proc doing Y damage. On the log you can see the latter happen twice.

**Comment by Keader** [comment]
test again after next restart xD

**Comment by Maesna** [comment]
@Porkeatingcrusader 
Do you see any weapon swing in log? No, I haven't swung a weapon once, I used Judgement from max range avoiding any weapon swing.

**Comment by fvicaria** [comment]
Thanks.

**Comment by Dranah** [comment]
This issue is back, lul. I've no idea when or how, but the exact same thing is happening again, each judgement procs x2 the seal effect, only with Seal of Righteousness.
Can you possibly reapply the fix?

**Comment by Keader** [comment]
It's not a regression.
Regression means: some fix cause a side effect or not working.
In this case, someone just vanished with the fix. And since i dont have it anymore... i need do again.
Anyway, fixed.
