### ISSUE TITLE
Scryer/Aldor rep bar not showing up for goblin characters

### ISSUE THREAD

**Issue by marthyjane** [WoWManiaUK/Redemption#2428]
I have 5 goblin characters and none of them have a rep bar for scyers or aldors.  The quest for choosing the faction in Shatt isn't available either.  I did do the balisks eye quest and also turned in fire wing signets but a rep bar still does not show up on character page.

**Comment by fvicaria** [comment]
Please follow the procedure described below before creating a new issue:
[How to Properly Report an Issue](https://github.com/wow-mania/Redemption/wiki/How-to-Properly-Report-an-Issue)

This will help developers identify and fix the issue quicker. Incorrectly or unclear reports will simply be deleted.

**Comment by fvicaria** [comment]
![image](https://user-images.githubusercontent.com/9414661/39092100-ec9b0c44-45fc-11e8-980d-f74e537303bc.png)

Make sure you have our client and is up to date. Always use the Launcher.
