### ISSUE TITLE
[Race] Worgen/Goblin - Aldor/Scryers Faction

### ISSUE THREAD

**Issue by marthyjane** [WoWManiaUK/Redemption#2431]
I made a death knight goblin to see if I could get a rep bar for aldor/scyer to show up and it did but when  I logged out then back in, it disappeared.  
![biop](https://user-images.githubusercontent.com/29937252/39099538-8474619e-4631-11e8-9696-a2d51d072536.png)
![bioplogback](https://user-images.githubusercontent.com/29937252/39099545-8f027dee-4631-11e8-87e4-f96943927bc8.png)
also my other goblins don't have rep bars
![acerbis](https://user-images.githubusercontent.com/29937252/39099552-afab7514-4631-11e8-9df9-9bc374c78ff9.png)
![demmona](https://user-images.githubusercontent.com/29937252/39099554-b49ee24a-4631-11e8-8501-29800cdd017e.png)
This appears to be a bug and is there a fix or something on my end I need to do?
Rep bar initially showed up after speaking to a banker.

**Comment by fvicaria** [comment]
Please follow the procedure described below before creating a new issue:
[How to Properly Report an Issue](https://github.com/wow-mania/Redemption/wiki/How-to-Properly-Report-an-Issue)

This will help developers identify and fix the issue quicker. Incorrectly or unclear reports will simply be deleted.

**Comment by fvicaria** [comment]
It has been fixed in dev. This will require client update. Probably next Wednesday.
