### ISSUE TITLE
Hunter's pet talent Culling the herd

### ISSUE THREAD

**Issue by Enmerkar75** [WoWManiaUK/Redemption#2432]
Hello, I noticed a little problem about a hunter pets' talent, I mean Culling the Herd, that is, when the pet scores a special ability, there is the possibility of a temporary increase in the attack power of 3%, but during the boss fight the pet can't bite (I refer to the wolf in particular), so I have never been able to notice this active talent; Now I don't know, is it a pet's bug, or is it normal for the pet not to be able to bite the bosses?
Thanks.

**Comment by TheManiax** [comment]
![image](https://user-images.githubusercontent.com/14857593/39130185-b8625394-4721-11e8-8072-80afe72eec98.png)
