### ISSUE TITLE
Sealed Chest.

### ISSUE THREAD

**Issue by AlbionSirzechs** [WoWManiaUK/Redemption#2434]
Greetings,

I am writing in reference to a new bug that I am dealing with at the moment.

I got Shadowmourne on my deathknight, and used the sealed chest I have the quest items in my bag but can see no NPCs to deliver those items to.

So basically I didn't enter the phase where I can see the NPCs.

Could you please confirm if this is a bug or not.

"Note I did the last chain quest before I get the sealed chest, because it didn't drop on the 25HC LK kill for some reason"

**Comment by fvicaria** [comment]
This happens because you left the raid or let its ID expire. This is as-is and not a bug.
Contact a GM and he will help.
