### ISSUE TITLE
NPCs and Objects disappear when moving from one "sub-zone" to another.

### ISSUE THREAD

**Issue by icswcshadow** [WoWManiaUK/Redemption#2436]
Been doing a quest chain to try getting my reputation for Sons of Hodir up, until I came across this. During the quest "You'll Need a Bear" I have to talk to an NPC called Brijana. However getting close to her causes her to disappear, more specifically once I leave the area of Brunnhildar Village. I made a quick video showing the problem. There is no way I can get to her as she disappears. (Also notice in the video that the Titanium Ore Deposit also disappears, this is something I've noticed with my Blacksmith/mining character as well that ore deposits would disappear).

https://puu.sh/Aavng/17a6a11449.mp4

**Comment by fvicaria** [comment]
This is because you missed a quest in the chain and are not in the correct phase.

**Comment by icswcshadow** [comment]
I don't think I have missed a quest, I followed that chain correctly. Like I said, I have noticed this strange behavior with Ore Deposits as well. Most notably in Zul'Drak with the Cobalt deposits.
