### ISSUE TITLE
[Spell] Lifebloom

### ISSUE THREAD

**Issue by Smazacik** [WoWManiaUK/Redemption#2437]
Hi, I've done some search and found this thread describing issues with the lifebloom spell. [Issue Nr. 2232](https://github.com/WoWManiaUK/Redemption/issues/2232). I have asked there 3 days ago but nobody responded. 
Is there any chance that someone will look into this issue again?

**Comment by fvicaria** [comment]
This is an issue in the core. A fix would require a big change.
I will try a hack today and if people test I can decide if I leave it or not.

**Comment by fvicaria** [comment]
Please re-check. It will either fix it or reverted and closed again as "won't fix"

**Comment by Dranah** [comment]
Retested - stacking lifebloom still only adds the base 776 value for each stack to the healing. No change.
