### ISSUE TITLE
Lord Valthalak

### ISSUE THREAD

**Issue by Sexeh** [WoWManiaUK/Redemption#2438]
I do the quest Line with Lord Valthalak and when i kill him i cant summon his spirit.

**Comment by gamer100** [comment]
http://www.wowhead.com/quest=8995/mea-culpa-lord-valthalak
It is about this  quest, I have tried  but the  spirit  dont show up

**Comment by Sexeh** [comment]
After 5 times i found a solution for this. You can use the amulet before loot the boss. I dont know how that is happening but is working.
