### ISSUE TITLE
[Spell] Power Word: Shield

### ISSUE THREAD

**Issue by kirilpanov** [WoWManiaUK/Redemption#2439]
The issue I`m reporting is very important, because it basically "killed" PVE discipline priest on the whole server.  It occurred since 17-18th April 2018. The problem is this - the Power Word: Shield is now abosrbing like 2.5-3 times less than it should be. In simple mathematics I`ll explain and show it with REAL numbers out of WoW. On my discipline priest 4/5 T10 set bonus, 6,100 gearscore. **Exactly same items, talents, glyphs and buffs, on the last version 2.3.1, axactly the same starting the game etc. BEFORE and AFTER** The "Glyph of Power Word: Shild" says: "Your Power Word: Shield also heals the target for 5% of the absorbtion amount." With this we can calculate how much is the absorbtion on the shield.  The mathematics on absorbstions:
With the 5% of the glyph we calculate:

5% * x = 100%;
x = 20; 
x is the the multiple to get the 100%;

Before the problem, before 17th April: **In Icecrown Citadel:**
5% healed = 1900 heal; so the total absorbtion = 38 000;

After 17th:  
5% healed = 620  =>  absorbtion = 12 500;

38 000 / 12 500  =  3 times less absorbtion.

Outside **Icecrown Citadel:**

Before 17th:
5% healed = 1100  => absorbtion = 22 000;

After 17th;
5% healed = 430  => 8600;

22 000 / 8 600  =  2.55 times less absorbtion. 

I seek out a solution to this problem. Now with those numbers Discipline Priest is unplayable.
It`s not only my character, it is the whole server. Every discipline priest is the same.

**Comment by Hajzlopuc** [comment]
It got actually fixed, it was bugged before.

**Comment by kirilpanov** [comment]
You don`t say. This was not what I was expecting. For me, and for every disc priest, this is not a great fix.

**Comment by medmonlolz** [comment]
Blame Hajzlopuc for that he killed disc priest :/
