### ISSUE TITLE
[Spell] Beacon of Light / Unchained Magic

### ISSUE THREAD

**Issue by xclaw800** [WoWManiaUK/Redemption#2440]
I have done extensive playing on this encounter and spec as well as checking retail kills to confirm my theory to be true. 
Beacon of light is either not coded properly or the way it’s paired with unchained magic is incorrect. 
In the Sindragosa fight if a holy paladin has beacon of light on a target and casts a Heal they will get 2 stacks of unchained magic. Based on this footage (look at 4:00) https://youtu.be/LVcWZ5hfhis
this is improper. The paladin should only receive 1 stack of unchained magic.

It is my theory that either beacon or light is coded as an entire spell cast for the person being healed by the beacon rather than it just mirror healing the person with beacon on them or it’s just a problem with beacon heals causing a stack of unchained on the paladin.

So to reiterate a holy paladin healing someone and having beacon of light on another target receives 2 stacks of unchained instead of just one which is what should be happening.

**Comment by fvicaria** [comment]
As-is.

**Comment by xclaw800** [comment]
May I ask what “as-is” means. I put research into it. If it can’t be fixed Bc of how we code beacon that’s fine just want to know.

**Comment by xclaw800** [comment]
If u want more proof I’ll find more proof btw. I know for a fact this is incorrect. If it can’t be fixed I have no problem with it. But I will find enough proof if needed.

**Comment by fvicaria** [comment]
I will get keader to have a look but this has been worked on already.

**Comment by Keader** [comment]
Tested today and working fine.
Now Beacon of Light effect will not proc unchained magic :)
