### ISSUE TITLE
Equipment Manager Not Switching Items Properly

### ISSUE THREAD

**Issue by xclaw800** [WoWManiaUK/Redemption#2441]
Equipment manager is saving items to sets properly but when trying to switch sets there will be multiple items not switched. 
I don’t want to say “make this a priority” but trust me everyone on the server is having a fit over this. 
Specific items I have noticed are ring and trinket for many people but others have said more than that have not switched when using the set manager.

**Comment by fvicaria** [comment]
has been fixed today

**Comment by xclaw800** [comment]
Ty

**Comment by xclaw800** [comment]
By the way. Now we can’t switch any items. Completely broken.

**Comment by fvicaria** [comment]
Need server restart. Will be done today.
