### ISSUE TITLE
game crush when trying to change haircut in game

### ISSUE THREAD

**Issue by TheSale** [WoWManiaUK/Redemption#2442]
It happen many times before, but I tought it was outdated patch or something, but 2 weeks ago I donloaded new game with new launcher, everything working and now I tried again to change haircut it crush.
I do use launcher to run game
I do have administrator privileges and run it as administrator
I did remove read only from folders and subfolders
I already did deleted wtf folder and cleared cache
and it happen more than once

pc is decent it can run wow without problems
processor intel core2duo e675
ram 2x2gb ddr3 1800mhz
vga radeaon saphite  hd 5750 1gb gdder5
hdd 320gb sata 200gb free

mega link is for video, I did not want to download any game recording software so I used my phone
https://mega.nz/#!Qd80QBwQ!8oqN9gvAN0lJ8S3cJI3YuMnNIMGTsLEFTXQCd29mux8

and this is screenshot of an error
[https://prnt.sc/jb6rpw](url)

**Comment by fvicaria** [comment]
Make sure you have our client fully updated. Also, some hairstyles may cause that. We cannot fix it. Ask a GM to flag you for re-customization.
