### ISSUE TITLE
[Spell] Glyph of Power Word: Shield

### ISSUE THREAD

**Issue by Ashamedlol** [WoWManiaUK/Redemption#2443]
Glyph is currently scaling by 5% of the absorb amount, instead of 20%.

Glyph: http://www.wow-mania.com/armory/?item=42408#created-by
Proof of it being 20% in old retail: https://wow.gamepedia.com/Glyph_of_Power_Word:_Shield (mentions a previous version on the Mists of Pandaria section).

**Comment by fvicaria** [comment]
Tooltip will still show 5% until client update but value has been fixed and is now 20%

**Comment by Dranah** [comment]
After my tests, it's actually 21% atm, but I guess we can disregard that minor difference.
