### ISSUE TITLE
[Spell] Earth Shield and talent synergies

### ISSUE THREAD

**Issue by Hajzlopuc** [WoWManiaUK/Redemption#2445]
Hello,

I would like to report issues with shaman's [Earth Shield](http://www.wow-mania.com/armory/?spell=49284) and its synergy with talents.

First I have reset all my talents. I had 2861 spell power (healing power) for the whole time while testing.

https://puu.sh/AcCW5/5cad7de860.jpg

**_1._**
Without any talents which improve healing or earth shield itself, earth shield proc healed me for 1699. Base heal of the spell is 337. Let's calc coefficient:
(1699-337) / 2861 = 0.47605 = 47.61%
This coeff seems to be wrong and should be 0.5371

**_2._** 
I have picked [Improved Shields](http://www.wow-mania.com/armory/?spell=51881) as my first talents.
Earth shield proc healed me for 1749.
1749/1699 = 1.029 = only **3%** difference, should be **15%**.
EDIT: Seems that only base value is boosted. 337*0.15=50.5 ; 1749-1699=50

**_3._**
I have picked [Improved Earth Shield](http://www.wow-mania.com/armory/?spell=51561) as my next talents. This talent stacks additively with Improved Shields (**_2._**) (That means not 1.15 * 1.10 but 1.15+0.10)
Earth shield proc healed me for 1783
1783/1699 = 1.049 = only **5%** difference, should be already **25%** with these 2 talents stacking additively.
EDIT: Seems that only base value is boosted. 337*0.25=84.25 ; 1783-1699=84

**_4._**
I have picked [Purification](http://www.wow-mania.com/armory/?spell=16213) as my next talents.
Earth shield proc healed me for 2157
2157/1783 = 1.2097 = **21%** difference, **too much**, should be **10%**. 
Seems to be double-dipping: 1.1 * 1.1 = 1.21 (I haven't tested this talent with any other spell yet, I'm focusin on earth shield now.)

**_5._**
I have picked [Glyph of Earth Shield](http://www.wow-mania.com/armory/?item=45775).
Earth shield proc healed me for 2588
2588/2157 = 1.1998 = 20% difference, this glyph seems to be **OK**.

Expected value with all these talents and glyph (step **_5._**) should be:
[337 + 2861*0.5371] * (1.15 + 0.10) * 1.1 * 1.2 = 3091 - it's almost 20% difference between expected and experienced value

**Comment by Keader** [comment]
1 - I dont have proof enough. But i'm checking with a friend about it.

2 - Is working. When you put the talent, remove current earth shield and apply other. You will see the value is correct.

3 - Correct too

**Comment by Hajzlopuc** [comment]
No, 2 and 3 is not working, I removed, applied new one, even relogged, still only base value is boosted.

**Comment by Hajzlopuc** [comment]
Base value of the spell - 337 in this case. No matter how much spell power I have, only number 337 gets multiplied by talents Improved Shields and Improved Earth Shield. (Talents completely ignore my spell power)

**Comment by Keader** [comment]
Sorry Hajzlopuc but cant be fixed.
First issue i'm sending fix to janitor, but nothing can be done for other ones.
Reason: Talents is working ! But how Spell System is working now, is making some spells "nerfed" and others "buffered".
It is part fixed in Trinity, but wow mania dont has this fixes yet.
