### ISSUE TITLE
Hidden chicken quest CLUCK! Can't be completed.

### ISSUE THREAD

**Issue by laminatefish** [WoWManiaUK/Redemption#2446]
Was asked to leave a bug report by a GM that has just helped me complete this quest. There is a hidden quest (http://www.wowhead.com/quest=3861/cluck) in Westfall at Saldeans Farm (probably works elsewhere this npc is, but I've always done it here).

1. Visit Saldeans Farm.
2. Create a macro containing "/chicken"
3. Target a wandering chicken (http://www.wowhead.com/npc=30379/westfall-chicken) and click your macro a lot. 
4. Eventually the chicken will "look at you quizically" (or something similar). Upon which, it offers the quest CLUCK!
5. Go to Saldean and buy the special chicken feed (http://www.wowhead.com/item=11109/special-chicken-feed).

At this point, the chicken that gave you the quest vanishes and it cannot be completed. It should have a "?" symbol and accept the food. Upon accepting the food, the chicken lays an egg, which becomes a Westfall Chicken companion (http://www.wowhead.com/object=161513/farm-chicken-egg).

Hope this is enough info!

**Comment by fvicaria** [comment]
![image](https://user-images.githubusercontent.com/9414661/39409555-1093afae-4be1-11e8-8926-d699c4bcba12.png)

**Comment by fvicaria** [comment]
You went for the wrong NPC. It's http://www.wow-mania.com/armory/?npc=620


![image](https://user-images.githubusercontent.com/9414661/39409725-13501a7c-4be4-11e8-8287-339b8d8d77a0.png)

**Comment by laminatefish** [comment]
That's weird, as I've always done the quest in Westfall. In fact, that link shows that that NPC is at Saldeans Farm also. Nevermind, as long as it's working. Didn't for me, without the aid of a GM
