### ISSUE TITLE
[Quest] "The Eye of Haramad"

### ISSUE THREAD

**Issue by moontouched** [WoWManiaUK/Redemption#2447]
Hello,

I would like to report an issue with the quest [The Eye of Haramad](http://www.wow-mania.com/armory/?quest=10982). The quest is not available for taking. Confirmed by 2 GMs in-game.

Steps to reproduce:
1. Be revered with [The Consortium](http://www.wow-mania.com/armory/?faction=933)
2. Go to the [Protectorate Watch Post](http://www.wow-mania.com/armory/?zone=3854) in [Netherstorm](http://www.wow-mania.com/armory/?zone=3523#subzones)
3. Take the quest [A Thousand Worlds](http://www.wow-mania.com/armory/?quest=10973), complete it and turn it in.
4. Take the quest [Stasis Chambers of Bash'ir](http://www.wow-mania.com/armory/?quest=10974) and turn it in.
5. You are now offered a repeatable quest: [Purging the Chambers of Bash'ir](http://www.wow-mania.com/armory/?quest=10975). Repeat untill you get a [Mark of the Nexus-King](http://www.wow-mania.com/armory/?item=31941)
6. Complete the quest [The Mark of the Nexus-King](http://www.wow-mania.com/armory/?quest=10976)
7. Take the quest [Stasis Chambers of the Mana-Tombs](http://www.wow-mania.com/armory/?quest=10977) and complete it.
8. Go back to [Image of Commander Ameer](http://www.wow-mania.com/armory/?npc=20482), he only offers the repeatable quest [Purging the Chambers of Bash'ir](http://www.wow-mania.com/armory/?quest=10975)
9. No other quest available.

How it should work:
At step 8. after returning to [Image of Commander Ameer](http://www.wow-mania.com/armory/?npc=20482) you should be offered one of two quests according to your reputation standings with [The Consortium](http://www.wow-mania.com/armory/?faction=933)
1. If revered - the quest [Nexus-Prince Shaffar's Personal Chamber](http://www.wow-mania.com/armory/?quest=10981) which is a repeatable quest, granting a one-time key to summon the boss [Yor](http://www.wow-mania.com/armory/?npc=22930) in Mana Tombs.
2. If exhalted - the quest [The Eye of Haramad](http://www.wow-mania.com/armory/?quest=10982) which grants a permanent key to the boss chamber.

I wrote an in-game ticket about the issue (when i was at step 8.) and Metaxa answered me. He checked my log and said i'm missing a quest in the chain - [Nexus-Prince Shaffar's Personal Chamber](http://www.wow-mania.com/armory/?quest=10981). He confirmed he cannot take it aswell, so he added the quest to my log.
After completing the quest, i still had no access to [The Eye of Haramad](http://www.wow-mania.com/armory/?quest=10982) so i wrote another ticket, an update. 
I dont remember the GM's name, but he confirmed, after doing the quest chain himself, that he also has no quest available at step 8. and he redirected me to github.

Using wow-mania's client.
Using latest Launcher version.
Race: Gnome
Class: Mage
Nick: Moontouched

**Comment by fvicaria** [comment]
![image](https://user-images.githubusercontent.com/9414661/39410314-b533a7d2-4bee-11e8-8460-dbdfc2138478.png)

**Comment by moontouched** [comment]
yes, i CAN accept it
but the NPC does NOT offer it

**Comment by moontouched** [comment]
I am exhalted.

**Comment by moontouched** [comment]
![wowscrnshot_042918_230206](https://user-images.githubusercontent.com/36900407/39410477-72f83a14-4c01-11e8-8b61-beca104b4bcd.jpg)
![wowscrnshot_042918_230215](https://user-images.githubusercontent.com/36900407/39410478-73dc3bf6-4c01-11e8-9035-956ac5965b0b.jpg)

**Comment by moontouched** [comment]
This is how it looks like for me, a yellow question mark with only the repeatable quest open. No other options

**Comment by Zunrin** [comment]
Ah my bad i just saw you said you CAN accept it so i thought you had it.
I'll try the chain as soon as i can.
