### ISSUE TITLE
[Object] Ethereum Prison

### ISSUE THREAD

**Issue by moontouched** [WoWManiaUK/Redemption#2448]
Hello,

I would like to report an issue with the [Ethereum Prisons](http://wowwiki.wikia.com/wiki/Ethereum_Prison) in [Netherstorm](http://www.wow-mania.com/armory/?zone=3523).

Issue is: once you open a prison cell and get a friendly NPC you are not granted reputation as reward.

Steps to reproduce:
1. Be honored with [The Consortium](http://www.wow-mania.com/armory/?faction=933)
2. Go to the Protectorate Watch Post in [Netherstorm](http://www.wow-mania.com/armory/?zone=3523).
3. Get the quest [A Mission of Mercy](http://www.wow-mania.com/armory/?quest=10970) and complete it.
4. Get the quest [Ethereum Secrets](http://www.wow-mania.com/armory/?quest=10971). You can now use [Ethereum Prison Keys](http://www.wow-mania.com/armory/?item=29460)  to open up prison cells.
5. When a prison is opened, either a friendly mob will come out ( and SHOULD give rep, but it doesnt), or a level 71 non-elite hostile mob will come out.

I was farming my Consortium reputation via those prison quests and i opened over 60 cells, none of the friendly mobs coming out gave me any reputation.

Using the wow-mania client.
Using latest Launcher version.
Race: Gnome
Class: Mage
Nick: Moontouched

**Comment by fvicaria** [comment]
Please if you get one wrong chances are you need to go back a step and retrace your steps.

**Comment by moontouched** [comment]
i'm not sure i get what you mean

**Comment by fvicaria** [comment]
Don't use wowwiki or wowhead. Use armory to check as much as possible.
Objects are rarely an issue. What is more likely to be is a missing condition.
Also, make sure you have the correct key. I have done these myself and they work.

**Comment by fvicaria** [comment]
![image](https://user-images.githubusercontent.com/9414661/39410423-f14314fa-4bef-11e8-88ea-6b6b08eed055.png)
![image](https://user-images.githubusercontent.com/9414661/39410428-ff030f64-4bef-11e8-837d-b9c7dd179960.png)

**Comment by moontouched** [comment]
They work. but the NPCs that you free, the friendly ones are supposed to reward you with 250-500 reputation to a certain fraction they belong to. BUT they do not

**Comment by moontouched** [comment]
For example, you find a Consortium Dealer inside the prison - he rewards you 500 Consortium reputation.
This is how it should be, but its not

**Comment by moontouched** [comment]
Okay, my bad. I did not open the issue correctly, it should be about the NPCs that are inside, not the Object itself but i wasnt sure how to post it

**Comment by fvicaria** [comment]
What is wrong with the NPC?

**Comment by fvicaria** [comment]
Where did you get that info from?

**Comment by moontouched** [comment]
When you open a Prison cell you get either a hostile mob or:
Known friendly mob factions are:

    Cenarion Expedition (Rescued Cenarion Expedition Druid - 500 rep)
    Consortium (Rescued Consortium Dealer - 500 rep)
    Keepers of Time (Rescued Keepers of Time Custodian - 500 rep)
    Lower City (Rescued Lower City Brute - 500 rep)
    Sporeggar (Rescued Sporeggar Scout - 450 rep)
    Sha'tar (Rescued Sha'tar Vindicator - 500 rep)

**Comment by moontouched** [comment]
http://www.wowhead.com/item=29460/ethereum-prison-key#comments first comment

**Comment by moontouched** [comment]
here it is in wowwiki aswell : http://wowwiki.wikia.com/wiki/Ethereum_Prison
or a youtube video showing how it works: https://youtu.be/WQPBa2-jsrs?t=115 - a short monolog, an animation, looking like Arcane Explosion - boom you get 500 rep (see chat)
