### ISSUE TITLE
[BOSS] Blackheart the Inciter

### ISSUE THREAD

**Issue by moontouched** [WoWManiaUK/Redemption#2449]
Hello,

I would like to report an issue with the boss [Blackheart the Inciter ](http://www.wow-mania.com/armory/?npc=18667) in Shadow Labyrinth.
He is either taking much less damage than he is supposed to or he has an "invisible" 1.3M hp bar.
Issue is present on both normal and heroic difficulty.
![wowscrnshot_042918_235318](https://user-images.githubusercontent.com/36900407/39410958-246a95ce-4c09-11e8-8682-4157dadae361.jpg)
![wowscrnshot_042918_235335](https://user-images.githubusercontent.com/36900407/39410960-25de3ef6-4c09-11e8-8098-25dca7d2501a.jpg)
![wowscrnshot_042918_235340](https://user-images.githubusercontent.com/36900407/39410962-27963122-4c09-11e8-8d40-ef26e7f28178.jpg)
![wowscrnshot_042918_235351](https://user-images.githubusercontent.com/36900407/39410963-28ba0812-4c09-11e8-8adf-f65d2ddf6bb6.jpg)
![wowscrnshot_042918_235416](https://user-images.githubusercontent.com/36900407/39410965-2a0f3a02-4c09-11e8-9f12-fcefa881e546.jpg)
![wowscrnshot_042918_235456](https://user-images.githubusercontent.com/36900407/39410966-2b25c62c-4c09-11e8-9344-cb12f074392a.jpg)

Look at the amount of damage i deal and the amount of HP his HP bar decreases by.
His HP bar decreases by about 10% of the damage i deal.

**Comment by fvicaria** [comment]
As-is. For this boss it doesn't matter how much damage you think you do in one hit. What counts is the number of hits as it will absorb anything passing 0.5% of his max health.

**Comment by moontouched** [comment]
Okay. It shouldnt be like that

**Comment by fvicaria** [comment]
All references you find now are as it is in retail today. Also old content need restrictions to over damage as they were not made to be solo'ed by level 80's. This will cause the NPC to skip phases and sometimes bug.
