### ISSUE TITLE
[Object] Arcane Containers - Karazhan

### ISSUE THREAD

**Issue by singhprasanna** [WoWManiaUK/Redemption#2453]
The quest Entry Into Karazhan, part of the Karazhan key quest chain, requires First Key Fragment dropped by the First Fragment Guardian. This is supposed to spawn when the Arcane Container in Shadow Labyrinth is used. It is not spawning the guardian and hence the quest cannot be completed.

**Comment by TheManiax** [comment]
[[Entry Into Karazhan]](http://www.wowhead.com/quest=9831/entry-into-karazhan)
**How it should work:**
The Object [[Arcane Container]](http://www.wowhead.com/object=182196/arcane-container) Is meant to contain summon an elemental on use, which will drop [[First Fragment Guardian]](http://www.wowhead.com/item=24514/first-key-fragment)
**How it works:**
Opening the  [[Arcane Container]](http://www.wowhead.com/object=182196/arcane-container) is not summoning the elemental, thus the player can not kill and loot the item required to complete the quest.

**Comment by fvicaria** [comment]
All 3 fixed. Should be deployed tomorrow morning.
![image](https://user-images.githubusercontent.com/9414661/39522415-08fff704-4e0a-11e8-8731-069eb0ec7925.png)
