### ISSUE TITLE
[Quest] Flight of the Wintergarde Defender

### ISSUE THREAD

**Issue by squalllh1989** [WoWManiaUK/Redemption#2455]
["Flight of the Wintergarde Defender".]( http://www.wow-mania.com/armory/?quest=12237) in this quest there should be [Helpless Wintergarde Villager](http://www.wow-mania.com/armory/?npc=27315), so you can gap them on your gryphin and complete the quest like how it is done (sample video of how it should work [here](https://www.youtube.com/watch?v=lF_OCW9WIHA)).
- How it work right now: currently no Helpless Wintergarde Villager arround for you to rescure, so this quest is undoable.
I already do the prequest needed in the line so it should not be phase issue:
![wowscrnshot_050318_165909](https://user-images.githubusercontent.com/27235989/39570947-1e756ff2-4ef4-11e8-88d3-d2dad409f969.jpg)

**Comment by fvicaria** [comment]
You have a bad phase they are there.

**Comment by squalllh1989** [comment]
the problem is that: 
1. This is a new char, created and didn't do any quest to be phased out of the right phase to do this quest
2. I already do the pre quest in the line for this one
So if there is a bad phase problem in this, then it is what the quest is bugged, and that is what needed to be fix. If this normally didn't happen and will only happen when you do a quest that phase you out then it's your problem because you get yourself into that phase to do something, but this isn't the case.

**Comment by squalllh1989** [comment]
just try to do this quest again when leveling new char, the helpless village still isn't there
