### ISSUE TITLE
no gold in loot from PoS

### ISSUE THREAD

**Issue by Sophraves** [WoWManiaUK/Redemption#2460]
Hi,

I'm running PoS Hc and notice no mob, not even the first boss, Garfrost, dropped gold in loot after killing them.
I checked FoS Hc, there the mobs do drop gold.
As far as I remember, these mobs and certainly all bosses drop gold as this was a steady source of income.
As it's Hc, I cannot reset and try again.
Yesterday i noticed the same problem in PoS Hc, but did not kill any boss to confirm it was a bug.

Happy to help if possible...
Thanks in advance for your effort!

Kind regards,
Soph

**Comment by fvicaria** [comment]
Please follow the procedure described below before creating a new issue:
[How to Properly Report an Issue](https://github.com/wow-mania/Redemption/wiki/How-to-Properly-Report-an-Issue)

This will help developers identify and fix the issue quicker. Incorrectly or unclear reports will simply be deleted.

**Comment by fvicaria** [comment]
I checked and Garfrost drops almost nothing which explains you getting nothing.
Please check our armory or wowhead (second option) as a source for your info.

https://www.wowhead.com/npc=36494/forgemaster-garfrost#drop-currency

**Comment by Sophraves** [comment]
Hi Janitor,

Sry for the late reply, didn't notice your email until just now.
I know he drops only a little, but its not just the boss, I got 0 gold from
the entire run, several times now in a row.
The same happenend in Culling of Stratholme, 0 gold from an entire run.
FoS on the other hand gave gold every time.

I suspect something could be wrong because it is very unlikely to loot 0
gold over an entire run repeatedly.
Playing this server for several years now, I'm still amazed how well so
much works. (I know what you start from as i tried running my own server
once)
Keep up the excellent work :-), I do not intend to complain about your hard
work, just trying to help you make it even more awesome!


Kind regards,
Soph.


2018-05-05 19:07 GMT+02:00 Janitor <notifications@github.com>:
