### ISSUE TITLE
[Quest] If He Cannot Be Turned not functioning correctly

### ISSUE THREAD

**Issue by stealer0517** [WoWManiaUK/Redemption#2461]
http://www.wowhead.com/quest=12897/if-he-cannot-be-turned

When you use the General's Weapon Rack to spawn Lightbane all of the ai characters spawn correctly, however Lady Nightswood tends to not attack, Vile doesn't hold aggro correctly and dies quickly, and every time that I've killed Lightsbane I don't get credit for it.

I should be able to spawn Lightbane, have Vile show up to tank him, and with the help of the other AI down him without getting much aggro (outside of the beginning). 
Instead I'll attack Lightbane 2 or 3 times after Vile spawns and I'll have aggro on me the whole time. If I try to run and let Vile get aggro he dies very quickly, and if I try to attack at all I get aggro and die. If I kite Lightbane around until the other AI get him to almost dead, then attack him I wont get credit for the kill.

**Comment by TenmanWoW** [comment]
I'm lookign into it.

**Comment by TenmanWoW** [comment]
So, I just finished looking into it. 

1) Vile is dying after 5 hits. His "tanking" abilities work but he only has 25.2k HP (non elite) and Lightbane is hitting for 5k+ a swing.

2) Confirming Lady Nightswood does spawn and attack correctly. Tested 4 times and no problems.

3) As for the aggro issue, confirming that virtually any action I performed drew Lightbane's attention.

4) I recieved credit just fine all 4 times for killing Lightbane.

**Comment by fvicaria** [comment]
OK, hard does not mean it doesn't work. Every assisted combat requires the player to do at least 50% of the damage. If any of the NPCs are doing too much damage or has too much health please describe it. Otherwise, I see nothing here to consider this broken.

**Comment by TenmanWoW** [comment]
For OP,

Credit was recieved for completion.

[https://i.imgur.com/x4CyBoK.jpg](url)

**Comment by TenmanWoW** [comment]
![wowscrnshot_050618_151922](https://user-images.githubusercontent.com/25806987/39677614-c7eb1360-5143-11e8-8f48-9e60e96cc949.jpg)

**Comment by stealer0517** [comment]
Did you fix Vile not being able to hold aggro?

**Comment by fvicaria** [comment]
There is nothing to fix. The quest works. You just need to work it out. As I said you are the one doing the fight not the assisting NPC.

**Comment by stealer0517** [comment]
You can't do the fight if you instantly get aggro and he kills you right away.
This is not a 3+ quest where you'd need help from another player to complete it.
It's the help that you already have that does not function correctly.

**Comment by fvicaria** [comment]
Then send me reliable 3.3.5a info saying that.

**Comment by stealer0517** [comment]
Before I waste a bunch of my time because you're too damn lazy, what do you consider a reliable source?
Would testing this out on multiple other servers be good? Or would I have to go back in time, record a video of me completing this quest on an official blizzard server back in 3.3.5 because all the damn videos from that time are horrible?
