### ISSUE TITLE
quel'delar enter sunwell bug

### ISSUE THREAD

**Issue by rekachu** [WoWManiaUK/Redemption#2462]
I am doing the quest "the purification of quel'delar" and i am standing in front of the entrance to sunwell. When i talk to the guards there, as the quest says, the screen closes and it will not let me in. This happens with both guards. Could u take a look at this?

Kind regards 
Rekachu

**Comment by fvicaria** [comment]
PLease search for the NPC.

**Comment by Zunrin** [comment]
You need to be in a raid group for it to work (just invite anyone and set the group to raid)

**Comment by rekachu** [comment]
Ok, thank you for the help!

Grt Rekachu

Verzonden vanuit Mail<https://go.microsoft.com/fwlink/?LinkId=550986> voor Windows 10

________________________________
Van: Zunrin <notifications@github.com>
Verzonden: Sunday, May 6, 2018 10:43:56 PM
Aan: WoWManiaUK/Redemption
CC: rekachu; Author
Onderwerp: Re: [WoWManiaUK/Redemption] quel'delar enter sunwell bug (#2462)


You need to be in a raid group for it to work (just invite anyone and set the group to raid)
