### ISSUE TITLE
[NPC] Taretha

### ISSUE THREAD

**Issue by WhosetheBost** [WoWManiaUK/Redemption#2464]
[http://www.wowhead.com/npc=18887/taretha](url)

In the dungeon Old Hillsbrad Foothills [http://www.wowhead.com/old-hillsbrad-foothills](url) players escort Thrall all the way to the inn, where he meets Taretha upstairs. Players should be able to choose the dialogue option that says "We'll get you out, Taretha. Don't worry. I doubt the wizard would wander too far away." Clicking this dialogue option should trigger the appearance of the final boss of the dungeon.

Clicking this dialogue option currently has no effect, preventing players from finishing the dungeon.

**Comment by fvicaria** [comment]
This actually works. There is an issue with the menus. 
The first time you open it you should click on the second option (should be the only one but it is not)
Then you click on the following option that is "We'll get you out, Taretha. Don't worry. I doubt the wizard would wander too far away." 
I will fix it today
