### ISSUE TITLE
[Boss] ICC's Lady Deathwhisper

### ISSUE THREAD

**Issue by Ashamedlol** [WoWManiaUK/Redemption#2466]
The Reanimated Adherent gains a buff called [Adherent's Determination] which causes him to be almost immune to magical damage (99% reduction), while the Reanimated Fanatic gains [Fanatic's Determination] which causes him to be almost immune to physical damage (99% reduction). This mechanic does not exist right now.

NPC ID:  http://www.wow-mania.com/armory/?npc=38009 (Reanimated Fanatic).
http://www.wow-mania.com/armory/?npc=38010 (Reanimated Adherent).
Spell ID:
http://www.wow-mania.com/armory/?spell=71235 (Fanatic's Determination) 
 http://www.wow-mania.com/armory/?spell=71234 (Adherent's Determination).

Second part is, after stunning the adds as/while they cast Dark Martyrdom they are standing still for the whole fight and doing nothing (no attacks, no spells), just because they got stunned during that spell.

**Comment by fvicaria** [comment]
Fixed in dev. Please check it.

**Comment by Ashamedlol** [comment]
The buffs now work accordingly, but the stun part is still bugged.

A new unnoticed thing:  [Dark Empowerment] and  [Shroud of the Occult] should make adherents immune to interupts.

Spell ID of Shroud: http://www.wow-mania.com/armory/?spell=70768
Spell ID of Dark Empowerment: http://www.wow-mania.com/armory/?spell=70901

**Comment by Ashamedlol** [comment]
http://www.wow-mania.com/armory/?spell=70674 is not healing the Fanatics.

**Comment by Ashamedlol** [comment]
Correction: Adherents are immune to the stun part, fanatics are the ones who freeze.
