### ISSUE TITLE
The Great Silver Deceiver: Quest

### ISSUE THREAD

**Issue by tecnoturc** [WoWManiaUK/Redemption#2467]
The quest is The Great Silver Deceiver from Galvin The Ancient in Stranglethorn Vale. The quest requires 40 mithril bars and 5 truesilver bars.

- I have all of the materials needed to cash quest.
- The questgiver doesn't have a golden questionmark above his head.
- After talking with him, the quest list has my quest with a golden question mark suggesting i can cash it in.
- Selecting the quest, the "continue" button to complete the quest isn't able to be clicked.

![untitled 2](https://user-images.githubusercontent.com/38804068/39939490-7628c29a-5524-11e8-8438-e2ed96cb93bf.png)
![untitled 3](https://user-images.githubusercontent.com/38804068/39939491-7641bdea-5524-11e8-9ea3-ddf57aaa9c2c.png)
![untitled](https://user-images.githubusercontent.com/38804068/39939492-76575844-5524-11e8-9c68-d30824238e17.png)

**Comment by TenmanWoW** [comment]
Tested from preamble up to and including the turn in for the quest in question. No bug found.

![wowscrnshot_051118_140730](https://user-images.githubusercontent.com/25806987/39942439-201efde6-5525-11e8-82b0-d5ccd59ba1ab.jpg)

![wowscrnshot_051118_140732](https://user-images.githubusercontent.com/25806987/39942443-23dc4bd2-5525-11e8-856a-b028ddc95320.jpg)

![wowscrnshot_051118_140738](https://user-images.githubusercontent.com/25806987/39942448-25e455a0-5525-11e8-87a3-c8e0fd07f674.jpg)

**Comment by fvicaria** [comment]
It can happen sometimes. If the client fails to update. To solve this drop the question, close client, delete cache, relog and try it again.
