### ISSUE TITLE
The Art of the Imbue: Quest

### ISSUE THREAD

**Issue by tecnoturc** [WoWManiaUK/Redemption#2468]
The quest is The Art of the Imbue from Galvin The Ancient in Stranglethorn Vale. The quest requires 40 mithril bars and 4 citrine.

- I have all of the materials needed to cash quest.
- The questgiver doesn't have a golden questionmark above his head.
- After talking with him, the quest list has my quest with a golden question mark suggesting i can cash it in.
- Selecting the quest, the "continue" button to complete the quest isn't able to be clicked.

![untitled 2](https://user-images.githubusercontent.com/38804068/39939974-cc131240-5525-11e8-9ce8-6b9a9fa3b407.png)
![untitled 3](https://user-images.githubusercontent.com/38804068/39939975-cc29b78e-5525-11e8-997e-553da4452bf8.png)
![untitled](https://user-images.githubusercontent.com/38804068/39939976-cc492e84-5525-11e8-8a10-5f30a966a79a.png)

**Comment by fvicaria** [comment]
Never collect material for multiple quests at the same time. Drop the quest and then get the material.
