### ISSUE TITLE
[Quest] Territorial Trespass

### ISSUE THREAD

**Issue by GMLucetta** [WoWManiaUK/Redemption#247]
wow-mania.com/armory/?quest=1305

Players place wow-mania.com/armory/?item=4279 into the nest and npc wow-mania.com/armory/?npc=30461 is supposed to appear. This does not happen and players cannot complete the quest.

**Comment by wow-mania** [comment]
Fixed for next update. Wait for a while and look up.

**Comment by Calebrimbor** [comment]
The dragon takes 5-12 minutes to arrive. Reopened the issue.

**Comment by RyogoKusama** [comment]
As of 10th february 2020, this quest is still bugged/broken, I attempted twice to complete it today, but the first time after placing the eggs the required dragon did not spawn, even after waiting the 5-12 minutes claimed in an old comment from 2016, I then abandoned and picked the quest back again, and this second time the dragon appeared out of nowhere with Thorim already on, after the 20th minute mark.

**Comment by wow-mania** [comment]
Please do not reopen issues because someone mentioned it doesn't work without confirming..
I am pretty sure this should work.

**Comment by Kitzunu** [comment]
I opened it so somebody can confirm it.
It is useless if it is closed because then nobody will even look at it

**Comment by wow-mania** [comment]
Don't just reopen it without confirming.

**Comment by wow-mania** [comment]
Re-open when confirmed. I got reports of people completing it a couple of days ago.

**Comment by gamer100** [comment]
Quest is working, but you just have to be patient

**Comment by Kitzunu** [comment]
It actually is bugged but I won't dare to reopen this so I asked Rushor in a DM to fix this if he can :)

**Comment by gamer100** [comment]
It is working i just did it

**Comment by Kitzunu** [comment]
I am not saying it isn't working xD I am saying it is bugged.

There are a lot of visual shit and movement that is super off from what Retail has :)

**Comment by RyogoKusama** [comment]
> Don't just reopen it without confirming.
> 
> https://cdn.discordapp.com/attachments/530718279396753408/676531286151790622/unknown.png

In my report I never said you could not complete it, I explained exactly what is going on and how is it bugged/broken, you shouldn't have to wait 10+ minutes for a quest to complete itself out of nowhere, it shouldn't work like that.
