### ISSUE TITLE
[Quest] Dun-da-Dun-tah!

### ISSUE THREAD

**Issue by cathyr1** [WoWManiaUK/Redemption#2470]
Found another bugged quest: http://www.wow-mania.com/armory/?quest=12082. After taking the quest the NPC simply remained on his position and didn´t move forward.
![1](https://user-images.githubusercontent.com/30184491/39966242-8f98f8fa-56a8-11e8-8227-87f2cf1d43a8.png)

**Comment by TheManiax** [comment]
The quest works fine.
Please make sure you are using wow-mania launcher to update to the latest patch and clear catch before running the client.
![image](https://user-images.githubusercontent.com/14857593/39966344-99b93e96-56bf-11e8-95f1-30cd7accd3e3.png)

**Comment by cathyr1** [comment]
I´m using everything you mentioned. I brought a friend who picked up the quest and then it worked in group so I did it at last. Dunno why it had not worked when picked up in the first time.
