### ISSUE TITLE
Felguard's melee hit range

### ISSUE THREAD

**Issue by TheSale** [WoWManiaUK/Redemption#2472]
This bug is occurring to me for a 2 weeks already and I was not in a mood to report it, but couple people confirmed that they have same issue as I do, so I decided.
https://mega.nz/#!dI0HBbTQ!xOOF7EYgN-gNYhGmbUrsTXYkmaKzh8OL7vfvPK7TE1Y
https://mega.nz/#!hJ0B3LrJ!SKIL5Mugh5ILvy11LNLdCGdNKXeunr1MEYuB83oTzaE
https://mega.nz/#!oR9HVBAC!8M3i1NfSeuZzjJz4yQIyEyqyHqEfQw01sbUKOC7xwDs
https://mega.nz/#!kMdU3YyT!3xgXeoaxOkfGR5i_O9gOM1Gn1LnQGIgwkEOLFzp9n_Q

there are 4 clips I managed to take, in other occurrences eater I die, or mob/boss die before I can record.
I tried to reproduce but it wont always happen.
However during my attempts to reproduce bug I think I found what is an issue
https://mega.nz/#!9JsiRBoC!zIjiVJvzkuWggobffknjujLJG3MotW-5w1kB45qvrNg

training dummies in sw do not reproduce non attacking,  but it show that he stand way out of range of targets, he dont stand behind dummies, he stand on the wall, and when I send him to another dummies where he dont have room to stand behind, he enter the house and just stand.

I think that he is set to be on max melee range from npc, and in some occasions hit box of boss is offset from his range, so he just end up standing even he get attacked by mob.

I am sorry for por quality of videos and lack of proffesionalism, I just want to help, get rid of bugs and enjoy the game.
P.S. I am using newest game client and launcher.

**Comment by Keader** [comment]
without a way of reproduce it, is impossible fix.

**Comment by WhitephoenixTheBunny** [comment]
Keader, I tried last night, on some of the bosses on the video and my felguard always was attacking. I asked for a re-test.

**Comment by TheSale** [comment]
well again I am sorry for poor quality of videos, and for not enough of info
but I was playing game, having fun, also trying to do my job in raid,
or I cant record while we fight or it is too late to record

https://mega.nz/#!4Q1mjSya!CXwsf4RuEOAIdO_h4qwWDGfUrJ9Ec4x-jxdYQkjQaTM

this video is from valkyre before valithria it is short and I tried to record combat log but I kinda failed
but you can se that felguard just standing behind valkyre do not attack

I had same problem on fest and rot but I walked to a boss and tried to move felguard into range for attacks and it worked.
however I dont think that I should risk and bring vile gas in melee or somehow to endanger whole raid.
And lose dps while I am doing that.

I did not test on thise fights but in some fights like sindragosa, pp or lk where is a lot of movement of the boss and mechanics involved
I cant use intercept and to walk in boss so my pet attack

**Comment by Keader** [comment]
Well i need something to reproduce it to try find what's wrong.
Without it, is impossible fix.
Make a new issue if someone find a way to reproduce it.

**Comment by TheSale** [comment]
uhhh I dont know with who I was in test realm for an hour testing on dolls and gm confirmed that pet do not attack big dolls in mall, and in stormwind pet go in house and stand inside, and even gm found that voidwalker have a same issue that I didnt even know....

I asked many demonology warlock players and all of them are aware off issue that pet sometimes do not attack, they just get used to it and try to position pet so it attack or they use different pet.

I will also use different pet from now or I wont play demonology at all.
However I decided to put last effort in trying to help to solve this issue even you already anounce closed and cant reproduce even we did reproduce. But if GM and dev dont care about this I could care even the less.

I installed obs but I did not set up it properly so it is kinda low quality and I have lot of stuff runing in background so it preformed really bad, but it can give some prof of what is going on, and in how many situations pet did not attack in one istance

https://mega.nz/#!gdNxWBoJ!Ml9P60AJlYOTZLQ2dTQGlGK19PYDQ0cSEeo2NstTyNI

I think that felguard on each boss had period of not attacking, I even tried to call pet back and send it again.
And after dungeon I go to mall again, and recorded pet behavior with dolls, and give some recount info.
Overall data can be miss leading coz I did use pet om dolls, but on last dragon boss in nexus, my pet only did about 4k dmg 1 cleave and 1 basic attack for entire fight.

even tough intercept can be helpful and make your pet attack, but sometimes it wont, or sometimes you cant use it, pet is not too far so it cant intercept, or he is out of mana, or it is on cooldown

Anyway Good Luck guys :)

**Comment by TheManiax** [comment]
@Keader 
**How to reproduce:**
1-Summon a big dummy in middle of a room (to make sure it's not about the wall behind it)
2-Stay in front and away from dummy (like 10 yard)
3-Send the felguard to attack it (Ctrl+1)
3-Felguard will try to go behind the dummy. While Felguard is passing (walking **Through**) the dummy, he will do 1 or 2 hit until he reaches the spot where he stops, that spot is 6.7 yard away from the dummy.
![image](https://user-images.githubusercontent.com/14857593/40169426-39dabd64-59db-11e8-9a63-427571b5ce34.png)
That's the spot where Felguard will stop doing melee.
Incase you try to use one of Felguards abilities (i.e. Cleave), you will get the "Your pet is out of range" message.
![image](https://user-images.githubusercontent.com/14857593/40169327-02180b70-59db-11e8-9b33-04e6b4f87ae6.png)

-----
Testing different cases, I got to this;
Felguard stands behind his target in a distance that is:
Target's combat reach + 4.25 yard
And I think Felguard's melee hit range is lower than 4.25
So, incase Felguard stands in a closer range (using intercept / follow / stand ... ) he will be able to attack the target, else he won't be able to do any attack.
No need to say how much this can effect the Demonology spec.

**Comment by Keader** [comment]
@TheManiax Test if you can reproduce in ptr now 💃

**Comment by TheManiax** [comment]
Good job!

**Comment by Keader** [comment]
Thanks.
See @TheSale
We just need a way to reproduce. 😄

**Comment by TheSale** [comment]
all thanks to the @TheManiax :) 
really good job with report! I am impressed! :)
