### ISSUE TITLE
[Quest] The Last Line Of Defense

### ISSUE THREAD

**Issue by knoblobster13** [WoWManiaUK/Redemption#2474]
http://www.wowhead.com/quest=13086/the-last-line-of-defense

In this quest 2/4 of the turrets are inside the tower, and kind of hard to get out of if you get on them.
Fairly obviously they should be on top of them like the other 2.

![wowscrnshot_051318_200935](https://user-images.githubusercontent.com/39036622/39973910-89a47f7c-56ea-11e8-95a0-17cb865dcd13.jpg)
![wowscrnshot_051318_201033](https://user-images.githubusercontent.com/39036622/39973911-89b41158-56ea-11e8-9c5f-c04668da3c0e.jpg)
![wowscrnshot_051318_201038](https://user-images.githubusercontent.com/39036622/39973912-89c079a2-56ea-11e8-8a6e-af5d8b8fbac5.jpg)

**Comment by fvicaria** [comment]
Will be ok after restart
