### ISSUE TITLE
[Quest] Garments of Spirituality - Grunt Kor'ja Issue

### ISSUE THREAD

**Issue by corywormhole** [WoWManiaUK/Redemption#2475]
Grunt Kor'Ja accepts the healing and fortitude required by the quest, and responds with a 'thank you' message, but the objective does not update, unable to turn in quest.

**Comment by WhitephoenixTheBunny** [comment]
You need fortitude and after healing... Quest a bit messed up, but doable.

**Comment by fvicaria** [comment]
This is working as intended.

**Comment by corywormhole** [comment]
Sorry but I still don't understand how this works. I have Power Word: Fortitude and Lesser Heal, using them in either order on Kor'Ja is not working for me.
