### ISSUE TITLE
Can't buy with MP

### ISSUE THREAD

**Issue by Kezzas** [WoWManiaUK/Redemption#2476]
![1](https://user-images.githubusercontent.com/39270002/40003145-3bd1d7d4-579b-11e8-9b10-10adcbd0bf31.jpg)
Realm: Redemption
IGN: Kezzas
Level: 48
Riding level: 150
MP: 71

Can't buy a mount in the MP shop.

**Comment by WhitephoenixTheBunny** [comment]
You need Vote Tokens to buy those mounts.
