### ISSUE TITLE
[Spell] Innervate

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#2479]
SPELLID 29166

Spell generates very high numbers of threat.

How it should work:

- Power gains (such as mana) should generate 0,5 threat points per power gained. (IF it is meant to generate threat at all)

- Threat generated should be split among all targets who have the caster on their threat list
Quote from wowwiki:
"Threat caused by beneficial effects is divided amongst all NPCs that are aware of the character. This global threat applies to heals, bonus threat from buffs (such as Battle Shout or Arcane Brilliance), and power gains (such as a Mana Potion or Rage Potion). "
Example: if there are 5 mobs in a trash-pack and the druid innervates, that total 3500 threat will be split among 5 enemies, generating only 700 against each.

How it works right now:
- Innervate does 2 kinds of threat: Mana restored when target is missing mana, and mana restored when target is full mana (much like healing vs overhealing)
The threat value of "overhealing" is normal, 0,5x per point. (assuming its meant to generate any threat)
The Threat value of actual restored mana , however, seems to be around 3-4 threat points per mana point which is extremely high.
Example: that 7k total mana regen creates around 25k threat if the target is missing enough mana so that the spell can do its full effect. 
- Innervate's threat generation isn't split among multiple targets in combat. 
Example: If there are 10 zombies spawned on gluth, the threat should be split by 11 (zombies and gluth). However at the moment each zombie will receive the full 25k threat against the druid, as well as Gluth himself.

The synergy of these two problems can result in druids randomly overaggroing (mostly adds) when they innervate.

**Comment by Keader** [comment]
What?
Any source for this?
Because innervate has nothing related with Threat in dbc

> Effect 0: Id 6 (SPELL_EFFECT_APPLY_AURA)
> BasePoints = 225
> Targets (21, 0) (TARGET_UNIT_TARGET_ALLY, NO_TARGET)
> Aura Id 24 (SPELL_AURA_PERIODIC_ENERGIZE), value = 225, misc = 0 (0), miscB = 0, periodic = 1000

**Comment by Dranah** [comment]
http://wowwiki.wikia.com/wiki/Threat
It is a power gain effect and i assumed it is handled as such.
I'd be completely fine with the ability making no threat at all, btw. 
The problem is it makes a fuckton atm.

**Comment by Keader** [comment]
Any spell that should add threat, need some effect to do it.
In this case, has not, and checking sniffs, no other spell is casted together to make threat effect.
So, i realy think it's invalid.

**Comment by Keader** [comment]
I will search if some part of core add threat in somewhere.
In Trinity i realy sure it dont add threat...
Idk if has some hack in wow mania code adding it, so need search.
But innervate in self dont add any threat.

**Comment by Dranah** [comment]
Well, something IS generating threat atm, if that's not intended, that needs to be removed.
Or reduced. Whichever is easier really.

**Comment by Dranah** [comment]
Spell no longer generates any threat. Seems fixed.
