### ISSUE TITLE
Quest: Waste Not, Want Not (Alliance): Interactables not working correctly.

### ISSUE THREAD

**Issue by Arek75** [WoWManiaUK/Redemption#2481]
I just did the alliance quest Waste Not, Want Not on my Druid (erimi) and discovered a bug where if you collect all the Salvageable Metal first, both the Metal and the Wood become uninteractable (tho wood still "glows").  If you collect all the wood first, both remain interactable.

Steps to reproduce:
1. Pick up the quest "Waste Not, Want Not" in Honor Hold.
2. Collect 8 "Salvaged Metal"
3. Notice that you can no longer interact with either Salvageable Wood or Salvageable Metal.
4. Abandon and retake the quest.
5. Collect 8 "Salvaged Wood"
6. Notice that you can still interact with both Salvageable Wood and Salvagable Metal.

Correct Behaviour:  When you collect 8 of either type of Salvaged Wood/Metal, that particular type of Salvageable should become non-interactable, but the other should remain interactable.

--Arek75
(character: Erimi, Alliance Worgen Druid)

**Comment by fvicaria** [comment]
The client cannot keep count of stuff you already have when you get the quest. This is a known client issue.

**Comment by TheManiax** [comment]
![image](https://user-images.githubusercontent.com/14857593/40278567-ad2b77ee-5c48-11e8-89af-d79a91c085ca.png)
![image](https://user-images.githubusercontent.com/14857593/40278571-bed10040-5c48-11e8-8cdb-72073323464f.png)
![image](https://user-images.githubusercontent.com/14857593/40278583-efb4aa22-5c48-11e8-818c-09714bbbf7e4.png)
Works fine.
