### ISSUE TITLE
[Spell] Rune of Death (Iron Council)

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#2482]
http://www.wowhead.com/spell=62269

Cast by Runemaster Molgeim http://www.wowhead.com/npc=32927
Cast when at least 1 other member of the Iron Council is down.

What it should do: This ability is supposed to do 2750 damage per half-second on 10man before mitigation.
What it does atm: Currently it does 7,5k-8k damage every half second instead. This is about 3 times higher than intended and pretty much insta-kills players.

I've yet to test 25man numbers.

A possible reason could be that the spell somehow benefits from the damage boost effects that Molgeim periodically receives from his other abilities- However that is not intended. This spell should always do the same periodic damage.

**Comment by Keader** [comment]
Test if work please.

**Comment by Dranah** [comment]
Damage is now correct on 10man (2750)
Tested 25 as well, i see youve set same value - it should be slightly higher, around 3500 on 25man mode.

**Comment by Keader** [comment]
Hmm, maybe he's casting 10 man spell in 25 man.
I will check today.
