### ISSUE TITLE
[NPC] Feral Defender (Auriaya)

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#2484]
http://www.wowhead.com/npc=34035/feral-defender

Their melee damage is insanely high. Note this has been tested on 10man mode.

How it should work:
These adds keep switching target (cannot be tanked) all the time, hitting raid members at random. Based on worldoflogs samples from 2010, their melee damage is typically around 4k on cloth, with their maximum power of 9 stacks. (and around 1,5-2k on tanks). This reduces over time as they lose stacks with each death.
In addition to that they also pounce if there is enough distance between their targets - that part works properly.

How it works atm:
They seem to melee for 30-35k on non-tanks. even on tanks around 15-20k. Considering they cannot be tanked but are constantly switching target, this leads to instant deaths unless you have multiple tanks taunt-spamming the adds. (even then, a tiny lag and you're done)

**Comment by fvicaria** [comment]
Should be as-is but I have reduced by about 50%

**Comment by Dranah** [comment]
The cat now does 60-70k unmitigated dmg. This is even worse. The boss herself only melees for 15k on cloth...
This should be an add with trash-level melee swings, not a one-shotter. 4k on cloth with 8k criticals.

**Comment by Dranah** [comment]
http://www.worldoflogs.com/reports/7bapmsnloka4ix71/details/152/?s=6268&e=6338

Here's an example from one of the 2010 charts where you can see a feral defender's damage output.

You can see next to "Melee" that the add hit the warlock 4 times, for an average of 4194 damage, totaling 16776 over whole course of fight.

4 | 4194.0 | 16776

Here the damage is more than 10 times higher, that cannot be "as-is"

**Comment by Ashamedlol** [comment]
![index](https://user-images.githubusercontent.com/16576459/40363887-8173e856-5dd9-11e8-8764-afb92fa95cae.png)
It's doing 6k to a Plate tank,  not sure about clothies.

**Comment by Dranah** [comment]
much better question, why is your ret aura reflecting 3k damage pet hit?!

**Comment by Dranah** [comment]
Cat melees 16-18k on cloth and this is on 10man... still too much. You said it was set to 6k >.>

**Comment by Dranah** [comment]
Here is a video from 25man https://www.youtube.com/watch?v=HZCL4RTWzIc
At 1:50 you can see the caster druid "tinybit" take a hit from the cat switchin aggro on him, reducing his health by about 30-40% based on the health bar. That cannot be more than 8-9k damage in one hit.
Same happens around 2:40 to "cantgetright" another caster druid.

It is safe to say even on 25man the cat is not meant to hit harder than half the health pool of a caster

**Comment by Keader** [comment]
I need you online to change it with me tomorrow.

**Comment by Keader** [comment]
Done Dranah.
I did directly in dev.
I got 5~6k with full stacks (with soul link)

**Comment by Dranah** [comment]
yes it is fine now, 7k on a mage
