### ISSUE TITLE
[Spell] Combustion

### ISSUE THREAD

**Issue by cathyr1** [WoWManiaUK/Redemption#2487]
The mage spell Combustion http://www.wow-mania.com/armory/?spell=11129 does not work properly as it should as the buff fades away after 2 direct critical hits instead of 3.

**Comment by squalllh1989** [comment]
Confirmed. After 2 direct crit hit, combustion fade, it should stay for 3.

**Comment by GMWeeble** [comment]
Works fine. 3 Critts and the spell wears off.
