### ISSUE TITLE
Shadowmourne quest line final quest bug

### ISSUE THREAD

**Issue by Madara77** [WoWManiaUK/Redemption#2488]
Hello
I just finished my Shadowmourne quest line few days ago with the killing of Lich King in ICC 25 HC
the boss is supposed to be dropping an item that starts another quest for the Lightbringer tabard and other items u get as reward for finishing Shadowmourne quest line
the item is called "Sealed Chest" and it's 100% drop rate once u finish the quest line but it didn't drop.
http://www.wow-mania.com/armory/?item=51315
u can check my account and see that i just finished the quest line and got the weapon in the same raid as i killed LK, but i think that happened duo to a server crash happened while we're at LK platform
here is a video of our guild streaming LK kill yesterday in the min 3:16:30 to be exact  
https://www.twitch.tv/videos/263544174
please i would like that u send me that item "Sealed chest" so i can start the quest and get the reward for completing shadowmourne quest line
Char name: Madara

**Comment by GMWeeble** [comment]
No he did not.
