### ISSUE TITLE
Missing Items; Skeleton Keys / Dungeon rewards

### ISSUE THREAD

**Issue by Tonedawg** [WoWManiaUK/Redemption#2489]
Created some silver skeletons keys, didn't show up in the inventory. Made a bunch of Gold Skeletons Keys, same issue. Cleared cache, no difference. Now for random dungeon finder, my friend and I are not receiving manic points or the bag of helpful goods. Reported the issue and was directed to this entity. Thank you for your time and blessings to play on this server. 
With great love,
Tonedawg

**Comment by fvicaria** [comment]
Please follow the procedure described below before creating a new issue:
[How to Properly Report an Issue](https://github.com/wow-mania/Redemption/wiki/How-to-Properly-Report-an-Issue)

This will help developers identify and fix the issue quicker. Incorrectly or unclear reports will simply be deleted.

**Comment by fvicaria** [comment]
The Maniac Points will not show up unless you have our client up to date.
Please contact us on Skype or via email if you need help.
