### ISSUE TITLE
[3D Model] Mount

### ISSUE THREAD

**Issue by TheManiax** [WoWManiaUK/Redemption#2490]
The 3D model of the following mounts are smaller than what they are meant to be.
1- [[Bloody Reins of Dark Portent]](http://www.wow-mania.com/armory/?item=143490)
2- [[Mephitic Reins of Dark Portent]](http://www.wow-mania.com/armory/?item=143491)
3- [[Midnight Black Reins of Dark Portent]](http://www.wow-mania.com/armory/?item=143492)
4- [[Razor-Lined Reins of Dark Portent]](http://www.wow-mania.com/armory/?item=143493)
**How it looks:**
![image](https://user-images.githubusercontent.com/14857593/40428910-a0c1f8a0-5eb6-11e8-893e-b9455de90391.png)
**How it should look:**
![634048-shadowblades-baneful-omen-credits-to-celinamuna](https://user-images.githubusercontent.com/14857593/40428879-8dafc972-5eb6-11e8-989c-3aa37905dfa4.jpg)

**Comment by fvicaria** [comment]
Will need client update.
I will try to fix it tomorrow.

**Comment by fvicaria** [comment]
Fixed but it will only be deployed tomorrow with the other issue that also requires client update.
