### ISSUE TITLE
Transmog: Doomed Crown of Lei-Shen ( Item #94984 )

### ISSUE THREAD

**Issue by Sinlithe** [WoWManiaUK/Redemption#2493]
> I previewed Doom Crown of Lei-Shen on my character and found this bug. I reported this to GM Saintz, who then directed me here once he was able to confirm the same issue from his client. 

This item can be found in the Epic [1] Category of Helmets, last page.

Attached, I have included a picture of the helmet without the bug and my character in game showing the "Doomed Crown of Lei-Shen" bugged with the green digital look.

![doomed crown of lei shen](https://user-images.githubusercontent.com/39575659/40460349-17aca556-5ebb-11e8-82cf-8d0370269e63.png)

![wowscrnshot_052318_184642](https://user-images.githubusercontent.com/39575659/40460362-28a5cf54-5ebb-11e8-936a-0e83d65889f6.jpg)
![wowscrnshot_052318_184645](https://user-images.githubusercontent.com/39575659/40460363-28c44718-5ebb-11e8-80d0-b685dfe3aed3.jpg)
![wowscrnshot_052318_184650](https://user-images.githubusercontent.com/39575659/40460364-28dfa756-5ebb-11e8-8a19-cee8abe182a7.jpg)

**Comment by fvicaria** [comment]
![image](https://user-images.githubusercontent.com/9414661/40535957-8b2564c6-6002-11e8-8b3e-a4a96639cf95.png)

**Comment by Sinlithe** [comment]
Good work! :D
