### ISSUE TITLE
Rend Boss Fight - No waves, No scales :(

### ISSUE THREAD

**Issue by tecnoturc** [WoWManiaUK/Redemption#2494]
Trying to complete 2 quests: Legplates of the Chromatic Defier -and- Breastplate of the Chromatic Flight.

On my journey to get Brilliant Chromatic Scales, I found that there aren't any enemies to kill to get them! (or very few)

In the Rend bossfight, it looks like there needs to be more waves of enemies so you can loot these items. The gate opens and closes, and there is chat from the NPC, but only 1 wave out of... looks to be 7? Please make dragons or w/e come out of the gate. We will love you forever.

**Comment by fvicaria** [comment]
Please follow the procedure described below before creating a new issue:
[How to Properly Report an Issue](https://github.com/wow-mania/Redemption/wiki/How-to-Properly-Report-an-Issue)

This will help developers identify and fix the issue quicker. Incorrectly or unclear reports will simply be deleted.

**Comment by fvicaria** [comment]
http://www.wow-mania.com/armory/?item=12607
