### ISSUE TITLE
[Spell] Alchemy Specialization

### ISSUE THREAD

**Issue by TheManiax** [WoWManiaUK/Redemption#2495]
[[Alchemy Specialization]](http://www.wow-mania.com/armory/?spell=150002), racial ability for Goblins is not increasing the alchemy skill as intended.
![image](https://user-images.githubusercontent.com/14857593/40538040-c70dc8a2-6025-11e8-99a0-f7baab7c13fc.png)

**Comment by fvicaria** [comment]
@Keader Can you look at this one?

**Comment by Keader** [comment]
This spellid is cata one ?
I Will take a look when i back of uni

**Comment by fvicaria** [comment]
No, this is our custom addition to the race to wotlk, should follow the same rules. 
TheManiax, as an experienced tester, has kindly added the spell id. :)

**Comment by TheManiax** [comment]
Check the engineering for goblins
It has the same effect and it is working fine
I can’t search for the links atm
