### ISSUE TITLE
[Quest] Alpha Worg

### ISSUE THREAD

**Issue by Ashercraft** [WoWManiaUK/Redemption#2496]
http://www.wowhead.com/quest=11326/alpha-worg#criteria-of

Garwal spawns directly as "Garwal - Worgen Transform", and doesn't give credit for quest completion when killed.  Objective remains as "Garwal slain: 0/1" even after waiting for him to respawn, and killing him multiple times
![garwal worgen form](https://user-images.githubusercontent.com/34398168/40554620-518f8e5a-6014-11e8-826f-dc7192631358.JPG)

**Comment by fvicaria** [comment]
Just done the quest and it worked fine.
I will just wait for a tester to confirm before closing it.

![image](https://user-images.githubusercontent.com/9414661/40565930-5a336cdc-6066-11e8-9213-30347b06ad57.png)

**Comment by Ashercraft** [comment]
Thank you so much for looking into it.  I went to stand directly where you took the screenshot, and he did in fact stroll by.  The confusion comes from a SECOND copy which always stands in the same area, at 27.0, 13.4, and doesn't give credit for the quest
![dual garwals](https://user-images.githubusercontent.com/34398168/40577316-aeaa57f6-60d1-11e8-8584-f60b175cb61c.JPG)
