### ISSUE TITLE
[Spell] Hand of Protection and Bladestorm Interaction

### ISSUE THREAD

**Issue by Ashamedlol** [WoWManiaUK/Redemption#2497]
When a warrior uses Bladestorm and a Paladin uses Hand of Protection on the Bladestorming Warrior it should cancel Bladestorm but instead it's causing the warrior to still deal damage and be immune to disarm effects and physical damage.

Hand of Protection ID: http://www.wow-mania.com/armory/?spell=1022 / http://www.wow-mania.com/armory/?spell=5599 / http://www.wow-mania.com/armory/?spell=10278

Bladestorm ID: http://www.wow-mania.com/armory/?spell=46924

**Comment by Keader** [comment]
Fixed
