### ISSUE TITLE
[Boss] Magtheridon lair

### ISSUE THREAD

**Issue by gamer100** [WoWManiaUK/Redemption#2498]
http://www.wowhead.com/npc=17257/magtheridon

Magtheridon is not to target, after mobs and casters are  killed, You cant target him. you cant kill him and you are locked in the room. he just say i am unleahed

**Comment by Wiindmere** [comment]
Fixed.  Fix sent to Janitor via Discord.

**Comment by Keader** [comment]
How you killed casters?
.die? some hit kill ?

**Comment by WhitephoenixTheBunny** [comment]
@Keader 
You can kill trash/adds normally, after you clean room, Matherion start his Role Play, but doesn't become targetable, and you need HS or Mall stone to leave instance.

**Comment by Keader** [comment]
Perfect Angie.
Fixed. I need wait janitor send me the file.

**Comment by Keader** [comment]
Fixed and confirmed today :)

**Comment by WhitephoenixTheBunny** [comment]
<3
