### ISSUE TITLE
Chapter IV

### ISSUE THREAD

**Issue by GM-Gathios** [WoWManiaUK/Redemption#2499]
http://www.wowhead.com/quest=342/chapter-iv

For this quest you'll have to bring a page bundle (http://www.wowhead.com/item=2759/green-hills-of-stranglethorn-chapter-iv)  to Barnil Stonepot (http://www.wowhead.com/npc=716/barnil-stonepot)

- Green Hill's of Stranglethorn - Page 25 (http://www.wowhead.com/item=2749/green-hills-of-stranglethorn-page-25)
- Green Hill's of Stranglethorn - Page 26 (http://www.wowhead.com/item=2750/green-hills-of-stranglethorn-page-26)
- Green Hill's of Stranglethorn - Page 27 (http://www.wowhead.com/item=2751/green-hills-of-stranglethorn-page-27)

Once completed, you are unable to reward this quest, .die and .respawn didn't work.

**Comment by fvicaria** [comment]
Need confirmation. This has never been a problem. It may be due to the fact the player was doing multiple quests at the same time with similar/common requirements.

**Comment by GM-Gathios** [comment]
It works now, thank you!
