### ISSUE TITLE
[3D Model]  Jin'ya, Orb of the Waterspeaker ID:86335

### ISSUE THREAD

**Issue by TheManiax** [WoWManiaUK/Redemption#2501]
**How it looks like:**
![image](https://user-images.githubusercontent.com/14857593/40764647-1c8903da-64bf-11e8-8956-535afd914b22.png)
**How it should look like:**
![image](http://wow.zamimg.com/uploads/screenshots/normal/380680-jinya-orb-of-the-waterspeaker-orb-in-staff-spins-sha-flakes-float-from-it.jpg)

**Comment by TheManiax** [comment]
Checked with several players to confirm.

**Comment by fvicaria** [comment]
Will need the new client.
