### ISSUE TITLE
Quest: On Ruby Wings

### ISSUE THREAD

**Issue by chekong** [WoWManiaUK/Redemption#2502]
The quest for On Ruby Wings from Dragonblight is currently bugged and unable to complete.  One of the objective is to obtain quest item, the Scythe of Antiok from the NPC Grand Necrolord Antiok.  Antiok has a shield buff that makes him invulnerable to all damage.  That shield is suppose to disappear once you killed his giant that he is riding on named Thiassi.  But even after Thiassi is killed, Antiok still has his shield and is thus unkillable which I can't loot the quest item from his dead body.  Please fix.

**Comment by fvicaria** [comment]
Works. 

Also...
Please follow the procedure described below before creating a new issue:
[How to Properly Report an Issue](https://github.com/wow-mania/Redemption/wiki/How-to-Properly-Report-an-Issue)

This will help developers identify and fix the issue quicker. Incorrectly or unclear reports will simply be deleted.
