### ISSUE TITLE
Unable to Fly in Azeroth

### ISSUE THREAD

**Issue by AndrewRedican** [WoWManiaUK/Redemption#2503]
I am following instructions to submit a bug/request from a moderator which I made the same inquiry.

I recently donated to the server to get my hands on ironbound proto-drake http://www.wowhead.com/item=45801/reins-of-the-ironbound-proto-drake. This item is not listed in the shop, however like other flying mounts, I assumed http://www.wowhead.com/npc=33892/ironbound-proto-drake would be able to fly in Azeroth. Turns out it does not. :(

I know there are many mounts from different expansions obtainable via donation as an alternative to obtain the mount different from what the original means of obtaining are in the actual game.

I would like to know if we can make it be able to fly in Azeroth? 

I was told some mounts in particular do not fly in Azeroth due to *policy*. I am worried this might be the case for this mount I got from donating. If by some policy you cannot change it, I would argue that this donation/purchase I made came without any warning labels that it would not fly in Azeroth. It would be very disheartening finding I can't take it with me anywhere, where other mounts of the same or higher caliber are able to.

Let me know your thoughts.

Kind Regards,
AndrewR

**Comment by fvicaria** [comment]
There is a list on the forum of all flyable mounts in Azeroth.
We do not use GitHub for requests sorry.
We won't be adding any more mounts capable of flying in Azeroth for while now.
