### ISSUE TITLE
Problem with Barbershop in Stormwind

### ISSUE THREAD

**Issue by SheHunter** [WoWManiaUK/Redemption#2505]
Realm:Elysium
Hello if i wanna change hair in  barbershop i get this 
![image](https://user-images.githubusercontent.com/39839718/40858375-6a6c474a-65de-11e8-8f61-db462656824d.png)
I hope u will fix that and have a good day 
Greetings SheHunter

**Comment by gamer100** [comment]
Player is on client and launcher, on patch 2.3.7. Did  delete the cache and dont use addons.

**Comment by Kadajj** [comment]
There is a known issue this one. Unfortunately, as i know, there is nothing we can do at the moment.
If i am wrong please correct me.

**Comment by fvicaria** [comment]
As-is and it will not be fixed at this stage. Request a character customization via an in-game ticket please.
