### ISSUE TITLE
[Quest] Proof of Treachery

### ISSUE THREAD

**Issue by gamer100** [WoWManiaUK/Redemption#2507]
The Npc dont  give the  quest
 
http://www.wow-mania.com/armory/?quest=11222

This quest is  started with the quest Survey Alcaz Island, 
http://www.wow-mania.com/armory/?quest=11142
But she  only keeps an conversation and  dont give Proof of Treachery

**Comment by fvicaria** [comment]
Can someone confirm this one please.

**Comment by gamer100** [comment]
I have test it after player  could not take  quest, i have reset  jaina the npc, but  did not make any diffrence.

**Comment by WhitephoenixTheBunny** [comment]
Did you start the chain quest with http://www.wow-mania.com/armory/?quest=11126 ?

**Comment by fvicaria** [comment]
This quest has been Deprecated since 3.0.2
