### ISSUE TITLE
[Spell] Ritual of the Sword (Svala Sorrowgrave)

### ISSUE THREAD

**Issue by Pohotliv** [WoWManiaUK/Redemption#2508]
http://www.wowhead.com/achievement=2043/the-incredible-hulk#criteria-of
For the achievement you have to start the encounter and drain hulk to low enough hp so when the sword drops it kills him. In our case there were no sword at all the boss didn`t phased at all even tho we were carefull with the dps.

**Comment by TenmanWoW** [comment]
Tested this on Redemption proper.

How it should work:

Fight beings and it's fairly straight forward. At points, Svala will offer up one of the party members as a sacrifice. This target takes periodic damage as a sword slowly descends from above. The idea is to heal the player through the damage and avoid getting hit by the sword.

Achievement:

Pulling the Hulk mob in the same room to be included in the fight. When a player is sacrificed, the Hulk should be dragged over to the same spot. Once the player is free, the Hulk is hit by the sword (and if weakened enough) dies.

What actually happens:

The fight begins as stated. The Hulk is able to be included in the fight. The sword is not visually there although can confirm the damage from being the sacrifice is working how it should. The graphics of the sword completing it's cycle was plainly visible. The Hulk was not finished off the "impact" of the sword, although he was at 10k life, which is easily within the acceptable range.

Party freed me by correctly targeting and kill the banshees. Svala did not attempt another sacrifice for the rest of the fight.

Achieve - http://www.wowhead.com/achievement=2043/the-incredible-hulk
Boss - http://www.wowhead.com/npc=26668/svala-sorrowgrave
Spell - http://www.wowhead.com/spell=48267/ritual-preparation  (Stuns player)
           http://www.wowhead.com/spell=48276/ritual-of-the-sword   (Sword)

Pictured below - The lack of the sword (biggest reason being it judges how long you have until the spell completes). Me affected by Ritual Preparation.

![wowscrnshot_060218_181919](https://user-images.githubusercontent.com/25806987/40881828-b4433fbe-6696-11e8-9cfe-23c7f86978a3.jpg)


Pictured below - Fight following completion of Ritual. Hulk still alive. Player no longer stunned.

![wowscrnshot_060218_181928](https://user-images.githubusercontent.com/25806987/40881843-f90af2ea-6696-11e8-9104-41e421d7fc2b.jpg)

**Comment by Dranah** [comment]
Just to add some info,

1) the achievement is doable
Video guide here i just filmed it 10mins ago: https://youtu.be/p7biNd4TSQ0

2) Svala always begins "Ritual of the Sword" at 50% health, if you don't damage her, she is never going to sacrifice
3) The achievement only counts if you engage Svala and THEN pull the hulk (svala must be already in combat when you pull hulk)
4) The Achievement must be earned if the Hulk dies to the sword landing OR also if he dies to the DOT that it leaves behind (if the DOT deals the killing blow!)

The only problem currently the sword is visually missing and the instant-damage portion of the impact is missing. The DOT is however applied properly to the targets in the right area and it is possible to complete achievement using the DOT damage of the Sword.

**Comment by Keader** [comment]
Can you confirm @Dranah?

**Comment by Dranah** [comment]
- Sword visual is added but is wrong, should be a descending sword, but it's floating towards player horizontally instead
- Timer for ritual now works as intended, but the visual does not match. The sword - coming from wrong direction - slams into the target very soon, but the damage only comes later, when it should. The sword visually hitting target should happen at same time.
- instant damage done by "ritual strike" only hits the player sacrificed, does not damage the hulk for achievement
- svala receives the DOT damage from "ritual strike" too, she probably shouldn't but this isn't a huge issue

**Comment by Keader** [comment]
Visual shit i cant fix.
Instant damage is in new fix.

**Comment by Keader** [comment]
This need wait Dranah xD
