### ISSUE TITLE
Mines for minning Bug from Areas

### ISSUE THREAD

**Issue by Sonyabladee** [WoWManiaUK/Redemption#2509]
Hello , when im in one Area on Ice Crown i can see that mine and couple from the others , but when i go to that Area that mine dissapear. The Problem is not from me because i already tryied alot of Stuffs what the GM's told me nothing works. there are the Screens for Proof
![wowscrnshot_060318_145116](https://user-images.githubusercontent.com/32413884/40887875-67179212-674f-11e8-8f5c-b23bc31f8f8c.jpg)
![wowscrnshot_060318_145121](https://user-images.githubusercontent.com/32413884/40887876-67329030-674f-11e8-8cb4-246807eae866.jpg)
![wowscrnshot_060318_145125](https://user-images.githubusercontent.com/32413884/40887877-674af850-674f-11e8-84db-d8bb662d9cfe.jpg)
![wowscrnshot_060318_145128](https://user-images.githubusercontent.com/32413884/40887878-6762c818-674f-11e8-9513-9ec4b34de512.jpg)
![wowscrnshot_060318_145132](https://user-images.githubusercontent.com/32413884/40887879-677a265c-674f-11e8-85b3-368374edc4e6.jpg)

**Comment by TenmanWoW** [comment]
Hello! Tenman here.

Just from looking at the screenshots, I would say it's a phasing issue. Did you complete the quests in Scourgeholme that unlocks the FP there? If you didn't fully unlock the area, then this will occur.

**Comment by TenmanWoW** [comment]
Solved. Was indeed phasing, no bug found.
