### ISSUE TITLE
Transmog: T'uure, Beacon of the Naaru ID: 150138

### ISSUE THREAD

**Issue by Theleiba** [WoWManiaUK/Redemption#2510]
The artifact weapon transmog T'uure, Beacon of the Naaru...
http://www.wow-mania.com/armory/?item=150138
http://www.wowhead.com/item=128825/tuure-beacon-of-the-naaru
...shows up upside down when holstered. Both when transmogged onto something and when directly equipped. 
These links show how it should look when holstered:
http://www.wowhead.com/outfit=76443/t6-recolor-priest-blue-white-gold-tuure-keeper-of-the-light-blue#screenshots:id=640058) and http://wow.zamimg.com/uploads/screenshots/normal/502618-tuure-beacon-of-the-naaru.jpg
This is how it looks when holstered on my character on the Wow-Mania server with the latest client and launcher:
![wowscrnshot_060418_001117](https://user-images.githubusercontent.com/16779682/40891788-90e4ec08-6794-11e8-8523-3686c9182e56.jpg)
This was confirmed by a gm to not be an issue on my side only and all other players saw it upside down. It's been a few months since I first found this bug and I was told to report it here but I stopped playing for a while soon after so I never did until now.

**Comment by TheManiax** [comment]
Thanks for the proper report but These items are imported from another client and displayed the best way possible.
We will not change it. Sorry.
