### ISSUE TITLE
[Spell] Death Coil

### ISSUE THREAD

**Issue by Ashamedlol** [WoWManiaUK/Redemption#2516]
Death Coil is not healing 300% of the damage it deals, and is also consuming Fear Ward above fearing/horrifying the target at the same time, it should not consume Fear Ward as it's a horrify effect.

![coil](https://user-images.githubusercontent.com/16576459/41048453-64d46fce-69b7-11e8-8b8d-25ecce7e064b.png)

As seen here, Coil did 2.4k damage and healed for 2.7k only. / Fear Ward was casted, Death Coil consumed it and feared the target at the same time when it should do one function only.

Death Coil ID: http://www.wow-mania.com/armory/?spell=6789 (R1) / http://www.wow-mania.com/armory/?spell=17925 (R2) / http://www.wow-mania.com/armory/?spell=17926 (R3) / http://www.wow-mania.com/armory/?spell=27223 (R4) / http://www.wow-mania.com/armory/?spell=47859 (R5) http://www.wow-mania.com/armory/?spell=47860 (R6)

Fear Ward ID: http://www.wow-mania.com/armory/?spell=6346

**Comment by Keader** [comment]
Fix confirmed.
