### ISSUE TITLE
Character Loot

### ISSUE THREAD

**Issue by cesargarza1** [WoWManiaUK/Redemption#2518]
I purchase the instant level 60 with maniac points, and the loot that is supposed to come with it did not go into my bags because of no space. Please send by mail loot included with purchase. Character name is Ildanar lvl 60 warrior.

![image](https://user-images.githubusercontent.com/40011291/41073138-840ed298-69c7-11e8-98e5-9ee5ce7a8606.png)

**Comment by WhitephoenixTheBunny** [comment]
Hello, this is not a post for GitHub. Contact a GM ingame via Ticket.
