### ISSUE TITLE
Ethereal Soul-Trader still bugged

### ISSUE THREAD

**Issue by Tamagucci** [WoWManiaUK/Redemption#2520]
Sorry, but ethereal soul trader is still not collecting ethereal credits off of kills :(

Downloaded the new patch; cleared cache and tested on level 80 mobs and still nothing.

He does say the emote when summoned now though.

**Comment by TheManiax** [comment]
https://github.com/WoWManiaUK/Redemption/issues/2506

**Comment by Keader** [comment]
Hmm, other topic has more info...
