### ISSUE TITLE
Unexpected Results

### ISSUE THREAD

**Issue by skittleferret** [WoWManiaUK/Redemption#2521]
In Eversong Woods, the NPC Apprentice Mirveda qives a chain of quests. The second quest is Unexpected Results. During this quest, you have to protect her for a certain amount of mob spawns. For me, only one set of mobs spawned. as I'm a high level for the area (going for loremaster) I figured I had killed them to quickly. I waited about 10 minutes with no new spawns. I was unable to hand the quest in, so I abandoned it, hoping to pick it back up and start again. However I was unable to interact with the guest giver so I cant complete the quest chain. I've tried relogging and waited a few days and it still wont let me talk to her. 
Thanks
Kheda

**Comment by WhitephoenixTheBunny** [comment]
NPC Apprentice Mirveda: http://www.wow-mania.com/armory/?npc=15402
Unexpected Results: http://www.wow-mania.com/armory/?quest=8488
Start of Chain Quest: http://www.wow-mania.com/armory/?quest=9254

**Comment by skittleferret** [comment]
I just tried to do this quest and the same happened. I wasnt able to complete the quest so, I abandoned it in hopes of picking it back up and I cant talk to the quest giver.
Thanks
Kheda
