### ISSUE TITLE
Hunter's Pet Ability not doing total damage

### ISSUE THREAD

**Issue by crulinjr** [WoWManiaUK/Redemption#2523]
So i am leveling up a hunter and i notice a damage number was not right. Something was doing between 1 to 8 damage sometimes and looking into the combat log i realized that the Bear hunter pet ability, Swipe (http://www.wow-mania.com/armory/?spell=53533), was not doing the damage it should. A GM told me maybe it was i was not using the launcher or the latest patch but then when i did i notice the same problem. Maybe thats why Bears are not holding aoe aggro properly. I will send a screenshot.
[wow test.docx](https://github.com/WoWManiaUK/Redemption/files/2086008/wow.test.docx)

**Comment by crulinjr** [comment]
The ability swipe is really bugged

**Comment by TheManiax** [comment]
No damage is being registered on combat log as I see.
And @crulinjr you can upload screenshots by dragging or using Ctrl+C on the pic file and pasting in comment using Ctrl+V.
No need to upload .docx file.

**Comment by crulinjr** [comment]
Ok ty. Did not realize i could do that. So Will you try yo Fix It? The los
damage and the nota registro general part?

**Comment by Echinaceax** [comment]
Hi crulinjr 
Im not a fixer but i noticed that the linked spell was rank 6 and your picture is only rank 3 ..i could be wrong but have you checked in your spellbook for the right rank of swipe you have out on your bar ?

maybe just a quick check and see

**Comment by crulinjr** [comment]
The rank of my swipe ability in the pic is rank 5 and still no damage is
registered. In lower levels the damage was registered but doing between 1
and 8 despite the rank of the ability. Evento so, ay rank 3 swipe should be
doing between 17 and 28 not 1 ir 8. However, when i got to Outland, the
damage stop being registered so swipe was not doing damage. Sometimes i got
the message "swipe was Dodge" but thats it.

**Comment by Echinaceax** [comment]
![rank 3](https://user-images.githubusercontent.com/39439201/41370079-f0396850-6f46-11e8-9c3d-1ef72b1999a8.jpg)

I see rank 3 ..cooldown 5 sec.
But anyway ..i think the tecs are working on it as far as i can see as this report has been closed.
so im sure there will be an update to fix it soon

**Comment by crulinjr** [comment]
I sent another pic in another thread

**Comment by crulinjr** [comment]
Oh ok ty still means a lot that you are working on it
