### ISSUE TITLE
[NPC] Chief Engineer Copperclaw

### ISSUE THREAD

**Issue by cathyr1** [WoWManiaUK/Redemption#2526]
This NPC http://www.wow-mania.com/armory/?npc=30825 seems missing. He should be aboard Orgrimm´s Hammer right on the place on my screenshot but he´s not there.
![obr](https://user-images.githubusercontent.com/30184491/41194305-b7e32836-6c19-11e8-83fd-0eda8c3727ea.png)

**Comment by fvicaria** [comment]
If a player kills the NPC it will take time for it to respawn. It is there.

**Comment by cathyr1** [comment]
He was missing whole afternoon while all other mobs were on the ship so it´s not this reason.

**Comment by cathyr1** [comment]
Returned today and he is still not here. Not possible anyone keep killing him while all other NPCs on the ship are still alive. It is a bug. I have new client, each time using launcher and deleted cache.
![obr](https://user-images.githubusercontent.com/30184491/41199270-1e547802-6c8f-11e8-9142-0cd47232a2c5.png)
