### ISSUE TITLE
Quest: The Exorcism of Colonel Jules

### ISSUE THREAD

**Issue by GM-Gathios** [WoWManiaUK/Redemption#2528]
http://www.wowhead.com/quest=10935/the-exorcism-of-colonel-jules

For this quest you'll need to use the Ritual Prayer Beads (http://www.wowhead.com/item=31828/ritual-prayer-beads) on Anchorite Barada or Colonel Jules before starting the ritual in order to save Colonel Jules. Several skulls need to be killed.

The quest is doable with a workaround. Colonel Jules floats to a other room, also spawning skulls in the other room. This isn't what he should do. After the ritual is completed Colonel Jules swims mid air back to the bed he was lying on. The objective should be completed automatically. In order to complete it now, you'll have to talk with Colonel Jules.

**Comment by fvicaria** [comment]
Also pretty sure it works

**Comment by TenmanWoW** [comment]
I tested this on dev. Except for a few pathing things (like Jules swimming around midair in the room the event takes place in), I noticed nothing that would prevent completion.



![wowscrnshot_060918_190639](https://user-images.githubusercontent.com/25806987/41197133-cc30293e-6c18-11e8-8aa2-5451475d72c8.jpg)
![wowscrnshot_060918_190628](https://user-images.githubusercontent.com/25806987/41197134-cc44567a-6c18-11e8-9028-0f88ad22060a.jpg)
![wowscrnshot_060918_190542](https://user-images.githubusercontent.com/25806987/41197135-cc551316-6c18-11e8-90b1-3f813fdf3560.jpg)
