### ISSUE TITLE
ICC-Valithria dreamwalker bug

### ISSUE THREAD

**Issue by catastross** [WoWManiaUK/Redemption#2529]
hello,
Today (as in Saturday 9 June) me and my guild did 25nm icc run and on the boss Valithria dreamwalker, when healers went in portals they were still targetable by people outside of portals and adds that spawned in the fight. This meant that while in the portal and flying you were able to be slowed by frost bolts and so there wasn't enough time to get as many stacks as possible, effecting the length of the fight. Also adds would still follow the healer while in the portals, accidentally kiting them around the room and getting re-attacked by them after exiting the portals. It was never like this before in the server and retail: 'The Dream is a version of the room where only Valithria, several green orbs, and the players who entered exist.' from WoWpedia.

Thanks,
Catastross

**Comment by Keader** [comment]
It is phase bug, can happen with Halion too.
I realy think it's "one time bug", normally caused by GM Summon xD

**Comment by TheManiax** [comment]
@catastross 
Thanks for the report.
More than what has happened there as a bug, I need to know how to reproduce the bug.
If I can't reproduce it, Then Developers can't find the incorrect code to fix it.
If you ever found the way to make it happen again, add the steps here and I make sure to handle it.
Till then, there is nothing I can do to help you.

**Comment by catastross** [comment]
On Monday I'll do another icc, this time 10hc and I'll be looking into it further
