### ISSUE TITLE
[Quest] The Hunter and the Prince

### ISSUE THREAD

**Issue by cathyr1** [WoWManiaUK/Redemption#2530]
I have some problems with this quest http://www.wow-mania.com/armory/?quest=13361. The stone that should be clicked on is missing as you can see on the screenshot.
![obr](https://user-images.githubusercontent.com/30184491/41201205-cc058c56-6cb3-11e8-8f24-5dfe99c11f0c.png)

**Comment by fvicaria** [comment]
Pretty sure you are missing something that let you in the wrong phase. The rock is there.
I will check.

**Comment by TenmanWoW** [comment]
I'll go check it, Janitor.

**Comment by WhitephoenixTheBunny** [comment]
the stone is it, it's phase issue

**Comment by TenmanWoW** [comment]
Phoenix says she did two days ago and below are SS from PTR from me about 5 mins ago.

![wowscrnshot_061018_091957](https://user-images.githubusercontent.com/25806987/41202607-35efe4fe-6c91-11e8-9f5d-c9527923e565.jpg)
![wowscrnshot_061018_091831](https://user-images.githubusercontent.com/25806987/41202608-3605690a-6c91-11e8-9707-25319f511c3b.jpg)

**Comment by fvicaria** [comment]
Is this a valid issue for someone doing the entire quest chain?

**Comment by TenmanWoW** [comment]
I don't believe so. When checking the original report, I went back a few quests just to be sure it phased correctly. I had no issue completing the quest on PTR as if a player would.

**Comment by cathyr1** [comment]
So what should I do? The stone is still not there, checking it multiple times every day. I need to complete that quest so I ask GM ingame?

**Comment by fvicaria** [comment]
I will check where this can go wrong again. In the meantime please just open a ticket. The GM can summon you into the correct phase or complete the quest.
