### ISSUE TITLE
[Hunter Ability] Chimera Shot - Serpent Sting

### ISSUE THREAD

**Issue by Xantoni** [WoWManiaUK/Redemption#2538]
Chimera Shot: https://wotlk-twinhead.twinstar.cz/?spell=53209
Serpent Sting: https://wotlk-twinhead.twinstar.cz/?spell=36984

**How it should work:**
Chimera Shot with the Serpent Sting applied in the target gets 2 shots. The first one is full damage of the Chimera Shot, and the second one deals 40% of the TOTAL Serpent Sting damage dealt.

**How it works:**
The second tick does 40% of ONE tick of damage of the Serpent Sting, dealing 500 (1k if critical hit) damage only with the secondary shot of Chimera Shot.

EDIT : i've tried this with my hunter Alarian.
![chimerashot](https://user-images.githubusercontent.com/31468160/41507606-f4659d80-7235-11e8-8d55-25ba9660a8cb.jpg)

**Comment by Keader** [comment]
My serperting dot hit 443

443*5 = 2215
2215 * 0.4 = 886

https://i.imgur.com/c2Hul7A.jpg

Looks correct now.

**Comment by Xantoni** [comment]
Thanks for your attention :)
