### ISSUE TITLE
[Spell] Divine Shield

### ISSUE THREAD

**Issue by Ashamedlol** [WoWManiaUK/Redemption#2539]
Some spells are going through the immunity of the spell, such as:

Nibelung's Val'kyr Protector:
![ntmrymewqgyxl9fwcj8wva](https://user-images.githubusercontent.com/16576459/41510291-963da29a-726a-11e8-9138-e9045c6d5f2b.png)

Val'kyr Protector ID: 
25hc: (http://www.wow-mania.com/armory/?npc=38392) / 25nm: http://www.wow-mania.com/armory/?npc=38391

Nibelung ID: 25nm: http://www.wow-mania.com/armory/?item=49992 / 25hc: http://www.wow-mania.com/armory/?item=50648

Holy Shield: 
![dvhmm3upqukx8txbw7zxpq](https://user-images.githubusercontent.com/16576459/41510669-86242314-7271-11e8-9948-d0c86b3f90da.png)

Rank1 (http://www.wow-mania.com/armory/?spell=20925) /  R2 ( http://www.wow-mania.com/armory/?spell=20927) / R3 ( http://www.wow-mania.com/armory/?spell=20928) / R4 (http://www.wow-mania.com/armory/?spell=27179) / R5 (http://www.wow-mania.com/armory/?spell=48951) / R6 (http://www.wow-mania.com/armory/?spell=48952)

Divine Shield ID: http://www.wow-mania.com/armory/?spell=642

**Comment by Keader** [comment]
i dont get it

**Comment by Dranah** [comment]
It seems mostly holy damage spells?

**Comment by Keader** [comment]
will be nice if i have spell ids to check :/

**Comment by Dranah** [comment]
nvm it's not only holy.
"Dark Slash" by king ymiron is also going through
spell ID 48292

Also for Val'kyr protector's smite: spell ID 71841

**Comment by Ashamedlol** [comment]
@Keader Get a protection paladin, let him use holy shield and get another paladin of any specs to attack that paladin while having divine shield on, you'll get damaged through.

Same thing goes for Nibelung, get any caster to trigger the proc then use divine shield, you'll get damaged through by the val'kyr of the proc, provided the ID for the staff+val'kyr but forgot the smite id :p.

**Comment by Keader** [comment]
Fixed and confirmed.
But still, has other case that was ignoring imune?
