### ISSUE TITLE
[Quest] Hellfire Fortifications

### ISSUE THREAD

**Issue by gamer100** [WoWManiaUK/Redemption#2543]
http://www.wow-mania.com/armory/?quest=10106
http://www.wow-mania.com/armory/?quest=10106#conditions
This npc is only showing as a vendor  and  dont give the quest.
The player is up  to date, with client and  launcher, deleted cache and tried it with addons disabled.
![image](https://user-images.githubusercontent.com/33811022/41512580-291c7f30-728b-11e8-8df4-86f08a8b5d3d.png)
![image](https://user-images.githubusercontent.com/33811022/41512583-361db140-728b-11e8-93d0-2d26d2abf6cf.png)
To  check or it have to  do  with  reputation i have changed  my reputation from neutral  till  friendly  and still the npc  wont give  quest

**Comment by TenmanWoW** [comment]
I checked this NPC at all reputation levels on PTR and up until friendly on Red. I have the same results as the above screenshot. 

This repeatable quest should be available at 55 without any prequisites.

**Comment by GM-Gathios** [comment]
This issue still persist, ticket #664 Diletta states it's acting as a normal vendor

**Comment by wow-mania** [comment]
THis works. I have tested. It does if you don't have the previous quest.
