### ISSUE TITLE
Account Recovery

### ISSUE THREAD

**Issue by Greyskull24** [WoWManiaUK/Redemption#2545]
Hey Guys,

I opened a ticket in game about recovering my old account and was directed here. It was around two years ago that I had an account with mostly Alliance characters but when it came to starting back up on Wow-mania I couldn't recall the email I had used or account name. Is there any way to recover those old characters? I had a Shaman named Relief, and a human Death Knight if I recall correctly. 

If these characters have been lost to a digital graveyard, I understand and will mourn accordingly. Thanks.

**Comment by fvicaria** [comment]
Sorry, this repository is for server issues only.
If you have a problem with your ccount you should send an email to support.
