### ISSUE TITLE
[Quest] A Fall From Grace complete but not complete enough

### ISSUE THREAD

**Issue by stealer05172** [WoWManiaUK/Redemption#2548]
http://www.wowhead.com/quest=12274/a-fall-from-grace

The quest itself completes just fine. Both requirements (speak to high abbot and abbey bell rung) complete just fine.
But when you run back to the quest giver Agent Skully the question mark over her head is gray, and when you try to turn it in the quest the button is grayed out.
I've done the quest 3 times now and it hasn't worked. Every time it will be "complete", but not complete enough for Agent Skully. Doesn't matter if I'm still shape shifted, de shapeshifted during the quest, or de shapshifted after completing it.
It's worked fine on my other characters in the past.

![wowscrnshot_061918_205514](https://user-images.githubusercontent.com/12975839/41633274-a8978ad8-7403-11e8-9c6c-2bb01f7b3bb4.jpg)

**Comment by fvicaria** [comment]
Works. You need to stay close to the NPC before he jumps.

**Comment by stealer05172** [comment]
I was like 3 feet away from him.
Do you have to stand inside of him or something?

**Comment by fvicaria** [comment]
As I can see in the image the objects were completed but your client was not so the quest is grayed. You can either do it again or ask a GM to reward it.
