### ISSUE TITLE
[Achievement] Burning Hot Pole Dance

### ISSUE THREAD

**Issue by mephorash** [WoWManiaUK/Redemption#2549]
http://www.wow-mania.com/armory?achievement=271

Linked achievement (Burning Hot Pole Dance) is bugged but still obtainable. It should require (http://www.wow-mania.com/armory/?spell=58934) which is the serverside achievement of having full Midsummer Reveler clothing set equipped, but it gives the achievement regardless. Clothing set is the Midsummer Reveler (http://www.wow-mania.com/armory/?itemset=785), which has 3 pieces, visible on the link.

**Comment by fvicaria** [comment]
Pretty sure both of them work.
