### ISSUE TITLE
[Item] Mail LK Set

### ISSUE THREAD

**Issue by Boyangy** [WoWManiaUK/Redemption#2551]
Hi I have just bought a mail LK set and the stats on it seem to be disappointing. There are 3 spellcaster pieces in the set and 2 set bonuses for hunter (if the set was made for hunter i dont see a reason for the 3 spellcaster pieces) and i don't really benefit from these stats as an Enhancement Shaman. I am wondering if there can be a revamp on the mail set since the plate set is really good and viable for both protection and dps spec but the mail LK set weirdly has 3 spellcaster pieces which is not viable for caster mail classes nor for agility mail classes.

**Comment by TheManiax** [comment]
This is not a bug report to be placed in GitHub.
If you have a suggestion or a demand, use Forums please.
