### ISSUE TITLE
[Quest] Of Thistleheads and Eggs...

### ISSUE THREAD

**Issue by voidwalker21** [WoWManiaUK/Redemption#2552]
http://www.wow-mania.com/armory/?quest=10547 you don t get quest item

**Comment by gamer100** [comment]
I have done it also you can open the eggs , but they are  empty

**Comment by TenmanWoW** [comment]
Quest - http://www.wow-mania.com/armory/?quest=10547
Quest Item - http://www.wow-mania.com/armory/?item=30500

The object does spawn in multiple places in the given area. However, the egg itself just inflicts a DoT. I checked 20 eggs or so and the quest item never dropped.

![wowscrnshot_062218_143306](https://user-images.githubusercontent.com/25806987/41795738-78839aa8-7629-11e8-8b6d-3a363c884ff6.jpg)
![wowscrnshot_062218_143232](https://user-images.githubusercontent.com/25806987/41795739-78956f12-7629-11e8-8f71-8e6567a2e777.jpg)

**Comment by wow-mania** [comment]
Pretty sure it works.

**Comment by wow-mania** [comment]
![image](https://user-images.githubusercontent.com/12248683/41799135-3270de38-7668-11e8-9794-6dd9ee18e3c4.png)
There is only one egg that gives the item.
![image](https://user-images.githubusercontent.com/12248683/41799168-4999b404-7668-11e8-9766-a3d1356174ba.png)
