### ISSUE TITLE
[Achievement] Torch Juggler

### ISSUE THREAD

**Issue by cathyr1** [WoWManiaUK/Redemption#2553]
This achievment http://www.wow-mania.com/armory/?achievement=272 doesn´t work. I spent tokens for 40 torches, used them in less than 15 seconds but no one torch was count as I watched it.

All other achives in this world event could be done, just except this one, as you can see on my screenshot.
![achive](https://user-images.githubusercontent.com/30184491/41796639-a0c23536-7667-11e8-8ea0-24483ee36e20.png)

**Comment by Keader** [comment]
Dup? #2550

**Comment by cathyr1** [comment]
This is achievment, that one is quest, so its different. But maybe the type of the mistake is the same.

**Comment by jokeruwd** [comment]
Not fixed... quest line for actually catching torches does not work still.

**Comment by wow-mania** [comment]
FFS this is fixed in dev not in live. PLease spend time 5 min reading the wiki.
