### ISSUE TITLE
[Mount] Cindermane Charger

### ISSUE THREAD

**Issue by gamer100** [WoWManiaUK/Redemption#2554]
http://www.wow-mania.com/armory/?item=118515
The cindermane charger is a  ground and  flymount.
The  mount you can also use in  city's. Horde  works  fine, but alliance  cant use the  mount in there.
They can only mount outside  the city.

**Comment by wow-mania** [comment]
As-is mounts made to fly in Azeroth will not work as a ground mount. Known side-effect.
