### ISSUE TITLE
Fel Intelligence

### ISSUE THREAD

**Issue by crizefgm1** [WoWManiaUK/Redemption#2555]
Hello,

I have a bug to report...the fel intelligence spell from warlock pet....
I saw many this when i'm in party mode/raid...that the spell doesn't activate (manual/raid), then when i exit party mode the spell still won't activate (see screen shot)....this happens for a while ...2-3 weeks

best regards
![wowscrnshot_062318_231429](https://user-images.githubusercontent.com/40527264/41813287-898911a8-773b-11e8-9d0e-03e43ed55430.jpg)

**Comment by Keader** [comment]
It will active if pet or you enter in combat.

**Comment by Dranah** [comment]
The reason for this is that when you party with a mage or a priest, and they use their intellect or spirit buff, it gives an 1hour buff that fully overwrites Fel Intelligence (yes its a bug, they should coexist with only the higher of the stats given being considered, it's been reported https://github.com/WoWManiaUK/Redemption/issues/2314 and cannot be fixed at the current state of core).
When you leave party/raid, you lose those buffs, but your pet does not. So long as the buffs exist on him, he cannot activate Fel Intelligence.
The way to fix this is to dismiss and resummon the pet , which means your pet will lose all raid buffs and can now activate his own. (note, casting summon without dismiss first will NOT remove buffs from the pet).
