### ISSUE TITLE
[Spell] Dancing Rune Weapon

### ISSUE THREAD

**Issue by Ashamedlol** [WoWManiaUK/Redemption#2557]
![drw](https://user-images.githubusercontent.com/16576459/41863305-01dacd6c-78af-11e8-85ae-9b5765f6f12a.png)

Tooltip says: Summons a second rune weapon that fights on its own for 12 sec, doing the same attacks as the Death Knight but for 50% reduced damage.

As seen, DRW isn't even dealing 50% of the damage the DK is dealing including dual crits (on both sides critting, still not 50%) and this is coming from a 100% ARP DK friend.

Spell ID: http://www.wow-mania.com/armory/?spell=49028

**Comment by Keader** [comment]
it was not fixed? https://github.com/WoWManiaUK/Redemption/issues/1719

**Comment by Ashamedlol** [comment]
If it was fixed, numbers would say otherwise.

**Comment by Keader** [comment]
Without pet stat system, this is more close that we can get.

**Comment by Ashamedlol** [comment]
But it's almost impossible to do proper dps on blood if this + bloodworm are broken.
