### ISSUE TITLE
account blocked

### ISSUE THREAD

**Issue by aratros** [WoWManiaUK/Redemption#2560]
Hi, i have a trouble with my account,  i tried to change the language of the game to spanish, i downloaded the esMX spanish pack, i changed the wft file and redirect the data folder, and also the realmlist in order to put the realmlist of wowmania, all worked until that, i opened the game, menus and game in spanish, i can see my character (a death rogue lvl 15) but at the moment of login the server kick me out, so i create another character but it happens the same, so i decided to leave in english the client again, but the problem persist, i deleted the game and i downloaded the client of wowmania from the page with the torrent, but now, always kick me out when i try to login, can you help me? my account is called aratros, I will apreciate your help.

**Comment by gamer100** [comment]
Hello Aratros.
This  you better can post on the  forum, this  is  for bugs in game.
Please contact support cause it has to  do  with the  ip that is with proxy or vpn. And that is  not accepted. At support they can help  you  with that

Mail: Support@wow-mania.com
Skype: Wow-Mania Private Servers

Gamer100

**Comment by aratros** [comment]
Ty, yes I was using a vpn client, as son I deactivated the game works fine again, ty for your support and fast respond.

**Comment by wow-mania** [comment]
Please read the wiki before posting here.
