### ISSUE TITLE
[Quest]

### ISSUE THREAD

**Issue by carriestienen** [WoWManiaUK/Redemption#2561]
Unable to get a another Earth Sapta from canaga earthcaller for Call of Earth. I made another character and was able to do it on that.

**Comment by TheManiax** [comment]
Please follow the procedure described below before creating a new issue:
[How to Properly Report an Issue](https://github.com/wow-mania/Redemption/wiki/How-to-Properly-Report-an-Issue)

This will help developers identify and fix the issue quicker. Incorrectly or unclear reports will simply be deleted.

**Comment by Dranah** [comment]
If you are able to do it on your other character, it's probably not a general bug. You may want to contact a GM (make a ticket) to help the character that is bugged.
