### ISSUE TITLE
[Spell] Frostfire Bolt

### ISSUE THREAD

**Issue by cathyr1** [WoWManiaUK/Redemption#2562]
Please check this spell http://www.wow-mania.com/armory/?spell=44614.

This spell should be checked against the lower of the target's Frost and Fire resists. So only one should count = the one to that the target is more vulnerable. But when the target is immune to one of these schools of magic, he is immune to entire spell, which in my opinion denies how it should work.

For exapmple Frost Lord Ahune is immune to frost but vulnerable to fire and his frost immunity causes immunity to Frosfire Bolt. The same situation happens when the target is immune to fire but vulnerable to frost.

**Comment by Dranah** [comment]
Can't really find video evidence for spell behavior but as far as I recall, the main reason this spell was introduced by blizzard at all, was to unfuck mages that got fucked by fights such as ahune. So I give this an upvote.

**Comment by TenmanWoW** [comment]
This mage also agrees.

**Comment by cathyr1** [comment]
Why closed without any information provided? Does the spell work correctly when either one or another one immunity means immunity to entire spell? I don´t think so but need any confirmation.

**Comment by wow-mania** [comment]
Sorry I did not mean to close it.

**Comment by Dranah** [comment]
https://frostisthenewblack.wordpress.com/2010/06/22/frosty-foes-ahune/ comments found in this thread from 2010 confirm that frost mages who have trouble with ahune should simply switch rotation to Frostfire Bolt instead (and that frostfire-mages had no trouble dpsing him)

**Comment by Keader** [comment]
Check tomorrow pls

**Comment by Keader** [comment]
Making a new fix.
