### ISSUE TITLE
Profession skill bug

### ISSUE THREAD

**Issue by thepreast** [WoWManiaUK/Redemption#2563]
Hi. I have 80 paladin character and i leveled up 2 profession: jewelcrafting and mining. And now i wanted to change mining with enchanting so i quit mining, i went to wow-mania mall and used 300 maniac points to learn profession enchanting but enchanting icon doesn't appear in my skillbook / abilities, so i can't acces it. I went to Dalaran and learnt from trainer all the recipes but not even then didn't showed up. I restarted the game, i cleared cache, cookies but still no icon. I made ticket, a GM came and was willing to help me but need to quit first on that enchanting skill first but i can't - doesn't have any additional mark near, as u can see in my attached screenshot. Please, help me with this. Thank you.
![profession skill bug](https://user-images.githubusercontent.com/40723420/42128480-4672c3e4-7cb5-11e8-983b-caa5198a6e20.jpg)

**Comment by wow-mania** [comment]
You cannot have more than 2 professions.
1. you need to drop one of them
2. you need to learn the prof you want
The profession boost is exactly what is says on the tin, just a boost of the skill level.

**Comment by thepreast** [comment]
But I can't drop enchanting now. That's why I post the screenshot - there is no mark on the right to make it available for dropping off.

**Comment by TheManiax** [comment]
@thepreast 
It's not a bug, as stated already; what you get through profession boost is the skill levels, But you still need to learn the abilities.
Go to honor hold and visite [[Johan Barnes]](http://www.wow-mania.com/armory/?npc=18773)
Learn the skills as shown in the picture, and the unlearn icon will appear.
![image](https://user-images.githubusercontent.com/14857593/42136780-f9101954-7d76-11e8-982e-988b8a6dea95.png)
