### ISSUE TITLE
[PvP] Halaa

### ISSUE THREAD

**Issue by NightSeekerr** [WoWManiaUK/Redemption#2564]
Hello. There are a few issues with the Halaa PvP zone in Nagrand. 

First one is that the Halaa Battle Token (http://www.wow-mania.com/armory/?item=26045) is unobtainable. It should be obtained by killing members of the opposing faction, that give Honor Points, in Halaa or near it. Today I killed a lvl 80 enemy player in Halaa more than once and I didn't get any Halaa Battle Tokens, I only got Honor Points.

Second issue is with the quest "In Defense of Halaa" (http://www.wow-mania.com/armory/?quest=11502). It requires you to "defeat 10 enemy players in Halaa", but the kills I got at Halaa didn't count for the quest.

Third issue is with the Alliance PvP vendor - Quartermaster Davian Vaclav (http://www.wow-mania.com/armory/?npc=18822). It doesn't spawn after Halaa is captured by the Alliance. Waiting doesn't help either, hours later the NPC is still missing.

**Comment by wow-mania** [comment]
All of them are a single issue.
Should be working on dev.
