### ISSUE TITLE
[Spell] Flames of Failure

### ISSUE THREAD

**Issue by Ashamedlol** [WoWManiaUK/Redemption#2566]
After failing the torch juggling, you get a debuff called Flames of Failure that does 1% of your hp every second for 5 seconds, however it's scaling with SP here so casters are getting 1-shot from having a failed juggle. It should only do the 5%.

Spell ID: http://www.wow-mania.com/armory/?spell=45699

**Comment by cathyr1** [comment]
This is probably a bug, but you can avoid IK if you put your gear off.

**Comment by Keader** [comment]
Fixed.
