### ISSUE TITLE
[Spell] Raise Ally

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#2568]
Spell ID 61999

How it should work:
Raises a dead party/raid member as a ghoul for 5minutes, giving him same stats and abilities as your own ghoul has via Raise Dead. (note, they receive coefficients from the caster Death knight (attack power, stamina etc), but DONT become a pet under your commands, they receive same main action bar as your ghoul pet-bar and they need to play on their own)
This is probably similar transformation to becoming a vampire on blood-queen fight, where players receive a buff and a new action bar upon becoming thirsty. (although here the target needs to be revived too - just an idea)

How it works atm:
The ghoul spawns with 1/1 health and dies instantly to a breeze. This makes it essentially useless.

**Comment by Keader** [comment]
Raise Ally is working, but ghoul  has wrong stamina values.
So main issue in this topic is wrong xD
Anyway, Ghoul need fix. Working on it.

**Comment by Dranah** [comment]
Edited with new info - point stands :D

**Comment by Dranah** [comment]
ghoul has now proper stamina
need to fix (or at least increase) his damage

**Comment by Dranah** [comment]
no change on his damage yet @Keader

**Comment by Keader** [comment]
Now is more blizzlike possible.
