### ISSUE TITLE
NPC: Thassarian in Icecrown is missing

### ISSUE THREAD

**Issue by GM-Gathios** [WoWManiaUK/Redemption#2569]
http://www.wowhead.com/npc=29799/thassarian

The NPC Thassarian located in Icecrown standing on a Stormbreaker is missing.

**Comment by TenmanWoW** [comment]
Below is how it currently looks. I am standing where THassarian should be.

![wowscrnshot_070518_160920](https://user-images.githubusercontent.com/25806987/42348112-d3b20f42-806d-11e8-89a4-8b06d1693e54.jpg)


Would like to point out that the same spot on dev has Lurid and a guard standing in these same places, but not Thassarian.

![wowscrnshot_070518_161242](https://user-images.githubusercontent.com/25806987/42348232-447042f8-806e-11e8-992e-6c43537d5807.jpg)

**Comment by TenmanWoW** [comment]
I manually added and deleted thassarian to check if the NPC was broke from a player point of view. It is working the same as before, with the exception of the NPC being a female belf model/voice when it should be human DK model/voice.

**Comment by TheManiax** [comment]
It's a known issue.
They will be back ASAP.
We are working on a permanent fix.
Thanks for the report anyway.

**Comment by GM-Gathios** [comment]
Thassarian is missing again.

**Comment by wow-mania** [comment]
This is not something that we fix. It needs restarting.
Will be dorted on the next restart.
