### ISSUE TITLE
[NPC] Imp Minion

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#2570]
http://www.wowhead.com/npc=12922/imp-minion

This is the generic imp pets summoned by warlock NPCs, including Burning Blade Cultists http://www.wowhead.com/npc=3199 in Durotar, objective for a part of shamans fire totem chain. (shaman's must-do quest chain)
These minions should have their health, mana and damage scaling with their level depending on which NPC they accompany, but the scaling is wrong in case of NPC=3199.

NPC=3199, they are level 9-10 mobs, and should have their companions match this level:
NPC info shows the imps' base health is 64, and maximum health is 1031 (probably at lvl 80).
At level 10, they should have 80-100 health at most, but currently have their maximal 1031 health instead.
Same goes for their mana, which is currently the maximum of 2398, which is as much as a level 80 pet should have.
Same goes for their melee physical attacks, which is around 50-100 base damage atm (a level 80 imps melee swings).

Intended numbers are approximately 80 health, 300 mana, and melee swings of 5-10. (their firebolt hits for 15-20, that is normal and it is meant to be their stronger attack)
This makes the quest painful to complete for newly leveling shamans.

**Comment by squalllh1989** [comment]
Not fixed, i found a bunch of those imp here in the cave with over 1k hp at level 10

**Comment by squalllh1989** [comment]
![wowscrnshot_070918_193737](https://user-images.githubusercontent.com/27235989/42450819-9dc6d576-83af-11e8-94d4-c3a17d7c4f39.jpg)

**Comment by Keader** [comment]
Melee damage fixed.
Just waiting new build to see if hp/mana is fixed too

**Comment by Dranah** [comment]
Fixes aren't active on PTR yet, just on keader's test server. Give it a day or two.
