### ISSUE TITLE
Artifact Transmog Weapon - Odyn's Fury (Warswords of the Valarjar)

### ISSUE THREAD

**Issue by Gorelicious** [WoWManiaUK/Redemption#2575]
Hello,

this sword [Odyn's Fury (Warswords of the Valarjar)] is supposed to be worn on the back but the character wears it on his hips. Please fix it as it looks way better on the back.
Thanks

**Comment by wow-mania** [comment]
Unfortunately, this cannot be fixed due to client limitation. This was an import from later versions of the client and it cannot be rendered on the back.
