### ISSUE TITLE
[Quest] The Reckoning

### ISSUE THREAD

**Issue by Nocturnus23** [WoWManiaUK/Redemption#2580]
Picked up quest.  Arrived at the location but nothing happened.   Tried dropping and picking the quest back up, restarting the client, and deleted the cache.  Still no avail.  Thorim and Veranus are here, but are not leaving their initial positions.

**Comment by wow-mania** [comment]
http://www.wow-mania.com/armory/?quest=13047

**Comment by wow-mania** [comment]
![image](https://user-images.githubusercontent.com/12248683/42557272-ebd5e108-84e5-11e8-92ff-105eb238b8ad.png)
Seems to work fine.
Maybe NPC got stuck for some reason.
