### ISSUE TITLE
[Quest] Clefthoof Mastery

### ISSUE THREAD

**Issue by KonradWallenrod** [WoWManiaUK/Redemption#2582]
Quest is about killing 12 aforementioned beasts. When killed one, two notations appeared:
 "Clefthoof slain: 1" "Clefthoof slain: 2". And so, I have finalized it whole with just 6 murders.

The same way is with the next in series (the same name), and with other beasts too:
 "Talbuk Mastery" "Windrock Mastery"

It is not problematic at all. Just not proper.

**Comment by KonradWallenrod** [comment]
![wowscrnshot_071318_014549](https://user-images.githubusercontent.com/41172273/42665164-a68a9ddc-863e-11e8-9075-737d1f079a9c.jpg)

**Comment by KonradWallenrod** [comment]
![wowscrnshot_071318_015343](https://user-images.githubusercontent.com/41172273/42665367-9caae15e-863f-11e8-8b38-ee3deb088e49.jpg)

**Comment by TenmanWoW** [comment]
Quest : Clefthoof Mastery (9851)
NPC: Clefthoof (18205)

How it should work:

    Kill 12 Clefthoof and return to NPC.


How it currently works:

  Killing a single clefthoof gives double credit.



![image](https://user-images.githubusercontent.com/25806987/42665996-cc65278e-8607-11e8-8848-08c7dab14790.png)

**Comment by Keader** [comment]
#2588
