### ISSUE TITLE
Crusader Olakin Sainrith phases out

### ISSUE THREAD

**Issue by ggosse52** [WoWManiaUK/Redemption#2583]
Hi
I have completed the quest "Jagged Shards" btu when I go tot he NPC to hand in, he fades out and I cant hand it in.

I can see the ? mark on the map but he just fades away as I arrive

I wonder of this might have something to do with my having completed the quest to reassemble his body parts before completing Jagged Shards ?

**Comment by ggosse52** [comment]
Ha ha. How did you get a level one to Icecrown :) - dont tell me.

No worries, Ill just drop the quest

Kind regards,

*Graeme Gosse*

Mobile  +61 401127679

Business website       www.graemeg.acndirect.com

**Comment by TheManiax** [comment]
There are several quests there
taking the quests in a specific order will get you stuck there in a phase where you can't see olakin
it's not the NPC issue
It's a quest which I didn't have time to find
One of the quests there takes the player to a phase where they can't see Olakin as well as other NPCs up on the mountain there

**Comment by wow-mania** [comment]
As I said the NPC has phase mask 1, which means it can be seen by all.
The only thing I can think of is some quest that changes your phase or aura that makes you not see NPCs.
In that case, you must finish the quest or quest chain.
