### ISSUE TITLE
Preparations for War

### ISSUE THREAD

**Issue by ggosse52** [WoWManiaUK/Redemption#2584]
The quest "Preparations for War" requires the player to take a flight from Dalaran to the Skybreaker after speaking to Officer Van Rossen at Krauses Landing
Once aboard Skybreaker, we are supposed to speak with High Captain Justin Bartlett.

The yellow question mark can be seen on the map but High Captain Justin Bartlett seems to be AWOL because he just isn't on board. I searched every deck and clicked on every NPC..maybe its a case of man overboard :)
http://www.wowhead.com/npc=30344/high-captain-justin-bartlett

**Comment by TheManiax** [comment]
There is the possibility that the NPC is killed or dropped off the ship
Try it again later, if not, make a ticket and ask a GM if he can find the NPC
Though we are already working on the ICC ship NPCs so they will be invulnerable.
