### ISSUE TITLE
[Quest] double credit

### ISSUE THREAD

**Issue by WhitephoenixTheBunny** [WoWManiaUK/Redemption#2588]
Some quests are giving double credits, those are the ones I found so far.
In Icecrown:
Leave Our Mark
(http://www.wow-mania.com/armory/?quest=12995)
From Their Corpses, Rise!
(http://www.wow-mania.com/armory/?quest=12813)

In Nagrand:
Windroc Mastery
(http://www.wow-mania.com/armory/?quest=9854)
Talbuk Mastery
(http://www.wow-mania.com/armory/?quest=9857)
Clefthoof Mastery
(http://www.wow-mania.com/armory/?quest=9789)

![screenshot_76](https://user-images.githubusercontent.com/31921098/42725626-d26fbb94-877e-11e8-8570-e7fe08b0f067.jpg)
![screenshot_77](https://user-images.githubusercontent.com/31921098/42725627-d28d01e0-877e-11e8-8b26-a488641d1c88.jpg)
![screenshot_78](https://user-images.githubusercontent.com/31921098/42725628-d2ac2138-877e-11e8-88c7-5957a73cfbc1.jpg)
![screenshot_79](https://user-images.githubusercontent.com/31921098/42725629-d2ca1b0c-877e-11e8-8e94-6b88ab8befb3.jpg)
![screenshot_80](https://user-images.githubusercontent.com/31921098/42725630-d2e6723e-877e-11e8-8fdf-7d68a6276941.jpg)

**Comment by Keader** [comment]
Same of (#2582)
But i will keep this open, more generic bug.

**Comment by Keader** [comment]
Nagrand dual credit fixed

**Comment by Keader** [comment]
All quest reported, fixed.

**Comment by jayz0n09** [comment]
Quest: Leave Our Mark
http://www.wow-mania.com/armory/?quest=12995
getting double credit again as off this post.
