### ISSUE TITLE
[Spell] Unstable Sun Beam

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#2589]
http://www.wowhead.com/spell=62243
This is used by NPC Elder Brightleaf, one of Freya's mini bosses, when he is engaged on his own. http://www.wowhead.com/npc=32915

The problem with the spell is that the number of Sun Beams spawned at once seem to scale with player count around the NPC. (very similar problem to what happened with Vesperon's twilight torment debuff).

It should spawn one single beam at once, but if there is 1 player testing, it spawns 2 (one for Brightleaf and one for the player), and for a full raid it spawns 10+, all on top of each other.
These 10+ beams apply their debuff effects separately , so the boss gains 10+ auras that instant heal him to full before you have a chance to move him. And players who attempt to get the buff from the beam will get one-shot killed because it applies so many stacks at once that it instantly explodes them with unstable energy.

The spell otherwise works fine, there is just too many of it.

**Comment by Keader** [comment]
Fixed

**Comment by Dranah** [comment]
Summons only one beam now.
