### ISSUE TITLE
[Quest] Kartak's Rampage

### ISSUE THREAD

**Issue by lemonlimes** [WoWManiaUK/Redemption#2590]
Killing sparktouched oracles is supposed to drop http://www.wowhead.com/item=39265/oracle-blood in order to speed up this daily quest. I have almost killed the entire quota of 50 sparktouched gorloc's and am still yet to see a blood drop. The drop rate appears to be incredibly low. I only finally found the blood on my 38th kill.

**Comment by Dranah** [comment]
I'm not sure if you took a closer look at the wowhead page you linked, but there it is stated that the drop chance is around 1,9%. That is indeed incredibly low but is not a bug.

**Comment by lemonlimes** [comment]
hmm perhaps you're right. I don't recall ever having this issue when doing this daily on retail...
