### ISSUE TITLE
[Quest] It Rolls Downhill

### ISSUE THREAD

**Issue by squalllh1989** [WoWManiaUK/Redemption#2592]
[This quest](http://www.wow-mania.com/armory/?quest=12673) require you to use [Scepter of Suggestion](http://www.wow-mania.com/armory/?item=39157) on a [Blight Geist](http://www.wow-mania.com/armory/?npc=28750) to take control over it (it will follow you as a pet) then use the ability you gain when has it under control, [Harvest Blight Crystal](http://www.wow-mania.com/armory/?spell=52245) to send it to a crystal and havest it. Currently after control the geist, you didn't gain the new spell so you can't send the geist to havest, make this quest uncompleteable.

**Comment by wow-mania** [comment]
It works. Search the previous posts on this issue.

**Comment by squalllh1989** [comment]
yeah it work now, i didn't understand, last time i tried this the pet bar doesn't appear so i can't use the command at all....
