### ISSUE TITLE
Sindragosa and Unchained Magic debuff on hunters

### ISSUE THREAD

**Issue by crulinjr** [WoWManiaUK/Redemption#2593]
Unchained Magic: http://www.wowhead.com/spell=69762/unchained-magic
Chilled to the Bones: http://www.wowhead.com/spell=70106/chilled-to-the-bone

How to reproduce:
Just play as a hunter during a Sindragosa fight. You may or may not get hit by Unchained Magic depending on rng.
If hit by Unchained Magic, casting Arcane Shot or having Serpent Sting on Sindragosa will get you stacks of Instability.

How it should work:
Hunters should not get the Unchained Magic debuff at all since they already get the Chilled to the Bones debuff from hitting Sindra
with physical attacks.

What is happening: 
Apparently Hunters are being treated as dps casters which they are not.

**Comment by TenmanWoW** [comment]
I agree with your assessment of the mechanics of the fight. However, I also don't see anything wrong here. It's just a tough fight for a hunter to be in. The exact same could be said for enhancement shamans. 

Much like the LDW fight where having too much ranged DPS causes a wipe, 

Casters (mage, in my case) also get stuck with stacks of Unchained Magic if they get the debuff after firing off a volley of missles that have not impacted Sindy.

It's a tricky fight, rightlyfullly called the hardest one in ICC.

**Comment by crulinjr** [comment]
On retail hunters didnt get this debuff. Have done a lot of research about
it. Thats why im putting the issue. The idea behind the Chilled of the
bones debuff and the unchained magic is that each class could get one may
it be unchained or chilled but no both.

2018-07-16 13:50 GMT-05:00 TenmanWoW <notifications@github.com>:

**Comment by Dranah** [comment]
Actually you're half-right, hunters are not meant to be primary targets for Unchained Magic, but they are possible secondary targets if the raid composition is lacking on casters.
I have already reported this https://github.com/WoWManiaUK/Redemption/issues/2263 but it was dismissed by Janitor. Perhaps now that there are less open reports, it can receive some attention.

**Comment by crulinjr** [comment]
yes maybe you are right but since you will always have healers, a hunter
should not be getting this debuff.

2018-07-16 14:37 GMT-05:00 Dranah <notifications@github.com>:

**Comment by crulinjr** [comment]
exactly but since the hunters have Chilled to the bones they are not
targeted. I've read comments from retail players and a warlock said he had
100% uptime on Unchained magic due to his party beign hunters mdps and
healers.

2018-07-16 15:27 GMT-05:00 Dranah <notifications@github.com>:

**Comment by Dranah** [comment]
That's what I said. If there is normal caster, a hunter should never get it. Only if there are no real caster DPS.

**Comment by crulinjr** [comment]
yes you are right. Hope this gets fixed.

2018-07-16 16:47 GMT-05:00 Dranah <notifications@github.com>:

**Comment by wow-mania** [comment]
Attempt to improve it.

**Comment by Dranah** [comment]
After fix , now hunters are not eligible targets for the debuff at all anymore. That's not an improvement, that's a step back before blizzard patchfix. This means if the raid only brings hunters as ranged, nobody is getting debuffed, or only the healers are. This also does not help retris and enhas.

**Comment by crulinjr** [comment]
Im there with you but why pm earth Ford a raid would bring only hunters?

**Comment by Dranah** [comment]
Apparently, on retail it was a thing before blizzard patchfixed the spell, but that isn't the point anyway.
I'm just saying it doesn't solve the main issue with the spell, which is that it has no priorities among cast targets.

**Comment by wow-mania** [comment]
It will remain as it is in Redemption.

**Comment by crulinjr** [comment]
The lag we had yesterday was because of the changes you made?

**Comment by crulinjr** [comment]
So no Fix?

**Comment by wow-mania** [comment]
There was nothing done to Redemption I am talking about PTR.
There will be nothing more done on this issue for now so it will stay as it is now.
