### ISSUE TITLE
Night Elf Ghost form

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#2594]
Ghost - Spell ID 8326
Night elf racial "Wisp Spirit" - Spell ID 20585

There is a problem with night elves being unable to fly in ghost form in areas where other players can fly as ghosts. (Tested in Wintergrasp and Wyrmrest temple)
Other players receive a ghost gryphon in these areas, night elves assume their usual Wisp form, but it cannot fly.
The way it should work is that night elves also receive gryphon and their racial effect adds the 75% speed to that (not replaces the fly effect)

**Comment by Dranah** [comment]
Night elf flight in WG is now fixed.
Still does not work near wyrmrest though. That is less of an inconvenience because you dont need fly form to get to your corpse most of the time. But there may be other areas with similar problem.

**Comment by Keader** [comment]
Go to the area, and use .gps Commander
Pass to me the output

**Comment by Keader** [comment]
In Map: 571 (Northrend) Zone: 65 (Dragonblight) Area: 4254 (The Dragon Wastes), was missing.
Inside of temple i can fly normally.
So... it's fixed.
