### ISSUE TITLE
Changed race to Goblin, can't finish argent tournament dailies. 

### ISSUE THREAD

**Issue by xandror** [WoWManiaUK/Redemption#2599]
I finished 4 of the 5 faction champions and changed race from undead to goblin. now I can't get the quest http://www.wow-mania.com/armory/?quest=13720 to continue the dailies. I can't get any argent tournament quests at all but i can get dailies for the champion seals (although i'll never be able to spend any without finishing that quest). 

Characters name is Picklepants.

**Comment by wow-mania** [comment]
Same reply as in the forum post. It is not a race or quest issue.
It is more likely a consequence of the change faction.
So unless we have steps to reproduce it's unlikely that we will be doing anything about it.
