### ISSUE TITLE
[NPC] Stormcaller Brundir

### ISSUE THREAD

**Issue by Ashamedlol** [WoWManiaUK/Redemption#2600]
Located in the Iron Assembly encounter of Ulduar:
The shield is supposed to be on Stormcaller Brundir (http://www.wow-mania.com/armory/?npc=32857) which makes him deal 250 damage on each attack he recieves back (somewhat like thorns), and granting him STUN immunity.

He gains the Shield when he's casting Overload (10m: http://www.wow-mania.com/armory/?spell=61878/ 25m: http://www.wow-mania.com/armory/?spell=63481) and when he's the last one alive between the Assembly of Iron (Runemaster Molgeim and Steelbreaker).

He's currently immune to stuns in general, he shouldn't be as the spell is the thing that gives him the immunity unless under the effects of Lightning Tendrils (So immune during overload and phase 3 by Stormshield, Lightning Tendrils already giving him immunity as a buff).

Spell ID: http://www.wow-mania.com/armory/?spell=64187

**Comment by Dranah** [comment]
Stormshield is properly applied if Brundir is the last boss alive.

I can confirm it isn't applied when he casts Overload though. Also when he casts Overload, a dummy NPC appears called "Overload Visual" which begins chasing healers. It doesn't really do anything it just looks stupid.

**Comment by Dranah** [comment]
Brundir is now able to buff himself with Stormshield even if he's casting something else at the time.

There is no change on his stun immunity, and he also does not gain Stormshield when casting Overload.

**Comment by Dranah** [comment]
Brundir is no longer stun immune before gaining Stormshield.
he properly shields during overload and after he remains alone
