### ISSUE TITLE
Origrimar Interceptor

### ISSUE THREAD

**Issue by Varenine** [WoWManiaUK/Redemption#2604]
I purchased the Orgrimar Interceptor because I thought it was a two person mount. It does not seem that it is in fact a two person mount. Is it possible I am doing something wrong? or can I switch it for a two person mount like the rocket? Thank you for your help in advanced.

**Comment by wow-mania** [comment]
As-is. In no place we refer to this mount as a two-seat mount. This is not a server issue.
If you wish to switch contact me via support email and send your character name please.
