### ISSUE TITLE
[Quest] Dimensius the All-Devouring

### ISSUE THREAD

**Issue by KonradWallenrod** [WoWManiaUK/Redemption#2605]
I killed the aforementioned boss, yet didn't get the notation about it, so was unable to complete the quest.

Have contacted with the GM - Mr. "Vousalan". Said, He cannot do a thing. Suggested
 to bring the problem here (for He has assumed it is a bug). And so - I did.

Wowhead's links:

Quest: http://www.wowhead.com/quest=10439/dimensius-the-all-devouring

NPC: http://www.wowhead.com/npc=19554/dimensius-the-all-devouring

**Comment by wow-mania** [comment]
Works.
This quest, as many others that use NPC assistance, will require you to do at least 50% of the damage or you will not get the credit for the kill.

**Comment by KonradWallenrod** [comment]
Thank U. For clarification - should I answer those e-mails, or this is just bother to U; other developers?Od: "Janitor" &lt;notifications@github.com&gt;Do: "WoWManiaUK/Redemption" &lt;Redemption@noreply.github.com&gt;; Wysłane: 8:57 Czwartek 2018-07-19Temat: Re: [WoWManiaUK/Redemption] [Quest] Dimensius the All-Devouring (#2605)Works.
This quest, as many others that use NPC assistance, will require you to do at least 50% of the damage or you will not get the credit for the kill.
