### ISSUE TITLE
wow-mania.com/vote page is trying to install a virus

### ISSUE THREAD

**Issue by Beelzybud** [WoWManiaUK/Redemption#2609]
Your website page wow-mania.com/vote (the vote page) appears to be trying to infect computers with a virus. I noticed the page was using very high CPU and, when first loaded, Microsoft Security Essentials (win7) would pop up showing it had blocked this virus: fBrocoiner!rfn

https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?name=Trojan%3aHTML%2fBrocoiner!rfn&threatid=2147724297&enterprise=0

I didn't know how to report this problem with your website so just decided to let you know here, hoping you could pass on the information. This happened earlier today, roughly 5pm pacific, and again just now 2:30 am pacific.

**Comment by wow-mania** [comment]
There is nothing being installed.
Check this post:
http://www.wow-mania.com/forum/viewtopic.php?p=5493
