### ISSUE TITLE
Blackwatch quest chain

### ISSUE THREAD

**Issue by Greywolf59** [WoWManiaUK/Redemption#2611]
Hello dear developers!
I would like to report an issue regarding Blackwatch chain quest (Icecrown).
Short Version: Some quests from chain are vailable before completing pre-requisite ones. After completing one such later quest, one of the two quest givers disappear and does nto return, so you can't turn in the quests that were supposed to be pre-requisite.
Details: QUESTGIVER: http://www.wowhead.com/npc=30708/crusader-olakin-sainrith
 PROBLEM 1: http://www.wowhead.com/quest=13138/im-smelting-smelting
→ this quests should be available only after finding quest-giving item and completing said quest; uncompletable if quest giver disappears
PROBLEM 2: http://www.wowhead.com/quest=13136/jagged-shards
→ afformentioned quest given by the item, uncompletable if quest giver disappears
PROBLEM 3: http://www.wowhead.com/quest=13144/killing-two-scourge-with-one-skeleton
Quests belonging to the chain leading to this quest are available even if you haven't completed quests in P1 and P2. If you complete this quest, Crusader Olakin is taken away by wyrm and although reanimated later, you can't turn in the quests P1 and P2, leaving them completed but unturnable.

Best regards,
Greywolf59

**Comment by wow-mania** [comment]
1. No requirement for this quest as in 3.3.5a so it is not an issue.
2. It has been noticed that there is an issue here but only if you miss something along the way.
3. Not a quest chain. This quest "requires" both quests as a condition but not specify the order to take them.
And they do close other quests. Meaning when you do a particular quest you will lose the ability to do some others. Check our Armory and not wowwiki as often as possible.

As I have explained in a previous similar issue. I have completed all the quests with a newly created char with no problem. I will investigate the visibility of the NPC which as far as I can see is the only possible issue here.

**Comment by Greywolf59** [comment]
Thank you for your attention and explanation and all the help you keep providing. And I am sorry for keeping to trouble you with stuff.

**Comment by wow-mania** [comment]
Please continue to inform us of everything you see that does not work as expected.
Read our wiki to learn how to provide the type of information developers need to fix the issue quicker.
I will be changing the visibility of the NPC by next restart.
Thanks a lot.
