### ISSUE TITLE
Maniac Points lost

### ISSUE THREAD

**Issue by Vertilio** [WoWManiaUK/Redemption#2612]
I have some months without playing and 2 days ago I came back to Wow Mania server.. I was trying to change my main toon from ally to horde and I was looking for the MP's of my other toons so I can transfer them to the main one, when clicked the mail on my 2nd toon with the MP's inside, they went to I don't know where and the GM told me to make this post.. I having headaches trying to get my MP's..

Also, I was told by the GM to delete my game cache and then, the windows inside the Character Info "Currency" dissappaired and now I am not able to see my emblems and etc.

Any help is aprecciate it.

**Comment by wow-mania** [comment]
Not the place for this. contact support but I will tell you now that MP don't just disappear.
