### ISSUE TITLE
[Spell] Holy Nova

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#2614]
ID 48078

As the tooltip says, "These effects cause no threat".
Nor the healing, nor the damage portion should generate any threat.

Problem is currently it does generate threat.
Threat must be set to zero for all of its effects.

**Comment by Dranah** [comment]
An unexpected side effect came up which is probably related to this fix:

If a priest is in party with others, as long as he only uses holy nova to damage and heal (no other spells), the priest isn't put in combat at all. (except in raids where bosses do pulses)
While the spell generates no numeric threat, it should put the priest in combat and on the threat list of affected enemies with a value of 0.

**Comment by Keader** [comment]
Test now @Dranah

**Comment by Dranah** [comment]
Looks good, now I always enter combat as intended.
