### ISSUE TITLE
[Spell] Empowered Flames

### ISSUE THREAD

**Issue by TenmanWoW** [WoWManiaUK/Redemption#2615]
Spell ID  72040 - Conjure Empowered Flames
              71718  - Conjure Flame

I do not know which ID is the root of the issue. 

"Conjures a ball of flame that flies through the air towards the target and explodes on impact."

Ice Block - 45438

"Encases you in a block of ice, protecting you from all attacks and damage for 10s..."

How it's working:

The spell Empowered Flame bypasses the immunity provided by ice block. The DoT damage is prevented, but the impact damage bypasses the immunity to all effect of ice block.

![wowscrnshot_072118_202829](https://user-images.githubusercontent.com/25806987/43049997-1c6497e4-8dc7-11e8-9827-012bf2afffc8.jpg)

How it should work:

  Any current DoT's are removed, threat is frozen while further direct physical, and direct spell will fail against the casting mage for the duration of Ice Block. At the end of Ice Block, threat is resumed, all DoT's are no longer active, and the mage is now again vulnerable to physical and spell damage.

**Comment by Dranah** [comment]
Ok so:
Conjure flame spell=71718 summons an NPC called Ball of Inferno Flame npc=38451 that you can see on the combat log who is casting Flames spell=71393 on you.
This Flames is the one to hit you through iceblock, thing is, on wowhead it has a flag "unaffected by invulnerability" which translates to ignoring bubbles and iceblocks.
To me that means it works as intended.

**Comment by TenmanWoW** [comment]
Then the tooltip of iceblock needs tweaking. Point is, the two tooltips are in conflict with each other.

**Comment by Keader** [comment]
No.
Alot of spells has unaffected by invulnerability flag. And all spells with this flag will ignore ALL IMMUNY spells.
Nothing wrong in tooltip here.
