### ISSUE TITLE
[Boss] Kologarn Arms

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#2617]
NPC ID 32930

There are two large encounter issues related to his Arms
http://www.wowhead.com/npc=32934/right-arm
http://www.wowhead.com/npc=32933/left-arm

1) The arms don't take off proper health.
How it should work: Every time an Arm dies, its health should be 1:1 deducted from Kologarn health.
This is 543k health on 10man mode (15% of total 3,6million hp)
And 2,3million on 25man mode (15% of total 15,9million hp)
Right now, regardless of difficulty, killing an arm takes off about 300k health (this makes 9% of the boss health on 10man, and barely 2% on 25man)
This makes the boss take ages to die, especially on 25man mode.

2) There is a problem with kill credit not being granted for the boss when you kill too many arms. 
As far as I can tell, it is when the damage done to his body by the Arms' deaths is larger than the total damage of players done to the body (exceeds 50% health). 
On 25man this won't happen atm due to arms taking almost no health off (see bug no.1 above) 
But on 10man it happens frequently especially when doing the Rubble and Roll achievement.
If more than 5 arms are killed, they will deal more than 50% of Kologarn Body health and the raid receives no credit for his defeat, ruining both Rubble and Roll achievement, and the regular Antechamber one too.

I suspect this happens because regular world mobs don't grant credit if more than 50% of their health is taken off by NPC source (like helping npcs in some quest areas), but this SHOULD NOT be in effect here.

**Comment by Dranah** [comment]
This issue have not been addressed before. XT-002 had similar type of bug with Heart not reducing his health, but is a completely different boss.

**Comment by Keader** [comment]
1 - The arms don't take off proper health.

True. it's caused by 2 spells.
Spell 1 - 63629 Arm Dead Damage Kologarn
Spell 2 - 63979 Arm Dead Damage Kologarn

Problem was: In 10 and 25 man, he always cast Spell1. But in 25 man he should cast Spell2.
Fixed this part.

**Comment by Keader** [comment]
2 - There is a problem with kill credit not being granted for the boss when you kill too many arms.

I belive that is fixed too.

**Comment by Keader** [comment]
I'm puting confirmed in dev, because credit part is fixed and spell just need attribute to ignore armor.
I send to janitor ignore armor already and tested in my server, works fine.
So... everything should be working fine in update tomorrow.

**Comment by Dranah** [comment]
Arms now take off proper 15% health. Kill credit of Kologarn is also fine,
