### ISSUE TITLE
Problem with "It`s all fun and games" quest

### ISSUE THREAD

**Issue by OldBastard** [WoWManiaUK/Redemption#2618]
There`s impossible to hit "The Ocular" using "Eyesore Blaster". Animation is just ~ 1s long, and nothing happens. CD on blaster skill works, as intended, but Ocular do not engage in combat.
Did this quest proeviously, few day`s ago, on alliance DK - it took ~ 3x shots to engage Ocular, but now even after 10x shots nothing happens.
Did relog, client restart (proper client and launcher, separate dir), another client restart after clearing the cache, supposed - druid flight form bug, bought regular flying mount - still all the same, short shot animation, and nothing happens.

**Comment by wow-mania** [comment]
Please search before posting. Quest works.

**Comment by OldBastard** [comment]
Today it doeas, but yesetrday we were two there with same prob, and it doesn`t...

**Comment by wow-mania** [comment]
This may be due to some player leaving it halfway through.
When it does happen we just need to open a ticket and ask a GM to kill it and reset.

**Comment by OldBastard** [comment]
GM was involved, and, when I told about both of us, he recommended to report problem there.
So...
