### ISSUE TITLE
[Spell] Aura of Arcane Haste

### ISSUE THREAD

**Issue by TenmanWoW** [WoWManiaUK/Redemption#2619]
Spell ID - 56827

How it should work:

  When stolen via spellstell, the effect becomes the players. If stolen again, it simply refreshes the buff, not to exceed 2 minutes.

How it currently works:

  A mage can steal this spell and each time, it becomes it's own seperate buff. I was instant casting Arcane Blast as a result of my own haste and stealing this buff twice, which I took into the Telestra fight with me.

![wowscrnshot_072418_080117](https://user-images.githubusercontent.com/25806987/43140805-1fc3d3b0-8f1a-11e8-89d1-70717676df2f.jpg)
![wowscrnshot_072418_080116](https://user-images.githubusercontent.com/25806987/43140806-1fd4173e-8f1a-11e8-874a-111e2490d882.jpg)
![wowscrnshot_072418_080113](https://user-images.githubusercontent.com/25806987/43140807-1fe36b9e-8f1a-11e8-8343-3ea0451b35be.jpg)

**Comment by Keader** [comment]
Well, corect system that should handle with it not work in wow mania.
Best that i can do, is make mage "immune" to effect when he already has aura.
It cause: If player already has aura, will not stuck, but will not refresh time too.

**Comment by TenmanWoW** [comment]
Thanks man. I appreciate you looking into this.
