### ISSUE TITLE
[Spell] Rune of Power

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#2621]
http://www.wowhead.com/spell=61973/

This spell should be used by Runemaster Molgeim under one of the 3 bosses randomly in Iron Council encounter.
Problem is, currently he uses it always and only under himself, never under any of the other bosses.
Not a huge issue, but it does make the fight more predictable and less blizzlike.

**Comment by Dranah** [comment]
Works good now, he uses it under random boss.

**Comment by Dranah** [comment]
May be related to this fix, i'm not sure how long this been broken - the Rune of Power despawns when Runemaster Molgeim dies.
This is not intended, the rune should last its full duration (1min) regardless of the caster dying

**Comment by Keader** [comment]
try now @Dranah

**Comment by Dranah** [comment]
No change, rune despawns immediately when Molgeim dies.

**Comment by Dranah** [comment]
Good now, the rune stays, for up to 1minute.

**Comment by Dranah** [comment]
Unexpected side effect no. II:
The raid is now stuck in combat when the encounter is defeated.

**Comment by Keader** [comment]
Hmm
Try now
