### ISSUE TITLE
[Spell] Righteous Defense(Paladin)

### ISSUE THREAD

**Issue by Vastdog** [WoWManiaUK/Redemption#2623]
Hello, I am Vast - I have been tanking with multiple classes on wow-mania for quite a while now and have just come across a significant issue with my paladin. 

**Did I include the steps to reproduce the problem?**
[https://imgur.com/ryRgpf0](url)
[https://imgur.com/5rCSKiC](url)
[https://imgur.com/01q8o1s](url)
[https://imgur.com/eouUsMN](url)
[https://imgur.com/ZCVRl9W](url)
[https://imgur.com/XeRIo0c](url)

I apologize for links, I am not very savy with linking things. Please copy and paste to a new tab to see. Thanks.

**Did I include the description of how it should work?**
40 yard range. Instant Cast ability. 8 second cooldown. Come to the defense of a friendly target, commanding up to 3 enemies attacking the target to attack the Paladin instead.  - taken from http://www.wow-mania.com/armory/?spell=31789

To note, this ability should work while the player targets an enemy(that he does not have agro on) or a friendly player who has agro on one or more enemy minions( if it is over 3, the paladin should gain agro on a maximum of 3 enemys)

**Did I include the description of what is happening?**
Righteous Defense, one of my taunt abilities is not working. The cooldown engages, but the ability seems to just not work.

**Did I include NPC/Item/Spell names (or IDs) from wowhead.com or Armory?**
http://www.wow-mania.com/armory/?spell=31789

**Comment by TenmanWoW** [comment]
Hi Vast! Tenman here! I'll looking into this ticket for you, however, i have some questions. Can you contact me on discord or in-game (Tenman for both).

**Comment by TenmanWoW** [comment]
Spell ID - 31789

Looked into this on both PTR and Red. 

How it is currently working:

3 mobs - the ability is used, it registers in the log, but NPC's do not switch aggro the casting paladin.
2 mobs - same result
1 mob - same result.
 
How it should work: 

40 yard range. Instant Cast ability. 8 second cooldown. Come to the defense of a friendly target, commanding up to 3 enemies attacking the target to attack the Paladin instead.

**Comment by Vastdog** [comment]
Correct

**Comment by squalllh1989** [comment]
Confirmed, it's not working right now, this is a critical bug for prot paladin, we need this to be fixed asap

**Comment by wow-mania** [comment]
Leave this with me. I think I caused it.

**Comment by Keader** [comment]
Fix confirmed :)

**Comment by Vastdog** [comment]
I just did an RHC, and it is still not working in game.

**Comment by wow-mania** [comment]
Read the label.
