### ISSUE TITLE
Spirit is permanently decreased by 3 points. 

### ISSUE THREAD

**Issue by Squidpretty** [WoWManiaUK/Redemption#2627]
It has been a week and my spirit has been permanently decreased by 3. There is no debuff on me and I'm not carrying any items that have a debuff of sorts. I already deleted my cache and wtf folder and it didnt work. What do? 

EDIT: Maybe it could be rez sickness from a week ago?

**Comment by Squidpretty** [comment]
I dont know why this was closed but it was never fixed for me. The issue still remains...

**Comment by wow-mania** [comment]
1. it is not reproducible 
2. You did not give steps (read wiki)
3. It is is a problem with a specific character send an email to support with the name of the character.

I will check it when separately.

**Comment by Squidpretty** [comment]
A gm told me to post it here so i did. Sorry if i offended your huge ego. Go eat some chum you dick sucker. Thank you.

**Comment by wow-mania** [comment]
I love how stupid people are... they do this with the same username in-game. Banned. :)
