### ISSUE TITLE
Spirit (still) permanently decreased by 3. 

### ISSUE THREAD

**Issue by Squidpretty** [WoWManiaUK/Redemption#2628]
It has been a week and my spirit has been permanently decreased by 3. There is no debuff on me and I'm not carrying any items that have a debuff of sorts. I already deleted my cache and wtf folder and it didnt work. What do?

EDIT: Maybe it could be rez sickness from a week ago?

**Comment by shitfarts** [comment]
I have this EXACT same issue. Cannot get an answer, tickets just get closed with no explanation... my guess is its some sort of bug they are unable to figure out how to correct. Hopefully I get proven wrong! fingers crossed!

**Comment by wow-mania** [comment]
Do not reopen closed issues.
