### ISSUE TITLE
WOW

### ISSUE THREAD

**Issue by Squidpretty** [WoWManiaUK/Redemption#2629]
I'm disappointed. I kissed gms' asses the whole time I played on this server. When they said don't make any jokes, I didn't, When they said that they don't condone cussing (cause apparently they're children) I said fine. But for real this is why there's no population. You guys have no personality (especially janitor who is probably living in his mother's basement) and I'm so bored of this. I spent so much time on here and it all feels wasted. I'm going to go on multiple sites and try to tell people about how horrible my experience was. For a lowpop, buggy, and shit server you guys should be more humble. If someone wants to report a bug, dont treat them like it's middle school. This is the number one reason why you dont a population or get DONATIONS. 
Janitor seems to close a lot of issues but doesnt solve them. Other gms, you guys rock. You helped me with my problems and didn't try to molest my 11 year old brother(no joke im serious what a creep). 
See y'all. There are so many better servers to go to that don't treat their guests like trash ( like a sunday school).

**Comment by wow-mania** [comment]
That is the lovely tone of the lady that had her 11 year-old molested... 
One can only imagine the kind of education the poor bastard is having. :)

![image](https://user-images.githubusercontent.com/12248683/43312452-3a087e34-9185-11e8-8e0e-5c23b4cd9ccd.png)
