### ISSUE TITLE
[Quest] The Last Line Of Defense

### ISSUE THREAD

**Issue by Calebrimbor** [WoWManiaUK/Redemption#263]
http://www.wow-mania.com/armory/?quest=13086

For this quest you'll need to man a Argent Cannon(http://www.wow-mania.com/armory/?npc=30236) and kill 100 Scourge Attackers and 3 Frostbrood Destroyers(http://www.wow-mania.com/armory/?npc=30575)

I couldn't enter a cannon since it was not visible.
![wowscrnshot_082216_143352](https://cloud.githubusercontent.com/assets/20358867/17854839/93134c7e-6875-11e6-96cd-8736fc4537e9.jpg)

Then I toggled GM mode, the cannon is visible, but not on the pillar. In this way you'll hit the wooden bar.
![wowscrnshot_082216_143412](https://cloud.githubusercontent.com/assets/20358867/17854853/9f666470-6875-11e6-9fcc-c3bd094e4518.jpg)

When I toggled GM mode again, the pillar is shown, without cannons again.
![wowscrnshot_082216_143419](https://cloud.githubusercontent.com/assets/20358867/17854863/a9cdf324-6875-11e6-9a30-67204bf03f32.jpg)

Also, no mobs spawned, so you can't get the quest objective.

**Comment by Thrashattack** [comment]
During the phase stage of this quest there are cannons positioned at the towers on the argent hold. 

One of the cannons is positioned under the another terrain that was suppose to be "holding" the cannon. 
As you can see in the screenshot there is no LOS for this cannon. 

Position : 85.8, 78.1 - Icecrow , Northrend.

**Comment by Thrashattack** [comment]
![cannon](https://user-images.githubusercontent.com/23486776/48296871-16d57b80-e47b-11e8-9cda-f0b9ea042601.jpg)

**Comment by wow-mania** [comment]
This will go back to normal after restart. Players somehow move it sometimes. I will keep checking.
