### ISSUE TITLE
[Quest] Battle for the Undercity

### ISSUE THREAD

**Issue by RealDerlan** [WoWManiaUK/Redemption#2630]
The quest "battle for the undercity" isn't working properly. I got send here by one of the devs when i made a ticket.
Every npc is located before the entrance of the undercity. Basically what happens is when i accept the quest 13267 from vol jin (31649) i can immediately complete it with thrall (31650) without having to do a thing.
The normal procedure i think would be a battle to retake the undercity and kill varimathras i presume. I have never done this quest before

Is this enough information for you guys?

**Comment by squalllh1989** [comment]
Confirm, the quest [The Battle For The Undercity](http://www.wow-mania.com/armory/?quest=13267) currently complete the moment you get throught the portal and get to front of undercity, none of the event of the battle happen.
Here is some video for what should happen before the quest completed:
Alliance side: [The Battle for the Undercity - Alliance](https://www.youtube.com/watch?v=PxvQKCJagoI)
Horde side: [The Battle for the Undercity - Horde](https://www.youtube.com/watch?v=thvM9fd-pJA)

**Comment by wow-mania** [comment]
This is an extremely long event and the chances we will get the proper sniffs at this point are very slim. 
It should be doable though. If not I will add to the .bq command.

**Comment by squalllh1989** [comment]
yeah right now the quest completed right away, so the problem is not that we can't have the quest completed, but we are not having the event in there.

**Comment by squalllh1989** [comment]
and yes, that's a long event and only given more fun to player, not a critical thing, so i put on tweaking for this.

**Comment by wow-mania** [comment]
Unfortunately, there is too much work to be done here and a lot is unknown. Since the quest is completable I will leave it as it is for now. If things change in the future and we have more manpower we will re-open it.

**Comment by Rushor** [comment]
will work on this now

**Comment by Rushor** [comment]
first progress https://i.imgur.com/DpyP3cl.jpg

**Comment by Rushor** [comment]
all added. will show some screens later. will do some last questchainfixes today and tomorrow.

**Comment by Rushor** [comment]
showcase horde:
![I](https://i.imgur.com/hnxACr1.jpg)
![I](https://i.imgur.com/qAgERBA.jpg)
![I](https://i.imgur.com/hnxACr1.jpg)
![I](https://i.imgur.com/gFGfRXG.jpg)
![I](https://i.imgur.com/D62THne.jpg)
![I](https://i.imgur.com/ymGz1jS.jpg)
![I](https://i.imgur.com/1U25ZPk.jpg)
![I](https://i.imgur.com/TnpfJKZ.jpg)
![I](https://i.imgur.com/8HqvZQf.jpg)
![I](https://i.imgur.com/a19wbca.jpg)
![I](https://i.imgur.com/eGCRTpe.jpg)
![I](https://i.imgur.com/7Pa0LOt.jpg)
![I](https://i.imgur.com/DZcTzJx.jpg)
![I](https://i.imgur.com/e31n3HI.jpg)
![I](https://i.imgur.com/9xkXPnp.jpg)
![I](https://i.imgur.com/p9v0R2k.png)
![I](https://i.imgur.com/6cuDnS9.jpg)
![I](https://i.imgur.com/ygM99fA.jpg)
![I](https://i.imgur.com/7BHQB2H.jpg)
![I](https://i.imgur.com/j6NzIAV.jpg)
![I](https://i.imgur.com/PtJIKyX.jpg)
![I](https://i.imgur.com/yx8xtUm.jpg)
![I](https://i.imgur.com/wi9JYIx.jpg)
![I](https://i.imgur.com/kAHrjNE.jpg)
![I](https://i.imgur.com/b5EdlJ7.jpg)
![I](https://i.imgur.com/42m4AUM.jpg)
![I](https://i.imgur.com/jVCZ61T.jpg)
![I](https://i.imgur.com/86HHGBy.jpg)
![I](https://i.imgur.com/4ajUIrT.jpg)
![I](https://i.imgur.com/oB5oROv.jpg)
![I](https://i.imgur.com/NJKtniF.jpg)
![I](https://i.imgur.com/qKKLhU5.jpg)
![I](https://i.imgur.com/t9GYBBH.jpg)
![I](https://i.imgur.com/Sct3Fl1.jpg)
![I](https://i.imgur.com/ywBJYBb.jpg)
![I](https://i.imgur.com/c1t88KS.jpg)
![I](https://i.imgur.com/3mTMaCu.jpg)
![I](https://i.imgur.com/rAeaigy.jpg)
![I](https://i.imgur.com/AAekPwH.png)
![I](https://i.imgur.com/ErbnYag.jpg)

**Comment by Rushor** [comment]
alliance also done now

![I](https://i.imgur.com/BvEBAXW.jpg)
![I](https://i.imgur.com/gDewqFV.jpg)
![I](https://i.imgur.com/yI9W9xh.jpg)
![I](https://i.imgur.com/0EyN4oL.jpg)
![I](https://i.imgur.com/3wRfSEK.jpg)
![I](https://i.imgur.com/g1uD10V.jpg)
![I](https://i.imgur.com/YHi156R.jpg)
![I](https://i.imgur.com/k2ScUyJ.jpg)
![I](https://i.imgur.com/8bQEpE4.jpg)
![I](https://i.imgur.com/ZvT2cRf.jpg)
![I](https://i.imgur.com/9VWZUGn.jpg)
![I](https://i.imgur.com/QlSKSQk.jpg)

(ignore the dumb mount issue on last SS, fixed that aswwll now. autocomplete also removed now.)

**Comment by RealDerlan** [comment]
thank you for doing this! i was looking forward to this quest the moment i
began lvling on wow mania.
Now i have a reason to come back haha

Op vr 22 nov. 2019 om 10:50 schreef Janitor <notifications@github.com>:
