### ISSUE TITLE
[Core] Dungeon Finder

### ISSUE THREAD

**Issue by TheManiax** [WoWManiaUK/Redemption#2632]
- [ ]  **How it works:** When a replacement is found, the new member will be teleported to the starting location of the dungeon.
**How it should work:** When a replacement is found, the new member will be teleported to the party leader's current location.

- [ ]  **How it works:** You can not provide any reason when using the vote kick option.
**How it should work:** Players who use the Vote Kick option will now be prompted to provide a reason for kicking a party member. This reason will be presented to everyone in the party except for the person voted to be kicked.

- [ ]  **How it works:** Using Vote kick option has no cooldown.
**How it should work:** The functionality of the Vote Kick feature in the Dungeon Finder will now behave differently according to a player's history with the system. Players using the Dungeon Finder who rarely vote to kick players from a group, or rarely abandon groups before a dungeon is complete, will find that the Vote Kick option will have no cooldown. For players who frequently abandon groups or vote to kick other players, the Vote Kick option will be kept on a cooldown. This functionality will adjust itself as a player's behavior while using the Dungeon Finder changes.

- [ ]  **How it works:** If a player gets Disconnected or logs out(relog) on purpose, he will leave the group without any consequences.
**How it should work:** If a player DC's, they cannot be kicked for a full minute to give the player a fair chance to reconnect.

- [ ]  **How it works:** Players can initiate a vote kick at the start of the dungeon, this leads to abusing the system to refrain from doing specific dungeons.
**How it should work:** A vote to kick a member may not be initiated in the first 15 minutes of a group.

- [ ]  **How it works:** when a player joins a group via dungeon finder or gets kicked via vote or leaves the group by disconnection/relog, he can que again instantly.
**How it should work:** When you join a group you got via the Dungeon Finder you will be on Dungeon Finder cooldown, preventing you from joining another random group for the next 30 minutes (from the time you were matched with a dungeon). There are the following exceptions:

- You got kicked from the group
- The end boss (or whoever gives the reward for joining a LFD group) of the instance has been killed
Additionally, if you leave or are kicked from a group before one of the bosses is killed, you will receive the Dungeon Deserter debuff, which will prevent you from using the Dungeon or Raid Finder for 30 minutes.

**Comment by Dranah** [comment]
id suggest that issue 5) "a vote kick may not be initiated in the first 15 minutes of group" in case it gets implemented it should be reduced to 3 or 5 minutes, because as a private server, it tends to happen that dungeons break (like oculus many times) and become difficult or impossible to complete. So players need to have an option to skip buggy dungeons. A 3-5min delay for kicks is enough to demotivate players from kicking each other just for the sake of getting a dungeon they like more.

**Comment by wow-mania** [comment]
1. As is. (feature request not issue)
2. As is. (feature request not issue)
3. As is. (feature request not issue)
4. As is ( you just said on purpose.)
5. As is (feature request not issue)
6. 5. As is (feature request not issue)

Not changing any of these.
