### ISSUE TITLE
[Dungeon] Reputation Gain

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#2635]
Mobs and bosses in level 80 dungeons should all award reputation, if you dont wear a tabard then to Horde Expedition/Alliance Vanguard for horde/ally respectively, if you wear a tabard, then to that tabards chosen faction.
This includes ALL heroic dungeons and dungeons that are lvl 77-80 on normal mode too:
Utgarde Pinnacle
The Culling of Stratholme
The Oculus
Halls of Lightning
Also TOC/FOS/POS/HOR on normal too.

Problem: currently there are 2 dungeons that should award rep but do not (the rest works fine)
1) Violet Hold heroic - http://www.wowhead.com/the-violet-hold
2) The Oculus normal - http://www.wowhead.com/the-oculus
None of the mobs or bosses inside award any rep when being killed, with or without a tabard.

EDIT: Possibly same issue with TOC 5 normal

**Comment by squalllh1989** [comment]
The occulus normal is 77-80, so it's should not give rep. Gonna try toc5 normal and violet hold then.

**Comment by Keader** [comment]
1.The Violet Hold (H) does not give rep
2. The Oculus normal does not give rep
3. Trial of the Champion does not give rep on both normal and heroic.

^ what reputation each instance should give (without tabard)?

**Comment by Dranah** [comment]
Without tabard:
Horde Expedition http://www.wowhead.com/faction=1052/horde-expedition for Horde
Alliance Vanguard http://www.wowhead.com/faction=1037/alliance-vanguard for Alliance

How much:
Non elites (like whelps in oculus, or small mobs spawned by portal keepers) 5 rep per mob
Elites: 15 rep per mob
Bosses: 250 Rep

**Comment by Keader** [comment]
in all 3 instances?
