### ISSUE TITLE
[Spirit Healer] - Coldarra

### ISSUE THREAD

**Issue by Bartok14** [WoWManiaUK/Redemption#2636]
If  you die on Malygos 10 man fight you end up spawning at the spirit healer in Borean Tundra but you get stuck in place. Only way to fix this is to log out and then log back in.

**Comment by wow-mania** [comment]
I cannot reproduce this. I will wait for someone else to try it.

**Comment by Dranah** [comment]
I can confirm this happening, though its not 100% chance. It has nothing to do with malygos though, it s simply that spirit healer spot in Coldarra.

**Comment by wow-mania** [comment]
I guessed that. But it if it's not 100% reproducible we need to have a clue of when it happens. Maybe position or faction related.

**Comment by squalllh1989** [comment]
i have no clue what actually caused it too, but yeah, it really does happen randomly, but a lot, about 5 time that i died in Malygos encounter, 10 or 25,, there will be 1-2 time that i stuck in 1 place and can't move, have to relog to be able to move again.

**Comment by Keader** [comment]
Please reopen it when we have a way to reproduce it.
I kill myself 10 times inside of Malygos instance, and always i go to Coldarra.
