### ISSUE TITLE
[Boss] Grand Champions

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#2639]
http://www.wowhead.com/trial-of-the-champion
http://www.wowhead.com/npc=34702/ambrose-boltspark
http://www.wowhead.com/npc=34701/colosos
http://www.wowhead.com/npc=34657/jaelyne-evensong
http://www.wowhead.com/npc=34703/lana-stouthammer
http://www.wowhead.com/npc=34705/marshal-jacob-alerius
http://www.wowhead.com/npc=35617/deathstalker-visceri
http://www.wowhead.com/npc=35572/mokra-the-skullcrusher
http://www.wowhead.com/npc=35571/runok-wildmane
http://www.wowhead.com/npc=35570/zultore

This is the first encounter in Trial of the Champions. There are multiple issues:

1) The mounted champions are idle. 
You can fight their mounted servants more or less properly, but when the last wave comes, the 3 champions on their mounts themselves, they simply don't fight. 
Sometimes they refresh their defend stacks, but if you stop attacking them for 2-3 seconds, they even lose their buffs and reset to full health, completely evading.

How it should work: the champions should attack you just like their servants, just for a little more dmg (Thrust when in melee range, charge and remove your shield if out of melee range). They should never reset to full health and lose their buffs randomly or reset in any other way unless you wipe.

2) Kill credit for champions.
Every time you do the dungeon, you fight a set of three enemies in this encounter. (there are a total of five champions for each faction to pool from). 
Right now, upon defeating them, only one awards credit, the last one that you kill, which counts for the Trial of the Champion achievement (and its heroic version).

How it should work: all 3 champions that you face should award credit for defeating them.

3) The warrior
Now, this is slightly related to the previous, as you'd expect to overcome the kill credit issue by always choosing a different target to kill as last.
However, when attempting to leave the warrior last, so far i encountered 2 outcomes:
- The warrior dies last but does not register credit. It counts the 2nd boss you killed for credit, as if the warrior didnt exist.
- The fight simply ends after 2nd boss when the warrior is last to be left alive. The other bosses run out, loot spawns, the warrior just despawns. (ive yet to figure what triggers this, but the result is same - you dont get credit for the warrior)

I dont know if this is related to the warriors constant aggro-dropping. which is another issue i hereby report, because i found no evidence of this happening on retail. What happens atm, is that he randomly switches target every 4-5 seconds, charges on that target, starts spinning, and repeats it over and over after being taunted. He is pretty much untankable here.

How it should work: He's supposed to have a regular threat table and only start charging clothies when someone overaggroes.

**Comment by Keader** [comment]
Finally, fixed xD

```
Some charges will charge at the target but deal no damage
```
It can miss '-'

```
charges are scaling with %DMG modifiers.
```
Dont have any attr that dont allow it, so looks correct.

**Comment by Ashamedlol** [comment]
I don't think it's about missing Keader, if you decide to wait 5-7 seconds between each charge, every one of them will hit.

**Comment by Dranah** [comment]
UPDATE:
- Champions now fight as intended
- Warrior no longer acts stupid
- Kill credit is properly awarded for all three
I can confirm the issue with charges failing, it happens way more often than any spell should reasonably miss. It is mostly as Ashamed says, if you wait more time between charges they dont fail, but if you spam it and try to use it asap when its off cooldown, it will have no effect. It also seems to fail more when the server lags. Sometimes 3-4 times in a row, which is just insane.

**Comment by Keader** [comment]
It was 12.5% chance of miss.
I removed that.
Testing in dummy, always work for me.
