### ISSUE TITLE
Crocolisk Mastery; The Ambush

### ISSUE THREAD

**Issue by ggosse52** [WoWManiaUK/Redemption#2640]
I've tried this quest over and over. Accepted and abandoned it many times.
I always get the message "Requires fallen Log"
I've tried activating it all around the log, on top of it - nothing works. I have done this quest many times on the original game so I do know how it is supposed to work
I think the target zone must be way too small.
Please increase the area in which it will work to make it viable. Thanks

**Comment by Dranah** [comment]
http://www.wowhead.com/quest=12569
