### ISSUE TITLE
[Instance] Oculus not giving reputation in normal mode

### ISSUE THREAD

**Issue by Keader** [WoWManiaUK/Redemption#2643]
Missing reputation data (#2635)

**Comment by Dranah** [comment]
only broken on normal. corrected title

**Comment by Dranah** [comment]
Most of it gives rep properly now.
Missing rep on Urom and his adds:

Mage-Lord Urom https://www.wowhead.com/npc=27655 = should give 250
Phantasmal Cloudscraper https://www.wowhead.com/npc=27645 = should give 15
Phantasmal Ogre https://www.wowhead.com/npc=27647 = should give 15
Phantasmal Air https://www.wowhead.com/npc=27650 = should give 15
Phantasmal Murloc https://www.wowhead.com/npc=27649 = should give 15
Phantasmal Wolf https://www.wowhead.com/npc=27644/ = should give 15
Phantasmal Fire https://www.wowhead.com/npc=27651 = should give 15
Phantasmal Water https://www.wowhead.com/npc=27653 = should give 15
Phantasmal Mammoth https://www.wowhead.com/npc=27642 = should give 15
Phantasmal Naga https://www.wowhead.com/npc=27648 = should give 15

**Comment by Keader** [comment]
Ok Darling.

**Comment by Dranah** [comment]
All works good now.
