### ISSUE TITLE
[Transmog] Hood of Hungering Darkness

### ISSUE THREAD

**Issue by Anthonhed** [WoWManiaUK/Redemption#2645]
So I went to transmog my [Hood of Hungering Darkness](http://wow-mania.com/armory/?item=97213) when I realized that for some reason the hood does not show up in the selection menu for transmoging the head even though I do have the item in my bags.
![transmog](https://user-images.githubusercontent.com/26274880/43680377-a437ca3e-9839-11e8-84ed-994073b1170b.PNG)
![hood](https://user-images.githubusercontent.com/26274880/43680380-a6e838fe-9839-11e8-9810-6ea45214bee7.PNG)

I do use WoW-Mania's custom launcher and before I made this issue on GitHub I did Delete cache and updated the launcher to try again.

**Comment by wow-mania** [comment]
Fixed in dev. It will be deployed tomorrow.
