### ISSUE TITLE
[Pet] Voidwalker not attacking mobs

### ISSUE THREAD

**Issue by drat311** [WoWManiaUK/Redemption#2646]
How it should work:

 Warlock pets should engage and cast abilities as defined by the current settings and player commands.

How it is currently working:

The warlock voidwalker pet will sometimes stand behind mobs but not attack them.  One specific mob the VW seems to never attack is Fozruk in Arathi Highlands.  If you set the voidewalker to follow+defensive and order him to attack, he'll path up to Fozruk but just stand there.   

A more common variant of the problem can be duplicated on mobs throughout the game, but especially in Ungoro Crater.  There, if you have the voidwalker set to follow+defensive and you pull a Diemetradon (It works on multiple, but Diemetradon for sure) by casting a spell on it, the VW will path to where the mob was at the time of the pull and then path to the rear of the mob but never attack it.  It's very rare that the VW fails to attack if I let him pull but I have seen it happen. And it happens on Fozruk regardless of who pulls. 

Fozruk - 2611
Diametredon - 9163
Summon Voidwalker - 697

When this happens I am also unable to manually cast torment from the pet bar.

**Comment by TenmanWoW** [comment]
Pending spell ID's and NPC ID's. Will update tonight.

**Comment by Keader** [comment]
Can you check if is fixed please?

**Comment by Dranah** [comment]
Can no longer reproduce problem on the mammoths that usually did this, neither on Fozruk, so i suppose other npcs should be fine too.
