### ISSUE TITLE
[Quest] Collection of Goods

### ISSUE THREAD

**Issue by GM-Gathios** [WoWManiaUK/Redemption#2647]
http://www.wowhead.com/quest=7642/collection-of-goods

For this quest one of the requirements are you'll need 5x Stratholme Holy Water (http://www.wowhead.com/item=13180/stratholme-holy-water) wich can be looted from Stratholme Supply Crates  (http://www.wowhead.com/object=181085/stratholme-supply-crate) in Stratholme.

Issue:
All of the found crates can't be looted. Nothing happens when you click on it.

**Comment by WhitephoenixTheBunny** [comment]
Wrong crates, not sparking ones...
check this post: https://github.com/WoWManiaUK/Redemption/issues/2307

**Comment by Dranah** [comment]
The quest works as intended, all subject crates are in the last room with abominations:
https://imgur.com/Yh9Tcg1
https://imgur.com/ubEXvnT
