### ISSUE TITLE
[Boss] The Black Knight Loot table

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#2648]
http://www.wowhead.com/item=47560
http://www.wowhead.com/npc=35451/the-black-knight
Boots of Crackling Flame is a lvl 219 item which is supposed to drop only on heroic mode from Black Knight in TOC5.
Right now, he drops it on normal mode, which is not intended.
How it should work: This item should only drop on heroic mode.

**Comment by Dranah** [comment]
Ive been farming TOC normal for the past few days and i get these damn shoes literally every 2nd run, so yeah, quite sure.

**Comment by Keader** [comment]
I need wait janitor send me files, to check if someone added it directly in script.
Because based in PTR DB, it's correct.
Are you sure that you tested in PTR?

**Comment by Dranah** [comment]
Absolutely did not , i am running it on Redemption.
Could the two be different?

**Comment by Keader** [comment]
Maybe, i dont have access to check in redemption.
Teu in PTR please

**Comment by Dranah** [comment]
then I need a command to spawn a black knight that is actually dropping loot, because spawning the IDs i found for him, do not drop any

**Comment by Keader** [comment]
will be ready to test after any server reset

**Comment by Dranah** [comment]
I've no means of making a thoroughful test for this as i cant respawn the NPC. Killed him 3 times and didnt get the shoes anymore, for me it's good enough.
