### ISSUE TITLE
Heroic Training Dummy

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#2649]
How it works atm:

Attacking the dummy with ranged  weapon (gun, bow, crossbow,thrown) properly adds weapon skill ups.
Attacking with a melee weapon does not add weapon skill ups.
This does not depend on the character, you can test both weapon types as a hunter and youll find that only the ranged is skilling up properly.

How it  should work:
Dummy should add weapon skillups when being attacked by any type of weapon.

**Comment by squalllh1989** [comment]
Dummy should not give any weapon skill up at all.

**Comment by Keader** [comment]
Yeah, dummy should not give any skill up.
Fixed.
