### ISSUE TITLE
A Sister's bond Transmog

### ISSUE THREAD

**Issue by EmileMidna** [WoWManiaUK/Redemption#2652]
So I have bought the bow from the artifact vendor in the mall named A sister's Bond and I transmoged it but when I am shooting arrows from the bow it's not giving me the normal shooting animation, instead it's giving me an animation like i'm casting an instant fire spell even though I am still shooting arrows like normally its just the visual that's messed up

**Comment by wow-mania** [comment]
I will check that and let you know.
Please send me the link to our armory of the item you are trying to transmog and the source item also.

**Comment by EmileMidna** [comment]
the item i am trying to transmog http://www.wow-mania.com/armory/?item=42946
the item i am trying to transmog to http://www.wow-mania.com/armory/?item=150208

**Comment by wow-mania** [comment]
As-is. Imported items from later versions do not always render as you would expect in wotlk.
If you wish you can send me a message on email or skype and I will refund the token.
