### ISSUE TITLE
[Raid] Ooze at Professor Putricide (Heroic)

### ISSUE THREAD

**Issue by squalllh1989** [WoWManiaUK/Redemption#2654]
The too ooze at Professor Putricide in heroic mode should not target the same person, but what i see in the raid just now is: the [Gas Cloud](http://www.wow-mania.com/armory/?npc=37562) (orange ooze), and the [Volatile Ooze](http://www.wow-mania.com/armory/?npc=37697) (green ooze) target the same person, and this happen 3 times in the raid. It should not ever happen like this, at no chance should both Gas Cloud and Volatile Ooze target the same person at all as it's a wipe if that happen.

**Comment by Dranah** [comment]
Ooze targets received a 15second protection from being targeted by another ooze.
Red and Green ooze can no longer pick the same target.
