### ISSUE TITLE
[Quest] Bloody Breakout

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#2657]
http://www.wowhead.com/quest=12727

This is the escort quest you can pick up from http://www.wowhead.com/npc=28912/koltira-deathweaver after handing in the previous quest http://www.wowhead.com/quest=12725/brothers-in-death.
It is a mandatory part of the DK starter chain.

While the quest itself is doable, it can be an insane waste of your time due to its bugs. I know that his 10min respawn timer is blizzlike, but you aren't supposed to have to do it one by one when questing in a party. 
Anyway, in order:

1) Koltira's Anti-Magic Zone is only present for the first wave of mobs.
He kneels down and pops it as intended when the event starts, but he starts running to the mobs that spawn to fight, and after the first wave is defeated, he resets and runs back to his original spot, the zone disappears and he never casts it again. This means players have to face the High Inquisitor without the protection of the shield.

How it should work: Koltira should not aggro to the mob waves in the first place. He kneels and upholds the magic zone, while you fight for him. He must maintain the magic zone until the High Inquisitor is defeated and the event progresses on. The High Inquisitor's smite damage is greatly mitigated by the shield, making it easy for soloing as well.

2) No means to do this quest in party.
Right now, if you are leveling together with others, or simply multiple people happen to be on the quest simultanously, you will have to do it 1 by 1, each time waiting out the 10minute respawn for the NPC. It is not intended.
This is because once someone picks up the quest and the event starts, Koltira becomes impossible to interact with. Even if you are all in party, even if you all managed to hand in the previous quest (so everyone is on same stage), when one person picks it up, the game does not offer to share it to his party members like for other escorts, and the quest itself is not sharable. 

How it should work:
Koltira should remain possible to interact with, even after someone started the event. Players should be able to hand in the previous quest and pick up the new one , without it having any effect on the ongoing event. (basically, people who "arrive" halfway can also join in)
All players that have accepted the quest (regardless of being in party or not) must be able to loot the Inquisitor's head in the end. 
Note: the Inquisitors remains is an object that is lootable, not a regular corpse. Therefore it does not require "tag" to loot, just the player to have the quest. It is very important that the remains dont disappear after one person looted, everyone on the quest must be able to loot it.

**Comment by wow-mania** [comment]
Minor improvements. I was about to set it to "Won't fix" as this is doable at the moment but decided to try a few things.
If there this is better great otherwise we revert to the previous code.

**Comment by Dranah** [comment]
For an optional random world quest, "doable" is good enough for status, however this is a MANDATORY quest that every single DK must complete to exist at all.
Leaving it bugged in a state where it's doable but takes potentially 2hours of a newbie players life is not going to win new players to the server, I hope you agree.

PS:
The only thing that changed after your fix is that Koltira no longer attacks the mobs. However he still loses the anti magic shield after the first wave so this is not any improvement, players don't receive help with defeating the High Inquisitor and they still have no option to do this quest in party, as only one person can hand in q and take the escort, and only one person can loot in the end.

**Comment by wow-mania** [comment]
We cannot do escorts as a party in the core so this probably remains as is.

**Comment by Dranah** [comment]
But is it possible to allow players to interact with koltira after the event started? (without it having any effect on the event)
As i said, this quest does not need a "tag" to complete, nor credit really, the problem is you can't pick up the quest once the event started and the object in end can only be looted by one person.

**Comment by Dranah** [comment]
Anti magic zone is now good.
Need to fix problem with the quest share checking for wrong conditions.

**Comment by Dranah** [comment]
Quest share now checks for conditions properly.
However the previous fix on Anti magic zone is gone. It behaves now as before, disappears after first wave . Something was reverted by accident i suppose.

**Comment by wow-mania** [comment]
All restored. Should work fine. If not re-open.
