### ISSUE TITLE
Umberwing  MOG

### ISSUE THREAD

**Issue by DeathBezar** [WoWManiaUK/Redemption#2658]
the  Unberwing mog war-blade if i you  Sheath it Under the tons arm sticking out the head ... it looks like a Man bag or sumthing  can you fix it please
![unknown](https://user-images.githubusercontent.com/34142628/43992000-c426e49a-9d77-11e8-875e-d1d1f0dee199.png)
 
Thanks.

**Comment by wow-mania** [comment]
As-is. Imported items from other versions do not always render as you expect on wotlk.
