### ISSUE TITLE
Gobo female voice

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Redemption#2659]
Hey guys sorry to bother you, there is already a forum for this but it was in April 2017, a guild member is enquiring about the female gobo voice, she says that when it is struck it is giving the sound effect of a male gnome, is there anyway of fixing this?

**Comment by wow-mania** [comment]
Unless you give me steps to reproduce this will be very difficult to reproduce. 
Is it just when stuck?

**Comment by sarahkay88** [comment]
Hi its not when it stuck, but when its struck so during combat. everything else like the laugh, flirt ect sound like a gobo female but during combat whilst fighting it makes the sound of a male gnome. I tried this myself just to check if it was an issue on the guild members side n it was the same for my low level gobo.  ty for your help.

**Comment by TheManiax** [comment]
Just make a goblin male and female, Go and attack a mob and listen to the voices.
To me, it sounds like the female voice is male, and male voice is female. Probably you need to swap the combat sound file for male and female.

**Comment by wow-mania** [comment]
Will need client update next week.

**Comment by Talarok** [comment]
This problem is back. I have male voices in combat.

**Comment by wow-mania** [comment]
I will check it but in any case it will be on next client update only. 2.5.3

**Comment by TheManiax** [comment]
Goblin and Worgen are missing a lot of sounds
The sound files are not missing in the MPQ, but apparently they are not being loaded properly
I will send you a list of those we could find in test team

**Comment by wow-mania** [comment]
Will be in 2.5.3
