### ISSUE TITLE
[Boss] Ouro

### ISSUE THREAD

**Issue by NightSeekerr** [WoWManiaUK/Redemption#2660]
So the boss Ouro (http://wow-mania.com/armory/?npc=15517) in Temple of Ahn Qiraj is not spawning. Usually he's supposed to spawn once you go near his spot. Per admin Aymelek the boss "is not working atm". Here's exactly what he said: https://i.imgur.com/8hqKDmp.jpg

I need the boss for Ouro's Intact Hide (http://wow-mania.com/armory/?item=20927), which I need for the quest "Conqueror's Legguards" (http://wow-mania.com/armory/?quest=8560).

**Comment by TenmanWoW** [comment]
NPC ID - 15517

How it should work: 

   Boss approaches from underground upon players nearing. Fight ensues.


How it currently working-

   I approach and about 35 yds out, the Ouro Spawner appears. It is a level 69 mob with 3k hp. It stays underground and hits for 200 hp, following me around. Boss never appears.


![wowscrnshot_081218_115145](https://user-images.githubusercontent.com/25806987/44004320-7188d3ba-9e26-11e8-8896-e64b1ec71a0d.jpg)

**Comment by TenmanWoW** [comment]
Also tried to spawn boss using ID, no effect aside from respawning the above mob.

**Comment by Keader** [comment]
I cant fix it properly, because i dont have any sniff about that.
But i'm putting Ouro as permanent spawn inside of instance.
