### ISSUE TITLE
[Quest] Empty Stables

### ISSUE THREAD

**Issue by NightSeekerr** [WoWManiaUK/Redemption#2661]
So the quest "Empty Stables" (http://wow-mania.com/armory/?quest=7027) seems bugged. You're supposed to tame an Alterac Ram using a Stormpike Training Collar (http://wow-mania.com/armory/?item=17689), but when you use the collar on a ram the ram attacks you. Happens everytime, tried it probably 10 times.

**Comment by TheManiax** [comment]
According to wowhead:
![image](https://user-images.githubusercontent.com/14857593/44016265-9c9f1640-9ee9-11e8-96b7-9f7925316b43.png)

I tried as stated and couldn't manage to tame any ram.
BTW the channel bar is visible in mania. the wowhead comments says it is not.
