### ISSUE TITLE
Patience and Understanding

### ISSUE THREAD

**Issue by Greywolf59** [WoWManiaUK/Redemption#2663]
Hello dear Dev team!
Issue arised concerning quest http://www.wow-mania.com/armory/?quest=10004 (Patience and Understanding). Since I took this quest the NPC I should talk to, beat, and which ends the quest: Sal'salabim http://www.wow-mania.com/armory/?npc=18584 is either not visible or somebody managed to overkill him and it did not respawn. This NPC shouldn't not be killed and should switch to friendly after bringing its HP low enough. I was at its place for three times and I have always waited for a fairly long time to be sure it wasn't killed only a few minutes ago but it never respawned.
I also tried to delete cache.
Best regards!
GreyWolf

**Comment by TheManiax** [comment]
![image](https://user-images.githubusercontent.com/14857593/44015356-d85fd146-9ee5-11e8-8e03-cf63cd3f8c9e.png)

![image](https://user-images.githubusercontent.com/14857593/44015375-e34e514a-9ee5-11e8-9ea6-4f2c7ee2329c.png)

Tried 2 times, at around 6~7k HP he turned to friendly and the quest completed.

**Comment by Greywolf59** [comment]
Ok, thank you very much, it seems more and more like it's a problem with my char actually. I still don't see this NPC and I had problem wit phasic when I couldn't attack The Oculus at Shadow Hold and with seeing this NPC http://www.wow-mania.com/armory/?npc=30708 after completion of certain quests. I have seen Sal'salabim normally before taking the quest regarding him. Should I ask for help ingame or what am I supposed to do?
Greywolf (char Geshoia)

**Comment by TheManiax** [comment]
Ask a Game Master to check if it's a phase issue or the NPC is just dead.
In either case, I see no bug to fix.
But thanks for the report anyway :slightly_smiling_face:
