### ISSUE TITLE
[Mount] Arcadian war turtle

### ISSUE THREAD

**Issue by Ezzraeil** [WoWManiaUK/Redemption#2665]
Hello
The mount "Arcadian war turtle" seems to be smaller in this server. Here is a pic from wow mania and a random pic of this mount.

WoW-Mania:
![123123232](https://user-images.githubusercontent.com/32011503/44078867-d8197958-9fbc-11e8-936f-d3b080eb7b00.jpg)

Normal size:
![643050](https://user-images.githubusercontent.com/32011503/44078883-e13e8b90-9fbc-11e8-8a2b-e327bd005d4e.jpg)

**Comment by WhitephoenixTheBunny** [comment]
http://www.wow-mania.com/armory/?item=141713

**Comment by wow-mania** [comment]
I will check it.
