### ISSUE TITLE
[Object] Empowering Blood Orb

### ISSUE THREAD

**Issue by TheManiax** [WoWManiaUK/Redemption#2666]
[[Empowering Blood Orb]](https://www.wowhead.com/object=201741/empowering-blood-orb)
**How it works:**
The Object is not working at all.
**How it should work:**
It casts the spell [[Empowered Blood]](http://www.wow-mania.com/armory/?spell=70227) on the first player who clicks on it, the buff will drop off by [[Remove Empowered Blood]](http://www.wow-mania.com/armory/?spell=72131) when the buffed player gets away from the object or gets close to the boss.
@Keader  If you have scripted this one before, would you please implement on PTR so we can check it?

**Comment by Keader** [comment]
I can improve it

**Comment by Keader** [comment]
It has chance to fail if i remember right.
Anyway, not fully scripted but is working now.
I should improve it in future, when i got sniffs to script trash mobs close of it.
