### ISSUE TITLE
Penance

### ISSUE THREAD

**Issue by Tamagucci** [WoWManiaUK/Redemption#2667]
Hey there. I was wondering if you guys could look into penance when you get the time to. I've noticed for a while now that about 25% of the time penance will only show 2 out of 3 bolts in the animation of the spell (the yellow stars) and will consequently only give 2 out of 3 the buff "grace" (tier 9 talent). I don't know if it's from my end with server lag or what since it only happens maybe 25-30% of the time but it's a issue when healing 25m raids and I need that extra tick of healing.

P.S. - I've also noticed that in PvP - when I use it **offensively** that it doesn't happen and all 3 bolts fire out and register as damage so it's only when healing.

https://www.wowdb.com/spells/186720-penance
https://www.wowdb.com/spells/200309-grace

Edit: I wanted to say about the lag that I'm in the US and typically have constant 115ms lat - nothing crazy.

**Comment by TheManiax** [comment]
Thanks for the report @Tamagucci 
By casting it normally, you will always get 3 bolts. I tried +200 cast in PTR.
So **IF** there is something affecting it and making it cast 1 less bolt, we need reproduce steps for it.
Please add reproduce steps so we can find the code that needs to be changed.
I will leave the report open for more hours maybe any other tester knows how this can be reproduced.

**Comment by Dranah** [comment]
Quick question, are you using nochanneling command on your spells?
Penance is a channeled spell, and like other similar effects (mind flay, arcane missiles) it is interrupted by any spell you cast. It's duration slightly exceeds the GCD, so if you try to "queue up" the next spell too early, it will clip the 3rd tick.
When spamming spells macroed with nochanneling, I always get all the 3 ticks right.

**Comment by Tamagucci** [comment]
Thanks for the reply.

No macros or anything - just dragged from spell book onto the bar. I do use
quartz addon so it gives me the latency of the spell and I've noticed that
when the red zone is bigger then normal is when it'll only shoot 2 out.
That's why I figured it was a problem with my end to the server.




On Aug 20, 2018 11:58 AM, "Dranah" <notifications@github.com> wrote:

Quick question, are you using nochanneling command on your spells?
Penance is a channeled spell, and like other similar effects (mind flay,
arcane missiles) it is interrupted by any spell you cast. It's duration
slightly exceeds the GCD, so if you try to "queue up" the next spell too
early, it will clip the 3rd tick.
When spamming spells macroed with nochanneling, I always get all the 3
ticks right.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/WoWManiaUK/Redemption/issues/2667#issuecomment-414368967>,
or mute the thread

**Comment by Dranah** [comment]
I'm fairly certain you're simply clipping the spell then. It's difficult to queue the next spell at the right time with no macros + latency.
I suggest you macro a nochanneling command to every spell that is no priority above finishing your Penance channel.
Example:
/cast [nochanneling] flash heal
This way your flash heal won't be allowed to begin casting until your penance finished channeling, even if you have latency. It can also prevent clipping Divine Hymn or Hymn of Hope which behave the same way (any spell you cast while channeling will immediately end their channel)
