### ISSUE TITLE
[Quest] "The Rethban Gauntlet" not starting

### ISSUE THREAD

**Issue by Tabris0017** [WoWManiaUK/Redemption#2668]
I took the quest "Yorus Barleybrew" from a Warrior Trainer at level 20, and when completing the quest the next stage "The Rethban Gauntlet" didn't start. The pane popped up for half a second but then closed before I could agree to the quest. He no longer offers the quest so I won't be able to do the subsequent quest "The Shieldsmith" or the rest of the chain. 

Character: Daelan, dwarven warrior

**Comment by GmSaintz** [comment]
Appears to be working as intended. Seems to be an isolated issue. Problem has been taken care of.
