### ISSUE TITLE
[Mount] Invincible

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#2669]
Hello,

I have heard before of the issues with the LK 25HC mounts [Invincible], and now that I have gotten it, i find it odd how it acts. 

First, it can only be mounted in northrend, and cannot be used anywhere else, neither azeroth nor Outland. Also, the mount, which was available in retail Wotlk, doesn't even count as an actual mount in the achievement Mountain o' Mounts.

Amytis told me this: 'As I see, Janitor has changed it so it can be used in Azeroth as a flying mount, and as a side effect, it lost some options like being able to be used as a ground mount in dalaran. But now, the ability to fly in azeroth is gone as well. So it needs to be reported on the Github. 

So yea, right now it can't be used as ground mount anywhere, and can only fly in Northrend. :/

I would honestly rather have it be like in retail than how it is right now. Even if that meant not being able to fly in Azeroth.

Thanks for your time.
Oganku

**Comment by Oganku** [comment]
After further testing, the mount can actually be used in Outland, but still not in Azeroth or as ground mount.

**Comment by wow-mania** [comment]
Nothing has changed on this in months but I will check.

**Comment by wow-mania** [comment]
Fixed in dev. Those with the issue will have to open a ticket to have the mount spell removed and then re-learned.

Spell to remove: 72284
Spell to add: 72286

**Comment by TheManiax** [comment]
The ground mount speed is not set to 100%
needs a recheck

**Comment by wow-mania** [comment]
Works. I have just tested.

**Comment by TheManiax** [comment]
Confrimed
My bad :stuck_out_tongue:
