### ISSUE TITLE
Spark of Imagination Combat bug

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#2670]
Not sure if this is still related to Mimiron encounter as you get this problem without even engaging him.

When teleporting to Spark of Imagination in Ulduar, you and your raid (even those that are elsewhere) immediately get into combat. This results that people who are elsewhere cannot use teleporter anymore.
You cannot get rid of it with .cl, you immediately get back into combat again. Leaving the raid or going outside to Storm peaks does not remove it either.
Only way to remove it is to die, every single raid member has to be dead at same time or it comes back.
After wiping to remove combat, it does not return until soft reset.

PS: I can't log on the PTR to test what could possible be responsible for this. Janitor is unresponsive and i'm locked out.

**Comment by Oganku** [comment]
Actually, only the people that are at the Spark of Imagination has to wipe. I have fixed the combat bug before by engaging Mimiron (on hard mode if that matters) alone and dying.

**Comment by Dranah** [comment]
This got reverted by last update.
