### ISSUE TITLE
[Boss] General Vezax

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#2672]
https://www.wowhead.com/npc=33271

There are so far the following problems I noticed:

1) Searing Flames somehow going off after being interrupted.
https://www.wowhead.com/spell=62661
It may have something to do with Vezax casting multiple spells at the same time, because it usually happens when multiple spells coincide. He puts a Mark on somebody, then throws a shadow crash and begins casting Searing Flames nearly same moment. You cast an interrupt, it does not miss, you see his cast bar interrupted and 2seconds later, your raid still gets hit by the fire AOE and receives the debuff as well.
Note there was no lag during any of my tests.
EDIT: I found that sometimes Vezax visually interrupts his own Searing Flame cast by beginning to cast another spell. But the spell still goes off if you don't land an interrupt afterwards. This is confusing, sometimes it's hard to tell if your interrupt landed or Vezax just fucked up his cast bar.

2) Shadow Crash targeting melee. https://www.wowhead.com/spell=63277/shadow-crash
This may have something to do with the boss' large hitbox. And I suspect the distance is calculated wrongly, from the center of his hitbox rather than the edge.
What happens is if you have melee dps attacking him just outside his red circle (but still in melee range, as they can attack with melee spells and he has a fairly huge hitbox), Shadow Crash will notice them as possible targets and be cast on them. This should never happen unless there are no ranged targets available. 
How it should work: It should check for 15 yards from the edge of his hitbox, not the center. Only players beyond that 15 yards should be considered as targets.
Note: you can't just expect melee to stay inside the red circle at all times. Vezax is supposed to be kited through Surge of Darkness and he casts Shadow Crash as soon as it falls off.

EDIT:

3) Shadow Crash likely targeting dead players.
After further testing, I found that after a couple of ranged units die, the cast frequency of Shadow Crash drops to nearly half. Like every 2nd crash is "missing", probably due to Vezax attempting to target one of the dead bodies at those casts.

**Comment by Dranah** [comment]
Adding a 4th point)
https://www.wowhead.com/spell=63276/mark-of-the-faceless
Mark of The Faceless seems to be able to target melees even when you have 4+ ranged targets available on 10man mode (which is the requirement to prefer ranged)
It seems to have something to do with spell range as it usually happens after a shadow crash hits a ranged group and knocks them away.
The spell is supposed to have a 100 yard range of cast and that means ranged being knocked away to 50-60 yards is still supposed to be the target.
What happens atm is that when a couple of ranged are knocked back, the mark is cast on melee.

**Comment by Keader** [comment]
@Dranah i need you multibox magic to test it.
To Melee Range check works, code say that need  5 or more  alive/out of range in 10 man, and  9 or more alive/out of range in 25 man.
PS: Out of range =  15y < distance < 50y

**Comment by Keader** [comment]
Fixed.
Searing Flame is just visual interrupt, spell always work now, even if got "interrupt" in cast bar

**Comment by Dranah** [comment]
Shadow crash 15 yard min range check is now proper.
Waiting for fix on max-range on both Shadow Crash and Mark of Faceless to be built.

**Comment by Dranah** [comment]
I'm sorry i found some more small problems:

- General vezax should be taunt immune at all times (right now is tauntable)
- Paladins who have Judgement of the Wise in their spec should receive a debuff "Corrupted Wisdom" during this fight which increases mana gained from judgement of the wise but decreases healing done
https://www.wowhead.com/spell=64646
This is currently missing.

**Comment by Dranah** [comment]
UPDATE
- General Vezax is no longer tauntable (works good)
- Corrupted Wisdom now grants proper mana increase to retri pallies on 10man mode (also good)

- Corrupted Wisdom (64646) must be added to 25man difficulty as well (need fix)
- Corrupted Rage https://www.wowhead.com/spell=68415/corrupted-rage
It must be added to both 10 and 25man difficulties: This effect is the shaman version of the above one, it decreases healing done by 90% when they have Shamanistic Rage talent in their build, but increases the mana returned from the spell's procs by 100%.
