### ISSUE TITLE
[NPC] Ominous Cloud (Yogg saron)

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#2674]
https://www.wowhead.com/npc=33292

These are the green clouds during phase1 that spawn Guardians https://www.wowhead.com/npc=33136.
Sara herself activates one time to time, otherwise they can be "popped" by players touching them.

Problem: Currently every time a player touches a cloud, it spawns two Guardians instead of just one.
Clouds activated by Sara spawn only one Guardian as intended.

**Comment by TenmanWoW** [comment]
Tested this for Dranah with his directions. Screenshots incoming

**Comment by TenmanWoW** [comment]
![wowscrnshot_081818_180337](https://user-images.githubusercontent.com/25806987/44312155-26cc4a80-a3b9-11e8-8bb0-23e56d391090.jpg)

**Comment by Dranah** [comment]
Problem with double spawns is fixed, however there is another issue with chain triggers that is still being worked on.

**Comment by Dranah** [comment]
Update:

- Clouds popped by players now register double trigger upon being touched (as opposed to one trigger spawning two adds before, now two triggers spawn two adds) - this need fix
- Clouds popped by players now cannot be triggered again until the add spawns -this works good
- Clouds popped by Sara spawn only one add, but have no immunity to being triggered over and over, they can register a new trigger every 2-3seconds - this need fix
