### ISSUE TITLE
[Boss] Zul'Gurub - Edge of Madness

### ISSUE THREAD

**Issue by therealjimboslice** [WoWManiaUK/Redemption#2675]
Wanted to see if it's possible to summon these bosses. I leveled alchemy to 300 and was able to learn recipe for [Gurubashi Mojo Madness] simply by clicking the large tablet in the center. https://www.wowhead.com/item=19931/gurubashi-mojo-madness#comments

It seems the only thing missing to start the encounter is the Brazier of Madness.

**Comment by GM-Gathios** [comment]
Confirmed.

The Brazier of Madness (http://wow-mania.com/armory/?object=180327) is missing. URL on Armory is also not working.

**Comment by WhitephoenixTheBunny** [comment]
I tested in Red (ptr down) i can learn the recipe, but no brazier. I will try get more info about it.
