### ISSUE TITLE
[QUEST] The Storm King's Vengeance

### ISSUE THREAD

**Issue by furkanaltur34** [WoWManiaUK/Redemption#2676]
Hi, 
The mob named "Algar the Chosen" isn't spawning in quest area. 
Mob link: https://www.wowhead.com/npc=29872/algar-the-chosen
Quest link: https://www.wowhead.com/quest=12919/the-storm-kings-vengeance

**Comment by wow-mania** [comment]
NPC is there.
Follow comments on your links.

**Comment by furkanaltur34** [comment]
sorry for disturbing then, im using updated wow-mania client and i tried a couple times restart quest, but "Algar the Chosen" isn't at that area.

**Comment by wow-mania** [comment]
The NPC moves around. No fixed spot. It may be a phase issue. But the NPC is there for sure. We will check it.

**Comment by TheManiax** [comment]
The NPC is there, but it's a phase issue.
NPC Phasemask: 256
Can't be seen by players with the quest active in their logs.

**Comment by wow-mania** [comment]
Quest works fine for me. Just tested. Do all pre-quests and follow order in videos and it just works.
If you could see the other NPCs you had to kill then you could see this one.
You can't break the quest into parts or come back later.
