### ISSUE TITLE
Noggenfogger Elixir - cannot mount in undead shapeshift

### ISSUE THREAD

**Issue by marko0419** [WoWManiaUK/Redemption#2680]
Dear GM's,
Whenever I drink Noggenfogger Elixir with any of my characters and get the undead form it provides, I can't mount, just get an error message which says: 'You are in shapeshift form.'
Can you fix this by any chance? It appears to be a server-wide issue according to players.
Thanks in advance,
Flamelash

**Comment by wow-mania** [comment]
As-is the ability to mount came only with 5.0.4

**Comment by wow-mania** [comment]
Pretty sure this refers to reduction size only and not the shapeshift but as you said this is quite harmless and may be fun so I have changed so you can now mount while under the shapeshift effect of Noggenfogger.

**Comment by Dranah** [comment]
Confirmed, you can now mount with the effect. Cheers!
https://imgur.com/KC63UOK
