### ISSUE TITLE
Belt of broken bones

### ISSUE THREAD

**Issue by kallemeisner** [WoWManiaUK/Redemption#2682]
![screenshot_29](https://user-images.githubusercontent.com/32076729/44371938-c7b62500-a4e1-11e8-9d23-feca457c2ff1.png)

As you can see here the belt´s apperance is missing

**Comment by TheManiax** [comment]
[[Belt of Broken Bones]](http://www.wow-mania.com/armory/?item=50036)
Graphic data missing for Male Undead.

**Comment by wow-mania** [comment]
As-is. This is an original wotlk item so nothing we can do.

**Comment by kallemeisner** [comment]
Really? Wtf...

**Comment by wow-mania** [comment]
Yes, we did nothing on its appearance so we can change it back. It looks as it does on a pristine client.
