### ISSUE TITLE
[Quest] Abduction

### ISSUE THREAD

**Issue by TenmanWoW** [WoWManiaUK/Redemption#2685]
Quest ID - 11590  (Wowhead is giving me a bad gateway error, idk)
Quest NPC 25585

How it's supposed to work:

  You engage a Beryl sorceror and get the npc below 25% health. You then use the provided quest item to "capture" the NPC, turning him friendly and on follow, for return to the quest giver.

How it's currently working:

 All Beryl sorcerors in the quest area are currently friendly. There are no capturable sorcerors available, making the quest unable to be completed. Upon abandoning the quest, the sorcerors remained friendly with the title of "Captured Beryl Sorceror". 

Steps to reproduce:

  Acquire quest, fly down to Beryl point, and see that all sorcerors on the field are friendly and already captured..

Supporting screenshots

![wowscrnshot_082118_144259](https://user-images.githubusercontent.com/25806987/44425509-b0af1b80-a551-11e8-8cb9-9fa22d859674.jpg)
![wowscrnshot_082118_144144](https://user-images.githubusercontent.com/25806987/44425510-b0af1b80-a551-11e8-971e-24eb13107664.jpg)
![wowscrnshot_082118_144140](https://user-images.githubusercontent.com/25806987/44425511-b0af1b80-a551-11e8-963f-f4b9526e0953.jpg)
![wowscrnshot_082118_144133](https://user-images.githubusercontent.com/25806987/44425512-b0af1b80-a551-11e8-8236-65333570a8f0.jpg)

**Comment by WhitephoenixTheBunny** [comment]
They are friendly cuz someone give up in the middle of the quest... Open a ticket, GM will reset NPCs

**Comment by GM-Gathios** [comment]
This issue is confirmed, as what Phoenix mentioned. 

The NPC's should reset themselves when the quest is abandoned, so no GM's are needed to reset.

**Comment by WhitephoenixTheBunny** [comment]
The same happen with The Battle For Crusaders' Pinnacle (http://www.wow-mania.com/armory/?quest=13141), if someone abandon quest while banner up, player cant put a new one, and GM wil need kill the banner.

**Comment by wow-mania** [comment]
Send me the id of the objects and I will make sure they despawn after 3m

**Comment by wow-mania** [comment]
NPC will now despawn 3 min after it enters combat or dies.
