### ISSUE TITLE
[Quest] Inability to gain "Smelt Dark Iron" from quest

### ISSUE THREAD

**Issue by Tabris0017** [WoWManiaUK/Redemption#2686]
When I did the quest "The Spectral Chalice" from NPC Gloom'rel in Blackrock Depths to get the ability to smelt dark iron ore in to dark iron bars, I wasn't able to actually get the ability. I already spoke to a GM and they said that the quest completed but the additional dialogue with Anger'rel wasn't there so the ability wasn't given to me even though the quest was completed.

Quests
https://www.wowhead.com/quest=4083/the-spectral-chalice
NPC
https://www.wowhead.com/npc=9037/gloomrel
Ability
https://www.wowhead.com/spell=14891/smelt-dark-iron

Character: Zankoku
Edited to add WoWhead links

**Comment by WhitephoenixTheBunny** [comment]
Working fine in PTR, you need speek Gloom'rel to get the ability.

![image](https://user-images.githubusercontent.com/31921098/44511999-1d8cf780-a6b1-11e8-9cc2-e29fd6bac37e.png)
