### ISSUE TITLE
[NPC] Koltira Deathweaver is missing

### ISSUE THREAD

**Issue by GM-Gathios** [WoWManiaUK/Redemption#2687]
https://www.wowhead.com/npc=29795/koltira-deathweaver

This NPC is missing. He should be on the Horde air ship. 
![wowscrnshot_082218_104701](https://user-images.githubusercontent.com/39500349/44453363-2ae6ab00-a5f9-11e8-8fa7-cf1d3a148600.jpg)

**Comment by wow-mania** [comment]
Will come back after restart
