### ISSUE TITLE
Game crashes at Barbershop

### ISSUE THREAD

**Issue by Kytanna** [WoWManiaUK/Redemption#2689]
I've seen forum comments on this, but not an answer to the crashing issue. Every time you're at the Barbershop and get to the new hairstyles, or what would be, the game crashes. I didn't see a ticket for it open, despite the forum posts so I'm hoping this will be helpful.

**Comment by WhitephoenixTheBunny** [comment]
#1557 #1198

**Comment by wow-mania** [comment]
Nothing we can do about this. There are certain combinations of hair and face styles that cause it.
Ask a GM to flag you for character re-customization.
