### ISSUE TITLE
[Quest] Where in the world is Hemet Nesingwary?

### ISSUE THREAD

**Issue by TenmanWoW** [WoWManiaUK/Redemption#2690]
Quest ID - 12521

https://www.wowhead.com/quest=12521/where-in-the-world-is-hemet-nesingwary

How it should work:

Speak to Archmage Pentarus to gain access to his flying machine which takes you through a portal into Sholazar Basin where the quest sequence begins with you being taken towards the objective. Towards the end, the flying machine is shot down by Venture Co and you land near the quest NPC who is hanging in a tree.

How it currently works:

Speaking to Archmage Pentarus to gain access to the flying machine while goes throught the portal correctly. When you appear in Sholazar, the flying machine appears to be hovering, but in reality it is moving foward at almost not measurable speed. 

What to fix:

  Need to normalize the flight speed of the flying machine

How to reproduce:

 Talk to Archmage, hop in flyilng machine, load into Sholazar and supporting screenshots below.

These were taken about a minute apart.

![wowscrnshot_082518_162737](https://user-images.githubusercontent.com/25806987/44622813-592cea80-a886-11e8-8108-3a179869694c.jpg)
![wowscrnshot_082518_162657](https://user-images.githubusercontent.com/25806987/44622814-592cea80-a886-11e8-832c-e56b468402bc.jpg)

**Comment by wow-mania** [comment]
What is the id for the vehicle?
This was working fine.

**Comment by wow-mania** [comment]
http://www.wow-mania.com/armory/?npc=28192

**Comment by TheManiax** [comment]
The speed is still the issue
The vehicle is moving very slow

**Comment by wow-mania** [comment]
How slow?

**Comment by Rushor** [comment]
this is still an issue. will fix.

the vehicle speed was totally bugged because of wrong teleport and missing grid load.

fixed like in https://github.com/WoWManiaUK/Blackwing-Lair/issues/787
