### ISSUE TITLE
[Loot] Flame Leviathan hard modes

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#2691]
https://www.wowhead.com/npc=33113/flame-leviathan

How it should work (source: wowwiki 3.3.5):
10man /25man
1 tower: normal ilvl 219 for 10man/226 for 25man items + double emblem of triumph
2 tower: normal ilvl 219 for 10man/226 for 25man items + double EoT + guaranteed Runed Orb
3 tower: normal ilvl 219 for 10man/226 for 25man items + triple EOT + guaranteed Orb + recipe
4 tower: at least 1 piece of hardmode loot (ilvl 226-232 for 10man/239 for 25man) + triple EOT + guaranteed orb + recipe
Boss should always drop 2-3 pieces of gear that match above criteria, recipes have a chance to drop on 3-4 towers but is not a guaranteed drop. Runed orbs however should always drop on hardmode.

How it works atm:
Tested on 4tower full hard mode
Hard mode items are missing on both 10man and 25man, no extra emblems, no runed orbs drop and i've yet to see a recipe though that may be unluck. But the rest should be guaranteed drop.
In addition, when testing on PTR the boss drops 2-3 items as intended, but on Redemption it drops full gallery of normal loot table to me. (8 pieces, see screenshot below)
https://imgur.com/d0ilUo2

**Comment by Dranah** [comment]
I need to add here some further problems:

1) Problem with health values on 25man mode:
In 25man, all Demolishers and Siege engines are spawned and start off 50% health. There is no way to heal them unless using the repair system, which makes "Unbroken" more difficult to obtain.

2) Problem with energy level of Demolishers.
On both 10m and 25m difficulty, Demolishers spawn with 0 energy (energy=pyrite)
They are supposed to start off with a full bar.

Here is a video that sums up how it should work when you enter a vehicle:
https://www.youtube.com/watch?v=Hx6stgx8WRQ
As you can see, the demolisher starts with full health and full energy bar as the guy mounts it.

**Comment by Keader** [comment]
Ok, i change core to handle with number of broken towers.
And i remade loot table based in Sunwell Core, since wiki say that is not 100% correct.
I realy think it's fixed.

**Comment by Dranah** [comment]
Extra emblems, runed orb drop and hard mode items are now dropping off hard mode so the composition of loot is correct.
However there is a problem with the amount of loot. It still drops like 8-9items on both difficulties.
It should be two pieces on 10man normal, 3 pieces on 10 hard mode (at least one 226) and 25man, and 4 pieces (at least one 239) on 25 hard mode.
