### ISSUE TITLE
[Ability] Chain Heal

### ISSUE THREAD

**Issue by Flux13** [WoWManiaUK/Redemption#2696]
The Chain Heal ability for shamans no longer jumps to people with full HP. Targeting someone with full HP will still allow it to jump to a nearby player with missing health, but players with full HP can't be used as a bridge between two players missing health who are too far away from each other.

**Comment by Dranah** [comment]
This is not fixed, I just tested on PTR. Chain heal ignores full health targets. cutting off its jumps if the "bridge" is someone with full hp.

**Comment by wow-mania** [comment]
Absolutely nothing changed

**Comment by NiX005** [comment]
Just tried healing with chain heal in game, and its clearly not jumping when the targets are at full hp like it should be this is not fixed its broken

**Comment by Keader** [comment]
It's not broken.
Should not Jump if all targets around is full HP. It avoid stack healing enchant doing overheal by chain heal. (blizzlike).

**Comment by NiX005** [comment]
So may I ask why this used to heal and jump when people were on full hps a few days ago and now it doesnt? makes the 4p t10 kinda worse now when your trying to stack heals in raids for incoming damage etc.  So druids wild growth shouldnt land on people with full hp by your line of thought then as well

**Comment by Flux13** [comment]
I don't mean to be argumentative, but I clearly remember it chaining off of full health players until very recently. I've watched plenty of shamans sit in front of the banks in Dalaran and spam chain heal on all the players standing around. If that's not how it was supposed to work that's fine, but something definitely changed.

This issue prevents shamans from being able to spread around their tier 10 4 set bonus, earthliving  weapon proc, and the damage reduction from their ancestral healing talent as effectively as before.
