### ISSUE TITLE
[Boss] Kologarn vol. II

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#2700]
https://www.wowhead.com/npc=32930/kologarn
https://www.wowhead.com/npc=32934/right-arm
https://www.wowhead.com/npc=32933/left-arm

Here's a compilation of Kologarn bugs:

1) Focused Eyebeam https://www.wowhead.com/spell=63346/focused-eyebeam
Broken most of the time as the boss is staring at his own feet, the beams are directed into the hole he stands inside. Seldom they emerge and start circling in the room, but most of the time the beams aren't targeting raid members. This is not a visual problem, the beams are actually misdirected.
Note: this may be difficult to reproduce alone, as it seems to work fine when there is no one but the tank alive as a possible target. However in a regular raid, there are many targets and most of people are scattered around the room, some near the entrance or the walls. The spell may have trouble targeting or following you in certain positions.

2) Overhead Smash https://www.wowhead.com/spell=63356/overhead-smash 
and One-armed Overhead Smash https://www.wowhead.com/spell=63573/one-armed-overhead-smash
Description: On 25man, the long duration of Crunch Armor https://www.wowhead.com/spell=63355/crunch-armor stacked by these abilities allows the debuff to stack and demands tanks to be switching in order to let it wear off.
How it works: Now, the problem is that the Crunch Armor applied by these two different smashes don't seem to stack properly.
If the boss casts 2x Overhead Smash in a row, it will properly apply a 2nd Crunch Armor, refreshing the duration of previous.
However,if the boss casts one Overhead Smash, and then one One-armed Smash, the two Crunches will apply two different debuffs, not refreshing each other. This allows the buffs to expire and do the fight with just one tank.
How it should work: no matter which smash applies the Crunch armor, they should all go into same stack, refreshing duration.

3) Arms meleeing
Currently both arms are meleeing an aggro target for about the same amount as the boss himself. 
How it should work: They are not supposed to be offtanked, they should only be casting their Stone grip and shockwave respectively.
I could not find any sign from retail logs that the arms would have ANY sort of melee damage themselves. This means a lot of extra healing needed, or the arms to be offtanked.

4) Kologarn suicide
It occurs that when you wipe, Kologarn resets in a manner that he kills both of his arms first.
This means that if Kologarn is below 30% health when you wipe and both of his arms are up, the following happens
Last person dies > Kologarn's arms suicide > Kologarn himself dies because he is under 30% and each arm takes off 15%. Disarmed! Achievement is also awarded when he dies this way.

**Comment by Keader** [comment]
2, 3 and 4 fixed.
1 still need fix

**Comment by Dranah** [comment]
UPDATE:
1. Focused eyebeam issue still persists. (need fix)
2. Overhead Smash / One-armed smash stacking is now correct. (fixed)
3. The arms are still meleeing. (need fix)
4. Kologarn still kills his arms when you wipe. (need fix)

Can you please not close untested fixes?

**Comment by Dranah** [comment]
Eyebeams now work as intended.
Kologarn will no longer suicide.
