### ISSUE TITLE
[Spell] Moonkin Form

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#2702]
ID 24858 - Moonkin Form
ID 24907 - Moonkin aura

How it works atm: 
There is a problem with Moonkin Aura not properly applying when the druid casts Moonkin Form while already a Moonkin.
This is done by a /cast !Moonkin Form macro often used in pvp to dispel poly and snares.
If the druid shifts from humanoid or any other shapeshift form to Moonkin, the aura is properly applied.
However if he uses the above macro, to "recast" moonkin form without leaving it, he loses the 5% crit aura.

How it should work:
When the druid is in moonkin form, the moonkin aura must be always active.

**Comment by TheManiax** [comment]
@Dranah 
The macro ` /cast !moonkin` will cast moonkin **IF** it's not already active.
So, if you are already in moonkin form, it doesn't do anything.
You might need to add `/cancelform` at the first line of the macro to get a working macro that breaks snares and roots.
This might work in another way in next patches though.

**Comment by Hajzlopuc** [comment]
Hello, I would like to add some info. The macro is 

`/cast !Moonkin Form`

I recorded a short video. https://youtu.be/vn9151Q6-HA
First time I click the macro (from the human form) - everythings good.
Second time I cast the macro (already in moonkin) - **Moonkin Aura fades** - this shouldn't happen.

https://github.com/TrinityCore/TrinityCore/commit/57672fdf259d1106420e6a2c91f6f1b65b00fbc9 Maybe something with this?

**Comment by TheManiax** [comment]
As far as I know, `/cast !Moonkin Form` is not supposed to work at all when mookin form is already active at first place
But as I see, it does work in mania, and as you said, you loose moonkin aura if you use that macro
I doubt if anything should be changed here
@Keader  Can you take a look at this report please?

**Comment by Keader** [comment]
Not realy.
I have same issue with this macro.
I already debug it, i cant find why it dont work.
Because after commit linked here (https://github.com/WoWManiaUK/Redemption/issues/2702#issuecomment-418157708) everything work "fine" inside of Spell System, but cast dont work, idk why

**Comment by Dranah** [comment]
@TheManiax 
Wrong, this type of macros are used to "rebuff" yourself with the shapeshift aura, without leaving it for even a split second. It's been used this way for 10 year on WOTLK. 
There's a different macro /cast [stance:0] Moonkin Form or /cast [nostance] Moonkin Form, which is used to only activate moonkin form if you aren't already in it. I use that one to multibox, so that my druid doesn't keep casting moonkin form when she's already inside of it.

The macro i originally wrote works flawlessly for removing roots and snares, thus its use in pvp. That is NOT the problem I reported.
The problem is that after using this macro, you are a moonkin without moonkin aura. Which should never happen.
None of you even remotely discussed this problem, only that the macro should or should not work to remove snares. Can you please look into the actual issue?
If you can't find the problem and can't fix it, then it's a different matter.

**Comment by wow-mania** [comment]
What are we missing here? Can we close it?

**Comment by Keader** [comment]
Nope. Issue is real.
I fixed it last night, I will send to you when I go work
