### ISSUE TITLE
Wolfshead Helm issue

### ISSUE THREAD

**Issue by zonefrost** [WoWManiaUK/Redemption#2703]
the item Wolfshead Helm advertises that it gives 20 energy when shifting into cat form and 5 rage when shifting into bear form. the latter works, the former does not. this is a pretty expensive hat to craft to not have it work correctly.

**Comment by TheManiax** [comment]
https://www.wowhead.com/item=8345/wolfshead-helm

**Comment by Keader** [comment]
ahh, it's spell issue.
I will take a look tonight or tomorrow xd

**Comment by Dranah** [comment]
gives energy and rage as intended now
