### ISSUE TITLE
[Quest] Path to the Citadel

### ISSUE THREAD

**Issue by NiX005** [WoWManiaUK/Redemption#2704]
Hi there, the freeing slaves part of this quest isn't recording slaves being freed, only the kill on Garfrost has worked for the quest.  Had multiple people have this same issue last few days, re-taking quest and clearing cache doesn't make a difference for this.

**Comment by TenmanWoW** [comment]
Quest - https://www.wowhead.com/quest=24507/the-path-to-the-citadel
Quest ID - 24507
NPC - 36770 (Horde) 36764 (Alliance)

Freeing the slaves works, as they respond appropriately. However, credit is not given towards the 15 required for quest completion.

**Comment by TheManiax** [comment]
This was working like 10 days ago
Is there anything changed here? @wow-mania

**Comment by TenmanWoW** [comment]
Currently working on PTR, just checked. Was not working an hour ago on Red. Looking into reasons.

**Comment by TenmanWoW** [comment]
https://media.discordapp.net/attachments/470402840309792789/486401431562354698/WoWScrnShot_090418_000410.jpg?width=1323&height=702

https://media.discordapp.net/attachments/470402840309792789/486401432799674378/WoWScrnShot_090418_000415.jpg?width=1323&height=702

**Comment by wow-mania** [comment]
Was this working before?

**Comment by TheManiax** [comment]
![image](https://user-images.githubusercontent.com/14857593/45048500-5655a500-b091-11e8-92df-ad18f11bd6c1.png)
It's working on both realms
I don't see how you could reproduce it.

**Comment by TheManiax** [comment]
The issue seems to be real
We just need repro steps
I leave the report open for some more time

**Comment by WhitephoenixTheBunny** [comment]
Testing Races atm (will update post), so far the quest is NOT working for:
Human
Gnome

**Comment by GMWeeble** [comment]
Issue found. Just the slaves has been swapped (the credit for horde is alliance and for ally is horde.)
No idea how it happend but I guess that is the issue-

**Comment by WhitephoenixTheBunny** [comment]
Tested on ally and horde side :P
