### ISSUE TITLE
[Hunter Talent] Piercing Shots

### ISSUE THREAD

**Issue by crulinjr** [WoWManiaUK/Redemption#2705]
https://www.wowhead.com/spell=53234/piercing-shots

Current behaviour: Tell us what happens in detail (Where, When, What, Why, Who)

The MM talent, Piercing Shots, is a bleed dot that procs from your critical Chimera, Aimed and Steady Shots. Ill describe how it is working and the moment and how it should work.

How it works right now:
Everytime you crit with those abilities you will get the DoT and each crit will overwrite the one you had before. If for example you crit with a Chimera Shot for 9900 your bleed should do 3300 over 8 seconds (412 bleed per second)  but if you crit with a Steady Shot right after that for 5100 the bleed will change to 1700 over 8 seconds (212 bleed per second).

How it should work:
Lets use the example i use before, so our target is bleeding for 412 per second (chimera shot crit) now if we crit with Steady Shot after 2 seconds the game should recalculate the bleed damage and add up the rest of the Chimera shot bleed (3300-824=2476) to the steady shot bleed damage (1700) and get a new bleed (2476+1700=>4176/8=522 bleed per second). This should be ocurring everytime you get a new crit with Chimera, Aimed and Steady Shot.

I will link an image from a retail hunter's bleed damage.
https://imgur.com/1C8DTdk

Screenshot from Piercing shots damage. You can see that the dot damage does not go above 454 per second despite me criting with chimera shot 7 times. This 454 damage per second corresponds to a 12107 Chimera Shot.
![wowscrnshot_090518_131705](https://user-images.githubusercontent.com/40045543/45112745-15e83c80-b10e-11e8-9a6b-fa967bb56305.jpg)

Include Screenshots from the issue if necessary

Screenshots above for proof

Hope this can raise some attention to this issue, ive looked through the forums for similar issues to not duplicate but couldn't find anything for this spell so here it is.

**Comment by crulinjr** [comment]
Any comments on how progress is going?

**Comment by Dranah** [comment]
@crulinjr I confirmed the problem so now it's waiting for Keader to fix it. He does not work well under pressure so please be patient.

**Comment by crulinjr** [comment]
Haha its ok thanks for the reply. Just wanted to know if You are working on
It.

**Comment by crulinjr** [comment]
This means its fix?

**Comment by Dranah** [comment]
Yes, the extra damage is now added to the remaining.
