### ISSUE TITLE
Living seed not working

### ISSUE THREAD

**Issue by diplo1** [WoWManiaUK/Redemption#2706]
Druid talent Living seed is not working. I have all 3 points in the talent, it gives you the buff 100% of the time, but when you get damaged it disappears without doing any healing I did a full icc 25 hc run while casting more than usuall, and I did 0 healing with it through the whole raid acording to skada and recount, I tested this in all dificulties of icc and ruby sanctum.

**Comment by TheManiax** [comment]
[[Living Seed]](http://www.wow-mania.com/armory/?spell=48500)

**Comment by TheManiax** [comment]
According to combat log, it's working fine in open world
![image](https://user-images.githubusercontent.com/14857593/45140137-24def580-b1c7-11e8-9d1e-b615e3d2ad9b.png)
I will try to reproduce in ICC to make sure

**Comment by TheManiax** [comment]
Works fine in ICC as well
![image](https://user-images.githubusercontent.com/14857593/45140305-96b73f00-b1c7-11e8-94a4-74758ada8635.png)
Might be something wrong with Skada or Recount, I'm not sure
But it's working fine for me
I suggest you to check it by combat log, if still bugged, add the info here with Screenshot please
