### ISSUE TITLE
[Spell] Gymer's Buddy

### ISSUE THREAD

**Issue by TheManiax** [WoWManiaUK/Redemption#2710]
This is a very old issue causing hundreds of tickets till now as reported by game masters
Also mentioned before by @GMWeeble [here](https://github.com/WoWManiaUK/Redemption/issues/1958#issuecomment-352225043) , but not enough info on how to reproduce back then.

 --------
When doing the quest [[The Storm King's Vengeance]](https://www.wowhead.com/quest=12919/the-storm-kings-vengeance), you will have to talk to the NPC [Gymer <King of Storm Giants>](https://www.wowhead.com/npc=29647/gymer) , Then you will ride Gymer as your vehicle which has several abilites.
The abilities are only working if you have the custom client as it seems, but this is not the issue (as players **HAVE** to use the custom client)
The issue is the [[Gymer's buddy]](http://www.wow-mania.com/armory/?spell=55430)
This aura will be casted on you when you ride Gymer
Getting disconnected, or relogging for any reason (mostly cause the vehicle's spells don't work for players without custom client) will result in dismounting the vehicle while you still have the aura on you, changing your phase completely
And the only way to get out of that phase is to make a ticket and ask a Game Master to unaura 55430
So what you need to change is to add a condition to the spell [[Gymer's buddy]](http://www.wow-mania.com/armory/?spell=55430) , so when the player logs out for any reason, he loses the aura

**Comment by Keader** [comment]
Now it will vanish on logout.
