### ISSUE TITLE
[Dungeon] Trial of the Champion

### ISSUE THREAD

**Issue by Ashamedlol** [WoWManiaUK/Redemption#2713]
Black Knight (http://wow-mania.com/armory/?npc=35451) on heroic version should not be stunnable, you can keep crowd controlling him which allows you to solo him easily.

PRIORITY (Incase other thread was missed): Alliance version of Grand Champions is broken right now: Once you finish all three champions, the instance won't progress, which means the instance is non-existant on alliance right now.

**Comment by NiX005** [comment]
On Alliance side ToC normal you dont get the chest from the first boss and cant talk to the guy to start the next noss, this is still bugged on normal

**Comment by NiX005** [comment]
Also bugged on heroic ally side

**Comment by Keader** [comment]
Because it was edited after fix made? :)

**Comment by Dranah** [comment]
Instance properly progresses now.

**Comment by WhitephoenixTheBunny** [comment]
@NiX005 When it have the label Fix in Dev, and Fix Confirmed in Dev, that means it is on Test Realm (PTR), it will be apply on next server resart.

**Comment by Ashamedlol** [comment]
Horde version now undoable: Horde Champions spawn so when you finish all 9 adds, The Jousting Champions are friendly and unattackable.

**Comment by Dranah** [comment]
Could be a side effect, can confirm now hordes are also getting the ally version of the dungeon.

**Comment by Dranah** [comment]
- Both Horde and Alliance are now getting proper enemies
- Horde groups sometimes get alliance version of NPC who starts event https://www.wowhead.com/npc=35005/arelas-brightstar instead of horde version https://www.wowhead.com/npc=35004/jaeren-sunsworn 
It's a cosmetic issue tbh but shouldn't be difficult to fix.

**Comment by Keader** [comment]
Try now @Dranah

**Comment by Dranah** [comment]
Looks good.

**Comment by Keader** [comment]
ty
