### ISSUE TITLE
[Glyph] Glyph of Flame Shock

### ISSUE THREAD

**Issue by Ashamedlol** [WoWManiaUK/Redemption#2716]
The glyph is increasing the values of Flame Shock crits by 15% only, not 60% as it describes.

Flat no-increase:
![dundun](https://user-images.githubusercontent.com/16576459/45328649-7d1a4c80-b565-11e8-9779-faca87f5985f.png)

2440 initial crit, 1665 DoT crits.

Glyph added in:
![dun](https://user-images.githubusercontent.com/16576459/45328694-a76c0a00-b565-11e8-9964-deb11061d062.png)
2806 initial crit, 1914 DoT crits.

Now if you calculate it, 2440 + 15% = 2806, 1665 + 15% = 1914.75. It's calculating by 15%, not 60%.

Glyph ID: http://wow-mania.com/armory/?item=41531
Flame Shocks (r1-r9): http://wow-mania.com/armory/?search=Flame+Shock#abilities

**Comment by Dranah** [comment]
Read tooltip again. It does not grant a flat 60% increase to the crit damage.
It grants 60% to critical DAMAGE BONUS increase.

A spell crit does 150% of a regular hits damage by default, which means the bonus is 50% (for Dk spells it is 100%, also some talents increase it to 100% for casters). Now, with elemental talent "Elemental Fury", that 50% bonus is already increased to 100% for you.
If you glyph it, it will increase the 50% spell crit bonus by 160% total (100% from elemental fury + 60% by glyph), which means the new bonus will be 130%.

Your non crit flame shock tick does 833 damage, with the unglyphed 100% bonus making it 1665.
After glyph, your critical damage bonus is 130% , so 833 x 2,3 = 1916

**Comment by Ashamedlol** [comment]
Should the initial hit also be increased though?

**Comment by Ashamedlol** [comment]
I took off the talents and here's the result:
Pre-Glyph: 1419 intitial hit crit
520 crit DoT

Post-Glyph: 1702 initial hit crit.
623 crit DoT.

If I calculate the 15%, it goes lower, is it scaling with something else other than Elemental Fury?

**Comment by Ashamedlol** [comment]
Thanks for the clarification then, mistaken about the multiplier/additive part.
