### ISSUE TITLE
[Quest] Foolish Endeavors

### ISSUE THREAD

**Issue by Etalide** [WoWManiaUK/Redemption#2719]
Hi,
I signal that the quest, in Borean Thundra doesn't work. The NPC doesn't attack the mob for the quest: Varidus the Flenser.
Thank's for the attention
Ewyan

**Comment by wow-mania** [comment]
Quest works. Maybe someone left it incomplete. Ask a GM to reset NPC.

**Comment by Etalide** [comment]
Ehm, nope.
I've asked to GM in game, he has controlled and then he told me to report the bug here...

**Comment by Etalide** [comment]
This is yours problems xD
