### ISSUE TITLE
Wrong phase in the DK starter place

### ISSUE THREAD

**Issue by zwezub** [WoWManiaUK/Redemption#2720]
Hi, In some way i managed to go past some quest in the DK starting area. And now i can't finish them because NPC's that not should be here are killing me immediately. Please help me

**Comment by wow-mania** [comment]
This is not a game issue. Open a ticket.

**Comment by zwezub** [comment]
Thet told me to talk to You...

11 sep. 2018 kl. 22:09 skrev Janitor <notifications@github.com<mailto:notifications@github.com>>:


Closed #2720<https://github.com/WoWManiaUK/Redemption/issues/2720>.

**Comment by zwezub** [comment]
The GM’s could not fix this!!

**Comment by wow-mania** [comment]
What is the char name? I will fix for you.

**Comment by zwezub** [comment]
Deathdeath

**Comment by wow-mania** [comment]
Done
