### ISSUE TITLE
[Quest] Neutralizing the Plague

### ISSUE THREAD

**Issue by TenmanWoW** [WoWManiaUK/Redemption#2721]
Quest - https://www.wowhead.com/quest=13297/neutralizing-the-plague
Quest ID - 13297

How it currently works: 

Killing the giant will yield the spine needed to create the item used on the cauldron. When used on the cauldron, it gives quest completion but does not spawn the appropriate mob(s) that is indicated by "Something emerges from the cauldron".

How it should work:

Neutralizing the cauldron spawns mob(s) which need to be killed before quest completion is achieved.

As per GM Aymelek

**Comment by wow-mania** [comment]
Tested quest and it works fine.
It's a probability. You have 1 in 3 chances of it to just work and neutralize it. I guess you were lucky.
When it does not neutralize it spawns the mobs.
