### ISSUE TITLE
[Spell] Death Knight Spell Ranks

### ISSUE THREAD

**Issue by Ashamedlol** [WoWManiaUK/Redemption#2723]
When the DK learns spells and logs off, he loses the PREVIOUS spell ranks he has learned due to the logoff, this includes all spells he has learned from level 55+ and spells in talents except last rank of the spell learned.

Example:
![spec](https://user-images.githubusercontent.com/16576459/45466484-c82d8e80-b722-11e8-9649-348889ba67ea.png)
I just specced into blood, I got all ranks of Heart Strike

So, I decide to relog, and I lose all of my Heart Strike ranks except rank 6:
![spec2](https://user-images.githubusercontent.com/16576459/45466497-d54a7d80-b722-11e8-95d2-defd02735381.png)

Having low rank spells can be useful for specific circumstances such as rank 1 Icy Touch on a spell reflect or for example Dark Nucleus orbs of Prince Keleseth.

**Comment by Dranah** [comment]
Do lower rank spells also not work via macros?

**Comment by Ashamedlol** [comment]
They do I believe, have tried it but just not visible on the spellbook.

**Comment by Dranah** [comment]
So this is more of a visual issue.

**Comment by Keader** [comment]
Each time that i try fix it, i break rank of alot of spells.
I realy think it's so cosmetic and nobody realy use it, that i dont wanna lose more time trying find why it is not working only for DKs.
So... i'm closing it.
