### ISSUE TITLE
[Spell] [Frost Strike] interaction with %Damage Modifiers

### ISSUE THREAD

**Issue by TheManiax** [WoWManiaUK/Redemption#2724]
[[Frost Strike]](http://www.wow-mania.ru/armory/?spell=49143)
[[Strength of Wrynn]](http://wow-mania.com/armory/?spell=73828)
[[Hellscream's Warsong]](http://wow-mania.com/armory/?spell=73822)

**Pre-needed Data:**
All calculations include the talents of [[Glacier Rot]](http://www.wow-mania.ru/armory/?spell=49791) (20%) and [[Tundra Stalker]](http://www.wow-mania.ru/armory/?spell=50130) (15%)
No-ICC buff
![image](https://image.prntscr.com/image/xU3Uv5a1QC6JA8X3sK5ztw.png) 

**How it should work (after applying the ICC +30% buff):**
```
2195 + 30% = 2853.5 Flat
5032 + 30% = 6541.6 Crit
```

**How it works (after applying the ICC +30% buff):**
ICC buffed
![image](https://image.prntscr.com/image/2NXnYDQDSpGycFt6jtwNyw.png)
Values going out:
```
4041 Flat
8064 Crit
```
-----

What ever is causing it, should probably be in [[Frost Strike]](http://www.wow-mania.ru/armory/?spell=49143)'s script, since it scales unusually high with other damage boost buffs like [[Essence of the Blood Queen]](http://www.wow-mania.ru/armory/?spell=70867).

**Comment by Dranah** [comment]
This problem includes any %damage buff not only ICC one.
I.eg. Essence of the Blood Queen 70867 gives 4 times the damage instead of x2.

**Comment by Keader** [comment]
will be fixed next week i think

**Comment by Dranah** [comment]
"Apply Aura: Mod Damage Done % (Arcane, Fire, Frost, Holy, Nature, Physical, Shadow)" effects no longer double dip Frost strike damage, however they don't seem to be affecting the extra 138 damage it has added to the weapon damage. This results in a minor (2-3%ish) negative difference on damage values. Not priority, but need to be fixed.

**Comment by wow-mania** [comment]
After discussing with @keader and seeing the current result we will consider this one fixed. The difference is minute (under 2% in the worst case).
