### ISSUE TITLE
[Spell] [Chimera Shot] interaction with %Damage Modifiers

### ISSUE THREAD

**Issue by TheManiax** [WoWManiaUK/Redemption#2725]
[[Chimera Shot]](http://www.wow-mania.ru/armory/?spell=53209)
[[Strength of Wrynn]](http://wow-mania.com/armory/?spell=73828)
[[Hellscream's Warsong]](http://wow-mania.com/armory/?spell=73822)

**Pre-needed Data:**
No-ICC buff
![image](https://image.prntscr.com/image/uxtoINHhSQ_-kbQu4NLnfA.png) 
```
Min damage: 2876
MAX damage: 2936
Crit damage: 7386
```

**How it should work (after applying the ICC +30% buff):**
```
Min damage:2876*1.3= 3738.8
MAX damage:2936*1.3= 3816.6
Crit damage:7386*1.3= 9601.8
```

**How it works (after applying the ICC +30% buff):**
ICC buffed
![image](https://image.prntscr.com/image/0aNujj6YQE60IBYDt3dg8A.png)
Values going out:
```
Min damage: 4908
MAX damage: 5257
Crit damage: 11k-12k
```
-----

This is extremely similar to #2724  as you have noticed for sure. Same thing happens with other damage boost buffs, so probably it's the spell / core, not the ICC buff. But you can make sure by rechecking the script.

**Comment by Dranah** [comment]
The catch here is that both of these effects rely on weapon damage to calculate themselves.
As ICC buff already increases your weapon damage by 30%, and then affects the spell by further 30%, it results in a double-dip.
I am not fully sure if this is a bug, as these spells don't have a fix damage value like Ignite does.

**Comment by Ashamedlol** [comment]
Spells like Heroic Strike/Slam are considered the same type of weapon damage + base value and yet scaled perfectly into 30%, the only difference is this one is frost damage instead though.

**Comment by Dranah** [comment]
Mmm, likely because the buff gives %damage to both physical and magic spell schools. Pure physical effects only receive the physical modifier, while in these spells' case, weapon damage gets the physical school increase and the nature/frost damage gets the nature/frost increase afterwards.

**Comment by Keader** [comment]
will be fixed next week i think

**Comment by crulinjr** [comment]
how can i see the tooltips the way it is shown in the screenshots?

**Comment by crulinjr** [comment]
Alright thanks dranah i can always count on you
