### ISSUE TITLE
[Spell] Seal of Corruption / Seal of Vengeance

### ISSUE THREAD

**Issue by Ashamedlol** [WoWManiaUK/Redemption#2726]
http://wow-mania.com/armory/?search=Seals+of+the+Pure

How it should work: The seal damage is amplified by 15%, from judgment to seal function.

How it works: The amplifier is going into a bigger number (30%?) to Seal of Corruption/Seal of Vengeance as seen below:
I stack up my Seal of Corruption/Seal of Vengeance to 5 stacks, then I spec into Seals of the Pure after it ticks three times:

![dmg](https://user-images.githubusercontent.com/16576459/45493039-7f072a00-b776-11e8-86de-fc4f77041606.png)
Notice how it jumps from 64 to 73 after I add in 5 points into Seals of the Pure, which is the addition of 64 + 15% 

So, I decide to not refresh the seal and build up a new one into 5 stacks:
![dmg2](https://user-images.githubusercontent.com/16576459/45493131-bfff3e80-b776-11e8-8ab8-127b2c4734d8.png)
It jumped from 73 to 83, which is the 30% of 73.

**Comment by Dranah** [comment]
Another DOT that double dips, hell yeah.

**Comment by Dranah** [comment]
does the talent calculate wrongly for any other seal than SOC/SOV?
If not, then again it is the Seal's core problem rather than the talent's
