### ISSUE TITLE
[Item] Item skins for capes

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#2727]
Hello,

According to wowhead, [Royal Crimson Cloak](https://www.wowhead.com/item=50718/royal-crimson-cloak#same-model-as) should be visible on human models, as seen in the first screenshot available for it in-game. When I was Draenei, I could see the cape skin properly on my character, but since I swapped my race to human, I cannot see the cape, it only appears as an [invisible mesh with some grey things 'floating'](https://imgur.com/a/nWyVcCq). My only option seems to be to transmog it to some similar appearance such as the [Crimson Paragon's Cover](https://www.wowhead.com/item=34190/crimson-paragons-cover), which does not have the same identical model, but which does show up on wow-mania.

I know this cape problem does not apply only to Royal Crimson Cloak, and many probably noticed it while doing the Culling of Stratholme instance which transforms you into a human. I am also using the latest WoW-Mania launcher version 2.3.8 and have tried clearing my cache.

Is there any way to make these cape skins show up? Or will I have to transmog it to something else?

Thank you

**Comment by TenmanWoW** [comment]
I'll look at this on Dev when it comes up.

**Comment by TenmanWoW** [comment]
I destroyed the item and gave it to myself again, and it still appears as mesh.

**Comment by wow-mania** [comment]
As is. this is a wotlk item so it looks as in retails. We also have all bugs that retail had.
