### ISSUE TITLE
[Quest] Rescue OOX-09/HL!

### ISSUE THREAD

**Issue by Druhl** [WoWManiaUK/Redemption#2728]
[https://www.wowhead.com/quest=836/rescue-oox-09-hl](https://www.wowhead.com/quest=836/rescue-oox-09-hl)

What is supposed to be quest-ending spawn of (I believe) 3 mobs produced hundreds or thousands. Screenshots attached (one right after char death, one after returning and rezzing).

![wowscrnshot_091318_104527](https://user-images.githubusercontent.com/19803911/45507371-f1204480-b75f-11e8-8b00-a12238572727.jpg)
![wowscrnshot_091318_104630](https://user-images.githubusercontent.com/19803911/45507374-f3829e80-b75f-11e8-9fe6-64700ffa1590.jpg)

**Comment by TenmanWoW** [comment]
Quest worked fine for me, both horde and alliance.

![wowscrnshot_091318_150527](https://user-images.githubusercontent.com/25806987/45512829-8e7e7700-b766-11e8-81e3-d00e62a0f1bb.jpg)
![wowscrnshot_091318_150145](https://user-images.githubusercontent.com/25806987/45512830-8e7e7700-b766-11e8-8a11-b3527155140e.jpg)
![wowscrnshot_091318_150140](https://user-images.githubusercontent.com/25806987/45512831-8e7e7700-b766-11e8-8e96-2e88897a2c93.jpg)
![wowscrnshot_091318_144459](https://user-images.githubusercontent.com/25806987/45512832-8e7e7700-b766-11e8-8d70-8efa45ca84c8.jpg)

**Comment by Druhl** [comment]
I just ran it on a Horde alt and it seemed to run normally this time for me as well.

Maybe my experience up top was just a one-off.
