### ISSUE TITLE
[Reputation] Worgen Character doesnt get reputation on Cenarion

### ISSUE THREAD

**Issue by Sheae** [WoWManiaUK/Redemption#2729]
I wrote an ingame ticket and got asked to write it down here.
On my worgen druid Character Sheae i dont get the credit for the reputation of Cenarion Circle and Cenarion Expedition.
I killed mobs like https://www.wowhead.com/npc=11881/twilight-geolord and finished Quests like https://www.wowhead.com/quest=8318/secret-communication and got the text that i received reputation, but it doesnt actually work. 

-  using the newest launcher
-  cleared my cache
-  double-checked that the Rep. is not set to inactive
-  reproduced it in different weeks

Can this be fixed?
Or is it possible to change my race into Nightelf so i can farm the reputation?

Thanks for you time and help

**Comment by TenmanWoW** [comment]
![image](https://user-images.githubusercontent.com/25806987/45530187-0c667080-b7af-11e8-8b57-b9f9dd2b97a7.png)

**Comment by TenmanWoW** [comment]
Sheae, 

  Can you post a screenshot of your reputation screen? I've tested the same quest you listed in your ticket and it worked fine. I am thinking it may be an overlooked aspect, like you moved the rep to inactive.

**Comment by Sheae** [comment]
Cenarion Circle:
![cenarion1](https://user-images.githubusercontent.com/43255386/45539322-ab1fbb00-b809-11e8-853f-0e1d49c21801.jpg)
![cenarion2](https://user-images.githubusercontent.com/43255386/45539323-ab1fbb00-b809-11e8-9a33-b4b6dc3c8882.jpg)

Name and ID should be the ones i posted, not sure though.
8318
secret communication

Cenarion Expedition:
![cenarion3](https://user-images.githubusercontent.com/43255386/45540945-ff2c9e80-b80d-11e8-92e8-50cb639454f8.jpg)

9724
warning the cenarion circle

**Comment by Sheae** [comment]
I did the same quests on my other character, a Gnome, and he got the Reputation.

Its sad that i farmed a couple thousands of Reputation before i noticed it doesnt show up

**Comment by Sheae** [comment]
No, this is my first WoW-Character ever and she was born a Worgen.

I am not sure if i ever got the "you are now neutral/friendly with Cenarion Circle" message.
I did some Anh Qiraj runs, did some Quests and killed many of the Twilight Cultists down there.

Is it possible to check it ingame? I will be online the next hour.

**Comment by wow-mania** [comment]
Your rep is currently at 5678. So it is adding up.

**Comment by Sheae** [comment]
Ok nice, good to know it is working. So i guess i'll just keep going without the visual feedback?

**Comment by wow-mania** [comment]
I will try to find out why you it's not showing for you.

**Comment by wow-mania** [comment]
OK I have reproduced the issue.
You need to open a ticket and ask for a GM to flag you for race change twice.
Change to Night Elf and then change back to Worgen.
This will fix the issue.
