### ISSUE TITLE
[Spell] Flame Shock

### ISSUE THREAD

**Issue by Ashamedlol** [WoWManiaUK/Redemption#2730]
Same issue as #2726 and #2718 and #2708 

Some talents are double dipping the flame shock into dealing more damage than intended:

Talents: Concussion: http://wow-mania.com/armory/?search=%09+Concussion#talents (without Concussion Blow)

Storm, Earth and Fire: http://wow-mania.com/armory/?search=Storm%2C+Earth+and+Fire

Talent is double dipping from being increased:

Flat value:
![fs](https://user-images.githubusercontent.com/16576459/45544413-e75e1600-b81f-11e8-9e1a-2abb77174700.png)

5% increase from Concussion: 

![fs2](https://user-images.githubusercontent.com/16576459/45544504-2a1fee00-b820-11e8-9b1d-d7557c6cbc5e.png)

increased to 364, then I refresh the flame shock and it goes to 374.

****  Value of Storm, Earth and Fire in comment below.

**Comment by Ashamedlol** [comment]
![senf](https://user-images.githubusercontent.com/16576459/45545808-09f22e00-b824-11e8-9cca-2a3a4a08ab46.png)

**Comment by Dranah** [comment]
Does this affect any other shaman spell but flame shock?
If not, the issue title should be Flame shock, as it is the DOT formula that is bugged in the core.

**Comment by Ashamedlol** [comment]
Oh but it's doing fine damage until scaled with those, I'll investigate other spells when I have time since I was investigating rogue and found same DoT issues such as garrote/deadly poison double dipping from talents.

**Comment by Dranah** [comment]
yes, all dots have a common calculation mistake towards %damage mods 
it won't appear if there are no mods, but its still the dot formula itself
