### ISSUE TITLE
[Spell] Garrote

### ISSUE THREAD

**Issue by Ashamedlol** [WoWManiaUK/Redemption#2731]
The talents Blood Splatter, Find Weakness and Opportunity are double dipping (or extra dipping) Garrote's damage:

Blood Splatter: 149 -> 193 -> 205
Pre-Value:
![gar](https://user-images.githubusercontent.com/16576459/45563496-36bf3900-b856-11e8-8b48-7e920a7e9ef4.png)

Post-Talent Value:
![gar2](https://user-images.githubusercontent.com/16576459/45563518-40e13780-b856-11e8-8b84-e7cf029699ed.png)

Post-Talent Re-applied Value:
![gar3](https://user-images.githubusercontent.com/16576459/45563526-4b9bcc80-b856-11e8-9b98-aed909caa67e.png)

Find Weakness:
All values described above are in one screenshot on this talent: 161 default, 170 with 6% amplifier, 172 after re-applying.

![weakness](https://user-images.githubusercontent.com/16576459/45563821-307d8c80-b857-11e8-9a4d-eb1a8ca7fcee.png)

Opportunity: 
Default (161) -> Spec (193) -> Re-applied (202)
![oppor](https://user-images.githubusercontent.com/16576459/45563858-4f7c1e80-b857-11e8-881f-9213dde1b3ef.png)

Rupture worked fine, no double dips happend to me.

Talent links: http://wow-mania.com/armory/?search=Blood+Spatter#talents (Blood Splatter)
http://wow-mania.com/armory/?search=Find+Weakness (Find Weakness)
http://wow-mania.com/armory/?search=Opportunity#talents (Opportunity)

Rupture: http://wow-mania.com/armory/?search=Rupture#abilities

**Comment by Keader** [comment]
please, stop.
All double DOT is same issue, so why open new issues? z.z

**Comment by Dranah** [comment]
I'll mark all threads that are linked by this problem with this shiny new label so we can find them later (after janitor ninjacloses all as I expect)

**Comment by Ashamedlol** [comment]
It's to inform you which abilities combined with talents are bugged Keader, some of them work fine :D.

**Comment by Ashamedlol** [comment]
Glyph of Garrote also if it was missed:
![glyph](https://user-images.githubusercontent.com/16576459/45592905-987cc180-b982-11e8-9f8c-ec3e8f36c8f5.png)

http://wow-mania.com/armory/?item=42964
