### ISSUE TITLE
[Spell] Improved Devouring Plague

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#2733]
Imp. Devouring Plague (IDP) spell ID 63675

_EDIT: Only the instant portion has problems now._

Improved Devouring Plague is not a fix value calculated from DP as it should be.
**Expected behavior** is that IDP is a flat 30% of whatever total damage DP calculates to do on the current target when it is cast. This effect then takes no further modifications from buffs, debuffs etc.
It has the ability to crit.
**How it works**: IDP seems to be independent from DP damage calculating itself as a separate spell. This grants the spell the ability to benefit from (double-dip) %damage mod debuffs on target such as Curse of the Elements, Icehowl's Staggered Daze or XT's Exposed Heart. It gives the spell an unfair DPS in certain encounters (icehowl, XT, etc) and makes it generally stronger as well.
In certain situation it makes the spell weaker, as it double dips also damage reduction effects on the target, like in pvp an enemy popping a def cooldown.

Example:
IDP does 4 times higher damage on XT's heart or Icehowl when he's stunned instead of 2 times higher.
IDP does 99% reduced damage against hostile shadow priests that are dispersed instead of 90% reduction.

**Comment by Dranah** [comment]
UPDATE:
Devouring Plague now calculates damage properly with modifiers after latest update (except for the additive stacking that is reported elsewhere)

Remaining problem is Improved Devouring Plague's ability to double dip debuff boosts that make it extremely powerful in certain circumstances.

**Comment by Keader** [comment]
Test if is fixed

**Comment by Dranah** [comment]
Nope. DP still double dips debuffs.

**Comment by Dranah** [comment]
Works good now, IDP no longer double dips debuffs. It always matches 30% of total disease damage calculated in moment of cast.
