### ISSUE TITLE
[Spell] Crypt Fever and Ebon Plague

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#2734]
http://www.wow-mania.com/armory/?spell=49632
http://www.wow-mania.com/armory/?spell=51735

How it should work:
On WOTLK, the 30% effect is an increase to "disease damage taken" by target, unspecified whether those diseases are cast by the same caster or somebody else.
This means it should affect damage of Frost Fever, Blood Plague and Devouring Plague done by anyone in the raid, not only by the caster death knight.
On cataclysm it was changed to "increase damage taken by **your** diseases on target", which would affect only the DK's own diseases.

How it works atm:
The 30% disease damage taken portion of the debuffs apply only to the caster DK's own Frost Fever and Blood Plague, it does not boost damage of other DKs or shadow priests DP.

**Comment by Keader** [comment]
How you tested it?
Working fine to me in ptr with 2 characters in group.

**Comment by Dranah** [comment]
Oddly, it appears to work on Red now as well. It did not when I tested on PTR. Oh well.
