### ISSUE TITLE
[Spell] Corruption and Shadow Word: Pain rolling SP

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#2735]
ID 47813 - corruption
ID 25368 - SWP

Warlocks' corruption (and shadow priests SWP) ability has a "rolling" behavior, which means certain stats are only checked when you manually recast the buff and keep rolling with the spell as long as it is refreshed via Everlasting Affliction (or Pain and Suffering, for priests). This includes %crit and %damage buffs.
Stats that are not rolling are checked also when the DOT is refreshed via Everlasting Affliction/Pain and Suffering (such as haste buffs, spell power), or already on the next tick (any debuff effects).

How it should work:
Spell power is not supposed to be rolling, Corruption/SWP must check your spell power value every time its refreshed. This means if you receive a spell power proc while corruption/SWP is ticking, it will notice the spell power buff on the next refresh by Everlasting Affliction/Pain And Suffering and last until the spell is refreshed without the proc.
Example:
>Cast corruption
>Corruption ticks for 1352
>Get 861 SP proc
>Corruption ticks for 1352
>Refresh Corruption via Everlasting Affliction
>Corruption ticks for 1850
>Lose 861 SP proc
>Corruption ticks for 1850
>Refresh Corruption via Everlasting Affliction
>Corruption ticks for 1352

How it works atm:
Spell power right now is rolling just like crit and spell damage, so the spell only checks for your SP value only when you manually cast it. This means if you receive a SP proc, it won't begin automatically affecting your corruption/SWP when your Everlasting Affliction/Pain and Suffering refreshes it. However if you recast Corruption/SWP with SP procs active, you can forever keep "rolling" those effects via Everlasting Affliction/Pain and Suffering, since it never rechecks the value.
Example:
>Cast corruption
>Corruption ticks for 1352
>Get 861 SP proc
>Corruption ticks for 1352
>Refresh Corruption via Everlasting affliction
>Corruption ticks for 1352
>Recast Corruption
>Corruption ticks for 1850
>Lose 861 SP proc
>Corruption ticks for 1850
>Refresh Corruption via Everlasting affliction
>Corruption ticks for 1850

some more detailed read:
https://www.wowhead.com/forums&topic=162195

EDIT: Shadow word pain shows exact same behavior, instead of just rolling %crit and %damage, it also rolls spell power.

**Comment by squalllh1989** [comment]
confirmed, those problem make warlock's dps be insance as corruption's dps gotten crazy with all proc at the start of the fight then keep refresh all the time through the fight -> warlock's dps became insance.
