### ISSUE TITLE
[Dungeon] "You are not in this instance group" 

### ISSUE THREAD

**Issue by Thrashattack** [WoWManiaUK/Redemption#2736]
An issue with Dungeons is kicking everybody from the instance group, but not from the party group. 

Sometimes (it seems to be randomically), in the middle of a Random Dungeon Finder dungeon it happens and the players can teleport out/in and the bug will be gone. 

Today i faced this issue in a POS HC run, but the problem was that we didn't joined by RHC. 
Once the bug happened, and we lost the instance group, the dungeon had been reseted. 

![image](https://user-images.githubusercontent.com/23486776/45593105-44ef8100-b94c-11e8-8319-3587ff8409f2.png)

In the screen capture you can check the frame advertising us about the instance group and at the same time, the party group is up.

**Comment by Dranah** [comment]
If I noticed well, it's 5:59 in the morning on your screenshot.
6:00 is the time for daily instance reset, any players inside a dungeon at this point are kicked out with a 1minute timer and the instance is reset.
If this happens to you at any other time of the day, that would be odd, but the 6am reset is completely normal.

**Comment by wow-mania** [comment]
Good catch. :)
