### ISSUE TITLE
[Quest] Mutiny on the Mercy

### ISSUE THREAD

**Issue by GM-Kratos** [WoWManiaUK/Redemption#2737]
The Quest [Mutiny on the Mercy](http://wow-mania.com/armory/?quest=11527) is unable to be done since the [Mutinous Sea Dog](http://wow-mania.com/armory/?npc=25026) are not located on the ship.
![image](https://user-images.githubusercontent.com/43315225/45596387-7eaba080-b9bb-11e8-85fc-624d45d7b170.png)

How it should work: [Mutinous Sea Dog](http://wow-mania.com/armory/?npc=25026)'s should be down in the deck of the ship so that you can kill them and loot the [Barrel of Blasting Powder](http://wow-mania.com/armory/?item=34387) but since the NPC are not there you cannot get the quest item and therefore not complete the quest.
https://www.youtube.com/watch?v=uOkySkZfWFQ

**Comment by TheManiax** [comment]
https://github.com/WoWManiaUK/Redemption/issues/2596#issuecomment-405455791

**Comment by wow-mania** [comment]
Check previous report on this issue.
