### ISSUE TITLE
[Core] Passive %Damage and %healing mod talents stacking additively

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#2738]
This issue affects all talents that grant a **passive** increase to a damaging or healing ability's damage or healing, and it affects every spell of every class/spec that has multiple passive %damage or %healing modifying talents.

How it should work:
Generally in the game %damage and %healing mod effects are all meant to be stacking multiplicative, regardless of being a passive increase, an active buff/proc or ability on-use.
This works as intended for **active** buffs/procs/on-use effects as far as my testing goes.

Problem:
Currently all **passive** %damage and %healing increase talents are stacking additive when boosting any spell or ability, when they should be all multiplicative.
This means that if a spell has a talent that boosts its damage/healing by 10% and another that gives 20% boost, instead of 1,1 x 1,2 = 32% total increase, it only gets a 1,1 + 1,2 = 30% boost to its effect.
This problem makes everything generally weaker, it just hasn't been much of a trouble so far as most abilities still did higher damage than intended due to wrong scaling, double dipping etc, but as those bugs are getting fixed, it becomes important to fix also this problem.

Example:
Shadow priests gain 10% passive shadow damage from talent "Darkness" and also 10% Shadow damage from Shadow Weaving, which is an active buff that the priest keeps stacked up. As Shadow Weaving stacks multiplicative with other modifiers, these two effects will add a total of 1,1 x 1,1 = 21% boost to all shadow damage spells.
However, when stacking "Darkness" 10% shadow damage boost with "Twin Disciplines" 5% damage increase towards instant spells, you will find that these two effects (both passive) are stacking additive and only grant a 15% total increase instead of 1,1 x 1,05 = 15,5%

Example2:
Holy priests gain 15% passive increase to Renew's healing from talent "Improved Renew" and also 10% passive increase to all healing done via talent "Spiritual Healing". These two effects should grant a total of 1,15 x 1,1 =26,5% increase to Renew's healing, however they only grant 25%.

While this may not look like a lot of difference at first, it all adds up 
...literally, instead of multiplying

EDIT: stacking behavior of talents which grant extra %stats %manacost and %threat are under investigation

**Comment by crulinjr** [comment]
This is related to the Mortal Shots + Marked for death talents stacking additively aswell

**Comment by Dranah** [comment]
Nope, it isn't. Those talents add critical strike damage bonuses, and those are meant to be additive. This thread is about talents that give X % damage done or healing done to a spell (or spells).

**Comment by crulinjr** [comment]
oh ok ok

**Comment by Thrashattack** [comment]
### How it should work 

- dmg [shadow, holy, ...] 

- Darkness x5 (+10% shadow damage) 

• at this point the talent script should make something like (shadow_dmg += shadow_dmg*0,1)
and register it

-  Twin Disciplines (+5% damage to instant spells (DoT's) 

• at this point the talent script should iterate the dmg[] for all instant spells and increase it current damage  in 5% (if shadow, the damage was already increased by 10%) 
and register it again. 

### How it is working now 

The register is being made in a global way

when you spend the point to - Darkness x5 (+10% shadow damage) and save the damage increases in 10% and ok. 
But if you spend more 5 in  Twin Disciplines (+5% damage to instant spells (DoT's)  and save again, the register will be updated by : 
                   - If the spell is shadow school and instant increases it damage by 15% (0,15 = 0,1(Darkness) 
                     + 0,05(Twin Disciplines) 
That is the wrong approach. 

I know that maybe it doesnt only depends of a single function for each class but this was the more close i could be to a technical speech with ingame analysis.

**Comment by Thrashattack** [comment]
about the numbers 

How should be: 

Initial damage: SW:P : 230 

SW:P + Darkness : 253 (230 + 10%(25,3))
SW:P + Twin Disciplines : 266 (253 + 5%(12,65))


How it is: 

Initial Damage SW:P : 230 
SW:P + Darkness : 253 (230 +10%) 
SW:P + Twin Disciplines : 264 ( 230 (??) + 15% (??) )

**Comment by Keader** [comment]
Closing it for now, until Ariel back to TC to do it.
