### ISSUE TITLE
[Spell] Wandering Plague

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#2739]
ID 49655

How it should work:
This ability is technically an "aoe crit", that is supposed to hit for the same amount as the DOT tick that procs it, but on every nearby target. It should take no boosts or modifiers from buffs or debuffs, but be a fixed 100% of the DOT tick damage.

Problem is that the spell is not a fixed 100% damage of the DOT tick atm. It can benefit from debuff effects such as the DK's own Ebon Plague 13% magic damage, or XT's Exposed heart, Icehowl's staggered Daze etc.
This makes it generally a bit stronger than intended, and extremely powerful in certain encounters (like XT or northrend beasts), but also proportionally weaker when used against a target who has damage reduction buffs active.

**Comment by Dranah** [comment]
No change.

**Comment by Dranah** [comment]
Still nope.

**Comment by Keader** [comment]
Test now Dranah.

**Comment by Dranah** [comment]
Wandering Plague now deals an exact copy of the disease damage that proc'd it.
