### ISSUE TITLE
[Mount] Jade Pandaren Kite Issue

### ISSUE THREAD

**Issue by Hurrz** [WoWManiaUK/Redemption#2740]
Hi,

I bought the new mount "Jade Pandaren Kite" and immediately noticed that the mount is not working properly. When I fly it straight ahead it wiggles unnaturally fast, which is not pleasant to the eye. When strafing sideways it actually goes smoothly, as I assume it should. 

Kind regards from a long time player,
Hurrz

**Comment by Hurrz** [comment]
Will players be reimbursed for the 300 MP spent?

**Comment by wow-mania** [comment]
I have given authorization for GM to unlearn the spell for the player and refund the MPs
