### ISSUE TITLE
[Spell] Death Grip

### ISSUE THREAD

**Issue by bluemonstrr** [WoWManiaUK/Redemption#2750]
Spell ID: 51399

How it's supposed to work; The spell pulls the target towards the caster _**from it's current position**_ , forcing them to attack the caster for 3 seconds

How it's currently working; When inside an instance (& possibly outside) the spell will pull the target from it's original position/spawn point.

This can be recreated by pulling trash in RS to the other side of the instance, then death gripping and it will pull from it's original position.

**Comment by TenmanWoW** [comment]
Tested this in RS against multiple mobs. Unable to reproduce.
![wowscrnshot_092218_235059](https://user-images.githubusercontent.com/25806987/45924303-7e7f3980-bec2-11e8-9267-eaaef6582ac6.jpg)
![wowscrnshot_092218_235002](https://user-images.githubusercontent.com/25806987/45924304-7e7f3980-bec2-11e8-8e3c-a36544f73f8d.jpg)
![wowscrnshot_092218_234954](https://user-images.githubusercontent.com/25806987/45924305-7e7f3980-bec2-11e8-814f-ab552bcf072e.jpg)

**Comment by TenmanWoW** [comment]
![wowscrnshot_092318_000011](https://user-images.githubusercontent.com/25806987/45924360-dcf8e780-bec3-11e8-8a69-a0e44c963bae.jpg)
![wowscrnshot_092318_000020](https://user-images.githubusercontent.com/25806987/45924362-de2a1480-bec3-11e8-97ce-6a088b193e34.jpg)

**Comment by bluemonstrr** [comment]
I tried to recreate it as well, but it appears it's been fixed in the last core update.

**Comment by TenmanWoW** [comment]
It appears this issue isn't isolated to RS however it only happens after kiting the mob a great distance. 

![wowscrnshot_092318_000828](https://user-images.githubusercontent.com/25806987/45924399-e9ca0b00-bec4-11e8-8ab2-e171ff580961.jpg)
![wowscrnshot_092318_000827](https://user-images.githubusercontent.com/25806987/45924400-ea62a180-bec4-11e8-8ef5-da66d1d7cdfd.jpg)
![wowscrnshot_092318_000825](https://user-images.githubusercontent.com/25806987/45924401-ea62a180-bec4-11e8-8c74-99e9c030a059.jpg)
![wowscrnshot_092318_000822](https://user-images.githubusercontent.com/25806987/45924402-ea62a180-bec4-11e8-8bff-3dfbd70279e4.jpg)
