### ISSUE TITLE
[Pet] Imp mana regen

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#2751]
https://www.wowhead.com/spell=688/summon-imp

How it should work: 
- The imp has a small mana pool but an intense native mana regen that applies even while he's casting.
- This means the imp is very difficult to run out of mana, as over a 2sec Firebolt he spends 180 mana at level 80 and regens back most of it before the next cast.
Here are some videos showing the imp regen mana while casting, completely unbuffed with no other source of mana regen: 
https://www.youtube.com/watch?v=ClP2iBVqvi0
https://www.youtube.com/watch?v=IMoYxz3avF0
- Based on some retail discussions, (source: https://www.mmo-champion.com/threads/634375-Does-the-imp-run-out-of-mana) a completely unbuffed, unsupported imp takes a fair 4minutes of non stop combat to run out of mana, but if he has a single replenishment effect in the raid, or a Blessing of Wisdom, he will essentially stay at full mana all the time
- If you do manage to run the imp out of mana (only documented cases are boss abilities such as KT's mana bomb draining it) the imp is rendered useless, he does not ever melee the target. He waits for his mana to regen and spam Firebolts again.

How it works atm:
- The imp's native mana regen does not apply while the imp is casting. He takes the same 5sec waiting penalty and only then he begins regen, just like players.
- This means the imp is running oom extremely quick with its small mana pool, as the Destruction tree (which is designed for imp, that supposedly has endless mana) has no specific talent that would keep up a pet's mana.
- No, improved soul leech cannot do it, it doesn't regen by far enough and it's a generic replenishment talent anyway - and a really expensive one at 5 talent points - that nobody is supposed to take unless their raid leader forces him to supply replenish
- This means destruction is only viable for short-span dungeon fights, in any regular raid encounter the imp's mana simply doesn't even last til halfway
- The imp is capable of meleeing, which leads to him dying to some melee aoe for most of the time, after he ran out of mana and went in melee range. But also it can increase his dps output sometimes, because he tucks in melee swings between firebolts

**Comment by Dranah** [comment]
The imp can now regen mana while casting.
He still runs to melee when oom or silenced.

**Comment by Keader** [comment]
Try now.

**Comment by Dranah** [comment]
The imp will no longer melee when it's unable to cast.
