### ISSUE TITLE
[Dungeon]: Utgarde Pinnacle

### ISSUE THREAD

**Issue by Drostthehunter** [WoWManiaUK/Redemption#2753]
As soon as you enter the dungeon and keep following the path, after you kill the 1st group of mobs including the abomination, it will automaticly open the gates leading to the last boss which are supposed to be open after you slain the last boss, this way you can skip whole instance and finish random heroic dungeon very fast :D

**Comment by wow-mania** [comment]
Which door exactly are you talking about? Can you send me the name of the object or the id.
Screenshots will also help.

**Comment by Drostthehunter** [comment]
I just got in a pug run, i saw the doors are opened late so i couldnt take screenshots, those are the doors separating Final boss room from the hallway as soon as you entered the dungeon, unfortunately dont have screenshots nor object id.

**Comment by Dranah** [comment]
https://imgur.com/WrjRLDu
This one I believe?
