### ISSUE TITLE
Patch 2.4.0 Discipline Priest nerf

### ISSUE THREAD

**Issue by GordyA** [WoWManiaUK/Redemption#2755]
Hi, I've been advised by Kratos (GM) to log a ticket here.
Since patch 2.4.0 I've noticed a significant (20%-25%) drop in healing throughput. My talents are still the same. 
Previously my renew ticked over for around 2100 now it's down to 1630, greater heals are also affected, previously, greater heal crits averaged around 17k and are now more like 13k/14k.
When I spoke to Kratos he mentioned that this is the first he'd heard of this so I can assume that this is not intentional and is a by-product of the changes to fix the double-dipping issue but is itself not a double-dipping issue. It may also be related to another post here which indicates that multipliers are not working correctly.
Can someone investigate this please as this massive nerf completely breaks this class.

**Comment by wow-mania** [comment]
This is not an issue. Please read wiki on how to post an issue.

**Comment by Dranah** [comment]
Here is the math behind current healing:

Renew has a base healing of 280/tick (1400 total) at level 80, this receives a 37,6% sp coefficient per tick.
With a test value of 2858 spell power, this means 1071 bonus healing per tick, 1351/tick total before talents. (matches tests)
With Improved Renew, Twin disciples and Focused power, this increases to 1676/tick for a disci.
(There is an ongoing argument in another thread, whether the talents should stack multiplicative and that would increase to 1696/tick but you see this is a very small difference)

Before the core fix, the 3 talents above affected the spell power bonus (that 1071) twice, making it 1993/tick healing before buffs/debuffs. This was not intended and is now fixed.

The "fall" in healing done after fix scales with your spell power, so while in my test (2,5k sp) the difference is roughly 15%, for a bis priest with full raid buffing, it can match your 20-25% difference.
Then again, the spell is now doing correct healing. It used to do too much. (Same issue as warlocks corruption)
