### ISSUE TITLE
[Hunter] Armor pen does not affect Aimed Shot

### ISSUE THREAD

**Issue by crulinjr** [WoWManiaUK/Redemption#2756]
Currently, Here is the Issue I believe I have identified:
1) ArP does not affect Aimed shot Crits. There is an error in the calculation of armor's damage reduction for Aimed Shot Crits.

Currently the damage done by my aimed shot HITS with any level of ArP are  more or less what i should expect to observe. However, the difference from what we should expect from our Aimed Shot Crits is about 1K dmg. 

See the images I provided in the proof section. for the data to back this up.

Expected behaviour: Tell us what should happen instead

before I do the aimed shot math, lets start with armor/ArP:

**DR%** = Armor / (Armor + 15,232.5)
**Effective Armor(post ArP)**= Armor-(ArP x Cap)
**Cap**= (10643+(400+85 x 83+4.5 x 85*(83-59)))/3 = 9092.66

merging it all together:
**DR%** = (10643-ArP x 9092.66)/((10643-ArP x 9092.66)+15232.5)

Now,
if you have 0% ArP, bosses armor (10643) would reduce your damage by
10643/(10643+15232.5) = 41.11316%
this means that when you run the calculation to see what damage you do, you must multiply your pre armor damage by (1-41.11316%) = 58.8864%

**Aimed shot damage SHOULD be:**

HITS:
(12% from barrage, 5% from ranged weapon spec)
(avg char sheet damage + 456.5) x 1.12 x 1.05 x (1-DR%)
expanding out the armor portion of the equation:

CRITS:
(100% from base crit dmg bonus, 30% from mortal shots, 10% from marked for death, plus the above multipliers)
(avg char sheet damage + 456.5) x 1.12 x 1.05 x 2 x 1.3 x 1.1 x (1-DR%)

This is the results i got:

		
![image](https://user-images.githubusercontent.com/40045543/46051748-73b1e800-c100-11e8-98f6-b04d0c8c8a75.png)

				

Steps to reproduce the problem:

calculate expected damage for aimed shot
go to boss target dummy, use aimed shot a bunch to get a sample
compare
Include proofs for this behaviour

pages used to get the formulas,etc for armor/ArP
http://wowwiki.wikia.com/wiki/Damage_reduction
http://wowwiki.wikia.com/wiki/Armor_penetration

As you can see the difference from the expected damage compared to the actual damage Aimed shot Crits does is about 1k since Hunters crit a lot this is a mayor dps loss.

**Comment by Ashamedlol** [comment]
Dummy is not a reliable testing source when it comes to Armor Penetration, look at what I had when I put on scale+dbw with one aimed, then removed on second as well as one crit without, one with:
![arp](https://user-images.githubusercontent.com/16576459/46058521-2cf5d980-c164-11e8-86c5-70941f842c0d.png)

Please try it on level 80 NPCs and check your results.

**Comment by crulinjr** [comment]
If you notice, your Aimed Shot Crits are doing less damage than they
should. Maybe its not something about ArP scaling but an issue with the
Crits variables but If your Aimed Shot hits are doing 2700-3200 dmg your
crit should be doing 7722-9152 dmg

**Comment by Ashamedlol** [comment]
You're miscalculating things, don't forget ranged weapon specialization is already taken into account while calculating your weapon damage and is 3%, not 5%.
Crits have a way higher range of min-max damage than normal hits, but how should a 3200 do 9k crit?
Lets say I did 3200, my aimed shot average will be 7680 with calcs (mine did 8k in the screenshot), and can go below and above that based on weapon damage min/max.

They're doing fine damage for me, please test on normal mobs and tell me your results :p

**Comment by Ashamedlol** [comment]
It's 3200 * 2.4 (2 + .4 + .1)
And yeah, seemed specialization was wrong on my tooltip.

**Comment by crulinjr** [comment]
Have done some research and the crit multipliers stack multiplicatively not
additively. Same goes to the 3% meta gems increased damage. It should go
like this: X is hit damage.

x*2*1.03=x*2.06=x*206% Thats how it works. Since Mortal shots and Marked
for Death are separate talents they should stack multiplicatively.

**Comment by Ashamedlol** [comment]
Care to share the research source? Because in this case, most classes have wrong crit modification by what you're saying as well as all the hunter spells benefited by those 2 spells.

**Comment by Dranah** [comment]
None of you are fully wrong, but neither fully right. Let me clear this up.

Bonuses to your critical damage bonus stack **multiplicative** with your native critical damage bonus, but **additive** with each other.
(Total critical damage) = (Base ability damage) + (Total critical damage bonus)
(Total critical damage bonus) = (Base critical damage bonus) x (1+ talent bonus + talent bonus)
For casters, the base crit damage bonus is 50%, for melee/hunter/DK spells it is 100%.
Glyph bonuses work the same way as talent bonuses.
The Meta gem is a special snowflake as it's not a crit damage bonus-bonus but a raw multiplier to crit damages, stacking multiplicative with everything, and is applied before everything. 
Meta damage calculates from the total crit damage before the bonuses are applied and then scales up with those bonuses.
EJ on meta gem mechanism: http://web.archive.org/web/20130209181158/http://elitistjerks.com/f47/t37804-warrior_fury_compendium/#Impale

For a hunter, the calculation looks like this.
No meta, no talents:
100% + 100% = 200% total crit damage
Without meta, with talents:
100% + (100% x 140%) = 240% (like Ashamed says)
With meta, no talents:
(100% + 100% ) x 103% = 206% (like crulin says)
With meta, with talents:
100% + (106% x 140% )= 248,4% 
The meta calculates its 3% off the 200% base critical damage, which is 6% and is considered a damage bonus itself, so it scales up with the talent bonuses.

So with a 3200 non crit, the expected crit damage is 3200 x 2,484 = 7948 damage
Matches both your test numbers.

PS: calculating with armor reduction or damage increases from ranged spec talent is completely pointless, those talents apply to the both equally and does not anyhow affect the conversion from hit >crit
The only other stat that affects crit/hit ratio is resilience on enemy players as it has an extra reduction for critical strikes
