### ISSUE TITLE
Brewfest bug

### ISSUE THREAD

**Issue by festerhowl** [WoWManiaUK/Redemption#2760]
Ram master Ray isn't offering 2 brewfest tokens for delivering every barrel of "portable brewfest keg". Brewfest is almost over and i need more tokens for the title :C

**Comment by wow-mania** [comment]
Unless you tell us the exact quest and NPC we can't do anything about it.
Please read the wiki on how to post an issue.

**Comment by wow-mania** [comment]
As far as I can see after testing. This seems to be as-is. Some players will get it once, some twice and some 3 times depending if all the conditions are met at the time and position of the delivery.
You still get the reward for the quest completed as normal.

**Comment by Echinaceax** [comment]
Its the additional work part after completing the `There and Back Again` quest
will be fixed here as it is still bugged 
https://github.com/WoWManiaUK/Redemption/issues/3600
