### ISSUE TITLE
[Mount] Solar Spirehawk

### ISSUE THREAD

**Issue by TheManiax** [WoWManiaUK/Redemption#2761]
https://www.wowhead.com/item=116771/solar-spirehawk
How it should look:
https://wow.zamimg.com/uploads/screenshots/normal/456045-solar-spirehawk-ruhkmar-mount-solar-spirehawk-front-view.jpg
How it looks:
https://cdn.discordapp.com/attachments/360499662160920586/494595042669756416/WoWScrnShot_092618_214027.jpg

------
@wow-mania  Can the real graphic be imported or is it already the best we can get?

Players check the wowhead pic and buy the mount and then they get upset. If not fixable, any chance to remove or refund?

**Comment by wow-mania** [comment]
Mounts do not always translate well. The client is much older than the one it was designed for and not all effects can be applied.

**Comment by TheManiax** [comment]
If not fixable, any chance to remove the mount or refund the players?

**Comment by svijetlonosa** [comment]
it is also smaller then it should be 
so if it can not look as it is suppose to , try to make it be proper size

**Comment by wow-mania** [comment]
I will change the size.
