### ISSUE TITLE
quest bug

### ISSUE THREAD

**Issue by Sekula1993** [WoWManiaUK/Redemption#2762]
i cannot complete quest  [Seek Out Neltharaku], first quest work den wen i got next quest i cannot fiend end
this is list of quest

1. | Kindness
-- | --
Seek Out Neltharaku
Neltharaku's Tale
Infiltrating Dragonmaw Fortress
To Netherwing Ledge!
The Force of Neltharaku
Karynaku
Zuluhed the Whacked
Ally of the Netherwing

**Comment by wow-mania** [comment]
Unless you give the exact info of why it doesn't work and how it should work we cannot do anything.
Please read the wiki on how to long an issue.

**Comment by TheManiax** [comment]
Neltharaku is not easy to find.
Keep searching.
It works.

**Comment by wow-mania** [comment]
It does a closed loop in the entire region and you won't see him without the goggles.
