### ISSUE TITLE
Purchased the wrong heirloom?

### ISSUE THREAD

**Issue by Hype13371** [WoWManiaUK/Redemption#2763]
Well, when i purchased the wrong heirloom, i couldn't get my maniac points back. And i spend 125 Maniac points on stuff i can't even use. Normaly you can sell it back to the Vendor for a full refound..

**Comment by wow-mania** [comment]
Not a server issue.

**Comment by wow-mania** [comment]
This is a player mistake. You can ask a GM but it is not a server issue and it does not belong here. Sorry.
