### ISSUE TITLE
PvP flagging

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#2766]
This has been an issue for a while but after a petty quarrel over people getting ganked in front of ICC now I decided to report.
There are several problems with PvP flag not working as intended.

How it should work:
- You should only get PVP flagged if you 1. turn it on, 2. engage in combat with a player from opposite faction, 3. Healing or buffing a friendly player that is PVP flagged (indirect engage of pvp)
- If you are flagged by an action, (and is not turned on permanently), it should begin a 5minute timer after leaving combat that will turn off your flag unless you are engaged in PVP combat again

How it works atm:
On top of the above listed, you can get flagged by the following actions: 
- Healing or buffing help NPCs in a raid (which should have no pvp status)
- Getting mind controlled by a boss and being forced to cast on your team mates
- Getting hit by or casting anything on somebody else that is mind controlled

Furthermore, ANY actions done while you are pvp flagged (casting any spell, drinking a potion, getting an automatic proc, reflecting damage to a simple mob) will all refresh your pvp flag and not allow it to turn off.

**Comment by wow-mania** [comment]
If any NPC is PvP and you attack, heal or interact in any way, mind controlled or not you will get flagged. That is just the way it is at the moment.
So from your 3 examples give me the NPC name. I will try to reproduce.
The last comment is as-is. Any actions that prolong your life, health or increase your dps while flagged will reset your flag.

**Comment by Dranah** [comment]
Why would helper NPCs inside a raid or dungeon be PvP? There is no sense to get flagged in a PVE fight while doing PVE. 
It happens on any fight where you have NPCs that can benefit from your aoe effects such as chain heals, like on Razorscale or Hodir.
Mind control fights are for example Kel'thuzad, Lady Deathwhisper, Yogg-saron. Being Mind controlled in a PVE instance doing a PVE fight is again not pvp combat, it's not meant to flag you.

The last sentence essentially means you have to sit down for 5minutes and not do anything at all. That's just not intended. You can't carry on questing or farming because you'll be forever flagged. Why is it as-is? If it can't be fixed that's okay, but otherwise i just don't understand.

**Comment by wow-mania** [comment]
Send me the NPC id and I will check. Yes, that does not make sense.

**Comment by Dranah** [comment]
This affects at least 20 different npcs across all kind of dungeon and raid fights. I can try to make a list but it'll be long. Is it not possible to just set all npcs inside a raid instance to pvp-off?

**Comment by wow-mania** [comment]
I just need one.

**Comment by wow-mania** [comment]
Can someone confirm this? I tried all sorts of way and NPCs did not enable pvp for me.
Maybe something else is causing this.

**Comment by TheManiax** [comment]
Didn't get me to combat by healing the Expedition Defender in Razorscale
![image](https://user-images.githubusercontent.com/14857593/47226035-5bb24900-d3cc-11e8-9b0d-bd7fb2daa3bf.png)
Something else is affecting the test
I tested solo

**Comment by Dranah** [comment]
Lol, I can see on your screenshot that you are PVP flagged, your name appears in green and you have the Horde icon on your portrait. If you leave the dungeon you will be attackable by enemy players, you can try it with an alliance toon.
It does not set your PVP to enabled on the portrait, that only changes if you set it to enabled yourself.

**Comment by Keader** [comment]
I made impossible get pvp inside of dungeons (you dont need it anyway)

**Comment by Dranah** [comment]
Seems to work, interacting with the npcs no longer flags you, unless you enter the dungeon already with PVP flag.
