### ISSUE TITLE
Pets retaining ICC buff when zoning out

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#2769]
This affects all permanent pets (any warlock demons, DK ghouls, hunter beasts, water elemental etc) that stick around with you when you leave the instance.
They don't lose their buff of Strength of Wrynn/Hellscream's Warsong respectively, not even when you relog, respect or manually dismiss and resummon. Apparently not even if they die.
Needless to say this can make pets extremely powerful outside the instance where they aren't meant to have the buff.

**Comment by Keader** [comment]
waiting your confirmation :)

**Comment by Dranah** [comment]
Pets now properly lose aura if they aren't inside ICC.
