### ISSUE TITLE
[Gear] Conqueror's Scourgestalker Battlegear Set from Mall vendor

### ISSUE THREAD

**Issue by crulinjr** [WoWManiaUK/Redemption#2771]
So i bought the Conqueror's Scourgestalker Battlegear set from the mall vendor. Before i could buy them i got the message that i should check on the internet so im sure thats the gear ill be getting. So i checked the internet and found this:

https://www.icy-veins.com/wow/conquerors-scourgestalker-battlegear-hunter-transmog-pve-tier-8-5-set
 
(https://www.icy-veins.com/wow/valorous-scourgestalker-battlegear-hunter-transmog-pve-tier-8-set)

So after i bought it and test it on me using Shift-click i found out the gear is red instead of blue.
So the valorous scourgestalker battlegear is the red one; however, i  bought and expected the conqueror one since its the one offered.  The icons from the gear you get are from the Valorous set and not the Conqueror one and ill put screenshots comparing. 

![wowscrnshot_100218_082224](https://user-images.githubusercontent.com/40045543/46356728-eeab5f00-c628-11e8-8d94-ef813b4de082.jpg)
![wowscrnshot_100218_082415](https://user-images.githubusercontent.com/40045543/46356831-29ad9280-c629-11e8-907a-57be7df5cbf6.jpg)

**Comment by wow-mania** [comment]
This is a wotlk set and has not modification whatsoever.
As-is.

**Comment by crulinjr** [comment]
Well then ill need a refund because im not getting what i bought.
