### ISSUE TITLE
Players not Recieving PvP Tokens.

### ISSUE THREAD

**Issue by GM-Kratos** [WoWManiaUK/Redemption#2773]
After the recent patch (2.4.0) several tickets have been raised and messages about players not getting [PvP Tokens](http://wow-mania.com/armory/?item=37711) after losing Battle Grounds or Wintergrasp.

All the players I have spoken to use the Launcher with the latest patch (2.4.0) and all get the same message of "You don't have enough bag space"

I have got the same issue myself on my play char

![no_pvp_tokens_again_2](https://user-images.githubusercontent.com/43315225/46369597-b8e79400-c683-11e8-8517-4ef9d4120b5d.jpg)
This is a screenshot by one of the players of the issue.

I don't know how to reproduce this or what is causing the problem.

**Comment by GM-Gathios** [comment]
Could the: "You don't have any space in your bags." error message have something to do with it?

**Comment by GM-Kratos** [comment]
@GM-Gathios That is the message everyone has got including me got after, so my guess is that it has to do something with it. But as I said, I have no idea.

**Comment by wow-mania** [comment]
Tokens require place in bag.
There is no way some will get and some will not. Unless this is reproducible we won't be doing anything about it.

**Comment by GM-Gathios** [comment]
Tried to reproduce by making my bags full and add a token to my inventory. It worked but I'm not sure if adding a item to the inventory works the same way.

**Comment by GM-Kratos** [comment]
When myself got this issue I had plenty of bag space left over.
And PvP Token is a currency, isn't it?

**Comment by GM-Gathios** [comment]
Yes it's a currency. The source of this issue could be bag-related. We have to sort it out

**Comment by GM-Kratos** [comment]
This seems to ONLY occure to some of the players that lose BattleGrounds (Specific and Random) and to those that lose Wintergrasp.

**Comment by Dranah** [comment]
i can confirm, winners get their tokens, losers dont

**Comment by TheManiax** [comment]
@wow-mania 
PvP Token doesn't require bag space.
It goes to Currency tab.
The issue is real. But needs more info to reproduce.

**Comment by wow-mania** [comment]
How many is the winner getting?

**Comment by wow-mania** [comment]
I found the issue. This was happening only on randoms and not on pugs.
Fixed for next update.

**Comment by GmSaintz** [comment]
I can confirm that it was happening to the losing team in specific battlegrounds (Arathi Basin, and Warsong Gulch) yesterday evening. The winners were getting 3 PvP tokens, as they should have.
