### ISSUE TITLE
[Spell] Twilight Shift

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#2774]
ID 57874

This is the aura applied by drakes in Obsidian Sanctum when you take a portal and get shifted to twilight.
It is supposed to reduce your damage by 25% and tick for 1000-1100 damage per sec.

Problem: spell currently does roughly 4 times the intended damage, 4000-4400 per tick on every player inside. It is unhealable for a non-overgeared party.

**Comment by GMWeeble** [comment]
Says 1018 to 1182 Dmg and I am taking this much [damage](https://gyazo.com/367f01f7e8b19579bca90936096ecf71)

**Comment by Keader** [comment]
Test now

**Comment by Dranah** [comment]
Damage is now in the correct range.
