### ISSUE TITLE
[NPC] Ice Steppe Rhino

### ISSUE THREAD

**Issue by TenmanWoW** [WoWManiaUK/Redemption#2778]
NPC 29469

How it should work:  Basic mechanic. The mob in question is considered neutral but will aggro if directly attacked or a player attacks the pack it is with. 

Issue: Upon attacking any member of the pack (Bull or Rhino) the entire pack aggros. Casting Ice Nova to freeze them all in  place, followed by a blink to gain distance will result in just the Ice Steppe Bull to continue chasing the player. The Ice Steppe Rhino(s) will remain aggroed on the player but will not engage from the point they were frozen at by Ice Nova.

Steps to reproduce:  Around Engine of the Makers in Storm Peaks is where this issue was encountered. Attacking any member of a pack with a spell (Did not try melee as I'm on a mage), cast Ice Nova to freeze them in place, blink away, and when Ice Nova ends, Rhinos just stand there until either killed or ran away from.
 
![wowscrnshot_100418_221242](https://user-images.githubusercontent.com/25806987/46514498-e1a68f80-c823-11e8-9cee-c888cb073ae2.jpg)

![wowscrnshot_100418_222406](https://user-images.githubusercontent.com/25806987/46514572-46fa8080-c824-11e8-9966-aab382ad8a8a.jpg)

**Comment by wow-mania** [comment]
AS-Is.
