### ISSUE TITLE
[Raid] Trial of the Grand Crusade's PvP Fight

### ISSUE THREAD

**Issue by Ashamedlol** [WoWManiaUK/Redemption#2781]
This is only on Heroic Version of Trial of the Crusade:
Issues: A) 
How it's working: Pets of the Warlock/Hunter are set on Passive, they only attack if you go near them, you can ignore them for the rest of the fight until a person goes close to those 2 classes.  Issue is shared with normal version I believe.

How it should work: They should be automatically aggressive and attack just like the champions on pull.

B) 
How it should work: All the Champions should have a PvP Trinket (http://www.wow-mania.com/armory/?spell=42292) at a 5 minute cooldown, so when they are CCed once they will remove it with that spell then have 5 minutes cooldown on that ability.

C) 
How it's currently working: You can taunt any champion, no matter what.
How it should work: Champions should be immune to taunt.

D) 
How it's currently working: Scatter Shot and Blind are being removed within 3 seconds without touching the person Blinded or Scatter Shotted (Not even related to PvP Trinket). Issue is shared with normal version I believe.
EDIT: Only happens in 25HC for me, to reproduce: Blind the target and then go next to him if you're the aggro target, he will break free from the blind unless you're far away from him.

How it should work: Remains full duration until damaged by 1 ability or attack.

 **Uncertain about**:
E) 
How it's currently working: You can disarm the champions, they will do some reduced damage but still cast spells that require a weapon to use, specifically the hunter champion (Shoots with bow while disarmed, casts explosive shot etc).

Source: https://wow.gamepedia.com/Faction_Champions
There may be few more issues but this is what I could find for now.

**Comment by Ashamedlol** [comment]
F) 
How it's currently working: Retaliation of the Warrior is just a visual spell.
How it should work: Retaliation should deal physical damage back to the physical attacker of the warrior for 20 attacks.

**Comment by wow-mania** [comment]
Champions are only immune to charm. 
We need someone else to confirm the other issues and find some references.

**Comment by Ashamedlol** [comment]
ONLY in heroic they are immune, you can see that from the video and the tactic explanation link, can't have better sources than that :D.

**Comment by Keader** [comment]
k, fixed to heroic diffs

**Comment by Ashamedlol** [comment]
Taunt is fixed, pets are still bugged and blind is still bugged. 

PvP Trinkets aren't added yet to HC version.

**Comment by Ashamedlol** [comment]
Aggro isn't reseting anymore based on proximity threat nor time, needs adjustment.

**Comment by Keader** [comment]
Blind is a deep core issue, sometimes happens with polymorph too, we cant find why.
I put a new check, so even if they lost blind, they will not melee attack.

**Comment by Keader** [comment]
test now.

**Comment by Ashamedlol** [comment]
Pets work, PvP Trinket added.
