### ISSUE TITLE
[NPC] Swarm Scarab

### ISSUE THREAD

**Issue by Ashamedlol** [WoWManiaUK/Redemption#2782]
How it works: Determination isn't causing the Swarm Scarab adds to be immune to Stuns or Judgement of Justice, the buff isn't healing them back to full HP.

How it should work: Under that buff (Determination), they are immune to Stuns and Judgement of Justice. And once they get buffed up their HP should refresh back to full.

Spell ID: http://www.wow-mania.com/armory/?spell=66092 / http://www.wow-mania.com/armory/?spell=66147

NPC ID: http://www.wow-mania.com/armory/?npc=34605

**Comment by wow-mania** [comment]
Should be fixed on next restart.

**Comment by Ashamedlol** [comment]
Restart up yet? Still not fixed.

**Comment by wow-mania** [comment]
Give me 5min

**Comment by Ashamedlol** [comment]
Now immune to stuns.
