### ISSUE TITLE
[QUEST] Supplies to Private Thorsen

### ISSUE THREAD

**Issue by GM-Gathios** [WoWManiaUK/Redemption#2783]
http://wow-mania.com/armory/?quest=198

For this quest you'll have to bring (http://wow-mania.com/armory/?item=2252) to Private Thorsen (http://wow-mania.com/armory/?npc=738). This item is obtained when accepting the quest and marks the quest as 'complete'.

The issue:
Private Thorsen does not have a question mark. This quest can't be turned in.
Tested in on Redemption

**Comment by GM-Gathios** [comment]
Closed, after reset NPC works properly, should have tried that earlier 👎

**Comment by Luthanos** [comment]
I had the same problem as well, what do you mean by reset? reset the quest? the game? the computer? Please more info

**Comment by Echinaceax** [comment]
i was asked to check this today for Janitor
when he starts his patrol he is busy, therefor he cannot be disturbed. https://github.com/WoWManiaUK/Redemption/issues/4175#issuecomment-2335609969
