### ISSUE TITLE
[Boss] Valithria Dreamwalker

### ISSUE THREAD

**Issue by NiX005** [WoWManiaUK/Redemption#2784]
During this fight if you are a Priest and target Dreamwalker and cast Prayer of Healing it heals the entire raid including the boss instead of only a 5man group of the raid, very noticeable on 25mans.

**Comment by Ashamedlol** [comment]
May as well check Blazing Skeleton's HP (25HC HP lower than 10HC HP).

**Comment by Dranah** [comment]
No change.
Btw this is probably a side effect of that on Valithria fight she is considered to be in party with everyone so that she can be affected by beneficial spells that are only usable on group members.
Perhaps it can be changed so she is considered a raid member but not a party member, so she doesn't link the entire raid?

**Comment by Keader** [comment]
I tested in my server and was working fine
I will check if I forgot to send something

**Comment by Dranah** [comment]
Blazing skeletons have 83k health on 10man normal and 250k on 25man normal.
350k on 10hc and 125k on 25 hc
To me it appears that the 10hc and 25hc health values are switched. It would make sense 83 > 125k on 10man mode and 250 > 350 on 25man.

**Comment by Dranah** [comment]
UPDATE:
- Prayer of Healing cast on a raid member will properly heal the party members of that raid member and won't heal valithria (fixed)
- Prayer of Healing cast on Vali won't heal the raid (fixed)
- Some spells that can only affect party members (non raid wide) will no longer affect vali
- Spells that can affect any raid member will still always jump between Vali and players
- Switched health values of 10hc and 25hc Blazing Skeletons, so now both difficulties have the intended. Other mobs health looks to be in order.
