### ISSUE TITLE
[NPC] Ancient Conservator

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#2786]
https://www.wowhead.com/npc=33203/ancient-conservator

This is one of Freya's adds.
There are problems with his spell timers, which make him a lot harder than intended.

1) Spells instantly cast when add spawns
When the add pops up, the entire raid is instantly afflicted by Conservator's grip https://www.wowhead.com/spell=62532 and Nature's fury https://www.wowhead.com/spell=63571/natures-fury is up ticking already in exact same moment as well. 
**How it should work:** When the add pops up, only the mushrooms must begin spawning at the same moment. Neither Nature's fury, nor Conservator's grip should be cast for about 6-8seconds.
You can see this on tankspot video : https://www.youtube.com/watch?v=mc2ZOf3CkKA
When the Conservator spawns, everyone is still comfortably casting and attacking. The tank can pick up the add, and there is proper amount of time for everyone to hide in a mushroom before the aura kicks in.
Here, the tank is already pacified before the add becomes targetable and you can only pray there is a shroom close enough in reach to get out a taunt before he kills a healer.

2) Conservator's grip is a permanent aura
Here the silence aura is not only cast instantly as the add spawns, it is also instantly reapplied if you remove it with a mushroom and then leave the mushroom's safety.
**How it should work:** 
Wowwiki describes it as "He **periodically** uses Conservator's Grip to silence and pacify all members of the raid"
Based on the tooltip on wowhead, it is clear that the spell should have a 2sec hidden casttime so it shouldn't be possible to apply more than every 2seconds, but it's probably much less frequent than that. 
Possibly it runs on a similar 6-8sec cooldown as Nature's fury though i could not find exact data for this.
You can see on retail videos that people have no trouble running from a despawning mushroom to another without getting the silence back in their faces, that shows at least 3seconds of time between the aura being reapplied.

**Comment by Dranah** [comment]
I understand this is no priority, but it's neither a nuance, especially on full hard mode. You are capable of wiping within 3seconds with a bad RNG of mushroom spawn positions because the tank won't be able to pick up the add (and the person with nature's fury will go down sooner than anyone can heal him)

**Comment by Keader** [comment]
Sniffs info:

```
19:44:37.178 - Created
19:44:37.989 - start summon Healthy Spore
19:44:38.005 - start cast 62532 (Conservator's Grip)
19:44:43.184 - start cast 62589 (Nature's Fury)

[0] Slot: 43
[0] Spell ID: 62532 (Conservator's Grip)
[0] Flags: 129 (EffectIndex0, Negative)
[0] Level: 81
[0] Charges: 0
[0] Caster GUID: Full: 0xF13081B30000A131 Type: Creature Entry: 33203 (Ancient Conservator) Low: 41265


[0] Slot: 44
[0] Spell ID: 62589 (Nature's Fury)
[0] Flags: 161 (EffectIndex0, Duration, Negative)
[0] Level: 81
[0] Charges: 0
[0] Caster GUID: Full: 0xF13081B30000A131 Type: Creature Entry: 33203 (Ancient Conservator) Low: 41265
[0] Max Duration: 10000
[0] Duration: 10000
```

Without Max Duration and Duration means: Infinity.
So 2. Is invalid, wiki is wrong.
But... it should has cast time of 5 sec

About 1. is fixed in my server.
Idk why, but i cant access ftp of wow mania right now.
So will pass to PTR when i back of uni

**Comment by Dranah** [comment]
You misunderstood point 2). The problem is not that the spell has no duration, it indeed does not, you need to use the shrooms to dispel it.
The problem is (most likely) the frequency of it being reapplied. 
Here, when you dispel the aura with a shroom, after your shroom despawns and no longer protects you, you instantly get the debuff again, while on retail videos you can clearly see people keep casting and then move over to another shroom easily before the effect is reapplied. That's atleast 3-4seconds.
What I think is that since it has no cast time (bug) and is also not on the GCD (this is intended) the boss is just eternally spamming it, therefore creating an "infinite" aura.
Wiki is not wrong, he should cast it "periodically", not spam it non stop. The fact that once the debuff is applied, it has infinite duration is a whole different story, it just sets the need to use the shrooms to dispel it.
Btw giving it a 5sec cast time would probably solve both issues, because that prevents the spell being cast more often than 5seconds in any case.
I don't think it could be interrupted in a regular way, as the casttime is most likely hidden, but possibly he should not be able to cast it while moving. Need to do more research on that.

**Comment by Dranah** [comment]
UPDATE:
- Conservator's grip now properly has a 5second cast time when the add spawns. (fixed)
- Nature's fury also won't be cast sooner than he finishes applying the grip, so the first cast now occurs roughly 6seconds after add spawns. (fixed)
- Conservator's grip cast is visible to players (this can't be fixed), but uninterruptible by spells or movement. (fixed)
