### ISSUE TITLE
[Spell] Improved Devouring Plague can't crit

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#2787]
http://www.wow-mania.com/armory/?spell=63627

Similar issue to what happened to Hunter's chimera-serpent, the spell lost its ability to crit.
Proof that it should be capable of crit: http://www.worldoflogs.com/reports/rt-dut3y9l0xiriwo5d/details/2/?s=5023&e=5278

**Comment by Keader** [comment]
I forgot to set shadow school haha
I think that now is working.

**Comment by Dranah** [comment]
The spell is now able to crit.
Just like chimera-serpent, these crits are wrongly displayed as regular hits on logs/recount, but they do proper damage. This cannot be helped atm.
