### ISSUE TITLE
[Boss] Trial of The Crusade's Icehowl

### ISSUE THREAD

**Issue by Ashamedlol** [WoWManiaUK/Redemption#2788]
Massive Crash IDs: http://www.wow-mania.com/armory/?search=Massive+Crash

How Massive Crash currently works: You are stunned for 6 seconds, Icehowl starts to charge at you and you're still stunned while he's stampeeding towards you, but charges at mediocore speed.

How Massive Crash should work: You are stunned for 5 seconds, Icehowl emotes glaring at a target and then jumps to begin stampeeding towards the zone of that target at FAST speed.

Proof: https://youtu.be/LyKvaBFImcY?t=360

**Comment by Keader** [comment]
He will start with medium speed and will increase after 1 sec.
And charge delayed in 2 sec
