### ISSUE TITLE
[Trial of the Grand Crusader] - Boss Timing / Habilits Targets

### ISSUE THREAD

**Issue by Thrashattack** [WoWManiaUK/Redemption#2789]
The Beasts Of Northrend are with bad behaviours in ToC HC mode. 

## How should work 
1st: The first 2 bosses have a battle time. 
The Twin Worms shall enter the arena 2.5 minutes (according to dbm database and retail videos) after Gormok be engaged, even if gormok isnt dead, the worms shall enter. 

This first DPS race is essential to know if your party ll be able to finish the raid, since in HC mode there are few ice spheres for Anub'arak. If you don't have enought DPS you ll face 2 sumerges phase wich is 99% of chance to wipe due to this fight mechanic. 
The same timing occur for Ice Howl , he needs to enter the arena 5 minutes after the twin worms be engaged. 

2nd: Ice howl should be the only one of the three beasts to bersek, since he is the last one. 
After 5 minutes he isn't entering in berserker state. Frosthing Rage keeps up for 30s if not tranquilized but he never berserk. 

3rd: Acid Bite / Acid Split 

Acid Bite : Should only the main tank or the rangeds be target of this habilit. 
Acid Split: Acidmaw shall always face the tank (High aggro player) and split in his direction 

## How it is working 

1st: You can take 1 hour to kill each of the beasts. The twins won't enter the arena unless Gormok are dead. Same with Icehowl. 

2nd: You can take 1 hour to kill Icehowl, he will never berserk. 

3rd: Acid Bite is affecting to melee players behind the boss in 10yd away of the tank. This shouldn't happen. First Acid Bite is always on main tank or rangeds. 
Acid Split: Acidmaw is turning his head away from the tank during the split phase causing near melee players to be affected by Paralytic Toxin.  

Tests was conduced today in PTR  

Proof Videos: 
• https://www.youtube.com/watch?reload=9&v=feno0x6bTsE (Retail) 
• https://www.youtube.com/watch?v=GoRyBjGBDFo (Retail)

**Comment by wow-mania** [comment]
Do not confirm your own issues, please.

**Comment by Keader** [comment]
This issue is real, but idk if we can handle with it xD
I fixed it and rewrited northrend beasts for TC.
Idk if can be ported to wow mania.
i will try in next days.

**Comment by Thrashattack** [comment]
Is possible to make something like a scheduled event for each one ? 



        struct boss_gormokAI : public BossAI
        {
            boss_gormokAI(Creature* creature) : BossAI(creature, BOSS_BEASTS) { }

            void Reset() override
            {
                events.ScheduleEvent(EVENT_IMPALE, Seconds(8), Seconds(10));
                events.ScheduleEvent(EVENT_STAGGERING_STOMP, Seconds(15));
                events.ScheduleEvent(EVENT_THROW, Seconds(15), Seconds(30));
                ### event start twin worms
                summons.DespawnAll();
            }

About the spray and the bite it seems to be random after all 

             case EVENT_SPRAY:
                    if (Unit* target = SelectTarget(SELECT_TARGET_RANDOM, 0, 0.0f, true))
                        DoCast(target, SpraySpell);
                    events.ScheduleEvent(EVENT_SPRAY, urand(15*IN_MILLISECONDS, 30*IN_MILLISECONDS), 0, PHASE_STATIONARY);
                    return;

**Comment by Thrashattack** [comment]
New found: Icehowl is reseting with full party alive after first breath. Trying to get why.

**Comment by Thrashattack** [comment]
If you tank icehowl at the gate (Security reasons because of stomp) , he will not breath and consider you "Not in line sight" (Based in the fact that i had "Target is not in line sight" when i tryied to hit him being on the gate), after this he will reset. Only for TOGC 10 untill now.

**Comment by Keader** [comment]
Hello.
Cant be fixed at this point.
To port my Northrend Beast and timers, i need use all boss scripts of TC on mania, because it is a lot of work and i will not do it again ._. (3 weeks working 10h+ per day).
So... in january i should finish to rewrite toc bosses (i did already: northrend beasts, jaraxus all announcer events). When i finish rewrite, i put all scripts together here.
Until there, instance can be done with a little wrong timers xD
