### ISSUE TITLE
[Spell] Fear Ward

### ISSUE THREAD

**Issue by Anthonhed** [WoWManiaUK/Redemption#2793]
The spell [Fear Ward](http://wow-mania.com/armory/?spell=6346) doesn't remove the Fear effect of Blood Queen Lana'thel's Fear before Air Phase 
(BQ Fear Spell http://wow-mania.com/armory/?spell=73070) 

I don't know if it is the same for other Fear spells.

**Comment by Keader** [comment]
@Dranah can you confirm it?
I found a diff issue about that.
Is working fine to me testing with 2 players in duel.
But... fear ward is not consumed and it should.

**Comment by squalllh1989** [comment]
I can confirm this, currently the priest's fear ward work on some spell and doesn't work on some, example of work is the fear from General Zarithrian in Ruby Sanctum (work properly, consume when render you immune to fear), example of not working is the fear from Blood Queen Lana'thel (not make you imune to fear, not consume), not sure what is the different from those those.

**Comment by Keader** [comment]
Fixed and tested by @Dranah.
Plus, fixed some spells not proccing it and wrong procs (like with smite o.o)

**Comment by Dranah** [comment]
Fear ward now properly protects you from BQL's Incite Terror.
Most likely it always did, simply the spell got removed by some damaging ability before the fear kicked in. Non-fear type of effects mistakenly consuming Fear ward are now fixed.
