### ISSUE TITLE
Halaa Battle tokens

### ISSUE THREAD

**Issue by Midgetmage** [WoWManiaUK/Redemption#2794]
Hello;
the Problem is that in Halaa (Nagrand) the bombs that should damage the guards are bugged they dont take damage.
And if you wanna get the Halaa Battle tokens you cant get them you only get the Honor for killing enemys near Halaa, and we tried it on ally and Horde and neither of us got them 
Note: we tried it with Halaa in horde control and ally controlled

**Comment by Lucie93** [comment]
Lemme add some info...
You should get [battle token](https://www.wowhead.com/item=26045/halaa-battle-token#created-by-spell) from opening [tower tokens](https://www.wowhead.com/spell=33005/nagrand-tower-token-alliance-1) which you should get by killing players of opposite faction around your lvl.

You can stack (10) of mentioned [bombs](https://www.wowhead.com/item=24538/fire-bomb) from using Wyvern Roost (which you can find in camps around Halaa while it's controled by other faction).
It will automatically mount you and you can drop bombs on enemy guards.

**Comment by Lucie93** [comment]
After test on PTR I can confirm. Bombs don't deal dmg to guards and you recieve no token for killing players.

![wowscrnshot_101318_194304](https://user-images.githubusercontent.com/43965184/46908262-cf61db00-cf20-11e8-865c-9b33df3c622c.jpg)

**Comment by WhitephoenixTheBunny** [comment]
Just adding one more info:
This issue were fixed previously, somehow broke again.

#2564

**Comment by WhitephoenixTheBunny** [comment]
![image](https://user-images.githubusercontent.com/31921098/46908311-00d6a880-cf19-11e8-873c-698f12d79c21.png)
And my side after killing Lucie

**Comment by wow-mania** [comment]
Just tested on dev and bombs are doing damage.

**Comment by WhitephoenixTheBunny** [comment]
We will re-test it.
And about the tokens?

**Comment by wow-mania** [comment]
I will check the tokens next.
Can you explain how it is working and how it should work, please?
Who drops the token? Rival players?

**Comment by Lucie93** [comment]
Yes i mentioned it above even with links.
You will get Nagrand tower token from killing players of opposite faction. If you use it, it will create battle token.
But at this point it gave us only honor.

**Comment by Lucie93** [comment]
Also i'm gonna check the bombs again cause me and Phoenix tried it manualy (click bomb, click ground) yesterday on both ptr and redemption and it didn't hurt the guards at all. They had full HP.

**Comment by wow-mania** [comment]
Everything works on dev
![image](https://user-images.githubusercontent.com/12248683/46940759-6635b100-d061-11e8-9aac-3b528bfbdf91.png)
This is after killing a player.

![image](https://user-images.githubusercontent.com/12248683/46940891-b6ad0e80-d061-11e8-8136-bbc562ce904c.png)
This is after the bomb. 1% per second. Not enough to kill any guard.

Make sure you have PVP enabled.

If you have any question let me know and I will show you.
