### ISSUE TITLE
[Quest] Unholy Infusion

### ISSUE THREAD

**Issue by TheManiax** [WoWManiaUK/Redemption#2795]
[[Unholy Infusion]](https://www.wowhead.com/quest=24749/unholy-infusion)
**How it should work:**
This quest may only be completed in **25 person** difficulty of Icecrown Citadel.
**How it work:**
This quest can be completed in any difficulty of Icecrown Citadel.

**Comment by squalllh1989** [comment]
Hope this time's fix won't get bugged again like last time :|

**Comment by Billas1** [comment]
On January 27 2019 US time. I did the unholy infusion quest. I had shadow's edge equipped and did the infusion. We then killed PP and the quest did not complete. I was watching the timer and still had about 15 or so seconds left on infusion before it expired. There were multiple witnesses in the raid that seen it and all told me to put in a ticket/report.
