### ISSUE TITLE
[Faction / Reputation] Sons of Hodir

### ISSUE THREAD

**Issue by WhitephoenixTheBunny** [WoWManiaUK/Redemption#2798]
How it should work:

Grinding [Sons of Hodir](http://www.wow-mania.com/armory/?faction=1119) reputation should follow this quest sequence:
- [They Took Our Men](http://www.wow-mania.com/armory/?quest=12843)! – Questline;
- [The Last of Her Kind](http://www.wow-mania.com/armory/?quest=12983) – Questline;
- [The Refiner's Fire](http://www.wow-mania.com/armory/?quest=12922) – Questline from drop item;
- [Forging an Alliance](http://www.wow-mania.com/armory/?quest=12924) – Questline:
- [Loken's Lackeys](http://www.wow-mania.com/armory/?quest=13035) and [The Earthen Oath](http://www.wow-mania.com/armory/?quest=13005);
- [The Reckoning](http://www.wow-mania.com/armory/?quest=13047);
- [Whatever it Takes!](http://www.wow-mania.com/armory/?quest=13108) and [Diametrically Opposed](http://www.wow-mania.com/armory/?quest=13109).

How it is working:
At moment the drop item “[Slag Covered Metal](http://www.wow-mania.com/armory/?item=41556)” giving the quest “[The Refiner's Fire](http://www.wow-mania.com/armory/?quest=12922)” don’t need any requirement to be looted.
The item should have as requirement to be looted / started: have the quest “[Mending Fences](http://www.wow-mania.com/armory/?quest=12915)” complete – this is the last quest from previous questline.

Making that quest BEFORE starting the “They Took Our Men!” will make the player unphase on several quests.

**Comment by Lucie93** [comment]
Confirm ^^

**Comment by WhitephoenixTheBunny** [comment]
![image](https://user-images.githubusercontent.com/31921098/47011211-3b1e9080-d139-11e8-9a93-c26f7dd3a233.png)
The item only drops after the quest now ^^
