### ISSUE TITLE
[Quest] The Sun King's Command

### ISSUE THREAD

**Issue by GM-Kratos** [WoWManiaUK/Redemption#2799]
The quest [The Sun King's Command](http://wow-mania.com/armory/?quest=9695) does not have a quest giver and cannot be picked up.

There is no info on the Armory who the quest giver should be, I checked [WoWHead](https://www.wowhead.com/quest=9695/the-sun-kings-command#screenshots) as well but no info there either.

This quest is the start for a long quest line required for the Achievement [Loremaster Kalimdor](http://wow-mania.com/armory/?achievement=1678)

When I try to manually try to add the quest (.q add 9695) I get the message "Quest 9695 not found."
![image](https://user-images.githubusercontent.com/43315225/46970027-2cdc6000-d0b8-11e8-8be1-b2a090745891.png)
First line: .lo q The Sun King's Command
Second line: .q add 9695

**Comment by WhitephoenixTheBunny** [comment]
https://wow.gamepedia.com/The_Sun_King%27s_Command

This what i find, the item was removed

**Comment by WhitephoenixTheBunny** [comment]
The next quest can be added

**Comment by wow-mania** [comment]
The quest has been deprecated.
To make things simpler I have added to Vindicator Boros to start it and finish it.

**Comment by WhitephoenixTheBunny** [comment]
As I already have said the item [The Sun King's Command](https://wow.gamepedia.com/The_Sun_King%27s_Command) was removed. 

The quest [The Sun King's Command](http://wow-mania.com/armory/?quest=9695) do not exist anymore, but the questline yes, that quest were replaced by [Intercepting the Message](http://wow-mania.com/armory/?quest=9779)

**Comment by WhitephoenixTheBunny** [comment]
You can remove that "fix" @wow-mania 
the quest still there...

**Comment by wow-mania** [comment]
Excellent so it is not an issue at all. The quest is fully deprecated and replaced.
