### ISSUE TITLE
[Spell] Master's Call

### ISSUE THREAD

**Issue by Ashamedlol** [WoWManiaUK/Redemption#2800]
When both player and pet are snared (Roots, Frost Nova etc), The pet will break free but not the owner:

![mastercall](https://user-images.githubusercontent.com/16576459/47015035-a164dc80-d154-11e8-9273-b331b62eb6c6.png)

As you see, the roots from a druid are immediately removed on the pet after I press Master's Call, but my roots are still up.
 If only one of them is rooted: it works properly.

Spell ID: http://www.wow-mania.com/armory/?spell=53271

**Comment by Keader** [comment]
Not caused by distance?

**Comment by Ashamedlol** [comment]
Did it next to pet, same result.

**Comment by Ashamedlol** [comment]
Only works when I'm on top of pet, from how I see it this is how it's working currently: If pet is rooted, pet will cleanse himself and not rush into hunter nor give him a buff.
But if hunter is rooted, pet will rush into hunter and give both the buff.

**Comment by Keader** [comment]
Fixed.
Test in dev now @Ashamedlol

**Comment by Keader** [comment]
confirmed with Ashamedlol in ptr now.
