### ISSUE TITLE
[Spell] Heart of the Phoenix

### ISSUE THREAD

**Issue by Ashamedlol** [WoWManiaUK/Redemption#2801]
When cast while pet is alive, it goes on CD and leaves a debuff on pet and ends up being a loss of a CD (Shouldn't be castable while pet is alive, and revives pet when pet dies).

Spell/talent ID: http://www.wow-mania.com/armory/?spell=55709

**Comment by Thrashattack** [comment]
The Spell works. 
You need to cast Hearth Of Phoenix after you pet die not before. 
But in retail, Hearth Of Phoenix can be configured to automatic cast when pet dies, by activating the spell on the spellbook/pet bar. Here on mania isn't possible.

**Comment by Ashamedlol** [comment]
The spell works when pet is dead indeed, and the automatic cast of the spell was glitchy on retail too, you had to do it through macro.

But the bug here is that it can go on CD without met requirements.

**Comment by Keader** [comment]
Fixed.

**Comment by Keader** [comment]
Now it will not enter in CD if pet is alive, or if pet still has debuff aura.
And will send a error message to player :)
