### ISSUE TITLE
[Spell/Talent] Judgements replenishment not working correctly 

### ISSUE THREAD

**Issue by Aristo14** [WoWManiaUK/Redemption#2803]
When in raid the replenishment was quite low, soon we noticed the pally judgements arent really replenishing what they should. 

**How its should work**

http://www.wow-mania.com/armory/?spell=31878
The paladins should get 25% mana regained immediatly when a judgement is casted. 

In the following example this means an instant 25% of 6049 = 1512,25

**How it works**

After judgement is cast a mana regen of  1098 is logged 
 (1098 = 18.15% of 6049)

![wowscrnshot_101618_233338](https://user-images.githubusercontent.com/38132718/47049800-a9e20500-d19e-11e8-8c46-056882978468.jpg)

More testing is needed to see if this is a spell or talent issue and if it applies to all judgements. Also the effect of this on the raidwide replenishment should be tested more.

**Comment by Hajzlopuc** [comment]
...immediately grant you 25% of your **base** mana. 
Base mana for paladin level 80 is 4394, 
4394*0.25=1098.5. 
Where's the problem?

**Comment by Aristo14** [comment]
You are right, this is something I overlooked. 

However I did notice sometimes not even getting any replenish during the raid. It was mostly noticed by our healers who suddenly had mana issues on bosses they usually can spam away. Will look into how to reproduce but on some bosses all seemed fine and on others it was random.
