### ISSUE TITLE
[Boss] Twin Emperors - Ahn'Qiraj

### ISSUE THREAD

**Issue by Thrashattack** [WoWManiaUK/Redemption#2804]
### How it is working 
The spell Twin Teleport is casted only by one of the emperors what will cause they to heal with Heal Brother . 

### How Should Work 
Every 30–40 seconds, the two twins will switch places

**Comment by Thrashattack** [comment]
• Veknilash Casts 
https://www.wowdb.com/npcs/15275-emperor-veknilash#related:casts  

• Veklor Casts 
https://www.wowdb.com/npcs/15276-emperor-veklor#related:casts

**Comment by Thrashattack** [comment]
Note: Heal Brother is know in mania db:
http://www.wow-mania.com/armory/?spell=7393 
But i don't found twin teleport.

**Comment by wow-mania** [comment]
As far as I can see both are doing exactly the same. Will need confirmation on dev.
Which one is not teleporting?

**Comment by TheManiax** [comment]
Both are doing the same as you said
But the encounter is so broken, it's not only about the teleport spell imo
Needs more investigation and info

**Comment by TheManiax** [comment]
@wow-mania  They are not teleporting at the same time.
The teleport timer is between 30 and 40 second, but whatever it is, they should do it together.
This causes the encounter to get weird, Because they act different way when near or far from each other.

**Comment by wow-mania** [comment]
Please re-try after restart.

**Comment by wow-mania** [comment]
Recheck please. If it is worse like this I will revert to previous.

**Comment by TheManiax** [comment]
It's worse now, revert it please
And you need to make the big eye in middle invisible
it's visible atm

**Comment by wow-mania** [comment]
Reverted to the previous fix. Will stay as-is.
