### ISSUE TITLE
[Spell] - Trap Maestry

### ISSUE THREAD

**Issue by Thrashattack** [WoWManiaUK/Redemption#2808]
### How it is working 
The number of snakes is the same as without the talent, 8 snakes. 

### How should work 

The number of snakes should be increased in 6, 14 snakes. 

http://www.wow-mania.com/armory/?spell=63458

**Comment by Keader** [comment]
Fixed i belive.

**Comment by Thrashattack** [comment]
The number of snakes has increased properly.
