### ISSUE TITLE
Violet Hold Npc

### ISSUE THREAD

**Issue by Irgnac** [WoWManiaUK/Redemption#2811]
Npc Lieutenant Sinclari http://www.wow-mania.com/armory/?npc=30658 
when you start the dungeon event with this npc she is suppose to close the door and stay there in case there is a wipe and people run back can enter before enemy npcs break the door or if someone leave and someone new come the new player can enter the dungeon but the problem is that she disappear and if there is a wipe or someone new comes there is no way to enter and fight again. this happen in heroic and normal

**Comment by Lucie93** [comment]
![2222](https://user-images.githubusercontent.com/43965184/47199501-34c72900-d372-11e8-9e0b-6e4d340ea265.png)

There really is no NPC or lever when you join later or wipe.

**Comment by wow-mania** [comment]
NPC is there inside only (respawn every hour) and so is the lever.
Lever disappears if encounter is on.

![image](https://user-images.githubusercontent.com/12248683/47202912-85408580-d376-11e8-8097-775e5d9d189a.png)

![image](https://user-images.githubusercontent.com/12248683/47202934-99848280-d376-11e8-8ddb-5d109b976342.png)

**Comment by Lucie93** [comment]
That is not what he to was talking about tho.......

**Comment by TheManiax** [comment]
**How it works:**
If one or two player dies during the dungeon, they will be stuck behind the last door with no NPC to port them in.
**How it should work:**
If only a single player or two dies without a wipe, they may simply enter the instance again as a ghost and speak with Sinclari outside the doors of the prison; she'll teleport the player inside the doors. 
Proof: http://wowwiki.wikia.com/wiki/Violet_Hold_(original)
**How to reproduce:**
When one or two player die and release
You come as a ghost to the entrance
![image](https://user-images.githubusercontent.com/14857593/47224557-ab8f1100-d3c8-11e8-945f-9b0db0c790bb.png)
You pass the first door as you are a ghost
Then you will see the portal of the entrance , You will enter the portal to revive
![image](https://user-images.githubusercontent.com/14857593/47224709-00328c00-d3c9-11e8-9b99-b4cffc66f813.png)
What you will get next is a closed door, no NPC , no way to enter
![image](https://user-images.githubusercontent.com/14857593/47224751-1e988780-d3c9-11e8-853e-ab54725030f2.png)
The door is not possible to open, and there you are stuck.

**Comment by Keader** [comment]
Fixed

**Comment by Keader** [comment]
I tested in game and is working fine.
But if someone want test it too...

**Comment by Dranah** [comment]
Works fine.
