### ISSUE TITLE
[Spell] Misdirection bug

### ISSUE THREAD

**Issue by Undertower** [WoWManiaUK/Redemption#2813]
Issue: [Misdirection](http://www.wow-mania.com/armory/?spell=34477) is triggered by [Mend Pet ](http://www.wow-mania.com/armory/?spell=48990).

How it should be: Misdirection should only trigger from Damaging Attacks.

Source: The tooltip.
[The current party or raid member targeted will receive the threat caused by _your next damaging attack_ and all actions taken for 4 sec afterwards.](http://www.wow-mania.com/armory/?spell=34477)

**Comment by Keader** [comment]
Fixed my dear.

**Comment by Dranah** [comment]
Not fixed, the first tick of Mend Pet still triggers MD.

**Comment by Keader** [comment]
what?
i tested it and was working lul
i will test again.

**Comment by Keader** [comment]
now fixed ._.

**Comment by Dranah** [comment]
Misdirection now only triggers on damaging attacks.
