### ISSUE TITLE
[Spell] Volley and Auto Shot interaction

### ISSUE THREAD

**Issue by Undertower** [WoWManiaUK/Redemption#2814]
Issue: If you cast [Auto Shot](http://www.wow-mania.com/armory/?spell=75) on a target before casting [Volley](http://www.wow-mania.com/armory/?spell=58434), you can [Auto Shoot](http://www.wow-mania.com/armory/?spell=75) during the [Volley.](http://www.wow-mania.com/armory/?spell=58434)

How it should be: A channeled ability should cancel the [Auto Shot](http://www.wow-mania.com/armory/?spell=75)

Source: [Kripp Video 1](https://www.youtube.com/watch?v=OlkkQNRJfgo&feature=youtu.be&t=2m41s) [Kripp Video 2](https://www.youtube.com/watch?v=YMaNM3FQ7TM&feature=youtu.be&t=1m10s)

**Comment by Aristo14** [comment]
overall this doesnt happen 100% of the time, without testing it yet i can tell that sometimes autoshot keeps going when changing target at certain time

**Comment by Keader** [comment]
Fixed.

**Comment by Dranah** [comment]
Casting Volley will now turn off your Auto shots while its channeled.
When volley ends, your auto shots are properly resumed.

**Comment by wow-mania** [comment]
@keader and @Dranah Did we mess up a SQL here, given that as I can see it was confirmed working at some point. :)

**Comment by Aristo14** [comment]
The original issue was that auto shots kept going, they shouldnt and that was fixed. 
Now if you would only test if it stops the auto shot when you do volley you could confirm the previous issue fixed. 

However there seems to be a unwanted/intended effect to this fix but seperate in a way (why i posted a new issue and linked to this one) The auto shots stops during the channel of volley and resumes after, as if its just on pause.

**Comment by Aristo14** [comment]
players can make a macro to go arround the issue but its preferably fixed ofcourse

/stopcasting 
/cast Volley

**Comment by Dranah** [comment]
@wow-mania This wasn't in the original issue and wasn't tested for. We can't think of all possible side effects, especially not ones that need specific circumstances to reproduce.

Ontopic:
I can confirm that if you enable auto-shot, cast Volley and then attempt to override it with another Volley before the channel ends, it will result in a double interrupt, both the old and the new channel gets interrupted. Using a /stopcasting command will prevent it from bugging by cancelling the suppressed autoshots. This is not intended.

**Comment by Keader** [comment]
@Dranah try now

**Comment by Dranah** [comment]
Looks good.
You can now interrupt the Volley with another Volley before the channel ends and the new cast won't get interrupted. Auto shots still resume as intended when you stop channeling.
