### ISSUE TITLE
[Spell] Volley and Aspect of the Viper/Weapon Skill interaction

### ISSUE THREAD

**Issue by Undertower** [WoWManiaUK/Redemption#2815]
Issue: Each enemy hit by [Volley](http://www.wow-mania.com/armory/?spell=58434) counts as an individual ranged attack thus each hit regenerate mana from [Aspect of the Viper](http://www.wow-mania.com/armory/?spell=34074) as well as increasing weapon skill.

How it should be:  [Volley](http://www.wow-mania.com/armory/?spell=58434) is a Spell, not a ranged or melee attack, and should not trigger [Aspect of the Viper](http://www.wow-mania.com/armory/?spell=34074).

Source: It is impossible to find a video of someone using [Volley](http://www.wow-mania.com/armory/?spell=58434) and [Aspect of the Viper](http://www.wow-mania.com/armory/?spell=34074) together on retail 3.3.5, as no one ever used them in combination. 
Only Shots that deal Direct Damage(Chimera Shot, Arcane Shot, Steady Shot, Multi Shot, Kill Shot, Auto Shot, Explosive Shot, Silencing Shot, Scatter Shot) should trigger [Aspect of the Viper](http://www.wow-mania.com/armory/?spell=34074) while spells such as Black Arrow, Serpent Sting, Explosive Trap, Immolation Trap, Hunter's Mark, Kill Command and Volley should not.

**Comment by Dranah** [comment]
This also has a side effect of volley consuming as much ammo as many targets are hit.

**Comment by Aristo14** [comment]
Ill look into this but to say volley shouldnt activate the viper mana regen.. it should ;)

**Comment by Dranah** [comment]
Yes, the initial cast should. Not every tick on every mob it touches.

**Comment by Dranah** [comment]
Volley ticks no longer proc regen.
Initial cast however should. Currently does not.

**Comment by Keader** [comment]
https://github.com/TrinityCore/TrinityCore/issues/18152#issuecomment-256700339
I dont think that volley should proc never mana.

**Comment by Dranah** [comment]
If the initial cast of volley does not count as a ranged attack, then sure. Casting Serpent Sting properly procs Viper, though that is not a channel so it could be different.
