### ISSUE TITLE
[Boss] Freya vol. III

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#2816]
Another compilation of problems:

1) Healthy Spores https://www.wowhead.com/npc=33215
These are the red mushrooms appearing throughout the Conservator's phase.
They cast an aura, Potent Pheromones which makes you immune to Conservator's grip silence and also grants 25% increased damage.
https://www.wowhead.com/spell=62541
https://www.wowhead.com/spell=64321
**How it should work:** this aura should only be granted to players
**How it works atm:** the mushrooms buff Freya and her adds as well, creating a lot of extra damage to the maintank
Video Proof - https://www.youtube.com/watch?v=z0GD8QNQUgA
Notice how at 2:52 the player has the mushroom buff but the conservator standing on top of him does not.

2) Eonar's Gift https://www.wowhead.com/npc=33228/ cancelling Healthy Spores effect
Eonar's gift itself has a pheromone aura https://www.wowhead.com/spell=62619/pheromones to help melees to attack it, it removes the conservator's pacify, but does not grant a damage increase buff that the spores above do.
The problem here is the synergy of the two auras when the Eonar's gift spawns near a mushroom.
**How it works:** If an Eonar spawns next to a mushroom, the mushroom aura stops working. You obviously have to kill the Eonar and this means that as soon as the Eonar dies, you become silenced even though you are standing on top of a mushroom. Note, you visually retain the mushroom's buff, but it just doesnt work, you are silenced with the mushroom's buff on yourself.
**How it should work:** If Eonar's gift spawns next to a Healthy Spore, the Spore's aura should remain intact.

EDIT - There seem to be also other auras cancelling the mushroom effect as well, but so far i could only confirm this one

3) Conservator stunnable
The Ancient Conservator must be immune to stun and snare effects, currently he's not.

**Comment by Dranah** [comment]
UPDATE:
- Healthy Spores (mushrooms) will no longer buff Freya and her adds (fixed)
- Potent pheromones (mushroom buff effect) is no longer cancelled by the Eonar's gift (fixed)
- Ancient Conservator is now immune to stun effects however still vulnerable to snares and fear. This needs fix.

**Comment by Dranah** [comment]
Sorry I meant all kinds of CC ._.
I am not sure about disarm but how would you disarm a tree anyway...
It works good now.

**Comment by Dranah** [comment]
Unexpected side effect:
The last fix of immunities seems made the Conservator Immune to his own Conservator's grip aura.
Therefore when he casts it, it pops an "immune" message and just doesn't work.
Conservator must not be immune to his own aura.

**Comment by Keader** [comment]
Before test use: 
.reload creature_template 33203 
.reload creature_template 33376

Should be fixed now.
