### ISSUE TITLE
[NPC] Mikhail

### ISSUE THREAD

**Issue by GM-Gathios** [WoWManiaUK/Redemption#2818]
http://www.wow-mania.com/armory/?npc=4963

This NPC you'll need to talk with for http://www.wow-mania.com/armory/?quest=1248. But when you do, the NPC isn't available for other players to talk with. He says: Give me a couple of minutes Naralex, There was some excitement in here a moment ago.....

He does not seem to reset, killing him and respawn does fix the issue.

**Comment by wow-mania** [comment]
Does it work at least once without issues after respawn?

**Comment by GM-Gathios** [comment]
Yes, after respawn he works once. Then he needs a new reset

**Comment by wow-mania** [comment]
What is the last action of the npc?
Do you see this sentence: "I'm glad the commotions died down some around here. The last thing this place needs is another brawl."?

**Comment by wow-mania** [comment]
Where? on ptr?

**Comment by GM-Gathios** [comment]
On Redemption

**Comment by wow-mania** [comment]
Need confirmation of this in PTR.
Check with two different characters in a row.
