### ISSUE TITLE
[NPC] Loken

### ISSUE THREAD

**Issue by TenmanWoW** [WoWManiaUK/Redemption#2819]
Boss ID 28923
Spell ID 59835

How it is currently working: The boss casts Lightning Nova (59839) and damage is based on distance from the epicenter of the cast (aka the boss himself). The spell is interruptible.

How it should work: The boss casts Lightning Nova (59839) and damage is based on distance from the epicenter of the cast (aka the boss). The spell is not interruptible.

SS 

![wowscrnshot_102118_210052](https://user-images.githubusercontent.com/25806987/47275445-2dbc3880-d575-11e8-901b-3ccf109bfa2d.jpg)
![wowscrnshot_102118_210030](https://user-images.githubusercontent.com/25806987/47275446-2e54cf00-d575-11e8-8c0b-f4e834458626.jpg)

**Comment by wow-mania** [comment]
How do you interrupt it? It is not related to the spell but immunities of the NPC.

**Comment by squalllh1989** [comment]
well they just use a interupt spell and it will be interupted :)

**Comment by TenmanWoW** [comment]
Yes, just used counterspell.

**Comment by Dranah** [comment]
Not fixed yet, the spell is still interruptible by any interrupt or silence effects.

Btw this fight has another issue:
Pulsing Shockwave Aura https://www.wowhead.com/spell=52942/pulsing-shockwave
The damage is more or less correct at long range (approx 4k where you are safe from Nova), however it's doing incredibly low at short proximity.
**How it should work:** It should tick for ~700-800ish damage unmitigated before resists in melee range. 
**How it works atm:** its ticking for 150-180 unmitigated damage before resists at melee range. Essentially no damage at all.

Here's a video with displayed damage values: https://www.youtube.com/watch?v=VUmPzGO_STQ
Wowwiki: http://wowwiki.wikia.com/wiki/Loken_(tactics)
"- AoE dealing damge every tick, damage starts at ~800 in melee range increasing to 3000 at about 10 yards, further increasing farther away from the boss "

**Comment by Midnaa** [comment]
UPDATE `creature_template` SET `mechanic_immune_mask`=650854271 WHERE `entry` IN (28923, 31538); should fix

**Comment by Dranah** [comment]
Looks good.
- Lightning Nova is no longer interruptible
- Damage of Pulsing Shockwave Aura now deals intended values in close proximity as well.
