### ISSUE TITLE
Mount stopped working bug

### ISSUE THREAD

**Issue by razorblads** [WoWManiaUK/Redemption#2821]
Swift blue gryphon stopped working. Bougjt it and used it in sw and arzo for a few hours. Then it stopped working and the description even changed to only summons in outerland and northern.  When i bought it that was not the description.  It changed. My riding is 300. I already logged out and cleared catch.opened a ticked and they told me to open one here please help.

**Comment by wow-mania** [comment]
Client issue.

**Comment by razorblads** [comment]
So who do i go to next?

**Comment by razorblads** [comment]
Fixed nvm

**Comment by razorblads** [comment]
Not fixed

**Comment by GMWeeble** [comment]
Can only mount up Outside of stormwind

**Comment by wow-mania** [comment]
As-is. Talk to other players if you can't figure it out.
