### ISSUE TITLE
[Spell] Dancing Rune Weapon

### ISSUE THREAD

**Issue by Thrashattack** [WoWManiaUK/Redemption#2822]
http://www.wow-mania.com/armory/?spell=49028

### How it should work: 
When you cast DRW in a specific target (i.e Dummy A) it should attack this target (Dummy A). 

### How it works now: 
DRW is attacking always the Death Knight target , and casting the mirror spells always in the Death Knight Target.

*Also, the DRW damage is logged as "Rune Weapon" but the weapon damage doesnt appear in the combat texts, and after all the Rune Weapon damage seems to be done by the DK for behind the scenes. DRW should work in the same way as the gargolye as i can remember.

**Comment by Keader** [comment]
Both cant be fixed at this point.
Pet system dont support DRW in current implementation to make it work properly.

**Comment by bluemonstrr** [comment]
Is it reasonable to expect a new implementation in the future that could make the pet system support DRW?
