### ISSUE TITLE
[Item] Oracle Talisman of Ablution

### ISSUE THREAD

**Issue by wowmania-Kindly** [WoWManiaUK/Redemption#2823]
Hello :)
This item has an equip effect:
http://www.wow-mania.com/armory?item=44074 
That effect is not working, upon killing blows i do neither recieve energy or rage, in either cat or bear form.

My Research of this item has wielded that it should yield either: 30energy, 10rage, 40runic Power, or 5% of Your total mana pool, upon any killing blow you land on a target that would give you xp or honor. This includes any mob that is not grey to you at Level 80, meaning it still gives the effect allthough you are xp capped.

Here is a link to Wow-head comments about the effect on this item: 
https://www.wowhead.com/spell=59787/oracle-ablutions#comments
and here is a quote from those comments:

_**By Fonjask (13,728 –  2·18·90)  on 2009/02/08 (Patch 3.0.8)
Grants 5% of total mana
Grants 10 rage
Grants 30 energy
Grants 40 runic Power**_

the problem may be that i am a druid and have several pools of energy/mana, i dont know.
it takes 20days and a total of 60 dailys to obtain this, so i hope you can fix it :)

Allthough this item may seem a temporary trinket for any player, the energy gain had a use in Retail, and i plan to use this for 25hc Ruby Sanctum myself, So i hope you will take this ticket seriously, allthough at first glance this item perhaps looks unworthy of fixing.

Good Luck! and thank Your for all Your efforts on the realm!

**Comment by Keader** [comment]
Fixed.

**Comment by Thrashattack** [comment]
The mana was awared as expected and logged correct. 
![image](https://user-images.githubusercontent.com/23486776/47469522-4de73400-d7cf-11e8-99aa-589bb816fce3.png)
