### ISSUE TITLE
[Boss] Lady Deathwhisper 

### ISSUE THREAD

**Issue by Thrashattack** [WoWManiaUK/Redemption#2824]
### How it should work  

After a wipe, Lady Deathwhisper's body disappear for a second, so she can properly reset all phases and re appear saying the initial phrases ("You have found your way here...") 

### How it is working 

At the moment, Lady Deathwhisper isn't reseting properly. 
After a wipe if you enter the lady's stage, her body will appear sonner in the place and she will enter in Phase 2 with all the mana shield up and walking. 

As you can see in the chat, there's record of the combat ended and the combat started again in phase 2. 

![image](https://user-images.githubusercontent.com/23486776/47452372-20cb5f00-d798-11e8-84fe-15ac5f318dac.png)

**Comment by Dranah** [comment]
This appears to be an issue with DBM, not the fight.
In my tests she properly starts in phase1 even though DBM announces its phase two.

**Comment by Keader** [comment]
Yeap, is DBM bug.
Fight is working fine.

**Comment by Dranah** [comment]
Occasionally the fight auto-engages after reset (there is no one in pull-range). It does not consistently happen and I can't reproduce why. Until someone has further information for this, there's nothing we can do about it.
