### ISSUE TITLE
[Boss] Felmyst (Sunwell Plateau)

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#2825]
https://www.wowhead.com/npc=25038/felmyst

1) The spawn
**How it works atm:**
When Brutallus dies, Felmyst instantly becomes visible and attackable in the air slightly above him. (this is already an improvement from not spawning at all)
However this brings up issues with ninjapulls.
**How it should work:**
When Brutallus dies, after a 2minutes of pause, Felmyst rises from Madrigosa's corpse.
The original spectacular event may be too troublesome to fix, however we need an improvement that gives raids a warning of Felmyst's presence and ample time to rest and prepare for the pull.
Suggestion for workaround: Making Felmyst visible but not yet attackable for a minute, and add her missing intro yell emote "Glory to Kil'jaeden! Death to all who oppose!" when she spawns 

2) Encapsulate https://www.wowhead.com/spell=45662/encapsulate
This mechanism is missing entirely. Should be cast on a random raid member (tank included!), grabbing them in a capsule, dealing strong arcane damage both to the target and nearby allies.

3) Fog of Corruption 
https://www.wowhead.com/spell=45717/fog-of-corruption
How it should work: 
The trail of fog should MC and empower players that step in it. If the encounter is reset because the raid wipes, Felmyst kills all MC'd targets via https://www.wowhead.com/spell=45917/soul-sever.
How it works atm:
The MC/empower effect is missing, the fog simply instantly kills players. 

4) Deep Breathe
**How it should work:**
Boss flies to one end of the room, and begins a cycle of 3 breathes, each time does an emote "Choke on your final breath!" and then sweeps through the field, covering about 1/3 of the area either on the south or the north with a trail of Fog of Corruption, then turns around and rinse repeat until all 3 are done. Then she lands and returns to the MT and starts ground phase again.
**How it works atm:**
- Despite being in "air" phase, the boss is walking on the ground, instead of flying. (note: she properly flies while casting Demonic Vapor, but then lands) Emotes are wrong or missing, she usually does the take-off emote "I am Stronger than ever Before!" whenever she starts moving, whether she breathes or just goes for a walk. (see point a little below)
- The boss keeps leaving a trail of Fog even when air phase ended and she is returning to follow the main tank. This can cause serious issues as this is the main wipe mechanism and it's hardly possible to dodge if the boss follows you with it.
- Often, between 2 deep breathes, she comfortably (and slowly) walks from one end to another while also leaving a trail of fog. This "extra mile" she walks completely fucks the DBM timers as it elongates the air phase, instead of breath > breath > breathe, she does breathe > walk back > breath > walk back > breath , essentially walking back and forth on the same path. 
- Wrong starting position: right now she has 3 or 4 possible positions to fly to when beginning deep breath cycle, far right (works ok), closer right(bugs with the extra miles most often), far left(works ok), and the balcony where the raid came from (total broken). This last one is totally unintended, and when she chooses to jump up on the balcony, her first breathe then cuts across the room in the center and gets her stuck inside the fire walls, there she keeps walking back and forth on the wall's line, being line of sight and evading and not willing to return when air phase ends. 
Sometimes even wiping won't unbug her and reset her position.
- Boss resets fully if her main tank dies in the fog, even if there are other raid members alive present

5) Unyielding Dead https://www.wowhead.com/npc=25268/unyielding-dead
These are skeletons spawned by the Demonic Vapor used during air phase.
They normally spawn with their intended 24k health, however some transform into 10million health. This seems to happen if they walk through the Fog of Corruption. This happens usually if you root/CC them while dodging the clouds and so it hits them. With 10million health they are literally immortal.
How it should work: Fog of Corruption should not affect skeletons health

6) Felmyst shouldn't be tauntable
Right now she is - though you may rightfully ask, with all the above bugs in mind, who the bloody hell cares?

**Comment by wow-mania** [comment]
Please re-test.

**Comment by Dranah** [comment]
UPDATE 
- Fog of corruption no longer kills players, in fact it barely does anything at all. Seems to spawn more skeletons like the demonic vapor o,o
- Felmyst no longer starts her breathe cycle off the balcony and won't get immediately stuck evading behind the fire.
- Skeletons no longer gain 10mil health in the Fog

Overall the fight is still very broken and hardly resembles how it should look but it's doable at least.
Will leave this as tweaking, hopefully someone on trinity rewrites this to be blizzlike.

**Comment by fvicaria** [comment]
New version uploaded. Let me know if it is an improvement or worse than previous.
This is very much a new script.

**Comment by Dranah** [comment]
Hard to compare.
1) The spawn is cosmetically a little more blizzlike with felmyst rising from the ground (though madrigosa is nowhere and the actual event does not work) with an emote instead of simply appearing, but practically worse as she also auto-engages way too early. Is also a minor annoyance that if you reset the encounter, every time you pull Felmyst, she'll do a little flight with an emote while she's unattackable, before she lands and goes to your tank.
2) Deep breathe: her flight is cosmetically more blizzlike, she now actually flies instead of walking in the air. Also at correct speed and pathing. Functionally however... the Fog she breathe does not actually reach the ground, there's no fog.
3) The demonic vapor never despawns. Endless, endless skeletons. They also don't seem to despawn when the fight is reset.

Overall I'd say this version is slightly worse but at some points it has improvements.

**Comment by Dranah** [comment]
I have managed to get the start event to work but Brutallus is getting stuck behind the fire wall....
Please revert this new script. I told you the previous version functions better at the current state.
I don't know if this one is a better material to work on, but with Brutallus bugging and evading and the vapors filling the entire room over time as they never despawn, right now it's awful and the improvements are only cosmetic.

**Comment by wow-mania** [comment]
I will revert on dev this morning. Just let me know.

**Comment by wow-mania** [comment]
I have reverted to the previous workable version.
We will keep it like this for now and improve later.

**Comment by Dranah** [comment]
Fight was reverted to the state it is doable now, just full of glitches. Leaving an update summary for future work.

**Remaining problems are:**
- Fog of Corruption does not do its intended effect (mind control players), instead it behaves like the Demonic vapor and spawns skeletons
- Felmyst still leaves a trail of Fog of Corruption when she ends the air phase cycle, which inevitably hits the tank as she returns. She should stop spawning fog once she's descending. (this bug is balanced by the previous atm, so both will need to be fixed at same time)
- Air phase Deep breathe cycle is still off, she walks in the air rather than flies, is way too slow and does wrong emotes as well. She appears to walk the same path over and over and sometimes hesitates to come down (stays there in the corner for a while). Apart from looking awful cosmetically, this bug mainly screws the timers and makes air phase somewhat easier than it should be.
- Encapsulate mechanism missing (can live without it for now just makes fight much less blizzlike)
- Felmyst being tauntable (same)
- Spawn event missing, Felmyst simply appears above your head once Brutallus dies. Part cosmetic issue, partly leads to ninjapulls.
