### ISSUE TITLE
[Quest] Rejold's New Brew

### ISSUE THREAD

**Issue by WhitephoenixTheBunny** [WoWManiaUK/Redemption#2826]
At the moment [Tharek Blackstone](http://www.wow-mania.com/armory/?npc=1872) is not offering the quest [Rejold's New Brew ](http://www.wow-mania.com/armory/?quest=415).

Following [WoWhead info](https://www.wowhead.com/quest=415/rejolds-new-brew) this is a removed quest but only on Cataclysm.

Note: I have all the quests done on the leveling zone, and the only requirment asked on armory is level 8.

**Comment by wow-mania** [comment]
![image](https://user-images.githubusercontent.com/12248683/47494724-3d27d400-d84a-11e8-90d7-fbddbeb315c8.png)
You need to do quest http://www.wow-mania.com/armory/?quest=315 before.
I will make sure it appears in the requirement.

**Comment by wow-mania** [comment]
Fixed in Red and Ely also.
Armory will take a few minutes to update.
