### ISSUE TITLE
[Quest] Feathers for Nafien

### ISSUE THREAD

**Issue by TheSale** [WoWManiaUK/Redemption#2827]
This is repetitive quest that give repitation with Timbermaw Hold
turing 5x Deadwood Headdress Feather you should get 2.000 reputation with Timbermaw Hold
https://www.wowhead.com/quest=28395/feathers-for-nafien
this is original post from wowhead

the issue is not quest itself, but the item Deadwood Headdress Feather that does not drop at all!
http://www.wow-mania.com/armory/?item=21377#dropped-by

I have killed over 50npc and not 1 single drop of feathers.
I did prequest timbermaw ally http://www.wow-mania.com/armory/?quest=8460
and blue question mark appeared on Nafien and he want to accept my feathers, but they dont drop.

on wowhead it is displayed that item droprate is 20%-45% by sample over 1 million of total npc kills
on wow-mania it is marked 25%-35%

And also I have noticed that on wow-mania armory quest is labeled to give only 25 reputation when it should give 2.000 reputation

I also want to note to testers, that if they manage to get few items dropped, and that I was very unlucky od drops, for 50 npc that I have killed they should drop around 10-25 feathers.

**Comment by wow-mania** [comment]
On my first try...
![image](https://user-images.githubusercontent.com/12248683/47570708-bac51000-d92e-11e8-9fb3-ce6838b36865.png)

**Comment by TheSale** [comment]
https://mega.nz/#!9JVyQaDK!F0OJ4mipNEYekIU-vY3qf0-kztgKCHVnDk15T3Zzp4U

video is a little bit bad, my obs was set up for my better configuration.
this is sample of 35looted npc and not 1 single feather

I have no idea how and where u testing, but this would be over 100npc killed by me and no drop

**Comment by wow-mania** [comment]
I will ask a tester to re-check it.
I got it on the first try on one mob and on the second try on another.

**Comment by TheSale** [comment]
dear good I wish I can have that :(

but also check if the quest give 2.000 reputation coz another quest that should give 2.ooorepitation on another side of tunel give only 300 rep....

**Comment by TheManiax** [comment]
![image](https://user-images.githubusercontent.com/14857593/47576887-6cc20380-d952-11e8-8f47-17bca7bb5ee0.png)
@TheSale do [[Timbermaw Ally]](https://wotlk.evowow.com/?quest=8460) first and the feathers will drop.

**Comment by TheSale** [comment]
Did I wrote in post that I did that quest?

**Comment by TheSale** [comment]
omg GM Amytis just helped me, I did wrong quest, I am sorry!
