### ISSUE TITLE
"One or more of your MPQ files are corrupt. Please download a fresh client"

### ISSUE THREAD

**Issue by cNkbZ33v4U** [WoWManiaUK/Redemption#2829]
Hi

I've tried using the proper launcher, but it doesn't work. I get the above error. I have tried re-downloading the client several times, to no avail. Through some trial and error, someone helped me find out that for whatever reason, i was missing a few files. She sent me the files, but I get the same error still. 

The weird thing is that i can launch wow.exe directly, and it works and i can play the game etc, but when i try to run launcher.exe, i get that error. Any ideas?

Thanks

**Comment by wow-mania** [comment]
Not a server issue. Corrupted files are client side, 100% your problem.
Redownload client from scratch or check the forums.
