### ISSUE TITLE
[Boss] Freya - Allies of Nature

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#2830]
https://www.wowhead.com/npc=32906/freya
This is a new issue that wasn't present a couple weeks ago.

Allies of Nature is one of the add-waves that consist of three adds:
https://www.wowhead.com/npc=32916/snaplasher
https://www.wowhead.com/npc=33202/ancient-water-spirit
https://www.wowhead.com/npc=32919/storm-lasher

**How it should work:**
These adds are linked together in a manner that they must all die within 12 seconds of each other, otherwise the dead ones resurrect.
Each add is supposed to remove 10 stacks of Attuned Nature stacks from Freya, and it should only be removed once, no matter how many times they resurrect.

**How it works atm:**
Their Resurrection appears completely broken, killing an add will not result in it coming back to life if the other two are still alive 12 sec later.
If you still happen to kill them at same time, there's a problem with Attuned to Nature stacks being discounted twice for each add (so one wave removes a total of 60 stacks instead of 30)
Note this ONLY happens if you kill all the three adds within about 1second of each other (but that's kinda how it should be done).
However this is a very spectacular issue as it results in Freya beginning phase 2 after just 4 waves (if you had 2x allies) instead of the intended 6.

Steps to reproduce:
>Get freya to spawn Allies
> Take each add to as low as 10k health
> Spam frost nova or another AOE damage with no cd and finish off all the adds within a very short time frame
> Freya's stacks fall by 60 stacks instead of 30

**Comment by squalllh1989** [comment]
Confirmed.
- The Allies of Nature at the moment won't resurrect if being splited kill, their corpse just disapear when killed, even if 1 of them still alive.
- If you kill them slowly (not too fast, since the resurrect is broken atm, you can use half an hour or what ever to kill them off), kill all 3 of them remove 30 stack of buff off freya. If you kill them all together very fast (in about 1-2 sec for all 3), you remove 60 stack instead of 30.

**Comment by Keader** [comment]
God, it was super broken.
I did a new code to handle with it.
Check if work.

**Comment by Dranah** [comment]
Something in that code is crashing the PTR. When you kill one of the adds, 12sec later when it should ress, PTR goes down instead.
 + New problem arose with Detonating Lashers (probably related to previous immunity fix on Conservator), they are now also immune to all form of stun/snare, this is not intended. Those little shits shouldn't be immune to anything.

**Comment by Keader** [comment]
try now @Dranah 
And use:

.reload creature_template 32918
.reload creature_template 33399

Before test.

**Comment by Dranah** [comment]
The good news is that the PTR no longer crashes.
The bad is that the fix doesn't work. Both issues with allies still persist, dead ones wont resurrect, and killing them at the same time results in double the stacks lost.

Meanwhile, Detonating Lashers immunity is fixed, they can be cc'd now.

**Comment by Keader** [comment]
Try now
@Dranah

**Comment by Dranah** [comment]
Update:
- Adds that are killed now properly resurrect after 12sec (fixed)
- Adds that resurrect don't automatically re-engage if you aren't very close to them (approx 15yard). This need fix.
- Adds that are killed and then resurrected don't seem to take off Attuned stacks when killed again
Steps to repro:
1. Kill one of adds
2. Wait for it to ress
3. Kill all 3 adds
4. Only 20 points off, instead of 30
- Adds now take off proper amount of Attuned stacks when they are killed within a short time frame
- Fix on Conservator being immune to his own aura is reverted (was reported in the other thread)

**Comment by Keader** [comment]
test now @Dranah 
Looks working to me now.

**Comment by Dranah** [comment]
UPDATE:
- Allies that rezz will now auto engage properly (fixed)
- Killing adds at roughly the same time still results in only 20 stacks being removed instead of 30 if one of the adds have resurrected before. (need fix)
- Immunities are now as intended

**Comment by Keader** [comment]
rdy to test

**Comment by Dranah** [comment]
Can no longer reproduce issue with only 20 stacks being lost.
