### ISSUE TITLE
Closed issue 2814 not fixed correctly 

### ISSUE THREAD

**Issue by Aristo14** [WoWManiaUK/Redemption#2834]
https://github.com/WoWManiaUK/Redemption/issues/2814

This issue isnt fixed correctly as atm when you are doing auto shots and then go to volley it will create a bug. 

How it should work: 
when in any situation you go to volley and line volley up in a sequence you should be able to do so and just refresh the channeling. Casting other abilities or moving should cancel the channeling. 

How it works: 
- When you go from auto shots to volley you will not be able to refresh the channeling and instead of refreshing the volley channel it gets interupted and resumes autoshots
- It also does cost mana (for the volley)  while not doing anything. 
- You can't resume autoshot during/interupting the channeling of volley.

(when you haven't done any autoshot everything works properly, this is why I link it to the previous issue)

Please re-open the issue and fix appropriatly.

**Comment by wow-mania** [comment]
Please do not open a new issue like this. Comment on existing issue.

**Comment by Aristo14** [comment]
Apologies for the inconvenience

I have added it to the closed issue and re-opened that one + removed the labels.

**Comment by wow-mania** [comment]
No worries. Keader will take a look at this.
