### ISSUE TITLE
[NPC] Short John Mithril

### ISSUE THREAD

**Issue by GMWeeble** [WoWManiaUK/Redemption#2837]
[> `Short John Mithril`](http://wow-mania.com/armory/?npc=14508#ends) Spawns a chest in Gurubashi Arena every 3 hours, but this timer seems to be off. Please take a look.

**Comment by wow-mania** [comment]
The event is happening every 2hr on redemption on even hours.

**Comment by GMWeeble** [comment]
This should be every 3 hours

**Comment by wow-mania** [comment]
I know. I have increased the frequency to promote more pvp.
