### ISSUE TITLE
[Spell] Raise Dead

### ISSUE THREAD

**Issue by Thrashattack** [WoWManiaUK/Redemption#2838]
Raise Dead (ID: is currently not working with Humanoid Corspses as intend. 

As the spell description says: 
![image](https://user-images.githubusercontent.com/23486776/47832419-cc157e80-dd6b-11e8-9480-f5d75834cb18.png)

• IF, and only if no humanoid corpse you must supply a Corpse Dust.

### How it is working  

Raise Dead always need a Corpse Dust to complete the spell 

### How it should work 

Raise dead should be applyied on the near humanoid corpse. 
If no humanoid corpse , then look for a corpse dust. 

![image](https://user-images.githubusercontent.com/23486776/47832540-768da180-dd6c-11e8-8348-0d079e48ff15.png)

**Comment by Dranah** [comment]
Confirmed, also if you do have Corpse Dust in your bags for times when you can't find a corpse, if there is a humanoid nearby it should still consume the humanoid first and not the corpse dust item from your inventory.
