### ISSUE TITLE
[NPC] Brew Vendor

### ISSUE THREAD

**Issue by cathyr1** [WoWManiaUK/Redemption#2840]
This NPC http://www.wow-mania.com/armory/?search=brew+vendor who sells the brews necessary for achievment http://www.wow-mania.com/armory/?achievement=1183 is missing on the horde side. There is only alliance one in Ironforge, but the horde one simply dissapeared.
![vendor](https://user-images.githubusercontent.com/30184491/47953782-66e7a600-df82-11e8-9ae7-a1fe154b6244.png)
If possible, add him until end of November please to not miss this month´s brew.

**Comment by wow-mania** [comment]
Which vendor? Please link the correct npc not a search. Thanks.

**Comment by wow-mania** [comment]
The vendor is there. Just dropped below the texture. It will be back after a restart.
