### ISSUE TITLE
[Item] Val'anyr Hammer of Ancient Kings Weapon Internal Cooldown

### ISSUE THREAD

**Issue by xclaw800** [WoWManiaUK/Redemption#2842]
On retail the weapon Val'anyr Hammer of Ancient King's ability has a 45 second internal cooldown. This is accurate on Wow-Mania if the player only uses the hammer then this cooldown stays in 45 second increments.

HOWEVER when you swap the weapon out and unequip it for something else, much like for a trinket, the internal cooldown resets when the Val'anyr Hammer is equipped again. This means the player must wait a minimum of 45 seconds for the blessing to be placed upon the player after it is equipped. On retail this was not the case. The internal cooldown is supposed to finish and remain ready to use without having to wait after they equip the weapon.

The following article shows very closely that there were top retail healers who used to mid fight swap to using the mace. More specifically when the internal cooldown on the mace was ready to use. As in the internal cooldown kept going while it was in the characters bags and then did not reset to 45 seconds when equipped.
The wording from a top restoration druid in retail is that "I use Val'anyr when I know high burst AOE is coming and the internal cooldown on the proc is up. When raid damage is incoming, I will swap my Val'anyr for the bubbles and then swap back to Trauma since it has no internal cooldown,"

Website url:
http://www.headhunters-guild.co.uk/forums/showthread.php?9155-Focus-To-Val-anyr-or-Not-To-Val-anyr

The specific section is shown in this second url: 
https://cdn.discordapp.com/attachments/503728598352396289/507582209402601473/image0.png

This clearly shows that he is swapping for specific situations and not something that would be happening 45 seconds later. To make sure I am being clear, my request for the fix is that Val'anyr must not have its internal cooldown reset after reequipping it. Weapon Internal Cooldowns and trinket internal cooldowns work differently because you cannot switch out anything but weapons and secondary slots like librams or idols mid fight. Hence why this is different.
If more proof is needed I will find it but this is 3.3.5 confirmed and even continued after the expansion finished.

**Comment by DiomacheTharghan** [comment]
Confirming and supporting this, our resto druid, Baotn, was doing the same thing between Val'anyr and Royal Scepter HC.

Tharghan/Diomache

Former Officer and CL of Nihilum, core raider of Ensidia.

**Comment by wow-mania** [comment]
Sorry, this has been worked on and it works. So unless you provide hard evidence and reliable material we will not look at it again.

**Comment by Keader** [comment]
I was talking with Dranah this weekend about it.
I think that the issue here is opposite.
I remember that when i was testing Shadowmourne in retail, when i swap weapon, it stop proc souls for something like 30 sec, like all active weapons.
I realy think that Valanyr cooldown is correct, what's missing is add 30 sec cooldown to other weapons that dont have it yet, like Trauma, Shadowmourne, etc.

**Comment by DiomacheTharghan** [comment]
> 
> 
> I was talking with @Dranah this weekend about it.
> I think that the issue here is opposite.
> I remember that when i was testing Shadowmourne in retail, when i swap weapon, it stop proc souls for something like 30 sec, like all active weapons.
> I realy think that Valanyr cooldown is correct, what's missing is add 30 sec cooldown to other weapons that dont have it yet, like Trauma, Shadowmourne, etc.

You don't understand what's the issue then.. Having other Weapon in cd doesn't mean valanyr also does, and it's its own peculiarity to be able to swap it to play with icd while standing inside the bag.. Also, Trauma has been known for NOT HAVING an internal cd, never had and never will, nor in retail or anywhere. Val'anyr swap has been around since ulduar content in retail, and, as member of the best guild in the world at that time, there are nothing else than evidences to prove it, everywhere. 3.2 Has been the patch that scaled the val'anyr, and that allowed the people/players to make the swap a new era of the meta games for legendary weapons.

**Comment by Dranah** [comment]
Let me clarify, I did not play retail in 2010 on 3.3.5a to have personal experience.
Therefore, as I said to @Keader (and also Kestor) before, we need to compare evidences to make an objective judgment.
While i'm not the big boss here and the final decision belongs to @wow-mania , I'd like to help in summarizing what we currently have:

1) The manner of Shadowmourne having its ICD reset on equip is not directly related to Valanyr at all so it cannot be taken as an evidence. Also any tests done on current retail (patch 8.0) are completely meaningless as the game changed in several ways over the years.

2) I did find certain comments on wowhead that state blizzard made this swapping not possible after a while, but it is unclear when, and most of them are of unreliable, noname posters and some been downvoted as well.

3) Sources I see posted here are pretty solid and reliable and confirm each other.

4) Keader raised a question of why there is no official word from blizzard on this swapping thing being viable. I already answered this in private discord chat, that all of official posts suggest Blizzard wished to tell as little of the weapon and the proc to players as necessary. https://www.wowhead.com/forums&topic=94042 full text here, important part is "**While we originally intended for this effect to be a mystery,** we realize that guilds now know what the tooltip on the proc says without necessarily knowing the details on how it works."

5) There is one large argument that can be brought up against this change, which is that it would make sense that these effects have their ICD reset on equip just like trinkets to prevent "abuses".
However, it is essentially the only way Valanyr was still viable at ICC and RS end-game, so it is hardly an abuse, and it also makes total sense that Blizzard did NOT change this, at least not before Cataclysm, to make sure the legendary ppl worked SO much for, doesn't get thrown into the bin too early.

**My consensus:**
There is more reliable proof that supports this post than what contradicts it, so we should fix it.
Using this swapping method allows this weapon to remain viable in ICC gear levels, which would motivate more people to do more Ulduar.
And finally,there is much less harm in fixing it, even in that 0,1% chance of case that all the above proof are wrong, than leaving it broken while they are valid as it prevents players from utilizing one of the most awesome additions in the WOTLK expansion.

**Comment by DiomacheTharghan** [comment]
> 
> 
>     4. Keader raised a question of why there is no official word from blizzard on this swapping thing being viable. I already answered this in private discord chat, that all of official posts suggest Blizzard wished to tell as little of the weapon and the proc to players as necessary. https://www.wowhead.com/forums&topic=94042 full text here, important part is "**While we originally intended for this effect to be a mystery,** we realize that guilds now know what the tooltip on the proc says without necessarily knowing the details on how it works."
> 
> 
> 

Took 3 and half years to make player understand they could have Totem Twist, so please don't talk about what blizzard stated or could have state, because it's leading nowhere... The fact blizzard should have just open a blue post, aka a post from ghostcrawler, which was the chief designer of the game at that time, was just a pure illusion if you think they were working again. We lost our world 1st due to saronite bombs, which were never tested in any PTR because blizzard "didn't state" any of these bull****. So, It is so clear that using the fact that blizzard didn't call it out pubblicly some game mechanic it's kind of senseless, because at that time, including wotlk too even if in a small part compared to the previous expansions, blizzard wanted the community to enjoy the discovery of game mechanics and yet, they even didn't know most of them (i.e. Totem twist as i said).

**Comment by GMWeeble** [comment]
Just so it is clear, you are not talking about the ITC resetting when re-equiped? Just that the cooldown cools down while unequiped and continues it's cooldown to whatever it was when you then re-equiped?

**Comment by Keader** [comment]
@DiomacheTharghan idk if is my bad english, but why be rude? you will dont get nothing with that attitude.

@xclaw800 Yeah, looks like we have more proof which supports your arguments than against

@GMWeeble Cooldown already count while Valanyr is un-equipped. But current code, add a ICD on proc aura, when it's equipped.

Still dont make much sense to me, why blizzard add internal cooldown to all weapons with active spells, and not do it in passive (proc) ones?

**Comment by wow-mania** [comment]
@keader This is your call. I don't think there is much to do here but if you think it is a meaningful thing feel free.

**Comment by DiomacheTharghan** [comment]
> 
> 
> @DiomacheTharghan idk if is my bad english, but why be rude? you will dont get nothing with that attitude.
> 
> @xclaw800 Yeah, looks like we have more proof which supports your arguments than against
> 
> @GMWeeble Cooldown already count while Valanyr is un-equipped. But current code, add a ICD on proc aura, when it's equipped. Cooldown is always added to player, not to equips... so, equiped or not, cooldown is always running (if player is online).
> 
> Still dont make much sense to me, why blizzard add internal cooldown to all weapons with active spells, and not do it in passive (proc) ones?

I honestly wasn't trying to be rude, if this was the "message" that passed through, i apologize

**Comment by DiomacheTharghan** [comment]
> 
> 
> @Keader This is your call. I don't think there is much to do here but if you think it is a meaningful thing feel free.

Tbh Janitor, and don't get me wrong on that, i think it's "mean" to people that have donated for that weapon (aka 99% of the holder of that specific mace), deserve ATLEAST a proper working one. This doesn't mean i'm telling you how to run your server, god no, but atleast use some common sense and do the good of the server itself, the community, and the donators.

**Comment by xclaw800** [comment]
> @DiomacheTharghan idk if is my bad english, but why be rude? you will dont get nothing with that attitude.
> 
> @xclaw800 Yeah, looks like we have more proof which supports your arguments than against
> 
> @GMWeeble Cooldown already count while Valanyr is un-equipped. But current code, add a ICD on proc aura, when it's equipped. Cooldown is always added to player, not to equips... so, equiped or not, cooldown is always running (if player is online).
> 
> Still dont make much sense to me, why blizzard add internal cooldown to all weapons with active spells, and not do it in passive (proc) ones?

Ty for accepting the evidence and I hope you guys can sort out the fix whenever you have time. Thank you!!

**Comment by Dranah** [comment]
@wow-mania As Diomache pointed out, (even if slightly overzealous at times), this issue is HEAVILY supported by players, specifically donators among them, so it benefits both the server and its community to have this fixed. The only question was if the report is valid, but after comparing evidences, we can agree that it is.

**Comment by Dranah** [comment]
UPDATE:
Valanyr no longer resets ICD when equipping/unequipping. You can now toss it into your bag for 30sec after its proc expired and then re-equip when the cd is ready.
Note: if you unequip valanyr while its 15sec duration proc is still running, it will dispel the proc from you. This is intended, as the proc has a flag "requires main hand weapon"

**Comment by Keader** [comment]
what?

**Comment by Keader** [comment]
Is a new issue, related with proc system.
Looks like we lose all proc cooldown if aura is removed...
So i made a hack to store cooldown.
Now will work fine, test please @Dranah

**Comment by Dranah** [comment]
Nop, re-equipping valanyr still erases its cooldown

**Comment by Keader** [comment]
what? i tested myself and is working o.o

**Comment by Dranah** [comment]
Works good now.
