### ISSUE TITLE
[Quest] Tempering the Blade

### ISSUE THREAD

**Issue by Blasphemiah** [WoWManiaUK/Redemption#2847]
I tossed the blade into the crucible but nothing happenned. I lost the blade and could not get the forged blade back, so I'm stuck in the quest chain as it is
![wowscrnshot_110918_193625](https://user-images.githubusercontent.com/33109088/48281841-2ee7d380-e458-11e8-8bba-f47d2ce2b9a6.jpg)

**Comment by wow-mania** [comment]
Cannot reproduce. Works everytime.
