### ISSUE TITLE
[Battleground] Alterac Valley - Body Ressurrection 

### ISSUE THREAD

**Issue by Thrashattack** [WoWManiaUK/Redemption#2848]
When you die in Alterac Valley and the opposite side take the GY wich you are waiting for ressurection, you have 3 options: 

• Wait for your faction to re-take controll of this GY 
• Go to the next near GY controlled by your facction 
• Go to your body and revive with 50% health and mana. 

At the moment the last option isnt working. When you go to your body the acction of ressurrect when you click to do it just does nothing and you keep there as a ghost. 

I also noticed that your body isnt there at all nor the bones.

**Comment by Dranah** [comment]
I cannot reproduce issue on PTR.
Did somebody remove your insignia after you died perhaps? That prevents you from using your body to ress, i think you even get a message like "you can only resurrect at a graveyard".

**Comment by squalllh1989** [comment]
Can't reproduce, can rez normally when test.
