### ISSUE TITLE
Conflicting points award for 25 Exalted 

### ISSUE THREAD

**Issue by Masterscubadude** [WoWManiaUK/Redemption#2850]
![wowscrnshot_111018_220200](https://user-images.githubusercontent.com/44933105/48306866-08e63000-e539-11e8-9e74-63ccc7976181.jpg)
![wowscrnshot_111018_220209](https://user-images.githubusercontent.com/44933105/48306869-17cce280-e539-11e8-80bc-c3a7a6983ecc.jpg)
 As you can see they differ by as much as 50 points ... Summary shows 10 points only instead of the 60 for 25 exalted Reputations 

Best regards Oldboy Redemption

**Comment by wow-mania** [comment]
Cannot reproduce this. Pretty sure it is just visual glitch of the summary.

**Comment by Masterscubadude** [comment]
Hi there Janitor! I'm sure it must be a glitch on my end however I just thought you'd obviously like to see such weird & rather curious anomalies.. only thing I could think of is when I tried the PTR last year back only to find that I already had a character on their which was a facsimile of my character "Oldboy"  wearing all the items I had at a level 58...strange but true!! Anyway brother keep up the good work & thank you & your team for making Wow Mania a very enjoyable experience for this returned vanilla vet..all the best Phil aka Oldboy...



Sent from my Samsung Galaxy smartphone.


-------- Original message --------

**Comment by WhitephoenixTheBunny** [comment]
Achievment tab have other visual bug, annoying ones, I will (maybe, probably :)  ) make a report
