### ISSUE TITLE
bug quest

### ISSUE THREAD

**Issue by Debastador** [WoWManiaUK/Redemption#2851]
Hi, i was going to kill Tapoke''Slim''Jahn but he never whent outside so i contacted a GM he told me to report it here because i cant get the quest again hes in Menethil Harbor Inn ty the guy that gives the quest hes name is Mikhail hope it can get fix fast ty again

**Comment by Thrashattack** [comment]
The quest is working on PTR. 
![image](https://user-images.githubusercontent.com/23486776/48310323-57f98880-e56c-11e8-9229-3766b88d3844.png)
