### ISSUE TITLE
[Spell] Wailing Souls

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#2852]
https://www.wowhead.com/spell=68873/wailing-souls
Cast by https://www.wowhead.com/npc=36502/devourer-of-souls

This ability currently deals no damage.
It appears to properly rotate around but no matter how hard I tried, I could not get it to damage me a single time (over ten runs in FoS). I went a full circle in case it was simply a visual issue but it isn't.
Its visual beam is also pointed somewhat upwards, if that has anything to do with it.

How it should work: "Lets loose Wailing Souls, inflicting 4,875 to 5,125 Shadow damage every 0.4 seconds to anyone infront of it."

**Comment by squalllh1989** [comment]
Confirmed this, the beam doesn't do any damage, this is currently bugged (or at least the visual beam is bugged, as stand in the beem do no damage at all)

**Comment by Ashamedlol** [comment]
The visual of the beam is bugged, as someone standing way far from the beam could be hit massively.

And the boss is autoattacking the tank standing in front of him while this is being cast, which is another bug.

**Comment by Keader** [comment]
Fixed
