### ISSUE TITLE
Character Glitch

### ISSUE THREAD

**Issue by PandaEyesXD** [WoWManiaUK/Redemption#2855]
My characters are glitched.. What do i do?
![errer](https://user-images.githubusercontent.com/45076585/48575279-360c5700-e91a-11e8-9f65-3c28964fc503.PNG)

**Comment by wow-mania** [comment]
Please do no re-open issues. Or we will be forced to block you.

**Comment by PandaEyesXD** [comment]
but you didn't help me on what i wanna do to fix this.. :(

**Comment by wow-mania** [comment]
There is no issue.
