### ISSUE TITLE
[Quest] The Light of Dawn

### ISSUE THREAD

**Issue by Anthonhed** [WoWManiaUK/Redemption#2856]
How it works:
When you start the quest The Light of Dawn(http://wow-mania.com/armory/?quest=12801) Mograine and the Army is running to Light's Hope Chapel but then stops right before.
![wowscrnshot_111618_112216](https://user-images.githubusercontent.com/26274880/48618184-e02ac400-e998-11e8-973d-b7be4655e7a0.jpg)
And does not go all the way there to help defeat the Argent Dawn
![wowscrnshot_111618_112245](https://user-images.githubusercontent.com/26274880/48618241-0cdedb80-e999-11e8-9220-28d1137bbcfb.jpg)

How it should work:
The whole army should run all the way to Light's Hope Chapel to help defeat the Argent Dawn as shown in the video
https://www.youtube.com/watch?v=YP8nbf9TBso

**Comment by wow-mania** [comment]
You have to stay close to the leading NPC at all times.
Quest works but there is ways to for it to bug if you don't follow it closely.

**Comment by Anthonhed** [comment]
I was aware of that and ran with Mograine all the time, the same thing still happened

**Comment by wow-mania** [comment]
Check on dev. An NPC may be in a bad state.
