### ISSUE TITLE
[Mount] Luminous Starseeker

### ISSUE THREAD

**Issue by Muffinbutton13** [WoWManiaUK/Redemption#2859]
This new mount should act like a ground mount and flying mount depending on the location and riding skill, although at the moment it can only be summoned in places where you can use a flying mount, making it effectively only a flying mount.
It should act like the ''Celestial Steed'' mount which is both a ground and flying mount and can be summoned and treated like a ground mount in places that restrict flying.

PS: I've also noticed that this is another mount that has the same exact problem, and here's a link showing the description on the item itself talking about this particularity from the mount of being a ground or flying mount depending on it's location.
https://www.wowhead.com/item=109013/reins-of-the-dread-raven
Quote: ''This mount changes depending on your riding skill and location''

So I guess the issue is either with several mounts as a coincidence or simply a mechanic from these kinds of mounts not working properly for any of them.

**Comment by TenmanWoW** [comment]
Mounts that are imported from later expansions are "as is". Similar to Heart of the Aspects, mounts imported from later expansions are purely a model. The part about "Mount changes depending on your riding skill and location" cannot be implemented on our server. Therefore, how the mount appears when you summon it will be how it always appears independent of your riding skill and location.

**Comment by WhitephoenixTheBunny** [comment]
Extra info:
Only three mounts acts as flying and grounding:
Celestial Steed
Invicible
Horseman

**Comment by Muffinbutton13** [comment]
That's the thing though, those three mounts have that particularity working on this server about acting as both ground and flying mounts, and while I admit the Luminous Starseeker stops counting as both a ground and flying mount IF you still do NOT have flying riding skills (my mistake), the Dread Raven mount is the same case as those three mounts meantioned by Phoenix.

I don't really know much about the coding part of all this and if it's doable, but if this ground/flying aspect is already working on those 3 mounts meantioned by Phoenix, could it not be added to the Dread Raven? Because it clearly has the same "Mount changes depending on your riding skill and location" as the other three mounts so it counts as the same, and the other 3 mounts do work as intended, so that aspect is already implemented on our server.
But like I said, I don't have much of a clue about the coding part of this mount particularity and it could be ''deeply encoded'' into the mount and not easy to replicate to others.
But the Dread Raven is definatly a mount with this same aspect as this link proves (https://www.wowhead.com/item=109013/reins-of-the-dread-raven#teaches-ability) and the aspect is implemented in this server as I've seen at least 2 of those 3 mounts Phoenix meantioned being used in non-flying area's.
