### ISSUE TITLE
[Instance] Trial of the Champion

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#2862]
New bugs again. Yes it broke recently. (It worked fine for at least 2days after last fix release)

1) Grand champions auto attacking while mounted
**How it should work:** During mounted encounter, both players and their enemies can only use their mount's abilities, namely Thrust, Shield-breaker, Defend and Charge. No white melee attacks should be happening.
**How it works atm:** All three bosses steadily auto-attack while fighting on their mounts, for approx 3-4k damage EACH against a player mount. While this is somewhat mitigated by the stacks from Defend, as these auto attacks aren't on the generic cooldown of mounted abilities, as soon as you allow the NPCs to use charge or shield-breaker, it becomes able to one or twoshot your group members (you have no chance to reshield before they melee you to death). It's an extreme advantage to the bosses that can easily wipe most dungeon groups.

2) Wiping after dismount
**How it should work:** Once you are done with the mounted combat ("jousting"), the champions will run to their places as regular bosses. They're normally auto-engaged in a few seconds, but if you wipe or exit the instance, you can "reset" them to be pullable to properly start the encounter.
**How it works atm:** If you defeat the mounted fight and then wipe against the dismounted bosses, or exit the dungeon to prevent the auto engage, the encounter won't properly reset. When you re-enter, you find the bosses still standing there but they're unattackable.

http://www.wowhead.com/trial-of-the-champion
http://www.wowhead.com/npc=34702/ambrose-boltspark
http://www.wowhead.com/npc=34701/colosos
http://www.wowhead.com/npc=34657/jaelyne-evensong
http://www.wowhead.com/npc=34703/lana-stouthammer
http://www.wowhead.com/npc=34705/marshal-jacob-alerius
http://www.wowhead.com/npc=35617/deathstalker-visceri
http://www.wowhead.com/npc=35572/mokra-the-skullcrusher
http://www.wowhead.com/npc=35571/runok-wildmane
http://www.wowhead.com/npc=35570/zultore

**Comment by TenmanWoW** [comment]
Supporting SS's
![wowscrnshot_111218_212809](https://user-images.githubusercontent.com/25806987/48881941-8c2b3f80-eddd-11e8-85c0-daddf8b13eed.jpg)
![wowscrnshot_111218_212437](https://user-images.githubusercontent.com/25806987/48881942-8c2b3f80-eddd-11e8-8544-670d26e61fb3.jpg)

**Comment by TenmanWoW** [comment]
With this SS, it appears the minimum range for an NPC charge is null. The last thrust killed my mount and then I iceblocked to get the screenshot and I barely got the spell off before I got hit with another charge from the same NPC.
![wowscrnshot_111418_120442](https://user-images.githubusercontent.com/25806987/48881999-c0066500-eddd-11e8-8c58-d07b8006146d.jpg)

**Comment by Dranah** [comment]
Now it totally broke, when you start event, immediately all waves spawn and aggro, also the champions but they aren't mounted. All npcs are unattackable and they murder you real quick.

**Comment by Keader** [comment]
Try now @Dranah

**Comment by squalllh1989** [comment]
Not fixed, the problem of melee hit still persis

![wowscrnshot_112518_231222](https://user-images.githubusercontent.com/27235989/48981412-b8a9c900-f107-11e8-98ea-337b5155ecea.jpg)

How ever, after wipe, the reset is now work properly.

**Comment by Keader** [comment]
@Dranah / @squalllh1989 Test now

**Comment by Dranah** [comment]
UPDATE:
- Champions no longer melee while mounted (fixed)
- Once the jousting is complete, you can now reset the fight properly with the three dismounted champions, they are now attackable (fixed)
- There is a visual issue with the mounted groups no longer "lining up" like they used to. Instead they are all stacked up on top of each other like my multibox alts (tweaking)

**Comment by Dranah** [comment]
UPDATE:
Visual issue fixed.

After my last tests, I can confirm that the NPCs charge has incorrect cooldown.
It appears to run on the ~1,5sec general cooldown that Thrust and Shield Breaker has, while it should have 4,5sec cooldown.

**Comment by Keader** [comment]
and now @Dranah ? 😡

**Comment by Dranah** [comment]
They appear to charge less frequently now. I'd say it's around 4sec cd atm. Good enough i guess.
