### ISSUE TITLE
[General] Pets and teleporting

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#2863]
There is an issue that happens whenever you use a portal/translocation device that teleports you to a distant spot within the same zone and phase you are in. (Note, when you port to a different zone, or get phased to a different phase, the pet is properly transferred with you)
Typical and most important cases are 
- Frostmourne room on the LK encounter
- Brain room on the Yogg-Saron encounter

Both rooms are placed physically apart from the original encounter room, but in the same phase and close enough to not give you a loading (or zoning) screen. 

**How it works atm:** Whenever a pet class uses portal (or gets sucked into frostmourne), their pets are left behind, and either despawn because of outrange or they begin to walk through a hundred yard of textures to catch up to their master.
At yogg, if you wait long enough, they'll pop up from the floor or fly in through the roof in the brainroom eventually, but when you port back before Madness hits, they stay behind again and you have to wait for them to walk a mile again. In the end, your pets spend about 85% of the fight just walking back and forth in the empty space of texture between the two areas, rendering them entirely useless.

The same thing happens also in outdoor quest zones where you teleport up to platforms in Eversong or Borean and such, and also in The Oculus when you use the portal to get from the first corridor to the first boss' platform. It's just, these have less dramatic consequences than losing your pet during raid fights.

**How it should work:** When the owner of pet uses a portal or translocation device, the pet should always be teleported together with them.

**Comment by squalllh1989** [comment]
The pet should be teleported together with it's owner, in some fight the pet just lost completely when teleported, for hunter you can just call pet again since it's a instant cast, but for class like warlock, who need to stand still to cast the long time channel pet calling spell, they having bad time, like example being a demo warlock in lich king hc fight, have to call pet again each time get out of frostmoure room, to be able to buff the whole raid with their pet

**Comment by squalllh1989** [comment]
And it's even worse if they traveling, as to fix that you have to dimiss the pet and call it again, if it's too far from you, the dismiss doesn't even work.

**Comment by Keader** [comment]
I cant do it generical @Dranah.
But, i  put exceptions for The Oculus, ICC, and Ulduar.
It's caused by distance, need have more distance to pet teleport.
Anyway, in ICC/ULDUAR/OCULUS it will always teleport now.

**Comment by Dranah** [comment]
Tested those three instances, they work fine now. I suppose the outdoor objects aren't much of a matter anyway.
