### ISSUE TITLE
[NPC]Ray'ma

### ISSUE THREAD

**Issue by gamer100** [WoWManiaUK/Redemption#2864]
http://www.wow-mania.com/armory/?npc=27489
Npc is missing in orgrimmar. Target the  npc  did not  work.
the Npc is needed for archievment
http://www.wow-mania.com/armory/?achievement=2796

**Comment by squalllh1989** [comment]
Confirmed, the NPC should be at the red mark in my screenshot (he is there at the brewfest event to provide player the monthly brew for the achivement, but no longer there now, so it's imposible to do the achivement now)
![wowscrnshot_112318_120538](https://user-images.githubusercontent.com/27235989/48929144-5c348700-ef18-11e8-81e0-d5abd877649e.jpg)

**Comment by squalllh1989** [comment]
Also can we fix this quickly, i need the npc too for this month's brew :D, i think it should be the a event flag for the npc.

**Comment by wow-mania** [comment]
THe NPC is there just fell through the texture. Will come back after restart.
