### ISSUE TITLE
(Spell) Death Knight raise dead(ghoul)

### ISSUE THREAD

**Issue by HotBoxMcgea** [WoWManiaUK/Redemption#2865]
My raise dead skill is not working and is all shaded out, and every time i go to use the spell it tells me the spell isnt ready yet.

**Comment by squalllh1989** [comment]
Please read what the spell say, it has requirement to be able to cast, you didn't meet it requirement so you can't use the spell, not that the spell is bugged.
Here is the screenshot prove that it work, i just test it in redeemtion
![wowscrnshot_112318_115818](https://user-images.githubusercontent.com/27235989/48929049-90f40e80-ef17-11e8-8ebc-0d08217322f1.jpg)
![wowscrnshot_112318_115827](https://user-images.githubusercontent.com/27235989/48929022-568a7180-ef17-11e8-95c0-e2cece561f26.jpg)
In case you still have doubt, i marked the requirement said in the spell with red line, and if you don't want to bother about have the material to cast your spell, you can get your glyph:
![wowscrnshot_112318_120337](https://user-images.githubusercontent.com/27235989/48929084-d1ec2300-ef17-11e8-80aa-29fbe62064fb.jpg)

**Comment by Dranah** [comment]
This bug can sporadically happen sometimes the skill gets stuck on cooldown. Simple relog fixes it.
