### ISSUE TITLE
Warlock Pet is misbehaving

### ISSUE THREAD

**Issue by GM-Gathios** [WoWManiaUK/Redemption#2866]
When my Warlock's pet is on Defensive, every time after a combat it wanders of in a random direction, pulling a number of nearby enemies. When put back on Passive it walks back to the caster's location.

I've seen this behavior with a Fel Hunter and  Felguard and being in Dragonblight.

**Comment by Keader** [comment]
???

**Comment by Druhl** [comment]
I experienced this once on my Affli Warlock using a Voidwalker, 7 or 10 days ago, in Hellfire Peninsula while doing the quest [Felspark Ravine]. Though pet was in Defensive mode, after killing a mob I'd aggro'd and it had joined in on, it self-selected a new target and travelled to it and pulled it by itself. This particular behaviour I've not seen before or since, just this one time.

**Comment by Dranah** [comment]
I cannot reproduce this.

**Comment by Druhl** [comment]
By complete coincidence, I just experienced this again on the same alt a couple hours ago - around Warsong Hold in Borean Tundra, while doing the quest [Taken By The Scourge].

Double-checked pet was definitely set Defensive, but same bugged behaviour as above. Clicking him to Aggressive then Defensive again did seem to reset it / fix it however.

**Comment by squalllh1989** [comment]
Can you put it a more specific location / mob that do this ? normally this aren't happen, maybe there is some problem with pathing or group agro / patrol agro something like that happen. If you are in that case, if you didn't have your pet, the agro will just reset and you get out of combat, even not gonna relize that you just get in some random agro, but, if you have a pet, your pet will go attack that mob to defense you again those agro.
Well all of those are just my thinking, the actually situation maybe different, so we actually want a place to reproduce this, as we can't run all arround the world trying to reproduce this :)

**Comment by GM-Gathios** [comment]
It happened to me in Dragonblight Wintergarde Keep while doing the Geist quest. Both Fel Hunter and Felguard had the same behaviour on the same location. But since this also happened in Borean Tundra, reported by Druhl, I doubt it's a location error.

When the mob was down I saw my state change into 'not in combat'. The pet simply run in a random location and kept running whilst having some pulled enemies running after him. When I changed pet from Defensive to Passive mode it immediately headed towards my location giving me a challenge to kill the amount of mobs he had following him.

**Comment by Dranah** [comment]
Is it possible that a nearby caster/ranged mob was in pull range of your pet?
In that case, the mob is only in combat with the pet, not its master, and the pet will automatically go attack it once his current target is dead.

**Comment by GM-Gathios** [comment]
No, as I've said it wandered of in a random direction. While doing so it pulled. When combat ended my pet was nowhere near a enemy.

**Comment by squalllh1989** [comment]
well we really need a clue to this to be able to test and give dev an idea how to fix

**Comment by Dranah** [comment]
To me it sounds like a random glitch. Unless someone can figure how to reproduce it, there is no chance to fix.
