### ISSUE TITLE
[Item/Proc] Eye of the Broodmother

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#2867]
http://www.wow-mania.com/armory/?item=45308

How it should work:
As the description says, the trinket should proc when you CAST a damaging or healing spell = on spellcast.

How it works atm:
The trinket only procs on direct damage or healing LANDED on targets. 
It does not stack when you apply dots or hots, does not stack when you cast mind flay, drain soul, or drain life, does not stack off holy nova if the nova only does healing. There is probably more but i've only tested these so far.

Overall this means the proc is awful for shadow priests and afflocks and this is not intended.

**Comment by Keader** [comment]
Test now

**Comment by squalllh1989** [comment]
Worked

**Comment by Dranah** [comment]
You didn't actually fix it, simply made DOT ticks also proc it... well, good workaround, but need to be applied also to channeled spells then.
Mind flay, Drain Life and Drain soul still cannot proc it anyhow.

**Comment by Keader** [comment]
wow mania core do not support proc on cast

**Comment by Dranah** [comment]
DFO is capable of proccing off Mind Flay. Not sure if the cast or the ticks, but it procs.

Also, Illustration of the Dragon Soul http://www.wow-mania.com/armory/?item=40432 trinket requires same fix. Cannot proc off Mind flay, HoTs or holy nova healing currently.

**Comment by Keader** [comment]
try now

**Comment by Dranah** [comment]
Well, this workaround is good. Now they can proc off channeled ticks, HOT ticks and holy nova as well.
