### ISSUE TITLE
[Item/Proc] Nightslayer Armor (T1)

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#2868]
https://www.wowhead.com/item-set=204/nightslayer-armor

8piece bonus isn't working.
How it should work: when the rogue uses vanish, he should be healed for 500.
How it works: the heal is missing.

I suppose this could bother only some twink alts so I set it to tweaking.

**Comment by squalllh1989** [comment]
The heal is working, but for 600 instead of 500, should be gôd enough

**Comment by Dranah** [comment]
It heals for 500 as intended, you must have something that increases your healing taken.

**Comment by squalllh1989** [comment]
well i don't think so, tested on a level 80 fresh rogue with only the set equipt, with a .learn all my spell command, maybe it make the character learn something that increase healing ? not sure about that tho
