### ISSUE TITLE
[Spell] Spell Reflection / Shroud of Runes

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#2869]
https://www.wowhead.com/npc=26794/ormorok-the-tree-shaper
https://www.wowhead.com/spell=47981/spell-reflection

How it should work: Spell Reflection has 4 charges and each reflected spell should consume one. This means after 4 spells are reflected, the effect is removed, no matter how much duration it has left.

How it works atm: Spell reflection reflects infinite number of spells cast over its duration, because its charges aren't removed when a spell is reflected.

**Comment by Dranah** [comment]
UPDATE:
I found that this may be a general issue with mob reflect abilities.
Shroud of Runes https://www.wowhead.com/spell=69056/shroud-of-runes cast by https://www.wowhead.com/npc=36478/soulguard-watchman in Forge of Souls trash also behaves the same way, does not lose charges when it reflects an ability, so you have to wait for the full duration to run out.

**Comment by Keader** [comment]
Fixed Dranah.
Both was not proccing xD

**Comment by squalllh1989** [comment]
so it's work like a run out of time buff instead of a consume one >.<, yeah i see this a lot too as farm those instant a lot, alway forget to report those anoying thing

**Comment by squalllh1989** [comment]
Fixed in dev.
