### ISSUE TITLE
[Spell] Lifebinder's Gift (Freya)

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#2871]
https://www.wowhead.com/npc=32906/freya
This is the healing cast by Eonar's Gift (the growing trees) on the Freya encounter.

On 10man, this effect is supposed to heal for 30% of NPCs health, via this spell http://www.wow-mania.com/armory/?spell=62584

On 25man, it's supposed to heal for 60% of NPCs health, via this spell http://www.wow-mania.com/armory/?spell=64185

I suspect the wrong ID is used on 10man currently, because the tree heals for 60% on 10man too. This is not intended, it should only heal for 30% (past a heal reduce is only 15% which can be easily ignored by melee-heavy groups)

**Comment by Keader** [comment]
Well, was missing 25 man spell.
It was casting 10 man spell in 10 and 25 man '-'

**Comment by Dranah** [comment]
Nope, it was missing 10man spell. It was casting 25man spell (60%) on both difficulties. And it still is. Except now on 25man the healing is cast twice... so 120% total.

It must heal 30% on 10man and 60% on 25man. I linked you both corresponding spells.
