### ISSUE TITLE
[Spell] Hemorrhage

### ISSUE THREAD

**Issue by Ashamedlol** [WoWManiaUK/Redemption#2872]
Issue: Hemorrhage is not affecting bleed spells (Rupture + Garrote mainly, Rend, Deep Wounds and Rake+Rip possibly) seeing as it says ANY physical damage done.

![rup](https://user-images.githubusercontent.com/16576459/48989725-34216f80-f134-11e8-9c4c-4309ac3901b9.png)

While it can benefit bleeds, stacks should not be consumed when bleed effect ticks in (This part is working, it's not consuming): 
Patch 1.11.0 (20-Jun-2006): Your damage over time effects will no longer consume charges of Hemorrhage.
S: http://wowwiki.wikia.com/wiki/Hemorrhage

Spell IDs: http://www.wow-mania.com/armory/?search=Hemorrhage#abilities

**Comment by Keader** [comment]
![image](https://user-images.githubusercontent.com/7120913/49335078-c4443680-f5c4-11e8-9466-4e811efc7ea0.png)

https://wow.gamepedia.com/Rupture

The  [Hemorrhage] ability will not add damage to Rupture (or any other DoT).

Not a bug
