### ISSUE TITLE
[NPC] Saronite Animus

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#2873]
https://www.wowhead.com/npc=33271/general-vezax
https://www.wowhead.com/npc=33524/saronite-animus

This is the add spawned by General Vezax on hard mode.
There are 2 major problems:

1) His hitbox is awfully small. This just can't be intended. He is nearly same size as Vezax himself, but to get in range of the add, the RDPS needs to move closer in by at least 10 yards (from the position where they can easily reach vezax, who stands right on top of the add). And for the melee, even inside his "red circle" you can barely touch him, you need to stand right under his head in the center.

2) Timers are off
How it should work: 
A total of 6 Saronite Vapors spawn, every 30seconds. This can be off by 1 seconds, max 2, but never more based on retail videos. This means the 6th vapor spawns around the 3rd minute, somewhere at the 3:00-3:10 time range. The Saronite Animus spawns 1-2 seconds after the 6th vapor. This matches the DBM timer as well (~3:08)
How it works:
A total of 6 Saronite Vapors spawn, with varying intervals. They never come at the intended 30 sec, shortest i've seen was 34sec between two, but it can go up to 42sec. This all adds up and delays the spawn of the animus by well over half a minute. Usually he spawns around 3:40-3:50, delaying the fight by quite a bit. It makes DBM timers useless too.

PS: The add also appears to be stunnable atm i'm still trying to research if its intended but it's probably not.

**Comment by Dranah** [comment]
This got totally cucked. Now every time a vapor would be due to spawn, it spawns a whole Saronite animus and vezax gets shielded.

**Comment by Dranah** [comment]
Hitbox feels slightly better. Timers have been reverted to previous state where the vapors come at average 36sec and the Saronite Animus is half a minute late. Still need fix.

**Comment by wow-mania** [comment]
Timers are exactly at 30 there is absolutely nothing even close to 36 in the entire boss.

**Comment by wow-mania** [comment]
Try now.

**Comment by Dranah** [comment]
UPDATE:
The 30sec timers now work as intended, the vapors spawn in order.
There is only one problem with the timer now. On blizz, when the 6th vapor spawns, the raid gets a message:
"The Saronite Vapors mass and swirl violently, merging into a monstrous form!"
And about 3sec later the Animus pops up.
Here, the warning message is missing and he pops up right away with the 6th vapor and this means he's about 4sec early.

https://www.youtube.com/watch?v=B5Wvusf8Nfc here is tankspot vid for reference:
3:37 6th Vapor spawn
3:38 raid message of merging
3:41 Saronite Animus spawns and Vezax gains his bubble

**Comment by wow-mania** [comment]
Updated.

**Comment by Dranah** [comment]
Almost good, the message now appears and the Animus spawns on time after.
However, Vezax must also be shielded the same moment Animus spawns, not 4sec earlier when the message pops.

**Comment by wow-mania** [comment]
Try now.

**Comment by Dranah** [comment]
This is broken again, seems reverted. Probably also broke with the update in the beginning of feb (which broke everything else too). You can keep saying you didn't touch anything, but I don't believe you >.>

**Comment by wow-mania** [comment]
Absolutely nothing changed here.

**Comment by Dranah** [comment]
The timer for Saronite Vapors is still wrong (avg 35-38sec between spawns), resulting in the saronite animus being still ~40sec late. The cast is probably delayed by something (as it was when Jani was fixing it).
There is no merge message when the 6th vapor spawns (i'm not sure it spawns at all, but perhaps i just couldnt see where, since there was no announcement - this also makes it impossible to determine if the delay between 6th spawn and animus is there or not), the animus and the bubble just happens out of nowhere. The message for vezax bubbling is present though.

**Comment by Dranah** [comment]
UPDATE:
- Timer is no longer delayed, vapors spawn every 30sec. (fixed)
- The announcement for vapor spawn is still missing for the 5th and 6th, and the 6th vapor doesn't spawn at all (no announcement and i can't find it physically anywhere) - need fix
- The merge announcement "The Saronite Vapors mass and swirl violently, merging into a monstrous form!" is still missing, the saronite animus just spawns out of nowhere (need fix)
- There seems to be a delay between the shield and the animus spawning (2-3sec), which is not intended, these two events should happen at same time. (need fix)
- The delay should be between the 6 vapors merging and the animus spawn, however this cannot be tested atm since there is no 6th vapor spawn. (need fix)
- When the Saronite animus is killed, there should be a message "The saronite barrier protecting General Vezax shimmers and fades away!"

**Comment by Keader** [comment]
and now?

**Comment by Dranah** [comment]
Almost perfect.
- 5th and 6th vapor are now properly announced and spawned (fixed)
- The announcements are added to the events (vezax shielding, animus spawn, vezax losing shield) - fixed
- Vezax now shields only when the Animus spawns (fixed)
The delays between 6th vapor, the merge and the spawn of animus needs a minor correction (I may not have provided enough details for this in my previous post).
**How it should work:**
If 
t=0 is when the 6th vapor spawns, then
t=5 is when the merge announcement "The Saronite Vapors mass and swirl violently, merging into a monstrous form!" happens
(between the two events, the vapors should be visibly rushing towards vezax, but this is a cosmetic issue i am willing to ignore)
t=8 is when the Animus actually spawns and vezax shields with the announcement "A saronite barrier appears around General Vezax!"

**How it works atm:**
The 5sec delay between 6th vapor and the merge is missing. (need fix)
The visual effect of the vapors gathering under vezax and swirling is missing (tweaking, cosmetic)
Currently t=0 is when 6th vapor spawn and the merge announcement is made
t=3 the saronite animus spawns and vezax shields
This leads to the Animus spawning 5sec early and the timer not being accurate.

**Comment by Keader** [comment]
Try now...

**Comment by Dranah** [comment]
Timers all good now. Announcements on spot.
However... saronite animus went missing. Vezax shields but no add spawn. Need fix

**Comment by Keader** [comment]
Test now

**Comment by wow-mania** [comment]
Can I close this one now?

**Comment by Keader** [comment]
I fixed last issue last night xD

**Comment by Dranah** [comment]
Animus is back
All good now
