### ISSUE TITLE
[Quest] The Way to His Heart...

### ISSUE THREAD

**Issue by GM-Gathios** [WoWManiaUK/Redemption#2874]
http://wow-mania.com/armory/?quest=11472

For this quest you'll receive a  Anuniaq's Net (http://wow-mania.com/armory/?item=40946) so you can fish up Tasty Reef Fish (http://wow-mania.com/armory/?item=34127) from school's in the river and throw these fishes to a Reef Bull (http://wow-mania.com/armory/?npc=24786) to lure it to a Reef Cow  (http://wow-mania.com/armory/?npc=24797)

Issue: No schools are present.

**Comment by wow-mania** [comment]
Have you tried to fish?

**Comment by wow-mania** [comment]
![image](https://user-images.githubusercontent.com/12248683/49147322-4d751800-f2fc-11e8-9b95-077713ffd235.png)

Please be more thorough before rushing to open issues.

**Comment by GM-Gathios** [comment]
Sorry for the late response. No, I haven't tried to fish since it shouldn't be needed to complete this quest. How can I be more thorough when there where no schools at that time :P
I did, however, wait a fair time to test if the school would respawn.
