### ISSUE TITLE
[Pet] Corehound and BW

### ISSUE THREAD

**Issue by crulinjr** [WoWManiaUK/Redemption#2875]
How it is working:
So the pet Corehound its really buggy sometimes it does some weird paths specially on arena when sometimes the opponent is on the boxes but the pet tries to go down the stair and goes back and forth without actually achiveving something.  His ability named Lava breath has a 30 yard range but if you try to put it on a macro or try to only use that ability the pet will run melee then use the ability which should not be the case.  His size is not accurate and also his range (maybe its because his size does not represent the actual size of the pet and it looks like he is hitting from range).

How it should work: 
![cotstrat-hunterpetcoolness](https://user-images.githubusercontent.com/40045543/49179552-82936180-f320-11e8-9c34-d32918926249.jpg)
 This is the proper size of the corehound. Fixing his size will lead to fixing his pathing and range. Lava Breath should be able to be casted using macros from 30 yards away from the target (focus macros are not working atm cause of this).

**Comment by zonefrost** [comment]
> 
> 
> There is no such a thing as a specific pet being bugged.
> Also, size is as per Blizzard. There was no change to its size.
> Please give specific step to reproduce the issue or we can't do anything about it.

the sizes are absolutely NOT blizzlike, so many pets are way smaller than they should be, notably corehounds and devilsaurs. I remember corehounds being up to about shoulder height for a night elf, now they're knee high... if there's nothing that can be done then that's that.

**Comment by wow-mania** [comment]
The size itself has nothing to do with a possible problem. I will check if there is an issue with range

**Comment by crulinjr** [comment]
What i meant is that since he is smaller than he should i looks like he is hitting from further or that he should be on range but he is not. Updating his size will make things better. Also the pathing issue may be a core problem from the server. Like for example, while in Blade's Edge Arena if i stand on one of the pillars next to the bridge and my opponent is just down from me and i send my pet to attack, my pet will stand next to me trying to attack my opponent and do nothing instead of going down the bridge. It have something to do with lava breath beign 30 yards range.

**Comment by wow-mania** [comment]
Can you send me the id of the pet please

**Comment by crulinjr** [comment]
Please dont close it yet since we dont have a solution

**Comment by wow-mania** [comment]
So provide info requested and don use images from other servers.

**Comment by crulinjr** [comment]
yeah it was too early in the morning for me i was sleeping. I will 1 sec lf
the info


El 1 dic. 2018 12:10 p. m., "Bgil20" <alvaro.vigil90@gmail.com> escribió:

Please dont close it yet since we dont have a solution

**Comment by wow-mania** [comment]
I checked the pet and it has the correct size.
![image](https://user-images.githubusercontent.com/12248683/49331034-ef139800-f58e-11e8-8bef-2a57872033d7.png)

**Comment by crulinjr** [comment]
Is that from wow mania? cause mine is not that size

**Comment by crulinjr** [comment]
And every corehound and devilsaur i see are not the size they should be.

**Comment by wow-mania** [comment]
Of course, it is wow-mania. :) 
Dude, why would I log into another server?
Are you using our client? Is it fully up to date? Send me a screenshot of the login screen and of the pet. Or is it that hard? You should have done that from the start instead of taking the time to send a picture from another server.
Also, send me your character name.

**Comment by crulinjr** [comment]
Im sending 3 different pictures now from different ppl from my guild. They
all have the game at the lastest patch and use the client (me aswell). The
pics i sent were from retail wotlk. I even sent the wow head link to it. My
character name is Braindeadly and ill sent the login screen picture. 1 sec

**Comment by crulinjr** [comment]
Jimboslice PoV:
https://media.discordapp.net/attachments/505127643843133462/518482172693184522/unknown.png?width=832&height=468

Medousa PoV:
https://media.discordapp.net/attachments/483075005416996874/518482474288939008/WoWScrnShot_120118_194326.jpg?width=749&height=469

Briecookie PoV:
https://media.discordapp.net/attachments/508446034226315264/518480895271895050/unknown.png?width=832&height=468

Im uploading the logging screen photo:

**Comment by Dranah** [comment]
I can confirm Core Hounds are indeed not the size as on your screenshot @wow-mania 
I don't know for what reason, but in game it is really really small, while on the character page it appears normal.
Login scrn: https://imgur.com/neojrhB
Ingame: https://imgur.com/280txlM

You can spot the difference.

**Comment by crulinjr** [comment]
Btw yesterday i was on Dalaran arena and i jumped from the boxes to the
lower side of the arena. My opponent followed me while my Corehound pet
stood there near the boxes trying to go down the stairs then went back to
the boxes over and over. I had to command follow then command attack again
for him to be able to come down and attack my target.

**Comment by wow-mania** [comment]
This will require a client update. It's visual only. No connection with in-game issues.

**Comment by crulinjr** [comment]
That would be amazing. It will actually help gameplay and to further verify
some pathing problems. It will help testing.

**Comment by wow-mania** [comment]
Size fixed but it will require client update.
This will probably be pushed in January only now.
