### ISSUE TITLE
[Talent] Owl's Focus

### ISSUE THREAD

**Issue by Ashamedlol** [WoWManiaUK/Redemption#2876]
Talent is only being consumed if the spell cast was Bite, it's not being consumed when Dash or Growl are cast.

It's also being consumed on the usage of the Wolverine Bite spell, which is supposed to cost 0 Focus.

Talent IDs: http://www.wow-mania.com/armory/?search=%09+Owl%27s+Focus

**Comment by Keader** [comment]
It should proc in next spell, even if that spell dont have focus cost.
Fixed proc with Dash and Growl
