### ISSUE TITLE
Nitro Boost from Engineering

### ISSUE THREAD

**Issue by Grimjaw1** [WoWManiaUK/Redemption#2878]
Hello i use Nitro Boost to my boots from engineering but i take only the active effect.The +24 critical doesnt exists.http://www.wow-mania.com/armory/?spell=55016. Same problem have other players too.Thanks!

**Comment by Thrashattack** [comment]
The bonus isn't displayed on the tooltip of the item enchancement, but is displayed on the item craft screen. 
You can proof that it works by watching the critical value change while you trinker your boots.
