### ISSUE TITLE
[Quest] Throwing Down

### ISSUE THREAD

**Issue by GM-Kratos** [WoWManiaUK/Redemption#2880]
You are supposed to hand in the Quest Throwing Down(http://wow-mania.com/armory/?quest=12598) to Captain Rupert(http://wow-mania.com/armory/?npc=28044), however if you have accepted/completed/ the quest Pure Evil(http://wow-mania.com/armory/?quest=12584) you are not able to speak with the NPC to hand in the quest

This is how it looks if you have not done Pure Evil and is going to hand in Throwing Down
![image](https://user-images.githubusercontent.com/43315225/49303132-418a8100-f4c9-11e8-807a-6016aa955b01.png)

However now when I have accepted the quest I am not able to interact with Captain Rupert to hand in Throwing Down
![image](https://user-images.githubusercontent.com/43315225/49303208-67178a80-f4c9-11e8-9c17-e2eba34bb4ca.png)

And when Pure Evil is Rewarded I still cannot speak with Captain Rupert to hand in Throwing Down.
![image](https://user-images.githubusercontent.com/43315225/49303300-a9d96280-f4c9-11e8-983b-b68af0564f0e.png)

I have tried to reset the NPC, going out from GM and invisible, but still the same issue.

**Comment by wow-mania** [comment]
All works fine.
Please double check and use a non-gm character to do the quests in the intended order. This is the second issue in a row that is invalid.

![image](https://user-images.githubusercontent.com/12248683/49305001-d8553e80-f4c5-11e8-8b0b-fec694f7d1de.png)


![image](https://user-images.githubusercontent.com/12248683/49304976-c5db0500-f4c5-11e8-96a3-aaa823bb912f.png)

**Comment by jarvik76** [comment]
This is definitely a problem, I have repeated the above process with the same results - "Throwing Down" is still in my quest log and I cannot turn in, as I am not able to speak to Captain Rupert.  No ? marker, and NPC is unresponsive.
No addons, launcher used, patch 2.5.0 updated, cache deleted.   (Character "Jeyrella")
![wowscrnshot_122318_160216](https://user-images.githubusercontent.com/46089380/50385421-33491280-06cd-11e9-8050-846c26e9f0c1.jpg)

(I did "Pure Evil" out of order, because of issue 2993 - that one is I think still valid, I will post there too)

**Comment by TenmanWoW** [comment]
I have obtained and completed Pure Evil.

I gave myself "Throwing down" and completed it. Captain Rupert's state is unchanged.
![wowscrnshot_122318_102958](https://user-images.githubusercontent.com/25806987/50385727-c3706300-069f-11e9-9bd7-21f17840e139.jpg)
![wowscrnshot_122318_103304](https://user-images.githubusercontent.com/25806987/50385728-c408f980-069f-11e9-9fc5-550e6eb4fc1e.jpg)
![wowscrnshot_122318_104258](https://user-images.githubusercontent.com/25806987/50385729-c408f980-069f-11e9-994e-9a08fa33e993.jpg)

**Comment by wow-mania** [comment]
Do not use any GM power to do depended or required quests. 
Quest works.
I have just done it once again (second time now).
