### ISSUE TITLE
[Spell] Mind Control

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#2882]
http://www.wow-mania.com/armory/?spell=605

The MC spell consists of 2 parts within the same spell ID - one is a 3sec cast time cast and 20 yard range, the other is a channeled aura applied by this cast, which can last up to 1minute and has 100 yard range.
Several issues with these, on top of the core issue with charmed creatures' auto attacks.

1) Spellcast being interrupted/overridden by any keys the priest hits while casting
This could be related to the fact the whole thing is labeled wrongfully as one "channeled" ability on our armory, instead of a cast time spell with a channeled aura effect.
**How it works:** The 3sec cast part behaves pretty much as if it was a channel, so that if you attempt to cast another spell while it's casting, the cast will stop and the new spell begins casting. However, even the [nochanneling] command does not save it from being interrupted by literally everything, like for regular channels.
**How it should work:** The 3sec spellcast part should behave like regular cast-time spells, not interrupted unless you jump, hit escape or do /stopcasting (or an enemy casts an interrupt on you).

2) Aura applied wrongly, causing instant break of range issue
**How it works**: When the MC lands, the target sometimes receives his 1minute debuff as intended, sometimes not, but what's more important, the priest receives a 10second buff which appears to respond to diminishing returns (duration shortens with each cast, and after 3 MC casts, you no longer receive it but pops a message "immune"). 
During this 10sec buff, the MC spell is breaking way too easily, as it appears to be still checking for 20 yard range like the original cast, instead of 100yards that the channeled aura should have. Any little movement away from the priest (who typically stands on the edge of the cast range when trying to MC a distant mob) instantly breaks the effect. Heavy loss of functionality here.
However, if you manage to keep the mob MC'd until this 10sec aura wears off, the spell stops checking for ANY kind of range, you can run from Stormwind to Redridge with the charmed creature and the spell will NEVER break.
**How it should work:** When the MC lands, both the priest and the target creature should receive a matching duration effect (10sec in PVP, 1minute in PVE).
The priest who is channeling the effect, can right-click or cancelaura the buff effect in order to break the MC whenever they want. The target gets it as a magic debuff, which can be dispelled. This channeled effect should check for 100 yard range from the priest at all times, instantly breaking if the target is moved further than that.

3) Exit vehicle option missing / Can't break MC
Once the 3sec cast completes and the 10sec duration aura on priest wears off, it becomes impossible to end the MC effect by the priest's will.
**How it should work:** There should be 4 ways to break MC voluntarily by the priest
- Casting something: the channeled aura should behave like regular channels, interrupted by any cast the priest attempts to perform (unless they are macroed with [nochanneling])
- The priest should have a buff that matches the debuff duration on target, which they can right click or cancelaura with a macro
- The priest should have an "Exit Vehicle" option on the altered action bar they receive when mind controlling a player or creature
- Moving the target further than the 100 yard max range (see issue 2.)
**How it works atm:** None of the listed options work, there is no exit vehicle option, range check does not work after the 10sec buff is gone and with no buff on you, there is nothing you can right click or cancel. The channel is non responsive to spells you attempt to cast.

4) Range checks
MC on retail has a behavior that it performs a random break chance calculation every X seconds over its 1minute duration. This break chance depends on target's shadow resist, level difference between caster and target and also the range/distance between caster and target.
More info here: http://wowwiki.wikia.com/wiki/Mind_Control
This kind of random break is fully missing right now.
Not a big loss due to bug no.2 which breaks the spell instantly in most cases anyway, but if that got fixed, we would want this implemented too.

**Comment by Keader** [comment]
Bug 1 is not a bug.
And spell need be interrupted by
![image](https://user-images.githubusercontent.com/7120913/49329061-9de8b180-f558-11e8-99c2-bad417fe7f59.png)

**Comment by Dranah** [comment]
Yes it is, the original cast is not meant to behave like a channel, only the channel effect it procs.
Also those interrupt flags clearly don't work, the priest is unable to activate any ability while mind controlling.

**Comment by Keader** [comment]
Well, looks like clientside issue, because server never get cast message when you charming a creature/player and try cast something else.
About debuff duration, is a deep core issue. I fixed but still will have some desync. In players, to priest will show 1 min and to controlled player will show the correct time.
But now, for creatures, will always work, and you cant go away of 100 yards

**Comment by Dranah** [comment]
Ok so,
1. If the cast spell is an intended channel, then it needs to be fixed to respond to [nochanneling]. It's either channeling or not channeling ,it cannot be halfway.
2. There is no change, the aura still only lasts 10sec also when controlling creatures. While you have the aura, you can cancelaura it or use the cancel option that seems to appear only on the default UI.
However when the 10sec aura expires, the channel is visually interrupted, you have no aura and nor /cancelaura, nor the default cancel option will work anymore.
3. @wow-mania can something be done about the clientside issue of not receiving cast message that should interrupt the MC?
4. Still able to run beyond 100 yard after aura is gone

**Comment by Dranah** [comment]
UPDATE:
- Spell now checks for proper 100 yard range (fixed)
- Aura is properly applied with 1 min duration to both the priest and the creature (fixed)
- Channel can now be cancelled with /cancelaura or the exit vehicle option (fixed)
- Spellcast being overridden by other spells is a blizzlike bug (as-is)
- Spellcast attempts while channeling do not go through from client to server, so cannot be fixed (as is)
