### ISSUE TITLE
[Spell] Eyes of the Beast

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#2883]
http://www.wow-mania.com/armory/?spell=1002

Found problems here too, on top of the already known auto attack bug.

1) Spellcast being interrupted/overridden by other casts
Same issue as with MC, the entire spell is labeled as "channeled" on our armory.
The original spellcast is a 2sec cast, not a channeled ability, and should not be interrupted and overridden by other spells the hunter presses while casting.

2) Aggro problem
When the Eyes of the Beast effect runs out or is cancelled, the pet threat values are fully reset for no reason.
How it should work: Threat generated by your pet should remain active when effect ends. Not only the threat gained while it was controlled, but also the threat it generated before you cast Eyes.
Right now the pet just gets all aggro reset and this makes it ill advised to use Eyes of the Beast with a tanking pet.

**Comment by Dranah** [comment]
How is it channeled when it's a 2sec cast time cast
That flag is just wrong

**Comment by Keader** [comment]
Test if agro problem is fixed.
Problem 1 is same of mind control

**Comment by Dranah** [comment]
Then, just like for MC, if its channeled, then it needs to respond to [nochanneling]. It cannot be that some parts of game consider it channel and others dont.

**Comment by Dranah** [comment]
- Spell no longer resets pet threat upon expire
- bug1 stays as-is, can't be helped
