### ISSUE TITLE
Character bug

### ISSUE THREAD

**Issue by Sypereth** [WoWManiaUK/Redemption#2884]
Hello!
I've recently switched launchers from WoW 3.3.5 to WoW Manias 2.4.1 and while everything else looks and feels better I found an character bug. It's hairstyle bug and I've noticed that character creation has that problem as it is since I tried various races and most of them has it. In short, some hairstyles are replaced with a bald head while others are like they are supposed to be.
Heres a picture of my character and how it looks on both launchers
![wowproblem](https://user-images.githubusercontent.com/45523292/49333595-d375b500-f5c1-11e8-835f-6417e85585b3.jpg)

Cheers and hope u guys can fix this !

**Comment by wow-mania** [comment]
Know issue. As-is for now.
