### ISSUE TITLE
Bug npc

### ISSUE THREAD

**Issue by Debastador** [WoWManiaUK/Redemption#2885]
Hi,i found a bug npc that cant talk to him for the quest:The Test of Righteousness the npc name is:Bailo Stonehand and he shout direct me where to get Jordan's Refined ore Shipment plz it needs fix ty in advance

**Comment by Dranah** [comment]
Just leaving these here
https://www.wowhead.com/npc=6241/
https://www.wowhead.com/quest=1654/the-test-of-righteousness
https://www.wowhead.com/quest=1655/bailors-ore-shipment

**Comment by wow-mania** [comment]
Fixed also applied to redemption.

**Comment by Debastador** [comment]
sorry the npc is not fix i try everything and nothing plz check again cant even get the item if i dont speak to him and i cant speak to him ty

**Comment by wow-mania** [comment]
Works.
![image](https://user-images.githubusercontent.com/12248683/49855372-f8013680-fde4-11e8-890e-0277134f79a7.png)
