### ISSUE TITLE
[Spell] Shadowmeld - Racial Night Elf

### ISSUE THREAD

**Issue by WhitephoenixTheBunny** [WoWManiaUK/Redemption#2887]
The Night Elf Racial [Shadowmeld](http://www.wow-mania.com/armory/?spell=58984#spell-link) flag the player to PvP when used **ONLY** on **Low Maps from Azeroth**

Kalimdor - Flagged
Eastern Kingdoms - Flagged
Outland - NOT Flagged
Northrend - NOT Flagged

**Comment by Dranah** [comment]
Confirmed, though it happens in specific areas within Kalimdor/EK.
It may have something to do with PVP guard NPCs nearby, in Elwynn it happens in and around Stormwind, along roads and towns, while distant spots near the river are not producing this bug.
I could also reproduce near Lakeshire in Redridge (but not in other parts of Redridge), and generally is not happening in higher level, contested zones.
Dun Morogh is also same as Elwynn, anywhere far away from towns and roads it does not bug, only near NPCs (agglomeration of roads and bases)

**Comment by Keader** [comment]
fixed

**Comment by Dranah** [comment]
Can't reproduce issue in Elwynn and Dun Morogh anymore. @WhitephoenixTheBunny feel free to check out more areas that you know of, but to me it seems good.
