### ISSUE TITLE
Patching issue

### ISSUE THREAD

**Issue by Sypereth** [WoWManiaUK/Redemption#2891]
Hello,
I'm using WoW-Mania Launcher but for some reason its not patching. I thought it was until today when I looked at the lower left corner and saw that it still says 2.4.0 instead 2.4.2 . 
Is there any way to manualy patch it or something I can do to fix this? 
Ty in advance!

**Comment by wow-mania** [comment]
This is not a server issue. Search forums and if still have a problem contact support.
