### ISSUE TITLE
[NPC] Justicar Mariel Trueheart & Crusader Rhydalla

### ISSUE THREAD

**Issue by Anthonhed** [WoWManiaUK/Redemption#2894]
Logging both under 1 issue since it is the same issue for both.

Once you have picked up a quest from either NPC's the ![image](https://user-images.githubusercontent.com/26274880/49649096-67170d80-fa28-11e8-8076-dd2f0fd43974.png) stays and does not turn into a Grey ?, When quest is completed the NPC does not have a Yellow ?
Once the NPC's has no more Quests to offer it still shows a ![image](https://user-images.githubusercontent.com/26274880/49649133-8ca41700-fa28-11e8-98af-cedb22d7aeb8.png) over both NPC's head.

Justicar Mariel Trueheart(http://wow-mania.com/armory/?npc=33817)
Crusader Rhydalla(http://wow-mania.com/armory/?npc=33417)

**Comment by wow-mania** [comment]
What quest are you talking about?
The ! does not go grey or turn into a ? because it does not end the quest.
Check on the map and you see where the ? is.
