### ISSUE TITLE
HC dungeon and raid lockout bug

### ISSUE THREAD

**Issue by Svinneh** [WoWManiaUK/Redemption#2895]
Whenever I complete a HC dungeon or kill a raid boss, I am locked out for two cycles (two days for HC dungeons and two weeks for raid bosses).
This issue applies to all max level characters on my account.
Example: Did ICC 10 man on Saturday 1st of December
Lockout expires on Thursday 13th of December 04:59
Account name: Andrudis

I have previously created a ticked about this, but was advised to log this as an issue here.

Please let me know if any additional information can help

**Comment by Svinneh** [comment]
![wowscrnshot_120718_233918](https://user-images.githubusercontent.com/45698561/49676298-6eb2d280-fa79-11e8-9c8e-6f6cc7d3369d.jpg)

**Comment by Keader** [comment]
This screen please:

![image](https://user-images.githubusercontent.com/7120913/49676383-4c5c8d00-fa58-11e8-91cd-6d5009e97891.png)

**Comment by Svinneh** [comment]
![wowscrnshot_120718_235409](https://user-images.githubusercontent.com/45698561/49676779-74111c80-fa7b-11e8-8906-332f0d5f38d9.jpg)
OK judging from this, it looks like a calendar display bug instead. Aw man! Does this mean I have wasted your time?

**Comment by Keader** [comment]
yeah, always trust in this interface, not in calendar.
Anyway is not waste of time 💃
