### ISSUE TITLE
[Spell] Light's Favor (Terenas Menethil II)

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#2896]
https://www.wowhead.com/spell=69382/lights-favor

This is the buff on the NPC inside Frostmourne https://www.wowhead.com/npc=36823/terenas-menethil
It is responsible for periodically healing him and scaling his damage with his health.

Problem: The conversion for damage appears wrong.

**How it should work:**
Based on retail videos, at around 50% health that Terenas starts with, he's hitting for ~15k damage.
Below 30% he's still hitting for about 11k.
Around 60% hp he's already hitting 17-18k
Over 70% is 20k-22k damage
Around 26-28k at 80%.
Fight never lasted long enough for him to be healed above that, he finishes the enemy warden so quick.

Video links: 
https://www.youtube.com/watch?v=9-5eyqpUDwI&feature=youtu.be&t=18s
https://www.youtube.com/watch?v=hu7iccUI1Ek

**How it works here:**
At 50% health, Terenas hits for 8-9k damage.
At 30% it is 7-8k
At 10% it is 6-7k
At 70% he does 9-10k
At max health 100% he still only hits for 10-11k

SS from mania with Terenas kept on full health with LOH spam (credits to Ashamed)
https://image.prntscr.com/image/cPOjRi-fRV_nWdIPc3ejfQ.png

Summary: 
If you compare, it appears the scaling with health is much weaker on mania, than on blizz, the NPC is half as strong as intended. Players spend more time inside Frostmourne than necessary and healers ported inside have a major disadvantage, since the value of their healing done to Terenas is incredibly low.

**Comment by Ashamedlol** [comment]
Additional Healer PoV: https://www.youtube.com/watch?v=D2qoHM_rEJ4 / https://www.youtube.com/watch?v=tmgrQrorJQA

**Comment by Dranah** [comment]
UPDATE:
Terenas is now hitting for more or less the intended amount at 50% health and below.
There are issues with scaling being too weak above 50%.
At 50% health 11-15k
At 30% health 9-12k.
At 20% health 8-10k.
At 10% health 7-8k.

Above 50%, his damage does not seem to increase much if at all. Ranges from 12-17k at around 70% and at maximum 100% health he can do 16-20k.
Need to increase scaling above 50%.

**Comment by Dranah** [comment]
Damage now matches retail numbers. At 90%+ health he can now hit for 28-30k damage.
