### ISSUE TITLE
Wintergrasp Battle - Flying and Entering

### ISSUE THREAD

**Issue by hAi777** [WoWManiaUK/Redemption#2899]
1. During a Wintergrasp Battle, players who died can release spirit, be ported to the graveyard, FLY back while DEAD to their corpse and ressurect. This is currently being used by some players to camp atop Sunken Ring building to cap the base and kill players, especially a warlock who can jump down and teleport back above the building.
How it should work: You are not supposed to be able to fly during a wintergrasp battle when you are dead.

2. During a Wintergrasp Battle, entering wintergrasp will pop a message asking whether you want to join the battle. Selecting "No" ports you to Ice Crown, otherwise "Yes" will join you to the raid group of your own faction and continue your agenda without getting ported. Leaving the raid group still enables you to participate in the battle.
How it should work: Flying in to the map and joining the wintergrasp battle and selecting "Yes" should port you to the starting point (In front of Fortress Entrance if you held WG, Alliance/Horde Graveyard if not) just like when joining WG battle from Dalaran. Leaving the raid should automatically kick you out from the WG battle and be ported to Ice Crown. The Raid Leader should not be able to kick Members from the Raid Group.

**Comment by wow-mania** [comment]
No and no. As-is.
