### ISSUE TITLE
Pets in Ring of valor

### ISSUE THREAD

**Issue by crulinjr** [WoWManiaUK/Redemption#2900]
So if you call your pet while on the elevator, the pet will bug when the arena start and it will do nothing. For Beastcleave this is bad cuse you want to rush down your opponent and if you lose 3, 4 with no Master's Call nor Bestial Wrath which is your main CDs for this comp you will certainly lose. I have tried to start pet less and calling but this unmounts you and the pet still sometimes bugs or you could get CCed before you use the ability cause you want to make sure the pet does not bug out. Hunters already have a lot of drawbacks in this arena but starting petless is a mayor handicap.

**Comment by Keader** [comment]
Nothing that i can do here.
Elevators has "no position" so creatures cant move above him, and spells with area effect cant work too.
I realy think that Ring of Valor should be closed.
