### ISSUE TITLE
[Talent] Entrapment - Frost Trap

### ISSUE THREAD

**Issue by crulinjr** [WoWManiaUK/Redemption#2902]
How it is working: 
Sometimes Frost Trap is not triggering the root from Entrapment (http://www.wow-mania.com/armory/?spell=19388) while Snake trap does 100%. If you put a Explosive trap + Frost trap together the success rate is really low while on the contrary if you out an Explosive trap + Snake trap the success rate is a 100%. I'll put some screeshots. The mob kept running towards me and did not get rooted. The proof is that the 4 second taunt was still up when the mob was on the other side of the trap instead of dissapearing while the mob was still on the root since both root and taunt have the same duration.

![wowscrnshot_121018_231226](https://user-images.githubusercontent.com/40045543/49778767-be560000-fcfe-11e8-99e3-488021177f1d.jpg)
![wowscrnshot_121018_231018](https://user-images.githubusercontent.com/40045543/49778768-be560000-fcfe-11e8-9244-d203e7f35798.jpg)

How is should work:  Frost should always proc Entrapment and should not break the root from damage.

**Comment by Keader** [comment]
Try now.
I put a fix, because somtimes caused by los spell was not working.
Now looks ok, can you confirm?

**Comment by Keader** [comment]
@crulinjr or @Dranah can confirm it?

**Comment by crulinjr** [comment]
Havent be able to try it out. I will in a couple hours
