### ISSUE TITLE
[Quest] The Test of Righteousness

### ISSUE THREAD

**Issue by gamer100** [WoWManiaUK/Redemption#2903]
http://www.wow-mania.com/armory/?quest=1654
Need to interact  with npc Bailor Stonehand but there is no interaction possible
http://www.wow-mania.com/armory/?npc=6241
![bailor](https://user-images.githubusercontent.com/33811022/49835177-b0f05280-fd9e-11e8-9e25-d2669fdd8822.png)

**Comment by gamer100** [comment]
![image](https://user-images.githubusercontent.com/33811022/49835981-4f7db300-fda1-11e8-98f9-6a8fec971b50.png)

**Comment by wow-mania** [comment]
Works!
![image](https://user-images.githubusercontent.com/12248683/49855627-b7ee8380-fde5-11e8-94ca-5610f1e993fc.png)
