### ISSUE TITLE
Armory Talent Calculator doesn't work

### ISSUE THREAD

**Issue by Boobarnes** [WoWManiaUK/Redemption#2905]
When I click on the wow-mania armory's talent calculator [http://www.wow-mania.com/armory/?talent](url)    , nothing works. I click on the class and no talent trees appear. I have tried it in Firefox, Chrome, Edge, and even Opera. I'm on Windows 10 Home. I thought it might be a javascript issue with my browsers, but I've googled other 3.3.5a talent calculators, and they load fine. Yes, I can use them instead, just thought you should know.

**Comment by wow-mania** [comment]
This repository is only for server issue, not website ones.
There are loads on talent calculator online that you can use.
