### ISSUE TITLE
Temple of Ahn'Qiraj - dors dont open after kiling Prophet

### ISSUE THREAD

**Issue by Zabzero** [WoWManiaUK/Redemption#2906]
After kiling Prophet dors to tunels shuld opend and they dont, what makes other boses not duable.

**Comment by wow-mania** [comment]
This pretty much give me no info. Go read "The how to log an issue" page, please.

**Comment by Keader** [comment]
Fixed in PTR @Zabzero 
Will be on Redemption in next update
