### ISSUE TITLE
Launcher crashes when scanning drives

### ISSUE THREAD

**Issue by emmet7** [WoWManiaUK/Redemption#2907]
I downloaded the current launcher in the link stated in this post: 

http://www.wow-mania.com/forum/viewtopic.php?f=16&t=35

The assembly version is: 1.2.6879.17506 (12.12.2018 11:52:05). Wen starting the launcher, the download starts, however the launcher terminates after some MB with a standard windows notice.

There is a corresponding event log entry:

Anwendung: Launcher.exe
Frameworkversion: v4.0.30319
Beschreibung: Der Prozess wurde aufgrund einer unbehandelten Ausnahme beendet.
Ausnahmeinformationen: System.IO.IOException
   bei System.IO.__Error.WinIOError(Int32, System.String)
   bei System.IO.FileSystemEnumerableIterator`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].CommonInit()
   bei System.IO.FileSystemEnumerableIterator`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]..ctor(System.String, System.String, System.String, System.IO.SearchOption, System.IO.SearchResultHandler`1<System.__Canon>, Boolean)
   bei System.IO.DirectoryInfo.InternalGetFiles(System.String, System.IO.SearchOption)
   bei Launcher.MainWindow.d(System.String)
   bei Launcher.MainWindow.d()
   bei Launcher.MainWindow+<>c.a()
   bei System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   bei System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   bei System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   bei System.Threading.ThreadHelper.ThreadStart()

I debugged into the issue with DnSpy. The problem is, that the launcher scans all drives for the presence of a file with a specific name. I'm not gonna post it here since I guess it's part of an anti-bot check or something.
It catches UnauthorizedAccessExceptions, when trying to enlist a directory, however it does not handle IOExceptions. The IOException is triggered on my system, when trying to list the contents of a cd rom drive, which has no cd inserted, so I guess the constellation is not that seldom.
I would suggest to handle IO Exceptions just like the UnauthorizedAccessExceptions.

When skipping over the above mentioned check, everything went fine.

**Comment by wow-mania** [comment]
NOt a server issue. Please check the forum for solutions. Contact me via Discord or Skype and we can solve it.
