### ISSUE TITLE
[Spell] Divine Storm! (Retribution 2pt10 proc)

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#2908]
http://www.wow-mania.com/armory/?spell=70769
http://www.wow-mania.com/armory/?spell=53385

There is an issue with the way it visually resets global cooldown on all your attacks. It is about 90% visual issue but it can cause problems with players' performance. Details below.

**How it works atm:**
When the proc occurs right after you had cast a Divine Storm (and your GCD is still running), it bugs out all of your attacks, visually reseting their global cooldown. 
It does not actually reset the GCD (nor it should), the problem is that it can no longer be seen running, which confuses players and can also lead to delays in rotation. 
All of your spells appear to be ready-to-use, but when you press one, the button just flickers and says it is not ready yet, since obviously the GCD is still running.
The real problem here is if you cannot see when the global cooldown is coming off and press a button milliseconds before it is actually ready, it will still just "flicker" and then can only activate with a delay on next press.

Steps to repro:
- Cast Divine storm http://www.wow-mania.com/armory/?spell=53385
- Immediately after, while GCD is still running, cast t10 proc spell=70769
Now every ability is seen ready, though they aren't.
- Attempt to use another ability while in this state (within 1> sec), you will see the button flicker but the attack can't go off
- If you keep pressing, after some time the attack finally goes off (but this is overall slightly more time than it would take if you could see the GCD and just pressed next attack when it's ready)
This sequence needs to be performed at high speed, like the pace of a high-end retri racing for DPS meter.

In game, players experience this most often during bloodlust/burst phase when increased haste gives them more frequent procs, and that's the time when precise rotation is the most essential.
Also bear in mind retri paladins play with two different GCDs by default (their spell attacks such as Exorcism trigger a shorter GCD than their melee based attacks, due to scaling with haste) which means that being able to see their global cooldown running is important for optimal performance.

**How it should work:**
Even if the proc occurs right after a Divine Storm cast with GCD just triggered, it should only reset the spell's own 10sec cooldown and allow the triggered GCD to run on your spells properly.

**Comment by Keader** [comment]
Test now little Dranah =)

**Comment by Dranah** [comment]
Well, atleast DS now displays the GCD running and that one button doesn't flicker.
This is an improvement and if it cannot be fixed any better, i guess it'll do for now.

**Comment by Dranah** [comment]
It seems we can add more spells for client to receive GCD data for, as long as latency allows.
Main rotation abilities should be covered, Crusader Strike, Judgements, Exorcism and Consecration, possibly Hammer of Wrath and Hammer of Justice/Divine Shield.
Spell IDs to add for @Keader 
http://www.wow-mania.com/armory/?spell=48819 consec
http://www.wow-mania.com/armory/?spell=48806 hammer of wrath
http://www.wow-mania.com/armory/?spell=10308 hammer of justice
http://www.wow-mania.com/armory/?spell=642 divine shield
http://www.wow-mania.com/armory/?spell=20186 JOW
