### ISSUE TITLE
Quest Bugged: Klaven's Tower

### ISSUE THREAD

**Issue by Kirahx** [WoWManiaUK/Redemption#2911]
Main Problem: The box wont open.

Detail: As the quest start, you need to go in the Defias Tower (Westfall Area), Pickpocket a Spiked undead that roaming around the Tower to get the ''Defias Tower Key'' 0/1, and climb up the Tower to loot The box near Klaven (NPC). 

The problem is, even if i have looted the Key, i still can't open the Box. i abandonned the quest 2 time to try again, same result.

**Comment by wow-mania** [comment]
Works. Check your lockpicking level.
