### ISSUE TITLE
Game crush when trying to enter world

### ISSUE THREAD

**Issue by Vnholy** [WoWManiaUK/Redemption#2912]
Dear devs,

I have faced a fatal error when I tried to enter the world with my character. I replicated this issue a couple of times and seems like there is an issue with the blood elf female model, this is from the error log I saved for further investigation. I can send you the whole error log if necessary.

"This application has encountered a critical error:

ERROR #134 (0x85100086) Fatal Condition
Program:	X:\XYZ\WoW-Mania-2.5.0\Wow.exe

Failed to read file character\bloodelf\female\bloodelffemale01.skin.

Debug Details:

[2] err=0 text=SFileReadFile - character\bloodelf\female\bloodelffemale01.skin - Data\patch-Z.MPQ
[1] err=0 text=LoadSectorTable failed
[0] err=0 text=LoadSectorTable failed"

I tried to solve the issue by deleting the cache and the WTF folders, it did not help.

Since there is no repair tool I started downloading the whole client again, will update you if that solved the issue, but I expect it to be working.

Also I am trying to use the launcher you dedicated to your servers, however after starting it up it checks for updates and automatically closes instead of starting the game or showing any more information. I suspect this is not how it supposed to work? I am not sure, if this might be part of the issue I am having with the skin, but I guess not.

Thank you for your assistance in advance and if there is any more detail I might have missed please let me know.

BR,
Vnholy

**Comment by wow-mania** [comment]
This is not a server issue. Please check forums or contact support via email or Discord.
