### ISSUE TITLE
[Spell] Totem of Wrath/ Flametounge Totem interaction with ICC

### ISSUE THREAD

**Issue by Ashamedlol** [WoWManiaUK/Redemption#2913]
When pulling down a Totem of Wrath (http://www.wow-mania.com/armory/?search=Totem+of+Wrath#abilities) or a Flametounge Totem (http://www.wow-mania.com/armory/?search=Flametongue+Totem) while there's a gunship cannon (Gunship) or abomination (PP) active, the fuel resource will go to 0/0 and you won't be able to fill energy by shooting nor drinking, resulting in less effective fights in those two encounters.

Proof Below:

**Comment by wow-mania** [comment]
Did you test in dev?

**Comment by Ashamedlol** [comment]
It was on Redemption.

**Comment by squalllh1989** [comment]
Confirmed, just test this out, the totem make the energy disapear.

**Comment by squalllh1989** [comment]
![wowscrnshot_121518_224927](https://user-images.githubusercontent.com/27235989/50044803-ddb4aa80-00bb-11e9-9a3e-72d2d2aa1060.jpg)
Screenshot: drinking (skill on cd), and no energy on abom
