### ISSUE TITLE
[Achievement] Warglaives of Azzinoth

### ISSUE THREAD

**Issue by NightSeekerr** [WoWManiaUK/Redemption#2915]
Link: http://www.wow-mania.com/armory/?achievement=426
Link 2: https://www.wowhead.com/achievement=426/warglaives-of-azzinoth#comments

So, today I equipped both Warglaives and nothing happened. I own the Off Hand Warglaive, and the Main Hand one was borrowed to me by a guy who just won it in a Black Temple run I organized. 

I spoke to admin Aymelek who told me that maybe I didn't get the achievement because one of the glaives was still tradeable. That doesn't make sense to me because the achievement criteria is just to equip both. Also: 
![wowhead](https://user-images.githubusercontent.com/30464528/50044927-62d79980-0093-11e9-9f93-9b01b9a44209.png) So it seems to me I should have obtained the achievement.

Here's a screenshot of me with the 2 Warglaives equipped: 
![wowscrnshot_121518_163624](https://user-images.githubusercontent.com/30464528/50044941-961a2880-0093-11e9-924c-c07777d50732.jpg)

P.S. I use latest Client version and Launcher.

**Comment by wow-mania** [comment]
Your comment is from 2010 dude. This is not valid on 3.3.5a so the GM is right.

**Comment by wow-mania** [comment]
If the weapon is not equipped you don't get it sorry.

**Comment by NightSeekerr** [comment]
I equipped both weapons, dude. Also, of course the comment is from 2010 and is also for patch 3.3.5.

**Comment by WhitephoenixTheBunny** [comment]
I am testing it anyway :P

**Comment by wow-mania** [comment]
Just tested multiple times and it works fine if items are soulbound an equipped.

**Comment by Keader** [comment]
It's not correct behavior.
Even if is not soulbound it should give achiev.
I fixed it already, just not send yet (was working in paladin issue x_x)

**Comment by NightSeekerr** [comment]
Can an admin help me get the achievement now that it has been fixed?

**Comment by wow-mania** [comment]
@Keader Item is not tradeable it's BoP so your fix is not meaningful.

@Nightseeker I will give you the benefit of the doubt this time since we had some misunderstanding here. Open a ticket.

**Comment by Keader** [comment]
It is.
When you kill the boss, you can equip item, get achiev and pass to another guy before 2 hours.
Many players can get the achiev using same weapon
