### ISSUE TITLE
Going Bearback

### ISSUE THREAD

**Issue by Shadowmalroc** [WoWManiaUK/Redemption#2916]
Quest name - Going Bearback
Quest giver - Brijana at Brunnhildar Village

Quest requires you to mount Icefang and burn 7 Frostworgs and 15 Frostgiants.

I am doing the quest correctly as far as I know, but I do not get a tally of targets burned. I have tried the quest numerous times all with the same result.

Regards Ken

**Comment by wow-mania** [comment]
The quest works. Just checked. You probably missed something along the way.
![image](https://user-images.githubusercontent.com/12248683/50047005-3a589b00-00a5-11e9-941a-acbae320e51a.png)

**Comment by Shadowmalroc** [comment]
Sorry, thanks for checking. I had the reputation setting at "not at war". At that point I should still have been at war with Sons of Hodir. Quest now completed.

Regards

Ken
________________________________
