### ISSUE TITLE
Cannot obtain quest "A Father's Duty"

### ISSUE THREAD

**Issue by enderGG** [WoWManiaUK/Redemption#2920]
After finishing quest "Our Boy Wants To Be A Skyguard Ranger" the quest giver Torkus doesn't give the continuation of the quest in the form of "A Father's Duty". This quest is needed chain is needed for the winter achievements. This quest is located in blade's edge in the Ogri'la

**Comment by GM-Kratos** [comment]
Adding links:

Torkus: http://wow-mania.com/armory/?npc=23316
Our Boy Wants To Be A Skyguard Ranger: http://wow-mania.com/armory/?quest=11030
A Father's Duty: http://wow-mania.com/armory/?quest=11061

**Comment by wow-mania** [comment]
Just tested this and works fine.
Make sure you have the correct reputation with Sha'tari and Ogri'la
