### ISSUE TITLE
Lock and load proc not resetting the cd on Explosive shot

### ISSUE THREAD

**Issue by Aristo14** [WoWManiaUK/Redemption#2921]
http://www.wow-mania.com/armory/?spell=56344
http://www.wow-mania.com/armory/?spell=60053

**How it works at the moment**
When you proc the lock and load ability, your current cd on the explosive shot is still running and you will have to wait for it to run out before you can utilize the proc. 

**How it should work**
When you proc the lock and load ability, your current cd on the explosive shot should reset, enabling you to utilize the proc immediatly. 

This will cause issues due to the 11sec timer on the proc and the full 2 seconds you need per explo shot. Resulting in a, worst case scenario,  6 sec wait for explo cooldown before you can do the explo shots that need 2 full seconds each (You dont want to clip your ticks).

Proof: 
You can easily check several videos about sv hunters where you can see the cd resetting. 
https://www.youtube.com/watch?v=8TksuZylUd0 (recommend watching at 1:50)
This is how it works on cata (i know everything is different for hunters on cata) and I haven't found a relevant changelog between cata and wotlk patches.

**Comment by Dranah** [comment]
I believe this report is valid, all WOTLK sources I find speak of LNL giving you 3 explosive shots to cast, which is only possible with it also reseting the CD (since a surv hunt always keeps the spell on cooldown).
I can confirm there is currently no reset when the proc occurs.

**Comment by Ashamedlol** [comment]
The sources I've checked seem to be opposite @Dranah 
https://youtu.be/e_zGndYpkkQ?t=111
https://youtu.be/RtkraBQbpgI?t=271

Notice how the Trap/Black Arrow procs Lock and Load but Explosive doesn't reset in CD.

**Comment by Dranah** [comment]
Yeah the problem is that none of those videos are from 3.3.5a :/
One is from 3.2 and the other is 3.3.0 based on the date, so that does not tell anything of how the spell worked on 3.3.5a.
I understand that the spell did not always reset the CD, but how do you know it was added on cata and not on 3.3.5a?

**Comment by Keader** [comment]
Tested and is working.
The Problem that can happens with GCD (like divine storm) is super rare here (because is just 6% of chance), so... i will leave as is.

**Comment by Dranah** [comment]
Confirmed, CD is now reset when the proc happens. GCD issue is negligible due to rarity of procs.
