### ISSUE TITLE
[Talent] Titan's Grip

### ISSUE THREAD

**Issue by Ashamedlol** [WoWManiaUK/Redemption#2924]
The penalty of 10% physical damage reduction is not working.

Proof: 
![rend 2h](https://user-images.githubusercontent.com/16576459/50227796-3f705f80-03af-11e9-9269-e827c18b4ff0.png)
With one 2H only.

![rend 2 2h](https://user-images.githubusercontent.com/16576459/50227810-47c89a80-03af-11e9-8deb-5d306c4d3470.png)
With two 2H.

There's no leap in damage, 10% reduction of 137 would be 123.3.

Additional proof: 
![hs 2h](https://user-images.githubusercontent.com/16576459/50228144-f53bae00-03af-11e9-9585-81250f8dc147.png)

Heroic Strike with only one weapon.

![hs tg 2h](https://user-images.githubusercontent.com/16576459/50228158-fbca2580-03af-11e9-805e-b72566a8f8ad.png)

Heroic Strike with two weapons (No reduction of 10%, seeing as 245 stayed 245 instead of going 220.5).

So yeah, there's no reduction of 10%, this includes ALL autoattacks and spells, not just spells.

Talent ID: http://www.wow-mania.com/armory/?spell=46917

**Comment by Ashamedlol** [comment]
For an extra: 
Result of 1H rend: 
![1h tg](https://user-images.githubusercontent.com/16576459/50230889-38008480-03b6-11e9-9e99-1d9268d82ff4.png)

**Comment by Dranah** [comment]
I can confirm this, also that it used to work way back... i've no idea when this broke.

**Comment by Aristo14** [comment]
I was talking with Ashamed about this yesterday, from what I understood, he did see the dmg reduction when using a 1h weapon. As if it's applying to the wrong weapon type.

**Comment by Dranah** [comment]
Strange. I don't get the penalty even with 2x 1h on my warrior. Maybe it's specific weapon types?

**Comment by Keader** [comment]
Fixed.
Now it will work to all wepons.

**Comment by Dranah** [comment]
Appears to work as intended now. Equipping a two hander dual wielded with another weapon now always gives penalty. 

But, I found another flaw with the talent itself.
Polearms shouldnt be affected by the talent, and while you cannot equip 2x polearms or polearm + another 2 hander, you can in fact currently equip a Polearm in your main hand and a shield or one-hander in your offhand.
This also grants the 10% penalty as intended, the question is why is this possible at all, Polearms shouldn't work with being put in 1 hand.

**Comment by Keader** [comment]
Because polyarm still is a "two hand weapon" '-'

**Comment by Dranah** [comment]
That doesn't explain why titan's grip allows it to be wielded in one hand, together with a shield.
TG only applies to 2h axes maces and swords, it is stated in the tooltip that way.

**Comment by Keader** [comment]
This is other bug Dranah :)

**Comment by Dranah** [comment]
Ok original issue fixed, new one is opened for the other problem since it is a core issue.

**Comment by Ashamedlol** [comment]
New bug: Swapping the Titan's Grip spec into another spec causes weapon to have same 10% penalty on other talents, including Arms and Protection specs.

How to reproduce: Have Titan's Grip spec with two weapons equiped, swap to other spec, you'll notice the 90% weapon damage instead of 100%.
You can revert it by unequiping the second weapon or putting a 1handed weapon on main hand without any offhand on Titan Grip spec.

**Comment by Keader** [comment]
Fixed @Ashamedlol 
Please test and confirm.

**Comment by Ashamedlol** [comment]
Now no longer penaltizes offspec.
