### ISSUE TITLE
[Spell] Seal of Corruption/Seal of Vengeance's Blood Corruption

### ISSUE THREAD

**Issue by Ashamedlol** [WoWManiaUK/Redemption#2925]
The Seal DoT damage (Blood Corruption/Holy Vengeance) should be going up based on the procs active (and when they disappear it goes back to what it was), but instead, it just stays on a stable damage number.

![socsov](https://user-images.githubusercontent.com/16576459/50257948-2941be00-0406-11e9-93c2-0b74dbbf3849.png)

It deals same damage, Twilight Scale procs, still no damage increase.

Video Proof: https://youtu.be/0Y88l_tVXAk?t=49 
You can notice here how his damage jumps up on the Blood Corruption when he has Avenging Wrath and trinket+procs up, then it goes down as they are off.

Spell IDs: 
Blood Corruption: http://www.wow-mania.com/armory/?spell=53742 
Holy Vengeance: http://www.wow-mania.com/armory/?spell=31803
Seal of Corruption: http://www.wow-mania.com/armory/?spell=53736
Seal of Vengeance: http://www.wow-mania.com/armory/?spell=31801

**Comment by Keader** [comment]
Well, damage and mods should always get calculated on cast.
Now, it will get all damage and stuffs on cast. (Before was always getting damage and mods of first stack only).
And fixed to get effect in all stacks, not just in 5.

**Comment by Dranah** [comment]
UPDATE:
- Blood Corruption (dot) now re-checks your damage buffs whenever a new stack is applied. (fixed)
- Seal of Corruption (instant) effect is now applied to your attacks even when the target has only 1-4 stacks of Blood Corruption. Problem is, this damage is currently not scaled proportionally to the amount of stacks, but instead always applies the maximum (5stack damage).
How it should work:
5 stacks applies maximum 33% of weapon damage as seal damage
4 stacks applies 4/5 of that 33% weapon damage = 26,4%
3 stacks applies 3/5 of that 33% weapon damage = 19,8%
2 stacks applies 2/5 of that 33% weapon damage = 13,2%
1 stack applies 1/5 of that 33% weapon damage = 6,6%

**Comment by Dranah** [comment]
UPDATE:
Lower stack damage went missing, need fix.

**Comment by Dranah** [comment]
UPDATE: 
- Seal damage now scales proportionally with stack count as intended.
- Blood Corruption (dot application) acquired the ability to miss, for some reason. This need to be fixed, the DOT should always apply if the original attack which proc it lands.

**Comment by Dranah** [comment]
UPDATE: everything fixed
- Blood Corruption can no longer miss or be dodged/parried
- Seal of Corruption/Vengeance now deals instant damage proportional to the amount of stacks on target
- Blood Corruption/Holy Vengeance (DOT) now re-checks damage mod buffs whenever the stacks are refreshed.
