### ISSUE TITLE
Respawn rates on nodes such as herbs

### ISSUE THREAD

**Issue by Papamac1234** [WoWManiaUK/Redemption#2926]
Hello, I have recently noticed that the respawn rate of herbs in Arathi Highlands and Feralas are incredibly slow to the point of making it impossible to properly level the professions in a decent manner. I believe these will not be the only zones affected. The main issues this causes is;
1. Levelling professions for players is incredibly hard 
2. The server economy will struggle as players find it difficult to find mats to sell and craft items.
As the population is low in comparison to retail WotLK don't you think the respawn rates should take this into account if not atleast match retail?
Regards
Papamac

**Comment by wow-mania** [comment]
1. Leveling gathering profs have x2 on the server.
2. Being hard is not a bug
3. The server economy is fine.

What we are looking for here is measurable and objective issues that can be compared to the official documentation not personal points of view.
Please gather enough info on how the server may have the wrong values and I will be more than happy to reopen this.

**Comment by Papamac1234** [comment]
What a lazy ass answer.

**Comment by wow-mania** [comment]
I would say the opposite. Your report lacks facts and you can't be bothered to produce them. So who is lazy?

**Comment by Papamac1234** [comment]
What facts would you like to be produced?

**Comment by Papamac1234** [comment]
The 12+ hour spawn time experienced within arathi highlands and feralas?
