### ISSUE TITLE
Druid Travel Form

### ISSUE THREAD

**Issue by Cyligod** [WoWManiaUK/Redemption#2927]
Issue I am having is the travel form speed. It is locked at 40% which it should be going up to epic speed at lvl 38. I think I have found the reason why. We are using the stag form of travel which doesn't come out till 5.0.4 patch. Which stag form is locked at 40% but lets you carry someone unless you glyph it to become the cheeta again with default speed that is that of a epic mount. The links with patch info and stuff will be below to verify that we are using a incorrect version of travel form.

    Mists of Pandaria Patch 5.0.4 (2012-08-28): Travel Form now uses a stag model rather than cheetah.

        To have the cheetah form,  [Glyph of the Cheetah] is needed.

https://wow.gamepedia.com/Travel_Form Main page with all the info

**Comment by wow-mania** [comment]
Dude we are 3.3.5a

**Comment by Cyligod** [comment]
i know but we have a 5.0.4 version of travel form

**Comment by Cyligod** [comment]
instead of the orignal cheeta form that gets upgraded to epic speed

**Comment by wow-mania** [comment]
Does not change the mechanics in any way. It's just visual.

**Comment by Cyligod** [comment]
Incorrect Stag form change makes it where you have to have a glyph to go full speed. As the post says i linked. before stag version your cheeta speed was 40 at lvl 18 then you got a faster version at lvl 38. in teh form we have its locked at 40% unless you glyph it to become the normal version

**Comment by Cyligod** [comment]
its actually a huge problem and difference

**Comment by Cyligod** [comment]
I do agree it looks better dunno if the ppl riding you function is working but the broken speed is very bad and altars immersion and play style so much.

**Comment by wow-mania** [comment]
I highly doubt there is any issue with speed. Speeds on travel form are the same as the equivalent mount to the same level. If you can show me how we are wrong with references from 3.3.5a I will check.

**Comment by Cyligod** [comment]
i just did instead of 100% its only 40% in game i am using a swift saber atm because my travel form is so slow compaired.

**Comment by wow-mania** [comment]
You didn't the link you added is valid for retail not 3.3.5a.

**Comment by Cyligod** [comment]
Unless the tool tip is wrong which could be the issue but when i change to travel form from swift i notice the dip in speed  also so =/

**Comment by GMWeeble** [comment]
The speed is 40% but we have wod Models added in the game, si it looks like the wod one but does -not- give more speed. It Acta just like retail wotlk, but looks like wod.

**Comment by Dranah** [comment]
Travel form never gave you more than 40% speed on WOTLK.
It was a means to travel when you didn't have a mount yet, or couldn't afford it. (I understand beyond cataclysm these terms are unknown to players but that was it's original purpose + also situations like carrying flags in battlegrounds, where you cannot mount but you can activate ghost wolf / travel form)
