### ISSUE TITLE
[Boss] Escape from the Lich King - Halls of Reflection

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#2928]
https://www.wowhead.com/npc=37226/the-lich-king

There are severe issues with LK and adds movement/activity here, which overall increase the difficulty of the fight. Note this has been tested on heroic, normal may or may not behave same way but it's less relevant as normal is very easy.

1) LK casting his Remorseless Winter too late https://www.wowhead.com/spell=68981/remorseless-winter

**How it should work:** He should pause in the first curve of the road right as he leaves the chamber (next to the first brazier that marks the road) and cast the first Ice Wall and then Remorseless Winter immediately. During this, he does not move!
Seen here from retail video: https://www.youtube.com/watch?v=EIb8ThOfL3E

**How it really works:**
When you begin the event and start running down with the NPC, LK keeps moving at full speed until he reaches Sylvanas/Jaina (who stops for a moment), smacks them once, keeps moving even while he casts the first ice wall (still at full speed) and only then he begins casting Remorseless winter to slow himself down. 
At this point he is a heartbeat away from your group at wall, and he hasn't even summoned his adds yet.
Screenshot from mania to display just how close he stops from your group and the first wall:
https://imgur.com/kpsAOSu
As you can see he is already beyond the alcove that you're supposed to use to LOS his adds...
And this head starts he gets will affect the whole encounter as he already starts way closer behind you than he should be.

2) Ghouls Leaping https://www.wowhead.com/npc=36940/raging-ghoul
https://www.wowhead.com/spell=70150/leap

**How it works atm:** The first wave of Raging ghouls appears to leap to you as intended, possibly because they are very close due to bug1.
On other waves, you only see a couple leaps happening, mostly from ghouls that are very close proximity.
I suspect the range may be wrongly calculated here.

**How it should work:** When a ghoul spawns, as soon as he is in 30yrd range, he should leap to your group.
You can see on the video how ghouls are flying in from miles away, you never have to wait for them to run to you.

3) Unexplained delays of casts
- There is a 3second delay between last add dying and the wall being destroyed and letting u move on. As you can see on video I linked, this does not exist on retail, there is less than 1sec between that's like basic response time from server.
- There is a 4-5second delay between a wall being destroyed and LK casting the new wall
How it should work: On blizz video as you can see, the moment one wall falls, LK stops immediately and begins casting the new one. Then 3-4sec after he is already summoning adds.
How it works atm: Here, he keeps moving for 4-5sec and only then he casts the new wall. At same time, the message "X adds incoming" arrives because he should already be casting the new set of adds at this point, not the wall.
- There is another 4sec delay on him actually beginning to summon the adds.

During all of this delay, LK keeps moving and moving, closing in the distance between him and the party and leaving you with much less time to deal with the adds than you would normally have.

**Comment by Dranah** [comment]
UPDATE:

1) Fixed, LK now properly stops at the beginning and casts remorseless winter immediately.
2) Ghouls arent using their leap ability at all, they always just run up to you (need fix)
3) The walls now fall without delay (fixed)
There is still a 4sec delay between wall being destroyed and LK beginning to cast the new one.  (need fix)
There is still a further 4-5sec delay until he begins summoning the adds he had announced long ago. (need fix)
During this time, LK keeps moving to you.

**Comment by Keader** [comment]
test now

**Comment by Dranah** [comment]
Update:

- Delay between wall destroyed and LK beginning to cast new one was reduced to about 2sec (fixed)
- Delay between LK casting new wall and beginning to summon adds is still around 4-5sec (need fix)
- LK still keeps on moving (or rather, drifting) while he's casting the wall and the adds, when he should stop for that period (need fix)
- Ghouls are now properly leaping to you whenever possible (fixed)

**Comment by Keader** [comment]
test now

**Comment by Dranah** [comment]
UPDATE:
- Delay between new wall cast and summoning adds has been reduced to 1-2sec. (fixed)
- LK still keeps drifting while casting walls instead of making a full pause (need fix)

**Comment by Dranah** [comment]
UPDATE:
- LK now properly pauses for casting the new wall and new set of adds every time a wall falls.
- Players now have approx 25-30sec more time to finish the event after the achievement is failed.
