### ISSUE TITLE
[Spell] Petrified Bark

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#2931]
http://www.wow-mania.com/armory/?spell=62337
Cast by https://www.wowhead.com/npc=32914/elder-stonebark on Freya trash

**How it should work:** the aura should reflect MELEE attacks and abilities up to 60 charges (120 on 25man). Spells and ranged attacks should not be affected at all.
**How it works atm:** The aura also reflects spells and ranged attacks , but without consuming any charges. Makes it really OP against a caster-heavy group.

**Comment by Keader** [comment]
You are right and wrong.

spell has proc flag:

```

  03 Taken damage from melee strike hit
  05 Taken damage by Spell that use melee weapon
  07 Taken damage from ranged attack
  09 Taken damage by Spell that use ranged weapon
  13 Taken negative spell hit
```

It means that sould proc with ranged and some spells.
But you are right in 1 thing.
Old non-implementation was a big hack in damage method of creature.
So was reflecting any damage, ignoring totally proc flags.
Now, it is correct scripted.

**Comment by Dranah** [comment]
Uhm, "spell that use melee weapon" and "spell that use ranged weapon" are basically special abilities of melees and hunters, not real spells, but yeah.
The tooltip does not explicitly speak of ranged attacks being reflected, but it makes sense that hunters are affected too, as they're physical dps.
Nonetheless, spells of casters should never be affected.

**Comment by Dranah** [comment]
After several crashes, now the spell no longer reflects spells. It will also properly lose charges from reflected melee abilities.
