### ISSUE TITLE
Paladin Seals' proc behavior

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#2933]
http://www.wow-mania.com/armory/?spell=53736 SoCorruption
http://www.wow-mania.com/armory/?spell=21084 SoRighteousness
http://www.wow-mania.com/armory/?spell=20375 SoCommand
http://www.wow-mania.com/armory/?spell=53696 Judgements of the Just
http://www.wow-mania.com/armory/?spell=20271 JoL
http://www.wow-mania.com/armory/?spell=53408 JOW
http://www.wow-mania.com/armory/?spell=53407 JoJ
http://wowwiki.wikia.com/wiki/Seal_of_Command_(old)

There are some anomalies I found with the way procs happen (or rather, not happen) sometimes

1) REMOVED
EDIT : found evidence that of 3.3.0 seal of righteousness can proc off judgement but seal of command and corruption cannot https://www.wowhead.com/forums&topic=142284
http://eu.battle.net/wow/en/game/patch-notes/3-2-0

2) Divine Storm can proc Seal of Righteousness and Seal of Corruption on all targets but does not properly proc Seal of command
Refer to the link above for source:
"When Divine Storm is used, a maximum of 4 enemies are hit by it. Seal of Command will apply extra holy damage to each of these targets, but each of these procs will not "spread" to two other nearby targets"
**How it works right now:** the seal of command proc is only applied to 1 target (at random) instead of all the four.
**How it should work:** all targets hit by Divine Storm should receive the single-target seal damage of Seal of Command

Note: When using Seal of Righteousness all 4 targets properly receive seal damage and when using Seal of Corruption, all targets hit that have Blood Corruption DOT on them will receive seal damage properly.

3) Full absorbs can proc Seal of Corruption, but cannot proc Seal of Righteousness or Seal of Command

**How it works atm:** If your target has an absorb effect that fully absorbs your melee attack, Seal of Righteousness and Command will not proc a Seal damage. Seal of Corruption will however apply a stack of Blood corruption (if it was a white swing) and also apply Seal damage.
**How it should work:** Seal of Righteousness and Command should also result in Seal damage proc even if your target fully absorbs your melee attack. In case of Command, if it was a single-target attack, it should also proc the cleave damage.

Note: this looks like an issue of trinity https://github.com/TrinityCore/TrinityCore/issues/11528

4) Hammer of the Righteous fails to proc Seal of Command
Again refer to above link:
"Hammer of the Righteous' initial target will proc the seal, but its nearby additional targets will not. This means that 3 targets will be hit by Hammer of the Righteous (4 if the paladin got the [Glyph of Hammer of the Righteous] ) while the initial target plus 2 nearby ones will be hit by Seal of Command at the same time. In theory it is possible to totally strike 6 different enemies at once this way. "
**How it should work:** when hammer is used, the initial target receives seal damage + 2 nearby targets receive cleave damage (as if the seal was used by a regular single target attack - the cleave damage from seal may not target the same targets as the other 2 or 3 damages done by hammer)
**How it works atm**: Hammer does not proc any Seal of Command damage on any of its targets

Note: Seal of Righteousness and corruption are proc'd properly by the Hammer.

**Comment by Keader** [comment]
Fixed seal of veg/corrup

**Comment by Keader** [comment]
Divine Storm Fixed
Proc with absorb fixed.
About Hammer, pretty sure  that issue is invalid.
It should hit original (with seal of command) and chain.
Hammer and Seal, both is chain effect, so both is one target spell that chain to more targets.

**Comment by Keader** [comment]
https://youtu.be/JSadpiOka2E

Hammer is proccing seal.

**Comment by Dranah** [comment]
No it isn't, it's procced by the melee swing triggered by hammer. You're preventing the melee swing from landing but the seal proc still does. If you are testing it normally when tanking trash packs, you find there are only seal procs belonging to your white melee, none to the hammer itself.
https://imgur.com/Y0GtoWP
1 melee 1 hammer = 3 seal procs, instead of 6. Always.

**Comment by Dranah** [comment]
UPDATE: everything's fixed now

- Divine Storm will now apply a single target seal of command proc on each 4 targets hit (fixed)
- Attacks that are fully absorbed can now still proc Seal of command or Seal of Righteousness (fixed)
- Hammer of the Righteous will now properly proc Seal of Command on it's main target with the seal cleaving two additional targets (fixed)
