### ISSUE TITLE
[Spell] Icecrown 25 Heroic Dagger Proc

### ISSUE THREAD

**Issue by deimien1** [WoWManiaUK/Redemption#2934]
Hello,
 
I am using the current client, along with the latest launcher update.
My character is a lev 80 human rogue, Brenam is the nick.
I am using the dagger http://www.wow-mania.com/armory/?item=50641
The problem is that is not regenerating energy it only activates the buff Invigoration but is not regenerating energy, it appears on the caracters buffs but it's not doing anything.
When it procs it doesn't regenerate energy I have the option activated from the game"energy gain"and that buff is not showing because is not doing anything.
Can you please fix it?

Thank you

have a nice day

**Comment by wow-mania** [comment]
![image](https://user-images.githubusercontent.com/12248683/50510016-ecb63800-0a7f-11e9-9330-31c7633fd0ce.png)
Do you know what that means? It means it may or may not happen. You have to do it enough times so it "has a chance" to happen. Usually lower than 5% or so.

**Comment by deimien1** [comment]
Clearly I do, but you don't if you would be so kind an read The item description you would understand. 
Item passive:has a chance to trigger invigoration!!Not a chance to gain energy.
Like.... Are we both reading The same thing? And in The same language?!
I'm complaining that when The effect occures nothing happens, no energy it's gain.
I'm gonna say it again, not The proc chance is my topic about is about what IT happens when The item comes online.
Please do read this:when The buff from The dagger activates(invogoration) is not regenerating energy, 4 energy like is wrote!!!

**Comment by wow-mania** [comment]
Dude!!! It's one or the other depending on your class. Do I need to underline the entire sentence? :)

**Comment by deimien1** [comment]
You really don't get IT.... Can ask someone else to read my post? Or can you try and test The item? How can I explain you better The passive invigoration should regen energy when it procs, but IT doesn't. Try and focus on what i am saying.
I'm sure The item has a small chance like 5% to activate invigoration, but it needs to regen energy when it procs. The item can't have two chances like you are saying one to proc invigoration and one to regen energy.

**Comment by wow-mania** [comment]
So you are saying it does proc? but it does not regen energy?

**Comment by Dranah** [comment]
Proc will now restore mana/rage/energy as intended.

**Comment by deimien1** [comment]
Thank you! Have a wonderful Day.

**Comment by deimien1** [comment]
Hello... It's stilul not working, just test IT.

**Comment by deimien1** [comment]
Still

**Comment by deimien1** [comment]
Can you look again? Please.
