### ISSUE TITLE
Paladin Quest Bugged

### ISSUE THREAD

**Issue by Deanochai** [WoWManiaUK/Redemption#2935]
The Paladin Quest in questions is "Collection of Goods"

It requires the player to collect an item called "Stratholme Holy Water" which is obtained in the Stratholme Dungeon, I have tried to complete this quest by myself (Lvl 66 Ret Pally named Punchit) but have found that the crates in which the item can be found are non interactable therefore the player is unable to collect the item and as such unable to complete the quest.
I have provided a screen capture of my encounter with said crates.

![pally quest broken](https://user-images.githubusercontent.com/46210787/50503343-57c43680-0aa1-11e9-9014-d86dc2380a20.PNG)
![2nd pally quest error](https://user-images.githubusercontent.com/46210787/50503377-9a860e80-0aa1-11e9-91b7-cddcef7dd7f7.PNG)

**Comment by Dranah** [comment]
Those are not the correct crates... only the ones with a Red cross on them in the last room are containing quest items.
