### ISSUE TITLE
[Quest] Call to Arms: "Any battleground"

### ISSUE THREAD

**Issue by cathyr1** [WoWManiaUK/Redemption#2938]
There seems to be a problem with this quest. I got it automatically in Warsong Gulch this version of the quest http://www.wow-mania.com/armory/?quest=11342 without taking it. And now when the quest is completed it is impossible to return to warbringer, he has no questionmark. So it is also impossible to do an achievment http://www.wow-mania.com/armory/?achievement=909.

The questions are: How to do this achievment and how can I return this quest to questgiver?

Thanks.

**Comment by wow-mania** [comment]
You don't take the quest it's automatically given.
This was fixed today so you have to drop the quest and get it on the next bg,

**Comment by cathyr1** [comment]
Thank you for a quick answer but this is quite problem for me. I never take quest that I know I will have to drop so I didn´t take this one - as you confirmed, it was automatically given. So I´d like to ask you to some possibility to return it or erase from my questbook without any impact into my permanent character statistics. We can discuss it also ingame if you wish, I will make a ticket. Thanks.

**Comment by Dranah** [comment]
I'm really curious what the purpose of that statistic is.
Some kind of personal achievement you're trying to uphold?

**Comment by cathyr1** [comment]
Something like that, statistics are in-game character description as well as the achievments.

This situation was not caused by my mistake, I didn´t take quest, I didn´t accept anything but, however I have in my log something completed that I cannot return. If this is fixed as written above, then it must be possible to return if it was given to me and I completed. I don´t mind if it will be tomorrow or in next month, I just need to return this one I already have to not abandon.

**Comment by Dranah** [comment]
Well i'm not sure if GMs removing your quest won't show up anywhere on your statistics, but if there is no other way, you can always faction change and hand it in :)
