### ISSUE TITLE
[Achievement] All You Can Eat

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#2940]
This achievement is required for the achievement [[Glory of the Icecrown Raider (10 players)]](https://www.wowhead.com/achievement=4602/glory-of-the-icecrown-raider-10-player) that awards the [Bloodbathed Frostbrood Vanquisher](https://www.wowhead.com/item=51954/reins-of-the-bloodbathed-frostbrood-vanquisher) mount.

We just tried doing the achievement and we had dbm watch the stacks for us and we killed Sindragosa on 10nm without anyone getting over 5 stacks of Mystic Buffet. However, we didn't get the achievement because Sheep (Neyman's pet) got stacks and made us fail the achievement, even though pets are not supposed to count toward the achievement. 

>  Pets do not count towards this achievement anymore so they can get as many debuffs as they want and it will not ruin your achievement. - https://www.wowhead.com/achievement=4580/all-you-can-eat-10-player#comments

Thanks for considering this issue

**Comment by Keader** [comment]
Can you confirm @Dranah ?

**Comment by Dranah** [comment]
Confirmed, pets can fail you this achievement.
With 6 stacks on pet: https://imgur.com/DZEkOi5
Without pet: https://imgur.com/piAR1RD
Both 10man and 25man versions are broken.
https://www.wowhead.com/achievement=4620/all-you-can-eat-25-player
https://www.wowhead.com/achievement=4580/all-you-can-eat-10-player

**Comment by Dranah** [comment]
Looks good now:
https://imgur.com/VKy3ZGs
6 stacks on pet, still got achiev.
