### ISSUE TITLE
[Boss] Steelbreaker - New issue

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#2942]
https://www.wowhead.com/npc=32867/steelbreaker

There are new issues on this encounter. Both exist for no more than a month.

1) Meltdown http://www.wow-mania.com/armory/?spell=61889 triggers explosion even if its duration does not run out
How it should work: Meltdown should only trigger the AoE damage when it kills a player at the end of duration. If a player dies to something else (typically fusion punch on tanks) while affected by the debuff, it should not trigger the AOE damage.
How it works atm: if the person with debuff dies to any source, the meltdown will trigger and kill all nearby players, which is a guaranteed wipe

2) Reset issue with https://www.wowhead.com/spell=61902/electrical-charge stacks
When you wipe in phase 3 when only Steelbreaker is alive and capable of gaining these charges, upon reset he does not lose all of the charge buffs.
https://imgur.com/Q2AHni6
After running back and recovering, he still has that one charge, sometimes not even one but 3-4.
You then have to do the encounter with boss buffed, or sacrifice someone to suicide pull and reset the fight properly.

**Comment by Dranah** [comment]
Zzzz I hate when you close threads before i can confirm @wow-mania 
This one totally got lost.
**UPDATE:**
- The first issue is fixed, meltdown no longer explodes nearby people if the target dies early to another source. However, a side effect came up, which is that with the same condition (dying early to another source of damage with overwhelming power debuff), the tanks dying will not properly trigger Electrical Charge on the boss. No healing and no buff to the boss damage from these deaths.
NOTE: It is properly healing the boss and adds the charge when someone else dies to something else, but the tank with Overwhelming getting one-shot does not. It also properly triggers if the tank with Overwhelming lasts the full duration and dies to Meltdown.
- Second issue still persists, wiping with only Steelbreaker alive nearly always results in him retaining a number of stacks gained. You have to sacrifice someone to pull and wipe again in order to reset him properly.

**Comment by Keader** [comment]
Fixed i guess

**Comment by Dranah** [comment]
Can't reproduce the problems anymore so hopefully it is fixed for good.
Will double check on Red when the fix gets ported.
