### ISSUE TITLE
Blowing Hodir's Horn

### ISSUE THREAD

**Issue by jarvik76** [WoWManiaUK/Redemption#2944]
The daily Blowing Hodir's Horn is non-interactive for me
http://www.wow-mania.com/armory/?quest=12977
started at:
http://www.wow-mania.com/armory/?object=192078
The marker shows on the map, and on the object, but no dialog box is opened.  Tried from multiple angles and distances
I am friendly with SoH, and as far as I can tell have completed the prerequisite chain(s)
Video of issue:  
[World of Warcraft 2018-12-31 03-32-30.zip](https://github.com/WoWManiaUK/Redemption/files/2717708/World.of.Warcraft.2018-12-31.03-32-30.zip)
Launcher, patch 2.5.0, cache deleted, no add-ons, re-log tried

**Comment by WhitephoenixTheBunny** [comment]
Are you sure you have done all quests? 
This is in Redemption with my main Whitephoenix:

![image](https://user-images.githubusercontent.com/31921098/50560562-24c8af80-0cfa-11e9-8df9-23ef0e923eab.png)

![image](https://user-images.githubusercontent.com/31921098/50560573-3611bc00-0cfa-11e9-9b75-8ebdd0acd9f1.png)

After doing [Territorial Trespass](http://www.wow-mania.com/armory/?quest=13051) from main questline to farm the reputation to Sons of Hodir, you need pick [Jormuttar is Soo Fat...](http://www.wow-mania.com/armory/?quest=13011) at [King Jokkum](http://www.wow-mania.com/armory/?npc=30105).
You will need pick [In Memoriam](http://www.wow-mania.com/armory/?quest=12975), also with [King Jokkum](http://www.wow-mania.com/armory/?npc=30105), and do the 2 quests ([In Memoriam](http://www.wow-mania.com/armory/?quest=12975) and [A Monument to the Fallen](http://www.wow-mania.com/armory/?quest=12976) after this the [Blowing Hodir's Horn](http://www.wow-mania.com/armory/?quest=12977) will be avaible.

**Comment by Dranah** [comment]
Pretty sure the object is just too big to easily interact with. Keep trying to find the center of its hitbox @jarvik76

**Comment by WhitephoenixTheBunny** [comment]
Just place where are I am on SS
