### ISSUE TITLE
[Item] Orb of the Sin'dorei

### ISSUE THREAD

**Issue by Drostthehunter** [WoWManiaUK/Redemption#2946]
Using the item Orb of the Sin'dorei, http://www.wow-mania.com/armory?item=35275, we are supposed to transform into an Blood Elf, however the textures arent working as intended and your face is painted in the color of your hair.
Sending a screenshot as confirmation:
![wowscrnshot_121518_223238](https://user-images.githubusercontent.com/43518434/50569551-d520cd00-0d67-11e9-9088-091abd3cf8f0.jpg)

**Comment by Keader** [comment]
It's client side.
I remember to get weird effects when using legion model

**Comment by wow-mania** [comment]
Sorry, As-is.

**Comment by WhitephoenixTheBunny** [comment]
Not client side, all people with Orb have issue

**Comment by wow-mania** [comment]
I will try to fix this for the 2.5.1 patch. It is client-side. It just means the issue is on the client software not on the server.

**Comment by wow-mania** [comment]
Fixed. Will release patch next week.
