### ISSUE TITLE
sons of hodir

### ISSUE THREAD

**Issue by soultheif** [WoWManiaUK/Redemption#2948]
ok lets start with some how i missed the forge a aliance quest for part of the chain now to get to the meaty part i have spoke to a few gms bout this issue they have had me abando the quest regave it to me but to no avail the quest item (anvil)does not drop also i am exzalted with sos rep got it through rep tokens the went to start quests and this is when the bug happened i have done almost the whole chain but missed the one quest persay the gms i have spoken to i have asked for a quest line rest or somthing to help me out im stuck in wrong phase and have no idea what to do bout it there r no quest for me to get im just stuck let me know if you need more info on this matter

**Comment by wow-mania** [comment]
The quest line works perfectly. Some quest have a single chance to be done and this is the same as in retail.
We here are interested in proper issues.
So if you think there is a problem somewhere please read the wiki on how to login an issue or refer to some of the issues logged by say, Drannah and follow the format.
What you did here was to tell a sad story of how you messed up a step but nothing more.
Unless there is a clearly described issue, steps to reproduce it, how it is working and how it should work we won't do anything about it.

**Comment by soultheif** [comment]
Yes but it won't drop the anvil item for me for some reason

**Comment by wow-mania** [comment]
Ask a GM to help you with that instead. It's pointless to keep asking the gm to summon you. That only sweeps the real issue under the rug.

**Comment by soultheif** [comment]
I just picked the quest up again I'm a try to run it again see what happens
I'll get gm if it don't work  to for info tho
