### ISSUE TITLE
[Talent] Judgements of the Wise RET Talent does not proc in old world

### ISSUE THREAD

**Issue by Cheree11** [WoWManiaUK/Redemption#2951]
Hello there,

After the latest game update i noticed the talent Judgements of the Wise does not proc in old world -> EK nor Kalimdor. Outland/Northrend is fine.

**Comment by squalllh1989** [comment]
![wowscrnshot_010419_214946](https://user-images.githubusercontent.com/27235989/50693831-bcb3f980-106a-11e9-944b-22068b11c73d.jpg)
Tested in Elwyn forest, EK, proc normally

**Comment by wow-mania** [comment]
Thanks a lot @squalllh1989 for the confirmation.
