### ISSUE TITLE
[Trainer] Warrior Trainer Telios Silverblade

### ISSUE THREAD

**Issue by voleroth** [WoWManiaUK/Redemption#2952]
http://prntscr.com/m2x8ro

Blood Elf Warrior trainer -  Telios Silverblade on the starting zone is bugged and it doesn't let me learn any spell.
+Not able to complete Class Quest since it requires Charge Spell.

**Comment by wow-mania** [comment]
No only your issue is not well described it is in the wrong repository.
This is wotlk only.
