### ISSUE TITLE
Halls of Reflection quest, Wrath of the Lich King: Cant turn in to Jaina Proudmore

### ISSUE THREAD

**Issue by Nicefits** [WoWManiaUK/Redemption#2953]
The quest Wrath of the Lich King in Halls of Reflection cant be turned in once completed.
I have completed the quest in normal and heroic difficulty. It works properly all the way to the end when the airship comes and blocks the Lich Kings path. After that Jaina Proudmore disappears before i can turn in the quest to her. Map shows she should be right there at the rear of Halls of Reflection, but she is not.

**Comment by WhitephoenixTheBunny** [comment]
Alliance:
Quest: http://www.wow-mania.com/armory/?quest=24500
NPC: http://www.wow-mania.com/armory/?npc=36955

Horde:
Quest: http://www.wow-mania.com/armory/?quest=24802
NPC: http://www.wow-mania.com/armory/?npc=37554

Going test now

**Comment by WhitephoenixTheBunny** [comment]
On Alliance I can confirm, I go test on horde now

![image](https://user-images.githubusercontent.com/31921098/50709118-adc74a00-105e-11e9-9dbb-55f0a3502676.png)

![image](https://user-images.githubusercontent.com/31921098/50709138-ba4ba280-105e-11e9-8ce7-7c74e6b34c75.png)

**Comment by Keader** [comment]
Npc Vanishing Fixed.
I tested in Horde side and quest work fine.
If not work in Ally side, open a new ticket to Janitor fix (i dont fix quest e.e)
