### ISSUE TITLE
[Spell] Dark pact

### ISSUE THREAD

**Issue by sepherick** [WoWManiaUK/Redemption#2954]
Dark Pact Rank 2 ID 18937 does not restore my mana but does drain my pets mana when it's used.
before and after screenshot is attached.
![after dark pact 2](https://user-images.githubusercontent.com/46388353/50717783-fd564780-1057-11e9-80f3-4d91dcb8f645.jpg)
![before dark pact 2](https://user-images.githubusercontent.com/46388353/50717784-ff200b00-1057-11e9-855b-b43850a564ca.jpg)

**Comment by sepherick** [comment]
before is the second picture after is the first.  sorry about that

**Comment by Dranah** [comment]
Confirmed, this affects all ranks of dark pact, it drains the pet's mana but grants nothing to the caster.
I'm sure this broke just recently, because I was testing the spell for vezax about a month ago and it was fine.
