### ISSUE TITLE
Insect Swarm

### ISSUE THREAD

**Issue by JohnBrinkle** [WoWManiaUK/Redemption#2957]
Only one "Insect Swarm" can applied at once to an enemy at all times.
A placed Insect Swarm Rank 7 from balanced druid (tested on ally/night elf)
was always overwritten by another druids Insect Swarm and vice versa.
This could be seen visually on applied dots and in the statistics in recount where the druid
spamming Insect Swarm got significantly more hits
than others doing their routine of applying it every 12 - 14 seconds.
In this raid specific raid I saw it at least one druid got the Glyph of Insect Swarm, another did not.
I know the 3% hit malus should only work once, but the damage should still for every druid.

This issue should be happening every time but I can definitly confirm it didn't work on Professor Prutricide and the Blood-Queen Lana'thel as intended.

**Comment by Dranah** [comment]
Works good now, you can have IS from multiple druids on same target. With or without glyph.
