### ISSUE TITLE
Engineering: Hyperspeed Accelerators

### ISSUE THREAD

**Issue by hAi777** [WoWManiaUK/Redemption#2960]
WowMania Link:  http://www.wow-mania.com/armory/?spell=54758
External Link:       https://wow.gamepedia.com/Hyperspeed_Accelerators

How it should work:
Hyperspeed Accelerators does not trigger the global cooldown, thus enabling you to macro it with another ability and pressing the keybind once should trigger both spell.

How it currently works:
Using hyperspeed accelerators and another ability(with a gcd) in a macro requires double pressing the keybind in order to trigger both spells.

Macro used:
#showtooltip Shamanistic Rage
/use 10
/cast Shamanistic Rage

where /use 10 is the slot for the gloves with Hyperspeed Accelerators
in this instance, pressing the keybind once triggers Shamanistic Rage and i need to press again in order for the hyperspeed accelerator to trigger

same applies with any equipped item with "Use" trigger like Flexweave Underlay, Nitro boosts, Emblem of Triumph Trinkets

**Comment by Keader** [comment]
I cant do a generic fix.
I can do specific ones.
Fixed for Hyperspeed Accelerators, gime items ids if you need some more

**Comment by Keader** [comment]
Not the same bug.
This can only happens with items.
Need check why Kill Command (not item) can have same issue.

**Comment by crulinjr** [comment]
I use this macro and sometimes it seems that Kill Command messes up with the macro. Like i press the button i see the cd going down but then i dont shoot anything and have to press the button again to make it work.
#showtooltip Explosive Shot
/petattack
/cast [target=pettarget,exists] Kill Command
/cast explosive shot
/script UIErrorsFrame:Clear()

**Comment by hAi777** [comment]
Item IDs:
Mark of Supremacy - http://www.wow-mania.com/armory/?item=47734
Shard of the Crystal Heart - http://www.wow-mania.com/armory/?item=48722
Glyph of Indomitability - http://www.wow-mania.com/armory/?item=47735
Talisman of Resurgence - http://www.wow-mania.com/armory/?item=48724
Nevermelting Ice Crystal - http://www.wow-mania.com/armory/?item=50259
Ephemeral Snowflake - http://www.wow-mania.com/armory/?item=50260
Ick's Rotting Thumb - http://www.wow-mania.com/armory/?item=50235
Sliver of Pure Ice - http://www.wow-mania.com/armory/?item=50339
HC - http://www.wow-mania.com/armory/?item=50346
Bauble of True Blood - http://www.wow-mania.com/armory/?item=50354
HC - http://www.wow-mania.com/armory/?item=50726
Sindragosa's Flawless Fang - http://www.wow-mania.com/armory/?item=50361
HC - http://www.wow-mania.com/armory/?item=50364
Glowing Twilight Scale - http://www.wow-mania.com/armory/?item=54573
HC - http://www.wow-mania.com/armory/?item=54589
Corroded Skeleton Key - http://www.wow-mania.com/armory/?item=50356
Maghia's Misguided Quill - http://www.wow-mania.com/armory/?item=50357
Satrina's Impeding Scarab - http://www.wow-mania.com/armory/?item=47080
HC - http://www.wow-mania.com/armory/?item=47088

NitroBoosts - http://www.wow-mania.com/armory/?spell=55016
Hand-Mounted Pyro Rocket - http://www.wow-mania.com/armory/?spell=54998
Flexweave Underlay - http://www.wow-mania.com/armory/?spell=55002
Springy Arachnoweave - http://www.wow-mania.com/armory/?spell=63765
Global Thermal Sapper Charge - http://www.wow-mania.com/armory/?spell=56488
Cobalt Frag Bomb - http://www.wow-mania.com/armory/?spell=67769

Frostweave Net - http://www.wow-mania.com/armory/?spell=55536
Potion of Speed - http://www.wow-mania.com/armory/?spell=53908
Flask of the North - http://www.wow-mania.com/armory/?spell=67019

Added "use" trinkets from ilvl232 except toc10 items regardless whether people would macro them or not. Added Engineering and PvP item/spell/miscs (does not trigger gcd) which some people use.

**Comment by crulinjr** [comment]
Kill Command - http://www.wow-mania.com/armory/?spell=34026

**Comment by hAi777** [comment]
> This also happens with Kill Command the Hunter ability

Put abilities that have no GCD first in your macro followed by GCD ability. Like

#showtooltip Vanish
/cast Vanish - no gcd
/cast Cloak of Shadows - has gcd

this one triggers both abilities, and swapping them like

#showtooltip Vanish
/cast Cloak of Shadows  - has gcd
/cast Vanish- no gcd

only triggers vanish

**Comment by hAi777** [comment]
> I cant do a generic fix.
> I can do specific ones.
> Fixed for Hyperspeed Accelerators, gime items ids if you need some more

Item IDs:
Mark of Supremacy - http://www.wow-mania.com/armory/?item=47734
Shard of the Crystal Heart - http://www.wow-mania.com/armory/?item=48722
Glyph of Indomitability - http://www.wow-mania.com/armory/?item=47735
Talisman of Resurgence - http://www.wow-mania.com/armory/?item=48724
Nevermelting Ice Crystal - http://www.wow-mania.com/armory/?item=50259
Ephemeral Snowflake - http://www.wow-mania.com/armory/?item=50260
Ick's Rotting Thumb - http://www.wow-mania.com/armory/?item=50235
Sliver of Pure Ice - http://www.wow-mania.com/armory/?item=50339
HC - http://www.wow-mania.com/armory/?item=50346
Bauble of True Blood - http://www.wow-mania.com/armory/?item=50354
HC - http://www.wow-mania.com/armory/?item=50726
Sindragosa's Flawless Fang - http://www.wow-mania.com/armory/?item=50361
HC - http://www.wow-mania.com/armory/?item=50364
Glowing Twilight Scale - http://www.wow-mania.com/armory/?item=54573
HC - http://www.wow-mania.com/armory/?item=54589
Corroded Skeleton Key - http://www.wow-mania.com/armory/?item=50356
Maghia's Misguided Quill - http://www.wow-mania.com/armory/?item=50357
Satrina's Impeding Scarab - http://www.wow-mania.com/armory/?item=47080
HC - http://www.wow-mania.com/armory/?item=47088

NitroBoosts - http://www.wow-mania.com/armory/?spell=55016
Hand-Mounted Pyro Rocket - http://www.wow-mania.com/armory/?spell=54998
Flexweave Underlay - http://www.wow-mania.com/armory/?spell=55002
Springy Arachnoweave - http://www.wow-mania.com/armory/?spell=63765
Global Thermal Sapper Charge - http://www.wow-mania.com/armory/?spell=56488
Cobalt Frag Bomb - http://www.wow-mania.com/armory/?spell=67769

Frostweave Net - http://www.wow-mania.com/armory/?spell=55536
Potion of Speed - http://www.wow-mania.com/armory/?spell=53908
Flask of the North - http://www.wow-mania.com/armory/?spell=67019

Added "use" trinkets from ilvl232 except toc10 items regardless whether people would macro them or not. Added Engineering and PvP item/spell/miscs (does not trigger gcd) which some people use.
