### ISSUE TITLE
[Core?] CC, Purge and Interrupt resist

### ISSUE THREAD

**Issue by Hajzlopuc** [WoWManiaUK/Redemption#2961]
Hello,

I realized I can NEVER resist any magic CC, Purge(offensive dispel) or Interrupt effect. You should be able to sometimes resist these effects if you have more resistance than your opponent's spell pen.

http://www.dslreports.com/forum/r22554253-Classes-How-can-you-resist-Fear
https://www.ign.com/boards/threads/wow-question-fear-resist.250408004/
https://us.battle.net/forums/en/wow/topic/1922566146
https://eu.battle.net/forums/en/wow/topic/3225594605
https://us.battle.net/forums/en/wow/topic/1127489992
https://www.wowhead.com/forums&topic=115661
http://wowwiki.wikia.com/wiki/Dispel#Resists
http://wowwiki.wikia.com/wiki/Binary_spell

Is it possible to look into it please?
Thank you.

**Comment by Dranah** [comment]
Confirmed. It appears that on mania, full resists simply don't exist.

**How it should work**: Spells should be either binary (full resist/no resist) or non-binary (damage reduction of 10-20-30% up to 100%) behavior when it comes to being resisted.
Binary spells are generally effects such as CC, dispel, harmful debuffs that have an adverse effect (not only damage) basically everything that can either hit or miss but not be partially reduced.
Non-binary spells are damaging spells that can get their damage reduced by partial resists on a scale of 10-100%.
More detailed at: http://wowwiki.wikia.com/wiki/Formulas:Magical_resistance

**How it works here:** 
Binary spells cannot be resisted at all, they always hit.
Non-binary spells can be partially resisted on a scale of 10-80%. I could not produce a 90% or 100% (full resist) even with 800+ resistance value on my test char.
Note: this renders the mage talent "Magic Absorption" essentially useless as it only procs on full resists, which never happen on this server.

**Comment by Keader** [comment]
Cant be fixed right now.
It was implemented on Trinity here: https://github.com/TrinityCore/TrinityCore/pull/18933
And made some fixes later.
With my experience about this implementation, it cause alot of issues, some unfixed until now.
I realy dont see how port it to wow mania, without port more stuffs before it.

**Comment by Hajzlopuc** [comment]
Any news on this? It's pretty huge in pvp
