### ISSUE TITLE
[Raid] Temple of Ahn’Qiraj (AQ40)

### ISSUE THREAD

**Issue by WhitephoenixTheBunny** [WoWManiaUK/Redemption#2962]
After the patch 2.5.0, AQ40 got the doors back, now to progress in the raid you MUST defeat some bosses. After killing first boss ([The Prophet Skeram](http://www.wow-mania.com/armory/?npc=15263)) the first door (6686) go down.

After defeating the next bosses:
- [Battleguard Sartua](http://www.wow-mania.com/armory/?npc=15516) ;
- [Fankriss the Unyielding]( http://www.wow-mania.com/armory/?npc=15510);
- [Princess Huhuran]( http://www.wow-mania.com/armory/?npc=15509);
The doors (6680) to The Twins Emperor ( [Emperor Vek'lor](http://www.wow-mania.com/armory/?npc=15276) and [Emperor Vek'nilash](http://www.wow-mania.com/armory/?npc=15275)) should be open, **but they aren’t**, making like that progression impossibe.

After defeat the twins, the last door (6683) to [Eye of C'Thun](http://www.wow-mania.com/armory/?npc=15589)  / [C'Thun](http://www.wow-mania.com/armory/?npc=15727) should open, but the fight still have some issues #2804

Since Twins give some problems, boths doors (6680 and 6683) should open after defeating the 3 boss referenced, until the fight is fixed.

**Comment by Keader** [comment]
If still has issues, why dont have a open ticket for it?

**Comment by WhitephoenixTheBunny** [comment]
The Twin fight? Is doable, but can bug out. 

and since the doors were always open, ppl were skipping bosses

**Comment by Dranah** [comment]
That fix looks pretty untested to me.

**Comment by Keader** [comment]
Test now @WhitephoenixTheBunny
