### ISSUE TITLE
[Spell] Mend Pet triggers DMC: Greatness

### ISSUE THREAD

**Issue by crulinjr** [WoWManiaUK/Redemption#2965]
Atm the spell Mend pet is triggering the dmc: greatness when it shouldn't.
![wowscrnshot_010819_084019](https://user-images.githubusercontent.com/40045543/50851058-b4e5a500-1349-11e9-99c1-8c6be376ba30.jpg)

As you can see, im healing my pet, im not in combat but the trinket has triggered.

**Comment by Keader** [comment]
what is DMC my dear?
Can you post a link of our armory? ty

**Comment by crulinjr** [comment]
Darkmoon card: greatness

**Comment by crulinjr** [comment]
http://www.wow-mania.com/armory/?item=42987

**Comment by Keader** [comment]
Well it should...

Proc Flags has: 1024 (0x400) - Successful positive spell hit - that means heal.

And description has:

```
When you heal or deal damage you have a chance to gain Greatness, increasing your Strength, Agility, Intellect, or Spirit by 300 for 15 sec. Your highest stat is always chosen.
```

I can make a exception but.. is non-blizzlike

**Comment by Hajzlopuc** [comment]
Yes it definitely should proc from mend pet. 
![image](https://user-images.githubusercontent.com/32883164/50860939-91494b80-1397-11e9-9a65-1e38ae107aa8.png)
![image](https://user-images.githubusercontent.com/32883164/50860942-94dcd280-1397-11e9-9cb9-3e8889150f69.png)

**Comment by Dranah** [comment]
tooltip also states it can proc off heals too
this report is invalid

**Comment by crulinjr** [comment]
Yeah i dropped the ball right there. Thought the healing part was only for
Spirit and intellect. My bad.
