### ISSUE TITLE
[Spell] Lava Lash

### ISSUE THREAD

**Issue by JohnBrinkle** [WoWManiaUK/Redemption#2966]
The damage of the enhancement shaman talent spell "Lava Lash"  ID 60103
is not increased by 25% when the off-hand weapon is enchanted with Flametongue.
It doesn't matter if it is Flametongue or another weapon spell on any weapon -
the damage is always similar.
Tested as tauren shaman. Weapons: Abomination Knuckels (hc) & Gutbuster (hc)

**Comment by Keader** [comment]
Fixed.

**Comment by JohnBrinkle** [comment]
When will this be implemented on the server?
Can't confirm it yet.
