### ISSUE TITLE
[Graveyard] Rise of Suffering - Icecrown

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#2967]
Map: 571 (Northrend) Zone: 210 (Icecrown) Area: 4597 (Rise of Suffering) Phase: 1

How it works: Ghost flight gained in this area does not work properly to players who don't have riding skill to fly in northrend.
You get the fly mount but it will not fly, sticks to the ground.
How it should work: ghosts should be able to fly regardless of player riding skill

Note: it works fine if you land in other graveyards such as the one in Ymirheim.
There may be other broken graveyard spots too, however this one hold special importance, as ICC/fos/pos/hor parties are all teleported here upon releasing.

**Comment by squalllh1989** [comment]
fix this will be great, since many player doesn't buy the cold weather fly since they have a rocket that can fly them in northen, or you can leave it like that and remove the ablity to fly in northen of the rocket if they doesn't have cold weather fly, force them to get it :)

**Comment by wow-mania** [comment]
Will look into now

**Comment by Dranah** [comment]
This is still broken, but I have discovered another detail to the issue.
It bugs when you are inside one of the aforementioned dungeons (FOS POS HOR ICC) when you die and release.
If you die outside in Icecrown, you can fly properly after release.

**Comment by wow-mania** [comment]
I will probably either work for one or the other. Not both. The Graveyard need to be specific to a region.

**Comment by wow-mania** [comment]
Please re-test on dev.

**Comment by wow-mania** [comment]
Just tried on Redemption and both, diying near the grave and inside ICC work just fine.

**Comment by WhitephoenixTheBunny** [comment]
Not Fixed
I just dies on FoS NM, no riding skills, I couldn't fly on Gryphon

**Comment by wow-mania** [comment]
OK I will try something else on dev shortly.

**Comment by wow-mania** [comment]
I just tried on dev and they worked

**Comment by Dranah** [comment]
No change, tested dying in FOS and ICC just now, can't fly after release.

**Comment by wow-mania** [comment]
If you have no skill?
You should have the skill

**Comment by Dranah** [comment]
Of course without skill. That's the bug in the first place.
Just because you can't fly in IC without a rented mount (because u have no cold weather or expert riding), you should still be able to get back to your corpse if you die inside a dungeon.

**Comment by Keader** [comment]
Test now @Dranah

**Comment by Dranah** [comment]
Looks good, i can fly after release from dungeons, icc and outside too.
