### ISSUE TITLE
[Fishing/Item] Winter Squid / Raw Summer Bass drop

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#2968]
https://www.wowhead.com/item=13755/winter-squid
https://www.wowhead.com/item=13756/raw-summer-bass

These are seasonal fishing drops that should both drop in specific time of the year depending on calendar.

Description from wowhead:
"Raw Summer Bass and Winter Squid are seasonal fish. The catch changes at the September and March equinoxes. This means one can be caught in Winter, one in Summer. There is no way to catch Raw Summer Bass in Winter, or Winter Squid in Summer - except to wait a few months"

How it works atm: Summer fish appears to be still dropping, although it is pretty much winter atm.
Winter fish is not dropping.
How it should work:
Between Sept23-March22 only Winter Squid should drop, never Summer bass.

Note: Minmaxing raiders are in need of the winter fish for the agility buff it gives when cooked. So this is at high demand to be fixed.

**Comment by squalllh1989** [comment]
should be relate to a event flag somewhere

**Comment by Dranah** [comment]
None of the two fish are dropping now but i'm having periodically empty catches.

**Comment by Keader** [comment]
Try now darling :)

**Comment by Dranah** [comment]
UPDATE:
- Winter squid now drops as intended
- For now the summer version will be capable of dropping too, because is not possible to remove it from the drop without causing empty catches. This will be fixed by trinity sometime and then corrected as per keader.
