### ISSUE TITLE
[Spell] Shadow Word: Death

### ISSUE THREAD

**Issue by Ashamedlol** [WoWManiaUK/Redemption#2970]
Issue 1: The spell self-damage is being modified by %DMG buffs when it should ONLY duplicate the value of the damage you've done with the main spell.

Causes circumstances like this: 
![swd](https://user-images.githubusercontent.com/16576459/50970941-7a1b7280-14eb-11e9-8937-9d4a55f10451.png)
This is with the 30% self-damage reduction talent, which makes it as if it wasn't even reduced.

Issue 2: Shadow Word Death still costs HP when you execute a target.
![swd2](https://user-images.githubusercontent.com/16576459/50971095-da121900-14eb-11e9-9738-629141954bce.png)
"If the target is not killed by Shadow Word: Death, the caster takes damage equal to the damage inflicted upon the target."

Issue 3: Vampiric Embrace is healing you twice when using Shadow Word Death, even though the second damage shouldn't be considered your own damage.

IDs: http://www.wow-mania.com/armory/?search=Shadow+Word+Death#abilities  (Shadow Word: Death)
http://www.wow-mania.com/armory/?spell=15286 (Vampiric Embrace)

**Comment by Keader** [comment]
I dont understand the issue 1.

**Comment by Ashamedlol** [comment]
When you have Shadow Weaving, ICC buff, or arcane mage buff (etc, any %DMG buff), your second part of Shadow Word Death (the self damage part) will get modified by those buffs even though it's already amplifying the first Shadow Word Death, so the self-damage part for example is getting 20% bonus instead of just scaling with the 10% amplification towards the original Shadow Word Death.

**Comment by Dranah** [comment]
The backfire damage is supposed to be a fixed damage such as Wandering Plague or Improved DP we've been fixing before.
Currently the backfire damage scales with modifiers.

**Comment by Ashamedlol** [comment]
https://youtu.be/DMXM4D8vHgg?t=138

Notice the damage he recieves from Shadow Word Death not followed up by a heal/green text, Vampiric Embrace was up.

**Comment by Keader** [comment]
try now

**Comment by Keader** [comment]
Hmm I will fix it todat

**Comment by Keader** [comment]
Hmm, test now @Ashamedlol

**Comment by Ashamedlol** [comment]
Pain and Suffering now reduces the self damage of SWD.

**Comment by Ashamedlol** [comment]
Another thing: I don't see it duplicating crit number, only the flat one.
