### ISSUE TITLE
[QUEST] Supplies to Private Thorsen #2783 (Old Problem Back)

### ISSUE THREAD

**Issue by gantor2** [WoWManiaUK/Redemption#2971]
The old problem with this quest has resurfaced. It seems to be that his location changes when you pick up the quest and that may be the problem. Unsure.

**Comment by wow-mania** [comment]
NPC moves. There is no problem.

**Comment by Echinaceax** [comment]
for notes, janitor has a player with this issue, so i was asked to check

Standing at the camp, he has the quest delivery https://i.gyazo.com/f4bb04e4047bc73ed7b2e5a5c8f1a47d.mp4
When he starts his patrol he loses it, Player just need to wait until he returns to camp https://i.gyazo.com/f1db0a4f7ed7e0733224e9c951736462.mp4
