### ISSUE TITLE
Paladin "Guarded by the Light" not proc'ing 

### ISSUE THREAD

**Issue by Namol91** [WoWManiaUK/Redemption#2974]
The paladin talent "Guarded by the Light"(http://www.wow-mania.com/armory/?spell=53585) is supposed to reset the cooldown of "Divine Plea" (http://www.wow-mania.com/armory/?spell=54428) Every time you hit an enemy. I have tested both on a target dummy and multiple mobs and it does not reset at all. This is a game breaking bug for paladin tanks as it makes it very difficult to maintain mana without this ability. This leads me to believe most paladins aren't having this issue. I have tried relogging and reloading UI to no avail. Please help.

**Comment by wow-mania** [comment]
We will test it and if confirmed we will fixe it.

**Comment by Dranah** [comment]
You misunderstand that talent.
It "refreshes" your already active divine plea on yourself, does not reset the cooldown of the spell.
Try casting divine plea and hitting a mob, it will jump back to full duration on you. That's how it works and with this you can keep the spell running on yourself with 100% uptime so you won't have any issues at all.

**Comment by Namol91** [comment]
That is my bad then for misunderstanding the spell, I will confirm but I'm sure you are correct.

**Comment by squalllh1989** [comment]
![1](https://user-images.githubusercontent.com/27235989/51075249-9968fa00-16bb-11e9-971e-7b691da12947.png)
I play protection paladin a lot so i know that this is working properly or prot pala gonna be really suck because of getting oom every 120 sec when spamming spell to keep agro.
