### ISSUE TITLE
[Quest] Power of the Great Ones

### ISSUE THREAD

**Issue by jarvik76** [WoWManiaUK/Redemption#2976]
Quest 12762  "Power of the Great Ones" allows me to recharge the item at the pillar, but the NPCs say "invalid target" when trying to attack them, and do not respond to aggro range.
The NPCs are either:
http://www.wow-mania.com/armory/?npc=28079    (Frenzyheart Hunter)
http://www.wow-mania.com/armory/?npc=28078    (Frenzyheart Ravager)
There dozens in the area of south-west Sholazar and they are all passive.  Completed this quest a few days ago so I know it has worked recently.
(Launcher used, 2.5.1, cache cleaned, read-only unticked on folder)

**Comment by Drostthehunter** [comment]
I can confirm this, i just went to Sholazar Basin to try and do this quest. 1st part of the quest where you need to charge the crystal, is working as intended, but you can not target neither of the NPCs that are supposed to be killed as the 2nd part of the quest.

**Comment by Dranah** [comment]
The player cannot seem to gain/put at-war status despite being hated with the Frenzyhearts.

**Comment by wow-mania** [comment]
Have you tested this on dev?
Is this the result of a change in reputation with the faction?
Does it happen with all races?

**Comment by GMaymelek** [comment]
I recall a Night Elf Hunter and a Tauren Druid with this issue.

**Comment by Dranah** [comment]
Looks fixed to me, "At war" is now properly checked on both my chars (oracle and frenzyheart aligned) and I can attack the quest mobs too.

**Comment by jarvik76** [comment]
Thanks very much for the fix Janitor, confirmed I just completed this quest successfully.
