### ISSUE TITLE
Talisman of the Binding Shard!

### ISSUE THREAD

**Issue by Serraria** [WoWManiaUK/Redemption#2977]
I recently donated and received my Talisman of the Binding Shard [item=17782], everything about the item works fine (including the animation when you equip it) excluding the physical appearance that it is supposed to give on your character. I have tried relogging, taking everything off, etc. Obviously this isn't an important bug of any kind, I'm just curious if there is an easy fix, and to let you be aware of it. :) 

![wowscrnshot_011319_201458](https://user-images.githubusercontent.com/46574057/51084086-253c5e00-1770-11e9-9d36-688297c79044.jpg)
![wowscrnshot_011319_201543](https://user-images.githubusercontent.com/46574057/51084087-25d4f480-1770-11e9-8f59-7f2478c692fb.jpg)

**Comment by wow-mania** [comment]
Just looked into this and there is absolutely nothing we can do. 
The item was removed pretty much as soon as introduced so no sniffs available.
No examples on live, no videos, no info on the possible effect and very likely the effect has also been removed.
Just contact support if that makes the difference to you.
Thanks.
