### ISSUE TITLE
[Spell] Life Tap

### ISSUE THREAD

**Issue by Ashamedlol** [WoWManiaUK/Redemption#2978]
EDIT:
Health base value is broken on tooltip, scales with spirit on tooltip.

[Life Tap]     50% (for mana gained, health cost is unmodified)     Patch 3.3.3

Source: https://wow.gamepedia.com/Life_Tap
Spell ID: http://www.wow-mania.com/armory/?search=Life+Tap#abilities

**Comment by Dranah** [comment]
Tooltip is visually broken. Spell health cost should not scale with anything on 3.3.5
