### ISSUE TITLE
Quest Garments of darkness not working

### ISSUE THREAD

**Issue by Ezmegaz10** [WoWManiaUK/Redemption#2979]
Did it first with lvl 3 heal, then read the description.
logged out, vaited for npc to reappear, did it whit lvl 2, used fortify as well, nothing happened.
abandoned quest, picked up again, did lvl 2 spell + forify, no good neighter

**Comment by wow-mania** [comment]
Works. Also please read wiki on how to describe an issue.

**Comment by wow-mania** [comment]
There was an issue with NPC getting stuck.
I have fixed in dev. Should be deployed tomorrow.
Ask a GM to complete for you.

**Comment by GMZinius** [comment]
> There was an issue with NPC getting stuck. I have fixed in dev. Should be deployed tomorrow. Ask a GM to complete for you.

Reproduce steps are on the newest report #6014
