### ISSUE TITLE
[Item] Crimson Acolyte Gloves

### ISSUE THREAD

**Issue by jarvik76** [WoWManiaUK/Redemption#2980]
Gemming up Crimson Acolyte Gloves http://www.wow-mania.com/armory/?item=50766
and then attempting to refund it, makes the item non-interactive in inventory - cannot wear it, move it, put it in bank - goes grey and cannot further select it.
Only possible to interact with it after player has logged out & cleared cache
(Might be same with other tier gear)

Also don't recall getting any warning about gemming it would make it non-refundable - but this may be my memory...

**Comment by Dranah** [comment]
Gemming or enchanting does make an item non-refundable.
Not sure if the warning message pops up properly or not.
Nonetheless it's probably an error that occured because of that.

**Comment by WhitephoenixTheBunny** [comment]
gemming doesnt pop warning, enchant pops

**Comment by wow-mania** [comment]
This is common knowledge.
You damage the item or modify it in any way, gemming, enchant etc it becomes non-refundable
