### ISSUE TITLE
Chief Researcher Kartos not spawning for Alliance in Halaa, Nagrand

### ISSUE THREAD

**Issue by Scootsay** [WoWManiaUK/Redemption#2986]
For several days the Alliance have had Halaa control in Nagrand and I am needing to turn in the Oshu'gun Crystal Powder Sample for Halaa Research Tokens to redeem a mount has not spawned. This NPC is suppose to spawn when the Alliance are in control of Halaa.  I do not know if it requires all 15 guards to be spawned or not but the alliance have been sitting at 12/15 guards all weekend. Something is keeping this NPC from spawning. The only thing I haven't been able to test is having horde kill the guards and respawning them to see if he appears.

**Comment by Dranah** [comment]
"when alliance takes control" that means horde must first capture base and have allies recap it?
Shouldn't it spawn whenever alliance **has** control?

**Comment by wow-mania** [comment]
It does at the minute alliance take control. But if it gets killed it will not spawn again until alliance takes control again.

**Comment by Scootsay** [comment]
So I tested it with some horde friends and it does respawn after recapture. But said horde friend is going to let me farm them for the battle tokens i need for the mount i want, and we are both receiving Honor, but no Halaa battle tokens. Is this maybe a known issue or a bug?

**Comment by Echinaceax** [comment]
> So I tested it with some horde friends and it does respawn after recapture. But said horde friend is going to let me farm them for the battle tokens i need for the mount i want, and we are both receiving Honor, but no Halaa battle tokens. Is this maybe a known issue or a bug?

Made a separate report for the Halaa Battle tokens here #2989
