### ISSUE TITLE
[Spell] Suppression

### ISSUE THREAD

**Issue by bluemonstrr** [WoWManiaUK/Redemption#2987]
https://www.wowhead.com/npc=36789/valithria-dreamwalker#article
https://www.wowhead.com/npc=37863/suppresser
https://www.wowhead.com/spell=70588/suppression

Spell ID - 70588; Suppression.

How it should work; Reduces the healing done to the target by 10% per application. Channeled.

How it currently works; It does not have any affect on the boss.

How to reproduce; allow 10+ suppressers to channel on the boss, this should mean that the boss can no longer receive any healing at all, yet the healing % done to boss is still 100%

**Comment by Keader** [comment]
What spell are you using to heal?
I tested here with Rejuvenation and is working fine.

**Comment by bluemonstrr** [comment]
No, but it shouldn't be healable with 10+

**Comment by Keader** [comment]
I can reproduce now.

**Comment by Dranah** [comment]
Note, the Suppression effect is multiplicative, not additive. 
So it's not 10 + 10 + 10...etc % reduction, but the healing value is modded by 0,9 for each stack.
0,9x 0,9 x 0,9 .... etc accumulate to a total of 65,2% healing reduction at 10 stacks.
This means Valithria will always be healable for a reduced amount.

I just made a test and i can confirm it works good now:

Renew ticks for 364 base on a target without debuff. That's 100% healing.
With 1 stack of suppression, this is reduced by 10%:  364 x 0,9= 327.
With 2 stacks, the new value is reduced by 10% again: 327 x 0,9 = 294
...
With 10 stacks the spell heals for 34,8% of the original amount = 126
This checks out and works as intended now.
