### ISSUE TITLE
rogue lockboxes respawn rate

### ISSUE THREAD

**Issue by wowmaniasupportsucks** [WoWManiaUK/Redemption#2991]
the respawn rate on all lockboxes should be reduced.  I have been waiting for over an hour in badlands for the lockboxes to respawn so I can continue to level.  There is no reason for this to be so high it's not like you get rich off of what is inside.  These boxes are there for rogues to learn to unlock so it's for skill up if you are going to have it so high then just go ahead and get rid of the skill in general and make it so anyone and everyone can open any box.

**Comment by wowmaniasupportsucks** [comment]
Oh and the reason for the name is because I think it's really poor service for the gm to just send me to another site instead of dealing with the issue.

**Comment by wow-mania** [comment]
Unless you come with info on how this is a bug I cannot do anything about it.
Our rates are blizzlike. 
Please read our wiki on how to login an issue and provide the needed info so the developers can investigate and find out if it is a true issue.

**Comment by Dranah** [comment]
@wowmaniasupportsucks GMs are there to help if your character is bugged or stuck, not to solve whatever gameplay-problem you come across. Fixing a general bug belongs to the developers (=this github site), if it is confirmed to be a bug.
Badlands lockboxes have a varying respawn time from 5minutes to 2hours and varying respawn spots. This means the new spawn won't always be where the previous, you need to search around the fortress.
This is blizzlike.
