### ISSUE TITLE
Reputation of Aldor to Scryers

### ISSUE THREAD

**Issue by Irgnac** [WoWManiaUK/Redemption#2992]
This issue has been report before but the issue was close. My brother is having the problem he raise his aldor reputation to exalted and change to scryer to get the achievement https://www.wowhead.com/achievement=1205/hero-of-shattrath . His rep with scryer is honored but he can't do any quests because the rep appear with the "at war" on and can't be turn off
![wowscrnshot_011819_115427](https://user-images.githubusercontent.com/44279804/51397662-10691d00-1b18-11e9-96e7-ce8eaa627201.jpg)

**Comment by wow-mania** [comment]
Just tested and it works fine.
We had an issues a couple of weeks ago which may have caused this on the char.
Contact me via support email with the char name and I will fix it for you.
