### ISSUE TITLE
[Raid] Blackwing Lair - Lord Victor Nefarius

### ISSUE THREAD

**Issue by WhitephoenixTheBunny** [WoWManiaUK/Redemption#2993]
[Lord Victor Nefarius](http://www.wow-mania.com/armory/?npc=10162) - This is the last boss of BWL, and it start on his human form and friendly.

How is working:
When player gets in Nefarian’s Lair, players interact with Lord Victor Nefarius and the dialogue shows up, when we last line up shows "Please do" you can't click/interact and like that start the encounter.

![image](https://user-images.githubusercontent.com/31921098/51425955-52a76280-1bdb-11e9-903d-c5bc48ee62de.png)

**Comment by Keader** [comment]
try now @WhitephoenixTheBunny
