### ISSUE TITLE
[Faction] Aldor

### ISSUE THREAD

**Issue by NightSeekerr** [WoWManiaUK/Redemption#2994]
So, I'm switching from Scryers rep to Aldor rep and I got to Neutral with the Aldor. However, this happened: 

![wowscrnshot_011919_172808](https://user-images.githubusercontent.com/30464528/51428806-b009d680-1c10-11e9-891b-3e57d9f0cca7.jpg)

All of a sudden I became "At war" with the Aldor and I can't turn it off. I tried deleting my cache but it didn't help.

**Comment by fvicaria** [comment]
Please search before posting. I have already explained this issue.

**Comment by NightSeekerr** [comment]
I didn't know I had to search through the closed issues first. I see https://github.com/WoWManiaUK/Redemption/issues/2992

Does that mean I have to send support email?
