### ISSUE TITLE
[NPC] Spirit Waves - Halls of Reflection

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#2995]
The following NPCs spawn in waves before the first and second boss are encountered:
https://www.wowhead.com/npc=38175/ghostly-priest
https://www.wowhead.com/npc=38172/phantom-mage
https://www.wowhead.com/npc=38567/phantom-hallucination
https://www.wowhead.com/npc=38177/shadowy-mercenary
https://www.wowhead.com/npc=38173/spectral-footman
https://www.wowhead.com/npc=38176/tortured-rifleman

Issues:
1) Rifleman does not respond to aggro https://www.wowhead.com/npc=38176/tortured-rifleman
**How it should work:** 
While at long range, the Rifleman should always Shoot https://www.wowhead.com/spell=72208/shoot at his aggro-target (the tank)
If he's forced into melee range, he should start meleeing (for much weaker damage than his shoot).
**How it works atm:** 
The rifleman fully ignores threat list and Shoots at random targets throughout the whole fight.
Even keeps moving towards the wrong target he's shooting at.
Does not switch to melee when in melee range.

2) Phantom Mage ignores aggro and attacks in melee https://www.wowhead.com/npc=38172/phantom-mage
**How it should work:** 
The phantom mage should only cast spells and never move into melee or try to melee attack. 
Her main nukes https://www.wowhead.com/spell=72163/fireball and https://www.wowhead.com/spell=72166/frostbolt should always be targeted at her aggro-target (the tank).
**How it works atm:** 
The mage slowly moves into melee range between her casts and once there, she'll begin melee as hard as the other melees do, between her casts. 
She's not responding to aggro, continuously fireballs/frostbolts at random targets instead of the tank, and once she's close enough, she tucks in melees at the wrong target too between the casts.

3) Phantom Hallucination - https://www.wowhead.com/npc=38567/phantom-hallucination
Spawned by the mage's https://www.wowhead.com/spell=72342/hallucination
**How it should work:**
It should be used when the mage is at 50% health, unless the mage is CC'ed at that point. 
The Hallucination should have the same max and current health as the mage = 50% and also take 50% more damage from all sources.
Much like the mage herself, the hallucination should focus her single-target nukes on the aggro target (tank).
**How it works atm:**
It appears to be cast on a timer, does not happen if you kill the mage fast enough.
CCing the mage before he hits 50% health however does not seem to prevent it.
The Hallucination starts off full health, has 10k more health than the mage himself, and does not take extra damage from any source.
Also attacks random targets instead of the tank.

4) Phantom mage is using an ability http://www.wow-mania.com/armory/?spell=72121 Frostbite, which she's not supposed to have. I cannot find what this spell is or who is supposed to cast it but there's no evidence of this NPC using it on blizz, nor wowhead, nor wowwiki list it among her abilities, and you can't see this debuff applied on videos either.

Video from blizz: https://www.youtube.com/watch?v=B5ne4ozFyv4

**Comment by wow-mania** [comment]
Fixed 1, 2 and 3.
4 is AS-IS
![image](https://user-images.githubusercontent.com/12248683/51437105-382fc080-1c91-11e9-84ce-e6f91f1e0a8a.png)

**Comment by wow-mania** [comment]
All fixed.

**Comment by Dranah** [comment]
UPDATE:

1) Rifleman now only melees, never shoots - this need fix.
Also his melee attacks are far stronger than his Shoots.
Shoot hits for ~3k damage on my test char, and he melees for 5-6k.
He should keep shooting whenever he can and only start meleeing if his target is in melee range.
His melee attacks should be about half of his shoot damage ~ 1-2k max.

2) Phantom mage now works as intended, no longer attacks in melee. (fixed)

3) Hallucination spawn is now properly prevented by ccing the mage at 50% health (fixed)
Hallucination still spawns with incorrect health values. Should copy the current and maximum health vaue of the caster mage. (need fix)

4) The mage is now casting the correct spell ID 72171 (Chains of Ice) instead of Frostbite (72121) - fixed.

**Comment by Dranah** [comment]
- Rifleman now doesn't auto attack at all (nor melee nor shoot)

**Comment by Dranah** [comment]
no change
- rifleman chooses to go melee after 2 shots instead of shooting like a decent hunter
- rifleman melee twice as hard as his shots
- hallucination spawns with wrong health values

**Comment by Dranah** [comment]
UPDATE:
Rifleman is back to shooting, will not melee at all (as-is)
Hallucination health value stays as-is

**Comment by Dranah** [comment]
Ever since this fix went live, the instance has been acting up. The scripts did not behave same on Redemption as on my last PTR test.
Hallucination multi-spawn has already been corrected.
Remaining issue is the continuity of events, players on Red complain that the spirit waves stop spawning and they have to restart the event. This is still under testing, we don't know what triggers the bug.

**Comment by Keader** [comment]
Try now.
If is the bug that i'm thiking... was caused by corpse decay of Falric

**Comment by WhitephoenixTheBunny** [comment]
![image](https://user-images.githubusercontent.com/31921098/55233454-9e503b00-5220-11e9-9689-a291bd70af86.png)
Tank paladin
healer paladin
mage
2 hunters

**Comment by Keader** [comment]
??

**Comment by Dranah** [comment]
This needs to be pushed to Red to see if the problem stops (though I doubt it will fix it)
On Red I have spent 10+minutes fearing and ccing mobs after Falric death to allow his corpse to decay and didn't bug the instance so I dont think it's related to the problem...

**Comment by wow-mania** [comment]
Applied to Red this morning.
