### ISSUE TITLE
[NPC] Horde Warbringer - Dalaran / Org

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Redemption#2999]
https://www.wowhead.com/npc=32615/horde-warbringer

**_NPC as the top of Sunreaver's sanctuary stairs_**

- NPC is bugged
- Cant hand in (call to arms) Battleground quest
- Clicking "complete quest" isnt working 

![horde war](https://user-images.githubusercontent.com/39439201/51500281-c6a95c80-1dcd-11e9-86dc-163d8d4f49b5.jpg)

**Comment by Echinaceax** [comment]
- Checked the Warbringer in ORG, Its not working with him either

![org](https://user-images.githubusercontent.com/39439201/51502201-530b4d80-1dd5-11e9-8072-bc7ab5159e04.jpg)

**Comment by wow-mania** [comment]
Fixed. It will be applied today.

**Comment by Echinaceax** [comment]
Update
It broken again :)

- Seems that its only the daily (blue question mark) can be delivered
- But not the "call to arms" weekend win "call to arms" event.

every win in this weekend event "should" be completedible (but isnt) 

- So what its doing is only completing the day after (so its counting at daily)  

not meant to work that way :)
