### ISSUE TITLE
[Mount] High Priest's Lightsworn Seeker doesn't have wings when flying

### ISSUE THREAD

**Issue by SibirkoJ** [WoWManiaUK/Redemption#3001]
Hello team,

The mount "High Priest's Lightsworn Seeker (Holy)" which i obtained from  the mall - Gift of the Holy Keepers (Holy), does not seem to show wings when flying. They can be seen only when reversing with the mount but not when going forward. I have opened a ticket with the GM and he explained that this is a issue with all 3 of the mounts. Mine is Holy, the issue is common for Shadow and Discipline as well.

I have attached a-link from the wow-mania armoury for you to check:  
http://www.wow-mania.com/armory/?item=142219#see-also

Thanks in advance,
Kind Regards
Epsylon

**Comment by wow-mania** [comment]
Imported items do not always behave as they do in retail.

**Comment by wow-mania** [comment]
I will check if there is anything else that can be done. Maybe an animation missing somewhere.

**Comment by SibirkoJ** [comment]
Hello again,

Has there been any development on the problem ?

Kind Regards

**Comment by Echinaceax** [comment]
> Thank you for yhe help. The thing is , i saw like 2/3 weeks ago the same mount perfectly working on another player. Thats where i saw it first. And it worked with the wings and the feathers coming out of it and everything. Something must have bugged since then.

Hi SibirkoJ
Just a thought while your waiting...
Maybe test in both "launcher" and with "wow.exe" 

As i said (just a thought) 
hope it fixes (im saving for one) :)

**Comment by SibirkoJ** [comment]
Hello again,

I just tried with the Launcher and it is the same :( 
I can only see the wings when reversing with the mount, but not when going forward. 

Regards

**Comment by Echinaceax** [comment]
Hi, 
Ok was worth a try

**Comment by SibirkoJ** [comment]
yeah of course, thank you that you are working on it !! :)

**Comment by Echinaceax** [comment]
- Horde version also had this graphical bug

Backwards (with wings)

![backwards flight](https://user-images.githubusercontent.com/39439201/52520901-68a2c300-2c6f-11e9-80f7-1c3024d16126.jpg)

Forward (no wings) 

![flight no wings forward](https://user-images.githubusercontent.com/39439201/52520904-7eb08380-2c6f-11e9-9405-39c7e285ac38.jpg)

Side view ( swim type graphics) 

![graphical](https://user-images.githubusercontent.com/39439201/52520914-9851cb00-2c6f-11e9-874f-44cb44a7bffe.jpg)

**Comment by SibirkoJ** [comment]
Hmm yeah exactly the same with me. Im ally and the mount is Holy. Maybe from one of the restarts something broke ? Because it was working before.

**Comment by Echinaceax** [comment]
Something has yes,
if there is anything wow-mania can do, they will :)

**Comment by SibirkoJ** [comment]
Thats why i love you guys, everything is so well organised, there is no cheating and the whole server is without bugs and it works, also you have helped me several times with stupid mistakes i have made :D .
Also all the people i have brought to the server are so happy as well :).

So big THANKS to all of you ,the whole team !! <3

**Comment by Skelebonestheoriginal** [comment]
Bumping...
Just bought the Horde shadow version.  Problem is still there.
Many thanks!
Skelebones

**Comment by Echinaceax** [comment]
Thanks for bumping (i also have horde version) without wings. i dont use it and spent 250 pvp tokens on it
