### ISSUE TITLE
[Quest] Divination: Gorefiend's Armor

### ISSUE THREAD

**Issue by jarvik76** [WoWManiaUK/Redemption#3005]
The quest (http://www.wow-mania.com/armory/?quest=10634) has you kill Vhel'kur (http://www.wow-mania.com/armory/?npc=21801) and looting Gorefiend's Armor (http://www.wow-mania.com/armory/?item=30797).

I am wearing Spectrecles, I have tried re-wearing them, and abandoning/re-taking quest, and getting a new pair from the NPC, but Vhel'kur is still not visible.
2.5.1, launcher used, cache cleaned.
I do see there are two versions of the Spectrecles on the Armory, items 30719 and 30721, but it is not clear what the difference is, or if that would have an effect.  I'm not sure which version I have in my inventory.

GM Kratos has looked into and advised I seemed to have followed correct protocol for the quest, and suggested I raise a github issue.

I do see issue 541 raised in November 2016, but it had tags "Confirmed" and "Will not fix" placed and then closed, but I can't see any salient information on why that would be.

Thanks!

**Comment by wow-mania** [comment]
What is the issue?
I have not seen any explanation of what is happening and how you expected it to happen.
Please read our wiki on how to log an issue.

**Comment by jarvik76** [comment]
".... but Vhel'kur is still not visible....."

If it's not visible, I can't kill it, right?   What's unclear?

**Comment by Dranah** [comment]
The first version 30719 is for the first quest in the base to kill spirits. The second version 30721 is provided for the Teron quests.
I can see Vhel'kur with the spectrecles (30721) provided when you pick up this quest.
Surely he's nowhere near the spot he's marked on the map since he's flying around. Not sure if you went through his entire patrol route?
Other options are 1. character specific phasing issue, 2. he was recently killed and has a long ass respawn

**Comment by jarvik76** [comment]
i've been checking for a few days.  i'll fly down there now, since you can see him right now :)

**Comment by Dranah** [comment]
I am on the dev realm, obviously. I've no idea if he's up on Redemption.

**Comment by jarvik76** [comment]
ok so I just found him.  I have a feeling there is some phasing issue somewhere: there was something very odd:
the first time i flew into the ledge, all the NPCs were aggressive, even though I had the "Dragonmaw Illusion" transformation aura, and he definitely wasn't there.
I flew out, back in again and the NPCs had changed correctly to being friendly, and he was right there (he's so huge you can't miss him)
I didn't re-wear the spectrecles or change anything, literally just flew out of and into the Dragonmaw Illusion "aura zone" and he suddenly appeared...

**Comment by jarvik76** [comment]
Does not have a long respawn timer, he's already back again minutes after killing him

**Comment by Dranah** [comment]
Glad you're sorted. In the end the quest itself works fine, if there's problem with anything that could be the way your phasing is affected by other quest chains you completed (i suppose the netherwing one is to put you friendly with dragonmaw mobs). But if flying in and out fixes that, i don't think it really needs work.
