### ISSUE TITLE
Bugged Quest: Reconnaissance Flight

### ISSUE THREAD

**Issue by bahamut82** [WoWManiaUK/Redemption#3006]
# Quest: Reconnaissance Flight (Sholazar Basin)
Quest ID: 12671

Quest NPC: Pilot Vic <Cold Weather Flying Trainer>
(NPC for both start & end of quest)
NPC ID: 28746

The quest was bugged for me on two separate characters now already and I reported the bug ingame both times. This time GM Fairwinds told me to create an issue here on GitHub. There are two different glitch-states described in detail below. One of the glitch-states makes the quest impossible to complete.

Characters of mine which had the bug until now:
Koorika - Worgen Mage
Mienai - Nightelf Rogue

# What's supposed to happen during the quest:
The quest normally pops you into the Flying Machine next to the NPC and auto-pilots towards "The Avalanche" in the northeast of Sholazar Basin. The Flying Machine is quite slow, about the same speed as a slow flying mount (+150% movement speed). You're supposed to shoot down some bats during the flight when near The Avalanche. At some point near the huge undead elite "Urgreth of the Thousand Tombs" (ID: 28103) you will gain steering control of the Flying Machine. You need to fly back to the "River's Heart" and land on the landing spot next to the Quest NPC. The quest objective then is fulfilled.

# What happened for me instead:
## Attempt(s) with steering bug (can not finish quest in this glitch-state):
- Normal flight speed
- once I gained control over the Flying Machine I couldn't steer down/up only turn left/right.
- I couldn't steer down to the landing spot and was unable to finish the quest
- had to abandon the quest

## Attempt with speed-glitch (can finish quest in this glitch-state):
- Extremely high flight speed, completely unnatural, (about +600% or even more I would guess)
- Extremely high speed persists from start until the end
- Enemies you're supposed to shoot are barely loaded, because of the high movement speed
- Pretty hard to hit the landing skill (2nd vehicle skill) with the right timing to land
- Quest can be finished though

When my 2nd character (Mienai) had the same problem (steering bug, quest impossible) I deleted my cache, as advised by a GM during discussion of my first ingame ticket. Deleting the cache did not help though.

# Repro-steps (screenshots below):
1.) accept quest
2a.) is the vehicle at normal speed? If so following sub-steps apply:
I.) occasionally shoot attacking enemies with first vehicle skill
II.) wait until you gain control over the Flying Machine (somewhere in the middle of The Avalanche)
III.) try steering up/down
IV.) if you can't steer up/down the quest is impossible
2b.) is the vehicle at extremely high speed? If so following sub-steps apply:
I.) wait until you gain control over the Flying Machine (somewhere in the middle of The Avalanche)
II.) try steering up/down
III.) if you can steer up/down fly back to River's Heart
IV.) try hitting the second vehicle skill (landing) right on the landing spot (circle next to NPC)
V.) Quest objective is fulfilled
VI.) finish quest

Screenshot for step 1.)
https://i.imgur.com/kaYRIrJ.jpg

Screenshots for steps 2a.) II.) and 2b.) I.)
location top-view:
https://i.imgur.com/IxSkGp8.jpg
approximate perspective when gaining control:
https://i.imgur.com/Du4YPbK.jpg

Until now I only have 2 characters high enough to do the quest and both suffered from the bugs I've mentioned. I could not do the quest normally yet. When I get to this quest on my next character I'll probably try recording the issue entirely, if it happens again.

If you need to know anything else, let me know.

I'm using the WoW Mania client (downloaded freshly about 3 months ago and always updated via the launcher ever since).
I'm on WoW-Mania Version 2.5.1 right now.

Let me know if I can help in any way. (You might have guessed already - I'm a developer myself, so maybe there's some technical detail that I could investigate for/with you.)

Best regards!

**Comment by Dranah** [comment]
Hmmm, interesting. 
I've done a total of 14 attempts.
About 50% of them were bug-free and 50% of them were speed bugged with the camera breaking and the vehicle blinking around rapidly, making it extremely difficult to steer.
The quest was doable in each case nonetheless. 
Could not reproduce attempt where i couldn't steer up/down at all.
I failed to find any sort of logic behind why it sometimes works fine and sometimes doesn't, i've tried with multiple classes, different positions to pick up quest etc. It's total random.

**Comment by WhitephoenixTheBunny** [comment]
I tried 3 times tbh

**Comment by wow-mania** [comment]
Nothing we can do about that, unfortunately. I will research what can be done but this is a more generic issue and not related to the quest itself.

**Comment by jarvik76** [comment]
Had more reports recently this was behaving strangely, with players getting dropped into odd random zones e.g. Westfall, STV etc
Did another 7 test runs, including race/class combos of players reporting issue, and while on all of them the camera and "blinking" issues described in ticket above were experienced, the plane was still controllable in final phase & the quest still completable.  No odd "teleports" experienced.
Adding to notes on this, for reference use today.
