### ISSUE TITLE
[NPC/Pet] Doomguard

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#3008]
https://www.wowhead.com/npc=11859/doomguard
Summoned by http://www.wow-mania.com/armory/?spell=18540 or http://www.wow-mania.com/armory/?spell=47867

Multiple issues with this guy:

1) EDIT: Spawning as hostile mob is intended if the curse procs it. Issue is the low lvl.
**How it works atm:** Spawns as a level 58-70 mob when summoned by curse of doom (spell=47867)
This is possibly a problem with this spell http://www.wow-mania.com/armory/?spell=18662 "curse of doom effect"
**How it should work:** Should give you a lvl 80 Doomguard as the Ritual of Doom effect http://www.wow-mania.com/armory/?spell=60478, only it is not enslaved automatically, you have to do it yourself.

2) Weak melee attacks and low hp
**How it should work:** This guy is supposed to hit like a truck and be capable of tanking elites/dungeons. Much like the Infernal, his stat scaling should be near that of the Felguard, but with a higher base damage and health, and less AP buffs.
As per wowhead comments,
_"Dealing up to 1300 DPS the Doomguard is now a very viable pet to use in raids. Whenever the ritual is not on cooldown you can summon him for some extra DPS. Other than that he has great survivability, his HP pool seems to be around 40k. This is probably the most underrated tool in the warlock arsenal."_

^Note this is a comment from 3.0.3 so that DPS number is way above what other pets could push with naxxramas content gear on the warlock. (a felguard in naxx gear levels pulls near 900-1000 fully buffed). However on patch 3.1 the damage of Doomguard has been nerfed by 30% so that puts him down to about same level of damage as the Felguards. The health values received a nerf on 3.1 too, so instead of 40k you can calculate with ~28k with some buffs, slightly above the health of the Felguard, in naxx content. With an ICC geared lock, that could be easily 35-40k due to scaling.

Other comments:
_"As of Patch 3.1 the doomguard and the infernal are very much worth it.
They are a fine boost to DPS, they also do not attack raid members anymore, they simply despawn after the timer runs out.
the doomguard stays for 15 mins while the infernal stays for 1 min."_
From 3.3.0: _"Doomguards are, simply put, summonable tanks. I summoned mine in UP heroic for the for time. It prettymuch tanked Ymiron for the real tank (who settled for off-tank XD), LOL. "_

**How it works atm:**
- Melees for 40-50, is useless, no dps, no threat
- Has only 16k hp with bis geared owner

3) Spam Cripple/Rend
The Doomguard's abilities seem to have no cooldown (not even gcd), so whatever is set to autocast, the pet will use it infinite times and instantly ooms. (gives you a nice screen-freeze as well)
Need to add some kind of cooldowns or an interval for the pet to use these abilities (or both)
http://www.wow-mania.com/armory/?spell=20812 cripple
http://www.wow-mania.com/armory/?spell=21949 rend
EDIT: this only seems to be an issue with manually enslaved doomguards that spawn from Curse of Doom

**Comment by Dranah** [comment]
UPDATE:
No change on 1) and 2) both still need fix
3) the uncontrolled infinite autocast looks fixed on the COD spawns

**Comment by Dranah** [comment]
UPDATE:
Melee attacks are same state as those of Infernal. Still too low and does not scale.
Coefficients are missing for Rain of Fire (ID 4629) and Rend (ID 21949), both deal base damage atm.

**Comment by Dranah** [comment]
Remaining issues:
- Must spawn as a lvl 80 when proc'd by curse of doom
- Must fix AP scaling off owner's spell power (currently does same base damage with or without gear)
- Must fix base health and health scaling off owner's gear (currently 8k base hp, 16k with full geared owner
- Must fix coefficients for Rend and Rain of Fire (both spells deal base damage and are extremely weak and useless)
https://www.wowhead.com/spell=4629/rain-of-fire
_Rain of fire should receive a total of 6% of the warlock's spell power, which should be equal to 40% of the Doomguard's spell power. This is divided to 4 ticks then, making it 1,5%/10% per tick accordingly.
Source:https://wowwiki.fandom.com/wiki/Spell_power_coefficient_
https://www.wowhead.com/spell=21949/rend
_Note: the Rend ability has a flag "scales with item level" implying it gets increase similar to vehicle abilities, only considering gear level on the warlock, instead of raw stats like AP or STR that the pet gets from scaling. Not sure if this can be implemented, i'm fine with a workaround to simply grant the spell the same AP coefficient that warriors' rend has_

**Comment by Keader** [comment]
Test now @Dranah

**Comment by Dranah** [comment]
UPDATE:
- Curse of doom still spawns a useless lvl 60 (need fix)
- Melee damage now scales with the owner's gear (fixed)
- Mana value of the Doomguard has doubled but health value is even lower than before, he's incredibly squishy. Health need to be increased, in a similar manner to the infernal. (need fix)
- Rend now does decent damage (fixed)
- Rain of Fire coefficient is too large, each tick seems to receive about 16% of owner's spell power. Not a big deal as the ability has 5minutes cooldown, but should be reduced. (need fix)
- Doomguard does not seem to receive proper hit and expertise values off the warlock's hit rating. He's constantly missing, being dodged and getting parried with 17%+ hit on the warlock. Even his Rend ability is getting dodged (need fix)
Side note: the infernal appears to inherit these stats properly.

**Comment by Dranah** [comment]
Ok uhh...
1) Health values
Doomguard's health has increased, though still not quite where it should be (about 20% lower still than it's meant to be)
But, side effects:
Infernal lost 3k health.
All other warlock demons (voidwalker,felhunter,succubus,imp,felguard) received about +8k-9k extra health.
Can you revert this and make sure only doomguard is affected?

2) Curse of doom now spawns level 80 doomguard but it has still same stats as the level 60 version.
3k hp and 4k mana, this does not change when enslaving. This is still dysfunctional.
Need to receive same stats as he gets when summoned by 60478 (ritual spawn)

3) Rain of fire now hits even harder , about 37% SP coeff per tick instead of 1,5%.
It needs to be reduced, not increased. Still need fix.

4) Doomguard now inherits hit cap properly, but still misses expertise. With 17% hit on the warlock, he should also be expertise capped (=no dodged attacks). Need fix.

**Comment by Dranah** [comment]
UPDATE:
- Doomguard now has 30k+ with a fully geared owner and infernal got back his missing 3k too. (fixed)
- Other pets health is however still 8-9k higher than intended (need fix)
- Rain of Fire now gets even higher, approx 42% of the warlocks SP per tick. What the heck? Just revert it back to the first version that was about 16%, it was still the best so far... (need fix)
- The Doomguard refuse to go melee targets if he has Cripple on autocast (need fix)
- Doomguard now gets properly expertise capped too (fixed)
- Curse of doom: "I can't make this creature scale after charmed" - you shouldn't. It needs to receive proper stats when it spawns, still as a hostile target, not after it is enslaved. It should be capable of killing your group if you don't do something with it.

**Comment by Keader** [comment]
```
Rain of Fire now gets even higher, approx 42% of the warlocks SP per tick. What the heck? Just revert it back to the first version that was about 16%, it was still the best so far... (need fix)
```
Not possible.
Before was 10% i changed it to 1.5% when you tested and now is 1%.
I'm getting 968 in each tick, with a warlock with 3018 of fire damage.

Cripple issue fixed.

Curse of Doom: dont metter, in the end nothing will scale after control, so why lose time with it?
And i dont have any value of damage, and how it should scale with level.

**Comment by Dranah** [comment]
I just tested again:
.cast 60478 (summon ritual-of-doom doomguard)
Naked test: 0 spell power > Doomsy Rain of Fire ticks for 73
Geared test: 3234 spell power > Doomsy Rain of Fire ticks for 1185
1185-73 = 1112 bonus damage, 1112/3234 = 34,38% spell power coefficient per tick.
How did you calculate 1%?

- Cripple issue fixed (fixed)
- Fine, curse of doom spawns stay cosmetic... (as-is, cant fix)
- Other demons health is still buffed. It appears they are getting their health scaling mods twice.
Equipping any piece of gear appears to shift their health values twice. Once for the correct amount (75% of the stamina on the piece of gear), and then once more for 75% of the 75% stamina they gained. (about 56% of the warlock's stamina gain)
The base health values are correct. This scaling issue affects Imps, Voidwalkers, Felhunters, Succubi and Felguards. You can even see when you summon them they do not spawn with full health, as the delayed extra stamina is added only afterwards.
I saw you had opened and fix confirmed a thread about pets getting double scaling. I believe this could be the same issue. How were these guys not fixed...?

**Comment by Dranah** [comment]
Ok other pets health is corrected.
Doomguard is now as good as it gets.
