### ISSUE TITLE
[Spell/Interaction] Death Coil heals when reflected

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#3011]
http://www.wow-mania.com/armory/?spell=49895
DK ability that normally deals damage but heals when cast on friendly undead (like ghouls)

**How it should work:** When the ability is reflected by spell reflection of warriors, mobs or anything, it should reflect damage upon the death knight, not heal - unless the DK is affected by Lichborne, which turns them into undead temporarily.
**How it works atm:** Currently the reflected number is healing the death knight, as if they were undead, even without Lichborne.

**Comment by Dranah** [comment]
No longer heals but also does no damage when reflected. (Testing with warrior spell reflect)

**Comment by Keader** [comment]
test now @Dranah

**Comment by Dranah** [comment]
The warrior's reflect is consumed but the spell is not reflected. Warrior takes damage.

**Comment by Keader** [comment]
Fixed Dranah.
Tested now in ptr.

**Comment by Dranah** [comment]
Still nop :S

**Comment by Keader** [comment]
Now is fixed.
Was a old fix of janitor fucking everything.
