### ISSUE TITLE
Unholy infusion did not complete

### ISSUE THREAD

**Issue by Billas1** [WoWManiaUK/Redemption#3012]
I did the unholy infusion quest on Jan 27 (US time) and the quest did not complete. I had shadow's edge equipped and did the infusion then proceeded to kill pp. Was watching the timer and still had about 15 seconds left on the timer before it expired. There were multiple witnesses in the raid that seen it and told me to put in a ticket/report. This is the second time I tried it and it did not complete. Because the first on did not complete I figured I did something wrong so I made sure I did everything right this time and confirmed with multiple ppl in the raid to make sure I was doing all the steps correctly before we tried it.

Thanks

**Comment by wow-mania** [comment]
Works.

**Comment by TheManiax** [comment]
![image](https://user-images.githubusercontent.com/14857593/51861896-a1c76300-2352-11e9-8133-46eb3f6fd2fe.png)
![image](https://user-images.githubusercontent.com/14857593/51861926-b6a3f680-2352-11e9-8492-0e8079c2dff7.png)
It works fine @Billas1 
Make sure to hit PP with Shadow's edge at least one time after you did the infusion and got the "shadow infusion" buff.
