### ISSUE TITLE
[Spell] Vanish

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#3015]
https://www.wowhead.com/spell=1856/vanish
Does not properly drop threat.

**How it works atm:** 
If an enemy is engaged in combat with someone else too, not only the rogue, using Vanish will put you in stealth and drop the enemy's target to someone else (this works fine), but not remove you from threat list. As soon as you leave stealth mode, you'll get back aggro since your threat values are retained.
**How it should work:**
It should always remove you from enemy threat list, reseting your threat to 0.

Note: it seems to work fine if you're fighting a mob alone, probably because the encounter is reset once you're dropped as a target, so your threat is also gone
Note2: the ability does not and should not wipe combat, only threat (this has been fixed already, but it'd be nice to not screw it up now)
Note3: Could be related to fix of combat-wipe. Need @Keader to investigate it.

**Comment by Keader** [comment]
Test now Dranah.
I replaced to a new way to reduce threat in 100% without remove target of threat list.

**Comment by Keader** [comment]
It was never real implemented.
You before just skipped it because combat was removed.
Now it should set you threat to 0, without remove ou from threat list.
@Dranah

**Comment by Dranah** [comment]
Now removes threat as intended.
