### ISSUE TITLE
[Quest] The Purification of Quel'Delar

### ISSUE THREAD

**Issue by Anthonhed** [WoWManiaUK/Redemption#3017]
http://wow-mania.com/armory/?quest=24553
http://wow-mania.com/armory/?quest=24564
http://wow-mania.com/armory/?quest=24594
http://wow-mania.com/armory/?quest=24595
http://wow-mania.com/armory/?quest=24596
http://wow-mania.com/armory/?quest=24598

**How it works at the moment:**
- You need to go into a raid Group
- You need to talk with the NPC to get TPed into Sunwell Plateau
- Use Quest item
- Wait for the dialogue
- Loot the Restored Quel'Delar

**How it should work**
- You don't need to be in a raid group
- When you talk with the NPC you should get TPed into Sunwell Plateau
- Use Quest item
- Wait for the dialogue
- Loot the Restored Quel'Delar

> WoWWiki https://wowwiki.fandom.com/wiki/Quest:The_Purification_of_Quel%27Delar
> Speak to any Warden of the Sunwell to zone in. Players will be teleported into the actual Sunwell instance, although phased.

Also as seen in [this](https://youtu.be/NLHm-e8v1L8?t=223) video, the player is not in a group with anyone else. Video from June 2010
It was also reported earlier on the [Trinitycore GitHub ](https://github.com/TrinityCore/TrinityCore/issues/4866)

**Comment by wow-mania** [comment]
As-is. There is an NPC there to complete quest for years now.

**Comment by GM-Kratos** [comment]
Probably as-is like you say.
However, I just want to add that we do get tickets about this issue every now and then.

And not a top priority issue since it has the workaround of going in a group :)

**Comment by GM-Kratos** [comment]
I found out that with the quest, when you enter SWP you get to phase **2048** of the instance and without the quest you are in Phase **1** of SWP.

Is it possible to remove raid requirements for that specific phase?

![image](https://user-images.githubusercontent.com/43315225/52164389-e6efea00-26f0-11e9-8561-d0e041005a7d.png)
![image](https://user-images.githubusercontent.com/43315225/52164384-d6d80a80-26f0-11e9-8eb3-36423ff9260a.png)
