### ISSUE TITLE
[Raid][Spell] ICC Gunship / Killingspree

### ISSUE THREAD

**Issue by Anthonhed** [WoWManiaUK/Redemption#3019]
http://wow-mania.com/armory/?spell=51690
http://wow-mania.com/armory/?zone=4812
http://wow-mania.com/armory/?npc=37117

**How it works**
When you cast Killing Spree on Kor'Kron Battle-Mage you fall through the boat and deal no damage to the Battle-Mage.

**How it should work**
You should stay ontop of the boat and deal the Killing Spree damage to the Battle Mage. 

This was only tested fron the Alliance PoV, I do not know how it is for a Horde Rogue
![image](https://user-images.githubusercontent.com/26274880/52156952-eb35ec00-268b-11e9-877f-e794d4e9de7b.png)

**Comment by Keader** [comment]
Test now in ptr.

**Comment by Kitzunu** [comment]
This is still an issue and nothing changed.

![image](https://user-images.githubusercontent.com/24550914/52491052-7ea87900-2bc6-11e9-8232-b177749122a9.png)

**Comment by wow-mania** [comment]
Can this be retested on dev, please.
Is it consistent or random?

**Comment by Kitzunu** [comment]
Current situation is that you do not fall through the boat when you use killing spree.
Was something changed?

However the Battle-Mage takes 0 damage from Killing Spree, other mobs do take damage from KS

**Comment by Keader** [comment]
Fall issue fixed.
About killing spree damage, i need more time to research.

**Comment by Kitzunu** [comment]
You no longer fall through the ship.

@Keader I am getting confused about the damage atm though.
no DMG Numbers appear on the screen when I use KS on the mage, but the mage do take damage.

So it is possible there is only a visual bug?
