### ISSUE TITLE
[Spell] Gargoyle Strike - scaling

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#3021]
http://www.wow-mania.com/armory/?spell=51963
Cast by http://www.wow-mania.com/armory/?npc=27829
Summoned by http://www.wow-mania.com/armory/?spell=49206
Unholy DK end tier talent.

1) Cast time 
**How it should work:** Should scale with the caster DK's spell haste rating and spell haste buffs (such as Bloodlust) snapshot in the moment of cast.
_Example:
Calculation with 6,65% spellhaste (218 rating) on the DK:
2 / 1,0665 = 1,87 sec cast time on Gargoyle Strike.
Calculation with 30% spellhaste (bloodlust) on the DK:
2/1,3 = 1,53sec cast time on Gargoyle Strike._

**How it works atm:** Does not scale with any haste. Cast time is fixed 2second.

2) Attack power coefficient
**How it should work:** Gargoyle should have a base 33,3% AP coeff, which is then increased to 40% with 5/5 impurity (that pretty much every UH DK has)
**How it works atm:** Gargoyle has base 40% AP coeff, which is then increased to 50% with 5/5 impurity.
_Detailed: we have previously taken the 40% AP coeff which can be found in all sources, but did not account for impurity. Most of these sources (such as wowwiki) already considered impurity._

**Comment by wow-mania** [comment]
can you re-check this one please.

**Comment by Dranah** [comment]
No change, haste scaling need to be implemented.

**Comment by Keader** [comment]
Test now.

**Comment by Dranah** [comment]
UPDATE:
- Haste still does not affect gargoyle strike (need fix)
- AP coefficient has increased to 66%. Probably a double dip of 33? (need fix)

That was a good round.

**Comment by Keader** [comment]
Test now.

**Comment by Dranah** [comment]
Interesting. The spell now shows some kind of haste scaling but it makes no sense.

1) Bloodlust is a 30% boost and is expected to make cast time 2 / 1,3 = 1,5sec.
Tested cast time with BL is 1,7sec. (Theory: calculates half, as if it was only 15% boost)

2) Unholy presence should have no effect on the cast time at all, but if it did, it would make the cast time 2 / 1,5 = 1,7.
Tested cast time was 1,8sec. Makes no sense, probably calculates half the effect like BL, but it should not scale the cast time at all.

3) Haste rating from gear does not seem to modify the cast time on its own, it is the same 2sec with or without whatever amount of haste from gear. Haste from gear SHOULD affect it, calculating as spell haste.

4) Permanent haste buff effects don't affect the 2sec cast either (nor wrath of air, nor windfury). Spell haste effects should.

5) Improved Icy Talons talent's 5% innate haste seems to affect it and scales correctly 2/ 1,05 = 1,9sec cast. Too bad it's a frost talent that Unholies cannot normally pick up at all, I only took it for test purposes. It's just interesting that this alone does the correct math - perhaps helps fix the others too.

6) Paired with Improved Icy Talons, haste rating from gear starts working. 4,6% haste from items and 5% from Imp. Icy Talons together make the cast time 2/  1,096= 1,8sec.

So, I absolutely don't understand the logic behind these, but it still needs fixing.

- The attack power coefficient is now proper 33%, together with impurity becomes 40%.

**Comment by Keader** [comment]
Tested here and HAST from GEAR affect it.
It's based in BASE_ATTACK speed percent, not SPELL HAST.
Spell cast is always based in Owner BASE_ATTACK, not gargoyle "status".
Amount of hast is calculated when gargoyle is summoned.

**Comment by Dranah** [comment]
UPDATE:
- Gargoyle strike now scales with melee haste rating and melee attack speed boosts (fixed)
- Cast time has been gcd capped at 1,00sec which is possible to achieve with 100% haste added up from gear, haste potion, bl/heroism and buffs or procs. (fixed)
- The gargoyle should snapshot haste values of DK at the moment of summon. Currently it dynamically updates/rechecks after each cast, so the cast time changes around. This need fixing.

**Comment by Keader** [comment]
Test now @Dranah

**Comment by Dranah** [comment]
The cast time now properly snapshots and does not change for duration.
However, the cap appears to have raised to 1,3sec. No amount of haste can reduce it below :/
Can this be corrected back to the 1sec gcd cap?

**Comment by Keader** [comment]
fixed.

**Comment by Dranah** [comment]
All good now.
Gargoyle now scales with melee haste of the DK properly, snapshotting the stats, buffs and procs in the moment of summon. Cast is GCD capped at 1sec.

**Comment by LockecoleSiren** [comment]
> All good now. Gargoyle now scales with melee haste of the DK properly, snapshotting the stats, buffs and procs in the moment of summon. Cast is GCD capped at 1sec.

Im curious, where did you get the 1sec GCD cap from? Has this been confirmed from older blizzlike logs?
