### ISSUE TITLE
[Quest]  Whelps of the Wyrmcult

### ISSUE THREAD

**Issue by jarvik76** [WoWManiaUK/Redemption#3022]
Quest 10747   Whelps of the Wyrmcult:  http://www.wow-mania.com/armory/?quest=10747
Use item "net" 31129 on the whelp npc 21387
As per the quest text It should drop item 31130 into inventory without having to kill the whelp.

There were some odd behaviours that were intermittent, witnessed by GM Kratos.  Possibly the changes in retail patch 2.1.0 were not fully correct.  
It sometimes seemed to not create the item in the inventory, or credit the "kill" only sometimes.
Since the charges on the net is limited to 10, this is a problem as one cannot get a replacement net, and cannot complete the quest without more charges.

This seems particularly problematic if one is using blackcult disguise (item 31122, spell 38156), if one is combining for efficiency with quest 10748 (also found in the same cave)

Also, the eggs in the cavern are meant to spawn the whelps, but it is on a strangely long timer.  i *think* this is object 184839.  Perhaps the timer on the whelp spawn could be reduced.

I realise this is an intermittent problem so might be difficult to replicate, but believe it's worth further investigation.

**Comment by wow-mania** [comment]
Works just fine.
![image](https://user-images.githubusercontent.com/12248683/52165503-a2b51780-26f9-11e9-9407-55b894c886ed.png)
Make sure you are in range.
