### ISSUE TITLE
Wrong Event Start and End dates

### ISSUE THREAD

**Issue by GM-Kratos** [WoWManiaUK/Redemption#3023]
Most of the World events have the wrong Start and End dates, which makes them not match with the calendar ingame

These are the Events that does not have the correct Start and End dates on the Armory according to the Calendar, but also added the correct Start and End times.

| Event | Start Date | End Date |
| ------ | :-----------: | :----------: |
| Lunar Festival | 28/01 | 17/02 |
| Love is in the Air | 05/02 | 18/02 |
| Noblegarden | 22/04 | 28/04 |
| Childrensweek | 29/04 | 05/05 |
| Midsummer Fire Festivals | 21/06 | 04/07 |
| Hallow's End | 18/10 | 31/10 |
| Pilgrim's Bounty | 25/11 | 01/12 |

**Dates in Day/Month**

**Comment by GM-Kratos** [comment]
As an example I will take Love is in the air 

![image](https://user-images.githubusercontent.com/43315225/52171368-23a4fb00-275c-11e9-9435-f70b8dcb0ed9.png)
![image](https://user-images.githubusercontent.com/43315225/52171371-33bcda80-275c-11e9-9ba1-ad2ccd5d1d7b.png)

**Comment by wow-mania** [comment]
I still need to confirm if this is a valid issue.
Holidays will fall in different days every year. I am confident this is correct but need to confirm.

**Comment by GM-Kratos** [comment]
This might just be an armory error, and correct ingame.

I checked the details for Love is in the air, and the Armory says it's active, but checking ingame it's not.
![image](https://user-images.githubusercontent.com/43315225/52176586-05b7b480-27b5-11e9-9edc-2ad96c7dbafe.png)
![image](https://user-images.githubusercontent.com/43315225/52176594-1405d080-27b5-11e9-9357-a57829607b9a.png)
![image](https://user-images.githubusercontent.com/43315225/52176596-19631b00-27b5-11e9-99b6-29b30634bcb0.png)

So possibly only the armory needs to be updated to the correct data

**Comment by wow-mania** [comment]
This is an issue with the Armory not the game. Calendar in-game show correct dates.
I will try to refresh armory.
