### ISSUE TITLE
[Quest] The Eye of Haramad

### ISSUE THREAD

**Issue by cathyr1** [WoWManiaUK/Redemption#3027]
This quest http://www.wow-mania.com/armory/?quest=10982 seems bugged. The NPC don´t give me that one even when exalted and succesfully completed http://www.wow-mania.com/armory/?quest=10981.
Instead, he´s still repeating http://www.wow-mania.com/armory/?quest=10975.
![quest](https://user-images.githubusercontent.com/30184491/52235189-b2805780-28c3-11e9-90b4-5f74a40faa0c.png)

**Comment by wow-mania** [comment]
This is not the NPC that gives the quest. You have to summon it in a different location.
