### ISSUE TITLE
[Quest] Nexus King Salhadaar

### ISSUE THREAD

**Issue by jarvik76** [WoWManiaUK/Redemption#3028]
Quest 10408.  Kill Nexus King Salhadaar.
Nexus-King Salhadaar (NPC 20454) stays inactive after destroying the 3 conduits using the Protectorate Disruptor (item 29618)
He does not engage, simply stays floating in the air, untargetable.

**Comment by WhitephoenixTheBunny** [comment]
Quest: http://www.wow-mania.com/armory/?quest=10408

Checking
