### ISSUE TITLE
Savage Saronite armor set issue

### ISSUE THREAD

**Issue by Nytpersun97** [WoWManiaUK/Redemption#3029]
Hello, the Savage Saronite Armor set has the appearance of one of the Lower tier plate armor sets on the alliance side, like the Field Marshal set. Thought you should be informed of this issue.
 
![saronite armor](https://user-images.githubusercontent.com/47347705/52260365-bd92b200-28da-11e9-93fe-3dd1df3d1bd7.jpg)
![470531](https://user-images.githubusercontent.com/47347705/52260373-c08da280-28da-11e9-97c2-3bfc0f1f48f6.jpg)

**Comment by wow-mania** [comment]
As is. We used the entries for other purposes.
