### ISSUE TITLE
[TALENT] Ardent Defender-NO PROC

### ISSUE THREAD

**Issue by Enmaiaeiou** [WoWManiaUK/Redemption#3030]
**How it should work:** Damage that would take you below 35% health is reduced. In addition, attacks which would otherwise kill you cause you to be healed (amount healed based on defense). This healing effect cannot occur more often than once every 2min.

**How it works atm**: From Saturday to Monday It only procs when you are below 2% health.  From the test I run today it does not proc anymore, whatever your % health is.

**Comment by Dranah** [comment]
I cannot reproduce this issue.
Both the death prevention and the damage reduction works alright to me.

Mob damage above 35% health: 4,3k~
Mob damage hitting me from 36% to 25% and under: ~3,5k
Death prevention proc'd at 100% health to prevent being oneshot by a boss. I remained at 100% health as the damage was negated and it did overhealing.
Death prevention proc'd at 5% health to prevent being killed by last swing of a mob and healed me up to 22% (i have no defense on test char).

If you can provide more information I can look to reproduce it, but for now I can't find any issue.
