### ISSUE TITLE
[Pet] Hunter/DK pet's health scaling (not regression)

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#3031]
Sources: https://wow.gamepedia.com/Hunter_pet#Pet_scaling
https://bigredrhino.wordpress.com/pet-stats/

So this issue existed for a long long time, but it was only noticed now when I recalculated pet stats after fixing the issue with scaling auras. (these few days when hunter pets had lost nearly all scaling both in damage, armor and health - that issue was fixed by reverting the changes which broke it)

Now all stats are calculated properly, except health, which is back to being too high.

**How it should work:** 
- Base pet stamina at lvl 80 should be 361 and base pet health 2582
- Hunter pets are meant to receive 45% of their owner's stamina, this can be increased to 54/ 63% with 1/2 or 2/2 Wild hunt pet talent.
- This value (361+45%HunterStam) should be then multiplied by 1,12 if you have pet talent 3/3 Great Stamina, making it 404+ 50,4%HunterStam
/This stamina value can be further multiplied by raid buffs /
- Stamina is then converted to health points by a x10 multiplier 
- All pets receive an extra 5% multiplier to that
 _"Patch 3.1.0 (2009-04-14): All Cunning, Ferocity, and Tenacity pets now have identical bonuses - +5% Health,+5% Armor,+5% Damage. "_
- This is then added to the base health which is 2582 at lvl 80.

_Example1:
Level 80 naked hunter has 129 stamina, pet wolf at lvl 80 base 361+58 from hunter.
Taking Great Stamina 3/3, this becomes 469 stamina total.
This adds 4690 x10,5 4924 health to the wolf base 2582 =  7506 health.
Taking 1/2 Wild hunt increases the stamina contribution from 45% to 54%, which is 361+69 stamina, multiplied by 1,12 from Great stamina, totals 481 stamina.
This adds 4810x1,05=5050 health to the wolf base 2582 =  7632 health._

_Example2:
Level 80 average-geared hunter with 21k hp test subject has 1456 stamina, pet wolf at level 80 base 361+655 from hunter.
Taking Great Stamina 3/3 this becomes 1137 stamina total.
This adds 11370x1,05 =11938 health to the base 2582 = 14520 health.
Taking 1/2 Wild Hunt increases stamina contribution to 54% which is 361+ 786 stamina, multiplied by 1,12 totals 1284 stam.
This adds 12840x1,05=13482 health to the base 2582 = 16064 health._

**How it works atm:** 
- Base pet stamina at level 80 is only 356 and base pet health appears to be only 1681
- At the moment they receive double amount, 45+45% of owner's stamina, which is then increased to 54+54% or 63+63% with 2/2 Wild Hunt.
- Great Stamina 3/3 does not properly multiply this. It adds about 7,2% instead of 12%. This seems to happen because it only affects the first half of the bonus stamina the pet gets from hunter (the correct amount they should get) and does not affect the extra doubled amount.
- This stamina is then properly converted to health with x10 and receives the 5% modifier as intended.

_Example1:
Level 80 naked hunter with 129 stamina, pet has base 356 + 58+58 from hunter.
Taking great stamina 3/3 increases this to 1,12x (356+58) + 58 = 521
This is converted to 5210 x 1,05 =5470 health + 1681 base = 7151 health.
Wild Hunt 1/2 increases the contribution to 1,12x (356+69) + 69 = 545 stam.
This is then converted to 5450 x 1,05 = 5722 health, added to the base 1681 making it total 7403 health._

_Example2- lvl 80 hunter with 1456 stamina. Pet turtle lvl 80 has base 356 + 655+655 from hunter, total 1666 stamina. This is increased to 1787 by Great Stamina 3/3 which is barely 7,2% extra.
Wild Hunt 1/2 increases the contribution to 356+786+786 making it total 1928 stam. That should then be increased to 2159 by Great stamina, however it is only increased to 2065. This is calculated as 1,12 x (356+ 786) + 786.
So at 2065 stamina the pet gains 20650 x 1,05 = 21682 + 1681= 23363 health._

As you can see this means the scaling is quite overpowered and hunter pets have much more health than they should. However the base values require fixing too, so that the health values won't fall below the intended numbers.

**Comment by Dranah** [comment]
ADDENDUM: Same issue affects DK ghouls too. Their STR scaling seems doubled too.

**Comment by Dranah** [comment]
Bump! @Keader this issue significantly affects gameplay, especially the DK ghouls being op.

**Comment by Keader** [comment]
Hmm, test now.

**Comment by Dranah** [comment]
1) Ghoul
- Ghouls no longer receive their stam/str scaling auras twice.(fixed)
- Base health is incorrect, should be 5342, currently only 4551 (need fix)
Opened new thread for other scaling issues.
2) Hunter pet
- Base scaling of 45% is now working as intended (no longer doubles - fixed)
- Base stamina is still 356 instead of 361 (need fix - tweaking issue)
- Great stamina talent (ID 61688) does not properly multiply this base value. After 3/3 talent taken, base stamina becomes 391 which is only 10% of increase. (need fix - tweaking issue)
Note: The added stamina from hunter is multiplied correctly.
- Wild Hunt (ID 62758) has broken in a manner that the increase is only applied if the hunter modifies their stamina(buff, unequip gear, etc), it does not take effect otherwise. The boost disappears on each relog, can only be reactivated manually by modifying the stamina value. (need fix - this is a major issue) 
- Base health value is still wrong, should be 2582 but is only 1681 (need fix)

**Comment by Keader** [comment]
Idk where you get BaseHealth = 1681... because in game is 5161.
The rest, fixed i think.

**Comment by Dranah** [comment]
Number displays fixed.
Wild Hunt now properly applies whenever the pet is active. (fixed)
Base health as-is, conflicting info on calculation.
Health scaling from owner now works as intended. (fixed)

Problem: Attack power/damage of pet got screwed up, a full icc geared hunter's pet barely does above 300 dps on dummy now. This need to be reverted. (Note: on redemption the damage is still okay, well above double of it.)

**Comment by Dranah** [comment]
Please revert all but the Wild hunt fix. The rest are unimportant and a lot of shits broke.
Ghoul hp now double scales again.

**Comment by Keader** [comment]
Test now.

**Comment by Dranah** [comment]
- Ghoul hp fixed (fixed)
- Hunter pets are still doing half the damage they do on Red. I've tested with near full buffing in icc they can barely get above 600 dps on PTR. I don't really understand what happened, it seems their attack power is much lower, base AP missing or something, because the +AP matches.
Oddly, on Redemption now both the health and damage of pets is working properly, only Wild Hunt talent is broken in the way I described. Is it possible to copy the AP scripts from Red to PTR and then copy the wild hunt fix from PTR to red?

**Comment by Keader** [comment]
And now?

**Comment by Dranah** [comment]
200 fixes later:

UPDATE:
- Base health values for hunter pets and ghouls have been corrected (fixed)
- Health scaling for hunter pets and ghouls have been corrected (fixed)
- Damage and armor values of Hunter pets are back to normal (fixed)
- Visual display of stamina and base stamina values remain as-is, they are cosmetic anyway. (as-is)
- Wild hunt is now properly applying at all times (fixed)
