### ISSUE TITLE
[Item] Design: Infused Twilight Opal

### ISSUE THREAD

**Issue by cathyr1** [WoWManiaUK/Redemption#3033]
This item http://www.wow-mania.com/armory/?item=41796 is currently missing in the game. It should drop from Anub'arak in Heroic Azjol-Nerub (https://wow.gamepedia.com/Infused_Twilight_Opal) but it doesn´t. Its actually the only one missing JWC northrend recipe.

**Comment by wow-mania** [comment]
Fixed. Item has a 12% chance.
