### ISSUE TITLE
[Pet] Hunter/DK pet's hit scaling

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#3035]
Patch 3.2.0 notes state that "If a player is at their appropriate spell hit chance or hit chance maximum, their pet will be at the maximum for spell hit chance, hit chance, and expertise. If they are below the maximum, their pet will be proportionately below those maximums."

Used to work sometime, not sure what broke it or when.

**How it should work:** As per the description above, hunter's ranged hit cap is 8%. So if a hunter has 8%+ hit from gear (talents dont count), their pet should be hitcapped and expertise capped for all of their abilities.
**How it works atm**: with 8,5% hit from gear on my hunter, my pet is continuously missing both their melee auto attacks and special abilities such as Bite or Claw. Oddly, spells such as Spirit Strike do not seem to miss.
This leads me to think their ranged hit chance is properly converted to spell hit chance for abilities that run on the spell hit table, however melee-based attacks are not getting any hit or expertise converted.

EDIT: Affects Ghouls too.

**Comment by wow-mania** [comment]
Why a separate issue?  #3031

**Comment by Dranah** [comment]
Because #3031 has existed for at least a year, it was just never noticed/reported.
This hit issue was however broken just now, it worked fine a week ago. I'm nearly certain is a side effect of all the tweaking on pets recently.

**Comment by Keader** [comment]
Test now @Dranah

**Comment by Dranah** [comment]
Looks good.
