### ISSUE TITLE
WOW mania Crashing when Entering RHC

### ISSUE THREAD

**Issue by Willsmite** [WoWManiaUK/Redemption#3038]
Crashed twice while entering 2 different Dungeons through the Random Dungeon Finder on heroic difficulty with a fatal error.
Happened once while entering HOR HC then Happened back to back on entering the Violet Hold HC...
I re logged again and this time it did not occur again.
please instruct me if this is a problem on my PC setup or is it something that is known on the Server.

**Comment by WhitephoenixTheBunny** [comment]
Contact a GM in-game. But you need use the mania ccustom launcher.

Btw, I had long time an issue like that, turns it was questhelper addon lagging and crashing me.
