### ISSUE TITLE
DK Ghoul - Night of the Dead Talent

### ISSUE THREAD

**Issue by Liamyloo** [WoWManiaUK/Redemption#3039]
Hi, 

I hope whoever is reading this is very well!

This has just come to me today, I've logged onto my UH DK (Which I haven't done for months) and joined a quick 10NM ICC. Do note that this was an easy LK Kill so the issue I'm raising won't be down to poor raid.

The main issue is, the pet taking too much damage. The talent specifically says 
![image](https://user-images.githubusercontent.com/28461676/52540004-bb1dd580-2d7c-11e9-8895-bac025ef4072.png)

If we take this example on Sindragosa.. her frost aura ticks for approximately 2k-4k every few seconds, let's take 1k damage per second for example, this 1k damage per second should only be doing -100 to my pet, my pet has 38k hp (unbuffed) and thus it should take 6.3 minutes to kill my ghoul with no healing or extra damage taken into account, I'm not sure if it was just a hunch but I had to summon my ghoul 3 times during that fight as he kept dying. 

The same occurred on Rotface, my ghoul being killed my Slime Spray, with BQL he got killed by shroud of sorrow and her bloodbolts etc. 

During this entire time it wasn't like the healers weren't trying to heal him but it was essentially like having an 11th squishy cloth player wherin I almost had to summon him at least 2 or 3 times each boss.

As before, I'm not sure if this is simply a problem which I'm not used to given I haven't played him in a while but it seems something worth investigating as -90% AoE damage should at least allow him to survive more than twice in a single pull.

**Comment by Dranah** [comment]
Confirmed, the talent applies the AOE reduction properly to Gargoyle and Army of the dead, for some reason the ghoul isn't getting it. Possibly got screwed up among the other scaling auras.

**Comment by Dranah** [comment]
The ghoul now properly benefits from the AOE reduction.
