### ISSUE TITLE
[Pet] DK ghoul scaling II. (AP, Haste and armor)

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#3040]
Sources: https://wowwiki.fandom.com/wiki/Risen_Ghoul
https://www.wowhead.com/forums&topic=146346
https://www.youtube.com/watch?v=Cp3nIhf2tfk
> on this video you can see an authentic 3.3.5a unholy DK with a ghoul, you can see how the ghoul attacks much more frequently than every 2.00 sec his melee swings are however nowhere as strong as on mania. ~430-440 melee swings with 2377 unbuffed STR on the DK + horns on both DK and ghoul. With same stats, here on mania the ghoul swings for nearly double.

- Ghouls should receive 100% of the owner DK's melee haste, both from gear and buffs/auras. This scaling is dynamic, updating constantly unlike the gargoyle who snapshots when summoned. Currently their 2.00 swing timer is fixed and does not scale with the owner's haste (need fix)
- Ghouls should convert 1 STR to 1 melee attack power. Currently they convert double, 1 str = 2 attack power. This makes their melee attacks much stronger than intended. (need fix)
- Ghoul appears to scale with armor of the DK. This is also not intended, ghouls should not inherit any armor. (need fix - tweaking issue, not a game breaker)

Overall these issues currently balance each other in a manner that the ghoul melee swings are much stronger than intended but he melees less frequently due to not getting his haste scaling...
So these need to be fixed at same time to keep things balanced.

**Comment by Keader** [comment]
Hmm test now.

**Comment by Dranah** [comment]
- Haste scaling works now (fixed)
- Armor is no longer scaling (fixed)
- STR conversion is still double of the intended (need fix)

**Comment by Keader** [comment]
Test now.

**Comment by Dranah** [comment]
- STR conversion fixed (1:1) (fixed)
- base AP value still missing (need fix)
- Ghoul now benefits from raid-wide haste auras twice, as intended (fixed)

**Comment by Keader** [comment]
And Now?

**Comment by Dranah** [comment]
UPDATE - Summary:

- Ghoul base AP added (fixed)
- Ghoul STR conversion corrected (fixed)
- Ghoul haste scaling properly (fixed)
- Ghoul does not scale with armor or AP (fixed)

The Ghoul's overall DPS didn't change much, but it behaves much more blizzlike. While his melee damage reduced drastically, he's also swinging much faster since he now properly scales with haste.
