### ISSUE TITLE
[Spell] Killing Spree sometimes falling to hit targets in movement

### ISSUE THREAD

**Issue by Keader** [WoWManiaUK/Redemption#3041]
Sometimes killing spree miss in targets moving.
It is caused by wrong little spell range.

Test case: Put a character in movement (press num lock key) and try use killing spree on him.
All damages need hit.

**Comment by svijetlonosa** [comment]
killing spree also does not work in Ruby Sanctum on Boss Halion in 25man version HC and NM in physical /fire realm.
As so in NM version of raid you can not use it at all in HC version you can use it only ones Living Infernos come with meteor strike.

**Comment by Kitzunu** [comment]
Hits every time on a moving target now
