### ISSUE TITLE
[NPC] Private Thorsen

### ISSUE THREAD

**Issue by k1ll3r** [WoWManiaUK/Redemption#3042]
The npc is suppose to go on a walk from time to time and you need to protect him from 2 adds and he gives you the quest "Jungle Secrets" but instead of that he doest even went to battle the 2 adds he continues walking back and you are unable to get the quest chain he starts :)

**Comment by WhitephoenixTheBunny** [comment]
Quest giver: http://www.wow-mania.com/armory/?npc=738
Quest: http://www.wow-mania.com/armory/?quest=215

I will test in a while

**Comment by WhitephoenixTheBunny** [comment]
The NPC's now are spawning, and he gives the quest ;)

![image](https://user-images.githubusercontent.com/31921098/52634147-579bc100-2ebe-11e9-93ee-224e810f1690.png)
