### ISSUE TITLE
[Raid] ICC10NM LK fight

### ISSUE THREAD

**Issue by Dioden101** [WoWManiaUK/Redemption#3044]
5 times now we have had a DPS interupt the cast after they got taken with "Harvest soul", reading log it seems like "destroy soul" is cast as if the friendly NPC is dead meaning the DPS inside dies. (Friendly NPC wasnt even close to death when it happens) 
It works fine when a healer been inside, its only with DPS it seems to happen.

**Comment by Keader** [comment]
> Inside Frostmourne
> Inside Frostmourne, King Terenas' spirit (an NPC) fights with the Spirit Warden (a mob). Upon entering, players get the Harvest Soul buff, which increases damage done by 100%, but kills after 60 seconds. The buff is removed when leaving Frostmourne. Players leave Frostmourne when the mob is dead.
> 
> This means that the add must die within 60 seconds. The NPC deals nearly enough damage to do the job by himself, but he does need support. The channeled spell from the add (Soul Rip) alone is enough to kill Terenas - it must be interrupted. Tanks should take over the add. Healing classes should heal Terenas. All classes should DPS the add as much as they can, and interrupt Soul Rip. Stunning the add is also very helpful, since it heals itself for 50% damage dealt. It is vulnerable to most forms of CC and interrupts that affect Undead creatures. Restoration Druids can use  [Incarnation: Tree of Life] form to do both healing and damage quickly while in Frostmourne.
> 
> If either the player or the NPC die inside Frostmourne, Arthas gains +200% damage for 15 seconds.

Checked my self in code, and everything looks fine.
Destroy soul is casted when terenas die inside frostmourne.
And Npc cast each X seconds Soul Rip, that kill terenas if is not interrupted.
