### ISSUE TITLE
[Quest] Battle of the Crimson Watch - Crimson Watch, Shadowmoon Valley - #10781

### ISSUE THREAD

**Issue by Revner17** [WoWManiaUK/Redemption#3045]
Hello,

I ran into an issue with this quest. When I first picked it up from the Crystal Prison all NPC's spawned but I was killed and had to revive. Once I was resurrected I abandoned the quest and reacquired it from the same locations but NPC's failed to respond and after pick up a few minutes later I was prompted with "Battle of the Crimson Watch Failed" I tried this a couple times and was unable to get it to work. The following NPC's were suppose to spawn upon pick up.

https://www.youtube.com/watch?v=8vJJHVD93vo 

https://www.wowhead.com/quest=10781/battle-of-the-crimson-watch

**Comment by wow-mania** [comment]
Tried multiple times. Dying in between.
![image](https://user-images.githubusercontent.com/12248683/52700113-3941ce00-2f6f-11e9-9615-83fd921926bd.png)

**Comment by Revner17** [comment]
Thank you sir, myself another guild member couldn't get it to happen, even had GM Fairwinds investigate it. Glad to know it is working.
