### ISSUE TITLE
[Quest][NPC] It's All Fun and Games , The Ocular

### ISSUE THREAD

**Issue by Dunnington882** [WoWManiaUK/Redemption#3046]
http://www.wow-mania.com/armory/?quest=12887

Hello WowMania Team,

For this quest i should target NPC named "The Ocular" and use quest item for completing the quest. 
The NPC is missing i cant target it.
Thank you.

**Comment by wow-mania** [comment]
Works

**Comment by Dunnington882** [comment]
![wowscrnshot_021319_111531](https://user-images.githubusercontent.com/47590903/52704410-cb060700-2f80-11e9-8d90-61135baf084c.jpg)

Still not working

**Comment by Dranah** [comment]
You need to target the Ocular geez.... it'll attempt to self-cast if you have no target selected. Which is why it says invalid.
Screenshot: https://imgur.com/iiK9sNn
