### ISSUE TITLE
Starfall During Unchained Magic (Sindragosa)

### ISSUE THREAD

**Issue by wowmania-Kindly** [WoWManiaUK/Redemption#3047]
Hello!
I have taken up Balance druid, and noticed that when you cast: starfall - http://www.wow-mania.com/armory/?spell=53199, while having Unchained Magic - http://www.wow-mania.com/armory/?spell=69762.
It gives you way too many stacks of instability - http://www.wow-mania.com/armory/?spell=69766.
On Retail you would get 1 stack, the one for casting Starfall, however on Redemption you gain stacks for each of the projectiles that are launched by the starfall buff.
I searched around for links to verify my claim that it should work that way, i found some Balance druid discussions about the Sindragosa encounter, and they mention nothing of being cautious of this mechanic, i hope that is enough to satisfy you that i am right.

Heres a quote from this forum thread: https://www.mmo-champion.com/threads/694406-Boomkins-what-are-you-doing-for-Sindragosa
_"As to what I do when I get unchained magic, we're currently restricted by raid leaders to only stack it to 6 before letting it fall off until the fight is more farm mode for us. So I just keep MF/IS refreshed, **use Starfall if it's up"**_
Thank you in advance for looking over my post, and thank you for working continuosly on the server.

**Comment by Keader** [comment]
Fixed.

**Comment by Dranah** [comment]
Unchained magic now only triggers backlash on the spellcast of Starfall.
