### ISSUE TITLE
[Spell] Rune Strike

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#3048]
ID 56815
http://eu.battle.net/wow/en/game/patch-notes/3-3-3
Bug fixes: "Rune Strike: This ability can now proc Necrosis and Blood-Caked Blade"

**How it should work:** replacing one of your melee attacks on the next melee, casting Rune strike should still grant you the extra damage a regular melee strike would via Necrosis or a BCB proc.
**How it works atm:** Rune strike is not triggering either of the bonus damage from those talents, making it potentially worse than a regular melee swing would be with those procs.

**Comment by Keader** [comment]
Fixed.
