### ISSUE TITLE
[Quest] Blast the Gateway - Living Flare does not grow in power & randomly disappears

### ISSUE THREAD

**Issue by jeyrella** [WoWManiaUK/Redemption#3049]
Quest ID 11516.  The spell 44879 does summons NPC 24916 "Living Flare" correctly , but that NPC does not seem to grow in power no matter how many Fel Sparks you kill in the area.

This means the Living Flare never becomes the Unstable Living Flare (NPC 24958), so quest is uncompletable.   (Quest is to use the Unstable Living Flare to blow up the legion gateway.)

2.5.2, launcher, cache cleared

**Comment by WhitephoenixTheBunny** [comment]
Not 100% of this, need more eyes to look at it

Quest: [Blast the Gateway](https://www.wow-mania.com/armory/?quest=11516)
Quest item: [Sizzling Embers](https://www.wow-mania.com/armory/?item=34253)

When [Living Flare](https://www.wow-mania.com/armory/?npc=24916) got fully charged (8 stacks) e becomes an [Unstable Living Flare](https://www.wow-mania.com/armory/?npc=24958); it's appearance should change to "green" - as the icon suggest - and when going to the gate and completing like that the quest. 

ATM, it will randomly disappear while doing the quest, or it will disappear fully charged, after a few seconds (when going to the gets) or if you kill more elementals


A YouTube Video of the quest [here](https://www.youtube.com/watch?v=khWyssRJy9w)


![image](https://user-images.githubusercontent.com/31921098/156410636-d4f0ad85-fc12-4d07-9703-8a7ad337fe6d.png)

**Comment by Echinaceax** [comment]
Confirmed still bugged PTR 

![image](https://user-images.githubusercontent.com/39439201/156574170-537cf21d-0133-45ec-9d7b-a9c93b296f70.png)

**Comment by Rushor** [comment]
fixed, model will now change correctly and it becomes a green big ball

**Comment by Echinaceax** [comment]
Confirmed green ball fixed in PTR 
However the pathing still an issue as stated by Phoenix above https://i.gyazo.com/665aca7903b796bc35d09c3d0ed776aa.mp4

**Comment by Rushor** [comment]
ignore pathfinding now and should move smother now, nothing more we can do here

**Comment by Echinaceax** [comment]
perfect, much better thanks 👍 
https://i.gyazo.com/338360f9eb72dd50dfffedec4ec1d678.mp4
