### ISSUE TITLE
[Spell] Scourge Strike (Shadow)

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#3050]
http://www.wow-mania.com/armory/?spell=55271

Found some evidences recently that the Shadow damage portion of this ability SHOULD benefit from **certain** effects (mainly +damage mods)
To be clear, I highlighted certain because while originally after the 3.3.3 redesign it double dipped everything (including crits, as it could separately crit), blizz has fixed/limited the double dips afterwards to prevent the spell being OP. We're still left with a few double dips that were in effect on 3.3.5 and should add to the damage of the ability, which is currently too weak on Mania.

**How it should work:** SS (shadow) should not always calculate the extra damage as a raw 12/24/36% of the original physical damage, but should be further scaling with **certain** damage boost effects.
Confirmed double dipping effects:
- Blood Presence (15%)
- Desolation (5%)
- Two handed specialization (4%)
- Bone Shield (2%)
- Raidwide 3% damage boost (sanctified retribution/arcane empowerment/ferocious inspiration)

These damage mods will increase the physical damage portion of SS , which indirectly increases the shadow portion and then boost the shadow portion itself, for a doubled effect.
There are also boosts that don't apply to the physical effect but should increase the Shadow damage portion:
- Black Ice (10%)
- 13% magic debuff (ebon plague/curse of elements/earth and moon)

SS will not double dip into effects that will reduce it's damage.
Non listed damage mod buffs and talents should also NOT affect the shadow portion as blizzard realized that'd make the spell overpowered and fixed them before the patch went live (outbreak, RoR, ICC buff, t10 2piece bonus etc)

**How it works atm:** SS (shadow) always deals a fixed 12/24/36% of the physical damage portion, taking zero benefit from any other effect itself.

Sources:
http://www.arenajunkies.com/topic/118334-death-knight-obliterate-vs-scourge-strike/
This speaks of:
_"the ScS shadow portion benefits twice from blood presence, desolation and two hand spec (both aren't eligible for PvP unholy anyway), but apparently doesn't double dip into neither Rage of Rivendare nor Outbreak. Don't ask me why, it just doesn't (if it would, a 3 disease-strikes' shadow portion should be dealing roughly 1,5 times the damage of the physical portion, which it clearly doesn't - or 1,2 times the damage in case of only RoR double dipping)"_

Another source that speaks of double dips: https://www.wowhead.com/forums&topic=141587
_"Scourge Strike double dips into many talents and buffs/debuffs there is. Many people might wonder why a Blood subspec is superior to Black Ice which buffs the shadow portion of SS by 10%. So let's take a look at what we get by speccing into Blood, that's a total of 14% crit for SS (5% crit on everyting), 2h spec which gives us another 4% (double dips into SS), the static AP from Bladed Armor and some RP through Butchery. "_

Another source confirms double dips for specific boosts:
https://www.mmopro.org/talent-specs/3333-unholy-dps-pve-3-3-3-updated.html
_"Bone Shield, Desolation, Two-Handed Weapon Specialization, Blood Presence, Ferocious Inspiration, Sanctified Retribution, and Arcane Empowerment are all buffs or talents which are double dipped."_
_"...some buffs and talents will affect the physical strike (thus increasing the damage of the shadow strike) but then also affect the shadow strike directly. Blood Presence, as previously mentioned, is one such buff. It will increase the damage of the physical strike by 15% which will then increase the damage of the shadow strike by 15%"_

**Comment by Keader** [comment]
Check now.
But i realy think it looks like so much overpower...

**Comment by Dranah** [comment]
Works as intended now.
Not overpowered at all, it still does only about half the damage of the physical portion after all the extra boosts it receives. It can now deal reasonable amount ~10% of your total dps on the recount, as it should.
