### ISSUE TITLE
scryer turn on at war

### ISSUE THREAD

**Issue by saritax** [WoWManiaUK/Redemption#3053]
my scryer reputation look at war and can be cahnge i done the quest," city of light and choice scryers them the problem begin
Gm fix me 3 time son game but when y run again the game  scryer turn at war again

**Comment by wow-mania** [comment]
Please read wiki on how to login an issue properly. You have given us nothing here.

**Comment by saritax** [comment]
![angelicax](https://user-images.githubusercontent.com/47676857/52888583-93fc4500-317c-11e9-869e-2153a6f06c2a.jpg)
i try to explaiin better 
in scryer  at war is marked
a GM in game fix it and remove mark on war and game run ok
when i relaunch the game , im at war again
before the quest https://www.wowhead.com/quest=10211/city-of-light
i was neutral ,affter i done the quest i be friendly but at next log on game show im at war

**Comment by wow-mania** [comment]
I fixed your char.
