### ISSUE TITLE
unholy infusion didnt work

### ISSUE THREAD

**Issue by Cyligod** [WoWManiaUK/Redemption#3054]
Just did Prof putricide i infused in phase two and tanked in phase 3. It didnt update the quest. He had my SM buff and he was infused but still no quest update

**Comment by Kitzunu** [comment]
Please read the wiki on how to report an issue.

As for this issue I tried it and it works.
![image](https://user-images.githubusercontent.com/24550914/52905377-c28c2580-3239-11e9-83ac-be655ab82199.png)

Make sure you actually infuse your weapon and then hit PP with it.

**Comment by Cyligod** [comment]
I did infuse on phase 2 after the orange i got to 100 and infused then i tanked in phase 3  he had the buff and still didnt get the quest update

**Comment by Cyligod** [comment]
entire raid saw the infuse go off and me lose the 100 energy and him have the debuff.. and i hit him because i was tanking in phase three. after the transition

**Comment by Cyligod** [comment]
he def had the debuff.

**Comment by Cyligod** [comment]
i can understand maybe not hitting him if i was a dps but i was tanking him =P

**Comment by Kitzunu** [comment]
You must have done something wrong, because it clearly works as I tested it on Dev right after this issue was opened.

**Comment by Cyligod** [comment]
Like i said entire raid saw me infuse and tank and win so i didnt do anything wrong=/ like i said IF i was dps i can understand me not hitting him but As to SM was my only weapon and me tanking in phase 3 only thing could be a bug and it didnt register some reason which i have no clue.
