### ISSUE TITLE
[Quest] "When Smokey Sings, I get violent"

### ISSUE THREAD

**Issue by jarvik76** [WoWManiaUK/Redemption#3055]
Quest 6041 "When Smokey Sings, I get violent"
The blue marks in the ziggurats are supposed to despawn when item 15736 is used on them.
They don't, meaning that the next time the item is used once the mobs have regenerated the quest count does not update.

Since there is only 8 charges on the item, and only 7 unique spawn sites, it means player cannot distinguish which sites have respawned. There means it is possible (and probable) to run out of charges, as there is always a duplicate, and cannot identify it is respawned or not to prevent this.

To prevent this, the mark should despawn once the item is used, so that a charge is not expended on the item without the quest updating.

launcher. 2.5.2.

**Comment by Kitzunu** [comment]
I can confirm that the Mark of Detonation do not despawn most of the times.
It does happen that it despawns but this is still an issue.

When it doesn't despawn, it let's you use the item which makes it consume one of the 10 charges but doesn't give credit for it. 

I also discovered that it respawns way too quickly, on Mania it respawns about after 1.50-2 minutes, while in retail it respawned after 3 minutes

https://www.wowhead.com/quest=6041/when-smokey-sings-i-get-violent#comments
>By impala454 (350 – 1·2) on 2008/01/12 (Patch 2.3.2)
>Respawn rate on the mark is 3 minutes. "Protector" mob respawns in 6 minutes, and is a non-elite level 58 as of 2.3. Easily soloed as a 55 prot/ret Paladin.

Latest WoWHead comment about the respawn times were patch 2.3

![image](https://user-images.githubusercontent.com/24550914/52906801-7c908b00-3254-11e9-98a4-9ebdff7390bb.png)
I am not sure this is the correct Object ID, but when I looked up this object the only ID i found was `177668`

The quest is not incompletable if you wait the time that it is supposed to take for it to respawn, but the object is not despawning like it should.
