### ISSUE TITLE
minor Forge of souls bug

### ISSUE THREAD

**Issue by boohe91** [WoWManiaUK/Redemption#3056]
rogues while stealthed get targeted by the Soulguard Bonecasters and get hit by their aoe spell witch breaks stealth so we cant use stealthed attack abilitys

**Comment by Kitzunu** [comment]
No issue.

If the rogue is close enough the Souldguard Bonecaster will see the rogue and will cast https://www.wowhead.com/spell=69080/bone-volley and hit the rogue making him go unstealthed

My best advice is to attack him before he casts the ability :)

**Comment by boohe91** [comment]
im talking when the rogue is way away from him

**Comment by boohe91** [comment]
grab a tank and a rogue start fighting with rogue in stealth mode ull see what i mean

**Comment by Dranah** [comment]
It is an aoe spell, it does not even require a target.
It will hit any enemies in a 30 yard radius, stealthed or not.
The ability is interruptible and should be interrupted every time, since it deals high damage to your party - that is the intended way of dealing with it.
