### ISSUE TITLE
[Item] Romantic Picnic Basket

### ISSUE THREAD

**Issue by WhitephoenixTheBunny** [WoWManiaUK/Redemption#3057]
The item [Romantic Picnic Basket](http://www.wow-mania.com/armory/?item=34480) is one of the requirments for the achievment [Lonely?](http://www.wow-mania.com/armory/?achievement=1291).

**How it should work:**
When clicking on [Romantic Picnic Basket](http://www.wow-mania.com/armory/?item=3448) the player would be buffed with [Romantic Picnic](http://www.wow-mania.com/armory/?spell=45123) (criteria for  the achievment [Lonely?](http://www.wow-mania.com/armory/?achievement=1291), the item will long for hours before disappear.

**How is working**
When clicking on [Romantic Picnic Basket](http://www.wow-mania.com/armory/?item=3448) nothing happen, and after several clicks on it, the item disappear.

Note
The item was working fine until yesterday.

The event, [Love is in the Air](http://www.wow-mania.com/armory/?achievements=155.187), ends today and for some people is the last achievment needed for [Fool For Love](http://www.wow-mania.com/armory/?achievement=1707) / [Fool For Love](http://www.wow-mania.com/armory/?achievement=1693) and get the title ["<Name> the Love Fool"](http://www.wow-mania.com/armory/?title=135)

Relatable issue:
#858

**Comment by wow-mania** [comment]
Fixed in dev please check.

**Comment by WhitephoenixTheBunny** [comment]
Nope

**Comment by WhitephoenixTheBunny** [comment]
*party dance*
