### ISSUE TITLE
[Pet] Water Elemental

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#3058]
Summoned by spell ID 31687 (Summon Water Elemental)
Waterbolt Spell ID 31707
Glyph of Eternal Water item ID 50045
Sources: https://wowwiki.fandom.com/wiki/Spell_power_coefficient
https://www.wowhead.com/forums&topic=148315

The pet has two versions based on you having the glyph of eternal water or not.
This report is dedicated to the GLYPHED, permanent pet version.
There are multiple issues with this pet, the most important are the first two in order:

1) Spell power coefficient of Waterbolt (ID 31707)
**How it should work:** According to all wotlk sources I found, the water elemental receives 33% of the mage's spell power and 5/6 of that should go into his Waterbolt (83,33% of pet SP equals 27,78% of mage SP - that's what waterbolt should get)
**How it works atm:** The spell appears to receive only ~12-13% of the mage's SP as a coefficient, which is about 40% of the pet's spell power (assuming he gets 1/3 of mage SP converted as intended). This is the cataclysm SP coefficient, not wotlk.
NOTE: oddly, the non-glyphed version of the pet receives proper coefficient. This leads to the strange situation of the temporary pet being twice as strong as the permanent...

2) No hit scaling
**How it should work:** Like other permanent pets, the water elemental should also scale with the owner's hit rating from gear. So if the mage has 17%+ spell hit from gear, the water elemental should be also hitcapped. 
**How it works atm:** The water elemental keeps missing at the same rate, even with above 17% hit on the mage. Does not appear to have any hit converted at all.

3) Base stats - TWEAKING (this may be hardest to fix and has the least effect on gameplay - but I add it for the sake of completion)
**How it should work:** As a permanent, controllable pet, the glyphed elemental should show up on a separate pet tab among your pets while it is active and you should be able to see his base stats, spell power, etc.
He should receive 30% of the mage's stamina and intellect, and 35% of the mage's armor, other stats (str, agi,spirit) are irrelevant.
**How it works atm:**
This pet does not show up on the pet tab at all, you cannot see his base stats. 
Calculating of his current health (14303 for my tester mage) and naked hp, which is 7623 with no gear on the mage, he appears to have 6680 health bonus from mage (=668 stamina converted), which is a vast 43,3% of my mage's 1542 stamina.
Intellect conversion comes out to be roughly the same 43,3% with the same calculation.
Now the odd part is, this means the pet should have at least 600 stamina and intellect, just from the mage, (base value unknown), so casting a stat buff (Blessing of Kings) should add **at least** 10% of that, which is 60+ stamina/int and 600+ health and mana.
Test result is however, BOK cast on this elemental with 14303 hp, increases health of the pet by 30. That equals 3 stamina. Which means his total stamina (at least the value BOK sees) is about 30.
This does not match.

4) SP from gear does not scale dynamically - TWEAKING
**How it should work:** As every other permanent pet, the water elemental should also keep dynamically checking the stats of the caster mage. If the mage swaps gear, the stats of the water elemental need to update accordingly without needing to be recast.
**How it works atm:** This dynamic scaling works fine for health and mana, they change as soon as the mage changes gear. Spell power, however, does not change, it keeps the value it snapshots when you summoned the elemental.
Note: Oddly, procs and buffs seem to work fine, the elemental gets the SP from those and then loses it when the duration expires. Only Spell power from your gear does not update. This means whenever you swap gear for example pvp > pve, you need to resummon the elemental to update his SP value.

**Comment by Keader** [comment]
Rly?
What i told you about pet scaling?

**Comment by Dranah** [comment]
Well the first two issues are major and aren't too complex. The hit scaling works fine on every other pet, I suppose it can be copied over. The SP coeff should be one number to modify, clearly someone mislooked and added cataclysm version.
I've put TWEAKING next to those stat scaling issues that I know would piss you off. If you can fix them easily, please do, if it's too complex, we can live without them, they aren't so important.

**Comment by Keader** [comment]
Try now.
OBS: I hate you.

**Comment by Dranah** [comment]
Whatever changes you added are affecting the temporary (non glyphed) pet now.
The coefficient of that pet increased and his hp/mana stats too...
There is no change on the permanent (glyphed) pet.

**Comment by Keader** [comment]
Test now.

**Comment by Dranah** [comment]
UPDATE:
- Sp coefficient of the glyphed water elemental's water bolt is now correct (fixed)
- Stam and int converted as intended (fixed)
- Hit rating converted as intended (fixed)
Temporary (non glyphed) elemental NPC ID 510
Permanent (glyphed) elemental NPC ID 37994
- The water ele (both temporary and perma version) lost its ability to benefit from targeted raid buffs such as blessings, arcane intellect, mark of the wild etc- this need fixing (need fix)
- Base health and mana values of the temp and perma elemental version aren't matching, they also alter on each recast by a few hundred. This is not intended but neither really game changing so as-is for now (tweaking)

**Comment by Keader** [comment]
Test now.

**Comment by Dranah** [comment]
Raid buffs can now affect the pets as intended.
HP and mana values as-is.

**Comment by Dranah** [comment]
Something has changed here. 
The fix is now live on Red and the hit chance and damage looks alright, but the health of the elemental does not behave (nor on Red, nor on PTR) as on my last test when I confirmed fixes on PTR so it has been definitely touched (i know you gonna say you didnt, perhaps something gone wrong when copying back and forth then). 
It's broken in so many ways I don't even know where to begin. Sorry, wall of text inc.

1) At level 50 ( when you acquire the talent) 
- The temporary (unglyphed) pet summons with around 4k health and mana which is way more than a level 50 pet should have (these are like base stats for lvl 70-80....).
![wowscrnshot_030319_203617](https://user-images.githubusercontent.com/31132743/53700604-56422200-3df4-11e9-8478-2a8769dae91d.jpg)
- The permanent (glyphed) pet summons with 1/1 health, no base hp no stamina conversion like WTF.
![wowscrnshot_030319_203829](https://user-images.githubusercontent.com/31132743/53700607-5fcb8a00-3df4-11e9-9d67-7005c9b2ccf5.jpg)
Note: using a stamina buff or equipping a piece of gear with stamina will make the elemental recalculate health and acquire the bonus health of +120 health from the mage (that's the 30% of the naked mage's stamina at lvl 50) which puts him to a grand total of 121 health... 
![wowscrnshot_030319_204041](https://user-images.githubusercontent.com/31132743/53700655-e5e7d080-3df4-11e9-99e6-7f0fafe8f2aa.jpg)
Note2: this recalculation is done automatically with a 3sec delay on subsequent summon casts. The elemental however doesn't get healed up, he remains on 1/121 hp and starts regen slowly.
Note 3: the mana value of the glyphed pet at lvl 50 is around the intended ~1800 (unlike the unglyphed pet who has level 70+ base stats already at lvl 50)

2) Leveling up 51-58, summoning the pet still results in 1/1 hp which only recalculates when the mage's stamina is buffed/changed. The recalculated health value slowly increases but is still laughably low, around 191, then 241 etc. These are health values for mobs/pets below lvl 10, not lvl 50+...

I've ran into some random additional glitches with the recalculation if you level up multiple times without resummoning the elemental. This can happen easily with VIP feature since players level very fast.
After leveling up, the mage gaining any extra stamina/int (from gear , buff etc) adds the bonus to the pet multiple times. 
For example if you level up 5 levels without the elemental resummoned, the conversion is added 5 times, you can see the health of the elemental jump 5 times when you equip an item (241 > 361 > 481 > 601 > 801 at level 52... 5 jumps within 2seconds when I equip a piece of gear)
Another weird glitch is the elemental losing health when you gain stamina, and gaining when you lose. This is probably the result of the extreme lag on the recalculation, the pet's health can't follow what's going on.
![wowscrnshot_030319_210858](https://user-images.githubusercontent.com/31132743/53701020-16316e00-3df9-11e9-9575-cae0aefa8f97.jpg) > 1681 hp without staff equipped
![wowscrnshot_030319_210854](https://user-images.githubusercontent.com/31132743/53701036-33fed300-3df9-11e9-9adc-1a0c38dc520f.jpg)
>961 health with staff equipped

3) At lvl 58, the elemental's health suddenly jumps to 3k. He probably receives the base hp that is missing between 50-58. 
![wowscrnshot_030319_211546](https://user-images.githubusercontent.com/31132743/53701064-8a6c1180-3df9-11e9-8337-2d66396e71f5.jpg)
The stamina scaling (30% of mage stam) is only added if you modify the mage's stam with a buff and the health recalculates.
Adding a +3 stam buff to the mage (which is +1 stam to pet) then adds the +12 stamina from the mage's base stamina to the pet too:
![wowscrnshot_030319_211704](https://user-images.githubusercontent.com/31132743/53701080-b7202900-3df9-11e9-92fe-ff6b161eb382.jpg)
Note: the pet is not healed up after receiving the bonus stamina

4) From lvl 58-80, the pet's base health/mana is scaled up properly.
- At lvl 80, the pet has the old base health/mana values (which are both higher than blizzlike but this is not a gamebreaking issue and we chose to leave it as-is)
![wowscrnshot_030319_212307](https://user-images.githubusercontent.com/31132743/53701158-8f7d9080-3dfa-11e9-8be8-c941e593b9e9.jpg)

The major change / issue here is that any extra stamina/intellect that the pet receives from the mage's gear and buffs, are added with a 2-3sec delay after the pet is summoned. The pet is not healed up, so he's low health and mana after being summoned:
![wowscrnshot_030319_212406](https://user-images.githubusercontent.com/31132743/53701170-b045e600-3dfa-11e9-96b6-8b79967077d9.jpg)

How it should work:
- The pet should have a reasonable amount of base health (~1-2k) at lvl 50 on both the temporary and permanent (glyphed) versions.
- This should then scale gradually in the level 50-58 bracket to ~3k as you level up and so does the pet (the scaling afterwards 58-80 looks ok)
- The pet must receive his 30% bonus from the mage's stamina and intellect as soon as he's summoned at all level brackets, and he must be healed to full health and mana.
- Leveling up multiple times without resummoning the pet must not result in his bonus stats being added multiple times

**Comment by Keader** [comment]
It is happening in PTR or just on Red?

**Comment by Dranah** [comment]
Both.
Also, this is a new problem, not a regression of the old issues.
I just don't know if it's somehow related to them. It would be nice if whatever happened between my fix-confirm and the release could just be reverted, but i know jan's gonna say he didn't touch it ...

**Comment by Keader** [comment]
```
The pet should have a reasonable amount of base health (~1-2k) at lvl 50 on both the temporary and permanent (glyphed) versions.
```
I send to you on discord current values in DB for this pet. (Temporary one)

```
This should then scale gradually in the level 50-58 bracket to ~3k as you level up and so does the pet (the scaling afterwards 58-80 looks ok)
```

Same as above.
But right now, permanent pet is using 28 + 30 * petlevel as base. Same of Gargoyle.

```
The pet must receive his 30% bonus from the mage's stamina and intellect as soon as he's summoned at all level brackets, and he must be healed to full health and mana.
Leveling up multiple times without resummoning the pet must not result in his bonus stats being added multiple times
```
Fixed both

**Comment by Dranah** [comment]
Those DB values are screwed up big time. Somebody switched a column here and there. Also the temporary pet currently generates random health and mana values within a range, instead of using fix ones.

UPDATE:
The pet now gets their bonus stam and int from the mage immediately and is also healed up. (fixed)
Health and mana calculation formulas still need fix. Will PM on discord.

**Comment by Dranah** [comment]
UPDATE:
New formula to calculate base health between 50-58 has been added for the permanent water elemental.
New formula does not seem to work for the temporary elemental. Temp ele needs his calculation to match that of the permanent elemental.

**Comment by Keader** [comment]
@Dranah any news with formulas?

**Comment by wow-mania** [comment]
Is this done?

**Comment by Dranah** [comment]
Nope. It will be labelled as such when we're finished.

**Comment by Keader** [comment]
Ok @Dranah, i found why it was getting random values and removed it.
So, you need addapt the formula for new results.

**Comment by Dranah** [comment]
New formulas added.
Water Elemental's health and mana corrected. Temporary (unglyphed) elemental's stats are now an exact match with those of the permanent (glyphed) elemental.
