### ISSUE TITLE
[Encounter] Thorim - Arena

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#3060]
https://www.wowhead.com/npc=32865/thorim
Initial adds: 
Jormungar http://www.wow-mania.com/armory/?npc=32882
Captain http://www.wow-mania.com/armory/?npc=32908 / http://www.wow-mania.com/armory/?npc=32907
Soldier http://www.wow-mania.com/armory/?npc=32883 / http://www.wow-mania.com/armory/?npc=32885
Acolyte http://www.wow-mania.com/armory/?npc=32886
Wave spawns:
Warbringer http://www.wow-mania.com/armory/?npc=32877
Evoker http://www.wow-mania.com/armory/?npc=32878
Champion  http://www.wow-mania.com/armory/?npc=32876
Commoner http://www.wow-mania.com/armory/?npc=32904

The arena event is part of the 1st phase of the Thorim encounter in Ulduar.
This is an old problem, but wasn't reported before.
Timers and spawn patterns are vastly different from blizz atm.

**How it should work (spawn data collected from analyzing several retail videos):**
- The encounter should only begin when every add from the initial ones are dead
- The upcoming waves follow a strict pattern that matches on every video
**10man**
- After 25sec, 45sec, 85sec, 105sec, 145sec etc (20/40sec intervals alternating) a Warbringer spawn
- After 30sec, and then every 25 seconds, an Evoker spawn
- After 35sec, and then every 30seconds, a set of commoners spawn
- After 45sec, and then every 40seconds, a Champion spawn
Time Lapse:
t=0 last add dies from initial group
t=25: 1 warbringer
t=30: 1 evoker
t=35: commoners
t=45: 1 warbringer 1 champion
t=55: 1 evoker
t=65: commoners
t=80: 1 evoker
t=85: 1 warbringer 1champion
t=95: commoners
t=105: 1 warbringer 1 evoker
t=125: commoners
t=130: 1 evoker
t=145: 1 warbringer
t=155: commoners + 1 evoker
etc.

25man
- After 20sec, and then every 15sec, a Warbringer spawns
- After 25sec, and then every 20sec, an Evoker spawns
- After 26sec, and then every 22sec, a set of Commoners spawn
- After 30sec, and then every 25sec, a Champion spawns.
Time Lapse:
t=0 last add dies from initial group
t=20: 1 warbringer
t=25: 1 evoker
t=26: commoners
t=30: 1 champion
t=35: 1 warbringer
t=45: 1 evoker
t=48: commoners
t=50: 1 warbringer
t=55: 1 champion
t=65: 1 warbringer, 1 evoker
t=70: commoners
t=80: 1 warbringer, 1 champion
t=85: 1 evoker
t=92: commoners
t=95: 1 warbringer
t=105: 1 evoker, 1 champion
etc.
As you can see, with these timers no more than 2 adds spawn collides at a time on either difficulties. There is never more than 1 of same type of add spawning at once, except the small commoners which come in group. On 25man, the adds are spawning at a slightly higher rate. The spawns are predictable and consequent with no RNG in factor.

**How it works atm:**
- Often (though not always) the encounter is engaged and the timer begins with still 1 or 2 adds alive from the initial wave. Most commonly Captured Mercenaries are still up.
- The wave spawns are extremely random and follow a largely different pattern (if it can be called pattern at all). Generally adds are spawning too fast.
Both 10man and 25man has the same spawn pattern
- Commoners spawn every 20sec, constantly. This means their 20sec duration debuff on you has no chance to reset. 
- After 30sec, and then every 20sec, either 1 single warbringer spawns, or a set of 2-4 adds consisting of evokers/champions. It is completely random.
In lucky days, it's just 1 warbringer over and over which makes you near jobless. If RNG does not favor you, you get 3-4 evokers spawn at once, oneshotting your healer with their lightning as soon as they land.
As you can see, this means sometimes the fight ends up being easier than expected, other times you are flooded with adds without a chance to survive. There is no difference between 10m and 25m difficulties in the spawn rate, which makes 10man significantly harder with bad RNG on the waves.

**Comment by Keader** [comment]
Test now.

**Comment by Dranah** [comment]
UPDATE:
- Waves spawn times and intervals corrected 
- Fixed issue with duplicate adds present which led to the encounter starting with some adds still alive
