### ISSUE TITLE
[Spell] Blizzard - Sif

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#3061]
https://www.wowhead.com/spell=62576/blizzard
used by Sif https://www.wowhead.com/npc=33196/sif during the Thorim Encounter in Ulduar

**How it should work:** 
- The area covered by the blizzard should be orbiting the **outer** circle of the room, leaving the central area safe.
- The frost damage done by this spell should be resistible. FR gear is highly suggested for lesser geared/newbie groups for this fight as it mitigates Sif's damage by loads.
Description from wiki:
"A rain of ice moves around the room, dealing 2,188 to 2,812 (25 Player: 4,813 to 6,187) Frost damage every 1 second, for 10 seconds. Targets caught in the Blizzard have their movement speed reduced by 65%"
"Much like Shade of Aran, Sif conjures a Blizzard which orbits the room, making the centre 'safe'."
Video source: https://www.youtube.com/watch?v=1EZcpwdz42E&t=136s
Pictogram: https://wowwiki.fandom.com/wiki/Thorim_(tactics)?file=Thorimposition.jpg > mentions resist gear too

**How it works atm:**
- The blizzard spawns much closer to the center and covers a much wider area than intended. Even the central ring isn't safe.
- The spell does not seem to be resistible partially or at all, with 300+ FR i didn't manage to get any sort of resisted damage off it - the other frost abilities used by Sif are properly mitigated by resistance.

I made a couple of extremely bad paint pictures for you to demontrate the positioning in case yer lazy to watch the video:
Mania
![thorim](https://user-images.githubusercontent.com/31132743/53064005-7d305800-34c6-11e9-91f4-ac8279a9637e.png)
Blizz
![wowscrnshot_022019_034732](https://user-images.githubusercontent.com/31132743/53063990-6ee23c00-34c6-11e9-921f-6d4c7ed030eb.jpg)

**Comment by Keader** [comment]
Idk until when it's true.
If you back of that room, you will see that one of "Thorim Event Bunny" is moving around in circle.
Blizzard always hit this npc. I checked in sniffs and his position and movement is correct.
Blizzard has 13 yards radius range, so is impossible just mark where you put in SS.

Other thing.
Blizzard cant be resisted because in dbc has ```SPELL_ATTR4_IGNORE_RESISTANCES``` attribute.
Sometimes they put this attribute in wrong spells, since lord marrowgar flames has it and is wrong.
You checked and it realy can resist?

**Comment by Keader** [comment]
ok, talking with sirikfoll he say that can be a old core issue
Fixed by: https://github.com/TrinityCore/TrinityCore/pull/16290
I dont think that janitor will cherry-pick it... so the best that we can do, is maybe adjust spell radius?

**Comment by Keader** [comment]
I did a little change suggested by sirikfoll.
check now.

**Comment by Dranah** [comment]
UPDATE:
- Blizzard now circles the outer ring of the room as intended
- The frost damage it deals can now be mitigated with resistance
Blizzard positioning post-fix - looks pretty af:
![wowscrnshot_022019_211747](https://user-images.githubusercontent.com/31132743/53121902-9207fc80-3555-11e9-9a56-2fbc77159efe.jpg)
