### ISSUE TITLE
[SotA] Mark of Honor

### ISSUE THREAD

**Issue by Kitzunu** [WoWManiaUK/Redemption#3063]
http://wow-mania.com/armory/?item=42425

**How it works:**
At the end of the Battle Ground you will recieve a Strand of the Ancients Mark of Honor
![image](https://user-images.githubusercontent.com/24550914/53102249-93bcca80-352b-11e9-8a5f-6250aab1f40d.png)
![image](https://user-images.githubusercontent.com/24550914/53102262-98817e80-352b-11e9-970d-5ddcf44ec33d.png)

**How it should work:**
At the end of the Battle Ground there should not be any Mark of Honors given out.

>https://wow.gamepedia.com/Strand_of_the_Ancients
>Patch 3.3.3 (2010-03-23): Battlegrounds will no longer award Marks of Honor.

**Comment by wow-mania** [comment]
We know we keep this one for the vendors. 
Same happens with other BGs. As-is.
