### ISSUE TITLE
[SotA] Massive Seaforium Charge

### ISSUE THREAD

**Issue by Kitzunu** [WoWManiaUK/Redemption#3064]
http://wow-mania.com/armory/?item=39213
http://wow-mania.com/armory/?object=190752

**How it works:**
At this moment only Horde can disarm a placed Massive Seaforium Charge when they are the defending team and Alliance cannot disarm it when they are the defending team.

Alliance:
![image](https://user-images.githubusercontent.com/24550914/53103334-b51eb600-352d-11e9-9d90-26c99cf09828.png)
Horde:
![image](https://user-images.githubusercontent.com/24550914/53103597-3b3afc80-352e-11e9-8344-c17bd1f636c6.png)

**How it should work:**
Both Alliance and Horde should be able to disarm the Massive Seaforium Charge when they are the defending team.

**Comment by Keader** [comment]
Fixed.

**Comment by Kitzunu** [comment]
Amazing
