### ISSUE TITLE
Unholy Infusion Does not Work

### ISSUE THREAD

**Issue by slaniaxx** [WoWManiaUK/Redemption#3065]
I have today did the Unholy infusion quest correctly, did not get credited.
I am on client, used the launcher, was fully updated.
I did infuse at 100%, hit the boss afterwards, did not die, and had shadow's edge equipped all time.
I have the video proof which will be added in 50 minutes once it uploads to youtube.

**Comment by wow-mania** [comment]
Works. Please stop creating new issue. Just search.

**Comment by slaniaxx** [comment]
I've been told by a GM to actually open this, sorry if I offended you... maybe inform you GM's? and I have fully video'd the entire encounter, please let me know what I did wrong, so I can do it right the next time.

**Comment by Kitzunu** [comment]
https://github.com/WoWManiaUK/Redemption/issues/3054

**Comment by Dioden101** [comment]
To me it seems like some parts of the SM questlines are semi bugged, works for some and not for others, so im guessing its one of those thats hard to do anything about... like when i did the last part on my warrior the NPCs didnt spawn you hand the items into so you get the BoE items, and i was told i just had to wait for someone else to do it. (cant see why they couldnt just exchange the 3 items for the 3 NPCs that didnt spawn) But lucky for me i had another toon that was almost done on another account so i got both done when he did it... So in short, Better luck next time, and i hope you get it 🗡
