### ISSUE TITLE
[NPC] Falling to 1hp and unkillable

### ISSUE THREAD

**Issue by wowmania-Kindly** [WoWManiaUK/Redemption#3066]
Hello again, again! :)
My guild had problems With Baltharus the Warborn http://www.wow-mania.com/armory/?npc=39751#drops-1 on both monday and wendesday of this week.
When he does his spell to split himself into 2 fragments he spawns the extra, and then both loose all their Health, goes into the Death animation, and then their corpses continue to follow and kill raidmembers.
uattackable and unkillable, allthough aoe effects hit him for 1dmg and the rest is overkill dmg.
Here are some screenshots of mondays incident, im trying to illustrate the corpse moving:
![wowscrnshot_021819_121034](https://user-images.githubusercontent.com/31795370/53127364-8a028980-3562-11e9-83c4-f406fe11cdd8.jpg)

![wowscrnshot_021819_121033](https://user-images.githubusercontent.com/31795370/53127374-91c22e00-3562-11e9-8fa3-e308cc157c6e.jpg)

![wowscrnshot_021819_121032](https://user-images.githubusercontent.com/31795370/53127426-adc5cf80-3562-11e9-9206-74004eb8ac50.jpg)

**Comment by Kitzunu** [comment]
When he splits into 2 they have the same HP, and does not drop to 1 anymore.

**Comment by Earthliving** [comment]
Bugged again. same issue. RH 25 Heroic.

**Comment by WhitephoenixTheBunny** [comment]
The issue also happen on others mobs/NPC

For example: fos HC bonecaster

**Comment by Kitzunu** [comment]
@Earthliving Do you know any way on how to reproduce this issue?

**Comment by wow-mania** [comment]
send entries of NPCs so dev can reproduce.

**Comment by Keader** [comment]
Test now.
Why nobody noticed that HP sincronization was not working? O.o

**Comment by Kitzunu** [comment]
I have tested and after split they do not drop to 1HP.

They have the equal health, alive and killable.

**Comment by WhitephoenixTheBunny** [comment]
Mobs on RHC also MAY have that.
