### ISSUE TITLE
[Battleground] Isle of Conquest - Base Flags bugged ( Both sides)

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Redemption#3067]
**_As a horde we have to penetrate Alliance keep (ally base) and contest their flag in order to gain access to the graveyard within enemy fort_** 

- Flag is not clickable 
- Cant test horde win without it :)
- Also Capping "the keep" flags give the graveyard to the enemy (important) 

![no click ally flag](https://user-images.githubusercontent.com/39439201/53129408-bd93e280-3567-11e9-9492-46c9ff0bd70b.jpg)

- Need an Ally to test the horde flag in Horde keep

**Comment by Echinaceax** [comment]
Tested myself from my Ally 

- Horde flag not clickable

![horde flag in horde keep - not clickable](https://user-images.githubusercontent.com/39439201/53138324-41f55e00-3586-11e9-83bd-c69b93f5407a.jpg)

**Comment by Echinaceax** [comment]
video - https://www.youtube.com/watch?v=na8exh8Mwmc

- player capped horde flag inside horde keep 

capping

![from video](https://user-images.githubusercontent.com/39439201/53140689-d57e5d00-358d-11e9-9510-4b8c9d089819.jpg)

capped / assaulted horde flag

![capped](https://user-images.githubusercontent.com/39439201/53140710-eaf38700-358d-11e9-8663-23be55efd1a4.jpg)

**Comment by wow-mania** [comment]
What are the objects id?

**Comment by wow-mania** [comment]
Objects are clickable as far as I can see.

**Comment by TheManiax** [comment]
@Echinaceax  Make sure to brake the fort door before trying to capture the flag
If you use GM fly to go inside the fort , the flag is not click-able as you have reported and that's as intended.

**Comment by Echinaceax** [comment]
> What are the objects id?
 i couldnt find an ID on the portals sorry. will search more now and let you know

**Comment by Echinaceax** [comment]
> What are the objects id?

https://www.wowhead.com/object=187433/horde-flag
Location - on SS 
ID - 187433

https://www.wowhead.com/object=187432/alliance-flag
Location - on SS
ID - 187432

please note 1: 
**This object can be found in _Alterac Valley_ (16), _Isle of Conquest_ (13), _Strand of the Ancients_ (3) and _Blasted Lands._**

So please only check Isle of Conquest (horde keep) and (Alliance keep) 

Also take into account the reply of TheManiax comment
but unable to complete this as gates have 600k hp :)
