### ISSUE TITLE
[Battleground] Isle of Conquest - glaive-thrower [Spell] -67195 - 

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Redemption#3068]
npc - https://www.wowhead.com/npc=35273/glaive-thrower

- blade-salvo does no dmg
https://www.wowhead.com/spell=67195/blade-salvo

**Comment by Keader** [comment]
Effect is not implemented in core.
Cant be fixed.

**Comment by Rushor** [comment]
@Keader what about https://github.com/Inquisitor/mangos/commit/e06c62518e684069e0f3507f5a9ecd9e8e5cf280 maybe

**Comment by Keader** [comment]
More like: https://github.com/TrinityCore/TrinityCore/issues/23204

**Comment by Rushor** [comment]
ohh good catch, i'm outdated haha

**Comment by Keader** [comment]
Handler is implemented.
Spell fixed.
Remember: it dont do damage to objects (gates) only to players/npcs
