### ISSUE TITLE
[IoC] Hanger portal (Ally)

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Redemption#3069]
- When Ally cap the Hanger Flag and use the portal it ports you too "gunship" under the stairs 

![this portal bugs](https://user-images.githubusercontent.com/39439201/53134815-f5575600-3578-11e9-9b1f-9dc8c3bc7a33.jpg)

![port 2 under gunship](https://user-images.githubusercontent.com/39439201/53135227-bd511280-357a-11e9-988d-59510655deeb.jpg)

Couldnt glitch up to get out, had too use the "unstuck feature" and be ported to Draenei start zone

**Comment by Echinaceax** [comment]
Ally portal was at the other side of the hanger (im horde player so didnt know that) :)

**Comment by Echinaceax** [comment]
**_For Horde_** 

- 2 portals worked correctly
- 1 didnt 

![not working](https://user-images.githubusercontent.com/39439201/53136376-1327b980-357f-11e9-966a-9c019d7680b6.jpg)

more tests needed.
Horde doesnt get ported under the stairs , so the portals are still a problem for Ally

**Comment by wow-mania** [comment]
Please retest on dev

**Comment by Echinaceax** [comment]
oki, will when we get online :)
we are going too, just waiting server to come online

**Comment by Echinaceax** [comment]
Update:
Changes have made the server crash ...apparently

**Comment by Echinaceax** [comment]
@wow-mania 

its the ally side portal on the airship needs fix it seems :)

**Horde (perfect location)**

![horde perfect](https://user-images.githubusercontent.com/39439201/53202404-ad8f0800-3626-11e9-8c2a-31148057ccc9.jpg)

**Ally port not in right location on the airship , so it ports under stairs**

![ally airship](https://user-images.githubusercontent.com/39439201/53202472-d6170200-3626-11e9-8caa-f829085ff07f.jpg)

**Comment by Kitzunu** [comment]
The issue still persists, could this be because it is a moving object that you are being teleported onto?
![image](https://user-images.githubusercontent.com/24550914/53247588-0658b200-36b4-11e9-9eff-6d24e984c274.png)

¨But it is like Echi said, sometimes it teleports you ontop of the Gunship, and sometimes it teleports you inside of the gunship

**Comment by wow-mania** [comment]
Could be.

**Comment by Echinaceax** [comment]
But horde gunship is moving and is fine

**Comment by Echinaceax** [comment]
**Update**
- Tested all 3 portals (Ally) all working :)

both ships are hanger before cap - good :)
![both ships of hanger before cap](https://user-images.githubusercontent.com/39439201/53265458-99a6dd00-36de-11e9-894d-41927805bba9.jpg)

portal -test 1 - working 
![test1](https://user-images.githubusercontent.com/39439201/53265516-bcd18c80-36de-11e9-84ef-40b5d6af03ff.jpg)

portal 2 - working 

![test 2](https://user-images.githubusercontent.com/39439201/53265542-cce96c00-36de-11e9-9797-f1f8e1933464.jpg)

Portal 3 - working (though i did fall off the ship as i ported just once) 
- bad timing of porting i believe 

![test 3](https://user-images.githubusercontent.com/39439201/53265618-faceb080-36de-11e9-8d3a-6a6aef721142.jpg)

All working on ally cap

**Comment by Kitzunu** [comment]
Okay, it is not fixed and I have a theory.
I believe this goes hand in hand with https://github.com/WoWManiaUK/Redemption/issues/3074

I believe that you fall through the texture and get bugged out when the gunship is too far from the player so it is not loaded in, then it does not load in fast enough making the player fall through the texture.

**Comment by Echinaceax** [comment]
Horde side 
- falls through graphics now too

![horde](https://user-images.githubusercontent.com/39439201/53269406-12ab3200-36e9-11e9-8a4c-f844a7dce69b.jpg)

**Comment by wow-mania** [comment]
I will try to raise them a bit

**Comment by Kitzunu** [comment]
This still happens for both factions

**Comment by Keader** [comment]
K, now you will not fall of the boat... but will  still will not stop in correct place...
So i think that is better, but not totally fixed.
I have no idea right now how fix it :/

**Comment by Kitzunu** [comment]
@Keader You can still fall through the airship as alliance and horde
