### ISSUE TITLE
[Spell] Shadow Veil

### ISSUE THREAD

**Issue by Ashamedlol** [WoWManiaUK/Redemption#3071]
When casted while on a Catapult, the player shouldn't gain the same buff.

Currently: Allowing him to be a stealth class as long as no one's near him within 800 yards.

Catapult L70 ID: http://www.wow-mania.com/armory/?npc=34793
Catapult L80 ID: http://www.wow-mania.com/armory/?npc=35413
Spell ID: http://www.wow-mania.com/armory/?spell=66296

**Comment by wow-mania** [comment]
I don't understand what you meant here.
What is happening? When? and how it was supposed to be?

**Comment by wow-mania** [comment]
Just tested and player does not get the buff only the vehicle.

![image](https://user-images.githubusercontent.com/12248683/53174018-b5c45480-35e0-11e9-9dcb-b0e54e6d2af1.png)

**Comment by Ashamedlol** [comment]
Wierd, it applied to me inside the battleground and I managed to become a stealth Paladin, could you try it inside the battleground by any chance?

What I did: Got on a catapult, used the spell, left the catapult, I had the buff on me while not on the catapult and got away, my second toon couldn't spot first one in specific range.

**Comment by Echinaceax** [comment]
i got the same 
https://www.wowhead.com/spell=66296/shadow-veil

- Casts both on catapult and the player 
- I didn't get stealth tho ..but i walked like a stealthy does

**Comment by Kitzunu** [comment]
Not fixed
![image](https://user-images.githubusercontent.com/24550914/53285657-65293480-3763-11e9-8e93-c235f0254c46.png)

**Comment by wow-mania** [comment]
Another try. :)

**Comment by Kitzunu** [comment]
No change

**Comment by Keader** [comment]
Fixed, test now @Kitzunu

**Comment by Kitzunu** [comment]
You loose the buff once you leave the vehicle now

**Comment by Echinaceax** [comment]
nice :)
