### ISSUE TITLE
[Spell] Mountain Horse

### ISSUE THREAD

**Issue by Kitzunu** [WoWManiaUK/Redemption#3073]
http://wow-mania.com/armory/?item=73838
http://wow-mania.com/armory/?spell=103195

**How it works:**
This mount currently has a 100% speed

**How it should work:**
This mount should have a 60% speed

This is the mount Worgens get at level 10, which gives them an unfair advantage since all other races get a 60% mount at level 10.

**Comment by wow-mania** [comment]
This will probably need a client update to fix.

**Comment by Keader** [comment]
@wow-mania cant be fixed using SpellMgr like wotlk mounts?

**Comment by Kitzunu** [comment]
I got sent a patch and tested it.

The tooltip of the mount now says 60% however the mount still runs at 100%
I compared it to the human horse which runs at 60%.

**Comment by wow-mania** [comment]
I tested locally and it is fixed. Will require client update.

**Comment by WhitephoenixTheBunny** [comment]
I have retested this issue, due at some comment on World Chat.
I have created a Worgen on PTR and the mount is 100%

![image](https://user-images.githubusercontent.com/31921098/57580910-a0581b80-74a7-11e9-8a55-ea9eb2937f83.png)

**Comment by wow-mania** [comment]
![image](https://user-images.githubusercontent.com/12248683/57581385-b4534b80-74ae-11e9-8c86-2fbf29fcb63d.png)
Fixed again. Maybe a regression.
Will need client update so I will close it now.
