### ISSUE TITLE
[SotA] Attacking Boats

### ISSUE THREAD

**Issue by Kitzunu** [WoWManiaUK/Redemption#3074]
This will be a tricky one to describe.

**How it works:**
Basically, when you accept the BG game to SotA and you are on the Attacking team you will spawn on the boats, however when you get in the texture of the boat is not loaded in causing players to fall through the texture into the water or the lower deck of the boat.
(This happens some times, not 100% of the times)

**How it should work:**
The Boat should be loaded in before you get into the battleground so that you do not fall through the boat and get stuck

This is when I got glitched through the boat to the lower deck when you are supposed to be ontop of the deck
![image](https://user-images.githubusercontent.com/24550914/53266093-16868680-36e0-11e9-884b-01db4a7297bd.png)

**Comment by Keader** [comment]
Weird, i did it this week and works fine to me.

**Comment by Kitzunu** [comment]
As I mentioned, it happens some of the times, not all the time.

But when it happens, it causes the player to fall through the first deck, or even down into the water.

**Comment by wow-mania** [comment]
No change on this anywhere so pretty sure it may be lag or something similar.
Try this on Redemption.

**Comment by Kitzunu** [comment]
Made the report after it happened on Red

**Comment by wow-mania** [comment]
All these should be a single issue - "Teleporting - IoC"

**Comment by Kitzunu** [comment]
This seems to be okay for Alliance now
Horde still needs their spawn to be adjusted

**Comment by Kitzunu** [comment]
I tried to find NPC's for the spawns on the boats for both Alliance and Horde, but there were none. 
Had GM on.

Is it possible that it is a spawn on coordinates and not on an NPC?
