### ISSUE TITLE
[SotA] Massive Seaforium Charge Damage

### ISSUE THREAD

**Issue by Kitzunu** [WoWManiaUK/Redemption#3075]
http://wow-mania.com/armory/?item=39213
http://wow-mania.com/armory/?object=190752

**How it works:**
The Seaforium Charge deals 1250 hit damage

**How it should work:**
It should deal equal to 25% of the Wall's "HP" (damage hit since it is an object)

Wall "HP" = 9000
9000/4 = 2250

The damage on the Seaforium Charge should be increased to 2250

>https://wowwiki.fandom.com/wiki/Strand_of_the_Ancients
>When laid, they explode after ten seconds, doing about 25% of the walls' HP.

**Comment by Keader** [comment]
Wiki is wrong.
I did it on blizzard, and i need alot of bombs to break wall.

**Comment by Kitzunu** [comment]
I found nothing about this matter on wowhead, so I checked two wikis, one said 25% of the wall, and another one said 4000 damage. Which made me to believe this was the most accurate.

But if what you are saying is true, then 1250 (8 bombs) is most likely correct
