### ISSUE TITLE
[IoC] Huge Seaforium bombs Damage 

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Redemption#3076]
https://www.wowhead.com/item=47030/huge-seaforium-bombs

**_Horde test in Alliance keep_**

-  Huge Seaforium bombs are doing the almost the same dmg whether the team has Quarry and Oil Refinery or not

commented from Wowhead
https://www.wowhead.com/item=47030/huge-seaforium-bombs#comments

> These suckers do ~6.5k damage to an enemy gate.
> These bombs ARE affected by Quarry and Oil Refinery. This means that when your team controls both bases, bombs will do ~10k to a gate.

**_Damage without capping Quarry and Oil Refinery_**

![10k huge](https://user-images.githubusercontent.com/39439201/53271329-653b1d00-36ee-11e9-9ffa-a4923af5e5e0.jpg)

**_Dmg with capping both Quarry and Oil Refinery_**

![9 8](https://user-images.githubusercontent.com/39439201/53273782-33798480-36f5-11e9-83bd-706024091144.jpg)

![9 5](https://user-images.githubusercontent.com/39439201/53273814-56a43400-36f5-11e9-916d-470afcdc8bf0.jpg)

As quoted from wowhead, Huge Seaforium bombs are meant to have half the dmg if you havent capped them 2 bases 

(6.5k) if team hasnt capped Quarry and Oil Refinery
(10k) When they have capped

**Comment by Echinaceax** [comment]
Going to test ally side now ...

**Comment by wow-mania** [comment]
Please re-test on dev.

**Comment by Echinaceax** [comment]
ok...omw

**Comment by Kitzunu** [comment]
No change

| Buff #        | Damage           | Extra info  |
| ------------- |:-------------:| -----:|
| 0     | 10241  |  |
| 1      | 9684       |  No increase of Damage. 15% increase should have been roughly 11777 |
| 2 | 9814      |    No increase of Damage. 30% increase should have been rougly 13313 |

**Comment by wow-mania** [comment]
What are the buffs id?

**Comment by Kitzunu** [comment]
@wow-mania 
Buff IDs: 
Quarry `68720`
Refinery `68719`

**Comment by wow-mania** [comment]
Should be OK now please retest on dev

**Comment by Kitzunu** [comment]
Fixed

| Buff #        | Damage           | Extra info  |
| ------------- |:-------------:| -----:|
| 0     | 10265  |  |
| 1      | 11440       |  Roughly a 15% damage increase |
| 2 | 12970      |  Roughly a 30% damage increase |

**Comment by Echinaceax** [comment]
Thank you guys :)
sorry i forget to link the buffs :)
