### ISSUE TITLE
[Quest] Gizelton Caravan

### ISSUE THREAD

**Issue by jarvik76** [WoWManiaUK/Redemption#3078]
Quest 5943 Gizelton Caravan
am at Desolace 66.9,57.8.  Rigger Gizelton (NPC 11626) has shouted for assistance, I have accepted the quest and it is in my log
However the caravan does not start to move, even after 10 mins of waiting
Have screenshot inc timestamp log
Launcher, 2.5.2
![wowscrnshot_022319_113716](https://user-images.githubusercontent.com/46089380/53285962-8c7e0280-375f-11e9-9866-7101a6fc62be.jpg)

**Comment by wow-mania** [comment]
Quest works.
You need to find Cork
![image](https://user-images.githubusercontent.com/12248683/53286597-eafbae80-3768-11e9-975d-53ed8a9592c7.png)
There is indeed some issue there where the Kodos get separated from Cork but does not stop you from completing the quest.
I will look into it.

**Comment by jarvik76** [comment]
Argh.  Sorry. I put the wrong quest in the title, but the correct one in the body.   It's Gizelton Caravan I had an issue with, quest 5943.  Screenshots are for Gizelton caravan problem

**Comment by jarvik76** [comment]
I have a feeling the issue that you identified of the Kodos getting separated from Cork perhaps might be the problem with this "Gizelton Caravan" quest - that the caravan is supposed to start moving but does not, and only Cork moves.  Leaving the Kodos behind and the "Gizelton Caravan" quest non-completable.
Maybe.
A thought, anyway.  Thanks!

**Comment by Kitzunu** [comment]
Quest is fixed.
Remember that you do not hand in the quest to the Quest Giver.
Check armory for which NPC you should hand in the NPC to
