### ISSUE TITLE
[Quest] Envoy to the Mag'har

### ISSUE THREAD

**Issue by Annieagain** [WoWManiaUK/Redemption#3079]
i am able to get the quest, but when i return to BLoddfist i am unable to turn in the quest

**Comment by Kitzunu** [comment]
I can confirm that when you have the quest, and you go to Gorkan Bloodfist he does not let you interract with him, making it impossible to complete the quest

![image](https://user-images.githubusercontent.com/24550914/53287785-8e58bd80-3781-11e9-905c-7ab2683293ff.png)

**Comment by wow-mania** [comment]
As-is. You need to raise your rep with The Mag'har
http://wow-mania.com/armory/?faction=941
I will add that to armory but nothing to do to quest or NPC.
