### ISSUE TITLE
[IoC] Demolisher Damage

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Redemption#3080]
https://www.wowhead.com/npc=34775/demolisher

- Demo damage is also same with and without the oil refinery buff 

**without capping** 

![without oil demo](https://user-images.githubusercontent.com/39439201/53287830-f8716280-3781-11e9-91df-3bf1f4ebf443.jpg)

**with capped**

![with oil buff 1509](https://user-images.githubusercontent.com/39439201/53287866-50a86480-3782-11e9-83cf-c7a5e611be26.jpg)

**or** 

![quarry buff](https://user-images.githubusercontent.com/39439201/53287987-71bd8500-3783-11e9-8d15-1398f95c08ac.jpg)

** or both**

![2 buffs](https://user-images.githubusercontent.com/39439201/53288034-1f309880-3784-11e9-9c85-0fb671708e0b.jpg)

![with oil 1509](https://user-images.githubusercontent.com/39439201/53287842-07581500-3782-11e9-8fcc-4a186977ed2a.jpg)

im not sure if my theory is connect but this and the sea forium bombs have the same issue #3076
They both require having the oil refinery / quarry for dmg buff increase 

one or both buffs still should alter the demo dmg but they dont.

1 buff (15%)
2 buffs (30%)

**Comment by wow-mania** [comment]
Where is this? Dev?

**Comment by Echinaceax** [comment]
:P

**Comment by Kitzunu** [comment]
Works properly.

| Buff #        | Damage           | Extra info  |
| ------------- |:-------------:| -----:|
| 0     | 1484 |  |
| 1      | 1692      |  Roughly 15% Damage increase |
| 2 | 1978      |    Roughly 30% Damage increase |
