### ISSUE TITLE
[Spell] Violet Spellwing

### ISSUE THREAD

**Issue by Kitzunu** [WoWManiaUK/Redemption#3081]
http://wow-mania.com/armory/?spell=150181

Tooltip should say `280%` and not `100%` because it is a 280% flying mount.

![image](https://user-images.githubusercontent.com/24550914/53291736-5caf1900-37b8-11e9-8ad8-5fe1860246fa.png)

**Comment by wow-mania** [comment]
Will check but will not consider this as an issue. More like a visual glitch.
