### ISSUE TITLE
[Spell] Divine Sacrifice - 64205

### ISSUE THREAD

**Issue by bluemonstrr** [WoWManiaUK/Redemption#3082]
Both Divine Sacrifice and Hand of Sacrifice are transferring far more damage than they should.
Divine Sacrifice Spell ID - 64205
Hand of Sacrifice Spell ID -6940

![sac](https://user-images.githubusercontent.com/33989250/53296319-fcbd7000-37c1-11e9-9f3e-2d515b588d4e.png)
![hsac](https://user-images.githubusercontent.com/33989250/53296327-1f4f8900-37c2-11e9-8011-db299eeb6b5d.png)

Upon taking any damage at all my paladin was always brought to exactly 30% hp

When used at 30%, each time it would drop me to 10%

Once below 10% and further, the % of damage dealt appears to drop off.

**Comment by Keader** [comment]
Test now.

**Comment by Dranah** [comment]
Looks good now. Sharp 30% of melee and spell attacks too.
