### ISSUE TITLE
[Loot] Halion 25hc

### ISSUE THREAD

**Issue by Yhato794** [WoWManiaUK/Redemption#3083]
Hi, my guild is on Halion 25hc farming we are able to do 2 runs per week and we noticed a wrong amount of trinkets drops. By far we got:
-5 Sharpened twilight scale
-7/8 Petrified 
-8/9 Glowing 
-20-24 Charred
Base of wow mania armory loot table, each trinket should have 25% drop rate and this is not true simply because we got over 20 Charred scale and less the 10 of the others. Could you take a look into that. Thanks in advance 
Link to the armory: http://www.wow-mania.com/armory/?npc=39863#drops-3

**Comment by wow-mania** [comment]
Do you understand what probability is?

**Comment by Dranah** [comment]
No need to be so harsh, if players feel something is off, it is better looked at.
I've made a quick test and it's just RNG @Yhato794 . Your casters may have secretly sacrificed a virgin or two to the gods for getting so lucky.
Wowhead drop chances for 25hc are
27% Glowing
22% petrified
21% Sharpened
19% charred

test on PTR:
18 Glowing
24 sharpened
30 petrified
17 charred
There is nothing wrong with the drop rates.

**Comment by wow-mania** [comment]
Nicely done Drannah.

**Comment by Yhato794** [comment]
All right thanks Dranah :D
