### ISSUE TITLE
[Item/Loot] Warr tier on Malygos

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#3085]
https://www.wowhead.com/npc=28859/malygos
http://www.wow-mania.com/armory/?item=40547

Malygos regularly drops warrior tier leggings on 25man mode.
This item is not supposed to be on his loot table at all.

Note: the display on mania armory is wrong too, here it shows it is contained in malygos' chest http://www.wow-mania.com/armory/?item=40547#contained-in-object which is unintended.

**Comment by wow-mania** [comment]
can you send me a screenshot and also the actual npc id.
I cannot see how that would be possible.

**Comment by Dranah** [comment]
![wowscrnshot_022519_014612](https://user-images.githubusercontent.com/31132743/53329052-97fe3480-38eb-11e9-926b-18b3669e9dcd.jpg)

NPC ID for Malygos is 28859 but the item drops are contained in a chest called "Alexstrasza's gift"
There are two of these objects on armory, http://www.wow-mania.com/armory/?object=193905 and http://www.wow-mania.com/armory/?object=193967 not sure which is the one in game

**Comment by wow-mania** [comment]
Applied to Redemption.
