### ISSUE TITLE
[Quest] Verog the Dervish

### ISSUE THREAD

**Issue by fas7blas7** [WoWManiaUK/Redemption#3089]
The quest requires the player to kill Kolkar centaurs near a specified tent around the Stagnant Oasis in the Barrens (Kalimdor, Horde), until they "sound an alarm" which will cause the named mob "Verog the Dervish" spawn. Ive killed Kolkars for 30-40 minutes and I think this quest might be broken.

**Comment by Kitzunu** [comment]
![image](https://user-images.githubusercontent.com/24550914/53507146-9da87580-3ab7-11e9-876a-cc8156c491c6.png)

**Comment by Kitzunu** [comment]
Make sure you check for Verog at the correct Location

**Comment by fas7blas7** [comment]
Thank you.
