### ISSUE TITLE
Pets and Halion

### ISSUE THREAD

**Issue by crulinjr** [WoWManiaUK/Redemption#3090]
So everytime i get into RS as a Hunter my pet always dies in the 2nd phase. I think is probably due the cleaving or the aoe from the breath but something is not working correctly.

**Comment by Dranah** [comment]
This is not a proper report. It lacks all essential information.
You can check the deaths/damage taken log on recount, uncheck "merge pets with owner" and you'll see what killed your pet.
If it is something that is not supposed to hit the pet (or not for that much), add it to the thread and it'll be looked at.
Until then, we won't be looking for a needle in a haystack.
