### ISSUE TITLE
[PvP] flagged pvp 

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Redemption#3091]
I decided to open this report after seeing Changelog in discord
  
![changes](https://user-images.githubusercontent.com/39439201/53576460-f6d5df00-3b73-11e9-9894-5ddf9cface07.jpg)

- Ive always seen PvP Flagging while on FP Taxi over **WG** too **Sholazar Basin** from Dala FP
(Ive always logged out/in while on Flight, which clears the flag in mid Flight) 
- Tested on 3 chars

**FP Dala** 

![fp dala](https://user-images.githubusercontent.com/39439201/53576708-9bf0b780-3b74-11e9-91ce-c8da37d26a02.jpg)
![left dala](https://user-images.githubusercontent.com/39439201/53576693-91362280-3b74-11e9-872f-3e695356ce13.jpg)

**Flagged WG**

![flagged over wg](https://user-images.githubusercontent.com/39439201/53576817-ce9ab000-3b74-11e9-9172-23a86821d456.jpg)

- Still flagged on landing in Sholazar Basin
- 9mins to WG timer (didnt accept) and still Flagged on Taxi FP 

![not accept wg](https://user-images.githubusercontent.com/39439201/53583648-4ae7c000-3b82-11e9-9df7-09535856e4b5.jpg)
![flagged still](https://user-images.githubusercontent.com/39439201/53583654-4de2b080-3b82-11e9-8bdf-66062d2e6fd9.jpg)

- Test also with and without ICC FP
- Still get flagged when Taxi FP enters WG and still flagged when landing in Sholazar Basin

![icc fp](https://user-images.githubusercontent.com/39439201/53584944-19242880-3b85-11e9-9bce-608c9bae1835.jpg)

**Comment by Echinaceax** [comment]
**On the flight back (same route)**

**from Sholazar Basin too Dala**

![from sb](https://user-images.githubusercontent.com/39439201/53585745-eed36a80-3b86-11e9-9d44-d41987e8dab9.jpg)

- OFC not attack-able in dala but still have flagged

![flagged back](https://user-images.githubusercontent.com/39439201/53585844-2e01bb80-3b87-11e9-9936-9eeed9704def.jpg)

**Comment by Keader** [comment]
I wonder if someone removed the fix...
I will check.

**Comment by Echinaceax** [comment]
> I wonder if someone removed the fix...
> I will check.

No idea :)
Thanks

**Comment by Keader** [comment]
Try now dear.

**Comment by Echinaceax** [comment]
Sorry nope :) 
- Still flagged (in dev)

![nope](https://user-images.githubusercontent.com/39439201/53593214-678ef280-3b98-11e9-98b5-713121c3c89f.jpg)

**Comment by Keader** [comment]
Not just visual?
Let me see if it generate any build error

**Comment by Echinaceax** [comment]
Test was on horde toon 
Shall i test on my Ally too ?

**Comment by Keader** [comment]
after my mess, now is fixed.

**Comment by Kitzunu** [comment]
works

**Comment by Keader** [comment]
I put a extra check to not allow change pvp states inside dungeon too.
Cause if you heal any npc that is pvp (like ulduar ones) you will get pvp state too.
So it will prevent that a old bug back too.
