### ISSUE TITLE
[Talent] Bloodworms - ID 49543

### ISSUE THREAD

**Issue by bluemonstrr** [WoWManiaUK/Redemption#3092]
![image](https://user-images.githubusercontent.com/33989250/53611484-a36b8d00-3b83-11e9-9c44-108525cd9787.png)

How it should work; at 3/3 melee attacks have a 9% chance to spawn Bloodworms.( NPC - ID 28017) 

"Bloodworms attack your enemies, healing you as they damage for 20 seconds or until killed." 

But Bloodworms won't engage in pvp combat. When you damage an enemy, when an enemy damages you, or when an enemy damages the Bloodworms, they will not attack.

When taunted, the Bloodworm will attack the caster of taunt once then return to the Death Knight.

**Comment by Keader** [comment]
Test now.

**Comment by bluemonstrr** [comment]
Working as intended now.

**Comment by Kitzunu** [comment]
Tested by Baguette
