### ISSUE TITLE
[Spell] Drain Soul (interaction with Dummies)

### ISSUE THREAD

**Issue by WhitephoenixTheBunny** [WoWManiaUK/Redemption#3093]
Not sure if is actually an issue, I haven't find any info about it.

Atm, as warlock level 80, while using [Drain Soul](http://www.wow-mania.com/armory/?spell=47855) on an Heroic or GrandMaster Dummy the warlock will create [Soul Shard](http://www.wow-mania.com/armory/?item=6265).

This is a Screenshot from Redemption, alliance character, training in Stormwind
![1](https://user-images.githubusercontent.com/31921098/53637639-9a2dff00-3c1b-11e9-84f8-5604d1e3f74b.jpg)

This one is from Frostmourne, training at the mall, but also testes in Orgrimmar, same resultat
![2](https://user-images.githubusercontent.com/31921098/53637693-c2b5f900-3c1b-11e9-85eb-aa4b84d2afa9.jpg)

**Comment by Keader** [comment]
But what should happens here?
Level 80 dummy should give no shard? Any dummy need have charge?

**Comment by Keader** [comment]
@Dranah Can you confirm if dummies should not give any shard?

**Comment by Kitzunu** [comment]
>https://wowwiki.fandom.com/wiki/Drain_Soul
Patch 3.1.0 (14-Apr-2009): Each time Drain Soul deals damage to a target which can **grant experience**, it now has a chance to generate a Soul Shard.

Afaik dummies do not grant XP, therefore not generate a Soul Shard either.

**Comment by Keader** [comment]
Perfect. i will fix.

**Comment by Dranah** [comment]
Err, i don't want to ruin the party but training dummies SHOULD grant soul shards on patch 3.3.5
They are boss level targets, which in theory does grant experience. It's a different story that they aren't killable, but if you could kill them, they would give xp.
Here's a discussion from 3.3.0 https://www.wowhead.com/forums&topic=139788
By twitch77 on 2010/01/13 at 6:54 AM (Patch 3.3.0)
"you can also goto a lvl 80 target dummy and collect shards. that's what i always do in sw before raids/lfd."
And another on the wowhead page of training dummy: https://www.wowhead.com/npc=31146/raiders-training-dummy
"locks can farm shard off the lvl83 dummy. I have the minor glyph. and I usually get 2 shards per drain."
"As of patch 4.0 the dummies no longer give soul shards.
So, it has been changed on cataclysm.
Please revert this "fix"

Go kill for your souls like a real warlock, you pansy."

**Comment by Dranah** [comment]
PS: i've tested the low level (60,70) dummies on Redemption and they aren't granting soul shards to a level 80 warlock. So the eligibility check is working as intended.

**Comment by Dranah** [comment]
Confirmed reverted.
