### ISSUE TITLE
NPC Murkdeep despawning

### ISSUE THREAD

**Issue by VoidShifter** [WoWManiaUK/Redemption#3094]
https://www.wowhead.com/npc=10323/murkdeep 

The NPC despawns at midfight, at around %40 HP.

**Comment by WhitephoenixTheBunny** [comment]
![image](https://user-images.githubusercontent.com/31921098/53645998-0f0c3380-3c32-11e9-8df3-01a4cf2ccfd6.png)
Can you tell the steps to reproduce?

**Comment by WhitephoenixTheBunny** [comment]
If you take very long to kill it, it will despawn. standing there being hitted by him for 1 min make him despawn after a while. But that is as-is, since is a mob that appear after clearing the camp

**Comment by VoidShifter** [comment]
Being a lvl 19 priest seems hard to kill it under a minute while coping with other 2+ mobs backslashing your castbar + healing yourself...but whatever :D

**Comment by WhitephoenixTheBunny** [comment]
I have tested as lvl 20 paladin. Some classes are harder, but nothing than asking help on world chat can solve :P
I personaly help some ppl on that quest when they ask on world chat :)

**Comment by VoidShifter** [comment]
Ahhhhh, yes, right... Must have read over the -inexistent- suggested players{} line in the quest description ;)
