### ISSUE TITLE
Reminder! [Texture] The Lich King Encounter - Frostmourne room #2364 

### ISSUE THREAD

**Issue by wowmania-Kindly** [WoWManiaUK/Redemption#3095]
Hey!
I was gonna post this, but there was allready an old post... i hope you dont mind me posting it anyway as a reminder, i see that post has not been looked at for allmost a year? 
https://github.com/WoWManiaUK/Redemption/issues/2364
I hope you can solve it.

**Comment by Keader** [comment]
Cant be fixed.
