### ISSUE TITLE
[Boss] Freya - new issue(s)

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#3096]
https://www.wowhead.com/npc=32906/freya

New issue, probably broke recently (have only seen it for a week or two)

1) Freya continues to keep spawning adds every 1minute past the 6th (last) wave.

**How it should work:**
- Freya should always spawn a total of 6 add waves with 60sec intervals
- She must then stop spawning new ones, whether you killed the previous or not. 
- Normally you kill all adds and when the last wave is defeated she begins p2, but if the group is going for the achievement "Getting back to Nature" they must keep a wave of adds alive and fight through her healing stacks instead. As there are no waves beyond the 6th, their time is only limited by Freya's enrage.

**How it works atm:**
- Freya only stops spawning adds if you begin phase 2, meaning when all the previous 6 waves are dead. 
- The major difference here is that you are forced to kill the 6th wave within 1minute, otherwise she spawns a 7th which is likely a wipe on hardmode, because it leads to phase2 having adds up. This is never supposed to happen. 
- This also makes "Getting back to Nature" near impossible as the achievement requires you to leave at least 1 wave alive to make sure Freya doesn't lose all her stacks, and then the add waves will keep spawning throughout the whole fight. You'll be inevitably wiped by the continuing spawns that you cannot kill, because that would ruin the achievement criteria.

2) Something is disabling the aura of mushrooms
This has been once reported and fixed,  https://github.com/WoWManiaUK/Redemption/issues/2816 so this part is likely a regression but it isn't exactly the same bug as the previous.
I've seen this happening also in the past two weeks, not before.
The mushroom loses its aura (links in the referred issue) and the raid gets pacified by the Conservator even without an Eonar's gift nearby. I've yet to figure what exactly causes it.
EDIT: it's most likely multiple sources, as sometimes the mushroom stops working right after I drop totems, other times when I pop raid cooldowns,
It also seems to disable on specifically ret paladins (often they alone are pacified while under the mushroom that the whole raid uses and everyone else is protected), which leads me to believe some of their personal cds/procs may also affect it.

**How it works atm:** certain player auras/spells disable the aura of Healthy Spores
**How it should work**: none of player auras/spells should ever disable or overwrite this aura, it should always be active as long as the mushroom is up

**Comment by Dranah** [comment]
UPDATE:
- Freya now spawns a total of 6 add waves as intended
- Improvement on mushrooms not going evade (need to be pushed to Red for testing, issue cannot be reproduced on PTR - as we don't exactly know what causes them to lose the aura)
- Remaining issue seems to be that the protective aura of Eonar's gift (spell ID 62619) does not seem to ward off the Conservator's grip. Here's a SS of both effects active on me while standing under the Eonar, and yet i am silenced. This is never supposed to happen.
![wowscrnshot_030219_134501](https://user-images.githubusercontent.com/31132743/53684363-87472780-3d0c-11e9-81f1-c9aac4eb646e.jpg)

**Comment by Keader** [comment]
@Dranah Cant reproduce issue posted by SS.
Working fine to me.

**Comment by Dranah** [comment]
After last fix, aura from Eonar's gift now properly dispels conservator's grip.
The other shroom malfunction needs testing on red.
