### ISSUE TITLE
Mailbox: "sale pending" mail lingers

### ISSUE THREAD

**Issue by wowmania-Kindly** [WoWManiaUK/Redemption#3097]
Hey again!
When i sell Things on the auction house i get a sale pending mail in the mailbox.
This mail does not dissapear when i recieve the mail that contains the gold for the sale.
On Retail that "Sale Pending" mail would dissapear, saving you having to manually delete that mail.
It both fills the mailbox and becomes alot of clicking when youre selling many items over time.

**Comment by Dranah** [comment]
Those mails do disappear after some time.
Not sure if they are meant to disappear faster.

**Comment by wow-mania** [comment]
Get an addon to do it for you.

**Comment by Kitzunu** [comment]
The mail disapears after 30 minutes
![image](https://user-images.githubusercontent.com/24550914/53687601-d30ec680-3d36-11e9-8c5d-b7ef9931435f.png)
