### ISSUE TITLE
[Quest] Protect Kanati Greycloud

### ISSUE THREAD

**Issue by Kitzunu** [WoWManiaUK/Redemption#3099]
http://wow-mania.com/armory/?quest=4966
http://wow-mania.com/armory/?npc=10638

**How it works:**
You pick up the quest, you defend him from the 3 centaurs and then he runs back and the quest does not complete.

**How it should work:**
After defeating the 3 centaurs Kanati Greycloud should run back and the quest should be marked complete.

**Comment by wow-mania** [comment]
This was turned to SAI recently. I will revert it.

**Comment by Kitzunu** [comment]
The revert also reverted back a previous bug #1046

Kanati walks out to the Centaurs, and then walks directly back without fighting the Cenataurs and the quest gets completed.

**How it works:**
He walks to the centaurs, stands still for 2 seconds and walks back without fighting the centaurs. Quest gets completed.

**How it should work:**
Kanati should go to the centaurs and after defeating the 3 centaurs Kanati Greycloud should run back to the camp and the quest should be marked complete.
