### ISSUE TITLE
[Quest][Reputation] A Change of Heart - Ashen Verdict

### ISSUE THREAD

**Issue by Kitzunu** [WoWManiaUK/Redemption#3101]
http://wow-mania.com/armory/?quest=24822
http://wow-mania.com/armory/?quest=24821
http://wow-mania.com/armory/?quest=24820
http://wow-mania.com/armory/?quest=24819
http://wow-mania.com/armory/?npc=39509

**How it works:**
You cannot change your Ashen Verdict ring if you are Friendly with them
Honored, Revered and Exalted works as intended.

**How it should work:**
You should be able to change your Ashen Verdict ring if you are friendly too.

**Comment by wow-mania** [comment]
Where is the info that asserts that? I am pretty sure the requirement for rep is more than friendly.

**Comment by Kitzunu** [comment]
Those 4 quests linked above are all the quests that change the Friendly version of the Ring.
however, that quest does not appear when you are friendly.

As I mentioned above, the quests to change the Honored Revered and Exalted ring does show on the NPC

**Comment by Kitzunu** [comment]
Just to clearify.

You do get the ring at Friendly, however the quest(s) to switch it to one of the other rings does not appear over the NPC linked above at friendly which it is supposed to do

**Comment by Kitzunu** [comment]
All the quests I linked above works.

I forgot to add this quest too, when that is added it will work :)
http://wow-mania.com/armory/?quest=25247
