### ISSUE TITLE
[Quest] Rampage

### ISSUE THREAD

**Issue by Kitzunu** [WoWManiaUK/Redemption#3103]
http://wow-mania.com/armory/?quest=12721q
http://wow-mania.com/armory/?object=191018
http://wow-mania.com/armory/?npc=28952

Several issues here.

**How it works:**
1. There are no chains attached from the GameObject to Akali.
![image](https://user-images.githubusercontent.com/24550914/53749162-1e47e700-3ea7-11e9-9df2-0957a953c0c0.png)

2. When you press the GameObject nothing happens.

**How it should work:**
1. There should be chains attached to Akali from all 4 GameObjects.

2. When you click each GameObject a chain should be removed. When you have clicked all the quest should complete.

I made some research upon this and found a GitHub report on the Trinity Core GH.
By reading that report I have come to understand that the GameObject has no faction.

>https://github.com/TrinityCore/TrinityCore/issues/22938
Current behaviour:
Nothing happens when the gameobject is clicked.
Server.log show this (four times for each click on the gameobject):
GameObject (template id: 191018) has invalid faction (faction template id) #0

**Comment by wow-mania** [comment]
Does the quest work?

**Comment by Kitzunu** [comment]
No

**Comment by Kitzunu** [comment]
@wow-mania I just did the quest again, and somehow it completed this time.

The only missing thing are the chains.
Quest is completable and GameObject works.

**Comment by wow-mania** [comment]
so it is just the visual of the chains?

**Comment by Kitzunu** [comment]
Yes
