### ISSUE TITLE
[Profession] Unable to Smelt in Dalaran

### ISSUE THREAD

**Issue by Etherialis** [WoWManiaUK/Redemption#3104]
Currently, there is no way to smelt in the blacksmith's building, or in the mining building next door  in Dalaran. I am pretty sure the ability to do so was added to the smith's building was added the naxx release, but I do know you could smelt in the mining room with the molten minerals in it before hand. I've tried it with various minerals. Khorium was all I ha
![1](https://user-images.githubusercontent.com/15037448/53772338-b3e57580-3eab-11e9-8775-6cac48743d17.JPG)
![2](https://user-images.githubusercontent.com/15037448/53772340-b47e0c00-3eab-11e9-951f-7bf2a4603b1a.JPG)
![3](https://user-images.githubusercontent.com/15037448/53772341-b47e0c00-3eab-11e9-9bdf-8746c451417e.JPG)
![4](https://user-images.githubusercontent.com/15037448/53772342-b47e0c00-3eab-11e9-8fac-765ee5845bea.JPG)
![5](https://user-images.githubusercontent.com/15037448/53772343-b47e0c00-3eab-11e9-8da4-fd9ae3ce2cdc.JPG)

d free on me at the time.

**Comment by Kitzunu** [comment]
There is a forge in the Mining place in Dalaran.
![image](https://user-images.githubusercontent.com/24550914/53775619-8e7c5a00-3ef3-11e9-9a77-a26ca269e305.png)

Do you have any evidence that the Forge of Fate also were a forge? I cannot find any WotLK related info about it on the website? @Etherialis

**Comment by Etherialis** [comment]
Oh wows!! Not sure how I missed it.. Derp.

**Comment by Kitzunu** [comment]
@Etherialis Please do add info here though if you find any that the places you mentioned above should be forges too :)

**Comment by Rushor** [comment]
well nevertheless you should be able to smelt at the big forge - spellfocus is missing here

**Comment by Rushor** [comment]
http://www.wowwiki.com/Locations_of_fixed_devices_in_Dalaran
http://www.wowwiki.com/Forge_of_Fate
