### ISSUE TITLE
[Combat] Ranged mob follow after LoS but not Silence/interrupts

### ISSUE THREAD

**Issue by Etherialis** [WoWManiaUK/Redemption#3105]
When you for instance, shield bash a mob, and move away from them, they do not follow. Ranged mobs and casters just stand in place and wait for the effect to end instead of following and melee attacking. If you grab agro however, and line of sight these same mobs, 90% of the time they will chase you down. I have experienced it with a variety of mobs from vanilla-wrath expansion zones. Latest one was the unbound corrupters in crystal song. (Purple area)

**Comment by Kitzunu** [comment]
Does this only happen with Shield Bash or other abilities too? @Etherialis

**Comment by wow-mania** [comment]
As-is,

**Comment by Etherialis** [comment]
So far, shield bash is all I have to interrupt a caster type mob. So yes.
