### ISSUE TITLE
Abilities/spells not working properly

### ISSUE THREAD

**Issue by Hellbound2019** [WoWManiaUK/Redemption#3106]
I've noticed a couple character spells and abilities not working properly.
Warriors Victory Rush: doesn't appear to be healing at all.
Rogues Sap: range so short you practically have to be on top of the mob to use.
Goblins Rocket Jump: comically broken, distance is fine, but it also launches you so high into the air that you take falling damage. Best not to use while aimed down hill.

That's what I've noticed so far. I appreciate any who look into these issues.

**Comment by Kitzunu** [comment]
Please read the wiki on how to properly report an issue.
Your report is missing key things, what should happen, and most importantly **DO NOT log multiple issues in one**

Re-read the wiki and make a proper report please, then I'll be more than happy to look into your problems 

https://github.com/WoWManiaUK/Redemption/wiki/How-to-Properly-Report-an-Issue

**Comment by Kitzunu** [comment]
I can tell you right now that there is nothing wrong with Sap, it has a 10yard range which it has had since it got introduced into the game.
