### ISSUE TITLE
[Spell] Rocket Jump

### ISSUE THREAD

**Issue by Kitzunu** [WoWManiaUK/Redemption#3107]
http://wow-mania.com/armory/?spell=150000
https://www.wowhead.com/spell=69070/rocket-jump

**How it works:**
You take fall damage

**How it should work:**
You should not take fall damage

I know it is a custom spell, but would it be possible to make it ignore fall damage?

**Comment by wow-mania** [comment]
Unfortunately, there is nothing we can do about this because the jump most of the times lasts longer than the aura. So there is no way to detect if the player is falling from after using Rocket Jump or a normal fall.
