### ISSUE TITLE
[Achievement] Abuse the Ooze

### ISSUE THREAD

**Issue by skillszero** [WoWManiaUK/Redemption#3108]
**Links:**

https://www.wowhead.com/achievement=2155/abuse-the-ooze

**Current Behaviour:**

We waited like 10 minutes untill 6 ozes spawned. We killed even 6 and the Achiev didn't POP !

**Expected Behaviour:**

Getting the achiev

**Steps to reproduce the issue:**

**Additional info:**

**Comment by Kitzunu** [comment]
You need to kill the Iron Sludges, not the oozes.
The oozes become Iron Sludges when they get to the center of the room

http://wow-mania.com/armory/?npc=28165
![image](https://user-images.githubusercontent.com/24550914/53831308-d4cdc980-3f84-11e9-9f12-7c10bd668d52.png)
