### ISSUE TITLE
[Quest] The Air Strikes Must Continue

### ISSUE THREAD

**Issue by jarvik76** [WoWManiaUK/Redemption#3109]
http://www.wow-mania.com/armory/?quest=11533
In particular, the Wrath Enforcer NPC  http://www.wow-mania.com/armory/?npc=25030
Supplied item: 34475 "Arcane Charges"

**Current Behaviour:**
Wrath Enforcers are either very rare spawned, or it is very difficult to get credit when air strikes dropped on them.  It looks as if the Skeletal Ravagers / Frenzied ghouls in the area do too much damage to the Enforcers, so there is less than 50% health by the time the player flies overhead, and thus does not get credit when hit.
If one gets 3 Enforcer kills on a single run, it feels lucky.

It also feels like the player's hawk mount is flying too fast - faster than blizz.  It is very difficult to target/aim effectively.

**Expected Behaviour:**
Blizzlike behaviour is that it should be possible to complete all kills in a single run.  Occasionally one might get 11/12 enforcers.  In other words, it's pretty easy to do in one go.

**Steps to reproduce the issue:**
Take the quest, and try to kill the Enforcers using item provided.

**Comment by wow-mania** [comment]
Difficult does not mean broken? Which one is it? Where is it broken exactly?

**Comment by WhitephoenixTheBunny** [comment]
The secreenshot is on one run. 
I didn't focus on the other mobs, but 1~2 runs the daily is completed
![image](https://user-images.githubusercontent.com/31921098/54056616-89b3f080-41e8-11e9-803b-aa8f02b8f837.png)

**Comment by jarvik76** [comment]
Great, thanks for fixing it to like it should be :)  Much appreciated.
