### ISSUE TITLE
[Quest] Teron Gorefiend - Lore and Legend

### ISSUE THREAD

**Issue by Santoss71** [WoWManiaUK/Redemption#3111]
The quest is http://www.wow-mania.com/armory?quest=10644

How it should work: When arriving at Altar of shadows http://www.wow-mania.com/armory?zone=3944 and after equipping Spectrecles http://www.wow-mania.com/armory?item=30719 i should be able to see the Ancient Shadowmoon Spirit http://www.wow-mania.com/armory?npc=21797 and talk to him to complete the quest

How it's working: at the altar i can only see Teron Gorefiend http://www.wow-mania.com/armory?npc=21867 who shouldn't even be visible and cannot interact with him
![teron](https://user-images.githubusercontent.com/48369817/54062719-276ae800-4208-11e9-9f4e-d4a9911c1602.png)

**Comment by wow-mania** [comment]
Missing quest. You are in the wrong phase.

**Comment by Kitzunu** [comment]
I cannot reproduce this issue on dev
![image](https://user-images.githubusercontent.com/24550914/54071914-b8c37400-4273-11e9-9b87-4cddfa15961d.png)

**Comment by Kitzunu** [comment]
I will check on Redemption to see if it is different there.

**Comment by Kitzunu** [comment]
Cannot reproduce on Redemption either.
You must have missed a quest somehow OR you are on another quest that changed your phase.
![image](https://user-images.githubusercontent.com/24550914/54072097-5455e400-4276-11e9-9c7f-1e4bef7e0128.png)

@Santoss71 Try equipping the goggles at Wildhammer Stronghold and then fly there, because I cannot reproduce this issue.

**Comment by hammereddann** [comment]
![image](https://user-images.githubusercontent.com/122736582/229354815-0540f795-20fc-4a64-80c8-919ca23efd13.png)
Still an issue here. I have the buff for goggles and goggles on and still cannot see the Ancient Spirit!
![image](https://user-images.githubusercontent.com/122736582/229354858-4d99512c-a6c2-4c82-b9be-9aac9234b07e.png)

**Comment by GMZinius** [comment]
Thank you @hammereddann

**Comment by Echinaceax** [comment]
I just retested this for another player (for slightly different issue with it, and still cant reproduce not being able to see him 

![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/affd714d-ea7a-4976-813a-3359bf34c1d0)

Extra notes:
Apparently googles are not even needed 

TBC https://www.wowhead.com/tbc/quest=10644/teron-gorefiend-lore-and-legend#comments
Wotlk https://www.wowhead.com/wotlk/quest=10644/teron-gorefiend-lore-and-legend#comments
![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/56e2b92a-86ca-4cb1-879f-bdac1c25b794)
