### ISSUE TITLE
Val'anyr - legendary healer mace

### ISSUE THREAD

**Issue by andro3** [WoWManiaUK/Redemption#3112]
After using ~10 full mana bars i couldn't get my weapon to proc. Other players seem to have no problems with it but whatever i do absorbtion proc is not showing up.

**Comment by wow-mania** [comment]
NO issue here. As-is.

**Comment by Dranah** [comment]
Valanyr cannot proc if all you do is overhealing. The proc requires at least a portion of your healing to be actual healing done.
If your target keeps taking damage, it procs just fine.
