### ISSUE TITLE
[Texture] Jelinek Sharpshear

### ISSUE THREAD

**Issue by Kitzunu** [WoWManiaUK/Redemption#3114]
http://wow-mania.com/armory/?npc=29142

Got a hole in the head
![image](https://user-images.githubusercontent.com/24550914/54088236-38c50900-435c-11e9-9ac2-6565d1a0710c.png)

DisplayID `25624`

**Comment by Rushor** [comment]
that's nice xD

**Comment by Kitzunu** [comment]
DisplayID `20016` also have the same issue
