### ISSUE TITLE
[Spell] Siphoned Might

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#3115]
ID 74507
Found this while testing the other issue with the boss.
This is the buff applied to the "caster" when Baltharus https://www.wowhead.com/npc=39751/baltharus-the-warborn casts Enervating Brand https://www.wowhead.com/spell=74505/enervating-brand

**How it should work:** This effect should be applied to the boss himself.
More detailed: when Enervating Brand is used, Baltharus pretty much drains power from players. While players receive a debuff that reduces their damage/healing (as tooltip says, enemies' damage and healing is reduced), the boss himself should receive a matching buff, which increases his damage and healing, (as tooltip says, "while increasing the caster's damage and healing accordingly")

The 'caster' in this case is the boss. The more players near the target of enervating brand (=the more targets getting stacks of debuff), the more stacks the boss should gain as well, making it extremely dangerous to have it hit multiple players.

**How it works atm:** The damage/healing boost is applied to the players affected by the brand, effectively negating the loss from the debuff, while the boss gains no damage boost at all, making the entire mechanism lose its utility.

**Comment by Keader** [comment]
Looks fixed to me.
Check now @Dranah

**Comment by Dranah** [comment]
The stacks are now properly applied to the boss.
