### ISSUE TITLE
Eadric the Pure

### ISSUE THREAD

**Issue by Skallgrom** [WoWManiaUK/Redemption#3116]
**Links:**
The quest
http://www.wow-mania.com/armory/?quest=13794
The NPC
http://www.wow-mania.com/armory/?npc=33817

The npc doesn't give me the next quest that i need for the chain.

The npc just shows the exclamation mark (!) and it doesn't give when clicked, it's a huge problem because it's a quest chain for the argent crusade shop,that you cannot open without this.

**Comment by WhitephoenixTheBunny** [comment]
Can you tell me your race? That quest require previous quests race based and I need go back and do the whole questline

**Comment by wow-mania** [comment]
![image](https://user-images.githubusercontent.com/12248683/54109507-c0e7f480-43d6-11e9-882e-7e4fc2f2a45c.png)

Please check all requisites and do all quests up to that point.

**Comment by WhitephoenixTheBunny** [comment]
It may be a race issue, thats why I asked the race

**Comment by Skallgrom** [comment]
Yeah i tryed it with bloodelf and orc and she wouldnțt give the quest.

**Comment by Skallgrom** [comment]
Also i have done the quests in Argent Vanguard up to that one.

**Comment by Skallgrom** [comment]
the last quest was "The Black Night's Orders"

**Comment by WhitephoenixTheBunny** [comment]
I will check out

**Comment by WhitephoenixTheBunny** [comment]
Is working fine:
![image](https://user-images.githubusercontent.com/31921098/54225259-38ab4180-44f3-11e9-84de-d6d3d9f38678.png)

This is on the link you shared:
![image](https://user-images.githubusercontent.com/31921098/54225324-5b3d5a80-44f3-11e9-8ebd-0fc5c5974f83.png)
http://www.wow-mania.com/armory/?quest=13794


You, either haven't started previous questline or lost on it

This is the starting questline:
http://www.wow-mania.com/armory/?quest=13668

Here you can check the questline and see if you are lost on it
![image](https://user-images.githubusercontent.com/31921098/54224525-9b034280-44f1-11e9-9b5f-c580db4e2d4d.png)

**Comment by Skallgrom** [comment]
![WoWScrnShot_031219_213919](https://user-images.githubusercontent.com/48421574/54230732-b1b89200-450f-11e9-854e-34bf2444105b.jpg)
![WoWScrnShot_031219_213924](https://user-images.githubusercontent.com/48421574/54230733-b41aec00-450f-11e9-9901-6d266a54ded6.jpg)

**Comment by WhitephoenixTheBunny** [comment]
Check the quests... all of them...
You need do dailies to collect valian marks for like 2 weeks, u have done that?

**Comment by Skallgrom** [comment]
It's in the progress ,thanks for the quick feedback guys.You are awesome.
