### ISSUE TITLE
[NPC] Crusader Rhydalla

### ISSUE THREAD

**Issue by WhitephoenixTheBunny** [WoWManiaUK/Redemption#3123]
Both of the NPCs [Justicar Mariel Trueheart](http://www.wow-mania.com/armory/?npc=33817) & [Crusader Rhydalla](http://www.wow-mania.com/armory/?npc=33417) will show quest avaible when isn't.

![image](https://user-images.githubusercontent.com/31921098/54282306-a018ce00-4593-11e9-9b27-adcad5e882c9.png)
![image](https://user-images.githubusercontent.com/31921098/54282328-b0c94400-4593-11e9-84f2-b83ce0b615ce.png)

Is only a visual bug, but leading to confusion to some players.

Note: I have finished the quest line: http://www.wow-mania.com/armory/?quest=13663

Those NPC will give me quests when I will meet the requirments.

**Comment by wow-mania** [comment]
A visual bug only. Quests are shown correctly according to requirements. The only issue is "!" being shown when no quest is available. 
I will try to fix it but not a priority.

**Comment by wow-mania** [comment]
Just done all the quests and the ! has gone away. So if the requirements is missing you won't see it.

**Comment by Kitzunu** [comment]
I will take care of Justicar Mariel Trueheart later in another issue.
but for now, Crusader Rhydalla is fixed :)
