### ISSUE TITLE
No emote sound.

### ISSUE THREAD

**Issue by FlarePyroscythe** [WoWManiaUK/Redemption#3124]
Current Behaviour:

No sound at all from any characters using emotes that would have speech.

Expected Behaviour:

Sound when Emotes such as /silly or /flirt should be heard.

Additional info:

Have no clue why this is happening. A complete reinstall was performed, and nothing changed. Have checked, and sound boxes are ticked to on. Am currently playing a Worgen female Warrior, and have tried it with the male, yet have received the same issue.

**Comment by wow-mania** [comment]
Not a server issue. Reset your settings to default and delete WTF and cache folders. If not enough try asking in world chat how to solve it.
