### ISSUE TITLE
[Item] Vicious Warsaber Sound

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#3128]
**Links:**

https://www.wowhead.com/item=102514/reins-of-the-vicious-warsaber#comments

**Current Behaviour:**

The Vicious Warsaber's /mountspecial 'emote' (can also be triggered by pressing spacebar) makes a Skeletal Warhorse sounds rather than a cat sound.

**Expected Behaviour:**

It should sound more like 'ROAR!' than 'Neigh!'. 

**Steps to reproduce the issue:**

Step 1 Mount up on a Vicious Warsaber
Step 2 Press space bar
Step 3 Use ears

**Comment by wow-mania** [comment]
Fixed. But this requires client update so it will only be seen on the next time we update the client which may take a month or so.
