### ISSUE TITLE
cooking recipes for "Second that emotion" achievement

### ISSUE THREAD

**Issue by foter456** [WoWManiaUK/Redemption#3129]
The recipes for the achievement should be dropped by North Fleet Marines with a 0,5% chance/recipe. After killing about 200 mobs i did some calculation. The chances of not getting any of the 4 recipes after 200 mobs are below 2%. That's still okay,it can be bad RNG, but i had 17 (!) other items looted, all with lower or way lower drop rates (some with 0.02%). Tried with other type of mobs too,which drops only one recipe with 0,7% chance. Same issue, hours of farming, no recipe, but a full bag of items with about the same, or way lower droprates. This made me assume that the droprates on the given recipes are not exact, or they can't be dropped.

**Comment by Kitzunu** [comment]
http://wow-mania.com/armory/?npc=23983
http://wow-mania.com/armory/?item=43509
http://wow-mania.com/armory/?item=43510
http://wow-mania.com/armory/?item=43508
http://wow-mania.com/armory/?item=43507

**Comment by wow-mania** [comment]
OK after killing 200 you have the PROBABILITY of getting 1 on average.
Heads on a coin has a probability of 50%, does that mean that if you throw it twice you are guaranteed to get a head? :P

**Comment by foter456** [comment]
You definetly didn't understand my concept....
