### ISSUE TITLE
[Quest/Daily] Dangerously-Delicious (Fishing) in Wintergrasp

### ISSUE THREAD

**Issue by Roteki** [WoWManiaUK/Redemption#3131]
**Links:**

https://www.wowhead.com/quest=13834/dangerously-delicious

**Current Behaviour:**

There are no fishing schools in Wintergrasp.

**Expected Behaviour:**

There should be fishing schools in Wintergrasp.

**Steps to reproduce the issue:**

Go to Wintergrasp and try to find a school of fish.

**Additional info:**

This is a recent issue, as there was no problem with Wintergrasp fishing last week.

**Comment by Kitzunu** [comment]
Confirmed, I cannot find a single fishing pool in Wintergrasp

**Comment by Echinaceax** [comment]
i dont have a problem with doing the fishing daily "dangerously-delicious"

![i can fish](https://user-images.githubusercontent.com/39439201/54480208-fe5cdf80-4825-11e9-8312-5d52b12a882f.jpg)
![dont see a problem](https://user-images.githubusercontent.com/39439201/54480212-0157d000-4826-11e9-8def-90d10a302cbe.jpg)

**Comment by wow-mania** [comment]
Make sure you have the minimum level to fish there.

**Comment by Roteki** [comment]
Yeah, I have 450 fishing. There is no issue with fishing terrorfish, I just didn't know what else to put there, since it's the only quest connected to Wintergrasp fishing schools. My original ticket didn't have the [Quest/Daily] tag, just Wintergrasp fishing.

The issue I reported was that there are no fishing schools in the whole zone.

**Comment by Kitzunu** [comment]
There are no fishing schools in Wintergrasp.
These are the fishing schools in Northrend
![image](https://user-images.githubusercontent.com/24550914/54480416-690f1a80-4828-11e9-9934-52a69cb9f5a4.png)

As for the quest, you can see that it is completed in WG without a school.

I misunderstood, I apologise for that.
There is no issue here

**Comment by Echinaceax** [comment]
> There is no issue with fishing terrorfish, I just didn't know what else to put there

Ah understood, thats what confused me :)

but as Kitz replied "there are not meant to be any "fishing pools in WG"
