### ISSUE TITLE
If he cannot

### ISSUE THREAD

**Issue by Tholia** [WoWManiaUK/Redemption#3132]
**Links:**

CHANGEME. Copy the link of the NPC/Quest/item etc, from WoWHead or our Armory

**Current Behaviour:**

CHANGEME. Tell us what happened

**Expected Behaviour:**

CHANGEME. Tell us what should have happened instead.

**Steps to reproduce the issue:**

CHANGEME. Step 1
Step 2
Step 3

**Additional info:**

CHANGEME. Is there any extra info that we need to know?

**Comment by Tholia** [comment]
March 17, 2019
Account Tholia
User: Yodal

Links:
http://www.wow-mania.com/armory/?quest=12896

If he cannot be turned, in Shadow Vault, @ Ice Crown.

Have killed General Lightsbane 7 times and have not gotten credit for it.  Unable to continue quest line.

Searched WoW- Mania.com/Armory and WoWHead.com 

Pre quest (#12893) ref WoWHead “Free Your Mind” quest was completed correctly.  This is verified as the 3 NPCs did participate in the “If he cannot be turned” quest (#1387)

Character Issue specific—
No; as this has been successfully completed by 2 other characters on this account.

UI or Addon issue- 
No, same load for all previous successful completions.

Client; 2.5.2
Launcher: Latest
Steps to Reproduce: see above, pre quest completed, killed General Ligthsbane (WoWhead and Armory), did not count.
How it should work; After Death of General Lightsbane the flag indicator should toggle.
What is happening: As noted above
Name of NPC: As noted above

Note: viewed Identical problems on Git hub, verify I did continue attacking the entire time on 7th try.

**Comment by Kitzunu** [comment]
@Tholia Was this issue supposed to be closed, or did you missclick?

**Comment by Tholia** [comment]
Opps I thought I was saving the message.  Obtw, I ran another toon 
through the quest line and it worked for him.  Could that particular 
character be corrupt, I have had a number of issue with it lately?

------ Original Message ------
