### ISSUE TITLE
[Quest] A Crystalforged Darkrune

### ISSUE THREAD

**Issue by vexira** [WoWManiaUK/Redemption#3133]
I file this bug on GM Aymelek request.

The problem is with Gahk NPC in Ogri'la.
My rep is honored, and I have done a quest for him already ([A Fel Whip For Gahk]).
The next quest is not available to me ([[A Crystalforged Darkrune](https://www.wowhead.com/quest=11060/a-crystalforged-darkrune
)]), but the NPC has a golden '?' over his head, waiting for me to turn in this very quest.
This is the problem.

GM Aymelek has tested it and has the same problem.

Here is a screenshot with most of the elements on screen.

![WoWScrnShot_031719_154050](https://user-images.githubusercontent.com/46292860/54492951-43871d00-48cb-11e9-9f25-0cf826c9c138.jpg)

Plus a screenshot of my quest log

![WoWScrnShot_031719_154556](https://user-images.githubusercontent.com/46292860/54493029-e3dd4180-48cb-11e9-94e8-86024da65ea2.jpg)

**Comment by wow-mania** [comment]
You can collect the item and get and complete the quest at the same time.

**Comment by wow-mania** [comment]
Rushor added the condition to show quest only if you have the item.

**Comment by wow-mania** [comment]
Quest is not auto-completable anymore.
