### ISSUE TITLE
[Dungeon] Mechanar

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Redemption#3134]
**what happened**
 killing both gate watchers the gate/barrier for the lift up to the next area opens as intended but another member of the team can then reactivate the gate closing it. The gate cannot then be re-opened so if half the party is on one side the are trapped once closed again
After

 **what should have happened instead.**
the gate needs to be made so that it non-interactable once opened preventing others in the party from closing it.

**Steps to reproduce the issue:**

. Step 1 kill gate keepers
Step 2 combine crystals to create legion key
Step 3 open cache to receive loot
step 4 click the cog icon near the open gate and it will shut the gat, preventing it from being reopened.

**Comment by wow-mania** [comment]
You are on a dungeon! :)
Don't go around pushing levers you don't know.

**Comment by sarahkay88** [comment]
Haha I was asked by GM Farwinds to check it out. He had a few reports so I went to confirm the issue.

**Comment by Kitzunu** [comment]
I can confirm that after the gate has been open, a regular player can press the gate, locking it for everyone
![image](https://user-images.githubusercontent.com/24550914/54520341-c5795380-4968-11e9-8c7c-2930fa835a04.png)
![image](https://user-images.githubusercontent.com/24550914/54520355-ce6a2500-4968-11e9-8411-2730d6516a02.png)

After the gate is opened it should not be clickable at all.

Broken: http://wow-mania.com/armory/?object=184632 (Mo'arg 1 door)
Works as intended: http://wow-mania.com/armory/?object=184322 (Mo'arg 2 door)

**Comment by Kitzunu** [comment]
You can no longer press Mo'Arg 1 Door when the door is down nor when it is up.
Should cause no more issues now :)
