### ISSUE TITLE
[Spell/Warlock] Enslave Demon -61191-

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Redemption#3136]
**Links:**

http://www.wow-mania.com/armory/?spell=61191

_Was Asked by GM weeble to see if this spell worked_ 
tested on (rank 4) 

**What is Happening:**
- It casts on the demon but...
- Demon doesnt move when sent to attack (just turns around and stands there)
- Tested on passive - defensive and aggressive
- Tested 2 different lvls of Demon (Ashenvale and Outland)

![outland](https://user-images.githubusercontent.com/39439201/54547273-b1a01280-49a5-11e9-81ec-d7056fa8b5c2.jpg)

![doesnt attack](https://user-images.githubusercontent.com/39439201/54545032-1dcc4780-49a1-11e9-944b-004497951802.jpg)

**What Should happen:**
- Enslaved Demon should act as a pet for 5 mins and attack your target you sent it to attack

![should attack](https://user-images.githubusercontent.com/39439201/54544018-faa09880-499e-11e9-963f-00996b13f813.jpg)

**To reproduce** 
1. Enslave the demon
2. set his action bar too attacks active
3. Set his aggression status 
4. Send pet (demon) to attack your target

![cant send pet](https://user-images.githubusercontent.com/39439201/54546915-fe371e00-49a4-11e9-856b-532cdaf5b050.jpg)

**Comment by Dranah** [comment]
Same issue as https://github.com/WoWManiaUK/Redemption/issues/2879 and https://github.com/WoWManiaUK/Redemption/issues/2586
Unless there were changes to the core, i guess it's still not possible to fix.

**Comment by Keader** [comment]
I really tried.
I don't know why guardians just ignore it

**Comment by Rushor** [comment]
Will try, but cannot promise
