### ISSUE TITLE
[NPC] Image of Archmage Modera

### ISSUE THREAD

**Issue by Ebonlox** [WoWManiaUK/Redemption#3138]
**Links:**
http://www.wow-mania.com/armory/?quest=11995

**What is Happening:**
I completed the quest "Your Presence is required at Star's Rest" and turned in to Image of Archmage Modera at Star's Rest but no further quests are offered. Please see armory link above.

**What Should happen:**
After turning in "Your Presence..." a line of quests should open, offered by Modera, beginning with "Rifle the Bodies.

I am on launcher 2.5.2. Deleted cache and re-tried multiple times. Chatted with GM Psygoa in game and issue could not be resolved.

Thank you for your attention in this matter.

**Comment by WhitephoenixTheBunny** [comment]
The quest [Rifle the Bodies](http://www.wow-mania.com/armory/?quest=12000) can be opened by 2 quests:
[Your Presence is Required at Stars' Rest](http://www.wow-mania.com/armory/?quest=11995)
**OR**
[To Stars' Rest!](http://www.wow-mania.com/armory/?quest=12440)

At the moment, [Your Presence is...](http://www.wow-mania.com/armory/?quest=11995) does not give the quest [Rifle the Bodies](http://www.wow-mania.com/armory/?quest=12000).

![image](https://user-images.githubusercontent.com/31921098/54552063-2889db00-49a7-11e9-8629-2c7d62a78afe.png)


[To Stars' Rest!](http://www.wow-mania.com/armory/?quest=12440) will open the quest [Rifle the Bodies](http://www.wow-mania.com/armory/?quest=12000) (auto offer)

![image](https://user-images.githubusercontent.com/31921098/54552224-81597380-49a7-11e9-951a-ba938e9387c9.png)

**Comment by Ebonlox** [comment]
Having completed "Your Presence is Required at Star's Rest" already, I don't believe that "To Star's Rest" can be offered to me. Is there a way this can be resolved?

**Comment by Ebonlox** [comment]
Nevermind. I was able to get "to star's rest"
issue seems to be resolved
I will steer people away from "Your presence...." should it come up

**Comment by WhitephoenixTheBunny** [comment]
One quest should close the other one
Is a requirment issue

**Comment by Ebonlox** [comment]
OK, hope my report is helpful. In the short term i was able to get the quests I was seeking and will recommend "to star's rest" for the time being.

Thank you for your help and attention.

**Comment by Rushor** [comment]
https://github.com/TrinityCore/TrinityCore/issues/22968 some strange stuff with breadcrumb is going on there

**Comment by WhitephoenixTheBunny** [comment]
on drugs?

**Comment by wow-mania** [comment]
Armory updated today.
