### ISSUE TITLE
[Faction/Reputation] Thorium Brotherhood

### ISSUE THREAD

**Issue by WhitephoenixTheBunny** [WoWManiaUK/Redemption#3139]
To farm the reputation from [Thorium Brotherhood](http://www.wow-mania.com/armory/?faction=59) you have the 3 phase:

> Reputation
> Neutral to Friendly
> Turn in  Incendosaur Scale,  Coal and either  Heavy Leather,  Iron Bar, or  Kingsblood to Master Smith Burninate.
> Friendly to Honored
> Turn in  Dark Iron Residue to Master Smith Burninante.
> Honored to Exalted
> Turn in  Dark Iron Ore to Lokhtos Darkbargainer.
> Turn in  Core Leather to Lokhtos Darkbargainer.
> Turn in  Fiery Core to Lokhtos Darkbargainer.
> Turn in  Lava Core to Lokhtos Darkbargainer.
> Turn in  Blood of the Mountain to Lokhtos Darkbargainer.

As described on Armory

I am at the moment getting the rep from Neutral to Friendly, and for that I am turning 3 repeatable quests:
[Restoring Fiery Flux Supplies via Kingsblood](http://www.wow-mania.com/armory/?quest=7736)
[Restoring Fiery Flux Supplies via Heavy Leather](http://www.wow-mania.com/armory/?quest=8242)
[Restoring Fiery Flux Supplies via Iron](http://www.wow-mania.com/armory/?quest=8241)

On armory, the 3 quests says:
![image](https://user-images.githubusercontent.com/31921098/54680594-25573200-4b02-11e9-9e1f-6e0756590280.png)

The requirement, for the 3 quests is:
![image](https://user-images.githubusercontent.com/31921098/54680629-3bfd8900-4b02-11e9-89f9-c8acfab4bf13.png)

I am neutral:
![image](https://user-images.githubusercontent.com/31921098/54680663-59caee00-4b02-11e9-9d82-ff2eb8359cac.png)

At the moment quest are giving only 25 reputation
![image](https://user-images.githubusercontent.com/31921098/54680703-7bc47080-4b02-11e9-9a8e-9f00ebd2f035.png)

I know isn't a faction with benefits, but I am doing Loremaster and exalting on the Reputation I can

**Comment by WhitephoenixTheBunny** [comment]
Nop

**Comment by wow-mania** [comment]
Fixed now
![image](https://user-images.githubusercontent.com/12248683/54816364-fbca1200-4c8b-11e9-9668-2b6b69a19b11.png)
