### ISSUE TITLE
[Quest] A visit to the Doctor

### ISSUE THREAD

**Issue by Aciid88** [WoWManiaUK/Redemption#3140]
**Links:**
https://de.wowhead.com/npc=30992/doktor-sabnok#english-comments
https://www.wowhead.com/quest=13152/a-visit-to-the-doctor

**What is Happening:**
The doc Kills Patches in 2-4 seconds and if patches die he kills the player in the same time
according to wow head he should have only 10k life i think thats the problem

**What Should happen:**

**Comment by WhitephoenixTheBunny** [comment]
On Mania armory he shows http://www.wow-mania.com/armory/?npc=30992
![image](https://user-images.githubusercontent.com/31921098/54687708-1ed1b600-4b14-11e9-93a1-83d360cf121d.png)

This is the NPC info
![image](https://user-images.githubusercontent.com/31921098/54687972-b2a38200-4b14-11e9-81a4-908d0f383342.png)

You need assist Patches, he will not kill Doctor alone, and you need do more than half of damage, if I am correct, to the quest be complete.

**Comment by Kitzunu** [comment]
Something is weird with either Patches HP or the Doctors damage

I believe Rushor sent a fix to Janitor

**Comment by WhitephoenixTheBunny** [comment]
Thanks for rechecking it...
