### ISSUE TITLE
[Creature/Spell] Explosive Sheep

### ISSUE THREAD

**Issue by Kitzunu** [WoWManiaUK/Redemption#3143]
http://wow-mania.com/armory/?item=4384
http://wow-mania.com/armory/?spell=4074
http://wow-mania.com/armory/?npc=2675

**Description:** This is a Construct which Engineer's can craft and use, which should detonate at the target, and can only stay out for max 3 minutes before it disappears.

**What is happening:**
The sheep does not explode on impact with the target.
The sheep melee attacks the target.
The sheep is out for way longer than 3 minutes.
The sheep initates fights without the player being attacked / attacking (PVE) (It should only initate it own fights in PvP!)
The sheep is following the player

**What should happen:**
The sheep should explode on impact with the target
The sheep should never melee the target (duh)
If the sheep has not exploded within 3 minutes it should despawn
The sheep should only initiate a fight in PVE if the player attacks the enemy OR if the player is being attacked by the enemy
The sheep should take off on it's own path and not follow the player

**Comment by Kitzunu** [comment]
![image](https://user-images.githubusercontent.com/24550914/54830286-86286b00-4cb8-11e9-8211-a1f76d36146f.png)

**Comment by Keader** [comment]
Fixed 💃

**Comment by Kitzunu** [comment]
The sheep explodes now at least 🗡 
It dies after 3 minutes as intended.

The sheep works as intended now, in PvE and PvP.

I have not found any info on this, but do you know if the damage from the sheeps explosion should scale?
