### ISSUE TITLE
[NPC] Leviathan Defense Turrets

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#3144]
https://www.wowhead.com/npc=33142/leviathan-defense-turret
https://www.wowhead.com/npc=33113/flame-leviathan encounter

**How it should work:**
- These NPCs should be on Leviathan's body, not targetable by players on foot.
- 2 turrets on 10man, 4 on 25man.
- 2 or 4 Players should be able to land on the leviathan after being launched from the demolishers via Throw Passenger https://www.wowhead.com/spell=62324/throw-passenger
- Throw passenger itself simply throws players on the trajectory that the demolisher shoots, it is Flame Leviathan who must hook the players onto himself (similar to grab crate done by demolisher gunners)
- Players mounting the leviathan must be able to target and kill the turrets
- Players mounting the leviathan must also be periodically attacked by the turrets' https://www.wowhead.com/spell=62402/searing-flame
- Killing all turrets must result in https://www.wowhead.com/spell=62475/systems-shutdown on the leviathan and the players on him to be parachuted in the air.
- Over time the dead turrets repair themselves (much like Mimiron's body parts)
- https://www.wowhead.com/achievement=2909/take-out-those-turrets-10-player
and https://www.wowhead.com/achievement=2910/take-out-those-turrets-25-player should be awarded to players who land a killing blow on a turret.

**How it works atm:**
- Turrets misplaced, they are on the ground and i only saw just one.
- Turrets are invisible and non-targetable by anyone. (only visible in GM mode)
- Players launched onto the Leviathan are rooted on the ground in the position where Leviathan was in the moment of launch instead of being hooked onto leviathan's body. These players are then stuck there with nothing to attack and no way to get out.
- You can't overload Leviathan since you have no means to kill the turrets and you also can't complete the achievements
- At random intervals Leviathan overloads anyway, probably because the turrets are capable of taking splash damage from pyrite stacks (this is totally unintended) and dying. Killing turrets this way however does not count for the achievement.

**Comment by rockysnow9** [comment]
Confirmed, is bugged I raid this specific instance all the time, every week, and have all the achs in 10 man, (except 2) and ONLY missing 5 from 25 man, and the turret achievement, which is not currently obtainable is one of them. because you cannot do anything with the turrets, no damage to or from them.

**Comment by Keader** [comment]
Impossible fix in current version of core.
Need some updated that we dont have.

**Comment by Dranah** [comment]
No chance for an improvement either?

**Comment by grigtsiouv** [comment]
Hello, this issue stilll exists. the turrets are on top of flame leviathan, but you get a "you cannot attack this target" message when u try to attack them. Aoe damage from pyrite stacks does indeed damage, however it reduces the turrets hp to 1/65k

**Comment by Rushor** [comment]
https://www.wowhead.com/achievement=2910/take-out-those-turrets-25-player

try this improvement pls. if fully damaged the turret you should get the achievement
