### ISSUE TITLE
[Quest] Teron Gorefiend, I am..

### ISSUE THREAD

**Issue by Drostthehunter** [WoWManiaUK/Redemption#3148]
Hello, ive been working around on a quest http://www.wow-mania.com/armory/?quest=10639 at the Shadowmoon Valley, trying to finish the chain line for obtaining a mog item.
 I have found a various amounts of bugs related to this quest. On this quest you are supposed to kill http://www.wow-mania.com/armory?npc=21877 , Karsius the Ancient Watcher while you are controlling a summoned pet called Teron Gorefiend, that has available amount of mana that you can use to cast spells that you get in a special cast bar once the quests start.

![WoWScrnShot_032319_155543](https://user-images.githubusercontent.com/43518434/54867837-57c49180-4d85-11e9-8868-265a7ba66f16.jpg)
The Screenshot is showing that the summoned spirits around you are damaging you, also you can see the cast bar of my controllable pet.
![WoWScrnShot_032319_155627](https://user-images.githubusercontent.com/43518434/54867852-775bba00-4d85-11e9-8a2b-fc1a32171b14.jpg)
Here you can see that Krasius is not attacking summoned pet but instead attacking me (Drostan) Also you are unable to auto attack the Krasius even tho you have the *sword* icon plus auto attack icon down in your pet bar. Since you are unable to regenarate mana of the summoned, once you use all your spells you need to auto attack him till he is dead, but since you can autoattack him you also can not kill him, while you are constantly taking damage from the summoned spirits shown on 1st screenshot. 
![WoWScrnShot_032319_155651](https://user-images.githubusercontent.com/43518434/54867878-d15c7f80-4d85-11e9-93a0-6bffebb02947.jpg)
Last Screenshot is showing that Krasius actually did attacck me and damaged me before he killed my summoned unit and then dissapeared. 
There are many things causing this quest not to be able to complete, since i was not only one doing this quest, guildiie of mine actually did killed it and got no completition of the quest.

**Comment by Kitzunu** [comment]
I can confirm that Karsius is attacking the Player and not the Pet.
I can also confirm that the spirits are attacking Gorefiend way too often and way too much.
I can confirm that the autoattack of Gorefiend does not work
I can confirm that if you kill Karsius you do not get credit

![image](https://user-images.githubusercontent.com/24550914/54882444-67fa7080-4e5a-11e9-98fe-bd2c8eba93c3.png)

**Comment by Drostthehunter** [comment]
The quest is doable only under 1 sircumstance:
You can get a friend to heal the Teron Gorefiend while you are killing Krasius
There is a spell that uses no mana, showing as Death and Decay, and it does do dmg to the Krasius but takes some time to take down all the health, which would not happen if you dont have anyone to heal you.
Also it is questionable shall other people not related to the quest be able to see my controlled pet *Teron Gorefiend* without using "Spectrles" ( Item provided at the start of the chain that makes you see all those NPCs that are hidden).

**Comment by Drostthehunter** [comment]
I have done it just like i explained in the comment before and i did got quest completed, since this is last quest of the chain, there were no more problems corelating with this one.

**Comment by Rushor** [comment]
it's a hard one, cause it's a vehicle
