### ISSUE TITLE
Event Quests should be removed from quest log when Event ends

### ISSUE THREAD

**Issue by Kitzunu** [WoWManiaUK/Redemption#3149]
**What happens:** Event quests are not removed when the event is over.
![image](https://user-images.githubusercontent.com/24550914/54870977-d2a1a280-4dad-11e9-834a-ea26fa3ddc1b.png)

Here we can see that Brewfest is not active, but I still have the quest in my quest log.

**What should happen:** Event quests should be removed from quest log when the event is over

**Comment by Dranah** [comment]
The pain of deleting them from 25 alts. Damn.

**Comment by Kitzunu** [comment]
@Dranah ikr xD
Minor issue, but still a bug :D

**Comment by wow-mania** [comment]
As-is this is the same as retail. Just delete the quest.
