### ISSUE TITLE
You have been disconnected from server

### ISSUE THREAD

**Issue by Glennfyr** [WoWManiaUK/Redemption#3151]
You have been disconnected from server over and over again I'm getting the same error message when I login to my any charachter
![1](https://user-images.githubusercontent.com/48884313/54880440-a0e41680-4e55-11e9-858e-713b0a4ab52a.png)
![2](https://user-images.githubusercontent.com/48884313/54880441-a0e41680-4e55-11e9-81e1-4d5c8b80a104.png)
![3](https://user-images.githubusercontent.com/48884313/54880442-a3467080-4e55-11e9-8167-607133fe0e18.png)

**Comment by wow-mania** [comment]
Please read our wiki. 
This is not why we have this repository.
If you have connection problems please contact support.

**Comment by Glennfyr** [comment]
I don't have any connection problems goddamnit

**Comment by Glennfyr** [comment]
how can I see my toons If I had connectivity issues...

**Comment by Echinaceax** [comment]
Are you using a VPN ?
coz that will do the same issue as your describing

if no, then asking in Discord : discord.gg/R6DcdcP

**Comment by Glennfyr** [comment]
Im not using vpn but my router is provided by my isp and there is an embedded dns proxy which cannot be changed by user by any means .. And i think i ve figured it out it was my ip ... I ve changed my wan ip adress and problem solved.. Thanks for your concern

Have a nice week

iPhone'umdan gönderildi

24 Mar 2019 tarihinde 17:09 saatinde, Echinaceax <notifications@github.com<mailto:notifications@github.com>> şunları yazdı:


Are you using a VPN ?
coz that will do the same issue as your describing

if no, then asking in Discord : discord.gg/R6DcdcP

**Comment by WhitephoenixTheBunny** [comment]
Download ONLY the launcher, or when website or on discord.
