### ISSUE TITLE
[Quest] It goes to 11...

### ISSUE THREAD

**Issue by Kitzunu** [WoWManiaUK/Redemption#3153]
https://www.wowhead.com/quest=11421/it-goes-to-11
https://www.wowhead.com/spell=43986/fiery-harpoon
https://www.wowhead.com/spell=43997/fiery-lance
https://www.wowhead.com/npc=24533/dragonflayer-defender

**How it works:**
Dragonflyer Defenders are spawned from start in the air
1 Dragonflyer Defender counts as 2 "kills"
When you use Fiery Harpoon on Dragonflayer Longhouse, Dragonflayer Dockhouse and Dragonflayer Storage Facility they do not get Destroyed, which means you do not get quest credit for it.

**How it should work:**
The Dragonflyer Defenders should spawn when you shoot at one of the Dragonflyer Houses.
1 Dragonflyer Defender kill should be equal to 1 quest kill
When you use Fiery Harpoon on Dragonflayer Longhouse, Dragonflayer Dockhouse and Dragonflayer Storage Facility you should get credit.

**Comment by wow-mania** [comment]
Works. I am not going to start nitty picking on quests that work at this point. Sorry. I will check but it is in no way a priority. This may be due to the fact that you kill 2 npcs at a time.

**Comment by WhitephoenixTheBunny** [comment]
I have just see this today.

@Keader have fixed some quests like that on #2588
