### ISSUE TITLE
[NPC] Hierophant Liandra

### ISSUE THREAD

**Issue by Kitzunu** [WoWManiaUK/Redemption#3154]
https://www.wowhead.com/npc=25838/hierophant-liandra

**How it works now:**
She sometimes falls through the texture

**How it should work:**
She should never fall through the texture

**Comment by wow-mania** [comment]
Nothing to do with NPC this is a glitch in the Map.
Nothing to do. But try a better position.

**Comment by Kitzunu** [comment]
@wow-mania couldnt this be fixed by changing the NPCs state to flying instead of ground/swim
