### ISSUE TITLE
[Quest] Hodir's Tribute

### ISSUE THREAD

**Issue by RushdieRocks** [WoWManiaUK/Redemption#3156]
**Links:**

http://www.wow-mania.com/armory/?npc=32540
http://www.wow-mania.com/armory/?quest=13559

**What is Happening:**

I'm having problems with Sons of Hodir rep increase by way of Relics of Ulduar. I theory, the NPC Lillehoff should offer a quest called "Hodir's Tribute", but he is only available as vendor. I contacted a GM about the issue and they told me to report the bug here. 

Other relevant info: 
I am not at war with the faction, and have completed the quest chain up until "Krolmir, Hammer of Storms", and I'm currently neutral 2750/3000, and have Relics of Ulduar in my inventory.  

**What Should happen:**
Lillehoff should offer the quest "Hodir's Tribute"

**Comment by Kitzunu** [comment]
I can confirm that http://www.wow-mania.com/armory/?quest=13559 does only come available at "Friendly"

**How it should be:**
The quest should be available from "Neutral" status with Sons of Hodir
https://wowwiki.fandom.com/wiki/Quest:Hodir%27s_Tribute

**How to reproduce:**
1. go to Lillehoof
2. .mod rep 1119 neutral - check the NPC
3. .mod rep 1119 friendly - see that the quest comes available

**Comment by wow-mania** [comment]
![image](https://user-images.githubusercontent.com/12248683/55277128-b2656c80-52f4-11e9-9eae-9288f518b2c0.png)
