### ISSUE TITLE
[Spell] Lightwell

### ISSUE THREAD

**Issue by Tamagucci** [WoWManiaUK/Redemption#3159]
https://cdn.discordapp.com/attachments/529549035837587466/561959345701519370/unknown.png

Hi there, I've noticed a bug I think that pertains to Lightwell priest talent. It seems that currently you can only use the lightwell once. After you click it, get the heal, you can not interact with it again for another use. The screenshot I posted shows me hovering over the lightwell without the "interact" wheel after using it once. I waited until it dissapeared to see if there was some internal cooldown but nothing. 

I believe that on retail, you were able to use it multiple times essentially spamming it if you wanted.

**Comment by Kitzunu** [comment]
http://wow-mania.com/armory/?spell=27870
https://github.com/TrinityCore/TrinityCore/pull/4254

**Comment by wow-mania** [comment]
@Dranah Is this valid?

**Comment by Keader** [comment]
Fixed.
Each player can click 1 time each 7 sec.

**Comment by Dranah** [comment]
@wow-mania 
yes, players should be able to benefit more than once - with the limitation that you cannot click again until your previous effect expires.
That more or less matches what keader says, since the effect lasts 6sec - allowing ppl to click it every 7sec is close enough.

**Comment by Tamagucci** [comment]
Thank you! works now
