### ISSUE TITLE
[Spell] Flames - Mimiron 

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#3160]
http://www.wow-mania.com/armory/?spell=64566
http://www.wow-mania.com/armory/?spell=64561

1) Damage need to be resistible
Currently the damage is not resistible on mania.
Yes, i know they do not have the attribute here. But that is wrong. I've brought some evidences:
Here's a log from worldoflogs retail 3.3.5: http://www.worldoflogs.com/reports/mvcx6ygcwgyvs5rt/spell/64566/?s=7301&e=7752
You can see at average 25% of the total damage was resisted by players, which is accountable to a single fire resistance aura/totem active that nearly every group has.
Same on this one http://www.worldoflogs.com/reports/wkm55ua9s5v1g8in/spell/64566/?s=2856&e=3226

2) Flames area radius is too large.
The visual is meant to be wider than the actual damage range that is only 3 yards, aka you need to be standing right on top of it to take any damage.
Here's a retail video showing how easily people walk through what seems to be a wall of flame but do not take a single tick of damage with no absorbs/immunities on the buffs as they cross between the patches.
2:18-2:28 https://www.youtube.com/watch?v=9QmwU-eI9Bg
As you can see, even after a new flame spreads on top of someone, they can move out of it without taking any damage, because it is possible to leave the 3yard radius of it before it would tick (takes 1s before tick)
The intended tactic to control flames is to stand right next to a fire and only move away when it moves on you.
This tactic does not work on mania because the new fire spawning on you is impossible to dodge and with the higher, non-resistible damage, it is potentially lethal to allow it to reach you.
PS: It is possible that the root of the problem is, just like for other similar issues, the 3 yard range is calculated from the edge of the flame NPC's hitbox rather than its center.

3) Flames sometimes stop spawning after the Leviathan MK II casts "Flame Suppressant"
May be related to the flame cap, because it usually happens if you fire cap the room before the suppressant occurs.
http://www.wow-mania.com/armory/?npc=33432
http://www.wow-mania.com/armory/?spell=65192
After the Flame Suppressant, you can see the explosion animation trigger when new flames should spawn, but no fire patches spawn (just like when you're flame capped), even though the suppressant has cleared it all, which should reset the flame cap.
Throughout the whole fight after, explosions cause no patches to spawn.
Another reason why it seems the encounter thinks you are flame capped is that Frost bomb keeps spawning during p2 which normally does not if you have no fires outside melee range. Judging by the position where Frost bombs appear, basically the encounter can still see the flame patches that were spawned before the Suppressant cleared them.

**Comment by Keader** [comment]
1 - Fixed
2 - Is that bug using wrong point to calculate radius... Nothing that i can do to fix it. But... i change the radius to 2 yards, may it will be better now.
3 - Fixed

**Comment by Dranah** [comment]
Damage of flames is now resistible. (fixed)
The radius is now much more blizzlike. (fixed)
Flame suppressant no longer stops fires from spawning.
A new issue came up with the flame cap, however. Once capped, fires stop spreading, but new patches still appear whenever an explosion happens. This is not intended.

**Comment by Keader** [comment]
Try now.

**Comment by Dranah** [comment]
Same issue still, initial patches keep spawning past the cap.

**Comment by Keader** [comment]
?????

https://youtu.be/H5vK3cRkmA4
Looks working for me.

**Comment by Dranah** [comment]
Weird, last night it didn't... now it really does.
