### ISSUE TITLE
[NPC] Burst target

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#3161]
"Burst target" NPC
This invisible stalker NPC is responsible for marking the person targeted by VX-001's "Rapid Burst"
http://www.wow-mania.com/armory/?npc=33651
http://www.wow-mania.com/armory/?spell=64019

It is currently attacking players for physical damage. 
You can see it on my priest's death log, he hits for about 2k and is capable of critting and dazing targets he hits from behind:
![WoWScrnShot_033119_160610](https://user-images.githubusercontent.com/31132743/55290599-6e966400-53d5-11e9-8b59-746c20aba6bd.jpg)

This NPC should not be attacking anyone.

**Comment by Keader** [comment]
"kill this little caaaaat !"
Will be fixed tonight :)

**Comment by Dranah** [comment]
I love how you weren't brave enough to say 'pussy' :P

**Comment by Dranah** [comment]
No more invisible NPC attacks.
