### ISSUE TITLE
[Quest] The Wayward Apprentice

### ISSUE THREAD

**Issue by Felfyre** [WoWManiaUK/Redemption#3164]
**Links:**https://www.wowhead.com/quest=9254/the-wayward-apprentice

**What is Happening:**
Cannot speak to NPC, Apprentice Mirveda

**What Should happen:**

Should be able to talk to NPC Apprentice Mirveda to turn in quest, and get the first of her 2 quests

**Comment by WhitephoenixTheBunny** [comment]
#2521
Regression?

**Comment by Kitzunu** [comment]
@WhitephoenixTheBunny I've been trying to find the reason to this, and the quest works *most* of the times, but there's still some weird bug...

**Comment by wow-mania** [comment]
Please retest

**Comment by Felfyre** [comment]
I will, it will have to be later today ty 😀

**Comment by Felfyre** [comment]
I have gotten the quest that leads to apprentice mirveda... Can't rem the
name and not at my computer atm

**Comment by Felfyre** [comment]
Rechecked the npc with cleared cache. Attached is screen's hot with my log
showing I have the quest to go to her

**Comment by Felfyre** [comment]
Still cannot interact
