### ISSUE TITLE
[Quest] Saltheril's Haven

### ISSUE THREAD

**Issue by Felfyre** [WoWManiaUK/Redemption#3165]
**Links:**
https://www.wowhead.com/quest=9395/saltherils-haven

**What is Happening:**
You cannot pick up the quest from the NPC,  Magistrix Landra Dawnstrider

**What Should happen:**

You should be able to pick up the quest from the NPC,  Magistrix Landra Dawnstrider

**Comment by Kitzunu** [comment]
You have to have done  http://wow-mania.com/armory/?quest=9255 to be able to pick up that quest, I doubt this is bugged.

**Comment by Felfyre** [comment]
Ahh, that's why I couldn't get it, myself and a couple of others where
having issues with apprentice mirveda. We couldn't speak to her... I will
check later today if that's changed thank you fir the time
