### ISSUE TITLE
[Quest] Rescue 00X-17/TN

### ISSUE THREAD

**Issue by dothie** [WoWManiaUK/Redemption#3167]
**Links:**http://www.wow-mania.com/armory/?quest=648

When you accept the quest nothing happens.
He should start walking and you need to protect him. Till he reached the Caverns of Time

Now when you accept the quest he will talk to you but dont move, nothing happens. The quest is not to complete.

![image](https://user-images.githubusercontent.com/26550083/55436290-2ecda900-559c-11e9-9587-663a37d6dd09.png)

**What is Happening:**

**What Should happen:**

**Comment by wow-mania** [comment]
![image](https://user-images.githubusercontent.com/12248683/55463904-e3de8080-55f1-11e9-90fc-f883a0bc37a4.png)
Works just fine.
![image](https://user-images.githubusercontent.com/12248683/55464326-c6f67d00-55f2-11e9-88b3-d9143b20a683.png)

Please read requirements and necessary pre-quests.
While it is nice that you take the time to log an issue if you don't do the research first and check to see if you are not mistaken you will waste developers and testers time that could be used to fix a real issue.
