### ISSUE TITLE
Memory access error when logging on to Worg or Goblin

### ISSUE THREAD

**Issue by tomoswald2** [WoWManiaUK/Redemption#3169]
**Links:**

**What is Happening:**
When logging on to a Worg or Goblin character I get the following running client 2.5 on the PC.  Then the games exits.

    ERROR #132 (0x85100084) Fatal Exception
    Access_Violation at 0023:005BE395

    Instruction at "0x00tBE95" referenced memory at "x0000000C"
    Memory could not be "read".

**What Should happen:**
Login should be successful as it is with all other races.

**Comment by Kitzunu** [comment]
That is corrupted patches, not a server issue.

Just download and replace your patches from http://wow-mania.com/downloads
