### ISSUE TITLE
Reins of the Black War Bear error

### ISSUE THREAD

**Issue by panton116** [WoWManiaUK/Redemption#3171]
**Links:**
http://www.wow-mania.com/armory/?item=44224

**What is Happening:** my character name is Panton. At level 20, I joined a Stormwind raid, also raided the other cities. Then got the Achievement For the Horde and receive the Reins of the Black War Bear (http://www.wow-mania.com/armory/?item=44224) via mail box. Then when I get to level 40 and learn Journeyman Riding, I tried to use the item but it said "No Charges Remain". Same thing happen to my wife's Character Phoebee.

**What Should happen:** I should be able to add the mount to my collection after using it's item.

**Comment by wow-mania** [comment]
As-is Item fucntions as it should.
You shouldn't be doing the achieve at level 20. This may have caused the issue. Thesy should be used as you get them. Did you take them from mail straight away or waited a month? :)
I will send you the item anyways.

**Comment by wow-mania** [comment]
Sent to Phoebee. Let me know your char name.

**Comment by Echinaceax** [comment]
@wow-mania 

> my character name is Panton
