### ISSUE TITLE
[Mount] Reins of the  Black War Bear

### ISSUE THREAD

**Issue by gamer100** [WoWManiaUK/Redemption#3172]
http://www.wow-mania.com/armory/?item=44224

http://www.wow-mania.com/armory/?achievement=619

When they want to learn it at level 40 It give the message "no charges remainining"
They have done the archievement for the horde before level 40.
And stored it in the bank till they could use it.
When the item is removed  from bag  and replaced  it works

**Comment by wow-mania** [comment]
Works fine.
If you have done the achievement and you were not even 40 and stored the item it is too bad.
Achiev and conditions go together.
I tried the item and it works just fine.
