### ISSUE TITLE
ICC ID

### ISSUE THREAD

**Issue by Moskwich** [WoWManiaUK/Redemption#3173]
Charr Kamu Exp Wotlk
**What is Happening:**

Got ICC 10 ID 4 no reason.
**What Should happen:**

Shoud be raiding ICC 10 with my guild

**Comment by Kitzunu** [comment]
Please read how to properly report an issue
https://github.com/WoWManiaUK/Redemption/blob/master/CONTRIBUTING.md

**Comment by Dranah** [comment]
Unless it is happening to multiple people, it is most likely a character issue. Which does not belong to github. You may need to make a ticket in game.

**Comment by Moskwich** [comment]
its not, my guild mate wich was in the same group got it 2, Roudy. They sed
2 meke it here WTF is this?
