### ISSUE TITLE
In-game calendar offset by an hour

### ISSUE THREAD

**Issue by cooperonie** [WoWManiaUK/Redemption#3175]
Hello,

**What is Happening:**
Since about a week ago every event created in the guild calendar is offset by +1 hour.
I create an event at 20:00 hit save and the event shows as 21:00.

**What Should happen:**
If i create an event at 20:00 it should save at 20:00.

It might be related to daylight saving time but it should save the number i put in the calendar not change it +1..

Thank you

**Comment by wow-mania** [comment]
check your local and server clock and change it appropriately
![image](https://user-images.githubusercontent.com/12248683/55780686-75416d00-5aa0-11e9-8402-7ed5af7dcc93.png)
