### ISSUE TITLE
Kirgaraak bug

### ISSUE THREAD

**Issue by cooperonie** [WoWManiaUK/Redemption#3176]
**Links:**
In burnnhildar village, there's a quest "The warm-up" where you need to kill a big chained up yeti looking mob "Kirgaraak" while on a quest provided mount.

**What is Happening:**
If you kill the monster while on the special mount, the quest does not succeed, however, if you jump off the mount after engaging him and kill him with your normal abilities the quest succeeds.

**What Should happen:**
If you kill him while on the special mount, it should succeed.

**Comment by wow-mania** [comment]
Work as it should.
![image](https://user-images.githubusercontent.com/12248683/55781617-81c6c500-5aa2-11e9-958d-7595b1643cd7.png)
