### ISSUE TITLE
Fel Reaver in Hellfire Peninsula

### ISSUE THREAD

**Issue by volkangul** [WoWManiaUK/Redemption#3177]
Greetings,

Fel Reaver removes stealth when you hover him around 25-30yards. No agroo , no damage taken and no frontal approach ( 180 degree ).

**Comment by TheManiax** [comment]
https://www.wowhead.com/npc=18733/fel-reaver
Has nothing to do with "hovering"
He is casting an earth-quake-like spell which is not being logged in combat log
But yes, it will remove your stealth if you be in the area of effect

**Comment by TheManiax** [comment]
Sounds like it's the fel reaver pre-agro that is removing your stealth
https://www.wowhead.com/sound=9417/felreaverpreaggro
I'm not confirming this as a bug
It's as intended in my opinion
