### ISSUE TITLE
Quest - The Plains of Nasam

### ISSUE THREAD

**Issue by volkangul** [WoWManiaUK/Redemption#3178]
**Links:**
https://www.wowhead.com/quest=11652/the-plains-of-nasam

**What is Happening:**
Tank abilities uses mana as intented but it's mana draines eventually. You need to go back and Leave Vehicle then jump in to a new one in order to complete quest. Also Lich attacks deals damage to player not to Tank.

**What Should happen:**
All incoming damage should go to tank's hp not the player. Tank should not be getting out of mana.

**Comment by wow-mania** [comment]
Of course it should. :)
