### ISSUE TITLE
[Item] Arcanite Dragonling - ID 16022 Not attacking/moving

### ISSUE THREAD

**Issue by Drostthehunter** [WoWManiaUK/Redemption#3179]
**Links:**
https://www.wowhead.com/item=16022/arcanite-dragonling
https://www.youtube.com/watch?v=SxcgVWW1WJw

**What is Happening:**

This is a very exclusive pet (trinket) you can get while you are having the engineering and using the https://www.wowhead.com/item=48933/wormhole-generator-northrend, usually there are 5 options on the wormhole generator but there is a very small chance youll get extra option called as "Underground" where you can find secret vendor selling this Dragonling.
Dragonling is not attacking or even casting debuff which is the reason someone wants to farm it, he is supposed to cast a stackable debuff on the enemy target increasing fire dmg the NPC is receiving. Here on the screenshot you can see that once in a combat he is not moving/attacking 
![Screenshot_42](https://user-images.githubusercontent.com/43518434/55881924-dc941580-5ba3-11e9-8cad-545f8b47b6f1.png)

The pet was not summoned by me, it was summoned by the Ezzdeath and you can see he is showing as a friendly NPC to me even tho i should be able to attack him.
The same issue is happening with 2 other dragons summoned by the trinkets, shown on the screenshot but only Arcanite Dragonling is able to cast fire debuff. 

![Screenshot_41](https://user-images.githubusercontent.com/43518434/55882148-4dd3c880-5ba4-11e9-956e-cdb0f5945f50.png)
![Screenshot_40](https://user-images.githubusercontent.com/43518434/55882152-50362280-5ba4-11e9-9d79-f3a41eaa6cdb.png)

**What Should happen:**

I will send a video of how this specific pet ( trinket ) should behave in combat while adding the fire debuff to the target. 
https://www.youtube.com/watch?v=SxcgVWW1WJw

**Comment by TheManiax** [comment]
Any link to the spell ID that is missing? @Drostthehunter

**Comment by wow-mania** [comment]
it's all there. I doubt this is valid.

**Comment by Drostthehunter** [comment]
I couldnt find the link to the spell anywhere on forums/wowhead or any other related site.

**Comment by TheManiax** [comment]
It is valid as the video proves
But since there is not enough info, we can't do anything
I will leave the report open for now to see if any one can find any proper info

**Comment by Keader** [comment]
Try now.

**Comment by TheManiax** [comment]
Still doesn't attack nor casts the flame buffet (unknown ID)

**Comment by Keader** [comment]
@TheManiax tested again and working fine in PTR.

**Comment by Keader** [comment]
![image](https://user-images.githubusercontent.com/7120913/56035533-d10a3100-5d00-11e9-8d6b-6feef05b8753.png)
I tested on Red now, and is working too.
Wtf Nima? '-'

**Comment by GreatPsycho12** [comment]
hey man did you find a way to force this dragon to attack ?
