### ISSUE TITLE
[NPC] Siegesmith Stronghoof -31106- Wintergrasp

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Redemption#3181]
**Links:**
npc - https://www.wowhead.com/npc=31106/siegesmith-stronghoof
quest - https://www.wowhead.com/quest=13191/fueling-the-demolishers

![siegesmith stronghoof](https://user-images.githubusercontent.com/39439201/55904450-2561c380-5bd0-11e9-8b9d-912e84bc8175.jpg)

![returning quest](https://user-images.githubusercontent.com/39439201/55904454-285cb400-5bd0-11e9-8873-8da826ad40b9.jpg)
Ive been meaning to check on this for a while, but then got busy with something else.

**What is Happening:**
- When Horde is going WG for the weekly quest we can give all quests back except one 
- Then NPC is here at "the chilled quagmire, but cant return quest 

**What Should happen:**

- Should have quest back :)

**Comment by Echinaceax** [comment]
Ally is the same - so im guessing its meant to be like that for some reason 

![ally npc](https://user-images.githubusercontent.com/39439201/55908506-ea648d80-5bd9-11e9-9d52-c63935a86a0f.jpg)

**Comment by WhitephoenixTheBunny** [comment]
So far I know, you should turn that quest when WG is controlled by your faction, inside the forteress, not on the camps.

**Comment by WhitephoenixTheBunny** [comment]
![image](https://user-images.githubusercontent.com/31921098/55941698-a5bd0e80-5c3a-11e9-8f1b-b0fbb2eb40da.png)

**Comment by WhitephoenixTheBunny** [comment]
@wow-mania remove fix on NPC.
Is the quest showing wrongly on the map
