### ISSUE TITLE
[CLIENT] Tamed Northrend spirit beasts permanently smaller in size

### ISSUE THREAD

**Issue by Tyrandiel** [WoWManiaUK/Redemption#3186]
Since a few days all of the four Northrend spirit beasts tamed with my beast mastery hunter Tyrandiel are less than half the size they used to be. The problem occured without any ado during a "normal" time of flying around, occasionally dismounting, doing quests, etc. The problem is permanent. Interestingly, the fifth pet, a "normal" wolf, is of normal size. Can you please have a look into this issue?
Thank you in advance.
![Northrend_Spirit_Beast_half_size](https://user-images.githubusercontent.com/49534228/55983637-d719f680-5c9b-11e9-8bfb-452749601dd2.JPG)

**Comment by wow-mania** [comment]
This is fixed in dev but will need client update.
