### ISSUE TITLE
"Disarmed!" quest turn in seemed to subtract 3000 rep

### ISSUE THREAD

**Issue by Boobarnes** [WoWManiaUK/Redemption#3188]
**Links:**
Here's the armory link to the daily Disarmed! quest: http://www.wow-mania.com/armory/?quest=13836

**What is Happening:**
The screen showed I ***lost*** 3000 Kirin Tor for turning it in. (I'm already Exalted with Kirin Tor.) That didn't actually happen, but I want to report it in case it actually does start to happen. This happened 13-4-19. Screenshot showing the blue message and including server time and toon name is attached. (I ran the same quest on all my 80s, most of them Exalted with Kirin Tor, but I didn't pay attention to the status message, so not sure if it happened more than once.)

**What Should happen:**
Since I'm already Exalted, I should just get the gold reward and fishing bag with no change in rep, and certainly not a penalty.
![wow screen 13-4-19, kirin tor -3000 rep](https://user-images.githubusercontent.com/25782570/56074643-3fdc9e00-5d84-11e9-953f-ba841719a1e5.jpg)

**Comment by wow-mania** [comment]
THis has been fixed. Contact me on Discord with your char name. It is an issue in your character,
