### ISSUE TITLE
[NPC / Quest] Private Thorsen

### ISSUE THREAD

**Issue by Xman993** [WoWManiaUK/Redemption#3189]
**Links:**

![image](https://user-images.githubusercontent.com/6819293/56078255-47349380-5de6-11e9-94eb-d5fd9c5333a5.png)
http://www.wow-mania.com/armory/?npc=738

**What is Happening:**

dose not give me the quest

**What Should happen:**

need to give me the quest

**Comment by wow-mania** [comment]
please read conditions
