### ISSUE TITLE
[Quest] Stranglethorn Fever issue.

### ISSUE THREAD

**Issue by JohnDoeNN** [WoWManiaUK/Redemption#3192]
Hi, 
problem is with the quest mentioned in the topic. Related to T# 1781, 1907, 1893.
**Links:**
![image](https://user-images.githubusercontent.com/49613413/56093393-7e7b7100-5ec8-11e9-9ff5-6a6f395b7145.png)

**What is Happening:**
We're unable to talk to the NPC which should summon for us Mokk.

**What Should happen:**
After obtaining Gorilla Fang, we should speak with mentioned NPC so he could summon for us this ape.

**Comment by Kitzunu** [comment]
Looks to me that he is mid event, could this bug be like the Mirveda one @wow-mania ?
