### ISSUE TITLE
[Client] Dungeons & Raids Achievements

### ISSUE THREAD

**Issue by WhitephoenixTheBunny** [WoWManiaUK/Redemption#3194]
**What is Happening:**

Atm, on all the raids tab the 10 and 25 shows on same _section_ being messed
![image](https://user-images.githubusercontent.com/31921098/56201424-c3beb080-6038-11e9-87c9-47ca18a1ad14.png)
![image](https://user-images.githubusercontent.com/31921098/56201481-e18c1580-6038-11e9-89ab-b97e3e52bf08.png)
![image](https://user-images.githubusercontent.com/31921098/56201511-efda3180-6038-11e9-8207-563e1f6eb1a2.png)
![image](https://user-images.githubusercontent.com/31921098/56201556-084a4c00-6039-11e9-8fd1-c27369437737.png)
![image](https://user-images.githubusercontent.com/31921098/56201587-1730fe80-6039-11e9-9b63-0f1b00a50e8e.png)

Happening With:
Lich King 10 / Lich King 25
Secret of Ulduar 10 /Secret of Ulduar 25
Call of the Crusade 10 / Call of the Crusade 25
Fall of the Lich King 10 / Fall of the Lich King 25

EDIT: 
Lich King Dungeons / Lich King Heroic

**What Should happen:**

Achievments 10 and 25 should be on the specific sections

**Comment by wow-mania** [comment]
Seems to be client-side. Very minor and probably will have to wait.

**Comment by Dranah** [comment]
This makes it take awfully long to find your favorite achievements to link so you can brag.
Extremely high priority!

**Comment by Kitzunu** [comment]
Fixed, but requires client update
