### ISSUE TITLE
Shadowmourne Chest items not obtainable

### ISSUE THREAD

**Issue by Earthliving** [WoWManiaUK/Redemption#3200]
I completed the smourne chest quest but left ICC, NPCs no longer present to turn in for jaina's locket etc.

**What Should happen:**
The NPCs should be there if the quest has been completed.

**Comment by Keader** [comment]
They are present in first floor of ICC, after Lich King die.
You need kill LK, and go to first floor to finish quest.

**Comment by kondoekoe** [comment]
I have exactly the same issue. I still have the locket and there is no NPC. i've been told  by others that i can steal someone else's quest and that this is the reason it never worked for me, someone took my jaina turn in to do it themselves. I tried reporting this but had an issue with filing the report. I have all the other quests turned in, so im sure i wasnt at the wrong place at the wrong time. I saw jaina, but while turning in the others items she vanished. I didnt look around to see if anyone else turned it in. Hope u can look into this again. 

With regards,

Bizon
