### ISSUE TITLE
[Klaven's Tower]

### ISSUE THREAD

**Issue by elodiejane** [WoWManiaUK/Redemption#3201]
**Links:**

**What is Happening:** I can kill the zombie/drone with the spiked head but he does not drop the key needed to complete the quest. I can lockpick the Duskwood Chest at the top of the tower and get the needed Journal but without the key I can't finish and go on.

**What Should happen:** The zombie/drone with the spiked head should drop the Defias Tower Key needed to complete the quest.

**Comment by gamer100** [comment]
Player got the  buf Touch of Zanzil  could not pickpocket cause of that ,

**Comment by Kitzunu** [comment]
You need to pickpocket the key from http://wow-mania.com/armory/?npc=7051
If you have the Touch of Zanzil buff, you need to complete that quest chain first
