### ISSUE TITLE
[Client] Visual bug with Set Bonuses after Transmogrification

### ISSUE THREAD

**Issue by GMWeeble** [WoWManiaUK/Redemption#3202]
**Links:**
[Here I have all my gear all normal not transmoged with the hands not a part of the set items.](https://gyazo.com/b6242d1fdb9f6c2c955f25ff5315e64f)

[Here I transmoged my head to another item but it is still equiped](https://gyazo.com/e214ff2ec4bd19a3f163f1c8b5e62c6a)

**What is Happening:**
When you transmog set items the specific item of the set will remove that item from the set bonus list making a visual bug that you no longer have the set bonus active.

**What Should happen:**
The set bonus should be active at all time even if setbonus items gets transmoged.

This is just a visual but no impact on the game, but a few players do get confused.

**Comment by wow-mania** [comment]
As-is. Any loss of bonus is just visual.
