### ISSUE TITLE
[Quest] Tails Up

### ISSUE THREAD

**Issue by Kitzunu** [WoWManiaUK/Redemption#3204]
http://www.wowhead.com/quest=13549/tails-up#comments

**How it works:**
Darting any Icepaw Bear or Frost Leopard makes it become friendly and it continues to walk around.
Then after talking with it, if it is a male it becomes neutral and goes to sleep, if it is a female it becomes neutral and stands still.

**How it should work:**
Darting any Icepaw Bear or Frost Leopard should put it to sleep and it will become neutral.
After talking with it, if it is a male, it should wake up, becomes hostile and attack you, if it is a female it should wake up and become friendly and follow you for 5 minutes.

**Comment by IvanLlanas** [comment]
After darting a leopard, you can get a dialog qith an option: "Lift the leopard's tail to check if it's a male or a female.", clicking the options does nothing. The quest can't be completed.
The bears' dialog does not even show the option.
