### ISSUE TITLE
[Spell] Hunger For Blood

### ISSUE THREAD

**Issue by pungkanana** [WoWManiaUK/Redemption#3205]
**Links:**

**What is Happening:**
Not working it doesn't cast at all 

**What Should happen:**

**Comment by Kitzunu** [comment]
I really appreciate that you take time to report issues, but at the same time it made me laugh.
You have given barely any info here mate.

Please read the "How to Properly Report an Issue" or "CONTRIBUTING.MD" 

What you are missing is: 
Link to the spell
Explination of what should happen / how it should work.

**Comment by Kitzunu** [comment]
Spell: http://wow-mania.com/armory/?spell=51662
Talent: http://wow-mania.com/armory/?spell=51662
Glyph: http://wow-mania.com/armory/?item=45761

**Comment by Keader** [comment]
Working fine.
Target need has some Bleed Effect to it work.

**Comment by volkangul** [comment]
As an Assasination Rogue raiding 4 days in a week, i can confirm spell working properly. The thing is you need a bleed effect on your enemy target in order to "cast" spell to be active.
