### ISSUE TITLE
[Quest] A Pawn on the Eternal Board

### ISSUE THREAD

**Issue by Clearlygnome** [WoWManiaUK/Redemption#3207]
http://www.wow-mania.com/armory/?quest=8519

Role play goes through to the end, you kill the adds, RP continues, but the quest didn't complete.

Made tickets with GM, was completed manually.

I was using up to date patch and launched using launcher.

**Comment by Kitzunu** [comment]
Please follow the Template made to log issues.
You can also read CONTRIBUTION.MD for extra help.

Thank you for taking the time to log the issue, it will be looked into

**Comment by wow-mania** [comment]
Works just fine.
![image](https://user-images.githubusercontent.com/12248683/56798670-2705cb00-680f-11e9-8a3d-9b5bef9c10b8.png)
You don't have to do anything. Just watch and stay close.

**Comment by Echinaceax** [comment]
Tested this for GM psygoa 

**Whats happening** 
no quest credit given 

- [ ] NPC doesnt say his last gossip text 
he should quest reward on "and now you know all there is to know. mortal" and that text line is missing 
- [ ]  Dragons are clipping ground

No quest complete quest text 
timestamp 4:24 https://i.gyazo.com/34b340c19b7ddd2b036bf21f40dd9846.mp4

Bad dragon ground clipping 
https://i.gyazo.com/3a1dd91a7c630e8ca704a7fb8aa835e6.mp4

NPC tell players to "stay close" lol and when they do they move from quest credit spot 😄 

![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/084554f8-d59f-49fc-a65c-bf28387b0872)

NOTE: quest credit given at wrong place 
https://i.gyazo.com/a41feb310dedee2e02f07c78bfa70e27.mp4


**What should happen**
- Dragons should not clip ground 
- Quest credit needs to be given near the NPC after adding the last gossip text 
"and now you know all there is to know. mortal"

**Comment by Lumber-Jack-2** [comment]
ground clipping cannot be fixed here, else they will not fly away sadly

reduced the quest reward range to 50 yards instead of 600 yards

**Comment by Echinaceax** [comment]
fixed in PTR 
quest credit at correct distance https://i.gyazo.com/40c36c8114489692cd93976d3eabe78a.mp4
