### ISSUE TITLE
[Quests] "Among the Champions" and "The Grand Melee"

### ISSUE THREAD

**Issue by MeanieUK** [WoWManiaUK/Redemption#3208]
When a fight against an NPC is complete the NPC returns to its starting (holding) position and no Mark of the Valiant or Mark of the Crusader is given.

I tried clearing the cache, no UI and obviously relogging, nothing worked

**Comment by zerocooled** [comment]
same issue

**Comment by WhitephoenixTheBunny** [comment]
I have tested on Redemption, Draenei char, only got the first one, fighting Stormwind on the "the Grand Melee"

**Comment by WhitephoenixTheBunny** [comment]
Guys, horde or alliance?

**Comment by WhitephoenixTheBunny** [comment]
**Among the Champions** 
_Alliance_ 
http://www.wow-mania.com/armory/?quest=13790
http://www.wow-mania.com/armory/?quest=13793
_Horde_
http://www.wow-mania.com/armory/?quest=13811
http://www.wow-mania.com/armory/?quest=13814

**The Grand Melee**
_Alliance_
http://www.wow-mania.com/armory/?quest=13665
http://www.wow-mania.com/armory/?quest=13745
http://www.wow-mania.com/armory/?quest=13750
http://www.wow-mania.com/armory/?quest=13756
http://www.wow-mania.com/armory/?quest=13761

_Horde_
http://www.wow-mania.com/armory/?quest=13767
http://www.wow-mania.com/armory/?quest=13772
http://www.wow-mania.com/armory/?quest=13777
http://www.wow-mania.com/armory/?quest=13782
http://www.wow-mania.com/armory/?quest=13787

**Comment by wow-mania** [comment]
What exactly is the issue? There is absolutely no code checking the health of char or mount.

**Comment by MeanieUK** [comment]
i'd post a video but at these impossible sizes i cant really, suffice to say, when winning a duel with an npc you do not get credit

**Comment by MeanieUK** [comment]
put it on google, [https://drive.google.com/open?id=1Erd5j3AyPXiwmaGPTmVStjUsFAV3HSzU](url)

**Comment by Kitzunu** [comment]
I just tested it, I doubt it has anything to do with HP as I managed to get aMark of the Valient when I was very close to death.

BUT I think I have found the issue:

Everytime you kill the opponent with Charge (http://wow-mania.com/armory/?spell=62960) you DO NOT get quest credit.

**Comment by WhitephoenixTheBunny** [comment]
I was to recheck today :P

**Comment by Dusticles** [comment]
Remember, checks and fixes arent applied instantly to the server but possibly in the next server restart or even when a bundle of fixes are done in the near future, submitting them all at once.
