### ISSUE TITLE
[Quest] Post-partum Aggression

### ISSUE THREAD

**Issue by volkangul** [WoWManiaUK/Redemption#3211]
![WoWScrnShot_042619_011346](https://user-images.githubusercontent.com/49440467/56771921-ce0f4600-67c0-11e9-83ad-7295ff3311a7.jpg)

Quest is not ending when the object slain...

**Comment by Kitzunu** [comment]
Please follow the Template made to log issues.
You can also read CONTRIBUTION.MD for extra help.

Thank you for taking the time to log the issue, it will be looked into

**Comment by wow-mania** [comment]
Works
![image](https://user-images.githubusercontent.com/12248683/56796471-801f3000-680a-11e9-93ce-71faa738a7c2.png)
