### ISSUE TITLE
Quest Betrayal

### ISSUE THREAD

**Issue by Tawana-wowmania** [WoWManiaUK/Redemption#3212]
**Links:**

**What is Happening:**

I talk to Drakuru and get teleported to the roof. There is mean't to be mobs up there and Drakuru as well but there is only a portal labeled Drakuru's last wish. This takes you down to Zul'drak
**What Should happen:**
Drakuru should be there as well as some mobs that you can use to fight drakuru and when he is dead you are meant to get his skull. The quest has been broken since the recent update.

**Comment by wow-mania** [comment]
Works.
