### ISSUE TITLE
[NPC] Exodar Valiant

### ISSUE THREAD

**Issue by Kitzunu** [WoWManiaUK/Redemption#3213]
Made http://wow-mania.com/armory/?npc=33566 sit instead of stand

![image](https://user-images.githubusercontent.com/24550914/56849303-0e6ee100-68f3-11e9-854a-cf5bc8c42f36.png)

**Comment by wow-mania** [comment]
Minor and it can't be fixed for now. Some issue in client maybe.

**Comment by Rushor** [comment]
https://i.imgur.com/Nc5i6j8.jpg

this was actually fixed
