### ISSUE TITLE
[PvP] Occurrence in towns and cities

### ISSUE THREAD

**Issue by Dusticles** [WoWManiaUK/Redemption#3214]
**Links**
https://www.youtube.com/watch?v=RYYXcHuotj8

**What is happening**
From what I've seen, Stormwind City is not reporting to its local defense chat everyone has when joining a city limits that Stomwind is Under Attack! In yellow letters across every inhabitant of Stormwind everytime something is attacked by the opposing faction. This isn't occuring at all within the world from multiple examples of attacks in various locations. Its to prompt pvpers to be alert and find this threat wherever it may be... but sadly not going off so people never know until somone says something in world chat.

**What should happen**
In game alert (in yellow text) Is to prompt pvpers to be alert and find this threat wherever it may be... 

note: Youtube link proof that this was the case in Wrath in 2008

**Comment by Kitzunu** [comment]
Please follow the Template made to log issues.
You can also read CONTRIBUTION.MD for extra help.

Thank you for taking the time to log the issue, it will be looked into

**Comment by WhitephoenixTheBunny** [comment]
So far, just tested Stormwind. 
I will check other main cities

**Comment by WhitephoenixTheBunny** [comment]
Me and Echi retested:

What tigger a warn:

Exodar : king and guards
Stormwind: nothing
Darnassus: guards
Ironforge: guards

Orgrimmar: nothing
Thunder Bluff: guards
Undercity: guards
Silvermoon: nothing

All pop under attack after death

**Comment by Keader** [comment]
Remember: only trigger message when guards die.
Not when it enter in combat.

**Comment by WhitephoenixTheBunny** [comment]
Leaders does not tigger, but guards does...
