### ISSUE TITLE
[Spell] Mixology

### ISSUE THREAD

**Issue by Kurioss** [WoWManiaUK/Redemption#3215]
**Links:**
https://www.wowhead.com/spell=53042/mixology#comments

The flask duration is increased by 1 hour from the "Mixology" buff, but does not get an increased effect as mentioned in the buff. Example Frost Wyrm gives 125 spell power when its suppose to give 162 SP instead. The effect is supposed to be increased by 29%. Same for Endless rage, Stone blood and Pure Mojo.

Flask of Stoneblood 650 HP => 970 HP = +320 HP = ~+49%
Flask of Endless Rage 180 AP => 244 AP = +64 AP = ~+35%
Flask of Pure Mojo 38 MP/5 => 51 MP/5 = +13 MP/5 = ~+35%
Flask of the Frost Wyrm 125 SP => 162 SP = +37 SP = ~+29%

**Comment by Keader** [comment]
check status, not tooltip.

**Comment by Keader** [comment]
One more time... It Work.

My warlock without flask:

![image](https://user-images.githubusercontent.com/7120913/56896875-67f61d80-6a63-11e9-9fff-91346ce6193c.png)

With Flask:

![image](https://user-images.githubusercontent.com/7120913/56896979-ab508c00-6a63-11e9-967a-ba729ff9686f.png)

As you can see, tooltip stay in 125, but my spell power get 172 of bonus.
(2763-2591 =  172)
