### ISSUE TITLE
[NPC] Whip Lasher

### ISSUE THREAD

**Issue by Nufii** [WoWManiaUK/Redemption#3216]
**Links:**
do a dire maul east dungeon urself and u will see it

**What is Happening:**
little plant monsters the slashers hit too hard and they spawn endlesly in certain spots making so it's impossible to complete a dungeon run there and they look weird like spawning at each other and u can't tell how many are there when this happens; can u fix it pls?

**What Should happen:**
they shuld not be able to 1shot a tank and full wipe the team and everything shuld be normal

**Comment by Nufii** [comment]
u need to do it with a group by dungeon finder to replicate the bug

**Comment by Nufii** [comment]
u can't tell the difference when u can solo everything at sight solo as an endgame full character

**Comment by wow-mania** [comment]
As is. Hitting too hard is not a bug. THis is a group dungeon.

**Comment by Nufii** [comment]
what about the rest of the bugs i mentioned before?

**Comment by Nufii** [comment]
can u fix it?

**Comment by Kitzunu** [comment]
What was the "rest of the bugs" you mentioned?

**Comment by Nufii** [comment]
copy pasta from my first post

they spawn endlesly in certain spots making so it's impossible to complete a dungeon run there and they look weird like spawning at each other and u can't tell how many are there when this happens; can u fix it pls?

**Comment by Nufii** [comment]
it's the same for some tree monster mobs like there 4 or more at each other patroling and it looks, weird, buggy and u can't tell how many are there etc...

**Comment by Nufii** [comment]
everyone knows the dungeon is bugy when i asked around the server

**Comment by Nufii** [comment]
dunno how u guys missed it

**Comment by Kitzunu** [comment]
Please give me links to the NPCs that spawns weirdly and too many

Without the actual NPC name or ID there is nothing we can do

**Comment by Nufii** [comment]
u can go to the dungeon like i did with a group

**Comment by Nufii** [comment]
and see it urself

**Comment by Nufii** [comment]
i am the only player from the server to take my precious time to post a bug here so this is the best link i can give u https://www.wowhead.com/dire-maul#npcs

if no one cares to even check the dungeon themselves in live then there is nothing i can do

**Comment by Echinaceax** [comment]
@Nufii i see you are really trying to explain but in order for Devs to fix you "must" supply NPC link that your are describing, there are 111 NPC is that dungeon :)

the more info you give the quicker it can be fixed.

**Comment by Nufii** [comment]
played it once don't know their name only how they look like

ask a gm to go to the dungeon to see it; if he is a veteran he will spot the bugs at first glance

**Comment by Nufii** [comment]
bonus points if the gm knows the dungeon and played it before

**Comment by Echinaceax** [comment]
GMs are not testers , we are -  thats we are asking for npc name :)

**Comment by Dranah** [comment]
He is talking about these https://www.wowhead.com/npc=13022/whip-lasher
I don't think they are bugged, they spawn if you walk through a pod (which is a trap) and that's supposed to punish you. Don't walk on the pods.

**Comment by Nufii** [comment]
i hope u didn't miss my comments dranah

**Comment by Nufii** [comment]
spawn bug; mobs walk / look weird cos they look liek they are at each other and u can't tell their numbers

**Comment by Nufii** [comment]
imagine if the mobs are spawned at the same exact spot and they move/patrol together at the same time or even attack like that; 'cos of that u can't tell their numbers

patrolling wood mobs like treants/  tree monsters;   same for spawning slashers

**Comment by Dranah** [comment]
I don't see the issue, the mobs aren't being stacked up. You can see each of them next to each other.
![WoWScrnShot_050319_220654](https://user-images.githubusercontent.com/31132743/57162883-d7676680-6def-11e9-8494-ec81736b6d4a.jpg)

However, I found evidence that the Whip Lashers' damage is too high.
https://vanillawowdb.com/?npc=13022
As you can see the base damage is supposed to be 70-86 for these creatures, which comes down to about 40-50 damage swings past armor.
Currently, they are doing nearly 10 times higher.

**Comment by Nufii** [comment]
> As is. Hitting too hard is not a bug. THis is a group dungeon.

this wowmania guy doesn't know a thing; remove him from cases like this 'cos he was wrong

**Comment by Nufii** [comment]
dranah check the lower levels; go lower sometimes it buges out for those and the slashers

**Comment by Nufii** [comment]
btw i am glad u re here dranah u re the only hero here

rest of the guys were incompetent saying no bugs or can't help rofl

**Comment by Nufii** [comment]
check the lower levels for mob stacking it's sometimes bugy

**Comment by Nufii** [comment]
btw there are more bugs on the server but i am too lazy reporting it 'cos they are not game breaking just annoying a bit for me

**Comment by Nufii** [comment]
btw i checked the ghub with older bugreports about the same topic like i posted and they were mishandled  by incompetent fools years ago

so u shuld choose carefuly not to give rights to incompetent fools to review a bug report 'cos it gives a bad impression

**Comment by Nufii** [comment]
sorry if i was harsh but it's the truth

thx again for help dranah only u were good

just check the lower levels for mob stacking; maybe from the west or north entrance of the instance

**Comment by Dranah** [comment]
@Nufii 
1) Your report wasn't very clear. Most of the mishandling can be avoided if you provide information in a clear format, such as the one suggested in the "how to properly report an issue" section
2) Wow-mania is the owner of the server. He may not know everything about the game but that's why he has us testers to do the job. Give him a break :)
3) Lastly, github is not a chat platform, we need the reports clean and easy to look-through. That's why Kitzunu locked the thread just now and began clearing your comments.
Please try to put your thoughts into one single comment, otherwise it gets spammy. Alternatively, you can message us on discord (anyone in the test team, really), and chat there.
4) I'll take a look at the mobs on the lower level but in general, with nameplates enabled it's only a cosmetic issue. I understand it can be frustrating to newer players though.
