### ISSUE TITLE
Mutated Professor Putricide - Hit Box ( Melee Range ) (3rd Phase )

### ISSUE THREAD

**Issue by volkangul** [WoWManiaUK/Redemption#3218]
http://www.wow-mania.com/armory/?npc=36678

http://www.wow-mania.com/armory/?npc=38216

Professor Putricide ( 3 rd Phase ) Mutated his hit box.

How it works:
His hitbox pretty narrow. No hitbox problems for both Phase 1 and Phase 2. But in 3rd phase when he mutated his hitbox nearly you have to go inside him.

How it should work:

His hitbox should be enlarge like the other bosses can be hit by maxmelee range.

**Comment by Keader** [comment]
Fixed.

**Comment by volkangul** [comment]
Thank you.
