### ISSUE TITLE
Mutiny on the Mercy

### ISSUE THREAD

**Issue by Wolfdragon76** [WoWManiaUK/Redemption#3219]
**Links:**https://www.wowhead.com/quest=11527/mutiny-on-the-mercy

**What is Happening:**The mutinous sea dogs are spawning on one of the stationary boats in Scalawag Point.

**What Should Happen:**
They should be spawning on the Sister Mercy(the moving one)
This appears to be an ongoing platform issue where the mobs have been moved to make the quest possible to complete. If it can't be fixed, you may want to consider changing the quest text to point players to the boats at Scalawag point where the mobs do spawn.

**Comment by wow-mania** [comment]
As-is.
They are spawned on both. The stationary one is an alternative.
