### ISSUE TITLE
[Object] Battleground Flags

### ISSUE THREAD

**Issue by Bartok14** [WoWManiaUK/Redemption#3221]
Warsong Gultch didn't have a horde or alliance flag so there was no way to capture the flag and no way to end the game. Subsequently, Alterac Valley also once you capture the Graveyard flags, they vanish and u can't take it back.

**Comment by Darkslyy** [comment]
My whole group was having the same problem.

**Comment by Kitzunu** [comment]
Please read CONTRIBUTION.md and use the issue template when you log an issue

**Comment by WhitephoenixTheBunny** [comment]
Information I got:
3 BGS have the issue:
 - Warsong Gulch
 - Alterac Valley
 - Eye of the Storm

Issue with BGS started with the event [Children's Week] (http://www.wow-mania.com/armory/?achievements=155.163), and people can't progress with the achievment [School of Hard Knocks](http://www.wow-mania.com/armory/?achievement=1786).

Not sure if Arathi Basin have same issue.

**Comment by Echinaceax** [comment]
@WhitephoenixTheBunny - information you have gathered seems the most likely reason TBH.
i think as it is affecting "flags" i would take that AB will be also affected. 

as a none pvp'er (you have done good lol) 
thanks phoe

**Comment by Echinaceax** [comment]
@WhitephoenixTheBunny Eye of the storm i need to make new ticket then for (coz no flags there too)

**Comment by Echinaceax** [comment]
its this issues fixed now and sent in todays fixes or ?

**Comment by Echinaceax** [comment]
@wow-mania - still no flags wsg

**Comment by Kitzunu** [comment]
Flags are there.
The BG works.

However you cannot see your own faction flag. Just needs some tweaking :)

**Comment by Echinaceax** [comment]
@Kitzunu cant see opersite either we was in ally base :)

**Comment by wow-mania** [comment]
The two issues are the same open only one
