### ISSUE TITLE
[Quest] Capture a Mine

### ISSUE THREAD

**Issue by NightSeekerr** [WoWManiaUK/Redemption#3222]
http://www.wow-mania.com/armory/?quest=7122

![WoWScrnShot_042919_223723](https://user-images.githubusercontent.com/30464528/56932715-6ffa9f80-6aed-11e9-9ece-decd8926e587.jpg)

The quest requires you to capture a mine that the Stormpike does not control in Alterac Valley, but as you see in the picture above - once you capture a mine, it isn't counted for the quest.

**Comment by Kitzunu** [comment]
Please use the issue template that is made.

**Comment by Keader** [comment]
Well, this quest not work to me, even if i .quest complete 7122 hahaha
no idea wtf is going on.

**Comment by Keader** [comment]
Fixed.
