### ISSUE TITLE
Bug with the Polar bear quest in the Mall

### ISSUE THREAD

**Issue by ChaosSoldier776** [WoWManiaUK/Redemption#3226]
I accepted the quest to get the Ice bear in the mall for the death run. I completed the death run and the person to return the quest was not there. A GM then ported me to him in order to fix it, but the entirety of the mall had dissappeared. The mall, all NPCs, I could not interact with anything but the floor I stood on and the GM could not return me to normal. He had to Finnish the quest for me and give me my bear. I had to hearth in order to fix the bug

**Comment by Kitzunu** [comment]
Just relog and delete the cache folder.

Nothing to be done, GMs can kill and respawn Delroy
