### ISSUE TITLE
Wintergrasp Mark of Honor not attributed if dead when match ends.

### ISSUE THREAD

**Issue by Ahedonia** [WoWManiaUK/Redemption#3228]
**Links:**
link 1    https://imgur.com/a/JxN34Ar
link 2    https://imgur.com/a/KOrfz0G
link 3    https://imgur.com/a/DRaKOuE

**What is Happening:**

Ever since I started playing on this server I noticed that, in Wintergrasp, if I happen to be dead (waiting for rez at spirit healer) when match ends (either by timer end or fortress capture) I don't receive any Wintergrasp Mark of Honor, be it a win (3 marks) or a loose (1 mark). I only receive the WoW-Mania's PvP tokens  (3 or 1).
Finally made a ticket on 28/4/2019 after it happened again on a rare Ally win, so I miss 3 Wintergrasp marks. Took screenshot on [link 1](https://imgur.com/a/JxN34Ar); shared this screenshot with GM Divigrac and he asked me to exit game and clear cache, which I did. I'm also on last patch. On next Wintergrasp match I wasn't able to get killed at timer end, but GM said he tested and was dead, and he received marks. Don't know how he "died" so I don't know if it makes a difference, but when I'm dead at match end its always player killed, or vehicle killed, never mob or "suicide".
Yesterday, May 1st, it happened again, and this time I made the experiment of being in Wintergrasp with 2 accounts at same time.
[Link2](https://imgur.com/a/KOrfz0G) screenshot shows that I didn't receive Wintergrasp mark, in ghost form. I had Full rank before match ended.
[Link 3](https://imgur.com/a/DRaKOuE) screenshot shows the same char from link 1, with NO rank at all, but alive at match end, receiving the Wintergrasp Mark.
Also, for this last occurrence, I turned off the load "out of date" addons option.

**Comment by Ahedonia** [comment]
This seems to be an old issue since i found 
https://github.com/WoWManiaUK/Redemption/issues/1450
from 2017 that didn't get a response and was just closed?

**Comment by wow-mania** [comment]
I will try to improve this but it may be one of those things that you just have to live with. i.e. dead man don't get medals. :)

**Comment by Ahedonia** [comment]
So, in other words, play for for 30 minutes and get nothing for it? Doesn't sound humorous to me, especially trying to pvp gear Ally chars, ie, Horde wins 98% of the time. Hope this gets proper attention, since it's a fundamental MMO drive, get rewards for the time you put in.

**Comment by Kitzunu** [comment]
@Ahedonia What is being said here is that it might not be possible to fix it to a hundred percent.
But we always try to fix everything to the best possible state
