### ISSUE TITLE
[Achievement] Undying

### ISSUE THREAD

**Issue by manahansf** [WoWManiaUK/Redemption#3229]
**Links:**

**What is Happening:**
Our PSA guild run for the Undying Achievement on 5/2/19 at 4ST (raid ID 832) was completed and met the requirements of the achievement (no deaths during boss encounters during a single lockout period) however we did not get the achievement after we down the final boss.

I created a ticket and GM Divigrac responded.  He said he took screen shots of our 10 man group and passed the information on to Metaxa.  He also had me update my ticket to include the 10 players in the raid, which I did.  Additionally, he sent me an in-game mail asking to record ticket here.

**What Should happen:**
Should have received achievement.

**Comment by wow-mania** [comment]
pretty sure it works.

**Comment by WhitephoenixTheBunny** [comment]
Any Hunter on the party?

**Comment by wow-mania** [comment]
Have we confirmed this?

**Comment by Keader** [comment]
![image](https://user-images.githubusercontent.com/7120913/57225897-034b3d80-6fe4-11e9-9320-eb0ba793b185.png)

I wonder why we have testers, if they dont test... 😡
