### ISSUE TITLE
Projectile tracking on vehicles visual bug.

### ISSUE THREAD

**Issue by Talarok** [WoWManiaUK/Redemption#3230]
**Links:**
![Do a barrel roll](https://user-images.githubusercontent.com/48861986/57087089-5152ff00-6ccd-11e9-83ae-38f85fc7a6e3.png)

**What is Happening:**
Projectiles visually fire off in wrong direction. (I'm aiming at the tower doing damage in the screenshot. The damage applies to where you're aiming still. So np there.

**What Should happen:**
Projectiles fire visually in the direction they are aimed.

**Comment by Keader** [comment]
Sorry, cant be fixed right now.
Missing spell system rewrite in mania :/
