### ISSUE TITLE
Horde and Alliance Symbols for World chat.

### ISSUE THREAD

**Issue by Talarok** [WoWManiaUK/Redemption#3231]
**Links:**
![image](https://user-images.githubusercontent.com/48861986/57094626-02ae6080-6cdf-11e9-9dc6-b115b8eccec7.png)

**What is Happening:**
Self explanitory

**What Should happen:**
The image :P

Sorry this isn't a bug. I'll post real bugs from now on :P

**Comment by WhitephoenixTheBunny** [comment]
If not a bug, don't use GitHun for suggestions.
Use discord and forum.
GM's look at suggestions
