### ISSUE TITLE
Deathknight issue

### ISSUE THREAD

**Issue by Takarashu** [WoWManiaUK/Redemption#3233]

**Comment by Takarashu** [comment]
Sorry didnt know how this works. 

I was on the last Quest on the starting area of Deathknights. The one with the big fight. The Server crashed while the fight was on going. After like an hour i logged in again and the event was gone. I completly downloaded the Client again, patched it and used the Launcher. Still no event. I as well Abandoned the quest. Nothing helped. I created a new Character, but my friend was with me doing it Parallel. I dont know if he has the same problem. He did not logg in again.

**Comment by Kitzunu** [comment]
If this is still an issue, please open a new ticket after reading CONTRIBUTING.md (How to Properly report an issue) and follow the Template made for reporting issues.
