### ISSUE TITLE
Reset Instance, not resetting the instance

### ISSUE THREAD

**Issue by Talarok** [WoWManiaUK/Redemption#3234]
**Links:**
![image](https://user-images.githubusercontent.com/48861986/57156304-a107f800-6dab-11e9-85bc-b8edb0d9b5c3.png)

**What is Happening:**
Not working when I click yes.

**What Should happen:**
My dungeon (BRD at the time) reset so I can get my irolfel for shadowforge key :P

**Comment by Kitzunu** [comment]
This issue is accurate, I have encountered it myself.

You can reset it by changing dificulty to HC then back to NM or vice versa, but the main "Reset instance" does not work on vanilla dungeons (TBC WotLK?)

**Comment by WhitephoenixTheBunny** [comment]
Some vanilla dungeons....

**Comment by wow-mania** [comment]
Are we sure this is not the correct behaviour for 3.3.5a?

**Comment by Dranah** [comment]
Sometimes it works, sometimes it doesn't. Yet to figure what makes the difference but it usually works fine while you have only cleared the trash and you aren't in a party...

![WoWScrnShot_050319_221712](https://user-images.githubusercontent.com/31132743/57163348-35487e00-6df1-11e9-97da-10264bc2cb82.jpg)
![WoWScrnShot_050319_221713](https://user-images.githubusercontent.com/31132743/57163375-3a0d3200-6df1-11e9-9850-a0511307908e.jpg)

**Comment by Kitzunu** [comment]
@wow-mania it is not working as intended atm

**Comment by wow-mania** [comment]
If any of the boss scrpits started that is what happens. It can happen by entering an area, killing a cetain mob wired to the boss etc.

**Comment by Talarok** [comment]
> Are we sure this is not the correct behaviour for 3.3.5a?

Did you not play warcraft before this?

![image](https://user-images.githubusercontent.com/48861986/57427141-b092a100-71f0-11e9-871f-212fd0f2b7ed.png)

The more I read you, the more I see your flaws. It's like you don't even read things. You aren't even knowledgeable of how WotLK was by your comment I'm replying on. You may be a good coder sir, but you need to shape up your listening and comprehension skills judging by my 4 or 5 times interacting with you. I'm to the point that I hope to god you don't see my github post first. I don't like disliking people and I try my best to be nice and fair to all, but when a person acts a certain way it blows my mind. Idk sorry for letting this all out, but I hope you read this and it incites a positive change in your lackluster presence in conversations. Gn guys. See ya tomorrow.

**Comment by Dranah** [comment]
@Talarok Your observations are correct, Janitor is too busy to read all that we write. Instead, he cherry picks a few words that grasp his eyes. This can lead to miscommunication.
Nonetheless the point is that this issue (the dungeon reset) can't be helped, and you can go around it with using the difficulty-change option so it's not a tragedy.
