### ISSUE TITLE
Gate in Ring of Law BRD, closes back after boss encounter after so long.

### ISSUE THREAD

**Issue by Talarok** [WoWManiaUK/Redemption#3235]
**Links:**
![image](https://user-images.githubusercontent.com/48861986/57156583-53d85600-6dac-11e9-850f-8b48f52441fd.png)

**What is Happening:**
Gate closed when it shouldn't be.

**What Should happen:**
Gate stay open after successful boss encounter.

**Comment by Kitzunu** [comment]
Please follow the Template made to log issues.
You can also read CONTRIBUTION.MD for extra help.

Thank you for taking the time to log the issue, it will be looked into

**Comment by Kitzunu** [comment]
You are not given me any information here.

Which gate?
Where?
Which boss?

I will close the issue until more information that can be used is added
