### ISSUE TITLE
Missing spawn points in Storm Peaks.

### ISSUE THREAD

**Issue by Talarok** [WoWManiaUK/Redemption#3236]
**Links:**
![image](https://user-images.githubusercontent.com/48861986/57170362-6073a300-6dda-11e9-94d3-68ac72e6315e.png)

**What is Happening:**
Missing two spawn points for http://www.wow-mania.com/armory/?npc=30160 (Brittle Revenants)

**What Should happen:**
The points in the minimap should have http://www.wow-mania.com/armory/?npc=30160 there.

**Comment by wow-mania** [comment]
They are there
![image](https://user-images.githubusercontent.com/12248683/57175782-c1859000-6e47-11e9-945d-face13c1f343.png)
13 of them.

**Comment by Talarok** [comment]
What's that supposed to mean? All those dots, don't all spawn. Unless you fixed them all right then lol. Thought I don't know because you didn't say so. You just linked a picture from the website and said "They are there."

**Comment by Talarok** [comment]
Just went to check them again. They are still not spawning. Please don't brush this off. These npcs are for dailies and it is annoying to have less mobs to drop the essence of ice. Or just make it 100% drop rate that'd be nice.

**Comment by Talarok** [comment]
I checked even further. Only 7 of the 13 spawns are there.

**Comment by Talarok** [comment]
the top ones and the bottom ones are not there.

**Comment by Talarok** [comment]
> They are there
> ![image](https://user-images.githubusercontent.com/12248683/57175782-c1859000-6e47-11e9-945d-face13c1f343.png)
> 13 of them.

*sigh* didnt even look
