### ISSUE TITLE
[Dungeon] Mechanaar

### ISSUE THREAD

**Issue by cathyr1** [WoWManiaUK/Redemption#3238]
The inner door inside Mechanaar (heroic version) are bugged as they don´t open despite full dungeon clear. This was working in the past so the bug seems to be new.
![Mechanaar](https://user-images.githubusercontent.com/30184491/57176411-f7cb0b80-6e57-11e9-9dea-577c4c3b3c86.png)

**Comment by cathyr1** [comment]
.

**Comment by Kitzunu** [comment]
Is this issue valid?

**Comment by cathyr1** [comment]
It´s no longer valid. It worked later.
