### ISSUE TITLE
Disconnect Wing Boss (Lich King LoD)

### ISSUE THREAD

**Issue by Agarwaenlul** [WoWManiaUK/Redemption#3239]
**Links:**
https://www.twitch.tv/videos/419842875
After 2:29:27 Deathbreeze is disconeccted, reconnects and outside

**What is Happening:**
Yesterday night we were about to kill LK HC 25 man, when my game froze at 14% and i DCed.
Shortly after i logged back in, was released outside of icc.
So i rolled for Blood Surge, my BiS item and Master Looter couldn't give it to me even though i won the roll.  The raid killed LK and i wasn't eligible for loot.

This isn't an LK problem in particular, when you disconnect on Wing Bosses in general you will not be eligible to receive any loot

**What Should happen:**
Please find a way for people who disconnect to be able to receive the loot from a boss they killed.
What should happen, is when a player comes back he should be dead on the Platform of LK and not released outside.
One of the MOST important things you never want do on a boss fight, is to release your ghost and this happening automatically is unfortunate.

**Comment by wow-mania** [comment]
Git hub is to login actual issues anything specific to you is irrelevant as is comments of your feelings.
Clean up the description as per our guidelines. We will look into it.

**Comment by Agarwaenlul** [comment]
I am sorry, I was upset. Will fix it!

Best regards and love the server <3

Von meinem iPhone gesendet

**Comment by wow-mania** [comment]
If you DC you are release. That is a fact.
