### ISSUE TITLE
7 Missing spawn points.

### ISSUE THREAD

**Issue by Talarok** [WoWManiaUK/Redemption#3240]
**Links:**
![image](https://user-images.githubusercontent.com/48861986/57188358-4a91db00-6ecb-11e9-8a9b-811cb0994f20.png)
![image](https://user-images.githubusercontent.com/48861986/57188367-7dd46a00-6ecb-11e9-86a7-9e0ffdb14c93.png)

**What is Happening:**
There are seven missing spawns.

**What Should happen:**
Check for confirmation, fix it, be on your way.

**Comment by Talarok** [comment]
Very disappointed in your unprofessionalism,,,,,,,

**Comment by Talarok** [comment]
Well. I learned new info about how spawn points work. I had no idea I was posting something that was already working. I apologize  for getting heated on discord. I didn't think I said anything wrong and I felt ignored when you closed my issue both times with no info given to me. I found it rude, and rude begets rude ugh... Once again sorry for the rudeness and please be more informative. You guys request us to be super informative to you so do the same :)

**Comment by Kitzunu** [comment]
They are there.

Check ingame, not the spawn points on website

**Comment by Talarok** [comment]
lol Kitzunu funny you say that because I did and the spawn points in this game are not all there regardless of what the website says, but I was informed they were supposed to be 100% drop rate and with 7 currently spawn each spawn, that's enough for the 6 essences of ice needed for the daily quest. :)
