### ISSUE TITLE
Most caster npcs don't path properly.

### ISSUE THREAD

**Issue by Talarok** [WoWManiaUK/Redemption#3241]
**Links:**
Sry I don't have links for this one. Just my cold hard facts :P

**What is Happening:**
Caster NPCs don't allow DK's Death Grip to work on them if they are casting (the pull), some don't chase you after you LOS them (they'll stand there forever or keep their out of combat path while still targeting you waiting to cast once you're not los), and some don't even cast when they should (they just come melee lol (fine with me XD (not really...)))

**What Should happen:**
It's obvious I'd hope lol.

**Comment by wow-mania** [comment]
I need specific steps to repro.
Please don't just say "It's a fact" or "it's obvious". 
Facts are facts when proven beyond reasonable doubt and can be replicated independently. 
Nothing you gave here helps.

**Comment by Kitzunu** [comment]
I am sorry to say, but it is like Janitor says.

There are a million caster creatures in-game, without us knowing which ones don't prroperly cast, or properly move we cannot really do anything with this info.

**Comment by Talarok** [comment]
Yeah I was at work. Couldn't alter it. I was already told this was too broad. There were A LOT of caster npcs like this but I didn't document each one >.< Next time I see one I'll proper document it.

**Comment by Kitzunu** [comment]
If you find NPC's doing it, you can comment here and we will re-open :)
