### ISSUE TITLE
...... Spawn points

### ISSUE THREAD

**Issue by Talarok** [WoWManiaUK/Redemption#3242]
**Links:**
![image](https://user-images.githubusercontent.com/48861986/57193860-d167a780-6f0d-11e9-89a3-8add55c37962.png)

**What is Happening:**
This issue keeps getting brushed under the table by the one person who SHOULDN'T since they are the 
number 1.... 6 missing Brittle Revenant spawn points out of the 13 that are intended to be there, are missing and never spawn. (or not on top of the plane)

**What Should happen:**
They show up on armory so don't look there. You need to go to Storm Peaks and LOOK yourself and not be lazy....

**Comment by WhitephoenixTheBunny** [comment]
![image](https://user-images.githubusercontent.com/31921098/57194284-fd4e5180-6f3c-11e9-8b6c-72fba7fd5a99.png)
