### ISSUE TITLE
[Item/Drop] Essence of Ice

### ISSUE THREAD

**Issue by Talarok** [WoWManiaUK/Redemption#3243]
**Links:**
![image](https://user-images.githubusercontent.com/48861986/57194309-5c976c00-6f13-11e9-8b15-a3c2ff0d6556.png)
I moved my chat over to it to make it a smaller picture lol.

**What is Happening:**
Drop rate for http://www.wow-mania.com/armory/?item=42246 is not 100% from the 
http://www.wow-mania.com/armory/?npc=30160
**What Should happen:**
Drop rate should be 100% as of 3.2.2.

**Comment by Dranah** [comment]
Based on wowhead, the drop rate for this item has been increased to 100% sometime around on patch 3.2.2
Currently the drop rate is the old 50-60%ish.

**Comment by Kitzunu** [comment]
fixed
