### ISSUE TITLE
[Client/Item] A Sister's Bond

### ISSUE THREAD

**Issue by bagi84** [WoWManiaUK/Redemption#3244]
**Links:**
Item - http://www.wow-mania.com/armory/?item=150208

**What is Happening:**
I bought this transmog item in mall today but after transmoging my bow I now have the visual animations of a mage when attacking

**What Should happen:**
The item should transmog my bow to look like a sisters bond but still keep the animations of a bow 

this is whats happeing
https://youtu.be/zTSt_T_rfLk

**Comment by wow-mania** [comment]
All transmog items are as-is. It's not always possible to import the visual effects of later versions.
Sorry about that.

**Comment by WhitephoenixTheBunny** [comment]
Can't you add one from normal bow shooting?
Just to not be like a caster?

**Comment by bagi84** [comment]
not being funny but that's 100mp that I spent on a item that clearly states its a bow.... ive not tried to transmog anything weird just a bow to bow ...using an item that has been on the server a couple of months … not something new ..surly all these items should have been tested before implementing them for sale … if it cant be used as a bow transmog u should remove the item... ill more than happily return mine for a refund of my mp so I can use it for a working transmog item.
