### ISSUE TITLE
[Talent] Spirit Tap

### ISSUE THREAD

**Issue by D0nV170** [WoWManiaUK/Redemption#3245]
**Links:**

**What is Happening:**
The talent Spirit Tap is not activating after killing a mob that gives experience.

**What Should happen:**
The talent should give the buff that increases spirit when something that gives experience is killed.

**Comment by Kitzunu** [comment]
Level:
3: http://wow-mania.com/armory/?spell=15336
2: http://wow-mania.com/armory/?spell=15335
1: http://wow-mania.com/armory/?spell=15270

I do not know if the improved version is also bugged, but here it is:
2: http://wow-mania.com/armory/?spell=15338
1: http://wow-mania.com/armory/?spell=15337

**Comment by Keader** [comment]
![image](https://user-images.githubusercontent.com/7120913/57243160-c7c46980-700b-11e9-8024-4c0a207524ae.png)

Both talents working.

**Comment by D0nV170** [comment]
Maybe it fixes at level 80 but at levels 22-28 it only procs about 1/3 of the time and I have all 3 points into it so it should be every kill.
