### ISSUE TITLE
[Instance/ICC] Fixed Valithria Dreamwalker Mobs

### ISSUE THREAD

**Issue by Keader** [WoWManiaUK/Redemption#3253]
Fixed Valithria Dreamwalker mobs sometimes not starting combat with raid, and stay stoped in spawn point.

**Comment by Dranah** [comment]
This must have gone wrong. GMs report that all raid groups are stuck on the encounter now. I have no idea what was fixed here in the first place, but please revert it...

**Comment by gamer100** [comment]
When Valithria is  fully healed  she is  not  going away, she stay there  and is being attacked by mobs, so the fight not  end end there is  no chest, cause she does not  go  away, when  they  go on  to  Sindy then there  pets  running of  to  val to attack mobs

**Comment by Keader** [comment]
Removed last change.
