### ISSUE TITLE
[Quest] Paladin Quest [The Tome of Divinity](Part 6 of 8)

### ISSUE THREAD

**Issue by lukwild** [WoWManiaUK/Redemption#3259]
**Links:**

**What is Happening:**
The Quest item needed to resurrect the NPC to turn in the quest does not appear in the inventory.

**What Should happen:**
The Item [Symbol of Life] should be placed in the inventory when accepting the quest

**Comment by Kitzunu** [comment]
I really doubt this is bugged as it has been working since for ever, 

have you done a race change mid-quest line or before the quest line?

**Comment by wow-mania** [comment]
Works

**Comment by Kitzunu** [comment]
It can bug if you change race.
In that case gp to your old race's trainer

**Comment by GMZinius** [comment]
completed a check on a Human paladin tonight (coz of player tickets in the past) 
and can confirm working fine
