### ISSUE TITLE
Player shows as enemy. Same faction though.

### ISSUE THREAD

**Issue by Talarok** [WoWManiaUK/Redemption#3261]
**Links:**
![image](https://user-images.githubusercontent.com/48861986/57306903-9aca9200-70b1-11e9-924d-d1558daaea79.png)

**What is Happening:**
Coldparadise here always shows up as enemy. On different days and logins as well.

**What Should happen:**
Same faction players should always show as friendly. Maybe it's a goblin problem again XD

**Comment by Talarok** [comment]
im not Kazmael btw that's my friend fyi

**Comment by wow-mania** [comment]
There are FFA regions. Please check our custom features on the website.

**Comment by Talarok** [comment]
Can you link what you're talking about? I don't know where on the site you're talking about.

**Comment by Talarok** [comment]
I only know FFA as meaning Free for all in the loot options. If you're talking about gurubashi, nagrand, and blade's edge arenas; then yeah I know about those. Kazmael had this goblin mage showing every visual characteristic of an enemy player (even the sword shows up when hovering over) and the two locations this happened was Dalaran and Wintergrasp (in the final keep room)

**Comment by Talarok** [comment]
"He's like that every time I've ever saw him." says Kazmael.

**Comment by WhitephoenixTheBunny** [comment]
That's because you are not up to date probably
