### ISSUE TITLE
ToC 25 Faction champion loot box bug

### ISSUE THREAD

**Issue by jisub2da** [WoWManiaUK/Redemption#3264]
Our Guild ran a Toc 25 run and on the third encounter, the faction champions, we killed all the champions but the loot box did not appear and we could not progress the raid. We ended up calling a gm to fix the issue for us and he asked us to post to github. Please look into this issue please Thank you.

**Comment by Kitzunu** [comment]
Please follow the template made and please read the CONTRIBUTING.md or How to Properly Report an issue.

**Comment by wow-mania** [comment]
Need more info on this.

**Comment by WhitephoenixTheBunny** [comment]
I have tested, couldn't reproduce issue.
