### ISSUE TITLE
[Instance] Black Morass - Caverns of Time

### ISSUE THREAD

**Issue by Bartok14** [WoWManiaUK/Redemption#3265]
Ok there is a script error with this instance. The main problem is that it takes way too long for the portals to spawn. The way it is supposed to work is that the portals spawn fast for the regular waves, and then after a boss there is a longer break to allow for recovery. How its currently working is that for the first 7 portals they spawn at the correct rate, but after the first boss each portal takes forever to spawn as if a boss is spawning on each one. This instance takes way too long to complete, almost 40 minutes. This should not be the case. I looked but there doesn't appear to be a report about this. 

Here's a link to the instance on wowhead.
https://www.wowhead.com/the-black-morass

Here's a link to a group running this instance in 13 mins.
https://www.youtube.com/watch?v=77-BEWsV7Eg

**Comment by wow-mania** [comment]
I looked at the code an there is really nothing we can do there. It's just the natural sequence of things.
This dungeon is made for levels 60-70 and not for overgeared 80s.
It will stay as it is for now.

**Comment by Bartok14** [comment]
I understand that it's not meant to be run by a geared level 80, but if you go through the instance yourself you can clearly see a discrepancy between how fast the first 7 portals spawn and the ones that spawn after. Because there are 18 portals to close it should be similar to say The Violet Hold. The portals at the start spawn at the correct timing, but then you get a boss, which after you've defeated Blizzard would naturally want you to recover/res/eat etc. But after that, the next 6 portals should spawn at the same timing as the first seven. 

The problem with the instance is that after the first boss is killed, the other normal portals simply assume that its supposed to give the same amount of time for each portal as a boss would get. So there is actually a problem with this instance. 

If you go through the instance, time how long it takes between killing a wave of enemies and how long the next portal spawn. Then keep going through until you have killed the first boss and the wave after that, then time it. Blizzard would not have intended the later portals to take this long.

**Comment by jarvik76** [comment]
I would respectfully request if there was another look taken at this please.   It is nothing to do with gear.  This happens even when completed at level.   The issue as Bartok says is that the timing of the spawn of the portals after the first boss is incorrect.

**What is happening**
For the first 7 portals, up until and including the portal with Chrono Lord Deja, the portals spawn at about 45 second intervals.  (Correct)
For the portal after the boss (8th portal), it spawns after ~120 second gap.  This is to allow recovery after fighting boss. (Correct)
EVERY portal after the 7th now gets the ~120 second spawn interval.  (**Incorrect** - should be 45 seconds again)

**What should happen**
For the first 7 portals, up until and including the portal with Chrono Lord Deja, the portals spawn at about 45 second intervals.  (Correct)
For the portal after the boss (8th portal), it spawns after ~120 second gap.  This is to allow recovery after fighting boss. (Correct)
Thereafter, the portals **should** then spawn at 45 second intervals again until the the next boss, (13th portal) , Temporus, which should then have another 120 second interval for fighting boss.

**Comment by Rushor** [comment]
this is working correct now right?

**Comment by jeyrella** [comment]
@Rushor Ummm.  I thought this was indeed fixed even though there's no note that it was here.  Will have a run through it tomorrow to check.

**Comment by jeyrella** [comment]
Oh, I am pretty sure this was fixed under https://github.com/WoWManiaUK/Redemption/issues/3322
