### ISSUE TITLE
Battered Chest (looted during fishing)

### ISSUE THREAD

**Issue by RlyNotLazy** [WoWManiaUK/Redemption#3268]
**Links:**
https://www.wowhead.com/object=2843/battered-chest

**What is Happening:**
1. Fish up Battered Chest
2. Get excited about epic lewt
3. Open Battered Chest
4. You get **nothing** and Battered Chest disappears
5. Confusion, doubt, sadness and self loathing.
6. ** eye of the tiger track comes on **
7. CONTINUE FISHING - FUCK BATTERED CHESTS!
8. win

**What Should happen:**
Large amount of gold, custom mounts and oh who are we kidding.
Anything would be better than nothing from those Battered Chests I guess. ;-)

**Comment by wow-mania** [comment]
![image](https://user-images.githubusercontent.com/12248683/57565800-b4265380-73bb-11e9-8c3d-f4d0dd864141.png)
If you got nothing it's just life.
