### ISSUE TITLE
A Plague Upon Thee

### ISSUE THREAD

**Issue by Jaderoamer** [WoWManiaUK/Redemption#3269]
The second part of the quest A Plague Upon Thee, requires for you to place the jar of termites in the Northridge Lumber Mill in Eastern Plaguelands. When clicking on the box to complete the quest, nothing happens. I have tried to abandon the quest and re-acquire it but it does not complete.

**Comment by wow-mania** [comment]
Please check the wiki on how to login an issue.

**Comment by wow-mania** [comment]
![image](https://user-images.githubusercontent.com/12248683/57565784-5db91500-73bb-11e9-99bb-b41f7f298806.png)

![image](https://user-images.githubusercontent.com/12248683/57565786-6e698b00-73bb-11e9-9bf4-1baf0c5b457a.png)
