### ISSUE TITLE
[QUEST] Death's Challenge

### ISSUE THREAD

**Issue by crashvoncrash** [WoWManiaUK/Redemption#3270]
**Links:**

https://www.wowhead.com/quest=12733/deaths-challenge

https://www.wowhead.com/npc=28406/death-knight-initiate

**What is Happening:**

The Death Knight Initiates will not initiate a duel when the dialog box is opened and the dialog is selected to challenge them. I tried this with every Initiate I could find in the area, and the bug affected all of them. One did randomly accept the duel after trying several dozen times, but then stopped accepting challenges again after her first defeat.

**What Should happen:**
The Death Knight Initiate NPCs should begin a duel when the dialog option is selected. Upon defeating them, the player gets credit for 1 defeat. After getting credit for defeating 5, they can complete the quest.

**Comment by wow-mania** [comment]
works. specify race,

**Comment by wow-mania** [comment]
Quest works but there is an issue with the double menu.
