### ISSUE TITLE
Quest bugged - Escape through force. Blackwood den

### ISSUE THREAD

**Issue by DisgracedGod** [WoWManiaUK/Redemption#3271]
Quest - Escape through force 
Location - Blackwood den

Travel along path. 
Wave at White bear who then points in direction of cave. 
Man in cave should have a quest marker over him but doesn't. 
I have tried killing everything outside the cave first but no luck with that. 

Please see pics. 

![15575708330445746325854344915043](https://user-images.githubusercontent.com/50505089/57568540-b0f18e80-73e0-11e9-90d2-fd31f85a4750.jpg)
![15575708866114070462180894442631](https://user-images.githubusercontent.com/50505089/57568547-df6f6980-73e0-11e9-85c4-625228c72ec6.jpg)
![15575709544265016752870946321966](https://user-images.githubusercontent.com/50505089/57568555-ff9f2880-73e0-11e9-96a9-e5b45522c54b.jpg)

Raised a ticket spoken with Divigrac
Cleared cache 
Problem still persists
Asked to report on git hub. 

Cheers

**Comment by wow-mania** [comment]
What? Please use our armory for quest description and goals.
Quest works perfectly.

![Uploading image.png…]()

**Comment by DisgracedGod** [comment]
Ah, no idea why it wasn't working at the time. But glad it's working now. I did have 2 gm's look into this too at the time of raising the ticket.
And will do in future, it was first time reporting something so still learning the process. 
But thanks again.
:)
