### ISSUE TITLE
Warrior Mission The islander doesnt complete, preventing warrior to get berserker instance

### ISSUE THREAD

**Issue by GrimbleThorn** [WoWManiaUK/Redemption#3272]
**Links:**

**What is Happening:**
Warrior Mission "The islander" doesn't complete, preventing my warrior to get berserker instance.

**What Should happen:**
The mission should finish with a fight in the pit that never triggers to beggin, but it doesn't happens at all...

**Comment by GrimbleThorn** [comment]
I think I've figured out what happens. In the pit, the enemies do not respawn, enven in a 10 hour period(I've tested it yesterday, and now again) but in the pit there is only spactators, but it doesn't suppose to be that way...

**Comment by wow-mania** [comment]
Pretty sure it works and you have it all wrong. I will confirm but these sort of things take devs time when it could be researched and confirmed by the player doing a minimum of homework.

**Comment by wow-mania** [comment]
Major waste of my time.  All quests in this sequence work perfectly.
Please, next time either do your research or refrain from login issues here.

**Comment by GrimbleThorn** [comment]
https://www.wowhead.com/quest=1718/the-islander
That is the referenced quest. But at the end I should have received my berserker instance and it doesn't happen. And I am needing help to understand hou to solve this...

**Comment by WhitephoenixTheBunny** [comment]
1. Use Mania client and launcher
2. Abadon and retake quest
3. Relog and delete cache.

Those 3 steps solve like 95% of "quest issue"

**Comment by GrimbleThorn** [comment]
But the quest disappear from my quest log... There is a way to reset that
quest?


Em seg, 13 de mai de 2019 às 13:11, Phoenix <notifications@github.com>
escreveu:

**Comment by GrimbleThorn** [comment]
1. Use Mania client and launcher ....... OK
   2. Abadon and retake quest ............... NOT POSSIBLE (Quest
   disappeared from questlog)
   3. Relog and delete cache .................. *OK*

Result: My warrior is still incomplete. I tried to talk to a warrior class
trainer, in order to acquire the quest again. But it is not available to
get...

Em seg, 13 de mai de 2019 às 13:19, Anderson Luiz Oliveira de Abreu <
anderson.redranger@gmail.com> escreveu:

**Comment by WhitephoenixTheBunny** [comment]
If you abandon the request, go back quest giver and take it again

**Comment by GrimbleThorn** [comment]
Thats the issue! The quest disappear from my quest log. so I can't quite
the quest. And, in that case, the questgiver is any warrior trainer.
Talking to any questgivers(I've talk to 3 of them) the quest is not
available... So... The problem persists...

Em seg, 13 de mai de 2019 às 14:13, Phoenix <notifications@github.com>
escreveu:

**Comment by WhitephoenixTheBunny** [comment]
http://www.wow-mania.com/armory/?quest=1718

Check that link and the quests givers... Isn't _any_ they have specific ones

**Comment by GrimbleThorn** [comment]
[image: WoWScrnShot_051319_161706.jpg]
Yes. I have talked to him. thats the quests from him I got.

[image: WoWScrnShot_051319_161826.jpg]
And here, he still have no one quests for me...

Em seg, 13 de mai de 2019 às 16:06, Phoenix <notifications@github.com>
escreveu:

**Comment by GrimbleThorn** [comment]
[image: WoWScrnShot_051319_162527.jpg]
one more

Em seg, 13 de mai de 2019 às 16:19, Anderson Luiz Oliveira de Abreu <
anderson.redranger@gmail.com> escreveu:

**Comment by WhitephoenixTheBunny** [comment]
I can't see any of the screenshots.
Open a ticket ingame
Quests work fine.

**Comment by GrimbleThorn** [comment]
Can't you just reset the quest for me?
I have tried everything that you asked me to do.
But still my character with *4 days, 18 hours and 50 minutes*
seems will never ever have a berserker instance because of a bug.
See, I talked to Kelv Sternhammer
<http://www.wow-mania.com/armory/?npc=5113>, and  Wu Shen
<http://www.wow-mania.com/armory/?npc=5479>, try again and again and when I
come back to Klannoc Macleod <http://www.wow-mania.com/armory/?npc=6236>,
he doesn't finish the quest. Even with you telling me
the quests are ok. I want nothing but a berserker instance in my character.
Please man, help me to solve this problem, can't you log my character and
see for yourself?

Em seg, 13 de mai de 2019 às 16:52, Phoenix <notifications@github.com>
escreveu:

**Comment by WhitephoenixTheBunny** [comment]
The quest isn't bugged.

Open a ticket in-game, a GM will help you

**Comment by wow-mania** [comment]
There are thousands of warriors on the server
You can ask advise to them

**Comment by GrimbleThorn** [comment]
Man, thank you for your pacience and your help! The GM helped me to solve
the problem and its all ok now! Thank you again, and have a great day! You
helped a gamer to get happy! 👍


Em ter, 14 de mai de 2019 às 14:41, Janitor <notifications@github.com>
escreveu:
