### ISSUE TITLE
[Quest] The Key of Warlord Zol'Maz

### ISSUE THREAD

**Issue by IvanLlanas** [WoWManiaUK/Redemption#3276]
Quest: https://www.wowhead.com/quest=12712/the-key-of-warlord-zolmaz
Item: https://www.wowhead.com/item=39314/tiki-dervish-ceremony

The item is correctly build and a tiki can be summoned at the Warlord's gate. The Warlord charges and almost kills me. The tiki does nothing. At some point the tiki should attack and kill the Warlord but this never happens (first problem).

In addition, there's a chance after a failed try that the Warlord do not get back to his place (see screenshot) and stays there for a long time, making impossible to try again (second problem).

![WoWScrnShot_051519_021202](https://user-images.githubusercontent.com/25532326/57740216-f818a180-76b6-11e9-847e-d7bf25051646.jpg)

**Comment by wow-mania** [comment]
Why would he not go back?
And you normally fight him inside.
I have tried the quest multiple times and all worked.

**Comment by IvanLlanas** [comment]
"Why would he not go back?"
I think you missunderstand me, I meant that, sometimes, the Warlord does not go back to his place as he is meant to be.

Ok, "all worked", well, the quest works if you are able to handle a 37k elite mob, because the tiki you summon will not help you at all (as it should). I understand you can reform the quests details and not implement all the features as the official servers, the problem is that the quest is considered as normal, and such new difficulty should be tagged as "(Group)", moreover when the Warlord charges you performing multiples blows of about 1k each, leaving you in the first second of fight with just the 30% of hp.

**Comment by Dranah** [comment]
The quest may be possible to complete but it doesn't work as intended.
The player needs help from the item, which does not work.
And if you wipe, the Warlord must reset correctly.
