### ISSUE TITLE
[Dungeon][NPC] Baroness Anastari

### ISSUE THREAD

**Issue by Talarok** [WoWManiaUK/Redemption#3277]
**Links:**
![image](https://user-images.githubusercontent.com/48861986/57799858-0057f780-771e-11e9-8f2b-62f364fbe0e9.png)
http://www.wow-mania.com/armory/?npc=10436

**What is Happening:**
Boss' death not opening door to ziggaraut.

**What Should happen:**
Boss' death open door to ziggaraut to allow finishing of dungeon.

**Comment by Talarok** [comment]
![image](https://user-images.githubusercontent.com/48861986/57800556-aeb06c80-771f-11e9-9e35-e5aa45f17d48.png)
It successfully opened the second time when I entered the UD strat side. Check scripting on the Baroness upon entering from live strat side. There may be a difference.

**Comment by wow-mania** [comment]
It works correctly. You just got to the wrong one.
Each boss controls a particular door and therefore a particular way.

**Comment by WhitephoenixTheBunny** [comment]
They work fine.
