### ISSUE TITLE
Worgen cant be healed or buffed

### ISSUE THREAD

**Issue by Crymson138** [WoWManiaUK/Redemption#3278]
**Links:**

**What is Happening:**
My friend cant heal me or buff me on my worgen. It says im a invalid target
**What Should happen:**
i should be healed and buffed by anyone

**Comment by Kitzunu** [comment]
I see that you closed the issue so you probably got help or figured it out yourself.

But I will still answer for what the solution to this is if you accidentally closed it OR if someone else comes about this post.

This is a pure player side issue. This will ONLY occur when both players are not updated to the latest WoW-Mania patch.

So the solution to this is that EVERYBODY gets the Launcher.exe started to get the latest patches downloaded! This is in the hands of the players to be responsible and always start their game with the launcher.exe and NOT wow.exe

**Comment by WhitephoenixTheBunny** [comment]
I will just say one thing more:

IF they are using launcher, and say they are on last patch, they have a corrupted file and need repatch manually:
Go data -> engb, and delete patches A to E, and start launcher as admin
