### ISSUE TITLE
[Quest] A Carver and a Croaker

### ISSUE THREAD

**Issue by darkhammon** [WoWManiaUK/Redemption#3279]
**Links:**
https://www.wowhead.com/quest=11476/a-carver-and-a-croaker

**What is Happening:**
When you talk to the NPC named "Silvermoon" Harry to buy the knife, he turns in enemy and attack you.

**What Should happen:**
You talk to NPC "Silvermoon" Harry, buy the knife and can get the frog to complete the quest.

**Comment by wow-mania** [comment]
![image](https://user-images.githubusercontent.com/12248683/57982798-d8c89e00-7a41-11e9-914e-02c4615bfcd4.png)

Works fine if you have correct rep and requirements.

**Comment by wow-mania** [comment]
if not jus start fighting and he will stop.
