### ISSUE TITLE
Ethereum Prison

### ISSUE THREAD

**Issue by jarvik76** [WoWManiaUK/Redemption#3280]
What is happening:  When the **friendly** NPC is rescued from the Ethereum Prison cell, it is not casting the spell that grants reputation to the players in the group
What should happen:  A spell aligned to the NPC's faction is cast, and players should receive reputation.

When the Ethereum Prisons in Netherstorm are opened using http://www.wow-mania.com/armory/?item=29460, (which uses spell http://www.wow-mania.com/armory/?spell=35349), then **one of two scenarios happens;**

1.  A hostile NPC is spawned  (Untested, I have not managed to get him to spawn, may just be bad RNG).  I think this is NPC https://www.wowhead.com/npc=20520/ethereum-prisoner

2.  A friendly NPC from this list is spawned (this actual spawn works)
http://www.wow-mania.com/armory/?npc=22810  "Rescued Cenarion Expedition Druid"
http://www.wow-mania.com/armory/?npc=22813  "Rescued Consortium Dealer"
http://www.wow-mania.com/armory/?npc=22815 "Rescued Keepers of Time Custodian"
http://www.wow-mania.com/armory/?npc=22811 "Rescued Lower City Brute"
http://www.wow-mania.com/armory/?npc=22812 "Rescued Sha'tar Vindicator"
http://www.wow-mania.com/armory/?npc=22814 "Rescued Sporeggar Scout"
This NPC is supposed to cast the spell appropriate to their faction from this list, and then despawn.  **They are not casting this spell, and simply despawn.**
http://www.wow-mania.com/armory/?spell=39460 Cenarion
http://www.wow-mania.com/armory/?spell=39474 Consortium
http://www.wow-mania.com/armory/?spell=39475 Keepers of Time
http://www.wow-mania.com/armory/?spell=39456 Lower City
http://www.wow-mania.com/armory/?spell=39457 Sha'tar
http://www.wow-mania.com/armory/?spell=39476 Sporeggar

**Comment by wow-mania** [comment]
Fixed.
![image](https://user-images.githubusercontent.com/12248683/58016355-4e417680-7af5-11e9-94f6-1f1e80df2372.png)

It's not the NPC that gives the spell is the act of opening the prison.
But yes, there was an issue and now it is fixed. Thanks a lot.
