### ISSUE TITLE
Kartos not spawned in Halaa

### ISSUE THREAD

**Issue by jeyrella** [WoWManiaUK/Redemption#3281]
**Links:**
http://www.wow-mania.com/armory/?npc=18817

**What is Happening:**
When Halaa is captured by Alliance, Chief researcher Kartos (http://www.wow-mania.com/armory/?npc=18817) is not spawning.

After 3 restarts this week, have gone to Kartos and captured Halaa.  The PVP bar does not go all the way to the Alliance side and instead disappears at a random time.  Kartos never spawns.

**What Should happen:**
When Halaa is captured by Alliance,  Chief researcher Kartos (http://www.wow-mania.com/armory/?npc=18817) should spawn.

**Comment by wow-mania** [comment]
Works

**Comment by jeyrella** [comment]
This is most definitely still an issue.  Multiple reports that the QM is not spawning when Halaa is captured.  @GMMetaxa confirmed in-game tickets raised.

**Comment by Keader** [comment]
Fixed.
I moved both npcs, will be close of flag.
Inside of that house, was bugging both

**Comment by jeyrella** [comment]
Seems to be working now, tested two cycles
![image](https://user-images.githubusercontent.com/46089380/87883452-61a0e800-c9ff-11ea-98b5-539110961d9f.png)
