### ISSUE TITLE
Unarmed skill leveling with other weapon equiped

### ISSUE THREAD

**Issue by Tarkuss** [WoWManiaUK/Redemption#3282]
**Links:**

**What is Happening:**
In Wailing caverns with a sword equipped I was getting points in Unarmed skill.

My worgan had 100% riding speed at level 10 

**What Should happen:**

**Comment by wow-mania** [comment]
If anyone can give me steps to this I would appreciate.

**Comment by Kitzunu** [comment]
What kind of sword did you use?

1h? 2h?

**Comment by Kitzunu** [comment]
Also, please only report 1 bug per issue.

This report will only be about the skill since the other issue is a known one

**Comment by Dranah** [comment]
It happens when a mob disarms you.

**Comment by Tarkuss** [comment]
one hand I was getting unarmed just it seemed I went from 0 to 135 in a flash

________________________________
