### ISSUE TITLE
[Quest] Fires Over Skettis

### ISSUE THREAD

**Issue by IvanLlanas** [WoWManiaUK/Redemption#3283]
Quest: https://www.wowhead.com/quest=11008/fires-over-skettis
Skyguard Blasting Charges: https://www.wowhead.com/item=32406/skyguard-blasting-charges
Bombs Away: https://www.wowhead.com/achievement=1275/bombs-away

In this quest you're supposed to drop explosive charges over the kaliri eggs. The charges can only be used while on your flying mount. Everything works fine except for the fact that using the explosives dismounts you. This is a minor problem if you only try to complete the quest but a major issue if you try to get the "Bombs Away" achievement.

**Comment by Echinaceax** [comment]
will mark this as confirmed fixed @wow-mania 
 
but i am suprised this other bug with the eggs wasnt also reported with this report https://github.com/WoWManiaUK/Redemption/issues/6040
