### ISSUE TITLE
[Spell/Interaction] Aura Mastery / Potent Pheromones  / Conservator's grip

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#3284]
https://www.wowhead.com/spell=31821/aura-mastery
https://www.wowhead.com/spell=64321/potent-pheromones
https://www.wowhead.com/spell=62532/conservators-grip
Concentration Aura: ID 19746

There is a mildly interesting interaction bug among these spells that causes Freya's mushrooms to lose effect on raid members.

**Steps to repro:**
> Conservator spawns, activates Conservator's grip, silences raid
> Raid members hide under mushrooms, the mushrooms' Potent Pheromones suppress the silence effect on those that stand under
> Paladin with concentration aura activates Aura mastery, mushroom still works fine
> When Aura mastery expires, Conservator's grip reactivates, silencing every raid member who was affected by the expiring Aura mastery, despite all of them still standing under a mushroom that should be still protecting them
> the potent pheromones buff is still active on raid members, but they are silenced nonetheless

Here's me, silenced under a mushroom
![WoWScrnShot_040919_234001](https://user-images.githubusercontent.com/31132743/58135071-48e54880-7c29-11e9-8cb6-1dba76647497.jpg)
It feels like the aura mastery overwrites some component (probably immunity flag?) of the mushroom aura, and when it expires, it disappears without the other becoming active again.

**How it should work:**
Using Aura mastery should not anyhow interfere with the mushrooms' effect.

This can lead to random wipes since an unexpected raid-wide silence is not very pleasant on hard mode.

**Comment by Keader** [comment]
Nice match
Fixed.

**Comment by Dranah** [comment]
It no longer cancels the mushrooms protection.
Note: I also found it seems to have the ability to disable the GM cheat godmode. This is not a bug that would affect legit players, I just found it mildly interesting...
