### ISSUE TITLE
Quest bug: Klaven's Tower

### ISSUE THREAD

**Issue by RlyNotLazy** [WoWManiaUK/Redemption#3287]
**Links:**
https://www.wowhead.com/quest=2359/klavens-tower

**What is Happening:**
Same issue as described on wowhead:
The journal you need to complete the quest is not on the table => the quest cannot be completed.
Could you please mailbox me either the journal or quest reward?
Would suck to have a recipe missing just because this quest is bugged. :(

**What Should happen:**
The journal should be on the table, at the top of the tower.
I should be able to click it, get it, complete the quest using it.

I launched the game using the launcher, I am on the latest version.
I play night elf rogue.

**Comment by RlyNotLazy** [comment]
I abandoned the quest, no need to send me the quest item anymore.
Needed room in quest log. (the reward would be nice though :)

**Comment by Kitzunu** [comment]
You get it by pick-locking the box.
This works
