### ISSUE TITLE
[Spell] Pursuit of Justice

### ISSUE THREAD

**Issue by cathyr1** [WoWManiaUK/Redemption#3288]
This talent is bugged: http://www.wow-mania.com/armory/?spell=26023, just try it this way:

Load paladin with this talent active, then enter vehicle in wintergrasp, cannon, dragon or any other vehicle and then leave this vehicle. Your speed after leaving vehicle will be 100 % instead of 115 %.

**Comment by Kitzunu** [comment]
Please use the set template when you are reporting issues.

Thanks for your time :)

**Comment by Keader** [comment]
Fixed.
