### ISSUE TITLE
[Dungeon] Halls of Reflection

### ISSUE THREAD

**Issue by crulinjr** [WoWManiaUK/Redemption#3294]
What is happening: On a RHC i got into HoR hc so after killing the first 2 bosses and got to the end of the LK runaway, 1 Abomination got bugged and stood on the back so we couldnt kill it. LK then came and killed the mage NPC and procceded to kill us. After we came back we found the abom lying around and LK still at the end of the dungeon.
![WoWScrnShot_052719_141127](https://user-images.githubusercontent.com/40045543/58436292-35533b00-808a-11e9-9040-cc02d03c290c.jpg)

**What Should happen:**

**Comment by Dranah** [comment]
Can this be steadily reproduced in each run or it's just a random glitch?
We really can't do anything about it unless it has a specific reason to happen.

**Comment by Dranah** [comment]
Did we really need a label for this?

**Comment by volkangul** [comment]
I can confirm this is a "Random" Glitch.
