### ISSUE TITLE
[QUEST] Klaven's Tower [2359]

### ISSUE THREAD

**Issue by RlyNotLazy** [WoWManiaUK/Redemption#3295]
### **Links:**
https://classic.wowhead.com/quest=2359/klavens-tower

### **Some background:**
During this quest we should:
1.) pickpocket the key to the door of the tower off an npc outside
2.) use the key to get into the tower
3.) go upstairs and lockpick the chest
4.) get a debuff
5.) hand the quest in outside
6.) continue the quest chain and learn to remove the debuff

### **What is Happening:**
1.) I arrive at the tower
2.) I notice there is NO DOOR in the tower so I run straight in
3.) I lockpicked the chest
4.) I got the debuff
5.) I then cannot hand in the quest since I never pickpocketed the key
-> unable to go pickpocket it after lockpicking chest, due to the debuff that prevents you from going into stealth mode (it lasts 7 days and persists through death)
6.) unable to continue quest chain

### **What Should happen:**
The door should be there or the quest turn-in should not have the key as a requirement.

GM Metaxa was kind enough to remove the debuff for me.
I was then able to drop the quest and do it again in the correct error.
You may have other idiots like me encountering the same issue. (sorry!)

**Comment by Kitzunu** [comment]
Hmm, thats an interesting notice.

I will look into this ASAP

**Comment by Kitzunu** [comment]
Thanks for your contribution

**Comment by wow-mania** [comment]
![image](https://user-images.githubusercontent.com/12248683/58488793-eb3d8880-8161-11e9-916a-33ccb4258b43.png)

Damn how difficult is it to follow quest description instead of what you think is easier.
