### ISSUE TITLE
[QUEST] The Touch Of Zanzil [2608]

### ISSUE THREAD

**Issue by RlyNotLazy** [WoWManiaUK/Redemption#3296]
### **Links:**
https://classic.wowhead.com/quest=2608/the-touch-of-zanzil
https://classic.wowhead.com/quest=2609/the-touch-of-zanzil

**### Some background:**
During this quest we should:
1.) /lay in front of the NPC Doc Mixilpixil
2.) Doc Mixilpixil will finish his diagnosis
3.) Complete quest 2608 (the diagnosis)
4.) Start quest 2609 (the cure)

### **What is Happening:**
1.) Doc Mixilpixil starts before I even /lay
2.) He then disappears at random moments, and stays gone for long periods
3.) I dropped the quest 2608, restarted it and managed to complete it on my second try (before he vanished again)
4.) However, I was still unable to get 2609 before he vanished again

### **What Should happen:**
He should not start the diagnosis until players /lay
He should not be disappearing all the time.

**Comment by RlyNotLazy** [comment]
Was able to complete the quest by logging in a few hours later and clicking Doc Mixilpixil fast.

**Comment by wow-mania** [comment]
![image](https://user-images.githubusercontent.com/12248683/58487115-fba03400-815e-11e9-902d-98efa36121bd.png)
Works just fine
