### ISSUE TITLE
Sindragosa Gauntlet

### ISSUE THREAD

**Issue by Kitzunu** [WoWManiaUK/Redemption#3297]
The Teleporter to Sindragosa (The Frost Queen's Lair) should only be available after finishing the Sindragosa Gauntlet event.

Currently, you can bypass this by directly going to the teleporter and get the TP down to Sindy.

**Comment by Kitzunu** [comment]
Keader fix my shit :P

**Comment by Kitzunu** [comment]
By the way, I believe the trigger for the event to start is just a small circle that is in the center of the room.
So that trigger area would be needed to increase in size too so that you cannot skip the event

**Comment by Keader** [comment]
Fixed.

**Comment by Kitzunu** [comment]
The event works ok and the teleporter opens correctly

but the door from the gauntlet to Sindragosa CLOSES after the event is done and is OPEN when the event is going. this is wrong.

it should be CLOSED when the event is going and OPEN when it is finished

**Comment by Kitzunu** [comment]
Sindragose Entrance Door

**Comment by Kitzunu** [comment]
nvm had old lock with SAI :D
