### ISSUE TITLE
[Quest] A Plague Upon Thee (Part 2/3)

### ISSUE THREAD

**Issue by deltahammerfest** [WoWManiaUK/Redemption#3299]
**Links:**
Quest ID : 5904
Quest : https://www.wowhead.com/quest=5904/a-plague-upon-thee

**What is Happening:**

I use the Northridge Lumber Mill Crate, and nothing happens, but this : 

![WoWScrnShot_052919_194735](https://user-images.githubusercontent.com/15983089/58579392-3e3f3a80-824b-11e9-89c3-ff9e163d3805.jpg)

**What Should happen:**

Normally, the commentaries in wowhead explain that you can use the barrel of plaguelands, like this : 

![Sans titre](https://user-images.githubusercontent.com/15983089/58579894-3df36f00-824c-11e9-8bc4-16916571ac85.png)

(This is screenshots is from this video : https://youtu.be/BBAFM96QJBs?t=121 )

I have the barrel in my inventory.

I know that this issue was already reported before (https://github.com/WoWManiaUK/Redemption/issues/3269) but the issue was closed.

Sorry for my english, and thanks for what you doing !

**Comment by Kitzunu** [comment]
I cannot reproduce.
This works as far as I can see

![image](https://user-images.githubusercontent.com/24550914/58587162-f6291380-825c-11e9-82b6-d7b5568f07a7.png)

**Comment by Kitzunu** [comment]
nvm, something is shady with the script

**Comment by Kitzunu** [comment]
So the issue here is that after 1 player has used the gossip, the gossip does not re-appear causing this bug.

I have tried to check around with the script but cannot figure it out...

either @wow-mania or @Rushor has to look into this

**Comment by wow-mania** [comment]
Quest works flawless.

![image](https://user-images.githubusercontent.com/12248683/58620152-4edcc880-82be-11e9-97d7-e13c8b47f3e1.png)

**Comment by Kitzunu** [comment]
Not if one person does the quest and then another comes to do it after the barrel despawns...

**Comment by wow-mania** [comment]
Yes, the object is not resetting. We need to fix it.

**Comment by Kitzunu** [comment]
I tried to make it despawn and respawn with SAI, but for some reason, it would not work

**Comment by Rushor** [comment]
try now pls after server restart
