### ISSUE TITLE
Killing Booty Bay Bruisers 

### ISSUE THREAD

**Issue by grigtsiouv** [WoWManiaUK/Redemption#3300]
So, killing Booty Bay Bruisers https://www.wowhead.com/npc=4624/booty-bay-bruiser doesn't decrease reputation with Booty Bay https://www.wowhead.com/faction=21/booty-bay on one of my characters. Becoming Hated with Booty Bay is a requirement for these quests https://www.wowhead.com/quest=1036/avast-ye-scallywag https://www.wowhead.com/quest=4621/avast-ye-admiral 
Killing Booty bay Bruisers with my priest however, my rep got decreased by 625 per kill.

**Comment by Kitzunu** [comment]
Please use the given template when creating a report.

thank you for your contribution

**Comment by wow-mania** [comment]
Did some changes to script but nothing related to this. I cannot reproduce.

**Comment by GMMetaxa** [comment]
@Kitzunu The information he provided should be more than enough.
@wow-mania Killing Booty Bay bruisers should decrease Reputation with Booty bay. This does not happen on Revered status. On Neutral it does.

**Comment by WhitephoenixTheBunny** [comment]
Tested on Dev

Stood my Steamwheedle Cartel Rep to Revered
[Boorty Bay](http://www.wow-mania.com/armory/?faction=21), [Gadgetzan](http://www.wow-mania.com/armory/?faction=369), [Ratched](http://www.wow-mania.com/armory/?faction=470) and [Everlook](http://www.wow-mania.com/armory/?faction=577).

Attacking the referenced NPC, [Booty Bay Bruiser](http://www.wow-mania.com/armory/?npc=4624), the reputation with Booty Bay didn't decrease as it should.

![image](https://user-images.githubusercontent.com/31921098/58632192-d20d1700-82dc-11e9-9df8-4002cb8c9c5c.png)

Beside the screenie provided by GM Metaxa I found another [source](https://wowwiki.fandom.com/wiki/Bloodsail_Buccaneers_reputation_guide):

![image](https://user-images.githubusercontent.com/31921098/58632471-6e371e00-82dd-11e9-81ca-1c6524bc7203.png)

**Comment by Kitzunu** [comment]
![image](https://user-images.githubusercontent.com/24550914/58633151-e99dcd00-82e7-11e9-83e2-fa043c43a0d9.png)
![image](https://user-images.githubusercontent.com/24550914/58633168-fc180680-82e7-11e9-840d-11d13020bf72.png)
