### ISSUE TITLE
Worg form for DK's does not increase speed.

### ISSUE THREAD

**Issue by MathewH** [WoWManiaUK/Redemption#3301]
**Links:**
https://www.wowhead.com/spell=68996/two-forms#changelog

**What is Happening:**
The character transforms from Human to Worgen form or from Worgen form to Human form. No buff is applied.

**What Should happen:**
The transformation should happen in the same way, but the Worgen form should come with a 20% increase in movement speed as well as a reduced chance to be hit by effects that would reduce movement speed.

**Comment by wow-mania** [comment]
This is Wotlk not cata.
Not everything is as it is in cata.
I will look into it but no promises

**Comment by wow-mania** [comment]
![image](https://user-images.githubusercontent.com/12248683/58645015-65087a00-82fa-11e9-9332-b16790e39faf.png)

**Comment by MathewH** [comment]
Ok, I get my mistake. I thought Two Forms, which switches between Human/Worgen would give the buff, but instead there is the sepparate Worg Form spell, that acts like a druid travel form.
