### ISSUE TITLE
Speed Hack is really a bug!

### ISSUE THREAD

**Issue by wsforthug** [WoWManiaUK/Redemption#3303]
**Links:**
wsforthug banned due to speed hack!

**What is Happening:**

I was flying my flying mount and suddenly I was in red ridge mountains near the castle where i didn't see any mobs, and there I lost my flying mount and I was swimming it the air, then when I came to the ground I was walking faster, and when i came near the water it showed as of I was on my flying mount due to the wave in water.
Also I got hit by mobs even in the air when I thought it is lagging.
Suddenly I get banned, what is the reason for that? Hack?
I am a developer my self in python computer vision, now if you ask me to test some hack with my main account is stupid, secondly I play for fun, thirdly even if I dont get un-banned dont care and that is the truth, But you can check my previous msg with GM (name: Divigrac, Have image too) I asked about contacting Janitor for hosting for my country wow-mania, because I thought it is maintained very well, so the main purpose of this msg is dont bann other people same as me without knowing the real problem with your system because I did not HACK!
now if you believe me or not up to you.
Thank you I loved playing the game and thanks for your efforts so far!

**What Should happen:**

**Comment by Kitzunu** [comment]
Please make a formal ban appeal to Janitor on E-Mail or Discord since this is not the place for that.

As for the bug, feel free to PM me or Janitor directly on Discord to give either of us reproduction steps on how this happened to you.

I will close the thread and take this private instead.

**Comment by GMMetaxa** [comment]
We will look into this. A PM to Kitzunu is useless, He has no power to decide.
