### ISSUE TITLE
[Object] Flame Cap - ID 181276 Missing nodes, long respawn rate

### ISSUE THREAD

**Issue by Drostthehunter** [WoWManiaUK/Redemption#3304]
**Links:**
https://www.wowhead.com/item=22788/flame-cap
https://www.wowhead.com/object=181276/flame-cap

**What is Happening:**
I have been spending lately a lot of time trying to figure out what is the issue along with the 2 guildies who have been farming this specific herb for end game purposes. Flame Cap is supposed to share the nodes same as respawn time along with the Ragveil according to wowhhead comments that i was able to dig up. At the moment after weeks of farming this same herb and finding almost ALL nodes with all possible herbs that could of been found in Zangarmarsh i have only found 17 nodes that are spawning Flame Cap with the respawn time of 75 minutes, which is insane. 
 
![WoWScrnShot_053119_182901](https://user-images.githubusercontent.com/43518434/58720693-285c8180-83d3-11e9-8ca3-082667c6ac86.jpg)

**What Should happen:**
According to wowhead comments, the Flame Cap should be a spawned on the same spot as you can find Ragveil, there should be around 200 Ragveil spawns around the Zangarmarsh and so far only 17 nodes of Flame Cap,
https://www.wowhead.com/object=181276/flame-cap this link showing the possible spawn points of Flame Cap and throughout all Wowhead comments i havent find a single post saying that respawn time is this long, makes no sense.

**Comment by jarvik76** [comment]
I'm sorry, I don't understand - how is this invalid when there were 200 nodes in Blizz (i.e. every Ragveil spawn point) and only 17 here?

**Comment by WhitephoenixTheBunny** [comment]
@wow-mania I will try look more infos about it.
I think is a valid report.
I will reopen if I found valid sources

**Comment by WhitephoenixTheBunny** [comment]
https://wotlk-twinhead.twinstar.cz/?object=181276

On WoTLK those are the spawns 

![image](https://user-images.githubusercontent.com/31921098/58753147-0fc39880-84b3-11e9-8cda-6a0f564cd9c5.png)
