### ISSUE TITLE
Wintergrasp: allies with perma-tenacity...

### ISSUE THREAD

**Issue by Diletance** [WoWManiaUK/Redemption#3306]
**What is Happening:**
There are some Alliance players that are ALWAYS at Wintergrasp and they may be either be using some kind of hack or abusing some kind of bug. Reasons:

1: they seems to always "track hidden" without a hunter/druid or Blackened Worg Steack buff active, or any of the like.
Even when they are on a siege engine, they throw stuff far, far away (example, the catapults AoE attack), aiming exactly at where any stealthed character is hiding, in hopes of dealing damage to reveal the player to others. I'm not talking about "randomly throwing AoE" in hopes of finding an enemy.
Also, if a stealthed Horde character aproaches a lone Ally they usually play bait; but if more than one Horde is going for the same target, they move out, just like as if they knew exact amount of enemies incoming.

2: they ALWAYS seem to have "tenacity" no matter how many "Horde vs Alliance" are on the current Wintergrasp. This buff should balance the battle, but no balance is possible when you have 3 Horde with "75% tenacity" versus 8 Allies with "112% tenacity". I once took my Worgen DK into the lot to confirm how strange things were: I reached wintergrasp, joined the battle, and got no "tenacity" buff myself, as there were more Ally than Horde. However, there were at least 3 alliance players with tenacity, with varied amounts of bonus. At the time I decided to try to reach a GM in-game and ask him to check it out (but to no avail) and for this reason I didn't take any picks or the like. (yes, I hate me now).

However, as this issue keeps on happening, I believe it is just a matter of time to confirm what is going on.

**Comment by wow-mania** [comment]
Without a way to reproduce we can't do much.
This issue has been worked over many times and we believe it works quite well.
If there is a corner case where it fails please describe it.
