### ISSUE TITLE
Levitate+penance bug

### ISSUE THREAD

**Issue by grigtsiouv** [WoWManiaUK/Redemption#3308]
**Links:**
https://www.wowhead.com/spell=47540/penance
https://www.wowhead.com/spell=50195/levitate

**What is Happening:**
When I use penance while i have the levitate buff on my priest only the first bolt will be cast, and the spell is interrupted. Mind flay also gets interrupted when im levitating. This mostly happens in dungeon groups.

**What Should happen:**
Penance should always get 3 bolts.

**Comment by jak2019** [comment]
Penance has been doing this to me without having levitate. I can't pin down the common thread on why some casts go through all the way and others don't, but it is happening.

**Comment by grigtsiouv** [comment]
I never had any issues with Penance by it self. perhaps you are interruping it by casting another spell too soon.

**Comment by Dranah** [comment]
If you take damage while levitating, the spell breaks and the falling movement interrupts whatever cast or channel has been going on. 
Cannot reproduce channels breaking in any other case when levitating.

https://github.com/WoWManiaUK/Redemption/issues/3157 this issue with 2-tick penance has been reported multiple times, but nobody can figure how to reproduce the problem. 
Some players never experience it, which leads me to believe it is based on lag. It's most certainly not the player's fault with interrupting early (fellow player made video of it for us and he has tried using the nochanneling macro I gave him). 
However we cannot fix a problem that only affects a few people and is not a general issue.

**Comment by grigtsiouv** [comment]
It doesn't have to do with taking damage in my case. It happens to me while im in dungeons, but in dalaran or other places it works perfectly fine.

**Comment by Dranah** [comment]
if you can point to a specific dungeon, specific area, I can see to reproduce there maybe

**Comment by grigtsiouv** [comment]
Its in every area of every dungeon (wotlk at least). If it doesnt happen to you maybe my character is bugged? idk. i will ask some players in game.

**Comment by grigtsiouv** [comment]
Ok, this seems to happen to other people too. Casting it on myself works, but casting it on others gets interrupted.

**Comment by Kitzunu** [comment]
I will re-open this if more information on how to reproduce this issue is found, as this has been reported plenty times and nobody has been able to recreate the bug yet.

**Comment by Kitzunu** [comment]
When this bug happened to you, did you have any other buff/debuff/spell/aura on you or the target you are trying to pennance?

**Comment by grigtsiouv** [comment]
I looked into it a bit more, and this looks to be a camera issue. When the target is directly in front of me, penance will be normally cast with 3 ticks.  However, if im looking in any different direction, the first tick will rotate my character to align with the target and then it will be interrupted. However, when i dont have the levitate buff, no matter where im looking at, the first tick will rootate my character, but then it won't interrupt the cast on next two ticks. This means, that in dungeons and raids (where the targets will be moving around) only the first tick will apply, so it cannot be used properly. I hope this helps :)

**Comment by Keader** [comment]
This bug is real, and i think that i know how fix.

**Comment by Keader** [comment]
Try now please.

**Comment by grigtsiouv** [comment]
It is  still getting interrupted :/

**Comment by Keader** [comment]
Did you tested on PTR ?

**Comment by grigtsiouv** [comment]
oh no, idk how to do that.

**Comment by Dranah** [comment]
I cannot test something that i've never been able to produce in the first place. Please push the fix to live so they can see the result.
