### ISSUE TITLE
[Spell] Infest - 10HC Not working as it should (resto druid)

### ISSUE THREAD

**Issue by Rho-Redemption** [WoWManiaUK/Redemption#3309]
**Links:**
https://www.youtube.com/watch?v=ym_ypieeVFM&list=PLYXp-VsdBp47c6K6vz3x9u6PIdQDPLe4k
Here is a preview of what is happening at the moment, from 3 different LK 10hc runs.
http://www.worldoflogs.com/reports/rt-kdvjib0q3vufnqh6/details/2/?s=7334&e=8813
Preview of how it should be taking into account "befallen" is infest = 7.2k on average for 10hc.
https://wowwiki.fandom.com/wiki/Lich_King_(Icecrown_Citadel_tactics)
Also states a ranging value from 6.5k to 7.4k on 10man.
**What is Happening:**
Infest is hitting for values ranging from 8k to 12.8k. In the latest video, it is hitting for 12.7k in phase 1 at the second infest. And usually in phase 2, it hits from 11k-12k.
**What Should happen:**
I have spoken to dranah, and according to the world of logs it should hit around 7k average. 
http://www.worldoflogs.com/reports/rt-kdvjib0q3vufnqh6/details/2/?s=7334&e=8813
is proof of old log from a resto druid. This problem I have only noted on resto druids. 
If one watches the 25hc videos/fights you would see it hits on average at around 12k-14.5k. This ratio does not go in line with the 10hc values

**Comment by wow-mania** [comment]
I cannot confirm this.
Can anyone try it on dev please.

**Comment by Dranah** [comment]
I can.
It's hitting up to 12,5k on 10 hc. That is 25hc damage value.
Whenever it hits for less, it's due to partial resists.

**Comment by Dranah** [comment]
https://www.wowhead.com/spell=70541/infest

**Comment by Dranah** [comment]
Ok so after some intense debating/research it seems the damage value was buffed sometime on 3.3.5a Wowwiki shows the original logged values of 3.3.0 and so do most videos, but on end game 3.3.5a videos (2010 July-Sept) the spell hits more than that, which matches the database value of 11k.
Here's an example: https://www.youtube.com/watch?v=rAF6rCKDeDo
At 5:43 the warlock takes an infest hit for 6,6k damage, 1,6k going on pet, that totals 8,2k and he has 130 shadow resistance from the paladin's aura. Which means he resist 25% of shadow damage almost all the time, so the original spell was hitting for 11k to produce that value.
You can also see on this video that even with 11-12k base damage the spell is not strong enough to hit through a disc priest's shield at this gear level.
So this stays as is.
