### ISSUE TITLE
Transmog Issue

### ISSUE THREAD

**Issue by soulblade128** [WoWManiaUK/Redemption#3310]
**Links:**
http://www.wow-mania.com/armory/?item=22743

**What is Happening:**
This item is flagged as a consumable for some reason.
So when you go to a transmogrifier you can't put it in a set.

**What Should happen:**
It should be classified as a Cloth Armor, since you can equip it to your character.
You should be able to choose it for transmoging.

**Comment by wow-mania** [comment]
As-is. This is a default item with no modification.
Please check on the forum the rules for transmogrification.
