### ISSUE TITLE
hunter pets agro

### ISSUE THREAD

**Issue by jak2019** [WoWManiaUK/Redemption#3311]
**Links:**

**What is Happening:**
Pet is generating ZERO threat.  Using growl, attacking and misdirect, the pet is no longer gaining any agro. I feign death and combat breaks.

**What Should happen:**
The pet should get agro if it growls, I feign or even if it just attacks.  When my pet attacks and I don't, the mob still comes straight at me.

**Comment by Dranah** [comment]
Something bugged your pet... i have no such problem.
