### ISSUE TITLE
[Quest] Amped for Revolt!

### ISSUE THREAD

**Issue by kalitor92** [WoWManiaUK/Redemption#3313]
**Links:**
Amped for revolt!

**What is Happening:**
you can pick up the quest, but you cant do anything else

**What Should happen:**
Rizzy ratchwiggie should give you a bomber.

**Comment by gamer100** [comment]
http://www.wow-mania.com/armory/?quest=13374

**Comment by wow-mania** [comment]
works

**Comment by wow-mania** [comment]
looking into it
