### ISSUE TITLE
[Npc] Yebb Neblegear

### ISSUE THREAD

**Issue by gamer100** [WoWManiaUK/Redemption#3315]
**Linkhttp://www.wow-mania.com/armory/?npc=14829s:**

Need to offer  daily  quest"More Glowing Scorpid Blood"
http://www.wow-mania.com/armory/?quest=8223
 The quest is not on the npc

![image](https://user-images.githubusercontent.com/33811022/58946695-c743fd80-8786-11e9-9421-d681f096f355.png)
![image](https://user-images.githubusercontent.com/33811022/58946785-ee023400-8786-11e9-972a-6a1aae033f0b.png)

When you  finished the Quest, glowing scorpid blood

http://www.wow-mania.com/armory/?quest=8222
He must have the next
http://www.wow-mania.com/armory/?quest=8223
But is not there  even if you  have the 10 Glowing Scorpid Blood
http://www.wow-mania.com/armory/?item=19933

**Comment by wow-mania** [comment]
![image](https://user-images.githubusercontent.com/12248683/58950570-01ad9a80-8787-11e9-81b5-210e26d2b014.png)

Please check quest requirements before posting issues. It will save devs time.
You can also ask another person to check. Sometimes we miss some simple details.

![image](https://user-images.githubusercontent.com/12248683/58950612-168a2e00-8787-11e9-825c-7af0c9f64885.png)
