### ISSUE TITLE
[NPC] Horde Runners in Loch Modan

### ISSUE THREAD

**Issue by corrinr** [WoWManiaUK/Redemption#3318]
**Links:**
http://www.wow-mania.com/armory/?npc=2477 | https://www.wowhead.com/npc=2477/gradok
http://www.wow-mania.com/armory/?npc=7170 | https://www.wowhead.com/npc=7170/thragomm

**What is Happening:** Two Horde Runner NPCs in Loch Modan seemed to be following their pathing by bouncing up and down very fast and T-posing:
![WoWScrnShot_060519_161644](https://user-images.githubusercontent.com/48542141/59058200-bae0a300-8861-11e9-8f23-bca005295e5f.jpg)
![WoWScrnShot_060519_161648](https://user-images.githubusercontent.com/48542141/59058211-c0d68400-8861-11e9-9c95-878791c9e4dd.jpg)
![WoWScrnShot_060519_161658](https://user-images.githubusercontent.com/48542141/59058217-c3d17480-8861-11e9-81dd-1e41e519aab7.jpg)

**What Should happen:** I think they are both supposed to be walking up and down the banks of the Loch, but maybe not so high in the air?

**Comment by wow-mania** [comment]
thanks I will check that

**Comment by wow-mania** [comment]
This is fine.
What you probably saw was them returning to meet Haren Swifthoof after being killed by someone.
They move in formation.
