### ISSUE TITLE
[Quest] Collection of Corrupt Water

### ISSUE THREAD

**Issue by Bartok14** [WoWManiaUK/Redemption#3319]
Here's a link to the quest.

https://www.wowhead.com/quest=5157/deprecated-collection-of-the-corrupt-water#screenshots

When you try to get the new canteen, nothing happens. You can use the empty canteen at the well and you won't receive the next quest item.

**Comment by wow-mania** [comment]
![image](https://user-images.githubusercontent.com/12248683/59144298-c3ee8300-89cd-11e9-8bac-b36736d7a32e.png)


From time to time someone comes with the same issue. Just try different locations. If it worked then, it works now!
