### ISSUE TITLE
[Instance] Black Morass

### ISSUE THREAD

**Issue by jarvik76** [WoWManiaUK/Redemption#3322]
The timing of the spawn of the portals after the first boss is incorrect.
This happens even when completed at level. It is nothing to do with gear.

**What is happening**
For the first 7 portals, up until and including the portal with Chrono Lord Deja, the portals spawn at about 45 second intervals. (Correct)
For the portal after the boss (8th portal), it spawns after ~120 second gap. This is to allow recovery after fighting boss. (Correct)
EVERY portal after the 7th now gets the ~120 second spawn interval. (**Incorrect** - should be 45 seconds again)

**What should happen**
For the first 7 portals, up until and including the portal with Chrono Lord Deja, the portals spawn at about 45 second intervals. (Correct)
For the portal after the boss (8th portal), it spawns after ~120 second gap. This is to allow recovery after fighting boss. (Correct)
Thereafter, **the portals should then spawn at 45 second intervals agai**n until the the next boss, (13th portal) , Temporus, which should then have another 120 second interval for fighting boss.
14th portal then 45 seconds again, etc.

**Comment by wow-mania** [comment]
We will re-check.

**Comment by Bartok14** [comment]
I really don't know why this was closed in the first place. I provided you guys with everything you needed to look into the issue. If you want your community to take their time to post these issues you can't just close them without fixing the problem.

**Comment by jarvik76** [comment]
Thank you all for your efforts to fix this, appreciated.
