### ISSUE TITLE
[Boss] Valithria Dreamwalker Enrage/Berserk Timer

### ISSUE THREAD

**Issue by Kitzunu** [WoWManiaUK/Redemption#3324]
Atm Valithria has to Enrage/Berserk timer but after doing some research it looks like she should have some form of way to wipe the raid.

>https://wow.gamepedia.com/Enrage_(mechanic)
Valithria Dreamwalker: **If not fully healed in around 7 minutes, she 'enrages' and starts to pull every mob to her position, wiping the raid.** Players have to manage to protect the healers as they heal Valithria, and dps have to kill and interrupt the mobs to prevent the healing reduction debuff. Using the Emerald Nightmare portals properly and killing the dream clouds inside is important to beating the encounter, since it is impossible for players to heal Valithria and handle the mobs without properly using the buff granted by killing the dream clouds.

>https://wow.gamepedia.com/Valithria_Dreamwalker#Setup
Adds spawn from the gates. In 25 player, all four gates spawn adds, in 10 player it's only the front two. The spawn rate increases over time. **After 7/? (10/25 player) minutes, Suppressors and Blazing Skeletons start to spawn continuously, which usually leads to a quick wipe.**

>https://wowwiki.fandom.com/wiki/Valithria_Dreamwalker#Quotes
Berserk
FAILURES!

>https://www.mmo-champion.com/threads/708492-Healing-Valithria?p=7629636&viewfull=1#post7629636
We got her to 80% on our last attempt, but hit the enrage timer.

You also have this post mentioning *soft enrage timer* https://www.wowhead.com/npc=36789/valithria-dreamwalker#comments:id=963596

**What should happen:**
I am not exactly sure what should happen when the timer is reached, but from the sounds of it, there should be some kind of soft enrage timer for around 7 minutes.

**Comment by Kitzunu** [comment]
If someone finds a youtube video or other information that could help please add it.

**Comment by wow-mania** [comment]
As is. Not messing with this again.

**Comment by Dranah** [comment]
The soft enrage of 7mins for Vali means at this point the spawn rate of adds grows significantly, especially Suppressors and Blazing Skeletons.
Or should mean. Basically adds flooding the raid = wipe soon.
I'm not sure if this can be implemented, but it puts a significant difference in the fight as of not needing to worry about how long you take.
