### ISSUE TITLE
Problem with logging in the game

### ISSUE THREAD

**Issue by Votrubic** [WoWManiaUK/Redemption#3325]
**Links:**

**What is Happening:**
I turn on wow.exe. Write my name and password and continue on my characters. I choose one, It doesn´t matter which and the loading screen came next. The bar of loading screen goes until the end, when It´s done it returned on the screen where is name and password and told me: you have been disconected from the server. So I can´t play at all, because It doesn´t let me in the game on my character. My friend told me, that he see me online on a sec. and then i went offline..
![WoWScrnShot_060919_195558](https://user-images.githubusercontent.com/51538172/59162468-f0032480-8af1-11e9-9f49-e0e2e45f3704.jpg)

**What Should happen:**
Turn on wow.exe. Logg in. Choose character. Wait until the loading screen bar goes until the end. And then I´ll be on my character and I can play.

**Comment by Kitzunu** [comment]
This could be the use of Proxy/VPN.

Make sure you place your folder in a root drive i:e.: C:\
Uncheck Read-Only for the folder and realmlist.wtf
Start the launcher as an administrator

if you still have issues, contact Janitor on Discord or E-Mail

Janitor#2871
support@wow-mania.com

**Comment by Votrubic** [comment]
Doesn´t working.

**Comment by Kitzunu** [comment]
Contact janitor via either discord or email that I linked above

**Comment by Votrubic** [comment]
contacted, thanks for reply :)

**Comment by Votrubic** [comment]
> This could be the use of Proxy/VPN.
> 
> Make sure you place your folder in a root drive i:e.: C:
> Uncheck Read-Only for the folder and realmlist.wtf
> Start the launcher as an administrator
> 
> if you still have issues, contact Janitor on Discord or E-Mail
> 
> Janitor#2871
> [support@wow-mania.com](mailto:support@wow-mania.com)

I tried change realmlist on different server and it was all okey and i can play. But when i set realmlist on wowmania back, I have same problem. It´s really weird.

**Comment by Votrubic** [comment]
Okey It is working. wtf ? :D thanks for help
