### ISSUE TITLE
Enchanting Cloth Heirloom Chest Fails - Target is too low level (Confirmed by GM Zinius)

### ISSUE THREAD

**Issue by StirCwazy** [WoWManiaUK/Redemption#3329]
I'm level 77, have the [Tattered Dreadmist Robe](https://www.wowhead.com/item=48691/tattered-dreadmist-robe) (Heirloom) with [[Enchant Chest - Superior Health](https://www.wowhead.com/spell=13858/superior-health)] currently.  I'm trying to enchant with  [[Enchant Chest - Super Stats](https://www.wowhead.com/item=38989/enchant-chest-super-stats)] and receive the message that the Target it too low level.  The requirements for the enchant are a level 60 item, since I'm using an heirloom at level 77, it should and does show it as a level 77 item.  I spoke with GM Zinius and he/she confirmed by duplicating the issue and requested the bug report be filed.

**Comment by wow-mania** [comment]
The issue is the heirloom not your level.

**Comment by StirCwazy** [comment]
So am I not supposed to be able to enchant my heirloom with that enchant?

**Comment by wow-mania** [comment]
![image](https://user-images.githubusercontent.com/12248683/59358186-04c6fe80-8d24-11e9-8be3-f382029d4108.png)

**Comment by Kitzunu** [comment]
Basically, Heirlooms are counted as iLvl 1 which means that you will not be able to enchant heirlooms that require a specific level to be enchanted.
