### ISSUE TITLE
[Quest] Banish the Demons

### ISSUE THREAD

**Issue by jarvik76** [WoWManiaUK/Redemption#3331]
**Links:**
http://www.wow-mania.com/armory/?quest=11026

**What is Happening:**
The Ogri'la reputation requirements for this quest is set to Revered

**What Should happen:**
The Ogri'la reputation requirements for this quest is set to **Honored**

Apologies for the following screenshots from Wowhead comments, it is the only source I could find, note the patch numbers:
![image](https://user-images.githubusercontent.com/46089380/59550479-03374980-8f63-11e9-9155-44955a782a67.png)
![image](https://user-images.githubusercontent.com/46089380/59550491-2bbf4380-8f63-11e9-8f0c-edffe06cc957.png)
![image](https://user-images.githubusercontent.com/46089380/59550577-21ea1000-8f64-11e9-9639-a87ccd2b673a.png)

(If the above screenshots are not convincing enough, then here's another rational reason:  quest 11060 A Crystalforged Darkrune is available at Honored, but requires using the reward from quest 11026 to complete.  In that case, it makes no logical sense for 11026 to be locked behind Revered.)

Thanks!

**Comment by wow-mania** [comment]
Applied to live also.
