### ISSUE TITLE
[Spell] Call of the Wild ID: 53434

### ISSUE THREAD

**Issue by Drostthehunter** [WoWManiaUK/Redemption#3332]
**Links:**
http://www.wow-mania.com/armory/?spell=53434

**What is Happening:**
At the moment in raid atmosphere the pet ( wolf ) is applying this buff to ALL raid members. It does not happen everytime this spell has been cast by a wolf but it does occur often.

**What Should happen:**
It should be a buff only for Hunter and his pet.
I have no screenshots to prove this, therefore pls dont close it right away.
I have been digging around and found that it is very common bug on some other private servers.

**Comment by wow-mania** [comment]
Highly doubt there is an issue here but will give the benefit of the doubt and wait for tester's comment.

**Comment by Dranah** [comment]
Confirmed, steps to repro:

1. Have a raid group inside a raid, in combat with a boss engaged, at least 2 party fully or partly filled.
2. Have auto cast active on the Call of the wild and send your pet to attack
3. The pet attacks, auto casts Call of the wild and it affects every PARTY member (not whole raid), like it used to do before the patch 3.0.8.

Patch 3.0.8 changed the ability from party-wide to hunter and his pet only.

How it should work:
The spell should always be affecting only hunter and his pet, no matter the raid environment or if the pet is autocasting.

Screens:
TEST1 - Manual cast: Hunter has the buff but her party member, Roana, does not
![WoWScrnShot_061519_173301](https://user-images.githubusercontent.com/31132743/59553325-c46db780-8f93-11e9-8bd6-b8a1346f1916.jpg)

TEST2 - autocast: Both hunter and her party member Roana is affected:
![WoWScrnShot_061519_173018](https://user-images.githubusercontent.com/31132743/59553330-d7808780-8f93-11e9-974b-99dcbd33f232.jpg)
