### ISSUE TITLE
Lich King Leather Armor Set - Chest Slot Stats

### ISSUE THREAD

**Issue by volkangul** [WoWManiaUK/Redemption#3333]
**Links:**
http://www.wow-mania.com/armory/?item=90031

**What is Happening:**
1)This item's stats are too weak for a 283 ilvl.
2)In game item sets showing 6/6 and 9/9.

**What Should happen:**
1)The item based on http://www.wow-mania.com/armory/?item=50656   probably. But the stats are too weak if we compare them. The LK Chest item should be buffed to 283 ilvl quality.

2) 6/6 set bonus should not be showing in game which is same with 9/9 bonus. Also 6/6 is not working due to item set bonuses starting to giving those bonuses on 7/7.

**Comment by wow-mania** [comment]
This is not an issue. It is a feature request on a custom item.
I will look into it when I have some time.

**Comment by volkangul** [comment]
Thank you boss.
