### ISSUE TITLE
[Talent] Improved Shadow Bolt ID: 17803

### ISSUE THREAD

**Issue by Drostthehunter** [WoWManiaUK/Redemption#3335]
**Links:**
http://www.wow-mania.com/armory/?spell=17803
http://www.wow-mania.com/armory/?spell=12873
**What is Happening:**
Those 2 spells are at the moment stacking, adding 10% extra critical strike chance instead of only 5%. The debuffs are called Improved Scorch which is a talent in a mage fire tree and Improved Shadow Bolt which is a talent in Destruction warlock tree.

![](https://cdn.discordapp.com/attachments/534798332011347968/590503225988349965/unknown.png)

![](https://cdn.discordapp.com/attachments/534798332011347968/590504301403701249/unknown.png)
![magelock stack](https://user-images.githubusercontent.com/43518434/59679893-5b26b800-91d0-11e9-8b12-e3373b402d02.jpg)

**What Should happen:**
Those debuffs should not stack, and should not increase the critical strike chance further more. As shown on those screenshots.

Tip: Since this is not tested in raid atmosphere maybe it needs to be done

**Comment by Echinaceax** [comment]
Also only tested on dummy 
we (test team 5) havent tested via dummy :)

**Comment by Keader** [comment]
Tested now and they are not stacking
With my mage:

Without any debuff on dummy critical chance was: 34.1795
With Improved Scorch: 39.1795
With Improved Scorch and Improved Shadow Bolt (Shadow Mistery): 39.1795
With only Improved Shadow Bolt:  39.1795

Even with 2 debuffs on target, same effect will not stack xD
The list include those spells:

![image](https://user-images.githubusercontent.com/7120913/59868894-601e6f80-9368-11e9-9321-1b30b5f23a72.png)
