### ISSUE TITLE
[Core] Group behaviour when player logout

### ISSUE THREAD

**Issue by Kitzunu** [WoWManiaUK/Redemption#3348]
**How it works:** 
When you log out you leave the party you are in

**How it should work:** 
As of patch 3.3.0 you should no longer leave the party you are in if you log out.

**Proof:** 
From the 3.3.0 [undocumented changes](https://wowwiki.fandom.com/wiki/Patch_3.3.0_(undocumented_changes)):
- You no longer leave your party upon logging out.

**Suggested fix:**
I believe this would fix the issue
https://github.com/TrinityCore/TrinityCore/commit/e906a2fe7d71fc17de9f7ea4778970beb3f9265e

**Comment by Kitzunu** [comment]
Why would you close this?

**Comment by Dranah** [comment]
Kitzu proposed the fix, can we at least try it out? :D
