### ISSUE TITLE
Wrong colors on T8 Dead Knight set.

### ISSUE THREAD

**Issue by Roguess** [WoWManiaUK/Redemption#3350]
**Links:**http://www.wow-mania.com/armory?item=46111    http://www.wow-mania.com/armory?item=46115    http://www.wow-mania.com/armory?item=46113     http://www.wow-mania.com/armory?item=46116      http://www.wow-mania.com/armory?item=46117

**What is Happening:** The Dps T8 set have the wrong color. It is brown like T8 tank set.

**What Should happen:** The color of T8 dps set must be something like black/dark-combined with dark purple.
![WoWScrnShot_061919_145003](https://user-images.githubusercontent.com/51996550/59763352-15d2bb00-92a2-11e9-87fa-f4a825d51456.jpg)
![WoWScrnShot_061919_145032](https://user-images.githubusercontent.com/51996550/59763354-15d2bb00-92a2-11e9-9faf-4179412fa4a3.jpg)
![WoWScrnShot_061919_145038](https://user-images.githubusercontent.com/51996550/59763356-15d2bb00-92a2-11e9-9ee5-e87aae6db7bd.jpg)
![WoWScrnShot_061919_145043](https://user-images.githubusercontent.com/51996550/59763357-166b5180-92a2-11e9-9bd7-9d1dc289b1a8.jpg)
![WoWScrnShot_061919_145049](https://user-images.githubusercontent.com/51996550/59763358-166b5180-92a2-11e9-8900-456188efeb5b.jpg)

Thanks and sorry for my bad english.

Algor

**Comment by WhitephoenixTheBunny** [comment]
![image](https://user-images.githubusercontent.com/31921098/59766196-87f1d280-9297-11e9-82ad-130a027c2e48.png) 
Seller

![image](https://user-images.githubusercontent.com/31921098/59766703-af956a80-9298-11e9-926e-0a801e0d7477.png) 
Ingame

![image](https://user-images.githubusercontent.com/31921098/59766750-cc31a280-9298-11e9-830b-fe143e2704ca.png)
WoW Head Screenshot

Links: https://www.wowhead.com/outfit=52402/conquerors-darkruned-battlegear
https://www.wowhead.com/transmog-set=499/conquerors-darkruned-plate-25-recolor

**Comment by WhitephoenixTheBunny** [comment]
![image](https://user-images.githubusercontent.com/31921098/59778279-1bce9900-92ae-11e9-8009-21f44aae3fea.png)
