### ISSUE TITLE
[QUEST] Call to Arms: Warsong Gulch

### ISSUE THREAD

**Issue by Exxelz** [WoWManiaUK/Redemption#3351]
**Links:**
http://www.wow-mania.com/armory/?quest=11338

**What is Happening:**

The Quest completed, but u are not able to turn it in. I dont know yet if this bug existing only for WSG or if all BG's are affected

Note: I can only speak for Alliance Fraction i dont know if it affects the horde side too. Also it would be nice if any one can confirm this.

**What Should happen:**

You should be able to turn in the quest at any Alliance Brigadier General in all Main Cities, as well as in Dalaran, Shattrath and 1K Winter (if the Fort is capped by the right fraction)

**Comment by wow-mania** [comment]
This works.
