### ISSUE TITLE
Bug: Wrong model for Mount Demonic Gladiator's Storm Dragon

### ISSUE THREAD

**Issue by shoug-shoug** [WoWManiaUK/Redemption#3352]
**Links:**
https://www.wowhead.com/item=153493/demonic-gladiators-storm-dragon

**What is Happening:**
The Supposed Item 153493 At the Mall of Wow-mania
is called the Demonic Gladiator's Storm Dragon
But the model used is the Dominant Gladiator's Storm Dragon

**What Should happen:**

Demonic Gladiator's Storm Dragon should be Purple and Green Coloration as the original model intended.
https://www.wowhead.com/item=153493/demonic-gladiators-storm-dragon
This is the wrong model used for this item in the actual patch
https://www.wowhead.com/item=141848/dominant-gladiators-storm-dragon

**Comment by WhitephoenixTheBunny** [comment]
Demonic on Mania:
![image](https://user-images.githubusercontent.com/31921098/59850723-dae48c00-9362-11e9-9e23-01bbc6cdf48a.png)

Correct colour:
![image](https://user-images.githubusercontent.com/31921098/59850754-f059b600-9362-11e9-9954-103e9a5d346a.png)

Wrong colour:
![image](https://user-images.githubusercontent.com/31921098/59850819-07000d00-9363-11e9-893a-57e68a5fdbe4.png)

Mania mounts:
![image](https://user-images.githubusercontent.com/31921098/59851076-986f7f00-9363-11e9-9559-67898f28549d.png)

**Comment by WhitephoenixTheBunny** [comment]
Is colour can't be changed, rename it.

**Comment by wow-mania** [comment]
This is a custom model. As-is. We will not going to work on imported models.
