### ISSUE TITLE
Honor among Thieves stealth bug

### ISSUE THREAD

**Issue by Kallivira** [WoWManiaUK/Redemption#3353]
**Links:**
Potentially related bugs but not the same: 
https://github.com/WoWManiaUK/Redemption/issues/2362 - group critical hits not applying
https://github.com/WoWManiaUK/Redemption/issues/1295 - any critical hits not applying

I am creating a new one because I am not entirely sure its related, and the previous bug is a year old. The major difference in this bug, is it only pertains to attacks made when a rogue is actively in stealth.

https://wowwiki.fandom.com/wiki/Honor_Among_Thieves

Additional Links

**What is Happening:**
When a rogue uses the ability ambush from a stealthed state, if ambush were to crit no additional combo point is rewarded. However, Ambush does award a combo point from the talent Honor Among Thieves while using shadow dance.

Current state: a normal ambush strike awards 2 combo points. Initiative would give +1 combo point. Regardless of the attack being a critical hit Honor among thieves will not reward a combo point, when the attack is made while in stealth.

**What Should happen:**
When a rogue uses the ability ambush from a stealthed state, if ambush were to crit an additional combo point should be rewarded. This would be inline with how it operates while using shadow dance. 

Desired state: normal ambush strike awards 2 combo points. Initiative would give +1 combo point. Honor Among Thieves would award an additional 1 combo point if ambush were to crit from a stealthed state.

Attempted Troubleshooting from the client: Logged out, exited game, cleared cache, no addons in use. Had another rogue replicate the issue, and verified the issue with a gm in game. 

The day I encountered this issue was the 18th of June 2019.

**Comment by Keader** [comment]
i cant even understand what is the issue o.o
any help @Dranah ?

**Comment by Kallivira** [comment]
I'll try to clarify.

"Honor among thieves" that is a talent that will reward a combo point when any special ability (yellow damage) crits. This happens for your own abilities as well. 

The problem is: when using the ability stealth to be hidden, and using the ability ambush that initial attack will not add a additional combo point if it critically hits. 

This is most obvious with ambush because its the only opener that can take advantage of honor among thieves. In all other use cases, every thing is working as it should - just not when critically hitting with an ambush from stealth.

**Comment by Dranah** [comment]
Ok so, Ambush awards 2 combo points by default.
Taking Honor Among Thieves, Ambush crits should award 3, given that it isn't on internal cooldown from a party member.
It works when Shadow Dancing, but not when opening on someone with Stealth+Ambush.
Initiative has nothing to do with this. it works fine on its own, adding 1 extra regardless of everything else.
With Initiative taken, Shadow dance+Ambush awards 4points, and Stealth+Ambush awards only 3.

**Comment by flubbacrud** [comment]
I don't know the state of the core, understandably you haven't released it to public, but from what i've read on Wow-Mania it's TC.

This issue was fixed in TC a long time ago.

https://github.com/TrinityCore/TrinityCore/pull/16512
