### ISSUE TITLE
[Event] Brew of the Month Club mails

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#3356]
**Links:** https://wowwiki.fandom.com/wiki/Brew_of_the_Month_Club
https://www.wowhead.com/achievement=2796/brew-of-the-month
http://www.wow-mania.com/armory/?npc=27806

**What is Happening:** Purchasing a membership for the Brew of the Month Club grants the achievement and allows purchasing of the monthly beer from the NPC vendor (Brew Vendor), but members **do not** receive mail at the start of the month including a free sample to remind them of the new beer available.

**What Should happen:** 

> Each month, one sample beer is mailed to you. ou can buy additional samples of that month's beer from the Brew Vendor at the Stonefire Tavern in Ironforge for the Alliance or at Darkbriar Lodge in Orgrimmar for the Horde.

**Comment by WhitephoenixTheBunny** [comment]
I confirm as in game I have this

**Comment by Rushor** [comment]
fix will be like that: if you login on the month and if you have the archivement 2796 a  mail will be sended to you with the item

**Comment by WhitephoenixTheBunny** [comment]
Added achiev
Relogged and deleted cache
Got the mail

![image](https://user-images.githubusercontent.com/31921098/59976515-7ec97400-95bd-11e9-821c-01155d046e37.png)

**Comment by Rushor** [comment]
nice
