### ISSUE TITLE
[Quest] - The Drakkensryd

### ISSUE THREAD

**Issue by Ranaelchan** [WoWManiaUK/Redemption#3357]
https://www.wowhead.com/quest=12886/the-drakkensryd

If you are in cat form - you will be kicked out of it and return to human form and now have to destroy the NPC's while in this normal form.

Normally - regardless of class; this should be complete-able with ease as it's not supposed to be a difficult (2 or 3+ man quest) quest. However, when you use the harpoon to ride the Proto-drakes; whatever your form is - it will kick you out of that form. Now considering this is the case, you might think this is a bug - NO; I repeat, NO. It's working as intended by Blizzard. But unfortunately; it's bugged by design by Blizzard and they had forgotten about Hunters and Druids

My proposed solution for now is;
1.) Auto complete for now for those people who're currently doing this as it is a part of a massive quest-line. And...
2.) Have the ability to not be taken off druid forms when using the harpoon to allow any type of attacking forms the game allows is; (i.e. Moonkin, Feral or Bear). I heard stories about Hunters having a difficult in this quest too but please do test it for both Druids and Hunters.

**Comment by wow-mania** [comment]
Works!
