### ISSUE TITLE
[Achievement] Torch Juggler

### ISSUE THREAD

**Issue by Necko23** [WoWManiaUK/Redemption#3358]
I don't think the achievement alone is bugged, but it's showing some weird behaviour in certain parts of Dalaran. It is DEFINITELY DOABLE. Objective for the achievement : Juggle 40 torches in 15 seconds in Dalaran. I've made it a few times to 39/40. So I decided to switch to another part of Dalaran and give it a try there. I ended up at https://imgur.com/a/LWQ60ob . I started throwing torches and once they started falling down they literally phased thru me and I lost all of my 14 torches. I think it's the area that's not working well with the achievement and I had to find that out the hard way. Everything was working well on the top level of Dalaran. If I can provide any more information please let me know.

With regards,
Dudley

**Comment by wow-mania** [comment]
Works.
PLease search before entering new issues.

**Comment by nakininja** [comment]
Hi I'm still getting this and cant complete the meta achieve without it. it happens in every part of dala i am in. I have tried inside, outside, in the water everywhere
