### ISSUE TITLE
It's All Fun and Games

### ISSUE THREAD

**Issue by Slianchroi** [WoWManiaUK/Redemption#3359]
**Links:**
http://www.wow-mania.com/armory/?item=41265
https://www.wowhead.com/quest=12887/its-all-fun-and-games

**What is Happening:**
The Ocular is there, and can be targeted. However, once you use the Eyesore Blaster, even multiple times from different ranges and positions, it doesn't destroy the target to complete quest.

**What Should happen:**
The Eyesore Blaster should destroy NPC straight away

**Comment by WhitephoenixTheBunny** [comment]
Open a ticket ingame, you need a gm to reset NPC.
