### ISSUE TITLE
[NPC] Danno <Master Transmogrifier>

### ISSUE THREAD

**Issue by WhitephoenixTheBunny** [WoWManiaUK/Redemption#3361]
The NPC Danno <Master Transmogrifier> (no link avaible on armory - Entry: 70037) sells the "skin/xmog" for the player.

What is happening:

There is two major, and one minor, issues with this NPC atm:

1) It doesn't show the value of the xmog (1 [WoW-Mania's Transmog Token](http://www.wow-mania.com/armory/?item=37742) per Xmog);
![image](https://user-images.githubusercontent.com/31921098/60100539-d13b9980-9751-11e9-9efb-d22ef4716c90.png)

2) There's any purchase confirmation, when you click it, it will purchase it;

3) There's any information telling you only get the "skin/look" and not the actual object.

What should happen:

1) The NPC should show the value of the xmog:

2) & 3. A confirmation pop should appear, asking if player want progress with the purchase and informing he will not get the item but only the look.

**Comment by wow-mania** [comment]
Adding info on Hello dialog.
There will be NO confirmation dialog.

**Comment by WhitephoenixTheBunny** [comment]
![image](https://user-images.githubusercontent.com/31921098/60163082-bd943f80-97f2-11e9-9715-a96a2e69e6aa.png)
