### ISSUE TITLE
[NPC] Warpweaver Hashom <Transmogrifier>

### ISSUE THREAD

**Issue by WhitephoenixTheBunny** [WoWManiaUK/Redemption#3362]
The NPC [Warpweaver Hashom <Transmogrifier>](http://www.wow-mania.com/armory/?npc=70009) is the NPC offering the transmog service (transmog items, save sets, and remove transmog)
Geral menu:
![image](https://user-images.githubusercontent.com/31921098/60101321-799e2d80-9753-11e9-9684-508ade577a68.png)
![image](https://user-images.githubusercontent.com/31921098/60101347-815dd200-9753-11e9-9e4a-5976fc3406b5.png)
Slot menu (in this case the Head Slot)
![image](https://user-images.githubusercontent.com/31921098/60101694-1eb90600-9754-11e9-9ad6-b612d6c199f8.png)

What is happening:
ATM, one of his services isn't working, more specifically the "Remove Transmogrification" (slot menu) and "Remove all the Transmogrifications"(geral menu)
When you select it, it will remove the transmog (one piece or all, depending on the option selected), but when a player relog, the transmogs are back.

(minor issue: missing the tutorial in "How Transmogrifications Works")

What should happen:

When the player select "Remove Transmogrification" (slot menu) or "Remove all the Transmogrifications"(geral menu) the settings should stay even after a relog.
Maybe adding a confirmation pop, informing that option will be definitive.

**Comment by wow-mania** [comment]
Tutorial is on Forum.
Remove only works if ALL pieces are present

**Comment by WhitephoenixTheBunny** [comment]
The item used to xmog need be on our inventory?
