### ISSUE TITLE
[QUEST] Watts My Target

### ISSUE THREAD

**Issue by Holydefender** [WoWManiaUK/Redemption#3364]
**Links:**  
https://www.wowhead.com/quest=13381/watts-my-target

**What is Happening:** 
When i go to Karen No(https://www.wowhead.com/npc=31648/karen-no) to get the bomber, nothing happens when i ask her to summon it for me. I can open the dialogue, and press the button, but i dont get the bomber as i do in the previous two quests Leading the Charge and Static Shock Troops: the Bombardment

Note: Got assistance from Gamemasters - didn't work

**What Should happen:**
I should press the button in the dialogue menu, and a bomber should appear. as in the two previous quests.

**Comment by Rushor** [comment]
should be fixed now
