### ISSUE TITLE
[QUEST] The Storm King's Vengeance (Again)

### ISSUE THREAD

**Issue by Nithilus** [WoWManiaUK/Redemption#3366]
**Links:**
Quest: http://www.wow-mania.com/armory/?quest=12919
Problematic NPC: http://www.wow-mania.com/armory/?npc=29872#abilities

**What is Happening:**
During the quest "The Storm King's Vengeance" the NPC "Algar the Chosen" seems to have bugged and not spawn. I put in a ticket which was handled by GM Zinius who couldn't find the NPC after looking into the issue. I was then asked to report said issue here.
I had no problem finding the other NPCs required for the quest and could see/interact with the "Vargul Doombringer" NPCs which inhabit the same area as "Algar the Chosen" during the quest (same phase?). 
I have read all the previously reported bug reports regarding this particular quest.

**What Should happen:**
"Algar the Chosen" should be flying around the platform that teleports players up to the "Voltarus" necropolis in the "Reliquary of Pain" area.

**Comment by wow-mania** [comment]
NPC is there.
