### ISSUE TITLE
[Mount] Stormcrow

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#3368]
**Links:** https://www.wow-mania.com/forum/viewtopic.php?f=16&t=2100

**What is Happening:** The Stormcrow mount acquired with 50 primos does not fly at all. It only acts as a ground mount at the moment.

**What Should happen:** Stormcrow should be a 280% flying mount outside Azeroth. 

> 104011	Stormcrow	A-H	no	280

**Comment by wow-mania** [comment]
Require client update.
Will take a while.
