### ISSUE TITLE
[Quest] Escape Through Force

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#3370]
https://www.wowhead.com/quest=994/escape-through-force

This is an alliance escort quest in Darkshore. The quest begins as soon as one person accepts it, his party members receive a pop up of automatic share "Would you like to start it as well?" so they also receive the quest.

**How it works atm:**
No party credit is given upon completion to those who receive the quest via share.
Only the person who picks the quest directly from the NPC is able to get credit.

**How it should work:**
All nearby party members who are on the quest must receive credit for completion at the end of the escort.

This makes the quest a hassle to complete in a party, as all members need to do it 1 by 1.

PS: the pair of this quest https://www.wowhead.com/quest=995/escape-through-stealth likely has the same issue

**Comment by wow-mania** [comment]
Need confirming now on dev.

**Comment by Dranah** [comment]
This one does not work still.

**Comment by Dranah** [comment]
This is still not working lul

**Comment by wow-mania** [comment]
It will remain as-is. Nothing else can be done for now.

**Comment by Dranah** [comment]
Alright.

**Comment by Rushor** [comment]
all player in 50 yards range will get credit now
