### ISSUE TITLE
[Quest] Therylune's Escape

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#3371]
https://www.wowhead.com/quest=945/therylunes-escape

This is an alliance escort quest in Darkshore. The quest begins as soon as one person accepts it, his party members receive a pop up of automatic share "Would you like to start it as well?" so they also receive the quest.

**How it works atm:**
No party credit is given upon completion to those who receive the quest via share.
Only the person who picks the quest directly from the NPC is able to get credit.

**How it should work:**
All nearby party members who are on the quest must receive credit for completion at the end of the escort.

This makes the quest a hassle to complete in a party, as all members need to do it 1 by 1.

**Comment by wow-mania** [comment]
Need confirming on dev.
