### ISSUE TITLE
Faction Change not working

### ISSUE THREAD

**Issue by Bazran** [WoWManiaUK/Redemption#3372]
**Links:**
![image](https://user-images.githubusercontent.com/52381063/60399503-8635e200-9ba8-11e9-9427-2bab8b03ee06.png)

**What is Happening:**
Bought Faction change through in game mall with 500 Maniac Points, Points were taken from bag but no faction change occured and the button the GM said should've been in this page wasn't showing. Also followed suggestion of Closing completely opening launcher as admin and clearing cache (did this 3 times)

**What Should happen:**
Button should show next to character to change faction.

**Comment by wow-mania** [comment]
Works!
