### ISSUE TITLE
[Boss] Mimiron compilation II

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#3373]
https://www.wowhead.com/npc=33350/mimiron

1) Leviathan MK II melees during Plasma Blast
https://www.wowhead.com/npc=33432/leviathan-mk-ii
https://www.wowhead.com/spell=62997/plasma-blast
The Plasma blast is a channeled ability with a wind up cast time.
During both the cast and the channel, the boss is not supposed to do anything else (only flames can co-occur, as those aren't cast by the Leviathan)
He was already fixed so that he doesn't cast other spells during the channel, but he continues to melee.
**How it should work:** During the Plasma Blast channel, the boss must not melee the tank.

2) Frost bomb cast on imaginary fire
https://www.wowhead.com/spell=64627/frost-bomb
Frost bombs are meant to be thrown where fire is in the room. They are never meant to land in an empty quarter with no fire.
When the room is fire capped, the new fire cannot spawn, but the frost bomb appears to still detect them and be thrown at it. Also might detect flames that were cleared by suppressant before.
This leads to the Frost bomb landing in an empty quarter, taking away the remaining space from raid.
**How it should work:** Frost bomb must not target "invisible" fire (fire that failed to spawn due to fire cap or was cleaned up already)

3) Napalm Shell range check
https://www.wowhead.com/spell=63666/napalm-shell
The spell keeps hitting the melee camp on a regular basis, mostly after running back from a Shock Blast.
Feels like the range check for 15 yards is done way sooner than the spell is actually cast. Might be related to the spell having a 2sec hidden cast time.
However, I have watched a dozen retail videos and saw no precedent of this happening, which means there are 2 options:
Either the range check and target select is supposed to be done when the 2sec hidden cast ENDS, checking for current position at that moment,
Or the boss simply never begins casting Napalm Shell directly after a Shock Blast, so that the melee camp who just ran out is not being selected.
Both options are equally plausible.
**How it should work:** The melee camp should not be hit by Napalm shell in melee range after running back from a Shock blast.

**Comment by Dranah** [comment]
Issue 1 fixed.
Issue 2 persists: i've illustrated the problem
![frost bomb](https://user-images.githubusercontent.com/31132743/60456223-f8560780-9c38-11e9-94ea-7f70725c674e.png)
There used to be fire in that spot before the p1 Flame suppressant.
Issue3 looks fixed by the timer correction.

**Comment by Dranah** [comment]
Phase1 Suppressant now properly despawns fire so frost bomb cant target them anymore.

**Comment by Dranah** [comment]
After some more intense testing, it seems our workaround affected the timers of other spells too.
Something is off with the boss timers since this is released, often the boss begins the fight with casting shock blast and so on. This need further investigation when I have time
@Keader

**Comment by Keader** [comment]
Waiting your informations.

**Comment by Dranah** [comment]
UPDATE:
We have discussed with Keader the timer issues and fixes are under testing.
For reference: 
1) Timer on Shock blast cutting before plasma
2) Timer on Suppressant delayed by p3wx2 laser barrage
3) mimiron non engaging after wiping to p3wx2 laser barrage
