### ISSUE TITLE
Mog bug

### ISSUE THREAD

**Issue by serindari** [WoWManiaUK/Redemption#3374]
**Links:**

**What is Happening:**
item looks weird when mog.

**What Should happen:**
can u fix it ?
![WoWScrnShot_070119_210923](https://user-images.githubusercontent.com/52424434/60457842-b8e1e800-9c45-11e9-8334-6177e9e16afe.jpg)

**Comment by wow-mania** [comment]
This can only be fixed with client update. I will add to list.
