### ISSUE TITLE
[Quest] Leave Nothing to Chance (12277)

### ISSUE THREAD

**Issue by jarvik76** [WoWManiaUK/Redemption#3375]
**Links:**
http://www.wow-mania.com/armory/?quest=12277
http://www.wow-mania.com/armory/?npc=27436
http://www.wow-mania.com/armory/?npc=27437

**What is Happening:**
Both of the mine shaft entrances are blocked as a result of completing quest 12277, they are blocked with "rocks" that I believe are the NPCs named above

This means that quests 12269, 12272 and 12276 cannot be completed, as one cannot get into the mine due to it being blocked by a previous person completing 12277.
http://www.wow-mania.com/armory/?quest=12269
http://www.wow-mania.com/armory/?quest=12272
http://www.wow-mania.com/armory/?quest=12276

![WoWScrnShot_070119_210744](https://user-images.githubusercontent.com/46089380/60463995-4bce5280-9c45-11e9-8ec3-f60bca3dfa43.jpg)
![WoWScrnShot_070119_210832](https://user-images.githubusercontent.com/46089380/60463996-4bce5280-9c45-11e9-88ee-bc989cde662d.jpg)

Raised a ticket in game and GM confirmed they could not seemingly reset the NPCs properly.

**What Should happen:**
The NPCs blocking the mine entrance should despawn, leaving the entrance open.

**Comment by Rushor** [comment]
will fix it
