### ISSUE TITLE
Mog bug again

### ISSUE THREAD

**Issue by serindari** [WoWManiaUK/Redemption#3376]
**Links:**

Flamereaper weapon
**What is Happening:**

this mog bug again

**What Should happen:**
![WoWScrnShot_070119_230809](https://user-images.githubusercontent.com/52424434/60464356-fbf88700-9c56-11e9-9235-4cd7503a08ba.jpg)

**Comment by Kitzunu** [comment]
Which item is it?

**Comment by serindari** [comment]
Flamereaper

**Comment by WhitephoenixTheBunny** [comment]
He means a link, mania armory or wowhead

**Comment by serindari** [comment]
https://www.wowhead.com/acquiring-twinblades-havoc-demon-hunter-artifact#screenshots:abc:17

**Comment by wow-mania** [comment]
Client update.

**Comment by WhitephoenixTheBunny** [comment]
I am making a list of all "wrong xmogs" on artifacts seller... don't kill me
I will make a gereal report for those.
