### ISSUE TITLE
[Transmog] Artifacts items

### ISSUE THREAD

**Issue by WhitephoenixTheBunny** [WoWManiaUK/Redemption#3377]
I have checked all the Artifacts sold by Harrison Jones.

The items with wrong positions / animations are:

Bows:
150208 – acts as a caster (fire) animation
150209 – acts as a caster (fire) animation
150210 – acts as a caster (fire) animation
150113 – miss “shoot” animation 
150211 – miss “shoot” animation 

Guns:
150204 – acts as a shadoweaver craft, animation
150205 – acts as a shadoweaver craft, animation
150206 – acts as a shadoweaver craft, animation
150112 – acts as a shadoweaver craft, animation
150203 – acts as a shadoweaver craft, animation

One Hands Sword
150190 – Inverted, back-front
150191 – Inverted, back-front
150189 – Inverted, back-front
150153 – Inverted, back-front
150187 – should stand on back
150186 – should stand on back
150184 – should stand on back
150185 – should stand on back
150188 – should stand on back
150192 – should stand on back

Fist weapons

150172 – shouldn’t be visible, only when equipped/fighting
150173 – shouldn’t be visible, only when equipped/fighting
150122 – shouldn’t be visible, only when equipped/fighting
150111 – shouldn’t be visible, only when equipped/fighting
150130 – shouldn’t be visible, only when equipped/fighting
150169 – shouldn’t be visible, only when equipped/fighting
150170 – shouldn’t be visible, only when equipped/fighting
150171 – shouldn’t be visible, only when equipped/fighting

**Comment by wow-mania** [comment]
Thanks a lot for that.
I will move this to the client list of issues.
