### ISSUE TITLE
[Dungeon] Culling of Stratholme nm/hc

### ISSUE THREAD

**Issue by WhitephoenixTheBunny** [WoWManiaUK/Redemption#3378]
This dungeon is known to be a long instance, and for having a long roleplay (2 min), making it being "hated" by all players and having people leaving or insta kicking when it pops.

After some research, I have found, that a _role play skip_ option was introduced in 3.3.3:

> Culling of Stratholme
> Players may now skip the initial introduction dialog to this dungeon once they have completed it at least once.

Having this introduced will make rdf/rhc smooter.

Link: https://wow.gamepedia.com/Patch_3.3.3
![image](https://user-images.githubusercontent.com/31921098/60588925-16824b80-9d90-11e9-836b-30e313785b93.png)

**Comment by wow-mania** [comment]
this is a feature request not an issue. Not all features can be faithfully reproduced.

**Comment by Dranah** [comment]
It's a blizzard patch fix. Whether it is cosmetic or not, it's an issue. You can say it is unimportant or cannot be fixed, but you cannot say it isn't an issue.

**Comment by jarvik76** [comment]
As a suggestion for how to approach the fix to this issue, seemingly similar mechanics already exists in Halls of Reflection http://www.wow-mania.com/armory/?zone=4820 and Trial of the Champion http://www.wow-mania.com/armory/?zone=4723

**Comment by Rushor** [comment]
i have a fix for that, need to search

**Comment by Rushor** [comment]
i will bind the script of the intro to quest QUEST_A_ROYAL_ESCORT beeing completed or rewarded.

**Comment by Rushor** [comment]
okay this is how it will work now. @Kitzunu please note this down in some way in the changelog, so people will learn how it works :)

1. You talk to chromie 1 at the entrance. Once you have quest "A Royal Escort" completed (or rewarded), you will see the gossip option to skip the intro. 
![I](https://i.imgur.com/y3vDA6V.jpg)
2. Select it and you will be ported to Chromie 2. 
3. Beeing at Chromie 2 you can select another gossip to skip the intro of arthas. Arthas will then directly start his escortpath.
![I](https://i.imgur.com/JvfoVxi.jpg)

**Comment by Oganku** [comment]
Just did the exact steps of the 'fix' and it just led to Arthas not moving and being unable to talk to Chromie anymore afterwards. Instance got soft-locked and we had to restart. I had the Royal Escort quest completed too.
