### ISSUE TITLE
[Dungeon] Gun'drak 

### ISSUE THREAD

**Issue by volkangul** [WoWManiaUK/Redemption#3379]
**Links:**
http://www.wow-mania.com/armory/?zone=4416

**What is Happening:**
Entrance is starting with Moo'rabi which is wrong.

**What Should happen:**
Entrance should start with the room of Slad'ran ( snakes room ). And the first pack of Cobras ( 3 of them ) should stand still at the entrance of Slad'ran's room 2nd pack of Cobras should patrol.

**Comment by WhitephoenixTheBunny** [comment]
Do you have any link (site / video) where we can check that?

**Comment by WhitephoenixTheBunny** [comment]
I have found this video, 3.3.5 expansion.
https://www.youtube.com/watch?v=6FcUds0gJug

Maybe it starts with another both on another expansion?

**Comment by WhitephoenixTheBunny** [comment]
Players should be summoned to: 
![image](https://user-images.githubusercontent.com/31921098/60592140-e6d74180-9d97-11e9-8bba-06add8d18c0a.png)

**Comment by volkangul** [comment]
There are a lot of Youtube videos if you search like " Gun'drak dungeon ". But you already confirmed. I m trying to report as many as i can things like this. Thank you for your hospitality.

**Comment by wow-mania** [comment]
This is a feature request. Not an issue with existing functionality.

**Comment by WhitephoenixTheBunny** [comment]
But it have some logic, since atm a lot of mobs pack can be skipped.

**Comment by Kitzunu** [comment]
I can also confirm after watching videos from retail wrath that through RDF you should indeed spawn at the snakes, however, a fun fact;

> Gundrak has two entrances, one to the north and one to the south. The northern entrance has the summoning stone outside. The first boss encountered when entering through the north entrance is Slad'ran the serpent boss; if entering through the southern entrance, the first encounter is with Moorabi, the mammoth boss.

**Comment by volkangul** [comment]
The logic is, no level 80's are entering Gun'drak by walking and i remember perfectly there was no available trace route in the dungeon by the vise-versa. If you do the dungeon the current way it also bugs the 2nd boss ( Elemantal-Stone Boss ) you cannot target him like 3-4 seconds. RDF should always starts the players Slad'Ran's room which is snake boss. However i m not the owner of server, just trying to make it blizzlike.

**Comment by Keader** [comment]
Test now please.

**Comment by WhitephoenixTheBunny** [comment]
@wow-mania @Keader I hadnt tested :P just did an rhc, spawned on wrong side

**Comment by Keader** [comment]
i wonder if sql was applied.
Since... it was deployed in same week that alot of fixes was missing in cata.
I will send again this week Angie.

**Comment by WhitephoenixTheBunny** [comment]
thx :)

**Comment by Keader** [comment]
Sql is in PTR.
Please test in PTR and just re-open it if you can reproduce there.

**Comment by WhitephoenixTheBunny** [comment]
@Keader when you die, and go as spirit, you get the worng entrance
