### ISSUE TITLE
Issues with Horde-Infra-Green Bomber related quests

### ISSUE THREAD

**Issue by belgond** [WoWManiaUK/Redemption#3380]
**Links:**
http://www.wow-mania.com/armory/?quest=13374

**What is Happening:**
I linked only one of the quests related, but any quests (there are 3 I believe) that requires you to get into the bomber and shoot flying targets around Icecrown (Gargoyle Ambushers and Frostbrood Sentries) are kind of buggy.
The monsters take damage only when they are outside of the field of vision, probably because the rockets can't detect when they enter the personal space of one of the flying guys just explode at max range.

**What Should happen:**

The rockets should explode on impact, allowing for a far smoother experience.

**Comment by wow-mania** [comment]
as-is. it normally requires multiple passes.
