### ISSUE TITLE
Suspended?

### ISSUE THREAD

**Issue by canttouch420** [WoWManiaUK/Redemption#3381]
**Links:**
i cant get to the help link to post my problem so i had to post it here.

**What is Happening:*
i went to go log into my account today. And it told me i was suspended? but i was logged off for over 7 hours from the time i got home from work i barely ever say anything in world chat and i never disrespect people unless disrespected but i didnt even talk to anyone this morning at 2:30 est USA time. And everytime i go to log in its telling me im suspended? WHY?  i follow all rules ect. 
**What Should happen:**
i really want my account un suspended because i have done nothing wrong I have been wornged and all i do is donate and play for fun.

**Comment by WhitephoenixTheBunny** [comment]
Not an issue to github
