### ISSUE TITLE
Icecrown Citadel BROKEN

### ISSUE THREAD

**Issue by Oliver525** [WoWManiaUK/Redemption#3383]
**Links:**

**What is Happening:**
Some trash/all trash is hitting WAY too hard.
Marrowgar is hitting for 30k
Big ooze hits for roughly 75k (icc25nm)

**What Should happen:**
Trash shouod hit for less.
Marrowgar used to hit for 8-10k
No idea what the big ooze should hit for

**Comment by Oliver525** [comment]
I only tested this in icc25nm, though, it’s the same in icc10nm from what I’ve heard. Idk about HC. After doing icc25nm with the broken ICC I haven’t bothered to play.

**Comment by wow-mania** [comment]
AS-IS damages changed for now.
