### ISSUE TITLE
[Raid] ICC 

### ISSUE THREAD

**Issue by crulinjr** [WoWManiaUK/Redemption#3384]
How it is working: Bosses and even trash on ICC are doing way too much damage compared to last week. Tanks are getting 2 shot at Marrowgar or 1 shot by Shambling Horrors at LK for example. 

How it should work: Bosses and trash should be doing less damage. This should be looked upon.

**Comment by wow-mania** [comment]
Please search before posting.

**Comment by crulinjr** [comment]
Search where?
