### ISSUE TITLE
Race Condition causing deadlock on trade

### ISSUE THREAD

**Issue by helperdude** [WoWManiaUK/Redemption#3386]
**Links:**

**What is Happening:**

When two players trade almost simultaneously (i.e Both players send a request before the server has time process them), both players end in a deadlock where they can't trade until either:
a) One walks away to a different zone to cause different instancing;
b) One logs out.
c) Trade session times out.

As I don't have the actual code, all I can do is make the following assumptions:
1. There's a mutex in place to ensure only one trade window can be opened at once on the client side.
2. A thread is created to handle trades.
    a. Only one of these threads can exist at any time.
3. A mutex is locks the thread upon the following conditions:
    a. A trade is sent;
    b. A trade is received.
4. The mutex is only unlocked when the window closes, i.e those mentioned above in addition to a successful trade.

What I assume is happening is that before the player knows if the trade window was opened, the mutexis locked. (This issue can also occur if this is done on the main thread, i.e step 2 is not done, which also means assumption 2.a is false).

It is worth noting that if the code used pthread_mutex_lock(), the thread will remain locked until the mutex can be acquired. And if assumption 2 is true, this means that until either the code executes or the thread is destroyed, the player cannot initiate another trade.

**What Should happen:**

Players shouldn't need to have to worry about trading simulateneously. Since this is a race condition, a mutex on the server side should be acquired whenever a trade request is sent and released once it is received.

Here should be the general lines in terms of the communications:

1. Player A sends a requests to trade with player B to Server.
2. Server receives requests. 
3. The server attempts to lock player B (server side) trade mutex. 

If step 3 fails, then return failure to player A. This step failing means player B is already trading or has send a request already (both should be the same state imo).

4. The server attempts to lock player A (server side) trade mutex (This should never fail as the client is already sending a request, which means a trade is not already opened, some checks can be added to ensure it is the case).
5. Server sends open trade window to both clients.
6. Client receives open window request, they attempt to lock client trade window mutex and proceed normally as they would to open a trade.

When releasing Resources, it is detrimental that the following is done:
Player A trade window mutex unlocked (Client and Server side)
Player B trade window mutex unlocked (Client and Server side).
If it is not done, it will cause the issue to occur.

**Comment by helperdude** [comment]
Submitted before completing ticket. Will re-open once finished.

**Comment by helperdude** [comment]
Finished editing, re-opening the issue.

**Comment by Dranah** [comment]
I can confirm this happening, not a game breaker but super damn annoying.
