### ISSUE TITLE
The map doesn't work well

### ISSUE THREAD

**Issue by Mageone** [WoWManiaUK/Redemption#3387]
**Links:**
Hello,
I'm in Shattrath now, i do right click on the map to see Hellfire, the map shows me Shattrath.
I do right click on the map and i choose Nagrand, the map shows me Nagrand. Only Nagrand and Terokkar Forest are showed on map. All the other zones from Outland are not showed, the map  returns to Shattrath back. I tried to see Azeroth, i did right click on the map, but after i saw Outland then it turned me back to Shattrath.
The map works normal only maximised, but even so not always. For some quests are showed only the zone where i am. 
It's same problem in Azeroth, too. I can't see Outland, i can't see many zones when the map isn't maximised.
I talked with a GM and he told me that he had same problems as me...
Sorry for my english, it isn't my native language.

Best regards
Mageone
**What is Happening:**

**What Should happen:**

**Comment by Dranah** [comment]
This is for sure client or addon issue, it isnt something general. Try to install a different quest or map addon.

**Comment by Mageone** [comment]
I did with the support of GM more things before i posted here. I disabled all my addons, i did D|elete of Cache folder, i did Update again and logged in with the Launcher and still nothing changed. 
I don't know why Janitor closed this topic. Maybe my problem wasn't clear showed here, i don't know....
