### ISSUE TITLE
[Investigate The Blue Recluse] (Quest)

### ISSUE THREAD

**Issue by TheRealEpep** [WoWManiaUK/Redemption#3389]
**Links:**
https://gyazo.com/87e1a05a6fe099357040a5115a980eff

**What is Happening:**
Hey Gms, I have noticed a bug on the quest called ''Investigate The Blue Recluse'' Which is a mage quest I'm pretty sure but I needed to fill 0/3 filled containment coffer but once I use the quest item (Chest Of Containment Coffers) to fill the coffer it does nothing just places it down, Nothing else.. and when I got confused and tried to search up a guide on how to do it but one of the videos I saw said it was buggy so I suspected it was bugged   

**What Should Happen:**
Should fill up the coffers 3/3 please fix it Gms

**Comment by wow-mania** [comment]
Works.

**Comment by WhitephoenixTheBunny** [comment]
Just did in Redemption 
Worked fine
![image](https://user-images.githubusercontent.com/31921098/61189118-ad98ae80-a680-11e9-97e7-4b6022e0fee3.png)

You need use the [Cantation of Manifestation](http://www.wow-mania.com/armory/?item=7308) the rift will spawn, you attack him to stun, then you use [Chest of Containment Coffers](http://www.wow-mania.com/armory/?item=7247) and then click on it.

![image](https://user-images.githubusercontent.com/31921098/61189146-24ce4280-a681-11e9-8a79-b097a327d325.png)
