### ISSUE TITLE
 [What Came First, the Drake or the Egg?]

### ISSUE THREAD

**Issue by agris91** [WoWManiaUK/Redemption#3390]
**Links:**
https://www.youtube.com/watch?v=YwPFtU18JLw

**What is Happening:**
Quest bug, targets from egg are green , cant kill em

**What Should happen:**

**Comment by agris91** [comment]
Or on this server this quest is doing diferently?

**Comment by wow-mania** [comment]
Pretty sure it works.

**Comment by agris91** [comment]
and how to get essence if they are green? from eggs?

**Comment by agris91** [comment]
yea, i get it, i have to put in reaputation  at war ,

**Comment by agris91** [comment]
its just a glich   (netherwing)   you cant do it if you are exalted whis them lol

**Comment by agris91** [comment]
i completed it , but some other people may have problems to do it, if they dont now that they have to whis netherwing  status ( at war)
