### ISSUE TITLE
Worgen & Goblin player corpse skeleton texture missing

### ISSUE THREAD

**Issue by Marshmllw** [WoWManiaUK/Redemption#3392]
**Links:**
https://1drv.ms/u/s!Av8QC4Nsxqf6n3G_hbCpTT_-jWHC?e=aeTqSf

**What is Happening:**
The skeleton graphics are not shown when corpse is retreived

**What Should happen:**
The skeleton graphics should be shown when corpse is retreived

![WM-Graphic-Corpse-Glitch](https://user-images.githubusercontent.com/52990984/61350119-c19e0500-a866-11e9-8c97-b2d548afa8a7.png)

**Comment by wow-mania** [comment]
I need the NPC name or link.
This is a problem with your client.

**Comment by Marshmllw** [comment]
> I need the NPC name or link.
> This is a problem with your client.

This is not an NPC, this is my character 'skeleton' after respawning.

**Comment by WhitephoenixTheBunny** [comment]
Goblins and Worgens don't have "skeletons" after ressed, they are added races, some features be missing... Maybe WoW Mania can work on it for a next patch, but not sure.

**Comment by Marshmllw** [comment]
Hello,

That was a real facepalm moment on my end, reading your comment made me realize that Goblins where not originally in WOTLK and just looked it up, they where added in Catalysm.
Thanks for the info and update.

Met vriendelijke groet,

Dwayne Jurcka

________________________________
Van: Phoenix <notifications@github.com>
Verzonden: woensdag 17 juli 2019 11:37
Aan: WoWManiaUK/Redemption
CC: Marshmllw; Author
Onderwerp: Re: [WoWManiaUK/Redemption] Skeleton/Corpse graphics missing (#3392)


Goblins and Worgens don't have "skeletons" after ressed, they are added races, some features be missing... Maybe WoW Mania can work on it for a next patch, but not sure.

**Comment by jeyrella** [comment]
GM Aymelek will check to see if this player corpse skeleton texture can be added for Goblins & Worgens

**Comment by fvicaria** [comment]
This should have been fixed now. Please confirm and close the issue.

**Comment by GMZinius** [comment]
Thank you @fvicaria 
Confirmed fixed
