### ISSUE TITLE
Worgen cat form 

### ISSUE THREAD

**Issue by Maliban** [WoWManiaUK/Redemption#3393]
**Links:**
https://www.wowhead.com/worgen-druid-forms

**What is Happening:**
Cat form is stuck in low resolution - brown color despite fur/hair color of Worgen. Bear form works normally.

**What Should happen:**
Cat form should change just like bear form, color change with hair color. Also resolusion need to be same like other forms.

**Comment by WhitephoenixTheBunny** [comment]
About the resolution, I don't see it:
![image](https://user-images.githubusercontent.com/31921098/61368415-b60e0680-a885-11e9-999c-52b09829d6b5.png)
![image](https://user-images.githubusercontent.com/31921098/61368464-cf16b780-a885-11e9-9435-3c88b5543f33.png)

About the fur color, on barber shop, we have the option "hair color" but no change on worgen / cat 
![image](https://user-images.githubusercontent.com/31921098/61368627-36346c00-a886-11e9-9f17-f1f55f171440.png)

**Comment by Maliban** [comment]
If that color bug can be fixed? I saw raport about this from 2017... Reply was that this can be fixed with next pach but it was two years now.

**Comment by WhitephoenixTheBunny** [comment]
That will be looked into by Janitor.

**Comment by WhitephoenixTheBunny** [comment]
I believe this is the report https://github.com/WoWManiaUK/Redemption/issues/1140

**Comment by Maliban** [comment]
Thank You for reply, I hpoe You can resolve this problem.
