### ISSUE TITLE
[QUEST]Basic Chemistry

### ISSUE THREAD

**Issue by Necko23** [WoWManiaUK/Redemption#3394]
**Links:** https://www.wowhead.com/quest=13279/basic-chemistry

**What is Happening:** Once you use Pustulant Spinal Fluid on cauldron a text pops up:"The plague cauldron begins to boil vigorously!" and then "Something emerges from the cauldron!". Once you kill those mobs, that's it. I've contacted GM Zinius and we tried to solve it. I abandoned the quest, closed the launcher, opened it again, cleared cache and took the quest again. This time minor changes happened: "The plague cauldron begins to boil vigorously!" and then "Something emerges from the cauldron!" and this time nothing emerged but text popped up "Plague batch neutralized!" except the quest wasn't completed.

**What Should happen:** https://www.youtube.com/watch?v=HvO7ZRdkyhA There should be wave of mobs, altho I think you guys made it so they don't spawn just so people don't get bored by that quest, batch should be neutralized but that isn't happening

GM Zinius advised me to report it over here, hence he thinks it's bugged.

With regards.

**Comment by Oganku** [comment]
This quest works. I have done it multiple times.

I always used the cauldron on the left as you enter the big building, dunno if that matters though.

You just gotta use the spinal fluid, wait for it to spawn a couple ghouls and kill them. And then when the fluid is ready again, use it again.

**Comment by Necko23** [comment]
Oganku I tried more than 6 times, which after I contacted a staff member.

**Comment by wow-mania** [comment]
Ques works. 2 things to keep in mind. The reaction is a probability, to a certainty so you have to keep trying.

**Comment by Dmw1981** [comment]
been in there over an hour all the videos show it still bubbling yellow when the next batch is done. that IS NOT happening
