### ISSUE TITLE
Quest "The Plains of Nasam"

### ISSUE THREAD

**Issue by jcheckett25** [WoWManiaUK/Redemption#3395]
**Links:**
http://www.wow-mania.com/armory/?quest=11652

**What is Happening:**
The first ability on the Horde Siege Tank fires, but the projectile b-lines to somewhere predefined. Kind of like it's set to 0,0. It doesn't actually fire at the spot one would be aiming at. 
The other abilities seem to work just fine.

**What Should happen:**
Horde Siege Tank should fire at the point being aimed at. Like 45,48 BoreanTundra.PlainsofNasam, (or w/e you use for naming)

**Comment by wow-mania** [comment]
Works.

**Comment by jcheckett25** [comment]
![WoWScrnShot_071919_170609](https://user-images.githubusercontent.com/51798254/61568194-e30a1700-aa47-11e9-9657-1de1ebffa7a1.jpg)
![WoWScrnShot_071919_170617](https://user-images.githubusercontent.com/51798254/61568204-ea312500-aa47-11e9-903b-9911972d76d3.jpg)
![WoWScrnShot_071919_170640](https://user-images.githubusercontent.com/51798254/61568210-f3ba8d00-aa47-11e9-884f-9a05dae203cb.jpg)
![WoWScrnShot_071919_170644](https://user-images.githubusercontent.com/51798254/61568215-f917d780-aa47-11e9-9687-4b19c8357071.jpg)

**Comment by jcheckett25** [comment]
![WoWScrnShot_071919_170609](https://user-images.githubusercontent.com/51798254/61568462-fa95cf80-aa48-11e9-9866-ddeefb3ccfd1.jpg)
![WoWScrnShot_071919_170617](https://user-images.githubusercontent.com/51798254/61568464-fcf82980-aa48-11e9-9e88-ee5f1452f64c.jpg)
![WoWScrnShot_071919_170640](https://user-images.githubusercontent.com/51798254/61568467-008bb080-aa49-11e9-8809-207c0c36d52f.jpg)
![WoWScrnShot_071919_170643](https://user-images.githubusercontent.com/51798254/61568470-0386a100-aa49-11e9-9308-e6f61b2af726.jpg)
![WoWScrnShot_071919_170644](https://user-images.githubusercontent.com/51798254/61568473-06819180-aa49-11e9-8205-ac8b09e46703.jpg)

**Comment by Echinaceax** [comment]
@wow-mania quest tested and completed

![complete2](https://user-images.githubusercontent.com/39439201/61577199-43e72d00-aae4-11e9-9339-3ff685ae304c.jpg)


@jcheckett25 use buttons 2 and 4 :)
![these](https://user-images.githubusercontent.com/39439201/61577187-24500480-aae4-11e9-8f11-06f18ecd1bde.jpg)
