### ISSUE TITLE
Dungeon Finder bug

### ISSUE THREAD

**Issue by Triise** [WoWManiaUK/Redemption#3396]
**Links:**

After clearing a dungeon, reque with the same group sends you back into the same dungeon lock out. This starts the dungeon finder CD for everyone in the group, and the dungeon is still clear on the same ID. Also if you then try to disband that group then regroup and que after the dungeon finder CD is done, you get the 30m deserter punishment, and the group can't que again until it's gone.

**What Should happen: You should be able to reque with the same group after a dungeon is clear into a new dungeon ID even if the same dungeon in the rotation gets selected using random dungeon finder. 

The only work around that I didn't get to try yet, is to leave the current group and dungeon after it's clear, then que for a new group. But this shouldn't be necessary

**Comment by Keader** [comment]
This is a hard one.
I just can look again in week end :(

**Comment by Keader** [comment]
Ok, i lost good part of day in this issue yesterday.
I cant find a way to fix it.
I try do some hacks to fix it, but no success.
It just not respawn nothing if map is the same.
Work fine in diff map. Only way of reset it is doing a new group.
I dont plain lose more time on it, core developers should rewrite lfg queue in future, i will try again when they do it.
