### ISSUE TITLE
Need/Greed roll malfunction

### ISSUE THREAD

**Issue by zombabe** [WoWManiaUK/Redemption#3397]
I was part of a random dungeon finder group running Violet Hold. A necklace dropped that I rolled need on, but when the system rolled it did not include my roll. The item ended up going to a greed roll. I talked to Fairwinds regarding this who advised me to submit the issue here. Please advise if there is anything more you need me to do. Thanks!
![greed roll](https://user-images.githubusercontent.com/53150804/61594562-d950f280-abb2-11e9-9bc8-6c63b21c94db.jpg)
![selected need](https://user-images.githubusercontent.com/53150804/61594563-d950f280-abb2-11e9-95ec-2dc8b34a4c87.jpg)

**Comment by Keader** [comment]
Tested now in PTR and working fine.
Items rolled with Need has more priority then Greed.
