### ISSUE TITLE
[Spell/DK] Glyph of Death and Decay

### ISSUE THREAD

**Issue by Keader** [WoWManiaUK/Redemption#3401]
Not adding 20% more damage in death and decay.

**Comment by Oganku** [comment]
I've heard before that the tank DK 2t10 bonus that should grant +20% damage to dnd, just like the glyph, did not work. I have no evidence for this but I'm simply wondering if the 2 20% buffs (from glyph and tier) could be related. 

Sorry if this isn't a good place to ask.
