### ISSUE TITLE
[Achievement] Staying Buffed All Winter 25man

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#3405]
Achiev ID 2970

Achievement is not given when the criteria is completed. Was fixed way back, supposedly something reverted it. 
The 10man version works fine.

How it should work:
Achievement must be granted when the criteria is completed.

**Comment by Dranah** [comment]
Still does not work.

**Comment by Keader** [comment]
janitor reverted it. should be back tomorrow dranah
