### ISSUE TITLE
[NPC] Mindless Aberration

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#3406]
NPC ID 25469

These are adds spawned during the quest "The Plains of Nasam" Quest ID 11652
They are thrown on the ground from the Scourge plague spreaders ( NPC ID 25349), which hover in the air.
The problem is, these Mindless Aberrations are all glitched in a sense, they aren't actually on the ground and cannot be attacked by the vehicles. They are visually on the ground, but actually still up in the air where the plague spreaders are.

The problem here is, that without these NPCs being killable, there are way fewer than 100 to kill for the criteria and players need to wait multiple waves of respawn to complete the quest.
The quest is doable, but takes way longer than intended, thus most players skip it.

How it should work:
Mindless Aberrations should actually be on the ground after they are spawned, not only visually.

**Comment by wow-mania** [comment]
Please check.
