### ISSUE TITLE
Skull of the Man'ari not showed right

### ISSUE THREAD

**Issue by Mageone** [WoWManiaUK/Redemption#3409]
Hello,
I bought today a Skull of the Man'ari to transmogan Off-hand item. Item 150141 . It worked fine.
But the skull doesn't look as in all the websites about WoW stuff, no flames of any color, sometimes appears for short time something and disappears, the skull is showed only when i press the key to unsheathe the weapon, but it should be showed as default all the time when i walk, fly or ride a mount. It's so undistinguished that even the Ghostly Skull pet is prettier and more interesting than this one.
Any chance to have a better Skull, please? The character is gnome, mage.
Thanks!

![Clipboard011](https://user-images.githubusercontent.com/49594781/61801662-d6b2ff00-ae37-11e9-80ab-23abb399e3e7.jpg)
![Clipboard022](https://user-images.githubusercontent.com/49594781/61801675-dadf1c80-ae37-11e9-9374-04bc123eb60a.jpg)
![Clipboard033](https://user-images.githubusercontent.com/49594781/61801687-df0b3a00-ae37-11e9-90e7-d590b9cf8260.jpg)
![Clipboard044](https://user-images.githubusercontent.com/49594781/61801697-e29ec100-ae37-11e9-9628-489b9d46dc56.jpg)

**Comment by wow-mania** [comment]
As is. Imported items from other versions have not obligation to conform.

**Comment by WhitephoenixTheBunny** [comment]
@Mageone you have a link showing it should be visible when mounting? i cant find anything on google
only find the flames

![image](https://user-images.githubusercontent.com/31921098/61812909-665aac80-ae3c-11e9-9d8b-a932145df553.png)

**Comment by Mageone** [comment]
Hello,
Sure i can! That made me buy this item! You can see many characters from movies walking and flying mounts...

[https://www.youtube.com/watch?v=TQAYB3fXRqo](url) time 22' 22''

[https://www.youtube.com/watch?v=WEI30N6w4ro](url) time 21' 40''

[https://www.youtube.com/watch?v=zI-jea1IIUc](url) time 1" 

It's true that it's not possible to see it all the time and with better image than now, then i would prefer to get refund. I got what even in Armory website isn't showed like now. I hoped to get what in WoW websites they described, not something silly...

**Comment by WhitephoenixTheBunny** [comment]
I will let here the SS from videos:
![image](https://user-images.githubusercontent.com/31921098/61824242-6adf8f00-ae55-11e9-898e-52956e3b8b36.png)
![image](https://user-images.githubusercontent.com/31921098/61824324-9e221e00-ae55-11e9-9ea1-818102e6d1de.png)

This is another weapon, but should act as same:
![image](https://user-images.githubusercontent.com/31921098/61824398-c90c7200-ae55-11e9-8315-17cab307d916.png)
![image](https://user-images.githubusercontent.com/31921098/61824444-e80b0400-ae55-11e9-8973-55d079e8a892.png)

As @wow-mania said, not features can be added... but let's keep hope
