### ISSUE TITLE
[Server/PVP] PVP turns off after some time automatically

### ISSUE THREAD

**Issue by S-h-i-n-i-g-a-m-i** [WoWManiaUK/Redemption#3410]
**What is Happening:**

after you enable pvp it automatically gets disabled 
the option to turn it on still says enabled but you cant pvp
this resets if you disable and enable pvp again but the same thing keeps on repeating

**What Should happen:**
pvp should stay on forever unless turned off manually
![Captureee](https://user-images.githubusercontent.com/44024402/61807087-7d0dfd00-ae56-11e9-873e-d2a28028c9a9.PNG)

**Comment by wow-mania** [comment]
As-is. It will depend on a timer and on the regions and areas that you cross.

**Comment by WhitephoenixTheBunny** [comment]
@wow-mania that's the inverse situation...
It seems it disable the pvp and not enable it

**Comment by S-h-i-n-i-g-a-m-i** [comment]
> @wow-mania that's the inverse situation...
> It seems it disable the pvp and not enable it

might be the case .. it also happens if i log off and log on

**Comment by Echinaceax** [comment]
@wow-mania- tested and confirmed. Pvp disabled on log out too, 

If a player enables their own pvp status it shouldnt disable until you chose to disable it yourself

**Comment by WhitephoenixTheBunny** [comment]
When you turn pvp you get this:
![image](https://user-images.githubusercontent.com/31921098/61814496-20074c80-ae40-11e9-851d-c8b182bffbb0.png)

![image](https://user-images.githubusercontent.com/31921098/61814520-28f81e00-ae40-11e9-8c1c-b4759dd3b55a.png)

After relog: 
![image](https://user-images.githubusercontent.com/31921098/61814622-5d6bda00-ae40-11e9-9169-ead0db69e8f1.png)

![image](https://user-images.githubusercontent.com/31921098/61814751-a91e8380-ae40-11e9-849c-607bea8ed756.png)

And checking with a horde, to be sure I am unattackable
