### ISSUE TITLE
Wow-mania: Shop Issue

### ISSUE THREAD

**Issue by Tktoast** [WoWManiaUK/Redemption#3411]
I've been directed to emailing my issue to the GM, specifically Janitor. 

I've purchased items on your site with no problem in the past. When attempting to purchase Deathbringer's Will it doesn't direct me to the Paymentwall. This is the only item on the list that I've run into this problem with. 

https://wow-mania.com/rewards

**Comment by WhitephoenixTheBunny** [comment]
You need contact janitor on discord or mail.. not here

**Comment by Tktoast** [comment]
Okay.

**Comment by Tktoast** [comment]
I wouldn't of created a thread if I had his email..

It's not on the site.. eitehr I'm blind (which is very possibly, my wife
thinks so) or the site is lacking some informatino.
