### ISSUE TITLE
[NPC} Enemy Casters

### ISSUE THREAD

**Issue by Triise** [WoWManiaUK/Redemption#3412]
**What is Happening:** After interrupting enemy casters they just stand there until they can start casting again, making some dungeon pulls for challenging than they should be.

**What Should happen:** Caster NPC's should run to the person with aggro and try to melee, until they can cast again after being interrupted.

**Comment by wow-mania** [comment]
As-is.

**Comment by Dranah** [comment]
@Triise some casters work fine, some do not. It cannot be fixed in general,therefore cannot do much with this report. 
If there is a specific pull that is bothering players, report that one type of NPC and perhaps the devs can correct that one in particular.

**Comment by Triise** [comment]
Ok, I will wait until I am 80 and see what ones are those most important, I
guess. Won't be long. Thanks
