### ISSUE TITLE
[NPC] Garrosh Hellscream

### ISSUE THREAD

**Issue by Triise** [WoWManiaUK/Redemption#3419]
![WoWScrnShot_072819_084603](https://user-images.githubusercontent.com/52584736/62009851-6bf41300-b118-11e9-8c60-ffeb6ec3e219.jpg)
**Links:**https://www.wowhead.com/npc=25237/garrosh-hellscream#starts

**What is Happening:** When you first arrive in Warsong Hold, Garrosh Hellscream shows the ! as if he has a quest, but does not have a quest yet.

**What Should happen:** Garrosh should not show ! until he has a quest to give.

**Comment by wow-mania** [comment]
this means you have some conditions not filled in

**Comment by Dranah** [comment]
It's a visual issue, yellow exclamation mark should always mean you already meet all the conditions to pick up a quest. In this case, it shows a quest that is yet to be unlocked (need to complete other quests first). At this stage, no mark should show above his head yet.

**Comment by Dranah** [comment]
The two quests with wrong visual display are
1) "The defense of Warsong hold" QUEST ID=11596 from High Overlord Saurfang, which unlocks after you handed in "Hellscream's Vigil", but shows the exclamation mark sooner than being unlocked.
2) "Reinforcements Incoming" Quest ID=11618 from https://www.wowhead.com/npc=25237/garrosh-hellscream which unlocks after handing in "Message to Hellscream" QUEST ID=11616, but shows the exclamation mark without any quest done.

**Comment by Rushor** [comment]
'Quest \'The Defense of Warsong Hold\' requires quest \'The Lord of Blackrock\' NOT rewarded O
'Quest \'The Defense of Warsong Hold\' requires quest \'Bang a Gong\' NOT rewarded OR'),
 'Quest \'The Defense of Warsong Hold\' requires quest \'Hellscream\'s Vigil\' rewarded OR'),
'Quest \'The Defense of Warsong Hold\' requires quest \'The Lord of Blackrock\' NOT rewarded')
'Quest \'The Defense of Warsong Hold\' requires quest \'Bang a Gong\' NOT rewarded'),
 'Quest \'The Defense of Warsong Hold\' requires quest \'Hellscream\'s Vigil\' rewarded'),

"Only show quest Reinforcements Incoming if Message to Hellscream is rewarded"),

conditions added

**Comment by Dranah** [comment]
There's no change on this one. Still shows the exclamation marks before quests become available.

**Comment by Rushor** [comment]
which quest exactly?

**Comment by Dranah** [comment]
I have listed both quests
"The defense of Warsong hold" QUEST ID=11596 
"Reinforcements Incoming" Quest ID=11618

**Comment by Rushor** [comment]
ah there is another quest 11595 which needs to be hiddne with conditions

**Comment by Bathelmo** [comment]
the question mark could be just an aura or a visual id enforced

**Comment by Dranah** [comment]
@Rushor is there any progress on this one?

**Comment by Kitzunu** [comment]
There are more npc's with this issue, which has been ignored before.

I have been trying to figure out, to why it would show even though the requirements are not met, but so far I have no luck

**Comment by Kitzunu** [comment]
This could possibly be a core issue since it happens to more npc's

**Comment by Kitzunu** [comment]
@Keader could you check if there is anything in the core that could cause the ! to show as yellow even though you don't meet the requirement for the quest?

**Comment by wow-mania** [comment]
Will stay as is. This is visual only.

**Comment by Rushor** [comment]
@Kitzunu any news on that?

**Comment by Kitzunu** [comment]
No, afaik it is generic. 
But I do remember seeing TC fixing something like this. Maybe you could look, or I if I find time

**Comment by Kitzunu** [comment]
Fixed
