### ISSUE TITLE
[Spell] Drak'Tharon Keep

### ISSUE THREAD

**Issue by Triise** [WoWManiaUK/Redemption#3421]
**Links:**https://www.wowhead.com/npc=26632/the-prophet-tharonja#abilities

**What is Happening:**Prophet Tharon'ja casts Decay Flesh, shapeshifting all party members, When he casts Return Flesh to return players to normal forms, Warrior Stances are set to no stance.

**What Should happen:** Return Flesh should not remove stances, they should remain the same as they were when the players are transformed from normal.

**Comment by wow-mania** [comment]
as-is for now. I think I mentioned this before.
