### ISSUE TITLE
[Quest] The Coldhearted - Speed of vehicles

### ISSUE THREAD

**Issue by Creedpt** [WoWManiaUK/Redemption#3422]
**Links:** https://www.wowhead.com/quest=12856/cold-hearted

**What is Happening:** Once we get the protodrake i cant go down or up and the speed of the protodrake itself its way to slow

**What Should happen:** It should  go up and down ( afterall you need it for quest) and the speed should be faster.

**Comment by Oganku** [comment]
Tap spacebar once, the maneuvering will be fine after.

**Comment by wow-mania** [comment]
works. and please search before posting.

**Comment by Rushor** [comment]
will incewase the normal speed a bit https://www.youtube.com/watch?v=y25EOTX0M-Q according to that retail video 

https://gyazo.com/c9e303d8f1f0528664ca4b9cf71bf93c
