### ISSUE TITLE
Cant play, same problem again

### ISSUE THREAD

**Issue by Votrubic** [WoWManiaUK/Redemption#3423]
**What is Happening:**
I turn on wow.exe. Write my name and password and continue on my characters. I choose one, It doesn´t matter which and the loading screen came next. The bar of loading screen goes until the end, when It´s done it returned on the screen where is name and password and told me: you have been disconected from the server. So I can´t play at all, because It doesn´t let me in the game on my character. My friend told me, that he see me online on a sec. and then i went offline..

What Should happen:
Turn on wow.exe. Logg in. Choose character. Wait until the loading screen bar goes until the end. And then I´ll be on my character and I can play.

**Comment by Votrubic** [comment]
I had this problem after yesterdays restart server. It was at 12 am.

**Comment by WhitephoenixTheBunny** [comment]
Not an issue for github. Contact Janitor or a GM.
btw you need use Mania Launcher ALWAYS.
