### ISSUE TITLE
[Spell] Penance ID 47750

### ISSUE THREAD

**Issue by Drostthehunter** [WoWManiaUK/Redemption#3424]
**Links:**
http://wow-mania.com/armory/?spell=47750

**What is Happening:**
The recent fix is somehow reverted, still manages to fail 3rd tick of penance and bugs out when used alongside with levitate spell.

**What Should happen:**
Recent fix should be revereted apperenetly.

**Comment by wow-mania** [comment]
then reference original issue

**Comment by Dranah** [comment]
https://github.com/WoWManiaUK/Redemption/issues/3308
