### ISSUE TITLE
[Mount BoA] Black Riding Goat

### ISSUE THREAD

**Issue by Dioden101** [WoWManiaUK/Redemption#3425]
**Links:**

**What is Happening:** I bought the new VIP mount, and when i learned it, it vanished, talked to a GM ingame and was told to report it here.

**What Should happen:** Mount should stay in your bag when you learn it, so you can send it to your other toons.

**Comment by WhitephoenixTheBunny** [comment]
Tested on dev:
![image](https://user-images.githubusercontent.com/31921098/62291768-aa613900-b45c-11e9-93e7-af3dda4c5d67.png)

**Comment by WhitephoenixTheBunny** [comment]
Mount : http://www.wow-mania.com/armory/?item=89391
