### ISSUE TITLE
[Item] Pygmy Suckerfish

### ISSUE THREAD

**Issue by WhitephoenixTheBunny** [WoWManiaUK/Redemption#3426]
The item [Pygmy Suckerfish](http://www.wow-mania.com/armory/?item=40199) have atm a droprate of 10% everywhere (schools and open sea)

[Open Sea](http://www.wow-mania.com/armory/?item=40199#fished-in-zone)
![image](https://user-images.githubusercontent.com/31921098/62312750-e8735280-b486-11e9-89e4-4f32770041df.png)

[Schools](http://www.wow-mania.com/armory/?item=40199#fished-in-object)
![image](https://user-images.githubusercontent.com/31921098/62314027-0db59000-b48a-11e9-8b9e-b1c887a834a0.png)

But it should be arround 75% on schools after patch 3.0.8 and 10% on open sea.

[Link](https://wowwiki.fandom.com/wiki/Patch_3.0.8_(undocumented_changes))

![image](https://user-images.githubusercontent.com/31921098/62313820-9122b180-b489-11e9-828f-52ed9ac2e3d8.png)

[Previous information](https://wowwiki.fandom.com/wiki/Pygmy_Suckerfish)

> Pygmy Suckerfish are primarily caught from the schools of fish found in Northrend but have a smaller chance to be found in open water. Schools of fish, with the exception of Crystalsong Forest have about a 65% chance to drop suckerfish, while open water has about a 10% chance. Note that the suckerfish is an adittional catch to the fish you catch from the school or body of water, you will never catch a pygmy suckerfish alone.

![image](https://user-images.githubusercontent.com/31921098/62313924-cc24e500-b489-11e9-858e-5cd8b97d2dfd.png)

The droprate should remain as 10% on Open Sea, and change from 10% to ~75% on schools of fishes

**Comment by wow-mania** [comment]
Armory will take a while to update. Maybe a day or 2.
