### ISSUE TITLE
[Spell/NPC] Immortal Guardians' Drain Life

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#3427]
https://www.wowhead.com/spell=64160/drain-life
cast by https://www.wowhead.com/npc=33988/immortal-guardian

Damage of the spell is incredibly high, probably scales in wrong direction with the guardians https://www.wowhead.com/spell=65294/empowered buff.
**How it should work:** the max damage of the spell is meant to be 3,3k/sec ticks on 10man, and as the guardians lose health, the damage should decrease further.
**How it works atm:** it seems to scale up with the 9 stacks up to 30k/sec damage at full health, 16-20k at average, both ways one shotting players if you fail to interrupt it before the first tick happens.
The healing is also off, it should heal 33k/sec by default, and while i'm not sure that the stacks should anyhow reduce this healing, it's currently healing 80-90k per tick at avg, which is definitely off the roof.

Video proofs:
https://www.youtube.com/watch?v=pnrSVREmmWQ
https://www.youtube.com/watch?v=pviyYZAvyyQ

**Comment by Dranah** [comment]
It only does 2k/tick now and doesnt heal the guardian at all.

**Comment by Keader** [comment]
heal is working fine.

**Comment by Dranah** [comment]
Confirmed fix on 10man, however this needs correcting on 25m too.
