### ISSUE TITLE
[Dungeon/Boss] Hellfire Ramparts

### ISSUE THREAD

**Issue by tvshadowz** [WoWManiaUK/Redemption#3428]
**Links:**  
http://www.wow-mania.com/armory/?npc=17537

**What is Happening:**
Currently the Dragon will come down and Vazruden will jump off and dissapear. The dragon will then take off again and only rDPS can take it down for the loot from the dragon. 

**What Should happen:**
The group should kill the drake with Vazruden riding it, once the drake is down Vazruden should jump off to be killed next.

**Comment by wow-mania** [comment]
Need someone to reproduce this.

**Comment by tvshadowz** [comment]
Want me to run ramparts again with a different group?

**Comment by wow-mania** [comment]
Tried and cannot reproduce.
