### ISSUE TITLE
[Spell] Bloodlust / Heroism

### ISSUE THREAD

**Issue by Loktard** [WoWManiaUK/Redemption#3429]
http://wow-mania.com/armory/?spell=2825

http://wow-mania.com/armory/?spell=32182

How it works:

If you change factions as Shaman u have both Skills available. This can be abused in raids and gives the whole raid a big advantage.

How it should work:

If you change faction you should only have one spell available. On ally side it's Heroism and on horde side it's Bloodlust.

**Comment by wow-mania** [comment]
Players with both spell have also been removed.

**Comment by Loktard** [comment]
> Players with both spell have also been removed.

I hope this doesn't mean people got banned, because they swaped factions.  I didn't mean to get anyone in trouble. I just like to see bugs removed not players :O
