### ISSUE TITLE
[Items] Unique vs Unique-equiped

### ISSUE THREAD

**Issue by WhitephoenixTheBunny** [WoWManiaUK/Redemption#3431]
There is two items (that I am aware) that are unique - can only carry one equiped and/or inventory/bank - and they are:
- [Je'Tze's Bell](http://www.wow-mania.com/armory/?item=37835)
- [Belt of the Blood Nova](http://www.wow-mania.com/armory/?item=50015)

The Belt of the Blood Nova can drop on [Sack of Frosty Treasures](http://www.wow-mania.com/armory/?item=52006) (Weekly ICC quest) and if you have one equiped you cannot loot the Sack, and have a "lost loot".

The items should be lootable even if the player owns one (equiped or on bank)

**Comment by wow-mania** [comment]
Don't think it works like that.
You shouldn't be able to even have both in your bag.
Same happens with the rings.

**Comment by WhitephoenixTheBunny** [comment]
I wasn't sure.
Since, as shaman using the blood nova and getting it on the sack, I only can destroy it. Being able to have on inventory, even with it equiped, could be given/sold to some else...
I couldnt find related source from blizzlike

**Comment by Kitzunu** [comment]
works as intended
![image](https://user-images.githubusercontent.com/24550914/62417324-eeb32b80-b64c-11e9-8251-2c18105c5bae.png)
