### ISSUE TITLE
Dungeon Finder Bug #2

### ISSUE THREAD

**Issue by Triise** [WoWManiaUK/Redemption#3432]
**What is Happening:** If you are in que and the finder puts you into a group while on a Flight path route, you can't zone into the dungeon. If you try to right click the DF Eye and port in, it tells you that "You cannot do that while falling"

**What Should happen:** You should be able to Zone in if the RDF que pops at any time, unless you are in combat.

**Comment by WhitephoenixTheBunny** [comment]
I confirm this happen, I will check if is inteed or not.

**Comment by Triise** [comment]
I'm pretty certain it was this way just from memory, on Blizzards version of Wotlk, But would be hard pressed to find it in writing some place. Maybe someone else who also played during this expansion can confirm.

**Comment by Keader** [comment]
I will not change nothing in DF system...
It's a cluster of shits, if i touch in something it will bug more...
A core dev is planing rewrite it, i will wait for him.
