### ISSUE TITLE
[Spell] Utgarde Pinnacle - Svala Sorrowgrave

### ISSUE THREAD

**Issue by Triise** [WoWManiaUK/Redemption#3434]
**Links:**https://www.wowhead.com/npc=26668/svala-sorrowgrave#abilities

**What is Happening:** She casts Ritual of the Sword and after the targeted player is free to move away and avoid it, Svala Sorrowgrave does not land and reengage,The party must move away to get here to reengage in battle, and the targeted player gets hit by Ritual of the Sword no matter where they move to.

**What Should happen:** If the targeted player moves out of the way, the spell should not hit them and leave the DOT. and Svala Sorrowgrave should land and reengage the players immediately after the sword touches the floor, no matter where the players are standing.

**Comment by wow-mania** [comment]
Will remain as-is for now.

**Comment by Dranah** [comment]
This bug isn't particularly old, been this way just a few months. Any idea what broke it? @wow-mania

**Comment by Dranah** [comment]
Can you please look at this? It worked flawlessly after this fix https://github.com/WoWManiaUK/Redemption/issues/2508
And it got broken a month or two ago. Can you perhaps revert it to that fix we had before?

**Comment by Keader** [comment]
Well, encounter is working.
Sword has a weird desync visual, of effect and visual.
Effects is taking +- 20 sec to execute after sword hit the ground, blame wow mania weird core.
I fixed a other issue. Npc that is target of sword was dying, making encounter bug if wipe after a ritual.
So now everything will be working, only visual desync stays, i cant find any reason for it happens.
