### ISSUE TITLE
EPGP lootmaster not working as intended

### ISSUE THREAD

**Issue by romasruls** [WoWManiaUK/Redemption#3436]
**Links:**

(EPGP addon bundle link) 
https://mega.nz/#!NmxX3IKS!JgeqkMgwfbYNX76VWLHlyEs9jcm1b8VAdrSdyDOv3yA

**What is Happening:**

Since the new server update the EPGP addon is not working properly anymore on the server. If the loot master in a raid wants to distribute loot the addon shows in the response tab " Offline or lootmaster not installed". Addon is still working, If you want to give EP for the boss kill.
So in particular "EPGPLootmaster" is not working cannot see who made what choise and cant give out the loot trough the addon, probably due to messages sent.

https://cdn.discordapp.com/attachments/555420191857573954/608000807014498304/EPGP_error.png

**What Should happen:**

The loot master rolls the loot with the EPGP addon. Raidmembers who are in the raid and online can choose to roll for an item in the EPGP addon by picking mainspec, offspec etc. The loot masters addon will show in the response tab who is rolling on an item for e.g. mainspec, offspec, pass etc. Than lootmaster is able to select the person he wants to give loot to and give it away and give GP points
https://cdn.discordapp.com/attachments/555420191857573954/608000780363890708/No_error_example.jpg

**Comment by wow-mania** [comment]
Some addons are not supported. We have no obligation to support any addon.
We have blocked some to avoid hacking holes.
