### ISSUE TITLE
[Item] Titanium Seal of Dalaran

### ISSUE THREAD

**Issue by jarvik76** [WoWManiaUK/Redemption#3437]
**Links:**
http://www.wow-mania.com/armory/?item=44430

**What is Happening:**
The possessive pronoun generated in the action text for female characters is incorrect.  It currently uses the gender form "his" regardless of male or female gendered characters.
> <char_name> casually flips **his** Titanium Seal of Dalaran

![WoWScrnShot_080519_214942a](https://user-images.githubusercontent.com/46089380/62495595-44631180-b7ce-11e9-9e16-311a988f9d16.jpg)

**What Should happen:**
Female characters that use the item should return the text 
> <char_name> casually flips **her** Titanium Seal of Dalaran"

**Comment by wow-mania** [comment]
As is.

**Comment by Rushor** [comment]
will fix that !

**Comment by Rushor** [comment]
done https://i.imgur.com/MQVxaaw.jpg https://i.imgur.com/CSLLxbD.jpg
