### ISSUE TITLE
VIP x6 exp is not working

### ISSUE THREAD

**Issue by Glitterwow** [WoWManiaUK/Redemption#3438]
**Links:**

**What is Happening:**
I have confirmed that x6 vip is not working. I have 2 different characters, i turn on x1 xp rate for 1 of them i turn on x6 for the other. They are the exact same level and I kill a monster and they both get the exact same amount of xp per kill.

**What Should happen:**

Hypothetically if I were to gain 100 xp at x1 I should get 600 xp on x6 for the same monster. 

I purchased VIP on 3 characters just so I wouldnt out level them on my tank which has RAF enabled for our 5th character (my room mate) and he has out leveled them by 10 levels already and I an unable to even run dungeons anymore. Something needs to be done about this.

**Comment by wow-mania** [comment]
works
