### ISSUE TITLE
[Quest] Rescuing the Rescuers

### ISSUE THREAD

**Issue by popawheelee** [WoWManiaUK/Redemption#3442]
**Links:**

**What is Happening:**None of the harpoons are respawning. i got 7/8 by waiting for the only one that was spawning harpoons to keep spawning. after 7, the only one stopped spawning. Ive spend well over an hour on this easy quest.

**What Should happen:**The flags should respawn to complete the quest

**Comment by WhitephoenixTheBunny** [comment]
Quest: http://www.wow-mania.com/armory/?quest=11244
NPC: http://www.wow-mania.com/armory/?npc=24077

Waiting on respawn

**Comment by WhitephoenixTheBunny** [comment]
After the 5min respawn, some will respawn with harpoon others no... is random...

![image](https://user-images.githubusercontent.com/31921098/62570555-ad5a9000-b887-11e9-99a2-d606b8d59aec.png)

**Comment by popawheelee** [comment]
Yeah I cleared the area twice before 1 would spawn the only one.

**Comment by gamer100** [comment]
Quest  complete does not show in log, but they  can deliver, some howe there is  going  something wrong in the  log

**Comment by wow-mania** [comment]
Just tested on dev and it works perfectly. All harpoons respawn fine
