### ISSUE TITLE
[Quest] Icecrown Citadel Weekly Quest Randomization

### ISSUE THREAD

**Issue by Kitzunu** [WoWManiaUK/Redemption#3443]
How it is: 
* Atm you get the same quest in 10 and 25 mode
* Quest is not removed from quest log the next week (at marrow kill/after marrow kill)
* If there is a server crash/restart there is a possibility that the quest changes making it possible for groups to complete 2(or more) ICC quests per week 

How it should be:
* The quest should be randomized for every difficulty (I dont know if it is per id or just difficulty)
* After marrowgar kill or joining a new lock that already killed marrowgar should remove the previous weeks ICC quest from your quest log
* If the server crashes/restarts the weekly should not change. There should only be a new quests after raid reset.

Proof:

This was said in a blue post by a blizzard employee:

>Now that Icecrown Citadel has been fully unlocked, allowing players the ability to progress in 10- and 25-player formats to defeat the Lich King, new raid weekly quests have been unlocked! These quests are specific to the Icecrown Citadel raid dungeon and do not correspond with the standard random raid weekly quest offered in Dalaran. Here's an overview of what you need to know. 
One of five quests will be randomly available each week in both 10- and 25-player versions of the dungeon. This means each player has the opportunity to complete two Icecrown Citadel raid weekly quests each week if the dungeon is run in both versions, however, these quests have to be completed within the raid version (10- or 25-player) in which they are offered.
If a player obtains one of these quests but does not complete it that week, the quest will automatically be removed from the player's Quest Log the next time Lord Marrowgar is defeated under a new raid ID, or when zoning into an instance with a new raid ID where Lord Marrowgar has already been defeated. This only applies if the random raid weekly offered when the player enters a fresh Icecrown Citadel raid instance happens to be different from the one already in his or her Quest Log. Players can otherwise simultaneously have both the 10- and 25-player raid weekly quests in their Quest Logs and complete either of them at any time during the week in their respective raid versions. The quests given each week in 10- and 25-player versions of Icecrown Citadel will be randomly determined once Lord Morrowgar is killed, or once a player zones into an instance where Lord Morrowgar has already been killed. 

Source: https://blue.mmo-champion.com/topic/505-icecrown-citadel-raid-weekly-quests/

**Comment by Keader** [comment]
Need some core support that we dont have (because we use a old version).
So, cant be implemented until update.
