### ISSUE TITLE
[Item] DBW Shapeshift + mounting

### ISSUE THREAD

**Issue by Kitzunu** [WoWManiaUK/Redemption#3445]
as of patch 3.3.3 
>[Deathbringer's Will]: Players can no longer mount with any of the shapeshifts from this item active.

Currently you can still mount when you are affected by one of the shapeshifts http://wow-mania.com/armory/?spell=71558

How it should be:
You should not be able to mount with any of the shapeshift forms

**Comment by WhitephoenixTheBunny** [comment]
Yeah. I have reas that on a patch change... I will try find it

**Comment by Kitzunu** [comment]
https://wowwiki.fandom.com/wiki/Patch_3.3.3
