### ISSUE TITLE
[Item] Argent Crusader's Tabard

### ISSUE THREAD

**Issue by WhitephoenixTheBunny** [WoWManiaUK/Redemption#3446]
The item [Argent Crusader's Tabard](http://www.wow-mania.com/armory/?item=46874) should no longer triggers a 30 second cooldown when equiped.

In: https://wowwiki.fandom.com/wiki/Patch_3.3.3_(undocumented_changes)

**Comment by Kitzunu** [comment]
It should not trigger a 30s cooldown when you equip it.

it should still have the 30min cooldown after usage

**Comment by Kitzunu** [comment]
@Keader do you know why item_template.flag  **128 | 0x080 | No default 30 seconds cooldown when equipped** does not change anything when applied?

**Comment by Keader** [comment]
nope, need check in core

**Comment by Keader** [comment]
Yes, was a core issue about that.
Fixed :)
