### ISSUE TITLE
[Feature] Buyback

### ISSUE THREAD

**Issue by WhitephoenixTheBunny** [WoWManiaUK/Redemption#3447]
When a player sell an item and then relog / log off / crash / DC, the item isn't avaible anymore  on the Buyback option (on any seller). 

What should happen:  Items sold to vendors now stay in the buyback page even if you log off.

In: https://wowwiki.fandom.com/wiki/Patch_3.3.3_(undocumented_changes)

**Comment by Keader** [comment]
Closing it.
I make a issue about it on Trinity Github, when it get implemented there i will cherry-pick to here.
Has not reason to leave it open too.
