### ISSUE TITLE
[World Event] Hallow's End

### ISSUE THREAD

**Issue by WhitephoenixTheBunny** [WoWManiaUK/Redemption#3448]
Well.... about this one, dunno if it can be worked when event not up, but report will be already here when it is up.

On patch changes from 3.3.3, there is this note:

> The previous summoning criteria for these bosses have been removed. Players can queue up for and fight each World Event boss as many times as they want for any standard loot that they may drop.
> in: https://wowwiki.fandom.com/wiki/Patch_3.3.3

Meaning this, a low geared can queue to farm the gear dropping from the bosses, for the whole day.

### What's happening (for the last 3 years I have been on server)
The boss is summoned after completing a [quest ](http://www.wow-mania.com/armory/?quest=11392)or the [daily quest](http://www.wow-mania.com/armory/?quest=11405) _Call the Headless Horseman_ (I believe those are the corrects links)
After running the instance a few time, and everyone had the daily done, the boss can't be summoned.

### What should Happen
The boss should be summonable, even without the daily quest, with a dialogue text on the [Pumpkin Shrine](http://www.wow-mania.com/armory/?object=186267) ([wowhead link](https://www.wowhead.com/object=186267/pumpkin-shrine)), as all the others events have.

**Comment by Kitzunu** [comment]
the gossip option to summon him without the quest is there, however it is missing a script

![image](https://user-images.githubusercontent.com/24550914/62629456-72129c80-b92d-11e9-9ea8-b0d9062bdd7d.png)

**Comment by WhitephoenixTheBunny** [comment]
I will reopen and label as regression, As it was released without confirmation.
I have ran dungeon several times and didn't was able to summon him without quest.
There is also another "bug" that I will report after a few others runs to be sure :P

**Comment by Rushor** [comment]
Will fix That

**Comment by WhitephoenixTheBunny** [comment]
The others issues:
When someone turn the quest OR use the "gossip" (main issue), anyone else should be able to turn the quest.
ATM, you can summon a max of 5 times the boss.
After boss summoned the "turn quest" should disappear
![Screenshot_19](https://user-images.githubusercontent.com/31921098/67104339-a7a1f480-f1be-11e9-9c55-24fa83665d4b.jpg)
![Screenshot_20](https://user-images.githubusercontent.com/31921098/67104340-a83a8b00-f1be-11e9-9ea2-7ae5077bca4e.jpg)

**Comment by Rushor** [comment]
i will make it like that.

once gossip is selected and no headless horse mna is in range > both objects will become unusable in the instance run and headless horse will be summoned.

once quest is completed and no headless horse mna is in range > both objects will become unusable in the instance run and headless horse will be summoned.

so quest OR gossip is only one time usable. and the horseman can only be summoned one time at instance run. 

with next instance run objects are usuable again.

**Comment by WhitephoenixTheBunny** [comment]
@Rushor 
I just removed labels to not be pushed yet.
I remind something over the others "worlds event"

Normally, quests does not tigger boss, everyone can turn, and only the gossip will tigger boss.
Can you check on other world event?

I don't want mess up event even more :P

**Comment by Rushor** [comment]
okay changed that. the gossip will only show up ONE time until the boss is summoned. Once the boss is summoned the gossip will not show up again per instance run. The quest can now always be rewarded.
