### ISSUE TITLE
[Feature] Dungeon finder

### ISSUE THREAD

**Issue by WhitephoenixTheBunny** [WoWManiaUK/Redemption#3449]
On the patch change from 3.3.3 there's two _important_ change related with the dungeon finder:

> o	Anyone in a dungeon party can now re-queue their group for a dungeon, as players will still be prompted whether or not to accept their chosen role.
o	Players who use the Vote Kick option will now be prompted to provide a reason for kicking a party member. This reason will be presented to everyone in the party except for the person voted to be kicked.
in: https://wowwiki.fandom.com/wiki/Patch_3.3.3

1- 
What is happening: only party leader can re-queue the party to another dungeon;
What should happen: "Anyone in a dungeon party can now re-queue their group for a dungeon, as players will still be prompted whether or not to accept their chosen role.";

2-
What is happening: no reason can be given;
What should happen: "Players who use the Vote Kick option will now be prompted to provide a reason for kicking a party member. This reason will be presented to everyone in the party except for the person voted to be kicked.".

**Comment by Kitzunu** [comment]
I guess Keader won't touch it until a core dev has rewritten the lfg system, but I can confirm this :)

**Comment by WhitephoenixTheBunny** [comment]
They're more dungeon finder changes related, but due at the long period of queue we have, appling them would hurt more the server than help, reason why I didn't report them.

**Comment by Keader** [comment]
https://media0.giphy.com/media/11ZSwQNWba4YF2/source.gif
How DF system work now ^

**Comment by Kitzunu** [comment]
HAHAHAHAHA @Keader
