### ISSUE TITLE
[Quest] Bitter Departure

### ISSUE THREAD

**Issue by tvshadowz** [WoWManiaUK/Redemption#3450]
**Links:**

Quest - http://www.wow-mania.com/armory/?quest=12832

**What is Happening:**

Once the escort is started the inured goblin does not stop when a npc begins to attack the player. 

**What Should happen:**

As with other escort quests the escortee should assist the player in attacking the npc but instead the injured goblin keeps running.

**Comment by wow-mania** [comment]
The NPC is not meant to help you. You are meant to help him when he is aggroed. 
As-is.
