### ISSUE TITLE
[Halls of Lightening] Ionar sparks following same player

### ISSUE THREAD

**Issue by Triise** [WoWManiaUK/Redemption#3451]
**Links:** https://www.wowhead.com/npc=28546/ionar#comments

**What is Happening:** 
Bug 1 After the 2nd boss Volkhan, There is a gauntlet, after clearing the gauntlet it will respawn the mobs you just killed, and they will also keep you in combat while they are respawning. So if anyone dies you are stuck in combat, and when they release and run back in, they will aggro all the respawned gaunltlet NPC's.

Bug 2 Is on the next boss Ionar. He casts a spell called Disperse turning into orb's that chase each member in the group and doing aoe damage in a 8 yard radius.

**What Should happen:**
Bug 1 The NPC's killed in the gauntlet should not respawn and not keep the party in combat in the mean time. Any remaining NPC's that did not activate in the gauntlet should never activate after it is cleared.

Bug2 All of the Disperse orbs should all target 1 random player and chase him/her, so everyone should stay away from that player, and the targeted player should kite them away until the spell duration is over.

**Comment by WhitephoenixTheBunny** [comment]
Bug 1:
NPC: Slag - http://www.wow-mania.com/armory/?npc=28585

Bug 2:
Boss: Ionar: http://www.wow-mania.com/armory/?npc=28546#drops
Spell: Disperse: https://www.wowhead.com/spell=52770/disperse

**Comment by Triise** [comment]
The slag are after the first boss, these are the NPC's after the 2nd boss that are bugging in permanate combat and respawning.  The slag should respawn after first boss, and should remain as -is

**Comment by Dranah** [comment]
These are the gauntlet mobs in question:
![WoWScrnShot_082019_142726](https://user-images.githubusercontent.com/31132743/63347099-ba32b580-c356-11e9-9e91-5cc099900b42.jpg)
![WoWScrnShot_082019_142740](https://user-images.githubusercontent.com/31132743/63347105-bc950f80-c356-11e9-8b9b-2d81c2d0a385.jpg)

The slags after 1st boss are respawning too but i'm not sure if that's unintended.
