### ISSUE TITLE
[Event] Hourly Bells

### ISSUE THREAD

**Issue by Kitzunu** [WoWManiaUK/Redemption#3452]
**What is happening:** Currently the Hourly Bells event does not work at all, I tested in Stormwind at 15.00 (3 PM) Server Time, but no chimes/bell sounds went off. 

**What should happen:** Every hour, on the hour the event should start and play a bell sound in Horde/Ally and Kharazan clocks towers

**Comment by Kitzunu** [comment]
http://wow-mania.com/armory/?event=-73

**Comment by Keader** [comment]
events is not with me o.o

**Comment by Kitzunu** [comment]
So the sound is fixed. But you can hear it in all of Eastern Kingdoms.
You should only be able to hear it within the zone of Stormwind City

**Comment by wow-mania** [comment]
I will keep it as it is.
I think it will help players.
