### ISSUE TITLE
[Mobs] Magisters' Terrace

### ISSUE THREAD

**Issue by cathyr1** [WoWManiaUK/Redemption#3455]
These mobs inside Magisters' Terrace (heroic mode) are bugged:

http://www.wow-mania.com/armory/?npc=24689
http://www.wow-mania.com/armory/?npc=24688
http://www.wow-mania.com/armory/?npc=24690

Their abilities deal damage by single hit about 10k - 20k. But they shouldn´t do such big dps as this instance is for 70s where tanks had about 12k hit points.
![Bug](https://user-images.githubusercontent.com/30184491/62818752-e4f95e80-bb4b-11e9-9479-60dd56a5af74.png)

**Comment by WhitephoenixTheBunny** [comment]
I am trying get some data about the intance, a source with damage record. 
The only thing that I seems find, shows is as inteed: 

> Groups should come prepared to this instance as the level of difficulty is greater than the hardest of the level 70 5-man instances like Shattered Halls and Shadow Labyrinth, and is on a similar level to that of beginning heroics such as Hellfire Ramparts and Underbog. On heroic mode Magisters' Terrace is one of the most difficult five man experiences at level 70.
In: https://wowwiki.fandom.com/wiki/Magisters%27_Terrace

**Comment by Dranah** [comment]
They have an ability called "Drink Fel Infusion" which is responsible for this damage.
However their base damage values looks to be set wrong. 
**How it should work:** They should be hitting for like 50-100 by default and this increases to about 1,5-2k per swing under the effect of Fel Infusion.
**How it works atm:** They hit 1-2k by default, and this increases to 10-20k under the effect of Fel Infusion.

Sources: https://www.wowhead.com/npc=24689/wretched-bruiser#comments
 on 2008/08/23 (Patch 3.0.1)
When i am there they hit like 60-100 before they drink a pot then they take like 1500"
https://www.youtube.com/watch?v=HrHTaIHiq2U

**Comment by WhitephoenixTheBunny** [comment]
I found another bug related with this fight (nm and hc)

> The first two mobs in the dead center of the room may be safely pulled without attracting the attention of the other two groups. Fight the next two six-pulls out in the hall if you can. Crowd control--sap, sheep, trap, mind control, whatever you have--is useful for these pulls.
in: https://wowwiki.fandom.com/wiki/Selin_Fireheart

Pulling those mobs will aggro boss

**Comment by Dranah** [comment]
Damage corrected. Pulling the mobs still aggros Selin however.

**Comment by Dranah** [comment]
These two, specifically, did NPC info on them and marked with raidmarks:
![WoWScrnShot_082019_140857](https://user-images.githubusercontent.com/31132743/63345903-23fd9000-c354-11e9-9d80-e9fcd2ba8977.jpg)
![WoWScrnShot_082019_140910](https://user-images.githubusercontent.com/31132743/63345908-25c75380-c354-11e9-8afc-f0cd0af6e85a.jpg)

**Comment by Keader** [comment]
Is call for help ( any npc when attacked, call for help).
I cant disable it, without rewrite script of all npcs around.
I realy dont want do it, because cost x benefit is not good (and i'm not sure if wow mania core support disable call for help, without do a big hack)
So... stay as is for this case.
