### ISSUE TITLE
[NPC] Ymirjar Deathbringer ID: 38125 Abilities missing

### ISSUE THREAD

**Issue by Drostthehunter** [WoWManiaUK/Redemption#3457]
**Links:**
https://www.wowhead.com/npc=38125/ymirjar-deathbringer
https://www.wowhead.com/spell=71296/shadow-bolt
https://www.wowhead.com/spell=71299/deaths-embrace
https://www.wowhead.com/spell=69929/spirit-stream
https://www.wowhead.com/spell=71303/summon-ymirjar
https://www.wowhead.com/spell=71298/banish

**What is Happening:**
This npc has a total of 5 abilities he should be doing, atm he is casting only https://www.wowhead.com/spell=71296/shadow-bolt. 

**What Should happen:**
10normal ICC NPC has a total of 4 abilities, the missing abilities are:
https://www.wowhead.com/spell=71299/deaths-embrace
https://www.wowhead.com/spell=69929/spirit-stream
https://www.wowhead.com/spell=71303/summon-ymirjar

On 10heroic 25normal 25heroic this NPC gets 1 more ability that he is also missing:
https://www.wowhead.com/spell=71298/banish

**Comment by Oganku** [comment]
Missing: https://www.wow-mania.com/armory/?spell=71299 https://www.wow-mania.com/armory/?spell=71300 and https://www.wow-mania.com/armory/?spell=69929.

Also missing difficulty variations.

**Comment by Rushor** [comment]
https://www.wow-mania.com/armory/?spell=69929. cannot be added, but the other protection auras are added now based on difficulty https://www.wow-mania.com/armory/?spell=71299 https://www.wow-mania.com/armory/?spell=71300

**Comment by Rushor** [comment]
https://i.imgur.com/ZfaaqLy.jpeg

**Comment by Rushor** [comment]
here the icetrap in action, hawks are also summoned https://i.imgur.com/iPMmXSs.jpeg

**Comment by Rushor** [comment]
stream added https://i.imgur.com/Ma0tCyD.jpeg
protection bubble added https://i.imgur.com/fo44XQJ.jpeg
