### ISSUE TITLE
[NPC] Ymirjar Frostbinder ID: 37127 Abilities missing

### ISSUE THREAD

**Issue by Drostthehunter** [WoWManiaUK/Redemption#3458]
**Links:**
https://www.wowhead.com/npc=37127/ymirjar-frostbinder
https://www.wowhead.com/spell=71270/arctic-chill
https://www.wowhead.com/spell=71274/frozen-orb
https://www.wowhead.com/spell=69929/spirit-stream
https://www.wowhead.com/spell=71306/twisted-winds

**What is Happening:**
This NPC is atm doing non of thos abilities besides auto attack.

**What Should happen:**
This NPC has total of 4 abilities spread throughout difficulties of Icecrown Citadel
ICC 10normal and 25normal NPC should have next abilities:
https://www.wowhead.com/spell=71270/arctic-chill
https://www.wowhead.com/spell=71274/frozen-orb
https://www.wowhead.com/spell=69929/spirit-stream
https://www.wowhead.com/spell=71306/twisted-winds
ICC 10heroic and 25heroic NPC has a difference in that that 10heroic NPC does not have the spell "Twisted Winds" and 25heroic version of this npc should have it.

**Comment by Oganku** [comment]
[Spirit Stream](https://www.wow-mania.com/armory/?spell=69929) and [Twisted Winds](https://www.wow-mania.com/armory/?spell=71306) (for 25hc only) are still missing.

Also, the [Frozen Orb](https://www.wow-mania.com/armory/?spell=71274) summoned currently doesn't do anything. I assume it should target nearby enemies, as the tooltip implies.

**Comment by jeyrella** [comment]
The remaining missing skills actually makes frost quarter in ICC significantly easier than it should be.  Should revisit and add these spells to the NPCs.

**Comment by Rushor** [comment]
Spirit Stream will be casted outfight to the clostest triggers in the wall,

Frozen Orb and Twisted Winds will now also be casted infight.

Frozen Orb is only a visual it will trigger missiles to clostst enemies around it

**Comment by Rushor** [comment]
https://i.imgur.com/ZfaaqLy.jpeg

**Comment by Oganku** [comment]
When looking at videos of the frostwing trash clears for issue #5677, I saw that the frozen orbs are meant to shoot projectiles with blue ground markers similar to those of the 2 dragons before Sindragosa. However, the balls still don't do anything. They don't show 24/7, but while the Frostbinder is channeling it, it does nothing.

Also, Twisted Winds is still never used on heroic.

**Comment by jeyrella** [comment]
Lets make sure this is fully tested this time for all spells, with photo/video evidence.  Thanks.

**Comment by Rushor** [comment]
as is, this spell is too complicated
