### ISSUE TITLE
[NPC] Ymirjar Huntress ID: 37134 Abilities missing

### ISSUE THREAD

**Issue by Drostthehunter** [WoWManiaUK/Redemption#3459]
**Links:**
https://www.wowhead.com/npc=37134/ymirjar-huntress
https://www.wowhead.com/spell=71249/ice-trap
https://www.wowhead.com/spell=71705/summon-warhawk
https://www.wowhead.com/spell=71251/rapid-shot
https://www.wowhead.com/spell=71252/volley

**What is Happening:**
This NPC is at the moment casting non of his abilities on any ICC difficulty. The abilities are linked above.

**What Should happen:**

10normal and 10heroic version of this NPC has access to 1 ability:
https://www.wowhead.com/spell=71249/ice-trap

25normal and 25heroic version of this NPC has access to 4 abilities:
https://www.wowhead.com/spell=71251/rapid-shot
https://www.wowhead.com/spell=71249/ice-trap
https://www.wowhead.com/spell=71705/summon-warhawk
https://www.wowhead.com/spell=71252/volley

**Comment by Oganku** [comment]
Rapid Shot and Volley work, but Ice Trap and Summon Warhawk dont.

Also, they currently use all their working abilities (Rapid Shot and Volley) on 10 man difficulty.

https://www.wow-mania.com/armory/?spell=71249
https://www.wow-mania.com/armory/?spell=71705

**Comment by jeyrella** [comment]
This actually makes frost quarter in ICC significantly easier than it should be.  Should revisit and add these.

**Comment by Rushor** [comment]
hawks and traps should be casted now

**Comment by Rushor** [comment]
https://i.imgur.com/ZfaaqLy.jpeg

**Comment by Rushor** [comment]
here the icetrap in action, hawks are also summoned https://i.imgur.com/iPMmXSs.jpeg
