### ISSUE TITLE
[Raid] Ulduar 10 Siege/Demolisher/Chopper

### ISSUE THREAD

**Issue by GMSunShield** [WoWManiaUK/Redemption#346]
1) the spells for the siege don't work
2) if you switch seat it resets health

http://www.wowhead.com/npc=33060/salvaged-siege-engine
http://www.wowhead.com/npc=33109/salvaged-demolisher
http://www.wowhead.com/npc=33062/salvaged-chopper

**Comment by Kalasbyxan** [comment]
Also, exiting a vehicle resets it's HP, according to Barfmachine.
