### ISSUE TITLE
[Event] Kalu'ak Fishing Derby

### ISSUE THREAD

**Issue by PLZHALP** [WoWManiaUK/Redemption#3463]
**Links:**
https://www.wowhead.com/quest=24803/kaluak-fishing-derby
http://www.wow-mania.com/armory/?quest=24803
https://imgur.com/a/9KrFc6l

**What is Happening:**
I have completed quest Kalu'Ak Fishing Derby, and am unable to receive the reward.
When choosing either the ring or boots, I get the error "Item not found", as shown in the above screenshot.

**What Should happen:**
I should be able to select my reward, click Complete Quest and the item should appear in my bags.

**Comment by PLZHALP** [comment]
too late now, someone else won the derby by now :(
request can be closed i guess.

**Comment by WhitephoenixTheBunny** [comment]
If I am correct, the quest linked is from Dalaran Fishing Dailies, and Kalu'ak Fishing derby is another quest.
And Github doesn't check live, we check on PTR, to be checked and fixed.

**Comment by WhitephoenixTheBunny** [comment]
Correct quest:

http://www.wow-mania.com/armory/?quest=24803

**Comment by PLZHALP** [comment]
apologies, I was trying to register on github as fast as I could to post this bug before someone else nabbed my quest from me.
In my haste I mentioned the wrong quest in the title, I will correct it right away.
turns out I took too long to post the issue anyway, someone has nabbed my reward :(
