### ISSUE TITLE
[Spell] Spirit Alarm ID: 70547, Traps missing

### ISSUE THREAD

**Issue by Drostthehunter** [WoWManiaUK/Redemption#3464]
**Links:**
https://www.wowhead.com/spell=70547/spirit-alarm
https://www.wowhead.com/npc=37007/deathbound-ward

**What is Happening:**
According to the tester, those traps actually exists on Dev server, yet they are not present on Redemption and not working. The Deathbound Wards ( ID 37007) are walking freely inside the Icecrown Citadel in the hall before the Marrowgar even tho they should not act like that unless the trap ( ID 70547) is activated.

**What Should happen:**
There are 4 traps in raid that are spread around 1st big hall leading to Lord Marrowgar and the 2nd room right before him, once a raid member steps on ANY of those trap, the trap will activate and will wake up the Deathbound Ward that is standing as untargatable npc before the trap activation. The only way to see those traps is having a rogue using stealth who can actually disarm them and avod waking up of Deathbound Wards. 
This is also noticable as a missing spell since once you enter the ICC your Deadly Boss Mods will trigger and yell Deathbound Ward activated, which is suggesting that there should be some mechanism to "wake up" the Deathbound Wards.

Here you can see comments made about this thread on wowhead:

By FlawedHero (7,673 – 2·22·124) on 2009/12/09 (Patch 3.2.2)
This alarm is invisible, detectable by Rogues, and located on the floor near some of the large trash packs. The alarm will aggro an individual Deathbound Ward on either side of many of the rooms when set off.

**Comment by Kitzunu** [comment]
I might be wrong, but shouldn't there be traps before Fester/Rot too?

**Comment by Drostthehunter** [comment]
@Kitzunu You are right, there should be 2 traps right before Festergut and Rotface room, but they are working different, they are triggering wave of https://www.wowhead.com/npc=37038/vengeful-fleshreaper, that will be spawned from your back if the trap is activated

**Comment by Kitzunu** [comment]
Does that one work?

**Comment by Drostthehunter** [comment]
No, it does not, idk about Dev, but on Red it does not work.

**Comment by WhitephoenixTheBunny** [comment]
I recall seeing both traps on ptr, but none working

**Comment by Keader** [comment]
Closing because i want implement it in my vacation to Trinity, so i port to wow mania too.
And it need be in my vacation because i will need alot of time, sniffing it alot of times, because looks like blizzard randomize traps spot.
So... will me fixed in future.

**Comment by Rushor** [comment]
already fixed meanwhile :)

**Comment by GMMetaxa** [comment]
Got some reports traps aint working. Please check.

**Comment by Rushor** [comment]
they work https://i.imgur.com/2N7oPA3.jpg https://i.imgur.com/yElZBr6.jpg
