### ISSUE TITLE
[Raid] Blood Prince Council - Kinetic Bombs aggro Blood Queen Lana'thel

### ISSUE THREAD

**Issue by jarvik76** [WoWManiaUK/Redemption#3471]
**Links:**
https://www.mmo-champion.com/threads/690262-Moderators-Recruitment-Crimson-Halls-Hotfixes-Blue-posts
https://wowwiki.fandom.com/wiki/Blood_Prince_Council#Patches_and_Hotfixes

**What is Happening:**
During the Blood Prince Council fight, if a targeted AoE spell such as mage's Living Bomb or boomkin Starfall is cast on the Kinetic Bombs while high in the air, they occasionally will cause Blood Queen Lana'thel to aggro.
This causes the BPC encounter to end, and the entire raid to be transported to the entrance teleporter.

There was a hotfix applied by Blizzard for this specific problem, which made BQL only spawn after the BPC had been defeated.
https://www.mmo-champion.com/threads/690262-Moderators-Recruitment-Crimson-Halls-Hotfixes-Blue-posts

https://wowwiki.fandom.com/wiki/Blood_Prince_Council#Patches_and_Hotfixes
"Hotfix (2010-01-21): "Kinetic Bombs no longer aggro Blood Queen Lana’thel." 

**What Should happen:**
Blood Queen Lanathael should only spawn after the Blood Prince Council has been defeated, preventing her from being aggroed accidentally by AoE spells.

**Comment by WhitephoenixTheBunny** [comment]
I have tested with druid, starfall on the trash at entrance (that could also reset fight), and on the fight itself, casted starfall on all the area fight didn't reset.
