### ISSUE TITLE
[Item] Ring of the Kirin Tor (all variants)

### ISSUE THREAD

**Issue by jarvik76** [WoWManiaUK/Redemption#3472]
**Links:**
Ring of the Kirin Tor (all variants)  
http://www.wow-mania.com/armory/?items&filter=sl=11;na=kirin+tor
http://www.wow-mania.com/armory/?item=51557
http://www.wow-mania.com/armory/?item=51558
http://www.wow-mania.com/armory/?item=51559
http://www.wow-mania.com/armory/?item=51560
http://www.wow-mania.com/armory/?item=48954
http://www.wow-mania.com/armory/?item=48955
http://www.wow-mania.com/armory/?item=48956
http://www.wow-mania.com/armory/?item=48957
http://www.wow-mania.com/armory/?item=45688
http://www.wow-mania.com/armory/?item=45689
http://www.wow-mania.com/armory/?item=45690
http://www.wow-mania.com/armory/?item=45691
http://www.wow-mania.com/armory/?item=44934
http://www.wow-mania.com/armory/?item=44935
http://www.wow-mania.com/armory/?item=40585
http://www.wow-mania.com/armory/?item=40586

**What is Happening:**
Ring of the Kirin Tor (all variants) cause a 30-second cooldown on equip.

**What Should happen:**
This is not correct for this item, and should be usable immediately on equipping:
https://www.wowhead.com/achievement=2084/ring-of-the-kirin-tor
![image](https://user-images.githubusercontent.com/46089380/62836464-1f055600-bc5b-11e9-894b-7f216990a7bb.png)

https://us.battle.net/forums/en/wow/topic/2456447609
![image](https://user-images.githubusercontent.com/46089380/62836546-1f522100-bc5c-11e9-81ec-1cf9a280b555.png)

**Comment by wow-mania** [comment]
will remain as is.

**Comment by Kitzunu** [comment]
fixed
