### ISSUE TITLE
[Spell] Enhancement Shaman; Stoneclaw Totem consuming Maelstrom Weapon stacks

### ISSUE THREAD

**Issue by therealjimboslice** [WoWManiaUK/Redemption#3473]
**Links:**

https://www.wowhead.com/spell=78153/maelstrom-weapon

*What is Happening:**

Stoneclaw Totem is removing Maelstrom Weapon at 5 stacks. Does not consume if stacks are between 1-4.

**What Should happen:**

MW stacks should only be consumed by casting Lightning Bolt, Chain Lightning, Lesser Healing Wave, Healing Wave, Chain Heal and Hex.

**Comment by wow-mania** [comment]
Needs confirmation,

**Comment by Dranah** [comment]
This is still happening, the issue seems to be the Glyph of Stoneclaw Totem effect that pvpers use.
ID 58582 (stoneclaw totem)
Spell ID 55277 (absorption proc from the glyph) is overriding a 5 stack maelstrom (spell ID 53817 on the buff)

**Comment by Keader** [comment]
Fixed.

**Comment by Dranah** [comment]
No change, still consumes them. Although now I seem to get new stacks afterwards at least, but, the 5 I had are still gone...

**Comment by Keader** [comment]
fixed²
