### ISSUE TITLE
[Spell / Talent] Touched by the Light reduces Avenging Wrath damame

### ISSUE THREAD

**Issue by slaniaxx** [WoWManiaUK/Redemption#3474]
**Links:**
https://wotlk.evowow.com/?spell=53590
https://www.wowhead.com/spell=31884/avenging-wrath
**What is Happening:**
Paladin Talent [Touched by the Light] is reducing [Avenging Wrath] skill damage by nearly half. Also reduces Consecration damage.  (Shield of Righteousness and Hammer of the Righteous damage is not changed.) 

**What Should happen:**
Paladin Talent [Touched by the Light] should increase Consecration and Avenging Wrath damage as it increases spellpower. In any case it should never reduce it.

**Comment by Keader** [comment]
I cant reproduce it.
