### ISSUE TITLE
[Quest] Venom Bottles

### ISSUE THREAD

**Issue by AIlindah** [WoWManiaUK/Redemption#3475]
**Links:**
https://classic.wowhead.com/quest=2933/venom-bottles

**What is Happening:**
The quest is supposed to turn in to Apothecary Lydon in Tarren Mill but there is no turn in option available.

**What Should happen:**
Apothecary Lydon in Tarren Mill should be waiting to accept this quest turn in and give me the next step in the chain.

**Comment by WhitephoenixTheBunny** [comment]
I haven't done the quest, but the NPC is there.
![image](https://user-images.githubusercontent.com/31921098/62861650-131da080-bcfc-11e9-9a4e-05913c9b65d5.png)
http://www.wow-mania.com/armory/?quest=2933
http://www.wow-mania.com/armory/?npc=2216

**Comment by AIlindah** [comment]
When I went to Tarren Mill today the Questgiver was willing to accept the quest now, closing this issue,
