### ISSUE TITLE
Hunter Pets

### ISSUE THREAD

**Issue by Elfar2** [WoWManiaUK/Redemption#3476]
**Links:**
[https://imgur.com/a/nMxEZVw](url)
Clicking on the link does not work for me, so in order to see the pictures, just copy the link and paste it in another window.
**What is Happening:**
1. After taming a devilsaur and leveling it up to 80 I noticed that his size remained the same. Visually, they should be the biggest pets in WoTLK for BM hunters. On the other hand, my two other pets (wolf and cat) increased in size every time they leveled up and reached max size on level 80 (shown in the link above).
2. Pet's abilities charge and dash do not work properly. I have them in a macro with my Aimed Shot, Steady Shot etc, but they rarely trigger. I tried removing them from the macro and just activate auto-cast on them but the triggering still remained random. Sometimes the pet will charge and use dash, sometimes not. It's really helpful for hunters to be able to control and trigger these pet abilities at will in PVP and PVE.

**What Should happen:**
1. Devilsaur's height should be checked because at max level they should be larger even than the hunter himself.
2. Pet abilities (charge and dash) should be triggered simultaneously (even by the player, using macros) because they do not share a GCD.

**Comment by wow-mania** [comment]
Sizes are as per 3.3.5a and depend on the type of animal.
We do not support macros.
