### ISSUE TITLE
[Quest] Arelion's mistress

### ISSUE THREAD

**Issue by Joblaisk** [WoWManiaUK/Redemption#3477]
**Links:**   https://www.wowhead.com/quest=9472/arelions-mistress

**What is Happening:**  When you give her the wine she moves forward for 3 seconds then stop moving. Can't lure her.

**What Should happen:** Should be able to lure her down the road so you can use the scroll of retribution on her

**Comment by Drostthehunter** [comment]
Edit the issue as explained at the start or sadly it can get closed without even being looked at:
[Quest] Arelion's Mistress ID: 9472

**Comment by WhitephoenixTheBunny** [comment]
Works fine 
![image](https://user-images.githubusercontent.com/31921098/63224400-94bd7480-c1bb-11e9-9f80-fece41da58a3.png)
