### ISSUE TITLE
[Spell] Fan of Knives

### ISSUE THREAD

**Issue by Kitzunu** [WoWManiaUK/Redemption#3479]
What is happening: Currently (as per the tooltip) Fan of Knives does 105% of weapon damage if you have daggers equipped.

What should happen: With daggers equipped Fan of Knives should deal 150% of weapon damage.

![image](https://user-images.githubusercontent.com/24550914/62978877-9afdca80-be22-11e9-937a-5336a3965075.png)

**Comment by Kitzunu** [comment]
or 120%, very unsure O.o

**Comment by Drostthehunter** [comment]
Patch 3.2.2 came after 3.0.8 means that Fan of Knives dmg was nerfed from 150% to 120%.

**Comment by limoncin** [comment]
wtf....xD
3.0.8 = 150%
3.2.2 = reduce 30% of 150%

150 * 30/100 = 45
150 - 45 = 105%

Was working perfect....

**Comment by Kitzunu** [comment]
Oh yea you right, I calculated wrong xd

@Keader Pls revert
