### ISSUE TITLE
Icecrown Warsong Ship: Insta Deff

### ISSUE THREAD

**Issue by LaughingNighty** [WoWManiaUK/Redemption#3480]
**Links:**

**What is Happening:**

Sometimes when i get to the Warsong Ship i just die (One-Shot)
**What Should happen:**
Nothing

**Comment by Kitzunu** [comment]
By what do you die of? 
Send a screenshot of the combat log and give reproduction steps

**Comment by Kitzunu** [comment]
I guess you mean the Orgrims Hammer, and without reproduction steps / more info I cannot reproduce this issue

**Comment by LaughingNighty** [comment]
![WoWScrnShot_081419_001758](https://user-images.githubusercontent.com/54084107/62981264-182c3e00-be29-11e9-9fac-5c5d8e6d9829.jpg)
![WoWScrnShot_081419_001801](https://user-images.githubusercontent.com/54084107/62981266-182c3e00-be29-11e9-949a-a35147abd9de.jpg)
![WoWScrnShot_081419_001804](https://user-images.githubusercontent.com/54084107/62981268-182c3e00-be29-11e9-81e1-1d4f0c4d7b60.jpg)

**Comment by LaughingNighty** [comment]
I just flew on it and died the moment i touched it

**Comment by Kitzunu** [comment]
@WhitephoenixTheBunny @Dranah something you can try/reproduce? O.o
