### ISSUE TITLE
Taunt - Diminishing Returns

### ISSUE THREAD

**Issue by Kitzunu** [WoWManiaUK/Redemption#3481]
>3.3.0
Taunt Diminishing Returns: We've revised the system for diminishing returns on Taunt so that creatures do not become immune to Taunt until after 5 Taunts have landed. The duration of the Taunt effect will be reduced by 35% instead of 50% for each taunt landed. In addition, most creatures in the world will not be affected by Taunt diminishing returns at all. Creatures will only have Taunt diminishing returns if they have been specifically flagged for that behavior based on the design of a given encounter.

I am positive that there are encounters that are missing this mechanic. However, I don't know which ones.

Please help me out if you know more about it! :D

**Comment by Keader** [comment]
It's already implemented.
Special flag is: CREATURE_FLAG_EXTRA_TAUNT_DIMINISH

**Comment by Kitzunu** [comment]
That I know, I just believe a lot of mobs are missing it.

however I dont know a good way to check if they should have it or not D:

**Comment by Keader** [comment]
Fixed
