### ISSUE TITLE
Blackwing Lair First Boss Bug

### ISSUE THREAD

**Issue by TomFate** [WoWManiaUK/Redemption#3482]
**Links:**
Start of the fight: 
![WoWScrnShot_081419_034137](https://user-images.githubusercontent.com/39968269/62987151-21c49e80-be47-11e9-92c6-9cff199d6e6f.jpg)

During first Mind Control:
![WoWScrnShot_081419_034157](https://user-images.githubusercontent.com/39968269/62987189-3dc84000-be47-11e9-9497-86101b209a6d.jpg)

After i cleaned the center of the room:
![WoWScrnShot_081419_034318](https://user-images.githubusercontent.com/39968269/62987211-5173a680-be47-11e9-919f-479f30b40842.jpg)

And then the bug happens when my Mind control ends:
![WoWScrnShot_081419_034332](https://user-images.githubusercontent.com/39968269/62987242-723bfc00-be47-11e9-8d60-6253fa2e0709.jpg)

You can see the time also to see that its original.

**What is Happening:**
While we switch Orbs boss restarts, plus also when we kill the three mobs it restarts again,(who are supposed to get killed by tacts) it's  a never ending loop.

**What Should happen:**
When switch orb or retake it eggs or the boss fight should not be restarted.

**Comment by WhitephoenixTheBunny** [comment]
This as been reported several times, the script would need be re-writen
But it is doable,
Don't kill mobs on platform, use orb from downstair, when mobs spawn don't kill them, dodge them.
After 3 uses of orbs, you can kill boss.

I will close it for now...
If someone have more info, they can add

Last fix: https://github.com/WoWManiaUK/Redemption/issues/2109

**Comment by Rushor** [comment]
the orb creatures will no longer respawn. the fight should continue.

**Comment by jarvik76** [comment]
Razorgore still resets at the start of the 3rd channeling.  Clicking the orb then does nothing.

**Comment by Rushor** [comment]
Razorgore still resets at the start of the 3rd channeling. 

> will be fixed next year
