### ISSUE TITLE
Its All fun and Games Quest

### ISSUE THREAD

**Issue by Agrannis73** [WoWManiaUK/Redemption#3483]
**Links:**

**What is Happening:**
Quest item "Eyesore Blaster" does not channel leaving The Ocular unharmed.

**What Should happen:**
Eyesore Blaster should channel and damage over time The Ocular to continue quest chain to unlock Shadowvault

**Comment by WhitephoenixTheBunny** [comment]
You need open a ticket to ask a gm to reset the ocular.

**Comment by Agrannis73** [comment]
I did that prior to submitting the ticket. Vadashu? Said to open a ticket
on Github.  He had me delete my cache and relog and the issue was not
corrected.

**Comment by Kitzunu** [comment]
What happened? Was the ocular there? Untargetable? 
Need to know more if I should be able to look into it

**Comment by Agrannis73** [comment]
Showed up a second time and asked for a reset.. a few minutes later the
Ocular disappeared and res pawned and it was completeable
