### ISSUE TITLE
Razorgore The untamed [boss]

### ISSUE THREAD

**Issue by Kallivira** [WoWManiaUK/Redemption#3484]
**Links:**
Change log of this fight
https://github.com/WoWManiaUK/Redemption/issues/2109
https://github.com/WoWManiaUK/Redemption/issues/2293
https://github.com/WoWManiaUK/Redemption/issues/2610

**What is Happening:**
Razorgore is resetting seemingly randomly during the fight. Additionally Mind Control doesn't grant full control over the NPC. Rather the NPC (Razorgore) will chase after enemies limiting the players ability to control the character. 

**What Should happen:**
The player should use the orb of mind control and take control of razorgore and destroy the eggs around the room to trigger Phase 2.

**Additional insight**
Razorgore the untamed has been modified heavily according to the changes listed above. From Earliest to most recent report (top to bottom). 

VA-L made a comment which mentioned this:
Razorgore and all the summoned adds will now despawn if he evades.
Eggs will now respawn when razorgore evades.
Razorgore gets in combat correctly when the channeling is canceled. (The only way to cancel is by dismissing as it should)
The 3 mobs around the Orb of domination will respawn when Razorgore evades.

I tested this a few times with my guild mates and found the following:
If you mind control Razorgore and let the timer expire with out destroying eggs, the fight will reset - however the timer will consistently expire. 

If you mind control Razorgore and destroy an egg to trigger the adds, razorgore will chase an add once he gains aggro on it despite being mind controlled. When adds start attacking razorgore the fight will reset. Presumably because of an evade mechanic occurring - potentially being enabled by whatever is causing Razorgore to ignore the effects of mind control.

Alternatively if you kill the controller (the orc npc) while mind controlling razorgore the fight resets.  

**Maybe a way to test** 
An easy way to test this in dev would be to disable the ability of Razorgore to "evade" if thats possible. Alternatively make the mobs not attack Razorgore as to prevent evades from happening.

**Comment by WhitephoenixTheBunny** [comment]
It was reported 2 days ago in: https://github.com/WoWManiaUK/Redemption/issues/3482

As commented boss is still doable... following the steps on my comment...
The fight it self need to be re written and atm I don't know how @Keader feel with re-write a fight.
