### ISSUE TITLE
[Boss] Twins Emperors - AQ40

### ISSUE THREAD

**Issue by WhitephoenixTheBunny** [WoWManiaUK/Redemption#3485]
This fight is doable (with several level 80, more than 20) but very hard as several mechanics fails - suchs as the most important one: Twin teleport.

The fight was reported on https://github.com/WoWManiaUK/Redemption/issues/2804 but was reverted; with the doors fixed on https://github.com/WoWManiaUK/Redemption/issues/2962 the way to C'thun is almost impossible.

---

The Fight have two bosses: [Emperor Vek'nilash](http://www.wow-mania.com/armory/?npc=15275) and [Emperor Vek'lor](http://www.wow-mania.com/armory/?npc=15276); they both share some spells and have unique ones.

There is some spells that I am sure that are broken or not working at all ( I will check others when PTR back)

Both Emperors:
**Twin Teleport** — Every 30–40 seconds, the two twins will switch places, visible by a blue glow around their feet. The twins will be rooted for about 2 seconds after they teleport before they start attacking again. There is a complete aggro wipe, and the Emperors will attack the closest player to them, who will receive a large amount of threat after the 2 second root runs out. (in [wowwiki fandom](https://wowwiki.fandom.com/wiki/Twin_Emperors))
_**ATM**_ One of the emperors will be summoned to the other one (one of the spells not working)
Spells ID Mania: [799 ](http://www.wow-mania.com/armory/?spell=799)and [800](http://www.wow-mania.com/armory/?spell=800)

**Combined Health** — The Emperors share percentage health. Damage to one emperor hurts the other emperor as well. HP of Vek'nilash is about 1.6M, HP of Vek'lor is about 1M. Therefore 100k damage done to Vek'lor equates to 160k damage done to Vek'nilash. This allows them to die simultaneously, but not in fact have the same real HP. Only their HP percentages go down simultaneously. This causes casters to have a greater effect in this fight than melee damage dealers.
About this one, and note I am not sure at 100%, but the damage isn't shared (at any percentage) as is possible to kill one of twins and the other one remaining at 100% health.

Emperor Vek'lor should cast [Explode Bug](http://www.wow-mania.com/armory/?spell=804) — Every 7-10 secs Emperor Vek'lor forces a nearby bug to explode, blowing it up and dealing a huge amount of fire damage over a wide area. (Qiraji Scarabs/Qiraji Scorpions: Explode Bugs — grow to 200% size, and their tentacles begin to spark. They explode 3sec after they are triggered and inflict between 2813 to 3187 fire damage.?
**_ATM_** he doesn't cast it at all 

---

Extra note:
As the fight is nearly impossible to do atm, and I don't know IF it can be fixed (at least on a short period of time) I suggest to the door (6683) to C'thun stay open 'till a fix be applied, as stated on issue https://github.com/WoWManiaUK/Redemption/issues/2962

**Comment by WhitephoenixTheBunny** [comment]
Twin Teleport  not happening at all....

Vek'lor still doesn't cast Explode Bug

At least now they don't teleport to each other... making the fight more doable... but the twin teleport is the main spell of fight... making the fight more intene...

if it can't be fixed... this way will be fine.

**Comment by Keader** [comment]
test now @WhitephoenixTheBunny 
Tested in PTR and everything is working now.

**Comment by WhitephoenixTheBunny** [comment]
Perfect <3
