### ISSUE TITLE
[Item-Proc] Chilling Knowledge

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#3490]
**Links:** http://www.wow-mania.com/armory/?item=50400#reward-from-quest
http://www.wow-mania.com/armory/?spell=72418
http://www.wow-mania.com/armory/?spell=48441
http://www.wow-mania.com/armory/?spell=53251
http://www.wow-mania.com/armory/?spell=50464

**What is Happening:** Ashen Band of Endless Wisdom's proc, 'Chilling Knowledge, cannot proc off of Healing over Time (HoT) spells such as Rejuvenation or Wild growth. Only direct heals such as Swiftmend, Nourish, or other classes' Holy Light / Healing Wave, etc. can proc it. It is a pretty big deal for restoration druids considering they barely do any direct heals whatsoever.

**What Should happen:** The ring should have a 10% proc rate from any healing done and have an ICD of 60 seconds. Not only behave as such only from direct heals.

**Comment by Kitzunu** [comment]
http://www.wow-mania.com/armory/?spell=72419

**Comment by Keader** [comment]
Wow mania core version dont allow fix it as it should be...
So i fix for some spells like: rejuvenation, wild growth, renew
