### ISSUE TITLE
Saurfang Deathbringer Death Event

### ISSUE THREAD

**Issue by Kitzunu** [WoWManiaUK/Redemption#3491]
After defeating Saurfang in ICC an outro event is supposed to take place.
Currently, these events are missing from the game.

**[Alliance]**
Deathbringer Saurfang dies.
The ironforge "captives" will be let down from the air
Muradin walks to Saurfangs dead body
Muradin: That was Saurfang's boy - the Horde commander at the Wrath Gate. Such a tragic end...
Muradin turns and points to the left.
Muradin: What in the... There, in the distance! 
A horde zeppelin is approaching Deathbringers Rise.
Muradin runs to the "Left part" of Deathbringers rise.
Muradin yells: Soldiers, fall in! Looks like the Horde are comin' to take another shot!
Zeppelin lands at the left part of Deathbringers Rise, in front of Muradin
Muradins soldiers are reforming like a "wall" behind Muradin in battle position
High Overlord Saurfang walks off the zeppelin
Muradin: Don't force me hand, orc. We can't let ye pass.
High Overlord Saurfang: Behind you lies the body of my only son. Nothing will keep me from him.
High Overlord Saurfang stands in battle position
Muradin: I... I can't do it. Get back on yer ship and we'll spare yer life.
Alliance Stormwind portal spawns
Lady Jaina Proudmoore and King Varian Wrynn spawn.
King Varian Wrynn: Stand down, Muradin. Let a grieving father pass.
Muradin runs to stand beside Jaina
Muradins crew runs further back behind Muradin
High Overlord Saurfang walks towards Deathbringer Saurfang
High Overlord Saurfang kneels
High Overlord Saurfang: No'ku kil zil'nok ha tar
High Overlord Saurfang picks Deathbringer Saurfang up and carries him towards King Varian Wrynn
High Overlord Saurfang: I will not forget this... kindness. I thank you, Highness
King Varian Wrynn: I... I was not at the Wrath Gate, but the soldiers who survived told me much of what happened. Your son fought with honor. He died a hero's death. He deserves a hero's burial.
High Overlord Saurfang nods.
High Overlord Saurfang walks towards the zeppelin
High Overlord Saurfang & Deathbringer Saurfang despawns and the zeppelin flies away
Lady Jaina Proudmoore cries.
King Varian Wrynn: Jaina? Why are you crying?
Lady Jaina Proudmoore wipes her tears away and smiles at King Varian Wrynn.
Lady Jaina Proudmoore: It was nothing, your majesty. Just... I'm proud of my king.
King Varian Wrynn: Bah! Muradin, secure the deck and prepare our soldiers for an assault on the upper citadel. I'll send out another regiment from Stormwind.
Muradin: Right away, yer majesty!
Muradins soldiers run to the ship & despawn
King Varian Wrynn teleports away
Lady Jaina Proudmoore teleports away
Muradin run to the teleporter
Muradins soldiers spawn behind Muradin
Two Alliance shield blue thingies spawn with blue fireworks on both sides of the "Base" part of Deathbringers Rise.
Two Alliance Mason's teleport, one to either blue thingy.
Alliance Mason's run to the left part of Deathbringers Rise.
Alliance Mason's starts to work.
Two Argent Vanguard tents, Blacksmith Forge, Blacksmith anvil (to the right of the right tent) and an Alliance Banner spawns.
Alliance Mason's run back to the blue thingies, and teleports away.
Sheiy Steelbowels <Blacksmith> & Brazzie Getz <General Goods> spawns at the blue thingies and walks to the tents.
Sheiy Steelbowels stands at the most right tent and Brazzie Getz and the most left tent.

Video of the whole event if you don't want to read:
https://www.youtube.com/watch?v=S6wF_8LGp_E

Blue thingies:
![image](https://user-images.githubusercontent.com/24550914/63223027-e8c25c00-c1af-11e9-80db-d70f8b02cf21.png)

Sheiy Steelbowels <Blacksmith> is a blacksmith and sells Draenic Sparring Blade, Draenic Warblade and Volatile Rum (10) (25?)

**[Horde]**
Deathbringer Saurfang dies.
High Overlord Saurfang and his crew fall down.
High Overlord Saurfang coughs.
High Overlord Saurfang walks up to Deathbringer Saurfang.
High Overlord Saurfang weeps over the corpse of his son.
High Overlord Saurfang kneels.
High Overlord Saurfang: You will have a proper ceremony in Nagrand, next to the pyres of your mother and ancestors.
High Overlord Saurfang picks Deathbringer Saurfang up. (Mid-sentence of mother and ancestors)
High Overlord Saurfang carries Deathbringer Saurfang to the teleporter
High Overlord Saurfang: Honor, young heroes... no matter how dire the battle... never forsake it.
High Overlord Saurfang carries Deathbringer Saurfang to Orgrims Hammer (the boat) and despawns.
High Overlord Saurfang and his crew spawn at the "start" position of Deathbringers Rise
Two Warsong Peons spawn at the edges on two red thingies

END OF YOUTUBE VIDEO

The two Warsong Peons run to the left side and starts to work.
Two Warsong tents, forge and an anvil (to the right of the right tent) and a bonfire spawns.
Warsong Peons run back to the red thingies and teleports away.
Apothecary Candith Tomas <General Goods> & Morgan Dayblaze <Blacksmith> spawns at the red thingies.
Apothecary Candith Tomas <General Goods> walks to the left tent
Morgan Dayblaze <Blacksmith> walks to the right tent

Video of the event until the END OF YOUTUBE VIDEO line if you don't want to read: 
https://www.youtube.com/watch?v=zAUcrT78wko

Red thingies:
![image](https://user-images.githubusercontent.com/24550914/63223218-8b7bda00-c1b2-11e9-8418-62e7e6c8a447.png)

(After the END OF YOUTUBE VIDEO line that info is taken from today's retail BFA on my own character from there. I could not find any info on the internet about the part of the event that was left from wotlk time)

**Comment by wow-mania** [comment]
As is not going to touch it.
