### ISSUE TITLE
Players able to be killed in Duels

### ISSUE THREAD

**Issue by Kitzunu** [WoWManiaUK/Redemption#3492]
I just encountered an interesting bug on Redemption.

I was dueling a druid, and at very low HP I used Sinister Strike to win the duel but then instead of stopping at 1 HP, the druid died.

 (Instant poison and Deadly Poison are the poisons I used)

How it should work:
You should not be able to kill or be killed in a duel

I noticed this is hard to reproduce since I tried to do it after I killed my opponent, it happens sometimes and sometimes not

**Comment by WhitephoenixTheBunny** [comment]
This have been used to get the achievement an honarable kill for many people... doing 2 duels one after the other one, and if the HP isn't at 100%, the "loser" may die.

**Comment by Keader** [comment]
Added a extra protection.
Now players will be immune to damage after duel ends, for 3 sec.
it not protect 100% of cases, but helps alot.

**Comment by Kitzunu** [comment]
This is not working, I just killed a DK as Rogue right after the duel ended in Dalaran.

Would it be possible to make it so hp cannot go under 1HP in a duel?

**Comment by Kitzunu** [comment]
I would think that Poison proc (or any other dmg proc) right as the duel ended causes this

**Comment by Rushor** [comment]
can you check again @Keader ? :>

**Comment by Keader** [comment]
Nothing more that i can do.
Those damages happens after duel ends, that's why blocks not work.
I realy dont know nothing more that can help with it.
