### ISSUE TITLE
Unable to use Mail Armor such as Tier 8 armor.  I never got the ability to wear mail armor

### ISSUE THREAD

**Issue by Kharlah** [WoWManiaUK/Redemption#3494]
Unable to wear any Mai; armor.  I thought I'd be able to wear Mail Armor.  As a leathercrafter I can make Mail Armor bur have never gained the ability to wear mail.  Where do I get that ability to wear mail armor or where do I learn/gain that ability.  I tried getting Conquerors' Terrorblade armor for a rogue but that didn't allow me wear that armor because it was only available for a rogue.  That was a BUST.  I need to return that armor and get the correct one for a Hunter.  And get the ability to WEAR mail armor!!!!!

**Comment by Drostthehunter** [comment]
Visit your trainer, you learn it at lvl 40
