### ISSUE TITLE
[Boss] The Curator

### ISSUE THREAD

**Issue by WhitephoenixTheBunny** [WoWManiaUK/Redemption#3495]
[The Curator](http://www.wow-mania.com/armory/?npc=15691) is one of the bosses in Karazhan, atm he is imune to all the physical damage (melee) and he should only be "Immune to arcane, poison, taunt and mana drain spells and effects." (in: https://wowwiki.fandom.com/wiki/The_Curator)

**Comment by WhitephoenixTheBunny** [comment]
15691

**Comment by wow-mania** [comment]
Immunities
536870912 - sapped
67108864 - dazzed
33554432 - interrupt
8388608 - horror
4194304 - turn
524288 - shackle
131072 - banish
65536 - polymorph
8192 - knockout
4096 - freeze
2048 - stun
1024 - snare
512 - sleep
256 - silence
64 - root
32 - grip
16 - fear
8 - distract
4 - disarm
2 - disoriented

It is correct as is.
