### ISSUE TITLE
[ICC] Gauntlet Sindragosa

### ISSUE THREAD

**Issue by WhitephoenixTheBunny** [WoWManiaUK/Redemption#3497]
After seeing a lot of ppl complaining on world chat about a bug, I went dev test:

On the gautlet do Sindragosa, there's an infinite spawn of [Nerub'ar Broodling](http://www.wow-mania.com/armory/?npc=37232), preventing the waves to procede and continue the raid like that, on all dificulties.

**Comment by Dranah** [comment]
could it be related to https://github.com/WoWManiaUK/Redemption/issues/3461 ?
The fix just went live and this is a new bug. And this NPC is a part of the same gauntlet event, so I doubt it's coincidence.

**Comment by wow-mania** [comment]
Please re-check on dev.
