### ISSUE TITLE
[Boss] Valithria Dreamwalker

### ISSUE THREAD

**Issue by crulinjr** [WoWManiaUK/Redemption#3498]
How is it working: The Portals are clickable but you cant get into the Dream World, they just disappear after you click them. So the fight ends up beign way slower.

How is should work: By clicking the portal you should go to the dream world.

**Comment by WhitephoenixTheBunny** [comment]
All portals?
I know sometimes it bugs, making her spawn twice, and one of spawns doesn't work.

**Comment by crulinjr** [comment]
yeah all portals, we had like 7-8 halers and now one could enter

**Comment by WhitephoenixTheBunny** [comment]
The portals, spawns, the jump option apear, but the player isn't ported to emerald Dream

**Comment by Keader** [comment]
Fixed.

**Comment by crulinjr** [comment]
Ty
