### ISSUE TITLE
Quest: The Earthen Oath

### ISSUE THREAD

**Issue by LastGasp91** [WoWManiaUK/Redemption#3499]
**Links:**
http://www.wow-mania.com/armory/?quest=13005

I am not receiving credit for the Iron Sentinels I kill, and thus it is taking me an inordinately long time to get credit for the 7 of them the quest requires. I've made sure to use the Horn of the Peaks before fighting so the earthen army are with me. 
I made sure to check to see if this had already been logged, and noticed a previous user had reported the same issue. They were told that they needed to kill Iron Sentinels that weren't already engaged in combat with other NPCs. I have been very careful to do this, only attacking ones that are alone with no other NPCs around them, and I am still not receiving credit for killing them.

**Comment by wow-mania** [comment]
Please confirm on dev

**Comment by WhitephoenixTheBunny** [comment]
Tested several ways.
The quest can be done without the item.
If the "army" does more damage than you (I believe that you need do more than 50% of damage) the kill will not count.

Remind, they are here to assist you, not to do the kills for you.
