### ISSUE TITLE
Kaw the Mammoth Destroyer not spawning

### ISSUE THREAD

**Issue by Taungo** [WoWManiaUK/Redemption#3501]
Kaw the Mammoth Destroyer has not spawned for the quest to kill him. I tried to force a spawn by killing his mammoth Moira (which does respawn correctly) but to no avail. It's been about 12 hours of trying (off and on) but he still hasn't shown up.

I did check everywhere in the immediate area in case he spawned somewhere other than his platform, but he did not as far as I could tell.

**Comment by wow-mania** [comment]
works.
