### ISSUE TITLE
Kaw still missing

### ISSUE THREAD

**Issue by Taungo** [WoWManiaUK/Redemption#3503]
NPC http://www.wow-mania.com/armory/?npc=25802 Kaw the Mammoth Destroyer not spawning making quest http://www.wow-mania.com/armory/?quest=11879 impossible to complete.  I've been more than patient thus far. but bug reports shouldn't be closed until the bug is fixed. Today alone I've spent an hour camping his spawn with no spawn. Take 30 seconds and check for yourself before assuming it works.
![WoWScrnShot_082119_160951](https://user-images.githubusercontent.com/54374143/63465573-8aa3ac00-c42f-11e9-93c3-449123550a31.jpg)

**Comment by Taungo** [comment]
Honestly I'm just disgusted with this entire encounter with you and am moving on to a different server. Fix it for the future players so that they can finish it. Or leave it broken and be lazy with the next player that reports it. Either way, enjoy.

**Comment by wow-mania** [comment]
I will ban you from game if you do that again.

**Comment by wow-mania** [comment]
Awesome I am speeding up the process for you.

**Comment by Dranah** [comment]
My god how does the github always turn into kindergarten :D
@taungo There is a dissonance between the mammoth's spawn timer and that of Kaw, and you need both of them present to begin the encounter. Killing the mammoth cannot spawn him.
You're simply unlucky as the quest is fairly popular.
Here's a live view from Redemption, he's just doing fine in his intended spot. Has one spot to spawn, doesn't patrol or spawn anywhere else, so chances are someone robbed you of the kill whenever you went looking for him elsewhere:
![WoWScrnShot_082219_171138](https://user-images.githubusercontent.com/31132743/63526767-34526e00-c500-11e9-8015-1a466c2ebabd.jpg)
PS: If you bothered asking any other players in the area, or the world chat, multiple people would have told you, that they had no problems completing the quest. Talk about who's lazy....
