### ISSUE TITLE
[NPC] Warden Treelos  (ID 18424)

### ISSUE THREAD

**Issue by jarvik76** [WoWManiaUK/Redemption#3504]
**Links:**
http://www.wow-mania.com/armory/?npc=18424

**What is Happening:**
Warden Treelos has green flightmaster icon when quest 9951 is available (http://www.wow-mania.com/armory/?quest=9951)

**What Should happen:**
Warden Treelos should have yellow quest icon.  (Compare with Earthbinder Tavgren in the background)
![image](https://user-images.githubusercontent.com/46089380/63510794-71563a80-c4d7-11e9-8967-5f89dfd34012.png)
(Yellow icon is appearing correctly in minimap)

EDIT:
The turn in question mark is also green, instead of yellow:
![image](https://user-images.githubusercontent.com/46089380/63511106-2d176a00-c4d8-11e9-8f0d-b110ebf266be.png)

**Comment by WhitephoenixTheBunny** [comment]
Isn't that because of the aura on the area?

**Comment by jarvik76** [comment]
Well, it looks like it has a physically different icon, it's a solid green all the way through, rather than varying.

**Comment by wow-mania** [comment]
as is

**Comment by WhitephoenixTheBunny** [comment]
Is due at the area spell
