### ISSUE TITLE
[Boss/Spell] Resistant Skin - Deathbringer Saurfang adds

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#3507]
https://www.wowhead.com/spell=72723/resistant-skin
https://www.wowhead.com/npc=38508/blood-beast
https://www.wowhead.com/npc=37813/deathbringer-saurfang

This is the AOE reduction buff on Deathbringer Saurfang's Blood beasts. 

While the tooltip speaks of reduced damage from diseases and "aoe spells", after a bit of research I found that the list of abilities it's supposed to affect is far larger than classic aoe abilities. It should affect cleaves too.
Which is the main reason the fight looks so much different on retail than here, there you are forced to kite down the adds with ranged dps dealing targeted damage and they don't just die to cleave.

**How it works atm:** currently it only mitigates damage from classic aoe abilities, does not affect cleaves and any targeted ability that strikes a multi target. This means the adds die in 1-2 seconds after they spawn to cleaving and the raid does not need to handle the mechanism.
**How it should work:** It should affect nearly every multi target ability that classes have, except for shaman's Chain Lightning, prot warr's Revenge and druid's Maul (these abilities only cleave when specced/glyphed) and the non-splash damage of Starfall stars.
Proof and a full list below. (note, there has been some patch fixes that affected which spells are mitigated, I have only taken data from the most relevant 3.3.5 logs of 2010 july-sept)
http://www.worldoflogs.com/reports/rwpm5n0tc9y9puc5/details/158/?s=5089&e=5258
http://www.worldoflogs.com/reports/rt-25148sw7av0k8ht0/details/156/?s=3519&e=3703

Here's a list with spell IDs of abilities that currently deal full damage to the beasts on mania, but should be mitigated by the aoe reduction:
Cleave - ID 20569
Swipe(cat) - ID 62078
Heart Strike - ID 55262
Multi-shot - ID 27021
Blade Flurry - ID 13877
Sweeping strikes - ID 12328

Up to extension in case I find something else, lol.

**Comment by crulinjr** [comment]
By Coilz0r (2,247 – 3·22) on 2010/03/10 (Patch 3.3.2)
The aoe damage decreasing aura does not affect a warriors cleave, effectively making it easier to do dps at boss & blood beasts at the same time.
Last edited by Coilz0r on 2010/03/10 (Patch 3.3.2)

**Comment by Keader** [comment]
https://github.com/TrinityCore/TrinityCore/issues/8728#issuecomment-12674246

**Comment by Dranah** [comment]
Yes, it does not currently affect any cleaves, but it should. Check the logs I linked please, you can clearly see cleave abilities taking the 95% cut just like AOEs. It's facts, numbers, from 3.3.5 parses, you can probably also find sniffs to confirm the damage of cleaves being that low on the adds.

**Comment by Keader** [comment]
https://youtu.be/-YMKonWG2-g?t=60
for cleave is true :O

**Comment by Dranah** [comment]
The only abilities I didn't link logs to show damage are blade flurry and Sweeping strike.
And you know why? because there does not exist a log where anyone would use those abilities. No melee DPS are stupid enough on retail to purposefully cleave the adds, since it does no damage and grabs aggro and causes a wipe.

**Comment by Keader** [comment]
already fixed btw '-'

**Comment by Dranah** [comment]
all of them or just cleave?

**Comment by Keader** [comment]
all, they all have same case

**Comment by Dranah** [comment]
<3

**Comment by crulinjr** [comment]
The ability showed on the video is whirlwind. He does reduced dmg on WW

**Comment by crulinjr** [comment]
Also do you know how are they aoe stunning the adds as soon they spawn?

**Comment by Keader** [comment]
my guess? holy wrath

**Comment by crulinjr** [comment]
Me too but i thought they have the beast designation not undead. Maybe they
fixed it later and this is an early video?

**Comment by Dranah** [comment]
@Keader Blade flurry and Multi-shot still deals full cleave damage. That needs fixing.
The other spell IDs are now fixed.
Chain lightning and the single target damage from Starfall stars retains their full damage as intended.

**Comment by Kitzunu** [comment]
Does Fan of Knives get the reduced dmg too?

**Comment by Dranah** [comment]
@Kitzunu yes, that works as intended

**Comment by crulinjr** [comment]
The only part that should not do reduce dmg is the instant poison.

**Comment by Keader** [comment]
try now.

**Comment by Dranah** [comment]
Multi-shot fixed, Blade flurry still full damage.
