### ISSUE TITLE
[Spell] Feign Death NOT cancelling Distracting Shot

### ISSUE THREAD

**Issue by crulinjr** [WoWManiaUK/Redemption#3508]
How it is working: Atm when you use distracting shot and then feign death the target will still run at you and hit/kill you. If you hit a world mob with distracting shot and then feign death it will make a weird iteraction where the mob will stay still with the debuff and then go back when its over. 

How it should work: Feign Death should just cancel Distracting shot period. It was one of the best tools for hunters on raids to gain more time for healers to Brez tanks or when a boss got enraged.

**Comment by Keader** [comment]
it's not a issue i belive.
Attack Me effects normally has some duration and it make creatures dont change target until this duration ends.

**Comment by wow-mania** [comment]
As-is.

**Comment by crulinjr** [comment]
https://wowwhimsy.wordpress.com/2009/06/01/hunter-bag-of-tricks-no-3-feign-death/

An article back from retail. Dated 2009. States: "You can also use it to
ping pong aggro between you and your pet, if you need to give you pet some
breathing space to heal up when he is low on health.   Throw on a mend pet,
hit distracting shot, mob runs for you, slow him or kite him if you like,
maybe even take a hit, when your pet is ready to retake aggro, hit feign
death."

You have the option to take the hit or feign death before hand depending if
you want to give your pet more time to heal  . This means Feign Death
SHOULD drop Distracting Shot. Seems you like to just erase or close my
threats without giving it an actual thought or research.
