### ISSUE TITLE
[Spell] Sentry Totem - Shaman

### ISSUE THREAD

**Issue by reponi** [WoWManiaUK/Redemption#3511]
![WoWScrnShot_082419_010521](https://user-images.githubusercontent.com/22345676/63628532-44a43f00-c60d-11e9-9cb1-0b9f471b022b.jpg)
![WoWScrnShot_082419_010524](https://user-images.githubusercontent.com/22345676/63628533-44a43f00-c60d-11e9-8fc4-609e084c709b.jpg)

**What is Happening:**

the totem teleports to a place far away from me

**What Should happen:**

If I push it out at the totem bar or summon a new totem I may wait 5 minutes then it will not come up with a reset. If I use totem recall then the error comes up

PS.:
the bottom right shows that 3 seconds have elapsed between the two images

**Comment by Keader** [comment]
I will close it, because to fix this issue, need fix other (grid unload for totems).
Sooo, even if i fixed it, without fix grid unload will not make any difference.
