### ISSUE TITLE
[Profission] Prospecting

### ISSUE THREAD

**Issue by WhitephoenixTheBunny** [WoWManiaUK/Redemption#3512]
The skill [Prospecting ](http://www.wow-mania.com/armory/?spell=31252)is atm giving skills on Jewcrafting (leveling it) and it shouldn't.

> Note that prospecting ore will never grant a skill point in Jewelcrafting.
in: https://wowwiki.fandom.com/wiki/Prospecting

**Comment by Dranah** [comment]
Still grants skill up.

**Comment by wow-mania** [comment]
was not deployed yet. where did you test it?

**Comment by Dranah** [comment]
I'm testing on the PTR.

**Comment by Keader** [comment]
build was broken, test now.
