### ISSUE TITLE
[Profission] Mining

### ISSUE THREAD

**Issue by WhitephoenixTheBunny** [WoWManiaUK/Redemption#3513]
[Mining ](http://www.wow-mania.com/armory/?spell=32606) should have level requirment in Northrend:

> Wrath-Logo-Small Patch 3.2.0 (04-Aug-2009): In addition to the normal requirements, mining deposits in Northrend now require a minimum character level of 65 to mine.

in: https://wowwiki.fandom.com/wiki/Mining

![image](https://user-images.githubusercontent.com/31921098/63636751-78ae4d00-c66b-11e9-8284-9cc12e134564.png)

**Comment by wow-mania** [comment]
We already have a requirement to go to Northrend so this is not that important. Also we need to know what 3.3.5a was.
