### ISSUE TITLE
[Profission] Prospecting Northrend Ores

### ISSUE THREAD

**Issue by WhitephoenixTheBunny** [WoWManiaUK/Redemption#3514]
Prospecting Northrend ores have drop rate lower than it should, I have checked several sources and all show they are correct, some lower, others highers, and I haven't find any patch change over the droprate value.

[Cobalt Ore Prospecting:](http://www.wow-mania.com/armory/?item=36909#prospecting)
![image](https://user-images.githubusercontent.com/31921098/63636923-21f64280-c66e-11e9-8432-9ffd1c4c58d4.png)

[On wowwiki:](https://wowwiki.fandom.com/wiki/Prospecting)
![image](https://user-images.githubusercontent.com/31921098/63636945-523de100-c66e-11e9-897a-b494f1dac7b8.png)
extra info: https://wowwiki.fandom.com/wiki/Cobalt_Ore

[Saronite Ore Prospecting](http://www.wow-mania.com/armory/?item=36912#prospecting)
![image](https://user-images.githubusercontent.com/31921098/63636958-81545280-c66e-11e9-8f50-8d77689df28b.png)

[On wowwiki:](https://wowwiki.fandom.com/wiki/Prospecting)
![image](https://user-images.githubusercontent.com/31921098/63636967-96c97c80-c66e-11e9-8458-fc13d5092f4e.png)
Extra info: https://wowwiki.fandom.com/wiki/Saronite_Ore

[Titanium Prospecting Ore](http://www.wow-mania.com/armory/?item=36910#prospecting)
![image](https://user-images.githubusercontent.com/31921098/63636970-b660a500-c66e-11e9-9c3c-98f8f1750c2a.png)
![image](https://user-images.githubusercontent.com/31921098/63636971-bc568600-c66e-11e9-8333-95737b8dfcbb.png)

[On wowwiki:](https://wowwiki.fandom.com/wiki/Prospecting)
![image](https://user-images.githubusercontent.com/31921098/63636977-dbedae80-c66e-11e9-8cd7-a179376a1c67.png)
Extra info: https://wowwiki.fandom.com/wiki/Titanium_Ore

Need someone to confirm this

**Comment by wow-mania** [comment]
Both sites show situation as in retail.
Our rates were as they should as per 3.3.5a.

**Comment by WhitephoenixTheBunny** [comment]
I have checked other armorys (other servers) and all have the drop slight higer... i will recheck which ones
