### ISSUE TITLE
[Mechanic] DoTs and HoTs don't put you in combat

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#3516]
This is some recent issue.

**How it works:** DOT and HoT effects, be it a debuff/buff, channeled, or area effect, don't seem to engage your character in combat with a target that has another person on 1# aggro.
Only if you are the 1st on threat list it makes you enter combat (if youre the one who pulls, or you take aggro).
Here are some screens for proof where I have used Entangling roots on a mob, or Rejuvenation on his target, and my character is still out of combat, so I can freely drink or prowl or do anything I wish while I only use Dots and Hots and the other person maintains aggro.
![WoWScrnShot_082419_152313](https://user-images.githubusercontent.com/31132743/63638005-57595b00-c683-11e9-8cf1-b475ed76e4c5.jpg)
![WoWScrnShot_082419_151710](https://user-images.githubusercontent.com/31132743/63638006-5d4f3c00-c683-11e9-9acc-7e410f2cdb65.jpg)

**How it should work:** Applying a DOT to an enemy, or a HOT to a friendly target that is engaged in combat with an enemy, should immediately put your character into combat as well.

**Comment by Keader** [comment]
Check if one of your character has any immune effect aura.
I cant reproduce, working fine to me.

**Comment by Dranah** [comment]
It happens on all of my characters on live realm too. I can literally sit through drinking whole dungeon fights while my hots are ticking on the tanks and I keep enemies rooted.

**Comment by Keader** [comment]
I can mais a vídeo If you want...
Not general.issue.

**Comment by Dranah** [comment]
In that case, I suppose i'm free to abuse the unfair advantage it gives :D
