### ISSUE TITLE
[Spell/Pet] Succubus bugs out when she has no mana to cast Seduction

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#3517]
spell ID=712 summon succubus
spell ID=6358 seduction

**How it works:** When the pet is on /stay and has Seduction enabled to autocast, and she attempts to cast Seduction with no mana to do so, she runs off in a random direction for no reason and stays there until combat ends.

Repro Steps:
1.Set pet on /stay
2.Set Seduction on Autocast
3.Make succu attack
4.She will keep casting Seduction until she's oom.
5.When she can no longer use it, she runs off.
6.You can use /petfollow to call her back, but commanding her to attack will make her run off again.

Result is as seen on screen:
![WoWScrnShot_082419_153334](https://user-images.githubusercontent.com/31132743/63638252-1878d480-c686-11e9-9670-1ed018a2d31a.jpg)

**How it should work:** The succu should go into melee range of target and begin to melee attack when she has no mana to use seduction anymore.

**Comment by Keader** [comment]
When dont have mana, should stay (if stay is active).

**Comment by Dranah** [comment]
Not if you command her to attack. She is a melee DPS on wotlk, not a ranged like on cata. (on cata, she is unable to melee)

**Comment by Keader** [comment]
ah, in this case yes

**Comment by Dranah** [comment]
I misunderstood. I thought she wouldn't be able to melee at all. This fix is good.
