### ISSUE TITLE
[Boss/Spell] Nature Bomb - Freya

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#3521]
https://www.wowhead.com/npc=32906/freya#encounter
https://www.wowhead.com/spell=64606/nature-bomb
https://www.wowhead.com/npc=34129/nature-bomb

Four problems with these sweet green love-bags- In order of importance:

1) They can spawn in phase1
**How it works atm:** Their timer seems to begin when 1minute has passed since the last wave of adds spawning, not when you actually start phase2.
This means if you're a tad too slow on killing the last wave of adds, or you're doing the achievement to keep stacks on freya, she will begin putting bombs on you regardless of being in phase2 or not.
**How it should work:** This is strictly a phase2 ability and phase2 begins when Freya loses all stacks of Attuned to Nature. She should not ever spawn them when she is still in phase1 (still any adds up and still has some stacks).

2) They have a physical body which behaves as an obstacle and can give LoS. 
They cannot be walked through and multiple bulbs near each other can get your character stuck, barely able to escape with a ton of jumps. You will have your line of sight blocked towards players on the other side of the bulb, preventing heals etc.
**How it should work:** The bulbs don't behave like a physical obstacle on retail. Should not block your character from walking through them, should not grant line of sight.

3) The bombs can spawn in the air
Combined with the other issue above, this resulting in characters getting stuck, getting line of sight, and generally, why are bombs in the air?!
**How it works atm:** The bombs seem to check for the altitude of the character they target, not only their map position. If the character is jumping when the bombs are cast (and man, you jump a lot, due to the issue described above), the bomb will appear mid-air where the character was in the moment of jump.
**How it should work:** The bombs should always spawn on the ground in the position where the character is.

4) The bulbs don't despawn when they explode
As phase2 progresses, the room slowly fills up with dead bulbs forming obstacles to jump over everywhere. If you wipe and the fight resets, they still remain where they are, and you can spend the next 10minutes while rebuffing with clicking every bomb 1 by 1 to make them disappear. Right clicking them (like the Dire Maul bulbs that can be opened for roots) is the only means to get rid of their physical form.
**How it should work:** Once the bombs explode, they should disappear with the same visual as they do now when you click their empty shells.

Video proof to see how the bulbs should disappear after the bomb exploded:
https://www.youtube.com/watch?v=mc2ZOf3CkKA

**Comment by Keader** [comment]
Rest is fixed.
But i cant disable collision of one object.
It come from blizzard files and nothing can edit it :/
