### ISSUE TITLE
[Spell] Fireball DOT benefits from Empowered Fire

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#3522]
Spell ID 42833 fireball
same problem with this dot spell as with FFB here https://github.com/WoWManiaUK/Redemption/issues/3488

**How it should work:** Shouldn't get 15% SP per tick from the talent Empowered Fire (spell ID 31656). Should never have any SP coefficient at all.
**How it works atm:** gets 15% SP per tick from the talent empowered fire.

**Comment by Drostthehunter** [comment]
Id like to add that in 99% this does not make any difference, any fire mage should have Fireball glyphed and Fireball DoT removed completely

**Comment by Dranah** [comment]
thanks we have discussed it in the previous thread :P and came to the conclusion this bug might make the DoT powerful enough to be worth not glyphing the ability, which would be very-very not blizzlike
therefore needs fixing,
