### ISSUE TITLE
[Quest / POI] A Portable Power Source

### ISSUE THREAD

**Issue by WhitephoenixTheBunny** [WoWManiaUK/Redemption#3523]
The quest [A Portable Power Source](http://www.wow-mania.com/armory/?quest=8925) send collect [Magma Core](http://www.wow-mania.com/armory/?item=21938) to the wrong map.

Quest on the quest log:
![image](https://user-images.githubusercontent.com/31921098/63641075-60a4f080-c6a0-11e9-8131-cd7b130f8b84.png)

Info on armory:
![image](https://user-images.githubusercontent.com/31921098/63641081-731f2a00-c6a0-11e9-9c85-2fb39534d432.png)

![image](https://user-images.githubusercontent.com/31921098/63641146-60592500-c6a1-11e9-991e-abd81ec498f0.png)

**Comment by Kitzunu** [comment]
test now
