### ISSUE TITLE
Nethermancer Encounter Door

### ISSUE THREAD

**Issue by Blyatman1** [WoWManiaUK/Redemption#3524]
The gate at the top of the elevator in The Mechanar is able to be interacted with (when open, to close it). If a player interacts with it, while being on the elevator side of the gate, they are locked behind it, can't interact with it again to open it, and can no longer progress.
http://wow-mania.com/armory/?object=184449

**What is Happening:** Gate is able to be interacted with.

**What Should happen:** Gate should not be able to be interacted with.

![WoWScrnShot_082419_171426](https://user-images.githubusercontent.com/35879017/63642850-bd4dde80-c693-11e9-925e-6bdd530b5f06.jpg)
![WoWScrnShot_082419_171435](https://user-images.githubusercontent.com/35879017/63642851-bd4dde80-c693-11e9-8d7d-d1bd89b86213.jpg)

**Comment by Kitzunu** [comment]
Somehow https://github.com/WoWManiaUK/Redemption/issues/3134 must have been reverted.

Fixed, can no longer target or press them

**Comment by Oganku** [comment]
The door before the last boss of Karazhan (Prince Malchezaar) has the exact same issue btw.
