### ISSUE TITLE
[Item/Quest] Oscillating Frequency Scanners

### ISSUE THREAD

**Issue by jarvik76** [WoWManiaUK/Redemption#3526]
**Links:**
http://www.wow-mania.com/armory/?item=30701
(used for quest http://www.wow-mania.com/armory/?quest=10594)

**What is Happening:**
The item has a 5 second cooldown whether you can place the item or not (i.e. still have the debuff from being too close to another totem)

**What Should happen:**
The item should only get the on-use cooldown if placing the totem is successful.
For details See https://youtu.be/9I683HKPMJo?t=38

**Comment by wow-mania** [comment]
As-is. It does not stop the quest in any way.

**Comment by jarvik76** [comment]
It makes it incredibly hard since the totems have a low existence timer, and is most definitely not as was in retail.
