### ISSUE TITLE
[Quest / POI] The Path of the Righteous

### ISSUE THREAD

**Issue by WhitephoenixTheBunny** [WoWManiaUK/Redemption#3527]
The quest [The Path of the Righteous](http://www.wow-mania.com/armory/?quest=8301) doesn't show on map the location of the quest. The quest items, [Silithid Carapace Fragment](http://www.wow-mania.com/armory/?item=20384#dropped-by), can drop in Silithus and Un'Goro Crater.

![image](https://user-images.githubusercontent.com/31921098/63682407-cb187680-c7ef-11e9-9848-c1b2de70ff85.png)
![image](https://user-images.githubusercontent.com/31921098/63682685-60b40600-c7f0-11e9-9c15-2d4b899fdcec.png)

![image](https://user-images.githubusercontent.com/31921098/63682733-7a554d80-c7f0-11e9-8691-4349415c6a84.png)

**Comment by Rushor** [comment]
hm i don't think they should have any kind of points on the map :o

**Comment by WhitephoenixTheBunny** [comment]
no?
For what I have found, some quest that show as "raid" event outside instance doesn't show... but this one doesn't show "raid" option

**Comment by wow-mania** [comment]
I will mark this as-is for now as there seems to be no info from sniff or any other source.
