### ISSUE TITLE
[Game Mechanic] Glancing Blows unstable numbers.

### ISSUE THREAD

**Issue by crulinjr** [WoWManiaUK/Redemption#3528]
https://wowwiki.fandom.com/wiki/Glancing_blow

What is Happening: When reading the recount it seems that the glancing blows number are too unstable going from 19% up to 29%. 

What Should happen: The % of glancing blows should be around 24% almost everytime.

**Comment by wow-mania** [comment]
This is statistical.

**Comment by crulinjr** [comment]
Again closing reports without a proper respond. 29% on Glancing blows is
not ok. Either 19%
