### ISSUE TITLE
[Boss] Halion and Killing Spree

### ISSUE THREAD

**Issue by crulinjr** [WoWManiaUK/Redemption#3529]
What is Happening: As a rogue when using Killing Spree at Dragon fights mostly Halion and Sindragosa, the spells bugs and you need to go under their belly for the spell to activate, however other spells like Sinister Strike works well at max melee range while Killing Spree doesnt

What Should happen: Like every other rogue spell, Killing Spree should work correctly at any given distance towards the enemy Dragon Boss.

**Comment by wow-mania** [comment]
Not going to change this.

**Comment by crulinjr** [comment]
If not, why? Any reasoning?
