### ISSUE TITLE
Herbs Spawn Rate & More Instanzes per Hour

### ISSUE THREAD

**Issue by LaughingNighty** [WoWManiaUK/Redemption#3531]
Hi,
1. Is a Issue:
There are almost no Herbs in alot of the regions. "Start Regions. Outland Northrend " for example im trying to Skill Herb&Alchi and i need to farm in Outland the prob was that the herbs spawn rate is something like 1h and when there are more than 3 people farming outland you can forget about skilling. About Northrend there are almost no Herbs = Goldclee for example i fond 4 spawns in Tundra and 2 in Sholo and the spawn rate isnt that great ether. The other thing is the amount of herbs you get per collecting/picking up (Sry i dont know the words to discribe it xD) Example i get almost every time 1 Felweed from 1 Spawn which means if you can collect alot of  the spawns in Teroka/Hellfire you can get around 16-30 herbs which is a joke if you think about the respawn time, which btw on the Retail Game was 6 Min

2. Is a advice:
It would be cool if you would chance the Amount of Instances per Hour from 5 to 8 or just change the reset from 1h to 30 min.

**Comment by Kitzunu** [comment]
First off: Use the Issue template when creating an issue for consitency
2ndly: Please provide proof, for example "Retail game was 6 min", we need a source that can confirm that statement
3rd: Dont report more than 1 issue in a report
4th: Suggestions are supposed to be made in Discord or Forum
