### ISSUE TITLE
[Game mechanic] Glancing Blows

### ISSUE THREAD

**Issue by crulinjr** [WoWManiaUK/Redemption#3535]
https://wowwiki.fandom.com/wiki/Glancing_blow

What is Happening: From the Link we can know that Blizzard made the Glancing Blows to be around the 24% however this is not the case for Wow Mania where a player can get from 19% up to 29% glancing blows. This is specially benefitial or detrimental for the classes that attack faster since they will get either a dps boost or a dps decrease due to this unstable number that we get on the server.

What Should happen: Glancing blows should be coded in a way that the melee classes should have a expected percentage of 24 or as close as 24 instead of the 19-29 interval.

**Comment by wow-mania** [comment]
Will need someone to confirm this but as I said this seems statistical variance.

**Comment by Dranah** [comment]
It's simply how RNG works, yes.
