### ISSUE TITLE
[Spell] Feign Death + Distracting Shot

### ISSUE THREAD

**Issue by crulinjr** [WoWManiaUK/Redemption#3536]
https://wowwiki.fandom.com/wiki/Feign_Death
https://wowwiki.fandom.com/wiki/Distracting_Shot

What is Happening: Atm Feign Death is not cancelling distracting shot anymore. If used on a Boss the only way of getting it away from you is either use deterrence or taunt it back.

What Should happen: Feign Death should be cancelling Distracting Shot since the Boss wont have any target available and go back to the highest threat player. This combo have been used since retail to be able to solo Elite quests by giving time for your pet to take more mend pet ticks while you kite the add and using Feign Death to the last moment until your pet can tank again.

**Comment by crulinjr** [comment]
Found this video dated to 2012 not sure if cata or mop but ar 1:28 the
hunter uses Feign while the boss has distracting shot on and succesfully
dropping any targetting. Please re open https://youtu.be/r5np6lU4jLA

**Comment by Kitzunu** [comment]
this was fixed @crulinjr

**Comment by crulinjr** [comment]
This is dated back to Cata by looking at the vid again. On BFA the combo is
working the way it is working in wow mania. Meaning the made this change
after wotlk and Cata.
