### ISSUE TITLE
[Mobs] in Pit of Saron immune to spell

### ISSUE THREAD

**Issue by cathyr1** [WoWManiaUK/Redemption#3537]
The two first bosses in Pit of Saron: http://www.wow-mania.com/armory/?npc=36476 and http://www.wow-mania.com/armory/?npc=36494 are immune to spell Deep Freeze http://www.wow-mania.com/armory/?spell=44572.

This spell should stun the target and when the target is immune, then does frost damage instead. This is working for all other bosses I tried but these 2 are immune for both stun and dps that shouldn´t be right behavior. They are not immune to frost damage as the frostbolt does full dps to them so the Deep Freeze should also.

To test this, you need to have this talent http://www.wow-mania.com/armory/?spell=44545 to be able to use Deep Freeze against bosses.

**Comment by wow-mania** [comment]
as-is mobs have the correct immunity.
