### ISSUE TITLE
[NPC] Crank Fizzlebub

### ISSUE THREAD

**Issue by WhitephoenixTheBunny** [WoWManiaUK/Redemption#3538]
The NPC [Crank Fizzlebub](http://www.wow-mania.com/armory/?npc=2498) keeps showing ! after completing all quests provided by the NPC (information confirmed by a GM). Psygoa told me I was missing a quest and I went check on dev.

![image](https://user-images.githubusercontent.com/31921098/63805092-92bc8980-c910-11e9-8653-39ff81f575c0.png)

![image](https://user-images.githubusercontent.com/31921098/63804984-538e3880-c910-11e9-8158-099522c825e2.png)

The quest [Fool's Stout ](http://www.wow-mania.com/armory/?quest=1127#conditions) only show up if [Zanzil's Mixture and a Fool's Stout](http://www.wow-mania.com/armory/?quest=1119) fails (times ran up)

![image](https://user-images.githubusercontent.com/31921098/63805126-a49e2c80-c910-11e9-9878-1aeb2d93d1f4.png)

So, the npc keeps showing the ! yellow after completing the [Zanzil's Mixture and a Fool's Stout](http://www.wow-mania.com/armory/?quest=1119) in time, and it should disappear, as [Fool's Stout ](http://www.wow-mania.com/armory/?quest=1127#conditions) is "optional".

![image](https://user-images.githubusercontent.com/31921098/63805285-078fc380-c911-11e9-9399-85c2eabe42fa.png)

**Comment by Kitzunu** [comment]
If you only have fools stout it should turn to a blue ?

But I guess this wont be looked into, too many reports like this has already been closed as-is by janitor.

My guess is that some condition or smt is wrong in the core making these visual bugs for seversl of the  npcs

**Comment by WhitephoenixTheBunny** [comment]
When you do the quest on the first try (Zanzil's Mixture and a Fool's Stout), Fool's Stout will not appear.
