### ISSUE TITLE
[Quest] Hunting for Ectoplasm

### ISSUE THREAD

**Issue by IvanLlanas** [WoWManiaUK/Redemption#3539]
Hunting for Ectoplasm (quest): http://www.wow-mania.com/armory/?quest=8924
Mux Manascrambler (quest giver): http://www.wow-mania.com/armory/?npc=16014
Ectoplasmic Distiller (provided item): http://www.wow-mania.com/armory/?item=21946

I'm in Silithus (61, 53), I have 8x[Goblin Rocket Fuel] in my inventory, and tried to use the Ectoplasmic Distiller but I got the error message:
**The spell is not available to you.**

**Comment by IvanLlanas** [comment]
I tried it in Corin's Crossing (54, 63) in Eastern Plaguelands and the result is the same.

**Comment by WhitephoenixTheBunny** [comment]
Hi.
I have done that quest 3 days ago, I had same issue. But when I killed and looted I got quest item without using the items.
You will need more Goblins Rocket Fuel on the next quest.

**Comment by IvanLlanas** [comment]
Confirmed. Thanks.

**Comment by Rushor** [comment]
wil check, the conditions are required for the item drop

**Comment by Rushor** [comment]
loot condition fixed in dev, corespellcast is strange. 

can you check that @Keader 

it's spell id: 27433

**Comment by Grimwaldo** [comment]
Hello, 
Iam on this quest and its still bugged, the quest item is not dropping from mobs. I've tested in corin's crossing in eastern plaguelands and in silithus.

**Comment by Rushor** [comment]
yeah in cata the spell works but not in wotlk. strange

**Comment by Rushor** [comment]
okay you can loot the creatures now https://i.imgur.com/uzEzEAS.jpg

the object is not required to loot. the spell will be fixed later.
