### ISSUE TITLE
[Object] Old Lion Statue

### ISSUE THREAD

**Issue by jarvik76** [WoWManiaUK/Redemption#3542]
**Links:**
http://www.wow-mania.com/armory/?object=31
(armory bugs out, also seen at: 
https://classic.wowhead.com/object=31/old-lion-statue)

Quests:
Turning in:  http://www.wow-mania.com/armory/?quest=94
Follow-up:  http://www.wow-mania.com/armory/?quest=248
EDIT:
Quest "Morganth" http://www.wow-mania.com/armory/?quest=249 is also likely available, since it is a follow-on quest also started by the object, however mallstone is on cd so cannot 100% verify.

**What is Happening:**
The Old Lion Statue in the mall are acting as the turn-in and questgiver for the above quests.  

![WoWScrnShot_082919_134303a](https://user-images.githubusercontent.com/46089380/63941869-66198680-ca64-11e9-9799-4a51d71fdf01.jpg)
![WoWScrnShot_082919_133818a](https://user-images.githubusercontent.com/46089380/63941872-66b21d00-ca64-11e9-9692-65de8b2b81d6.jpg)
![WoWScrnShot_082919_133842a](https://user-images.githubusercontent.com/46089380/63941870-66b21d00-ca64-11e9-8c42-98200db4e136.jpg)

**What Should happen:**
This statue is found in Redridge.  Quest turn-in and follow-up should only be available from the statue instance in Redridge.

**Comment by wow-mania** [comment]
As-is. This is a minor visual issue.
I will try to remove the !/? from the mall statues
Thanks for the report.
