### ISSUE TITLE
[NPC/Spells] Galak Assassin

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#3543]
https://classic.wowhead.com/npc=10720/galak-assassin

Three of these assassins spawn as an ambush event of "Protect Kanati Greycloud" (ID 4966) which is a popular quest in Thousand Needles. It's a level 27 quest where an average player has 700-900 health.
The problem is, these mobs are using high level abilities, instead of the ones they should have, essentially one-shotting any player in the appropriate level range.

**How it should work:**
They should have two abilities, https://classic.wowhead.com/spell=744/poison which does 26-28 damage per tick, and https://classic.wowhead.com/spell=6533/net which is just an immobilize effect with no damage.
They should not be casting anything else.

**How it works atm:**
They are using two high level abilities which are similar in name to their intended ones, but are wrong spells that someone gave to them by accident. They have a "Deadly Poison" which ticks for ~230 damage (one magnitude higher than their poison should be) and an "Electrified Net" that does 140-150 instant nature damage.
Both of these abilities are overpowered at the lvl 27-28 range and with 3 of the npcs spawning at once, even a heirloomed player does not stand a chance to survive it. Maybe a full 5man party, however this is meant to be a solo quest.

**Comment by Rushor** [comment]
i could fix that for ya if you which, it's database script

**Comment by Keader** [comment]
Please

**Comment by Rushor** [comment]
or no, i need npc_galak :D  it's a core script - could you send me that?

**Comment by Keader** [comment]
Tell to janitor send to you
I AM not in home

**Comment by Rushor** [comment]
alright fixed in dev
