### ISSUE TITLE
[Spell/Interaction] Divine Shield + Suffering

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#3544]
spell ID 642 divine shield
Spell ID 47990 suffering (voidwalker)

**How it works:** Suffering causes a magic debuff that impairs the target's hit chance on top of the taunt effect. This magic debuff is currently not removed as intended by paladins' bubble. 

**How it should work:** As all other magic debuffs from players, Suffering should also be cleansed off by the paladin bubbling.

**Comment by Dranah** [comment]
No change.

**Comment by wow-mania** [comment]
was not deployed yet. where have you tested it?

**Comment by Dranah** [comment]
On the PTR, obviously.

**Comment by Keader** [comment]
build was broken.
Test now.

**Comment by Dranah** [comment]
The effect is now properly removed by bubble.
However, a "side effect" arose, which is that my Voidwalker behaves like an imp now. Casts firebolts and has a blood pact effect active.I can see these abilities in the pet section of spellbook for him now and only since last night. (when i was testing yesterday, he was still okay)
I remade my test lock to be sure if it's not
![WoWScrnShot_090219_090952](https://user-images.githubusercontent.com/31132743/64096244-76ca4500-cd61-11e9-97dd-b5fd2459ecd5.jpg)

I made a 2nd warlock to be sure it's not some failure from my part, and the same happened, step to repro:
1) Make a lock, level it to 80
2) summon new voidwalker at level 80 (if your VW levels up with you, he doesn't get the imp spells, only after you resummon)
3) check spellbook or try to make it attack

**Comment by Keader** [comment]
Not remates.
This "bug" existe before any change Mine, since my fix only change interrupt flags

**Comment by Dranah** [comment]
Couldn't have existed, since I tested last night and it was fine. But okay, i'll open a new thread for it.
