### ISSUE TITLE
[NPC/Spell] Centipaars' Thrash

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#3545]
https://classic.wowhead.com/npc=5459/centipaar-tunneler
https://classic.wowhead.com/spell=3391/thrash

I encountered this issue with this specific NPC however the other Centipaar having the same ability seem to behave in a similar manner. (possibly all NPCs that use this same Thrash, as you can see a long list of them under the spell in wowhead)

**How it should work**: Thrash should proc off only regular melee attacks , should not chain procs from the extra attacks it gives. It should always be 1 regular melee + 2 thrash attacks when it procs.

**How it works atm:** They seem to spam Thrash and getting chain procs hitting 10-12 times every swing, killing players of appropriate level range in 1-2 shots.

PS: oddly, the Centipaar tunnelers shouldn't even possess this spell according to the wowhead list, however the other Centipaars should, therefore it still needs to be fixed.

**Comment by Rushor** [comment]
could fix that for ya if you wish

**Comment by Keader** [comment]
Please

**Comment by Rushor** [comment]
Creature ID List

https://wowgaming.altervista.org/aowow/?npc=23680
https://wowgaming.altervista.org/aowow/?npc=11372
https://wowgaming.altervista.org/aowow/?npc=14821
https://wowgaming.altervista.org/aowow/?npc=14882
https://wowgaming.altervista.org/aowow/?npc=11357
https://wowgaming.altervista.org/aowow/?npc=14750
https://wowgaming.altervista.org/aowow/?npc=9096
https://wowgaming.altervista.org/aowow/?npc=449
https://wowgaming.altervista.org/aowow/?npc=2560
https://wowgaming.altervista.org/aowow/?npc=1353
https://wowgaming.altervista.org/aowow/?npc=4479
https://wowgaming.altervista.org/aowow/?npc=2728
https://wowgaming.altervista.org/aowow/?npc=5977
https://wowgaming.altervista.org/aowow/?npc=478
https://wowgaming.altervista.org/aowow/?npc=6005
https://wowgaming.altervista.org/aowow/?npc=8299
https://wowgaming.altervista.org/aowow/?npc=7039
https://wowgaming.altervista.org/aowow/?npc=8981
https://wowgaming.altervista.org/aowow/?npc=9176
https://wowgaming.altervista.org/aowow/?npc=9777
https://wowgaming.altervista.org/aowow/?npc=7369
https://wowgaming.altervista.org/aowow/?npc=2717
https://wowgaming.altervista.org/aowow/?npc=5435
https://wowgaming.altervista.org/aowow/?npc=4023
https://wowgaming.altervista.org/aowow/?npc=5455
https://wowgaming.altervista.org/aowow/?npc=5456
https://wowgaming.altervista.org/aowow/?npc=5457
https://wowgaming.altervista.org/aowow/?npc=5458
https://wowgaming.altervista.org/aowow/?npc=5459
https://wowgaming.altervista.org/aowow/?npc=5460
https://wowgaming.altervista.org/aowow/?npc=7234
https://wowgaming.altervista.org/aowow/?npc=3256
https://wowgaming.altervista.org/aowow/?npc=3378
https://wowgaming.altervista.org/aowow/?npc=100
https://wowgaming.altervista.org/aowow/?npc=1202
https://wowgaming.altervista.org/aowow/?npc=1783
https://wowgaming.altervista.org/aowow/?npc=1791
https://wowgaming.altervista.org/aowow/?npc=4493
https://wowgaming.altervista.org/aowow/?npc=519
https://wowgaming.altervista.org/aowow/?npc=3722
https://wowgaming.altervista.org/aowow/?npc=3746
https://wowgaming.altervista.org/aowow/?npc=10639
https://wowgaming.altervista.org/aowow/?npc=12940
https://wowgaming.altervista.org/aowow/?npc=14282
https://wowgaming.altervista.org/aowow/?npc=14283
https://wowgaming.altervista.org/aowow/?npc=13088
https://wowgaming.altervista.org/aowow/?npc=10991
https://wowgaming.altervista.org/aowow/?npc=16216
https://wowgaming.altervista.org/aowow/?npc=8138
https://wowgaming.altervista.org/aowow/?npc=7268
https://wowgaming.altervista.org/aowow/?npc=3636
https://wowgaming.altervista.org/aowow/?npc=11043
https://wowgaming.altervista.org/aowow/?npc=10414
https://wowgaming.altervista.org/aowow/?npc=10416
https://wowgaming.altervista.org/aowow/?npc=10407
https://wowgaming.altervista.org/aowow/?npc=4540
https://wowgaming.altervista.org/aowow/?npc=12258
https://wowgaming.altervista.org/aowow/?npc=11782
https://wowgaming.altervista.org/aowow/?npc=16593
https://wowgaming.altervista.org/aowow/?npc=17397
https://wowgaming.altervista.org/aowow/?npc=29392
https://wowgaming.altervista.org/aowow/?npc=29033
https://wowgaming.altervista.org/aowow/?npc=18631
https://wowgaming.altervista.org/aowow/?npc=1696
https://wowgaming.altervista.org/aowow/?npc=4855
https://wowgaming.altervista.org/aowow/?npc=5267
https://wowgaming.altervista.org/aowow/?npc=7320
https://wowgaming.altervista.org/aowow/?npc=7446
https://wowgaming.altervista.org/aowow/?npc=9164
https://wowgaming.altervista.org/aowow/?npc=9167
https://wowgaming.altervista.org/aowow/?npc=10488
https://wowgaming.altervista.org/aowow/?npc=11442
https://wowgaming.altervista.org/aowow/?npc=11486
https://wowgaming.altervista.org/aowow/?npc=11677
https://wowgaming.altervista.org/aowow/?npc=12138
https://wowgaming.altervista.org/aowow/?npc=13285
https://wowgaming.altervista.org/aowow/?npc=639
https://wowgaming.altervista.org/aowow/?npc=18105
https://wowgaming.altervista.org/aowow/?npc=5709
https://wowgaming.altervista.org/aowow/?npc=3456
https://wowgaming.altervista.org/aowow/?npc=9267

**Comment by Rushor** [comment]
creatures which use the spell 'Trash' will now only use it if they are in range to a victim (0-2 yards)

**Comment by wow-mania** [comment]
Where is the fix for this? code or sql?
Can you mark it fixed if it is please?

**Comment by Dranah** [comment]
No change, the thrash still chain procs up to 12-14 hits per swing.
I don't understand what you mean by in range of victim @Rushor , I didn't report anything about the range. The problem is the fact it can endlessly chain proc and oneshot a player like Windfury on vanilla. This is not intended.

**Comment by wow-mania** [comment]
server needs restart

**Comment by Dranah** [comment]
This is still broken, even on the PTR. Please dont close thread until the fix is active on at least the PTR.

**Comment by Rushor** [comment]
okay new try, ALL npcs with trash ability will now only cast the proccaura http://cata.cavernoftime.com/spell=12787 on respawn. (and not in range or every few seconds)

**Comment by Dranah** [comment]
No more chain procs, that worked fine. But there seems to be an issue with the aura disappearing if the mob drops combat (doesnt die and respawn, but a player engages and then resets the mob).
Basically, if you pull, run away, mob resets, his aura is gone and then if you engage him, he won't use thrash at all.

**How it should work**: the npc should retain the aura when reseting combat without dying or respawning. Or he should recast it upon being engaged

**Comment by Rushor** [comment]
okay the aura will now be added on each reset of the creature. (so it will be casted on spawn and then after each combat leave)
