### ISSUE TITLE
[Item/Loot] DK Tier 8 Tanking Gloves / Shoulders

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#3546]
Ok, this is an odd one. It seems to be that we have some wrong item IDs set into mania's armory/database/whatever for certain slots of this tier armor.
1) Hands
**How it should work:**
DK tier 8 tanking gloves should be these "Conqueror's Darkruned Handguards" item ID 46236
![tank hands](https://user-images.githubusercontent.com/31132743/63981334-fa183c00-cabe-11e9-8bb3-d53e842db7f8.png)

**How it works atm:**
DK tier 8 tanking gloves are replaced by a misc item that has similar name but no stats and wrong tier bonus. "Conqueror's Darkruned Gauntlets" item ID 46119
![WoWScrnShot_082019_163500](https://user-images.githubusercontent.com/31132743/63981484-92162580-cabf-11e9-89b8-dcae741cb8e1.jpg)

This item is currently dropping from loot on Emalon and is available from the vendor to purchase in place of the actual DK T8 tanking gloves that should be present.

2) Shoulders
**How it should work:**
DK tier 8 tanking shoulders should be this "Conqueror's Darkruned Pauldrons" ID 46240
![tankshoulder](https://user-images.githubusercontent.com/31132743/63982364-79f3d580-cac2-11e9-987f-4688a7f017a7.png)

**How it works atm:** 
DK tier 8 tank shoulders are replaced by a misc item with similar name but no stats and wrong tier bonus: "Conqueror's Darkruned Shoulderplates" item ID  46122
![wrongshoulder](https://user-images.githubusercontent.com/31132743/63982563-39e12280-cac3-11e9-83cd-6eff52e1b136.png)

This one is on the vendor in place of the proper tanking shoulder item.

Need to swap item IDs in the game.
Note: Atlasloot seems to display the wrong IDs for some reason too.

**Comment by Dranah** [comment]
PS: @wow-mania can this have something to do with the recent fix on the tier colors?

**Comment by Dranah** [comment]
No change, still the wrong items on vendor.
![WoWScrnShot_090119_202123](https://user-images.githubusercontent.com/31132743/64080551-1e119280-ccf6-11e9-8798-724296ba3a2e.jpg)
![WoWScrnShot_090119_202154](https://user-images.githubusercontent.com/31132743/64080558-25d13700-ccf6-11e9-96f9-66e4d667eaf2.jpg)

**Comment by wow-mania** [comment]
server needs restart

**Comment by Dranah** [comment]
Still wasn't restarted? I'm testing on the PTR and there is no change.

**Comment by wow-mania** [comment]
Need to clear cache or you will not see it.
![image](https://user-images.githubusercontent.com/12248683/64101872-afb8e880-cd66-11e9-9c1c-af859dddaa06.png)

**Comment by wow-mania** [comment]
Also works on Red.

**Comment by Dranah** [comment]
Yes, I cleared cache and I can now see these stats too. However, 2 problems:
1) Now you fucked up the leg slot tier (this worked before)
![WoWScrnShot_090219_220335](https://user-images.githubusercontent.com/31132743/64132124-9a2ad980-cdcd-11e9-8102-87897a1349cf.jpg)
2) I understand you added the stats onto the misc item ID, but you forgot the set bonuses. This is the tanking set, and these items have the DPS bonus still. You need to fix them to have the tanking bonus. This is the intended tanking bonus:
![tankbonus](https://user-images.githubusercontent.com/31132743/64132132-b595e480-cdcd-11e9-95a0-df489e0e0c1e.png)

**Comment by wow-mania** [comment]
Please do not re-open

**Comment by Dranah** [comment]
They have no stats now and the set bonus is wrong. The t8 tank set in its current form is unusable so can you tell me why you keep closing the thread? I deleted my cache twice and I am checking my stats upon equip to rule out visual issues.
Here, watch my stats, it doesn't give anything but armor and it has wrong tier bonus:
![WoWScrnShot_090319_184109](https://user-images.githubusercontent.com/31132743/64192326-bd5f9280-ce7a-11e9-94a0-0389d769cd9b.jpg)

**Comment by wow-mania** [comment]
I have not changed anything on legs. if there is a problem on the legs open as a new issue. the other items have been resolved.
