### ISSUE TITLE
[Talent] Everlasting Affliction

### ISSUE THREAD

**Issue by JohnBrinkle** [WoWManiaUK/Redemption#3548]
**Links:**
Talent: http://www.wow-mania.com/armory/?spell=47205
Corruption: http://www.wow-mania.com/armory/?spell=47813
Seed of Corruption: http://www.wow-mania.com/armory/?spell=47836

**What is Happening:**
I've looked into the WoW Mania Armory and saw Everlasting Affliction not effecting
Corruption or Seed of Corruption (last one is mentioned for the first rank of this talent tho)

**What Should happen:**
I don't know if the armory is a direct representation of how the game handels
the spells - if so, Everlasting Affliction needs to add 5% bonus spell damage to Corruption
and Seed of Corruption.
If not - I am sorry for wasting your time, if it already does!

**Comment by Dranah** [comment]
Armory sucks. The talent does affect corruption in the game.
