### ISSUE TITLE
[Quest] Frostmane Hold

### ISSUE THREAD

**Issue by jarvik76** [WoWManiaUK/Redemption#3549]
**Links:**
http://www.wow-mania.com/armory/?quest=287

**What is Happening:**
Frostmane Hold (Quest ID 287) does not seem completable.  The objective "Fuly explore Frostmane hold" does not trigger at the supposed coordinates according to Wowhead.  
Have spent several minutes wandering the back of the cave, witnessed by GM Psygoa
Cannot find where this is supposed to trigger.  If there is a spot, it is incredibly small.
2.5.5, launcher, cache cleared

**What Should happen:**
Fully Explore Hold should trigger at about 21,51, on top of the bulging ridge at the back of the cave.

**Comment by wow-mania** [comment]
pretty sure it works

**Comment by wow-mania** [comment]
Explored the entire cave and it completed.
