### ISSUE TITLE
[Boss] Postmaster Malown [npc=11143]

### ISSUE THREAD

**Issue by whosthebost** [WoWManiaUK/Redemption#3551]
**Links:**
Postmaster Malown
[(http://www.wow-mania.com/armory?npc=11143)](url)
Stratholme Courier
[(http://www.wow-mania.com/armory?npc=11082)](url)
Postbox Key
[http://www.wow-mania.com/armory/?item=13303](url)

**What is Happening:**
To summon Postmaster Malown the player needs to kill the NPC Stratholme Courier and loot 3 Postbox Keys from him. The player then needs to open all three corresponding Postboxes. After opening the third Postbox Postmaster Malown should be summoned, but he does not appear.

**What Should happen:**
After following all of the above steps Postmaster Malown should appear.

*Note: I made a github post about this approximately 1 year ago, but it seems it wasn't fixed. Here's the link if it's helpful. [https://github.com/WoWManiaUK/Redemption/issues/2622](url)

**Comment by Rushor** [comment]
okay try now, after opening the boxess Postmaster Malown should spawn

**Comment by Rushor** [comment]
https://i.imgur.com/MORK31O.jpg

works now.

if you open 3 of the postboxes, on the third postbox the postmaster will spawn.

**Comment by whosthebost** [comment]
Thank you, I will try it tonight.
