### ISSUE TITLE
Skar'this the Heretic

### ISSUE THREAD

**Issue by Gainarrow** [WoWManiaUK/Redemption#3553]
**Links:**
http://www.wow-mania.com/armory?npc=22421
http://www.wow-mania.com/armory?quest=10900
http://www.wow-mania.com/armory?quest=13431

**What is Happening:**
Can`t pick up quest its a grey "!".
Those two quests stops me for finishing my quest chain.

**What Should happen:**
Take quest/remove "!"

**Comment by wow-mania** [comment]
as-is check requirements
