### ISSUE TITLE
[NPC/Pet] Warbot

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#3554]
https://www.wowhead.com/item=46767/warbot-ignition-key#comments
https://www.wowhead.com/item=46765/blue-war-fuel
https://www.wowhead.com/item=46766/red-war-fuel

"on 2009/06/17 (Patch 3.1.3) |   |  
If you get a friend and mix opposite fuel with each other they'll begin to fight, losing HP per attack. Pretty clever for non-combat pets."

"IF you had the Warbot, and you came across someone else who had it, if the fuels were opposing (one red, one blue) the two bots would fight. If they were the same color, they would be friendly to each other."

**How it works atm:** The pet is missing its interaction feature with other Warbots. The fuels don't do anything apart from their visual upon cast.
**How it should work:** Fuels should be able to charge your warbot with a color of blue or red. Two warbots with the opposite color should engage in a fight, eventually beating each other to death.

PS: Metaxa wants it fixed real bad for reasons I don't know.

**Comment by wow-mania** [comment]
This is a non-wotlk import. We did not import the effects and not even sure if it would be possible.

**Comment by Dranah** [comment]
This is a wotlk pet though, lmao. It was first available on LK during a promotion. Then it was later available again on MoP, but both ways, it existed on 3.3.5a and its effects did too. So it's not a custom addition.

**Comment by wow-mania** [comment]
What about the effects/features? Were they added later?

**Comment by Rushor** [comment]
blue warbot 34588, red warbot 34589

**Comment by Dranah** [comment]
these feature descriptions are all from WOTLK
what was added later was being able to buy more fuel from vendors, because originally you only had as much as you gained through the promotion

**Comment by Rushor** [comment]
if you mix each other the bot should reset to unfilled

**Comment by Rushor** [comment]
https://i.imgur.com/jKGtUYT.jpg

warbots are now fighting each other
