### ISSUE TITLE
[Spell/Mechanic] Disorient effects bugging on moving target

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#3555]
This is a major visual issue that was discovered and, seemingly fixed on TC already:
I found these
https://github.com/TrinityCore/TrinityCore/pull/18336
https://github.com/TrinityCore/TrinityCore/issues/15952

Basically, it's still broken here, and it's making hunters' life hard.
It affects all disorient effects but mostly causes a problem with Scatter shot due to the broken movement making them unable to land freezing arrow properly on the target.

**How it works atm:** Using a disorient effect (Scatter shot, Blind etc) on a target that is moving results in them doing a weird visual glitch with continuing to move forward, and then teleport super fast backwards, towards the direction they are turned by the effect.
As the threads on TC explain, it is a client-side issue, however it's the server's fault for not sending some packet.
**How it should work:** Using a disorient effect on a moving target should first stop the target's movement and then perform the same effect as it normally does.

**Comment by Keader** [comment]
Cant be fixed for now.
