### ISSUE TITLE
[NPC] Servant of the Throne

### ISSUE THREAD

**Issue by jarvik76** [WoWManiaUK/Redemption#3557]
**Links:**
https://www.wowhead.com/spell=70980/web-wrap#used-by-npc
https://www.wowhead.com/npc=36724/servant-of-the-throne#abilities
https://www.wowhead.com/npc=37012/ancient-skeletal-soldier#abilities

http://www.wow-mania.com/armory/?spell=70980#used-by-npc
http://www.wow-mania.com/armory/?npc=36724
http://www.wow-mania.com/armory/?npc=37012

**What is Happening:**
Servant of the Throne and Ancient Skeleton Soldier in the pre-Marrowgar trash are using web wrap.

**What Should happen:**
This ability should **only** be used by the Nerubar Broodkeeper in the same area and not be available to the above two NPCs.

**Comment by wow-mania** [comment]
I am fixing this because I found some other issue. But just remember that we can change scripts sometimes to improve the game/challenge.
