### ISSUE TITLE
[Pet/Spells] Voidwalker casting imp abilities

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#3558]
Recent issue, Voidwalker seems to receive imp spells when summoned at lvl 80.

He has a rank2 Firebolt (ID 7799) ,rank1 blood pact (ID 6307) and Phase shift (ID 4511), in addition to his regular Voidwalker abilities.
These IDs need to be removed from the Voidwalker.
![WoWScrnShot_090219_213534](https://user-images.githubusercontent.com/31132743/64131552-a14fe880-cdc9-11e9-8a56-aaaf05238a0a.jpg)

**Comment by Keader** [comment]
Cant reproduce.

![image](https://user-images.githubusercontent.com/7120913/64136833-d90b6000-cdca-11e9-9900-baff3948d019.png)

Following steps: https://github.com/WoWManiaUK/Redemption/issues/3544#issuecomment-527031233
