### ISSUE TITLE
Wintergrasp flight bug

### ISSUE THREAD

**Issue by Kallivira** [WoWManiaUK/Redemption#3560]
**Links:**
No Links for this behavior.

**What is Happening:**
In Wintergrasp, during the pvp event, all flying players are supposed to get a debuff called "Restricted flight Area" that will dismount them in 8 seconds. 

If a player joins a group, or raid during the duration of this debuff, it removes the debuff and forces it to start over after a couple of seconds. Doing this just once allows up to 30 seconds of flight time in Wintergrasp. 

**What Should happen:**
The debuff "Restricted flight Area" should persist regardless of the state of the players group.

**Comment by Rushor** [comment]
OnPlayerEnterZone change - please check now :)
