### ISSUE TITLE
[Herb] Netherdust Bush

### ISSUE THREAD

**Issue by cathyr1** [WoWManiaUK/Redemption#3561]
The respawn of this herb is surely bugged. After about 10 hours from gathering that still no 1 at the entire Netherwing Ledge respawned. It serves for daily quests for all herbalists so it should have similar cooldown like other herbs and veins. This is looted for the quest item linked here:
http://www.wow-mania.com/armory/?item=32468#gathered-from-object

**Comment by wow-mania** [comment]
As-is.
