### ISSUE TITLE
[Item] Dormant Wind Kissed Blade

### ISSUE THREAD

**Issue by Unstompable** [WoWManiaUK/Redemption#3563]
**Links:**
http://www.wow-mania.com/armory/?item=19019
http://www.wow-mania.com/armory/?quest=7787
**What is Happening:**
The problem that is occurring here is that I got all the Materials for Thunderfury I go Back to the quest giver to hand them in to be able to spawn the boss Prince Thunderaan, He spawns the boss and I kill him, He then drops the item I need to Proceed to the next quest step but it bugged out and wouldn't let me pick it up saying something like "I don't have permission to loot said item. the item is called Dormant Wind Kissed Blade one that I should Pick up after killed the Boss.

**What Should happen:**
I should Loot the item to proceed to the next step of the questline to get the Legendary Weapon

I wanna make it clear that I picked up the quest after faction changing and doing all my race changing things. I picked up the beginning of the quest when i race changed into a Orc

**Comment by WhitephoenixTheBunny** [comment]
Dormant Wind Kissed Blade: http://www.wow-mania.com/armory/?item=19018

**Comment by Rushor** [comment]
maybe you need to be in raid group to loot the item?

item will only be shown in loot if quest 7786 is rewarded

**Comment by WhitephoenixTheBunny** [comment]
![image](https://user-images.githubusercontent.com/31921098/64337898-3fb19900-cfd8-11e9-9135-da567bc281b2.png)

I have tested item dropped...
Do you have any other information that can help to reproduce?

@Rushor I didn't needed raid group

**Comment by WhitephoenixTheBunny** [comment]
Re-tested:

![image](https://user-images.githubusercontent.com/31921098/64338521-e3e80f80-cfd9-11e9-852f-23e7e1ca04e3.png)

![image](https://user-images.githubusercontent.com/31921098/64338537-ec404a80-cfd9-11e9-9962-1e6762cae3c8.png)

**Comment by Rushor** [comment]
seems fine to me too. once you added a way to reproduce the issue we will reopen it. thanks.

**Comment by Unstompable** [comment]
Also forgot to mention that I was in a raid with Master looter on when killing the Npc

**Comment by WhitephoenixTheBunny** [comment]
So far I know it may be that... I am going test with ML

**Comment by WhitephoenixTheBunny** [comment]
With ML

ML in durotar, char on quest in sil
![image](https://user-images.githubusercontent.com/31921098/64355199-b199da80-cff8-11e9-8a86-2b2d4ae251cd.png)


![image](https://user-images.githubusercontent.com/31921098/64355177-a8107280-cff8-11e9-9acd-e376c23affb6.png)

![image](https://user-images.githubusercontent.com/31921098/64355307-e1e17900-cff8-11e9-9277-c01ecb23488c.png)

**Comment by Unstompable** [comment]
Yeah that’s what it said for me and then I left group and the entire thing disappeared and I couldn’t get the boss to spawn again
