### ISSUE TITLE
Warsong Supplies quest cannot be completed due to missing item.

### ISSUE THREAD

**Issue by manshorts** [WoWManiaUK/Redemption#3564]
**Whats Happening:**
The quest [Warsong Supplies](http://www.wow-mania.com/armory/?quest=6571) cannot be completed because of the inability to obtain 1 item, [Warsong Axe Shipment](http://www.wow-mania.com/armory/?item=16745), from the NPC you are direct to talk to.  When speaking to [Wharfmaster Lozgil](http://www.wow-mania.com/armory/?npc=4631) located in Booty Bay, who is supposed to give you the item, he instead shows his default text and does not give the option to obtain the items needed for the quest.  I tried dropping the quest and restarting from the beginning, but this did not fix the problem.

**What Should Happen:**
When you arrive in Booty Bay, [Wharfmaster Lozgil](http://www.wow-mania.com/armory/?npc=4631) should provide a way to obtain [Warsong Axe Shipment](http://www.wow-mania.com/armory/?item=16745).

**Comment by wow-mania** [comment]
Item is obtained by looting crate.
