### ISSUE TITLE
[Spell] Nature's Grasp ICD

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#3566]
spell ID 53312

This ability grants you 3 charges of buff to entangle enemies who strike you in melee.
Problem is, currently there is no ICD on the charges being consumed, which leads to problems in PVP with i.eg. rogues consuming all 3 charges at once with swift attack and overriding the 8s duration root to 1sec and becoming immune with Diminishing Returns immediately.

**How it should work:** To counter this problem, Blizzard added a 1,5s internal cooldown to the spell, as explained here
https://www.engadget.com/2010/02/25/starfall-and-natures-grasp-ptr-changes/?guccounter=1&guce_referrer=aHR0cHM6Ly9naXRodWIuY29tL1N1bndlbGxUcmFja2VyL2lzc3Vlcy9pc3N1ZXMvNDk3&guce_referrer_sig=AQAAAD4rm2rX4EjAwypdOcK2LOkg3YkIYye8Viy7RxAS3mOT_697d_x0fK5s8S57SXESWJTL1GyOwWYk8gfXS4uL5FHHYAE8TMfk5yFBpGxTlrvs1jmVfo2KYy8JbCAAjP2hGCDyZbHtUJFJmDT5No1FEt6qmb71X51R2ArOomtohW1-

"Nature's Grasp is a self buff that causes things that hit you to become rooted. That effect now has 3 charges. There is a small internal cooldown in between roots to keep say a rogue who hits you twice very quickly from wasting two charges."
Judging by the date (2010 feb) this was a pre-icc patch and therefore it has been in effect on 3.3.5 as well.

**How it works atm:** There's no ICD currently, all 3 charges can be consumed at once.

**Comment by Dranah** [comment]
Well, now only 1 charge can be consumed and then its stuck on ICD forever, not being able to consume the other charges at all. I tried for 2-3minutes, left combat, recast the spell etc, wasn't able to trigger another charge.
Relogging seems to reset it alone :s

**Comment by Keader** [comment]
use .reload spell_proc_event and try again please.

**Comment by Dranah** [comment]
goodie

**Comment by Dranah** [comment]
This fix was reverted to the point where the spell is only able to consume 1 charge because the ICD then gets stuck for ages. Please reapply fix (think it had something to do with seconds vs milliseconds)

**Comment by Keader** [comment]
I made the fix again (idk who removed) and told to janitor execute on live.
Will be in ptr again after next server reset.
