### ISSUE TITLE
[Quest] Broodling Essence [ID: 4726]

### ISSUE THREAD

**Issue by Grimwaldo** [WoWManiaUK/Redemption#3567]
**Links:**
https://classic.wowhead.com/quest=4726/broodling-essence

**What is Happening:**

When i try to use the item provided on the small drakes and then kill them, they spawn the crystal, i try to loot the quest item from the crystal but it doesn't go into inventory and it disappears.
**What Should happen:**
the item should be looted normally from crystals and they should appear only when the item provided is used.

**Comment by wow-mania** [comment]
Works

**Comment by WhitephoenixTheBunny** [comment]
Tested with 2 chars, working now
