### ISSUE TITLE
[Object] Portal to Inner Maraudon

### ISSUE THREAD

**Issue by WhitephoenixTheBunny** [WoWManiaUK/Redemption#3570]
The [Portal to Inner Maraudon](http://www.wow-mania.com/armory/?object=178404) at 29.29 61.12 should be clickable.

Therefore the Scepter of Celebras was needed to create the portal, but on patch 3.0.8 the scepter is no longer needed to create.

> The  [Scepter of Celebras] is no longer required to create a portal to the Earth Song Falls area of inner Maraudon
in: https://wow.gamepedia.com/Patch_3.0.8_(undocumented_changes)#Dungeons_and_Raids

I belive the quest [The Scepter of Celebras](http://www.wow-mania.com/armory/?quest=7046) keep being a requirement to use portal.

**Comment by WhitephoenixTheBunny** [comment]
https://github.com/WoWManiaUK/Redemption/issues/2035 maybe side effect of... I am pretty sure the portal was working 2 years ago

**Comment by Rushor** [comment]
clickable now

**Comment by WhitephoenixTheBunny** [comment]
@Rushor is the quest a requirment?

**Comment by Rushor** [comment]
no

**Comment by WhitephoenixTheBunny** [comment]
not clickable

**Comment by Rushor** [comment]
oh i may forgot to restart. pls retest

**Comment by WhitephoenixTheBunny** [comment]
I still can't click...

**Comment by WhitephoenixTheBunny** [comment]
![image](https://user-images.githubusercontent.com/31921098/64561969-c30a1c00-d343-11e9-9da7-24989ebcbfda.png)

**Comment by Rushor** [comment]
works fine for me on dev. 

https://i.imgur.com/c2eRh8Q.jpg
https://i.imgur.com/vOzxzGR.jpg

you must be at least level 30

**Comment by WhitephoenixTheBunny** [comment]
I tested with a level 80.
