### ISSUE TITLE
Perma glancing warrior

### ISSUE THREAD

**Issue by diplo1** [WoWManiaUK/Redemption#3571]
**Links:**

**What is Happening:** My warrior after pressing an orb before blood queen's trash mobs started to glance 100% of attacks. I would like some help so I can play the toon again since none of the GM's that I have contacted was able to resolve this issue.

**What Should happen:** I should not be glancing 100% of my attacks.

**Comment by Dranah** [comment]
Cannot reproduce issue, my warrior can properly attack after using the orb.
If your character is bugged, please provide screens for proof and i'm sure Janitor will figure a way to help you.

**Comment by diplo1** [comment]
ss of what? my attacks hitting for 1.5k with shadowmourne?

**Comment by Dranah** [comment]
detailed recount chart show the amount of glancing attacks as a percentage if you click on your character name and mouse over melee

**Comment by Dranah** [comment]
like this is my test char after using the orb:
![WoWScrnShot_090919_012714](https://user-images.githubusercontent.com/31132743/64496026-0495bb00-d2a1-11e9-9cf6-206275733218.jpg)

Note, im testing with a naked, talentless char on purpose to rule out other factors.
Clearly the orb alone does not have any effect on your glancing attacks.
If a specific talent or ability is at play when it bugs, that's a needle in a haystack to find unless you can provide more information.
