### ISSUE TITLE
[Boss/Spell] Slime Spray (Rotface)

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#3572]
https://www.wowhead.com/npc=36627
https://www.wowhead.com/spell=69508/slime-spray

This ability is broken in a way that Rotface keeps turning after his target while channeling the spray.

**How it should work:** Rotface chooses a random player's direction and channels the entire spray facing that way, he no longer turns after he began the channel. So all players can move out of the cone and dodge the ability.
See video: https://www.youtube.com/watch?v=0V_rk3FGFNw you can see how the boss never turns after he already began channeling the spray, even if there is no one in front of him anymore.

**How it works atm**: Rotface keeps following the original target player with his spray, (turning around as he's channeling it) when the target attempts to move out of the cone to dodge the damage. 
Note: The target of the slime spray is hidden (not announced) as it does not usually matter, so it's a bloody mess because nobody knows who it is channeled at and nobody has a reason to sit still and eat the damage in the face, so all players try to move out and Rotface keeps turning after the raid.

**Comment by Rushor** [comment]
can add a solution based on event handling if you wish

**Comment by Rushor** [comment]
try now, reactstates are changed now and he should no longer change the orientation while casting

**Comment by Keader** [comment]
@Rushor this is wrong and a big hack.
Issue here is about Focus and release target system is broken.
Change to passive while casting is wrong.

**Comment by Dranah** [comment]
Still turns.

**Comment by Rushor** [comment]
next try

**Comment by Rushor** [comment]
nice

**Comment by Keader** [comment]
@Rushor 

SourceEntry 69508 SourceGroup 1 in condition table - spell 69508 does not have implicit targets of types: AREA, CONE, NEARBY, CHAIN for effect 0, SourceGroup needs correction, ignoring.

**Comment by Dranah** [comment]
This is reverted it seems. Fix stopped working on both PTR and Red after last update.

**Comment by Rushor** [comment]
on dev it does not work aswell?

**Comment by Dranah** [comment]
As I specified above, it doesn't. It did when I tested 6 days ago, it feels like something reverted it.

**Comment by Rushor** [comment]
hm yeah i see. it was reverted

**Comment by Rushor** [comment]
okay try again now pls. should be all back fixed.
