### ISSUE TITLE
[Boss/NPC] Little Ooze (Rotface)

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#3573]
https://www.wowhead.com/npc=36627/rotface
https://www.wowhead.com/spell=69674/mutated-infection
https://www.wowhead.com/npc=36897/little-ooze

These small adds are missing their head start of 500k threat on the target they spawn on.

**How it should work:**
When a Little ooze spawns off a target with Mutated Infection, they should have 500k threat on the target to begin with, making it pretty much only possible to aggro them off with a taunt.

You can see this on the threat meter of the offtank on this video:
https://phimpha.com/watch/ICC25-Catalyst-vs-Rotface-Tank-Pov
And is also explained on wowwiki: https://wowwiki.fandom.com/wiki/Rotface
"a random raid member gets Mutated Infection. This debuff ticks for some damage for 12 seconds, and then spawns a small Ooze with 500k aggro on the formerly infected player. "

**How it works atm:** 
The Little Ooze don't have any initial aggro on their target, causing random healing and AOE to aggro them off immediately. 
This makes it much more difficult to control the position of the Little Oozes, which is the blizzlike  strategy for doing the achiev "Dances with Oozes", by leaving small oozes on their original target to prevent them merging.

**Comment by Rushor** [comment]
threat doadded, try now :)

**Comment by Dranah** [comment]
The little ooze now has 500k threat but not towards the player who spawned him, but rotface lmao :D
![WoWScrnShot_091119_134906](https://user-images.githubusercontent.com/31132743/64694868-0d51e100-d49b-11e9-9fc6-59717d0bfcb3.jpg)
Need to gain threat towards the person whose infection spawned it, not the boss.
