### ISSUE TITLE
[Boss/NPC] Saronite Animus (General Vezax)

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#3574]
https://www.wowhead.com/npc=33271/general-vezax
https://www.wowhead.com/npc=33524/saronite-animus

This is the hard mode add on Vezax encounter.
We mostly fixed him earlier, but 2 issues about it still:

1) The add is currently immune to taunts.
General Vezax is intended to be taunt-immune, but the Saronite Animus should not be.

**How it should work:** The Animus shouldn't be immune to taunts

2) There's a visual issue with the coloring of the add. This is how he currently looks like totally missing his blueish saronite color:
![WoWScrnShot_091019_130918](https://user-images.githubusercontent.com/31132743/64609034-4707e680-d3cc-11e9-96b1-9485e6f75f0d.jpg)

How it should work: this is how he should look like 
https://wow.zamimg.com/uploads/screenshots/small/131737.jpg

**Comment by Rushor** [comment]
that visual spell 63319 semms only to add green aura. strange
