### ISSUE TITLE
[Boss/Spell] Tear Gas - Professor Putricide

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#3575]
https://www.wowhead.com/npc=36678/professor-putricide
https://www.wowhead.com/spell=71617/tear-gas
https://www.wowhead.com/spell=71618/tear-gas

This is apparently a timer issue, Putricide cuts the transition phases short and tear gas expires way sooner on players than on the abomination.

**How it works atm:** 
PP casts tear gas, jumps to his table, then casts Concoction, and resumes the fight approximately 10seconds after the transition began. 
The Tear gas on players expires as soon as PP rejoins the fight, and everything continues, except the Abomination is still stunned by the Tear gas for 10seconds more (since the tear gas normally last 20s), leaving the raid unprotected against the oozes.
**How it should work:**
The Tear gas lasts 20seconds and that's how long the transition should last as well. If you watch videos from retail, PP takes his time sitting at his table after using the Concoction spell and only rejoins the fight at the 20sec mark, when Tear gas expires (on everyone, players and abom)
https://www.youtube.com/watch?v=8vmBSF5vxPg

**Comment by Drostthehunter** [comment]
Does this means that on 10heroic and 25heroic where there is no actual stun part the Proffesor Putricide casts his spell on the table 10 seconds shorther meaning he is rejoining the fight 10 seconds earlier then he is supposed to? @Dranah

**Comment by Dranah** [comment]
Hmmm, indeed, although it isn't 10seconds just about 5-6, i miscalculated due to PP being very from from the center where he throws the tear gas on my tests.
But yeah, I haven't really considered checking heroic since there is no tear gas over there,but the transition timer seems wrong in there as well.
In retail, PP takes about 10s to rejoin fight after the concoction cast is over, here is only 5s on both normal and heroic.
This means the transition lasts up to 15s instead of 20 on normal and only about 40s instead of 45 on heroic. 
I'm not sure if this is a giant difference of impact on the encounter, but i'll leave the thread open for now.

**How it should work:** PP should wank 5sec longer at his table after drinking the concoction before rejoining fight.
**How it works atm:** PP rejoins the fight 5sec early, on both difficulties.

**Comment by Dranah** [comment]
video reference for hc https://www.youtube.com/watch?v=fRVDK3tDtJw

**Comment by Dranah** [comment]
Timer looks good now, aligns with even the DBM one if the boss is relatively close to the center of room.
