### ISSUE TITLE
[Quest]The Stones That Bind Us

### ISSUE THREAD

**Issue by Jhaza** [WoWManiaUK/Redemption#3577]
**Links:**
The quest: https://classic.wowhead.com/quest=2681/the-stones-that-bind-us

**What is Happening:**
Sometimes (roughly 30-50% of the time), using the Stone of Binding will destroy the Stone, but not kill the Servant. That is, during the fight you would reduce the servant to 1 HP; the servant would start glowing, become invincible and start glowing, and a chat message say, "Servant of <Name>'s physical form is weakened. You notice the Stone of Binding near the creature is glowing! Strike now!;" you right-click on the Stone to attack it, channeling briefly; after a short pause, the stone would disappear, but the servant would stick around, still stunned and glowing.

A possibly related issue is that there are a number of servants wandering around with no nearby Stones; I don't know if this is intentional or not, but it makes the quest even more annoying than the bug otherwise would.

**What Should happen:**
As above, except that when the Stone is destroyed, the servant should die at roughly the same time, with an exclamation about their freedom.

**Comment by WhitephoenixTheBunny** [comment]
Destroyed stone, servent still alive

**Comment by Rushor** [comment]
maybe this happens if the creature is to far away for the stone. inceased the actable distance between stone and creature to 50 yards now. please test :)
