### ISSUE TITLE
[Boss/Spell] Slime Puddle

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#3578]
https://www.wowhead.com/spell=70341/slime-puddle
https://www.wowhead.com/npc=36678/professor-putricide

**How it works atm:**
These puddles sometimes spawn in the air when the players that are targeted are thrown up by the Volatile Ooze Explosion.
![WoWScrnShot_091119_153818](https://user-images.githubusercontent.com/31132743/64839036-3935a980-d5f6-11e9-80fa-703ee8dd3099.jpg)
![WoWScrnShot_091119_153947](https://user-images.githubusercontent.com/31132743/64839104-77cb6400-d5f6-11e9-91d4-9684822d42d2.jpg)
Note they still do damage to the players under, but it becomes more difficult to tell where they begin and end and for the abomination to suck them up as well.

**How it should work:**
The puddles should always spawn on the ground under the targeted person, never in the air, even if he's jumping/thrown around.

**Comment by Rushor** [comment]
should no longer be able to "fly" but instead alsways drop to the ground.
