### ISSUE TITLE
[Core] In-game calendar event creation

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#3579]
**Links:** Issue #3175 

**What is Happening:** After creating or updating a personal or guild event in the in-game calendar, it shows up as 1 hour later than the time picked. (All times are based on server time obviously)

**What Should happen:** Creating an event at 2:00 Realm Time should post said event on the calendar at 2:00 Realm Time and not at 3:00. (Hours given as example, any time results in the same issue)

Also, simply updating the description or "type" of an already existing event will cause it to be pushed by one hour upon clicking the final "Update" button.

**Impacts on the game:** This issue can cause a lot of confusion in guilds that aren't used to the bug, since updating an event notifies every member signed up through in-game mail.

**Comment by wow-mania** [comment]
This is not a core issue this has to do with the fact the server is at GMT+1

**Comment by Rushor** [comment]
okay could you try this to add in shared folder: https://github.com/TrinityCore/TrinityCore/issues/8390#issuecomment-111730231

**Comment by Rushor** [comment]
works, does not upfate anymore once editited

**Comment by WhitephoenixTheBunny** [comment]
@Rushor @wow-mania I think this brought a side effect, svt is now 2h behind

**Comment by Drostthehunter** [comment]
We are flying back atm, 2 hours to be precise..

**Comment by Aristo14** [comment]
calendar has allways been like this, it has to do with daylight saving times winter/summer.

**Comment by WhitephoenixTheBunny** [comment]
Maybe revert it till the time change
