### ISSUE TITLE
ICC vanishing buff on warlock pets

### ISSUE THREAD

**Issue by Kinkywiener** [WoWManiaUK/Redemption#3580]
Hey, I had been noticing a bug in Icecrown Citadel during last 2-3 months, didnt manage to find the trigger up until yesterday. Each time I use Demonic Circle: Teleport, ICC buff Strength of Wrynn wears off of any pet I have summoned. This lowers the damage output, especially for demonology specced warlocks. I tested the issue with another 2 human warlocks. From what I heard, the horde players are not affected by the issue. Thanks in advance"

**Comment by Rushor** [comment]
didn't this affect all kind of pets?

**Comment by Dranah** [comment]
Only warlocks have Demonic Circle ability so... 
I can confirm btw.
Spell ID 48018 summon
Spell ID 48020 teleport
spell ID 73822 ICC buff horde
spell ID 73828 ICC buff ally

**Comment by Dranah** [comment]
Before - after:
![WoWScrnShot_091319_220307](https://user-images.githubusercontent.com/31132743/64891472-51e3a500-d672-11e9-8dc5-d9ed329c7315.jpg)
![WoWScrnShot_091319_220314](https://user-images.githubusercontent.com/31132743/64891473-53ad6880-d672-11e9-8e8b-c875f93454b2.jpg)

**Comment by Rushor** [comment]
and other pets like hunter do not loose their buff upon normal teleport? okay nice
