### ISSUE TITLE
[Dungeon/Rewards] Trial of the Champion not giving RDF reward

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#3583]
https://www.wowhead.com/trial-of-the-champion

**How it should work:** If you get this dungeon in the Random Dungeon Finder, finishing the Black Knight (last boss) encounter should trigger the end rewards of RDF (emblems + MP+ gold)
**How it works atm:** Finishing the dungeon does not give you the RDF reward

Note: this was tested on heroic.

**Comment by Rushor** [comment]
hm does this happens sometimes or always?

**Comment by wow-mania** [comment]
Need confirmation on this please.

**Comment by Rushor** [comment]
or better where reards are handled?

**Comment by wow-mania** [comment]
I don't think it is a reward issue as it works for all others. That is what is strange.
We need confirmation.

**Comment by Rushor** [comment]
alright, so anyone got the same issue while doing that dungeon?

**Comment by Dranah** [comment]
cannot seem to steadily reproduce it. sometimes it just doesnt award and i have to do another rdf, but it probably has an extra condition i've yet to figure.
