### ISSUE TITLE
[Quest] Rescuing The Rescuers (A) Not Spawning Objects.

### ISSUE THREAD

**Issue by SPRF89** [WoWManiaUK/Redemption#3584]
**Links:** 
https://www.wowhead.com/quest=11244/rescuing-the-rescuers

**What is Happening:**
Quest isn't spawning clickable harpoons which are needed to complete the quest.

**What Should happen:**
Harpoons should spawn on NPC bodies which you click to remove and counts towards the quest counter. However they are not and this quest is -needed- to progress in the Howling Fjord questline for Alliance.

Have waited around 30mins for them to spawn in case another player had just passed through before me, have exited and restarted the game in case it was on my end, but no luck in having them spawn.

**Comment by SPRF89** [comment]
Some eventually spawned, roughly between 5-7 hours later, 6 of, which wasn't enough to complete the quest (8 required) as some were still not spawning.

**Comment by corrinr** [comment]
See previous issues as well: https://github.com/WoWManiaUK/Redemption/issues/3442 https://github.com/WoWManiaUK/Redemption/issues/870

**Comment by Rushor** [comment]
it should works now. rspawntimer adjusted to 60 seconds

**Comment by WhitephoenixTheBunny** [comment]
I have "looted" all
3 are missing the harpoon

**Comment by Rushor** [comment]
which once? always the same ones?

**Comment by WhitephoenixTheBunny** [comment]
Is random.... now was others...

**Comment by Rushor** [comment]
hm okay

**Comment by Rushor** [comment]
set them to active state. try now

**Comment by jarvik76** [comment]
Following player complaints, have retested and there does seem to be problem again so re-opening.
- Took quest, picked all the harpoons i could find and abandoned.  
- **Went back 7 mins later and took quest again, no harpoons available**
- Seems to apply to ALL the instances in the area, not just 3

**Comment by jarvik76** [comment]
Interestingly, these 3 respawned after approx 10 mins.  The others in the area did not, still waiting 30 mins later
![WoWScrnShot_112219_114637](https://user-images.githubusercontent.com/46089380/69423683-af553b80-0d1e-11ea-84f0-b595248bc13b.jpg)

**Comment by Rushor** [comment]
the script is like that:

npc > spawn > spawn go

will change to:
npc > out of combat > after 100 ms > spawn go
+ set active

**Comment by Rushor** [comment]
seems to work for me https://i.imgur.com/lTbW80w.jpg

**Comment by jarvik76** [comment]
confirmed, re-tested and looks good now, harpoons spawn as expected.
