### ISSUE TITLE
[NPC] Pusillin

### ISSUE THREAD

**Issue by WhitephoenixTheBunny** [WoWManiaUK/Redemption#3588]
**Links:**
http://www.wow-mania.com/armory/?npc=14354

**What is Happening:**
This NPC is running too fast, can't be followed

**What Should happen:**
It should have a "normal" speed, so player can assist him on the way

**Comment by Drostthehunter** [comment]
Only way to actually know where is he running is if you put {mark} on him, even then its almost impossible to track him down.

**Comment by Dranah** [comment]
I don't understand? He is not an escort, you dont have to assist him. He is playing catch with you, he IS supposed to be faster than you are. His movement pattern is fully predictible and following the corridor just eventually lets you catch up to him after a while.

**Comment by Rushor** [comment]
Yes that's right. You just need to follow his stoppoints and talk again to him.

**Comment by wow-mania** [comment]
As-is you need to follow as fast as you can and avoid trash. Your goal is to follow not escort.

**Comment by WhitephoenixTheBunny** [comment]
I cleaned trash before, level 80, druid, used cat form + dash and still I have lost him several times

**Comment by Dranah** [comment]
You can't lose him, he goes on a predictible path along your way, and doesnt despawn when outranged.
