### ISSUE TITLE
[Boss] Sjonnir the Ironshaper

### ISSUE THREAD

**Issue by corrinr** [WoWManiaUK/Redemption#3589]
**Links:**
http://www.wow-mania.com/armory/?npc=27978

**What is Happening:**
Sjonnir is not spawning when the doors to his room are opened. Steps that caused this bug for me on heroic:
-wiped very close to the end of the Tribunal of Ages encounter
-ran back and went to the front of the room, fought mobs that accumulated there, wiped again bc the tank got overwhelmed
-ran back and heard Brann /yell to signal the end of the encounter, walked back out to Sjonnir's room which was open, went in and he wasn't spawned
-went back to Brann, killed remaining mobs and looted the chest, talked to him, he started walking where he is supposed to and despawned
-went back to Sjonnir's room with no change
-kicked 2 people so we could leave, tried requeuing to see if it affected anything, when we did this (in the room) the doors closed behind us but nothing else happened so we left
Back when the tribunal encounter wasn't working, if you wiped you were able to unlock Sjonnir without going back in the room by having one person go to where the earthen guys are and wait until Brann yells. Mob/statue attacks still seem to not be damaging Brann while there are no players alive and in the room.

This is happening to other people as well; earlier someone asked if the dungeon was bugged in world chat bc the last boss was not spawning for their group.

My guess is that either this is a preexisting bug that no one was experiencing before because the old version of the Brann fight was impossible to wipe during, or a side effect of the fixed fight. People are used to just leaving as soon as the mobs stop spawning and usually don't talk to Brann, bc you have to wait a bit until he stops talking to be able to activate him. The usual method was to tp out/in as soon as the fight finished and you would find the door to Sjonnir open and the encounter ready to start. I'm guessing a likely cause for this bug is teleporting to Sjonnir's room before Brann has finished talking and not having activated Brann.

**What Should happen:**
The door to Sjonnir's area should remain closed until the Tribunal of Ages encounter completes, and once opened should spawn Sjonnir, Brann and other NPCs, enabling players to complete the dungeon.

**Comment by corrinr** [comment]
I've been able to get to him fine with other groups, but never after a wipe, so it seems like this is likely triggered by a wipe or something about how we handled a wipe.

**Comment by wow-mania** [comment]
Boss is there.

**Comment by Keader** [comment]
@corrinr if psosible, test now in PTR please?

**Comment by corrinr** [comment]
@Keader would love to but I'm not on the test team haha, I was actually thinking about joining so I probably can once that happens
