### ISSUE TITLE
[Achievement] Blade's Edge Bomberman

### ISSUE THREAD

**Issue by Joblaisk** [WoWManiaUK/Redemption#3591]
Achievement http://www.wow-mania.com/armory/?achievement=1276 almost not doable here.

High amount of casts ended with "failed" without any reason.Even if you are lucky and get no failed casts you are short by 5-6 seconds to do this achivement without casting 2 bombs on 1 cooldown. I've tried at least 100 times in the past 2 days and my best shot was short by 7 seconds. Is it possible to fix the "failed" shots or to add the 2-tick bombs in 1 shot.

https://www.wowhead.com/achievement=1276/blades-edge-bomberman#comments

**Comment by wow-mania** [comment]
Have you completed the quests? If not the problem is not the achievement.

**Comment by Joblaisk** [comment]
I've completed the quest several times, but can't do it under 2m15s

**Comment by Rushor** [comment]
i think it's related to the spell handling of the cannon

**Comment by cathyr1** [comment]
I can confirm that unreasonable fails.

**Comment by Rushor** [comment]
it's related to the spell i think http://cata.cavernoftime.com/spell=40160

**Comment by Rushor** [comment]
okay soemhow the trigger do not despawn

**Comment by Rushor** [comment]
yes triggers are invisible and don't despawn and they keep you interrupting the spell

**Comment by Joblaisk** [comment]
Is a fix possible or not?

**Comment by Rushor** [comment]
possible i'm struggeling right now

**Comment by Rushor** [comment]
![I](https://i.imgur.com/5XbYUwR.jpg)

okay fixed. 

no much trigger spawns. they will despawn and the chance to get chanceled/interrupted is lower now.
