### ISSUE TITLE
[Quest] Guardian of the Monument   ID: 11059

### ISSUE THREAD

**Issue by Grimwaldo** [WoWManiaUK/Redemption#3592]
**Links:**

https://www.wowhead.com/quest=11059/guardian-of-the-monument
**What is Happening:**

I pay the 35 apexis shards an summon the boss, The quest item didnt drop from the boss when i killed him
**What Should happen:**
the quest item should drop from him

![WoWScrnShot_091819_142742](https://user-images.githubusercontent.com/55025796/65165984-21b84f80-da40-11e9-9743-33aae715f443.jpg)

**Comment by Rushor** [comment]
22275

chance increased to 100 now
