### ISSUE TITLE
[Boss/Spell] Unstable Ooze Explosion

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#3594]
https://www.wowhead.com/spell=69839/unstable-ooze-explosion
https://www.wowhead.com/npc=36899/big-ooze
https://www.wowhead.com/npc=36627/rotface
https://www.wowhead.com/spell=69558/unstable-ooze

Main mechanic of Rotface encounter, broken since ever. 
Wowhead description:
"The first two Small Oozes that merge will form a Big Ooze. Every next Ooze that merges with the big one will add a stack to its Unstable Ooze. When that stack reaches 5 (after the 6th ooze has spawned), the Big Ooze will freeze in place and cast Unstable Ooze Explosion."

1) Big ooze won't explode when merging with other big oozes
**How it works atm:** You can fully avoid the explosion forever by continuously merging 2x big oozes throughout the encounter. It does properly add up the stacks of Unstable ooze, but it won't explode at 5+ stacks so long as you only merge big oozes into it. 
(If you happen to merge a small ooze into a stacked big one, it will instantly trigger explosion, but this is very easy to avoid.)

Makes the achievement "dances with oozes" effortless and the fight itself too.
Note, there used to be issues with the ooze stacking on retail too, but blizzard hotfixed it all by 3.3.5 (that's why you can find early ICC launch notes about that two big oozes would not add up stacks properly, but that is not up to date 3.3.5).

**How it should work:** Whenever a big ooze gets 5+ stacks of Unstable Ooze, it should explode, period. Doesn't matter what ooze they merge with.

2) Big oozes begin with 2 stacks
**How it should work:** When two small oozes merge, they should become a Big ooze with a single of Unstable ooze buff. Each extra ooze that merges into it, will add 1 extra stack, that's how you get the first ooze explosion after a total sum of 6 small oozes if you keep merging them.

**How it works here**: When two small oozes merge, they become a big Ooze with 2 stacks of Unstable ooze. This means it only takes 3 extra small oozes to merge in order to make it explode, which is 1 fewer than it should be.

**Comment by Rushor** [comment]
have a possible fix if you don't wanna do it :>
