### ISSUE TITLE
[Boss/Spell] Gunship Cannon abilities

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#3596]
https://www.wowhead.com/object=201873/gunship-armory
https://www.wowhead.com/spell=70172/cannon-blast
https://www.wowhead.com/spell=70175/incinerating-blast

There are several issues with the cannon's damaging abilities, which make the fight quite different from what it was on retail.

1) Cannon blast does too little damage
**How it should work**: It should do a fixed 1k damage to the enemy ship.
**How it works atm:** It's doing something around 800-900 damage depending on raid environment as it appears to scale with certain buffs, but never seen it hit for actual 1k.
Note: It was later increased to 1500 (on mop or something...) which is why the tooltip is now showing 1500 but that's wrong.

2) Incinerating Blast does way too much damage with high heat
**How it should work:** On wotlk it used to scale from 1k damage (10 heat) up to around 8-9k when the energy bar was nearly full (90-95). 
You can see this on the tankspot video below where the ship's health is shown precisely, there is never a jump greater than 7-8k on the enemy ships hp (the cannoneers likely used to heat at 80~ energy to play safe).
**How it works atm:** It seems to do the boosted MOP damage with full energy, which goes as high as 50-60k damage when stacked to 90+ energy. Other than that the scaling is totally fucked, it starts off at 1800 damage with 10 heat and then decreases to 1100-1200 in the 20-40 energy range until it starts to rapidly grow.

Here's a description of the increase to the incinerating blast, which took place sometime in 2012, link to the forum discussion below:
"They got rid of that, the adds still do burning pitch but to compensate for that they upp'd the dmg on the rocket jump w/ the shirt and the burn all energy thing (the 2 button on the cannon), it now does like 60k dmg near full energy instead of the 8-9k before."
It should never do that high damage on wotlk 3.3.5a.

3) Cannon abilities don't damage enemy mobs
**How it should work:** As it is described on wiki and visible on several videos, "Both types of shot not only deal siege damage but also damage enemy mobs, thus shots should be angled at the rocketeers/ranged NPCs. "
**How it works here:** The cannon abilities deal only siege damage, they aren't doing any damage to the enemy mobs they are aimed at. This makes the cannoneer duty overall dull and boring because there is no point paying attention to what they are shooting at.

**Sources:** https://wowwiki.fandom.com/wiki/Gunship_Battle
"The ship's guns have two different attacks: a normal shot bound to "1" which deals 1000 siege damage. Firing a normal shot also generates between 6 to 10 heat, which fills up the heat gauge on the gun (begins at 0, maximum 100, losing 1-2 heat per second while not firing). The second shot is bound to "2". It's a heated shot which immediately expels all the accumulated heat on the gun and deals 1000 siege damage plus extra damage for each unit of heat, up to just under 10000 with a nearly filled bar. If the heat meter reaches or exceeds 100, the gun overheats and both shots are locked for five seconds until all heat has been drained. "
https://www.youtube.com/watch?v=WBAnLhFk2EE 
wowhead: https://www.wowhead.com/forums&topic=136089
"You're better off using the turrets to take out the rifleman/mortor teams that are stacking experience buffs increasing their damage."
https://us.battle.net/forums/en/wow/topic/7199963380

**Comment by Drostthehunter** [comment]
Blessing of Might increases the cannon damage if caster on cannons itself

**Comment by Keader** [comment]
Damage of both spells fixed.
The only thing that i cant fix, is damage trash mobs part.
The problem is gunship is a transport, and old core version dont handle well with transport positions.
So... the part of spell that should hit trash mobs, cant find targets x_x.

**Comment by Dranah** [comment]
Gotta put this on hold until we investigate the issue with the GCD. If that cannot be fixed, we need to balance it somehow.
