### ISSUE TITLE
[Quest / POI] Body and Heart - Alliance

### ISSUE THREAD

**Issue by WhitephoenixTheBunny** [WoWManiaUK/Redemption#3597]
The quest [Body and Heart](http://www.wow-mania.com/armory/?quest=6001) show wrong place on the map, making the quest confuse at low level

Where it shows:
![image](https://user-images.githubusercontent.com/31921098/65376507-6b02dc00-dc98-11e9-8ebf-2c69f1d93141.png)

Where it is:

![image](https://user-images.githubusercontent.com/31921098/65376512-7d7d1580-dc98-11e9-829e-88a277fced82.png)

![image](https://user-images.githubusercontent.com/31921098/65376522-8ec62200-dc98-11e9-9428-d3c9d8a65ec3.png)

**Comment by WhitephoenixTheBunny** [comment]
Also, after completation it doesn't show the yellow question mark on map:
![image](https://user-images.githubusercontent.com/31921098/65376572-76a2d280-dc99-11e9-89cd-7f91d142e6ea.png)
![image](https://user-images.githubusercontent.com/31921098/65376577-91754700-dc99-11e9-83b6-5f04ca6d52e6.png)
![image](https://user-images.githubusercontent.com/31921098/65376591-b8337d80-dc99-11e9-89df-1ffacc951bcc.png)

**Comment by Rushor** [comment]
http://www.wow-mania.com/armory/?quest=6001

**Comment by Rushor** [comment]
select * from quest_poi_points where questid=6001
select * from quest_poi where questid=6001

okay first need acces to quest_poi_points  and quest_poi for that

**Comment by Rushor** [comment]
okay point is now shown on the map in darkshore

![I](https://i.imgur.com/IMj4ErY.jpg)

**Comment by Rushor** [comment]
sadly the questionmark once completed cannot be fixed, but that's only minor
