### ISSUE TITLE
[Auction house] Sorting prices incorrectly

### ISSUE THREAD

**Issue by tvshadowz** [WoWManiaUK/Redemption#3598]
Horde Auction House: 

Currently if the auction house is sorted via lowest to highest current bid, the correct lowest bid item is not shown. Rather another, higher priced in both current bid and buyout price is shown. In image 1 is the first page of Greater Plantar essence sorted by lowest to highest bid and the second image is page two. The lower items are displayed later when they should be displayed first. 

This is also the case for Frostweave Cloth on the Horde auction house.

![Image 1](https://user-images.githubusercontent.com/30256554/65400424-bd6ef600-dd87-11e9-86dd-70f1d9a2834a.png)

![Image 2](https://user-images.githubusercontent.com/30256554/65400428-c233aa00-dd87-11e9-9076-cd4c8edc55be.png)

**Comment by Rushor** [comment]
some info on this here https://github.com/TrinityCore/TrinityCore/issues/15648. It's a deep core issue
