### ISSUE TITLE
[Event] There and Back Again - Follow-up (gossip)

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#3600]
**Links:** Previous Issues related: #1673 and #3595
https://wowwiki.fandom.com/wiki/Brewfest
https://www.wowhead.com/item=33306/ram-racing-reins#comments
https://www.wowhead.com/spell=43880/ramsteins-swift-work-ram
https://wowwiki.fandom.com/wiki/Brewfest_Prize_Token

**What is Happening:** The hidden daily 'quest' started by selecting the gossip option from Neill Ramstein starts properly when un-mounted. The player gets mounted on a [Rental Ram](https://www.wowhead.com/spell=43880/ramsteins-swift-work-ram) of a duration of 4 minutes and has to do as many laps as possible between Kharanos and Neill to turn-in barrels. 

1. At the moment, players seem to be randomly awarded the intended 2 [Brewfest Prize Tokens](https://www.wowhead.com/item=37829/brewfest-prize-token). I have tried going closer to Neill or staying near him longer and none seem to increase the chance to get the tokens. Seems to be about ~50% chance to get them each lap. 

2. The race ends after 4 minutes regardless of the number of laps completed.
Edit: It seems like the 50% of turn-ins that award the tokens also add the intended 30 seconds. So 2 would be linked to 1.

3. The gossip option seems to be available very quickly after completing it. I haven't sat there and waited to check the exact time, but it seems to be do-able again after less than 2 hours.

**What Should happen:**

1. Players should get 2 [Brewfest Prize Tokens](https://www.wowhead.com/item=37829/brewfest-prize-token) for every lap completed.

2. The turn-ins should grant 30 additional seconds to the buff duration, up to a maximum of 15 minutes. 

3. According to a blue post from an old forum I can't retrieve:

> Blizz Kisirani 2009-09-23. Re: still cant do the ram racing quest. Archived from the original on 2009-09-23. Retrieved on 2009-10-09. “I'm just popping in to confirm this resets every 18 hours, not 12 as has been the case in previous years.” - _from References section of https://wowwiki.fandom.com/wiki/Brewfest_Prize_Token_

Reset should reset 18 hours after completing the race.

**Comment by Rushor** [comment]
> At the moment, players seem to be randomly awarded the intended 2 Brewfest Prize Tokens. I have tried going closer to Neill or staying near him longer and none seem to increase the chance to get the tokens. Seems to be about ~50% chance to get them each lap.

if you are closer than 9 yards to him, you should get the token spell

**Comment by Rushor** [comment]
that is what the codes says

```
if (me->GetDistance(who) < 10.0f && who->GetTypeId() == TYPEID_PLAYER && who->GetMountID() == RAM_DISPLAY_ID)
```

so if you are closer than 10 yards you will get the token and the items.

anyway i will increase that range to 14 yards. maybe it helps

**Comment by Oganku** [comment]
I supposed proximity could be a factor, but I guess latency affected it considerably considering the mount moves at +186% speed. I'll test soon when I get the chance. Thanks for the quick fix though. ^^

**Comment by Rushor** [comment]
it's on dev realm

**Comment by Echinaceax** [comment]
there is still a few issues with this @Rushor 
tested both all and horde today, coz i noticed that on the 3rd invisible daily quest that the keg returms are being thrown to the wrong NPC for delivery 

- [ ] Horde are thown to https://www.wow-mania.com/armory/?npc=24510#abilities but 0 tokens given and are never thown to https://www.wow-mania.com/armory/?npc=24497

Ally are thrown to https://www.wow-mania.com/armory/?npc=23558 and https://www.wow-mania.com/armory/?npc=24468 depending on which angle you run in from 

![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/c6c6b45f-ab9b-4a64-8e57-5864a714ce32)



- [ ] Ram buff timer isnt increased as it should be 
https://www.wowhead.com/wotlk/item=37829/brewfest-prize-token#comments:id=384809

![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/880534a8-bea3-489b-ae1c-722e07bc3dfa)

**Comment by Lumber-Jack-2** [comment]
- Player now gets https://www.wowhead.com/spell=43880/ramsteins-swift-work-ram#comments
- timer should be increased on deliver

**Comment by Echinaceax** [comment]
Just for notes atm @Rushor 
Apple buckets have stopped removing the fatigue debuff since this fix 
https://i.gyazo.com/81c01c515b4b4790718ea095e73c5965.mp4 `funny video end `
(note to self, echi dont confirm fixes when rushor is restarting the PTR) 😄 

Well i will retest when you've finished others

**Comment by Lumber-Jack-2** [comment]
fatigue remove works for me https://gyazo.com/31b715732b3ff40b79f6d9ffaa2634ba - i think it needs to be very close to the apple object

**Comment by Echinaceax** [comment]
> fatigue remove works for me https://gyazo.com/31b715732b3ff40b79f6d9ffaa2634ba - i think it needs to be very close to the apple object

I was very close look https://i.gyazo.com/81c01c515b4b4790718ea095e73c5965.mp4

Retesting now

**Comment by Echinaceax** [comment]
Re-tested on a different char 
There and Back Again 
Apple working now https://i.gyazo.com/69750973c3237e69c5be7e57e1a118b9.mp4
![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/e5b25b9b-c0e9-4d77-9b35-eca875ca4a4e)

**Comment by Lumber-Jack-2** [comment]
Visibility for Bok Dropcertain and deliver code adjusted to the new mount model (swift ram from additional work)

**Comment by Echinaceax** [comment]
> Visibility for Bok Dropcertain and deliver code adjusted to the new mount model (swift ram from additional work)

Confirmed, thanks rushor 

Also confirmed is the keg delivery and timers 

![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/dab6d306-03a5-470b-b5b9-568958f676c7)

Confirmed Ram model (for additional work)

![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/8aae499e-1f2a-45a1-b3cb-24bc57c04920)
