### ISSUE TITLE
[NPC] Sparktouched Oracle in Sholazar Basin

### ISSUE THREAD

**Issue by AIlindah** [WoWManiaUK/Redemption#3602]
**Links:**
https://wotlkdb.com/?npc=28112
https://www.wowhead.com/npc=28112/sparktouched-oracle

**What is Happening:**
This NPC has significantly more HP than it should, by my estimates about 4.5 times the HP it should as compared with links above and other mobs in the area.  Comments on Wowhead and links provided above point to it having ~4k HP as opposed to the 18k it has. 

**What Should happen:**
The Sparktouched Oracles HP should be less than it currently is in game.

**Comment by wow-mania** [comment]
As-is.
