### ISSUE TITLE
[Quest / Event] Catch the Wild Wolpertinge!

### ISSUE THREAD

**Issue by Critman** [WoWManiaUK/Redemption#3603]
**Links:**

**What is Happening:** 
"Catch the Wild Wolpertinge!" quest should be given from Goldark Snipehunter (npc).
Also the googles (Synthebrew Goggles) are not retrievable from the same npc.

**What Should happen:**
Goldark Snipehunter should give two quest :
"Catch the Wild Wolpertinge"  & "Pink Elekks" on Parade, along with the goggles.

**Comment by WhitephoenixTheBunny** [comment]
ally quest http://www.wow-mania.com/armory/?quest=11117
horde quest http://www.wow-mania.com/armory/?quest=11431
