### ISSUE TITLE
[Boss/Spell] Kinetic Bomb - Blood Prince Council

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#3604]
https://www.wowhead.com/spell=72053/kinetic-bomb

These guys have multiple issues.

1) The timer is off
**How it should work:** 
On 10man, the ability should have a 27sec cooldown on use, which means you would juggle only 2 bombs for most of the time.
On 25man, the ability should have 18second cooldown on use, which means, you would juggle 3 bombs for most of the time.
**How it works atm:** Valanar spawns a new bomb every 21seconds, regardless of difficulty, This means there are always exactly 3 kinetic bombs up on both difficulties. It makes 25man slightly easier, 10man way harder to upkeep.

2) They don't get lifted by certain direct damage attacks.
So far the faulty damage sources seem to be
Faerie Fire (feral) ID 16857
Hand of Reckoning ID 62124
You can see them dealing damage on the combat log, but the orb ignores their damage and does not begin to lift:
![kinetic](https://user-images.githubusercontent.com/31132743/65816344-a18da900-e1fa-11e9-9ddc-bf30218659f7.png)
**How it should work:** all direct damages done to the orb should make a response to lift the orb, including these two spells.

3) They spawn too close to the ground on normal difficulty
**How it works here:** the bombs spawn with the same reduced altitude on normal mode as on heroic. (note: the speed is okay, that is only increased on hc)
**How it should work:** They should be spawning near the ceiling on normal, twice as high as on hc.
You can see it on this vid how the druids camera doesn't even pick them up, they spawn so high, and the hunter next to him begins to shoot it before it'd descend low enough to see on the druids screen: https://www.youtube.com/watch?v=YQTO_4Nl_Ec

4) They aren't picked up by targeting macros.
I have tried everything from /tar Kinetic, /tar Kinetic bomb, /tar Kin, they are literally on top of me and the macro is unable to pick them up. 
As most of them are difficult to see or click due to their altitude, this reduces the effectiveness of the assigned persons that handle the bombs by large.
Besides, it makes no sense.

**Comment by Keader** [comment]
- [ ] The timer is off
- [ ] They don't get lifted by certain direct damage attacks.
Both fixed.

> They spawn too close to the ground on normal difficulty.

Wrong, i checked in various sniffs (10 and 25 man), it always spawn in 20 yards from ground.


> They aren't picked up by targeting macros.

Nothing that i can do about it, macros like target, run in clientside.

**Comment by Dranah** [comment]
Altitude is the same on 10man and 25man, the difference is between normal and heroic.
It cannot be the same altitude on normal and heroic. Check various sources, videos, descriptions, it's a heroic feature that the bombs spawn closer to the ground. While it is not stated "how much closer", based on the video footage you can make a rough estimation that it's at around 30 yards on normal mode.
Please just check the video I linked in. It shows perfectly how the bombs are spawning way higher near the ceiling.
