### ISSUE TITLE
 [Nature's Grasp] Druid spell Not working 

### ISSUE THREAD

**Issue by shadownib** [WoWManiaUK/Redemption#3605]
**Links:** spell link https://www.wowhead.com/spell=66071/natures-grasp

**What is Happening:** [Nature's Grasp] works only for the first stack proof link of " What is Happening" - https://www.youtube.com/watch?v=z5ds-saOl-E&feature=youtu.be

**What Should happen:** there is 3x stacks they should be activated each an any physical / mele attack u get ( that's it ) please fix that Basic issue which should work in any random private server , how the players didn't notice that simple / basic issue , those years in wow-mania idk :S ...

P.S. Quality Above all
P.S. Game is Too Hard

**Comment by Dranah** [comment]
Because it was only broken with the last update. We have fixed the spell recently to not release all 3 charges in one second, and it appears that a part of the fix was reverted among others (cough, slime spray...)
Original issue:
https://github.com/WoWManiaUK/Redemption/issues/3566
