### ISSUE TITLE
Lieutenant General Andorov not spawning in AQ20

### ISSUE THREAD

**Issue by drewbost** [WoWManiaUK/Redemption#3607]
**Links:**
Lieutenant General Andorov NPC ID: 15471
https://www.wowhead.com/npc=15471/lieutenant-general-andorov

https://wow.gamepedia.com/Lieutenant_General_Andorov

**What is Happening:**
In the Ruins of Ahn'Qiraj (AQ20), LtGen Andorov is not spawning after killing Kurinnaxx.

**What Should happen:**
After killing Kurinnaxx (NPC ID 15348), the first boss of AQ20, Lieutenant General Andorov and four Kaldorei Elite NPCs (ID 15473) should spawn right next to Kurinnaxx and run to the stairs between the Kurinnaxx boss room and General Rajaxx boss room. You can then talk to LtGen Andorov to start an event where he helps you kill General Rajaxx. After defeating the Rajaxx, Andorov turns into a vendor where you can buy blacksmithing plans and some consumables.

Although Wowhead and Wowpedia say Andorov spawns after killing Kurinnaxx, several Youtube videos I found show him and the four bodyguards standing near the boss before it is killed:

https://youtu.be/MMqJfX149hw?t=1275

https://youtu.be/bBX3V6XX-VA?t=511

**Comment by Rushor** [comment]
Oh this is a nice little Event that should Happen here. Will implement that!

**Comment by Rushor** [comment]
going to fix that once all access to tables is granted :)

**Comment by Rushor** [comment]
r: 1686bcc456fe4ee64c8e758f1745f18a743d337a

**Comment by Rushor** [comment]
the whole fight added. if kurrinaxx is killed is killed, Lieutenant General Andorov will spawn with his gaurds. then you need to fight aginst the minibosses. once rjaxx is killed you can open his vendoroption.

![I](https://i.imgur.com/XDcL1uB.jpg)
![I](https://i.imgur.com/vGKEHte.jpg)
![I](https://i.imgur.com/RtGy3tX.jpg)
![I](https://i.imgur.com/hL6hApp.jpg)
![I](https://i.imgur.com/oXef41P.jpg)
![I](https://i.imgur.com/cLdEgWG.jpg)
