### ISSUE TITLE
[Mechanic] Caster pets and Line of Sight

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#3611]
This affects water elementals and imps mostly.

**How it works atm:** When the pet has no line of sight towards the enemy you make him attack, he just stands still and stares until you move him via /petfollow in a position where he has los to attack. Will never attempt to move around the wall, or get closer until he is in LOS.

**How it should work:** If your pet has no line of sight on the selected target, they should move towards it (walk through/around the wall or object in front) until they have line of sight to cast. As soon as the LOS check allows the cast, he should immediately pause and begin to cast.

Note: earlier when the caster pets were able to melee this wasn't a problem, however we need to fix this without making them stupidly keep meleeing again. Just like NPCs, they should only keep coming closer to the target until they have LOS to cast.

**Comment by Keader** [comment]
Each time that i change something in Pet.cpp, server start a big lag without reason.
I will not touch on it.

**Comment by wow-mania** [comment]
This will depend on Keader's opinion. If this is risky we mark it as "won't fix for now".

**Comment by Rushor** [comment]
i can provide a patch for that, but i don't know if it breaks other pet mechanics later. Also would need the help of Keader then :)

**Comment by Keader** [comment]
I have a fix for it, i will send tomorrow

**Comment by Keader** [comment]
test now.
Is not a perfect system, but a big improvement :)

**Comment by Dranah** [comment]
well yes, its some kind of improvement, the pet will now SOMETIMES opt to walk around the wall.
I can't find much logic behind when he decides to move and when he decides to stare.
So uhh idk. This is the most that can be done about it?

**Comment by Keader** [comment]
Can you give me reproduce case of fail?

**Comment by Dranah** [comment]
Yep, like here:
I spam attack at this spot, he doesn't move around:
![WoWScrnShot_100519_192513](https://user-images.githubusercontent.com/31132743/66258457-e343c400-e7a5-11e9-8b8e-936ff9f2eaa2.jpg)
If I step a few yards behind, he does begin to move (might not be visible on the screen but he properly moves to the left and begins to attack when the wall is no longer blocking:
![WoWScrnShot_100519_192558](https://user-images.githubusercontent.com/31132743/66258466-fbb3de80-e7a5-11e9-964d-2db760ec6f7b.jpg)

**Comment by Dranah** [comment]
My experience shows it has to do with range: if the pet is not only LOS but also out of range so that he needs to move closer, now he can properly walk around obstruction.
However if the pet isn't out of range, he still won't walk around wall to get in LOS.

**Comment by Keader** [comment]
Test now :)

**Comment by Dranah** [comment]
Same as before, was the fix properly built?

**Comment by Keader** [comment]
It's a big edge case, i will not look it now.
Like i said, it's a improvement, not a 100% fix.

**Comment by Dranah** [comment]
Alright well, it works if the pet is already moving. That's an improvement i suppose. Not perfect but it's better than it was.
