### ISSUE TITLE
[Quest] Ursoc, the Bear God - Tur Ragepaw not moving, then vanish after dialogue

### ISSUE THREAD

**Issue by hollydesired** [WoWManiaUK/Redemption#3612]
Quest Link: https://www.wowhead.com/quest=12249/ursoc-the-bear-god

How it works atm: Player would speak to NPC - Tur Ragepaw, after choosing which form Ragepaw should take, Ragepaw just stands on the same spot and vanishes after a while. Would respawn later but he still just stands and vanishes after dialogue.

How it should work: After dialogue, Tur Ragepaw should start moving into Ursoc Den and summons Ursoc for the quest.

**Comment by Kitzunu** [comment]
I know that this works initially, make a ticket and a GM can help you to reset the NPC for the quest.

The issue here is that the NPC/Event doesnt reset properly if it fails, like other quests that have been fixed before @Rushor

**Comment by hollydesired** [comment]
Just an update, i have opened ticket twice in game, and the GMs were very kind to help to reset the NPC & guide me to try deleting cache. Unfortunately, the issue is still there where the NPC just disappears a while after the dialogue ends.
