### ISSUE TITLE
[NPC] Troll Roof Stalker

### ISSUE THREAD

**Issue by Kitzunu** [WoWManiaUK/Redemption#3614]
Entry: 23090

How it works:
These are not immune to mind control

How it should work:
They should be immune to mind control. [Source](https://www.wowhead.com/npc=23090/troll-roof-stalker#comments:id=1044328)

Fix:
```sql
UPDATE `creature_template` SET `mechanic_immune_mask`=`mechanic_immune_mask`|1 WHERE `entry`=23090;

**Comment by Rushor** [comment]
btw do hey have waypoints on the realm? they should have. can add later :)

**Comment by Kitzunu** [comment]
I dont know tbh, never thought of it
