### ISSUE TITLE
Warlock pet: Infernal

### ISSUE THREAD

**Issue by soulblade128** [WoWManiaUK/Redemption#3616]
**Links:**
https://wow.gamepedia.com/Infernal_(warlock_minion)
https://wow.gamepedia.com/Immolation

**What is Happening:**
Currently, when you use this ability on a warlock, it drops the Infernal, and it only uses it's melee attack.

**What Should happen:**
When it lands, it is not only supposed to run in and melee attack, but it is supposed to have a passive Immolation aura that does fire damage to all hostile around it.

**Comment by Dranah** [comment]
He works as intended, the aura activates by proc when the infernal is being attacked.
