### ISSUE TITLE
[Quest] Spawn of Jubjub

### ISSUE THREAD

**Issue by Wolch** [WoWManiaUK/Redemption#3620]
**Links:**
https://classic.wowhead.com/quest=7946/spawn-of-jubjub
http://www.wow-mania.com/armory/?quest=7946
**What is Happening:**
Jubjub does not come to Morja when the Dark Iron Ale Mug is placed near her, thus she does not give the quest. I tried to place several mugs, also tried to place mugs near Jubjub, but nothing's happening.

**What Should happen:**
According to the comments on Wowhead:
To get the egg there are a couple things that you need to do.
1. You need 2 Dark Iron Ale Mug which you can get by going into the Grim Guzzler in BRD, buying from the AH, or having a high level friend get them for you.
2. Go to the Darkmoon Faire when it has appeared.
3. Locate Morja, the orc female near the wagons.
4. Right click on ONE mug, when the hand starts to glow place the mug on the ground next to Morja. (note: do not click on Morja before this)
5. Wait for Jubjub to return to Morja, this may take some time, but he should jump back to her.
6. When he has returned, talk to Morja and complete the quest. This means you give her the other Dark Iron Ale Mug that you have.
7. One week later your Unhatched Jubling Egg will hatch and you will have your own jubling running around with you.

**Comment by Rushor** [comment]
i have an event for that :)

**Comment by Rushor** [comment]
fixed

![I](https://i.imgur.com/DR22ZKW.jpg)
![I](https://i.imgur.com/GotfW3H.jpg)
