### ISSUE TITLE
Unable to start quest chain Jagged Shards

### ISSUE THREAD

**Issue by Elizzardra** [WoWManiaUK/Redemption#3621]
**Links:**http://www.wow-mania.com/armory/?quest=13136 - quest.
http://www.wow-mania.com/armory/?item=43242 - item that open a quest chain.

**What is Happening:**Doesn't matter how many Spiked Ghouls i killed the quest item which are opening quest chain isn't drop.  

**What Should happen:** After i kill Spiked Ghoul the quest item should drop (to be able to start new quest chain)

**Comment by Rushor** [comment]
the item should drop if you have quest 13134 REWARDED OR TAKEN.

currently i ony drop while quest 13134 is TAKEN.
