### ISSUE TITLE
bug 

### ISSUE THREAD

**Issue by lkif1** [WoWManiaUK/Redemption#3623]
I have a problem on the abilities tab. I am currently lvl 57 and the Holy Shock lvl1 (required lvl 48) is not available at the grandmaster. So, this is the bug and I cannot upgrade to Holy Shock lvl2.

Can you check this bug please?

Thanks

**Comment by Oganku** [comment]
This spell is only available if you unlock it in the holy talent tree, which you probably haven't. It's not a bug.
