### ISSUE TITLE
Darkmoon Faire

### ISSUE THREAD

**Issue by TaylrT** [WoWManiaUK/Redemption#3624]
**Links:**

**What is Happening:**
Wow-Mania Redemption:  Darkmoon Faire prizes are not available- you can purchase bags with tickets but the bags are empty.

**What Should happen:**

"Guaranteed one unique item"

![image0](https://user-images.githubusercontent.com/56379683/66540578-f0d4b300-eaf1-11e9-95d3-18650e42afa4.jpg)

**Comment by TaylrT** [comment]
bags are empty- quests still available. GMs are experiencing the  same issues. Located outside of Thunderbluff right now.. I lost 36 tickets due to this. GM reference: Divigrac

**Comment by wow-mania** [comment]
What is the quest?
