### ISSUE TITLE
[General] Ignore

### ISSUE THREAD

**Issue by Kitzunu** [WoWManiaUK/Redemption#3625]
**What is Happening:**
Currently, you can send in-game mail to a player who has got you on ignore list.

**What Should happen:**
You should not be able to send mail to a player who has got you on their ignore list

**Suggestion:**
I do not know how it was on retail for this specific suggestion, that is why I make it a suggestion. But currently on WoW Classic when you ignore a player all characters on that specific account are ignored. But I could not find any info on that particular thing from retail wotlk.

**Comment by wow-mania** [comment]
Ignore is for chat only we do not implement it for mail.

**Comment by Kitzunu** [comment]
Mail is a retail function, so this is an issue.

" Ignored characters cannot ask to duel you, or send you mail[1]"
https://wow.gamepedia.com/Ignore

**Comment by Rushor** [comment]
alright so where are ignored guids handled?

**Comment by Kitzunu** [comment]
SocialMgr.cpp maybe? Idno
