### ISSUE TITLE
[Trash] The Ramparts of Skull

### ISSUE THREAD

**Issue by Kitzunu** [WoWManiaUK/Redemption#3626]
**What is Happening:**
NPC's at the Ramparts of Skulls are not fighting each other.

**What Should happen:**
These NPC's should attack each other when players get up to the ramparts without a player needing to engage the fight.

Concerns:
Kor'Kron Primalist
Kor'Kron Invoker
Kro'Kron Vanquisher
Skybreaker Protector
Skybreaker Vicar
Skybreaker Dreadblade
Skybreaker Hierophant
Skybreaker Marksman

**Comment by Rushor** [comment]
Will fix that

**Comment by Rushor** [comment]
fixed <3

![I](https://i.imgur.com/6ZR88qx.jpg)

they attack each other now. aggro reset if a player attacks them.
