### ISSUE TITLE
Lack of monsters spawned in an area

### ISSUE THREAD

**Issue by oldmagic** [WoWManiaUK/Redemption#3629]
https://classic.wowhead.com/npc=5472/dunemaul-enforcer
https://classic.wowhead.com/npc=5474/dunemaul-brute
Quest: https://classic.wowhead.com/quest=5863/the-dunemaul-compound

What is Happening: The amount of npcs aint showing up.

What Should happen: According to the links there should be plenty of npcs around these areas but there aint.
This makes the quest taking way too long as after one npc is killed it takes a good amount of time before respawning.

**Comment by Oganku** [comment]
From my experience of having done the quest multiple times, there are plenty of both types of ogres near the spot marked 43,57 on the map (north-western camp). Last time I did the quest was less than a month ago, so I would be surprised if there was an issue with that.

**Comment by oldmagic** [comment]
Then i can say as i just did that one 10mins ago that, that's not the case.
Or i just had bad luck or you better luck then me finding them.

**Comment by wow-mania** [comment]
Send me the actual NPC id and I can look into it. Otherwise there is nothing we can do. This is called chance.
