### ISSUE TITLE
bug icc adds

### ISSUE THREAD

**Issue by yeahpallypowa** [WoWManiaUK/Redemption#3630]
when the target is under slowdown effects and when the shadow priest cast his mind control spell 
the priest gains a speed buff after the latter is complete
this speed buff get canceled when the priest is affeted by any slowdowns
and no fly hack btw valithria mechanis give you the posibility to fly

**Comment by WhitephoenixTheBunny** [comment]
We need more information.
Steps, mobs names, ...

**Comment by Rushor** [comment]
do you mean the clouds?
