### ISSUE TITLE
Icc speed gain from Mind controlling Ymirjar Frostbinder

### ISSUE THREAD

**Issue by yeahpallypowa** [WoWManiaUK/Redemption#3631]
**Links:**
https://www.wowhead.com/npc=37127/ymirjar-frostbinder#abilities:mode=h25
https://classic.wowhead.com/spell=605/mind-control

**What is Happening:**
when the Ymirjar Frostbinder "cause normally i use the mind control to have benefit from the aoe damage" is under slowdown effects and when the shadow priest cast his mind control spell
the priest gains a speed buff after the latter is complete
this speed buff get canceled when the priest is affected by any slowdowns
and no fly hack btw valithria mechanics give you the posibility to fly

**Comment by Rushor** [comment]
> valithria mechanics give you the posibility to fly

that is intended

**Comment by Rushor** [comment]
i do not undertand this

**Comment by Rushor** [comment]
https://i.imgur.com/Kjwk9m5.jpg

the creatures does not has any spells and i do not get and speed once the effect faded? cannot reproduce this
