### ISSUE TITLE
[BOSS] Sindragosa Parry-Haste

### ISSUE THREAD

**Issue by slaniaxx** [WoWManiaUK/Redemption#3632]
Sindragosa should have parry-haste mechanic enabled. This mechanic makes boss hit faster if it parries any attack. This caused tanks to cap expertise (56 on retail) for Sindragosa fight as a survival stat.

Currently Sindragosa does not gain any visible haste from parrying. Between 15 Expertise and 56 expertise the incoming damage does not seem to differ. 
(Please test on dev as I was not able to get those 2 expertise totals without any changes to the other survival related stats and raid environments were different.)

Note: Halion fight should also have parry hasting enabled but I was not able to test it.

Note2: This is the cleanest explanation I could find regarding parry hasting. 
"
When you parried an attack, if your swing timer would get up to 40% haste(depending on when your swing timer was) on your next melee swing.

Bosses would benefit from that, unless Blizzard tagged them to not have parry haste.

This made is what a lot of prot warriors complained about in WotLK (moreso than Druids) because we had a 1.6 weapon speed but we could parry, yet we had to spam Heroic Strike, rather than press it once every 2 seconds like a Druid, because it could be "Heroic Strike, parry boss attack, heroic strike <1second later"

As for the ICC one, Sindragosa was the only boss with parry haste, which is kind of ironic considering she hit like a truck on heroic (Her melee hits we're just as strong as her frost breath, so 30-40k swings)
"

**Comment by Rushor** [comment]
will check the flag extra

**Comment by Rushor** [comment]
CREATURE_FLAG_EXTRA_NO_PARRY_HASTEN removed
