### ISSUE TITLE
[ICC] Aggro behaviour for trash in first room of ICC

### ISSUE THREAD

**Issue by Rushor** [WoWManiaUK/Redemption#3638]
So the aggro behaviour in the first room in front of marrowgar is insane wrong.

Those champions (ids: 38194, 37967,37586,37120,37589,37928,37996,37689) should not attack creatures in the second room. They should evade once they enter room two.

Those hostile units (ids: 36724, 37012, 37007) should not attack any creatures(champions) in room one.

**Comment by Rushor** [comment]
![I](https://i.imgur.com/PJGwMm5.jpg)

this looks more smooth now.

f.ex.: http://cata.cavernoftime.com/npc=37007 can no longer attack units in room one.

**Comment by Kitzunu** [comment]
🖤
