### ISSUE TITLE
[Event/Quest] Hallows End - Let the Fires Come / Stop the Fires

### ISSUE THREAD

**Issue by jarvik76** [WoWManiaUK/Redemption#3641]
**Links:**
http://www.wowhead.com/quest=12139/let-the-fires-come
http://www.wowhead.com/quest=11219/stop-the-fires

**What is Happening:**
The amount fires on the buildings are dedsigned for a high-population server, meaning it takes several tens of people to put out, as the fires are continously spawning and spreading.
On a low-population server this means there are not enough people available to put out the fires in time before the interval event expires.

**What Should happen:**
Fires should be slower to spread or respawn, in order for low population to complete it before the interval of the event expires.

**Comment by Rushor** [comment]
Okay

**Comment by wow-mania** [comment]
People have been doing this for 5 years and it works.
I give you the fact that is harder with fewer people but we can't change functionality like this because not enough people show up for an event.

**Comment by jarvik76** [comment]
Fair enough, thanks for your thoughts.

**Comment by Echinaceax** [comment]
Funny story, Ally have too many and Horde hasnt got any fires, and quests are auto completing
