### ISSUE TITLE
[Mechanic] Pets attacking while feared

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#3642]
I noticed this using an interaction with Turn evil ID 10326 and any warlock or DK minion, but it could be a general issue that happens with other fears used on pets too.
**How it works atm:** If the pet is on defensive stance and set to follow owner, if they are feared the defensive mechanic sends them to attack the caster (paladin) , ignoring the fear effect and letting the pet keep attacking and casting. The magical debuff is visibly present and is also dispellable, so the fear is there, is just not working.
Steps to repro:
1. set a demon pet, i.eg. felhunter on def stance and follow
2. do NOT send it to attack
3. cast turn evil on pet with an enemy paladin
4. watch pet attacking and casting while feared

This method to reproduce doesn't work on gargoyle because they have no stances and generally just attack the target they were cast on, but it has been reported that sometimes gargoyle bugs the same way for whatever reason. Would be nice to make a general fix.

**How it should work:** When a pet is feared, it should never be able to attack or cast.

**Comment by Rushor** [comment]
The attack overrides the fear i guess

**Comment by Dranah** [comment]
Possibly. Happens on Aggressive stance too, but not on passive, and not if the pet is set to "Stay" in any stance.
No clue how to trigger it for gargoyle though, it happens randomly.
