### ISSUE TITLE
Blazing Hippogryph slow

### ISSUE THREAD

**Issue by FPSTordah** [WoWManiaUK/Redemption#3643]
**Links:**
https://www.wow-mania.com/armory/?item=54069

**What is Happening:**
Using the mount in a flight restricted area, the mount moves at 60% speed. The Mount will speed up once it get's to a flight capable area. Confirmed in Dalaran and Stormwind. A friend also said in Dalaran I was in Parachute mode.

**What Should happen:**
The mount should scale to what flying I have. I have Artisan/Cold weather

**Comment by wow-mania** [comment]
Imported mounts do not scale. As-is.

**Comment by FPSTordah** [comment]
Ok then the Tooltip needs to get changed because it says otherwise.

**Comment by WhitephoenixTheBunny** [comment]
@wow-mania I will re-send you the list with hippogryph that need a fix.

**Comment by wow-mania** [comment]
ok. if it is the case we speed up the mount on the next client update.
