### ISSUE TITLE
[Spell] Deathchill Bolt

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#3644]
https://www.wowhead.com/spell=70594/deathchill-bolt
cast by https://www.wowhead.com/npc=37949/cult-adherent
during encounter https://www.wowhead.com/npc=36855/lady-deathwhisper

**How it should work**: This spell should be interruptible by default. Once the adherent is empowered or shielded by Shroud of the Occult, those buffs give them immunity to interrupts, however with no such buff present, the casts should be possible to silence and interrupt.

**How it works atm:** This spell is shown "immune" to interrupt effects even with no buffs present on the add.

**Comment by Dranah** [comment]
Still not interruptible.

**Comment by Keader** [comment]
Test now in dev.

**Comment by Dranah** [comment]
The spell is now interruptible but also when the add is shielded.
Shroud of the occult (70768) and Dark Empowerment (70901) are supposed to make the add immune to interrupts.
It should be interruptible by default, but not when one of these effects are present.

**Comment by Dranah** [comment]
Shroud of the occult now properly prevents interruption.
Dark Empowerment still does not.
Getting there.

**Comment by Dranah** [comment]
This got reverted by the last update. Idk what the hell is going on. The buffs no longer grant immunity to interrupt.

**Comment by wow-mania** [comment]
Nothing changed. Code is identical to dev and it works on dev.
