### ISSUE TITLE
[Boss/NPC] Deformed Fanatic

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#3645]
https://www.wowhead.com/npc=38135/deformed-fanatic
created by https://www.wowhead.com/npc=36855/lady-deathwhisper via https://www.wowhead.com/spell=70900/dark-transformation
https://www.wowhead.com/spell=70670/shadow-cleave

The Dark transformation buff is properly adding damage increase however has 2 effects missing:

1. Missing the 40 or 50% (sources conflict) movement speed snare granted by the dark transformation effect
2. Missing the 50% size boost on the NPC granted by the dark transformation effect

3. Additionally, there is an issue with the add "instacleaving" after deformation, which I believe could be because the transformation resets both his melee swing timer and the cooldown on Shadow cleave.
I don't think this is intended because I could not find a single video or log from blizz where the tank would take any damage instantly as the add Deforms, they always have time to run away and begin kiting before taking a single hit. 
While here, you get cleaved by the Cult Fanatic and if 1second later lady deforms the add, you eat another, empowered Cleave for 30k+ damage.
While this does assume a metric ton of bad luck, it can lead to wipes at random.

**How it should work:**
The adds should be slowed by default, making them kitable as described in all blizz sources.
They should gain an increase in size by their buff as well, making them stand out among other npcs.
The cooldown on Shadow Cleave should not reset because of the Transformation.

Sources
As per wiki:
"Deformed Fanatics should be kited, which is quite easy because their movement speed is halved."
wowhead:
"While this isn't an answer to your question, the mobs are already self-snared. As long as you keep running they won't catch up with you. When our tanks tried to take the time to snare them the tanks just got owned from their abnormally massive damage."
https://www.mmo-champion.com/threads/684184-Deformed-Fanatic-hot-damn >about what happens if you don't kite them

**Comment by Keader** [comment]
Size fixed.
Slow fixed.
Cleave is not possible reproduce.
For me, always work fine.

**Comment by Dranah** [comment]
The size increase works now, the slow does not.

**Comment by Keader** [comment]
test now in dev.
