### ISSUE TITLE
[Boss/NPC] Adds on LDW cannot be CC'd

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#3646]
https://www.wowhead.com/npc=36855/lady-deathwhisper
https://www.wowhead.com/npc=37890/cult-fanatic
https://www.wowhead.com/npc=38135/deformed-fanatic
https://www.wowhead.com/npc=37949/cult-adherent
https://www.wowhead.com/npc=38010/reanimated-adherent
https://www.wowhead.com/npc=38009/reanimated-fanatic
https://www.wowhead.com/npc=38136/empowered-adherent

**How it should work:** All types of adds spawning on Lady Deathwhisper encounter should be susceptible to CC (unless their shield or martyrdom cast makes them immune to it)
NOTE: Lady transforming the adds around is not affected by the adds being CC'd at all, both Dark Martyrdom, Dark Transformation and Dark Empowerment can be cast on CC'd adds.
from wowhead>
"It's imperative that you get her to P2 ASAP at this point! While she is in P1, she can turn the humanoids into undead, even if they are CC'd."

**How it works atm:** All adds on the encounter are fully immune to CC, snare, interrupt, everything by default.

Sources:
Here's a video where you can see a Reanimated add getting stunned by a charge:
https://www.youtube.com/watch?v=JXTE2VJSJS0
Here's a discussion from forums about the Full House achievement which requires heavy CC:
https://www.mmo-champion.com/threads/713046-Lady-Deathwhisper-Full-House-Achievement
Currently the achievement requires the raid to highly outgear the content.
Here's another strategy compilation from wowhead:
https://www.wowhead.com/achievement=4535/full-house-10-player#comments
By GraveDiggerX (18,910 – 4·57·60) on 2009/12/26 (Patch 3.3.0)
Deformed Fanatic - Kited around by our Hunter. CAN NOT let it hit anyone. Will one shot anything but a tank, which will die in 2 hits.
Reanimated Fanatic - Shackled by our priests.
By Enquillion (40,606 – 8·49·217) on 2009/12/17 (Patch 3.3.0)
Reanimated Fanatic = Turn Evil from our (holy) paladin

**Comment by Dranah** [comment]
There is no change, they are still immune to everything.

**Comment by Keader** [comment]
Test now in dev.

**Comment by Dranah** [comment]
The adds can now be cc'd as intended.
However, the Dark Martyrdom cast must ignore CC (can be cast while CC'd and make them immune to any CC during cast) and currently it does not.
Right now you can interrupt the martyrdom cast with CC and it bugs the add so that it wont even attack after.

**Comment by Dranah** [comment]
Dark Martyrdom is no longer possible to interrupt with interrupt/silence effects but you can still stun/fear the add and it breaks it. Gotta be immune to all CC during the cast (similar to brundir casting Overload in Ulduar)

**Comment by Dranah** [comment]
This got reverted by the last update idk why. Can you please reapply.

**Comment by wow-mania** [comment]
Nothing changed as far as I can tell.

**Comment by Rushor** [comment]
me neither btw

**Comment by Dranah** [comment]
Well shit, 1 week ago the adds were possible to CC as per the fix. Now they aren't. That's all I can tell.
Just reapply the fixes.
