### ISSUE TITLE
[Quest] Fei Fei's Treat

### ISSUE THREAD

**Issue by WhitephoenixTheBunny** [WoWManiaUK/Redemption#3648]
The quest [Fei Fei's Treat](https://www.wow-mania.com/armory/?quest=10919) requires the quest [Digging for Prayer Beads](https://www.wow-mania.com/armory/?quest=10916).
This is a side quest of Digging for Prayer Beads, you feed the dog and he will show you were he burried the quest item.

So far I can tell, this issue is random.
I had abandoned and retook quest, relogged and deleted cache, opened a ticket, had a GM checking with me, he could see the quest, I was unaured, reloged, deleted cache and still no quest.

Is not a "big issue" since the main quest (Digging for Prayer Beads) is doable, but something is probably wrong on the requirements, since I have dones most of all the quests in Hellfire.

**Comment by Rushor** [comment]
changed requirements static now.

In order to see the quest "Fei Fei's Treat" by https://www.wow-mania.com/armory/?npc=20206#starts, you will need to have quest [Digging for Prayer Beads](https://www.wow-mania.com/armory/?quest=10916) active in log (not completed or rewarded.
