### ISSUE TITLE
alchemy mixology not working

### ISSUE THREAD

**Issue by Zaylah** [WoWManiaUK/Redemption#3649]
**Links:**
char name zagita horde goblin

**What is Happening:**
do not get two hours for a flask or elixir

**What Should happen:**
time should be 2 hours on flasks and elixirs

**Comment by Kitzunu** [comment]
For @Keader: Maybe possible to make the same fix for both of the issues? https://github.com/WoWManiaUK/Blackwing-Lair/issues/2429

**Comment by WhitephoenixTheBunny** [comment]
What the spec?
I have several alchemist and the last time I checked I had the 2h buff

**Comment by Echinaceax** [comment]
Same for me on Reign @Kitzunu. ive added my comment there

**Comment by Rushor** [comment]
code is fine for that

```
// Mixology - duration boost
		if (target->GetTypeId() == TYPEID_PLAYER)
		{
			if (spellProto->SpellFamilyName == SPELLFAMILY_POTION && (
				sSpellMgr->IsSpellMemberOfSpellGroup(spellProto->Id, SPELL_GROUP_ELIXIR_BATTLE) ||
				sSpellMgr->IsSpellMemberOfSpellGroup(spellProto->Id, SPELL_GROUP_ELIXIR_GUARDIAN)))
			{
				if (target->HasAura(53042) && target->HasSpell(spellProto->Effects[0].TriggerSpell))
					duration *= 2;
			}
		}
```

**Comment by Dranah** [comment]
It works as intended, but you only get the bonus for recipes that you can create yourself.

**Comment by Rushor** [comment]
that's the condition aswell yeah
