### ISSUE TITLE
Sets for leveling with MP

### ISSUE THREAD

**Issue by luciano004-coder** [WoWManiaUK/Redemption#3651]
I was wondering if the toons leveled with Maniac Points to level 70 included or not an extra equipment or set. GM Divigrac clarified and linked to me the items that a HUMAN PRIEST should have at level 70, which are the following: 

https://www.wow-mania.com/armory/?item=27537
https://www.wow-mania.com/armory/?item=28415
https://www.wow-mania.com/armory/?item=28232
https://www.wow-mania.com/armory/?item=27778
https://www.wow-mania.com/armory/?item=27948

The problem is that the set is for warlocks, since that the 4th bonus improves Seed of Corruption instead of something for priests.

Thanks in advance.

**Comment by Rushor** [comment]
You get the Set by gm or do you buy it some where?

**Comment by Kitzunu** [comment]
It works like this:
When you go to the NPC in the mall and choose any level upgrade you will also recieve gear appropirate to that class and level.

Maybe it needs to be rechecked on Dev to see that it gives appropirate gear

**Comment by luciano004-coder** [comment]
I know it's supposed to be that way. The thing is that GM Div tested it and
he advised me to write the ticket in github.

Best.

**Comment by Kitzunu** [comment]
Oh okay, I didnt understand that Divigrac had tested it at first. 
Janitor will have to look over the code for this one

**Comment by luciano004-coder** [comment]
I didn't receive anything. I sent a ticket asking if the boost comes with
equipment for priest or not. GM Div linked me those warlock parts, when he
realized it wasn't for priests, he told me that it may be a glitch.

Maybe you should talk directly to him. I'm Ammygdala on game, he'll
remember.

Best.

**Comment by WhitephoenixTheBunny** [comment]
Just tested on dev. I leveled a human priest from 10 to 70 with the boost option, those are the item I have recieved:
![image](https://user-images.githubusercontent.com/31921098/67487624-2a66fb80-f666-11e9-97bd-7de87ec35599.png)
![image](https://user-images.githubusercontent.com/31921098/67487658-3bb00800-f666-11e9-9a6f-0b69949b0d44.png)

**Comment by luciano004-coder** [comment]
Yes, the oblivion set, as I said before, it contains a buff bonus for Seed
of Corruption (warlock ability).

**Comment by Rushor** [comment]
yes i have the code here now.

could you guys pls find a good itemset for mage and priest then? (mage has same issue)

**Comment by Rushor** [comment]
those are the current items:

28415, 1);	// Helm
28232, 1);	// Chest
27778, 1);	// Shoulders
27537, 1);	// Gloves
27948, 1);	// Legs
30908, 1);	// Staff

**Comment by wow-mania** [comment]
this is as is. the amour given is generic and not specifically to a build or spec.

**Comment by luciano004-coder** [comment]
It's unfair for other clothe classes then, with that "generic" set, you are
favouring one class above the other. Honestly I think it's not worthy it to
level a priest with MP if you are giving a set with no bonus.

As a piece of advice, I'd rather provide players the class tier set, which
gives bonusses according to each class and spec.

Best.

**Comment by WhitephoenixTheBunny** [comment]
@wow-mania @Rushor 
I found this tier : https://www.wow-mania.com/armory/?itemset=520
Works for the 3 clothies, but too "low" for level 70 boost
