### ISSUE TITLE
Missing texture

### ISSUE THREAD

**Issue by erl7902** [WoWManiaUK/Redemption#3652]
**Links:**

https://imgur.com/a/pSiPVcV

**What is Happening:**

I was in Kolkar Crag when I stumbled upon this missing texture. I think it was from the corpse of a Kolkar Outrunner, but I'm not sure.

**What Should happen:**
 
the appropriate texture should load instead of the checkered cube?

**Comment by Kitzunu** [comment]
This is due to your launcher not updating correctly.

Move your folder to a root drive
Download a new Launcer.exe
Start Launcher.exe as an Administrator
Delete Cache

that will fix it

**Comment by erl7902** [comment]
I am using linux - I thought I wasn't supposed to use the launcher? my copy is also very new, downloaded yesterday via gdrive.

**Comment by Kitzunu** [comment]
I dont know if it is supported or not, but you could try to re-download patches from http://wow-mania.com/downloads and replace your current ones, could fix the issue

**Comment by wow-mania** [comment]
Launcher will only run on Windows since it uses .NET Framework.
If you are running on MAC or Linux you need to manually install the updates available to download on our website.
