### ISSUE TITLE
[Spell/Mechanic] Losing movement speed bonus after leaving a vehicle

### ISSUE THREAD

**Issue by cathyr1** [WoWManiaUK/Redemption#3655]
This spell https://www.wow-mania.com/armory/?spell=26023 is broken whenever the player enters a vehicle (e.a. demolisher, cannon in Wintergrasp or a dragon in Occulus).

With 2/2 of this talent normal and mounted speed is 115 % until the player enters the vehicle but after leaving it its only 100 % so the talent is not working until relog or switch talents which costs all mana.

This was once fixed but after some patch its broken again. Pls fix it permanently if possible. It causes quite a big handicap especially in Wintergrasp, Strand of Ancients or Isle of Conquest.

Thanks a lot.

**Comment by Dranah** [comment]
Confirmed.
**How it works:** Entering a vehicle turns off movement speed boosts active on the player and it does not turn them back on when leaving until the player relogs.
**How it should work:** The movement boosts should reactivate after leaving the vehicle.

Note: it affects other movement boost effects such as Tuskarr's vitality enchant (spell ID 47901), the movement speed metas (tireless skyflare/starflare item=41375, item=44078, Swift Skyflare/Starflare diamond, item=41339), other movement speed increase talents like assassination rogue (fleet footed: spell=31208)
Non comprehensive list, would be nice to make a general fix.
