### ISSUE TITLE
[Spell/NPC] Death Plague - Rotting Frost Giant

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#3656]
https://www.wowhead.com/npc=38494/rotting-frost-giant
https://www.wowhead.com/spell=72865/death-plague
This is the npc for the 5 eof weekly quest "securing the ramparts" inside ICC.

**How it works atm:**
The timer is wrong. The boss casts the first plague after 10sec as intended and then recasts it every 15sec, flooding the raid with a dozen of plagues in no time.

**How it should work:**
The boss should cast the first plague after 10seconds and then recast only every 50seconds thereafter.
This is visible on any retail videos: https://www.youtube.com/watch?time_continue=8&v=ZGkF36YfR0A 
Note: the original plagues cast by the boss are announced with golden letters by DBM at 0:09, 0:59, 1:49, 2:39 etc. while the jumps are just shown as "plague on XXX".
Note2:
Wowwiki incorrectly states the boss to cast a new plague 'every 15s'. What happens every 15sec is that an ongoing plague expires and needs to jump to a new target.

**Comment by Rushor** [comment]
i think that was fixed in tc

**Comment by Keader** [comment]
I have sniff about It.
Will check today.

**Comment by Keader** [comment]
yes, you are correct.
Fixed.
