### ISSUE TITLE
Halls of Reflection Lichking Event.

### ISSUE THREAD

**Issue by lembnau1** [WoWManiaUK/Redemption#3658]
**Links: https://www.wow-mania.com/armory/?zone=4820

**What is Happening: After a wipe where lk killed sylvanas while the last ice wall was destroyed and we went onto the balcony and the gunship didnt appear, the fight did not reset. GM was also unable to help and told me to report the issue.

**What Should happen: The fight should reset to make it possible to try again.

**Comment by wow-mania** [comment]
Check if it can be reproduced please.

**Comment by Dranah** [comment]
Confirmed.
You can reproduce it as this:
1) Leave 1mob alive on the last wall and let LK get to Sylvanas and smack her in melee until she is below 30k hp.
2) Kill the last mob, making the last wall fall and both Sylvanas and LK begins to run towards the balcony
3) LK will melee her to death while running, making the event unable to finish. LK won't reset, you have no means to re-try the fight.

I could not find any exact info on what should happen in this scenario, but there are two possible fix options:
A) Make LK stop dealing damage (both melee and aura) once the last wall fell and the NPCs are moving. The event is over, you won, he can't kill Sylvanas anymore.
B) Allow LK to kill her while running (by melee or his aura), and make it properly fail the event, make the encounter force-reset.

Imho option

**Comment by Dranah** [comment]
Sylvanas can no longer take damage once the wall has fallen.
