### ISSUE TITLE
[NPC] Dread Captain DeMeza

### ISSUE THREAD

**Issue by Blyatman1** [WoWManiaUK/Redemption#3659]
**Links:**
https://wow-mania.com/armory/?npc=28048
https://wow-mania.com/armory/?achievement=3457

**What is Happening:**
[Dread Captain DeMeza](https://wow-mania.com/armory/?npc=28048) for the "[The Captain's Booty](https://wow-mania.com/armory/?achievement=3457)" achievement is not on top of the bank building in Booty Bay, where she should be.
https://gyazo.com/5716d988dd7b5b9f9839a6a385dfb8dc

**What Should happen:**
Dread Captain DeMeza should spawn on top of the bank building in Booty Bay during the Day of the Dead event.

**Comment by Oganku** [comment]
Pirate Day isn't the same as Day of the Dead. 2 different events. No issue here.

**Comment by Rushor** [comment]
true she spawns during https://wow-mania.com/armory/?event=398 Pirates' Day

Anfang: 18.09.2020 um 00:01
Ende: 19.09.2020 um 00:01
