### ISSUE TITLE
Sindragosa Frost Bombs

### ISSUE THREAD

**Issue by wshircliffe** [WoWManiaUK/Redemption#3662]
**What is Happening:**
During Phase 1, the Frost bombs are dropping before the marked players turn into ice tombs.  This prevents players from taking cover before the frost bombs explode.  Also, upon landing Sindragosa hesitates for a few seconds instead of landing immediately.

**What Should happen:**
The Frost Bombs should drop after the Ice Tombs are formed.  Sindragosa should not hover in the air before landing after Air Phase.

**Comment by wow-mania** [comment]
Closing this issue as it is a side-effect of a previous fix. Other issue will be reopen.
