### ISSUE TITLE
 [Bloodsail Sash] transmog 

### ISSUE THREAD

**Issue by kallemeisner** [WoWManiaUK/Redemption#3663]
**Links:**
 [Bloodsail Sash] 

**What is Happening:**  [Bloodsail Sash] does not show up when trying to transmog 

**What Should happen:**  should show up  so you can select it like all other bloodsail pieces.

**Comment by wow-mania** [comment]
As- is please read our guide and rules on the transmogrification.

**Comment by kallemeisner** [comment]
i got told to report it.
________________________________
Fra: Janitor <notifications@github.com>
Sendt: 5. november 2019 08:47
Til: WoWManiaUK/Redemption <Redemption@noreply.github.com>
Cc: kallemeisner <kallemeisner@live.dk>; Author <author@noreply.github.com>
Emne: Re: [WoWManiaUK/Redemption] [Bloodsail Sash] transmog (#3663)


As- is please read our guide and rules on the transmogrification.

**Comment by kallemeisner** [comment]
when i try look it up on google i get this.
________________________________
Fra: Janitor <notifications@github.com>
Sendt: 5. november 2019 08:47
Til: WoWManiaUK/Redemption <Redemption@noreply.github.com>
Cc: kallemeisner <kallemeisner@live.dk>; Author <author@noreply.github.com>
Emne: Re: [WoWManiaUK/Redemption] [Bloodsail Sash] transmog (#3663)


Closed #3663<https://github.com/WoWManiaUK/Redemption/issues/3663>.
