### ISSUE TITLE
grounding totem is not working with mage's deep freez

### ISSUE THREAD

**Issue by Vircy** [WoWManiaUK/Redemption#3664]
**Links:**

**What is Happening: the frost mage spell " deep freez" completely ignore restoration shaman ( didn't test other specs , but i guess it would be the same) grounding totems , when a mage cast it on me i get frozen and the buff of the grounding remains untouched.
on my character the only things affecting my geounding totem spell is the 4 items set bonus from the pvp set that reduce it's CD by 1.5 seconds**

**What Should happen: the grounding totem should absorb the deep freez**

**Comment by Rushor** [comment]
hmm https://github.com/TrinityCore/TrinityCore/issues/15108

**Comment by Keader** [comment]
2015 commit rushor, is already here.
Anyway, i will take a look tomorrow.

**Comment by Rushor** [comment]
yes was just a rev to the old fix (history xD)
