### ISSUE TITLE
Quest Time for Answers

### ISSUE THREAD

**Issue by Jerre84** [WoWManiaUK/Redemption#3665]
I cant finish the quest. I see Matthias Lehner who is the quest giver and reciver. I can also see the questionmark but I cant finnish the quest.

**Comment by wow-mania** [comment]
Make sure you have all pre-reqs. This quest have conditions.

**Comment by Jerre84** [comment]
I know. Have done all pre quests. The questionmark and questgiver is there but I cant turn it in. 

Skickat från Yahoo Mail på Android 
 
  På tors, nov. 2019 klockan 9:53, Janitor<notifications@github.com> skrev:   
Make sure you have all pre-reqs. This quest have conditions.
