### ISSUE TITLE
Expertise Cap

### ISSUE THREAD

**Issue by slaniaxx** [WoWManiaUK/Redemption#3666]
**What is Happening:**
For Boss level mobs (lv83) a melee dps character with 21 Expertise does not get dodged from behind.

**What Should happen:**
For boss-level mobs (which are calculated as your level + 3) the soft cap is 6.5% dodge or 26 expertise , and the hard cap is 14% parry or 56 expertise.
Thus the boss should be able to dodge the player if the player is below 26 expertise.

**Comment by Dranah** [comment]
To my knowledge this is intended. The expertise cap was reduced to 22 sometime on patch 3.3.5a with no real documentation other than a blue post from blizz somewhere. I can't find that discussion from EJ anymore, but it does answer why every private server that runs on 3.3.5a is having the same expertise caps set.
I do get seldom dodges at 21, but the chance at that point is very low so it's safe to say the cap is 22.

**Comment by slaniaxx** [comment]
Taken directly from EJ Fury Warrior compendium for 3.3.5 = The expertise cap is considered a "hard" cap. Any excess will result in zero theoretical gain. From what you have read in previous discussion, the dodge cap for a boss is 6.5 percent. One must come up with 26 expertise points (214 rating) to circumvent every dodge.

The reason every server has the same problem might be similar to the problem with Blood DK's dancing rune weapon. Since most(every?) servers use TrinityCore, it might be a TC problem that's never been fixed.

**Comment by Dranah** [comment]
It was changed during the patch, likely a few weeks before the cata prepatch (long after guides and compendiums were written). Which means having it changed to 26 is as equally blizzlike 3.3.5a to me as leaving it on 22. At this point I don't particularly care whether we change it or not, I leave it up to the devs.
Dancing Rune Weapon is a completely different type of issue.

**Comment by Kitzunu** [comment]
@Dranah according to wowwiki it was changed in cata 4.0.1
Wrath-Logo-Small/Cataclysm-Logo-Small Patch 4.0.1 (12-Oct-2010): Expertise rating changed from 8.1974973675 to 7.688690185546875 per 1 expertise.; Many talents with expertise were removed from game.; At level 85 you will need 30.0272 rating pr 1 expertise.

But maybe it is not the same thing? o.o

**Comment by Dranah** [comment]
Is not, because on cata they reduced the cap even further, to 20 I believe.
What i'm talking about is a change towards the end of 3.3.5a, where they reduced it to 22. It was undocumented and only a handful of people noticed it and they had a discussion about it on EJ after a GM finally confirmed in a blue post that the cap is now indeed lower so people don't need more than 22 expertise. 
But as I said, i don't mind for it being changed to 26. It was that way for most of the expansion.
