### ISSUE TITLE
[NPC] Scarshield Quartermaster - 9046 - Blackrock Mountain

### ISSUE THREAD

**Issue by jarvik76** [WoWManiaUK/Redemption#3667]
**Links:**
https://www.wowhead.com/npc=9046/scarshield-quartermaster

**What is Happening:**
Respawn timer is currently set to 2 hours, this is certainly longer than intended.
(He drops the attunement quest starter for Blackwing Lair, so this has importance for those seeking Achivements in classic content.)
![image](https://user-images.githubusercontent.com/46089380/68484944-3b9f3300-0236-11ea-8343-cd8c5e7a4e4f.png)

**What Should happen:**
Hard to find reliable sources but the comments section in wowhead for both TBC and Cata patches mention a matter of minutes ("2 minutes"), so it is reasonable to assume it was the same in the intervening WOTLK.
A historical edit on wowwiki suggests the spawn timer was 100 seconds in TBC.
https://wowwiki.fandom.com/wiki/Scarshield_Quartermaster?diff=1615252&oldid=1479070

Wowhead:
![image](https://user-images.githubusercontent.com/46089380/68484837-009cff80-0236-11ea-9552-8c151de4056b.png)

http://web.archive.org/web/20051113024126/http://wow.allakhazam.com/db/mob.html?wmob=9046
![image](https://user-images.githubusercontent.com/46089380/68485085-81f49200-0236-11ea-96fc-d0d5d75ee266.png)

**Comment by Kitzunu** [comment]
I agree 2 hours seems off, seeing as the info you have found states that the earlier and later expansions had about a 2 minute respawn.

However, that doesn't really make sense though since the Corpse Decay Timer for Rank 4 mobs (Rares) are at 5 minutes.

But it is as you said, very hard to find evidence since it is so long ago and not many people take notes of these kinds of things :(

**Comment by Kitzunu** [comment]
I just found this comment, seems like a more appropriate time would be over 10 minutes
![image](https://user-images.githubusercontent.com/24550914/68487962-5b3d5800-0244-11ea-9000-2a79497578b5.png)

**Comment by Kitzunu** [comment]
Suggested fix:
```sql
-- This will add 300 seconds = 5 minutes to the respawn timer since 
-- default Corpse Decay Timer is 300 seconds = 5 minutes
UPDATE `creature` SET `spawntimesecs` = 300 WHERE `id` = 9046;

**Comment by jarvik76** [comment]
This seems like a good compromise.

**Comment by wow-mania** [comment]
Fixed. Set to 5 minutes as suggested.
