### ISSUE TITLE
darkspear troll quartermaster

### ISSUE THREAD

**Issue by dutchmen8** [WoWManiaUK/Redemption#3668]
https://wowwiki.fandom.com/wiki/Darkspear_Tabard

noticed that Champion Uru'zin the darkspear trolls quartermaster is missing in sen'jin village.  

Added a link where you can see when he whas added to the game, so its probarly a bug or something why he is gone

**What Should happen:** bring him back in the game??

**Comment by wow-mania** [comment]
This is not a wotlk NPC.
