### ISSUE TITLE
[NPC/Object] Deathbound Ward / Spirit Alarm

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#3670]
https://www.wowhead.com/npc=37007/deathbound-ward
**How it works atm:**
They never have worked blizzlike, but ever since Rushor's changes about a month ago, these trash mobs and their traps behave retardedly. There are now random triggers throughout the instance in all the least appropriate spots.
The giants themselves, they aggro as soon as you enter the raid, then they despawn when reaching the first room and reset to their spot and become impossible to aggro or kill. But then at random occasions they do reactivate and it's especially lovely when they do it during Marrowgar encounter, come through the door and wipe you.

**How it should work:** There should be 4 traps=Spirit Alarms belonging to the 4 giants in random locations in the 2 trash rooms before Marrowgar. They should be visible and possible to disarm for rogues. Triggering a trap should result in a linked Deathbound Ward aggroing, an emote from the ward:
"I... awaken!"
"The master's sanctum has been disturbed!"
"Who... goes there..?"
and applying a slow aura on nearby targets https://www.wowhead.com/spell=70547/spirit-alarm

from wowhead:
"There are total of 4 Deathbound Wards before Lord Marrowgar - two in the first room, two in the second one. There are 4 Spirit Alarms, again two in the first room, two in the second one. Spirit Alarms are activated by a player (or a pet) walking on top of them. They slow everybody in proximity for a few seconds when they go off, and they slow them a lot. Each Spirit Alarm is tied to one of the Deathbound Wards, but it seems like the Alarm and its Ward don't necessarily have to be in the same room."

You should never get a ward activate while fighting Marrowgar, Gunship, or the trash in the upper spire. You should not get wards activate as soon as you enter ICC. 
Note: If you can't script it properly, please just disable the wards as they are.

**Comment by Keader** [comment]
Rushor change, so... rushor need fix it '-'

**Comment by Dranah** [comment]
Ok now rushors fix is reverted. So back from more buggy to less buggy, which is a good start.
Now, can we have a good fix that actually makes the traps work better? :D
As in, there being 4 actual traps in the 2 rooms and no random triggers right on the entrance.

**Comment by Rushor** [comment]
okay fixed!

they now only get's activated if you step close to them. and they yell and they will have a path as soon as they got 'activated'. Once the stone form is removed they will move in circles.

https://i.imgur.com/KhHOHKq.jpg
https://i.imgur.com/9bvcwoE.jpg

**Comment by Dranah** [comment]
Looks good!

**Comment by Drostthehunter** [comment]
@Dranah Should reopen this issue, you have not added the 2 traps, that are present in Plague Quarter right before Festergut and Rotface, i have posted the issue before, those traps summons a pack of 6 reapers coming behind your back once the traps are activated, they have same mechanism as ones in the hall before Marowgar. https://github.com/WoWManiaUK/Redemption/issues/3464
