### ISSUE TITLE
[ICC/Sindragosa] Blistering Cold

### ISSUE THREAD

**Issue by Keader** [WoWManiaUK/Redemption#3672]
Sindragosa: Blistering Cold triggering phase1 cooldown if its mid-cast when you enter p2.
This is fully unrelated of the recent fixes, been happening before as well.
**How it works:** Blistering Cold timer normally resets and begins a different timer for p2 when you enter p2, since its cast every 35s in p1 but only every 65s in p2. However if your raid pushes Sindy to p2 while she is casting a Blistering Cold (the cast started in p1, but ends in p2), the timer is unable to reset/change to the p2 one, and you get the next blistering cold after 35seconds, which wipes you because it coincides with a beacon.
**How it should work:** Even if she begins the cast of Blistering in p1, if she enters phase 2, the timer should modify to the phase2 timer.

Split of #3669

**Comment by Dranah** [comment]
This is still happening. If the transition to p2 happens while she is mid cast, she will use the next Blistering Cold after 35s .

**Comment by Keader** [comment]
Test now
