### ISSUE TITLE
[ICC/Lich King] Harvest Soul (Normal mode)

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#3673]
**Links:**https://www.wowhead.com/spell=68980/harvest-soul
https://www.wow-mania.com/armory/?spell=68980
https://wow.gamepedia.com/Lich_King_(tactics)

**What is Happening:** On normal difficulty, the Lich King sometimes fails to cast his [Harvest Soul](https://www.wow-mania.com/armory/?spell=68980) ability at the supposed timing. If he 'forgets' to cast it once, he won't try again until the next 70s timer has elapsed; however, when he does forget to cast this 6 second long channeled ability, the timing for all his following casts of Defile and Infest are off by a couple seconds. The cause of these failed attempts to cast Harvest Soul seem to be due to the same reason Saurfang fails to cast a mark sometimes (he is just already casting something else while he should be casting Harvest Soul and he simply skips the cast instead of doing it right after). Ref: #3671 

*Note: When he fails to cast Harvest Soul, it eventually leads to a very awkward timing of Defile happening at the same moment as the Vile Spirits are about to crash into the raid, making it nearly impossible to stack behind the boss and properly soak AND avoid Defile for this particular cycle. 

**What Should happen:** On normal difficulty, the Lich King should cast [Harvest Soul](https://www.wow-mania.com/armory/?spell=68980) on one target every 70 seconds, without ever 'skipping' any of the casts.

> Arthas also casts a new spell called Harvest Soul every 70 seconds on a random raid member, which causes 45,000 (25-man 90,000) damage over six seconds. Victims who survive this are sucked into Frostmourne. https://wow.gamepedia.com/Lich_King_(tactics)

**Comment by Keader** [comment]
The only way that i think it can fail, is LK cant find a target.
I put a extra protection, so if he cant find target he will try again in 100 ms
