### ISSUE TITLE
[NPC/Spell] Vengeful Fleshreaper

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#3675]
https://www.wowhead.com/npc=37038/vengeful-fleshreaper
https://www.wowhead.com/spell=71164/leaping-face-maul
https://www.wowhead.com/spell=71163/devour-humanoid

**How it works atm:** They spam their devour ability non stop as soon as you aggro them. They don't leap to you, you have to CC them to interrupt their cast and force them to move a bit closer. 

**How it should work**: They should always use Devour Humanoid after leaping on a target, which has a 5-30yards range. This means they will not cast leap+devour combo if you are stacked in melee range. As described on wowhead:
By kicken (6,621 – 1·17·43) on 2010/02/10 (Patch 3.3.2)
"If desired, stacking close to these guys while fighting will prevent them from jumping all over.

I had my heals stack directly on top of me (tank) while fighting them and they never once got jumped on and stunned. DPS was also spared the stuns if they fell in close.

**Comment by Dranah** [comment]
Still fails to leap. Now leaves 1-2 seconds delay between the Devour casts, suppose when he is meant to leap, but they don't. They can still cast it in melee range.

**Comment by Dranah** [comment]
They seem to have some extra condition to cast the Devour now, they need at least 3-4 targets available and choose randomly, but they still do it in melee. They still don't leap, just devour much less often, and sometimes not at all.

**Comment by Dranah** [comment]
No change :s

**Comment by Keader** [comment]
My last try.
Condition is: Select a random player that is player and is out of melee range.
If still not work, nothing more i can do.
