### ISSUE TITLE
[Talent/Spell] Reckoning

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#3676]
spell id=20177

**How it works atm:** Proc chance is way lower than intended. With 5/5 talent points, I am getting 1 proc out of every 40-50 damaging attacks taken, which is 2-2,5% proc chance instead of the intended 10%.
With 2/5 talent usual spec in a raid scenario, I receive just 1 proc out of approximately 150 attacks on me during an entire raid fight.
I suspect that the talent has only 2% proc chance with full 5/5 points instead of per-point. (so with 2/5 the chance is only around 0,8%)
**How it should work:** The talent should grant 2% proc chance per point, scaling up to 10% chance to proc at max rank.

**Comment by Keader** [comment]
Test now please
