### ISSUE TITLE
[Spell] Dispel Magic (Rank 2)

### ISSUE THREAD

**Issue by JohnBrinkle** [WoWManiaUK/Redemption#3677]
**Links:**
https://www.wow-mania.com/armory/?spell=988
Priest Dispel Magic spell (Rank 2).

**What is Happening:**
Removing two harmful spells works on stacked magic spells and when two
different spells are appiled.
It does not remove two identical spells like two seperated corruption spells on the target.

**What Should happen:**
Dispel Magic rank 2 should dispel two magic spells even if it is the same one two times.
Either on friendly or enemy targets.

**Comment by Dranah** [comment]
Could be same issue as we fixed on Cata: https://github.com/WoWManiaUK/Blackwing-Lair/issues/2987
