### ISSUE TITLE
thunderstorm reflect

### ISSUE THREAD

**Issue by Vircy** [WoWManiaUK/Redemption#3679]
**Links:**

**What is Happening:warriors can reflect shaman's thunderstorm**

**What Should happen:being an AOE spell thunderstorm should not be reflected**

**Comment by Dranah** [comment]
There is no notice of spell reflect not working against AoE effects. It only needs to be a direct attack (not a dot, or aura), and thunderstorm is.
Please provide a written source or video evidence if you still believe it works wrongly, but to my knowledge it is as intended.

**Comment by Vircy** [comment]
https://wotlk.evowow.com/?spell=23920

It is right in the spell description , it is ment to work on targeting
spells any aoe should be non considered , I'm 100% sure about this one
because I had experienced it on retail servers. The only exception that
pops on my mind is the freezing trap but that particular things changes
from patch to patch

Il lun 11 nov 2019, 22:25 Dranah <notifications@github.com> ha scritto:

**Comment by Dranah** [comment]
https://www.mmo-champion.com/threads/624196-Thunderstorm-amp-Spell-Reflection
https://eu.battle.net/forums/en/wow/topic/3888479045

It's a blizzlike feature that it is reflected in wotlk. Was changed on cata.

**Comment by Vircy** [comment]
you sure it was not already like that in 3.3.5?  btw if i will find an
evidence i will let you guys know ^^ thx

Il giorno mar 12 nov 2019 alle ore 00:58 Dranah <notifications@github.com>
ha scritto:
