### ISSUE TITLE
bladestorm gives immunity from shaman's thunderstorm

### ISSUE THREAD

**Issue by Vircy** [WoWManiaUK/Redemption#3680]
**Links:**

**What is Happening:warriros are not suffering from the knock back of the thunderstorm while they are on bladestorm**

**What Should happen:**

**Comment by Dranah** [comment]
Can you provide any 3.3.5a evidence that bladestorm shouldn't make you immune to knockbacks?
As far as I know this is not a bug, only disarms can go through.
