### ISSUE TITLE
Pumpkin Fiend spawning in Stormwind Trade District

### ISSUE THREAD

**Issue by billykitty** [WoWManiaUK/Redemption#3682]
**Links:**
Pumpkin Fiend (https://www.wowhead.com/npc=23545)

**What is Happening:**
After Hallows End 2019 ended, a Pumpkin Fiend began spawning in Stormwind Trade District. It is killing low level characters. When killed it respawns in about 10 minutes.

**What Should happen:**
Pumpkin Fiends should never spawn in Stormwind Trade District.

**Comment by Dranah** [comment]
I cannot locate these on the PTR. Can you provide some screenshots of where exactly they are?

**Comment by Oganku** [comment]
Some GM was spawning pumpkin friends for fun to kill in dal and stormwind, but they seem to have placed a spawn point instead or a single mob in stormwind. 
It is located in between the bank and auction house in the trade district, near Joe Maniac.
Like OP said, the mob being lvl 70 causes problems to low level characters.

**Comment by Dranah** [comment]
That could explain why it isn't present on the PTR. The spawn point probably only exists on the live realm. Now, that means it should be gone once Janitor copies PTR over I guess? @wow-mania

**Comment by Kitzunu** [comment]
If the GM used .npc add it will have a spawnpoint until it is removed, but if the gm have used ".npc add temp" it will be gone after a restart.

Either way, a GM can use .npc delete to remove the npc from the game now...

**Comment by Oganku** [comment]
It's been there since the start of November, so a simple restart doesn't seem to affect it.
