### ISSUE TITLE
[Spell/Pet] Spider Web

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#3683]
spell ID 4167 (web)

**How it works atm:** spider web ability seems to turn on the pets autoattack, sending the pet to go break the CC it just used
**How it should work:** spider web should not turn on the pets autoattack, should simply root the target.
Note: It is normal for the pet to begin auto attacking if another ability is left on autocast or the pet is set to defense/aggressive but it should not activate just by using a ranged CC ability such as the spider's web with everything disabled and the pet on passive. 

original report by Rivax https://github.com/WoWManiaUK/Redemption/issues/3640

**Comment by Dranah** [comment]
No change here.

**Comment by Keader** [comment]
try now
