### ISSUE TITLE
[Boss/NPC] Dark Nucleus

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#3686]
https://www.wowhead.com/npc=38369/dark-nucleus

These are the creatures spawned by Blood Princes in order to protect the range tank from Keleseth.
Their aggro behavior is wrong.

**How it should work:** The nucleus should follow and engage at (apply his dot that gives the Shadow Resonance buff) to the player who LAST hit them with a direct, single target attack. Direct taunts and death grip also work on them. 
**How it works atm:**  The nucleus seems to stick to the target who touch them first, so if someone accidentally hits them, the keleseth tank is unable to get them off. If the keleseth-tank dies (the one who had all the nuclei gathered), no one is able to "take over" because you cannot aggro the nuclei he left behind, they'll ignore you.

**Comment by Dranah** [comment]
There is no change. The nuclei fixate on the first target that touches them.

**Comment by Dranah** [comment]
Well, now the nucleus changes target if the beam is broken by i.eg. the keleseth tank being knocked out of range, but still won't switch target by simply being hit.
The issue seems to be he only re-checks aggro target if the beam is not already active on someone.

**Comment by Keader** [comment]
i found another system bugging it.
Fixed both now.

**Comment by Dranah** [comment]
This fix has been reverted to the previous state (where the nucleus can only switch target if the beam on the previous is broken by range first)

**Comment by Keader** [comment]
You tested it in PTR?
Because in ptr, everything looks correct

**Comment by Keader** [comment]
I send sql file again to janitor, and told to run in live db again.
Closing, since is working in ptr.
