### ISSUE TITLE
[Loot] Gunship Battle 25man

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#3687]
https://www.wowhead.com/object=201873/gunship-armory
How it works: Gunship battle encounter on 25man mode is only dropping 2 pieces of loot instead of 3.
How it should work: Should drop 3 items on 25man.

**Comment by Drostthehunter** [comment]
The loot will be plenty :D

**Comment by Rushor** [comment]
changed to 3 in nh and hc 25 man
