### ISSUE TITLE
[Boss/Spell] Bone Spike Graveyard / Bone Storm

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#3688]
https://www.wowhead.com/npc=36612/lord-marrowgar
https://www.wowhead.com/spell=73142/bone-spike-graveyard
https://www.youtube.com/watch?v=q8cqU_4zzfk
https://www.wowhead.com/spell=69076/bone-storm

1) Timers
**How it works atm:**
- In the first p1, spikes are cast every 18seconds (it has a 18sec cooldown and it triggers in the moment he **starts** casting)
- During heroic Bone Storm, the spikes happen at random depending on how the cooldown was running. Often right after he began to spin, or right after he stops. The Bone Storm duration is same as normal difficulty (24-25s)
- After the first bone storm, the cooldown is reduced to 16seconds, and he ends up casting 3 sets of spikes instead of two. This leads to the Bone Storm being delayed at times.

Timer sample from wow-mania:
Where t=0 is the pull
t=15 spikes begin to cast
t=18 spikes land
t=33 spikes begin to cast
t=36 spikes land
t=50 he either casts bonestorm or bone spike graveyard, depends if his timers bug or not and he casts the other one instantly afterwards. Let's go with the case he actually casts Bone Storm as intended.
(heroic only):
t=53 Bone storm begins
t=53 Spikes begin to cast
t=56 Spikes land
t=71 spikes begin to cast
t=74 spikes land
t=76 bone storm ends

t=88 spikes begin to cast
t=91 spikes land
t=105 spikes begin to cast
t=108 spikes land
t=121 spikes begin to cast
t=124 spikes land
t=129 bone storm begins to cast (5-6s delayed)

**How it should work:**
- In p1 the spikes should land every 20-21seconds (supposedly the cd should only trigger when the cast is finished)
NOTE: the DBM timer is off. You can see this on the retail video I linked, the spikes are delayed compared to what DBM shows.
- During bone storm, there are always two set of spikes, landing every 12-13 seconds. This way they are properly divided over the storm's duration. In general the bone storm is longer (average 30s) than normal mode.
- When bone storm ends, the cooldown is reset back to the 18s of p1, and you can't get a set of spikes right after the storm has ended (the timer starts over)
- There is never more than 2 bone spike casts between bone storms.
- Bone storm is never delayed by the spike cast coinciding. If they'd coincide, Bone storm is cast as priority, and because of the change in timer, the spikes won't follow for another 9-10s.

Timer sample from retail 3.3.5:
Where t=0 is the pull
t=18 spikes begin to cast
t=21 spikes land
t=39 spikes begin to cast
t=42 spikes land
t=47 bone storm begins to cast
(heroic-only:)
t=50 bone storm begins
t=59 spikes begin to cast
t=62 spikes land
t=72 spikes begin to cast
t=75 spikes land
t=82 Bone Storm Ends

t=100 spikes begin to cast
t=102 spikes land
t=118 spikes begin to cast
t=121 spikes land
t=137 bone storm begins to cast
t=140 bone storm begins

Note: there can be 1-1second differences due to lag and whatnot to the shown patterns.

2) It's possible for the main tank to get spiked
This seems to happen because there is often a very short window between the Bone Storm ending and Marrow casting Bone Spike and he either does not use Bone Slice at all in this time, or it misses/dodges/parries, so the tank does not get hit by it.
**How it works atm:** Only being hit by bone slice seems to provide immunity to being Spiked, having 1# threat does not.
**How it should work:** Having 1# aggro should protect you from being spiked, as well as having recently been hit by Bone Slice.

3) The spike's damage cannot be blocked by HoP

**How it should work**: You can see on the video I linked that it is possible to negate the damage of the spike by using a bubble (Hand of Protection) on the spiked person. This is essential to save people if Marrow charges on top of them while they are spiked.
This does not free the person from the spike, but makes him immune to the physical damage it deals for the duration.
**How it works here:** using immunities on the spiked person does not do anything, the spike's damage goes through everything.

4) Impaled person falling in texture if the spike kills him and the spikes don't despawn upon wipes.
**How it works:**
If you fail to free someone from the spike, his corpse falls under texture 50% of the time, making it impossible to battle rezz, or rezz upon a wipe.
These people then spawn upon release in The Barrens either dead or alive, often needing to take rez sickness.
When you wipe, the spikes remain where they are and never go away.

**How it should work:**
- If the spike kills somebody, his corpse needs to be dropped in ICC in marrowgar's room and the spike must disappear.
- If the raid wipes, all spikes should disappear, and should drop their impaled persons corpses in ICC in marrowgar's room, not under texture.

**Comment by Dranah** [comment]
Bone Spike times are corrected.
Bone Storm is way too short still (20-24s) instead of like 30s, marrow has no time to charge a 4th time and to cast the second spike.
Bone spikes still don't despawn when a player dies, or when the fight ends.

**Comment by Keader** [comment]
Duration of Bone storm: 10 man = 20 sec, 25 man = 30 sec
(with all timers added 3050 ms)
So, looks correct to me.

Fixed (again) spikes not vanishing.

**Comment by Dranah** [comment]
Wait no, there is meant to be no difference between 10 and 25m in bone storm timer. Both should last 20seconds. The difference is between normal and heroic.
So on both 10hc and 25hc, the Bone Storm is extended to roughly 30sec to fit in the two spike casts and the extra charge.

**Comment by Dranah** [comment]
**How it should work:**
Bone Storm should last ~20seconds on 10normal and 25normal.
If t=0 is when bone storm begins, Marrow charges at t=1, t=6, t=11 and t=16.
(4 charge total)
Bone Storm should last ~30seconds on 10hc and 25hc.
If t=0 is when Bone Storm begins, Marrow charges at t=1, t =6, (spike between), t=13, t=19, (spike between), t=26
(5 charge total)
**How it works atm:** After the last fix attempt, the 25normal storm has been elongated to 30seconds, Marrow charge only every 10sec for a total of 3 times instead 4.
On 10hc he charges only 3 times instead of 5 and only casts 1 spike during storm because it lasts only 20s.
On 25hc, he charges 4 times instead of 5 even with the elongated 30s timer.

**Comment by Dranah** [comment]
Durations are fine now, but Marrow still only charges 3 times ._.
Needs to be 4 charges on normal and 5 on heroic.

**Comment by jarvik76** [comment]
While the bonespikers are despwaning visually, the effect is not being removed from the player.
i.e. this comment from Dranah has regressed:
EDIT: I forgot, the spikes properly despawn now when marrow dies or if his target dies.
But the stun debuff stays and the person needs to leave the raid to remove it.
The "impaled" debuff should vanish together with the spike, spell ID 69065

**Comment by Dranah** [comment]
UPDATE:
Timers are correct now and Marrowgar charges the correct amount of times.
Remaining issue is the bone spike debuff "Impaled" not vanishing properly when the fight ends and spikes disappear. ID 69065

**Comment by Dranah** [comment]
Timers corrected. Spike debuff is now properly removed if the raid wipes or if Marrowgar dies and also if the spike finishes off his target.
However it still remains on target if the target dies to another source of damage (i.eg. bone storm) while being spiked.

**Comment by Dranah** [comment]
Spikes timer during storm fixed.
Debuff is now always properly removed.
