### ISSUE TITLE
[Dungeon] - Pit of Saron pre-gauntlet - 658

### ISSUE THREAD

**Issue by jarvik76** [WoWManiaUK/Redemption#3689]
**Links:**
https://www.wow-mania.com/armory/?npc=36841
https://www.wow-mania.com/armory/?npc=36842

In the pre-gauntlet ramp in Pit of Saron HC:

1. There is only one pack of Fallen Warrior 36841 & Wrathbone Caster 36842
2. That pack is in the wrong place, leading to it being skippable
3. The pack make-up is incorrect

|
1. 
**What is Happening:**
There is a single pack of mobs at the top end of the ramp
**What Should happen:**
There should be an additional pack located at the lower end of the ramp
https://youtu.be/ZLLmVdxM9WM?t=444

2. 
**What is Happening:**
The upper pack is located too far up the ramp, leading to it being possible to skip entirely by using the rock ledge to the left
**What Should happen:**
The pack should be located further down in line with the rock ledge.  See screenshot from retail video:
![WoWScrnShot_100619_142738a - retail](https://user-images.githubusercontent.com/46089380/69008589-f967a700-0943-11ea-8a41-5565b776bbdd.png)

3.
**What is Happening:**
The pack consists of 3 Warriors and two Casters, with the casters in front
**What Should happen:**
There should be 4 warriors in front, with 2 casters behind
https://youtu.be/ZLLmVdxM9WM?t=513

![WoWScrnShot_111719_135900](https://user-images.githubusercontent.com/46089380/69008625-71ce6800-0944-11ea-87ea-d3321a223f45.jpg)

On normal mode I have not yet been able to 100% verify how the packs should be made up, but the positioning of the upper pack is incorrect.

**Comment by Rushor** [comment]
i have a fix for that - i could add it

**Comment by wow-mania** [comment]
Go for it.

**Comment by Rushor** [comment]
all fixed https://youtu.be/6r8d5KlLxrI

**Comment by jarvik76** [comment]
Looks good! Thanks.
