### ISSUE TITLE
Wintergrasp Siege teleporter

### ISSUE THREAD

**Issue by Brazier1** [WoWManiaUK/Redemption#3692]
**Links:**

**What is Happening:**Horde attacking, Allies defending. Horde had Sunken Ring in their control. Allies all the rest. Afther I build a siege vehicle at Fortress Vehicle Workshop (E), my intension was to teleport with the siege outside the Fort (SE) in order to defend against incoming vehicles from SR. The teleporter didn't work as it should be; The siege with me included got teleported back to the workshop i came from. For some person the teleporter worked as it should be, for some it didn't.
For who it did not had to drive their vehicle from Fortress Vehicle Workshop (W) to the East side, wich is a disadvantage when you're defending. I Asume those certain horde players are aware of this and used it as an advantage.

**What Should happen:**
The siege should teleport outside the fort.

**Comment by wow-mania** [comment]
Can anyone confirm this on dev, please. 
Sound more like the wrong location to me.
