### ISSUE TITLE
[Quest] Into The Pit 12997 / Back to the Pit 13424 - Stormpeaks

### ISSUE THREAD

**Issue by jarvik76** [WoWManiaUK/Redemption#3693]
**Links:**
Into the Pit: https://www.wowhead.com/quest=12997/into-the-pit
Back to the pit (daily)  https://www.wowhead.com/quest=13424/back-to-the-pit
Provided mount: https://www.wow-mania.com/armory/?npc=29918
mount "Maul" skill: https://www.wow-mania.com/armory/?spell=54459

**What is Happening:**
The provided mount's "Maul" skill (spell 54459) does not have the knockback effect.  This means the 3rd "charge" skill is unusable.

**What Should happen:**
Target enemy should be knocked back with successful use of the Maul skill.  See retail video:
https://youtu.be/CJ28xVAeh6M?t=23

**Comment by Rushor** [comment]
knockback fixed now! https://i.imgur.com/9LFav3T.jpg
