### ISSUE TITLE
[NPC] Hyldsmeet Warbear - 30174 - Stormpeaks

### ISSUE THREAD

**Issue by jarvik76** [WoWManiaUK/Redemption#3694]
**Links:**
NPC - Hyldsmeet Warbear :  https://www.wowhead.com/npc=30174/hyldsmeet-warbear
(only becomes hostile during the following quests)
into the pit https://www.wowhead.com/quest=12997/into-the-pit
back to the pit  https://www.wowhead.com/quest=13424/back-to-the-pit

**What is Happening:**
The Hyldsmeet Warbear, is set to agressive rather than defensive behaviour

**What Should happen:**
The Hyldsmeet Warbear, while appearing hostile, should not be agressive - should be defensive and only attack when hit by the player.
This is critical as during the quest, currentlyif the target is knocked back using the mount Maul skill, all of the bears in the pit area will be pulled and quest will be failed.
This behaviour can be witnessed in retail video:
https://youtu.be/CJ28xVAeh6M?t=23

**Comment by Rushor** [comment]
they are defensive now. also removed some duplicate spawns and reduced respawntimer + added some abilities. https://i.imgur.com/QGe8KAK.jpg
https://i.imgur.com/8vjgTQS.jpg and defensive now
