### ISSUE TITLE
[Quest] They Call Him Smilling Jim 27251 - Dustwallow Marsh

### ISSUE THREAD

**Issue by NestLucky** [WoWManiaUK/Redemption#3695]
**Links:**
https://www.wowhead.com/quest=27251/they-call-him-smiling-jim
https://www.wow-mania.com/armory/?quest=1282
**What is Happening:**
The Guard Byron dont give me the quest after complete the previous quest James Hyal

**What Should happen:**
After complete the quest James Hyal, the quest in question have to be available. See Classic Video (is the only i can get):
https://www.youtube.com/watch?v=dZfNwSIRTnk

**Comment by Rushor** [comment]
you have quest 1301 and 1302 done already?

**Comment by NestLucky** [comment]
Yes

**Comment by wow-mania** [comment]
If cannot be reproduced just close it please.

**Comment by NestLucky** [comment]
So, the problem of this quest dont be solved?

**Comment by Rushor** [comment]
wil check it

**Comment by Rushor** [comment]
the mechanic was changed. on current reatil you can do the chain like that. but back in wotlk/tbc/classic those quests killed each other.

see here:
https://www.wowhead.com/quest=1282/deprecated-they-call-him-smiling-jim


By GreyGore (739 –  2·5)  on 2007/06/05 (Patch 2.1.1) |   |  
You can't do this quest after turning in the last step of James Hyal (they're both just an excuse to get you to talk to Captain Vimes).

https://www.wowhead.com/quest=1282/deprecated-they-call-him-smiling-jim#comments:id=98307

So this is invalid
