### ISSUE TITLE
 [A Mangled Journal]

### ISSUE THREAD

**Issue by Anticreator** [WoWManiaUK/Redemption#3696]
**Links:**
https://wotlk.evowow.com/?item=11116

**What is Happening:**
after player have complete this item quest. Item still droping, But is unable for take. After this beasts are imposible to skinning. (for me 75%)

**What Should happen:**

 [A Mangled Journal] is non-dropable for character, who have already completed this quest.

**Comment by Rushor** [comment]
i cannot confirm this on dev. drop chance is 60 percent. once i rewarded the quest, i do not see the item anymore and i can skinn then

**Comment by Anticreator** [comment]
![WoWScrnShot_111919_001359](https://user-images.githubusercontent.com/57919453/69102029-8ce2ca00-0a61-11ea-9115-49ab86ab5707.jpg)

**Comment by Anticreator** [comment]
I cannot confirm this decision. I am not only one person who have this problem, but I believe we will find the right solution to this problem.
