### ISSUE TITLE
[Quest] Dangerous! - 567 - Hillsbrad Foothills

### ISSUE THREAD

**Issue by jarvik76** [WoWManiaUK/Redemption#3697]
**Links:**
https://www.wow-mania.com/armory/?quest=567

**What is Happening:**
The "poster" object that starts the quest is partially underneath the texture of the inn building, meaning it is difficult to see and is easily missed unless one happens to hover over the part that is visible.

![WoWScrnShot_111919_014504](https://user-images.githubusercontent.com/46089380/69109216-f6b5a080-0a6e-11ea-8577-36c654bb8bec.jpg)

**What Should happen:**
Poster object should be on top of the inn texture, so that it is visible in its entirety.

**Comment by wow-mania** [comment]
Applied on live but will need restart.
