### ISSUE TITLE
[Mount] Kodo mount model collision box too big

### ISSUE THREAD

**Issue by jarvik76** [WoWManiaUK/Redemption#3698]
**Links:**
https://www.wow-mania.com/armory/?search=kodo#mounts

**What is Happening:**
Suspect the collision model for the kodo mount (all) is set to be too wide or tall compared to the actual texture.
e.g. in Dalaran sewers, the Kodo model cannot enter if it is even slightly off center of the tunnel, yet other taller and wider mounts such as Elekks and Rhinos have no problem  (although naturally the Mammoth correctly does not fit!). 

This is perhaps best demonstrated in this video I made here:
https://youtu.be/MeEDSocdB4A

This potentially affects all of the kodo mounts as seen in this list, I believe they all use the same core model:
https://www.wow-mania.com/armory/?search=kodo#mounts

**What Should happen:**
Kodo model should be able to enter Dalaran sewers, as it is smaller in stature than some other mounts.

**Comment by wow-mania** [comment]
As-is. The video clearly shows you can pass if you pick the correct spot.
I will not change this is it is the default and changing it may have side-effects on other places.
