### ISSUE TITLE
Dungeon Finder Locks

### ISSUE THREAD

**Issue by Kitzunu** [WoWManiaUK/Redemption#3701]
**How it works:** Currently if you get locked to every dungeon in the Dungeon Finder you will not be able to queue again until the instance reset the day after.

**How it should work:** After you have gotten a lock to every dungeon with LFG it should reset making it possible to queue again.

**Comment by jarvik76** [comment]
Is that really true?  I have this memory of the full lockout being the blizzlike behaviour.   Have you got the reference documentation?  Would love to read that to refresh my memory.

**Comment by Kitzunu** [comment]
I am quite sure, this source from 2009 says:

https://www.engadget.com/2009/12/08/patch-3-3-the-dungeon-finder-guide-page-2/?guccounter=1&guce_referrer=aHR0cHM6Ly93d3cuZ29vZ2xlLmNvbS8&guce_referrer_sig=AQAAANqwmzXi33Q2wxTfxsxhYCQkQDu5w230CNhlt1XMLhYwodxs4qIFtbtrpET56REP4Mlbfxan6pTkQSSXFVVsiRgYti2RLU9YJVfXrLDT9Fs98QsiHQuy-hicJdQVyKj7YJRGjgubJL05jnAivNsCTpOHUv-mBV6Cm6LLcab3ettz
>The randomness of the random dungeon dailies aren't completely random. While the text does specify the dailies as random, they're not really. The system tries to make sure you aren't running the same dungeon over and over again. With random mode on, it will allow you to bypass your normal heroic lockouts. This means if the dice gods are against you, that random dungeon could be one you really don't like. However, the system tries really hard not to do that.

>If you're choosing specific dungeons through the interface, it will still take your heroic lockouts into account, so you can't just choose to run new Icecrown heroics over and over again. 

Which is not similar to what I reported, but it shows that in some way this system should not completely lock you out

**Comment by Rushor** [comment]
https://github.com/TrinityCore/TrinityCore/issues/14705

**Comment by jarvik76** [comment]
This doesn't mean the locks reset, it just means the LFG tool continues to work.  This is different to releasing locks as that would allow you to queue for specific dungeons.
But yes, if it does not allow **random** queuing after all are locked, then that is not correct.

**Comment by Kitzunu** [comment]
nono I think you got me wrong :P

I didnt mean to release the lock, just to let LFG continue to work
atm it doesnt

**Comment by jarvik76** [comment]
yup, all clear :)

**Comment by Keader** [comment]
Not possible change something in LFG  for now.
