### ISSUE TITLE
Guild Control

### ISSUE THREAD

**Issue by Kitzunu** [WoWManiaUK/Redemption#3702]
**How it works:**
If you edit rank 1 and proceed to rank 2 (without pressing accept) the edits of rank 1 will not be saved.

**How it should work:**
If you edit rank 1 and then proceed to rank 2 the edits of rank 1 should not be removed even if you did not click accept before.

**Comment by Keader** [comment]
WTF?
Not even possible.
Server only get the packet with info, when you click in Accept button.
So is impossible to server save it, before click happens.
