### ISSUE TITLE
[Boss] Sindragosa ground movement speed

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#3703]
https://www.wowhead.com/npc=36853/sindragosa

**How it works atm:** Sindy moves on like 500% movement speed, extremely fast when in ground phases. This causes issues with positioning on the pull and also if someone overaggros, she charges onto the ranged on the stairs in a blink of time.
**How it should work:** Sindy should have same ground movement speed as other bosses, only slightly faster than a player so that she cannot be kited.

Note: this problem only affects her GROUND speed, her fly speed is just fine!

**Comment by jarvik76** [comment]
I have tonight noticed that some random mobs have this "fast move" ability too, such as basilisks and scorpids in 1k Needles, perhaps this is related?

**Comment by shadownib** [comment]
Hi Dranah i just wanna added " Her fly speed is not fine " if it was fine u wasn't going to make the boss standing 3 second doing nothing , just to fit the tombs announcement timing :d cmon its so obvious :)

**Comment by Dranah** [comment]
Her flight speed generally is fine. Her flight route is incorrect, which was worked around by giving her a pause, because nobody will rewrite her entire pathing. It's unnecessary to touch something that already works essentially fine.
The reason I emphasize the report is about the GROUND speed, is so that the devs don't change the flight speed by accident. The two are set and handled differently based on my past experience and I don't want 3 fix attempts fucking up her fly speed without changing the ground one.

**Comment by Keader** [comment]
Invalid.

Run Speed of a creature is: Sniffed Value / 7

> [11] GUID: Full: 0xF1308FF5000234EA Type: Creature Entry: 36853 (Sindragosa) Low: 144618
> [11] Object Type: 3 (Unit)
> [11] Has bit654: False
> [11] Has GameObject Rotation: False
> [11] Has Attacking Target: False
> [11] Has bit520: False
> [11] Transport: False
> [11] Has GameObject Position: False
> [11] Has bit784: False
> [11] Self: False
> [11] Living: True
> [11] Has bit644: False
> [11] Has Stationary Position: False
> [11] Has Vehicle Data: False
> [11] Has AnimKits: False
> [11] Has Fall Data: False
> [11] Lacks Timestamp: True
> [11] Lacks Pitch: True
> [11] Has Transport Data: False
> [11] Has Spline Data: False
> [11] Movement Flags: 512 (OnTransport)
> [11] FlyBack Speed: 4.5
> [11] Swim Speed: 4.72222
> [11] Turn Speed: 3.141593
> [11] Run Back Speed: 2.5
> [11] Walk Speed: 12
> [11] Unk UInt32: 3231640548
> [11] Pitch Speed: 3.141593
> [11] **Run Speed: 30**

30/7 = 4.28571

Value in DB:

![image](https://user-images.githubusercontent.com/7120913/69386267-dd943600-0ca0-11ea-8c09-7232833f0e80.png)

**Comment by Dranah** [comment]
My estimation was only 72% off hahahaha. Anyway, I stand corrected, I double checked and she does indeed move faster than other bosses. The difference in hitbox is likely to cause it feels much faster than intended, her mobility is just smoother on retail.
