### ISSUE TITLE
[Raid] Serpentshrine Cavern Bridge

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#3704]
**Links:**https://www.wowhead.com/serpentshrine-cavern
[Issue #2624](https://github.com/TrinityCore/TrinityCore/issues/2624)

**What is Happening:** The bridge leading to Lady Vashj, the last boss in the TBC [Raid Serpentshrine Cavern](https://www.wowhead.com/serpentshrine-cavern) has no texture whatsoever. It works just fine and can be walked on, but it is completely invisible and can easily confuse players that aren't aware of that.

**What Should happen:** The bridge should be visible once spawned. Also, according to [Issue #2624](https://github.com/TrinityCore/TrinityCore/issues/2624), the behavior of how it appears is wrong. The invisible bridge is constantly present, whereas usually it should appear and be visible only after the console has been clicked (which needs some bosses to be defeated to become active).

**Comment by Rushor** [comment]
That is a nice one to fix

**Comment by Rushor** [comment]
fixed that one  https://i.imgur.com/nLcbBdn.jpg https://i.imgur.com/lQG15Yo.jpg https://i.imgur.com/LDl5Xyd.jpg

**Comment by Oganku** [comment]
Looks great. Awesome work :)
