### ISSUE TITLE
Sindragosa : issue with Instability or specific spells issue , boss fly movement speed , boss reset 

### ISSUE THREAD

**Issue by shadownib** [WoWManiaUK/Redemption#3705]
**Links:**about link with evidence i prefer Not linking bcuz nobody back then retail did even record while he is casting with unchain magic , not gonna spent 1 month of research forums while im not even tester + the ppl seems to Not give shit about anything , anymore " bcuz the game is too old" lets say :d

**What is Happening:**I'll just mention all the issue here :1. Dispersion is refreshing the instability stacks for next 5 sec ( ty god dispersion is a 6 sec duration )  2. Divine hymn is giving us like 6 ~ 7 stacks of instability ( ty for fixing penance nitro boots instability issue ) 3. traveling spells still gives Instability on HIT it means 2x stacks for 1 shadow bolt cast ( lets hope u can successfully move the Core Spell Proc System from your Cata server ) 4. boss Flying speed movement is FAST than it should be ( i know how many things it will BROKE like a " DOMINO" but its just obvious that have to get any improvements )

**What Should happen:**1 Using Dispersion should Not give at all stack of instability ( issue example , you are spriest , you have 20 stacks of instability , you are watching ur stacks time like : 5, 4 ,3 ,2 ,1 and at "1" u are using your dispersion until it soak the dmg and 1 sec later u use the cancel aura macro for your dispersion, that can help you do more dps and not only that , another example is how u can manage to explode out of the raid while u have the ice tomb in last phase for like 5 sec time ( with nitro boots )     2. Divine hymn should give only 1 stack of instability. ( same a penance was , now penance gives 1 stack only ) obvious things can start working at least 2020 <3

**Comment by shadownib** [comment]
ah i forgot about  " Boss Reset "  i meant : example : if u are the only alive person in the raid and u are in ice tomb , as boss land on the ground it will just get Reset and the tomb will free you out , without Dying. ( thats how its suppose to be )

**Comment by wow-mania** [comment]
I am starting to get pissed with your comments and the way you are acting. Stop trying to stir shit.
