### ISSUE TITLE
Reporting a Basic issue but as same it is for every boss ( based on same thing )

### ISSUE THREAD

**Issue by shadownib** [WoWManiaUK/Redemption#3706]
**Links:**

**What is Happening:** Every single boss i mean : 1. bone spikes are staying alive after boss die ( if we killed the boss before them , so we have to kill them or the guy will stay there forever or just die if we are not healing him ) 2. Lady adds same , they will stay alive if we killed the boss and they are still alive ( they should disappear )3. gunship cannons are not working properly ( thats out of the topic anyway ) 4. Deathbringer Saurfang : Blood Beasts are the same ( we have to kill them even if the boss is dead already ) 5. Rotface is the same , with the Oozes they will stay alive and we have to finish them( if there is any oozes while we are killing the boss ) funny thing is : i hear one raid leader said : " lets make the explosion so we don't have to kill oozes" P.S. how ppl adapt to something instead of reporting it :( ( not even usable for something good ) About PP  oozes im not sure ( i think those issue can be the reason " why we cannot reset sindragosa " , she may is getting reset , but the tomb is not going out until u didn't die inside , which i'm only guessing about that , rest of the thing i saw with my eyes. ) those things can fix others or bug others GL :Dx
 

**What Should happen:**
As " Basic" means " everyone should know what it should happen " <3

**Comment by wow-mania** [comment]
As-is

**Comment by Dranah** [comment]
This is only true for the spikes. On all the other bosses you listed, the adds properly despawn when fight ends. The spikes have been reported separately.
