### ISSUE TITLE
Lady Deathwhisper Spirits Not triggering in the right way

### ISSUE THREAD

**Issue by shadownib** [WoWManiaUK/Redemption#3707]
**Links:**

**What is Happening:** they are not targeting the closer person for sure

**What Should happen:** They should target the closer target ( ALWAYS ) and there must have at least 1 ~ 2 sec for that basically ( if spirit spawned just on my spot 1 yard next to me and i just use nitro boots and move and jump in same time it means able to get 10 ~ 15 yards away from it for 1 ~ 2 sec , so while that the spirit will target the target who is the closer one that's it , just mention that when the spirit is spawning he doesn't know yet where to go :)                                                          
   P.S. I hope you get my Bulgarian explanation , be cool so i can be your guest ! <3

**Comment by wow-mania** [comment]
As-is
