### ISSUE TITLE
[NPC/Spell] Mutated Abomination - Mutated Slash

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#3708]
https://www.wowhead.com/spell=70542/mutated-slash
cast by https://www.wowhead.com/npc=37672/mutated-abomination

**How it works atm:**
The abomination's spammable ability (mutated slash) is doing less than half the intended damage, only about 2,5k-3k on any difficulty.
The abomination's melee auto attack is missing entirely.
The abomination cannot crit.

**How it should work:**
- The damage of mutated slash should scale with difficulty, from 5-6k damage per hit on 10nm, 7-8k on 10hc, 9-10k on 25nm up to 11-12k on 25hc.
- The abomination should auto attack for roughly the same 100% weapon damage on each difficulty, swinging every 2seconds.
- Both the melee auto attacks and the mutated slash should be able to crit, roughly 5% chance like a regular NPC as it appears on the logs.

sources:
http://www.worldoflogs.com/reports/rt-inufofzjkhog0uoz/details/123/?s=8325&e=8584 10nm
http://www.worldoflogs.com/reports/jsks30wp00wb0byw/details/135/?s=5025&e=5303 10nm
http://www.worldoflogs.com/reports/mmo52j0s7w83yybc/details/129/?s=4136&e=4419 10hc
http://www.worldoflogs.com/reports/rt-hv22aw4l1z1bobko/details/54/?s=990&e=1329 25nm
http://www.worldoflogs.com/reports/pt6hgjymsmjqt24s/details/181/?s=3049&e=3374 25hc

**Comment by Rushor** [comment]
i think vehicles cannot autoattack

class spell_mutated_slash : public SpellScriptLoader
{
    public:
        spell_mutated_slash() : SpellScriptLoader("spell_mutated_slash") { }

        class spell_mutated_slash_SpellScript : public SpellScript
        {
            PrepareSpellScript(spell_mutated_slash_SpellScript);

            void CalculateDamage(SpellEffIndex /*effIndex*/)
            {
                Unit* target = GetExplTargetUnit();
                uint32 damage = 0;
                switch (target->GetMap()->GetDifficulty())
                {
                    case RAID_DIFFICULTY_10MAN_NORMAL:
                        damage = 12500;
                        break;
                    case RAID_DIFFICULTY_25MAN_NORMAL:
                        damage = 16500;
                        break;
                    case RAID_DIFFICULTY_10MAN_HEROIC:
                        damage = 14400;
                        break;
                    case RAID_DIFFICULTY_25MAN_HEROIC:
                        damage = 21500;
                        break;
                }
                SetHitDamage(damage);
            }

            void Register()
            {
                OnEffectHitTarget += SpellEffectFn(spell_mutated_slash_SpellScript::CalculateDamage, EFFECT_0, SPELL_EFFECT_WEAPON_PERCENT_DAMAGE);
            }
        };

        SpellScript* GetSpellScript() const
        {
            return new spell_mutated_slash_SpellScript();
        }
};

DELETE FROM `spell_script_names` WHERE `spell_id`=70542;
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES 
(70542, 'spell_mutated_slash');

**Comment by Dranah** [comment]
Sure they can't on mania, but you can see on logs and videos that on retail the abom does auto attack. Question is if it's possible to fix.

**Comment by Rushor** [comment]
that's what i'm asking me for years haha. would be awesome if we could that get fixed <3

**Comment by Keader** [comment]
Is like Rushor said...
Vehicles cannot do melee attacks.
I realy dont know how fix it for now... i will put in hold on and try find where it is blocked.

**Comment by Dranah** [comment]
Can you at least fix the damage and ability to crit on Mutated slash?

**Comment by Keader** [comment]
I dont find anything that prevent spell to crit

**Comment by Dranah** [comment]
Ok i'll go by difficulty:
1) 10man normal:
Mutated Slash damage is too high after fix (7k+) approx 20% reduction needed. (need fix)
Melee auto attacks still missing. (need fix)
2) 25man normal:
Mutated Slash damage matches retail. (fixed)
Auto attacks work now, but only swing for 2k instead of same 9-10k as Mutated. (need fix)
3) 10man heroic:
Mutated Slash damage slightly overtuned (8-9k), approx 10% reduction needed. (need fix)
Auto attacks missing still. (need fix)
4) 25man heroic:
Mutated Slash damage slightly overtuned (12-13k), approx 10% reduction needed. (need fix)
Melee auto attacks work now, but only swing for 2k instead of same as mutated. (need fix)

Great improvement though!

**Comment by Keader** [comment]
Auto attack damage amount belongs to other issue.
And i need you to adapt it :)

**Comment by Dranah** [comment]
Mutated Slash damage values fixed except for 10normal which is still a bit overtuned. Need to reduce 10% more.
Auto attack goes in separate report.

**Comment by Dranah** [comment]
All difficulties damage corrected to match retail logs.
