### ISSUE TITLE
Creature: Saurfang the Younger - Add movie after quest 'Return To Angrathar' is finished

### ISSUE THREAD

**Issue by Rushor** [WoWManiaUK/Redemption#3713]
http://cata.cavernoftime.com/?search=Return+To+Angrathar

movie at the end for horde is missing.

**Comment by Rushor** [comment]
all added

![I](https://i.imgur.com/vfY5OyR.jpg)
![I](https://i.imgur.com/dWoFSJs.jpg)
![I](https://i.imgur.com/2Q7Lh8U.jpg)

**Comment by Kitzunu** [comment]
cool!

**Comment by jarvik76** [comment]
Ooooooh, excellent!  Thanks Rushor :)
