### ISSUE TITLE
[Quest] Steamtank Surprise

### ISSUE THREAD

**Issue by Kitzunu** [WoWManiaUK/Redemption#3719]
**How it works now:**
Quest works, however, the quest credit distance for destroying the Plague Wagons is way too small.
If you only stand a few yards away you won't get the quest credit as shown in the image below.
It does work if you stand right ontop of it.

![image](https://user-images.githubusercontent.com/24550914/69431193-88efca00-0d37-11ea-8b40-d222346c4662.png)

**How it should work:**
You should be able to be further apart from the Plague Wagon and still get the quest credit.

Spell for quest credit: 49122

**Comment by Rushor** [comment]
currently it's 30 yards range. will increas to 500 yards that should be enough.

**Comment by Rushor** [comment]
fixed

![I](https://i.imgur.com/HFZ1fCo.jpg)
