### ISSUE TITLE
[Quest] The Chain Gun And You

### ISSUE THREAD

**Issue by Kitzunu** [WoWManiaUK/Redemption#3720]
https://www.youtube.com/watch?time_continue=58&v=JxdWf1O9k0o&feature=emb_logo
Q ID = 12457

**How it works:**
Currently, the ghouls are not respawning quickly enough.

After the Soldier has been rescued it runs back down again.

In other words, badly scripted.

![image](https://user-images.githubusercontent.com/24550914/69432564-3a8ffa80-0d3a-11ea-99e2-477077ced303.png)

**How it should work:**
The ghouls should respawn at a fairly fast pace 

The solider is meant to despawn after it has said it's text

**Comment by Kitzunu** [comment]
Pathing for Injured 7th Legion Soldier is also very wonky.

**Comment by Kitzunu** [comment]
related to the quest https://github.com/WoWManiaUK/Redemption/issues/3721

**Comment by Rushor** [comment]
despawn at the end added and the ghouls respawn faster now

![I](https://i.imgur.com/7kAfseL.png)
![I](https://i.imgur.com/oEja4Pn.jpg)
