### ISSUE TITLE
[Spell] Call Out Injured Soldier

### ISSUE THREAD

**Issue by Kitzunu** [WoWManiaUK/Redemption#3721]
**How it should work:**
When you use the spell Call Out Injured Soldier (49550) the caster (player) should say "Soldier, run to me! I'll clear a path with the chain gun!" in Type: 12  (Say)

**Comment by Rushor** [comment]
two texts actually either 

Come out, soldier! I'll cover you!
--


or 


Soldier, run to me! I'll clear a path with the chain gun!
--

**Comment by Rushor** [comment]
will fix that because it is quest related

**Comment by Rushor** [comment]
done 
![I](https://i.imgur.com/Cy0a9DX.png)
