### ISSUE TITLE
Matis the Cruel not responding to attacks (bug confirmed by GM)

### ISSUE THREAD

**Issue by JustinG47** [WoWManiaUK/Redemption#3724]
**Links:**
https://www.wowhead.com/quest=9711/matis-the-cruel

**What is Happening:**
When you try to kill Matis the Cruel, he gets off his horse, yet doesn't move or attacks.
You can kill him with ease.
He also moves weirdly around one small location, he doesn't follow his path. 

**What Should happen:**
Fix movement and attacks.

**Comment by wow-mania** [comment]
Pretty sure it works. What level was your character?

**Comment by JustinG47** [comment]
I was level 18. It happened yesterday. I reported it to a GM and he confirmed that this dude doesn't attack.

**Comment by JustinG47** [comment]
The GM didn't confirm the Blood Elve's weird movement, although I didn't mention it when I opened a ticket.
