### ISSUE TITLE
[Quest] Call to Arms: (Horde)

### ISSUE THREAD

**Issue by pitstem** [WoWManiaUK/Redemption#3725]
**Links:**
https://www.wowhead.com/quest=11340/call-to-arms-alterac-valley
https://classic.wowhead.com/npc=15350/horde-warbringer
**What is Happening:**
After a battleground is won, there is a daily PvP quest(linked) for that battleground that auto accepts and auto completes. It requires the player to visit his faction's warbringer(liked) at any of his faction major cities, Shattrath, Wintergrasp or Dalaran. However, when I(Horde) receive said quest, there is no option for me to turn it in at any of my faction's warbringers(screenshot provided). Strangely, there is an option to return it to an Alliance warbringer located in Shattrath(screenshot provided), but since he's Alliance and I'm Horde there is no way to talk to him in order to return the quest.
**What Should happen:**
I should be able to turn in my daily PvP battleground quest at a warbringer of my faction.
![WoWScrnShot_112219_213137](https://user-images.githubusercontent.com/58089094/69456749-19e49680-0d74-11ea-960f-0a4ec48491df.jpg)
![WoWScrnShot_112219_213016](https://user-images.githubusercontent.com/58089094/69456775-2c5ed000-0d74-11ea-9e39-5abdac28e904.jpg)

**Comment by Oganku** [comment]
Linked to #3351 I suppose. This bug used to be true for all call to arms.

**Comment by Kitzunu** [comment]
I am making this a more generic report.

I have added all Call to Arms: Horde quests to the NPC's now.

Somehow they all had been added for Ally npc :P

**Comment by jarvik76** [comment]
- [ ] (15350, 11339),
- [ ] (15350, 24216),
- [ ] (15350, 24217),
- [ ] (15350, 24221),
- [ ] (15350, 24225),
- [ ] (15350, 24226),
- [ ] (15350, 24426),
- [ ] (15350, 13407),
- [ ] (15350, 11340),
- [ ] (15350, 11341),
- [ ] (15350, 11342),
- [ ] (15350, 14164),
- [ ] (15350, 13428),
- [ ] (15350, 14181),
- [ ] (15350, 14182),
- [ ] (15350, 14183),

**Comment by jarvik76** [comment]
non-found quests are deprecated versions.  non-deprecated versions works
