### ISSUE TITLE
[Quest] Call to Arms: (Alliance)

### ISSUE THREAD

**Issue by Kitzunu** [WoWManiaUK/Redemption#3726]
I have added all the missing Call to Arms: quests to the quest ender NPC's

Many was missing but should all be good now.

Also added AllowableRaces to be alliance for all ally quests

**Comment by jarvik76** [comment]
Alliance: 

- [ ] (15351, 13427),
- [ ] (15351, 11335),
- [ ] (15351, 11336),
- [ ] (15351, 11337),
- [ ] (15351, 11338),
- [ ] (15351, 13405),
- [ ] (15351, 14163),
- [ ] (15351, 24218),
- [ ] (15351, 24220),
- [ ] (15351, 14178),
- [ ] (15351, 24219),
- [ ] (15351, 14179),
- [ ] (15351, 14180),
- [ ] (15351, 24223),
- [ ] (15351, 24224),
- [ ] (15351, 24427),
- [ ]

**Comment by jarvik76** [comment]
non-found quests are deprecated versions.  non-deprecated work fine, can be turned in.
