### ISSUE TITLE
[Spell] Improved Charge increasing slam damage

### ISSUE THREAD

**Issue by Greywolf59** [WoWManiaUK/Redemption#3728]
**Links:**
Slam: https://www.wow-mania.com/armory/?spell=47475
Mortal Strike: https://www.wow-mania.com/armory/?spell=47486 (btw guys you have strange number there in healing reduced :D)
Improved Mortal Strike: https://www.wow-mania.com/armory/?spell=35449 (also some strange numbers)
Glyph of Mortal Strike: https://www.wow-mania.com/armory/?spell=58389

**What is Happening:**
Hello! On my arms warrior I was testing my dps rotations on boss level dummy in Ironforge.
What I noticed was that Slam hit harder then Mortal strike, both normal hit and crit in every situation. I watched my damage buffs, rechecked talents, I am using wow mania launcher.
Slam tooltip says  "...causing weapon damage plus 250"
Mortal Strike fully improved and glyphed says "...weapon damage plus 456"
I tried using mortal strike without glyphing it. Tooltip went to plus 418 and damage went even lower (so glyph is not an issue).
Slam hit harder at crits roughly about 1.5-2K then mortal strike and 1K on normal hits but it really varies as the spells are based on weapon damage. But never ever happened a situation that mortal strike hit harder then Slam, so either Slam is overpowered or Mortal Strike underpowered.

**What Should happen:**
Mortal Strike should do more damage then Slam.

**Comment by Greywolf59** [comment]
Update: Starweaver/Slania tried to test this himself and said that his mortal strike does more damage then slam even without the glyph. However he also said he talended only to get improved mortal strike and no further. This would suggest either personal bug or some talent he did not pick affects the mechanics, however no talent does says so nor does it even suggest a possibility of improving slam or diminishing mortal strike. I do not have more precise infkrmstion about his tests. Also I had a chance to watch my damage in icc 25 and it stayed the same, slam stronger then mortal strike.

**Comment by Dranah** [comment]
Ok can confirm the following issues:

1) Improved Charge talent ID 12697
is increasing slam damage by 29 damage per talent point.
This means on a naked char, the damage goes from 220 >> 279 by 2/2 talent taken.
It's a fixed value at higher gear levels too, but it scales with %dmg modifiers like certain buffs and also arpen and goes up to 100-150 damage difference at high end content.
My tests below have been done without this talent to rule out this factor.

2) Scaling of Mortal Strike
My numeric tests show that mortal strike scales stronger with the attack power based component of weapon damage. When using a trash weapon (2-4dmg grey sword), MS damage is way higher than calculated, especially at high levels of attack power (see test results below).
Meanwhile, when using a high damage weapon such as Glorenzelg, MS slightly underperforms at best, and slam starts scaling better. Slam appears to benefit slightly more from the weapon source of melee damage.

Here are my tests numbers - All of them have been done with no talents, no buffs, no procs and no arpen to confuse results:
1) Naked char (melee damage mostly comes from attack power)
Melee attack 72-73 damage
Mortal strike 306-307 damage (should be ~296 after armor reduction) - overscales
Slam avg dmg 218-219 (matches calculation)

2)Naked char with good weapon (melee damage mostly comes from weapon)
Melee attack dmg 672-928
Mortal strike dmg 881-1143 (calculation:895-1151) - underscales
Slam damage dmg 825-1080 (calculation: 819-1075) - overscales

3)Geared toon with good weapon (melee damage is shared from weapon and AP)
Melee attack dmg 1269-1531
Mortal strike dmg 1430-1693 (calculation:1492-1754) - underscales
Slam dmg 1415-1678 (matches calculations)

4)Geared toon with trash weapon (melee dmg mostly comes from attack power)
Melee attack dmg 543-545
Mortal Strike dmg 841-842 (calculation:766-767) - overscales
Slam dmg 690-691 (matches calculation)

Note:
'Weapon damage' has two components, the raw damage that your weapon adds, and the increase it gains from attack power. The two add up to form your "melee attack damage" after armor reduction on target.


**How it should work:**
Talent improved charge should not affect Slam damage.
Both mortal strike and slam should calculate off 100% total melee damage, not dipping a bit more into either the weapon or the attack power component of it.

**Comment by Greywolf59** [comment]
Thank you guys for investigating this. This sounds like delicate matter hard to repair tbh 😅. Funny as such small thing can scale into something so big on certain gear. And that charge talent ads to slam damage :D

**Comment by Keader** [comment]
Damage issue cant be fixed for now. Needs weapon rewrite of ariel...
but i fixed improved charge affecting slam damage
