### ISSUE TITLE
[Boss/NPC] Raging Spirits immunities

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#3730]
https://www.wowhead.com/npc=36701/raging-spirit

How it should work: Raging spirits should be immune to all form of CC, snare, silence and interrupt.
How it works atm: Raging spirits are susceptible to nearly all such effects, making their defeat trivial.

**Comment by Kitzunu** [comment]
I have added immune flags:

1 - MECHANIC_CHARM
2 - MECHANIC_DISORIENTED
16 - MECHANIC_FEAR
32 - MECHANIC_GRIP
64 - MECHANIC_ROOT
256 - MECHANIC_SILENCE
512 - MECHANIC_SLEEP
1024 - MECHANIC_SNARE
2048 - MECHANIC_STUN
4096 - MECHANIC_FREEZE
8192 - MECHANIC_KNOCKOUT
65536 - MECHANIC_POLYMORPH
524288 - MECHANIC_SHACKLE
8388608 - MECHANIC_HORROR
67108864 - MECHANIC_DAZE
536870912 - MECHANIC_SAPPED

for NPCs 36701, 39302, 39303, 39304

**Comment by crulinjr** [comment]
They still can be slowed right? Since frost traps were used to slow them down on retail

**Comment by Dranah** [comment]
the report is about the transition mobs which are immune to all form of CC including slows (this is clearly visible on videos)
the report does not affect the p3 spirits which can be kited
