### ISSUE TITLE
[Mechanic] Some Vehicles gaining raid auras and buffs

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#3731]
Problem: some vehicles i.eg. PP abom (earlier cannons on gunship too, but we fixed those separately) gain raid auras and buffs even though they aren't supposed to.

How it should work: Some vehicles like PP abom must not gain raid auras and buffs, but still be able to receive healing.

**Comment by Keader** [comment]
Please test tomorrow.
Build is broken, janitor will fix in some point.
