### ISSUE TITLE
[NPC] Ragnaros

### ISSUE THREAD

**Issue by Blyatman1** [WoWManiaUK/Redemption#3732]
**Links:**
https://wow-mania.com/armory/?npc=11502
https://wowwiki.fandom.com/wiki/Ragnaros_(tactics)

**What is Happening:**
When Ragnaros submerges, he is still able to be killed with DoT effects. If he dies while submerged, he cannot be looted.

**What Should happen:**
He should be immune to damage while submerged.
> This fight alternates between two stages - in the first, Ragnaros is up and everybody concentrates on DPSing him, in the second Ragnaros is immune to DPS, and the raid has to deal with his sons instead.

**Comment by Rushor** [comment]
All auras will be removed upon submerger now, so dot effects should not kill him.
