### ISSUE TITLE
[Loot/Drop] ICC trash BoE drop rates

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#3733]
The following items have an extravagantly increased drop rate on all difficulties:

https://www.wowhead.com/item=50449/stiffened-corpse-shoulderpads
https://www.wowhead.com/item=50452/wodins-lucky-necklace
https://www.wowhead.com/item=50447/harbingers-bone-band
https://www.wowhead.com/item=50453/ring-of-rotting-sinew
https://www.wowhead.com/item=50444/rowans-rifle-of-silver-bullets
https://www.wowhead.com/item=50450/leggings-of-dubious-charms
https://www.wowhead.com/item=50451/belt-of-the-lonely-noble

**How it should work:** Their intended drop rate seems to be around 0,1-0,2% for most creatures, with only unique mobs such as Svalna, the two dogs and likes having 0,8-1% chance to drop.
Bearing in mind mania has 2x drop rates on most items, it could possibly go as high as 0,2-0,4% for an average mob inside ICC, and 1,5-2% chance on unique ones.
Note: this includes the skybreaker/korkron mobs on the ramparts too which don't currently have any loot.

**How it works atm:** The drop rate appears to be 5-6 times higher than intended around 1-1,5% on on average mob. You easily get 4-5 BoE epics in a single run to drop without even clearing anything more than the mandatory packs.
Considering the mobs on ramparts and the gauntlet at Valithria don't have loot and the gauntlet of Sindragosa despawns way faster than I can click, this "mandatory packs" means approximately 50-60 mobs in a full ICC clear, which is what my %calculations are based off.
Note: the unique mobs such as Svalna/dogs/colossus barely drop any items at all, so their drops are probably missing, but this still does not balance the overflow of BoEs in every run. Their market price is laughable because they are way too easy to acquire.

**Comment by Kitzunu** [comment]
this is the loot template for Sister Svalna
![image](https://user-images.githubusercontent.com/24550914/69488203-69a38a80-0e66-11ea-975c-e4c46f5bf4aa.png)
![image](https://user-images.githubusercontent.com/24550914/69488209-76c07980-0e66-11ea-9ac6-c906a48bdd55.png)

**Comment by Rushor** [comment]
changed to 0.1 percent. was 2 percent before.

**Comment by Dranah** [comment]
This fix isn't working right. I confirmed earlier that they arent dropping too frequently anymore, but doing a more in-depth test now (with 1000+ trash mob kills on different types of rooms), it appears that the drop has gone in the opposite direction.
Other 0,1rate items are coming up every once in a while after 400-500mobs since there are multiple of them (like 6-8 types of blue BoEs and special items like damaged necklaces,Guide of Northern scavenging etc), but there is not a single epic dropping at the expected rate. And mania's custom x2 rates definitely fail to apply.
Also, half the trash still does not have loot at all, entire gunship trash, the Damned at the beginning and the special mobs which are supposed to have the highest drop chances dont have a loot table at all.
So this fix needs correction. Proposed changes:
1) Increase drop rate to 0,3% for all epics on every type of mob inside ICC (some mobs should have 0,1 and some 0,5 so it is averaged)
2) I'll report the mobs with missing loot tables separately.

**Comment by Dranah** [comment]
Getting a reasonable rate of drops since the fix.

**Comment by Dranah** [comment]
This seems reverted once more. I get 5-6 epics per run easily, if not more.

**Comment by Rushor** [comment]
Will check

**Comment by Rushor** [comment]
reapplied the fix, pls check on dev if all is good again
