### ISSUE TITLE
[Item] Maniac's Hacker of the Light

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#3734]
https://www.wow-mania.com/armory/?item=92018

On the shop description, the item says it is main-handed, like it is supposed to be, because it's a spellpower weapon, however in the armory and in-game, it is one-handed, which allows it to be dual-wielded by shamans.
I know it's a custom weapon, but this is clearly an overlooking, so I decided to report here to you.

**How it should work:**
Spell power weapons should be main-hand equipped.

Note: if you want to keep it as-is since it's custom, it is your right to do so, but please bear in mind this can be greatly imbalanced.

**Comment by Kitzunu** [comment]
```sql
UPDATE `item_template` SET `InventoryType` = 21 WHERE `item = 92018;
```
I believe this would be the fix, but this could make donators who have donated to have 2 of this item could get mad.

But it is up to Janitor I guess

**Comment by wow-mania** [comment]
Unfortunately, this can not be changed without a client update.
I will keep it in mind and add it to the next update.

Probably January.

**Comment by jarvik76** [comment]
Perhaps offer to replace 1x with https://www.wow-mania.com/armory/?item=92028 - Maniac's Barrier of the Light (Shield), which I think is the intention of the Shaman gear.
Or simply do db query for where this item is in equipment slot 17 and replace.
This would seem to be reasonable for those that have paid for 2x this item.

**Comment by wow-mania** [comment]
We will sort it in a way that is good for all.

**Comment by dodoxa** [comment]
The damages, enhancement shamans do with these weapons is no where near warriors or dks of the same gear level. It basically just makes them viable, and enhancement shaman is basically the only class that can use them. I disagree with the nerf.
