### ISSUE TITLE
[NPC] Wrath Master & Fel Soldier packs - Hellfire Peninsula 

### ISSUE THREAD

**Issue by jarvik76** [WoWManiaUK/Redemption#3735]
**Links:**
https://www.wow-mania.com/armory/?npc=19005
https://www.wow-mania.com/armory/?npc=18944

**What is Happening:**
There are two Wrath Master packs spawning in incorrect locations by the legion teleporters, and when they do they do not path to the Hellfire Portal.  This disturbs 2 specific quests (10450 & 10482) in Horde & Alliance as it makes them uncompletable.
The incorrect locations are:
70.6,45.9
71.9,55.2
[image](https://user-images.githubusercontent.com/46089380/69498646-09eac500-0ee2-11ea-8f0e-524914a17dc8.png)

**What Should happen:**
They should spawn along the Path of Glory nearer to the Hellfire Portal, and path to there.
Somewhere around location 77.7,49.5

**Comment by wow-mania** [comment]
This is as-is. They spawn and move on. Just need to wait.

**Comment by Rushor** [comment]
there is a big event connected to them called the Portal invader event - it was added some time agao and should work fine

**Comment by wow-mania** [comment]
Yes it this as is.
