### ISSUE TITLE
[Event/Quest] Pilgrims Bounty Quest - Goblin Commoner

### ISSUE THREAD

**Issue by jarvik76** [WoWManiaUK/Redemption#3736]
**Links:**
Goblin:  https://www.wow-mania.com/armory/?npc=20102
Horde Quest:  https://www.wowhead.com/quest=14036/pilgrims-bounty
Alliance Quest:  https://www.wowhead.com/quest=14022/pilgrims-bounty

**What is Happening:**
The Goblin Commoners located in Shattrath are giving the horde version of the quest (14036) to both Horde and Alliance players

**What Should happen:**
They should give quest 14036 to Horde players, and quest 14022 to Alliance.

**Comment by jarvik76** [comment]
Looks like it is all Goblin Commoners that would give this quest, not just those located in Shattrath.

**Comment by Kitzunu** [comment]
Will fix when I get home later today

**Comment by Rushor** [comment]
race condtion added fast :P
