### ISSUE TITLE
[Item/Loot] ICC trash level 200 BOEs

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#3738]
https://www.wowhead.com/item=44308/signet-of-edward-the-odd
https://www.wowhead.com/item=44313/zoms-crackling-bulwark
https://www.wowhead.com/item=37835/jetzes-bell
Forgot these on the previous report, and they are slightly different category anyway.

**How it works atm:** They have extravagantly increased drop rates from ICC trash, possibly the same 2-3% chance that other epics had. Their drop rates from other sources look alright.
**How it should work:** These can drop in several dungeons and raid trash as well as from world mobs with a low drop rate ranging from 0,01-0,5%
ICC trash mobs respectively have 0,01-0,05 rate on each according to wowhead. With mania's double rates their intended drop rate should be around 0,1%.

**Comment by Rushor** [comment]
and what is about those @Kitzunu ?

select * from reference_loot_template where reference=35074
select * from reference_loot_template where entry=35074

i think we have to chance the change of reference_loot_template itself not the chance of the item

**Comment by Kitzunu** [comment]
Oh I totally missed those, anywho.

So make chance of item = 0 and chance of reference to 0.05?

**Comment by Rushor** [comment]
yes :)

**Comment by Rushor** [comment]
updated for ref and creature loot template
