### ISSUE TITLE
[NPC] Varidus the Flenser

### ISSUE THREAD

**Issue by jarvik76** [WoWManiaUK/Redemption#3740]
**Links:**
https://www.wowhead.com/quest=11705/foolish-endeavors

**What is Happening:**
There is an error in the speech text that Varidus gives:
> Take %g him:her; away and prepare %g him:her; for animation 
![WoWScrnShot_112519_221244](https://user-images.githubusercontent.com/46089380/69583090-f9b21300-0fd1-11ea-893a-3a37a9bdb14b.jpg)

**What Should happen:**
Speech should use the engendered text.

**Comment by Kitzunu** [comment]
fixed

**Comment by Kitzunu** [comment]
![image](https://user-images.githubusercontent.com/24550914/69585350-bd85af00-0fdf-11ea-8736-ca08906cfa83.png)

**Comment by jarvik76** [comment]
Seems to have reverted.
![image](https://user-images.githubusercontent.com/46089380/73203337-c22c2800-4134-11ea-816d-45934e1fb4af.png)

**Comment by Kitzunu** [comment]
Fixed with next restart
