### ISSUE TITLE
Lich King last phase Vile Spirits 

### ISSUE THREAD

**Issue by shadownib** [WoWManiaUK/Redemption#3741]
Right now in Wow-Mania the Vile spirits are only able to be slowed 

The Vile Spirits at LK last phase must be stun able from any kind of stuns ( for example even cobalt bomb ) its the same for the spirits inside in heroic mode u must be able to stun them as the same.
( the thing which is not suppose to be stunnable is the Raging spirits / clones at the transitions.

Evidence from The world's first Lich King 25 Hardmode by Paragon 26.3.2010.  :  https://youtu.be/HKDLXauhy7E?t=38  and screen shot that shows the paladin who is stunning the vile spirit with Holy Wrath https://imgur.com/a/ojyR8qQ check them Both

**Comment by Kitzunu** [comment]
Current immunities:

1 - MECHANIC_CHARM
2 - MECHANIC_DISORIENTED
16 - MECHANIC_FEAR
32 - MECHANIC_GRIP
64 - MECHANIC_ROOT
256 - MECHANIC_SILENCE
512 - MECHANIC_SLEEP
2048 - MECHANIC_STUN
8192 - MECHANIC_KNOCKOUT
65536 - MECHANIC_POLYMORPH
131072 - MECHANIC_BANISH
4194304 - MECHANIC_TURN
8388608 - MECHANIC_HORROR
33554432 - MECHANIC_INTERRUPT
67108864 - MECHANIC_DAZE
536870912 - MECHANIC_SAPPED
