### ISSUE TITLE
Sindragosa Icy Grip 

### ISSUE THREAD

**Issue by shadownib** [WoWManiaUK/Redemption#3742]
**Links:** https://wowwiki.fandom.com/wiki/Hand_of_Protection /  https://www.wowhead.com/spell=70117/icy-grip#used-by-npc 

extra info and reason to report it : if u research in other servers their bug tracker u can probably find a evidence , atm i thust my closer friend who got some experience and memories from back the retail ( he gived me those tips how that HOP situation can help in some hard moments like example : ppl are already  verry low HP and all of them are getting grip , so they may just die , bcuz the healers won't manage to heal them that easy as , they can do it if some pala give them HOP before the grip , so the healer can just over heal while he stand on same spot , while rest of the ppl are runing back to avoid blistering cold ) plus i have experience even from other private servers where that thing was working.

**What is Happening:**ATM in Wow-Mania when u give Hand of Protection on any Healer or Rdps nothing happened , the HOP target still getting Icy Grip.

**What Should happen:**I don't know how sindragosa recognizes atm the HOP , but the Icy Grip is School from Physical spell and what should happen if u HOP any player before the Icy Grip for Blistering cold is that, he should avoid it fully ( standing on his same space while rest of the ppl are getting Icy Grip )

**Comment by Rushor** [comment]
we could make an exception to not grip targets with HoP. Are there any other spells that should prevent gripping?

**Comment by Blyatman1** [comment]
Just pitching in my two cents:

I searched the internet for anything proving this to be possible, but was not able to find any.

The only possibility that I found, is that the Paladin could have been using Hand of Protection on a player that managed to not get pulled in, but it wasn't Hand of Protection that prevented it, but rather the player that would recieve HoP would resist the pull (irrelevant to HoP).

I can't guarantee this to be the case, but I searched and could not find anything regarding this (even from other servers).

**Comment by Keader** [comment]
I never hear about that too.
@Dranah can take a time to search this ?

**Comment by shadownib** [comment]
:(

**Comment by Rushor** [comment]
eh

https://www.google.com/search?sxsrf=ACYBGNQiUSZt5WPaUHTgZkirFJzVPa5_ew%3A1574845423798&source=hp&ei=7zveXZmsLo-s6AS_opjwDQ&q=Icy+Grip+Hop+sindragosa&oq=Icy+Grip+Hop+sindragosa&gs_l=psy-ab.3...111.6678..7621...1.0..0.228.2577.0j15j1......0....2j1..gws-wiz.......0i10j0j0i22i30j33i22i29i30j33i160j33i21.cipzT7qWw8g&ved=0ahUKEwjZ37ywhIrmAhUPFpoKHT8RBt4Q4dUDCAc&uact=5

https://www.google.com/search?sxsrf=ACYBGNTWNctB-UOk1Z0-3qk8d83Wyde1dw%3A1574845432650&ei=-DveXdCVJ-SHk74P7LyKiAw&q=Icy+Grip+hand+of+protection+sindragosa&oq=Icy+Grip+hand+of+protection+sindragosa&gs_l=psy-ab.3...13199.17058..17295...1.0..0.184.2680.0j19......0....1..gws-wiz.......35i39.xU3hBQHkdgU&ved=0ahUKEwjQ8dq0hIrmAhXkw8QBHWyeAsEQ4dUDCAo&uact=5

Cannot find there naything either. Maybe some video research now?

**Comment by Dranah** [comment]
Not enough evidence. Some sources suggest the ability is more of a spell that just cannot be reflected or resisted, rather than a physical attack, which means BOP has not much to do with it.

**Comment by shadownib** [comment]
:(
