### ISSUE TITLE
[Quest] Rescuing the Rescuers (Alliance)

### ISSUE THREAD

**Issue by JohnBrinkle** [WoWManiaUK/Redemption#3743]
**Links:**
https://www.wowhead.com/quest=11244/rescuing-the-rescuers

**What is Happening:**
The harpoons that hold down the scouts do not respawn.

**What Should happen:**
The harpoons for the quest should respawn at a relatively fast rate.
It is a crucial quest that has to be done by everyone starting in the Howling Fjords.

**Comment by wow-mania** [comment]
Thanks for taking the time to log the issue. Please use our armory whenever possible.

**Comment by JohnBrinkle** [comment]
Ah yes I couldn't find it at first in the armory
But now I found the same issue was mentioned here a while ago (found on google now)
He writes
Quest: http://www.wow-mania.com/armory/?quest=11244
NPC: http://www.wow-mania.com/armory/?npc=24077

The old issue was https://github.com/WoWManiaUK/Redemption/issues/3442

**Comment by JohnBrinkle** [comment]
So in the old post it was mentioned to work fine in dev and that the respawn time is 5 min.
But I haven't seen any harpoons respawn for hours now. I have no idea what could interfere with that.

**Comment by wow-mania** [comment]
This has been fixed yesterday.

**Comment by JohnBrinkle** [comment]
The harpoon near the bridge respawned one time - then even that didn't respawn anymore

**Comment by Rushor** [comment]
okay the creature will now despawn on kill event after 5 sec. maybe the grid cell got inactive once the player left the zone, that caused the creature to become inactive and therefore no oject spawned on respawn of npc. pls try now.

**Comment by wow-mania** [comment]
Script was incomplete. Works now.
