### ISSUE TITLE
[Pillgrims bounty ability pass the (food type)]

### ISSUE THREAD

**Issue by dimman321** [WoWManiaUK/Redemption#3744]
When you sit on the chair you get 6 abilitys, one of them is switch plates for another. Bugg is it doesnt switch plates. Plane simple.

**Comment by Kitzunu** [comment]
Do you know the name or ID of the spell?

**Comment by WhitephoenixTheBunny** [comment]
I believe is: https://www.wow-mania.com/armory/?search=pass+the#spells

![image](https://user-images.githubusercontent.com/31921098/69638678-0d518e00-1053-11ea-9785-76a2ca66e189.png)

**Comment by dimman321** [comment]
Thank you! I was about to look it up.

**Comment by WhitephoenixTheBunny** [comment]
I tried test, but PTR is down _I blame kit_

**Comment by Blyatman1** [comment]
You don't switch plates. The ability allows you to "pass a plate" to the seat you're targetting. It doesn't switch the plate of the seat you are currently sitting in.
 
If you're sitting in Turkey, you can "pass a plate" of turkey to any other seat. If you stand up, and sit back down in the seat that you passed a plate to, you can "eat" the plate that you passed to it.

(Ex. Sitting in turkey, pass a plate to sweet potato, stand, sit in sweet potato, you can eat the turkey you sent)

**Comment by dimman321** [comment]
kek... now how i do remove this stupidity now :S

**Comment by WhitephoenixTheBunny** [comment]
I just tested it lol... 
I haven't seen this.. but anyway they are working 
![image](https://user-images.githubusercontent.com/31921098/69644431-8b666280-105c-11ea-8c54-463d60dbf9e1.png)
