### ISSUE TITLE
[Spell/Boss] Remorseless Winter Range

### ISSUE THREAD

**Issue by slaniaxx** [WoWManiaUK/Redemption#3745]
**What is Happening:**
Lich King's remorseless winter does heavy damage to mages who are at max range with range increasing talents.

**What Should happen:**
Remorseless Winter should do negligible/no damage to mages/hunters who are talented into range increase (41 yards total spell range I believe).

https://www.youtube.com/watch?v=lO8KFr6oIZ0 
in this retail video it's clearly seen that mages/hunters do damage the LK without taking heavy hits from RW. (They do take some damage spikes from the ice orbs). 
The problem might be related to mages/hunters range increasing talents and/or remorseless winters range/damage.

**Comment by Dranah** [comment]
Okay, so it is a fact that 41 yard abilities are supposed to be able to reach LK in some delicate positioning without taking damage. 
The remorseless winter https://www.wowhead.com/spell=68983/remorseless-winter however has a 45 yard range which seems quite controversial at first.

I was trying to figure how this is possible and came up with this after my in-game tests:
![WoWScrnShot_112719_210913](https://user-images.githubusercontent.com/31132743/69756484-f302d780-115a-11ea-8d3f-63d8d9c1b410.jpg)
As you can see on the screen, I snapshot my distance from LK in 2 positions; the above one is where i just can't shoot him yet and currently don't take any damage from remorseless winter. The below one is where I can reach him with my 41 yard spells but here on mania, you start taking damage from remorseless winter at the same time.

**How it should work** is that your spells calculate with the first range values, but the remorseless winter aura considers the second one (exact) distance. In the position where I was standing (the lower line range check) is where you are supposed to be able to shoot LK (40,99yard for your FB), but LK's aura cannot damage you (45,99 range for him).

PS: I believe the difference between the two values is that one calculates from the edge of LK's hitbox, and the other is calculating from the center.

**Comment by Keader** [comment]
Ok, it will do damage in exactly 45 yards now (counting with hitbox)

**Comment by Dranah** [comment]
It is 45 yard now but checks for the wrong value. It is considering the first value, and now you need to stand here, even further to be safe:
![WoWScrnShot_113019_200536](https://user-images.githubusercontent.com/31132743/69904879-e1187300-13ac-11ea-9219-34c2948de265.jpg)

**Comment by Dranah** [comment]
New fix added by Keader, works as intended now, you can shoot him at the 40-41 yard range
![WoWScrnShot_113019_203023](https://user-images.githubusercontent.com/31132743/69905278-81709680-13b1-11ea-8b96-6e3302cf7431.jpg)
