### ISSUE TITLE
[Glitch/phasing/texture] Bone Spikes phasing people out and throwing them underground

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#3746]
I managed to reproduce this issue. It seems to happen when the Bone Spike is freed too fast (within 1second). Aka, when people do their job properly and instantly smack the spike, they get their party member bugged.

**How it works:** If the Bone Spike is freed within 1 second while its still positioning the person it just impaled (you can see the character turning on top of the spike), the character gets phased out after the spike drops him.
He sees other units in the room disappearing and re-appearing and he's invisible to other players.
SS:
![WoWScrnShot_112719_224212](https://user-images.githubusercontent.com/31132743/69761390-8b9f5480-1167-11ea-9f2b-b953721d2145.jpg)

However it is possible that Marrowgar chooses to spike him again, or he simply dies to any incoming damage he still takes, which updates the position of the person to be actually under texture like this:

![WoWScrnShot_112719_224228](https://user-images.githubusercontent.com/31132743/69761410-9d80f780-1167-11ea-81c3-a686a8e2f481.jpg)

![WoWScrnShot_112719_224232](https://user-images.githubusercontent.com/31132743/69761422-a70a5f80-1167-11ea-8cec-77492225115e.jpg)

This person cannot be battle rezzed, rezzed and might also not get credit/loot for the kill if they get auto-released. Most of the time though, you have to /rl to release and you end up here:
![WoWScrnShot_112719_224247](https://user-images.githubusercontent.com/31132743/69761469-c7d2b500-1167-11ea-8915-9e9638ea4b5f.jpg)

**How it should work:** The spikes should behave properly even if they are instantly killed when they spawn. Should not phase their target or drop them into texture to fall under and respawn in barrens.

**Comment by Keader** [comment]
I made a fix, not idea if will work, since i cant reproduce.

**Comment by Keader** [comment]
Need dynamic spawn to fix it :/

**Comment by Dranah** [comment]
We are doing a workaround for this to prevent it happening when a player gets spiked at low hp.

**Comment by Dranah** [comment]
Now the only way to glitch players is to purposefully nuke down a spike in less than 1second which takes real effort.
