### ISSUE TITLE
[Spell] Blink

### ISSUE THREAD

**Issue by dimman321** [WoWManiaUK/Redemption#3748]
**Links:**
https://www.wow-mania.com/page/armory
Well look at that, link doesnt want to show properly.
Attach image doesnt work btw unless browser is a resized window...
![attach](https://user-images.githubusercontent.com/13328157/69892316-80cdf680-1304-11ea-8bd6-ed7792c8aa8b.png)
![noupload](https://user-images.githubusercontent.com/13328157/69892229-a1e21780-1303-11ea-81bb-5c20a8feca23.png)
![manavoid](https://user-images.githubusercontent.com/13328157/69892223-9b53a000-1303-11ea-8fb8-017bc28b379e.jpg)
Correct me if im wrong on the name please. I tried to look it up in what happened to me log but it wasnt there, so I asked people in the raid and they said it was mana void.

**What is Happening:**
This happened on in icc25 on valithria dreamwalker fight. 
Mana Void spell that targets a random raid member and puts a shadowy circle underneath him,
drains his mana and slows him while he is inside, after short time it shoots him up in the air and he takes fall damage once he land.

I used blink to get out of it because I was slowed. Instead of teleporting out I was shot in the air and blinked at the same time which caused me to teleport outside icc-raid as in outside the dungeon and fall to the death.

**What Should happen:**
https://www.youtube.com/watch?v=B_m-YDp8YOw
If you use blink in freefall you teleport directly to the ground.

**Comment by Drostthehunter** [comment]
1st of all Mana Void does not shoots you up in the air, its the other spell shooting you up into the air if you do not move fast enough, about the blink issue it is true, it happened to me many times, not just on Valithria encounter, also when leaving Blood Queen Lana'thel Platform, in order to escape fall damage you blink under the ICC and die, its the issue with blink spell, and so far ive only experienced it in ICC.

**Comment by Drostthehunter** [comment]
Should rename the issue to [Spell] Blink since its not related to Mana Void at all.

**Comment by Keader** [comment]
Test if still happens.

**Comment by dimman321** [comment]
Thank you for changing and correcting me. I did not know it was the other way around :S
