### ISSUE TITLE
Game closes

### ISSUE THREAD

**Issue by tejszin** [WoWManiaUK/Redemption#3749]
Started to have a tons of wowerrors, usually when entering a city, but since i deleted all of my addons i dont get the errors, the game just closes right after world loads. Cache always deleted.
I would much appriciate a solution, since i cant play a minute with this issue.

**Comment by tejszin** [comment]
[2019-11-30 01.03.22 Crash.txt](https://github.com/WoWManiaUK/Redemption/files/3907034/2019-11-30.01.03.22.Crash.txt)
this is the latest crash log

**Comment by wow-mania** [comment]
This is not a server-side issue. This repository is only for server issues and not the client.
Make sure you have OUR client and always start with the Launcher.
