### ISSUE TITLE
[Quest] Where in the World is Hemet Nesingwary

### ISSUE THREAD

**Issue by hornista** [WoWManiaUK/Redemption#375]
Quest: Where in the World is Hemet Nesingwary
Quest ID: http://www.wow-mania.com/armory/?quest=12521

Archmage Pentarus http://www.wowhead.com/npc=28160/archmage-pentarus
Archmage Pentarus' Flying Machine http://www.wowhead.com/npc=28192/archmage-pentarus-flying-machine#screenshots

Speak to Archmage Pentarus at the Dalaran Flightpoint to gain the quest, to travel to Sholazar basin and find Hemet Nesingwary

Speak to him again and he mounts the player on a Flying machine which then takes a portal from Dalaran to Sholazar Basin

This is the point where the quest fails
The player mounts and the portal opens but the flying machine does not move. The player cannot exit the vehicle manually
Relogging dismounts the player. Player can remount but with the same results.

The Flying machine should enter the portal and fly above sholazar toward Nesingwary camp.  
It is attacked and shot down. The player parachutes down, next to a survivor and turns in the quest before moving onto the camp itself

This can be reproduced (and has been) on a total of 2 characters; of mine; so far and I have seen one other player so afflicted

Using the current wow mania client and Launcher
Win 10 installed

**Comment by Kalasbyxan** [comment]
The player can fly to the destination themselves to complete the quest. Doable, but broken and not working as intended.
