### ISSUE TITLE
NPC and enemies missing weapon

### ISSUE THREAD

**Issue by AndrasAhr** [WoWManiaUK/Redemption#3750]
**Links:**

**What is Happening:**

**What Should happen:**

**Comment by Dranah** [comment]
I tried, but could not find the "what" label for this post.

**Comment by AndrasAhr** [comment]
For example, at the beginning of the Human's story, the Defias bandits do not have their weapon, they fight with their fists

**Comment by Rushor** [comment]
that needs to be fixed individual. you need to make a list of npcs
