### ISSUE TITLE
[Killbox] Nagrand killbox where there shouldn't be one

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#3753]
**Links:** ![WoWScrnShot_120219_012642](https://user-images.githubusercontent.com/34783736/69935624-77c75b80-14a3-11ea-92d8-f16fc69c6bee.jpg)

**What is Happening:** There currently is a killbox on the overworld in Nagrand, which causes players to instantly die if they are to go through it. It is near (56,70) right at the top of the lower waterfall.

**What Should happen:** There shouldn't be a killbox there.

**Comment by wow-mania** [comment]
This has nothing to do with killbox. Thi is a glitch in the texture and unfortunately it can not be fixed.
You basically fall and die.

**Comment by wow-mania** [comment]
#179
