### ISSUE TITLE
[Spell] Unbound Plague / Plague Sickness

### ISSUE THREAD

**Issue by dimman321** [WoWManiaUK/Redemption#3765]
**Links:**

https://www.wowhead.com/spell=70911/unbound-plague

https://www.wowhead.com/spell=70953/plague-sickness

https://www.youtube.com/watch?v=zvJ9HpNKyj8

**What is Happening:**

   On Professor Putricide Heroic encounter he uses a spell called Unbound Plague. The player who gets it also gets a debuff called Plague Sickness after he passes the Unbound Plague - which increeses the damage done by Unbound Plague. This debuff stacks, so if a player was affected by same plague say 5 times, it would increese the damage plague does on that player by 500%.
   During my last encounter I think I saw the plague sickness debuff go up to 700% on me according to mouseover tooltip while the damage dealt by plague was unaffected. 

**What Should happen:**
   I shouldve been dead long ago... xD
   Plague Sickness should work as an amplifier for Unbound Plague. People shouldnt be able to "stack" away this debuff. Player who has the debuff should run away from raid, have plague for 8-15 sec and then another player should come and take it. This is repeated untill the plague passes. 

ps: I think that wowhead values are incorrect, it says N x 250% and I dont know if that value was changed because during the encounter I saw it beeing N x 100%  aaand I dont know if you know this but mania armory links does not "link" anything :S

![asd](https://user-images.githubusercontent.com/13328157/70110161-5d7db100-164e-11ea-8d22-9edd9354995d.JPG)

**Comment by wow-mania** [comment]
This most likely will remain as-is.

**Comment by GMWeeble** [comment]
This is correct, the boss is really done easy unless this is fixed. And it should be.

**Comment by jarvik76** [comment]
Previously reported on #2089 #2074

**Comment by Keader** [comment]
@jarvik76 not same issue.
This issue was never reported before.

**Comment by Keader** [comment]
Starting working on it.

**Comment by Keader** [comment]
Tested and working correctly.
Base damage in 10 man is 259 (first tick)
With Plague Sickness, it become 906
906*3.5 (250%) = 906.5

Damage of this spell scale with: BaseDamage * ModsTaken * (1.25 ^ ticksDone)
