### ISSUE TITLE
Critical Chance Bug

### ISSUE THREAD

**Issue by Shauni1155** [WoWManiaUK/Redemption#3766]
I use
Shadow's Edge (ilvl 264) - 43.99% crit chance - https://wotlk.evowow.com/?item=49888
when i equip Bloodfall (ilvl 264) - 31.48% crit chance - https://wotlk.evowow.com/?item=50178

Please fix it

**Comment by Kitzunu** [comment]
First of all, please use the template that is made.
Second, what is the bug? You have not said anything about what is not working correctly.

Thank you,
Regards

**Comment by wow-mania** [comment]
Please read our wiki on how to create an issue and NEVER use other servers links here.
