### ISSUE TITLE
Wep Crit chance Bug

### ISSUE THREAD

**Issue by Shauni1155** [WoWManiaUK/Redemption#3767]
**Links:**
https://wotlk.evowow.com/?item=49888
https://wotlk.evowow.com/?item=50178
**What is Happening:**
With Bloodfall i have 13% less crit than Shadow Edge.

**What Should happen:**
Since am a Paldin and Bloodfall gives Agility, i should have more crit, not 13% less!

**Comment by Kitzunu** [comment]
On Paladin with bloodfall, naked char: 
![image](https://user-images.githubusercontent.com/24550914/70154076-2dff9080-16b0-11ea-948e-c1833c3f781d.png)
First row = Critchance + Critrating
2nd row = Bonus crit from agil

Paladin naked with Shadowedge: 
![image](https://user-images.githubusercontent.com/24550914/70154142-4b345f00-16b0-11ea-8052-7ac6ce565d07.png)
First row = Critchance + Critrating
2nd row = Bonus crit from agil

**Comment by Kitzunu** [comment]
I cannot reproduce

**Comment by Shauni1155** [comment]
![InkedWoWScrnShot_120119_154037_LI](https://user-images.githubusercontent.com/58518861/70243348-b5153d00-1772-11ea-9d56-4ca33abdda66.jpg)
![InkedWoWScrnShot_120119_154033_LI](https://user-images.githubusercontent.com/58518861/70243355-b8102d80-1772-11ea-9ba2-6d2beea8607c.jpg)

**Comment by Dranah** [comment]
do you have maxed polearm weapon skill?
