### ISSUE TITLE
Wep Crit chance Bug

### ISSUE THREAD

**Issue by Shauni1155** [WoWManiaUK/Redemption#3768]
**Links:**
![InkedWoWScrnShot_120119_154037_LI](https://user-images.githubusercontent.com/58518861/70243601-2fde5800-1773-11ea-947d-92c48dc78a6c.jpg)
![InkedWoWScrnShot_120119_154033_LI](https://user-images.githubusercontent.com/58518861/70243603-3076ee80-1773-11ea-9a3c-de1e644510ba.jpg)

**What is Happening:**
With Bloodfall equiped i have 13% less crit chance  than Shadow Edge...

**What Should happen:**
BloodFall gives 160 Agility, so as Paladin i should have more crit than Shadow Edge, not 13% less !!!

**Comment by Oganku** [comment]
Did you try clearing cache? Cause that can cause that kind of visual issues sometimes.

**Comment by Shauni1155** [comment]
I did all steps the gms told me, cleared cache several times, i run the game form laucncher, i have the latest update, i posted it here because the gms couldnt do anythink abou it.

**Comment by wow-mania** [comment]
As- is formula is not direct proportional it takes into account many other variables. What you get on screen is the final result.

**Comment by Kitzunu** [comment]
Again, as I explained before.
I cannot reproduce it. Might be a char issue
