### ISSUE TITLE
[Item] A Guide to Northern Cloth Scavenging - 43876 

### ISSUE THREAD

**Issue by jarvik76** [WoWManiaUK/Redemption#3770]
**Links:**
Item: https://www.wowhead.com/item=43876/a-guide-to-northern-cloth-scavenging
Skill taught: https://www.wowhead.com/spell=59390/cloth-scavenging

**What is Happening:**
This book drops even after you learn the skill.  This is rather annoying, since all you can do is delete it, and it needs confirmation to delete.

**What Should happen:**
The book should only drop if you a) have tailoring skill >325, b) haven't learned the skill already.

**Comment by Rushor** [comment]
can either be fixed in core or db. i have a fix for that if you wish

**Comment by Kitzunu** [comment]
This was not properly fixed.

I have added so it will check for:

1. You have Tailoring skill level to 325
2. You have not learned the spell = 59390

If those two criteria are fulfilled then the item can drop.
