### ISSUE TITLE
[Item] Manual: Heavy Frostweave Bandage

### ISSUE THREAD

**Issue by jarvik76** [WoWManiaUK/Redemption#3771]
**Links:**
Item:  https://www.wowhead.com/item=39152/manual-heavy-frostweave-bandage
Spell taught:  https://www.wowhead.com/spell=45546/heavy-frostweave-bandage

**What is Happening:**
Itemis dropping regardless of First Aid skill.

**What Should happen:**
Should only drop if you have >390 skill in First Aid, and have not learned the spell.

**Comment by wow-mania** [comment]
We cannot know about if you know the spell or now.
It is being set just to check the skill level.

**Comment by Kitzunu** [comment]
This was not properly fixed.

I have added so it will check for:
1. You have First Aid skill level to 390
2. You have not learned the spell = 45546

If those two criteria are fulfilled then the item can drop.
