### ISSUE TITLE
quest in howling fjord Send Them Packing

### ISSUE THREAD

**Issue by bjuice1225** [WoWManiaUK/Redemption#3773]
**Links:**

**What is Happening:**  The quests wants you to send 10 abandoned pack mules packing by " getting close to them and threatening them with a raised fist" after  having gm psygoa atempt to resolve it was told to report the quest here

**What Should happen:**  I am not entirely sure whats supposed to happen  but im quite sure it should be giving credit to you when you threaten them not  have  nothing at all happen.

**Comment by gamer100** [comment]
https://www.wow-mania.com/armory/?quest=11224%20item
https://www.youtube.com/watch?v=9JT_foO0WC0

**Comment by Kitzunu** [comment]
![image](https://user-images.githubusercontent.com/24550914/70339982-2971de00-1850-11ea-8fc9-00d40c11e5a2.png)

Works. You have to stay near them and do /raise
