### ISSUE TITLE
[NPC/Loot] Sister Svalna

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#3774]
https://www.wowhead.com/npc=37126/sister-svalna

**What is Happening:**
She has no loot table apart from gold and emblem of frost on any difficulty.

**What Should happen:**
Should have a regular trash drop rate mixed from uncommon/common/rares as per wowhead and an outstanding 1-1,5% drop rate on all the ICC epic zone drops. (full list of zone drops here https://github.com/WoWManiaUK/Redemption/issues/3733)

**Comment by Rushor** [comment]
https://i.imgur.com/6Cxbifs.jpg
drops are handled like for every other creature that already has fitting loot tabes and 1.5 percent chance to drop one of the epics.
