### ISSUE TITLE
[NPC/Loot] The Damned

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#3775]
https://www.wowhead.com/npc=37011/the-damned

**What is Happening:**
Has no loot table other than silvers.

**What Should happen:**
Should have regular trash loot table with common/uncommon/rare items as shown on the wowhead page and an average 0,2% chance for the ICC zone epics (full list of zone drops here:
https://github.com/WoWManiaUK/Redemption/issues/3733

**Comment by Rushor** [comment]
I fix those issues in 3 hours

**Comment by Rushor** [comment]
https://i.imgur.com/FIyUO4y.jpg
drops are handled like for every other creature that already has fitting loot tabes.
