### ISSUE TITLE
[NPC/Loot] Gunship Trash

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#3776]
https://www.wowhead.com/npc=37148/skybreaker-summoner
https://www.wowhead.com/npc=37027/skybreaker-hierophant
https://www.wowhead.com/npc=37016/skybreaker-luminary
https://www.wowhead.com/npc=37144/skybreaker-marksman
https://www.wowhead.com/npc=36998/skybreaker-protector
https://www.wowhead.com/npc=37026/skybreaker-sorcerer
https://www.wowhead.com/npc=37017/skybreaker-assassin
https://www.wowhead.com/npc=37003/skybreaker-vindicator
https://www.wowhead.com/npc=37004/skybreaker-dreadblade
https://www.wowhead.com/npc=37021/skybreaker-vicar
https://www.wowhead.com/npc=37032/korkron-defender
https://www.wowhead.com/npc=37030/korkron-primalist
https://www.wowhead.com/npc=37032/korkron-defender
https://www.wowhead.com/npc=37028/korkron-stalker
https://www.wowhead.com/npc=37031/korkron-oracle
https://www.wowhead.com/npc=37035/korkron-vanquisher
https://www.wowhead.com/npc=37033/korkron-invoker
https://www.wowhead.com/npc=37149/korkron-necrolyte
https://www.wowhead.com/npc=37029/korkron-reaver

**What is Happening:**
These are the trash mobs fighting each other on the Ramparts leading from Lady to Gunship. They have no loot table at all, never drop anything, not even gold.

**What Should happen:**
They should drop silvers, common/uncommon/rare items like other trash and ICC zone epics with an average 0,1% chance. (full list of zone drops here: https://github.com/WoWManiaUK/Redemption/issues/3733)

**Comment by Rushor** [comment]
loot added with 0.1 percent chance for epics. silver also added.


https://i.imgur.com/G1oGOgw.jpg
