### ISSUE TITLE
[NPC/Loot] Precious

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#3777]
https://www.wowhead.com/npc=37217/precious

**What is Happening:**
Has no loot table other than gold and his Ribbon.

**What Should happen:**
Should have a regular trash loot consisting of common/uncommon/rare drops and an outstanding 1%ish chance on all ICC epic zone drops. (full list of zone drops here: https://github.com/WoWManiaUK/Redemption/issues/3733)

**Comment by Rushor** [comment]
https://i.imgur.com/VxtgrUt.jpg 

drops are handled like for every other creature that already has fitting loot tabes.
