### ISSUE TITLE
[Spell] Mortal Wound - ICC Pups

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#3778]
https://www.wowhead.com/spell=71127/mortal-wound
Used by Stinky and Precious in ICC
https://www.wowhead.com/npc=37025/stinky
https://www.wowhead.com/npc=37217/precious

The two dogs have 2 different problems with this same ability they share.
1) Precious uses it non stop. Spams it without cooldown, basically you get a stack every second regardless of avoidance and even the second tank is up to 10 stacks before the first would have their buff expire.
**How it should work:** The ability should be used only every 10seconds
2) Stinky sometimes forgets to use it after decimates.
He uses it with proper 10sec intervals by default, but when the cast would co-occur with Decimate, it gets skipped and he wont attempt to cast it again for another full course, allowing one tank to easily tank him without ever getting more than 2-3 stacks.
**How it should work:** If the spell coincides with Decimate, he should use it on next melee attack after the Decimate.

**Comment by Keader** [comment]
Precious sniff:

```
ServerToClient: SMSG_SPELL_GO (0x7686) Length: 51 ConnIdx: 2 Time: 12/30/2011 14:52:58.235
Caster GUID: Full: 0xF1309161000008A1 Type: Creature Entry: 37217 (Precious) Low: 2209
Caster Unit GUID: Full: 0xF1309161000008A1 Type: Creature Entry: 37217 (Precious) Low: 2209
Cast Count: 0
Spell ID: 71127 (Mortal Wound)
Cast Flags: 264 (Unknown3, Unknown7)
Time: 0
Hit Count: 1
[0] Hit GUID: Name: XXXXX
Miss Count: 0
Target Flags: 2 (Unit)
Target GUID: Name: XXXXX
```

Getting all timers based in SPELL_GO (when spell finish cast and hit someone).
It returns me:

> 14:52:46.223
> 14:52:48.626
> 14:52:51.028
> 14:52:53.430
> 14:52:55.833
> 14:52:58.235

So, interval is around 2~3 sec.
In code was exactly 2 sec, fixed it.
But still, is not 10 sec like you said.
You can see it in this video too: https://www.youtube.com/watch?v=RdqPb2Fslg0
Look how faster dbm spam it :)

Stinky should have this "spam" too, so fixed too :)

**Comment by Dranah** [comment]
My bad then. Just make them alike :D
