### ISSUE TITLE
[Boss/Spell] Coldflames

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#3779]
https://www.wowhead.com/npc=36612/lord-marrowgar
https://www.wowhead.com/spell=69146/coldflame
https://www.wowhead.com/spell=69075/bone-storm

1) Cold flame speed
**How it works atm:** Moves roughly twice as fast as on blizz. As far as i could test, the tiny NPC that is moving the flame is jumping double every time. 
**How it should work:** Coldflames should spread at half the speed of the current.

2) "Fake flames" delay actual flames
**How it works atm**: There is some kind of "indicator" flame that precedes all of the coldflames coming out of marrow. (i believe this? https://www.wowhead.com/spell=69145/coldflame)
Its original purpose on blizz seems to be to "travel through the hitbox" during p1, as the actual flames only have to spawn outside of it.
On blizzard, it just goes from the center to the edge of hitbox towards the targeted person and then begin to spawn actual flames as soon as it leaves the red circle.
Here however, this indicator travels as far as the targeted person stands, which is often the other end of the room in case of a ranged DPS.
![WoWScrnShot_120719_040208](https://user-images.githubusercontent.com/31132743/70368122-7208b600-18a7-11ea-9454-29f9ce359d57.jpg)
The Screenshot shows a bauble of fake flame headed towards one of my alts. Now, this "flame" does not deal damage or do anything, only marks the path where the actual cold flame is intended to spawn. The actual coldflames cannot seem to spawn until this indicator has reached its original target, which can be up to 7-8 seconds even with its boosted movement speed.

The problem is tenfold with these being present;
- confuses players as it has similar color and animation to the real flames
- delays the actual flames, which results in multiple flames spawning at the same time, either on top of each other or next to, both are equally bad
- Happens during bone storm too, going in all directions, creating duped flames. During Bone storm, as the cross of flame does not specifically target anyone, the indicator travels until it hits the wall, creating a 7-8second delay on the flames spawning after marrowgar has charged.

**How it should work:**
- The indicator flame must only travel til the edge of the red circle and then begin to spawn the actual flames immediately.
- During bone storm, the indicator must not spawn/be present at all. There is no need for them, Marrow spawns the flames right under himself each time after he charges.

**Comment by Keader** [comment]
I cant make animation go faster.
But now, flames will not be delayed.
Speed fixed.
And on storm, it have a "fake flame" but, only in hitbox area, cant be removed.

**Comment by Dranah** [comment]
Flame speed and Flame timer has been fixed. The visual issues will be in a separate report if we find some way to improve.

**Comment by Dranah** [comment]
This has been reverted by the last update... -.-"

**Comment by Keader** [comment]
It's not a regression in the end, we fixed some new issues and updated the ones made here.

**Comment by Keader** [comment]
@Kitzunu wtf?

**Comment by Kitzunu** [comment]
Sorry 😅 Was on phone and was supposed to change milestone x)
