### ISSUE TITLE
[Raid] Ulduar's Mimiron

### ISSUE THREAD

**Issue by Ashamedlol** [WoWManiaUK/Redemption#378]
Phase 1 (Leviathan Vehicle): Mines do not spawn, should be spawning as a circle and another layer of them later on.

Phase 3 (Aerial Assault Command): The copter goes in meele range (supposed to be in the air), Boom Bots should be exploding dealing 23,563 to 26,437 Fire damage in a 5 yard radius, Magnetic Cores do not do anything because the boss is already meele range (not in the air) and the adds do not de-spawn if you wiped on phase 3 which can cause you to delay looting magnetic bombs for an advantage of phase 3.

**Comment by fvicaria** [comment]
Is this one still valid?

**Comment by Grindall** [comment]
it is. 
also, 
 Plasma Blast – a 3-second cast that deals 25,000 Spellfire damage per second for 6 seconds. 
it doesn't cast, it is instant

**Comment by wcslanker** [comment]
To add a little more information to the Ph1 Leviathon (tank) mechanic... the mines do spawn sometimes, but are invisible making it a gamble to move. 

Ph3 for the ariel command unit (head) phase, the head moves too close to the raid, drops to the ground making it to where the bomb adds will spawn way to close to the raid and blow up. 
The Assult Bots that spawn are suppose to drop Magnetic Cores which are to use to throw at the head to bring it to the ground and receive extra damage for melee dps to run in and dps. 
Now  what needs to be fixed on the phase 3 is the head needs to still be in the air droppin the Bomb bots properly, and the Assult Bots need to drop their Magnetic Cores so you can shoot the head down to deal more damage to push the phase.

**Comment by wcslanker** [comment]
Update: Just tried to do hard mode today on live and we wiped on ph3 but its definitely do able but when we wiped he was stuck in combat.

**Comment by Emcitementz** [comment]
> Plasma Blast – a 3-second cast that deals 25,000 Spellfire damage per second for 6 seconds.
it doesn't cast, it is instant

It's casted, the turret casts it not the tank.
