### ISSUE TITLE
[Dungeon] Culling of Stratholme, Event bugging out

### ISSUE THREAD

**Issue by Drostthehunter** [WoWManiaUK/Redemption#3780]
**What is Happening:**
If you have spoken to Arthas and started the event for entering the Culling of Stratholme the event is able to get stuck in 1 place and freeze in time preventing you from continuing the dungeon if you go and speak to Chromie to skip the event right after you did spoke to Arthas.

Since this is the newest fix after years people could try and skip event right after they did talk to Arthas already because they are used to the dungeon that way.

**What Should happen:**
If you have already spoke to Arthas to do the full roleplay event there should be no way to talk to Chromie and get event "skipped" cus it bugs out the dungeon.

**Comment by wow-mania** [comment]
You cannot skip it. That is how we designed it.
Unless you can show us this was an option on 3.3.5a

Let me know how and where you got stuck and we can try to fix it.

**Comment by Drostthehunter** [comment]
I opened this in order so your GMs dont get 3 thousands tickets regarding this dungeon, rest is out of my power. I explained when and how dungeons bugs out, the whole roleplay event can be skiped as you added it in the latest fix.

**Comment by Kitzunu** [comment]
Most likely a side effect of @Rushor fix.

**Comment by Kitzunu** [comment]
@wow-mania Yes, there is an option to skip the role play if you have completed the required quest.
Rushor fixed that the last update, so this is most likely a side effect :)

**Comment by Rushor** [comment]
Okay will remove the skip once arthas have been speeken to. Sorry for that. Fast fix tomorrow

**Comment by Rushor** [comment]
once you started the long version, you can no longer talk to chromie.

once long version was selected, chromie will not even react to tigger the skip.

![I](https://i.imgur.com/nVZXx8m.jpg)
