### ISSUE TITLE
[Boss/Glitch] Gunship encounter glitches

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#3783]
https://www.wowhead.com/object=201873/gunship-armory

1) Encounter won't start after a wipe
**How it works:** If the raid wipes (yes it happens, dont laugh) in a manner that no one in the raid is alive in the moment your ship dies and the encounter terminates, upon trying to start the event again, it will not work.
You talk to the NPC, the ship does not begin moving and you cannot see the enemy ship, you can't see or fight the enemy NPCs that begin shooting you through texture. 
You have to wipe and redo, but if you don't make sure that at least 1 person is alive when your ship gets finished off, the same glitch will happen over and over when you try to start the fight again.
**How it should work:**
The encounter needs to reset properly even if your raid dies sooner than your ship.

2) Getting instant-killed after releasing and rezzing
**How it works:**
This happens if your raid members release and rezz before the encounter is fully reset. The full reset is marked by all the corpses being teleported down to the ramparts and any raid member still alive getting instant killed and teleported to the same spot.
You can enter ICC sooner than that happens, because the encounter is no longer in progress once everyone in your raid is dead. After a few seconds everyone gets instant killed at the entrance, and since the encounter can't teleport your corpses up from there to terminate properly, it gets stuck in a loop, instant killing you over and over when you attempt to enter and rezz again.
You need to leave the raid for a good 10-15minutes to allow it to soft-reset so you can continue.
**How it should work:**
The fight must properly reset even if some raid members released earlier.
It should not allow ghosts to enter the raid until the fight is fully reset.

**Comment by Dranah** [comment]
The encounter will no longer bug as long as at least 1 person is not-yet released when the ship is destroyed. That is easy to avoid.

**Comment by Filosof93** [comment]
This bug is super annoying still. Having to rely on tickets to reset the raid. Happened two times in a short time where some jerk went ahead and started the fight while raid was not on the ship. -> wait 30 minutes. Ship is not there and you die upon entering the raid. During offtimes GM's can't guarantee on responding quick enough, so it's a raidover if one player doesn't know about the bug or are being a jerk.
