### ISSUE TITLE
Bag bug

### ISSUE THREAD

**Issue by fedeas** [WoWManiaUK/Redemption#3785]
Hey
I've recently replaced my ordinary starting bags with netherweave ones from the guild vault and since then every item that goes in those bags is disappearing
I've talked to a gm cleared the cache files run the launcher as administrator but nothing seemed to be working  
Thanks in advance,
Endorth

**Comment by Kitzunu** [comment]
This could be because of 2 reasons
1. You are using 2 bag addons at the same time
2. Bagnon (an addon) is bugged.

Nothing disapears. Its just visual. But most likely an addon issue that you have to look into :)

**Comment by jarvik76** [comment]
This is a visual-only issue, when a new bag is replaced.  The items are not lost, they are just not cached visually.  Usually a relog sorts this, or swapping the bag places around.
Can you confirm if you were using Bagnon or Arkinventory addons (or both!) ?

**Comment by billykitty** [comment]
I don't have either of those addons, or any bag addons, and I have to restart with a clear cache to see the items.
