### ISSUE TITLE
Wintergrasp Tower Cannon

### ISSUE THREAD

**Issue by shevsea** [WoWManiaUK/Redemption#3787]
**Links:**
https://www.wowhead.com/npc=28366/wintergrasp-tower-cannon#comments

**What is Happening:**
In the middle of battle/fight, Wintegrasp Tower Cannon(WTC) with 50% HP (for example), players of the opposite faction jump out from the cannon so it regenerates life to 100% HP and they jump back again.

**What Should happen:**
Wintegrasp Tower Cannon(WTC) should not regenerate life in the middle of battle even if a person jumps out. I dare to say, they should not even regenerate life at all because they have a short ~5min spawn rate.

**Comment by Kitzunu** [comment]
Known issue.
Devs know about it, GMs don't want it on Github.

I will Close it, but it wont be forgotten :)
