### ISSUE TITLE
Bugged voting system

### ISSUE THREAD

**Issue by kabanefv** [WoWManiaUK/Redemption#3788]
Hey WoWMania,
Im having this issue when trying to vote that i do all the steps, opening the tap clincking on the link, then checking that im not a robot and confirming the vote, even after doing all of that one by one site by site, im only getting 1 vote points, when i used to get 8. If u guys could help me solving that issue i would appreciate a lot.

Thanks for your time, 
pedrofv

**Comment by Kitzunu** [comment]
Not an ingame issue. 
But I will forward it to Janitor.

Thank you :)
