### ISSUE TITLE
[Quest/Item] Arete's Gate never despawning (Part of [Second Chances])

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#3789]
**Links:**https://www.wow-mania.com/armory/?quest=12847
https://www.wow-mania.com/armory/?item=40730

**What is Happening:** Arete's Gate (visually identical to a DK's death gate) spawned by using [Arete's Gate (Item 40730)](https://www.wow-mania.com/armory/?item=40730) never disappears unless a server restart happens. The quest is doable just fine, but it causes a bunch of death gates to amass inside the cathedral and those never despawn. (See picture)
![WoWScrnShot_121219_215424](https://user-images.githubusercontent.com/34783736/70766013-7fe88c00-1d2a-11ea-9c11-2710f75d6234.jpg)

**What Should happen:** The [death gates](https://www.wow-mania.com/armory/?item=40730) spawned in The Crimson Cathedral in Icecrown as part of the quest [Second Chances](https://www.wow-mania.com/armory/?quest=12847) should eventually despawn after some pre-determined timer.

**Comment by Rushor** [comment]
objects will now despawn after 3 minutes
