### ISSUE TITLE
[NPC] Bone Gryphon skills usable on all mobs

### ISSUE THREAD

**Issue by jarvik76** [WoWManiaUK/Redemption#3790]
**Links:**
NPC mount: https://www.wow-mania.com/armory/?npc=29414
used on quest: https://www.wow-mania.com/armory/?quest=12815
and has skills:
Frost Breath: https://www.wow-mania.com/armory/?spell=48766
Plague Strike: https://www.wow-mania.com/armory/?spell=54469
target NPC for skill:  Onslaught Gryphon Riders: https://www.wow-mania.com/armory/?npc=29333

**What is Happening:**
Player uses Bone Gryphon NPC on quest "No Fly Zone".  Quest is to use the NPC's "Frost Breath" and "Plague Strike" to kill Onslaught Gryphon Riders.
These skills should only hit the Riders, and should cause no damage to any other NPC, however they do currently cause damage to other NPCs

**What Should happen:**
These skills should ONLY hit the riders (NPC 29333), and cause no damage to any other NPC.
![image](https://user-images.githubusercontent.com/46089380/70800401-11481480-1da4-11ea-837e-5aa2fe60ca7e.png)

![](https://cdn.discordapp.com/attachments/525463124485210113/654839667790970890/unknown.png)

**Comment by Rushor** [comment]
missile trigger https://www.wow-mania.com/armory/?spell=74541

**Comment by Rushor** [comment]
only targets 29333 now.

**Comment by jarvik76** [comment]
While Frost Breath is fixed and only damages NPC 29333, Plague Strike still affects other NPCs

**Comment by wow-mania** [comment]
Please mark this as tweaking if the general functionality works and if it doesn't obstruct progress.

**Comment by Rushor** [comment]
need to add spellscript for that. work in progress now

**Comment by Rushor** [comment]
okay done. only on https://i.imgur.com/eenFk21.jpg now
