### ISSUE TITLE
[Talent] Improved Water Shield does not properly proc from Lesser Healing Wave

### ISSUE THREAD

**Issue by jarvik76** [WoWManiaUK/Redemption#3791]
**Links:**
Talent:  https://www.wow-mania.com/armory/?spell=16198
LHW spell (rank 1):  https://www.wow-mania.com/armory/?spell=8004
LHW spell (rank 2):  https://www.wow-mania.com/armory/?spell=8008
LHW spell (rank 3):  https://www.wow-mania.com/armory/?spell=8010
LHW spell (rank 4):  https://www.wow-mania.com/armory/?spell=10466
LHW spell (rank 5):  https://www.wow-mania.com/armory/?spell=10467
LHW spell (rank 6):  https://www.wow-mania.com/armory/?spell=10468
LHW spell (rank 7):  https://www.wow-mania.com/armory/?spell=25420
LHW spell (rank 8):  https://www.wow-mania.com/armory/?spell=49275
LHW spell (rank 9):  https://www.wow-mania.com/armory/?spell=49276

**What is Happening:**
Lesser Healing Wave is not proccing the talent Improved Water Shield (16918) properly.

On hit, water shield consumption restores 492 mana. 

On testing, from 200 **critical** heals from LHW, it procced only 13 times (~6.5%).    (This should be 60%, as per the talent.)
When it does so, it restores 600 mana (108 mana too much).
This happens on all ranks of LHW spell.

The Healing Wave and Chain Heal portions of the talent are proccing at the expected rate and value  (100% and 30% respectively)

**What Should happen:**
As per the talent:
> You have a 
> - 100% chance to **instantly gain mana as if you consumed a Water Shield Orb** when you gain a critical effect from your Healing Wave or Riptide spells, 
> - a **60% chance when you gain a critical effect from your Lesser Healing Wave spell,** 
> - and a 30% chance when you gain a critical effect from your Chain Heal spell.
![image](https://user-images.githubusercontent.com/46089380/70841014-bef00d80-1e0e-11ea-9435-bbd25e04a434.png)

**Comment by Kitzunu** [comment]
Confirmed by @Dranah
