### ISSUE TITLE
[Quest] Abduction

### ISSUE THREAD

**Issue by leon20000026** [WoWManiaUK/Redemption#3821]
**Links:**
![WoWScrnShot_121519_075843](https://user-images.githubusercontent.com/58900394/70859236-c992cb80-1f10-11ea-90ba-d8da18437ce8.jpg)

**What is Happening:**
The Sorcerer that i have to capture is Green like an normal NPC so i cant hit him low to use the Arcane Binder.

**What Should happen:**
The Sorcerer schould get damage so i can capture him.

**Comment by leon20000026** [comment]
And der are only Captured Beryl Sorcerer

**Comment by Rushor** [comment]
maybe a resetting issue

**Comment by wow-mania** [comment]
https://www.wow-mania.com/armory/?quest=11590

**Comment by wow-mania** [comment]
Seems to work fine for me. Maybe someone left halfway through the quest

**Comment by Rushor** [comment]
creatures does not despawn if a player simply leaves the zone.

will now be active once captured and despawn after 5 minutes no matter if player is there or not.

**Comment by Rushor** [comment]
117775

**Comment by Fourlugas** [comment]
Last comment says creatures will despawn after 5 min.  It's been 20 min and these 2 are still up.  not despawning so more will spawn.

**Comment by Fourlugas** [comment]
I'm sorry correction.  I found a 3rd that hasn't despawned now

**Comment by Kitzunu** [comment]
It is not on live yet.
once the issue is closed these changes will be present on the live server :)
