### ISSUE TITLE
[NPC/Event] Morshelz Copperpinch - 23011 - Silvermoon City

### ISSUE THREAD

**Issue by jarvik76** [WoWManiaUK/Redemption#3822]
**Links:**
https://www.wow-mania.com/armory/?npc=23011

**What is Happening:**
Morshelz Copperpinch is not present in the Silvermoon Smokeywood Pastures vendor location.
![WoWScrnShot_121519_110247](https://user-images.githubusercontent.com/46089380/70861808-2ef3b600-1f2b-11ea-821e-64cb1fd56a1e.jpg)

**What Should happen:**
Morshelz Copperpinch should be present in the Silvermoon Smokeywood Pastures vendor location.  (Around 63.6,78.4 in Silvermoon)
https://www.wowhead.com/npc=23011/morshelz-copperpinch

**Comment by jarvik76** [comment]
Also, Hotoppik also missing from same location.
https://www.wowhead.com/npc=23012/hotoppik-copperpinch

**Comment by Rushor** [comment]
Okay will fix

**Comment by Rushor** [comment]
both added https://i.imgur.com/m9KX3rV.jpg
