### ISSUE TITLE
[Quest] Jungle Secrets

### ISSUE THREAD

**Issue by Afterdarknes** [WoWManiaUK/Redemption#3823]
**Links:**

**What is Happening:**
I can no longer obtain this quest from Private Thorsen. He has a yellow ! mark on him, but gives no quest.

**What Should happen:**
Private Thorsen should give the quest Jungle Secrets
![WoWScrnShot_121519_084332](https://user-images.githubusercontent.com/58676235/70863686-a8ce7400-1f18-11ea-9425-fd0936e14ed0.jpg)

**Comment by Rushor** [comment]
http://cata.cavernoftime.com/npc=738

**Comment by Rushor** [comment]
reduced the time until he starts his path.

was: after respawn start path after 600 seconds

now: start path after 5 seconds.

**Comment by Rushor** [comment]
https://i.imgur.com/nKU9tjY.jpg
