### ISSUE TITLE
[object] Apexis Monument - wrong text

### ISSUE THREAD

**Issue by WhitephoenixTheBunny** [WoWManiaUK/Redemption#3824]
The quest [Guardian of the Monument](https://www.wow-mania.com/armory/?quest=11059) requires to click on the [Apexis Monument](https://www.wow-mania.com/armory/?object=185944) and start ann event.

ATM the gossip information given is wrong, it says "an apex shard" is required, when is actually 35 apexis shards required.

Mania: 
![image](https://user-images.githubusercontent.com/31921098/70865332-45face00-1f54-11ea-9d03-f2425ad7dd3f.png)

From a youtube video:
![image](https://user-images.githubusercontent.com/31921098/70865342-5ad76180-1f54-11ea-9dbe-0c704e642f26.png)

**Comment by Rushor** [comment]
"Insert 35 Apexis Shards, and begin!", GOSSIP_SENDER_MAIN, 0);
