### ISSUE TITLE
Quest in Borean Tundra "Abduction"

### ISSUE THREAD

**Issue by Fourlugas** [WoWManiaUK/Redemption#3825]
**Links:**

**What is Happening:**
Supposed to find a Beryl Sorcerer and capture.  

**What Should happen:**
There is only one Beryl Sorcerer standing alone that is already captured and green con.  Can't interact with.  No others will spawn.

**Comment by Kitzunu** [comment]
resetting issue. 
Duplicate https://github.com/WoWManiaUK/Redemption/issues/3821

**Comment by Fourlugas** [comment]
Ok thanks.  That ticket shows closed 4 hrs ago and that these mobs will despawn.  It's been at least 20 min and they are not despawning.  Not a huge issue other than it keeps from going to the dome area.

**Comment by Kitzunu** [comment]
https://github.com/WoWManiaUK/Redemption/issues/3821#issuecomment-565842484
