### ISSUE TITLE
[Item] Reindeer Reins

### ISSUE THREAD

**Issue by Kitzunu** [WoWManiaUK/Redemption#3830]
**What is Happening:**
Currently, Reindeer Reins (21044) applies the aura (25675)

**What Should happen:**
Reindeer Reins (21044) should apply aura (25858)

**Comment by Rushor** [comment]
if you need any help let me know :>

**Comment by Kitzunu** [comment]
Well, I have no idea how to fix this :P 
So feel free to teach me or do it yourself @Rushor

**Comment by Rushor** [comment]
it is ahndled in `spellid_1` in item_template

**Comment by Kitzunu** [comment]
Was just to say I found the correct spell there XD

you fixing it explains it haha
