### ISSUE TITLE
[Spell] Reindeer + Festive Holiday Mount

### ISSUE THREAD

**Issue by Kitzunu** [WoWManiaUK/Redemption#3831]
**What is Happening:**
When you have the Reindeer (25858) on you and then apply the Festive Holiday Mount (62061) aura the model of Festive Holiday Mount will not appear.

(Festive Holiday Mount comes from the item Preserved Holly (21213))

![image](https://user-images.githubusercontent.com/24550914/70913271-009ed500-2016-11ea-87a6-c73de7b7945d.png)

**What Should happen:**
If you are under the aura Reindeer (25858) and use Preserved Holly for the aura (62061) the model of that reindeer mount should be changed to the "festive" model and not disappear.

**Comment by Rushor** [comment]
case 62061: // Festive Holiday Mount
                    if (target->HasAuraType(SPELL_AURA_MOUNTED))
                    {
                        uint32 creatureEntry = 0;
                        if (apply)
                        {
                            if (target->HasAuraType(SPELL_AURA_MOD_INCREASE_MOUNTED_FLIGHT_SPEED))
                                creatureEntry = 24906;
                            else
                                creatureEntry = 15665;
                        }
                        else
                            creatureEntry = target->GetAuraEffectsByType(SPELL_AURA_MOUNTED).front()->GetMiscValue();

                        if (CreatureTemplate const* creatureInfo = sObjectMgr->GetCreatureTemplate(creatureEntry))
                        {
                            uint32 displayID = ObjectMgr::ChooseDisplayId(creatureInfo);
                            sObjectMgr->GetCreatureModelRandomGender(&displayID);

                            target->SetUInt32Value(UNIT_FIELD_MOUNTDISPLAYID, displayID);
                        }
                    }

is the current code. maybe sth wrong there?

**Comment by Kitzunu** [comment]
To clear:
It works as it should for normal mounts.

**Comment by Keader** [comment]
Test now

**Comment by Kitzunu** [comment]
Now it doesn't make it disappear, but it doesn't add the "festive" version to the mount either.

**Comment by Kitzunu** [comment]
![image](https://user-images.githubusercontent.com/24550914/70922365-46639980-2026-11ea-9e01-fe5823ddf9bb.png)
how it is

![image](https://user-images.githubusercontent.com/24550914/70922384-524f5b80-2026-11ea-94e0-bdefb827ac45.png)
how it should be

**Comment by Keader** [comment]
It's wrong...
Fly version should only work for flying mounts o.o

**Comment by Kitzunu** [comment]
Doesn't says it is a fly version though. Only "mount" and it works for ground mounts

**Comment by Kitzunu** [comment]
My mistake :D
