### ISSUE TITLE
Corps 4000 yards away

### ISSUE THREAD

**Issue by hondaerazor** [WoWManiaUK/Redemption#3833]
**Links:**

**What is Happening:**
I died wile riding over a mountain. My coprs is now 4000 yards away and i cant find it. Even the map does not show anything. There´s no button to get back to graveyard. Even i would not help. because my ghost cant get to my body.

**What Should happen:**
I should find my body.
Please help me. My ingame Name is Rumors. A level 27 Paladin in the Alliance.

**Comment by Kitzunu** [comment]
1. Please tell us where this mountain is located.
2. screenshots please.
3. Make an ingame ticket to get help by a GM to get ressed :)

I will close this until there is more info added.
