### ISSUE TITLE
[Quest] It's All Fun and Games - Icecrown

### ISSUE THREAD

**Issue by Sparky1387** [WoWManiaUK/Redemption#3835]
**Links:**

**What is Happening:**
when trying the "It's All Fun and Games" quest, the target monster "The Ocular"apears dead, it attacks me, when i try to attack it is give the "Invalid Target"message.
please fix. thank you

**What Should happen:**
In the "It's All Fun and Games" quest you are sent to kill "The Ocular" then report to Baron Sliver at the Shadow Vault to complete the Quest.

**Comment by Kitzunu** [comment]
@Rushor Could you check, please. This is a resetting issue that has been ignored in previous reports.

**Comment by Sparky1387** [comment]
i have checked a few moments ago. The Ocular still apears Dead and untargetable untill he attacks you.

**Comment by Kitzunu** [comment]
@Sparky1387 Make a ticket and a GM will help you, this will be fixed soon for other players :)

**Comment by Sparky1387** [comment]
one of the GM's already helped me. he was the one who told me to post it here so that other players may not have the same problem as me. ^^

**Comment by Kitzunu** [comment]
Great!
Thank you for your help @Sparky1387 !

And Merry Christmas or Happy Holidays!

**Comment by wow-mania** [comment]
Most definitely work.

**Comment by Kitzunu** [comment]
It is a resetting issue, like a lot of other quests.
so it needs fixing.

**Comment by Rushor** [comment]
tada https://i.imgur.com/IhgIUdB.jpg

it was missing health reggen on on reset

**Comment by Sparky1387** [comment]
Happy to see problems geting fixed. ^^ well done boys!!!
