### ISSUE TITLE
[Event/NPC/Quest] Winter Veil Quest "You're A Mean One" no longer offering Smokywood Pastures Thankyou

### ISSUE THREAD

**Issue by jarvik76** [WoWManiaUK/Redemption#3836]
**Links:**
Horde:
https://www.wowhead.com/quest=6983/youre-a-mean-one
https://www.wowhead.com/quest=6984/a-smokywood-pastures-thank-you
https://www.wow-mania.com/armory/?quest=6983
https://www.wow-mania.com/armory/?quest=6984

Alliance: 
https://www.wowhead.com/quest=7043/youre-a-mean-one
https://www.wowhead.com/quest=7045/a-smokywood-pastures-thank-you
https://www.wow-mania.com/armory/?quest=7043
https://wow-mania.com/armory/?quest=7045

**What is Happening:**
Since the changes on #3832, completing Quest 6983 "You're a mean one" is no longer offering 6984 "Smokywood Pastures Thankyou".  This means the "Simply Abominable" Achievement is also locked out.
![image](https://user-images.githubusercontent.com/46089380/71038460-c880ba80-2119-11ea-9c4c-462b57e6c215.png)

**What Should happen:**
Completing 6983 should offer 6984 as follow-up

**Comment by Rushor** [comment]
same on cata right now. daily quests prevent the chaining?

**Comment by Kitzunu** [comment]
I think so. 
Because it works if I remove the flag.

**Comment by Kitzunu** [comment]
I have reverted You're a Mean One... so it is not repeatable. Should fix the issue

**Comment by Kitzunu** [comment]
![image](https://user-images.githubusercontent.com/24550914/71042167-5022f500-212b-11ea-8159-199a6f00a0e5.png)
