### ISSUE TITLE
[Core/Auctionhouse] Pending Mail

### ISSUE THREAD

**Issue by Kitzunu** [WoWManiaUK/Redemption#3839]
1.
**What is Happening:**
Currently the Pending Mail does not have an estimated delivery time.

![pendingmail](https://user-images.githubusercontent.com/24550914/71044472-02f65180-2132-11ea-944c-a92d86647530.JPG)

**What Should happen:**
The Pending Mail should have an estimated time shown for when your ingame gold is supposed to arive. So the time should be `time item sold on auctionhouse + MailDeliveryDelay`
so it looks like this:
![pendingmailworks](https://user-images.githubusercontent.com/24550914/71044570-418c0c00-2132-11ea-83bd-ff25fa70e11b.JPG)

 MailDeliveryDelay is in worldserver.conf
ex: Item sold 13:00 and MailDeliveryDelay = 1800 it would be 46,800 + 1800 = 13:30 (since it is calculated in seconds)

2.
**How it works:**
When the "Time until message is deleted" is = to 0 the message does not get deleted.
![time left](https://user-images.githubusercontent.com/24550914/71044615-6bddc980-2132-11ea-9454-3f85aa8ca402.JPG)
![image](https://user-images.githubusercontent.com/24550914/71044610-67191580-2132-11ea-888e-692a08485fc1.png)

after a while it goes to the "normal" duration of a mail being delated 
![image](https://user-images.githubusercontent.com/24550914/71203216-e0814700-229d-11ea-8ce3-ee6b45b27c7a.png)

**How it should work:**
When the time on the Pending Mail from the auctionhouse is = 0 it should be deleted from the recipients mailbox.

**NOTE:**
Issue 2 is ONLY for auctionhouse mail. It works as intended for "normal" mail.

*Reported by GM & Player, confirmed by me.*

**Comment by Rushor** [comment]
I have a fix for the timer of you wish

**Comment by Rushor** [comment]
sale pending timer fixed

**Comment by Rushor** [comment]
@Keader done in SendAuctionSalePendingMail 

maybe you can handle the delete then?

**Comment by Kitzunu** [comment]
Not fixed.
Currently it is `time on auction house sell` only. Should be 
`time item sold on auction house + MailDeliveryDelay`
![image](https://user-images.githubusercontent.com/24550914/71203107-b039a880-229d-11ea-9122-80ddefbe8c12.png)

**Comment by Rushor** [comment]
okay will check again tomorrow

**Comment by Keader** [comment]
Test now please
Changed to get auctionTime + DeliveryMails
And added delete mail method.
It will deleted, 1 minute after mail get expired (because it update each 1 minute lul)

**Comment by Kitzunu** [comment]
1. Not fixed, because I bought it on Realm Time 14:12 and estimated time is 11:20 xd
![image](https://user-images.githubusercontent.com/24550914/71322933-7fd85100-24cd-11ea-97df-03defa4bbeb7.png)

2. Works now.

**Comment by Kitzunu** [comment]
![image](https://user-images.githubusercontent.com/24550914/71325854-284cdc00-24f3-11ea-98dc-967799cbd416.png)
1. & 2. Fixed :)

**Comment by Kitzunu** [comment]
It will show the estimated time in **Server Time** and works with the 24-hour mode on or off.
It will NOT adapt to your local time if you have that time option selected. Keep that in mind :)
