### ISSUE TITLE
[NPC] Grunt Ragefist

### ISSUE THREAD

**Issue by BeakerGoBoom** [WoWManiaUK/Redemption#3892]
Grunt Ragefist in the Borean Tundra seems to be permanently dead. I have not seen him alive in at least 2 days.

https://www.wow-mania.com/armory/?npc=25336

Thank You.

**Comment by Rushor** [comment]
Will fix

**Comment by Rushor** [comment]
fixed with next update. all envoled creature will have healthregen on on respawn

**Comment by Grunow** [comment]
Report to Steeljaw's Caravan the quest giver doesn't show and i need thes last 2 quests to complete achevement
I see Grunt Ragefist is dead and he is not respawning 12-26-19
