### ISSUE TITLE
[NPC] Silvermoon Harry

### ISSUE THREAD

**Issue by Reckful29** [WoWManiaUK/Redemption#3908]
https://www.wowhead.com/npc=24539/silvermoon-harry

The NPC is permanently dead and does not respawn. Its present is necessary for completing chain quests in Howling Fjord.

Should be alive.

**Comment by Rushor** [comment]
Fixed

**Comment by Reckful29** [comment]
Sorry, but nothing is fixed. The NPC is still lying dead in the tent and not respawning alive.

**Comment by WhitephoenixTheBunny** [comment]
@Reckful29 Fixed in Dev means is fixed on PTR and need to be applied on live (redemption)

**Comment by Reckful29** [comment]
Okay, sorry then.
