### ISSUE TITLE
Quest : call of fire (shaman fire totem quest)

### ISSUE THREAD

**Issue by benoitvm** [WoWManiaUK/Redemption#3909]
http://www.wow-mania.com/armory?quest=1522 
Start at npc http://www.wow-mania.com/armory?npc=5892

What is Happening:  The quest was available at level 10 ( I didn't try to do the quest right away)but disappeared when other quest came on.
I'm lvl 47 and still no call of fire quest.?

thx

**Comment by WhitephoenixTheBunny** [comment]
Did you checked others quest giver on horde? And questline?

**Comment by WhitephoenixTheBunny** [comment]
Can you also tell your race?

**Comment by Kitzunu** [comment]
Will close until more info is added, cuz I can't reproduce it.

it will only be gone if you complete one of these quests before.
quest_template
---
```sql
SELECT id, logtitle FROM quest_template WHERE id IN (1522, 1523, 2983, 2984)
```
| id | logtitle | 
| ---: | --- | 
| 1522 | Call of Fire | 
| 1523 | Call of Fire | 
| 2983 | Call of Fire | 
| 2984 | Call of Fire |

**Comment by benoitvm** [comment]
I m a troll shaman , so i have checked Sean Firewarder in Ogrimmar : http://www.wow-mania.com/armory?npc=5892 no quest
      , Narm Skychaser in thunder bluff : http://www.wow-mania.com/armory?npc=3066, no quest
     , Swart in Durotar : http://www.wow-mania.com/armory?npc=3173 , no quest 
I have done call of water at lvl 20 http://www.wow-mania.com/armory?quest=1528   and call of air at lvl 30 http://www.wow-mania.com/armory?quest=1531 
thx

**Comment by Kitzunu** [comment]
ok will recheck. Thanks for the additional information :)

**Comment by Kitzunu** [comment]
For the time being, make a ticket ingame and a GM can help you
