### ISSUE TITLE
[Item] Dark Armor Plate

### ISSUE THREAD

**Issue by moranon** [WoWManiaUK/Redemption#3910]
The Stormforged War Golems should drop the item "Dark Armor Plate" (http://www.wow-mania.com/armory?item=42203) with a 100% chance. After killing of like 30 still no item drop.
I tried different spawn spots under the supervision of an gm.
The item is needed to start a quest.

**Comment by Kitzunu** [comment]
conditions
---
```sql
SELECT comment FROM conditions WHERE sourceentry = 42203
```
| comment | 
| --- | 
| Dark Armor Plate drops if Facing the Storm taken | 
| Dark Armor Plate drops if Facing the Storm rewarded | 
| Dark Armor Plate drops if Armor of Darkness isn't rewarded | 
| \0 | 

conditions to make the item drop.

**Comment by Rushor** [comment]
This item still drops after completing the two quests mentioned above. I almost had a heart attack when I heard that you had to be on the quests to get this. But fear not loremasters to be! My first kill after turning in those quests, this item dropped.
https://www.wowhead.com/item=42203/dark-armor-plate#comments:id=1109838

conditions are confusing - will remove them, so only condition:
Dark Armor Plate drops if Armor of Darkness isn't rewarded - will remain.

**Comment by Rushor** [comment]
https://i.imgur.com/mMmWvNE.jpg
