### ISSUE TITLE
[Quest] The Murketh and Shaadraz Gateways

### ISSUE THREAD

**Issue by JonW98223** [WoWManiaUK/Redemption#3911]
**Links:**
https://imgur.com/a/JvYXDJU

**What is Happening:**
When I try to turn in quest that I have completed, it doesn't let me turn it in. I have each item completed, and yet the question mark above his head is not yellow like on the map.

**What Should happen:**
NPC should grant completion of quest so I can move on to the next step.

**Comment by Rushor** [comment]
https://i.imgur.com/kdffYfz.jpg works for me.
rember to be NOT in a raid group

try to redo the quest and type in 
/scipt LeaveParty()
