### ISSUE TITLE
[Quest] Rescuing the Rescuers (Alliance)

### ISSUE THREAD

**Issue by Feuerwiesel** [WoWManiaUK/Redemption#3912]
**Links:**
https://github.com/WoWManiaUK/Redemption/issues/3743

**What is Happening:**
The harpoons that hold down the scouts do not respawn.

**What Should happen:**
The harpoons for the quest should respawn at a relatively fast rate.
It is a crucial quest that has to be done by everyone starting in the Howling Fjords.

**Comment by Rushor** [comment]
i have tried to fix this quest so ften now.. what is the reason for not respawn?

**Comment by Kitzunu** [comment]
Maybe, if we cannot fix it in SAI, we make it c++?

**Comment by Kitzunu** [comment]
or maybe if we add spawns in `gameobject` for Ceremonial Dragonflayer Harpoon and link them to the SAI script and give them a `spawntimesecs` instead of having the SAI script respawning them?

**Comment by Rushor** [comment]
that is what was done before yes - will try

**Comment by Rushor** [comment]
the gameobjects now respawn independed from the creatures https://i.imgur.com/L5HM3o9.jpg

works for me so far.
