### ISSUE TITLE
[Quest] You, Robot

### ISSUE THREAD

**Issue by stealer0517** [WoWManiaUK/Redemption#3913]
https://www.wowhead.com/quest=10248/you-robot

I'm unable to turn in the quest despite killing the enemy robot (and getting the completion text) and still having the controller in my inventory.
The "Continue" box is still greyed out.

I've tried this quest multiple times in the past and it hasn't worked with the same issue.

**Comment by Rushor** [comment]
quest credit targeting for player fixed https://i.imgur.com/OdTpEru.jpg (with next update)
