### ISSUE TITLE
[Quest] The Conquest Pit: Bear Wrestling!

### ISSUE THREAD

**Issue by Sammasterthemad** [WoWManiaUK/Redemption#3914]
The pit of conquest which is a group arena is only marking "complete" for the player who gets the death blow in. So if you're doing a group of 3. You have to take turns beating the combatant and do it 3 times vs the one time like the other arena style fights like in Nagrand and Zul Drak.

**Comment by Kitzunu** [comment]
ok, I set it to 

SMART_TARGET_INVOKER_PARTY on Completion and Failing the quest. 
Should fix it

**Comment by Kitzunu** [comment]
https://www.wowhead.com/npc=27715/ironhide
https://www.wowhead.com/quest=12427/the-conquest-pit-bear-wrestling
