### ISSUE TITLE
Character bug

### ISSUE THREAD

**Issue by highjimmy** [WoWManiaUK/Redemption#3916]
i have Problem with my first Character ( Hijimmygh ) 
I choose them and it get out Game.
Another Character's are Ok,

can you help me ?

**Comment by WhitephoenixTheBunny** [comment]
Not an issue to Github, is mostlike an issue from client, follow those steps:
1. Move the wow client to the root of your driver (Ex.: c:\wow-mania)
2. Make sure that the file realmlist.wtf is NOT read-only
3. Make sure the client folder is not read-only either
4. Add the client folder to the list of exceptions of your anti-virus
5. Start Launcher as Admin
if you still bugged contact janitor
