### ISSUE TITLE
[Quest] Finding the Phylactery

### ISSUE THREAD

**Issue by jarvik76** [WoWManiaUK/Redemption#3917]
**Links:**
Quest: https://www.wow-mania.com/armory/?quest=11956
Object (phylactery): https://www.wow-mania.com/armory/?item=35687
Summons: https://www.wow-mania.com/armory/?npc=26225

**What is Happening:**
On using the object, there is a delay before the summoned NPC appears.  At first the phylactery becomes inactive, but then becomes active again, before the NPC spawns.  
There is no "speech" or other visual clues for the player that something is happening.
This means it is possible that if the object is used again that the NPC is summoned multiple times simultaneously.  When done at-level, this can cause significant difficulty for the player.

**What Should happen:**
The phylactery (opbject 35687) should remain inactive for longer - preferably until NPC or player is killed, alternatively at least until after the NPC is spawned.

**Comment by Rushor** [comment]
will fix

**Comment by Rushor** [comment]
object is 20 seconds (until boss spawned) inactive once activated now.
