### ISSUE TITLE
[Quest] Abduction - 11590

### ISSUE THREAD

**Issue by jarvik76** [WoWManiaUK/Redemption#3918]
**Links:**
https://www.wow-mania.com/armory/?quest=11590
https://www.wow-mania.com/armory/?npc=25474

**What is Happening:**
Since the fixes on #3821, the Captured Beryl Sorcerer does not detach from the player on quest completion.

**What Should happen:**
Captured Beryl Sorcerer should despawn on quest completion too.

**Comment by Rushor** [comment]
that was never implemented. will fix that aswell soon

**Comment by Rushor** [comment]
he despawns if you walk with him in front of this creature https://i.imgur.com/GX6ZCdW.jpg


anyway. he will always despawn after 360 seconds once player captured him. there is no other way to fix that sadly. will add lable as-is
