### ISSUE TITLE
[Quest] No Mere Dream - Druid 10965

### ISSUE THREAD

**Issue by jarvik76** [WoWManiaUK/Redemption#3930]
**Links:**
https://www.wow-mania.com/armory/?quest=10965

**What is Happening:**
On completing Quest ID 10964, the NPC speech is triggered correctly, but on completion of that speech the follow-up quest 10965 is not offered to the player.
Reset and respawn of the NPC did not seem to help.
![image](https://user-images.githubusercontent.com/46089380/71551013-b255e280-29d4-11ea-9251-c19f5b0ecc1f.png)

**What Should happen:**
After the speech from 10964 is finished, quest 10965 should be offered.
https://www.youtube.com/watch?v=plTFDCpzPYg

**Comment by Kitzunu** [comment]
You are required to have riding skill 300

https://www.wowhead.com/quest=10965/no-mere-dream#comments

![image](https://user-images.githubusercontent.com/24550914/71551197-a45a8e80-29e1-11ea-887b-e1d277e7d500.png)
