### ISSUE TITLE
[QUEST] Argent Tournament Quest

### ISSUE THREAD

**Issue by scuall8907** [WoWManiaUK/Redemption#3931]
Dear Dev,
First of all, this is not a blocking issue.
At the argent tornamet there is a quest line to get Champion of the Horde that begin from that quest [The Argent Tournament](https://www.wowhead.com/quest=13668/the-argent-tournament).
After beginning this quest chain you have to gather a few item [Aspirant's Seal](https://www.wowhead.com/item=45192/aspirants-seal) in order to the first step [Up To The Challenge](https://www.wowhead.com/quest=13678/up-to-the-challenge). To get this item you have to do 3 daily quest, 2 of this are fixed [Training In The Field](https://www.wowhead.com/quest=13676/training-in-the-field) and [Learning The Reins](https://www.wowhead.com/quest=13677/learning-the-reins) the third should be one for a pool of 3 quest [The Edge Of Winter](https://www.wowhead.com/quest=13675/the-edge-of-winter), [A Worthy Weapon](https://www.wowhead.com/quest=13674/a-worthy-weapon) and [A Blade Fit For A Champion](https://www.wowhead.com/quest=13673/a-blade-fit-for-a-champion).

As i have seen in the last week from [Magister Edien Sunhollow](https://www.wowhead.com/npc=33542/magister-edien-sunhollow) i receive only the quest [A Blade Fit For A Champion](https://www.wowhead.com/quest=13673/a-blade-fit-for-a-champion).

You can see a better description of the chain quest structure from [this link](https://www.wowhead.com/championing-the-argent-tournament#questline-an-aspirants-training).

I hope my report is clear, English is not my main language.

Thank you for the hard work.

**Comment by Rushor** [comment]
pool_template and pool_quest updates
