### ISSUE TITLE
[Quest] The Lost Mistwhisper Treasure

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#3932]
**Links:**https://www.wowhead.com/quest=12575/the-lost-mistwhisper-treasure
https://www.wowhead.com/npc=28105/warlord-tartek
https://www.wowhead.com/item=38601/mistwhisper-treasure
https://www.wowhead.com/npc=28114/mistcaller-soo-gan
https://www.wowhead.com/npc=28667/jaloot

**What is Happening:** I have completed the quest [[The Lost Mistwhisper Treasure]](https://www.wowhead.com/quest=12575/the-lost-mistwhisper-treasure) twice already on previous toons, but am just unable to do it now on my Human Warlock. Don't know if the pet is causing the issue or not. I get credit for both killing [Warlord Tartek](https://www.wowhead.com/npc=28105/warlord-tartek) and looting the [Mistwhisper Treasure](https://www.wowhead.com/item=38601/mistwhisper-treasure), but no matter in what order I get them, I am unable to turn-in to [Mistcaller Soo-gan](https://www.wowhead.com/npc=28114/mistcaller-soo-gan). Looting the treasure before or after killing Tartek doesn't change anything and having [Jaloot ](https://www.wowhead.com/npc=28667/jaloot) out the whole time doesn't seem to affect it either. Seems like the quest-complete NPC is not checking for conditions properly or something.
 
**What Should happen:** Killing Tartek and recovering the Mistwhisper Treasure completes the quest properly, and one should be able to turn it in at Mistcaller Soo-gan when the game says it is completed.

* Seems to be related to issue #837

**Comment by Rushor** [comment]
questcredit handling adjusted.
