### ISSUE TITLE
[QUEST] Kroshius' Infernal Core

### ISSUE THREAD

**Issue by Arie1990** [WoWManiaUK/Redemption#3935]
**Links:**
https://classic.wowhead.com/quest=7603/kroshius-infernal-core

**What is Happening:**
He is red (his bar), should be yellow/elite. Therefore i cannot use the quest item 'Fel fire' on him to complete the quest.

**What Should happen:**
Walk up to his remains, click on him, use 'Fel fire' quest item, then kill him.

**Comment by jarvik76** [comment]
Confirmed
![image](https://user-images.githubusercontent.com/46089380/71557496-db12c200-2a3e-11ea-8b3e-d6567eecf8a1.png)

**Comment by Rushor** [comment]
will do this differently -change position of dead creatures, spellgo will wok then, and init ai on creaste not on respawn of creature

**Comment by Rushor** [comment]
https://i.imgur.com/zRefLwe.jpg

castable now. the spellfocus go is at that position then

**Comment by Arie1990** [comment]
Sorry, but I have no idea what you just wrote. Can you explain what you mean and when it's done?
