### ISSUE TITLE
[Spell] Killing Spree - 51690 - Combat Rogue

### ISSUE THREAD

**Issue by jarvik76** [WoWManiaUK/Redemption#3936]
**Links:**
https://www.wow-mania.com/armory/?spell=51690
![image](https://user-images.githubusercontent.com/46089380/71557386-3a6fd280-2a3d-11ea-888b-abf85bd3d0f8.png)

**What is Happening:**
Roughly 50% of activations of the skill result in a 6th attack, and very occasionally a 7th and 8th attack have been witnessed.
This can be replicated on a naked and untalented rogue
6 killing spree attacks:
![image](https://user-images.githubusercontent.com/46089380/71557370-fe3c7200-2a3c-11ea-8181-8702791122ac.png)
6 killing spree attacks:
![image](https://user-images.githubusercontent.com/46089380/71557372-0399bc80-2a3d-11ea-8ef5-e44faeea8322.png)
8 killing spree attacks:
![image](https://user-images.githubusercontent.com/46089380/71557374-085e7080-2a3d-11ea-80f2-9071ff79e9ab.png)

**What Should happen:**
Killing Spree should attack only 5 times

**Comment by Kitzunu** [comment]
I have never witnessed that it attacks >5 times in fights, but I have witnessed that it attacks <5 times, for example, if you kill a target with 2 strikes, it won't search for a new target to execute the 3-5th strikes

**Comment by Keader** [comment]
It should do, 10 attacks, not 5 xD
5 assaults mean: 5 attacks from main hand, 5 attacks from off hand.
I fixed it to do the correct amount of assaults, if you dont miss xd

**Comment by Dranah** [comment]
Keader is right. Its 10x total attacks, but when it misses, it seems to miss with both weapons at once. Basically each miss = 2 attacks missing. I am not certain that's intended. It does properly 10 attacks now always when it does not miss.
