### ISSUE TITLE
[Core/Spells] Fixed CastSpell: unknown spell id 22540 error

### ISSUE THREAD

**Issue by Keader** [WoWManiaUK/Redemption#3937]
:)

**Comment by Aristo14** [comment]
Are these fixes to underlying core triggers or? Unclear to community what is fixed and how it effects gameplay. Personally it would be nice if you comment, on these kind of fixes, by very briefly stating what you did @Keader. Even if it's just "core issue, doesn't affect gameplay" 

Thanks for all the work and HNY
