### ISSUE TITLE
Pet bar disappears after exiting Wintergrasp Seige engine

### ISSUE THREAD

**Issue by jarvik76** [WoWManiaUK/Redemption#3939]
**Links:**
https://www.wow-mania.com/armory/?npc=28094
https://www.wow-mania.com/armory/?npc=28312
https://www.wow-mania.com/armory/?npc=27881

**What is Happening:**
Sometimes, Warlock pet bar disappears after exiting a Wintergrasp siege engine.  Witnessed in all three WG engines.
Is intermittent - in testing it sometimes happened 1st exit after summoning pet, or could take 10-12 exits.
/reload does not help, pet bar is still missing.
Have replicated using Voidwalker, Imp and Felhound.
https://youtu.be/hIKR8HJ1AOk?t=178
May be related to (very old ticket) #1648

**What Should happen:**
Pet bar should show every time after exiting seige engine, if it was summoned before entering.

**Comment by Kitzunu** [comment]
I have sent a possible fix to Janitor, when he makes it "fixed in dev" pls test it

**Comment by Keader** [comment]
i did it already lol

**Comment by Kitzunu** [comment]
Just to add info for anyone who is interested to know what causes this issue:

It is due to the opcode CMSG_REQUEST_PET_INFO is unhandled.
This also caused the /reload not to load the pet bar.

**Comment by Keader** [comment]
In this case, miss handle of CMSG_REQUEST_PET_INFO not cause this specific issue.
But... help solve alot of issues, typing /reload on chat.
Anyway, still working in a solution of this issue.

**Comment by Keader** [comment]
Ok i made a fix, not work in 100% of cases, it still can bug sometimes.
But... now you can make it work using /reload any time. (yeah, it bugs sometimes on blizzard too, yay).

**Comment by jarvik76** [comment]
Well.  reload does fix it now, but the bar still disappears quite regularly.  In 30 dismounts it happened 7 times.  Is there no other fix possible?

**Comment by Keader** [comment]
client just ignore the server packet
server send the packet with the bar
client get the packet
and just ignore the packet
/reload or mount again is the only thing that desbug it.
