### ISSUE TITLE
[Quest] Rampage - 12721 - Zul'drak

### ISSUE THREAD

**Issue by jarvik76** [WoWManiaUK/Redemption#3941]
**Links:**
Quest:  https://www.wow-mania.com/armory/?quest=12721
Akali Anchor Chain:  https://www.wow-mania.com/armory/?object=191018
Akali:  https://www.wow-mania.com/armory/?npc=28952

**What is Happening:**
Akali is somehow gotten stuck in place, inactive, not killing the mobs. 
Using the Akali Anchor Chain has no effect.  (Looks visually like the chains have already been removed after a previous player has completed the quest.)
![image](https://user-images.githubusercontent.com/46089380/71601630-35e60f80-2b4c-11ea-8eec-8a50bc92a865.png)

However am having troubles replicating the exact cause on PTR. Seems to work there after several tries.  GM Psygoa asked to have it logged in github and refused to reset the event in Redemption.  Am doing so for visibility in case other testers/devs have more luck or already have ideas around the cause.

**What Should happen:**
Akili should kill the summoned mobs and despawn, resetting for the next player

**Comment by Rushor** [comment]
so the stucking is only happening on live realm?

**Comment by jarvik76** [comment]
Well I guess there must be SOME condition that makes it stick.  But i can't find what it is on test server.  Tried a number of times and it worked fine.

**Comment by jarvik76** [comment]
Ok.  so after he was reset by GM, he came loose on the rampage after only one chain being undone.  Then, the Prophet of Akali 28996 ran in, yelled his scripted speech "ENOUGH!", and Akali just stood there again.

![image](https://user-images.githubusercontent.com/46089380/71603418-9e38ef00-2b54-11ea-95bf-4ca9a9301ab1.png)

**Comment by wow-mania** [comment]
pretty sure this works fine

**Comment by Rushor** [comment]
Okay i will check. I guess we need to load the grid for fight to Not get stuck

**Comment by wow-mania** [comment]
This quest has been working for ages and, of course, there will be some extreme cases where it may fail.
In those cases, player will have to just drop and retake quest.

**Comment by jarvik76** [comment]
That did not help in this case. Akali remained bugged out and the event did not reset.

**Comment by jarvik76** [comment]
Could it be a byproduct of https://github.com/WoWManiaUK/Redemption/issues/3893?

**Comment by Rushor** [comment]
@jarvik76 no because that addition actually made him work again. before the change he never respawned.

**Comment by Rushor** [comment]
okay issue is that the endevent is triggere by spellcast of http://cata.cavernoftime.com/spell=52859

But the spell is not correctly casted upon jumping of the prophet. Fixed this now.

**Comment by Rushor** [comment]
https://i.imgur.com/SPR5Qgg.jpg
