### ISSUE TITLE
[Spell/Interaction] Disorient effects delay hunter traps

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#3942]
https://classic.wowhead.com/spell=19503/scatter-shot
https://classic.wowhead.com/spell=2094/blind
https://classic.wowhead.com/spell=1499/freezing-trap
https://classic.wowhead.com/spell=13813/explosive-trap
https://www.wowhead.com/spell=43449/snake-trap
https://classic.wowhead.com/spell=13809/frost-trap

**What is Happening:**

When the target is afflicted by a disorient effect such as Scatter shot, or Blind, any hunter traps placed underneath them cannot activate until the effect makes the next movement direction change. (even if the target is rooted and unable to move - the same time frame needs to pass, as the way the disorient is moving the character normally)
This has two possible outcomes: 
1) Either the trap lands with a delay, when the disoriented target changes direction and it triggers the trap.
2) If the disorient ends before finishing the next cycle of movement (broken by damage or having PVP talents that reduce the effect duration), it is possible to simply move away from the trap without it activating at all. (even though you were in range of it for long enough that it should have activated)

Both outcomes are gamebreaking in PVP scenarios and mean a huge disadvantage to hunters trying to CC.

Note: when the trap is placed or shot under target with no disorient effect active, the activation is instant as intended.

**What Should happen:**
Traps should activate instantly even if the target in range is afflicted by a disorient effect.

I can only imagine that the disorient somehow prevents the trap from checking for the character's position until the next movement is made.
NOTE2: this problem might somehow be related to the visual issue that disorients cause, but since that was claimed to be client-side, I can't imagine how it could interact with traps behavior.

**Comment by Aristo14** [comment]
Can confirm, this indeed makes scatter-trapping difficult and easy to avoid.

**Comment by Keader** [comment]
I dont have knowledge to fix it.
It's a ancient issue in TC (since 2011).
Is caused by a desync in clientside/serverside movements.
