### ISSUE TITLE
[Spell/Mechanic] Health Leech effects ignoring absorbs

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#3943]
https://www.wowhead.com/item=50415/bryntroll-the-bone-arbiter
https://www.wowhead.com/spell=71838/drain-life
https://classic.wowhead.com/spell=28412/death-coil

**What is Happening:**
Effects that leech health from enemies do not consider absorption effects and will do full healing even if the damage is partially or fully absorbed. Examples are in the above links, most notably Bryntroll's proc effect and warlock's Death coil.

**What Should happen:**
Health Leeches must only work with actual damage dealt to the target. Absorbed damage is not damage dealt/taken. They should not return health based on damage that was absorbed.

PS: Several other talents and mechanics confirm that absorbed damage is not considered "damage dealt" or "damage taken". Basically no mechanics worded with "damage done/taken" involved will proc/work if said damage is absorbed and neither should leeches.

Other sources:
https://www.mmo-champion.com/threads/658331-Death-Coil-Not-Healing
https://wowwiki.fandom.com/wiki/Death_Coil_(warlock_ability) - note: this specifies that the horrify effect is still intact even if the damage is fully absorbed - the damage done is only a requirement for its healing, not the CC portion
Issue has been reported (and supposedly fixed) on TC too https://github.com/TrinityCore/TrinityCore/issues/23311

**Comment by Aristo14** [comment]
Bryntroll is a chance on hit though right? as long as it hits but is absorbed it can still proc the leech?

**Comment by Dranah** [comment]
It can proc off an attack that is absorbed, but if the damage of the leech proc is absorbed, it will not heal.

**Comment by Dranah** [comment]
Snatch that. There is a problem with partial absorbs.
Ok so, the healing now properly scales with the amount of non-absorbed damage done, whether it is fully or partially absorbed.
However the damage of the leech effect for both DC and Bryntroll pierces through the absorb if the absorb shield is lesser than the damage done. Basically they can't be partially-absorbed atm, if the shield would absorb just a portion of the damage, the absorb is removed but the spell still does full damage with reduced healing though, as if the damage was absorbed.
