### ISSUE TITLE
profession boost

### ISSUE THREAD

**Issue by rmdeewow** [WoWManiaUK/Redemption#3945]
**Links:**
caracter Nieto

**What is Happening:**
A few moments ago i bought for 300 mp the engineering profession but i did receive nothing, even after restarting the game i did not receive de engineering profession in my spellbook!!

**What Should happen:**
I aspected to receive de engineering profession in my spellbook so please can you help me in this now I lost 300 mp voting points!

Thanks in advance,
RMdeewow, Nieto

**Comment by WhitephoenixTheBunny** [comment]
you need learn the spell... visit a trainer on a Stormwind or Orgrimmar... 
Profission boost only boost your skill, you still need learn all recipes on trianers (azeroth, outland, northrend and drops / rep ones)
