### ISSUE TITLE
[Quest] Fate of the Titans - 12986 - Storm Peaks

### ISSUE THREAD

**Issue by jarvik76** [WoWManiaUK/Redemption#3946]
**Links:**
https://www.wow-mania.com/armory/?quest=12986

**What is Happening:**
There is a typo in the quest story speech during the Temple of Winter:
"Temple of Winter verified to be in tact".
![image](https://user-images.githubusercontent.com/46089380/71669268-03166400-2d64-11ea-8ddf-dbd27db3a423.png)

**What Should happen:**
Should read:  "Temple of Winter verified to be intact".

**Comment by jarvik76** [comment]
Also, "Temple of Order verified to be in tact".

**Comment by Rushor** [comment]
will fix

**Comment by Rushor** [comment]
https://youtu.be/uxFLWbMnM6s

check this vid, text is correct and from sniffs :)
