### ISSUE TITLE
Ingame champ Sneake

### ISSUE THREAD

**Issue by mropo85** [WoWManiaUK/Redemption#3947]
**Links:**
Ingame name Sneake

**What is Happening:**
Every time I login the game freezes. Made another char and this one is not freezing

**What Should happen:**
Nothing, just login and play

**Comment by mropo85** [comment]
I spend like a 120 pounds for rankup and gear. So hope you can fix this soon!

**Comment by Rushor** [comment]
pls write an ingame ticket and let a gm check your auras. could it be related to some addons you are using? just rying to help :>

**Comment by mropo85** [comment]
Cant, game freezes instantly like I said

**Comment by Drostthehunter** [comment]
Open it from your alt, maybe

**Comment by wow-mania** [comment]
This is a client issue. Contact support if you need help.
This repository is for server issues only.
