### ISSUE TITLE
[Object] Wild Mustard - 192827 - Dalaran

### ISSUE THREAD

**Issue by jarvik76** [WoWManiaUK/Redemption#3948]
**Links:**
https://www.wow-mania.com/armory/?object=192827

**What is Happening:**
During daily cooking quest 13107, there is a Wild Mustard (object ID 192827) at Dalaran 37.8,43.4 that is underneath the ground texture.
![image](https://user-images.githubusercontent.com/46089380/71736429-eacc4500-2e48-11ea-986c-d45e2565aabe.png)

**What Should happen:**
Wild Mustard object at this location should be above the ground texture, so it can be collected by player.

**Comment by Kitzunu** [comment]
fixed
