### ISSUE TITLE
[Spell] Death coil non-binary resists

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#3951]
https://classic.wowhead.com/spell=17926/death-coil

**What is Happening:**

Death coil is running on non-binary resistances, so if your target has shadow resistance it will cause partial resists to the damage of the spell, but not affect the healing done, or the horror effect.
The spell is able to critically hit, which also does not affect the healing done, causing a mismatch in the healing being 300% of the damage.

**What Should happen:**
Death coil should be a binary spell, which means it either lands or not - if it hits, it hits for full damage, heals for 300% of it, and horrifies the target, and if it misses (if not hitcapped), or is fully resisted (if not spell pen capped) that means it doesn't heal, and doesn't horrify either.
Should not be possible to crit, and should not be possible to partially resist the damage with the horrify effect being unaffected.

sources:
https://classic.wowhead.com/spell=17926/death-coil#comments
https://wow.gamepedia.com/Death_Coil_(warlock_ability)

**Comment by Keader** [comment]
Fix reverted... will not work.
We dont have Binary Resist implemented here
https://github.com/TrinityCore/TrinityCore/pull/18933

**Comment by Kitzunu** [comment]
Just to reference incase this would sometime be implemented https://github.com/WoWManiaUK/Redemption/issues/2961
