### ISSUE TITLE
[Spell] Geist Alarm ID: 70739 Icecrown Citadel

### ISSUE THREAD

**Issue by Drostthehunter** [WoWManiaUK/Redemption#3962]
**Links:**
https://www.wowhead.com/spell=70739/geist-alarm

**What is Happening:**
In the hall leading to Rotface and Festergut there are no invisible traps that activates once you step down on them.

**What Should happen:**
In Plagueworks aka Plague Quarter in the hall leading to 2 mentioned bosses, should be 2 Alarm Traps, known as Geist Trap, once stepped on them, they should summon a pack of Fleshrending reapers coming from your back, the traps can be disarmed and seen by rogues once they use the stealth, same as Alarm Traps present in hall leading to Lord Marrowgar. The traps looks like this:
![image](https://user-images.githubusercontent.com/43518434/71935487-319e9f80-31a7-11ea-8208-395098cb1c9e.png)

Its been confirmed before that traps can be seen on PTR but are not working, on live they are not even present. 
Here you can see the comment from retail explaining what does happen once you step down on them:
CaptMonkey on 2009/12/19 (Patch 3.3.0)

You're also partly wrong. There are 4 before Marrowgar, two in each room, like you said. However, there are 2, not 1, in the Plagueworks hallway before Putricide/Festergut/Rotface. These each summon a pack of geists which go down pretty easily with AoE spam, but are good for rep, if anyone in your party still needs it. And the same number of traps spawn in 10 and 25-man, if there was any doubt about that. Like others have said, just mark them with a smoke flare if you intend to trigger them rather than disarm.

**Comment by Rushor** [comment]
have a fix for that :)

**Comment by Rushor** [comment]
fix available once watcher is restarted

**Comment by Rushor** [comment]
12 geists will spawn now if you run over the traps. 2 traps exist.

**Comment by Dranah** [comment]
This is incorrect atm. Right now if you trigger either of the 2 geist traps, it will spawn all the 12 geists on you and then triggering the other trap will have no effect.
It should be 6 mobs for each trap, not 12 on one. Also, the traps must be possible to disarm by rogues' disarm trap.  https://classic.wowhead.com/spell=1842/disarm-trap
These traps cannot currently be dodged by walking around them, which means if the disarm cannot be fixed, it's better to not implement them at all (or reduce their trigger range drastically, so players have a means to dodge it)

**Comment by Rushor** [comment]
amount of spawned creatures reduced to 6 and trigger radius reduced to 4 yards

**Comment by Dranah** [comment]
The reduced range works great, you can dodge the traps if you hug the wall very close now.
The creatures are however still doubled. Now each trap spawns 12 of them, for a total of 24.

**Comment by Rushor** [comment]
hm for me it works good https://i.imgur.com/KJZdUAT.jpg

those spawns are already spawned by default - remember to kill them first.

after trap is activated it's only 6 per trap then > https://i.imgur.com/sree9H7.jpg

**Comment by Dranah** [comment]
Weird, it works now. I always clear the room xD
Anyway, looks good enough.
