### ISSUE TITLE
[NPC/Dungeon] Drakkari Rhino/Battle Rider setup in Gundrak (Normal+Heroic)

### ISSUE THREAD

**Issue by jarvik76** [WoWManiaUK/Redemption#3964]
**Links:**
Gundrak zone:  https://www.wow-mania.com/armory/?zone=4416
Drakkari Rhino (with 1x Drakkari Battle Rider): https://www.wow-mania.com/armory/?npc=29838
Drakkari Battle Rider (nm):  https://www.wow-mania.com/armory/?npc=29836

Drakkari Rhino  (with 3x Drakkari Raider):  https://www.wow-mania.com/armory/?npc=29931
Drakkari Raider (nm): https://www.wow-mania.com/armory/?npc=29982

**What is Happening:**
At the end of Gundrak Normal, just prior to final boss Gal'darah, there are 4 Drakkari Rhinos.  
![image](https://user-images.githubusercontent.com/46089380/71977878-de156b80-3211-11ea-97d2-7d0b8211c8f3.png)

The number and positioning is incorrect.  There should be only 3, and the front rider should be on the stairs, so that the two behind are not aggrod on the pull of the front rhino.
(Note:  this incorrect setup is also seen on Heroic version, but there are additional issues at same place with HC and uses different NPC IDs so for clarity will make separate ticket for HC version)

**What Should happen:**
 There should be only 3, and the front rider should be on the stairs, so that the two behind are not aggrod on the pull of the front rhino.
See video of Gundrak nm from March 2010 so patch 3.3.1, https://youtu.be/4GhwzON3h0I?t=208
There is additional evidence of same setup in a video of HC from same period: https://youtu.be/1YK7mqvU5os?t=472

Checklist:
- [ ] The middle back one is extraneous and should be removed (DB GUID 127111)
- [ ] Move front rhino to top of stairs between pillars (BD GUID 127207

![image](https://user-images.githubusercontent.com/46089380/71982543-9c3df280-321c-11ea-8a8b-ce3192d38779.png)

**Comment by jarvik76** [comment]
This is a different issue to that reported on #3965.

**Comment by Rushor** [comment]
done https://i.imgur.com/yh736YY.jpg
