### ISSUE TITLE
[NPC/Dungeon] Drakkari Battle Rider missing from Rhino in Gundrak Heroic

### ISSUE THREAD

**Issue by jarvik76** [WoWManiaUK/Redemption#3965]
**Links:**
Gundrak zone:  https://www.wow-mania.com/armory/?zone=4416
Drakkari Rhino (with 3x Drakkari Raider): https://www.wow-mania.com/armory/?npc=29931
Drakkari Raider (HC): https://www.wow-mania.com/armory/?npc=30934  (note:  this version of the NPC is not found in armory when doing text search)

Drakkari Rhino (with 1x Drakkari Battle Rider): https://www.wow-mania.com/armory/?npc=29838
Drakkari Battle Rider (HC): https://www.wow-mania.com/armory/?npc=30925  (note:  this version of the NPC is not found in armory when doing text search)

**What is Happening:**
At the end of Gundrak Heroic, just prior to final boss Gal'darah, there are 4 Drakkari Rhinos.  
Addtionally to the changes requested on #3964 , which should be replicated in HC too, there is an issue that in HC mode the riders are entirely missing, on all 3 rhinos.
![image](https://user-images.githubusercontent.com/46089380/71997350-a7e9e300-3235-11ea-98df-1b3df8dafd78.png)

In the normal version of the instance, these riders are present, they are a different ID, 29836.

**What Should happen:**
Additionally to changes on #3964, 
- [ ] The two Drakkari Rhino 29838 at the back should have 1x Drakkari Battle Rider 30925 as accessory
- [ ] The Drakkari Rhino 29931 on the stairs should have 3x Drakkari Raider 30943 as accessory.
![image](https://user-images.githubusercontent.com/46089380/71998301-44f94b80-3237-11ea-9d9c-7220d689af86.png)

**Comment by Rushor** [comment]
fixed https://i.imgur.com/Vy4wYXh.jpg
