### ISSUE TITLE
Lost Heirlooms

### ISSUE THREAD

**Issue by JonW98223** [WoWManiaUK/Redemption#3966]
**Links:**
I don't have any

**What is Happening:**
Yesterday, I was shuffling gear between all of my toons and even had deleted ones I didn't play much anymore. I even sent mail to the toons that were active because I didn't have room in my bank so I sent it to alts to place it in the alts bank until I needed it. After I was done playing for a while I made sure every item had a place in bags within my toon. After finishing there was some serious lag and I got disconnected. Upon getting logged back in the bags in which all of the items I had farmed including several heirloom pieces had disappeared from my bags. I didn't place them in the bank yet but was getting ready shortly before being disconnected.

**What Should happen:**
All heirlooms which I have purchased, there should be a record of all the items I have purchased.

**Comment by Kitzunu** [comment]
Make a ticket ingame
