### ISSUE TITLE
[NPC] Innkeepers in major cities now sell WoW-Mania's Mall Teleport Stone

### ISSUE THREAD

**Issue by Kitzunu** [WoWManiaUK/Redemption#3971]
Will now sell WoW-Mania's Mall Teleport Stone

**Comment by jarvik76** [comment]
Innkeeper Allison
Innkeeper Firebrew
Caregiver Breel
Innkeeper SaelienneInnkeeper Gryshka, Innkeeper Pala, Innkeeper Velandra, Innkeeper Jovia, Innkeeper Norman, Isirami Fairwind, Amisi Azuregaze, Uda the Beast, Ajay Green
