### ISSUE TITLE
[NPC] Azshir the Sleepless

### ISSUE THREAD

**Issue by tecnoturc** [WoWManiaUK/Redemption#3972]
**Links:**
https://www.wow-mania.com/armory/?npc=6490
https://classic.wowhead.com/npc=6490/azshir-the-sleepless#comments

**What is Happening:**
Only Iron Spine and Fallen Champion spawn together in Scarlet Monastery Graveyard after going into a new instance of Scarlet Monastery Graveyard 50 times. Azshir the Sleepless is not spawning.

**What Should happen:**
There should be a chance for Azshir the Sleepless to spawn.

**Comment by Rushor** [comment]
Will Fix

**Comment by Rushor** [comment]
only one of the three rares will spawn now. and missing rare spawn added.
