### ISSUE TITLE
Quest not working

### ISSUE THREAD

**Issue by QueenZessa** [WoWManiaUK/Redemption#3974]
The quest for paladins to receive their Resurrection spell is not working and wont show up on my paladin character. I started the one quest to get on the path to receive the quest but after it just disappeared. I am level 65 which means I should have it by now and I've also watched every guide video and none have worked since I believe it disappeared due to a bug. I hope there is some way to fix it since its really embarrassing going into raids and them realizing their healer cant even resurrect 
*My account is Zessa and my paladin's name is also Zessa

Have a great day!

**Comment by Kitzunu** [comment]
Did the quest just disappear or a quest item?

can you pick up the quest again from the quest giver?

**Comment by Kitzunu** [comment]
I will be closing this until you add more information that we can work with.

I am pretty sure it works, but anyhow if you answer the questions above I am more than happy to assist you :)
