### ISSUE TITLE
[NPC] Thassarian appearing to offer quest turn-ins - 29799 - Icecrown

### ISSUE THREAD

**Issue by jarvik76** [WoWManiaUK/Redemption#3977]
**Links:**
https://www.wow-mania.com/armory/?npc=29799

**What is Happening:**
Thassarian is showing ? quest completion symbol even when no quest available to turn in, but (daily) quests available to take.
![image](https://user-images.githubusercontent.com/46089380/72204454-013d5680-3470-11ea-8aa6-7a7c5767c5de.png)

**What Should happen:**
Should not show ?, should show ! instead - yellow when quests available and blue when only dailies.

**Comment by Kitzunu** [comment]
Currently troubleshooting which quest may cause this

**Comment by Kitzunu** [comment]
Found the quest causing it, now I just have to figure out why...

**Comment by Kitzunu** [comment]
Fixed
