### ISSUE TITLE
[Quest] Quests on Skybreaker are not chained correctly - Icecrown

### ISSUE THREAD

**Issue by jarvik76** [WoWManiaUK/Redemption#3980]
**Links:**
https://www.wowhead.com/quest=13225/the-skybreaker#comments:id=661907

**What is Happening:**
Currently the Skybreaker has no chaining, offering all quests at the same time.

**What Should happen:**
Should be chained like it is shown here: https://www.wowhead.com/quest=13225/the-skybreaker#comments:id=661907

**Comment by jarvik76** [comment]
Slaves to Saronite from Absalan has incorrect quest marker, yellow instead of blue.
![image](https://user-images.githubusercontent.com/46089380/72207367-5db06e00-3490-11ea-91f6-99b1cfa8f726.png)

**Comment by jarvik76** [comment]
working on retesting this chain

**Comment by jarvik76** [comment]
- [ ] The Skybreaker------->Mind Tricks 
- [ ] The Skybreaker------->Joining the Assault
- [ ] The Skybreaker------->D)Blood of the Chosen
- [ ] The Skybreaker------->D)Slaves to Saronite |
- [ ] The Skybreaker------->Get to Ymirheim! 
- [ ] The Skybreaker------->The Broken Front 
- [ ] Joining the Assault ------->D)Assault by Air
- [ ] Joining the Assault ------->D)Assault by Ground
- [ ] The Skybreaker------->The Broken Front
- [ ] The Broken Front------->Finish Me!
- [ ] Finish Me!------->D)No Mercy!  
- [ ] Get to Ymirheim! -------> D)King of the Mountain  
- [ ] The Broken Front------->Your Attention, Please
- [ ] The Broken Front------->...All the Help We Can Get.
- [ ] Your Attention, Please------->Borrowed Technology
- [ ] Borrowed Technology------->D)The Solution Solution
- [ ] Killohertz------->Leading the Charge
- [ ]  Leading the Charge------->  D)Static Shock Troops: the Bombardment 
- [ ]  Leading the Charge------->  D)Putting the Hertz: The Valley of Lost Hope
- [ ] Poke and Prod------->That's Abominable!      
- [ ] That's Abominable!------>D)That's Abominable!
- [ ] Poke and Prod------->Against the Giants
- [ ] Against the Giants------->Coprous the Defiled
- [ ] Against the Giants------->Basic Chemistry
- [ ] Basic Chemistry-->D)Neutralizing the Plague
- [ ] That's Abominable!------>Sneak Preview    
- [ ] Sneak Preview------>Chain of Command 
- [ ] Sneak Preview------>Cannot Reproduce
- [ ] Cannot Reproduce------>Retest Now
- [ ] Retest Now------>D)Retest Now
- [ ] Sneak Preview------>Drag and Drop
- [ ] Drag and Drop-->D)Drag and Drop
- [ ] Drag and Drop-->Not a Bug
- [ ] Not a Bug-->D)Not a Bug
- [ ] Drag and Drop-->Need More Info
- [ ] Need More Info-------->No Rest For The Wicked
- [ ] No Rest For The Wicked-------->D)No Rest For The Wicked
- [ ] Need More Info-------->Raise the Barricades
- [ ] Raise the Barricades------>The Ironwall Rampart
- [ ] Raise the Barricades------>Get the Message
- [ ] Get the Message------>D)Capture More Dispatches
- [ ] Raise the Barricades------>Bloodspattered Banners

- [ ] Bloodspattered Banners------>Before the Gate of Horror
- [ ] Before the Gate of Horror------>Shatter the Shards
- [ ] Before the Gate of Horror------>The Guardians of Corp'rethar

**Comment by jarvik76** [comment]
Testing paused, see discord discussion

**Comment by jarvik76** [comment]
All you the Help you can Get cannot be turned into Thassarian:
 ![unknown](https://user-images.githubusercontent.com/46089380/72263762-6c725e80-3611-11ea-8181-d3d31dc44671.png)

Fixed by Kitzunu
![unknown2](https://user-images.githubusercontent.com/46089380/72263914-bc512580-3611-11ea-8df9-62e15aef34d6.png)
Testing to continue tonight

**Comment by Kitzunu** [comment]
https://github.com/WoWManiaUK/Redemption/issues/3997

**Comment by jarvik76** [comment]
#3998 #3999

**Comment by jarvik76** [comment]
"The Ironwall Rampart" should require both "No Rest for the Wicked" AND "Raise the Barricades"
(13337 should require both 13346 AND 13332)

Before the Gate of Horror should require both The Ironwall Rampart AND "Bloodspattered Banners"
(13335 should require both 13337 AND 13334)

![image](https://user-images.githubusercontent.com/46089380/72292086-9f841480-3648-11ea-9ccd-05bda65a3513.png)

**Comment by jarvik76** [comment]
Was painful and lengthy to test but looks clean now. Will retest in production once this goes live.  Big thanks to @Kitzunu for additional fixes for previously undiscovered quest blocks found during testing.
