### ISSUE TITLE
[Spell] Sear - Searing totem killing itself with spell reflect

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#3985]
https://www.wowhead.com/spell=65998/sear
https://classic.wowhead.com/spell=10438/searing-totem

**What is Happening:**
Searing totem's attack (sear) can be currently spell reflected so the totem kills itself on any reflect shields in PVE and can consume the reflect of warriors in PVP.

**What Should happen:**
Searing totem's attack should not be possible to reflect, it has a flag for it on wowhead.

**Comment by Keader** [comment]
It's a boss spell, not the shaman one.
Totems uses: 58702, that dont have any attribute.
Is a pvp mechanic, use totem to remove spell reflection (shaman vs warrior)

**Comment by Dranah** [comment]
Okay wowhead is retarded. My bad :P
