### ISSUE TITLE
[Spell/Pet] Feral Spirit scaling with hit

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#3986]
spell ID 51533 feral spirit

**What is Happening:**
The wolves do not benefit from the shaman's hit or expertise, and keep missing and being dodged even if the shaman himself is capped.

**What Should happen:**
The wolves should benefit 100% of the shaman's hit rating, so if the shaman is capped, so are the wolves and much like hunter pets, they also gain expertise soft cap from that (no dodges).

https://www.mmo-champion.com/threads/624759-*Enhancement-Shaman-FAQ-(3-3)
https://wowwiki.fandom.com/wiki/Feral_Spirit

**Comment by Keader** [comment]
hit and expertise, are 2 different things.
Why this is regression? o.o

**Comment by Dranah** [comment]
I did say in the original report that the pet must also receive expertise from the shaman's hit.
Need I open a new report for it?
