### ISSUE TITLE
[Boss] Gunship Battle adds (ICC)

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#3988]
**Links:** https://wowwiki.fandom.com/wiki/Gunship_Battle
https://www.wowhead.com/npc=36968/korkron-axethrower
https://www.wowhead.com/npc=36982/korkron-rocketeer
https://www.wowhead.com/npc=37029/korkron-reaver
https://www.wowhead.com/npc=36960/korkron-sergeant
https://www.wowhead.com/spell=71188/experienced
https://www.wowhead.com/spell=71193/veteran
https://www.wowhead.com/spell=71195/elite

**What is Happening:** 

1. The enemy ship's adds can be completely broken by applying a debuff to them while they are pathing to their 'attack' position. Corruption, Living bomb, or any curses that don't instantly deal damage instantly will cause the issue. Their AI simply breaks and they stop doing anything. Mobs affected from an alliance POV are [Kor'kron Axethrower](https://www.wowhead.com/npc=36968/korkron-axethrower)s, [Kor'kron Rocketeers](https://www.wowhead.com/npc=36982/korkron-rocketeer), [Kor'kron Reavers](https://www.wowhead.com/npc=37029/korkron-reaver) and [Kor'kron Sergeants](https://www.wowhead.com/npc=36960/korkron-sergeant). The last 2 being more difficult to reproduce since they reach their position very quickly (upon going through the portal).

2. The adds are missing their 'experience' system.

**What Should happen:**

1. Mobs shouldn't have their AI broken with the simple application of a debuff.

2. > All enemy NPCs except the Commanders and the Battle-Mage/Sorceror gain experience the longer they are left alive, starting from Regular and progressing to [Experienced](https://www.wowhead.com/spell=71188/experienced), then [Veteran](https://www.wowhead.com/spell=71193/veteran), and finally [Elite](https://www.wowhead.com/spell=71195/elite
). Depending on rank, damage and attack speed are increased. - https://wowwiki.fandom.com/wiki/Gunship_Battle

The last 2 'ranks' should only be reached in 25 heroic difficulty.

**Comment by Dranah** [comment]
I can confirm the issue with the AI breaking when the NPCs are engaged with a non-direct attack-

Not sure what the issue with the exp system is. I can't find any source that claims the Veteran and Elite ranks are 25hc-only.

**Comment by Oganku** [comment]
![Screenshot_2020-01-12-08-00-59](https://user-images.githubusercontent.com/34783736/72219228-bd9b2900-3511-11ea-82cd-308a5a9c2e0f.png)

**Comment by Dranah** [comment]
I believe that is an overlooking. There is no specified change between difficulties in the amount of ranks, only the speed of gaining experience.
"Rocketeers and Mortars have a small knockback added to their rockets. The enemy's commander does more damage, and his Battle Fury increases his damage by 12% instead of 10%. Enemy soldiers gain experience faster, but not one of those changes should pose a problem."
https://www.wowhead.com/object=201873/gunship-armory#abilities-normal-10-player lists the same ranks for all difficulties and so does wiki

**Comment by Dranah** [comment]
Enemy rocketeers and riflemen will no longer be bugged when receiving a dot or direct damage while running to their spots.
