### ISSUE TITLE
[Spell] Life Tap/Living Bomb interaction with Unchained Magic

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#3989]
**Links:**https://www.wow-mania.com/armory/?spell=57946
https://www.wow-mania.com/armory/?spell=69762
https://www.wow-mania.com/armory/?spell=69766
https://github.com/WoWManiaUK/Redemption/issues/3983

**What is Happening:** Casting [Life Tap](https://www.wow-mania.com/armory/?spell=57946) while affected by  [Unchained Magic](https://www.wow-mania.com/armory/?spell=69762 grants the warlock 2 stacks of [Instability](https://www.wow-mania.com/armory/?spell=69766
) instead of just one. It seems to be giving one for damaging yourself, and one for giving mana. Seems possibly related to #3983.

**What Should happen:** Casting [Life Tap](https://www.wow-mania.com/armory/?spell=57946) with [Unchained Magic](https://www.wow-mania.com/armory/?spell=69762
) should only grant 1 stack of [Instability](https://www.wow-mania.com/armory/?spell=69766
).

**Comment by Dranah** [comment]
Add to it Living Bomb, which also gives 2 stacks: 1 for the application, 1 for the explosion - reported by Drostan

**Comment by Oganku** [comment]
While we're at it haunt does too. One for the cast, and one for when it returns to you and heals.

**Comment by Dranah** [comment]
Fixed, fixed and fixed. None of the three spells will grant double stack now.
