### ISSUE TITLE
[Spell] Disarm Trap 

### ISSUE THREAD

**Issue by Kitzunu** [WoWManiaUK/Redemption#3990]
https://wow-mania.com/armory/?spell=1842

**How it works:**
Currently, you are not able to disarm any GAMEOBJECT_TYPE_TRAP               = 6 (Traps) which make you unable to disarm hunter traps and ICC traps for example.

**How it should work:**
Disarm Trap should be able to disarm any gameobject with GAMEOBJECT_TYPE_TRAP               = 6

**Comment by Kitzunu** [comment]
Confirmed by a player yesterday

**Comment by Kitzunu** [comment]
2. I do not know if this should go into a new issue or the same but.
**How it works:** 
Currently, while the rogue is stealthed he cannot see any hostile traps, be this hunter or ICC traps.

**How it should work:**
Whilst the rogue is stealthed, he should be able to see hostile traps so that they can be disarmed.

**Comment by volkangul** [comment]
i can confirm its 21.10 SVT on 13.01.2020, traps cannot be disarmed. Stealthed but there is no right click on traps to disarm them. Neither clicking the ability itself cannot find any thing on laid traps.
