### ISSUE TITLE
Two unique gems( [Nightmare Tear]) can be equipped at the same time

### ISSUE THREAD

**Issue by timbazi** [WoWManiaUK/Redemption#3992]
**Links:**
Video to demonstrate how it can happen: https://www.youtube.com/watch?v=huc81-nSn8c

**What is Happening:**
A way to equip two of same unique gems at the same time (+10 stats gem). 
Don't know why it works when equipping the items in this specific order, but it does, apparently.
The items are; Chest: [Carapace of Forgotten Kings] Belt: [Belt of Rotted Fingernails] with [Eternal Belt Buckle] attached

**What Should happen:**
This should not happen.

**Comment by Dranah** [comment]
Confirmed. Requires a belt with no default socket slots, only gaining one via the Eternal belt buckle. The extra socket slot given by the buckle is not considered when attempting to equip another item with a Nightmare tear in it, The second item equipped does not need to be a chest slot, any other slot works.
