### ISSUE TITLE
[Spell] Savage combat

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#3993]
spell ID 58413

**What is Happening:**
The effect is not removed when the rogue's poison expires or gets dispelled.
It has a 5minute duration and as far as I could dig up, this is an old workaround made by VaL:
https://github.com/WoWManiaUK/Redemption/issues/720
However this is a custom addition and is not blizzlike.

**What Should happen:**
The effect is tied to the rogue having poisoned its target, when the poisons are removed, the Savage combat should be too.

Right now you have to walk around with this debuff for 5minutes in a BG or arena even if the rogue is dead or long gone.

**Comment by Keader** [comment]
I did a little script to handle with it.
Script will check each 2 sec, if has some rogue poison on target.
So may, it take 2 sec to remove savage combat, after poison expire.

**Comment by Kitzunu** [comment]
Does it check poisons in general or that specific players poisons?

Only reason I ask is because say Rogue 1 has spec for Savage Combat Rogue 2 doesnt,
Rogue 1 applies poison and SC
Rogue 2 applies poison
Rogue 1 poison go out but Rogue 2's poison still on.
Would SC be remove or stay on the target?

**Comment by Keader** [comment]
Rogue specific
If a rogue A has a talent and Rogue B dont has It
, This effect Will expire when Poison of rogue A expire

**Comment by Kitzunu** [comment]
Cool!

**Comment by Dranah** [comment]
Works neat. gg!
