### ISSUE TITLE
Putting the hertz: the valley of lost hope

### ISSUE THREAD

**Issue by nephril** [WoWManiaUK/Redemption#3994]
The target creatures for this quest are almost all (a small percentage of the gargoyles work and an occasional dragon) are glitched displaying "EVADE" whenever i try to use the weapons on the quest vehicle to hit them. Confirmed through wowhead how to complete this quest and watched a video and the flying creatures are not working as intended. 
https://www.wowhead.com/quest=13382/putting-the-hertz-the-valley-of-lost-hope

**Comment by jarvik76** [comment]
https://youtu.be/Q86W4k7cEFI
Gargoyle that did not evade
![image](https://user-images.githubusercontent.com/46089380/72229160-537f9400-35a4-11ea-873b-7835cc402c73.png)
Gargoyle that evaded
![image](https://user-images.githubusercontent.com/46089380/72229169-672afa80-35a4-11ea-9529-08ed19af30e4.png)

**Comment by wow-mania** [comment]
This is as-is. There are many possible reasons for this. The NPCs are all identical. You are supposed to do multiple rounds of the quest to complete it.

**Comment by Kitzunu** [comment]
Do not close it, because if Rushor has a way to fix it, its better to fix than leave as-is

**Comment by Rushor** [comment]
yeah lot of reasons, all i can do is removing evade mode for individual creatures. will do it now

**Comment by Rushor** [comment]
well i tried a lot now - this cannot be fixed right now sadly
