### ISSUE TITLE
[Quest] Trolls Is Gone Crazy!

### ISSUE THREAD

**Issue by Kitzunu** [WoWManiaUK/Redemption#3996]
Removed some hack fixes and fixed it properly.

Will now show 2 chains :)
![image](https://user-images.githubusercontent.com/24550914/72262904-1e148e00-3618-11ea-8132-30e57adfdee6.png)

**Comment by jarvik76** [comment]
https://www.wow-mania.com/armory/?quest=12861

**Comment by jarvik76** [comment]
Fix confirmed.  Animation of result is indeed a lot smoother.
![image](https://user-images.githubusercontent.com/46089380/72295336-453a8200-364f-11ea-975c-4db70b597a72.png)
