### ISSUE TITLE
[Item] Purified Lunar Dust

### ISSUE THREAD

**Issue by venuminostrates** [WoWManiaUK/Redemption#4000]
**Links:**
https://www.wow-mania.com/armory/?item=50358

**What is Happening:**
Purified Lunar Dust trinket proc "Revitalized" is not triggering properly. It is triggering on direct damage or direct healing. Spells such as a Druid's Rejuvenation will never trigger it, despite the wording on the trinket that the spell cast itself (not the heal or damage) is supposed to proc it. I can also find no mention on other forums, such as wowhead, that this was how it functioned on retail. If this was how it functioned, then resto druids would have avoided this trinket, and it would not have been on recommended upgrade lists in guides.

To replicate the issue, get on a Druid, equip the trinket, cast Rejuvenation over and over, and watch for the "Revitalized" proc, which will never happen. You can also cast Hurricane and see that the proc triggers off of the direct damage that Hurricane deals, not the spell cast itself. 

In terms of prioritization, this bug only affects resto druids adversely, and only those who have purchased this trinket (60 Frost Emblems). In raids, they spam Rejuvenation and Wild Growth, both of which cannot trigger the proc with the current state of this bug.
 
**What Should happen:**
The trinket should proc on spell casts, not direct healing or direct damage.

**Comment by Keader** [comment]
Yes, we dont have support for it (old proc system sucks).
So i allow to proc it with DOTS, for now... is the best solution (since blizzlike behavior will proc with dots cast anyway)

**Comment by Kitzunu** [comment]
@Keader When will the new proc system come? x))))

**Comment by Keader** [comment]
'-'
why you hate me?

**Comment by Kitzunu** [comment]
Only love here ❤️

**Comment by venuminostrates** [comment]
Could you make it proc with hots?

**Comment by jarvik76** [comment]
@venuminostrates DOTS & HOTS use the same trigger mechanic so yes it will proc with both

**Comment by venuminostrates** [comment]
Amazing! It works for druids now! <3
