### ISSUE TITLE
[General] Creatures with NO AI

### ISSUE THREAD

**Issue by Rushor** [WoWManiaUK/Redemption#4003]
https://gist.github.com/Rushor/bfb9944086b124a25f5c0782551a494f

Those creature entries are all missing an AI resulting in strange behaviour when charm is ending. 

Now all those creatures have at least a SmartAI and will reset properly on charm ending.

**Comment by Rushor** [comment]
will now only affects huamoids
so type 7 creatures
8000 creatures affected then
so just pls test if pet work still no strange behaviour for them

**Comment by Keader** [comment]
wtf?

**Comment by Rushor** [comment]
big stuff :o

**Comment by Rushor** [comment]
only affects creatures which are NOT:
- vehicle,
- trigger,
- placeholder,
- difficulty entry npc
- have not smartai yet
- have not corescript yet
- are humanoid
