### ISSUE TITLE
[Boss] Felmyst

### ISSUE THREAD

**Issue by cooperonie** [WoWManiaUK/Redemption#4006]
**Links:**
https://www.wowhead.com/npc=25038/felmyst

**What is Happening:**
We did a raid with the guild recently in Sunwell Plateau and ran into a few issues with the Felmyst encounter
1) Felmyst  is unkillable; it was down to 10 HP dot's and spells showed up as "doing damage" but felmyst just kept flying around and attacking us without a care ..
2) An INSANE amount of those skeletons(adds) spawned ( i know it's a mechanic but everyone's GPU's started crying and dropped to like 5FPS) 
![sgfjjertj 1](https://user-images.githubusercontent.com/2728624/72382142-ed684d80-3718-11ea-9df2-3e17252699c0.png)

**What Should happen:**
1) He should not go invincible at 10HP ..
2) any chance there should be a limit on the amount of mobs that spawn ?

Thanks for looking into this,

**Comment by Oganku** [comment]
Can confirm lagging the server just by surviving long enough against the skeletons. They do spawn in absurd amounts.

**Comment by Rushor** [comment]
void DamageTaken(Unit*, uint32 &damage) override
        {
            if (phase != PHASE_GROUND && damage >= me->GetHealth())
                damage = 0;
        }

this prevents him from damage. so you need to wait until he lands again.

for the NPC_DEAD = 25268, > i will remove those spawns for now until i rewrote the whole encounter.

**Comment by cooperonie** [comment]
Cool thank you, any chance you could make it show up as "resisted" or something ? 
It'd avoid being clueless and confused..

**Comment by WhitephoenixTheBunny** [comment]
@Rushor we keep having infinite ones
![image](https://user-images.githubusercontent.com/31921098/74091500-2691a480-4ab0-11ea-9a54-0d1fd3b17587.png)

**Comment by Rushor** [comment]
okay refixed! no dead spawn
