### ISSUE TITLE
[Bosses] Blackheart the Inciter and Rend Blackhand

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#4007]
**Links:** https://www.wowhead.com/npc=18667/blackheart-the-inciter
https://classic.wowhead.com/npc=10429/warchief-rend-blackhand

**What is Happening:** Both [Blackheart the Inciter](https://www.wowhead.com/npc=18667/blackheart-the-inciter) and [Warchief Rend Blackhand](https://classic.wowhead.com/npc=10429/warchief-rend-blackhand) are taking way less damage than they should. They seem to be taking capped damage per hit, making them very long to kill even for a geared lv80. A while ago I made a ticket and was told it was to prevent skipping the bosses' phases, but none of them seem to have any apparent phase and thus have no reason to take such low damage.

**What Should happen:** Both bosses shouldn't take ridiculously low damage since they have no damage reduction buffs or abilities.

**Comment by wow-mania** [comment]
As-is.  They are not supposed to be run at level 80 anyways and expected to be downed in 15 seconds.

**Comment by Kitzunu** [comment]
I think this should be looked into since level 80:s can be expected to run these. For example, during reputation runs.
