### ISSUE TITLE
[Mounts] Several mounts with wrong animation / "permissions" 

### ISSUE THREAD

**Issue by WhitephoenixTheBunny** [WoWManiaUK/Redemption#4009]
**Panthers - Have wrong flying animation, they look swimming:**

ItemID - NAME+link
82453 - [Jeweled Onyx Panther ]( http://www.wow-mania.com/armory/?item=82453)
83090 - [Sapphire Panther](http://www.wow-mania.com/armory/?item=83090)
83089 - [Sunstone Panther ](http://www.wow-mania.com/armory/?item=83089 )
83088 - [Jade Panther](http://www.wow-mania.com/armory/?item=83088)
83087 - [Ruby Panther]( http://www.wow-mania.com/armory/?item=83087) 

example of a mount with correct animation:

 142225 - [Ban-lu, Grandmaster's Companion](http://www.wow-mania.com/armory/?item=142225)

**Serpents - Have wrong flying animation, they look swimming:**

ItemID - NAME+link
87768 - [Reins of the Onyx Cloud Serpent](https://www.wow-mania.com/armory/?item=87768)
79802 - [Reins of the Jade Cloud Serpent](https://www.wow-mania.com/armory/?item=79802)
89304 - [Reins of the Thundering August Cloud Serpent](https://www.wow-mania.com/armory/?item=89304)
87769 - [Reins of the Crimson Cloud Serpent](https://www.wow-mania.com/armory/?item=87769)
87771 - [Reins of the Heavenly Onyx Cloud Serpent](https://www.wow-mania.com/armory/?item=87771)
87773 - [Reins of the Heavenly Crimson Cloud Serpent](https://www.wow-mania.com/armory/?item=87773)
87774 - [Reins of the Heavenly Golden Cloud Serpent](https://www.wow-mania.com/armory/?item=87774)
87775 - [Reins of the Heavenly Jade Cloud Serpent](https://www.wow-mania.com/armory/?item=87775)
87776 - [Reins of the Heavenly Azure Cloud Serpent](https://www.wow-mania.com/armory/?item=87776)
87777 - [Reins of the Astral Cloud Serpent](https://www.wow-mania.com/armory/?item=87777)

example of a mount with correct animation (ignore the wings)
78924 - [Heart of the Aspects](https://www.wow-mania.com/armory/?item=78924) 
___

104011 - [Stormcrow](https://www.wow-mania.com/armory/?item=104011) - This is a flying mount, but is acting as grounding mount.

__

118515 - [Cindermane Charger](https://www.wow-mania.com/armory/?item=118515) - This is a flying mount, only can be used on Outland and Northrend, should act as [Invincible's Reins](https://www.wow-mania.com/armory/?item=50818): Grounding on cities and Azeroth and flying on Northrend and Outland

__

150080 - [Long-Forgotten Hippogryph](https://www.wow-mania.com/armory/?item=150080) - Have wrong texture... it shows: [Silver Covenant Hippogryph](https://www.wow-mania.com/armory/?item=46813) - IF it can't be fixed, it should be removed as is a VIP mount and the Silver Covenant Hippogryph is an ingame mount

__

54069 - [Blazing Hippogryph](https://www.wow-mania.com/armory/?item=54069) - This is a flying mount, but is acting as grounding mount.
__

150093 - [Leyfeather Hippogryph](https://www.wow-mania.com/armory/?item=150093) - Missing flying animation

__

149985 - [Viridian Sharptalon](https://www.wow-mania.com/armory/?item=149985)
149984 - [Predatory Bloodgazer ](https://www.wow-mania.com/armory/?item=149984)
149986 - [Brilliant Direbeak](https://www.wow-mania.com/armory/?item=149986)
149987 - S[nowfeather Hunter](https://www.wow-mania.com/armory/?item=149987)

Those 4 mounts miss the casting mount animation.

EDIT:

150521 - [Vicious Warstrider](https://www.wow-mania.com/armory/?item=150521) is a PVP mount, it should be 100% speed, is 60% atm

**Comment by Oganku** [comment]
Note: [Lightforged Warframe](https://www.wow-mania.com/armory/?item=150569) (150569) and [Grinning Reaver ](https://www.wow-mania.com/armory/?item=112327) (112327) are meant to behave like Invinicble/Cindermane Charger, where they should be able to fly in certain areas. I'm aware their flying animations are unique and most likely not in the game for us, but I still wanted to mention it.

**Comment by slaniaxx** [comment]
We do actually see "Lightforged Warframe"'s flying animation when it jumps, it flies with the same exact animation.

**Comment by Rushor** [comment]
Can this be fixed with a new Client Update maybe?

**Comment by wow-mania** [comment]
THis will remain as-is for a while until we have a client update.
