### ISSUE TITLE
[Mount] Leyfeather Hippogryph particles

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#4010]
**Links:** https://www.wowhead.com/spell=225765/leyfeather-hippogryph
https://www.wow-mania.com/armory/?spell=150163

**What is Happening:** In WoW-Mania, the [[Leyfeather Hippogryph]](https://www.wowhead.com/spell=225765/leyfeather-hippogryph) mount glow particles are wrong. They look like very bright fire and can't be seen on the armory and some players have reported being disappointed by them after purchasing the mount. (See Mania screenshot below)

![Mania_leyfeather](https://user-images.githubusercontent.com/34783736/72555833-61b30600-386b-11ea-8f49-7c001bd1c091.png)

**What Should happen:** The glow on the mount should be very faint and not obstruct the model so much (way too opaque). Having no glow at all might even be better if possible. (See retail screenshot below)

![retail_leyfeather](https://user-images.githubusercontent.com/34783736/72555899-89a26980-386b-11ea-9e10-c20a6517e99c.jpg)

P.S. The glow should be an outline glow nearly identical to the "Prestigious" horses we have on mania, whose particle glow outlines show up perfectly. Maybe something related between the 2 could be useful.

**Comment by wow-mania** [comment]
This one is a limitation on the client.
We won't be able to fix.

**Comment by WhitephoenixTheBunny** [comment]
Can you remove the "glowing" at least?
