### ISSUE TITLE
[Gameobject] Geist Alarm / Deathbound Ward

### ISSUE THREAD

**Issue by Kitzunu** [WoWManiaUK/Redemption#4011]
Now since disarm trap works, the range on these needs to be adjusted so you can disarm them from 20yards.

How it works now:
You detect the trap for 1 second and then it instantly triggers.

How it should work:
A rogue should be able to detect the trap and then disarm it from a 20-yard range without the trap triggering.

**Comment by Kitzunu** [comment]
Not fixed, they trigger instantly when you detect them making it unable to disarm

**Comment by Rushor** [comment]
try later

**Comment by Kitzunu** [comment]
Not fixed, now it doesn't even let me discover it.
just triggers without me even seeing it

**Comment by Rushor** [comment]
i don't know how to fix that - will remake i to the old behaviour
