### ISSUE TITLE
[Zone] Light's Hammer

### ISSUE THREAD

**Issue by Kitzunu** [WoWManiaUK/Redemption#4014]
- [x] Ormus the Penitent - Added missing gossip menu.

- [x] Crusader Gromtong - Added missing gossip menu and conditions.

- [x] Crusader Halford - Added missing gossip menu, conditions and emote STATE_WORK_MINING.

- [x] Scott the Merciful - Added missing gossip menu and conditions.

- [x] Niby the Almighty - Added missing gossip menu and conditions.

- [x] Jedebia - Added missing gossip menu and conditions.

- [x] Talan Moonstrike - Added missing gossip menu and conditions.

- [x] Alana Moonstrike - Added missing gossip menu and conditions.

- [x] Yili - Added missing gossip menu and conditions.

- [x] Malfus Grimfrost - Added missing gossip menu and conditions.

- [x] Saronite Bars - Added missing spawn.

- [x] Argent Verdict Anvil - Added missing spawn, adjusted one spawn Z value.

**Comment by jarvik76** [comment]
Fix confirmed
![image](https://user-images.githubusercontent.com/46089380/72672033-e9576b00-3a4b-11ea-9e66-d29fae19ab99.png)
![image](https://user-images.githubusercontent.com/46089380/72672038-f8d6b400-3a4b-11ea-9dcd-c5ba85b42ce3.png)
![image](https://user-images.githubusercontent.com/46089380/72672040-068c3980-3a4c-11ea-9bec-ea4e1a37348f.png)
