### ISSUE TITLE
[Achievement] Murkimus the Gladiator

### ISSUE THREAD

**Issue by NightSeekerr** [WoWManiaUK/Redemption#4015]
**Links:** Achievement: https://www.wow-mania.com/armory/?achievement=3618
NPC: https://www.wow-mania.com/armory/?npc=33578
Object: https://www.wow-mania.com/armory/?item=45180

**What is Happening:** I bought and used the object "Murkimus' Little Spear" and obtained the pet "Murkimus the Gladiator", but did not obtain the achievement that comes with it.

**What Should happen:** When you obtain either the object or the pet you should also get the achievement that comes with it. Other players in the server have it so I assume it bugged in my case.

**Comment by Kitzunu** [comment]
![image](https://user-images.githubusercontent.com/24550914/72667034-e6428780-3a17-11ea-94f6-6b72efbad149.png)

Works. Make a ticket ingame and a GM can help you

**Comment by WhitephoenixTheBunny** [comment]
I retested it, and I menaged to find the issue.
The item at mall isn't the correct one to give the achivement

AT MALL: https://www.wow-mania.com/armory/?item=54857

From achiev: https://www.wow-mania.com/armory/?achievement=3618
Required: https://www.wow-mania.com/armory/?item=45180

the item at mall need be switched UNLESS this is as inteed, as as so far I recall, that was (and is?) a PVP reward

**Comment by wow-mania** [comment]
OK, I will change it. Thanks for that.
