### ISSUE TITLE
[NPC] Azuregos - Missing Path

### ISSUE THREAD

**Issue by Rushor** [WoWManiaUK/Redemption#4019]
http://wotlk.openwow.com/npc=15481

Should use waypoints and have a path.

Source: http://wowwiki.wikia.com/wiki/Azuregos

...To avoid this a Spirit of Azuregos can always be found wandering through southern Azshara.

**Comment by Kitzunu** [comment]
Only stands still.

**Comment by Rushor** [comment]
oh my bad. it is entry 6109! not the spirit. sorry. works now
