### ISSUE TITLE
[NPC][TBC] Dragonmaw Wrangler + Dragonmaw Subjugator + Dragonmaw Drake-Rider + Dragonmaw Shaman - Missing Aggro texts

### ISSUE THREAD

**Issue by Rushor** [WoWManiaUK/Redemption#4021]
Dragonmaw Wrangler + Dragonmaw Subjugator + Dragonmaw Drake-Rider + Dragonmaw Shaman
should all say on of those texts:

Your bones will break under my boot, $r!
Long live the Dragonmaw! Die you worthless $r!
For the Dragonmaw!

on aggro for 15 percent.

**Comment by Kitzunu** [comment]
I cannot confirm it reproduce the fix

**Comment by Rushor** [comment]
aggro test chance is 15 percent https://i.imgur.com/kgiyInt.jpg
