### ISSUE TITLE
[Spell] Glyph of Scourge Strike

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#4024]
Item ID = 43551
spell ID = 58642

**What is Happening:**
The glyph does not extend the duration of Ebon Plague (spell ID 51735) which is also a disease and otherwise scales with the duration of the other diseases (Frost fever, blood plague) that apply it.
This causes the Ebon plague effect to expire sooner than the other diseases, which should never happen (effect must always be up on target you have diseased)

**What Should happen:**
Glyph of Scourge strike should extend the duration of Ebon Plague as well.

**Comment by GMZinius** [comment]
Player reported this issue isnt fixed @Keader 
re-opening this for you

**Comment by svijetlo** [comment]
since when testing is done on live ?
is that new things when i did it it was not valid as test

**Comment by Greywolf59** [comment]
Why wouldn't it be valid? People play on live, not on PTR. I have seen enough dismissive replies "works on PTR, case closed" so I will always test it both on PTR and live if possible. Also I dont have a DK on PTR nor do I have commands yet I think so I can't test it on PTR anw.

**Comment by Greywolf59** [comment]
Scourge Strike test live. Don't ask me why it has such a stupid screen format, just downloaded the OBS and can't figure it out.
https://files.fm/f/erewnbgk8

**Comment by svijetlo** [comment]
cos it is known bug exist on live , if smt then work on ptr it means it should not be worked on as next "build / reset " will fix problem 
but i was just asking , as i know those tests were not considered as valid , but things change.

**Comment by GMZinius** [comment]
> since when testing is done on live ? is that new things when i did it it was not valid as test

Hi svijetlo, I told him it was ok

**Comment by Greywolf59** [comment]
Tested on PTR. Glyph of Scourge Strike does prolong Blood Plague and Frost Fever but does not prolong Ebon Plague
Video: https://files.fm/f/9ph2dsmsu

**Comment by Keader** [comment]
Fixed, but i cant build the server
i will post here when fix become up

**Comment by Keader** [comment]
try now pls

**Comment by Greywolf59** [comment]
Tested on PTR. It works.
