### ISSUE TITLE
[NPCs] Temp summoned NPCs for quests have super-fast run speed

### ISSUE THREAD

**Issue by jarvik76** [WoWManiaUK/Redemption#4032]
**Links:**
https://www.wowhead.com/quest=12411/a-sisters-pledge
https://www.wowhead.com/quest=11984/filling-the-cages

**What is Happening:**
NPCs that are temporarily summoned for quest purposes have a movement speed that is abnormally fast.
e.g. 
Budd in https://www.wowhead.com/quest=11984/filling-the-cages
Anya in https://www.wowhead.com/quest=12411/a-sisters-pledge

Speed is returned to normal if they are GM dismissed and re-summoned

This has **only changed in the last day or two**.

**What Should happen:**
NPCs summoned for quests should move at 1x speed.

**Comment by Kitzunu** [comment]
This does not happen after the npc is dismissed by force, or by time running out, so you have a one time chance to reproduce
