### ISSUE TITLE
[Zone] Shattrath City

### ISSUE THREAD

**Issue by Kitzunu** [WoWManiaUK/Redemption#4036]
- [x] Marksman Bova - Fixed positioning.

- [x] Korim - Fixed positioning.

- [x] Lady Liandrin - Fixed positioning.

- [ ] Shattered Sun Marksman & Warrior - Fixed waypoints for walking.

**Comment by Rushor** [comment]
the dudes sometimes walk on right spots
https://i.imgur.com/xEtBBpw.jpg

need to add unitflag ignore pathfinding
