### ISSUE TITLE
[NPC] Some emote states

### ISSUE THREAD

**Issue by Kitzunu** [WoWManiaUK/Redemption#4038]
GUID 127995,127998,128029,127997,128030,127996
-> removed wrong emote 193 added byte 8 = Makes the mob kneel

GUID 126599,53282,53247,27685,27684,27683,27681,27675,6455,6854,49199,82886,82293,82286,82285,82277
-> remove wrong emote 193

**Comment by Rushor** [comment]
looks good. emote is also removed in combat https://i.imgur.com/gi1u9MF.jpg so all is good

others also good https://i.imgur.com/AlduU4E.jpg
