### ISSUE TITLE
[Zone] Mana Tombs

### ISSUE THREAD

**Issue by Kitzunu** [WoWManiaUK/Redemption#4039]
- [x] Captain Kaftiz - added an event

- [x] Add a missing gob

- [x] Remove a wrong spawn

- [x] Add a cosmetic cast to a Consortium Engineer

- [x] Added gossip menu for "Captain" Kaftiz

**Comment by Rushor** [comment]
looks good https://i.imgur.com/lg4bPRH.jpg
