### ISSUE TITLE
[Boss] Forgemaster Garfrost (Pit of Saron)

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#4042]
**Links:** https://www.wowhead.com/npc=36494/forgemaster-garfrost
https://www.wowhead.com/spell=68771/thundering-stomp
https://www.wowhead.com/spell=68774/forge-frozen-blade
https://www.wowhead.com/spell=68785/forge-frostborn-mace

**What is Happening:** On heroic mode, [Forgemaster Garfrost](https://www.wowhead.com/npc=36494/forgemaster-garfrost) transitions at 66% and 33% by briefly stunning all party members with [Thundering Stomp](https://www.wowhead.com/spell=68771/thundering-stomp) and then jumping to his forge to cast [Forge Frozen Blade](https://www.wowhead.com/spell=68774/forge-frozen-blade) at 66% and then [Forge Frostborn Mace](https://www.wowhead.com/spell=68785/forge-frostborn-mace) at 33%. Upon certain conditions, the boss' jump can be interrupted and he will instead cast his spell on the party, allowing for free damage and removing the need to run after him to follow him. I'm not entirely sure what causes the jump interruption, but it is quite common.

**What Should happen:** Garfrost's jump to his forges when he transitions should not be interruptible and he should not move until he has completed his corresponding spell at his forge.

**Comment by Keader** [comment]
I need a reproduce case.

**Comment by Keader** [comment]
I made a fix, not sure if works.
Needs test in dev.
