### ISSUE TITLE
[Raid] Onyx Sanctum Guardian dropping too much gold

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#4043]
**Links:** https://www.wowhead.com/npc=30453/onyx-sanctum-guardian

**What is Happening:** This is an older bug that has come back 'recently' (regression. The [Onyx Sanctum Guardians](https://www.wowhead.com/npc=30453/onyx-sanctum-guardian) patrolling around Sartharion in the Obsidian Sanctum raid drop about ~200g each and can be farmed quite efficiently with few players, making this quite easy to abuse. GMs have warned players about this in the past and it was fixed before. Fixes should be reapplied.

**What Should happen:** Those mobs should only drop ~1-2 gold per kill, not 200. This applies to both the 10 and 25 man versions.

**Comment by Rushor** [comment]
will check

**Comment by wow-mania** [comment]
This is really strange. Creature template is correct.

**Comment by Kitzunu** [comment]
creature_template
---
```sql
SELECT MINgold, maxgold FROM creature_template WHERE entry = 30453
```
| MINgold | maxgold | 
| ---: | ---: | 
| 21855 | 23530 |
