### ISSUE TITLE
[Raid] Ruby Sanctum trash mobs loot tables

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#4044]
**Links:** https://www.wowhead.com/npc=40419/charscale-assaulter
https://www.wowhead.com/npc=40423/charscale-commander
https://www.wowhead.com/npc=40421/charscale-elite
https://www.wowhead.com/npc=40417/charscale-invoker

**What is Happening:** All 4 trash mobs in the Ruby Sanctum raid are missing their loot tables. They drop gold sometimes, but never drop any items. Their wowhead pages show they clearly should be able to drop a variety of random items. This applies to all 4 difficulties.

**What Should happen:** Those 4 mobs should have proper loot tables.

**Comment by Rushor** [comment]
will add a rev table to it

**Comment by Rushor** [comment]
common loot added with high percent chance. green and rare loot added with 5 and 2 percent chance in lootgroups
