### ISSUE TITLE
[Boss] Trollgore (Drak'tharon Keep)

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#4045]
**Links:** https://www.wowhead.com/npc=26630/trollgore
https://wowwiki.fandom.com/wiki/Trollgore
https://www.wowhead.com/spell=49555/corpse-explode
https://www.wowhead.com/spell=49380/consume

> Trollgore is the first boss of Drak'Tharon Keep. He is attacked by a constant flow of non-elite Drakkari trolls.

**What is Happening:** [Trollgore](https://www.wowhead.com/npc=26630/trollgore) is missing the endlessly spawning adds that should be engaging him in combat, trivializing the fight, as his only mechanic revolves around him killing them and [exploding them](https://www.wowhead.com/spell=49555/corpse-explode) on the party in the normal version, or [consuming them to grow larger and stronger](https://www.wowhead.com/spell=49380/consume) on heroic.
 

> Consume: A stacking 5% damage buff that also causes Trollgore to grow in size. It is applied every swing. This replaces his Cannibalize buff from normal.

**What Should happen:** Trollgore should be constantly swarmed by non-elite troll adds which he kills and explodes/consumes. These adds are missing completely. Make sure the adds stop spawning whenever Trollgore dies too, or it could easily lead to an awful dungeon experience.

**Comment by jeyrella** [comment]
Has been reported on #4265 this has regressed.

**Comment by Keader** [comment]
Blizzard video: https://www.youtube.com/watch?v=7FAAaXMf5_s

Check that periodically, some trolls are summoned and he explode him.

In our PTR: https://youtu.be/v1Xrl0MlSg4

i dont get what's missing o.o

**Comment by Sharuzan** [comment]
Waves are spawning as intended on PtR

**Comment by Keader** [comment]
@jeyrella if is not working in live server, you need talk with janitor.
something fucked in update.
