### ISSUE TITLE
[Encounter] Tribunal of Ages (Halls of Stone)

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#4046]
**Links:** https://wow.gamepedia.com/Tribunal_of_Ages
https://www.wowhead.com/npc=28070/brann-bronzebeard
https://www.wowhead.com/npc=27983/dark-rune-protector
https://www.wowhead.com/npc=27960/dark-rune-warrior
https://www.wowhead.com/npc=27984/dark-rune-stormcaller
https://www.wowhead.com/npc=27985/iron-golem-custodian
https://www.wowhead.com/npc=27972/lightning-construct

**What is Happening:** The statues now work perfectly and the fight is a lot better than it was before. The issue is that the adds spawned throughout the fight completely ignore [Brann Bronzebeard](https://www.wowhead.com/npc=28070/brann-bronzebeard), making it possible to stay far away from the statues the whole time and rendering 2 of them completely useless. The adds will still aggro to the players and not care about Brann whatsoever. (All add types linked above)

**What Should happen:** The 5 add types that spawn throughout the fight should automatically aggro to Brann Bronzebeard, as he is the target the party is meant to protect. It is impossible for Brann to even get damaged. Everything else in the fight works just fine, just aggro properties of adds are wrong.

**Comment by jarvik76** [comment]
This appears to have regressed.  Adds no longer aggro onto Brann again.

**Comment by jarvik76** [comment]
Not fixed.  Adds still do not aggo onto Brann.

**Comment by jarvik76** [comment]
yup, fixed now :)
