### ISSUE TITLE
[Raid] Ulduar portal to Dalaran

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#4048]
**Links:** https://www.wowhead.com/ulduar

**What is Happening:** There is a portal to Dalaran on the right down the stairs after entering Ulduar, but it is currently inactive and you cannot click it. (See screenshot below)

![WoWScrnShot_012020_193724](https://user-images.githubusercontent.com/34783736/72765863-89cc9d00-3bbc-11ea-8c03-d2c315e9ad26.jpg)

**What Should happen:** The portal should be usable like any other mage portal or the one in Trial of the Crusader and should bring you to Dalaran upon being used.

**Comment by Keader** [comment]
Blizzlike.
Those portal is not for players, a event with npcs should happens there.
