### ISSUE TITLE
[Forge of Souls] All NPC

### ISSUE THREAD

**Issue by WhitephoenixTheBunny** [WoWManiaUK/Redemption#4050]
Well, ALL the NPCs fell under texture when you iniciate combate.
The instance is undoable

![image](https://user-images.githubusercontent.com/31921098/72924175-633b6d00-3d48-11ea-979c-09ac29382f40.png)
![image](https://user-images.githubusercontent.com/31921098/72924201-6f272f00-3d48-11ea-9f66-e057947d967b.png)

**Comment by Rushor** [comment]
can you check on dev aswell? it works there

**Comment by Rushor** [comment]
https://i.imgur.com/taZBzJc.jpg

**Comment by WhitephoenixTheBunny** [comment]
I did fos, cuz a lot of ppl complaining on world chat :P weird it worked for you...

**Comment by wow-mania** [comment]
Try on dev again please.
