### ISSUE TITLE
[Achievements/Statistics] Numbers

### ISSUE THREAD

**Issue by jarvik76** [WoWManiaUK/Redemption#4051]
**Links:**

**What is Happening:**
Many boss kills in dungeons raids are being counted incorrectly in "statistics" page in player details, including LDW and Marrowgar.
Instead the statistics is counting the total of both 10 and 25-person versions for each individual.
In some 5-man dungeons, the HC and nm versions are being summed instead.

![image](https://user-images.githubusercontent.com/46089380/72925482-ac8cbc00-3d4a-11ea-9184-6d807a8ace7d.png)
Reached 80 on 29th December, thus maximum number of ICC kills per boss should be 4.
However:
![image](https://user-images.githubusercontent.com/46089380/72925656-f7a6cf00-3d4a-11ea-9707-aa4d3987a5b2.png)
vs the real situation:
![image](https://user-images.githubusercontent.com/46089380/72925782-2de44e80-3d4b-11ea-845e-23fb65c3e41f.png)

**What Should happen:**
The number of boss kills should be listed per normal and HC mode.

**Comment by jarvik76** [comment]
Also suspected, bosses in the "Icecrown" dungeons of Forge of Souls, Pit of Saron, Halls of Reflection
![image](https://user-images.githubusercontent.com/46089380/72930919-db0f9480-3d54-11ea-97f6-4d70716433bc.png)

**Comment by Kitzunu** [comment]
This will probably be as-is but I can take a look at it when I get some time over.
Perhaps even Janitor can take a look

**Comment by Keader** [comment]
If i remember right, it's calculated by clientside no?

**Comment by Kitzunu** [comment]
I have come to understand that it is stored in character_achievement or whatever the table is called.

So what I am investigating atm is if perhaps there is something faulty with Achievement_criteria.dbc because for example killing Marrowgar 10nm gives a point for all difficulties

**Comment by Kitzunu** [comment]
For self:
SELECT * FROM db_achievement_12340 WHERE title_lang_enus LIKE '%Gunship Battle victories%';
SELECT * FROM db_achievement_12340 WHERE description_lang_enus = ''; 
SELECT * FROM db_achievement_12340 WHERE category IN (14807,14821,14822,14823,14963,15021,15062);
SELECT * FROM db_achievement_12340 WHERE id IN (4726,4727,4639,4640,4641,4642,4604,4531);
SELECT * FROM db_achievement_criteria_12340 WHERE achievement_id IN (4726,4727,4639,4640,4641,4642,4604,4531);

**Comment by Kitzunu** [comment]
This is supposedly a bug from retail.

Until I can figure out what is causing it I will close it as Won't Fix
