### ISSUE TITLE
[NPC] Crok will not engage in combat with adds at the Frost Wing

### ISSUE THREAD

**Issue by blindead** [WoWManiaUK/Redemption#4052]
**Links:**

**What is Happening:**
Crok and his power rangers, after initiating the role play, should engage in combat with the adds in the Frost Wing in ICC. However, they will run in and stand still, not entering combat. 

Add HP will reset to 100% when damaged and are not killable, and the raid comes to dreadful halt.

**What Should happen:**
They should begin combat and thus continue the event chain to open the door to loot dragon.

**Comment by Dranah** [comment]
@blindead does this happen consistently or just 1 time so far? Also, have you engaged the adds before Crok finished the talk and charged in?

**Comment by blindead** [comment]
@Dranah happening to every single raids, at least on horde side.

and no, we did not touch the adds until crok finishes his roleplay ("enough banter...") and moves into the wing.

at SVT 03:47, the same bug happened again.

**Comment by blindead** [comment]
happening in both 10 man, 25 man, both nm and hrc.

**Comment by blindead** [comment]
at svt 1941, in icc25hrc, confirmed that the fix is applied. Thank you.

**Comment by Keader** [comment]
Please do not close It.
Janitor Will do
