### ISSUE TITLE
[Item] Arthas Menethil's Oathbinder

### ISSUE THREAD

**Issue by cathyr1** [WoWManiaUK/Redemption#4055]
There is a bug that prevents to equip this ring https://www.wow-mania.com/armory/?item=90025.

An error message about arena appears despite not in the arena.
![Pic](https://user-images.githubusercontent.com/30184491/73005366-25524d80-3e09-11ea-92f5-b08a262cdc16.png)

**Comment by Kitzunu** [comment]
I think this is because some weird implementation to prevent them in arena...

@Keader Why not just add
```sql
UPDATE `item_template`  SET `flasg`=`flags`|67108864 WHERE `entry` = 90025 -- 67108864 | 0x04000000 | Item cannot be used in arena
```

**Comment by wow-mania** [comment]
This is working fine and the fix works.
We are currently working with code from Jan 12 on Redemption to find another issues.
As soon as we finish this will be back to normal.

**Comment by Keader** [comment]
Not work @Kitzunu.
It prevent USE of item (like trinket use).
We dont have nothing to prevent EQUIP.
USE and EQUIP is 2 different things.
I already fixed this issue (reported by Dranah 2 weeks ago)
It's a regression like janitor said, fix will back soon.

**Comment by Kitzunu** [comment]
Oh I thought 67108864 | 0x04000000 | Item cannot be used in arena was so ppl cannot equip
