### ISSUE TITLE
Subscription cancel

### ISSUE THREAD

**Issue by FPSTordah** [WoWManiaUK/Redemption#4062]
I'm sorry I can't find another place to report this, however I am trying to cancel my subscription but it's not letting me.

**What is Happening:**
Error
An internal server error occurred.

**What Should happen:**
Should be canceling it.

**Comment by Kitzunu** [comment]
PM Janitor on Discord and he will sort it out.

I have forwarded this to him as well so he can fix the issue as Github is only for ingame issues.

Thank you!
