### ISSUE TITLE
[Item] Dr. Terrible's "Building a Better Flesh Giant"

### ISSUE THREAD

**Issue by grimwaldo123** [WoWManiaUK/Redemption#4063]
**Links:**
https://www.wowhead.com/quest=13043/the-sum-is-greater-than-the-parts
https://www.wowhead.com/item=42772/dr-terribles-building-a-better-flesh-giant
http://www.wow-mania.com/armory?quest=13043
https://www.wow-mania.com/armory/?item=42772
**What is Happening:**
I killed the mob who should drop the item more than 9-10 times but it doesnt drop it

**What Should happen:**
the mob should drop the item that starts the quest

**Comment by Kitzunu** [comment]
Dropped by https://www.wow-mania.com/armory/?npc=30409

**Comment by Kitzunu** [comment]
Dr. Terribles "Building a Better Flesh Giant" only drops if player has completed Deep in the Bowels of The Underhalls OR
Dr. Terribles "Building a Better Flesh Giant" only drops if player has taken Deep in the Bowels of The Underhalls

Also has those conditions

**Comment by grimwaldo123** [comment]
i did complete the quest
also i killed Apprentice Osterkilgr many times but he does not drop it

**Comment by Kitzunu** [comment]
Ok I will reopen, The item ONLY DROPS if you have TAKEN the quest OR COMPLETED the quest. Not if you have REWARDED the quest.

This needs to be investigated if it is correct or not

**Comment by grimwaldo123** [comment]
but this closes a long chain of quests

**Comment by WhitephoenixTheBunny** [comment]
@Kitzunu and @wow-mania armory need be update if 

> "The item ONLY DROPS if you have TAKEN the quest OR COMPLETED the quest. Not if you have REWARDED the quest."

as there is any requirement in it

**Comment by grimwaldo123** [comment]
i also remember i did complete it but when i checked the mob for loot it wasnt there

**Comment by Kitzunu** [comment]
I will add so the book can also be looted if you have rewarded the quest

**Comment by Rushor** [comment]
works. nice catch. that issue happens to many items actually. good to havw that one fixed
