### ISSUE TITLE
[Core] Parry

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#4065]
**Links:** https://wowwiki.fandom.com/wiki/Expertise

**What is Happening:** Expertise cap to never be parried in 3.3.5a is 56 expertise, which nobody obviously runs. Bosses usually are dps'd from behind (in a 180 degree angle) to avoid getting parried since bosses can only parry from the front. However, bosses on mania seem to currently be unable to parry whatsoever, even from the front. I do not recall ever seeing a parry and in 2 hours of icc 25, not a single parry was recorded for any of the melee classes in the raid. 

This means that players dpsing from behind currently gain 0 benefit, which is kinda huge in my opinion, as it adds to the positioning aspect of playing melee.

**What Should happen:** Bosses should have a 14% base chance to parry player melee attacks coming from the front.

**Comment by slaniaxx** [comment]
^^ still broken in live
