### ISSUE TITLE
World updates and improvements

### ISSUE THREAD

**Issue by Kitzunu** [WoWManiaUK/Redemption#4067]
- [ ] Plaguehoof & Bloodsunder & Icefury added to the game.

- [ ] Gorkun Ironskull - Added gossip menu

- [ ] Martin Victus - Fixed unit_flags UNIT_FLAG_IMMUNE_TO_PC UNIT_FLAG_UNK_6

- [ ] Dark Ranger Loralen & Coliseum Champion (1) & Archmage Elandra (1) <Kirin Tor> Unit_flags UNIT_FLAG_UNK_6 UNIT_FLAG_UNK_15

- [ ] Vision Guide Kill Credit Trigger - added Trigger flag

- [ ] Infernaling Summoner Damage Trap - Added to DB

- [ ] Infernaling Summoner - Added to DB

- [ ] Great Brewfest Kodo - update creature movement & added to the game

- [ ] ZONE Unu'pe - Fixed some armor and movement.

- [ ] QUEST Smash the Pumpkin - Fixed reward item.

- [ ] QUEST Nolkai's Words - Fixed reward item.

- [ ] QUEST Ally of the Netherwing - Fixed RewardChoiceItem

- [ ] QUEST He Will Walk The Earth... - Fixed RewardChoiceItem

- [ ] QUEST Hero of the Mag'har - Fixed RewardChoiceItem

- [ ] ZONE Area52 - Added missing spawns

- [ ] Fixed gossip_menu_option text for some guards.

- [ ] Add equipment to some creatures.

- [ ] QUEST Improve Dark Iron Legacy - cosmetic improvements

- [ ] QUEST Standards and Practices - Corrected some spawn locations.

- [ ] Defias Miner - Movement fixed

**Comment by Rushor** [comment]
general fixes by the big mother project - looking good!
