### ISSUE TITLE
[Vehicle] Campaign Warhorse in Icecrown for quest:  At The Enemy's Gates

### ISSUE THREAD

**Issue by Rushor** [WoWManiaUK/Redemption#4069]
Stabled Campaign Warhorse can currently be mounted without any kind of lance equipped (Argent Lance for example).
As noted here, they should require a lance.
https://wowwiki.fandom.com/wiki/Stabled_Campaign_Warhorse

http://cata.cavernoftime.com/?search=At+the+Enemy%27s+Gates

**Comment by Keader** [comment]
again?
https://github.com/fvicaria/WoW-Mania/issues/150

**Comment by Rushor** [comment]
okay. fixed an other issue there. requirment to have the lance equiped to mount added.

https://i.imgur.com/F1Ll1uU.jpg
https://i.imgur.com/dPZzZ8z.jpg
