### ISSUE TITLE
[Pet] Shimmering Wyrmling - Hover

### ISSUE THREAD

**Issue by Rushor** [WoWManiaUK/Redemption#4071]
http://wotlk.cavernoftime.com/?search=Shimmering+Wyrmling#items

That pet should hover much higher in the air beside the player.

**Comment by Kitzunu** [comment]
According to this vid it shouldnt be that high as in your image https://youtu.be/Z4oUHE8Ce-M?t=24

**Comment by Rushor** [comment]
okay from live version https://gyazo.com/54f8ed074a26251f91d755b81cc0afdc

updated https://gyazo.com/54f8ed074a26251f91d755b81cc0afdc

**Comment by Kitzunu** [comment]
same link x) 
but ok

**Comment by Rushor** [comment]
so many links open https://www.youtube.com/watch?v=MnFFVvxJaQg xD

**Comment by Kitzunu** [comment]
Haha :D
