### ISSUE TITLE
[Pet] Lurky's Egg + Pink Murloc Egg (22114) + Blue Murloc Egg (20371)

### ISSUE THREAD

**Issue by Rushor** [WoWManiaUK/Redemption#4072]
http://wotlk.cavernoftime.com/item=30360

The pet should dance from time to time. Fix added. 

https://gyazo.com/fbaf4dfaaae04b1900add130a2a3f089

**Comment by Rushor** [comment]
added that for Pink Murloc Egg (22114) + Blue Murloc Egg (20371) aswell.

**Comment by Kitzunu** [comment]
Lurky is not fixed

**Comment by Rushor** [comment]
you need to wait some time to get it triggered

**Comment by Kitzunu** [comment]
yea, but the 2 other worked x)

**Comment by Rushor** [comment]
every 60 -120 seconds https://gyazo.com/29d236b529b0da0f940d621206361af6
