### ISSUE TITLE
[Quest] Eye of the Emberseer chaining

### ISSUE THREAD

**Issue by grimwaldo123** [WoWManiaUK/Redemption#4073]
**Links:**
https://classic.wowhead.com/quest=6804/poisoned-water
http://www.wow-mania.com/armory?quest=6804

**What is Happening:**
The questgiver (Duker Hydraxis) is not showing the quest even after doing stormers and rumblers
https://www.wow-mania.com/armory/?quest=6805

**What Should happen:**
He should should give the quest

**Comment by Kitzunu** [comment]
You can only do 1 of the quests. They cancel each other out.

Quest progression 
Neutral 15 [56] Poisoned Water / Neutral 15 [57] Stormers and Rumblers
Neutral 15 [60R] Eye of the Emberseer
Neutral 15 [60R] The Molten Core
Neutral 15 [60] Agent of Hydraxis
Neutral 15 [60R] Hands of the Enemy
Neutral 15 [60] A Hero's Reward

**Comment by grimwaldo123** [comment]
he is not showing any other of the quests you mentioned after doing stormers and rumblers

**Comment by grimwaldo123** [comment]
I checked wowhead comment section too it says both quests can be done together
https://classic.wowhead.com/quest=6821/eye-of-the-emberseer#comments

**Comment by Kitzunu** [comment]
ok I will look into this

**Comment by Kitzunu** [comment]
Okay I found the issue LOL.

**Comment by Kitzunu** [comment]
Okay issue was:

Quest 6804 did not have a creature_queststarter assigned, so it would be impossible to do.

Open a ticket ingame and ask them to add that quest to you :)

**Comment by Rushor** [comment]
@Kitzunu 

pls remove that fix. the quest is not available in 3.3.5

hazyred on 2009/04/03 (Patch 3.0.9)
That's actually correct. Spoke with a gm today and he mentioned that the quest is indeed removed.
https://www.wowhead.com/quest=6804/poisoned-water#comments

**Comment by Kitzunu** [comment]
O.o must have missed it...

Then I will remove it from quest_template_addon so both are not needed

**Comment by Rushor** [comment]
Thanks!

can you also remove https://www.wowhead.com/quest=6821/eye-of-the-emberseer

SELECT * FROM quest_template_addon WHERE id=6804

maybe check all quests while you are at it. most of them are outdated in that zone

**Comment by Kitzunu** [comment]
Yea I removed everything from quest_template_addon that wasn't neccessary and added quest_template addon for 6821 to prevquest 6805

**Comment by Rushor** [comment]
alright!
