### ISSUE TITLE
[NPC] Blood Elf Magister - Missing Pathing-, Cast-, Emotescript

### ISSUE THREAD

**Issue by Rushor** [WoWManiaUK/Redemption#4076]
This creature should walk around, handle emotestae 69 and cast spell http://wotlk.openwow.com/spell=32760 from time to time to a close dummy.

Fix: https://gyazo.com/3ebadffc54a96b445a6f2c6378a1ff45

**Comment by Kitzunu** [comment]
Not fixed

**Comment by Rushor** [comment]
i only added it for this guid:
[21:59:52]DB GUID: 63517, current GUID: 178.

that works fine :)

**Comment by Kitzunu** [comment]
Oh, didnt know it was only for 1 guid
