### ISSUE TITLE
Huge quest fix :)

### ISSUE THREAD

**Issue by Kitzunu** [WoWManiaUK/Redemption#4080]
Fixed 392 quests to prevent them from showing (!) over an NPC's head while you do not meet the requirements to pick up the quest.

**Comment by jarvik76** [comment]
| NPC id
-- | --
- [ ] | 773
- [ ] | 1373
- [ ] | 1449
- [ ] | 1872
- [ ] | 2198
- [ ] | 2357
- [ ] | 2530
- [ ] | 3189
- [ ] | 3616
- [ ] | 4709
- [ ] | 4984
- [ ] | 5111
- [ ] | 5878
- [ ] | 5887
- [ ] | 5888
- [ ] | 5900
- [ ] | 5901
- [ ] | 6171
- [ ] | 6179
- [ ] | 6266
- [ ] | 6408
- [ ] | 6410
- [ ] | 6411
- [ ] | 6735
- [ ] | 6741
- [ ] | 6746
- [ ] | 6826
- [ ] | 6929
- [ ] | 7775
- [ ] | 7876
- [ ] | 8997
- [ ] | 9459
- [ ] | 10877
- [ ] | 10878
- [ ] | 10879
- [ ] | 10880
- [ ] | 10881
- [ ] | 11814
- [ ] | 11878
- [ ] | 12696
- [ ] | 12724
- [ ] | 12862
- [ ] | 12863
- [ ] | 12864
- [ ] | 14305
- [ ] | 14392
- [ ] | 14394
- [ ] | 14444
- [ ] | 15191
- [ ] | 15192
- [ ] | 15295
- [ ] | 15440
- [ ] | 15612
- [ ] | 15891
- [ ] | 15892
- [ ] | 16588
- [ ] | 17226
- [ ] | 17241
- [ ] | 17242
- [ ] | 18266
- [ ] | 18267
- [ ] | 18802
- [ ] | 19202
- [ ] | 20722
- [ ] | 20724
- [ ] | 21797
- [ ] | 22293
- [ ] | 22817
- [ ] | 22818
- [ ] | 22941
- [ ] | 23316
- [ ] | 23831
- [ ] | 23973
- [ ] | 24117
- [ ] | 24155
- [ ] | 24494
- [ ] | 24519
- [ ] | 25233
- [ ] | 25256
- [ ] | 25272
- [ ] | 25273
- [ ] | 25280
- [ ] | 25327
- [ ] | 25729
- [ ] | 26440
- [ ] | 26441
- [ ] | 26505
- [ ] | 26875
- [ ] | 26896
- [ ] | 27102
- [ ] | 27266
- [ ] | 27317
- [ ] | 27348
- [ ] | 27388
- [ ] | 27582
- [ ] | 28095
- [ ] | 28503
- [ ] | 28667
- [ ] | 28668
- [ ] | 29053
- [ ] | 29796
- [ ] | 29804
- [ ] | 30007
- [ ] | 30223
- [ ] | 30596
- [ ] | 30657
- [ ] | 30677
- [ ] | 30683
- [ ] | 30686
- [ ] | 30714
- [ ] | 30944
- [ ] | 30946
- [ ] | 31044
- [ ] | 31240
- [ ] | 31241
- [ ] | 31259
- [ ] | 31261
- [ ] | 31304
- [ ] | 31892
- [ ] | 33532
- [ ] | 33533
- [ ] | 33542
- [ ] | 33625
- [ ] | 33646
- [ ] | 33647
- [ ] | 33658
- [ ] | 33659
- [ ] | 33759
- [ ] | 33762
- [ ] | 38293
- [ ] | 38295
- [ ] | 38316
- [ ] | 39509

**Comment by jarvik76** [comment]
All 134 and 392 quests now look correct
