### ISSUE TITLE
[Reputation] Tournament Dailies

### ISSUE THREAD

**Issue by WhitephoenixTheBunny** [WoWManiaUK/Redemption#4083]
Doing the dailes at tournament, all the quests gave me reputation with Stormwind, but when delivring At The Enemy's Gates I got rep with Stormwind, but I got Honored with Exodar. I already am Honored with Stormwind

When delvring the quest:
![image](https://user-images.githubusercontent.com/31921098/73362131-30402e80-429e-11ea-87ee-d0c31aacbb77.png)
![image](https://user-images.githubusercontent.com/31921098/73362150-37ffd300-429e-11ea-8b8f-80e506a3b625.png)

My Rep tab:
![image](https://user-images.githubusercontent.com/31921098/73362187-464def00-429e-11ea-8ae4-752fb71fdb64.png)

EDIT:
tomorrow I will check the rep at start and end of dailies.

Don't close 'till tomorrow please

**Comment by Rushor** [comment]
can you check that @Kitzunu ?

**Comment by Blyatman1** [comment]
"At level 77 and above, characters can also gain reputation with their faction's races by completing quests for the Argent Tournamnt. Each Valiant quest rewards 250 reputation points for the appropriate race, and 62.5 for each of the other races in the faction. (e.g. Completing a daily quest as a Valiant of the Undercity gives 250 Undercity reputation, 62.5 Orgrimmar, 62.5 Thunder Bluff, etc.)"

https://wow.gamepedia.com/Reputation

**Comment by Kitzunu** [comment]
I do not know why At The Enemy's Gate would make you honored with Exodar because it does only reward faction XP for

72 - STORMWIND
1094 - THE SILVER COVENANT
