### ISSUE TITLE
[Quest/NPC] The Missing Diplomat/Tapoke Jahn

### ISSUE THREAD

**Issue by jarvik76** [WoWManiaUK/Redemption#4084]
**Links:**
http://www.wow-mania.com/armory/?quest=1249
http://www.wow-mania.com/armory/?npc=4962

**What is Happening:**
During quest 1249 "The Missing Diplomat", players are asked to subdue Tapoke Jahn (4962).  However, for high level players, one hit kills him and fails the quest, even naked.

**What Should happen:**
Tapoke Jahn should not die, he should be reduced to 1 hp and stop combat ("be subdued").

**Comment by Kitzunu** [comment]
@Rushor This will have to wait since we are on Code + DB freeze :(

But pls PM me in discord how you would fix this, because I want to learn :D

**Comment by Rushor** [comment]
i need some fixes aswell :D 

well invinsible hp must be set

**Comment by wow-mania** [comment]
This needs to be confirmed before any work is done to change anything, please.

**Comment by Rushor** [comment]
we will check it

**Comment by Rushor** [comment]
yes confirmed, there must be a checkt that he does not die before the quest is completed - no matter what damage

**Comment by Rushor** [comment]
fixed - creature will no longer go down 1 hp.

you need to test it with normal spells

**Comment by jarvik76** [comment]
Looks good, thanks @Rushor :)
