### ISSUE TITLE
[Item] Missing Disenchant template for Ruby Sanctum items

### ISSUE THREAD

**Issue by Rushor** [WoWManiaUK/Redemption#4085]
(23461,53103,53110,53111,53112,53113,53114,53115,53116,53117,53118,53119,53121,53125,53126,53127,53129,53132,53133,53134,53486,53487,53488,53489,53490,54556,54557,54558,54559,54560,54561,54561,54561,54562,54563,54564,54565,54566,54567,54569,54571,54572,54573,54576,54577,54578,54579,54580,54581,54582,54583,54584,54585,54586,54587,54588,54589,54590,54591);

All those items had missing disenchants.

Reported by @jarvik76 

Fixed in dev

**Comment by jarvik76** [comment]
Tested fix on:
53112
53117
54576
54578
54586
54561
All passed.

Note 23461 should not be included in above list and (correctly) is still not disenchantable.
