### ISSUE TITLE
[NPC/Dungeon] Shadowy Mercenary (Halls of Reflection)

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#4086]
**Links:** https://www.wowhead.com/npc=38177/shadowy-mercenary#abilities
https://www.wowhead.com/spell=72326/shadowstep

**What is Happening:** In the first part of Halls of Reflection, the 10 waves, the [Shadowy Mercenary](https://www.wowhead.com/npc=38177/shadowy-mercenary#abilities) enemies will frequently cast [Shadowstep](https://www.wowhead.com/spell=72326/shadowstep) on party members while fighting. If the targeted player happens to have his back too close to a wall or corner, the Mercenary can teleport behind the wall and fall under the map. When this happens, the enemies quickly de-spawn as a 'fail-proof' mechanic I guess. Usually you can walk to the center of the room to restart the event, but sometimes it won't work at all and the instance becomes soft-locked. Many new players seem unaware of this issue and will hug walls, causing the issue to happen often for some.

**What Should happen:** These Shadowy Mercenaries should never teleport through walls.

**Comment by jarvik76** [comment]
Have witnessed the above but not been able to replicate it specifically & consistently.
Had also thought it may be the [Phantom Mage](https://www.wowhead.com/npc=38172/phantom-mage) using [Hallucination](https://www.wowhead.com/spell=72342/hallucination).  

https://www.wowhead.com/npc=38172/phantom-mage
https://www.wowhead.com/spell=72342/hallucination

**Comment by Rushor** [comment]
map related i guess - can you check that @Keader - Maybe disable the shadowstep for them for now?

**Comment by Keader** [comment]
will take a look in this weekend

**Comment by jarvik76** [comment]
Note that if this is map related, I have seen it happen in both of the common alcove tanking areas, i.e. the circles in the below img (where A is the instance entrance)
![image](https://user-images.githubusercontent.com/46089380/73591296-cebdd100-44e4-11ea-80c5-882a1f6b5670.png)

**Comment by Keader** [comment]
I added a protection, if rogue fall of map, he will teleport back to the middle

**Comment by Keader** [comment]
@jarvik76 can you confirm fix on ptr?

**Comment by jarvik76** [comment]
Not really since I was not able to replicate the issue reliably in the first place.

**Comment by jarvik76** [comment]
I have observed the  Shadowy Mercenary alone, he does now seem to shadowstep correctly - i.e. if where he would go to would be in the wall, he now stays within the playable area.  Tested around all parts of the alcove.
At no point did the waves despawn.
If this is what is causing the reset, I believe it may be fixed.  I will add the Confirmed Fix label for now.
