### ISSUE TITLE
[Boss/Blood Furnace] Fixed issues with Broggok wipe

### ISSUE THREAD

**Issue by Keader** [WoWManiaUK/Redemption#4088]
Fixed issues that dont allow players start fight after wipe in Broggok.
Added missing spells in Prisioners too.

**Comment by Rushor** [comment]
does not work yet or restart missing? 

https://i.imgur.com/v6IX55g.jpg

the door opens after wipe, but creatures don't attack :o

**Comment by Keader** [comment]
Fixed xDD
