### ISSUE TITLE
[Item/Proc] Toxic Revenger

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#4097]
https://ptr.wowhead.com/item=9453/toxic-revenger

**What is Happening:**
The item does not proc the poison cloud effect (or it is so rare that an hour of test session wasn't enough to see one proc)

**What Should happen:**
The poison proc should occur approximately 3 times per minute.
Note: While it is unclear if it runs on an actual ppm mechanism (which didn't exist in classic I believe), this translates to either 4-5% proc chance on each attack, or possibly a higher proc (15-20%?) paired with a 15seconds internal CD, although that is unconfirmed. (I could not find data if the effect is able to overlap itself or if it can proc while it is already active once)

**Comment by Kitzunu** [comment]
![image](https://user-images.githubusercontent.com/24550914/73615930-4edf5600-460d-11ea-9e08-069517af01f8.png)

in DB it runs on a 1.5 spellppmRate

After a short test on like 10 minutes, I get it to proc about every 1.5 minutes after the aura has expired from the target. (Sometimes it happened ~20 seconds after aura fade, but most times every 1.5 minutes)

**Comment by Dranah** [comment]
If it currently procs every 1,5 mins doesn't that translate to 0,67 ppm?
Anyway, the proc seems insanely low. If it can be tuned a bit, that'd be nice. In general vanilla content items tend to be lackluster on private servers due to their nonexistant procs, which is sad. 
I'm aware that it's low level items and nothing gamebreaking, but fixing these procs could possibly benefit levelers and twinks which can do a good impression on newcomers to the server, that's why I decided to report.

**Comment by Kitzunu** [comment]
Yea, I never think such things really got worked on, not even onTC (I might be wrong)

**Comment by Kitzunu** [comment]
I changed the procppmRate to 2.5 so it will always proc 2 times and has a chance to proc 3 times per minute.
