### ISSUE TITLE
[Item] Abomination's bloody ring

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#4098]
item ID 51913

**What is Happening:**

There is an error when you attempt to pick this item up directly from the chest of Gunship armory, saying you can only carry one of this:
![image](https://user-images.githubusercontent.com/31132743/73615264-97dfdc00-4606-11ea-92e3-fa987a3dfe6a.png)
This happens if you have already one of these rings in your bags or bank, even though this item is not unique (just unique equipped, which means you cannot WEAR more than one.)
Note: Odd enough, other players who pick it up can trade it to you after so you can disenchant it, but not every puggie might be bright enough to figure that.

**What Should happen:**
You should be able to pick this item up regardless of already having one in your bags/bank, because it is not unique.

**Comment by Kitzunu** [comment]
I cannot reproduce this, I have tested having a ring on me, in my bag and in my bank and I still can pick up another one
