### ISSUE TITLE
[Boss/Raid] Attumen the Huntsman (Karazhan)

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#4100]
**Links:** https://www.wowhead.com/npc=16152/attumen-the-huntsman
https://www.wowhead.com/npc=16151/midnight

**What is Happening:** Sometimes after damaging [Midnight](https://www.wowhead.com/npc=16151/midnight), it is possible to kill him without his master [Attumen](https://www.wowhead.com/npc=16152/attumen-the-huntsman) ever getting on him and transitioning into the 'mounted' phase 2. Killing the horse in that manner causes the fight to end and no loot is obtained that way.

**What Should happen:** After sustaining a certain amount of damage, Midnight should always call for her master and transition the fight into phase 2, no matter what. It should not be possible to 'miss' the mounting phase.

P.S.: Also this boss seems to do very high damage for the level (3k+ hits from both horse and master on a level 80 character).

**Comment by Rushor** [comment]
We can add a save check in damage taken - the high damage is a real problem yes. Need to be fixed

**Comment by wow-mania** [comment]
This is typical of low level bosses being over-dpsed by level 80s.
This causes the NPC to skip steps of the script. You can limit the maximum damage that the boss will take at any one time.

**Comment by Rushor** [comment]
fyi: there is one spell that has wrong sclaing that needs adjustment. will check that

**Comment by Oganku** [comment]
Usually I do this boss as prot when I solo him and I don't do that much damage since he aslo applies this hit debuff. The fight typically can take upwards of 3 minutes and it can still fail to transition. I feel a simple "damage-per-hit cap" might not solve it entirely.

**Comment by Rushor** [comment]
damage reduced. health sav check added. so mount phase should always be triggered. only test after compile is done.

**Comment by Rushor** [comment]
tested it on testserver and seems fine so far - can another tester confirm pls :)
