### ISSUE TITLE
[Spirit Healer / Teleporter] DK's starting zone

### ISSUE THREAD

**Issue by WhitephoenixTheBunny** [WoWManiaUK/Redemption#4101]
When a DK dies and his ported to his spawning zone, he cannot ressurect.

The Spirit Healer is downstair and the ghost can't use the teleporter to ressurect.

**Comment by Kitzunu** [comment]
I cannot reproduce this on dev...
Pls try to find a way so I can reproduce it, cuz atm it works as it should from what I can see

**Comment by Rushor** [comment]
can you pls gps that  - then we could may add another spirit healer

- or try to use unstuck

**Comment by Oganku** [comment]
I'm pretty sure you can just jump down as a ghost even if the portal doesn't work as a ghost? There's a balcony on both floors.
