### ISSUE TITLE
Dedication of Honor

### ISSUE THREAD

**Issue by Altocs** [WoWManiaUK/Redemption#4104]
**Links:**
https://wow.gamepedia.com/Dedication_of_Honor

**What is Happening:**
Atm it is only the normal Dalaran Fountain in the middle that is shown.

**What Should happen:**
After Lich King is defeated the first time the fountain should change to Dedication of Honor.
This clearly never worked since Lich King is killed every week but still, there is the old fountain.

>  It becomes a permanent feature of Dalaran once someone on the server defeats the Lich King.

**Comment by Rushor** [comment]
will add that

**Comment by Oganku** [comment]
I have seen the statue thingy multiple times, but I'm not sure what triggers it (I thought it was first LOD of the weekly lockout) and it definitely isn't permanent right now. I can say the statues are always there, just invisible, cause you can still "feel" their hitboxes.

**Comment by Kitzunu** [comment]
Yes, it is because the game objects "Active" state will show the statues.
It can be triggered by a GM right-clicking on it.

**Comment by Rushor** [comment]
active now https://i.imgur.com/kUudpuW.jpg

**Comment by WhitephoenixTheBunny** [comment]
@Rushor It changes... Only on 25hc... no fix needed

**Comment by Kitzunu** [comment]
I cannot find ant patchnotes for that.
All I find is that it is always supposed to be active

**Comment by Rushor** [comment]
anyway - we can only make it active or inactive - cannot bind it to anything
