### ISSUE TITLE
Dalaran visitors event

### ISSUE THREAD

**Issue by Altocs** [WoWManiaUK/Redemption#4105]
**Links:**
https://wow.gamepedia.com/Dalaran_Visitor
https://www.wowhead.com/npc=32597/dalaran-visitor (Flying Machine)
https://www.wowhead.com/npc=32598/dalaran-visitor (Nether Drake)
https://www.wowhead.com/npc=32600/dalaran-visitor (Wyvern)
https://www.wowhead.com/npc=32601/dalaran-visitor (Argent Hippogryph)
https://www.wowhead.com/npc=32602/dalaran-visitor (Bronze Drake)
https://www.wowhead.com/npc=32596/dalaran-visitor (Armored Snow Gryphon)

**What is Happening:**
I noticed today that this event seems to never occur here.

**What Should happen:**
How it should work is that from time to time there should be landing NPC's (The ones above) on the Krausus' Landing and then dismount and run into the "entrance" of dalaran to then despawn.

> They can spawn on many different kinds of mounts, such as: the  [Argent Hippogryph], the  [Armored Snowy Gryphon], the Bronze Drake, or a flying machine, a wyvern, and a nether drake.

**Comment by Rushor** [comment]
all done https://gyazo.com/3b95ef5e8e6cac4c9e0af3506d386dda
https://gyazo.com/d0ce94987019028c22bae43529f425a5
https://gyazo.com/00b709c0c69e0cc1df5ff42444c9bde9

**Comment by Kitzunu** [comment]
Without being able to check retail, this seems great.

I just have one request and that is to fix so that when the NPC is riding the carpet he doesn't sit on it, but actually stands on it.

If you .aura the spell on the NPC it works as it should, but not through the script

**Comment by Rushor** [comment]
i would like to remove the carpet

**Comment by Kitzunu** [comment]
Works too ^^

**Comment by Rushor** [comment]
okay carpet gone lol
