### ISSUE TITLE
[Spell/Glyph] Glyph of Kilrogg

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#4106]
**Links:** http://www.wow-mania.com/armory?spell=126
http://www.wow-mania.com/armory?spell=58340

**What is Happening:** The [[Glyph of Kilrogg]](http://www.wow-mania.com/armory?spell=126) does not affect the summon from the warlock spell [[Eye of Kilrogg]](http://www.wow-mania.com/armory?spell=58340). Tested in Northrend and Outland and it currently doesn't work on either.

**What Should happen:** Using the glyph should increase the summon's speed by 50% and allow it to fly in areas where flight is allowed.

**Comment by Rushor** [comment]
Have a fix for That, can add if you wish

**Comment by Rushor** [comment]
in tbc and wotlk area, speed will be increased now and is able to fly - pls test
