### ISSUE TITLE
[Core] Party size/Dungeon Finder

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#4107]
**Links:** N/A

**What is Happening:** It is currently possible to be in a party of more than the usual maximum of 5 people. This happens quite often after a member of the group leaves and the remaining 4 people queue up to find a person to fill the vacant spot. Dungeon finder will then somehow allow 2 people to be matched and fill that single open spot. It will appear as if there's only 5 people on the party frame, but a sixth person will be able to chat in /p and see everyone else. Only the first member to join will be able to enter the instance, and the 6th will be forced to leave and get the deserter debuff. I have even had a party of 7 after someone left and we queued up to fill the spot and then invited someone manually. The invited person accepted and 2 people were still matched through dungeon finder.

**What Should happen:** Dungeon finder should never make groups larger than 5 people, and should never attempt to allocate a single open spot to 2 different players.

**Comment by wow-mania** [comment]
Unless this can be reproduced by a tester or dev it will be impossible to fix. 
We need steps to reproduce.

**Comment by Oganku** [comment]
Vote kick a dps in an rdf group and then re-queue the remaining 4 players. If there's more than 1 player in rdf queue waiting, it will almost always match 2 people at once. It's happened consistently enough lately for me to open this issue

**Comment by WhitephoenixTheBunny** [comment]
I can confirm, already happened to me

**Comment by Keader** [comment]
I need someone to confirm if is fixed on ptr please.

**Comment by Keader** [comment]
That's why i need someone to test it in PTR !
anyway, backing to this (original issue).
I will try fix again in this weekend.

**Comment by Keader** [comment]
I need someone to test if it fix the issue.
