### ISSUE TITLE
[Spell] Yaaarrrr / Flip Out

### ISSUE THREAD

**Issue by Kitzunu** [WoWManiaUK/Redemption#4108]
**Links:**
8221
8219
8222
8220 

**What is Happening:**
These spells are not counted as shapeshifts and therefore you are able to mount/use Druid flight form with any of these spells aurad on you.

**What Should happen:**
These 5 spells should count as a Shapeshift.

> 3. You can't mount or use flight paths.

**Comment by Keader** [comment]
rdy for test

**Comment by Kitzunu** [comment]
@Keader All fixed except Spell ID 58501 - Iron Boot Flask
