### ISSUE TITLE
[Spell] Sheath of Light

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#4114]
spell ID 53503

**What is Happening:**
Scaling issues, multiple.
1) The effect double dips every %mod such as ICC buff, Valithria healing stacks, 6% healing taken aura, or warrior's Mortal strike. This means it will perform way above intended in a buffed raid environment and it's getting overly negated in PVP when playing against a warrior.
2) The effect does not properly stack with itself. When the paladin crits healing twice in a row, the second sheath proc overrides the previous, instead of adding to it.

**What Should happen:**
1) Like every other effect that uses a fix percentage of another spell (dots such as ignite, healing such as Empowered Renew, damage such as Improved Devouring plague, etc...) Sheathe should also be a fix amount of healing that does not get modified from any effects on its own. 
It should always calculate solely from the healing that procs it and be exactly 60% of it (divided to 4 ticks)
2) Subsequent procs of Sheathe must stack and add up in a manner, that when a new sheath procs, it refreshes the duration to max and adds the remaining healing from the previous HOT to the new total amount. (same mechanic as ignite)

**Comment by Dranah** [comment]
Stacking fixed.
Double dipping persists still.

**Comment by Keader** [comment]
Try now pls :)
