### ISSUE TITLE
[Event] L70 ETC Shattrath & L70 ETC Shattrath Announce

### ISSUE THREAD

**Issue by Kitzunu** [WoWManiaUK/Redemption#4118]
The concert event in Shattrath has been fully scripted. Huge props and thanks to dr-j at trinitycore who scripted it all :)

![image](https://user-images.githubusercontent.com/24550914/74279491-4bd61b00-4d1b-11ea-997f-b1c0635b36d7.png)

**Comment by Rushor** [comment]
works great https://i.imgur.com/KnOBdIL.jpg event is 82

**Comment by Kitzunu** [comment]
81 - Announcement
82 - concert
