### ISSUE TITLE
[Item] Goblin Beam Welder

### ISSUE THREAD

**Issue by grigtsiouv** [WoWManiaUK/Redemption#4119]
**Links:**
https://www.wowhead.com/npc=28312/wintergrasp-siege-engine
https://www.wowhead.com/item=47828/goblin-beam-welder

**What is Happening:**
I cant seem to heal the siege engine with my goblin beam welder

**What Should happen:**
I should be able to heal it

**Comment by Rushor** [comment]
Maybe it is immune

**Comment by grigtsiouv** [comment]
wowhead comments suggest otherwise

29 | By cawfee (9,415 – 2·19·95) on 2009/06/28 (Patch 3.1.3)Another Engineering item that's marginally useful and will have its usefulness completely removed in subsequent patches. I can't wait! It's like they finally listened to us and gave us what we wanted.As a little example of the above statement (and to outline its only real possible use as of right now), a Wintergrasp Siege Engine has a base HP of 85,000 without player gear contribution. It will take an Engineer 10 seconds to restore 7000 health to said vehicle. | By cawfee (9,415 – 2·19·95) on 2009/06/28 (Patch 3.1.3) |   |  
-- | -- | -- | -- | --
By cawfee (9,415 – 2·19·95) on 2009/06/28 (Patch 3.1.3) |   |

**Comment by Rushor** [comment]
okay that is keader :>

**Comment by wow-mania** [comment]
@keader did some work here also so it may be a side-effect. I need to confirm with him.

**Comment by Keader** [comment]
Not related with anything that i did before.
To me, looks like clientside issue.
I can fix the spell issue (to heal vehicles) but i cant fix the item.
Problem is: When you click on item, it returns the "little hand" to select the target.
This part looks like handled by clientside, and it dont allow click in any mechanical creature :/
