### ISSUE TITLE
Target Dummy Not Taunting

### ISSUE THREAD

**Issue by BKnight07** [WoWManiaUK/Redemption#4120]
**Links:**

**What is Happening:**
My 14th level hunter is an engineer and created a stack of target dummies.  However, when I lay one down, it fails to "taunt" and draw any enemies.  I've tested in Westfall.  I shoot a boar (to make it hostile), lay down a dummy, and after several seconds, confirm that the dummy never "taunts" my target.  It stays on me the whole time (my pet is kept passive).

**What Should happen:**
I would expect dropping a target dummy to draw the aggro of my enemies.

**Comment by Rushor** [comment]
Will fix it

**Comment by Rushor** [comment]
taunting should work now https://i.imgur.com/SuIsZiu.jpg

**Comment by BKnight07** [comment]
As of just now, there's no change.  Do I need to wait for the server to be rebooted for the changes to take effect?  I attached a low rez video so you can see what I mean.  Let me know what you think.

[World of Warcraft 2020-02-12 480p.zip](https://github.com/WoWManiaUK/Redemption/files/4196025/World.of.Warcraft.2020-02-12.480p.zip)

**Comment by Kitzunu** [comment]
Tuesday next week

**Comment by Kitzunu** [comment]
![image](https://user-images.githubusercontent.com/24550914/74592572-df149680-5022-11ea-83a2-a8f2bfb4c069.png)

Works :)

**Comment by BKnight07** [comment]
Confirmed!  It's working as expected.  Thanks guys.

**Comment by Kitzunu** [comment]
Dont close.
Janitor does that when he updates

**Comment by BKnight07** [comment]
ok

________________________________
