### ISSUE TITLE
[Gob] Boss encounter doors

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#4122]
**Links:** https://wow-mania.com/armory/?object=185134 (Door before Prince Malchezaar in Karazhan)
https://wow-mania.com/armory/?object=184274 (Doors to the Nightbane boss area in Karazhan) (1/2)
https://wow-mania.com/armory/?object=184280 (Doors to the Nightbane boss area in Karazhan) (2/2)
https://wow-mania.com/armory/?object=176966 (Portcullis before Razorgore the Untamed in Blackwing Lair)

**What is Happening:** All doors linked above (gob 176966, 184274, 184280, 185134) are clickable and clicking on them makes them close forever. They work as they should otherwise if ignored by players. New players can easily click them and soft-lock themselves off continuing the instance.
(I'm most likely missing similar doors in the world)

**What Should happen:** These doors should only close once their respective encounters are started and they open upon defeating the boss or wiping.

**Comment by Rushor** [comment]
wuut i added a fix aswell now :S

**Comment by Rushor** [comment]
okay does not matter :D

**Comment by Kitzunu** [comment]
LOOOOL

**Comment by Kitzunu** [comment]
Doesn't matter to me either, so up to you :D

**Comment by Rushor** [comment]
works!
