### ISSUE TITLE
[Boss/Raid] Razorgore the Untamed

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#4123]
**Links:** https://classic.wowhead.com/npc=12435/razorgore-the-untamed
Issues: #2109, #2610, #3482 

**What is Happening:** This boss fight has multiple issues that have been reported in the past. There is a specific way to still get through him, but the majority of players do not know of it and end up being unable to progress further into the raid that otherwise works just fine.

Looking into what might cause the entire encounter to reset, I have determined the following:

- Killing adds that spawn during the fight has a high chance of resetting the encounter.
- Having Razorgore aggro'd onto adds as the mind control effect expires causes the encounter to reset.

Skimming through previous reports, I found the following in #2109:

> This one has been fully rewritten.
> - Razorgore and all the summoned adds will now despawn if he evades.
> - Eggs will now respawn when razorgore evades.

Most of the points of this 'rewritten script' are fine, but these first 2 are what's causing the encounter to fully reset multiple times.

Most mobs will start evading attacks when you break their aggro leash and they start pathing back to their original spot. What seems to be happening is that if the mind control effect ends while Razorgore is aggro'd on adds, he then starts pathing back to the position he would be at if he wasn't aggro'd. Problem is, not being able to kill the adds means a dozen projectiles are already on their way to hit him and he ends up evading.

Keeping the boss away from a sea of adds that cannot be killed and that will aggro him with any opportunity they get can be very tricky and exhausting, and near impossible for players unaware of the nature of the bug.

**What Should happen:** Is it necessary for the encounter to fully reset when the boss evades? This older script seems odd and results in a very broken fight. It is by far the most broken encounter on mania and I feel like it should be looked upon, or at least players should be given an alternative to progressing further into Blackwing Lair.

P.S. from #3482

Rushor commented on Dec 21, 2019
> Razorgore still resets at the start of the 3rd channeling.
>>will be fixed next year

**Comment by Rushor** [comment]
Yes will check today. So removing evade of all on evade of razor should be a big progress

**Comment by Karbaros** [comment]
I just tried it on my main account. (Everything works fine there) so it really can't be up to me.

**Comment by Rushor** [comment]
okay pls try it now - pn me in discord @tester . i need another mate for testing this!

**Comment by Rushor** [comment]
made some more changes concering the evade mechanic, pls check after compile is done

**Comment by Rushor** [comment]
https://i.imgur.com/DPk5s7F.jpg

works - on mind controle fade out, the encounter no longer resets.
