### ISSUE TITLE
[Dungeons Finder] no rewards and players are shown as unknown

### ISSUE THREAD

**Issue by Karbaros** [WoWManiaUK/Redemption#4124]
so I followed everything they said:

I am always connected to the internet via cable (but checked it, everything is ok)

I checked my firewall (everything is ok too)

I checked the settings and the update of my router (everything is ok)

did a Windows update, performed a virus scan, did a malware scan. ( Is everything OK )

I even reinstalled the game and the luncher.

**And the problem still exists!**

I always start the game via the luncher as admin

**Comment by wow-mania** [comment]
Send me a screenshot of your client login screen on discord

**Comment by WhitephoenixTheBunny** [comment]
Prolly related with https://github.com/WoWManiaUK/Redemption/issues/4107

**Comment by Karbaros** [comment]
the screenshots to Phoenix ?

**Comment by Kitzunu** [comment]
How did you reproduce it @WhitephoenixTheBunny ? I cannot reproduce it

**Comment by Rushor** [comment]
https://github.com/WoWManiaUK/Redemption/issues/4107 creates some strange issue on dev aswell for raid party. pn me in discord keader :)

**Comment by RyogoKusama** [comment]
> so I followed everything they said:
> 
> I am always connected to the internet via cable (but checked it, everything is ok)
> 
> I checked my firewall (everything is ok too)
> 
> I checked the settings and the update of my router (everything is ok)
> 
> did a Windows update, performed a virus scan, did a malware scan. ( Is everything OK )
> 
> I even reinstalled the game and the luncher.
> 
> **And the problem still exists!**
> 
> I always start the game via the luncher as admin

Thankfully I'm not the only one, people in world chat have been trolling every time I asked about this. T_T

I've been having the same exact issue in the past two days:

- People shown as Unknown in Party Finder, even with no AddOns (at first I thought it was my custom UI causing this issue, but sadly nope)

- No daily rewards for completing the duties (RIP Event, RIP Emblems of Frost)

I have noticed two things tho:

1- Relogging once inside the dungeon fixes the party visual bug and you can see/interact with people, but you still get NO rewards.
2- Everyone, except me/who has the same issue, has the "Luck of the Draw" buff https://www.wow-mania.com/armory/?spell=72221 which is the one you get for using the Random Dungeon/Heroic Finder, this is problably why upon completing the duty, we don't get the daily rewards?

I opened a ticket yesterday and a GM answered me quickly, but we couldn't fix this on my end and suggested to make a report here.

**Comment by WhitephoenixTheBunny** [comment]
@Kitzunu It just happened on 2 of my chars... I don't know how to reproduce, it just happened
![image](https://user-images.githubusercontent.com/31921098/74444937-7f28bf00-4e6d-11ea-82d1-5f2438c3bb90.png)

**Comment by Karbaros** [comment]
It was even the case that when all party members are shown as unknown and then, for example in the dungeon "the Nexus" you teleported in and out of the penultimate boss via the dungeon finder, the dungeon is reset but you stay in the group and see it others on the minimap

**Comment by Keader** [comment]
Ok, i reverted my previous fix, so... everything will looks ok again.
