### ISSUE TITLE
[Spells/Pet] Pets should not try follow target if is in stay and casting

### ISSUE THREAD

**Issue by Keader** [WoWManiaUK/Redemption#4125]
It fix some bugs related with Succubus trying cast seduction in a target outside of range with stay state.
Old behavior make succubus try follow the target and start a loop of try cast -> stop cast caused by move -> and repeat.

**Comment by Kitzunu** [comment]
Works, if out of range in stay state, auto-cast seduction is on and then I click to attack the succubus will run in range and then stand and cast seduction for the entire duration.

BUT, it has some weird stuff going on.
When she is out of mana she will run to max range and just stand there (Stay + Passive on) and then when she gets mana she will stand there at max range and cast it.
