### ISSUE TITLE
[Spell/Enchant] Lifeward need critical heals

### ISSUE THREAD

**Issue by Keader** [WoWManiaUK/Redemption#4126]
Enchant Lifeward need get criticals.

Proof: https://www.youtube.com/watch?v=XbDqU-J9Amk
https://www.youtube.com/watch?v=GwAApGUS2UQ

**Comment by Kitzunu** [comment]
![image](https://user-images.githubusercontent.com/24550914/74594396-3a03b900-5036-11ea-86bf-483e3c91010a.png)

Works :)
