### ISSUE TITLE
[Core/Spells] Chain Heal (Shaman) can wrong heal neutral units

### ISSUE THREAD

**Issue by Keader** [WoWManiaUK/Redemption#4127]
Chain Light need always select friendly units.
In some fights, some monsters has neutral faction, and it make Chain Light select they to heal.
A good example is spirits inside of frostmourne in Lich King Heroic. In some conditions Chain Light can heal they. Like the print shows:

![image](https://user-images.githubusercontent.com/7120913/74536635-3b8a8f80-4f17-11ea-8de5-117f10e81f75.png)

If someone find how reproduce it, can troll a lot of fights xD

**Comment by Kitzunu** [comment]
tested on dalaran guards, Chain Heal does not bounce Player -> NPC but it bounces NPC -> player if you cast on npc first.

Works :)
