### ISSUE TITLE
[Spell/Warlock] Immolate aura negative

### ISSUE THREAD

**Issue by Keader** [WoWManiaUK/Redemption#4128]
Spell need be positive. It means that it should appear as buff instead of debuff.
When appear as buff, player can cancel using right click on icon, it helps in fights with mind controlled players (yes kids, stop kill your friends).

**Comment by Kitzunu** [comment]
Well it shows blue as if it is a buff, but you cannot right-click it 
![image](https://user-images.githubusercontent.com/24550914/74593644-b0e88400-502d-11ea-8248-f6b4a062b167.png)

**Comment by Keader** [comment]
Immolate aura = Metamorphosis one, is not Immolate

**Comment by Kitzunu** [comment]
works x)
