### ISSUE TITLE
[Spell/DK] 2P T10 DK Tank

### ISSUE THREAD

**Issue by Keader** [WoWManiaUK/Redemption#4130]
2P T10 bonus should:

Description: Increases the damage done by your Death and Decay ability by 20%.

Problem is: it's incrementing the base damage, instead the final damage.
It make DK tanks lose a lot of threat caused by low damage.

**Comment by Kitzunu** [comment]
Yep works :)

Tested on naked char, without spell 70650 dmg is 102, with spell 70650 damage is 122
102*1.20 = 122
