### ISSUE TITLE
[Spell/Priest] Shadowfiend attack speed

### ISSUE THREAD

**Issue by Keader** [WoWManiaUK/Redemption#4133]
> Some brief things about Shadowfiend, taken from Elitist Jerks:
> - Attacks are melee shadow damage, using a normal melee attack table, with damage reduced based on armor of the target
> - **Has ~1.5second attack speed (10 times per 15 second life)**
> - Benefits from your +dmg with a ~65% coefficient (6.5% per hit)
> - Damage added from Shadowform, Darkness, Shadow Weaving, Misery, Curse of Shadow, and Improved Shadow Bolt, and so on.
> - Damage added from attack power bonuses (possibly double-dipping - the direct buff, and scaled with your stats), armor reductions on the target, and so on
> - Benefits from Bloodlust/Heroism and similar buffs IF the fiend is already out when it's cast.
> - Has extremely high dodge rating (in the vicinity of 75%) and significant resistances to most/all spell schools

Attack speed was wrong, it means: less mana for priests and less damage.
Fixed.

**Comment by Kitzunu** [comment]
Works, now attack 10 times :)
