### ISSUE TITLE
NPC Updates

### ISSUE THREAD

**Issue by Kitzunu** [WoWManiaUK/Redemption#4135]
Just some small imports from Trinitycore, I will update this issue with all NPCs that have been changed in some way when I get home :)

**Sawemba** - Added script.
**Magister Savarin** - Added script.
**Wyrmcaller Vile** - Added script.
**Pool of Souls** - Added to the game and scripted.
**Raging Soul** - Fixed auras.
**Wildhammer Gryphon Rider** - Added to the game with movement.
**Alliance Berserker** - Added missing spawns.
**Alliance Ranger** - Added missing spawns.
**Alliance Cleric** - Added missing spawns.
**Ancient Draenei Spirit** - Added to the game.
**Hillsbrad Internment Lodge Quest Trigger** - Added to the game.
**Thrall Quest Trigger** - Added to the game.
**Blade Dance Target** - Added to the game.

**Comment by Rushor** [comment]
looks good! the spawns are really nice
