### ISSUE TITLE
[Items] Mounts "use" missing / amount of sell price

### ISSUE THREAD

**Issue by WhitephoenixTheBunny** [WoWManiaUK/Redemption#4138]
Several mounts are missing the "use" description:

23193 | Naxxramas Deathcharger Reins
63125 | Reins of the Dark Phoenix
64883 | Scepter   of Azj'Aqir
69213 | Flameward Hippogryph
69224 | Smoldering   Egg of Millagazor
69226 | Felfire Hawk
69230 | Corrupted   Egg of Millagazor
69846 | Winged Guardian
70909 | Vicious   War Steed
70910 | Vicious War Wolf
71665 | Flametalon   of Alysrazor
76755 | Tyrael's Charger
78924 | Heart   of the Aspects
85870 | Imperial Quilen
89305 | Reins   of the Green Shado-Pan Riding Tiger
89306 | Reins of the Red Shado-Pan   Riding Tiger
89307 | Reins   of the Blue Shado-Pan Riding Tiger
89362 | Reins of the Brown Riding Goat
89363 | Disc   of the Red Flying Cloud
89390 | Reins of the White Riding Goat
89391 | Reins   of the Black Riding Goat
89783 | Son of Galleon's Saddle
90710 | Reins   of the Ashen Pandaren Phoenix
90711 | Reins of the Emerald Pandaren   Phoenix
90712 | Reins   of the Violet Pandaren Phoenix
93168 | Grand Armored Gryphon
93169 | Grand   Armored Wyvern
93385 | Grand Gryphon
93386 | Grand Wyvern
93671 | Ghastly Charger's Skull
104011 | Stormcrow
109012 | Reins of the Corrupted Dreadwing
109013 | Reins   of the Dread Raven
112326 | Warforged Nightmare
112327 | Grinning Reaver
115484 | Core Hound Chain
116771 | Solar   Spirehawk
116791 | Challenger's War Yeti
121815 | Voidtalon   of the Dark Star
141713 | Reins of the Arcadian War Turtle
143643 | Reins   of the Abyss Worm
143643 | Reins of the Abyss Worm
147835 | Reins   of the Riddler's Mind-Worm
147835 | Reins of the Riddler's Mind-Worm
147901 | Luminous   Starseeker
149989 | Defiled Reins
150076 | Mystic   Runesaber
150513 | Vicious Skeletal Warhorse
150514 | Vicious   War Trike
150515 | Vicious War Ram
150516 | Vicious   War Mechanostrider
150517 | Vicious War Kodo
150518 | Vicious   War Elekk
150519 | Vicious Warsaber
150520 | Vicious   War Raptor
150521 | Vicious Warstrider
150522 | Vicious   Gilnean Warhorse
150523 | Vicious War Scorpion
150524 | Vicious   Golden King
150525 | Vicious War Turtle - A
150526 | Vicious   War Turtle - H
150527 | Midnight
150529 | Brawler's   Burly Basilisk
150530 | Lucid Nightmare
150531 | Wild   Dreamrunner
150532 | Prestigious Azure Courser
150533 | Prestigious   Bronze Courser
150534 | Prestigious Forest Courser
150535 | Prestigious   Ivory Courser
150537 | Prestigious Midnight Courser
150538 | Prestigious   Royal Courser
150539 | Felblaze Infernal
150540 | Hellfire   Infernal
150541 | Flarecore Infernal
150542 | Frostshard   Infernal
150543 | Coldflame Infernal
150553 | Russet   Ruinstrider
150554 | Amethyst Ruinstrider
150555 | Bleakhoof   Ruinstrider
150556 | Umber Ruinstrider
150557 | Cerulean   Ruinstrider
150558 | Sable Ruinstrider
150560 | Darkspore   Mana Ray
150561 | Lambent Mana Ray
150562 | Magenta   Mana Ray
150563 | Scintillating Mana Ray
150564 | Vibrant   Mana Ray
150565 | Felglow Mana Ray
150566 | Darkmoon   Dirgible
150567 | Orgrimmar Interceptor
150568 | Stormwind   Skychaser
150569 | Lightforged Warframe
150570 | Glorious   Felcrusher
150571 | Avenging Felcrusher
150572 | Blessed   Felcrusher
150573 | Crimson Slavermaw
150574 | Acid Belcher
150575 | Biletooth Gnasher
150577 | Vile Fiend
150578 | Antoran Gloomhound
150579 | Antoran   Charhound
150580 | Shackled Ur'zul
150581 | Shackled Ur'zul
150582 | Shackled Ur'zul
150583 | Shackled Ur'zul
150584 | Vicious   War Fox (Alliance)
150585 | Vicious War Fox (Horde)
152901 | Kirin   Tor Summoning Crystal
153594 | Xiwyllag ATV
155662 | Reins   of the Highmountain Thunderhoof
156487 | Reins of the Nightborne Manasaber
156564 | Shu-Zen,   the Divine Sentinel
159146 | Kua'fon's Harness
159842 | Sharkbait's   Favorite Crackers
161215 | Reins of the Obsidian Krolusk
161479 | Reins   of the Nazjatar Blood Serpent
161665 | Reins of the Cobalt Pterrodax
161773 | Reins   of the Alabaster Hyena
163042 | Reins of the Mighty Caravan Brutosaur
163063 | Reins   of the Spectral Phoenix
163183 | Spawn of Krag'wa
163576 | Captured   Dune Scavenger
163577 | Conquerer's Scythemaw
163586 | Squawks
163981 | Frenzied Feltalon

The next ones have an huge sell price (750g-1250g)

87781 | Reins of the Azure Riding Crane
87782 | Reins   of the Golden Riding Crane
87783 | Reins of the Regal Riding Crane
87784 | Reins   of the Jungle Riding Crane
87786 | Reins of the Black Riding Yak
87787 | Reins   of the Brown Riding Yak
87788 | Reins of the Grey Riding Yak
87789 | Reins   of the Blonde Riding Yak
87791 | Reins of the Crimson Water   Strider
87792 | Reins   of the Orange Water Strider
87793 | Reins of the Jade Water Strider
87794 | Reins   of the Golden Water Strider
89304 | Reins of the Thundering August   Cloud Serpent
91802 | Jade   Pandaren Kite String

> Kit, have fun <3

**Comment by wow-mania** [comment]
Set all of them to 1 copper please.

**Comment by Kitzunu** [comment]
Ay ay captain

**Comment by Kitzunu** [comment]
I will continue this work in the evening.

**Comment by Kitzunu** [comment]
Fixed
