### ISSUE TITLE
[Item] Shackled Ur'zul

### ISSUE THREAD

**Issue by Kitzunu** [WoWManiaUK/Redemption#4139]
Renamed to match the color of the mount:

Shacled Ur'zul (Blue)
Shacled Ur'zul (Red)
Shacled Ur'zul (Green)
Shacled Ur'zul (Purple)

**Comment by Kitzunu** [comment]
@WhitephoenixTheBunny feel free to test

**Comment by Kitzunu** [comment]
Misspelled lol
Will correct it in the evening

**Comment by wow-mania** [comment]
No need to do this. The icon colour should indicate it. Like in retail.
Id anything it should be "Blue Shacled Ur'zul"

**Comment by Kitzunu** [comment]
@wow-mania icons were wrong but I got rushor to fix that, so hopefully you got the file.

**Comment by Kitzunu** [comment]
Edit: I looked into this, they are wrongly named

**Comment by Kitzunu** [comment]
I will update them to match retail

**Comment by Kitzunu** [comment]
Edit: Lol further looking it seems that anything but the Purple one has never been available in Retail.

I will fix it accordingly

**Comment by Kitzunu** [comment]
![image](https://user-images.githubusercontent.com/24550914/75092763-6c07a480-557b-11ea-9d45-9f5af94b63e5.png)
