### ISSUE TITLE
voting does not give reward

### ISSUE THREAD

**Issue by rodrigo1120** [WoWManiaUK/Redemption#4141]
**Links:**

**What is Happening:**
When I open a voting site, contribute by voting and return on the wow web page, after I refresh the page my vote point does not appear

**What Should happen:**
vote point should appear

**Comment by wow-mania** [comment]
Please read guides and forum posts on this matter.

**Comment by WhitephoenixTheBunny** [comment]
I suggest to use Firefox:

The forum post:

https://www.wow-mania.com/forum/viewtopic.php?f=13&t=11

> Keep in mind that the voting websites are the third party and not WoW-Mania related. We are not able to fix any kind of other issues according to the websites.
