### ISSUE TITLE
Gnomes missing animation cast

### ISSUE THREAD

**Issue by WhitephoenixTheBunny** [WoWManiaUK/Redemption#4142]
On gnomes, all casts miss the animation - glowing - on the left hand

![image](https://user-images.githubusercontent.com/31921098/75013355-008add80-547c-11ea-907b-aed964bba61d.png)

**Comment by Kitzunu** [comment]
How should it be?

**Comment by WhitephoenixTheBunny** [comment]
@Kitzunu both hand should have glowing...
I will try show with several races

**Comment by WhitephoenixTheBunny** [comment]
Test: 
Warlock casting shadow bolt, several races

![image](https://user-images.githubusercontent.com/31921098/75036053-d7cd0d00-54a8-11ea-9b8d-d75336642c22.png)

![image](https://user-images.githubusercontent.com/31921098/75035658-e830b800-54a7-11ea-871b-f1fa2df5e094.png)
![image](https://user-images.githubusercontent.com/31921098/75035784-32199e00-54a8-11ea-8988-4f183262895b.png)
![image](https://user-images.githubusercontent.com/31921098/75035886-73aa4900-54a8-11ea-8493-3836373a0718.png)

**Comment by wow-mania** [comment]
Yes, we will not change this for now.

**Comment by GMZinius** [comment]
Reopening this issue, Players would like this fixing please 😄

**Comment by fvicaria** [comment]
We have no plans to fix this for now. It would require client update and also a lot of research to find out why,
