### ISSUE TITLE
[NPC] Chambermaid Pillaclencher

### ISSUE THREAD

**Issue by epoptic** [WoWManiaUK/Redemption#4143]
**Links:**
https://www.wowhead.com/quest=28058/look-at-the-size-of-it
https://www.wow-mania.com/armory/?quest=7704

**What is Happening:**
the named mob "Chambermaid Pillaclencher" is not spawning

**What Should happen:**
during the quest ( https://www.wow-mania.com/armory/?quest=7702 ) to steal 20 pillows, the chambermaid should spawn, allowing you to kill her and get the giant pillow so you can hand that in and retrieve https://www.wow-mania.com/armory/?item=18951 Evonice's Landin' Pilla

**Comment by thos72** [comment]
I WAS THERE I SAW EVERYTHING!

Seriously though,
We wait several probably an hour or so did laps, deleted and re-looted pillows

**Comment by Kitzunu** [comment]
Confirmed.

The event is not scripted at all, not even on Trinitycore.

Last WIP from TC https://github.com/TrinityCore/TrinityCore/pull/22235 but never got finished.
There are NPCs and Videos of the events can be found so it can be scripted.

@Keader @Rushor Any of you that want to do some diggin'? :D

**Comment by Kitzunu** [comment]
This blocks out the ability to get the item https://www.wow-mania.com/armory/?item=18950 which then blocks being able to do the quest chain it begins.

**Comment by Rushor** [comment]
will add a script for it.

**Comment by Rushor** [comment]
http://cata.cavernoftime.com/quest=7702

**Comment by Rushor** [comment]
Okay event added https://i.imgur.com/pFICu2A.jpg

It works like that.

1.) Take the quest http://cata.cavernoftime.com/quest=7702
2.) Loot one of the "Dark Iron Pillow"
3.) A generator (not visisble will spawn) which handles the event (can only happen one time the a player in range looted a "Dark Iron Pillow"
4.) 60 seconds after event start a wave of "Dark Iron Worker" will spawn and run around
5.) 180 seconds after event start a wave of "Dark Iron Worker" will spawn and run around
6.) 300 seconds after event start Chambermaid Pillaclencher will spawn and will drop the gameobject on death which will give the startquestitem

PS: The event generator will spawn around: -6545.88f, -1345.29f, 208.89f

**Comment by epoptic** [comment]
i appreciate the hard  work on this, however, the quest https://www.wow-mania.com/armory/?quest=7702 has you loot 20 of the pillows. only 8 to 10 spawn at a given time.

i'm not too certain that the script takes that into consideration

**Comment by Rushor** [comment]
reduced spawntime seconds to 60 seconds for the objects, so it will be easier
