### ISSUE TITLE
Action House

### ISSUE THREAD

**Issue by WhitephoenixTheBunny** [WoWManiaUK/Redemption#4144]
Lichbloom can't be purchased on AH, on any of them - Horde, ally and neutral
![alliance](https://user-images.githubusercontent.com/31921098/75069483-2d290e80-54e9-11ea-9173-9e31d5bfbbba.png)
![horde](https://user-images.githubusercontent.com/31921098/75069484-2e5a3b80-54e9-11ea-9e6c-e5071d805ffa.png)

![image](https://user-images.githubusercontent.com/31921098/75069486-2ef2d200-54e9-11ea-8afc-c4ec884f258d.png)

**Comment by Kitzunu** [comment]
I can confirm :)

**Comment by Kitzunu** [comment]
![image](https://user-images.githubusercontent.com/24550914/75070061-c4df2a80-54f2-11ea-9784-a71981a4b01b.png)

This seems to be some weird bug with the "normal" interface because I can buy it with my AH Addon

**Comment by wow-mania** [comment]
THis  has nothing to do with the item.
I will sort it on the next update.
