### ISSUE TITLE
auction problem

### ISSUE THREAD

**Issue by hagigol** [WoWManiaUK/Redemption#4145]
I have a problem with the auction house. I put several titansteel bars for sale. I cannot withdraw the auction, the buttons are inactive. I tried to buy a different character, I can't. I logged out and again the same. A colleague from lichbloom had a similar problem. Inactive house buttons in auction. Thank you in advance for your help Haggi id 2036119

**Comment by Kitzunu** [comment]
https://github.com/WoWManiaUK/Redemption/issues/4144 same as this
