### ISSUE TITLE
Auctions

### ISSUE THREAD

**Issue by hagigol** [WoWManiaUK/Redemption#4146]
![SnipSnip_Capture_2020-02-22-1121AM_1](https://user-images.githubusercontent.com/61333828/75090687-afefaf00-5565-11ea-8a8b-a78645cffefd.Png)

auction house is not working properly. I put some titanium bars for sale on ah and i can't cancel the auction. Can buy some stuff but some is like inactve. I tried to buy bars from my brothers account but the are like not active... I remove all addons and relog and nothing changes.

**Comment by Kitzunu** [comment]
Duplicate of #4144
