### ISSUE TITLE
[Group] Implemented automatic pass

### ISSUE THREAD

**Issue by Keader** [WoWManiaUK/Redemption#4149]
When the party/raid loot settings are set to "group loot" and a dropped item cannot be looted by some players (because it's an unique item and they can't store any more of those, or because it's a soulbound recipe they already learned/they lack the profession and skill for), they should receive a "You automatically passed on: [item] because you cannot loot that item." chat message and automatically pass the loot.

Also don't start the loot if all the players automatically passed because of unlootable item or because of autopass setting being turned on, prevents loot rolls being stuck until timeout.

**Comment by Kitzunu** [comment]
![image](https://user-images.githubusercontent.com/24550914/75093034-76776d80-557e-11ea-8b0c-a4aa3402beb3.png)
![image](https://user-images.githubusercontent.com/24550914/75093035-7d05e500-557e-11ea-8824-27b53b420e36.png)

Works <3
