### ISSUE TITLE
[Quest] Jungle Secrets - 215

### ISSUE THREAD

**Issue by jarvik76** [WoWManiaUK/Redemption#4156]
**Links:**
https://www.wow-mania.com/armory/?quest=215
https://www.wow-mania.com/armory/?npc=469

**What is Happening:**
Once completed, supposed to be handed in at Lieutenant Doren (ID 469), however he is not accepting the quest turn in - there is no "?" mark and is non-interactive.
See https://youtu.be/RJ7-IL7_8cM on PTR

**What Should happen:**
Doren should be interactive.

**Comment by Kitzunu** [comment]
It is due because CONDITION_SOURCE_TYPE_QUEST_AVAILABLE that makes you not be able to take the quest from Private Thorsen if he is in Rebel Camp

**Comment by Kitzunu** [comment]
I will do this in another way

**Comment by jarvik76** [comment]
Taking the quest FROM Thorsen is not the issue - it's handing into Doren once done.  Unless I misunderstood the linkage, of course...

**Comment by Kitzunu** [comment]
yes but same cause :)

**Comment by jarvik76** [comment]
ok, good :)

**Comment by Kitzunu** [comment]
I have no idea how to fix...

Anything I do won't work.

**Comment by Rushor** [comment]
this works for me on ptr? https://i.imgur.com/xR0A1Yv.jpg

**Comment by jarvik76** [comment]
Thanks, working now.
