### ISSUE TITLE
quest uncompleteable - Krolmir, Hammer of Storms

### ISSUE THREAD

**Issue by Probzta5311** [WoWManiaUK/Redemption#4159]
**Links:**

**What is Happening:**
Completed the quest but am unable to hand it in to Thorim at Temple of Storms. 
GM Brontus tried to resolve and advised to report here
![WoWScrnShot_022320_161457](https://user-images.githubusercontent.com/61386022/75115577-b1999f80-5657-11ea-84db-ef3cd75d22a4.jpg)

**What Should happen:**
Quest should be able to be handed in

**Comment by wow-mania** [comment]
Pretty sure this works.

**Comment by Rushor** [comment]
yes works, you need reputation to be able to speak with him to get the next quest

https://i.imgur.com/dhWtMI4.jpg

You need minimum http://wotlk.cavernoftime.com/faction=1119 3000 repuaution with them

**Comment by Probzta5311** [comment]
rep is honoured - only needs friendly , when gm checked it wasn't working for him either

**Comment by Rushor** [comment]
which quest you have done before that?

**Comment by Probzta5311** [comment]
im at the final stage of the quest line

**Comment by Probzta5311** [comment]
![WoWScrnShot_022320_165820](https://user-images.githubusercontent.com/61386022/75116198-afd2da80-565d-11ea-8850-e148a62b402b.jpg)

**Comment by Rushor** [comment]
ah nonononono, you need to reward the quest at the questender npc of the event here https://i.imgur.com/xaVXbgG.jpg

retake the quest and do the event again :)

**Comment by jarvik76** [comment]
i don't understand, the quest ender is not Thorim, it's Jpkkur in Duin Niffelem, right?   Am i missing something?

**Comment by Rushor** [comment]
http://wotlk.cavernoftime.com/quest=13010
http://wotlk.cavernoftime.com/npc=30390 - this not http://wotlk.cavernoftime.com/npc=29445

**Comment by Probzta5311** [comment]
during the event no one appears and nothing spawns - retook twice , I will retake and try again quickly

**Comment by Rushor** [comment]
do you talked to this guy to start the event https://i.imgur.com/Q4CAJfe.jpg ?

**Comment by Probzta5311** [comment]
sorted now - previous attempts thorim wasn't there , this time before the event had started he was kneeling there - Thankyou :)
