### ISSUE TITLE
[Core/Boss] Dragon bosses parry angle

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#4160]
**Links:** Related: #4065 

**What is Happening:** Dragon bosses like Halion and Sindragosa are able to parry from all around them (whole 360 degrees). Fix for issue #4065 worked perfectly fine for all other mobs, making them able to parry only in the frontal 180 degrees, but for some reason dragons can all around.

**What Should happen:** Dragons should behave like any other enemy, only being able to parry from the frontal 180 degree arc. Their tail swipe from behind makes it harder on dragons to dps from the sweet spot, but one should still exist. (Picture below as example)

> This is not to be confused with the old "behind the boss" which was 90 degrees of dragon ass, where you would often get tailswiped to death. In this time people talked about flanks, consisting of two 45 degree sweetspots, that counted as the unparryable zone but was still not the tailswipe zone. - Message from WoD commenting about the 'old' behavior being pre-wod.

![Dragon](https://user-images.githubusercontent.com/34783736/75121592-7735ff80-5663-11ea-8280-78d6cd4517b0.png)

**Comment by Keader** [comment]
I cant reproduce.
I put a little comment in GM chat, check this:

https://youtu.be/MTh4rhCutlw

Remember: Creatures cant parry attacks from behind.

**Comment by Kitzunu** [comment]
Wow keader, even music on the vid :P

Production value 100 xddd
