### ISSUE TITLE
[Boss/Spell] Sartharion (Flame Breath)

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#4161]
**Links:** https://www.wow-mania.com/armory/?npc=28860#drops
https://www.wowhead.com/spell=56908/flame-breath

**What is Happening:** [Sartharion's](https://www.wow-mania.com/armory/?npc=28860#drops) [Flame Breath](https://www.wowhead.com/spell=56908/flame-breath) is interruptible.

**What Should happen:** It should be impossible to interrupt his breath, just like Sindragosa's or Halion's.

**Comment by Rushor** [comment]
can fix that aswell if you wish. i guess the whole creature whould not be interuptable
