### ISSUE TITLE
Professor Putricide Choking Gas Explosion

### ISSUE THREAD

**Issue by shadownib** [WoWManiaUK/Redemption#4162]
**Links:** https://www.wowhead.com/spell=71279/choking-gas-explosion  and evidence what is suppose to happen if players are staying closer to the chocking gas : https://youtu.be/tPbRafn3Tuo?t=308

**What is Happening:**ATM Players didn't get any knocking back from the gas explosion

**What Should happen:**The players who stand closer than 10 yards to the choking gas must be pushed back like the feral cat in this current time from this video : https://youtu.be/tPbRafn3Tuo?t=308

**Comment by Oganku** [comment]
Choking gas bombs do knock back players within 10 yards. I have seen multiple people getting blown back by them and I can confirm the range is quite big as sometimes I get hit by accident when out of the gas aoe. 

Already works fine.

**Comment by shadownib** [comment]
Oganku you are right , i just check now old stream 6 months ago , back then it works , maybe it somehow happened randomly to me yesterday. nvm i guess closing this " issue "
