### ISSUE TITLE
[Boss] Rotface random melee one-shots

### ISSUE THREAD

**Issue by Flux13** [WoWManiaUK/Redemption#4164]
http://www.wow-mania.com/armory?npc=36627
http://www.wow-mania.com/armory?spell=69508

**What is happening:** When Rotface finishes using his Slime Spray ability, he will sometimes one shot a random player within melee range of the boss, regardless of where they are on the threat list. This seems to be happening because he chooses that person to target for the Slime Spray direction, and then he sneaks in a melee attack on them before turning back to the tank. I've witnessed this on 25 heroic, unsure if it happens on other difficulties.

**What should happen:** Rotface should finish his Slime Spray and calmly turn back to the person with highest threat without backhanding the poor healer who was just minding his own business.

**Comment by Rushor** [comment]
the unit with SELECT_TARGET_MAXTHREAT

**Comment by Rushor** [comment]
no i did that first :D

**Comment by Rushor** [comment]
The unit with the maximum threat should now be selected at the end of the slime spray (rotface will no longer select a random unit, but instead the one with the highest Threat on Rorface)
