### ISSUE TITLE
[NPC] Dark Iron Agent

### ISSUE THREAD

**Issue by BKnight07** [WoWManiaUK/Redemption#4165]
**Links:**

**What is Happening:**
Hey guys, a couple of us grouped and went through the Gnomeregan instance.  When fighting the Dark Iron Agents, the would not drop any Dark Iron Land Mines.  In fact, they seemed to only drop them when out of combat (that is, they all had mines sitting at their feet as we approached them).  They never dropped them during combat.

**What Should happen:**
I would expect the Dark Iron Agents to set Dark Iron Land Mines during combat.

**Comment by BKnight07** [comment]
Hey Kitzunu, why was this closed?  Are you combining it with my other ticket?  Maybe they are related?

**Comment by Kitzunu** [comment]
@BKnight07 I have no idea why it got closed, but it is being looked into 👍

**Comment by Rushor** [comment]
will check

**Comment by Rushor** [comment]
they will now only summon the mines in combat now

**Comment by jarvik76** [comment]
https://www.wow-mania.com/armory/?npc=6212
Agents now only drop mines when in combat, and the mines despawn when NPC is killed.
