### ISSUE TITLE
[NPC] Walking Bomb

### ISSUE THREAD

**Issue by BKnight07** [WoWManiaUK/Redemption#4166]
**Links:**

**What is Happening:**
Hey guys, when fighting the final boss Mekgineer Thermaplugg, a pair of Walking Bombs appeared only once but never made a move toward us.  They just stayed there the whole time.

**What Should happen:**
I would expect the Walking Bombs to "walk" toward us wrecking all sorts of havoc.  I would also expect more than one wave (admittedly, I'm going from memory from my time playing classic).

**Comment by Kitzunu** [comment]
Thank you for the time you spent to look into this bug!

We appreciate all contributions by players and will look into this issue as we get time for it!

**Comment by Rushor** [comment]
they will now attack the player on summon https://i.imgur.com/dMZXLiR.jpg

**Comment by jarvik76** [comment]
Can confirm that they do now move and attack the player on summon
