### ISSUE TITLE
[Boss] Lich King random melee one-shots

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#4168]
**Links:** Related: #4164
https://www.wowhead.com/spell=72133/pain-and-suffering
https://www.wowhead.com/spell=72262/quake

**What is Happening:** Same issue as Rotface in #4164 can happen with Lich King at the end of transition. During both transitions, the Lich King casts [Pain and Suffering](https://www.wowhead.com/spell=72133/pain-and-suffering) at random targets and when the transition ends, if said target is unlucky enough to be within melee range of the boss when his [Quake](https://www.wowhead.com/spell=72262/quake) ends, he will be able to sneak in a melee hit on a dps and very likely one-shot him.

**What Should happen:** Lich King should automatically default back to his highest threat target upon transition end.

**Comment by Rushor** [comment]
shoudl now select top aggro target
