### ISSUE TITLE
[NPC] Anachronos

### ISSUE THREAD

**Issue by Kitzunu** [WoWManiaUK/Redemption#4169]
**What Should happen:**
Should despawn on 20% and say a line

Proof:
https://wow.gamepedia.com/index.php?title=Anachronos&oldid=2155845

How to reproduce:
1. .go c id 15192
2. Kill to 20%

![image](https://user-images.githubusercontent.com/24550914/75191237-3cf75b80-5752-11ea-9f0f-e4e0a7f243d9.png)

First SAI script I ever managed to somewhat control x) #Proud

**Comment by Rushor** [comment]
Nice man!

**Comment by jarvik76** [comment]
Nicely done @Kitzunu it works fine :)
https://youtu.be/GjMRyADKQsQ
