### ISSUE TITLE
Bug Interface + No 5th Anniversary Wow-Mania Mount + Addon Instalation (3.3.5a)

### ISSUE THREAD

**Issue by Arkhon853** [WoWManiaUK/Redemption#4170]
Good day,

I am contacting you as I have several questions regarding my WoW-Mania account (Version 3.3.5a - WotlK, Redemption Server).
First of all, want to say that you guys are doing an amazing job on a daily basis and saved a lot of my evening thanks to you.
Nevertheless, I have some issue regarding : 

1) The Interface : It seems like some icon do not upload properly. A lot of them actually show a "Red Question Mark", as you can see in the below picture. It is happening for many of items. How to solve that?

![20200225_142042](https://user-images.githubusercontent.com/61424760/75251697-6f00d000-57db-11ea-812f-c2e9fc67d559.jpg)

Sorry the picture seems upside down without possibility of putting it back to normal.

2) I have received as many of us a new mount for the 5th Anniversary of Wow mania. But the mount just disapeared (also with the same icon problem from the point 1 above).

3) I have been problem to add some cool addon in my game. It seems like all the addon downloaded (where it says it is compatible for a 3.3.5a version which I am playing right now) do not work or like only 1 or 2 only.

Not sure what happen but if you need any information please let me know :)

My Account name in Wow-Mania = Arkhon853

Cheers,

**Comment by Arkhon853** [comment]
UPDATE : 

So I have just lost 200 MP (In the Mania Mall) for no reason, it gave me a random mount which I never asked for. This mount just disappeared too. I have no idea what is going on. Please, could you help on that?

**Comment by wow-mania** [comment]
That was one day only and you obviously don't have our client or it is not up to date.
