### ISSUE TITLE
[Quest] The Admiral Revealed

### ISSUE THREAD

**Issue by RyogoKusama** [WoWManiaUK/Redemption#4171]
**Links:**
https://www.wow-mania.com/armory/?quest=12852

**What is Happening:**

You need to kill Grand Admiral Westwind ( https://www.wow-mania.com/armory/?npc=29621 ) which is a pretty generic warrior-like NPC (he uses heroic strike/whirlwind).
Once he reaches a certain % of HP, he casts a shield on himself that makes him immune to everything, and the whole gimmick here is to use the provided quest-item ( https://www.wow-mania.com/armory/?item=40917 ) to make him vulnerable again and deal the final blow.

The issue is, as you can see from this link ( https://www.wow-mania.com/armory/?npc=29621 ) his damage output is bugged, he deals Melee: 16.820 - 23.401 instead of 10 times less like retail... we had to contact a GM in order to finish the quest.

**What Should happen:**

According to retail source he should deal 1.5k-2k damage on auto, which is close to being 10 times less than current value, so I'm guessing somehow the damage went up x10 ?

**Comment by Kitzunu** [comment]
Could you please provide any sources?
I have made a quick search but could not find any concrete information on the actual values

**Comment by Kitzunu** [comment]
Actually, I found a TC rework.

The whole quest has been improved and the DMG of the NPC will be less now.

**Comment by Kitzunu** [comment]
He's flagged as a World Boss, deals insane damage and moves too fast. He should be a normal level 80 boss, soloable by most classes.
Fix position, orientation and movement type, he shouldn't wander around.
Fixed various timing and cosmetic issues.
Add missing creature texts.
Add conditions for the quest item usage.

**Comment by RyogoKusama** [comment]
> Could you please provide any sources?
> I have made a quick search but could not find any concrete information on the actual values

I didn't know if I could provide official WoWHead links, since some things are slightly different here, this was what I found before opening a GM ticket and asking for assistance ( https://www.wowhead.com/npc=29621/grand-admiral-westwind#comments ) according to these comments on patch 3.0.3+ this NPC is way weaker than what we got now!

**Comment by volkangul** [comment]
I can give a hint about this. His Cleave ability normally can hit up to 3 persons and indeed that cleave hitted my 6.6k GS Rogue as 20k (i got 10k armor %39 reduction). So my advice to check this ability damage. His normal hits are standart.
