### ISSUE TITLE
[NPC] Silvermane Stalker - 2926

### ISSUE THREAD

**Issue by jarvik76** [WoWManiaUK/Redemption#4173]
**Links:**
https://www.wow-mania.com/armory/?npc=2926

**What is Happening:**
Silvermane Stalkers in the Hinterlands do not have an enemy unit nameplate on targeting.
![WoWScrnShot_022720_204249](https://user-images.githubusercontent.com/46089380/75485221-365f2300-59a2-11ea-89a8-995d13d9e023.jpg)

**What Should happen:**
Nameplate should be generated, e.g. 
![WoWScrnShot_022720_204233](https://user-images.githubusercontent.com/46089380/75485212-33fcc900-59a2-11ea-9699-c26ca8aeed0d.jpg)

**Comment by Kitzunu** [comment]
Press "V"

You can hide them or make them appear always or only in combat

**Comment by Kitzunu** [comment]
nvm you are on the same char x) My bad

**Comment by jarvik76** [comment]
Yep I think you got my meaning - this mob has no nameplate regardless of the menu setting or hotkey used.

**Comment by Rushor** [comment]
Will fix it.

**Comment by Rushor** [comment]
nameplates enabled now - pls test once the server is restarted (restart not available right now)

**Comment by jarvik76** [comment]
Fix confirmed
![image](https://user-images.githubusercontent.com/46089380/75616086-6c3c0d00-5b44-11ea-9e77-531ccb08f87d.png)
