### ISSUE TITLE
[Talent] Mage's Burning Soul is broken

### ISSUE THREAD

**Issue by slaniaxx** [WoWManiaUK/Redemption#4174]
**Links:**https://db.rising-gods.de/?spell=11083&locale=0

**What is Happening:**
Talent, when taken does not reduce threat by mage spells. (Tested on dummy)

**What Should happen:**
Talent, when taken, should reduce mage's threat

Note: Similarly; Warrior's "Intervene" ability is broken in the way that it does not reduce threat when cast as well.

**Comment by Keader** [comment]
The problem is: you tested in Dummy.
Dummys has a special script that add threat = damage caused, just to keep you in combat.
With any other npc, talent work fine.
