### ISSUE TITLE
[Quest] Gods Like Shiny Things

### ISSUE THREAD

**Issue by Kalasbyxan** [WoWManiaUK/Redemption#418]
In the quest (http://www.wow-mania.com/armory/?quest=12572) you walk around with Lafoo (http://www.wow-mania.com/armory/?npc=28120) who digs upp a variety of Shiny Treasures (http://www.wow-mania.com/armory/?item=38575) from glints on the ground (http://www.wow-mania.com/armory/?npc=28362) or from bugs (http://www.wow-mania.com/armory/?npc=28372). This quest (http://www.wow-mania.com/armory/?quest=12704) turns into a daily quest once it's done. The quest also opens up http://www.wow-mania.com/armory/?quest=12573 in the quest line.

Lafoo does not dig up treasures when walking on top or around them. I tried on over ten different glints. One time when moving towards a glinting bug Lafoo randomly says "Maybe more shiny bugs! We like bugs!" and I see a Glinting Armor (http://www.wow-mania.com/armory/?object=190560) on the ground. The player can not progress in the chain without this one done.

**Comment by Kalasbyxan** [comment]
The daily version of this quest (http://www.wow-mania.com/armory/?quest=12704) works fine.

**Comment by rafirstgod** [comment]
not fixed yet .... still lafoo doesn't dig for the trasure

**Comment by Kalasbyxan** [comment]
Out of 9 glints, 6 worked. It isn't 100% as it should be (treasure or other action included) it is doable.

**Comment by Echinaceax** [comment]
Apparently player in WC says - not a happy player in WC atm 
Lets take a look at it @Rushor

**Comment by Lumber-Jack-2** [comment]
yeah i remember the script partly, will check whats wrong - could be related to the trigger objects

**Comment by Echinaceax** [comment]
Only thing i did notice is he can be a little slow to react to the "shiney thing" sometimes

https://i.gyazo.com/24387fbf7c220d4ced0e24f95420f1a9.mp4
