### ISSUE TITLE
[Item/Loot] Ulduar hard mode wrong items

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#4184]
https://www.wowhead.com/npc=32867/steelbreaker
https://www.wowhead.com/npc=33350/mimiron

**What is Happening:**
1-1 misplaced items in the 10man hard mode loot table of Assembly of Iron and Mimiron were found.
Killing steelbreaker last (assembly hard mode) can award an item=25455 grey item in place of the guaranteed hard mode (lvl226) loot.
![WoWScrnShot_030220_164207](https://user-images.githubusercontent.com/31132743/75692031-3b271e00-5ca5-11ea-9d2b-1e779c283ea7.jpg)

Doing Mimiron 10 man hard mode can award a Fragment of Valanyr.
![WoWScrnShot_030120_230552](https://user-images.githubusercontent.com/31132743/75692276-96591080-5ca5-11ea-8839-e69394e2aa46.jpg)

**What Should happen:**
Assembly of Iron 10hard mode should never award a grey item in place of the hard mode loot.
Mimiron 10 hard mode should never award a Fragment of Valanyr, only 25 hard-mode.

**Comment by Rushor** [comment]
Will check

**Comment by Rushor** [comment]
misplaced items removed

**Comment by bluemonstrr** [comment]
Appears to now drop the 226 ilvl loot each time without dropping item=25455.
