### ISSUE TITLE
[Glyph] Druids Cosmetic Glyphs

### ISSUE THREAD

**Issue by WhitephoenixTheBunny** [WoWManiaUK/Redemption#4185]
The Glyphs (cat / bear / tree) are now soulbounded, but don't have that information on the description.
They should have the BOP information.

Items:
150508
150507
150504
150509
150505
150503
150500
150506
68039

![image](https://user-images.githubusercontent.com/31921098/75693649-2a73a980-5c9f-11ea-923d-f31e46fd5bef.png)

**Comment by Kitzunu** [comment]
I dont think that is possible...

only if I do "Use: Changes the appearance of your Tree form. (Souldbound)"

**Comment by Kitzunu** [comment]
but i will check tomorrow

**Comment by Kitzunu** [comment]
I think I maybe found a way

**Comment by Keader** [comment]
why they are SB anyway? is a glyph.
@Kitzunu change in item_template to not be soulbound o.o

**Comment by Kitzunu** [comment]
This is wrong.

they are not soulbounded, in DB they have bonding = 0 (No Bonds)
