### ISSUE TITLE
[Quest] The Aspirant's Challenge - Alliance version

### ISSUE THREAD

**Issue by WhitephoenixTheBunny** [WoWManiaUK/Redemption#4186]
The quest [The Aspirant's Challenge](https://www.wow-mania.com/armory/?quest=13679) requires "Equip your lance, then go to the stables outside the pavilion and mount up on the stabled Quel'dorei steed.", **but** the quest can be done without using the Quel'dorei steed & lance, as we can see on the below screenshots

![image](https://user-images.githubusercontent.com/31921098/75699678-c229c580-5ca8-11ea-8a27-fa41e08a7e2d.png)

![image](https://user-images.githubusercontent.com/31921098/75700275-b7236500-5ca9-11ea-8117-1ab5dd232add.png)

![image](https://user-images.githubusercontent.com/31921098/75700310-c5718100-5ca9-11ea-962a-897262b041f9.png)

Squire David only should give the option to start if we meet the requirements.
The horde version works as it should.

**Comment by Rushor** [comment]
Will check once i'm back on thursday

**Comment by Rushor** [comment]
The gossip to show the fight will now only be showns if player has the quests http://cata.cavernoftime.com/?search=The+Aspirant%27s+Challenge AND has the vehicle mounted:

NPC_SUNREAVER_HAWKSTRIDER        = 33844, //mount A
    NPC_QUEL_DOREI_STEED             = 33845, //mount H
