### ISSUE TITLE
Guild Announcement

### ISSUE THREAD

**Issue by Darkwolf-web** [WoWManiaUK/Redemption#4187]
**Links:**
N/A 

**What is Happening:**
The feature of "Guild Announcement" in calendar might be bugged as it does not create any announcement. The appointed time passes and nothing happens

**What Should happen:**
I do not know how it works but if i were to guess, it should give the announcement for all the guild members as the name suggests.

Kindly look into it. Thanks :)

**Comment by Kitzunu** [comment]
I cannot find anything that would prove the theory that it should send some kind of announcement in chat or notification on the screen.

If you manage to find something that can prove how it should work, please comment and I will reopen the issue.

Thank you for the time you took into creating this report :)
