### ISSUE TITLE
Spirit healer in coldarra, stuck in the ground

### ISSUE THREAD

**Issue by cooperonie** [WoWManiaUK/Redemption#4188]
**Links:**
![image](https://user-images.githubusercontent.com/2728624/75767060-7166ab00-5d42-11ea-8d37-8b3810f1b4d1.png)

**What is Happening:**
When you wipe in Eye of Eternity, you go to the spirit healer from the screenshot.
You are then unable to move( and jump)..
/reload doesn't fix this, logging out and back in does fix this.
I added the coordinates in the screenshot.

Note: i was multiboxing a 10man group it does have an element of randomness to it, not 100% of characters got stuck every time.
Note2: i had this happen several times over so it should be possible to replicate the issue

**Comment by cooperonie** [comment]
I found this same issue posted previously: https://github.com/WoWManiaUK/Redemption/issues/2636

So a bit more data: it doesn't seem to be related to race or class, the characters that are excluded from being stuck is random, each time different characters are escaping the bug.

**Comment by Rushor** [comment]
Maybe dbc xyz change can fix it

**Comment by Keader** [comment]
Fixed with a workaround.
I cant find the reason of this bug happens.
But now, when player get "stuck", he will be revived in spirit position
