### ISSUE TITLE
Can't talk to npc 'Kregga' to complete the quest 'Opportunity'

### ISSUE THREAD

**Issue by Sophraves** [WoWManiaUK/Redemption#4189]
The npc is there (under Icecrown citadel 55.74 ; 84.97), but not responsive so i can't complete the quest.
Using the launcher and patch 2.2.5.
I have 9 toons in raid and 1 seperate, but it 's the same for all.
I deleted my cache, but that did nothing for this issue.

**Comment by Rushor** [comment]
Can you leave all Party and maybe retake the quest and See what happens?

**Comment by Kitzunu** [comment]
I cannot see why this should not work.

Try rushors suggestion and if it doesn't work comment here and we can reopen.
