### ISSUE TITLE
[Quest] Alchemy quests display

### ISSUE THREAD

**Issue by skeeve159** [WoWManiaUK/Redemption#4190]
**Links:**

**What is Happening:** i finish Elixir mastery quest and when i return to the Honor Hold alchemy quest giver offers me rest two quests Potions and Transmutation mastery

![Snímek obrazovky (8)](https://user-images.githubusercontent.com/61806883/75927048-e681cf80-5e6b-11ea-9979-3456509ec8f9.png)

im will not finish them still when i try to take one of them it will give it to me. i talk about thys whyt Psygoa GM to be sure someone will knew about thys in instant

**What Should happen:**

**Comment by Kitzunu** [comment]
I will fix tomorrow when dev is back :)

Thank you for your reporot :)

**Comment by Kitzunu** [comment]
I think this maybe is fixed could you test @WhitephoenixTheBunny or @jarvik76 when dev has restarted later today? (I cant restart atm)

**Comment by Rushor** [comment]
conditions for display quests adjusted.

**Comment by skeeve159** [comment]
Hi again i ubdated client to 2.6.0 version still those quest are avilable to me so nothing changes even after ubdate. Again i checked it whit Psygoa GM just to be sure.
![Snímek obrazovky (11)](https://user-images.githubusercontent.com/61806883/76897447-0e255e80-6894-11ea-9382-cea3a40eb4c5.png) 

PS: first name of thys chara was Allheilsatan just for sure. Sorry for problems

**Comment by jeyrella** [comment]
Re-opening for re-testing

**Comment by Rushor** [comment]
which quest do you have completed already - can you gimme the id @skeeve159

**Comment by skeeve159** [comment]
hi i have elixir mastery for chance to create more flasks

**Comment by Rushor** [comment]
this seems to be an individual char issue - tester could not replicate the issue sadly 

https://media.discordapp.net/attachments/444436687397978112/689886694715162667/unknown.png

**Comment by skeeve159** [comment]
so its about me to not pick them. or maybe if i unlearn alchemy and learn it again it will repair itself maybe. but im not sure if i wana go again all the way and that quest doing again. so im not sure what lasts maybe only trust i did not pick them up

**Comment by Aristo14** [comment]
double check on this one, im confused if its fixed or ?

**Comment by skeeve159** [comment]
sry that dude still offers them to me 
![Snímek obrazovky (12)](https://user-images.githubusercontent.com/61806883/77507203-3d296a80-6e68-11ea-9eb8-8e69140e0b23.png)

**Comment by Rushor** [comment]
this is as-is sorry - we have not more time for that
