### ISSUE TITLE
[NPC/Ability] Ymirjar Deathbringer's Summon Undead

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#4191]
**Links:** https://www.wowhead.com/npc=36892/ymirjar-deathbringer#abilities
https://www.wowhead.com/spell=69516/summon-undead
 

**What is Happening:** The [Ymirjar Deathbringers ](https://www.wowhead.com/npc=36892/ymirjar-deathbringer#abilities) in the Frostwing Halls in ICC cast the spell [Summon Undead](https://www.wowhead.com/spell=69516/summon-undead), but nothing gets summoned upon completing the cast.

**What Should happen:** Summon Undead should probably summon an undead.

**Comment by Kitzunu** [comment]
Pit of Saron*

**Comment by Oganku** [comment]
I actually meant ICC, didn't realize there was a mob with the same name in PoS. 

Correct link here: https://www.wowhead.com/npc=38125/ymirjar-deathbringer

**Comment by Kitzunu** [comment]
Ymirjar in ICC dont use that spell.
![image](https://user-images.githubusercontent.com/24550914/75967892-c9311d80-5ecc-11ea-8b11-642120b1d8ea.png)

**Comment by Rushor** [comment]
They summon it in a rp run Event in pos when you walk up to tyrannus
