### ISSUE TITLE
Random Dungeon Finder gets players saved in Heroic Dungeons.

### ISSUE THREAD

**Issue by emeraldastro** [WoWManiaUK/Redemption#4193]
**What is Happening:**
The Random Heroic Dungeon Finder tool is getting players saved in each heroic dungeon every time they kill a boss, meaning it functions just like any heroic dungeon you walk in.

**What Should happen:**
The Random Heroic Dungeon Finder tool should not get you saved in any case.

**Comment by Kitzunu** [comment]
It actually should save you to all and then unlock when you have done all during a day.

Unfortunatly it cannot be fixed until a big redo of the system is made by Trinitycore.

Sorry
