### ISSUE TITLE
[Battleground] Adding an option to add Deserteur Debuff if player denies Battleground proposal

### ISSUE THREAD

**Issue by Rushor** [WoWManiaUK/Redemption#4196]
Adding an option to add Deserteur Debuff if player denies Battleground proposal.

Will add a 6 minutes deserteur debuff if the player denies the battleground proposal.

**Comment by GMMetaxa** [comment]
When que-ing for two BG's and joining the first but denying the second, the buff will added, but will make you able to play that first BG, so the debuff has no use.
Assuming that the BG lasts longer than 6 minutes, "you won't feel a thing". 
Suggestion: Extend the 6 minutes to 15 minutes.

**Comment by WhitephoenixTheBunny** [comment]
Should be 
Fix - improvement needed

**Comment by wow-mania** [comment]
That is how it will be.

**Comment by Rushor** [comment]
increase to 15 minutes in the config then :)
