### ISSUE TITLE
[Wintergrasp] PvP Flags for Horde Warsong Champions 

### ISSUE THREAD

**Issue by Blackhelm36** [WoWManiaUK/Redemption#4197]
**Links:**https://youtu.be/8mzlj2ZZzTA  Alliance,
https://youtu.be/VVzrNzH70lk  Horde

**What is Happening:**There is a discrepancy in Wintergrasp for time in combat after killing an opponent. I play both factions and my Alliance characters are immediately out of combat upon target death, while on Horde characters there is a 2-5 second delay.

**What Should happen:**in combat delay should be the same for both factions.

**Comment by Rushor** [comment]
check it but it is not related to flags in the creature_template :o

**Comment by Blackhelm36** [comment]
the same delay is there when fighting other players on Horde characters and lack of delay on Alliance characters

**Comment by Oganku** [comment]
I've had this long delay while playing my alliance holy paladin. I suspect buffing and healing allies is keeping me in combat longer than when I'm playing my warrior and not doing either of the above. Does not seem faction related.

**Comment by Rushor** [comment]
when testing, it was actually faction related for me

**Comment by Blackhelm36** [comment]
Oganku, check out the 2 videos I posted at the top, both single target attacks with a shadow priest of each faction. I get the same delay with all of my Horde toons and no delay on the Alliance toons
Alli toons--Pally-S Priest-Warrior-Warlock-DK-Mage
Horde toons-Pally-S Priest-Rogue-Warlock-DK-Druid-Mage
all 80s and I play in WG battles every chance I get, so I see both sides often

**Comment by sirikfoll** [comment]
@Keader

**Comment by Keader** [comment]
Bitch

**Comment by Rushor** [comment]
can you both gimme some hints where you fixed it? :D

**Comment by bluemonstrr** [comment]
Tested on both Alliance and Horde. Works great now! 👍
