### ISSUE TITLE
[NPC] Vagrant speech text incorrect

### ISSUE THREAD

**Issue by jarvik76** [WoWManiaUK/Redemption#4199]
**Links:**
https://www.wow-mania.com/armory/?npc=19283

**What is Happening:**
There is an error in the speech text gender variable of the Vagrants in Shattrath.
![image](https://user-images.githubusercontent.com/46089380/76160819-46ef6600-6125-11ea-9cf1-28a9af617dc3.png)

**What Should happen:**
Text should contain "sir" or "madam", appropriate to character's gender.

**Comment by Rushor** [comment]
texttarteting fixed as soon as dev is restarted :)

**Comment by jarvik76** [comment]
confirmed fixed 
![image](https://user-images.githubusercontent.com/46089380/76251118-6f1eb800-623e-11ea-96b6-08d57eb21ca4.png)
