### ISSUE TITLE
[Spells/Enchants/DK] Allow melee enchants proc in spells with attribute SPELL_ATTR1_UNK27

### ISSUE THREAD

**Issue by Keader** [WoWManiaUK/Redemption#4203]
"rune of the fallen crusader" (buff is called unholy strength) and "cinderglacier" (buff is called cinderglacier) should have chances to proc off the ability "chains of ice".

https://www.youtube.com/watch?v=teIODQeVjOI&t=
7:20
8:35
9:29

This fix make melee enchants proc with any spell with attribute SPELL_ATTR1_UNK27.

**Comment by svijetlo** [comment]
i em not sure this is working, i spent over 1h today on test realm doing Chains of Ice and Death Coil on mobs in Northtrend  and test dummy and it did not proc ones while in melee attack it still does as intended , here is img of it procking with melee after 5 hits
![WoWScrnShot_030820_183029](https://user-images.githubusercontent.com/61908373/76172116-c10a0400-6192-11ea-8424-d5ce51aa8530.jpg)

**Comment by svijetlo** [comment]
i em not sure this is working, i spent over 1h today on test realm doing Chains of Ice and Death Coil on mobs in Northtrend and test dummy and it did not proc ones while in melee attack it still does as intended

**Comment by Keader** [comment]
Fixed.
Was a core issue, fixed too Xd

**Comment by bluemonstrr** [comment]
Perfection 👍  :)
