### ISSUE TITLE
[Ulduar/Algalon] Fixed a issue when players get summon in algalon platform

### ISSUE THREAD

**Issue by Keader** [WoWManiaUK/Redemption#4205]
Sometimes summoned players will fall of algalon platform, caused by Z difference.
It only happens if you summon someone inside of algalon plataform/room.
Outside of glowing ground, everything will work fine.
I added 5 yards in Z position, to make players not fall.

**Comment by bluemonstrr** [comment]
Summoned about 50 times. Appears to be working well now.
