### ISSUE TITLE
[NPC] Ulduar Flame Leviathan Systems Shutdown

### ISSUE THREAD

**Issue by bluemonstrr** [WoWManiaUK/Redemption#4207]
**Links:**
https://www.wowhead.com/npc=33113/flame-leviathan
https://www.wowhead.com/spell=62475/systems-shutdown
https://www.wowhead.com/spell=62374/pursued

**What is Happening:**
During the Systems Shutdown Flame Leviathan will continue to follow it's pursued target as if it were not stunned. It does still take 50% increased damage.

**What Should happen:**
Systems Shutdown, as stated in the tooltip stuns the boss, rendering it completely immobile for the duration of the shutdown.

**Steps to reproduce:**
Doing the fight as intended without killing the boss before the Systems Shutdown.

**Comment by Rushor** [comment]
Will try a fix

**Comment by Rushor** [comment]
stutdown is after 150 sec.

he will stay in hs position now when the stun effect is active https://gyazo.com/09caaa92a3cb8b74086a2d5a313d39c0
