### ISSUE TITLE
Auction House does not sort correctly by bid across multiple pages

### ISSUE THREAD

**Issue by Boobarnes** [WoWManiaUK/Redemption#4208]
I am using the Wow-mania client and latest launcher.

The addons I use are Carbonite and Gearscore Lite.

**What is Happening:**
I noticed this on Horde's Auction House in Thunder Bluff and Org. It occurs on more than one item, but where I noticed it first was with Damaged Necklaces. They were selling from 150g to 200g. I posted some at around 120g hours ago, came back, and they weren't on the first page when sorting by lowest bid. Only by going to the 3rd of 3 pages did I find my and others' lower-priced items. 

**What Should happen:**
Well, I'd say lowest prices should appear on the first page when sorting by lowest price, not the last. The last page was a jumble of both high and low prices. Yes, I tried re-sorting the column to high and low--it didn't fix anything.

**Comment by svijetlo** [comment]
Happens only if there is bigger amount of item in AH. 
tho idk why 
My advice and easy solution is to use addon Auctioneer, it will be fast fix and make your life much easier with AH in all aspects.

**Comment by wow-mania** [comment]
This is a client issue. Cannot be fixed.
