### ISSUE TITLE
[NPC] Flame Leviathan Ulduar

### ISSUE THREAD

**Issue by bluemonstrr** [WoWManiaUK/Redemption#4209]
**Links:**
https://www.wowhead.com/spell=62375/gathering-speed
https://www.wowhead.com/npc=33113/flame-leviathan

**What is Happening:**
Flame Leviathan is stacking this buff approximately every 50 seconds or so, making it 3 stacks before shutdown happens and the stacks reset.

**What Should happen:**
The boss should stack this ability every 5 seconds, making it more and more difficult to kite as the fight goes on until the shutdown and then the stacks reset. Stacks should go up to 20, making it 100% faster.

**Comment by Rushor** [comment]
Gonna check

**Comment by Rushor** [comment]
should be every 5 sec now.
