### ISSUE TITLE
[Object] Alliance Version of Battered Hilt drops for Horde players

### ISSUE THREAD

**Issue by emeraldastro** [WoWManiaUK/Redemption#4211]
**Links:**
https://prnt.sc/rewyhl

**What is Happening:**
The Alliance version of Battered Hilt drops for Horde players in Forge of Souls, Pit of Saron and Halls of Reflection and everyone is unable to loot it.

**What Should happen:**
The Horde version of the same item should be the only one to drop instead of both versions.

**Comment by Rushor** [comment]
try now pls

**Comment by WhitephoenixTheBunny** [comment]
and the horde one drops on ally

**Comment by jarvik76** [comment]
Total 10 dropped during testing all for right faction.  1/1024 of this being incorrect if it is not fixed.  Statistically good enough for sign-off.  Thanks @Sharuzan as this took a while :)

**Comment by jeyrella** [comment]
Reopening for further attention; multiple reports on discord and in world chat this is still not working
![image](https://user-images.githubusercontent.com/46089380/77570470-c0c47500-6ec3-11ea-8748-abdbdea123e7.png)

**Comment by wow-mania** [comment]
need to confirm... I find difficult for things like this to regress

**Comment by Rushor** [comment]
loot reworked. for testing purpose dropchance set to 100 percent. on live it will be 0.08.

**Comment by Rushor** [comment]
fix was confirmed in dev test chat :)

**Comment by jeyrella** [comment]
have had a total of 60 drop now, all correct.
That would be a 1 in 1,152,921,504,606,846,976 chance of not having seen it occur by now :D

**Comment by Rushor** [comment]
hahahahaha

**Comment by GMMetaxa** [comment]
https://imgur.com/a/EqT8sSL  New ticket after applied fix. 31-03   22:08

**Comment by Rushor** [comment]
maybe something was missing to be applied? can someone recheck that on prt? i have added the fix there agan (with 100 percent drop chance for easier test)

**Comment by Sharuzan** [comment]
I went into FoS/PoS/HoR with no hilt dropping for the wrong faction.
30 hilts in FoS. 30 hilts in PoS and lastly 40 hilts in HoR. 
If this bug isn't fixed with the latest fix, then the odds of a hilt dropping for the wrong faction are astronomical.

**Comment by Rushor** [comment]
I guess it was not fully applied or sth. We will readd it!

**Comment by jeyrella** [comment]
Astronomical is the word.....
1 in 1,267,650,600,228,229,401,496,703,205,376

**Comment by gilmye** [comment]
> 
> 
> **Links:**
> https://prnt.sc/rewyhl
> 
> **What is Happening:**
> The Alliance version of Battered Hilt drops for Horde players in Forge of Souls, Pit of Saron and Halls of Reflection and everyone is unable to loot it.
> 
> **What Should happen:**
> The Horde version of the same item should be the only one to drop instead of both versions.

Monday May 4th Horde in FoS HC and hilt dropped and everyone auto passed. was a Ally hilt in a Horde made grp.

**Comment by jeyrella** [comment]
@gilmye any idea of group composition?  (race/classes)

**Comment by gilmye** [comment]
Troll hunter Druid Tauren x2. And I think was a pally tank and mage. Most likely blood elf’s

**Comment by GMMetaxa** [comment]
Still happening. Need a better fix :)

**Comment by wow-mania** [comment]
Not possible to regress. It was either never fixed correctly or not tested.

**Comment by jeyrella** [comment]
@GMMetaxa PLease see dev/team test channel, we have tested this exhaustively on ptr with good results.  As in, literally hundreds of correct drops.  Everything seems good on code according to @Rushor 

We don't know why there is specific problems on live.  We can only think there are very specific conditions which make this fail, it only seems to fail on Horde side

We will need really detailed info on group race/class compositions, the mob it dropped off, etc./  we simply have no way to test/replicate.

**Comment by Rushor** [comment]
yes the code is in dev ptr all fine. a reproduction would really help us

**Comment by Rushor** [comment]
also upgraded to 100 percent the drop (on PTR ONLY) get a way to reproduce it guys, or we must find a different solution

**Comment by Sharuzan** [comment]
I did some testing to include the new races and DK variants. 
During testing no wrong hilt dropped for either side. Aimed for 33 hilts per dungeon.

Horde 
Orc Warrior: FoS / PoS / HoR 33 hilts in each 
Bloodelf Paladin: FoS / PoS / HoR 33 hilts in each 
Goblin Warlock: FoS / PoS / HoR 33 hilts in each 
Goblin DK: FoS / PoS / HoR 33 hilts in each 
 
Alliance
Human Priest: FoS / PoS / HoR 33 hilts in each 
Worgen Warrior: FoS / PoS / HoR 33 hilts in each 
Worgen DK: FoS / PoS / HoR 33 hilts in each

**Comment by jeyrella** [comment]
Unless we get specific details on groups, race/class combos, the NPCs the hilt dropped off wrongly, we could spend all year testing only this issue and never find it.
We will need detailed info to even have a shot at reproducing this, I fear.

**Comment by Rushor** [comment]
any news?

**Comment by Aristo14** [comment]
Still lack specific details surrounding this bug.

**Comment by jeyrella** [comment]
Horde version dropped in Alliance run of PoS HC
Dropped from Wrathbone Coldwraith
https://wow-mania.com/armory/?npc=36842

![image](https://user-images.githubusercontent.com/46089380/82755798-e8559200-9dcd-11ea-97b3-85e0403a19e0.png)

Group:
NE feral druid tank
Human Holy Paladin
Human Retri Paladin
Dwarf Hunter
Human Rogue

**Comment by jeyrella** [comment]
Alliance Battered Hilt dropped for a horde group in PoS... 
Dropped from deathwhisperer Necrolyte
https://wow-mania.com/armory/?npc=36788

Blood Elf Shadow Priest
Tauren Druid
Blood Elf Mage
Goblin Shaman 
Blood Elf Paladin.

**Comment by jeyrella** [comment]
@Rushor 
See discussion/agreement with @GMMetaxa on test team channel.  
At this point, having spent dozens of hours testing with no discernible error pattern, the suggestion is to **remove the faction roll pass function for this item so that it can be looted by all,** to take it and sell/trade/mail to alt.

While not entirely blizzlike, this does solve the frustrations of the issue and the impact is still minimal.

**Comment by svijetlo** [comment]
yes i told this when problem 1st time appeared

**Comment by Rushor** [comment]
Okay will change that

**Comment by svijetlo** [comment]
i was blood elf ally one droped in POS i could loot it to my bag
