### ISSUE TITLE
[Object] Quest marker clips into scenery texture at Spinebreaker Post

### ISSUE THREAD

**Issue by yani** [WoWManiaUK/Redemption#4212]
At Spinebreaker Post (Hellfire Peninsula), a quest marker is hidden in the scenery.

You can see the bottom tip of it in this screenshot:
![image](https://user-images.githubusercontent.com/6956790/76476723-43006400-6403-11ea-84c8-cd7b16f4b3e5.png)

**Comment by jarvik76** [comment]
confirmed
![image](https://user-images.githubusercontent.com/46089380/76522819-272aab80-645f-11ea-9e32-4e6bd3cabdac.png)
Starts quest https://www.wow-mania.com/armory/?quest=10809

**Comment by Rushor** [comment]
try with next dev restart

**Comment by svijetlo** [comment]
![Untitled](https://user-images.githubusercontent.com/61908373/76533479-6dd8cf80-6478-11ea-9f35-4df085487ecf.jpg)
