### ISSUE TITLE
[NPC/Dungeon] Soulguard Adept (Forge of Souls)

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#4213]
**Links:** https://www.wowhead.com/npc=36620/soulguard-adept#abilities
https://www.wowhead.com/spell=69564/shadow-mend

**What is Happening:** The Soulguard Adept mobs currently never cast their healing ability 'Shadow Mend'. Other 3 work fine.

**What Should happen:** The Soulguard Adepts should sometimes try to heal their allies.

**Comment by Rushor** [comment]
should be able to heal/cast it now.
