### ISSUE TITLE
[Pet] Pet positioning incorrect 

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#4214]
**Links:** 

**What is Happening:** Pets do not automatically position themselves behind their targets, resulting in lots of their attacks being parried. This causes quite an issue since parry is now fixed.

**What Should happen:** Pets should automatically attack from behind so as to not be parried. (Was working fine before, but can't find the previous issue)

**Comment by svijetlo** [comment]
sadly could not reproduce it 
did FOS-POS-HOR-icc-RS and pet was behind target 90% of time
it did take time to adjust if i turn target around etc 
and it had like from 100 melee 1 parry

**Comment by wow-mania** [comment]
Thank you.
