### ISSUE TITLE
[Quest] Wrong instance on exiting Eye of Acherus during quest Death Comes From On High

### ISSUE THREAD

**Issue by yani** [WoWManiaUK/Redemption#4215]
**Links**
https://www.wow-mania.com/armory/?quest=12641

**What is Happening:**
When on the quest **Death Comes From On High**, which is the 3rd or 4th quest in the DK storyline, when using the Eye of Acherus Control Mechanism to spy, executing "Exit Vehicle" returns the user to a type of instanced world. 

**What Should happen:**
You should be in the normal world instance. The buff "The Eye of Acherus" should also be removed.

![image](https://user-images.githubusercontent.com/6956790/76514588-699cba00-6458-11ea-8922-50b888e817a6.png)

A quick fix is to logout and log back in. The buff will be gone and the user is back in the normal world instance.

**Comment by wow-mania** [comment]
Pretty sure this works. The player must have done something wrong or found a corner case.

**Comment by Rushor** [comment]
cannot confirm this aswell https://i.imgur.com/Y7qczul.jpg after cancel the buff get's removed

**Comment by svijetlo** [comment]
just did it works fine to me

**Comment by Rushor** [comment]
if a reproduction way or video is given we will inspect it again. closed till then

**Comment by yani** [comment]
I have done the quest now. If possible, feel free to undo it on my character "Fidz" and I will make a video.

**Comment by yani** [comment]
Did you guys try to exit the vehicle in the first few bits of being launched to the city? I haven't tried it after I got to the city that had to be scanned. I also tried it as soon as the screen changed. There's also 2 ways to exit the vehicle. One returns the orb home, and has an explanation, the other one is just "Exit Vehicle".

**Comment by Rushor** [comment]
can you show us a video?
