### ISSUE TITLE
[Pet] Pet positioning against large targets

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#4216]
**Links:**

**What is Happening:** Against enemies with large hitboxes such as dragons (Halion, Sindy, etc.) pets would attack in a straight line between the owner and the boss and will not actively look for their backs. Manually repositioning pets is quite troublesome and not doing so resulted in warlock/hunter pets dosing from the side of the dragon (almost perpendicular) where they would get parries. 

*I had not checked against smaller enemies before, but it definitely is an issue against large bosses.

**What Should happen:** Pets should automatically seek the back of large enemies so as to attack opposite of where they're facing. They used to do it before, where you would see a small cluster of pets at the tail, but they don't anymore.

Edit: It seems that as soon as the pet reaches the hitbox and is able to melee, it will stop looking for the back and just stick to that spot. It should usually prioritize moving behind over 'sticking' to the hitbox and attack there no matter of the angle.

**Comment by svijetlo** [comment]
been watching pets in raid last night , 
where i faild and where is problem if you are alone so boss trget player pet will go behind boss 
but in raid last night on sindragosa i seen hunter pet on opposite side of where player stands not behind boss, so i think pet is positions it self by where player /owner is not to seek back of boss

**Comment by Keader** [comment]
I tried 3 hours, but without success.
our core dont have support to proper fix it.
