### ISSUE TITLE
[Reputation] Scryers

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#4217]
**Links:** https://www.wowhead.com/item=25744/dampscale-basilisk-eye#objective-of
https://www.wowhead.com/npc=18596/arcanist-adyria
https://wow.gamepedia.com/Scryers
https://www.wowhead.com/quest=10412/firewing-signets

**What is Happening:** I was previously Exalted with the Aldor and recently handed in about 1300 [Dampscale Basilisk Eyes](https://www.wowhead.com/item=25744/dampscale-basilisk-eye#objective-of) to [Arcanist Adyria](https://www.wowhead.com/npc=18596/arcanist-adyria) to get back to unfriendly with them and Aldor. I then unlocked the quest [[City of Light] ](https://www.wowhead.com/quest=10211/city-of-light) once again and upon completion, I chose the Scryers, which put me at Neutral rep. 

So far so good. I then went to the Scryer's tier and took the quest [[Firewing Signets]](https://www.wowhead.com/quest=10412/firewing-signets) and went off to farm the ~120 needed to hit Honored and unlock the next quest. However, I logged out for a few minutes in this time and when I logged back on I was put back to 'At war' and am unable to un-check it. When I went to complete the quest, I was unable to interact with the quest giver even though he had the gold '?'. I tried abandoning the quest, but to no avail. I can't turn-in more eyes at Adyria either. So I'm just stuck.

**What Should happen:** You should never be put back to At war with the Scryers or Aldor after having selected one of them after completing [[City of Light] ](https://www.wowhead.com/quest=10211/city-of-light). Much less if you are unable to un-check it and aren't unfriendly/hated with them.

**Comment by Rushor** [comment]
you can test this with .mod rep 932/934 9999999 and .mod rep 932/934 -9999999

**Comment by Rushor** [comment]
Game/ReputationMgr: Fixed an issue where player are set to "At war" with Aldor or the Scryers Faction even if the reputation is highter than REP_UNFRIENDLY

* Also fixed an issue where the "At war" state was not correctly set upon relog for the Sholazar Factions

**Comment by jarvik76** [comment]
Confirmed fixed
Did repeatable quest on non-GM pc, monitored war status throughout turn ins.  At war was not flagged on reaching Neutral after turn in.
![image](https://user-images.githubusercontent.com/46089380/76649283-3b9e9f00-6558-11ea-9466-6403b578ded6.png)
Logged out and waited 15 mins.  Logged in, still correctly not "at war."

@Oganku However, quest City of Light was not unlocked.  According to gamepedia/fandom (and my memory, although that is bad!) this is not a quest that should unlock again (and it's not repeatable), so unsure how you managed this.  One simply takes the Scryer repeatable quest at neutral.   Was there something particular you did to manage this?
