### ISSUE TITLE
[Quest] On ruby wings 12498

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#4218]
**Links:** https://github.com/WoWManiaUK/Redemption/issues/1621
https://www.wowhead.com/quest=12498/on-ruby-wings
https://www.wowhead.com/npc=28006/grand-necrolord-antiok
https://www.wowhead.com/npc=28018/thiassi-the-lightning-bringer
https://www.wowhead.com/spell=50455/shadow-bolt
https://www.wowhead.com/spell=55984/shadow-bolt
https://www.wow-mania.com/armory/?npc=27996

**What is Happening:** Multiple issues here.

1. [Antiok](https://www.wowhead.com/npc=28006/grand-necrolord-antiok) can target the player even while they are riding the provided Drake vehicle from the quest. 

2. Once the [giant](https://www.wowhead.com/npc=28018/thiassi-the-lightning-bringer) is dead, the boss keeps his immunity shield for several seconds (as mentioned in #1621) and keeps casting his shadow bolts at the player. Those shadow bolts are meant to hit the Drake with much higher HP and will usually 1-2 shot the player. Not sure if he switches to his regular shadow bolts one his shield goes down, but most players don't live that far. (Both versions of the NPCs shadow bolts linked above).

**What Should happen:** Antiok should never target the player while he is mounted on the [Wyrmrest Vanquisher](https://www.wow-mania.com/armory/?npc=27996) vehicle and should switch to regular shadow bolts that don't one shot players when his giant is defeated. Also immunity shield should drop at the same time.

**Comment by svijetlo** [comment]
he was not targeting me while i was on drake , but ones drake went  down he did continue to do same dmg on me like he did on drake if i were not geared lvl 80 would easy kill me  , if need be can provide video

**Comment by Rushor** [comment]
will fix this tomorrow

**Comment by Rushor** [comment]
according to this https://www.youtube.com/watch?v=-BdkqD7O3Eo he should not cast any spells upon death of the vehicle, but instead kill hisself after some seconds

**Comment by Rushor** [comment]
okay he will now only cast ID - 55984 Shadow Bolt against player and ID - 50455 Shadow Bolt against the vehicle. you will also get dismounted from your vehicle once Thiassi the Lightning Bringer is killed.

**Comment by IvanLlanas** [comment]
Grand Necrolord Antiok is not with Thiassi anymore.
