### ISSUE TITLE
[Npc/Quest] Darkrider Arly questchain

### ISSUE THREAD

**Issue by UniversalSoldier1985** [WoWManiaUK/Redemption#4219]
**Links:**

**What is Happening:**
Darkrider Arly not giveing the proper quest chain and I cant turn in stuff. I received" Death's Gaze" and "Destroying the Altars" but that is not the propper starting quest. "A Visit to the Doctor" is. Also I can't turn in "Death's Gaze" but can turn in "Destroying the Altars". 

**What Should happen:**

**Comment by svijetlo** [comment]
quest chain actually start from https://www.wowhead.com/npc=29804/baron-sliver
quest A Visit to the Doctor is 5th in chain you get it after you are don with quest from npc standing next to Darkrider Arly , his quest start ones you get https://www.wowhead.com/quest=13136/jagged-shards quest item drooping from Spiked Ghoul
