### ISSUE TITLE
[NPC] Alliance Brigadier General missing in Dalaran

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#4220]
**Links:** https://wowwiki.fandom.com/wiki/Alliance_Brigadier_General

**What is Happening:** [Alliance Brigadier General](https://wowwiki.fandom.com/wiki/Alliance_Brigadier_General) NPC is missing in Dalaran's Alliance quarter (Silver Enclave). This NPC exists also in all the capitals and wintergrasp and is the end point of Call to arms battlegrounds quests. Hordes do have a Horde General properly working in Dalaran as well as the other locations.

**What Should happen:** There should be an Alliance Brigadier General in Dalaran as well.

**Comment by wow-mania** [comment]
What is the Location?
I cannot find any confirmation that there was an instance of this NPC in Dalaran only in Stormwind City, Ironforge, The Exodar, Shattrath City, Crystalsong Forest, Darnassus.

**Comment by Keader** [comment]
Fixed.

![image](https://user-images.githubusercontent.com/7120913/76684237-f2e2f680-65e8-11ea-8e43-0183646f9b58.png)
