### ISSUE TITLE
[Object] Pet moving through closed gates

### ISSUE THREAD

**Issue by bLeyaa** [WoWManiaUK/Redemption#4221]
What is happening: At the event before Sindragosa, you're able to send the pet through the gates to pull the trash (for example). 

What should happen: Pathing shouldn't allow pets to move through objects, such as wall or gate.

**Comment by Keader** [comment]
Fixed.
Pets should not be able to attack targets that is not in his vision.

**Comment by bLeyaa** [comment]
Hi, i noticed today that this is also possible in Utgarde Keep, at the beginning of the dungeon - through that fire wall. Not sure if this fix will include it as well, looks like a different type of object to me.
If you want i can make a new report for it.

**Comment by Keader** [comment]
will work to any objetct or struct that cause line of sight block

**Comment by bLeyaa** [comment]
@Keader @Rushor Done Utgarde Keep today after the update and i had the paladin tank taunt the adds behind the fire wall. Not sure if you want to re-open this issue or i can make a new one.

**Comment by Keader** [comment]
Paladin is not pet.
So is other issue

**Comment by bLeyaa** [comment]
@Keader @jeyrella 

Regression.

Had a warlock pet go through gates today, was Felhunter for what it matters.

**Comment by Keader** [comment]
fixed again

**Comment by svijetlo** [comment]
![WoWScrnShot_092720_155143](https://user-images.githubusercontent.com/61908373/94366580-8db0a780-00d9-11eb-960c-1db10122516f.jpg)
![WoWScrnShot_092720_155124](https://user-images.githubusercontent.com/61908373/94366583-90130180-00d9-11eb-8c63-7f3ca1f2361f.jpg)
![WoWScrnShot_092720_155129](https://user-images.githubusercontent.com/61908373/94366588-92755b80-00d9-11eb-887f-b3dd19f986c5.jpg)
![WoWScrnShot_092720_155140](https://user-images.githubusercontent.com/61908373/94366592-94d7b580-00d9-11eb-9fbb-534335f58e59.jpg)
![WoWScrnShot_092720_155141](https://user-images.githubusercontent.com/61908373/94366593-973a0f80-00d9-11eb-8d20-7d51cf0f596f.jpg)
as you can see on Ss my force of nature pet just went trou door like it  does not exist same was with lock and hunter pet ion lot of diferent spots

**Comment by Keader** [comment]
Because they're not pets, are guardians.
cant do a thing about it

**Comment by svijetlo** [comment]
![WoWScrnShot_092720_162318](https://user-images.githubusercontent.com/61908373/94367282-fef25980-00dd-11eb-83d1-a62110780a49.jpg)
![WoWScrnShot_092720_162321](https://user-images.githubusercontent.com/61908373/94367285-01ed4a00-00de-11eb-9db7-baceaaa4e1cd.jpg)
![WoWScrnShot_092720_162322](https://user-images.githubusercontent.com/61908373/94367286-044fa400-00de-11eb-8168-d3642a79cdb7.jpg)
![WoWScrnShot_092720_162324](https://user-images.githubusercontent.com/61908373/94367290-074a9480-00de-11eb-821d-20de7560776a.jpg)
![WoWScrnShot_092720_162331](https://user-images.githubusercontent.com/61908373/94367292-0a458500-00de-11eb-8033-7eccbfeaa0fd.jpg)
![WoWScrnShot_092720_162333](https://user-images.githubusercontent.com/61908373/94367296-0ca7df00-00de-11eb-83a1-c1a537e492cb.jpg)
there just don it on same spot with warlock felhunter you target mob behind doors use Attack of pet and he will go true and pull what ever you target on other side

**Comment by Keader** [comment]
ok, something's still wrong.
i'll take a look today

**Comment by svijetlo** [comment]
=) thx for understanding as wrote before i did it with lock pet but did not made ss

**Comment by wow-mania** [comment]
When this is closed it will not be re-opened.

**Comment by Keader** [comment]
fixed.

**Comment by svijetlo** [comment]
warlock pet, hunter pet and boomkin tree guardians can not pass doors if closed atm tested with all of them on this same spot and some other i could remember like in icc and dungs
