### ISSUE TITLE
[Mechanic] Sindragosa starting event missing

### ISSUE THREAD

**Issue by bLeyaa** [WoWManiaUK/Redemption#4222]
Links: https://www.youtube.com/watch?v=o89tT2o87r0

What is happening: Sindragosa is grounded already in the middle of the area, prior to anyone entering the zone.

What should happen: Sindragosa should be flying around in distance and only land down from air after player(s) move down into the zone (somewhere after the staircase).

**Comment by wow-mania** [comment]
We will not be changing this at this point. Maybe in future.
