### ISSUE TITLE
Can't reset password to account

### ISSUE THREAD

**Issue by AndreaDicka** [WoWManiaUK/Redemption#4223]
**Links:**
https://www.wow-mania.com/site/reset-password?token=hXWQhlrvtK6eHfqDYd-228pRWDUg0-Ev_1584133683

**What is Happening:**
I forgot my password to my account. I tried to refresh it via "forgot password". I got an email with a link to reset my password, but when I put my new password and confirmed it, I got an internal server error and in the end I could not reset my password. Can you please help? I don't want to loose all my characters.

**What Should happen:**
I should have my password changed :) Instead internal server error is happening.

**Comment by Aristo14** [comment]
please contact janitor with this issue, i'm sure it can be sorted out.
