### ISSUE TITLE
[NPC/Raid] Blistering Zombie - ICC - 37934

### ISSUE THREAD

**Issue by bLeyaa** [WoWManiaUK/Redemption#4225]
**Links:**
https://youtu.be/ORn6SC-X7Cg?t=89 (At 01:30 you can see what it looks like along with the damage taken and the debuff applied)
Zombie explodes in foreground

**What is Happening:** Blistering zombie has no animation upon dying, but just spreads the debuff to nearby targets.

**What Should happen:** Upon being killed, blistering zombies should explode and inflict damage to nearby targets leaving a debuff on them.

**Comment by jarvik76** [comment]
https://www.wow-mania.com/armory/?npc=37934

**Comment by jeyrella** [comment]
Yep, working

![image](https://user-images.githubusercontent.com/46089380/76783557-fd98b980-67a9-11ea-9cd2-933f74d88ae1.png)

**Comment by bLeyaa** [comment]
@Keader @Rushor 
This need a little tweak. The zombie starts casting the Acid Burst prior to reaching 1hp and oftenly does not cast it at all but just disappear. Or cast it but w/o exploding the aoe dmg & debuff to nearby enemies.

**Comment by Keader** [comment]
what?
It cast the spell always that damage > his hp.
