### ISSUE TITLE
[Cosmetic] Stinky green aura missing

### ISSUE THREAD

**Issue by bLeyaa** [WoWManiaUK/Redemption#4226]
**Links:** https://youtu.be/RdqPb2Fslg0?t=86 (01:26)

**What is Happening:** Stinky is missing the radiating glow aura around him

**What Should happen:** Should look like on the video provided above

**Comment by svijetlo** [comment]
he does make some of those green clouds but not as much as in video

**Comment by svijetlo** [comment]
![WoWScrnShot_031520_144350](https://user-images.githubusercontent.com/61908373/76702675-ea172100-66cb-11ea-853a-45f8b188880a.jpg)

**Comment by bLeyaa** [comment]
That screenshot shows the aoe damage that he does (on low graphs). It's a different thing.

**Comment by Rushor** [comment]
https://youtu.be/RwRD9mzQl2E?t=689 hmmm

**Comment by bLeyaa** [comment]
> https://youtu.be/RwRD9mzQl2E?t=689 hmmm

That's not wotlk, but he still has the green aura on him before dying nonetheless...

**Comment by Rushor** [comment]
yes i got it :)

**Comment by jeyrella** [comment]
Has a lovely green cloud around him now.  @svijetlo farted near him, I think.... :D
![image](https://user-images.githubusercontent.com/46089380/76782811-c1b12480-67a8-11ea-8306-545b456ae54d.png)

**Comment by bLeyaa** [comment]
Beautiful
