### ISSUE TITLE
Precious - Plagued Zombies spawn delay

### ISSUE THREAD

**Issue by bLeyaa** [WoWManiaUK/Redemption#4227]
**Links:** https://youtu.be/JRhMPYnTUBY?t=7m11s

**What is Happening:** Plagued Zombies are active as soon as they spawn

**What Should happen:** Plagued Zombies summoned by Precious should have a 3 second (or so) delay before becoming active.

P.S. Precious should also have a "Precious Ribbon" buff on him, same as for when we equip the shirt (cosmetic)

**Comment by jarvik76** [comment]
https://www.wow-mania.com/armory/?npc=38104
