### ISSUE TITLE
[Hunter] Melee skill increased with ranged attacks

### ISSUE THREAD

**Issue by bLeyaa** [WoWManiaUK/Redemption#4228]
**Links:** https://youtu.be/wqdwuJ0f3KA

**What is Happening:** While attacking from distance melee skill is being increased. Not related to a specific weapon. Tested with staff, 2h sword, 2h axe, polearm and fist weapons.

**What Should happen:** Melee skill should not be increased with ranged attacks.

**Comment by jarvik76** [comment]
I couldn't replicate with fist weapons or polearms on test toon, however clearly shows this is an issue in your video.
Maybe it is a talent interfering.  Could you post screenshot of your spec please?

**Comment by svijetlo** [comment]
i can confirm i seen this happen but for the life of me i can not remember where and how

**Comment by svijetlo** [comment]
figured it out 
https://www.wow-mania.com/page/armory
Kill Command from Beast mastery speck on hunter can prock you melee weapon skill to increase

**Comment by wow-mania** [comment]
Then this sounds like as-is to me. There is nothing in code causing this.

**Comment by bLeyaa** [comment]
![talents](https://user-images.githubusercontent.com/61625377/76680388-65070b80-65e8-11ea-8905-dd7c0cea0119.jpg)

An example of my macroed abilities, so you're aware what's possibly triggering it:
#showtooltip Chimera Shot
/cancelaura Hand of Protection
/cast Chimera Shot
/cast Silencing Shot
/cast Kill Command
/cast Furious Howl(Rank 6)
/cast Rabid
/petattack

**Comment by svijetlo** [comment]
seen your vid every time you do kill command it does it as K,C, is 1 min cd it can happen every 1 min tho not 100% of times but a lot

**Comment by jarvik76** [comment]
I can't seem to replicate this with KC while in Marksman spec.  Not getting melee skills on KC use.  Wondering if there is some specific talent in BM tree causing this.

**Comment by Keader** [comment]
Fixed

**Comment by bLeyaa** [comment]
@Rushor @Keader @jeyrella 

Happened again tonight, at range i got staff skill increase.

**Comment by jeyrella** [comment]
Reports this is still an issue / regressed, for retesting

**Comment by svijetlo** [comment]
pet skill is doing it just chek pet skills

**Comment by Keader** [comment]
yeah, is a regression.
i will check again this week

**Comment by Keader** [comment]
test now.

**Comment by svijetlo** [comment]
it is fine now no pet skill for sure kill command will not give wepon skill
