### ISSUE TITLE
[Item] Swift Gryphon & Swift Wind Rider on-use text incorrect

### ISSUE THREAD

**Issue by jeyrella** [WoWManiaUK/Redemption#4231]
**Links:**
https://www.wow-mania.com/armory/?item=25527
https://www.wow-mania.com/armory/?item=25528
https://www.wow-mania.com/armory/?item=25529
https://www.wow-mania.com/armory/?item=25531
https://www.wow-mania.com/armory/?item=25532
https://www.wow-mania.com/armory/?item=25533

**What is Happening:**
The on-use descriptions of Swift Gryphons and Swift Wind Riders are incorrect, they do not reflect that they are summonable in Azeroth.
![image](https://user-images.githubusercontent.com/46089380/76687283-605b4b00-661a-11ea-812d-18c525bd9da7.png)

However the Swift Blue Gryhpon and Swift Red Wind Riders are correct.

**What Should happen:**
The text of the other grphyons & wind riders should be adjusted to that of the Blue/Red ones.
i.e.
Teaches you how to summon this mount. Can be summoned in Azeroth, Outland or Northrend.  This is a very fast mount.
(Note:  Many were fixed in #3800 but these were missed.)
![image](https://user-images.githubusercontent.com/46089380/76687277-4f123e80-661a-11ea-8bd9-e9641131a624.png)

**Comment by svijetlo** [comment]
![gryphon](https://user-images.githubusercontent.com/61908373/76701777-7291c380-66c4-11ea-9549-fa5d81d9e545.jpg)

**Comment by jarvik76** [comment]
"All over Azeroth" is incorrect, since Outland and Northrend is not Azeroth.
The correct text should be the same as the Blue Gryphon.

> Teaches you how to summon this mount. Can be summoned in Azeroth, Outland or Northrend. This is a very fast mount.

**Comment by wow-mania** [comment]
This is implicit. They are summed everywhere.

**Comment by jeyrella** [comment]
Excellent, thanks janitor
![image](https://user-images.githubusercontent.com/46089380/76783119-31271400-67a9-11ea-8cb8-d52d70992561.png)
