### ISSUE TITLE
[Spells/Boss] Mind controlled mages, can cast while iceblocked

### ISSUE THREAD

**Issue by Keader** [WoWManiaUK/Redemption#4234]
In some enconters like Blood Queen or Lady Deathwhisper, mages controlleds can continue cast while mind controlled.
Something like this video: https://youtu.be/bw6N3j53R5M
It's incorrect, iceblocked mages should not cast a thing.

**Comment by tvshadowz** [comment]
Could not cast Iceblock during the icc10nm blood queen mind control. See screenshot. 
![WoWScrnShot_031520_201838](https://user-images.githubusercontent.com/30256554/76715663-55c4b280-66fb-11ea-9693-1ec329a5c121.jpg)
