### ISSUE TITLE
[Achievement/ICC] Flu Shot Shortage

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#4236]
**Links:** https://www.wowhead.com/achievement=4615/flu-shot-shortage-25-player
https://www.wowhead.com/achievement=4577/flu-shot-shortage-10-player
https://www.wowhead.com/spell=69291/inoculated

**What is Happening:** The achievement only checks stacks of [Inoculated](https://www.wowhead.com/spell=69291/inoculated) when the boss dies. It does not check that raid-wide stacks were lower than 3 during the entire encounter.

**What Should happen:** No party member should EVER (at any point of the fight) have 3 stacks for the achievement to be awarded.

**Comment by tvshadowz** [comment]
Confirmed, tested in 10nm and 25nm. Players should not gain the achievement if someone within the raid ever receives 3 stacks but currently if you kill the boss after the stacks have reset you still gain the achievement. 

Picture 1 - Having 3 stacks
Picture 2 - Stacks reset 
Picture 3 - Gaining the achievement

![WoWScrnShot_031520_135417](https://user-images.githubusercontent.com/30256554/76708699-ecc34780-66c6-11ea-9710-00e21a5d826f.jpg)
![WoWScrnShot_031520_135424](https://user-images.githubusercontent.com/30256554/76708703-f056ce80-66c6-11ea-8a84-2615d4843511.jpg)
![WoWScrnShot_031520_135456](https://user-images.githubusercontent.com/30256554/76708705-f2209200-66c6-11ea-88d0-92a40c3cb0da.jpg)

**Comment by Rushor** [comment]
could not find a good solution for that sadly, keader guide us please :D

**Comment by Keader** [comment]
Based in code, it never worked lol.
Now it will proper check stack amount.
