### ISSUE TITLE
[Quest] Krolmir, Hammer of Storms

### ISSUE THREAD

**Issue by bLeyaa** [WoWManiaUK/Redemption#4237]
**Links:**https://www.youtube.com/watch?v=7aTSFJ5xspA

**What is Happening:** There is no event once King Jokkum comes to Thunderfall

**What Should happen:** Event should be taking place as shown in the video.

P.S. Thorim also did not appear for the quest to be turned in and next one to be picked up. I happened to stay in the same place for some minutes chit chatting and noticed Thorim had appeared meanwhile so i could turn in the quest and take the following one.

**Comment by wow-mania** [comment]
Works. Check requirements.

**Comment by bLeyaa** [comment]
Quest can be completed, but there is no event.

**Comment by WhitephoenixTheBunny** [comment]
@Rushor , you are the event guy

**Comment by Rushor** [comment]
the event is really happening. maybe it just failed to spawn. but i saw in on ptr several times
