### ISSUE TITLE
[Quest] Forging a Head

### ISSUE THREAD

**Issue by bLeyaa** [WoWManiaUK/Redemption#4238]
**Links:** 
https://www.wow-mania.com/armory/?quest=12985
https://www.youtube.com/watch?v=kgHlDznPXlY; 
https://www.youtube.com/watch?v=B1HYDRLDnVU (better quality, although later than WotLK)

**What is Happening:** The giants never drop [Stormforged Eye](https://www.wowhead.com/item=42423/stormforged-eye#comments) upon being salvaged. On the contrary, they always spawn the [Stormforged Ambusher](https://www.wowhead.com/npc=30208/stormforged-ambusher) which should only be a possibility of a spawn. These ambushers are not always lootable.

**What Should happen:** The giants should occasionally salvage 2x [Stormforged Eye](https://www.wowhead.com/item=42423/stormforged-eye#comments) and have the possibility to spawn 3x [Stormforged Ambusher](https://www.wowhead.com/npc=30208/stormforged-ambusher) instead of one. The loot table on them needs to be updated as well as they currently only drop the eyes for the quest and nothing else.

**Comment by jarvik76** [comment]
Dead Iron Giant:  https://www.wow-mania.com/armory/?npc=29914

**Comment by jarvik76** [comment]
- [ ] Giants drop Stormforged Eye upon being salvaged
- [ ] Giants can spawn 3x Stormforged Ambusher instead of one
- [ ] Loot table on spawned Stormforged Ambusher corrected (https://www.wowhead.com/npc=30208/stormforged-ambusher#drops:0-19+16+1)

**Comment by Rushor** [comment]
okay all done now. issue was related to stun in feign death aura of the creatures.

**Comment by jeyrella** [comment]
Looks good for all 3 issues:
![image](https://user-images.githubusercontent.com/46089380/76781846-3edb9a00-67a7-11ea-97b5-fef395e01eeb.png)

![image](https://user-images.githubusercontent.com/46089380/76781961-734f5600-67a7-11ea-9fc3-861a27ee2a2b.png)

![image](https://user-images.githubusercontent.com/46089380/76781646-f7eda480-67a6-11ea-99af-14f834c28675.png)
