### ISSUE TITLE
[Quest] The Earthen Oath

### ISSUE THREAD

**Issue by bLeyaa** [WoWManiaUK/Redemption#4239]
**Links:** https://www.wowhead.com/quest=13005/the-earthen-oath

**What is Happening:** Iron Sentinels and Iron Dwarf Assailant kills count 2 for 1.

**What Should happen:** Each Iron Sentinel and Iron Dwarf Assailant kill should only account 1 kill for the quest progress.

**Comment by jarvik76** [comment]
Confirmed, kill count increases by 2 each time

**Comment by jeyrella** [comment]
Now, if the **player** kills the dwarf/sentinel, only 1 kill is correctly recorded, BUT if the summoned Oathbound Warder pet kills them, there is no credit given towards the quest.
Since the quest specifically is to use the pet to kill the targets, this is a somewhat crucial requirement.

**Comment by Rushor** [comment]
updated

**Comment by jeyrella** [comment]
Yep working now!  thanks @Rushor 
![image](https://user-images.githubusercontent.com/46089380/76786507-3ab37a80-67af-11ea-9904-0f518f7ff2fa.png)
