### ISSUE TITLE
[Mount] Cobalt Pterrodax has too low riding skill requirement - 161665

### ISSUE THREAD

**Issue by jeyrella** [WoWManiaUK/Redemption#4240]
**Links:**
https://www.wow-mania.com/armory/?item=161665

**What is Happening:**
Currently requires 225 skill and level 60; this is a flying 280% mount and thus should require level 70 and 300 skill (Artisan).
![image](https://user-images.githubusercontent.com/46089380/76711102-fc618100-6704-11ea-9d59-d85195138c01.png)

**What Should happen:**
Currently requires 225 skill and level 60; this is a flying 280% mount and thus should require level 70 and 300 skill (Artisan).

**Comment by Rushor** [comment]
remember to delete cache before testing :)

**Comment by jeyrella** [comment]
will test tonight

**Comment by jeyrella** [comment]
Looks good
![image](https://user-images.githubusercontent.com/46089380/76780471-01760d00-67a5-11ea-97d6-1ab686053724.png)
