### ISSUE TITLE
[NPC] Vile

### ISSUE THREAD

**Issue by bLeyaa** [WoWManiaUK/Redemption#4241]
**Links:** https://youtu.be/jeWKrYznlTY ; https://www.wowhead.com/npc=29769

**What is Happening:** Weird movement while attacking, keeps player in combat after dying.

**What Should happen:** His pathing i suppose needs to be fixed. Upon dying player should leave combat.

**Comment by bLeyaa** [comment]
Same happens with [The Leaper](https://www.wowhead.com/npc=29840/the-leaper) and [Lady Nightswood](https://www.wowhead.com/npc=29770/lady-nightswood).

I believe all 3 links are correct for the NPCs prior to obtaining reputation with Ebon Hold.

**Comment by svijetlo** [comment]
that is new , i did those few days ago to test follow up quest line it was working fine , will check it all tomorrow
