### ISSUE TITLE
[NPC] The Scarlet Crusade 

### ISSUE THREAD

**Issue by CaliBoiiBeezy** [WoWManiaUK/Redemption#4242]
**Links:**
https://flic.kr/p/2iEE7TT

**What is Happening:**
The Scarlet Covert text is in a different language.

**What Should happen:** 
The Scarlet Covert text should be in English

**Comment by bLeyaa** [comment]
You're horde, this is a human npc. It is in English, but because of the factions you see [Common] "text". Not sure if the "language barrier" was removed for interaction with NPCs like it was between players though.

**Comment by tvshadowz** [comment]
This is working as intended.
