### ISSUE TITLE
[Quest] Honor Challenge

### ISSUE THREAD

**Issue by bLeyaa** [WoWManiaUK/Redemption#4243]
**Links:** https://www.youtube.com/watch?v=RR3lGLcjOUE ; https://www.wowhead.com/quest=12939/honor-challenge

**What is Happening:** Mjordin combatants kills account for the quest when they're killed without using Challenge Flag (quest item). In addition, Combatants do not respond to the the flag and there is no interaction from their side. They receive the challenge flag debuff, but that's it.

**What Should happen:** As shown on the video. In addition, the positioning of the combatants across the area is off. First, there's too many of them. Second, they're all clamped up together instead of being 2 by 2 in pairs.

**Comment by wow-mania** [comment]
As-is.

**Comment by Rushor** [comment]
i have a fix for that :) https://i.imgur.com/8v6YKOY.jpg

https://i.imgur.com/G4qLZxf.jpg https://i.imgur.com/YpGnBSX.jpg

you now actually need to place the flag and then the actions like in the video will start.
