### ISSUE TITLE
[Quest] Honor is for the weak

### ISSUE THREAD

**Issue by bLeyaa** [WoWManiaUK/Redemption#4244]
**Links:** https://www.youtube.com/watch?v=IJHKEX5J1Cc ; https://www.wowhead.com/quest=13170/honor-is-for-the-weak

**What is Happening:** When using "Assassinate Restless Lookout" ability on Restless Lookout creep, they do not die but keep healing up. If the ability is used more than once on the same target, it will account for 2 kills rather than 1.

**What Should happen:** The ability should either one shot them or leave them at very low hp which is followed by the debuff (debuff is currently present btw) and then dying there on the spot. Each kill should be accounted 1 for 1.

**Comment by svijetlo** [comment]
i did it wo problems 1 use of skill 1 shoot each one of them , tho i did find spot where is 3 of them that can be targeted but on use of skill it say Invalid target on all 3 of them there 
![WoWScrnShot_031620_102043](https://user-images.githubusercontent.com/61908373/76741747-5ba8ab00-6770-11ea-99c5-685ee3ee6314.jpg)

**Comment by bLeyaa** [comment]
They are being one shot, but with a delay of few seconds every time, which is the duration of the debuff

**Comment by jeyrella** [comment]
@svijetlo Not sure this is invalid; 1 kill should not count twice in the quest counter, right?   Can't test until this evening though.

**Comment by svijetlo** [comment]
1 shoot 1 kill , quest counted 1 by one not 2 , no delay in kill basically i use skill they drop down should have recorded it to think of it now

**Comment by svijetlo** [comment]
ok need to change me self i me sorry , run it on druid works fine, then i did it on paladin and rogue and i did encounter problem he told in 1st place

**Comment by Rushor** [comment]
related to the creature not entering combat. will try to fix that for that ability

**Comment by Rushor** [comment]
you will only get one credit now. this is only fixed fot that ability. vehicles are strange

**Comment by svijetlo** [comment]
they do need couple  hits to die or for debuff to run out to kill them no healing up  , but multiple hits on them after death counts as one kill in quest so i would say this is fine

**Comment by Rushor** [comment]
if you wait until the debuff fades out, you get the credit
