### ISSUE TITLE
[Quest] Shadow Vault Decree

### ISSUE THREAD

**Issue by bLeyaa** [WoWManiaUK/Redemption#4245]
**Links:** https://www.youtube.com/watch?v=zNPsDeTah7M&t=22s ; https://www.wowhead.com/quest=12943/shadow-vault-decree

**What is Happening:** The event starts as soon as you enter the room / engage one of the mobs inside.

**What Should happen:** The event should only start after using the quest item, which should work as indicated on the tooltip.

**Comment by tvshadowz** [comment]
Ufrang the mighty may be engaged prior to using the quest item suggested on the tooltip. This does not prevent the quest from being completed and the scripting does still work.

**Comment by Rushor** [comment]
yes the faceaggro should not be there. will be fixed once ptr is up again.
