### ISSUE TITLE
[Dungeon] The Oculus

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#4246]
**Links:** https://www.wowhead.com/the-oculus

**What is Happening:** When you die from falling off one of the platforms in [The Oculus](https://www.wowhead.com/the-oculus), your body gets sent to the wrong location. (Usually to where your hearthstone is set) As a ghost, the player can walk to his misplaced body and ress before going back to the dungeon through RDF. Many people don't know about that and will instead take ress sickness and whine in world chat.

**What Should happen:** Dying from falling in The Oculus should revive you at 50% at the Coldarra graveyard.

**Comment by svijetlo** [comment]
i do remember this happening long ago to everyone, even me 
but today i did 5x suicide on 3 toons and every time i get out as ghost at caldera graveyard
to think if it 2 or so months ago there was github post were dev changed it that you ALWAYS got to caldera graveyard

**Comment by Rushor** [comment]
Just a random issue
