### ISSUE TITLE
[Boss] Svala Sorrowgrave

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#4247]
**Links:** https://www.wowhead.com/npc=26668/svala-sorrowgrave

**What is Happening:** Upon finishing the RP event, [Svala Sorrowgrave](https://www.wowhead.com/npc=26668/svala-sorrowgrave), the first boss of Utgarde Pinnacle does not become hostile or attackable. No matter how long you wait, the fight never starts.

**What Should happen:** Svala should become attackable once the RP finishes.

**Comment by svijetlo** [comment]
![WoWScrnShot_031720_094412](https://user-images.githubusercontent.com/61908373/76838102-046c0e80-6834-11ea-8160-5b6522a9c2b0.jpg)

**Comment by Rushor** [comment]
Will check

**Comment by Rushor** [comment]
bossfight should be triggered again.

**Comment by bLeyaa** [comment]
The dungeon boss is attackable, however there is a delay when she goes into air phase, and the debuff applied from the falling sword delays with her landing as well. The delay is present even if you kill the 3 adds.

PTR: https://youtu.be/qrrqOCmQgS0

**Comment by Rushor** [comment]
well that is not related to this issue then

**Comment by bLeyaa** [comment]
I'll make a new post about it
