### ISSUE TITLE
[Dungeon] Trial of the Champion

### ISSUE THREAD

**Issue by svijetlo** [WoWManiaUK/Redemption#4248]
**Links:**
https://youtu.be/26Ui9FfV-Ko?t=388

**What is Happening:**
After you defeat Fraction champions on the non mounted fight they reappear on mount stay around for the rest of dungeon. you can not agro or damage them.

![WoWScrnShot_031720_170442](https://user-images.githubusercontent.com/61908373/76880267-baa51780-6877-11ea-81d2-81cf93050f87.jpg)
![WoWScrnShot_031720_171218](https://user-images.githubusercontent.com/61908373/76880284-bf69cb80-6877-11ea-890e-f48723a87884.jpg)

**What Should happen:**
After you defeat them they should run out and clear the arena for the next encounter

**Comment by tvshadowz** [comment]
I haven't been able to reproduce this

**Comment by bLeyaa** [comment]
It happens every time on live server. I've done it quite a bit recently and every time it was the same thing. Sometimes the pet would bug out and try to attack them but with no success of course.

**Comment by jeyrella** [comment]
Confirmed, has happened to myself too.  Certainly on nm, have not tested on hc

**Comment by tvshadowz** [comment]
This happens more so on the alliance side and on horde you see the horde bosses mount up, run away and disappear, the alliance bosses also disappear

**Comment by Keader** [comment]
check now pls

**Comment by tvshadowz** [comment]
Fixed confirmed both alliance and horde side
