### ISSUE TITLE
[NPCs] Wintergrasp alliance NPCs don't path back to their original locations

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#4249]
**Links:** https://www.wowhead.com/npc=31054/anchorite-tessa
https://www.wowhead.com/npc=31036/commander-zanneth
https://www.wowhead.com/npc=31109/senior-demolitionist-legoso
https://www.wowhead.com/npc=31051/sorceress-kaylana
https://www.wowhead.com/npc=31052/bowyer-randolph
https://www.wowhead.com/npc=31108/siege-master-stouthandle
https://www.wowhead.com/npc=31051/sorceress-kaylana
https://www.wowhead.com/npc=31153/tactical-officer-ahbramis

**What is Happening:** The Wintergrasp alliance NPCs don't path back to their original locations outside the fortress when Alliance don't have control over it. Hordes can aggro them and drag them really far and they won't go back.

**What Should happen:** The NPCs should automatically go back to their original location when they leave combat.

**Comment by Rushor** [comment]
will add a generic one for that

**Comment by Rushor** [comment]
okay try now pls

**Comment by svijetlo** [comment]
https://github.com/WoWManiaUK/Redemption/issues/4603#issue-628133057  

this is happening again 
closed new post so it is not double

**Comment by Oganku** [comment]
Is happening again.
