### ISSUE TITLE
[Quest] Weird dead during the Magic Carpet Ride

### ISSUE THREAD

**Issue by yani** [WoWManiaUK/Redemption#4250]
**What is Happening:**
During the quest *Magic Carpet Ride*, it's possible for *Kel'Thuzad* to kill you while you are on the magic flying carpet after talking to *Yanni*

**What Should happen:**
I don't think it should be possible for *Kel'Thuzad* to kill you.

![image](https://user-images.githubusercontent.com/6956790/76912684-05915000-68b5-11ea-8c79-f7c93b69e04f.png)

The screenshot is my char being dead high up in the air. I guess right in the range of Kel'Thuzad.

**Comment by jeyrella** [comment]
https://www.wow-mania.com/armory/?quest=11636

**Comment by jeyrella** [comment]
Confirmed.  As player flies over Kel'thuzad on the carpet ride, he targets and casts Soul Flay
Kel'Thuzad: https://www.wow-mania.com/armory/?npc=25465
https://www.wow-mania.com/armory/?spell=50319
![image](https://user-images.githubusercontent.com/46089380/77012350-b5be9180-6965-11ea-95d7-294c797d04a3.png)

In fact, he even targets and casts it at GMs in GM invis mode too ;)

**Comment by Rushor** [comment]
spell cast range reduced. ke should no longer target people on the carpet.
