### ISSUE TITLE
[Vehicle] Tank projectile flies in wrong direction during The Plains of Nasam

### ISSUE THREAD

**Issue by yani** [WoWManiaUK/Redemption#4251]
**What is Happening:**
During the quest *The Plains of Nasam*, when casting *The Demoralizer* while in a in the tank, the projectile flies to a different direction.

**What Should happen:**
The projectiles should fly directly straight as seen in this video: https://www.youtube.com/watch?v=2_YqAxsZvYg

![image](https://user-images.githubusercontent.com/6956790/76912790-66208d00-68b5-11ea-9aac-669d4329abae.png)

You can see the projectile flying to the left after firing it. The tank is still positioned in the way it was fired.

**Comment by jeyrella** [comment]
https://www.wow-mania.com/armory/?quest=11652

**Comment by Keader** [comment]
Clientside issue, i cant help with that.
Missing this information in spell:
![image](https://user-images.githubusercontent.com/7120913/77226666-e0bd0700-6b58-11ea-9a06-af5ef1695a8c.png)

**Comment by wow-mania** [comment]
Will mark this as-is / won't fix for now.
Quest is doable so it does not affect the outcome.
