### ISSUE TITLE
[NPC] No spirit healer in Borean Tundra

### ISSUE THREAD

**Issue by yani** [WoWManiaUK/Redemption#4252]
**What is Happening:**
There is no Spirit Healer at the graveyard at Borean Tundra.

**What Should happen:**
I think there should be a Spirit Healer at this graveyard.

![image](https://user-images.githubusercontent.com/6956790/76912880-a97afb80-68b5-11ea-9af1-b45596c92e68.png)

**Comment by Sharuzan** [comment]
This appears to be a common misconception, seeing as no databases contains a spirit healer at that particular location. While it definitely looks like there should be one, it appears that there never was :)

**Comment by Rushor** [comment]
confirmed. if you check https://www.wowhead.com/npc=6491/spirit-healer#map there should be one.

**Comment by jeyrella** [comment]
Also, if you die in the vicinity and release, you end up releasing here; yet there is no Spirit Healer at this location.  Logically, that wouldn't make sense, as the point of the Spirit Healer is so you can revive.

**Comment by svijetlo** [comment]
![WoWScrnShot_032120_165458](https://user-images.githubusercontent.com/61908373/77230471-bf7a0c00-6b94-11ea-9453-3d62f991d46e.jpg)
