### ISSUE TITLE
[NPC/Raid] Onyx Flamecaller - General Zarithrian spawned adds

### ISSUE THREAD

**Issue by bLeyaa** [WoWManiaUK/Redemption#4254]
**Links:** https://www.wowhead.com/npc=39814/onyx-flamecaller

**What is Happening:** When the adds are spawned they do not pull any aggro from the players. E.g. they would spawn and run into the same spot, next wave would walk in into the same spot again.

**What Should happen:** Upon being spawned, the adds should try to attack someone and cast their abilities. Random videos to back up: https://www.youtube.com/watch?v=DTQKe9v2nwY ; https://youtu.be/DjT57-w377Y?t=349

**Comment by tvshadowz** [comment]
Currently, the adds will attempt to target players within a small range of them, thus if all players are out of that range then the adds stand still.

**Comment by bLeyaa** [comment]
I believe i was quite close to them when i did it the other day, cant say for sure tho.

**Comment by Rushor** [comment]
should add now
