### ISSUE TITLE
[Quest] During "Abduction", you can chain an unwounded Beryl Sorcerer - ID 11590

### ISSUE THREAD

**Issue by yani** [WoWManiaUK/Redemption#4255]
**What is Happening:**
You can chain an unwounded Beryl Sorcerer, but nothing happens. 

**What Should happen:**
Something different should happen. But I do not know what. It should only be possible when the Beryl Sorcerer is wounded, as stated in the quest log.

![image](https://user-images.githubusercontent.com/6956790/76912977-fe1e7680-68b5-11ea-82b4-0498fe23861e.png)

**Comment by jeyrella** [comment]
https://www.wow-mania.com/armory/?quest=11590
https://www.wow-mania.com/armory/?npc=25316

Confirmed.  Item should not even be usable on target until NPC is <25% health

**Comment by bLeyaa** [comment]
@Rushor 
Cannot be used until low hp, however there is no action shown at cast anymore. The chain shows for a milisecond.
