### ISSUE TITLE
Spell casting through objects

### ISSUE THREAD

**Issue by bLeyaa** [WoWManiaUK/Redemption#4256]
**Links:** N/A

**What is Happening:** Certain spells are usable through objects, such as fiery wall at the beginning of Utgarde Keep (using this as example as i was present when it happened). Example was a protection paladin taunting the adds behind it, which caused them to run through and "break" the wall, making a shortcut.

**What Should happen:** Line of sight should stop the above.

**Comment by Rushor** [comment]
related to m2 objexcts maybe?

**Comment by Keader** [comment]
I cant reproduce in ptr.

![image](https://user-images.githubusercontent.com/7120913/77226809-d9e2c400-6b59-11ea-94db-6166aeaadbea.png)

any reproduce steps?

**Comment by Keader** [comment]
Confirmed by Baguette
![image](https://user-images.githubusercontent.com/7120913/77227925-832db800-6b62-11ea-931c-9e74c692c35c.png)

**Comment by bLeyaa** [comment]
Had a bear tank charge through the same wall last night. @Keader

**Comment by wow-mania** [comment]
The charge is another issue. It is a core thing and will never be 100% fixed. We still have it better than most servers.
