### ISSUE TITLE
[NPC] Halion Loot table - Ruby Sanctum 25man

### ISSUE THREAD

**Issue by bLeyaa** [WoWManiaUK/Redemption#4257]
**Links:** https://youtu.be/T2GGlJ4kXR0?t=339 ; https://youtu.be/cpbIWfLwp-8?t=464 ; https://youtu.be/HPF19n6fY-U?t=424

**What is Happening:** Upon killing Halion in Ruby Sanctum, the boss drops 4 items on each kill instead of 3.

**What Should happen:** The boss should only drop 3 items after being killed on 25 man mode. Couple of different videos provided as proof.

**Comment by jeyrella** [comment]
drops 2 in 10-man:
![image](https://user-images.githubusercontent.com/46089380/77250587-e42bbd80-6c40-11ea-8367-ea9c9c3f5df7.png)

drops 3 in 25-nm
![image](https://user-images.githubusercontent.com/46089380/77250624-235a0e80-6c41-11ea-894d-f760cb38a6cc.png)

drops 3 in 25-hc
![image](https://user-images.githubusercontent.com/46089380/77250688-8ba8f000-6c41-11ea-8375-c7b858b7cf19.png)
