### ISSUE TITLE
[Raid] Pet behavior - Thorim (Ulduar)

### ISSUE THREAD

**Issue by bLeyaa** [WoWManiaUK/Redemption#4258]
**Links:** N/A

**What is Happening:** After running through the hall on the side and getting to the platform where Thorim is standing, the pet does not go down following the player.

**What Should happen:** The pet should jump down with the owner, instead of being stuck and useless on the platform. https://youtu.be/5q7xGDyQJlg?t=210

**Comment by Aristo14** [comment]
Need more info about retail wotlk 3.3.5a workings. The video is an example of without any pet involved besides the warlock imps that do get stuck for so far you can see it.

**Comment by bLeyaa** [comment]
> Need more info about retail wotlk 3.3.5a workings. The video is an example of without any pet involved besides the warlock imps that do get stuck for so far you can see it.
> https://imgur.com/21s7hDv

Do you not see the pets next to the warlocks when they've jumped down, attacking the boss as well?

**Comment by bLeyaa** [comment]
Ok.. I've gone through bunch of videos but can't determine what it really is.

https://www.youtube.com/watch?v=rpfvhXKCiEE 04:16 you will see the dwarf hunter on the left that jumped down without a pet, but then suddenly pet appears next to him

https://www.youtube.com/watch?v=-EJ7AbhOryQ 03:17 you will see hunter pet running behind warlock and then disappearing and showing in the arena going at boss
