### ISSUE TITLE
[Raid] Thorim - second phase (Ulduar)

### ISSUE THREAD

**Issue by bLeyaa** [WoWManiaUK/Redemption#4259]
**Links:** https://www.wowhead.com/npc=32865/thorim

**What is Happening:** There is a long delay with Thorim jumping down after being engaged on the platform. (to get the idea, this evening he jumped down with only 1 minute before berserk). In addition, Berserk phase does not seem to exist

**What Should happen:** Thorim should jump down into the arena shortly after being engaged on the platform. https://youtu.be/o4__jtI--N0?t=345 ; https://youtu.be/BYebcs2jumI?t=373

**Comment by bluemonstrr** [comment]
@bLeyaa at least one person needs to stay up until thorim jumps down, did everyone jump down?

**Comment by bLeyaa** [comment]
> @bLeyaa at least one person needs to stay up until thorim jumps down, did everyone jump down?

We were not running together and by the time the last person jumped, he should have jumped down already. (We even had someone get stuck on the large circle behind him, the immobilization lasts for like 6 seconds i think?)

**Comment by Keader** [comment]
Delay exists and should be there.
I reduced of 8 sec to 4 sec.
And... berserk is working for both phases.
Berserk in phase 1 means: a giant bubble in tunnel.
