### ISSUE TITLE
[Raid] Teleport option - The Spark of Imagination (Ulduar)

### ISSUE THREAD

**Issue by bLeyaa** [WoWManiaUK/Redemption#4260]
**Links:** https://wowwiki.fandom.com/wiki/Spark_of_Imagination

**What is Happening:** The option of porting to Mimiron (Spark of Imagination) becomes available after killing Kologarn.

**What Should happen:** The option should only be available after the first engagement with the boss.

**Comment by Aristo14** [comment]
Need more info on retail wotlk 3.3.5a workings of this. Especially since it isn't a gamebreaking issue.

**Comment by bluemonstrr** [comment]
Killing trash before mimiron on the way to the tram was causing a combat bug. Additionally the tram often bugs out and won't run at all.

**Comment by bLeyaa** [comment]
> Killing trash before mimiron on the way to the tram was causing a combat bug. Additionally the tram often bugs out and won't run at all.

If that's the reason the portal is available then that's another thing. But finding concrete proof that the portal is not available until engaging the boss is probably impossible. It's common sense really, why would there be a whole path of trash mobs and a tram before the boss if you can just skip it with the teleport after Kologarn.

**Comment by Aristo14** [comment]
If this is a work around for other bugs that can't be fixed than it will probably stay as is.

**Comment by Keader** [comment]
Report is correct, but for now will stay as is.
Train is not working correctly, so... sometimes is the only way to go to mimiron
