### ISSUE TITLE
[Raid] ICC loot table - double loot drops

### ISSUE THREAD

**Issue by bLeyaa** [WoWManiaUK/Redemption#4261]
**Links:** N/A

**What is Happening:** Upon being killed, bosses sometimes drop two of the same items from the loot table. e.g. two one hand axes from gunship battle

**What Should happen:** Items should not be duplicated on drops, with exception of T10 marks which are a possibility

**Comment by Rushor** [comment]
https://us.battle.net/forums/en/wow/topic/1772573952 yes. 

was fixed by shauren https://github.com/TrinityCore/TrinityCore/issues/9203

it is  blizzlike https://github.com/TrinityCore/TrinityCore/commit/ca280dbe051f2d9c43bbda128a6aa6bc19d8149f

https://github.com/fvicaria/WoW-Mania/issues/122

**Comment by Rushor** [comment]
okay this has to be inspected again. the duplicates must switch between tokens and equipable items.

**Comment by tvshadowz** [comment]
I have seen this in icc25nm and 25hc but have never seen it in 10nm and 10hc raids.

**Comment by Rushor** [comment]
Equippable item are limited to 1 duplicate drop and Non-equippable items are limited to 3 duplicate drops (this prevents multiple same itemsdrops for worldbosses)

**Comment by bLeyaa** [comment]
Just did a full run on 25nm 5 times and 25hc 5 times, can confirm the fix. :)
