### ISSUE TITLE
[Pet] Hunter pet - spell autocast bug

### ISSUE THREAD

**Issue by bLeyaa** [WoWManiaUK/Redemption#4263]
**Links:** https://youtu.be/XaLQ2YMTgR8

**What is Happening:** When pet runs out of focus (energy), the autocast of abilities stops.

**What Should happen:** Pet should continue to use abilities once enough focus was accumulated.

**Comment by bLeyaa** [comment]
Okay, just tested with @Aristo14 . The way to re-produce it is to keep the pet in Passive mode and then do as shown in the video above. Keeping the Bite on auto cast with Furious Howl (for example) being used to dump the focus to zero will make the pet stop auto casting the Bite. It works fine in other two stances of the pet, but not Passive.

**Comment by Keader** [comment]
test now

**Comment by Sharuzan** [comment]
Pet continues to use autocasts as intended, when enough focus has been accumulated. Fix confirmed :)

**Comment by bLeyaa** [comment]
I cannot reproduce it on PTR anymore either.
Thanks!!
