### ISSUE TITLE
[Spell] Flare - Hunter spell - ID 1543

### ISSUE THREAD

**Issue by bLeyaa** [WoWManiaUK/Redemption#4264]
**Links:** http://www.warcraftmovies.com/movieview.php?id=163895 13:20

**What is Happening:** Flare does not instantly reveal someone from the area of effect, but is delayed by the visual travel time.

**What Should happen:** Flare should instantly apply the debuff upon cast, with the visual being as it currently is.

**Comment by Rushor** [comment]
i have a fix for that

**Comment by jeyrella** [comment]
https://www.wow-mania.com/armory/?spell=1543

**Comment by Rushor** [comment]
spell should be instant now.
