### ISSUE TITLE
[Pet] Hunter pet GCD

### ISSUE THREAD

**Issue by bLeyaa** [WoWManiaUK/Redemption#4266]
**Links:** 1. https://www.wowhead.com/forums&topic=157123 ; 
2. https://imgur.com/80HWFVL ; 
3. https://outdps.wordpress.com/2009/05/29/shandaras-dps-spreadsheet-guide-updated/ (4th pic from bottom up) ; 
4. http://www.worldoflogs.com/reports/0w1utsdyg1suwv3a/xe/?x=spell%3D%22Bite%22+AND+targetName%3D%22The+Damned%22

**What is Happening:** GCD on Bite spell (probably Claw and Smack as well) is 1.5s instead of 1.25s.

**What Should happen:** The GCD should be 1.25s.

FYI, 2nd and 3rd links are based on shandara's dps spreadsheet(a highly valued hunter spreadsheet back in the day). I can't find the actual spreadsheet, but only screenshots like these.

**Comment by bLeyaa** [comment]
GCD still seems to be 1,5 seconds.

**Comment by Keader** [comment]
![image](https://user-images.githubusercontent.com/7120913/77256102-d3804500-6c4a-11ea-89ad-55ccf61a6843.png)

Now is correct.
Was missing rank 9-11.
