### ISSUE TITLE
[Pet] Pet weird pathing

### ISSUE THREAD

**Issue by bLeyaa** [WoWManiaUK/Redemption#4267]
**Links:** https://youtu.be/fbHTg-LJzqg

**What is Happening:** Pet follows weird path coming to the owner. This is also visible when sending pet to attack.

**What Should happen:** Pet should use the closest distance and adjust on the go.

**Comment by Aristo14** [comment]
Need way more info on this. 
What situation? Where? What pet type? etc etc

**Comment by bLeyaa** [comment]
All of your questions were answered on the video provided in the original post.
I don't have details for sending pet to attack yet, but i'll post the recordings of that as well if needed.

**Comment by bLeyaa** [comment]
This might help additionally. https://youtu.be/i8adpZv79AM

**Comment by bLeyaa** [comment]
@Keader @Rushor 

Can we please have another look at this? This seems to happen with warlock pets as well.

**Comment by wow-mania** [comment]
Also please if an issue is reopened mark it as regression.

**Comment by Keader** [comment]
What ? Regression without a fix ? O.o

**Comment by bLeyaa** [comment]
That's what i was thinking... Can't be regressing when it was never fixed.
