### ISSUE TITLE
[Pet] Focus(energy) - hunter pet

### ISSUE THREAD

**Issue by bLeyaa** [WoWManiaUK/Redemption#4268]
**Links:** https://youtu.be/oPyMoaytmoQ?t=45 ; https://youtu.be/lZSza_bqQI0?t=74 ; https://youtu.be/zxIMtOriauw?t=158

**What is Happening:** Every time you dismount pet's focus is being reset to 0.

**What Should happen:** Pet's focus should not reset every time. I am not sure, but i suppose it should be regenerating even when pet is hidden(player mounted)?

**Comment by Aristo14** [comment]
Make sure it is confirmed blizz 3.3.5a

**Comment by bLeyaa** [comment]
https://youtu.be/FXjoSaP054I?t=53
https://youtu.be/R8UaXL8No_k?t=39
