### ISSUE TITLE
[Quest] Generosity Abounds

### ISSUE THREAD

**Issue by bLeyaa** [WoWManiaUK/Redemption#4269]
**Links:** https://youtu.be/E38MC9ZSJhU

**What is Happening:** While moving with the bombs, they visually disappear, but with different angle do show up again. (see video)

**What Should happen:**  The object should always be visible while moving.

**Comment by jeyrella** [comment]
https://www.wow-mania.com/armory/?quest=13146

**Comment by jeyrella** [comment]
@Rushor have yoiu already fixed this?  I couldn't replicate.
@bLeyaa is this at a particular resolution or graphics setting?

**Comment by Rushor** [comment]
Hey btw leyaa could you Limit the Tickets to 20 / week :) Then it is not too much for us :)

**Comment by bLeyaa** [comment]
LOL 
:(

**Comment by Rushor** [comment]
cannot reproduce aswell https://gyazo.com/14a8fcce017abd0b25e8bc9f54a4ac61

but there is an other issue. the abominations should be ammunce against the knockback effect from the bomb.

**Comment by svijetlo** [comment]
i also could not reproduce this been walking around with bomb for 5ish mins

**Comment by Rushor** [comment]
okay then it is client side issue or a random issue - closed for now until way to reproduce is given :) Thanks all.

**Comment by jeyrella** [comment]
Got exact graphics settings from OP, still cannot reproduce. :(
