### ISSUE TITLE
[Skill] Weapon Skill and Defense Skill not raising

### ISSUE THREAD

**Issue by Gittyhubbers** [WoWManiaUK/Redemption#4270]
**Links:**

**What is Happening:**
Nothing is happening. Night Elf Druid at Lv13. Heirlooms with +Hit at 8.32% and I'm missing Lv7-8 Grey mobs about 8% according to Recount
![WoWScrnShot_031820_222242](https://user-images.githubusercontent.com/36137479/77013013-113d4f00-6967-11ea-8aa0-95ff5491030a.jpg)

**What Should happen:**
Weapon Skill should raise when attacking with weapons. Defence skill should raise when attacked. They are not raising. Damage isn't improving as Weapon Skill appears to be set at 1. Damage reduction isn't working as Defence doesn't appear to be raising either.

Several people have noticed this and it apparently is an issue only affecting new characters?
![WoWScrnShot_031820_222655](https://user-images.githubusercontent.com/36137479/77013268-9b85b300-6967-11ea-9449-00dcf72c93b4.jpg)
 Even using vendor bought trash weapons I'm still missing a lot more than I should be attacking lv6 greys at lv13. Still the same +8.32% Hit rating.

**Comment by Rushor** [comment]
I think that was working - we must check

**Comment by Gittyhubbers** [comment]
Update: Bear form is unaffected. I never miss while attacking as Bear, even against yellow mobs. Defence does not raise in Bearform though.

**Comment by wow-mania** [comment]
hmm can someone confirm this please? highly unlikely...

**Comment by WhitephoenixTheBunny** [comment]
I have tested yesterday, on live, with a DK, Draenei, level 80, axes = not leveling - used some spells and auto attack, also tested with a Priest, Draenei, level 80, staff = not leveling, used autoattack

**Comment by WhitephoenixTheBunny** [comment]
@Rushor https://github.com/WoWManiaUK/Redemption/issues/4228 related? Cause of it?

**Comment by Keader** [comment]
Possible? not sure.
I will try take a look tonight.

**Comment by Keader** [comment]
Please test now @WhitephoenixTheBunny / @jeyrella on ptr.

**Comment by WhitephoenixTheBunny** [comment]
damn, you was faster

**Comment by svijetlo** [comment]
i em busy bee :D
