### ISSUE TITLE
[Spell] Fel Intelligence buff

### ISSUE THREAD

**Issue by bLeyaa** [WoWManiaUK/Redemption#4272]
**Links:** https://wowwiki.fandom.com/wiki/Fel_Intelligence

**What is Happening:** If there is a warlock and a priest in the raid, the raid will not benefit from the intellect part of the buff due to priest's spirit buff.

**What Should happen:** Felhunter's buff should be present while not stacking with priest/mage buff. The buff should provide intellect and spirit if no priest/mage in the group. Only intellect with priest in group and only spirit with mage in group. The buff should only become redundant when both priest and mage are present in the group. By present i mean, the buffs are given by the classes.

**Comment by Rushor** [comment]
There is a stacking Group for that i think

**Comment by Keader** [comment]
Is wrong.
I have a fix for It, Will fix tomorrow

**Comment by tvshadowz** [comment]
PTR: the priest buff overrides the fel hunter buff but both are shown to be active
