### ISSUE TITLE
Quest: Fortunate Misunderstandings, npc bug

### ISSUE THREAD

**Issue by Speeaker** [WoWManiaUK/Redemption#4273]
**Links:**
Link 1: https://www.wowhead.com/quest=12570/fortunate-misunderstandings
Link 2: https://www.youtube.com/watch?v=ZPYAhuqMz5w

**What is Happening:**
When telling the Injured Rainspeaker Oracle that you are ready to travel to the village he teleports to island in Frenzyheart River and despawns after some time.

**What Should happen:**
When telling the Injured Rainspeaker Oracle that you are ready to travel to the village he starts walking to the village.

**Comment by wow-mania** [comment]
Works
