### ISSUE TITLE
[Dungeon] Gundrak Boss: Eck the Ferocious

### ISSUE THREAD

**Issue by RyogoKusama** [WoWManiaUK/Redemption#4274]
**Links:**
https://www.wowhead.com/npc=29932/eck-the-ferocious

**What is Happening:**
Two bugs:
1- It spawns in Gundrak normal (it shouldn't, it's a Heroic Boss-only)
2- It hits enrage a whole one minute (60 seconds) before it should, making the fight a tiny bit harder for your average group (tracked the timer with Deadly Boss Mod addon for our current patch)

**What Should happen:**

1- It shouldn't spawn in Gundrak normal.
2- It should hit Enrage later in the fight.

**Comment by wow-mania** [comment]
Given that this is not retail or a progressive realm we have things slightly harder than usual.
We will keep this as-is for now.
Thanks for the report.

**Comment by RyogoKusama** [comment]
Well, I can get behind the "hard" thing, but still, it shouldn't spawn in the Normal version...

**Comment by Rushor** [comment]
hardmode/enrage aura is always like that. can you give us a source for the timer of the enrage?

**Comment by RyogoKusama** [comment]
> hardmode/enrage aura is always like that. can you give us a source for the timer of the enrage?

https://i.postimg.cc/nzVHvPfQ/Immagine2.png

Fight Starts at: 12:25:24

He goes enrage at: 12:26:34

(1 minute and 10 seconds into the fight, WTF?!)

Again, feel free to leave it like this if it's for the extra "challenge", but don't ignore that this Boss should NOT spawn in NORMAL Gundrak, only in HEROIC Gundrak.

You can check this from its loot table (it only has an Heroic loot table) and from the Dungeons achievements:

Normal Gundrak: https://www.wow-mania.com/armory/?achievement=484
Heroic Gundrak: https://www.wow-mania.com/armory/?achievement=495

**Comment by Blyatman1** [comment]
He definitely is supposed to be a Heroic-only boss, as the door to the passage towards Eck should not open after killing Moorabi on normal.

The enrage timer is only slightly faster if it's set to 70sec, as normally, it'd be 90sec.

https://wow.gamepedia.com/Eck_the_Ferocious
