### ISSUE TITLE
Get loot on any character easy

### ISSUE THREAD

**Issue by Krattzu** [WoWManiaUK/Redemption#4276]
**Links:**
It is possible to get new loot on any character without getting raid loocks.

You just have to do this:
Make a raid with your guild
Kill a boss
Invite another character
Summon it to the boss
Don't accept raid lock
Loot the boss with group loot on
Leave the raid

Easy loot with no locks.

For example: Fresh level 80 can get Lich King 25hc loot :)

**What is Happening:**

**What Should happen:**

**Comment by WhitephoenixTheBunny** [comment]
Loooool
The objective of raid is to work to get the loot...
