### ISSUE TITLE
Broken newline in text after wrong VIP command

### ISSUE THREAD

**Issue by yani** [WoWManiaUK/Redemption#4279]
Picture should explain it. Broken newline

![image](https://user-images.githubusercontent.com/6956790/77237955-b147e200-6bcc-11ea-9094-1bc79cb71e50.png)

**Comment by WhitephoenixTheBunny** [comment]
The command is vip xp 6
You get x2 (12) by default due to double xp weekend.

**Comment by yani** [comment]
I know it is. But look at the "/n" character in the text. It should be a newline.
