### ISSUE TITLE
Gjalebron Attack Plans item do not work

### ISSUE THREAD

**Issue by Kantboll** [WoWManiaUK/Redemption#4280]
**Links:**
https://www.wow-mania.com/armory/?item=33347

**What is Happening:**
Whenever I kill a mob in Gjalerbron (Howling Fjord) that drops the [Gjalerbron Attack Plans] and click on the item to start the quest, it says: "You don't meet the requirements for that quest".

**What Should happen:**
A quest should start, this one: 
https://www.wow-mania.com/armory/?quest=11266

**Comment by wow-mania** [comment]
Then maybe you don't meet the requirements.

**Comment by Rushor** [comment]
you need to do https://www.wow-mania.com/armory/?quest=11261 first. the item is for horde only
