### ISSUE TITLE
[Quest] Bodyguard for Hire - Desolace - 5821

### ISSUE THREAD

**Issue by jeyrella** [WoWManiaUK/Redemption#4283]
**Links:**
Quest:  https://www.wow-mania.com/armory/?quest=5821
Cork Gizelton: http://www.wow-mania.com/armory/?npc=11625

**What is Happening:**
After completing one circuit of Desolace, Cork Gizelton is non-interactive when the caravan stops at northern wait location (66.8,59.1).  He does not offer his quest, or do the "yell" to the zone that the quests is available.  At that point the kodos get stuck on either side, and the caravan does not move again, staying stuck in that place.
Was reset twice by Divigrac with same result - caravan completed one  loop and got stuck at this location

![image](https://user-images.githubusercontent.com/46089380/77259974-c714e000-6c7c-11ea-8192-2adf01addb36.png)

Checking on PTR though:
Reveals caravan seems to be cyclying properly, although Cork is still non-interactive - he should have a gossip text anyway - there must be some additional condition when on live that causes this to happen.

**What Should happen:**

**Comment by jeyrella** [comment]
Stayed there for 16 mins. Didn't move.  (Caravan is only supposed to stay there for 10 mins)

**Comment by wow-mania** [comment]
As-is.
There is specific points during the route where it will.

**Comment by jeyrella** [comment]
Yes.  This is one of thse places where it should.

**Comment by wow-mania** [comment]
Pretty sure there is only one place where it worked and I have done it myself.

**Comment by jeyrella** [comment]
Certainly I've done it myself in the past, no argument there.  Some condition seems to have changed

Armory seems to indicate this is the spot Cork is supposed to be active:
![image](https://user-images.githubusercontent.com/46089380/77272104-4cfa5080-6ca8-11ea-9be7-8eaf69461c7a.png)

**Comment by jeyrella** [comment]
I noticed on PTR as Cork approached this spot, he reversed direction for about 0.5 second, but did not stop, the kodos changed direction with him, then he went back again.  repeated this 3-4 times without about 0.5 second between each "pulse", then carried on walking up the path

**Comment by jeyrella** [comment]
Ok, managed to capture a video of this bug happening on PTR.  
https://youtu.be/gzFdeX8-Jy0
When heading north, Cork stops for no apparent reason at 66.8,59.1.  Rigger and one of the kodos goes past him.... and that's it, nothing else happens after that - neither Gizeltons nor kodos move again until a forced reset.

**Comment by Rushor** [comment]
> I suspect this happens only after some kind of interaction from the player, as earlier on PTR they did continue walking, albeit with that odd shuffle-step at that location.

i removed the option to talk with them during the escort completely now. i think that helps.

**Comment by jeyrella** [comment]
Confirmed that their interaction gossip has been removed, but don't think this has worked.  They were already stuck, killed them and they spawned ok, I followed them round on one complete circuit without interacting, and again when they got the same place they got stuck again in exactly the same way.
![image](https://user-images.githubusercontent.com/46089380/77374541-e25a1b00-6d62-11ea-844e-401b1577eafb.png)

**Comment by wow-mania** [comment]
They stop at a couple of places for a while. Then continue.

**Comment by Rushor** [comment]
i think they just continue the route from scratch once the final point is reached

at waypoint 282 - need to investigate this further

**Comment by Rushor** [comment]
Okay the issue was following: Once the final path point (as you can see in screenshot above) was reached, the creatures never restarted their path.

This should happen now.

**Comment by jeyrella** [comment]
unfortunately takes a whole hour to do a cycle! :D

**Comment by Rushor** [comment]
Yes it is long time :( and pls only test of they do the Route now - nothing else

**Comment by jeyrella** [comment]
Ok now I undestand your last comment :)  
Followed round for two cycles.  Yes, two and a half hours.  Ouch...

So now when they reach the location heading northwards, one copy phases out, and another phases in, heads south for about 2 seconds then turns around and goes north.
Whilst not perfect, I think this is "good enough".

However, now, at the northern location heading south, Bodyguard for Hire quest is no longer available, Cork does not offer it.
![image](https://user-images.githubusercontent.com/46089380/77528869-93a5a180-6e86-11ea-93b3-1759850fa178.png)
![image](https://user-images.githubusercontent.com/46089380/77528913-a91acb80-6e86-11ea-954f-62f00c9236d6.png)

**Comment by Rushor** [comment]
okay :) THANK YOU

**Comment by jeyrella** [comment]
Also tested that quest is correctly offerered at both the correct locations, and is accompanied by the corresponding "yell" by the NPC.

**Comment by Rushor** [comment]
niice
