### ISSUE TITLE
[Core] Dodge

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#4284]
**Links:**  https://wowwiki.fandom.com/wiki/Expertise
Related: #4065 

**What is Happening:** Expertise cap to never be parried in 3.3.5a is 26 expertise against a level 83. Bosses should be able to dodge from all around them. However, bosses on mania seem to currently be unable to dodge whatsoever. In a full raid of ICC 25hc, nobody has ever gotten dodged by a boss. The lower level adds spawned seem to be able to somehow though.

**What Should happen:** Level 83 (skull) bosses should have a 6.5% base chance to dodge incoming melee attacks.

**Comment by Rushor** [comment]
works like that now:

5.85f : 5.0f; // bosses should have 6.5% dodge (5.9 + 0.6 from defense skill difference)

so i will be 26 with all skills against worldbosses

**Comment by Rushor** [comment]
german source for that http://www.fiesstiefel.de/WoW/guide/wk.pdf

**Comment by Aristo14** [comment]
f

**Comment by Aristo14** [comment]
fix needs to be confirmed
