### ISSUE TITLE
Old Kingdom's Herald Volazj freezes during the encounter.

### ISSUE THREAD

**Issue by emeraldastro** [WoWManiaUK/Redemption#4285]
**Links:**
https://prnt.sc/rl3i0z

**What is Happening:**
Herald Volazj casts his Insanity, people start killing the copies of other party members and then, nothing. Every party member is stuck there, unable to get out of the insanity realm and kill the boss.
Teleporting out and back in seems to reset the fight and the boss' starting position was moved.

**What Should happen:**
Once every member's copy is defeated, everyone gets pulled out of the Insanity realm and continues the fight accordingly.

**Comment by Rushor** [comment]
for me it worked smooth so far

kille copy https://i.imgur.com/apBxEcu.jpg
boss attacks again https://i.imgur.com/Cc4XOKM.jpg

**Comment by svijetlo** [comment]
my advice is try to stack close and not run around as clones are slow to get to you

**Comment by Rushor** [comment]
the script is like that: if all summons /copys are killed) the counter will be decreased and the boss become attackable again

**Comment by emeraldastro** [comment]
I am not saying it happens every time but it did happen. I doublechecked with other people outside the dungeon to assure the rest of the server was running smoothly and it was. No idea why it happened but all 5 members had the same issue, we could do nothing but wait there for nothing to happen

**Comment by wow-mania** [comment]
No one said it didn't. Just that if we can't reproduce we can't fix it. 
If it is a corner case and very specific that you bumped into the chances of us finding it are minuscule and not worth the time.

**Comment by emeraldastro** [comment]
You are right about that. I reported it because I thought you'd like to know in case it happens again. Thank you for all the replies

**Comment by svijetlo** [comment]
if it happens again make sure to member some minor detail etc so we can pinpoint what problem might be otherwise it is just burning time
