### ISSUE TITLE
Bugged Quest: It Rolls Downhill

### ISSUE THREAD

**Issue by Psynister** [WoWManiaUK/Redemption#4286]
**What is Happening:**
The item controls a Blight Geist correctly, but the geist does not gather any crystals when you have him, and the command to have them do it or to send them back to turn it in, do not work.

**What Should happen:**
You should be able to control the pet npc, but you cannot.

**Comment by wow-mania** [comment]
works

**Comment by WhitephoenixTheBunny** [comment]
Go near the platform, he will start gatjering crystals

**Comment by Psynister** [comment]
On the platform, near the platform, on the ramp, off the ramp, standing on a crystal, standing beside a crystal, looking at a crystal, standing on top of a crystal - I've collected 1 shard in the last 20 minutes of repeated trying.

Sometimes the pet ability makes him crouch in place, doing nothing. Sometimes it makes him move up or down the ramp. Usually, it does nothing.

**Comment by Psynister** [comment]
And then I did one that gave me credit for 5 in one go. Alright, it "works". It doesn't do what it's supposed to do, but it works.
