### ISSUE TITLE
Mind Control (Priest + Engineer) not fully working. Unable to melee & not using CDs

### ISSUE THREAD

**Issue by Kilju** [WoWManiaUK/Redemption#4287]
**Links:**

Spell IDs:
http://www.wow-mania.com/armory?spell=67839 (Mind Amplification Dish)
http://www.wow-mania.com/armory?spell=605 (Priest Mind Control spell)

NPCs used in tests:
http://www.wow-mania.com/armory?npc=3296 (Orgimmar Grunt)
https://wow-mania.com/armory/?npc=1064 (Grom'Gol Grunt)
https://wow-mania.com/armory/?npc=3100 (Elder Mottled Boar)

**What is Happening:**
Priest mind control: Player targets & Orgrimmar Guards cannot melee/attack in mind control (These 2 I tested)
(Engineering) Mind Amplification Dish: Same issues as Priest MC + controlled players will not move at all.

https://www.youtube.com/watch?v=3Qyi4BQ4-Qc&feature=youtu.be Orgrimmar grunt unable to attack another guard, or a Boar not affliated with orgrimmar.
https://www.youtube.com/watch?v=M_8TxCBrZkk&feature=youtu.be (Engineer MC) Players will try to start melee, but will not move from the spot they were MC'd from.
https://www.youtube.com/watch?v=V4iKM0iQNs4&feature=youtu.be (Priest MC) Players are not able to melee in priest mind control.

**What Should happen:**
Priest MC: You should be able to attack targets with auto attacks in priest mind control. 
(Engineer) Mind amplification dish: The controlled NPC / Player should follow you as a pet and use random abilities and cooldowns (Usually the longest cooldowns you have) and be forced to move and auto-attack.
Videos are gathered from retail vanilla + cataclysm. Did not find wotlk ones with any quality but the functionality should be same. 

https://www.youtube.com/watch?v=3dGijgzrbS4 (Mage mind controls a warrior with mind control cap (NOT WOTLK Engineer DISH, but same functionality), which starts to follow mage and uses battle shout+autoattack, Mage gains  buff 25 seconds in)
https://www.youtube.com/watch?v=Hggwgb9Pgy4 Cataclysm: Ret paladin gets mind controlled by Mind amplification Dish and uses guardian + wings and attacks own faction
https://youtu.be/cQ3gkWbnNnM?t=50 UD Priest mind controls a NPC in alterac mountains and proceeds to attack Alliance members with mind controlled NPC.

**Comment by Sharuzan** [comment]
Neither Grunt will melee-attack anything, when mind-controlled by Priest or Engineer.

Engineer Dish makes the target your pet, but doesn't follow you or attacks enemies.
The target just stands still and turns around to face the direction, of what you want it to kill, without moving.

**Comment by Keader** [comment]
Old issue.
I tryied fix it, when i fix melee of abomination, without success.
Is not item issue, any mind control has it.
I realy dont know how fix it for now.
