### ISSUE TITLE
[Quest] The Deserters - Theramore 1286

### ISSUE THREAD

**Issue by jeyrella** [WoWManiaUK/Redemption#4288]
**Links:**
https://www.wow-mania.com/armory/?quest=1286
https://www.wow-mania.com/armory/?npc=5089

**What is Happening:**
During the quest, players are asked to subdue Balos Jacken (NPC 5089), However, for high level players, one hit kills him and fails the quest, even naked.
This is extremely similar to the issue that was seen & fixed in #4084

**What Should happen:**
Balos Jacken should not die, he should be reduced to 1 hp and stop combat ("be subdued").

**Comment by Aristo14** [comment]
Fix needs to be confirmed

**Comment by jeyrella** [comment]
Confirmed.
![image](https://user-images.githubusercontent.com/46089380/77488939-996f9880-6e2e-11ea-97cd-9cc0d9af0575.png)
