### ISSUE TITLE
Experience interference in party with VIP.

### ISSUE THREAD

**Issue by Hatework** [WoWManiaUK/Redemption#4289]
**Background:** Party of 5, let's call them A, B, C, D and E (Character name - Hrasta). All 5 are using WoW Mania client at 2.6.0. C, D and E have no AddOns. While testing, all players have cleared cache.  A and B, as well as C and D have RAFs and have set the experience to default. E has not Referred and has not been Referred by any player but has VIP and has set his experience rate to 6x. All players are the same level (or 1 level in range as some have leveled during the testing process).

**Issue:** While alone he gets the full benefits of his VIP experience rate, but once in dungeon with A-D he gets far less experience and it seems that any change of the experience rate does not affect that.  We have tried changing experience rates in various forms. At first E had set his experience rate to 6x via the command. Then he tried to set it via the NPC at the Mall. He re-logged every time he did so. He then tried to change the experience rate to different values. His experience gain was not affected at 1x, 2x, 4x and 6x. This issue was confirmed by GM Divigrac with the suggestion that RAF interferes with the VIP experience gain.

**How it should work:** The experience rate of a 3rd party should not be affected by RAF players. I don't think there's any need of a reference. In any event, we refer to Divigrac's assessment. E should be receiving even more experience than the rest of us. This makes playing in party of 5 impossible, renders his VIP useless and wastes the money spent. 

This issue seems to affect unaffiliated players, which could potentially ruin dungeon finders for many players. 

Attaching screenshots:
https://imgur.com/a/bnOr6Cy  - Showing the experience gained by E 
https://imgur.com/a/7yGD4MK - Showing the experience gained by A
https://imgur.com/a/g8dq4IR - All party members stating their experience gain for reference. A and B have heirlooms, C and D do not. Only E (Hrasta) has VIP. 
https://imgur.com/a/DKgbQY9 - GM affirming the existence of the issue just for the sake of it.

**Comment by wow-mania** [comment]
There is no should in VIP. 
As-is VIP is an individual benefit.

**Comment by Hatework** [comment]
This doesn't really answer the issue presented...?

**Comment by jeyrella** [comment]
I think the issue may have been misunderstood.  Reopening for further investigation

**Comment by bLeyaa** [comment]
The non-VIP group members are receiving proper XP as they're RAF accounts. Which equals the XP gained by a VIP player(x6 XP). Not to be confused that they're receiving it for having VIP in group, as that's not the case.

**Comment by wow-mania** [comment]
Please do not re-open this.
It is AS-IS
VIP WILL NOT stack with anyother XP rates or when in group with non-VIPs
