### ISSUE TITLE
[Quest] Raze Direhorn Post visuals missing - Dustwallow Marsh

### ISSUE THREAD

**Issue by jeyrella** [WoWManiaUK/Redemption#4291]
**Links:**
https://www.wow-mania.com/armory/?quest=11150 (A)
https://www.wow-mania.com/armory/?quest=11205 (H)
Torch:  https://www.wow-mania.com/armory/?item=33072
Tents:
https://www.wow-mania.com/armory/?npc=23751
https://www.wow-mania.com/armory/?npc=23752
https://www.wow-mania.com/armory/?npc=23753

**What is Happening:**
Quest is to burn the tents in Direhorn Post in Dustwallow Marsh.  The visual effect of the tents actually burning is missing, there is no visual clue to player that anything has happened other than quest counter increases.

**What Should happen:**
Burned tents should have a visual of them burning.
https://www.youtube.com/watch?v=YOYwyIJlAvE

**Comment by Rushor** [comment]
all visual added

**Comment by Aristo14** [comment]
fix need to be confirmed.

**Comment by jeyrella** [comment]
COnfirmed.
![image](https://user-images.githubusercontent.com/46089380/77488983-bd32de80-6e2e-11ea-920b-46b82198fb9b.png)

**Comment by jeyrella** [comment]
I don't currently have a toon on Redemption that can test on live production.
