### ISSUE TITLE
[Spell] Mark of the Wild buff stacking

### ISSUE THREAD

**Issue by bLeyaa** [WoWManiaUK/Redemption#4292]
**Links:** N/A

**What is Happening:** Mark of the Wild and Gift of the Wild buffs are currently stacking on players. Regardless if it's different druids buffing. The second buff does not increase attributes and resistance but only armor.

**What Should happen:** There can be only ever be only one buff on a player, regardless of who is buffing.

**Comment by Rushor** [comment]
only the strongest effect will remain active now. other will be removed.

added for spells: 21849, 1126, 72588

let me now if i need to add more spells.

**Comment by rizal068** [comment]
![glyph](https://user-images.githubusercontent.com/62842082/77851498-b4ae1f80-7203-11ea-8944-2845f47cec29.png)
![glyph1](https://user-images.githubusercontent.com/62842082/77851503-bd065a80-7203-11ea-9422-11c8be788459.png)

armor still increase from both

**Comment by bLeyaa** [comment]
This is fixed on PTR, not updated yet on live server. :)

**Comment by Keader** [comment]
will be in live tomorrow or in 2 days xD
