### ISSUE TITLE
[Spell] Polymorph 

### ISSUE THREAD

**Issue by svijetlo** [WoWManiaUK/Redemption#4293]
**Links:**
http://www.wow-mania.com/armory?spell=12826
http://www.wow-mania.com/armory?spell=71289
**What is Happening:**
During Lady Death-whisper fight in ICC , ones a player get under effect of LDW spell Dominate Mind and mage cast Polymorph spell on player turn them to any animal  after the effect of dominate mind is over person will be able to cast spells or use any skill in polymorphed state, ergo paladin can dispell it self etc.

**What Should happen:**
Player character in polymorphed state should not be able to cast or use any talents or items

**Comment by Rushor** [comment]
hmm in playerai there seem to be no polymorph spell at all

**Comment by Keader** [comment]
Fixed for all char spell (not just for lady)
