### ISSUE TITLE
Getting instant lock out when walking into Icecrown Citadel

### ISSUE THREAD

**Issue by Darkapples** [WoWManiaUK/Redemption#4294]
**Links:**

**What is Happening:**
Today we were making a group for Icecrown Citadel 10 normal. The raid leader was doing invites on a character that was locked to ICC 10nm. Normally in this situation when entering you would get a warning telling you that you are entering a locked instance, and have to either accept or decline the lock. However when I entered, I just got instantly locked instead. There was no warning at all.

**What Should happen:**
When entering you should get a warning telling you that you are entering a locked instance, and have to either accept or decline the lock.

**Comment by Rushor** [comment]
This is intended change for now - pls see the annoucements in Discord. It prevents special abuses.
