### ISSUE TITLE
Memory error

### ISSUE THREAD

**Issue by yani** [WoWManiaUK/Redemption#4295]
I'm currently often receiving the following memory error:
![image](https://user-images.githubusercontent.com/6956790/77483460-75a95400-6e28-11ea-9cba-e80ff0e8285b.png)

Probably because the **large address aware flag** is not set on the new `WoW-Mania.exe` executable. It's also impossible to set the flag manually. I tried replacing the previously shipped `Wow.exe`, which came with the 2.5.5 full torrent. It's possible this **might fix the errors**. However, launching the Launcher with the changed exe gives: `Invalid or corrupted WoW.exe` (this should also say **WoW-Mania.exe** now btw)

I think it's best to look at why the flag isn't and can't be set, because this fix fixed this error for other players before.
![image](https://user-images.githubusercontent.com/6956790/77477948-7983a900-6e1d-11ea-8dbe-872aca3086f1.png)

SHA-1 checksums:
`Wow.exe` : `2F8041D7046E8DBD9AF5C634372247F42BF374CA`
`WoW-Mania.exe` : `B8D125A408643AC883C878F7B3322EC6A815CB69`

**Comment by wow-mania** [comment]
Client issue issue cause by corrupted file or some other security restriction on the machine
