### ISSUE TITLE
[Quest] Raze Direhorn Post player position issue - Dustwallow Marsh #4291

### ISSUE THREAD

**Issue by Sharuzan** [WoWManiaUK/Redemption#4296]
Links:
https://www.wow-mania.com/armory/?quest=11150 (A)
https://www.wow-mania.com/armory/?quest=11205 (H)
Torch: https://www.wow-mania.com/armory/?item=33072
Tents:
https://www.wow-mania.com/armory/?npc=23751
https://www.wow-mania.com/armory/?npc=23752
https://www.wow-mania.com/armory/?npc=23753

What is Happening:
East Tent has some issues with player placement. Compared to the other 2 tents it doesn't always set the tent ablaze, when using the Torch, in front of the tent or on it's side. 

What Should happen:
Regardless of positioning, as long as the player is close to it and as long as the tent is in line of sight, it should set it ablaze on the first try.

**Comment by Rushor** [comment]
will fix this - related to gameobject range

**Comment by Rushor** [comment]
testable once server is restarted

**Comment by jeyrella** [comment]
Works fine now

**Comment by Rushor** [comment]
perfect
