### ISSUE TITLE
[Spell] Duplicate portal spells at Portal Trainer in Shattrath

### ISSUE THREAD

**Issue by yani** [WoWManiaUK/Redemption#4297]
There are duplicate portals spells at the Portal Trainer in Shattrath.

![image](https://user-images.githubusercontent.com/6956790/77533170-afb13f00-6e96-11ea-8bf7-361608d6e8e5.png)

It's also possible to buy them 2 times. (byebye 20g)
![image](https://user-images.githubusercontent.com/6956790/77533195-b8a21080-6e96-11ea-9cbb-f72541324b60.png)

**Comment by wow-mania** [comment]
Needs condition added it is showing all spells. They are actually different spells.

**Comment by Rushor** [comment]
condition added
