### ISSUE TITLE
[Spell] Warlock Pet Dispel not dispelling Discombobulating Spray

### ISSUE THREAD

**Issue by slaniaxx** [WoWManiaUK/Redemption#4298]
**Links:**
https://classic.wowhead.com/spell=19505/devour-magic
https://www.wowhead.com/spell=71103/combobulating-spray
**What is Happening:**
Devour magic does not dispell Combobulating Spray, if self-cast by warlock

**What Should happen:**
As a pet ability, devour magic should be usable while cc'd and should be able to dispel a magical effect such as combobulating spray.

**Comment by Rushor** [comment]
works fine for me https://gyazo.com/3b1ce4229441eb964ba2ce60b0ec0ad2

**Comment by slaniaxx** [comment]
ignore this, was caused by something else
