### ISSUE TITLE
[Quests] Bomber quests in Icecrown from Fringe Engineer Tezzla

### ISSUE THREAD

**Issue by BeakerGoBoom** [WoWManiaUK/Redemption#4299]
The following quests given by Fringe Engineer Tezzla can not be completed due to the aerial mobs evading all attacks from the bombers turret. Occasionally the gargoyles can be stuck and killed but the Frostbrood Sentrys all seem to evade.

There is no issue with the ground based mobs.

https://www.wowhead.com/npc=32430/fringe-engineer-tezzla
https://www.wowhead.com/quest=13374/amped-for-revolt
https://www.wowhead.com/quest=13376/total-ohmage-the-valley-of-lost-hope
https://www.wowhead.com/quest=13406/riding-the-wavelength-the-bombardment
![evidence](https://user-images.githubusercontent.com/59102678/77578974-d7f96780-6eaf-11ea-82c8-b40776618f77.png)

**Comment by Rushor** [comment]
me must add a kill for the credit

**Comment by Rushor** [comment]
ah nevermind - you can kill them, it's just that evade message. ignore that for now. quest can still be done.
