### ISSUE TITLE
[NPC/Dalaran] Sunreaver Guardian Mage interactions

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#4300]
**Links:** https://www.wowhead.com/npc=15350/horde-warbringer
https://www.wowhead.com/npc=34953/isle-of-conquest-portal
https://www.wowhead.com/npc=29255/sunreaver-guardian-mage

**What is Happening:** The [Horde Warbringer](https://www.wowhead.com/npc=15350/horde-warbringer) in the horde area of Dalaran (Sunreaver Sanctuary) is hostile to alliance players and can be engaged in combat. The [Isle of Conquest Portal](https://www.wowhead.com/npc=34953/isle-of-conquest-portal) to his left is neutral and can also be engaged in combat. As long as they take damage (can be just 1, it has to be repeated) these NPCs will remain in combat with their targets. Also, while in combat, alliance players seem to be less likely to get teleported by [Sunreaver Guardian Mages](https://www.wowhead.com/npc=29255/sunreaver-guardian-mage), making it possible to avoid them and keep hitting the portal and warbringer so as to bring them outside the horde quarter of Dalaran. 

**What Should happen:** These NPCs should not engage in combat ever and/or the Mages should have better eyes.

**Comment by Rushor** [comment]
should no longer be attackable now (all npcs in dalaran)

**Comment by svijetlo** [comment]
players from ally need to stop cliping to horde side :)
