### ISSUE TITLE
Potions 

### ISSUE THREAD

**Issue by Tradervic402** [WoWManiaUK/Redemption#4301]
**Links:**

**What is Happening:**
When I try to drink a potion about 1 time in 10ish I get "you cannot drink again".. even if it's been 30 mins since I have drank anything.  This seems to happen to multiple chars on my account, and has been tested on healing potions and strong trolls blood potions. I can try it later and it may (or may not) work

**What Should happen:**
The potion should take effect.

**Comment by wow-mania** [comment]
I highly doubt this is an issue.

**Comment by Keader** [comment]
What potion are you using?
Good part of potions has 1 min cooldown, not 30 secs

**Comment by svijetlo** [comment]
i menage to reproduce it wait testing bit more will add all info

**Comment by svijetlo** [comment]
ok got it 
if you use 
http://www.wow-mania.com/armory?item=3388
and you remove buff that it gives you or you die it will stop you form using other potions  for next 60 sec all tho cool-down on this one as it is counted as flask is only 3 sec

**Comment by wow-mania** [comment]
as-is then.
