### ISSUE TITLE
Rotface (Heroic) - Vile Gas

### ISSUE THREAD

**Issue by bLeyaa** [WoWManiaUK/Redemption#4302]
**Links:** https://youtu.be/JroyAvgk9Xw?t=101 ; https://youtu.be/pb9YPfn8R_s?t=39 (bottom left mage, bit less visible than the first video)
Also mentioned here: https://shyatwow.blogspot.com/2010/07/icc10-heroic-guide-festergut-rotface.html

**What is Happening:** When you are under the effect of Vile Gas, you are being disoriented and unable to cast spells & abilities.

**What Should happen:** It should cause damage, a root effect every other second, and cause you to do damage to others around you. It should NOT disorient you and you should be able to cast while affected by it. Disorient effect should come ONLY from vomit spell itself, not from the initial Vile Gas spell.

a ) If you are spread out (8+ yards between players) and get targeted by Vile Gas, you will vomit, but you will not get disoriented, because there is no one that vomits back on you.

b ) If you are not spread out (less than 8 yards between players) and get targeted by Vile Gas, you will vomit on person next to you and that person will vomit back on you, and those vomits WILL cause disorient effect on the initial target of Vile Gas.

Vomits should create a chain reaction if people are closer than 8 yards to each other. So, for example, if a single vomit gets chained to a single melee it will chain to all melees and cause a 100% wipe.

**_This only applies to Rotface and NOT to Festergut. Festergut's Vile Gas should remain as it is._**

**Comment by Rushor** [comment]
try now pls

**Comment by bLeyaa** [comment]
Works perfect now, checked with hunter and warlock classes.

**Comment by Rushor** [comment]
niice
