### ISSUE TITLE
[Quest] Help those that cannot help themselves

### ISSUE THREAD

**Issue by Natharius** [WoWManiaUK/Redemption#4303]
**Links:**

**What is Happening:**
In D.E.H.T.A. Encampment (Borean Tundra) there is a quest called "Help Those that cannot help themselfs", and the point of it is to free 8 Trapped Mammoth Calfs.
If you spam the quest item given by the quest giver near of one Trapped Mammoth Calf, you "free" more than the calf you have in front of you possibly completing the quest with one or two trapped Calf.

**What Should happen:**
With the item you should only be able the free one at a time and roam around to find the other trapped Calfs.
I am using the WOW Mania Launcher and I have my game up to date.

**Comment by bLeyaa** [comment]
Confirmed.
Was on my list of reports to add. :)

**Comment by Rushor** [comment]
itemscript/spellscript convert needed

**Comment by Rushor** [comment]
no longer spamm click possible

**Comment by bLeyaa** [comment]
All good now! :)
