### ISSUE TITLE
[NPC] Ymirjar Deathbringer (38125) - Icecrown Citadel

### ISSUE THREAD

**Issue by bLeyaa** [WoWManiaUK/Redemption#4304]
**Links:** [Ymirjar Deathbringer](https://www.wowhead.com/npc=38125/ymirjar-deathbringer) 

**What is Happening:** The mob currently uses only one ability of the ones it's supposed to have. Ymirjar Deathbringer upon being attacked will only cast Shadow Bolts and no other abilities.

**What Should happen:** In addition to Shadow Bolts, Ymirjar Deathbringer should also use [Summon Ymirjar](https://www.wowhead.com/spell=71303/summon-ymirjar), [Banish](https://www.wowhead.com/spell=71298/banish), [Death's Embrace](https://www.wowhead.com/spell=71299/deaths-embrace) and [Spirit Stream](https://www.wowhead.com/spell=69929/spirit-stream).

**Comment by tvshadowz** [comment]
I can confirm I have only seen these mob used shadow bolt and not use other spells listed.

**Comment by Keader** [comment]
Spirit Stream is only visual spell.
Added the rest.

**Comment by bLeyaa** [comment]
As you said, everything is fine except for the summon spell.
There is no cast on the summoning and when they appear there is only 1 which despawns right away.

**Comment by Keader** [comment]
@bLeyaa is a big problem if it stay with no cast?

**Comment by bLeyaa** [comment]
Not a big bother really, just mentioning what i see :P 
I'm just not sure if this is interruptable with silence/kick spells or stuns/grips/knock backs. 
Otherwise it's fine :D
