### ISSUE TITLE
Kinetic Bomb vs pets - Blood Prince Council

### ISSUE THREAD

**Issue by bLeyaa** [WoWManiaUK/Redemption#4305]
**Links:** [Kinetic Bomb](https://www.wowhead.com/spell=72053/kinetic-bomb)

**What is Happening:** Currently, if you leave your pet hitting the kinetic bomb it happens that the bomb still falls down. From what i understood talking to @Aristo14 is that this apparently happens when they're at BPC platform or if the Kinetic Bomb is about to expire (any location). As if the pet recognizes it as gone already and does not hit.

**What Should happen:** Pets should be able to hit the kinetic bombs for as long as they're spawned, without them being able to fall down and blast the raid away.

**Comment by jeyrella** [comment]
For evidence, https://youtu.be/nH0ao8VfTzM?t=114 (tankspots 2010 guide) clearly shows hunter doggy "tanking" the bomb on the right side

**Comment by shadownib** [comment]
Hi. Also the kinetic Bomb are supposed to hit the whole room , not only the the 30 ~ 40 yards area.

**Comment by Keader** [comment]
try now.

**Comment by tvshadowz** [comment]
Drops extremely close to the floor but hunter wolf can attack and prevent it from dropping. The warlock pet void walker cannot attack the kinetics even when theyre on the floor but the imps can attack.

**Comment by bLeyaa** [comment]
I just tried it on 25 normal difficulty, it happened three times. Once on the platform, once on the stairs of the platform and once on the bottom area (to the left side for what it matters). Pet was on autoattack with bite on autocast as well.

**Comment by Keader** [comment]
hmm, i tested with warlock pet.
i will take a look in hunter one.

**Comment by tvshadowz** [comment]
Yeah so its specific to the kinetic orbs spawning on a specific space

**Comment by bLeyaa** [comment]
Doubt it's the location as i've had it at different places... did a few more tests after my last comment. More likely to be the pet type or the attacking abilities.
For what it matters, i tried changing pets stance between Passive and Agressive and it worked the same way.

**Comment by Keader** [comment]
How?

https://youtu.be/B9RQwj2FRnA
Looks correct to me.
I tested with hunter pet and warlock

**Comment by bLeyaa** [comment]
I'll record it as soon as i get the chance, i dont think its 100% occurence. Maybe related to wolf specifically, i see u are using a boar.

P.S. nice music 😛

**Comment by bLeyaa** [comment]
@Keader 
Check this: https://youtu.be/tmWif3tOy5M

**Comment by bLeyaa** [comment]
@Keader 
Check this: https://youtu.be/jOrbIryBNAE

**Comment by Keader** [comment]
@bLeyaa it looks like some problem with wolfs hitbox.
and has other issue with this. Core check combat distance in 2d... and should be in 3d.
until combat distance is not fixed, i cant proper make all pets hit kinetic.
so we have a improvement here, but not 100% fix
