### ISSUE TITLE
Missing Gas clouds for engineers to extract elemental materials from.

### ISSUE THREAD

**Issue by Isabella-Mania** [WoWManiaUK/Redemption#4306]
First of this has already been addressed in 1 very specific case:
[Item?] gas clouds in wintergrasp Confirmed - Not Working
#1435 by havocisback was closed on 16 Aug 2017

However this is a general issues of missing gas clouds, according to the spawn points on wow-mania's armory spawn points:

The only one that matches the spawn points in the armory are the ones in Zangarmarsh - Outland.
All other places are missing some if not all gas clouds.
To take a particular case, the gas clouds in Netherstorm - Outland:
only 1 of 77 spawn spots is giving results.

**Links:**
https://www.wow-mania.com/armory/?npcs=13
https://www.wow-mania.com/armory/?npc=17408
https://www.wow-mania.com/armory/?item=23821

**What is Happening:**
Gas-clouds for use by engineers to extract elemental material for crafting professions in the game is not spawning/present/missing.

**What Should happen:**
Well the issue of the missing gas-clouds should be fixed.
I see 2 items of note that needs to be 'fixed':

1) Making sure that the missing gas-clouds become available for engineers to make use of as intended.

2) Fixing the armory spawn points to match a similar realistic map, such as Netherstorm's down from 77 spawn points to perhaps 7-14 spawn points and have that being reflected on the armory.

I hope I have done this properly and that some developers can fix the issue.

**Comment by Rushor** [comment]
No this is correct, the Spawn pool for Netherstorm - Arcane Vortex (17408) are pooled, which means that only one glas cloud out of 70 spawns is active at a time.

As soon as one despawns, an other other at a different place will spawn
