### ISSUE TITLE
[NPC/Spell] Salia (Cause Insanity)

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#4307]
**Links:**https://www.wowhead.com/npc=9860/salia#abilities
https://www.wowhead.com/quest=5242/deprecated-a-final-blow
https://www.wowhead.com/spell=12888/cause-insanity

**What is Happening:** [Salia](https://www.wowhead.com/npc=9860/salia), an enemy demon objective of the quest [[A Final Blow]
](https://www.wowhead.com/quest=5242/deprecated-a-final-blow) seems to prioritize casting her ability [Cause Insanity](https://www.wowhead.com/spell=12888/cause-insanity) every ~6 seconds regardless of how many players are engaged in combat with her. If a single player is fighting her, it causes all 3 mini-bosses to get out of combat and reset completely. This makes the quest and encounter much more frustrating and nearly impossible to do. (The only way is to burst Salia before she gets to cast her mind control even once, after which you can kill the other 2 mobs normally).

**What Should happen:** Salia should not cast her mind control ability, [Cause Insanity](https://www.wowhead.com/spell=12888/cause-insanity), if she is engaged in combat by a single player.

Edit: [Jadefire Tricksters](https://www.wowhead.com/npc=7107/jadefire-trickster) in the same area also cast the same spell with the same issue. Probably exact same spellID.

**Comment by Rushor** [comment]
they will now cast it on TARGET_HOSTILE_RANDOM_NOT_TOP
