### ISSUE TITLE
[Instance] The Nexus

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#4308]
**Links:** https://www.wowhead.com/the-nexus

**What is Happening:** While doing The Nexus instance on normal mode through rdf, the game will never save any sort of lockout or ID for the party. If the group wipes or leaves the instance all at the same time (frequent for people who tp out and in after the golem boss), the entire instance will simply reset. 

**What Should happen:** Even though normal dungeons don't have daily lock IDs, this instance should still have a temporary 'savestate' for a party as long as it doesn't disband or willingly clicks 'reset all instances'.

**Comment by Keader** [comment]
Is working without group and without DF.
I cant find any reason to not work in DF.
i cant build the code in debug mode to try find where it's falling
