### ISSUE TITLE
[Quest] Flight of the Wintergarde Defender

### ISSUE THREAD

**Issue by squalllh1989** [WoWManiaUK/Redemption#4309]
**Links:**  ["Flight of the Wintergarde Defender".]( http://www.wow-mania.com/armory/?quest=12237)

**What is Happening:**
currently no Helpless Wintergarde Villager arround for you to rescure, so this quest is undoable.

**What Should happen:**
in this quest there should be [Helpless Wintergarde Villager](http://www.wow-mania.com/armory/?npc=27315), so you can gap them on your gryphin and complete the quest like how it is done (sample video of how it should work [here](https://www.youtube.com/watch?v=lF_OCW9WIHA)).

note that i already report this quest before here: https://github.com/WoWManiaUK/Redemption/issues/2455

**Comment by Rushor** [comment]
they should always respawn now (active flag missing)

**Comment by jeyrella** [comment]
hmm.  odd.  this was definitely regression since this has worked in the past. will test it :)

**Comment by jeyrella** [comment]
respawning confirmed
![image](https://user-images.githubusercontent.com/46089380/77758924-bd4bfd80-702b-11ea-8c12-cb4a8e93b82b.png)
