### ISSUE TITLE
[Spell/Glyph] Glyph of Seal of Vengeance losing bonus on relog.

### ISSUE THREAD

**Issue by Sharuzan** [WoWManiaUK/Redemption#4310]
Links. 
Not sure what links to provide.
No links on WoWhead

What is happening: 
When you have the Glyph of Seal of Vengeance, use Seal of Vengeance, enter a dungeon, anr relog, you lose the expertise bonus provided by the glyph. The seal will still be active but without the added expertise. Only way to get it back, is reapplying the seal.

What should happen: 
Bonus should be active regardless, as long as Seal of Vengeance is active.

**Comment by jeyrella** [comment]
Glyph: https://www.wow-mania.com/armory/?item=43869
Spell:  https://www.wow-mania.com/armory/?spell=31801

**Comment by svijetlo** [comment]
could this be related to recent fox of glyph for seal of corruption

**Comment by Keader** [comment]
Not related.

**Comment by Keader** [comment]
Try now
