### ISSUE TITLE
[Event] Dalaran Visitor - update with custom mounts

### ISSUE THREAD

**Issue by WhitephoenixTheBunny** [WoWManiaUK/Redemption#4312]
Mania Custom Mounts

(Some ingame mount might be duplicated)

Alliance and Horde:

Item ID
--
68825
150579
150578
142223
142222
142221
45725
32458
150082
142225
50250
54069
143490
32319
150090
43516
54811
33999
118515
150085
150566
150560
46708
142230
142229
142231
150088
150084
150565
150086
150087
69213
46171
142224
142219
142218
143502
32314
150091
143503
143503
78924
143637
143505
50818
142234
142232
142235
83088
82453
152901
150561
150093
150080
147901
150562
143491
143491
34092
143492
45693
143638
150567
32316
143488
143487
143489
32317
150089
143643
44178
87777
43952
32858
43986
44164
51954
43953
44151
43951
32859
161665
109012
87769
89154
63125
62901
63040
63041
63039
156879
109013
150552
44707
87776
87773
87774
87775
87771
51955
45801
79802
161479
87768
32857
49636
63042
44175
32860
43955
44160
147835
45802
163063
89304
44168
43954
32861
32862
44177
63043
62900
47840
83087
83090
150580
150581
150582
150583
142233
159842
32318
229417
150092
116771
163586
104011
83089
30609
92724
37012
142228
142226
142227
150081
37676
65891
150564
150083
69846
40775
50435
35226
54860
153594
158100
158101
158102
158103
158104
158105
158106
158107
158108
158123
158124

Alliance:

Item ID
--
44689
44843
76889
150568

Horde:

Item ID
--
44690
44842
76902
46814

**Comment by Rushor** [comment]
all mounts added 

https://i.imgur.com/4su1I2E.jpg https://i.imgur.com/td0C7mk.jpg  https://i.imgur.com/eCkqa8p.jpg  https://i.imgur.com/niOCl2N.jpg

const uint32 FlyingMountHorde[] =
{   // Both
    17890, 20344, 21152, 21155, 21158, 21157, 21156, 21520, 21521, 21522, 21523, 21524, 21525, 22473, 22620, 23647, 25958, 24725, 28108, 27507, 27785, 25832, 25835, 27796, 25833, 25831, 28044, 28040, 28041, 28045, 28042, 28043, 25836, 28053, 28890, 22471, 28953, 28954, 25511, 25593, 29794, 30346, 30989, 31047, 31007, 31154, 31156, 31803, 31958, 31992, 35551, 35757, 35740, 35755, 35754, 35553, 35751, 37145, 35750, 37800, 38018, 38260, 40029, 40590, 42185, 42499, 42500, 42501, 42502, 41990, 41592, 43689, 43692, 43693, 43695, 43697, 46087, 44633, 43686, 46729, 48714, 53774, 55005, 70232, 70211, 70210, 70209, 70207, 70201, 70206, 70205, 70204, 70203, 70202, 70194, 70193, 70196, 70129, 70005, 90080, 90081, 90082, 90084, 90085, 90110, 90108, 90089, 90088, 90076, 90075, 90074, 90073, 70238, 70231, 70233, 90111, 90123, 90122, 90121, 90126, 90143, 90144, 90145, 62019, 29361, 90000, 90001, 90002, 90025, 90026, 90027, 90007, 90006, 90008, 90009, 90005, 90020, 90021, 90022, 90004, 90010, 90011, 90015, 90028, 90029, 90030, 90017, 90016, 90018, 90014, 90013, 90023, 90024, 
    // Specific
	27914, 28402, 29696, 39547
};

const uint32 FlyingMountAlliance[] =
{   // Both
    17890, 20344, 21152, 21155, 21158, 21157, 21156, 21520, 21521, 21522, 21523, 21524, 21525, 22473, 22620, 23647, 25958, 24725, 28108, 27507, 27785, 25832, 25835, 27796, 25833, 25831, 28044, 28040, 28041, 28045, 28042, 28043, 25836, 28053, 28890, 22471, 28953, 28954, 25511, 25593, 29794, 30346, 30989, 31047, 31007, 31154, 31156, 31803, 31958, 31992, 35551, 35757, 35740, 35755, 35754, 35553, 35751, 37145, 35750, 37800, 38018, 38260, 40029, 40590, 42185, 42499, 42500, 42501, 42502, 41990, 41592, 43689, 43692, 43693, 43695, 43697, 46087, 44633, 43686, 46729, 48714, 53774, 55005, 70232, 70211, 70210, 70209, 70207, 70201, 70206, 70205, 70204, 70203, 70202, 70194, 70193, 70196, 70129, 70005, 90080, 90081, 90082, 90084, 90085, 90110, 90108, 90089, 90088, 90076, 90075, 90074, 90073, 70238, 70231, 70233, 90111, 90123, 90122, 90121, 90126, 90143, 90144, 90145, 62019, 29361, 90000, 90001, 90002, 90025, 90026, 90027, 90007, 90006, 90008, 90009, 90005, 90020, 90021, 90022, 90004, 90010, 90011, 90015, 90028, 90029, 90030, 90017, 90016, 90018, 90014, 90013, 90023, 90024, 
    // Specific
    27525, 27913, 39546, 90109
};

**Comment by jeyrella** [comment]
note that 143503 was duplicated in the list....

**Comment by Rushor** [comment]
yeah does not matter that much - it will always pick a random one :>

**Comment by Rushor** [comment]
All done

**Comment by WhitephoenixTheBunny** [comment]
@Rushor I stood there for a long time... only saw the 4 ~5 mounts being in use, maybe bad luck? :P

**Comment by Rushor** [comment]
yes, i always a total random game which will be shown :D
