### ISSUE TITLE
[Pet] Boneshard

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#4313]
**Links:** https://www.wow-mania.com/armory/?item=170008
https://www.wow-mania.com/armory/?spell=160008
![WoWScrnShot_032720_163115](https://user-images.githubusercontent.com/34783736/77798369-19714a80-7049-11ea-9a70-77f9a71e1f46.jpg)
![WoWScrnShot_032720_163115](https://user-images.githubusercontent.com/34783736/77799000-440fd300-704a-11ea-85fe-d14cb0f59069.jpg)

**What is Happening:** The new [Boneshard](https://www.wow-mania.com/armory/?spell=160008) pet added in 2.6.0 has a gigantic visual surrounding it that covers the floor in a blue polka dot pattern that spins and moves with the pet.

**What Should happen:** The pet's visuals should not include such a polka dot pattern. Maybe we could limit its size horizontally so as to limit the spread of too many dots at least?

**Comment by Rushor** [comment]
Sadly this is not possible - else the whole pet will be too tiny. and client update would be required, which will not happen that anytime soon
