### ISSUE TITLE
[NPC] Pathfinding through objects

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#4314]
**Links:** Sort of related to #4256 

**What is Happening:** Enemy NPCs will walk through walls, fences, bridges and even the ground. (and more)

**What Should happen:** Mobs should never ignore collisions while pathfinding to their target.

**Comment by wow-mania** [comment]
This is a core issue. Most likely cannot be fixed. I

**Comment by svijetlo** [comment]
we should then just mark as-is and move on not to clutter posts
