### ISSUE TITLE
[NPC] Marsh Lurker not attackable - Zangarmarsh 18136

### ISSUE THREAD

**Issue by jeyrella** [WoWManiaUK/Redemption#4315]
**Links:**
https://www.wow-mania.com/armory/?npc=18136
(For quest https://www.wow-mania.com/armory/?quest=10096)

**What is Happening:**
The [Marsh Lurker](https://www.wow-mania.com/armory/?npc=18136) at 74.0, 94.5 (the 1st split inside the Zangarmarsh southern cave) is targetable but not attackable. Error message "You are too far away".

This has significance as during quest https://www.wow-mania.com/armory/?quest=10096 there are limited numbers of this NPC to kill.

![image](https://user-images.githubusercontent.com/46089380/77822034-f301ec80-70e6-11ea-8926-0844e6086232.png)

**What Should happen:**
Should be killable.

**Comment by Rushor** [comment]
Will fix

**Comment by Rushor** [comment]
position changed. should be attackable now

**Comment by jeyrella** [comment]
looks good to me :)
![image](https://user-images.githubusercontent.com/46089380/77861097-e5458780-720a-11ea-863d-11855b346c54.png)
