### ISSUE TITLE
Local zone : testing!

### ISSUE THREAD

**Issue by mrjokertgtv** [WoWManiaUK/Redemption#4319]
Hello,
I was browsing in the Testing zone when the game suddenly crashed!
Now every time I log in with my character It crashes instantly and I can't even leave that zone or do anything with my character!

All i'm asking is if  you can just get my character "Saiidos" out of that zone so I can keep playing the game!

Here's the crash's details : 
[2020-03-28 23.28.12 Crash.txt](https://github.com/WoWManiaUK/Redemption/files/4398005/2020-03-28.23.28.12.Crash.txt)

**Comment by Blyatman1** [comment]
You crashed because you're not using the client nor patches provided by WoW-Mania.

Since you are using an enUS client, I'd suggest downloading the full client, or you can try to find a 3.3.5a enGB client and just download the patches and launcher.

https://wow-mania.com/downloads

**Comment by mrjokertgtv** [comment]
I'm back to the game after a long and Indeed it's not the same client provided by WoW-Mania,
Never thought it would be a big issue, thank you!
