### ISSUE TITLE
[Boss/Item] Lady Vashj (Tainted Core)

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#4320]
**Links:** https://wow.gamepedia.com/Tainted_Core_(item)
https://wowwiki.fandom.com/wiki/Tainted_Core
https://www.wowhead.com/item=31088/tainted-core

**What is Happening:** The [Tainted Cores](https://www.wowhead.com/item=31088/tainted-core) looted during the Lady Vashj encounter do not root the player in place.

**What Should happen:** The Tainted Cores are supposed to root the person holding them, and they should have to pass them from one player to another volleyball-style to reach the bindings and use the item to weaken the boss' shields. 

P.S. The rooting aspect was removed, but only in patch 4.2.0, and should therefore still be present in Redemption.

**Comment by Keader** [comment]
well...
we dont have any sniffs of this root.
So i cant find what is the spell exactly...
If you have any idea.
Looks a lost information to me, since we cant sniff in current retail (because was removed in 4.2)

**Comment by Keader** [comment]
If you know what is the root spell, let me know.
I know how fix it, but i need root spell.
And since we dont have sniffs of it, and i cant find the spell in web, this issue will be put on hold.

**Comment by Keader** [comment]
Thanks to Kitzunu to found the correct spell.
test in dev now.

**Comment by Aristo14** [comment]
lacking confirmation, please confirm.

**Comment by svijetlo** [comment]
looting http://www.wow-mania.com/armory?item=31088 will root you in place , throwing it out of bag or to other player allows you to move again , works perfect
