### ISSUE TITLE
[Core/Spells] Charm vs Fear

### ISSUE THREAD

**Issue by Keader** [WoWManiaUK/Redemption#4321]
Fixed a bug that make charmed players, ignore fear, when charm expire.
Similar #4293, happens with fear.
Fixing both cases for all bosses, not only for lady.

**Comment by Keader** [comment]
bLeyaa found a issue, i'm looking

**Comment by bLeyaa** [comment]
Now it's fine. :D

**Comment by Keader** [comment]
GG, Ty 👍
