### ISSUE TITLE
[SPELL] WARRIOR, PETS CHARGES

### ISSUE THREAD

**Issue by Clickclackz** [WoWManiaUK/Redemption#4324]
**Links:* 
I dont know what to link here. Its ridicoulous.

**What is Happening:**
HI, Sometimes in arena (overall in dalaran arena) when a warrior or pet (hunter) charges in stairs inmediately warrior or pet dissapear during some time, and then reappears in the mid of arena. When a player get feared it happen the same (sometimes).

**What Should happen:**
Nobody would disappear

**Comment by jeyrella** [comment]
may be related to/better explained in https://github.com/WoWManiaUK/Redemption/issues/4326
