### ISSUE TITLE
[Pet] Pet attack issue in PvP

### ISSUE THREAD

**Issue by Clickclackz** [WoWManiaUK/Redemption#4325]
**Links:**

**What is Happening:**
Sometimes (in arena i saw it), pet doesnt attack if you send it. For exapmple i have it in passive, if someone goes behind pillar to drink, i send pet to not let him and pet doesnt respond. Pets dissapear in BG too i lost my pet definetely in a WSG bg (if i can put it in here for test it).

**What Should happen:**
Pet should attack allways when you send it, and pet shouldnt dissapear forever from your pet stabled.

**Comment by wow-mania** [comment]
no evidence or reproducible steps

**Comment by GMMetaxa** [comment]
Target should be in sight of the pet I assume. Not behind a pillar.
The lost pet should be checked imo.

**Comment by jeyrella** [comment]
May be related to https://github.com/WoWManiaUK/Redemption/issues/4267 ?

**Comment by bLeyaa** [comment]
> Target should be in sight of the pet I assume. Not behind a pillar.

Pet should actually find a path to the target. 
Say for example your enemy went behind a pillar in arena to eat, you should be able to send a pet to get him in combat/interrupt it. However this cannot currently be done. I suspect this started happening after #4221

**Comment by Keader** [comment]
try now.
I allowed pets attack targets that is not in line of sight in bgs and arenas

**Comment by bLeyaa** [comment]
As good as it can be. :)
