### ISSUE TITLE
[PvP] Fear in Dalaran Arena - platform box

### ISSUE THREAD

**Issue by Clickclackz** [WoWManiaUK/Redemption#4326]
**Links:**

**What is Happening:**
In dalaran arena if you are in a box and you get feared, fear can you send you down.

**What Should happen:**
In fear you NEVER should be droped down from box if you dont get pushed by some other spell.

**Comment by svijetlo** [comment]
yes this is true, fear like effect should never take you off platform you just wonder to edge of it, unless some other push, death grip like spell push you down

**Comment by bLeyaa** [comment]
What Svijet said.

Fear/Blind/Polymorph/Death Coil should not get the player off the box if affected by either of the spells.

As mentioned by Svijet, just to highlight, this **_does not_** apply to Typhoon and Thunderstorm.

**Comment by Keader** [comment]
Fear/Desorient mechanic uses some special motion code, that can cause a lot of issues.
I dont think that it's worth the risk @wow-mania
