### ISSUE TITLE
I trying to update the launcher so i can open the game using it but, i won't let me do it, it gives me this error. 

### ISSUE THREAD

**Issue by Shablezx** [WoWManiaUK/Redemption#4327]
**Links:**

**What is Happening:**
[](url)

**What Should happen:**

**Comment by Shablezx** [comment]
![Annotation 2020-03-29 154859](https://user-images.githubusercontent.com/62855571/77860453-01c6cd00-71d5-11ea-86fa-0e42cbc7e81e.png)

**Comment by wow-mania** [comment]
not an server issue. if you have an issue please contact support.
