### ISSUE TITLE
[Achievement] Upper Back Pain (10/25)

### ISSUE THREAD

**Issue by bLeyaa** [WoWManiaUK/Redemption#4329]
**Links:** https://www.wowhead.com/achievement=3813/upper-back-pain-25-player

**What is Happening:** Players will receive the achievement regardless of how many [Snobolds ](https://www.wowhead.com/npc=34800/snobold-vassal)remain alive.

**What Should happen:** The achievement should only be obtained if the appropriate number(difficulty dependent) of Snobolds is alive after killing Icehowl.

**Comment by jeyrella** [comment]
If no Snobolds are alive, player does not get achievement.

**Comment by bLeyaa** [comment]
10m: https://youtu.be/FCoX_u1mJKY
25m: https://youtu.be/KMzPd6ZNDbY (shown from Gormok)

**Comment by svijetlo** [comment]
got ach while only one of them was alive

**Comment by Keader** [comment]
try now
