### ISSUE TITLE
[Raid] Divine Storm in RS not hitting Halion

### ISSUE THREAD

**Issue by Stormender** [WoWManiaUK/Redemption#4330]
**Links:**

Inside of Rs on Halion only the Divine storm doesn't hit halion unless ur inside her hit box ...as in 8yds from the middle of her...not 8yds from her hit box..thats only on the outside....once u go inside its alittle better but its still not 8yds from the hitbox

**What Should happen:**…..as far as I know it should be 8yds from the outside of her hitbox not 8yds from the middle of the inside of her 

This is my first GitHub post if u guys need more info please let me know

**Comment by wow-mania** [comment]
As-is

**Comment by bluemonstrr** [comment]
@Stormender just move in a little bit and move out for meteor. It's working alright as of right now, just need good positioning.

**Comment by Stormender** [comment]
Ye if ur skilled enough u have to be inside her hit box and run out easy
for most..but say adds r up...it wont hit her while ur at max melee with
the rest of the melee sadly....was noticing lastnight when solo tanking
fester if ur max melee to be away from the big ooze...like everyone
else...ds also doesnt hit then
