### ISSUE TITLE
NPC bugged out for questing

### ISSUE THREAD

**Issue by CpScotch** [WoWManiaUK/Redemption#4331]
**Links:**
NPC
https://www.wowhead.com/npc=30631/darkrider-arly
Quests
https://www.wowhead.com/quest=13120/deaths-gaze
https://www.wowhead.com/quest=13119/destroying-the-altars

additional drop quest
https://www.wowhead.com/quest=13136/jagged-shards

**What is Happening:**
The NPC in question is Darkrider Arly stationed in IC at blackwatch for the quests related to the fleshworks.

i was busy turning in the quests "deaths-gaze" and "destroying-the-altars" when i turned in "destroying-the-altars" the NPC became unresponsive and would not let me turn in the second quest. I abandoned the  "deaths-gaze" quest in the hopes of reacquiring it from the npc but she refused to give me any new quests. i eventually got a GM to complete the quest for me and i could carry on with the quest chain once those tow quest where completed.

it should be noted that there is a third quest that starts from a drop item from the gouls of the fleshworks. i do not know how this quest interacts with the chain. That quest is "jagged shards"

**What Should happen:**
The NPC should accept both quests and carry on with the chain.

**Comment by wow-mania** [comment]
Pretty sure it works.
