### ISSUE TITLE
[NPC] Attumen the Huntsmen broke

### ISSUE THREAD

**Issue by Klickslave** [WoWManiaUK/Redemption#4332]
**Links:**
https://de.wowhead.com/npc=16152/attumen-der-j%C3%A4ger

**What is Happening:**
We (2 Players) were engaging Attumen. After killing the Horse , Attumen despawned out of Battle and no Lootable Object was there. The "Body" of the Horse was not lootable. 

**What Should happen:**
After killing the Horse Attumen continues the fight until we slay him. After that he drops several Stuff which is lootable.

The Case occured at about 9:37 p.m. CEST.
The Character Names taking part were "Longjohn" and "Hellford".
The ID of the Instance was 655.

**Comment by Rushor** [comment]
Try to reproduce this people pls

**Comment by Klickslave** [comment]
We will but we have to wait for ID Reset about 5-6 Days i guess. Will keep this updated !

**Comment by wow-mania** [comment]
pretty sure it works

**Comment by Blyatman1** [comment]
Can confirm as I had this happen to me yesterday in a group of 4, for the first time in over a month.

https://github.com/WoWManiaUK/Redemption/issues/4100

**Comment by Oganku** [comment]
That happens if you nuke him too fast. He skips going into phase 2 and nothing drops. The latest fix helped a lot to prevent that, but it can still happen if you aren't careful. Either make the transition more lenient or just leave as is and be more careful. Up to you.
Related: #4100

**Comment by svijetlo** [comment]
let horse attack you for a bit if you burst to fast it is gone 
i will try reproduce it tomorrow and record it

**Comment by GMMetaxa** [comment]
At 25% he jumps on his horse. If you kill him before that moment, you get no loot. This is how it SHOUL work and works.

**Comment by Rushor** [comment]
thanks for the tests :)
