### ISSUE TITLE
[Quest] Two Wrongs - Howling Fjord

### ISSUE THREAD

**Issue by CpScotch** [WoWManiaUK/Redemption#4333]
**Links:**
https://www.wowhead.com/quest=11188/two-wrongs

**What is Happening:**
The quests asks you to kill 3 proto drakes. the item given is used to start combat and lure the drakes down for meal combat.
i found that the item taunts the drakes effectively but the drakes do not remain in combat long enough for you to kill them on the ground. they fly down for a hit of two and then they fly back up.

this is a low priority fix as you can still kill the drakes by flying to the nearby roof but i thought i would mention it. without access to a flying mount i do not see how you would be able to complete this quest.
i did find one drake which spawned on the ground but he did not re-spawned as far as i could tell
**What Should happen:**
The drakes should remain in meal range till thy die

**Comment by Rushor** [comment]
Will fix that by increasing the combat distancd

**Comment by wow-mania** [comment]
Quest works. We don't "fix" to make things easier.

**Comment by jeyrella** [comment]
Quest does not work if player does not have Northrend flying, which first time toons are not likely to have yet due to the gold cost

**Comment by Rushor** [comment]
should no longer reset while in combat.
