### ISSUE TITLE
[NPC] Vendor Madame Ruby in Shattrath City has missing items

### ISSUE THREAD

**Issue by yani** [WoWManiaUK/Redemption#4334]
Current items:
![image](https://user-images.githubusercontent.com/6956790/77966089-ac78e180-72e2-11ea-892e-c09d1bf78f2b.png)

Correct items:
https://www.wowhead.com/npc=19663/madame-ruby

I was specifically looking for [Formula: Enchant Shield - Major Stamina](https://www.wowhead.com/item=28282/formula-enchant-shield-major-stamina) and [Formula: Superior Wizard Oil](https://www.wowhead.com/item=22563/formula-superior-wizard-oil).

**Comment by Oganku** [comment]
Those are limited stock items. Once the vendor has been depleted, it takes a little timr before they come back. Some people camp them to try to sell them higher to auction.
That's probably what you seen there.

**Comment by yani** [comment]
Weird that it doesn't show the item being out of stock then, if that's a thing. 
Probably "It's a feature not a bug", lol.

**Comment by yani** [comment]
Ah yes, now I see. The grayed out items are gone now that I open the shop again.
