### ISSUE TITLE
Bladestorm bug 

### ISSUE THREAD

**Issue by Wylliam94** [WoWManiaUK/Redemption#4335]
**Links:**
![Bladestorm bug](https://user-images.githubusercontent.com/62913298/77968227-1abfa300-72e7-11ea-8e17-b1ddff480dcd.jpg)

**What is Happening:**

Warrior lvl 42, have not and cannot skill Bladestorm yet
The Bug started occuring right after the server crash on evening of the 30th of march.
My Warrior randomly uses Bladestorm whenever I use an attack. In this case "heroic strike".
I cannot move during the attack and its only occasionally interruptable by using another attack not consistently. 
I use the 2.6 launcher as admin. 
I had cleared my cache. 
I had all addons disabled.
My char was "cleared"(dunno what that means) by a GM (very friendly).
Sometimes the intervalls of the bug occuring were as large as 10 min and othertimes a few seconds.
The bug was observable by my group mates when I pulled them through stockades.
I THINK the bug was occuring for another warrior (40-ish) as we were doing Uldaman. I heared the sound it makes while not spinning myself.
That guys name was Lu or La or Le and he appeared to be a bit of a troll.
Only been on the server for a couple of days but I like it very much!
Thank you for your time and I hope it helps :)
**What Should happen:**

Not that lul

**Comment by Oganku** [comment]
Are you currently using [Ravager](https://classic.wowhead.com/item=7717/ravager)  from scarlet monastery armory?
The weapon's proc is exactly what you described and is not a bug.

**Comment by bLeyaa** [comment]
Edited OP to remove the account name for privacy reasons.

OT: This is hardly to be as described, most likely what Oganku suggested to be happening.

**Comment by bLeyaa** [comment]
Alright, just had it confirmed by Divigrac. He is indeed using Ravager weapon.

Closed.
