### ISSUE TITLE
[Spell] "Gift of the Wild" got overide by "Arcane Brilliance"

### ISSUE THREAD

**Issue by squalllh1989** [WoWManiaUK/Redemption#4336]
**What is Happening:** [Gift of the wild](https://www.wow-mania.com/armory/?spell=48470) can't be used when [Arcane Brilliance](https://www.wow-mania.com/armory/?spell=27127) is up, if [Arcane Brilliance](https://www.wow-mania.com/armory/?spell=27127) is up, it will overide[Gift of the wild](https://www.wow-mania.com/armory/?spell=48470)

**What Should happen:** the two buff should be stack normally

**Comment by squalllh1989** [comment]
This problem doesn't happen to ["Dalaran Brilliance"](https://www.wow-mania.com/armory/?spell=61316), it stack properly with Gift of the wild

**Comment by svijetlo** [comment]
![image](https://user-images.githubusercontent.com/61908373/78113696-64e87780-7400-11ea-80fa-cc8d17c176ec.png)

**Comment by bLeyaa** [comment]
The regular 30 minute intellect buff also stacks with the Gift of the Wild. It's only the 60 minute that causes this.

**Comment by Keader** [comment]
Will fix in some minutes

**Comment by tvshadowz** [comment]
Yeah arcane brilliance overrides the single and multi gift of the wild however the arcane intellect buff does not override either.

**Comment by Keader** [comment]
fixed
