### ISSUE TITLE
[PvP] PvP flags auto-turned on in Free For All areas

### ISSUE THREAD

**Issue by jeyrella** [WoWManiaUK/Redemption#4337]
**Links:**
https://wowwiki.fandom.com/wiki/Bluewall

**What is Happening:**
Currently, "free for all" areas such as Southern Barrens and Zangarmarsh automatically turn on player's PvP flags.  This is incorrect behaviour and not the meaning of Free For All areas.  FFA areas were regions in which players can choose to fight **anyone of any faction**, not a "danger zone".
It is of course difficult to find documentation sources for something that didn't exist, however see the phenomenon of "bluewalling" for the reverse inference.  https://wowwiki.fandom.com/wiki/Bluewall   If players were automatically flagged, then bluewalling as a phenomenon would not have existed.  

Note on that page also, the phrase: 
> On a PVE server, if you are for any reason flagged, that means you are subjecting yourself to PVP, period..... That means you have to be really careful when **deciding whether to flag or not**

i.e. that on PvE realm player has the choice at all times to flag or not.

On a PvE realm, incoming new players would not be expecting to be suddenly PvPd while questing in what is otherwise a PvE zone, and there is no warning or region markers that this the case. It often manifests as complaints/surprise in discord and world channel.

**What Should happen:**
In FFA areas, players should be able to **choose** to turn on their PvP flags and be able to fight players of any faction, without having the PvP flag automatically turned on.

**Comment by jeyrella** [comment]
Note this does not apply to Wintergrasp, which is NOT a FFA zone - it is PvP zone and was designated from the start as an entire zone of PvP play.  PvP flag should be auto-turned on correctly in this area.

**Comment by wow-mania** [comment]
as-is that is the whole point.

**Comment by jeyrella** [comment]
As discussed, agreed to remove non-blizzlike FFA areas.

**Comment by Echinaceax** [comment]
THE_HINTERLANDS,
DESOLACE,
SOUTHERN_BARRENS,
ZANGARMARSH,
ZUL_DRAK,
EMERALD_FOREST,

ported to all listed above, zones dont show pvp flagged anymore
