### ISSUE TITLE
[Achievement] Earth Wind and fire

### ISSUE THREAD

**Issue by Stormender** [WoWManiaUK/Redemption#4338]
We did VoA 10m achiv Earth wind and fire...killed them all within 37second of the first one dying and we didn't get the achive 

**What Should happen:**
Defeat Archavon the Stone Watcher, Emalon the Storm Watcher, and Koralon the Flame Watcher withing 60 seconds of each other in 10-player mode

**Comment by tvshadowz** [comment]
https://www.wow-mania.com/armory/?achievement=4017

**Comment by Keader** [comment]
try now

**Comment by Stormender** [comment]
Will do reset should of just happened ❤

**Comment by Keader** [comment]
I mean, in ptr xD
Will be on Live after next update

**Comment by Stormender** [comment]
Ooooh gotta
