### ISSUE TITLE
 [The Keepers of Ulduar (25 player)]Achiv

### ISSUE THREAD

**Issue by Stormender** [WoWManiaUK/Redemption#4339]
[The Keepers of Ulduar (25 player)]  where your ment to Kill Hodir, THorim, Freya, Mimiron, three of the bosses counted towards the achiv accept for Hodir didn't count after killing him 

**What Should happen:**….. [The Keepers of Ulduar (25 player)] Kill Hodir, THorim, Freya, Mimiron,

**Comment by wow-mania** [comment]
Pretty sure it works.

**Comment by Stormender** [comment]
We are trying again after reset and I'll make sure we get a video

**Comment by bluemonstrr** [comment]
@Stormender I just tested it on two characters without the progress on the achieve, I got it on both. Try next lockout and let me know what happens.

**Comment by Stormender** [comment]
Forsure thax..ye none of us in that 25m got it..had a few people die idk if
that has something to do with it
