### ISSUE TITLE
Training Dummies dodge and parry

### ISSUE THREAD

**Issue by Greywolf59** [WoWManiaUK/Redemption#4341]
**Links:**
Heroic Training Dummy https://www.wow-mania.com/armory/?npc=31146

**What is Happening:**
I do not know that for sure as I never played retail, but I think it might be worthy of the post. HEroic Training Dummy does not have enabled parry and dodge chance. With 11 expertise I did not get a single parry nor dodge from this dummy. I do suspect the other versions of dummies might have the same issue, however I have not tested that, after all Boss level dummy is the one important usually (and the easiest to test this).

**What Should happen:**
I guess it should dodge and parry. If they should not dodge and parry, you have my sincere apologies for useless post.

**Comment by bLeyaa** [comment]
![image](https://user-images.githubusercontent.com/61625377/78132558-3927ba80-741d-11ea-901f-51647541f10d.png)


https://www.wowhead.com/npc=31146/raiders-training-dummy
> By PrettyKitty (3,327 – 1·4·18) on 2008/12/24 (Patch 3.0.3)
> The odd thing is that these things can dodge, parry, and miss.
> I mean they are just sitting non-living dummies how could this be :P
>Last edited by PrettyKitty on 2008/12/24 (Patch 3.0.3)

**Comment by Keader** [comment]
Fixed.
I will keep the wow-mania heroic dummy still doing not parry/dodge, since they are custom npcs btw
