### ISSUE TITLE
Calendar bug is back

### ISSUE THREAD

**Issue by Greywolf59** [WoWManiaUK/Redemption#4342]
Hello dear GMs and developers!

**What is Happening:**
So, as we have a new time shift, the calendar bug strikes again! As with last time shift some characters are subject to this bug.  Simply, if you open the calendar on the affected toon your game freezes and crashes, on weaker laptops (as mine) whole laptop freezes and you have to restart whole laptop. This bug is not account wide. My druid has it, my warrior does not. Same with some other players. Most of theirs toons are okay but some of them do have this issue.

**What Should happen:**
Opening calendar should not be a a bane of your game or laptop.

**Comment by yani** [comment]
Is it possible you signed up for raids with the affected toons?

**Comment by Greywolf59** [comment]
Of course I did sign for raids, on all my toons. And that is why I open calendar - to sign up for more, which now I can't on my druid. I will try again now when time switched again.

**Comment by jeyrella** [comment]
@Greywolf59 If this is still a problem, please can you find a crash log in the "Errors" folder inside your WoW folder, and attach it here, or contact a Tester on Discord.

**Comment by Greywolf59** [comment]
Hi. I tried an hour back. It still is an issue on my toon Geshoia. Problem is I cannot post an Error/crash log since there is none. My game does not crashes per se with error notifications. If I should describe in detail:
Once I open the calendar the video/graphics freezes completely. I am not sure now but I believe that music/ambience continues normally. Even if I wait fro a long time the game does not unfreezes. I can't even go to Task Manager or anything, my whole laptop freezes and I have to hard restart it.

**Comment by Greywolf59** [comment]
Hello again. This happened also on my DK Parset. I am not sure if I made my DK on unofficial mania launcher but I sure did so with my feral druid Geshoia. It seems the bug affects the toons I made on launcher from different server, launcher without custom changes, in times when I started to play here, oblivous of the real need of mania launcher.

**Comment by Greywolf59** [comment]
Okay so I reffered with some other players who have the same bug and they said they made toons on official mania client so the issues does not lay in toon being created on different client.

**Comment by yani** [comment]
@Greywolf59 have you created or signed up for any events?

**Comment by Greywolf59** [comment]
I did not create any event last few months. I signed up for guild events regulary on my toons before the bug. on Geshoia I signed and he is bugged. On Lykfar I signed and he is not bugged. On my DK Parset I am not even in any guild, my calendar is event-empty and still if I open it I crash.
