### ISSUE TITLE
Unable to get the poisons skill for Rogue class

### ISSUE THREAD

**Issue by AresRex** [WoWManiaUK/Redemption#4343]
**Links:**
https://classic.wowhead.com/quest=2480/hinotts-assistance#comments

**What is Happening:**
I am playing a rogue with my account AresRex and I just finished the quest "Hinott's Assistance" but there is nothing else happening. I checked with the Rogue trainer in Orgrimar but these poisons are nowhere to be found.

**What Should happen:**
I checked online and I should be having a new icon for making poisons. Can you please help out?

**Comment by svijetlo** [comment]
making poisons as rogue was vanilla wow thing in later expansions spicily wotlk you just buy poisons form vendor , if you think about that poisons skill

**Comment by AresRex** [comment]
Thanks a lot, Svijetlo. Sorry for not being aware of this beforehand, will check in a better way next time.

Hope you have a great day!
