### ISSUE TITLE
Mall Dalaran portal

### ISSUE THREAD

**Issue by Blackhelm36** [WoWManiaUK/Redemption#4344]
**Links:**

**What is Happening:**Alliance has the new Dalaran portal in the mall but horde does not

**What Should happen:**

**Comment by Rushor** [comment]
can you show me the dalarn portal position for alliance and where it should be for horde? (screenshot)

**Comment by GMMetaxa** [comment]
April 1 announcement. Nothing to fix.

**Comment by Blackhelm36** [comment]
first 2 screen shots are the Alliance tower in the mall, second 2 are the Horde tower in the mall.
As you can see, there is a Dalaran portal in the alliance tower but not in the Horde tower.
________________________________

**Comment by Blackhelm36** [comment]
first 2 shots are of the Alliance tower, second 2 shots are the Horde tower...both in the mall, as you can see there is a Dal portal in the Alliance tower but not in the Horde tower.
________________________________
