### ISSUE TITLE
Warsong Gulch textures

### ISSUE THREAD

**Issue by Greywolf59** [WoWManiaUK/Redemption#4345]
**Links:**
Hello dearGM and Dev team! There would be as many links as there is ranged spells. I do not even know them all.

**What is Happening:**
Once again disclaimer: I did never play retail. Players under redpective faction graveyards can use spells on targets ressing on given graveyard through the textures, be it mage spells, mind flay, curses, hunter shots, sending pets up the hill, charging up the hill (charge is possible only from certain spots and it copy actual terrain so that might be okay, not sure about pets) etc. It is not only graveyarf but I was alao shot by hunter through piles of big cut down logs thrown around wsg. In all and all some textures do apply LoS (like tree stomps, huts), some do not.

**What Should happen:**
I very much think that every object should apply LoS, graveyard hill textures especially, unless you stand on the verge/top of the gy hill. This is long known issue among community which sometimes ehmm, pardon me... pisses people of, but I am not sure if anyone ever even tried to do the post about it here since the complexity of this post would be immense. So I am trying to put here at least some kind of general post here. I really cannot provide a list of spells going through texture. I am melee player and I have no idea about all kinds of ranged spells, my apologies.
P.S: this might be the issue also in other battlegrounds.

**Comment by Keader** [comment]
same issue in blizzard servers.
that's why they remade the graveyard some xpacks later
