### ISSUE TITLE
[Raid] Professor putricide - abomination disappearing

### ISSUE THREAD

**Issue by Terrorblat** [WoWManiaUK/Redemption#4346]
**Links:**

**What is Happening:**
We do all the way to Professor Putricide fine, but when we are starting to begin the figth, (the OffTank), drink the flask to get the abomination buff, and when he stepped in the first Mutated Slime to use Eat Ooze, the Mutated Abomination buff disappeared and we wipe.
That happens 3 time, with 2 different people making the same; I dont try it in other characters or in  other raid, but that happens for sure.

**What Should happen:**
The buff of Mutated Abomination must keep going, this is a must in this boss battle, without it, the boss can´t be killed.

**Comment by Keader** [comment]
any chance of someone dispel it (or totem)?

**Comment by tvshadowz** [comment]
As above this sounds like it was being dispelled, I have not seen this in horde side at all.

**Comment by Keader** [comment]
yeap, we dont changed abomination since 4 months ago.
@tvshadowz can you test in ptr to confirm?

**Comment by bluemonstrr** [comment]
@Terrorblat The abom is working fine and doesn't self dispel. If this happens again please check the dispels for the encounter.
