### ISSUE TITLE
[Core/Boss] Heigan the Unclean insane lag

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#4347]
**Links:** https://wowwiki.fandom.com/wiki/Heigan_the_Unclean

**What is Happening:** Fighting Heigan the Unclean causes crazy stress on the server and causes ~3-5 seconds of delay for all players while the fight is happening. I have witnessed this happening 3 times already and every time was a horde group fighting him. (Might be race/faction related)
Might be related to the green geyser particles or the fix to make sure the room has no safe spots.

Not entirely sure what the cause is, but it's a major issue whenever a raid is fighting him.

**What Should happen:** Heigan should not nearly crash the server.

**Comment by tvshadowz** [comment]
I believe this is a known/previously reported issue.

**Comment by Rushor** [comment]
Onyxia has maybe the same?

**Comment by wow-mania** [comment]
Lag is not is due to Heigan.

**Comment by Keader** [comment]
I need reproduce steps folks

**Comment by Oganku** [comment]
Fighting Heigan with a raid of ~6 (1 of each horde race) should trigger the lag in normal circumstances. Phase 2 is a lot worse than the first too, since the explosions happen much quicker.

**Comment by bluemonstrr** [comment]
![naxx](https://user-images.githubusercontent.com/33989250/78422599-6dbe9080-762e-11ea-9892-21bc7abc0b2f.png)

I found this upon entering naxx, when I opened my combat log my fps dropped from 120 to 30, then stayed at 1 or below, in the first few seconds before my fps dropped completely I was able to see how fast it was going. It was filling the combat log more than once fully per second.

**Comment by jeyrella** [comment]
#4359 opened for above

**Comment by wow-mania** [comment]
I have change the script for the Golen.

**Comment by bluemonstrr** [comment]
Embalming slime no longer spamming. Golem no longer casting.
