### ISSUE TITLE
Lag spikes 

### ISSUE THREAD

**Issue by Nightmarelandcreature** [WoWManiaUK/Redemption#4349]
![Untitled](https://user-images.githubusercontent.com/63058916/78261831-67ce8f80-7508-11ea-9491-58f3483ff6e6.png)
**Links:**

![wow mania ping](https://user-images.githubusercontent.com/63058916/78261887-7ddc5000-7508-11ea-8b47-aa1c00d3fca9.png)

**What is Happening:**
I did contact an GM earlier, they said my lag was because of my router/connection. So, i took those screenshots, and clearly, my connection seems pretty fine, since i can open anything else, even your website, but the lag spikes in game are hell. And the ping is nonexistant. I am using the wow-mania client, and launcher, i did clear my cache and restored all the patches, is there a way this problem could be solved because I can't even play at this point. 

**What Should happen:** Maybe we can do something to fix the lag.

**Comment by Nightmarelandcreature** [comment]
Do you even have any staff?

**Comment by bluemonstrr** [comment]
The recent lag and crashes are being worked on.
