### ISSUE TITLE
[ICC] Oozes of PP

### ISSUE THREAD

**Issue by Keader** [WoWManiaUK/Redemption#4350]
Morning all.
Has a issue with Oozes in Professor Putricide (PP).
Professor Putricide should cast spell:  ```SPELL_UNSTABLE_EXPERIMENT = 70351``` and summon a Ooze 5 secs later.
But when he is casting Unstable Experiment and raid force him to change phase (like keep PP with 76% hp, start cast unstable experiment and raid drop hp below 75% while he's casting) instead of summon 3 Oozes (1 of cast and +2 of phase change), it's summoning only 2 oozes.
This bug causes conflicts in https://github.com/WoWManiaUK/Redemption/issues/4200 too
Is same situation that show in this video: https://www.youtube.com/watch?v=wYoarTmLDFU&feature=youtu.be&list=PL33DAB04490C357B5&t=614
3 oozes need be summoned when he change phase close of cast, not only 2.

**Comment by Keader** [comment]
rdy to test

**Comment by bluemonstrr** [comment]
Works as shown in the video above. 👍

**Comment by slaniaxx** [comment]
in the same video, mage uses invisibilty to force the ooze to retarget, while I can't test this right now, can someone test that in dev?
