### ISSUE TITLE
[ICC/Professor Putricide] Bottles of transition²

### ISSUE THREAD

**Issue by Keader** [WoWManiaUK/Redemption#4351]
This topic, updates https://github.com/WoWManiaUK/Redemption/issues/4200
I'm marking as regression, since it's caused by last fix. It's a side effect.

In the last reprot, we have:

> In 25 man raids, Professor cast some bottles in players (1 green and 1 orange), to determine who should attack each ooze, during transitions.
> Problem is: The bottles was just removed when PP finish cast (5 sec later). It's wrong.
> Correct behavior is: bottles should vanish ONLY when all oozes die. It count any Ooze used BEFORE transition too.
> If before transition has 1 ooze and PP summon +2 during transition, you need kill 3 oozes to bottles vanish.
> Confirmed this behavior in blizzard servers.

But during this week, we found some issues in previous fix.
Some situations make the Bottles dont vanish when all oozes die, and some situations make Bottles dont even appear in transition.

So... i'm refixing it, with a new approach.
Correct behavior need be: After transition, you need kill ALL Oozes in Room before bottles vanish.
It means: 
-if you have 0 ooze before transition, you need kill 2 oozes during transition to get bottles dispel.
-if you have 1 ooze before transition, you need kill  3 oozes during transition to get bottles dispel.
-if you have 0 ooze before transition, but while transition phase PP summoned a new ooze (plus 2 oozes summoned when transition phase start), you need kill 3 oozes to get bottles dispel.

So... you always need have a clean room (without any ooze), before bottles get dispel.
It include oozes that is not spawned yet, but the smoke in big bottle of right and left side is already in.

**Comment by Keader** [comment]
Please test in dev, if you guys find any other way to make Bottles not vanish.
with video if possible (if you can find a way).

**Comment by Keader** [comment]
Updated to a new version.
Now it will count only oozes present in room (not counting the not-summoned yet).
More blizzlike now.
Plus fixed the summon of Ooze after transition. He should get a 20~25 sec delay after PP back to move.

**Comment by svijetlo** [comment]
very nice , as long you got transition debuff it wont be gone no mater what you do till you kill all ooze
