### ISSUE TITLE
Theramore Combat Dummies giving weapon skillup

### ISSUE THREAD

**Issue by jeyrella** [WoWManiaUK/Redemption#4352]
**Links:**
https://www.wow-mania.com/armory/?npc=4952

**What is Happening:**
Theramore Combat Dummies currently give weapon skill ups.
![image](https://user-images.githubusercontent.com/46089380/78283128-41fbb780-7515-11ea-88ae-40c0ae908016.png)

**What Should happen:**
No dummies anywhere should give weapon skillups, either with white attacks or special skills.
Other dummies in capital cities already seem to operate correctly in this regard.

**Comment by Rushor** [comment]
should no longer increase the skills

**Comment by jeyrella** [comment]
confirmed working correctly now 
![image](https://user-images.githubusercontent.com/46089380/78500282-6641d900-774d-11ea-8912-ea2bab915192.png)
