### ISSUE TITLE
Disenchant Roll Unavailable

### ISSUE THREAD

**Issue by slaniaxx** [WoWManiaUK/Redemption#4354]
**Links:**

![unknown](https://user-images.githubusercontent.com/45994511/78362526-f1db2e80-75c2-11ea-8ee9-6de916cffcd9.png)

**What is Happening:**
Disenchant Rolling option unavailable randomly in ICC.
(The option was available for PP, but was not available for Blood Prince Council.
We were combat bugged after Plague trash, but we were able to d/e roll Plague bosses.
I (450 enchanter) was in the room during the boss kills, and participated by healing for 

**What Should happen:**
Disenchant Rolling option should be available if a properly leveled enchanter is in the party during the kill, regardless of the player being in the same instance/zone/lockout(Blizzlike from my memory, regardless the option should not disappear).

**Comment by Rushor** [comment]
can someone reproduce this?

**Comment by svijetlo** [comment]
i did try lot of different things could not reproduce this
