### ISSUE TITLE
Huge Memory Allocation Fails

### ISSUE THREAD

**Issue by yasar11732** [WoWManiaUK/Redemption#4355]
**What is Happening:**

Couple of times a day, client crashes with following error;

![wow mania error](https://user-images.githubusercontent.com/976436/78381466-12fd4880-75de-11ea-887a-e76baa59f361.png)

**What Should happen:**

Game should not crash.

**Comment by Rushor** [comment]
Hello pls contact Janitor in Discord for such issues. The bugtracker is for ingame issues only
