### ISSUE TITLE
[Quest] Duplicate entry in quest window during A Blade Fit For A Champion

### ISSUE THREAD

**Issue by yani** [WoWManiaUK/Redemption#4356]
There is a duplicate option entry in the quest window of **Maiden of Ashwood Lake** during the daily quest **A Blade Fit For A Champion**.

![image](https://user-images.githubusercontent.com/6956790/78399902-0edd2500-75f6-11ea-90de-4d966cfb783a.png)

**Comment by Rushor** [comment]
will fix that.

**Comment by Rushor** [comment]
try now pls

**Comment by svijetlo** [comment]
![WoWScrnShot_040620_101319](https://user-images.githubusercontent.com/61908373/78537955-8e364880-77f0-11ea-9b20-43b97bfea806.jpg)
![WoWScrnShot_040620_102211](https://user-images.githubusercontent.com/61908373/78537959-90000c00-77f0-11ea-8506-0d10bb314380.jpg)
nop , same for ally and horde tho quest works so it is not that important minor visual thing

**Comment by Rushor** [comment]
newest fixes are live within couple of minutes
was not yet deployed
