### ISSUE TITLE
Quest 11879

### ISSUE THREAD

**Issue by goodebug** [WoWManiaUK/Redemption#4357]
NPC http://www.wow-mania.com/armory/?npc=25802 Kaw the Mammoth Destroyer not spawning making quest http://www.wow-mania.com/armory/?quest=11879 impossible to complete. 

I camped the area for nearly an hour and also asked 4 other players - they all came and couldn't find him. We tried killing Moria several times but everytime she just spawned and Kaw didn't.

Please check and let me know if I am mistaken.

**Comment by goodebug** [comment]
Well seems like it spawned after 2 hours, but unsure if it was due to any npc refresh command of the GM. I was able to do the quest, however, I request you to please check it once. Thank you!

**Comment by wow-mania** [comment]
Respawn time is 3+10 minutes.
