### ISSUE TITLE
[Spell] Disease Cloud 

### ISSUE THREAD

**Issue by bluemonstrr** [WoWManiaUK/Redemption#4358]
**Links:**
https://www.wow-mania.com/armory/?spell=27793
https://www.wow-mania.com/armory/?spell=28358
https://www.wowhead.com/npc=16017/patchwork-golem

**What is Happening:**
NPC=16017(Patchwork Golem) has disease cloud Spell aura ID=27793 which casts disease cloud spell ID=28358 

It currently casts the disease cloud insanely fast as shown in the gif below where I cast spells with only one golem left in the instance. 

https://i.gyazo.com/c65409154f4b0fac8d926d9a288b4045.mp4

**What Should happen:**
As far as I know it shouldn't be recasting like this. Opening the combat log in the middle of the construct quarter made me disconnect.

**Comment by bluemonstrr** [comment]
I should add that to reproduce you must be out of combat with the one you leave.

**Comment by jeyrella** [comment]
![image](https://user-images.githubusercontent.com/46089380/78450025-7b4a3980-7673-11ea-8c6a-04b0d81021d5.png)

**Comment by wow-mania** [comment]
This should be reported as part of the issue with Heigan not an issue with the spell itself.
