### ISSUE TITLE
[Spell] Embalming Cloud

### ISSUE THREAD

**Issue by bluemonstrr** [WoWManiaUK/Redemption#4359]
**Links:**
NPC ID=16024
Spell ID=28322

**What is Happening:**
Reference https://github.com/WoWManiaUK/Redemption/issues/4358
The spell is casting insanely fast specifically when they are out of combat.

**What Should happen:**

**Comment by bluemonstrr** [comment]
https://gyazo.com/d7b7c6768c6a74a82e9b2924e3228420

**Comment by jeyrella** [comment]
![image](https://user-images.githubusercontent.com/46089380/78450055-c5331f80-7673-11ea-963d-215d8e041223.png)

**Comment by wow-mania** [comment]
This should be reported as part of the issue with Heigan not an issue with the spell itself.
