### ISSUE TITLE
[ICC] Gas Cloud Damage (Expunged Gas)

### ISSUE THREAD

**Issue by Keader** [WoWManiaUK/Redemption#4360]
Our current script uses this formula:

![image](https://user-images.githubusercontent.com/7120913/78455361-3d014a00-7674-11ea-80a8-db1f9bd22f3b.png)

it come from wowwiki and TC uses it since 2015.
But we found evidences in warcraft logs, that this formula is not correct.
After analyse alot of logs, we get a new formula blizzlike.
To proof how much, damage diverge in 2 formulas i did a little simulation using 25 heroic as example.

> With 1 stacks, we have:
> Old Value = 1500
> New Value = 3900
> -----
> With 2 stacks, we have:
> Old Value = 4500
> New Value = 7800
> -----
> With 3 stacks, we have:
> Old Value = 9000
> New Value = 11700
> -----
> With 4 stacks, we have:
> Old Value = 15000
> New Value = 15600
> -----
> With 5 stacks, we have:
> Old Value = 22500
> New Value = 19500
> -----
> With 6 stacks, we have:
> Old Value = 31500
> New Value = 23400
> -----
> With 7 stacks, we have:
> Old Value = 42000
> New Value = 27300
> -----
> With 8 stacks, we have:
> Old Value = 54000
> New Value = 31200
> -----
> With 9 stacks, we have:
> Old Value = 67500
> New Value = 35100
> -----
> With 10 stacks, we have:
> Old Value = 82500
> New Value = 39000
> -----

As you can see, after 4 stacks, old formula get a fucking big damage, more then it should.
You can see this behavior in alot of Professor Putricide videos, when Orange Ooze reach raid and they still can survive the damage.

Remember: this values is the clean value, without absorves, damage reductions, etc.

**Comment by bluemonstrr** [comment]
![image](https://user-images.githubusercontent.com/33989250/78461855-7f3d8200-769a-11ea-9bd8-19c19ace3307.png)

Currently seems like I'm getting hit by one from pp, one from the gas cloud.

**Comment by bluemonstrr** [comment]
I will try a few more times at all different stacks.

**Comment by bluemonstrr** [comment]
The Gas Cloud's Expunched Gas is still hitting for 75900 at 10 stacks. as I lower stacks it does really seem to lower the damage as well, but I still don't understand why pp would be casting it as well. It didn't happen every time the gas cloud went off either. No steps to properly reproduce.

**Comment by Keader** [comment]
what?

**Comment by bluemonstrr** [comment]
PP also casted Expunged gas. Only 1 or 2 times though. The damage at 10 stacks is also still around 80k

**Comment by Keader** [comment]
Fixed again @bluemonstrr .
Call was duplicated. And not by me, was duplicated since forever.
How no one noticed it? lol

**Comment by bluemonstrr** [comment]
Gas Cloud's Expunged Gas hits Consecration for 35100 Plague.
Gas Cloud's Gaseous Bloat (9) subsides.
👍
