### ISSUE TITLE
[ICC/LK] Ice Pulse ignoring Resists

### ISSUE THREAD

**Issue by Keader** [WoWManiaUK/Redemption#4361]
Ice Pulse, casted by the little orbs of Lich King fight, need be reduced by resists.
In current script, it just ignore all resistences, doing a big damage on raid.
Proof: http://worldoflogs.com/reports/2gfwvypg9xqqq5b5/xe/?s=9522&e=9870&x=spell+%3D+%22Ice+Pulse%22

**Comment by bluemonstrr** [comment]
Ice Pulse hits Ossus for 8380 Frost.
Ossus casts Aegis of Dalaran.
Ossus gains Ossus's Aegis of Dalaran.
Ice Pulse hits Ossus for 3871 Frost.(3870 Resisted)

👍

**Comment by Aristo14** [comment]
Still needs confirmation.

**Comment by bluemonstrr** [comment]
@Aristo14 
Ice Pulse hits Ossus for 8380 Frost.
Ossus casts Aegis of Dalaran.
Ossus gains Ossus's Aegis of Dalaran.
Ice Pulse hits Ossus for 3871 Frost.(3870 Resisted)

I confirmed it
