### ISSUE TITLE
Blacksmithing Plans item in Blackrock Depths only spawning in one location

### ISSUE THREAD

**Issue by drewbost** [WoWManiaUK/Redemption#4362]
The Blacksmithing Plans item (https://www.wowhead.com/object=173232/blacksmithing-plans) that is supposed to appear in various locations within Blackrock Depths seems to only appear in one location.  According to some Wowhead comments, there should be a total of 5 potential spawn points with two active spawns per instance. After running the instance 10+ times, I have only ever seen it in one of the locations. This issue has been confirmed by GM Osyris.

The item gives various blacksmithing plans when you click on it. I am particularly interested in obtaining Plans: Dark Iron Shoulders ([https://www.wowhead.com/item=11615/plans-dark-iron-shoulders](https://www.wowhead.com/item=11615/plans-dark-iron-shoulders)) which, according to other Wowhead comments, can only be obtained from one of the 5 potential spawn points.

Other relevant Wowhead links with potentially helpful comments:
[Plans: Dark Iron Mail](https://www.wowhead.com/item=11614/plans-dark-iron-mail)
[Plans: Dark Iron Shoulders(Classic)](https://classic.wowhead.com/item=11615/plans-dark-iron-shoulders#comments)
[Plans: Dark Iron Mail(Classic)](https://classic.wowhead.com/item=11614/plans-dark-iron-mail#comments)

**Comment by Oganku** [comment]
I can confirm this also.

**Comment by wow-mania** [comment]
As is. If you can show the 5 coordinates from a wotlk source we will update.

**Comment by Rushor** [comment]
here some info https://www.wowhead.com/maps?data=1584.1:432867357634380706344782485380 

https://www.wowhead.com/object=173232/blacksmithing-plans#comments:id=515020

I will update the spawns and add the pooling

**Comment by Rushor** [comment]
spawns like shown here https://i.imgur.com/GCR9Gum.png added.

only 2 spawns maximum per instance.

**Comment by drewbost** [comment]
Not sure if this is still active but after running it 6 times today I only saw the same two spawns: the one next to the shadowforge lock and the one on the bench in the room with the gnomes.

**Comment by Keshilolz** [comment]
it seemes that is linked to my issue 4510, for me i found 3 all the time, one in the detention block behind the high interrogator gestharn. at the chambre ,ortheast (see image) . blank all the time

![image](https://user-images.githubusercontent.com/64604656/80745908-8aa49180-8b10-11ea-997f-0d40566996b5.png)

second in the room before the general angerforge (see image below)
![WoWScrnShot_043020_172544](https://user-images.githubusercontent.com/64604656/80746063-ca6b7900-8b10-11ea-8f88-d0b4c17f693f.jpg)

the third near the golem master (Allways the mail chest plan)

Btw the scroll at the shadowforge i never saw it and it drops the plate shoulders 100%

Thanks
