### ISSUE TITLE
[Quest] Foolish Endeavors 

### ISSUE THREAD

**Issue by bLeyaa** [WoWManiaUK/Redemption#4363]
**Links:** https://www.wowhead.com/quest=11705/foolish-endeavors

**What is Happening:** After starting the quest, text script of the NPCS talking is messed up a bit
> [00:56:14] Varidus the Flenser says: Take **$g him:her;** away and prepare $g him:her; for reanimation.

Also, when you finish the quest and go to turn it in at Garrosh Hellscream (Warsong Hold) there is no question mark on top of him.

**Comment by Rushor** [comment]
updated. remember that you need rep with https://www.wowhead.com/faction=1085/warsong-offensive in order to reward the quest.

**Comment by svijetlo** [comment]
![WoWScrnShot_040620_104905](https://user-images.githubusercontent.com/61908373/78540327-4ca79c80-77f4-11ea-909d-41b9023eab40.jpg)

**Comment by Rushor** [comment]
newest fixes are live within couple of minutes
was not yet deployed

**Comment by svijetlo** [comment]
![WoWScrnShot_040620_111148](https://user-images.githubusercontent.com/61908373/78542457-7c0bd880-77f7-11ea-8b40-2c31d721a474.jpg)
 perfect

**Comment by bLeyaa** [comment]
@Rushor 
>Varidus the Flenser says: Take $g him:her; away and prepare $g him:her; for reanimation.

![image](https://user-images.githubusercontent.com/61625377/78561560-3c091d80-7818-11ea-8ca7-2c4d05179513.png)

This is still present

**Comment by Rushor** [comment]
updated aswell with next restart
