### ISSUE TITLE
Darkmoon Faire cannon at Thunderbluff does not work

### ISSUE THREAD

**Issue by yani** [WoWManiaUK/Redemption#4365]
**Links:**
https://youtu.be/iRk2siEWD7E

**What is Happening:**
When using the Darkmoon Faire cannon at Thunderbluff weird stuff happens and you don't go to the Darkmoon Faire.

**What Should happen:**
I think you should be flown to the Darkmoon Faire.

**Comment by Rushor** [comment]
clicking > root > flybuff > hurray

**Comment by svijetlo** [comment]
nop same as in vid

**Comment by Rushor** [comment]
coolio
