### ISSUE TITLE
[Quest] During "The Honored Dead" there is a missing alert

### ISSUE THREAD

**Issue by yani** [WoWManiaUK/Redemption#4366]
**Links:**
https://www.youtube.com/watch?v=C9TB1KYZ3ME

**What is Happening:**
When you are not in range of a **Dead Caravan Guard** when using the **Ragefist's Torch** during **The Honored Dead** you are not notified of this.

**What Should happen:**
I think you should receive a message like "You need to be closer to interact with that target."

**Comment by Rushor** [comment]
will fix

**Comment by Rushor** [comment]
added a range check - but i can only add the message "cannot do that yet"

**Comment by yani** [comment]
Maybe that message could also be added when you try to burn a corpse that has recently been burned?

**Comment by Rushor** [comment]
sadly no, but that should be obvious
