### ISSUE TITLE
[Spells/PVP] Fixed Drain Mana removing Poly/Fear

### ISSUE THREAD

**Issue by Keader** [WoWManiaUK/Redemption#4367]
Drain mana is removing Poly / Fear.
This fix come from Trinity sometime ago, and was incorrect.
Drain Mana should not remove Poly / Fear in pvp.
Is a very OP strategy, spam fear and drain mana on target :)

**Comment by Sharuzan** [comment]
Bug confirmed by testers Zanguin(Sharuzan) and Velzevoul; Warlock skills will indeed break Polymorph and Fear.

**Comment by Keader** [comment]
try again now @Sharuzan 
I think that Janitor reseted DB 📦
