### ISSUE TITLE
[Core] Rendering

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#4369]
**Links:**

**What is Happening:** Recently rendering distance was massively reduced server-wide to help reduce the lag, but it can interfere with raids pretty bad. 

For example on Sindragosa, the markers for the Frost Bombs during the air phase don't load if they spawn too far from the players, making it impossible to avoid them and making the fight kind of a lottery. It also can make people think a boss/mob isn't there until they run right up to its face and it renders too late. Can easily be very frustrating  for new players who don't know the exact layout of bosses.

**What Should happen:** Rendering shouldn't be limited so heavily on server side. It can't make the game unplayable or more difficult in raids.

**Comment by Rushor** [comment]
If we make the markers active they should be visible right?

**Comment by Keader** [comment]
yes @Rushor .
Active creatures get a "world" visibility

**Comment by Rushor** [comment]
all related summons should be active now (bigger visibility)

**Comment by svijetlo** [comment]
![WoWScrnShot_040620_100237](https://user-images.githubusercontent.com/61908373/78536397-136c2e00-77ee-11ea-9e14-7383f99ceeba.jpg)
![WoWScrnShot_040620_100422](https://user-images.githubusercontent.com/61908373/78536406-15ce8800-77ee-11ea-89d7-7a5f0881c753.jpg)
![WoWScrnShot_040620_100416](https://user-images.githubusercontent.com/61908373/78536412-18c97880-77ee-11ea-9723-e60610ea6414.jpg)
  SEAMS JUST FINE TO ME
