### ISSUE TITLE
The Blood Furnance reputation on normal difficulty

### ISSUE THREAD

**Issue by Barentino92** [WoWManiaUK/Redemption#4373]
**Links:**

**What is Happening:**
Mobs in blood furnance normal dung giving 1 reputation per kill.

**What Should happen:**
the should give 5 reputation per kill on normal difficulty untill honored.

**Comment by Rushor** [comment]
will update

**Comment by wow-mania** [comment]
We need to confirm if what was said it should happen is correct, not just that is happening.
Reps and everything else should be as it WAS in retail then and not now.

**Comment by Rushor** [comment]
okay confirmed by https://wow.gamepedia.com/index.php?title=Laughing_Skull_Legionaire&type=revision&diff=2464922&oldid=1715780 (version wotlk)

will update the rep for the instnce now.

**Comment by Rushor** [comment]
done 5 in nh, 15 in hc

**Comment by svijetlo** [comment]
oh lol you found smt i was just about to link one terrible vid form back in day XD

**Comment by Rushor** [comment]
:D videos are even better - picture tells more than 100000 words
