### ISSUE TITLE
"Breaking News" text at login screen is often not HTML formatted

### ISSUE THREAD

**Issue by yani** [WoWManiaUK/Redemption#4374]
**What is Happening:**
The "Breaking News" text is often not formatted and displays raw HTML. A rough estimation would be that this happens 25% of the times for me. 

**What Should happen:**
The text should always be HTML formatted. I think it might be something with the ddos-guard protection and return headers.

![image](https://user-images.githubusercontent.com/6956790/78559057-019d8180-7814-11ea-94b9-f32490b5ccc4.png)

**Comment by wow-mania** [comment]
has to do with access right from client on you machine

**Comment by yani** [comment]
> has to do with access rights from the client on your machine.
> Close and re-open client as admin and it solves it.

What do you mean? It's random. And there are no weird policies on my machine.
