### ISSUE TITLE
[Instance] Zul Aman

### ISSUE THREAD

**Issue by cathyr1** [WoWManiaUK/Redemption#4375]
What is Happening:
When player leaves this instance (e.a. dead or to turn quest), its impossible to enter it again.

What Should happen:
When player needs to re-enter instance while no bossfight inside, he should enter like any other raid instance.

It says "encounter in progress" even when no bossfight. This bug lasts for very long time. Nothing can help, even regroup, reset instances, changes all difficulties etc. Only server restart works.

**Comment by Rushor** [comment]
that was a good one.

reason is this boss: https://www.wowhead.com/npc=23574/akilzon

If you kill him the instance is not set to "done/finished" (same on reset). Added that for him.

**Comment by Rushor** [comment]
tested on dev and works fine so far for the boss (it was the only fault)
