### ISSUE TITLE
[Achievement] Trial of the Champion + Heroic: Trial of the Champion (horde side)

### ISSUE THREAD

**Issue by cathyr1** [WoWManiaUK/Redemption#4376]
**Links:**
https://www.wow-mania.com/armory/?achievement=3778
https://www.wow-mania.com/armory/?achievement=4297

**What is Happening:**
There is no progression of this quest despite I killed these bosses multiple times.

**What Should happen:**
Each kill of the boss linked in the achieve should complete that part of it.

![achieve](https://user-images.githubusercontent.com/30184491/78562998-91462e80-781a-11ea-974b-4c4e74ac5229.png)

**Comment by bLeyaa** [comment]
Works fine on Alliance, but its broken on Horde. I couldn't get credit for either of the possible 5 NPCs from the first fight.
I noticed that both of the achievements on horde are shown where normal difficulty achievements are. Not sure if this is clashing with the given count.
![image](https://user-images.githubusercontent.com/61625377/78566240-3c58e700-781f-11ea-84cb-1db0f5e0fc24.png)

**Comment by Rushor** [comment]
ah i remember keader modified some stuff there -soo the stage is yours sir :>

**Comment by Keader** [comment]
i do not lol
nothing related with that @Rushor

**Comment by Rushor** [comment]
okay gonna check again

**Comment by Aristo14** [comment]
Current state of this GH?

**Comment by Rushor** [comment]
try now pls
