### ISSUE TITLE
[Boss/Mechanic] Professor Putricide Unstable Experiment

### ISSUE THREAD

**Issue by bluemonstrr** [WoWManiaUK/Redemption#4378]
**Links:**
https://www.wowhead.com/npc=36678/professor-putricide
https://www.wowhead.com/spell=70351/unstable-experiment

**What is Happening:**

Once the boss starts phase 2 it will cast the first unstable experiment of the phase. Roughly 12 seconds afterwards it will start to cast again, meaning you will not even have enough time to dps one down before the second spawns. The 3rd spawns when the 2nd should, then the 4th spawns 10 seconds after that again. 5th spawns when 4th should ETC. 

This is currently making the fight impossible to do on 25hc.

**What Should happen:**
 Once phase 2 starts the time between unstable experiment casts is around 36 seconds, giving the raid enough time to actually dps them down and go back to boss before the next one.

**Comment by bluemonstrr** [comment]
Sindragosa's Gauntlet isn't activating either. I imagine this may be because of the rendering change put in by janitor, but just a thought.

**Comment by Rushor** [comment]
trigger have move  in line of sight default enabled again

**Comment by Rushor** [comment]
okay now works again

**Comment by bLeyaa** [comment]
Bump, still the same.

**Comment by bluemonstrr** [comment]
The Pp oozes are still summoning every 12 seconds rather than 36 or whatever it should be.
Apparently it's not from the gauntlet like I had hoped.

**Comment by bluemonstrr** [comment]
I have edited out the gauntlet as it has been fixed. The unstable experiment fix should be top priority right now. If anyone finds anything else wrong with the fight please DM me on discord @ Baguette#6413.

**Comment by Rushor** [comment]
needed the ticket. gaunlet all outsourced to https://github.com/WoWManiaUK/Redemption/issues/4386

nly boss needs fixing now

**Comment by Rushor** [comment]
check now pls
