### ISSUE TITLE
"Nightfall" affliction lock bug

### ISSUE THREAD

**Issue by Kinkywiener** [WoWManiaUK/Redemption#4379]
**Links:**
http://www.wow-mania.com/armory?spell=18095
http://www.wow-mania.com/armory?spell=17941

**What is Happening:** 
Shadow trance (nightfall talent proc) procs upon landing Corruption on a target, without the actual damage tick.

**What Should happen:**
Shadow trance should only proc upon Corruption tick damage, not upon landing the spell on a target.

**Comment by wow-mania** [comment]
Please use our armory. Takes exactly the same time.

**Comment by bLeyaa** [comment]
Updated with wow-mania armory links.
