### ISSUE TITLE
Warlock pet gets "loose"

### ISSUE THREAD

**Issue by Kinkywiener** [WoWManiaUK/Redemption#4380]
**Links:**

**What is Happening:**
Whenever, I put pet on Stay, move a few steps, put pet on Follow and then again Stay without it coming back to me, then using any of the pets abilities without having the determined effect (Spell Lock on felhunter without target, Devour Magic with no target or a target without a debuff/buff, Seduction on succubus without a target etc...) pet runs off in a straight line, through the texture/falls through the floor and disappears. Its quite a troublemaker when it comes to PVP.

**What Should happen:**
Pet should stay at place, regardless of using abilities that have the effect or not. Then again, he should follow and stay however commanded. I do not know if hunters have the same issue, but this issue has been present on several warlocks, not just me.

**Comment by Keader** [comment]
Fixed and tested in game.
Working fine now :)
