### ISSUE TITLE
The Culling of Stratholme - Stratholme Citizen (Infinite Hunter)

### ISSUE THREAD

**Issue by bLeyaa** [WoWManiaUK/Redemption#4381]
**Links:** [Stratholme Citizen](https://www.wowhead.com/npc=28167/stratholme-citizen) / [Infinite Hunter](https://www.wowhead.com/npc=27743/infinite-hunter) 

**What is Happening:** After killing the first two bosses and moving towards the third one, there is 3 Stratholme Citizens at the entrance of the house (well, 2 Agitated Stratholme Citizens and 1 Stratholme Citizen). The Stratholme Citizen is attackable before transforming into Infinite Hunter, which then makes the third Infinite Hunter that appears non-attackable NPC.

**What Should happen:** None of the Stratholme Citizens at that place should be attackable until they transform into Infinite Hunters and initiate the fight.

P.S. For what it matters, if not too big deal in changing, all three NPCs should be called Stratholme Citizen rather than Agitated Stratholme Citizen. Agitated ones are supposed to be the ones who turn into zombies.

**Comment by squalllh1989** [comment]
I can confirm that this indead is the case, however the 3rd citizen that is attackble and after transform become not attackble npc isn't cause any trouble, the result is the same as 3 of them is being killed. The different is that player saved like 5-10 sec to kill just another mob.

**Comment by bLeyaa** [comment]
Didn't say it causes trouble, it's just incorrect. :)

**Comment by Rushor** [comment]
test now pls

**Comment by Rushor** [comment]
https://i.imgur.com/NRcoDi0.jpg
