### ISSUE TITLE
Empowered blood at Blood quarter bug

### ISSUE THREAD

**Issue by Kinkywiener** [WoWManiaUK/Redemption#4382]
**Links:**
https://www.wowhead.com/spell=70227/empowered-blood

**What is Happening:**
The buff doesnt reduce the cost of the spells.
Also, upon casting a Damage over time spell, the spell only deals initial 1 tick damage and the debuff doesnt stay on. That 1 tick is 200% the damage of the default damage. Sometimes upon clickiing on the orb, "You are in the wrong zone" warning pops up, even though youre in the right zone and you end up unbuffed. When you leave the zone, the buff wears off as it should.

**What Should happen:**
The buff should reduce the cost of the spells by 100%. I believe the dots should land the same way.

**Comment by Rushor** [comment]
second effect should be active now

**Comment by bLeyaa** [comment]
@Rushor I've also noticed that the orb is being respawned after someone uses it. Should be one time use only afaik.

**Comment by Rushor** [comment]
increased the respawntimer aswell (6 days)

**Comment by Aristo14** [comment]
Any fact check done about: " I've also noticed that the orb is being respawned after someone uses it. Should be one time use only afaik."
afaik is not enough to just go change stuff ;)

**Comment by Rushor** [comment]
yes i did that on retail some years ago - that mechanic was not changed since a decate

**Comment by bLeyaa** [comment]
@Rushor Still getting "you're in the wrong zone" and mana is being consumed

@Aristo14 
> By Barkbober (238 – 2·4) on 2010/06/22 (Patch 3.3.5)
When you first pull the group of adds one of them will begin to siphon from the orb. If you kill them before the orb is drained then the first person to click it gets that buff.

**Comment by Rushor** [comment]
i can click just fine on them :o https://i.imgur.com/NIF8Oin.jpg

**Comment by Rushor** [comment]
or show me a video pls - test both on horde and ally on dev :o

**Comment by Aristo14** [comment]
ok ;) 
Try to use links like that when commenting so there is no question about it.

**Comment by bluemonstrr** [comment]
No issue here with zone error now. Cast was free and DoT was dealing 200% damage. If anyone gets "Wrong zone" again please remove the fix confirmation.

**Comment by bLeyaa** [comment]
I was getting it from the very first orb, 10m normal difficulty. Will record it in a bit, just to get to PC.

**Comment by bluemonstrr** [comment]
Working on all difficulties other than 10nm, I didn't have mana issues, but @bLeyaa did.

**Comment by Rushor** [comment]
works for me in 10 man aswell :o https://i.imgur.com/fMrRio7.jpg this is strange

**Comment by bLeyaa** [comment]
Mana usage: https://youtu.be/-ROGDZdZiYo

Wrong zone: https://youtu.be/zr73BtsQy00

**Comment by Rushor** [comment]
hmm i still cannot reproduce that for me - is really strange

**Comment by Rushor** [comment]
another tester can confirm that issue aswell?

**Comment by bLeyaa** [comment]
I believe @bluemonstrr had it reproduced.

**Comment by Rushor** [comment]
@bluemonstrr can you also make a video with reproduce step? because i caanot see the error so far still :(

**Comment by bluemonstrr** [comment]
I just tried to reproduce again, but the message isn't showing up. I'm getting the empowered blood just as I should.
![image](https://user-images.githubusercontent.com/33989250/78948180-88ad5c80-7a95-11ea-8287-b1743b1f2cf6.png)
