### ISSUE TITLE
judgement of wisdom don't work

### ISSUE THREAD

**Issue by Ghunter1981** [WoWManiaUK/Redemption#4383]
**Links:**

**What is Happening:**
in game paladin name Syllenne
for a couple of days now the judgment of wisdom of my paladin tank no longer works

**What Should happen:**

it should happen that when I use it I should get mana, but it doesn't happen

**Comment by Rushor** [comment]
this works fine for us

Attacks and spells used against you have a chance of restoring 46 of the attacker's mana.
