### ISSUE TITLE
Ice Tomb line of sight - Sindragosa

### ISSUE THREAD

**Issue by bLeyaa** [WoWManiaUK/Redemption#4384]
**Links:** https://www.youtube.com/watch?v=O8NDBlSpM4g (09:00) ; https://www.youtube.com/watch?v=z9CQ3d5kel8 (07:10)

**What is Happening:** Ice Tombs have no line of sight in second phase, you can attack boss while standing behind the tombs.

**What Should happen:** Ice Tombs should represent an obstruction in front of a player not allowing to cast through them.

*Ice Block should LoS players from being gripped for Blistering and block Mystic Buffet stacks.
*Ice Block **_should NOT_** LoS Blistering Cold damage.

**Comment by wow-mania** [comment]
I specified a while back that we would not be fiddling with this anymore. Up to Keader.

**Comment by bLeyaa** [comment]
Don't know how difficult it is to do this, but it changes the fight A LOT. Any ranged dps can literally stand in one place the entire phase 2, making the fight trivial - even on heroic.

**Comment by wow-mania** [comment]
If it is to make the fight harder it is ok :)

**Comment by svijetlo** [comment]
was this tested can you shoot trou toomb in p2 here , as in vids they use different tactic then we do so tomb is not right in front of us

**Comment by bLeyaa** [comment]
I've been shooting through tombs since i joined the server :P

**Comment by bLeyaa** [comment]
As i manged to test everything works perfect now.

**Comment by Rushor** [comment]
cool was a good one :)
