### ISSUE TITLE
Sindragosa gauntlet not active

### ISSUE THREAD

**Issue by squalllh1989** [WoWManiaUK/Redemption#4386]
**What is Happening:** Currently the sindragosa gauntlet does not active, so the door is close and the teleport is not active, you can't get to her.

**What Should happen:** The gauntlet should active when you move to the gauntlet room before sindy.

Not sure if this is reported or not, but since i can't find it so i will report it just to make sure.

**Comment by bluemonstrr** [comment]
See https://github.com/WoWManiaUK/Redemption/issues/4378 for the info on that in the comments. Gauntlets have been fixed on PTR. Will be live in the morning.

**Comment by Rushor** [comment]
will use this ticket, since i fixed the mechanic for the trigger/gaunlets - pp is fro keader now :)
