### ISSUE TITLE
[Quest] Death's Gaze - 13120

### ISSUE THREAD

**Issue by xrawenx** [WoWManiaUK/Redemption#4387]
https://www.wowhead.com/quest=13120/deaths-gaze

**What is Happening:**
Quest can't be turned in when finished. And if abandon the quest it won't work to pick it up again. 
Npc Darkrider Arly doesn't have the question mark above her head after I got help from gm to get back my quest.

**What Should happen:**
It should finish when turning in and get the next quest.

**Comment by wow-mania** [comment]
100% sure it works. Check requirements.

**Comment by svijetlo** [comment]
let me check fast

**Comment by svijetlo** [comment]
![WoWScrnShot_040720_135931](https://user-images.githubusercontent.com/61908373/78666722-117e9980-78d8-11ea-8bdf-a999dd9d0a36.jpg)
yup ,a fter completing quest you can not interact with npc at all, smt went wrong it worked perfect 2 weeks ago

**Comment by wow-mania** [comment]
Check conditions and requirements. I am sure this used to work fine so we need to know what happened.

**Comment by svijetlo** [comment]
i em sure 100% it used to work as i tested whole quest line form this npc 2 weeks ago well redo it few times see is there some rquirement wrong

**Comment by Rushor** [comment]
in db we have 2 conditions for the quest.

you will only see the mark and can complete if if you have quest: https://www.wowhead.com/quest=13105/once-more-unto-the-breach-hero and https://www.wowhead.com/quest=13104 rewarded. pls check that

**Comment by svijetlo** [comment]
oh lol it just worked on other toon that don that argent grounds quest line, so as it is icecrown quest a bit of storytelling you need to do some other quest before you can do some quest as it is connected in story , so this one is working as it is , sorry for time taken

**Comment by Rushor** [comment]
no not yet man

**Comment by Rushor** [comment]
there was an issue with the condition -

you will now either need 13104 or 13105 rewarded in order to take the quest

(and of course in addition to that you need quest 13117 rewarded in order to take 13120)

updated the conditions

**Comment by svijetlo** [comment]
yes it is proper now need to follow questline, if ppl get confused you must complete quest of npc next to gnome before cont with gnome dk

**Comment by xrawenx** [comment]
I just logged in and still can't turn it in. No questionmark above head either.
How's it going with the troubleshooting? I have done 117 of 140 quests in Icecrown.

**Comment by Aristo14** [comment]
It will first be fixed on the test realm xrawenx. What you see the testers talk about it working is on the testrealm. The fix will be in the weekly update tuesdays.
