### ISSUE TITLE
[Item] Sharpened Twilight Scale proc

### ISSUE THREAD

**Issue by Greywolf59** [WoWManiaUK/Redemption#4388]
**Links:**
Sharpened Twilight Scale https://www.wow-mania.com/armory/?item=54569
HC version probably too 

**What is Happening:**
There is written "When you deal damage you have a chance to gain..."
I got the buff from STS when chilling in lava pool in Obsidian Sanctum from taking damage. So STS also activates from damage taken. Other Scales should be tested too.

**What Should happen:**
I suppose STS should activate only from damage dealt. I have no screenshot as it did not occur to me to make one at the time but I presume this is easily testable and provable.

**Comment by svijetlo** [comment]
![WoWScrnShot_040720_150338](https://user-images.githubusercontent.com/61908373/78672628-362b3f00-78e1-11ea-94d5-ed3dbc2e6228.jpg)

**Comment by svijetlo** [comment]
it only happens in OS lava pools i just spend some time in lava around the world and no proc and it does not prock if you take dmg form enemy, so low prio for sure

**Comment by Greywolf59** [comment]
Oh lol, magical lava in OS :D. Okay, never thought it would be instance-specific.

**Comment by bluemonstrr** [comment]
It's common for it to proc when damage is taken in raid environment due to buffs. Since you need only sneeze for this trinket to proc, it will happen a lot.

**Comment by svijetlo** [comment]
tho i cant find anything of it procking like this back in retail if it did just then close this thing

**Comment by wow-mania** [comment]
We need something to back it up... if there isn't an article or source specifying this just close it.

**Comment by svijetlo** [comment]
i cant find a thing about this, so as i care it is one place pricking one trinket it wont change game , potently can make bigger mess then benefit so as i care close it waste of time if you ask me , just dont step in lava if you are there , help your healers

**Comment by Keader** [comment]
Should not proc with damage taken.

**Comment by bLeyaa** [comment]
i had STS proccing on PTR from random things when i took damage, and i didnt stand in lava.... I just dont remember what it was specifically now, but i've seen it happen...

**Comment by Greywolf59** [comment]
Addition: right now at the start of gunship 25m N when we entered combat, no damage out yet, my STS proced.

**Comment by Keader** [comment]
rdy to test
