### ISSUE TITLE
"Black Proto Drake" can't fly in Azeroth even if "Reins of Black Proto Drake" tooltip says otherwise

### ISSUE THREAD

**Issue by yahyaharif** [WoWManiaUK/Redemption#4389]
**Links:**
https://imgur.com/8fNKV4v
https://imgur.com/Jv5qV2c

**What is Happening:**
The tooltip of "Reins of Black Proto Drake" says you can fly the mount in Azeroth. However once you learn it, the tooltips don't match anymore and indeed you can't fly the mount in Azeroth (tested in Stormwind only though) 

**What Should happen:**
Have the tooltip information match. Preferablt have the mount be able to fly in Azeroth since it's the reason people spent a VIP token for it.

Thanks for your time,

**Comment by wow-mania** [comment]
![image](https://user-images.githubusercontent.com/12248683/78674487-97501400-78db-11ea-9f4f-551eb8e06e85.png)

**Comment by wow-mania** [comment]
Make sure you have our client fully updated and delete cache.

**Comment by WhitephoenixTheBunny** [comment]
I was to comment :(
