### ISSUE TITLE
[Quest] Grunt Ragefist is nowhere to be found during Report to Steeljaw's Caravan 

### ISSUE THREAD

**Issue by yani** [WoWManiaUK/Redemption#4391]
**Links:**
Bug: https://youtu.be/o74NPNkYzL0
How it should be: https://www.youtube.com/watch?v=AYca7s4vWWs

**What is Happening:**
**Grunt Ragefist** is not at the location marked by the quest. He's nowhere to be found.

**What Should happen:**
**Grunt Ragefist** should be at the location of the quest.

**EDIT:** He suddenly spawned, but without a questionmark above him.
https://v0id.us/uploads/WoW-Mania_4TN6Cvjq08.jpg

**Comment by wow-mania** [comment]
please check quest requirents

**Comment by yani** [comment]
I have the requirements. He spawned after making this ticket. Was possible to complete the quest.

**Comment by Rushor** [comment]
will check maybe some escort issues with flags

**Comment by wow-mania** [comment]
You think so... also opening a tickets had nothing to do with it spawning. 
We will try to reproduce the issue to give the benefit of doubt.

**Comment by jeyrella** [comment]
https://www.wow-mania.com/armory/?quest=11591

**Comment by jeyrella** [comment]
was there immediately after taking the quest
![image](https://user-images.githubusercontent.com/46089380/78714011-039a3a00-7913-11ea-830f-17565e55ea7c.png)
will see if i can find a way to force him to not be there in some way

**Comment by jeyrella** [comment]
Ok.  If a previous player has tried (and failed) the follow-up quest ["We Strike!"](https://www.wow-mania.com/armory/?quest=11592) , and Grunt Ragefist is killed, then he will be despawned for a length of time.  This is normal and expected, and I believe exactly what was experienced here.

However, the [Warsong Caravan Guards](https://www.wow-mania.com/armory/?npc=25338) respawn much quicker than he does, giving the optical illusion that Grunt is missing.
![image](https://user-images.githubusercontent.com/46089380/78714817-604a2480-7914-11ea-9517-cd06d69c85eb.png)

Warsong Caravan guard spawn:  https://www.wow-mania.com/armory/?npc=25338
![image](https://user-images.githubusercontent.com/46089380/78715019-ae5f2800-7914-11ea-8218-e728af3b183a.png)

![image](https://user-images.githubusercontent.com/46089380/78715121-d77fb880-7914-11ea-8ddd-036683f39f1c.png)

I can't find any evidence to the contrary that these are correct spawn times.  5 mins is not exactly long time so I don't think there is any particularly pressing reason to make any change here.
