### ISSUE TITLE
[Quest] Opening the Backdoor bugged

### ISSUE THREAD

**Issue by yani** [WoWManiaUK/Redemption#4392]
The quest **Opening the Backdoor** is awfully bugged. I'm unable to use the **Transporter Power Cell** (I had to /camp to "trigger" the quest log just to show I got it). Also, talking to **Ricket** again shows the quest window as seen in the screenshot.

![image](https://user-images.githubusercontent.com/6956790/78696108-418d6300-78ff-11ea-86e9-ceb01a9ae6f6.png)

**Comment by wow-mania** [comment]
works

**Comment by jeyrella** [comment]
@yani I could take this no problem

Can i suggest you check your client download/cache folder and/or ElvUI update etc.  There's a number of issues you reported now that seem to work fine

**Comment by yani** [comment]
Nevermind. I was wrong. The teleporter is not located at 41,85 but at 49,82.
