### ISSUE TITLE
[Skill] Clearcasting with a finishing move on a kitty druid

### ISSUE THREAD

**Issue by nhockey** [WoWManiaUK/Redemption#4393]
**Links:**

**What is Happening:**
When you use a finishing move while clearcasting is up it consumes both energy and the clearcasting effect.

**What Should happen:**
When the clearcasting effect is up energy should not be consumed by finishing moves.

**Comment by jeyrella** [comment]
Let's have a skills tester run on this first, there is some doubt that this is valid, and/or there are some specific scenarios for this.

**Comment by Rushor** [comment]
okay :)

**Comment by Sharuzan** [comment]
Finishing move does indeed consume energy during clearcasting, though it seems to only affect Ferocious Bite & Savage Roar. 
Maim & Rip consume no energy.

**Comment by Kilju** [comment]
Ferocious is supposed to consume your clearcast + energy as well. 
Cata discussion (not official): https://www.mmo-champion.com/threads/887818-Ferocious-Bite-Clearcasting
Found many links to just writing "Ferocious bite clearcast" from vanilla through to cataclysm.
So Ferocious Bite will consume your clearcast (for initial 35 energy) and then use your energy as well for extra damage.
Server armory: https://www.wow-mania.com/armory/?spell=48577

**Comment by Aristo14** [comment]
This is why I initially wanted to label it [Invalid - Incomplete report]  
Thank you Kilju! 

The report is incomplete as it does not pertain to any specific spell.
