### ISSUE TITLE
[NPC] Longrunner Proudhoof does not respawn after killed by NPC in quest We Strike

### ISSUE THREAD

**Issue by jeyrella** [WoWManiaUK/Redemption#4394]
**Links:**
https://www.wow-mania.com/armory/?npc=25335

**What is Happening:**
If Proudhoof is killed during quest "We Strike!" then he does not respawn at the caravan at all (even with a GM-forced .respawn)
![image](https://user-images.githubusercontent.com/46089380/78717159-18c59780-7918-11ea-9a65-cf52e52e4ab5.png)

**What Should happen:**
According to armory, Proudhoof should have a 2 min respawn.

**Comment by Rushor** [comment]
hmm for me he respawns there https://i.imgur.com/ua6HizZ.jpg

is that issue always happening to you?

**Comment by Rushor** [comment]
okay he will directly despawn after beeing killed - i think that should solve the issue

**Comment by Sharuzan** [comment]
Longrunner Proudhoof now respawns correctly at Steeljaw's Caravan, by himself, when killed by mobs :)
