### ISSUE TITLE
[Quest]  Double the correct number of ambushers in quest "We Strike!" - 11592

### ISSUE THREAD

**Issue by jeyrella** [WoWManiaUK/Redemption#4395]
**Links:**
https://www.wow-mania.com/armory/?quest=11592

Ghostly Sage: https://www.wow-mania.com/armory/?npc=25351
Risen Longrunner:  https://www.wow-mania.com/armory/?npc=25350

**What is Happening:**
During the quest, the group is ambushed after a few seconds.  There are 5x ambushers, but each one looks like it is duplicated at the same location, so actually 10 are spawned.
![image](https://user-images.githubusercontent.com/46089380/78717496-9e494780-7918-11ea-86a9-14a4eebc35db.png)

**What Should happen:**
There should be only 5 ambushers; 4x Ghostly Sage and 1x Risen Longrunner.
10x mobs is entirely unreasonable expectation for a single-player quest, even with 3x NPC "helpers".
Whilst the only video of this I could find is of later era, it clearly shows only 5 non-duplicated spawns
https://youtu.be/dRn6AecIB8o?t=44
![image](https://user-images.githubusercontent.com/46089380/78717577-ba4ce900-7918-11ea-807a-4301131e557c.png)

**Comment by Rushor** [comment]
no double anymore

**Comment by Sharuzan** [comment]
Only 4 sages and 1 longrunner do indeed spawn :)
