### ISSUE TITLE
Varos Cloudstrider not encounterable

### ISSUE THREAD

**Issue by squalllh1989** [WoWManiaUK/Redemption#4396]
**Links:** https://www.wowhead.com/npc=27447/varos-cloudstrider

**What is Happening:** The boss can't be encounterable even after kill all centrifuge constructs.

**What Should happen:** The boss should be encounterable after kill all 10 centrifuge constructs.

**Comment by svijetlo** [comment]
![WoWScrnShot_040820_103027](https://user-images.githubusercontent.com/61908373/78762331-04b77f80-7984-11ea-9fad-0b6a35115c38.jpg)
can not reproduce after multiple attempts

**Comment by squalllh1989** [comment]
![image](https://user-images.githubusercontent.com/27235989/78825831-ca44f580-7a0a-11ea-80bd-cd439280b148.png)

please try again, i just do another rdf hc on another character and got into this again, so that time is not a single 1 time case, some thing must be wrong

**Comment by squalllh1989** [comment]
just got oculus popped again today after the daily rhc reset, and the 2nd boss is bugged, again, i recorded a video of the run this time, maybe it will help you to find out why this is bugged. 
link: https://youtu.be/Hdiy4_njgV0

**Comment by squalllh1989** [comment]
this is another run, i queued specificly for the oculus, on horde side: https://youtu.be/icadoV-kQMw

**Comment by squalllh1989** [comment]
@svijetlo can you recheck this please
