### ISSUE TITLE
[Raid/NPC] Trial of the Crusader (Swarm Scarabs)

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#4397]
**Links:** https://www.wowhead.com/npc=34605/swarm-scarab#abilities
https://youtu.be/PlMtNG8D2x0?t=20

**What is Happening:** Anub'arak's boss room is filled with visible scarabs that skitter around even before he is engaged. Those scarabs are untargetable and don't interact with players, but clutter the arena and can be confusing to players that don't know they're not actually there.

**What Should happen:** As seen in [this video](https://youtu.be/PlMtNG8D2x0?t=20), the arena is completely clear except for the boss himself before the pull, and the [Swarm Scarabs](https://www.wowhead.com/npc=34605/swarm-scarab#abilities) remain unseen until they start spawning during the burrow phase.

**Comment by Rushor** [comment]
https://i.imgur.com/sESppvq.jpg

only spawn in in "underground" phase now + the "Frost Sphere" are no longer visible as dummy creature.

**Comment by bluemonstrr** [comment]
**Before Fight**
![image](https://user-images.githubusercontent.com/33989250/78947510-877b3000-7a93-11ea-8e5c-b9ede94d997c.png)
**Underground Phase**
![image](https://user-images.githubusercontent.com/33989250/78947645-f35d9880-7a93-11ea-88f2-0acbc27d1bcc.png)
Seems to be working just fine now :)
