### ISSUE TITLE
The Cipher of Damnation-Grom'tor's Charge

### ISSUE THREAD

**Issue by foter456** [WoWManiaUK/Redemption#4399]
**Links:**

**What is Happening:** The Coilskar chests doesn't drop the quest item. I'm safe to say that after opening at least 50 chests.
**What Should happen:** The armory tells me that the quest item has a 12% drop rate from chests. This number is either much lower, or they doesn't drop at all. Please fix it, because it makes leveling, or loremastering very frustrating.

**Comment by Rushor** [comment]
dropchance is indeed 12 percent in db. maybe the objects you looted were wrong?

**Comment by jeyrella** [comment]
Tested on PTR 4x.   Got item on 2nd, 6th, 8th and 19th chest.  Sounds like you just got really bad RNG.
