### ISSUE TITLE
[Quests] Masked Orphan Matron quest order / 0 fires / Shade's pathing

### ISSUE THREAD

**Issue by hornista** [WoWManiaUK/Redemption#440]
Reports the following quests are not doing anything.  Have not seen any fires myself either
http://www.wowhead.com/quest=11361/fire-training
http://www.wowhead.com/quest=12139/let-the-fires-come
http://www.wowhead.com/quest=11219/stop-the-fires

**Comment by Kalasbyxan** [comment]
Closing as Hallow's End content is being tested and worked on.

**Comment by Echinaceax** [comment]
Video to show first quest (doesnt show all at the same time) https://www.youtube.com/watch?v=Hrxzd5pmjjg
Link to show "notes" of quest order https://wowpedia.fandom.com/wiki/%22Let_the_Fires_Come!%22_(Horde)

### This has not been worked on for the horde side as stated above from 2016

Atm I see ALL horde Quests for [Razor Hill](https://wowpedia.fandom.com/wiki/Razor_Hill) in [Durotar](https://wowpedia.fandom.com/wiki/Durotar), in [Eversong Woods](https://wowpedia.fandom.com/wiki/Eversong_Woods), and in [Brill](https://wowpedia.fandom.com/wiki/Brill) in [Tirisfal Glades](https://wowpedia.fandom.com/wiki/Tirisfal_Glades) all auto completing after a short time, so players can pick up ALL the quest at the same time and stand there and wait for a very short time and the quests complete without having to do anything

Seen myself for the list horde zones above. including [Eversong Woods](https://wowpedia.fandom.com/wiki/Eversong_Woods) i just missed the screenshot for that one (coz i was on a different test at the time)

- [ ] Brill 

![Brill](https://github.com/WoWManiaUK/Redemption/assets/39439201/97e00cea-8747-463a-b340-338ff9fcdb2f)

- [ ] Razer hill

![razerhill](https://github.com/WoWManiaUK/Redemption/assets/39439201/05598c0a-cb42-4623-80e2-01cf819e5d6d)


- [ ] 0 building fires
- [ ] Shade movement and pathing is weird for all horde zone 
https://i.gyazo.com/bef7b898c2ae97b7629668580d248e41.mp4

### Edited same issues for Alliance 

The Alliance [Costumed Orphan Matron](https://wowpedia.fandom.com/wiki/Costumed_Orphan_Matron) can be found in [Azure Watch](https://wowpedia.fandom.com/wiki/Azure_Watch) in [Azuremyst Isle](https://wowpedia.fandom.com/wiki/Azuremyst_Isle), [Kharanos](https://wowpedia.fandom.com/wiki/Kharanos) in [Dun Morogh](https://wowpedia.fandom.com/wiki/Dun_Morogh), and in [Goldshire](https://wowpedia.fandom.com/wiki/Goldshire) in [Elwynn Forest](https://wowpedia.fandom.com/wiki/Elwynn_Forest)

https://i.gyazo.com/cc84206c6fbec12721ad78713f504b44.mp4
https://i.gyazo.com/637e09054dad449702170afd1070b837.mp4
https://i.gyazo.com/701be144849ecebd6adeada0bebf447d.mp4

All quests
![Goldshire](https://github.com/WoWManiaUK/Redemption/assets/39439201/233cf0fe-53ca-43c5-b0a0-b541548982f4)

All auto complete

![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/e4b9a9fe-0b65-4f19-ae03-2dbe1f90ecee)

**Comment by Lumber-Jack-2** [comment]
yeah there is no check for the triggers to add the fire spell

**Comment by Echinaceax** [comment]
> yeah there is no check for the triggers to add the fire spell

What i dont understand is https://github.com/WoWManiaUK/Redemption/issues/3641 this report said "too many fires" so there has to have been a removal of code somewhere coz there are 0 fires enywhere anymore 

trigger bunnies entry 23686
![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/e5ca349e-8bd9-403c-af3f-30e87c10789d)

![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/ff1198af-c1cc-434d-ae72-d0c1f39ddcd8)

**Comment by Lumber-Jack-2** [comment]
-- Event can no longer start if quest was started already <=5 minutes before (it has 5 minutes cooldown)
-- Event can no longer start if there is a Headless Horseman in range
-- Movement for Horseman fixed
-- Spread of Fire on the buildings fixed

**Comment by Echinaceax** [comment]
- Quest order also fixed for now 

Fix confirmed 
Fires and movement https://i.gyazo.com/a1bfa659fb7d9152006cd1b73eca8920.mp4

![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/4f6fd9dd-6499-46b6-9e7d-1399436fa9a8)
