### ISSUE TITLE
[Item/spel] Goblin Mortar - Missing/Wrong requirement

### ISSUE THREAD

**Issue by WhitephoenixTheBunny** [WoWManiaUK/Redemption#4400]
The item [Goblin Mortar](https://www.wow-mania.com/armory/?spell=12716#conditions) already was reported before #1357 and #1409 

![image](https://user-images.githubusercontent.com/31921098/78938719-9de0b600-7aaa-11ea-8b67-e34327871c83.png)

Note, this was tested on PTR

The issue is the same, having the "correct" requirements:
Spectialzation 
![image](https://user-images.githubusercontent.com/31921098/78938577-607c2880-7aaa-11ea-98f2-506d0d5a5a74.png)

Character level
![image](https://user-images.githubusercontent.com/31921098/78938605-696cfa00-7aaa-11ea-8d48-e2682881ddfd.png)

Skill level
![image](https://user-images.githubusercontent.com/31921098/78938660-81447e00-7aaa-11ea-9f54-83fc77581cc3.png)

and corrects mats
![image](https://user-images.githubusercontent.com/31921098/78938694-91f4f400-7aaa-11ea-99e7-fb2408b1f5d8.png)

this the message I get:

![image](https://user-images.githubusercontent.com/31921098/78938761-bc46b180-7aaa-11ea-88f8-1a943f3a8068.png)

On wow mania armory, this is one of the requirements: 
![image](https://user-images.githubusercontent.com/31921098/78938824-d97b8000-7aaa-11ea-952d-bb4939e3ef98.png)

Redirecting to Quest 3633
https://www.wow-mania.com/armory/?quest=3633

When looking up the quests "goblin engineer" this is what is shown

![image](https://user-images.githubusercontent.com/31921098/78938969-252e2980-7aab-11ea-94f3-5f4a3c8fc67e.png)

There's 4 quests starting the questline and those 4 **should** count as requirement - no matter where you start the quest.

(I hope I explained well myself)

**Comment by jeyrella** [comment]
Confirmed.  These are different quests from 4 different starting area NPCs that are all Goblin engineers, they should all count as meeting the requirement.  This explains the previous tickets.

**Comment by Rushor** [comment]
added the other quest: https://user-images.githubusercontent.com/31921098/78938969-252e2980-7aab-11ea-94f3-5f4a3c8fc67e.png to the condition.

if more quests in condition are missing let me know. i will add.

**Comment by WhitephoenixTheBunny** [comment]
![image](https://user-images.githubusercontent.com/31921098/79042149-31ba9b00-7bed-11ea-94a4-e2e564257d36.png)
have you added those 4 quests?

**Comment by jeyrella** [comment]
- [ ] 3526
- [x] 3629
- [ ] 3633

**Comment by jeyrella** [comment]
3629
![image](https://user-images.githubusercontent.com/46089380/79043743-12c20600-7bf9-11ea-8723-b0469587cf1d.png)

3633
![image](https://user-images.githubusercontent.com/46089380/79043799-751b0680-7bf9-11ea-9039-bb19929a26ee.png)
![image](https://user-images.githubusercontent.com/46089380/79043821-94b22f00-7bf9-11ea-96c7-893bab98f9b6.png)
![image](https://user-images.githubusercontent.com/46089380/79043915-2e79dc00-7bfa-11ea-9956-352a11c28a42.png)
