### ISSUE TITLE
[Spell] Duplicate Teleport and Portal Spells to Shattrath

### ISSUE THREAD

**Issue by cathyr1** [WoWManiaUK/Redemption#4401]
Links
https://www.wow-mania.com/armory/?spell=35715
https://www.wow-mania.com/armory/?spell=35717

As the horde mage I should have only the ones linked below in my spellbook. However, I have a duplicite still in my spellbook, even after ticket No. #4297 is shown as fixed. How to refresh to remove one of each spell to Shattrath?

![Teleport](https://user-images.githubusercontent.com/30184491/78973043-580a0900-7b0f-11ea-969e-e3851aab2574.png)
![Portal](https://user-images.githubusercontent.com/30184491/78973056-5b9d9000-7b0f-11ea-8cc2-066e5b511377.png)

**Comment by wow-mania** [comment]
This is a side effect of an error with the vendor.
I will sort it.

**Comment by cathyr1** [comment]
There are 2 levels but should be only one, like as for alliance mage who learned this recently.
![Portal](https://user-images.githubusercontent.com/30184491/78984602-f6559900-7b26-11ea-96ec-b94145060dcb.png)
