### ISSUE TITLE
[Spell]Frost Presence DK does not give stamina increase 

### ISSUE THREAD

**Issue by Anirsb** [WoWManiaUK/Redemption#4402]
i just created a DK last night on redemption, Deathksb, and when i switch from blood to frost presence i get increased armor but i dont get increased stamina...

**Comment by svijetlo** [comment]
UH DK- naked wo gear or pet in blood presence 228 stamina , going to frost 246 stam by simple math we get increase of cca 18 stamina (8% of 228 228 / 0.08 =18.24), so it is working as intended  or i can not reproduce this problem 
alos armor benefit works perfect

**Comment by Anirsb** [comment]
blood presence 463 stamina 5295 armor
frost presence 463 stamina 8243 armor

conclusion armor is working fine stamina is not check it out again pls

________________________________

**Comment by svijetlo** [comment]
did check on ptr and on live works fine to me might be smt local to you as it is not server side i even made fresh toon on ptr to test worked fine

**Comment by squalllh1989** [comment]
![image](https://user-images.githubusercontent.com/27235989/78989116-dccf4400-7b5c-11ea-841f-7ed604a2dcc0.png)
![image](https://user-images.githubusercontent.com/27235989/78989146-f4a6c800-7b5c-11ea-87e8-45f89b27e270.png)

Stamina in blood/ UH presence: 2163
Stamina in frost presence: 2336
2163 + (2163*8% = 173) = 2336 => work

**Comment by svijetlo** [comment]
ok 
i just did more research in to this 
so what i did with new toon this morning is i made me self lvl 80 and it worked 
and on my old DK lvl 80 it worked 
but i made other new toon gave it 1 by 1 lvl up after i did learn frost presence it did not give me 8% stam increase so it need to be looked it as it only happens to newly made toons that are lvling atm on server , it is very recent thing as we just got reports of it

**Comment by Keader** [comment]
Hey guys, everything fine?
I cant find any problem with the spell.
Remember, if you have Improved Frost Presence talent, it will give you 8% stamina in ALL presence.

**Comment by Keader** [comment]
8

**Comment by svijetlo** [comment]
fml , i never used that talent before so i did not even bother to read it XD 
you are actually right , problem is person specking smt not for dps rly
