### ISSUE TITLE
[Quest] Attacking NPC's dissapear during Sniffing Out the Perpetrator

### ISSUE THREAD

**Issue by yani** [WoWManiaUK/Redemption#4403]
**Links:**
Current behavior of NPC's: https://www.youtube.com/watch?v=I-ger9-mV-8
Correct behavior of NPC's: https://www.youtube.com/watch?v=aypXfa20lNI
https://www.wowhead.com/quest=12910/sniffing-out-the-perpetrator

**What is Happening:**
The NPC's that attack you while you ride Frostbite during [Sniffing Out the Perpetrator](https://www.wowhead.com/quest=12910/sniffing-out-the-perpetrator) disappear after they spawn and attack you once.

**What Should happen:**
They should follow you faster than the mount goes and attack you while you should fend off the attacks.

**Comment by wow-mania** [comment]
Maybe a corner case related to something you did. Pretty sure this works. In any case, we will check and confirm. Thank you.

**Comment by yani** [comment]
The first time I went to the cave directly without mounting Frostbite. After I killed Tracker Thulin I flew back and mounted Frostbite. Then I saw the bug. I abandoned the quest and restarted it with the same issue.

**Comment by Rushor** [comment]
They should be active or have longer spawn time. That issue is quite old. We also need to incease the movement speed of them :)

**Comment by svijetlo** [comment]
can confirm i just did it basically you are much faster then them so they "give up"

**Comment by Rushor** [comment]
they will attack and follow a bit now. it cannot be done better. but the solution should be good enough :)

**Comment by svijetlo** [comment]
much better
