### ISSUE TITLE
The Oculous: Varos Cloudstrider Unkillable

### ISSUE THREAD

**Issue by Owen-TG** [WoWManiaUK/Redemption#4404]
**Links:**https://www.wowhead.com/npc=27447/varos-cloudstrider

**What is Happening:**
After Killing the 10 Centrifuge Contructs the party will go to fight him, only for his shield to not have dropped. He is immune to all damage and cannot be killed, forcing the dungeon to end early as it cannot be completed.
(It is not always consistant,I am farming Rhc daily to try and get the mount on my Alliance character Rooibostea, it has happened to me 3 times in my last 5 attempts. The only thing that stood out is that in our last attempt someone left during the dungeon and rdf found a replacement. I cant remember if it happend in the other bugged attempts)

**What Should happen:**
After killing the 10 Centrifuge constructs Varos should be vulnerable to damage, and thus killable

**Comment by wow-mania** [comment]
Need tester testing. Unlikely that is a common/generic issue.

**Comment by Rushor** [comment]
i tested that aswell last night, could not reproduce so far - needs more digging

**Comment by svijetlo** [comment]
i em on it atm and i can dmg it wo problem did few trys idk what might be issue

**Comment by squalllh1989** [comment]
i already reported this, and also made 2 video of what is happening on redemtion right now: https://github.com/WoWManiaUK/Redemption/issues/4396
the 2 video that i made: 
https://youtu.be/Hdiy4_njgV0
https://youtu.be/icadoV-kQMw
All we did is just as alway: clear the way to first boss, kill him, kill all refuge along with the mage with them, then go to the boss

**Comment by Rushor** [comment]
maybe is related to the reduced visibiliyt distance hm?

**Comment by svijetlo** [comment]
ok do me favor , in most cases some one went offline or left group /dung , does it efect the count of big robots things killed cos of that i need more ppl to tets that posibilty and cant cos i em bit bussy , it might be smt with dung raid lockout thing

**Comment by wow-mania** [comment]
visibility for pve is unchanged

**Comment by svijetlo** [comment]
it is not load distance i can see thing form 40+ yards in that dung

**Comment by wow-mania** [comment]
If it cannot be reproduced just close it please.

**Comment by svijetlo** [comment]
i rly do not know what to do anymore i even went to it on live and works for me , im rly sorry

**Comment by Rushor** [comment]
tested on ptr aswell again https://i.imgur.com/ejRRIBg.jpg hmm. all good there
