### ISSUE TITLE
Mage animation bug

### ISSUE THREAD

**Issue by Creedpt** [WoWManiaUK/Redemption#4405]
**Links:**

**What is Happening:**
When the class ( at least mine) the animation only on one hand rather on both hands.

**What Should happen:**
It needs to be able to see the cast on both hands.
Ex: Casting frostbolt only appears in one hand ( the little blue on hads)

**Comment by wow-mania** [comment]
if you don't specify more clearly with images we have no idea of what you are saying.

**Comment by Creedpt** [comment]
Normal animation : https://imgur.com/a/nzljtL3

What is doing now : https://imgur.com/a/YbpW7u2

**Comment by wow-mania** [comment]
As-is. We are not changing that.
Thanks for the report.
