### ISSUE TITLE
Teleport between dimensions while flight master mounted causes bug. (Shattrath)

### ISSUE THREAD

**Issue by lolneylsesses** [WoWManiaUK/Redemption#4406]
**Links:** No screenshots yet.

**What is Happening:** When you are below level 58 and go to Shattrath City through the portal at the mall, when you exit the city, it should teleport you to the location of your Hearthstone. However, when using Shattrath's Flight Master NPC to fly to a pre-unlocked area in Hellfire Peninsula (different for horde and alliace), you exit the city to fly there, and get teleported back to your Hearthstone,  But the bug is, you keep being mounted on the Flight Master mount while teleporting, causing you to fly through the floor, through mountains and objects, through the sea barrier and you can only exit the mount when the flight ends, bringing you to a location on Azeroth based on the coords of the flight location in Outlands.
I think the cause of the bug is because flight route coords stay the same between dismensions and teleporting between Outlands and Azeroth while en route does not dismount you from undismountable mounts.

**What Should happen:** If you're too low level, using the Flight Master on Shattrath City should take you out of the city, you should get teleported to your Hearthstone location, but dismount from the Flight Master mount, or just disable the ability for low level players to interact with that NPC.

**Comment by svijetlo** [comment]
it is setting on server that before lvl 60 you can not go to outland

**Comment by wow-mania** [comment]
AS-IS
