### ISSUE TITLE
[Raid] ICC - Spinestalker - immunities 

### ISSUE THREAD

**Issue by bLeyaa** [WoWManiaUK/Redemption#4407]
@Rushor  Addition to #4281 

The NPC(s) missing immunities to the below:
Arcane Torrent - Spell ID: 28730 / 25046 / 50613
Thunderstorm - Spell ID: 59159
Silencing Shot - Spell ID: 34490

If you can, please also check: 15487 and pet ability 19647
I believe these two i missed when i was checking on the initial report.

**Comment by Rushor** [comment]
try now after server restart (check dev test channel)

**Comment by bLeyaa** [comment]
@Rushor Rimefang is not immune to Thunderstorm anymore. Was on horde toon in 25 man normal difficulty for what it matters.
