### ISSUE TITLE
Tagging mobs

### ISSUE THREAD

**Issue by bLeyaa** [WoWManiaUK/Redemption#4408]
**Links:** https://youtu.be/LnBzbXCBREY

**What is Happening:** Currently the mobs are being tagged by certain spells, without even being hit. An example given in the video where Hunter's Mark spell would tag the creatures upon casting even though no damage was caused. If Hunter's Mark is used on another creature afterwards, the previous one still remains tagged. Tag persists through logout of both hunter and other players.

**What Should happen:** Mobs should only be tagged after being actively hit. If another player has engaged a creature at some point and never killed it but left, the creature should reset and credited for kill/xp/loot to whoever initiates it again.

I am unsure if there are any other spells causing this to happen, but i've seen many mobs in popular leveling areas being tagged, causing headache to players questing & leveling up.

**Comment by Keader** [comment]
rdy to test.

**Comment by bLeyaa** [comment]
Works fine for Hunter's Mark now.

I think I've seen the same effect from rogue's Sap, would this fix include that as well?

**Comment by Keader** [comment]
nope, need report all spells that have it.
