### ISSUE TITLE
Finding Fish

### ISSUE THREAD

**Issue by allanjchiang** [WoWManiaUK/Redemption#4409]
**What is Happening:** My character's Finding Fish button is stuck on the minimap. I can't change to other searches. When I try to use 'Find Minerals' it doesn't work, it just stays on 'Finding Fish'

**What Should Happen:** When I use 'Find Minerals', it should change to 'Find Minerals' on the minimap.

**Comment by Aristo14** [comment]
Try Clearing cache and restart using launcher and no addon's. 
This is not a client side issue.
