### ISSUE TITLE
Refer a Friend "Grant Level" Problem

### ISSUE THREAD

**Issue by Klickslave** [WoWManiaUK/Redemption#4411]
**Links:**

**What is Happening:**

I registered a Account , Friend of Mine registered after me , i sat beside him and dictated the code , checking if he is doing right. He entered the Code correctly. After founding a Party ingame , we met near Thunderbluff via Summoning (which worked well). After that i tried to grant him a Level , which did not work after all. I made sure that we meet all the requirements mentioned on the Mania Website but everytime im clicking on "Grant a Level" it keeps telling me that "You were not referred by that player". Even after contacting a GM , who confirmed that we associated correctily via Code , it was not possible to grant my Friend a Level. GM did not found the Failure and told me to try to logoff , which we did. We also cleared cache via Launcher. Even with just 4 Levels difference the "Grant a Level" Funtion does not work.

**What Should happen:**
When pressing "Grant a Level" the Friend of Mine should gain 1 Level instantly , this should be working as long as we meet the Requirements :

Be in a group with your friend
Be within 4 levels apart from eachother
Be lower than level 60

*We noticed that its only possible to grant a Level once u made 2 Levels "on your own" , we tried this from Level 10 to 19 several times.

![WoWScrnShot_041120_055255](https://user-images.githubusercontent.com/38255320/79034906-ae338680-7bb9-11ea-8ced-5be47af727f2.jpg)

**Comment by Aristo14** [comment]
The recruiter can't grant levels, the recruited should be able to. 

![Screenshot_1](https://user-images.githubusercontent.com/38132718/79040123-93c3d200-7be6-11ea-9ba4-e62e5d8d0a91.png)
