### ISSUE TITLE
Area Chat channels are not joined when logging in

### ISSUE THREAD

**Issue by yani** [WoWManiaUK/Redemption#4412]
**What is Happening:**
When you log in, you are not added to the chat channels of that area. For example, logging in while in **Dalaran** does not put you in **General - Dalaran**. 

It does however work when entering the area ingame. When in Dalaran and not in the chat channel, teleporting to Dalaran puts you in the chat channel.

**What Should happen:**
I think you should automatically join the chat channels of the area where you are when you log in.

**Comment by Sharuzan** [comment]
This is a bug. 

When logging in, the player wont be joining the general chat channel in any zone, before they move; but as soon as they do, they join the channel. 

When logged into capitols or inns, the player wont be able to access the general channel, unless they leave the capitol.
Leaving an inn inside a capitol doesn't make any difference. 

In both cases during testing, there was no way to even join the general channel by command. Tested on PtR and Live.

**Comment by svijetlo** [comment]
![image](https://user-images.githubusercontent.com/61908373/79067287-8a0d9d80-7cbe-11ea-9821-34ef5872323b.png)
on log in
