### ISSUE TITLE
[Raid] TOC - Massive Crash targeting (Icehowl)

### ISSUE THREAD

**Issue by bLeyaa** [WoWManiaUK/Redemption#4413]
**Links:** https://youtu.be/oEcCItDmIz0?t=332

**What is Happening:** After the boss jumps to the middle of the arena, raid is not being notified as to who is being targeted by Icehowl.

**What Should happen:** There should be a notification shown to players who is being targeted for the charge.

Note: This is **_NOT_** related to an addon, but an in-game notification.

My guess is that this happens because the boss keeps targeting the tank even after the jump, if you look at the video, he is supposed to drop target, announce who is he going to charge and then go for it. If he's stunned then he will target the highest aggro after it's done. If he's enraged he will target the last highest aggro before the jump (aka tank).

Worth mentioning, the only time i've managed to reproduce this to actually work as it should was after i've let several jumps to be made (lot more than it would usually take the raid to down the boss). Sadly i have not counted after how many jumps would it trigger to work as it should.

**Comment by wow-mania** [comment]
There was no server crash. Also, most of these crashes are due to someone in the group not using our client.

**Comment by Keader** [comment]
![image](https://user-images.githubusercontent.com/7120913/79048416-49951d80-7bf3-11ea-8f69-75fc9db12f25.png)

Fixed

**Comment by tvshadowz** [comment]
![WoWScrnShot_041120_164217](https://user-images.githubusercontent.com/30256554/79055530-6ccfc500-7c13-11ea-8ffe-45ba4f994b7b.jpg)
