### ISSUE TITLE
Icecrown Gunship Battle - Muradin & Saurfang damage values

### ISSUE THREAD

**Issue by bLeyaa** [WoWManiaUK/Redemption#4414]
**Links:** /

**What is Happening:** Gunship Battle bosses do not deal enough damage.

**What Should happen:** This is a troublesome issue to report because I've had great difficulty in finding hard, objective data on what Muradin and Saurfang should be doing damage wise. That being said, the issue is simple: the incoming damage on the commander tank is way, way too low on both 10 and 25 difficulties

Staying over for two entire Below Zero phases should require significantly outgearing the encounter or chaining external CDs. Muradin's & Saurfang's damage is intended to be threatening to tanks after just one Below Zero phase finishes, killing you if you stay too long. However, here, the incoming damage is pitifully low. Muradin & Saurfang can actually reach 99 stacks. Surviving to 99 stacks should be hilariously impossible. This bug means that the encounter, which is already obviously one of the easiest in ICC, is practically impossible to fail unless your entire group commits suicide on purpose. The encounter should stress healing and tanking on undergeared groups, and put pressure on the mage DPS team to finish their target quickly and return. As it is now, you could have a DPS team remain on the enemy gunship for the entire battle. This shouldn't be possible just by face tanking Muradin or Saurfang to 99 stacks.

https://www.youtube.com/watch?v=7EjS6Zq7Rvc

In this video you can hear the tank announce that he'll call for people to head back at 15 stacks, because at that point the boss is doing dangerous amounts of damage. You can also see the significant amount of incoming damage after just one Below Zero phase.
In several other videos and guides you will see tanks jumping back after each mage, if needed i can link them here as well.

This bug may be due to Battle Fury incorrectly modifying Muradin's & Saurfang's damage, so that it scales up poorly, or it may be due to a wrong autoattack value, or weapon damage value so that his Cleave is improperly weak.

**Comment by bluemonstrr** [comment]
You realize the people in the video are in t9 right?

**Comment by bluemonstrr** [comment]
If you can bring the proper values to show that it is bugged I'll reopen the report

**Comment by bLeyaa** [comment]
You realize 99 stacks is 700% damage increase?

Here's a video with full heroic geared people, just farming the bosses at this point.
They do not jump until the first mage, and reset after its dead.
https://youtu.be/3gQUlfMTCDw?t=375

**Comment by bLeyaa** [comment]
At the above video you can also see how tank's health is dropping at only around 20 stacks. 
08:32, group 3 paladin Toastyroach.
