### ISSUE TITLE
[Raid] Icecrown Gunship Battle - Cannon damage

### ISSUE THREAD

**Issue by bLeyaa** [WoWManiaUK/Redemption#4415]
**Links:** [Alliance Gunship Cannon](https://www.wow-mania.com/armory/?npc=36838) / [Horde Gunship Cannon](https://www.wow-mania.com/armory/?npc=36839) 
[Cannon Blast](https://www.wow-mania.com/armory/?spell=69399) / [Cannon Blast](https://www.wow-mania.com/armory/?spell=70172)

**What is Happening:** 
1. Cannons do not deal damage to the Axethrowers and Riflemen on the enemy ship.
2. Cannon Blast deals 1000 damage per hit.

**What Should happen:** 
1. Damage dealth to the ship should also affect the nearby Axethrowers Riflemen. (https://youtu.be/WBAnLhFk2EE?t=154)
2. Cannon Blast should deal 1500 damage per hit.

Worth checking is the [Incinerating Blast](https://www.wow-mania.com/armory/?spell=70174) / [Incinerating Blast](https://www.wow-mania.com/armory/?spell=69401) if they're affected by the change in Cannon Blast damage. I couldn't find any information on how the Heat scales with added damage done.

**Comment by Rushor** [comment]
maybe 1000 in nh and 1500 in hc?

**Comment by tvshadowz** [comment]
1. Cannon damage does not currently do damage to the adds on the enemy ship. 
2. Cannon blast currently does 1k damage as compared to 1.5k 

![WoWScrnShot_041120_163541](https://user-images.githubusercontent.com/30256554/79055446-c5eb2900-7c12-11ea-944e-cb1cf6200c1f.jpg)

**Comment by Keader** [comment]
try now

**Comment by tvshadowz** [comment]
1st skill does 1.5k damage and hits the adds on the ship 
2nd kill doesn't hit the adds but this may be intended
