### ISSUE TITLE
25HC Festergut malleable goo not showing

### ISSUE THREAD

**Issue by helperdude** [WoWManiaUK/Redemption#4416]
**Links:**

**What is Happening:**
The malleable goo on the ground doesn't show up. PP also doesn't throw the malleable goo.

**What Should happen:**
The opposite of what is not happening.

**Comment by helperdude** [comment]
Might have been a one time thing from having my render distance reduced.

**Comment by Keader** [comment]
Invalid, working fine.

**Comment by bLeyaa** [comment]
@Keader 
Just had it happen to me as well in 10 heroic. Another priest was affected with this as well.

**Comment by Keader** [comment]
Gimme a repro steps

**Comment by bLeyaa** [comment]
Fight boss, get hit out of nowhere? lol

Notable thing is that we had PP stuck at the edge when we were going for him after that. Maybe related?
