### ISSUE TITLE
The Ocular: Untargetable

### ISSUE THREAD

**Issue by Winslow221** [WoWManiaUK/Redemption#4417]
**Links:**

**What is Happening:**
At the Ocular in Icecrown it seems to be impossible to target it for the quest [It's All Fun and Games]. It should be targetable so you are able to use the item [Eyesore Blaster] to take it down

**What Should happen:**

**Comment by jeyrella** [comment]
works fine.

![image](https://user-images.githubusercontent.com/46089380/79054198-e333ed80-7c3a-11ea-98b0-8a3ba4b319c5.png)

**Comment by jeyrella** [comment]
Suggestions to try:  make sure you use launcher, have a patched client, clear your cache.

**Comment by Aristo14** [comment]
Probably was targeting the wrong one.. Make sure you go all the way up ;) 

(the one Jeyrella is attacking in the picture)
