### ISSUE TITLE
[Raid] RS Halion Cutter Cutter Positions

### ISSUE THREAD

**Issue by slaniaxx** [WoWManiaUK/Redemption#4418]
**Links:**

**What is Happening:**
Halion cutters are placed oddly.

**What Should happen:**
at heroic mode, halion cutters should form an X or a "+" sign, crossing each other.
![haly](https://user-images.githubusercontent.com/45994511/79054378-f2239b80-7c4c-11ea-959b-bb744b45ddd6.png)

**Comment by squalllh1989** [comment]
is this happen every attempt ? we just kill hallion like 2,5 hours before and doesn't have any trouble with the cutter being like this.

**Comment by tvshadowz** [comment]
![WoWScrnShot_041120_162456](https://user-images.githubusercontent.com/30256554/79055235-0e094c00-7c11-11ea-8fcd-f3b541c78797.jpg)

Looks fine on the test server

**Comment by bLeyaa** [comment]
It's only visual though. I've had the same appear to me, but the one that is "missing" is only visual. Not sure if it's related to delay or rendering distance by any chance, as i couldnt reproduce it on PTR either.... But definitely had the same thing happen to me as well.
