### ISSUE TITLE
[Core] Melee line of sight issues near walls

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#4419]
**Links:**

**What is Happening:** If a player tries to attack an enemy while being very close to a wall (back directly against wall is the best way to reproduce), a 'target not in line of sight' error will happen. The bigger the enemy's hitbox, the easier it is to get the error. It seems as though walls had an 'invisible thickness' and that being too close to them is the same as being inside the wall, making it impossible to melee through it. Moving away from the wall can fix this, but often tanks have to bring bosses against walls while keeping their backs faced to the raid and it is made a lot more difficult with this.

**What Should happen:** Unless an object/wall is present in between a melee player and his target, no 'line of sight error' should happen.

**Comment by bluemonstrr** [comment]
I reported this a few years ago and Maniac told me they did what they could. It helped a little, but not sure if anything else can be done.

**Comment by Oganku** [comment]
Couldn't find the previous report, sorry if it's redundant.
