### ISSUE TITLE
[Dungeon/NPC] Violet Hold Heroic mobs missing loot tables

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#4420]
**Links:**https://www.wowhead.com/the-violet-hold#npcs
https://www.wowhead.com/npc=32191/azure-stalker#drops:mode=heroic
https://www.wowhead.com/npc=30668/azure-raider#drops:mode=heroic
https://www.wowhead.com/npc=30892/portal-guardian#drops:mode=heroic
https://www.wowhead.com/npc=30695/portal-keeper#drops:mode=heroic
https://www.wowhead.com/npc=30666/azure-captain#drops:mode=heroic
https://www.wowhead.com/npc=30667/azure-sorceror#drops:mode=heroic

**What is Happening:** All of the Violet Hold trash mobs (all listed above) are missing their loot table for the heroic version. Normal is fine.

**What Should happen:** These mobs should have the loot tables listed above.

**Comment by wow-mania** [comment]
Creatures have loot and are working for me
