### ISSUE TITLE
Judgement of Light

### ISSUE THREAD

**Issue by allanjchiang** [WoWManiaUK/Redemption#4421]
**Links:**
https://www.youtube.com/watch?v=UjVPEbDEAws&feature=youtu.be

**What is Happening:**
Judgement of Light icon appears greyed out and when I try to use Judgement of Light, it says 'You can't do that yet.'

**What Should happen:**
I should be able to cast Judgement of Light.

**Comment by Oganku** [comment]
You need to use a seal buff
