### ISSUE TITLE
[Dungeon] Varos Cloudstrider

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#4422]
**Links:** #4404
https://www.wowhead.com/npc=27447/varos-cloudstrider

**What is Happening:** If any member of the rdf group leaves or is replaced at any point inside The Oculus before fighting the second boss, Varos Cloudstrider, it will be impossible to engage him. We had the tank go offline at the very start, replaced him, and then did the instance as normal. After clearing all 10 sentries, we went to Varos and he was untargetable.

**What Should happen:** Varos should be killable when all 10 sentries are killed, no matter party size or history.

**Comment by svijetlo** [comment]
porblems with this boss were before reported i been suspecting it is this reason tho could not find ppl to test it out

**Comment by squalllh1989** [comment]
well, i don't think this is related to people quit the queue, as you can see before, i made 2 video of the 2 case that i got a bugged varos, in both case, none of the member in my party quit, so it's the party of  5 from the beginning, problem is something else. And this seem to be random, as for the last 5 day, i get this dungeon 5 time, 4 is bugged which i did the report, but the last one i did yesterday didn't.

**Comment by svijetlo** [comment]
in one of your vids i seen some one go offline while you were killing those robots , so far that was only common thing to every dung where problem with this boss happen, so far it is only lead i have , and i test it today with 3 of my accounts that one leave dung or crash and it still worked fine

**Comment by squalllh1989** [comment]
yeah i didn't notice that, but that probly just a dc/crash and he quickly come back online, and the 2nd one doesn't have any dc/ leaver there

**Comment by Rushor** [comment]
added a tiny check for the constructs. if all of them are killed, boss should always loose his shield aura.
