### ISSUE TITLE
[Dungeon/Achievement] Trial of the Champion 5 person NM/HC Horde 

### ISSUE THREAD

**Issue by svijetlo** [WoWManiaUK/Redemption#4423]
**What is Happening:**
Trial of the Champion 5 person NM/HC Horde does on give ach for defeating 1st wave group of bosses that come on mounts , even after you beat them in ground combat . NOTE: other fight count properly , as seen in img 
![image](https://user-images.githubusercontent.com/61908373/79068590-63ecfb00-7cc8-11ea-99d6-3593c35ce09c.png)

**What Should happen:**
After defeating bosses in ground combat and 1st encounter ends one/group should get them listed in achievements  as completed , ofc not all of them but 3 you got in that encounter

**Comment by wow-mania** [comment]
THis is a dupe
