### ISSUE TITLE
[VIP] Revive command does not work

### ISSUE THREAD

**Issue by yani** [WoWManiaUK/Redemption#4425]
The `.vip revive` command often does not work. It mostly says:

```
You can't chat when you are dead!
```

I posted a fix on the forums:
```
/w @ .vip revive
```
S: https://www.wow-mania.com/forum/viewtopic.php?f=12&p=799

This one works all the time and the wisper will not bother anyone because there will not be a character with that name. It also does not give any warning so it's nice to have as a macro. 

I do however think the original command should go past the dead chat filter.

![image](https://user-images.githubusercontent.com/6956790/79080500-b6083d80-7d15-11ea-870b-8660db419718.png)

**Comment by bLeyaa** [comment]
This is not a bug, as-is.
This is how the game was made, you cannot write in /s while dead. 

To avoid it you can use guild/raid/party chats as well, even if you're not in either of mentioned as the message will not go through but the command will.

**Comment by wow-mania** [comment]
you cannot do /w you need to enter the chat field and directly type .vip rivive.
