### ISSUE TITLE
[Core/Spells] Spells with SPELL_ATTR3_NO_INITIAL_AGGRO tapping creatures

### ISSUE THREAD

**Issue by Keader** [WoWManiaUK/Redemption#4427]
Spells with SPELL_ATTR3_NO_INITIAL_AGGRO should not tapping creatures.
Same case of : https://github.com/WoWManiaUK/Redemption/issues/4408
It will fix cases like Sap, like reported here: https://github.com/WoWManiaUK/Redemption/issues/4408#issuecomment-612547857

Only damage spells should tapping creatures.
PS: Tapping means: make player owner of loot / XP

**Comment by bLeyaa** [comment]
@Keader 
Polymorph / Cyclone / Fear / Wind Shear / Blind / Hammer of Justice / Psychic Scream

All of these currently tag the mob without doing any damage. Not sure if intended (believe not), but for now at least the creatures do not remain tagged after they reset.
