### ISSUE TITLE
[NPC] NPC Thassarian and Chief Engineer Boltwrench are missing

### ISSUE THREAD

**Issue by mimiklo** [WoWManiaUK/Redemption#4428]
NPC Thassarian ( https://www.wow-mania.com/armory/?npc=29799 ) and Chief Engineer Boltwrench ( 
https://www.wow-mania.com/armory/?npc=30345 ) are missing on Skybreaker ship. Talked to GM Brontus and he confirmed that they are missing.

https://imgur.com/Ql6s3s6 
https://imgur.com/UdzAexY

**Comment by wow-mania** [comment]
It is there. Sometimes they disappear for a while (maybe toilet) but they always come back.

**Comment by svijetlo** [comment]
yes i just did check on test he is there on live not there so it will be back, seen it desapier sometimes before he will be back

**Comment by svijetlo** [comment]
@mimiklo  it is back to his place lunch brake is over :D
