### ISSUE TITLE
Keristraza (Nexus)

### ISSUE THREAD

**Issue by GM-Osyris** [WoWManiaUK/Redemption#4429]
**Links:**
https://cdn.discordapp.com/attachments/697519727525888025/699243681500364800/WoWScrnShot_041320_144237.jpg

https://cdn.discordapp.com/attachments/699248038958333962/699251876901945464/WoWScrnShot_041320_151022.jpg

**What is Happening:**
Keristraza is not resetting correctly if party wipes. She is frozen and is unable to be attacked if party wipes

**What Should happen:**
Boss should reset if party wipes. Party should be able to re-engage her.

**Comment by Sharuzan** [comment]
<img width="764" alt="nexus" src="https://user-images.githubusercontent.com/47272908/79126248-e4caf600-7d9f-11ea-8ac8-994867ac324b.png">

Keristraza freezes where the player is killed and doesn't reset it's position.

**Comment by Rushor** [comment]
Will fix

**Comment by Rushor** [comment]
should be fixed :) on reset if boss was activated once he will not go in ice state again.
