### ISSUE TITLE
Strand of the Ancients gate bug

### ISSUE THREAD

**Issue by Kinkywiener** [WoWManiaUK/Redemption#4430]
**Links:**

**What is Happening:**
If the player is not in proximity of the gate destroyed by the sieges, the gate stays intact, but for the players who were in close enough, the gate is destroyed. Therefore, the players who joined late/were on the other side of the shore, cannot pass through the already destroyed gate. This affects mainly attacking faction, as defending faction can still use the teleporter. If you find yourself in this situation as the attacker and you have no siege left, youre left stranded.

**What Should happen:**
Gates should be destroyed for each player, regardless of the distance from the gate when destroyed.

**Comment by Rushor** [comment]
try now. i know that issue from live realm

**Comment by Aristo14** [comment]
Went live without confirmation, please test if fix is confirmed for posible future refference.
