### ISSUE TITLE
Dahlia's  Tears

### ISSUE THREAD

**Issue by Telmarine** [WoWManiaUK/Redemption#4431]
Starting off, I'd like to point out I am using the most current launcher for WoW Mania and my version is 2.6.0

I submitted a GM's Ticket and was aided by Divigrac who confirmed the issues and requested I submit a bug report.

[Convo with Divigrac.txt](https://github.com/WoWManiaUK/Redemption/files/4472613/Convo.with.Divigrac.txt)

**Links:**
Quest: [Dahlia's Tears](https://www.wowhead.com/quest=13078/dahlias-tears)

**What is Happening:**
The Ruby Keepers are severely bugged. Their pats are insanely small or they are getting stuck in to the terrain. Bringing mobs to kill as per the questline is not causing the Keepers to aggro or trigger. We actually had to drag a mob to directly underneath its feet just for the dragon to aggro and attack the mob. However, instead of burning the mob as per the quest scripts, the Keepers simply attack them and the quest item, [Dahlia's Tears](https://www.wowhead.com/item=43084/dahlias-tears), finally spawns.

**What Should happen:**
There should be only a few of the Keepers flying about. Once a mob is brought underneath them, the Keeper is supposed to burn them with fire, and spawning the quest item.

**Comment by Rushor** [comment]
There are several scripts missing. Added pathig improvement and an OOC spawnevent with waypoints for all the hostile spawns on horde and alliance side.

**Comment by Aristo14** [comment]
Went live without confirmation, please test if fix is confirmed for posible future refference.

**Comment by svijetlo** [comment]
imo works fine , some mobs can clip to ground or smt but Janitor told it is core issue so dont bother with that
