### ISSUE TITLE
Lay on Hands

### ISSUE THREAD

**Issue by bLeyaa** [WoWManiaUK/Redemption#4432]
**Links:** http://www.wow-mania.com/armory?spell=48788

**What is Happening:** Lay on Hands currently does not benefit from any healing modifiers and does not crit.

**What Should happen:** Lay on Hands should be able to both crit and benefit from healing modifiers (both positive and negative).

https://www.mmo-champion.com/threads/904193-Can-Lay-on-Hands-Crit
https://www.youtube.com/watch?v=Fost7trWHw0 - pause at 06:19 you'll see the amount healed from Lay on Hands

**Comment by GMMetaxa** [comment]
![image](https://user-images.githubusercontent.com/34750502/79218862-7ba3bb00-7e51-11ea-8243-e1b7b44cb131.png)
 While we're at it, please test it in a PvP envirment too.

**Comment by bLeyaa** [comment]
> It should NOT work in PvP.

That only applies to arena environment, duels / battleground / world pvp it is supposed to work.

**Comment by GMMetaxa** [comment]
Correct, good addition.

**Comment by svijetlo** [comment]
![image](https://user-images.githubusercontent.com/61908373/79223455-a85bd080-7e59-11ea-8eb4-21df36278d5b.png)
![image](https://user-images.githubusercontent.com/61908373/79223528-ce817080-7e59-11ea-800d-e20db378dd59.png)

it can crit in open world and in dung and raids did not test it in pvp , it does get efect by mods that effect healing like foods , glyph etc

**Comment by svijetlo** [comment]
![WoWScrnShot_041420_150706](https://user-images.githubusercontent.com/61908373/79228409-a990fb80-7e61-11ea-8ad2-2bf2bee1fefe.jpg)
this was in duel, in arena you can not use it at all icon is light-grey
