### ISSUE TITLE
[Item - Consumeable][Buff]: Noblegarden Chocolate instant Well Fed.

### ISSUE THREAD

**Issue by Sharuzan** [WoWManiaUK/Redemption#4433]
Links:
https://www.wow-mania.com/armory/?item=44791

What is happening: The item description of the Noblegarden Chocolate consumeable, reads that you must spend at least 10 seconds eating, to get the Well Fed buff that it provides.
The Well Fed bonus activates the moment you right click it.

![WoWScrnShot_041420_115036](https://user-images.githubusercontent.com/47272908/79212104-66c22a00-7e47-11ea-82de-6139f797d65a.jpg)

As shown in the screenshot, I am provided with the buff, before my character even sits down properly.

What should happen: The consumeable should work as it is described in the item description; Players should sit for 10 seconds, before getting Well Fed.

**Comment by bLeyaa** [comment]
There is currently one minute cooldown on eating it, is this supposed to be like that? Looking at wowhead it says 1 second and the shared cooldowns are with other food/drinks consumables. I know its a different patch that wowhead is reflecting to but i havent found any information about this being 1 minute.

Also, a comment from Wowhead:

> By Deru99 (3,534 – 1·7·30) on 2009/04/28 (Patch 3.1.0) |   |  
Something I found out today which should help some of you is that you can eat while running. It won't count as eating it buff or health-wise, but it does count towards the achievement. **So you can eat the chocolates while running around looking for more eggs. You can set them to an actionbar button, or a hotkey and eat while you run, reducing the time away from egg running.**

**Comment by Keader** [comment]
try now dear

**Comment by Sharuzan** [comment]
No real cooldown on PtR between eating now :)

**Comment by Keader** [comment]
What ?

**Comment by svijetlo** [comment]
only problem now is that you must spend 20 sec eating till end of timer basically to get well feed buff from it , only GCD on item as it is suppose to be , truth to be told as i care it is fine

**Comment by Keader** [comment]
ok, try now.
send a new script for it.

**Comment by svijetlo** [comment]
if you sit and eat you must wait till timer run out to get well feed 
but 
if you move as soon you start eating or when ever in time eating you will get well feed

**Comment by Keader** [comment]
sorry, server was not builded.
try now xD

**Comment by bLeyaa** [comment]
Can you also check if it actually restores 2% health every second, as per the tooltip? It doesn't do it on live server atm.

**Comment by jeyrella** [comment]
Kinda pointless now that the event is over....  but hey, there's next year right? :-)

**Comment by bLeyaa** [comment]
Well the original post was made 6 days ago... rip
At least for next year it will be fine 😀
