### ISSUE TITLE
[Boss/ICC] Professor Putricide HC (Unstable Experiment)

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#4435]
**Links:** Related to #4350  
https://www.wowhead.com/npc=36678/professor-putricide
https://www.wowhead.com/spell=70351/unstable-experiment
https://youtu.be/jv93ko3WeK8?t=113

**What is Happening:** The fix applied for Issue #4350 is wrong. As seen in the video linked above, the first kill on retail by Paragon shows them pushing the boss while he is casting [Unstable Experiment](https://www.wowhead.com/spell=70351/unstable-experiment) and they still end up getting only 2 oozes. (1 of each color)
The reference video linked in the previous issue (#4350), the boss actually has time to complete his cast before transition happens, which is why 3 oozes spawn. 

**What Should happen:** If transition is pushed while the boss is casting Unstable Experiment on heroic, the cast is interrupted and no extra ooze is spawned.

**Comment by Rushor** [comment]
Can Tester confirm that? :o

**Comment by svijetlo** [comment]
1st kill was not don i 3,3.5 i em not sure but i think current version is ok need to see for patch notes 
as do to addition of zone buff it made fight much easyer

**Comment by Oganku** [comment]
From the video I see in issue #4350, the Unstable Experiment spawning the first orange is clearly complete before they push, and then he starts casting the transition one after, which results in 2 more oozes. Picture below show patch change history for the fight and Unstable Experiment was never touched.

From https://wowwiki.fandom.com/wiki/Professor_Putricide:
![image](https://user-images.githubusercontent.com/34783736/79309904-0b388080-7ec9-11ea-9f1e-59919ab686af.png)

**Comment by svijetlo** [comment]
you know sir you could be right, i also can not find any data on this, this fix was don by Keader i i would think he has some source evidence of this

**Comment by Oganku** [comment]
That is actually true. So many normal pp fights wipe because the stun happens in a bad timing and multiple puddles grow too large during it. 😲

**Comment by Rushor** [comment]
Pls create an issue with the missing stop of the grow while stunned and assign to me :)

**Comment by Oganku** [comment]
I'll do that

**Comment by wow-mania** [comment]
Will not change this as per explanation on the other issue.
