### ISSUE TITLE
[Boss/ICC] Sindragosa air phase

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#4436]
**Links:** Related to #4282 
https://youtu.be/BJzWK8RvbxY?t=87

**What is Happening:** Sindragosa currently takes-off and lands immediately with no vertical animation or small delay at all. This causes all DBM timers to be off-set by 3s for each air phase, which stacks up. Those timers were made accurate to retail fight experiences. She used to pause far too long before and after taking off, but now does not pause whatsoever and just zooms outward instantly, causing this discrepancy.

**What Should happen:** As seen in the video from the previous issue, Sindragosa flaps her wings about 3 times before actually moving out from the platforms. That short animation of her gaining height takes about 1.5s and added to the identical landing animation, makes the air phase longer by 3s (which would corroborate with the timers).

**Comment by svijetlo** [comment]
this is correct , current sindy fight pushed true by bleeya is not correct at all in timers

**Comment by wow-mania** [comment]
Was this working before?

**Comment by bLeyaa** [comment]
Previously she would stay in the air for too long before the air phase and when landing as well. Now it's a bit faster than it should be, need some middle ground between the previous and current state.

**Comment by svijetlo** [comment]
it is working but it is too fast so after 1st air phase it is broken as every blistering and everything comes bit faster and for each air phase it accumulates so if you can 3rd blistering cold it is 4 sec sooner then timer should be ,
previously it was bit slower to fly up but it was not game braking as only rare ppl can use that to do few more hits for dps , 
i openly did disagree with this change go live tzhe moment it was 1st implemented on test realm

**Comment by Aristo14** [comment]
This fight was better pre-fix indeed. 
Aparently Sindragosa should gain momentum upwards. (thanks Oganku) 

old situation: Sindragosa completely stalled few seconds and then went up. 
current situation: to 'fix' the stall, sindragosa now just speeds up without building any momentum. 

Old situation: 1 or 2 more seconds to hit sindragosa for melee before moving for airphase
Current situation: Discrepency in timers and phases of the fight. 

Fight is still fine to do, marking it as low prio for that reason.

**Comment by svijetlo** [comment]
in tops you can have 2 gcd used before she fly up in old way it was ,

**Comment by svijetlo** [comment]
this is very very very good, lest not touch this fight anymore unless it is so broken that you can not complete it
