### ISSUE TITLE
[Boss/ICC] Professor Putricide Growing Ooze Puddles

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#4437]
**Links:** https://www.wowhead.com/spell=71617/tear-gas#see-also-other
From https://wowwiki.fandom.com/wiki/Professor_Putricide:
![image](https://user-images.githubusercontent.com/34783736/79311560-a0d50f80-7ecb-11ea-9f12-c097c6d21a03.png)

**What is Happening:** The Growing Ooze Puddles spawned periodically throughout the fight keep growing even during the [Tear Gas](https://www.wowhead.com/spell=71617/tear-gas#see-also-other) raid-wide stun.

**What Should happen:** In normal modes, the puddles should stop growing while the raid is under the effect of Tear Gas.

**Comment by wow-mania** [comment]
AS-IS we will no longer work on issues that in any way makes the fight easier.
We will work only if it stops the fight.
