### ISSUE TITLE
[Quest] A Special Surprise - Added races (Goblin and Worgen)

### ISSUE THREAD

**Issue by WhitephoenixTheBunny** [WoWManiaUK/Redemption#4438]
This was done with a Goblin but the issues is same with Worgens

When a **Goblin** is on the quest chain [Knight Commander Plaguefist](https://www.wow-mania.com/armory/?npc=29053) will offer **TWICE** A Special Surprise
![dk goblin 1](https://user-images.githubusercontent.com/31921098/79344642-ffc87200-7f27-11ea-8df8-341fffe26977.jpg)
![dk goblin 2](https://user-images.githubusercontent.com/31921098/79344701-1242ab80-7f28-11ea-834f-7677996f36a3.jpg)

The IDs are [12748](https://www.wow-mania.com/armory/?quest=12748) and [28650](https://www.wow-mania.com/armory/?quest=28650)

As they are added race Goblins will be associate to Orc quest, being the quest 12748 the Orc one, and 28650 the Goblin one.
Looking at armory the 28650 shows 👍 
![image](https://user-images.githubusercontent.com/31921098/79345769-70bc5980-7f29-11ea-8ebc-69d01c4649c4.png)

_**Possible Solution**_

Remove the 28650 

Worgens have same issue, the quest to remove is 28649

**Comment by Rushor** [comment]
will fix that :)

**Comment by Rushor** [comment]
try now pls

**Comment by jeyrella** [comment]
Correct, only offers the goblin version of the quest now
![image](https://user-images.githubusercontent.com/46089380/79595625-1a8d1900-80d7-11ea-9c3e-c41e2e5c5f28.png)
