### ISSUE TITLE
Not enough resources to process command. File: M2Shared.cpp

### ISSUE THREAD

**Issue by IJustWannaPlayWOW** [WoWManiaUK/Redemption#4439]
Hey, thanks for taking the time to read through this.

**Links:**
Picture of the error message:
![image](https://user-images.githubusercontent.com/63742502/79369090-b3ddf300-7f50-11ea-970e-4e3a11a62a88.png)

**What is Happening:**
I started playing last week and so far its been nothing but great, so thanks for that! 

Today I arrived in Dalaran for the first time and every couple of minutes my game crashes with the error message posted above. This has not happened in any other region before. 
At first glance it looks like a RAM related issue so started task manager and logged in WoW again. Same error just different number of requested bytes of memory. In task manager I cannot see a spike in RAM. Nothing for GPU dedicated memory either. Which makes sense because its only 9965648 bytes requested, so about 10MB. My system is equipped with 16GB RAM and 4GB dedicated on the GPU so it should be able to handle this without breaking a sweat. Next I restarted my computer, disabled all my addons and cleared the game cache but I keep getting the same error resulting in a game crash.
To test if it just occurs in Dala I teleported down and ran near Dragonblight but just before I reached the entrance path between the mountains the game crashed with the same error. 
I did not tinker with any files in the WoW folder besides adding a couple of addons from your addon pack linked on your Discord server. I still manually removed all addon folders leaving just the Blizzard_* folders that came with the game. I started the game again and played in Northrend for a solid hour without crashes. Thinking I solved the problem I go back to Dala because I want to meet up with someone. Not even 2 minutes in Dala the game crashes with the same error. 
I'm running a fresh install of Windows 10 Education N (installed not even a month ago) with the latest updates and drivers installed. I am on the latest version of the game 3.3.5 (12341) (WoW-Mania 2.6.0) and use the official WoW-Mania client provided on your website. I start the launcher with administrator rights every time I open up the game. 

**What Should happen:**
Not crash, probably.

Thanks again! If you have any questions let me know.
BR

**Comment by gamer100** [comment]
Need to add the new launcher

**Comment by WhitephoenixTheBunny** [comment]
Download the new launcher, it will fix it

**Comment by IJustWannaPlayWOW** [comment]
I got in contact with Psygoa via an ingame ticket and this was actually the solution. The launcher didn't update itself and you had to manually download and replace Launcher.exe and WoW-Mania.exe. The Link can be found on the official Discord channel under pinned messages by GM Metaxe here: https://cdn.discordapp.com/attachments/288054714527121418/697520856494243880/Launcher-2020-03-25.zip
