### ISSUE TITLE
Sons of Hodir rep farm quest seams bugged

### ISSUE THREAD

**Issue by wors101** [WoWManiaUK/Redemption#4440]
**Links:**

**What is Happening:**
problem is I'm having is that i can not take the quest from King Jokkum or any NPC's around him including the dailies it shows to me they green meaning i should be able to but when i get to them my cursor shows the attack icon and not the icon ! for the quest i cant talk to him only attack him 

**What Should happen:**
what should happen is i should be able to do the quests and the dailies

**Comment by WhitephoenixTheBunny** [comment]
Go reputation tab, uncheck "at war" , relog and delete cache.
![image](https://user-images.githubusercontent.com/31921098/79426471-1c61ba00-7fbb-11ea-9918-52a9b771cd53.png)
