### ISSUE TITLE
[Boss/Karazhan] Chess Event

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#4441]
**Links:** https://wowwiki.fandom.com/wiki/Chess_event

**What is Happening:** The Chess Event boss currently doesn't work at all and I don't see any previous reports about it so I wanted to see if it could be looked at.

**What Should happen:** The fight should work.

**Comment by bLeyaa** [comment]
Ahhh the chess event... I believe this is a bitch to fix. I don't think i've seen a server where this works properly, probably due to outdated content requiring too much work = not worth it. I guess it's one of those things like Ring of Valor. :P

**Comment by Rushor** [comment]
it required to much work time for now - but one day it will be fixed :)

**Comment by Lumber-Jack-2** [comment]
future request aswell
