### ISSUE TITLE
[QUEST] The Angry Gorloc

### ISSUE THREAD

**Issue by joka95** [WoWManiaUK/Redemption#4442]
**Links:**
http://www.wow-mania.com/armory?quest=12578
https://www.youtube.com/watch?v=OEPJ3j7UXtQ

*What is Happening:**
This is the line quest for The oracles reputation. I take a q and travel to mosswalker village as it says but when i came to viliage nothing hapend. And quest cant be finished.

**What Should happen:**
The q should be completed when i enter in village.

**Comment by Rushor** [comment]
i'm sure this works in a specific way

**Comment by svijetlo** [comment]
but busy atm irl will test it later tho i member doing it some time ago , if i complete it will post instruction and close post

**Comment by wow-mania** [comment]
There is a specific location. Unless you go within a certain radius of it you don't get credited.

**Comment by svijetlo** [comment]
yes just figured it out  you need to get to spot in MIDDLE of place somewhere just walk around

**Comment by Bobthereaper** [comment]
Run around near the eastern entrance under the terrace/trees marking the entrance spam resummoning moodle using his stress ball i did this for about 5-10mins and it finally worked.
