### ISSUE TITLE
[Dungeon/NPC] Violet Hold Heroic mobs missing loot tables (Possibly alliance-only, have not tried on horde)

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#4444]
**Links:**https://www.wowhead.com/the-violet-hold#npcs
https://www.wowhead.com/npc=32191/azure-stalker#drops:mode=heroic
https://www.wowhead.com/npc=30668/azure-raider#drops:mode=heroic
https://www.wowhead.com/npc=30892/portal-guardian#drops:mode=heroic
https://www.wowhead.com/npc=30695/portal-keeper#drops:mode=heroic
https://www.wowhead.com/npc=30666/azure-captain#drops:mode=heroic
https://www.wowhead.com/npc=30667/azure-sorceror#drops:mode=heroic
Issue #4420

Reopening this cause I have done Violet Hold heroic 3 times on alliance since the previous one was closed and not a single mob dropped loot. I suppose maybe faction affects it,

**What is Happening:** All of the Violet Hold trash mobs (all listed above) are missing their loot table for the heroic version for alliance side on live Redemption. Normal version has loot.

**What Should happen:** These mobs should have the loot tables listed above. Just do a run on live version HEROIC on alliance and you 100% will not get a single drop from trash.

**Comment by Rushor** [comment]
okay they should drop in heroic now sth too. i will rework all those tables in future. but for now. this should work.
