### ISSUE TITLE
[Spell/Glyph] Glyph of Molten Armor losing bonus on relog

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#4445]
**Links:** https://www.wow-mania.com/armory/?item=42751

**What is Happening:** Like Seal of Wisdom, Seal of Vengeance (#4310) and Seal of Light (#4316), [Glyph of Molten Armor](https://www.wow-mania.com/armory/?item=42751
) is losing its effect on relog.

**What Should happen:** The glyph's effect should 'stick' even when relogging.

**Comment by jeyrella** [comment]
Without glyph or armor
![image](https://user-images.githubusercontent.com/46089380/79590408-e57cc880-80ce-11ea-9735-90a124dfd85a.png)

with molten no glyph before logout
![image](https://user-images.githubusercontent.com/46089380/79590473-f9282f00-80ce-11ea-9757-86eae19a94c3.png)
after relog
![image](https://user-images.githubusercontent.com/46089380/79590539-165cfd80-80cf-11ea-93ef-6dc005e74b54.png)
with glyph, but armor inactive
![image](https://user-images.githubusercontent.com/46089380/79590665-45736f00-80cf-11ea-84bc-591619c4878c.png)
with glyph, armor active before logout
![image](https://user-images.githubusercontent.com/46089380/79590702-545a2180-80cf-11ea-9c51-cd65e3b11082.png)

with glyph, armor active after logout
![image](https://user-images.githubusercontent.com/46089380/79590791-7b185800-80cf-11ea-9dce-995aa489e526.png)

Conclusion:  confirmed, issue is specifically around Glyph of Molten Armor not reflecting properly on relog.

**Comment by Keader** [comment]
rdy to test
