### ISSUE TITLE
PvP Wintergrasp 

### ISSUE THREAD

**Issue by Grin44** [WoWManiaUK/Redemption#4446]
**Links:**

**What is Happening:**
I first ask GM, they suggest make report there in website.
Battle start 17.04,2020 ~ 12:30 at server time. Fortress must defense Alliance (I was alliance too). Battle go very good we defend fort very good. Hord was scratch one wall little bit. We was destroy almost all towers. Battle looks very good for Alliance, but after ~  10 fighting Show message Hord capture the fortress. 

What was be bug or Hax, because Hord was only scratch one wall little bit.They must breake two walls and entrance door.

**What Should happen:**

**Comment by wow-mania** [comment]
YOu did not describe a bug or anything procedure to test anything.
