### ISSUE TITLE
[Boss/Ulduar] XT-002 Deconstructor Pathing + Idle animation

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#4448]
**Links:** https://www.wowhead.com/npc=33293/xt-002-deconstructor#comments
https://www.youtube.com/watch?v=8ilbrE6COoI (From 0:00 to 1:12)

**What is Happening:** Currently, the boss only moves back and forth until pulled, constantly moving and never pausing at any point.

**What Should happen:** The boss should follow the same path, but stop at 3 different spots. He should stop to 'pound' the 2 scrap piles on the far ends of the room for about 10-15 seconds before resuming his path, and upon reaching the middle (bottom of the stairs) he should stop and do his idle animation of stretching for about 20-25 seconds. 

> By Felborn (10,754 – 2·12·87) on 2009/04/15 (Patch 3.1.0) |   
> Idle animation is him doing stretching exercises.

**Comment by wow-mania** [comment]
Minor issue. If simple to fix fine if not close it. Animation is not critical.

**Comment by Rushor** [comment]
i have a fix for that

**Comment by Rushor** [comment]
https://gyazo.com/444b11798827c599ce8dd416bd9bff8c

**Comment by svijetlo** [comment]
THIS IS AWEEESOMEEEEE
