### ISSUE TITLE
[NPC/Ability] Val'kyr Herald doesn't have raid copy ability

### ISSUE THREAD

**Issue by slaniaxx** [WoWManiaUK/Redemption#4449]
**Links:**
https://www.wowhead.com/npc=37098/valkyr-herald#abilities

**What is Happening:**
Val'kyr's don't do any abilities. 

**What Should happen:**
Val'kyr trash in icc, should use his ability to create copies of the raid who use same abilities as we fight them. More they stay alive, more copies. The copies should use abilities(healers should cast heal spells etc.

**Comment by Rushor** [comment]
uhh that is sth big

**Comment by Keader** [comment]
I will put this on hold.,,
Has a lot of serverside spells without information, i cant fix it right now.

**Comment by Rushor** [comment]
Okay thanks for info :)
