### ISSUE TITLE
[NPC/ICC] Nerub'ar Broodkeeper (Web Wrap)

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#4450]
**Links:** https://www.wowhead.com/npc=36725/nerubar-broodkeeper#abilities
https://www.wowhead.com/spell=70980/web-wrap
https://www.wowhead.com/npc=38028/web-wrap

**What is Happening:** The [Nerub'ar Broodkeeper](https://www.wowhead.com/npc=36725/nerubar-broodkeeper#abilities)  in Icecrown Citadel currently cast their [Web Wraps](https://www.wowhead.com/spell=70980/web-wrap)  properly, but only the first part of the spell works. The target gets immobilized for 3 seconds, but are then freed and nothing more happens.

**What Should happen:** After the 3s immobilization of the Web Wrap cast time, the target should become encased in a [cocoon](https://www.wowhead.com/npc=38028/web-wrap) .

**Comment by Rushor** [comment]
added the effect. https://i.imgur.com/XrHOrr5.jpg once the web wrap is killed, the player is freed from the sun again
