### ISSUE TITLE
[NPC/ICC] Pustulating Horror (Bubbling Pus)

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#4451]
**Links:** https://www.wowhead.com/npc=10404/pustulating-horror#abilities

**What is Happening:** The [Pustulating Horrors](https://www.wowhead.com/npc=10404/pustulating-horror#abilities) in The Plagueworks in Icecrown Citadel are currently missing their [Bubbling Pus](https://www.wowhead.com/spell=71089/bubbling-pus) ability.

**What Should happen:** Every so often, this mob should target a random raid member with Bubbling Pus, inflicting nature damage to them equal to 15% (25% on heroic) of their maximum health every 2 seconds for 10 seconds. This damage is doubled if the caster is affected by plague scientist's [Plague Stream](https://www.wowhead.com/spell=69871/plague-stream).

**Comment by Rushor** [comment]
had to adjust the timer for that
