### ISSUE TITLE
Arcane Torrent

### ISSUE THREAD

**Issue by Myzeriel** [WoWManiaUK/Redemption#4452]
**Links:**
https://www.wowhead.com/spell=28730/arcane-torrent

**What is Happening:**
Icon missing

**What Should happen:**

Show icon

**Comment by svijetlo** [comment]
![image](https://user-images.githubusercontent.com/61908373/79613805-8aaf9500-80ff-11ea-9e9e-f0b06a7185bf.png)
it is there , problem is on your side

**Comment by Rushor** [comment]
which class are you @Myzeriel

**Comment by svijetlo** [comment]
made every possible blood elf class it was there

**Comment by bLeyaa** [comment]
He's a mage on that screenshot @Rushor

**Comment by svijetlo** [comment]
i em , tho we do not know what class was a person that made post,

**Comment by bLeyaa** [comment]
If you look at the spell on the bar you'll see Fireball and Ice Armor...

**Comment by bLeyaa** [comment]
Oh nevermind... for some reason i thought your screenshot was an extension of his original post... my bad
