### ISSUE TITLE
[Core/Spells] Problem with load auras order

### ISSUE THREAD

**Issue by Keader** [WoWManiaUK/Redemption#4453]
We have a problem with load auras order.
When a player make a login, he needs get Glyph auras, before get normal auras, or it can make glyphs bugs and not give effect.
It should generic fix issues like Glyph of Seal of Wisdom and other seals. And will fix some issues not even reported yet.
I need that testers test all glyph of seal xxx of paladin, if they will work after relog.

**Comment by svijetlo** [comment]
will do all tomorrow, was actual paining to run thru all of them :D
this came as good reason to do it

**Comment by svijetlo** [comment]
Glyph of seal of command 👍 
Glyph of Seal of Righteousness 👍 
others i tested before they are working fine
