### ISSUE TITLE
Lady Deathwhisper - Dominate Mind vs Cyclone

### ISSUE THREAD

**Issue by bLeyaa** [WoWManiaUK/Redemption#4454]
**Links:** http://www.wow-mania.com/armory?spell=71289

**What is Happening:** Players who are mind controlled by Lady Deathwhisper stop moving/using abilities after the cyclone done by druids.

**What Should happen:** Affected players should continue to move/attack/use abilities once the cc on them has ended/has been broken.

Occured tonight on 25hc difficulty, experienced it as both the one being cycloned and myself using cyclone on someone else.

**Comment by svijetlo** [comment]
after get cyclone mind controlled person AI does not cont using any spells after cyclone ends 
need to see is it same for BQ mind control

**Comment by svijetlo** [comment]
P.S. BQ one works fine , got killed by my other account alt

**Comment by bLeyaa** [comment]
Well, it can be abused, if one druid casts cyclone on all 3 targets the two of them will just stand while one is actually cced... beats the purpose of the boss mechanic.... But if that's low priority then ok :)

**Comment by svijetlo** [comment]
form what i seen it does not stand around it keeps doing auto shoot if hunter and melee hist if melee...
it just does not use spells
