### ISSUE TITLE
[Quest] Just Around the Corner - missing mechanic

### ISSUE THREAD

**Issue by bLeyaa** [WoWManiaUK/Redemption#4457]
**Links:** http://www.wow-mania.com/armory?quest=12819

**What is Happening:** The mines area is missing a mechanic where if you try to go over it with a flying mount you should be dismounted (as mentioned in the quest)

**What Should happen:** Anyone flying over the area, on the quest or not, should be hit and dismounted as shown on the video: https://youtu.be/bkEZAqH-FoI?t=22

The quest itself works (picking up the toolbox), but this should only be possible to do on foot/ground mount.

**Comment by Rushor** [comment]
will fix that

**Comment by Rushor** [comment]
fixed as soon as dev restarts

**Comment by Rushor** [comment]
now is applied the fix

**Comment by jeyrella** [comment]
Am getting "You are in the wrong zone" when trying to mount a flying mount WAYYYYYY outside the minefield.  I think the exclusion zone is somewhat too big.

**Comment by jeyrella** [comment]
https://youtu.be/fuWvFcotEkg
