### ISSUE TITLE
[Quest] Anatoly Will Talk doesnt work - Grizzly Hills - 12330

### ISSUE THREAD

**Issue by horusgr33n** [WoWManiaUK/Redemption#4458]
**Links:**
https://www.wow-mania.com/armory/?quest=12330

**What is Happening:**
when i cure the npc she made a copy of herself green (good) npc and red (bad) npc.
 the good npc stays in the floor while the red (bad) npc rides the horse

**What Should happen:**
The red npc should dissapair while the cured npc (green) should stay with the player in the horse 
i didnt take screeshots.. an gm complete the quest for me... while they are checking it

**Comment by Rushor** [comment]
reason is that vehicles resummon all minions on reset

**Comment by Rushor** [comment]
fixed once dev is restarted

**Comment by Rushor** [comment]
now is applied the fix

**Comment by jeyrella** [comment]
Red NPC still stays on ground.  Green version of Tatjana doesn't get put on horse.

**Comment by Rushor** [comment]
hmm can you try again now :o

**Comment by svijetlo** [comment]
This quest was always strange , i just trank her , red npc stood there i jumped on horse , there was no green npc with me on horse , but horse took me back and quest was completed .
On 2nd attempt i jumped of the horse on way back and it did not complete .
3rd try same as 1st with npc , but i stood on horse , took me back to quest giver , quest was completed.
Conclusion; it can be completed if you do not dismount form horse, if you do dismount , run back wait for npc to reset (cca 5mins) use trank on her jump on horse if it does not move insta jump of and back on it will move take you back and complete quest, IMO this should be left as it is atm as quest can be completed this never worked perfect and it is burn of time on it.
i wont confirm it i let some one other decide on that , for me it is fine as long you can complete quest

**Comment by Rushor** [comment]
if you all aggree we gonna push that version on lve if i find no better solution

**Comment by Rushor** [comment]
added some more changes. she should always mount now. pls test :)

**Comment by svijetlo** [comment]
ouch, this made it atm worse , 
after you use trank , you get green npc on horse and green horse , while you can not mount up horse red npc that remain keeps on attacking you and you can not target it 
![WoWScrnShot_042020_172924](https://user-images.githubusercontent.com/61908373/79769554-9207b600-832c-11ea-9967-964474ede69e.jpg)

**Comment by Rushor** [comment]
what happens if you use the trank on the Tatjana only and not on the horse?

**Comment by svijetlo** [comment]
i did do that only used it on her not horse i never used it on horse

**Comment by Rushor** [comment]
hm okay strange, for me it all worked good

**Comment by Rushor** [comment]
here : https://gyazo.com/56b8fb78965ab8f4f0be7846d71ab2a9

**Comment by svijetlo** [comment]
worked now for me will try few more times on different toons if same will conclude it
