### ISSUE TITLE
[Quest] Mull Thunderhorn (Mulgore) don't give quests at all

### ISSUE THREAD

**Issue by foter456** [WoWManiaUK/Redemption#4461]
**Links:**

**What is Happening:**
No quests given from the NPC called Mull Thunderhorn in Mulgore. 

**What Should happen:**
The NPC should give 6 quests in a chain.

**Comment by jeyrella** [comment]
Works just fine - when you are a Tauren....
![image](https://user-images.githubusercontent.com/46089380/79698193-33383300-827f-11ea-98f0-15feecf436c4.png)

**Comment by jeyrella** [comment]
(...and ONLY when you are a Tauren, if that wasn't clear.)
