### ISSUE TITLE
[Npc/Ulduar] Fixed Feral Defender damage, based in warcraft logs

### ISSUE THREAD

**Issue by Keader** [WoWManiaUK/Redemption#4462]
Now Feral Defenders (Auriaya) will have correct damage, based in warcraft logs, instead random videos (like we did last time).
in 10 man he should do: 1.5-3k damage (without stacks) in plates
in 25 man he should do: 5-12k damage (without stacks) in plates.

**Comment by svijetlo** [comment]
works better, this is good
