### ISSUE TITLE
Valithria Dreamwalker Berserk

### ISSUE THREAD

**Issue by slaniaxx** [WoWManiaUK/Redemption#4464]
**Links:**

**What is Happening:**
Valithria Dreamwalker, after a set amount of time does emote "FAILURES!", indicating the start of the enrage... but nothing happens.

**What Should happen:**
Valithria Dreamwalker, after a set amount of time should emote "FAILURES!" and the adds should start spawning at an extremely increased rate (1 mage per 1-2 seconds for example), causing the raid to get overwhelmed and wipe. This is the enrage mechanic for this fight.

**Comment by Keader** [comment]
fixed

**Comment by Aristo14** [comment]
fixed how? 

what is the increased rate? (pref. with blizzlike proof)

**Comment by svijetlo** [comment]
https://imgur.com/a/8pIFn
img is form reddit post
https://www.reddit.com/r/wow/comments/1ktjq0/so_this_is_what_it_looks_like_when_valithria/

**Comment by svijetlo** [comment]
https://youtu.be/T01W26Qp0Y8?t=261

**Comment by svijetlo** [comment]
just tested fight nothing strange happens , it const continues as normal one berserk time run out

**Comment by Keader** [comment]
After 7 minutes, valithria should say: "FAILURES !" and start spawn alot of adds.
Test in wow mania (after my fix):
https://youtu.be/eDLtxK4bSLc
How you dont notice difference @svijetlo ?

**Comment by svijetlo** [comment]
works now that was a looooot of mobs XD

**Comment by Oganku** [comment]
The berserk mechanic itself still works, but it seems to accelerate spawn of only [Blistering Zombies](https://www.wowhead.com/npc=37934/blistering-zombie) and [Gluttonous Abominations](https://www.wowhead.com/npc=37886/gluttonous-abomination), and not the others. 

Video of the fix previously posted by @Keader shows a lot of [Risen Archmages](https://www.wowhead.com/npc=37868/risen-archmage) and [Suppressers](https://www.wowhead.com/npc=37863/suppresser) also spawning, and multiple wowhead or wotlk forum comments indicate the stacking [Blazing Skeletons](https://www.wowhead.com/npc=36791/blazing-skeleton) spamming their AOE ([Lay Waste](https://www.wowhead.com/spell=69325/lay-waste)) contribute to making the berserk a difficult situation to handle.

Currently, one can sort of just kite the abominations and zombies spawning to buy quite a bit of time for the healers if necessary.

**Comment by Keader** [comment]
Test now please.
