### ISSUE TITLE
[Boss/ICC] Valithria Dreamwalker (Dream portal animation)

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#4465]
**Links:** https://youtu.be/LEipp3dDR9I?t=142
https://youtu.be/D_b5ACDLCfg?t=70
https://youtu.be/Yfr2nowQ7DI?t=183
https://youtu.be/wZqk_sypl5s?t=74

**What is Happening:** When a player enters the Dream/Nightmare phase during the Valithria encounter, they see Valithria still sleeping on the ground.

**What Should happen:** As seen from the multiple videos from retail above, Valithria should appear idle, but 'flying' in the air while inside the portals. This is only visual, but displacing the boss a couple feet up in the portal phase should just switch the idle animation from 'grounded' to 'airborne'.

**Comment by Rushor** [comment]
okay fixed. not really important, but the fix also does not hurt aswell. no need to test it, since it would consume to much time of the testers.

**Comment by svijetlo** [comment]
works fine did it today during other tests on that boss , atm in portals she floats in air
