### ISSUE TITLE
[Boss/ICC] Valithria Dreamwalker (Rot worms spawning from Gluttonous Abominations)

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#4466]
**Links:** https://www.wow-mania.com/armory/?npc=37886
https://www.wow-mania.com/armory/?npc=37907
https://wowwiki.fandom.com/wiki/Valithria_Dreamwalker
https://wow.gamepedia.com/Valithria_Dreamwalker
https://wow.gamepedia.com/Gluttonous_Abomination
https://youtu.be/wZqk_sypl5s?t=148

**What is Happening:** At the moment, once a [Gluttonous Abomination](https://www.wow-mania.com/armory/?npc=37886) dies, 4 [Rot Worms](https://www.wow-mania.com/armory/?npc=37907) spawn immediately from its body. Always 4 and only 4 will spawn.

**What Should happen:** 

> Spawn Rot Worms — Spawns 8 to 10 Rot Worms after the abomination dies.

Upon dying, the abominations should spawn many more worms, between 8 and 10 according to the sources above. Also, we can see in the video (at 2:28) that there is a ~3 second delay between the Abomination's death and the Worms spawning. The video also clearly shows the worms 'jumping' out of the abomination's corpse 1 by 1 in a quick succession, instead of just instantly appearing on the ground at the exact time as the abom dies. (2:28 to 2:43 on the right of the screen, by the recount healing window, clearly shows the behavior of rot worms spawning.)

**Comment by bLeyaa** [comment]
Please note that on wowmania the worms will also spawn at the end of the fight if there is an abomination alive, these adds **_should not_** spawn after abos are killed by Valithria Dreamwalker. This is also seen on the above youtube video.

**Comment by Rushor** [comment]
this is actually important and makes the fight harder (what we want)

**Comment by Oganku** [comment]
I agree with Rushor on this. Many of the deaths that happen on this fight are little worms rushing a clothie and killing them with too many stacks. Going from a constant 4 worms to 8-10 worms is a big deal.

**Comment by Rushor** [comment]
the animation part is best! :D i finally found the spell.

all fixed.
- despawn of worms instant if vali encounter is done
- spawn of 8 - 10 worms
- worms do the jump stuff
- worms attack on spawn

https://gyazo.com/95b0035f4baebb972bd37daef6d147de

**Comment by svijetlo** [comment]
perfection :D

**Comment by Keader** [comment]
@Rushor careful with "spawn of 8 - 10 worms".
Spell has 4 sec of duration and 500 ms periodic, it means: it always SHOULD spawn 8 worms.

**Comment by Rushor** [comment]
ah alright, thanks Keader. where is that random value 8-10 from then?

i mean we can increase duration for aura ofc

**Comment by svijetlo** [comment]
seen toon of vids in each one it was only 8 worms idk where it comes that 10

**Comment by bLeyaa** [comment]
@Rushor worms still spawn after aboms are killed by valithria being healed up to full.

**Comment by Rushor** [comment]
Maybe regression

**Comment by Rushor** [comment]
okay this is actually new issue, since code is not changed. try now pls

**Comment by svijetlo** [comment]
if you have aboom out and you heal her no worms will spawn now , tho in fight ofc it normal spawns 8 of them

**Comment by bLeyaa** [comment]
@Rushor Regression again i guess, still happening with the worms.

**Comment by jeyrella** [comment]
Note the piece that is regression is the worms spawning after the fight ends.
Count of worms seems ok (at least on live).

**Comment by Rushor** [comment]
okay tra now pls. all worm and abomination should despawn now upon vali geting 100 percent heal. pls also check if the dead abominations despawn aswell.

**Comment by Rushor** [comment]
adn actually this is new or extended issue, since code has not changed here
