### ISSUE TITLE
Ice Tomb ft Blistering Cold grip

### ISSUE THREAD

**Issue by bLeyaa** [WoWManiaUK/Redemption#4467]
**Links:** https://www.youtube.com/watch?v=ksHLp1TABOM

**What is Happening:** Sometimes, not often, the target of Ice Tomb will also get pulled with the Blistering Cold. 

**What Should happen:** Player marked for Ice Tomb should be immune to the grip of Blistering Cold.

**Comment by svijetlo** [comment]
this will be fixed with next update and change to blistering timer as now for 2nd blistering in p2 it comes 7 sec to soon and person is only marked no
pls do not change or touch this i beg you , Keader,

**Comment by bLeyaa** [comment]
This has nothing to do with timer, marked (tombed) player should be immune to grip.
If timers are off after the first air phase, then they're off for everything else as well, not just blistering?

**Comment by Keader** [comment]
I was making a protection, to not allow it happens...
i will not touch in timers.

**Comment by svijetlo** [comment]
timers are of as blistering cold is off times it comes to soon do to it affected only blistering cold so it eater come same time as mark or 1 sec sooner we did last night , after next update it will be fine , lest stop messing this fight more

**Comment by Keader** [comment]
ok, closing this
