### ISSUE TITLE
[Quest] Shoot 'Em Up

### ISSUE THREAD

**Issue by bLeyaa** [WoWManiaUK/Redemption#4468]
**Links:** http://www.wow-mania.com/armory?quest=13069

**What is Happening:** Kill count is not being given when proto drakes and their riders are shot down. 

**What Should happen:** Each drake should be accounted towards the quest progression

What happens at the moment: https://youtu.be/-MD8MKBaVPI

**Comment by svijetlo** [comment]
lol funny enough after relog it did work @bLeyaa  try that

**Comment by Rushor** [comment]
there is strange hp behaviour for those creatures

**Comment by svijetlo** [comment]
funny enough after relog it did work to me

**Comment by svijetlo** [comment]
now 3 kills not count then 4th kill did count

**Comment by svijetlo** [comment]
![WoWScrnShot_042020_172218](https://user-images.githubusercontent.com/61908373/79768779-88318300-832b-11ea-8016-6ca81ee2d1e6.jpg)
this one is strange now it counted all of them to me

**Comment by svijetlo** [comment]
![WoWScrnShot_042020_172448](https://user-images.githubusercontent.com/61908373/79769001-dcd4fe00-832b-11ea-93ef-492c3958057d.jpg)
just completed quest for 3rd time so will mark it as is

**Comment by bLeyaa** [comment]
If there's something affecting it to work on RNG then something is wrong with it, as shown on the video it doesnt count as it should. You've had the issue with it as well. 

@Rushor [Seeds of Chaos](http://www.wow-mania.com/armory?quest=13172) not sure if this is related as you're also in vehicle for this quest, but the count is not given properly as well. This one accounts every few kills instead of each kill. FYI

**Comment by svijetlo** [comment]
after relog it counted all to me last try i even gave up quest and took it again 3 times in row counted all of them, as quest can be completed i wont bother much more around it.

**Comment by Rushor** [comment]
i just fixed the quest in dev :D issue was the health pool. so fix will go live tomorrow
