### ISSUE TITLE
[Quest] Honor is for the weak

### ISSUE THREAD

**Issue by bLeyaa** [WoWManiaUK/Redemption#4469]
**Links:** http://www.wow-mania.com/armory?quest=13170

**What is Happening:** Credit is not being given after the debuff fades, [Assassinate Restless Lookouts](https://www.wow-mania.com/armory/?spell=58563) needs to be spammed 3-4 times to be credited.

**What Should happen:** https://youtu.be/eY-nO3IHrvM?t=38

> Rushor commented on Mar 16
if you wait until the debuff fades out, you get the credit

Related to #4244

**Comment by bLeyaa** [comment]
Btw, here's the example of what happens at the moment.

https://www.youtube.com/watch?v=jX3WA7FA4NA

**Comment by Rushor** [comment]
reapplied the old fix - pls check

**Comment by svijetlo** [comment]
still if you use Assassinate restless Lookout one time on them does not count kill when debuff run out , if you use skill 2 or more times it does count it
