### ISSUE TITLE
The Storm King's Vengeance Quest Zul Drak

### ISSUE THREAD

**Issue by Dmw1981** [WoWManiaUK/Redemption#4470]
**Links:**

**What is Happening:**
giant moves and jumps but does not attack 
dismount button does not work
have to log out to get off

**What Should happen:**
he should attack

**Comment by Rushor** [comment]
Keader can you fix that? It is like the pp abomination

**Comment by Oganku** [comment]
The giant had abilities and they all work, the quest is doable. I don't know if the auto attack of the vehicle is even significant too, one of his abilities is basically a spammable auto attack already

**Comment by Rushor** [comment]
mabye recheck with videos

**Comment by Rushor** [comment]
according to this no melee attack from vehicle https://www.youtube.com/watch?v=nxwliC-Dn84

we must check the "leave vehicle" problem

**Comment by Rushor** [comment]
for me the leave also works fine https://gyazo.com/09d8c0431ed33b2555468fd6f398e47f
