### ISSUE TITLE
Cant connect to server

### ISSUE THREAD

**Issue by feralshnitzel** [WoWManiaUK/Redemption#4471]
**Links:**
My account username is Vixrath 

**What is Happening:**
When i went to login it disconnected me after loading Instead of loading into the game.
Checker server status and even Ban Lists and found nothing to my issue 

**What Should happen:**
I have ran the program in administrator and cleared cache but nothing has worked.
Perhaps it is something having to do with This account in particuliar.
Please help. ):
-Vixrath

**Comment by Rushor** [comment]
bugtracker is for serverside issues only.

try to redownload the full clien and remove "read only" in your wow folders
