### ISSUE TITLE
Duplicate mining node at Thousand Needles

### ISSUE THREAD

**Issue by yani** [WoWManiaUK/Redemption#4472]
Don't have a screenshot but there was a duplicate (copper) mining node at [11.27, 14.24] in Thousand Needles.

Should these be reported?

**Comment by Rushor** [comment]
you can report that, but the priority is not high

**Comment by Rushor** [comment]
fixed once dev is restarted

**Comment by Sharuzan** [comment]
<img width="825" alt="bug" src="https://user-images.githubusercontent.com/47272908/79854819-54f20100-83ca-11ea-8d56-4fb7e4b1bbc9.png">

2x veins indeed.
