### ISSUE TITLE
Only one forge in Dalaran works to smelt bars

### ISSUE THREAD

**Issue by yani** [WoWManiaUK/Redemption#4474]
**What is Happening:**
Only one forge in Dalaran works to smelt bars.

**What Should happen:**
Both forges should work.

![image](https://user-images.githubusercontent.com/6956790/79803562-7e774200-8362-11ea-8055-7af1cc0beaea.png)

![image](https://user-images.githubusercontent.com/6956790/79803575-833bf600-8362-11ea-9371-17c715d7ea92.png)

**Comment by Rushor** [comment]
should work on more places now.

**Comment by svijetlo** [comment]
all forges in dala work properly now

**Comment by Rushor** [comment]
thanks for the test
