### ISSUE TITLE
[NPC] Stoic Mammoth have no droptable

### ISSUE THREAD

**Issue by yani** [WoWManiaUK/Redemption#4475]
**Stoic Mammoth** at **The Storm Peaks**, around [57.37, 64.31] appear to have no droptable. 

https://www.wowhead.com/npc=30260/stoic-mammoth

They should be dropping **Stoic Mammoth Hide** for the quest **Raising Hodir's Spear**.

![image](https://user-images.githubusercontent.com/6956790/79823030-f1001600-8392-11ea-8197-813b248c0000.png)

**Comment by Oganku** [comment]
I did that quest less than a week ago and it worked, it was on alliance, not sure if any different.

**Comment by yani** [comment]
> I did that quest less than a week ago and it worked, it was on alliance, not sure if any different.

Did you skin them or get the hides as drops? It's possible to get the hides from skinning, but they should also be dropped.

**Comment by bLeyaa** [comment]
I've done it yesterday, can confirm that not all of them had the hide as a drop. However, as per wowhead they only have 15% drop chance of dropping the hide. But in addition to that, none of them had a single piece of other loot from what shows on wowhead.

**Comment by Rushor** [comment]
will drop some other stuff aswell now.

**Comment by svijetlo** [comment]
on horde and ally trash has drooped
