### ISSUE TITLE
[Quest] "Test of Faith" teleport in thousand needles 

### ISSUE THREAD

**Issue by yani** [WoWManiaUK/Redemption#4476]
**Links:**
https://youtu.be/fQAJAOVGKUM

**What is Happening:**
The teleport location used during **Test of Faith** is active even when the quest is not active.
I accidentally flew my mount into it and was randomly teleported to the quest giver.

**What Should happen:**
I think the teleport location should only be active during **Test of Faith**.

**Comment by Sharuzan** [comment]
Even if the player doesn't have the quest, the player is still teleported if you get to the spot, where the quest would normally teleport you from. Bug confirmed :)

**Comment by Rushor** [comment]
areatrigger must rescript

**Comment by Rushor** [comment]
fixed now. now only teleport is triggered if you have quest=1149 in your log.
