### ISSUE TITLE
Explosive Barrage - Ick & Krick (Pit of Saron boss)

### ISSUE THREAD

**Issue by bLeyaa** [WoWManiaUK/Redemption#4477]
**Links:** [Ick](http://www.wow-mania.com/armory?npc=36476) & [Krick](https://www.wow-mania.com/armory/?npc=36477)

**1)**
**What is Happening:** When boss is casting Explosive Barrage, he keeps moving with the person who has the aggro on the boss instead of being stationary while casting it.

**What Should happen:** Boss should stand in place while casting the ability.

**2)**
**What is Happening:** 
At the moment if the boss is killed while casting the Explosive Barrage, the bubbles will keep appearing until the duration of the cast is done. This should not be the case.

**What Should happen:** 
Once the boss is killed the channeling of the spell should stop and the only bubbles that should pop and do damage are the ones that were already created while the boss was alive.

**Comment by svijetlo** [comment]
https://youtu.be/au7YoR4UJLg?t=52

**Comment by Keader** [comment]
test now

**Comment by bLeyaa** [comment]
Looks good on PTR, thanks Keader

**Comment by bLeyaa** [comment]
> _2) What is Happening:
At the moment if the boss is killed while casting the Explosive Barrage, the bubbles will keep appearing until the duration of the cast is done. This should not be the case.
What Should happen:
Once the boss is killed the channeling of the spell should stop and the only bubbles that should pop and do damage are the ones that were already created while the boss was alive._

Regression on the above point, worth checking first one as well.

@Oganku can confirm

@Keader @Rushor @jeyrella

**Comment by Oganku** [comment]
Explosive barrage cast will indeed keep going even if the boss dies during it.

**Comment by Rushor** [comment]
maybe changed because spell update? or core regression

**Comment by Keader** [comment]
fixed again
