### ISSUE TITLE
[MOUNT] Magic Rooster - stacking

### ISSUE THREAD

**Issue by svijetlo** [WoWManiaUK/Redemption#4478]
**Links:**
http://us.battle.net/wow/en/item/46778

**What is Happening:**
 Magic Rooster mount if used while on flying mount will stack with flying mount what allows  Magic Rooster to fly and be used as flying mount 
(can not provide Screen shoots atm) 
**What Should happen:**
 Magic Rooster should remove other mounts in "buff" list and should not fly

**Comment by svijetlo** [comment]
@Rushor   this is good but there is slight problem :)
you see if i have mount B and Rooster all are ground mount or standing on ground 
if i em on Rooster and i want to be on mount B i just use mount B it dismount me auto and and start casting B (removing  Rooster icon from buff list)
but if i em on B mount and want to use Rooster it gives me **You are mounted** 
i think some might complain about it ;) 
so you need to manual dismount mount B then one can use Rooster
personally i'm fine with this, but you know how ppl are :)

**Comment by Rushor** [comment]
yes leave that as is, since the rooster is handle in a different way than the other mounts in general

**Comment by Echinaceax** [comment]
Note for future reference https://github.com/WoWManiaUK/Redemption/issues/5715
