### ISSUE TITLE
Sacred Shield

### ISSUE THREAD

**Issue by bLeyaa** [WoWManiaUK/Redemption#4479]
**Links:** http://www.wow-mania.com/armory?spell=53601

**What is Happening:** Sacred Shield does not proc on other players other than the paladin casting it on himself.

**What Should happen:** Sacred Shield should proc on any friendly target, upon being hit under the buff of Sacred Shield.

**Comment by jeyrella** [comment]
Really?  Honestly i could swear I'd seen SS procs in recount.  That would be odd no-one has noticed....  guess this is why we exist :D

**Comment by bLeyaa** [comment]
I've just done a raid followed up with a dungeon, did not proc. I noticed this a bit earlier but though i'm missing something...

**Comment by bLeyaa** [comment]
Nevermind... did a dungeon again after restart and it seems fine... T_T

**Comment by Keader** [comment]
i tested it last week, working fine

**Comment by bLeyaa** [comment]
Yeah, for some reason i couldn't see it in HoR and ICC, but when i went back again to check it... it was there >.<
