### ISSUE TITLE
[Talent] Vengeance not proccing with FoL/Holy Light

### ISSUE THREAD

**Issue by bLeyaa** [WoWManiaUK/Redemption#4480]
**Links:** http://www.wow-mania.com/armory?spell=20057

**What is Happening:** Vengeance does not proc when casting Flash of Light / Holy Light.

**What Should happen:** As per the tooltip, Vengeance should proc from weapon swing, spell or ability.

**Comment by Blyatman1** [comment]
Vengeance should not be procced by Flash or Light, nor Holy Light. It should only proc when you deal critical damage with a melee swing, ability, or damage dealing spells (Judgement, Hammer of Wrath, etc), which to my knowledge, all proc Vengeance correctly. It worked this way on retail as well.

**Comment by svijetlo** [comment]
Vengeance | Rank 3

Gives you a 3% bonus to **Physical and Holy damage** you deal for 30 sec after dealing a **critical strike** from a **weapon swing, spell, or ability.** This effect stacks up to 3 times.

this should never proc form those two 
closing it until you find me proof form back in days that it should do so on 3.3.5a

**Comment by bLeyaa** [comment]
My bad :)
