### ISSUE TITLE
[Spell] Fel Intelligence stacking with Arcane Brilliance

### ISSUE THREAD

**Issue by bLeyaa** [WoWManiaUK/Redemption#4481]
**Links:** [Fel Itelligence](https://www.wow-mania.com/armory/?spell=57567)

**What is Happening:** Fel Intelligence is currently stacking with [Arcane Brilliance](https://www.wow-mania.com/armory/?spell=43002) buff.

**What Should happen:** Fel Itelligence should not stack with more powerful spells of the same type. FYI it does not stack with the [Dalaran Brilliance](https://www.wow-mania.com/armory/?spell=61316) version of the buff. I wasnt able to check the [Arcane Intellect](https://www.wow-mania.com/armory/?spell=42995) though.

**Comment by jeyrella** [comment]
Not tested yet, but could be related to the recent change under #4272 ?

**Comment by bLeyaa** [comment]
Or #4292 ; or #4336 
Odd enough, it works fine with Dalaran Brilliance.

**Comment by jeyrella** [comment]
Ok, so, while mages can cast it on themselves and have both buffs, only the +12 difference between the 48 int of Fel Int and +60 int of Arcane Brilliance is actually applied
![image](https://user-images.githubusercontent.com/46089380/80040661-7d751a80-84f2-11ea-88a6-2d14ee59f453.png)
![image](https://user-images.githubusercontent.com/46089380/80040747-adbcb900-84f2-11ea-9696-a6ef68964b9d.png)
In effect, this is not stacking, it is simply applying the most powerful buff from the two.

Not yet tested:  Dalaran Brilliance

**Comment by jeyrella** [comment]
@bLeyaa I will leave open until tomorrow for a chance of rebuttal, otherwise I will close tomorrow evening.

**Comment by bLeyaa** [comment]
You've used Arcane Intellect and not Arcane Brilliance, there's a difference between the two of them and only one is affected.

See here: https://youtu.be/Otw3BDs97sE

**Comment by Keader** [comment]
fixed
