### ISSUE TITLE
[Talent/Spell] Titan's Grip interaction with Shield Wall / Spell Reflection on stance change

### ISSUE THREAD

**Issue by bLeyaa** [WoWManiaUK/Redemption#4482]
**Links:** [Titan's Grip](https://www.wow-mania.com/armory/?spell=46917) / [Shield Wall](https://www.wow-mania.com/armory/?spell=871) / [Spell Reflection](http://www.wow-mania.com/armory?spell=23920)

**What is Happening:** Warriors with Titan's Grip talent, changing to Defensive Stance and using Shield Wall / Spell Reflect do not keep the buffs on themselves after changing the shield to 2H weapon. They just disappear.

**What Should happen:** The buffs should remain on the player until the timer ticks off.

Reference: https://youtu.be/OqCk2_QkOio (01:12 Shield Wall) / (02:54 Spell Reflection)

Spell Reflection is near end before he swaps back to Berserk Stance and change to another 2H weapon, best seen in slow-mo.

**Comment by Oganku** [comment]
Note that this only applies to fury warriors that have the Titan's Grip talent. If you don't, removing your shield WILL remove shield wall/reflect. Multiple experienced pvp warriors used to tell how broken it was that it didn't remove it, which led to the fix from issue #3420. 

See https://github.com/TrinityCore/TrinityCore/issues/21594 as reference.

**Comment by bLeyaa** [comment]
Correct, this only applies to warriors with Titan's Grip talent.

**Comment by Sharuzan** [comment]
Seems to work as intended, buffs don't wear off when switching stance/shield ->weapon.
