### ISSUE TITLE
[Spell] Warlock - corruption

### ISSUE THREAD

**Issue by swiffty95** [WoWManiaUK/Redemption#4484]
**Links:**

**What is Happening:**
Normally the warlock affly correction when you use the glyph of quick decay is used so that the corruption is affected with your haste and it no longer does it anymore even if you have glyph the time between ticks remains the same I would like to know if it is something that has a solution otherwise the lock affly wont be the same as the corruption is like the 60% of his dps thanks

**What Should happen:**

**Comment by Keader** [comment]
I tested in ptr and is working correctly.
Everlasting Affliction should not keep the hast, he should always update with your current hast, is the blizzlike behavior.
