### ISSUE TITLE
[BOSS/Mechanic] Sindragosa_Blistering Cold

### ISSUE THREAD

**Issue by svijetlo** [WoWManiaUK/Redemption#4486]
**What is Happening:**
During the Sindragosa encounter in every icecrown citadel after 1st air phase each next blistering cold comes 4 sec sooner then it should, what in process has cascading effect as ones encounter enter phase 2 and marks for ice tomb coincide with Blistering cold and it self happens 4 sec sooner rest of players get pulled in at same time as ice tomb appears so they get stuck in it , not **stunned** but stuck in tomb bounds like in small cage (still only one tomb appears), what force raids to stop and wipe making it almost impossible to finish fight, some even resorted to making needless tickets.
And to some it appears as person with mark got pulled in with ice grip effect of blistering cold. 
**What Should happen:**
http://www.wow-mania.com/armory?spell=71049 Blistering cold after 1st air phase should be synchronized with DBM timers and come 4 seconds later then it does at this moment.
NOTE; rest of mechanics are correct on times. Tested extensively with 3 accounts

**Comment by Rushor** [comment]
Ah wrong click

**Comment by Keader** [comment]
try now please.

**Comment by bLeyaa** [comment]
#4467 ?

**Comment by svijetlo** [comment]
will try tomorrow was rly busy irl today

**Comment by svijetlo** [comment]
it works good now , timers on blistering are at point in p2 tested for 10 tomb marks it works fine, tomb appeared before Ice grip effect of blistering, tho i wont confirm it now as i made post and i would prefer one more tester run it, one more pair of eyes can see smt different
