### ISSUE TITLE
Dalaran Bug

### ISSUE THREAD

**Issue by Leithmorien** [WoWManiaUK/Redemption#4487]
**What is Happening:**

After a non-fixed amount of time I stand in Dalaran I get a wow-crash with an insufficient memory error related (related module is .\M2Shared.cpp: requested xxxxxxxxxx bytes of Memory), while I have a lot of memory still free to be used.

Happens ONLY in Dalaran or in its close proximity. Happened to a friend of mine too, all the times.
We both run wow-mania client.

**Comment by wow-mania** [comment]
Get our latest launcher it will fix this issue.
This repository is for server-side issues only.

**Comment by Leithmorien** [comment]
> Get our latest launcher it will fix this issue.
> This repository is for server-side issues only.

No way, I'm using the launcher and it happened anyway, my friend also using it, same story

**Comment by Aristo14** [comment]
Make sure to get the launcher that metaxa posted on mania discord and is a pinned message. 
Try testing out starting launcher as admin or without admin. 

Hope it helps, have a nice day ;)
