### ISSUE TITLE
DK Death Grip to range mobs

### ISSUE THREAD

**Issue by darkrecx** [WoWManiaUK/Redemption#4488]
**Links:**

**What is Happening:**
Death Grip won't draw spellcasters or ranged dps mobs to the DK.

**What Should happen:**
Right the opposite, Death Grip should draw ANY mob to the DK.

**Comment by Keader** [comment]
reproduce steps?

**Comment by Oganku** [comment]
Usually when a spell caster is casting something, death grip will not move him unless you interrupt/silence him first. It's like spellcasting 'roots' them.

**Comment by svijetlo** [comment]
there is also resist to be gripped by Dk keep that in mind , sometimes Adherent in icc can resist grip

**Comment by wow-mania** [comment]
Very likely not an issue as it starts with an invalid statement, but feel free to check.

**Comment by svijetlo** [comment]
ill see tomorrow in raid atm

**Comment by darkrecx** [comment]
I am not trying to prove anything here because I simply don't remember how Death Grip was working back in the WOTLK years, but I know for sure that now it does interrupt the target and it does draw it near the DK. Now, if I am wrong just cause the skill has changed then forgive me, I didn't know and of course thank you for your time.

**Comment by Aristo14** [comment]
need more specifics but indeed most likely you got resisted.
