### ISSUE TITLE
Mage-Lord Urom after wipe is bugged - impossible to turn it back into fight stage

### ISSUE THREAD

**Issue by denis-lytov-nc** [WoWManiaUK/Redemption#4489]
**Links:**
https://www.wowhead.com/npc=27655/mage-lord-urom#comments

**What is Happening:**
TC: 
1) Fight with boss on platform ER=AR - pack of mobs are summoned
2) After 3 packs are killed - boss appears on central platform
3) Try to wipe on boss and return back to instance
AR: boss is again on outside platform - but after killing pack party stuck in combat. .cl doesn't work. 
Teleport out/in works to clean combat - however boss packs counter is reset back to 0. So it's impossible to continue instance after wipe. 

**What Should happen:**
1) I believe there should be two possible scenarios - either party needs to fight on platform first again or start with boss fight immediately. Probably since oculus itself is annoying - second option is preferable but it's up to you to decide :)

**Comment by svijetlo** [comment]
works fine , after wipe run back in go and clean out side 3 platforms , killing trash on outside platforms is part of that boss fight it is as is , do to fast boss has only 400k hp and on its own would be way to easy thing , stack in combat might be you pulled one of dragon that fly around in air , happen to me

**Comment by denis-lytov-nc** [comment]
The issue is that it's impossible to clean 3 platforms: after cleaning one of them party is stucks in combat - so it's impossible to use dragons to flight to another platform. '.cl' doesn't help - tells 'you are fighting with boss'. 
The only thing party can do to clean combat - it to teleport from instance and return back. However it seems that this action resets counter of waves - yesterday we cleaned in such way four platform but boss still didn't appear in central platform. 

I'm ok that party needs to clean platform agains - but please make it possible for party to do.
