### ISSUE TITLE
Filling the Cages - Quest is bugged.

### ISSUE THREAD

**Issue by Zakdir** [WoWManiaUK/Redemption#4491]
https://www.wowhead.com/quest=11984/filling-the-cages
https://www.wowhead.com/npc=26422/budd

The Tag Troll ability on Budds action bar is not working hence the quest is impossible to complete.

Budd should stun an Ice Troll as the Tag Troll ability says so.

Note: I have opened a ticket to a GM and talked to Osirys(I might be spelling wrong) and he confirmed the quest was bugged and told me to report it in here.

**Comment by jeyrella** [comment]
Quest is not impossible to complete.  Just use the cage.
However, it is true that this does not work like retail, so could be improved, but I would class this as low priority as the quest is still completable.

**Comment by Rushor** [comment]
Will fix that

**Comment by Rushor** [comment]
have added the db part, only core is missing.

**Comment by Rushor** [comment]
is applied

**Comment by lowbg** [comment]
@Rushor well done . Work perfectly tested
