### ISSUE TITLE
[QUEST] The Tome Of Valor - paladin

### ISSUE THREAD

**Issue by ramzius12** [WoWManiaUK/Redemption#4492]
**Links:**
https://classic.wowhead.com/guides/paladin-class-quests-classic-wow#redemption-dwarf

**What is Happening:**
Quest is sending me to Daphne Stilwell to talk to. but no "!" or "?" above her and can't interact with her.

**What Should happen:**
She should talk to continue quest and than get attacked as part of the quest

**Comment by wow-mania** [comment]
I doubt this one is not working.

**Comment by Sharuzan** [comment]
<img width="825" alt="Redemption-quest" src="https://user-images.githubusercontent.com/47272908/80304815-d249b700-87b8-11ea-967b-6b4b5632ec87.png">

Quest seems to be working as intended :)

**Comment by ramzius12** [comment]
![WoWScrnShot_042720_095507](https://user-images.githubusercontent.com/64349319/80342649-2f9f4000-886d-11ea-9d2c-de6cd84f6ef4.jpg)

Hi, I meant Daphne which didn't continue the quest.....for others players too....but Just logged in again and now its working....dunno what changed...
THX anyway :-)
