### ISSUE TITLE
[Spell] SpellSteal vs Heroism/BL

### ISSUE THREAD

**Issue by Keader** [WoWManiaUK/Redemption#4494]
When mages Spellsteal heroism/BL, he should get sated/exhaustion
proof: https://www.youtube.com/watch?v=l8p9kz4svQI&feature=youtu.be&t=66
server behavior: players dont get sated/exhaustion when spellsteal heroism/bl

**Comment by Aristo14** [comment]
is already live, please confirm fix

**Comment by svijetlo** [comment]
person who use Heroism ones you spell steal Hero form them DOES get Exhaustion debuff for 10min
person that stole buff with spell steal DOES get buff benefit but DOES NOT get Exhaustion debuff for 10min

**Comment by Keader** [comment]
![image](https://user-images.githubusercontent.com/7120913/80397292-4903b480-888c-11ea-8401-6c522fc0251d.png)
where you tested it?

**Comment by svijetlo** [comment]
on my 2 toons in front of icc in duel
tho non of toons were  shaman and mage i just gave them spells

**Comment by Keader** [comment]
on live or ptr?

**Comment by svijetlo** [comment]
ptr :) i cant give spells to my toons on live :D

**Comment by Keader** [comment]
well, it's working in ptr rofl

**Comment by svijetlo** [comment]
hmm strange i did it few times and as i explained toon that stole heroism did get buff for 30 sec but after it run out there was no debuff for 10mins

**Comment by Keader** [comment]
![image](https://user-images.githubusercontent.com/7120913/80398281-c11eaa00-888d-11ea-8198-bf438ae64967.png)

**Comment by svijetlo** [comment]
![WoWScrnShot_042720_185054](https://user-images.githubusercontent.com/61908373/80398630-37380680-88b8-11ea-9837-85fb851036d6.jpg)
1st img is with buff after i steal it 
![WoWScrnShot_042720_185141](https://user-images.githubusercontent.com/61908373/80398694-533ba800-88b8-11ea-94bb-09afb9322986.jpg)
2nd one is when it run out

**Comment by svijetlo** [comment]
and i removed aura form caster did it again stole it and got buff again

**Comment by Keader** [comment]
well, it's your side.
