### ISSUE TITLE
Aspect of Hawk rank 3

### ISSUE THREAD

**Issue by j-easy1** [WoWManiaUK/Redemption#4495]
**Links:**

**What is Happening:**
I have the talent Aspect Mastery, and Aspect of the Hawk rank 3. in the spellbook, it says 65 attack power but when i use the spell, I only get 50 attack power.
**What Should happen:**
I should get 65 attack power from the spell

**Comment by Keader** [comment]
Spell will always say 50, but you realy got in your status 65.

**Comment by Keader** [comment]
![image](https://user-images.githubusercontent.com/7120913/80314696-67ed4280-87c9-11ea-8138-8be39e52294c.png)

![image](https://user-images.githubusercontent.com/7120913/80314699-6c196000-87c9-11ea-8792-d85cd4891a68.png)

**Comment by j-easy1** [comment]
thank you!
