### ISSUE TITLE
[Spells/Druid/Priest] Reflective Shield and Thorns should never miss

### ISSUE THREAD

**Issue by Keader** [WoWManiaUK/Redemption#4496]
Spells like Reflective Shield (Priest Disc Talent) and Thorns (Druida) should never miss on reflect damages.
Checked by warcraftlogs.
Both can miss on server
![image](https://user-images.githubusercontent.com/7120913/80314479-18f2dd80-87c8-11ea-8f6a-b99652afa483.png)

**Comment by svijetlo** [comment]
![image](https://user-images.githubusercontent.com/61908373/80319987-e1aa1e00-8813-11ea-9bf3-541fa7aa8787.png)

**Comment by Aristo14** [comment]
is already live, please confirm fix
