### ISSUE TITLE
[NPC] Blood Prince Council - Crimson Hall doors 

### ISSUE THREAD

**Issue by svijetlo** [WoWManiaUK/Redemption#4498]
**What is Happening:**
ones the raid in ICC kills 1st group of trash mobs on way Crimson Hall and the doors for room of  Blood Prince Council open , players can enter room clear trash in it and engage Blood Prince Council to fight what will make doors to enter room close , how ever if the raid wipes on Blood Prince Council fight release spirit and runs back to  Crimson Hall  they will find doors to enter room where you fight closed, what leads to them needing to make ticket and wait for Gm to open the doors. what leads to waste of Gm time and unhappy players, there is no other way to open the doors 
**What Should happen:**
Doors to enter  Crimson Hall  form upper spire in ICC should open ones whole raid wipes and fight reset

**Comment by Keader** [comment]
see why i dont like when rushor take issues like this?

**Comment by svijetlo** [comment]
sadly i can not decide who when and why take issue ;)

**Comment by Rushor** [comment]
Keader pls

**Comment by Keader** [comment]
try now pls

**Comment by Aristo14** [comment]
is already live, please confirm fix
