### ISSUE TITLE
Hor Hc

### ISSUE THREAD

**Issue by Velzevoul** [WoWManiaUK/Redemption#4499]
What happened: We were trying to do HOR hc. We always stayed away from walls since we were trying to avoid bring the rogue inside the wall with shadowstep, we manage to kill the first boss and at wave 6 every mob dissappeared as we were fighting. 
What should Happen: The mobs needed to die and let us go to the last wave and start the encounter with the boss.
Tip: Since we didnt have the gs to push the dungeon we need to us our hunter to put freezing traps down in order to have less adds to fight. At the screanshot you will see where did we trap the rogue and were we stand as party(Purple mark) when the rogue went out of trap and shadowstep even if the player wasnt near the wall he passed throw the wall because we were los to him maybe imo that made the bug happen...

- 
![Screenshot_7](https://user-images.githubusercontent.com/25705676/80321550-846b9800-8826-11ea-92fb-74b8e85c761e.jpg)

**Comment by GM-Osyris** [comment]
Seems to be happening more frequently now. even with parties standing in the middle of the room.

**Comment by svijetlo** [comment]
try truing off shadowstep form mob rogue ability , i rly spent lot of time there on ptr and could not make it to reset

**Comment by wow-mania** [comment]
It may be related with the visibility being reduced last night.
So I will restore it to normal and close it and if it happens just re-open it.
