### ISSUE TITLE
Disarm bug

### ISSUE THREAD

**Issue by Kultivater** [WoWManiaUK/Redemption#4500]
I searched for this bug and found a similar report that claims to have been fixed, but it's not exactly the same. I'll explain: The bug I found in the search is: Whenever your character is disarmed, and your crit chance switches to unarmed, the crit chance doesn't change back once disarm ends.

**What is Happening:**

My issue is almost the same as above, only instead of crit chance, it's minimum weapon damage. This happened on my lvl 35 paladin. When he is disarmed, the maximum lisetd weapon damage(under "Melee" tab on character sheet) changes back to normal after disarm ends, but the minimum damage remains at what I'm assuming is unarmed minimum damage. The only way to fix it(that I've found so far) is to swap weapons, or simply unequip it and re-equip it. If you wish to recreate this bug, then take a melee character to an NPC that disarms, pull up your character sheet and watch the numbers for weapon damage before, during, and after disarm effects take hold.

**What Should happen:**
Weapon damage should switch back to that of the weapon being used after disarm effects end,

On a side note: I want to mention that I didn't notice whether or not the crit chance is affected by this(or anything else is). I will update this issue if I find anything else relevant to it.

**Comment by Keader** [comment]
Before desarm
![image](https://user-images.githubusercontent.com/7120913/80374092-7f313c00-886c-11ea-9190-4f3a5da1f4c5.png)

while desarmed

![image](https://user-images.githubusercontent.com/7120913/80374128-8c4e2b00-886c-11ea-92de-4877f65e62f3.png)


after desarm

![image](https://user-images.githubusercontent.com/7120913/80374141-92440c00-886c-11ea-8fcc-99e22c9e848b.png)

I cant reproduce

**Comment by Kultivater** [comment]
I will take screenshots and prove it the next time I find a disarming mob to fight.
