### ISSUE TITLE
[Roll System] Shields vs Clothers

### ISSUE THREAD

**Issue by WhitephoenixTheBunny** [WoWManiaUK/Redemption#4501]
ATM, on RDF (any kind of levels) and RHC **Clothers** - Mages, Warlocks and Priests, **CAN** roll **NEED** on shields.

They should be **only** able to roll **greed** on shields

**Comment by Rushor** [comment]
are you sure about that? :o

**Comment by WhitephoenixTheBunny** [comment]
Yes, happened to me on mage and priest

**Comment by Keader** [comment]
RDF?
It uses need before greed method?

**Comment by WhitephoenixTheBunny** [comment]
A Mage, Warlock, or Priest, shouldn't be able to roll on a shield, and atm they can.

The need should be greyd to those...


And yes, need before greed

**Comment by Keader** [comment]
Fixed, clothes will not need shields anymore

**Comment by Aristo14** [comment]
is already live, please confirm fix

**Comment by WhitephoenixTheBunny** [comment]
No more tank mages :D
