### ISSUE TITLE
Sindragosa - Frost Breath cone angle

### ISSUE THREAD

**Issue by bLeyaa** [WoWManiaUK/Redemption#4502]
**Links:** https://youtu.be/1tddXuRJG4A

**What is Happening:** Cone at which players get hit by Frost Breath is at a too high angle at the moment.

**What Should happen:** The cone of Frost Breath should not be that wide.

https://www.youtube.com/watch?v=LVcWZ5hfhis (04:10 u can see where disc priest is, about the same area as on the video above)

**Comment by svijetlo** [comment]
inflicts 128 Frost damage to enemies in a 60 yard cone in front of the caster. In addition, the targets' attack speed is decreased by 50% and movement decreased by 15% for 1.5 min.

**Comment by Rushor** [comment]
maybe related to the hitbox

**Comment by svijetlo** [comment]
hit box on dragons is already strange i would not mess with that one , like in RS for example divine storm is not scaling with hit box , and it can not be changed easy
