### ISSUE TITLE
Ice Tomb ft Blistering Cold v2

### ISSUE THREAD

**Issue by bLeyaa** [WoWManiaUK/Redemption#4503]
**Links:** https://youtu.be/3zi_jtJTobs

**What is Happening:** Still present as previously reported: #4467 #4486

**Comment by svijetlo** [comment]
wtrf why is this still happening i was there with 3 toons it did not happen was this on every tomb or just on 2nd in p2 ?

**Comment by bLeyaa** [comment]
It seems to happen with this one at around 02:10 before enrage.... guys last night thought it was 8th tomb... i believe that is the only time i've had it happen before as well

**Comment by svijetlo** [comment]
figured it out just spent hour there 
anyhow while in phase 1 everything is just fine as it can be perfection 
problem comes ones we enter phase two
in phase to every 4th mark for ice tomb comes ice grip+blistering cold 
and while for 4th tomb mark blistering cold is some what good 
on 8th 12th 16th mark for tomb ice grip + blistering cold comes way to soon before tomb even materialize so in process everyone gets pulled in before tomb appears 
so to conclude 2nd 3rd etc blistering colds in phase two that come on 8th 12th 16th mark for tomb happen to soon as i seen some 3.7sec to soon

**Comment by Keader** [comment]
Now, even timers colide, marked player will not be gripped.

**Comment by svijetlo** [comment]
will tomb appear before ice grip ?

**Comment by svijetlo** [comment]
wilol test it late :)

**Comment by Keader** [comment]
Nope, player Will not be pushed

**Comment by svijetlo** [comment]
sad to say just did test 
it is still happening person with mark gets pulled 
will make video of it tomorrow, ice grip came before tomb was appear

**Comment by Keader** [comment]
try now (again)

**Comment by svijetlo** [comment]
nice work Keader ,
