### ISSUE TITLE
wow mania sign in 

### ISSUE THREAD

**Issue by bellgoseman** [WoWManiaUK/Redemption#4504]
**Links:**

**What is Happening:** i signed on after being gone awhile seen i needed to get the 2.6.0 client did that went to sign back on wont let me on the 2.6.0 client and now it says im temp banned when i try and sign into the 2.5.5 client iv done nothing that i know of to bet any sort of ban please help bellgoseman is my account name 

**What Should happen:**i should be able to log into my account when i downloaded the latest client instead i got some sort of temp ban please help

**Comment by svijetlo** [comment]
not place for it here contact GM or Janitor on discord

**Comment by bellgoseman** [comment]
i cant i try to sign it it asks me to link my account i cant ever get it to work i never liked discord never use it iv not been able to contact any gm or janitor and i go to the web sight it says report bug here well i did nothing for the ban i spoke to no one broke no rule i just went and downloaded the latest client and now it wont let me sign in saying i have a temp ban i cant get onto discord iv tried and i know i broke no rules i did nothing but sign in after a long time seen the upgrade message in chat signed right back out got the latest version let it update and here we are
