### ISSUE TITLE
lk set leather

### ISSUE THREAD

**Issue by Bromes88** [WoWManiaUK/Redemption#4505]
**Links:**
https://www.wow-mania.com/armory/?itemset=2002

**What is Happening:**
the proccs of the lk set dont work. the first and fourth are the same procc and only 1 works.
the trinkets where you have the proccs from are useless

**What Should happen:**
i dont know what should happen. its your custom set

**Comment by Rushor** [comment]
i think the set is already powerful enough without proccs

**Comment by GMMetaxa** [comment]
Works as intended.

**Comment by Bromes88** [comment]
can i have my money back ? -.-
