### ISSUE TITLE
Vip points

### ISSUE THREAD

**Issue by Milenskiqt** [WoWManiaUK/Redemption#4506]
**Links:**
Transfering from bags
**What is Happening:**
Vote points disapear in the BANK

**What Should happen:**

Should be transfered Or not , i am not sure what and why

**Comment by Milenskiqt** [comment]
Found them, The icons were BLACK BLANK

**Comment by Milenskiqt** [comment]
IT LOOKS LIKE ONLY IN THE MAIN BANK INVENTORY IS BLANK IN OTHERS THE ICON IS QUESTIONMARK 🗡️

**Comment by lowbg** [comment]
are you sure you are using the wow mania client  and update from the launcher work fine  Tested no black blank
