### ISSUE TITLE
[Spell] Fire Elemental Totem

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#4507]
**Links:** https://www.wow-mania.com/armory/?spell=2894

**What is Happening:** The elemental spawned from [Fire Elemental Totem](https://www.wow-mania.com/armory/?spell=2894) kinda just sits there afk for several seconds after spawning. No matter how close to the target you summon him, or if you move around your target, it will still take him a couple seconds to 'snap' onto it and actually start attacking.

**What Should happen:** The fire elemental summoned should actively look for enemies to attack right as it spawns, and should not take multiple seconds before doing so. Basically it should behave like a pet on defensive, and not like a pet on passive.

PS: It used to attack immediately before.

**Comment by lowbg** [comment]
@Oganku are you using Flame shock on target  after spawn the pet totem

**Comment by Oganku** [comment]
Not necessarily. Sometimes yes, sometimes not and sometimes the dot is already on the target when it spawns and he still doesn't do anything.

**Comment by lowbg** [comment]
There has not been found a issue tested on raid after tank start also on single  and multiple targets .The totem has going to atack the target straight away  if is not in combat and spawn him not going to atack anyone unless you dont enter combat .
