### ISSUE TITLE
[Boss/Spell] Scourgelord Tyrannus (Overlord's Brand)

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#4509]
**Links:** https://wowwiki.fandom.com/wiki/Scourgelord_Tyrannus
https://www.wowhead.com/spell=69172/overlords-brand

**What is Happening:** The [Overlord's Brand](https://www.wowhead.com/spell=69172/overlords-brand) debuff the boss applies to a random non-tank in the party is supposed to mirror the damage the person does onto the tank, or mirror and amplify healing done to the caster (the boss). The healing component seems to work fine (maybe missing the amplification? not sure), but the damage reflect component is pathetic. Any dps can just keep attacking with no worry once they get it, even if the tank is fairly low geared. The wording implies that a 10k fireball cast by the branded target would cause 10k damage to the tank, but during the 10s of duration where I had the brand in my last run, I only caused ~10k dmg total to the tank while doing about 5k dps. The tank should have taken closer to 50k damage over this duration. This mechanic is trivialized from a dps pov and makes the fight much easier.

**What Should happen:** The branded target's damage should be mirrored directly onto the tank (boss' target).

**Comment by lowbg** [comment]
Tested working fine It depends from the gear i try with low gs tank and almost 1 shot him so no issue with that

**Comment by lowbg** [comment]
P.S Tested on heroic

**Comment by Keader** [comment]
test now dear

**Comment by lowbg** [comment]
@keader tested again working fine the spell Overlord's band reflecting the same from the dps over the  tank on right way . i tested with normal atack and with spell both working normal
