### ISSUE TITLE
[Blackrock Depths] Plans: Dark Iron Shoulders - missing plans

### ISSUE THREAD

**Issue by Keshilolz** [WoWManiaUK/Redemption#4510]
**Links:**
https://classic.wowhead.com/item=11615/plans-dark-iron-shoulders
the plan is necessary to complete the dark iron set. 
1- At BRD there is 4 location where a blacksmiting plan spawns, you need to be 285 to click on it.
2- 3 of the spawns drops the "mail chest"  and 1 DROPS 100% "the dark iron shoulders". (see image below)

![image](https://user-images.githubusercontent.com/64604656/80738022-e9174300-8b03-11ea-8735-4d375f44a8a9.png)

**What is Happening:**
Such plans do not currently exist in BRD, The Dark Iron shoulders  never spawn at the location.

**What Should happen:**
The plan should be spawning here.(see image below)

![image](https://user-images.githubusercontent.com/64604656/80738227-31cefc00-8b04-11ea-9ac4-30137edc5693.png)
First room at East garrison to the left after you activate the door.

For more help you can see video below at 0.36.
https://www.youtube.com/watch?v=WHdsVujJ2KY

P.S : i did 6+ runs with the GM last night, we faced a problem that if you click a scroll nothing happens, he helped me fix that by disabling auto-loot.but still we couldn't found the scroll at the location.
Thanks
P.S 2 : Found this ticket on github for the same issue if it can helps.
https://github.com/Atlantiss/NetherwingBugtracker/issues/1475

Thanks

**Comment by Aristo14** [comment]
Maybe linked to: https://github.com/WoWManiaUK/Redemption/issues/4362

**Comment by Keshilolz** [comment]
yes it's linked i mentioned there some infos.
after several times clearing the instance.
1- scroll in detention block  behind the high interrogator gestharn, 100% spawn but empty
2- scroll near the general angerforge : spawn like 75 % - always empty
3- scroll near the golem lord : spawns like 50% - always the mail chest plan
4- i never found the scrolls at east garisson or the room before the 7 spirits .

thanks

**Comment by GMMetaxa** [comment]
On a sidenote: You need level 285 of the prof to make this work.

**Comment by Rushor** [comment]
that is too complicated, i will add a 50 percent chance to get it from the normal Blacksmithing Plans in addition to the Plans: Dark Iron Mail
