### ISSUE TITLE
to many rings came in

### ISSUE THREAD

**Issue by asharian123** [WoWManiaUK/Redemption#4511]
**Links:**
https://www.wow-mania.com/account/shop?category=6#

**What is Happening:**
was buying Arthas Menethil's Oathbinder, then my pc frozed when i clicked it. and then said process is complete, but when i looked at the coins to much was taken out, turn out i had gotten 3 of them

**What Should happen:**

was only tring to get 1 Arthas Menethil's Oathbinder

**Comment by svijetlo** [comment]
@asharian123   contact janitor on discard about purchase items , this is not place for it
