### ISSUE TITLE
[QUEST] Where Dragons Fell-Killable Lich King

### ISSUE THREAD

**Issue by dawid12201** [WoWManiaUK/Redemption#4512]
**Links:**
https://www.wowhead.com/quest=13398/where-dragons-fell

**What is Happening:**
After turning the quest, one is shown the vision of Lich King resurrecting Sindragossa. The only problem being that Arthas is attackable and killable (28Million HP). He stands still while being damaged, does not attack, nor move, doesn't drop anything and doesn't provide one with any achievement.

**What Should happen:**
Vision should end, both Sindragosa and Arthas shouldn't be attackable, and both should disappear.

**Comment by Rushor** [comment]
will fix that

**Comment by Rushor** [comment]
unattackable now
