### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by rakun996** [WoWManiaUK/Redemption#4513]
**Links:**

**What is Happening:**
Hi, my name in Wow is Rakun96, my brother is playin wow on your server long time, and i was come to his place and make account on your server trying to play , but i try something very stupid, to take hack but nothing bad just to come to another place by flying and speedhack,and i get banned...im sorry about that i know is not good, and im sorry most becouse my brother dont know about ban, and i know he cant play becouse of me now..and please unban my ip i promise i wont do it again, just i dont want my bro find out that he get banned becouse of me... im sorry 

**What Should happen:**

unban please, he will play in few hours and i dont want to he figure that ip is banned, please unban im sorry...

**Comment by Aristo14** [comment]
not the place to talk about bans
