### ISSUE TITLE
[Quest] Wolvar Orphan Questline

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#4514]
**Links:** https://wowwiki.fandom.com/wiki/Curious_Wolvar_Pup
https://wow-mania.com/armory/?quest=13960

Wolvar Pup next to me, about to complete quest:
![WoWScrnShot_050120_035824](https://user-images.githubusercontent.com/34783736/80793437-1c3dee80-8b65-11ea-9b3a-404d258c9a0d.jpg)
Quest completed (see chat log):
![WoWScrnShot_050120_035828](https://user-images.githubusercontent.com/34783736/80793441-1e07b200-8b65-11ea-8e39-2f2d415ce212.jpg)
Mailed reward 30min later:
![WoWScrnShot_050120_043438](https://user-images.githubusercontent.com/34783736/80793443-1f38df00-8b65-11ea-8adb-569ce60847e4.jpg)

**What is Happening:** As seen in the above pictures, I have chosen the Wolvar Pup orphan and completed his quest chain, but have received the oracle hatchling (again) in the mail. 

**What Should happen:** The northrend orphan quest chains should award you the child pet of the type you chose to help at the start. Regardless of your choice, you always receive the oracle hatchling right now.

> Unlike previous Children's Week quests, you have to choose your reward at the beginning by selecting which orphan to adopt for this event. After the quest chain is finished, the companion will be mailed to you with a certain delay, which may vary from a few to 30 minutes.

**Comment by jeyrella** [comment]
Confirmed.  Same has happened to myself
![image](https://user-images.githubusercontent.com/46089380/80800278-fd5d4d80-8ba0-11ea-89f8-d1dc2cb09712.png)

**Comment by jeyrella** [comment]
Seems to be reward mail triggered from https://wow-mania.com/armory/?quest=13960 is wrong

**Comment by Rushor** [comment]
adjusted:

quest 13959 will now reward item 46545
quest 13960 will now reward item 46544

**Comment by jeyrella** [comment]
![image](https://user-images.githubusercontent.com/46089380/80832046-db38ef00-8be3-11ea-82d1-2f59642d969a.png)
waiting for mail...

**Comment by jeyrella** [comment]
Now correct
![image](https://user-images.githubusercontent.com/46089380/80839701-a92f8900-8bf3-11ea-863e-596847b66229.png)

![image](https://user-images.githubusercontent.com/46089380/80839758-c49a9400-8bf3-11ea-91cd-e367610ac978.png)
