### ISSUE TITLE
[Pet/DK] Gargoyle vs Hand of Protection

### ISSUE THREAD

**Issue by Keader** [WoWManiaUK/Redemption#4515]
If paladin uses Hand of Protection in Gargoyle (DK Pet) she stop attack.
Hand of protection should prevent only melee damages, not spell ones.

Behavior before my fix: https://youtu.be/tKu_lFF4A8g
Behavior after my fix: https://youtu.be/bVLgi16Qnkg

**Comment by lowbg** [comment]
working perfectly well done  keader
