### ISSUE TITLE
Take their Rear - Very low droprate

### ISSUE THREAD

**Issue by UniversalSoldier1985** [WoWManiaUK/Redemption#4516]
**Links:**
https://www.wow-mania.com/armory/?quest=12216

**What is Happening:**
Grizzlys should drop Grizzly Flanks but the droprate is ridicilous low

**What Should happen:**
Upgrade the droprates on the bears.

**Comment by Rushor** [comment]
will update that to a better value.

**Comment by svijetlo** [comment]
![image](https://user-images.githubusercontent.com/61908373/80815766-8b036200-8bce-11ea-8ace-e087d3b12f9f.png)
those are drop rates so not every one should drop could be person just has bad luck

**Comment by jeyrella** [comment]
current value seems correct vs retail.  @Rushor what changes are you proposing?

**Comment by Rushor** [comment]
nah, those values from wowhead are never correct because it also adds number from kills of player who are not having the quest.

that's why sometimes you also get a 95 % dropchance for actually a 100 % drop on a head or sth.

most items can have a ~10 percent higher chance

**Comment by jeyrella** [comment]
ok database matches armory at 23%.  That's a reasonable rate, I will check actual on PTR

**Comment by svijetlo** [comment]
i just did fast test 10 kills 3 drops then took other toon 10 kills 5 drops , that seams fine to me

**Comment by jeyrella** [comment]
sounds fine.
Sorry @UniversalSoldier1985 , sounds like you just had a case of really bad luck :(
