### ISSUE TITLE
Hunter quest. Taming the beast(surf crawler) - durotar

### ISSUE THREAD

**Issue by asp1s** [WoWManiaUK/Redemption#4518]
**Links:**
https://tbc-twinhead.twinstar.cz/?quest=6083

**What is Happening:**
Cant tame surf crawler, checked 5 times. Another hunter had same problem

**What Should happen:**
Surf crawler should be tamed

**Comment by Aristo14** [comment]
make sure to abandon previous pet in this questline. 

tame>dismiss>tame>dismiss>tame>dismiss

No you learned how to tame and you can go tame a wolf as you should ;)
