### ISSUE TITLE
[Quest]Time for Answers

### ISSUE THREAD

**Issue by Theragrim** [WoWManiaUK/Redemption#4519]
My friend and I picked up the quest from quest giver Matthias Lehner in Sindragosa's Fall, but we couldn't deliver it to him at the Court of Bones. NPC was there with yellow question mark, but was unresponsive. 
Filed a ticket and GM Psygoa attempted to help by killing and removing the npc several times (including killing him and waiting for him to respawn after 5 min), having us delete cache and reload the game, disable addons, make sure that we had the correct client (WoW-Mania 2.6.0, and launcher from Discord link). Disbanding group also didn't help.

GM Psygoa asked me to file this bug report and then awarded quest completion, but we both can't pick up the follow-up.

Keep up the good work

EDIT: I forgot to mention, we've done pretty much every quest we can, bar raid quests and some argent tournament ones, so I don't think it would be lack of pre-requisites.

**Comment by Rushor** [comment]
maybe phasing related or quest was not completed for player

**Comment by Theragrim** [comment]
We had a phasing issue as well with Orbaz (again both of us), but a GM porting us to the right phase fixed that np.

**Comment by wow-mania** [comment]
that happens when player skip quests

**Comment by Theragrim** [comment]
We've tried to do all quests as we came up on them. We got northrend loremaster already but we'll check to see if there are more quests that we haven't done.

**Comment by svijetlo** [comment]
will test it tomorrow all but i did Matthias Lehner quest line on 3 toons and it worked wo problems

**Comment by svijetlo** [comment]
just did it on 2 toons completed quest wo problems and got next one in line up **The Hunter and The Prince**

**Comment by Theragrim** [comment]
I guess that is it, I logged in today after reading this and could pick it up. Thanks for your time.

**Comment by Theragrim** [comment]
Couldn't edit last comment so, to clarify, we went there while doing the Argent tournament daily at that place, so the phase must have prevented us from interacting.

**Comment by svijetlo** [comment]
> Couldn't edit last comment so, to clarify, we went there while doing the Argent tournament daily at that place, so the phase must have prevented us from interacting.

that is your problem ;) those 2 interact with phasing there so you will eather do one or other
