### ISSUE TITLE
[QUEST] The Nightmare Manifests (scepter of shifting sand ques-line) 

### ISSUE THREAD

**Issue by svijetlo** [WoWManiaUK/Redemption#4520]
**Links:**
http://www.wow-mania.com/armory?quest=8736

**What is Happening:**
1. ones you get to spot where quest should start dragon fall form sky and and hover half in lake
![WoWScrnShot_050220_113556](https://user-images.githubusercontent.com/61908373/80860886-129eae80-8c6b-11ea-83d8-2bbb95b0a976.jpg)
2. ones event start dragon fly to middle of village and hovers half in ground
![WoWScrnShot_050220_114051](https://user-images.githubusercontent.com/61908373/80860918-5ee9ee80-8c6b-11ea-98d7-65532cb3c26d.jpg)
3.  lot more shadow adds should spawn and Keeper Remulus should stay help you fight here he just walks off

**What Should happen:**
1. Dragon should stand in middle of lake 
2. dragon should fly and land in middle of village where quest is taking place 
3. lot more adds need to be there Remulus need to stay and help you fight 
video show how it should look https://www.youtube.com/watch?v=vAsyIbNokao
NOTE: tho the quest is still working and you can finish it will add it to low priority

**Comment by Rushor** [comment]
.mod rep 910 4500000000000 

for testing. https://www.wow-mania.com/armory/?quest=8735 as previous quest is required

**Comment by Rushor** [comment]
will fix the first 2 points. the 3rd one is to risky for low level players in that zone. will not change that :)

**Comment by Rushor** [comment]
50 percent more spawns added, Eranikus, Tyrant of the Dream no more hover on the bridge + is flying on summon
