### ISSUE TITLE
[NPC] Malfurion Stormrage (scepter of shifting sand ques-line)

### ISSUE THREAD

**Issue by svijetlo** [WoWManiaUK/Redemption#4521]
**What is Happening:**
ones you do 1st part of quest line and get to point where you need 3 shards, for green one in sunken temple when you get to  Shade of Eranikus there are 2  Malfurion Stormrage npc talking bouth offering same quest
![WoWScrnShot_050220_095733](https://user-images.githubusercontent.com/61908373/80861204-44187980-8c6d-11ea-960d-47f3cfd5d094.jpg)

**What Should happen:**
only one  Malfurion Stormrage need to show up at start of room do a bit of talk and offer you quest 
NOTE: quest ones taken form one npc will be gone on 2nd so it can be don normally ergo low prio

**Comment by Sharuzan** [comment]
Confirmed: 2 Malfurions spawn.

**Comment by Rushor** [comment]
are those instantly spawning both together? which quests are neededto trigger that?

**Comment by Sharuzan** [comment]
https://classic.wowhead.com/guides/scepter-of-the-shifting-sands-scarab-lord-legendary-mount

I followed what I could find online with this questline and I used that guide primarily.

**Comment by svijetlo** [comment]
The Charge of the Dragonflights  if you complete that quest and go there you will see that not as that is trigger for it
