### ISSUE TITLE
DK Silenced/Pacified

### ISSUE THREAD

**Issue by deathbringer93** [WoWManiaUK/Redemption#4522]
**Links:**

**What is Happening:**My 62lvl DK is silenced and pacified, he cant attack do spells or open a Death Gate but it doesnt show that anything is casted on him. I think I went throuh all the quests 
 in the chain. The light of dawn was the last quest i did. The character is in Outland now and can't go back to Ebon Hold to see if there are other quests.

**What Should happen:**

**Comment by WhitephoenixTheBunny** [comment]
Kill yourelf or open a ticket
