### ISSUE TITLE
Chill out, Mon - The item Snow of Eternal Slumber isnt on the fountain

### ISSUE THREAD

**Issue by UniversalSoldier1985** [WoWManiaUK/Redemption#4523]
**Links:**
https://www.wow-mania.com/armory/?quest=12137

**What is Happening:**
The quest Chill out, Mon - The item Snow of Eternal Slumber isnt on the fountain next to Gan'Jo it should be. Ergo I cant put it on 5 Drakkari Spirit Particles. Phase issue!

**What Should happen:**
The item Snow of Eternal Slumber should be to pickup in the fountain

**Comment by GM-Osyris** [comment]
looked like item was in and out of phase to me.

**Comment by wow-mania** [comment]
Needs to be confirmed.

**Comment by Sharuzan** [comment]
<img width="894" alt="Quest" src="https://user-images.githubusercontent.com/47272908/80912747-75fa1080-8d3f-11ea-9fdf-904877cb415b.png">

Confirmed :)

**Comment by Sharuzan** [comment]
Quest item is missing while in the spirit world.
<img width="433" alt="Quest" src="https://user-images.githubusercontent.com/47272908/80912808-020c3800-8d40-11ea-9a46-3a2747d8c89f.png">
<img width="433" alt="Quest1" src="https://user-images.githubusercontent.com/47272908/80912811-03d5fb80-8d40-11ea-8a22-e4bca3d9ca84.png">

https://www.youtube.com/watch?v=eBTimzMAtlU&t=10s at 0:10 we see the player pick up the item in the spirit world. Which is what should happen.

Item suddenly appears when you have been returned to the world of the living by Gan'Jo and you can then loot the item.

Confirmed bugged :)

**Comment by Rushor** [comment]
chest in both phases there now

**Comment by jeyrella** [comment]
Chest sparkles and can be looted both in the spirit world and after being returned to the world of the living.
