### ISSUE TITLE
[ICC] Trash mobs around Blood Orb

### ISSUE THREAD

**Issue by Keader** [WoWManiaUK/Redemption#4527]
Has some trash mobs around blood orb objects (blood prince/blood queen room)
When combat start, 1 npc will try get the orb.
They need be immune to desorient effects, or players can just use blind on him and get the orb.
Correct behavior is: only be able to get orb, if kill that npc, because he must be immune to everything that interrupt cast.

**Comment by bLeyaa** [comment]
orb still respawns after being used btw
