### ISSUE TITLE
[Spell/Druid] Ferocious Bite + ClearCasting

### ISSUE THREAD

**Issue by Keader** [WoWManiaUK/Redemption#4529]
When feral druids have clear casting, they should not use any energy in ferocious bite.
Problem is: in current state, when you use ferocious bite, having clear casting, you still lose 30 of energy.
Correct behavior: dont use any energy if you have clear casting.

**Comment by jeyrella** [comment]
Keader, I think this maybe was tested last month and thought invalid?
https://github.com/WoWManiaUK/Redemption/issues/4393
Someone should test this one

**Comment by Keader** [comment]
Hmm, checking https://github.com/WoWManiaUK/Redemption/issues/4393#issuecomment-611113608
it's invalid xd
