### ISSUE TITLE
[Quest] Buggy companions during "The Earthen Oath"

### ISSUE THREAD

**Issue by yani** [WoWManiaUK/Redemption#4531]
**Links:**
Current: https://youtu.be/xkqm4pr7j3U
Blizz: https://www.youtube.com/watch?v=Bo5pSdZrgqs

**What is Happening:**
The spawned companions remain on their last location after killing a target. They also do not keep a distance from eachother. It's also possible to toggle their aggressive/defensive/passive stance.

**What Should happen:**
They should keep following you and keep their distance from eachother. There should also be no way to toggle between aggressive/defensive/passive stance.

**Comment by jeyrella** [comment]
Whilst it could be improved, doesn't break the gameplay or stop quest being completed.  Marking P low.

**Comment by Rushor** [comment]
cannot be changed for now
