### ISSUE TITLE
 [NPC] Veranus can get stuck at a bridge near Ulduar

### ISSUE THREAD

**Issue by yani** [WoWManiaUK/Redemption#4532]
It's possible for Veranus to get stuck at [36.46, 31.38].

![image](https://user-images.githubusercontent.com/6956790/80915620-cd09e080-8d53-11ea-8ff2-0c18a007fc88.png)

**Comment by jeyrella** [comment]
Confirmed.  Have seen this 3 or 4 times and never managed to get screenshot.

Also becomes non-attackable when stuck like this.  As this is the target of an achievement, and prevents TLPD spawning, could do with being improved.

**Comment by Drostthehunter** [comment]
@jeyrella Veranus is not affiliated by any means to TLPD, Veranus is a quest chain in the Hodir questline, the drake that shares the spawn with TLPD is Vyragosa :D

**Comment by Rushor** [comment]
pathing adjusted a bit, should be better now

**Comment by Rushor** [comment]
this quest http://www.wowhead.com/quest=13051/territorial-trespass triggers the spawn

**Comment by jeyrella** [comment]
> @jeyrella Veranus is not affiliated by any means to TLPD, Veranus is a quest chain in the Hodir questline, the drake that shares the spawn with TLPD is Vyragosa :D https://www.wowhead.com/quest=13050

Ooops :D  I shouldn't do this so late at night,  thanks Drostan :D

Anyways, not sure that quest 13051 spawns this copy of Veranus that gets stuck;  on placing the egg Veranus can still be seen static in GM mode at the bridge and never seems to move in any phase.  So I think the symptom seen by players is somehow the phase changing and never getting reset.
Am not sure what causes this.

Regardless, that version does now seem higher above the bridge, so in any event it shouldn't get "stuck" in terrain.

**Comment by jeyrella** [comment]
Regression.
![image](https://user-images.githubusercontent.com/46089380/88294989-c35d9c80-ccf4-11ea-91d5-1fa399e6e6a0.png)

**Comment by Rushor** [comment]
try again pls, this is because of the updated and removed duplicates in event_scripts

**Comment by jeyrella** [comment]
Fixed
![image](https://user-images.githubusercontent.com/46089380/88479099-c5b63580-cf44-11ea-90a0-ffab2d292b99.png)

Also, quest Territorial Trespass still works.
![image](https://user-images.githubusercontent.com/46089380/88479032-5e988100-cf44-11ea-910d-fa687ad921cd.png)
