### ISSUE TITLE
Maniac s Hacker-item

### ISSUE THREAD

**Issue by needek** [WoWManiaUK/Redemption#4534]
**Links:**
https://www.wow-mania.com/armory/?item=92002

**What is Happening:**
I bought this gun from you for 25 coins, but it doesn't work. I can deploy it, but it doesn't give me any stats. I can not insert Enchant and runeforge. It can't be seen in my hand. 
It does not damage

**What Should happen:**
Can you please fix it?

**Comment by wow-mania** [comment]
Get our client! Item works. 
This is just one of the many problems you will have if you don't.
