### ISSUE TITLE
[NPC] Dr. Terrible can spam his yell

### ISSUE THREAD

**Issue by yani** [WoWManiaUK/Redemption#4537]
For some reason **Dr. Terrible** at **Valhalas** spammed his yell text.

I don't have much more info as I just ran in the area.

![image](https://user-images.githubusercontent.com/6956790/81018499-ec446300-8e64-11ea-950a-79488e7f3822.png)

**Comment by yani** [comment]
I think it might have something to do with the **Valhalas Vargul**. As it happens around them and they spam a weird combat sound during these spams.

I'm also unable to leave combat in this area. Have to resort to .cl

**Comment by jeyrella** [comment]
I can reproduce this.  This occurs when player takes quest 13043 https://www.wow-mania.com/armory/?quest=13043 The Sum is Greater than the Parts, enters Nergeld, engages Dr. Terrible but runs with Nergeld out of the room and engages the Valhalas Vargul in doing so - i.e. chickens out of the fight.

Player is auto-dismounted  and runs, but Dr Terrible is left in a strange loop with Nergeld at the entrance way:
https://youtu.be/M1Ix8p6qnj0

**Comment by jeyrella** [comment]
![image](https://user-images.githubusercontent.com/46089380/81020866-b81b7300-8e61-11ea-9510-97cbf1cbec62.png)

**Comment by Rushor** [comment]
issue was related to maps. all creatures can now walk correctly and no more endless evade/entercombat spamms.

also:

- the creatures will now all attack nergeld
- nergeld should NOT be ablt to move (fixed that)
- later this day a fix will be applied that increases the range of the first ability of nergeld (punch) to hit in a bigger distance
