### ISSUE TITLE
[Dungeon] Anub'arak uses impale continuously and does not resurface

### ISSUE THREAD

**Issue by lowbg** [WoWManiaUK/Redemption#4538]
**Links:**
https://www.wowhead.com/npc=29120/anubarak

**What is Happening:**
on p1 its fine as soon going under the ground (p2) and start to use this spikes(impale)  not coming  up  after staying under the ground and  going again and again 
https://youtu.be/Fs9prccrwXo

**What Should happen:**
https://www.youtube.com/watch?v=JET5C4cwiYs
after went underground and we kill the spawned mobs should come back up 
not happening after we kill mobs

**Comment by Oganku** [comment]
If a pet starts attacking the adds outside the webbed arena or a party member dies and runs back to the instance and spawn at the start, the adds will take longer to die. The boss does come up properly after adds die though.

**Comment by svijetlo** [comment]
yap seen it happen what oganku told that is problem , add going somewhere other or fighting pet outside of platform

**Comment by Rushor** [comment]
hm something that can be done to prevent adds to go outside of the web circle?

**Comment by lowbg** [comment]
@Oganku the thingy was no one of the pets was fighting outside we start together the boss and everyting went good until  the  boss go under  pet can't go out if there is a web wall  we try  that as well but didnt happend  everyone was inside the boss area + pet

**Comment by Oganku** [comment]
Pets that are on aggressive or you can't control (shaman elementals) will aggro to the spiders by default as they run down and will stall their entry in the arena. Also if for some reason a party member joins late or ressurects at the entrance, the spiders get stuck in the ceiling trying to get to him. Only way to fix is to wait for it to reset or have that person run down

**Comment by svijetlo** [comment]
ye what oganku told i seen it happen before only in those situations

**Comment by Keader** [comment]
try now pls.
