### ISSUE TITLE
[Boss] Onyxia

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#4539]
**Links:** https://www.wow-mania.com/armory/?npc=36561#abilities
https://www.wow-mania.com/armory/?spell=68960#triggered-by
https://www.wowhead.com/spell=18500/wing-buffet

**What is Happening:**

1. The big adds summoned in phase 2 of Onyxia's boss fight, [Onyxian Lair Guards](https://www.wow-mania.com/armory/?npc=36561#abilities) use an ability called [Ignite Weapon](https://www.wow-mania.com/armory/?spell=68960#triggered-by) to empower their melee attacks, causing them to deal AoE fire damage around the target struck. However, while this empowered attack is active, the Lair Guards  seem to have infinite range on their melee attacks. This lets them melee a target from super far away, even ranged or healers and cause that explosion around them before they're even remotely close to the tanks. As a healer I would always be highest on threat as those adds spawned and would instantly be targeted by the attack while the mobs were still halfway down the corridor to the main room. The explosion around the target hurts and that's fine, but it shouldn't magically extend the range of the mob and allow him to randomly whack a ranged group if one person were to pull aggro for a second.

2. Onyxia's [Wing Buffet](https://www.wowhead.com/spell=18500/wing-buffet) can be completely negated by just having the tank stand against a wall. If they are close enough to it, they will be very close to 'inside the wall' according to line of sight and that ability will completely miss the tank. This makes tanking Onyxia twice as easy, as one of her 2 main attacks currently doesn't really work. Even if a tank doesn't try to avoid it on purpose, the first couple buffets will hit him properly, push him against a wall and then make him avoid all subsequent ones without trying.

**What Should happen:**

1.  The explosion around the target hurts and that's fine, but it shouldn't magically extend the range of the mob and allow him to randomly whack a ranged group if one person were to pull aggro for a second. They should just retain their regular melee range and have their next attack be empowered.

2. Wing buffet shouldn't be negated entirely by simple standing near a wall.

**Comment by Keader** [comment]
try now.
