### ISSUE TITLE
Transmogrification removal

### ISSUE THREAD

**Issue by ukoz** [WoWManiaUK/Redemption#4540]
If I remove transmogrification item still transmogrified on next login.
What do I exactly do to remove it?

Reproduce:
1. Click item slot (it highlighted) by transmogrification NPC
2. Click remove transmogrification
see it removed
can click save set or not, it do nothing
can put item to bank or leave it equipped
3. Switch character or Relog (with cache deleted)
4. Item still transmogrified on next logon, not on character select screen but when enter world.

**Comment by wow-mania** [comment]
save after remove.

**Comment by ukoz** [comment]
save after remove do nothing
it said in my post

**Comment by ukoz** [comment]
tested right now

Reproduce:
1. Click item slot (it highlighted) by transmogrification NPC
2. Click remove transmogrification, see it removed
3. Click Back
4. Click Manage Sets
5. Click Save set
6. relog
7. Still transmogrified on next character enter world.

**Comment by svijetlo** [comment]
i just did it all on 6 toons works just fine to me , if i remveo it it is removed if i add mog it is there , after relog after hard crash etc

**Comment by ukoz** [comment]
what proof you need?
i did it with GM by my side
he saw item transmogrified back on next logon

**Comment by jeyrella** [comment]
Unfortunately, we can't reproduce it despite significant time spent testing this.  Neither have we had widspread reports from multiple players that they are facing the same issue.
The only conclusion we can draw is that there must be some issue specifically with your character or your account causing this, which is not something we can fix server-side.

If you do have more evidence on other toons of the same thing happening, please post it - preferably with a video of the issue - and we will certainly be more than happy to investigate.
