### ISSUE TITLE
Transmogrification removal 2

### ISSUE THREAD

**Issue by ukoz** [WoWManiaUK/Redemption#4541]
https://github.com/WoWManiaUK/Redemption/issues/4540

still bugged

**Comment by wow-mania** [comment]
please do not add the same issue again.
this is a player issue not server-side

**Comment by ukoz** [comment]
One GM saw it bug.
Other GM close ticket because he not see.

**Comment by ukoz** [comment]
if you new you github it how it work
people open new tickets with link to issue if it not fixed
