### ISSUE TITLE
[Enchanting] Weird message when trying to enchant the wrong item

### ISSUE THREAD

**Issue by yani** [WoWManiaUK/Redemption#4542]
**What is Happening:**
The message **"Must have a Cloth equipped"** is shown when using a wrist enchant on gloves.

**What Should happen:**
I think there should be a better error message for this.

![image](https://user-images.githubusercontent.com/6956790/81080301-e005e780-8ef0-11ea-8b2c-c9e925c7c3af.png)

**Comment by wow-mania** [comment]
this is the original error message from 3.3.5a
