### ISSUE TITLE
[Quest] Territorial Trespass - 13051 - Storm Peaks

### ISSUE THREAD

**Issue by jeyrella** [WoWManiaUK/Redemption#4546]
**Links:**
https://wow-mania.com/armory/?quest=13051

**What is Happening:**
Veranus lands successfully, Thorim script runs successfully and they fly off, but the quest completion is not flagged properly.
Very likely linked to #4532

**What Should happen:**
Quest should be marked completed after Thorim & Veranus fly away.

**Comment by Rushor** [comment]
try after server has restarted. i will let you know

**Comment by farmerpker** [comment]
This appears to still be an issue. Tried dropping the quest and picking it up again but is not resolved. Never receive the completion flag after Thorim mounts and flies off on Veranus.

**Comment by Rushor** [comment]
the fix will be applied with next update

**Comment by UniversalSoldier1985** [comment]
The quest still not completes at the moment.

**Comment by jeyrella** [comment]
Yep.  This once again seems not to complete.  Uploading YT now.

**Comment by jeyrella** [comment]
Also redid the chain starting from https://wow-mania.com/armory/?quest=12924 on different toon, same thing.  Thorim flies off with Veranus and the quest does not complete.
This definitely worked after the first fix on the 6th, so has somehow regressed.

**Comment by Rushor** [comment]
hm okay wait

**Comment by Rushor** [comment]
sql got lost i guess pls recheck

**Comment by jeyrella** [comment]
Tested on two toons again, still does same thing.  Thorim flies off with Veranus and the quest does not complete.

**Comment by Rushor** [comment]
try now

**Comment by svijetlo** [comment]
as soon he land on dragon quest will be don now

**Comment by gh0ster** [comment]
just tested again after a restart and unfortunately still not completing quest.
Thorim jumps on back of Veranus and slowly flies off.. no completion

**Comment by Aristo14** [comment]
fixes are made in the PTR realm (Frostmourne) and the results of that will only be active for you when these are updated to the live play realm (Redemption) This usually happens on every tuesday.
