### ISSUE TITLE
[Spell] Disarm Bug with Heirloom weapons

### ISSUE THREAD

**Issue by Kultivater** [WoWManiaUK/Redemption#4547]
I reported this bug a week or so ago, and it was closed because they claim to be unable to reproduce the bug. I said I'd repost this once I have proof, and I have it now. I took 3 screenshots of it happening, which I will post below before  I copy/paste the text from the post:

![WoWScrnShot_050520_225005](https://user-images.githubusercontent.com/64390861/81137407-54a64980-8f24-11ea-9a6e-cf5b3297c704.jpg)
![WoWScrnShot_050520_225019](https://user-images.githubusercontent.com/64390861/81137410-58d26700-8f24-11ea-98f2-3700806fdfe3.jpg)
![WoWScrnShot_050520_225028](https://user-images.githubusercontent.com/64390861/81137414-5d971b00-8f24-11ea-9548-5b7431c2b0e1.jpg)

I searched for this bug and found a similar report that claims to have been fixed, but it's not exactly the same. I'll explain: The bug I found in the search is: Whenever your character is disarmed, and your crit chance switches to unarmed, the crit chance doesn't change back once disarm ends.

What is Happening:

My issue is almost the same as above, only instead of crit chance, it's minimum weapon damage. This happened on my lvl 35 paladin. When he is disarmed, the maximum lisetd weapon damage(under "Melee" tab on character sheet) changes back to normal after disarm ends, but the minimum damage remains at what I'm assuming is unarmed minimum damage. The only way to fix it(that I've found so far) is to swap weapons, or simply unequip it and re-equip it. If you wish to recreate this bug, then take a melee character to an NPC that disarms, pull up your character sheet and watch the numbers for weapon damage before, during, and after disarm effects take hold.

What Should happen:
Weapon damage should switch back to that of the weapon being used after disarm effects end,

On a side note: I want to mention that I didn't notice whether or not the crit chance is affected by this(or anything else is). I will update this issue if I find anything else relevant to it.

**Comment by Rushor** [comment]
can confirm this now

**Comment by svijetlo** [comment]
could it be item related i see he uses airloom weapon , i try to reproduce this with lvl 80 toon and Sm and it did not happen

**Comment by Keader** [comment]
Yeah, happens only with heirloom.
fixed.

**Comment by svijetlo** [comment]
damn im smart :D

**Comment by Kultivater** [comment]
I'm not positive, but I don't think I had the heirloom when this first happened to me. The first time it happened was in Southshore against a Syndicate Thief, and I wanna say I had a blue axe at the time. I guess there's only one way to find out. If one of the GMs wants to temporarily give me another weapon of some kind and let me test it out on those raptors you see there in the screenshots, I'll see if I can reproduce it.

**Comment by Rushor** [comment]
yeah for me was bugged aswell as lowlevel toon just with normal weapon
