### ISSUE TITLE
[Raid] Valithria Dreamwalker Berserk

### ISSUE THREAD

**Issue by slaniaxx** [WoWManiaUK/Redemption#4550]
https://github.com/WoWManiaUK/Redemption/issues/4464

^^ as per the fix here, she should berserk at 7 minutes.
She berserked at 4.30 minutes today (others told me similar short berserk time fights randomly, but it's the only time I confirmed myself)

Edit: 2nd pull, zerked at 2.30 minutes...
Edit2: Also observed portal bug (portals spawning indefinitely over and over again before the first one is over) on the 2nd pull

**Comment by slaniaxx** [comment]
> #4464
> 
> ^^ as per the fix here, she should berserk at 7 minutes.
> She berserked at 4.30 minutes today (others told me similar short berserk time fights randomly, but it's the only time I confirmed myself)
> 
> Edit: 2nd pull, zerked at 2.30 minutes...

**Comment by Tankjnr** [comment]
Here is the recording as proof :)

https://youtu.be/ABJcC7Ndw-Y

Kind Regards

Tankjnr

**Comment by svijetlo** [comment]
i did notice rly low healing on boss could it be connected to that somehow 
tho i did seen before valy fight bug out and spawn way to uch adds and portals if you wipe on boss and pull again

**Comment by Tankjnr** [comment]
Yeh healing was abit low. but if healers could do all bosses up2 vali then it shouldnt have been an issue. as mentioned above first pull she went zerk at 4:30 and second one at @2:30

**Comment by wow-mania** [comment]
if this will make the fight easier we will not fix it

**Comment by Tankjnr** [comment]
@wow-mania the Beserk timer should be 7 minutes if im not mistaken.

**Comment by Rushor** [comment]
i guess the timer is not resetted after a wipe

**Comment by slaniaxx** [comment]
"if this will make the fight easier we will not fix it" umm rather than easier...
when this bug happens the fight is nigh-impossible, especially a 2.30 minute situation.

**Comment by svijetlo** [comment]
yes i think timers keep on going after wipe it does not reset after 1st pull i will test it later 
it does not make fight easy it makes fight as it should be , you have 7 min to heal boss iof you fail you fail you need more heals

**Comment by svijetlo** [comment]
berserk time is proper 7 min every time now even if you wipe and start encounter again or do not heal boss at all
