### ISSUE TITLE
[Mount] The mystic runesaber mount is not the right size

### ISSUE THREAD

**Issue by Rupuu** [WoWManiaUK/Redemption#4551]
**Links:**
![image](https://user-images.githubusercontent.com/62323191/81326367-66adf680-90a2-11ea-9a6c-f8ae4107bff2.png)

**What is Happening:**
When i ride the mount it's so small, it looks like a gnome should ride it and it's just weird. I compered it to the normal tiger mount and the normal one is like 2x bigger almost. I saw pictures on the interned and the runesaber didnt look that small there for sure.

**What Should happen:**
The size of the runesaber should look normal, like it's made for a human not a gnome

**Comment by Rushor** [comment]
can you post the item id of the mounts pls

**Comment by Rupuu** [comment]
how can i see the id ?

**Comment by Rupuu** [comment]
> can you post the item id of the mounts pls
how can i see the id ?

**Comment by Rupuu** [comment]
> can you post the item id of the mounts pls

i found it, its 122469

**Comment by Rushor** [comment]
thank you

**Comment by Rushor** [comment]
ah need dbc update sadly

**Comment by Rupuu** [comment]
> ah need dbc update sadly, so cannot fix that

so that cant be fixed and it's going to stay that way ?

**Comment by svijetlo** [comment]
it can be fix but change in mount size and appearance need client update

**Comment by Rupuu** [comment]
> it can be fix but change in mount size and appearance need client update

so i just need to wait for that then ?

**Comment by svijetlo** [comment]
compared with 3 different cat type mounts , also added img of size of mount compared to character 
![WoWScrnShot_050820_010607](https://user-images.githubusercontent.com/61908373/81353129-8e17ba00-90c8-11ea-8c04-a5574785496b.jpg)
![WoWScrnShot_050820_010618](https://user-images.githubusercontent.com/61908373/81353132-9112aa80-90c8-11ea-8c21-900c2fad978b.jpg)
![WoWScrnShot_050820_010631](https://user-images.githubusercontent.com/61908373/81353135-93750480-90c8-11ea-8b31-2728b78767a4.jpg)
![monture-sabrerune-mystique](https://user-images.githubusercontent.com/61908373/81353149-9b34a900-90c8-11ea-9b21-cbdd8572102f.jpg)

**Comment by jeyrella** [comment]
Reopening for @wow-mania 's attention.  Most likely will need a client change, which are maintained separately to here.

**Comment by lowbg** [comment]
tested on few  toons looks the same.
Checked online videos  as welll for me this tiger it  separate from others and thats why is so small every mount should be  unique with someting right i dont think thats a problem let my colleges say someting about that as well i found it out for normal this mount .
