### ISSUE TITLE
QUEST BUG LVL 80 TERRITORIAL TRESPASS

### ISSUE THREAD

**Issue by Mingozzi** [WoWManiaUK/Redemption#4552]
**Links:**

**What is Happening:* 
I'm trying to complete lvl80 quest "Territorial trespass" in Storm Peaks. I'm suppose to put an egg on top Broodmother's nest(a dragon). Thorim controls her but the they go away and the quest doesn't complete.

**What Should happen:**
Thorim should control the dragon and the quest should be complete

**Comment by wow-mania** [comment]
pretty sure i works

**Comment by jeyrella** [comment]
Duplicate of #4546
