### ISSUE TITLE
[Achievment/Statistic] Lord Marrowgar/LDW hc/nm statistics share

### ISSUE THREAD

**Issue by slaniaxx** [WoWManiaUK/Redemption#4554]
**Links:**

**What is Happening:**
For Marrowgar and LDW, the 25 man normal/heroic kill counts for both.
For example, a player who killed marrowgar on 25nm, gets 25hc statistic. 

**What Should happen:**
a 25nm kill should count for 25nm statistic, while a 25hc kill should count for 25hc kill statistic.

Same problem seemingly exists on 10 man as well

**Comment by jeyrella** [comment]
I have reported this on https://github.com/WoWManiaUK/Redemption/issues/4051 previously.  Unfortunately this cannot be fixed.
