### ISSUE TITLE
[NPC] Bad cannon placement in Wintergrasp

### ISSUE THREAD

**Issue by Blackhelm36** [WoWManiaUK/Redemption#4555]
**Links:**

**What is Happening:**
Wintergrasp 
Flamewatch tower, cannons incorrectly placed. Upper deck front mount has two cannons located there at the same time, lower deck 1 cannon placed inside inner wall.
![wow 2020-05-07 15-41-48-662](https://user-images.githubusercontent.com/42321026/81481613-471fe680-91e6-11ea-8527-f1c031bf82e7.jpg)
![wow 2020-05-07 15-42-39-841](https://user-images.githubusercontent.com/42321026/81481641-7171a400-91e6-11ea-8981-26b75ffe5dad.jpg)

Winter's Edge tower, guard at bridge is located under ground.

![wow 2020-05-08 11-32-03-658](https://user-images.githubusercontent.com/42321026/81481661-7f272980-91e6-11ea-8f8f-aba95a63b8de.jpg)

**What Should happen:**Targets should be located in original positions

**Comment by wow-mania** [comment]
Cannons are in the correct position. Someone moved them during the battle.

**Comment by Sharuzan** [comment]
Confirmed - Cannons are now in the right positions.

Regarding the Alliance guard, will need some testing later, couldn't check it out due to Alliance holding WG. 
Horde guards and Alliance guards on either side of the bridge were in the right positions.

**Comment by wow-mania** [comment]
You removed the fixed but did not mention what is wrong.

**Comment by Rushor** [comment]
If the cannons are really movable or sth i can add a fix for it aswell

**Comment by svijetlo** [comment]
those cannon have / had same issues like ones on wall in Argent vanguard (icecrown) sometimes theyr position shifts a bit , atm they are non movable (apart form rotation left /right ofc ) and properly placed

**Comment by Blackhelm36** [comment]
the guard placement on middle tower is correct but elevation places it below ground on both horde and alliance.
