### ISSUE TITLE
[Quest] Wanton Warlord

### ISSUE THREAD

**Issue by Wolch** [WoWManiaUK/Redemption#4556]
**Links:**
https://wow-mania.com/armory/?quest=12151
(https://www.wowhead.com/quest=12151/wanton-warlord)

**What is Happening:**
Cannot take the quest on one of my alts. I click on the quest giver, then click on the quest - and the game stops responding. It looks like as if the server is about to crash: I can move, but cannot perform any other actions. I have to exit the game with alt-f4. I did all previous quests in that chain without any problems.
Tried to clear cache; tried to disable all add-ons. Nothing helps. Talked to GM, Psygoa reset the quest giver, but it didn't help either.
I am using WoW-mania client 2.6.0 and start the game via launcher.

**What Should happen:**

**Comment by jeyrella** [comment]
Seems to work just fine.
https://youtu.be/cuxn7VSKDMc

Will need more detail on class/race/spec, otherwise have to assume it's something local with your specific toon/client

**Comment by Wolch** [comment]
> Will need more detail on class/race/spec, otherwise have to assume it's something local with your specific toon/client

Lvl 80 blood elf paladin, name Agraell. Doing quests for the achiev. I have a lvl 70 alt, will try to do the quest with him when I lvl a bit more and see if I have same issue on him as well.

**Comment by jeyrella** [comment]
As it happens I have a Belf pala on test realm already.  Just picked it up fine with that toon too.  Also with an Undead mage and human priest.
At this point I have to surmise this is an issue with your client and/or character, not a server issue.
