### ISSUE TITLE
[Quest] Desert Recipe quest serie

### ISSUE THREAD

**Issue by taniosnassar** [WoWManiaUK/Redemption#4559]
**Links:**
https://classic.wowhead.com/quest=8307/desert-recipe

**What is Happening:**
The NPC (Calandrath) that is supposed to give the quest is not showing any "!" (ss attached)

**What Should happen:**
This quest has no prerequisites (except for the player which was met) and it should appear with that NPC.

I have discussed the issue ingame with Psygoa and Osyris and I was asked to log the issue here. Please let me know if you need more info.

![unknown](https://user-images.githubusercontent.com/65182289/81585082-4e005200-93bc-11ea-8d6d-b007c2b177ee.png)

**Comment by wow-mania** [comment]
The quest requires cooking skill 285.
Please use our armory as reference.

**Comment by taniosnassar** [comment]
Hello Janitor,
I'm sure that I had that level of cooking if not higher.
But anw i don't think this is as urgent as other important issues.
Thanks

**Comment by svijetlo** [comment]
quest works fine guilde did it 2 days ago

**Comment by jeyrella** [comment]
@taniosnassar As janitor says, works fine when you have cooking skill 285.  If you don't have cooking skill then it will not be available.
