### ISSUE TITLE
Stealth and pet companions

### ISSUE THREAD

**Issue by Myzeriel** [WoWManiaUK/Redemption#4560]
**Links:**
https://www.mmo-champion.com/threads/1081781-Can-opposing-faction-see-your-vanity-pet-while-stealthed

**What is Happening:**
pet visible

**What Should happen:**

pet goes stealth with me/disappear while im in stealth - reappears when im out of stealth

**Comment by jeyrella** [comment]
The thread you quoted is from Cataclysm era.  In  that thread:
https://www.mmo-champion.com/threads/1081781-Can-opposing-faction-see-your-vanity-pet-while-stealthed?p=15475162&viewfull=1#post15475162

> Pets **used to not stealth with you,** now they do.
That would suggest the behaviour was changed with or sometime before Cata.  Do you have any evidence from WotLK?  I could not find much about this.

**Comment by svijetlo** [comment]
introduced in cata , till cataclysmic vanity pets would never go stealth with owner, that is why rogues never had pets around

**Comment by jeyrella** [comment]
Ok, thanks @svijetlo.  Closing for now.  
If anyone has reference material to disprove, we will look at again.

**Comment by svijetlo** [comment]
![image](https://user-images.githubusercontent.com/61908373/81749693-69e32100-94ac-11ea-87a8-d0fb92fb6fd4.png)

**Comment by Myzeriel** [comment]
ok tnx
