### ISSUE TITLE
[Quest] Sniffing out the Perpetrator NPC's remain after quest

### ISSUE THREAD

**Issue by yani** [WoWManiaUK/Redemption#4561]
I submitted an issue for this quest before: #4403

**What is Happening:**
The **Stormforged Pursuer**'s that are spawned during **Sniffing out the Perpetrator** remain after the quest has been completed.

**What Should happen:**
The **Stormforged Pursuer**'s should despawn after they get out of vision of the person completing the quest.

![image](https://user-images.githubusercontent.com/6956790/81757002-acf9c000-94bd-11ea-9b46-0934836a9de8.png)

**Comment by Rushor** [comment]
the sql got lost somehow. the always despawn after 30 seconds now.

**Comment by Sharuzan** [comment]
Confirmed they do despawn.
