### ISSUE TITLE
Bug for quest "I Work... For The Horde!"

### ISSUE THREAD

**Issue by Tsriell** [WoWManiaUK/Redemption#4562]
**Links:**
It's a quest in Hellfire Pennensula, obtained from Megzeg Nukklebust

**What is Happening:**
Nodes are not interactable, but indicate that they are.

**What Should happen:**
Should be able to loot the quest items, temporarily despawning the node and putting it on a cooldown timer.

**Comment by GMMetaxa** [comment]
No valid post. Need links on how it should work and what's happening.

**Comment by Rushor** [comment]
Both objects on both sides should work. There is an issue with the Interaction on those gameobjects you are supposed to collect

**Comment by Rushor** [comment]
https://www.wow-mania.com/armory/?quest=10086

the objects are:

https://www.wow-mania.com/armory/?object=182797
https://www.wow-mania.com/armory/?object=182798
https://www.wow-mania.com/armory/?object=182937
https://www.wow-mania.com/armory/?object=182938
https://www.wow-mania.com/armory/?object=182799
https://www.wow-mania.com/armory/?object=182936

can now all be collected from players

**Comment by Sharuzan** [comment]
Fix Confirmed - nodes containing Salvaged Wood and Salvaged Metal can be interacted with now.
