### ISSUE TITLE
Battered Hilt Quest Chain

### ISSUE THREAD

**Issue by Tamagucci** [WoWManiaUK/Redemption#4564]
**Links:**
https://www.wowhead.com/quest=24564/the-purification-of-queldelar

**What is Happening:**
Hello. I'm on the last part of the battered hilt quest chain and I'm running into a bug.
The part I'm on is the "purification of quel'delar" where these 2 npc's are supposed to be able to teleport me inside Sunwell Plataeu and I'm getting no response. I'm able to talk to them, pick the dialogue to start it but then nothing happens.
I'm unable to further the quest because of it.
I've deleted cache, and dropped and restarted the quest already. Nothing

I'm a female Troll Mage. 
I was mounted when I first tried to talk to the npc's if that matters and got the "You are mounted" error. Maybe that bugged it?
**What Should happen:**
 Talk to a guard in-front of the entrance he will port you inside.

**Comment by jeyrella** [comment]
Be in a raid group.
