### ISSUE TITLE
[Quest] Fortunate Misunderstandings - 12570 - Sholazar

### ISSUE THREAD

**Issue by overkill321321** [WoWManiaUK/Redemption#4565]
**Links:**
qeust:
https://www.wow-mania.com/armory/?quest=12570
NPC:
https://www.wow-mania.com/armory/?npc=28217

**What is Happening:**
When you ask the npc to walk  to their village the bug out and dont move.
This qeust makes you at war with frenzy heart tribe instead of friendly but changes this back on completion so now i am stuck at war with frenzytribe

**What Should happen:**
You should be able to escort them to the nearby village

**Comment by Rushor** [comment]
this used to work for a long time

**Comment by lowbg** [comment]
yep its working i v done that as well  you doing someting wrong

**Comment by svijetlo** [comment]
smt is wrong , when i get to npc he is like corpse on ground , ones i speak to it he say Injured Rainspeaker Oracle says: Home not far. Come! , then teleport one step still looking as corpse on ground and that is where it all stop

**Comment by wow-mania** [comment]
Works.

**Comment by svijetlo** [comment]
@mfranca0009  take a look at it problem is still same

**Comment by Echinaceax** [comment]
### Tested this to and there are a few issues i noticed, Quest is do-able yes but ...

- [ ] The dead on the ground that Svijet mentions is correct for some of them `not all`

![wrong position](https://user-images.githubusercontent.com/39439201/178329281-062fc8a1-1287-4c5c-9aa1-d0fa7a64a2ea.jpg)



there is a dialog that says: `reach down and pull the injured rainspeaker oracle to his feet`

- [ ] Issue is once you click that dialog and he is stood up the dialog should disappear `and it doesnt`

https://i.gyazo.com/ba6c8a72f3f60e95232ef226309943f4.mp4
![image](https://user-images.githubusercontent.com/39439201/178327964-d4f3bd27-b2c9-454b-92dd-7691ac10be7c.png)

- [ ] some of them have bad pathing going through rocks `quest still completed though`

test 1 https://i.gyazo.com/cea0a51ba90a77ac4d476d56f5db49c8.mp4
test 2 https://i.gyazo.com/cf5ab8cda62df976e3870090e2cd30fe.mp4 `showing bad inpcs on his path`
test 3 https://i.gyazo.com/38c70bbdf92d8035941621d9489553ab.mp4 `showing completed`
test 4 https://i.gyazo.com/a6d0ab2412de8b86987793267e0eeb72.mp4 `showing bad spawns`
test 5 https://i.gyazo.com/ba6c8a72f3f60e95232ef226309943f4.mp4 `showing bad pathing`

**Comment by Echinaceax** [comment]
after some more searching it seems that this was a little buggy in 3.3 

![image](https://user-images.githubusercontent.com/39439201/178836807-3461bbeb-e242-4667-862d-c267c9eb03d9.png)
![image](https://user-images.githubusercontent.com/39439201/178836858-91530460-1c5b-465b-b5a6-d77b4ebae9ad.png)

quest is doable if you follow the steps below
