### ISSUE TITLE
[Quest/ICC] Respite for a Tormented Soul (Frost Quarter quest)

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#4567]
**Links:** https://www.wowhead.com/quest=24872/respite-for-a-tormented-soul
https://www.wowhead.com/item=51026/crystalline-essence-of-sindragosa
https://www.wowhead.com/item=50851/pulsing-life-crystal
https://www.wowhead.com/spell=72424/life-infusion
https://www.wowhead.com/spell=72466/soul-preservation

**What is Happening:** The weekly ICC quest for the frost quarter, [[Respite for a Tormented Soul] (10/25 players)](https://www.wowhead.com/quest=24872/respite-for-a-tormented-soul) currently auto-rewards you the quest reward, [Crystalline Essence of Sindragosa](https://www.wowhead.com/item=51026/crystalline-essence-of-sindragosa) for simply defeating her normally.

**What Should happen:** The quest is lacking its mechanics. Upon accepting it, the players are all awarded a [Pulsing Life Crystal](https://www.wowhead.com/item=50851/pulsing-life-crystal) which they need to use on Sindragosa when she is below 20% hp to build stacks of [Life Infusion](https://www.wowhead.com/spell=72424/life-infusion) on the boss. One stack is granted per second spent channeling the item and all players can help build stacks this way. Those stacks last only 10 seconds and have to be maintained and brought up to 30/75 stacks (10/25 man) in order to grant Sindragosa the buff [Soul Preservation](https://www.wowhead.com/spell=72466/soul-preservation). 
The quest reward (Crystalline Essence of Sindragosa) should only drop if the boss is killed while under the effect of that buff.

Explanatory quote from wowhead:
> In order to complete this quest, you need to have multiple people using their Pulsing Life Crystal. (obtained from Valithria Dreamwalker for the random raid weekly) Having multiple people using the quest item, will make the buff Life Infusion stack faster. You CAN have one person do it, but it will go faster the more people that do it. You need to get 30 stacks on her in 10-player, and 75 stacks for the 25-player encounter. She will do an emote when she hits 20% life, and only after that are you allowed to use the item. You have 10 seconds for someone in the raid to use the Pulsing Life Crystal before the entire stack of buffs falls off. If your stacks of Mystic Buffet start to get high, you can hide behind a frost pillar until they drop. But be careful, as you can have the entire stack drop if your raid isn't careful about managing it. Sindragosa gains the buff Soul Preservation once the correct number of stacks are attained.

**Comment by Rushor** [comment]
will check that

**Comment by Rushor** [comment]
okay should only drop now if the stacks (30/75) are applied and only if sindra got the buff (Soul Preservation). Only then the quest loot can be seen.
