### ISSUE TITLE
Klaven's Tower 

### ISSUE THREAD

**Issue by Franciss983** [WoWManiaUK/Redemption#4568]
**Links:**
[Klaven's Tower](http://www.wow-mania.com/armory?quest=2359)

**What is Happening:**
Cant open [Duskwood Chest](https://www.wow-mania.com/armory/?object=123214) in Tower with [Defias Tower Key](http://www.wow-mania.com/armory?item=7923) to get [Klaven Mortwake's Journal](http://www.wow-mania.com/armory?item=7908)

**What Should happen:**
Duskwood chest should be opened with that key to get [journal](url)

**Comment by svijetlo** [comment]
worked perfect fine to me just now , take quest go westfall, pickpocket key form mobs out side tower , climb top of tower sap Klaven, open chest next o him get item be don

**Comment by Rushor** [comment]
you need pickpocket skill to open it - some player forget about that
