### ISSUE TITLE
[SPELL] Counterspell issue

### ISSUE THREAD

**Issue by mrtimelord** [WoWManiaUK/Redemption#4569]
**Links:** 
[Counterspell](https://www.wow-mania.com/armory/?spell=2139)
[Sandfury Witch Doctor](https://www.wow-mania.com/armory/?npc=5650)

**Class:** Mage
**What is Happening:**
Counterspell doesn't prevent the same class of magic from being cast for the 8 seconds as per the spell's description:

`Counters the enemy's spellcast, preventing any spell from that school of magic from being cast for 8 sec. Generates a high amount of threat.`

**What Should happen:**
 It should prevent spells from the same class of magic from being cast for 8 seconds.

I have tested it in Zul'Farrak on the Sandfury Witch Doctors. I have Counterspelled Flash Heal and the NPC was able to instantly cast Healing Ward and vice versa. Both are healing spells.

**Comment by Rushor** [comment]
counterspell does not seem to work on any creature

**Comment by Rushor** [comment]
pls check if https://github.com/TrinityCore/TrinityCore/commit/f4c1a8fb2d6aff13f67dd2494dc18b481c548af9 was ported to the core

**Comment by Oganku** [comment]
I can confirm it doesn't work on most mobs. (The same school part)

**Comment by Keader** [comment]
We need check each case.
Fixed Witch Doctor case.
Let me know if has more

**Comment by mrtimelord** [comment]
I'll let you know when/if I see more. Thanks!
