### ISSUE TITLE
[Boss] Halion (Twilight Precision)

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#4572]
**Links:** https://www.wowhead.com/spell=78243/twilight-precision
https://www.wowhead.com/spell=69127/chill-of-the-throne

**What is Happening:** Just want to make sure the [Twilight Precision](https://www.wowhead.com/spell=78243/twilight-precision) buff that affects Halion is properly enabled. I have no way to verify, as skada provides no information about damage taken hit tables. There is no visible indicator on Halion himself and I had to resort to posting a 'tentative' report here.

Note: No previous posts related to this buff have ever been made.

**What Should happen:** [Twilight Precision](https://www.wowhead.com/spell=78243/twilight-precision) should lower Halion's melee targets' dodge chance by 20% and increase Halion's hit chance by 5%. This is somewhat similar to the [Chill of the Throne](https://www.wowhead.com/spell=69127/chill-of-the-throne) debuff in ICC.

**Comment by svijetlo** [comment]
i think this is working properly

**Comment by Keader** [comment]
holy...
was not working o.o

**Comment by Oganku** [comment]
I kinda had a feeling it didn't. Thanks for looking into it. Much appreciated
