### ISSUE TITLE
Unable to create guild events

### ISSUE THREAD

**Issue by AranMat** [WoWManiaUK/Redemption#4573]
![Capture](https://user-images.githubusercontent.com/38553469/82543939-9ce47f00-9b54-11ea-848f-2e86418bf6a5.JPG)
**Links:**

**What is Happening:**
When creating a guild event for a raid. After filling in all the required details. When clicking the option to create. The "create" button goes grey, and calendar freezes and event is not created. A number of players in the guild " Chilll and Kill" have attempted to create and are are getting the same out come. Officers and Guild master alike.

**What Should happen:**
An event should appear on the date selected so other playets may sign up to take part.

**Comment by Sharuzan** [comment]
I have come across this bug before and I got into contact with the devs/GM's about it.

Only solution we found was swapping around the GuildMaster title:
1. Promote someone else to Guildmaster
2. New Guildmaster gives title back
3. Calendar resets by itself

Works like a charm :)

**Comment by AranMat** [comment]
> I have come across this bug before and I got into contact with the devs/GM's about it.
> 
> Only solution we found was swapping around the GuildMaster title:
> 
> 1. Promote someone else to Guildmaster
> 2. New Guildmaster gives title back
> 3. Calendar resets by itself
> 
> Works like a charm :)

Hi

Thanks, will give it a try when our guildmaster is on and inform if it worked or not.

**Comment by svijetlo** [comment]
yes this with calendar event is messy and bugy i can confirm it

**Comment by wow-mania** [comment]
it is pretty much as it is at the moment. not sure if we can improve it much more.

**Comment by AranMat** [comment]
Sadly did not work, thanks though

**Comment by Sharuzan** [comment]
If you have made a lot of events, try and clear all the past and future playermade events in the calendar, do the GM-swap then see if you can make new events :)

**Comment by AranMat** [comment]
Could changing the guild name, then changing it back work ?

**Comment by GMMetaxa** [comment]
Cool
