### ISSUE TITLE
[Dungeons/Loot]Repeated loot

### ISSUE THREAD

**Issue by mrtimelord** [WoWManiaUK/Redemption#4574]
**Links:**
[Pandemonius](https://www.wow-mania.com/armory/?npc=18341#drops)
[Tavarok](https://www.wow-mania.com/armory/?npc=18343#drops)
[Nexus-Prince Shaffar](https://www.wow-mania.com/armory/?npc=18344#drops)
[Mennu the Betrayer](https://www.wow-mania.com/armory/?npc=17941#drops)
[Quagmirran](https://www.wow-mania.com/armory/?npc=17942#drops)
[Rokmar the Crackler](https://www.wow-mania.com/armory/?npc=17991#drops)

**What is Happening:**
Certain bosses ( that we've found so far ) only seem to drop one item of their loot table after repeated runs:

Pandemonius (Mana-Tombs) - Creepjacker
Tavarok (Mana-Tombs) - Shaarde
Nexus-Prince Shaffar (Mana-Tombs) - Ethereal warp-bow

Mennu the Betrayer (Slave Pens)- Wastewalker Shiv
Quagmirran (Slave Pens) - Spore- Soaked Vaneer
Rokmar the Crackler (Slave Pens) - Runed Fungalcap

They have consistently dropped the same items for our group every time we run the dungeons using Dungeon Finder on random as we're trying to level up.

The Dungeon Finder Satchels are also misbehaving at least for our group, they are dropping 64 iLevel items while our player levels are 64-66.

My IGN is Dalek and the rest of my group are: Hounded, Axhumier, Anchorz and Kurushimi ( if having a look at the logs could help you )

**What Should happen:**
The bosses should drop all the items from their loot table as they all have an equal drop rate as per the Armory.

**Comment by Rushor** [comment]
Will check that!

**Comment by wow-mania** [comment]
This is within probability. Just check if we have all loot in there.

**Comment by svijetlo** [comment]
i been doing those places for some things they drop different items just cos you see some item drop few times in row it is not smt wrong, like for example my guild got GTS on halion 8 times in row, that does not mean other trinkets do not drop it is just do to luck of person, group. for example almost every icc we get DBW trinket while some think it is rare,  but ye make sure to chek loot tables on them

**Comment by jeyrella** [comment]
Looks like your bad luck.  Working fine.
![image](https://user-images.githubusercontent.com/46089380/82688223-65f39380-9c50-11ea-89cd-7b0911001b17.png)

![image](https://user-images.githubusercontent.com/46089380/82687928-e82f8800-9c4f-11ea-892c-b708aa72f948.png)

![image](https://user-images.githubusercontent.com/46089380/82688071-288f0600-9c50-11ea-862b-bb857ff09eec.png)

![image](https://user-images.githubusercontent.com/46089380/82688275-7f94db00-9c50-11ea-9a6a-d0a0798f0090.png)
