### ISSUE TITLE
[Battlegrounds] Demolishers

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#4575]
**Links:** https://wowwiki.fandom.com/wiki/Strand_of_the_Ancients
https://wowwiki.fandom.com/wiki/Wintergrasp
https://www.wowhead.com/npc=28094/wintergrasp-demolisher#comments

**What is Happening:** The demolishers in both [Strand of the Ancients](https://wowwiki.fandom.com/wiki/Strand_of_the_Ancients) and [Wintergrasp](https://wowwiki.fandom.com/wiki/Wintergrasp) behave incorrectly: 

The players in the passenger seats of demolishers are able to cast/shoot as intended, but their damage output is greatly increased. It seems they get a 2-3x damage increase by doing so.

I have searched in wowhead comments, in wowwiki pages, and was unable to find any mention of such a thing.

**What Should happen:**
The demolishers should provide a safe spot for ranged characters to attack, but it shouldn't affect their raw damage output.

**Comment by Rushor** [comment]
Nah there is a scaling depending on item Level that works as intended as far as i know

**Comment by wow-mania** [comment]
This is as-is.

**Comment by Oganku** [comment]
The Demolisher itself scales with ilvl and that's fine, but the passengers are just standing there using their regular abilities. They should not benefit from vehicle scaling I'm pretty sure

**Comment by Keader** [comment]
Passenger should not get damage scale
