### ISSUE TITLE
Quest: Who are They

### ISSUE THREAD

**Issue by UniversalSoldier1985** [WoWManiaUK/Redemption#4576]
**Links:**
https://www.wow-mania.com/armory/?quest=10040

**What is Happening:**
Shadowy Disguise - is not provided so the quest can't be done.

**What Should happen:**
Shadowy Disguise should be Provided uppon taking the quest.

**Comment by GMMetaxa** [comment]
On a sidenote: You won't get the disguise when mounted, which is as it should be.

**Comment by Sharuzan** [comment]
<img width="509" alt="screen" src="https://user-images.githubusercontent.com/47272908/82663455-fe2d5080-9c2f-11ea-93db-1a8e400532b6.png">

Dunno why buff stacks to 2 when used,  but the disguise works :) Even mounted, tested with the Swift Red Gryphon, Snowy Gryphon and a Swift Palomino.

**Comment by Rushor** [comment]
added an additional save call, so that the cast of the buff will always happen now.
