### ISSUE TITLE
Darkweaver Syth overscaled Shadow ability

### ISSUE THREAD

**Issue by Hounded96** [WoWManiaUK/Redemption#4578]
[Party] [Hounded]: Skada: Damage for Darkweaver Syth, 21:37:25 - 21:39:21:
[Party] [Hounded]:  1. Hounded 98.9K (852.7, 58.4%)
[Party] [Hounded]:  2. Dalek 28.2K (300.2, 16.6%)
[Party] [Hounded]:  3. Kurushimi 24.7K (411.4, 14.6%)
[Party] [Hounded]:  4. Anchorz 17.7K (153.9, 10.4%)
[Party] [Hounded]: Skada: Damage taken by spell for Darkweaver Syth, 21:37:25 - 21:39:21:
[Party] [Hounded]:  1. Shadow Shock 75.1K (53.7%)
[Party] [Hounded]:  2. Attack 25.3K (18.1%)
[Party] [Hounded]:  3. Arcane Shock 17.3K (12.4%)
[Party] [Hounded]:  4. Flame Shock 10.4K (7.4%)
[Party] [Hounded]:  5. Frost Shock 7.8K (5.6%)
[Party] [Hounded]:  6. Chain Lightning 3.7K (2.7%)
[Party] [Hounded]:  7. Arcane Buffet 0.3K (0.2%)
[Party] [Hounded]:  8. Frost Buffet 0.1K (0.0%)

Ability is instant killing when its alive less than 2 seconds. 

Seems to be overscaled 

2nd fight

[Party] [Hounded]: Skada: Damage taken for Darkweaver Syth, 21:30:09 - 21:33:08:
[Party] [Hounded]:  1. Hounded 51.9K (33.6%)
[Party] [Hounded]:  2. Axhumier 30.3K (19.7%)
[Party] [Hounded]:  3. Dalek 30.2K (19.6%)
[Party] [Hounded]:  4. Kurushimi 21.2K (13.8%)
[Party] [Hounded]:  5. Anchorz 20.5K (13.3%)
[Party] [Hounded]: Skada: Damage taken by spell for Darkweaver Syth, 21:30:09 - 21:33:08:
[Party] [Hounded]:  1. Shadow Shock 103.0K (66.8%)
[Party] [Hounded]:  2. Attack 15.5K (10.1%)
[Party] [Hounded]:  3. Arcane Shock 11.9K (7.7%)
[Party] [Hounded]:  4. Flame Shock 10.9K (7.0%)
[Party] [Hounded]:  5. Frost Shock 8.5K (5.5%)
[Party] [Hounded]:  6. Chain Lightning 3.7K (2.4%)
[Party] [Hounded]:  7. Frost Buffet 0.3K (0.2%)
[Party] [Hounded]:  8. Arcane Buffet 0.2K (0.1%)
[Party] [Hounded]:  9. Flame Buffet 0.2K (0.1%)

**Comment by Sharuzan** [comment]
Did the issue occur through RDF? Is it HC?
Testing on nm and on hc, shadow shock never reached near those numbers.

**Comment by mrtimelord** [comment]
RDF normal

**Comment by Hounded96** [comment]
^

**Comment by Hounded96** [comment]
We managed to kill it but it was seriously rough haha Br's on tank and healer 2 man to death

**Comment by jeyrella** [comment]
Posting a total damage count from Skada does nothing to show it is overscaled.
Not every fight you have should be a pushover because you're used to an overgeared 30% nerfed ICC.
Please post a full log showing individual hits, as nothing we see makes us think so far this is anything outside of the norm.  Will reopen once you provide that & can see where there is an issue.

**Comment by Hounded96** [comment]
Well first off overgeared 30% nerfed ICC No? New to this server, I mythic raid retail xd 

When an ability is wiping a group and the mobs been up for less than 2 seconds somethings wrong

The mechanic for this mob shouldnt hit that hard (compared to retail) *spawns hits 9k in 1 hit and proceeds to insta cast Shadow Shock
