### ISSUE TITLE
[Spell] Intervene

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#4579]
**Links:** https://wow-mania.com/armory/?spell=3411
https://wowwiki.fandom.com/wiki/Intervene?oldid=2064744
https://wow-mania.com/armory/?spell=1038

**What is Happening:** [Intervene](https://wow-mania.com/armory/?spell=3411) currently has no effect on the intervened target's threat.

Proof:
Before using intervene, Duduganku's threat sits at 20.1K against the target Pustulent Horror.
![WoWScrnShot_052220_191112](https://user-images.githubusercontent.com/34783736/82715361-ce4a7100-9c60-11ea-9585-44554109962b.jpg)

Directly afterwards, I cast Intervene on the chicken that was nearing danger. Combat log shows text of the ability being used, and we see the shield on the target and all that. No change in threat, still at 20.1K.
![WoWScrnShot_052220_191114](https://user-images.githubusercontent.com/34783736/82715430-179ac080-9c61-11ea-94f6-60bd9bfc0b58.jpg)

I wait a couple seconds to account for any possible addon refresh rate, and we see the intervene lines in combat log scroll up a bit, but the bird's threat still remains at 20.1K.
![WoWScrnShot_052220_191117](https://user-images.githubusercontent.com/34783736/82715499-5d578900-9c61-11ea-974d-61cc636f1e36.jpg)

**What Should happen:**
![image](https://user-images.githubusercontent.com/34783736/82715302-80ce0400-9c60-11ea-824c-1cd83c60565c.png)

According to the tooltip and wowwiki entires, Intervene should reduce the target's total threat by 10%, similarly to how a paladin's [Hand of Salvation](https://wow-mania.com/armory/?spell=1038) would work.

In the above's situation, Intervene would be expected to reduce Duduganku's threat by ~2.01K, bringing his total threat to about 18.1K total, extending the poor chicken's life expectancy.

**Comment by Keader** [comment]
what happened with you this week? o.O
you're on fire hehe
Good catch, working on it.

**Comment by Keader** [comment]
check now :)
