### ISSUE TITLE
[Dungeon] Varos Cloudstrider in the Oculus

### ISSUE THREAD

**Issue by squalllh1989** [WoWManiaUK/Redemption#4580]
**Links:** https://www.wow-mania.com/armory/?npc=27447

**What is Happening:**  [Varos Cloudstrider](https://www.wow-mania.com/armory/?npc=27447) can be attack and killed with all 10 [Centrifuge Construct](https://www.wow-mania.com/armory/?npc=27641) alive

![WoWScrnShot_052320_134140](https://user-images.githubusercontent.com/27235989/82724585-508a7200-9d01-11ea-9810-41b7782aae14.jpg)

**What Should happen:**  [Varos Cloudstrider](https://www.wow-mania.com/armory/?npc=27447) can only be attack after all 10 [Centrifuge Construct](https://www.wow-mania.com/armory/?npc=27641) is killed.

**Comment by Keader** [comment]
Test now in ptr pls

**Comment by Sharuzan** [comment]
Still killable on PtR without having killed all the centrifuges.

**Comment by Sharuzan** [comment]
<img width="960" alt="ss" src="https://user-images.githubusercontent.com/47272908/82751012-96544280-9db4-11ea-9768-0542294c0c70.png">

**Comment by Keader** [comment]
How the fuck you're testing it?

![image](https://user-images.githubusercontent.com/7120913/82753737-6437e600-9d9e-11ea-9ee1-00fbc323d238.png)

**Comment by Sharuzan** [comment]
what xD I went into Ocu, went to first boss, grabbed myself a dragon, flew up

**Comment by Sharuzan** [comment]
Ok works now

**Comment by jeyrella** [comment]
Did tonight,  still killable without killing the constructs

**Comment by Keader** [comment]
Fixed.
i found a new issue that make old fix not work sometimes
