### ISSUE TITLE
[QUEST] Vile Like Fire!

### ISSUE THREAD

**Issue by billykitty** [WoWManiaUK/Redemption#4582]
**Links:**
Vile: https://www.wowhead.com/npc=30216/vile
Vile Like Fire!: https://www.wowhead.com/quest=13071/vile-like-fire

**What is Happening:**
Quest NPC Vile does not offer players the daily quest "Vile Like Fire!" when he is walking back and forth unless he is right in front of The Shadow Vault entrance, coordinates 43.5, 24.4.  He does offer the quest when standing still at coordinates 43.2, 25.2.  It appears you can turn in the quest wherever he is.

**What Should happen:**
Vile should offer Players the daily quest wherever he is.

**Comment by Rushor** [comment]
related to conditions

**Comment by Rushor** [comment]
check now pls

**Comment by billykitty** [comment]
Thank you for looking at this. It's working much better now. I can take the quest wherever he is while walking or standing.  

But when I first got to The Shadow Vault he was standing at 42.8, 26.1 and I couldn't take the quest until he started walking. Maybe someone had just interacted with him, or I had just logged in, I'm not sure.

But he's working much better now, I appreciate your help. 

Should I test this for a few days and let you know the results, or would you prefer to close the issue until it reoccurs?

- Waffles -

**Comment by Rushor** [comment]
no the fix not not on live realm yet. will be applied on friday
