### ISSUE TITLE
[ICC/Mob] Nerub'ar Broodkeeper

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#4583]
**Links:** https://www.wowhead.com/npc=36725/nerubar-broodkeeper

**What is Happening:** Those spiders located in the Lower Citadel area are currently unskinnable.

**What Should happen:** These spiders should be skinnable and have their appropriate skinning loot table.

**Comment by Sharuzan** [comment]
<img width="727" alt="ss" src="https://user-images.githubusercontent.com/47272908/82751235-26df5280-9db6-11ea-94ac-d3889b0b8cd4.png">

Currently can't be skinned
