### ISSUE TITLE
[NPC] Jang is missing in Booty Bay - NPC 15078 / Stranglethorn Fishing event timing

### ISSUE THREAD

**Issue by jeyrella** [WoWManiaUK/Redemption#4584]
**Links:**
https://wow-mania.com/armory/?npc=15078

**What is Happening:**
Jang is in the database, but is not present in game when Stranglethorn fishing event is active.

![image](https://user-images.githubusercontent.com/46089380/82754879-d244d300-9dc7-11ea-97ca-03a74d27ff76.png)

Appears Jang's quest may be linked to the Kalu'ak event instead of the STV one?
![image](https://user-images.githubusercontent.com/46089380/82754923-2485f400-9dc8-11ea-8bc6-10cae99835d1.png)

**What Should happen:**
Jang (event 62) should be active when the STV fishing tournament is active.

**Comment by jeyrella** [comment]
Does appear in PTR when event 62 is manually started.

**Comment by Rushor** [comment]
hmm maybe the timer was already passed?

the creature is connected to event 62 : 
starttime: 2017-04-30 14:01:00 
Duration 3 hours

should we may delay the event or change the starttime?

**Comment by jeyrella** [comment]
Then something is wrong with this event overall.  Riggle appears far too early, by several hours, with his text saying there is already a winner this week - yet the fishing event itself starts at 1pm instead of 2pm (like the issue with Kalu'ak on Saturday).
![stv_fishing_3](https://user-images.githubusercontent.com/46089380/82820693-90389180-9e9a-11ea-9d8b-3e904ce4853e.png)

![stv_fishing_2](https://user-images.githubusercontent.com/46089380/82820764-ae9e8d00-9e9a-11ea-8d7a-ab7fdcd80a75.png)

![stv_fishing_1](https://user-images.githubusercontent.com/46089380/82820698-9169be80-9e9a-11ea-84f8-4d22cb8fda50.png)

**Comment by Rushor** [comment]
hmm wait i will check his script and spawn

**Comment by Rushor** [comment]
starttime is 2017-04-30 14:01:00 - it reappears every 10080 minutes and stays for 180 minutes

**Comment by jeyrella** [comment]
will observe tomorrow what time he spawns and starts

**Comment by Rushor** [comment]
That would be perfect man! Thanks a lot. Then er can Adjust it!

**Comment by jeyrella** [comment]
Fishing event vendors already spawned at 10am server time
![image](https://user-images.githubusercontent.com/46089380/83348796-a5dd0980-a327-11ea-8ad1-8b6761cfb2a8.png)

**Comment by jeyrella** [comment]
![image](https://user-images.githubusercontent.com/46089380/83351754-a0d78480-a33e-11ea-82c9-24fc6aff27d0.png)

**Comment by jeyrella** [comment]
Jang is still not present

**Comment by Rushor** [comment]
Riggle Bassbait spawnstuff delayed by one hour (same fix as for the northrend guy)

spawn of tastyfish pools also delayed by one hour

jang and fishbot is now moved to the event of the fishing pools: https://i.imgur.com/L3IGMaP.png

**Comment by jeyrella** [comment]
Great.  Again I don't think this is testable until it's in live as it is dependent on the timed script running.

**Comment by jeyrella** [comment]
Riggle's appearance time is still a bit screwy.
![image](https://user-images.githubusercontent.com/46089380/83964837-7427ed80-a8a7-11ea-85ba-39f8034c70e7.png)

**Comment by jeyrella** [comment]
Confirmed however that tournament now starts at correct time and Jang is now present.
