### ISSUE TITLE
[Quest] Enraged Spirits of Fire and Earth - 10458 - Shadowmoon Valley

### ISSUE THREAD

**Issue by jeyrella** [WoWManiaUK/Redemption#4586]
**Links:**
https://wow-mania.com/armory/?quest=10458
Item:  https://wow-mania.com/armory/?item=30094
which uses spell:  https://wow-mania.com/armory/?spell=36107
which summons NPC:  https://wow-mania.com/armory/?npc=21071

**What is Happening:**
The "NPC" 21071 totem placed by the player using item 30094 casting 36107 moves with the player.

**What Should happen:**
The totem should stay still where it is placed.

**Comment by jeyrella** [comment]
https://youtu.be/LKFejOWZ_X8?t=27

**Comment by jeyrella** [comment]
Also the same effect for the followup quests, probably because it uses the same spell & NPC
Enraged Spirits of Water
https://wow-mania.com/armory/?quest=10480
Enraged Spirits of Air
https://wow-mania.com/armory/?quest=10481

**Comment by Rushor** [comment]
should stay in one place now
