### ISSUE TITLE
[Boss/Loot] Lich King Emblem of Frost amount

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#4587]
**Links:** https://wowwiki.fandom.com/wiki/Lich_King_(Icecrown_Citadel_tactics)
https://www.wowhead.com/item=49426/emblem-of-frost#criteria-of

**What is Happening:** Lich King only gives 1 Emblem of Frost on 25 heroic difficulty. It very likely also happens on other difficulties, but I have only noticed on 25hc tonight.

**What Should happen:** Lich King, like other ICC bosses, should drop 2 emblems per kill.

**Comment by Rushor** [comment]
it was only wrong in 25 hc. fixed.
