### ISSUE TITLE
[NPC] Prince Skaldrenox - Silithus - 15203

### ISSUE THREAD

**Issue by jeyrella** [WoWManiaUK/Redemption#4588]
**Links:**
https://wow-mania.com/armory/?npc=15203

**What is Happening:**
His spawn text uses "$c" instead of the player's class.
![image](https://user-images.githubusercontent.com/46089380/82809537-3927c200-9e84-11ea-9fce-08e44481e396.png)

**What Should happen:**
$c should be replaced with the summoning player's class.

**Comment by Rushor** [comment]
check now pls

**Comment by jeyrella** [comment]
Unfortunately, not fixed, see last line here.
Also it seems that all four of the summoned use a mix of the same lines between them, and they all have issues:
![image](https://user-images.githubusercontent.com/46089380/82953351-88fcab00-9fa2-11ea-98ab-e4a96bcc76c3.png)

"What?  Such a small, frail thing beckons me?  I shall add your bones to my throne, $r!"
"You dare!  Outrageous!  I curse you, $c.  I curse you with.... death!"
"Killing you and your cohorts, $c, will amuse me.  I shall make it quick."

NPCs are
https://wow-mania.com/armory/?npc=15203
https://wow-mania.com/armory/?npc=15204
https://wow-mania.com/armory/?npc=15205
https://wow-mania.com/armory/?npc=15305

**Comment by Rushor** [comment]
okay forgot to save the change :D 

try now

**Comment by Rushor** [comment]
is it fixed?

**Comment by jeyrella** [comment]
looks good
![image](https://user-images.githubusercontent.com/46089380/83325841-618a3480-a267-11ea-9127-2000013106a0.png)
