### ISSUE TITLE
[Quest item] Fel Gland has incorrect drop rate

### ISSUE THREAD

**Issue by jeyrella** [WoWManiaUK/Redemption#4589]
**Links:**
https://wow-mania.com/armory/?item=32502#dropped-by

**What is Happening:**
Fel Gland is set to 33% drop rate.
https://wow-mania.com/armory/?item=32502#dropped-by

**What Should happen:**
Fel Gland should have 100% drop rate.  (When on quest A Slow Death https://wow-mania.com/armory/?quest=11020).  This was changed in patch 3.0.8.
![image](https://user-images.githubusercontent.com/46089380/82825774-bb73ae80-9ea3-11ea-89e9-c531684a38c5.png)
![image](https://user-images.githubusercontent.com/46089380/82825830-d6462300-9ea3-11ea-8bc0-6376b38e1397.png)

**Comment by Rushor** [comment]
aye done
