### ISSUE TITLE
[RS/Bosses] Skinning RS Bosses

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#4590]
**Links:** https://www.wowhead.com/npc=39747/saviana-ragefire#skinning
https://www.wowhead.com/npc=39751/baltharus-the-warborn#skinning
https://www.wowhead.com/npc=39746/general-zarithrian#skinning
https://www.wowhead.com/npc=39863/halion#skinning

**What is Happening:** All of the bosses in Ruby Sanctum (including the 3 mini-bosses) are currently un-skinnable.

**What Should happen:** [Saviana Ragefire](https://www.wowhead.com/npc=39747/saviana-ragefire#skinning), [Baltharus the Warborn](https://www.wowhead.com/npc=39751/baltharus-the-warborn#skinning), [General Zarithrian](https://www.wowhead.com/npc=39746/general-zarithrian#skinning) and [Halion](https://www.wowhead.com/npc=39863/halion#skinning) should all be skinnable and have their respective loot tables linked above.

**Comment by Sharuzan** [comment]
Confirmed: Currently no bosses in RS are skinnable.

**Comment by Rushor** [comment]
skinning loot added for all the boses based on wowhead
