### ISSUE TITLE
[QUEST]: [Adding Injury to Insult] - Bjorn movement issues.

### ISSUE THREAD

**Issue by Sharuzan** [WoWManiaUK/Redemption#4593]
**Links:**
Quest:
https://www.wow-mania.com/armory/?quest=12481
NPC:
https://www.wow-mania.com/armory/?npc=24238

What is happening:

When luring Bjorn back to Lydell's Ambush, his movement speed is like a marathon runner; 
You can't outrun him and he will most likely kill you before you reach the Ambush.

Furthermore checking this on PtR, if I activate GM Fly, he will just continue to fly towards me and keep trying to bash my skull in. 
+ Appears to not give a damn about pet taunts; At least not Warlock Voidwalker.

What Should happen:

Looking at:
https://www.youtube.com/watch?v=qfqhB2df9r8

The quest should be soloable and Bjorn should run like a big heavy viking, easy to outrun and lure into the planned ambush.

**Comment by svijetlo** [comment]
i never had issue with this quest , come to range use item turn around run back to ambush kill him there all good

**Comment by Rushor** [comment]
speed reduced for him

**Comment by Sharuzan** [comment]
Perfect! Thanks a lot! :D
