### ISSUE TITLE
Transmog disappeared after crash

### ISSUE THREAD

**Issue by Loladinz** [WoWManiaUK/Redemption#4594]
What is Happening:
Server crashed and when i logged in my transmog was gone. This had happen before, but usually i can go to transmogrifier and equip it again.
But this time all my saved sets were gone as well.

**Comment by Rushor** [comment]
Pls contact a gamemaster for that since it is an Individual issue

**Comment by Loladinz** [comment]
I spoke with a gamemaster, and was told to post it on github as it was all sets removed from transmogrifier as well.

**Comment by Aristo14** [comment]
It seems to have happened to multiple people now, but no steps to reproduce ar found as of yet. 
I will not re-open the issue but rather hope for a more complete report with specifics so we can start figuring out what's going on.
