### ISSUE TITLE
[Mount] Azeroth flying mounts with too low riding skill requirement

### ISSUE THREAD

**Issue by jeyrella** [WoWManiaUK/Redemption#4597]
**Links:**
https://wow-mania.com/armory/?spell=93326
https://wow-mania.com/armory/?item=65891

**What is Happening:**
Similar to the other Azeroth-flying webshop custom mounts on ticket #4240 and #4290, the Sandstone Drake currently requires 225 skill.

**What should Happen**
This is a flying 310% mount that flies in Azeroth so it thus, like the other custom mounts, should require riding level 300 skill (Artisan).

**Comment by wow-mania** [comment]
Fixed also in live but will need restart.

**Comment by jeyrella** [comment]
confirmed on live by Osyris
