### ISSUE TITLE
Offline realm server

### ISSUE THREAD

**Issue by khastehh** [WoWManiaUK/Redemption#4598]
Hello  

my realm server is still from yesterday after server restart offline and I cant connect to the server.it shows offline for me.

thanks for your helping

Cyruss

**Comment by khastehh** [comment]
Hello
my realm server is still from yesterday after server restart offline and I cant connect to the server.it shows offline for me.
thanks for your helping
Cyruss
![photo_2020-05-30_11-31-15](https://user-images.githubusercontent.com/36959063/83325014-6a7c0580-a269-11ea-95fc-887714e9633b.jpg)

**Comment by jeyrella** [comment]
This is not a server bug.  Make sure you have the correct launcher from the pinned messages in the Discord world channel.
