### ISSUE TITLE
[Quest] Into Hostile Territory

### ISSUE THREAD

**Issue by genasi** [WoWManiaUK/Redemption#46]
In the quest Into Hostile Territory, you have to talk to Gryphon Commander Urik to get a ride to Thorson's Post. When I talk with him, he just says "The gryphon riders are standing 10 paces from us, friend. They'll be giving you a ride to Thorson's Post. Get going!" but there are no gryphon riders around to take me anywhere, except the flight master Rodney Wells which only provide the regular flightpoint option.
This isnt a character specific issue as its happened on both Corbin, worgen druid, and Daeron, draenei shaman.

wowhead quest link: [http://www.wowhead.com/quest=12325/into-hostile-territory](http://www.wowhead.com/quest=12325/into-hostile-territory)

Are you using our client? Yes
Are you using the latest Launcher? Yes

**Comment by Calebrimbor** [comment]
Issue added to the BugTracker for testing. Thank you for your report. 
@ Testers: Please add all details such as links etc.

**Comment by Calebrimbor** [comment]
Confirmed!

http://www.wow-mania.com/armory/?quest=12325

For this quest you'll need to speak with Gryphon Commander Urik(http://www.wow-mania.com/armory/?npc=27317) to secure a ride to Thorson's Post. 

Ulrik doesn't give you any options to take a gryphon. Since you can fly there yourself this quest is doable. It's not working as intended, therefore a fix is needed.

**Comment by wow-mania** [comment]
Seems that a script is missing on the Gryphon. The NPC Urik is fine.

**Comment by fvicaria** [comment]
@Rushor Do you have this one working at your server?

**Comment by ManiaLightmare** [comment]
Appears to still be an issue.
When you try to get on one of the gyphons, you get the vehicle mount arrow, but it just disappears out from under you.  Tried relogging as well which fixes many of the vehicle related phased problems.  No luck
