### ISSUE TITLE
dbw procs when i use shapeshift as druid

### ISSUE THREAD

**Issue by Bromes88** [WoWManiaUK/Redemption#4601]
**Links:**

**What is Happening:**
death bringers will heroic procs when i switch the form

**What Should happen:**
it should proc only when i attack

**Comment by svijetlo** [comment]
@Bromes88  from what form to what form you were switching as i can not reproduce this , i assume you were going form cat to bear or vice versa

**Comment by Bromes88** [comment]
i guess there is a problem with the lk leather set. it only happens when i wear that.

**Comment by svijetlo** [comment]
that is lk set then pls make new post for that one and link set name so we can test it out , will close this post as this item works perfect
