### ISSUE TITLE
Bag of Fishing Treasures Loot Table Issue

### ISSUE THREAD

**Issue by manahansf** [WoWManiaUK/Redemption#4602]
**Links:**
https://www.wow-mania.com/armory/?item=35348
https://www.wow-mania.com/armory/?item=34863

**What is Happening:**
When completing the fishing dailies from Old Man Barlo, the loot only represents the loot table from the Crocolisks in the City quest.  (This is my assumption based on the armory list of the loot and the fact that I get croc pet drops at 50% as reward no matter what the quest is for more than 6 months now and I have done the daily everyday.)

**What Should happen:**
There should be a loot table for all other dailies from Old Man Barlo that is separate from the Crocolsks quest.

**Comment by svijetlo** [comment]
bag is same form every quest and it has same loot table just that pet has highest drop rate form bag so you get it lot of times , it is just your "luck" not broken loot table of bag/bags 
i got 3 http://www.wow-mania.com/armory?item=33820 when i was doing those quests

**Comment by Oganku** [comment]
https://www.wowhead.com/item=34863/bag-of-fishing-treasures#contains
https://www.wowhead.com/item=35348/bag-of-fishing-treasures#contains

If you look on wowhead, there are actually 2 different bags, with 2 different loot tables.

The crokolisk quest bag has 11% chance to drop either pets, whereas the other dailies' bag has those extra % distributed across the other items

Here is the 'Reward from (1) quest' that shows the 4 pets:
![image](https://user-images.githubusercontent.com/34783736/83345192-4d354e80-a2de-11ea-9119-a05664f87750.png)

Here is the other 'Reward from (4) quests' (the other dailies) and we see no buckets:
![image](https://user-images.githubusercontent.com/34783736/83345198-6938f000-a2de-11ea-82d5-1c6149b1c5b1.png)

Also, the Contains (29) and Contains (25) show very obviously that one has buckets, while the other doesn't. 

Valid issue.

**Comment by Rushor** [comment]
Will check

**Comment by jeyrella** [comment]
Hard to help research this one @Rushor , problem is Wowhead is not clear if that was a later change (although I don't see why it would be) and the stats misleading.
Hard to find a clear resource.
WIll have to depend on your backend access to various old databases for this one.  Thanks.

**Comment by jeyrella** [comment]
https://www.wowhead.com/item=34863/bag-of-fishing-treasures#comments:id=306525 seems to confirm the OP's issue.  patch 2.4.1 but I don't see why that would have changed in WotLK

**Comment by manahansf** [comment]
TBH, I’ve just been hunting the lager bier recipe that appears to be only available through these bags.  We’ll only one of the 2 bags.  But the loot table is off.  Yes, wowhead says it, but the WOw-Mania armory links also say it.  
No matter what quest you do, you get the loot from the Crock daily.

**Comment by svijetlo** [comment]
![image](https://user-images.githubusercontent.com/61908373/83373822-06bd1e00-a3ca-11ea-8520-c041e8c691a1.png
quests that are no Crocolisks in the City should never ever give pet

**Comment by Rushor** [comment]
https://i.imgur.com/bR4ABQM.png 

okay will remove that

**Comment by Rushor** [comment]
pets removed from this item reward (https://www.wow-mania.com/armory/?item=34863#reward-from-quest) all the quests that are not Crocolisks in the City

**Comment by svijetlo** [comment]
50 bags form other quests no pet on 4th bag from crocolisk got the pet i would say that is fine
