### ISSUE TITLE
Trial of Crusader bosses are not skinnable

### ISSUE THREAD

**Issue by Kinkywiener** [WoWManiaUK/Redemption#4604]
**Links:**
https://www.wowhead.com/npc=34797/icehowl#skinning
https://www.wowhead.com/npc=34564/anubarak#skinning

**What is Happening:**
Icehowl and Anubarak in Trial of Crusader are not skinnable either.

**What Should happen:**
Icehowl and Anubarak in Trial of Crusader should be skinnable.

**Comment by jeyrella** [comment]
![image](https://user-images.githubusercontent.com/46089380/83429628-33a21d00-a42c-11ea-999e-cb94b0cd3e8c.png)

**Comment by Rushor** [comment]
reason is the factioj specific loot. i will add the skinning loot manualy to the corpse

**Comment by Rushor** [comment]
applied some changes, that will fix that - testable once dev is compiled

**Comment by Rushor** [comment]
should work now
