### ISSUE TITLE
[ITEM/Set] Lich King Leather set 

### ISSUE THREAD

**Issue by Bromes88** [WoWManiaUK/Redemption#4605]
**Links:**
https://www.wow-mania.com/armory/?itemset=2002

**What is Happening:**
when i wear the lk leather set dbw proccs every time i switch the form as druid

**What Should happen:**
it should only proc when i attack

**Comment by svijetlo** [comment]
no it wont prock dbw , lk leather set every time you change form will http://www.wow-mania.com/armory?spell=71560
it is connected to recent going towards change in Leather Lk set to make it better for each speck that use it 
that is also wrong it need to have chance  prock on hit of http://www.wow-mania.com/armory?spell=71492 with internal cooldown of DBW 
it is not connected to dbw as it is procing it even wo dbw

**Comment by Aristo14** [comment]
Not linked to any changes since no changes have been made to it yet.

**Comment by Keader** [comment]
rdy to test
