### ISSUE TITLE
[Boss/SSC] The Lurker Below (Serpentshrine Cavern)

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#4606]
**Links:** https://www.wowhead.com/npc=21217/the-lurker-below

**What is Happening:** [The Lurker Below](https://www.wowhead.com/npc=21217/the-lurker-below) in the TBC Serpentshrine Cavern raid can be fished properly by any level fishing to start the fight in the correct way. However, it is also possible to target the boss deep in the water while standing on the platform above and just shooting/meleeing him without him fighting back whatsoever. You can simply swim down and loot his corpse for free loot afterwards.

**What Should happen:** The boss should only spawn after having been fished (component that works properly) and should not be attackable prior to doing so.

**Comment by WhitephoenixTheBunny** [comment]
Please don't make fun at me, but I know when this boss started behaving like this... and was long time ago :D

Is related with the fix done to Ouro (#2660)

**Comment by Keader** [comment]
rdy to test
