### ISSUE TITLE
can't finish and start certain quest

### ISSUE THREAD

**Issue by ramzius12** [WoWManiaUK/Redemption#4608]
**Links:**
![WoWScrnShot_060320_061954](https://user-images.githubusercontent.com/64349319/83593462-7d425300-a565-11ea-94eb-5f50a02fe6b5.jpg)

**What is Happening:**
Hi, trying to finish spymaster thalodien quest and start anchorite karja quest
both have question/exclamation mark above them but I cant click them to talk to them....tried logging out and in but doesn't work

TY

**What Should happen:**
They should talk to me to finish/start a  quest

**Comment by Rushor** [comment]
Maybe conditions or Reputation related

**Comment by jeyrella** [comment]
I have done this quest chain twice in past two weeks with different chain paths, all works flawlessly.  I highly suspect local cache issues.

**Comment by ramzius12** [comment]
What can I do? Somehow to clear local cache?

בתאריך יום ד׳, 3 ביוני 2020, 13:22, מאת jeyrella ‏<notifications@github.com

**Comment by svijetlo** [comment]
those are conected to reputation mark will always be above npc

**Comment by ramzius12** [comment]
ok...Ill try again when I have more reputation...TY! :-)
