### ISSUE TITLE
Ruby Sanctum mobs are not skinnable

### ISSUE THREAD

**Issue by Kinkywiener** [WoWManiaUK/Redemption#4609]
**Links:**
https://www.wowhead.com/npc=40423/charscale-commander#skinning
https://www.wowhead.com/npc=40419/charscale-assaulter#skinning
https://www.wowhead.com/npc=40417/charscale-invoker#skinning
https://www.wowhead.com/npc=40421/charscale-elite#skinning

**What is Happening:**
In Ruby Sanctum Charscale Commander/Assaulter/Invoker/Elite mobs are not skinnable.

**What Should happen:**
In Ruby Sanctum Charscale Commander/Assaulter/Invoker/Elite mobs should be skinnable.

**Comment by Rushor** [comment]
will update that

**Comment by Rushor** [comment]
fixed once dev is restarted

**Comment by Rushor** [comment]
fixed in dev

**Comment by Rushor** [comment]
seems to be on live already

**Comment by Rushor** [comment]
@svijetlo can you check if the issue is still there? my addition is actually already on live realm, could the reason maybe be sth else?

**Comment by svijetlo** [comment]
will check it as soon i can log in

**Comment by svijetlo** [comment]
![WoWScrnShot_060420_162708](https://user-images.githubusercontent.com/61908373/83769696-78be8d00-a680-11ea-8b1d-0ad5ff5714c7.jpg)
![WoWScrnShot_060420_162719](https://user-images.githubusercontent.com/61908373/83769704-7b20e700-a680-11ea-8c81-b203d7b00e87.jpg)
works fine for me
