### ISSUE TITLE
Why is your client requesting 9 to 14 GB of RAM?

### ISSUE THREAD

**Issue by erasertoorin** [WoWManiaUK/Redemption#4610]
[**Links:**](url)

**What is Happening:**
Game crashed because out of memory.

**What Should happen:**
No crash

this one happened upon landing from gryphon
![grafik](https://user-images.githubusercontent.com/35346209/83757482-d814a100-a670-11ea-8d63-33c5a7099796.png)

these two happened in dalaran without related cause
**Aaaand 5 minutes later this**
![grafik](https://user-images.githubusercontent.com/35346209/83757924-83bdf100-a671-11ea-90fa-8272dd90b2c5.png)

getting more and more......
![grafik](https://user-images.githubusercontent.com/35346209/83758344-39893f80-a672-11ea-8fed-d13d4987e8d1.png)

**Comment by svijetlo** [comment]
@erasertoorin  go to wow-mania discord in #red-world channel find pinned msg from there download launcher  GM-Metaxa posted , replace launcher in your wow-mania folder with that one your problems will be gone
![image](https://user-images.githubusercontent.com/61908373/83760126-c9c88400-a674-11ea-9a6c-d2db7fd347d3.png)

**Comment by jeyrella** [comment]
this is not a server problem.

**Comment by erasertoorin** [comment]
thanks for the tip i'll try it 
and thumbs up for the quick response :-)
