### ISSUE TITLE
[Quest] Crush Dem Vrykuls! 

### ISSUE THREAD

**Issue by gh0ster** [WoWManiaUK/Redemption#4611]
**Links https://www.wowhead.com/quest=12992/crush-dem-vrykuls
**What is Happening:**
When shooting down the drake it spawns the rider as a separate NPC. This NPC then "litters" the cliff below the quest platform.. It is a daily quest to shoot 15 drakes, so 15 riders spawn for each person who does the quest.

Not sure when they get cleaned out, but currently there are a few hundred non-interactive NPC spawned below the quest area. I assume this could contribute to strain on the server overhead.

**What Should happen:**
When the drake dies, so should the rider.

**Comment by svijetlo** [comment]
@gh0ster   quest you explain is not one you link 
the quest you explain is https://www.wowhead.com/quest=12992/crush-dem-vrykuls
Crush Dem Vrykuls! from same npc Vile in Shadow Vault:
and yes i can confirm that npc riding a dragon stay around even after corpse of dragon despawns 
it can potentaly be lag and load issue as some keep on running in place 
what should happen that rider die and corpse despawns same as dragon corpse 
![WoWScrnShot_060420_182125](https://user-images.githubusercontent.com/61908373/83782874-4321a000-a690-11ea-9333-4b15c1b9e384.jpg)
![WoWScrnShot_060420_181913](https://user-images.githubusercontent.com/61908373/83782901-44eb6380-a690-11ea-81a0-1231dd880411.jpg)

**Comment by svijetlo** [comment]
EDIT: i been here for 40 mins and all of them are here if lot of ppl do this quest or some one just come and kill dragon wo completing quest i would assume those are gone only ones server get reset , could be potential lag issue

**Comment by Rushor** [comment]
Will fix that

**Comment by Rushor** [comment]
i guess we are speaking about those? https://www.wowhead.com/npc=30330/jotunheim-proto-drake

added despawn for them once drake is dead

**Comment by svijetlo** [comment]
yes sir @Rushor

**Comment by svijetlo** [comment]
![WoWScrnShot_060620_115438](https://user-images.githubusercontent.com/61908373/83941551-927ce300-a7ec-11ea-8b44-4ed17fe836da.jpg)
this is how it looks now after 2 mins corpse of rider is gone after some 4 min corpse of dragon is gone

**Comment by Rushor** [comment]
coolio
