### ISSUE TITLE
(Quest) Call Of Fire

### ISSUE THREAD

**Issue by alematador** [WoWManiaUK/Redemption#4612]
https://pt.wowhead.com/quest=9467/call-of-fire

The problem is occurring with my character "Candira". It's a shaman.

As you may know, the shaman needs to complete some quests to get his totems.

I had no trouble completing three totems (air, earth and water). When I went to look for the fire totem quest, I couldn't.

None of the characters who were supposed to provide the quest were available.

I searched all the guides on the internet, it seems to be a common bug.

Can you help me? I donated just to get the xp vip to upload faster. Now I'm stuck with fear of leveling up and not being able to use my character.

Thank you.

**Comment by Rushor** [comment]
Hmm did you checked the wotlk quest line? Have you done all previous quests?

**Comment by wow-mania** [comment]
Pretty sure it works.

**Comment by alematador** [comment]
I know the quest is working because I've seen other shamans using the fire totem. What I am saying is the problem is happening to me specifically.
and there are no other previous quests. I will put below the description of the quest taken from the site https://pt.classic.wowhead.com/guides/shaman-class-quests-classic-wow
"To get started for this quest you can visit ANY shaman trainer you will have access to at that level whether it be in Mulgore, Penhasco do Trovão, Durotar or Orgrimmar. The quest will be named  Clamor do Fogo and it will send you to the Sertões to speak with Kranal Fiss".
The only requirement is to be at right level and be a shaman.
But i just can't do the quest.
Can you help me, please?

**Comment by Rushor** [comment]
which race are you? can you try to start any of those quests:

https://www.wow-mania.com/armory/?quest=2983
https://www.wow-mania.com/armory/?quest=1522
https://www.wow-mania.com/armory/?quest=1523
https://www.wow-mania.com/armory/?quest=2984

**Comment by Aristo14** [comment]
Not an issue for GH but for an ingame ticket to a GM 
They can look trough your quests and either tell you what's happening or add the quest to your log.
