### ISSUE TITLE
[Quest] Hot Fiery Death

### ISSUE THREAD

**Issue by svijetlo** [WoWManiaUK/Redemption#4613]
**Links:**
http://www.wow-mania.com/armory?quest=5103

**What is Happening:**
Ones i lower B.R.S. you take quest form http://www.wow-mania.com/armory?object=176090
*Human Remains* next to it is arm/gauntlet you can click and get the item in bag that you need take to Winterspirng to finish quest , 
BUT after click arm/gauntlet you do not get a single thing in bag so quest is not completed ergo you can not finish quest /give it in

**What Should happen:**
After taking quest and click on item next to corpse you need to get gauntlets to player bag

**Comment by Oganku** [comment]
You have to click the gauntlet again to actually pick it up after taking the quest.

**Comment by svijetlo** [comment]
don it 3 times it spowns back after some time never got item

**Comment by Rushor** [comment]
try now

**Comment by svijetlo** [comment]
![WoWScrnShot_060620_120943](https://user-images.githubusercontent.com/61908373/83941804-a0336800-a7ee-11ea-9e46-03f6d019a0b0.jpg)
