### ISSUE TITLE
[Quest] Creatures of the eco-domes - 10427 - Netherstorm

### ISSUE THREAD

**Issue by jeyrella** [WoWManiaUK/Redemption#4614]
**Links:**
https://wow-mania.com/armory/?quest=10427

**What is Happening:**

1.  When Talbuk Doe or Talbuk Sire is tagged, player is left in combat until the corpse despawns.
2.  Talbuk instantly dies on tagging and corpse despawns after 20 seconds
3.  There is no "zzz" animation when Talbuk is tagged.
https://youtu.be/p76eX1xQAPo

**What Should happen:**
1.  When Talbuk Doe or Talbuk Sire is tagged, player should leave combat immediately
2.  It should not despawn as a corpse, it should fall asleep at same health as when tagged for the 20 seconds and re-awaken with full health
3.  Should be a "zzz" animation when Talbuk is tagged.

![image](https://user-images.githubusercontent.com/46089380/83872043-238a8600-a729-11ea-8370-5c05ae93f01b.png)
![image](https://user-images.githubusercontent.com/46089380/83872071-2c7b5780-a729-11ea-8b06-f8e1db5aa252.png)
![image](https://user-images.githubusercontent.com/46089380/83872107-3ef59100-a729-11ea-8552-d1db1dba1e5d.png)
https://youtu.be/Xh0xJPQnSJQ?t=79  (from later era, but had not changed.  no era-correct videos found)

**Comment by wow-mania** [comment]
@Rushor just make creature run into a random direction and despawn in the distance

**Comment by Rushor** [comment]
hmm combatstop function no longer seem to work here. i must investigate it

**Comment by Rushor** [comment]
okay added the best i could do so far

* combat stops now upon spellhit
* after 20 seconds creature wakes up again and can be reused
* note: they will walk to homeposition and then fall asleep - that cannot be changes for now

**Comment by svijetlo** [comment]
![WoWScrnShot_060620_121403](https://user-images.githubusercontent.com/61908373/83941922-657dff80-a7ef-11ea-931a-2f9aee9a9f69.jpg)
rest works fine after some 25ish sec he is awake with full hp , as soon you tag it and mob pass out you lave combat
