### ISSUE TITLE
[Quest] It Goes to 11...  11421 - Howling Fjord

### ISSUE THREAD

**Issue by jeyrella** [WoWManiaUK/Redemption#4615]
**Links:**
https://wow-mania.com/armory/?quest=11421
https://wow-mania.com/armory/?npc=24533   (dragonflayer defender)
https://wow-mania.com/armory/?npc=27992  (harpoon gun)

**What is Happening:**

1.  Dragonflyer Defenders are already spawned before you start quest
2.  Using Firey Lance skill (2) on the Vyrkul Harpoon Gun automatically updates the quest completion step to kill the Defenders, regardless of where it is aimed
https://youtu.be/TBjGPRN6Ad4

**What Should happen:**
1.  Dragonflyer Defenders should be spawned only hitting each of the buildings
2.  Quest updation should only occur when Defenders are targeted and then using Firey Lance skill (2)

**Comment by wow-mania** [comment]
Works. this is nit-picking.

**Comment by wow-mania** [comment]
Rushor please check the 2 kills if you have time, please. The rest is fine.

**Comment by Rushor** [comment]
double kills shoud be removed now after server restart on ptr

**Comment by Rushor** [comment]
improvement:

* no double kill anymore
* drakes are active and more visible
* harpoon no longer damages itself with spell "fiery lance"
