### ISSUE TITLE
Can't Filter on Cloth Chest Pieces in AH

### ISSUE THREAD

**Issue by UniversalSoldier1985** [WoWManiaUK/Redemption#4616]
**Links:**

**What is Happening:**
If you filter on Cloth hands, feet or other items it works. But if you filter on chestpieces you get all cloth items.

**What Should happen:**
If you filter on cloth chest pieces, it should be only be showing that.

**Comment by wow-mania** [comment]
@Keader can you re-check this, please. It may be a client-side issue.

**Comment by svijetlo** [comment]
i can confirm this atm on live on 2 different clients that are up to date ones you do AH-armor-cloth-chest it will mix in all other cloth item with chest 
![WoWScrnShot_060520_225452](https://user-images.githubusercontent.com/61908373/83921908-accca780-a77f-11ea-8279-c79ee7fc44d0.jpg)

**Comment by svijetlo** [comment]
i use Ah addon but even wo addon it is same

**Comment by Keader** [comment]
try now.

**Comment by svijetlo** [comment]
![WoWScrnShot_060620_122843](https://user-images.githubusercontent.com/61908373/83942158-57c97980-a7f1-11ea-881f-f64e97005d82.jpg)
![WoWScrnShot_060620_122850](https://user-images.githubusercontent.com/61908373/83942160-5ac46a00-a7f1-11ea-9fd9-aa3fa5794548.jpg)
![Uploading WoWScrnShot_060620_122859.jpg…]()
