### ISSUE TITLE
[Spell/Paladin] Judgement of Light (Heal) overpower

### ISSUE THREAD

**Issue by Keader** [WoWManiaUK/Redemption#4617]
**What is Happening:** Judgement of Light should restore 2% max hp of target.
Currently it's scaling to any type of spell mods, making spell restore much more then 2%.
In cases with alot of melees, a paladin dps can make 12k HPS in Blood Queen only with this spell (yes a DPS PALADIN !)

**What Should happen:**
Searching in warcraft logs and some videos, we found that it should only scale with:
Improved Devotion Aura / Tree of Life and ICC buff
So... it should scale 36% (based in 2% max hp), instead get all mods.
Heal amount should be: (TargetMaxHp * 0.02) * 1.3 * 1.06

Testing with just paladin talents (checkchat)

![image](https://user-images.githubusercontent.com/7120913/83945426-e4b80700-a7e0-11ea-8231-7a0383c2d55c.png)

The difference is alot bigger when you get all raid buffs.

**Comment by svijetlo** [comment]
![WoWScrnShot_060820_115140](https://user-images.githubusercontent.com/61908373/84017058-7315bf80-a97e-11ea-9bad-a7425a9069d4.jpg)
