### ISSUE TITLE
[Spell/Mage] Clearcasting

### ISSUE THREAD

**Issue by Keader** [WoWManiaUK/Redemption#4618]
**What is Happening:**

![image](https://user-images.githubusercontent.com/7120913/83947714-2d76bc80-a7ef-11ea-8ba6-acc82c932031.png)

Source: https://wowwiki.fandom.com/wiki/Patch_3.2.2

If mage has Clearcasting + Missile Barrage active, only Missigle barrage should be consumed (casting arcane missiles), not both procs.

**What Should happen:**

Both procs is consumed.

Showcase: https://drive.google.com/file/d/1o3294LzDFQcdIvmtIgwo5JhgN7ujgCKx/view?usp=sharing

**Comment by Sharuzan** [comment]
https://www.youtube.com/watch?v=H_FMS6aNsFI&feature=youtu.be

Confirmed; now working as intended, thank you!
