### ISSUE TITLE
[ICC/BQ] Fixed Twilight Bloodbolt resistance calculation

### ISSUE THREAD

**Issue by Keader** [WoWManiaUK/Redemption#4619]
**What is Happening:**

Like in Professor Putricide, this spell need use sum of school mask as resistence, not the weak one.

Logs says: 
![image](https://user-images.githubusercontent.com/7120913/83950046-315e0b00-a7fe-11ea-8d5e-6b021a016cc7.png)

Source: http://worldoflogs.com/reports/udqni9w8roj989w7/xe/?x=spell+%3D+%22Twilight+Bloodbolt%22%0D%0AOR%0D%0Aspell+%3D+%22Bloodbolt+Splash%22

This spell is used by blood queen

**What Should happen:**

To get those resistances values, need use ARCANE+SHADOW resistence, instead just weak one.

Plus: With this fix, the old fix of Professor Putricide is updated too.
Now will show correctly in combat log how much is resisted (it was broken in previous fix)

**Comment by svijetlo** [comment]
![WoWScrnShot_060820_120808](https://user-images.githubusercontent.com/61908373/84019001-04863100-a981-11ea-876b-7ac8d20c6b5e.jpg)
![WoWScrnShot_060820_121002](https://user-images.githubusercontent.com/61908373/84019006-06e88b00-a981-11ea-8ade-129f9506a2c6.jpg)
