### ISSUE TITLE
"Squealer" Thornmantle - Squealers Belt 

### ISSUE THREAD

**Issue by Rushor** [WoWManiaUK/Redemption#4620]
**Links:**
*source: https://www.wowhead.com/npc=3229/squealer-thornmantle#comments

**What is Happening:**
The creature should drop the item https://www.wowhead.com/item=4951/squealers-belt#comments for 100 percent, many equip people use to farm that

**What Should happen:**

**Comment by GMMetaxa** [comment]
![image](https://user-images.githubusercontent.com/34750502/83954585-c71f8780-a84a-11ea-82ee-73b3f1d2a886.png)
Almost 100% :)

**Comment by Rushor** [comment]
okay updated

**Comment by Sharuzan** [comment]
<img width="390" alt="belt" src="https://user-images.githubusercontent.com/47272908/83967891-93ce0e80-a8c5-11ea-8ccc-dd4ac041dbae.png">

Belt now drops as intended. Multiple kills tested.
