### ISSUE TITLE
[NPC] Marshal Ivalius and Warlord Hork Strongbrow - Texture issue

### ISSUE THREAD

**Issue by Rushor** [WoWManiaUK/Redemption#4621]
**Links:**
https://i.imgur.com/R4HXiTW.jpg
https://www.wowhead.com/npc=31241/marshal-ivalius
https://www.wowhead.com/npc=31240

**What is Happening:**

Texture for those two creatures is wrong. they should be ON the bed, not inside it. leading to people sometimes thinking that the npcs are not spawned or bugged while it is just a texture issue

**What Should happen:**
creatures should always be ON the bed. fixed https://i.imgur.com/QyN93h5.jpg

**Comment by svijetlo** [comment]
![WoWScrnShot_060820_122404](https://user-images.githubusercontent.com/61908373/84020338-f507e780-a982-11ea-83a3-45b2b9da379c.jpg)
