### ISSUE TITLE
lost xmogs

### ISSUE THREAD

**Issue by maniospanos** [WoWManiaUK/Redemption#4623]
**Links:**

**What is Happening:** logged on  a couple of hour after logging off (fully log off) and all of my xmogs were gone. Also all of my saved sets were gone too. 
(I always log on through the launcher, I have the latest update 2.6.0, the only addons I use are DBM, X-pearl and GearScore)

**What Should happen:**

**Comment by Rushor** [comment]
please contact a gamemaster for that issue, he will assist you

**Comment by maniospanos** [comment]
Dear Rushor/GitHub team,

I was directed to GitHub by a GM after I had raised a ticket for this issue.
thank you for your prompt reply.

kind regards,

Peter



________________________________
Από: Rushor <notifications@github.com>
Στάλθηκε: Σάββατο, 6 Ιουνίου 2020 10:02 μμ
Προς: WoWManiaUK/Redemption <Redemption@noreply.github.com>
Κοιν.: maniospanos <pmaniatakos@windowslive.com>; Author <author@noreply.github.com>
Θέμα: Re: [WoWManiaUK/Redemption] lost xmogs (#4623)


please contact a gamemaster for that issue, he will assist you
