### ISSUE TITLE
[NPC] High Admiral "Shelly" Jorrik (26081) with 2 Booty Bay Bruiser (4624)

### ISSUE THREAD

**Issue by Rushor** [WoWManiaUK/Redemption#4624]
**Links:**
* source: http://wow.gamepedia.com/High_Admiral_%22Shelly%22_Jorrik
http://wowwiki.wikia.com/wiki/High_Admiral_%22Shelly%22_Jorrik
https://de.wowhead.com/npc=26081/hochadmiral-shelly-jorrik

Yes, he DOES give rep into exalted. I'm at 544/1000 exalted and he still gives me 5 rep, so I assume he'll give rep till max exalted (yay!). Armory: 
https://de.wowhead.com/npc=26081/hochadmiral-shelly-jorrik#comments:id=423641:reply=102885

**What is Happening:**
The creature was added with wotlk and should reward reputation. it is needed for those hardcore reputation booty bay farmer.

So i added the spawn for him now :) https://i.imgur.com/t1H0Ikp.jpg

Respawn timer is set to 9 hours, as said in the wowhead comments

**Comment by svijetlo** [comment]
![WoWScrnShot_060820_124114](https://user-images.githubusercontent.com/61908373/84021823-998b2900-a985-11ea-8934-7dbb03ae3ba1.jpg)
![WoWScrnShot_060820_124144](https://user-images.githubusercontent.com/61908373/84021831-9bed8300-a985-11ea-8514-4e10edc89540.jpg)
