### ISSUE TITLE
Unable to cancel or purchase items from AH after restart

### ISSUE THREAD

**Issue by AranMat** [WoWManiaUK/Redemption#4625]
**Links:**

**What is Happening:**
I recently created an auction and unable to cancel it, but able to cancel auctions from before restart. Same goes with purchasing items, only old listed i can purchase, I spoke to GM Psygoa and he confirmed and asked me to report it here
![Capture](https://user-images.githubusercontent.com/38553469/83955224-da355600-a850-11ea-9f03-336fe655489d.JPG)
The item circled i am unable to purchase, the option is greyed out when i select it, same goes for newly created auctions, option is greyed out to cancel it.

**Comment by Oganku** [comment]
Can confirm being unable to purchase/bid certain items on the AH.

**Comment by svijetlo** [comment]
yes AH has some problem, i can not click on some item in AH at all only hover mouse over them , also item i post to AH i can not cancel auction nor click on those item of mine in item lists in auction 
i would assume it is like so for all newly posted items after yesterday reset as for other item it works just fine

**Comment by wow-mania** [comment]
This is solved periodically when server updates. It should be ok after today's restart.
