### ISSUE TITLE
[QUEST] Super Sticky

### ISSUE THREAD

**Issue by billykitty** [WoWManiaUK/Redemption#4626]
**Links:**
https://www.wow-mania.com/armory/?quest=4504
https://www.wow-mania.com/armory/?item=11834

**What is Happening:**
The drop rate for Super Sticky Tar from Tar Beast, Tar Creeper, Tar Lord, and Tar Lurker feels like it's super low! Could you please verify the drop rate is 33%?

**What Should happen:**
The drop rate for Super Sticky Tar should be 33%.

**Comment by Rushor** [comment]
Will check!

**Comment by Rushor** [comment]
![KPZwNWM 1](https://user-images.githubusercontent.com/5568820/83963071-52c50280-a8a3-11ea-9061-b0bfe0f50c54.png)


yes is 33 percent
