### ISSUE TITLE
Transmog disappearing

### ISSUE THREAD

**Issue by Lightshammer** [WoWManiaUK/Redemption#4627]
Hi, what happened is on Friday I got disconnected a lot during a guild raid, on one of the re logging i found all my items are missing their transmog except the Weapon Boots, and Waist. and they are still missing till now.

**Comment by svijetlo** [comment]
@Lightshammer  are the saved sets also gone form npc

**Comment by wow-mania** [comment]
This is due to improperly shutting down the client or not logging out during restarts

**Comment by Rushor** [comment]
pls contact a gamemaster for that, since serverside we cannot do much here

**Comment by Lightshammer** [comment]
I didn't check the transmog NPC, but i still have the transmog items in my
inventory.
