### ISSUE TITLE
[Spells/Hunter] Roar of Recovery line of sight issue

### ISSUE THREAD

**Issue by Keader** [WoWManiaUK/Redemption#4628]
**What is Happening:**

If hunter use roar of sacrifice with pet out of line of sight, spell will trigger cooldown but nothing happens.

**What Should happen:** if pet is not in line of sight, spell need fail and not trigger any cooldown

Showcase: https://drive.google.com/file/d/1CRCQiLoyrG7gKkrIMBArQTDFWLARLUsC/view?usp=sharing

**Comment by svijetlo** [comment]
it is working fine could not be bothered to make video and upload it and SS wont show much for this
