### ISSUE TITLE
[Spell/Warlock] Demonic Knowledge

### ISSUE THREAD

**Issue by Keader** [WoWManiaUK/Redemption#4629]
**What is Happening:**

Talent description (rank3): Description: Increases your spell damage by an amount equal to 12% of the total of your active demon's Stamina plus Intellect.

Problem is: in wow mania it dont automatic update when intelect or stamina change.

**What Should happen:** Should update warlock spell power, based in how much stamina / intelect pet has.

Showcase: https://drive.google.com/file/d/15ilU-iDPWgAmuBpDUTQ7QlMVNRyLhvi0/view?usp=sharing

**Comment by Sharuzan** [comment]
![WoWScrnShot_060820_131221](https://user-images.githubusercontent.com/47272908/84024423-2c2dc700-a98a-11ea-9fd1-b6d4c7785a18.jpg)

Confirmed working as intended :) Buff and stats are applied immediatly :)
