### ISSUE TITLE
[ICC/Deathbringer] Deathbringer dont lose auras on death

### ISSUE THREAD

**Issue by Keader** [WoWManiaUK/Redemption#4631]
**What is Happening:**
When you kill deathbringer, he dont realy die, he cast a feign death spell instead.
But our current code, cause 2 issues:

1 - Keep players that attack with DOT in combat for more time that should.
2 - Recount continue counting dps/damage with deathbringer "dead", since dots still damage him (you just cant see it), that's why recount dps/damage change.

**What Should happen:**
Deathbringer should lose all negative auras on "death"
It fix both issues above

**Comment by svijetlo** [comment]
stops counting things as soon he drops down
