### ISSUE TITLE
[Crashfix] npc_lord_illidan_stormrage

### ISSUE THREAD

**Issue by Keader** [WoWManiaUK/Redemption#4632]
**What is Happening:**

Fixed a crash in npc_lord_illidan_stormrage::npc_lord_illidan_stormrageAI::SummonNextWave()
WaveCount can overflow and crash the code.

**Comment by svijetlo** [comment]
is this for BT illeden fight for crash one he spawns adds ?

**Comment by Keader** [comment]
no.
is a quest in shadowlands one.
BT illidan has some crash @svijetlo ?
if yes, report pls.

**Comment by svijetlo** [comment]
@Keader  it never happen to me , but i did seen ppl crash ones he fly to air phase and summ those 2 adds from blades in BT fight

**Comment by jeyrella** [comment]
@Keader Don't know how you expect us to test this one, since we don't know what the problem was.  Have Keader, contact us in the discord dev channel on this one pls.

**Comment by Keader** [comment]
Tou dont need, is Just for janitor remember.
