### ISSUE TITLE
Mixology of alchemist

### ISSUE THREAD

**Issue by AhmedAlami96** [WoWManiaUK/Redemption#4633]
**Links:**

**What is Happening:** Mixology give increased duration only (2hours flask)

**What Should happen:** it should incresed also the  effect of flasks ( more than 125sp if we're talking about flask of wyrm for example )

**Comment by Rushor** [comment]
effect is already increased see spell_gen_mixology_bonus_AuraScript

keep in mind that the amount that is displayed in tooltip is not correct (blizzlike client issue)

you must inspect the stat change in character tab itself

**Comment by Rushor** [comment]
see https://github.com/WoWManiaUK/Redemption/issues/3215 and https://github.com/WoWManiaUK/Redemption/issues/3649
