### ISSUE TITLE
Call to arms

### ISSUE THREAD

**Issue by Myzeriel** [WoWManiaUK/Redemption#4634]
**Links:**

**What is Happening:**
cant turn in quest Call to Arms, after pressing complete quest it doesnt do anything
this is not happening all the time, but sometimes

**What Should happen:**
complete quest

**Comment by Oganku** [comment]
The quest works fine, but you're able to get it more than once daily. The problem is that you can only turn it in once per day, and if you try to complete it a second time the same day, it just doesn't let you. Just limiting the quest from being given more than once daily should be fine.

**Comment by Aristo14** [comment]
as mentioned above..
