### ISSUE TITLE
Captain Skarloc Heroic Loot

### ISSUE THREAD

**Issue by robertgf1** [WoWManiaUK/Redemption#4635]
https://wowwiki.fandom.com/wiki/Captain_Skarloc

He continiues to drop "normal" loot when doing heroic mode, boss before him (Lieutenant Drake) drops heroic loot, so it seem to be an issue with Skarloc's Loot table.

He should drop heroic loot, requiring level 70 with an ilvl 115.

**Comment by svijetlo** [comment]
![WoWScrnShot_060820_133100](https://user-images.githubusercontent.com/61908373/84025698-53859380-a98c-11ea-824a-ddd43f0bb165.jpg)
![WoWScrnShot_060820_133103](https://user-images.githubusercontent.com/61908373/84025715-56808400-a98c-11ea-8a86-ab67feb0ab76.jpg)

**Comment by Rushor** [comment]
Retail tbc heroic loot is now different, keep that in mind when playing wotlk :)

**Comment by GMZinius** [comment]
For notes:
I had a ticket today saying the same thing as the OP 
I did check the Mania armory and there are seperate loot tables for this boss 

Normal mode https://www.wow-mania.com/armory/?npc=17862#drops (6 items) 
Herioc mode https://www.wow-mania.com/armory/?npc=17862#drops-1 (16 items) 
_In the herioc loot there are x3 66 ilvl 103 - x6 70 llvl 115 and a few gems_
