### ISSUE TITLE
Reflected abilities affect the caster post-duel

### ISSUE THREAD

**Issue by Kinkywiener** [WoWManiaUK/Redemption#4636]
**Links:**
https://www.wow-mania.com/armory/?spell=23920
https://www.wow-mania.com/armory/?spell=13043
https://www.wow-mania.com/armory/?spell=8458
https://www.wow-mania.com/armory/?spell=8462
I apologize if I left any other spells out.

**What is Happening:**
After finishing a duel by forfeit/win/loss, the reflected abilities stay on the target or damage the target if talking of direct damage abilities. Example given: If I as a warlock cast Immolate or Corruption on the target and the spells get reflected and still endure after the duel ended, the debuffs actively damage me, which a lot of times ends up with me dying of it. Reflected direct abilities (Fireball, Shadow bolt...) kill the target if reflected while the target is below the hit points of the damage value of the spell.

**What Should happen:**
Spells shouldnt have post-duel consequences after reflected.

**Comment by Keader** [comment]
https://github.com/TrinityCore/TrinityCore/issues/19852#issuecomment-435190398
Looks like a blizzlike bug.
