### ISSUE TITLE
Pushing The Limit buff not always activating

### ISSUE THREAD

**Issue by Kinkywiener** [WoWManiaUK/Redemption#4637]
**Links:**
https://www.wow-mania.com/armory/?spell=70753
https://www.wow-mania.com/armory/?item=50275
https://www.wow-mania.com/armory/?spell=44448
https://www.wow-mania.com/armory/?spell=54490
https://www.wow-mania.com/armory/?spell=44549

**What is Happening:**
According to the 2nd set of the mage gear, the abilities should grant 12% haste as Pushing The Limit buff on the caster after the aforementioned spell buffs are consumed. Sometimes, after Missile Barrage in consumed, the haste buff is not granted. Allegedly, Hot Streak works just fine. I didnt test Brain Freeze. 

**What Should happen:**
Haste buff should be granted after the effect is consumed.

**Comment by Keader** [comment]
I cant reproduce your issue.
Check: https://youtu.be/R7A7g4tti4U

**Comment by mamgy** [comment]
I noticed this problem also so i spent some time trying to find when this happens, only thing that i notices is when only 4 out of 5 Arcane Missiles gets casted even without interupting cast by moving or being attacked by someone .... 2set bonus ( Push to the Limit ) will NOT proc.


![Missile Barrage1](https://user-images.githubusercontent.com/63264336/84092215-fd9a0580-a9f6-11ea-8d7a-e2087a1ed2d1.png)
![Missile Barrage2](https://user-images.githubusercontent.com/63264336/84092230-0d194e80-a9f7-11ea-9292-43bd58d922be.png)
![Missile Barrage3](https://user-images.githubusercontent.com/63264336/84092273-29b58680-a9f7-11ea-8397-7f8796c06ded.png)

**Comment by Keader** [comment]
i still cant reproduce.
if you find any reproduce steps, let me know and i will fix.

**Comment by mamgy** [comment]
https://youtu.be/rb4_Xg8kZbU

There is even video when it happens, i really can't tell what causes that.
