### ISSUE TITLE
Quest Tooltip hovering over NPCs bug.

### ISSUE THREAD

**Issue by dauzhanyer** [WoWManiaUK/Redemption#4640]
**Preface:**
I know I am not supposed to report UI issues here, but the GM I spoke to asked me to create one here since we weren't able to resolve the issue.
I am a relatively new player on this server (joined 31st May), and **downloaded all of my game files from the Wow-Mania website.**

**What is Happening:**
When hovering over an NPC which is supposed to drop quest objective items, the tooltip of the quest progression is missing. The tooltips for quest progression of any other kind of objective (slay x enemies, revive x amount of soldiers, etc.) is functional and present when hovering over an NPC.

**What Should happen:**
Hovering over an NPC should show the amount of lootable x objects obtained so far.

**What I have tried:**
1. Disabling all my addons and resetting to default settings from the in-game interface menu, and having a GM "clear my char".
2. Clearing the cache with all of the addons removed.
3. Deleting the Interface and WTF folders.

None of these options worked for me.

**Comment by svijetlo** [comment]
can you pls post here few screen shoots of it how does it look ones you hover over mob etc

**Comment by wow-mania** [comment]
This is 3.3.5a not retails. This is not how it worked.
