### ISSUE TITLE
Loot Bug

### ISSUE THREAD

**Issue by jookerxx** [WoWManiaUK/Redemption#4644]
**Links:**
screen shot for loot from boss
https://prnt.sc/sy53md

**What is Happening:**
Anubarak 25 on TOC25 Loot bugged cant see them after some one left raid i rolled item been rolled over but couldn't handed and after i close window loot couldnt open it any more 
and i call GM he is also couldnt see loot

**What Should happen:**
Should be able to give loot to ppl in raid 
please at least give tank feet dropped from Anub to this sad warr name  Juliantauren via email

**Comment by svijetlo** [comment]
i could not be able to reproduce this by some one leaving raid 
and/or by closing loot window i could look at loot again
