### ISSUE TITLE
[Raid] The Ulduar tram

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#4645]
**Links:** https://youtu.be/_kDKVUayo7s

**What is Happening:** In Ulduar, the tram that is supposed to take you to the spark of imagination where you fight Mimiron is not working. Instead, the players can use the teleporter to access the spark as soon as Kologarn has been defeated. 

**What Should happen:** In order to activate the Spark of Imagination teleporter, the players should first need to ride the tram as shown in the video above. The entrance to the tram is located in the Shattered Walkway, at the end of the Corridor of Ingenuity

![Screenshot_20200612-075959~3](https://user-images.githubusercontent.com/34783736/84500690-10286f00-ac83-11ea-8ec0-920fa938ea8f.png)

**Comment by Keader** [comment]
Cant be fixed for now.
Has a core bug that make traim button fall of tram, so... even if i script the tram, players cant active all the time, because button will not be there :/
