### ISSUE TITLE
[Quest] Battle for the Undercity - 13267 (and maybe 13377)

### ISSUE THREAD

**Issue by jeyrella** [WoWManiaUK/Redemption#4646]
**Links:**
Horde
https://wow-mania.com/armory/?quest=13267
https://wow-mania.com/armory/?npc=32518

Alliance
https://wow-mania.com/armory/?quest=13377
https://wow-mania.com/armory/?npc=29611

**What is Happening:**
On completion, Thrall, to whom you hand in the quest, despawns rather quickly - so quick it is not much time enough to choose the reward.
Since it takes ~20 mins to complete this epic quest, this is significantly annoying as there is no other way to complete - one has to abandon and re-do entire quest.

Although not tested, I suspect the Alliance version of this quest has the same issue with King Varian Wrynn.

**What Should happen:**
Please increase the despawn time for Thrall (and Wyrnn>) on completion.

p.s. @Rushor thankyou thankyou thankyou for taking the time to implement this epic quest - from those who care about the lore, we appreciate it :)

**Comment by svijetlo** [comment]
WAAAAAAT this works ... when i was doing it loooong ago it was not working damn mzst do it again :D

**Comment by Rushor** [comment]
alliance should be np, because player get ported to stormwind at the end (in stormwind is the questender)

current despawntimer for thrall after event is 120 seconds.

i increased it to 6 minutes

fixed one ptr is up again

**Comment by Rushor** [comment]
compile started ready to test

**Comment by jeyrella** [comment]
confirmation vid.  not very interesting :D  https://youtu.be/Azk8ZTmUHM0
