### ISSUE TITLE
Kalu'ak Fishing Derby incorrect start time in a really weird way

### ISSUE THREAD

**Issue by emeraldastro** [WoWManiaUK/Redemption#4647]
**Links:**
![image](https://user-images.githubusercontent.com/61832025/84570144-135f5000-ad94-11ea-9f6b-65144b8a0a20.png)
![image](https://user-images.githubusercontent.com/61832025/84570142-0e9a9c00-ad94-11ea-8fde-8cd3ca6b3780.png)
![image](https://user-images.githubusercontent.com/61832025/84570148-19553100-ad94-11ea-9984-10e31a5e4a13.png)

**What is Happening:** The Kalu'ak Fishing Derby starts at an earlier point other than 14:00 Server Time. In the screenshots, a winner was declared at 13:40 Server Time (please excuse my 15:40 due to local time). An announcement of the event's start happened at 14:00 Server Time but the quest was still "Better Luck Next Time" since that very beginning. There was no further announcement made for a winner, even though I caught and delivered a fish at 14:10 and there was no prior announcement to my quest delivery.

**What Should happen:** The Kalu'ak Fishing Derby should start at 14:00 ST, there should be no winner before 14:00 since the event shouldn't be active at that time.

**Comment by Rushor** [comment]
can you clearly write the timers:

when started which timer (server time) - and when should it start?

**Comment by emeraldastro** [comment]
The event started at an earlier point than 13:40 Server Time which is unknown to me but I would assume it's 13:00 Server Time.
There was a winner at 13:40 when the event should start at 14:00, meaning the event was already running before the scheduled starting time on the calendar.

**Comment by jeyrella** [comment]
looks like #4581 isn't fixed then properly.  this is really odd as last week it worked perfectly.

**Comment by Rushor** [comment]
this is the timer in ptr right now https://i.imgur.com/23PL6Rw.png

**Comment by Rushor** [comment]
i changed the timers to start at the same time now (15.00) 

keep in mind that db time and server time is different

**Comment by Aristo14** [comment]
re-opening so it can be checked this weekend.

**Comment by Rushor** [comment]
that issue is really complicated because of different server times ptr/db/live/user

**Comment by jeyrella** [comment]
Indeed, and no way to test on PTR due to dependency on scripts running at specific time.  Just have to apply to live and observe.

**Comment by wow-mania** [comment]
This is on live already so just reopen if needed.
