### ISSUE TITLE
[Pet] Mend Pet aggro issues

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#4648]
**Links:** Mania armory currently down, using this in the meantime
https://wotlkdb.com/?item=43350#created-by
https://wotlkdb.com/?spell=48990
https://www.wowhead.com/ferocity-hunter-pets

**What is Happening:** 
I can't test every situation yet, but I can suppose the following is causing the issue:

If a hunter using the [Glyph of Mend Pet](https://wotlkdb.com/?item=43350#created-by) casts [Mend Pet](https://wotlkdb.com/?spell=48990) on their pet, the pet's auto attacks will generate insane threat (~10k threat pet hit, even at level 10). This allows the hunter to simply disable growl and use the pet's focus to do more damage and makes it even easier to solo as a hunter. 

I have only experienced this with a wolf and cat, so it's possible it only happens to [Ferocity-type](https://www.wowhead.com/ferocity-hunter-pets) pets, or it might be linked to one of the talents used in the bread and butter wolf dps build.

**What Should happen:** Mend pet should not allow the pet to become a super aggro-magnet.

**Comment by Keader** [comment]
i cant reproduce.
can you give me a reproduce steps?

**Comment by Oganku** [comment]
I can't narrow it down too much, but be marksman hunter at level ~40 at least, use a regular wolf pet with regular talents. Use the mend pet glyph, use the Mend Pet spell and have your pet attack anything. *Might* also be due to heirloom Charmed Ancient Bone Bow.

**Comment by Oganku** [comment]
Without mend pet on, wolf generates about ~500 threat per second over 18 seconds on a regular mob.
![WoWScrnShot_061320_184009](https://user-images.githubusercontent.com/34783736/84580543-cf754680-ada5-11ea-9f08-2871ccc0388c.jpg)

Same conditions, but now using mend pet, wolf generates about ~3500 threat per second, a whopping 3k more than previously. This flat increase applies the same at lower levels, allowing hunters to shoot at their leisure and never ever pull aggro off their pet.
![WoWScrnShot_061320_184223](https://user-images.githubusercontent.com/34783736/84580561-f5025000-ada5-11ea-860e-83f223115cfb.jpg)

**Comment by Keader** [comment]
will look again tomorrow morning

**Comment by Keader** [comment]
Fixed.
