### ISSUE TITLE
[ICC/Professor Putricide] Missing mechanic in Choking Gas

### ISSUE THREAD

**Issue by Keader** [WoWManiaUK/Redemption#4650]
**What Should happen:** On blizzard servers, if players get hitted by Choking Gas, need gets Ooze Variable and Gas Variable dispelled.

PS: Ooze Variable and Gas Variable is that bottles debuff (when PP change phase in heroic modes, that dont allow you attack Ooze with collor different of your bottle)

**What is Happening:** Players affected by choking gas, still remain with Ooze Variable and Gas Variable.

**Comment by Aristo14** [comment]
please add refferences for future gh's

**Comment by Keader** [comment]
Go to retail and get hitted by this If you dont belive.
