### ISSUE TITLE
[Item] Minor Darkmoon Prize - Does not contain items sometimes

### ISSUE THREAD

**Issue by Rushor** [WoWManiaUK/Redemption#4651]
**Links:**
https://www.wow-mania.com/armory/?item=19298

**What is Happening:**
The item does not contain an item sometimes. https://i.imgur.com/DPz3TAV.jpg

**What Should happen:**
Item should always conain an item

**Comment by Sharuzan** [comment]
https://youtu.be/1z8CCoOCUrk

Fix confirmed, item always contain loot, thanks! :)
