### ISSUE TITLE
[Item] Battered Junkbox - often does not contain anything

### ISSUE THREAD

**Issue by Rushor** [WoWManiaUK/Redemption#4652]
**Links:**
https://www.wow-mania.com/armory/?item=16882

**What is Happening:**
often does not contain anything https://i.imgur.com/Cbe05wB.jpg

**What Should happen:**
dhould always contain at least 1 item

**Comment by Sharuzan** [comment]
https://youtu.be/o1gDewU_hA8

Fix confirmed. Boxes always drop at least 1 item.
