### ISSUE TITLE
[Quest] Load'er Up! - creature follows you around endless even if quest is completed

### ISSUE THREAD

**Issue by Rushor** [WoWManiaUK/Redemption#4653]
**Links:**
https://www.wow-mania.com/armory/?quest=11881

**What is Happening:**
The creature for the quest https://www.wow-mania.com/armory/?quest=11881 https://www.wow-mania.com/armory/?npc=25969 does not despawn after quest is completed https://www.wowhead.com/quest=11881/loader-up#videos:id=60992

https://i.imgur.com/n5KfxCq.jpg

**What Should happen:**
Creatures should despawn 3 seconds after quest is completed and should not keep following the player

**Comment by Sharuzan** [comment]
https://youtu.be/s1ZYdVuELsU

Fix confirmed, Jenny now despawns when she reaches the quest NPC.
