### ISSUE TITLE
[Quest] Planting the Banner - Missing actions

### ISSUE THREAD

**Issue by Rushor** [WoWManiaUK/Redemption#4654]
**Links:**
https://www.wow-mania.com/armory/?quest=10518
https://www.wowhead.com/quest=10518/planting-the-banner#videos:id=57313

**What is Happening:**
The quest is missing one important detail - the summoned creatures do not walk up to the tower

**What Should happen:**
the summoned creatures should walk up to the tower once summoned as can be seen in the vieo

**Comment by Sharuzan** [comment]
![WoWScrnShot_061420_124514](https://user-images.githubusercontent.com/47272908/84591294-7eb12c80-ae3d-11ea-96f1-4c98ffa8c7f5.jpg)
![WoWScrnShot_061420_124208](https://user-images.githubusercontent.com/47272908/84591296-7fe25980-ae3d-11ea-85cb-d0ce2b158e2e.jpg)

Mobs + the mob dropping the helm now spawn and walk to the top of the tower when the player has planted the banner. Fix confirmed. Thanks!
