### ISSUE TITLE
[ICC] Bosses and Parryhaste 

### ISSUE THREAD

**Issue by Rushor** [WoWManiaUK/Redemption#4655]
-- There is a parryhast on all the bosses in the ICC.
-- ICC
-- Lord Marrowgar Parry Haste Disabled
-- Deathbringer Saurfang Parry Haste Disabled
-- Festergut Parry Haste Disabled
-- Rotface Parry Haste Disabled
-- Professor Putricide Parry Haste Disabled
-- Prince Taldaram Parry Haste Disabled
-- Prince Valanar Parry Haste Disabled
-- Blood-Queen Lana’thel Parry Haste Disabled
-- Sindragosa Parry Haste Enabled (was already fixed here https://github.com/WoWManiaUK/Redemption/issues/3632)
-- The Lich King Parry Haste Disabled

source: https://avengingwrathy.wordpress.com/2010/01/15/bosses-who-parry-haste/
https://www.wowhead.com/forums&topic=150538

By Dunsinane on 2010/03/30 at 8:15 AM (Patch 3.3.3)
The vast majority of bosses in ICC do not parry haste. The exceptions are Deathwhisper (who cares?) and Sindragosa.

http://maintankadin.failsafedesign.com/forum/index.php?f=6&t=27934&rb_v=viewtopic

**Comment by Oganku** [comment]
Is the fix just for lady deathwhisper since sindy already had it enabled? Also Halion needs to have it enabled in case it isn't. 
The 3 main endgame bosses that should have it are ldw, sindy and Halion

**Comment by Rushor** [comment]
Sindra and ldw have it enabled yes.

Halion i gonna check
