### ISSUE TITLE
Titles missing

### ISSUE THREAD

**Issue by Myzeriel** [WoWManiaUK/Redemption#4657]
**Links:**

**What is Happening:**
after obtaining title Argent champion, i noticed that im missing "Twilight Vanquisher" and "The Argent Champion" in the titles list at the character tab.
After trying with relog, delete cache, nothing. I run 2.7.0 through launcher as admin.
After making a ticket and waiting for almost half the day, i received a mail from a GM giving me instructions to do the same thing i already tried. 
After making another ticket, i got Psygoa GM trying to figure it out how and why, trying to solve this in many ways - still nothing. Both titles are missing in the list.
I've been told to message Janitor on discord, which i did, but its been 5h since that and i still have no reply. Decided to post it here, coz it is a serious issue. 
All i can see in the titles list on the character tab are the PvP titles and only one PvE - Jenkins, from the achievement Leeeeeeeeeeeeeroy!

**What Should happen:**
show me all the titles that i have obtained!

**Comment by Oganku** [comment]
Titles are ordered in alphabetical order on your character sheet and both the ones you mention are in the T's: 'Twilight Vanquisher' and 'the Argent Champion'.

You might need to scroll down the list a bit if you have more than 5, but both appear just fine.
![image](https://user-images.githubusercontent.com/34783736/84602903-7f0af100-ae58-11ea-8d31-57ffb7b59ab0.png)
![image](https://user-images.githubusercontent.com/34783736/84602924-9c3fbf80-ae58-11ea-8e69-0da7c973f025.png)
