### ISSUE TITLE
Transmogging Silver Hand Legplates

### ISSUE THREAD

**Issue by Tsriell** [WoWManiaUK/Redemption#4658]
Contacted GM Osyris about a potential transmog issue with the Lich King donor set and Silver Hand set and was asked to fill out a ticket. Slots involving head, chest, shoulders, bracers, belt, gloves, and feet appear to have transmogged accordingly. However, my menu options for Legs are completely empty.

Transmogs are also greying out set bonuses, although they appear to be working normally. (Just a visual bug)

**Comment by wow-mania** [comment]
I cannot find the cause for this. The legs is identical to other pieces.
If you are still having problems contact me on Discord and I can try to manually do it for you.
