### ISSUE TITLE
[Death] Spirit position if you die in Storm-wind (ally char)

### ISSUE THREAD

**Issue by svijetlo** [WoWManiaUK/Redemption#4659]
**What is Happening:**
if a player dies in SW it spirit get spawn outside of SW gate (cord and position will be shown on SS )
thos that is not problem in "normal" death case 
bigger issue is if player fly to SW phase to building fall down under SW and can not reach corpse and can not find spirit healer to res that way , so they resort to send pointless ticket 
![image](https://user-images.githubusercontent.com/61908373/84696847-67f9fb00-af4d-11ea-9b8f-4c6f6980b370.png)

**What Should happen:**
if you die in SW you need to spawn at grave yard in evelin forest close to SW 
(position of it will be shown in next SS) 
![image](https://user-images.githubusercontent.com/61908373/84697033-b27b7780-af4d-11ea-891f-d3744a5e92ed.png)

**Comment by Rushor** [comment]
if you die in stormwind you now get ported to Elwynn Forest, Goldshire and NOT Elwynn Forest, Stormwind

**Comment by svijetlo** [comment]
![WoWScrnShot_061620_003651](https://user-images.githubusercontent.com/61908373/84712684-87068600-af69-11ea-9059-ec63069a283f.jpg)
