### ISSUE TITLE
[Quest] Rescue at Sea

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#4661]
**Links:** https://www.wowhead.com/quest=14152/rescue-at-sea
https://www.wowhead.com/npc=34947/kvaldir-berserker
https://www.wowhead.com/npc=34907/kvaldir-harpooner
https://youtu.be/zhgV9WrdFhI?t=52

**What is Happening:** The quest [[Rescue at Sea]](https://www.wowhead.com/quest=14152/rescue-at-sea) is doable and somewhat works to a point, but the spawning behavior of the quest mobs is wrong.

As can be seen in [the video linked above](https://youtu.be/zhgV9WrdFhI?t=52), the 2 ships (horde and ally) should be under constant assault by the [Kvaldir Berserkers](https://www.wowhead.com/npc=34947/kvaldir-berserker) and [Harpooners](https://www.wowhead.com/npc=34907/kvaldir-harpooner). 
![image](https://user-images.githubusercontent.com/34783736/84841104-642ead00-b00f-11ea-88a1-497a3e50b670.png)

At the moment, only a set amount of Berserkers and Harpooners spawn, and they take about ~5mins to respawns, which makes it annoying to kill the 8 berserker the quest requires. There aren't enough to usually do it in one cycle and the player finds themselves waiting for a new spawn cycle.

**What Should happen:** 
1. The mobs should respawn much faster, as the wowhead comments from wotlk indicate. The video above (although it's from wod) does support this comment).

2. As they respawn, the mobs should appear to jump from the boarding kvaldir ship before engaging in combat. (Only visual)

**Comment by Rushor** [comment]
Will check that

**Comment by mfranca0009** [comment]
There are two boats, one Alliance and one Horde where the mobs needed for the quest raid these two ships. The respawns for these mobs are extremely slow compared to the video and the animation of the mobs jumping onto the ship from their own does not exist; they just spawn on the Horde or Alliance ship.

I was able to confirm the issues occurring, the quest does work as intended but just takes longer to do with the respawns being slow.

**Comment by jeyrella** [comment]
Yep. COnfirmed.  Although.... low priority as it technically does work.

**Comment by mfranca0009** [comment]
Was using a local WOTLK server for testing, and changing the `spawntimesec` from 180 seconds (3 minutes) to 30 seconds for IDs 34947 and 34907 in `creature` table seems to increase respawn speed well enough to have the mobs spawning as fast or a little bit less than the WoD video provided. 

I was playing around with the MovementType but it does not seems to change anything regarding the mobs jumping off their ship; they still spawn on the alliance/horde ship.

**Comment by Rushor** [comment]
yes i know, i will fix that needs deeper fixes in their ai

**Comment by Rushor** [comment]
spawntime reduced, texts and jump events added

**Comment by jeyrella** [comment]
Works really well!  https://youtu.be/sN0R0YV2XUE
Thanks @Rushor
