### ISSUE TITLE
Via the voting systems it says that when i join the WOW mania community i get a free mount and free heirlooms. I got the mount but i did not receive any heirlooms

### ISSUE THREAD

**Issue by Hyaroko** [WoWManiaUK/Redemption#4662]
**Links:**
https://mmtop200.com/world-of-warcraft

**What is Happening:**
Via the voting systems it says that when i join the WOW mania community i get a free mount and free heirlooms. I got the mount but i did not receive any heirlooms.

I also filled in the ID in the RAF section, we were both online but didnt receive anything.

**What Should happen:**
Receive Heirlooms, get RAF rewards if this is still possible

**Comment by Hyaroko** [comment]
![free heirloom](https://user-images.githubusercontent.com/67044322/84867817-0a180100-b07c-11ea-98f4-05df0dea5f09.PNG)

**Comment by Hyaroko** [comment]
My ingame name is Hyaroko and my wow mania ID is  2064165

**Comment by svijetlo** [comment]
that is wrong information i em here for 3 and never got that only mount ones you reach lvl 10

**Comment by Hyaroko** [comment]
3 what ? Well i think it's not a nice way to bring people in based on a lie... they should hand out the heirloom items now since they advertise with it and i saw it at a friend who was playing and decided to start because of it!

**Comment by svijetlo** [comment]
well actually it is true , as while you lvl you get Maniac Points for free , you can use Maniac Points to buy heirlooms, that technically info is not wrong  , as you can use maniac points to boost professions etc

**Comment by jeyrella** [comment]
@Hyaroko thanks for your feedback
As svijetlo said, it is not technically wrong as you receive free tokens by leveling which you can (choose to) swap for heirlooms, amongst other cool benefits for free.
However we will pass on your comments to GMs to see if we can better phrase this.

As for RAF issues, please fill out a GM ticket in-game.

**Comment by Hyaroko** [comment]
at what levels will i receive maniac points ? Cause i havent received one yet

**Comment by Hyaroko** [comment]
> @Hyaroko thanks for your feedback
> As svijetlo said, it is not technically wrong as you receive free tokens by leveling which you can (choose to) swap for heirlooms, amongst other cool benefits for free.
> However we will pass on your comments to GMs to see if we can better phrase this.
> 
> As for RAF issues, please fill out a GM ticket in-game.

it's not wrong, it's misleading. As it states here you receive the mount and leveling heirlooms if you join.. But it's not stating that you first need to lvl all the way up to receive points to buy the heirlooms which you dont need anymore since you already lvld urself all the way up..

In general terms people call that clickbait.

**Comment by svijetlo** [comment]
if you make an alt you get 1 more free mount and you can have on it free heirloom =)

**Comment by Hyaroko** [comment]
then i still need to lvl a toon :P
