### ISSUE TITLE
Put the game in windowed mode and now it only displays a black screen

### ISSUE THREAD

**Issue by Curtizzler** [WoWManiaUK/Redemption#4663]
**Links:**

**What is Happening:**
I tried to change some display settings on the game, changed the graphics, scale... then I changed it to windowed mode... bad idea. now the game only displays a black screen. i have tried restarting the game, restarting my PC, running in compatibility mode and still no luck

**What Should happen:**
It should display the game.

**Comment by Curtizzler** [comment]
Have done some testing, a slight fix to this is to add SET gxWindow "1" in to the config.wtf
I say slight fix because when you want to go back to full screen, it still only displays a black screen

**Comment by Aristo14** [comment]
This issue doesnt seem to be on the client side, we will keep track on it however.

**Comment by WhitephoenixTheBunny** [comment]
read: https://wow-mania.com/forum/viewtopic.php?f=13&t=188
