### ISSUE TITLE
NPC missing

### ISSUE THREAD

**Issue by Desmock992** [WoWManiaUK/Redemption#4664]
During the quest "The storm king's vengeance" I was unable to find the NPC Prince Navarius.
Without him was impossible to complete the quest and proceed with the chain.
I search on the web for any tips to solve this issue but seems that it's a quest bug.

**Comment by mfranca0009** [comment]
Quest: https://www.wowhead.com/quest=12919/the-storm-kings-vengeance
NPC: https://www.wowhead.com/npc=29821/prince-navarius

He is in the proper location on the PTR and I do remember completing this quest recently on a normal level 78 Paladin on Redemption live. Can't seem to reproduce the issue.

**Comment by jeyrella** [comment]
Works fine.  You have to search for him.

**Comment by jeyrella** [comment]
So looks like there may be a specific issue on live stopping Navarius spawning / in wrong phase.  Can't replicate it on PTR.  Could be any number of things causing this.  
Would imagine restart will reset this situation.  May reopen if this continues to be an issue.
