### ISSUE TITLE
[Loot] Automatic Passing and Anub'arak un-lootable items

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#4665]
_The following tests were made in the PTR_

**Links:** Issue #4149 
https://wowwiki.fandom.com/wiki/Trial_of_the_Crusader_loot
Full loot table for the raid (Alliance and horde version of items available in link above)

**What is Happening:**

1. The automatic passing on loot causes a lot of confusion in players that aren't always aware of what's causing them to pass the item. The battered hilt drops are a great example of an item that 'drops' server-side and nobody should never know about, but the automatic passing message makes people angry that they missed a valuable hilt they should never have seen in the first place.

A great place to reproduce this is Trial of the (Grand) Crusader. In this raid, alliance and horde loot have different items, but the bosses/chests drop alliance AND horde loot when looted, but you are only able to see your own faction's and will automatically pass on the opposite's. 

Below is an image showing loot obtained after defeating Icehowl on ToGC 10 (heroic mode). In this difficulty, Icehowl drops 2 items, a Crusader Orb and has a chance to drop a pattern (which it did here).

Being Alliance, the 2 items I could roll on were [Carnivorous Band](https://www.wowhead.com/item=47920/carnivorous-band) and 
 and [Gauntlets of Rising Anger](https://www.wowhead.com/item=47917/gauntlets-of-rising-anger). Those are both alliance items, which is fine. However, I did get a message that I automatically passed both [Belt of the Impaler](https://www.wowhead.com/item=47859/belt-of-the-impaler) and [Pauldrons of the Spirit Walker](https://www.wowhead.com/item=47860/pauldrons-of-the-spirit-walker) both horde items that would have dropped for this raid ID were a horde group to loot the boss instead. Seeing that I passed on those items is completely irrelevant and 90% of the playerbase will just be upset they have 'lost' 2 extra items.

![image](https://user-images.githubusercontent.com/34783736/84958018-6b66c100-b0ca-11ea-9c6e-3a4b7298476a.png)

Below is the same situation replicated this time with the second boss: Lord Jaraxxus.
Details are omitted here because the exact same logic as above applies, but without the lucky drop of a pattern.

![image](https://user-images.githubusercontent.com/34783736/84958430-5b9bac80-b0cb-11ea-828c-74730c5b6c27.png)

2. Moving on, we have the issue with Anub'arak, the final boss of the same raid. This boss drops items from his body, as well as items from the [Argent Crusade Tribute Chest](https://www.wowhead.com/object=195665/argent-crusade-tribute-chest). The items dropping from both of those behave the same way as mentioned above, with players automatically passing the opposite faction's items, but there is now a new issue.

Upon being presented the prompt to roll on the items of their faction, for which they are eligible, the rolls of a player will not be accounted for and the items will simply never be awarded to anybody and will instead vanish into thin air.

The first picture below shows the 4 items dropped from the boss' corpse.
![WoWScrnShot_061720_183712](https://user-images.githubusercontent.com/34783736/84959015-889c8f00-b0cc-11ea-9cb5-8e11e148c0f3.jpg)

This one shows what happens after I rolled greed on both the crusader orb and the [Westfall Saber](https://www.wowhead.com/item=47971/westfall-saber) shown above. We see the Crusader Orb being rolled for and awarded properly, but the weapon just vanishes with no roll being accounted for. The same happened with the other 2 weapons right after.
![WoWScrnShot_061720_183723](https://user-images.githubusercontent.com/34783736/84959162-d0231b00-b0cc-11ea-8e2a-666b474e321f.jpg)

**What Should happen:**

1. I do not believe the change from issue #4149 is blizz-like and being able to see in chat the items you automatically pass on because you are not eligible due to faction causes a lot of frustration from players. Such a message should never be visible for players as it has 0 impact on the game and simply shows them extra information that should only be handled server-side.

2. Anub'arak items that are rolled for should be handed out normally and rolls should not be completely ignored, after which the items are simply sucked into a void.

**Comment by Keader** [comment]
why toc is dpping other faction items in first place? xd

**Comment by Oganku** [comment]
Might be lazy code from Blizzard? You can only see your faction's items and you automatically pass on the opposite's, but you shouldn't see that you auto passed on them.

**Comment by Keader** [comment]
try now Oganku ^^
