### ISSUE TITLE
Wrong faction mounts at argent grounds

### ISSUE THREAD

**Issue by swix1978** [WoWManiaUK/Redemption#4666]
**Links:**

**What is Happening:**after faction change I cannot use the proper faction mounts to complete quests 

**What Should happen:**

**Comment by Aristo14** [comment]
Either make an in game ticket or GH report with more info. 
What mounts? What quest? What change? etc etc

**Comment by swix1978** [comment]
I made in game ticket they told me to come here, argent daily quests I used to be horde I changed to alliance now any quests that require me to mount I cannot use alliance mounts there’s no options
