### ISSUE TITLE
gnomish death ray

### ISSUE THREAD

**Issue by e42j** [WoWManiaUK/Redemption#4667]
**Links:**
https://www.youtube.com/watch?v=leoK-k0AP2g

**What is Happening:**
The engineering trinket "gnomish death ray" doesn't do any damage on Naxx realm. 

**What Should happen:**
 Looking at web posts, it's supposed to do 4k+ crits.

ty!

**Comment by wow-mania** [comment]
Please refrain from posting videos and add info on item/quest from armory etc.

**Comment by svijetlo** [comment]
1)  Cooldown - 5mins, 4sec channeled spellcast
2)  Cancelling it resets it's cooldown.  Use it when you know you can pull it off.
3)  Always have over 1.5k hp when firing.  There's a chance you could kill yourself with low HP.
4)  The more it hurts you in the wind-up, the more it's going to hurt your enemy.
5)  It's channeled but doesnt seem to be interrupted by getting hit.  It will get interrupted from shield bash/silence, and then reset the cooldown.
6)  Shares Cooldown with bombs.  Don't throw a bomb right before you wanna use death ray.
7)  Net-o-matic and this is a wonderful combo.
8)  In PvE, if trying to death ray an untapped target, the mob will aggro as soon as you start channeling.
9)  In PvE, it seems like this creates VERY LITTLE hate for how much damage it does
10) In PvE, be extra careful about your HP when firing.  It can potentially hurt you for 1.2k.
11) In PvE and PvP, if a mob is "Immune"  (Like a pally bubble/banish/etc) the mob must get out of his bubble before you start channeling.  If you fire it while he's immune, it will just say "Immune" and reset cooldown.  So don't try to time it out so as soon as his bubble goes down he gets zapped, gotta wait until it goes down.
12) As a warrior, the best way to use it pvp I've found is to charge in, bloodrage, intimidating shout everything else away, then zap, then play cleanup on whatever is left.

So far my records a 4216 crit  :)  Herod never saw it comin

**Comment by Rushor** [comment]
damage effect is:

Effect 0: Id 2 (SPELL_EFFECT_SCHOOL_DAMAGE)
BasePoints = 600
Targets (6, 0) (TARGET_UNIT_TARGET_ENEMY, NO_TARGET)

that works all as intended

**Comment by e42j** [comment]
Doesn't work - I just tested - zero damage to me or to target.  is there anything else i should  do to help address this?  (I'm new to reporting bugs here).  thankyou so much!
