### ISSUE TITLE
[Raid] Trial of the Crusader - Faction champions not affected by Death Group

### ISSUE THREAD

**Issue by jookerxx** [WoWManiaUK/Redemption#4668]
**What is Happening:**
Death Knights Death grip not working on any Faction Champions in TOC either 10 or 25, didn't try it in Grand Crusade yet but I assume its same, since all strategies are including this spell to be used .

**What Should happen:**
Death Knights should be able to use death grip on Faction champions in TOC, as its pvp fights and most of raids are   I hope we can be using it to be able to do the usual tactics as its on every forum of Blizz Like, those champions are highly threating and that spell is the thing can make a lot of difference in that fight.

**Comment by wow-mania** [comment]
@Rushor please don't just fix without confirming. A lot of stuff is as-is. and should not be "firxed".

**Comment by jeyrella** [comment]
Certainly could ge deathgripped as it was in retail, video from era:  https://youtu.be/x6zLbPKOfvQ?t=39

However deathgrip can be resisted, and we will need to test to rule out it this "bug" as actually a resisted case.  Am not a DK specialist but I think even if resisted the DK should go to the mob instead.

**Comment by svijetlo** [comment]
if grip is resist 2 things will happen you will go to enemy or nothing will happen 
also grip has effect of forcing target to attack you for 3 sec that should not work on champions , as they are immune to tount like effects they decide what they want to attack

**Comment by jookerxx** [comment]
well, @wow-mania am just making this because there is real issue at that boss you can count how many raids passing Faction champions wasting time there always figuring out how lucky would be not to have many dies due to going to mob target kill then the mele faction champion are switching to them and killing one by one of the raid till wipe.
Also the Fact about "death grip" the taunt effect should happens once target are gripped, So the problem we have it here is the resist to grip ofc not the immune to taunt, As its normal TOC so taunt are working already when the HC mode TOGC are immune to taunt mechanic but also still the grip effect should works then the immune to taunt comes after.

I believe there is solution for this because I've seen it working perfect in Icecrown marrowgar spikes & Ozes at Rotface.

**Comment by Rushor** [comment]
just to confirm db:

34441, 34442, 34443, 35749,
34444, 35740, 35741, 35742,
34445, 35705, 35706, 35707,
34447, 35683, 35684, 35685,
34448, 35724, 35725, 35726,
34449, 35689, 35690, 35691,
34450, 35695, 35696, 35697,
34451, 35671, 35672, 35673,
34453, 35718, 35719, 35720,
34454, 35711, 35712, 35713,
34455, 35680, 35681, 35682,
34456, 35708, 35709, 35710,
34458, 35692, 35693, 35694,
34459, 35686, 35687, 35688,
34460, 35702, 35703, 35704,
34461, 35743, 35744, 35745,
34463, 35734, 35735, 35736,
34465, 35746, 35747, 35748,
34466, 35665, 35666, 35667,
34467, 35662, 35663, 35664,
34468, 35721, 35722, 35723,
34469, 35714, 35715, 35716,
34470, 35728, 35729, 35730,
34471, 35668, 35669, 35670,
34472, 35699, 35700, 35701,
34473, 35674, 35675, 35676,
34474, 35731, 35732, 35733,
34475, 35737, 35738, 35739);

there is no grip immunity fot them at all.

you say the taunt effect is not working? well all the creatures have special aggro system

**Comment by jookerxx** [comment]
I don't know what that's means but taunt effect is working already only its not gripping the creatures to the death knight

**Comment by Rushor** [comment]
Hm okay

**Comment by svijetlo** [comment]
tount efect should not work on then non of tount effects , as it is like pvp fight player can ignore tount and only get dmg or grip effect of that spell

**Comment by Rushor** [comment]
try now with deathgrip

**Comment by svijetlo** [comment]
works better now you can Dg then not allways as there is resist and also if they dont fell like it they will just move awey and go to other player in raid

**Comment by jeyrella** [comment]
Multiple reports that this is not fixed on live.  @Rushor can you check pls if this code was properly transported.

**Comment by Rushor** [comment]
yeah the fix is still on ptr, but you must ask jani if it is on live aswell in that case

**Comment by wow-mania** [comment]
Everything goes when I close. There is not "if".

**Comment by jeyrella** [comment]
ok so in the reference video posted https://youtu.be/x6zLbPKOfvQ?t=39  the DK uses DG 14 times and as far as I can tell is only resisted once.
This seems I am hearing reports from live users that they used it 10+ times and did not work / resisted every time.
The two don't seem to match.

@Aristo14 @svijetlo could I ask one of you to check this again, as you have specific knowledge in DK, and it is not my forte....  am having trouble finding the actual resist % that should be present but from the video I would guess it isn't massive?

**Comment by svijetlo** [comment]
¸for some reson all of them are missing 
![image](https://user-images.githubusercontent.com/61908373/86119927-b1ad1e80-bad3-11ea-8ec0-fdb5d82f924d.png)

**Comment by Rushor** [comment]
okay it was disabled in scripts, all bosses are immune to the grip effect there, we need to add an exception for those guys here

**Comment by Rushor** [comment]
problem was that all bosses in the whole world are general immune to it
will add an exception for the bosses in toc
but you must check if all other bosses are still immune to the effect

**Comment by svijetlo** [comment]
ok now you can grip them 90% of time , other bosses just say immune if you use grip on them
