### ISSUE TITLE
[Quest] Fuel for the Fire quest bug

### ISSUE THREAD

**Issue by JasdfWasdf** [WoWManiaUK/Redemption#4669]
**Links:**
https://www.youtube.com/watch?v=jwpzV0wORW4&feature=youtu.be

**What is Happening:** 
I am trying to do the quest Fuel for the Fire and charming the Bloated abominations and have them attack the Drakkari Skullcrushers but they won't.

**What Should happen:**
The bloated abominations should attack the Drakkari Skullcrushers and when I make them explode.

**Comment by Oganku** [comment]
The abomination's explosion Works, but they indeed won't move when ordered to attack a mob. They just follow you and you're forced to drag them across mobs before making them explode. This makes it much more difficult for clothes that can't sustain as much damage

**Comment by wow-mania** [comment]
Please reference material to prove how it "should be".

**Comment by Oganku** [comment]
[Bloated Abomination](https://www.wowhead.com/npc=28843/bloated-abomination#abilities) is the pet controlled by the [Scepter of Command](https://www.wowhead.com/item=39238/scepter-of-command). 

Various wowhead comments from wotlk indicate the controlled minion should have regular pet behavior on top of its 2 special abilities ([Flatulate](https://www.wowhead.com/spell=52497/flatulate) and [Burst at the Seams](https://www.wowhead.com/spell=59576/burst-at-the-seams)):

> If you're a tank or class that can round up a lot of them easily, set abom on passive and follow.

This indicates the pet is by default NOT on passive and will attack by itself. Confirmed by:

> It is entirely false that you need to have your abomination melee them before exploding to get a kill.

This implies the abom can melee, which it currently cannot.

Final obvious confirmation: 

> Click on one troll, hit your attack button on the pet bar, then go after another. Soon you'll have a train going.

**Comment by Rushor** [comment]
abbo should autoattack again correctly now

**Comment by jeyrella** [comment]
Reference video for how it "should be". https://youtu.be/66Cf6cfv_Co?t=147

**Comment by jeyrella** [comment]
Abom does not follow player on charm, and stands still, even though "follow" mode is activated.  
See reference video showing that as soon as abom is charmed, it should automatically be following player.

**Comment by Rushor** [comment]
It might me not be possible to fix that, but i will try. All charm currently have that problem

**Comment by wow-mania** [comment]
We will leave this as-is. Quest is completable.

**Comment by wow-mania** [comment]
@Rushor have a look at it and see what can be done please.

**Comment by Rushor** [comment]
okay all fixed, will follow directly on charm now

**Comment by jeyrella** [comment]
Notes for testing
quest  https://wow-mania.com/armory/?quest=12690
disguise  https://wow-mania.com/armory/?item=38699
scepter  https://wow-mania.com/armory/?item=39238

**Comment by jeyrella** [comment]
Works great now!  Pretty much exactly as it should do.  Abom follows on charm, responds to kill commands, melees properly and explodes.
Thanks @Rushor this is one of the few quests that always irked me :)
https://youtu.be/x6e0QGTBjKs

**Comment by Rushor** [comment]
thank you for testing! :)
