### ISSUE TITLE
[Quest/NPC] Among the Champions (NPC Behavior)

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#4670]
**Links:** https://www.wowhead.com/quest=13790/among-the-champions
https://www.wowhead.com/npc=33738/darnassus-champion#comments
https://www.wowhead.com/npc=33739/exodar-champion#comments
https://www.wowhead.com/npc=33740/gnomeregan-champion#comments
https://www.wowhead.com/npc=33749/undercity-champion#comments
 

**What is Happening:** The mounted champions you need to challenge as part of [Among the Champions](https://www.wowhead.com/quest=13790/among-the-champions), NPCs 33738 thru 33749, do not path back to their spawn points after being defeated and will simply stand still, slowly cluttering the arena.

**What Should happen:** The champions should move back to their starting positions once they exit combat, whether they are defeated or de-aggro'd because their opponent ran out of range.

_The rest of the quest works fine, it's just the NPCs not pathing back to their original positions that is broken._

**Comment by Sharuzan** [comment]
Exodar champion(still need to test both champions) returns to it's original position, got it on video.

First Gnomeregan champion returned to it's original position, but wanting to test it out once more, it didn't return to it's position but test realm went offline very shortly after. 

Wanting to go through some of the other champions to check just in case, I had also tried a Stormwind Champion which worked and I got that on video too.

Alas after restart and having bested 4 champions, I could not manage to gain access to fighting anymore champions, even by adding the quest again manually by command. 
Abandoning and picking up the quest from the npc again, just picked up the quest with completed progress.

Issue still need UC/Gnome/Darnassus champions confirmed and I don't know if we need to check the rest of the factions too.

Will be picking this up tomorrow(Saturday) if no one has had any luck with the rest.

**Comment by Oganku** [comment]
It can happen with all champion, although I'm not sure what causes it exactly.

**Comment by Rushor** [comment]
at 0-1 percent hp they should always evade actually

**Comment by Oganku** [comment]
Evading is fine, but they just don't path back after leaving combat.

**Comment by Oganku** [comment]
Happens with the valiants in the 2 smaller arenas also.

**Comment by Rushor** [comment]
But they change faction aswell to friendly? Can you may do a Video?

**Comment by Oganku** [comment]
They don't change faction and you can still interact with them, they just don't move after being defeated and eventually they're all over the place instead of all standing around the arena.

**Comment by Sharuzan** [comment]
https://youtu.be/H93xwUo_M1I

Getting video of Exodar Champion tomorrow. Issue described in video info.

**Comment by Rushor** [comment]
a video with reproduce would be nice

**Comment by Rushor** [comment]
added a call, that they walk always to homeposition once they reset.

**Comment by jeyrella** [comment]
Regressed.
![image](https://user-images.githubusercontent.com/46089380/88761519-350b6f80-d167-11ea-9498-de36306f2cda.png)

**Comment by Rushor** [comment]
reapplied

**Comment by svijetlo** [comment]
they now get back to original spot ones you beat them in duel

**Comment by jeyrella** [comment]
Issue still present on live.

**Comment by Rushor** [comment]
i don't understand. while testing the code worked and now not anymore?

**Comment by Rushor** [comment]
okay change now: the will have an additional call to move to the homeposition once they evade.

**Comment by Zanguin-ManiaTester** [comment]
Unless it's due to PtR instability, valiants are now pathing correctly; staying within the "arena".
Will upload proof later when I have time.

**Comment by Zanguin-ManiaTester** [comment]
https://youtu.be/PzA_FPePWvg

3 / 4 pathed back. Played as alliance and it was a dwarf being too lazy to return :)
Fix still needs work :)

**Comment by Rushor** [comment]
okay next try
