### ISSUE TITLE
[Dungeon] Azjol-Nerub Blink glitch

### ISSUE THREAD

**Issue by Lunaros123** [WoWManiaUK/Redemption#4671]
**Links:**
![received_605530093422114](https://user-images.githubusercontent.com/67155990/85140941-4dbe6680-b246-11ea-8853-a2fa30e8c425.jpeg)
![received_261459788606707](https://user-images.githubusercontent.com/67155990/85140956-531bb100-b246-11ea-9e1b-d479d0233b07.jpeg)

**What is Happening:**
Using mage spell "Blink" while being in the water at Azjol Nerub teleports you to different place with no exit, as shown on attached picture.

**What Should happen:**
The player should be teleported 20 yards in the direction they're looking at while casting Blink

**Comment by Sharuzan** [comment]
Issue confirmed on PtR.

https://www.youtube.com/watch?v=RGLQ-2Wp4xE

**Comment by Keader** [comment]
i dont see big possibility to fix it
blink system of TC is a real mess...
i realy dont want change it, because has big chances to cause more issues for a "minor improvement"

**Comment by Rushor** [comment]
Hm Maybe disable blink in water in that instance?

**Comment by Keader** [comment]
naah, i will try tomorrow something better :/

**Comment by Keader** [comment]
try now please.
should have some improvement.

**Comment by Sharuzan** [comment]
https://youtu.be/7caZJrVQQWM

Fix confirmed, thanks!
