### ISSUE TITLE
[Buff] Increased Block

### ISSUE THREAD

**Issue by cathyr1** [WoWManiaUK/Redemption#4673]
The buff from this item https://www.wow-mania.com/armory/?item=45145 not working correctly when changing librams. It seems to have 30 second cooldown (similar like trinkets) however without visible counting time remaining while other librams (e.a. https://www.wow-mania.com/armory/?item=47661) don´t have such cooldown and the effect starts nearly immediately after equping the item.

Is this correct?

**Comment by Keader** [comment]
Fixed.
