### ISSUE TITLE
HoR Hc Escape Event

### ISSUE THREAD

**Issue by Tankjnr** [WoWManiaUK/Redemption#4674]
**Links:**
![WoWScrnShot_062020_113723](https://user-images.githubusercontent.com/62798410/85198719-3ab1a200-b2eb-11ea-8edb-2d6ffc950c6a.jpg)

**What is Happening:**
In the last phase of HoR Hc. If the party wipes. LK doesnt reset
(neither do the ghouls or pudges)

**What Should happen:**
If party dies the escape event should reset.

**Comment by wow-mania** [comment]
pretty sure it works and something was done for this to happen.
it will be nearly impossible to fix without steps to reproduce.

**Comment by Keader** [comment]
I cant reproduce.
Event reset WHEN LK Kill Jaina.
Not when everyone die xD
