### ISSUE TITLE
[Hyjal Summit] Archimonde (Visual Issue)

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#4675]
**Links:** https://youtu.be/ZV2uiI7CbCM?t=6

**What is Happening:** Archimonde is currently ridiculously small and is simply standing there until he enters combat.

**What Should happen:** As can be seen in this [video from retail](https://youtu.be/ZV2uiI7CbCM?t=6), Archimonde should be channeling a green beam at Nordrassil when he is out of combat. Also, he is more than twice the size that he is currently on Redemption.

The fight itself is fine and the issue is only visual.

**Comment by Rushor** [comment]
That is a nice one

**Comment by Rushor** [comment]
boom https://i.imgur.com/FBm6D3o.jpg

**Comment by jeyrella** [comment]
Properly impressively big.... and GREEN DEATH RAY from his hands I WANT SO BAD GIMME
![WoWScrnShot_062220_214711](https://user-images.githubusercontent.com/46089380/85333708-f46a6780-b4d1-11ea-8379-898f837134b9.jpg)

**Comment by svijetlo** [comment]
there is quest item that can give you that green death ray
