### ISSUE TITLE
[Violet Hold] Limit the amount of summons before waves start

### ISSUE THREAD

**Issue by Keader** [WoWManiaUK/Redemption#4676]
**What is Happening:** In violet hold , before event start has 3 portals summoning npcs.
Currently, it has no limit of summoned monsters and it can cause server lag if accumlate alot of npcs there.

**What Should happen:**
Should has a limit of 3 npcs summoned.
To summon a new npc, one of already summoned need die first.

**Comment by Sharuzan** [comment]
https://youtu.be/sSbIJc8Tuuk

Improvement. Generally only 3 mobs appear at one time, however at one point, 4 spawned.
