### ISSUE TITLE
Character doesnt load

### ISSUE THREAD

**Issue by wowtinus** [WoWManiaUK/Redemption#4679]
The character is a box, many NPCs are also displayed as a box.
Seems that the character information isn't loaded.

This happened after upgrading to client 2.7.0

**Comment by Sharuzan** [comment]
Upgrading to 2.7.0 did make some players realmlist/files read-only. 
Do try and clear your cache and make sure to uncheck "read-only" for files and folders in your Mania directory. 
Then try run the launcher as admin and see what happens :)

**Comment by wow-mania** [comment]
Contact support.
