### ISSUE TITLE
[Quest/Event] (More) Torch Catching  - Quest 11657/11923

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#4681]
**Links:** https://www.wowhead.com/quest=11657/torch-catching
https://www.youtube.com/watch?v=TnWuqOUBldI

**What is Happening:** The torches are visible and behave correctly, but are lacking their shadow. It is possible to follow them by angling the camera in a very weird way, but it makes it much more difficult and the daily version where you need to catch 10 juggles is more difficult than intended due to it.

**What Should happen:** As can be seen in [this video](https://www.youtube.com/watch?v=TnWuqOUBldI) from retail Wotlk (and many others) the torches are supposed to have a shadow below them, which is how you're supposed to follow them in order to catch them.

**Comment by wow-mania** [comment]
This may not be able to fix.

**Comment by jeyrella** [comment]
**Torch Catching** quests:
Starters:
https://wow-mania.com/armory/?quest=11923 (alliance)
https://wow-mania.com/armory/?quest=11657 (horde)
Daily versions
https://wow-mania.com/armory/?quest=11924
https://wow-mania.com/armory/?quest=11925

For the avoidance of doubt, this is NOT the same as Torch **Tossing** which is the OTHER ticket 4680, which are these ones:
Torch Tossing quests:
Starters:
https://wow-mania.com/armory/?quest=11922  (alliance)
https://wow-mania.com/armory/?quest=11731  (horde)
Daily versions
https://wow-mania.com/armory/?quest=11921
https://wow-mania.com/armory/?quest=11926

**Comment by Rushor** [comment]
no solution for this - but it is still easy doable https://i.imgur.com/ofixLV4.jpg

add:

/console cameraDistanceMax 50

and scroll out as much as possible, then the qzest is easy
