### ISSUE TITLE
Orc Starting area

### ISSUE THREAD

**Issue by crazyheifer34** [WoWManiaUK/Redemption#4682]
**Links:**

**What is Happening:** When ya go near a certain area the entire game crashes every time ya go near that area and ya can't load that char again when it happens 

**What Should happen:**

**Comment by Rushor** [comment]
Try to reinstall the Client, delete Cache and disable strange addons.

I guess this does Not Happen to everyone

**Comment by crazyheifer34** [comment]
This has happened to me and my husband and when we try to log back onto
that char it crashes every time
