### ISSUE TITLE
[ICC/Sindragosa] Backlash - Heroic

### ISSUE THREAD

**Issue by Keader** [WoWManiaUK/Redemption#4683]
**What is Happening:** Players affected by Unchained Magic, get Instability debuff (69766) each time that they cast something.
Problem is: You can just dispel it using immune (ice block, divine shield, etc.)

**What Should happen:** When you use immune having instability in heroic difficulty, you should dispel unchained magic, dispel instability, _**but active backlash when instability is removed**_.

Proof:

Log: http://worldoflogs.com/reports/rt-szhtkresk1zad6du/xe/?s=5985&e=6293&x=spell+%3D+%22Ice+Block%22+OR+spell+%3D+%22Unchained+Magic%22+OR+spell+%3D+%22Instability%22+OR+spell+%3D+%22Backlash%22+OR+spell+%3D+%22Divine+Shield%22

![image](https://user-images.githubusercontent.com/7120913/85226606-b6285780-b3ae-11ea-8cba-2ff39ea620df.png)

A video about it: https://youtu.be/5MFTxvSHy1g?t=21
Mage get the unchained, get 1 stack of instability and use iceblock.
when he do it, everyone around get backlash damage

**Comment by jeyrella** [comment]
Hang on one moment here.  There is a VERY important facet here, did we check that using ice block WITHOUT a stack of instability doesn't trigger backlash?

**Comment by Keader** [comment]
yes, because who trigger backslash is instability aura.
If you dont have instability, you cant trigger backlash :)
