### ISSUE TITLE
[World Event] 2 Midsummer Bonfires at Azure Watch.

### ISSUE THREAD

**Issue by Sharuzan** [WoWManiaUK/Redemption#4686]
Links:
https://www.wow-mania.com/armory/?achievement=1032
https://www.wow-mania.com/armory/?quest=11735
https://www.youtube.com/watch?v=s63re3OfCZQ

What is Happening: See uploaded picture. 

What Should happen: Only one Midsummer Bonfire should 
<img width="759" alt="Azuremyst" src="https://user-images.githubusercontent.com/47272908/85236028-3e901200-b41a-11ea-8ac8-f180ec57e615.png">

https://www.youtube.com/watch?v=s63re3OfCZQ
Video from retail also shows only 1 Midsummer Bonfire.

I could only interact with the left Bonfire.

**Comment by Sharuzan** [comment]
https://youtu.be/7vnRgmLoaO8

Darnassus, but example of duplicate behavior.

**Comment by Rushor** [comment]
it works like that: trigger s spawned over the spellfocus > trigger summons bonfire > player can enlight or despawn bonfire. we had to adjust all positions of the triggers and the bonfires to the same position and remove the duplicate static spawned bonfires

overlapping cannot be fixed, but everything else is done now.

**Comment by Sharuzan** [comment]
Thank you Rushor :)

**Comment by jeyrella** [comment]
Great :)
![WoWScrnShot_062220_212636](https://user-images.githubusercontent.com/46089380/85332048-1f9f8780-b4cf-11ea-8aa1-d734215113c8.jpg)

**Comment by jeyrella** [comment]
For clarity of readers, this means ALL the bonfires where there were obvious duplicates in differing locations are fixed, not just Azure Watch.  e.g. Shadowmoon Village, 

Also that many of the bonfires where it was very difficult to find the ? are much easier as the "duplicates" are better aligned.
