### ISSUE TITLE
[World Event][Quest]: Midsummer Bonfires contain a duplicate "Desecrate This Fire!" quest.

### ISSUE THREAD

**Issue by Sharuzan** [WoWManiaUK/Redemption#4688]
Links:
https://www.wow-mania.com/armory/?achievement=1032
https://www.wow-mania.com/armory/?quest=11735
https://www.youtube.com/watch?v=s63re3OfCZQ

What is happening: When you interact with an opposing faction's Midsummer Bonfire, the Bonfire will offer 2 quests; one being a duplicate of the other. 
As soon as you turn in either quest, the other one disappears, so the player can not abuse it and complete it twice from one Bonfire - So marking this one as "Low Priority Cosmetic issue".

What Should happen: Midsummer Bonfires should only give out one quest. 

https://www.youtube.com/watch?v=s63re3OfCZQ
As seen here, the Midsummer Bonfires offers no additional quests.

<img width="234" alt="Desecrate this Fire!" src="https://user-images.githubusercontent.com/47272908/85236255-b2331e80-b41c-11ea-9581-1f26c36a1562.png">

**Comment by Rushor** [comment]
is this happening for all bonfires?

**Comment by Sharuzan** [comment]
<img width="695" alt="bloodmyst" src="https://user-images.githubusercontent.com/47272908/85236406-f4109480-b41d-11ea-9e2f-91b1b25d494d.png">

The story is the same on Bloodmyst at least and having done a bunch of the other bonfires too, it seems to me the alli ones mess a bit, at least from a horde player's perspective.

**Comment by Rushor** [comment]
it happens on the whole world

**Comment by Rushor** [comment]
fiying it once ptr is up

**Comment by Rushor** [comment]
seems like in core the menu is called twice in GameEventMgr

**Comment by Rushor** [comment]
as is for now
