### ISSUE TITLE
[Quest/Escortcreature] Despawn Range too low

### ISSUE THREAD

**Issue by Rushor** [WoWManiaUK/Redemption#4689]
**What is Happening:**
Currently the range for escortquests with core escortai is too low. It is 50 yards and the creature often despawn way too often. 

**What Should happen:**
The range to despawn if too far away should be 100 yards.

**Comment by Rushor** [comment]
good guy to test it is quest: 836

**Comment by jeyrella** [comment]
item 8704 to start quest 836

**Comment by jeyrella** [comment]
Looks good.  https://youtu.be/YEwY3Y2mYi4
