### ISSUE TITLE
[ICC/Gunship] Damage of incinerating blast

### ISSUE THREAD

**Issue by Keader** [WoWManiaUK/Redemption#4690]
**What is Happening:** 

Our current formula is: 1000 + energyLeft²
with 100 energy, max damage will be: 1000 + 10000 = 11k
Problem is:  if you check http://worldoflogs.com/reports/udqni9w8roj989w7/xe/?x=spell+%3D+%22Incinerating+Blast%22
and http://worldoflogs.com/reports/ul76xm556v85ir2v/xe/?x=spell+%3D+%22Incinerating+Blast%22
You will see that this spell can hit more then 11k.

**What Should happen:** I cant determine the exactly formula for this. But looks like we are missing about 20% of damage.
So, i'm adding 20% more damage for this spell.

Has other issue, fixed too.
if incinerating blast hits 5k in boat, it should hit 5k in npcs  that spell hit too.
Right now, it always hit 1k in npcs, instead hit same thing that hit in boat.

**Comment by svijetlo** [comment]
this is much better as before you could just spam 1,2 1,2 now the more nergy you build you do more dmg with skill 2 , and it makes fight more normal as it should be
