### ISSUE TITLE
[NPC] Tortured Skeleton 

### ISSUE THREAD

**Issue by Rushor** [WoWManiaUK/Redemption#4691]
**Links:**
**What is Happening:**
Tortured Skeleton https://www.wow-mania.com/armory/?npc=18797 Auchindoun: Shadow Labyrinth
has some missing feature.

**What Should happen:**
The Tortured Skeleton should some have random movement and some should appear dead and then attack the player if player run over them. Similar to a trap effect.

https://i.imgur.com/fOLgB21.jpg
https://i.imgur.com/CQxDWoq.jpg

added that :)

**Comment by jeyrella** [comment]
I mean.... really?  ok then....  well yeah it's "fixed"   https://youtu.be/5aQXAu2t0tk
