### ISSUE TITLE
[Item] Time Lost Proto Drake

### ISSUE THREAD

**Issue by Rushor** [WoWManiaUK/Redemption#4692]
**Links:**
npc=32491

**What is Happening:**
Creature can sometimes not drop the drake.

**What Should happen:**
The dropchance should alway be 100 percent. 

https://www.wowhead.com/item=44168/reins-of-the-time-lost-proto-drake wowhead has strange data on that drop. it is not correct and results in data mining where players do not loot the body, thus adding bad analysis data to wowhead

**Comment by jeyrella** [comment]
Well.  not sure we can really test this since 99% drop rate of now vs 100% drop rate of fix......
I will confirm this and trust you Rushor :)
