### ISSUE TITLE
Focused Aim- Hunter

### ISSUE THREAD

**Issue by Aceloth** [WoWManiaUK/Redemption#4693]
https://wow-mania.com/armory/?spell=53622      (MOD EDIT:  changed to wow-mania armory link)

It doesn't show any sign of the improvement of the hit rating % in stats on applying talent points on it.

I have tried with two different builds, one that includes the focused aim and one that it doesn't. It stays the same.

**Comment by Rushor** [comment]
Can a Tester confirm that?

**Comment by Aristo14** [comment]
This is only a visual bug on your character screen.

**Comment by Aceloth** [comment]
So the stats of hit % that doesn't show any difference in having talents on or less is just visual but still applies?
I tried myself and for example on my hunter it helps me keep my 8% and without will be lower so it makes me miss the 83+ target.

**Comment by Rushor** [comment]
there are several cases with buffs where the missing percent additions take place. it is mostly visual and happened on retail aswell
