### ISSUE TITLE
Feralas alliance flame

### ISSUE THREAD

**Issue by Tradervic402** [WoWManiaUK/Redemption#4694]
**Links:**

**What is Happening:** Going to the alliance camp in Feralas, and there is no bonfire.  Tent, npcs.. but no flame to extinguish

**What Should happen:**
There should be a fire there

**Comment by jeyrella** [comment]
You sure you don't need to use a blossom on it?  It might have been extinguished by a Horde.

**Comment by jeyrella** [comment]
Don't know what you're seeing, but it's definitely there.
![image](https://user-images.githubusercontent.com/46089380/85476621-a4160700-b5b0-11ea-8cb0-a8e1c8580bfd.png)

**Comment by jeyrella** [comment]
For avoidance of doubt, this is what it looks like after [Burning Blossom] has been used to re-light it
![image](https://user-images.githubusercontent.com/46089380/85477681-b133f580-b5b2-11ea-962b-59982623a9f1.png)
