### ISSUE TITLE
[NPC] Crok Scourgebane icc 10 hc 

### ISSUE THREAD

**Issue by lowbg** [WoWManiaUK/Redemption#4698]
**Links:**
https://youtu.be/y05RmuJCLvM

**What is Happening:**
This is happening on icc 10 hc its keep repeating same message: Augh! i must rest for a moment  in a spam  like in the video 
the mob called Crock scourgebane 
**What Should happen:**

should not spam that message  that many times

**Comment by jeyrella** [comment]
https://wow-mania.com/armory/?npc=37129

This happens when he is low on health and all his companions are dead.  At ~20% health he heals himself.

**Comment by jeyrella** [comment]
@lowbg can you provide the source please for your claim that he should not spam that message, as I cannot.  
Era-relevant video would be excellent.

**Comment by Rushor** [comment]
we can simply remove the spam, that he will say it only one time during the fight

**Comment by jeyrella** [comment]
We _can_, but we _should_ only do it if it is correct to do this.  
At the moment I can find no evidence (and the poster has not provided) that this is even a bug.

**Comment by Rushor** [comment]
removed the spamm for now (will not lable it as fixed, but the spamm is gone now)

**Comment by jeyrella** [comment]
Well.  I am marking this "fixed" but in protest that we have not established if this actually is a bug.
