### ISSUE TITLE
[Spell] [Death Knight] Chains of Ice

### ISSUE THREAD

**Issue by festerhowl** [WoWManiaUK/Redemption#4699]
Links:
Chains of Ice:  https://wowwiki.fandom.com/wiki/Chains_of_Ice
 Frost fever:    https://wowwiki.fandom.com/wiki/Frost_Fever

**What is Happening:** Chains of Ice isn't applying frost fever on the target if it has hand of freedom or if casting bladestorm. Unsure if other similar spells have the same effect.

**What Should happen:** Chains of ice should always apply frost fever disease on the target regardless of the person being immune to ensnare effects.

**Comment by Kilju** [comment]
You are immune to chains of ice during freedom. Since the spell never actually lands, it shouldn't add an secondary effect.

**Comment by Keader** [comment]
wrong.
you're immune to snare effect, not immune of all effects.
