### ISSUE TITLE
[Boss/Loot] Anub'arak loot vanishing

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#4700]
**Links:** Issue #4665

**What is Happening:** Point 2 of issue #4665 is still present. The body loot from Anub'arak in trial of the crusader (not the chest) will be visible when looting, but will instantly become un-lootable and vanish. Reign of the living/undying seems unaffected somehow, but other items just disappear and the body appears as if it held no items. Both group loot or master looter face the same problem.

**What Should happen:** The boss's drops should not just vanish and be unobtainable.

**Comment by Keader** [comment]
Fixed dear

**Comment by svijetlo** [comment]
ok i did this with 3 accounts , group loot and master loot 10 and 25 man ones did not see any loot desaper or auto pass msg and i could loot every boss , even if i would look at loot then move then come back i could still loot in normal ways
