### ISSUE TITLE
[NPC] Nagrand Elementals immunity to Nature spell school

### ISSUE THREAD

**Issue by Guigou4261** [WoWManiaUK/Redemption#4701]
**Links:**
http://www.wow-mania.com/armory?npc=17156
http://www.wow-mania.com/armory?npc=17158
http://www.wow-mania.com/armory?npc=17154
Lightning bolt ID: 25448
Chain Lightning ID: 25439
Thunderstorm ID: 51490
Earth Shock ID: 10414

**What is Happening:**
Every Elementals (Water, Earth, air) I can find in Nagrand seems to be immune to every single nature damage. You will find above every shaman spell I tried on them that doesn't work. I have linked above one of each elementals but it happens with every elementals of the same model even with different names. The only thing that works on them is flame shock and fire totems.

I contacted a GM. He made sure I use the right game version and the game launcher (I do) We cleared my cache, and tried to see if it was some temporary buffs on the NPCs. 

**What Should happen:**
Even if they have nature resistance, We should be able to damage those elementals. I have played on other private servers and Official servers as well. Never have I encounter this phenomenon.

**Comment by Sharuzan** [comment]
https://youtu.be/yDpQ0gT9kcM

Bug confirmed; Elementals are immune :)

**Comment by jeyrella** [comment]
Well.  Yes, but the problem with this one is confirming if this is correct as per original Blizzard or not.   Or what their status should be.
ust because it isn't like that on other servers doesn't mean it isn't correct.
Although wowhead comments would normally say there is an immunity, and those comments aren't there...

**Comment by jeyrella** [comment]
actually
https://www.wowhead.com/npc=17156/tortured-earth-spirit#comments
seems to confirm that in Wotlk (i.e. before 4.2) they were indeed immune to nature.
![image](https://user-images.githubusercontent.com/46089380/85846095-3975ee80-b79d-11ea-9f2c-ec71c5e1bd91.png)

**Comment by Sharuzan** [comment]
I just found sources for confirming them all to be blizzlike hang on

**Comment by jeyrella** [comment]
and 
https://www.wowhead.com/npc=17154/muck-spawn#comments
![image](https://user-images.githubusercontent.com/46089380/85846303-835ed480-b79d-11ea-872e-7c2e217d101f.png)

@Guigou4261 it seems you have been playing on servers that are not as accurate as Mania :)   Immunity to Nature is correct.

**Comment by Sharuzan** [comment]
<img width="864" alt="muck spawn" src="https://user-images.githubusercontent.com/47272908/85846356-f9673980-b7a5-11ea-8f8f-3e1117f88104.png">

https://wowwiki.fandom.com/wiki/Air_elemental
Attacks are frequently nature-based, and are usually immune or strongly resistant to Nature magic. They also tend to attack faster than other elementals.

https://wowwiki.fandom.com/wiki/Earth_Elemental_Totem
Earth elementals deal physical damage, but as with any earth elemental, they are immune to all Nature spells and effects.

**Comment by jeyrella** [comment]
Thanks @Sharuzan 👍

**Comment by Sharuzan** [comment]
Happy to help :)

**Comment by Guigou4261** [comment]
My mistake! Thank you for your time :)
