### ISSUE TITLE
[Spell] [Death Knight] Unholy Blight

### ISSUE THREAD

**Issue by festerhowl** [WoWManiaUK/Redemption#4704]
no links as the spell has been modified in later expansions and the tooltips provided weren't informative enough.

**What is Happening:**
Unholy Blight has a delay and takes approximately 2 seconds to apply after a death coil lands on the target. The unholy blight damage isn't adding up too after multiple death coils have been cast.

**What Should happen:**
unholy blight should have no delay and should apply immediately after a death coil lands on the target. 
Like deep wounds(warrior) and ignite(mage), unholy blight should also stack with each cast of death coil on the target and refresh the duration of the debuff as well.

**Comment by Zanguin-ManiaTester** [comment]
Death Coil instantly applies Unholy Blight on the target. Thanks!

https://youtu.be/PfdkhcZuguo

**Comment by festerhowl** [comment]
https://www.youtube.com/watch?v=2ZuzThfqYYU

as you can see the delay is quite apparent. I also used icy touch as proof that i am not experiencing any lags or visual bugs. Although it might seem like a minor issue but its not. Getting your diseases dispelled because your unholy blight didn't trigger 1 second faster is a waste of rune.

**Comment by Rushor** [comment]
The fix will be applied tomorrow
