### ISSUE TITLE
[Spells] PROC_FLAG_KILL vs CREATURE_FLAG_EXTRA_NO_XP_AT_KILL

### ISSUE THREAD

**Issue by Keader** [WoWManiaUK/Redemption#4706]
**What is Happening:** Current spell system, dont allow any spell with PROC_FLAG_KILL, proc vs creatures that have CREATURE_FLAG_EXTRA_NO_XP_AT_KILL.
It's wrong, because some raid creatures has this flag, it those spells should still proc
Example: Talent Rapid Killing (Hunter) need proc when hunter kill wicked spirit (LK)
Proof:

> [20:41:47.479] Rogerbrown Chimera Shot Wicked Spirit *8000* (O: 7279)
> [20:41:47.732] Wicked Spirit dies
> [20:41:47.789] Rogerbrown's Rapid Killing fades from Rogerbrown
> [20:41:47.789] Rogerbrown's Rapid Recuperation is refreshed by Rogerbrown
> [20:41:47.789] Rogerbrown gains Rapid Killing from Rogerbrown

source: http://www.worldoflogs.com/reports/b0e71guud7hcynf1/xe/?s=9921&e=10899&x=targetName%3D%22Rogerbrown%22+AND+spell+%3D+%22Rapid+Recuperation%22+OR+spell+%3D+%22Rapid+Killing%22+OR+targetName+%3D+%22Wicked+Spirit%22+&page=1

It affect pvp too.
It should proc if a hunter kill other player pet too.

I'm using Rapid Killing as example, but it affect any talent/spell that proc when you kill something.

**What Should happen:**

Spells should proc when kill creatures that are flagged as not granting XP.

PS: Ez way to test it.
Use a hunter with talent Rapid Killing.
And kill other player pet in duel :)
Rapid Killing need proc when you kill the pet.

**Comment by Aristo14** [comment]
> I'm using Rapid Killing as example, but it affect any talent/spell that proc when you kill something.

Just talking about Rapid Killing, it has an exception that it needs to be a kill that grants exp OR honor.  
Where all exceptions to talents like this taken into account? 

Killing a pet doesn't give exp nor honor (and if it should than that's a different GH) 

At the moment for this reason I can't confirm yet, please provide more info.

**Comment by Keader** [comment]
It's a complete list of spells effected:

![image](https://user-images.githubusercontent.com/7120913/86011633-50158300-b9f3-11ea-986a-737c2ee01e7b.png)

![image](https://user-images.githubusercontent.com/7120913/86011651-56a3fa80-b9f3-11ea-9619-8e2256e5105d.png)

As you can see, drain soul is in that list.
From MOP patch notes:

![image](https://user-images.githubusercontent.com/7120913/86011750-7e935e00-b9f3-11ea-9d7f-7322ef67becf.png)

It stay like that until mop.
We handle this proc flag wrong since always, creatures that have CREATURE_FLAG_EXTRA_NO_XP_AT_KILL and pets need proc spells with proc flag PROC_FLAG_KILL.
Is a implementation error that just fixed now (years after implementation)
