### ISSUE TITLE
[Spell/Item] Idol of Mutilation vs Lacerate

### ISSUE THREAD

**Issue by Keader** [WoWManiaUK/Redemption#4707]
**What is Happening:** Idol of Mutilation (itemid = 47668) has a chance to proc 200 de dodge when you attack a target with Lacerate or Swipe (bear form).
Problem is: Is working with Swipe, but is not proccing with lacerate

**What Should happen:** should proc with lacerate

Showcase: https://drive.google.com/file/d/10sIJLaiXKTZksO9pBUy1WdieonGNpMcD/view?usp=sharing

**Comment by Zanguin-ManiaTester** [comment]
https://youtu.be/AMdSaEDeb8A

Fix confirmed, thanks! Idol will proc off both abilities now.
