### ISSUE TITLE
[NPC] Merideth Carlson 

### ISSUE THREAD

**Issue by Rushor** [WoWManiaUK/Redemption#4708]
**Links:**
**What is Happening:**
Merideth Carlson should hand out her Manna-Enriched Horse Feed to only people/paladins who finish the quest [60] Manna-Enriched Horse Feed. However she does not have it in her shop.

This was added in patch 1.5.0 http://www.wowwiki.com/Merideth_Carlson

**What Should happen:**
DB/Creature: Merideth Carlson - add item Manna-Enriched Horse Feed
- the item will only be shown in the shop if you already rewarded the quest Manna-Enriched Horse Feed 

(quest=7645)

**Comment by jeyrella** [comment]
Confirmed corrected
https://youtu.be/9Y0wpgYIw0Q
