### ISSUE TITLE
[Quest][Classic] Rescue OOX-22/FE! - Update to WotlK Version

### ISSUE THREAD

**Issue by Rushor** [WoWManiaUK/Redemption#4711]
**Links:**
**What is Happening:**
http://www.wowhead.com/quest=2767/rescue-oox-22-fe#comments:id=799559

**What Should happen:**

Since WotlK, this quest event and the whole path must be way more short. The chicken should already complete the quest once reached the path.

**Comment by jeyrella** [comment]
Oh wow, this was changed in WotLK?  I thought it was Cata with the Flooding....
This is the comment you linked.
![image](https://user-images.githubusercontent.com/46089380/85945658-2d259900-b937-11ea-8299-90d293007779.png)
Should probably check the other escort quests (Tanaris, Hinterlands)

**Comment by jeyrella** [comment]
Actually, I think I have confirmed it should apply to all 3
https://www.wowhead.com/quest=836/rescue-oox-09-hl#comments:id=26322:reply=117837
![image](https://user-images.githubusercontent.com/46089380/85945734-afae5880-b937-11ea-94fa-5e41cdb1cae8.png)
https://www.wowhead.com/quest=648/rescue-oox-17-tn#comments:id=16412:reply=117838
![image](https://user-images.githubusercontent.com/46089380/85945860-69a5c480-b938-11ea-9784-4174c05ae92d.png)


https://wow-mania.com/armory/?quest=836
https://www.wowhead.com/quest=836/rescue-oox-09-hl
![image](https://user-images.githubusercontent.com/46089380/85945776-d8cee900-b937-11ea-9c0c-da810597f5e6.png)


https://wow-mania.com/armory/?quest=648 is also the old version, **but it looks like fix #1676 has regressed for this**

**Comment by Rushor** [comment]
Oh Well i will open new issues for the other two quests then later. This is fixed then
