### ISSUE TITLE
[Spell] [Death Knight] Raise Dead

### ISSUE THREAD

**Issue by festerhowl** [WoWManiaUK/Redemption#4712]
**Links:**

Raise Dead: https://wowwiki.fandom.com/wiki/Raise_Dead_(death_knight_ability)
**What is Happening:**
![Screenshot (58)_LI](https://user-images.githubusercontent.com/43633844/85929386-ed789600-b8d1-11ea-8aae-8149b837ce5e.jpg)
Ghoul action bar doesn't show up sometimes when using raise dead. I've noticed this spell starting to glitch after playing matches in Wintergrasp. Sometimes the spell will also gray out preventing the summoning of a ghoul. This issue persists until i relog back into the game.

**Comment by Keader** [comment]
reproduce steps?

**Comment by svijetlo** [comment]
might be visual bug so you need to phase zone for bar to show up 
and for grey icon it means pet still exist somewhere but could not follow you 
seen it happen after yopu kill BQ and run to valy there is not cast bar and icon is grey and you also can not use use death pact , but ones you stop for a bit pet shows up its cast bar 
thos i could not reproduce that castbar does not show

**Comment by Rushor** [comment]
try to reproduce with a vehicle. f.ex enter a demolisher while having a pet. after exit vehicle the pet bar should vansih

**Comment by wow-mania** [comment]
Close client delete cache, make sure you start the client using the Launcher as admin.
If you can send the exact steps to reproduce we will take another look.

**Comment by festerhowl** [comment]
when your ghoul is already summoned and you mount up, the raise dead spell starts its cooldown as if the pet was unsummoned. IF you press the raise dead spell again(while mounted) when its cooldown finishes, and somehow if your pet dies/ you unsummon it, the spell will gray out. This can happen anywhere, even outside wintergrasp. Here's a video to show what i mean:
https://www.youtube.com/watch?v=pcyEpNCLgKA
