### ISSUE TITLE
Ruins of Ahn'Qiraj (AQ20) Ossirian crystals bugged.

### ISSUE THREAD

**Issue by timbazi** [WoWManiaUK/Redemption#4713]
**Links:**
-

**What is Happening:**
After Ossirian is pulled and the crystals spawn, the crystals can't be interacted with.

**What Should happen:**
The crystals should be clickable.

**Comment by Rushor** [comment]
Will check and fix

**Comment by Rushor** [comment]
all fixed

https://i.imgur.com/rlsQTLY.jpg https://i.imgur.com/imZyj21.jpg https://i.imgur.com/jg5WkvM.jpg https://i.imgur.com/nvxYkIr.jpg

**Comment by Rushor** [comment]
Do Not close before it is on live realms. Next thuesday

**Comment by jeyrella** [comment]
Hmmm.  @Rushor I must be doing something wrong here as the crystals are now not even present.

**Comment by Rushor** [comment]
those are the trigger positions

    { -9188.4404296875f, 1940.2099609375f, 85.6390991210937f, 3.17650008201599f },
    { -9244.41015625f, 1808.97998046875f, 85.6390991210937f, 5.63741016387939f },
    { -9248.41015625f, 1974.82995605469f, 85.6390991210937f, 5.89920997619629f },
    { -9282.080078125f, 1887.33996582031f, 85.6390991210937f, 2.00712990760803f },
    { -9299.73046875f, 1748.44995117187f, 85.6390991210937f, 1.44861996173859f },
    { -9357.8603515625f, 1929.07995605469f, 85.6390991210937f, 1.06465005874634f },
    { -9367.169921875f, 1780.89001464844f, 85.6390991210937f, 1.90241003036499f },
    { -9383.2900390625f, 2012.68005371094f, 85.6511001586914f, 2.93214988708496f },
    { -9406.099609375f, 1862.38000488281f, 85.6390991210937f, 6.2308201789856f },
    { -9407.7197265625f, 1960.2099609375f, 85.6390991210937f, 1.11700999736786f },
    { -9432.400390625f, 1782.53002929687f, 85.6390991210937f, 5.86430978775024f },
    { -9506.1904296875f, 1865.56994628906f, 85.6390991210937f, 4.27606010437012f }

**Comment by Rushor** [comment]
https://classic.wowhead.com/npc=15339/ossirian-the-unscarred

**Comment by Rushor** [comment]
here the first spawn position https://i.imgur.com/C1RpACh.jpg

.go xyz -9188.4404296875f, 1940.2099609375f, 85.6390991210937f

**Comment by jeyrella** [comment]
yes i see them in GM mdoe
![WoWScrnShot_062820_201957](https://user-images.githubusercontent.com/46089380/85956335-11dd7c80-b97d-11ea-925c-7fdf7fc6b093.jpg)
but not when actually engaged with him
![WoWScrnShot_062820_202128](https://user-images.githubusercontent.com/46089380/85956330-10ac4f80-b97d-11ea-861d-1b5f4cfe8423.jpg)
I must be doing something wrong here

**Comment by Rushor** [comment]
Pn me tomorrow then we check together on ptr :)
