### ISSUE TITLE
[Quest][Classic] The Annals of Darrowshire - Missing mechanic

### ISSUE THREAD

**Issue by Rushor** [WoWManiaUK/Redemption#4714]
**Links:**
**What is Happening:**
https://www.wowhead.com/quest=5154/the-annals-of-darrowshire
https://www.wowhead.com/npc=10943/decrepit-guardian#comments

"The trick with this quest is to carefully examine the books on the floor. "Trapped" tomes that spawn guards have a clear white/gray split on their pages, whereas the real thing has a smooth transition from white to gray. This may only become apparent if you zoom in and highlight a book, but it's worth it to avoid unneccessary fights."

This is missing.

**What Should happen:**
- All white/gray split ones should spawn a monster
- The only working smooth looking book should contain the item (.go object 45467)

fix: https://i.imgur.com/xDIb2F2.jpg

**Comment by Zanguin-ManiaTester** [comment]
https://www.youtube.com/watch?v=SY8t8QmbYXk&feature=youtu.be

Fix confimed; Every book now spawns guards except the correct one, thanks!
