### ISSUE TITLE
[Quest][Classic] Jonespyre's Request - Missing condition

### ISSUE THREAD

**Issue by Rushor** [WoWManiaUK/Redemption#4715]
**Links:**
**What is Happening:**
https://www.wowhead.com/quest=3787/jonespyres-request
https://www.wowhead.com/quest=3787/jonespyres-request#comments:id=891324
Currently this quest has no condition.

**What Should happen:**
By AudreyChandler (22,754 –  5·24·130)  on 2009/11/15 (Patch 3.2.2) |   |  
This quest is unavailable until you complete Morrowgrain Research at the Cenarion Enclave in Darnassus.

https://www.wowhead.com/quest=3785/morrowgrain-research

**Comment by Zanguin-ManiaTester** [comment]
https://youtu.be/Xj9g6W59OGs

![WoWScrnShot_062820_181212](https://user-images.githubusercontent.com/47272908/85952754-ce2e4700-b96b-11ea-85ce-0307110d48d4.jpg)

Fix confirmed. Video was cut a bit short by accident, hence the screenshot.
