### ISSUE TITLE
[NPC] Bonestripper Vulture Issue with Abilities and Aggro.

### ISSUE THREAD

**Issue by SiranGaming** [WoWManiaUK/Redemption#4717]
**Links:**
![WoWScrnShot_062820_174127](https://user-images.githubusercontent.com/67561770/85958920-68d85700-b967-11ea-8bdc-fc8fbff20fa6.jpg)
https://www.wowhead.com/spell=33985/use-corpse#used-by-npc

**What is Happening:**
Bonestripper Vulture wanders aimlessly after killing another one beside them keeping aggro and not coming close to the PC even with a ranged attack is thrown. They will continue to wander despite being aggro'ed until approached with melee attacks.
(Side Note: It's hard to capture it in screenshots but a GM had tested it and advised me to post here.)

**What Should happen:**
Bonestripper Vulture should be using an ability called Use Corpse or Cannibalize to recover health slightly during the fight instead of wandering aimlessly.

**Comment by Rushor** [comment]
Thanks gonna check

**Comment by Rushor** [comment]
npc=16973

**Comment by Rushor** [comment]
the event that they move to the closest corpse is correct, but i added that they will now attack the closest player once they reached the corpse

**Comment by jeyrella** [comment]
Still needs work.  After using the ability, the buzzard now wanders off with partial health and stops combat, but leaves player in combat.

**Comment by Rushor** [comment]
okay then we will remove those rp actions because they create more trouble than beeing useful. problem is that there is no way in the ai to check if creatures to choose is alive or not

**Comment by svijetlo** [comment]
works fine he will inage and fight you till bitter end , not more wondering off or leaving combat

**Comment by Rushor** [comment]
is on live already, so we can close :)
