### ISSUE TITLE
[Raid] Door doesn't open in Upper Blackrock Spire dungeon

### ISSUE THREAD

**Issue by Elthelune** [WoWManiaUK/Redemption#4718]
What should happen:
After defeating Warchief Rend Blackhand, the small door is supposed to open. After going through the small door, there's another one to the left that's also supposed to open. 

What actually happened:
When I went through this dungeon, neither of them opened - which prevented me from going to the last boss and completing my quest.

**Comment by Rushor** [comment]
i can confirm that

**Comment by svijetlo** [comment]
it happens if you kill boss fast for like all gear ppl , you must let boss attack you for a bit ,
just make doors open if boss is killed fast

**Comment by Rushor** [comment]
Alright will add that

**Comment by Rushor** [comment]
try now pls

**Comment by svijetlo** [comment]
works fine doors will open even if you smakc it in sec

**Comment by Oganku** [comment]
Pretty sure that boss has capped damage taken per hit (or used to). It would take nearly a minute to kill him with multiple 80s even though he has like 50k hp.

**Comment by Elthelune** [comment]
I haven't entered the dungeon since I posted this issue, but I can confirm that it took me a few minutes to kill him. No matter how much I tried to damage him, he wouldn't take any more than a few hundred damage per hit. I don't know if this helps?

**Comment by Elthelune** [comment]
I haven't entered the dungeon since I posted this, but I can confirm that it took me a few minutes to kill him. No matter how much I tried to damage him, he wouldn't take any more than a few hundred damage per hit. So either he has a cap, or I'm just terrible at dps. xD

**Comment by Rushor** [comment]
nah, that is added in the script, that he will not take that much damage. anyway, the door shiuld still open always now

**Comment by Elthelune** [comment]
Thank you :D

**Comment by Rushor** [comment]
With the next update of course

**Comment by jeyrella** [comment]
Reoccuring regression.  see #5308 / #5311

**Comment by Rushor** [comment]
@Keader you can take that aswell if you wish

**Comment by Keader** [comment]
i cant reproduce, i mean, to me door is openning

**Comment by svijetlo** [comment]
this is strange one i seen doors do not open then next run it open , i would like to see how and where ppl fight boss to be sure is there some criteria of this , i did try it today few times and could not reproduce , meaning doors did open in normal way after i would kill dragon then boss

**Comment by Rushor** [comment]
Well then close until clear reproduce. A Video from the Player would be good. I think it only happens a few times? Not Sure. But we need reproduction in this case, really

**Comment by GMMetaxa** [comment]
Read game mechanics.
