### ISSUE TITLE
[Talent/Druid] Owlkin Frenzy

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#4719]
**Links:** https://www.wow-mania.com/armory/?search=Owlkin+Frenzy
https://wowwiki.fandom.com/wiki/Owlkin_Frenzy
https://wow.gamepedia.com/Owlkin_Frenzy#cite_note-1
https://www.mmo-champion.com/threads/852521-Owlkin-Frenzy-PVE

**What is Happening:** Owlkin Frenzy does not proc from all damage types as it should, it seems the revert to the change in 3.1 isn't on Redemption. It did not proc once during multiple PP fights with 2 points into it. Considering the plague and abom debuff are constantly ticking on the whole raid, it should proc at least a few times here and there.

**What Should happen:** 

![image](https://user-images.githubusercontent.com/34783736/86203335-c10f8480-bb32-11ea-88d9-7f90396bb7ca.png)

Sources above show this talent should proc from ANY damage source, including aoe damage in raid bosses. Furthermore, the comments from the mmo-champion thread indicate it should proc fairly often during raids on fights such as professor putricide. These comments are from 2011, which was during 3.3.5a, which indicates that the change was really reverted.

**Comment by Keader** [comment]
Is not "any type of aoe", only the ones that appy direct damage.
Anyway... fixed.
