### ISSUE TITLE
[Quest] Orabus the Helmsman not appearing.

### ISSUE THREAD

**Issue by Frejavestergaard** [WoWManiaUK/Redemption#4720]
http://www.wow-mania.com/armory?quest=11661

What is happening: Orabus isn't spawning when using the quest item.

What should happen: Orabus should spawn when using the quest item as shown here:
https://www.youtube.com/watch?v=eGsEu1rPcOU

**Comment by wow-mania** [comment]
Pretty sure it works. 
Can someone check this on ptr, please?

**Comment by Zanguin-ManiaTester** [comment]
on it, hang on 2 min

**Comment by Zanguin-ManiaTester** [comment]
https://youtu.be/m3z-UaTYmMc

Confirmed not working. No ship has appeared, not even after all the time spent uploading this video and comment.

**Comment by Zanguin-ManiaTester** [comment]
Got some more intel on the bug, hang on;: uploading video

**Comment by Zanguin-ManiaTester** [comment]
https://youtu.be/KaREus1xUhk

ship spawns, sinks with no NPC's present.

**Comment by jeyrella** [comment]
I would be tempted to say this is regression of some kind since I have completed this fine on 2 toons on live.

**Comment by Rushor** [comment]
the whole event must be scripted from scratch i think - all the movement and spawns were missing since today

**Comment by Rushor** [comment]
whole event fixed with all details https://i.imgur.com/V4NrkwF.jpg

small thing: creatures are stacked visualla once boat reaches the final path, but that is only tiny cosmetic detail, that can be ignored.

**Comment by Zanguin-ManiaTester** [comment]
https://youtu.be/K9SkyhRgE_4

Fix confirmed : Quest is functional now, thanks!
