### ISSUE TITLE
[Quest]Springing the Trap quest not completing.

### ISSUE THREAD

**Issue by immba** [WoWManiaUK/Redemption#4721]
https://www.wow-mania.com/armory/?quest=11969

What is Happening: Keristraszas has monologue with Malygos and flies you somewhere.

What Should happen: Keristraszas should fly you and have a meet with Malygos or a small fight not sure.
Shown here: https://www.youtube.com/watch?v=n_fVmqFpG1o

**Comment by Rushor** [comment]
If a Tester confirms i can fix it

**Comment by Oganku** [comment]
This quest chain works, might be some specific condition that fails to award credit. Make sure you don't turn it in to the npc spawned by the prison though.

**Comment by Rushor** [comment]
fixed, was related to the duplicate event_scripts

**Comment by svijetlo** [comment]
you get to spot , use item , wait for dragon lady , she comes burns some other npc fly you around drops you off , and quest will be completed i would call it fine as long you get quest completed
