### ISSUE TITLE
Zul'Gurub 

### ISSUE THREAD

**Issue by Alansaal2** [WoWManiaUK/Redemption#4722]
**Links: https://www.wow-mania.com/armory/?item=19902 **

**What is Happening: The npc that is supposed to transform into a bigger tiger after bringing the zealots to 5% at the same tiem never happens, so we cannot get the mount.**

**What Should happen: Zealots die, priest transforms into a tiger and drops mount.**

**Comment by Oganku** [comment]
The mechanics of the fight are a little wonky, but the mount can still drops regardless of whether the guy transforms or not.

**Comment by Rushor** [comment]
the mechanic must be indeed updated, since the transform does not happen always and the resurrection is also malformed often

**Comment by Rushor** [comment]
the adds will now be respawned pericically again https://i.imgur.com/ORvnlWG.jpg

if you kill the boss the first time then with all adds down, he will transform to the cat https://i.imgur.com/tGGEZOm.jpg https://i.imgur.com/KLCq47b.jpg

the best solution we can do so far

**Comment by Alansaal2** [comment]
Ill try to get the mount next week then and ill give you update as player perspective thanks

**Comment by svijetlo** [comment]
you can still get mount i got it on 2 toons

**Comment by svijetlo** [comment]
funny enough i got mount while testing it XD

**Comment by Rushor** [comment]
lol, okay the boss mechanic should be all fine now. keep in mind to kill the adds and boss at same time. else they will always restart respawning

**Comment by svijetlo** [comment]
ye ye seen it if you kill boss not adds boss will come back if you do adds not boss adds will come back
