### ISSUE TITLE
Soul power FOS

### ISSUE THREAD

**Issue by Alansaal2** [WoWManiaUK/Redemption#4723]
**Links https://www.wowhead.com/achievement=4522/soul-power:**

**What is Happening: Boss fight: he will spawn a soul fragment that neeed to be kited around the area for a total number of 4 simulaneous souls trying to reach the boss, "tecnically" the souls are absorbed when they reach the boss, in this case they dont, they get absorbed like 8 yards away.**

**What Should happen:Boss casts 4 times the souls, we kite them around room, snare them outside of the room and nuke on soulstorm phase and achiv complete.**

**Comment by Keader** [comment]
test now.
it should consume soul only when it realy reach the boss.

**Comment by Alansaal2** [comment]
yes, apparently does at around 5 to 8 yards, we tried 2 times but priest mana couldnt keep up

**Comment by Alansaal2** [comment]
Will do.

**Comment by Keader** [comment]
remember: test now in ptr hehe
will be in live in some days

**Comment by svijetlo** [comment]
will now be absorbed only if they reach boss
