### ISSUE TITLE
[Spell/Druid] Living seed

### ISSUE THREAD

**Issue by Keader** [WoWManiaUK/Redemption#4725]
Living seed is a druid talent, that make you critical heals, add a seed in a target, that heals him when he take damage

**What is Happening:** 

Issue 1 - Wrong caster is appearing in combat log / recount when living seed procs. Heal is added in target recount, instead of caster recount.

Issue 2 - Druids talents is ignored and it's taking account target talents instead.

**What Should happen:**

Druid should get heal in his recount, instead target get it.
Druids talents should be checked in cast, instead target talents.

Showcase: https://drive.google.com/file/d/1tZyclEyS6tXN1exlSLQOyUApV2OfHjWV/view?usp=sharing

**Comment by svijetlo** [comment]
yeeee living seed is  kinda viable to use :D
