### ISSUE TITLE
[Player] Odd behavior of the Inspect option

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#4726]
**Links:**

**What is Happening:** When you inspect a player, you can see their gear and talents normally. However if you happen to simply mouse over another player that is within inspect range while the inspect window is still open, it will query info from that other player and you will see that other player's talents while still having the first one's frame, and still having him targeted. 

Also, if you're only looking at gear, mousing over someone else will cause you to be unable to see any equipment details from the original target, until he is re-inspected.

You can see it easily by moving your mouse across a bunch of different players after having inspected someone.

It happens often during raids since after opening the inspect window, you will often mouse over other players while moving your mouse to the window to see talents and item details.

**What Should happen:** Once a player is inspected, that player's information should "stick" to the inspect window unless the player specifically inspects a different one. Simply mousing over someone else should not cause it to act weird.

**Comment by jeyrella** [comment]
I'm not seeing this issue.  Perhaps I'm misunderstanding.  Please take a video?

**Comment by Oganku** [comment]
You're right, seems to be caused by an addon, although I'm not sure why. Ignore this
