### ISSUE TITLE
[Quest] Felwood corrupted flowers

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#4728]
**Links:** https://classic.wowhead.com/object=164886/corrupted-songflower#comments
https://classic.wowhead.com/object=164882/cleansed-songflower#comments
https://classic.wowhead.com/item=11516/cenarion-plant-salve
https://wowwiki.fandom.com/wiki/Useful_zone-specific_buffs

**What is Happening:** You can properly get the [Cenarion Plant Salves](https://classic.wowhead.com/item=11516/cenarion-plant-salve) from the corresponding quests, but once you use them on a corrupted flower of any kind located in Felwood (eg: [Corrupted Songflowers](https://classic.wowhead.com/object=164886/corrupted-songflower#comments)), they do not transform into their [cleansed couter-parts](https://classic.wowhead.com/object=164882/cleansed-songflower#comments), which should be interactable with in order to obtain their corresponding buff. 

**What Should happen:** Once you complete the quest from any of the corrupted flowers in Felwood, the 'quest-giving flower' should de-spawn, and an interactable cleansed version should spawn in its place, granting a buff and containing various items.

The songflower directly grants its buff and contains items from its loot-table listed [here](https://classic.wowhead.com/object=164882/cleansed-songflower#contains). The other flowers will contain a few consumable items listed in the table below:
![image](https://user-images.githubusercontent.com/34783736/86526201-d4865c80-be5e-11ea-84cb-7e8a864b7508.png)

**Comment by Rushor** [comment]
Will fix that

**Comment by Zanguin-ManiaTester** [comment]
https://youtu.be/q5BI9HbaqQg

**Comment by Rushor** [comment]
fully fixed all

**Comment by Zanguin-ManiaTester** [comment]
https://youtu.be/rGgcrnxXjRE

Regression. Invalid target when interacting with cleansed songflower. Flower despawns without providing any buff or items. If a player is shapeshifted, it does nothing either, but give a message about not being able to do it while shapeshifted and then despawns

This is both improvement and regression I suppose?

**Comment by Rushor** [comment]
no if you are under level 60 it should not work as said in wowhead comments. that already worked fine and was not fixed here.

i only fixed the spawn of the flower

**Comment by Zanguin-ManiaTester** [comment]
Test char is not under level 60.

**Comment by Rushor** [comment]
oh i see - it is disabled for chars above level 63 (fixed my comment, sorry for that)
