### ISSUE TITLE
[Spell/Paladin] Sacred Shield

### ISSUE THREAD

**Issue by Keader** [WoWManiaUK/Redemption#4731]
**What is Happening:** Sacred shield has some issues.

Issue 1 - When paladin use in a target (not self) T8 bonus was not applied (cooldown stuff)
Issue 2 - Wrong proc flags.
In DBC, sacred shield has flags:

![image](https://user-images.githubusercontent.com/7120913/86534019-b266fb80-beab-11ea-96cd-b4e6db3150fa.png)

But in our old code, has:

![image](https://user-images.githubusercontent.com/7120913/86534034-c01c8100-beab-11ea-9f47-045b1145ce76.png)

It make sacred shield only proc with physical damage, and not with spells.

Issue 3 - Wrong caster. Old script was using target as "caster".
It make sacred shield absorb amount use target status instead paladin status.

**What Should happen:**

1 - T8 bonus should be always applied
2 - Sacred shield should proc with melee and spell hits
3 - We should always use Paladin status, not target status.

**Comment by svijetlo** [comment]
nice job =) i know smt was wrong with this one but never could bother to check it in depth
