### ISSUE TITLE
[Quest] Making Sense of It - Fix Endevent

### ISSUE THREAD

**Issue by Rushor** [WoWManiaUK/Redemption#4732]
**Links:**
https://youtu.be/fMbEZGBjE98?t=24
quest=4321
**What is Happening:**
The questevent currently is wrong. the object at the end is not spawned. And the event happens on quest accept, while it should happen on quest reward, as can be seen in the vide.

**What Should happen:**
The questevent currently is wrong. the object at the end is not spawned. And the event happens on quest accept, while it should happen on quest reward, as can be seen in the vide.

**Comment by jeyrella** [comment]
Ooooh.  Interesting.  I always thought this one was a bit odd but could never remember/work out what it was :)

**Comment by jeyrella** [comment]
Great :) 
https://youtu.be/M0rs4V2uOso
