### ISSUE TITLE
BQL stuck at 1hp on air phase

### ISSUE THREAD

**Issue by bLeyaa** [WoWManiaUK/Redemption#4733]
**Links:** https://clips.twitch.tv/RudeSmoothLardPoooound

**What is Happening:** If BQL is pushed into air phase while dying she remains at 1hp and continues casting her abilities

**What Should happen:** Boss should die and drop dead once her hp reaches 0

I don't know if this is intentional due to possibility of her remaining stuck in air after dying (seen it elsewhere), disregard if that's the case.

**Comment by svijetlo** [comment]
i know she will be in air till air phase is over even if it is ¸1hp left , and i do think that was do cos some time ago if you kill her in air she would stuck up there and you need to send ticket for loot , 
think this was workaround will let some of devs check and support me  or disagree if that is case

**Comment by Keader** [comment]
Was a old protection, maybe to prevent his stuck in the air.
I removed this protection, and make she fall to the ground when die.
Test now in PTR please @svijetlo

**Comment by svijetlo** [comment]
if killed in air she will drop down to ground where you can loot her , works in 10/25 nm and 10/25 hc
