### ISSUE TITLE
Wicked Spirits (Frostmourne) evading attacks

### ISSUE THREAD

**Issue by bLeyaa** [WoWManiaUK/Redemption#4734]
**Links:** https://clips.twitch.tv/RefinedVainReubenStoneLightning

**What is Happening:** Wicked Spirits will sometimes evade attacks for unknown reason

**What Should happen:** Wicked Spirits should not be evading attacks

I've had this happen since a long time ago, just never had it on video. No idea what could be causing it, as initially i thought they might "reset" after the person they were after dies or something... but nobody died in frostmourne for that to be the case

**Comment by Keader** [comment]
try now pls

**Comment by Aristo14** [comment]
please close when confirmed ;) thanks

**Comment by wow-mania** [comment]
I can't wait for this.
It has been fixed 3 days ago and it's on live already. If not working just re-open and mark as regression.

**Comment by svijetlo** [comment]
i reopend it as i just don it it works fine did it on hunter and boomy non evaded

**Comment by Keader** [comment]
wait, what?
