### ISSUE TITLE
[Item] Potions on cooldown before LK actually got engaged

### ISSUE THREAD

**Issue by bLeyaa** [WoWManiaUK/Redemption#4735]
**Links:** https://clips.twitch.tv/AdventurousPeacefulBisonCurseLit (bottom right, use traps/feign death for orientation on the bars)

**What is Happening:** Potions go on cooldown as if the fight is engaged

**What Should happen:** Potions or anything with a similar effect (if there is such) should not be on cooldown until LK actually becomes attackable. Role play should not count towards getting into combat

**Comment by Rushor** [comment]
will check that once tester confirmed it

**Comment by svijetlo** [comment]
yes i can confirm this as soon you talk to npc to start LK role play it will count potion of speed or any other pot as if you used it in combat . what should be is that role play is not combat it self but one NPC say "So be it , champions attack"  then combat start , so this way it stops ppl form prepoting and poring out max they can

**Comment by jeyrella** [comment]
Well we know it is current behaviour.  But this is not proof of a problem.
We need to research / have reference posted that are era-relevant that show this was possible in retail (i.e. that combat had not started at that point yet).  Sounds obvious, but as always, we should keep status quo until we can prove definitively that it is incorrect.

**Comment by svijetlo** [comment]
watch paragon Lk kill vids and guides for class , all prepot and use pot 2nd time in fight when it is sticky situation and you need bit more bit more output

**Comment by bLeyaa** [comment]
https://youtu.be/NUDbNDACFEo

**Comment by jeyrella** [comment]
thanks @bLeyaa 

Confirmed Improvement.

(For those looking, specifically https://youtu.be/NUDbNDACFEo?t=38 , watch the potion count/cd above the player frame in bottom middle of screen.  Clearly has a 60 second cd when used ass he shouts "Champions, attack!")

**Comment by svijetlo** [comment]
told you so ;)

**Comment by Keader** [comment]
yes, combat just start when LK become attackable.
during the intro shits, you can use whatever you want

**Comment by svijetlo** [comment]
as i told best example is deathbringer fight

**Comment by Rushor** [comment]
okay state of encounter get's riggered once he is attackable now

**Comment by svijetlo** [comment]
use any potion like potion of speed before high-lord get frozen in ice tomb and you will be able to use 2nd one in 60 sec
