### ISSUE TITLE
Halls of reflexion Bug

### ISSUE THREAD

**Issue by Alansaal2** [WoWManiaUK/Redemption#4737]
**Links:**

**What is Happening: At the end of the wave 9/10 last npc clipped the floor and reset the instance, both doors closed and no npc to talk to.
![WoWScrnShot_070720_183405](https://user-images.githubusercontent.com/67749805/86813566-9ff1eb00-c080-11ea-9db4-8c1c5757bc84.jpg)
**

**What Should happen:**

**Comment by Rushor** [comment]
Ehh which creature Was that? What nams

**Comment by bLeyaa** [comment]
Here we go again... GL with finding what it really is @Alansaal2

**Comment by wow-mania** [comment]
without repro steps there isn't much we can do.

**Comment by Rushor** [comment]
if you tell me the npc name / id i can fix it

**Comment by Alansaal2** [comment]
Sorry, the npc was a https://www.wowhead.com/npc=38175/ghostly-priest
wave 9/10 sorry for the late answer

**Comment by Rushor** [comment]
if they drop below the texture, they reappear on the floor again, Thanks to Keader

**Comment by Alansaal2** [comment]
Thanks man

**Comment by svijetlo** [comment]
i spent some time there last night as i could not sleep , i could not make any of them fall trou ground or so XD

**Comment by Rushor** [comment]
perfect!
