### ISSUE TITLE
NPC missing "Silver Covenant Guardian Mage"

### ISSUE THREAD

**Issue by Desmock992** [WoWManiaUK/Redemption#4738]
Doing the quest "The Silver Covanant Scheme" I found a bug.

The NPC called "Silver Covenant Guardian Mage" isn't in the right position.
I can target him but not able to see it.
![InkedWoWScrnShot_070820_141237_LI](https://user-images.githubusercontent.com/67071675/86917925-36c4b300-c126-11ea-89f2-f82033981781.jpg)

Do you have any solution for this issue?

Regards
Desmock

**Comment by Oganku** [comment]
The NPC is actually right above you (that's why you're close enough to target him). He's not located in the sewers. Those guardian mages are the ones guarding the entrance to the alliance section in dalaran.

**Comment by Desmock992** [comment]
> The NPC is actually right above you (that's why you're close enough to target him). He's not located in the sewers. Those guardian mages are the ones guarding the entrance to the alliance section in dalaran.

Thx for the suggestion, but still no NPC in sewers even after retake the quest and cache reset

**Comment by Oganku** [comment]
The NPC isn't in the sewers... There's no big and he's outside above. I didn't mention relogging or clearing cache either.

The NPC is there and at the right place, but you aren't. 

They are above ground, at the entrance to the alliance section of dalaran. The 2 screenshots below show where they are. 
![Screenshot_20200708-104823](https://user-images.githubusercontent.com/34783736/86933583-b04da880-c108-11ea-8188-8d52b8634a23.png)
![Screenshot_20200708-104835](https://user-images.githubusercontent.com/34783736/86933587-b0e63f00-c108-11ea-9f39-f47801a1b665.png)
