### ISSUE TITLE
Karazhan Opera ewent loot

### ISSUE THREAD

**Issue by Zabpl** [WoWManiaUK/Redemption#4739]
There is a problem with Karazan opera ewent loot. Ewery bos in krazan drops 2 items per kill, but opera drops only one and it is always from shared loot. Items wich should drop depend of wich bos u kill dont drop at all.

**Comment by wow-mania** [comment]
Unless you send the info on which npc and also some evidence on the loot that confirms that it is wrong we cannot do anything.

**Comment by Zabpl** [comment]
ok here is some screns for confirmation, loot from Moroes to konfirm that Karazhan bos shuld drop 2 items and loot from opera ewent romeo and juliet fight wich drop only 1 item from shared loot and dont drop second (bos depend) item
![WoWScrnShot_071920_145515](https://user-images.githubusercontent.com/68014491/87875621-cf82ea80-c9d2-11ea-8b2b-e26da054d352.jpg)
![WoWScrnShot_071920_150515](https://user-images.githubusercontent.com/68014491/87875622-d0b41780-c9d2-11ea-9fff-e8ae22bc60f3.jpg)
![WoWScrnShot_071920_150524](https://user-images.githubusercontent.com/68014491/87875623-d1e54480-c9d2-11ea-900a-c98e924d45c5.jpg)

**Comment by Zabpl** [comment]
I’ve posted some screnshots to this topic Wysłane z aplikacji Poczta dla Windows 10 Od: JanitorWysłano: środa, 8 lipca 2020 16:19Do: WoWManiaUK/RedemptionDW: Zabpl; AuthorTemat: Re: [WoWManiaUK/Redemption] Karazhan Opera ewent loot (#4739) Unless you send the info on which npc and also some evidence on the loot that confirms that it is wrong we cannot do anything.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.  
	
      
		Wolny od wirusów. www.avast.com

**Comment by Rushor** [comment]
Will Fix that

**Comment by Rushor** [comment]
some proof that two items should drop https://youtu.be/b4IWLpy_13M?t=600

**Comment by Rushor** [comment]
okay for now we can only add from shared loot 2 items to improve the situation. added that for the involved npcs.

https://i.imgur.com/95qPr7o.jpg

**Comment by svijetlo** [comment]
![WoWScrnShot_072120_095552](https://user-images.githubusercontent.com/61908373/88028050-69b07300-cb38-11ea-8e15-f4cf24f7ec59.jpg)

**Comment by svijetlo** [comment]
![WoWScrnShot_072120_095715](https://user-images.githubusercontent.com/61908373/88028173-982e4e00-cb38-11ea-8bf7-b5ddba140d2a.jpg)
