### ISSUE TITLE
[Gob] Ogre Tannin Basket

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#4740]
**Links:** https://wow-mania.com/armory/?object=179499
https://wow-mania.com/armory/?item=18240

**What is Happening:** O[gre Tannin Basket](https://wow-mania.com/armory/?object=179499) isn't dropping the [Ogre Tannin](https://wow-mania.com/armory/?item=18240) every time it is looted. I had to do 5 runs before getting a single drop.

**What Should happen:** The basket should always contain 1 [Ogre Tannin](https://wow-mania.com/armory/?item=18240). 
![image](https://user-images.githubusercontent.com/34783736/86991178-6b5b5d80-c16c-11ea-817c-4a44b8aec08b.png)

**Comment by Rushor** [comment]
Why Do you closed it? :o
