### ISSUE TITLE
[Quest] Fortunate Misunderstanding, Sholazar Basin 12570

### ISSUE THREAD

**Issue by theonykry** [WoWManiaUK/Redemption#4741]
**Links:**
http://www.wow-mania.com/armory?quest=12570

**What is Happening:** while completing the quest, i followed the NPC, i never lost LoS and when we were at the camp he turned into the water and walked through the bottom of the map and just "dissapeared", leaving me with an unfinished quest and i cant hand it in. this all happend close to 2 mobs fighting ( 1 from oracle 1 from frenzyheart tribe, a hunter) 

**What Should happen:** i guess the NPC should move to a slightly diffrent position, maybe closer to the NPC where you can hand it in in the end and not dissapear through the ground :D

**Comment by jeyrella** [comment]
reference video for testing later https://www.youtube.com/watch?v=thWnpu77E8M

**Comment by Rushor** [comment]
Will check if confirmed :)

**Comment by jeyrella** [comment]
Hmmm.  I tried this 4 times and I couldn't replicate.  Worked every time.  https://youtu.be/v47gfFXfS94

@theonykry There are multiple Oracles that can be rescued, do you remember which one you chose?

**Comment by theonykry** [comment]
yes i do i could show you ingame, it was the one closest to the frenzyhearth camp. also it took a completly diffrent path than shown in your reference vid.

**Comment by jeyrella** [comment]
can you give coordinates of the one you chose pls.  or screenshot / ping me them on Discord.  Thanks :)

**Comment by jeyrella** [comment]
theonykry: this the one. 54,00 / 64,5

Again seems to work just fine under testing.  (Although admittedly the path up the side of the cliff is a bit odd but doesn't break it)
https://youtu.be/1HFTyaNfaBY

**Comment by theonykry** [comment]
unfortunatly i did not record what actually happend and my description of it is not 100% perfect, but maybe someone else does.

**Comment by jeyrella** [comment]
Sorry kry.  Until we get some more evidence I have to mark this as unreproducible.

**Comment by GMZinius** [comment]
We have a reproduce of this one from GM remmy 
there are a 2-3 oracle npcs that do fall through the terrain/or despawn 

@Rushor I will be reopening this one

**Comment by GMZinius** [comment]
Test noticed so far 

- GPS of 1st bugged one 
![image](https://github.com/WoWManiaUK/Redemption/assets/108176634/6fa2e9b0-4258-4c41-971a-ef62df28fb46)

- Unsure why these are all grouped together, shouldnt be this way 

GPS of grouped ones
![image](https://github.com/WoWManiaUK/Redemption/assets/108176634/72fd5557-8935-4ef2-b0a8-159ec3876480)
 ![image](https://github.com/WoWManiaUK/Redemption/assets/108176634/824bbc4e-dd06-463a-98b9-2db382ac01fe)

Map Location via wowhead https://www.wowhead.com/wotlk/npc=28217/injured-rainspeaker-oracle
Map Location via Mania https://www.wow-mania.com/armory/?npc=28217

- We have 6 spawns, but only a few actually work correctly 
![image](https://github.com/WoWManiaUK/Redemption/assets/108176634/d21cce88-caec-4cf7-b9f1-f3b4688340c2)

**Comment by GMZinius** [comment]
Unfortunately there is no easy fix for this one ATM.

- Quest bugs only if player does'nt click on the gossip first 


`players must click the gossip first before accepting the quest. `
Thank you

**Comment by Rushor** [comment]
Full gossip fix applied, gossips will be applied in correct order now (make sure to remove quest 12540 and 12570 again before testing) 
Only taking 12540 quest and then all is good

**Comment by GMZinius** [comment]
Great fix @Rushor ❤️ 

https://i.gyazo.com/b6cd60230c1b6ab20c81c00bcfa6fe54.mp4
https://i.gyazo.com/c1a60631c8814c22741a7afbbf6e6d0b.mp4

![image](https://github.com/WoWManiaUK/Redemption/assets/108176634/db24bcde-fd58-45a8-83f6-2d3c930ecf2a)
![image](https://github.com/WoWManiaUK/Redemption/assets/108176634/93ce4a2d-0353-4dcb-bceb-68960cc90852)
![image](https://github.com/WoWManiaUK/Redemption/assets/108176634/13d33faf-a3ef-4b6b-995a-3ab7324d58f0)
