### ISSUE TITLE
[Quest] Ras the Human - Scholomance - 5466

### ISSUE THREAD

**Issue by Sierbahnn** [WoWManiaUK/Redemption#4742]
**Links:**
While on "The Lich, Ras Frostwhisper" in the Scholomance-chain, I fight my way down to Ras Frostwhisper, and aim my "Soulbound Keepsake" at him. 
The channel triggers, the boss acquires the buff/debuff (something about Gift of life) but does not despawn and get replaced with "Ras the human", so that I can complete the quest.
Ideally, the buff/debuff would apply, the Lich would despawn, the human would spawn, and the mob would aggro. It does not.

https://classic.wowhead.com/quest=5466/the-lich-ras-frostwhisper

**What is Happening:**

**What Should happen:**

**Comment by Zanguin-ManiaTester** [comment]
https://youtu.be/ymRyMeWgGyk

Using the Soulbound Keepsake should turn Ras Frostwhisper into a human, as shown in this video https://www.youtube.com/watch?v=_hhQWZE87os

Confirmed not working.

**Comment by Rushor** [comment]
fix added, creature will transform now once hit by the spell of the item! :)

**Comment by Sierbahnn** [comment]
I just tested it, but I am guessing the fix has not been implemented yet, as it is not working.
I am not familiar with how these things are marked in GitHub, so pardon me if I am missing something.

**Comment by Sierbahnn** [comment]
Oh wait - things just got interesting. The mob did not despawn, nor did the new mob spawn, but the head did drop so that the quest can be completed. 
Was that supposed to happen, rather than have the mob despawn?

**Comment by Rushor** [comment]
The fix is on ptr

**Comment by Zanguin-ManiaTester** [comment]
https://youtu.be/haar68yppmE

Having tried with 2 different chars; 1 horde & 1 alliance, I get the same result: 
 Ras changes to human, but no head drops.

Improvement?

**Comment by Sierbahnn** [comment]
In a way it is.
I mean, I used the effect prior to getting into combat, didn't see any despawn, but got a head. In vanilla this didn't used to be the cast. If you used the item, the mob would aggro, or you had to use the item once combat had started, in order to see the despawn and then get the head. 
The order should be "combat starts, item use, despawn, kill, head", but the way it works currently is "use item, enter combat, kill, head".

**Comment by Rushor** [comment]
okay try again pls

**Comment by Sierbahnn** [comment]
1. You can use the keepsake on him out of combat without him despawning/spawning. 
2. Entering combat and using the item does not despawn /spawn him either.

Now I cannot tell if the head drops or not, since I am not on the quest. I can only test the despawn/spawn.

**Comment by Rushor** [comment]
do you tested that on ptr realm?

**Comment by Sierbahnn** [comment]
I have no access to the ptr, sorry.

**Comment by Zanguin-ManiaTester** [comment]
Still no head dropping on PtR. Doesn't matter if I use the item on Ras from a distance outside combat or using the item after starting combat. He transforms no problem, but no head drops.

**Comment by Rushor** [comment]
okay now it should work https://i.imgur.com/NsZRwGn.jpg https://i.imgur.com/hfoFpHH.jpg

hed will only be given if boss is transformed to human

**Comment by Zanguin-ManiaTester** [comment]
Quest now indeed works as intended: Head drops when Ras is turned human and killed. 
Uploading video to make sure the evidence for this fix is not lost. 

https://youtu.be/5M9swLcqjdw

**Comment by Rushor** [comment]
Goody
