### ISSUE TITLE
[Quest]: Blood Quickening, missing auto-fail

### ISSUE THREAD

**Issue by Zanguin-ManiaTester** [WoWManiaUK/Redemption#4743]
Links:
https://www.wow-mania.com/armory/?quest=24874

What is Happening:
It seems to me, that the ICC weekly quest, is missing a script that should mark the quest as "failed", when the timer runs out.

As it is now, as long as the raid engages Blood Queen before the timer runs out, even if the timer runs out during the encounter, the raid still gets credit for the quest and it is marked as complete.

The NPC however, disappears as soon as timer runs out. This leads to confused and disappointed raid members, with a completed quest in their quest log, but no NPC to turn it by.

What Should happen:
Having had no luck finding anything to support the theory, but what would make the most sense, would be, if the quest auto-fails, when timer runs out.

**Comment by Oganku** [comment]
The first comment on wowhead shows that the current behavior is correct.

> You only have to pull Blood Queen before the timer runs out, it doesn't matter if the timer runs out while you are fighting her.

If you end up taking too long to save him, or wipe after the timer expired midfight, the quest does turn to "failed" already. Leaving open just for someone else to confirm, but there is no incorrect behavior here I'm 99% sure.

**Comment by Zanguin-ManiaTester** [comment]
But in the 10m icc raid I was in, we engaged Blood Queen with 3 mins left. The quest was never marked as failed, the questgiver NPC just disappeared. Ticket was made, the GM who came to help, did not know if it was Blizzlike, neither did Rushor.
So I don't know about this being Blizzlike or not. Certainly is frustrating for players, to have the completed quest in their quest logs with no NPC outside the Blood quarter, to turn it into.

**Comment by Zanguin-ManiaTester** [comment]
Furthermore said comment from wowhead doesn't say anything about wether the quest can still be turned in, after killing her and the timer running out meanwhile.

**Comment by svijetlo** [comment]
as long you ingage her with in 30 mins even if 1 min left after kill you will be able to turn in quest i rember vid of it need to find it

**Comment by Zanguin-ManiaTester** [comment]
I don't doubt that it can be turned in at a later time, in fact a wowhead comment says so, that if you have the completed weekly in your quest log, and that weekly comes around again inside icc one week, you can turn it in when you reach the NPC.

But as for the quest now, the NPC just disappeared and you are left with no questgiver and with sweet disappointment.

**Comment by Rushor** [comment]
Pls tell me what to fix now :)

**Comment by Zanguin-ManiaTester** [comment]
Even if it's not exactly Blizzlike, which to me seems we can't determine, out of convenience and to avoid unnecessesary future tickets, just make the quest auto-fail as soon as the timer runs out :)

**Comment by jeyrella** [comment]
No @Zanguin-ManiaTester the proper behaviour is that, if the quest is complete, NPC should not disappear when the time of the (now redundant) timer runs out.
If this is the case, then this indeed needs fixing.
