### ISSUE TITLE
Launcher Error

### ISSUE THREAD

**Issue by dauzhanyer** [WoWManiaUK/Redemption#4744]
**Links:**
No links

**What is Happening:**
![Capture](https://user-images.githubusercontent.com/36056838/87225571-1f6f0b00-c35c-11ea-9012-ba3cccbe0115.JPG)

**What Should happen:**
Should open the launcher.
This only happens with the wow mania client launcher (one that loads any updates if there are any), and the client that instantly opens the game does not have this issue.

**Comment by jeyrella** [comment]
This is not a server error.
