### ISSUE TITLE
[ICC] Deathbringer Saurfang - Bloodbeasts

### ISSUE THREAD

**Issue by Keader** [WoWManiaUK/Redemption#4749]
**What is Happening:** Npcs summoned during deathbringer encounter.
After summoned, they just attack a random player.

**What Should happen:** After summoned, like Living Inferno (Ruby Sanctum), it should wait 3 secs before engage with a random player.

**Comment by svijetlo** [comment]
damn this makes it so much better to deal with them :D thx
