### ISSUE TITLE
Quest: From Whence They Came - Reduce visual despawn for Containment Crystal from 5 minutes to 30 seconds

### ISSUE THREAD

**Issue by Rushor** [WoWManiaUK/Redemption#4750]
**Links:**
http://www.wowhead.com/quest=13171/from-whence-they-came#comments:id=449536

**What is Happening:**
The current timer is 5 minutes and the animation of the object does not get restored to "alive"

**What Should happen:**
* http://www.wowhead.com/quest=13171/from-whence-they-came#comments:id=449536
* By Scain (2,017 – 1·3·16) on 2008/11/17 (Patch 3.0.3)
They have a respawntime of 30 secs, so just find 2 crystals and run between those 2.

**Comment by jeyrella** [comment]
Fixed 
https://youtu.be/gzxYFmq01KY
