### ISSUE TITLE
NPC: Boulderfist Mage - Add abilities

### ISSUE THREAD

**Issue by Rushor** [WoWManiaUK/Redemption#4751]
**Links:**
https://www.wowhead.com/npc=17137/boulderfist-mage#comments:id=366415

**What is Happening:**
Boulderfist Mage does not cast abilities

**What Should happen:**
Boulderfist Mage should cast abilities

**Comment by Zanguin-ManiaTester** [comment]
https://youtu.be/fGESJLwOODg

Fix confirmed: Boulderfist mages now know how to cast spells, thanks!
