### ISSUE TITLE
Quest: The Divination - Quest Startscript

### ISSUE THREAD

**Issue by Rushor** [WoWManiaUK/Redemption#4752]
**Links:**
https://www.wowhead.com/quest=2992/the-divination#screenshots:id=109001

**What is Happening:**
Nothing

**What Should happen:**
Upon queststart, there should take place a tiny event where "Grimshade's Vision" get's summoned for a short time, and some line shsould be spoken

**Comment by Zanguin-ManiaTester** [comment]
https://youtu.be/Pof5LDQCQtY

Fix confirmed, event now plays at queststart, thanks!
