### ISSUE TITLE
[NPC] Warmaul Chef Bufferlo- Missing event

### ISSUE THREAD

**Issue by Rushor** [WoWManiaUK/Redemption#4753]
**Links:**
https://www.wowhead.com/npc=18440/warmaul-chef-bufferlo#comments:id=568082

**What is Happening:**
Nothing

**What Should happen:**
Every few minutes Warmaul Chef Bufferlo should yell some lines about some nice new recipes of Corki! :D 

By Iilrane (3,167 –  16·39)  on 2009/01/18 (Patch 3.0.3) |   |  
-- | -- | --

—First you need da spices.
—Da salt goes into da pot…
—Den you put da pepper in da pot…
—Now we gonna kick it up a notch wit da secret ingra…ingor…inrag…da secret sauce!
—And last, we put in da Corki!

He may also say "BAM! Look at dat gristle sizzle!".

**Comment by Zanguin-ManiaTester** [comment]
https://youtu.be/U9KXrmNL2-8

Event is missing no more :) Fix confirmed, thanks!
