### ISSUE TITLE
Quest: Gizmo for Warug - Missing outro event

### ISSUE THREAD

**Issue by Rushor** [WoWManiaUK/Redemption#4754]
**Links:**
https://classic.wowhead.com/quest=1371/gizmo-for-warug

**What is Happening:**
nothing

**What Should happen:**
once quest is completed, there should happen a tiny event with Warug, "attacking" a 'Warug's Target Dummy'

**Comment by Zanguin-ManiaTester** [comment]
https://youtu.be/P--Gbn8efW0

Fix confirmed, thanks!
