### ISSUE TITLE
[Raid/Event] Zul'Aman Timed Event

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#4755]
**Links:** https://wowwiki.fandom.com/wiki/Zul%27Aman_timed_event
https://wow.gamepedia.com/Zul%27Aman_timed_event#:~:text=The%20subject%20of%20this%20article,of%20Warcraft%20in%20patch%204.1.
https://wow.gamepedia.com/Zul%27Aman_(removed)
https://github.com/TrinityCore/TrinityCore/issues/8966

**What is Happening:** The timed event simply doesn't happen right now. The timer at the top of the screen doesn't appear, and even if you save the hostages within the time limits, the chests are un-lootable.

**What Should happen:**  

> Enter the instance and talk to Harrison Jones to start the event and open the doors. You will now have 20 minutes to defeat the first animal-boss of your choice. Any of the loa spirit bosses will do and there is no required order, but two of them will add extra time to the timer.
Killing Nalorakk (bear) will add 15 minutes to your timer.
Killing Akil'zon (eagle) will add 10 minutes to your timer.
Other bosses will not grant additional time.
Therefore you have exactly 45 minutes to kill the first four bosses

A timer should appear at the top of your screen indicating the amount of time left, similar to the [[Blood Quickening]](https://www.wowhead.com/quest=24879/blood-quickening) quest timer. 

The main reward from the timed event, which is the Amani War Bear, has been removed from the loot table with 3.0.2 and should not be available, but the other extra loot shown below should be obtainable, and it currently isn't:

> The loot from the event is dependent on the number of hostages you rescue. All loot is from the Zul'Aman timed event loot table (see below).
First hostage will give a random piece of armor (iLvl 128).
Second hostage will give a random weapon (iLvl 132).
Third hostage will give a random ring (iLvl 141).
Fourth hostage will give a random ring (iLvl 141).

**Comment by jeyrella** [comment]
Confirmed.  Timer doesn't start, event doesn't register.   Chests unlootable.

**Comment by Keader** [comment]
what?
Timer is there: 
![image](https://user-images.githubusercontent.com/7120913/87883967-6191ef80-c9e1-11ea-84f0-00b50a13def7.png)

**Comment by Keader** [comment]
Fixed in Dev.
You can loot the chest now.

**Comment by jeyrella** [comment]
Chests now lootable.  (Timer also appears.... so.... dunno what was with that.)
