### ISSUE TITLE
[QUEST] Get the  scoop

### ISSUE THREAD

**Issue by gamer100** [WoWManiaUK/Redemption#4756]
https://www.wow-mania.com/armory/?quest=1950
https://www.wow-mania.com/armory/?npc=6626
https://www.wow-mania.com/armory/?npc=6666

Quest Get the scoop is not  working. You need to talk  to npc "Plucky" Johnson but the npc  is not interacting. When  you  speak  to him he need to transform to the  human  form and complete the  quest. This is  not happening
![image](https://user-images.githubusercontent.com/33811022/87236230-b2ed1e00-c3e6-11ea-8434-76e84f9e5412.png)

https://www.youtube.com/watch?reload=9&v=5gFzA3p40vg

**Comment by Rushor** [comment]
it works you need to do textemote on him:

/beckon

as seen in the video here aswlel https://www.youtube.com/watch?v=m1DfQKsWM3E Then he will transform and move to you.

https://www.youtube.com/watch?v=m1DfQKsWM3E https://i.imgur.com/Ag3eSV9.jpg
