### ISSUE TITLE
[Quest] Minor typo-issue in handing in Scourgestones

### ISSUE THREAD

**Issue by Sierbahnn** [WoWManiaUK/Redemption#4757]
**Links:**
I am just handing in Scourgestones at the Argent Officer Garush (not sure if this holds true for the one at Light's Hope too, but I suppose it might), and when I do and I am about to complete the quest it says "For the dawn, my g$sister:brother;!". I think that's just a trigger not hitting for the correct tag, but thought I would mention it.

**What is Happening:**

**What Should happen:**

**Comment by jeyrella** [comment]
https://wow-mania.com/armory/?quest=5406
![image](https://user-images.githubusercontent.com/46089380/87250149-013c0480-c45b-11ea-8761-28a34c5af120.png)

**Comment by jeyrella** [comment]
Confirmed same text on Alliance side
https://wow-mania.com/armory/?quest=5404
![image](https://user-images.githubusercontent.com/46089380/87250364-339a3180-c45c-11ea-8c32-cf32a767b087.png)

**Comment by Rushor** [comment]
fixed, remember to delete cache before testing :)

**Comment by jeyrella** [comment]
Fixed
![image](https://user-images.githubusercontent.com/46089380/87253404-ce056f80-c472-11ea-8e2d-b976c2c2a81d.png)
![image](https://user-images.githubusercontent.com/46089380/87253436-1755bf00-c473-11ea-9012-bc4459df7d86.png)

**Comment by Sierbahnn** [comment]
You guys are just the best.

**Comment by Rushor** [comment]
the fixes will be live on tuesday
