### ISSUE TITLE
[Quest] Not a Bug - Icecrown - 13358

### ISSUE THREAD

**Issue by jeyrella** [WoWManiaUK/Redemption#4758]
**Links:**
https://wow-mania.com/armory/?quest=13358
https://wow-mania.com/armory/?item=44433
Used on corpse of NPC:  https://wow-mania.com/armory/?npc=32260
Using rod:  https://wow-mania.com/armory/?spell=60528  >> casts: https://wow-mania.com/armory/?spell=60531  >>  creates  https://wow-mania.com/armory/?item=44434

**What is Happening:**
One can use the [Rod of Siphening](https://wow-mania.com/armory/?item=44433) on the same corpse repeatedly to generate [Dark Matter](https://wow-mania.com/armory/?item=44434).

**What Should happen:**
Corpse should only allow Rod to be used once to generate one Dark Matter per corpse.

**Comment by Rushor** [comment]
all fixed. you can now only use the item newar a dead  https://wow-mania.com/armory/?npc=32260 (only 1 time). cannel spell will now also target https://wow-mania.com/armory/?npc=32260 visually.

once you got 5 of the items, you can use the summon stone gameobject, it will remove the 5 items from inventory, complete the quest and a Dark Messenger will spawn a few seconds.

**Comment by Zanguin-ManiaTester** [comment]
https://youtu.be/p8l4umQsuWo

Fix confirmed, thanks! Player can only get 1 Dark Matter from minions now.

**Comment by jeyrella** [comment]
May need checking for the Alliance version.  Could not complete today on live.  Will check in PTR once back up and re-open if necessary.
