### ISSUE TITLE
[Instance] CoT Old Hillsbrad Foothills - Escape from Durnholde event not completing

### ISSUE THREAD

**Issue by Davilah77** [WoWManiaUK/Redemption#4759]
**Links:**
the quest https://www.wowhead.com/quest=29599/escape-from-durnholde

**What is Happening:** When arrived to the last part of instance Thrall is in front of Taretha u must talk with Taretha for the event of the last boss but cant happends nothing, a gm try to respawn new toon of taretha sometimes but still bugged, you can click in the option for nothing happends

**What Should happen:** This quest is necesary for a chain for can go to COT2 (and still doing the quest chain for alchemyst) if not finish cot1 cant enter in cot2

**Comment by jeyrella** [comment]
Interesting.  Has worked in the past on at least 4 of my toons.  Will check later (if nobody else picks up)

**Comment by Oganku** [comment]
Might be one of the events that was missed when we fixed the double spawns a few weeks ago.

**Comment by svijetlo** [comment]
i never had problem with him at the end i had problem ones thral exist prison

**Comment by jeyrella** [comment]
Well yeah, this one is confirmed, surprisingly.  Some kind of regression  It's when you are in the upper floor of the inn, waiting for Taretha to respond to Thrall. 
![image](https://user-images.githubusercontent.com/46089380/87352973-d97c9780-c553-11ea-9f31-19dfdf7d4fb8.png)

Video of runthrough is here https://youtu.be/RfH2ofnpb5o.  Relevant issue starts at 7mins 35sec.  I have spotted some other minor improvements that could be made, I will catalogue those separately.

**Comment by Davilah77** [comment]
I try few hours later and can done without problem, so weird. I do again all instance and looks like all is good... except, when finish the dungeon you can talk with the "dragon" and click in "please teleport out, im tired" and doesnt work xD

Thanks for all

**Comment by jeyrella** [comment]
Reopening.  Just done this on Redemption and did exactly the same thing.  Stuck at the text with Taretha

**Comment by Rushor** [comment]
Once Thrall is close to the girl, the girl will get a gossip option to continue the fight. That worked fine for me so far.

https://gyazo.com/1d7fae6a60f2a3329ddf25dd11eb642b
