### ISSUE TITLE
[Quest] Healthy Dragon Scales drop chance too high

### ISSUE THREAD

**Issue by Sierbahnn** [WoWManiaUK/Redemption#4760]
**Links:**
https://classic.wowhead.com/quest=5582/healthy-dragon-scale#comments

**What is Happening:**
This item keeps dropping from the mobs in Scholomance, and should not.
This means that you can get a bagful of scales that prompts you to start the quest, and once you are on it, and pick one up, you cannot loot more of the dragonlings since they have scales you cannot pick up.

**What Should happen:**
If you have one item that starts or ends this quest in your inventory, no other drops should be visible from other mobs.

**Comment by jeyrella** [comment]
_"This item keeps dropping from the mobs in Scholomance, and should not."_
This wowhead comment would seem to disagree.  Perhaps I've misunderstood the problem you're seeing?
![image](https://user-images.githubusercontent.com/46089380/87350231-78eb5b80-c54f-11ea-8f98-207fc3b02309.png)

**Comment by Sierbahnn** [comment]
Oh I see. That's not how I remembered it at all. Then it is not a bug, only a very annoying feature. Thanks.

**Comment by jeyrella** [comment]
Ok so there was a change needed;  drop chance was 100% and should be 20%, also should only drop if quest 5529 has been turned in.

**Comment by svijetlo** [comment]
it is vanilla quest , so you can see 10000000000 drop but you can start quest only form one , almost every vanilla dung has one of those
