### ISSUE TITLE
[Item/Spell/Quest] Onslaught Gryphon Reins - Icecrown

### ISSUE THREAD

**Issue by jeyrella** [WoWManiaUK/Redemption#4762]
**Links:**
https://wow-mania.com/armory/?spell=49642
Provided by https://wow-mania.com/armory/?item=40970
Used in quest:  https://wow-mania.com/armory/?quest=12814

**What is Happening:**
This "mount" (actually, it's a vehicle) appears to have a native speed of 357%.  This makes it faster than epic flying mounts.

**What Should happen:**
Should have a flying speed of 100% and ground speed of 114%
https://www.wowhead.com/item=40970/onslaught-gryphon-reins#comments
![image](https://user-images.githubusercontent.com/46089380/87358005-e2be3200-c55c-11ea-8e99-91d68f0d1dd3.png)

**Comment by Rushor** [comment]
this aura is the reason https://wow-mania.com/armory/?spell=54422

**Comment by Rushor** [comment]
replaced the aura with https://wow-mania.com/armory/?spell=43775, so it has normal 100 % speed again.
