### ISSUE TITLE
[Quest] Recover the Cargo - Quest item not dropping from pools - 11140

### ISSUE THREAD

**Issue by Doottacc** [WoWManiaUK/Redemption#4763]
**Links:**
http://www.wow-mania.com/armory?quest=11140

**What is Happening:**
I would go to the Floating Wreckage and use the item that comes out of the bag and nothing happens with it, I tried it on a lot of the pools however I did not get any items from it. Tried disabling my addons, and leaving the quest and picking it back up but nothing happened still. 

**What Should happen:**
Should drop a strongbox on successful salvage, or you are attacked by a Murloc.

**Comment by Rushor** [comment]
can a tester confirm that?

**Comment by jeyrella** [comment]
Ooh.  Yes I will.  I sort of remember thinking this one was a bit odd

**Comment by jeyrella** [comment]
reference video:   https://www.youtube.com/watch?v=S28r-OIzHcc    
(Cata era but should be generally the same idea, no vids found for wotlk or earlier era)

**Comment by jeyrella** [comment]
Confirmed.  Item works but on completion of the spell neither murloc is spawned ("failed salvage") nor the successful quest item.
https://youtu.be/DZnIq-i0TVs

This has worked in the past as I can see 4 of my toons with it completed.

**Comment by jeyrella** [comment]
Shipwreck Debris does not despawn after salvaging so one can sit there and salvage the same debris over and over.

This is not correct, should despawn after salvaging, regardless of success or fail:  https://youtu.be/S28r-OIzHcc?t=40

**Comment by Rushor** [comment]
okay the object (ring) now despawns and a monster will spawn. we cannot do it in different way sadly. we have only limited options to script that currently. (the fire cannot despawn)

**Comment by Rushor** [comment]
okay burning object cannot be despawned. everything else will work.

circle object will despawn and either murloc will spawn and attack or the item will be added

**Comment by jeyrella** [comment]
Fixed nicely.  https://youtu.be/w4HfNlM0O5w

**Comment by Rushor** [comment]
thank you for the treamwork :)
