### ISSUE TITLE
[Quest] After the lovepotion:  Post-quest event missing - Blackrock Depths 

### ISSUE THREAD

**Issue by Sierbahnn** [WoWManiaUK/Redemption#4764]
**Links:**
https://classic.wowhead.com/quest=4201/the-love-potion

**What is Happening:**
After handing in the quest the dialog option appears, but clicking it does not activate the behavior.

**What Should happen:**
When prompted, the NPC Mistress Nagmara should leave the conversation, and open the other door of the Guzzler.

**Comment by Rushor** [comment]
lot of event missing here https://classic.wowhead.com/quest=4201/the-love-potion#screenshots:id=871686

**Comment by Rushor** [comment]
NPCs:
Mistress Nagmara: 9500
Private Rocknot: 9503

Spells:
Nagmara's Love Potion: 14928
Nagmara + Rocknot: 15064
Nagmara's Vanish: 15341

Quest:
The Love Potion: 4201

Zone:
Blackrock Depths: 1584

https://github.com/TrinityCore/TrinityCore/issues/15138

https://github.com/newkev/cmangos-classic-pvebot/blob/d67976c40786753b7560cd91d4c669729fc9e38a/src/game/AI/ScriptDevAI/scripts/eastern_kingdoms/blackrock_depths/blackrock_depths.cpp

need to convert that with sai

**Comment by Rushor** [comment]
fixing this today!

**Comment by jeyrella** [comment]
yeah i would have tested it but PTR was down for the whole day.  or rather, couldn't log in

**Comment by jeyrella** [comment]
Confirmed event is missing.  https://youtu.be/Fb0T0RUYcsg

**Comment by Rushor** [comment]
added! https://gyazo.com/95b62e128858f7ce8aea50aa18672b07 was a lot of research haha.

now ehen chosing the gossip option, nagmara will walk together with Rocknot, open the door, go under the bridge and start loving
