### ISSUE TITLE
[Quest] The Earthen Oath + Loken's Lackeys

### ISSUE THREAD

**Issue by Sierbahnn** [WoWManiaUK/Redemption#4765]
**Links:**
https://www.wowhead.com/quest=13005/the-earthen-oath

**What is Happening:**
The mobs spawn when I use the Horn of the Peaks, but they do not aggro the enemy, nor help out in any way, even when taking direct damage.

**What Should happen:**
The Earthen Wardens should spawn and aggo what I aggro, and beat it to a pulp.

**Comment by jeyrella** [comment]
Hang on, this might be regression of previous ticket

**Comment by jeyrella** [comment]
@Sierbahnn That is not how they act.  They are not SUPPOSED to take aggro, they are a pack of pets that you have to physically command.
See video https://www.youtube.com/watch?v=q4V1eq6oreI retail.
