### ISSUE TITLE
[Quest]: The Battle For The Undercity - Warsong Battleguard pathing issues

### ISSUE THREAD

**Issue by Zanguin-ManiaTester** [WoWManiaUK/Redemption#4766]
**Links:**
http://www.wow-mania.com/armory?quest=13267

What is Happening:

During the Battle for The Undercity, at some point down in the sewers a horde of Warsong Battleguards spawn and do not stop to turn at the royal quarters but continues on and stops dead in their tracks as can be seen on this video. If the player follows the Warsong Battleguards and returns to the royal quarters, the player cannot enter the quarters and complete the quest, as there will be a stonewall locking the player from entering the royal quarters as shown in the video. 

https://youtu.be/9fbgbOs9iys

I encountered it on Zanguin on Redemption and needed aid from a GM, I also encountered it on PtR. 
Furthermore I had a player test it out for me and he contacted GM's about it.

What Should happen:
Even if videos like https://www.youtube.com/watch?v=u3zjdI_LN68 shows no guards actually entering the quarters, the player should not get stuck down in the Undercity due to following the wrong NPC's

**Comment by Rushor** [comment]
ehh wait this is wrong. players should NOT follow the Warsong Battleguards. This is just useless event :D 

People must follow thrall. If the player is too far away from thrall, he will despawn. That is intended to my mind

**Comment by Zanguin-ManiaTester** [comment]
Statistically a certain amount of people will end up following those guys and as such there would be more ingame tickets about it in the future?

**Comment by Zanguin-ManiaTester** [comment]
and thanks! should solve it!

**Comment by Zanguin-ManiaTester** [comment]
Player reports now that he saw Thrall walk through the stonewall. Hm.

**Comment by Rushor** [comment]
guards will despawn right after the bridge now, so player no longer confused

**Comment by jeyrella** [comment]
https://youtu.be/PkYHn-N01rg

**Comment by Rushor** [comment]
thank you
