### ISSUE TITLE
Cant play! :(

### ISSUE THREAD

**Issue by Vanja1987** [WoWManiaUK/Redemption#4767]
**Links:**
https://www.wow-mania.com/

**What is Happening:**
when i log on my account and select hero it disconet my from server
**What Should happen:**

**Comment by Oganku** [comment]
Make sure you aren't using a VPN and are using the latest patch and launcher you can find at https://www.wow-mania.com/downloads.

I'll close your issue since this github is for in-game related bugs, but feel free to ask on discord (https://discord.gg/b7s5ZV) if you still can't get it to work.

**Comment by Vanja1987** [comment]
i still cant enter the world..i try everything. : (


________________________________
