### ISSUE TITLE
Mining nodes missing

### ISSUE THREAD

**Issue by Davilah77** [WoWManiaUK/Redemption#4768]
**Links:**
https://www.wow-mania.com/armory/?object=189980
https://www.wow-mania.com/armory/?object=191133

**What is Happening:**
Since arround 3 days the spawn nodes of all saronite and titanium in icecrown and sholozar bashin dont spawn properly, if they do, the time is extremely long since on several occasions I have waited to see if it would appear for 30 min without results

**What Should happen:** The nodes of mining they should reappear every 5-10 minutes

**Comment by Keader** [comment]
Fixed already, will be on live soon
