### ISSUE TITLE
[NPC] Torwa Pathfinder speech text incorrect on quest 9063

### ISSUE THREAD

**Issue by Sierbahnn** [WoWManiaUK/Redemption#4769]
**Links:**
https://classic.wowhead.com/quest=9063/torwa-pathfinder

**What is Happening:**
After you complete the questchain and click "Who is this Lar'korwi you spoke of?" the answer is "Greetings [name]".

**What Should happen:**
She should tell you about the monster you killed during the quest.

**Comment by jeyrella** [comment]
Again, I can't replicate this
![image](https://user-images.githubusercontent.com/46089380/87873213-9721e300-c9b7-11ea-84e1-8dd5427104fc.png)

Can you please give class/race specifics, or some screenshot about this.

**Comment by Rushor** [comment]
he means this https://i.imgur.com/dpfhkBb.jpg after quest 4290 is rewarded

**Comment by Sierbahnn** [comment]
Exactly. Thanks Rushor.

**Comment by Rushor** [comment]
found the text:


The ravasaur here in Un'Goro seem to be related to the raptors of the barrens - highly intelligent, volatile, and with a sense or code of conduct. The greatest of these that I have encountered is  Lar'korwi. He is one of the most dangerous beasts I've ever seen. In taurahe, Lar'korwi means "sharp claw," but that does not do him justice.$B$BDo not underestimate Lar'korwi if you ever plan on hunting him, but I will help you in any way I can if you do.
--

added to him with next update

**Comment by Rushor** [comment]
npc 9619

**Comment by jeyrella** [comment]
hmm.  odd.  I never saw that option and still don't
![image](https://user-images.githubusercontent.com/46089380/87877457-58e7ec00-c9d6-11ea-8e5a-45666396d366.png)
Oh well.

**Comment by Rushor** [comment]
hmm okay if quest is 4290 completed and rewarded it will be shown :O

**Comment by Rushor** [comment]
oaky updated again, pls delete cache also before testing

**Comment by Rushor** [comment]
https://i.imgur.com/nWaoFBx.jpg
