### ISSUE TITLE
[Quest] Drag and Drop

### ISSUE THREAD

**Issue by Sierbahnn** [WoWManiaUK/Redemption#4770]
**Links:**
https://www.wowhead.com/quest=13323/drag-and-drop

**What is Happening:**
I get an "Invalid target"-warning when I try to chuck the Orb of Illusion onto a Dark Subjugator.

**What Should happen:**
The orb should hit the Dark Subjugator, triggering its despawn/respawn, event/death.

**Comment by jeyrella** [comment]
Am having trouble reproducing this one.  Seems to work fine.  https://youtu.be/coC0yDYrx5M

Are you sure it was on an untapped target?

**Comment by Rushor** [comment]
works for me too https://i.imgur.com/VEqpvfI.jpg

if you can make a video of it, we can see the reason of the issue and we will reopen
