### ISSUE TITLE
Sword's Rest

### ISSUE THREAD

**Issue by Sierbahnn** [WoWManiaUK/Redemption#4771]
**Links:**
https://wowwiki.fandom.com/wiki/Halls_of_Reflection

**What is Happening:**
After the ninth wave completes and the second boss is supposed to spawn the wave-counter resets to 1 and with Sylvanas out of the door you have to disband to get out.

**What Should happen:**
Second boss should spawn and the event should continue

**Comment by Blyatman1** [comment]
Halls of Reflection works just fine most of the time. In some cases, something bugs out and either makes the gauntlet reset, or softlocks the group in the dungeon. Go out, reset the dungeon, and try again. There's many other reports about HoR bugging out, and unfortunately it would seem there's no clear fix at the moment.

**Comment by Sierbahnn** [comment]
I see. Sorry to hear that. I hope that I can get through it once or twice then. At least he bug is early in the instance, and not in the last bit. That would be frustrating!
