### ISSUE TITLE
[NPC/Raid] Hands of the Deceiver (Sunwell Plateau)

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#4772]
**Links:** https://wowwiki.fandom.com/wiki/Hand_of_the_Deceiver_(mob)
https://www.wowhead.com/npc=25588/hand-of-the-deceiver

**What is Happening:** 

> Initially, three [Hands of the Deceiver](https://www.wowhead.com/npc=25588/hand-of-the-deceiver) are positioned next to the Sunwell, channeling Anveena's powers into the Sunwell.

These 3 adds constitute the first phase of Kil'jaeden's sunwell plateau encounter, and only upon defeating all 3 does the main boss actually appear (phase 2).

> Once all three Hands are defeated, phase 2 begins.
>
> Phase 2
> Kil'jaeden arrives in a blaze of glory (literally).

The issue is that these adds are treated as regular mobs, and if the party wipes in the later phases of the encounter, these mobs never respawn, making it impossible to re-try the fight, as it is only upon defeating all 3 of them that the fight continues into phases 2 thru 5.

**What Should happen:** If the party wipes against Kil'jaeden in Sunwell Plateau, the boss despawns properly, but the 3 [Hands of the Deceiver](https://www.wowhead.com/npc=25588/hand-of-the-deceiver) should also respawn. The fight works fine, but it is impossible to currently re-try it since those mobs never respawn.

**Comment by Rushor** [comment]
they drop below the map once beeing spawned. will adjust the positions

**Comment by svijetlo** [comment]
![WoWScrnShot_072120_100334](https://user-images.githubusercontent.com/61908373/88028833-75e90000-cb39-11ea-9517-2a76d5b83333.jpg)
