### ISSUE TITLE
[Quest]: A Fine Mess - Quest Doesn't Complete

### ISSUE THREAD

**Issue by kamoodle5** [WoWManiaUK/Redemption#4773]
Links: https://wotlkdb.com/?quest=2904

What is Happening:
Quest does not complete when arriving at the dungeon's entrance with the goblin NPC. Also, the little alarm robot, which acts like a time bomb during the escort, follows at only walking speed.

What Should happen:
Quest should complete successfully when at the dungeon's entrance with the goblin NPC (no need to step out of the instance). As for the time bomb robot, it should follow at normal running speed.

**Comment by jeyrella** [comment]
Sounds very similar to https://github.com/WoWManiaUK/Redemption/issues/4398 and #3505.  Both of which couldn't be proven and seemed to work fine.  Will see.

**Comment by Rushor** [comment]
Thanks for testing :)

**Comment by kamoodle5** [comment]
Tried this quest several more times to no avail. At one point, I even watched a video on how it's done and followed the player almost exactly. I have noticed that from my experience compared to the Youtuber is the goblin does attract hostile mobs, which he normally doesn't. During another attempt, I had a hunch that while in combat, my pet's thunderstomp have somehow messed up the Alarm Bot's AI if it got close enough, thus botching the upcoming quest.

Here's a video clip I made showing my experience with the escort quest. It can also confirm how the goblin pulled some mobs: https://youtu.be/v9WSHwStvPs

**Comment by jeyrella** [comment]
thanks for your video clip @kamoodle5 , this helps enormously.  will try it out tonight on PTR

**Comment by Rushor** [comment]
for anyone beeing involved, the areatrigger that is important for the credit is exactly HERE https://i.imgur.com/n73ADxX.jpeg

i will work on the speed of the alarm bot and the faction since that seems to be the reaosn for the issue (missing interaction between bot and questgiver because they are too far away)

**Comment by Rushor** [comment]
okay the bot should be faster now

**Comment by kamoodle5** [comment]
Just now got the quest completed myself, although the Alarm Bot was still at walking speed. What I did on the second attempt was walk all the way along with the goblin and the bot, just to make sure those two stayed together. The goblin did finally respond as normal on the final turn towards the exit.

![WoWScrnShot_072020_231914](https://user-images.githubusercontent.com/67519835/88012533-cb90be80-cadf-11ea-82d2-980695c8b466.jpg)
