### ISSUE TITLE
[Raid] Zul'Aman event chests have wrong loot table

### ISSUE THREAD

**Issue by jeyrella** [WoWManiaUK/Redemption#4774]
**Links:**
https://wow.gamepedia.com/Zul%27Aman_timed_event

**What is Happening:**
Most of the chests are empty, where as some have up to 4 items in
![image](https://user-images.githubusercontent.com/46089380/87884999-57381b80-ca0a-11ea-8efd-cdef1f4bb7cd.png)
![image](https://user-images.githubusercontent.com/46089380/87885034-9ebea780-ca0a-11ea-904a-026a08ea1f1f.png)

**What Should happen:**
Each chest should have exactly one item inside.

**Comment by Keader** [comment]
To help you test:

make 4 macros:

.gob add temp 186648

.gob add temp 187021

.gob add temp 186672

.gob add temp 186667

Each macro will have a type of chest.

**Comment by jeyrella** [comment]
Fixed
![image](https://user-images.githubusercontent.com/46089380/87885220-2527b900-ca0c-11ea-83c1-bf141613ccf8.png)
![image](https://user-images.githubusercontent.com/46089380/87885227-396bb600-ca0c-11ea-9bf9-197ae2fd9161.png)
