### ISSUE TITLE
[Quest] Bring Down those shields

### ISSUE THREAD

**Issue by Sierbahnn** [WoWManiaUK/Redemption#4779]
**Links:**
https://www.wowhead.com/quest=11396/bring-down-those-shields

**What is Happening:**
When using the Scourging Crystal Controller on one of the crystals it comes up as EVADE, and does not trigger a despawn of the shield, so that you can proceed with the quest.

**What Should happen:**
It ought to remove the shield so that the objective completes.

**Comment by Rushor** [comment]
hmm for me they become attackable and then i can kill them. can you try it after a some hours again?

are you using pets to kill them them? https://gyazo.com/68404ca004bf5ed9de5a79930a23b051
