### ISSUE TITLE
[Companions] Faction Issue with the Moonkin Hatchling companion pets

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#4782]
**Links:** https://www.wow-mania.com/armory/?item=68618#see-also
https://www.wow-mania.com/armory/?item=68619

**What is Happening:** The 2 versions of the Moonkin Hatchling companion pet ([Alliance](https://www.wow-mania.com/armory/?item=68618)/[Horde](https://www.wow-mania.com/armory/?item=68619)) do not have any indicator on their tooltips showing that they are faction-exclusive. However, if one does acquire the opposite faction's pet through any means (donation, mall sale, vendor issue, etc.) they will get the message "You can never use that message". This causes players to ask for refunds or complain about a missing warning.

The weird part of this, is that Alliance players can properly only see and purchase the alliance one from Joe Maniac, but Horde players can see both the Alliance AND Horde version at the same NPC (Joe).

**What Should happen:** Either remove the faction-exclusivity for these pets (only custom pet that has one right now), add a tag that specifies it requires horde races or alliance races (like for mounts), or just make the Alliance Hatchling invisible for Horde players.

**Comment by Rushor** [comment]
alright horde will now only see the horde hatchling  - no more confusion
