### ISSUE TITLE
[Quest] The Call to Command

### ISSUE THREAD

**Issue by Sierbahnn** [WoWManiaUK/Redemption#4783]
**Links:**
https://classic.wowhead.com/quest=6144/the-call-to-command

**What is Happening:**
When handing in this quest I was teleported several kilometers above the UC, and fell long enough to chat with a guildie about it before landing back in the throneroom again.

**What Should happen:**
It ought to just complete the quest and let me get on with my game.

**Comment by jeyrella** [comment]
Am having trouble replicating, well, anything really.  Nothing happened at all when tried on two test toons on PTR.
https://youtu.be/64W8n_Cw9mI
I can't remember whether it is supposed to teleport player to UC or not, am having trouble finding any reference videos from the era.  Nothing in wowhead comments to confirm either way.

**Comment by Sierbahnn** [comment]
I am guessing it was just a one-time glitch then.
