### ISSUE TITLE
[PVP] Warsong gulch battleground debuff persists after the end of event

### ISSUE THREAD

**Issue by 2751gleb** [WoWManiaUK/Redemption#4784]
**Links:**

**What is Happening:**

At Warsong gulch, when flagcarrier holds flag for 10(or 15? not sure) she gets "Focused assault" debuff, limiting one's movement speed by 100% and encreasing taken damage. This spell is removed after flagcarrier looses flag. Warsong gulch pvp battleground has limited duration (25 minutes). And If this timer expires while player is still holding the flag "Focused assault" debuff is still being applied, even after telepoting charater out of battleground.
**What Should happen:**
"Focused assault" debuff should be removed after battleground end.

**Comment by Keader** [comment]
Something removed this fix (is not in core anymore).
I made a new one
