### ISSUE TITLE
Dodge while stunned

### ISSUE THREAD

**Issue by 2751gleb** [WoWManiaUK/Redemption#4785]
**Links:**
https://drive.google.com/file/d/1sFA-cydahBKCwfgu5cACgSUVH-CFaPpX/view?usp=sharing

**What is Happening:**
When pvp opponent is under stun effect, she dodges melee attacks

**What Should happen:**
Stunned character is to be unable to dodge

**Comment by svijetlo** [comment]
works good not no dodge while you get stun , tested it while forcing mob to stun me and by stunning me self with rogue
