### ISSUE TITLE
[Quest] A Delicate Touch - Storm Peaks - 12820

### ISSUE THREAD

**Issue by jeyrella** [WoWManiaUK/Redemption#4786]
**Links:**
https://wow-mania.com/armory/?quest=12820
https://wow-mania.com/armory/?item=40676

Reference video from 2008:  https://youtu.be/1aCPJU9KysM

**What is Happening:**
a)  Land mines are blowing up instantly
b)  This means only one can be used at once
c) NPCs heal themselves up extremely fast after hit, as if they are no longer in combat / evading.
This was improved in #2573, but needs further refinement.  Whilst it is technically completable, you need to outgear the (incorrect) NPC healing, and be able to do lots of instant cast burst damage.  At level this extremely difficult for many classes.
https://youtu.be/ednmmcurlJM

**What Should happen:**
a)  Land Mines should be placed on the floor, and should blow up as an NPC gets near (rather than instantly)
b)  Multiple mines can be laid at once, and NPCs can be hit by multiple explosions
c)  NPCs should not heal themselves rapidly
Reference video from 2008:  https://youtu.be/1aCPJU9KysM

**Comment by Zanguin-ManiaTester** [comment]
https://youtu.be/rZ4BWHV3s6g

Confirmed not working. Landmines explode instantly and mobs regenerate health at an insane rate.

**Comment by Rushor** [comment]
okay fixed. mines will now only detonate if a invader is in range and the invaders will no longer regenerate health.

there is an issue that the mines spawn a bit mid air. that issue can be ignored.

**Comment by Zanguin-ManiaTester** [comment]
https://youtu.be/qLf1-qJPxWw 

Fix confirmed, Landmines and health no longer bug :) Thanks!
