### ISSUE TITLE
Blackrock Depth - Talking to Doom'rel

### ISSUE THREAD

**Issue by Sierbahnn** [WoWManiaUK/Redemption#4789]
**Links:**

**What is Happening:**
When talking to him I get the response "[PH] Continue..."

**What Should happen:**
Not sure what the dialogue is supposed to be, but I don't think it is supposed to be "[PH]" anyway.

**Comment by Rushor** [comment]
Can you try to find a source on Youtube maybe from classic wow

**Comment by Sierbahnn** [comment]
Sorry, all the videos I found someone else was talking to the mob, not the guy recording it. :(

**Comment by Rushor** [comment]
fixed waiting for compile

**Comment by Rushor** [comment]
applied

**Comment by svijetlo** [comment]
![WoWScrnShot_073020_131218](https://user-images.githubusercontent.com/61908373/88916440-5d2dc800-d266-11ea-9710-eddfbbed524d.jpg)
![WoWScrnShot_073020_131226](https://user-images.githubusercontent.com/61908373/88916445-60c14f00-d266-11ea-8f59-53ef7261dab4.jpg)
