### ISSUE TITLE
[Raid] Blackrock Stadium

### ISSUE THREAD

**Issue by Sierbahnn** [WoWManiaUK/Redemption#4791]
**Links:**

**What is Happening:**
I entered the blackrock stadium in Upper BlackRock Spire and the first wave of mobs spawned, and then the gate opened and shut a few times while Victor was yelling as if the fight continued below, but no more waves appeared. Then the Warchief spawned as he was supposed to, but all the other waves never appeared.

**What Should happen:**
After the first wave a second should appear, and a third, and so on, until the boss.

**Comment by svijetlo** [comment]
work fine now you get few waves of mobs then boss comes 20ish sec after last wave of mobs
