### ISSUE TITLE
[Quest] No Mercy for the Merciless/Slay them All!

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#4792]
**Links:** https://www.wow-mania.com/armory/?quest=13177
https://www.wow-mania.com/armory/?quest=13178
https://www.wow-mania.com/armory/?quest=13179
https://www.wow-mania.com/armory/?quest=13180
https://www.wowhead.com/quest=13177/no-mercy-for-the-merciless#comments

**What is Happening:** The alliance wintergrasp weekly quests [[No Mercy for the Merciless]](https://www.wow-mania.com/armory/?quest=13177) currently only award credit for killing the horde NPCs across wintergrasp, but not for killing players. I suppose the horde version [Slay them [all!]](https://www.wow-mania.com/armory/?quest=13179) behaves the same way.

**What Should happen:** Killing players of the opposite faction in wintergrasp should also award credit toward quest completion.

**Comment by Rushor** [comment]
okay fixed once compiled

**Comment by Rushor** [comment]
applied

**Comment by svijetlo** [comment]
counts player of opposite fraction now

**Comment by jeyrella** [comment]
Confirmed working still in PTR.
https://youtu.be/ArREtS46h3E

**Comment by Oganku** [comment]
Works well with kills of horde members, but now the horde/alliance NPCs count as 2 credits, since they're faction members and one for being an NPC. Old requirements only checked for specific NPCs, whereas now any opposite faction killed in wintergrasp counts, which is correct. Old requirement should be removed to avoid double credits from NPCs.

**Comment by Rushor** [comment]
should be fixed now
