### ISSUE TITLE
[Spell] Judgement of Justice slow

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#4793]
**Links:** https://www.wow-mania.com/armory/?spell=20184

**What is Happening:** [Judgement of Justice](https://www.wow-mania.com/armory/?spell=20184) currently slows (prevents from fleeing) any mob/boss in the game. 

**What Should happen:** The slow applied should not bypass cc resistance of most bosses, and should always check for slow resistance/immunity before taking effect.

**Comment by Aristo14** [comment]
It is slowing? It should only prevent increase of speed other than normal speed.

**Comment by Oganku** [comment]
It definitely slows. 

If you use it on lk at the start of transition, it takes him a very long time to walk to the center. 
On blood prince council you can also slow the 2 melee princes and if your tank can keep aggro, you can kite them without taking any damage that way. 

I'm not sure of how many bosses it affects, but LK and blood princes are definitely not meant to be slowed below player normal speed.

**Comment by svijetlo** [comment]
works fine no does not apply slow efect on normal moving speeds but will put you  down to normal speed if you use some speed boost , rogue sprint etc , did not take any effect on boss in icc or RS
