### ISSUE TITLE
[Quest] Fire upon the water

### ISSUE THREAD

**Issue by Sierbahnn** [WoWManiaUK/Redemption#4794]
**Links:**
https://www.wowhead.com/quest=12243/fire-upon-the-waters

**What is Happening:**
You throw the firewater on the sails, and the sailors are still on deck, and still red

**What Should happen:**
The fire should aggro the sailors so that they do not aggro on you when you sneak below decks.

**Comment by Rushor** [comment]
will check once ptr is back

**Comment by Rushor** [comment]
yeah it's an old issue, the npcs never changed their faction upon using the firewater

**Comment by Rushor** [comment]
okay once the firewater is used, the npcs will turn "neural" (yellow) for 2 minutes. after that they are hostile again

**Comment by jeyrella** [comment]
hmm.  don't see it.  still seems to be hostile.  was it properly applied?
https://youtu.be/ZgeeV6IfjBw

**Comment by Rushor** [comment]
it was not applied and got reverted... shit

**Comment by Rushor** [comment]
reapplied now

**Comment by jeyrella** [comment]
Fixed.  
https://youtu.be/kerpe6LweWE
