### ISSUE TITLE
[Quest] Assault by Air (Icecrown) - Horde

### ISSUE THREAD

**Issue by Scara999** [WoWManiaUK/Redemption#4795]
**Links:**
[https://www.wowhead.com/quest=13310/assault-by-air](url)

**What is Happening:**
The vehicle i was supposed to mount didn't spawn.

**What Should happen:**
[https://www.wowhead.com/npc=31881/korkron-troop-transport](url) should spawn after accepting the quest. I checked youtube for the location, but it wasn't there. Tried relogging two times, still nothing.
I flied over to where the Alliance version of the quest is and I could see the vehicle there, obviously couldn't mount it though, being Horde.

**Comment by Rushor** [comment]
We need to Adjust the respawn timer

**Comment by jeyrella** [comment]
PTR not available for testing.

**Comment by wow-mania** [comment]
pretty sure it works

**Comment by Rushor** [comment]
it works, but the respawntimer for both airplanes is reaaaly too long. reduced the respawntimer now, so people can do the quest better.

**Comment by Rushor** [comment]
okay it is back online the fix

**Comment by jeyrella** [comment]
still not here 17 mins later
![image](https://user-images.githubusercontent.com/46089380/89129035-c37a4b00-d4f1-11ea-8074-3c92981d49bb.png)

**Comment by jeyrella** [comment]
![image](https://user-images.githubusercontent.com/46089380/89129149-e6f1c580-d4f2-11ea-975b-7772d3e85b34.png)

**Comment by Rushor** [comment]
okay now should work. one the first guy did the quest, the bomber will despawn on last waypoint and respawn after around 10 minutes. before it was like 1 hour

**Comment by jeyrella** [comment]
Nope
![image](https://user-images.githubusercontent.com/46089380/89226425-d36a5b80-d5d3-11ea-8023-536a992c39b3.png)

**Comment by wow-mania** [comment]
What's going on with this one?

**Comment by jeyrella** [comment]
Not sure why this was closed?  This is still an issue meaning players can't complete the quest.

**Comment by jeyrella** [comment]
Ahhh hang on.  I exited the bomber straight away so i could test the respawn.  Needs to be a condition check for that as well then.

**Comment by Rushor** [comment]
okay i will add that

**Comment by Rushor** [comment]
i will that the airship always despawns of a player passenger leaves it ok?

**Comment by jeyrella** [comment]
yes, it should do that indeed

**Comment by Rushor** [comment]
okay ship will now also despawn when player simply leaves the turret - it should then respawn within 5 -7 minutes. fix for horde and alliance.

**Comment by jeyrella** [comment]
Airship despawns....  but the turret doesnt and stays fixed on the ground.  lol
![image](https://user-images.githubusercontent.com/46089380/89731935-0a60c700-da43-11ea-87fa-2efda78a11ea.png)

**Comment by jeyrella** [comment]
Ok, now respawns correctly if exits
![image](https://user-images.githubusercontent.com/46089380/89732236-49901780-da45-11ea-8d06-06a8d1ae490e.png)

Quest itself works
![image](https://user-images.githubusercontent.com/46089380/89732263-6a586d00-da45-11ea-952d-3c2c26c4ee6c.png)
and transport respawns after that too
![image](https://user-images.githubusercontent.com/46089380/89732337-008c9300-da46-11ea-8ee1-e9323de6edfb.png)

Looks good!

**Comment by Rushor** [comment]
will check

**Comment by Rushor** [comment]
the fix got lost, the turret should now again despawn the whole plane and the passengers if the player leaves the turret during the escort. also plane should respawn faster again (after 5-7 mins). please check for possible crashes

**Comment by hawker357** [comment]
Confirmed working on horde side, both manually exited and quest completion, ship respawns after around 5 minutes
![Screenshot (73)](https://user-images.githubusercontent.com/79724094/121348687-8e643380-c920-11eb-8b84-9ac86be52b0b.png)
![Screenshot (74)](https://user-images.githubusercontent.com/79724094/121348691-915f2400-c920-11eb-9fb7-48fd63b41d6e.png)

**Comment by hawker357** [comment]
Confirmed working on alliance side, both manually exited and quest completion, ship respawns after around 5 minutes
![Screenshot (75)](https://user-images.githubusercontent.com/79724094/121350323-6ece0a80-c922-11eb-84ce-8620a4478f02.png)
![Screenshot (77)](https://user-images.githubusercontent.com/79724094/121350339-72fa2800-c922-11eb-892a-224f5b66ab04.png)
