### ISSUE TITLE
The Dancing Rune Spell for Blood DK

### ISSUE THREAD

**Issue by AhmedCllyde** [WoWManiaUK/Redemption#4796]
**Links:**

**What is Happening:**
The Dancing Rune spell is not doing its proper damage it should,  making blood dk dps undesirable in raids, everyone agree that it's not doing the proper damage it should.
**What Should happen:**
It should do its proper damage, apperently the "weapon" as many people speculate counts as a pet and there for does less damage than the player, and this is not how it should be.

**Comment by jeyrella** [comment]
This is already covered in #2557 / #2882 as "confirmed - can't fix"; if @Keader reviews and finds it can now be (core has been developed?) then we should re-open one of those instead of creating this as new.

**Comment by Keader** [comment]
nope, same state
