### ISSUE TITLE
[quest] Fletcher's Lost and Found

### ISSUE THREAD

**Issue by Sierbahnn** [WoWManiaUK/Redemption#4797]
**Links:**
https://wotlkdb.com/?quest=13571

**What is Happening:**
The questgiver window opens, with no text or objectives. 

**What Should happen:**
The window should open reading the text of the quest, listing the objectives.

**Comment by jeyrella** [comment]
Does this one even have objectives?  I thought it was simply a turn-in.
See here
https://kaliope.files.wordpress.com/2009/01/ck-kungalooshmats.jpg

**Comment by Sierbahnn** [comment]
Yes, but that text does not appear either.

*** Rasmus Strand 

    On Wednesday, July 29, 2020, 8:38:47 PM GMT+2, jeyrella <notifications@github.com> wrote:  
 
 


Does this one even have objectives? I thought it was simply a turn-in.
See here
https://kaliope.files.wordpress.com/2009/01/ck-kungalooshmats.jpg

**Comment by Rushor** [comment]
works fine https://i.imgur.com/6i4kmgM.jpg

make sure to delete the cache, use engish client and use the wowmania client up to date :)

**Comment by Rushor** [comment]
oh wait now i see the issue https://i.imgur.com/BssgfvS.jpeg

**Comment by Rushor** [comment]
this is limited by core side. anyway added the description now

**Comment by Rushor** [comment]
remember to delete cache before testing :)

**Comment by jeyrella** [comment]
Looks good here
![image](https://user-images.githubusercontent.com/46089380/88913541-08378500-d259-11ea-83c7-fc4f57af6eb5.png)
