### ISSUE TITLE
[quest] Medallion of Faith

### ISSUE THREAD

**Issue by Sierbahnn** [WoWManiaUK/Redemption#4798]
**Links:**
https://classic.wowhead.com/quest=5122/the-medallion-of-faith

**What is Happening:**
The quest opens with no text and no objectives.

**What Should happen:**
The window should contain the text of the quest listing its objectives.

**Comment by Rushor** [comment]
core issue. i can only add the initital text in this case

**Comment by Rushor** [comment]
remember to delete cache before testing :)
