### ISSUE TITLE
[Item] Solar Spirehawk Tooltip Mistake

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#4799]
**Links:** https://www.wow-mania.com/armory/?item=116771
https://wow-mania.com/forum/viewtopic.php?f=13&t=22

**What is Happening:** The tooltip for the custom mount [Solar Spirehawk](https://www.wow-mania.com/armory/?item=116771) mentions it can fly in azeroth, but it actually cannot.

**What Should happen:** As the forum flying mount list indicates, this mount should not be able to fly in azeroth and should have its tooltip updated to reflect so in order to prevent disappointed buyers.

**Comment by wow-mania** [comment]
Fixed. Needs clearing cache.

**Comment by jeyrella** [comment]
![image](https://user-images.githubusercontent.com/46089380/89280028-fa5e7700-d63f-11ea-99ea-440a75f65b4c.png)
