### ISSUE TITLE
unable to interact with quest NPC

### ISSUE THREAD

**Issue by amvsda** [WoWManiaUK/Redemption#4800]
**Links:**
https://www.wowhead.com/quest=24879/blood-quickening

**What is Happening:**
After completing the quest, noone in raid was able to interact and talk to Minchar and get the reward

**What Should happen:**

talk with the NPC and get reward

**Comment by Rushor** [comment]
Is this Happening to anyone else?

**Comment by Rushor** [comment]
the questender for the quest is npc=38551 not minchar https://www.wowhead.com/npc=38551/alrin-the-agile
