### ISSUE TITLE
Raging Flames inmune to Fire damage/Explosive Shot

### ISSUE THREAD

**Issue by crulinjr** [WoWManiaUK/Redemption#4801]
https://www.wowhead.com/npc=30847/raging-flame#drops

How is it working: These NPCs are inmune to fire damage. 

How it should work: They should NOT be inmune to fire damage.

**Comment by Rushor** [comment]
Will check

**Comment by Rushor** [comment]
https://www.wowhead.com/npc=30847/raging-flame#comments:id=872861:reply=139326

452994 on 2009/12/25 (Patch 3.3.0)
They ARE immune to fire spells.
