### ISSUE TITLE
[NPC]  Tactical Officer Ahbramis shows quest available even when there is none - NPC 31153 / Wintergrasp weekly quests missing

### ISSUE THREAD

**Issue by jeyrella** [WoWManiaUK/Redemption#4802]
**Links:**
https://wow-mania.com/armory/?npc=31153
https://wow-mania.com/armory/?quest=13538

**What is Happening:**
When Horde hold Wintergrasp, Tactical Officer Ahbramis shows quest available even when there is none.
![image](https://user-images.githubusercontent.com/46089380/88909930-a1fc3380-d253-11ea-8ec9-dc8c59acd0ec.png)
(In this instance, Victory in Wintergrasp is not complete)

Probably some condition around quest "Southern Sabotage" https://wow-mania.com/armory/?quest=13538 is missing.

**What Should happen:**
If there are no quests available, "!" should not be shown.

**Comment by svijetlo** [comment]
![WoWScrnShot_073020_122731](https://user-images.githubusercontent.com/61908373/88912784-163cd400-d260-11ea-98df-af9c95dabc28.jpg)

**Comment by Rushor** [comment]
try now, but i cannot change more than that

**Comment by svijetlo** [comment]
still same you take quest mark ! is still there if you cant change it i dont care visual thing not game braking , can confuse ppl a bit

**Comment by Rushor** [comment]
okay more updates

those are the conditions to see the quests now https://i.imgur.com/yZYqnPh.jpg

"Quest mark for Alliance quest 'A Rare Herb' (attackers) is available if Wintergrasp is held by Horde"),
"Alliance quest 'A Rare Herb' (defenders) is available if Wintergrasp is held by Alliance"),
"Quest mark for Alliance quest 'A Rare Herb' (defenders) is available if Wintergrasp is held by Alliance"),
"Horde quest 'Healing with Roses' (defenders) is available if Wintergrasp is held by Horde"),
"Quest mark for Horde quest 'Healing with Roses' (defenders) is available if Wintergrasp is held by Horde"),
"Horde quest 'Healing with Roses' (attackers) is available if Wintergrasp is held by Alliance"),
"Quest mark for Horde quest 'Healing with Roses' (attackers) is available if Wintergrasp is held by Alliance"),
"Alliance quest 'Bones and Arrows' (defenders) is available if Wintergrasp is held by Alliance"),
"Quest mark for Alliance quest 'Bones and Arrows' (defenders) is available if Wintergrasp is held by Alliance"),
"Alliance quest 'Bones and Arrows' (attackers) is available if Wintergrasp is held by Horde"),
"Quest mark for Alliance quest 'Bones and Arrows' (attackers) is available if Wintergrasp is held by Horde"),
"Horde quest 'Bones and Arrows' (defenders) is available if Wintergrasp is held by Horde"),
"Quest mark for Horde quest 'Bones and Arrows' (defenders) is available if Wintergrasp is held by Horde"),
"Horde quest 'Bones and Arrows' (attackers) is available if Wintergrasp is held by Alliance"),
"Quest mark for Horde quest 'Bones and Arrows' (attackers) is available if Wintergrasp is held by Alliance"),
"Alliance quest 'Fueling the Demolishers' (defenders) is available if Wintergrasp is held by Alliance"),
"Quest mark for Alliance quest 'Fueling the Demolishers' (defenders) is available if Wintergrasp is held by Alliance"),
"Alliance quest 'Fueling the Demolishers' (attackers) is available if Wintergrasp is held by Horde"),
"Quest mark for Alliance quest 'Fueling the Demolishers' (attackers) is available if Wintergrasp is held by Horde"),
"Horde quest 'Fueling the Demolishers' (defenders) is available if Wintergrasp is held by Horde"),
"Quest mark for Horde quest 'Fueling the Demolishers' (defenders) is available if Wintergrasp is held by Horde"),
"Horde quest 'Fueling the Demolishers' (attackers) is available if Wintergrasp is held by Alliance"),
"Quest mark for Horde quest 'Fueling the Demolishers' (attackers) is available if Wintergrasp is held by Alliance"),
"Alliance quest 'Warding the Warriors' (defenders) is available if Wintergrasp is held by Alliance"),
"Quest mark for Alliance quest 'Warding the Warriors' (defenders) is available if Wintergrasp is held by Alliance"),
"Alliance quest 'Warding the Warriors' (attackers) is available if Wintergrasp is held by Horde"),
"Quest mark for Alliance quest 'Warding the Warriors' (attackers) is available if Wintergrasp is held by Horde"),
"Horde quest 'Jinxing the Walls' (attackers) is available if Wintergrasp is held by Alliance"),
"Quest mark for Horde quest 'Jinxing the Walls' (attackers) is available if Wintergrasp is held by Alliance"),
"Horde quest 'Warding the Walls' (defenders) is available if Wintergrasp is held by Horde"),
"Quest mark for Horde quest 'Warding the Walls' (defenders) is available if Wintergrasp is held by Horde"),
"Horde quest 'Stop the Siege' (defenders) is available if Wintergrasp is held by Horde"),
"Quest mark for Horde quest 'Stop the Siege' (defenders) is available if Wintergrasp is held by Horde"),
"Alliance quest 'Stop the Siege' (defenders) is available if Wintergrasp is held by Alliance"),
"Quest mark for Alliance quest 'Stop the Siege' (defenders) is available if Wintergrasp is held by Alliance"),
"Alliance quest 'Defend the Siege' (attackers) is available if Wintergrasp is held by Horde"),
"Quest mark for Alliance quest 'Defend the Siege' (attackers) is available if Wintergrasp is held by Horde"),
"Horde quest 'Defend the Siege' (attackers) is available if Wintergrasp is held by Alliance"),
"Quest mark for Horde quest 'Defend the Siege' (attackers) is available if Wintergrasp is held by Alliance"),
"Alliance quest 'Southern Sabotage' is available if Wintergrasp is held by Alliance"),
"Quest mark for Alliance quest 'Southern Sabotage' is available if Wintergrasp is held by Alliance"),
"Horde quest 'Toppling the Towers' is available if Wintergrasp is held by Horde"),
"Quest mark for Horde quest 'Toppling the Towers' is available if Wintergrasp is held by Horde");

**Comment by jeyrella** [comment]
@Aristo14 for the notes, "Wintergrasp: weekly quests now only available when your faction holds Wintergrasp".

**Comment by svijetlo** [comment]
![WoWScrnShot_073020_184004](https://user-images.githubusercontent.com/61908373/88949917-325a6880-d294-11ea-884f-9473ff13c924.jpg)

**Comment by jeyrella** [comment]
Can you check again pls @Rushor 
Seems did not get applied on PTR?
![image](https://user-images.githubusercontent.com/46089380/89458687-553ac000-d75f-11ea-892a-f29d8dbe51ed.png)

**Comment by jeyrella** [comment]
Also appears to be having the effect that some quests are not available at all on live when faction-owned.  
Yet on PTR they are all available irrrespective of which side owns.

Need to check exactly what has been pushed live for this one please

**Comment by Rushor** [comment]
all condition are on prt again, if anything was missing, pls check

**Comment by jeyrella** [comment]
This one is missing on PTR
"Alliance quest 'Fueling the Demolishers' (defenders) is available if Wintergrasp is held by Alliance"),
"Quest mark for Alliance quest 'Fueling the Demolishers' (defenders) is available if Wintergrasp is held by Alliance"),
![image](https://user-images.githubusercontent.com/46089380/90332379-384e8a00-dfb4-11ea-9376-5e92e536ea6b.png)

**Comment by jeyrella** [comment]
On Horde side, Vieron Blazefeather in the camp does not offer quest when held by Alliance, although the quest mark is active.

"Horde quest 'Bones and Arrows' (attackers) is available if Wintergrasp is held by Alliance"),
"Quest mark for Horde quest 'Bones and Arrows' (attackers) is available if Wintergrasp is held by Alliance"),

![image](https://user-images.githubusercontent.com/46089380/90332613-3ede0100-dfb6-11ea-80bb-7273eb0819c2.png)
Others seem fine

**Comment by Rushor** [comment]
This is the only one that is bugged then?

**Comment by jeyrella** [comment]
Two.

"Alliance quest 'Fueling the Demolishers' (defenders) is available if Wintergrasp is held by Alliance"),
"Quest mark for Alliance quest 'Fueling the Demolishers' (defenders) is available if Wintergrasp is held by Alliance"),

"Horde quest 'Bones and Arrows' (attackers) is available if Wintergrasp is held by Alliance"),
"Quest mark for Horde quest 'Bones and Arrows' (attackers) is available if Wintergrasp is held by Alliance"),

**Comment by Rushor** [comment]
this is really a strange issue

**Comment by Rushor** [comment]
disables are the reason! will change that

**Comment by Rushor** [comment]
okay both conditions fixed now.

**Comment by jeyrella** [comment]
Fixed :)
![image](https://user-images.githubusercontent.com/46089380/90489718-948ce780-e135-11ea-8a63-04d2750e004c.png)
![image](https://user-images.githubusercontent.com/46089380/90489952-ed5c8000-e135-11ea-952a-7987c7e58a14.png)
