### ISSUE TITLE
[NPC] Sorceress Kaylana double spawn

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#4804]
**Links:** https://www.wowhead.com/npc=31051/sorceress-kaylana

**What is Happening:** [Sorceress Kaylana](https://www.wowhead.com/npc=31051/sorceress-kaylana) currently spawns in double in the Wintergrasp fortress while Alliance controls it. 

See screenshot where both entities of the same NPC are marked.
![WoWScrnShot_073020_192737](https://user-images.githubusercontent.com/34783736/88984244-1a3a1780-d29b-11ea-8634-7b27068b55b6.jpg)

**What Should happen:** Sorceress Kaylana isn't that powerful of a mage, and shouldn't have a permanent carbon-copy of herself.

**Comment by Rushor** [comment]
Good joke xD

**Comment by Rushor** [comment]
useless copy removed

**Comment by jeyrella** [comment]
![image](https://user-images.githubusercontent.com/46089380/89129225-9333ac00-d4f3-11ea-9552-17b1b740232d.png)
