### ISSUE TITLE
Grizzly Hills Arena glitches

### ISSUE THREAD

**Issue by chadwrd** [WoWManiaUK/Redemption#4805]
**Links:**

**What is Happening:**
Quest received for the Arena, and after each fight - you dont get credit for kills. GM Brontes watched. It happens on almost every fight, having to repeat the fight multiple times (between 1-3 times for me) before you can get credit for kill.s This is in Conquest hold and seems to affect all fights in the pit. 

**What Should happen:**

**Comment by chadwrd** [comment]
Sorry just wanted to add - i was unable to complete the final leg of the chain in the fighting pit: The Conquest Pit: Final Showdown. Repeating it 3 times and still did not get credit.

**Comment by Rushor** [comment]
Will check that

**Comment by Rushor** [comment]
credit should alays been given now

**Comment by jeyrella** [comment]
Retested in PTR following the glitch, seems ok.
