### ISSUE TITLE
[Boss/NPC] Lord Marrowgar's Bone Spikes

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#4807]
**Links:** https://www.wow-mania.com/armory/?npc=36619
https://www.wow-mania.com/armory/?spell=70826
https://www.wow-mania.com/armory/?spell=53276

**What is Happening:** The [Bone Spikes](https://www.wow-mania.com/armory/?npc=36619) spawned on players during the Lord Marrowgar encounter after he casts [Bone Spike Graveyard](https://www.wow-mania.com/armory/?spell=70826) can be [death gripped](https://www.wow-mania.com/armory/?spell=53276).

**What Should happen:** Digging through retail wotlk guides, videos and forums, it shows that Bone Spikes should not be affected by Death Grip, and that players should focus on killing them quickly, especially if they are located in a poor position.

**Comment by Keader** [comment]
can you post a proof?

**Comment by Keader** [comment]
fix is ready, i just need a proof to send 👍

**Comment by jeyrella** [comment]
@Keader pls see the (lengthy!) discussion in dev-tester discord channel - has been decided this is one of those utterly obvious tactical things that if it were not true, there would be some video or some mention of it in guides _somewhere_.   As it is, it's entirely void, so inference is it wasn't possible.

**Comment by jeyrella** [comment]
in other words, the very absoence of it EVERYWHERE is the proof itself

**Comment by Keader** [comment]
ok, sending tomorrow morning.
ty

**Comment by bLeyaa** [comment]
Ah nice, i didn't  report this cuz i couldn't find stuff to prove it either. Good call!

**Comment by bLeyaa** [comment]
Oh, I almost forgot... This rule should be added to the Big Ooze as well from Rotface encounter.

**Comment by svijetlo** [comment]
YOU SHELL NOT GRIP XD
