### ISSUE TITLE
[Quest] Bodyguard for Hire/Gizelton Caravan

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#4809]
**Links:** https://classic.wowhead.com/quest=5943/gizelton-caravan
https://classic.wowhead.com/quest=5821/bodyguard-for-hire
https://classic.wowhead.com/npc=11625/cork-gizelton#comments
https://classic.wowhead.com/npc=11626/rigger-gizelton#starts
https://classic.wowhead.com/quest=5943/gizelton-caravan#screenshots:id=29783

**What is Happening:** The caravan mechanic works fine, but if you accept any of the 2 quests ([Bodyguard for Hire](https://classic.wowhead.com/quest=5821/bodyguard-for-hire)/[Gizelton Caravan](https://classic.wowhead.com/quest=5943/gizelton-caravan)) the first one while heading south, and the second while heading back north. 

The issue is the following: After taking either of the escort quests, the initial quest giver moves much faster than the other 34escortees (the other goblin and 3 Caravan Kodos). This leads to the caravan eventually falling far behind the quest NPC, making the quest impossible to do. You either abandon the caravan, which eventually just flags the quest as failed (possibly from going out of range of the "quest area", or you stay with it and abandon the faster NPC, causing him to dies on his own ahead of you, and also failing the quest. Trying to go back and forth between the 2 groups also causes the quest to eventually fail by itself.

The issue might be related to their change in movement speed during and outside of the quest.

> During the "escort" leg of the trip both direction, they move more slowly. Otherwise they move at run speed.
Timed 09/08/2019.

**What Should happen:** The caravan should have all of its members moving at the same speed, allowing players to follow them and protect them along the road.

**Comment by Rushor** [comment]
will increase the speed

**Comment by Rushor** [comment]
speed increased on ptr check it out :)

**Comment by jeyrella** [comment]
This is some kind of odd interaction due to recent changes then, since this used to work just fine (I spent hours correcting these in #4283 ...)

**Comment by Rushor** [comment]
actually i saw that follow bug even before #4283 sometimes

**Comment by jeyrella** [comment]
Ok I did Bodyguard 3 times and the return Gizelton quest twice, seemed to work.
https://youtu.be/vPLNEuADNDE
Given how long this one takes I don't really have the patience to do more than that :D

The minor comments I do have are that 
for Bodyguard for hire, the kodos surround the questgiver so it's difficult to see
The ambushers don't attack the caravan, but I guess when at level the ambushers WILL attack the player, so I think this is fine
Both of these are minor and I don't think need further attention really.

**Comment by NightSeekerr** [comment]
This still doesn't work. The 3 kodos stay behind and barely move. If you stay with the 2 goblins the quest eventually fails.

**Comment by jeyrella** [comment]
@Rushor Regressed/reverted/not applied - not sure which.

**Comment by wow-mania** [comment]
everything was applied

**Comment by Rushor** [comment]
the kodos never attack right?

**Comment by NightSeekerr** [comment]
The kodos attack and bug out after the first wave of mobs. Here's what happens after the 1st wave, the quest-giver (Star) runs ahead, while the 3 kodos and the other goblin start acting retarded and barely move:





![WoWScrnShot_080620_230334](https://user-images.githubusercontent.com/30464528/89577504-71ab2b00-d839-11ea-85d4-694fe2a30458.jpg)
![WoWScrnShot_080620_230339](https://user-images.githubusercontent.com/30464528/89577529-7d96ed00-d839-11ea-9b97-b041eafa2fbe.jpg)

**Comment by Rushor** [comment]
try now please, the movement generator for the "follow guys" should no longer be broke after each "enterevade" mode aka leaving-combat mode

**Comment by NightSeekerr** [comment]
This is still not fixed. The kodos continue to stay far behind the goblins. I somehow managed the complete the "Gizelton Caravan" quest, but the "Bodyguard for Hire" one still fails.

**Comment by Brazier1** [comment]
I can confirm this issue still occuring. Gm Divigrac was kindly to run allong a couple of times. He resetted the npc Cork by killing him and even resetting all of them. I've used the launcher and deleted my cache before we started.

**Comment by jeyrella** [comment]
Confirmed.  It seeems that if the kodos get into combat, they slow to a crawling speed once combat ends, whereas Cork and Rigger run ahead at full speed.  
This means the quest fails as they get far ahead of the kodos.

**Comment by wow-mania** [comment]
There is no regression here. Either it works or it never did.

**Comment by jeyrella** [comment]
This is true - it looks like this was not properly fixed/tested on the last time.  Will work with @Rushor for this.

**Comment by Rushor** [comment]
this is a general formation issue, pretty sure it happens with all kind of creature formations

**Comment by Rushor** [comment]
those following guard and the kodos and more complicated than beeing useful. They will no longer change the faction and should not attack the hostile enemies. Hope that helps

**Comment by svijetlo** [comment]
![WoWScrnShot_102720_164514](https://user-images.githubusercontent.com/61908373/97330347-6dab0a00-1878-11eb-8f6a-025aecb29f5f.jpg)
![WoWScrnShot_102720_164522](https://user-images.githubusercontent.com/61908373/97330358-713e9100-1878-11eb-94d0-514bad771f81.jpg)
![WoWScrnShot_102720_164540](https://user-images.githubusercontent.com/61908373/97330368-74d21800-1878-11eb-8988-58be829e38e6.jpg)
![WoWScrnShot_102720_164554](https://user-images.githubusercontent.com/61908373/97330382-77cd0880-1878-11eb-9c35-a850616e425f.jpg)
![WoWScrnShot_102720_164603](https://user-images.githubusercontent.com/61908373/97330388-7ac7f900-1878-11eb-87db-864898cca171.jpg)
![WoWScrnShot_102720_164628](https://user-images.githubusercontent.com/61908373/97330397-7d2a5300-1878-11eb-8acf-b4c9d28bdd0c.jpg)
![WoWScrnShot_102720_164637](https://user-images.githubusercontent.com/61908373/97330409-7f8cad00-1878-11eb-92a7-694ebe00a24a.jpg)
![WoWScrnShot_102720_164648](https://user-images.githubusercontent.com/61908373/97330419-82879d80-1878-11eb-8f36-07744d184417.jpg)
quest bodyguard for hire now work great all move tighter speed is good , tehy do not agro mobs on side mobs that spawn and attack them after killed caravan moves on togather

**Comment by Brazier1** [comment]
@jeyrella @Rushor . I can confirm it is fixed. I was able to complete both quest. The kodo's followed 'Cork' Properly. I know it is a time consuming quest to investigte and test, so tyvm for doing so!
