### ISSUE TITLE
Unchained Magic - Instability stack application timing

### ISSUE THREAD

**Issue by bLeyaa** [WoWManiaUK/Redemption#4813]
**Links:** https://www.wow-mania.com/armory/?spell=69766

**What is Happening:** Currently, if the spell has travel time (bolts / wrath / haunt and similar), the stacks are applied only once they reach Sindragosa/tomb. 

**What Should happen:** Stacks should be applied on cast.

**Comment by bLeyaa** [comment]
For reference: 
https://youtu.be/Lp0vhItW9wk?t=184 (cast bar is at his name top left, debuffs below the name)

https://youtu.be/bevQZmTwWjc?t=222

**Comment by Keader** [comment]
We dont have support for this in current proc system xd

**Comment by bLeyaa** [comment]
Ughhh... that's a shame... Classes like balance druids are cucked on it with wrath, as much as affliction warlocks or even mages -_-
