### ISSUE TITLE
[Quest] A Feast of Souls

### ISSUE THREAD

**Issue by bLeyaa** [WoWManiaUK/Redemption#4815]
**Links:** https://www.wow-mania.com/armory/?quest=24547

**What is Happening:** Certain mobs not being counted towards the quest. Such as Suppressors, Sindragosa event mobs, pre-Sindragosa trash.

**What Should happen:** They should all be tagged and award a soul count towards the quest.

Few things to note:

Sindragosa event: small spiders should remain as they are, this applies to the big 2 types coming down and both frostwarden types.
Pre-Sindragosa event: From what i've seen all the whelps and two frostwardens should be giving, but not rimefang and spinestalker.
Valithria: all mobs except for the worms - atm i believe the zombies are being tagged but not awarding after exploding (should be checked)

P.S. There is also this weird behavior where if you taunt the mob you've tagged, it ends up giving 4-5-6 souls for a single kill instead of 1.

**Comment by bLeyaa** [comment]
https://youtu.be/kopqIH_T8hc?t=262

From the timestamp above up until Sindragosa u can see the mentioned points in the OP.

**Comment by Rushor** [comment]
Valithria: all mobs except for the worms - atm i believe the zombies are being tagged but not awarding after exploding (should be checked) - this will not be fixed for now since those mobs are very special. 

The other mobs will be fixed

**Comment by Rushor** [comment]
sindragosa big gaunlet trash and the trash just in front on sindragosa now give the credits.

valithria trash already works

**Comment by bLeyaa** [comment]
Can you please confirm for Suppressors as well, from what i remember they were not tagged at all

**Comment by Rushor** [comment]
can you give me the npc id of them?

**Comment by Rushor** [comment]
supressor also added now

**Comment by bLeyaa** [comment]
Should be 37863

Thanks

**Comment by Zanguin-ManiaTester** [comment]
Zombies still seem to bug. One Nerubian in the Sindy gauntlet seems to not reward any credit.

https://youtu.be/nySbrYl7wlk

Labeling improvement?

**Comment by Rushor** [comment]
as i said zombies will not be fixed since their script is to complicated for that.

which sindy nerubian id or name exactly? you must make sure that the debuff from the sword was applied on the trash creature before killing

**Comment by Zanguin-ManiaTester** [comment]
I just noticed on 2 separate occasions that one of the Nerubians in the gauntlet, didn't give any credit, one of the darker ones. Little occupied at the moment, so will be looking it up later

**Comment by svijetlo** [comment]
works fine now if there is some small ones that dont reveord soul it can be made to new post all i killed gave soul apart form zombies but who care , not like you will miss 5 solus to get it

**Comment by bLeyaa** [comment]
@Rushor what about the taunting  part?

**Comment by Rushor** [comment]
Cannot be done atm
