### ISSUE TITLE
Recklessness & Cleave / Whirlwind 

### ISSUE THREAD

**Issue by bLeyaa** [WoWManiaUK/Redemption#4817]
**Links:** http://www.wow-mania.com/armory?spell=1719

**What is Happening:** Recklessness currently has a weird behavior, where Cleave will take 1 stack even if 3 targets are hit and Whirlwind will take 2 stacks no matter how many target are hit. Additionally, if there is one stack remaining and Whirlwind is used it will not crit for all the targets (unless your crit / rng does it) and Cleave will still crit on all hits even with 1 stack.

**What Should happen:** Recklessness stacks should be removed per target hit. That means that if you have 3 stacks and Cleave hits 2 targets you should be left with 1 stack. However, if you with that one stack use Whirlwind on 4 targets, all 8 hits should be critical. Due to the mechanic of whirlwind where 1 target is hit twice, it should count targets hit and not attack swings... If that makes sense :) Videos below should help

https://youtu.be/MOyfG-s3Gj0?t=518
1. Using Reck;
2. Using Heroic Strike -- Crit, one charge down;
3. Using Whirlwind -- eight Crits, both remaining charges expended

https://www.youtube.com/watch?v=-tm9-1PatKg&feature=youtu.be&t=307
while low-quality, shows him:
1. Using Reck;
2. Using WW -- two hits (2 targets), from three charges down to one left.

**Comment by Keader** [comment]
https://github.com/TrinityCore/TrinityCore/issues/15529

That's a perfect example of: "we need proc rewrite fixes" hahaha
I realy want port it y.y

**Comment by jeyrella** [comment]
@bLeyaa now looks rectified with the changes shceduled incoming on #4846 soon™
