### ISSUE TITLE
[Instance] Essence of Wintergrasp buff not applied in ICC 5-man dungeons

### ISSUE THREAD

**Issue by jeyrella** [WoWManiaUK/Redemption#4818]
**Links:**
Buff:  https://wow-mania.com/armory/?spell=57940
Missing from Dungeons:
https://wow-mania.com/armory/?zone=4813
https://wow-mania.com/armory/?zone=4809
https://wow-mania.com/armory/?zone=4820

**What is Happening:**
Essence of Wintergrasp buff is missing from the ICC dungeons  (Pit of Saron, Forge of Souls, Halls of Reflection), and thus Stonekeeper's Shards do not drop when boss is killed when faction holds Wintergrasp.
https://wow-mania.com/armory/?spell=57940
https://youtu.be/Ah3jJlmIGHk

**What Should happen:**
ICC 5-man dungeons should be included.  These videos clearly show the buff in the upper right for each of the three dungeons.
https://www.youtube.com/watch?v=6eeMlVoOi8s
https://www.youtube.com/watch?v=BhEVYBZXmok
https://www.youtube.com/watch?v=hr47csbvPpY

**Comment by jeyrella** [comment]
Also missing from Azjol Nerub
https://wow-mania.com/armory/?zone=3477

**Comment by Rushor** [comment]
will check all

**Comment by Rushor** [comment]
fixed

**Comment by jeyrella** [comment]
- [ ] PoS
- [ ] FoS
- [ ] HoR
- [ ] AN
- [ ] ToC

**Comment by jeyrella** [comment]
Retested in PTR following the possible glitch, seems still fine.
