### ISSUE TITLE
[Spell] Judgement of Light vs Avenging Wrath and Divinity

### ISSUE THREAD

**Issue by Keader** [WoWManiaUK/Redemption#4825]
**What is Happening:**

Checking warcraft logs, we notice that Judgement of Light should be affect to more 2 talents.

1 - Avenging wrath : Add 20% of judgement heal, even if casted for other paladin. But only affect players with avenging wrath active, the rest of players get normal heal

2 - Divinity: can only affect the judgement caster, he got more heal, but the rest of players get normal heal.

**What Should happen:** Both talents should affect judgement of light, following the rules.

**Comment by svijetlo** [comment]
GOD damn thx for this :D i know smt is not perfectly right but could not pinpoint it
