### ISSUE TITLE
[Paladin] Seal of Command range

### ISSUE THREAD

**Issue by Keader** [WoWManiaUK/Redemption#4826]
**What is Happening:** 

Seal of command must hit targets until 16y +-
**Right now, it only hit targets in melee range (chain damage)**
proof: https://youtu.be/e4ZkhrwwGdw?t=401
In 6:45, he attack dummy and still hit other dummy located in 15.2y away

**Comment by svijetlo** [comment]
true good you made this i can cionfirm this was existing for some time but i nver bother to report as you do not use soc as much
