### ISSUE TITLE
[NPC] Vale Screecher Missing

### ISSUE THREAD

**Issue by billykitty** [WoWManiaUK/Redemption#4827]
**Links:**
https://www.wowhead.com/npc=5307
https://www.wowhead.com/quest=3520

**What is Happening:**
There used to be many Vale Screechers spawning at The Forgotten Coast in Feralas near the dock to Feathermoon Stronghold but now there are none.  They are needed for the quest "Screecher Spirits".

**What Should happen:**
Vale Screechers should spawn at The Forgotten Coast in Feralas near the dock to Feathermoon Stronghold.

**Comment by jeyrella** [comment]
Respawn time should be 5 mins.
![image](https://user-images.githubusercontent.com/46089380/89226701-4bd11c80-d5d4-11ea-8c8a-87ca0b10fc59.png)
https://wow-mania.com/armory/?npc=5307

Confirmed!  There does indeed seem to be a spawning problem with this NPC.
https://youtu.be/UdqwGltcsHw

This is regression as it is definitely worked in the past.

**Comment by jeyrella** [comment]
@Rushor am hearing rumours about various other Feralas NPCs, shorestriker giants etc.  If you find whats wrong with this one, then if there's an easy way to check other Feralas NPCs for the same issue then please do so.  
If not then I will see if I can start hunting down others manually...

**Comment by jeyrella** [comment]
Hmm.  I came back 30 mins later and it was spawned.   Am wondering if the timer is just off a bit.  Will record the next one and see what the actual spawn time is.

**Comment by jeyrella** [comment]
Ok.  was 7 mins.

![image](https://user-images.githubusercontent.com/46089380/89229595-9e610780-d5d9-11ea-9771-82f35730ead2.png)

Odd, but they do spawn.

**Comment by jeyrella** [comment]
@billykitty 
I just noticed you put:   _Vale Screechers spawning at The Forgotten Coast in Feralas near the dock to Feathermoon Stronghold but now there are none_
That is where they spawned post-Cataclysm.  In WotLK and earlier, THIS is where they spawned:
https://wow-mania.com/armory/?npc=5307

**Comment by billykitty** [comment]
Thanks for checking!
