### ISSUE TITLE
[NPC]  Lost Shandaral Spirit walks inside wall and evades on combat engage

### ISSUE THREAD

**Issue by jeyrella** [WoWManiaUK/Redemption#4828]
**Links:**
This specific spawn of NPC 31231
![image](https://user-images.githubusercontent.com/46089380/89232106-a40d1c00-d5de-11ea-9473-05618772d2fe.png)
https://wow-mania.com/armory/?npc=31231

**What is Happening:**
On engaging combat, this Lost Shandaral Spirit walks straight inside the pillar next to her and evades combat.
https://youtu.be/AM_nzgm3F_4

**What Should happen:**
Should not walk inside the pillar to evade combat!  These wimpish ghosts :D

**Comment by Rushor** [comment]
that is funny :D 

try now, moved him a bit

**Comment by jeyrella** [comment]
Confirmed, she is good now.
![image](https://user-images.githubusercontent.com/46089380/89279443-45c45580-d63f-11ea-972b-27365d767a60.png)

**Comment by jeyrella** [comment]
Retested.  Is fine.
![image](https://user-images.githubusercontent.com/46089380/89514012-3541e580-d7cd-11ea-87d8-534705ffd43a.png)
