### ISSUE TITLE
[NPC]  Alliance Valiants at Argent Tournament ride off the edge onto thin air!

### ISSUE THREAD

**Issue by jeyrella** [WoWManiaUK/Redemption#4830]
**Links:**
Exodar:  https://wow-mania.com/armory/?npc=33562
Darnassus:  https://wow-mania.com/armory/?npc=33559
Gnomeregan:  https://wow-mania.com/armory/?npc=33558
Ironforge:  https://wow-mania.com/armory/?npc=33564
Stormwind:  https://wow-mania.com/armory/?npc=33561

**What is Happening:**
The Valiant mounted riders at the Argent Tournament in the northern ring are all initialised facing directly north.
![image](https://user-images.githubusercontent.com/46089380/89280718-ed8e5300-d640-11ea-8241-170ba30fa9f5.png)

This has the effect that on combat engage, Exodar, Darnassus and Gnomeregan Valiants run directly north through the fence, and out into open air, where the player obviously can't follow.   They then evade combat.

![tournament](https://user-images.githubusercontent.com/46089380/89280914-347c4880-d641-11ea-8bed-50bc7557fb10.png)

Once they have been fought once, they do run back and then face the centre correctly.
![image](https://user-images.githubusercontent.com/46089380/89281310-cdab5f00-d641-11ea-8de2-babf8cfb4948.png)

**What Should happen:**
They should all be initially facing directly towards the centre of the ring
Their pathing should not take them outside of the ring.

**Comment by jeyrella** [comment]
Actually noticed it's also happening at the southern Champions ring too, with the Horde Champions as well as the Alliance - although the impact is less severe as they don't path into mid-air
![image](https://user-images.githubusercontent.com/46089380/89399698-b71d0a80-d70a-11ea-8210-414e0936305b.png)

Regardless, they should still stay within the arena bounds for pathing (Rushor I know you know, just stating for the record)

**Comment by Rushor** [comment]
okay thanks for the info

**Comment by Rushor** [comment]
this is most likely because they forget to set the homeposition back to original state

**Comment by Rushor** [comment]
okay try now pls. they should always move to home spot and set the orientation to the initial position

**Comment by Zanguin-ManiaTester** [comment]
Valiants are placed correctly, though sometimes their pathing messes up and stops them on their way back.
https://youtu.be/2ivmsF-4hCg

**Comment by Rushor** [comment]
okay next try

**Comment by jeyrella** [comment]
![image](https://user-images.githubusercontent.com/46089380/90002203-3f128f80-dc8a-11ea-9529-6e9e7a1fd304.png)

**Comment by jeyrella** [comment]
Need this testing before push to live guys

**Comment by jeyrella** [comment]
![image](https://user-images.githubusercontent.com/46089380/90002626-ce1fa780-dc8a-11ea-875e-a3c3d0fa88ca.png)
![image](https://user-images.githubusercontent.com/46089380/90002657-daa40000-dc8a-11ea-881d-202eb56a2970.png)
![image](https://user-images.githubusercontent.com/46089380/90002766-01623680-dc8b-11ea-8c01-a47cc4d5b67d.png)

**Comment by Rushor** [comment]
one clear reproduction case would be awesome here.

we need a way to make sure that the creatures reset correctly

**Comment by Rushor** [comment]
new possible solution: despawn at end and respawn instantly. should solve all issues. will add this weekend.

**Comment by Oganku** [comment]
They all path to the center upon starting, and despawn and respawn at the correct position after fighting.

**Comment by Rushor** [comment]
awesome!! finally haha
