### ISSUE TITLE
Demonic Pact is not getting reapplied

### ISSUE THREAD

**Issue by Anw990** [WoWManiaUK/Redemption#4831]
**Links:**
https://youtu.be/lRC5Ig5eTVg

**What is Happening:**
When you summon your Pet as a Demon warlock and your pet crits, Demonic pact will be put on everyone in your raid as it should, however it will not refresh after the 20 sec internal CD, even after it falls off it will not be reapplied until you dismiss your pet and summon a new one, that new pet will only put the demonic pact debuff on your raid once, the first time it crits, then never again until you summon a new pet once again.

**What Should happen:**
Every 20 seconds when your pet crits the demonic pact debuff should be reapplied to everyone in your raid.

**Comment by Keader** [comment]
my fault, fixed already.
tomorrow will be on redemption

**Comment by jeyrella** [comment]
was a regresion of https://github.com/WoWManiaUK/Redemption/issues/4819 ?

**Comment by Oganku** [comment]
More like a side effect of the fix. There was no icd before, and now it's sort of infinite.

**Comment by Keader** [comment]
> More like a side effect of the fix. There was no icd before, and now it's sort of infinite.

yeah, something like it.
but it's easy to fix, janitor can execute in red DB tomorrow and reload without restart server :)
