### ISSUE TITLE
[Quest] Reconnaissance Flight - Sholazar Basin - 12671

### ISSUE THREAD

**Issue by jeyrella** [WoWManiaUK/Redemption#4832]
**Links:**
https://wow-mania.com/armory/?quest=12671

**What is Happening:**
The plane no longer responds to up/down controls.  This makes it impossible to control, and thus breaks the quest entirely.  Not completable.

**What Should happen:**
Plane should respond to up/down pitch controls.

**Comment by jeyrella** [comment]
Confirmed by @Zanguin-ManiaTester https://youtu.be/TUEwANzRvRk

**Comment by Rushor** [comment]
if you hit "space" it works, but it is insane fast

**Comment by Rushor** [comment]
okay fixed. you still need to hit "space" to enable up and down movement (similar to this cold-hearted quest in stormpeaks, but it has always been like that)

The insane speed movement after hitting space is fixed now and the initial movement speed for th plane towards the hill has been increased aswell to match retail speed.

**Comment by Zanguin-ManiaTester** [comment]
https://youtu.be/lgNeYxClhIw

Worked fine this time around, was not bad speedwise controlling it.

**Comment by Rushor** [comment]
So fix confirmed?

**Comment by Zanguin-ManiaTester** [comment]
Well I mean, I didn't feel like there was anything wrong with the quest, so I suppose :)

**Comment by Rushor** [comment]
thanks for testing, the speed should be ok in all quest situations now

**Comment by jeyrella** [comment]
> but it has always been like that)

what, hang on. Nope, it isn't, never needed to press space before.
Besides, pressing space isn't blizzlike for either quest.  Players aren't expecting to have to do that.  Still causes confusion even today with Coldhearted.  Adding it to this quest is a real downgrade.

Would love to know _why_ pressing space is now required, since it wasn't before....

**Comment by Rushor** [comment]
Can you try to talk with keader about that? And may open a Ticket then. It is some deep core issue

**Comment by jeyrella** [comment]
keader is on other project right now, will note & keep in mind for when that's done
