### ISSUE TITLE
[NPC] Shore Striders missing

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#4833]
**Links:** https://wow-mania.com/armory/?npc=5359
https://classic.wowhead.com/npc=14637/zorbin-fandazzle#starts

**What is Happening:** The [Shore Strider](https://wow-mania.com/armory/?npc=5359) giants that are involved in [Zorbin Fandazzle's](https://classic.wowhead.com/npc=14637/zorbin-fandazzle#starts) quests are currently on vacation and cannot be found anywhere along the coast.

**What Should happen:** Giants should sparsely populate the western coast of Feralas, allowing players to zap them to Zorbin's greatest pleasure.

**Comment by Rushor** [comment]
added spawns for them to the game

**Comment by jeyrella** [comment]
Can you check again pls, nothing there, but spent 10 mins and nothing spawned.   manual .respawn did nothing

**Comment by Rushor** [comment]
they should be there

try:
 .go c id 5359

**Comment by jeyrella** [comment]
![image](https://user-images.githubusercontent.com/46089380/89936373-72620980-dc0b-11ea-9b3e-e1bfe96e4e86.png)

**Comment by Rushor** [comment]
they are there now https://i.imgur.com/87RHaxe.jpg

**Comment by jeyrella** [comment]
see #4857 seems to be not fixed.  will test once major project done, for now low prio as other quests are available

**Comment by Rushor** [comment]
so the creatures are missing or quest is not completable?

**Comment by jeyrella** [comment]
Creatures are missing.  Will check it again tomorrow.

**Comment by Rushor** [comment]
added them again. i think this happened because we work on 2 different kind of ptrs atm
