### ISSUE TITLE
Quest item drop rates

### ISSUE THREAD

**Issue by Atheros01** [WoWManiaUK/Redemption#4835]
**Links:**

**What is Happening:**
ive been questing in the game for a while now, and this issue is more consistent in some of the northrend quests than in lower level zones, although a few have been troublesome (looking at you helcular's rod). It seems that the drop rates for some quest items which ought to be fairly high are instead abysmally low. For example, i killed literally hundreds of shoveltusks trying to get ligaments to drop for a quest (needed 6) and only got 3 after all that time. I checked online to see what the drop rate was, and it proclaimed around 60%. I promptly abandoned the quest. The quest im currently on (Rivenwood Captives) has me opening cocoons in order to free some dudes (requires 7 freed), and the game seems to have stalled out at 3, refusing to spawn any more friendly captives and instead only spawning empty cocoons, or those filled with hostile mobs. I dont know what the problem is, but its starting to tick me off that im putting in so much effort for quests that wind up being broken.

**What Should happen:**
Please fix it so that quest items/objectives spawn at a proper rate for these mentioned things.

**Comment by jeyrella** [comment]
Need specifics.  Drop rates are not set generically. 
So far, the ones you have mentioned are blizzard rates and are simply RNG.  I did shoveltusk quest literally today and got it in 8 kills.
