### ISSUE TITLE
Cyclone

### ISSUE THREAD

**Issue by bLeyaa** [WoWManiaUK/Redemption#4836]
**Links:** http://www.wow-mania.com/armory?spell=33786

**What is Happening:** Currently players affected by cyclone can still receive certain buffs. Currently tested with warlock being able to cast void's (pet) sacrifice shield while under cyclone. Also, player can receive riptide and earth shield while in cyclone. Both initial Riptide heal and the hot do not heal the player, but the buff is applied which continues healing once cyclone is done.

**What Should happen:** Invulnerable players should be immune to all buffs while in cyclone, somewhat like when banished.

**Comment by Keader** [comment]
fixed
