### ISSUE TITLE
[Quest] Verog the Dervish

### ISSUE THREAD

**Issue by Rushor** [WoWManiaUK/Redemption#4838]
**Links:**
quest=851

**What is Happening:**
Verog the Dervish can be summoned multiple times on the same spot, if player kill lots of members of him. 

**What Should happen:**
It should only be summoned one Verog the Dervish, not multiple.

**Comment by jeyrella** [comment]
Killed all the Kolkar I could find, could only spawn him once.  Calling this fixed.
![image](https://user-images.githubusercontent.com/46089380/89733174-8e1eb180-da4b-11ea-80fd-97c37d92f172.png)

**Comment by Rushor** [comment]
perfect!
