### ISSUE TITLE
[Quest] Guided by Honor - Adding Post Event

### ISSUE THREAD

**Issue by Rushor** [WoWManiaUK/Redemption#4839]
**Links:**
quest=11289
https://youtu.be/IEf0l00cJEY?t=115
https://wow.gamepedia.com/Cleric_of_the_Crusade
**What is Happening:**
Nothing

**What Should happen:**
Upon rewarding the quest, there should happen this tiny event posted above.

**Comment by jeyrella** [comment]
![image](https://user-images.githubusercontent.com/46089380/89732853-69c1d580-da49-11ea-86df-5dceaf4688d9.png)

**Comment by jeyrella** [comment]
Lovely touch of lore, this one.  Thanks @Rushor
