### ISSUE TITLE
[NPC] Angered Arakkoa Protector - Remove static spawns

### ISSUE THREAD

**Issue by Rushor** [WoWManiaUK/Redemption#4840]
**Links:**
http://web.archive.org/web/20100423195556/www.wowhead.com/npc=21470

**What is Happening:**
They are spawned

**What Should happen:**
-- view-source:http://web.archive.org/web/20100423195556/www.wowhead.com/npc=21470
-- 'Some of the Arakkoa can summon these at low HP, they are pretty worthless...'

Angered Arakkoa Protector should not have any static spawns

**Comment by Zanguin-ManiaTester** [comment]
Found no Angered Arrokoa Protector static spawns, in any of the possible locations with the mobs that can summon them.

**Comment by jeyrella** [comment]
well...  no - cos rushor already removed them right
