### ISSUE TITLE
[Quest] Meat on the Hook - Missing script intro event

### ISSUE THREAD

**Issue by Rushor** [WoWManiaUK/Redemption#4841]
**Links:**
Meat on the Hook quest=12017 https://www.youtube.com/watch?v=hvi715BFxtg

**What is Happening:**
Questcreature instantly spawns

**What Should happen:**
The shark should have an initial path and should then attack after a short time.

**Comment by jeyrella** [comment]
well.  it works, but can we make him swim a bit faster?  like?  50-100% faster?
era-appropriate video to go with yours:  https://www.youtube.com/watch?v=aSJuTb1toLA

**Comment by jeyrella** [comment]
According to Rushor, this is a no.  So, confirmed.
