### ISSUE TITLE
[NPC] Mr. Bigglesworth

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#4842]
**Links:** https://www.youtube.com/watch?v=s2iPehecpZY
https://www.youtube.com/watch?v=farZtXnUsC0
https://wow.gamepedia.com/Mr._Bigglesworth
https://www.wowhead.com/npc=16998/mr-bigglesworth#comments
https://wow.gamepedia.com/Lil%27_Phylactery

**What is Happening:** 

1. Mr. Bigglesworth does not move much, he spawns near (53,53) and barely move more than a yard away from that spot. However, from videos from retail wotlk, we see the cat wander as far as to the center portal.

Furthermore, 

> Mr. Bigglesworth will periodically attack the maggots and roaches that meander around the room.

However at the moment he never moves close enough to get in range to aggro them, and is thus missing his cleaning behavior.

2. The companion pet Lil' KT should eventually aggro Mr. Bigglesworth and fire a frostbolt at him, freezing him and killing him, as can be seen in [the video above](https://www.youtube.com/watch?v=farZtXnUsC0). Currently they both ignore each other though, the interaction is thus missing.

**What Should happen:**

1. Bigglesworth should wander around the center hub inside Naxxramas, attacking critters he encounters.

2. Lil' KT should attack his cat if he lingers near him for too long.

**Comment by Rushor** [comment]
Will fix in the evening

**Comment by Rushor** [comment]
okay Mr. Bigglesworth will wander around now. Mr. Bigglesworth will kill the maggots around it from time to time.

Lil' KT will kill Mr. Bigglesworth from time to time if Lil' KT is close to him.

**Comment by Rushor** [comment]
thanks for the test :D
