### ISSUE TITLE
[Raid] Trial of the Crusader entrance quote

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#4843]
**Links:**

**What is Happening:** Killing the last boss in the Trial of the (Grand) Crusader triggers the dialogue that plays when you first enter the raid. 

It goes something like:
> Welcome to the Trial of the crusader champions! 

**What Should happen:** The beginning quote that triggers when you first enter the raid should not also play upon defeating the final boss.

**Comment by Rushor** [comment]
Will fix in the evening

**Comment by Rushor** [comment]
testable once ptr is up

**Comment by jeyrella** [comment]
No extra event after Anub'Arak.  Full run through:  https://youtu.be/wsK4JhybJcE
