### ISSUE TITLE
[Quest] Weakness To Lightning:  Pet kills do not count towards kill progress - 11896 - Borean Tundra

### ISSUE THREAD

**Issue by vertrek** [WoWManiaUK/Redemption#4844]
**What is Happening:**
When pet gets killing blow, the kill is not counted towards Robots Weakened and Destroyed XX/15.
I put pet on passive and then all kills started counting, not some.

**What Should happen:**
Even if pet gets killing blow, it should count towards the quest goal.

**Comment by jeyrella** [comment]
https://wow-mania.com/armory/?quest=11896

**Comment by vertrek** [comment]
I just realized pet doesnt have electricity buff like I do. But I am still fighting the mob, it is only calculated on killing blow. So I have attacked the mob, I still think it should count towards kill for quest.

**Comment by Rushor** [comment]
Will fix in the evening

**Comment by Rushor** [comment]
okay should work now in all situations with or without pet.

fixed once ptr is up again

**Comment by vertrek** [comment]
Great thanks!

On Aug 10, 2020, at 11:09 PM, Rushor <notifications@github.com> wrote:

﻿
okay should work now in all situations with or without pet.

fixed once ptr is up again
