### ISSUE TITLE
[NEED-TEST] Ported Qaston Proc System

### ISSUE THREAD

**Issue by Keader** [WoWManiaUK/Redemption#4846]
Good morning folks.
With a lot of pleasure, we ported the Qaston proc system to wow mania.
It was implemented by ariel- (ty dude) in TC (2017) and will improve a lot how we fix proc issues.

**Improvements:**

- We can handle with procs using DB now
- spell_proc_event table is useless now, replaced by spell_proc (command .reload spell_proc_events will not work anymore, replaced by .reload spell_proc)
- Now we can control in wich phase of cast spell will proc (on cast, on hit, on finish, etc)
- Now drop charges will work, without stuck anymore.
- Now we can fix any issues related with procs \o/

**Regressions:**

**Yes, like any massive change, we can have some regressions. Normally related with Proc or Drop charge.
So testers need spend some time, testing basic spells of all classes to see if something is not working right now.
Will be great if they can do some bosses of icc, check if nothing break there.**
This system is not in live yet, we will wait testers before send.

"But Keader, if it raise regressions, why you ported it?"
Is easy, because old system dont allow we fix alot of proc spells like (https://github.com/WoWManiaUK/Redemption/issues/4817)
And even adding some new bugs, the new proc system is better. Since 2017 i never touched in any issue impossible to fix with new system.

**Comment by Keader** [comment]
Suggestion for testers: Split it for each class and post here what class are you testing right now.
it avoid that 2 testers , test same thing.

**Comment by Zanguin-ManiaTester** [comment]
Arcane and Fire mage procs seem to work as they should :)

**Comment by jeyrella** [comment]
Druid
- [ ] Resto:
- [ ] Balance:
- [ ] Feral:
- [ ] Bear:
- General

- Hunter
- [ ] MM:
- [ ] BM:
- [ ] SV:
- General

- Mage
- [ ] Fire: @Zanguin-ManiaTester 
- [ ] Frost:
- [ ] Arcane:  @Zanguin-ManiaTester 
- General

- Paladin
- [ ] Retri:
- [ ] Prot:
- [ ] Holy:
- General

- Priest
- [ ] Shadow:  @jeyrella 
- [ ] Disc: @jeyrella 
- [ ] Holy:
- General:

- Rogue
- [ ] Combat:
- [ ] Assa:
- [ ] Subt:
- General

- Shaman
- [ ] Resto:
- [ ] Enh:
- [ ] Ele:
- General

- Warlock
- [ ] Affli:
- [ ] Demo:
- [ ] Destro:
- General

- Warrior
- [ ] FuckProt:
- [ ] Fury:
- [ ] Arms:
- General

**Comment by jeyrella** [comment]
List of issues for @Keader reference - tick off when fixed

- [ ]  mage T10 P2 bonus with missile proc, seems off.

**Comment by jeyrella** [comment]
List of issues for @Keader reference - tick off when fixed

- [ ]  mage T10 P2 bonus with missile proc, seems off.

**Comment by Keader** [comment]
Fixed Mage t10 2p, proccing normally now 👍

**Comment by Zanguin-ManiaTester** [comment]
Retri pala seems normal.

**Comment by svijetlo** [comment]
i em happy to say i have not found problems with rogue,

**Comment by svijetlo** [comment]
@Keader item 50362 / 50363 and 54590 / 54569 are not procking at all , should be prock on hit

**Comment by svijetlo** [comment]
chill to the bone on sindy works fine it procs on melee hits

**Comment by Keader** [comment]
![image](https://user-images.githubusercontent.com/7120913/90151810-8584ee80-dd5d-11ea-86c3-8d7a5e7b1999.png)
i dont got it.
It's proccing on cast, not on hit?
or it should proc on cast, not on hit?

Because if is: "it should proc on cast, not on hit"
it's false. Because it should not proc on overheal. And we just know if spell will cause a heal or overheal in hit phase.

**Comment by jeyrella** [comment]
no, this is misalignment of the checklist.  "proc on DoT" is a header to the items below  (no underline feature so hard to distinguish!)

**Comment by jeyrella** [comment]
Deeathbringer's Will / Sharpened Twilight Scale (50362 / 50363 and 54590 / 54569) are not procking at all , should be prock on hit

**Comment by Keader** [comment]
Ok, fixed a bug that was adding 1000* more cooldown that it should on equiped items.
It should fix Dbw and Sharpened and any other proc item lul

**Comment by svijetlo** [comment]
glad to say Deeathbringer's Will / Sharpened Twilight Scale (50362 / 50363 and 54590 / 54569)  are now procining as intended =)

**Comment by bLeyaa** [comment]
sorry to butt in, just wanted to say i love you Keader :) ♥

**Comment by Keader** [comment]
I tested instability with chain heal, and it give 1 stack instead 4~5
it's proccing on cast, not on hit, like it should 👍

**Comment by svijetlo** [comment]
same i played around with it this morning with dots/hots it is just on cast you gain stack not on on tick or hit

**Comment by Oganku** [comment]
4t10 proc does not reduce global cooldown or slam/execute when you get double charges of Bloodsurge/Sudden Death.

General dps pve warrior issue. Duration doubles correctly and it triggers fine, but you just don't get any gcd reduction. Works fine on live.

**Comment by jeyrella** [comment]
Spriest:  Mind Sear 53022 does not cast.  Nothing happens!  No error displayed.

**Comment by Keader** [comment]
@jeyrella mind sear id is not 53022.
You should never have 53022, it com wrongly using .learn all my class command
just use .unlearn 53022 and it will work fine.
Players will have no access to 53022.

**Comment by Keader** [comment]
Fixed 4t10, test now @Oganku

**Comment by Keader** [comment]
missing bloodsurge issue in https://github.com/WoWManiaUK/Redemption/issues/4846#issuecomment-673009859 zzzz
anyway, test now @Oganku , bloodsurge issue too

**Comment by Oganku** [comment]
Sorry I edited and I forgot to edit the comment.

Will test both tonight. Thanks a lot

**Comment by Oganku** [comment]
Both procs now work perfectly. Thanks @Keader

**Comment by jeyrella** [comment]
Reopening as released to live without full testing.  Reports of untested classes having issues e.g resto druid

**Comment by bLeyaa** [comment]
Please note that Omen of Clarity is not proccing on boomkin at the moment, from any spell casted at all. Speaking to Oganku he could confirm it after testing it, but also noted that on PTR this is not the case. I would be guessing that #4869 fix may have affected it.
Would also suggest checking the t10 2set proc on boomkins as well on PTR as this is currently not working either on live as OoC doesnt proc.

**Comment by Keader** [comment]
t10 is working

![image](https://user-images.githubusercontent.com/7120913/90762272-25410000-e2bb-11ea-9b33-fc08fa5f8f6c.png)

Not proccing in live, because OFC is not proccing xd

**Comment by Oganku** [comment]
Can second that. Omen and the related 2t10 proc both work in ptr. Also it seems pretty close to 3.5ppm, as it should.

**Comment by Oganku** [comment]
Serpent sting is massively messed up by double dipping in talents in the same way as warlock talents do in #4906. This causes chimera shot to also deal increased damage by a side-effect (similar to conflagrate).

ID 19466 Improved Stings (~46% increase instead of 30% with 4142 AP)

@Keader

**Comment by Oganku** [comment]
Same for priest DoTs double dipping in %dmg talents. Talents that cause this are:

ID 15310 Darkness (~15% instead of 10% with 999 SP)
ID 15317 Improved Shadow Word: Pain (~8.5% instead of 6% with 999 SP)
ID 63627 Improved Devouring Plague (~23.7% instead of 15% with 999 SP) *Instant part of the damage also probably broken cause of that
ID 52803 Twin Disciplines (~7.5% instead of 5%)

**Spells affected:** Shadow Word: Pain, Devouring Plague, Vampiric Touch.

@Keader

**Comment by bLeyaa** [comment]
> Serpent sting is massively messed up by double dipping in talents in the same way as warlock talents do in #4906. This causes chimera shot to also deal increased damage by a side-effect (similar to conflagrate).
> 
> ID 19466 Improved Stings (~46% increase instead of 30% with 4142 AP)
> 
> @Keader

@Oganku 
Do double check that, just did a test on live and with no gear / talents / aspect and a weapon with no stats my sting was doing 254 per tick.

After adding the sting talent without any other talents affecting it, and again with no aspect / gear and a weapon with no stats the sting was doing 334 per tick. This is a 31.5% increase in damage where the talent provides 30% increase to it. I'm not sure if there's something i overlooked that would be adding up to the 1,5% discrepancy but by no means does it do 46% instead of 30%.

**Comment by Oganku** [comment]
Without AP, it would be a perfect 30%, hunters unfortunately cannot drop to 0 AP, but unequipping all still reduced it to the lowest ranged AP possible and that's why you see a very small discrepancy. If you test with your full gear on, you'll see the talent adding 45%+.

Basically it's supposed to be a flat +30% but right now it's exponentially bigger the more AP/SP you have (depending on the spell's scaling). 

Your results don't seem to contradict what I seen, test with full gear if you can though.

**Comment by bLeyaa** [comment]
Okay, yeah doing the same with gear and no talents ended up being 437 per tick with no talents and 643 per tick with talents, at 5.7k RAP. 

To be fair i'm not very familiar on how it scales with RAP and if the arp affects it or anything similar. Difference with gear does increase on percentage variation, that i can confirm.

**Comment by Keader** [comment]
fixed in https://github.com/WoWManiaUK/Redemption/issues/4906

**Comment by Keader** [comment]
well we have enough time to test this.
if new issue raise, please open a issue about it.
