### ISSUE TITLE
[Phasing] Icecrown Fleshwerks area phasing incorrectly

### ISSUE THREAD

**Issue by sergiorkd** [WoWManiaUK/Redemption#4848]
**Links:**

**What is Happening:**

The NPC vanish when i get near him. I'm trying to turn in the quest  [Jagged Shards] but when i enter the zone the npc disapear, it should be near Darkrider Arly.
**What Should happen:**

**Comment by Oganku** [comment]
There is some phasing issues in that area depending on what order you do the quests in.

I can look at it more carefully to make sure there's no sequence break like what you encountered if you get phased, but for your specific issue you can make a ticket in-game and have a gm bring you back to the correct phase where you can see the NPC.

I will rename your issue and leave it open so it doesn't get forgotten though.

**Comment by jeyrella** [comment]
Have done that quest sequence many many times and never had an issue, so either it's a regression from something else, or an extremely specific unusual case.

**Comment by Oganku** [comment]
It is a pretty niche case, you need to not do a certain quest before continuing in the chain. Jagged shards mentioned is one for sure, just gotta make sure not more are affected and what should be changed.

**Comment by Oganku** [comment]
**Links**:
https://wowwiki.fandom.com/wiki/Quest:He%27s_Gone_to_Pieces
https://wowwiki.fandom.com/wiki/Quest:Jagged_Shards

**What is happening**: Basically, the quest that phases the player is [[He's Gone to Pieces]](https://wowwiki.fandom.com/wiki/Quest:He%27s_Gone_to_Pieces), which should only become available once all the previous quests in the fleshwerks have been completed.

![image](https://user-images.githubusercontent.com/34783736/90201682-965b5180-dda9-11ea-9cd3-2ff4d7d385e8.png)

Currently, [[He's Gone to Pieces]](https://wowwiki.fandom.com/wiki/Quest:He%27s_Gone_to_Pieces) becomes available too early, and can be completed before having completed [[Jagged Shards]](https://wowwiki.fandom.com/wiki/Quest:Jagged_Shards), which causes the player to get phased and be unable to complete the quest at all.

**What should happen** [[Jagged Shards]](https://wowwiki.fandom.com/wiki/Quest:Jagged_Shards) should be a mandatory pre-requisite to being able to take [[He's Gone to Pieces]](https://wowwiki.fandom.com/wiki/Quest:He%27s_Gone_to_Pieces).

**Comment by Rushor** [comment]
hm currently you need to complete quest: Killing Two Scourge With One Skeleton (13144) in order to get quest 13212 He's Gone to Pieces

Is the condition of Jagged_Shards really needed?

**Comment by Rushor** [comment]
okay added conditions:

Only show quest He's Gone to Pieces - if quest Jagged Shards has been rewarded
