### ISSUE TITLE
[Battleground] Strand of the Ancients Attacker side start bug

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#4849]
**Links:** https://wow.gamepedia.com/Strand_of_the_Ancients

**What is Happening:** In [Strand of the Ancients](https://wow.gamepedia.com/Strand_of_the_Ancients), if you join the battle on attacker side after the first minute and the boat has started to move, you instead spawn on the beach. This allows you to start fighting the defenders before the boats have even docked, and you can even go and kill the cannons early. 

However, here comes the funkiest part. If you happen to die before the boats land, you will be unable to release or ressurect, or even from moving at all. If you /reload, you can move and show as alive, but you are still dead and see the Release Spirit prompt. Other players see you that way, and they cannot attack you. You basically become an immortal spectator. 

**What Should happen:** Even if a player joins late, they should still spawn on the boat on the attackers side, which would prevent all the following weird issues.

**Comment by Rushor** [comment]
well we cannot teleport players on ships.

i added a root aura for all those player who join the battle in the first phase (which are not spawned on the boat).

The root aura get's removed once the battle starts.
