### ISSUE TITLE
[Quest] Call to Arms: Strand of the Ancients

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#4850]
**Links:** https://www.wow-mania.com/armory/?quest=13405
https://www.wow-mania.com/armory/?quest=13407

**What is Happening:** The call to arms quests for Strand of the Ancients (linked above) don't get automatically accepted upon joining the battleground, despite the call to arms event being active.

**What Should happen:** You should automatically get the quest, similar to the other battlegrounds'.

**Comment by Rushor** [comment]
you should now get that quest if the event is active. pls also check if the reward works and is correct
