### ISSUE TITLE
[NPC] Deathbringer Saurfang - early death

### ISSUE THREAD

**Issue by bLeyaa** [WoWManiaUK/Redemption#4851]
**Links:** http://www.wow-mania.com/armory?npc=37813

**What is Happening:** Boss dies before his health reaches 0, which in turn also does not give reputation for defeating the encounter. If you have the beasts alive, the boss will drop a second or so before they despawn also. I can't check, but i would assume kill is not counted towards souls quest for Shadowmourne as well?

**What Should happen:** Boss should drop dead when he runs out of health points and awarding reputation to the players who are not fully exalted with Ashen Verdict.

I know there was an issue with combat bug earlier on this encounter, so i would assume this is something in relation to that.

**Comment by Oganku** [comment]
#4748 is the issue mentioned, which might be related.

**Comment by Keader** [comment]
test now in ptr pls
