### ISSUE TITLE
[NPC] Darnavan

### ISSUE THREAD

**Issue by bLeyaa** [WoWManiaUK/Redemption#4852]
**Links:** http://www.wow-mania.com/armory?npc=38485

**What is Happening:** If you use Mind Control on Darnavan and cancel it, the npc will return to his spawn location and not engage in combat further on.

**What Should happen:** NPC should remain in combat once the Mind Control effect fades.

**Comment by Oganku** [comment]
He should remain hostile for the entire duration of the fight, and needs to be cc'd. His bladestorm ability should make him immune to cc during its duration, but he only uses it periodically.

**Comment by bLeyaa** [comment]
I believe he is still hostile at the moment, just not engaged in combat... afk npc xD

**Comment by Rushor** [comment]
will add a check for that

**Comment by Rushor** [comment]
By Elaus (2,248 –  13·17)  on 2010/02/03 (Patch 3.3.2) |   |  
-- | -- | --


You can NOT CC him in anyway (polymorph, ice trap, disarm and even mind control). He must be tanked by someone in your raid, because he will bladestorm and do other nasty things. While tanking, you must do only enough damage to keep him from going to your healers and everyone in the raid must be aware of their splash damage. He has very little health, so he drops FAST!

https://www.wowhead.com/quest=24869/deprogramming#comments:id=963994

https://i.imgur.com/owRvzmA.png

**Comment by Rushor** [comment]
can no longer be charmed. fixed after ptr restart

**Comment by bLeyaa** [comment]
From CC i believe he can be rooted and maybe stunned. But thats about it.

**Comment by Oganku** [comment]
Still happening

**Comment by bLeyaa** [comment]
I believe its not Mind Control causing it, but things like Hex/Poly/Cyclone?

**Comment by Oganku** [comment]
This time it was mind control. He dropped aggro and ran back to his little corner

**Comment by bLeyaa** [comment]
Ahhh was it that again? Crap i must have missed it then 😂😂

**Comment by Rushor** [comment]
will add more immuntities to him then

could someone make a full list?

**Comment by Oganku** [comment]
From reading wow head comments, he should be immune to all cc **except** roots and during his bladestorm he removes those as well. The intended way to do it is that Darnavan should be tanked by something (pet, offtank, etc.).

**Comment by Rushor** [comment]
added lots of immunities like for NPC_GAS_CLOUD

**Comment by bLeyaa** [comment]
He should capable of being slowed and rooted, rest of the gas cloud immunities i believe apply, as gas clouds are immune to the first two as well. As Oganku said, once bladestorm is used he should remove the root and only then be immune to both slow and root for the duration of it.

**Comment by Oganku** [comment]
He can still be polymorphed, stunned, feared, death gripped, mind controlled, etc.

**Comment by Rushor** [comment]
is no longer immune against root and snare effects by default.

becomes immune to root and snare (and removes those auras) once baldestorm starts. once bladestorm faded away, he is no longer immune against root and snare again (till next bladestorm)

**Comment by Oganku** [comment]
Most immunities seem to work fine, but polymorph/hex and mind control still affect him, and they shouldn't.

**Comment by bLeyaa** [comment]
Not sure how i feel about hunter ice trap / freezing arrow..... how are they categorized? he's not immune to those either btw

**Comment by Rushor** [comment]
ice trap is MECHANIC_ROOT, so not immune against that

**Comment by Rushor** [comment]
immunities against SPELL_AURA_TRANSFORM, SPELL_AURA_MOD_STUN and SPELL_AURA_MOD_POSSESS added now

**Comment by Rushor** [comment]
can be tested now

**Comment by Oganku** [comment]
Hex and polymorph still affect him. He visually will remain human, but he gets the debuff and wanders around as if he was a frog/sheep. So he's only "visually" immune to it.

He doesn't get affected by mind control, but the player is still able to cast it at him, getting locked in a channeling state while Darnavan just ignores you and keeps attacking people. You should get the message "immune" if you try to mind control him, and the cast should just fail.

**Comment by Rushor** [comment]
Strange immunity system

**Comment by Rushor** [comment]
okay added it in db aswell. pls test :)

**Comment by Oganku** [comment]
Thanks a lot as usual ^^

**Comment by Rushor** [comment]
thanks for your tests
