### ISSUE TITLE
[Battleground] Strand of the Ancients Cannon damage

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#4855]
**Links:** https://wow.gamepedia.com/Strand_of_the_Ancients

**What is Happening:** The cannons in [Strand of the Ancients](https://wow.gamepedia.com/Strand_of_the_Ancients
) deal far too high damage against players. They are hitting for ~12k on players, even plate wearers.

**What Should happen:** 
![image](https://user-images.githubusercontent.com/34783736/90295068-fe677180-de55-11ea-99ec-b802e1d82ee7.png)

**Comment by Keader** [comment]
if i remember right, weapons like that scale damage with player items

**Comment by Oganku** [comment]
![image](https://user-images.githubusercontent.com/34783736/90302907-8d38b600-de77-11ea-8a98-b193411b2827.png)

This is the only thing I could find about the scaling. So the damage might be correct but I'm not sure if the falloff mechanic is present? (Should deal less damage further from the rocket explosion you are).

**Comment by Rushor** [comment]
okay i work on sth based on distance

**Comment by Aristo14** [comment]
based on distance? Just make sure the refference is checked guys.. 

without refference no changing please

**Comment by Rushor** [comment]
proof is there https://github.com/WoWManiaUK/Redemption/issues/4855#issuecomment-674331259

but a video proof would also be good

**Comment by Rushor** [comment]
question is what values we should take?

damge: (hitdamage / range to object) * 2  ?

**Comment by Rushor** [comment]
the damage should now be reduced, the more far away the target is

**Comment by Oganku** [comment]
I'd say if there's any similar falloff damage formula elsewhere to use that. I know algalon's cosmic smash does too.

**Comment by Rushor** [comment]
good point! will add that

**Comment by Rushor** [comment]
formula updated to the one same to algalon's cosmic smash

**Comment by Oganku** [comment]
**What is Happening:** Realized that the damage scales properly from distance, but is calculated based on distance from the Cannon (caster)! 

**What should happen:** Damage drop-off calculation should be based off distance from the center of the explosion from https://www.wow-mania.com/armory/?spell=49872.

**Comment by Rushor** [comment]
try now pls, destination is different calculated now

**Comment by Oganku** [comment]
Damage scales on distance from the explosion. Varies from ~3k to ~11k based on that.
