### ISSUE TITLE
[Battleground] Strand of the Ancients Demolishers not respawning

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#4856]
**Links:** http://wow-pro.com/general_guides/wotlk_bg_strand_ancients
https://postmasterinterest.blogspot.com/2012/10/world-of-warcraft-newbie-guide-12.html
https://wowwiki.fandom.com/wiki/Strand_of_the_Ancients

**What is Happening:** Currently, all Demolishers in the battleground spawn either at the start of the fight, or when their respective workshop is captured, but will never respawn afterwards if they are destroyed.

**What Should happen:** Sources from above ([1](https://postmasterinterest.blogspot.com/2012/10/world-of-warcraft-newbie-guide-12.html), [2](https://postmasterinterest.blogspot.com/2012/10/world-of-warcraft-newbie-guide-12.html)) mention that the demolishers should all respawn at their original spawn points after being destroyed. A strategy involving damaging but not destroying completely an abandoned demolisher is even mentioned in the second source. All other major guides about the battleground mention the cannons NOT respawn (as they already are) but also do mention demolisher spawn points and implicity also say that they do respawn.

**Comment by Keader** [comment]
fixed
