### ISSUE TITLE
[Quest] Mutiny on the Mercy

### ISSUE THREAD

**Issue by Sierbahnn** [WoWManiaUK/Redemption#4858]
**Links:**
https://www.wowhead.com/quest=11527/mutiny-on-the-mercy

**What is Happening:**
There are no hostile mobs spawned on the ship.

**What Should happen:**
There should be hostile mobs here that you can kill to get the barrels needed to finish the quest. As the boat is moving, I am guessing they spoawned, phased out the wall as the ship moved, and are gone.

**Comment by jeyrella** [comment]
Check other ship.
