### ISSUE TITLE
Find Fish Overrides

### ISSUE THREAD

**Issue by Sierbahnn** [WoWManiaUK/Redemption#4859]
**Links:**

**What is Happening:**
I click on Find Herbs, and Find Fish remains.
Changing the icon on the minimap does the same thing, which is nothing.
When clicking Find Fish in my Spellbook "<Find Fish>" Scrolls across the screen, but no "<Find Herbs>" Scrolls across it when I do the same.
Changing the minimap icon to another form of tracking and THEN changing to Find Herbs works.

**What Should happen:**
Clicking the minimap to "Find Herbs", or the spell in the Spellbook, ought to reset the tracking to Find Herbs immediately.

**Comment by Rushor** [comment]
Anyone else can confirm this?

**Comment by Oganku** [comment]
I did notice that using Find Fish would often ALSO keep tracking your previous selection, allowing me to see fish and mine nodes a while ago. It did act funky a while ago and it wasn't addressed since then. The issue isn't really a problem, more like a bug that makes tracking easier.

**Comment by Oganku** [comment]
So I went and tested, and here is how it behaves:

If you have any of the profession trackings enabled ([Find Fish](https://www.wow-mania.com/armory/?spell=43308), [Find Herbs](https://www.wow-mania.com/armory/?spell=2383) or [Find Minerals](https://www.wow-mania.com/armory/?spell=2580)) you will see on the minimap all of the corresponding nodes PLUS all other nodes that other profession trackings you have learned would show.

If you have Fishing + Mining + Herbalism, tracking any of the 3 will allow you to see all 3 types on the map. If you have any combination of the 2, you will only track those 2 instead (Herbs and Fish for Sierbahnn's case). This is however limited to the profession trackings you have learned, and will not instantly allow you to track everything from professions you don't have.

**Comment by jeyrella** [comment]
Personally...  I'm really all for Blizzlike where possible, but this is one of those things that actually feels better than Blizz, with no particular harm.  Let's discuss in Discord dev team channel.
