### ISSUE TITLE
[Raid] Blackwing Lair Entrance Portcullis

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#4860]
**Links:** Issue #4122
https://wow-mania.com/armory/?object=176966

**What is Happening:** [The portcullis](https://wow-mania.com/armory/?object=176966) right before Razorgore the Untamed in Blackwing Lair is clickable. If a player clicks it, it closes forever and soft-locks anyone from progressing into the raid.

**What Should happen:** This door should be un-interactable, and should only close/open when the boss is in progress or not. Pretty much regression from issue #4122.

**Comment by Rushor** [comment]
Will fix it

**Comment by Rushor** [comment]
ah well that id is a different, that kitz did not fixed. so no regression :>
