### ISSUE TITLE
[Vehicle] Channeled spells as passenger in a Demolisher

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#4862]
**Links:** https://www.wow-mania.com/armory/?npc=28781#criteria-of
https://www.wow-mania.com/armory/?npc=28094

**What is Happening:** If a player casts a channeled ability such as [Blizzard](https://www.wow-mania.com/armory/?spell=10), [Rain of Fire](https://www.wow-mania.com/armory/?spell=5740), [Volley](https://www.wow-mania.com/armory/?spell=1510) while in the passenger seat of a [Battleground Demolisher](https://www.wow-mania.com/armory/?npc=28781#criteria-of) or [Wintergrasp Demolisher](https://www.wow-mania.com/armory/?npc=28094), the driver can drive as far away as he wishes, and the channeled spell will not cancel due to range. 

For example, a coordinated duo of mage and driver can cast max range blizzards in strategic battle areas and drive the demolisher away to safety over its duration. When it ends, they drive back a little closer to re-cast it and repeat as desired, making it seem like the blizzard is coming from nowhere for most players.

**What Should happen:** If the driver of a demolisher causes a channeled ability to go out of maximum cast range, it should automatically cancel and end.

**Comment by Keader** [comment]
i dont think that it's a issue...
back in MOP on retail, i remember to cast rain of fire and get not interrupt when car move away

**Comment by Rushor** [comment]
Soo closing?

**Comment by Keader** [comment]
![image](https://user-images.githubusercontent.com/7120913/90761126-54ef0880-e2b9-11ea-9fad-71e664e8932a.png)

**Comment by Keader** [comment]
well... closing.
let me know if you find any evidance
