### ISSUE TITLE
[Battleground] Strand of the Ancients Demolisher combat bug

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#4863]
**Links:** https://www.wow-mania.com/armory/?npc=28781#criteria-of
https://wow.gamepedia.com/Strand_of_the_Ancients

**What is Happening:** If you attack a demolisher in Strand of the Ancients, you will remain in combat as long as the demolisher itself is in combat (which is pretty much the entire duration of its life). If you hit a demolisher that then manages to break through a gate and escape, you will be unable to mount up and catch up to it, forced to walk slowly. The only way to fix it is to either kill said demolisher, or die.

**What Should happen:** Players should exit combat as they would with a player when attacking a demolisher.

**Comment by Rushor** [comment]
pvp vehicles should no longer be able to keep players in combat

**Comment by Oganku** [comment]
**What is Happening:** Works well when the vehicle is operated by an enemy. However, if the vehicle is unmanned, combat only drops based on distance, and this distance is quite large. You need to go far enough to make it disappear from your screen. 

**What should happen:** Un-manned vehicles should drop combat the same way as the manned ones do.

**Comment by Rushor** [comment]
try now pls

**Comment by Oganku** [comment]
Still have to go all the way there to drop aggro from the unmanned demolisher on the dock where my mouse is.

![image](https://user-images.githubusercontent.com/34783736/101296467-d54a6280-37f1-11eb-872d-abc11924a06f.png)

**Comment by Rushor** [comment]
hmm yeah, i remember that i only added it to if vehicle is pvp

**Comment by Rushor** [comment]
cannot find the reason for that atm :(

**Comment by Oganku** [comment]
It's honestly not too big of a deal, since at least it does drop after a certain distance.
