### ISSUE TITLE
Shaman Quest (Spirit Totem) droprate extremely low.

### ISSUE THREAD

**Issue by manmetbaard** [WoWManiaUK/Redemption#4864]
https://classic.wowhead.com/quest=8412/spirit-totem

I killed 30-40 mobs and had no loot I needed,  created a ticket, and GM Brontes told me to create a ticket here.  
thank you in advance

According to wowhead loot should be around 25% droprate.

**Comment by Rushor** [comment]
will check, but pls also use wowwiki sources

**Comment by Rushor** [comment]
https://i.imgur.com/5MZEdbA.png dropchances loot fine in db

**Comment by manmetbaard** [comment]
Maybe it was badluck sorry about that..  then this is a false positive.
Again very sorry

**Comment by Oganku** [comment]
This quest is pretty terrible to do, but it's also not mandatory whatsoever. At least.
