### ISSUE TITLE
[Spell] Spell Proc Erros

### ISSUE THREAD

**Issue by Keader** [WoWManiaUK/Redemption#4867]
**What is Happening:**

AuraEffect::HandleProcTriggerSpellAuraProc: Could not trigger spell 0 from aura 54775 proc, because the spell does not have an entry in Spell.dbc.
None Low: 0)]
AuraEffect::HandleProcTriggerSpellAuraProc: Could not trigger spell 0 from aura 55221 proc, because the spell does not have an entry in Spell.dbc.

**What Should happen:**

Both errors should not happens

**Comment by jeyrella** [comment]
linked to the early release https://github.com/WoWManiaUK/Redemption/issues/4846 not fully tested
