### ISSUE TITLE
[Spell] Spell Reflection kills on duels

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#4868]
**Links:** https://www.wow-mania.com/armory/?spell=23920

**What is Happening:** If you win a duel by dealing the last damage necessary on the enemy player by reflecting one of their own spells with [Spell Reflection](https://www.wow-mania.com/armory/?spell=23920), it kills them.

**What Should happen:** Players should never die when a duel ends, and having one of their own spells reflected at the end should behave in the same way as losing to an enemy attack does: leaving you at 1hp, alive and free of any DoTs.

**Comment by Keader** [comment]
yeah... it's a blizzlike bug.
you can kill players in duel until Legion with it xD
