### ISSUE TITLE
[Spell] Omen of Clarity

### ISSUE THREAD

**Issue by Haponita** [WoWManiaUK/Redemption#4869]
**Links:**
https://wotlkdb.com?spell=16864
http://www.wow-mania.com/armory?spell=16864
wowhead link would not be relevant as it changed in the current blizzard server.

The talent was working as intended until last week. Today and yesterday, it has not procced a single time on my tree druid during an entire ICC 25 raid. I tested this after the raid and it never procced with any healing spell. I switched to feral and it procced by feral attacks.

**What Should happen:**
The talent should proc from melee attacks, damaging spells and healing spells.

**Comment by svijetlo** [comment]
keep in mind this need to proc on HIT

**Comment by jeyrella** [comment]
linked to the early release https://github.com/WoWManiaUK/Redemption/issues/4846 not fully tested

**Comment by Keader** [comment]
old hack, cause conflict with new proc system.
fixed.

**Comment by Oganku** [comment]
Omen of Clarity procs off of direct heals, damagin spells and melee attacks, but it still does not proc on HoT casts nor ticks. Should proc on initial casts of HoTs. Tested with [Rejuvenation](https://www.wow-mania.com/armory/?spell=48441), [Wild Growth](https://www.wow-mania.com/armory/?spell=53251) and [Renew](https://www.wow-mania.com/armory/?spell=48068) (for science).

**Comment by Keader** [comment]
fixed ²

**Comment by Haponita** [comment]
Thank you for the quick reply and fix. I really appreciate it :) It felt so bad going oom so early last week :D

**Comment by Keader** [comment]
@bLeyaa fixed to proc with non-damage/heal spells like buffs

**Comment by bLeyaa** [comment]
Thanks

This was an issue before the new implementation, thats why i made a separate report btw.
