### ISSUE TITLE
The RDF isn't working properly

### ISSUE THREAD

**Issue by tekpa** [WoWManiaUK/Redemption#4871]
**Links:**

**What is Happening:**
The RDF isn't connecting to other players when it searches. Instead, it just stays in the "searching for players" mode

**What Should happen:**
It should search for players and show the player in the que
![Clipboard01](https://user-images.githubusercontent.com/69919178/90672341-9a5cf880-e21b-11ea-8367-07d4da422158.jpg)

**Comment by Rushor** [comment]
disabled currently until we find a propper fix for a crash case

**Comment by tvshadowz** [comment]
Hi there! This issue is currently happening again. People will queue and all need to find another dps unless they queue with 3 dps then they need a healer. Issue should be assessed again. 

Thanks!

**Comment by tvshadowz** [comment]
Ah only if you queue with all roles in your party does it work.
