### ISSUE TITLE
Omen of Clarity proc

### ISSUE THREAD

**Issue by bLeyaa** [WoWManiaUK/Redemption#4874]
**Links:** http://www.wow-mania.com/armory?spell=16864

**What is Happening:** OoC does not proc from spells such as Mark/Gift of the Wild, Barkskin, Nature's Grasp, Innervate, Thorns

**What Should happen:** When either of the spells above is used there should be a chance for it to proc (6% if i'm not mistaken).

https://youtu.be/KFMPEECCAP0?t=38
https://wowwiki.fandom.com/wiki/Omen_of_Clarity
https://www.wowhead.com/forums&topic=55989

P.S. I haven't been able to check, but Faerie Fire should have an equal chance of proccing it as well.

P.P.S. I've also read posts about thorn damage proccing it but i have not found any proof of it as such, in case someone knows anything about it.

**Comment by Rushor** [comment]
pls add the informations in https://github.com/WoWManiaUK/Redemption/issues/4869 for @Keader
