### ISSUE TITLE
Rogues not being Revealed on Death and Decay

### ISSUE THREAD

**Issue by EldritchtheSnitch** [WoWManiaUK/Redemption#4875]
Putting Death and Decay under where an invisible rogue is standing does not reveal them 100% of the time.

**Comment by Oganku** [comment]
https://wowwiki.fandom.com/wiki/Stealth
https://eu.forums.blizzard.com/en/wow/t/is-there-much-point-to-revealing-a-rogue/47739

> Most damage taken (including from AoEs or DoTs) will remove Stealth. Also as of Bc icon Burning Crusade, fall damage will NOT remove Stealth.

Confirmed DnD should remove stealth, even if behaves as a DoT. Also confirmed it currently isn't working.

**Comment by Keader** [comment]
with or without absorb?

**Comment by Oganku** [comment]
Without
