### ISSUE TITLE
[Spells] Implemented spell Soul Deflection

### ISSUE THREAD

**Issue by Keader** [WoWManiaUK/Redemption#4883]
**What is Happening:**
Spell used by Counselor Talbot in Borean Tundra.
Spell was not scripted, so have no effect.

**What Should happen:**

Spell should reflect 100% of damage, while active.
it also fix core error:
AuraEffect::HandleProcTriggerSpellAuraProc: Could not trigger spell 0 from aura 51009 proc, because the spell does not have an entry in Spell.dbc.

**Comment by Oganku** [comment]
Counselor is not using any abilities, he just melee attacks horde players.

**Comment by Keader** [comment]
@Oganku not with me.
you can test this issue using in any enemy npc (not dummy) .cast back 51009
about your issue, make a new topic and mark rushor, this type of script is with him

**Comment by Oganku** [comment]
Ah ok, sorry about that
