### ISSUE TITLE
[Raid] Emalon the Storm Watcher's Overcharge

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#4885]
**Links:** https://wowwiki.fandom.com/wiki/Emalon_the_Storm_Watcher
https://www.wow-mania.com/armory/?spell=64217

**What is Happening:** [Emalon the Storm Watcher](https://wowwiki.fandom.com/wiki/Emalon_the_Storm_Watcher) currently does [Overcharge](https://www.wow-mania.com/armory/?spell=64217) his adds periodically, but only the initial buff is applied, and it doesn't stack afterwards. They therefore never explode, making this part of the fight irrelevant.

**What Should happen:** 
![image](https://user-images.githubusercontent.com/34783736/90987219-3b6aec80-e557-11ea-922d-6f41f2269119.png)
The overcharged minion should continously get stacks (~1 per 2 seconds) and eventually explode if he reaches 10 stacks before being killed, forcing the raid to switch focus on adds that are empowered.

**Comment by Rushor** [comment]
stacking should work now https://i.imgur.com/qpzABt4.jpeg

**Comment by Oganku** [comment]
Still only applies the initial cast, then no further stacks are gained. Tested on both 10 and 25, alliance side.

**Comment by Rushor** [comment]
sth must have gone wrong while testing - it works great for me https://gyazo.com/6945a8de4f8f51ab08f223cb59eefe47

**Comment by Oganku** [comment]
Can't reproduce it for some reason, I'll leave it for someone else to check.

**Comment by Rushor** [comment]
hmm okay if we find a reproduce case i can inspect again
