### ISSUE TITLE
Frostmourne room & Bombs - Lich King Heroic

### ISSUE THREAD

**Issue by bLeyaa** [WoWManiaUK/Redemption#4886]
**Links:** https://clips.twitch.tv/ElatedImportantWaterNotATK

**What is Happening:** As we enter you can see third warrior in group 2 suddenly goes out of range even tho we're all stacked up. He fell through ground shortly after entering Frostmourne room. As the clip goes, i get hit by bomb (two of them) even tho i dont appear to be in their range and then further on fall through ground as well. For reference, you can see the boomy running next to me not being hit, the only difference i see is him starting to move earlier, so i'd be guessing the bomb doesnt update actual player location well enough or something?

**Comment by Rushor** [comment]
First one is as is https://github.com/WoWManiaUK/Redemption/issues/2364

**Comment by bLeyaa** [comment]
I thought that bug was related to shapeshifting, is there anything else that causes it? Charge/Intervene?

What about bombs?

**Comment by Rushor** [comment]
okay made some adjustments to the spiritbom handling.

range of the damage form the bombs has been adjusted, they are active at spawn now (not only when player load their grid) and movement speed of them has been adjusted.
