### ISSUE TITLE
[NPC] Gravis Slipknot 

### ISSUE THREAD

**Issue by Rushor** [WoWManiaUK/Redemption#4887]
**Links:**
Gravis Slipknot 
https://www.wowhead.com/npc=14221/gravis-slipknot
https://i.imgur.com/Vy8E76c.jpeg
**What is Happening:**
Has an invisible model sometimes

**What Should happen:**
Should always be visible

**Comment by Zanguin-ManiaTester** [comment]
![3](https://user-images.githubusercontent.com/47272908/90988668-e352db00-e594-11ea-8487-8b7463e93118.png)


Visible for Alliance. Horde coming up next.

**Comment by Zanguin-ManiaTester** [comment]
![4](https://user-images.githubusercontent.com/47272908/90988736-65430400-e595-11ea-8ad8-c3b4d286e0b3.png)
