### ISSUE TITLE
[Item] Draconic for Dummies (Chapter VI)

### ISSUE THREAD

**Issue by Blyatman1** [WoWManiaUK/Redemption#4890]
**Links:**
https://wow-mania.com/armory/?quest=8620
https://wow-mania.com/armory/?item=21108

**What is Happening:**
According to the armory, the draconic should still drop from Onyxia on both 10 and 25 man. I haven't tried 10, but I killed Onyxia on 25 earlier today, with no drop. Judging by the armory, the condition for it to drop is broken, as it says:
> The Player has accepted (Quest #0)

**What Should happen:**
Onyxia should drop the item if somebody in the group is on the quest.

**Comment by Oganku** [comment]
From my experience the quest auto-completed and you could turn it in directly after taking it since Ony60 isn't available anymore. 

> As of Patch 3.2, this item will still drop from Onyxia in the level 80 version of the instance (10- or 25-man) if you have the quest. However, this means you must be level 80 to complete the quest chain, as lower levels cannot enter the new level 80 raid.

**Comment by Rushor** [comment]
should drop in 10 and 25 now
