### ISSUE TITLE
The Truth Shall Set Us Free npc duplication

### ISSUE THREAD

**Issue by wapachoo** [WoWManiaUK/Redemption#4891]
**What is Happening:**
while proceeding through The Truth Shall Set Us Free quest in dragonblight, the cutscene after using the item has every NPC duplicated once over - the voice lines and dialogue in chat are also doubled up.

![bug1](https://user-images.githubusercontent.com/26100987/90988904-3f910d00-e54b-11ea-9efa-d005cee84494.png)
![bug2](https://user-images.githubusercontent.com/26100987/90988905-415ad080-e54b-11ea-99f9-ed5e71334f5b.png)
https://youtu.be/fYFYzy0PysY video of issue

**What Should happen:**
presumably there should only be one copy of each NPC, and the voice lines & dialogue should also not be doubled.

**Comment by Rushor** [comment]
quest=12301

**Comment by Rushor** [comment]
no more duplicate spawn now
