### ISSUE TITLE
[NPC] Counselor Talbot

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#4893]
**Links:** https://www.wow-mania.com/armory/?npc=25301
https://www.wow-mania.com/armory/?spell=50992
https://www.wow-mania.com/armory/?spell=51009
https://www.wow-mania.com/armory/?spell=51016

**What is Happening:** [Counselor Talbot](https://www.wow-mania.com/armory/?npc=25301#drops) will only use melee attacks if engaged by a horde player.

**What Should happen:** 
![image](https://user-images.githubusercontent.com/34783736/90991361-a11aa100-e576-11ea-9509-fabaadbf8966.png)

Counselor Talbot should use the spells [Soul Blast](https://www.wow-mania.com/armory/?spell=50992), [Soul Deflection](https://www.wow-mania.com/armory/?spell=51009) and [Vampiric Bolt](https://www.wow-mania.com/armory/?spell=51016), since he is in fact Prince Valanar disguised.

**Comment by Rushor** [comment]
he will use the spells now
