### ISSUE TITLE
[DK] T10 4set bonus "Advantage" not working properly

### ISSUE THREAD

**Issue by gabrel1900** [WoWManiaUK/Redemption#4895]
**Links:**
https://www.wow-mania.com/armory/?spell=70656

**What is Happening:**
"Whenever  al your runes  are on cooldown, you gain 3% increased damage done with weapons, spells, and abillities for the next 15 sec"
noticed that im not getting the buff as a dk frost dps spec, after testing, my conclusion it that runes used by Pestilence doesn't count for the buff because if i use all my runes without using pestilence it works, but if i use pestilence it dosnt work.

**What Should happen:**
Pestilence not countig for rune cooldown for the t10 buff, it should.
![issue](https://user-images.githubusercontent.com/70123577/91001350-7857d300-e599-11ea-9e31-d7846b99aa8c.png)

**Comment by Keader** [comment]
try now pls

**Comment by Aristo14** [comment]
must be some regression..

**Comment by Keader** [comment]
I mean, test in ptr xD

**Comment by gabrel1900** [comment]
sorry but, how do i do that xD  i know  only how to create a lvl 1 in the frostmourne (PTR)  server

**Comment by Keader** [comment]
Our testers Will test It xD
