### ISSUE TITLE
[Battleground] Remove Reputation and Itemreward from battelgrounds (preclosed)

### ISSUE THREAD

**Issue by Rushor** [WoWManiaUK/Redemption#4896]
This adds a patch, that players will no longer get items/or Honor/or reputation if the battleground was pre-closed due to the fact that not enough players joined the battleground.

**Comment by Rushor** [comment]
you can test that with:

1. ".debug bg"
2. select battleground and join
3. after bg has started after 2 minutes -> ".debug bg" which restored the orignal requirements
4. battleground will close then after 5 minutes
5. inspect if no rewards are given

**Comment by Zanguin-ManiaTester** [comment]
https://youtu.be/EBhqSJS77HI

Fix confirmed, thanks!
