### ISSUE TITLE
[Dungeon][Mob][Spell]: Azjol-Nerub - Prime Guard - Mark of Darkness damage procs off everything.

### ISSUE THREAD

**Issue by Zanguin-ManiaTester** [WoWManiaUK/Redemption#4897]
Links:
http://www.wow-mania.com/armory?npc=29128
http://www.wow-mania.com/armory?spell=59352

What is Happening:

Mark of Darkness is proccing off everything, even buffing one self.

Mania-ptr recording: https://youtu.be/ue19ex3nZvo

What Should happen: Mark of Darkness should only hit when healing is done to the marked target.

**Comment by Keader** [comment]
fixed

**Comment by Zanguin-ManiaTester** [comment]
Fix confirmed! Normal spells no longer procs Mark of Darkness. Thanks!

https://youtu.be/2wk5gA78RL8
