### ISSUE TITLE
[Quest] Gormok wants his Snobolds - Snow Peaks

### ISSUE THREAD

**Issue by jeyrella** [WoWManiaUK/Redemption#4899]
**Links:**
https://www.wow-mania.com/armory/?quest=14141 
and
https://www.wow-mania.com/armory/?quest=14090
Snobold NPC:  29618
Item:  https://www.wow-mania.com/armory/?item=46885

**What is Happening:**
Weighted Net can be used on the same Snowbold more than once before they despawn

**What Should happen:**
Weighted Net should be usable only once per Snowbold

**Comment by Rushor** [comment]
try now please

**Comment by Oganku** [comment]
Kobold still keeps running, but you can use the net as many times as you want until he despawns (usually 2-3). He doesn't stop and become untargettable by the net as he should.

**Comment by Rushor** [comment]
okay should now be untargettable upon spellhit by net

**Comment by Oganku** [comment]
Could be better visual-wise, since they still only pause for a second then keep running for ~3s until they despawn, but functionally it's just fine.
