### ISSUE TITLE
[Quest] Breakfast of Champions - Storm Peaks

### ISSUE THREAD

**Issue by jeyrella** [WoWManiaUK/Redemption#4900]
**Links:**
Quests:
https://www.wow-mania.com/armory/?quest=14076
https://www.wow-mania.com/armory/?quest=14092

Missing NPC:  https://www.wow-mania.com/armory/?npc=34915

**What is Happening:**
https://youtu.be/4Z-8MQKz9dc
When the fumping "fails" and the dwarven mole machine turret is summoned;
a)  the mole machine texture is replaced by a small red diamond for a short time
b)  no [Stormforged Marauder](https://www.wow-mania.com/armory/?npc=34915) is spawned

**What Should happen:**
https://youtu.be/TuF1_I6_v14?t=60
a)  should be no temporary texture holder
b)  a [Stormforged Marauder](https://www.wow-mania.com/armory/?npc=34915) should be spawned from the turret

**Comment by Rushor** [comment]
also important for scripting: https://www.wowhead.com/npc=34915/stormforged-marauder#comments:id=826114

**Comment by Rushor** [comment]
try now.

there is a small issue that the Stormforged Mole Machine vanishs before despawn. that is a generic issue related to traps (ignore that :D )
