### ISSUE TITLE
[Quest] Lumber Hack - Dragonblight - 12050

### ISSUE THREAD

**Issue by jeyrella** [WoWManiaUK/Redemption#4901]
**Links:**
Quest:  https://wow-mania.com/armory/?quest=12050
Lumber:  https://wow-mania.com/armory/?item=36733
NPC:  https://wow-mania.com/armory/?npc=27061

**What is Happening:**
a)  [Xink's Shredder](https://wow-mania.com/armory/?npc=27061) can sit at the same tree and use [Gather Lumber](https://wow-mania.com/armory/?spell=47939) skill to farm as many times as required
b)  Excess of the [Coldwind Lumber](https://wow-mania.com/armory/?item=36733) gathered above the 50 needed for the quest is not removed from inventory when quest is turned in. 

**What Should happen:**
a) Once [Gather Lumber](https://wow-mania.com/armory/?spell=47939) has been used, player should have to move to another tree to farm more
b) Excess of Coldwind Lumber should be removed from inventory on turn in. 

Hard to find era-exact videos, this is one from slightly later period, but same effect & gamplay.
https://youtu.be/khAn6oRFrBA

**Comment by Zanguin-ManiaTester** [comment]
https://youtu.be/iAo1i2eE-h4

B is happening. A needs a fix.

**Comment by jeyrella** [comment]
hmm.  thats odd for b.  i had it happen to me in both live PTR earlier....  i forgot to record it ofc.  thx i will try again

**Comment by Rushor** [comment]
Moreover: spell Emergency Repair Kit from vehicle has no effect

**Comment by Rushor** [comment]
okay:

the vehicle can heal hisself now again
the vehicle will lumber only one time, then the tree sign will dissapear for a few seconds


fixed once prt is builded

**Comment by Rushor** [comment]
is on ptr now

**Comment by Oganku** [comment]
Lumber part works, heal (spell 47966) still does nothing.

**Comment by Rushor** [comment]
heal should work now :)
