### ISSUE TITLE
[Spell][DK]- Empower Rune Weapon

### ISSUE THREAD

**Issue by festerhowl** [WoWManiaUK/Redemption#4902]
**Links:**

**What is Happening:**- ERW is not refreshing death runes since rdf was fixed on saturday.

**What Should happen:**

**Comment by catastross** [comment]
was about to post this issue aswell, and another dk was testing with me and can provide video evidence since i wont post it now that theres a post before mine

**Comment by Oganku** [comment]
Probably linked to #4895.
Death runes not counted as actual runes for some reason?

**Comment by wow-mania** [comment]
Need a tester to confirm.

**Comment by svijetlo** [comment]
i just tested this works fine on my UH DK , did 2 x blood strike , used both blood runes did E.R.W. got 2 blood runes back worked every time i try it

**Comment by catastross** [comment]
it's doesn't work on death runes* and i was on frost spec with Blood of the North talent
here's video proof if required as original post doesn't really expand past what is broken
https://www.youtube.com/watch?v=dJiUWrmOAFY

**Comment by Keader** [comment]
try now pls

**Comment by rezognate** [comment]
no its still not working, 15:57 svt

**Comment by Keader** [comment]
need test in ptr @rezognate .
wait some tester like @svijetlo test it xD

**Comment by rezognate** [comment]
any update :D
