### ISSUE TITLE
Calendar

### ISSUE THREAD

**Issue by Gercsi** [WoWManiaUK/Redemption#4903]
hello!

several days ago i noticed that a random guild raids appeared in my calendar and it don't want to disappear and i am not in a guild numerous months ago

i hope we can solve it
(charname:  deborah)

best regards 
Deborah

**Comment by Rushor** [comment]
please talk to a gamemaster for the reset of that

**Comment by Gercsi** [comment]
i've already did and he told me to make a ticket on github
