### ISSUE TITLE
[Spells] DoTs double dipping in %dmg increase talents

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#4906]
**Links:** https://github.com/WoWManiaUK/Redemption/issues/2708 < Identical to this old issue

**What is Happening:** All flat damage multiplier talents from the affliction tree that affect dots are currently increasing damage more than they should.

ID 17814 (~15% increase instead of 10%) 
ID 63108 (~7.4% increase instead of 5%)
ID 18275 (~24% increase instead of 15%)
ID 30060 (~7% increase instead of 5%)
ID 18829 (~15% increase instead of 10%)

*All tests were done with 999 spell power*

Referencing this comment from Dranah explains the issue perfectly:

> Ok this gave me a headache to find how exactly the spell calculates right now, because not only the mods are double dipping, but also the stacking method is wrong, which kept distorting my results.
> But now I think I got the picture:
> 
> Here's the INTENDED formula to calculate damage for corruption with all talents taken except Malediction:
> **(BaseDamage + SP x Coeff ) x modifiers = total damage**
> Coeff: 1,2 + 0,3 (Everlasting Affliction) + 0,36 (Empowered Corruption)
> Modifiers: 10% from 17814, 5% from 63108, 15% from 18275, 5% from 30064 all stacking multiplicatively makes its math go as follows for a warlock with 3002 spell power:
> **(1080 + 3002 x 1,86) x 1,1 x x 1,05 x 1,15 x 1,05 = 9293 (1548 per tick)**
> This is the damage the spell SHOULD do.
> 
> Here's the formula that the spell currently uses:
> **(BaseDamage + SP x Coeff x modifiers ) x modifiers = total damage**
> With modifiers stacking ADDITIVELY for whatever reason instead of multiplicative, making the modifiers total 1,35 instead of 1,394.
> For a warlock with 3002 SP:
> **(1080 + 3002 x 1,86 x 1,35) x 1,35 = 11632 (1938 per tick)**
> My in game test is 1937 per tick.
> 
> EDIT: unfortunately this may be impossible to fix at current state of core (according to keader)

Source: Issue #2708 that was fixed on September 14, 2018.

DoTs are pretty much double dipping in flat % multipliers, as it seems to apply once to the spell power component of the damage, then again to the full damage. The higher your spell power, the bigger the discrepancy. Here, I tested with roughly equal parts base damage/scaling, which gives the 1.5x multiplier to the intended effect of the multiplier.

The other talents mentioned in #2708 that worked fine, still do, and only the ones mentioned above are flawed.

ALSO, affects the following destruction talents:

The DoT part of Immolate and Shadowflame (and therefore the total damage of conflagrate) is double dipping in the following % multiplier talents:

ID 18119 (Aftermath)
ID 17815 (Improved Immolate)
ID 17954 (Emberstorm)

**What Should happen:**
%Damage Multipliers should only apply once, at the end of other damage calculations, and never should spells double-dip in such a way with talents.

Priest and hunter dots behave the same (see qaston thread). Likely affects all other dots too.

**Comment by Keader** [comment]
try now in ptr pls
