### ISSUE TITLE
[Quest] Wooly Justice - 12707 - Zul'Drak

### ISSUE THREAD

**Issue by jeyrella** [WoWManiaUK/Redemption#4908]
**Links:**
Quest:  https://wow-mania.com/armory/?quest=12707
Item medallion: https://wow-mania.com/armory/?item=39268
Enraged Mammoth: NPC 28851
Mammoth skill - Rushing Charge: https://wow-mania.com/armory/?spell=52601
Mam'toth Disciple: NPC 28861

**What is Happening:**
When mounted on the Enraged Mammoth, it remains in combat after killing the first Mam'toth Disciple.  This means skill 1 "Rushing Charge" can only be used once and becomes unusable on further Mam'toth Disciples.
see 1:02 here https://youtu.be/dJDlfULUV4U

**What Should happen:**
This era-relevant video https://youtu.be/-ClQOpWiYn8?t=60 clearly shows at 1:21 that after the kill, the Mammoth vehicle should leave combat and Rushing Charge becomes usable again on further Disciples.

**Comment by Rushor** [comment]
this will be fixed in future with combat rewrite adjustments https://github.com/TrinityCore/TrinityCore/issues/15591
