### ISSUE TITLE
Warlock

### ISSUE THREAD

**Issue by bigbih** [WoWManiaUK/Redemption#4909]
**Links:**

**What is Happening:**

**What Should happen:**

**Comment by bigbih** [comment]
i missing my felhunter pet i know dont if people hve report this on their acount but i just want to ask for some help iknow it might be difficult also want to let your guys know that the pr looking great feels better then all the other

**Comment by bigbih** [comment]
hello first thing first love the PR play everyday I'm just missing half of my pets on my warlock I know it happens to some players but i was wondering if you guys can help me out with this one i would appreciate it thank you for the game play 👍 :)

**Comment by GMMetaxa** [comment]
Please read the "How to report a bug" section. Your issue isn't a server issue, I advise you to use Google on "How to obtain warlock pets".  Kind regards, Gamemaster Metaxa.
