### ISSUE TITLE
[ZG] Hakkar - Blood Siphon  + Corrupted Blood

### ISSUE THREAD

**Issue by Rushor** [WoWManiaUK/Redemption#4914]
**What Should happen:**
Hakkar - Blood Siphon will now be casted from the player towards the boss + Corrupted Blood will be casted on a random hostile player victim

* source: http://wowwiki.wikia.com/wiki/Hakkar_the_Soulflayer_(tactics)
* Hakkar should blood siphon and Corrupted Blood
Blood Siphon: Every 90 seconds from the time that Hakkar is pulled he will cast Blood Siphon on the entire raid. In its base state this is a 8 second channeled drain that deals 200 damage per second, stuns, and heals Hakkar for 1000 health per second
Corrupted Blood: 875-1125 direct shadow damage plus a 200 every 2 seconds shadow DOT that hits a player and several players around.

**Comment by Oganku** [comment]
Soul siphon works fine, but he isn't using corrupted blood. Was fighting him with 2 toons for ~5min and he didn't use it once.

Also, https://www.wow-mania.com/armory/?spell=24689 still applies to the boss even if High Priest Thekal has been killed before. It is the only buff to not disable when the corresponding priest dies, and is most likely related to the fix of the second phase from #4722 .

**Comment by Rushor** [comment]
oh right, my bad. fixed some error. corrupted blood should be used by boss now
