### ISSUE TITLE
[Quest/Hunter] Taming the Beast

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#4916]
**Links:** https://www.wow-mania.com/armory/?search=taming+the+beast#0+1+2

**What is Happening:** All variations of the quest [Taming the Beast] (all linked above) currently do not auto-dismiss/abandon the quest pet when you turn it in. This causes conflict when you try to tame another pet for the following quest(s), as even if you complete the channeling of the rod, the game doesn't let you have 2 pets, and it will just repeatedly fail. 

It can be fixed if the player pre-emptively dismisses the previous quest pet, but if they are unaware of the issue and run out of range of it, they will be unable to, and it causes a fair bit of frustration, especially since it affects low level hunters that are often new players.

**What Should happen:** Turning in any of the [Taming the Beast quests](https://www.wow-mania.com/armory/?search=taming+the+beast#0+1+2) should automatically dismiss any pet the player currently controls, regardless of its range to its owner, so that the following Taming the Beast quest isn't hindered by this temporary pet. Alternatively just have the pet despawn once the player goes out of range. (By default it spawns on "stay" and the player will more than likely run away from it, forgetting it where it was)

**Comment by Rushor** [comment]
Which dismiss spell could we use here?

**Comment by Oganku** [comment]
Is there any /script that dismisses your pet regardless of range? Cause the problem is when the player goes too far from the pet, /dismiss or regular methods don't work unless you go back close to it. By default it's on "stay", but I'm afraid even changing that could cause issues since players get a mount at 10 when they usually aren't supposed to.

**Comment by Rushor** [comment]
yes i will try to fix both

**Comment by Rushor** [comment]
okay despawn of the pet is now added once player reward the "Taming" quests.

few things to check:

- server should not crash if player rewards the quest without a pet (dismiss the pet before reward)
- pet should be unsummoned if player rewards quest and pet is still there

**Comment by Rushor** [comment]
will fix the pet following thing now

**Comment by Rushor** [comment]
https://gyazo.com/2c0ce25c162d668f41d790173765278b horray, the questpets will follow the player now once charmed.

you do not need to test it with every creature since it is everywhere the same script. just for 3 or 4 quests. :)

**Comment by Oganku** [comment]
- [x] Pet gets dismissed on turn-in (regardless of how far it is from you)
- [x] Mounting doesn't make the pet disappear so doesn't mess with the quest
- [x] Pet will follow the player after being tamed
- [x] If the pet is dismissed early (or abandoned through script), quest completion remains
- [x] Nothing I tried caused the server to crash either
- [x] Other quests from the same NPCs can still be rewarded/completed properly (there's very few)

Looks clean overall, so unless the player is doing some really bogus thing it should never bug now. ^^

**Comment by Rushor** [comment]
Awesome!
