### ISSUE TITLE
[Quest] Daggercap Divin'

### ISSUE THREAD

**Issue by Slysam** [WoWManiaUK/Redemption#4917]
**Links:**
https://www.wowhead.com/quest=11443/daggercap-divin
https://www.wowhead.com/item=34082/diving-helm

**What is Happening:**
When you try to equip the helm that he gives you it starts bugging out and 'flickering' your breathing bar and the rope that is supposed to attach you to whatever buoy(which I don't believe is spawned, I never saw it). It interrupts combat, it interrupts looting and interrupts mining and I presume other actions. You can't right click your helmet and put it back on, either, it just tells you that "You can't do that right now". You can, however, manually remove the helmet to replace your own helmet back on.

**What Should happen:**
The helmet should effectively give you a water breathing buff so you can do the quest.

**Comment by jeyrella** [comment]
Confirmed issue.  https://youtu.be/IIXpJr6Jiwo

**Comment by Rushor** [comment]
could fix the breath bar so far, but sadly all channel get's interrupted if player opens go interaction

**Comment by Rushor** [comment]
okay fix will be pushed tomorrow

**Comment by Rushor** [comment]
okay you can use the helm now https://i.imgur.com/dHc7aGL.jpg

you get a water brwathing buff once used and a rope will be channeld to the Buoy. you can also loot objects while having that breath helm.

However i could not fix that you cannot reuse the item once unequiped sadly. That must stay as is.

**Comment by Oganku** [comment]
- [x] Tube works perfect and doesn't tug you anywhere or hinder movement
- [x] Tube breaks and breath goes back to normal if you unequip the helm or go out of the water
- [x] Can only re-equip helm if you abandon and retake. As-is.
