### ISSUE TITLE
[Spell/War] Retaliation

### ISSUE THREAD

**Issue by Keader** [WoWManiaUK/Redemption#4922]
**What is Happening:**

Spell is not proccing with triggered spells... Like Lord Marrowgar Bone Storm.
As can see in this log: http://worldoflogs.com/reports/1eqihkl5ev90v8a3/xe/?s=590&e=745&x=spell+%3D+%22Retaliation%22+or+%28spell+%3D+%22Bone+Storm%22+AND+targetName+%3D+%22Providence%22%29
It should "reflect" bone storm damages.
Spell range is wrong too

**What Should happen:**

Should proc with triggered spells and should hit targets with distance > 5 yards.

**Comment by Oganku** [comment]
Does proc from melee spells now, but only in melee range. I suppose you meant distance <5yd? If you meant it should proc from any range, like long range talented judgement, then it doesn't.

**Comment by Keader** [comment]
i mean... in blade storm, marrowgar can hit you from distances > melee range/5y  (because blade storm has a big range)
and you should still "retaliate" bladestorm
