### ISSUE TITLE
[ICC/Buff] Empowered Blood cost reduction component missing

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#4923]
**Links:** https://www.wow-mania.com/armory/?spell=70227

**What is Happening:** [Empowered Blood](https://www.wow-mania.com/armory/?spell=70227) buff from the blood orbs in Blood Quarter inside ICC are not reducing the cost of any abilities (mana, rage, energy, etc.).

Also, the buff

**What Should happen:** This buff should make spells have no cost for the duration, regardless of if they usually require mana, rage, energy or else. Other parts of the buff works fine.

**Comment by Rushor** [comment]
maybe the linked spell is missing?

**Comment by Keader** [comment]
linked spell? ew...
maybe script missing, i will check now

**Comment by jeyrella** [comment]
COnfirmed mana is still used.  Cast time reduction is correct.

**Comment by Keader** [comment]
fixed

**Comment by Oganku** [comment]
Spells still use resources when cast.

**Comment by Keader** [comment]
test now

**Comment by Oganku** [comment]
Still the same result :/

**Comment by Keader** [comment]
i confirmed in ptr, it's fixed.
Use this command:
.go xyz 4522.418945 2779.099365 351.101074 631
use .cast 70227
Cast some spell.
Remember, only magic spells has cost reduced to 0.

If you're not getting this buff just walking to Blood Prince room, is other bug: https://youtu.be/mQb_PkCl9Rs
This Blood Orb spell need be inside of The Crimson Hall area.
If you dont jump inside of this area, you get incorrect area (you can check using .gps) and dont get this buff.
But it's another issue...

**Comment by Oganku** [comment]
@Keader Is it intended to reduce cost of only mana-based spells?
