### ISSUE TITLE
[ICC/Quest] Pulsing Life Crystal interaction with Unchained Magic

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#4924]
**Links:** https://www.wow-mania.com/armory/?spell=69762
https://www.wow-mania.com/armory/?item=50851
https://www.wow-mania.com/armory/?spell=69766

**What is Happening:** Using [Pulsing Life Crystal](https://www.wow-mania.com/armory/?item=50851) while affected with [Unchained Magic](https://www.wow-mania.com/armory/?spell=69762) will generate a stack of [Instability](https://www.wow-mania.com/armory/?spell=69766).

**What Should happen:** Using the quest item should not give stacks of instability, as it isn't a spell. It basically should be the unchained targets' role to use the crystal.

**Comment by Keader** [comment]
Test now please.
I made all spells casted by items not proc it.
