### ISSUE TITLE
[Dungeon/Quest] Pit of Saron slaves missing their ball and chain

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#4925]
**Links:** https://www.wow-mania.com/armory/?quest=24498
https://www.wow-mania.com/armory/?quest=24507

**What is Happening:** Multiple of the Slaves (both Alliance and Horde) that you have to free as part of the quest [The Path to the Citadel linked above] are missing. All of the ones mining inside the pit in the center, and 2 slaves (that probably shouldn't even be there) near (45, 52.5) seem to be the ones missing. It's sort of frustrating to find a slave and have it be "bugged" and un-freeable cause it's ball is missing.

**What Should happen:** All slaves should have a clickable ball at their feet to get credit toward the quest. The 2 spawns near (45, 52.5) should probably just be removed and the ones in the pit should have a ball added.

**Comment by Rushor** [comment]
missing objects added
