### ISSUE TITLE
[Hunter] Pet Aggressive behavior

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#4926]
**Links:** https://wowwiki.fandom.com/wiki/Aggressive

**What is Happening:** Pets that are put on [Aggressive](https://wowwiki.fandom.com/wiki/Aggressive) behavior currently only attack hostile (Red) mobs. They will also ignore nearby players until they attack.

**What Should happen:** 

> An aggressive pet should attack any mob that enters its aggro radius.

It should just attack anything that's attackable and withing it's aggro range, even yellow (neutral mobs).

**Comment by Rushor** [comment]
try now pls

**Comment by Rushor** [comment]
the range to select the nereast hostile target is 45 yards in that case. if it should be reduced let me know

**Comment by Oganku** [comment]
45 yards sounds a little extreme, from what the description and forum posts from vanilla-wotlk, it says it should attack anything that enters its aggro radius. Being an NPC, the pet should have an aggro radius similar to that of other mobs of its level (~10-15 yards).

If it's kept at 45 it can easily be problematic and no evidence from back then mentions pets attacking this far, just that they would constantly engage in combat with enemies that got too close.

**Comment by Rushor** [comment]
okay then 10 yards? just gimme a number :>

**Comment by Oganku** [comment]
The aggro radius of a mob having the same level as the player is roughly 20 yards (~ 18 meters). Aggro radius varies with level difference at a rate of roughly 1 yard/level. Aggro radius is capped at a maximum of 45 yards, that is, when the mob is 25 or more levels higher than the player.

So 20 would be good if implementing that kind of formula is too much trouble.

**Comment by Rushor** [comment]
adjusted to 20 yards :)

**Comment by Oganku** [comment]
Looks perfect ^^

**Comment by Rushor** [comment]
can you may test with some more pets and think on every possible way it could bug out?

the pet will not attack untargetable mobs right? 

I'm just asking to not break anything :D

**Comment by Oganku** [comment]
I'll try some more later
