### ISSUE TITLE
[Warrior] Deep Wounds not proccing from ranged attacks (Shoot)

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#4927]
**Links:** https://www.wow-mania.com/armory/?spell=12867
https://www.wow-mania.com/armory/?spell=3018
https://www.mmo-champion.com/threads/623902-Question-Deep-Wounds

**What is Happening:** If a warrior crits with a ranged bow/crossbow/gun's [Shoot](https://www.wow-mania.com/armory/?spell=3018), [Deep Wounds](https://www.wow-mania.com/armory/?spell=12867) isn't applied.

**What Should happen:** Any critical hit should trigger deep wounds if talented, including ranged white hits.

**Comment by Keader** [comment]
fixed
