### ISSUE TITLE
[NPC] Dismembered Winterskorn vrykul corpses rotate to follow the player

### ISSUE THREAD

**Issue by jeyrella** [WoWManiaUK/Redemption#4928]
**Links:**
Quest:
alliance: https://wow-mania.com/armory/?quest=11246
horde: https://wow-mania.com/armory/?quest=11257
item used on corpse:  https://wow-mania.com/armory/?item=33310
spell used by item on corpse:  https://wow-mania.com/armory/?spell=43036

**What is Happening:**
After dismembering Winterskorn vrykul corpses for quest "Gruesome but necessary", the dismembered corpses rather disturbingly swivel to always be facing the player.  Of their own volition. Like they are watching the player as they walk away.  Even though it is hunking pile of shredded meat.  Man, am I going to be having some nightmares about that one....
https://youtu.be/haP1zeVLidk
![image](https://user-images.githubusercontent.com/46089380/91667707-71334680-eafe-11ea-883e-c23b0682b1ad.png)

**What Should happen:**
The dismembered corpses should stay still.  No, really....

**Comment by Rushor** [comment]
should be fixed now
