### ISSUE TITLE
[Quest] Bang a Gong!

### ISSUE THREAD

**Issue by cathyr1** [WoWManiaUK/Redemption#4929]
This quest https://www.wow-mania.com/armory/?quest=8743 seems to be missing. The NPC https://www.wow-mania.com/armory/?npc=15693 has yellow questionmark above head but its impossible to speak with him, he does not offer this final quest.

I´m sorry if this is a duplicate and someone already posted but I got various information so I don´t know what is correct and what to do - if we can expect fix or will have to contact GM ingame or this will never be fixed. But then its weird why I saw ppl with both title and mount.

Thanks for any explanation.

**Comment by Rushor** [comment]
This is disabled since the event and the quests have been disabled on fully progressed WotlK Realms

**Comment by cathyr1** [comment]
OK, thanks for quick answer. And what about the ppl that have the title?
