### ISSUE TITLE
Shadowmourne - Chaos Bane

### ISSUE THREAD

**Issue by bLeyaa** [WoWManiaUK/Redemption#4931]
**Links:** http://www.wow-mania.com/armory?item=49623 / https://www.wow-mania.com/armory/?spell=73422

**What is Happening:** When the player gets the Chaos Bane buff and swaps the weapon, the buff disappears.

**What Should happen:** Chaos Bane buff should remain on the player even after swapping Shadowmourne to a different weapon.

https://youtu.be/rNVoMGRg4QE?t=189

**_P.S. Soul Fragments should be removed as they are, nothing should be changed with them. Only the Chaos Bane buff after the max stack of fragments is reached._**

**Comment by GMMetaxa** [comment]
No priority

**Comment by svijetlo** [comment]
btw correct me if im wrong 
as i remember by the end of wotlk (335) every weapon proc buff was changed to be gone if you remove weapon i know it form weapon Last Word, and as chaos bane is buff you get form item/weapon it should be gone if you remove item as if it stay you could stack up buffs

**Comment by Keader** [comment]
yeah, on video has a proof.
issue is valid

**Comment by Keader** [comment]
fixed
