### ISSUE TITLE
[Item] The Black Heart

### ISSUE THREAD

**Issue by bLeyaa** [WoWManiaUK/Redemption#4932]
**Links:** https://www.wow-mania.com/armory/?item=47216

**What is Happening:** Item is currently proccing from offensive melee attacks.

**What Should happen:** Item should only proc when being struck by a melee attack, as indicated on the tooltip.

**Comment by GMMetaxa** [comment]
No priority

**Comment by Keader** [comment]
@GMMetaxa please stop close issues.
Is Developer/Tester work, check each issue and determine what is/not priority.

@bLeyaa It's correct.
Trinket proc flags:
![image](https://user-images.githubusercontent.com/7120913/91851678-fbca9180-ec35-11ea-9c77-aa93c609bb8f.png)
It means: spells that use melee weapon can proc it too, not just auto-attack

**Comment by GMMetaxa** [comment]
@Keader Nothing is closed by me without consultance from Janitor.

**Comment by bLeyaa** [comment]
@Keader I think u misunderstood, the trinket is proccing on me if i am attacking, instead of when i am attacked.

**Comment by Keader** [comment]
Ahhh so it's wrong lul

**Comment by Rushor** [comment]
can i try fixing it? :>
