### ISSUE TITLE
Living Inferno - Death Grip

### ISSUE THREAD

**Issue by bLeyaa** [WoWManiaUK/Redemption#4933]
**Links:** Related to #4879 

**What is Happening:** The grip effect of Death Grip is gone, but the taunt still seems to work. The Living Inferno should be immune to the taunt effect as well. 

Should check if the other taunts work on the mob as well? Don't have info on other taunts at the moment.

**Comment by GMMetaxa** [comment]
No priority

**Comment by Keader** [comment]
yeah, deathgrip should not taunt it

**Comment by bLeyaa** [comment]
@Keader @svijetlo 

If someone can also check other taunt abilities please.
Unless the fix is not related to spell but the actual taunt immunity?

**Comment by Keader** [comment]
@svijetlo how you confirmed it?
Because... i tested in ptr, and taunt or death grip is not "taunting" it.
