### ISSUE TITLE
[Spell] Whirlwind

### ISSUE THREAD

**Issue by bLeyaa** [WoWManiaUK/Redemption#4934]
**Links:** https://www.wow-mania.com/armory/?spell=1680

**What is Happening:** Whirlwind has a weird behaviour, from what i've noticed on targets with bigger hit box, if it's used at max melee range. What happens is that the spell will go off, but there will be no damage. However, if you come in closer the the boss the ability will work correctly. This is best tested on bosses like Halion and Sindragosa.

**What Should happen:** Whirlwind should work from same distance as any other melee ability, in fact with a higher range - 8yd as indicated on the tooltip.

**Comment by Oganku** [comment]
Similar to #4330 .

**Comment by svijetlo** [comment]
same is for some other spells like killing spree on rogue and divine storm on paladin , i remember Kaidan (or how ever his name is he was dev here some time ago  ) explaining me it has smt to do with scale of hit box on boss like halion

**Comment by GMMetaxa** [comment]
No priority.

**Comment by svijetlo** [comment]
all tho as i remember this can not be changed
