### ISSUE TITLE
[Spell] Seed of Corruption

### ISSUE THREAD

**Issue by bLeyaa** [WoWManiaUK/Redemption#4935]
**Links:** http://www.wow-mania.com/armory?spell=47836

**What is Happening:** 

"_Imbeds a demon seed in the enemy target, causing 1896 to 1902 Shadow damage over 18 sec. **When the target takes 1518 total damage or dies**, the seed will inflict 1959 to 2277 Shadow damage to all enemies within 15 yards of the target. Only one Corruption spell per Warlock can be active on any one target._ "

Currently if the target dies before taking 1518 damage, the Seed of Corruption will not explode to the nearby enemies. Even if the target is below 1518 hp and takes a single hit over that, it will not explode.

**What Should happen:** Seed of Corruption should explode to nearby enemies after 1518 damage or more was done to the target OR the target dies before that.

**Comment by GMMetaxa** [comment]
No priority

**Comment by bLeyaa** [comment]
Not to open a new topic as it's related to same spell, but Seed of Corruption currently ignores the line of sight rule.

It should only hit enemies withing line of sight.

> Patch 2.3.0 (13-Nov-2007): Seed of Corruption detonation will now obey line of sight.

https://wowwiki.fandom.com/wiki/Seed_of_Corruption#:~:text=Seed%20of%20Corruption%2C%20often%20abbreviated,a%20specific%20amount%20of%20damage.

**Comment by Keader** [comment]
Fixed LoS issue.
But it should not proc with death, only with damage taken...
Has a comment in code about it:

"triggered only on amount drop (not on death)"

**Comment by bLeyaa** [comment]
The tooltip says it on death??

**Comment by Keader** [comment]
hmm, that is true...

**Comment by Keader** [comment]
k, now proc on death too
