### ISSUE TITLE
[NPC] Rotting Frost Giant

### ISSUE THREAD

**Issue by bLeyaa** [WoWManiaUK/Redemption#4936]
**Links:** http://www.wow-mania.com/armory?npc=38494

# 1
**What is Happening:** Currently the giant can be stunned and feared indefinitely. If you spam [Turn Evil](http://www.wow-mania.com/armory?spell=10326) on him, he will not be able to attack and will not cast the plague (even tho there will be a warning message saying he casted it on a player).

**What Should happen:** Giant should be immune to all forms of CC. If you look at any videos posted below (or any other for that matter) u wont see the boss being cced by spells like charge / stun / fear.

https://www.youtube.com/watch?v=kOEdWbmPQ4g
https://www.youtube.com/watch?v=Lr_nnAYZCyE
https://www.youtube.com/watch?v=KoEezS05JY0

# 2
Boss should be immune to kick when casting Frost Breath, which is currently missing. Can refer to above videos as well.

# 3
When the giant dies, the plague on players should instantly disappear, at the moment plague remains on players after giant's death. 
https://youtu.be/Lr_nnAYZCyE?t=218
https://www.youtube.com/watch?v=ZGkF36YfR0A

**Comment by GMMetaxa** [comment]
No priority

**Comment by Keader** [comment]
valid too.
i can confirm 1 and 3 bugs.
Not sure about 2, will research

**Comment by svijetlo** [comment]
yes frost breath should not be interuptable

**Comment by Keader** [comment]
Fixed giant immunity.
But death plague already got removed when giant dies... (tested in ptr)

**Comment by bLeyaa** [comment]
@Keader regression on below, just had the plague stay in 10hc

>3
When the giant dies, the plague on players should instantly disappear, at the moment plague remains on players after giant's death.
https://youtu.be/Lr_nnAYZCyE?t=218
https://www.youtube.com/watch?v=ZGkF36YfR0A
