### ISSUE TITLE
A Simple Re-Quest

### ISSUE THREAD

**Issue by SylferTheOrphan** [WoWManiaUK/Redemption#4937]
I cant believe iam writing here instead getting just a SIMPLE help via GM.
I make this clear and short i support the server and put alot real money inside and i will DEF: LEAVE if i dont get this achievment.. iam trough!!  This achievment have no title or special reward but thats not the fact its just statement!  I tryed doing 5 days the same daily ive tryed doing 5 days differnt dailys but everytime when i reach 3/5 or 4/5 it set back to 1/5   now after 20000000000000000000000000000000000000000000 trys .. ok be honest i guess it was arround 25 days which means 4-5 full trys its set back to 1/5 and iam in enrage mode.. i dont please for this you give me the achievment or i leave i dont discuss this point!

**Comment by svijetlo** [comment]
you are here as it is game bug that GM can not help with sadly so he pointed you to this place, your report will be checked and if found broken fix will be made to everyone's benefit

**Comment by Oganku** [comment]
You have to do a single daily quest 5 days in a row. The same quest, 5 times in a row without skipping days. I've got it on multiple characters and I'm very certain it didn't break recently.

**Comment by GMMetaxa** [comment]
@SylferTheOrphan 
For your information: We usually don't respond very well to threats. 
Remake if you have managed to find out how to post something on Github.
