### ISSUE TITLE
Resetting classic instances

### ISSUE THREAD

**Issue by Sierbahnn** [WoWManiaUK/Redemption#4938]
**Links:**

**What is Happening:**
I empty out Stratholme, exit, and press Reset all Instances. 
I enter. None of the mobs are there, and the same instance-save is still in effect.

**What Should happen:**
Upon reentry there should be a "fresh" instance, with all the mobs respawned.

I have tested grouping to reset, and waiting 30 minutes, but the only way to reliably reset the instance is to join another group on an instance and then come back later, preferably through rdf.

**Comment by Oganku** [comment]
If your instances are set to heroic difficulty by default, it will fail to reset normal instances, switch to normal difficulty to reset them properly. It might not be intended to be that way, so I'll leave it open just to verify if the behavior should be changed. Meanwhile you can manually switch to avoid the issue.

**Comment by Sierbahnn** [comment]
Aha! Brilliant! Thank you very much!

**Comment by jeyrella** [comment]
Have marked as technically not as per blizzard, but low priority as there is a viable workaround. 
@Keader depends on how much effort this will be.  If huge amounts, don't worry, will leave as is.

**Comment by Keader** [comment]
![image](https://user-images.githubusercontent.com/7120913/92247849-2cacff80-ee9e-11ea-82bd-967788a88445.png)
Reset only normal is blizzlike

**Comment by jeyrella** [comment]
so it is.  https://wow.gamepedia.com/index.php?title=Instance_reset&oldid=2292532
I should have done better research.  Thanks @Keader

**Comment by jeyrella** [comment]
@Sierbahnn can you DM me in Discord please :)  thanks!
