### ISSUE TITLE
[Warlock] Banish does not cancel when cast second time

### ISSUE THREAD

**Issue by Kri133** [WoWManiaUK/Redemption#4939]
**Links:**  https://www.wowhead.com/spell=710/banish

**What is Happening:**  Upon 1st Cast, the spell performs as normal on a valid target, upon 2cnd cast within the already active spell, Banish, is not removing itself per description.

**What Should happen:** Casting Banish again on the target will cancel the effect. - Confirmed on a Demon in Outland on a Lvl61 & another guild lock on an elemental.

**Comment by jeyrella** [comment]
Confirmed

Note: spell 710 is the 20-second rank 1.    The rank 2 player spell is ID 18746.
