### ISSUE TITLE
Razorscale bugged

### ISSUE THREAD

**Issue by Demokab** [WoWManiaUK/Redemption#4940]
**Links:**

**What is Happening:**
She bug's out if she takes off again after first ground phase, as the harpoons remain in her, making it impossible to bring her down again. This prevents use from doing the Iron Dwarf, Medium Rare achievement in one sitting.

**What Should happen:**
Harpoons should reset to being repaired status

**Comment by Rushor** [comment]
will check that

**Comment by jeyrella** [comment]
@Demokab @Rushor This has worked fine several times in the past few weeks on Redemption in both 10 and 25 man modes, as our guild have been doing this very achievement.

Might need more information about how to reproduce this one.

**Comment by jeyrella** [comment]
Could not reproduce in 5 tries, in either 10 or 25 man.  Harpoons reset perfectly, whether watchers were alive or not.

This is the first one of the 25's with watchers killed, others were identical:  https://youtu.be/tGDg6qqsvGQ

Has been working fine on live for at least 4 raids too.
Will close as this seems limited to this one occasion and without reproducibilty it will be hard to figure out what went wrong - if you can describe anything specific or unusual I'm more than happy to retest.

**Comment by Demokab** [comment]
So it's just us getting unlucky and it bugging every single time we attempt that achievement on 10 man? Seems highly unlikely.

I will come back with more evidence next time we attempt it

**Comment by jeyrella** [comment]
Please, that would be great.  If you can, record the fight as video so we can watch how it happens.

**Comment by jeyrella** [comment]
And no, that was just the vid I posted, worked keeping them alive too.
