### ISSUE TITLE
[Quest] Data Mining

### ISSUE THREAD

**Issue by Slysam** [WoWManiaUK/Redemption#4942]
**Links:**
https://wotlkdb.com/?quest=12860
https://wotlkdb.com/?npc=29746

**What is Happening:**
Often when 'scanning' the Databanks as part of the quest, they simply do not provide quest progress, making the quest take a frustrating and inordinate amount of time to complete. Scanning something like 20 databanks provided only 3 quest progress(out of 7) and it is unclear why they do not count. Sometimes scanning the same databank again would provide progress where it didn't before, but often scanning the same databank multiple times would produce no change in the results.

Edit: I noticed that it seems like Databanks that the guardians scan seem to not give you quest progress where ones they haven't scanned yet do? I don't know if this is true, just something I noticed as possible while trying to finish the quest.

**What Should happen:**
Every Databank should provide quest progress 100% of the time. Looking at the WoWhead for the quest itself, it seems that the databanks were sometimes bugged, but I didn't see any kind of solution that could have fixed the problem there either(and most of those reports are very old, so I do not know if it was ever fixed).

**Comment by Rushor** [comment]
Checking

**Comment by jeyrella** [comment]
Confirmed.  They did all eventually work but some needed 5 or 6 channels to complete successfully.  Targeting or not targeting does not seem to make difference, yet some do work first time.

https://youtu.be/pSztfKBzgrk

Can't immediately espy a pattern between them

**Comment by Rushor** [comment]
try now pls

**Comment by Zanguin-ManiaTester** [comment]
https://youtu.be/Q19MZ8XXl4Y

Fix confirmed, thanks :)
