### ISSUE TITLE
[Item] Herkumi War Token

### ISSUE THREAD

**Issue by bLeyaa** [WoWManiaUK/Redemption#4943]
**Links:** http://www.wow-mania.com/armory?item=50355

**What is Happening:** Trinket currently procs from casting Divine Storm, even if there is no opponents around the player.

**What Should happen:** Trinket should only proc upon hitting an opponent.

P.S. Not sure if this is related to the trinket or the ability, posted it as trinket issue.

**Comment by Oganku** [comment]
Most likely due to the fact that the Divine Storm "hits yourself" to heal you.

**Comment by Keader** [comment]
fixed
