### ISSUE TITLE
[Quest] Past Endeavors

### ISSUE THREAD

**Issue by cathyr1** [WoWManiaUK/Redemption#4945]
The quest https://www.wow-mania.com/armory/?quest=5057 should be available only for the horde. However this is offered to alliance as well and it cannot be completed cause the NPC in Thunder Bluff is hostile.
![Quest](https://user-images.githubusercontent.com/30184491/92301289-ce962000-ef62-11ea-97d5-e75f0b927c2c.png)

**Comment by jeyrella** [comment]
Confirmed.  
![image](https://user-images.githubusercontent.com/46089380/92302754-811bb200-ef66-11ea-8424-60109d3aa3bb.png)
https://youtu.be/n22IEk_9-ks

The quest chain 5054 through 5056 should be available to both factions, then 5057 should be Horde-only.

**Comment by Rushor** [comment]
should be only available for horde now
