### ISSUE TITLE
Hunter - Tame pet

### ISSUE THREAD

**Issue by iriemon69a** [WoWManiaUK/Redemption#4946]
**Links:**

**What is Happening:**
I have completed the hunter tame pet quest line, however even after re logging I cannot successfully tame a pet.

**What Should happen:**

Be able to tame a pet.

**Comment by iriemon69a** [comment]
toon is a Dwarf Hunter, account irirmon69

**Comment by bLeyaa** [comment]
I would suggest you to remove the comment with your account name, for security reasons.

**Comment by Rushor** [comment]
you must use the tame pet spell

**Comment by Rushor** [comment]
invalid https://i.imgur.com/vwBf7Kc.jpg https://i.imgur.com/PcqKp0N.jpeg

depending on you level sometimes the taming process fails. that is intended - then you must repeat it then simply :)
