### ISSUE TITLE
[Boss] Anzu (Sethekk Halls)

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#4947]
**Links:** https://wowwiki.fandom.com/wiki/Anzu
https://www.youtube.com/watch?v=U0dzJ0DCDPg
https://www.youtube.com/watch?v=p107LMj366A
https://www.youtube.com/watch?v=7vVvg1LhF20

**What is Happening:** The Anzu boss fight in Sethekk Halls is currently missing many of its mechanics and provides an incomplete experience as the final challenge in the old Swift Flight Form quest line. Considering this boss is farmed by people who desire to obtain its rare mount, it kinda sucks having to deal with a broken fight multiple times.

**What Should happen:**

1. The 3 bird spirits that should be present during the encounter are simply missing entirely. They should be inactive and become active an provide a certain buff to the group once they become activated by any druid's HoTs. They should remain active during the HoT, and go back to being inactive once it ends. [The first video shows the bird statues in action at 1:35.](https://youtu.be/U0dzJ0DCDPg?t=95)
![image](https://user-images.githubusercontent.com/34783736/92316923-83aef380-efc8-11ea-8370-19cc20117903.png)

2. Currently, when Anzu banishes himself, he just sits there and does nothing for a full minute, making the group just wait. He should instead spawn a small swarm of birds (Brood of Anzu) and banish himself. Upon defeating all the birds, he will automatically exit self-banishment. If for some reason the birds are left alive, he will still exit banishment after 1 minute. All 3 videos above show this behavior when the boss reaches 66% and 33% health. 
*Also currently if you push him past those health threshold while he is casting cyclone of feathers or paralyzing screech, you can sometimes skip a transition completely.

The following 2 issues are only visual:

3. The boss has a much bigger model than he should. All videos show him as about the size of the mount, but he is currently nearly double the size.

4. The summoning animation that happens when you use the key in the center of the room is missing. [The first video](https://www.youtube.com/watch?v=U0dzJ0DCDPg), as well as [the second at 1:20](https://youtu.be/p107LMj366A?t=80), show the animation/event that should happen.

**Comment by Rushor** [comment]
try now pls - all 4 points should be fixed. only the thing with the Brood of Anzu is like this:

Brood of Anzu will be spawned and after 45 seconds the banish will be removed

**Comment by Oganku** [comment]
All points work really well, such a big improvement!

Only small detail is that the statues apply a 5s buff as soon as they're hotted, and won't refresh it themselves while they remain hotted. I really don't mind leaving as-is, since it's very minor and the rest is perfect.
