### ISSUE TITLE
[NPC] Gordunni Backbreaker underneath texture

### ISSUE THREAD

**Issue by jeyrella** [WoWManiaUK/Redemption#4948]
**Links:**
NPC: 22143

**What is Happening:**
This specific Gordunni Backbreaker is walking around inside the texture, and thus evades combat if he is engaged.
![image](https://user-images.githubusercontent.com/46089380/92329091-1f8a3f00-f05d-11ea-9cf0-fe62bb322fe7.png)

**What Should happen:**
z-axis should be adjusted so he is walking on top of the texture.

**Comment by Rushor** [comment]
is a strange map position, hard to fix. removed the random movement of him

**Comment by jeyrella** [comment]
looks better.  
![image](https://user-images.githubusercontent.com/46089380/92335279-b2db6880-f08d-11ea-9041-ac7e45a1c234.png)

However - is it something wrong with the floor texture perhaps?  The one outside also has a habit of doing this once engaged, although out of combat he happily stands on top of it.
![image](https://user-images.githubusercontent.com/46089380/92335338-136aa580-f08e-11ea-892d-019329f3e58d.png)


And actually, the one inside also does this, plus walks through the doorway walls too
![image](https://user-images.githubusercontent.com/46089380/92335376-5593e700-f08e-11ea-87ef-97329e8b5d77.png)

neither of these though seem to force them to evade, however it does become impossible for the player to target occasionally as they can disappear entirely below the floor in some exact spots

**Comment by jeyrella** [comment]
![image](https://user-images.githubusercontent.com/46089380/92335444-e1a60e80-f08e-11ea-937e-edfc1f3efd29.png)

**Comment by Rushor** [comment]
Well then i think we must remove them or move to a different place

**Comment by Rushor** [comment]
moved the creatures to the outside, there is not much more we can do to fix this
