### ISSUE TITLE
[Quest] "HELP!" - 9923

### ISSUE THREAD

**Issue by jeyrella** [WoWManiaUK/Redemption#4949]
**Links:**
Quest:  9923

**What is Happening:**
Text on quest completion shows "$n" instead of player's name.
![image](https://user-images.githubusercontent.com/46089380/92335516-71e45380-f08f-11ea-8d99-60d243d83d6b.png)

**What Should happen:**
Text should show player's name.

**Comment by Rushor** [comment]
try now pls

**Comment by Zanguin-ManiaTester** [comment]
![Help!](https://user-images.githubusercontent.com/47272908/92384053-af88c100-f10f-11ea-9be5-acb8c3af526c.png)

Fix confirmed, thanks!
