### ISSUE TITLE
Random Dungeon Finder not working, Horde side

### ISSUE THREAD

**Issue by Snafu410** [WoWManiaUK/Redemption#4950]
**Links:**

**What is Happening:**
Random Dungeon Finder not working, Horde side

**What Should happen:**

**Comment by jeyrella** [comment]
Works fine.

**Comment by Snafu410** [comment]
Please log in and check cause it  is not working

**Comment by Snafu410** [comment]
people in world been on about it all day

**Comment by jeyrella** [comment]
Raise a GM ticket, this is not a code issue.
