### ISSUE TITLE
[Item] Libram of Defiance

### ISSUE THREAD

**Issue by cathyr1** [WoWManiaUK/Redemption#4952]
This item https://www.wow-mania.com/armory/?item=47664 has a 30 second cooldown after being equipped to work but there should be no cooldown. All librams should work immediately when swapped. Its similar problem as in Issue No. #4673.

Maybe would be better to test all paladin, DK, druid and shaman items in this slot to check if all of them works correctly.

**Comment by bLeyaa** [comment]
Proof that they shouldn't have an ICD?

**Comment by svijetlo** [comment]
they should not have icd as it is common to swap them in fights like weapons also , you should not use Libram of Defiance as prot paly it is just bad

**Comment by svijetlo** [comment]
i also tested this i can not reproduce it mine works fine , if anyone other is willing to give it go sure

**Comment by cathyr1** [comment]
Tried again after today´s release (deleted cache, used launcher for possible patch) and still broken for me. First 6 Hammer of the Righteous used after swap did not caused the buff but next 6 worked 5 times.

**Comment by Keader** [comment]
any proof?

**Comment by svijetlo** [comment]
ok 
i had more free time and tested this to more detail 
anyhow in 30 sec after equip  Libram of Defiance  will never proc so it has internal cd 
one again as prot paly pls dont use  Libram of Defiance

**Comment by Keader** [comment]
i mean, any proof that it should not get cd when equipped?

**Comment by svijetlo** [comment]
libram are like weapon has no internal CD i switch librams all the time , as i do not use this particular one at all i never noticed it has one , i can not find any proof atm as i em busy a lot every day with work but will find one as soon i get more time
