### ISSUE TITLE
[NPC] NPCs Duplicated At Argent Tournament

### ISSUE THREAD

**Issue by Slysam** [WoWManiaUK/Redemption#4954]
**Links:**
I can't find any links to the specific NPC in question, but they spawn semi-frequently at the Tournament grounds.

**What is Happening:**
There are multiple NPCs spawned that take part in the events where they walk up to the arena and speak to the other leaders. The ones I've personally observed are Thrall/Garrosh/Varian/Jaina and their various escorts(like the Kor'kron elite that accompanies thrall and garrosh). They will play their voice lines twice and their text gets duplicated into the text box as well. It doesn't really do anything other than just spam the text/sound and can get somewhat annoying if you're in the tournament grounds.

**What Should happen:**
There should only be one copy of each NPC.

**Comment by jeyrella** [comment]
Looking into which script this is.  Is a matter of seconds to fix.

**Comment by Rushor** [comment]
no more duplicates
