### ISSUE TITLE
[Spell/Mage] Combustion grants crit chance stacks incorrectly

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#4956]
**Links:** https://www.wow-mania.com/armory/?spell=11129

**What is Happening:** 
1. The combustion effect lasts until 6 crits have been done.

2. Combustion doesn't grant additional stacks when a critical hit is made.

**What Should happen:**

- [x] 1. Combustion should last until only 3 non-periodical critical strikes are made with fire spells. Not 6.

- [x] 2. Combustion should grant a stack for every fire damage spell that hits, not only non-crits.

Proof: 
![image](https://user-images.githubusercontent.com/34783736/92663353-05f02e00-f2cf-11ea-8c6f-c77d5ef0cf83.png)

**Comment by Keader** [comment]
fixed

**Comment by jeyrella** [comment]
- [x]  1. Combustion should last until only 3 non-periodical critical strikes are made with fire spells. Not 6.
- [x]  2. Combustion should grant a stack for every fire damage spell that hits, not only non-crits.
https://youtu.be/YjViWE5j_Yg
