### ISSUE TITLE
[Spell/Warlock] Immolation Aura persists after the player exits Demon form

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#4957]
**Links:** https://www.wow-mania.com/armory/?spell=50589
https://www.wow-mania.com/armory/?spell=59673
https://ptr.wowhead.com/forums&topic=163379/metamorphosis-question

**What is Happening:** [Immolation Aura](https://www.wow-mania.com/armory/?spell=50589) currently persists even after the player exits [Demon form](https://www.wow-mania.com/armory/?spell=59673).

**What Should happen:** Once the aura from [Metamorphosis](https://www.wow-mania.com/armory/?spell=59673) ends, Immolation Aura should be removed from the player regardless of the remaining duration, as the spell requires Demon form to occur. From [this wowhead post](https://ptr.wowhead.com/forums&topic=163379/metamorphosis-question), we clearly see that 

> If you glyph into Meta you can get in 2 Immolate Auras with 1 meta. The second one won't run the full duration though.

The reason being that Metamorphosis will expire before the second aura runs for its full duration.

**Comment by Keader** [comment]
i realy think that it's correct.
i remember to use it in blizzard servers...

**Comment by Oganku** [comment]
It's hard to find info about that. The only mention being the one I quoted. I will leave it open if others want to search more, but it's fine either way for me.

**Comment by bLeyaa** [comment]
![Screenshot_20200910-145014_Samsung Internet](https://user-images.githubusercontent.com/61625377/92731201-12c75d00-f375-11ea-9577-b425870f47b2.jpg)

https://web.archive.org/web/20150802013921/http://forums.elitistjerks.com/topic/99187-demonology-releasing-the-demon-in-you/

**Comment by Keader** [comment]
perfect, ty @bLeyaa 
fixing it.

**Comment by Keader** [comment]
fixed
