### ISSUE TITLE
[Spell] Acclimation not proccing from all spell damage

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#4958]
**Links:** https://www.wow-mania.com/armory/?spell=50152
[Issue #2113](https://github.com/WoWManiaUK/Redemption/issues/2113)
https://www.wow-mania.com/armory/?spell=75885
https://www.wow-mania.com/armory/?spell=70084

**What is Happening:** Acclimation is currently not proccing from all spell damage as intended. It works on direct sources, and some aoe (blood queen and pp) but not others like [Frost Aura](https://www.wow-mania.com/armory/?spell=70084) from Sindragosa or [Blazing Aura](https://www.wow-mania.com/armory/?spell=75885).

**What Should happen:** Looking through retail comments and especially issue #2113, we can see that:

> All spell damage that is checked as a hit can now proc Acclimation, including ground/area spells, spells that use ranged weapon and rogue's instant/wound poison. Periodic debuff ticks cannot and should not. 

From the fix from 2019. This makes this important talent for the niche spec of frost dk tank, kind of half useless.

**Comment by Keader** [comment]
test now
