### ISSUE TITLE
Elixir Master of Alchemy

### ISSUE THREAD

**Issue by irez-s** [WoWManiaUK/Redemption#4959]
flask of endless rage(https://wotlk-twinhead.twinstar.cz/?item=46377), flask of frost wyrm(https://wotlk-twinhead.twinstar.cz/?item=46376)

I recently got Elixir Master specialization of Alchemy. And i have crafted above 2 flasks, each 15 times, but Elixir Master which has about 20% of proccing only occured once.

Could you guys confirm this issue? or was it sheer bad luck for me xD

Thanks in advance.

**Comment by jeyrella** [comment]
Sheer RNG.
