### ISSUE TITLE
[Spell/Boss] Sindragosa's Frost Aura wrong damage type

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#4960]
**Links:** https://www.wow-mania.com/armory/?spell=70084
https://www.wow-mania.com/armory/?spell=71050
https://www.wow-mania.com/armory/?spell=71051
https://www.wow-mania.com/armory/?spell=71052
https://www.wow-mania.com/armory/?spell=75886

**What is Happening:** Sindragosa's Frost Aura (4 links above for all 4 difficulties) currently deals non-school damage. It is treated as frost damage for resistance calculation, but shows up as "Red" damage (physical) in floating combat text. This makes abilities that proc on spell hit unable to proc from it (such as Acclimation from #4958).  

**What Should happen:** If we compare to a Living Inferno's Blazing Aura (which acts properly and procs correct abilities):

![image](https://user-images.githubusercontent.com/34783736/92839527-0f9c9300-f3ae-11ea-9251-c706fa9da53f.png)
![image](https://user-images.githubusercontent.com/34783736/92839599-293dda80-f3ae-11ea-84d5-e6127fc0d531.png)

Blazing Aura clearly states "School Damage", which shows up as purple (magic) damage and procs acclimation.
Frost aura does NOT state "School Damage", and even though it is calculated as a frost damage-type, it is not seen as magical damage.

Frost Aura should deal School Damage of the corresponding value.

**Comment by Keader** [comment]
Keader suffers 2700 Frost damage from Grandmaster's Training Dummy's Frost Aura.
Keader suffers 2700 Frost damage from Grandmaster's Training Dummy's Frost Aura.
Keader suffers 2700 Frost damage from Grandmaster's Training Dummy's Frost Aura.

What is wrong is acclimation, not frost aura.
anyway, fixed.
