### ISSUE TITLE
[Spell/Boss] Living Inferno's Blazing Aura

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#4961]
**Links:** https://www.wow-mania.com/armory/?spell=75885
https://www.wow-mania.com/armory/?spell=75886
https://www.wow-mania.com/armory/?spell=75887
https://www.wow-mania.com/armory/?npc=40681
http://www.worldoflogs.com/reports/48ne8g4kkte9b59h/spell/75887/
https://www.wowhead.com/spell=75886/blazing-aura#changelog

**What is Happening:** [Blazing Aura](https://www.wow-mania.com/armory/?spell=75886) from [Living Infernos](https://www.wow-mania.com/armory/?npc=40681) is applying the wrong damage aura. The tooltip on the mob's buff corresponds to 75885, which should deal 3700-4300 fire damage every 2 seconds. 
![image](https://user-images.githubusercontent.com/34783736/92840053-a8331300-f3ae-11ea-849f-f848dfa2aafa.png)
However, the damage players receive is more around ~7000 damage per hit, as seen in the image below.

![Blazing Aura](https://user-images.githubusercontent.com/34783736/92840412-0bbd4080-f3af-11ea-886b-6ef83a6d8b05.png)

This seems to correspond to the mysterious spell 75887, which should not even be used by anything in the game. It exists in the files, but references such as world of logs, or wowhead show that this damage is wrong.

**What Should happen:** As per the logs linked above, as well as wowhead previous data, we see that the damage Blazing Aura should do is the one from spells 75885 and 75886 (3700 to 4300).

![image](https://user-images.githubusercontent.com/34783736/92840780-7ff7e400-f3af-11ea-9270-95ff8b15aac4.png)

![image](https://user-images.githubusercontent.com/34783736/92840751-78383f80-f3af-11ea-905d-cdbe4b0b9eff.png)

**Comment by Keader** [comment]
Wrong.

75886 Blazing Aura is 10 man spell.
75887 Blazing Aura is 25 man spell.

i can confirm with sniffs, that spells used are correct.
You summoned it inside of a instance, so it cast correct spellid (corresponding of difficulty)
in 10 man damage: ~3699 to 4300
in 25 man damage: ~6937 to 8062
