### ISSUE TITLE
Shadowmeld - aggro dropping

### ISSUE THREAD

**Issue by bLeyaa** [WoWManiaUK/Redemption#4962]
**Links:** https://www.wow-mania.com/armory/?spell=62199 / https://www.wow-mania.com/armory/?spell=62196 (not sure which one is it)

**What is Happening:** Currently if you shadowmeld in combat, you will drop all your threat - reset it.

**What Should happen:** Threat should be restored upon leaving shadowmeld.

![image](https://user-images.githubusercontent.com/61625377/92843923-928d1000-f3e5-11ea-8e84-9fc20e93ff86.png)

**Comment by Keader** [comment]
try now pls

**Comment by bLeyaa** [comment]
@Keader @Rushor @svijetlo 

Still broken

**Comment by svijetlo** [comment]
will check later busy irl atm

**Comment by Keader** [comment]
Fixed.
Not Regression atm, just a super old hack conflicting with it sometimes.
