### ISSUE TITLE
[NPC] Decaying Colossus - missing immunity

### ISSUE THREAD

**Issue by bLeyaa** [WoWManiaUK/Redemption#4963]
**Links:** http://www.wow-mania.com/armory?npc=36880

**What is Happening:** Giant is missing immunity to [Shackle Undead](https://www.wow-mania.com/armory/?spell=10955)

**What Should happen:** Giant should be immune to CC. [Wowhead comment](https://www.wowhead.com/npc=36880/decaying-colossus#comments): 
![image](https://user-images.githubusercontent.com/61625377/92867482-fa9d1f80-f400-11ea-8514-8d079eca73ad.png)

Now, it doesn't say for any other abilities in the comment but i strongly believe he should be immune to similar effects and stuns/fears. I'll leave it up to you to decide what u want to do as finding this specific info is near to impossible..

**Comment by Rushor** [comment]
should be immune now
