### ISSUE TITLE
[Spell] Gift of the Giants - Zone restriction

### ISSUE THREAD

**Issue by Rushor** [WoWManiaUK/Redemption#4966]
**Links:**
spell=47012
Reward from quest: https://www.wowhead.com/quest=11982/raining-down-destruction

**What Should happen:**
https://www.wowhead.com/quest=11982/raining-down-destruction#comments:id=862456
Sadly buff disappear if you teleport to orgrimar... ;(((
Not sure would it happen with dalaran but i guess so....
There is through, troll in newbie trolls village on bottom of durotar who can cast on you growth that will last there. Too bad i can't stack it with that giants growth (if it anyway would be even possible)...
There is nothing funnier than tauren on kodo who is bigger than org bank building :d (maybe except mage iceblocking on saph)

The buff should be removed if you leave the questarea close to the questobjecttive. eg. dalaran etc.

This should prevent from abusing with huge scale auras

**Comment by Oganku** [comment]
Buff gets removed when you change areas.
