### ISSUE TITLE
[Instance] Mechanar - Cache of the Legion missing from HC loot table

### ISSUE THREAD

**Issue by Rushor** [WoWManiaUK/Redemption#4967]
**Links:**
https://www.wowhead.com/object=184849/cache-of-the-legion

**What is Happening:**
**What Should happen:**
Mechanar - Cache of the Legion object is missing it's seperate HC Loot. In NH it should not contain a Badge of Justice.

BUT in the HC version there should be a Badge of Justice contained

**Comment by Oganku** [comment]
Badge is only present on HC, but the HC bosses Gatewatcher Gyro-Kill and Gatewatcher Iron-Hand don't drop the Jagged Red/Blue Crystals that you must combine to make the key. They only drop on normal right now.

https://wowwiki.fandom.com/wiki/Cache_of_the_Legion#:~:text=The%20Cache%20of%20the%20Legion,Legion%20Key%5D%20to%20open%20it.

**Comment by Rushor** [comment]
oh good catch

**Comment by Rushor** [comment]
fixed after next restart
