### ISSUE TITLE
[LFG] Stratholme - Service Entrance

### ISSUE THREAD

**Issue by Rushor** [WoWManiaUK/Redemption#4968]
**What is Happening:**
**What Should happen:**

If people get ported to Stratholme - Service Entrance with the LFG tool, they can be ported to the Service Entrance. Problem is, that the port position is BEHIND the door, so they cannot enter because they may do not have the key.

Solution:
Switch Teleport position behind the gate.

Testable:
- telport stratholme
- enter instance
type: .go xyz 3639.05, -3584.54, 138.496

This will be the new teleport position

**Comment by svijetlo** [comment]
Rush i think this should not be change LFG should port you to main enter to Strat , service one was always for ppl with key only or if you bring lockpick rogue , so LFG should never port you to service enter.
as with service door you can skip army wing
LFG should always take you to main doors of city

**Comment by Rushor** [comment]
okay changed to main gate

.go xyz 3395.09, -3380.25, 142.702

**Comment by Oganku** [comment]
https://wowwiki.fandom.com/wiki/Stratholme_(original)

> When using the dungeon finder the end boss, and thus the side of Stratholme your party needs to clear, is determined by the entrance you are ported to. The main gate will lead to the Live Side, while the service entrance will lead to the Undead Side. Players can complete the other side as well, but will not earn credit for completing the dungeon until they destroy the end boss of the appropriate side.

It should port you to the service entrance if rdf matches you for that you. Both taking you to the main entrance is wrong.

**Comment by Rushor** [comment]
Okay will change again. Thanks for the proof

**Comment by Rushor** [comment]
okay changed again to

3639.05, -3584.54, 138.496

i think we must stay it like that, since we caanot check for individual players in the group if they have the key or not. so that is the best solution to prevent stucking withing the lfg tool
