### ISSUE TITLE
Vampiric Curse triggers Corrupted Blood on indirect heals as well

### ISSUE THREAD

**Issue by Kinkywiener** [WoWManiaUK/Redemption#4970]
**Links:**
https://www.wow-mania.com/armory/?spell=70423
https://www.wow-mania.com/armory/?spell=70426#triggered-by
**What is Happening:**
Vampiric Curse triggers Corrupted Blood debuff on indirect heals as well. Makes the target get 5 stacks pretty much immediately after the curse lands. Can easily one shot casters or melees when healed by party healing abilities (Vampiric Embrace) or Judgment of Light.

**What Should happen:**
Corrupted Blood debuff should be applied only from the direct heals.

**Comment by Keader** [comment]
Test now pls

**Comment by Oganku** [comment]
The curse damage scales with the cursed target's spell power. A naked character gets hit by 3k shadow damage per stack (which is correct), but my druid with 3k spell power gets hit for 3583 per tick for a single stack, 8332 with 2, 14248, 21331 for 4 and 29580 for 5. Compared to the expected 3k, 6k, 9k, 12k and 15k, this disparity is huge and grows exponentially. This makes any decently geared caster die extremely fast with even just a few stacks. @Keader

**Comment by Keader** [comment]
and this info should be in main topic.
i will fix this time, but i will not keep backing in solved issues because someone omit information

**Comment by Keader** [comment]
fixed spell scale too

**Comment by mamgy** [comment]
Vampiric Curse still procs all healing, this way Corrupted Blood is at 5 stacks immediately even tho 0 direct heals were casted on the target.

**Comment by Oganku** [comment]
Procs from all indirect heals such as Glyph of Holy Light splashes, and from any buffs gained. 

Ex: Bloodsurge, Enrage, Sts procs, Shadowmourne str stacks...
Idol of the Black Willow buff, Solace buff, basically ANY buff.

Any buff gained apply a stack, which makes it stack incredibly fast even on a non-healer just attacking a single mob.

Also, it does a flat 30% more damage than it should for no reason. (5200, 10400, 15600, 20800, 26000)

**Comment by Keader** [comment]
This is not full regression.
Not proc with direct heals is a regression, fixed.
But proccing with buffs and scaling damage with mods are new issues.
Anyway, fixed everything, test now @Oganku and let me know the result

**Comment by Oganku** [comment]
- [ ] Doesn't scale with damage modifiers anymore.
- [ ] Still grants 1 stack for gaining buffs. Only a maximum of 1 stack at a time, but shouldn't be gained from casting death wish, or transforming to bear form for example.

**Comment by Keader** [comment]
test now

**Comment by Oganku** [comment]
- [ ] Initial cast of HoTs does not apply any stacks

**Comment by Keader** [comment]
try again
