### ISSUE TITLE
[NPC] Plagued Zombie missing abilities

### ISSUE THREAD

**Issue by bLeyaa** [WoWManiaUK/Redemption#4973]
**Links:** http://www.wow-mania.com/armory?npc=38104

**What is Happening:** The spawned mobs are missing their only ability, at the moment they only do melee hits.

**What Should happen:** Plagued Zombies should apply [Infected Wounds](https://www.wow-mania.com/armory/?spell=71157) on hit as well

**Comment by Oganku** [comment]
https://wowwiki.fandom.com/wiki/Precious_(plague-dog)
https://www.wowhead.com/npc=38104/plagued-zombie#abilities:i|mode=n10

Can confirm this from the links above. The ability is missing currently.

**Comment by Rushor** [comment]
will fix

**Comment by Rushor** [comment]
they will now have the aura https://www.wow-mania.com/armory/?spell=71158

on spell proc

  4 (0x4) - Successful melee attack

they will apply https://www.wow-mania.com/armory/?spell=71157
