### ISSUE TITLE
[Dungeon/TBC] The Black Morass (Opening the Dark Portal) Waves Timing

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#4974]
**Links:** https://www.wowhead.com/the-black-morass#comments
https://wowwiki.fandom.com/wiki/Opening_the_Dark_Portal

**What is Happening:** The portals that spawn for each wave in The Black Morass dungeon (similar to Violet Hold) currently spawn far too slowly, slowing down even further after the 8th (?) wave. One can find themselves waiting for several minutes (3-4) for the next portal to spawn, making the instance very tedious to complete.

**What Should happen:**
> Once you destroy the elite in a wave, everyone should kill the remaining non-elites and rest up for the next portal. The key here is pacing: while the next portal will open immediately after you down the elite (or sooner, if you're slow), it's best to have healers and mana-based DPS classes drink up before they start in on the next rift lord/keeper.

But,
> There is time to drink between each Rift if you do this efficiently and quickly.

> Waves 13 through 17
Waves spawn at an accelerated rate, sometimes with as little as one minute between portals.

There are few retail videos from TBC, but from reading all the comments, it seems like this instance's portals behave pretty much exactly like the ones in Violet Hold from Wotlk. There is a timer if you kill them too slowly, where the next portal spawns regardless, but once the keeper of the current portal is dead, the next one should spawn right away, or very shortly, with a longer delay after the boss waves (6, 12 and 18).

**Comment by Rushor** [comment]
Will fix

**Comment by Rushor** [comment]
added some changes to the timings - should work faster now. only after boss spawn there will be a bigger "Break"

But during all trash wave spawns it should work faster

**Comment by jeyrella** [comment]
was this a regression of https://github.com/WoWManiaUK/Redemption/issues/3322 ?

**Comment by Rushor** [comment]
the code was still there, but somehow stopped working - so i changed it a bit
