### ISSUE TITLE
[Dungeon/NPC] Caverns of Time: Escape from Durnholde Keep - Thrall pathing & fight mounting

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#4975]
**Links:** https://wowwiki.fandom.com/wiki/Escape_from_Durnholde_Keep

**What is Happening:** 
1. After reaching Thrall inside the Keep and talking to him to start the first part of the escort, Thrall will ignore any kind of walls and terrain while pathfinding to the armory, then outside the keep all the way to the entrace. This causes him to clip through terrain *a lot* and go through walls often. Players who aren't familiar with the instance will very easily lose track of him, very likely resulting in Thrall's death and a failure of the escort.

2. After defeating Captain Skarloc, Thrall steals his horse to ride to Tarren Mill. However, if you happen to battle the group that patrols the road on your way to Tarren Mill, or any of the bears/spiders, Thrall will dismount to fight, and never re-mount afterwards.

**What Should happen:**
1. Thrall shouldn't try to behave like an ascended being and should respectfully obey the boundaries that are walls.

2. Thrall should re-mount his stolen horse after battles until he reaches the Stables, where he finally leaves his steed to continue on foot. Thrall even emotes to shoo the horse away once he reaches his destination, which looks quite silly right now since he never has his horse up to this point.

> Once you arrive on the outskirts of town, Thrall will ditch the mount and wait for you to speak with him again.

**Comment by jeyrella** [comment]
https://youtu.be/k4pcS-J0yJ0
1.  see @45 secs for the pathing issues.

2.  see 3:10 for the issue of not mounting after pack.  This pack should also turn agressive to player, not stay neutral (which they do even after player attacks them)

3.  there is a 3rd issue, Captain Skarlock should have 2 bodyguards, a [Durnholde Veteran](https://www.wow-mania.com/armory/?npc=17860) and a [Durnhold Warden](https://www.wow-mania.com/armory/?npc=17833)
see https://youtu.be/04dVBrsiFD0?t=386  (but save your ears and turn the sound off)

4.  4th issue, more cosmetic, in that at 1:37 Captain's Skarloc's mount should not despawn, and Thrall should walk up to it and mount it.  as it is, the mount appears out of thin air.

**Comment by Rushor** [comment]
1. Added Debug mode for testing, so player with GM MODE on can instantly start the escort without the conditions (only useful for gms)

**Comment by Rushor** [comment]
2. Mounting should always work now after he first entered and then left combat

**Comment by Rushor** [comment]
3. Captain Skarlock will now his guards

4. Horse should now be there when Captains Skarloc dismounts and will be despawned if Thrall starts riding

**Comment by Rushor** [comment]
Pathing issues cannot be handled since this is mmaps and vmaps related. Sadly as-is

**Comment by Oganku** [comment]
Thrall mounting behavior is good now.

He still clips through the armory wall to exit the keep, but will remain as-is.

One rifleman and his dog casually walk through the middle wall of the keep to go up the stairs too, but probably will remain as-is too.
![image](https://user-images.githubusercontent.com/34783736/93143912-e08c6700-f6b6-11ea-8aae-a98dff5d15b8.png)

**Comment by Rushor** [comment]
> One rifleman and his dog casually walk through the middle wall of the keep to go up the stairs too, but probably will remain as-is too.

fixed that aswell for him!
