### ISSUE TITLE
[NPC] Marshang Ripper bad model

### ISSUE THREAD

**Issue by cathyr1** [WoWManiaUK/Redemption#4976]
These mobs https://www.wow-mania.com/armory/?npc=18130, https://www.wow-mania.com/armory/?npc=18131 and https://www.wow-mania.com/armory/?npc=20196 look different than they should. All of them look like Sporebats but they should look like Nether Rays.

**Comment by jeyrella** [comment]
![image](https://user-images.githubusercontent.com/46089380/93014478-47235f00-f5a9-11ea-9fd8-5bd8d6b1729c.png)
Era-relevant model:  http://www.wowhunterpets.info/pets/marshfang-slicer


![image](https://user-images.githubusercontent.com/46089380/93014576-1c85d600-f5aa-11ea-8d74-9eb8aaf1f651.png)
Era-relevant model:  http://www.wowhunterpets.info/pets/marshfang-ripper

![image](https://user-images.githubusercontent.com/46089380/93014612-4c34de00-f5aa-11ea-916d-cd67212ecf79.png)
Era-relevant model: http://www.wowhunterpets.info/model/Nether_Ray_Green

I guess this is definition of low prio, but I suppose could be relevant for hunters wanting that perfect look

**Comment by Rushor** [comment]
https://www.wowhead.com/npc=18130/marshfang-ripper
https://de.wowhead.com/npc=18131/marschenfangschlitzer
https://de.wowhead.com/npc=20196/blutd%C3%BCrstiger-marschenfang

check model now

**Comment by Rushor** [comment]
models should be correct now
