### ISSUE TITLE
[Item] Deadwood Headdress Feather's

### ISSUE THREAD

**Issue by yoopieb** [WoWManiaUK/Redemption#4977]
**Links:**
Item Deadwood Headdress Feather - http://www.wow-mania.com/armory?item=21377

**What is Happening / What Should happen:**
The Feathers do not drop. After completing the initial quest for the 5 feathers they stop dropping for the repeatable quest after.

I have been around the whole camp where they should drop 2 times as honored, and 1 time as revered ranked.
They should drop off 9 mobs in total killed them all (the rare only 1 time) rest for a total of 3 times minimum and i got 0 feathers.

Hope this is enough information.

Warlocomotif.

**Comment by Rushor** [comment]
condition should be that is should drop after quest 8460 is rewarded?

**Comment by yoopieb** [comment]
https://www.wow-mania.com/armory/?quest=8466

Its a repeatable, but the feathers stopped dropping.

**Comment by Rushor** [comment]
this works fine for me https://i.imgur.com/tPB4n6r.jpeg

after i have rewarded quest https://www.wow-mania.com/armory/?quest=8460 i can always loot those items and they drop. dropchance is about 25 percent.

Can you may recheck that and let a gamemaster confirm that quest https://www.wow-mania.com/armory/?quest=8460 is marked as "rewarded" for your character?

**Comment by Rushor** [comment]
Can you help me to reproduce this?

**Comment by jeyrella** [comment]
Works fine for me here.
![Uploading image.png…]()
