### ISSUE TITLE
[Spell] Paladin Judgments + Seal of Command 

### ISSUE THREAD

**Issue by svijetlo** [WoWManiaUK/Redemption#4978]
**Links:**
http://www.wow-mania.com/armory?spell=53408 and rest of them 
http://www.wow-mania.com/armory?spell=20375

**What is Happening:**
if retribution paladin is ON seal of command and use any Judgement on target it will only hit one target even if there are others enemy around your main target 

**What Should happen:**
while seal of command is ON Judgement should also hit 2 addition targets according to seal of command description **When used with attacks or abilities that strike a single target, this additional Holy damage will strike up to 2 additional targets. Lasts 30 min.**

**Comment by Keader** [comment]
fixed
