### ISSUE TITLE
[NPC] Little Ooze

### ISSUE THREAD

**Issue by bLeyaa** [WoWManiaUK/Redemption#4979]
**Links:** http://www.wow-mania.com/armory?npc=36897

**What is Happening:** Little Ooze is missing immunity to Death Grip, same as the big one was in #4812 

**What Should happen:** Little Ooze should be immune to Death Grip / Taunt.

**Comment by Rushor** [comment]
source?

**Comment by svijetlo** [comment]
need proof form back in time or post can be closed by direct order from Janitor

**Comment by bLeyaa** [comment]
By the order of the Peaky Blinders

https://github.com/TrinityCore/TrinityCore/issues/1993

TrinityCore - 2011

**Comment by bLeyaa** [comment]
https://www.engadget.com/2010-06-03-wow-coms-guide-to-rotface.html

![image](https://user-images.githubusercontent.com/61625377/93032319-3ae2e480-f631-11ea-94d0-5896ddb3c968.png)

**Comment by Rushor** [comment]
For all Future posts - please add such proof if possible. Thank you.

**Comment by bLeyaa** [comment]
I figured it would be fine as it's same as Big Ooze, sorry about that ^^

**Comment by Rushor** [comment]
okay should be immune now to grip
