### ISSUE TITLE
[Buff/Debuff] Rabbit Costume- does not silent you 

### ISSUE THREAD

**Issue by svijetlo** [WoWManiaUK/Redemption#4980]
![WoWScrnShot_091620_210545](https://user-images.githubusercontent.com/61908373/93398630-39f1c300-f87c-11ea-8673-8e3e092c97ba.jpg)
http://www.wow-mania.com/armory?spell=61716
**What is Happening:**
Rabbit Costume while on player player can still do all skills and spells i did 2 fights as rabbit 

**What Should happen:**
one should not be able to cast any skill or spell while transformed in to rabbit

**Comment by Rushor** [comment]
Possible linked spell missing

**Comment by svijetlo** [comment]
http://www.wow-mania.com/armory?spell=61717
http://www.wow-mania.com/armory?item=44792

**Comment by Rushor** [comment]
try again pls - worked for me

**Comment by jeyrella** [comment]
Fixed.  Can still correctly use trinket escapes (EMFH etc)
