### ISSUE TITLE
Savory Deviate Delight buff blocks mounting

### ISSUE THREAD

**Issue by perlokic** [WoWManiaUK/Redemption#4981]
Item:
Savory Deviate Delight: https://www.wow-mania.com/armory/?item=6657

Buffs:
Flip Out https://www.wow-mania.com/armory/?spell=8219
Flip Out https://www.wow-mania.com/armory/?spell=8220

Yaaarrrr: https://www.wow-mania.com/armory/?spell=8221
Yaaarrrr: https://www.wow-mania.com/armory/?spell=8222

**What is Happening:**
After eating a savory deviate delight and receiving one of the buffs above, you can't mount up because you're "in shapeshift form"

**What Should happen:**
Should be able to mount up and ride around as normal with either Flip Out or Yaaarrrr buffs on

Proof in case needed:
https://youtu.be/IHc8ZnIB6KQ?t=111
Video from a guild event back on retail 3.3.5a

**Comment by bLeyaa** [comment]
Isn't this intended? The pirates on that video are not the pirates from Savory Delight buff, it's something else. Savory Delight makes u a human pirate no matter what race you are, these are all dwarves.

**Comment by Oganku** [comment]
https://wowwiki.fandom.com/wiki/Pirates%27_Day
https://classic.wowhead.com/item=6657/savory-deviate-delight#comments

From the wowwiki source above:

> This costume buff may be clicked off but persists through combat, mounting, death, and so on but disappears if shapeshifted.

From wowhead classic:

> 3. You can't mount or use flight paths.

**Comment by perlokic** [comment]
That's not blizzlike at all. You could mount with the deviate buff even back in vanilla, and even now in classic you can. I can find posts as far back as 2006 saying about it. Maybe the video I posted isn't the best example because I didn't put too much time into proofing, because I didn't think I needed to lol. I remember pvping and mounting with that buff on retail.

**Comment by perlokic** [comment]
Also your quote:

> From the wowwiki source above:

> This costume buff may be clicked off but persists through combat, **_mounting_**, death, and so on but disappears if shapeshifted.

**Comment by bLeyaa** [comment]
Okay, after a little bit of digging he seems to be correct. @Oganku @Keader 

https://www.wowhead.com/item=6657/savory-deviate-delight#comments:id=139148
![image](https://user-images.githubusercontent.com/61625377/93659610-4118fc80-fa47-11ea-94f3-b69d1329df6c.png)

https://www.reddit.com/r/classicwow/comments/bps6i5/can_you_mount_while_affected_by_savoury_deviate/ (classic wow subreddit, plenty of comments say it's possible. I would assume below would be the "explanation" as to why its different from other morphs.
![image](https://user-images.githubusercontent.com/61625377/93659620-686fc980-fa47-11ea-9d4d-6c6f4e48b27d.png)

P.S. Shapeshifting and shaman's wolf form should still break the effect. (this currently does not work either, checked both)

**Comment by Oganku** [comment]
My bad, it did get changed in TBC. It is valid.

**Comment by jeyrella** [comment]
Yes, from the same thread
![image](https://user-images.githubusercontent.com/46089380/93663186-c3acb680-fa5d-11ea-98ec-c620ed999e28.png)

**Comment by Keader** [comment]
fixed folks
