### ISSUE TITLE
Spells: Do not reset periodic on refresh auras, if they have stack amount

### ISSUE THREAD

**Issue by Keader** [WoWManiaUK/Redemption#4984]
**What is Happening:**

Last week, we found evidences based in sniffs and warcraft logs, that mechanic used by Lacerate (druid) must be applied for more spells.
Basically, any Damage over Time, should not reset periodic time on reset, if they're refreshing/adding a new stack.

Using lacerate as example:
Lacerate has 3 sec of periodic time (ticks happens each 3 secs).
If lacerate is already applied in a target and next tick will happens in 1 sec and you refresh it, next tick should still happens in 1 sec.

But... in other cases, like Vampiric Touch (Priest), when you refresh it, periodic tick must reset.

**What Should happen:**

Dots with stack amount should not reset periodic on refresh/add new stack.
Dots without stack amount, must still reset periodic on refresh :)

**Comment by bLeyaa** [comment]
Will this affect spells like Corruption and Shadow Word: Pain? As they're constantly refreshed by Shadow Bolts / Mind Flay
