### ISSUE TITLE
[Spell/Rogue] Hack and Slash should proc only on damage

### ISSUE THREAD

**Issue by Keader** [WoWManiaUK/Redemption#4985]
**What is Happening:**

Casting Sap in a enemy, with a sword or axe active, can making Hack and Slash proc and break sap

Like:

![image](https://user-images.githubusercontent.com/7120913/93687964-a34e1d80-fa98-11ea-9b78-13de3117affa.png)

**What Should happen:**

Hack and slash should proc only with damage

**Comment by svijetlo** [comment]
hehe i catch me to it i wanted to make post for this tomorrow atm to drunk to make proper post :D
