### ISSUE TITLE
[Item] Meteorite Crystal

### ISSUE THREAD

**Issue by bLeyaa** [WoWManiaUK/Redemption#4987]
**Links:** http://www.wow-mania.com/armory?item=46051

**What is Happening:** If there is a beacon of light casted on someone and heals are done while the trinket is activated, the stacks will still build up only 1 by 1. 
In addition, Holy Shock spell does not trigger stacks at all. I would assume this is because of the ability being heal/damage at the same time.

**What Should happen:** Casting heals while beacon is present should award 2 stacks each. Holy Shock should award stacks as well

![image](https://user-images.githubusercontent.com/61625377/93705286-501dae80-fb1c-11ea-89c5-b0342b8a6649.png)

One of many comments from https://www.wowhead.com/item=46051/meteorite-crystal#comments:id=772039

**Comment by Keader** [comment]
fixed

**Comment by svijetlo** [comment]
beacon + trinket + trinket still only stacks one by one

**Comment by Keader** [comment]
???
how are you testing it?
tested right now in ptr: https://youtu.be/qK53THh-6I4

**Comment by svijetlo** [comment]
tested it same as you on your vid just re did test but deleted cache 1st it is ok now , lazy to upload vid
P.S. my target was now gnome :D
