### ISSUE TITLE
[Quest] All Is Well That Ends Well - Missing event (partially)

### ISSUE THREAD

**Issue by bLeyaa** [WoWManiaUK/Redemption#4988]
**Links:** https://www.wow-mania.com/armory/?quest=13631 **(**[probably this one as well](https://www.wow-mania.com/armory/?quest=13819)**)**

**What is Happening:** The event happening in Dalaran is partially broken, there is no visual coming from the beacon outside the Alliance side bank.

**What Should happen:** The NPCs come down and do the talk, but the beam going up to the sky and rest of it is missing

As seen here: https://youtu.be/TuL-5LEUraI?t=110

**Comment by Oganku** [comment]
It used to work fine, but the visual beam is just missing. You can see small sparkles on the pillar, but the main event is missing.

**Comment by Rushor** [comment]
this needs weather override

**Comment by Rushor** [comment]
see https://github.com/WoWManiaUK/Redemption/issues/5244#issuecomment-761859642 

as is for now - too complicated to port for now
