### ISSUE TITLE
Druid fly form + Costumes 

### ISSUE THREAD

**Issue by svijetlo** [WoWManiaUK/Redemption#4989]
**What is Happening:**
If druid player put on costumes lime murlock or pirate then change to fly form it will not change  shape to bird but keep form of costume and look like it fly / swim in air , as seen in screen shoot 
![WoWScrnShot_091920_202330](https://user-images.githubusercontent.com/61908373/93726409-2add7e80-fbb6-11ea-8024-6bf1368834f7.jpg)
![WoWScrnShot_092020_202600](https://user-images.githubusercontent.com/61908373/93726413-2d3fd880-fbb6-11ea-9a8f-e1af54f75466.jpg)

**What Should happen:**
Druid Fly form should overwrite costume and change druid to respected bird form 
P.S. can not find proof of this form back in day , but this started recently as before it used to work normally

**Comment by Keader** [comment]
fixed.
flight form should always remove any transformation

**Comment by bLeyaa** [comment]
This should be fixed with #4981 already 👍

**Comment by Keader** [comment]
Not same issue
