### ISSUE TITLE
[Spell] Improved Devouring Plague - unable to crit

### ISSUE THREAD

**Issue by bLeyaa** [WoWManiaUK/Redemption#4991]
**Links:**  [Devouring Plague (spell)](https://www.wow-mania.com/armory/?spell=48300) / [Improved Devouring Plague (talent)](https://www.wow-mania.com/armory/?spell=63627)

**What is Happening:** The ability is not capable of critting with damage that comes on initial cast.

![image](https://user-images.githubusercontent.com/61625377/93833456-f1217c00-fc78-11ea-869e-44938874dc7b.png)

**What Should happen:** Ability should be able to crit on initial cast, just like it is on the dot.

As seen across entire video: https://www.youtube.com/watch?v=1xLK2Z1kqAQ (best visible at 06:05 and then a few secs later as he spams it while moving)

**Comment by wow-mania** [comment]
We will not be doing any more work on ICC unless it is critical.

**Comment by Keader** [comment]
It's not icc , is Priest spell

**Comment by jeyrella** [comment]
Yes, Imp Devouring plague should crit with initial cast.  See MMO-champ era-relevant thread on details around use of Inner Focus to improve the crit chance.

PTR is down right now so cannot fully check, but yes it should crit.

**Comment by jeyrella** [comment]
Confirmed.  Imp DP is not crittting.
![image](https://user-images.githubusercontent.com/46089380/93924116-36db5480-fd0c-11ea-993d-9e941fff9a21.png)

**Comment by Keader** [comment]
fixed

**Comment by jeyrella** [comment]
Fixed confirmed 
![image](https://user-images.githubusercontent.com/46089380/94358820-879bd600-009b-11eb-94e0-32bef2225847.png)
