### ISSUE TITLE
[Quest] Catch the Wild Wolpertinger!

### ISSUE THREAD

**Issue by bLeyaa** [WoWManiaUK/Redemption#4993]
**Links:** http://www.wow-mania.com/armory?quest=11117

**What is Happening:** Using Wolpertinger Net awards 2 counts towards the quest progress instead of one.

**What Should happen:** Each Wolpertinger that gets trapped should be accounted for only one in quest progress.
https://www.youtube.com/watch?v=wSUF-JfZTxM

**Comment by Rushor** [comment]
should be fixed now

**Comment by jeyrella** [comment]
Fixed fine
https://youtu.be/bNdSCTQ_DXg
