### ISSUE TITLE
[Spell] Guarded by the Light + Judgement

### ISSUE THREAD

**Issue by cathyr1** [WoWManiaUK/Redemption#4994]
This talent https://www.wow-mania.com/armory/?spell=53585 is not working properly.

When the Divine Plea is up, it should be refreshed by melee hits, Judgements, Hammer of the Righteous and Shield of Righteousness. It had been working like this until last patch. But now, after that patch, it can no longer been triggered by Judgement spells, rest are fine.

**Comment by svijetlo** [comment]
![image](https://user-images.githubusercontent.com/61908373/93904831-8ca70100-fcfa-11ea-88e2-c3581c6754c1.png)
ONLY melee hits should refresh that white melee hit with weapon not spells i tested it like 2 weeks ago to explain guild mate how it works and that it is proper
