### ISSUE TITLE
[Spell] Lay on Hands not affected by modifiers

### ISSUE THREAD

**Issue by bLeyaa** [WoWManiaUK/Redemption#4995]
**Links:** http://www.wow-mania.com/armory?spell=48788

**What is Happening:** Lay on Hands does not benefit from healing modifiers.

**What Should happen:** Lay on Hands should benefit from healing modifiers like talents (e.g quick recovery, nurturing instincts, other tank talents), buffs (e.g valithria stacks, divine hymn, amplify magic, guardian spirit), spells (e.g avenging wrath), set bonuses (e.g hpala 2set t10) etc.

https://www.youtube.com/watch?v=Fost7trWHw0 - If you pause it at 06:19 you will see a 226515 non crit heal of Lay on Hands ability.
At the beginning of Cataclysm you'll find [this topic](https://www.mmo-champion.com/threads/904193-Can-Lay-on-Hands-Crit) talk about it as well in the comments while discussing the inability of LoH to crit since that expansion.

**Comment by svijetlo** [comment]
![image](https://user-images.githubusercontent.com/61908373/94018951-7d36bf00-fdb1-11ea-96b5-5c53f659c615.png)

**Comment by Keader** [comment]
This note is wrong svijetlo
in wotlk it not depends of target health, it's based in spell power + caster spell mods

**Comment by svijetlo** [comment]
ye been just checking it is depended on caster-paladin HP + mods + sp

**Comment by Keader** [comment]
fixed
