### ISSUE TITLE
[Event Dungeon] Coren Direbrew - Drill mechanic

### ISSUE THREAD

**Issue by bLeyaa** [WoWManiaUK/Redemption#4996]
**Links:** N/A

**What is Happening:** The drill mechanic spawns under each player inside the dungeon and rams them up in the air.

**What Should happen:** The drill mechanic should only be affecting one player at the time.

Video from wotlk expansion: https://youtu.be/95NkWfS3M0k?t=122 - you'll see him do the same event dungeon two times in a row and on both is the same.

**_P.S. Coren is currently stunnable, I'd assume this is wrong as dungeon bosses are all immune to stuns. I couldn't really find evidence for this so i'll leave it up to you how you want to handle it._**

**Comment by Rushor** [comment]
should now only select one player

**Comment by Rushor** [comment]
also added Coren Direbrew basic immunities for boss (like Patchwerk)
