### ISSUE TITLE
Life Tap ft Unchained Magic (caused by Qaston Proc change)

### ISSUE THREAD

**Issue by bLeyaa** [WoWManiaUK/Redemption#4997]
**Links:** https://www.wow-mania.com/armory/?spell=57946

**What is Happening:** Life Tap procs 2 stacks of Unchained Magic. I would assume this is due to damage done by it as well as mana gained. I believe its related to #4846 

**What Should happen:** Life Tap should only proc one stack when used.

**Comment by Keader** [comment]
oh... shit
will fix tomorrow

**Comment by svijetlo** [comment]
most likely it counts mana gain as one more cast

**Comment by Keader** [comment]
test now

**Comment by svijetlo** [comment]
you get only one stack of instability with unchain magic if you use life tap
