### ISSUE TITLE
Paladin auras persist through death

### ISSUE THREAD

**Issue by bLeyaa** [WoWManiaUK/Redemption#4998]
**Links:** N/A

**What is Happening:** If paladin dies while in party/raid, the group will still benefit from the aura the player was on as it remains as a buff even though the player is dead.

**What Should happen:** Paladins should lose the aura buff upon dying, same as they lose all the other buffs.

https://youtu.be/EwLOcI4h_kg?t=453 You will see warlock on focus loses Concentration Aura upon his teammate's death.

**Comment by Keader** [comment]
fixed
