### ISSUE TITLE
[Spell] Unbound Plague damage too low - Professor Putricide

### ISSUE THREAD

**Issue by bLeyaa** [WoWManiaUK/Redemption#5000]
**Links:** https://www.wow-mania.com/armory/?spell=70911

**What is Happening:** Unbound Plague deals less damage than intended, while at the same time the damage increase is wrong and the damage multipliers from Plague Sickness are incorrect.

**What Should happen:** Base damage for the plague should be 250 on 10hc and 1000 on 25hc opposed to 200/800 as it is right now. The damage per second should increase by 25% on each tick in both difficulties. At the same time the debuff giving 250% damage to the plague needs to be multiplied correctly for each stack, which currently isnt.

Basically with no stack damage before any damage reduction talents and similar should be 
1000 / 1250 / 1562 / 1953 etc...

With one stack damage before any damage reduction talents and similar should be 
3500 / 4375 / 5467 / 6835 etc...

With two stacks damage before any damage reduction talents and similar should be 
6000 / 7500 / 9372 / 11718 etc...

http://worldoflogs.com/reports/rt-ft81j462bucjhiun/xe/?s=7368&e=7515&x=type+%3D+TYPE_DAMAGE%0D%0AAND+spell+%3D+%22Unbound+Plague%22

http://worldoflogs.com/reports/x97rsv7nxmqshrrn/xe/?s=86&e=214&x=type+%3D+TYPE_DAMAGE%0D%0AAND+spell+%3D+%22Unbound+Plague%22

http://www.worldoflogs.com/reports/sn12yn5vs33xtlcq/xe/?s=3493&e=4018&x=type+%3D+TYPE_DAMAGE%0D%0AAND+spell+%3D+%22Unbound+Plague%22

https://www.youtube.com/watch?v=jv93ko3WeK8&feature=youtu.be&t=506 (rogue gets the debuff with 1 stack = 3500 damage first tick)

At the same time, Unbound Plague can be removed by Divine Intervention at the moment which is incorrect.
![image](https://user-images.githubusercontent.com/61625377/94346508-5b497080-002d-11eb-8e04-aec115b2bf18.png)

It should immune the damage, but not remove the debuff.

**Comment by Keader** [comment]
fixed
