### ISSUE TITLE
[Spell] Chilled to the Bone - missing ICD

### ISSUE THREAD

**Issue by bLeyaa** [WoWManiaUK/Redemption#5001]
**Links:** https://www.wow-mania.com/armory/?spell=70106

**What is Happening:** There is no ICD on the boss ability, causing stacks to build up a lot faster than intended.

**What Should happen:** The ability should have a ~2 second ICD before another stack can be applied.

Rogue videos taken as example for the class which hits faster than most of the melee classes: 

https://www.youtube.com/watch?v=LVcWZ5hfhis
https://www.youtube.com/watch?v=PS07j7EjvO8

http://worldoflogs.com/reports/udqni9w8roj989w7/xe/?s=9901&e=10228&x=spell+%3D+%22Chilled+to+the+Bone%22+and+targetName+%3D+%22Xerofour%22

**Comment by Keader** [comment]
fixed
