### ISSUE TITLE
Buffs disappearing after portals - Halion / Valithria

### ISSUE THREAD

**Issue by bLeyaa** [WoWManiaUK/Redemption#5002]
**Links:** N/A

**What is Happening:** Certain buffs will disappear upon entering portals in Ruby Sanctum on Halion and ICC with Valithria Dreamwalker, such as Focus Magic, Beacon of Light, paladin "Hand of" spells

**What Should happen:** Buffs should remain on the player regardless of portals being used or not.

https://youtu.be/_6Hxpt9FLBU?t=70 You will see mage keeps both buff and proc of Focus Magic (02:34 again when going out of shadow realm)

https://youtu.be/_kSMSSXR22Q?t=218 Paladin enters portal with beacon on boss, comes out at 04:01 and beacon is still on boss

**Comment by Keader** [comment]
https://youtu.be/50YDqIBXQ9o?t=112

https://youtu.be/zJFdyAgoq1U?t=137

https://youtu.be/lk9f3GncuFU?t=88

yeah, i can confirm it too.
fixed

**Comment by jeyrella** [comment]
Focus Magic is fixed
still present on going to shadow
![image](https://user-images.githubusercontent.com/46089380/94464387-519f4480-01b6-11eb-89c0-9d7803e9c990.png)
back out to fire, same buff still correctly present
![image](https://user-images.githubusercontent.com/46089380/94464533-7eebf280-01b6-11eb-958c-3525ae60ad03.png)
