### ISSUE TITLE
[Battleground] Add several deserteur debuffs to specific situations

### ISSUE THREAD

**Issue by Rushor** [WoWManiaUK/Redemption#5003]
BG_DESERTION_TYPE_LEAVE_BG        = 0, // player leaves the BG
    BG_DESERTION_TYPE_LEAVE_QUEUE     = 2, // player is invited to join and refuses to do it
    BG_DESERTION_TYPE_NO_ENTER_BUTTON = 3, // player is invited to join and do nothing (time expires)
    BG_DESERTION_TYPE_INVITE_LOGOUT   = 4, // player is invited to join and logs out

In each case the player will now get a 30 min deserteuer  which prevents player from joining another battleground.

**Comment by Rushor** [comment]
you can test with : 
.debug bg

then you get an instant invite

**Comment by svijetlo** [comment]
@Rushor  it works but debuff is only 5 min not 30 mins
