### ISSUE TITLE
[Battleground] Disable queueing for more than one specific battleground at the same time

### ISSUE THREAD

**Issue by Rushor** [WoWManiaUK/Redemption#5004]
We need to add a sytem that the player can only queue for one battleground at the same time

That way players can no longer switch between battlegrounds if they already entered one.

How to test:

click "join battle" for one battleground Queue (WS .f.ex)
click "join battle" for other battleground Queue (Arathi. f.ex)
you shoud get a warning

**Comment by svijetlo** [comment]
![image](https://user-images.githubusercontent.com/61908373/94443760-d6359700-01a5-11eb-8c71-2efef51de782.png)
work nice =)
