### ISSUE TITLE
[BG + LFG] Add a system that enables battleground and LFG Queue at the same time

### ISSUE THREAD

**Issue by Rushor** [WoWManiaUK/Redemption#5005]
Adding a system that allows queueing for LFG and Battleground queue at the same time.

Entering one of those will remove you from the queue of the other.

Example:
Join lfg queue
Join BG queue

- bg pops and you join bg
- you get removed from the lfg queue

This also works vise versa

**Comment by svijetlo** [comment]
works like charm
