### ISSUE TITLE
[Battleground] Leaving a BG manually should also give a 30 min Deserter debuff

### ISSUE THREAD

**Issue by Rushor** [WoWManiaUK/Redemption#5006]
Leaving a BG manually should also give a 30 min Deserter debuff

Currently it is only 15 minutes.

**Comment by svijetlo** [comment]
same here by leaving it manually i only got 5 min debuff

**Comment by svijetlo** [comment]
![image](https://user-images.githubusercontent.com/61908373/94444597-c79baf80-01a6-11eb-923a-8ca066f327e3.png)
