### ISSUE TITLE
[NPC] Cursed Marine's text script incorrect

### ISSUE THREAD

**Issue by jeyrella** [WoWManiaUK/Redemption#5007]
**Links:**
NPC ID 1158
https://wow-mania.com/armory/?npc=1158

**What is Happening:**
NPC ID 1158  Cursed Marine says: A living **$r**... soon to be a dead like me.

**What Should happen:**
NPC ID 1158  [15:02:44] Cursed Marine says: A living (player's race)... soon to be a dead like me.

**Comment by jeyrella** [comment]
Actually, there is a 2nd slight typo as well - the "a" in the "soon to be a dead like me should be removed.

https://classic.wowhead.com/npc=1158/cursed-marine#comments
![image](https://user-images.githubusercontent.com/46089380/94916709-1a2ae380-04a7-11eb-84b5-54458f3f8cd9.png)

What Should happen:
NPC ID 1158 [15:02:44] Cursed Marine says: A living (player's race)... soon to be dead like me.

**Comment by Rushor** [comment]
text is correct and confirmed by broadcasttext aswell https://classic.wowhead.com/npc=1158/cursed-marine#comments https://i.imgur.com/G49IH2H.png :o

**Comment by Rushor** [comment]
$r error fixed

**Comment by Oganku** [comment]
The "a" is still there, but the race issue is fixed. Up to @Rushor's discretion whether it remains or not.

**Comment by Rushor** [comment]
i would say text stays as is since i got the files/texts directly from wow source folder
