### ISSUE TITLE
[NPC] Felspine the Greater 21987 location is incorrect

### ISSUE THREAD

**Issue by jeyrella** [WoWManiaUK/Redemption#5008]
**Links:**
Felspine the Greater NPC 21987

**What is Happening:**
Felspine the Greater 21987 is in the wrong location (in middle of lava flow, should be on the rocky outcrop

**What Should happen:**
Should be on the rocky outcrop, coords 56,44.  This was changed for TBC patch 2.3.3.  **It is actually important for quest 10678 when at level, as the lava kills level 65 players rather quickly.**

![image](https://user-images.githubusercontent.com/46089380/94677765-5d554d00-0315-11eb-9fa2-2672bbbd39d6.png)
https://www.wowhead.com/quest=10673/felspine-the-greater#comments:id=235631
![image](https://user-images.githubusercontent.com/46089380/94677818-7231e080-0315-11eb-8921-f9ab206c53d8.png)

**Comment by Rushor** [comment]
position adjusted :)
