### ISSUE TITLE
[NPC/Quest] A Necessary Distraction / Azaloth :  is already untrapped and aggressive to the player on approach

### ISSUE THREAD

**Issue by jeyrella** [WoWManiaUK/Redemption#5009]
**Links:**
Quest:  10688/10637 A Necessary Distraction 
https://wow-mania.com/armory/?quest=10637
https://wow-mania.com/armory/?quest=10688

NPC:  Azaloth https://wow-mania.com/armory/?npc=21506

Item:  Scroll of Demonic Unbanishing   https://wow-mania.com/armory/?item=30811

**What is Happening:**
Azaloth is already free and aggressive, which is problematic at level as he is elite, and at 80 easy to kill accidentally, both failing quest. 
He should not become unchained until you use item on him

**What Should happen:**
Azaloth should be trapped and non-aggressive.  Kill Warlocks in the area, not neccessarily the ones fighting Azaloth, until you get a http://www.wowhead.com/?item=30811 (Scroll of Demonic Unbanishing). Use on Azaloth.  At that point, he should turn against the warlocks fighting him, BEFORE the player.

https://www.wowhead.com/quest=10637/a-necessary-distraction#comments:id=24515

Era-relevant videos are hard to find, but this cata-era version shows how it should work:  https://youtu.be/_NPAIXkTFpY?t=4

**Comment by Rushor** [comment]
thanks for the reports man

**Comment by Rushor** [comment]
banish mechanic is added now, if he is banished he is not agressive
