### ISSUE TITLE
[Tooltip] Siegebreaker Plate tier bonus type (Warrior tier 8 (4) bonus)

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#5010]
**Links:** https://www.wow-mania.com/armory/?itemset=-163
https://www.wow-mania.com/armory/?itemset=831

**What is Happening:** In game, the (4) bonus for warrior tier 10 is written as follows:
Shield Block also grants you $s1% reduction to magical damage taken.

Proof
![image](https://user-images.githubusercontent.com/34783736/94733361-a1f0e080-0335-11eb-8fe3-81ef3de8a7c4.png)

**What Should happen:** The tooltip should say: Shield Block also grants you **20%** reduction to magical damage taken.

**Note:** The effect itself works perfect, but the tooltip is weird.

**Comment by Keader** [comment]
dbc issue, only janitor can fix it...
and i dont think that he want fix it... is 100% visual thing
@wow-mania
