### ISSUE TITLE
[NPC/Quest] Harvest Festival - Honoring a Hero - Alliance - Worgen

### ISSUE THREAD

**Issue by drpsyche** [WoWManiaUK/Redemption#5012]
This issue affects only Worgen characters
The quest to go to Uther's Statue in Western Plaguelands and place the tribute can be obtained.
Going to the Tomb, and using the tribute item is successfully consumed, but the quest is not advanced.

The quest still requests the tribute to be placed, despite the tribute item being consumed and is no longer available.

Quest should advance and request completion turn in back to the quest giver in Ironforge.

Have experienced issue on 2 lvl 80 Worgan characters (Druid and Warlock), and successfully completed on level 80 Gnome and Drenai characters

**Comment by Rushor** [comment]
for me it is bugged on other races aswell

**Comment by Rushor** [comment]
got it - it is just a condition issue, prolly affects goblin too. so adjusting spell 24105 for f.ex human and worgen will fix it 

same for 24104 for horde orc and goblin then

**Comment by svijetlo** [comment]
yes some things on wargen ergo goblin do not work perfect i remember 3y ago argent ground quests did not work if you were wargen , so what ever efect wolf ppl could potentially effect goblin on horde

**Comment by Rushor** [comment]
okay should work for goblin and worgen now

**Comment by jeyrella** [comment]
fixed https://youtu.be/uII0wjLqKy8
