### ISSUE TITLE
[Quest] I've Got a Flying Machine!

### ISSUE THREAD

**Issue by cathyr1** [WoWManiaUK/Redemption#5013]
This quest https://www.wow-mania.com/armory/?quest=11390 seems bugged. Its possible to grab the sack by the Grappling Hook but then the item cannot be delivered on any of the platforms.

**Comment by svijetlo** [comment]
i did it 4 days ago platform where you need to deliver the bags is one hanging form cranes not ones plane was on

**Comment by svijetlo** [comment]
https://www.youtube.com/watch?v=qjMMvnVo1XE&ab_channel=GitGudGuides

**Comment by cathyr1** [comment]
Thanks, works now. Saw different video before https://www.youtube.com/watch?v=P74jNj9vI8s.
