### ISSUE TITLE
[NPC] Blistering Zombie + Shackle Undead

### ISSUE THREAD

**Issue by svijetlo** [WoWManiaUK/Redemption#5014]
**Links:**
http://www.wow-mania.com/armory?npc=37934
https://www.wowhead.com/npc=37934/blistering-zombie
http://www.wow-mania.com/armory?spell=70744
http://www.wow-mania.com/armory?spell=10955
**What is Happening:**
If during valithria dreamwalker encounter priest cast Shackle undead on Blistering zombie before mob die and mob get killed while shackle undead is on it it will not do acid burst aoe dmg 
**What Should happen:**
Blistering Zombie Should always explode on death dealing dmg and dot on everyone in range of 15 yards 

NOTE: it is icc fight pots but GM approved for it to be made

**Comment by Rushor** [comment]
should we make them immune to Shackle undead ?

**Comment by svijetlo** [comment]
no no 
make it explode with https://www.wow-mania.com/armory/?spell=70744 even if Shackle undead is on him

**Comment by Rushor** [comment]
https://www.wow-mania.com/armory/?spell=70744 will now be casted instantly if Shackle undead is applied on them upon death, thus they should 100 % cast it
