### ISSUE TITLE
[NPC] Rigglefuzz text error after completing quest Pearl Diving

### ISSUE THREAD

**Issue by jeyrella** [WoWManiaUK/Redemption#5015]
**Links:**
NPC:  Rigglefuzz:  https://wow-mania.com/armory/?npc=2817
NPC:  Wayward Buzzard:  https://wow-mania.com/armory/?npc=6013
Quest:  https://wow-mania.com/armory/?quest=705

**What is Happening:**
After completing quest "[Pearl Diving](https://wow-mania.com/armory/?quest=705)", there is a short event where Rigglefuzz is attacked by [Wayward Buzzard](https://wow-mania.com/armory/?npc=6013)
His first text is:  Rigglefuzz says: Look out!  We're under attack by a **$n!**
![image](https://user-images.githubusercontent.com/46089380/95014008-f3ea7c80-063b-11eb-96d2-1054359ff958.png)

**What Should happen:**
I believe the text should say 
Rigglefuzz says: Look out!  We're under attack by a Wayward Buzzard!
Although finding videos or other definitive evidence is particularly difficult

**Comment by Rushor** [comment]
texttarget should be ok now

**Comment by jeyrella** [comment]
Hmm.  Seems the line is missing altogether now, he goes straight to "Take that, beast"
![image](https://user-images.githubusercontent.com/46089380/95108933-d00a6200-0733-11eb-8ee7-1a46ac40f71e.png)

**Comment by Rushor** [comment]
okay changed the text directly now - this requires a delete of cache folder

**Comment by Rushor** [comment]
should work now https://i.imgur.com/ghERJMN.jpg

**Comment by jeyrella** [comment]
![image](https://user-images.githubusercontent.com/46089380/95183082-5f0f8c80-07bd-11eb-8869-395561f85764.png)
