### ISSUE TITLE
[quest] Kaw the mammoth destroyer

### ISSUE THREAD

**Issue by Sierbahnn** [WoWManiaUK/Redemption#5016]
**Links:**
https://www.wowhead.com/quest=11879/kaw-the-mammoth-destroyer

**What is Happening:**
The mount is there, and respawns normally, but the mounted rider does not appear.

**What Should happen:**
The mount and the rider should spawn at the same time, so I can complete the quest.

**Comment by Rushor** [comment]
linked respawn added. so if the mount (Moria) respawns, the rider (Kaw the Mammoth Destroyer) will respawn aswell now 

https://gyazo.com/cf34888260d08a1d57bc25788a7f8236

**Comment by svijetlo** [comment]
nice this used to be issue for some time as they were not respawn together but i could not find data on how they respawn so i guess it is better for it to be same
