### ISSUE TITLE
[Spell/Warrior] Retaliation vs Judgements

### ISSUE THREAD

**Issue by Keader** [WoWManiaUK/Redemption#5020]
**What is Happening:**

https://www.youtube.com/watch?v=CoEQrIfRLeE

Judgement is proccing retaliation, what make warriors get some vantage vs paladins in pvp.
It's proccing with more triggered spells too and should not.

**What Should happen:**

Judgements should not proc Retaliation.
Should not proc with triggered spells casted by players (but should proc with triggered spells casted by creatures).

**Comment by Oganku** [comment]
Seems to work fine. Judgement is counted as a melee attack, so it will get counter-attacked if the player is in attack range, if not, then nothing happens.
