### ISSUE TITLE
Upper Blackrock Spire - Hall of Binding/Pyroguard Emberseer

### ISSUE THREAD

**Issue by gh0ster** [WoWManiaUK/Redemption#5023]
https://classic.wowhead.com/guides/upper-blackrock-spire-classic-dungeon-strategy
"This hallway will lead to the Hall of Binding. Kill each Blackhand Incarcerator around the room, which unlocks Pyroguard Emberseer. After killing the Pyroguard, the door to the Rookery will open."

**What is Happening:**
Pyroguard Emberseer not activating when Blackhand Incarcerators are killed and  altar used for summoning. This leaves you in room with inactive Boss and both doors locked. Each time (3 times in past +- month) we have had to log ingame ticket for GM to unlock door to rookery for us to proceed.

**What Should happen:**
This room is straightforward. Click the Altar to aggro all of the Incarcerators to release the bind on Pyroguard Emberseer. Once released, kill Pyroguard to advance into The Rookery.

Only logging Github as this has happened multiple times with different members in my guild so it seems more like game logic failing rather than anything a single player is getting wrong.

**Comment by Rushor** [comment]
We must change the Script - in wotlk only one Person for activating is needed

**Comment by Rushor** [comment]
some more stuff that must be fixed here:

1. Doors should only close once all Incarcerators are dead
2. Since WotlK only one person is needed to click the altar to start the fight

**Comment by Rushor** [comment]
clicking and holding the channel spell now starts the fight https://i.imgur.com/y4zh29w.png https://i.imgur.com/SWNlE7O.png
