### ISSUE TITLE
[Mount] Traveler's Tundra Mammoth vendors stay spawned after dismounting

### ISSUE THREAD

**Issue by GMMetaxa** [WoWManiaUK/Redemption#5024]
**Links:**
https://www.wowhead.com/item=44234/reins-of-the-travelers-tundra-mammoth

**What is Happening:**
After mounting it creates 2 vendors next to the mount. Those vendors don't disappear after dismounting.

**What Should happen:**
The vendors should be on the mount when mounting.

**Comment by GMMetaxa** [comment]
![image](https://user-images.githubusercontent.com/34750502/95301005-44521c00-0880-11eb-8b67-066523df0e12.png)

**Comment by svijetlo** [comment]
as i see this only happens on horde , on ally you mount 2 seller npc are sitting on seat if you dismount them they are gone after 5 sec , if you dismount bouth of them are gone after 5 sec

**Comment by Rushor** [comment]
will despawn instantly now

**Comment by jeyrella** [comment]
Fixed.  https://youtu.be/6n5WWzAUvKc
