### ISSUE TITLE
[Battleground] Strand of the Ancients root and timer

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#5026]
**Links:** https://github.com/WoWManiaUK/Redemption/issues/4849

**What is Happening:** 

1. The "root" added to fix issue 4849 is permanent and persists even after the battle starts. Also you can attack rooted players as defender if they join before battle start.

2. The start timer is way off, so people start fighting before the battleground officially starts, and if someone dies in that part, they "die" but can still move as an unattackable player with full health.

**What Should happen:** 

Probably just remove the root, even if it's kinda weird, but since we cant place new players on the boat, it's better to at least let them fight or prevent players from joining during the preparation phase.

**Comment by Rushor** [comment]
removed the root again. if you have other suggestions to fix this problem let me know
