### ISSUE TITLE
[Mount] Cindermane Charger - multiple seats bug

### ISSUE THREAD

**Issue by bLeyaa** [WoWManiaUK/Redemption#5028]
**Links:** http://www.wow-mania.com/armory?item=118515

**What is Happening:** If you get onto a mount that can have 1 or two passengers and then mount Cindermane Charger, the passenger seats will carry over to the mount causing it to be able to carry 1 or two passengers in addition to the original player mounting it.

To test it, use one of these mounts and see the magic: [chopper](https://www.wow-mania.com/armory/?item=44413), [rocket](https://www.wow-mania.com/armory/?item=54860), [mammoth](https://www.wow-mania.com/armory/?item=44235) ([also mammoth](https://www.wow-mania.com/armory/?item=44234))

**What Should happen:** Cindermane Charger is a one person mount, aka the player having it only.

**Comment by jeyrella** [comment]
Confirmed
![image](https://user-images.githubusercontent.com/46089380/95394440-6dac8f80-08f4-11eb-97d1-1af4e317c54a.png)
![image](https://user-images.githubusercontent.com/46089380/95394502-92086c00-08f4-11eb-836c-f4b4b28b1b7f.png)

**Comment by svijetlo** [comment]
same used to happen year or so ago with Invincible Lk mount it was fixed we should chek all who share this model it could be reverted as celestial steed share same model and could also do this

**Comment by bLeyaa** [comment]
I checked a lot of mounts, including celestial, couldn't find any other that had the same issue.

**Comment by svijetlo** [comment]
yes it is only on this one atm

**Comment by Keader** [comment]
Fixed
