### ISSUE TITLE
[Weekly] Push the Envelope

### ISSUE THREAD

**Issue by Rushor** [WoWManiaUK/Redemption#5031]
Daily Quest: "Push the Envelope".  Play 2 Random Battlegrounds and 2 Heroic Dungeons at level 80"  Reward: 5 PvP Tokens and 5 EoF

questgiver and questender
new creature
new quest
coresystem after random lfg is done > add credit
 5 PvP Tokens = WoW Mania's PvP Token

if you want tester or other devs can add goss fitting questtexts here :)

we make it daily for now and later weekly

**Comment by jeyrella** [comment]
See discord;  this should definitely be set as a **weekly** quest

**Comment by Rushor** [comment]
https://i.imgur.com/XYgZNMh.png 

okay weekly state added :)

core change applied, only sql missing

**Comment by Rushor** [comment]
all added now

**Comment by Rushor** [comment]
https://i.imgur.com/hhWDomL.jpg https://i.imgur.com/2een8KD.jpg
