### ISSUE TITLE
Can't learn of find an ability-Syphon Life Warlock.

### ISSUE THREAD

**Issue by Drugu** [WoWManiaUK/Redemption#5032]
**Links:**

**What is Happening:** I got level 40 and respec'd than i put talent points in aflliction but couldn't find syphon life anywhere.I bought dual spec and still didn't fix it. I want to mention i have the latest version of the launcher,Please fix this.

**What Should happen:**Find the goddamn ability

**Comment by svijetlo** [comment]
Patch 3.1.0 (2009-04-14): The Siphon Life spell has been removed. Siphon Life now causes your Corruption spell to instantly heal you for 40% of the damage done.
![image](https://user-images.githubusercontent.com/61908373/95613675-999b5280-0a65-11eb-9db5-55109413ea57.png)

**Comment by svijetlo** [comment]
in WOW WOTLk siphon life is passive ability not spell of its own 
Drain life is spell
