### ISSUE TITLE
[Spell] Cloak of Shadows completely removes Necrotic Plague

### ISSUE THREAD

**Issue by bLeyaa** [WoWManiaUK/Redemption#5033]
**Links:** https://www.wow-mania.com/armory/?spell=31224

**What is Happening:** When Cloak of Shadows is used on abilities such as Necrotic Plague, it completely removes it from the player.

**What Should happen:** Spell such as Necrotic Plague should jump as if it was dispelled from the player, rather than being completely lost.

Posting this under as CoS bug report per instructions from Keader as he said its related to spell and not boss ability.

**Comment by svijetlo** [comment]
this used to happen 2y or so ago and it was fixed when did it start to happen again ?

**Comment by Keader** [comment]
test now pls
