### ISSUE TITLE
Strength of Wrynn applied to certain mob/boss abilities

### ISSUE THREAD

**Issue by bLeyaa** [WoWManiaUK/Redemption#5034]
**Links:** https://wow-mania.com/armory/?spell=73828

**What is Happening:** Currently the player buff will increase the damage done by Unchained Magic (Instability stacks) as well as Unbound Plague on Professor Putricide. It was also increasing the damage of Corrupted Blood from Crimson Hall trash mobs but i see this was already addressed.

At the moment Unbound Plague is being fully increased by 30%, including the damage modifiers from Plague Sickness meaning that each tick will be doing 30% more damage to the player with or without the sickness debuff.

As for the Instability stacks, this one works a bit different at the moment and i would assume its because the debuff is stackable. What happens is that the very first stack that you get has the 30% damage increase applied, but every other stack is correct. This means that exploding with one stack will do 2783 damage to the player, but exploding with 10 stacks will do 20783 damage.

**What Should happen:** Boss abilities should not be affected by this buff.

I would assume the same happens with the horde version of this buff.

**Comment by Keader** [comment]
i will take a look tomorrow morning.

**Comment by Keader** [comment]
test now pls

**Comment by Oganku** [comment]
Also fixed for Hellscream's Warsong (horde version)
