### ISSUE TITLE
[Raid] Lich King encounter - run speed to centre on transitions incorrect

### ISSUE THREAD

**Issue by bLeyaa** [WoWManiaUK/Redemption#5036]
**Links:** N/A

**What is Happening:**

- [x] 1. When the boss is at 40% health at random times he will not run back to the middle but walk instead. This gives players advantage of getting some extra dps on him, but at the same time if there are valkyrs that just spawned and picked up players - they will not drop them until LK is back at middle and at the same time also the edge will not be spawned until he's there so these players will usually end up being dropped down because of it. See https://youtu.be/SZ4zEfIvl10

- [x] 2. Val'kyrs in the air are currently not tauntable. The taunt ability will not be immuned, but it will have no effect on the val'kyrs at all. Tanks should be able to taunt them and get them off the players. Proof: https://youtu.be/h1x9MErf5NA?t=165

- [ ] 3. When players are grabbed by val'kyrs they are unable to cast spells, which is correct, but for some reason paladins are able to swap auras while grabbed. Not sure this is correct, but it doesnt sound right.

- [ ] 4. When val'kyrs are picking up players, they will remember the location of the player where they were when they spawned and pick them up from there, instead of the actual location where the player was at the time of pick up. You can see here warlock on the left side moves after his val'kyr has spawned and is dragged from that location properly: https://youtu.be/_QcuB8zCpu4?t=530

**What Should happen:**

1. LK should have the same speed as in first transition when running back to the center of the platform.

2. Val'kyrs should be tauntable and direct their siphon to the player who taunted.

3. Not sure about this? Are the paladin auras considered different to the rest of the player abilities?

4. Val'kyrs should pick up the player at the location where he was when picked up.

**Comment by Keader** [comment]
issue 1 fixed

**Comment by svijetlo** [comment]
Janitor direct orders

**Comment by jeyrella** [comment]
Reopened on discussion with @wow-mania for issue #1 only.  thanks

**Comment by Keader** [comment]
Fixed valkyr taunt / soul sipphon stuff.
Now valkyr will always attack top threat player, not random members.
And now she will get a "black collor" when start cast soul siphhon xd

@jeyrella can you test it pls?
