### ISSUE TITLE
item bug from tier 10

### ISSUE THREAD

**Issue by pentagramab** [WoWManiaUK/Redemption#5037]
**Links:**

**What is Happening:**
i bought legs from tier 10 (hc one) that means bis for me.I am playing ret pally and i have 6334 gear score.Before buying my dps was better than rightnow.I am doing same dps with 5.9 gs paladin.There is no problem with my stats or gems or enchants.I tried a lot of things.I deleted my xmog and deleted the game.But nothing changed.I really need help about it.

**What Should happen:**
I need to do 8+ dps like 2 days ago,the item or something wrong with it.Need help immediately because i cant play my toon.

**Comment by jeyrella** [comment]
We'll need more specific details about what you think is wrong with the items.  We can't see any issue.
If you can give some proof of this, a video perhaps, we'll reopen.  Otherwise you may want to study your rotation to see what you're missing.
Thanks

**Comment by jeyrella** [comment]
You may also wish to check to make sure your items are fully repaired.   If they are red, then you will get no benefit from them, it will be like you are not wearing them and you will lose the set bonus.
