### ISSUE TITLE
Lich King Transmog Issue

### ISSUE THREAD

**Issue by findlogan** [WoWManiaUK/Redemption#5039]
**Links:**
https://wow-mania.com/armory/?item=90005

**What is Happening:**
The LK pants do not show up to transmog on the Vendor.

**What Should happen:**
When selecting pants to transmog, the LK pants should show up.

**Comment by svijetlo** [comment]
what vendor are you talking about pls

**Comment by sirjacob4pe** [comment]
okay so when you go to the transmog vendor the leg plates do not show up at all  I have changed legs to test it and it's just the lich king plate legs that do not show up in the vendors list to change the appearance

**Comment by svijetlo** [comment]
i em sorry i do not know how to reproduce your bog could be on your side  if you have not most recent update or smt like it as i can mog other items to look like Lk set pants and i can mog Lk set pants to look like other items 
![WoWScrnShot_101720_063824](https://user-images.githubusercontent.com/61908373/96328465-b0344180-1043-11eb-9ae8-5b4bcb3228ae.jpg)
![WoWScrnShot_101720_063836](https://user-images.githubusercontent.com/61908373/96328466-b5918c00-1043-11eb-8081-43007d8ebec2.jpg)

**Comment by sirjacob4pe** [comment]
idk svijetlo I guess I will have to re torrent the hole game now and see if it's still a issue

**Comment by svijetlo** [comment]
@sirjacob4pe  can you pls tell me what item you are trying to mog LK pants' to look like might be item related to try that out before you redownload game

**Comment by Keader** [comment]
ok, without a reproduce case, we cant fix.
Reopen it when have a reproduce case

**Comment by sirjacob4pe** [comment]
did a full redownload and it's not helping at all still shows the same thing

**Comment by findlogan** [comment]
![image](https://user-images.githubusercontent.com/58502025/96356796-743fc180-10c1-11eb-94e9-6ca1edba47e3.png)


it doesnt work..

**Comment by svijetlo** [comment]
after talking to player last night and getting some more data on items i must conclude that i can not reproduce this it is smt palyer specific or that LK panst specific as i could do it all wo problems as it is seen on next few ss
![WoWScrnShot_101820_112435](https://user-images.githubusercontent.com/61908373/96363437-b8b87500-1134-11eb-8baa-a93c186d043e.jpg)
![WoWScrnShot_101820_112347](https://user-images.githubusercontent.com/61908373/96363440-bce49280-1134-11eb-9db4-6f93cef83466.jpg)
![WoWScrnShot_101820_112409](https://user-images.githubusercontent.com/61908373/96363442-bfdf8300-1134-11eb-9aa4-30976426ee18.jpg)

i em rly and honesty sorry i could not do more do resolve your issue

**Comment by sirjacob4pe** [comment]
janitor said it was a issue and he will get on it

**Comment by Keader** [comment]
without reproduce case, we cant fix
