### ISSUE TITLE
item damage bug (tier 10hcmarked) <<<<

### ISSUE THREAD

**Issue by pentagramab** [WoWManiaUK/Redemption#5040]
**Links:**

**What is Happening:**
hello again i bought my bis item from t10 heroic one.I am playing ret paladin.My problem is about damage.Before buying my damage was more than rightnow.I tried too many times but there is no solve.I changed my pants and used my heal spec's panth insted of my new bis tier 10 hc pant but both of them have same damage i need help about it help me please.
Wotlk server wowmania 3.3.5 (private server) my nickname : Sogan

**What Should happen:**
i need to do dps 8k+ like 2 days ago

**Comment by Rushor** [comment]
Pls talk to a gamemaster. Without more Information about missing auras or incorrect working Talents we cannot fix anything for you.
