### ISSUE TITLE
[NPC] Val'Kyr Herald ID: 37098 Missing Spell on all difficulties.

### ISSUE THREAD

**Issue by Drostthehunter** [WoWManiaUK/Redemption#5042]
**Links:**
https://www.wowhead.com/npc=37098/valkyr-herald
https://www.wowhead.com/spell=71906/severed-essence
https://www.youtube.com/watch?v=AXkAFHXOlJs&ab_channel=zosalvo

**What is Happening:**
Currently Val'Kyr Herald (37098) does not cast an ability called Severed Essence.

**What Should happen:**
Val'Kyrs should be able to cast this spell on all difficulties of the raid, 10normal/heroic 25normal/heroic, Severed Essences are the souls ripped appart from the body of the raid members, they are attacking the raid and healing the Valkyr, they are Undead type which means they are stunnable via Holy Wrath. Ignoring the essences is not possible as long as they are alive Val'Kyr keeps on healing herself. Youtube link posted from 2010. is a proof that spell used to exist.

**Comment by jeyrella** [comment]
Has been reported before
https://github.com/WoWManiaUK/Redemption/issues/4449
https://github.com/WoWManiaUK/Redemption/issues/1330

Will check with @Keader if the landscape has changed for us to be able to fix this

**Comment by bLeyaa** [comment]
Currently the valkyrs are as good as dummies, if the changes in spell system now allow this to be added it will completely change the encounter against them. I know its a "fix in icc" but this would be really nice addition. :)

**Comment by Keader** [comment]
I Will only look It in the weekend
Until there, check If janitor approve It @jeyrella

**Comment by wow-mania** [comment]
This is starting to piss me off really.
Last one on this once this is closed I will be automatically close any issue around this.

**Comment by Keader** [comment]
try now pls

**Comment by Oganku** [comment]
Creates copies of all raid players in range with fixed hp and melee damage. Stars aggro'd with the original copy, but has 0 threat so can be aggro'd by anyone else.
The damage from the adds don't seem to scale. Damage is around 9k per hit on a naked toon. The melee damage is far greater than ability damage for all of them. Melee attacks comprise about 80% of their damage overall.

Uses the following for each class:

Druid: **Nothing**
Warrior: Mortal Strike and Heroic Strike
Death Knight: Necrotic Strike and Plague Strike
Shaman: Lightning Bolt
Warlock: Rain of Chaos/Corruption/Shadow Bolt
Paladin: Radiance Aura and Flash of Light
Rogue: Sinister Strike and Eviscerate
Hunter: **Melees and uses Mortal Strike and Heroic Strike...?**
Priest: Renew and Greater Heal
Mage: Fireball and **Frost Nova (doesn't root or damage)**

The summoning script and mob AI seems great though.

**Comment by bLeyaa** [comment]
Intended on the last part, they need to be killed separately. 
Sounds great so far, well done Keader!

**Comment by Keader** [comment]
yes, they should not vanish after vlakyr dies.
checking your complanings now.

**Comment by Keader** [comment]
"Hunter: Melees and uses Mortal Strike and Heroic Strike...?"

Fixed melee, but i cant reproduce this mortal strike/heroic strike bug.

Rest of issues, fixed.

**Comment by svijetlo** [comment]
![WoWScrnShot_102720_152928](https://user-images.githubusercontent.com/61908373/97315940-84963000-1869-11eb-8459-6ba9097ca8a4.jpg)
![WoWScrnShot_102720_152958](https://user-images.githubusercontent.com/61908373/97315952-8829b700-1869-11eb-843d-205b86f19aeb.jpg)
![WoWScrnShot_102720_153007](https://user-images.githubusercontent.com/61908373/97315964-8bbd3e00-1869-11eb-9b4a-a3a00817a40d.jpg)
![WoWScrnShot_102720_153028](https://user-images.githubusercontent.com/61908373/97315977-8f50c500-1869-11eb-846e-01eeed5df351.jpg)
![WoWScrnShot_102720_153103](https://user-images.githubusercontent.com/61908373/97315989-924bb580-1869-11eb-8272-bd19dff91018.jpg)
this is some good thisng nice job , ss are only form paly tested with rogue , boomy dk , priest hunter , as seen close need to be killed on its own wont be gone ones walk die
