### ISSUE TITLE
[Raid] Baltharus the Warborn - Repelling Wave wrong range

### ISSUE THREAD

**Issue by bLeyaa** [WoWManiaUK/Redemption#5045]
**Links:** http://www.wow-mania.com/armory?spell=74509

**What is Happening:** Currently the distance of the stun / damage / knock back seems to be set to 150 yards instead of 20.

**What Should happen:** The distance should be set to 20 yards for all 3 effects of the ability. Yes, mania armory and wowhead both show 150, but this is wrong. In the videos below you will see the evidence of it as well.

https://youtu.be/m2ScSlgH-yY?t=34

https://youtu.be/wXVwEf1tuVw?t=72

https://youtu.be/z2VZAhfPjpg?t=35 (also from PTR before it went live)

Additional proof:

cata/bfa values from dbc

![image](https://user-images.githubusercontent.com/61625377/96046781-50d40700-0e74-11eb-9106-b77019b29b89.png)

**Comment by jeyrella** [comment]
To be clear, the distance that the knockback sends the player (150 yards) is correct, it is the range for which this currently happens is incorrect.  It is intended to only affect melee.
i.e. 
**What is happening:**
Knocking back players within 150 yards of boss, by 150 yards
**What should be happening:**
Knocking back players within 20 yards of boss, by 150 yards

**Comment by bLeyaa** [comment]
I am not aware of whats the distance of the knockback, but i'm pretty sure its not 150 lol.... that's waaaay too much

The knockback distance at the moment seems perfectly fine, its just the area of the stun/damage that is currently larger than it should be.
To be fair, my original post has a typo as the knockback currently only affects melee but the stun and damage are the ones that go over the 20 yards.

For comparison, here's what approximately 150 yards would be in game...

![WoWScrnShot_101620_004933](https://user-images.githubusercontent.com/61625377/96199304-784fd000-0f57-11eb-86bc-10d3e35ef489.jpg)

**Comment by Keader** [comment]
all effects should affect targets in 20y only :)
