### ISSUE TITLE
[Dungeon] Stratholme gauntlets missing

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#5047]
**Links:** https://youtu.be/zP42DecUzHg (Living side gauntlet at 13:20)
https://youtu.be/YsFmsuBGQak (Undead gauntlet at 49:40)

**What is Happening:** The 2 gauntlets in Stratholme are currently missing.

**What Should happen:** When you step into the 2 specific gauntlet "rooms" the gates should be closed and the players should get attacked by small critters as seen in the videos above. Once all insects are killed, the gates reopen and the group can continue. 

*Note: Rushor had the bits of code for it before and I believe it was just forgotten since no issue had been opened officially.

**Comment by Rushor** [comment]
trap event added, if you run close to it the gate will close and the critters will spawn. after 30 seconds, the gate will open again 

https://gyazo.com/16411c04f2711a8672b547bfa70ffda7

**Comment by svijetlo** [comment]
![WoWScrnShot_101820_114015](https://user-images.githubusercontent.com/61908373/96363814-cd960800-1136-11eb-93b0-470abf8247e0.jpg)
