### ISSUE TITLE
[Boss/Dungeon] Ley-Guardian Eregos' Planar Anomalies (The Oculus)

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#5048]
**Links:** https://youtu.be/TZC-NyHZ8gU?t=125
https://youtu.be/4GigIXEA4KE?t=66
https://www.wow-mania.com/armory/?npc=30879

**What is Happening:** The [Planar Anomalies](https://www.wow-mania.com/armory/?npc=30879) are currently affected by gravity and pitifully fall to the ground rather quickly, rendering them fairly useless. 

**What Should happen:** 
> Planar Shift: At 60% and 20% hp, the boss will become transparent and immune to damage for 18 seconds. Planar Anomaly sparks will appear and follow each player. Fly far away from them! They will explode before the boss reappears. This also causes an aggro wipe. If there are whelps out during this phase, it is possible to target and kill them while you're flying away, assuming your group decides to fly clockwise or counterclockwise. This seems to be on Heroic Mode only.
Planar Anomaly: Casts Planar Blast if within range of a player, dealing 42,750 damage to all players within 20 yards.

At 60% and 20%, the boss phases correctly and 1 [Planar Anomaly](https://www.wow-mania.com/armory/?npc=30879) spawns for each player and chases their respective targets. Players have to fly away from them to avoid their deadly explosions.

**Comment by bLeyaa** [comment]
#4410

**Comment by Oganku** [comment]
The balls still behave the same and fall to the ground, being mostly harmless.

**Comment by Keader** [comment]
how it got fix confirmed label 10 days ago then?

**Comment by Oganku** [comment]
No idea, guess it wasn't tested ok, idk?

**Comment by Rushor** [comment]
Will check DB value

**Comment by Rushor** [comment]
hmm for me it stays in the air https://i.imgur.com/j0PjKPA.jpg ?

**Comment by Oganku** [comment]
On PTR it works, but yesterday in my RHC it didn't. I tried a bunch of things to try and replicate it but couldn't. I suppose I'll just keep an eye out if I ever get oculus again, but that was a false alarm from me.

**Comment by Oganku** [comment]
Just got oculus in an rhc again and it bugged again. I'm really confused.
I only managed to clip the end, but here it is:
https://imgur.com/a/cXSsSg6

So in PTR it's fine, but not on live. I guess maybe next week it'll be fine? I'm really not sure. @Rushor

**Comment by svijetlo** [comment]
thx for saying i did not testing ok =) in future i will post S.S.
