### ISSUE TITLE
[Dungeon] The Oculus' flags

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#5049]
**Links:** https://www.youtube.com/watch?v=TZC-NyHZ8gU
https://www.youtube.com/watch?v=4GigIXEA4KE
https://www.youtube.com/watch?v=f6KLV6P9LlY
And many more...

Possibly useful item links:
**Dragon Summon Items**
https://www.wow-mania.com/armory/?item=37859
https://www.wow-mania.com/armory/?item=37815
https://www.wow-mania.com/armory/?item=37860

**Call spell cast upon using item**
https://www.wow-mania.com/armory/?spell=49461
https://www.wow-mania.com/armory/?spell=49345
https://www.wow-mania.com/armory/?spell=49462

**Drake vehicles**
https://www.wow-mania.com/armory/?npc=27755
https://www.wow-mania.com/armory/?npc=27692
https://www.wow-mania.com/armory/?npc=27756

**What is Happening:** Players riding their dragon mounts are missing their faction's flag that they should be carrying.

**What Should happen:** As can be seen in any video from retail Oculus runs, players carry a Horde or Alliance visual flag while riding their dragons to help teammates locate them easier. Videos from 2009 retail wotlk up to modern retail wow both show these flags being there.

**Comment by Rushor** [comment]
do you know a similar aura where such effect is used in game?

**Comment by Rushor** [comment]
nvm got it

**Comment by Rushor** [comment]
flags added, you will wear them now if yu are on the vehicle, if you left the vehicle, they will vanish again
