### ISSUE TITLE
[Food] Stormchops

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#5050]
**Links:** https://www.wowhead.com/item=33866/stormchops#comments
https://www.wowhead.com/spell=43730/electrified#comments

**What is Happening:** This item used to be far more problematic but still has 2 issues:
1. The ["Zap"](https://www.wowhead.com/spell=43730/electrified#comments) proc currently occurs every ~2 seconds.

2. The Zaps can hit an unlimited amount of targets. They hit for small amounts of damage, but against huge trash pulls, it can do ~500 dps by itself.

3. It currently stacks with usual Well Fed buffs.

**What Should happen:**
1. The zaps should occur with an 8s interval.
![image](https://user-images.githubusercontent.com/34783736/96198713-93085180-0f23-11eb-8f46-e31ca812b630.png)

2. The zaps should only affect at most 2 enemies.

3. It should overwrite existing Well Fed buffs or vice-versa.
![image](https://user-images.githubusercontent.com/34783736/96198859-f2666180-0f23-11eb-9056-9f3ed2ee6684.png)

**Comment by Rushor** [comment]
this spell ID - 43733 Lightning Zap
