### ISSUE TITLE
The Cipher of Damnation quest mob not attackable - Naxxramas

### ISSUE THREAD

**Issue by timbazi** [WoWManiaUK/Redemption#5052]
**Links:**

**What is Happening:**
Cyrukh the Firelord is not attackable and wont attack after it's summoned using the item [The Cipher of Damnation]

**What Should happen:**
Should be able to attack and kill Cyrukh the Firelord

**Comment by jeyrella** [comment]
He is not supposed to be attackable.  You talk to the NPCs at the altar to start the event.
