### ISSUE TITLE
[Spell] Worg Form (Racial) removed by attacker skills

### ISSUE THREAD

**Issue by Searingstar** [WoWManiaUK/Redemption#5053]
**Links:** I can't find the spell link in https://www.wow-mania.com/armory/

**What is Happening:**
The worg form gets removed by certain abilities that should not remove it. I noticed it happens most when being attacked by Death Knights and Warriors, but happens with other classes too. Some examples from warriors are:
Thunder clap
Charge
Intimidating shout
Rend
Overpower
Mortal strike

Needs further testing.

**What Should happen:**
Worg form should not be removed, as its description reads exactly as Ghost Wolf from shamans, just with 20% less speed, and that one doesn't get removed from any ability.

**Comment by Keader** [comment]
Was caused by combat, and was wrong.
Blizzlike worg form should be removed if: worgen do melee attacks, cast any spell.
