### ISSUE TITLE
[Event/Boss] Headless Horseman spawns multiple copies of his Head

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#5054]
**Links:** https://www.wow-mania.com/armory/?npc=23682
https://www.wow-mania.com/armory/?npc=23775

**What is Happening:** In the Holiday dungeon, after killing the [Headless Horseman](https://www.wow-mania.com/armory/?npc=23682), the body starts spewing countless [Heads of the Horseman](https://www.wow-mania.com/armory/?npc=23775). The fountain will quickly flood the room with heads if the group doesn't kill the original rather fast.

**What Should happen:** After the horseman dies, a single head should appear from the corpse, as it used to in previous years.

**Comment by bLeyaa** [comment]
thief :(

**Comment by svijetlo** [comment]
**by order of janitor**
Links:
http://www.wow-mania.com/armory?quest=11135
https://www.youtube.com/watch?v=fC9ZCLzfl8Q&ab_channel=Incognito5x3x2x1
What is Happening:
ones 5 players enter fresh dung all 5 can take daily quest to summon horseman but after you do one quest other player even if they give in quest on grave horseman will not spawn

What Should happen:
after 1 horse man is killed and looted if other player give in quest it should summon new horseman to kill
at 2:02 min of vid you can see player going to summ 2nd one

**Comment by Echinaceax** [comment]
From what i remember how we used to do it @svijetlo is 

1. 1st player picks up the quest (and completes it)
2. 2nd player picks up the quest and completes it 
3. 3rd "" ""
4. 4th 
5. 5th etc

when i played on Mania on this event , problem was that the first player completed theirs then leaves 

players have to stay until all 5 players have done this daily quest , is it not working this way now @svijetlo ? coz it was last year

**Comment by Echinaceax** [comment]
I see the issue, This has change since i did this 

i just tested it now

1. All can pick up the quest at the same time (now) couldnt before
so when all players pick the daily up, only 1 kill counts for all who has the quest, coz i could complete it on first kill and so did others in the group

![i see the issue](https://user-images.githubusercontent.com/39439201/96366895-d1338a00-114a-11eb-9a4b-c811876fdf87.jpg)

**Comment by WhitephoenixTheBunny** [comment]
https://github.com/WoWManiaUK/Redemption/issues/3448
https://github.com/WoWManiaUK/Redemption/issues/4080
previous fix related with the event

**Comment by Keader** [comment]
Fixed.
Now he will only summon 1 head instead flood it.

**Comment by svijetlo** [comment]
yes last year all could take quest at same time but you can finish it one after other to summ him and form what i seen online data show that is how it should be , i made separate post but janitor told me to post it here so all is one bigger post for that boss

**Comment by Echinaceax** [comment]
yes thats how i remember it too @svijetlo , 
but "most videos data" is from other PServers thas the problem.




As @WhitephoenixTheBunny says in other reports, there has been issues for a while 

1 daily 1 run all complete daily 


> i made separate post but janitor told me to post it here so all is one bigger post for that boss

I know i saw it :)

**Comment by Keader** [comment]
i dont even understand what this discussion is about. '-'

**Comment by jeyrella** [comment]
![Uploading image.png…]()
