### ISSUE TITLE
[Raid] High Priestess Jeklik does not engage - Zul Gurub 

### ISSUE THREAD

**Issue by jeyrella** [WoWManiaUK/Redemption#5055]
**Links:**
https://wow-mania.com/armory/?npc=14517

**What is Happening:**
[High Priestess Jeklik ](https://wow-mania.com/armory/?npc=14517) does not engage on the pull, she stays on her ledge and does not fly down to start the encounter.   However players are left in combat, with no way to kill her.

**What Should happen:**
She should fly up and then down off her ledge, and combat should be begin.
See era-relevant videos:
https://youtu.be/R48hdaKR_BU?t=42
https://youtu.be/T9_oghoERTc?t=18

**Comment by Rushor** [comment]
texts, green channel added
should always engage combat properly now
