### ISSUE TITLE
[Event/Boss] Headless Horseman - quest 

### ISSUE THREAD

**Issue by svijetlo** [WoWManiaUK/Redemption#5057]
**Links:**
http://www.wow-mania.com/armory?quest=11135
https://www.youtube.com/watch?v=fC9ZCLzfl8Q&ab_channel=Incognito5x3x2x1
**What is Happening:**
ones 5 players enter fresh dung all 5 can take daily quest to summon horseman but after you do one quest other player even if they give in quest on grave horseman will not spawn

**What Should happen:**
after 1 horse man is killed and looted if other player give in quest it should summon new horseman to kill 
at 2:02 min of vid you can see palyer going to summ 2nd one

**Comment by Echinaceax** [comment]
From what i remember how we used to do it @svijetlo is 

1. 1st player picks up the quest (and completes it)
2. 2nd player picks up the quest and completes it 
3. 3rd "" ""
4. 4th 
5. 5th etc

when i played on Mania on this event , problem was that the fist player completed theirs then leaves 

players have to stay until all 5 players have do this daily quest , is it not working this way now @svijetlo ? coz it was last year
