### ISSUE TITLE
[Event/Boss] Headless Horseman event dungeon - missing mechanics

### ISSUE THREAD

**Issue by bLeyaa** [WoWManiaUK/Redemption#5058]
**Links:** N/A

**What is Happening:** Currently the boss is killed after the first time the head pops and is killed. The boss also does not spawn pumpkin adds and i believe he's not doing his bladestorm. Disorienting ability also missing as well.

**What Should happen:** Boss should reset to full hp after the first head was killed, only after the third head was killed should the fight end. At the same time, when the boss is being killed the third time - is when the boss starts spawning 3-4 pumpkins at a time. During the downtime of the boss he should be occasionally doing his bladestorm alike ability. Boss should also occasionally throw a pumpkin or something at a random player which disorients

TBC: https://www.youtube.com/watch?v=isU6aNKpwOg
WOTLK: https://www.youtube.com/watch?v=pJN3TmhekOQ ; https://www.youtube.com/watch?v=SQlUANV7mqM
WOD: https://www.youtube.com/watch?v=oPhATl0talM

**Comment by svijetlo** [comment]
re is most correct discerption of fight  https://www.youtube.com/watch?v=QAdap91uSHA&ab_channel=dungeoncrusader all this it is form MbP fight was same in WOTLK 

Phase one
The Horseman makes his entrance and engages **whoever lit the candle**. The tank should taunt immediately if the did not start the event. Watch out for  [Cleave] and DPS him down.

At 1% the horseman will go immune, toss his head, walk around disoriented, and occasionally use a  [Whirlwind] attack. The Head of the Horseman will become an active target while the body heals to 100%. All DPS should have a target macro for Head of the Horseman. After the party damages the head to about 60%, or the body heals to 100%, the head will rejoin the body and the next phase begins.

Phase two

The Pumpkin Shrine.
When the Horseman rejoins with his head, he targets the player with the highest threat. This is the same as phase one except he will randomly cast Conflagration on a random party member (not the tank). You can use a PvP Trinket to remove the Conflagration. Healers and ranged DPS should be alert to the location of both tank and Conflagration target; steer clear of these.

Phase two ends if the head reaches about 30% health, or when the body heals to 100%.

Phase three
The Horseman does not use Conflagration in Phase Three. Eventually he will toss four Pulsing Pumpkins, which sprout Pumpkin Fiends after several seconds, and they will completely heal. The fastest course of action seems to be having the tank stand in the middle of the pumpkins with focus abilities at the ready. The rest of the party continues DPS on the Horseman until his head is tossed. If the party has low DPS, a second or even third wave of Pulsing Pumpkins can be spawned before the head is tossed.


Once the Head of the Horseman dies, the Headless Horseman has been defeated, and the remaining pumpkins will die. If you don't kill the Head of the Horseman before the Horseman heals to 100%, Phase Three will repeat, meaning you have to nuke the Horseman again to get him to toss his head.

**Comment by Keader** [comment]
Script remade.
test now.
