### ISSUE TITLE
[AV][Battlegrounds] Sometimes when dying and a base is soonly after captured, you won't be transported to a valid graveyard

### ISSUE THREAD

**Issue by Searingstar** [WoWManiaUK/Redemption#5059]
**Links:**
No links

**What is Happening:**
When someone realeases spirit, and the base is soonly after capped, the person who released will be teleported to the graveyard of that base and the "resurrecting spirit" will disappear, leaving the person as a ghost in the graveyard. The only way to revive after that, is to walk to a currently owned graveyard. I can confirm this has happened to me in Arathi Basin and Eye of the Storm battlegrounds. This doesn't happen too often, but when it happens it is very annoying and gives high advantage to the team on the non receiving end. To reproduce this, one person must die and release spirit, just when that person releases, the base must be capped, with a little time difference.

**What Should happen:**
When a base is not currently owned all the spirits should be teleported to a current valid graveyard to start resurrecting.

**Comment by Rushor** [comment]
I can Provide a fix for av

**Comment by Oganku** [comment]
I confirm this happens, but I never looked to see if it was blizzlike or not (it probably isn't). Also the main ones where it happens the most are AB and Eots. If the AV fix can be copied to those it would be ideal.

**Comment by Kinkywiener** [comment]
Can happen also while the resurrection timer reaches 0, following a short delay before the player gets resurrected. When the base gets capped during this delay (especially at start), the player doesnt get TPed to the closest owned base graveyard. 
Just mentioning the same issue, different situation.

**Comment by Rushor** [comment]
fixed for AV for now - for the other i cannot fix it for now

**Comment by svijetlo** [comment]
worked fine to me in AV if i die and place got capured it would send me back to proper graveyard
