### ISSUE TITLE
[Spell] Killing Spree - ID 51690

### ISSUE THREAD

**Issue by bluemonstrr** [WoWManiaUK/Redemption#5060]
**Links:**
https://wow-mania.com/armory/?spell=51690

**What is Happening:**
Currently Killing Spree is able to hit stealthed targets and is able to be used if there is a stealthed target within it's radius.

**What Should happen:**
Killing Spree should not be able to go off at all if there is only a stealthed target in the radius. Additionally it should not hit them even if there is another target unstealthed in the radius.

(edit: jey: added armory link)

**Comment by Keader** [comment]
test now pls
