### ISSUE TITLE
Chaos Bane (Shadowmourne) wrong damage scaling

### ISSUE THREAD

**Issue by bLeyaa** [WoWManiaUK/Redemption#5061]
**Links:** https://www.wow-mania.com/armory/?spell=71904

**What is Happening:** The spell currently has increased base damage by what seems to be 50% on warriors and up to 103% on retribution paladins on single target. When it comes to AOE the damage on warriors remains increased by 50% while on paladins it starts scaling a lot more, during test it went up to 272% increase. AOE test was done with 5 targets on each class.

**What Should happen:** The base damage of Chaos Bane should vary between 1900 and 2100 as per the tooltip. This damage should only be modified by %damage multipliers from talents, abilities and ICC buff. Examples: [here](https://www.wow-mania.com/armory/?spell=31869), [here](https://www.wow-mania.com/armory/?spell=48266), [here](https://www.wow-mania.com/armory/?spell=31884), [here](https://www.wow-mania.com/armory/?spell=48511), [here](https://www.wow-mania.com/armory/?spell=49664), [here](https://www.wow-mania.com/armory/?spell=31868) and [here](https://www.wow-mania.com/armory/?spell=49222)... (i'm sure there's some more :P)

### Some results from testing:

**Single target naked warrior:**
![image](https://user-images.githubusercontent.com/61625377/96935403-4349fd00-14c4-11eb-87ff-5889a7a35cc8.png)

**AOE (5 target) warrior:**
![image](https://user-images.githubusercontent.com/61625377/96935427-5361dc80-14c4-11eb-920f-4f3221dcf614.png)

**You will see damage goes up to 3150 max on each (630x5=3150) which is exactly 50% increase to 2100 max damage it should be dealing.**

**Single target naked paladin:**
![image](https://user-images.githubusercontent.com/61625377/96935575-a5a2fd80-14c4-11eb-9823-d5a9f9dc9d30.png)

**AOE (5 target) paladin:**
![image](https://user-images.githubusercontent.com/61625377/96935601-b3f11980-14c4-11eb-8665-e3848876420f.png)

**As you can see on AOE paladin's split damage goes up to 1563 damage per target which means 7815 from a single Chaos Bane.**

**Comment by bLeyaa** [comment]
This being spell damage, it seems to be benefiting from spell power as well.
As the only classes that use Shadowmourne are melee, the benefit would really only come from elemental shaman or demonology warlock buffs. :)

**Comment by svijetlo** [comment]
any ptoof form back in day or you just say it is wrong ?

**Comment by bLeyaa** [comment]
Well, the tooltip itself says it:
![image](https://user-images.githubusercontent.com/61625377/97028057-e1d56d00-155b-11eb-8f55-5c76812efee8.png)

You can also take a look at the random log below from Method back in the days:
![image](https://user-images.githubusercontent.com/61625377/97028466-78a22980-155c-11eb-9799-9281f999e5b4.png)
http://www.worldoflogs.com/reports/mfxew5mdm3orj505/spell/71904/?s=3308&e=3508

The average hits for paladin are 3k under full buffs/debuffs on boss under ICC buff... I can get more than that on a dummy right now :)

**Comment by wow-mania** [comment]
Stop googling for issues, please. You either faced this issue yourself or not.

**Comment by bLeyaa** [comment]
Googling for issues??? Lmao it was reported by 2 guildies. Feel free to talk to either Vince or Diplo in game about it as they told me something was wrong with it.

**Comment by VinceHybrid** [comment]
I actually reported it to Bleya, i was practicing on the dummies with my friend Diplo and noticed it doing 400 damage on my Warrior, and 1500 damage on his Paladin. He's not to blame sir, excuse me jumping in.

**Comment by Keader** [comment]
It's valid.
Is scaling with Spell/Attack Power

**Comment by svijetlo** [comment]
![image](https://user-images.githubusercontent.com/61908373/97183170-b8a41f00-179d-11eb-9eb0-531198c582b0.png)
ret paly it does same with or wo gear on so dmg is just based on its own it will not scale with att or SP
