### ISSUE TITLE
[Mount] Mountable area set too small for Battle Before Citadel quest

### ISSUE THREAD

**Issue by cathyr1** [WoWManiaUK/Redemption#5062]
One mechanic of this mount mount https://www.wow-mania.com/armory/?npc=33531 is broken. While doing quest https://www.wow-mania.com/armory/?quest=13847, there are many mobs stacked near Icecrown Citadel which we need to kill. They are already in the location called Icecrown Citadel. When we charge them, we are suddenly dismounted among these strong mobs which is instant death.

This wasn´t broken before and did not remember on retail such dismounts. Something changed but it should not be like this.

**Comment by Rushor** [comment]
at a certain area, you get dismounted because you can use those mounts only in specific areas? What is the name of the area where you have been dismounted? can you attach a screenshot?

**Comment by cathyr1** [comment]
Screenshot will be available tomorrow as for today I have the daily done. But the area is probably Icecrown Citadel and the mobs are in this area.

**Comment by Rushor** [comment]
yes okay, just need the exact position then

**Comment by jeyrella** [comment]
Seems the area for eiligibility for phasing is slightly off.  Video taken on Live as PTR is down:
https://youtu.be/0fxdNtEREhM

Dismounted at 51.4,77.4 in The Court of Bones, the eligible area should go all the way back to the bottom of the stairs

**Comment by jeyrella** [comment]
also seems to come across diagonally on the right side, around 49 78, that also should be pushed back a little southwest as there is a Commander group in that corner that is unreachable
![image](https://user-images.githubusercontent.com/46089380/97024866-36beb680-154f-11eb-91a3-85fa756f94f9.png)

**Comment by jeyrella** [comment]
Also affects inevtibly (perhaps obviously) 13861, 13862, 13863, 13864 ("Battle before the Citadel"), being the follow-up quest, as they use the same mapped area.

**Comment by jeyrella** [comment]
Perhaps something to do with https://www.wow-mania.com/armory/?spell=64576

**Comment by cathyr1** [comment]
Here is my screenshot just in the moment while dismounting.
![screen](https://user-images.githubusercontent.com/30184491/97080969-8492f780-15ff-11eb-8f67-f6d876e0d2ac.jpg)

**Comment by Rushor** [comment]
issue is that there is a condition for the mounted area, will adjust it for the missing areas

**Comment by Rushor** [comment]
fixed

**Comment by Oganku** [comment]
Looks good. 

![image](https://user-images.githubusercontent.com/34783736/97195062-41f92880-1781-11eb-9e45-8ee714ca6b32.png)
