### ISSUE TITLE
[Quest] Glacial Wrists

### ISSUE THREAD

**Issue by cathyr1** [WoWManiaUK/Redemption#5063]
This quest https://www.wow-mania.com/armory/?quest=9238 and all other similar quests offered by NPC https://www.wow-mania.com/armory/?npc=16376 should be removed from the game and not be even available as they can never be completed. The items required for them https://www.wow-mania.com/armory/?item=22682 are not in this game. It was in Naxxramas lvl 60.

**Comment by svijetlo** [comment]
it is vanilla quest though do to move of naxx it can not be completed , it is still correct to keep it there as there is lot more of things like this , only change to this npc has been don in cataclysm expansion , so as it stands now this npc and quests he gives are as-is
