### ISSUE TITLE
[Quest] The Kessel Run ground mount is flying if player took while on flying mount

### ISSUE THREAD

**Issue by svijetlo** [WoWManiaUK/Redemption#5064]
**Links:**
https://www.youtube.com/watch?v=WEk1_ZkaGYM&ab_channel=WCQuests
http://www.wow-mania.com/armory?quest=9663
**What is Happening:**
if high level player with fly mount go there and takes the quest , mount will be transformed to elephant and will fly around 
https://media.discordapp.net/attachments/656586187816960003/769226346378559549/20201023_175032.jpg?width=893&height=413

**What Should happen:**
player should be dismounted and get quest GROUND mount elephant for time of quest

**Comment by jeyrella** [comment]
Confirmed! lol
![image](https://user-images.githubusercontent.com/46089380/97029486-67a1ea00-1555-11eb-8c20-801b07d1f045.png)

**Comment by jeyrella** [comment]
Also, if you abandon the quest, you are still left mounted on the elephant.

**What should happen**
If you abandon the quest, you should be dismounted (lose the aura)

**Comment by jeyrella** [comment]
This is possibly because the mount aura you have at start is not cleared on taking the quest
![image](https://user-images.githubusercontent.com/46089380/97030017-1d6d3880-1556-11eb-8d3a-4c2aa0ef7b4f.png)

**Comment by Rushor** [comment]
changes:

- you now get dismounted from other mounts before you get the elekk buff
- there is a internal check now once you have the elekk buff. If you abandon the quest, you will get dismounted after 5 seconds

**Comment by jeyrella** [comment]
Neither seems to be happening.

**Comment by Rushor** [comment]
hmm kessel works for me just fine, maybe was related to build fix? https://gyazo.com/6b4c1dab16f1a4005e0cafabf900ac73 can try again?

**Comment by jeyrella** [comment]
Fixed 👍 https://youtu.be/4AKblZM8rI0
