### ISSUE TITLE
[Spell] Banish/Immunity

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#5065]
**Links:** https://www.wow-mania.com/armory/?npc=23035#objective-of
https://www.wow-mania.com/armory/?spell=42354
https://www.wow-mania.com/armory/?npc=11583
https://wow.gamepedia.com/Nefarian_(tactics)

**What is Happening:** NPC Immunities such as [Nefarian's](https://www.wow-mania.com/armory/?npc=11583) first phase immunity or [Anzu's](https://www.wow-mania.com/armory/?npc=23035#objective-of) [Self Banish](https://www.wow-mania.com/armory/?spell=42354) are ignored by yellow damage (spells and special skills). White damage is correctly prevented.

**What Should happen:** Immunities should apply to both white and yellow damage, or any other sort honestly. I assume whichever flag is used for such immunities is globally broken since it started affecting multiple NPCs at the same time.

**Edit:** Also affects [Argent Confessor Paletress'](https://www.wow-mania.com/armory/?npc=34928) [Reflective Shield](https://www.wow-mania.com/armory/?spell=66515). You can therefore kill Paletress without even touching her summon.

**Comment by bLeyaa** [comment]
Same happens with http://www.wow-mania.com/armory?spell=72066 and http://www.wow-mania.com/armory?spell=72065

**Comment by Keader** [comment]
Fixed.
