### ISSUE TITLE
[Quest] Saving Princess Stillpine

### ISSUE THREAD

**Issue by Greywolf59** [WoWManiaUK/Redemption#5067]
**Links:**
https://www.wow-mania.com/armory/?quest=9667
https://www.wow-mania.com/armory/?npc=17682

**What is Happening:**
Even after completing all prerequisite quests the NPC does not offer the quest

**What Should happen:**
After completing furbolg line quest chain on Azuremyst Isle the quest should be available at the NPC.

**Comment by Oganku** [comment]
Tested with 2 different ally races (Human and Draenei) and completing quest #9538 opens up Saving Princess Stillpine (#9667) properly. 

Proof:
![image](https://user-images.githubusercontent.com/34783736/97123762-a4134880-1703-11eb-9ac3-ae38142f228a.png)

Might need more info on how to reproduce

**Comment by jeyrella** [comment]
@Greywolf59 can you please give myself or @Oganku details on your race and faction.  You can find us on discord if you like if thats easier, please quote github 5067.

**Comment by Greywolf59** [comment]
Geshoia / Lick far here. My faction is human warrior. I did all the quests available for humans in Azuremyst Isle, also on Bloodmyst Isle (I am using carbonite and several search engines). I did aformentioned quest https://www.wow-mania.com/armory/?quest=9538 and all the following quests up to and including https://www.wow-mania.com/armory/?quest=9622 @Oganku . No quest at Princess stillpine avaialble. I think one other player (Night elf druid Leandra) confirmed it on Naxx, though she cannot remember for certain.

**Comment by jeyrella** [comment]
Just ran through this chain as human warrior, and as soon as 9538 is completed, Saving Princess Stillpine is available.

![image](https://user-images.githubusercontent.com/46089380/97233839-916a4380-17d7-11eb-8478-a7d26eb2411e.png)

Best I can advise is have GM assistance. They will need to check you have completed quests:
9538
9539
9540
9541
9542
9544

If any one of those is not completed, they will be able to see and advise.

Alternatively you could get hold of EveryQuest addon yourself and do a server query, which will show which quests in that line you have not completed.  Post the screenshot here if you have.
(If you're doing Loremaster, I'd advise you get hold of it anyway :) )

**Comment by Greywolf59** [comment]
I do nit have everyquest but I remember what quests I did a day ago really. And since I see on carbonite questgiver icons with the list of their quests and thise I did I always know what I did. But sure I can download it.

**Comment by Greywolf59** [comment]
I checked all quests you listed. I done all of them. Please try checking if doing following stillpine hold chainquest up to "warn your people" does not block saving the princess

**Comment by GMZinius** [comment]
A little note on this one.
Player reported this today, after checking all the questline for this the player had completed all. 
- I reset the NPC Princess Stillpine and let her respawn herself (2 mins timer) Then the player could pick up the quest.
