### ISSUE TITLE
[Raid] Blackwing Lair portcullis after Broodlord Lashlayer

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#5068]
**Links:** https://www.wow-mania.com/armory/?npc=12017
Not sure which [portcullis](https://www.wow-mania.com/armory/?search=portcullis) it is :(  
https://www.wow-mania.com/armory/?object=180424

**What is Happening:** There are currently 2 gates behind Broodlord Lashlayer in Blackwing Lair. The portcullis (ID unknown) is currently clickable by players and does not open upon boss death. It's fairly useless and requires the player to click an additional door after defeating the boss.
![WoWScrnShot_102520_211313](https://user-images.githubusercontent.com/34783736/97124577-fdc94200-1706-11eb-9f19-3c045d88f045.jpg)

However, there is **also** an [Alterac Valley Gate](https://www.wow-mania.com/armory/?object=180424) (lol?) right behind the portcullis, that correctly opens after the boss dies.
![WoWScrnShot_102520_211324](https://user-images.githubusercontent.com/34783736/97124579-fefa6f00-1706-11eb-8471-44274133e077.jpg)

**What Should happen:** Either remove the redundant portcullis and only keep the correctly working Alterac Valley Gate, or remove the Alterac Valley Gate and transfer its properties to the portcullis. Since I'm not sure which one isn't supposed to be there (probably the Alterac Valley Gate), it doesn't really matter which one is removed as both fit the environment well. As long as the one that remains still opens after the boss dies, then all would be perfect.

**Comment by Rushor** [comment]
removed the duplicate
