### ISSUE TITLE
[Quest] Leading the Charge in Icecrown

### ISSUE THREAD

**Issue by ReiyneStabs** [WoWManiaUK/Redemption#5069]
The quest involves flying a plane in a small circle around Icecrown.  The Gargoyle Ambushers should attack the plane and should be able to be shot down, but when I fire missiles at them they don't take damage and it says EVADE.  For whatever reason they don't seem to aggro on the plane or take damage, so I can't finish the quest.  Might just be a problem for me, but it doesn't seem like very many people quest in Icecrown so it may have gone unnoticed.  Thanks y'all :)

**Comment by wow-mania** [comment]
Pretty sure it works. Don't go fixing without confirming please.

**Comment by Rushor** [comment]
yes the aggro and evade thing is a known bug that cannot be resolved so far. I will check if the credit is still rewarded, else we must adjust it

**Comment by Rushor** [comment]
okay tested, it is indeed bugged for the alliance, for horde it works

**Comment by Rushor** [comment]
The Gargoyle Ambushers will die now upon using the spell in the right direction - other evade issue stays as is to prevent further issues

**Comment by jeyrella** [comment]
......  this has worked in the past?  I have in done on 6 alliance toons....

**Comment by svijetlo** [comment]
worked fine to me
