### ISSUE TITLE
[Drop] Cache of the ley guardian

### ISSUE THREAD

**Issue by Speedpack** [WoWManiaUK/Redemption#5070]
**Links:**
Didn't found the link to "Cache of the Ley-Guardian" (its from the end chest of Oculus Dungeon)

**What is Happening:**
The drop rate, as a GM told me, is 59% and i didn't got it in over 8 times. The Chance for no drop in 8 times is 0,0008%. It is not unlucky anymore and i wasted a lot of time for that.

**What Should happen:**
It should drop so i get a chance for the [Reins of the blue drake]. I hope u can help me.

**Comment by Keader** [comment]
you know that probability not work like that right? xD

**Comment by Oganku** [comment]
The cache only drops on heroic if you got in the instance by the random dungeon finder. If you queue specifically for it, you get no cache. From my experience it drops every single time.

![image](https://user-images.githubusercontent.com/34783736/97180037-f1c59a80-176f-11eb-82e2-c9e20b2c1c41.png)

**Comment by jeyrella** [comment]
RNG is RNG.
