### ISSUE TITLE
[Fishing] Specific Waterlogged Wreckage in STV cannot be fished in

### ISSUE THREAD

**Issue by jeyrella** [WoWManiaUK/Redemption#5071]
**Links:**
https://www.wow-mania.com/armory/?object=180685

**What is Happening:**
The Waterlogged Wreckage at exactly 26.5, 19.9 in Stranglethorn Vale cannot be fished in, since it is in a position that is technically on land, and therefore the bobber cannot land on it.
![image](https://user-images.githubusercontent.com/46089380/97237310-c7f78c80-17de-11eb-9d8f-49adc3aec66c.png)
![image](https://user-images.githubusercontent.com/46089380/97237554-45bb9800-17df-11eb-9958-9b160cfe954e.png)

**What Should happen:**
Pool should be moved out seawards by 5-10 yards so that fishing bobbers can land on it ("target" it),

**Comment by Rushor** [comment]
fixed once ptr is restarted

**Comment by Rushor** [comment]
moved it to a slightly different spot https://i.imgur.com/HkMlx1H.jpeg

**Comment by jeyrella** [comment]
Perfect, thanks

![Uploading image.png…]()
