### ISSUE TITLE
[Spell] Vanish - not dropping threat

### ISSUE THREAD

**Issue by bLeyaa** [WoWManiaUK/Redemption#5074]
**Links:** https://www.wow-mania.com/armory/?spell=26889

**What is Happening:** Vanish is not resetting threat when used against mobs or bosses. (in raid environment at least, haven't check in world)

**What Should happen:** Vanish should remove all threat upon being used, same as Feign Death on hunters.

https://youtu.be/ak2-z7ShoQc?t=165 - Rogue uses vanish as part of dps rotation, on his Omen you can see his threat dropped down completely.

https://wowwiki.fandom.com/wiki/Vanish

https://www.wowhead.com/spell=1856/vanish#comments

From the above links:

![image](https://user-images.githubusercontent.com/61625377/97265614-3e1fe180-1827-11eb-91b5-ed64d050c96c.png)
![image](https://user-images.githubusercontent.com/61625377/97265765-78897e80-1827-11eb-9ded-d5a2d4ac626d.png)
![image](https://user-images.githubusercontent.com/61625377/97265831-97881080-1827-11eb-8f07-b1cdd320a1f8.png)

**Comment by bLeyaa** [comment]
I would assume it may have been affected by #4962

**Comment by svijetlo** [comment]
this is true i wanted to make post today , but guess you beat me to it good job

**Comment by jeyrella** [comment]
In that case we should probably thoroughly test other threat reset skills and talents in other classes as well

**Comment by Keader** [comment]
try now pls
