### ISSUE TITLE
[Transmog] Hair style/color not persistent through relogs after head transmog applied

### ISSUE THREAD

**Issue by joka95** [WoWManiaUK/Redemption#5075]
**Links:**
First Mate Hat
http://www.wow-mania.com/armory?item=2955

**What is Happening:**
When i put this transmog my hair disapier.When i go to store to change my hair style my hair is showen nice with transmog like it shoud. Then when i do log out and come again online hair is gonne again. Again go change hair style hair is agan there. Can it be fixed ? So can be look nice as should.

**What Should happen:**

Hair should be showen with transmog on head.
![received_364050434709030](https://user-images.githubusercontent.com/63783357/97289871-0f663300-1848-11eb-9651-69afa7656c5f.jpeg)
![received_2818719468384376](https://user-images.githubusercontent.com/63783357/97289874-10976000-1848-11eb-94b5-20a2019bc5b3.jpeg)

**Comment by jeyrella** [comment]
I can ask one of the testers to try this, but we will more than likely need exact item names (I see you are draenei race.)

**Comment by svijetlo** [comment]
i will try it later it is that pirat hat that cos it

**Comment by svijetlo** [comment]
here the deal , 
even item it self if you equip it hair is gone but if you change hair at barber it will be there 
but if you unequip then equip item hair is gone 
same goes for relog after relog hair is gone 
same applies if you mog any other head gear to that First Mate Hat

**Comment by jeyrella** [comment]
is this an issue for this specific item, or does it happen with other (every) head gear?

**Comment by svijetlo** [comment]
not sure need to check rest of head gear hats etc

**Comment by wow-mania** [comment]
This is not a custom item which means this is a retail issue. We won't be looking into this.
