### ISSUE TITLE
[Event/ Achievement ] Sinister Calling 

### ISSUE THREAD

**Issue by svijetlo** [WoWManiaUK/Redemption#5076]
**Links:**
https://www.wowhead.com/achievement=292/sinister-calling
http://www.wow-mania.com/armory?achievement=292
**What is Happening:**
after player get Pet http://www.wow-mania.com/armory?spell=42609 and uses it ,pet is counted for ach 
while no matter in what way player get helmet http://www.wow-mania.com/armory?item=33292 and equip it it is not counted for ach 

**What Should happen:**
ones you get to your beg pet and use it and ones you get helmet and equip it you should get ach completed 

P.S. it should be fix fast or help players somehow to get ach as lot of ppl farm it for even completion title and for drake ones you get all event titles

**Comment by jeyrella** [comment]
I think this can be simplified.  Even the wowhead comments say the helm does NOT need to be worn, only looted.

We can simplify this to:  Looting the helm from **the boss** should count for the achievement (as well as the bag, which works).

**Comment by svijetlo** [comment]
helm does not count for ach no matter how you get loot form boss or form daily gift bag

**Comment by jeyrella** [comment]
Yes, it does, I have the achievement on all toons, from looting from the bag

**Comment by bLeyaa** [comment]
I got it on a few toons, i think each helm came from the bag tho.

**Comment by svijetlo** [comment]
few ppl told me they did not get ach even if they equip helm no matter how they got it , and i try on ptr it did not work

**Comment by Oganku** [comment]
Currently bag works, but boss loot doesn't count.

**Comment by jeyrella** [comment]
Equipping the helm is not the achievement;  looting it is.
![image](https://user-images.githubusercontent.com/46089380/97339722-d5625480-187a-11eb-8eff-c445413fd5e6.png)

The bit that's not working is looting from boss should count, and it currently does not.

**Comment by Rushor** [comment]
looting system must be updated here then for that achievement

**Comment by Rushor** [comment]
looting it manually from boss works aswell for me https://i.imgur.com/tkqtkzO.jpg maybe it just is not working if the loot is party loot from lfg? Can you test if the achievement works for you solo? maybe it is just not working in a group then, when loot is rolled?
