### ISSUE TITLE
Voting on Gtop100 doesn't go to wow-mania.com

### ISSUE THREAD

**Issue by billykitty** [WoWManiaUK/Redemption#5078]
**Links:**
https://gtop100.com/

**What is Happening:**
Since 10/7 when I vote on Gtop100 (https://gtop100.com/) and click our website and the visit button, it tries to go to http://www.wow-mania.org/ and I get the error "The service you've requested couldn't be identified".

**What Should happen:**
It should go to http://www.wow-mania.org/ or at least be redirected to the right website.

**Comment by jeyrella** [comment]
This is not a game server issue.  However I have pointed janitor in this direction.
