### ISSUE TITLE
Hunter Tame Beast spell

### ISSUE THREAD

**Issue by juanitawos** [WoWManiaUK/Redemption#5079]
**Links:**
https://wotlk-twinhead.twinstar.cz/?spell=1515

**What is Happening:**
When I go to hit tame beast and it starts channeling, it will complete the spell but it does not tame the beast theirfore I will have to hit tame beast again and then it will tame the pet.  I tried this with a new hunter and after I finished the quest line Taming the Beast I went to tame a plainstrider and I hit tame beast, it went for 20 sec then stopped and I had to hit tame beast again

**What Should happen:**
When the hunter hits tame beast it will cast for 20 seconds and then tame the beast (if the hunter has not been interrupted by a knockback or stun spell)

**Comment by Rushor** [comment]
there is always a  chance to fail - that is intended. But in the end you could tame it right?

**Comment by GMMetaxa** [comment]
Nothing wrong here. When the pet hits you, there's a chance the spell stops. Use a frost trap ;)

**Comment by juanitawos** [comment]
it does tame, its just the tame fails every time i have tried to tame one on my horde or alliance and i do use frost trap, but the tame beast spell will go the full 20 sec and then fail without giving me a message like if the herbing fails.  if it is part of WOTLK back then thats fine because its not stopping me from taming pets, but if it is a bug i just would like someone to look into it

**Comment by Echinaceax** [comment]
Seems there was an issue with this @GMMetaxa 
fixed now here #5294
