### ISSUE TITLE
[Hunter] Pet Size

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#5080]
**Links:** https://www.youtube.com/watch?v=wirrLsx-P54
https://www.youtube.com/watch?v=15QCUMMi5zU
https://www.youtube.com/watch?v=oo_ngG136_E
https://www.youtube.com/watch?v=tsK4bc5c8qk
https://www.youtube.com/watch?v=VOzUoZe44lI

**What is Happening:** Core Hounds and Devilsaurs are 2 examples of pets that are currently way too small. On all videos above, you can see the devilsaur way taller than the dwarf, and even taller than a Tauren. However, in mania they're shorter than humans. Core hounds also look like puppies currently. 

**What Should happen:** Maybe there's a size modifier applied to pets that shouldn't be there? They should be bigger though.
(Almost feels like a 0.5-0.7x modifier from the videos I've looked at)

**Comment by Rushor** [comment]
Will check that

**Comment by wow-mania** [comment]
As-is.

**Comment by Rushor** [comment]
it can be fixed and i have a fix for it, if you wish to get it applied let me know
