### ISSUE TITLE
[PVP] Friendly fire after duel (Killing Spree)

### ISSUE THREAD

**Issue by bLeyaa** [WoWManiaUK/Redemption#5081]
**Links:** https://youtu.be/mszWFSDkcyk

**What is Happening:** If a rogue finishes the duel with Killing Spree, the auto attacks will keep on going at the target even if friendly.

**What Should happen:** Auto attacks should stop once the duel has finished. I haven't been able to reproduce the above in Dalaran so i would assume it's something that can only happen in the outdoor areas.

**Comment by bLeyaa** [comment]
I haven't seen similar report regarding this so idk... It sounds weird to be possible to do it in one place but not the other though.

**Comment by Keader** [comment]
Not same case ...
The other ones spells still hit target.
In this case melee hits can hit target until he die

**Comment by svijetlo** [comment]
anyhow still miss proof form back in day =) was it like this or different

**Comment by Keader** [comment]
Dont need.
Only travelling spells can kill target after duel (blizzlike bug)
0 spells should keep you melee hiting someone after duel.

**Comment by bLeyaa** [comment]
Some things are just obvious.... but to please you here's a combat rogue video

https://youtu.be/0MaGXVq1QuE?t=424

**Comment by svijetlo** [comment]
you do not need to please me , I'm not important here, but i do work under orders =)

**Comment by wow-mania** [comment]
This video is not wow-mania.
I have already told you to stop bringing bugs from other places.
Only log things you have experienced yourself.

**Comment by bLeyaa** [comment]
The video from first post is from mania lol... i recorded it myself it's my character xd

The second video is proof from retail i posted for svijetlo as he asked for proof lol

**Comment by Keader** [comment]
Issue is valid, tested in ptr.
fixed.

**Comment by Oganku** [comment]
https://imgur.com/a/duej35F
