### ISSUE TITLE
broken ability after crash

### ISSUE THREAD

**Issue by Dmw1981** [WoWManiaUK/Redemption#5082]
**Links:**
was logged in and playing hunter during crash logged back in to find chimera shot ability broken.
am using a full fresh 2.8 mania client. manually deleted cache but no luck
chimera shot will not fire. attempted use triggers auto attack and then "spell not ready" all other shots "so far" seem to be okay

**What Should happen:**

shot should fire

**Comment by Rushor** [comment]
This must be fixed by a gamemaster, pls contact one to fix it, thanks

**Comment by Dmw1981** [comment]
i did was told to report it here after manuall cache detetion DID NOT WORK

**Comment by Dmw1981** [comment]
multiple people are reporting similar probs with some of their abilities on world chat
