### ISSUE TITLE
Hearthstone CD 11Hrs

### ISSUE THREAD

**Issue by kasparux** [WoWManiaUK/Redemption#5083]
**Links:**
https://www.wowhead.com/item=6948/hearthstone

**What is Happening:**
noticed that hearthstone cd changed to 11hrs instead of 30 mins. Using latest version and game launcher.

**What Should happen:**
should be 30min cd
![WoWScrnShot_103120_140246](https://user-images.githubusercontent.com/73744468/97779498-229a3b00-1b87-11eb-91b4-1aca44300ab6.jpg)

**Comment by Dmw1981** [comment]
i was midfight when it crashed and my chimera shot went fubar i wonder if were you hearthing when crash happened

**Comment by kasparux** [comment]
I think i wasn't hearthin during the crash. But before server restart it was ok. I noticed this isue when i loghed second time after restat.

**Comment by jeyrella** [comment]
this is not a problem with the server code.  this is an in-game issue.

**Comment by Dmw1981** [comment]
have been informed is because we happened to be logged in during the crash, no fix just wait 24 hrs or use another toon. GREAT
closing tickets people are told to make doesn't help resolve things
