### ISSUE TITLE
posted auction items gone after crash

### ISSUE THREAD

**Issue by hisanam** [WoWManiaUK/Redemption#5084]
**Links:**
http://www.wow-mania.com/armory?item=49906 http://www.wow-mania.com/armory?item=34052

**What is Happening:**
posted few items on AH, but the most noticeable is the 1 Hellfrozen Bonegrinder and 10 Dream Shards. It's gone after the crash, including some of the same items from different sellers (they might experienced the same issue). Nothing in mailbox either.

**What Should happen:**
items should be shown in my toon auction's tab. and if it's sold then i should receiving the gold in mailbox (which i doubt, since i dont think about 3 Hellfrozen Bonegrinders around 5k+ are sold in such a short time).
![WoWScrnShot_103120_194918](https://user-images.githubusercontent.com/73744883/97779806-30fe4c00-1bb3-11eb-910f-042653c2e996.jpg)
![WoWScrnShot_103120_194904](https://user-images.githubusercontent.com/73744883/97779803-28a61100-1bb3-11eb-87be-617c69410e5e.jpg)
![WoWScrnShot_103120_194914](https://user-images.githubusercontent.com/73744883/97779805-2cd22e80-1bb3-11eb-939f-b77326e4a7ff.jpg)

**Comment by jeyrella** [comment]
this is not a problem with the game code.  it is an in-game issue due to the time change.
