### ISSUE TITLE
[Raid] Lady Deathwhisper's Mind Control can MC players through gate

### ISSUE THREAD

**Issue by jeyrella** [WoWManiaUK/Redemption#5086]
**Links:**
https://wow-mania.com/armory/?npc=36855

**What is Happening:**
When players are under Lady Deathwhisper's Mind Control, they can be MCd through the gate.  When the MC ends, player is left on wrong side of gate for the rest of the fight.

**What Should happen:**
Players should not be able to pass through the gate when under Lady Deathwhisper's Mind Control

**Comment by bLeyaa** [comment]
Same applies for the other side of the gate, if players didn't enter before the encounter began they can be MCed and move through to enter the area.

**Comment by svijetlo** [comment]
under no condition player should be able to pass closed gates

**Comment by Keader** [comment]
it's not lady deathwhisper issue, is a core issue.
Any CC (like fear, polymorph, blind) can cause similar issues.
for now, i dont know how fix issues like that, motion master is ignoring any object
