### ISSUE TITLE
Boat from Wetlands to Auberdine just dumps you back in the wetlands at the cemetary.

### ISSUE THREAD

**Issue by Lyrilin** [WoWManiaUK/Redemption#5087]
**Links:**

**What is Happening:**The boat from the Wetlands to Auberdine just dumps you back in the Wetlands in the cematery...

**What Should happen:** Should go to Auberdine

**Comment by jeyrella** [comment]
Just did this on two toons, works fine.  Is something to do with your game.  Clear cache, use launcher.  If still a problem contact a GM in game.

**Comment by Lyrilin** [comment]
I tried to use launcher but it didn't work so I just clicked on the game icon....
    On Saturday, October 31, 2020, 05:51:54 PM CDT, jeyrella <notifications@github.com> wrote:  
 
 


Just did this on two toons, works fine. Is something to do with your game. Clear cache, use launcher. If still a problem contact a GM in game.
