### ISSUE TITLE
[Spell] Eyes of the Beast - pet speed is incorrectly persistant

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#5088]
**Links:** https://www.wow-mania.com/armory/?spell=1002

**What is Happening:** 
1. If you cast [Eyes of the Beast](https://www.wow-mania.com/armory/?spell=1002), your pet will automatically be put on Passive, and will stay on Passive after the spell has ended, effectively forcing him into passive state every time you cast the spell. 

2. If you cast Eyes of the Beast, then go in the water and cancel the effect, your pet will remain at swim speed forever until he is either dismissed or Eyes of the Beast is used again. The pet doesn't know it ever got out of water and will just be super slow.

3. Somewhat related to 2, your pet gains the master's movement speed buffs while under the effect of Eyes of the Beast. For example, if the hunter uses [Aspect of the Cheeta](https://www.wow-mania.com/armory/?spell=5118)h or [Rocket Boots](https://www.wow-mania.com/armory/?item=41118), the pet gains the bonus if controlled through Eyes of the Beast, giving it a free movement boost. 

**What Should happen:**
1. When you cast Eyes of the Beast, your pet should remain on whatever "behavior" it was on before, and stay on it when the spell ends.

2. If you cancel Eyes of the Beast while your pet is in water, it should return to its normal speed once it exits water.

3. Movement speed buffs that only affect the hunter shouldn't transpose to the pet while it's under Eyes of the Beast's effect.

**Comment by Keader** [comment]
i cant reproduce bug 2.
bug 1 and 3 fixed.

**Comment by Oganku** [comment]
For 1 and 3, pet speed doesn't change with master speed anymore, but pet speed seems to be +100% or more constantly, making the pet constantly much faster when under eyes of the beast.

And for 2: https://imgur.com/a/Vwt95CE

**Comment by Keader** [comment]
@Oganku: "but pet speed seems to be +100% or more constantly", what?
I recorded it in ptr:
https://youtu.be/_lYhuyZkU1c

Speed is correct there.

**Comment by Keader** [comment]
about issue 2, i tested for hours, cant find the reason.
without debug modde, i cant do nothing on it.
