### ISSUE TITLE
[NPC] Sal'salabim - unable to be interacted with due to clipping through terrain

### ISSUE THREAD

**Issue by Trajectory77** [WoWManiaUK/Redemption#5089]
Hell Dev Team!
I am on a quest line that has me on https://www.wow-mania.com/armory/?quest=10004 where I am supposed to talk to https://www.wow-mania.com/armory/?npc=18584 and it will than initiate a fight. After looking for a bit as to where he should be I started the /Tar command and he is targetable however I can't select him to talk. I have a range finder addon as well which should show how far away he is and it shows no info (as compared to various ranges shown for other npcs). This NPC shold be able to be interacted with that ends in a fight.

A screenshot is attached as to where he should be, that he is targeted but no where to be found.

Thanks in advance.

![WoWScrnShot_103120_141815](https://user-images.githubusercontent.com/73453764/97794358-e5559d80-1bc6-11eb-8c10-0582d1012b92.jpg)

**Comment by Oganku** [comment]
He's back at his correct position right now. I suppose he probably fell through the ground or clipped in a wall and a GM respawned him for you. Hope you managed to continue the quest. Will confirm that his spawn position is fine on PTR, but he should be ok now. Thanks for the report though.

**Comment by Rushor** [comment]
i will adjust the spawn pos, so he should no longer clip trough the ground

**Comment by jeyrella** [comment]
When in combat he does clip through the floor and become untargetable at very specific points in that inn. (Much like the ogres did in the hills above Shattrath.  Seems there are some clipping issues with terrain maps in this area)

![image](https://user-images.githubusercontent.com/46089380/97800730-86783e80-1c2f-11eb-9a54-e390a98cced4.png)


I guess conceivably once in a while if a player fails the combat he could reset to be clipped inside the floor here?

Indeed @Rushor I think moving him slightly would stop this.  Maybe to the standard floor area (at the back of the rug) if you can fix the z-position?

While @Oganku while its correct for "cannot reproduce" the original issue, I'll mark this as improvement as I could make him untargetable in combat, and a tweak will help this.

**Comment by Trajectory77** [comment]
Thank you all for your attention to this. I was wondering when this should
be implemented, since I just checked and the issue is still present (no
rush or anything like that, just more so for ny own information so I dont
keep checking)?

Thanks again.

**Comment by Rushor** [comment]
position of him changed a bit now

**Comment by Trajectory77** [comment]
Okay. I just checked and seems to be the same situation of target able yet
not seen or intractable.

**Comment by Rushor** [comment]
no, the fix atm is on ptr only

**Comment by jeyrella** [comment]
Yep, that will make him lot less prone to bugging out.

![image](https://user-images.githubusercontent.com/46089380/97814816-daac0e80-1c81-11eb-9b49-f67803a01098.png)

Can still clip the steps and be unhittable if player deliberately paths him through the steps to the back, but thats easily avoidable, he doesn't reset.
Paths back to new place without issue if player dies.

**Comment by jeyrella** [comment]
@Trajectory77 we do all the changes on a seperate test realm, only once they are confirmed correct do we move those to the live server, once a week (usually tuesday or wednesdays).
