### ISSUE TITLE
[Quest] The Air Strikes Must Continue - Flight Path is too fast

### ISSUE THREAD

**Issue by Rushor** [WoWManiaUK/Redemption#5091]
https://wow-mania.com/armory/?quest=11533 

People on doing the quest are barerly able to complete it because the flightpath is too fast - the player is already flewn away and creatures are not fuly loaded - that makes the daily too difficult.

Fix:
Added the option to reduce the taxi flight path on that island by 20 percent. We can reduce it even more.

**Comment by Rushor** [comment]
try now pls

**Comment by jeyrella** [comment]
Thanks for this, this is so awkward as it is.  Glad we could find a fix.  I will test this.

**Comment by jeyrella** [comment]
Thank you, much MUCH more comparable to the original speed.
era-relevant original speed:  https://www.youtube.com/watch?v=_gTmZuI7xpc
as it is fixed:  https://youtu.be/fygHY5HlGow

Pretty much spot on now;  possible to complete in one run but still a challenge to do so.
