### ISSUE TITLE
[Quest] Leading The Ancestors Home - Borean Tundra - Elders should be nearer their named stones + Should be visible

### ISSUE THREAD

**Issue by vandamark** [WoWManiaUK/Redemption#5092]
https://www.wowhead.com/quest=11610/leading-the-ancestors-home

The 3 Elders in this quest should be near the rocks with their names in Coldrock Quarry, Borean Tundra. Only 2 of them, Kesuk is missing, are at their respective stones.

**Comment by Rushor** [comment]
Confirmed. The creature_template has modelid 25978, but in creature table it is overritten by 20559, which is invisible then

**Comment by Rushor** [comment]
try now https://i.imgur.com/UmuOSdG.jpeg

proof for issue: https://www.wowhead.com/npc=25397/elder-kesuk#screenshots:id=92300

**Comment by Oganku** [comment]
https://www.youtube.com/watch?v=oIMFG17qxH0
https://www.youtube.com/watch?v=aMGhoqjwwUk

From what I found, the elders should be invisible, and you just use the Tuskarr Ritual Object (34715) near their 3 stones, which causes the elders to appear and walk to it, before flying off. 2 videos above as proof, second one being from wotlk era.

Comparing 0:15 from the first video above to [this recording](https://imgur.com/a/6XFfCnL) from PTR we can see the discrepancy.

**Comment by Rushor** [comment]
Ah alright so the move Part is missing aswell

**Comment by Oganku** [comment]
They should be invisible to players at first, then the player uses the item near a stone, the walrus becomes visible, walks to the stone and flies away.

**Comment by Rushor** [comment]
move action added for all of them including the visible/invisible part

**Comment by Rushor** [comment]
the part where the transformed creature flies away is not display correctly at the moment can be ignored at the moment - will try to find a solution. it will not break the quest or the respawn or anything like that.

**Comment by Oganku** [comment]
Looks great
