### ISSUE TITLE
[Quest] Skywing pathing can clip terrain and become uncompletable - 10898 - Terrokar

### ISSUE THREAD

**Issue by Trajectory77** [WoWManiaUK/Redemption#5093]
https://www.wow-mania.com/armory/?quest=10898

Upon starting this quest, the npc https://www.wow-mania.com/armory/?npc=22424 Gives an emote and than does nothing. After waiting for several minutes, I initiate combat with a mob and than the npc begins to attack the mob that I am in a fight with. Once combat has ended, it has an erratic flight pattern, going the opposite direction and clipping the terrain. I try to follow it with a flying mount and eventually it just disappears. The quest is not performing in the manner in which it is supposed to and is not completable at this time.

![WoWScrnShot_110420_024748](https://user-images.githubusercontent.com/73453764/98090287-6fad3400-1e49-11eb-8376-6de8188afdca.jpg)
![WoWScrnShot_110420_024937](https://user-images.githubusercontent.com/73453764/98090292-720f8e00-1e49-11eb-8bd9-686b70d11722.jpg)

This is on the Naxxramas server.

**Comment by Rushor** [comment]
needs confirmation, then i can check

**Comment by Oganku** [comment]
Quest works fine, but I know from previous experience that sometimes the NPC will bug out and will need to be reset to work again. Might be when a player starts the quest and fails, or maybe if the NPC gets in combat. 

A while ago I had this happen and I just aggro'd mobs near Skywing to get him killed and have him respawn. After respawning the quest worked properly. I can't replicate the behavior break on PTR, but the quest works, and killing/respawning him doesn't affect his behavior either. Unrelated to the quest itself though.
@Rushor

**Comment by jeyrella** [comment]
Am in a quandary on how to mark this one.  I have the same experience as Oganku above; I've run this half a dozen times on PTR now, and I can find no way to replicate the OP's experience -  it completes as expected.

However like Oganku I do recall on Redemption a couple of times this odd behaviour.  Also note the OP has managed to capture pictures of Skywing doing very odd things with the pathing.

@Rushor relying on you for this one - can you find anything odd looking?

**Comment by jeyrella** [comment]
Hmm, I may have been able to replicate this.  

I deliberately failed and then abandoned the quest; now when I return to Skywing it no longer offers the quest.  If I add the quest manually, it sits there and does nothing.

I think we can mark this confirmed.

**Comment by Rushor** [comment]
try now pls

**Comment by jeyrella** [comment]
After completing, if abandoned then quest can be re-taken by Skywing stays still in starting place and does not move.

see here for what happens:  https://youtu.be/mKlvWsKSG4g?t=360

**Comment by Rushor** [comment]
not a regression

hm i see you used .respawn, can you try to restart the quest after the creature respawned manually? :o

**Comment by jeyrella** [comment]
Looks good:
Does not clip path if enters combat
Respawns & starts quest if previous player failed or abandoned
Does not clip or change path if previous player failed
Does not clip or change path if previous player completed
Respawns on completion
https://youtu.be/FtFUfK0SNK0
