### ISSUE TITLE
[Raid] Cannot re-enter Zul'Aman once started

### ISSUE THREAD

**Issue by cathyr1** [WoWManiaUK/Redemption#5094]
Entering this instance is broken again. When you go out to turn your quests and pick up the new ones you cannot return back in even if there is no bossfight. It says "Unable to zone while an encounter in progress".

There was such bug about half a year ago and got fixed. But its back now.

**Comment by wow-mania** [comment]
Do not leave in the middle of the instance run.

**Comment by Rushor** [comment]
If we find the reason i can fix it

**Comment by svijetlo** [comment]
after killing even one 1st mob 
if one die , can not back in 
if you lave to complete quest and grab new , can not get back in 
if for what ever reason you leave raid you can not get back in 
all the time you get msg 
Unable to zone in while an encounter is in progress.

**Comment by svijetlo** [comment]
could be smt connected to Harrison jones

**Comment by Rushor** [comment]
Soo which bosses are the reason for the Bug?
How is Harriron the reason? One you talked to him, the instance is bugged?

**Comment by svijetlo** [comment]
if harriosn is alive if you kill and take loot out of anything it wont let you go in , but on one try while one of my toons was out could not enter and other one was in harrison got killed by trash , then toon that was outside could again enter , thing is you can not enter even if harrison is not fighting anything , tho i say this is just my thinking i me not sure does he rly cos it or smt other but problem is there is you die or run out to do quest you wont eb able to be back in it will give you msg like boss fight is going on

**Comment by Rushor** [comment]
okay about which quest are we talking then actually? can you gimme the names and ids of the quest?

**Comment by svijetlo** [comment]
a person i talked to took all quests there in front ones he did those he went out give those in and took 2 form links 


http://www.wow-mania.com/armory?quest=11165   --  A Troll Among Trolls

http://www.wow-mania.com/armory?quest=11166  --  X Marks... Your Doom!

**Comment by Rushor** [comment]
try now pls, all bosses should handle their combat states correct now
