### ISSUE TITLE
[Dungeon/Boss] Pit of Saron (Forgemaster Garfrost adds)

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#5097]
**Links:** https://youtu.be/3AoXUWzieM0?t=15 at 0:15
https://www.wow-mania.com/armory/?npc=36907

**What is Happening:** The Wrathbone Siegesmiths in the boss arena do not engage when boss is aggro'd and can be ignored.

**What Should happen:** Aggroing a Wrathbone Siegesmith should aggro all of the others + Forgemaster Garfrost. Aggroing the boss should similarly aggro the entire room. They basically share engage/combat behavior.

**Comment by Keader** [comment]
I talk with janitor and he allow me fix this.
so fixed 👍

**Comment by Oganku** [comment]
Aggroing boss aggros adds, but aggroing an add doesn't aggro the boss.

**Comment by Keader** [comment]
@Oganku check discord chat pls

**Comment by Keader** [comment]
ok, fixed.
