### ISSUE TITLE
[Dungeon] Pit of Saron/Halls of Reflection bosses loot amount

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#5098]
**Links:** https://youtu.be/3AoXUWzieM0?t=137
https://youtu.be/ZLLmVdxM9WM?t=164

**What is Happening:** Forgemaster Garfrost and Krick & Ick currently both drop 2 items.

**What Should happen:** Forgemaster Garfrost and Krick & Ick should only drop 1 item.

**Affects both normal and heroic difficulties

**Comment by Rushor** [comment]
Will fix this

**Comment by jeyrella** [comment]
Is there any evidence for 1-2 drops vs exactly only 1 drop?  I could not confirm either way on a quick wowhead search.

**Comment by jeyrella** [comment]
In addition to OP's vid, https://youtu.be/ZLLmVdxM9WM?t=164, have found several others.  Definitely should only have 1 item drop.
https://youtu.be/J4CKJq_NAMM?t=224 
https://youtu.be/J4CKJq_NAMM?t=356

https://youtu.be/3AoXUWzieM0?t=124
https://youtu.be/3AoXUWzieM0?t=419

https://youtu.be/5E_E-w3KxxY?t=151

Note Tyrannus DOES drop 2 items, which is correct.

Same goes for HoR, both Falric and Marwyn are dropping 2 items.

What Should happen: Both Falric and Marwyn should only drop 1 item.

inks: https://youtu.be/KAipdzs8y6c?t=421
https://youtu.be/R9S5iuvr-bU?t=393


Have agreed with Janitor to re-open as it changes the balance of the instances

@Rushor To change:
- [ ] Krick
- [ ] Garfrost
- [ ] Falric
- [ ] Marwyn

**Comment by Rushor** [comment]
all fixed for nh and hc for the first bosses
