### ISSUE TITLE
[Dungeon/NPC] Geist Ambusher event missing in Pit of Saron

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#5099]
**Links:** https://youtu.be/3AoXUWzieM0?t=224
https://www.wow-mania.com/armory/?npc=36886

**What is Happening:** The Geist Ambushers in Pit of Saron are missing their triggering event that should make them attack the NPCs and the party afterwards.

**What Should happen:** Some slaves should be present between Ick & Krick and Forgemaster Garfrost, as seen in the video above. They should also play a small event where they get attacked by Geist Ambushers once the players get close to them.

**Comment by Greywolf59** [comment]
This is "won't fix" I assume? Just want to make sure, since I was about to make the same report.
