### ISSUE TITLE
[Dungeon/NPC] Forge of Souls Endevent

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#5100]
**Links:** https://youtu.be/-hYZQwyyBEo?t=295

**What Should happen:** https://youtu.be/-hYZQwyyBEo?t=295

In Forge os souls there should be a tiny outro event once the endboss was killed

**Comment by Rushor** [comment]
Will fix a different event instead, the other once i will do in future

https://youtu.be/-hYZQwyyBEo?t=295

In Forge os souls there should be a tiny outro event once the endboss was killed

**Comment by Rushor** [comment]
pathing end event added for all guards

**Comment by Oganku** [comment]
Event fixed for horde side, but Alliance mobs are still missing their pathing.

**Comment by Rushor** [comment]
should work for both versions now
