### ISSUE TITLE
[Dungeon] Pit of Saron ramp add packs can be skipped

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#5101]
**Links:** https://youtu.be/ZLLmVdxM9WM?t=283

**What is Happening:** The two add packs of 5 mobs on the ramp leading to the tunnel in Pit of Saron can be aggro'd partially right now. You can aggro only 2/5 of the mobs and pass without fighting the others. Also, you can currently aggro the Fallen Warriors separately from the Wrathbone Coldwraiths right behind.

**What Should happen:** The packs of 5 mobs should engage together as soon as one is aggro'd, as seen in the video above. Similarly, the two Wrathbone Coldwraiths futher up should aggro with the 4 Fallen Warriors in front of them and behave as a small pack.

**Comment by jeyrella** [comment]
Ahh good find Oganku, I was unable to find evidence of this to prove it.

**Comment by Rushor** [comment]
they should have an enganing summon event with waypoints aswell - just as note here

**Comment by jeyrella** [comment]
As we have a quiet week and this changes the nature of this whole section of the instance, let's take another look at this one

**Comment by svijetlo** [comment]
i think it is agro range on those mobs as you climb a bit of hill there so they can not see you as you Z axis is bigger could be that

**Comment by Oganku** [comment]
It's actually 1 vrykul summoner lady with 4 summoned zombies, they should aggro as a pack since technically they're her 'pets'. That's also why the zombies despawn so fast after they die, cause they're summoned units.

**Comment by Rushor** [comment]
the Ymirjar Deathbringer will now call for help and leads his adds to attack aswell
