### ISSUE TITLE
[Dungeon/Bosses] Halls of Reflection bosses loot amount

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#5103]
**Links:** https://youtu.be/KAipdzs8y6c?t=421
https://youtu.be/R9S5iuvr-bU?t=393

**What is Happening:** Both Falric and Marwyn are dropping 2 items.

**What Should happen:** Both Falric and Marwyn should only drop 1 item.

**Applies to both normal and heroic difficulties.

**Comment by Rushor** [comment]
Will fix this

**Comment by jeyrella** [comment]
Whilst agree with 1 being possible, is there any evidence for 1-2 drops vs exactly only 1 drop? I could not confirm either way on a quick wowhead search.

**Comment by Oganku** [comment]
Generally, bosses with 5 items in their loot tables only drop 1 item.

**Comment by wow-mania** [comment]
No official info added.
