### ISSUE TITLE
[Dungeon/Boss] Halls of Reflection Lich King escape

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#5104]
**Links:** https://www.wow-mania.com/armory/?spell=69409
https://www.wowhead.com/npc=36954/the-lich-king#abilities;mode:normal

**What is Happening:** The Lich King chasing the party will not use Soul Reaper if someone gets in melee range.

**What Should happen:** The Lich King should use [Soul Reaper](https://www.wow-mania.com/armory/?spell=69409) on melee targets if given the chance.
![image](https://user-images.githubusercontent.com/34783736/98421363-2fbb9c00-2057-11eb-90a8-b660b36e653d.png)

**Comment by Keader** [comment]
try now pls

**Comment by Oganku** [comment]
Still no Soul Reaper

**Comment by Keader** [comment]
try now pls.
i forgot to make event repeat lul

**Comment by Keader** [comment]
@Oganku fixed the icewall issue 👍
