### ISSUE TITLE
RHC queue buged

### ISSUE THREAD

**Issue by Loktard** [WoWManiaUK/Redemption#5105]
I queued in RHC with no Dungeon ID's and it shows me 1 DPS missing. Meanwhile in World others are looking for a tank. I make a party with 1 DPS and queue up it show's healer missing but i have a confirmed healern in queue. i fill my Party with a healer and 1 dps it shows 1 DPS missing. If fill the party with 5 and RHC is popping.

**Comment by jeyrella** [comment]
Not a game code issue.
