### ISSUE TITLE
[Spells] Misses don't aggro enemies

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#5108]
**Links:** https://github.com/TrinityCore/TrinityCore/issues/23804

**What is Happening:** Ranged spells/attacks can be used against enemy targets, and will not pull aggro if they miss.
Proof: https://imgur.com/a/1eOZatn

**What Should happen:** Attacking an enemy should always cause them to attack back, regardless of if the spell/shot missed.

**Comment by Rushor** [comment]
I can apply that of you wish, i need 5 tickets

**Comment by Keader** [comment]
go for it

**Comment by Rushor** [comment]
merged, ready once ptr is up

**Comment by Oganku** [comment]
Still same behavior: misses don't pull aggro (spells and white dmg)

**Comment by Rushor** [comment]
Try again now

**Comment by Oganku** [comment]
Negative, still not pulling aggro.

**Comment by Rushor** [comment]
hmm i only applied the fix from tc. is it an improvement to the previous state @Oganku ?

**Comment by Oganku** [comment]
Nothing noticeable, no. 😕

**Comment by Rushor** [comment]
hmm wel that commit changed, that spell like fireball will add aggro even if they miss, hunter shoot spells are not a type of those spells

affected spells are more likely such:

Fireball (3140) - no aggro
Corruption ( 172)- no aggro
Shadow Word Pain (589) - no aggro
Curse of Agony (980) - no aggro
Devouring Plague (2944) - no aggro
Drain Life (689) - no aggro
Drain Mana (5138) - no aggro
Immolate (348) - no aggro
Moonfire (8921) - no aggro
Serpent Sting (49001) - no aggro
Flame Shock (8050) - no aggro

Mind Blast (8092) - aggro
Smite (585) - aggro
Shadow Bolt (686) - aggro
Wrath (5176) - aggro
Lightning Bolt (403) - aggro

can you test if it works for those?

**Comment by Oganku** [comment]
I did test with corruption and smite (one from each batch), but I'll check again in a bit

**Comment by Oganku** [comment]
Tested with all spells linked above (same ID) + ranged Shoot, and none pull aggro when they miss.

**Comment by Rushor** [comment]
this is strange because the fix is exaactly applied from tc

**Comment by Rushor** [comment]
added a attackstart call - pls try now (and test if it does not break other behaviour for infight spells

**Comment by Oganku** [comment]
Now it aggros, but it will do a small aggro midfight also, even if you have low threat. Should revert that last thing xD

**Comment by Rushor** [comment]
Oh alright

**Comment by Rushor** [comment]
okay last one removed

**Comment by wow-mania** [comment]
Give it a try @keader

**Comment by Keader** [comment]
try now @Oganku pls
