### ISSUE TITLE
Afflliction Lock with Numbers

### ISSUE THREAD

**Issue by theonykry** [WoWManiaUK/Redemption#5110]
**Links:**

**What is Happening:**
I am by for not the best caster player, but i know way way around WoW in general and call myself a decent good player. i lately expierienced a drop in the dmg of affliction warlocks. i will assist you with some numbers.
WL lvl 80 Name: Kryosa. 1246 Haste 3300 spelldmg bonus, 31.05% crit (hitcapped ofc, numbers are selfbuffed, Fel armor/spellstone)
N= nocrit C =crit, SB= shadowbolt, Cor = corruption CoA = curse of agony H = haunt UA = unstable affliction T = ticks 
avg =avarage DMG, OD = overall dmg 
All data recorded without a pet and tested on Dummy, all procs immidietly removed too, so this is base dmg (gear stats + talents)
Corruption T=6 in 12s
N 3 avg 1524 / N 4 1524-1693 / N5 1524-1693 
C 3 avg 3537 / C 2 2830-3537 / C1 3537
OD 15352       OD 12960      OD 11664
With Haunt
N3 avg 2175    / N2 1959-2176 / N5 1517-2176
C3 3519-4546 / C4 3519-4546 / C1 4546
OD 19139       / OD 20838         / OD 14115
I had the cases where haunt flew back (projectile) and dispelled CoA, Cor and UA, right when i reapplied it. this might be a diffrent bu, but maybe there is a connection.
UA T=5 
N5 avg 1320   / N4 8038 / N2 --
C0                  / C1 2758 / C3 2483-2758
OD 6468        OD 10888   OD 10639
With Haunt
N3 1534 - 1704 / N2 1521-1771 / N4 1831-2034
C2 Avg 3560     / C3 3532 -3699 / C1 4058
OD 12062         OD 14055            OD 11807
CoA T = 12
N 431-734  OD 7448
N 431-734 OD 7468
N 431-734 OD 7268
With Haunt
OD 9366
OD 9746
OD 9693
those numbers represent only the spell-dmg i was able to test. i hope they help.
Now i did 2 Full rotations (count till 30 SB as measurement) inculding trinketprocs (phyla and toc haste trinket) and devious Minds and also shadow's embrace/ eradication from the talents, cloak enchantment as tailor profession and the Icc ring proc, but still without the pet. (100% uptime of haunt too). Opener: Haunt UA Cor CoA SB SB SB... here are my numbers:
SB: 207K  dmg  (40%)    count:30 N=20 3628-6431 / C=10 9909-14103
Cor 174K dmg (33.7%)  T=42, N=22 1744-3594 / C=20 3609-6728
UA  76K  dmg (14.7%)   T=25, N=11 1360-2459 / C=14, 3106-5137
CoA 34K dmg (6.6%)     T=36, 719-1205
Haunt 5%dmg N=5 2682-3655, C=2 4968-5584
second rotation:
SB 206k 39.6% Count 30 N=23 4056-7109 C=7 10363-14731
Cor 172k 34.3% T=42 N=23 2286-3758 C=19 4776-7029
UA 75k 15% T=25  N=15 1476-2707 C=10 3453-5655
CoA 6.9% T=36 608-1215
Haunt count: 7 N=2435-4030 C=4823-5689

i hope those number help. 

**What Should happen:**

**Comment by Oganku** [comment]
I'd like to help, but I have no idea what issue you are reporting. What spell is doing too low damage? What part of the numbers corresponds to evidence for it?

I ran through all affliction spells/talents not too long ago and all numbers were fine. If you specify what spell you think is acting up, I can check, but right now I'm kinda lost. 😕

**Comment by wow-mania** [comment]
There is no mention of what it should be backed up with official info.
Please come up with clear instructions on how to reproduce and how what we get here differs from the official description.
We cannot base ourself on hunches or feeling.

**Comment by theonykry** [comment]
well i know there is RNG always on procs, but i havent found the issue yet so far. its not just a hunch. I know other Aflli locks with the same problem. GM Brontes also i aware of it. I am not a tester myself so i cant really look further into it. i am going to gather more data, but all i can do is raid and give you numbers. unfortunatly i dont have records of how it was before so i cant give you guys Numbers to compare with.

**Comment by Oganku** [comment]
I need to at least know what spell(s) to look at, cause it's extremely unlikely it's affecting all spells (if there is an issue at all). 

A few months ago, warlock damage was very inflated due to an issue with spells double dipping in damage increase talents, and after the fix all numbers seemed accurate. 

It can be very difficult to find an issue with so little information. Saying "damage is too low" is way too vague to know where to look. 

If you provide info on what spell does consistently lower damage than expected, then I'll have a start point.

**Comment by jeyrella** [comment]
Kry, as @Oganku says this is far too vague to be useful as a report.  The numbers you posted check out.  We've had several locks testing and can't find any issue.  We have other locks saying they're doing exactly the same as last week and nothing's changed.

There's far too many interactions with spells in raids to go testing everything.  It's impossible to take this further without you giving us more of a clue.

**Comment by theonykry** [comment]
i will do more investigations, just keep the threat open. i will update when i have time. maybe other warlocks can supply information too
