### ISSUE TITLE
[Spell] Improved Tracking only giving damage bonus for currently tracked type

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#5111]
**Links:** https://www.wow-mania.com/armory/?spell=52788
https://wowwiki.fandom.com/wiki/Improved_Tracking
https://www.mmo-champion.com/threads/645577-improved-tracking
https://www.curseforge.com/wow/addons/smarttrack comments even

**What is Happening:** You need to track the specific mob type you're attacking in order to get the damage bonus.

**What Should happen:** 

> Note that you _do not_ have to change the tracking mode according to your target to get the bonus -- you have to have **one** of the tracking modes on.

> Useless. Improved Tracking talent does not limit bonuses to what you are tracking.
If, for example, you are tracking Beasts, you gain the bonus to EVERY target type in the talent. Not just Beasts.

**Comment by Keader** [comment]
i realy think that its wrong.
has macros used by hunters in retail to change to correct type...

**Comment by Oganku** [comment]
On macro threads and addons pages I found comments saying they're useless and only useful if you forget to remove track herbs or something.

**Comment by Keader** [comment]
dont make any sense, but... i can fix it.
if is the correct behavior.
i will wait more info

**Comment by Oganku** [comment]
Yeah wait until confirmation, I will research more. 👍

**Comment by jeyrella** [comment]
well we changed this in #4111, for reference

**Comment by Oganku** [comment]
Interesting

**Comment by Oganku** [comment]
![image](https://user-images.githubusercontent.com/34783736/98739882-25abdd00-2378-11eb-96b3-8fb93b04e3a8.png)
From elitistjerks guide: https://web.archive.org/web/20140511202731/http://forums.elitistjerks.com/topic/97220-the-mm-hunter-in-33/

https://www.mmo-champion.com/threads/645577-improved-tracking Pretty much in its entirety.

![image](https://user-images.githubusercontent.com/34783736/98740086-7ae7ee80-2378-11eb-8946-6276dbe19fed.png)
From: https://www.wowace.com/projects/track-o-matique
Since the talent was removed in cata, it's fair to understand the behavior remained until then.

![image](https://user-images.githubusercontent.com/34783736/98740126-8b986480-2378-11eb-9ccd-c8712c65cbba.png)
From: https://wowwiki.fandom.com/wiki/Improved_Tracking

Can fairly confidently confirm it's wrong on live. @Keader

**Comment by svijetlo** [comment]
as far i know as long you "track" any sort of enemy bonus form improved tracking should apply to all , it was goal to make things more simple easy for ppl in wotlk and spcly in later expansions

**Comment by GMMetaxa** [comment]
![image](https://user-images.githubusercontent.com/34750502/98979911-3b5a0780-251c-11eb-8ea4-d95f12e307a2.png)
Invalid.

**Comment by jeyrella** [comment]
Re-opened after discussion on discord

**Comment by Keader** [comment]
fixed
