### ISSUE TITLE
[Raid/Event] Sunwell Plateau Brutallus pre-encounter event missing

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#5113]
**Links:** https://www.youtube.com/watch?v=8thfmeQ5ICw

**What is Happening:** Currently some of the animations are playing, and Brutallus uses his lines, but Madrigosa is laying on the ground the entire time and thus it appears as though Brutallus gets frozen and lifted in the air by nothing. Also, no ice wall prevents players from entering the arena before the boss becomes attackable.

**What Should happen:** Madrigosa's part of the ''cutscene'' is missing, as she just lays there. There should also be an ice wall blocking players from dropping below until the boss engages. (See above video)

**Comment by Rushor** [comment]
intro event added. it will add be started once the player walked over the trigger:

.go trigger 4853

the the whole event will trigger https://i.imgur.com/9TamEmX.jpeg https://i.imgur.com/VwQc83s.jpg

Note: Felmyst will now spawn 60 seconds after the death of brutallus https://i.imgur.com/GQ0XxjW.jpeg

The icewall will be disabled for now, to prevent some bad complications after wipe

**Comment by Oganku** [comment]
Looks great ^^
