### ISSUE TITLE
[Item] Soul Fragment (Shadowmourne proc) and Paladin seals

### ISSUE THREAD

**Issue by Kilju** [WoWManiaUK/Redemption#5114]
**Links:**
http://www.wow-mania.com/armory?spell=71905 Soul Fragment
https://wow-mania.com/armory/?spell=31801 Seal of Vengeance
https://wow-mania.com/armory/?spell=20375 Seal of Command
https://wow-mania.com/armory/?spell=21084 Seal of Righteousness

**What is Happening:**
Only seal of command is proccing shadowmourne stacks, all of the seals should stack it each time they deal damage (Vengeance after 5 stacks)

**What Should happen:**
Each time you hit with a melee attack, you should get 1 shadowmourne stack. This is working correctly.
Seals should also proc it everytime they do damage from melee attack. (NOT vengeance dot for clarity as its not melee attack)
So attacking 1 person with Righteousness up should amount to 2 stacks each time.
Doing Divine Storm on 2 targets should give you 3 stacks as you are hitting 2 person with melee attack and 1 with your seal.
Seal of Vengeance should also proc them after the seal has reached 5 stacks.

Some information that I managed to find to show how it worked back in retail and information from several non-blizzard websites. 
The quality is very bad in the video but hopefully you have the patience. Sadly I didnt not manage to find another video from this era that would be retail 100%.
https://www.youtube.com/watch?v=tUL6GVDingQ (Play at 0.25 speed to see them stacking up from sor, hard with the quality and jumpcuts)
https://www.wowhead.com/spell=73422/chaos-bane#comments Comment stating the intended behavior, time of write it was 5.2 patch.
http://web-old.archive.org/web/20100401105230/http://elitistjerks.com/f76/t52371-rawr_retribution_model/p26 (Poster Glutton shared combat log, for clarity the third proc is from chaos bane but it is cancelled so fast that it manages to proc Soul Fragment aka 1 from melee, 1 from seal, 1 from proc because addon cancels it instantly)
https://www.mmo-champion.com/threads/733443-Shadowmourne-and-me?highlight=shadowmourne Talk about the addons ret use to cancel it without player interaction.  Quoted below.

"the reason that you remove the chaos bane buff is because we stack the 30 STR stacks so fast that we proc the damage in 4 seconds or so. this means that having 2K damage every 4 seconds and an average of 135 STR is better than 2K damage every 14 seconds, 135 STR for 4 seconds and 270 STR for 10 seconds. " The poster is not official but still talk from 2010. Using seal of command (it is working how intended) results in about 4 seconds to stack it up to 10 on wow-mania.

For warriors it should also proc from sunder armour and other similar skills. Don't have warrior to test it.
didn't find the website again fast as I was mainly looking at the seals.

edit: Also equipping shadowmourne causes you to have internal CD for 30 seconds before you can get the buffs. Not saying incorrect or correct but something to look into perhaps.

**Comment by Oganku** [comment]
Works with seal of corruption on live and other seals should proc it as well, as mentioned in evidence from retail. The video is kinda hard to decipher, but it did seem like he was very often getting multiples of 2 soul fragments for singular hits (hit + seal). Elitistjerk post is the most interesting probably

**Comment by bLeyaa** [comment]
> Each time you hit with a melee attack, you should get 1 shadowmourne stack. This is working correctly.
Seals should also proc it everytime they do damage from melee attack. (NOT vengeance dot for clarity as its not melee attack)
So attacking 1 person with Righteousness up should amount to 2 stacks each time.
Doing Divine Storm on 2 targets should give you 3 stacks as you are hitting 2 person with melee attack and 1 with your seal.
Seal of Vengeance should also proc them after the seal has reached 5 stacks.

Not sure if you worded it bad or it was intended, but proc is only a chance on hit. It's not guaranteed. Meaning that when you hit someone with Righteousness up it won't be 2 stacks _**each time**_. It can be two, or one, or none at all depending on RNG. So really, it's only about checking if the abilities mentioned in the post are able of providing the fragment (seals, sunder armor etc)

Shadowmourne should not have an ICD, as seen: https://youtu.be/rNVoMGRg4QE?t=200 (he goes from 1h+shield to SM and gets an instant fragment)

**Comment by Kilju** [comment]
Yes the intention behind this github post was to make sure those abilities are able to proc it as intended, Nothing to increase or decrease % the chance to proc. But good that you pointed it out to eliminate the misunderstanding.

**Comment by svijetlo** [comment]
yap weapons should not have icd on equip as in WOTLK and earlier expansions weapon swap for buff was common thing ppl did , same as librams on paladin i swap them all the time

**Comment by Keader** [comment]
Tested and seals already proc it... but like people said, is chance.
Fixed the icd on equip issue.

**Comment by Kilju** [comment]
Something else must have been changed on test then. I'm not getting those results on live.
Tests were 1min 30s pure auto attack. I was late cancelling chaos bane for 1 attack for 1 video, for results it does not matter.
in 1min 30s. Chaos Bane procced 4 times each test. Fragments varied. You can find recount at the end of the clips.

https://www.youtube.com/watch?v=FsvUgK3eZ2I&feature=youtu.be No seal
https://www.youtube.com/watch?v=-pgp0uyD05Q&feature=youtu.be Seal of Righteousness
https://www.youtube.com/watch?v=WKkE3yNK0RY&feature=youtu.be Seal of Vengeance

Heres SS of recounts:
[Seal of Righteousness](https://i.ibb.co/8dH8tZY/SoR.png)
[Seal of Vengeance](https://i.ibb.co/kq8vGks/SoV.png)
[No seal](https://i.ibb.co/HYXWrxp/No-seal.png)

**Comment by Keader** [comment]
Seal of Vengeance per Seal of Vengeance will not proc it, because it has a DOT effect and only direct damages can make it procs.
But judgement of vengeance (judgement with seal of vengeance) can proc it.
Seal of Righteousness and Seal of Command has direct damage, so both can proc it.
Seal of Vengeance direct damage (after stacks) can proc it too.
Just tested adding comment in script, to check who is exactly proccing it in PTR.

**Comment by Kilju** [comment]
Yes I agree on all those points. Vengeance after 5 stacks. like my original post, DOT does not stack it.

**Comment by Oganku** [comment]
Fixed for Seal of Corruption/Vengeance, Seal of Righteousness and also Manifest Anger (Tiny abom proc).

**Comment by Keader** [comment]
Me and Oganku tested the seal stuff.
now is working correctly xD
