### ISSUE TITLE
[Raid] Felmyst air phase issues (Sunwell Plateau)

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#5115]
**Links:** https://youtu.be/pcv5LlawB1A?t=811

**What is Happening:** 
1. Felmyst is far too slow during her "drive-bys" during her air phase. She pathetically moves across the arena, as seen from this clip from PTR: https://imgur.com/a/qt6pNry
However, [this video](https://youtu.be/pcv5LlawB1A?t=811) from retail shows at 13:30 that the 2 drive-bys per air phase are rather fast and dangerous.

2. Felmyst ends her second drive-by behind a very inconveniently placed wall, and then will "focus" on a raid member and dive to them in a straight line to land. Depending on the target's position in the arena, Felmyst can quite easily get stuck behind/in that wall and soft-lock the raid, as she will never land. Position of the wall: https://imgur.com/a/mz02D3I

**What Should happen:**
1. Felmyst should be significantly faster during the 2 drive-bys where she uses Demonic Vapors.

2. That section of the wall is purely decorative as there is nothing on the opposite side, so its collision could probably be removed to avoid soft-locks of the raid. Open to any other suggestions!

**Comment by Rushor** [comment]
felmyst will fly faster now and will no longer be stuck behind some strange walls

**Comment by Oganku** [comment]
Flight behavior is much improved, but her second air phase attack (Fog of Corruption) breath is currently only visual. The Fog that is left behind and should mind control players is missing. Visuals of the fog were present before (but the MC was missing), and now neither the fog nor the spell effect are present.

https://www.wow-mania.com/armory/?search=fog+of+corruption
https://www.wow-mania.com/armory/?spell=45782 ?

> Fog of Corruption - Area-of-Effect spell. Mind controls players inside it for duration of the battle. Big coverage and can cover a random 1/3 of the area. Characters afflicted by this debuff should be killed as quickly as possible because it also increases run speed, damage and healing. Once everyone is dead or mind-controlled Felmyst will temporarily despawn, and everyone mind-controlled will be killed instantly, so that the encounter can be reset. If a wipe is called during the air phase then you can deliberately enter the cloud so as to avoid repair costs from dying.

**Comment by Rushor** [comment]
Okay checking

**Comment by Rushor** [comment]
fixed https://i.imgur.com/KO9YhXa.jpg
