### ISSUE TITLE
[NPC] Anveena event script incorrect - Sunwell Plateau

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#5116]
**Links:** https://www.wow-mania.com/armory/?npc=26046
https://youtu.be/J_HyiKQKNJs?t=690

**What is Happening:** Aveena appears during the last phase of the Kil'Jaeden fight and says some dialogue before sacrificing herself to weaken KJ. However, she currently spawns at ground level (kinda inside KJ) and does not disappear after her sacrifice. 

After KJ dies, she kinda stays there T-posing in her bubble, untargetable, on top of KJ's body, which is very odd.

**What Should happen:** As seen in [this video](https://youtu.be/J_HyiKQKNJs?t=690) around 11:29, Anveena should float above KJ during her interaction with Kalecgos, and should disappear after her sacrifice.

**Comment by Rushor** [comment]
should fly now
should despawn 3 seconds after cast of SPELL_SACRIFICE_OF_ANVEENA

**Comment by Oganku** [comment]
- [x] She flies and properly disappears after her sacrifice

- [ ] She flies too high (twice as high as she should approx.)

**Comment by Rushor** [comment]
spawn high reduced by half

**Comment by Oganku** [comment]
Perfect now
