### ISSUE TITLE
[NPC]s [Mechanic] enemy NPC's pets aggro range

### ISSUE THREAD

**Issue by Greywolf59** [WoWManiaUK/Redemption#5117]
**Links:**

**What is Happening:**
I am sorry but I am not sure what links to post, because there would be many. Nor can I really find them. The following stands for Naxxramas realm, but I guess for Redemption too.
Enemy NPC's pets aggro the player from crazy long distance, even much higher level then they are themselves. By these pets I mesn pets like murloc hunter's pets from Westfall, warlock demons like those of bloodsail warlock's in STV or necromancer's skeletons in Stratholme, demons in Dire Maul etc. I can't say with certainty it happens with every NPC pet, but it most likely does.
**What Should happen:**
The NPC's pets most likely should notbe so aggressive, with such a long aggro range. They aggro you from much longer distance than their masters.

**Comment by Oganku** [comment]
I have seen it happen with minions/pets from NPCs. It is not happening with every pet, but happens with quite a lot of them.

**Comment by Rushor** [comment]
can you give examples where it works and where it does not work :)

**Comment by Greywolf59** [comment]
I will add more when I meet them again. What I met today...
Working: Tanaris - Voidwalker Minion
Bugged: Silithus - Earth Elemental (Twilight Stonecaller https://www.wow-mania.com/armory/?npc=11882 )

**Comment by Keader** [comment]
Try now.
Those pets will follow targets until 80~90y of distance of owner, instead of follow players until 533 yards of distance of owner.

**Comment by Greywolf59** [comment]
And the aggro range at which they start to attack?

**Comment by Keader** [comment]
follow same behavior of pets...

**Comment by Greywolf59** [comment]
Well it stayed the same. I am at stratholme atm so I can't test how for they follow me ofc. But the range from which they engage is still too big. I have deleted cache but  I still can try again after using launcher

**Comment by Keader** [comment]
it's fixed on PTR, not in live server.
Agro Range for all pets is 45y radius

**Comment by Greywolf59** [comment]
Oh okay :)

**Comment by Keader** [comment]
i will take a little look on it later...
i think we can reduce it a little bit.

**Comment by Keader** [comment]
they're selecting targets in 20 yards... so is correct

**Comment by Oganku** [comment]
It feels kinda weird. The 20 yards is what I'm experiencing, but I feel like it should scale with level like all other mobs. For example, a level 80 barely aggros the murlocs in Westfall even when standing on top of them, but their pet crabs will aggro from afar as if I was level 10. And even still, 20 feels large even for same-level character. If same aggros behavior (level based) can be implemented to pets, it would be ideal. It still feels wrong and problematic.

**Comment by Keader** [comment]
ok, now pet players will have same behavior as before.
but pet controlled by creatures will have 15y agro radius and will take account level difference and stuffs.

**Comment by Oganku** [comment]
Still aggroing level 15 murloc crabs from 20 yards away on a level 80. :/

**Comment by Keader** [comment]
I Will not spend more time on It.
Code is correct, nothing more that i can do

**Comment by Oganku** [comment]
Should not be much of a problem for a character around the level of the pets, aggro range feels decent for that.
