### ISSUE TITLE
[NPC] Ramstein the Gorger loot table seems incorrect - Statholme

### ISSUE THREAD

**Issue by Greywolf59** [WoWManiaUK/Redemption#5118]
**Links:**
Ramstein the Gorger https://www.wow-mania.com/armory/?npc=10439
Gauntlets of Valor https://www.wow-mania.com/armory/?npc=10439
**What is Happening:**
Please. I would like to ask of you to check the drop rate of the Gauntlets of Valor. I would not make this thread normally but:
1: wow-mania armory says the drop chance is 12% and I killed Ramstein over 30 times without it dropping.
2: It is only one rare item on drop table given by armory with given drop chance. 
The rest of the rare loot that can drop instead of the gauntlets have given drop chance of 0% on the armory, yet they definitely drop on each kill (one of them). These percentages and drops look peculiar since only one of the rare drops have given any real drop chsnce and it seems that this item only is not dropping. Kills were done on Naxxramas realm. It is worth mentioning because it is part id the warrior t1.5 quest chain.
**What Should happen:**
I think that there is a fair chance for the gauntlets to drop at least once in more than 30 kills. Please, I would just be happy if someone could recheck there is no issue with it. If ramstein's loot table on armory would look normally (no 0% items that actually drop) I would not make this post ofc. Thank you.

**Comment by jeyrella** [comment]
Armory loot table looks odd compared to retail drop loot https://wow.gamepedia.com/Ramstein_the_Gorger?oldid=2367748
Will check actual boss drops

**Comment by jeyrella** [comment]
This is definitely not a problem with the creature itself, nor with the drop rate of the gloves. 
![image](https://user-images.githubusercontent.com/46089380/98990576-88d97300-2522-11eb-8d8a-2fb2c84e7013.png)

Where I think possible confusion lies is that the drop rates stated in the armory are not correct - it is not 0% chance for these
![image](https://user-images.githubusercontent.com/46089380/98990682-b0c8d680-2522-11eb-80af-7dde3c88187b.png)
I think this may be simply a case of armory needing synch with database.  Will check with devs.

**Comment by Greywolf59** [comment]
Yeah, the armory site made me to do this topic mainly. And the fact of it not dropping for more than 30 kills did not help either (stopped playing vanilla Naxx because of these lol) :/. Thanks a lot and sorry for adding you more work.

**Comment by Rushor** [comment]
loot table adjusted, it should be dispayed now once armory and db was updated

**Comment by Oganku** [comment]
The item shows 12% in DB, other blues it drops still weirdly show 0%, but the gloves are fine. I guess that's only visual and not a big deal.
