### ISSUE TITLE
[Quest] Chicken Party - freanzyheart tribe rep

### ISSUE THREAD

**Issue by svijetlo** [WoWManiaUK/Redemption#5120]
**Links:**
https://www.youtube.com/watch?v=ZzAKQWqk2WU&ab_channel=GameGuidesChannel
http://www.wow-mania.com/armory?quest=12702
**What is Happening:**
Ones you take quest , all chicken stand on one spot close to quest giver and all you need to do is right click them you can do it even while mounted , no need to use net http://www.wow-mania.com/armory?item=38689 or what so ever  making this quest 12 sec job , Ss show it 
![WoWScrnShot_111220_115859](https://user-images.githubusercontent.com/61908373/98941172-73495680-24ec-11eb-8a44-3a689960d6af.jpg)

**What Should happen:**
Ones you take quest chicken should run all over and bit around camp, if you get to close they run away, you must use net on them only then you come come close and right click them to pick them up 
all can be seen in vido linked above 
NOTE; vid is form 2016 but quest it self did not change since it was 1st introduced to game

**Comment by jeyrella** [comment]
Confirmed, this has rather easier behaviour than intended.  Very hard to find orginal wotlk-era vidoes but svijet's assertion this was not changed seems correct

**Comment by Rushor** [comment]
issue is that the chicken loose their "fear" aura after some time and do not run anymore.

it should work now

**Comment by Oganku** [comment]
Chickens don't specifically run away from you, but they do run amock very erratically.
