### ISSUE TITLE
Argent Gruntling

### ISSUE THREAD

**Issue by krookizh** [WoWManiaUK/Redemption#5121]
**Links:**
![WoWScrnShot_111220_221814](https://user-images.githubusercontent.com/74381972/98997730-42414400-2535-11eb-8639-f8d21d76b041.jpg)

**What is Happening:**
My argent gruntling isn't working as it should. I can't click on it to buy any reagents or sell anything. his face is also not showing correctly, maybe this has something to do with the bug

**What Should happen:**
His face should show correctly, (worked last time with my addons) and i should also be able to buy reagents and sell things from him. It seems this is only a bug known to me, and i have also updated to the latest launcher

**Comment by jeyrella** [comment]
Have you got the upgraded Gruntling?  It can only act as a vendor if you have purchased the Argent Pony Bridle.
As for the model, delete your cache, disable your addons, and see if it works.

Both of these seem fine in PTR.

**Comment by Rushor** [comment]
works for me aswell, you need the fitting upgrades
