### ISSUE TITLE
[NPC] Warsong Champion Wintergrasp spawn below ground

### ISSUE THREAD

**Issue by gh0ster** [WoWManiaUK/Redemption#5122]
**What is Happening:**
There is one Warsong Champion at co-ords +-x50 y60 (from carbonite) who consistently spawns below ground. it can be attacked and killed, but respawns (or falls) below ground again.

**What Should happen:**
He should be above ground.

Wowhead co-ords show slightly different than my carbonite  (49.6, 51.8) but it is just over the south end of the bridge.

**Comment by Rushor** [comment]
can you upload a screenshot of it aswell pls :)

**Comment by jeyrella** [comment]
![image](https://user-images.githubusercontent.com/46089380/99072405-dea62d80-25ab-11eb-99b7-fea0db367e1a.png)
![image](https://user-images.githubusercontent.com/46089380/99072433-ed8ce000-25ab-11eb-8045-52cb2432e95c.png)
I think a companion 2nd champion should also spawn on this side
![image](https://user-images.githubusercontent.com/46089380/99072806-a4895b80-25ac-11eb-88b1-dd138033bf13.png)

Note also that when Horde control WG, a Valiance Expedition Champion should spawn here, and it does not.
![image](https://user-images.githubusercontent.com/46089380/99072995-f9c56d00-25ac-11eb-95c4-e46ee4fb8c6d.png)

**Comment by Rushor** [comment]
true there was one totally wrong spawn in 390.7810000f, 2840.560000f, 389.609000f

added the spawn to the position of the last sceenshot. The first spawm position is changed aswell.

Fixed those 2 cases

"Note also that when Horde control WG, a Valiance Expedition Champion should spawn here, and it does not."

cannot be changed for now

**Comment by Echinaceax** [comment]
> "Note also that when Horde control WG, a Valiance Expedition Champion should spawn here, and it does not."

Npcs spawn correctly since fix from another report, so all good now
