### ISSUE TITLE
Rhc Mp bug

### ISSUE THREAD

**Issue by Abyzou** [WoWManiaUK/Redemption#5123]
**Links:** https://ctrlv.sk/Y1Y4

**What is Happening:** for finish rhc i get only one Maniac points not 2  its buged

**What Should happen:** after finishing rhc as a reward i got only one MP not two

**Comment by Oganku** [comment]
First rhc of the day is 2 frosties and 1 mp. Every subsequent one is 2 eot and 2 mp. So if it was your first one of the day, it's normal.

**Comment by Abyzou** [comment]
oh really? ty so much for help its new info for me. you can close ticket.
