### ISSUE TITLE
[Spell/ICC] Professor Putricide Tear Gas vs Invisibility/Vanish

### ISSUE THREAD

**Issue by Keader** [WoWManiaUK/Redemption#5127]
**What is Happening:**

 In 10 normal and 25 normal, when change phase, Professor Putricide cast Tear Gas, stunning all players.
Has a mechanic that allow Mages and Rogues skip this stun and allow they continue attacking while the rest of raid get stun.

If Rogue uses Vanish or Mage uses Vanish/Invisibility, Tear Gas should not hit the caster.

Rogue Proof:
https://youtu.be/m7-3x8P_-wQ?t=80
and again in:
https://youtu.be/m7-3x8P_-wQ?t=344

Note that in both cases, all players get stun, but rogues can still attack the boss.

Mages Proof:

https://youtu.be/nfgc3Z1RmWM?t=106

**What Should happen:**

Rogues with Vanish and Mage with Invisibility should skip Tear Gas stun.

**Comment by wow-mania** [comment]
Please revert.
