### ISSUE TITLE
Improved Hunter's Mark

### ISSUE THREAD

**Issue by Sammasterthemad** [WoWManiaUK/Redemption#5128]
Improved Hunter's Mark with glyph of Hunter's Mark should be 750 on target which is what it show on toolbar, But when mouseover the debuff on target it only reads 500.

Normally no a big deal but when group with another hunter without the increased AP on mark leads to confusion if there is only 
![WoWScrnShot_111620_165336](https://user-images.githubusercontent.com/59262214/99317897-61d5b680-282c-11eb-8ef0-d2c8a21759a1.jpg)
![WoWScrnShot_111620_165358](https://user-images.githubusercontent.com/59262214/99317944-75811d00-282c-11eb-9391-b046fa8e2793.jpg)

**Comment by Oganku** [comment]
Tooltips are always really inconsistent in this game. Usually buffs/spells improved with talents will show the effect on _your_ tooltip, but not on the actual buff/debuff icon. An easy one to test is (Improved) Blessing of Might, which shows a flat 550 AP regardless of the talent on your buff bar, but will still give the correct increased amount if talented.

It's very likely to be the same situation here, but I'll check just to be 100% sure.

**Comment by Oganku** [comment]
Yep, increase is still working, just a visual tooltip inconsistency on blizzard's part. Also I remember reading at one point that non-improved will always overwrite Improved Hunter's Marks, but that is blizz-like, therefore you should communicate with other hunters to let them know you have improved talent/glyph.
