### ISSUE TITLE
Mount with wings or not 

### ISSUE THREAD

**Issue by joka95** [WoWManiaUK/Redemption#5129]
**Links:**

**What is Happening:**
I notice this mount dont have wings. But when  i fly in backward wings are there.  this is some interesting thing i think you guys should look for it.. 
![WoWScrnShot_111720_154955](https://user-images.githubusercontent.com/63783357/99406024-b5f49f80-28ed-11eb-98f5-4aabc62a9704.jpg)
![WoWScrnShot_111720_155122](https://user-images.githubusercontent.com/63783357/99406027-b68d3600-28ed-11eb-8ac5-bd087aab2acd.jpg)

**What Should happen:**

i think wings shoud be all time shown.

**Comment by Rushor** [comment]
what is the item name?

**Comment by svijetlo** [comment]
sec i will fiind them all

**Comment by svijetlo** [comment]
http://www.wow-mania.com/armory?spell=229379
http://www.wow-mania.com/armory?spell=229378
http://www.wow-mania.com/armory?spell=229377

**Comment by svijetlo** [comment]
![WoWScrnShot_111720_181013](https://user-images.githubusercontent.com/61908373/99422915-4cca5780-2900-11eb-8aac-8f3eee3648e1.jpg)
![WoWScrnShot_111720_181024](https://user-images.githubusercontent.com/61908373/99422928-4fc54800-2900-11eb-9365-adc5c3938540.jpg)
![WoWScrnShot_111720_181034](https://user-images.githubusercontent.com/61908373/99422934-5227a200-2900-11eb-88d9-622bd72cd696.jpg)
can confirm this 
if you fly in reverse wings show up but if you fly forward wings do not show , same for all 3 versions of it

**Comment by Echinaceax** [comment]
was reported here ages ago, i confirmed this myself https://github.com/WoWManiaUK/Redemption/issues/3001#issuecomment-462040946
