### ISSUE TITLE
Missing raid ID check box

### ISSUE THREAD

**Issue by Loktard** [WoWManiaUK/Redemption#5130]
**What is Happening:**
If i enter a dungeon with ID i get instant locked to that ID.

**What Should happen:**
I enter the dungeon  and get a check box with a 60 sec timer . After 60 sec i get teleported out of the dungeon or i accept the ID lock.

I know this got changed because some Players were abusing it to get gear on alts whithout running the Raid propperly. But fixing a bug to add another bug isn't the right way and it's also not blizzlike. With this new bug whole raids get screwed over.

**Comment by jeyrella** [comment]
There was a reason.  Won't be changing back until there is another solution.
