### ISSUE TITLE
[Raid] M'uru's Singularities

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#5131]
**Links:** https://wow.gamepedia.com/M%27uru_(tactics)
https://www.wow-mania.com/armory/?spell=46238
https://youtu.be/0bZi5KWON38?t=380

**What is Happening:** The singularities in M'uru's 2nd phase encounter (Entropius) are currently vacuuming the entire raid onto their position every ~0.5s, making it impossible to move away or even cast any non-instant spell, as you are constantly getting displaced. It's making M'uru's phase 2 nearly impossible unless you have enough dps to kill Entropius before or within a few seconds of the first singularity spawning.

The singularities are currently not moving at all, affecting all players in the room regardless of their distance, and seem to be missing their "throw" mechanic that should follow the vacuuming.

**What Should happen:** As can be seen in [this video](https://youtu.be/0bZi5KWON38?t=380) from around 6:20 onward, the singularities move about the room rather slowly, and will sort of suck and throw away players that get too close to them. At 6:24 we can see the tank moving the boss away from the incoming singularity, but the warrior we are watching ends up too close to it and gets grabbed then thrown away helplessly. It happens again several times in the minutes that follow.

> Singularity: Spawns over a player. After a few seconds will move around and toss any nearby players around dealing 500 damage a tick.

Their behavior from the video seems to be, they spawn at one edge of the room, and travel to the opposite edge, passing near the boss, and will suck and bounce players that get too close. It's possible for a single player to get sucked and bounced that way multiple times by the same singularity if they are unlucky and get thrown back into its path.

**Comment by Rushor** [comment]
try now pls, the knockback effect should be given now and the black holes should walk around

**Comment by Oganku** [comment]
They don't move too much, they spawn, home onto a player and kinda stop after a few seconds, but their knockback behavior is a thousand times better. 👍

**Comment by Rushor** [comment]
Thank you :)
