### ISSUE TITLE
Dual Talent Specialization

### ISSUE THREAD

**Issue by jonathan5er** [WoWManiaUK/Redemption#5133]
**Links:** No link

**What is Happening:** Buying second spec price is wrong, it costs only 500 gold to buy it

**What Should happen:** Price for dual spec should be 1000 gold instead

https://wowwiki.fandom.com/wiki/Dual_Talent_Specialization

**Comment by jeyrella** [comment]
I believe this was a deliberate design choice, but I will check.  Thanks.

**Comment by jeyrella** [comment]
Confirmed this was a design decision.
