### ISSUE TITLE
Quest: (Part 3) Trial of the Sea Lion - loot box missing.

### ISSUE THREAD

**Issue by Broadbanned** [WoWManiaUK/Redemption#5134]
**Links:**
Quest: [Trail of the Sea Lion](https://classic.wowhead.com/quest=30/trial-of-the-sea-lion)
Quest Item: [Half Pendant of Aquatic Endurance](https://classic.wowhead.com/item=15882/half-pendant-of-aquatic-endurance)
Map location: 30.0, 29.0
Video from WoWHead: [Youtube clip of where to find the loot box](https://youtu.be/ahnJOD3NsUE?t=112)

**What is Happening:**
Go to the map location and dive underwater, the loot box containing the quest item and air bubbles to breathe are completely missing.

![quest_item_missing](https://user-images.githubusercontent.com/74674754/99564408-a4f86c80-2987-11eb-9205-0cc32698bc55.jpg)

**What Should happen:**
You should be able to dive at the location and find then open a loot box containing the quest item.

**Comment by jeyrella** [comment]
Well, this seems to be confirmed.  Horde side quest only.
Object 177790 doesn't appear to exist
https://youtu.be/q5nqsc8qlDE
![image](https://user-images.githubusercontent.com/46089380/99572519-b3b54280-29cc-11eb-8fe5-c0996f81c28e.png)


Alliance side quest seems to be ok in regards to locations.

**Comment by Rushor** [comment]
position changed :)

**Comment by jeyrella** [comment]
confirmed fixed
![image](https://user-images.githubusercontent.com/46089380/99572994-6685a080-29cd-11eb-93ce-cf198bd7dbbd.png)
