### ISSUE TITLE
[Raid] Ouro's incomplete encounter (Temple of Ahn'Qiraj)

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#5135]
**Links:** https://wowwiki.fandom.com/wiki/Ouro
https://www.youtube.com/watch?v=9ltyRGoHqi4
https://www.wow-mania.com/armory/?npc=15957
https://www.wow-mania.com/armory/?npc=15718

**What is Happening:** Ouro, while a very simple encounter, is missing most of its mechanics and presents a couple issues (from most to least important):

1. 1.5min after being pulled, Ouro will burrow, and will simply vanish from existence. Players will leave combat, and the boss will disappear, ending the encounter. It forces you to kill him in 1.5min or he just goes bye-bye.

2. A targettable [Ouro Spawner](https://www.wow-mania.com/armory/?npc=15957) is present inside Ouro and can be killed by players.

3. Ouro greets players from his upright, unburrowed position.

**What Should happen:**
1. Ouro should have a very simple burrow phase, where he digs under ground for about 25 seconds (see [video](https://www.youtube.com/watch?v=9ltyRGoHqi4)) after which he emerges and continues attacking the group. Some [Ouro Scarabs](https://www.wow-mania.com/armory/?npc=15718) are also meant to emerge at this time, locking onto players and ignoring aggro tables.

> Scarabs: They hit for 300 on cloth, 40-150 on tanks. They will pick an initial target and will never change targets. They will despawn on their own after 45 seconds.

2. Ouro Spawner should not be visible, targettable, or killable by players, and might be the cause of issue 1.

3. Ouro should initially visually be burrowed, and emerge as players approach him to engage.

**Comment by Rushor** [comment]
the encounter will now continue after 1.5 minutes, the underground phase will be handled
the spawner is removed
the boss will perform the burrow visual correctly now
