### ISSUE TITLE
[Quest] That's Abominable! quest

### ISSUE THREAD

**Issue by jonathan5er** [WoWManiaUK/Redemption#5136]
**Links:** https://www.wowhead.com/quest=13264/thats-abominable

**What is Happening:** Attack option on abominaton does not work, pet (abomination) only stands next to player

**What Should happen:** When you press attack, pet should go to target and attack it

https://www.youtube.com/watch?v=ZEWsG37k-eY

**Comment by wow-mania** [comment]
pretty sure it works.

**Comment by jonathan5er** [comment]
I have just tried it @wow-mania but it did not work...

And minor thing too when blasting them away with ability, it is supposed to blast player away too but it doesn't...

**Comment by svijetlo** [comment]
![WoWScrnShot_111920_171843](https://user-images.githubusercontent.com/61908373/99693155-57fdbe80-2a8b-11eb-9c74-414326647566.jpg)
yap does not do a thing

**Comment by svijetlo** [comment]
other 2 skills work , explode and to "fart" but it wont attack enemy if you do pet attack

**Comment by svijetlo** [comment]
![WoWScrnShot_111920_172348](https://user-images.githubusercontent.com/61908373/99693767-0275e180-2a8c-11eb-93a2-d3ce9cfd31d1.jpg)

**Comment by jonathan5er** [comment]
yes, that is correct

**Comment by Rushor** [comment]
Checking

**Comment by Rushor** [comment]
creature will handle the attack start now if the pet bar is used
