### ISSUE TITLE
[Quest] Basic Chemistry

### ISSUE THREAD

**Issue by jonathan5er** [WoWManiaUK/Redemption#5137]
**Links:** https://www.wowhead.com/quest=13295/basic-chemistry

**What is Happening:** Event for quest is very broken, sometimes it starts after using the quest item and sometimes it doesnt... When it starts it will be one or two waves and then the event stops and nothing happens so you have to keep trying over and over again. Same happens on both side cauldrons and the one in the middle doesnt work at all, says "Requires Mord'rethar Plague Cauldron"

**What Should happen:** All three cauldrons should work to begin with, and then the event should follow as shown in this video on youtube... having waves and using the quest item again when event ask for it

https://youtu.be/HvO7ZRdkyhA (only difference is quest item here is 30 seconds cooldown instead of 1 minute 30 seconds - this change happen with Cataclysm come out)

**Comment by jeyrella** [comment]
This is a cata video.  It was changed for Cata due to likely only having one person available for the quest.  In WotLK it needed 3 people to work properly, which is unusual on this server due to phasing.

I believe with 3 people on the quest, it might work as intended, but will check this.

**Comment by jonathan5er** [comment]
Yes but event should not stop without asking for more fluid to be added
It just stop on its own now
Quest is also possible with 2 people to complete if cast not interrupted

**Comment by Rushor** [comment]
if you list me the issues i can fix it

**Comment by jonathan5er** [comment]
Me or @jeyrella ?

**Comment by wow-mania** [comment]
This is a "chance". As-is

**Comment by jonathan5er** [comment]
This is not a "chance" though... Don't know where you are getting this from
But if it was a chance lets say, it is still broken... The event just stops on its own when it does manage to start...
