### ISSUE TITLE
[Raid] Mimiron causes SW:P not to be refreshed by Mind Flay

### ISSUE THREAD

**Issue by jeyrella** [WoWManiaUK/Redemption#5138]
**Links:**
https://wow-mania.com/armory/?npc=33350
Mind Flay:  https://wow-mania.com/armory/?spell=48156
Shadow Word: Pain:  https://wow-mania.com/armory/?spell=48125

**What is Happening:**
When Shadow Word Pain is used on Mimiron, it is not refreshed by Mind Flay.  Seems to happen on both 10 and 25, hard mode and normal.
https://youtu.be/OuuXjqwn-fw

**What Should happen:**
Like every other NPC, Shadow Word Pain should be refreshed by Mind Flay.

**Comment by jeyrella** [comment]
Seems to affect all ranks of the spells too.

**Comment by Keader** [comment]
fixed, test now

**Comment by svijetlo** [comment]
![WoWScrnShot_112320_110551](https://user-images.githubusercontent.com/61908373/99950182-7231e800-2d7c-11eb-828e-0c45c3275a30.jpg)
![WoWScrnShot_112320_110553](https://user-images.githubusercontent.com/61908373/99950188-752cd880-2d7c-11eb-8ee8-28af9da28f34.jpg)
![WoWScrnShot_112320_110653](https://user-images.githubusercontent.com/61908373/99950195-778f3280-2d7c-11eb-8b61-76554f2f7da9.jpg)
![WoWScrnShot_112320_110654](https://user-images.githubusercontent.com/61908373/99950203-7958f600-2d7c-11eb-80fd-cbcee323e65d.jpg)
![WoWScrnShot_112320_110849](https://user-images.githubusercontent.com/61908373/99950209-7bbb5000-2d7c-11eb-9b2f-c50b154433bf.jpg)
![WoWScrnShot_112320_110914](https://user-images.githubusercontent.com/61908373/99950216-7e1daa00-2d7c-11eb-9ae1-be8e2f9fb154.jpg)
![WoWScrnShot_112320_110918](https://user-images.githubusercontent.com/61908373/99950221-7fe76d80-2d7c-11eb-8db3-adda5a22e475.jpg)
![WoWScrnShot_112320_110920](https://user-images.githubusercontent.com/61908373/99950232-8249c780-2d7c-11eb-9e80-56b1bd0bb846.jpg)
![WoWScrnShot_112320_110924](https://user-images.githubusercontent.com/61908373/99950234-84138b00-2d7c-11eb-8c6f-ff2fa1e7f4ce.jpg)

**Comment by svijetlo** [comment]
this still need work , thos it does work in all 3 phases , lower part , mid part , and head , but ones we get to phase 4 it works fine on lower part and middle part , but in phase 4 if you do it on body it does not work

**Comment by Keader** [comment]
Fixed.

https://youtu.be/sE2Rdx1TJCw
