### ISSUE TITLE
[Quest] The Ironwall Rampart

### ISSUE THREAD

**Issue by jonathan5er** [WoWManiaUK/Redemption#5139]
**Links:** https://www.wowhead.com/quest=13337/the-ironwall-rampart

**What is Happening:** Grimkor's pet "Grimkor's Hound" is level 1 with 126 health which make this group [5] quest much easier than intended... Also Grimkor is supposed to make speech before fight but he will instant pull when summoned if close to him

**What Should happen:** His pet should be level 80 elite pet with 37800 health and use his abilities and also the missing speech from Grimkor the Wicked

https://www.youtube.com/watch?v=jFzpGdD32Mw

**Comment by Rushor** [comment]
will fix that

**Comment by svijetlo** [comment]
![WoWScrnShot_112020_002348](https://user-images.githubusercontent.com/61908373/99736565-e5aacf80-2ac6-11eb-824c-8548860b291a.jpg)

**Comment by Rushor** [comment]
added the intro event and changed level and combat abilities for those 2 buddies
