### ISSUE TITLE
[Quest] A Short Fuse

### ISSUE THREAD

**Issue by jonathan5er** [WoWManiaUK/Redemption#5141]
**Links:** https://www.wowhead.com/quest=13389/a-short-fuse

**What is Happening:** When quest is accepted visual shows up for the explosion ("short fuse") but does not move player to fall down in the hole

**What Should happen:** Player should start falling in the hole after accepting quest

https://www.youtube.com/watch?v=0BhcfHN0qSE

**Comment by svijetlo** [comment]
![WoWScrnShot_112020_002011](https://user-images.githubusercontent.com/61908373/99736166-3968e900-2ac6-11eb-9899-f013e8d95310.jpg)
ramp under player should brake and he should fall down

**Comment by Rushor** [comment]
That is a nice one! Will fix it

**Comment by Rushor** [comment]
the player should now get ported to the middle and will fall down
