### ISSUE TITLE
[Quest] The Kessel Run not offered by Kessel

### ISSUE THREAD

**Issue by billykitty** [WoWManiaUK/Redemption#5142]
**Links:**
http://www.wow-mania.com/armory?quest=9663
https://www.wow-mania.com/armory/?npc=17649

[https://ibb.co/HVgXb2m](url)

**What is Happening:**
NPC Kessel has a yellow exclamation point but does not offer this quest.

**What Should happen:**
NPC Kessel should offer this quest to any level 10+ Alliance player, no prerequisite quests.

**Comment by Oganku** [comment]
Linked to #5064?

**Comment by jeyrella** [comment]
I just created a naked brand new level 80 druid, went to kessel and it works fine.
![image](https://user-images.githubusercontent.com/46089380/99726922-21d23600-2aaf-11eb-9a78-5fc6063da182.png)

Are you certain you have cache cleared, launcher updated, run with admin mode?

**Comment by billykitty** [comment]
I have cache cleared, launcher up to date at 2.8, running with admin mode, and add-ons disabled.  I even renamed my wtf folder but no change. Everyquest addon says I haven't taken this quest. Is there a way to verify this?
![WoWScrnShot_112020_103901](https://user-images.githubusercontent.com/1437646/99836123-d9546000-2b22-11eb-9ef1-3ca82627cc53.jpg)

Strangely, another level 80 on a different account can see the quest.

**Comment by jeyrella** [comment]
@billykitty a GM can verify this for you.  

By the way, have you re-downloaded the EveryQuest server query?  Try that.  If the server crashes or you otherwise DC in the zone, you lose any unsaved quest progress in EveryQuest.  You might actually have completed it and lost the data this way.
