### ISSUE TITLE
[Quest] Matis the Cruel - Flare Gun scaling with SP

### ISSUE THREAD

**Issue by billykitty** [WoWManiaUK/Redemption#5143]
**Links:**
http://www.wow-mania.com/armory/?quest=9711
http://www.wow-mania.com/armory/?npc=17664
provided item: http://www.wow-mania.com/armory/?item=24278

Previous bug report: #3585

**What is Happening:**
This report was closed but is still reproducible.

When completed at high level, using the provided item on Matis seems to cause damage. This kills him instantly, meaning the summoned NPCs have no chance to capture him.
This means the quest cannot complete, since the NPC have no target to capture.

Workaround is to do quest naked.

**What Should happen:**
Using the Flare Gun provided should not cause any damage to Matis, allowing the NPC to "capture" Matis.

**Comment by jeyrella** [comment]
Reopening original.
