### ISSUE TITLE
[Timer] Wintergrasp

### ISSUE THREAD

**Issue by cathyr1** [WoWManiaUK/Redemption#5144]
There is one small mistake in counting out time till next WG battle. When the player is in the certain map or city (except only Wintergrasp itself) and the battle ends, there remains "In Progress" and it never changes to proper timer until the player enters another map or relogs.

**Comment by Keader** [comment]
Fixed, WorldState was just updated when player change map or on login.
Testers can use command .bf start 1, to start wg and help test it.
