### ISSUE TITLE
Hulking Horror missing loot table

### ISSUE THREAD

**Issue by jonathan5er** [WoWManiaUK/Redemption#5145]
**Links:** https://www.wowhead.com/npc=31411/hulking-horror

**What is Happening:** This creature does not have any loot drops

**What Should happen:** Hulking Horror should have a chance to drop one of the items from his available loot

**Comment by Rushor** [comment]
do we have a similar creature with similar drops? so i could quick assign the same for this creature

**Comment by jonathan5er** [comment]
Maybe like this one? Minus the quest drop items
https://www.wowhead.com/npc=31155/malefic-necromancer#drops

Majority of Icecrown creatures have very similar drops +/- the quest drops
Maybe check for creature with 31413 too because it is for horde??

**Comment by Rushor** [comment]
thank you!

**Comment by Rushor** [comment]
loot added
