### ISSUE TITLE
Mage Frostfire Bolt - loss of critical hit chance

### ISSUE THREAD

**Issue by amvsda** [WoWManiaUK/Redemption#5146]
**Links:**
https://www.wowhead.com/spell=51779/frostfire-bolt#changelog
https://www.wowhead.com/spell=133/fireball

**What is Happening:**
Frostfire Bolt critical hit chance is significantly reduced, with roughly 20% of what is displayed on the Character Info->Spell->Crit Chance->Fire

**What Should happen:**
Frostfire Bolt critical hits percentage should be close or higher to what is displayed on the above mentioned pane.

**Further Details:**
I've tested with both Frostfire Bolt and Fireball, the latter working as it should.
-Gear: 
I've used the same gear to test with both spells.
-Talent tree and glyphs:
For Fireball:
![image](https://user-images.githubusercontent.com/68973755/99875749-9b2a6f80-2bfa-11eb-9ecb-d8a941749077.png)
For Frostfire Bolt:
![image](https://user-images.githubusercontent.com/68973755/99875841-463b2900-2bfb-11eb-8119-6dea0bcadb32.png)
-Recount Data:
![WoWScrnShot_112120_121938](https://user-images.githubusercontent.com/68973755/99875865-6d91f600-2bfb-11eb-8315-ebd1bd678f7d.jpg)
The data shown above was gathered from a 25 ICC normal raid. All buffs affecting the mage's spell critical hit chance were present, with a displayed chance (as shown on the character pane) of approximately 70%.

**Comment by Oganku** [comment]
Frostfire bolt has a DoT component, which is unable to crit. Skada counts both the DoT and the direct damage as part of the same data. So your crit chance is getting diluted by the DoT ticks of the spell.

**Comment by amvsda** [comment]
> Frostfire bolt has a DoT component, which is unable to crit. Skada counts both the DoT and the direct damage as part of the same data. So your crit chance is getting diluted by the DoT ticks of the spell.

I switched to Recount addon and you are right. Works as it should, closing issue.
Thanks.
