### ISSUE TITLE
[Raid] Chromaggus' portcullis and lever (Blackwing Lair)

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#5148]
**Links:** 

**What is Happening:** Chromaggus' door can be interacted by players to open it, and the lever that is meant to be used to release the beast does nothing.
![image](https://user-images.githubusercontent.com/34783736/99886846-c5395d00-2c0d-11eb-8faf-6879c874a025.png)

**What Should happen:** The lever should open the door, releasing Chromaggus, while the door should not be clickable by non-GMs.

**Comment by Rushor** [comment]
Will fix

**Comment by Rushor** [comment]
the chromaggus exit door to nefarian should also not be usable by player - it should open once chromaggus is dead

**Comment by Rushor** [comment]
all fixed, doors no longer clickable, lever usable and interactive with door by player
