### ISSUE TITLE
[Raid] Nefarian's ressurected drakonids

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#5149]
**Links:** https://wow.gamepedia.com/Nefarian_(tactics)
https://www.wow-mania.com/armory/?npc=14605
https://www.wow-mania.com/armory/?npc=14265
https://www.wow-mania.com/armory/?npc=14261
https://www.wow-mania.com/armory/?npc=14263
https://www.wow-mania.com/armory/?npc=14302
https://www.wow-mania.com/armory/?npc=14262
https://www.wow-mania.com/armory/?npc=14264

**What is Happening:** When Nefarian reaches 20% HP, he ressurects all of the colored drakonids (links above) killed in phase 1 as the original mob, causing the players to be swarmed by those fairly strong mobs.

**What Should happen:**
> When his health reaches 20% he will resurrect all the Drakonids killed in Phase 1 as "[Bone Constructs](https://www.wow-mania.com/armory/?npc=14605)". Those bone constructs, while numerous, are much more manageable, with their lower health and damage.

**Comment by Rushor** [comment]
Will fix, they just need a correct Update call

**Comment by Rushor** [comment]
all fixed. they will spawn as bone contruct now https://i.imgur.com/WYc4JjG.jpg
