### ISSUE TITLE
[Companion] Red Panda wrongly tagged as Dragonkin

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#5150]
**Links:** https://www.wow-mania.com/armory/?spell=137568

**What is Happening:** The [Red Panda](https://www.wow-mania.com/armory/?spell=137568) companion is currently marked as a dragonkin.
![image](https://user-images.githubusercontent.com/34783736/99891757-5ecb3380-2c3b-11eb-8536-8e461cbadf1e.png)

**What Should happen:** As all other companions, it should be tagged as a 'Non-combat Pet'.

**Comment by Rushor** [comment]
fixed pls remember to delete cache and restart client before testing :)
