### ISSUE TITLE
[Quest] Chicken party!

### ISSUE THREAD

**Issue by svijetlo** [WoWManiaUK/Redemption#5151]
**Links:**
http://www.wow-mania.com/armory?quest=12702

**What is Happening:**
ones you take quest no no chicken can be found in village or around it for 3 days now 
could be connected to https://github.com/WoWManiaUK/Redemption/issues/5120
![WoWScrnShot_112320_093338](https://user-images.githubusercontent.com/61908373/99943107-1150e280-2d71-11eb-8afd-fd5b5d83f14b.jpg)

**What Should happen:**
ones you take quest chicken should spawn and run around in village and close to village

**Comment by Rushor** [comment]
for me they are there https://i.imgur.com/i0brSFe.jpg

the zone has phasing

INSERT INTO `spell_area` (`spell`, `area`, `quest_start`, `quest_end`, `aura_spell`, `racemask`, `gender`, `autocast`, `quest_start_status`, `quest_end_status`) VALUES 
(50735, 3711, 12532, 12532, 0, 0, 2, 1, 74, 11),
(50735, 3711, 12702, 12702, 0, 0, 2, 1, 74, 11),
(50735, 4292, 12532, 12532, 0, 0, 2, 1, 74, 11),
(50735, 4292, 12702, 12702, 0, 0, 2, 1, 74, 11);


so the issue might be related to you phasing status?

**Comment by svijetlo** [comment]
i em doing those quests for rep till 3 days ago all was fine now  for last 3 days same to me and to some other players

**Comment by wow-mania** [comment]
nothing changed for the last week so it must be some refresh issue

**Comment by Rushor** [comment]
Can you reproduce it on ptr svijetlo?

**Comment by Oganku** [comment]
Both the daily and non-daily versions of the chicken quest phase me correctly and allow me to see the chickens on PTR. Can't reproduce myself.

**Comment by svijetlo** [comment]
it worked fine today , just ignore me , will close it for now , if it repeats i will see to gather more dana why does it happen

**Comment by jeyrella** [comment]
Getting reports that this is indeed still a problem in live, even if we can't reproduce on PTR

**Comment by svijetlo** [comment]
i deleted my cache and it worked , tho im don with rep so i dont do it anymore just today 3 ppl told me it did not work , and it was same after i told em to delete cache, i went there on ptr it was fine

**Comment by Rushor** [comment]
try now pls

**Comment by jeyrella** [comment]
Don't know what you changed, but can't be tested since the issue was not reproducible in PTR anyway.

**Comment by jeyrella** [comment]
Yes.  I will confirm this as there is not much we can really test other than it "still works", which it does.  Let's see if this helps.
