### ISSUE TITLE
The Nexus Dungeon - Death from falling on the first floor - Teleported my ghost in Icecrown

### ISSUE THREAD

**Issue by AresRex** [WoWManiaUK/Redemption#5153]
**Links:**

https://paste.pics/6a36f5c8e81908925896fb6067398aa2 - showing where my corpse is on the map.
https://paste.pics/5ac0f0acc40b712597828f1acc802eaf - showing that I can resurrect in the cave The Hidden Hollow (where I was before I joined the dungeon). It's not really clear on the screenshot but I couldn't find my corpse there.
https://paste.pics/733cde4068807e103f6b5719c14c319c - showing the other side, so you can see that there is no corpse there.

**What is Happening:**

I jumped off from the Nexus dungeon - first floor and it teleported my corpse in Icecrown. There is no way to get back to my real corpse from there, I am pretty sure this is a bug since there is a spirit healer in Coldarra. 
If it helps you - I had a loading screen twice after my death. Also, I was there before I entered the dungeon with Dungeon finder - it's the cave The Hidden Hollow. I was able to resurrect in the cave afterwards.

**What Should happen:**

I should've been teleported to a spirit healer in Coldarra. There is no way to reach your corpse as a ghost outside Coldarra.

I've read the rules and I hope this is a valid bug report. Hope it's fixed soon, thanks.

**Comment by Oganku** [comment]
Sams as #4246

**Comment by Keader** [comment]
Without reproduce case, nothing that i can do

**Comment by Oganku** [comment]
I'll try to see if I can reproduce it
