### ISSUE TITLE
[Quest] The Hunter and the Prince - Bloodstained Stone & Illidan not spawned

### ISSUE THREAD

**Issue by SzGabor93** [WoWManiaUK/Redemption#5154]
Hi!

The Hunter and the Prince quest is bugged (Icecrown).  The bloodstained stone is not here. Without the stone I cant do the quest.

**Comment by Rushor** [comment]
The stone is pooled as far as i know. Gonna check

**Comment by Oganku** [comment]
I did have to retake the quest myself to have it appear, and I know other players have had to also. Not sure what causes it, maybe wrong phasing idk.

**Comment by jeyrella** [comment]
Re-opened on discussion with Janitor.
I tested on PTR and could not reproduce on either faction; however I have experienced this on live, and see world chat comments from time to time.
Seems intermittent, or has an edge case cause.

Workaround is to drop the quest and take it again, and then it always works.  

Alliance:  https://wow-mania.com/armory/?quest=13400
Horde:  https://wow-mania.com/armory/?quest=13361

@Rushor perhaps you could take a quick look at code and see if anything jumps out as odd?

**Comment by jeyrella** [comment]
Just managed to replicate this in PTR.  Took the quest from Lerner, nothing happened; Illidan did not spawn and the stone was not present.  However 5 other times it worked ok.  Seems intermittent.

```
Quest accepted: The Hunter and the Prince
NPC currently selected by player:
DB GUID: 0, current GUID: 4418.
Faction: 14.
npcFlags: 0.
Entry: 31395.
DisplayID: 27571 (Native: 27571).
Level: 82.
EquipmentId: 1 (Original: 0).
Health (base): 903520. (max): 903520. (current): 903520.
InhabitType: 3
Unit Flags: 0
Unit Flags 2: 2048.
Dynamic Flags: 0.
Faction Template: 14.
SpawnTime: Full:5m Remaining:0s
Loot: 0 Pickpocket: 0 Skinning: 0
InstanceID: 0
Phasemask: 4
Armor: 10356
Position: 6314.500000 2342.800049 479.399994.
AIName: SmartAI ScriptName: 
Flags Extra: 0
MechanicImmuneMask: 0
```

**Comment by Rushor** [comment]
try now pls, they should always spawn now

**Comment by jeyrella** [comment]
Stone does not despawn if player abandons quest.
In that case other players can also see the stone, interact with it, and spawn Illidan.

Not only that, but when player is on quest, other players can STILL see the stone, interact with it, and they get phased into with the original player on the same fight
![image](https://user-images.githubusercontent.com/46089380/101290923-f795ad80-37fc-11eb-9da8-bd20fd78b9a2.png)
![image](https://user-images.githubusercontent.com/46089380/101290957-30358700-37fd-11eb-978a-4ee6a499fe2e.png)

**Comment by jeyrella** [comment]
If original player leaves vehicle while in combat, both illidan and stone ARE properly despawned though.

**Comment by jeyrella** [comment]
Am hearing this may actually be an additional issue that was already present.  If that's confirmed will split into separate ticket.

Original issue of "stone doesn't always spawn" does seem to be fixed, taken 12 times in a variety of ways and stone spawned every time

**Comment by Rushor** [comment]
i will add that you cannot use the stone, if you have not taken the quest

**Comment by jeyrella** [comment]
yep that would work

**Comment by Rushor** [comment]
stone should now only be usable if player has quest 13400 or 13361 taken

**Comment by jeyrella** [comment]
Ok.  So

Stone now despawns when player 1 uses it. (good)
Illidan despawns if player 1 leaves "vehicle" (good)

However, if after player 1 takes quest, player 2 uses stone, it despawns for player 1 also, and they are left having to re-take quest.
I think this could be acceptable, but the perfect fix would be that player 2 cannot use the stone at all?   
(Or that the stone itself is phased with player 1 on taking quest)

**Comment by jeyrella** [comment]
ok fix is complicated for what is minor issue left over.  happy to sign this fix off as it is.
