### ISSUE TITLE
[Raid] Felmyst's Demonic Vapors

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#5155]
**Links:** https://wowwiki.fandom.com/wiki/Felmyst
https://youtu.be/pcv5LlawB1A?t=862
https://www.wow-mania.com/armory/?search=demonic+vapor#spells
https://www.wow-mania.com/armory/?npc=25268

**What is Happening:** The fight function mostly fine, but 1 major issue persists. When air phase begins, Felmyst will use her first aerial-ability roughly 5 seconds after leaving melee range; the [Demonic Vapor](https://www.wow-mania.com/armory/?search=demonic+vapor#spells). However, it is currently targetting every single raid member with a nature damage beam that leaves behind a nature damage trail. 
The stacking trails of damage quickly overwhelm the entire room and the more players are present, the more chaotic it is.

**What Should happen:** 

> She will target a random player for a couple seconds, then cast it under them. The spell follows that player for about ten seconds, leaving the DoT trail and summoning skeletons soon after.

1. The spell is supposed to target only a single raid member and chase them for a short duration (duration and damage are correct for 1 person), before choosing a new target and repeating the process (Behaves somewhat like the spikes in the Anub'Arak encounter). After 2 Demonic Vapors, she starts her fly-bys that spread the Fog of Corruption (fixed previously).
Behavior is clearly seen from ~14:20 onward in [this video](https://youtu.be/pcv5LlawB1A?t=862).

2. The trail is supposed to spawn ~10 [Unyielding Dead](https://www.wow-mania.com/armory/?npc=25268) as it is forming (14:37 in the video), and additional skeletons if players touch the trail afterwards (similar to Yogg-Saron's clouds). There used to be a fairly bad issue with the number of skeletons spawned by this ability (most likely due to the spell targeting all raid members instead of only 1). *Less important than 1

**Comment by Keader** [comment]
can you check now please?

**Comment by Oganku** [comment]
- [x] Only targets one player, main issue fixed

- [x] Spawns skeletons when touched (I can't find exact number, but 10 for each second spent in the mist feels like a lot)

- [ ] Does not spawn the 10 skeleton on its own as the trail is forming

**Comment by Keader** [comment]
Fixed.
And fixed number of skeletrons when touch

**Comment by Oganku** [comment]
https://imgur.com/a/mgfGPGT

Spawn perfectly as it forms, targets only 1 person, does not spawn additional skeletons when touched. (Up to you if we fix that last point)
