### ISSUE TITLE
[Raid] Felmyst's Encapsulate

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#5156]
**Links:** https://wowwiki.fandom.com/wiki/Felmyst
https://www.wow-mania.com/armory/?spell=45661
https://www.youtube.com/watch?v=aKi-Dx7cm1w

**What is Happening:** Felmyst never uses the Encapsulate ability during her ground phase.

**What Should happen:** Felmyst should target 1 random raid member and cast [Encapsulate](https://www.wow-mania.com/armory/?spell=45661) on them about every 30s (evidence from [video](https://www.youtube.com/watch?v=aKi-Dx7cm1w) above) during the ground phase.

**Comment by Keader** [comment]
fixed.

**Comment by Oganku** [comment]
Haven't seen it happen with 2 ppl in the arena, over 2 ground phases.

**Comment by Keader** [comment]
Ok, now fixed.
Tested my self, i took a long time to find a janitor fix that was breaking it.

**Comment by Oganku** [comment]
https://imgur.com/a/NbisrQd

Works well, correct amount, and randomly targets!
