### ISSUE TITLE
[Achievement] Take out those turrets (Ulduar 10&25man version) is not working

### ISSUE THREAD

**Issue by theonykry** [WoWManiaUK/Redemption#5157]
**Links:**

**What is Happening:**
once inside the demolisher, the bystander has to load himself into the catalpult and get shot onto the Flame leviathan by the driver. Once up there the player has to destroy the turrets that are spawned, 4 of them should already be spawned once the player is shot onto the leviathan, which is not the case. so the player has to use some AoE-Dmg to activate the turrets. as soon as the turrets are activated by dmg of the player, he falls through the leviathan and is standing on the ground again (plattform disappread or became instable), hence the achievment is not completeable.

**What Should happen:**
Once shoot onto the leviathan the small turrets (4) should already be active on each corner of the platform/leviathan. the damage of the player should not cause him to fall through the leviathan / the plattform.

**Comment by theonykry** [comment]
i looked for an armory link but there seems to be noone, which is wierd too.

**Comment by Oganku** [comment]
#3144

I can confirm you don't get credit for killing the turrets. A while ago I did try and you can launch players and kill the turrets properly, causing the shutdown, but you get no achieve for it. :(

**Comment by jeyrella** [comment]
^^ confirming what Oganku said.  Turrets can be killed, but no achievement.

**Comment by Keader** [comment]
Ok, Test now please.
It's giving achiev now, but maybe it's giving achiev for both difficulties now.
Has a core issue adding both achievs, and since it's ulduar... i dont think tha worth lose much time trying track reason for it.

**Comment by Oganku** [comment]
![image](https://user-images.githubusercontent.com/34783736/100485931-ed263600-30cf-11eb-95f6-246d6e3d2f3a.png)
Not perfect, but works 👌

**Comment by jeyrella** [comment]
Yeah  works for me.  Better than none.... people after actually doing this are likely to do both anyways :D

**Comment by Woofles** [comment]
Well works but the wrong player is getting the achievement. 
Should be the passenger but it's the driver that gets it now.

**Comment by Echinaceax** [comment]
@Keader 

Wowhead comment https://www.wowhead.com/achievement=12315/take-out-those-turrets#comments
![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/957982f8-72f0-48b3-942a-59f77b409e5c)
