### ISSUE TITLE
[Item] Bountiful Feast wrong stats

### ISSUE THREAD

**Issue by bLeyaa** [WoWManiaUK/Redemption#5158]
**Links:** http://www.wow-mania.com/armory?item=46887

**What is Happening:** Well Fed buff gained from this feast gives higher stats than intended, currently it's as follows:

Attack Power: 96
Stamina: 48 
Spell Power: 56

**What Should happen:** Well Fed buff should be as indicated on the feast, as follows:

Attack Power: 80
Stamina: 40
Spell Power: 47

**Comment by Rushor** [comment]
is this official data source?

**Comment by bLeyaa** [comment]
Yes, the in game tooltip is correct but the stats received for some reason are not.

![image](https://user-images.githubusercontent.com/61625377/100258862-d3f27d80-2f47-11eb-876d-383268f4f51b.png)

The stats scale with level, but at level 80 its supposed to be same as fish feast, which is 80/40/47 respectively.

**Comment by jeyrella** [comment]
https://www.wowhead.com/spell=66486/bountiful-feast#comments:id=897739
![image](https://user-images.githubusercontent.com/46089380/100262607-49f4e580-2f44-11eb-8d0e-732999f68f8d.png)

**Comment by jeyrella** [comment]
https://wow.gamepedia.com/Bountiful_Feast
![image](https://user-images.githubusercontent.com/46089380/100262909-b8d23e80-2f44-11eb-9bd2-fd5d42290f09.png)

**Comment by bLeyaa** [comment]
Oh lmao, nice one @jeyrella! xD I missed that haha

**Comment by Keader** [comment]
i'm taking over @Rushor , it's a spell issue ^^

**Comment by Keader** [comment]
fixed.
now will follow item description
