### ISSUE TITLE
[Raid] Sartharion's Twilight Realm (1 to 3 drakes up)

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#5159]
**Links:** https://wowwiki.fandom.com/wiki/Sartharion
https://www.youtube.com/watch?v=iJJ4hhL9DU0
https://www.wow-mania.com/armory/?npc=31204
https://www.wow-mania.com/armory/?npc=31214
https://www.wow-mania.com/armory/?npc=31218
https://www.wow-mania.com/armory/?spell=58766
https://www.wow-mania.com/armory/?npc=31219
https://www.wow-mania.com/armory/?spell=58835

**What is Happening:** Currently, [Sartharion](https://wowwiki.fandom.com/wiki/Sartharion)'s Twilight portal remains empty during the entirety of the fight, and a big part of the mechanics of each of Sartharion's Lieutenants are missing due to this. The "portal" section of the lesser dragon mechanics listed below is the part that's currently missing. The raid messages/announcements happen, but the mechanics related don't.

**What Should happen:**
![image](https://user-images.githubusercontent.com/34783736/100308272-01eeb680-2f76-11eb-906a-f749c11dd3a2.png)

1. Upon landing, 30s into the encounter, Tenebron should start hatching [Sartharion Twilight Eggs](https://www.wow-mania.com/armory/?npc=31204) inside the twilight realm, which eventually spawn [Sartharion Twilight Whelps](https://www.wow-mania.com/armory/?npc=31214), which will phase into the physical realm and attack players after a certain delay, if left alive. Around [2:25](https://youtu.be/iJJ4hhL9DU0?t=145) in the video linked, we clearly see the wave of Whelps spawning from the portal, since the eggs were ignored in their strategy.

2. Upon landing, 75s into the encounter, Shadron should spawn an [Acolyte of Shadron](https://www.wow-mania.com/armory/?npc=31218) inside the twilight realm, which will apply [Gift of Twilight](https://www.wow-mania.com/armory/?spell=58766) to Sartharion, making his breath hit significantly harder, and rendering him immune to damage until the Acolyte is dealt with.

3. Upon landing, 120s into the encounter, Vesperon should spawn an [Acolyte of Vesperon](https://www.wow-mania.com/armory/?npc=31219) inside the twilight realm, which will apply [Twilight Torment](https://www.wow-mania.com/armory/?spell=58835#see-also) over the raid frequently, until the acolyte is dealt with.

The debuffs and acolytes mentioned in points 2 and 3 are explained around [3:01](https://youtu.be/iJJ4hhL9DU0?t=181) in the video.

**Comment by Oganku** [comment]
Noticed that the acolytes (not the eggs) actually spawn inside, but they die when their corresponding drake dies, which makes them mostly irrelevant, which is also not intended.

**Comment by Rushor** [comment]
so the only thing that must be fixed is that the acolytes should not die when the drakes die?

**Comment by Rushor** [comment]
alcolytes should no longer die if drake die at least now

**Comment by Oganku** [comment]
Acolytes and eggs still die when their respective drakes die, which should not happen. 
[Eggs](https://www.wow-mania.com/armory/?npc=31204) for [Tenebron](https://www.wow-mania.com/armory/?search=tenebron)
https://www.wow-mania.com/armory/?npc=31218 for [Shadron](https://www.wow-mania.com/armory/?npc=30451)
https://www.wow-mania.com/armory/?npc=31219 for [Vesperon](https://www.wow-mania.com/armory/?npc=30449)

The Acolytes/Eggs themselves behave fine, and do respawn periodically and use the correct spells while alive.

https://www.wow-mania.com/armory/?spell=61248, https://www.wow-mania.com/armory/?spell=58105 and https://www.wow-mania.com/armory/?spell=61251 are properly applied to the raid, but should fade once the respective drake does die. (Tenebron, Shadron and Vesperon respectively). Should be an aura debuff tied to the respective drakes.

@Rushor

**Comment by Rushor** [comment]
okay now the tempsummons should no longer despawn/die when the drake dies

**Comment by Oganku** [comment]
Acolytes, eggs and whelps work perfect. Just the powers remain even when the drakes die. 

* https://www.wow-mania.com/armory/?spell=61248, https://www.wow-mania.com/armory/?spell=58105 and https://www.wow-mania.com/armory/?spell=61251 are properly applied to the raid, but should fade once the respective drake does die. (Tenebron, Shadron and Vesperon respectively). Should be an aura debuff tied to the respective drakes.

**Comment by Rushor** [comment]
try now, aura should now be removed from all on death of dragon
