### ISSUE TITLE
[Raid] Blood quarter trash door is found closed after crash/restart

### ISSUE THREAD

**Issue by jeyrella** [WoWManiaUK/Redemption#5162]
**Links:**
https://www.wow-mania.com/armory/?object=201376

What is Happening:
If the server restarts or crashes after door to Blood Quarter is opened, then the door is found to be closed again with no way to reopen.
Probably related to #4229 
Causes GM tickets and halts raids.

Also reports that if the pack of NPCs immediately before that door is killed on the stairs in front of the door, then it also fails to open (to be tested)

What Should happen:
Once door is opened by killing trash, it should remain open for that instance, regardless of server restarts.

**Comment by wow-mania** [comment]
Not really a priority though.

**Comment by svijetlo** [comment]
it can be as it makes pointless tickets after server crash or reset and i see lot of ppl QQ how server big cos them to lose quest and waste time cos GM could not respond insta on ticket

**Comment by Rushor** [comment]
Will fix tomorrow

**Comment by svijetlo** [comment]
yes i just tested it you kill trash in front of doors rly fast and close to doors it wont open every time

**Comment by Keader** [comment]
Fixed
