### ISSUE TITLE
[Spell] Campfire "corpses"

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#5163]
**Links:**
![image](https://user-images.githubusercontent.com/34783736/100485337-9f103300-30cd-11eb-9076-0487561b9740.png)

**What is Happening:** If a player spawns a campfire using spell 818, a small stone with a tiny hitbox will remain after it disappears 5 minutes later. These stones persist until server restarts and can eventually clog rather significantly areas (at least visually). It's even possible to get stuck on them when running on flat ground!

Also, these corpses still grant their aura (Cozy Fire ID#7353) until server restart. 

**What Should happen:** Campfires should fully disappear after 5 minutes.

**Comment by Keader** [comment]
fixed
