### ISSUE TITLE
[Spell] Crusader Aura Affecting Dismounted Character After Taxi Flight

### ISSUE THREAD

**Issue by DaedalusAxios** [WoWManiaUK/Redemption#5164]
When booking a flight from one flight master to another and using Crusader Aura after getting on a gryphon / hippogryph, the aura will not affect the gryphon / hippogryph -- as is intended. However, after landing and while Crusader Aura is still active, my dismounted character has the 20% movement buff even though the aura should only affect mounted characters. The 20% movement buff persists when I mount my Charger and disappears after dismounting; but if I do not mount my Charger at all, and continue to run, my character will have the 20% movement buff.

https://www.wowhead.com/spell=32223/crusader-aura

**Comment by jeyrella** [comment]
Confirmed.
https://youtu.be/qSYQjh2eDWY
This happens with or without talent Pursuit of Justice specced.  Only occurs when crusader aura is selected mid-flight, not when it is active before the flight.
https://youtu.be/WjwQ5-5arpU

**Comment by Keader** [comment]
fixed.
