### ISSUE TITLE
[Mount] Red Flying Cloud doesn't fly in Azeroth

### ISSUE THREAD

**Issue by santa9631** [WoWManiaUK/Redemption#5165]
**Links:**
https://wow-mania.com/forum/viewtopic.php?f=13&p=938#p938
https://www.wow-mania.com/armory/?item=89363

**What is Happening:**
Apparently the Red Flying Cloud doesn't work in Azeroth, and only works in Northrend and Outland. I would assume it was overlooked as it isn't listed on the list of Azeroth flyable mounts as either able to fly in Azeroth or not.

**What Should happen:**
The Red Flying Cloud should work in all respectable flying zones and not just Northrend and Outland. Since it's technically a Mist of Pandaria mount and was thus added after the addition of flying in Azeroth.

**Comment by svijetlo** [comment]
i can confirm it will not fly in Azeroth but as it is not on list but it is 310% speed i would leave this one to @wow-mania  to sort out

**Comment by jeyrella** [comment]
@santa9631 By design, not all custom mounts fly in Azeroth, regardless of which retail patch in which they were introduced.  There are a large number that deliberately are not set to be flyable in Azeroth.

This is Janitor's call; if he says yes, we will assign a dev.
