### ISSUE TITLE
[Quest] Congratulations! @ Zul'Drak

### ISSUE THREAD

**Issue by JackieNL** [WoWManiaUK/Redemption#5166]
**Links:**
https://www.wow-mania.com/armory/?quest=12604

**What is Happening:**
I did the full quests in less than 20 minutes for getting the greater rewards quest: Congratulations!.

**What Should happen:**
It should still applies the aura or give me a follow up quest: Congratulations!.
![wow-mania 2020-12-01 15-11-54](https://user-images.githubusercontent.com/75321257/100755021-05f25c80-33ec-11eb-931a-16f7324e0cb6.png)
![wow-mania 2020-12-01 15-28-24](https://user-images.githubusercontent.com/75321257/100755035-0985e380-33ec-11eb-8ae2-5f18184f95f2.png)

**Comment by Oganku** [comment]
I do remember doing those dailies a few times and having both instances of it working and not working. So it probably has to do with conditions on the aura https://www.wow-mania.com/armory/?spell=51573#used-by-npc. Maybe it's limited to a too small zone and gets removed if you stray a little. Not 100% sure

**Comment by Rushor** [comment]
the conditions are:

Der Spieler hat eine Aura von [On Patrol]
Der Spieler hat keine Aura von [On Patrol Heartbeat Script]

https://www.wow-mania.com/armory/?quest=12604

can we find a way to reproduce it?

**Comment by Oganku** [comment]
Did the quest once and it worked fine, but maybe it has to do with it being a daily quest. I have to wait until reset to test again.

**Comment by Rushor** [comment]
if i have the aura, i can take the quest fine https://i.imgur.com/wAzAb9A.jpeg

Condition for the quest to take is. that you have aura https://www.wow-mania.com/armory/?spell=51573 and you do not have aura https://www.wow-mania.com/armory/?spell=53707

**Comment by Rushor** [comment]
Fix for it was this: https://github.com/TrinityCore/TrinityCore/commit/45c911ba94ab7f6f2952241191df258238c49035

**Comment by Oganku** [comment]
I'm not able to replicate it without more info :(
