### ISSUE TITLE
[Quest/NPC] Quest Suntara Stones 3367 - Dorius Stonetender has typo in script text

### ISSUE THREAD

**Issue by jeyrella** [WoWManiaUK/Redemption#5169]
**Links:**
Quest: Suntara Stones 3367
NPC: Dorius Stonetender 8284

**What is Happening:**
Dorius Stonetender says: It's on! $n, meet my fists. Fists, say hello to $n.

**What Should happen:**
Dorius Stonetender says: It's on! <creature_name>, meet my fists. Fists, say hello to <creature_name>.

**Comment by Rushor** [comment]
text should get the target now

**Comment by Rushor** [comment]
fix uploaded

**Comment by jeyrella** [comment]
Having trouble getting him to say this line at all now.  In 4 repeats of the escort quest, doesn't seem to say it when entering combat any more. 
Not sure if there's something wrong, or it's pure chance?  Referred back to Rushor.

**Comment by Rushor** [comment]
okay now it should always get the name

**Comment by jeyrella** [comment]
Yup.
![image](https://user-images.githubusercontent.com/46089380/101367455-17c97900-389e-11eb-94f1-3541f6bbbb3e.png)
![image](https://user-images.githubusercontent.com/46089380/101367482-1dbf5a00-389e-11eb-871c-8a1416ebdff4.png)
