### ISSUE TITLE
[NPC]  Target dummies in Mall area too close to wall

### ISSUE THREAD

**Issue by jeyrella** [WoWManiaUK/Redemption#5170]
**Links:**

**What is Happening:**
Parctise Targets in the Mall area are so close to the wall that rogues and cats cannot get behind them.  This is important as much of their combat abilities _require_ they be behind the target.
![image](https://user-images.githubusercontent.com/46089380/101244571-37766b00-36ff-11eb-8383-5cbe34f874eb.png)

**What Should happen:**
The npc_training_dummy mechanicals should be moved out from the wall by a few yards so that players can get behind

**Comment by Rushor** [comment]
okay will change the position

**Comment by Rushor** [comment]
jani fixed it

**Comment by Oganku** [comment]
Fixed, but one of them is a little off the line all the others are on. Still much better for backstabbers. :P 

![Dummies](https://user-images.githubusercontent.com/34783736/101265452-b0cc8880-3714-11eb-9c03-f9d7e414d013.png)
