### ISSUE TITLE
[Item] Feral-Cat: Idol of the Crying Moon procs on Rip

### ISSUE THREAD

**Issue by jeyrella** [WoWManiaUK/Redemption#5171]
**Links:**
Item:  https://www.wow-mania.com/armory/?item=50456
Rip:  https://www.wow-mania.com/armory/?spell=49800
Item proc spell:  https://www.wow-mania.com/armory/?spell=71174
Aura:  https://www.wow-mania.com/armory/?spell=71175

**What is Happening:**
[Idol of the Crying Moon](https://www.wow-mania.com/armory/?item=50456) procs "Agile" on using Rip ability
https://youtu.be/6K9I-QD-8Hk

**What Should happen:**
Idol of the Crying Moon should only proc on Lacerate and Rake
![image](https://user-images.githubusercontent.com/46089380/101244980-af459500-3701-11eb-834f-5e17aca13ac5.png)

**Comment by Rushor** [comment]
try now

**Comment by jeyrella** [comment]
Fixed.
- [x] Rip no longer procs Agile
- [x] Rake and Lacerate still proce Agile
https://youtu.be/dIRVdnRbUu4
