### ISSUE TITLE
[Spell] Master of Elements gives extra mana

### ISSUE THREAD

**Issue by jonathan5er** [WoWManiaUK/Redemption#5172]
**Links:** https://www.wow-mania.com/armory/?spell=29077

**What is Happening:** If you make crit with this talent your mana gained will be given two times from the talent... first time is good but second is extra... It is a small amount of mana given from second time but it should not be there

**What Should happen:** This talent should give mana only one time after critting with spell

**Comment by Keader** [comment]
![image](https://user-images.githubusercontent.com/7120913/101283242-f55d3000-37b7-11eb-95f3-1c9b84a371fc.png)

i can confirm in ptr lul

**Comment by jeyrella** [comment]
Partially  fixed 
![image](https://user-images.githubusercontent.com/46089380/101291551-873d5b00-3801-11eb-86e7-36c58eb0871c.png)
![image](https://user-images.githubusercontent.com/46089380/101291553-8dcbd280-3801-11eb-88de-6f034cb21c62.png)

However Arcane spells do not seem to be affected by Master of Elements at all....  separate issue?
![image](https://user-images.githubusercontent.com/46089380/101291898-02077580-3804-11eb-814c-738afd0f410d.png)
![image](https://user-images.githubusercontent.com/46089380/101291902-06339300-3804-11eb-8bd5-b0407ce6a89a.png)

**Comment by jeyrella** [comment]
Perhaps because of this not implemented?
![image](https://user-images.githubusercontent.com/46089380/101291940-40049980-3804-11eb-95d5-cc56a82591a1.png)

**Comment by jeyrella** [comment]
Nope.  this is not an issue on live.
![image](https://user-images.githubusercontent.com/46089380/101291979-7e9a5400-3804-11eb-9b38-77cd6f724864.png)

**Comment by jeyrella** [comment]
Ok.  separate issue.  original issue is fixed
