### ISSUE TITLE
[Raid] High Priest Thekal mechanics - Zul'Gurub

### ISSUE THREAD

**Issue by Bubunya** [WoWManiaUK/Redemption#5173]
**Links:**

**What is Happening: I guess while you've been fixing Thekal's after fight combat mode, you fixed whole mechanic of fight too 'cos it's not a fight "burn them down and loot" anymore :)))) Anyway, here is a few bugs still here. First is a healing/res mode. Like it was on retail servers, in wotlk you were able to place your pet at the entrance of the room, MD Thekal ONLY to your pet, FD, adds will run back, you deal with Thekal, who will receive NO HEAL (details below). Then it simple tank-n-kill fight. How it works now - MD, FD, just out of curiosity was able to kite Thekal almost half way across ZG - he still received heal from Lor'Khan who is waaaaay away and still res in phase 1 instead of phase 2 tiger/man form.

![WoWScrnShot_112620_232952](https://user-images.githubusercontent.com/53129632/101269324-dde06180-373b-11eb-9463-1e456c1dd0fd.jpg)

 However if keep a fight in normal mode (down to 20% and then burn them out) 1/2 times they will all res in full health at phase one instead of just Thekal in tiger form in phase 2.

![WoWScrnShot_120520_185141](https://user-images.githubusercontent.com/53129632/101269301-b8535800-373b-11eb-88da-a2d2a1facaeb.jpg)

Btw, based on log changes on discord "High Priest Thekal no longer leaves everyone in a fight even after he's dead." dunno what you've been trying to fix, but instead of fixing combat mode you fixed whole fight. And you WILL BE in combat mode after he dies :) 

![WoWScrnShot_120520_185326](https://user-images.githubusercontent.com/53129632/101269306-c1dcc000-373b-11eb-86d7-8be2d05d4bcc.jpg)

Another way was to get fight long enough till Lor'Khan drained out of his/her mana. Then no heal and fast kill. Not working on this server - his/her mana bar always full
 **

**What Should happen: At classic raid strategy was to separate Thekal from his two adds Lor'Khan and Zath, spread them across the room so Zath can't silence main tank and Lor'Khan is out of range to cast Great Heal on Thekal and Zath. Then as usual take them down to 15-20% and burn them out for a phase 2. Few years later when WOTLK came out there was few ways to solo Thekal, most of them pain in butt 'cos strategy was same as classic raid - get them down to 20% and then burn them out. There was few tricks to push Thekal to the second phase without killing all three of them first. One of that trick was able to do as a hunter. You need to place your pet at the entrance of this room, run to Thekal and MD only him to your pet. Then FD, so Lor'Khan & Zath will turn into passive non-combat mode and, most important, Lor'Khan WILL NOT be able to heal Thekal 'cos of the distance between two adds (they will run back to starting area) and Thekal. The rest of the fight is just between you. your pet and Thekal. You burn him down, he turns to the second phase, burn him down again, end of fight. Thats how I run him on retail till 4.0.1. 
Another way was to get fight long enough till Lor'Khan loose all his/her mana.**

**Comment by Rushor** [comment]
Can you Split all the Bugs in Single points pls

**Comment by Bubunya** [comment]
Sure.

How it was on retail:
Raid tactic always was separate Thekal and his two ads in that room, so Lor'Khan will not be able to heal Thekal & Zath and it's gonna be kind of easy fight to put them down within 10 sec. In WOTLK, based on this tactics, there was a solo tactics for different classes, one of them was based on withstand damage till Lor'Khan drained out of mana, then no heal ---> get them to 5% and burn down. Other techniques was based on hunter class. You placed your pet at the entrance of the room, run to Thekal, MD only him on your pet, ads will agro on hunter, hunter will FD and ads will run out of combat and back to start location. That is it, they are out of picture. Your pet tank Thekal at the entrance, no heal from Lor'Khan, he will die and res in second phase in form of tiger. Then tank & spank. End of fight.

How it works right now on mania server:
Yes you can pull only Thekal out to the entrance.
Problems is he will receive heal from Lor'Khan - not all the time but will.
AND after he is dead, he will res full health in his human form. meaning fight start over again.
No matter how far I kite him from room, he will res again and again.

How it was on retail:
Other techniques was based on outstand all damage till Lor'Khan will run out of mana.
Then no heal, get them down to 5% and burn it.

How it works on mania server:
Lor'Khan will NEVER run out of mana.
Lor'Khan mana bar always full

How it works on retail:
You kill all 3 of them within 10 sec, phase 2 starts.

How it works on mania server:
there is at least 1/3 chance that after they all down they will res all together full health and start phase one again.
My last kill it took me 3 times to get to phase 2. And only because Lor'Khan stop healing for more that 20 sec.

How it works on retail:
Fight is over, you are out of combat

How it works on mania server:
Based on log changes on discord "High Priest Thekal no longer leaves everyone in a fight even after he's dead."
Well, instead of fixing this you fixed whole fight. Before it was tank & spank fight without any phases or such, you burn ads down, they are running back to start location with 0 health (or die, it was random), then boss and we are done.
Now it looks more like pain in the butt retail fight, but very bugged one (read above)

**Comment by Bubunya** [comment]
Finally found one of the videos. Not much of them left, even on youtube, not even mention most popular back them hunter's portals, 95% of them are gone.. But this will show you how it use to work 'till ZG was swiped as a raid in Cata. 

[https://www.youtube.com/watch?v=zGmNgW-idd0](url)

**Comment by Bubunya** [comment]
Some updates.
I've been trying few different techniques today.
Mount up, ride to the boss and ads, ride out of the room.

How it use to work retail:
All 5 of them - boss, ads and 2 tigers - will follow you.
Half way to entrance two ads will leave combat and run back to the start area, Thekal, however, will follow you all the way to the entrance, then drop out and you have to agro him - or his two tigers - again right away, so he will engage fight again and then turn into second phase.
Please keep in mind I am not sure if "mount run in - run out" techniques was fixed before 4.0.1 or not.
However.
How it works on mania:
They will agro and then they will follow you no matter how far you are going.
Same problem like with single Thekal pull - they have no limit on location to stop agro, they just simply following you.
So even if "mount up" techniques was fixed in 3.3.5/before 4.0.1 there still a problem with agro.

Then I've been trying to do hunter pull few times in order to make sure it's not working 100%
It's not. So as you can see on video in previous post that's the way it should work.

However I've managed to find a way to solo it anyway, by kiting Lor'Khan away all the time and keep her in frost trap, while my bear dealing with Thekal and Zath. While Lor'Khan ina  trap, I am helping my pet with dps, then kite'n'shoot again, till Lor'Khan down to 'bout 5%, frost trap, dps down to 5% Thekal & Zath, pet on passive mode, run to Lor'Khan, pet on agro, MD, BW & all cd's, AoE then down. And it works.
SO please, PLEASE! If you going to fix don't ruin at least this way to get them down...

BTW, I was still on combat mode after fight was over and boss was looted....

**Comment by Oganku** [comment]
Can confirm the phasing not properly happening and having to re-do phase 1 quite often. 
Also the adds don't drop aggro separately from the boss as seen in video above.
Combat bug persists after their death also.
Last one where boss gets healed infinitely I haven't tested just yet, but could soon™.

**Comment by Bubunya** [comment]
> 

> Last one where boss gets healed infinitely I haven't tested just yet, but could soon™.

Oganku, it wasn't "infinitely healing", he did received heal way away from  Lor'Khan, but it works randomly, which is indicated bug in script. But problem was his res - even with ads dropped combat mode and he is all the way back to snake boss he will res in phase 1 and restart fight all over again. 
So two problems -  infinitely res full health in phase one and abnormal agro area.

Question - should I make other tickets 'bour bosses and hunter pets? Even in ZG on Bloodlord Mandokir "raptor" boss - damage scaled WAY too high, I can prove it with old videos of people running this boss with 17K health and pet received moderate damage ---> I am running in extreme solo spec with max pet agro/health and pet at 38-39K and sometimes it's hard to keep it alive. And I didn't start to run heroics BC places yet...  
I mean I don't want you guys keep busy with old contest, but at some points it connected with WOTLK too, especially with pets problems - path, movement etc etc. Pet acting weird in half of the boss fights in old world and BC,

**Comment by jeyrella** [comment]
@Bubunya we are currently giving focus to renovating older content; you may have seen our project around Sunwell Plateau.  So, yes, if you see documentable issues with other bosses then do make tickets, and we can take a look.
I would ask though that you try to keep explanations to bullet point forms, makes it easier to understand the issue :)

**Comment by Bubunya** [comment]
> 
> 
> So, yes, if you see documentable issues with other bosses then do make tickets, and we can take a look.
>
Oh boy... You asked for it :)))))) MC, here we come....

**Comment by Rushor** [comment]
i need clear advice to fix single point for this issue - else this consumes too much of my time

**Comment by Bubunya** [comment]
> 
> 
> i need clear advice to fix single point for this issue - else this consumes too much of my time

Watch video I've linked before. 
That's how it suppose to work - Thekal will agro, adds will be off combat, Thekal will die and will res in second phase.
How it workls on mania - he will die and will res in first phase and reset fight. Over and over again, no matter how many times he was killed.
At least can you fix this issue?
There is a lots of other issues with this fight in specific and whole ZG bosses in general.

**Comment by Rushor** [comment]
well for me it always worked when i did it like that:

bring all 3 creatures on 2 percent HP > call all at once > adds will stay dead > boss will transform to tiger > kill tiger > profit

**Comment by Rushor** [comment]
Thekal comes with 2 named humanoid adds (Zealot Lor'khan and Zealot Zath) and 2 tigers. The 2 humanoid adds are a shaman and a rogue. Thekal initiates the fight in priest form, where he can mortal strike. If any of the adds or Thekal dies, the remaining ones will resurrect them. This means all 3 must die simultaneously (within a 10 second window). 

https://wowwiki.fandom.com/wiki/High_Priest_Thekal

After dying once, Thekal respawns as a Tiger. 

This is how it worked for me

**Comment by Bubunya** [comment]
Works where and when? On Mania server? few months ago fight was as easy as trowing kitchen trash - kill the adds, they will turn green and run back to beginning area (hut), then kill boss. And he never turned into tiger.
Then - based on patch notice - you've been trying to fix after fight combat mode - which is, as a matter of fact, still exist! - and instead "fixed" whole fight to look like blizz-like.
Problems with killing all 3 of them within 10 sec was confirmed as an issue, you have to kill them few times till it clicks and Thekal will turn into phase two. I've been explained everything before - this and other bugs -  so no reason to go thru all of it again.
Video I posted earlier was from RETAIL.
Not mentioned there was 4 (four) ways to solo kill this boss on retail and all was legal.

I don't really understand meaning of your post, to be honest.
I am one click away from 50th birthday and been around not only at the time on vanilla beta, when players was able to build their own houses, an idea Blizz took from Ultima Online (half of Blizz team, and I use to know some of them back then, use to play it), but back at release of original warcraft, not mention other games like wolfenstein castle and such. And yes, I do know how this fight works, 'cos on retail I was proud owner of this tiger (tho raptor never drops on me)
All ZG is one big huge bug, if you ask me.
Some bosses in favor of players - like was Thekal, like panther or snake boss, other is pain in a a butt to solo - monkey, bat, spider bosses, even raptor is glitching,  and of cos Hakkar, which bugged as hell but soloable - tho soloable by crasiest way I can even imagine.
Same with MC and most Outland places. And I wasn't at half Old World and Outland places yet.

And as I said before, I can prove all bugs, can open tickets on each boss, can show you that some hunters pets and they talents are bugged on this server - but once again, if you care most only 'bout late game contest and top dps thingies, then we have nothing to talk 'bout 'cos it will "...consumes too much of my time..." to fix it and mine trying to prove that is bugged.

**Comment by Rushor** [comment]
>Problems with killing all 3 of them within 10 sec was confirmed as an issue

where was this confirmed as issue? in https://wowwiki.fandom.com/wiki/High_Priest_Thekal i find the 10 second source there

**Comment by Rushor** [comment]
Things i am gonna inspect and trying to fix now:

1) Heal of the Adds should not be possible if Adds are too far away from the boss
2) Clearn combat on death of thekal

That's the ay issues should be reported :) 

Simple clean points, no wall of texts - thanks

**Comment by Bubunya** [comment]
Wall of text was the explanation of all other issues - including issue with killing them all 3 within 10 sec NOT always triggering second phase (in some fights they need to be killed 2-3 times), which was told half a dozen times and confirmed by Oganku, but you keep sharing wowwiki link 

![phase_one](https://user-images.githubusercontent.com/53129632/102082778-877cbe00-3de0-11eb-816f-53f89d9dd286.jpg)

Bossed being pulled away from adds - as shown on video - will/may occasionally received some health (in my case one fight he was healed all the way passed Snake boss room, it could be just one fight glitch) BUT 100% for sure he will res over and over again no matter how far away he is from his room/adds, or he is IN his room? and reset phase one - which is another and most annoying bug. Video shows how it use to be on retail, not a bug but classic techniques for hunters pulling out bosses in lots of dungeons. So pulling boss away from adds should work and he should die alone and trigger phase two.

SO without explanation and all "walls of text" my next post here will be short and clean, right on point:
 1. Fight not working
 2. Boss not dying

No wall of text, you are most welcome.

**Comment by Rushor** [comment]
Okay 2 adjustments so far for this boss.

* Adds can now only cast the heal spell within 15 yards to the boss (previous the range was 100 yards)
* All players should be outfight once boss was killed after Phase 2 (Tiger)

**Comment by Rushor** [comment]
The issue about the ressurection is that i need a video or clear reproduction.

I tested it, i killed all 3 units within 10 seconds. All 3 in the time frame of 10 seconds and the second phase always started for me.

If you could make a video showing me how it bugged that would help aswell - or someone of the testers

**Comment by Bubunya** [comment]
Thanks a bunch for your help!
For res I can only show screenshots, which is not good enough in a case of 3-kill.
But other screens at least will show of Thekal permanent res on pulling him out of add pack and that his and his add's agro covered  - my wild guess - whole ZG, instead of dropping it out of room, they will follow you all around this place.

Btw, question. There is a some pet abilities that is bugged two. It won't be easy to explain it in two words, talking 'bout spec, gear buffs and result. Should I open bunch of other tickets regarding all those issues or I can summ them and send directly to you?

**Comment by Rushor** [comment]
one issue - one ticket 

if they are similar, do it in one ticket. like maximum 3 issues of one boss in one ticket

it would be nice if you can report some other issues about other raids aswell. i know the old ones need to be improved

pet/class/spell issues can also be reported and can be assigned directly to @Keader

**Comment by Bubunya** [comment]
Thanks a bunch again. So in order to report pet issues I should open ticket here but mention Kaeder or I can contact him directly let say thru Discord?
Sure I can do almost full report on MC (aside of Rag but once again pet issue) and the rest of ZG bosses, but need pet bugs to be fixed to try another places. I'll try and run other places, even 5 man, on my baby hunter to see all bugs as well.

**Comment by Rushor** [comment]
if you raise the ticket, we will assign him to fix it

it helps us always if you provide links to the database and videos - thanks in advance

**Comment by Oganku** [comment]
@Rushor 

- [x] Combat properly clears upon boss death

- [x] Thekal isn't getting healed when far away anymore

- [ ] I don't know exactly how to replicate it, but it happens often enough to have happened 3 times in a row on my first recording. I believe it might be when you kill the 2 adds too fast, and it fails to register as dead? You can see the corpses following Thekal even. https://imgur.com/a/twyH781

- [ ] As for the last issue, here is how it is. [This first video](https://www.youtube.com/watch?v=jYfiDq9YTcw) actually explains each steps to reproduce the trick, and around 0:40, when his adds despawn, you see the ress visual, indicating he starts phase 2. He then proceeds to kill him to get loot. Notice how even though the boss looks like a troll, he is not using his phase 1 Mortal Strike, and is using his tiger form Force Stomp, indicating that he is indeed in phase 2. [This second video](https://www.youtube.com/watch?v=AGWgo30I-Ac) shows the same trick, again in wotlk, but this time the boss correctly visually becomes a tiger when he phases after his adds despawn. Same trick, same behavior.
Then we have the [video linked above](https://www.youtube.com/watch?v=zGmNgW-idd0), from early cata. The tricks still works, but it seems as though you have to kill him twice now, since he does not automatically phases once his adds despawn. This isn't how it should be in 3.3.5 though.
Now here is how it is on PTR: https://imgur.com/a/S53GcB2 and https://imgur.com/a/7Rfheau (I cut the first one early cause of time limit, but basically you get an infinite loop of phase 1, where the boss never goes to phase 2 or dies)

**Comment by Bubunya** [comment]
Oganku, thanks A BUNCH for your help.
Yes, that is exactly how it works right now on live.
BUT! I have to agree to disagree about 

**_"Then we have the video linked above, from early cata. The tricks still works, but it seems as though you have to kill him twice now, since he does not automatically phases once his adds despawn. This isn't how it should be in 3.3.5 though."_**

That was exactly how it was in 3.3.5
As a proof - look at date.
Video was posted Apr 16, 2010
Patch 3.3.5a was June 29, 2010
And pre-Cata patch 4.0.1 was October 12, 2010

So video was made even before fix patch 3.3.5a.
And that's the way I use to kill them till last day before 4.0.1 when RNG gods stop laughing on me and tiger drops.

**Comment by Rushor** [comment]
The thing we can add here is that thekal will no longer Endless revive of the adds are Not close to him and let him join Phase 2. Everything Else seems to be to much potential for further Bugs.

Would that be fine?

**Comment by Rushor** [comment]
Sorry that i did Not got that directly - understood it know. Working on it tomorrow :)

**Comment by Oganku** [comment]
Would be perfect for point 4.

**Comment by Bubunya** [comment]
If that's what I thought it is - then yes, it will perfectly works as close to retail as possible :)
Thanks a bunch Rushor & Oganku for all your time and efforts.
ZC's other bosses, here we go next...

**Comment by Rushor** [comment]
Point 3 i guess we cannot fix because timers are too close together then

Point 4 i added that boss will not resurrect in phase 1 if he cannot find the both adds within 80 yards range.

This means if Thekal is more than 80 yards away from both adds (no matter if they are alive or dead), Thekal will instantly go to phase 2 upon first death

https://i.imgur.com/roOlZTo.jpeg > first death boss beeing more than 80 yards away from adds > https://i.imgur.com/jUXWrPM.jpg boss instantly goes to phase 2

**Comment by Rushor** [comment]
@Bubunya we are ready for you next issues :)
