### ISSUE TITLE
[PVP] paladins judgement (any kind) doesn't remove the stacks of unholy dk's bone shield

### ISSUE THREAD

**Issue by k00r** [WoWManiaUK/Redemption#5174]
**Links:**
Bone Shield:  https://wow-mania.com/armory/?spell=49222

**What is Happening:**
paladins judgement (any kind) doesn't remove the stacks of unholy dk's bone shield

**What Should happen:**
any kind of judgement should remove one stack of bone shield

**Comment by jeyrella** [comment]
![image](https://user-images.githubusercontent.com/46089380/101280260-0742d100-37c0-11eb-8a2c-9de9e400dd14.png)

**Comment by Rushor** [comment]
if you provide a source for that behaviour we will reopen the issue. thanks

**Comment by Keader** [comment]
proc system issue.
fixing it.
