### ISSUE TITLE
[PVP] priest shadow resistance buff doesn't stack with paladins shadow resistance aura

### ISSUE THREAD

**Issue by k00r** [WoWManiaUK/Redemption#5175]
https://www.wow-mania.com/armory/?spell=48170

**Comment by jeyrella** [comment]
This is not an issue
https://wowwiki.fandom.com/wiki/Resistance
![image](https://user-images.githubusercontent.com/46089380/101280480-36a60d80-37c1-11eb-994d-f8ea1ba2d80e.png)
