### ISSUE TITLE
[Spell/Mage] Burnout

### ISSUE THREAD

**Issue by Keader** [WoWManiaUK/Redemption#5176]
**What is Happening:**

Talent description: 
Description: Increases your spell critical damage bonus with all spells by $s1% **but your non-periodic spell criticals cost an additional $s2% of the spell's cost**.

This effect was not working.  Non periodic spells always have no extra cost.

**What Should happen:**

Non Periodic crit spells should get extra cost and appear in combat log.
Like:
![image](https://user-images.githubusercontent.com/7120913/101287385-c0a8a300-37ce-11eb-98a4-30efed86fe1d.png)

![image](https://user-images.githubusercontent.com/7120913/101287414-ea61ca00-37ce-11eb-9326-1c830af32c56.png)

I found it while fix https://github.com/WoWManiaUK/Redemption/issues/5172
approved by janitor

**Comment by jeyrella** [comment]
Nice catch

**Comment by jeyrella** [comment]
tested as part of #5172
