### ISSUE TITLE
[NPC/RP] Kalecgos missing from Kil'Jaeden's encounter

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#5177]
**Links:** https://wowwiki.fandom.com/wiki/Kil%27jaeden_(tactics)
https://www.wowhead.com/npc=25319/kalecgos#comments

**What is Happening:** Kalec is completely missing and Anveena is kind of talking to herself.

**What Should happen:** Kalecgos should be flying above the boss from phase 3 (85%) onward and speaking exchanging dialogue with Anveena. He also informs the players of the state of the blue dragonflight orbs and provides immersion in the fight. These are all the voice lines used by him during the encounter: 
![image](https://user-images.githubusercontent.com/34783736/101291075-382d0100-37d4-11eb-878a-9cefe54858e1.png)
**Note that Anveena's line in their exchange work fine, but Kalec's are missing.

**Comment by Rushor** [comment]
the creature is not spawned, the reason why the instance cannot access him

**Comment by Oganku** [comment]
Can he be spawned? It's this NPC: https://www.wow-mania.com/armory/?npc=25319

https://www.wowhead.com/npc=25319/kalecgos#sounds

**Comment by Rushor** [comment]
yes will add that he is static spawned and only visisble once fight started + at the end

**Comment by Rushor** [comment]
fixed, kalegos will now appear once all 3 hand of receivers have been killed, this will enable all his texts for the orbs and for his girl
