### ISSUE TITLE
[Event] Sunwell Plateau epilogue missing

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#5178]
**Links:** https://wowwiki.fandom.com/wiki/Sunwell_Plateau_epilogue
https://www.youtube.com/watch?v=4rlPMan2HGQ

**What is Happening:** After defeating Kil'Jaeden, nothing special really happens.

**What Should happen:** A long RP epilogue providing lore and stuff should happen after KJ's death. The wiki link above shows all the dialogue, and the video shows the event itself. It is purely cosmetic however.

**Comment by Rushor** [comment]
will add that the event will trigger 25 seconds after the death of the boss

**Comment by Rushor** [comment]
fixed. whole outro event added
