### ISSUE TITLE
[Raid/Dialogue] Kil'Jaeden's voice lines overlapping

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#5179]
**Links:** https://wowwiki.fandom.com/wiki/Kil%27jaeden_(tactics)

**What is Happening:** Kil'Jaeden is currently very talkative and he will periodically say the following voice lines during the entire time players are in the raid: 
![image](https://user-images.githubusercontent.com/34783736/101291187-d620cb80-37d4-11eb-8171-9acb9b71e158.png)
 
Even after engaging KJ, he will keep using those voice lines, weaving them between his regular phase-related dialogue. 

**What Should happen:** KJ should only use the 5 lines shown above prior to engaging him, and probably only after M'uru has been defeated. It's very strange to hear KJ spam those lines all the way from the entrance, or while doing anything in the instance.

**Comment by Keader** [comment]
why not include it in current openned issue?

**Comment by Oganku** [comment]
Cause one is regarding Kalecgos missing entirely + his voicelines. The other is an epilogue event and I felt that one was different.

I could've put them all together but I dunno. 🤷

**Comment by Rushor** [comment]
on it just right now, leave it like that, is better overview for me

**Comment by Rushor** [comment]
fixed, will only yell texts now if muru has been killed and if endboss fight has not been started yet
