### ISSUE TITLE
[Quest] Cave Medicine - Cave mushrooms don't respawn in Gimorak's Den - Storm Peaks

### ISSUE THREAD

**Issue by CuneraDiede** [WoWManiaUK/Redemption#5180]
**Links:**
https://www.wowhead.com/quest=13055/cave-medicine 

**What is Happening:**
While doing the quest 'Cave medicine' in Gimorak's Den (in The Storm Peaks) I needed to harvest 'Cave mushrooms'. 
After harvesting three of them, I got disconnected from server. Once I logged back in, I could no longer find the mushrooms in the cave. 
After raising an ingame ticket, Psygoa also wasn't able to respawn the mushroom, hence they suggested that I raised a ticket here. 

**What Should happen:**
A number of 'Cave mushrooms' should be visible in Gimorak's Den near the rocks in the cave while on the quest 'Cave medicine' 

**Quest copy**
"It's good to see a friendly face. Might be the last one I see.
One of those jormungar stung me with some sort of toxin before I managed to get away. I can feel my whole body getting numb, mon.
I'm going to need a toxin gland to make an antidote. I will also need some of the cave mushrooms that grow here... they'll slow the toxin down.
Hurry, please. I don't have much time."
Video of someone doing the quest can be found here: http://youtu.be/3oOnTmiUQRg

**Comment by Rushor** [comment]
testers and me will check

**Comment by Rushor** [comment]
okay that is strange in db it has 7 objects with id 300 and 5 minutes respawn time. can you may check again?

**Comment by svijetlo** [comment]
![WoWScrnShot_121120_095658](https://user-images.githubusercontent.com/61908373/101883816-13e87000-3b98-11eb-8828-e4b0dd5040e7.jpg)
![WoWScrnShot_121120_100057](https://user-images.githubusercontent.com/61908373/101883820-15b23380-3b98-11eb-8b15-e849a3be5c43.jpg)
![WoWScrnShot_121120_100209](https://user-images.githubusercontent.com/61908373/101883823-164aca00-3b98-11eb-9a09-8196de55f135.jpg)
sadly i can not reproduce this one , 
took quest 
went deep in cave to 1st mushroom, pick it up at 09:57
waited around 
at 10:02 mushroom came back 
i did try crashing my game , doing altF4 , reset my net so i get DC , giving up and reatke quest and crash etc and each time mushroom were back after 5 min
