### ISSUE TITLE
[Mount] Nightborne Manasaber miss sound

### ISSUE THREAD

**Issue by jonathan5er** [WoWManiaUK/Redemption#5181]
**Links:** https://www.wow-mania.com/armory/?item=156487

**What is Happening:** Mount from website shop does not have sound on /mountspecial... this is basically when u are standing still but press jump... mount does animation but is mute

**What Should happen:** Mount need to have sound dont know how to explain.... i find this video where he show mount https://youtu.be/RNdGTx-jfo4 at 59 second you can hear mount do this animation and sound

**Comment by wow-mania** [comment]
This won't be fixed until the next client update.
