### ISSUE TITLE
[Item] Thori'dal, the Stars' Fury drop rate 

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#5182]
**Links:** https://www.wow-mania.com/armory/?item=34334#dropped-by
https://www.wowhead.com/item=34334/thoridal-the-stars-fury#dropped-by
https://www.wowdb.com/items/34334-thoridal-the-stars-fury
https://eu.forums.blizzard.com/en/wow/t/legendary-bow-thoridal-the-stars-fury-have-you-seen-it-drop/122962
https://wow.gamepedia.com/Thori%27dal,_the_Stars%27_Fury

**What is Happening:** Thori'dal has a 3% drop chance according to the armory. 
![image](https://user-images.githubusercontent.com/34783736/101842311-c0cdd900-3b15-11eb-9825-09184906399e.png)
From: https://www.wow-mania.com/armory/?item=34334#dropped-by

**What Should happen:** Pretty much all sources online mention this bow having a 7% drop chance. Either the armory info is wrong and needs updated, or the actual drop rate is lower than it should.

[Wowhead](https://www.wowhead.com/item=34334/thoridal-the-stars-fury#dropped-by): 
![image](https://user-images.githubusercontent.com/34783736/101842370-de02a780-3b15-11eb-8ba7-ab3376fa8700.png)

[Wowdb](https://www.wowdb.com/items/34334-thoridal-the-stars-fury) (retail database): 
![image](https://user-images.githubusercontent.com/34783736/101842407-f5da2b80-3b15-11eb-814c-e75a01538d91.png)

Also, according to this [Blizzard forum](https://eu.forums.blizzard.com/en/wow/t/legendary-bow-thoridal-the-stars-fury-have-you-seen-it-drop/122962), the drop rate was never altered and it is just a fairly rare item. Patch notes for the item also mention no change in drop rate ever, making retail sources quite reliable for this.
![image](https://user-images.githubusercontent.com/34783736/101842539-43569880-3b16-11eb-92b2-ea5f94ede5bb.png)

**Comment by wow-mania** [comment]
Fixed and applied on live. Will take effect after the next restart.
