### ISSUE TITLE
Redemption server character bug

### ISSUE THREAD

**Issue by Zentez1** [WoWManiaUK/Redemption#5184]
**Links:**

**What is Happening:**
Downloaded full game, current version, questline checked, issue with or without addons, GM logged my account and suggests it's a character bug.
 
**What Should happen:**
NPCs in Orgrimmar are gone or when i teleport there, it was already fixed once by a GM but when i teleported again later it was the same problem..

**Comment by wow-mania** [comment]
Not a server issue.

**Comment by Zentez1** [comment]
> 
> 
> Not a server issue. You missed quest line.

what, the dk quest line? what should i do now? please explain the solution if you can

**Comment by jeyrella** [comment]
@Zentez1 this is an in-game issue;  raise a ticket in game, or go to Discord and use #make-a-ticket
