### ISSUE TITLE
[Quest] Seeds of Chaos - undead kills not counted when gryphon flies too far away

### ISSUE THREAD

**Issue by DaedalusAxios** [WoWManiaUK/Redemption#5185]
**Links:**
https://www.wowhead.com/quest=13172/seeds-of-chaos

**What is Happening:**
The quest allows me to talk to the Death Knight who gave me the quest and get an Ebon Gryphon which automatically flies around the quarry south-west of the Shadow Vault and allows me to throw bombs with which to kill undead. However, while I am able to kill undead and have it counted towards my total tally of up to 80 kills; whenever the gryphon would fly too far away from any undead I've killed with the bombs, it will not count them and the spawns will be wasted. This slows down the quest progress as I mentioned, the quest wants me to kill 80 Scourge.

**What Should happen:**
Any undead that belong to the quarry area south-west of the Shadow Vault should be counted even if killed by hand but especially with the bombs.

**Comment by Rushor** [comment]
good find. will fix that

**Comment by svijetlo** [comment]
yes i seen this happen on some other auto fly quests like that one where you throw spear at kraken in argent grounds if you fly to far even if you throw item hits do not count for quest

**Comment by Rushor** [comment]
should be more visible now and counter should be accessable more easy

**Comment by svijetlo** [comment]
it works now properly even if you you fly bit to far awey if bomb kills them you get the counts 
(forgot to make ss or vids )
