### ISSUE TITLE
[Spell] Replenishment - wrong values / wrong ticks

### ISSUE THREAD

**Issue by bLeyaa** [WoWManiaUK/Redemption#5186]
**Links:** https://www.wow-mania.com/armory/?spell=57669

**What is Happening:** The mana replenishment seems to be broken when it comes to how much it ticks and how often the ticks go. The discrepancy between the numbers at the moment is approximately mana worth: ~3x more; ticks count: ~17x less causing the overall numbers to be at least two times less depending on rng from what it seems and up to about five.

**What Should happen:** The ticks of replenishment should be constant and apparently more often. I will say, i dont understand why the Retail logs are showing the average mana gain so low as the 1% of maximum mana are the numbers shown in the Mania logs.

P.S. Raid from Mania logs had 4 Retribution Paladins and a Shadow Priest who apply the replenishment buff. For reference, in theory, only two Retribution Paladins would be enough for 100% uptime on all the mana users.

**_Logs for comparison (single character)_**

Retail: http://www.worldoflogs.com/reports/ikiublkprzh0pue1/details/18/?enc=kills (go to Buffs gained)
![image](https://user-images.githubusercontent.com/61625377/101993450-2e673a00-3cbb-11eb-8ce4-985d2ac7622f.png)

Mania: http://www.worldoflogs.com/reports/uwg0cqw1kkyeo7o5/details/2/?enc=kills (go to Buffs gained)
![image](https://user-images.githubusercontent.com/61625377/101993453-37f0a200-3cbb-11eb-84b6-e762a89922ad.png)

**_Also for entire raid_**

Retail: http://www.worldoflogs.com/reports/ikiublkprzh0pue1/spell/57669/?enc=kills
![image](https://user-images.githubusercontent.com/61625377/101993473-5f476f00-3cbb-11eb-9526-321d111a583a.png)

Mania: http://www.worldoflogs.com/reports/uwg0cqw1kkyeo7o5/spell/57669/?enc=kills (go to Power Gain tab)
![image](https://user-images.githubusercontent.com/61625377/101993489-725a3f00-3cbb-11eb-8ae7-5be533cb97cd.png)

**Comment by Keader** [comment]
try now pls

**Comment by svijetlo** [comment]
damn nice job i been collecting data for months on this(among other things) was still on it more or less
