### ISSUE TITLE
[Dungeon] Delrissa adds tend to evade on kiting - Magister's Terrace

### ISSUE THREAD

**Issue by Greywolf59** [WoWManiaUK/Redemption#5188]
**Links:**
https://wowwiki.fandom.com/wiki/Priestess_Delrissa
https://www.wow-mania.com/armory/?npc=24560

**What is Happening:**
The boss and mainly her additional ads tend to go into evade or leave combat which results in resetting the fight. For example they are often afraid to go into the shallow water near them
 Basically if they aggro anyone who is further away from them then their initial melee rsnge, mainly someone in or beyond the water there is a big chsnce for combat reset.
If wipe occurs the ads do not return to their initial positions thus bugging the fight further = even bigger chsnce for evade/combat leave.

**What Should happen:**
No clue what should happen exactly ( 0 retail experience) but pathing and evading is big issue on this fight. Also the ads not returning to initial position after wipe. Worth to look into.

**Comment by Rushor** [comment]
the water issue is pathing and inhabit related

the issue that they don't run back to homeposition is that reset is called upon evade and that instantly respawns the adds on the last combat position

**Comment by Rushor** [comment]
they will respawn inside the boss now. this is actually very strange to fix propperly because the respawnposition is not saved and we cannot access it. so we cannot do more here

**Comment by svijetlo** [comment]
this is as good it can get, i was not able to reset it now , while before it was easy to reset fight
