### ISSUE TITLE
group exp issue

### ISSUE THREAD

**Issue by Bladeadhunter13** [WoWManiaUK/Redemption#5189]
**Links:**

**What is Happening:**
Whenever I party with either of my friends on my druid I end up getting less exps from kills then either one of them. we would kill creature I would end up with 1/3 to 1/4 the exps that either of them was getting from the kill.

**What Should happen:**
we all get the same amount of exps from the kills.

**Comment by Oganku** [comment]
Experience depends on your difference in levels from the mob, and in group it gets a lot more complex. It also depends on each group member's level, and is not a simple division across them.

See: https://wowwiki.fandom.com/wiki/Formulas:Mob_XP
