### ISSUE TITLE
Getting disconnected when login into world with all characters

### ISSUE THREAD

**Issue by Shab00Za** [WoWManiaUK/Redemption#5192]
**Links:**

**What is Happening:**
After I login into the server I select my character and attempt to enter the world. I see the loading screen and when it finished I keep getting the "disconnected from server" message no matter which character I try to login with. Please assist

**What Should happen:**
Log me in and allow me to play. please.

Character names : Parcyloh, Whodashaman
Account name: Shab00Za

**Comment by Shab00Za** [comment]
![image](https://user-images.githubusercontent.com/76106472/102347452-1c321800-3fa9-11eb-9261-7770e67bd12c.png)

**Comment by Rushor** [comment]
Seems like Client issue

**Comment by svijetlo** [comment]
defiantly client issues there is pot of forum about this this does not belong here for sure
