### ISSUE TITLE
[Boss] Warchief Rend Blackhand

### ISSUE THREAD

**Issue by Greywolf59** [WoWManiaUK/Redemption#5194]
**Links:**
Boss: https://www.wow-mania.com/armory/?npc=10429
Gyth mount: https://www.wow-mania.com/armory/?npc=10339

**What is Happening:**
He has way more HP than is shown on his Health bar numbers.
Once warchief gets down and rides out on his mount Gyth we killed him but the gate out of the arena did not open.
I noticed copy of warchief still inside the spawn cage. We had to restart the dungeon. This time I waited for Warchief on Gyth to get out and quickly taunted his copy out of the spawn cage. This time the gate out of arena opened even before we killed any of the Warchiefs, it probably opened by taunting the copy out, into the arena and getting it into combat

**What Should (probably) happen:**
Warchief should not have so much "hidden HP" (over 100k for sure) and there should not be copy left after he mounts Gyth. After his death the gate out of the arena should open.
Also he is attackable while still on the balcony with Nefarian which I am not sure should be the case

**Comment by Rushor** [comment]
Doing some adjustement for him

**Comment by svijetlo** [comment]
i will test this will see how much i did to him and compare to his HP shown

**Comment by Rushor** [comment]
okay both gyth and rend will now have 60.000 HP this will make the encounter not a one hit show, but also not too complicated.

Previous all incoming damage was splitted a bit and could create some bugs.

The copy of Rend will now despawn as soon as gyth enters combat.

The rend from the balcony can also no longer be attacked

**Comment by Oganku** [comment]
Looks good
