### ISSUE TITLE
[Achievement] Fa-la-la-la-Ogri'la not triggered when using Preseved Holly (1282)

### ISSUE THREAD

**Issue by WhitephoenixTheBunny** [WoWManiaUK/Redemption#5195]
The achievement [Fa-la-la-la-Ogri'la](https://www.wow-mania.com/armory/?achievement=1282) require "_Complete the Bomb Them Again! quest while mounted on a flying reindeer during the Feast of Winter Veil._"

You can obtain the "Flying Reindeer Buff" by using [Preserved Holly](https://www.wow-mania.com/armory/?item=21213) or [Fresh Holly](https://www.wow-mania.com/armory/?item=21212), however, both will cast a diferent spell:
[Preserved Holly](https://www.wow-mania.com/armory/?item=21213) will cast [Festive Holiday Mount](https://www.wow-mania.com/armory/?spell=62061#used-by-item)
[Fresh Holly](https://www.wow-mania.com/armory/?item=21212) will cast Reindeer ([60%](https://www.wow-mania.com/armory/?spell=25858)/[100%](https://www.wow-mania.com/armory/?spell=25859)) or Flying Reindeer ([150%](https://www.wow-mania.com/armory/?spell=44824) /[280%](https://www.wow-mania.com/armory/?spell=44825) /[310%](https://www.wow-mania.com/armory/?spell=44827)) (the buff will be acording your riding skill).

ATM, the achievement _**only**_ will be tiggerd if you use [Fresh Holly](https://www.wow-mania.com/armory/?item=21212), and **both item should work**, as we can see in [wowheads comments](https://www.wowhead.com/achievement=1282/fa-la-la-la-ogrila#comments):
![image](https://user-images.githubusercontent.com/31921098/102461654-982b6f00-4040-11eb-8c5f-cfe4b0b6e8d0.png)
![image](https://user-images.githubusercontent.com/31921098/102461713-b3967a00-4040-11eb-8897-603a337c466a.png)

On a side note, and as improvement:
The achievement will be tiggered only using wotlk and pre-wotlk mounts, all (or most of ) the custom mounts will not tigger the achievement, if possible, make those also work there ;)

**Comment by Keader** [comment]
Please test now.

**Comment by svijetlo** [comment]
![WoWScrnShot_121920_124206](https://user-images.githubusercontent.com/61908373/102688541-ae2f6000-41f7-11eb-885d-59e1ce16ea35.jpg)
![WoWScrnShot_121920_124211](https://user-images.githubusercontent.com/61908373/102688543-b1c2e700-41f7-11eb-8a67-14d79cb03d4f.jpg)

![WoWScrnShot_121920_124215](https://user-images.githubusercontent.com/61908373/102688548-b4bdd780-41f7-11eb-8446-692919801d05.jpg)
work with custom mount and Preserved Holly
