### ISSUE TITLE
[Quest] "The Silver Covenant's Scheme" - Can't kill Silver Covenant agent - Battered Hilt Quest line on Horde Side

### ISSUE THREAD

**Issue by flyfrost** [WoWManiaUK/Redemption#5196]
EDIT:  Jey:  edited for clarity & completeness

**Links:**
https://wow-mania.com/armory/?quest=24557

**What is Happening:**
Cant Kill Silver Conevant agent

**What Should happen:**
Should be able to kill him, as the quest requires the item he drops.

**Comment by WhitephoenixTheBunny** [comment]
Can you provide a SS of the NPC please?

**Comment by WhitephoenixTheBunny** [comment]
@Rushor 
Maybe a side effect of https://github.com/WoWManiaUK/Redemption/issues/5183?

**Comment by Rushor** [comment]
Yes you can merge both issues, will refix and check all quest required nps aswell
