### ISSUE TITLE
Alliance Chopper few things about

### ISSUE THREAD

**Issue by jonathan5er** [WoWManiaUK/Redemption#5197]
**Links:** http://www.wow-mania.com/armory?spell=90000

**What is Happening:** I buy this mount with vote points on discount but i find few error with it

- [ ] chopper does not have any sound
- [ ] mount does only 1 kind /mountspecial
- [ ] mount is two seat and must be only one - for driver

also i see mount has name "Alliance chopper" if C should be big not small but it is not important just on side this i say

I find video with all this i mention up in here https://www.youtube.com/watch?v=iXfN3FmpBPY

**Comment by Rushor** [comment]
Mounts are manually ported here so they are not always exactly like on retail

**Comment by jeyrella** [comment]
This one, however, deserves attention, it definitely should not be 2-player at the least.

![image](https://user-images.githubusercontent.com/46089380/102685588-cabc9f80-41d9-11eb-95c0-46e4a8af4b55.png)

Also, [Horde chopper] has the same problems 
https://www.wow-mania.com/armory/?spell=90001
![image](https://user-images.githubusercontent.com/46089380/102685686-57675d80-41da-11eb-91ea-4992608956fa.png)


All 3 points are indeed confirmed, for both spells/items.

**Comment by wow-mania** [comment]
No change will be made on these. They have always been 1 seat.

**Comment by jonathan5er** [comment]
@wow-mania You missunderstand... is currently 2 seat bike.

i say it is supposed to be only one...
