### ISSUE TITLE
[NPC]  Glimmer Bay Orcas have lost their pathing

### ISSUE THREAD

**Issue by jeyrella** [WoWManiaUK/Redemption#5199]
**Links:**
glimmer bay orca https://www.wow-mania.com/armory/?npc=25204

**What is Happening:**
All the glimmer bay orca NPCs 25204 are no longer pathing.  Am almost certain they used to have this?
https://youtu.be/WkWCxBPrTtY

**What Should happen:**
Should have pathing

**Comment by svijetlo** [comment]
yes they were swimming around bay i did this few days ago and i think same that pathing is lost

**Comment by wow-mania** [comment]
I don't see any path on these. 
@Rushor can you add pathing to them, please.

**Comment by Rushor** [comment]
this is a issue with randommovement generator in deep water. will add pathing for them

**Comment by Rushor** [comment]
try now pls - if they still do not move i must add add single paths

**Comment by Rushor** [comment]
all orcas now have pathing
