### ISSUE TITLE
[Quest]  Mutiny on the Mercy

### ISSUE THREAD

**Issue by svijetlo** [WoWManiaUK/Redemption#5202]
**Links:**
https://www.youtube.com/watch?v=_ZfheZP46i4&ab_channel=GitGudGuides
http://www.wow-mania.com/armory?quest=11527
**What is Happening:**
yee there scrubby dogs, ones ye take the quest and venture to bowls of the rotting tub there is no skeleton mobs and barrels of blasting powder to be taken ,like seen in vid, it has been like this for some time now 
![WoWScrnShot_122120_112252](https://user-images.githubusercontent.com/61908373/102767180-7521f780-437f-11eb-9b5c-3ac0b98369a7.jpg)

**What Should happen:**
upon taking quest you go to bowls of ship to kill some skeleton mobs and pick up barrels of blasting powder

**Comment by Rushor** [comment]
try now pls

**Comment by svijetlo** [comment]
![WoWScrnShot_122120_174216](https://user-images.githubusercontent.com/61908373/102800267-eda2ab80-43b3-11eb-9544-871cbc0220e9.jpg)
![WoWScrnShot_122120_174107](https://user-images.githubusercontent.com/61908373/102800278-f09d9c00-43b3-11eb-9653-171985b47531.jpg)
![WoWScrnShot_122120_174123](https://user-images.githubusercontent.com/61908373/102800282-f3988c80-43b3-11eb-99be-8c76d28e6c73.jpg)
![WoWScrnShot_122120_174143](https://user-images.githubusercontent.com/61908373/102800290-f5fae680-43b3-11eb-93aa-459bd53fcaa2.jpg)

**Comment by GMMetaxa** [comment]
https://github.com/WoWManiaUK/Redemption/issues/4858

**Comment by GMMetaxa** [comment]
![image](https://user-images.githubusercontent.com/34750502/102817500-2d778c00-43d0-11eb-9b8c-97369ef7113d.png)
