### ISSUE TITLE
Improved Hunter's Mark talent not work

### ISSUE THREAD

**Issue by jonathan5er** [WoWManiaUK/Redemption#5203]
**Links:** https://www.wow-mania.com/armory/?spell=19423

**What is Happening:** When you have this talent and put mark on boss if other hunter use mark with no talent it overwrite it

**What Should happen:** Mark with this talent should not be removed by mark with no talent

https://wowwiki.fandom.com/wiki/Improved_Hunter%27s_Mark

**Comment by bLeyaa** [comment]
There is a same issue with Faerie Fire (Spell ID 770) and Faerie Fire Feral (Spell ID 16857) and Improved Faerie Fire (Spell ID 33602, 33601 and 33600).

The way it should be is that regular FF should have no effect other than proccing [Omen of Clarity](https://www.wow-mania.com/armory/?spell=16864) and the feral one should have that + damage/threat applied when in bear form without either of them overwriting the improved one.

**Comment by Rushor** [comment]
Is it really overwriting the effect or is it only visual issue?

**Comment by bLeyaa** [comment]
@Rushor Well, I have no idea about hunter's mark. I used it one time only but i saw the same thing as @jonathan5er posted, didn't test if its visual or not. 

As for Faerie Fire I'm 99% sure its NOT visual, as I've had spells miss on multiple occasions even though with FF I am 17%+

**Comment by jonathan5er** [comment]
Sorry i do not know

**Comment by Keader** [comment]
Fixed

**Comment by Oganku** [comment]
Works with either talent and/or glyph. :+1:
