### ISSUE TITLE
[Raid] Eredar Twins intro voicelines

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#5204]
**Links:** https://wowwiki.fandom.com/wiki/Eredar_Twins#:~:text=The%20Eredar%20Twins%2C%20Lady%20Sacrolash,of%20Rohendor%2C%20the%20Second%20Gate.

**What is Happening:** Lady Sarcolash and Grand Warlock Alythess currently play their intro dialogue exchange as soon as the first player enters the Sunwell Plateau instance. At this point, the bosses are way far from the players, and definitely out of sight, and them talking is quite strange and out of place.
![image](https://user-images.githubusercontent.com/34783736/102820947-1e7ae480-43a4-11eb-8944-f219966bd2eb.png)

**What Should happen:** Their intro dialogue should probably play as soon as the first player enters their room. (Change trigger)

**Comment by Rushor** [comment]
Gonna check that :)

**Comment by Rushor** [comment]
try now pls

**Comment by Oganku** [comment]
They don't play at the entrance, but they don't play the voicelines at all anywhere now.

**Comment by Rushor** [comment]
try now again pls

**Comment by Oganku** [comment]
Still no luck. The trigger should happen when you pass from area 1 to 2:
![image](https://user-images.githubusercontent.com/34783736/103469444-f50e7100-4d32-11eb-9051-929adc0a1c20.png)
![image](https://user-images.githubusercontent.com/34783736/103469448-ffc90600-4d32-11eb-8f78-2a6de2d0afca.png)

Area names are respectively Terrace of the Sun and Witch's Sanctum.

**Comment by Rushor** [comment]
okay just checked ths again. the event mus be bound to a trigger:

.go trigger 4937 (or.go areatrigger 4937)

when player walks over that trigger (as you said between to two subzones, the talk event should start)

**Comment by Rushor** [comment]
added that :)
