### ISSUE TITLE
[Quest] Chickens for Chicken Party! don't respawn

### ISSUE THREAD

**Issue by Xangretor** [WoWManiaUK/Redemption#5206]
**Links:**
https://www.wow-mania.com/armory/?quest=12702

**What is Happening:**
The chickens for Chicken Party! are not respawning. I have made several tickets to get the chickens respawned. I also waited for more then an hour, they just don't seem to respawn.

I also get weird rewards for picking up chickens. I pick up one and get rewarded with six chickens instead.

**What Should happen:**
The chickens should respawn.

**Comment by Rushor** [comment]
on ptr that seemed fine

**Comment by svijetlo** [comment]
https://github.com/WoWManiaUK/Redemption/issues/5120
https://github.com/WoWManiaUK/Redemption/issues/5151

will check it later if this keep up making problem we should see with jani and jayrella and remove all fixes and set it back to dumb state it was before

**Comment by jeyrella** [comment]
@Rushor Will give this one last try.  If we can't fix it properly we will have to revert it to the original state, as svijetlo suggests

**Comment by fushigi1984** [comment]
In my case, I was able to complete the quest but, after waiting a lot of time, maybe 20 minutes (it's a guess, but I mean, I've waited more than the normal time for something to respawn), I just tried next day and was able to get all the chicken. I don't know how much time it took for them to respawn, or if they did after a server restart.

**Comment by Rushor** [comment]
okay soo please with this fix, test if they respawn correct now after using.

i think the reason is the way the sripts are handled. first change phase > then despawn. not vise versa

**Comment by Rushor** [comment]
okay now if the npc has stopped and was "looted" it should instantly despawn and respawn after around a minute

**Comment by Xangretor** [comment]
@Rushor I will try this tomorrow, since I already did it today after the restart.

**Comment by jeyrella** [comment]
@Xangretor fixes are applied to testing realm first, not live

**Comment by svijetlo** [comment]
ones again on ptr it is fine , i leave it to jay to confirm it if he want to check it so it goes live

**Comment by jeyrella** [comment]
well I tried this and it seemed to work fine.  Like last time.  So....  again I guess mass public testing is the only way.  Put it in and see; we can always revert to the very first state.
