### ISSUE TITLE
[Quest] "Disclosure" central teleporter in Reliquary of Pain sends to lower chamber - Zul'Drak

### ISSUE THREAD

**Issue by Micio94** [WoWManiaUK/Redemption#5207]
https://www.wowhead.com/quest=12710/disclosure

Hello, I founded an issue withe the quest "Disclosure" in Zul'Drak. The problem is that the middle teleport of the Reliquary of Pain doesn't work properly, and it send me on the lower part of the place.

The function of that teleport is that it should have sent me on the upper chamber of the structure.

Thank you in advance

**Comment by Oganku** [comment]
The teleporters actually work, but they are reversed. The top portal sends you back to the ground, and the lower portal sends you upstairs. Should just have to swap them and it should be good. 👌

**Comment by jeyrella** [comment]
Yep, they are reversed.  https://www.youtube.com/watch?v=8dUexGT1ysA

**Comment by Micio94** [comment]
Ok, thank you...I'm going to check ^^

**Comment by Rushor** [comment]
try now pls, all teleports should be work correctly now to all positions:


Note: Upper Upper Teleport only works if plaxer has item: 39319 in inventory
