### ISSUE TITLE
[Spell] Warrior - Hard casting Slam does not pause swing timer

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#5209]
**Links:** https://www.wow-mania.com/armory/?spell=47475
https://wow.gamepedia.com/Slam
https://www.wowhead.com/spell=1464/slam#comments

**What is Happening:** Hard casting [Slam](https://www.wow-mania.com/armory/?spell=47475) currently does not pause the auto attack swing timer and allows you to fill any pause between 2 main abilities with hard casting a slam without getting punished whatsoever, since you still get the next autoattack as you should have anyways.

Evidence: https://imgur.com/a/mrKh8oo

In the clip linked above (from PTR), the warrior has no talents, and a weapon speed of 3.62, meaning one white hit every 3.62 seconds. I initiate a first white attack around 6 seconds into the clip. I then immediately proceed to hard cast 2 slams, which has a 1.5s cast time. Spending an entire 3 seconds casting slam, one would expect the following white hit to come about 3.62s + 3s after the initial one, however, nearly immediately after the second cast finishes, a second white hit occurs, proving that swing timer does not get paused whatsoever and keeps running in the background, disregarding the casting of slam.

**What Should happen:**
Casting slam should pause the swing timer instead of allowing it to still run in the background, making it generally a bad decision to cast in between main abilities (especially as fury, who do not have the improved slam talent).

- ![image](https://user-images.githubusercontent.com/34783736/103469289-ed4dcd00-4d30-11eb-9eca-8afdf8082c1a.png)
Slam used to completely reset the swing timer, but it was made a little more lenient at the start of wotlk by causing it to only delay the next swing instead.

- Multiple wowhead comments from 3.x.x mention this change on https://www.wowhead.com/spell=1464/slam#comments.

![image](https://user-images.githubusercontent.com/34783736/103469340-4d447380-4d31-11eb-896e-4ef68f3c0576.png)

![image](https://user-images.githubusercontent.com/34783736/103469327-43227500-4d31-11eb-87fa-1c15d4a38872.png)

- On quartz, the swing timer looks like it pauses, but when you start a hardcast < 1.5 sec before your next melee swing, you get that melee swing instantly as the cast ends.

- Having your swing timer paused while hard casting should eliminate any feasibility of hard casting Slam as Fury and somewhat diminish it as Arms. (Intended behavior of the swing timer pause) 
 However, it is currently actually optimal to fit as many hard cast slams as possible in between your more damaging abilities, regardless of spec or cast time, provided you have enough rage to do so.

**Comment by Greywolf59** [comment]
RIP Arms I guess heh.

**Comment by Keader** [comment]
fixed

**Comment by Oganku** [comment]
Tested for quite a while and it seems to work well, but it only pauses swing timer of main hand, so if you're dual wielding the offhand is still unaffected. Just need to apply the same thing to offhand and should be perfect. 👌

**Comment by Keader** [comment]
Added off hand too.
