### ISSUE TITLE
[Quest] Flown the Coop!

### ISSUE THREAD

**Issue by heitorsv** [WoWManiaUK/Redemption#5210]
**Links:**
https://www.wow-mania.com/armory/?quest=12532
https://www.wowhead.com/quest=12532/flown-the-coop
https://www.youtube.com/watch?v=w4vnsK8NW6g

**What is Happening:**
The chickens won't spawn/be released to be captured.

**What Should happen:**
Chickens should spawn/be released so the player can fetch and capture them.

I know there are similar Issues, but they are similar, not exact about this bug in this quest.
Thanks

**Comment by jeyrella** [comment]
duplicate #5206 , same core reason
