### ISSUE TITLE
[Quest] The Attack - typo in Tyrion's speech

### ISSUE THREAD

**Issue by jeyrella** [WoWManiaUK/Redemption#5211]
**Links:**
Quest ID: 434
NPC:  7766

**What is Happening:**
"Tyrion says: Wait here, Sn. "
![image](https://user-images.githubusercontent.com/46089380/103479624-e2de1280-4dc6-11eb-8220-1f5fe7dfbcd8.png)

**What Should happen:**
Should be "Tyrion says: Wait here, [player's name]. Spybot will make Lescovar

**Comment by Rushor** [comment]
fixed, player name should be displayed now
