### ISSUE TITLE
[RAID] Zul'Aman has incorrect entrance level requirement

### ISSUE THREAD

**Issue by womptista** [WoWManiaUK/Redemption#5213]
**Links:**

**What is Happening:**
Zul`Aman is a level 68 minimum raid instance. But it is telling level 68 players that they are to low of a level.

**What Should happen:**
Level 68 and above players should be able to enter the instance.

**Comment by Rushor** [comment]
Can you Provide a source (Video or link from old era) for that? :)

**Comment by bLeyaa** [comment]
I got you :)
https://wow.gamepedia.com/Zul%27Aman_(removed)

![Screenshot_20210104-111104_Samsung Internet](https://user-images.githubusercontent.com/61625377/103524290-973a7000-4e7d-11eb-8243-0f8296336d28.jpg)

**Comment by Rushor** [comment]
hmm that is the newer revision - in this case from 2010 we have different data https://wowwiki.fandom.com/wiki/Zul%27Aman_(original)?type=revision&diff=2155336&oldid=2146913

**Comment by Rushor** [comment]
Okay here we have final proof https://wowwiki.fandom.com/wiki/Instances_by_level?type=revision&diff=2147128&oldid=2146878

Should be level 68 min. https://i.imgur.com/3tLj4tm.png

**Comment by Rushor** [comment]
fixed on ptr
