### ISSUE TITLE
[Quest] Call of Water (alliance), npc despawn issue

### ISSUE THREAD

**Issue by Pektz** [WoWManiaUK/Redemption#5215]
**Links:**
Reference from retail:
https://www.youtube.com/watch?v=LiJN1fMnAv0&ab_channel=DanielDuRio
Quest:
https://www.wow-mania.com/armory/?quest=9508

**What is Happening:**
Water Spirits will not despawn after Tel'athion dies, blocking the quest for other players until the Spirits despawn (seems to take a long time).

**What Should happen:**
Water Spirits should despawn as Tel'athion dies.

**Comment by Rushor** [comment]
will fix this

**Comment by jeyrella** [comment]
confirmed.  https://youtu.be/ePjG5hfCdn0

**Comment by Rushor** [comment]
Fixed. On death of Tel'athion the Impure, the water eles will despawn

**Comment by jeyrella** [comment]
fixed. https://youtu.be/-Dv1JlqPrXg 
Also tested the event spawned both after completing and after abandoning.

**Comment by Rushor** [comment]
Thank you!
