### ISSUE TITLE
Pet disappearing during Algalon fight

### ISSUE THREAD

**Issue by bLeyaa** [WoWManiaUK/Redemption#5216]
**Links:** N/A

**What is Happening:** When entering the black holes to avoid the Big Bang mechanic, the pet remains outside and either dies to Big Bang or gets phased out and disappears.

**What Should happen:** Pet should phase into black hole together with the pet owner. Played warlock so can confirm for that class, not sure if it happens the same way for hunters.

Proof (both warlock PoV): 
https://youtu.be/Dvb2hTteZbs?t=219

https://youtu.be/X1xYP0ilx_o?t=113

For what it matters, the pet was Felguard from Demonology spec.

**Comment by Keader** [comment]
test now pls

**Comment by Oganku** [comment]
He follows when going in, but he does not follow when you get ported back out.

See: https://imgur.com/a/UU6wgxk

**Comment by Keader** [comment]
fixed xD

**Comment by Oganku** [comment]
Still happening 😕

**Comment by Keader** [comment]
now it's working ¬¬
