### ISSUE TITLE
[Quest] Stinky's Escape: error in Stinky's reaction speech - Dustwallow Marsh

### ISSUE THREAD

**Issue by jeyrella** [WoWManiaUK/Redemption#5217]
**Links:**
Quest ID: 1222

**What is Happening:**
When a hostile NPC attacks Stinky,  "Stinky" Ignatz says: Look out!  The <**player**_name> attacks!
![image](https://user-images.githubusercontent.com/46089380/103816102-5cdaf980-505c-11eb-8769-d83764f1282c.png)

**What Should happen:**
When a hostile NPC attacks Stinky,  "Stinky" Ignatz says: Look out!  The <**hostile_NPC**_name> attacks!

**Comment by jeyrella** [comment]
It might be true, but contextually it's nonsense.  Amusing though :)

**Comment by Rushor** [comment]
That is really funny haha

**Comment by Rushor** [comment]
try now pls, talktarget should be the victim now - else we must adjust the text manually

**Comment by svijetlo** [comment]
do not attack it next time pls

**Comment by svijetlo** [comment]
after talk with Jayrella , he say to reflag it as fix is don so npc does not say line **Look out ! The MOB-NAME attacks ! at all

**Comment by Rushor** [comment]
need a corefix then - as the other one we fixed

**Comment by svijetlo** [comment]
yes yes , jay told me same

**Comment by Rushor** [comment]
Those are the 4 texts that can happen

Look out!  The $n attacks!
I\'m glad you\'re here!  Because I need your help!!'
Help! I\'m under attack!
Help!  The beast is on me!

**Comment by Rushor** [comment]
should be good now. you may need some attempts to finally get that speech line from the 4 possible texts
