### ISSUE TITLE
[quest] Dun-da-Dun-tah!   Harrison Jones sometimes does not move

### ISSUE THREAD

**Issue by Sierbahnn** [WoWManiaUK/Redemption#5218]
**Links:**
https://www.wowhead.com/quest=12082/dun-da-dun-tah

**What is Happening:**
Harridon appears from the cage and then just stands there.

**What Should happen:**
Harrison should be commencing his exit from the ruins to complete the quest.

**Comment by Rushor** [comment]
If we can reproduce Wen can fix it

**Comment by Sierbahnn** [comment]
Yeah, I abandoned the quest and picked it up again, and then he started up. So it is intermittent, which is annoying.

**Comment by Rushor** [comment]
so it does not happen always hmm.

in db there is no cooldown set to start the action or sth like that

**Comment by Rushor** [comment]
fixed

**Comment by jeyrella** [comment]
reopening as #5252 reported

**Comment by jeyrella** [comment]
Players still reporting this is not working.  Yet on PTR it seems to work
Can we check the fix was properly transported?

**Comment by wow-mania** [comment]
Well we need to check on Redemption then. All fixes are 100% ported. PTR is always a copy of live after the update.

**Comment by Rushor** [comment]
okay then we need to check again. if we get a reproduce step for it  again we can fix it

**Comment by Rushor** [comment]
try again now and try to accept the quest over and over again.

. die and . respawn him several times

also try to take the quest at max interact distance. maybe that will be the reaosn for the bug
