### ISSUE TITLE
[Item] Whispering Fanged Skull trinket procs inside Frostmourne room

### ISSUE THREAD

**Issue by jonathan5er** [WoWManiaUK/Redemption#5219]
**Links:** http://www.wow-mania.com/armory?item=50342

**What is Happening:** When enter Frostmourne on HC mode this trinket proc from taking the damage on player

**What Should happen:** Trinket must only proc when damage is being done and not taken from other sources

**Comment by svijetlo** [comment]
what class and speck are you as i did not see this happen ?

**Comment by jonathan5er** [comment]
It is fury warrior

**Comment by bLeyaa** [comment]
I've had this happen as well on both rogue(assa) and warrior(fury). Happens with both normal and heroic version of the trinket.
Can probably clip it from one of my recordings if you cant reproduce it for some reason.

**Comment by Keader** [comment]
test now pls
