### ISSUE TITLE
[Event/Raid] Trial of the (Grand) Crusader roleplay after Twin Valkyrs

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#5221]
**Links:** I couldn't find actual evidence since most raid videos and guides cut the roleplay sequences.

**What is Happening:** After you defeat the Twin Valkyrs and talk to the npc at the entrance of the raid, a small roleplay event plays where the Lich King comes and breaks the floor. The event itself is fine, but there is an extra delay of about ~1 minute where nothing at all happens after you select the gossip option.

**What Should happen:** After selecting the gossip, the event sequence should play out without such a long pause.

**Comment by bLeyaa** [comment]
https://www.youtube.com/watch?v=UW7VjpglECc

**Comment by Rushor** [comment]
will change that

**Comment by Rushor** [comment]
try now pls. unneeded time is removed

**Comment by Oganku** [comment]
A lot better, but now the voice lines overlap by maybe a second or so. It's very minor, but does feel a little off if you actually pay attention. :P

**Comment by Rushor** [comment]
So increasing by 4 seconds should fix it?

**Comment by Rushor** [comment]
extended by 4 sec
