### ISSUE TITLE
[Item] Carrot on a Stick does not have any effect

### ISSUE THREAD

**Issue by jeyrella** [WoWManiaUK/Redemption#5222]
**Links:**
https://wow-mania.com/armory/?item=11122

**What is Happening:**
Equipping [Carrot on a Stick](https://wow-mania.com/armory/?item=11122) has no effect on mounted speed (on a toon under level 70 of course), whether equipped before or after mounting up.

**What Should happen:**
Mounted speed should be increased by 3% multiplied.
![image](https://user-images.githubusercontent.com/46089380/104093605-68f4d000-5283-11eb-8cbc-2f74b7bdf7cb.png)

**Comment by jeyrella** [comment]
evidence: https://youtu.be/4e1cXAGEnaI

**Comment by Keader** [comment]
fixed
