### ISSUE TITLE
[Item] Riding Crop does not have any effect

### ISSUE THREAD

**Issue by jeyrella** [WoWManiaUK/Redemption#5223]
**Links:**

https://wow-mania.com/armory/?item=25653

**What is Happening:**
Equipping Riding Crop has no effect on mounted speed (on a toon at or under level 70 of course), whether equipped before or after mounting up.

**What Should happen:**
Mounted speed should be increased by 10% multiplied.
However does NOT stack with Carrot on a Stick, Skybreaker Whip, or Mithril Spurs

**Comment by Keader** [comment]
fixed
