### ISSUE TITLE
[Item] Mithril Spurs item enhancement does not have any effect

### ISSUE THREAD

**Issue by jeyrella** [WoWManiaUK/Redemption#5224]
**Links:**
https://wow-mania.com/armory/?item=7969

**What is Happening:**
Equipping Mithril Spurs on a set of boots has no effect on mounted speed (on a toon at or under level 70 of course), whether equipped before or after mounting up.

**What Should happen:**
Mounted speed should be increased by 4% multiplied.
However does NOT stack with Carrot on a Stick, Riding Crop, or Mithril Spurs

**Comment by Keader** [comment]
fixed
