### ISSUE TITLE
[Item] Skybreaker Whip does not have any effect

### ISSUE THREAD

**Issue by jeyrella** [WoWManiaUK/Redemption#5225]
**Links:**
https://wow-mania.com/armory/?item=32863

**What is Happening:**
Equipping Skybreaker Whip has no effect on mounted speed (on a toon at or under level 70 of course), whether equipped before or after mounting up.

**What Should happen:**
Mounted speed should be increased by 10% multiplied.
However does NOT stack with Carrot on a Stick, Riding Crop, or Mithril Spurs

**Comment by Keader** [comment]
fixed
