### ISSUE TITLE
[Quest] Mutiny on mercy

### ISSUE THREAD

**Issue by heitorsv** [WoWManiaUK/Redemption#5226]
**Links:**
https://www.wow-mania.com/armory/?quest=11527
https://www.wowhead.com/quest=11527/mutiny-on-the-mercy
https://www.youtube.com/watch?v=_ZfheZP46i4

**What is Happening:**
Monsters are not spawning.

**What Should happen:**
Monsters should spawn player to collect the itens.

**Comment by jeyrella** [comment]
Check the other docked ship.
