### ISSUE TITLE
Deterrence deflect

### ISSUE THREAD

**Issue by jonathan5er** [WoWManiaUK/Redemption#5228]
**Links:** https://www.wow-mania.com/armory/?spell=19263

**What is Happening:** Deterrence spell has power to deflect Hammer of Wrath spell from paladin

**What Should happen:** Hammer of Wrath (this https://www.wow-mania.com/armory/?spell=48806) must hit hunter even with Deterrence spell

![image](https://user-images.githubusercontent.com/74667165/104351522-ca2bd600-5505-11eb-963f-73e1c2dad07c.png)

is no problem with Cloak of Shadows and Spell Reflect spells but is only Deterrence that have problem

**Comment by GMMetaxa** [comment]
No valid post. As is.

**Comment by jonathan5er** [comment]
what is no valid????? this very important in PVP!!
