### ISSUE TITLE
[Quest] [Spells] The Iron Colossus

### ISSUE THREAD

**Issue by Greywolf59** [WoWManiaUK/Redemption#5230]
**Links:**
Quest: https://www.wow-mania.com/armory/?quest=13007
NPC: https://www.wow-mania.com/armory/?npc=30301
https://www.wowhead.com/npc=30301/tamed-jormungar#abilities

**What is Happening:**
Jormungar can move when emerged.
There is no cooldown on abilities

**What Should happen:**
The worm should not be able to move when emerged.
There should be cd on its abilities (mainly acid spit).
I would also check mana costs.

**Comment by Rushor** [comment]
moving while emerged i cannot confirm https://gyazo.com/4fd67692986e8ef497d31e25e6d6c882

**Comment by Rushor** [comment]
ah i got it on first vehicle init, you can move with him, which should not happen

**Comment by Rushor** [comment]
fixed:

worm is now emegerd upon spawn
both abailities have a 2 sec and 6 sec cooldown now
mana cost will stay as is for now
