### ISSUE TITLE
[Quest] [NPC] Relief for the Fallen - Defender follows and does not engage in fight

### ISSUE THREAD

**Issue by Greywolf59** [WoWManiaUK/Redemption#5231]
**Links:**
Quest: 
https://www.wowhead.com/quest=12937/relief-for-the-fallen
https://www.wow-mania.com/armory/?quest=12937

NPC: 
https://www.wow-mania.com/armory/?npc=30036
https://www.wowhead.com/npc=30036/rejuvenated-defender

**What is Happening:**
Rejuvenated deffender is passively following you, not engaging in the fight. Not that I would actually complain (less time being stuck in combat).

**What Should happen:**
He should engage in fight, maybe be even aggressive. Some wowhead comment mentions rolling-like-a-hedgehog move too.

**Comment by Rushor** [comment]
try with next ptr restart

**Comment by Rushor** [comment]
added a ui for them, so you can control them and let them attack the victims
