### ISSUE TITLE
[NPC] [Quests] Xarantaur offers all quests without chaining

### ISSUE THREAD

**Issue by Greywolf59** [WoWManiaUK/Redemption#5232]
**Links:**
Quest giver:
https://www.wow-mania.com/armory/?npc=30381
Quests:
https://wow.gamepedia.com/The_Witness_and_the_Hero. (Progression part)

**What is Happening:**
Xarantaur currently offers all the quests at the same time so you can defeat the Northern Wind before even reading the scrolls and finding what is actually amiss.

**What Should happen:**
As logic and gamepedia suggest, these quest should be chained in progression and not opened all from the start.

**Comment by Rushor** [comment]
-- https://wow.gamepedia.com/Xarantaur
-- Questchain. Now works as follow:
-- All starts with 13426 Xarantaur, the Witness. 
-- After reward 13034 The Witness and the Hero becomes available
-- After reward 13037 Memories of Stormhoof becomes available
-- Next part
-- After reward of 13038 Distortions in Time the quest 13048 Where Time Went Wrong becomes available
-- After reward 13049 The Hero's Arms becomes available
-- After reward 13058 Changing the Wind's Course becomes available
