### ISSUE TITLE
[Quest] Krolmir, Hammer of Storms event broken, Thorim spawning after 2 mins

### ISSUE THREAD

**Issue by Greywolf59** [WoWManiaUK/Redemption#5233]
**Links:**
Quest
https://www.wow-mania.com/armory/?quest=13010
NPC
https://www.wow-mania.com/armory/?npc=30390

**What is Happening:**
The event does not run properly.
Thorim does not spawn, the Krolmir mace encased in ice neither.
King Jokkum repeats some of his replicas for 2nd time.

Edit: Thorim spawned post-event, after couple minutes of waiting

**What Should happen:**

**Comment by Rushor** [comment]
can confirm, thorim is not summoned https://i.imgur.com/rcqd7Zf.png

**Comment by Rushor** [comment]
issue is that Veranus is not active upon spawn and and will not start the script then

**Comment by Rushor** [comment]
fixed https://i.imgur.com/JDmCL3W.jpg
