### ISSUE TITLE
[Quest] Lupus Pupus not working correctly

### ISSUE THREAD

**Issue by Xangretor** [WoWManiaUK/Redemption#5234]
**Links:**
https://www.wowhead.com/quest=11728/lupus-pupus

**What is Happening:**
The wolfs drop the poop them selves without throwing the meat. They start as hostile, suddenly they turn neutral and then drop poop.

**What Should happen:**
You should first throw the meat to a wolf before they poop.

**Comment by Rushor** [comment]
added the missing elements

wolf will walk towards player, play emte, poop, run away and despawn (only happens one time on  spellhit)
