### ISSUE TITLE
[Nodes] Ore is respawning inside the node

### ISSUE THREAD

**Issue by theonykry** [WoWManiaUK/Redemption#5235]
**Links:**

**What is Happening:**
So are miner who farms ores, what you can do is: mine it and then dont autoloot it, just take the ore out and leave to node. After 5-45min you can go back to that node and mine it again and you will have a respawned random amount of ores in the node again. so basically you can leave nods of rare ores up, not fully clear them out and then just return to them. For example Titanium or Khorium ore. (tested it on all the Northrend Nodes there are, cobalt saronite and titanium)

**What Should happen:**
As far as i know the ore should not respawn inside the node itself. once you farmed it the whole node needs to respawn so that it carries some ore again. if its not a bug then i apologize.

**Comment by Rushor** [comment]
as is for now
