### ISSUE TITLE
[Raid/ToC] Incinerate Flesh (Lord Jaraxxus)

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#5236]
**Links:** https://www.wow-mania.com/armory/?spell=66237 (and 67049, 67050, 67051)
 

**What is Happening:** [Incinerate Flesh](https://www.wow-mania.com/armory/?spell=66237) currently counts current shields when calculating the amount of healing it will absorb, causing the effect to be completely nullified if a strong enough shield is already present. I feel like it sometimes also fails to apply when no bubbles are present, as if it had an inherent miss chance? 

**What Should happen:** Incinerate Flesh should always apply on its target, regardless of shields or whatever non-immunities may be present on them. It should only absorb following incoming heals up until the threshold at which it gets dispelled.

**Comment by jeyrella** [comment]
Feel?  Have you tested it?

**Comment by Oganku** [comment]
I'm not 100% sure what triggers it, but I know for sure it often fails to apply.

**Comment by Oganku** [comment]
Ok, so shields for sure prevent it from being applied, and maybe even a teeny tiny shield can block it. Just the presence of any absorb cancels it out. It should 100% apply regardless of shields on the target. If it fails to apply even after this, then I'll look into a potential second cause.

Evidence: https://imgur.com/a/1WINqj1
Incinerate Flesh would always get applied to the target at first, but once I shielded both of them with PW:S, it would give the voice line and game message that it was used, but would not afflict said target.

@jeyrella

**Comment by Keader** [comment]
test now pls

**Comment by Oganku** [comment]
https://imgur.com/a/2v0sGmY
