### ISSUE TITLE
[Raid/ToC] Gormok's Snobold Vassals

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#5237]
**Links:** https://www.wow-mania.com/armory/?npc=34800
https://www.wowhead.com/npc=34800/snobold-vassal#abilities;mode:h25
https://wow.gamepedia.com/Gormok_the_Impaler
https://www.youtube.com/watch?v=oEcCItDmIz0

**What is Happening:** 
1. [Snobold Vassals](https://www.wow-mania.com/armory/?npc=34800) are missing their abilities and are thus rendered close to completely harmless.

2. Upon dying, Gormok simply drops any remaining [Snobold Vassals](https://www.wow-mania.com/armory/?npc=34800) that haven't had the chance to be thrown (one every ~20s) to the ground. These snobolds simply stand still on the floor and don't do anything for the rest of the fight, or until killed.

**What Should happen:**
1. Snobold Vassals are supposed to have the last 3 abilities while latched onto players:
![image](https://user-images.githubusercontent.com/34783736/104797113-ae386680-5789-11eb-977f-1e40645c75d8.png)
*The first ability, [Rising Anger](https://www.wow-mania.com/armory/?spell=66636),, applies to the boss directly and works fine. 

These abilities exist on the armory but are just unused: [Head Crack](https://www.wow-mania.com/armory/?spell=66407), [Batter](https://www.wow-mania.com/armory/?spell=66408) and [Fire Bomb](https://www.wow-mania.com/armory/?spell=66313).

Snobolds should repeatedly kick their target's spellcasting with Batter, and stun them occasionally with Head Crack, both of which are currently missing. Their kick being on such a low cooldown, they can basically lock any caster out of a school of casting for the entire duration they're on them, and should be dispatched quickly for this reason. Snobolds riding the boss will properly throw bombs, but Snowbolds that are attached to players should continue throwing them periodically, adding an extra source of fire bombs for each Snobold alive.

2. I have seen one sentence that said they should spawn for each 20% of the boss' health that is lost, for up to 4 total. I could not find any strong evidence for this, but every guide video I have watched for Gormok has them spawning at those thresholds of 80-60-40-20% of boss' health. I do realize these videos generally take far longer to kill the boss, but it is odd that the spawns match the health thresholds across different videos. Otherwise, if spawn is kept the same, any extra Snobolds remaining on Gormok upon his death should despawn with him.

**Comment by Keader** [comment]
remaning snobolds, should attack raid after boss die.
Fixed :)

**Comment by Oganku** [comment]
- [x] Remaining snobolds attack players without latching onto them.
- [ ] Batter seems to be used by the snobolds regardless of whether their target is casting, and makes it fairly easy to still cast with one on you. They should reserve that ability for when you cast a spell and its low cooldown, added to its 5s school lockout should basically prevent casters from using any non-instant spells successfully. (Source: https://youtu.be/po9k71NjnE4?t=154 and other comments/guides) On PTR, [I could freely cast for nearly 12 seconds before getting interrupted ](https://imgur.com/a/xYBDVfa). I was interrupting my spells early to not pull aggro from the naked paladin, but could keep casting smite. Only around 15s into the clip do I finally get kicked and locked out of holy spells.
- [x] Head crack is used occasionally.

**Comment by Keader** [comment]
This script is sniffed, he should cast even if target is not casting.
