### ISSUE TITLE
Eye for an Eye Talent is Broken.

### ISSUE THREAD

**Issue by Tassann** [WoWManiaUK/Redemption#5242]
I have encountered an issue with the Eye for an Eye talent (I have noticed there was another incident with this that occurred on February 20, 2020 however this has since been "closed". 

I was in WSG battleground in PvE gear (I had left my PvP gear in bank on accident) and I casted Fire blast (which hit for 3000-4000 damage) and received this overkill.
![wtf](https://user-images.githubusercontent.com/77582845/104849911-54838980-58ba-11eb-9a07-2f5be925b379.jpg)
On the next encounter, I had casted frost nova (that hit for 1266 critical damage) and was hit with this overkill.
![wtf 3](https://user-images.githubusercontent.com/77582845/104849912-551c2000-58ba-11eb-863c-eeee8e7c4ea9.jpg)
This is a conversation I had with an in-game GM and the talent is included.
![okay](https://user-images.githubusercontent.com/77582845/104849913-551c2000-58ba-11eb-9493-f0ec424a3c28.jpg)

Although I do not feel I should have to say that this is broken, I feel that it should be understood the talent (at 2/2) will deal 10% of damage taken and it is capped at a maximum of 50% of the paladin's health. I have also talked with members of my guild who have said they were in PvP gear and were hit with overkills of 20M damage as well. 

This is quite bothersome as I was effectively unable to target or attack this player. While I am not saying this player was cheating - certainly this must be a bug and it ruined my experience in WSG.

I am happy to provide any further information should it be necessary.

**Comment by jeyrella** [comment]
Known, unfixable due to core.

**Comment by Keader** [comment]
without a reproduce steps is impossible to fix

**Comment by GMZinius** [comment]
> without a reproduce steps is impossible to fix

We have some repro steps for you @Keader 
Just checking on info given recently 😄 
I will re-open this when we have confirm the information we have

**Comment by Greywolf59** [comment]
Hello hello! I came to revive this thread :P.
Place of occurence: Naxxramas realm ToC 5man Heroic. Battle with mobs prior to Eadric/Paletress.
How it happened: One of the group of three was pulled. My fire mage Chava living bombed the mobs and started to cast Flamestrike. Argent Priestess MCed retri paladin with Eye for an Eye talent. As my Flamestriek went of, I instantly died. In about the same time the Living Bombs on mobs exploded. I have checked the Damage Taken by me on Skada and it was Eye for an Eye.
What triggered it: Either Flamestrike or Living Bomb exploding on one of the mobs and hurting the paladin. [Eye for an Eye](https://www.wow-mania.com/armory/?spell=25988) should react to criticals only. My only critical damage on paladin was one of the two [Living Bombs](https://www.wow-mania.com/armory/?spell=55360) exploding on mobs, thus it should be that, what triggered it.
Group composition: Two fire mages, one retri pala, one Blood DK tank, one Shadow Priest healing.

Damage taken by Eye for an Eye:
![damage taken](https://github.com/WoWManiaUK/Redemption/assets/41387450/f374a49f-741a-413b-80b4-aaeb1c14db7f)

Buffs on me during the WHOLE pull:
![My buffs](https://github.com/WoWManiaUK/Redemption/assets/41387450/950a9985-e2de-46cf-9dfd-5ceaa4840bbd)

Buffs on paladin during the WHOLE pull:
![paladins buffs](https://github.com/WoWManiaUK/Redemption/assets/41387450/7ffe4174-b3b1-4378-8fc9-86d3aa6943ea)

My Friendly Fire:
![my friendly fire](https://github.com/WoWManiaUK/Redemption/assets/41387450/d245d924-5e8d-4f52-9564-b12eb315c34a)

Paladin's Damage Taken:
![pala damage taken](https://github.com/WoWManiaUK/Redemption/assets/41387450/6a5a28fd-0fad-412b-a21f-b95a14c54cbd)
Note: Flamestrike 1 hit; Living Bomb 1 hit 1 crit

My gear:
![my gear](https://github.com/WoWManiaUK/Redemption/assets/41387450/d3868105-ef89-4ab1-99d2-c3dd725b2949)

Pala gear:
![pala gear](https://github.com/WoWManiaUK/Redemption/assets/41387450/ece19407-1b3b-4af1-9614-4431eff0250c)
Note: Some gear might changed, this screenshot was taken 20 minutes after the rhc ended (had to go afk), however as far as I know this player does indeed use rele set even in PvE.

Pala talents:
![pala talents 1](https://github.com/WoWManiaUK/Redemption/assets/41387450/cd18fd54-947f-4964-9e7b-ff7aee9c3b81)
![pala talents 2](https://github.com/WoWManiaUK/Redemption/assets/41387450/4211db45-c171-4f34-8458-d02bcc419386)
![pala talents 3](https://github.com/WoWManiaUK/Redemption/assets/41387450/67d2204c-0d17-4593-95ab-3e7a15976861)

My talents:
![mage talents 1](https://github.com/WoWManiaUK/Redemption/assets/41387450/98a464e7-6683-4189-829a-74694f14b83c)
![mage talents 2](https://github.com/WoWManiaUK/Redemption/assets/41387450/187a43e1-5719-4167-a66b-080bde471052)
![mage talents 3](https://github.com/WoWManiaUK/Redemption/assets/41387450/9d2ad2d8-fa99-4fb1-aaed-a52526a4b7b6)

My Glyphs:
[Living Bomb](https://www.wow-mania.com/armory/?item=45737), [Fireball](https://www.wow-mania.com/armory/?item=42739), [Molten Armor](https://www.wow-mania.com/armory/?item=42751), Slow Fall
Footnote: Molten armor was further boosted by using 2pt9 bonus at the start of the dungeon.

Paladin's glyphs: UNKNOWN
