### ISSUE TITLE
[Spell/Dungeon] Ymirjar Wrathbringer's Blight not jumping (Pit of Saron)

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#5245]
**Links:** https://www.wow-mania.com/armory/?spell=69603#used-by-npc (On normal)
https://www.wow-mania.com/armory/?spell=70285 (On heroic)
https://www.wow-mania.com/armory/?npc=36840#abilities

**What is Happening:** The [Blight](https://www.wow-mania.com/armory/?spell=69603#used-by-npc) disease applied by [Ymirjar Wrathbringers](https://www.wow-mania.com/armory/?npc=36840#abilities) in Pit of Saron never jumps to other players when it expires without being dispelled, no matter how close they are.

On this clip, I stand right on top of another party member with 2 applications of Blight, and when they end, neither jump to him: https://imgur.com/a/AWHDMTy

**What Should happen:** The Blight should jump to other nearby targets if it expires normally. Players should either dispel it to prevent the jump, or move away if they get infected. The armory or wowhead don't mention what max range it should spread to, but I suppose a range similar to that of [Necrotic Plague](https://www.wow-mania.com/armory/?spell=70337) would be reasonable. (I suppose there is a fixed value for any spell that mentions *nearby targets*)

**Comment by jeyrella** [comment]
This is important, as it is intended to be a training for the LK encounter Necrotic Plague spell

**Comment by Keader** [comment]
fixed

**Comment by Oganku** [comment]
On heroic, debuff 70286 does now jump, but randomly becomes 70285 when it does (probably intended?), and also jumps wayyy too far. You can be 50+ yards away from another player and it will still jump. I don't think this is what it means when it says 'nearby player'. 😛 

69603 becomes 69604 on normal, but also jumps from wayyyy too far.

**Comment by Keader** [comment]
Spell has 100 yards radius.
And id changes is controlled by dbc

**Comment by Oganku** [comment]
If your group has no way to dispel disease you'd get stuck with it bouncing endlessly unless someone goes over 100 yards away? That's bound to be problematic. Something has to be missing or something :/

**Comment by Keader** [comment]
Blame blizzard not me.
It's a disease, all healers has something to dispel it.

**Comment by Oganku** [comment]
Not druids :(

**Comment by Keader** [comment]
well, if your group dont have NO ONE to dispel it (paladin, priest, shaman) is not spell fault xD

**Comment by jeyrella** [comment]
@Keader What's the range on Necrotic Plague?

**Comment by Oganku** [comment]
Also from looking at old videos + comments on wowhead, the 'blue' version of blight (69604 and 70285) should not jump. Only the initial 'green' one does. (69603 and 70286)

> Note: This version does not spread and displays the second Wowhead tooltip: "Dealing Nature damage every 3 sec."

https://www.wowhead.com/spell=69604/blight#comments

**Comment by Keader** [comment]
> @Keader What's the range on Necrotic Plague?
not relevant.
It's not necrotic plague, so range of necrotic plague has 0 influence in this spell.


> Also from looking at old videos + comments on wowhead, the 'blue' version of blight (69604 and 70285) should not jump. Only the initial 'green' one does. (69603 and 70286)
> 
> > Note: This version does not spread and displays the second Wowhead tooltip: "Dealing Nature damage every 3 sec."
> 
> https://www.wowhead.com/spell=69604/blight#comments

Ok, removed the "second jump"

**Comment by Keader** [comment]
removed second jump
