### ISSUE TITLE
[Item] Tiny Abom in a Jar

### ISSUE THREAD

**Issue by malmakh** [WoWManiaUK/Redemption#5246]
**Links:**
http://www.wow-mania.com/armory?item=50706
http://www.wow-mania.com/armory?spell=71432

**What is Happening:**
Mote of Anger does not fade away when Tiny Abomination in a Jar is un-equiped. (I don't know how it works on other classes, I only have it on paladin)

![Screenshot (19)](https://user-images.githubusercontent.com/62926832/104905491-b8718500-5982-11eb-8e38-3b6a5e955f44.png)

A ticket was opened about this previsouly : #2079
It is marked as "Fixed on PTR - Tester Confirmer" but it's still not working on live server.

(I'm on patch 2.8.0)

**Comment by Keader** [comment]
fixed
