### ISSUE TITLE
Core/Spell: Creating items via spell will disappear if inventory is full

### ISSUE THREAD

**Issue by Kitzunu** [WoWManiaUK/Redemption#5247]
THIS ISSUE IS NOT RELATED TO https://github.com/WoWManiaUK/Redemption/issues/5249

Title description: When you use an item, like the one below, it casts a spell

**Links:**
I am not adding any links because it happens with all similar items as shown under how to reproduce, and this will require a generic fix.

**What is Happening:**
Currently, if you have a full inventory and try to convert an item into smaller, while having a smaller mat already. ie right-clicking Eternal Fire and having 1 crystalized fire in your inventory, it will convert into 9.

This is happening to spells with
SPELL_EFFECT_CREATE_ITEM
SPELL_EFFECT_CREATE_ITEM_2

This means you will lose one with the conversion. 

1 Eternal Fire -> 10 crystalized fire - 1 to fill the already existing one

**What Should happen:**
In this case, it should throw a "your bag is full" error and to prevent you from making it into smaller items and thereby you'll lose no mats.

This can be tested by this procedure:
1. .add 37702 11
2. Right-click the item to transform 10 into one big
3. fill your inventory with items so it is full
4. Click on Eternal Fire
5.  notice you will lose one crystalized fire

This bug was found 2021/01/19 on WoW-Mania 2.8.0 client

**Comment by GMMetaxa** [comment]
As is.

**Comment by Kitzunu** [comment]
It is an easy fix O.o

**Comment by Keader** [comment]
I can reproduce it using your steps, is valid.

**Comment by Keader** [comment]
fixed

**Comment by jeyrella** [comment]
https://youtu.be/FJbXOEiluBw
