### ISSUE TITLE
Core/Spell: Clams disappear if you have full inventory

### ISSUE THREAD

**Issue by Kitzunu** [WoWManiaUK/Redemption#5249]
THIS ISSUE IS NOT RELATED TO https://github.com/WoWManiaUK/Redemption/issues/5247

**Links:**
I am not adding any links because it happens with all similar items as shown under how to reproduce, and this will require a generic fix.

**What is Happening:**
Currently if you open a clam while your inventory is full you will receive the message "Your inventory is full" but the clam will still be consumed and your items will disappear. 

This affects spells that have SPELL_EFFECT_CREATE_RANDOM_ITEM which are as follows:

spellID | Name | Comment
-------|--------|--------
57844 | Darkwater Clam
58160 | Jaggal Clam
58165 | Big-Mouth Clam
58168 | Thick Shell Clam
58172 | Small Barnacled Clam
60445 | Dalaran Fountain Fishing | This is a QA spell and not the actual one used by dalaran fishing. Description: Simulates a single catch from the Dalaran Fountain.  Good luck!
61756 | Northrend Inscription Research (FAST QA VERSION)
61898 | Soft-Shelled Clam
64202 | Giant Darkwater Clam

**What Should happen:**
You should receive the "Your inventory is full" message as intended, but should also be restricted from opening it.

You can test this via this procedure
1. .add 45909
2. Fill your inventory with things
3. Use the clam
4. See that you get the message "inventory is full" and the clam won't be used.

This bug was found 2021/01/19 on WoW-Mania 2.8.0 client

<details><summary>Possible solution</summary>

SpellCastResult Spell::CheckItems()

```cpp
            case SPELL_EFFECT_CREATE_RANDOM_ITEM:
            {
                if (player->GetFreeInventorySpace() == 0)
                {
                    player->SendEquipError(EQUIP_ERR_INVENTORY_FULL, nullptr, nullptr, m_spellInfo->Effects[i].ItemType);
                    return SPELL_FAILED_DONT_REPORT;
                }
                break;
            }
```
</details>

**Comment by Keader** [comment]
will fix tomorrow morning, thanks

**Comment by Keader** [comment]
fixed

**Comment by jeyrella** [comment]
https://youtu.be/FJbXOEiluBw
