### ISSUE TITLE
[Quest] Long Forgotten Memories is not available on Anachronos after abandoning

### ISSUE THREAD

**Issue by sogan27** [WoWManiaUK/Redemption#5250]
**Links:**

**What is Happening:**
 im trying to get scarab lord title thats why im doing the quest chain but i took quest "long forgotten memories" (name) but when i tried to do this quest there was bug thats why i left this quest and tried to take it back again. when i left the quest i turn in back npc (anachronos in caverns of time) but i could not take becasue there is not quest in npc anymore. I need help about it. (it can be turn in quests bug because when i did wintergrasp quests i could not turn in there was not question mark in npcs,i left quests and took it back before)

**What Should happen:**
It happened to me again for different quest.they fixed it in game.

**Comment by Rushor** [comment]
will check what the conditions are

**Comment by Oganku** [comment]
You can't get that title anymore btw, cause the final part of the chain can only be completed within 24 hours of the first player doing it. You also won't get the mount.

**Comment by Rushor** [comment]
yeah true title and mount you will not get, but maybe there is indeed an issue with "long forgotten memories" that you cannot take it anymore once you abandon it

**Comment by Oganku** [comment]
I remember testing that quest before and I highly doubt it, but can double check.

**Comment by Oganku** [comment]
Whenever ptr is back...

**Comment by wow-mania** [comment]
ptr is up. just close it if it cannot be confirmed.

**Comment by Oganku** [comment]
This quest and the one that follows both can be re-taken just fine if you abandon them. You most likely abandoned 'A pawn on a Long Forgotten Board', which is given by the small red crystal near AQ gate if you drop it.
