### ISSUE TITLE
[NPC]  "Gnome Cannon Shooter #Ruaan" helper NPC visible in BEM

### ISSUE THREAD

**Issue by jeyrella** [WoWManiaUK/Redemption#5251]
**Links:**

**What is Happening:**

There is a "Gnome Cannon Shooter #Ruaan" floating in midair just outside of Toshley's Station in Blade Edge Mountains
Looks like a helper fake NPC as name is only  shown in GM mode but this one is actually visible.

Position: 1821.500000 5591.209961 269.221985.

![image](https://user-images.githubusercontent.com/46089380/105104365-003efc00-5aaa-11eb-9b52-01a3508a3bd4.png)
![image](https://user-images.githubusercontent.com/46089380/105104381-09c86400-5aaa-11eb-92be-ccfbde8de462.png)

```
NPC currently selected by player:
DB GUID: 76729, current GUID: 3448.
Faction: 35.
npcFlags: 0.
Entry: 21944.
DisplayID: 3441 (Native: 3441).
Level: 1.
EquipmentId: 0 (Original: 0).
Health (base): 42. (max): 42. (current): 42.
InhabitType: 3
Unit Flags: 33587200
UNIT_FLAG_UNK_15 (0x8000)
UNIT_FLAG_NOT_SELECTABLE (0x2000000)
Unit Flags 2: 2048.
Dynamic Flags: 0.
Faction Template: 35.
SpawnTime: Full:5m Remaining:0s
Loot: 0 Pickpocket: 0 Skinning: 0
InstanceID: 0
Phasemask: 1
Armor: 15
Position: 1821.500000 5591.209961 269.221985.
AIName:  ScriptName: 
Flags Extra: 2
CREATURE_FLAG_EXTRA_CIVILIAN (0x2)
MechanicImmuneMask: 0
```

**What Should happen:**
Should not be visible to non-GMs.

**Comment by Rushor** [comment]
is invisible for non gms now

**Comment by jeyrella** [comment]
The NPC itself is fixed, but stun effect hovering over his head is not.
![image](https://user-images.githubusercontent.com/46089380/105992214-bbfcbe80-609c-11eb-9c18-e29c1bc354b1.png)

**Comment by Rushor** [comment]
okay now should be good

**Comment by jeyrella** [comment]
fixed
![image](https://user-images.githubusercontent.com/46089380/106015774-b8763100-60b6-11eb-88a7-8387ee9ec875.png)
![image](https://user-images.githubusercontent.com/46089380/106015810-c035d580-60b6-11eb-90ba-5fc0cc7666b6.png)
