### ISSUE TITLE
[Quest] Dun-da-Dun-tah!

### ISSUE THREAD

**Issue by heitorsv** [WoWManiaUK/Redemption#5252]
**Links:**
https://www.wowhead.com/quest=12082/dun-da-dun-tah
https://www.wow-mania.com/page/armory
https://www.youtube.com/watch?v=kzWNML9eYJo

**What is Happening:**
NPC Harrison Jones doesnt move

**What Should happen:**
NPC Harrison Jones should move to be escorted out of the cave

**Comment by Rushor** [comment]
On ptr this works

**Comment by jeyrella** [comment]
closing as duplicate of #5218 which have reopened
