### ISSUE TITLE
[Quest] Exorcising the Trees - Blade's Edge Mountain

### ISSUE THREAD

**Issue by jeyrella** [WoWManiaUK/Redemption#5253]
**Links:**
Quest:  https://wow-mania.com/armory/?quest=10830
Exorcism Feather:  https://wow-mania.com/armory/?item=31518
Raven's Wood Leafbeard:  https://wow-mania.com/armory/?npc=21326
Koi-Koi Spirit:  https://wow-mania.com/armory/?npc=22226

**What is Happening:**
After killing the Koi-Koi Spirit, the Exorcised Leafbeard continues to attack the player.

**What Should happen:**
After killing the Koi-Koi Spirit, the Leafbeard is supposed to stop attacking and become passive and friendly (or possibly non-interactive so you cannot exorcise the same leafbeard again), as per the Feather:
![image](https://user-images.githubusercontent.com/46089380/105157974-63aa4780-5b05-11eb-82b3-01e71f992fb1.png)
![image](https://user-images.githubusercontent.com/46089380/105159858-7cb3f800-5b07-11eb-9bd6-b5302ceb8f1a.png)
![image](https://user-images.githubusercontent.com/46089380/105160005-a2410180-5b07-11eb-8fcc-8ef3766a426e.png)

There is no era relevant video evidence available, but it is very likely the behaviour had not changed much up to this one from 2013:
https://youtu.be/YfDnb271PKw?t=147

Also, once you complete the quest the Raven's Wood Leafbeards should turn Neutral as a whole, rather than aggressive
![image](https://user-images.githubusercontent.com/46089380/105160104-be44a300-5b07-11eb-89fa-354e4e5593c7.png)
![image](https://user-images.githubusercontent.com/46089380/105160350-0c59a680-5b08-11eb-9734-60b98409603e.png)

I think perhaps this is what https://wow-mania.com/armory/?spell=38665 is intended to do, but seems to have no effect.

**Comment by svijetlo** [comment]
not good still same , and it then let you do 5 spirits on one tree

**Comment by Rushor** [comment]
can you try again pls? for me it works - i use the item on them and it despawn - can only use it one time

https://gyazo.com/9f5aaec96e6d663a7b2e719a0852e22a

**Comment by svijetlo** [comment]
did work fine now good job , i know not what it couldbe before smt on my side
