### ISSUE TITLE
NPC Water Terror

### ISSUE THREAD

**Issue by Greywolf59** [WoWManiaUK/Redemption#5254]
**Links:**
Hey, no clue how to make square brackets on my keyboard. anw...
Water Terror - https://www.wow-mania.com/armory/?npc=30642
Mjordin Water Magus - https://www.wow-mania.com/armory/?npc=30632
Summon Water Terror - https://www.wow-mania.com/armory/?spell=7855

**What is Happening:**
Water Terror has fairly big aggro range, this issue was tackled once already with other pet mobs.  The main problem I see is the fact you can actually pull the Water Terror without also aggroing the Mjordin Water Magus

**What Should happen:**
Their threat tables should be most likely chained and aggro range of Terror might be a bit smaller.

**Comment by Rushor** [comment]
The Terror aggro range i cannot change sadly,

but once the Water Terror is pulled, the Mjordin Water Magus should be aggroed aswell now
