### ISSUE TITLE
NPC Ebon Blade Prisoner

### ISSUE THREAD

**Issue by Greywolf59** [WoWManiaUK/Redemption#5255]
**Links:**
Ebon Blade Prisoner - https://www.wow-mania.com/armory/?npc=30186  + ?npc=30194 + 30195 + 30196

**What is Happening:**
After me aggroing the Water Terror nearby the Prisoner just came out of his cage and attacked the Water Terror and then the Mjordin Water Magus. Water Magus was so shocked he got a seizure and keeps summoning new Water Terror over and over again while in process escaping the combat with Prisoner and thus healing himself to full. Neverending batle of the Prisoner and the Magus

**What Should happen:**
I doubt the prisoner should be able to escape the cage and attack the NPCs.

**Comment by Greywolf59** [comment]
To specify it: The Prisoner (male orc model iirc) left the cage twice. Always when I managed to aggro ONLY the Water Terror and fly up out of its reach but still being in combat with it. The cage with the Prisoner was right next to the Water Terror. So only pretty specific circumstances I suppose

**Comment by Rushor** [comment]
the ones in the cages should not attack by default now
