### ISSUE TITLE
[Quest] NPC Ebon Blade Prisoners

### ISSUE THREAD

**Issue by Greywolf59** [WoWManiaUK/Redemption#5256]
**Links:**
QUEST - https://www.wow-mania.com/armory/?quest=12982
Ebon Blade Knight - https://www.wow-mania.com/armory/?npc=30197 + 30198 + 30199 + 30200
                              - https://www.wowhead.com/npc=30200/ebon-blade-knight#abilities

**What is Happening:**
So, when locked in the cage as Prisoners these guys are pretty heroic, jumping out of cages to help in some special situations. Buit when they re freed and become your Guardians (link) they are just passively following you around. When some NPC attacks them (Magus with Frost Nova AoE) they do engage in combat, target the Magus but althoguht they are in battle position they do not attack.

**What Should happen:**
Well, I suppose they should help out and use the abilities assigned to them on wowhead.

**Comment by Rushor** [comment]
Thanks for those good reports man - that improves the game play :)

**Comment by Rushor** [comment]
the quest creatures should be able to attack now
