### ISSUE TITLE
Orc Racial Expertise

### ISSUE THREAD

**Issue by Greywolf59** [WoWManiaUK/Redemption#5259]
**Links:**
Hwy I am not ingame atm so no clue how it is called. I will fill in ihe links and names tomorrow moat likely.

**What is Happening:**
My Arms warr orc wielding 2h axe has +5 expertise visible on character sheet (25 total). Sometimes (rarely) upon entering RHC I see my expertise at 30 (namely Nexus). Upon "disequip expertise go to 20 (-10) and after reequiping it gets to usual 25. No clue if just visual or practical bug.

**What Should happen:**

The above should not happen. Expertise should stay at cureent expertise +5 with axes (20+5 = 25).

**Comment by Oganku** [comment]
Do you have any trandmogd on your weapon? Or a picture/video to show it happening?

**Comment by Greywolf59** [comment]
No transmog anywhere. No video, no picture. My laptop can't even handle well having wow and discord open at the same time lol. No video ever from me sadly.

**Comment by Rushor** [comment]
time for a new laptop :>

**Comment by Greywolf59** [comment]
Time for corona to end and finally get a job comes first haha

**Comment by Keader** [comment]
I cant reproduce.
Using those weapons:
![image](https://user-images.githubusercontent.com/7120913/105990546-61a23480-6081-11eb-8638-7df328f13186.png)

**Comment by Keader** [comment]
Let me know if we have a reproduce steps, then i can re-open it and fix.
