### ISSUE TITLE
[Quest] The Nightmare Manifests

### ISSUE THREAD

**Issue by Greywolf59** [WoWManiaUK/Redemption#5260]
**Links:**
Quest; https://www.wow-mania.com/armory/?quest=8736
https://wowwiki.fandom.com/wiki/Eranikus,_Tyrant_of_the_Dream
NPC:
https://www.wow-mania.com/armory/?npc=15491

**What is Happening:**
Hello! this is a minor report cause 
1: not many ppl get to doing this quest at all (loremasters only usually)
2: I can't describe it properly since it is kinda hard-to-get quest I done few months ago.

Eranikus lands before all th shades are killed. I am not sure if he uses his abilities (I think not). After getting his HP sufficiently low the quest got completed and in chat tab was visible Tyrande speaking with now redeemed Eranikus (humanoid form presumably) but I haven't noticed either Tyrande nor Eranikus human form anywhere around me. There were no priestess joining us during the fight.
Someone who can activate the event without prerequisities should take a look into it. It is pretty epic lore-wise. Pity to waste this event after such a long toil to get the quest for it.
**What Should happen:**
Eranikus should spawn in Moonglade, not reachable. In one of the main buildings of Nighthaven and around should spawn lots of shades the players kill. After they all are killed Eranikus lands and fights players while Tyrande and her priestesses join the fight.

**Comment by Rushor** [comment]
he will start the path back home after 2 minutes now, quest credit should be rewarded. the event all in all is a bit wonky.

that erankis is landing pretty fast is due to prevent bugs

here https://youtu.be/55zABZZ4908?t=568 he also lands pretty fast
