### ISSUE TITLE
[Item] Lunar Festival Invitation does not work

### ISSUE THREAD

**Issue by jeyrella** [WoWManiaUK/Redemption#5261]
**Links:**
Item 21711

**What is Happening:**
When [Lunar Festival Invitation](https://wow-mania.com/armory/?item=21711) is used in the Greater Moonlight, player is not transported to Moonglade.

**What Should happen:**
When [Lunar Festival Invitation](https://wow-mania.com/armory/?item=21711) is used in the Greater Moonlight, player is transported to Moonglade.

**Comment by Rushor** [comment]
okay will fix, is item related

**Comment by Rushor** [comment]
fixed

**Comment by jeyrella** [comment]
fixed
https://youtu.be/7wFl07cuXcE
https://youtu.be/Ft7WiRkCGUA
