### ISSUE TITLE
[Dungeon]  Swamplord Musel'ek - Claw does not engage on pull - Underbog

### ISSUE THREAD

**Issue by jeyrella** [WoWManiaUK/Redemption#5262]
**Links:**
Claw: https://wow-mania.com/armory/?npc=17826
Musel'ek: https://wow-mania.com/armory/?npc=17827

**What is Happening:**
[Claw ](https://wow-mania.com/armory/?npc=17827)does not engage when [Swamplord Musel'ek](https://wow-mania.com/armory/?npc=17826) is pulled, and just sits at the back watching his master get massacred.

**What Should happen:**
https://www.youtube.com/watch?v=fVF2rGQwGhE
As seen in this era-relevant video, Claw should rightly get pissed off that someone is hurting his master, and engage at same time as Swamplord Musel'ek.

**Comment by Rushor** [comment]
Good report and find!

**Comment by Rushor** [comment]
they will attack together now
