### ISSUE TITLE
[Raid] Living Ember in Ruby Sanctum 25 Heroic - too few spawn

### ISSUE THREAD

**Issue by jonathan5er** [WoWManiaUK/Redemption#5263]
**Links:** https://www.wow-mania.com/armory/?npc=40683

**What is Happening:** When Meteor Strike hit ground then spawn only six Living Ember npc

**What Should happen:** When Meteor Strike hit ground must spawn 10 Living Ember npc

for proof i have some video: 
https://www.youtube.com/watch?v=cpbIWfLwp-8 (02:00); https://www.youtube.com/watch?v=zw4c79j5hfs (01:40); https://www.youtube.com/watch?v=XLgVU_2ThU0 (01:40)

have also comment on wowehead https://www.wowhead.com/npc=40683/living-ember#comments

**Comment by jeyrella** [comment]
Proof of 10 taken from videos, for clarity.a
![image](https://user-images.githubusercontent.com/46089380/105770568-4804ce00-5f57-11eb-8b55-0e9b785b9f5d.png)
![image](https://user-images.githubusercontent.com/46089380/105770851-a8940b00-5f57-11eb-8166-e6aaa1e298cd.png)

**Comment by Keader** [comment]
fixed

**Comment by svijetlo** [comment]
omw there now to finish rest of thisng i been doing
