### ISSUE TITLE
Wintergrasp Siege Engine turrets

### ISSUE THREAD

**Issue by Greywolf59** [WoWManiaUK/Redemption#5264]
**Links:**
Siege engines:
https://www.wow-mania.com/armory/?npc=32627
https://www.wow-mania.com/armory/?npc=28312
Turret:
https://www.wow-mania.com/armory/?npc=32629
https://www.wow-mania.com/armory/?npc=28319

**What is Happening:**
As a Horde I have EMPTY turret on Alliance siege engine as friendly. As a Horde I can actually mount the empty turret on Alliance siege engine, not sure if I get kicked out right away or not. The vehicle died just as I tried this and was in middle of mounting it. I haven't checked if it is same for Alli yet.

**What Should happen:**

**Comment by Keader** [comment]
i dont even understand lul

**Comment by Rushor** [comment]
I think he means that Horde can mount turret of alliance siege engine - and vise versa

**Comment by Keader** [comment]
Yes... has a protection for it already.
You got kicked out.

**Comment by svijetlo** [comment]
kek, just tested it yes you get icon to sit in it but you get kick out
