### ISSUE TITLE
Valanar Starsong and Fariel Starsong have question mark

### ISSUE THREAD

**Issue by jonathan5er** [WoWManiaUK/Redemption#5265]
**Links:** https://www.wow-mania.com/armory/?npc=15864 and https://www.wow-mania.com/armory/?npc=15909

**What is Happening:** Before i take quest they have question mark on head like i turn quest in and then when i finish they quest and come to turn in they still have question mark on head but no more quest to take or give

**What Should happen:** Question mark must only be on head when turn in quest, if i take quest must be ! or little bag because there are vendors on them to buy items after

**Comment by Rushor** [comment]
problem: there are everal quests like https://www.wow-mania.com/armory/?quest=8882 which are wrong assigned. since wotlk you get those items from those creatures as vendor.

removed all wrong quests from them.
