### ISSUE TITLE
Mount Hyjal: post in Progress

### ISSUE THREAD

**Issue by Greywolf59** [WoWManiaUK/Redemption#5268]
**Links:**
Hey I would like to keep this post having around for now. It seems to me a lot of stuff in Mount Hyjal might be bugged but it needs more checking out and maybe more skilled knowledgable eyes to check out. It is a thing for a long track. This is kinda like a list of oddities to be researched by me and others and get completed.
 I write this immediately after raid in this way so I would not forget anything links and stuff will be added over time. Thank you.

**What is Happening:**
Second boss, Anetheron, did not award rep, BoJ and loot on the kill. He might have got killing blow from guard NPC.
Gargoyles have something wrong with their aggro and keep TELEPORTING around kinda randomly. Hunter's Misdirection stopped working completely during Horde camp part.
Mark of Kaz'rogal might not make people explode after leeching out their mana, not even leech properly.
Anetheron's Inferno spell is interruptable by Pummel. Not sure if it should be.
It seemed to me the victims of Rage Winterchil's Frostbolt freeze were freed from it by my Intervene. Can't confirm yet.
Kaz'rogal can be disarmed.
Two Epic fist weapons drop from trash too much, at least someone of the raid claimed so. They indeed drop a lot.
1st wave of Ghouls do not award reputation.

**What Should happen:**

**Comment by Rushor** [comment]
If you can Split this in points and add the entries we can solve it :)

**Comment by Greywolf59** [comment]
Okay I will take a look into it tomorrow most likely
