### ISSUE TITLE
[NPC] Gargoyle has incorrect aggro table & random teleport - Battle for Mount Hyjal

### ISSUE THREAD

**Issue by Greywolf59** [WoWManiaUK/Redemption#5269]
**Links:**
Gargoyle: https://www.wow-mania.com/armory/?npc=17906

**What is Happening:**
Something is smelly about gargoyles' aggro. They keep acting pretty random when engaged by the raid members (they are acting 100% fine when fighting NPC guards). They even keep kinda teleporting across to the raid members (when half of the raid fought the back wave and half the frontal wave of enemies in Horde village).
One of our hunter's Misdirect stopped working and was not usable at all during the rest of the raid. It happened when we started to get gargoyle waves so it might be a reason.

**What Should happen:**
They should keep aggro properly (?).

**Comment by Rushor** [comment]
i think the main proplem is that they cannot really fly in the air (only have inhabit ground and swim) and that leads to strange movement behaviour. Now they should actually be able to fly

**Comment by svijetlo** [comment]
![WoWScrnShot_020521_112021](https://user-images.githubusercontent.com/61908373/107021230-2cde5d80-67a4-11eb-8532-dce92f67ab98.jpg)
![WoWScrnShot_020521_112130](https://user-images.githubusercontent.com/61908373/107021676-bee66600-67a4-11eb-8d74-82641b1b96f8.jpg)
![WoWScrnShot_020521_112137](https://user-images.githubusercontent.com/61908373/107021683-c148c000-67a4-11eb-9cbb-e8b62828ec72.jpg)
![WoWScrnShot_020521_112145](https://user-images.githubusercontent.com/61908373/107021686-c3128380-67a4-11eb-974d-54c0ce0c0c44.jpg)

**Comment by Rushor** [comment]
niceee!!
