### ISSUE TITLE
[Raid] Anetheron boss did not drop any loot rep or badges - Battle for Mount Hyjal

### ISSUE THREAD

**Issue by Greywolf59** [WoWManiaUK/Redemption#5270]
**Links:**
Anetheron https://www.wow-mania.com/armory/?npc=17808

**What is Happening:**
After killing Anetheron in the Alliance Village, the raid did not get reputation, BoJ, and the boss was not lootable (no loot icon). It might be that the killing blow was dealt by one of the friendly NPC guards perhaps?

**What Should happen:**
Boss should award loot, BoJ and rep.

**Comment by Rushor** [comment]
boss should now award credit, and loot and all even if last hit was done by a helping creature unit.

(player still needs to do damage on it for over 50 % at least)

**Comment by svijetlo** [comment]
![WoWScrnShot_020521_105851](https://user-images.githubusercontent.com/61908373/107019005-70839800-67a1-11eb-924e-c69fcda68c58.jpg)
