### ISSUE TITLE
[Raid] Anetheron's Inferno is interruptable - Battle for Mount Hyjal

### ISSUE THREAD

**Issue by Greywolf59** [WoWManiaUK/Redemption#5272]
**Links:**
Anetheron: https://www.wow-mania.com/armory/?npc=17808
Inferno: https://www.wow-mania.com/armory/?spell=39346
Towering Infernal: https://www.wow-mania.com/armory/?npc=17818

**What is Happening:**
Anetheron casts Inferno spell on random target that should spawn Towering Infernal. This spell is interruptable by warrior's Pummel and probably by other interrupts too. 

**What Should happen:**
I did not find any mention in any wowhead comments and guides that raid should interrupt the Inferno cast thus I believe it should not be interruptable
I did not notice if his Vampiric Aura works so that might be considered to be checked too.

**Comment by Keader** [comment]
fixed

**Comment by svijetlo** [comment]
could not interrupt
![WoWScrnShot_020521_110309](https://user-images.githubusercontent.com/61908373/107019272-bf313200-67a1-11eb-92b9-7077e50d0f22.jpg)
 it
