### ISSUE TITLE
Battlegrounds close too fast due to "not enough players"

### ISSUE THREAD

**Issue by GMMetaxa** [WoWManiaUK/Redemption#5273]
**Links:**

**What is Happening:** BG with minmax 10-15 closes with 10vs9

**What Should happen:**BG should close with overpowering by 5, so 10vs5

Apply to all Battlegrounds please.
Rushor has information.

**Comment by Rushor** [comment]
If one side has less than 6 players and map is a battleground, the bg will close prematurely

**Comment by bLeyaa** [comment]
This is still happening, had it yesterday in Eye of the Storm.

10v10 game, one player left the battleground making it 10v9 and the message popped that not enough players are there and that it will close within 5 minutes.

**Comment by Keader** [comment]
Fixed in https://github.com/WoWManiaUK/Redemption/issues/5274 @bLeyaa

**Comment by bLeyaa** [comment]
Oh i missed that, thanks! :)
