### ISSUE TITLE
[Battleground] 5 minutes timer sets off in warsong gulch regardless of the amount of players present

### ISSUE THREAD

**Issue by Kinkywiener** [WoWManiaUK/Redemption#5274]
**Links:**

**What is Happening:**
While in warsong gulch (Queued via RBG), 5 minutes "Not Enough Players" timer is set off even while the amount of players on each side exceeds the number 5. 
**What Should happen:**
"Not enough players" timer should be triggered only when the number of one faction goes below 5. I dont know whether the issue affects other two battlegrounds in RBG queue (AB, EOtS) or all battlegrounds regardless of the type queued for.

**Comment by Rushor** [comment]
Ah Yeah we added that battle will close when there are below 6 players. I need more Information on that

**Comment by Kinkywiener** [comment]
There were 10 allies and 8 hordes, yet it closed.

**Comment by Rushor** [comment]
Okay i gonna check

**Comment by Keader** [comment]
Fixed

**Comment by svijetlo** [comment]
can not test this alone ... take it to live and see what happen and adjust accordingly

**Comment by jeyrella** [comment]
agreed with svijetlo here.  hard to test as is
