### ISSUE TITLE
[NPC] Hit points of NPC not matching their level

### ISSUE THREAD

**Issue by Kinkywiener** [WoWManiaUK/Redemption#5275]
**Links:**
https://www.wow-mania.com/armory/?npc=707
https://www.wow-mania.com/armory/?npc=706
https://www.wow-mania.com/armory/?npc=94
https://www.wow-mania.com/armory/?npc=38
https://www.wow-mania.com/armory/?npc=6
https://www.wow-mania.com/armory/?npc=30
https://www.wow-mania.com/armory/?npc=525
https://www.wow-mania.com/armory/?npc=116

**What is Happening:**
The issue affects NPCs that are found in 2 different levels (levels follow in order, e.g. 1-2, 2-3, 3-4). You can find an NPC of lower level with the hit points of the higher and the other way around. I scouted Elwynn Forest and Dun Morogh only, but the issue is present elsewhere else well - I noticed it in other races´ starting areas. Some of the NPCs of Elwynn Forest and Dun Morogh are posted above.

**What Should happen:**
The amount of hit points of an NPC on a particular level should be fixed to all of the NPCs of the same ID.
Hit points of NPCs according to the level should be as follows:
Level 1 = 42 Hit Points
Level 2 = 55 Hit Points
Level 3 = 71 Hit Points
Level 4 = 86 Hit Points
Level 5 = 102 Hit Points
Level 6 = 120 Hit Points
.
.
.
I dont know how far in the levels the issues goes. I noticed it mainly on low level NPCs, as it influences the levelling in starting areas most visibly due to different ratios between spell damage/autoattack damage and the amount of hit points of the NPCs.

**Comment by Rushor** [comment]
Assign @Keader here

**Comment by Keader** [comment]
i realy cant understand what you saying

**Comment by Kinkywiener** [comment]
You can find an NPC of lower level with the hit points of the higher level NPC and the other way around.
You have lower level NPCs (level1) having more hits points than higher level NPCs (level 2). Talking about the NPCs of the same kind. Scattered in starting areas, just check the healthbars.

**Comment by Keader** [comment]
and how are you checking those "hit points"?

**Comment by Keader** [comment]
i'm closing it... lack of information.
When we have all information needed, can be re-opened
