### ISSUE TITLE
[Raid] The Lurker Below incorrect behaviour on Geyser ability - SerpentShrine Cavern

### ISSUE THREAD

**Issue by womptista** [WoWManiaUK/Redemption#5276]
**Links:**
The Lurker Below:  https://www.wow-mania.com/armory/?npc=21217
Geyser ability:  https://www.wowhead.com/spell=37478/geyser

**What is Happening:**
Today 01/30/2021 there was a raid on the naxxramas realm of SerpentShrine Cavern. When we got to the boss known as "The Lurker Below" he bugged out twice during his spout phase. "The Lurker Below" Leaves his area and chases people during this phase. 
Video of the bug in action https://youtu.be/2Qulx-4k00g.

**What Should happen:**
He is suppose to stay in his pool and spin in circles while spout.  
This video that shows how he is suppose to react during this phase https://www.youtube.com/watch?v=_AJkJWSUUdQ&t=14s Lurker starts at 0:14. There are video shortcuts in the description.

**Comment by Rushor** [comment]
Ah yes needs a root here

**Comment by Rushor** [comment]
should no longer be able to move while casting the spout effect

**Comment by jeyrella** [comment]
Hmm.  Can't get it to work at all now, but may be some raid requirements.  Rushor, will connect with you on discord to test this.

**Comment by Rushor** [comment]
well there must always be someone in his melee range else he submerges
root yourself close to him with ID - 39258 Automation Root Spell (QAE)

**Comment by Rushor** [comment]
okay now he should always be rooted from the very beginning till end

**Comment by jeyrella** [comment]
so now Lurker Below does come up with the fish, but as soon as the tank hits him, he dives down again, even when there's 3 players in range and tank is already in water

**Comment by Rushor** [comment]
hmm for me he keeps beeing up https://i.imgur.com/JQDxGsP.jpg

can you test that again? :o
