### ISSUE TITLE
[Quest] Abandoning "Violet Eye" reputation ring quests deletes previous reward ring

### ISSUE THREAD

**Issue by jeyrella** [WoWManiaUK/Redemption#5277]
**Links:**

"Down the Violet Path"
https://wow-mania.com/armory/?quest=10733
https://wow-mania.com/armory/?quest=10734
https://wow-mania.com/armory/?quest=10735
https://wow-mania.com/armory/?quest=10736

"Distinguished Service"
https://wow-mania.com/armory/?quest=10739
https://wow-mania.com/armory/?quest=10740
https://wow-mania.com/armory/?quest=10741
https://wow-mania.com/armory/?quest=10742

"Eminence Among The Violet Eye"
https://wow-mania.com/armory/?quest=10725
https://wow-mania.com/armory/?quest=10726
https://wow-mania.com/armory/?quest=10727
https://wow-mania.com/armory/?quest=10728

**What is Happening:**
If one takes any of the 4 "Down the Violet Path" quests, and then abandons, the ring rewarded from the _previous_ level is removed/deleted from inventory/equipment.

This also happens with the Revered and Exalted version quests, "Distinguished Service" and "Eminence Among The Violet Eye" reespectively.

https://youtu.be/FiOkQKLpa3E

**What Should happen:**
If one abandons any of these quests, the previous reputation level's ring should not be deleted.

**Comment by Rushor** [comment]
i think this happens because any provided questitem get's deleted if quest is abandonated, we must add a check to not remove that

**Comment by Rushor** [comment]
at any point of the quests, you can now restore the deleted item with a gossip option at Archmage Leryda (That is how it is supposed to work on blizz)

**Comment by jeyrella** [comment]
Wow, that's such bad design.  OK, well...  it technically works now as per Blizz.  Albeit it's an awful solution!

**Comment by Rushor** [comment]
yeah i know it is really strange - in several situation it works like that sadly
