### ISSUE TITLE
Leotheras: Inner Demons take some damage they should not

### ISSUE THREAD

**Issue by Greywolf59** [WoWManiaUK/Redemption#5278]
**Links:**
Leotheras the Blind: https://wow-mania.com/armory/?npc=21215 + ?npc=21845 (demon form I guess)
Inner Demon https://wow-mania.com/armory/?npc=21857#summoned-by
Perhaps also invisible aura: https://www.wowhead.com/spell=37713/demonic-alignment as stated in comment on https://www.wowhead.com/npc=21857/inner-demon#comments

**What is Happening:**
Other people's demons do take damage from Bladestorm, Sweeping Strikes, Cleave and Whirlwind. Not sure if they take damage from direct melee hits, I was targetting boss at all times. One of the raid members said the other demons did not take any damage from him. I think it was a rogue. No clue about other spells, AoE, schools of magic etc. 

**What Should happen:**
The demons should take damage only from the person they belong to and their pets/totems/guardians.

**Comment by Keader** [comment]
In serverside, npc is not getting damage (something like dummy)
even if in clientside show damage and HP dropping, next damage will make "hp back to correct".
Only "demon owner" can damage him. (not even pets/totems/guardians can)
So in the end, it's correct ^^
