### ISSUE TITLE
[Raid] Lady Vashj taking damage in Phase 2

### ISSUE THREAD

**Issue by Greywolf59** [WoWManiaUK/Redemption#5279]
**Links:**
Lady Vashj: https://wow-mania.com/armory/?npc=21212
Tainted Core: https://wow-mania.com/armory/?item=31088#unlocks-object (+ links for generators)
Tainted Elemental: https://wow-mania.com/armory/?npc=22009#drops

**What is Happening:**
First and foremost the Tainted Elementals do not have 100% drop chance of the Tainted Core. M y educated guess would be it currently has 10-20% drop chance.
In Phase two when Elementals spawn and the 4 Generatos are active, creating Invulnerable shield around the boss, the boss should not take any damage until all 4 generators are swithced off by Tainted Cores. Currently it is enough to switch off one of the generators only and the raid can DPS the boss. I think the DPS grows with each generator swittched off but can't say for sure. In practice you can kill Lay Vashj in Phase 2, without her ever entering the Phase 3 and without taking all generators down.

**What Should happen:**
Tainted Elementals should have 100% drop chance for the Tainted Core and the boss should be completely invunerable to damage untill all 4 generators are down.

**Comment by Keader** [comment]
It dont have 100% drop chance.
Not back to tbc/wotlk
About generators, fixing it.

**Comment by Keader** [comment]
try now

**Comment by jeyrella** [comment]
No longer takes damage in phase 2 - completely immune to everything I tried.
