### ISSUE TITLE
[Spell] Battle Stance threat generation

### ISSUE THREAD

**Issue by Greywolf59** [WoWManiaUK/Redemption#5280]
**Links:**
Battle Stance https://wow-mania.com/armory/?spell=2457
https://wowwiki.fandom.com/wiki/Threat#Threat_tables_per_class
Battle Shout: https://wow-mania.com/armory/?spell=47436
Commanding Shout: https://wow-mania.com/armory/?spell=47440

**What is Happening:**
I do not have any comparison of threat gains in Battle Stance but the threat generated seems a bit high.
If the boss encounter is just started (boss pulled by tank +-2s prior) and you switch from any other stance to Battle Stance you automatically get 100% threat from the boss (aggroed all 3 BPCs yesterday) and tank can have a problem to pull it back. If you do stance-dance later in the fight, the issue is not visible. This isuse might apply to all the stance switching but I can't really say. I do believe taht 80% modifier is missing from battle Stance (see wowwiki)

I think this issue is also applied to warrior's shouts, at least in battle stance (I play arms so I am in Battle Stance 90% of the time). If you do use Battle Shout in dungeon or a raid, you can pull 100% aggro from pretty far mobs that were not active before, even if other party members were closer to them. I know these buffs do apply threat generation but it just feels kinda of somehow. I never seen pala grab aggro like this. it feels like Warrior is kind of walking Healing Stream Totem time to time.

**What Should happen:**
From wowwiki:
Finally, note that the in-game threat meter (introduced in Wrath) does not use the decimal notation the table does; instead, the baseline modifier is considered to be 100. For example, causing 100 damage would cause (100 * 1.0) = 100 threat by this page's system. The in-game threat meter, however, would consider 100 damage as causing (100 * 100) = 10000 threat. Likewise, the 80% threat modifier of Battle Stance would be 0.8x for all threat caused, while the in-game threat meter would consider all threat to be multiplied by 80 while in Battle Stance.

I do believe the Battle Stance should not generate so much threat. Neither the stance-dance.

**Comment by Keader** [comment]
I cant reproduce.
Battle Instance add a aura, that add 20% of thread reduction
In game:

![image](https://user-images.githubusercontent.com/7120913/106460721-87a94980-6472-11eb-85df-e845c1597769.png)

original thread was 128, -20% is become: 102.4

128*0.8 = 102.4
Working fine.

**Comment by Greywolf59** [comment]
Okay thank's for checking it. Is there any chance anyone checked the stance-switch? Or do you think it is normal too? I never played retail, nor ever I was a tester or something so I have no clue about this stuff, so sorry if this is just an useless topic.
