### ISSUE TITLE
Auction House doesn't deliver gold if setting more than one of the same item auction at the same time

### ISSUE THREAD

**Issue by Suvkiller** [WoWManiaUK/Redemption#5281]
**Links:**

**What is Happening:**
When I set more than an auction of the same item (i.e. 2 packs of Iron Ore) and someone buyout them, the first one comes with the gold and the second one says the gold will arrive later, but even when the time said on the letter is up, I don't receive the gold neither the items.

**What Should happen:**
The Auction House should send me the gold or the items back.

**Comment by bLeyaa** [comment]
Check auction house if both actually sold. 
The first email you receive is just informing you that the item was sold and that you will receive gold soon. The second mail is the one that comes with the gold of the sold item.

**Comment by jeyrella** [comment]
As bLeyaa said.   The first email gets deleted automatically as it's just a "progress report".  All this means the 2nd item you posted didn't sell yet.
