### ISSUE TITLE
[Raid] Respite for a Tormented Soul (Sindragosa) quest bugged

### ISSUE THREAD

**Issue by ZoLee89** [WoWManiaUK/Redemption#5282]
Hi,
i used the Pulsing Life Crystal on Sindragosa and the boss didnt drop the quest item.
My raid members had the same issue on 10 and 25 mode.

I have 2.8.0 patch and starting the game always with launcher.

I hope it will get fixed.

Best regards,
Twidgee

**Comment by wow-mania** [comment]
Please link quest and item you are talking about.
I doubt there is an issue here but we can check.

**Comment by svijetlo** [comment]
while you use item for quest in 10man boss get stacks it need 35 stacks to get debuff and quest will be don while in 25man it need 75stacks , quest works properly i did in 10 man 2 days ago and in 25 man yesterday, unless something buges out in one day 
https://github.com/WoWManiaUK/Redemption/issues/4567 this is ghub post that say how quest should work

**Comment by Oganku** [comment]
As svijet said, I highly doubt it doesn't work. Refer to image below for how the quest functions.
![image](https://user-images.githubusercontent.com/34783736/106516234-c22bda00-64a4-11eb-8048-f44dc8e1a95d.png)

**Comment by jeyrella** [comment]
@ZoLee89 to make this clear from the above, **you alone using the item will likely not be enough**.  Several players in the raid must build up enough stacks on the boss.

**Comment by Rushor** [comment]
was fixed long time ago, you need more stacks to get the credit

okay should only drop now if the stacks (30 in 10 man mode /75 stacks in 25 man mode) are applied and only if sindra got the buff (Soul Preservation). Only then the quest loot can be seen.
