### ISSUE TITLE
[Quest] Ruse of the Ashtongue

### ISSUE THREAD

**Issue by Greywolf59** [WoWManiaUK/Redemption#5284]
**Links:**
Quest: https://wow-mania.com/armory/?quest=10946
Ashtongue Cowl: https://wow-mania.com/armory/?item=31946
Al'ar https://wow-mania.com/armory/?npc=19514
wotlkdb post about the issue 3y back: https://github.com/cmangos/wotlk-db/issues/172

**What is Happening:**
Quest is automatically compelted after recieving it, probably missing "Al'ar slain" or "al'ar slain while wearing Ashtongue Cowl" condition

**What Should happen:**
This quest should not complete automatically. Player should be required to kill Al'ar while wearing Ashtongue Cowl.

**Comment by Rushor** [comment]
questcredit will now be given if quest is taken and player has aura: 42090 while creature get's killed

**Comment by jeyrella** [comment]
Fixed.  Now does not auto-complete, and must be wearing the cowl when Alar is killed.
https://youtu.be/I1AgNuhDoMk
