### ISSUE TITLE
[Lagging] Multiple places

### ISSUE THREAD

**Issue by heitorsv** [WoWManiaUK/Redemption#5285]
**Links:**
*None to display*

**What is Happening:**
Many places of the game are presenting an incredible amount of lag, which makes the game unplayable in such situations...
The places I had high lagging were The Server Mall, Onyxia's Lair, Maraudon, Dire Maul, Ragefire Chasm, Blackfathom Deeps, Blackrock Depths, Blackrock Spire, Stratholme (in Eastern Plaguelands, not the Culling).

This issue have been on for a few days now. I talked to people within my guild and some are experiencing the same problem while others are not.

Aside from The Mall and Onyxia's Lair, most of the lagging is happening in low level dungeons.
Cities, regular maps, high level dungeons and raids (except Onyxia's Lair) are all working fine.

**What Should happen:**
All areas should run smoothly likewise.

**Comment by Rushor** [comment]
This depends on Client and divers. Make sure both are on correct Version :)
