### ISSUE TITLE
Everfrost Chip doesn't give quest

### ISSUE THREAD

**Issue by Xangretor** [WoWManiaUK/Redemption#5286]
**Links:**
https://www.wowhead.com/item=44724/everfrost-chip
https://www.wowhead.com/quest=13420/everfrost

**What is Happening:**
You can loot the everfrost chip, but it doesn't let you take the quest "Everfrost" (by right clicking it) from it.

**What Should happen:**
You should be able to get a everfrost chip, that you can right click for the "Everfrost" quest to start.

**Comment by Rushor** [comment]
was you able to resolve the issue by yourself @Xangretor ?

**Comment by Xangretor** [comment]
Yes, I was being impatient / stupid

**Comment by jeyrella** [comment]
This is correct.  It DOES give the quest eventually, it is a 19% drop rate, NOT 100%.
