### ISSUE TITLE
[NPC] Arcane Vortex in Netherstorm not present

### ISSUE THREAD

**Issue by PrimeRet** [WoWManiaUK/Redemption#5287]
**Links:**
http://www.wowlevelingaddons.com/mote-of-air-water-ore-farming-engineering-mining/

Arcane Vortext:  https://wow-mania.com/armory/?npc=17408

Zapthrottle Mote Extractor:  https://wow-mania.com/armory/?item=23821

**What is Happening:**
Not finding any nodes in Netherstorm And don't know if the Respawn time on these are correct

**What Should happen:**
There should be nodes around the map then they will respawn in a different location in a certian amount of time

**Comment by jeyrella** [comment]
Confirmed.  Other gas clouds targetable by the extractor https://wow-mania.com/armory/?spell=30427#conditions all seem to be present, but the Arcane Vortex in Netherstorm seem to be phsyically missing, even through the armory shows them.  
Don't even show on the minimap when extractor is inventory.
![image](https://user-images.githubusercontent.com/46089380/106981205-840b1080-6759-11eb-9834-2b91824db3e4.png)
![image](https://user-images.githubusercontent.com/46089380/106981298-b1f05500-6759-11eb-9eca-695de4bb50da.png)
![image](https://user-images.githubusercontent.com/46089380/106981521-0c89b100-675a-11eb-9dd7-bdc25dd903ba.png)

**Comment by PrimeRet** [comment]
Was Farming the Air nodes in Nagrand I've went around the map 3 times so far and the nodes seem to be respawning in the same location

**Comment by Rushor** [comment]
There was pooling for them i guess. Will check

**Comment by Rushor** [comment]
So there are 69 spawns in total for nagrand, but only *1* is active at the same time. That is wrong. I will increase that to *15*. That mechanic is called pooling. so only a certain amount of creatures from all is visible at the same time.

For nagrand: They do not have any pooling them i guess

**Comment by svijetlo** [comment]
![WoWScrnShot_020521_114852](https://user-images.githubusercontent.com/61908373/107024303-2ce05c80-67a8-11eb-870d-bd186058b7b3.jpg)
