### ISSUE TITLE
[Quest] No Mercy for the Merciless quest

### ISSUE THREAD

**Issue by dzipinweed** [WoWManiaUK/Redemption#5288]
**Links:** https://www.wowhead.com/quest=13179/no-mercy-for-the-merciless#comments

**What is Happening:** Quest does not give kill count if someone in the raid group gets the killing blow

**What Should happen:** Quest should progress regardless of who gets the killing blow

I have noticed this happening with horde NPCs, dont know if its same with horde players but i would assume so

**Comment by Rushor** [comment]
Hmm i think that has special conditions

**Comment by Rushor** [comment]
https://www.wowhead.com/quest=13179/no-mercy-for-the-merciless#comments:id=746150

You do not need the killing blow and you do not even have to be in a raid group. You can kill the Horde NPC's in WG to do this quest.

You are right

**Comment by dzipinweed** [comment]
Yeah that's same link as mine 👍

**Comment by Rushor** [comment]
okay should now reward for the group if a group exists - testable on ptr

**Comment by jeyrella** [comment]
Fixed.
![image](https://user-images.githubusercontent.com/46089380/107160277-3f67bb00-698d-11eb-9d06-d8c4dfb07ba9.png)

![image](https://user-images.githubusercontent.com/46089380/107160288-48588c80-698d-11eb-98fb-dc92e8f45ddc.png)
