### ISSUE TITLE
[Raid] Hex Lord Malacrass - adds do not always reset position on wipe - Zul'Aman

### ISSUE THREAD

**Issue by jeyrella** [WoWManiaUK/Redemption#5290]
**Links:**
https://wow-mania.com/armory/?npc=24239

**What is Happening:**
On wipe, Hex Lord Malacrass and his adds do not always reset; in testing out of 6 times, 4 times the adds just stood still in same position after all dead.

**What Should happen:**
If raid wipes, Malacrass and all his adds should return to their starting positions.

**Comment by Rushor** [comment]
now they should always reset correctly again

**Comment by jeyrella** [comment]
Not sure if this is linked to this change, or is a New issue - Some adds seem only to aggro a few seconds into fight, but some respond instantly.  Even the boss sometimes doesn't aggro instantly.  Some dont respond on a direct taunt but others pull on that same taunt while first NPC stayus static

I tried various combinations of the adds, and can't pin down a for the conditions. 
e.g.
https://youtu.be/4GAjikUByLs


All adds should pull at the same time, together with Malacrass, regardless of which position they are in
https://youtu.be/7hq5qyyIEgo?t=12

**Comment by Rushor** [comment]
that is unrelated - it was like that also before

**Comment by Rushor** [comment]
should be good now - all attack together
