### ISSUE TITLE
[Spell] Professor Putricide - Unbound Plague not jumping

### ISSUE THREAD

**Issue by dzipinweed** [WoWManiaUK/Redemption#5291]
**Links:** https://www.wowhead.com/spell=70911/unbound-plague

**What is Happening:** This plague will often not jump from one player to another (none for that matter) ending up with plague ticking away and killing the player. It sometimes happens to 2-3 different players during a single encounter

**What Should happen:** Unbound Plague should always jump after being close by to another player. The only exception for it is the player who passed it on initially as there is a few seconds of immunity on that single player before he can take it again

**Comment by Keader** [comment]
Mutated Plague is correct not jump kekw
I belive that you talking about Unbound Plague.
Looking into it already.

**Comment by dzipinweed** [comment]
Hahaha yes my bad sorry, i was thinking of wrong plague :)

**Comment by Keader** [comment]
now Unbound Plague should ignore only targets affected by Unbound Plague or that have Protection Aura

**Comment by dzipinweed** [comment]
Hey, I forgot to mention the plague not jumping also happens after the boss was killed... Don't know if it matters but just to add 👍

**Comment by Oganku** [comment]
This still happens fairly often

**Comment by jeyrella** [comment]
got any Twitch streams / YT evidence of it?  kinda hard to replicate & debug on the small scale; seeing it in action helps massively.  Not sure where we'd even start with it, if not.

**Comment by Oganku** [comment]
It feels like every 3 attempts it happens at least once. I personally haven't recorded it, but I also can't find any steps to reproduce it. It happens often enough that it's hard to pinpoint anything.

**Comment by Oganku** [comment]
Random thought: It might have to do with player state/phase if they are ressurected in a specific way after a previous wipe. For example, using ankh or a soulstone to ressurect without having to run back manually.

**Comment by dzipinweed** [comment]
> Random thought: It might have to do with player state/phase if they are ressurected in a specific way after a previous wipe. For example, using ankh or a soulstone to ressurect without having to run back manually.

It happens on the first attempts as well, unless you are referring to a previous boss fight 🤷‍♂️

**Comment by Keader** [comment]
Try reproduce in PTR now.
Remember: it has a 5 sec protection, that dont allow same player get infection again

**Comment by svijetlo** [comment]
did fight 2 times on 10  and 3 times on 25 and yes it does jump do need to be careful of that 5 sec protection
