### ISSUE TITLE
[Raid] Zul'jin leaves players in combat after he dies - Zul'Aman

### ISSUE THREAD

**Issue by Greywolf59** [WoWManiaUK/Redemption#5292]
**Links:**
https://wow-mania.com/armory/?npc=23863

**What is Happening:**
Zul'jin leaves players in combat after he die

**What Should happen:**
Zul'jin should not leave players in combat after he dies

**Comment by Rushor** [comment]
oh already created a ticked for it :D 

https://github.com/WoWManiaUK/Redemption/issues/5293

is fixed on ptr
