### ISSUE TITLE
[Spell] Tame Beast failing if target not already in combat

### ISSUE THREAD

**Issue by jonathan5er** [WoWManiaUK/Redemption#5294]
**Links:** https://www.wow-mania.com/armory/?spell=1515

**What is Happening:** If cast Tame Beast on some npc you want a pet and cast Freezing Trap or Freezing Arrow then cast will finish but animal is not become pet

**What Should happen:** When use Freezing Trap or Freezing Arrow on animal and then cast Tame Beast it should become pet even when still is frozen.

is old tactic for hunter to get pet who does stun, fear etc... Is also work with mage Polymorph and similar spell

have info here https://wowwiki-archive.fandom.com/wiki/Tame_Beast and here in comment https://www.wowhead.com/spell=1515/tame-beast

**Comment by Echinaceax** [comment]
i used this tactic many times without any issue @Keader

**Comment by jonathan5er** [comment]
I try with 3 different animal and all fail... i got monkey, crab and ravager... 20 second cast finish but animal come out of freeze and attack me... i was in sholazar basen, borean tundra and helfire peninsula

**Comment by Keader** [comment]
i can reproduce.
i show to @Echinaceax hehe
working on it

**Comment by Keader** [comment]
Fixed.
Problem was: If you cast Tame Beast in a creature, that was not in combat with you, cast fail.
Now, even if a creature was not in combat with you, and you cast Tame Beast, you will tame it.
