### ISSUE TITLE
[Spell] Tricks of the Trade (Rogue) 

### ISSUE THREAD

**Issue by bLeyaa** [WoWManiaUK/Redemption#5295]
**Links:** https://www.wow-mania.com/armory/?spell=57934

**What is Happening:** When using TotT it sometimes happens that the ability goes on a permanent cooldown without it coming back. The bug does not disappear after doing reload or dying, only after relogging. Can confirm that it is also not a visual bug either.

**What Should happen:** TotT should always have 30 seconds cooldown upon being used and triggered.

Most recent recording of it occurring: https://clips.twitch.tv/ZealousZanyWrenLitty (from the addon text in the upper middle of the screen you can see that t10 2 set bonus (+15 energy) did not trigger either)

**Comment by Keader** [comment]
I added some protections...
protection will affect spells:

Shadowform
Misdirection
Tricks of the Trade
Stealth

**Comment by svijetlo** [comment]
i noticed this used to happen to me only if i tot with macros , thos great report and thx for fix
