### ISSUE TITLE
[Core/Spells] SpellHealingBonusDone missing CalculateDefaultCoefficient

### ISSUE THREAD

**Issue by Keader** [WoWManiaUK/Redemption#5297]
**What is Happening:**

While i was fixing https://github.com/WoWManiaUK/Redemption/issues/5296, i found a logic fail in SpellHealingBonusDone
Was missing a call of CalculateDefaultCoefficient, when spell has no spell power coeff.

**What Should happen:**
Healing spells with no Spell Power Coeff, should follow formula:
// As wowwiki says: C = (Cast Time / 3.5) * 1.88 (for healing spells)
This call was missing in code.

**Comment by jeyrella** [comment]
ok for MC, they still go back to their original place and sit quietly, instead of aggroing on the player
but they DO now respond if they're attacked.  so it's half-fixed
