### ISSUE TITLE
[Spell] Druid Lifebloom

### ISSUE THREAD

**Issue by bLeyaa** [WoWManiaUK/Redemption#5298]
**Links:** https://www.wow-mania.com/armory/?spell=48451

**What is Happening:** Lifebloom spell currently is not affected by talents modifiers nor spell power bonus healing. At the same time, the multiplier on stacks of it works fine on a naked toon but gets messed up on a geared one due to previously mentioned. In addition, the Lifebloom spell benefits from mana reduction in talent [Tree of Life](https://www.wow-mania.com/armory/?spell=65139) but the problem it has is that mana gained from Lifebloom is given for the original mana cost and not the reduced one.

**What Should happen:** Lifebloom should be affected by both spell power and talents while the multiplication of the stacks should be kept times the amount of stacks. Lifebloom mana gain should be adjusted to the new mana cost of the spell after it's affected by the Tree of Life talent.

**Comment by Keader** [comment]
https://github.com/WoWManiaUK/Redemption/issues/5296
noob
