### ISSUE TITLE
[Spell]  WhenMind Control breaks on NPC, they have no aggro or skill use

### ISSUE THREAD

**Issue by jeyrella** [WoWManiaUK/Redemption#5299]
**What is Happening:**
When a CC breaks on an NPC, they do not aggro back to the original player, nor do they even use skills if they are subsequently attacked.

**What Should happen:**
When CC breaks, NPC should aggro initially back to original casting player, and use all skills.

**Comment by Keader** [comment]
Fixed for Mind Control.
Please test if it solve for poly and fear too

**Comment by jeyrella** [comment]
ok. fixed for the non-attackable part.  found #4001 which is the reason for going to 'home', which was probably the wrong fix.  will talk to @Rushor to revise that one.
