### ISSUE TITLE
[Item/Raid] Zul'Aman timed event chest loot is not tradeable

### ISSUE THREAD

**Issue by jeyrella** [WoWManiaUK/Redemption#5301]
**Links:**
https://wowwiki.fandom.com/wiki/Zul%27Aman_timed_event
https://wow.gamepedia.com/Zul%27Aman_timed_event#:~:text=The%20subject%20of%20this%20article,of%20Warcraft%20in%20patch%204.1.
https://wow.gamepedia.com/Zul%27Aman_(removed)

**What is Happening:**
The chest loot added in https://github.com/WoWManiaUK/Redemption/issues/4755 is not tradeable, and is immediately soulbound on looting

**What Should happen:**
Loot from these chests should also have the the 2 hour trade window, like loot from raid bosses.

**Comment by Rushor** [comment]
seems like only this box 186648 bugs out, all others i can trade

**Comment by Rushor** [comment]
fixed

**Comment by jeyrella** [comment]
Tested all the loot drops from all chests, and while I won't link screenshots for every item, they are now all tradeable
Screenshots of one from each chest
![image](https://user-images.githubusercontent.com/46089380/107352109-632d1d00-6ac3-11eb-8297-a5dbd6c97dbe.png)
![image](https://user-images.githubusercontent.com/46089380/107352163-6fb17580-6ac3-11eb-9822-487829076488.png)
![image](https://user-images.githubusercontent.com/46089380/107352215-7e982800-6ac3-11eb-9aaf-6b6565474bd6.png)
![image](https://user-images.githubusercontent.com/46089380/107352291-8f489e00-6ac3-11eb-847c-1765590cd265.png)
