### ISSUE TITLE
[Client] Incorrect mounting sound for Squeaker, the Trickster

### ISSUE THREAD

**Issue by womptista** [WoWManiaUK/Redemption#5302]
**Links:**
Recorded from wow-mania server "Naxxramas": https://youtu.be/mhlUdANcyD8

**What is Happening:**
When mounting "Squeaker, the Trickster" He plays the mounting sound of a drake

**What Should happen:**
The mounting sound should be of a mouse and not a drake. Below is a video mounting with mouse sound from retail
https://www.youtube.com/watch?v=yCtuGj8KOW0

**Comment by wow-mania** [comment]
As-is as we don't have the required sound on the client.
