### ISSUE TITLE
[Client] Sound file missing from Illidari Felstalker

### ISSUE THREAD

**Issue by laurex2010** [WoWManiaUK/Redemption#5303]
Wowhead link   https://www.wowhead.com/item=128425/reins-of-the-illidari-felstalker

Got this mount in the mall only because of the hoof noises it makes when running, but it had no sound when I used it :( . Gm Jeyrella was very helpful and friendly when I related the issue.

**Comment by jeyrella** [comment]
Logged as per Amyelek, for tracking purposes.  Will need client change
