### ISSUE TITLE
[NPC] Freed Greengil Slaves do not despawn - Isle of Quel'Danas 

### ISSUE THREAD

**Issue by jeyrella** [WoWManiaUK/Redemption#5304]
**Links:**
Quest:  https://wow-mania.com/armory/?quest=11541
Greengil Slave:  https://wow-mania.com/armory/?npc=25084
Freed slave: https://wow-mania.com/armory/?npc=25086

**What is Happening:**
Some of the Freed Greengill Slaves involved in this quest do not despawn properly.  It appears to be only ones in some of the "camps", e.g. the ones at 64.5,46.7 seem to despawn ok, but ones at 61.4,46.5 do not

The impact is that they are forever Freed until the next server restart.

**What Should happen:**
Freed Greengil Slaves should all despawn after a few seconds, so they can respawn for following questing players.

**Comment by Rushor** [comment]
sai updated, they should always despawn now

**Comment by jeyrella** [comment]
Tried about 30 slaves in different camps, all despawned correctly
