### ISSUE TITLE
[NPC] Azaloth has become invisble - Shadowmoon Valley

### ISSUE THREAD

**Issue by jeyrella** [WoWManiaUK/Redemption#5305]
**Links:**
NPC: Azaloth https://wow-mania.com/armory/?npc=21506

**What is Happening:**
Like the Abyssal Flamewalkers reported last week, somehow Azaloth has become invisible.
![image](https://user-images.githubusercontent.com/46089380/107828671-3c9c0a00-6d81-11eb-850d-919b36792307.png)

This is a regression of some sort, as he has been clearly visible in the past, #1555

However he can be targeted and attacked, and the player enters into "combat", although he is still invisble and does not reciprocate or take any damage. At this point, the slight shadow banish outline of Azaloth does beome fainly visible

 If player then walks away out of combat range, Azaloth then becomes completely visible on disengage.

**What Should happen:**
Azaloth's banished shadow should be visible at all times, and as he is banished, he should not be able to engaged in combat until the quest item releases him.  Only on un-banishing with the quest should he become fully visible.
Hard to find era-exact videos, this gives an idea https://youtu.be/Nn_fDNtOKUw?t=37

**Comment by Rushor** [comment]
he is visible now
attacks on him in banished state will no longer have an effect. they hit him, but he does not attack, nor he takes damage.

once basnih is removed he can be killed. that's the only thing we can do here

**Comment by jeyrella** [comment]
Visible on spawn - fixed
![image](https://user-images.githubusercontent.com/46089380/108231962-32d82500-713a-11eb-8744-bfd3ef9b94be.png)

Initially immune to attacks
![image](https://user-images.githubusercontent.com/46089380/108226739-14bbf600-7135-11eb-93e1-8cc681b230a5.png)

**However** if player attacks him, disengages by going out of combat range & coming back, he can be attacked & take damage, but he does not react.  This is arguably worse since it now both makes him cheesable & ruins the quest....

**Comment by Rushor** [comment]
on evade he will readd the bansih state now. so if player may wanna abuse it he must use the spell 37834 from questitem again on him to remove bansih from him

**Comment by jeyrella** [comment]
Yep, this works well.  Stays immune if players return, and quest still works, and this part still is true 
![image](https://user-images.githubusercontent.com/46089380/108408540-0cd78100-721d-11eb-9265-195c6cf459a4.png)
;)
