### ISSUE TITLE
[NPC] Thrall is invisible - Nagrand

### ISSUE THREAD

**Issue by womptista** [WoWManiaUK/Redemption#5306]
**Links:**
Recorded from wow-mania Naxramas server: https://youtu.be/kaRJc8Q_rQI

**What is Happening:**
Thrall is showing up as an invisible NPC when travelling through Nagrand

**What Should happen:**
This is a video recorded from Retail back in 2018 that shows Thrall as a visible NPC: https://www.youtube.com/watch?v=DK3EuV7DRSk

**Comment by Rushor** [comment]
Yes i know that problem

**Comment by jeyrella** [comment]
Confirmed
https://wow-mania.com/armory/?npc=19556
![image](https://user-images.githubusercontent.com/46089380/107948462-bf90b080-6f8b-11eb-8f25-31bd1429b39e.png)

**Comment by Rushor** [comment]
should always be visible now

**Comment by jeyrella** [comment]
fixed
![image](https://user-images.githubusercontent.com/46089380/108225684-11743a80-7134-11eb-9449-391a48c1846e.png)
