### ISSUE TITLE
[RAID] The Lurker Below

### ISSUE THREAD

**Issue by womptista** [WoWManiaUK/Redemption#5307]
**What is Happening:**
When he does his spout mechanic he also goes into whirlwind at the same time; knocking back and killing everyone. If Anyone is under the water during this phase they live long enough to see him go into his second phase where is suppose to submerge (which he does) but he does not spawn his adds (which is is suppose to) and he resets himself after being submerged for about 50 seconds.

**What Should happen:**
The Lurker below is suppose to do whirlwind and then spot but not at same time. If there is a player within melee range the lurker is not suppose to whirlwind multiple times. When The Lurker Below submerges he is suppose to spawn adds 9 (I think). He is suppose to be submerged for about 50 seconds (again I think) then re-surface doing a whirlwind. He is not suppose to stay submerged and reset.

**Comment by Keader** [comment]
https://github.com/WoWManiaUK/Redemption/issues/5276 regression

**Comment by Rushor** [comment]
the other issue was about him beeing able to melee follow - this is a different thing now. will check

**Comment by Rushor** [comment]
whirl cast should now only be 20 seconds directly after the spout mechanic
