### ISSUE TITLE
Door in Upper Blackrock Spire arena stays closed

### ISSUE THREAD

**Issue by Xangretor** [WoWManiaUK/Redemption#5308]
**Links:**
https://classic.wowhead.com/npc=10429/warchief-rend-blackhand

**What is Happening:**
After killing Warchief Rend Blackhand and his dragon, nothing happens. Door stays closed.

**What Should happen:**
After killing Warchief Rend Blackhand and his dragon, door should open.

**Comment by Keader** [comment]
i need more info about this. What door dont open?
some tester can reproduce this issue?

**Comment by Xangretor** [comment]
When you jump down in the arena, you first need to kill a couple waves of dragons. After those waves Warchief Rend Blackhand comes out on his dragon. When they are all slain, a little door opposite of the gates releasing the adds and boss should open.

I did it twice in the same way and the first time it didn't open and the second time it did.

**Comment by Keader** [comment]
hmm, i cant reproduce in ptr :/

**Comment by Greywolf59** [comment]
Do not pull warchief before he sits up on his drake and flies out of the spawning area. this was +- repaired like 2 or 3 times already.

**Comment by jeyrella** [comment]
Reopenign #4718

**Comment by Xangretor** [comment]
Greywolf. It's not possible to attack the boss until he is on his dragon entering the arena. His HP is fixed now too. However it seems that if you kill him too quickly, aftering entering the arena on his dragon and being attackable, that it might bug out.

According to Wowhead he should jump off the dragon at 50%, but he doesnt do that

**Comment by Greywolf59** [comment]
Well prior to 2.9 I reported the same issue and it got fixed. No clue about now. And we killed him really fast. I eo not remember if he dismounted or not tbh.
