### ISSUE TITLE
Gate that will not open! 

### ISSUE THREAD

**Issue by Mizerie1** [WoWManiaUK/Redemption#5311]
**Links:**

**What is Happening:**I have been in the clasic dungeon upper blackrock spire to get the last boss for the loot and achievement, but after i defeat the boss called warchief rend blackhand the gate that lead the way up to the last 2 bosses won't open. I want to mention that this is not my first time im doing this dungeon and i look to see if i did something wrong but after the rend blackhand the gate itself opens. So yes this is a bug i have even made a ticket and talked with one of the GM and he told me to report the problem. 

**What Should happen:**

**Comment by Rushor** [comment]
see https://github.com/WoWManiaUK/Redemption/issues/5308
