### ISSUE TITLE
[Spell] Worgen Racial form healing for absurd amounts in combat/out of combat

### ISSUE THREAD

**Issue by Kilju** [WoWManiaUK/Redemption#5312]
**Links:**
http://www.wow-mania.com/armory?spell=150006
http://www.wow-mania.com/armory?spell=32819

**What is Happening:**
Worgen form is healing worgen characters to full health every 5 seconds. Also scaling with spellpower or spirit, with 3200-3500 spellpower it increases the heal by 0,3 million to total 1.3 million on a druid character from what the worgen players told me. See enclosed video for behavior and picture for heal amount reported by combat log

[Heal amount](https://i.ibb.co/wK5gmHg/Wo-WScrn-Shot-021521-235252.jpg)
https://www.youtube.com/watch?v=kiVG643ocMc&feature=youtu.be

**What Should happen:**
Worgen form should only have following effects:
Increases movement speed by 20%.
Effects that reduce movement speed may not bring you below your normal movement speed.

**Comment by jeyrella** [comment]
Confirmed, there is some crazy full-heal spell going on in background, however note I could only replicate when out of combat with NPCs.
https://youtu.be/9feITC6Ak7E
I couldn't replicate OP's scenario in duels
https://youtu.be/cfxFEINMqu8

**Comment by Keader** [comment]
Fixed
