### ISSUE TITLE
[Raid] Toravon the Ice Watcher - Frozen orb stays after boss death

### ISSUE THREAD

**Issue by svijetlo** [WoWManiaUK/Redemption#5313]
**Links:**
https://youtu.be/VMsP_8F6BvQ?t=174
http://www.wow-mania.com/armory?npc=38433
https://www.wowhead.com/spell=72091/frozen-orb

**What is Happening:**
During boss fight Toravon the Ice Watcher will summon frozen orbs , problem is if boss dies Frozen orb linger around and need to be killed by raid on its own  leaving raid in fight 

**What Should happen:**
On boss death, any remaining Frozen orb should despawn and leave players out of fight, as can be seen in vid https://youtu.be/VMsP_8F6BvQ?t=174

**Comment by Rushor** [comment]
should despawn now
