### ISSUE TITLE
[Item] Sandbox Tiger toy is attackable

### ISSUE THREAD

**Issue by jonathan5er** [WoWManiaUK/Redemption#5314]
**Links:** https://www.wow-mania.com/armory/?item=45047

**What is Happening:** If horde make tiger alliance can kill and if alliance make tiger horde can kill

**What Should happen:** Tiger is toy and should not have PvP marked... it must be neutral?

**Comment by Rushor** [comment]
you can no longer attack it once summoned and it should play cheer emotes now once player is mounted

**Comment by jeyrella** [comment]
Doesn't play the cheer emote on mounting, either in text or in sound.

Every few seconds seems to change the facing direction, and on the minimap it _appears_ that the player reverses entirely - neither of which it should not do.  
As is now: https://youtu.be/BurhdwMmXhc
Correct behaviour: https://www.youtube.com/watch?v=ZnGQjMVfM7I

Original issue is fixed:
While it DOES still appear as an enemy "player", it is not attackable:
![image](https://user-images.githubusercontent.com/46089380/108227801-2baf1800-7136-11eb-92d0-6e47d76df31f.png)

**Comment by jeyrella** [comment]
looks good
https://youtu.be/tr7puN3YiVk
