### ISSUE TITLE
[Raid] Marrowgar bone spikes turn player 180 degrees

### ISSUE THREAD

**Issue by dzipinweed** [WoWManiaUK/Redemption#5315]
**Links:** One of these I think https://www.wow-mania.com/armory/?search=bone+spike#spells

**What is Happening:** When player is spiked they will be turned around 180° facing the other way. This happens on every difficulty

**What Should happen:** Players should be facing the same direction as they were before the spike

Some retail videos showing the same 
1. https://youtu.be/b7lGWk6V-74?t=103
2. https://youtu.be/d8aYa5U4r4M?t=290
3. https://youtu.be/fyl62Eg4P2g - a lot of cases throughout the entire video, poor warlock

Another thing related to bone spikes is that players are standing on top of them whereas it seems on retail they'd always be in laid down position (only visual not so important) but also there is a "fall" back to ground once the spikes are killed.

**Comment by Keader** [comment]
please try now.

**Comment by dzipinweed** [comment]
Bring back during spike or once its killed?

**Comment by jeyrella** [comment]
Confirmed working in live
