### ISSUE TITLE
Love is in the Air NPC in Stormwind

### ISSUE THREAD

**Issue by womptista** [WoWManiaUK/Redemption#5316]
**Links:**
https://youtu.be/jjs7kh88Dm8 (recorded on Wow-Mania server Naxxramas realm

**What is Happening:**
During the event "Love is in the Air" the daily quest giver NPC 's are in the boxes.

**What Should happen:**
The NPC's should be standing on the boxes.

**Comment by Rushor** [comment]
try now pls

**Comment by jeyrella** [comment]
![image](https://user-images.githubusercontent.com/46089380/108869392-0ff0b980-75ef-11eb-8069-6b55125eaaed.png)

**Comment by jeyrella** [comment]
Not fixed.  Just logged back in, and found this:
![image](https://user-images.githubusercontent.com/46089380/108871749-5d6e2600-75f1-11eb-8794-2de8c3243142.png)

**Comment by jeyrella** [comment]
Ok worked with @Rushor on fixing this, seems corrected now for all locations where they're on boxes
