### ISSUE TITLE
Worgen - Racials Compendum

### ISSUE THREAD

**Issue by dzipinweed** [WoWManiaUK/Redemption#5317]
Disclaimer: Before you dwell into the report below, I fully understand that the race was custom added but some of these are quite significant for worgens and imo should be changed. As it is to my knowledge this would probably require new patch to change certain things, but perhaps some of them can be changed without it.

**What is Happening:**

1. [Two Forms](http://www.wow-mania.com/armory?spell=150330)
- The spell is supposed to be on a 1,5 seconds cooldown and is currently without it. 
- There is an animation missing when switching from human to worgen form. 
- When these two are combined you get people to spam it and single handedly do [this](https://i.imgur.com/LqyFEdH.jpeg). I would imagine this could possibly be stressing the server as well, contributing to the occasional lag spikes.

2. [Skinning Specialization](http://www.wow-mania.com/armory?spell=150007) 
- The racial spell name is supposed to be [Flayer](https://www.wowhead.com/spell=68978) 
- The spell only provides additional skinning skill but not the extra speed (this might be a tooltip issue only as I do not have skinning)

3. [Viciousness](https://www.wowhead.com/spell=68975)
- The racial spell is completely missing from worgens, probably the most important benefit for the race.

4. [Worg Form](http://www.wow-mania.com/armory?spell=150007)
- Custom spell, never existed for the race. If the following two points are added this should be completely removed.
- Gives great disadvantage to other players in PvP as the instant form cast means the player cannot really be slowed under the 100% regular run speed.

5. [Running Wild](https://wow.gamepedia.com/Running_Wild) 
- Racial spell is completely missing from worgens.
- If used in human form it should automatically change player into worgen as the spell is being casted.
- Spell has a 1.5 second cast time not affected by haste, same as mounts.
- Can only be used outdoors.
- Cannot be casted in combat.
- Speed changes depending on riding skill between 60% and 100%.

6. [Darkflight](https://www.wowhead.com/spell=68992)
- Racial spell is completely missing from worgens.
- Instant cast spell that provides 40% speed increase for 10 seconds on a 2 minute cooldown.
- If used in human form it should automatically change player into worgen as the spell is used.
- Can be used anywhere.

7. [Aberration](https://www.wowhead.com/spell=68976) 
- Racial spell is completely missing from worgens.
- Spell provides additional 64 resistance to Nature and Shadow damange at level 85 (as it was in Cataclysm). I believe the right amount at level 80 is 60.

**Comment by Rushor** [comment]
you know, we just imported that race and could not simply copy it from cata. So the stuff is missing because it is not there by default. Not sure if we should add those cata spells :) 

That's up to the creators :)

**Comment by wow-mania** [comment]
Unfortunately this is not an exact copy from Cataclysm and we have to deal with the limitations.
I will leave it open for now so devs can take a look and see what can be improved.
Whatever is left will be marked as-is.
Thank you!

**Comment by dzipinweed** [comment]
You are most welcome @wow-mania :)
Thank you for your replies!

If I can point out the most important ones from above that in my opinion should be focused are: 
[#1]() Two Forms
[#3]() Viciousness
[#4]() Worg Form

Two Forms for both annoying spam and possibly health of the server.
Viciousness for the extra 1% crit which means a lot in both PvE and PvP actions.
Worg Form for its overpowered state at the moment in terms of PvP. Perhaps a hotfix on this could be adding a cast time instead of it being instant? Just an idea

Thanks again for your attention to this report!

**Comment by Keader** [comment]
Like i told to janitor, the only one that i can fix is add cooldown into Two Forms.
Added 3 sec (it dont appear in client, but you cant cast spell before 3 sec), because with 1.5 sec we can still spam the effect.

**Comment by Keader** [comment]
Hmm, i think that i can maybe make Viciousness works, without call it Viciousness and just add critical effect kek (invisible)
better then nothing? xD
will check tonight

**Comment by jeyrella** [comment]
There is a cooldown effective on Worg > Human, but no CD on the reverse, from Human > Worg Form - is this intentional?

**Comment by jeyrella** [comment]
did the critical effect get added?

**Comment by Keader** [comment]
nope, i cant do it today :/
i will try tomorrow
