### ISSUE TITLE
[Event] Kwee Q Peddlefeet is missing the Smitten spell

### ISSUE THREAD

**Issue by jeyrella** [WoWManiaUK/Redemption#5318]
**Links:**
https://wow-mania.com/armory/?spell=27572
https://wow-mania.com/armory/?search=kwee+q#npcs
https://classic.wowhead.com/npc=16075/kwee-q-peddlefeet#abilities

**What is Happening:**
All the Kwee Q Peddlefeet vendors in all cities are missing the [Smitten](https://wow-mania.com/armory/?spell=27572) spell interaction

**What Should happen:**
if you /kiss any of the Kwee Q Peddlefeet NPCs, your max hp is increased by 200 through the [Smitten](https://wow-mania.com/armory/?spell=27572) spell.

**Comment by Rushor** [comment]
try now pls

**Comment by jeyrella** [comment]
Doesn't seem to be working, for either horde or alliance (Org/SW)

**Comment by Rushor** [comment]
added for all the ids of the city now, was assigned to wrong ids sorry

**Comment by jeyrella** [comment]
Now fixed
SW
![image](https://user-images.githubusercontent.com/46089380/108874827-73c9b100-75f4-11eb-9510-75b5784f3e7b.png)
and for Org
![image](https://user-images.githubusercontent.com/46089380/108875314-f5214380-75f4-11eb-9823-cc5c17299b11.png)
