### ISSUE TITLE
[Item] Val'anyr bubbles proc on Judgement of Light

### ISSUE THREAD

**Issue by bLeyaa** [WoWManiaUK/Redemption#5319]
**Links:** http://www.wow-mania.com/armory?item=46017

**What is Happening:** Currently when the weapon effect procs, the shields provided from it are proccing off the heals coming from paladin's Judgement of Light.

**What Should happen:** Bubbles (shields) should not be proccing from spells such as Judgement of Light.

Video evidence: https://www.youtube.com/watch?v=s-JKSJGwfTE

At 5:28 you can see that JoL is on active on the boss and that ret and dk are attacking LK without getting the bubbles on them. At the same time you can see on paladin's buffs that the Val'anyr weapon proc is active during that time.

**Comment by Keader** [comment]
Fixed.
No one reported it before? shame guys !
make val'anyr super overpowered lol

**Comment by svijetlo** [comment]
30k jol don and not single proc of hammer so i would say all good
