### ISSUE TITLE
[Item] Bryntroll, the Bone Arbiter proccing more than intended

### ISSUE THREAD

**Issue by bLeyaa** [WoWManiaUK/Redemption#5320]
**Links:** https://www.wow-mania.com/armory/?item=50709 & https://www.wow-mania.com/armory/?item=50415

**What is Happening:** Currently the Drain Life proc from the weapon seems to have an increased PPM than intended or it's being procced by attacks that shouldn't proc it. 

**What Should happen:** Based on numerous data from retail, the weapon should have 2 PPM before any special attacks or talents are factored in. Additionally you can see the proc behavior in the logs below:

[Retail logs of all the boss kills](http://www.worldoflogs.com/reports/93srz9oiyo0jzzth/details/1/?enc=kills) (keeping in mind these fights too a lot longer as well, so in theory it should have had more procs than the comparable reports below)
That's 245 procs over the course of 12 boss kills, no wipes or trash included.
![image](https://user-images.githubusercontent.com/61625377/108645574-96a07c00-74b3-11eb-8e59-76f250695a7a.png)

[Mania logs of all the boss kills](http://www.worldoflogs.com/reports/c9jkfd9untqg05eb/details/18/?enc=kills)
That's 701 proc over the course of 12 boss kills, no wipes or trash included.
![image](https://user-images.githubusercontent.com/61625377/108645634-cfd8ec00-74b3-11eb-963f-2dbbe42d2730.png)

Another [retail log](http://www.worldoflogs.com/reports/kuhj8jz4n5z3ld6r/details/27/?enc=kills) from the time where the group was a lot stronger and the fights were much shorter

To avoid screenshots i'll make a quick comparison between single bosses like this, fight length on each was nearly identical:

        Boss           Procs (Mania)             Procs (Retail)
     Deathbringer           61                         21
     Rotface                68                         16
     Festergut              47                         20
     Lich King             170                         54

Wowhead: https://www.wowhead.com/item=50709/bryntroll-the-bone-arbiter#comments:id=920514

**Comment by Keader** [comment]
Reduced proc chance
