### ISSUE TITLE
Parry & Dodge in PvP

### ISSUE THREAD

**Issue by dzipinweed** [WoWManiaUK/Redemption#5322]
**Links:** N/A

**What is Happening:** What happens is that in PvP if you stun a player they still have the ability to parry and dodge. This is also possible while the enemy is casting a spell too.

**What Should happen:** Players who are incapacitated, stunned or under a cast time of a spell should not be able to parry or dodge attacks. 

[Parry](https://wowwiki-archive.fandom.com/wiki/Parry)
[Dodge](https://wow.gamepedia.com/Dodge)

Additionally, there seems to be some weird behavior with how many attacks are actually parried / dodged based on their passive stats of each. Even with additional expertise gear to counter it, still happens a lot. Don't know if this can be looked into somehow, but just worth mentioning.

**Comment by Keader** [comment]
try now pls

**Comment by dzipinweed** [comment]
Hello, this is still happening after update. :/

**Comment by Kilju** [comment]
seconded what @dzipinweed wrote.
Dodges and parrys are still happening against players who are casting.

**Comment by dzipinweed** [comment]
It happens in stuns as well :(

**Comment by dzipinweed** [comment]
@jeyrella @Rushor @Keader @wow-mania 
Can you please re-visit this issue?

**Comment by Keader** [comment]
as a said before, is working in ptr :/

**Comment by dzipinweed** [comment]
How can we make it work on the live server too? :)
