### ISSUE TITLE
Triage Quest - Theramore Isle

### ISSUE THREAD

**Issue by teknlogik** [WoWManiaUK/Redemption#5323]
**Links:**
Triage Quest - Theramore Isle

**What is Happening:**
It's spawning injured people and there's not enough time to heal them

**What Should happen:**
More time to heal the people so the quest can be completed

**Comment by GMMetaxa** [comment]
This is for bugs, not for requests.

**Comment by jeyrella** [comment]
This is deliberately difficult, and works exactly to Blizzard specs.
