### ISSUE TITLE
[Event] Pyrewood Village at SFK

### ISSUE THREAD

**Issue by Rushor** [WoWManiaUK/Redemption#5325]
https://wowwiki-archive.fandom.com/wiki/Pyrewood_Village?type=revision&diff=1779804&oldid=1779794

The event was missing 2 features:

1.) The creatures did not handled the trasformation spell cast one the event "Night" starts ( can be triggered by .event start 25)
2.) The updated worgen night creatures did not continued the paths from their human forms. They just stood still.

**Comment by jeyrella** [comment]
Nice!
![image](https://user-images.githubusercontent.com/46089380/108869985-a1602b80-75ef-11eb-965c-e4f8eff6900f.png)
(and yes, pathing is fixed)

**Comment by jeyrella** [comment]
(and once the event is stopped, yes they change back)
![image](https://user-images.githubusercontent.com/46089380/108870206-d1a7ca00-75ef-11eb-914f-a20c1ff505a0.png)
