### ISSUE TITLE
[Quest] Killing Dragon Progession Quest

### ISSUE THREAD

**Issue by Rushor** [WoWManiaUK/Redemption#5326]
Killing:

Emeriss
Lethon
Taerar
Ysondre
Azuregos
Malygos
Onyxia
Sartharion
Sapphiron
Razorscale
Sindragosa

Quest Giver and Ender: Bounty Hunter

Reward Titel - Dragonslayer + Dragon Mount and Gold

Quest: Not repeatable or sharable to prevent abuse

**Comment by jeyrella** [comment]
Eregos?
Keristrasza?

**Comment by GMMetaxa** [comment]
Quest 1: 
Emeriss
Lethon
Taerar
Ysondre
Azuregos

Quest 2:
Malygos
Onyxia
Sartharion

Quest3:
Sapphiron
Razorscale
Sindragosa

Title and Mount rewarded after quest 3.
Total of quest should have a timelimit.

**Comment by Rushor** [comment]
@GMMetaxa which timer would you suggest for each quest

**Comment by GMMetaxa** [comment]
Not sure what's possible. Can you start a timer after first kill?

**Comment by GMMetaxa** [comment]
Or after taking the quest?

**Comment by GMMetaxa** [comment]
2 hours for each quest seems competetive but doable imo

**Comment by svijetlo** [comment]
halion ?

**Comment by Rushor** [comment]
Timer starts after talking the quest. So 2 hours ok?

**Comment by svijetlo** [comment]
if it can be don in 10nm raids it is more then enough

**Comment by GMMetaxa** [comment]
2 hours ok :) please move Azuregos from Q1 to Q2 and add halion to Q3

**Comment by GMMetaxa** [comment]
Quests should be repeatable in case of a fail. Not sharable.

**Comment by jeyrella** [comment]
Am not convinced 1st quest should have a time.  Aren't they world boss & plain RNG whether they've spawned or not?

**Comment by GMMetaxa** [comment]
Maybe we should change the spawntime. And yes, remove the timer from the first quest. Good input.

**Comment by Rushor** [comment]
which rewards should the first quests give - and a questtext for each would be good. sth connected to the life of the dragons. tiny peace of history. i can work on that but my english sucks

Infos:

https://wowwiki-archive.fandom.com/wiki/Emeriss 
https://wowwiki-archive.fandom.com/wiki/Lethon
https://wowwiki-archive.fandom.com/wiki/Taerar
https://wowwiki-archive.fandom.com/wiki/Ysondre

https://wowwiki-archive.fandom.com/wiki/Azuregos
https://wowwiki-archive.fandom.com/wiki/Malygos
https://wowwiki-archive.fandom.com/wiki/Onyxia
https://wowwiki-archive.fandom.com/wiki/Sartharion

https://wowwiki-archive.fandom.com/wiki/Sapphiron
https://wowwiki-archive.fandom.com/wiki/Razorscale
https://wowwiki-archive.fandom.com/wiki/Sindragosa
https://wowwiki-archive.fandom.com/wiki/Halion

**Comment by GMMetaxa** [comment]
Will do this weekend. Please let me know how many characters the text can be at max. The last quest will reward a mount and a title, that's what it's about. The first quests should give gold only imo.

**Comment by GMMetaxa** [comment]
Maybe swap Malygos and Sapphiron. makes more sense for the key to get to maly.

**Comment by jeyrella** [comment]
Also perhaps add a Eregos & Keristrasza as first quests, as they are the 5-man dungeons?  

in terms of lore it is a better fit as the 2nd quest, but if people are planning this as a chain, that would make it awkward breaking up the raid after first one

Nexus+Oculus; timer for both....  is 30 mins possible?  Thats a push perhaps

**Comment by Rushor** [comment]
yeah we should add those 2 aswell

any progress with the quest texts? :)

**Comment by Rushor** [comment]
i will move this to the private tracker so we can discuss better
