### ISSUE TITLE
[Spell] Omen of Clarity procs on Find Node change

### ISSUE THREAD

**Issue by svijetlo** [WoWManiaUK/Redemption#5327]
**Links:**
http://www.wow-mania.com/armory?spell=16864
http://www.wow-mania.com/armory?spell=8388
http://www.wow-mania.com/armory?spell=8387
**What is Happening:**
If player is druid that has talent 16864 Omen of Clarity, and has mining and herbalism then switch from find heab to find minerals and vice versa it can proc omen of clarity 

**What Should happen:**
it should not prock Omen of clarity

**Comment by Keader** [comment]
lol

**Comment by jeyrella** [comment]
that was my reaction too :D

**Comment by Rushor** [comment]
maybe any generic spell cast can procc it? like specc change

**Comment by svijetlo** [comment]
did try some other thing did not get it , if i see more ways prock it i will post

**Comment by Keader** [comment]
naaah dont need.
i can work without it @svijetlo

**Comment by jeyrella** [comment]
Confirmed.... lol
![image](https://user-images.githubusercontent.com/46089380/109296337-0ef69c80-7828-11eb-8ef9-08c81a61be8c.png)

**Comment by svijetlo** [comment]
i wonder i need to try can it proc also some other things on other classes :D 
need to test some things i guess XD

**Comment by Rushor** [comment]
this is the spell info

ID - 8388 Find Minerals (Rank 2)
=================================================
Description: Nearby mineral veins appear on the minimap. Only one form of tracking can be active at a time.
ToolTip: Finding Minerals.
Category = 1238, SpellIconID = 66, activeIconID = 0, SpellVisual = (0,0), SpellPriority = 0
Family SPELLFAMILY_GENERIC, flag [0] 0x00000000 [1] 0x00000000 [2] 0x00000000

SpellSchoolMask = 1 (SPELL_SCHOOL_MASK_NORMAL)
DamageClass = 0 (SPELL_DAMAGE_CLASS_NONE)
PreventionType = 0 (SPELL_PREVENTION_TYPE_NONE)
=================================================
Attributes: 0x29000010 (SPELL_ATTR0_ABILITY, SPELL_ATTR0_CASTABLE_WHILE_MOUNTED, SPELL_ATTR0_CASTABLE_WHILE_SITTING, SPELL_ATTR0_UNAFFECTED_BY_INVULNERABILITY)
AttributesEx1: 0x10000020 (SPELL_ATTR1_NOT_BREAK_STEALTH, SPELL_ATTR1_DONT_DISPLAY_IN_AURA_BAR)
AttributesEx2: 0x10000000 (SPELL_ATTR2_UNK28)
AttributesEx3: 0x00100000 (SPELL_ATTR3_DEATH_PERSISTENT)
AttributesEx6: 0x00001000 (SPELL_ATTR6_CASTABLE_WHILE_ON_VEHICLE)
=================================================
Skill (Id 186) "Mining"
    ReqSkillValue 1, Forward Spell = 0, MinMaxValue (0, 0), CharacterPoints (0, 0)Spell Level = 1, base 0, max 0, maxTarget 0

Category = 1238
DispelType = 0 (DISPEL_NONE)
Mechanic = 0 (MECHANIC_NONE)
SpellRange: (Id 1) "Self Only":
    MinRange = 0, MinRangeFriendly = 0
    MaxRange = 0, MaxRangeFriendly = 0

CastingTime (Id 1) = 0.00
RecoveryTime: 0 ms, CategoryRecoveryTime: 1500 ms
StartRecoveryCategory = 0, StartRecoveryTime = 0.00 ms
Duration: ID (21)  -1, 0, -1
Interrupt Flags: 0x00000000, AuraIF 0x00000000, ChannelIF 0x00000000
Chance = 101, charges - 0
=================================================
Effect 0: Id 6 (SPELL_EFFECT_APPLY_AURA)
BasePoints = 0
Targets (1, 0) (TARGET_UNIT_CASTER, NO_TARGET)
Aura Id 45 (SPELL_AURA_TRACK_RESOURCES), value = 1, misc = 3 (3), miscB = 0, periodic = 0

so any similar spell might ptocc it too

**Comment by Keader** [comment]
Fixed

**Comment by hawker357** [comment]
Still proccing Clearcasting when switching between Find Herbs (2383) and other trackers on PTR.
Find Minerals is not proccing Clearcasting

**Comment by svijetlo** [comment]
spammed those for over 5 min no prock

**Comment by Keader** [comment]
idk where this entry (2383) come from.
But i added a extra protection for it.

**Comment by hawker357** [comment]
I'm not getting procs now for find herbs either, seems to have worked

**Comment by svijetlo** [comment]
hmm have you don it on druid toon ? 
let me redo mine again and see what will happen

**Comment by svijetlo** [comment]
i can not make it procs while i change form find herb to find mineral but on attacks it did procsk wo problems

**Comment by Kilju** [comment]
Tested this change out with another druid (Rixxy) in-game and he reported that during 30 minutes of healing himself he did not get a single proc.

Went to test auto-attack, got it to proc just fine on auto-attacks within 30 seconds of starting auto-attack. clearcasting should proc from auto-attacks and any spells that druid can cast (excluding shapeshifting & feral abilities)
Unable to get it proc on spells, I did some healing and did motw and thorns for around 10-15minutes . None of spells I casted procced it.
Casted moonfire also for 3 minutes, no procs from damaging spells either.

Unable to test behavior on retail as it doesn't exist in its current form (passive since cataclysm, different in classic)
https://wowwiki-archive.fandom.com/wiki/Omen_of_Clarity

**Comment by jeyrella** [comment]
@svijetlo @hawker357 could you please re-test this change

**Comment by jeyrella** [comment]
not regression, just not properly fixed in first place

**Comment by Keader** [comment]
please keep the label. Is for me and janitor control.

**Comment by svijetlo** [comment]
as it seams fix was bad it locked out all spells/skill apart form auto attack only auto attacks will prock it atm

**Comment by Keader** [comment]
test now please

**Comment by jeyrella** [comment]
this was retested by svijet, unfortunately his account was locked out at the time
