### ISSUE TITLE
Bite them hard!

### ISSUE THREAD

**Issue by jonathan5er** [WoWManiaUK/Redemption#5329]
**Links:** Can not find

**What is Happening:** Quest not need to be taken but it marks automatically complete after winning battleground. Second problem is after quest given to the npc and rewarad taken if win another battleground the npc will have question mark on head and can talk to him for quest but then you can not turn in

**What Should happen:** Quest must be taken to be complete before winning battleground and there must not be question mark after win another battleground

**Comment by Rushor** [comment]
quests 113107 and 113108 and 113109 now only reward a credit in random battleground if quest is taken.

you can test that buy .debug bg and then join until you get av. then fly to last boss, kill it and the credit should be given

**Comment by svijetlo** [comment]
works fine ones you take it npc will have grey ? after complete will be golden/yellow
