### ISSUE TITLE
[Item] Hook of the Master Angler has on-equip cooldown

### ISSUE THREAD

**Issue by jeyrella** [WoWManiaUK/Redemption#5330]
**Links:**
https://wow-mania.com/armory/?item=19979

**What is Happening:**
Hook of the Master Angler has on-equip cooldown

**What Should happen:**
Hook of the Master Angler should not have on-equip cooldown  https://youtu.be/S-PysysL6QQ?t=33

**Comment by Keader** [comment]
try now pls

**Comment by hawker357** [comment]
No cooldown on equip on PTR
