### ISSUE TITLE
[Raid] Tempest Keep: Eye trash respawns too quickly

### ISSUE THREAD

**Issue by womptista** [WoWManiaUK/Redemption#5331]
**Links:**
https://wowwiki-archive.fandom.com/wiki/Eye_(Tempest_Keep) 1/4 down the page it will list mob respawn timer is 2 hours

**What is Happening:**
Was not able to get video prof but mobs were respawning in rooms after 15 minutes of death

**What Should happen:**
Mobs should stay dead for the full 2hour death duration.

**Comment by Rushor** [comment]
will increase the timer

**Comment by Rushor** [comment]
respawn timer is now round about 2-3 hours for all trash

**Comment by svijetlo** [comment]
waited around for one sandwich one juice drink and 2 smokes XD
