### ISSUE TITLE
Upper Blackrock Spire Gate issue

### ISSUE THREAD

**Issue by nerdofthenorth** [WoWManiaUK/Redemption#5332]
**Links:**

Issue~

After defeating Rend Blackhand in UBRS, the iron gates to the arena and the gates leading out towards the Raid Entrance of Blackwing Lair do not open.

What Supposed to Happen~

After defeat the doors should silmultaneously open to let players through to complete the rest of UBRS or allow entrance to BWL.

**Comment by jeyrella** [comment]
Working as intended.  There is a mechanic.  Don't kill him too quickly ;)
