### ISSUE TITLE
[Raid] Nefarion Phase 1 Issue

### ISSUE THREAD

**Issue by nerdofthenorth** [WoWManiaUK/Redemption#5333]
**Links:**

During Phase 1 of the Nefarion encounter in Blackwing Lair, instead of summoning Draknoids from the designated doorways, he simply continues to cast Shadowbolt Volley and his Invulnerability never drops. GM Psy was present to reset the boss when he failed to migrate into Phase 2 and transform into a dragon. After second reset the Draknoids did not return and a repeat of the same infinite cycle of boss immortality.

During Phase 1 aside from casting Class specific debuffs on all raid members, should be calling out for Draknoids to emerge from two "dead-end" hall ways adjacent to his throne. After he has summoned 42 Draknoids and they are killed he will transform into his dragon form and cast Shadow Flame on the raid from the balcony. He then is engageable by the raid. At 20% health he summons Bone Constructs from the 42 Draknoid coprses and continues his normal phase 2 routine until death.

**Comment by Rushor** [comment]
spawn locations adjusted a bit, they might were falling below the ground

**Comment by svijetlo** [comment]
worked fine for me
