### ISSUE TITLE
[Quest] Skywing

### ISSUE THREAD

**Issue by heitorsv** [WoWManiaUK/Redemption#5336]
**Links:**
https://www.wow-mania.com/armory/?quest=10898
https://www.wowhead.com/quest=10898/skywing
https://www.youtube.com/watch?v=EFe4K6fhI0Q

**What is Happening:**
Skywing flies through the scenery, crossing rocks and mountains instead of following the common path. At the end he is also not at the meeting place.

**What Should happen:**
Skywing should fly through a certain path, climb the ramps and get to his destination for the quest to be completed.

**Comment by Rushor** [comment]
most likely the event is not totally finished somewhere

**Comment by jeyrella** [comment]
re-opening #5283 instead
