### ISSUE TITLE
[SPELL/ITEM] Free Action Potion is not dispellable

### ISSUE THREAD

**Issue by Kilju** [WoWManiaUK/Redemption#5338]
**Links:**
http://www.wow-mania.com/armory?item=5634
https://www.wow-mania.com/armory/?spell=6615
https://wowwiki-archive.fandom.com/wiki/Free_Action_Potion#Patch_changes
**What is Happening:**
Free Action Potion should be an magic effect, and thus dispellable. It is not magic effect in wow-mania

**What Should happen:**
Free Action Potion was changed to be an magic effect in 1.7 patch. Please see enclosed screenshots, warrior one is taken today in classic wow and paladin one from wow-mania.
[Classic free action potion](https://ibb.co/TRkmbCX)
[Screenshot from wow-mania](https://ibb.co/ynPpzrH)

**Comment by Rushor** [comment]
since tbc they are no longer dispellable

here the source:
Effect is undispellable as of 2.3.


Von DELPylon (2,981 –  2·36)  am 2007.11.08 (Patch 2.2.3) |   |  
https://i.imgur.com/D7bqTHs.png

**Comment by Kilju** [comment]
You are correct. Apologies for the incorrect github report. Retail is not at TBC and wiki wasn't updated correctly. Very shameful. After checking 2.3 patchnotes I can see another change reverting them back to undispellable. 
https://wowwiki-archive.fandom.com/wiki/Patch_2.3.0
