### ISSUE TITLE
[SPELL] Mangle (Cat) / Hemorrhage energy refund issue for druids and rogues.

### ISSUE THREAD

**Issue by Kilju** [WoWManiaUK/Redemption#5339]
**Links:**
https://www.wow-mania.com/armory/?spell=48566
https://www.wow-mania.com/armory/?spell=48660
https://wowwiki-archive.fandom.com/wiki/Patch_0.6
https://roguecrap.blogspot.com/2006/03/energy-regeneration-oddities.html
**What is Happening:**
Combo point generating abilities for rogues and druids in catform do not return 80% of energy on all CP generating skills when they miss/parried/dodged

**Kitty Druid**
Rip is refunding 80% of energy
Shred is refunding 80% of energy
Claw is refunding 80% of energy
Mangle is not refunding any energy
 
***Rogue***
Sinister strike is refunding 80% energy 
Hemorrhage is not refunding any energy
Backstab is refunding 80% of energy
Shiv ignored due to shiv mechanics (cant be dodged or parried)
Mutilate, do not have spec for it.

**What Should happen:**
Missed combo point generating attacks that are dodged/parried/miss should refund 80% of energy since 0.6 patch. (No mention of druids since that is the patch they released out)
Found a old github from wow-mania also supporting partly 80% claim: https://github.com/WoWManiaUK/Redemption/issues/2512
Old rogue theorycrafting link for vanilla behavior included in links

Bonus finding for shiv: 
Shiv with 0% hit rating and 61 shivs on heroic dummy, none missed. So might be an issue there. Comparison to (double check combat log)  hemorrhage where out of 16 attacks 1 missed (5,3%), and sinister (23 attacks which 3 missed 13%. and autoattack 686 which 165 missed (24,1%). so i doubt I got so good RNG that none of shivs missed.

**Comment by jeyrella** [comment]
Am not too knowledgeable on these classes.  All I can find on that reference is this, and am struggling to find anything specific to mangle/haemorrage (also, 0.6 was alpha patch & very old, unsure if any changes happened since)
![image](https://user-images.githubusercontent.com/46089380/109792281-417b0d80-7c0b-11eb-9053-d1e2a0a0b3a2.png)

keader, svijet, maybe you can find/know more

**Comment by svijetlo** [comment]
Hemorrhage is not refunding any energy i think this is true need to check for sure but i remember it was not working as it should when i had speck for using it 
Mutilate also not sure will have to chek as soon i get rest and time

**Comment by Keader** [comment]
Fixed

**Comment by jeyrella** [comment]
This was confirmed fixed by Svijet, whose github account has become corrupted.
