### ISSUE TITLE
[Object]  Airship inside the Deeprun Tram

### ISSUE THREAD

**Issue by jeyrella** [WoWManiaUK/Redemption#5340]
**Links:**
... ?

**What is Happening:**
There is (very rarely & intermittently) an airship in the Deeprun Tram at the Ironforge end, transverse across the tracks
![image](https://user-images.githubusercontent.com/46089380/109856323-45ca1980-7c51-11eb-8bfe-2d885b2033af.png)

Cannot confirm which object ID this is, it has long eluded and is highly sporadic so difficult to test / confirm

**What Should happen:**
Well, there shouldn't be a bloody huge ship straight across the train tracks, right?

**Comment by jeyrella** [comment]
Apparently have had comments that it can happen at either end, not just IF

**Comment by Rushor** [comment]
ca happen in any instance in wow actually
