### ISSUE TITLE
[SPELL] Shred is able to be parried (and possibly dodged)

### ISSUE THREAD

**Issue by Kilju** [WoWManiaUK/Redemption#5341]
**Links:**
https://www.wow-mania.com/armory/?spell=48572

**What is Happening:**
Shred attack from druid is able to be parried and possibly also dodged in pvp combat. Was fighting a prot paladin who reported having 260ms. Most likely related to delay. I understand this would be hard to replicate for a tester. I attached recount of our duel.
![WoWScrnShot_030421_145128](https://user-images.githubusercontent.com/32513041/109967321-f12ea900-7cf9-11eb-932f-de2d23166ce8.jpg)

**What Should happen:**
Shred is only usable from behind the target and thus it should not be able to dodge or parry it in pvp, it can be dodged by NPC creatures with insufficient expertise.

**Comment by Keader** [comment]
fixed.

**Comment by jeyrella** [comment]
This was confirmed fixed by Svijet, whose github account has become corrupted.
