### ISSUE TITLE
[Quest] Ancient Spirit - typo in NPC commentary

### ISSUE THREAD

**Issue by jeyrella** [WoWManiaUK/Redemption#5342]
**Links:**
https://wow-mania.com/armory/?quest=4261
https://wow-mania.com/armory/?npc=9598

**What is Happening:**
When Arei is attacked by a hostile NPC, Arei says "This $n has been driven mad...."  whre $n should instead be the name of the NPC.
![image](https://user-images.githubusercontent.com/46089380/110038478-b3507580-7d37-11eb-9f2e-2887935760de.png)

**What Should happen:**
$n should instead be the name of the NPC.

**Comment by Echinaceax** [comment]
While checking this quest for a GM i noticed it still say  $n

![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/a54e4772-c1fc-45f5-9049-33ba30b39beb)
