### ISSUE TITLE
[PVP] RBG doesn't reward PVP tokens when losing

### ISSUE THREAD

**Issue by liendacil** [WoWManiaUK/Redemption#5344]
**What is Happening:**
Playing RBG on losing side doesn't reward PVP tokens. Even tough there were enough players, admittely some joined last minute. There was no reward other than honor. Suspiciously there's a "you don't have any space in your bags" message. I have forgot to open my bags in screenshot, but I can assure that I had bag space, for whatever purpose this would be needed.

![WoWScrnShot_030621_021552](https://user-images.githubusercontent.com/21057506/110190269-c12ef500-7e22-11eb-9d23-6c001e86b6c3.jpg)

**What Should happen:**
Should award the appropriate amount of PVP tokens. In this case I think it was 2 for winning 1 for losing side.

**Comment by GMMetaxa** [comment]
Pre-ended BGs do NOT reward.  BGs with not enough players on each side will end premature.

**Comment by liendacil** [comment]
This one was not pre-ended though. There are 9vs6, allys won by points. I asked Wolfiez he got 2x Tokens for winning in that BG.

**Comment by liendacil** [comment]
![WoWScrnShot_030621_163954](https://user-images.githubusercontent.com/21057506/110212232-ae580700-7e9a-11eb-8c63-897aa6c16faa.jpg)
Still the same.

**Comment by Echinaceax** [comment]
@GMMetaxa  please reopen this :)

i was just in there with them and 100% no pvp tokens given to the losing team , and as you can see from chat on the left we get an error message " "you don't have any space in your bags" message

this was not per ended Ally won we lost and go 0 Pvp tokens (we got honor and EoTs marks)

![image](https://user-images.githubusercontent.com/39439201/110213592-f843eb80-7ea0-11eb-8aba-58b80f1056e3.png)

**Comment by liendacil** [comment]
Apparently there was some setting that had to be adjusted by @fvicaria . And after reset it works as intended and losers get 1 PVP Token + the no bag space message is gone as well.

Consider it fixed for now, though it would proably be nice if the setting that had to be changed was documented here as well.

**Comment by jeyrella** [comment]
@liendacil note that this is a configuration item not a code adjustment issue, so therefore does not belong in github - hence why metaxa closed this.
Scope is purely under the GM purview as does not require any code change.  For same reason, documenting here is not required, as it is documented in the correct place already.
