### ISSUE TITLE
Nether Portal (Heroic) missing Death Grip immunity

### ISSUE THREAD

**Issue by bLeyaa** [WoWManiaUK/Redemption#5345]
**Links:** http://www.wow-mania.com/armory?spell=67900

**What is Happening:** Nether Portal spawned by Lord Jaraxxus on heroic difficulty can be death gripped by DKs.

**What Should happen:** Nether Portals should have immunity to Death Grip.

Possibly the Infernal Volcanos? Haven't tried that one but just worth checking along the way i guess.

There's no documented proof saying explicitly that the above is correct, but if you check any guide from wotlk for this fight or watch any video of it you will see that these do not get gripped. Additionally, all of the guides will say the melee needs to move to the portal to dps it.

For reference: https://wowwiki-archive.fandom.com/wiki/Lord_Jaraxxus & https://www.youtube.com/watch?v=_ub1sjwuIrQ (DK tank even)

**Comment by Keader** [comment]
both alread has grip immunity in ptr DB
