### ISSUE TITLE
[NPC] Mag'har Captive 18210 can be attacked by Alliance players

### ISSUE THREAD

**Issue by jeyrella** [WoWManiaUK/Redemption#5346]
**Links:**
NPC ID 18210

**What is Happening:**
For Alliance players, Mag'har Captive enters and immediately exits combat, repeating.  i.e. doesn't stay in combat once engaged.
(Horde players, he is correctly friendly)

https://youtu.be/3vds0IR8Gc0

NPC currently selected by player:
DB GUID: 65108, current GUID: 1864.
Faction: 1652.
npcFlags: 2.
Entry: 18210.
DisplayID: 17593 (Native: 17593).
Level: 62.
EquipmentId: 0 (Original: 0).
Health (base): 6411. (max): 6411. (current): 6411.
InhabitType: 3
Unit Flags: 37632
UNIT_FLAG_IMMUNE_TO_PC (0x100)
UNIT_FLAG_IMMUNE_TO_NPC (0x200)
UNIT_FLAG_PVP (0x1000)
UNIT_FLAG_UNK_15 (0x8000)
Unit Flags 2: 2048.
Dynamic Flags: 0.
Faction Template: 1652.
SpawnTime: Full:5m Remaining:0s
Loot: 0 Pickpocket: 0 Skinning: 0
InstanceID: 0
Phasemask: 1
Armor: 3555
Position: -1583.630005 8564.919922 2.000943.
AIName:  ScriptName: npc_maghar_captive
Flags Extra: 2
CREATURE_FLAG_EXTRA_CIVILIAN (0x2)
* is quest giver (2)
MechanicImmuneMask: 0

**What Should happen:**
Should stay in combat

**Comment by Keader** [comment]
Nope, blizzlike behavior for this creature is: Ally players cant attack him and he dont attack ally players too.
Fixed

**Comment by jeyrella** [comment]
Hmm.   I was going off this
![image](https://user-images.githubusercontent.com/46089380/110251185-462b2300-7f77-11eb-8885-5ee8dd30a90e.png)
and this
![image](https://user-images.githubusercontent.com/46089380/110251221-84c0dd80-7f77-11eb-89b7-19b1ca6af1db.png)

combined with the current behaviour that's he's attackable & hostile, as I could not find any reference that that behaviour had been changed
To be fair, it would be better that he is indeed not attackable for Alliance, much like the counterpart quest for Alliance

**Comment by Keader** [comment]
It has flags Immune to PC/NPC before start quest.
Is just impossible he attack someone while have it.

**Comment by jeyrella** [comment]
Fixed
![image](https://user-images.githubusercontent.com/46089380/110368539-17797f00-8041-11eb-8c49-3587fdef457c.png)

**Comment by jeyrella** [comment]
also still offers quest to horde
![image](https://user-images.githubusercontent.com/46089380/110369358-362c4580-8042-11eb-8b7f-0858209b9459.png)
