### ISSUE TITLE
[NPC] Arcane Vortexes from Netherstorm can be killed

### ISSUE THREAD

**Issue by Bulb1** [WoWManiaUK/Redemption#5347]
What is Happening:
It happens on Naxxramas realm (dunno if that changes something)
![image](https://user-images.githubusercontent.com/66064613/110241545-b8890c80-7f51-11eb-8869-65aeafcb5b5b.png)
![image](https://user-images.githubusercontent.com/66064613/110241595-deaeac80-7f51-11eb-8e4c-3da2448b0bdf.png)
![image](https://user-images.githubusercontent.com/66064613/110241602-f0904f80-7f51-11eb-81be-9df20aff8d3a.png)
U can target them using enemy name plates thus u can kill them. They leave no corpse so they can't be looted, but they can normally be collected using Zapthrottle Mote Extractor (of course when they are alive)
What Should happen:
They shouldn't be targetable/killable

**Comment by jeyrella** [comment]
Nice report.
@Rushor This one was easily missed as the target nameplate is wayyy above the ground level, in the z-axis.
As OP says, should not be able to even target these, much less kill them, as they are extractable engineering motes.

**Comment by jeyrella** [comment]
Has the pooling fix from https://github.com/WoWManiaUK/Redemption/issues/5287 regressed here?   I can't find any nodes at all now - was working fine this morning

**Comment by jeyrella** [comment]
(correct pooling still seen on live)

**Comment by Rushor** [comment]
Will check, those are spawned by item i think

**Comment by Rushor** [comment]
faction set to 190 like it was before, it that was wrong it will be updated correctly now again.

**Comment by jeyrella** [comment]
They are now correctly not targetable, and multiple spawned correctly now

However their name label is still visible, high above them, can we please hide that too
![image](https://user-images.githubusercontent.com/46089380/110628869-70f5c100-819b-11eb-8416-ad0042c69d90.png)

**Comment by Rushor** [comment]
as said, nameplate must stay, but no longer attackable

**Comment by Bulb1** [comment]
https://www.youtube.com/watch?v=W-OIBxLcYdI looks like they are still attackable 57.0 32.6
