### ISSUE TITLE
[NPC] Dalliah the Doomsayer from The Arcatraz in Netherstorm

### ISSUE THREAD

**Issue by Bulb1** [WoWManiaUK/Redemption#5349]
**What is Happening:**
"Gift of the Doomsayer" ability works wrong because even when target with this debuff is not healed, Dalliah is getting healed.
**What Should happen:**
It shouldn't heal boss when target with debuff is not healed.

**Comment by Rushor** [comment]
spell ids: 36174 or 39011 (nh + hc version)

should work now

**Comment by robertgf1** [comment]
still seem broken as per 15th of march 2021, 4.34pm cet
