### ISSUE TITLE
[NPC] Alliance Niobe Whizzlespark is killable by alliance

### ISSUE THREAD

**Issue by Bulb1** [WoWManiaUK/Redemption#5350]
What is Happening:
![image](https://user-images.githubusercontent.com/66064613/110306460-2854d100-7ffe-11eb-9896-85f6211bf56a.png)
![image](https://user-images.githubusercontent.com/66064613/110307023-c052ba80-7ffe-11eb-9cd7-da4ef40be05b.png)
you can kill her
What Should happen:
She is Alliance engineering trainer so she shouldn't be killable when you are from the alliance

**Comment by jeyrella** [comment]
https://wow-mania.com/armory/?npc=24868

**Comment by jeyrella** [comment]
confirmed.  not attackable witt auto-attacks, but skills and spells will indeed cause harm & combat.
Should be non-attackable.

**Comment by Rushor** [comment]
faction should be good now

**Comment by jeyrella** [comment]
fixed
![image](https://user-images.githubusercontent.com/46089380/110631362-583ada80-819e-11eb-9409-743f4a1fe310.png)
