### ISSUE TITLE
[Quest] True Masters of the Light 9737 - Aurius does not become hostile

### ISSUE THREAD

**Issue by robertgf1** [WoWManiaUK/Redemption#5351]
https://wowwiki-archive.fandom.com/wiki/Quest:True_Masters_of_the_Light_(3)

When using the "Extinguishing Mixture" the chapel catches fire and the five paladins does appear outside and are killable but Aurius (inside the chapel) does turn hostile and as such cannot be killed to complete the paladin class quest.

When using the "Extinguishing Mixture" Aurius should become hostile and killable, when he is killed the paladins outside should be killed and then the quest should be marked as completed.

**Comment by jeyrella** [comment]
https://wow-mania.com/armory/?quest=9737

**Comment by Rushor** [comment]
yes this is a good one!

**Comment by Rushor** [comment]
here the full script https://youtu.be/KY3E08MLXlw

**Comment by Rushor** [comment]
event fully fixed. it now works like you can see here https://youtu.be/KY3E08MLXlw?t=1275

Aurius becomes attackable after using Extinguishing Mixture, then the ghosts spawn and yell some lines.
Once Aurius is defeated the ghosts become attackable and reward the questcredit once all are killed.

**Comment by robertgf1** [comment]
Event does play out as it is suppose to now. Aurius turns hostile, when killed the paladins rushes in, when they are killed however the quest does not update to "complete".
