### ISSUE TITLE
Quest Bug: The Hunter and the Prince (Alliance) 

### ISSUE THREAD

**Issue by XeroPaladin** [WoWManiaUK/Redemption#5352]
**Links:**
This link is the description of the quest:
https://www.wowhead.com/quest=13400/the-hunter-and-the-prince#comments

This link is a video of the quest being done on retail version:
https://www.youtube.com/watch?v=FRFVDewnV1Y

**What is Happening:**
Currently, as i have received the quest, the stone to click to start the sequence is not spawning.
I have restarted my CPU, cleared my cache, everything is up to date with launcher and patches and i even waited a full 24 hours for a server reset and daily reset. 

**What Should happen:**
Ideally, only the stone needs to appear to start the sequence. i would suggest if this is not possible to just find some way to auto complete this quest. As far as i can tell, it's just a fun little mini battle with Arthas and Illidan.

**Comment by jeyrella** [comment]
Drop the quest and re-take it.  It's an old bug that we'll look into again
