### ISSUE TITLE
Quest Bite them hard! + Bite them Harder! + Push the Envelope.

### ISSUE THREAD

**Issue by Kilju** [WoWManiaUK/Redemption#5353]
**Links:**
Unable to find the quests on server armory. Sorry.

**What is Happening:**
Upon winning BG, you get all the quests instantly done, excluding Push the Envelope PVE dungeon parts. Bite them Hard is unaffected as its 1 victory to complete it anyways. Happened with 2 different characters.

**What Should happen:**
Probably intended to only get 1 win credit per BG victory for these custom quests.

![WoWScrnShot_030821_233341](https://user-images.githubusercontent.com/32513041/110385190-528ea900-8067-11eb-9a68-2bd3f71e07cc.jpg)
![WoWScrnShot_030821_223432](https://user-images.githubusercontent.com/32513041/110385196-53bfd600-8067-11eb-9b5e-9300a3cf2ce8.jpg)
![WoWScrnShot_030821_233441](https://user-images.githubusercontent.com/32513041/110385317-7ce06680-8067-11eb-9563-a577d1d9676b.jpg)

**Comment by Rushor** [comment]
each quest should reward now only 1 credit.

you can test that by .debug bg

waiting till av finally pops and then kill the last boss

**Comment by Rushor** [comment]
yep fixed for bg https://i.imgur.com/42CHP5u.png https://i.imgur.com/gjvHxSJ.png
