### ISSUE TITLE
[Spell] Death Knight- Death Strike off-hand heal(Threat of Thassarian)

### ISSUE THREAD

**Issue by festerhowl** [WoWManiaUK/Redemption#5354]
**What is happening**: Death Strike is not healing with the off-hand weapon when specced into threat of thassarian.

**Why it should heal with its off-hand**:  when blizzard introduced DK's they wanted to ensure that this class could efficiently tank and dps in all 3 of its specs, so if you notice how the talents are distributed in all 3 trees , you will find similarities in some talents. For example- _vampiric blood/unbreakable armor/bone shield_  and  _death rune mastery/blood of the north/reaping_. Similarly they also made talents that would ensure that DK's could improve their overall Death strike heal in each of these specs . Blood Spec has _improved Death strike_, unholy has _crypt fever/ebon plaguebringer_ and frost has _threat of thassarian_. 

**What should happen**: just like how plague strike reapplies blood plague on the target with off-hand weapon even after the main hand applied the disease, similarly when dual wielding and specced into Threat of thassarian, death strikes should also heal with its off- hand weapon. Moreover, since the hotfix of death strikes at patch 3.1.0 the maximum amount it can heal is 15% of total hp, therefore the main-hand weapon will heal 10% while the off-hand will only heal 5% of total hp so as to balance itself with the healing provided by the blood and unholy specs.

**Steps to reproduce:**
1. Get **3/3 Threat of Thassarian** from Frost tree.
2. Equip 2x 1handed weapons.
3. Apply _frost fever_ and _Blood plague_ diseases on your target with **Icy Touch** and **Plague Strike**.
4.  Use your **Death strike**.
5. Observe how it heals only 10% of your total hp when it should heal 15%.

**Comment by jeyrella** [comment]
Threat of Thassarian:  https://wow-mania.com/armory/?spell=66192
Death Strike

Cannot find any material to dispute the assertion, and seems reasonable argument; ofc wouldn't get comments on something that doesn't exist.  Only found references to "15% of health" in wowhead which would infer it should indeed heal on offhand strike (or it would be 10%)

Vindra/Svijet pls take a look as you have more knowledge on DK but this seems reasonable to adjust

**Comment by hawker357** [comment]
Confimed on PTR, Death Strike with Threat of Thassarian 3/3 deals 2 melee hits (1 MH 1 OF) but only heals once (5% per disease).

**Comment by svijetlo** [comment]
![Uploading WoWScrnShot_031121_133823.jpg…]()

**Comment by svijetlo** [comment]
![WoWScrnShot_031121_133823](https://user-images.githubusercontent.com/61908373/110788656-2f364a80-826f-11eb-87fa-88106b4eb5d3.jpg)

**Comment by Keader** [comment]
fixed

**Comment by hawker357** [comment]
Confirmed fixed on PTR, now heals twice with 3/3 Threat of Thassarian and dual-wielding, only heals once without ToT or when using 2h weapon.
