### ISSUE TITLE
Death Knight- Permanent Ghoul in Battlegrounds

### ISSUE THREAD

**Issue by festerhowl** [WoWManiaUK/Redemption#5356]
**What is Happening:** Despite not having **1/1 Master of Ghouls** talent, i am still getting a permanent ghoul which summons automatically when i enter battlegrounds or revive at the bg graveyard.

**What Should Happen** Only the players who are specced into that talent should have a permanent ghoul and should respawn only for them.

**Comment by svijetlo** [comment]
i do not know how you did that but i can not preproduce it 
if i summ ghoul out side of Bg then enter BG , ghoul is gone and it has 3 min cd to use 
if i use ghoul in bg he is there for 1 min and gone , spell enters 3 min cd 
if i die in bg with ghoul out on res ghoul is gone and spell is in 3 min cd

**Comment by festerhowl** [comment]
I didn't summon my ghoul when this bug happened. It just automatically spawned for me. Maybe try reviving in BG and don't use the raise dead spell(keep it off cd), see if it summons.
If that doesn't work, I also have that 1/1 master of ghouls in my off spec, but I am not sure how that can transition to my main spec though. @svijetlo

**Comment by festerhowl** [comment]
![Screenshot (172)](https://user-images.githubusercontent.com/43633844/111032674-69504980-8433-11eb-9da4-0079773d7cdd.png)
guessing the bug is random and probably has something to do with dying or mounting up, but can't say anything for sure, but its nice to have a free ghoul @svijetlo

**Comment by festerhowl** [comment]
will check a bit more and try to reproduce
