### ISSUE TITLE
[NPC] Magister Ilastar 25069 (Isle of Quel'Danas) engages in combat and can be kited

### ISSUE THREAD

**Issue by Bulb1** [WoWManiaUK/Redemption#5359]
**Links**

NPC ID 25069

**What is Happening:**
![image](https://user-images.githubusercontent.com/66064613/110496624-f58e0400-80f5-11eb-9a25-0205ae80f28e.png)
npc went to fight with Dawnblade Hawkrider and when I spoke to him he stopped where he was and he didn't go back to his place

**What Should happen:**
He should go back to his place

**Comment by Rushor** [comment]
why was he actually moving? i cannot reproduce this

**Comment by Bulb1** [comment]
> why was he actually moving? i cannot reproduce this

He went to kill Dawnblade Hawkrider that went inside

**Comment by Rushor** [comment]
is passive flagges now on ptr and should no longer engage this fight

**Comment by jeyrella** [comment]
Fixed, does not engage with hostile mobs now

![image](https://user-images.githubusercontent.com/46089380/110631762-c8e1f700-819e-11eb-9742-865641f14be6.png)
