### ISSUE TITLE
[NPC]  Scryer Arcane Guardian 18568 (Shattrath, Scryer's Tier) doesn't go back after combat

### ISSUE THREAD

**Issue by Bulb1** [WoWManiaUK/Redemption#5360]
Links:
Scryer Arcane Guardian: http://www.wow-mania.com/armory?npc=18568

What is Happening:
![image](https://user-images.githubusercontent.com/66064613/110657405-1a9b7900-81c1-11eb-8e9a-dd19f01a7400.png)

What Should happen:*
they should go back

**Comment by Rushor** [comment]
seemed to work fine on ptr

in code there is a part that let them move back home if there is no victim

**Comment by jeyrella** [comment]
Still cannot reproduce.
