### ISSUE TITLE
[Object] Herb in tree (Redridge Mountains)

### ISSUE THREAD

**Issue by Bulb1** [WoWManiaUK/Redemption#5361]
What is Happening:
![1flower](https://user-images.githubusercontent.com/66064613/110781328-11181c80-8266-11eb-8367-c145632f4fd3.png)
There is herb inside tree and it's inaccessible
What Should happen:
It should be accesable I guess

**Comment by Rushor** [comment]
will fix that

**Comment by jeyrella** [comment]
Item ID 2447
location 34.7, 64.1
zone ID 44

**Comment by jeyrella** [comment]
just needs moving a few yards then.  here is a good spot at the base of the tree it's in
![image](https://user-images.githubusercontent.com/46089380/110820580-25204600-8287-11eb-992d-750eef6126e5.png)
34.4, 64.0

**Comment by jeyrella** [comment]
yup this is a good place, thanks
![image](https://user-images.githubusercontent.com/46089380/111551458-2b775c00-8778-11eb-8841-0a25fc341ec4.png)
