### ISSUE TITLE
[Quest] Kindness - 10804 - Shadowmoon Valley

### ISSUE THREAD

**Issue by jeyrella** [WoWManiaUK/Redemption#5362]
**Links:**
Quest ID 10804
Item ID 31372

**What is Happening:**
When the Giblet item is placed, approximately 50% of the time it fails to attract a drake, as they are spread around a very large area.  This becomes incredibly frustrating as not only do you have to farm another item, the item itself has a 30 second cooldown.  
Absolutely nothing in wowhead or gamepedia mentions any of this, leading to hypothesis that this is an unwanted behaviour.  (Of course there would not be comments about it working 100% of the time, since that is what could be expected.)

**What Should happen:**
Believe the spell range of the item is too low, and should be increased such that it attracts a drake every time.  Probably does not need to be increased by much.

**Comment by Rushor** [comment]
okay issue is that the drakes have  too low active range. they should be able to interact from a bigger distance now :)

**Comment by jeyrella** [comment]
Did 24 drops (i.e. quest 3 times), worked every time.  Job done :)
