### ISSUE TITLE
[Quest] The Flesh Lies... - 10345 - Netherstorm

### ISSUE THREAD

**Issue by Bulb1** [WoWManiaUK/Redemption#5364]
Links:
Quest: https://wow-mania.com/armory/?quest=10345
Withered Corpse: https://wow-mania.com/armory/?npc=20561
Parasitic Fleshbeast: https://wow-mania.com/armory/?npc=20335
What is Happening:
Withered Corpse turns into Parasitic Fleshbeast immediately when player comes near thus there is no time to burn Withered corpse
What Should happen:
Time between Withered Corpse turning into Parasitic Fleshbeast could be longer

**Comment by jeyrella** [comment]
Working exdactly as expected.  Don't get too close to them.
https://youtu.be/T8jR_nXXPII
