### ISSUE TITLE
[Spell] Warlock - Death Coil can crit

### ISSUE THREAD

**Issue by jeyrella** [WoWManiaUK/Redemption#5365]
**Links:**
https://wow-mania.com/armory/?spell=47860

**What is Happening:**
Death Coil can crit.  
![image](https://user-images.githubusercontent.com/46089380/111030129-96333b00-83f8-11eb-8d56-d905bf94cdbb.png)

**What Should happen:**
Death Coil should not crit.  Binary spell (i.e. should either hit or miss, not resist or crit.)
https://wow.gamepedia.com/Death_Coil_(warlock_ability)
![image](https://user-images.githubusercontent.com/46089380/111030270-1d80ae80-83f9-11eb-8259-255853ad6c0f.png)

**Comment by Hajzlopuc** [comment]
https://github.com/WoWManiaUK/Redemption/issues/3951
https://github.com/WoWManiaUK/Redemption/issues/2961

**Comment by Keader** [comment]
Is possible fix the crit issue, but binary resist wont

**Comment by Hajzlopuc** [comment]
Any plans on implementing binary resistance?

**Comment by Keader** [comment]
> Any plans on implementing binary resistance?

i realy dont know, dont depends of me only
