### ISSUE TITLE
[NPC] Sagecedi sometimes swims in mid-air

### ISSUE THREAD

**Issue by jeyrella** [WoWManiaUK/Redemption#5366]
**Links:**
NPC ID 32664

**What is Happening:**
Sagecedi sometimes swims above the platform, when he paths to a specific point:
![image](https://user-images.githubusercontent.com/46089380/111030485-68e78c80-83fa-11eb-86aa-7c458cefd764.png)

**What Should happen:**
Sharks should not swim in mid-air!! :)

**Comment by Rushor** [comment]
should be better now

**Comment by jeyrella** [comment]
stood for 11 mins, paths correctly :)
https://youtu.be/0mwLKo81XJY
