### ISSUE TITLE
[Quest] Unable to summon Image of Wind Trader Marid (Getting Down to Business)

### ISSUE THREAD

**Issue by stealer0517** [WoWManiaUK/Redemption#5368]
https://www.wowhead.com/quest=10270/a-not-so-modest-proposal
https://www.wowhead.com/quest=10271/getting-down-to-business

I completed the quest "A Not-So-Modest Proposal" but I took too long reading the text for "Getting Down to Business" and the Image of Wind Trader Marid despawned.
I tried clicking on the Teleport Pad but the option to summon him was missing.

After completing the first quest you should be able to summon him at any time at the teleport pad. 

![not so modest proposal](https://user-images.githubusercontent.com/6968045/111084606-2a78cd00-84e1-11eb-8942-c961111a5419.png)

**Comment by jeyrella** [comment]
Confirmed.  
If player does not take quest 10271 from Image of Wind Trader Marid, he despawns after about 1 min.  At that point the above dialog is seen and player can no longer take the follow-up quest.

Image of Wind Trader Marid:  https://wow-mania.com/armory/?npc=20518
Objects (not sure which is the correct one):
25020 (Entry: 184109) - [Ethereal Teleport Pad X:4006.810059 Y:1517.189941 Z:-115.932999 MapId:530] 
24927 (Entry: 184073) - [Ethereal Teleport Pad X:4007.110107 Y:1517.150024 Z:-116.362999 MapId:530]

**Comment by stealer0517** [comment]
I don't remember exactly how long it should take, but I do remember being able to get the quest and complete it long before he de spawned. 
Probably 10 minutes should be plenty, but anything over a minute should be good enough.

**Comment by Rushor** [comment]
Image of Wind Trader Marid will be summoned by gossip option.

Gossip option will now be shown if quest https://www.wowhead.com/quest=10270/a-not-so-modest-proposal has been complete (as it is atm) or if quest has been rewarded (which is the case when player rewarded quest and Wind Trader Marid has been despawned.

Once quest https://www.wowhead.com/quest=10271/getting-down-to-business has been taken, gossip option is no longer there. Gossip option is also no longer there when there is already  a Image of Wind Trader Marid spawned.

Image of Wind Trader Marid will stay active for 10 minutes now (up from 1 minute)

**Comment by jeyrella** [comment]
Fixed

Offers quest initially
![image](https://user-images.githubusercontent.com/46089380/111546986-65dcfb00-8770-11eb-8d1f-fe655e44cd18.png)

Correctly Doesn't show gossip if Marid is already summoned
![image](https://user-images.githubusercontent.com/46089380/111547197-b3596800-8770-11eb-938e-bbf7ef3533f9.png)

Despawns after 10 mins
![image](https://user-images.githubusercontent.com/46089380/111552908-38e21580-877b-11eb-8e28-8ce0f158e293.png)

Offers gossip when teleport pad is used again after despawning
![image](https://user-images.githubusercontent.com/46089380/111552930-44354100-877b-11eb-8a14-ef510f29d07c.png)
Quest is offered
![image](https://user-images.githubusercontent.com/46089380/111552949-4b5c4f00-877b-11eb-82ee-bd3e4a507b33.png)
Quest is loaded
![image](https://user-images.githubusercontent.com/46089380/111552984-57e0a780-877b-11eb-82cf-c17bbf9ea219.png)
