### ISSUE TITLE
[Battlegrounds]- Isle of Conquest and Strand of the ancients

### ISSUE THREAD

**Issue by festerhowl** [WoWManiaUK/Redemption#5370]
**Issue**: These bgs have not been popping since past few months despite players using the random bg finder nowadays. I am unsure if these have been disabled intentionally or if its a bug preventing players from ever seeing it but it seems odd to not be able to do the bgs that were released in this expansion

**Comment by Rushor** [comment]
They are disabled at the moment yes

**Comment by festerhowl** [comment]
Is there any reason for this? I mean if those are too buggy atm im sure someone could report those bugs so it can be fixed, unless they cannot be fixed for some reason? @Rushor

**Comment by jeyrella** [comment]
Can't be fixed at the moment.
