### ISSUE TITLE
[Spell] Death Knight - Frost Strike Off-hand

### ISSUE THREAD

**Issue by festerhowl** [WoWManiaUK/Redemption#5371]
**Links:** Frost Strike -  http://www.wow-mania.com/armory?spell=49143

**What is Happening:** Frost strike is doing roughly 62.5% of main hand frost strike damage with its off-hand even without speccing into [3/3 Nerves of Cold Steel](http://www.wow-mania.com/armory?spell=50138) 

**Screenshots:**

**Without nerves of cold steel:**
![Screenshot (220)](https://user-images.githubusercontent.com/43633844/111576400-72943a00-87d6-11eb-825a-32880cdeff55.png)
![Screenshot (221)](https://user-images.githubusercontent.com/43633844/111576406-758f2a80-87d6-11eb-9a9e-a2ad9a815ef3.png)

**With nerves of cold steel:**
![Screenshot (218)](https://user-images.githubusercontent.com/43633844/111576416-7b850b80-87d6-11eb-9f45-97023cd74274.png)
![Screenshot (219)](https://user-images.githubusercontent.com/43633844/111576424-7d4ecf00-87d6-11eb-9259-5973e8cf945f.png)

**What Should happen:** Frost Strike off-hand damage should be roughly 50% of main hand frost strike damage as long as player isn't using Nerves of Cold Steel.

**_Reproduce steps: remove any talents or buffs, gears and stats that could potentially modify the off-hand damage of frost strike and interfere with results. Equip 2x 1 handed statless weapons and use the talents provided below to compare the off-hand frost strike damage with and without nerves of cold steel_**
![Screenshot (207)](https://user-images.githubusercontent.com/43633844/111568044-07426c00-87c6-11eb-846b-9ce33a1169dd.png)
![Screenshot (208)](https://user-images.githubusercontent.com/43633844/111568053-09a4c600-87c6-11eb-9a2f-1670cae767a7.png)

**Comment by hawker357** [comment]
Confirmed on PTR, Frost Strike deals the same MH/OH damage regardless of Nerves of Cold Steel

**Comment by Keader** [comment]
I tested today, and the whole issue looks wrong to me.
First thing is, frost strike should do 55% of weapon damage, not 50%.
The formula used is:

(weaponDamage + spell_bonus) * (weaponPercent)

In main hand spell_bonus = 250, in off hand 125.
weaponPercent = 0.55 in both cases.

In your calculations, you just forgot spell_bonus.

"Description: Instantly strike the enemy, causing X% weapon damage plus Y as Frost damage."

About Nerves of Cold Steel, it's not affecting it at all.
But like i said in other topic (https://github.com/WoWManiaUK/Redemption/issues/5372) i need proofs that it should affect spells.

**Comment by festerhowl** [comment]
>First thing is, frost strike should do 55% of weapon damage, not 50%.

I'm not talking about frost strike's tooltip. Yes the spell does 55% weapon damage+ frost damage but what I'm talking about is the difference in damage between the main and off hand. Since off-hand suffers 50% penalty to weapon damage it also affects the spells cast with off-hand. So for example if I am using same weapons, and my main-hand frost strike does 100 damage then my off-hand frost strike should do roughly 50 damage since it has 50% damage penalty. The spell will still do its thing as it's saying in the tooltip but it will calculate the off-hand damage keeping the penalty in mind.

**Comment by Keader** [comment]
**About Nerves of Cold Steel, it's not affecting it at all.**
And it's not getting any penalty too. That's why damage is always close.

**Comment by festerhowl** [comment]
>And it's not getting any penalty too. That's why damage is always close

from what i tested and what my SS shows, the off damage is about 62.5% of main, so it is definitely getting some penalty, maybe not as much as it should but yes. 

so there are 2 issues to this:

1. Off-hand frost strike isn't getting full 50% penalty. 
2. nerves of cold steel isn't affecting it #5372

**Comment by Keader** [comment]
dude i checked it in code.
It's not getting any penalty.
The effect of "penalty" that you're talking about, is just different basepoint on off hand spell.
Froststrike has 6 spells for "Maind Hand" and others 6 spells for off hand.

**Comment by hawker357** [comment]
So I grabbed a couple screenshots of the Frost Strike damage with and without Nerves of Cold Steel:
![Frost Strike + No Talent](https://user-images.githubusercontent.com/79724094/112145956-e8cbde80-8bd2-11eb-9edf-e0bd25d40f96.png)
![Frost Strike + Talent](https://user-images.githubusercontent.com/79724094/112145965-eb2e3880-8bd2-11eb-98bc-495fe9fa8666.png)

As you can see, having the talent Nerves of Cold Steel does not seem to increase the Off-Hand damage as you would expect.
The actual reason for this is unknown, maybe the buff to OH isn't being applied properly, maybe one of the many spells has an incorrect damage value. We can leave that up to @Keader to find out.

**Comment by Keader** [comment]
Fixed.
Now it should get penalty on off hand, but gets buffs like Nerves of Cold Steel.
Now calculation is correct, close of showed in dr damage

**Comment by svijetlo** [comment]
wo talent 3/3 Nerves of Cold Steel MH over few hits 1400- OH 713 dmg
with talent 3/3 Nerves of Cold Steel Mh over few hits 2700 -oh 1720 dmg
character was wo any gear and just normal weapons' wo stats 2x of same weapons' MH and OH
