### ISSUE TITLE
[Talent] Death Knight- Nerves of Cold Steel

### ISSUE THREAD

**Issue by festerhowl** [WoWManiaUK/Redemption#5372]
**Links:** Nerves of Cold Steel- http://www.wow-mania.com/armory?spell=50138

**What is Happening:** This talent is only affecting the damage of melee white hits on the off-hand but not the damage of abilities such as obliterate, death strike, blood strike, plague strike, rune strike and frost strike . Moreover, the off-hand damage of these abilities are approximately 30-35% of main hand(except for frost strike) even when i am using similar weapons in both hands and taking 3/3 of aforementioned talent.

_**Screenshots:**_

**Obliterate MH & OH**:
![Screenshot (210)](https://user-images.githubusercontent.com/43633844/111572811-5c36b000-87cf-11eb-9f67-2b2ade19d255.png)
![Screenshot (211)](https://user-images.githubusercontent.com/43633844/111572817-5f31a080-87cf-11eb-9d16-b8c8e12492f8.png)

**Death Strike MH & OH**:
![Screenshot (212)](https://user-images.githubusercontent.com/43633844/111573206-11696800-87d0-11eb-8f2f-067ac8e03c31.png)
![Screenshot (213)](https://user-images.githubusercontent.com/43633844/111573210-13cbc200-87d0-11eb-8029-94392e84124c.png)

**Blood Strike MH & OH:**
![Screenshot (216)](https://user-images.githubusercontent.com/43633844/111573339-5ee5d500-87d0-11eb-8601-0e75507a50b6.png)
![Screenshot (217)](https://user-images.githubusercontent.com/43633844/111573349-62795c00-87d0-11eb-8ad1-a1bdadebd0b1.png)

_could not show frost strike meter as it is bugged and scaling differently compared to these abilities_

**What Should happen:** By default the off-hand damage on these abilities should be roughly 50% of main hand when i take 3/3 Threat of Thassarian. The damage should also increase to roughly 62.5%(50+25%*50) when i add Nerves of Cold Steel into the mix.

**Reproduce steps: remove any talents or buffs, gears and stats that could potentially modify the off-hand damage of these abilities(aside from the ones posted in the talents below) and interfere with results. Equip 2x 1 handed similar and statless weapons and use the talents provided to compare the main and off-hand damage done by them.**
![Screenshot (208)](https://user-images.githubusercontent.com/43633844/111574603-cdc42d80-87d2-11eb-83df-04ed96d7ae5a.png)
![Screenshot (203)](https://user-images.githubusercontent.com/43633844/111574768-24316c00-87d3-11eb-8811-e5f67acd17c3.png)

**Comment by hawker357** [comment]
Confirmed on PTR, the abilities mentioned are hitting for between 35-40% of MH damage on the OH attack with 3/3 Nerves of Cold Steel.

**Comment by Keader** [comment]
Any proof that it should affect any spell?
based in how it's implemented in core, should affect only melee hits.

**Comment by festerhowl** [comment]
All the spells that I mentioned do a % of weapon damage+ other damage. So when the weapon damage of my off-hand gets affected by talents such as nerves of cold Steel, it also affects the damage on the spells as my spells such as obliterate and strikes do % of weapon damage. I don't know how I can prove this but its basic math

Suppose my off-hand weapon damage is 20. When I take 3/3 nerves of cold Steel the weapon damage is increased to 25. My spells do % weapon damage, so when the damage of my weapon changes from 20 to 25, my spells start taking % of 25 instead of 20. Can you imagine what a waste of a talent it would be if it only increased my auto attack dmg and that too of the off-hand?

**Comment by Keader** [comment]
It's not a evidence.
But still, i got some old simulators, that inside of source code has this talent present, so... i think that is a valid issue.

**Comment by festerhowl** [comment]
for the sake of clarity and so that some issue doesn't get overlooked going to simplify it a bit:

1. off-hand casts doing around 30-35% of main hand casts, when it should be 50%
2. nerves of cold steel isn't affecting these spells at all.

**Comment by Keader** [comment]
Fixed.
Now Nerves of Cold Steel should affect all spells correctly and damage should be correct now.

**Comment by svijetlo** [comment]
obliterate MH 200 - OH 1100
blood strike MH 1870 - Oh 1200
plague strike MH 1200 -oh 740
