### ISSUE TITLE
[Quest/Object] Gaining the Advantage - Shattrath - 11875

### ISSUE THREAD

**Issue by jeyrella** [WoWManiaUK/Redemption#5374]
**Links:**
Quest 11875
Item 35229
Mining node Objects: 
- 181569 Rich Adamantite Deposit
- 181570 Rich Adamantite Deposit
- 181555 Fel Iron Deposit
- 181557 Khorium Vein
- 181556 Adamantite Deposit

**What is Happening:**

It seems the item is missing the drops from the "mined from" nodes in Outland
https://wow-mania.com/armory/?item=35229#gathered-from-object

**What Should happen:**
From the quest description (and confirmed from wowhead comments), it is clear they should also drop from Outland mining nodes as well
![image](https://user-images.githubusercontent.com/46089380/111867608-14e62600-896d-11eb-8da7-96271aa83a0d.png)

https://www.wowhead.com/item=35229/nether-residue#mined-from-object
![image](https://user-images.githubusercontent.com/46089380/111867676-858d4280-896d-11eb-8d7c-5e7d2a3aaca7.png)
![image](https://user-images.githubusercontent.com/46089380/111867726-cb4a0b00-896d-11eb-8a3e-0b4eaf4bfccf.png)

**While the quest is active**, they should drop from the follow nodes, at the same rate as gathered from Herb nodes (i.e. 25%):
181569 Rich Adamantite Deposit
181570 Rich Adamantite Deposit
181555 Fel Iron Deposit
181557 Khorium Vein
181556 Adamantite Deposit

**Comment by jeyrella** [comment]
Also missing from the Herb nodes for Felweed and Ragveil
181270 Felweed
183044 Felweed
181275 Ragveil
183043 Ragveil

**Comment by Rushor** [comment]
herb, mining and skinning loot that was missing is added :)
