### ISSUE TITLE
[Transmog] A Sister's Bond transmog does not behave correctly on cast

### ISSUE THREAD

**Issue by Shawn6524** [WoWManiaUK/Redemption#5375]
**Links:**

**What is Happening:**the bow sometimes dissapears and when you shoot it looks like im casting a spell and then when does dissapear i have to hit z to pull weapons out to show again 

**What Should happen:** Shoot properly and not bug my equipment
![WoWScrnShot_032021_171517](https://user-images.githubusercontent.com/81049696/111885878-c0f53480-89a0-11eb-8afc-4a0822f46af2.jpg)

**Comment by jeyrella** [comment]
Have fixed your post for you.  Please next time provide a link to the item from the armory, and preferably don't severely typo the item name...

**Comment by jeyrella** [comment]
https://wow-mania.com/armory/?item=150208

**Comment by GMMetaxa** [comment]
Moved to the "xmog check and fix "list.

**Comment by Shawn6524** [comment]
Thank you I’m sorry I’m brand new to GitHub
