### ISSUE TITLE
Worgen's Reputation sheet does not show all Reputations

### ISSUE THREAD

**Issue by Elovena** [WoWManiaUK/Redemption#5376]
![Worgen does not see all reputation faction progress](https://user-images.githubusercontent.com/28679705/111903864-cf992580-8a4c-11eb-8754-fbd22188af77.PNG)

Worgen does not see all reputation factions in reputation faction sheet as seen on the picture. I have Sporeggar honored but it does not show under Outland heading. There are many more Outland factions that does not show in Reputation sheet for worgens. 

Atleast these reputations do not show for sure:
- Cenarion Circle 
- Cenarion Expedition
- Sporeggar 
- Consortium
- Aldor & Scyers

**Comment by svijetlo** [comment]
need to check this, or can some one remind me for sure but i think this used to happen in past also

**Comment by Rushor** [comment]
prolly dbc thing

**Comment by jeyrella** [comment]
Is this related to https://github.com/WoWManiaUK/Redemption/issues/2729 ?

**Comment by svijetlo** [comment]
@jeyrella  yes that is one i did remember in mist long ago bug about worgen missing rep on list

**Comment by wow-mania** [comment]
This is a visual issue only.
The reputation is being computed correctly.
We won't be changing this now.
