### ISSUE TITLE
[Spell] Fishing unable to loot corpse / bobber disappears after a bite

### ISSUE THREAD

**Issue by jeyrella** [WoWManiaUK/Redemption#5377]
**Links:**
https://wow-mania.com/armory/?skill=356

**What is Happening:**
Occasionally when fishing:

1. one gets the error: "You don't have permission to loot that corpse."
2. on clicking the bobber after a bite, it just plain disappears - no "No fish are hooked" or "Your fish got away" message - even with 450 fishing in a low area. Does not seem dependent on skill level or trained skill rank, with or without baits, different poles, etc.

**What Should happen:**
1. Should be able to loot the fish every time.
2. Should either catch a fish or not; bobber should not disappear without some kind of error if there was a "miss".

**Comment by Keader** [comment]
i tried fishing for 10 minutes.
In 10 minutes, everything works fine here.
Until we have a reproduce way, i cant do nothing here... because i cant reproduce.

**Comment by jeyrella** [comment]
.........  wtf.  last week this was reproducible on PTR.  this week, it now seems fine.
@svijetlo, is it just me, am i going crazy here or something?

**Comment by jeyrella** [comment]
i have checked with serveral players on redemption that fish a lot, and they all say they get it.  i will see if i can video it on redemption

**Comment by jeyrella** [comment]
reproducable on redemption with cache cleared, all addons disabled.  watch the 2nd cast
https://youtu.be/NfR_rNMrA20

but cannot reproduce on PTR

**Comment by jeyrella** [comment]
![image](https://user-images.githubusercontent.com/46089380/112307052-5ee64900-8c98-11eb-8a7f-9470a91ba725.png)
happens with auto-loot switch off on live realms, both naxx and redemption.  should always be something in loot, when the fish is successful and bite has happened
however this doesn't seem to happen ever on PTR

**Comment by svijetlo** [comment]
could it be one of those things that on PTR is fine and on live it is not , as irritating as it can be at times , perhaps best for now to leave it be

**Comment by wow-mania** [comment]
I Will mark this as-is. It happens even in retail.
