### ISSUE TITLE
King of Dire Maul Achievement not given

### ISSUE THREAD

**Issue by Ouchman421** [WoWManiaUK/Redemption#5378]
I have killed the appropriate bosses in Dire Maul East and Dire Maul North. I went to Dire Maul West and removed the barrier to kill Immol'thar for The Madness Within quest and for the Dire Maul Achievement. The first time it didn't work, some of the mobs from within the area were still alive so I thought maybe one of them got the killing blow. I tried again today after making sure all other mobs were killed and it still didn't give the achievement or complete the quest.

Character: Rockfoot
Lvl 80 Holy Priest
Attempted on 3/20/2021 and 3/21/2021
Patch 2.9.1

![image](https://user-images.githubusercontent.com/36287894/111912401-9cdc3680-8a26-11eb-84e6-80b6d2f9dbbb.png)

**Comment by jeyrella** [comment]
Well this has definitely worked in the past as I have 4 toons with the achievement.
(Also remember if you're soloing, YOU need to get the killing blow, not your pet.)

Will try it through tomorrow.

**Comment by jeyrella** [comment]
Please can you give a screenshot of the achievement page so we can see which of the 3 bosses it has not worked on.

**Comment by Ouchman421** [comment]
I tried again today. I abandoned the quest and re-accepted it. I took my time to kill all of the summoners in the arena where immol'thar was and then let him go back to 100% health before attacking. I was able to get the achievement and the quest updated as complete.

I'm not sure what the difference was, but thank you for your help. The issue is resolved.
