### ISSUE TITLE
Spawning issue of netherwing eggs

### ISSUE THREAD

**Issue by raenefir2** [WoWManiaUK/Redemption#5379]
**Links:**
https://www.wowhead.com/item=32506/netherwing-egg

**What is Happening:**
After collecting the netherwing eggs they are respawning below the surface beyond reach. Only the steam/particles are visible above the ground 

**What Should happen:**
Fixing spawning coordinates

**Comment by jeyrella** [comment]
Nope.  they do not respawn immediately.  They're not below the surface, they're simply not there at all.

**Comment by jeyrella** [comment]
So there is a very minor cosmetic difference in that the vapours spawn before the eggs do, giving the above illusion.  Visual difference only.  If it's a quick fix will reopen.
