### ISSUE TITLE
[NPC]  Terror Spinner is spawned double - Zul'Drak

### ISSUE THREAD

**Issue by jeyrella** [WoWManiaUK/Redemption#5380]
**What is Happening:**
Getting multiple reports that Rare mobs in Northrend are spawning double in the same place, even after restarts.
![image](https://user-images.githubusercontent.com/46089380/111921442-836dd580-8a8c-11eb-83cb-c345ae1cb7eb.png)

**What Should happen:**
Rare NPCs should be spawned once

**Comment by Rushor** [comment]
hmm this must be fixed individual since there is no speciall all in one pattern for those rares - if fixed it for terror spinner now :o
