### ISSUE TITLE
[Object] Naxxramas entrance portals doubled on 25-man mode

### ISSUE THREAD

**Issue by jeyrella** [WoWManiaUK/Redemption#5381]
**Links:**

**What is Happening:**
On 25-man mode on Naxxramas, one of the 4 entrance portals is normal whereas the other 3 have doubled portals spinning in opposide direction.
As far as I can tell, they still seem to physically function correctly i.e. I think this is a visual issue only.... not certain

"**correct**" portal looks like this
![image](https://user-images.githubusercontent.com/46089380/111925079-3ba47980-8a9f-11eb-8032-bf1fc234559e.png)

151227 (Entry: 196467) - [Doodad_InstanceNewPortal_Green01 X:3680.620117 Y:-1279.770020 Z:244.434006 MapId:571] 
151228 (Entry: 192671) - [Doodad_InstanceNewPortal_Green_Skull01 X:3680.620117 Y:-1279.770020 Z:244.434006 MapId:571] 
Found nearby gameobjects (distance 10.000000): 2

"**incorrect**" portals look like this
![image](https://user-images.githubusercontent.com/46089380/111925073-30e9e480-8a9f-11eb-99d9-948faeb95648.png)

151229 (Entry: 192671) - [Doodad_InstanceNewPortal_Green_Skull01 X:3659.570068 Y:-1280.969971 Z:244.434006 MapId:571] 
151230 (Entry: 196467) - [Doodad_InstanceNewPortal_Green01 X:3659.570068 Y:-1280.969971 Z:244.434006 MapId:571] 
59738 (Entry: 192673) - [Doodad_InstanceNewPortal_Green_Skull03 X:3659.760010 Y:-1281.069946 Z:244.598007 MapId:571] 
Found nearby gameobjects (distance 10.000000): 3

151231 (Entry: 192671) - [Doodad_InstanceNewPortal_Green_Skull01 X:3658.919922 Y:-1259.469971 Z:244.434006 MapId:571] 
151232 (Entry: 196467) - [Doodad_InstanceNewPortal_Green01 X:3658.919922 Y:-1259.469971 Z:244.434006 MapId:571] 
59714 (Entry: 192672) - [Doodad_InstanceNewPortal_Green_Skull02 X:3658.790039 Y:-1259.449951 Z:244.598007 MapId:571] 
Found nearby gameobjects (distance 10.000000): 3

59743 (Entry: 192674) - [Doodad_InstanceNewPortal_Green_Skull04 X:3680.399902 Y:-1258.479980 Z:244.598007 MapId:571] 
151233 (Entry: 192671) - [Doodad_InstanceNewPortal_Green_Skull01 X:3680.620117 Y:-1258.410034 Z:244.434006 MapId:571] 
151234 (Entry: 196467) - [Doodad_InstanceNewPortal_Green01 X:3680.620117 Y:-1258.410034 Z:244.434006 MapId:571] 
Found nearby gameobjects (distance 10.000000): 3

**What Should happen:**

the 3 portals that have double entrances should be single

**Comment by Rushor** [comment]
should be good now
