### ISSUE TITLE
[NPC] Ethereal Nethermancer 21370 doesn't use skills and doesn't move when aggroed from afar - Terrokar Forest near Tomb of Lights

### ISSUE THREAD

**Issue by Bulb1** [WoWManiaUK/Redemption#5382]
Links:
https://wow-mania.com/armory/?npc=21370
What is Happening:
![image](https://user-images.githubusercontent.com/66064613/112137953-36474c00-8bd1-11eb-807d-1caadb6e7590.png)

**Comment by Rushor** [comment]
fixing it

**Comment by jeyrella** [comment]
Yep, is on the list of NPCs with known SAI issues that we previously compiled

**Comment by Rushor** [comment]
should be good now
