### ISSUE TITLE
[NPC] Skithian Dreadhawk 18452 doesn't use skills when aggroed and doesn't move - Terrokar Forest, Veil Skith

### ISSUE THREAD

**Issue by Bulb1** [WoWManiaUK/Redemption#5383]
Links:
https://wow-mania.com/armory/?npc=18452
What is Happening:
![image](https://user-images.githubusercontent.com/66064613/112138872-51ff2200-8bd2-11eb-90d9-c6882ed073a9.png)

**Comment by jeyrella** [comment]
Yep, is on the list of NPCs with known SAI issues
![image](https://user-images.githubusercontent.com/46089380/112184663-52f67a80-8bf7-11eb-8d41-c9e02e87f0be.png)

**Comment by Rushor** [comment]
should be good now
