### ISSUE TITLE
[Object] Bubbly Fissure is below ground - Borean Tundra

### ISSUE THREAD

**Issue by jeyrella** [WoWManiaUK/Redemption#5384]
**Links:**
76929 (Entry: 187454) - [Bubbly Fissure X:3830.719971 Y:5984.779785 Z:-126.779999 MapId:571]
76928 (Entry: 187453) - [Bubbly Fissure X:3489.600098 Y:6303.189941 Z:-125.574997 MapId:571] 

**What is Happening:**
Both of these Bubbly Fissure objects in Borean Tundra are under the ground
76929 (Entry: 187454) - [Bubbly Fissure X:3830.719971 Y:5984.779785 Z:-126.779999 MapId:571] 
76928 (Entry: 187453) - [Bubbly Fissure X:3489.600098 Y:6303.189941 Z:-125.574997 MapId:571] 
![image](https://user-images.githubusercontent.com/46089380/112322130-89d89900-8ca8-11eb-920f-1905bc2c7fc4.png)

**What Should happen:**
Adjust the z-axis coordinates so object is above ground

**Comment by Rushor** [comment]
should be fixed within next restart of ptr
