### ISSUE TITLE
[Object] Bubbly Fissure in Desolace & Moonglade does not restore player breath bar

### ISSUE THREAD

**Issue by jeyrella** [WoWManiaUK/Redemption#5385]
**Links:**
Obj ID 177524

**What is Happening:**
All guids of Bubbly Fissure in the Desolace zone with obj ID 177524 are not restoring the player's breath when near.
https://youtu.be/BfLstF2BhMA

Moonglade
49216 (Entry: 177524) - [Bubbly Fissure X:7675.390137 Y:-2659.360107 Z:406.346008 MapId:1] 
49217 (Entry: 177524) - [Bubbly Fissure X:7697.359863 Y:-2569.159912 Z:400.309998 MapId:1] 
Desolace
31897 (Entry: 177524) - [Bubbly Fissure X:-498.032990 Y:2739.479980 Z:-30.666599 MapId:1] 
31896 (Entry: 177524) - [Bubbly Fissure X:-588.114014 Y:2858.040039 Z:-38.536900 MapId:1] 
31903 (Entry: 177524) - [Bubbly Fissure X:161.033997 Y:2742.560059 Z:-71.472900 MapId:1] 
31906 (Entry: 177524) - [Bubbly Fissure X:55.284199 Y:2842.689941 Z:-83.067703 MapId:1] 
31905 (Entry: 177524) - [Bubbly Fissure X:-22.351700 Y:2831.510010 Z:-34.259602 MapId:1] 
31899 (Entry: 177524) - [Bubbly Fissure X:-76.645500 Y:2685.810059 Z:-99.104301 MapId:1] 
31902 (Entry: 177524) - [Bubbly Fissure X:-147.744995 Y:2589.379883 Z:-48.167900 MapId:1] 
31907 (Entry: 177524) - [Bubbly Fissure X:-1829.400024 Y:3280.409912 Z:-68.253403 MapId:1] 
31684 (Entry: 177524) - [Bubbly Fissure X:-1876.680054 Y:3378.850098 Z:-70.177101 MapId:1] 
31900 (Entry: 177524) - [Bubbly Fissure X:-1985.920044 Y:3374.379883 Z:-80.173302 MapId:1] 
Found gameobjects 177524: 13 

**What Should happen:**
Should restore player's breath bar.
This version of the Bubbly Fissure found in Borean **DOES work correctly** and restore breath:
76930 (Entry: 187455) - [Bubbly Fissure X:4007.939941 Y:6009.370117 Z:-125.091003 MapId:571] 

Spell 17775 is cast as aura on player.

![image](https://user-images.githubusercontent.com/46089380/112325906-fb661680-8cab-11eb-8cd4-d15cd789d827.png)

**Comment by Rushor** [comment]
should work now
