### ISSUE TITLE
[NPC] High Inquisitor Whitemane not immune while resurrecting Mograine / In the Name of the Light quest is not completed

### ISSUE THREAD

**Issue by jeyrella** [WoWManiaUK/Redemption#5386]
**Links:**
https://wow-mania.com/armory/?npc=3977

**What is Happening:**
High Inquisitor Whitemane is not immune while resurrecting Mograine.

This means if she is killed extremely quickly before being able to cast the resurrect, or there are dots on while casting the resurrection that kill her, then 
- player is left in combat
- quest "In the Name of the Light" is not rewarded for the Mograine kill (as Mograine is never resurrected)
- player does not receive the achievement for dungeon completion.

![image](https://user-images.githubusercontent.com/46089380/112354994-23ae3f00-8cc5-11eb-8fb3-6f29e4ecef00.png)
![image](https://user-images.githubusercontent.com/46089380/112355306-6d972500-8cc5-11eb-9a79-4568437ebd67.png)

**What Should happen:**
This era-relevant video shows that even if Whitemane is brought to 0HP, she becomes immune for the cast while resurrecting Mograine.
https://youtu.be/LBHyuhUCJ6o?t=220

**Comment by Rushor** [comment]
all dot auras should now get removed when she is in the resurrect phase
