### ISSUE TITLE
[NPC] Dawnblade Marksmans that are shooting target turn to [ROGUE SPELL] distract for short time

### ISSUE THREAD

**Issue by Bulb1** [WoWManiaUK/Redemption#5387]
Links:
Dawnblade Marksman: https://wow-mania.com/armory/?npc=24979
Distract: https://wow-mania.com/armory/?spell=1725
![image](https://user-images.githubusercontent.com/66064613/112362018-4562f280-8cd4-11eb-9b70-4a7588ed37cf.png)
What is Happening: They turn to distract for short time 
What Should happen: They should be attracted to distract for 10s

**Comment by Rushor** [comment]
they should no longer cast spells while beeing distracted. the other orientation thing is a generic spell thing - maybe for Keader?
