### ISSUE TITLE
[Quest] The Astongue Corruptors become attackable after only one totem killed 10685 - Shadowmoon Valley

### ISSUE THREAD

**Issue by womptista** [WoWManiaUK/Redemption#5388]
Quest Link: 
https://www.wow-mania.com/armory/?quest=10685 (scryer)
https://www.wow-mania.com/armory/?quest=10574 (aldor)

NPCs:
21710
21711
21416
21709

Video Evidence: https://youtu.be/12RWBd9OK2w

The NPC is suppose to be invulnerable while totems are alive.

The NPC should not be able to be hit While the totems are alive.
Link to what is suppose to happen: https://www.wowhead.com/quest=10685/the-ashtongue-corruptors#comments

**Comment by jeyrella** [comment]
Hmmm
Seems immune when all 3 totems are up
![image](https://user-images.githubusercontent.com/46089380/112504378-9ed62a80-8d83-11eb-9f6e-726df3228b71.png)

But when only one is killed, then they lose immunity
![image](https://user-images.githubusercontent.com/46089380/112504512-c3ca9d80-8d83-11eb-8701-eeb02e9c8123.png)


What Should be happening:  all 3 totems must be killed before the Shamans become active

**Comment by jeyrella** [comment]
It seems that Eykenen (21710) and Lakaan (21416) work correctly, but the others become attackable after only 1 totem killed

**Comment by Rushor** [comment]
should all be immune now until all totems are killed now. each totem will spawn 3 adds now on kill as seen in https://www.youtube.com/watch?v=rf0POn7MdrE

**Comment by jeyrella** [comment]
It should be 2 elementals, not three.  That vidoe only shows 2:
![image](https://user-images.githubusercontent.com/46089380/112827809-be709a00-9086-11eb-84cd-c87be2dbcb76.png)
![image](https://user-images.githubusercontent.com/46089380/112827894-dfd18600-9086-11eb-8be7-de6a20a84965.png)
![image](https://user-images.githubusercontent.com/46089380/112828247-60908200-9087-11eb-8f34-99d8910b7e08.png)

plus
![image](https://user-images.githubusercontent.com/46089380/112827692-984afa00-9086-11eb-8e94-c9a9a788b5c0.png)

**Comment by jeyrella** [comment]
They also should not form AT the totem itself, but about 10 yards away and aggro to the player.

**Comment by Rushor** [comment]
Alright

**Comment by Rushor** [comment]
alright summons should be a bit away from totem now and only 2 elementals will spawn after totem is killed
