### ISSUE TITLE
[NPC] Windy Cloud can be skinned for air motes according to armory

### ISSUE THREAD

**Issue by Bulb1** [WoWManiaUK/Redemption#5389]
Links:
https://wow-mania.com/armory/?npc=24222
What is Happening: armory says that it can be skinned while elementals can't be +it can't be killed cus it's NPC for engineers
What Should happen: armory should not say that it can be skinned

**Comment by jeyrella** [comment]
Think this is more likely that the mob itself is incorrectly skinnable, than the armory being incorrect

**Comment by jeyrella** [comment]
So.  This mob is not attackable, even as GM, so can't be killed, so can't be skinned.  Even so, should be corrected so that the armory is correct and does not mislead players
![image](https://user-images.githubusercontent.com/46089380/112509671-97fde680-8d88-11eb-8e31-12962bdd5d4f.png)

**Comment by Rushor** [comment]
Will change that flag

**Comment by Rushor** [comment]
The loot for those objects is all handled in skinning_loot_template. It is just a visual thingy. You cannot skin it, but the loot that is added while interacting with it while using "Zapthrottle Mote Extractor" is handled in the skinning loot template of it. That's the way the loot is handled in general for "Gas cloud" creature types
