### ISSUE TITLE
[NPC] Taretha's ([DUNGEON] The Escape From Durnholde) dialogue doesn't work

### ISSUE THREAD

**Issue by Bulb1** [WoWManiaUK/Redemption#5391]
Links: 
Taretha: https://wow-mania.com/armory/?npc=18887
What is Happening:
![image](https://user-images.githubusercontent.com/66064613/112680453-b093fc80-8e6d-11eb-8387-0362f2cfecbb.png)
Nothing happens after clicking dialogue

**Comment by jeyrella** [comment]
You have to wait for Thrall to actually be there first.

**Comment by Bulb1** [comment]
https://www.youtube.com/watch?v=r_-IwghhQLo doesn't work even after thrall goes away
