### ISSUE TITLE
[NPC] Time Keeper 17918 from [ITEM] Chrono-beacon 24289 spawns perished ([DUNGEON] The Black Morass 10296)

### ISSUE THREAD

**Issue by Bulb1** [WoWManiaUK/Redemption#5392]
Links:
Time Keeper: https://wow-mania.com/armory/?npc=17918
Chrono-beacon: https://wow-mania.com/armory/?item=24289
The Black Morass: https://wow-mania.com/armory/?quest=10296
What is Happening:
![unknown](https://user-images.githubusercontent.com/66064613/112682931-133ac780-8e71-11eb-8451-1773301a0b48.png)
It spawns perished
What Should happen: It's meant to help with fighting

**Comment by Rushor** [comment]
the creature should help in combat now
