### ISSUE TITLE
[ITEM] Rightous Weapon Coating 34539 can be applied anywhere/doesn't fade after leaving Isle of Quel'Danas

### ISSUE THREAD

**Issue by Bulb1** [WoWManiaUK/Redemption#5393]
Links:
https://wow-mania.com/armory/?item=34539
What is Happening:
I'm in Zangarmarsh and I can still apply it
![image](https://user-images.githubusercontent.com/66064613/112730356-6ecc8a00-8f31-11eb-8d6b-5a7eaffbdefb.png)
What Should happen:
It shouldn't be applicable anywhere besides Isle of Quel'Danas/MGT/SWP

**Comment by jeyrella** [comment]
You can still apply it.  It just won't proc.
