### ISSUE TITLE
[Battleground] WG Siege Portal teleports under the terrain

### ISSUE THREAD

**Issue by Greywolf59** [WoWManiaUK/Redemption#5394]
**Links:**

**What is Happening:**
Today in WG I made a siege engine in Eastern Fortress Vehicle Workshop, drove it to the siege teleport. Instead of being ported outside the gates I was kicked out of the siege and sent flying under th textures to my death. I was Horde and without cannon passenger. I haven't noticed if the vehicle itself got ported or not.

**What Should happen:**
Siege should get ported outside the walls. Preferably with me in it.

**Comment by jeyrella** [comment]
This has worked in the past, so some recent change elsewhere has made this happen.
Confirmed on both East and West, Horde and Alliance

https://youtu.be/6rxrAF6sXNc
https://youtu.be/2iQRymak9Js

**Comment by wow-mania** [comment]
OK, this is really pissing me off and making me wonder.
How are things magically breaking?

**Comment by Rushor** [comment]
is related to the teleporters not working  https://github.com/WoWManiaUK/Redemption/issues/5369#issue-832347461Point: The Defender's Portal at 44.1, 22.5 is not working. Will fix the case now

**Comment by Rushor** [comment]
test now pls. 2 things must be tested:

- Teleport of the person teleporters in front and around fortress
- Teleport of vehicles that are created inside fortress to get ported outside
