### ISSUE TITLE
[NPC] Neltharaku 21657 Flying too quickly

### ISSUE THREAD

**Issue by stealer0517** [WoWManiaUK/Redemption#5395]
https://www.wowhead.com/npc=21657/neltharaku
https://www.wowhead.com/quest=10811/seek-out-neltharaku
https://www.wowhead.com/quest=10814/neltharakus-tale

If you watch the video from the quest seek out Nelthraku you'll see that it should be casually flying at about walking speed, if not a little faster.

In game Nelthraku is flying at "full" speed and even on my +280 mount I can barely catch up.
Paired with the issue of NPCs being rude and walking away from you mid conversation it makes doing the quest "Neltharaku's Tale" extremely long and tedious.

**Comment by Rushor** [comment]
Will reduce his speed to Match the value :)

**Comment by Rushor** [comment]
speed is reduced now (testable on ptr)
