### ISSUE TITLE
Falling through ground as defenders in wintergrasp

### ISSUE THREAD

**Issue by theonykry** [WoWManiaUK/Redemption#5396]
**Links:**

**What is Happening:**
Today i defended Wintergrasp, as Spriest, female Dwarf. I had Rank 2 so i was able to build a siege engine. Now the attackers had 3 sieges, still outside the fort, so i built a siege inside. I drove it close to the wall and then changed position within the vehicle to the cannon. Once i wanted to switch back into the driver seat, it pulled me out of the vehicle threw me through the ground and i kept falling for like 20s till i died. I spawned at the graveyard inside the fort at half HP/Mana. I thought it was only me, but it happend to me repeatedly 3 times in a row over timeperiod of 4min. My built vehicle disappeared each time btw. Now it was not only me who expierenced this bug. atleast 7/16 players had same experience, allthought i do not know if they also expierenced it the same way (by changing vehicle seats) as i did. i know a gnome rogue, Nelf hunter, human dk. maybe the classes affect it. Also outside of the fort i was able to build and change seats without any problems. the animation of "the throw" looks very familiar, like when hitting a shadowtrap in LK hc, but instead of getting thrown up, i was "pulled/thrown" down through the map.

**What Should happen:**
not getting thrown through the ground, by changing seats in a siege engine inside the WG fort.

**Comment by Rushor** [comment]
is duplicate
