### ISSUE TITLE
[SPELL] Eye of Kilrogg has way too much HP

### ISSUE THREAD

**Issue by Bulb1** [WoWManiaUK/Redemption#5399]
Links:
eye of kilrogg: https://wow-mania.com/armory/?spell=126
What is Happening:
![image](https://user-images.githubusercontent.com/66064613/112879526-88a0d500-90c9-11eb-9186-93b2ec143e5e.png)
![image](https://user-images.githubusercontent.com/66064613/112879553-92c2d380-90c9-11eb-8634-2c64a3c60ff0.png)
What Should happen:
It should be one hit to kill it

**Comment by jeyrella** [comment]
Should have 1hp as far as I can tell  from historical transcripts
https://wowpedia.fandom.com/wiki/Eye_of_Kilrogg_(warlock_ability)?oldid=4879243
![image](https://user-images.githubusercontent.com/46089380/112887941-ab33ed80-90cb-11eb-8e6f-92280136eb65.png)

> Due to its low health, any mob will one shot the eye

https://wowpedia.fandom.com/wiki/Patch_0.10

**Comment by hawker357** [comment]
Tested at levels 22,30,40,50,60,70,80 all Eye's summoned have 1hp as expected.
