### ISSUE TITLE
[NPC] Marshlight Bleeder inside terrain - Zangarmarsh

### ISSUE THREAD

**Issue by jeyrella** [WoWManiaUK/Redemption#5400]
**Links:**
DB GUID: 64727, current GUID: 6396.
Entry: 18133.
DisplayID: 19252 (Native: 19252).

**What is Happening:**
Marshlight Bleeder inside terrain, and thus not killable.

![image](https://user-images.githubusercontent.com/46089380/113048405-688d1680-919a-11eb-97bb-f895e5e99109.png)

NPC currently selected by player:
DB GUID: 64727, current GUID: 6396.
Faction: 14.
npcFlags: 0.
Entry: 18133.
DisplayID: 19252 (Native: 19252).
Level: 62.
EquipmentId: 0 (Original: 0).
Health (base): 5341. (max): 5341. (current): 5341.
InhabitType: 3
Unit Flags: 0
Unit Flags 2: 2048.
Dynamic Flags: 0.
Faction Template: 14.
SpawnTime: Full:5m Remaining:0s
Loot: 18133 Pickpocket: 0 Skinning: 0
InstanceID: 0
Phasemask: 1
Armor: 4391
Position: -416.219421 8271.898438 22.183685.
AIName: SmartAI ScriptName: 
Flags Extra: 0
MechanicImmuneMask: 0

**What Should happen:**
Be not inside the terrain!

**Comment by Rushor** [comment]
moved to a better place close to the water :)

.go c 64727

**Comment by hawker357** [comment]
Much better position now near the water.
![Screenshot (14)](https://user-images.githubusercontent.com/79724094/113292537-8ec2cb80-92ec-11eb-8ab8-0b6149565441.png)
