### ISSUE TITLE
[NPC / SAI] Skettis Windwalker does not aggro or cast spells correctly

### ISSUE THREAD

**Issue by womptista** [WoWManiaUK/Redemption#5404]
**Links:**
Link To video Prof: https://youtu.be/yj3TK32GNV8
Link to NPC on wow-mania armory: https://www.wow-mania.com/armory/?npc=21649#abilities

**What is Happening:**
Location: Skettis Islands. [lower right corner of Terokkar Forrest]
Seen issue: Skettis Windwalkers will only attack once then continue to cast either {Cyclone} which seems to switch finish cast into {Shadow Mend} which heals them. They are healing them self even when not needing to heal.

**What Should happen:**
I am unable to locate anything that shows that the NPC should attack more than once I am just assuming that it is supposed to.

**Comment by jeyrella** [comment]
on list of bad SAI NPCs
![image](https://user-images.githubusercontent.com/46089380/113299879-3f34cd80-92f5-11eb-9457-c51d146110c3.png)

**Comment by jeyrella** [comment]
@Rushor Can I suggest that all these 4 are fixed at same time, as they are all in that subzone, and part of the Skyguard rep grind

21911
21728
21650
21649

**Comment by Rushor** [comment]
all 4 fixed :)
