### ISSUE TITLE
[NPC] Silver Covenant Guardian Mage

### ISSUE THREAD

**Issue by Wolch** [WoWManiaUK/Redemption#5405]
**What is Happening:**

The Silver Covenant Guardian Mage near Sister Sorcerous shop in Dalaran is to eager to do her duty. Aa a result, she teleports Horde players the moment they exit the shop, when in fact they are nowhere near to entering the Alliance enclave.

**Comment by Rushor** [comment]
cannot confirm that :o https://gyazo.com/e8be6e827cdd9b3de1f8d2ef0a470660

**Comment by Rushor** [comment]
is related to the prevention that horde players can jump into the alliance zone.

should be better now
