### ISSUE TITLE
Lost items from Auction House

### ISSUE THREAD

**Issue by Fishaak** [WoWManiaUK/Redemption#5406]
**Links:**

**What is Happening:**
I had 2 Glacial Bags in AH, they was few hours before expiration when i went offline, after about eight hours later i come online and both Bags was lost, not in AH, not in Mailbox, just nowhere.. After 2 days of waiting still nothing come to mailbox.

**What Should happen:**

**Comment by jeyrella** [comment]
Nothing we can do about that from here.

**Comment by Fishaak** [comment]
GM told me that you can...
