### ISSUE TITLE
[Quest] Bloodpetal Sprouts - No text in quest, NPC offers as ? as if completed - Un'goro 4144 

### ISSUE THREAD

**Issue by jeyrella** [WoWManiaUK/Redemption#5407]
**Links:**
Quest "Bloodpetal Sprouts"  https://wow-mania.com/armory/?quest=4144
NPC "Muigin":  https://wow-mania.com/armory/?npc=9119

**What is Happening:**
Once quest [4143 Haze of Evil](https://wow-mania.com/armory/?quest=4143) is complete, [Muigin](https://wow-mania.com/armory/?npc=9119) appears to offer the follow-up quest [4144](https://wow-mania.com/armory/?quest=4144) as if it is already completed:
![image](https://user-images.githubusercontent.com/46089380/113485572-23bcf480-94a6-11eb-948f-65a7b0c84f43.png)

When the player "accepts" the quest, the dialogue shows no text
![image](https://user-images.githubusercontent.com/46089380/113485589-3c2d0f00-94a6-11eb-9d23-e8ea45eb4f60.png)

When in the player's quest log, similarly no text is shown:
![image](https://user-images.githubusercontent.com/46089380/113485599-5830b080-94a6-11eb-8424-76f689326a9e.png)

**What Should happen:**
After 4143 is complete, Muigin should offer 4144 with ! mark, not with ? as if it is already complete.

In the armory, the quest text for 4144 is present:

```
Here's the plan, <name>: Go out and collect some bloodpetal sprouts -- you know, the plants that haven't fully sprouted yet, and bring them here. Then I'll see what the Atal'ai haze can do.

You may think I'm vengeful... Actually, you'd be right about that!

Truth is, I know the way out of here, but until Larion will admit that I'm right, I'm staying right here!

So off with you, find those bloodpetal sprouts and let's have some fun!

333333333 | Bloodpetal Sprout (3)
-- | --

### Completion 
Here goes nothing, <name>! This will get Larion's attention!
```

**Comment by Rushor** [comment]
the texts are added now

**Comment by Rushor** [comment]
this requires cleared cache

**Comment by jeyrella** [comment]
![image](https://user-images.githubusercontent.com/46089380/114011349-06e54000-985d-11eb-9a84-87e7501658a8.png)
