### ISSUE TITLE
[NPC / Quest] Kristen Dipswitch does not walk to camp; Gankly spawns without her present

### ISSUE THREAD

**Issue by jeyrella** [WoWManiaUK/Redemption#5408]
**Links:**

Kristen Dipswitch:  https://wow-mania.com/armory/?npc=18294
Gankly Rottenfist:  https://wow-mania.com/armory/?npc=18297

https://wow-mania.com/armory/?quest=9897

**What is Happening:**
Kristen is always spawned.  She never walks to the camp.
Gankly spawns periodically in the camp without Kristen ever being there.

**What Should happen:**
Kristen should spawn every 1hr 30 mins.  She should then run to the camp after 5 mins.  Only when she reaches the camp should Gankly spawn (stealthed), creep up to her from behind and attack.
![image](https://user-images.githubusercontent.com/46089380/113486292-df335800-94a9-11eb-9820-d5652ae0bd27.png)
![image](https://user-images.githubusercontent.com/46089380/113486349-1f92d600-94aa-11eb-9614-bfb51f0cb17a.png)

**Comment by Rushor** [comment]
all added

**Comment by svijetlo** [comment]
gnome walks to camp ugly one spawn and they fight

**Comment by Rushor** [comment]
fight! very good!
