### ISSUE TITLE
[NPC] Shienor Sorcerer 18450 doesn't use all skills

### ISSUE THREAD

**Issue by Bulb1** [WoWManiaUK/Redemption#5409]
https://wow-mania.com/armory/?npc=18450
![image](https://user-images.githubusercontent.com/66064613/113504360-e86b0600-9537-11eb-9525-f7d2f75bf1bd.png)

**Comment by jeyrella** [comment]
Along with 18452, 18319, and 18457

**Comment by Rushor** [comment]
all 4 fixed
