### ISSUE TITLE
[QUEST] Return to Abyssal Shelf 10346 should have blue ? since it's repeatable quest

### ISSUE THREAD

**Issue by Bulb1** [WoWManiaUK/Redemption#5410]
ally: https://wow-mania.com/armory/?quest=10346
horde: https://wow-mania.com/armory/?quest=10347
![unknown](https://user-images.githubusercontent.com/66064613/113504422-4ac40680-9538-11eb-90f1-9f55bbae4f9d.png)

**Comment by Rushor** [comment]
fix for this was https://github.com/TrinityCoreLegacy/TrinityCore/commit/d896f7940c1241de12fdb59750fe6b55832635f5 and it is already added to the core :O

**Comment by Rushor** [comment]
Can you may check Keader? :)

**Comment by Rushor** [comment]
ahh nvm it should actually be like that

in tbc area quests are yellow, in wotlk area they are marked as blue

source:

From http://wowwiki.wikia.com/Quest
Daily quests:
In Burning Crusade most quests of this type appear with the standard marker (Quest Avail 16x16), regardless of how often you do them, but in Wrath of the Lich King several quest appear with the RRQ marker (RRQ Avail 16x16) that count against your daily quest limit.
