### ISSUE TITLE
[Quest] Wanted: Arcatraz Sentinels normal mode quest progress is not counted when Sentinels killed on Heroic mode of dungeon

### ISSUE THREAD

**Issue by lordiman** [WoWManiaUK/Redemption#5411]
**Links:**  https://www.wow-mania.com/armory/?quest=11389

**What is Happening:**  quest says that i must kill 5 mobs, and i do it, but quest is not complete. i was talking to GM, he checked this quest on his own, and tells me that is something wrong with this quest.

> EDIT BY JEYRELLA:
> Note:  this only applies to when completing the daily Normal quest while in Heroic mode of dungeon.  Normal mode dungeon works correctly.
> 

**What Should happen:** quest must will be complete, when it knows that i slain all mobs, but it dont even know that im killing those mobs. In the end quest is not complete at all. I cant turn it to quest giver.

![WoWScrnShot_040521_023846](https://user-images.githubusercontent.com/81937894/113525952-260f7380-95b8-11eb-9172-319ae4cfeb06.jpg)
![WoWScrnShot_040521_023648](https://user-images.githubusercontent.com/81937894/113525954-2740a080-95b8-11eb-8391-26d32bdbb324.jpg)

**Comment by jeyrella** [comment]
Seemed to work perfectly, and have done this quest many times myself on Naxx...  
Are you certain you were killing the correct mobs?
![image](https://user-images.githubusercontent.com/46089380/113552713-71dd0f80-95ee-11eb-92e3-94c4e4b32d60.png)
![image](https://user-images.githubusercontent.com/46089380/113552777-8b7e5700-95ee-11eb-9000-8aeeed79057a.png)
![image](https://user-images.githubusercontent.com/46089380/113552794-920cce80-95ee-11eb-87e8-dba68e8d0663.png)
![image](https://user-images.githubusercontent.com/46089380/113552823-9c2ecd00-95ee-11eb-8c5c-9ab224d65c06.png)

**Comment by jeyrella** [comment]
Ok, found the issue, it is that the *normal* version quest does not update when killing the Sentinels in the _heroic_ mode of the dungeon, but normal mode dungeon works fine.

Will update the titcket title.

Rushor, the following NPCs need to count towards quest 11389 completion.

NPC currently selected by player:
DB GUID: 86054, current GUID: 23.
Faction: 16.
npcFlags: 0.
Entry: 20869.
DisplayID: 19971 (Native: 19971).
Level: 70.
EquipmentId: 0 (Original: 0).
Health (base): 155788. (max): 155788. (current): 62315.
InhabitType: 3
Unit Flags: 524288
UNIT_FLAG_IN_COMBAT (0x80000)
Unit Flags 2: 2048.
Dynamic Flags: 0.
Faction Template: 16.
SpawnTime: Full:2h Remaining:0s
Loot: 20869 Pickpocket: 0 Skinning: 0
InstanceID: 6
Phasemask: 1
Armor: 6792
Position: 263.849609 -63.185513 22.370020.
AIName: SmartAI ScriptName: 
Flags Extra: 0
MechanicImmuneMask: 16384
MECHANIC_BLEED (0xF)

**Comment by Rushor** [comment]
credit is given in HC now aswell

**Comment by jeyrella** [comment]
Fixed
![image](https://user-images.githubusercontent.com/46089380/114010832-74dd3780-985c-11eb-981e-b2ae01db4adf.png)
![image](https://user-images.githubusercontent.com/46089380/114010896-8292bd00-985c-11eb-8785-1598cfd08346.png)
![image](https://user-images.githubusercontent.com/46089380/114010807-6e4ec000-985c-11eb-8f21-2e3fdb9ad7de.png)
