### ISSUE TITLE
Feral Dudu Clearcasting

### ISSUE THREAD

**Issue by ObiMeowCatnobi** [WoWManiaUK/Redemption#5413]
**Links:**

**What is Happening:**
With the Server's Custom Glyph "Fangs of Ashamane" i was not able to get a single Clearcast procc in a whole ICC or Random Dungeon. I also tried it again after i replaced the glyph and i worked again as it should. I dont know it the other custom apperance glyphs for feral druid have the same problem. 

**What Should happen:**
It should work like in a normal cut for cause it just changes the apperance.

**Comment by Keader** [comment]
Cannot reproduce.
Even with glyph, everything works fine.

https://youtu.be/I_Tz2njFWsw
