### ISSUE TITLE
[NPC] Haldor the Compulsive (Aldor) is accesabble without rep

### ISSUE THREAD

**Issue by Bulb1** [WoWManiaUK/Redemption#5414]
Links:
https://www.wowhead.com/npc=23484/haldor-the-compulsive#comments
Haldor the Compulsive: https://wow-mania.com/armory/?npc=23484
Arcanist Xorith: https://wow-mania.com/armory/?npc=23483
What is Happening:
I can access him with my new warlock that doesn't have any rep 
![image](https://user-images.githubusercontent.com/66064613/113593206-6dd4e000-9636-11eb-9201-91a68378b2b0.png)
What Should happen:
![image](https://user-images.githubusercontent.com/66064613/113593675-f81d4400-9636-11eb-9f9c-45fbbf6737ba.png)
He shouldn't be accesable as Arcanist Xorith cus It's kind of unfair to scryers players 
![image](https://user-images.githubusercontent.com/66064613/113593433-b7252f80-9636-11eb-8680-cdac54af7b53.png)

**Comment by jeyrella** [comment]
Confirmed.  https://wowpedia.fandom.com/wiki/Haldor_the_Compulsive

> Haldor the Compulsive of the Aldor will sell specialized flasks only usable in raid zones to players who are exalted with Cenarion Expedition, the Sha'tar and the Aldor.

Not only that, but also needs to be Cenarion and Sha'tar exalted too, which he also isn't set to observe
![image](https://user-images.githubusercontent.com/46089380/113613560-4e937e00-9649-11eb-8df5-182560228495.png)

**Comment by Rushor** [comment]
conditions to see items only if rep IDs 932, 935, 942 are exalted should be added now

**Comment by svijetlo** [comment]
![WoWScrnShot_040821_174353](https://user-images.githubusercontent.com/61908373/114056531-0fa43900-9892-11eb-8fc9-e3111b1d6115.jpg)
