### ISSUE TITLE
[SPELL] Eye of Kilrogg affected by Blood Pact

### ISSUE THREAD

**Issue by Bulb1** [WoWManiaUK/Redemption#5415]
Links:
eye of kilrogg: https://wow-mania.com/armory/?spell=126
What is Happening:
![image](https://user-images.githubusercontent.com/66064613/113620584-cf0eaa80-965a-11eb-9b3a-079295c2fccf.png)
What should happen:
It's supposed to have 1hp

**Comment by Bulb1** [comment]
https://github.com/WoWManiaUK/Redemption/issues/5399 first report here

**Comment by hawker357** [comment]
Seems to be affected by Blood Pact ([6307](https://wow-mania.com/armory/?spell=6307))
![Screenshot (19)](https://user-images.githubusercontent.com/79724094/113637863-801e4080-966d-11eb-83ed-c608435b1555.png)
![Screenshot (20)](https://user-images.githubusercontent.com/79724094/113638014-cc698080-966d-11eb-93e7-24e84c1c53af.png)
![Screenshot (21)](https://user-images.githubusercontent.com/79724094/113638018-cf647100-966d-11eb-8672-a001f0be6a1a.png)

**Comment by jeyrella** [comment]
Don't understand.  on PTR it works correctly
![image](https://user-images.githubusercontent.com/46089380/113712502-1be79500-96de-11eb-8376-dd5ca9e9fe48.png)

**Comment by Keader** [comment]
> Don't understand. on PTR it works correctly
> ![image](https://user-images.githubusercontent.com/46089380/113712502-1be79500-96de-11eb-8376-dd5ca9e9fe48.png)

add imp and cast blood pact.

**Comment by wow-mania** [comment]
Next time just comment on the existing issue pleae.
Thanks.

**Comment by Keader** [comment]
Fixed, it will not be affected by blood pact anymore.
And it's not a regression, since it was not reported before :)

**Comment by hawker357** [comment]
Tested with:
Prayer of Fortitude (All ranks/ with and with Improved from talents)
Runescroll of Fortitude
Greater Bless of Kings (All ranks)
Greater Blessing of Sanctuary (All ranks)
Gift of the Wild (All ranks)
Commanding Shout (With and without Commanding Presence from talents)
ICC Buff - Strength of the Wrynn

None of the above spells, items or effects have any affect on the Eye of Kilrogg's HP, it remained at 1.
