### ISSUE TITLE
[NPC/Add Does Not Attack] Levixus

### ISSUE THREAD

**Issue by womptista** [WoWManiaUK/Redemption#5416]
**Links:**
Link To video showing summon but no attack: https://youtu.be/rStIhDIVyT4
Link to wow-mania Armory: https://www.wow-mania.com/armory/?npc=19847

**What is Happening:**
Levixus will summon his Guardian (Infernal) and it will just stand there not attacking.

**What Should happen:**
The infernal Summon Guardian should aid Levixus in the battle.

**Comment by Rushor** [comment]
Fixing today

**Comment by Rushor** [comment]
added attackstart upon spawn
