### ISSUE TITLE
Thane Ufrang the Mighty is bugged

### ISSUE THREAD

**Issue by optimage** [WoWManiaUK/Redemption#5417]
GM tried killing him and respawning him. But he just spawns stuck in his chair 

![image](https://user-images.githubusercontent.com/4197123/113844430-cee7e980-97d7-11eb-926f-07e9004e2e62.png)

**Comment by wow-mania** [comment]
UNlikely and gm should not do that. It will not solve anything.

**Comment by optimage** [comment]
Not sure what you mean "unlikely".  I am standing next to him lol and he is not aggroed.   I have him targeted and can't attack him ...

**Comment by optimage** [comment]
Ok so I didn't use an item. Sorry about this guys.  You can  close this <3

**Comment by Rushor** [comment]
yeah you must always use the item "Shadow Vault Decree" to make the speech start and make him attackable 

this works https://i.imgur.com/58rBuiB.jpg https://i.imgur.com/AVDquOf.jpg
