### ISSUE TITLE
[OBJECT] Adamantite Deposit in 33.8 35.7 Blade's Edge Mountains is inaccessible

### ISSUE THREAD

**Issue by Bulb1** [WoWManiaUK/Redemption#5418]
Adamantite Deposit: https://wow-mania.com/armory/?object=181556
What is Happening:
It can't be found nowhere above or down
![image](https://user-images.githubusercontent.com/66064613/114024295-29cf1e80-9874-11eb-9771-aacef2dd90c3.png)
What Should happen:
I suggest moving it a little bit higher

**Comment by svijetlo** [comment]
![WoWScrnShot_040821_174812](https://user-images.githubusercontent.com/61908373/114057181-a4a73200-9892-11eb-88c9-1c9536345f03.jpg)
are you sure it was not this one in cave down under

**Comment by svijetlo** [comment]
as i see it can only be one in cave down under as location is same , could not find any other close by , some one other can check this one

**Comment by svijetlo** [comment]
![WoWScrnShot_040821_175309](https://user-images.githubusercontent.com/61908373/114057927-4dee2800-9893-11eb-8792-8a7cadba97e3.jpg)

**Comment by Rushor** [comment]
thanks for this finding man!

**Comment by Bulb1** [comment]
sorry for wasting your time svijetlo but I was sitting in this cave for 30 minutes waiting for 33.8 35.7 deposit to spawn and it didn't

**Comment by svijetlo** [comment]
you did not waste my time =) worry not i was there for some time farmed that one waited for other did not see on addon non new spawn around there

**Comment by jeyrella** [comment]
ok. there _is_ a node in the middle of the terrain.
the node found by svijetlo in the cavern is this one:
21885 (Entry: 181556) - [Adamantite Deposit X:3176.590088 Y:7101.310059 Z:178.832001 MapId:530] 
Found nearby gameobjects (distance 10.000000): 1

that is not at 33.6 35.7


THIS one IS at 33.6 35.7
![image](https://user-images.githubusercontent.com/46089380/114074440-47b07980-989c-11eb-99c4-308f52e1f43e.png)
![image](https://user-images.githubusercontent.com/46089380/114074469-4f701e00-989c-11eb-9c03-d4d6a9862936.png)

however i cannot find this node with gobj near. while there are several nodes in the cave,this one is not at that location in the cave:

![image](https://user-images.githubusercontent.com/46089380/114074824-b8579600-989c-11eb-893e-303e4ea85d56.png)

 so it must indeed be inside the terrain somewhere on a z axis between the cave and the upper ledge

**Comment by svijetlo** [comment]
that is why i told some one other also check as i gatherer did not show it , could be wrong Z axis for one more that should be in cave

**Comment by jeyrella** [comment]
Found this one
40212 (Entry: 181556) - [Adamantite Deposit X:3120.239990 Y:7012.490234 Z:355.450012 MapId:530]

**Comment by jeyrella** [comment]
its between 25 and 30 yards of this location, which puts it slap bang in the middle of the hillside
![image](https://user-images.githubusercontent.com/46089380/114075831-e5f10f00-989d-11eb-91fb-1bff0acfb6e6.png)

**Comment by jeyrella** [comment]
.go xyz 3120.239990 7012.490234 355.450012
https://youtu.be/NH_UCQZ_abk

**Comment by Rushor** [comment]
ahh alright! let's get this thing fixed!

**Comment by Rushor** [comment]
moved this big blue nice and clean to the top here https://i.imgur.com/ohNswAi.jpg :)

**Comment by svijetlo** [comment]
fine now there is one on top, i rly need to stop using gatherer addon for those
