### ISSUE TITLE
[NPC] Wyrmcult Blackwhelp doesn't use skill 

### ISSUE THREAD

**Issue by Bulb1** [WoWManiaUK/Redemption#5419]
Links: 
Wyrmcult Blackwhelp: https://wow-mania.com/armory/?npc=21387
Black Dragon Whelp: https://wow-mania.com/armory/?npc=441
What is Happening:
https://user-images.githubusercontent.com/66064613/114073148-3e76db00-98a3-11eb-8d07-0f835d947035.mp4
there is this lazy whelp that doesn't get up too
![image](https://user-images.githubusercontent.com/66064613/114068858-a7a81f80-989e-11eb-9f60-c8a8a48a599e.png)
![image](https://user-images.githubusercontent.com/66064613/114068960-c4445780-989e-11eb-8c5c-0d0329de765b.png)
What should happen: 
They should act as Black Dragon Whelps in Redrige Mountains 
https://user-images.githubusercontent.com/66064613/114071396-5a797d00-98a1-11eb-8213-d02fe5929116.mp4

**Comment by jeyrella** [comment]
Yup. on the existing list
![image](https://user-images.githubusercontent.com/46089380/114077513-cd81f400-989f-11eb-9ccd-9ccddf5bc817.png)

**Comment by Rushor** [comment]
should use abilities correctly like a charm now!

**Comment by Bulb1** [comment]
![image](https://user-images.githubusercontent.com/66064613/115065687-ba4dd480-9eee-11eb-9536-adc387979e2b.png)
https://www.youtube.com/watch?v=N-NJSkKpmQI

**Comment by Bulb1** [comment]
it looks like ones that spawn normally are laying, but ones that crack from eggs are normal

**Comment by jeyrella** [comment]
On PTR it does this.
![image](https://user-images.githubusercontent.com/46089380/115074577-cd15d880-9ef1-11eb-8155-1e382f6cb505.png)
On Redemption it does this.
![image](https://user-images.githubusercontent.com/46089380/115078145-11f03e00-9ef7-11eb-8453-9479f6b05d3a.png)


On Naxx it does this.
![image](https://user-images.githubusercontent.com/46089380/115075118-85dc1780-9ef2-11eb-9b90-ba909a20b9c4.png)
Concur with bulb's assessment that the ones that crack from the eggs are correct
![image](https://user-images.githubusercontent.com/46089380/115075282-c0de4b00-9ef2-11eb-9be5-ef84c7100a0a.png)

**Comment by Rushor** [comment]
yes pathing is added for the blackwhepls, so they no longer simply lying dead on the ground - that is intended :)

**Comment by Rushor** [comment]
hmm not sure why they play dead on naxx, nothing is different code wise

**Comment by Rushor** [comment]
added additional attackstart, hope this solves it

**Comment by jeyrella** [comment]
Not sure how to test this, since in PTR it was already working.  Unless you/janitor can think of anything else, will have to push live to Naxx and see.
