### ISSUE TITLE
[NPC] Thrall in caverns of time has weird path

### ISSUE THREAD

**Issue by Bulb1** [WoWManiaUK/Redemption#5420]
What is Happening:
https://www.youtube.com/watch?v=3kmBFX3evMY
What Should happen:
that's not game changing fix but it would be nice of him to walk normally

**Comment by Rushor** [comment]
ah yes that wall side is very well known for beeing having issues - will inspect next week since it's a huge script

**Comment by Rushor** [comment]
ah yes that wall side is very well known for beeing having issues - will inspect next week since it's a huge script

**Comment by wow-mania** [comment]
As-is. The map there is missing some tiles. Can't be fixed.

**Comment by jeyrella** [comment]
#4975 #1549

**Comment by Rushor** [comment]
added move jump for him now, too look a bit less strange, but well better than nothing
