### ISSUE TITLE
[Core] Mouse cursor blinking all the time after the latest update.

### ISSUE THREAD

**Issue by anedkow** [WoWManiaUK/Redemption#5421]
**Links:**

**What is Happening:**
After updating to the latest patch my cursor will blink all the time when I move the mouse in-game. I tried disabling the hardware acceleration on my mouse, but the option will not disable itself.
I have disabled the enchanced precision cursor on my mouse and I am with the latest drivers on both my graphics card and my mouse.

**What Should happen:**
I should be able to either disable the hardware acceleration option or the mouse cursor should not blink when it is moved.

**Comment by Rushor** [comment]
Please talk to a gamemaster from support team for this - the tracker is for serverside issues only
