### ISSUE TITLE
[SPELL] Find Fish lets Find Minerals to stay

### ISSUE THREAD

**Issue by Bulb1** [WoWManiaUK/Redemption#5422]
Links:
Find Fish: https://wow-mania.com/armory/?spell=43308
Find Minerals: https://wow-mania.com/armory/?spell=8388
What is Happening:
It could do same thing with other forms of tracking but I don't have fishing on other alts to check it :-(
https://youtu.be/O3cmtbXdLfE
What Should happen:
"Only one form of tracking can be active at a time."

**Comment by jeyrella** [comment]
We know.  Can't be changed.
