### ISSUE TITLE
[NPC} Defias Night Blade 49.8 77.4 Duskwood stuck in tree trunk 

### ISSUE THREAD

**Issue by Bulb1** [WoWManiaUK/Redemption#5423]
Links:
https://wow-mania.com/armory/?npc=909
What is Happening:
https://youtu.be/0FE9PX2a-kA
What Should happen: get him out, he has family to feed :(

**Comment by jeyrella** [comment]
NPC currently selected by player:
DB GUID: 4870, current GUID: 10.
Faction: 17.
npcFlags: 0.
Entry: 909.
DisplayID: 4280 (Native: 4280).
Position: -11107.185547 -517.845459 32.281357.

Much of the time, he paths outside of the trunk.  But at one particular point he paths over the top of it, and then falls inside it, and if attacked at this point he will evade:
![image](https://user-images.githubusercontent.com/46089380/114226292-5154e280-996b-11eb-9001-a0bf40cd9e01.png)

Either could alter his pathing route, OR could alter starting position.

If the latter, then also want to avoid the mound of dirt nearby, which is used for a quest, so in this case suggest something like
![image](https://user-images.githubusercontent.com/46089380/114226753-e8ba3580-996b-11eb-97f1-53c14a8cfed9.png)
