### ISSUE TITLE
[NPC] Yor <Unused> in Desolace

### ISSUE THREAD

**Issue by Bulb1** [WoWManiaUK/Redemption#5424]
What is Happening:
![image](https://user-images.githubusercontent.com/66064613/114234361-f200cd80-997e-11eb-802d-4ab1a085240c.png)
What Should happen:
this just shouldn't e x i s t

**Comment by jeyrella** [comment]
Should not spawn.
https://wowpedia.fandom.com/wiki/Yor_(centaur)
Not found in https://classic.wowhead.com/npc=10237/yor

**Comment by Rushor** [comment]
Will remove him :)

**Comment by Rushor** [comment]
seems still to be here https://i.imgur.com/oVoitbI.jpg

now is fully removed
