### ISSUE TITLE
[Raid] High Warlord Naj'entus is pulled with Aqueous Lord trash in the room - Black Temple

### ISSUE THREAD

**Issue by jeyrella** [WoWManiaUK/Redemption#5425]
**Links:**
Naj'entus:  https://www.wow-mania.com/armory/?npc=22887
Aqueous Lord:  https://www.wow-mania.com/armory/?npc=22878

**What is Happening:**
When Aqueous Lord trash is pulled for clear, Lord Naj'entus pulls too.
![image](https://user-images.githubusercontent.com/46089380/114285221-70c43c00-9a4d-11eb-9c6c-164c02fc4fd7.png)

NPC currently selected by player:
DB GUID: 12868, current GUID: 57.
Faction: 1813.
npcFlags: 0.
Entry: 22878.
DisplayID: 20609 (Native: 20609).

NPC currently selected by player:
DB GUID: 12867, current GUID: 56.
Faction: 1813.
npcFlags: 0.
Entry: 22878.
DisplayID: 20609 (Native: 20609).

**What Should happen:**
Each of the two Aqueous Lord mobs by his sides should pull independently, and Lord Naj'entus should stay until directly engaged.
https://www.youtube.com/watch?v=kXN3MlWAHRY
https://www.youtube.com/watch?v=NwVycw_hgWo

**Comment by Rushor** [comment]
should no longer attack together

**Comment by svijetlo** [comment]
![WoWScrnShot_041521_125420](https://user-images.githubusercontent.com/61908373/114858413-b84e1d80-9de9-11eb-9d62-57b67afc2750.jpg)
