### ISSUE TITLE
[NPC] The Lurker Below

### ISSUE THREAD

**Issue by womptista** [WoWManiaUK/Redemption#5426]
**Links:**
Link to video: https://youtu.be/Slk2OgVECck
Armory link to ability SPOUT: https://www.wow-mania.com/armory/?spell=42584
Armory link to ability WHIRL: https://www.wow-mania.com/armory/?spell=66511

**What is Happening:**
1. The Lurker Below stays in SPOUTphase dropping aggro and picking it back up right away
2. The Lurker Below constantly uses spell WHIRL

**What Should happen:**
1. The Lurker Below should drop aggro table when starting SPOUT phase and not pick it back up until SPOUT is complete
2. The Lurker Below should only cast WHIRL every 18 seconds. Not every .5-.10 mili seconds

**Comment by Rushor** [comment]
can someone confirm that on ptr?

**Comment by Rushor** [comment]
can only fix th timing here. he should not do it non stop anymore, but only after spout now
