### ISSUE TITLE
[Druid Talent] Survival of the Fittest 3/3 did not prevent melee critical strikes from Eadric the Pure (possibly other bosses too)

### ISSUE THREAD

**Issue by BearTank** [WoWManiaUK/Redemption#5427]
**Links:**
https://wowwiki-archive.fandom.com/wiki/Defense
The relevant quote from that article on Defense is "When an equal level mob is attacking a player, the mob has a 5% chance to critically strike the player. For every level beyond the player, there is an additional 0.2% chance for the mob to critically strike the player. **Therefore a level 83 mob (a raid boss) attacking a level 80 player has a 5% + (3 x 0.2%) = 5.6% chance to critically strike the player.**"

**What is Happening:**
I was tanking on my feral druid, who is spec'ed 3/3 into the Survival of the Fittest talent. The instance was Heroic Trial of the Champion and the 2nd boss, Eadric the Pure, critically hit me multiple times with melee according to the in game combat log. Screenshot of one example of a critical attack being taken is attached.

The Survival of the Fittest talent states "Increases all attributes by 6%, **reduces the chance you'll be critically hit by 6%**, and [...]"

Based on raid bosses having a maximum chance of 5.6% to critically hit you and the 6% reduction from the Survival of the Fittest talent, I do not believe my feral druid should be critically hit, especially by a heroic dungeon boss. This is in line with my memory from retail WotLK. I'm not sure if linking to guides on feral tanking stating that defense rating gear is not required because of this talent would be helpful or not. But there are guides from circa 2008 reiterating the critical strike immunity that Survival of the Fittest grants at 3/3 talent points.

**What Should happen:**
Eadric the Pure should not be able to melee critical hit a bear (druid) tank with 3/3 Survival of the Fittest talent. 

When I have more time, I plan to run a few more heroic dungeons and see if this happens again or if it was only on that boss. 

![Bear Critically Hit](https://user-images.githubusercontent.com/82350417/114330820-2ce23d00-9b08-11eb-9c94-0ef645ac613f.png)

**Comment by Oganku** [comment]
![image](https://user-images.githubusercontent.com/34783736/114453911-05db4800-9ba8-11eb-9975-fb4f68fb7595.png)
https://www.wowhead.com/npc=35119/eadric-the-pure/normal-encounter-journal

https://www.wow-mania.com/armory/?spell=66865

Eadric uses skill shown above, which can proc and cause his next hit to become a critical hit regardless of the receiver of the attack.
