### ISSUE TITLE
[NPC] Botanist Alaenra doesn't have her training ability

### ISSUE THREAD

**Issue by Bulb1** [WoWManiaUK/Redemption#5428]
Links:
https://wow-mania.com/armory/?npc=33639
What is Happening:
https://www.youtube.com/watch?v=iE17iXKhhK4
What Should happen:
She should be actual trainer of Herbalism like this one
![image](https://user-images.githubusercontent.com/66064613/114425701-a25a1600-9bb9-11eb-8b5d-f6aeab706d13.png)

**Comment by jeyrella** [comment]
Aelthin 33630 doesn't train alchemy either, and should.

Both have the trainer icon on hover, but don't actually offer any training dialogs.

**Comment by Rushor** [comment]
both fixed

**Comment by svijetlo** [comment]
![WoWScrnShot_041521_124840](https://user-images.githubusercontent.com/61908373/114857764-f1d25900-9de8-11eb-8468-2f7c55e6a4f5.jpg)
