### ISSUE TITLE
[NPC] Aelthin doesn't have his training ability

### ISSUE THREAD

**Issue by Bulb1** [WoWManiaUK/Redemption#5429]
Links:
https://wow-mania.com/armory/?npc=33630
What is Happening:
https://youtu.be/XqzyLvjp5z4
What Should happen:
He should be actual trainer of Alchemy like this one
![image](https://user-images.githubusercontent.com/66064613/114425772-b0a83200-9bb9-11eb-9272-a14886f4ef50.png)

**Comment by Rushor** [comment]
fixed :)

**Comment by svijetlo** [comment]
![WoWScrnShot_041521_124725](https://user-images.githubusercontent.com/61908373/114857613-c2235100-9de8-11eb-8bca-54ab0fdbd0f0.jpg)
