### ISSUE TITLE
[NPC] Dreadfang lurker and dreadfang widow evading - Terrokar

### ISSUE THREAD

**Issue by womptista** [WoWManiaUK/Redemption#5430]
**Links:**
Link to video prof : https://youtu.be/AXAl9nYu4_E
Wow mania link for dreadfang lurker: https://www.wow-mania.com/armory/?npc=18466
wow mania link for dreadfang widow: https://www.wow-mania.com/armory/?npc=18467

**What is Happening:**
When some of the mobs are attacked they seem to aggro on to the attacker and then instantly drop the aggro table and regenerate their lost HP.

**What Should happen:**
They should stay aggroed and attack the player that is attacking them.

**Comment by Rushor** [comment]
try now pls

**Comment by womptista** [comment]
I did 2-3 runs, 99% of the mobs seem to be acting as normal now except for one mob in the same exact place. I have a video of it in the link below
https://youtu.be/Uyf1qzrreP0

**Comment by jeyrella** [comment]
@womptista , when rushor says that, he is directing towards testers to try it in PTR.
Issues are always fixed in our PTR first before being applied to live in a weekly batch, at which time i post a changelog in Discord.

**Comment by Rushor** [comment]
Can you give me the exaxt coords for that mob, we may need to reposition him

**Comment by womptista** [comment]
the mob pats back and forth but the spawn location is 54.42 58.76
