### ISSUE TITLE
[Object] Triple Noblegarden Eggs in Silvermoon ruins

### ISSUE THREAD

**Issue by Bulb1** [WoWManiaUK/Redemption#5431]
Links:
Noblegarden Egg: https://wow-mania.com/armory/?item=44818
What is Happening:
https://www.youtube.com/watch?v=iJE8kh3AeK8
What Should happen:
It should spawn only 1 egg

**Comment by Rushor** [comment]
Will check

**Comment by WhitephoenixTheBunny** [comment]
Is that in Redemption or Naxxramas?
I went see on live on Redemption, and only one egg showed up to me, on the places you shown on the video.

**Comment by Bulb1** [comment]
naxx

**Comment by jeyrella** [comment]
This is normal, and expected.
![image](https://user-images.githubusercontent.com/46089380/114562980-e9521500-9c66-11eb-9e80-37287fdee83f.png)

**Comment by Rushor** [comment]
hmm i checked on ptr aswell just now an it was fine in that place, maybe was a one time issue?

**Comment by Rushor** [comment]
When i get a way to reproduce i can fix it

**Comment by Rushor** [comment]
i adjusted the pool max number for it. there are 20 eggs in that area and 20 eggs should respawn instantly which seems wrong. pooling would not make any sence then. i adjusted the value to 15 so the eggs rotate in respawning behaviour

**Comment by jeyrella** [comment]
This isn't really the same issue....  but ok
