### ISSUE TITLE
[NPC] Irradiated Pillagers in Gnomergan don't move

### ISSUE THREAD

**Issue by Bulb1** [WoWManiaUK/Redemption#5434]
Links:
https://wow-mania.com/armory/?npc=6329
What is Happening:
https://www.youtube.com/watch?v=Ll1CifXRQWo
What Should happen: 
They should use skills till oom and then start melee

**Comment by Rushor** [comment]
fixed on prt, the creature was using a wrong spell cast flag

**Comment by hawker357** [comment]
Mobs revert to melee between casts now as expected
![Screenshot (26)](https://user-images.githubusercontent.com/79724094/115017226-1d6b4700-9eae-11eb-8c34-467c6a55ebe1.png)
