### ISSUE TITLE
[NPC] Eclipsion Spellbinder will never run out of mana

### ISSUE THREAD

**Issue by Bulb1** [WoWManiaUK/Redemption#5436]
Links:
https://wow-mania.com/armory/?npc=22017
What is Happening:
https://www.youtube.com/watch?v=NUHX-PT27uY
What Should happen:
They should lose mana, right?

**Comment by Rushor** [comment]
yes was using wrong spell, will handle mana correctly now (on ptr :) )

**Comment by svijetlo** [comment]
![WoWScrnShot_020521_103244](https://user-images.githubusercontent.com/61908373/114856039-e8e08800-9de6-11eb-8621-c522039244f5.jpg)

**Comment by svijetlo** [comment]
![WoWScrnShot_041521_123356](https://user-images.githubusercontent.com/61908373/114856085-f85fd100-9de6-11eb-8c1e-5de123df4078.jpg)
