### ISSUE TITLE
[NPC] Cabal abjurist does not move when taken out of LoS

### ISSUE THREAD

**Issue by womptista** [WoWManiaUK/Redemption#5437]
**Links:**
Video Link: https://youtu.be/OpkV-wlWjXM
mania armory link: https://www.wow-mania.com/armory/?npc=21660

**What is Happening:**
Cabal Abjurist will not case but stay in combat while not in LoS

**What Should happen:**
Cabal Abjurist should chase the target to get them back into LoS

**Comment by Rushor** [comment]
try now pls (testable on ptr)

**Comment by hawker357** [comment]
Mobs now chase the player when the player breaks LoS
![Screenshot (27)](https://user-images.githubusercontent.com/79724094/115018980-763bdf00-9eb0-11eb-9e44-4c968d53f5c7.png)
