### ISSUE TITLE
[Item]  Leather Lich King 9-piece bonus does not proc

### ISSUE THREAD

**Issue by jeyrella** [WoWManiaUK/Redemption#5438]
**Links:**
https://wow-mania.com/armory/?itemset=2002
https://wow-mania.com/armory/?spell=71560

**What is Happening:**
9-piece bonus does not proc

**What Should happen:**
9-piece bonus should proc

**Comment by svijetlo** [comment]
http://www.wow-mania.com/armory?spell=71492        need to proc this one

**Comment by Keader** [comment]
"Fixed"
Added 1 min cooldown, since it dont have any information about.

**Comment by svijetlo** [comment]
![WoWScrnShot_042521_122815](https://user-images.githubusercontent.com/61908373/115990094-c823e980-a5c1-11eb-8b56-19228b902759.jpg)
