### ISSUE TITLE
[NPC] Old Man Barlo offers cooking Training after daily is complete

### ISSUE THREAD

**Issue by gorgar19** [WoWManiaUK/Redemption#5439]
**Links:**
https://www.wowhead.com/npc=25580/old-man-barlo

**What is Happening:**
He's acting as a cooking trainer

**What Should happen:**
I believe he's supposed to be a fishing trainer .only reason I noticed it was I tryed to do his daily with a toon to low level .then tested it with a follow up toon .

Put in a ticket and was I instructed to make a ticket here

**Comment by Rushor** [comment]
looks correct according to https://wowpedia.fandom.com/wiki/Old_Man_Barlo

fixed on ptr

**Comment by jeyrella** [comment]
Please revert.  He was not a fishing trainer until much later.  I think possibly MoP.

(Although he should not train cooking...  but in both Red & Naxx I cannot replicate him being a cooking trainer??)

https://www.gnarlyguides.com/wotlk/guides/fishing-guide-1-450-wotlk-3-3-5a/
![image](https://user-images.githubusercontent.com/46089380/115110081-69cb8b00-9f71-11eb-8310-da7c9005577e.png)

https://legacy-wow.com/fishing-cooking-alliance-1-450/
Does not list him, and directs you you Juno in Zangarmarsh.

Note the training aspect was only added to your link's history in 2015.
https://wowpedia.fandom.com/wiki/Fishing_trainer?action=history

https://wowpedia.fandom.com/wiki/Fishing_trainer does not list him at all.

There are zero comments on wowhead about him being a trainer - whilst not authoritative, someone would have mentioned it
https://www.wowhead.com/npc=25580/old-man-barlo#comments

**Comment by Rushor** [comment]
okay trainer option is removed as said above

**Comment by jeyrella** [comment]
So this was a slightly different issue, it was that he was (incorrectly) offering cooking Grand Master training, but only after daily fishing quest completed. 
Fixed.
![image](https://user-images.githubusercontent.com/46089380/115118650-20dcfc00-9f9c-11eb-94e1-71775a94b489.png)
