### ISSUE TITLE
[QUEST] Chromatic Mantle of the Dawn is repeatable quest, should have blue ?

### ISSUE THREAD

**Issue by Bulb1** [WoWManiaUK/Redemption#5443]
Links:
https://wow-mania.com/armory/?quest=5521
What is Happening:
![image](https://user-images.githubusercontent.com/66064613/115119176-51766300-9fa7-11eb-84aa-68da44f9b210.png)
What Should happen:
Chromatic Mantle of the Dawn is repeatable quest, should have blue question mark

**Comment by wow-mania** [comment]
As-is this may happen when the npc has other quests.

**Comment by Bulb1** [comment]
wel,l as you can see I have no other quests

**Comment by Rushor** [comment]
The blue Mark only works in wotlk zones. In tbc and classic zones it is yellow still. On retail it was the same
