### ISSUE TITLE
[OBJECT] Cannons don't shoot in Cannon Master Willey fight Stratholme

### ISSUE THREAD

**Issue by Bulb1** [WoWManiaUK/Redemption#5444]
Links:
Willey: https://wow-mania.com/armory/?npc=10997
What is Happening:
https://www.youtube.com/watch?v=0nw4eOOP9VE
What Should happen:
Dunno if video from 2008 is good source but why having cannons that don't shoot? 
https://www.youtube.com/watch?v=ZmSRo8AUVrI

**Comment by Rushor** [comment]
Will fix this :)

**Comment by jeyrella** [comment]
closed in oversight

**Comment by Rushor** [comment]
the cannons are now functional

**Comment by svijetlo** [comment]
![WoWScrnShot_042521_123421](https://user-images.githubusercontent.com/61908373/115990271-93646200-a5c2-11eb-911f-343627fd9ed6.jpg)
![WoWScrnShot_042521_123454](https://user-images.githubusercontent.com/61908373/115990286-a7a85f00-a5c2-11eb-9046-d96f4430f3c2.jpg)
