### ISSUE TITLE
[Spell] Warlock Pet Bar dissapears after vehicle summon

### ISSUE THREAD

**Issue by theonykry** [WoWManiaUK/Redemption#5445]
**Links:**
https://www.wow-mania.com/armory/?spells=-3.204 https://www.wow-mania.com/armory/?spells=-3.189
Cant find siege engine link 
**What is Happening:**
As a lvl 80 affli lock using Felhunter pet (improved and unimproved) and also using a Voidwalker. When entering a vehicle (siege in this case, i only tested it on siege as defending fraction) and then destroying one of the southern towers. Once i leave the vehicle, the pet i summoned before, still is summoned, but my petbar disappeared. this happend to me a few times. i can still use hotkey commands for the pet or written commands like /use Sacrifice (for voidwalker). they still work, but just wiothout a petbar. even after summoning a new pet, the petbar still is missing. the only way to fix it is to relog, which if you are in a BG is impossible to do, without getting deserter.
**What Should happen:**
Pet-Bar should not disappear once i leave the siege engine as defending fraction in Wintergrasp.

**Comment by Rushor** [comment]
more info here https://github.com/TrinityCore/TrinityCore/issues/24287

**Comment by jeyrella** [comment]
I experienced this (or extremely similar) on Redemption last night as it happens, I thought it was jsut me.
Can be replicated on PTR

However, am having trouble replicating the exact circumstances above of the trouble with physical vehicles.  With wintergrasp seige engines, salvaged demolisher 33109 and felhunter ID 691 / imp 688 / voidwalker 697 it seems to work ok

what *is* replicable on PTR, is this:
Warlock with felhunter ID 691 / imp 688 / voidwalker 697
cast Eye of Kilrogg ID 126
if ended using cancelaura or right clicking buff, pet bar is returned visible
if let channeling end, pet bar is not returned visible

/rl ui does not fix
full physical relog does

**Comment by Keader** [comment]
Can you check with vehicles if it's working?

> I experienced this (or extremely similar) on Redemption last night as it happens, I thought it was jsut me.
> Can be replicated on PTR
> 
> However, am having trouble replicating the exact circumstances above of the trouble with physical vehicles. With wintergrasp seige engines, salvaged demolisher 33109 and felhunter ID 691 / imp 688 / voidwalker 697 it seems to work ok
> 
> **what _is_ replicable on PTR, is this:**
> Warlock with felhunter ID 691 / imp 688 / voidwalker 697
> cast Eye of Kilrogg ID 126
> if ended using cancelaura or right clicking buff, pet bar is returned visible
> if let channeling end, pet bar is not returned visible
> 
> /rl ui does not fix
> full physical relog does

This is another case lul

**Comment by svijetlo** [comment]
did not post any Ss but after i enter sige engine and come out pet bar would be back always

**Comment by Dmw1981** [comment]
hunter pets have the same prob when ever you enter a vehicle questing while pet is summoned

**Comment by jeyrella** [comment]
@Dmw1981 @theonykry do we have any video of this happening?  (specifically with the vehicles)  
Neither myself nr Svijetlo can replicate on PTR, and I can't replicate on my lock on Redemption (although the Eye of Kilrogg issue I could, and is fixed).
