### ISSUE TITLE
[Zone] Mall area to be set to safe

### ISSUE THREAD

**Issue by jeyrella** [WoWManiaUK/Redemption#5446]
**Links:**
https://wow-mania.com/armory/?zone=3817

**What Should happen:**
As per agreement on "Suggestions", Mall area zone 3817 to be set to safe logout & gain rested xp

**Comment by Rushor** [comment]
the rested flag i cannot add due to dbc change required - but you can instant logout now in that zone :)

**Comment by jeyrella** [comment]
![image](https://user-images.githubusercontent.com/46089380/115758003-92e78380-a396-11eb-8cc8-bb8ae90f46c4.png)

**Comment by Rushor** [comment]
now it should work :)

**Comment by jeyrella** [comment]
Confirmed :)
