### ISSUE TITLE
[Mount] Antoran Gloomhound needs sounds remake

### ISSUE THREAD

**Issue by Bulb1** [WoWManiaUK/Redemption#5448]
Links:
https://wow-mania.com/armory/?item=150578
What is Happening:
https://www.youtube.com/watch?v=HoeQZS3P6Yk
What Should happen:
Here are right sounds  https://www.youtube.com/watch?v=kYoBglr_0Ok

**Comment by jeyrella** [comment]
Passed to Amyelek for review for client changes.
