### ISSUE TITLE
[Quest] Daily Cooking Quest reward for Alliance set too low

### ISSUE THREAD

**Issue by jeyrella** [WoWManiaUK/Redemption#5449]
**Links:**
Quests 
13100 
13103

vs correct rewards for Horde versions:
13112
13115

**What is Happening:**
The Alliance versions of Cheese for Glowergold and Infused Meatloaf Mushroom reward only 45s, whereas the Horde versions reward the full 5g80s as they should
![image](https://user-images.githubusercontent.com/46089380/115767215-c8916a00-a3a0-11eb-9e78-fb380b5cc40a.png)
![image](https://user-images.githubusercontent.com/46089380/115767537-2d4cc480-a3a1-11eb-922e-bc2cbf1df6cf.png)

**What Should happen:**
13100 and 13103 should be set to reward 5g80s like the other quests.

**Comment by Rushor** [comment]
reward amount fixed

**Comment by jeyrella** [comment]
Fixed
![image](https://user-images.githubusercontent.com/46089380/116075204-9165d600-a68a-11eb-929a-90dfd6eb7e95.png)
![image](https://user-images.githubusercontent.com/46089380/116075637-15b85900-a68b-11eb-8b1e-e83cb336e0ef.png)


vs already correct reward for Sewer Stew at level 80
![image](https://user-images.githubusercontent.com/46089380/116075131-78f5bb80-a68a-11eb-9340-49f773611dab.png)
