### ISSUE TITLE
Dreadsteed of Xoroth Bug

### ISSUE THREAD

**Issue by Abateman121** [WoWManiaUK/Redemption#5450]
**Links:**
https://www.wow-mania.com/armory/?quest=7631
https://www.youtube.com/watch?v=7qBvCvxac5k&ab_channel=BloodyFoxGaming

**What is Happening:**
J'eevees is running off into diremaul before placing the candle, wheel, and bell which starts the ritual to summon the Xorothian Dreadsteed.  This prevents you from being able to properly perform the ritual to summon the Xoronthian Dreadsteed.

**What Should happen:**
J'eevees should place the items for the ritual prior to running off

**Comment by Rushor** [comment]
Can fix that!

**Comment by Rushor** [comment]
now fully fixed, this spell will summon him and the event will be handled correctly now https://de.classic.wowhead.com/spell=23136

rune summon is also fixed

if the trash creatures evade (player is killed) all event will reset and all will despawn
