### ISSUE TITLE
[Instances/TOC] Fixed Earth Shield spell of Faction Champions

### ISSUE THREAD

**Issue by Keader** [WoWManiaUK/Redemption#5451]
**What is Happening:**

Spell was not scripted, so it dont give any healing.
And causes runtime error: AuraEffect::HandleProcTriggerSpellAuraProc: Could not trigger spell 0 from aura 66063 proc, because the spell does not have an entry in Spell.dbc.

**What Should happen:**

Spell should give heal when Faction Champion get damage ✌️ 
And not causes any runtime error.

**Comment by hawker357** [comment]
Earth Shield on Shaman is now healing on hit as expected
![Screenshot (35)](https://user-images.githubusercontent.com/79724094/116074527-cc1b3e80-a689-11eb-8389-dd74811dacce.png)
