### ISSUE TITLE
bug on my flying mount

### ISSUE THREAD

**Issue by HectorPolpetta** [WoWManiaUK/Redemption#5455]
**Links:**

**What is Happening:**
i buy a fast flying mount from shop with coins, send to mail on my characters, i put on my bag and when i use it for learn it, he dissapear and i didnt found him on my mount collection 

**What Should happen:** i should found my mount on my mount collection

**Comment by WhitephoenixTheBunny** [comment]
We will need the mount name.. but is most likely you are not correctly patched... Could you check uf you are on last patch? 2.9.1

**Comment by HectorPolpetta** [comment]
Reins of the Drake of the Four Winds is the name of mounts and yes i have 2.9.1 as currently patch

**Comment by jeyrella** [comment]
Working fine.  Contact a GM in game for this.
