### ISSUE TITLE
Dun-Da-Dun-Tah! doesn't work

### ISSUE THREAD

**Issue by Xangretor** [WoWManiaUK/Redemption#5459]
**Links:**
https://www.wowhead.com/quest=12082/dun-da-dun-tah

**What is Happening:**
Nothing. After accepting the quest, Harrison Jones stands still and doesn't move at all.

**What Should happen:**
After accepting the quest Harrison Jones should move around the crypt showing stuff and what not.

**Comment by Rushor** [comment]
is as is - within next restart this works again
