### ISSUE TITLE
Can't start call of fire quest

### ISSUE THREAD

**Issue by seknaingphyo** [WoWManiaUK/Redemption#5460]
**Links:**
https://classic.wowhead.com/quest=1522/call-of-fire

**What is Happening:**
I'm playing as troll shaman on level 43. The quest is supposed to unlock at level 10 and it should appear at any shaman trainer (Orgrimaar, Razor Hill, etc.). I've done three other totem quests (air, water, earth) but the call of fire quest is not appearing at all.

**What Should happen:**
Call of Fire quest should appear at a shaman trainer.

**Comment by Rushor** [comment]
you need to start it at the fitting trainer for you, pretty sure it works

**Comment by wow-mania** [comment]
unlikely to be a real issue.
please confirm

**Comment by jeyrella** [comment]
Seems to work fine.  Reach out to a GM on this one, maybe there is something up with your specific toon.
