### ISSUE TITLE
[Quest] Call on the Farseer 10968

### ISSUE THREAD

**Issue by WhitephoenixTheBunny** [WoWManiaUK/Redemption#5465]
After doing the first 3 quests:

![image](https://user-images.githubusercontent.com/31921098/116905721-44a86f00-ac37-11eb-86db-cafb28a9f418.png)

the [Draenei Orphan](https://www.wow-mania.com/armory/?npc=22818) gives more 2 quests:
[The Seat of the Naaru](https://www.wow-mania.com/armory/?quest=10956)
[Time to Visit the Caverns](https://www.wow-mania.com/armory/?quest=10962)

**_What is Happening:_**
At the moment, [Call on the Farseer](https://www.wow-mania.com/armory/?quest=10968) only will be avaible after completing [Time to Visit the Caverns](https://www.wow-mania.com/armory/?quest=10962)
This can lead to a missunderstanding if someone does:
1. Go to Exodar and complete [The Seat of the Naaru](https://www.wow-mania.com/armory/?quest=10956)
2. Go to Caverns of the Time and complete [Time to Visit the Caverns](https://www.wow-mania.com/armory/?quest=10962)
3. Then go back to Exodar to take [Call on the Farseer](https://www.wow-mania.com/armory/?quest=10968)
4. Complete it
5. Take [Back to the Orphanage](https://www.wow-mania.com/armory/?quest=10966) 
6. Complete it and have a nice pet :D

note: that on step 3, the [Draenei Orphan](https://www.wow-mania.com/armory/?npc=22818) will not inform that the player need go Exodar back, and it might think the questline ends there or there's some bug

**IF** the quests are done the other away - first doing [Time to Visit the Caverns](https://www.wow-mania.com/armory/?quest=10962) and then [The Seat of the Naaru](https://www.wow-mania.com/armory/?quest=10956), the "issue" isn't noticiable.

_**What Should happen_:**
1. The quest [Call on the Farseer](https://www.wow-mania.com/armory/?quest=10968) should be avaible after doing [The Seat of the Naaru](https://www.wow-mania.com/armory/?quest=10956)

2. The quest [Back to the Orphanage](https://www.wow-mania.com/armory/?quest=10966) should require [Call on the Farseer](https://www.wow-mania.com/armory/?quest=10968) and [Time to Visit the Caverns](https://www.wow-mania.com/armory/?quest=10962) _complete and rewarded_ 

See quest progression on [wowwiki](https://wowwiki-archive.fandom.com/wiki/Quest:Back_to_the_Orphanage_(Alliance))
![image](https://user-images.githubusercontent.com/31921098/116908571-fbf2b500-ac3a-11eb-8276-3e2f2bca7531.png)
See comments in [wowhead](https://www.wowhead.com/quest=10966/back-to-the-orphanage#comments) from patch 2.4.1
![image](https://user-images.githubusercontent.com/31921098/116908766-2fcdda80-ac3b-11eb-8199-60bf543fb9bd.png)

**Comment by Rushor** [comment]
added:

Call on the Farseer requires The Seat of the Naaru rewarded
quest Back to the Orphanage requires Call on the Farseer and Time to Visit the Caverns rewarded (and completed aswell but that is logic because rewarded it is after beeing completed)
