### ISSUE TITLE
[Spell] Chaos Bane / Shadowmourne proc is healing enemy players in arena on killing blow

### ISSUE THREAD

**Issue by Kilju** [WoWManiaUK/Redemption#5466]
**Links:**
https://www.wow-mania.com/armory/?item=49623
https://www.wow-mania.com/armory/?spell=71904
**What is Happening:**

Chaos Bane that is a proc from Shadowmourne weapon heals enemy players, atleast in arenas when they are about to die. Played 2 games in which both times enemy team member got healed from "1%" to 100% from chaos bane proc when they were about to die. This happened twice in 2 games, once on a priest and once on a mage. Played 2 teams this bug occured against only 1 team which makes it peculiar.

In this screenshot from other players combat log you can see him performing offensive spells on me and my teammate by fearing us. And you can see my righteous vengeance dealing damage and before that I'm healing with chaos bane proc for 27871 (+ millions overhealed), therefore the priest was at 3729hp when this bug occured.
![WoWScrnShot_050521_010823](https://user-images.githubusercontent.com/32513041/117077569-08613580-ad41-11eb-96cd-eff5e85db51f.jpg)

Can't possibly give hints to replicate this.. I had wings on atleast against priest..  I'm also wearing Tiny Abom in a Jar and using Seal of Command if that helps at all. 

**What Should happen:**

Chaos bane should not heal anything at all. It should be a shadow spell dealing damage.

**Comment by Keader** [comment]
Without a reproduce steps, i cant do a thing.
I tested a lot of time, i cant reproduce.
Looks like a Overflow/Underflow, but without a repro steps we cant find where

**Comment by jeyrella** [comment]
We've spent a lot of time trying to reproduce this, and can't.  We really need the full combat log and/or event trace, which I'm guessing you don't have.
If you can give us reliable reproduction steps, we can re-open and take a look, otherwise we're just shooting in the dark here.
