### ISSUE TITLE
[QUEST] The Exorcism of Colonel Jules

### ISSUE THREAD

**Issue by Greywolf59** [WoWManiaUK/Redemption#5467]
**Links:**
Quest: https://www.wow-mania.com/armory/?quest=10935
NPC: https://www.wow-mania.com/armory/?npc=22432

**What is Happening:**
Sometimes Jules decides to fly right out through the wall and keeps flying west until the exorcism is over. In this case quest does not get completed. Abandoning and retaking the quest can make it work again. Chance for quest to work properly is about 50/50 I guess.

**What Should happen:**
Jules should fly only around (inside) the room he is at.

Edit: retook, this time he flew out to east 😅
Edit 2: another retake. He went straight south.
Final edit: Talking with Jules when he starts flying away stops him and quest gets completed after the exorcism is done.

**Comment by wow-mania** [comment]
Pretty sure it works.
Make sure it is confirmed by a tester before touching it.

**Comment by Rushor** [comment]
added pathfinding adjustment to him, he should be on the correct path now

**Comment by GMZinius** [comment]
Hi @Rushor Please look into this fix, as a new report has been made that I have closed https://github.com/WoWManiaUK/Redemption/issues/6245 
- Seems no tester confirmed this fix back in 2021

**Comment by Echinaceax** [comment]
i have reproduced this bug, so no its not fixed

test 1
i let it complete correctly (Colonel Jules was flat on the bed at the start)

test 2 
i let Anchorite Bearada die, and let the event fully finish (Colonel Jules was NOT flat on the bed at start)

test 3 
i killed myself,  and let the event fully finish (Colonel Jules was NOT flat on the bed at start) 
https://i.gyazo.com/8b0b3627cd91143603e00643b72c79ac.mp4

test 4 
Bugged, he floated through the window 
https://i.gyazo.com/1f4bbc493d300fa618cd85d03f133c18.mp4

to note tho, the event continues even tho Colonel Jules isnt in the room 
https://i.gyazo.com/80fbbfbd008c76045f9fbe0f20d4da5b.mp4

Colonel Jules floats back in the room after a long time waiting 
https://i.gyazo.com/42c18d19a6fbf4135343402456ec9a41.mp4

after the .die of Colonel Jules, he respawns correctly flat on the bed 
https://i.gyazo.com/7f4c7da49b82eb99acb652e7f19ba863.mp4

after resetting 
https://i.gyazo.com/73aeb7a9017521092b0b1bdc58c1c771.mp4
completed as normal https://i.gyazo.com/86ea40ce8b8ebf0caf3c8039df6f0b69.mp4

BUT - he is NOT flat on the bed again 👎 
https://i.gyazo.com/90dbe53c2a889d61462a974d8aa02b79.mp4

**Comment by Echinaceax** [comment]
fixed in PTR - Colonel Jules doesnt float out the window anymore

check 1 - completed as normal
check 2 - i let barada die, Colonel Jules reset on the bed
check 3 - killed myself, Colonel Jules reset on the bed
check 4 - ran the full quest again, all good 

![image](https://github.com/user-attachments/assets/ffb9d27c-fbad-42e1-8f14-3731b8663748)
