### ISSUE TITLE
[NPC] Spitelash Siren

### ISSUE THREAD

**Issue by Greywolf59** [WoWManiaUK/Redemption#5468]
**Links:**
https://www.wow-mania.com/armory/?npc=6195#abilities

**What is Happening:**
Spitelash Sirens are not using their abilities. Instead, they just melee away on the player.

**What Should happen:**
They should use their spells.

**Comment by jeyrella** [comment]
Not in the known list.  Will need specific testing

**Comment by Rushor** [comment]
yeah because they have a corescript for a specific quest, need adding some abilities to them

**Comment by Rushor** [comment]
they will now use their abilities
