### ISSUE TITLE
[RAID] Battle for Mt. Hyjal boss loot

### ISSUE THREAD

**Issue by Greywolf59** [WoWManiaUK/Redemption#5469]
**Links:**
https://github.com/WoWManiaUK/Redemption/issues/5270

1st boss: Rage Winterchill https://www.wow-mania.com/armory/?npc=17767

2nd boss: Azgalor (repaired) https://www.wow-mania.com/armory/?npc=17842

3rd boss: Kaz'rogal https://www.wow-mania.com/armory/?npc=17888

4th boss: Azgalor https://www.wow-mania.com/armory/?npc=17842

5th boss: Archimonde https://www.wow-mania.com/armory/?npc=17968

**What is Happening:**
Some if not all bosses except the one repaired (Anetheron) in provided github link still have same issue of not dropping loot if killed by helping unit. Can't say if all but at least one of the Horde camp bosses has it. I can't remember which one. Either Kaz'rogal or Azgalor.

**What Should happen:**
Boss should award loot and emblems no matter from who was the last hit taken.

**Comment by jeyrella** [comment]
Archimonde is not affected as no NPCs assist.
But yes if the helper NPCs get killing blow on any of the other three unrepaired encounters, no loot is dropped and players are left in combat.
#5270

**Comment by Rushor** [comment]
all bosses except endboss fixed
