### ISSUE TITLE
[TALENT] [MAGE] Master of Elements

### ISSUE THREAD

**Issue by Greywolf59** [WoWManiaUK/Redemption#5470]
**Links:**
https://amp.reddit.com/r/classicwow/comments/c8bk41/mage_master_of_elements_talent_weird_description/
I know it is classic ans reddit but I haven't found any other info about it. I doubt it changed though.

MoE talent https://www.wow-mania.com/armory/?spell=29075
MoE effect (?) https://www.wow-mania.com/armory/?spell=29077
Arcane concentration (clearcasting talent) https://www.wow-mania.com/armory/?spell=12577
Clearcasting aura https://www.wow-mania.com/armory/?spell=12536

**What is Happening:**
Not sure if anyone except me uses spec that goes for both talents but I do at least for part of levelling.
Anw... Master of Elements does not refund mana from criticals made under effect of Clearcasting. I am using 2/3 Master of Elements

**What Should happen:**
Master of Elements should always refund % of BASE mana cost of the spell that crits, that is also when the Clearcasting (0 mana cost) is active.
Meaning that base fireball costs lets say 400 mana it will refund 40/80/120 mana (depending on talent points) even with Clearcasting crit ( + 80 in 2/3 case, 80 mana gained for crit, none mana lost).

**Comment by Keader** [comment]
Keamagic's Burnout drains 26 Mana from Keamagic.
**Keamagic gains 161 Mana from Keamagic's Master of Elements.**
Keamagic's Fireball hits Grandmaster's Training Dummy for 3 Fire.(2869 Overkill) (Critical)
Keamagic's Arcane Potency fades from Keamagic.
Keamagic's Clearcasting fades from Keamagic.

It's working fine.
Even with Clearcasting active, you get refund.

**Comment by Greywolf59** [comment]
Oh, so it is written in log BEFORE the actual hit? That might explain it. Thank you.

**Comment by Greywolf59** [comment]
@Keader  I have proof that it does not work. In fact I do not get any
 mana from Clearcasting critical strike and neither I get any mana from critical strike that triggers (buffs me with) Clearcasting.
![master of elements proof](https://user-images.githubusercontent.com/41387450/117334105-e62efb00-ae99-11eb-9946-10294a71991f.jpg)

**Comment by Keader** [comment]
Yeah, fixed.

**Comment by Keader** [comment]
fix added into ptr
