### ISSUE TITLE
[OBJECT] Felweed 69.0 59.3 in Shadowmoon Valley is unattainable 

### ISSUE THREAD

**Issue by Bulb1** [WoWManiaUK/Redemption#5471]
Links:
[Felweed](https://wow-mania.com/armory/?object=181270)
What is Happening:
![image](https://user-images.githubusercontent.com/66064613/117281083-903f6080-ae63-11eb-9775-007f22c9c4f8.png)
What Should happen:
![image](https://user-images.githubusercontent.com/66064613/117281501-017f1380-ae64-11eb-8f42-1e45f145e8c3.png)

**Comment by jeyrella** [comment]
confirmed, the z-axis is below ground
21367 (Entry: 181270) - [Felweed X:-4122.700195 Y:428.178986 Z:23.361900 MapId:530] 
![image](https://user-images.githubusercontent.com/46089380/117309228-22eafa00-ae7a-11eb-8e51-50c9ee59f7d0.png)

**Comment by Rushor** [comment]
changed position a bit to the side of the map
