### ISSUE TITLE
[OBJECT] Copper Vein stuck in tree in Redrige Mountains 

### ISSUE THREAD

**Issue by Bulb1** [WoWManiaUK/Redemption#5475]
Links:
[Copper Vein](https://wow-mania.com/armory/?object=2055)
What is Happening:
![image](https://user-images.githubusercontent.com/66064613/117808742-8b145400-b25d-11eb-8b4c-694bb0ac81c3.png)
What Should happen:
:)

**Comment by Rushor** [comment]
will check tomorrow! good that you find such things - it creates trouble for lot of people and we can fix it :)

**Comment by hawker357** [comment]
Confirmed - Coords are X-9078 Y-3300 X 102.24
![Screenshot (53)](https://user-images.githubusercontent.com/79724094/117967894-7eefcb80-b31d-11eb-8886-e67b3bc9bd90.png)

**Comment by Rushor** [comment]
moved a bit to the side of the three :)
