### ISSUE TITLE
[Quest] Reconnaissance Flight with Path of Frost unable to fly

### ISSUE THREAD

**Issue by hawker357** [WoWManiaUK/Redemption#5476]
**Links:**
https://www.wowhead.com/quest=12671/reconnaissance-flight
https://www.wowhead.com/spell=3714/path-of-frost

**What is Happening:**
When starting the quest with the buff active, the plane gets the buff also. As a result of this, the player is unable to move the plane once they get control. They can only turn the plane.

**What Should happen:**
The player should be able to assume control as normal.

May need to remove the buff upon quest accept, or prevent the plane from receiving player buffs.

![Screenshot (56)](https://user-images.githubusercontent.com/79724094/117970749-ee1aef00-b320-11eb-9f07-089faf15cbb4.png)
![Screenshot (58)](https://user-images.githubusercontent.com/79724094/117970759-f1ae7600-b320-11eb-9899-32921465ac08.png)

**Comment by wow-mania** [comment]
pretty sure it works as intended

**Comment by Rushor** [comment]
The aura actually creates some trouble here, will remove it when Player enters the vehicle to solve this

**Comment by hawker357** [comment]
From my knowledge this quest has had a lot of previous fixes so maybe something similar has happened with another aura. I first noticed this on live when levelling a new DK, so I checked it on PTR to make sure it wasn't a fluke.
