### ISSUE TITLE
[Item] Libram of Divine Judgement - not proccing

### ISSUE THREAD

**Issue by wfygFonsi** [WoWManiaUK/Redemption#5477]
**Links:**
https://wow-mania.com/armory/?item=33503
https://wow-mania.com/armory/?spell=43745

**What is Happening:**
On Naxxramas - Cast around 100 judgements (light, Wisdom and Justice), haven't see a single proc of Crusader's Command buff linked above.

**What Should happen:**
40% chance of proccing Crusader's Command buff (linked above)

**Comment by Keader** [comment]
fixed
