### ISSUE TITLE
Master of Elements

### ISSUE THREAD

**Issue by Kreepsula** [WoWManiaUK/Redemption#5480]
**Links:**

https://github.com/WoWManiaUK/Redemption/issues/5470

**What is Happening:**

checking our logs, u guys fixed master of elements last week
but we miss 1 little thing: Patch 3.0.3: Master of Elements: Now works with Living Bomb.
It's not working with living bomb explosion crits

**What Should happen:**

Living Bomb explosion should give mana back too

**Comment by Keader** [comment]
nice catch, fixed

**Comment by svijetlo** [comment]
![WoWScrnShot_051721_191750](https://user-images.githubusercontent.com/61908373/118530267-bd81ed80-b744-11eb-9ca0-5416d82639b5.jpg)
