### ISSUE TITLE
Druid - Frenzied Regeneration scaling

### ISSUE THREAD

**Issue by Kreepsula** [WoWManiaUK/Redemption#5481]
**Links:**

https://wow-mania.com/armory/?spell=22842

**What is Happening:**

Spell description says: Each point of rage is converted into 0.3% of max health

But in the server it's scaling with attack power / spell power / talents, making this talent very over power in pvp

**What Should happen:**

It should only scale with rage

**Comment by Keader** [comment]
fixed
