### ISSUE TITLE
Doomwalker

### ISSUE THREAD

**Issue by Kreepsula** [WoWManiaUK/Redemption#5482]
Sorry for flooding reports guys, i just can do it in weekends

**Links:**

https://wow-mania.com/armory/?npc=17711

**What is Happening:**

You can kill him without take any damage using this spot:

https://i.imgur.com/edlTcFp.jpeg

**What Should happen:**

maybe has some protection for it already, because old spot not work anymore
maybe apply same fix for new spot? idk

**Comment by Keader** [comment]
fixed
