### ISSUE TITLE
quest Let Them Not Rise!

### ISSUE THREAD

**Issue by gorgar19** [WoWManiaUK/Redemption#5483]
**Links:**
https://www.wowhead.com/quest=12211/let-them-not-rise

**What is Happening:**
theirs three mobs that the corpses don't despawn when you click the container of rats. other mobs that i tested it on with the same names despawned when you fed them to the rats by clicking the container
mobs are all in a corner at

onslaught footman 
72.65 72.22
onslaught raven priest 
72.46 72.52
72.38 72.98

could be others its a short quest only needing 15 clicks. not really a big bug but thought id report it none the less.
tested it on two toons with same results
**What Should happen:**

the corpses should despawn when you click the container of rats

**Comment by Rushor** [comment]
will inspect

**Comment by Rushor** [comment]
reaosn for this is that if corpse is half inside a building it will not correctly target the creature, the spell should now always hit

**Comment by svijetlo** [comment]
completed quest wo problems
