### ISSUE TITLE
[Item ] Gnomish Death Ray

### ISSUE THREAD

**Issue by svijetlo** [WoWManiaUK/Redemption#5484]
**Links:**
http://www.wow-mania.com/armory?item=10645
https://www.youtube.com/watch?v=IKLD2mk94Fg
https://www.youtube.com/watch?v=I1g0LuAHBRM&ab_channel=LebrawlskiLebrawlski

P.S. last vid is 1 y old but it is form current wow vanilla retail not other server 
**What is Happening:**
Gnomish Death Ray no matter how much times you use it , only does DMG to player the HP cost of cast while it never does DMG to enemy unit or player 

**What Should happen:**
Gnomish Death Ray should cost HP to player but also do dmg to enemy and or players in pvp

**Comment by Rushor** [comment]
can check, up to you keader if you want i will not touch :)

**Comment by Keader** [comment]
It's spell issue @Rushor ^^

**Comment by svijetlo** [comment]
ye this is spell not working properly

**Comment by Keader** [comment]
Fixed, can you test now?

**Comment by svijetlo** [comment]
will do later or tomorrow early just got home form work , yes i know there is % chance to fail ;) where it only does HP price on caster
