### ISSUE TITLE
Security DELTA Data Access Card not giving recipes

### ISSUE THREAD

**Issue by Xangretor** [WoWManiaUK/Redemption#5486]
**Links:**
https://classic.wowhead.com/item=9327/security-delta-data-access-card#comments
https://wowwiki-archive.fandom.com/wiki/Minor_Recombobulator
https://classic.wowhead.com/item=4413/schematic-discombobulator-ray
https://classic.wowhead.com/object=142345/matrix-punchograph-3005-a
https://classic.wowhead.com/object=142475/matrix-punchograph-3005-b
https://classic.wowhead.com/object=142476/matrix-punchograph-3005-c
https://classic.wowhead.com/object=142696/matrix-punchograph-3005-d

**What is Happening:**
When you are using the matrix punchograph 3500 machines the punch cards (starts with white), automatically upgrade to the next tier of the punch card (white -> yellow -> blue -> red -> prismatic)

**What Should happen:**
When you the punchograph 3500 machines you should be able to choose what you want to do. When having a yellow punch card using the punchograph 3500-B, you should be able to learn the recipe Minor recombulator. When using the matrix punchograph 3500-D, while having a security delta data access card, it should be able to learn you the discombobulator ray recipe.

**Comment by Rushor** [comment]
going to inspect, there are some conditions to it actually

**Comment by Rushor** [comment]
condition to access all punch o graphs now is to have the fitting Punch Cards in iventory.

the objects Matrix Punchograph 3005-B 142475 and Matrix Punchograph 3005-D 142696 will now give you the learning recipes if you have a engerieering skill of 140 or higher (lernable via gossip selection) 

object id 142696 will learn spell 11595
object id 142475 will learn spell 4011
