### ISSUE TITLE
[NPC] 4 of Iceskin Sentries (Icecrown) are evade to any spell 

### ISSUE THREAD

**Issue by Bulb1** [WoWManiaUK/Redemption#5487]
Links:
QUEST: [Stunning View](https://wow-mania.com/armory/?quest=13160)
NPC: [Iceskin Sentry](https://wow-mania.com/armory/?npc=31012)
What is Happening:
4 of [Iceskin Sentry](https://wow-mania.com/armory/?npc=31012) needed for quest [Stunning View](https://wow-mania.com/armory/?quest=13160) evade to any spell of Lithe Stalker and player
[Video evidence](https://www.youtube.com/watch?v=DJ2KV-YevxI)
They can be found on 
59.9 71.9
60.4 72.3
60.3 71.7
60.4 72.3
Malykriss: The Vile Hold (Icecrown)

**Comment by Rushor** [comment]
prolly faction related i think

**Comment by Rushor** [comment]
try now pls
