### ISSUE TITLE
Quest Respite for a Tormented Soul - Sindragosa

### ISSUE THREAD

**Issue by Kreepsula** [WoWManiaUK/Redemption#5491]
**Links:**

**What is Happening:**

You just need get quest, kill sindragosa e get loot.

**What Should happen:**

1 member of the raid should cast channel for 30 sec
Loot of quest should be present only if cast is successful

Has a guide here: https://www.youtube.com/watch?v=EoPlwTinULQ

Without this fix, Respite for a Tormented Soul = free 5 frost

**Comment by svijetlo** [comment]
are you sure , i did this quest yesterday and last week in icc if players do not use item on boss when boss is 20% hp or under you will not be able to loot item to finish quest form boss , tho smt might have happen i will have to tests it

**Comment by Rushor** [comment]
on ptr this seems fine aswell, reinserted the sql data, maybe it got lost on live

**Comment by svijetlo** [comment]
works on ptr to me
