### ISSUE TITLE
Vip token

### ISSUE THREAD

**Issue by reynardsf85** [WoWManiaUK/Redemption#5494]
I have had vip now for 4 months now but I have only recived 2 tokens, one did I spend on mystery bag and 1 is in the bank. But Im missing 2.

Regards
Reynard
Rumppaj

**Comment by WhitephoenixTheBunny** [comment]
Not a Github issue...
Try talk with a GM ingame or Janitor on discord.

(if u get monthly vip, you get it insta, but if it's the subscription, get the tokens the 1st of the months)

**Comment by Rushor** [comment]
If you need info on Discord Connection or Ingame Support Ticket setup let us now
