### ISSUE TITLE
NPC Jordy Smith item(s?) & Barbershop

### ISSUE THREAD

**Issue by Gainarrow** [WoWManiaUK/Redemption#5495]
Bought item from NPC Jordy Smith and did transmog.
Item info - http://www.wow-mania.com/armory?item=71100

Item itself when wearing and also when its in use as transmog, conflicts with sitting in barbershop chair (Happens with and without confirmation on window).

It leaves frontal white apron on character after.
(Might happen with other chest pieces from this vendor as well..)

Its not permament thing, logging out and being in combat helps (but not /reload).

![Apron](https://user-images.githubusercontent.com/46394455/119638113-04e03c00-be1f-11eb-8aa2-1a02df12d4fd.png)

**Comment by WhitephoenixTheBunny** [comment]
Try relog, it happens sometimes...

**Comment by Gainarrow** [comment]
> 
> 
> Try relog, it happens sometimes...

I did wrote that logging out ("relog") helps.
And "happens sometimes" happens with this particular piece 100%.

So instead writting ticket, Im reporting here. 👍

**Comment by WhitephoenixTheBunny** [comment]
Oh, sorry...

**Comment by wow-mania** [comment]
Thanks for the report but we will not be fixing this as transmogs are not part of wotlk and the barber has no way of knowing about it.

**Comment by Gainarrow** [comment]
That makes actually sense. Thank you!
