### ISSUE TITLE
[Object] Ethereum Prison Chamber isn't respawning never again after one use.

### ISSUE THREAD

**Issue by lordiman** [WoWManiaUK/Redemption#5496]
**Links:** https://wow-mania.com/armory/?object=184595

**What is Happening:** After opening ethereum prison chambers, they they work ok, we can kill or rescue npc which spawn from them. But those purple balls do not appear again.

**What Should happen:** Those prisons must respawn after 3 minutes.

**Comment by jeyrella** [comment]
Works fine?  Not sure what you're seeing, but these respawn perfectly fine.

**Comment by lordiman** [comment]
I mean not ethereum prison. Not those https://wow-mania.com/armory/?object=184429

I mean "Ethereum Stasis Chambers". Just https://wow-mania.com/armory/?object=185461

**Comment by lordiman** [comment]
My mistake. I was talking about prisons, and, issue is with stasis, not prisons

**Comment by jeyrella** [comment]
Ah. Not sure about those actually

**Comment by jeyrella** [comment]
ah i see new ticket already opened :D
