### ISSUE TITLE
[Object] Ethereum STASIS Chamber not working properly.

### ISSUE THREAD

**Issue by lordiman** [WoWManiaUK/Redemption#5497]
Links: https://wow-mania.com/armory/?object=184595

What is Happening: After opening ethereum STASIS chambers, they they work ok, we can kill npc which spawn from them. But those purple balls do not appear again.

What Should happen: Those STASIS CHAMBERS must respawn after 3 minutes.

My first report today was mistake, sorry...

**Comment by Rushor** [comment]
will inspect this

**Comment by Rushor** [comment]
the respawn setting is totally missing for them, added that they will respawn (reactivate) after 3 minutes
