### ISSUE TITLE
[NPC] Indu'le Fisherman unreachable - Dragonblight

### ISSUE THREAD

**Issue by LzVni** [WoWManiaUK/Redemption#5498]
**Links:**
[No proper link needed since it's an enemy reach problem]

**What is Happening:**

Indu'le Fisherman is out of bounds.

A few Indu'le Fisherman 's. Are unreachable for melee units such as [Warriors].

Not even skills seem to work, as they are out of range.

Aoe skills don't trigger them as well.

*Using a ranged Weapon however, seems to aggro them without issue.*

= After using a ranged weapon attack, their true placement seems to be visible=

**What Should happen:**

Enemy should be in range of attacks.

![WoWScrnShot_052621_102934](https://user-images.githubusercontent.com/71805677/119669241-49afa700-be0e-11eb-8ce3-22cac2fa4be6.jpg)

[File 1. shows attack from behind]

![WoWScrnShot_052621_103645](https://user-images.githubusercontent.com/71805677/119669285-5207e200-be0e-11eb-9903-145c807ef060.jpg)

[File 2, Shows attempt from the front]

![WoWScrnShot_052621_103757](https://user-images.githubusercontent.com/71805677/119669585-8c717f00-be0e-11eb-90fe-f730886a95f0.jpg)

[File 3. Shows where the true placement of the enemy is]

![WoWScrnShot_052621_104105](https://user-images.githubusercontent.com/71805677/119670025-ed00bc00-be0e-11eb-8c73-b601e0554b0a.jpg)

[File 4. Showing 2nd Mob, being out of range]

**Comment by Rushor** [comment]
position issue, will fix

**Comment by svijetlo** [comment]
works fine now i think it can be issue i remember some time ago if you walk a lot on ice you would get hack warning
