### ISSUE TITLE
[QUEST] Picking up some power converters not working

### ISSUE THREAD

**Issue by lordiman** [WoWManiaUK/Redemption#5499]
**Links:** https://wow-mania.com/armory/?quest=10584

**What is Happening:** when protovoltaic collector is used on electromental, and i can kill him, when he has "bubble" on, the quest is not going to progress. Nothing happen. I dont get any score.

**What Should happen:** When i kill electromental when he has bubble on it must score. It should be complete, when 5 electromentals is bubled and killed.

**Comment by jeyrella** [comment]
_What Should happen: When i kill electromental when he has bubble on it must score. It should be complete, when 5 electromentals is bubled and killed._

Nope, not quite.  Read the quest again :)

PTR is down right now so I can't test.  Are you sure this is not working, when you've read again what the completion criteria for the quest is?  I know for a fact I have completed it on at least 4 alts.

**Comment by lordiman** [comment]
Ok. strange it is... Sometimes it scores, sometimes not. I dont understand why. All i do, i do the same way all the time.

**Comment by lordiman** [comment]
Now I see whats going on. Those electromental not always get title "encases electromentals" when i use collector. so this is main issue. So question is:
Is it randomly, or it should be happen always?

**Comment by Rushor** [comment]
when i used https://de.wowhead.com/item=30656 on the creature i always got the credit

**Comment by lordiman** [comment]
So maybe i was getting visual bug or smthing. Anyway.. Quest is complete.
