### ISSUE TITLE
[Item] Deathbringers Will procs Strength for Druids

### ISSUE THREAD

**Issue by AranMat** [WoWManiaUK/Redemption#5500]
**Links:**
https://wowwiki-archive.fandom.com/wiki/Deathbringer%27s_Will

**What is Happening:**
Death bringers will is procing the str buff on a druid. 

**What Should happen:**
According to link above only, agility, haste, attack power and crit procs for druid

![Capture1](https://user-images.githubusercontent.com/38553469/119889269-a27a5f00-bf36-11eb-9e94-873f31ea2deb.JPG)
![Capture](https://user-images.githubusercontent.com/38553469/119889287-a7d7a980-bf36-11eb-85d4-c0073770be31.JPG)

**Comment by Keader** [comment]
fixed
