### ISSUE TITLE
[Spell] Warlock - Seed of Corruption ignores line of sight

### ISSUE THREAD

**Issue by Kreepsula** [WoWManiaUK/Redemption#5502]
**Links:**
https://wow.gamepedia.com/Seed_of_Corruption

**What is Happening:**

Seed of corruption explosion ignore line of sight

**What Should happen:**

**Patch 2.3.0 (2007-11-13): Seed of Corruption detonation will now obey line of sight**

**Comment by Keader** [comment]
fixed
