### ISSUE TITLE
[Druid] Shapeshifting does not remove slow auras

### ISSUE THREAD

**Issue by Hajzlopuc** [WoWManiaUK/Redemption#5506]
Hello, 

**What is Happening:**

Druid shapeshifting doesn't remove slow auras.
I think it might be related to the last fix of freedom 
https://github.com/WoWManiaUK/Redemption/issues/5492

**What Should happen:**
Druid shapeshifting should remove slow auras.

**Comment by Keader** [comment]
Last fix dont affect only Hand of freedom, it affect the whole mechanic.
It should dispel aura, ONLY if aura has only snare effect. If not, it will remove snare component, but not the whole aura.

**Comment by Keader** [comment]
Oh, no... it's bugged lol

**Comment by Keader** [comment]
Fixed
