### ISSUE TITLE
[Quest] The Sub-Chieftains

### ISSUE THREAD

**Issue by gorgar19** [WoWManiaUK/Redemption#5507]
**Links:**
https://www.wowhead.com/quest=11907/the-sub-chieftains

**What is Happening:**
not 100% sure its a bug or a working as intended 
your supposed to kill the 4 sub chieftains by clicking four  gears and that works perfectly each gear summoned the corresponding chieftain  but you can keep clicking the gear resummoning them over and over getting at lvl 73 2k and some change exp. i tested it and managed to get 3 of the same mob up at the same time  netting a quick 6k exp.

**What Should happen:**
i didn't see any posts online about using that as a quick easy way to grind out some exp so i believe it should not let you click and summon the ones your already marked as completed?

**Comment by Rushor** [comment]
Nah that is Bug

**Comment by Rushor** [comment]
they will no longer reward XP and can no longer be summoned if there is already a unit of that entry in range
