### ISSUE TITLE
[Item] Engineer - Gnomish Battle Chicken does not proc its buff

### ISSUE THREAD

**Issue by StomperFury** [WoWManiaUK/Redemption#5508]
**Links:**
https://classic.wowhead.com/item=10725/gnomish-battle-chicken
https://youtu.be/_QcuB8zCpu4

**What is Happening:**
The Gnomish Battle Chicken for Engineers isnt giving the 5% Attack Speed to the party/ Is not procing at all I have Tested this outside orgrimmar where cds reset and had a person use this in duels while watching for the buff to apply but didnt tested about 20 times and no proc at all 

**What Should happen:**
There should be a Chance for the Gnomish Battle Chicken to give -Battle Squawk-
Adds 5% attack speed to party members in 100 yards 
Duration 4 min
As you can see in the video 3-5 of the DPS puts down a chicken before the start of the pull and gives them the buff but on here on Mania we are not getting the buff at all

**Comment by Rushor** [comment]
checking

**Comment by svijetlo** [comment]
![image](https://user-images.githubusercontent.com/61908373/120342588-36ae4280-c2f8-11eb-91e1-38425ff2b52e.png)

**Comment by Rushor** [comment]
the buff should be given now

**Comment by hawker357** [comment]
Buff is given out now by the Battle Chicken
![Screenshot (67)](https://user-images.githubusercontent.com/79724094/120472968-6e6fc580-c39e-11eb-9ee1-d4050f36554e.png)
