### ISSUE TITLE
[Quest] Gluttonous Lurkers

### ISSUE THREAD

**Issue by gorgar19** [WoWManiaUK/Redemption#5509]
**Links:**
https://www.wowhead.com/quest=12527/gluttonous-lurkers

**What is Happening:**
your supposed to collect rats to toss at the basilisk and everything works and the quest can be completed but its letting you pick up the rats mounted .you get the message that your mounted but still collect the rat
**What Should happen:**
think it should dismount you or not let you pick up the rats when mounted.

**Comment by Rushor** [comment]
will fix that

**Comment by Rushor** [comment]
> not let you pick up the rats when mounted

added that
