### ISSUE TITLE
[Item] Yeh'kinya's Scroll unavailable

### ISSUE THREAD

**Issue by KidoBird** [WoWManiaUK/Redemption#5510]
**Links:**
Item:
https://www.wow-mania.com/armory/?item=10818

NPC:
https://www.wow-mania.com/armory/?npc=8579

Quest:
https://www.wow-mania.com/armory/?quest=3528

**What is Happening:**
After finishing the quest line (to summon the Avatar of Hakkar) the NPC Yeh'kinya should be able to give you the Yeh'kinya's Scroll to summon the Avatar of Hakkar again, but Yeh'kinya does not have the option to give you the scroll.

**What Should happen:**
Yek'kinya should be able to give you the scroll after finishing the quest chain.

![image](https://user-images.githubusercontent.com/60542988/120681616-d821c980-c49b-11eb-8df0-ab4406c99eb4.png)

**Comment by Rushor** [comment]
gossip has conditions if i remember right, will check the script.

**Comment by Rushor** [comment]
if quest 3528 has been rewarded and npc and player does not have item 10818 in inventory or bank, the plaer will see a gossip to get that item again. also added endevent rp for quest: Confront Yeh'kinya

**Comment by svijetlo** [comment]
![WoWScrnShot_060821_130102](https://user-images.githubusercontent.com/61908373/121173913-a2912d80-c859-11eb-8103-2b0b54d51e9d.jpg)
