### ISSUE TITLE
Helya's Fury (Warswords of the Valarjar) should sheathe on the back not waist

### ISSUE THREAD

**Issue by timbazi** [WoWManiaUK/Redemption#5511]
_I was redirected here from ticket 1155._ An transmog item sold by Harrison Jones in the WoW-Mania's Mall called "Helya's Fury (Warswords of the Valarjar)" sheathes on the waist of the character (female goblin in my case) when it should be on the back (according to wowhead) [wowhead dressingroom link](https://www.wowhead.com/dressing-room#dszm0zJ89c8zU8Tj8zS8Td8zW8Tl8zX8MFf8st8zD18d38MF18zY8ja8d58MHA8d28MFP8rz8MHg8rs8MJe87FvXY87cvXQ87VvYh808vXU808vXZ808vYa808vYk808Chg87R)
![issue1](https://user-images.githubusercontent.com/31126502/120903904-a5b9cd00-c651-11eb-9d36-b3b09931d16d.JPG)
![issue2](https://user-images.githubusercontent.com/31126502/120903905-a6eafa00-c651-11eb-913d-a02a5570ceed.JPG)

**Comment by Keader** [comment]
maybe need a client update?

**Comment by svijetlo** [comment]
could be if you ask me changes like this would need it if i remember correctly , ands yes i did delete cache etc i do it before every testing session

**Comment by wow-mania** [comment]
This will remain like this until a possible client update.
