### ISSUE TITLE
Energy Regeneration is not being effected by your haste %

### ISSUE THREAD

**Issue by Anw990** [WoWManiaUK/Redemption#5514]
**Links:**
https://www.wowhead.com/forums/topic/does-haste-affect-energy-regeneration-183407

https://us.forums.blizzard.com/en/wow/t/haste-energy-regen-but-how-much/172675

https://youtu.be/D5gIW7sYMXw

**What is Happening:**
Doesn't matter what your haste is, your energy regeneration is the same.

**What Should happen:**
Your regen rate should increase by roughly 1 energy per second for every 10% Haste

**Comment by Keader** [comment]
Your sources is from Cataclysm and not valid to wotlk.
