### ISSUE TITLE
[Spell] Druid - Tiger's Fury + Berserk 

### ISSUE THREAD

**Issue by svijetlo** [WoWManiaUK/Redemption#5517]
**Links:**
http://www.wow-mania.com/armory?spell=50213
http://www.wow-mania.com/armory?spell=50334
**What is Happening:**
![image](https://user-images.githubusercontent.com/61908373/121011351-ca6b8d00-c796-11eb-83d7-9452036395d2.png)
if Feral dps cat use Tiger's Fury 1st then he can use Berserk after it and buffs will stack , while if you use Berserk 1st you can not use tiger's Fury ,

**What Should happen:**
if one has Tiger's Fury on use of Berserk should remove Tiger's Fury

**Comment by Keader** [comment]
fixed
