### ISSUE TITLE
[Quest] Assault by Air Parachute (Horde/Alliance)

### ISSUE THREAD

**Issue by hawker357** [WoWManiaUK/Redemption#5521]
**Links:**
https://www.wowhead.com/quest=13309/assault-by-air
https://www.wowhead.com/quest=13310/assault-by-air

**What is Happening:**
When the quest objective completes and the ship despawns, the player does not get a parachute buff. The horde quest deals around 1k damage, and the alliance side deals 29k damage, killing the player.

**What Should happen:**
When the quest objective completes and the ship despawns, the player should get a parachute buff to prevent death from fall damage.

![Screenshot (78)](https://user-images.githubusercontent.com/79724094/121350446-9a50f500-c922-11eb-99b2-332cc2fa13b0.png)

**Comment by Rushor** [comment]
try now pls, player should get parachute if he leaves the turret now

**Comment by Echinaceax** [comment]
player in world chat said Ally still bugged - i see nobody confirmed your fix @Rushor 
with test tomorrow and re-open if it is
