### ISSUE TITLE
SPELL - Brain Freeze wrong procs

### ISSUE THREAD

**Issue by Kreepsula** [WoWManiaUK/Redemption#5523]
**Links:**

https://urbad.net/blue/us/24038455828-Brainfreeze_Procs_too_bursty
https://web.archive.org/web/20110902035416/https://blue.mmo-champion.com/topic/7/recent-in-game-fixes-march-2010-3-24

**What is Happening:**

Brain Freeze is procing with Frostfire Bolt and Frost Nova

**What Should happen:**

Should not proc with those 2 spells.
The first one to avoid frostfirebolt instant proc other frostfire bolt instant and make a super burst overpower

**Comment by Keader** [comment]
nice catch

**Comment by Keader** [comment]
fixed
