### ISSUE TITLE
QUEST - Drop it then Rock it

### ISSUE THREAD

**Issue by sergiorkd** [WoWManiaUK/Redemption#5524]
**Links:**

**What is Happening:**
When doing the quest Drop it then Rock it by alliance side, a lot of valkys spwns when I plant the banner on the groud. Turns out its impossible to defend the quest objective because there are like 10 mobs hitting me at the same time.

**What Should happen:**
Mobs supose to spawn one at time

**Comment by Rushor** [comment]
should only summon 3 creatures now

**Comment by wow-mania** [comment]
Please make sure you add links and info when you log an issue. It will help the developers.

**Comment by Rushor** [comment]
true ture, will quick add - quest is: quest=11429
