### ISSUE TITLE
QUEST - You're Fired Quest seems bugged!

### ISSUE THREAD

**Issue by peeyushnegi** [WoWManiaUK/Redemption#5525]
**Links: https://tbc.wowhead.com/quest=10821/youre-fired#comments**

**After wearing [Felsworn Gas Mask] I killed 5 guards and obtained the key.
I activated all 5 Obelisks but Doomcryer wasn't summoned**

**What Should happen: The Doomcryer should be summoned**

**Comment by Rushor** [comment]
checking, maybe in the script sth dos not reset

**Comment by jeyrella** [comment]
I've done this at least 6 times, the most recent just a few weeks ago, so I know it has worked perfectly fine for some time at least

**Comment by Rushor** [comment]
will check the quest script, if i remember correct there are also some elements missing like the beams

**Comment by Rushor** [comment]
fixed all, obelisks can now also only be clicked every 5 minutes to prevent spamm
