### ISSUE TITLE
[Spell] Feral Spirit: Incorrect Base Statistics

### ISSUE THREAD

**Issue by Lantanio** [WoWManiaUK/Redemption#5526]
### **Links:**

- Evidence from Rawr source files: 
[rawr-53855_extract.txt](https://github.com/WoWManiaUK/Redemption/files/6651802/rawr-53855_extract.txt)
- See last section of: [https://www.mmo-champion.com/threads/624759-*Enhancement-Shaman-FAQ-(3-3)*]( https://www.mmo-champion.com/threads/624759-*Enhancement-Shaman-FAQ-(3-3)*)

### **What is Happening:**

Enhancement Shaman wolves (summoned with the Feral Spirit talent) currently have **22 base Strength and Agility**. See the screenshot below for proof. To reproduce, add wolves manually to the pet display tab (C > Pets > Pet) through the following script

/run if not oldHasPetUI then oldHasPetUI = HasPetUI; HasPetUI = function() return true, false; end end PetTab_Update() ToggleCharacter("PetPaperDollFrame")

<img width="250" alt="feral spirit stats" src="https://user-images.githubusercontent.com/85909876/121972207-c7fec980-cd7a-11eb-9894-2eeba4b36389.png">

### **What Should happen:**
At level 80, base statistics should be 

- **Base Strength: 331**
- **Base Agility: 113**

Strength should be converted into AP on a x2 basis and Agility should increase the wolves crit chance.

**Comment by Keader** [comment]
i realy dont know if we can fix it right now...
pet status system is miss implemented

**Comment by Lantanio** [comment]
Not sure what the problem is, but if it has to do with, say, the STR to AP conversion a possible solution would be adding 662 plain attack power

**Comment by Keader** [comment]
fixed
