### ISSUE TITLE
cant hand in wg quests

### ISSUE THREAD

**Issue by reynardsf85** [WoWManiaUK/Redemption#5528]
I am unable to hand in the folowing wg quests, cant talk to the npc's

I rare herb
bones and arrows
fueling the demolishers

character

Rumppaj
redemption

**Comment by jeyrella** [comment]
You need to turn them into the same NPC that you picked them up from.
i.e. if your faction holds the fortress when you take them, you can only hand them into the NPCs in the fortress while your faction holds the fortress and **not** at the camp, and vice versa.

Please confirm if this is the case.

**Comment by reynardsf85** [comment]
then I have to wait for hordde to take over wg and see:) , I'm sure I have taken quest there and handed them in at the fortress but maybe Im mistaken

**Comment by Lantanio** [comment]
I think I experienced this issue in the past. I believe what happens is that when weeklies reset you get phased from the questgiver and cannot turn in previous week's quests. This would also be consistent with the timing of this report. I will try to confirm this on the next reset.
