### ISSUE TITLE
[Spell] Greater Fire Elemental: Incorrect Guardian Spell Damage/Scaling

### ISSUE THREAD

**Issue by Lantanio** [WoWManiaUK/Redemption#5529]
### **Links:**
- **Rawr 2.3.23** source files for WotLK (Lines 68-70). See for average base damage and scaling. 
[FireElemental.txt](https://github.com/WoWManiaUK/Redemption/files/6659463/FireElemental.txt)
- Source files from **EnhSim** for Cata provide minima and maxima **consistent with average WotLK base** from the above Rawr file. See lines 115-142. [level85.txt](https://github.com/WoWManiaUK/Redemption/files/6659470/level85.txt)

### **What is Happening:**
Spells of the Greater Fire Elemental (Shaman guardian) seem to have incorrect damage values/scalings. Consider the example of **Fire Nova (Greater Fire Elemental)**. 

- Minimum base damage should be 925. 
- The spell scales with 0.5 of the Shaman's spellpower, snapshotted on totem cast. 
- My shaman has 3239 bonus spell damage without buffs or totems (see Image 1 below). 

<img width="200" alt="stats" src="https://user-images.githubusercontent.com/85909876/122136540-fe078080-ce42-11eb-98a9-f9a90c123fb7.png">

This should result in an **unbuffed minimum of 2544.5 per hit**. Yet, in an ICC raid scenario (with additional buffs etc) real minima and even maxima are much lower (see Rotface Encounter in Image 2 below).

<img width="800" alt="Rotface Fight" src="https://user-images.githubusercontent.com/85909876/122141431-97d42b00-ce4d-11eb-87f9-e0809e9faa4b.png">

For reference, SP on a typical totem cast is in the 5-6k range for Spellhance. The wedge in damage then becomes substantial. The same applies to remaining spells. 

### **What Should happen:**
Spell values should be as follows:

- **Fire Blast (Greater Fire Elemental)**: [725-825 base] + 0.2 * SP (on totem cast)
- **Fire Nova (Greater Fire Elemental)**: [925-1050 base] + 0.5 * SP (on totem cast)
- **Fire Shield (Greater Fire Elemental)**: [96 base] + 0.015 * SP (on totem cast)

The linked files include other stat references which are harder to test from a pure user experience, but perhaps still worth a check.

**Comment by Keader** [comment]
fixed, implemented scaling system for this guardian
