### ISSUE TITLE
Mammoths perma combat you while on their back

### ISSUE THREAD

**Issue by LzVni** [WoWManiaUK/Redemption#5530]
**Links:**
https://www.wow-mania.com/armory/?quest=12707

**What is Happening:**
After using the [Charge] Skill of the mammoth once, you are not able to do it again.
You are permanently in combat as long as you stay in the Mammoth back

**What Should happen:**
After killing an enemy you should leave combat
The skill should be able to be used more than once

![WoWScrnShot_061621_172235](https://user-images.githubusercontent.com/71805677/122288891-75332800-cec8-11eb-8769-0554d014650e.jpg)

[Attachment 1. Showing proper skill display before entering anykind of combat]

![WoWScrnShot_061621_172401](https://user-images.githubusercontent.com/71805677/122288972-9136c980-cec8-11eb-8f2a-6cbeb42afc8f.jpg)

[Attachment 2. Showing bug in display of in-and-out of combat, and thus not allowing use of skill.]

**Comment by jeyrella** [comment]
Known, can't be fixed.

**Comment by jeyrella** [comment]
https://github.com/WoWManiaUK/Redemption/issues/4908
