### ISSUE TITLE
Unkillable High Priest Hawinni

### ISSUE THREAD

**Issue by LzVni** [WoWManiaUK/Redemption#5531]
**Links:**
https://www.wow-mania.com/armory/?quest=12674

**What is Happening:**
After being subjected to the  [Quetz'lun's Hexxing Stick], and having the animation of "Exploding", he stays immortal and keeps attacking the player.
After walking away from the mob, he instantly resets his position, and returns to before being affected by the quest item.

**What Should happen:**
The mob should be considered "Dead"
and have it's corpose dissapear properly

![WoWScrnShot_061621_163443](https://user-images.githubusercontent.com/71805677/122290056-bf68d900-cec9-11eb-849d-0dc5892dc570.jpg)

[Attachment 1. Showing hitting the mob after effect of the quest-item.]

![WoWScrnShot_061621_163448](https://user-images.githubusercontent.com/71805677/122289917-9d6f5680-cec9-11eb-8d2d-a3f4a2456ed6.jpg)
[Attachment 2. Showing the mob hitting player, while staying alive.]

**Comment by Rushor** [comment]
all 3 creatures should now depawn after 2 seconds on "death" to prevent such stuck cases
