### ISSUE TITLE
QUEST - Blinding the Eyes in The Sky

### ISSUE THREAD

**Issue by ysl060704** [WoWManiaUK/Redemption#5532]
**Links:**
https://www.wowhead.com/quest=13313/blinding-the-eyes-in-the-sky

**What is Happening:**
Suppose to fire at Skybreaker Recon Fighters

**What Should happen:**
No Skybreak Fighters spawn

**Comment by ysl060704** [comment]
No Skybreaker Fighters

**Comment by Rushor** [comment]
there were too less spawns for them, added a few more to make the quest more smooth
