### ISSUE TITLE
4th set bonous shaman enhancement

### ISSUE THREAD

**Issue by soloistttt** [WoWManiaUK/Redemption#5533]
**Links:**

**What is Happening:**hey there im an enhancement shaman with 4th (named soloistt in game) set but the 4th set bonous is not working ive been trying for 2 days and no buffs or increased stats happend i think its broken its supposed to give 20% more AP(15%chance) when mealstorm weapon tallent reaches 5 stacks but its not giving any

**What Should happen:**

**Comment by Oganku** [comment]
This worked fine a few months ago and I would be very surprised if it broke. Also considering I've seen multiple enhances do well recently, I'd say it's not broken. Can double check later.

**Comment by Keader** [comment]
tested in ptr, is working.
