### ISSUE TITLE
Spell "Tame pet" doesnt work

### ISSUE THREAD

**Issue by Inkcapable** [WoWManiaUK/Redemption#5534]
Hi, I have a problem with my Hunter character.
Account name "Inkcapable" character "Noico". Patch 2.9.3. Relevant quest done and completed.
When I am trying to tame new pet spell "Tame Pet" doesnt work as it should, instead of taming new pet is calling my existing pet. I know I have to dismiss current pet before using it, yet still instead of taming new beast it is recalling old pet. Looks like under my "Tame Beast" spell I have "Call Pet" linked. It was working at the beggining as I do have one pet tamed, so something broken in the meantime. Game master tried to fixed it to no avail, advised me to drop a line in here. Could you help please?

**Comment by Keader** [comment]
Someone can confirm it?

**Comment by Keader** [comment]
You must abandon your current pet before tame a new one.
You should not "dismiss", you should "abandon"
![image](https://user-images.githubusercontent.com/7120913/122460771-eb975f00-cf88-11eb-9998-d31e32f0c926.png)
working fine in ptr.

**Comment by Inkcapable** [comment]
Hi,
your solution didnt solve my problem. Abandoning means I am removing my pet pernamently, which means I will always have only one pet, and as a hunter as far I am concerned, I should be able to tame few pets, not only one.
My problem is not removing pet pernamently, but dissmissing it, while I want to tame and use other one. For example I want to have lion, turtle and cat as my pets. I should be able to dismiss one to use other one (but it would still be my pet).
Whats the advise on it?

**Comment by Echinaceax** [comment]
@Inkcapable 
Have you stabled your pet you want to keep?

i will log my hunter and see (i having played mine on Mania for a while)

**Comment by Keader** [comment]
Try this @Inkcapable 

https://youtu.be/yrEadqSpKSo

**Comment by Echinaceax** [comment]
> Try this @Inkcapable
> 
> https://youtu.be/yrEadqSpKSo

Your video was better than mine lol @Keader

**Comment by Inkcapable** [comment]
@Echinaceax @Keader I have stabled my pet no 1  now, but I dont have a spell CALL STABLED PET. ( I am only level 30 and this spell comes in lvl 80 ) So now I can tame new pet (no 2) - as no1 is left in stables, but again  I can not tame new pet. When I am trying to use Tame Pet it comes with info "You already control summoned creature". So something is still wrong.... I remember playing on different server I was able to pick and choose my pets, dismiss and tame new pets, without keeping them at stables and definatelu, it was availible quicker then lvl 80. How can I expo if as a hunter I ve got access only to one pet? :)
Dig deeper you are the Smart Heads :)

**Comment by Echinaceax** [comment]
@Inkcapable 
Didnt know you was low level 

So when you put your pet in the stabe you should have your current pet slot empty now correct?
can you screenshot your empty pet slot for us then we can see ?

If i remember correctly hunters get more pet slots as they get higher level. At lvl 30 i think you only have 1 or 2 slots on stable 
(been so long since i was a low level hunter

**Comment by Inkcapable** [comment]
![image](https://user-images.githubusercontent.com/86075744/122577976-55783d00-d04b-11eb-81e3-e87e17f379cc.png)
My stable looks like yours, got 4 slots, but for now purchased only 2 empty slots - whats the point to buy more and spend the money if I can not use it properly :)
Sorry, I should mentioned my character is lvl 30.
I dont mind if any of you want to use Team Viewer to try solutions yourself?

**Comment by Inkcapable** [comment]
@Echinaceax ha! I have no idea how to use discord :) team viewer?

**Comment by Echinaceax** [comment]
> @Echinaceax ha! I have no idea how to use discord :) team viewer?

yes i have teamviewer

**Comment by Inkcapable** [comment]
great, how can I give you pass?

**Comment by Echinaceax** [comment]
> great, how can I give you pass?

usually we use Discord :)

**Comment by Inkcapable** [comment]
If you guide me I can use Discord, I just have no idea how, lol

**Comment by Echinaceax** [comment]
> If you guide me I can use Discord, I just have no idea how, lol

just make an account then send friend request to Echinacea :)

**Comment by Inkcapable** [comment]
oki, bare with me

**Comment by Inkcapable** [comment]
whats your 4 digit tag?
discord asked :)

**Comment by Echinaceax** [comment]
> whats your 4 digit tag?
> discord asked :)

Echinacea#9418

**Comment by Echinaceax** [comment]
all fixed @Keader 👍

**Comment by Inkcapable** [comment]
Thank you very much for all your help both @Keader and @Echinaceax  x
