### ISSUE TITLE
Improper display of the amount of health restored [Sauteed Goby]

### ISSUE THREAD

**Issue by LzVni** [WoWManiaUK/Redemption#5535]
**Links:**
https://www.wow-mania.com/armory/?item=34761#created-by

**What is Happening:**
In the Armory [Sauteed Goby] says it restores 37500 health over 30sec.
in game it says it restores 22500 Health over 30sec.
and it does restore 22500 over 30sec [750 p/s].

**What Should happen:**
Either the description in the armory should be correctly fixed, or the description and value in-game should be ajusted.

![WoWScrnShot_061721_235825](https://user-images.githubusercontent.com/71805677/122500047-659b0880-cfc8-11eb-82cd-abf04b0b51d5.jpg)

[Attatchment 1. A mouse overview of the [Sauteed Goby]

**Comment by Rushor** [comment]
possible wrong item spell, will check

**Comment by LzVni** [comment]
The "refreshment" of 37500 is used by two other more fish items. 
Which also are being improperly displayed as they both also in-game heal for 22500
[Grilled Bonescale] [Smoked Rockfin]

**Comment by wow-mania** [comment]
This is not for armory issues.
Armory updates are done in batches from time to time. Not weekely.
