### ISSUE TITLE
The Cipher of Damnation

### ISSUE THREAD

**Issue by ysl060704** [WoWManiaUK/Redemption#5536]
**Links:**
https://tbc.wowhead.com/quest=10588/the-cipher-of-damnation

**What is Happening:**
Cyrikh the Firelord can be Summon.

**What Should happen:**
But mob is not able to attack and just stay there. Quest can't be completed.

**Comment by ysl060704** [comment]
Tried summoning Firelord again. 2nd spawn but also can't be attack.
Multiple firebird can be summoned but not able to attack.

**Comment by ysl060704** [comment]
have to talk to npc to initiate boss fight

**Comment by Rushor** [comment]
yep you need to talk to them to start the fight
