### ISSUE TITLE
[OBJECT] Ore stuck in ground 63.7 22.8 Icecrown

### ISSUE THREAD

**Issue by Bulb1** [WoWManiaUK/Redemption#5537]
Links:
[Titanium Vein](https://wow-mania.com/armory/?object=191133)
[Saronite Deposit](https://wow-mania.com/armory/?object=189980)
What is Happening:
![image](https://user-images.githubusercontent.com/66064613/122633972-b51e2900-d0db-11eb-8c70-db08a4cd2c5a.png)

**Comment by Bulb1** [comment]
There are 2 ore deposits in this area, one spawns on top and the other one is stuck under

**Comment by Rushor** [comment]
Will check

**Comment by Rushor** [comment]
is true https://i.imgur.com/pNoP3qd.png
