### ISSUE TITLE
Quest: The Cudgel of Kar'desh

### ISSUE THREAD

**Issue by ysl060704** [WoWManiaUK/Redemption#5538]
**Links:**
https://tbc.wowhead.com/quest=10901/the-cudgel-of-kardesh

**What is Happening:**
I have to enter Heroic Slave Pen and Find Skar'this the Heroic to get 2 quest from him.
When I reached him (in Heroic), he is there but white exclamation mark.
A quest that you are not quite at the right level to pick up yet.

I check for pre-requisite and I need Serpentshrine Caverns Attunement which is no longer needed right?
I don't see any other pre-requisite.

Found this: This quest has NOT been removed from the game, but made unavailable to characters above level 70! Simply speak to Skar'this the Heretic again to continue.

Without getting his quest I'm not able to complete Champion of the Naaru Title. 

**What Should happen:**
Able to take the quest.

**Comment by wow-mania** [comment]
Please refer to our Armory.
https://www.wow-mania.com/armory/?quest=10901
Quest does have pre-req as per retail in 2010 not today. :)
