### ISSUE TITLE
LK Shambling is immune to slow

### ISSUE THREAD

**Issue by Kreepsula** [WoWManiaUK/Redemption#5540]
**Links:**

https://youtu.be/_yYyeEKQB0A?t=520
https://youtu.be/_yYyeEKQB0A?t=9m12s
https://youtu.be/LCZx9h1ho4U?t=35

**What is Happening:**

Shambling is immune to slows

**What Should happen:**

Shambling should take slow, it helps tanks cait

**Comment by Keader** [comment]
fixed

**Comment by Kreepsula** [comment]
yo that was fast o.O

**Comment by hawker357** [comment]
Tested with 3 different slows, all take effect on the shamblings now.
![Screenshot (87)](https://user-images.githubusercontent.com/79724094/123631117-4c872880-d80e-11eb-82fc-5f25a4ea5689.png)
![Screenshot (88)](https://user-images.githubusercontent.com/79724094/123631122-4d1fbf00-d80e-11eb-94f3-bc9e4fe88e03.png)
![Screenshot (89)](https://user-images.githubusercontent.com/79724094/123631130-4e50ec00-d80e-11eb-90d1-c207fbd644cf.png)
