### ISSUE TITLE
Eye of the Broodmother procs with everything

### ISSUE THREAD

**Issue by Kreepsula** [WoWManiaUK/Redemption#5542]
**Links:**

https://www.wowhead.com/item=45308/eye-of-the-broodmother

**What is Happening:**

Should proc only with damaging and healing spells

**What Should happen:**

every cast make it proc
example: i can make it proc with my shaman water shield

**Comment by hawker357** [comment]
Confirmed that the trinket now only procs with damaging or healing spells. Buffs, even when casted by the player like water shield, weapon buffs etc do not proc.
