### ISSUE TITLE
Hunter talent Entrapment not always working

### ISSUE THREAD

**Issue by Kreepsula** [WoWManiaUK/Redemption#5543]
**Links:**

**What is Happening:**

Hunter talent Entrapment not work if hunter is far from trap

**What Should happen:**

Talent should root all targets around trap, even if hunter is not close

**Comment by Keader** [comment]
ok this is a fun bug.
was hitting targets around hunter, not trap KEKW
fixed.

**Comment by hawker357** [comment]
Just tested this on Elites and regular mobs. Entrapment debuff is not proccing at all now. (19184/19187/19188)

**Comment by Keader** [comment]
Fixed

**Comment by hawker357** [comment]
Entrapment is now triggering and is triggering for mobs around the trap.
![Screenshot (86)](https://user-images.githubusercontent.com/79724094/123627661-2cee0100-d80a-11eb-9f6c-0b08cf9c5ecb.png)
