### ISSUE TITLE
Lightweave/Swordguard Embroidery icd

### ISSUE THREAD

**Issue by Keader** [WoWManiaUK/Redemption#5544]
**What is Happening:**

Right now, both enchants has 45s as ICD.

**What Should happen:**

But after research in warcraft logs, after TOC patch, blizzard change it to: 60s Lightweave and 55s Swordguard Embroidery
It looks like "only 10/15 sec" but make a big difference in big encounters like Lich King.

**Comment by hawker357** [comment]
Confirmed, Swordgaurd now has the 55s ICD and Lightweave now has a 60s ICD
![Screenshot (79)](https://user-images.githubusercontent.com/79724094/123089909-73fd8000-d41f-11eb-8c8a-312d953852d5.png)
![Screenshot (80)](https://user-images.githubusercontent.com/79724094/123089918-75c74380-d41f-11eb-8a23-6bd4599206c5.png)
![Screenshot (82)](https://user-images.githubusercontent.com/79724094/123089922-77910700-d41f-11eb-8ba3-9eb41ef2260f.png)
![Screenshot (83)](https://user-images.githubusercontent.com/79724094/123089924-78c23400-d41f-11eb-866c-0826255dfe53.png)
