### ISSUE TITLE
Achievement Torch Juggler, Torch not working as intended

### ISSUE THREAD

**Issue by theonykry** [WoWManiaUK/Redemption#5545]
**Links:**
https://wow-mania.com/armory/?item=34599
https://wow-mania.com/armory/?achievement=272
**What is Happening:**
Visually the achievment works. i did it on my paladin last year aswell. Now what i came to realize is: Sometimes when the torch is thrown, visually the character catches the torch. Also the sound effect is working propperly, but even tho you see the character catching the torch, it doesnt reappear as it should in your bags. 

**What Should happen:**
once the torch is catched visually and wit haudio it should reappear in your bags so you can throw it again.

**Comment by wow-mania** [comment]
This has been fixed before so it should be either confirmed and marked as Regression, or closed.

**Comment by Rushor** [comment]
it's prolly a tiny spell range issue where people should get the spell triggered. Has been last year aswell like that

**Comment by Rushor** [comment]
try now after ptr has been restarted

**Comment by Rushor** [comment]
check now pls, just did it https://i.imgur.com/V5YpQzA.jpeg

you really need to spamm click and keep going even if it failed the first 2-3 times - it's a hard one :D

**Comment by joepl10** [comment]
I made a ticket about this as well, seems bugged. Tried it at alot of different positions in Dalaran, but the torches keep dissapearing out of my bag, and the counter keeps static at 0/40 (also while throwing them).

Brontes said they were aware of the situation, and was on their list to fix it asap. I hope they fix it before end of Midsummer Festival.
If you were able to do this achiev in 2021 (midsummer) then please comment, where and what you did.

**Comment by Rushor** [comment]
Have you complete the torch quests before?
