### ISSUE TITLE
[QUEST] Feeding Arngrim, you don't have to use quest item

### ISSUE THREAD

**Issue by Bulb1** [WoWManiaUK/Redemption#5547]
**Links:**
[Feeding Arngrim](https://wow-mania.com/armory/?quest=13046)
**What is Happening:**
![image](https://user-images.githubusercontent.com/66064613/123461319-419f7e80-d5e9-11eb-84ed-8a2e3b176334.png)
**What Should happen:**
![image](https://user-images.githubusercontent.com/66064613/123462141-39940e80-d5ea-11eb-9205-3b02d14751cc.png)

**Comment by Rushor** [comment]
will now only work if player has before used the questitem on the creature :)
