### ISSUE TITLE
Vicious Black Warsaber skin problem

### ISSUE THREAD

**Issue by Bubunya** [WoWManiaUK/Redemption#5548]
**Links:**
[Link to wowmania armory](https://www.wow-mania.com/armory/?item=158155)
[Link to wowhead](https://www.wowhead.com/item=165019/vicious-black-warsaber)

Evening.
I know you are extremely busy fixing game bugs and fighting our (players) stupidity :)
But maybe, just maybe, you'll have time and be able to fix this problem with Vicious Black Warsaber skin? It needs to be stretched just a bit so he doesn't look like he is after head collision with freight train. I don't really care 'bout bunch of other bugs and wrong colors and whatnot with this skin, but his face... 
I really like few mounts from mania store, but it seems none of them working the way it should.  So I was hopping at least this one basically standard cat without any special effects or shiny thingies will work :(  Please? :( 

![saber_002](https://user-images.githubusercontent.com/53129632/123537543-f75bf180-d6fd-11eb-86f9-4f5b62e923f4.jpg)

**Comment by Rushor** [comment]
requires client changes i guess

**Comment by wow-mania** [comment]
As-is. Not fixing this. Not all imports work as they should on an older client.
