### ISSUE TITLE
Chain quest

### ISSUE THREAD

**Issue by Mizerie1** [WoWManiaUK/Redemption#5549]
**Links:**

**What is Happening:**
So Saturday evening I did an 25 nm icc since I was still on shards, after we killed sindragosa I got my last shard for the shadowmourne quest I went to Darion to return the quest, I took my legendary and took the last quest where it's need to kill LK on 25 raid and loot the item for the quest to be completed. We killed the LK and I looked the boss but was no item for the quest but the quest showed that have been completed so I went at Darion, I give the quest and nothing alse happened after. I made a ticket in game and waited for a GM response after a GM been answered me we talked and he checked to see if I have finished the quest chain, after he told me to report the problem in here. 

**What Should happen:*
I have lost the npc's reward cuz I did not had the item quest but the quest it's done. So I don't rly know what to do now.

**Comment by Rushor** [comment]
Which item is missing exactly then?

**Comment by wow-mania** [comment]
You lose the item quest then you miss the requirement for the quest even if it was completed.
