### ISSUE TITLE
The Purification of Quel'Delar

### ISSUE THREAD

**Issue by nuoa123** [WoWManiaUK/Redemption#5551]
**Links:**
https://www.wow-mania.com/armory/?quest=24553

**What is Happening:**

![Screenshot (14)](https://user-images.githubusercontent.com/86771615/124095360-cb38cb80-da83-11eb-814b-b44759a8f706.png)

I try to speak with warden of the sunswell to enter the sunwell but nothing happen
**What Should happen:**

speak with warden of sunwell must be allowed me to enter sunwell

**Comment by jeyrella** [comment]
You need to be in a raid group.

**Comment by nuoa123** [comment]
what really? I watch on youtube it still ok, it's bug
