### ISSUE TITLE
[Item] Deadwood Headdress Feather does not drop

### ISSUE THREAD

**Issue by KidoBird** [WoWManiaUK/Redemption#5552]
Link: https://www.wow-mania.com/armory/?item=21377

Example NPC: https://www.wow-mania.com/armory/?npc=7154 , https://www.wow-mania.com/armory/?npc=7156 , https://www.wow-mania.com/armory/?npc=7157

What is Happening: After killing hundred(s) of Deadwood bears I could not find a single one while chance on the armory shows 25-35%

What Should happen: The item should drop way more often (the Winterfall Spirit Beads (https://wotlkdb.com/?item=21383) seem to drop fine

**Comment by Oganku** [comment]
Those used to drop fine not too long ago, might need to double check to make sure it didn't just break?

**Comment by Rushor** [comment]
Will check the rates

**Comment by Rushor** [comment]
dropchance is 25 percent, but you need quest 8460 rewarded first in order to see that loot drop

**Comment by Oganku** [comment]
Quest is [Timbermaw Ally](https://www.wow-mania.com/armory/?quest=8460) in case you wanna know @KidoBird .

**Comment by KidoBird** [comment]
I have completed that quest yet did not see the feathers drop

Via aPhone verstuurd dus kort en mogelijk met spelfouten
________________________________
Van: Oganku ***@***.***>
Verzonden: Saturday, July 3, 2021 7:09:54 AM
Aan: WoWManiaUK/Redemption ***@***.***>
CC: KidoBird ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [WoWManiaUK/Redemption] [Item] Deadwood Headdress Feather does not drop (#5552)


Quest is Timbermaw Ally<https://www.wow-mania.com/armory/?quest=8460> in case you wanna know @KidoBird<https://github.com/KidoBird> .

**Comment by KidoBird** [comment]
Oh wait, let me double check, the quest closer to the tunnel I completed I think; my apologies for making an incorrect request

Via aPhone verstuurd dus kort en mogelijk met spelfouten
________________________________
Van: Kerwin Goedhart ***@***.***>
Verzonden: Saturday, July 3, 2021 11:52:56 AM
Aan: WoWManiaUK/Redemption ***@***.***>; WoWManiaUK/Redemption ***@***.***>
CC: Mention ***@***.***>
Onderwerp: Re: [WoWManiaUK/Redemption] [Item] Deadwood Headdress Feather does not drop (#5552)

I have completed that quest yet did not see the feathers drop

Via aPhone verstuurd dus kort en mogelijk met spelfouten
________________________________
Van: Oganku ***@***.***>
Verzonden: Saturday, July 3, 2021 7:09:54 AM
Aan: WoWManiaUK/Redemption ***@***.***>
CC: KidoBird ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [WoWManiaUK/Redemption] [Item] Deadwood Headdress Feather does not drop (#5552)


Quest is Timbermaw Ally<https://www.wow-mania.com/armory/?quest=8460> in case you wanna know @KidoBird<https://github.com/KidoBird> .
