### ISSUE TITLE
[NPC] Elder Diemetradon stuck in tree! Un'goro Crater 24.6 54.5

### ISSUE THREAD

**Issue by Bulb1** [WoWManiaUK/Redemption#5553]
Links:
https://wow-mania.com/armory/?npc=9164
What is Happening:
![image](https://user-images.githubusercontent.com/66064613/124359045-8350aa80-dc23-11eb-9c07-4eb95fe44eb5.png)
What Should happen:
you know what *wink*

**Comment by Rushor** [comment]
Will fix :)

**Comment by Rushor** [comment]
fixed
