### ISSUE TITLE
[Raid] Faction Champions wrong kill dialogue 

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#5555]
**Links:** https://wowwiki-archive.fandom.com/wiki/Faction_Champions

**What is Happening:** Upon killing a raid member, the opposite faction's leader (either Varian or Garrosh) shouts various dialogue lines aiming to undermine the opponent's morale. However, these dialogues are currently swapped and the horde killing alliance dialogues play upon horde death, and the alliance killing horde on alliance death.

For example, if an alliance raid starts wiping to the Faction Champions, they will hear Varian repeatedly shouting lines such as: 

![image](https://user-images.githubusercontent.com/34783736/124361098-4f618f00-dbfb-11eb-9f0c-96c1a24100b0.png)
The last one being the most ironic, as the alliance are actually being wiped off the arena by the overpowering horde members. 😂 

**What Should happen:**  The correct lines should be played depending on whether an alliance or horde player is killed, causing the opposite faction's leader to use one of his 4 lines of dialogues listed below:
![image](https://user-images.githubusercontent.com/34783736/124361109-686a4000-dbfb-11eb-872a-82f41139cfd4.png)

A simple "faction-check swap" should be enough to fix this.

**Comment by Rushor** [comment]
text order should be correctly now
