### ISSUE TITLE
[QUEST] Last Rites Thassarian sitting on the job

### ISSUE THREAD

**Issue by womptista** [WoWManiaUK/Redemption#5557]
**Links:**
wow-mania armory link : https://www.wow-mania.com/armory/?quest=12019
Link to YT video showing him sitting on the job: https://youtu.be/-Jb9-VNvSk4

**What is Happening:**
Thassarian is sitting on the job I put in a previous github post about him and the boss acting up during this quest in another.

**What Should happen:**
Thassarian should be standing like a big boy NPC

**Comment by Rushor** [comment]
Checking

**Comment by womptista** [comment]
The only thing that I could think of is I was in combat when I entered the instance with Thassarian, as soon as I entered the instance with him I left combat and seen him sitting.

**Comment by Rushor** [comment]
should be fixed now

**Comment by jeyrella** [comment]
Reports that Thassarian is no longer interactive unless he is GM reset

**Comment by Rushor** [comment]
If we can reproduce would be great

**Comment by Rushor** [comment]
script should reset correctly now after respawn
