### ISSUE TITLE
Glyph of Pain Supression vs Seduction

### ISSUE THREAD

**Issue by Kreepsula** [WoWManiaUK/Redemption#5558]
**Links:**

**What is Happening:**

Glyph of Pain Suppression allow you cast Pain Suppression while affected by Stuns
But it should allow cast pain suppression while affected by Seduction too
Proof: https://www.youtube.com/watch?v=nZwxTlNXUxg&t=19s

**What Should happen:**

allow cast pain suppression while affected by Seduction

**Comment by Keader** [comment]
fixed
