### ISSUE TITLE
[Raid]  Deathbringer Saurfang - ICC - Wrong summon timer on Blood Beast

### ISSUE THREAD

**Issue by Kreepsula** [WoWManiaUK/Redemption#5559]
**Links:**

**What is Happening:**

Deathbringer surfrang is casting Summon Blood Beast first time in 30 seconds and repeat each 40 seconds

**What Should happen:**

It should first cast in 40 seconds and repeat each 40 seconds
10 seconds make a lot of difference, since blood beast can be melted by all boosts still active

**Comment by jeyrella** [comment]
@Kreepsula Can you help me with **reliable** sources for this please?  I have found one for 30 seconds, 1 for 40 seconds, and 2 for actually 35 seconds!

Am assigning "waiting reproduce" which, while not exactly right, is close enough for intention - needing more research before we touch this one as it is a primary raid.

**Comment by Keader** [comment]
i can confirm with sniffs @jeyrella 
DB should summon adds each 40 sec

**Comment by jeyrella** [comment]
including the initial one?

**Comment by Keader** [comment]
> including the initial one?

yeap

fixed

**Comment by hawker357** [comment]
Confirmed, Beasts now spawn 40 seconds after combat starts, and every 40 seconds after that.
![Screenshot (109)](https://user-images.githubusercontent.com/79724094/124592021-e8d7ad80-de54-11eb-8181-33e73bc27c37.png)
![Screenshot (110)](https://user-images.githubusercontent.com/79724094/124592028-ea08da80-de54-11eb-81f1-106cb18e227a.png)
![Screenshot (111)](https://user-images.githubusercontent.com/79724094/124592033-eaa17100-de54-11eb-8130-e834ec14938a.png)
![Screenshot (112)](https://user-images.githubusercontent.com/79724094/124592035-eb3a0780-de54-11eb-83e0-a68f0b4ff869.png)
