### ISSUE TITLE
[QUEST] Last Rites

### ISSUE THREAD

**Issue by womptista** [WoWManiaUK/Redemption#5560]
**Links:**
wow-mania Armory Link: https://www.wow-mania.com/armory/?quest=12019
YT video of Thassarian sitting with new friend Leryssa: https://youtu.be/kCAEYXVbEtg

**What is Happening:**
A friend and I entered into the instance, Thassarian is still sitting during the quest and this time he has a friend Leryssa.
On a side note, my recordings to record the dialogues but they are all off  in timing. 

**What Should happen:**
Leryssa should not be where she is; she should be in the middle of the arena, Thassarian should also not be sitting.

**Comment by Rushor** [comment]
will fix this together with the other issue related to it :)

**Comment by jeyrella** [comment]
#5557

**Comment by Abateman121** [comment]
Was this issue fixed because I am having a very similar issue where thassarian walks forwards and just stands there.  Leryssa and Valanar never show up so the fight never starts.  I can also post a video of this behavior if it helps.
