### ISSUE TITLE
Weapon Visual Bug.

### ISSUE THREAD

**Issue by Iazzy** [WoWManiaUK/Redemption#5563]
**Links:**
![WoWScrnShot_070521_231036](https://user-images.githubusercontent.com/86995784/124536588-3b2db580-dde6-11eb-8188-cd314fad26a1.jpg)
![WoWScrnShot_070521_231000](https://user-images.githubusercontent.com/86995784/124536633-4a146800-dde6-11eb-9c77-602419336da2.jpg)
![WoWScrnShot_070521_231036](https://user-images.githubusercontent.com/86995784/124536636-4aacfe80-dde6-11eb-89f4-f3b9bf198a09.jpg)
![WoWScrnShot_070521_231103](https://user-images.githubusercontent.com/86995784/124536638-4b459500-dde6-11eb-87cd-ca14244f069f.jpg)

**What is Happening:**
The weapon  [Monster - Frostmourne (Arthas Only Special)] for 1 xmog token has a visual appearance bug where it only appears when in combat. 

**What Should happen:**
I would like for the xmog to appear like any other weapon. I don't know if this a easy fix or not but it's just this weapon that seems to have the appearance bug. It's been like this for a few months now since I got it. I would like for it to be fixed and to always show. Getting a little tired of seeing my character without the sword mog and only 
![WoWScrnShot_070521_231000](https://user-images.githubusercontent.com/86995784/124536530-26512200-dde6-11eb-9c3e-983af5749992.jpg)
showing once I enter combat.

**Comment by wow-mania** [comment]
Unfortunately, this one can't be fixed.
