### ISSUE TITLE
[Mount / item] Lucid Nightmare -ItemID 150530

### ISSUE THREAD

**Issue by WhitephoenixTheBunny** [WoWManiaUK/Redemption#5564]
The mount [Lucid Nightmare](https://www.wow-mania.com/armory/?item=150530) is black - orange, the one in _retail_ is black - purple.

This mount as been reported several times, but there's a simple fix, as the mount we have in mania is an unused appearance that has never been available on a player mount as we can see on the site [warcraftmount](https://www.warcraftmounts.com/mount.php?mountid=817). 

We just need adjust the item name and spell name 

[Item - Lucid Nightmare](https://www.wow-mania.com/armory/?item=150530) be changed to **Black-Orange Dreamrunner**
[Spell - Lucid Nightmare](https://www.wow-mania.com/armory/?spell=150262) be changed to **Black-Orange Dreamrunner**

And one day, bring the real Lucid Nightmare :D

Lucid Nightmare at mania
![image](https://user-images.githubusercontent.com/31921098/124750532-7b438400-df1d-11eb-988f-33fa5f1770ef.png)

Lucid Nightmare at retail (acording warcraftmount)
![image](https://user-images.githubusercontent.com/31921098/124750565-87c7dc80-df1d-11eb-890f-4115bbe33430.png)

Black-Orange Dreamrunner acording warcraftmount
![image](https://user-images.githubusercontent.com/31921098/124750704-b2199a00-df1d-11eb-8f99-e97bd2e224a1.png)

**Comment by wow-mania** [comment]
You mean change the name on item and spell only?

**Comment by wow-mania** [comment]
This will need a client update. Probably next week.

**Comment by WhitephoenixTheBunny** [comment]
> You mean change the name on item and spell only?

Yes, just change the names @wow-mania

**Comment by GMZinius** [comment]
Update information checked today 

- Look item is correct 
![image](https://github.com/user-attachments/assets/c647172f-de38-4347-932c-66c8bacbe961)

- When learnt the mount is shown in mount tab Lucid Nightmare 
![image](https://github.com/user-attachments/assets/d2c0c435-1b3d-44b6-a7be-cfdd98351788)
