### ISSUE TITLE
[Item] Windchanneller's Miter - visual issue

### ISSUE THREAD

**Issue by WhitephoenixTheBunny** [WoWManiaUK/Redemption#5565]
**Links**

[Windchanneller's Miter in Mania](https://www.wow-mania.com/armory/?item=31552)
 [Windchanneller's Miter acording WowHead](https://www.wowhead.com/item=31552)

**What is Happening:**

On the using (and transmog) it will show the hair

**What Should happen:**

Acording wowhead, it shouldn't show hair (use or transmog) same as [Whitemane's Chapeau (Mania)](https://www.wow-mania.com/armory/?item=7720) / [Whitemane's Chapeau (wowhead)](https://www.wowhead.com/item=7720/whitemanes-chapeau)

**Comment by wow-mania** [comment]
![image](https://user-images.githubusercontent.com/12248683/124941210-8f14e600-e002-11eb-940f-5b89955d682a.png)

It does show the hair.
The only issue is that sometimes the hair shows through the hat.

https://cdn.discordapp.com/attachments/677889159846690816/862624292298817546/unknown.png

So we may leave it as-is.
