### ISSUE TITLE
[Quest] We Have the Power

### ISSUE THREAD

**Issue by stealer0517** [WoWManiaUK/Redemption#5568]
https://www.wowhead.com/quest=12197/we-have-the-power
https://www.wowhead.com/npc=26410/rune-smith-kathorn

Once you kill Rune-Smith Kathorn there should be a 100% drop rate of Kathorn's Power Cell assuming you're on the quest.
I've killed him 3 times now and it has not dropped.

Durar's Power Cell is fine and dropped immediately. It's just Kathorn's that won't drop for me.

**Comment by Rushor** [comment]
true that is one of the cases of wrong wowhead data mining

fixed and increased to 100 percent

**Comment by jeyrella** [comment]
@Rushor Did you increase Durar's too?  https://wow-mania.com/armory/?item=36857
It might have dropped immediately for the OP, but that was probably just luck as it shows 65% rate.  Should be 100% also (when on the quest, natch).
