### ISSUE TITLE
[Quest] Dun-da-Dun-tah!  Harrison Jones does not start moving when cage is opened

### ISSUE THREAD

**Issue by stealer0517** [WoWManiaUK/Redemption#5569]
https://www.wowhead.com/quest=12082/dun-da-dun-tah

After you accept the quest Harrison Jones kicks open his cage but doesn't start moving.
I've been standing here long enough for his cage to respawn, and I tried abandoning and re accepting the quest but that didn't work.

He should kick open his cage and immediately walk out before doing the rest of the escort quest.
(see one of the videos on wow head)

**Comment by wow-mania** [comment]
Pretty sure this was working. PLease confirm before attempting any fixes.

**Comment by Rushor** [comment]
no regression since that issue exists some time now, but could never reproduce it

**Comment by jeyrella** [comment]
This one appears to have recurring issues  #5459 #5252 #5218 #2470 #1697 so not too surprised if it's broken again
Let's see if we can fix it once and for all

**Comment by stealer0517** [comment]
I just went back in the normal server and tried again and It's still not working.
This time he didn't even open the cage or do his little saying.

**Comment by svijetlo** [comment]
this quest brakes every few months we need to find some more perma solution for it

**Comment by Rushor** [comment]
try now, i added that the script should reset upon respawn of him

**Comment by Moriane** [comment]
Harrison escorted my horde rogue to safety, everything worked fine. 

Respawn, tried it on a ally mage, and he did his saying, but did not open the cage.

Tried again on a horde hunter, and he didn't do his saying at all upon accepting the quest. 
![WoWScrnShot_072321_205837](https://user-images.githubusercontent.com/86922193/126773221-e88a9056-3476-4225-b63b-d6ac35a88202.jpg)

**Comment by stealer0517** [comment]
Has this fix been rolled out to the regular server? 
I'm still not able to get Harrison Jones to leave his cage.

**Comment by Xangretor** [comment]
This one is still not working. I accepted the quest and Harrison Jones just stands in his cage, doing nothing.

**Comment by jeyrella** [comment]
Many comments on Red that still not working.

**Comment by Rushor** [comment]
must be a general issue with waypoint or escort handling in SAI core, atm i cannot debug it

**Comment by Greywolf59** [comment]
Still doesn't work, looks like it works once after restart. When someone finishes it, gotta wait for restart that will rset some script i nit so it can work again (once). At least that is what I think it is, had similar issue on naxx realm with two other things, one quest event and one NPC respawn.

**Comment by mfranca0009** [comment]
Awaiting confirmation of fix.

**Note**: Due to outdated motion master/waypoint movement, `Harrison Jones` odd run/walk behavior will not be fixed right now; it will be corrected with the motion master/waypoint movement corrections later.

**Comment by Echinaceax** [comment]
Confirmed ALL fixed from checklist above 

Nice to see this finally fixed fully, even the correct spawn and de-spawning of Drakarri Ancient King NPCs when snake dies.

https://gyazo.com/66a698a32a8313ca5143ffa44795629a
