### ISSUE TITLE
[Item/Mount] Reindeer's Reins

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#5572]
**Links:** https://www.wow-mania.com/armory/?item=21044
https://www.wow-mania.com/armory/?spell=25858

**What is Happening:** [Reindeer's Reins](https://www.wow-mania.com/armory/?spell=25858
) is an item that is not obtainable by normal means, but has been awarded before in events as it is a pretty festive mount that looks quite inoffensive at first glance. 

However, this item allows you to mount a 60% speed mount with no cast time. Obviously this can be very powerful and is currently being abused in Wintergrasp (could also be done in battlegrounds). Any spell that takes you out of combat such as Feign Death, Vanish or whatever, allow for an instant mount-up seemingly mid-combat. Otherwise a fleeing opponent can mount this festive partner instantly as soon as they exit combat, giving them an advantage over whoever might be chasing them.

**What Should happen:** This item should either not be available to regular players, or should be changed to require the standard 1.5s cast in order to mount up.

**Comment by jeyrella** [comment]
![image](https://user-images.githubusercontent.com/46089380/125975824-c07af7e7-5bfd-4fc7-8d39-fd45660069d8.png)
3rd option: make it non-usable in PVP areas.

**Comment by svijetlo** [comment]
jusr make this mount no usable in battle grounds imo

**Comment by Keader** [comment]
Fixed
