### ISSUE TITLE
Npc Ymirjar Huntress missing pet

### ISSUE THREAD

**Issue by Keader** [WoWManiaUK/Redemption#5573]
**Links:**

https://www.wow-mania.com/armory/?npc=37134

**What is Happening:**

Npc is missing pet in all difficulties

**What Should happen:**

Npc should summon a falcon pet on spawn (now it's only spawned in 25 man and after 5 secs)
https://www.wow-mania.com/armory/?npc=38154

**Comment by Oganku** [comment]
Shameless plug to issues #3456 up to #3460 (5 total) regarding missing abilities on trash for that wing. Including these particular hawks.

**Comment by Keader** [comment]
hmm, i will check tomorrow if hawks has some spell and if it is missing

**Comment by Oganku** [comment]
The hawks themselves don't, but the Deathbringers and Frostbinders are missing key abilities. :(
