### ISSUE TITLE
[Hunter] Wrong Delay cast time

### ISSUE THREAD

**Issue by Keader** [WoWManiaUK/Redemption#5575]
**Links:**

![image](https://user-images.githubusercontent.com/7120913/126069179-df59ff02-e8bb-4cc7-8f39-3f75e5534e09.png)

**What is Happening:**

TC since always add 0.5 sec into Ranged Attacks. It's correct, Blizzard do it too.
Problem is: Right now, it's a constant value. Any ranged casted attack is added 0.5 sec of cast.

**What Should happen:**

It's wrong, 0.5 sec need be affected by hast.
So Hast bonus (by talents, equips, spells) must reduce this 0.5 sec cast delay too
It fixes discrepancies between how fast our hunters cast, of blizzard hunter videos

**Comment by Keader** [comment]
waiting server back to build it xd

**Comment by hawker357** [comment]
With a grand total of 1242 Haste I managed to get Autoshot and Steady Shot down to 0.4 seconds
![Screenshot (124)](https://user-images.githubusercontent.com/79724094/126482377-9da9745e-1549-466c-95db-1c40ce7bd982.png)

**Comment by hawker357** [comment]
Hunter on Live with 60 Haste total
![Screenshot (125)](https://user-images.githubusercontent.com/79724094/126484300-7c94dcfa-1f7e-4f33-a2b4-f0177a2785a2.png)

Hunter on PTR with 60 Haste total
![Screenshot (126)](https://user-images.githubusercontent.com/79724094/126484341-22ccda8b-ade4-46df-91aa-e4c4f7f89980.png)
