### ISSUE TITLE
[quest] Skywing - Movement Start upon quest accept #10898

### ISSUE THREAD

**Issue by gorgar19** [WoWManiaUK/Redemption#5576]
**Links:**
https://www.wowhead.com/quest=10898/skywing

**What is Happening:**

the quest can be completed once then the quest npc will be bugged once it returns to the starting position..
after you complete it once when skywing respawns the npc will not move from the starting position but if you pull a mob to his location he will agro on it then afterword's fly towards the final mob your supposed to kill and then  despawn .

I ran through this quest on several toon on the same account and the easy fix for me was to do the quest then for then next character  when he respawned pull mobs to him and let him die and then his next respawn the quest can b completed as normal.

**What Should happen:**

I'm guessing its not doing a full reset. you should be able to finish the quest then swap over to a new toon and wait for hi to return to do it again

**Comment by Rushor** [comment]
can this be reproduced that way on ptr?

**Comment by hawker357** [comment]
Can reproduce 2 ways:
First is as described above, fully complete the quest, handing it in at Shattrath.

Second method is only using one char, follow quest as normal until the Escort Skywing objective is completed, then abandon quest and go back to Skywing's spawn.

Both methods result in the same behaviour, Skywing will not move after the quest is accepted until he enters combat.

**Comment by Rushor** [comment]
crature will reset it script now upon respawn. pls test it the same way you posted above to see if the change i made actually fixed the issue.

**Comment by hawker357** [comment]
Still no movement after quest acception. This test was just abandoning the quest after the objective completed and re-taking it.
![Screenshot (127)](https://user-images.githubusercontent.com/79724094/126778731-4159d278-bae0-4e9d-9a52-ecf99599abcd.png)
![Screenshot (128)](https://user-images.githubusercontent.com/79724094/126778736-ccbe5dc9-0f82-4531-9159-400fb282dc84.png)

**Comment by Rushor** [comment]
unable to fix this atm - will reopen once solution i found

**Comment by GMZinius** [comment]
Reopening this now

**Comment by Rushor** [comment]
Fix suggestion from internal chat applied :)

**Comment by GMZinius** [comment]
> Fix suggestion from internal chat applied :)

- Movement (fixed)
- Quest completion bugged now

**Comment by Rushor** [comment]
Next try :)

Fix is applied in DB, pls let jani know to restart the ptr :)
