### ISSUE TITLE
Rogue Visual

### ISSUE THREAD

**Issue by womptista** [WoWManiaUK/Redemption#5577]
**Links:**
wow-mania rogue link: https://www.wow-mania.com/armory/?class=4
wow-mania hearthstone link: https://www.wow-mania.com/armory/?item=6948
wow-mania mall stone link: https://www.wow-mania.com/armory/?item=90044
I was unable to find a link that will put all the teleporters into one
Link to visual: https://puu.sh/HXhGE/4ed93ea2a7.jpg

**What is Happening:**
When leaving a dungeon, respawning after death, using the mall stone, using the hearthstone, and using a flight path will sometimes cause the visual of the rogue to lose their off hand weapon, and when entering battle with the visual it appears as iff the player is punching the mob but doing the same damage as the weapon. 

**What Should happen:**
The weapons should not be lost in visual.

**Comment by Oganku** [comment]
Happens with any character that's dual-wielding, not only rogues. You can fix it by re-equipping or toggling weapon off and back on.

**Comment by fvicaria** [comment]
This is a client issue. Meaning it comes from the time of retail.
It cannot be fixed, unfortunately. Luckily there is a known work-around :P
