### ISSUE TITLE
Level 20 Paladin Class Quest

### ISSUE THREAD

**Issue by WedgeVIII** [WoWManiaUK/Redemption#5578]
**Links:**

**What is Happening:**
I failed the level 20 Paladin class quest. The npc I'm supposed to protect doesn't allow me to try again. Tried dropping the quest but still cannot pick it back up.

**What Should happen:**

**Comment by svijetlo** [comment]
can you please post the name of quest and were you doing it on alliance or horde , thx in advance

**Comment by fvicaria** [comment]
Insufficient info.

**Comment by jeyrella** [comment]
@WedgeVIII can I suggest you reach out to a GM in-game first for assistance.  We'll need more detailed info than this.

**Comment by Rushor** [comment]
useually this works, at least fo the last years - nothing has changed there
