### ISSUE TITLE
Unable to remove transmog on bow

### ISSUE THREAD

**Issue by Brahanley** [WoWManiaUK/Redemption#5579]
**Links:**

**What is Happening:** I am removing the transmog but everytime i relog the transmog is back on the weapon, i got told by Brones to do a report here so a dev can check out the issue

**What Should happen:** What should happen is that i should see the original look of the weapon instead of seeing the transmog everytime i relog after been removing the transmog

**Comment by WhitephoenixTheBunny** [comment]
I think it's related to https://github.com/WoWManiaUK/Redemption/issues/3362
