### ISSUE TITLE
not gaining xp

### ISSUE THREAD

**Issue by RattleSnake84** [WoWManiaUK/Redemption#5580]
**Links:**

**when hunting monsters we do not get any xp anymore  only for quests:**

**when killing a monster we should gain xp:**

**Comment by svijetlo** [comment]
what lvl are you and where do you kill "monsters"

**Comment by WhitephoenixTheBunny** [comment]
If you are on a low map you don't get xp from killing mobs...

If NPC show 

Grey = no xp
Green = low xp
Yellow = normal xp
Orange = higer xp
Red = better run
skull= run for your life
