### ISSUE TITLE
Trash in most wotlk-dungeons dont drop items

### ISSUE THREAD

**Issue by Omnivore85** [WoWManiaUK/Redemption#5582]
All dungeons in WOTLK (exept Nexus it seems) got rares unique for that dungeon and some got lower lvl rares for normal and higher for heroic, however many of the dungeons dont have any drops at all. Its hard to remember all dungeons with these issues but Utgarde Pinnacle, Azjol Nerub, Occulus, Halls of Lightning doesnt drop any items at all, no greens no worlddrop rares or dungeon specific rares. 
Having items added will make the dungeons more alive and interesting.

PS: Also I have seen that lvl 200 epics like https://www.wowhead.com/item=37835/jetzes-bell?bonus=6660 doesnt drop at all in game or Zom's crackling bulwark.

**Links:**
https://www.wowhead.com/item=35665/soothing-lichen-wraps?bonus=6710 example of trashdrop from Azjol Nerub
https://www.wowhead.com/item=127502/ymirjar-physicians-robe?bonus=6652 trashdrop from Utgarde Pinnacle
https://www.wowhead.com/item=37197/tattered-castle-drape?bonus=6710 Trashdrop from Utgarde Keep heroic

**What is Happening:** 
Trash doesnt have loottables at all in some WTOLK dungeons or incomplete loottables

**What Should happen:**
Trash should drop items, both worlddrops and specific zonedrops depending on the dungeon and sometimes difficulty.

**Comment by jeyrella** [comment]
Hmm, this may take quite some time, it seems every single NPC in every dungeon will need inspecting individually, there appears to be no common "quick fix".

The level 200 epics *do* drop, they are just extremely rare - as rare as they were in retail, in fact :-)

**Comment by Omnivore85** [comment]
Ouch that doesnt sound fun..
Hmm the rarity must be insane then since ive been here for 3 years with around 200 days /played on a ton of chars and ive never seen the trinket drop in dungeons or in world or on anyone i've inspected^^

**Comment by jeyrella** [comment]
It is.  They were fairly special on retail, and that had a _much_ larger population.
That being said though, it may make sense to tweak it a little, I will discuss it with powers that be (in no way is this a promise or commitment to a change)

I will close this for now as the work is too big for a single ticket, it is however noted and we'll look at dungeon loot improvements on a gradual basis.  Thanks for bringing to attention :)
