### ISSUE TITLE
[Spell] Frost Ward: Absorbs not Scaling with ICC Buff

### ISSUE THREAD

**Issue by Lantanio** [WoWManiaUK/Redemption#5583]
**What is Happening:**
Frost Ward absorbs the same damage in and outside of ICC (holding spellpower constant). See screnshots below.

4687 damage absorbed inside ICC (Servant of the Throne)
![Frost Ward ICC](https://user-images.githubusercontent.com/85909876/126866285-3ec9c5d9-fcf7-4627-a7eb-362e12e9923c.PNG)

Same amount absorbed during a duel
![Frost Ward Outside](https://user-images.githubusercontent.com/85909876/126866286-e7b203a6-f1ed-4d5e-8a86-6e82f01042ed.PNG)

**What Should happen:**
Strength of Wrynn (tested in this example) / Hellscream's Warsong (not tested) should boost all absorbs by 30%, resulting in roughly 6093 damage absorbed inside ICC (again, at the spellpower level tested). 

Other Warding spells (Fire/Shadow) likely suffer from the same issue.

**Comment by Keader** [comment]
try now pls
