### ISSUE TITLE
[OBJECT] Arthas' Tear floating in air?! Western Plaguelands 45.5 67.6

### ISSUE THREAD

**Issue by Bulb1** [WoWManiaUK/Redemption#5585]
Links:
https://wow-mania.com/armory/?item=8836
What is Happening:
![image](https://user-images.githubusercontent.com/66064613/126945358-e2b06192-31f9-48f1-aeba-aeb64549fe11.png)
What Should happen:
:)

**Comment by hawker357** [comment]
Confirmed, had to spawn it in, IDs and Coords in the screenshot below
![Screenshot (129)](https://user-images.githubusercontent.com/79724094/126981009-235df561-57d6-4979-ac86-fbcaa1f0ecd8.png)

**Comment by Rushor** [comment]
fixed, now close to the tree on the floor
