### ISSUE TITLE
Bugged quest

### ISSUE THREAD

**Issue by Spenkozaur** [WoWManiaUK/Redemption#5586]
Mutiny on the Mercy quest

Barrels can't be clicked

Barrels should be clickable

**Comment by hawker357** [comment]
https://www.wowhead.com/quest=11527/mutiny-on-the-mercy
https://www.wowhead.com/item=34387/barrel-of-blasting-powder#dropped-by

The quest item is dropped by the mobs on the ship, not the barrels on the ship.
