### ISSUE TITLE
Warrior un unable to use titan grip

### ISSUE THREAD

**Issue by Consmith46** [WoWManiaUK/Redemption#5587]
My Dwarf Warrior, Holbert, is unable to learn Titan Grip. I have reset my talents multiple times. Everything I click on Titan Grip from the Talent Tree it does not get places in my spell book. I have issued a ticket go a GM and there were unable to assist.

**Comment by svijetlo** [comment]
what lvl are you ?
did you try to equip 2x 2h weapons' , keep in mind it only works on 2h axe , sword and or mace 
also Titan Trip ones Talented will not show in your spell book 
![WoWScrnShot_072821_152302](https://user-images.githubusercontent.com/61908373/127329740-c090163e-39d8-45f0-8f99-1fa3171d50ed.jpg)

**Comment by Consmith46** [comment]
I feel dumb... it's fixed!

Thank you!!
