### ISSUE TITLE
[NPC] Spiteful Apparition - ID 36551

### ISSUE THREAD

**Issue by WhitephoenixTheBunny** [WoWManiaUK/Redemption#5588]
In the Forge of Soul (normal and heroic) when walking by the "skulls" nothing happens, but it should tiger [Spiteful Apparition](https://www.wow-mania.com/armory/?npc=36551), and those should attack players.

Information in [wowwiki](https://wowwiki-archive.fandom.com/wiki/Spiteful_Apparition):
added in patch: 3.3.0

definition: Spiteful Apparition can be found in the Forge of Souls of the Frozen Halls in Icecrown, they appear out of thin air and attack a random party member, then disappear. It is very difficult to kill them before they use their attack and despawn.

Abilities: [Spite]ω ϖ 15 yd range—Deals [4500 to 5500](https://www.wow-mania.com/armory/?spell=68895) Shadow damage to enemies within 15 yards. 3 sec cast. [7200-8800](https://www.wow-mania.com/armory/?spell=70212) on Heroic.

The skull - with gm mode off:
![image](https://user-images.githubusercontent.com/31921098/127457256-25603d54-8e0e-4899-aa66-7edd6082b1fe.png)

The appartion - with gm mode on:
![image](https://user-images.githubusercontent.com/31921098/127457396-84354c0e-2597-4b8a-8d6b-0aeb0b85dfa4.png)

**Comment by jeyrella** [comment]
Oooh.  Nice find!

**Comment by Rushor** [comment]
fixed, when you mobe closer they appear attack and despawn after cast
