### ISSUE TITLE
[NPC / BOSS] The Black Knight - ID 35451

### ISSUE THREAD

**Issue by WhitephoenixTheBunny** [WoWManiaUK/Redemption#5589]
At the Trial of Champion heroic mode, last boss, [The Black Knight](https://www.wow-mania.com/armory/?npc=35451) have a missing ability effect on the first phase:

[Death's Respite](https://www.wow-mania.com/armory/?search=Death%27s+Respite)  ω ϖ (Heroic modeω ϖ) 50 yd range—Death's Respite stuns the target for 2 seconds, inflicts 8,288 to 8,712 (Heroic: 13,163 to 13,837) Shadow damage and knocks the target back. 1.81 sec cast [(wowwiki information)](https://wowwiki-archive.fandom.com/wiki/The_Black_Knight_(tactics))

At moment we see the boss cast the spell, it shows on quest log, but players aren't stunned and knocked back, and as the description above says, this should happen on heroic mode.

Also, on phase 2, he will summon an Army of the Dead (not sure with one is used if [67761](https://www.wow-mania.com/armory/?spell=67761) or [67874](https://www.wow-mania.com/armory/?spell=67874).

According with [wowwiki fight description ](https://wowwiki-archive.fandom.com/wiki/Trial_of_the_Champion), in phase 2 **all** the remaining ghouls should explode (this is the boss is killed before the ghouls)

> You can kill either the Black Knight or the Army first, but if you kill him first, all the remaining ghouls will explode after a short time all together, so it's advisable to AoE them down, especially if you're going for the achievement.

Still according According with [wowwiki fight description ](https://wowwiki-archive.fandom.com/wiki/Trial_of_the_Champion), the transition between phase 2 and phase 3 should happen after boss and ghouls been dealt with, but at the moment, the phase 3 will start after the boss is dead and ghouls are remaning.

> Once the Army of the Dead is dealt with and the Black Knight is dead once again, you're on to phase 3.

**Comment by Rushor** [comment]
Death's Respite knockback added, explode of all ghouls in phase switch added
