### ISSUE TITLE
[NPC/Spell] Dawnblade Marksman (Flaming Arrow)

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#5590]
**Links:** https://www.wow-mania.com/armory/?npc=24979
https://www.wow-mania.com/armory/?spell=45101

**What is Happening:** [Dawnblade Marksmen](https://www.wow-mania.com/armory/?npc=24979) will use their [Flaming Arrow](https://www.wow-mania.com/armory/?spell=45101) targetting players if they are moving anywhere within 35 yards of them, without actually engaging in combat. Moreover, these arrows are only visual and deal 0 damage.

https://imgur.com/a/A0GXfMH

**What Should happen:** These guys shouldn't attack players for 0 damage for no reason.

**Comment by jeyrella** [comment]
Not on the suspected incorrect SAI list (although sounds like they should be)

**Comment by Rushor** [comment]
onlx targets Shattered Sun Marksman now
