### ISSUE TITLE
[Spell/Death Knight] - Anti - Magic Zone unaffected by Attack Power

### ISSUE THREAD

**Issue by festerhowl** [WoWManiaUK/Redemption#5591]
**Links:** https://wotlkdb.com/?spell=51052#:~:text=Places%20a%20large%2C%20stationary%20Anti,%2B2*%20AP%20spell%20damage.

**What is Happening:** AMZ is not factoring in the buff from AP and only mitigating 10000 spell damage. 

 My AMZ tooltip: 
![Screenshot (267)](https://user-images.githubusercontent.com/43633844/128033485-bda73b86-cc7d-4b69-b413-348107557d41.png)
**Note that the spell should absorb 21802 spell damage for me, but currently it breaks after taking 10000 spell damage.**

 Base Spell Tooltip: Places a large, stationary Anti-Magic Zone that reduces spell damage done to party or raid members inside it by 75%. The Anti-Magic Zone lasts for 10 sec or until it absorbs 10000+2*AP spell damage.

**Comment by Keader** [comment]
idk who you are, but good reports !

**Comment by svijetlo** [comment]
![WoWScrnShot_080521_093924](https://user-images.githubusercontent.com/61908373/128311131-a472c88e-cb36-403d-8396-c6399b79007c.jpg)
