### ISSUE TITLE
[Talent/Death Knight] - Unholy Blight is not stacking

### ISSUE THREAD

**Issue by festerhowl** [WoWManiaUK/Redemption#5592]
**Links:**
Unholy Blight- https://wotlk-twinhead.twinstar.cz/?spell=50536

**What is Happening:**
Unholy Blight is not stacking on the target. Every successive application of Unholy Blight resets the damage of its previous application.

**What Should happen:**

https://wowwiki-archive.fandom.com/wiki/Unholy_Blight

Unholy Blight should work the same way as Mage - Ignite / Warrior - Deep wounds spells. The damage done by the de-buff should keep adding up with each cast of Death Coil and only reset if the de-buff runs out.

**Comment by svijetlo** [comment]
![image](https://user-images.githubusercontent.com/61908373/128060388-6a04c90a-d3d1-4ada-b186-36b9aabd60b5.png)
pls in future do not post link form other server as evidence =)

**Comment by Keader** [comment]
This is working correctly.
Damage Amount = [(Death Coil Damage * 0.10) / MaxTicks] + RemainingPeriodicAmount of old application
This case is correct, but since it's only 10% of death coil, is hard do see difference sometimes.

**Comment by svijetlo** [comment]
actually you are right i i checked it last night in detail deference is there but it is small that you sometimes in heat of fight do not even see it
