### ISSUE TITLE
Servers Offline

### ISSUE THREAD

**Issue by emahiser** [WoWManiaUK/Redemption#5593]
ALL Servers are Offline.  Deleted my Cache Folder and Realms List is set to Set Realmlist wotlk.wow-mania.com
![WoW-Mainia Servers Offline](https://user-images.githubusercontent.com/5267741/128165432-ccc3390e-2783-4d5e-9efd-b212c433cdc4.png)

**Comment by jeyrella** [comment]
Not a server issue. You need the latest launcher:  https://mega.nz/file/Z6wk0BYR#t-eOS9E7Xk8KdN_plqOJj8PyuIj_xnpHXUPVI0ROSww

Same link is available at https://wow-mania.com/downloads  (click "Launcher").  You need to run this Launcher in Admin mode, in order for it to update your game files.

You can also join the server's Discord channel for interactive help from the community:
https://discord.com/invite/7R4GAxUd?utm_source=Discord%20Widget&utm_medium=Connect

**Comment by emahiser** [comment]
> Not a server issue. You need the latest launcher: https://mega.nz/file/Z6wk0BYR#t-eOS9E7Xk8KdN_plqOJj8PyuIj_xnpHXUPVI0ROSww
> 
> Same link is available at https://wow-mania.com/downloads (click "Launcher"). You need to run this Launcher in Admin mode, in the same folder as your game files, in order for it to update your game files.
> 
> You can also join the server's Discord channel for interactive help from the community:
> https://discord.com/invite/7R4GAxUd?utm_source=Discord%20Widget&utm_medium=Connect

You dont need any Launcher!  Dont matter anyways, Went back to MY Server Arctic-WoW anyways.

**Comment by jeyrella** [comment]
To play on Wow-Mania, yes, it is required so that we can verify the connection configuration files, as an additional anti-cheat layer.  That's why you see server as offline, as your connection to the server is not verified.
Anyway, you're missing out on the best-scripted server out there.  Your loss :)  Good luck, hope to see you back some time!

**Comment by emahiser** [comment]
> To play on Wow-Mania, yes, it is required so that we can verify the connection configuration files, as an additional anti-cheat layer. That's why you see server as offline, as your connection to the server is not verified.
> Anyway, you're missing out on the best-scripted server out there. Your loss :) Good luck, hope to see you back some time!

No, sorry, there is NO need for anyone to peak into my system!!!  WoW-Mania is not the BEST out there.  Anywho, I am DONE!
