### ISSUE TITLE
[NPC] Mageslayer 57.5 86.5 keeps falling under ground

### ISSUE THREAD

**Issue by Bulb1** [WoWManiaUK/Redemption#5595]
Links:
https://wow-mania.com/armory/?npc=18866
What is Happening:
![image](https://user-images.githubusercontent.com/66064613/128349234-010f9c1b-2496-4007-b09e-40be8dd45650.png)
![WHAT](https://user-images.githubusercontent.com/66064613/128349673-9b669075-9fcc-4395-9483-87fb7358ac80.png)
What Should happen:
change his path I guess

**Comment by Bulb1** [comment]
![image](https://user-images.githubusercontent.com/66064613/128350177-3de4cda8-f002-408b-9a66-b0e9fba51589.png)
there's also 2nd npc that keeps falling down but when I came closer to this spot it crawled out from ground

**Comment by Rushor** [comment]
fixed
