### ISSUE TITLE
Graphic Bug of Vicious White Warsaber Mount

### ISSUE THREAD

**Issue by Earendir** [WoWManiaUK/Redemption#5596]
**Links:**
https://www.wow-mania.com/armory/?item=158151

**What is Happening:**
When riding the Vicious White Warsaber mount it comes with some graphic bugs when compared to the original one:
1) On its front part the tiger has two faces, a big (normal) one with its own pair of eyes (white) and a smaller tiger face right on top of this one (abnormal) with blue eyes and low poly graphics;
2) Its front paws and mouth (when opened) are clearly low poly compared to the original one, with the first missing the black and white striped pattern and the second being just a mixed stain of colours.

**What Should happen:**
When looking for any picture of the original mount it looks clear what is missing and what is wrong about the graphics of this mount.
Thank you for your support.
![Screenshot (6)](https://user-images.githubusercontent.com/88531497/128475442-a34ca260-4cf5-4f41-a82c-d8a9df2b8ea2.png)
![Screenshot (5)](https://user-images.githubusercontent.com/88531497/128475473-89f0d0f1-6579-48a4-a795-21275b6d9746.png)
![Screenshot (7)](https://user-images.githubusercontent.com/88531497/128475490-1a4149e9-2e7b-47f4-8939-02443c1ac72a.png)

**Comment by fvicaria** [comment]
As is. Unfortunately, some imports are not perfect for an older client.
We won't be doing anything other than potentially removing the mount if it gets too in the way.

**Comment by Earendir** [comment]
Can I at least receive the 15 coins refund I used to buy this mount?

**Comment by Earendir** [comment]
> As is. Unfortunately, some imports are not perfect for an older client.
> We won't be doing anything other than potentially removing the mount if it gets too in the way.
Can I at least receive the 15 coins refund I used to buy this mount?
