### ISSUE TITLE
Can't complete quest

### ISSUE THREAD

**Issue by Thinyshor** [WoWManiaUK/Redemption#5597]
**Links:**
https://www.wowhead.com/quest=13295/basic-chemistry

**What is Happening:**
I used the recieved item many times, the message that the cauldron begins to boil or that it summons ads appears, i killed them all, many times, but the quest never completes. I tried on both cauldrons at least 10 times each with a cd of 2 minutes from the item quest 

**What Should happen:**
I guess it should complete after i kill the mobs, or the cauldron should do something more then just boil... maybe explode. I see no comments on wowhead to be more specific about how it should complete

**Comment by Oganku** [comment]
The chance to complete the quest when you use the item is fairly low, if it fails you get the adds and you gotta try again. The current success rate might be too low though, but needs to be confirmed first.

**Comment by Rushor** [comment]
you better do the quest with 2 people
