### ISSUE TITLE
Freeing slaves in Pit of Saron

### ISSUE THREAD

**Issue by Omnivore85** [WoWManiaUK/Redemption#5598]
**Links:**https://www.wowhead.com/quest=24498/the-path-to-the-citadel

**What is Happening:**When someone frees a slave, the others in the group dont get credit for it.

**What Should happen:**Everyone should get credit when someone is freeing a slave. Freeing 30-45-60-75 slaves is a pain in the ass if the whole group needs them and sometimes requires 2-4 runs

**Comment by jeyrella** [comment]
Please can you state the source where you read that everyone should get credit.  I am having trouble locating any evidence that this should be the case.  Thanks!

**Comment by Omnivore85** [comment]
Hmm I cant find info about it but I remember it being so from Retail. Its kinda logical too dont you think:)

**Comment by jeyrella** [comment]
Logical or not, there are plenty of examples where group/instance quests don't share credit.  We also have people remembering the opposite to you :)
If we can find verifiable accurate information about this, we'll certainly change it, up until then it will be status quo.  Hasn't caused too much of a huge problem so far for the past 5 years...  ;-)

**Comment by Omnivore85** [comment]
Ok:)

**Comment by Rushor** [comment]
if you can find a video about that would be great. i remember several escort quests beeing modified to reward credits group wise, but this one is special

**Comment by WhitephoenixTheBunny** [comment]
I have been doing several research and I haven't found any proof that the quest progression is shared, and reading wowhead comments (from patch 3.3.0) we can see it's quest hard to do... There's also this @jeyrella, a diferente thing that caught my atention
![image](https://user-images.githubusercontent.com/31921098/128838842-7e48672a-f288-497d-b84e-4e0a8dd45a8b.png)
I don't know how true this is as a few comment under we can see this: 
![image](https://user-images.githubusercontent.com/31921098/128838950-f44612aa-4b07-448d-a803-47e489ec93d4.png)
Maybe a hotfix on retail?

**Comment by Echinaceax** [comment]
Same for me @WhitephoenixTheBunny ive been searching info on this without any proof that it should be shared progress.
Its ofc shitty that everyone on the quest have to compete with eachother to free their slaves, but when i did them i just mentioned to the group that i need the quest for the slaves and they generally said ok.

even with PUGs as long as the players know that there are players needing the quest, they are usually ok to let the ppl gather what they need before killing Boss coz they know the player cant progess to next quest without it 

No video showed more than 1 player on the quest so cant find proof (either way) unfortunately
