### ISSUE TITLE
[Quest] Klaven's Tower

### ISSUE THREAD

**Issue by stealer0517** [WoWManiaUK/Redemption#5599]
https://classic.wowhead.com/quest=2359/klavens-tower
https://classic.wowhead.com/item=7923/defias-tower-key

There are 2 issues, 1 minor 1 more major. 
1. I cannot loot the Defias Tower Key from killing the Malformed Defias Drone.
According to wowhead there should be a 100% drop rate either killing the drone and looting their body, or you can pick pocket the item.
After killing the guy about 10 times I wasn't able to loot the item. 
I went ahead and did the other part of the quest which gave me a 7 day debuff that doesn't allow me to go invisible to try pick pocketing the item.
According to the GM I spoke to he was able to complete the quest, but I'm not sure if he killed the drone or just pick pocketed.

2. Klaven Mortwake doesn't fight back, he just continues looking at books while you try to kill him.

1. There should be a 100% drop rate either from killing the guy or pick pocketing
2. Klaven Mortwake should fight back when attacking him.

**Comment by stealer0517** [comment]
It's definitely poor design on Blizzards part that there even is a wrong way to do the quest. 
Blizzard seem to have gotten around that by making the mob always drop the key based on wowhead's classic wow info.
I'm assuming that's something they changed for people like me who are too dumb to read properly.

Also rereading the original post I just noticed that github mangled my text.
It should have been 1 and 2 as the problems, then 1 and 2 as expected results. 
Sorry about that confusion.

**Comment by fvicaria** [comment]
works

**Comment by WhitephoenixTheBunny** [comment]
@fvicaria the quest works, only the npc doesn't fight back when aggroed

**Comment by Rushor** [comment]
will check

**Comment by Rushor** [comment]
will attack now
