### ISSUE TITLE
[Raid] Lady Deathwisper 25 hc phase transition

### ISSUE THREAD

**Issue by Plege** [WoWManiaUK/Redemption#560]
When we last tried this fight at the beginning of Phase 2 a wave of adds spawned, this should not happen there should be a delay as there is at the beginning of the fight

The spawn timers of the adds should be as follows:
Phase 1: - first wave 6/7 seconds after beginning of fight 
              - then 45 seconds intervals
Phase 2: -first wave after 6/7 seconds after the manashield goes down
              - then 45 second intervalls as before

My sources are:
Paragon kill of LadyD 25 hc https://www.youtube.com/watch?v=J2b-68A5Zi0 and 
Exodus kill of LadyD 25 hc  https://www.youtube.com/watch?v=YMaNM3FQ7TM

I could not find the spell id on wow head

**Comment by fvicaria** [comment]
Duplicate #555
