### ISSUE TITLE
Path of Frost stops player from moving on Argent Tournament mounts

### ISSUE THREAD

**Issue by Bulb1** [WoWManiaUK/Redemption#5601]
What is Happening:
https://youtu.be/hHxu3-t1juI

**Comment by hawker357** [comment]
Confirmed, the mounts used for the Argent Tournement quests are affected by Path of Frost, when the mount recieves damage and the buff is re-applied it gets stuck for a second.

Alliance mounts:
https://www.wowhead.com/npc=33845/
https://www.wowhead.com/npc=33319/
https://www.wowhead.com/npc=33217/
https://www.wowhead.com/npc=33317/
https://www.wowhead.com/npc=33408/
https://www.wowhead.com/npc=33318/

Horde mounts:
https://www.wowhead.com/npc=33844/
https://www.wowhead.com/npc=33321/
https://www.wowhead.com/npc=33324/
https://www.wowhead.com/npc=33320/
https://www.wowhead.com/npc=33323/
https://www.wowhead.com/npc=33322/

**Comment by Keader** [comment]
spell issue... fixed

**Comment by Moriane** [comment]
![WoWScrnShot_083021_181556](https://user-images.githubusercontent.com/86922193/131308386-eab6b998-0a91-47e9-9c6f-21ae1eb8b928.jpg)
![WoWScrnShot_083021_181549](https://user-images.githubusercontent.com/86922193/131308396-42ddad9d-2875-4a2a-962e-c87ffc8f176f.jpg)

Path of Frost aura now cancelled when mounting Argent Tournament mounts.
