### ISSUE TITLE
[QUEST] Last Rites

### ISSUE THREAD

**Issue by womptista** [WoWManiaUK/Redemption#5602]
**Links:**
wow mania armor link - https://www.wow-mania.com/armory/?quest=12019

**What is Happening:**
Video Prove - https://youtu.be/pG5KW9DuWxg
The line can be accepted but can not be started as only one NPC is there and the other NPC never show up so the quest can not be completed.

{I have abandoned the quest and retried with same results, I have abandoned the quest again, I have closed the game and cleared the cache then started the game, re accepted the quest and again same results.

**What Should happen:**
You should be able to talk to Thassarian inside the quest to start the quest and Valanar to show up and you can complete the quest.

**Comment by svijetlo** [comment]
have to test it cos i do remember i finished this quest on few toons

**Comment by jeyrella** [comment]
has had several fixes recently #5554 #5557 #5560  so this may be a regression/incompleteness

**Comment by fvicaria** [comment]
This was working before. This is the problem with trying to correct small cosmetic issues.
Need to be reverted or fixed quick.

**Comment by Rushor** [comment]
the issue seems that the quest npc does not reset when a player leaves to early.

the previous version had lots of issues aswell regarding boss not attacking, scenes beeing not in line

**Comment by Rushor** [comment]
should be fine now https://i.imgur.com/XQXMHJi.jpeg

when this issue happen for some reason a gm can safly die and respawn the Thassarian.

For me he despawns at the end of the outro and respawn again after some time
