### ISSUE TITLE
[NPC / Mob / Dungeon] Creeping Ooze (ID 17356) and Creeping Oozeling (ID 17357)

### ISSUE THREAD

**Issue by WhitephoenixTheBunny** [WoWManiaUK/Redemption#5604]
On the TBC dungeon, in Hellfire, **Shattered Halls** they're some missing mobs, namely in **The Sewer**, the missing mobs are:

[Creeping Ooze](https://www.wow-mania.com/armory/?npc=17356)
[Creeping Oozeling](https://www.wow-mania.com/armory/?npc=17357)

We can see here in [wowwiki ](https://wowwiki-archive.fandom.com/wiki/Shattered_Halls#Dungeon_Denizens)that those mobs are referred:
![image](https://user-images.githubusercontent.com/31921098/129903579-0749aec8-5759-4bdd-a26d-a4070b7f52b2.png)
and:
![image](https://user-images.githubusercontent.com/31921098/129903659-b02f50a8-240a-4239-9d58-b4d52e26a7d3.png)

And from a [youtube video](https://www.youtube.com/watch?v=-VykP8K_LUk), we can see them:
![image](https://user-images.githubusercontent.com/31921098/129904126-e700a436-c2fe-418b-9d6f-86c19cd56fe3.png)
![image](https://user-images.githubusercontent.com/31921098/129904179-5a2c9cc2-41cb-4857-b259-6264c68358c5.png)

Screenshot from Mania:
![image](https://user-images.githubusercontent.com/31921098/129904923-11a03a95-4628-4d4e-ba37-1fe7ec1a8c9b.png)

Both can be found on normal and heroic mode, and both give reputation, either Honor Hold either Thrallmar.

**Comment by Rushor** [comment]
spawns added for them
