### ISSUE TITLE
[Quest] Seal of Ascension

### ISSUE THREAD

**Issue by Sierbahnn** [WoWManiaUK/Redemption#5605]
The Scarshield Infiltrator in Lower BlackRock Spire changes into Vaelan, and offers his little monologue, and works, script and all, but does not offer the quest "Seal of Ascension".
I have completed it on another character but now the quest is not being offered.
Psygoa confirmed that the quest was not on there, reset the mob, and tried again, but it still did not work.

Help?

**Comment by Rushor** [comment]
removed and should work normal again
