### ISSUE TITLE
Shadowmeld not working

### ISSUE THREAD

**Issue by Xangretor** [WoWManiaUK/Redemption#5606]
**Links:**
https://www.wowhead.com/spell=58984/shadowmeld

**What is Happening:**
If you use Shadowmeld, mobs keep attacking and you turn visible.

**What Should happen:**
If you use Shadowmeld, you should leave combat and stay invisible.

**Comment by WhitephoenixTheBunny** [comment]
What's your level and the mob level?

**Comment by Xangretor** [comment]
Level 80, mob 77.

**Comment by svijetlo** [comment]
Shadowmeld does not make you lose agro
 it makes mobs not attack in agro range you if you are out of combat,
 if in combat it wont help much

**Comment by Xangretor** [comment]
I use it on retail all the time to leave combat. Works there and I know it used to be that way in WOTLK retail as well.
I am not talking about dungeons and raids and stuff, just open world.

**Comment by Oganku** [comment]
If you're in a group and you Shadowmeld, you drop aggro temporarily and re-gain it after you exit Shadowmeld, but if you are alone and without a pet, it should absolutely drop all your threat, causing you to exit combat, and if you then cancel Shadowmeld, you're still out of combat, there's no way it should put you back in combat.

**Comment by Keader** [comment]
Shadowmeld dont make creature ignore you, if u are too close of him (because he can still detect you)
i cant find anything wrong here
