### ISSUE TITLE
[instance] Rend/Gynth-fight

### ISSUE THREAD

**Issue by Sierbahnn** [WoWManiaUK/Redemption#5607]
**Links:**
https://classic.wowhead.com/npc=10339/gyth

**What is Happening:**
Rend does not spawn.
Even at super-low dps he does not reliably jump off at low health on Gynth.

**What Should happen:**
When you engage Gynth, at low health, Rend is supposed to jump off, you are supposed defeat him to open the next door.

I suggest that maybe you can time his appearance with the timer of the buff Gynth gets from Nefarian. If you nuke him down, no rend, but if you wait out the buff then Rend automatically spawns, regardless of health on Gynth.

**Comment by Keader** [comment]
try now pls

**Comment by svijetlo** [comment]
i did work for me fine

**Comment by moenbase** [comment]
Hi, I was prompted to reply to this ticket.
Been trying UBRS lately as well. To get the the tier 0 stuff for all my characters. And do their quests..
However, this miniraid is by far the worst so far.
The gate doesn't reliably open when killing both bosses.

Edit:
For each boss, I waited 5 minutes before killing it.
Now only the first gate opens. And the second gate after the bosses will stay shut.

Edit 2:
Waiting 5 minutes before going all out on Gyth.
Which is kinda when his buff runs out.
At around 1000-somewhat health, Rend will jump off.
Then you finish off Gyth.
Wait another 2:30 minute before killing Rend.
So far the door opens up for me 5 times in a row.
But it's bloody annoying to just stand there doing nothing.
