### ISSUE TITLE
[Fishing] Loot error "You Don't Have Permission to Loot This Corpse"

### ISSUE THREAD

**Issue by tozecrl** [WoWManiaUK/Redemption#5609]
**Links:**

**What is Happening:**  good morning i'm fishing to see if i can catch the sea turtle but what's happening to me is that " i don't have the premise to catch this body " i have screenshot

**What Should happen:** 
I opened a ticket for the GM and saw GM Brontes where he told me that because they are fighting players die and I can't catch the body but I was fishing I don't think one thing has anything to do with another and I said I had a screenshot of what was going on and I

![unknown](https://user-images.githubusercontent.com/89585881/130962513-f7df5b7d-20ee-4f20-b53b-77303ac54e38.png)

**Comment by Keader** [comment]
any reproduce step folks?
