### ISSUE TITLE
[Isle of Conquest] Parachutes

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#5612]
**Links:** I didn't manage to get the buff ID before it vanished from me and I can't seem to find it. (Edit: Spell ID: 66656)

**What is Happening:** After capturing the hangar, you can teleport on the gunship and the gunship itself+cannons work fine. I saw the parachute buff on me and decided to jump off to assault the keep on foot, but my parachute never deployed. The parachute aura buff seems to be based on a radius from the gunship, and after falling a certain distance it just disappeared. 

**What Should happen:** If people on the airship decide to jump off, they should be granted a parachute as they begin their descent, so they dont just kill themselves on the ground.

**Comment by svijetlo** [comment]
this one exist for some time now as i know

**Comment by Rushor** [comment]
changes made to id: 66656 trsnport handling, should work now

**Comment by Rushor** [comment]
https://i.imgur.com/iTYtzBq.jpeg
