### ISSUE TITLE
[Quest] The Missing Diplomat 

### ISSUE THREAD

**Issue by stealer0517** [WoWManiaUK/Redemption#5613]
https://www.wow-mania.com/armory/?quest=1265
https://www.wow-mania.com/armory/?quest=1266
https://www.wow-mania.com/armory/?npc=4967

With quest 1265 active when you arrive at Sentry Point Archmage Tervosh should be there in order to turn in the quest and start the next one.
Currently when you turn in quest 1265 he only stays active for about 20 seconds then despawns.
It's just long enough for him to cast the buff on the player then despawns a few seconds later.

Ideally he should stay active there long enough for someone as literate as me to read the text and figure out what the NPC is doing.

**Comment by stealer0517** [comment]
Additionally the last two quests in the chain have the NPCs despawn fairly quickly.
https://www.wow-mania.com/armory/?quest=1324
https://www.wow-mania.com/armory/?quest=1267

**Comment by Rushor** [comment]
in the script there is no action that makes him despawn actually

**Comment by Rushor** [comment]
https://i.imgur.com/eFx2flC.jpeg does not despawn for me at all. can you give more info on how to reproduce the issue?

**Comment by Rushor** [comment]
@stealer0517 can you try to reproduce this again?

**Comment by stealer0517** [comment]
In the big tower in town is where he's normally is at, but with quest 1265 active he should spawn in the watch tower at coordinates 59 41.
When I went to the tower he was correctly there. But once I turned in the first quest was when he despawned.

I was able to find him in the tower in town to continue the quest, but you're supposed to turn in 1265 and start 1266 at the guard tower.

**Comment by Rushor** [comment]
ah now i understood

**Comment by Rushor** [comment]
okay it works like that: when player enters tower the archmage will spawn for 60 seconds. will increase that timer to 180 sec
