### ISSUE TITLE
[Achievement] A-bomb-ination

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#5614]
**Links:** https://www.wow-mania.com/armory/?achievement=3849

**What is Happening:** Using bombs on enemy gates does not count towards the achievement.

**What Should happen:** Using bombs should add to the achievement counter, which resets after each battle.

**Comment by Rushor** [comment]
try now pls

**Comment by Rushor** [comment]
works when using https://i.imgur.com/qQZwqUE.jpeg Huge Seaforium Bombs
