### ISSUE TITLE
[Achievement] Demolition Derby

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#5615]
**Links:** https://www.wow-mania.com/armory/?achievement=4256 (Possibly also https://www.wow-mania.com/armory/?achievement=3856)

**What is Happening:** Killing a horde Siege Engine in Isle of Conquest as alliance does not count toward the achievement. Might be due to the vehicle ID being wrong (like if it's a wintergrasp siege for some reason). 
**I have not tried on horde side, killing an alliance Siege, but it probably behaves the same.

**What Should happen:** Killing Siege Engines should count toward the achievement just like the other vehicles.

**Comment by Rushor** [comment]
handled inside the corescript of the creatures 34775 - 35273 now

**Comment by Rushor** [comment]
https://i.imgur.com/L1fQMs2.jpeg works after killing fitting creature
