### ISSUE TITLE
[Quest] Call to Arms: Isle of Conquest

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#5616]
**Links:** https://www.wow-mania.com/armory/?quest=14163
https://www.wow-mania.com/armory/?quest=14164

Identical to issue #4850

**What is Happening:** The call to arms quests for Isle of Conquest (linked above) don't get automatically accepted upon joining the battleground, despite the call to arms event being active.

**What Should happen:** You should automatically get the quest, similar to the other battlegrounds.

**Comment by Rushor** [comment]
added to the script that the quest is added and rewarded(if winning) to the battleground
