### ISSUE TITLE
Cant Reset Password

### ISSUE THREAD

**Issue by beldis123** [WoWManiaUK/Redemption#5617]
**Links:**
https://www.wow-mania.com/site/reset-password?token=pC12T0POEBUOJ5sMfz9P_tyq85ARvGo1_1631252585

**What is Happening:**

Cant reset my password , it just says internal error
**What Should happen:**

**Comment by WhitephoenixTheBunny** [comment]
Not a GitHub post, try contact a GM on the discord
https://discord.gg/qCeUEgTu
