### ISSUE TITLE
[Quest] Frostsaber Provisions #4970

### ISSUE THREAD

**Issue by kamoodle5** [WoWManiaUK/Redemption#5619]
https://classic.wowhead.com/quest=4970/frostsaber-provisions

What is happening.
When the quest is accepted, this causes the player's PvP flag to activate. The player will remain flagged until the quest is either completed or disbanded.

What should happen.
The quest should not flag a player for PvP.

Attached image is a screenshot of the warning I received before accepting the quest.
![WoWScrnShot_091121_132606](https://user-images.githubusercontent.com/67519835/132997984-10c20794-23e0-49f5-aef7-f8fa01c97179.jpg)

**Comment by Rushor** [comment]
will check, needs wowhead research aswell

**Comment by kamoodle5** [comment]
I can post a link of the Frostsaber reputation guide from wowhead if requested. I was going to mention the Youtube video provided in the guide on how to obtain the mount that does briefly show this quest in progress, but that content is not from retail WoW.

**Comment by Rushor** [comment]
Is there a classic wow video about it maybe?

**Comment by Echinaceax** [comment]
@Rushor here is a pre cata video i found for you 
https://www.youtube.com/watch?v=flRTUI6u3Xw

**Comment by jeyrella** [comment]
@Echinaceax unfortunately that player is on a pvp realm already so it would have no difference.

Having said that, I have checked through wowhead and there is zero mention anywhere that it would flag player as pvp (one would expect that mentioned given the number of guides and comments)
Also, wowhead classic pvp quests only list the Silithus quests under the "pvp" category or "players flagged as pvp" filter.

While I can't find any +ve confirmation (which of course, wouldn't exist if it wasn't), the complete lack of -ve confirmation would suggest this is valid.

**Comment by Rushor** [comment]
no pvp flags anymore

**Comment by svijetlo** [comment]
all good here no pvp tag after taking quest
