### ISSUE TITLE
[Quest] Redemption (part 1 of 7)

### ISSUE THREAD

**Issue by jorgeppatron** [WoWManiaUK/Redemption#562]
First of all, full description:
- Zone: Easter Plaguelands
- Quest: Redemption
- NPC: Tirion Fordring
- Coords: 67~, 24~

You are able to get this quest after completing 3 quests from this same NPC and then you are able to take this quest. The thing is that you are supposed to "listen" the Tirion's tale in order to complete the quest, which is also supposed to get by the action when clicking it. Here is the thing: Tirion doesn't have the action to continue, and therefore you can't complete the quest and continue the chain quests for further adventures.

Some friends already told me that this quest is not working in several servers, including WoWMania. It would be awesome to consider this situation by the fact of all those quests to do (even for the ones as me who are actually trying to get the Loremaster's achievement).

That's all I have to say by now, thanks. :)

**Comment by Emcitementz** [comment]
This is not bugged.
You just have to /sit and listen to his tale.
