### ISSUE TITLE
[Spell] Haunted #18347

### ISSUE THREAD

**Issue by kamoodle5** [WoWManiaUK/Redemption#5620]
https://classic.wowhead.com/spell=18347/haunted
https://classic.wowhead.com/quest=5168/heroes-of-darrowshire
https://classic.wowhead.com/item=12954/davils-libram
https://classic.wowhead.com/item=12955/redpaths-shield

What is happening:
After collecting each quest item for Heroes of Darrowshire, the shield and the libram, the Haunted buff will appear. Once every 3 minutes, this buff will suddenly cause the world around me to disappear, having me fall into oblivion. I found if I stand still long enough while in the void, I'll safely return to almost the same spot I was.

What should happen:
The Haunted buff shouldn't cause players to fall off the world. Instead, it summons an apparition to follow the player around until the effect expires, or according to a comment, they mount.

Unfortunately, I wasn't able to find a video that shows the buff summoning a poltergeist after the player obtained the quest items. This is the best WoW Classic video available for the quest:
https://youtu.be/hvM7HFHQznk

And here's a screenshot of me stuck underneath the world once the buff triggered its effect after the first 3 minutes. This occurred twice more until the buff ran out:
![WoWScrnShot_091321_175236](https://user-images.githubusercontent.com/67519835/133188179-0c982cb4-55b4-4621-ba91-b76fc91f5eea.jpg)

**Comment by jeyrella** [comment]
Oooh.  That would be interesting, I have fallen into oblivion in WPL/EPL several times in the past but always assumed it was a map problem.  Interesting dots you have connected there...

**Comment by Rushor** [comment]
issue was that the spell that get's triggered after xx minutes calls a massive fall instead to summon a hunted creature. changed the effect to work as intended now.

also the summoned creature will be passive, walk around a bit and tell a text upon spawn. no supportive effect to prevent abuse

**Comment by Rushor** [comment]
possible texts upon spawn are https://classic.wowhead.com/npc=11296/darrowshire-poltergeist#comments:id=2912401 and some more

**Comment by Rushor** [comment]
you can quick text the summon effect by: .cast 17694

17694 is the spell that get's casted once spell Haunted#18347 fades away by time

**Comment by svijetlo** [comment]
works good no falling to void or smt you can complete it now properly
