### ISSUE TITLE
[Object] Wintersbite 

### ISSUE THREAD

**Issue by WhitephoenixTheBunny** [WoWManiaUK/Redemption#5621]
First at all I will really need a doble check from someone else on this one.

I've been farming [wintersbite](https://www.wow-mania.com/armory/?item=3819) for the [Frost Oil ](https://www.wow-mania.com/armory/?item=3829), but I haven't be able to find one single "node" of [wintersbite ](https://www.wow-mania.com/armory/?object=2044), I have been using WoW Mania Armory for that
![image](https://user-images.githubusercontent.com/31921098/133236210-0dcf9a85-52a1-43bd-9521-906683bcb05c.png)

I have done some research, and:

> After The Shattering, Wintersbite was renamed Dragon's Teeth. (in _[wowwiki](https://wowwiki-archive.fandom.com/wiki/Wintersbite)_)

So in Wotlk, we still should have Wintersbite spawns, and not only mobs drop

**Comment by jeyrella** [comment]
Yes it should spawn.  I could swear it has as it is used in two Loremaster quests, but then again maybe I just saved it from the various NPCs it drops from.
PTR is down so cannot check right now

**Comment by WhitephoenixTheBunny** [comment]
@jeyrella PTR is up
![image](https://user-images.githubusercontent.com/31921098/133402229-6dcf01da-2d63-44e1-b7f1-5ac8761eddf8.png)

from those 10 showing in the list, only one is there, with gm on

**Comment by jeyrella** [comment]
so sounds like pooling isn't working correctly

**Comment by Rushor** [comment]
they are pooled, which atm means 17 out of 364 objects spawn at the same time. it's lucky depend if it spawns Alterac Mountains - Stranglekelp or Alterac Mountains - Goldthorn or Alterac Mountains - Khadgar's Whisker  etc. etc.

i increaded the max limit from 17 to 30 to make it easier to farm in this area

**Comment by svijetlo** [comment]
looks fine to been there gathering for a bit , but as it share spawn with other plants it can also be do to luck how much you get

**Comment by Rushor** [comment]
Alright man, Yeah that is how it works
