### ISSUE TITLE
 Zone: Stormpeaks, Quest: The Drakkensryd, PRBL: Quest doesn't work right

### ISSUE THREAD

**Issue by goldfingyr** [WoWManiaUK/Redemption#5623]
You can get from drake to drake, but engaging in combat with the hostile rider is nearly impossible.
I succeeded in engaging in just one, but have no idea how that occurred and was not able to recreate the situation.
In order to complete the quest, you have to kill 10 hostile riders jumping from dragon to dragon. But the riders will not engage and neither can you.

**Comment by svijetlo** [comment]
this one can be strange but i always did complete it even now on test, some one other pls try it i did it with paladin and rogue

**Comment by fvicaria** [comment]
It works. It has some peculiarity and you need to insist.

**Comment by Rushor** [comment]
for melees it is sometimes bugged, only option for that is to remove the path movement from the drakes, but that looks even worse
