### ISSUE TITLE
bug for vote

### ISSUE THREAD

**Issue by Sekula1993** [WoWManiaUK/Redemption#5626]
**Links:**
https://www.wow-mania.com/account/voting

**What is Happening:**
When I go to vote, I just go to the voting site and get a VP token

**What Should happen:**
Usually I go to solve "I'm not a robot", but this time I just had to go to the site
Check it out because I guess then the vote will have no effect if the vote path is not done
i used google chrome, incognito mode

**Comment by GMMetaxa** [comment]
Invalid. Not a bug. Check the "How to vote" section on Discord or ask all players that receive the full amount how to properly vote.
