### ISSUE TITLE
72+ Last Rites

### ISSUE THREAD

**Issue by Strmo44** [WoWManiaUK/Redemption#5627]
![WoWScrnShot_092821_123306](https://user-images.githubusercontent.com/91536207/135071991-1c220cb8-f5bb-4029-8d12-2c5a278cb2d0.jpg)
 
in quest 72+ Last Rites is buget Thassarian. i can ask him to begin battle scene.

**Comment by Rushor** [comment]
Could someone help me to reproduce this?

**Comment by Dmw1981** [comment]
![image](https://user-images.githubusercontent.com/64038447/135569256-46133e0c-a544-4dbb-b5f2-5736205d6aa7.png)
same here he aint talking

**Comment by Dmw1981** [comment]
gm reset the npc so i could talk to him but he just got stuck again :(

**Comment by Dmw1981** [comment]
i went back to the area and did the extra introduction quest from the camp at deaths stand and he worked properly after that. so maybe skipping those 2 quests confuses the poor sod

**Comment by svijetlo** [comment]
it is questline if you do not do all leading to it it will not work properly
