### ISSUE TITLE
brewfest dailys issue

### ISSUE THREAD

**Issue by greenmangoo** [WoWManiaUK/Redemption#5628]
**Links:**

**What is Happening:**
hello, i m having issues with event dailys, i see them on minimap and i also can see the npc with exclamation mark on top of him but when i click on the npc there is no quest to accepct, i ve done every single quest from the event including the quest that you need to do to be able to acept these dailys soo i dont know what else i can do

**What Should happen:**
i should be able to see the quest and acept it since i ve done the previous ones to unlock the dailys

**Comment by Rushor** [comment]
prolly hardcoded quest menu, which daily quests you exepct to see at which npcs? I need npc names, entries etc.

**Comment by namedidntfi** [comment]
I'm having the exact same issue. There are two available brewfest dailies, 1 is the "Dark Iron mole machine wreckage" that will allow me to accept and complete, 2 is the ram run through ironforge where you Bark at the four locations and is offered by two npc's "Daran Thunderbrew" and "Becan Barleybrew." Both npc's have a blue ! mark but when you click on them the quest page has no information other than "Greetings, Lazoris," no accept or decline buttons, just goodbye.

The strange part is I don't have this issue on a different character despite having completed the Brewfest questchain on all of them.

**Comment by Rushor** [comment]
this is due to non reseted quest data from last year. we will take care of that within the next event start.
