### ISSUE TITLE
Brewfest Dailies not showing quest deatails "accept" "decline"

### ISSUE THREAD

**Issue by namedidntfi** [WoWManiaUK/Redemption#5629]
There are two available brewfest dailies, 1 is the "Dark Iron mole machine wreckage" that will allow me to accept and complete, 2 is the ram run through ironforge where you Bark at the four locations and is offered by two npc's "Daran Thunderbrew" and "Becan Barleybrew." Both npc's have a blue ! mark but when you click on them the quest page has no information other than "Greetings, Lazoris," no accept or decline buttons, just goodbye.

I've completed the Brewfest questchain on 2 characters. One allows me to complete both dailies. The other character only lets me complete the one daily.

**Comment by svijetlo** [comment]
we can close this one as it is in comment on same issue posted before

**Comment by Rushor** [comment]
Alright, maybe Post additional Infos in the existing one then of needed
