### ISSUE TITLE
[Core] Problems with getting stuck in combat

### ISSUE THREAD

**Issue by wrthigpen** [WoWManiaUK/Redemption#563]
When a player's character gets stuck in combat, they have only a few options to exit: 1) the mob they are fighting dies, 2) their character dies, 3) exit using .cl, or 4) close game using Alt-F4.  Most of the time options 1 and 2 work, but many times those do not.  Using .cl now has a 5 minute timer so the player is left  sitting around for up to five minutes twiddling his thumbs or exiting the game and then re-entering the game.  Both are time wasting and are not conducive to good game play.  Wow-Mania advertises in-game that they are the best private World of Warcraft server.  I submit a challenge that if this problem cannot be remedied, then Wow-Mania is not the best private World of Warcraft server.  I enjoy playing on your server, but I do like to have problems fixed, not workarounds that go on forever, then have time limits put on the workaround.  Character name=Johnt, location=Westfall, server=Redemption, Date & time=Dec 4, 2016, 01:12 server time.  Thank you for listening.

**Comment by fvicaria** [comment]
I will try to improve the system. A 5 minute cooldown for something that does not happen that often is not an issue. Besides people were abusing it when it had no cooldown.
