### ISSUE TITLE
[Quest] The Purification of Quel'Delar 

### ISSUE THREAD

**Issue by Strmo44** [WoWManiaUK/Redemption#5630]
https://wow-mania.com/armory/?quest=24553#.

![WoWScrnShot_100521_104843](https://user-images.githubusercontent.com/91536207/135994964-8783ca8b-79a3-452a-8446-db149defb49a.jpg)
Warden of the Sunwell dont teleport me in to Sunwell when i ask him .  i dont can purifi Quel'Delar. 

 I must speek with Warden of the Sunwell and they teleport me into Sunwell.

**Comment by WhitephoenixTheBunny** [comment]
You need be in a raid group

**Comment by svijetlo** [comment]
What phoenix told ...
