### ISSUE TITLE
[Spell] Rogue- Cloak of Shadows + Mind Control

### ISSUE THREAD

**Issue by svijetlo** [WoWManiaUK/Redemption#5633]
**Links:**
http://www.wow-mania.com/armory?spell=31224

http://www.wow-mania.com/armory?spell=71289

http://www.wow-mania.com/armory?spell=70923

https://wowwiki-archive.fandom.com/wiki/Cloak_of_Shadows

![image](https://user-images.githubusercontent.com/61908373/139062428-9f2c6418-8c33-4c95-b707-897924266cb0.png)

**What is Happening:**
While player fight bosses that can mind control in this case specifically ICC boss Lady Deathwhiper and Blood Queen Lanathel 
player can get  under mind control state from spells mentioned above  , if one has Cloak of Shadows off cooldown AI will use it AND NOT REMOVE mind control form it self and giving player back control over character / rogue .

p.s. need to test, find data and make one for other bosses that have similar mind control mechanic in other raids 
**What Should happen:**
if AI use cloak of shadows while player is mind controlled, **it should remove** mind control effect from character

**Comment by Keader** [comment]
fixed

**Comment by Keader** [comment]
k, it's builded

**Comment by svijetlo** [comment]
NICE IT WORK  sry for not testing it sooner =)
