### ISSUE TITLE
[Talent] Divine Guardian Talent (Paladin) does not buff Sacred Shield correctly

### ISSUE THREAD

**Issue by hawker357** [WoWManiaUK/Redemption#5634]
**Links:**
https://www.wow-mania.com/armory/?spell=53530
https://www.wow-mania.com/armory/?spell=53601

**What is Happening:**
Divine Guardian talent does not increase Sacred Shield absorb. It only increases the Aura duration.

**What Should happen:**
Divine Guardian is supposed to buff the Sacred Shield Spell/Aura by increasing the duration by 100% (30 seconds) and the absorb damage by 20% (100 dmg).

Talent (2/2)
![Screenshot (157)](https://user-images.githubusercontent.com/79724094/140339109-ec5204ca-3ea2-4000-a5f2-7e1a6118a906.png)

Spellbook tooltip (Note the 600 absorb and 1 minute duration)
![Screenshot (156)](https://user-images.githubusercontent.com/79724094/140339120-172a787f-569c-4147-9214-0a6908b0b5e9.png)

Active Aura on player (500 absorb and 1 minute duration)
![Screenshot (155)](https://user-images.githubusercontent.com/79724094/140339126-93fde79d-a3bb-49b5-a5f4-9e4b2b8e7aed.png)

**Comment by Keader** [comment]
Checked in code and everything is correct.
This is visual bug, the correct amount of sacred shield is correct.

**Comment by svijetlo** [comment]
yap tested it it is minor visual bug but spell talents work fine
