### ISSUE TITLE
[Quest] Iv'e got a flying machine

### ISSUE THREAD

**Issue by amikot** [WoWManiaUK/Redemption#5635]
**Links:**
https://www.wowhead.com/quest=11390/ive-got-a-flying-machine
https://www.youtube.com/watch?v=P74jNj9vI8s&ab_channel=Finom

**What is Happening:**
Flying machine works and can pick the sack of relics from excavation site with 2nd tool of toolbar (hook) - this is correct. 
Sack of relics brought to destination platform don't disappear and is not counted as supplied.
Using hook when sack is already hooked result in ejecting the player from flying machine. 

**What Should happen:**
Arriving to destination platform with sack attached should cause sack to be counted as delivered and should disappear from the hook.
Using the hook should do nothing except when picking the sack from bottom of the site.

**Comment by jeyrella** [comment]
Hmm.  I have done this a few times on Red and not noticed anything.  Will check when PTR is up and running again

**Comment by amikot** [comment]
For me and other person that I'm playing with it didn't work.
We both playing on the Alliance site - maybe it works only for horde?

**Comment by svijetlo** [comment]
works fine to me no eject if i have sack and i use hook ,a slo it was counted ones i deliver , keep in mind platform to deliver is one on crane not one where you pick up plane 
work perfect to me
