### ISSUE TITLE
[Quest] Mutiny on the Mercy

### ISSUE THREAD

**Issue by amikot** [WoWManiaUK/Redemption#5636]
**Links:**
https://www.youtube.com/watch?v=_ZfheZP46i4&ab_channel=GitGudGuides

**What is Happening:**
Cant collect quest items because pirates are not spawning at all - so they can't drop. 

**What Should happen:**
Under the board on the ship should spawn mutinous gunners who when killed should drop barrels of the gunpowder.

**Comment by Rushor** [comment]
generic vehicle related issue, i will spawn some of the needed pirates on land aswell

**Comment by jeyrella** [comment]
No rushor, this is not a defect.  it was moved to the other static ship as a silent fix by Blizzard because the drops fell through the floor.  Leave as is, as this is retail-like.

**Comment by Rushor** [comment]
alright man!
