### ISSUE TITLE
Mountaineer Kilian not giving quests

### ISSUE THREAD

**Issue by Xangretor** [WoWManiaUK/Redemption#5637]
**Links:**
https://www.wowhead.com/npc=26885/mountaineer-kilian#starts
https://www.wowhead.com/quest=12128/check-up-on-raegar

**What is Happening:**
Mountaineer Kilian doesnt give any quests.

**What Should happen:**
He should give 4 quests after completing https://www.wowhead.com/quest=12128/check-up-on-raegar

**Comment by Rushor** [comment]
quess you missing seom prequest, will check in DB

**Comment by Xangretor** [comment]
I did every normal quest, except for the Harrison Jones quest (also bugged) and this questgiver. I also have the Zul'Drak achievement 85/85.

**Comment by Xangretor** [comment]
So apperently, on this server you also need to complete https://www.wowhead.com/object=188261/battered-journal before you can get the quests. I opened up the questline, after completing that quest.

Sorry, if it's not a bug.

**Comment by Rushor** [comment]
closed
