### ISSUE TITLE
DK stucks in ghost at The Ebon Hold map

### ISSUE THREAD

**Issue by RedWM** [WoWManiaUK/Redemption#5639]
**Links:**
![image](https://user-images.githubusercontent.com/47967775/142865399-47e31503-b247-4d4a-944f-1d234a53867e.png)

**What is Happening:**
DK died 
use character stuck function in ? icon
relog then DK in ghost move to 2nd floor of the ebon hold
The spirit healer at 1st floor 
so DK in ghost cannot meet the spirit and stuck there

**What Should happen:**
should have more the spirit healer in 2nd floor

**Comment by Oganku** [comment]
You can use the teleport to go to the second floor as ghost..

**Comment by RedWM** [comment]
> You can use the teleport to go to the second floor as ghost..

I tried many times but not working, including jump out floor....
anw, I was revived thank you!!!
