### ISSUE TITLE
[ICC] Rotface oozes should grow based on stacks

### ISSUE THREAD

**Issue by Eronox** [WoWManiaUK/Redemption#5641]
**Links:**
http://www.wowhead.com/npc=36627/rotface#comments

**What is Happening:**

After Mutated infection gets removed, it spawn an ooze. 
Two oozes makes a big ooze. But a small ooze walking into the big ooze should make it even bigger and change color, that's not the case. 

Also, there's missing emotes when stacking the ooze.

Retail Tested

**What Should happen:**

 Mutated infection  
 --> Spawn Ooze
-----> Repeat
--------> 2 oozes merging into a bigger ooze
-----------> big ooze + small ooze = the big ooze gets even bigger and changes color

Upon each growth, these emotes  should occur. I couldn't get it to execute while dual logging on PTR

> '%s grows more unstable!

> %s is growing volatile!

> %s can barely maintain its form!

> %s begins to cast Unstable Ooze Explosion!

**Comment by Rushor** [comment]
all texts and grow and color spells added, actions will perform when the oozes get combined

**Comment by Eronox** [comment]
working
