### ISSUE TITLE
NPCs killed by player when other NPC was involved are not counted for player. 

### ISSUE THREAD

**Issue by amikot** [WoWManiaUK/Redemption#5642]
**Links:**
This is just example quest that is difficult to complete because of the global bug:
https://www.wowhead.com/quest=13212/hes-gone-to-pieces

**What is Happening:**
Allied NPC nearby the enemies are constantly attacking them. Even if I kill the enemy, but Allied NPC just hit him once - I can't loot it and they're not counted for the quest (actually in this quest it's not the case - since it's about collection of the drop).
Problem is really annoying as sometimes it's big problem to kill target without ally NPC being involved. 

**What Should happen:**
Blizzlike behaviour is that any enemy damaged by player is counted in even if was first attacked by NPC.
This of course don't apply to other players where everything is OK and blizzlike.
Problem is only related to enemies shared with allied NPCs.

**Comment by wow-mania** [comment]
Also as-is. You need to do at least 50% of the damage or the kill will not count.
