### ISSUE TITLE
[Location] Mine Field in Storm Peaks

### ISSUE THREAD

**Issue by amikot** [WoWManiaUK/Redemption#5645]
**Links:**

**What is Happening:**
Mines are exploding when you flying over mine field.

**What Should happen:**
Mines should explode only when player is on the ground.

**Comment by Rushor** [comment]
that is correct, needs to be adjusted

**Comment by svijetlo** [comment]
are you sre it is mines as there are also canons that shoot you form air if you fly over it , need to test this one

**Comment by Rushor** [comment]
yes the cannons are shooting you down, that is intended and works all fine, the mines only affect grounded people, the cannons only affect flying people

https://gyazo.com/d863df9e14d937f3daeea0af3ab1622b
