### ISSUE TITLE
[Boss/Mechanic] Lord Marrowgar - Bone Spike Graveyard

### ISSUE THREAD

**Issue by svijetlo** [WoWManiaUK/Redemption#5646]
**Links:**
http://www.wow-mania.com/armory?npc=36612
http://www.wow-mania.com/armory?spell=69057
**What is Happening:**
By the end of Lord Marrowgar if player get hit by Bone Spike Graveyard and boss die while the player is on spike in 4 out of 5 cases 
player will phase out and will not see rest of raid and raid will not see them.
Upon relog player who had it will start falling thru ground and die.
it can happen in every version if fight 10 nm/hc and 25 nm/hc
P.S. atm i have no vid or ss of this happening 

**What Should happen:**
if player get it by Bone Spike Graveyard and at same time while one is on Bone Spike Graveyard boss die , Bone Spike Graveyard should de spawn and player should continue raid wo any extra effects or problems .

**Comment by Rushor** [comment]
vehicle problem should be resolved now when boss dies

**Comment by svijetlo** [comment]
did it 4 times 10nm / hc and 25 nm/hc it did not happen
