### ISSUE TITLE
[Quest] Lantresor of the Blade not "advertising" his available quests

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#5647]
**Links:** https://www.wow-mania.com/armory/?quest=9927
https://www.wow-mania.com/armory/?quest=9928
Somewhat related to #3650
https://drive.google.com/file/d/1iQsgXL04qzk2cP8WXkiXWKgXtI8KCg9Y/view?usp=sharing

**What is Happening:** Lantresor of the Blade does not display an exclamation mark (!) on top of himself, nor on the minimap when he has the 2 quests linked above active. It probably happens with all of his quests and is rather related to the NPC, but I can't check that part. The quests were not "Low level" for me, as evidenced by the yellow text after accepting them on a 67 character: [Gif](https://drive.google.com/file/d/1iQsgXL04qzk2cP8WXkiXWKgXtI8KCg9Y/view?usp=sharing)

**What Should happen:** He should display an exclamation mark to show he has quests to offer.

**Comment by Rushor** [comment]
fixed was missing an update in quest_template_addon https://i.imgur.com/aebUSnH.png
