### ISSUE TITLE
[Quest] Post-Partum Aggression does not complete if using the quest mount

### ISSUE THREAD

**Issue by Scythre** [WoWManiaUK/Redemption#5648]
Having an issue where once the brood mother has been killed the quest doesnt register teh kill and therefore cannot complete the quest, as this is part of the Nessingwary quest line its the very end of a very long chain and needed for the achievment "The snows of Northrend"
A GM has atended and witnessed the quests failure

**Comment by Scythre** [comment]
I have since completed the quest by killing the brood mother whislt not on the quest mammoth mount and it completed the quest as expected. So just an issue when using the quests Mammoth mount.

**Comment by jeyrella** [comment]
Hmm, actually, additionally the quest should _not_ complete if killed while not on the mount, either.
I do recall this one, it never crossed my mind it was fishy.  We should check this one out with some testing.

**Comment by svijetlo** [comment]
need to test it , i always did this one wo problem but i seen lot of players complain about this one

**Comment by svijetlo** [comment]
one more vehicle issue , if you kill mob as you should while on mammoth, it does not count a kill and does not complete quest

**Comment by Rushor** [comment]
questcredit will now be given to the player once broodmother died, even wehen player is mounted on the mammoth

**Comment by jeyrella** [comment]
Need to check - should it not, complete if killed _only_ when on the mount?

**Comment by jeyrella** [comment]
yeah should also count if killed without mount ![image](https://user-images.githubusercontent.com/46089380/147107842-fca3ad8a-6817-456c-a5f7-946a5d6a67f8.png)

**Comment by svijetlo** [comment]
work both ways now mount / no mount
