### ISSUE TITLE
No pets or minions, please help this server is beautiful.

### ISSUE THREAD

**Issue by JagerDawg69** [WoWManiaUK/Redemption#5649]
**Links:**

**What is Happening:**

**What Should happen:**

**Comment by JagerDawg69** [comment]
Hey there, I am having troubles. everything works sweet i just cant see minions when im a warloc. they arent there at all. same goes with hunters, dont see any pets or even tame spell. i would love some help with this please. this server is so great.
thanks so much for you time

best regards,
Jagerdawg69

**Comment by jeyrella** [comment]
@JagerDawg69 this does not sound like a code issue.  Suggest you reach out to a GM in-game, or on the Discord channel.
