### ISSUE TITLE
[Raid] Razorscale does not ground if threshold reached after she casts Wing Buffet

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#5650]
**Links:** https://www.wowhead.com/npc=33186/razorscale

**What is Happening:** At 50% hp, Razorscale becomes permanently grounded in general. However, if you push through that 50% hp threshold after the harpoon expired and she is about to take off, she will skip her grounding and never ground after. If you use the next wave of harpoons, she still won't land and will be stuck in the air and force the raid to wipe.

**What Should happen:** The threshold for grounding phase should be periodically checked (at least every time the 4 harpoons are thrown) instead of punctually to avoid such problem.

**Comment by Rushor** [comment]
okay found it, boss should no longer start to fly away if 50 percent phase has been triggered. it was an issue, like you said, in between 4 seconds between wing buffet and the resume air phase.
