### ISSUE TITLE
[Raid] Auriaya's cats stack incorrectly while walking (25-man)

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#5651]
**Links:** https://www.wowhead.com/npc=33515/auriaya

**What is Happening:** Auriaya's cats are double spawned by mistake on 25 man.

**What Should happen:** Her cats should not randomly be copied like that.

**Comment by svijetlo** [comment]
also i need to make post about bug out of boss so you get easy ach if you pull and FD and or vanish ...

**Comment by Rushor** [comment]
4 cats on 25 man are intended:

I've yet to find a really GOOD, clear explanation of pulling this boss on 25 man- I've done it multiple times on 10 man with no issues, it's hardly difficult. However, all four cats on 25 man have a tendancy to completely obliterate someone if even one thing is off.

**Comment by Rushor** [comment]
But anyway i fixed the formation angle of the cats so they do not "stack" on each other. That was a issue

**Comment by Rushor** [comment]
with fix: https://i.imgur.com/svgiHhn.jpeg

**Comment by Oganku** [comment]
Good catch on the 4. Makes it more "normal" to have them spread this way instead of them surprising you with shadow clones on pull 😁
