### ISSUE TITLE
[Quest] Spirits of Stonemaul Hold #11159 are duplicated

### ISSUE THREAD

**Issue by kamoodle5** [WoWManiaUK/Redemption#5652]
https://tbc.wowhead.com/quest=11159/spirits-of-stonemaul-hold

What is happening:
Two spirits appear when redeeming one of these remains. Also, the remains take longer than expected to respawn.

What should happen:
Only one ogre should spawn instead of two, and the skeletons should respawn more frequently. Comments regarding this quest from wowhead can confirm both as standard.

![WoWScrnShot_121921_233803](https://user-images.githubusercontent.com/67519835/146718676-3bef5645-3d4f-4288-834d-cb7312908e9c.jpg)

**Comment by Rushor** [comment]
will fix

**Comment by svijetlo** [comment]
yes it get two spirits ogre but respawn idk how fast should it be

**Comment by Rushor** [comment]
https://tbc.wowhead.com/quest=11159/spirits-of-stonemaul-hold#comments:id=206661
By lcarnegie on 2007/12/24 (Patch 2.3.0) |   |  
just stick to about 3 of them. The bones spawn rate is insane.

will adjust it to 150 seconds and change the spirit amount

**Comment by jeyrella** [comment]
![image](https://user-images.githubusercontent.com/46089380/147106806-a75b8665-70f4-4f7c-9e25-37d7564e6967.png)

However timer doesn't seem right still?  Does this need a recompile?
![image](https://user-images.githubusercontent.com/46089380/147107300-e481f5f2-7de8-494e-893f-3f3e3c207c39.png)

**Comment by Rushor** [comment]
okay 100 sec now, server restarted
