### ISSUE TITLE
[NPC] Grizzly Bear ID:27131 in forest use wrong "river trout" animation

### ISSUE THREAD

**Issue by Airin258** [WoWManiaUK/Redemption#5653]
**Links:**
Mob: https://www.wowhead.com/npc=27438/rainbow-trout
Related mob: https://www.wowhead.com/npc=27131/grizzly-bear

**What is Happening:**
Northrend; Grizzly Hills; South-west to Westfall brigade encampment. There is a bunch of Grizzly bears in the forest, and near most of them are one rainbow trout critter that just flies around (animation of swimming, but in the air above ground). Sometimes bears catch one of trouts with their maw and this animation works propperly.
![dWyYjAvXJX0](https://user-images.githubusercontent.com/96421124/146761759-baa30b87-4971-4f5d-9f1d-cb848e19925f.jpg)
![WZwQMvkG5fI](https://user-images.githubusercontent.com/96421124/146761794-1154315e-95dd-423f-99fc-4dda7cc2c5bf.jpg)

**What Should happen:**
Looking at wowhead maps, i assume that trouts are supposed to spawn only in river zone, istead they spawn just near grizzly bears.

**Comment by svijetlo** [comment]
![WoWScrnShot_122021_191357](https://user-images.githubusercontent.com/61908373/146813629-b21cf2be-344c-4f21-a419-932134cafcd3.jpg)
![WoWScrnShot_122021_191405](https://user-images.githubusercontent.com/61908373/146813640-2fcc56b5-e05c-41ce-978e-566fd00a57eb.jpg)
i was there i did not see fish critters around them but bears do carry one in mouth and also do animation of eating fish

**Comment by svijetlo** [comment]
EDIT: tehy are copying behavior of bear mob next to river and in river to east , one going north to south next to amberpine lodge

**Comment by Rushor** [comment]
better position for the bears now, only the bears near the water will have the fish in the mouth now, all else are empty

**Comment by jeyrella** [comment]
fixed, bears not by the river no longer catch trout from mid-air
![image](https://user-images.githubusercontent.com/46089380/147105417-6dea4792-f8e0-445d-88e1-609256078898.png)
