### ISSUE TITLE
[NPC/Ability] Tiki Wariors's Spirit burn is too strong

### ISSUE THREAD

**Issue by Airin258** [WoWManiaUK/Redemption#5654]
**Links:**
Mob: https://www.wowhead.com/npc=28882/enchanted-tiki-warrior
Spell: https://www.wowhead.com/spell=54651/spirit-burn

**What is Happening:**
Zul'Drak; Zol'Maz Stronghold, quest enemies Enchanced Tiki Mobs are simply too strong. Their Spirit burn ability (small stat reducement and chance to deal damage on hit) procs too often, 2-4 times per second, dealing 600-700 points of damage each time, leading to 2000+ damage per second, plus meelee attacks, litteraly incinerating my 80 level death knight (against their 77) and making them stronger than most elites in this zone.

**What Should happen:**
I can't be sure if i understood correctly since i am not native english-speaker, but game-master suggested that it has something to do with "chance to deal fire damage on hit" wording and what counts as "hit": Spirit burn procs (or tries to do so) on each tick of my damage-over-time effects and meelee attacks, leading to monstrous amount of procs even if i use only autoattack.
Since i couldn't find any mentions of this mob being hard in any way in wowhead and any other resourses, i assume that Spirit burn supposed to proc when PC gets hit, not other way.

**Comment by Rushor** [comment]
can now only proc every 8 sec which is the best value for the spell now, everything else was simply bugged
