### ISSUE TITLE
[Mount] Magic Rooster has "Invalid Target" error on use

### ISSUE THREAD

**Issue by Wowtks** [WoWManiaUK/Redemption#5656]
**Links:**
https://www.wowhead.com/item=49290/magic-rooster-egg

**What is Happening:**
Magic Rooster Mount cannot be used. Error "Invalid Target" appears. GM Aymelek requests for me to report it here.

**What Should happen:**
Mount can be used.

**Comment by jeyrella** [comment]
Confirmed
![image](https://user-images.githubusercontent.com/46089380/147237124-bb4e0fdf-ffdb-4667-9e58-30adf5a67204.png)

**Comment by Rushor** [comment]
nice ui!

**Comment by Rushor** [comment]
found it! fixed!

**Comment by Wowtks** [comment]
at this point, it still didn't work for me. the same issue arises. I deleted cache and tried it again but didn't get it working.

**Comment by Rushor** [comment]
nah that is only for testserver

**Comment by jeyrella** [comment]
fixed
![image](https://user-images.githubusercontent.com/46089380/147477860-61292074-7ad8-461a-8960-a23d0a48d64c.png)

**Comment by Rushor** [comment]
goody

**Comment by Batildis** [comment]
Thank you!

**Comment by Wowtks** [comment]
is this supposed to be fixed and implemented?

**Comment by jeyrella** [comment]
Not yet.  When the issue is closed, it is implemented in live (and you'll see a #changelog from me on Discord too)

**Comment by Wowtks** [comment]
Thank you, that is helpful to know.

**Comment by jeyrella** [comment]
@Wowtks as you may have seen on Discord, this is now live on the Redemption server.  Thanks :)
