### ISSUE TITLE
[NPC] Teller Plushner wrong position

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#5657]
**Links:** https://www.wow-mania.com/armory/?npc=30607
https://imgur.com/a/LiN99Er

**What is Happening:** Teller Plushner's positioning is a little off, making him stand inside the bank, and not inside his little cubby. The other 2 bankers are fine. It does not seem to be caused by players messing with his, since he has been off position for multiple days, even after server restarts. Video evidence: https://imgur.com/a/LiN99Er
**Note: He is located in the alliance-side bank.

**What Should happen:** Teller Plushner should be returned to his work bench!

**Comment by jeyrella** [comment]
Will have to check on PTR.  This was always correct before so I suspect this is a problem only on Redemption, and that a GM can correct it directly.

**Comment by Rushor** [comment]
if compared to he should reall be inside https://de.wowhead.com/npc=30607/kassierer-pl%C3%BCschner#screenshots:id=94979

**Comment by jeyrella** [comment]
yes he's fine on PTR.  will ask a GM on Redemption to correct there directly.
![image](https://user-images.githubusercontent.com/46089380/147477941-b2de7339-103c-4f2e-8aa0-69356be5bae8.png)
