### ISSUE TITLE
[Item] Gnomish Battle Chicken does not pop on use

### ISSUE THREAD

**Issue by Wowtks** [WoWManiaUK/Redemption#5658]
**Links:**
https://classic.wowhead.com/item=10725/gnomish-battle-chicken

**What is Happening:**
Unable to use trinket. Chicken does not pop. GM verified and told me to report it on here. I'm just having issues with chickens...

**What Should happen:**
A chicken should pop upon use of the trinket.

**Comment by Rushor** [comment]
which error you get when you want to use it?

**Comment by Wowtks** [comment]
no error pops up. The trinket goes on CD and nothing discernible happens.

**Comment by Vousalan** [comment]
I tested this in game goes on CD does nothing else does not pop as it should.

**Comment by jeyrella** [comment]
@Rushor talk to me before making any changes on this one pls

**Comment by Keader** [comment]
It has 15% chance to summon chicken... it's not 100%.

**Comment by Wowtks** [comment]
> It has 15% chance to summon chicken... it's not 100%.

Where did this come from? It's more believable if the 15% applies to the battle squawk it procs.

**Comment by Oganku** [comment]
Battle squawk functionality already works, just rarely (15% chance). The chicken popping part seems to be only the visual missing.

**Comment by Oganku** [comment]
Did some actual testing: 

-The chicken spawns on live, but only 15% of the time, which is wrong. 
-The chicken already has an erratic behavior that makes him sometimes use his abilities, and sometimes not, but he is supposed to always be spawned when you use the trinket. Overall, only some of the times he is summoned should he actually cast his squawk (which is currently correct).
-I don't see why the 15% chance to summon chicken exists at all.

So the chicken functions as intended, sometimes using his squawk and other abilities, but very randomly. He just has an added 15% probability to spawn (which is wrong)!

**Comment by jeyrella** [comment]
This is a regression of a different ticket , Janitor pls DM me if you want to discuss

**Comment by svijetlo** [comment]
@Keader  can you pls look this one bit more , trinket now spawn pet every time but i think smt is wrong as every time it got spawned gave Battle Squawk and it should not do so it should only have 15% chance to give it

**Comment by svijetlo** [comment]
chicken is now spawning every time one use trinket , 
but it also give buff every time you spawn
 and it should have only 15% to give buff 
but now it is 100% every time you use trinket as soon Chicken appears it gives buff

**Comment by Oganku** [comment]
- [x] The chicken properly spawns upon trinket use

- [ ] The chicken will never fight, even though it's supposed to act as a guardian pet. It should be set to either aggressive or defensive behavior, I can't tell which one it's meant to have.
- [ ]

**Comment by Keader** [comment]
Ok, added 50% de chance of proc
I will not script combat for it, because well.. no one give a shit for it :)
