### ISSUE TITLE
[Spell] Raise Dead (DK) pet disappears and unusable on entering vehicle

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#5659]
**Links:** https://www.wow-mania.com/armory/?spell=46585
https://www.wow-mania.com/armory/?spell=52150
 

**What is Happening:** If you enter a vehicle while you have a summoned ghoul from Raise Dead (either the [talented permanent pet](https://www.wow-mania.com/armory/?spell=52150) version or the [temporary](https://www.wow-mania.com/armory/?spell=46585) one), your pet disappears and the spell becomes greyed out, making it impossible to cast. The pet bar also disappears and /script PetAbandon() does not fix it either. You are forced to either switch talent spec, die or relog to be able to resummon it properly.

**What Should happen:** If the pet is dismissed automatically after entering a vehicle (icc cannon, wintergrasp sieges, etc.) it should behave as if the player had mounted, temporarily putting the pet away without putting the spell on cd, so that the pet comes back once the vehicle is exited.

**Comment by jeyrella** [comment]
related to https://github.com/WoWManiaUK/Redemption/issues/4712 ?  (which also uses vehicles...)

**Comment by Rushor** [comment]
Hmm i have an idea for that

**Comment by Keader** [comment]
Fixed.
And now even if it bug, u can use /reload to fix it

**Comment by svijetlo** [comment]
![WoWScrnShot_011022_152052](https://user-images.githubusercontent.com/61908373/148781168-49155213-d6e0-4d98-ace2-4913ba730355.jpg)

**Comment by Oganku** [comment]
The permanent version of the ghoul now works perfectly and disappears when mounted or in a vehicle before reappearing when you exit.

However, the temporary 1 minute companion doesn't disappear in either state. This is consistent with other temporary summons, so it seems fine.
