### ISSUE TITLE
[Quest] Argent Tournament quests

### ISSUE THREAD

**Issue by elagen** [WoWManiaUK/Redemption#566]
hi i want to do the quests but i can pick up new quests for the factions 

this is what it looks like when i go there 

https://drive.google.com/open?id=0B_GODmkO59aEQmRmZmpQUDhzbGM

**Comment by fvicaria** [comment]
Not a problem with the quest but with your reputation or quest line.

**Comment by elagen** [comment]
i have completed the quest on silvermoon and undercity and orgrimmar but i can pick up thunder bluff or zen'jin quests

**Comment by fvicaria** [comment]
Are you online now?
