### ISSUE TITLE
[NPC] Grand Magus Telestra does not use Gravity Well

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#5660]
**Links:** https://www.youtube.com/watch?v=e2OS3gr0gTU
https://youtu.be/e2OS3gr0gTU?t=92 (Gravity Well)
https://youtu.be/e2OS3gr0gTU?t=105 (Split animation)
https://youtu.be/e2OS3gr0gTU?t=137 (Merge animation)
https://www.wow-mania.com/armory/?spell=47756 / https://www.wow-mania.com/armory/?spell=47764 / https://www.wow-mania.com/armory/?spell=47765 

**What is Happening:**
1. Grand Magus Telestra never uses her [Gravity Well](https://www.wow-mania.com/armory/?spell=47756) ability.

2. Grand Magus Telestra is missing her split/merge animations, which make it looks weird, since the boss basically just vanishes and there is no indication of what's happening.

**What Should happen:**
1. She should use that spell quite early in each "main" phase. From looking at [videos](https://youtu.be/e2OS3gr0gTU?t=92 (Gravity Well)) she seems to be casting a firebomb or two, followed by the Gravity Well, about 5-10 seconds after being pulled. She also appears to only really cast it once per main phase.

2. When she splits, 3 plumes of different colors should indicate where her copies will spawn ([1:45](https://youtu.be/e2OS3gr0gTU?t=105)) and as they die, the plumes should return to a fire tornado in the center of the room, which also indicates where the boss reappears once all 3 copies are killed. ([2:17](https://youtu.be/e2OS3gr0gTU?t=137) / [0:36](https://youtu.be/CkDEzwOiUl8?t=36))

**Comment by Rushor** [comment]
1.) Gravity Well added but the jump effect is not fully working yet, that is a spell fix you might can open up for Keader
2.) fire indicators added for the splits

**Comment by Oganku** [comment]
Gravity well properly cast, it's not "throwing you" but it keeps you from moving and deals correct damage, which is fine tbh. 
Indicators work great.

**Comment by Oganku** [comment]
This fix somehow now makes Telestra take damage during the copy phase, making it possible to kill her during the second copy phase. Doing so makes it impossible for the party to loot her. She should have a damage immunity on her while absent from the field.
