### ISSUE TITLE
Skinning +queue is bugged

### ISSUE THREAD

**Issue by mo0o0oka** [WoWManiaUK/Redemption#5661]
**Links:**

i dont have a link for the bugs
**What is Happening:**
Skinning skill is broken +dung queue

**What Should happen:**

fix it asap please

**Comment by jeyrella** [comment]
Your ticket is not clear.  What do you mean?

**Comment by Rushor** [comment]
moreover it's 2 different issues in one, we do not accept such things. clear reports in single reports only
