### ISSUE TITLE
[Quest] The Hero of the Day - Missing in progress and completion text

### ISSUE THREAD

**Issue by stealer0517** [WoWManiaUK/Redemption#5663]
https://classic.wowhead.com/quest=8763/the-hero-of-the-day

When you "speak" to the Holly Preserver both the in progress, and the completion quest text are blank instead of it's correct text.

**Comment by Echinaceax** [comment]
Tested this and checked videos  

cant find an earlier video on this other than these 
2015 https://www.youtube.com/watch?v=ExQrgOLlvgY
2016  https://www.youtube.com/watch?v=KDduD3UT4Xw

There isnt meant to be any completion text and the in progress text seems fine to me 
same as both videos 

![quest text](https://user-images.githubusercontent.com/39439201/148649743-c8de421b-3850-4fdd-b227-3cc208bd9fa5.jpg)
![1](https://user-images.githubusercontent.com/39439201/148649752-09231cad-06c1-439f-9177-7b0a80f21ebf.jpg)
![2](https://user-images.githubusercontent.com/39439201/148649755-919b2a12-7cc7-4126-9c5a-fa9fa32b937c.jpg)

**Comment by jeyrella** [comment]
Same.  Can't find any evidence either on wowhead/wowpedia that there ever was any text.

@stealer0517 if you can provide reference for where you found the text, we will gladly add it, closing until then.

**Comment by stealer0517** [comment]
According to classic wowhead link above the in progress text should be: 
The "Holly Preserver" machine looks like some sort of still at first, but a careful examination of it reveals some goblin-esque changes to it.  Still, your skill at cooking seems to allow you to understand how the machine works.

There is already fresh holly in the machine - you simply need to provide some deeprock salt and five gold coins to get the machine working.

~~~~~
and the completion text should be: 
The machine lets off a little rumble and a small amount of steam as it starts working.  It is not too long thereafter until it stops, heralded by another small jet of steam erupting from it.  A door hatch opens, revealing a batch of preserved holly!

~~~~
In theory this could have been something they changed from OG vanilla wow when they released classic but I sure don't remember for sure other than the quest seeming a bit goofy being blank.

Also the music in those two videos are just perfection. It's been a while since I've watch a video like that.

**Comment by Echinaceax** [comment]
Thanks @stealer0517 yes i see it on classic wowhead

 
![prog compl](https://user-images.githubusercontent.com/39439201/148662767-c7427d08-fd25-4dc4-999f-304860a5258e.jpg)



Mania doesnt usually use classic wowhead for researching patch change info as far as I know 

its your call @jeyrella 😄

**Comment by jeyrella** [comment]
As you've inferenced yourself, "Classic" wow is not WotLK - in fact, in many regards it's not like it actually was even in Vanilla.  Lots of things were "goofy" back in the day - it's why they fixed a lot of it in Classic :-) 
We don't make changes based on Blizzard's new games.  It's also interesting that wowpedia does not list the quest completion text for pre-Cataclysm.  
Not saying you are wrong, but policy is status quo unless there is definitive/obvious data it was not like this in retail WotLK.   As mentioned though, if you/we do find proof of it being different in WotLK, we'll change it.

**Comment by stealer0517** [comment]
http://web.archive.org/web/20091208143308/http://thottbot.com/q8763

I forgot about the wonder of the internet archive. Wowhead didn't seem to have the back backed up (or their URL scheme changed) but Thottbot did, and at least in 2009 it had the same text as wow classic does today.

**Comment by jeyrella** [comment]
Ooooooooh.  I completely forgot about Thottbot too.  Nice find.  Thanks :)

**Comment by jeyrella** [comment]
@Rushor text should be as OP says in https://github.com/WoWManiaUK/Redemption/issues/5663#issuecomment-1008167821

**Comment by Rushor** [comment]
for winter veil test event can be started with: .event start 2

**Comment by Rushor** [comment]
texts added, remember to clear cache before testing

**Comment by Echinaceax** [comment]
confirmed fixed in PTR 
![fixed1](https://user-images.githubusercontent.com/39439201/149659727-6079688f-6221-4a85-8f5c-9331e69b854e.jpg)
![fixed2](https://user-images.githubusercontent.com/39439201/149659729-2b32dfbe-72b5-4852-b0d5-dfe2a1d830d6.jpg)
