### ISSUE TITLE
DK blocked

### ISSUE THREAD

**Issue by sandro1345** [WoWManiaUK/Redemption#5664]
Good Evening, here it is 2 days that I am DK lvl 65, im am Not following quest lines and possibility of leaving in malterres which really starts to bother me.

**Comment by Rushor** [comment]
please contact a gamemaster for your problem, this is nothing serverside

**Comment by sandro1345** [comment]
Where is contact gamemasters ?

**Comment by sandro1345** [comment]
I'm French so I'm struggling in English, but we'll have to sort out the
problem it's been 2 days that I can no longer do anything, otherwise I
would have to stop this server, that's not what I want

**Comment by sandro1345** [comment]
or I can contact the game masters ?

**Comment by jeyrella** [comment]
@sandro1345 If your DK is new, you need to fully complete all the quests in the starting area.
You can contact a game master in the game, by clicking on the red "?" mark on the micro-menu.  

Si votre DK est nouveau, vous devez terminer toutes les quêtes dans la zone de départ.
Vous pouvez contacter un maître de jeu dans le jeu, en cliquant sur le rouge "?" marque sur le micro
menu.
