### ISSUE TITLE
Texture Bug in Frostmourne room after consuming alcoholic beverages

### ISSUE THREAD

**Issue by theonykry** [WoWManiaUK/Redemption#5665]
**Links:**
https://www.wow-mania.com/armory/?item=40042

**What is Happening:**
After drinking Caraway Burnwine, once teleported into the frostmourne room, your character falls through the ground and after being teleported out again, you lay dead on the ground. same shit happends when your character is already drunk and your camera is at max distance. so 3 cases of it happening: your character is already drunk, you get tp'ed into room, you fall. your character is a bit tipsy, you drink, get more drunk, you fall. you are completely sober, you drink, you fall. i guess it happends with other alcoholic beverages aswell, but i havent tested that. It happend 5x times in a row and this is why im reporting it. i like to take advantage of the increased drunk max. camera distance at that particular phase of the encounter, bcs it gives you a better oversight and makes trageting the spirits easier. i tested it on a boomkin on alliance side.

**What Should happen:**
you should not fall and die when drinking alcoholic beverages.

**Comment by Rushor** [comment]
this is as is, cannot be changed
