### ISSUE TITLE
[Object] Warpwood Pod's DoT causes pet pathing issues #179528

### ISSUE THREAD

**Issue by kamoodle5** [WoWManiaUK/Redemption#5666]
https://classic.wowhead.com/object=179528/warpwood-pod

What is Happening: 
1.) They trigger a debuff called Entangling Roots when getting close/clicking on them.
2.) They spawn more Whip Lashers (https://classic.wowhead.com/npc=13022/whip-lasher) than expected at a time. In total, I've always seen eight of them appear.
3.) I observed a strange behavior from my hunter's pet whenever the pod unleashes its poison DoT. When not on passive, the pet will keep pacing back and forth towards the pod as if wanting to attack it. 

What Should happen:
1.) Entangling Roots shouldn't occur at all, since it's not mentioned in the comments below.
2.) Less Whip Lashers should be spawning at a time.
3.) Pets shouldn't behave erratically to the poison DoT). I'll post a video clip if more clarification is needed with this particular issue.

Note: Here's a relevant comment I found from another warpwood pod page (https://classic.wowhead.com/object=179526/warpwood-pod#comments):

"These little green pods are found all over DM East and do one of the following randomly when you open them/approach them:

1) Spawn little 5-6 little mobs (https://classic.wowhead.com/?npc=13022)
2) Poisons you (a nature DoT)
3) Yields either Runn Tum Tuber (https://classic.wowhead.com/?item=18255), used in the recipe Runn Tum Tuber Surprise (https://classic.wowhead.com/?spell=22761) and/or Thornling Seeds (https://classic.wowhead.com/?item=18297)
4) Does nothing at all"

When the pod triggered the Entangling Roots debuff:
![WoWScrnShot_010322_214204](https://user-images.githubusercontent.com/67519835/148015141-a4736f43-a6b0-4b04-976b-440c299a38f5.jpg)

First screenshot here shows the pod that spawned the Whip Lashers in the next screenshot. If you check out the minimap on the second image, I had my cursor hovered over one of these new groups to show their number, since they stack on top of each other.
![WoWScrnShot_010322_214010](https://user-images.githubusercontent.com/67519835/148015254-c397c264-55e2-4fb1-9536-95e66a448ed7.jpg)
![WoWScrnShot_010322_214024](https://user-images.githubusercontent.com/67519835/148015195-788c4709-2882-47ad-83bd-f97c67514d81.jpg)

**Comment by jeyrella** [comment]
Take anything you read on wowhead with a very large pinch of salt, they are not always correct/complete.
For 1) "Entangling Roots" in warpwood pods:
https://wowpedia.fandom.com/wiki/Warpwood_Pod
Watch many guides to DM, and you'll see this is correct.

For 2) will have to do more research on this, cannot immediately find a reliable corroborative source
3) does sound odd.

**Comment by kamoodle5** [comment]
I understand what you're explaining about 1, since entangling roots does seem like a normal behavior. Guess I got so annoyed getting wrapped that I wanted that debuff to disappear. For 2, again what you iterated that the comment I quoted may not be accurate on the number of Whip Lashers the pod can spawn. After all, it was the only comment with viable information and there's no video.

Just finished uploading some video evidence on Youtube of the pet behavior when the pod triggers its DoT. Here, I show that my hunter's pet doesn't react as first in passive but it will on defensive.
https://youtu.be/4nFF38mue2o

**Comment by jeyrella** [comment]
For 2), not saying you are incorrect, just that we will need more info/evidence before making changes as there is no immediately available info.  We always prefer to take the status quo until proven otherwise (on things that are possibly incorrect rather than plain broken).  We will do a bit more investigation ourselves though, and if you find anything to support a change please do post it.

Thanks for the video for 3), this is useful and interesting.  Certainly this does not look normal and will have a developer look at it.

**Comment by kamoodle5** [comment]
I discovered another issue related to the pod's poison DoT, but I am not sure whether to post it here or as a separate topic since it's a spell. What do you think?

I have found what I believe to be sufficient proof to how many Whip Lashers the pod spawns. Normally, a single group of four would appear when the pod is either being approached or clicked on. On one of my previous screenshots, you will notice two groups when I clicked on my pod. I'll post another video clip if needed.

Below is a Twitch link to someone's recent run in Dire Maul: East. Check out 19:05, 31:45, and 46:43 for when these particular pods spawn their lashers. 
https://www.twitch.tv/joardee/video/1230754317

**Comment by Rushor** [comment]
Only max 4 creatures will now be summoned by the Pod,

for the debuff issue i would suggest to make it not target pets to prevent issues? would that be ok?

**Comment by Rushor** [comment]
okay added thet the trigger that summons the debuff (invisible) is no longer attackable, that was the reason why the pet behaviour was wonky i think

**Comment by Oganku** [comment]
Maybe I'm blind, but the pods never spawn any creatures, either when touched or clicked.

**Comment by Rushor** [comment]
okay fixed, you can test it by f.ex: .go object 73489 or .go object 73494

**Comment by Oganku** [comment]
Alright, so there's 3 kinds of pods. One that casts roots, one that poisons and one that spawns adds. I'm not sure if that's intended, but the one that spawns adds spawns only 4 (every time).

**Comment by Rushor** [comment]
yeah that is correct :) 3 versions to keep it spicy :>

**Comment by Echinaceax** [comment]
> Oganku

What i noticed is that the pots that auto trigger are the only ones that spawn the Whip lasher's 
the clickable dont (same for me)
