### ISSUE TITLE
Random Heroic Dungeon Finder Not Working

### ISSUE THREAD

**Issue by Kultivater** [WoWManiaUK/Redemption#5668]
**Links:**

This is not an issue that can have citations.

**What is Happening:**

Upon joining the Random Heroic Dungeon Finder, It will show that there are 2 DPS, a tank, and a healer joined, meaning it should pop immediately after 1 more DPS joins. It doesn't, and it doesn't for anyone else. Every player in the game that I've spoken to and grouped with has this issue. The only workaround is to form a complete 5 man group(a premade) before queueing, which, of course, defeats the entire purpose of it existing.

**What Should happen:**

I don't think I need to explain to a developer what tthe RHC is SUPPOSED to do... because if I did, I'd question the reason they're a WoW developer. Anyway, you're supposed to queue, and it searches for members for you, then teleports you in once all members are found.

Reproduce simply by joining RHC and getting one more DPS to join the queue.

**Comment by Oganku** [comment]
#2536

**Comment by Kultivater** [comment]
It randomly started working again. I don't know what to say about that. You should still look into it though.
