### ISSUE TITLE
[NPC] Edwin VanCleef does not reset / glitches into terrain - Deadmines

### ISSUE THREAD

**Issue by PeterConey** [WoWManiaUK/Redemption#5669]
**What is Happening:**

We were running from Edwin in Deadmines and I was the last one. He was chasing me, then I looked back and I think he glitched in some part of the building and is still there somewhere, because my teammates were saying, that the target skull was sometimes visible.
He didn't reset back to his position it seemed, so not a respawn issue, it's a glitch caused by running away from his range. 

Thanks to everyone in the team who will work on this issue.

**Comment by Echinaceax** [comment]
npc id link https://www.wow-mania.com/page/armory

**Comment by Echinaceax** [comment]
@Rushor 

I have tried my hardest to bug the NPC 😄 

running away, jumping off, running around buildings

NPCs path is fine 
Even when i go invisible (mage spell) , he resets him path without issue

### Cant reproduce

**Comment by jeyrella** [comment]
Reopened, svijetlo may have found a way, re-testing

**Comment by svijetlo** [comment]
hmmm strange what i did before does not work anymore it just came back to his spot properly

**Comment by Rushor** [comment]
will check his ai if i find sth related to it
