### ISSUE TITLE
[Quest] The Earthbinder

### ISSUE THREAD

**Issue by Collosal1** [WoWManiaUK/Redemption#567]
Quest: The Earthbinder http://www.wow-mania.com/armory/?quest=10349

Quest Description: Take the Crimson Crystal Shard to Earthbinder Galandria Nightbreeze at the Cenarion Post in Hellfire Peninsula.

Problem: Should be simple 'Go talk to X' quest. Earthbinder Galandria Nightbreeze (http://www.wow-mania.com/armory/?npc=19294) has no '?' markings and cannot be spoken to, effectively making quest incompletable.

**Comment by fvicaria** [comment]
Fixed.
