### ISSUE TITLE
[Talent/Spell] Improved Demonic Tactics not working (Warlock)

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#5670]
**Links:** https://www.wow-mania.com/armory/?spell=54347
https://www.wow-mania.com/armory/?spell=54348
https://www.wow-mania.com/armory/?spell=54349

**What is Happening:** The talent currently grants 0% of your crit chance to your pet, no matter the rank.

Testing done:
-Naked without talent, imp had ~15% crit chance on his firebolt. 
-Naked with talent, imp had ~15% crit chance on his firebolt.
-With aura 54349 and full crit gear (1530 crit rating, 44.57% total), I would expect my pet to behave as if he had an additional 510 crit rating, which would be +15.5%. But he ended up only critting ~21% of his firebolts. This 6% discrepancy is consistent from the Intellect gained from equipping the gear. His Int without gear was granting him 3.88% crit chance, but with gear it grants him 9.04%, for a total differece of 5.16%. The number is a little off, but the numbers are still very close, which I consider to be accurate considering my sample size was only 100 firebolts per test.

*All tests were done with a sample size of 100 firebolts.

**What Should happen:** The talent should grant your pet 10/20/30% of the caster's critical strike chance.

**Comment by Keader** [comment]
try now pls

**Comment by svijetlo** [comment]
looks fine to me but i would like if some one who know more on warlock to try this one out also
