### ISSUE TITLE
[Spell] Raise Dead does not attack if summoned during combat.

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#5671]
**Links:** https://www.wow-mania.com/armory/?spell=46585

**What is Happening:** The 1 minute temporary version of [Raise Dead](https://www.wow-mania.com/armory/?spell=46585) (without the Master of Ghouls talent) does not attack at all if summoned during combat. 
If summoned before combat however, it will attack the first target engaged.
Since this ghoul scales with its master's stats, you generally want to wait for procs to summon it, a few seconds into the fight, but right now doing so results in a wasted gcd.

Evidence: https://imgur.com/a/biTID2h

**What Should happen:** The ghoul, even though it isn't a fully functional pet, should still attack the dk's current target even if summoned during combat, similar to how other such pets behave.

**Comment by Keader** [comment]
test now

**Comment by svijetlo** [comment]
it will attack now no matter when you summon in even if you do it mid fight and with procks for max efect
