### ISSUE TITLE
[Quest/Event] Last Rites compendium

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#5672]
**Links:** https://www.wow-mania.com/armory/?quest=12019
https://www.wow-mania.com/armory/?npc=26170
https://www.wow-mania.com/armory/?npc=28189

**What is Happening:** 
1- Thassarian dies and is put back to his original position after completing the event/quest, but he then paths a few degrees off the intended path, which fails to trigger the event. This wrong position might be due to incorrect movement during the RP or to a wrong flag (see Unit Flags 2: 2048 vs 4196352)
2- Valanar ([Shadow Bolt](https://www.wow-mania.com/armory/?spell=9613), [Soul Blast](https://www.wow-mania.com/armory/?spell=50992), [Soul Deflection](https://www.wow-mania.com/armory/?spell=51009)) and Thassarian ([Empowered Blood Presence](https://www.wow-mania.com/armory/?spell=50995#)) are both missing their spells. 
3- Leryssa despawns rather quickly, sometimes making it so Thassarian is talking to himself during the final part of the RP.
4- Our Armory has some odd coordinates for Thassarian when compared to wotlkdb/wowhead. (Might cause #1)
5- Valanar is missing his loot table 
6- Thassarian is facing 180 degrees away from Leryssa during the final RP.

**What Should happen:** 
1- _Thassarian seems to be very slightly mispositioned after being respawned, which is enough to make the quest just fail the following time and requiring a manual reset from a GM. The NPC reset on top of Naxxanar should therefore be reviewed._
2- Their respective spells should be used. 
3- Leryssa should despawn after maybe 5 minutes instead of the current 150 seconds, considering the length of the event + fight.
4- Double-check armory coords.
5- Valanar's loot table should be added.
6- Thassarian should face the correct way.

Note that point #1 is by far the most important and that the following issues stated are mostly minor compared to it.

**Comment by Rushor** [comment]
>Thassarian dies and is put back to his original position after completing the event/quest, but he then paths a few degrees off the intended path, which fails to trigger the event.

Is this always happening after someone completed the quest?

**Comment by Oganku** [comment]
This happens every single time the final part of the rp concludes. So to reproduce 100% of the time, you just do the quest normally.

For the player, Thassarian seems to just slowly fade out and disappear, but with gm on, you can see him getting teleported back to his starting position and dying.

**Comment by svijetlo** [comment]
https://www.youtube.com/watch?v=wx4XEnUkGhk&ab_channel=MichaelHsiao OLDEST VID OF HOW IT SHOULD LOOK I FOUND 
also if you fail quest or abandon it and go back to tower to retake quest ones you go to naxxanar npc wont be there to start RP 
ones you do quest he does stand with his back to Leryssa
also if you do not give in quest at top of naxxanar he will despawn ones rp is over and you have to go back to tower to give in quest , he should be on top till you finish quest then reset back to original spot

**Comment by Oganku** [comment]
Him despawning at the end of the RP is normal, and since both NPCs are the same (on top of Naxxanar and below), it's your fault if you didn't hand in the quest up to that point and you should just go talk to him on the ground.

**Comment by svijetlo** [comment]
yes but here he despawns way to fast  imo , and then if other person stat quest down there in tower it can bug out returning i think that also bug RP in quest if you fail it or abandon and retake

**Comment by Rushor** [comment]
1- XXX
2- XXX
3- Leryssa will despawn after maybe 5 minutes instead of the current 150 seconds, considering the length of the event + fight. Same despawn as Thassarian and General Arlos at the end of the event.
4- armory coords i cannot fix, that is Janitor thing
5- Valanar's loot table i will not add, since the event is explaitable (can be done over and over again)
6- Thassarian will face the correct way now. as soon as the says "Leryssa are you alright?" he will face her

**Comment by Oganku** [comment]
Everything now works well.
