### ISSUE TITLE
Warlock's Fire Imp won't attack

### ISSUE THREAD

**Issue by moenbase** [WoWManiaUK/Redemption#5673]
[**Links:**](http://www.wow-mania.com/armory?spell=688)

Created a Warlock. Buy the Summon Fire Imp spell.
Set the Imp at Agressive.
Attack a target.
The Imp runs to the target. 
The attack command is flashing.
But it doesn't do anything.
Only manually inputs will allow the Imp to cast a fireball.

The Imp should attack the selected target.

**Comment by jeyrella** [comment]
Can't reproduce, works perfectly on both live and PTR.

What is your client number?  (post a screenshot of your login page)
Using launcher?  Cleared cache?

Most likely you will need to contact a Game Master in game for this, as this does not seem like a code issue.

**Comment by moenbase** [comment]
Hi Jeyrella,

My client number is as suggested:
WoW mania: 2.9.4

The launcher and it’s files come from the WoW Mania website. Downloaded as a torrent.


See attached screenshot.
wow screen.jpg

***@***.***


I cleared the catche as well.
Same result.
Also tried a few other races. Human and Gnome. No difference.


I noticed that in follow mode, the Imp won’t attack.
Even though the Attack button of the Imp is either manually pressed. The attack button is flashing, but nothing happens.

***@***.***



If I choose for Stay mode when selecting attack, the Imp will attack.
But will stay on the spot. And it also won’t use the Fireball.

***@***.***


Hope this helps.





Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by Oganku** [comment]
This issue sounds oddly similar to the one I just created yesterday for DK pets (#5671). I suppose it's the same behavior that is reproduced with a real pet when set on aggressive.

**Comment by svijetlo** [comment]
can not reproduce works fine to me

**Comment by moenbase** [comment]
Hello everyone,

Thank you for testing and confirming this works as intended.
It seems the mistake is on my side.
As default the Imp is set as not using the fireball. When right clicking the skill, some glow will circle around the icon.
This seems to activate the skill for the pet.
When I attack a creature now, the Imp will keep using it’s fireballs on him.

Sorry to waste your guys time. But thank you for confirming that it works as intended.
I  think this ticket can be closed.
Have a great day.


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows
