### ISSUE TITLE
Quest Bug Mission: Possible But Not Probable

### ISSUE THREAD

**Issue by rpcon** [WoWManiaUK/Redemption#5674]
**Links:**
[wowhead link](https://www.wowhead.com/quest=2478/mission-possible-but-not-probable)

**What is Happening:**
Opening with Ambush or Garrote on either of the Mutated Venture Co. Drones just inside the tower on the main floor successfully auto-kills it, but will not give credit toward quest completion. Any further kills of the same mob type also does not give credit (I went through 2 respawns to be sure).
Killing both mobs without a stealth opener (i.e. just melee) allows quest completion.
Also, after abandoning the quest, I was unable to use Fizzule's Whistle to make the quest npc non-hostile to re-acquire it.

**What Should happen:**
Opening from stealth using Ambush should give credit toward finishing the quest.
After abandoning the quest, using the whistle should allow the npc to become green and offer the quest again.

**Comment by Echinaceax** [comment]
Thanks @rpcon for explaining how to reproduce this bug (i did yet this without using ambush (which works)

- [ ] But confirmed no quest credit given if using Ambush
  
![ambush](https://user-images.githubusercontent.com/39439201/148930252-a42948da-e7a6-40c7-9713-558ba3958c5a.jpg)
![confirmed](https://user-images.githubusercontent.com/39439201/148930288-37decbd8-91bc-4cef-923c-0b3275d8b17c.jpg)

**Comment by jeyrella** [comment]
yup and commentary from https://www.wowhead.com/quest=2478/mission-possible-but-not-probable makes no mention of this, which given it's a staple rogue skill, it absolutely would.

**Comment by Rushor** [comment]
rank 8-10 were missing

**Comment by Rushor** [comment]
all missing ranks added

**Comment by Echinaceax** [comment]
confirmed fixed in PTR  tested also ranks 7, 8, 10

![comfirmed3](https://user-images.githubusercontent.com/39439201/149659398-dfb5d49e-c964-4a4c-9f85-c0ee5305bc6d.jpg)
