### ISSUE TITLE
[Raid/Event] Crok Scourgebane & Frostwing Halls - Crok missing RP protection causing Svalna to be unattackable

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#5677]
**Links:** https://www.wow-mania.com/armory/?npc=37129
https://www.wow-mania.com/armory/?npc=37126

**What is Happening:** Crok's RP can currently be interrupted if the Frostwing Halls adds are pulled to him before he finishes talking and paths to the adds himself. This causes him to reset to his initial position once these adds are dead, but he then does NOT resume or restart his RP and will just chill there forever. 

Trying to manually pull adds on Crok to put him back in combat and drag him back into the hall will not fix the issue and it generally requires a GM to simply kill [Sister Svalna](https://www.wow-mania.com/armory/?npc=37126) in order to progress through the raid.

**What Should happen:** There should be some sort of protection in case Crok's RP gets interrupted to ensure he will still properly trigger Sister Svalna. It could be a simple check every ~30s after his RP started to see if he's doing anything, if not, re-start it or something similar. 

Considering this event can soft-lock the raid, it is somewhat significant, hence the Priority - High.

**Comment by jeyrella** [comment]
I seem to remember the protection was that the mobs could not be engaged before his RP finished.  Need to research more

**Comment by jeyrella** [comment]
only confirmed video I can find is https://www.youtube.com/watch?v=dYXY7QsAI98 , which is inconclusive

**Comment by Oganku** [comment]
From https://youtu.be/leynpGTkq2M?t=126 we can see that you can definitely attack them while RP is happening, and the mobs are even supposed to run at you (which isn't the point of this report though). You can slow it down to 0.25x to see better.

It's surprisingly difficult to find other videos of that specific part, but any fix that would prevent the soft-lock would be good imo.

**Comment by Rushor** [comment]
i agree, a solution to fix the main problem would help and may prevent gms from further tickets.

what would be a good option? Setting the adds unattackable until crok moves forward into the hall?

**Comment by svijetlo** [comment]
https://www.youtube.com/watch?v=JZTuD2JSBEI&ab_channel=JosephMills 
even thos this vid is form 2012 , raid it self did not change to this day , 
how it goes was, ones you arrive to him he would start to talk , on ground next to him are allready two dead mobs , while he speaks mobs in hallway run down to fill hall (as can be seen in video )
as soon he finish RP he will run to mobs and start fight , mobs can not be attacked till rp is on

**Comment by Rushor** [comment]
Alright so i will add the Part of the Mobs beeing unattackable. Thanks for Research!

Svalna beeing on ground can also be added

**Comment by Rushor** [comment]
alright the trash is now only attackable one crok started it's path

svalna is only attackable one crok reached his last waypoint

svalna should also be stay on ground when her combat event starts

**Comment by Oganku** [comment]
There are still a few seconds in between when Crok actually starts moving and the adds become attackable. 
Knowing this, I did my best to bug Crok, but I still wasn't able to. So the issue appears to be solved!

**Comment by Rushor** [comment]
yeah that few seconds were there before aswell, it thinks it's okay :) Thanks for the tests!

**Comment by jeyrella** [comment]
Reopening as this is happening again; regression/reversion.

**Comment by Rushor** [comment]
@jeyrella Same reproduce case as before?

**Comment by svijetlo** [comment]
> @jeyrella Same reproduce case as before?

yes

**Comment by Rushor** [comment]
they are unattackable for me until he starts the run event

in the beginning: https://i.imgur.com/JvSAM6z.jpeg 

after the events started: https://i.imgur.com/FV4cwiZ.jpeg

**Comment by GMZinius** [comment]
Fix confirm on PTR 
Fix on live with next update

**Comment by svijetlo** [comment]
> Fix confirm on PTR Fix on live with next update

this bug is also back it happened to us on Friday, trash can be pulled and killed before he does/ends talk then he will not go in to hallway and event will not happen so you can not kill mini boss and open doors for 1st boss in frost quarters

**Comment by GMZinius** [comment]
@Rushor Can you ask Janitor to run the code again please, it was fine on PTR earier while I was on other test
