### ISSUE TITLE
[NPC] Southsea Freebooter continue attacking when CC'd- Tanaris

### ISSUE THREAD

**Issue by bloou2** [WoWManiaUK/Redemption#5679]
**Links:**

**What is Happening:**
i was there doing quests, and i discovered when you fear the southsea freebooter´s they dont get cc´ed they will wonder around in the fear and keep shooting at you so if you just get aggro of one of them and try to fear them they just keep shooting at you. i am an warlock. and i dont know if it happens to other classes/cc´s

**What Should happen:**
they should get feared :P

**Comment by Echinaceax** [comment]
@bloou2 
What level are you and what rank of "fear" are you using atm so we can check this out for you?

**Comment by Echinaceax** [comment]
Confirmed without extra player info 

Once player has Feared the reported npc the npc still shoots are player while fear is active 
my video https://gyazo.com/63a03705b9d54928708da1a4bf2519c9

**Comment by Oganku** [comment]
Confirmed for Fear and Psychic scream. Couldn't use a bow on my warlock but I lazily suppose it's also fixed. If you wanna double-check, feel free to.

**Comment by Echinaceax** [comment]
Hunter (Wyvern sting)  still bugged and lost bow animation

**Comment by Rushor** [comment]
needs make sure that damage effect does not cancel the stun, works for me https://gyazo.com/591646aaa3d2577c97b8900f6b86bfc3

**Comment by Echinaceax** [comment]
> needs make sure that damage effect does not cancel the stun, works for me https://gyazo.com/591646aaa3d2577c97b8900f6b86bfc3
> 
> for the other pirates it should be fixed now too

that the thing, if "sleeping shouldnt take damage (i had pet on passive) so no damage was giving to break sleep 

Will test again now

**Comment by Echinaceax** [comment]
- [ ]  Hunter (Wyvern sting) and lost bow animation

![image](https://user-images.githubusercontent.com/39439201/150774148-f922788e-7645-4a0c-8d12-1466c3843455.png)

Made new Hunter char for this test
