### ISSUE TITLE
Problem with Engineering proffesion

### ISSUE THREAD

**Issue by Psybrain6** [WoWManiaUK/Redemption#5680]
**What is Happening:**
I cant make item "goblin mortar".. i have  Engineering skill on 225
![WoWScrnShot_012022_213544](https://user-images.githubusercontent.com/98125067/150418023-33b7626f-79be-4d04-bc95-14f465d5eee8.jpg)

**Comment by Oganku** [comment]
Being part of vanilla, it requires Goblin engineering to actually craft. Ahhh the joys of classic... Am I right?

**Comment by Echinaceax** [comment]
> Being part of vanilla, it requires Goblin engineering to actually craft. Ahhh the joys of classic... Am I right?

Yes just found this info too 

https://classic.wowhead.com/spell=12716/goblin-mortar#comments

**Comment by WhitephoenixTheBunny** [comment]
I know I come here WAY late, but is that related to https://github.com/WoWManiaUK/Redemption/issues/4400 ?

**Comment by jeyrella** [comment]
No.  OP did not have Goblin specialisation of Engineering, which the item requires (albeit, the tooltip is not clear in this regard)
