### ISSUE TITLE
[Boss/Ability] The Lurker's Below (Spout + Phase 2)

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#5681]
**Links:** https://wowwiki-archive.fandom.com/wiki/The_Lurker_Below
https://www.wow-mania.com/armory/?npc=21217
https://www.youtube.com/watch?v=JhWuAKAwTaw
https://www.wow-mania.com/armory/?spell=37433
https://www.wow-mania.com/armory/?npc=21865
https://www.wow-mania.com/armory/?npc=21873

**What is Happening:** [The Lurker Below](https://www.wow-mania.com/armory/?npc=21217)'s fight is sort of scuffed currently. In most cases, it doesn't prevent him being killed if you manage to have enough players to kill him before he starts casting [Spout](https://www.wow-mania.com/armory/?spell=37433). The spell itself behaves properly (damage/knockback), but the boss is missing the script that's supposed to go along with it, so he constantly blasts his main target with this deadly ability, killing them extremely quickly (it deals 4k damage every 0.25s). During the entire duration of the spout, he will stay locked on his primary target and follow them no matter how quickly they move.

Also the boss is completely missing his phase 2 where he's supposed to submerge after a while and some adds spawn before he returns.

**What Should happen:**
[Spout](https://www.wow-mania.com/armory/?spell=37433) is a twilight cutter-like ability, in the sense that you are NOT supposed to be hit by it, or it very likely means death. Once the warning message that the boss is about to unleash his attack happens, the boss should "lock" to his currently facing position and beging casting Spout, after which he will do a scripted slow ~400 degree rotation. This makes the beam be predictable and allows players to jump in the water to avoid the damage when it's about to pass over them.

After 120 seconds of phase 1, the boss is supposed to submerge and spawn 6 [Coilfang Ambushers](https://www.wow-mania.com/armory/?npc=21865) and 3 [Coilfang Guardians](https://www.wow-mania.com/armory/?npc=21873) at specific, pre-determined positions. After 60 seconds of being submerged, the boss resurfaces (no matter if the adds were killed or not) and will immediately cast a new Spout.

Evidence from retail video: https://www.youtube.com/watch?v=JhWuAKAwTaw

**Comment by Rushor** [comment]
The current script was too overloaded with old mechanics that partly break important mechanics like the spawn of the adds.

Worked some hours now on a clean solution - please test this very intense, so that no bugs are left @TesterGroup

**Comment by Rushor** [comment]
https://i.imgur.com/xgW8UaZ.jpeg https://i.imgur.com/KPkQieJ.jpeg

**Comment by Oganku** [comment]
- [ ] Spout works well: You can avoid it in water, it properly spins and doesn't lock on anybody making it undodgeable.
- [ ] Phase 2 works well, adds spawn and the boss comes back after a timer. Boss also keeps his hp from phase 1.
- [ ] While testing I noticed an annoying behavior that if there was no targets in melee range of him (all raid in water or out of melee range), the boss would simply despawn. However, he should be casting [Water Bolt](https://www.wow-mania.com/armory/?spell=37138) very rapidly under these circumstances, which would quickly wipe the raid, but also not cause him to instantly despawn. It's possible that while dodging the spout, all players will be in the water at the same moment, and we don't want the fight to reset for that.

**Comment by Rushor** [comment]
I don't like this boss, but should be resolved now. The boss will only despawn if all players in the instance are dead. Else he will keep alive and spawned. He will also cast the Water Bolt if no target is in range.

https://i.imgur.com/Fcggy3t.jpeg
https://i.imgur.com/ig8n81B.jpeg

**Comment by Rushor** [comment]
added that no more fish spawns when lurker was killed

**Comment by Oganku** [comment]
If the aggro target is out of range AND in water, he will not cast water bolt at them. As soon as I jump out of water he casts it, but in water he ignores me. Other than that, everything looks good.

**Comment by Rushor** [comment]
fixed that https://i.imgur.com/px0mE0J.png

**Comment by Oganku** [comment]
Looks good! Also now lootable when he dies since he falls on the platform. 🥳
