### ISSUE TITLE
[Boss/Spell] Sartharion's Flame Tsunami missing its knockback effect.

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#5682]
**Links:** https://github.com/azerothcore/azerothcore-wotlk/issues/2891
https://www.wow-mania.com/armory/?spell=57491
https://www.wow-mania.com/armory/?spell=60241
https://youtu.be/iJJ4hhL9DU0?t=442
https://www.eurogamer.net/articles/world-of-warcraft-dragons-raid-guide-article

**What is Happening:** The exact issue mentioned [here](https://github.com/azerothcore/azerothcore-wotlk/issues/2891) is happening on Redemption. Sartharion's Flame Tsunami's ability applies its [damage component](https://www.wow-mania.com/armory/?spell=57491) correctly, but is missing the [knockback](https://www.wow-mania.com/armory/?spell=60241) that should be associated with it.

**What Should happen:** All of the evidence necessary should be present in the github post linked above. Other sources of evidence for the knockback component are: 
https://youtu.be/iJJ4hhL9DU0?t=442
https://www.eurogamer.net/articles/world-of-warcraft-dragons-raid-guide-article

**Comment by Rushor** [comment]
https://www.wowhead.com/spell=60241/flame-tsunami should now be casted by the Tsunami trigger every 3 seconds to the closest player within 5 yards range

**Comment by Oganku** [comment]
Errr, it looks like the knockback applies to the tsunami itself. 😅 
https://imgur.com/a/oSHvs9p

**Comment by Rushor** [comment]
alright next try - target should be player now

**Comment by jeyrella** [comment]
> Errr, it looks like the knockback applies to the tsunami itself. 😅 https://imgur.com/a/oSHvs9p

lol that's just funny :D    $10 if you leave that in ;)   It brings a new twist to that mechanic!

**Comment by Oganku** [comment]
The knockback feels very small, and only works if you're jumping for some reason. It also knocks you back in the direction you're facing. Needs more testing ideally.

**Comment by Rushor** [comment]
knockback should be better now https://gyazo.com/c18d9dd0a945e65e524e75e8435e3a71

**Comment by Oganku** [comment]
Knockback looks good. However it doesn't occur if the player is moving when hit by the debuff. If I walk through the wave, I never get knocked back, but when I let myself get hit, it works properly.

**Comment by Rushor** [comment]
okay it seemed to be related to the knockback effect range, increased that so the knockback will always happen

**Comment by Oganku** [comment]
Hits from further away (still very reasonable) but won't hit while moving. As-is for that part. 👍
