### ISSUE TITLE
[Boss] Ley-Guardian Eregos despawning permanently

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#5683]
**Links:** https://www.wow-mania.com/armory/?npc=27656
https://www.wow-mania.com/armory/?spell=49838

**What is Happening:** If someone tags Eregos with a spell without directly aggroing him (happens quite easily with [Stop Time](https://www.wow-mania.com/armory/?spell=49838)), he will just despawn at the end of the stun and never come back, leaving the group stranded in an un-completable dungeon.

**What Should happen:** Eregos should not just despawn...? Under any conditions in fact.

**Comment by Rushor** [comment]
should be fixed now, no longer strange despawn

**Comment by Oganku** [comment]
Perfect! Also prevents him from despawning after wipes.
