### ISSUE TITLE
[AI] Mob Targets Player Upon Respawning

### ISSUE THREAD

**Issue by kamoodle5** [WoWManiaUK/Redemption#5684]
This bug falls on multiple mobs throughout the world. Links posted below are some mobs I noticed exhibit this strange behavior, and likely there are more. I am open to assist by finding these mobs if needed.

https://tbc.wowhead.com/npc=20444/angorosh-shadowmage
https://tbc.wowhead.com/npc=533/nightbane-shadow-weaver
https://tbc.wowhead.com/npc=11881/twilight-geolord
https://tbc.wowhead.com/npc=18037/warmaul-warlock

What is Happening: Whenever a mob respawns, it will immediately target the player (but not attack) that killed it before. This causes the mob to keep observing the player no matter where they go; they are even able to detect players in stealth. As far as I know, only certain spellcasters display this behavior (no melee or hunter-ranged yet, perhaps), although the Twilight Geolord has no mana. I also found relogging does not revert this behavior.

What Should happen: This AI behavior shouldn't happen at all. Each spawn should be just as oblivious to a player's presence as the first.

The video posted below is my observation of how a Warmaul Warlock watches me everywhere I went after it respawned. In the beginning, this is the first time I kill the mob; skipping to 6:20, it reappears. Since I have "target of target" enabled on my UI frames, you'll see that the mob has me targeted.

https://youtu.be/SaNCRlekhEc

**Comment by wow-mania** [comment]
As-is
