### ISSUE TITLE
[Quest] The Wrath of Neptulon - Maws should not swim in mid-air

### ISSUE THREAD

**Issue by svijetlo** [WoWManiaUK/Redemption#5685]
**Links:**
http://www.wow-mania.com/armory?quest=8729
http://www.wow-mania.com/armory?item=21136
https://www.youtube.com/watch?v=ub1YO_s2nDI
**What is Happening:**
![WoWScrnShot_012322_000153](https://user-images.githubusercontent.com/61908373/150996336-a2cb9114-b76c-4536-af29-5af383aa9e5a.jpg)
![WoWScrnShot_012322_000006](https://user-images.githubusercontent.com/61908373/150996356-4c9b8449-6c16-4568-b310-606982e3da8b.jpg)
-ones player come to swirling maelstrom in Azshara and use Arcanite Buoy boss spawn way to far from spot 
as seen in img spot is in green circle
- swirling maelstrom is not physical object player can stand on to fight boss 
-ones boss spawns he floats in air not in water

**What Should happen:**
-boss need to spawn close to  swirling maelstrom 
-boss need to be swimming in water not float in air 
-swirling maelstrom need to be physical object player can walk on not that they fall in water

**Comment by Rushor** [comment]
will spawn correctly now and do a little path upon spawn

**Comment by Rushor** [comment]
i don't think the players can stand on the object, they always have a shaman that buffs "Water Walking" like see in https://www.youtube.com/watch?v=0dWui-qNSzY

everything else is fixed, the boss swings in water, only when attacked he emerges a bit, but that's fine if compared to https://youtu.be/0dWui-qNSzY?t=96

**Comment by svijetlo** [comment]
looks fine now he is not awey to be almost out of view , and he is not looking he he fly over water
