### ISSUE TITLE
[Quest] The Nightmare's Corruption - Fragment drop rate too high

### ISSUE THREAD

**Issue by svijetlo** [WoWManiaUK/Redemption#5686]
**Links:**
http://www.wow-mania.com/armory?quest=8735
http://www.wow-mania.com/armory?item=21147
http://www.wow-mania.com/armory?item=21148
http://www.wow-mania.com/armory?item=21146
http://www.wow-mania.com/armory?item=21149
**What is Happening:**
During the quest ID 8735 all fragments of nightmare corruption have 100% drop rate , while in all guides and how all data point that drop rate should be 5% for item ID 21147, 21148, 21146

**What Should happen:**
items ID 21147, 21148, 21146 need to be 5% drop rate form elite mobs around Dream portals 
item ID 21149 must be 100% drop rate as it drop in Duskwood from mini boss Twilight Corrupter http://www.wow-mania.com/armory?npc=15625

P.S. could not find any old video of quest

**Comment by Rushor** [comment]
if compared with wowhead comments this is valid info

**Comment by svijetlo** [comment]
wont post ss of vid as it is poain but as i seen it drop is much much lower did not count or do maths as it can be luck also but it is fine , i got one in Ashenvale on 5th kill, Feralas took around 30 kills and Hinterlands i got bored of trying to get it drop almost
