### ISSUE TITLE
Red 'blur' when looking in certain direction

### ISSUE THREAD

**Issue by Sofie10** [WoWManiaUK/Redemption#5687]
**Links:**
![Schermafbeelding 2022-01-29 om 18 11 41](https://user-images.githubusercontent.com/98659551/151670789-8b348cef-3882-455b-b96b-af4df2e5b29d.png)
![Schermafbeelding 2022-01-29 om 18 15 40](https://user-images.githubusercontent.com/98659551/151670802-a5f72838-d2fa-4409-a243-bd9b13787d4b.png)

**What is Happening:**
I can run the game easily however, whenever I am looking in a certain direction I see those red stripes, sometimes completely covering my screen. This is caused by the direction I am looking into, not for example whenever I get attacked. Whenever I look away the red 'blur' is gone. 
Next to directions I am looking into, it is also more present in certain area's. 

**What Should happen:**
I should not see such blur in that moment, I sometimes cannot see many things in the game. 
Does not go away whenever I restart the game. 

Let me know if you need any more information

**Comment by Sofie10** [comment]
![Schermafbeelding 2022-01-29 om 18 30 34](https://user-images.githubusercontent.com/98659551/151671061-5caae673-b21e-4c6c-9902-97a45d3b5d20.png)
Also there when I am ghost

**Comment by Sofie10** [comment]
And some extreme
![Schermafbeelding 2022-01-29 om 18 43 24](https://user-images.githubusercontent.com/98659551/151671517-b175ce09-65d3-499a-a4ea-c6adee039c0c.png)
s

**Comment by Rushor** [comment]
Please re download the client with the correct patch from the website. This is not a server side issues, so it we be closed here

https://wow-mania.com/start

**Comment by jeyrella** [comment]
@Sofie10 For expanding on what Rushor said, something is wrong with the client you are using, and you should install from the link he provided.  If you need GM support to install, quickest place is on the wow-mania discord https://discord.com/invite/72zQwMGn
You can also send an email to support@wow-mania.com if you end up really stuck

**Comment by Sofie10** [comment]
Thank you, I am looking for what is going wrong, probably it has something to do with trying to run this on my Macbook.

**Comment by Oganku** [comment]
seems like a potential driver missing 👀
