### ISSUE TITLE
[NPC] Master's Training Dummy in cities are Friendly

### ISSUE THREAD

**Issue by svijetlo** [WoWManiaUK/Redemption#5689]
**Links:**
N/A

**What is Happening:**
two Master's Training Dummy in Ironforge are friendly to alliance players 
![WoWScrnShot_013122_201338](https://user-images.githubusercontent.com/61908373/151857868-78cd4c6a-fc63-4bfe-88a9-28f911256376.jpg)
![WoWScrnShot_013122_201346](https://user-images.githubusercontent.com/61908373/151857881-e9567002-898e-431c-b4f7-0368d2ff52db.jpg)
P.S. after relog etc still same.
**What Should happen:**
training dummies in your fraction city should not be friends with you you have to beat them up

**Comment by Echinaceax** [comment]
ORG got 4 friendly Master's Training Dummies

![image](https://user-images.githubusercontent.com/39439201/151868098-b04a619b-6e3c-4c92-8153-75f10eae61c1.png)

**Comment by Echinaceax** [comment]
Undercity too 

![image](https://user-images.githubusercontent.com/39439201/151869356-4b7ae6fe-cc13-4bb8-bf01-0ccc2a1e9d62.png)

**Comment by Echinaceax** [comment]
Thunderbluff 

![image](https://user-images.githubusercontent.com/39439201/151870058-09446407-d5f7-4743-8610-aa522b1950a3.png)

**Comment by Echinaceax** [comment]
Silvermoon 

![image](https://user-images.githubusercontent.com/39439201/151871984-049ebf74-b90f-4cd8-b330-0d8935051371.png)

**Comment by Echinaceax** [comment]
The Exodar

![The Exodar](https://user-images.githubusercontent.com/39439201/151874924-50557125-9f40-4214-947a-835ec9c6d39f.jpg)


Darnassus

![image](https://user-images.githubusercontent.com/39439201/151875056-2f75f091-2047-4a86-81cf-34dac542680e.png)

Stormwind

![image](https://user-images.githubusercontent.com/39439201/151875165-e72f2b1d-7cbf-46a1-9871-6451bea4aa48.png)

**Comment by svijetlo** [comment]
after short investigation we can see every city has this , i think it happened sometimes today after crash as in morning and yesterday it was fine

**Comment by Rushor** [comment]
Will check

**Comment by Rushor** [comment]
fixed, all dummies schould be normal like the others again
