### ISSUE TITLE
Vote Points

### ISSUE THREAD

**Issue by Graydown** [WoWManiaUK/Redemption#5690]
**Links:**

**What is Happening:**
When on the Site wow-mania i voted from Friday 28 january 2022 and only received 1 vote point???? same thing for Saturday and Sunday and again today 31 January 2022??6 what s going on my Char is in Redemption realm Drakkor. If i understand correctly i should have gotten dbl Points for Friday-Saturday and Sunday 36 points in total plus 5 that i did not get today????making total of 41 i have spent money on the site for VIP, Coins for Points and i would just like to get this issue lookked into and replied with a solution

**What Should happen:**

**Comment by svijetlo** [comment]
sadly server can not help with that
vote are not form server directly like VIp tokens etc,
what you should do is try vote over mobile phone android or ios device and do it every day at same time more or less
