### ISSUE TITLE
[NPC] Teller Plushner in incorrect position - ID 30607

### ISSUE THREAD

**Issue by WhitephoenixTheBunny** [WoWManiaUK/Redemption#5691]
The banker[ Teller Plushner](https://www.wow-mania.com/armory/?npc=30607) as been rioting against his labor and went to the wall as protest and can't be target.
He should be stand at his nice "jail" and be targetable... We miss him!

![image](https://user-images.githubusercontent.com/31921098/152162695-5b1cc36d-beb4-484f-a5d3-4eef8e0fae56.png)

**Comment by Echinaceax** [comment]
Confirmed on PTR 

![image](https://user-images.githubusercontent.com/39439201/152165765-011fe249-c911-4ba6-877a-98d2af94fa27.png)

**Comment by Rushor** [comment]
Well it was never fixed before. Will check

**Comment by Oganku** [comment]
Same as 5657

**Comment by Rushor** [comment]
okay should be fixed now, was invalid map position

**Comment by Echinaceax** [comment]
nice 😄 

![image](https://user-images.githubusercontent.com/39439201/152652125-44971e8b-7776-4f5e-9b5c-81b307384d2c.png)

**Comment by Rushor** [comment]
Yay
