### ISSUE TITLE
[Death Knight] Shadowmourne - Soul Fragment procs

### ISSUE THREAD

**Issue by festerhowl** [WoWManiaUK/Redemption#5693]
**What is Happening:** 
Spells are currently generating soul fragments as below:

Icy Touch: 0
Plague Strike: 0-1
Blood Strike:  0-1
Scourge Strike: 0-1
Death Strike: 0-1

**What Should happen:** 
Above spells should generate soul fragments as below:
https://worldofwarcraft.fandom.com/et/wiki/Shadowmourne
![image](https://user-images.githubusercontent.com/43633844/152660541-4f56c59c-205c-4fa3-8dd2-54285353e578.png)

**Comment by jeyrella** [comment]
Source is not reputable.  That is not the official fandom page, is an Estonian translation of a deprecated site.  No edit history is available.  Confirm this from a reputable historic source and we'll look at it.

**Comment by festerhowl** [comment]
https://wowwiki-archive.fandom.com/wiki/Shadowmourne

![image](https://user-images.githubusercontent.com/43633844/152661768-644a33bc-4386-49fe-b1b4-bce4c7830e83.png)

**Comment by jeyrella** [comment]
Again, you've taken data from today's status, not as it was in 2009.  Soul fragments are generated on procs per minute basis in WotLK, **not** absolute melee hits.  This has been discussed in several other previous (also closed) tickets.
