### ISSUE TITLE
[NPC] Delmanis the Hated doesn't path - 3662 - Darkshore

### ISSUE THREAD

**Issue by jeyrella** [WoWManiaUK/Redemption#5694]
**Links:**
https://wow-mania.com/armory/?npc=3662
https://wowpedia.fandom.com/wiki/Delmanis_the_Hated
https://classic.wowhead.com/npc=3662/delmanis-the-hated

**What is Happening:**
Delmanis the Hated doesn't currently path, just stands there like a lemon.
![image](https://user-images.githubusercontent.com/46089380/152679309-30c39483-2572-4804-b101-91eb5019fa0f.png)

**What Should happen:**
He was infamous in Darkshore around the quest hub in the north, as he both pats silently and hits hard (like, Felreaver)
![image](https://user-images.githubusercontent.com/46089380/152678850-d9c367f7-f678-4bdd-9bbb-94a46b80aff0.png)
![image](https://user-images.githubusercontent.com/46089380/152678909-26aeb668-73d1-4fe3-8714-988af36c0d1f.png)

**Comment by Rushor** [comment]
fixed

**Comment by Echinaceax** [comment]
Confirmed fixed in PTR 

![image](https://user-images.githubusercontent.com/39439201/153223113-596f83ce-9441-4690-b778-98f73a1928d2.png)
