### ISSUE TITLE
[NPC] Prince Raze 10647 drops Branch of Cenarius - Felwood

### ISSUE THREAD

**Issue by jeyrella** [WoWManiaUK/Redemption#5696]
**Links:**
https://wow-mania.com/armory/?npc=10647
https://wow-mania.com/armory/?item=5461
https://wowpedia.fandom.com/wiki/Patch_1.5.0
https://wow-mania.com/armory/?quest=1031

**What is Happening:**
[Prince Raze ](https://wow-mania.com/armory/?npc=10647#drops) drops Branch of Cenarius during quest [The Branch of Cenarius](https://wow-mania.com/armory/?quest=1031).
![image](https://user-images.githubusercontent.com/46089380/152682983-de5bf1c8-5372-4b98-ba8a-f5d0b1a66877.png)

**What Should happen:**
Branch of Cenarius should only drop from Geltharis, and not Prince Raze.  This was a change made in patch 1.5.0.
![image](https://user-images.githubusercontent.com/46089380/152682886-5718c159-3509-4fdb-91c5-d913944085f3.png)

![image](https://user-images.githubusercontent.com/46089380/152682851-2426670c-dbb0-46ce-87eb-02889b2be96e.png)

**Comment by Rushor** [comment]
fixed :)
