### ISSUE TITLE
[Item] Skyflare Swiftness proc rate seems incorrect

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#5697]
**Links:** https://www.wow-mania.com/armory/?spell=55379#triggered-by
https://www.wowhead.com/spell=55380/skyflare-swiftness#comments
https://wotlkdb.com/?spell=55380

**What is Happening:** [Skyflare Swiftness](https://www.wow-mania.com/armory/?spell=55379#triggered-by) currently has quite a low proc chance (maybe 5% ?) and an ICD of 45 seconds according to our armory. I've hit a dummy for over a minute after the ICD was over before I managed to get a proc.

**What Should happen:** The proc should have a 100% proc rate according to wowhead, and confirmed by the 0.7 ppm (a proc each ~42s) and a 40s ICD.

**Comment by Keader** [comment]
Our Armory dont show correct info...
In our Database it already has correct info:

![image](https://user-images.githubusercontent.com/7120913/152700334-d40dc683-9f9d-4600-86b0-1b6e86f3f65d.png)

(chance = 0 means use "DBC chance", and in this case is 100%)
