### ISSUE TITLE
[Item] Rings of Ashen Verdict not procced by spriest Non-direct damage spells

### ISSUE THREAD

**Issue by jeyrella** [WoWManiaUK/Redemption#5699]
**Links:**
Items:
50397
50398

**What is Happening:**
See https://github.com/WoWManiaUK/Redemption/issues/5698. 
Spriest non-direct damage spells such as [Vampiric Touch](https://www.wow-mania.com/armory/?spell=48160), [Shadow Word: Pain](https://www.wow-mania.com/armory/?spell=48125), [Mind Flay](https://www.wow-mania.com/armory/?spell=48156) and [Mind Sear](https://wow-mania.com/armory/?spell=53023) will not proc rings as they are chance on cast.

**What Should happen:**
Spriest non-direct damage spells should proc Rings of Ashen Verdict.

**Comment by Keader** [comment]
test now

**Comment by svijetlo** [comment]
work just fine proc on all spells, 
will not post bunch of SS as i do not want github mute again
