### ISSUE TITLE
[Item] Charred Twilight Scale not procced by spriest Non-direct damage spells 

### ISSUE THREAD

**Issue by jeyrella** [WoWManiaUK/Redemption#5700]
**Links:**
Items
Charred Twilight Scale (both nm and HC versions)
54572
54588

**What is Happening:**
See https://github.com/WoWManiaUK/Redemption/issues/5698. 
Spriest non-direct damage spells such as [Vampiric Touch](https://www.wow-mania.com/armory/?spell=48160), [Shadow Word: Pain](https://www.wow-mania.com/armory/?spell=48125), [Mind Flay](https://www.wow-mania.com/armory/?spell=48156) and [Mind Sear](https://wow-mania.com/armory/?spell=53023) will not proc rings as they are chance on cast.

**What Should happen:**
Spriest non-direct damage spells should proc Charred Twilight Scale(s)

**Comment by Keader** [comment]
test now

**Comment by Keader** [comment]
try now

**Comment by svijetlo** [comment]
![WoWScrnShot_020922_151039](https://user-images.githubusercontent.com/61908373/153218722-4d3d83dc-8b5a-4714-b56e-dc1740608066.jpg)
![WoWScrnShot_020922_150923](https://user-images.githubusercontent.com/61908373/153218732-ee6e14c3-c4a4-4a58-9a18-2ef898ec1efb.jpg)
nice job works fine with all dmg spells
