### ISSUE TITLE
[Item] Dislodged Foreign Object not procced by spriest Non-direct damage spells

### ISSUE THREAD

**Issue by jeyrella** [WoWManiaUK/Redemption#5701]
**Links:**
Items
Dislodged Foreign Objects (both nm and HC versions)
50348
50353

**What is Happening:**
See https://github.com/WoWManiaUK/Redemption/issues/5698. 
Spriest non-direct damage spells such as [Vampiric Touch](https://www.wow-mania.com/armory/?spell=48160), [Shadow Word: Pain](https://www.wow-mania.com/armory/?spell=48125), [Mind Flay](https://www.wow-mania.com/armory/?spell=48156) and [Mind Sear](https://wow-mania.com/armory/?spell=53023) will not proc rings as they are chance on cast.

**What Should happen:**
Spriest non-direct damage spells should proc Dislodged Foreign Object(s)

**Comment by Keader** [comment]
try now

**Comment by svijetlo** [comment]
![WoWScrnShot_020722_164032](https://user-images.githubusercontent.com/61908373/152820945-090a798f-aa79-46c9-8eff-8e1811c0607a.jpg)
![WoWScrnShot_020722_154026](https://user-images.githubusercontent.com/61908373/152820965-fb4fd1e5-2175-45ee-aabe-db32120ebd85.jpg)
![WoWScrnShot_020722_155655](https://user-images.githubusercontent.com/61908373/152820991-378b7e0c-2684-4935-adb8-d5c1cf15aade.jpg)
![WoWScrnShot_020722_163728](https://user-images.githubusercontent.com/61908373/152821004-1ce77e2a-b79c-439a-8e0d-ad4f945e696b.jpg)
works just fine on all spells
