### ISSUE TITLE
im sorry i dont know how to reach anyone

### ISSUE THREAD

**Issue by wake327** [WoWManiaUK/Redemption#5707]
this is Waike, i dont know how to contact people on this site.. im sorry for making jokes in chat.. Metaxa.. please.. please.. dont do this to me.. this game brings me joy. im antisocial irl and dont talk to people, my only friends are here. i will be good in chat. i thought it was in good humor. i have autistic issues and depression issues so i dont comprehend sometimes but you're the only family i have at the moment and i have lung cancer.. i cant do this without this and over the past 5 years with you guys this was all i had. All i want to do in this server is make laughter and help people. Let me die here.

**Comment by jeyrella** [comment]
Send email to support@wow-mania.com
