### ISSUE TITLE
[Race] Worgens & Goblins - mounts incorrect on Faction Change

### ISSUE THREAD

**Issue by WhitephoenixTheBunny** [WoWManiaUK/Redemption#5709]
**Links:**
[Mountain Horse](https://wow-mania.com/armory/?spell=103195) - spellID 103195
[Swift Mountain Horse](https://wow-mania.com/armory/?spell=103196) - spellID 103196

[Goblin Trike](https://wow-mania.com/armory/?spell=87090) - spellID 87090
[Goblin Turbo-Trike](https://wow-mania.com/armory/?spell=87091) - spellID 87091

**What is Happening:**
_Issue 1:_ When a worgen switch to the opposite faction, the mounts Mountain Horse and Swift Mountain Horse will not switch to **any** mount.
_Issue 2:_ When a worgen switch to the opposite faction, the mounts Goblin Trike and Goblin Turbo-Trike will not switch to **any** mount.

**What Should happen:**
It should switch to a mount from the ooposite faction, to make it easier:
Worgen Mounts to Goblin Mounts and vice-versa

So:

[Mountain Horse](https://wow-mania.com/armory/?spell=103195) <-> [Goblin Trike](https://wow-mania.com/armory/?spell=87090) 
[Swift Mountain Horse](https://wow-mania.com/armory/?spell=103196) <-> [Goblin Turbo-Trike](https://wow-mania.com/armory/?spell=87091)

I forgot to take SS from the Worgen to horde test, so I only have the Goblin to Alliance test ss

![image](https://user-images.githubusercontent.com/31921098/154841692-cfd6bc4a-c63a-43e9-9ae9-e65572bb61c0.png)

**Comment by Rushor** [comment]
will fix

**Comment by Rushor** [comment]
fixed :)

**Comment by WhitephoenixTheBunny** [comment]
Now when you switch it gives the proper mount of the faction. Will this fix be applied to who already had made the faction change and had the wrong mount?

**Comment by jeyrella** [comment]
I believe that will need a player database retro-update

**Comment by Rushor** [comment]
yep jani needs to handle that manually
