### ISSUE TITLE
[NPC] Warlocks trainer at Teldrassil for Worgen

### ISSUE THREAD

**Issue by jeyrella** [WoWManiaUK/Redemption#5711]
**What is Happening:**
Introduction of "new" warlocks trainers at Teldrassil, due to the dificulty of Worgens leveling on a low map - at least leveling to level 10 without visiting a trainer, since at level 10 they can use the Mall Stone and go Stormwind.

**What Should happen:**
Aldrassil - coor for the new NPC 59.42. 42.65
entry - 459 (human - Northshire Valley) /new skin (nelf) displayID 11907

Dolanaar - coor for the new NPC 59.49. 59.26
entry - 906 (human - Goldshire) /new skin displayID (nelf) 2058

Darnassus - coor for the new NPC 37.77. 9.89 | 38.21. 10.15
entry - 461 | 5496 (human - Stormwind) /new skin (nelf) displayID 2054 | 7016

NOTE:

3 of the NPC are quest givers, for some class quests

NPC level are applied to area level

- [x]  Copy the NPC and rename
- [x]  apply the new look (open for new suggestions)
- [x]  put them on the new placements
- [x]  test

Phase 2

- [x] Add guards the information of the trainer 
- [x] test

Phase 3

- [x] add class quests
- [x] test

**Comment by WhitephoenixTheBunny** [comment]
I am going to check

**Comment by WhitephoenixTheBunny** [comment]
- [ ] Aldrassil

- [ ] Dolanaar 

- [ ] Darnassus 1

- [ ] Darnassus 2

**Comment by WhitephoenixTheBunny** [comment]
Poi tested and confirmed :D 

phase 3 added

**Comment by Rushor** [comment]
a list of all quest ids would be great :)

**Comment by WhitephoenixTheBunny** [comment]
> a list of all quest ids would be great :)

Will do, give me a few more

**Comment by WhitephoenixTheBunny** [comment]
- [ ] rename NPC ( we keep this one for @wow-mania maybe?)

- [ ] Add class quest to "Sandahl" in Darnassus
        - [ ] [An Imp's Request](https://www.wow-mania.com/armory/?quest=8419)

- [ ] Add class quest to "Demisette Cloyce" in Darnassus
        - [ ] [An Imp's Request](https://www.wow-mania.com/armory/?quest=8419)
        - [ ] [In Search of Menara Voidrender](https://www.wow-mania.com/armory/?quest=4738)
        - [ ] [Knowledge of the Orb of Orahil](https://www.wow-mania.com/armory/?quest=4968)
        
        
(Those are the human questline, only need the starting one)

**Comment by WhitephoenixTheBunny** [comment]
Nice! All good, I could take them and start the quests!
Nicely done with the easter egg
