### ISSUE TITLE
[Quest] Fool's Stout available before Zanzil's Mixture, causing item requirement conflict

### ISSUE THREAD

**Issue by jeyrella** [WoWManiaUK/Redemption#5714]
**Links:**
Crank Fizzlebub:  https://wow-mania.com/armory/?npc=2498
Zanzil's Mixture and a Fool's Stout:  https://wow-mania.com/armory/?quest=1119
Zanzil's Secret:  https://wow-mania.com/armory/?quest=621
Fool's Stout:  https://wow-mania.com/armory/?quest=1127

**What is Happening:**
Fool's Stout and Zanzil's Secret are being offered simultenously, leading to a conflict since both quests have requirement to gather Zanzil's Mixture for completion.
![image](https://user-images.githubusercontent.com/46089380/155564107-9af74def-8d52-49f7-bafb-d63746854497.png)
![image](https://user-images.githubusercontent.com/46089380/155565417-3caf682c-44f8-419a-bac8-728ec2c2ecf9.png)

**What Should happen:**
Fool's Stout exists only as a way to get more Stout if Zanzil's Mixture and a Fool's Stout is failed due to the expiry of the 2 hour window.  
Fool's Stout quest should sit later in the chain, only available after acceptance of 1119 and the item for that has expired.  It should not be offered in any other circumstances - it does not offer rep or xp.

**Comment by Rushor** [comment]
conditions added:

Only show quest: Fool's Stout if quest: Zanzil's Mixture and a Fool's Stout is taken + Only show quest: Fool's Stout if item: Fool's Stout is not in inventory or bank

You can quick test that by simply destroying the Stout from your iventory

**Comment by jeyrella** [comment]
![image](https://user-images.githubusercontent.com/46089380/155622969-d4c1ae6f-1eb0-436b-a12b-4f5cc39df982.png)

chain working:
1117:
![image](https://user-images.githubusercontent.com/46089380/155623582-4a39107b-3cc9-49f4-a100-396de30c8553.png)
![image](https://user-images.githubusercontent.com/46089380/155623613-05063cc0-5fca-4368-af33-342b57ff346d.png)

1118
![image](https://user-images.githubusercontent.com/46089380/155623639-1547aee8-15e3-4ae8-a523-e98ccd9e4bd3.png)
![image](https://user-images.githubusercontent.com/46089380/155623672-b7fc3e84-bb21-499e-a01f-92d6ef081175.png)
![image](https://user-images.githubusercontent.com/46089380/155623735-6e37a566-8c8d-4f2c-9d6c-895aa0161971.png)

1119
![image](https://user-images.githubusercontent.com/46089380/155623759-6420128a-192e-4f92-8c84-5eabcfefafd5.png)
![image](https://user-images.githubusercontent.com/46089380/155623794-3ca3d5eb-6497-4654-a9ee-20b5652adc7b.png)

stout destroyed:
![image](https://user-images.githubusercontent.com/46089380/155623834-f0e8ee62-c5c1-46c8-bfd9-e6227a25de29.png)
![image](https://user-images.githubusercontent.com/46089380/155623890-f8dd4f69-0c07-4d21-a630-864a8aa69aeb.png)
![image](https://user-images.githubusercontent.com/46089380/155623920-6e37c7c6-f6ff-44eb-9e5b-7efedd48258a.png)


perfect!
