### ISSUE TITLE
[Spell] Magic Rooster - Will not dismount from previous mount before casting

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Redemption#5715]
**Links:**
Spell https://www.wow-mania.com/armory/?spell=65917

**What is Happening:**
This mount has several issues 
https://gyazo.com/9fa6a8191b156f88a87ec2056cffacba

- [x] Ground mount to Rooster
- [x] Fight mount to Rooster
- [x] Shapeshift mount to Rooster
- [x] Rooster to Shapeshift mount
- [x] Rooster to Ground mount
- [x] Rooster to Flight mount
- [x] Druid flight form to Rooster
- [x] Rooster to Druid flight form
- [x] Rooster to Ghost wolf 
- [x] Ghost wolf to Rooster

**Comment by mfranca0009** [comment]
> **Links:** Spell https://www.wow-mania.com/armory/?spell=65917
> 
> **What is Happening:** This mount has several issues https://gyazo.com/9fa6a8191b156f88a87ec2056cffacba
> 
> * [ ]  Ground mount to Rooster
> * [ ]  Fight mount to Rooster
> * [ ]  Shapeshift mount to Rooster
> * [x]  Rooster to Shapeshift mount
> * [x]  Rooster to Ground mount
> * [x]  Rooster to Flight mount
> * [x]  Druid flight form to Rooster
> * [x]  Rooster to Druid flight form
> * [x]  Rooster to Ghost wolf
> * [x]  Ghost wolf to Rooster

Auto-dismount functions appropriately, however, needs fixing to prevent stacking of `SPELL_AURA_MOUNTED` effects, and get rid of `You are mounted.` error when trying to mount the Magic Rooster when on a different mount.

Currently, the stacking does not occur because of a previous fix, however, it is not a complete fix for the other issues.

**Comment by mfranca0009** [comment]
The first promising solution has been created, applying when PTR is available 👍

**Comment by mfranca0009** [comment]
### What has been fixed
- [x] You can now mount the Magic Rooster when already mounted on a different mount.
- [x] SPELL_AURA_MOUNTED does not stack with the previous mount.

### Remaining problem
- [ ] You receive "You are in shapeshift form" when trying to switch from Lunarwing Form or Sandstone Drake to Magic Rooster

**Comment by mfranca0009** [comment]
All set, however, Lunarwing Form to Magic Rooster will still provide a `You are in shapeshift form` error. This is due to a server crash occurring and it seems it will not work with the same solution as the sandstone drake fix.

**Comment by Echinaceax** [comment]
fix confirmed on PTR 

https://gyazo.com/f1f05916c80d85e98235dd63ccb265ba
