### ISSUE TITLE
[Object] Un'Goro Dirt Pile should contain 1-3 dirt

### ISSUE THREAD

**Issue by jeyrella** [WoWManiaUK/Redemption#5717]
**Links:**
Object:  Un'Goro Dirt Pile:  157936
Item:  Un'Goro Soil:  11018

**What is Happening:**
Dirt Pile only contains 1x Soil.
![image](https://user-images.githubusercontent.com/46089380/155859339-4cc9a497-963d-4b00-af27-3d9463c9e7e4.png)

**What Should happen:**
Can't believe I didn't notice this before.  Should contain 1x-3x of Un'Goro Soil, not 1x
![image](https://user-images.githubusercontent.com/46089380/155859223-8c9ce177-e697-439e-954c-7a8f761f838e.png)

**Comment by Rushor** [comment]
fixed

**Comment by Echinaceax** [comment]
Confirmed fixed on PTR 

![image](https://user-images.githubusercontent.com/39439201/156901784-8da784a7-8603-4c43-bfc4-1a7a54e47627.png)
![image](https://user-images.githubusercontent.com/39439201/156901791-094c06ea-fb17-4619-a63c-ee3605a659e6.png)
![image](https://user-images.githubusercontent.com/39439201/156901796-369b856d-eccc-453d-80aa-746b3630fb3b.png)
