### ISSUE TITLE
[Quest] Escape from Coilscar Cistern - Earthmender Wilda does not assist

### ISSUE THREAD

**Issue by Greywolf59** [WoWManiaUK/Redemption#5719]
**Links:**
Video: https://youtu.be/CdUORA8ABGI
Quest https://www.wow-mania.com/armory/?quest=10451
Npc https://www.wow-mania.com/armory/?npc=21027
Abilities https://tbc.wowhead.com/npc=21027/earthmender-wilda#abilities
Captured water spirit https://www.wow-mania.com/armory/?npc=21029
**What is Happening:**
She doesnt join the fights, doesnt use abilities, she doesnt actually free the spirits. Just walks in, says replica, gets attacked by one spawned mob and walks out. Otherwise works fine.

**What Should happen:**
In the video

**Comment by Rushor** [comment]
issue is related to the faction of the creature, it's not supporting player faction to helping engage the combat

**Comment by Greywolf59** [comment]
Yeah I have done it as Alli draenei, for the info.

**Comment by Rushor** [comment]
should assist players in combat now, combat abilities added.  that's all we can do here for now

**Comment by Rushor** [comment]
prio not low, since the quest is actually totally wrong handled atm

**Comment by Rushor** [comment]
prio not low, since the quest is actually totally wrong handled atm

**Comment by Echinaceax** [comment]
- [ ] She fights some joins in the fights now and uses here abilities (totems and spells)


**still some issues** 
- [ ] She still doesnt free the spirits https://i.gyazo.com/4e6cddb49c58977414dbe42cc5e19b52.mp4
- [ ] she walks past a few mobs without agroing them https://i.gyazo.com/e777ad7fb3f91f861c3d31209e0c7261.mp4

**Comment by Echinaceax** [comment]
@Rushor still not fixed, 
will PM you when discord is fixed 😄

**Comment by Rushor** [comment]
ye is totally broke for me aswell the discord lol
