### ISSUE TITLE
[Quest] Stinky's Escape

### ISSUE THREAD

**Issue by DarkestDuck** [WoWManiaUK/Redemption#572]
http://www.wowhead.com/quest=1270/stinkys-escape

It is supposed that you protect the guy while he is looking for Bogbean Leaves and then escort him to safe place, but he just stands and nothing happens.

Moreover, if you abandon the quest in order to restart it, exclamation mark does not appear again and you can not start it again.

**Comment by fvicaria** [comment]
Works fine in dev.

![image](https://cloud.githubusercontent.com/assets/9414661/20930002/e0384a12-bbc3-11e6-940b-4f5a1d439f9c.png)

Reopen if it happens again after Wednesday.
