### ISSUE TITLE
[NPC] Reliquary of Souls can crit and crush even with max defense rating

### ISSUE THREAD

**Issue by Greywolf59** [WoWManiaUK/Redemption#5720]
**Links:**
https://wowwiki-archive.fandom.com/wiki/Reliquary_of_Souls
Boss 1st phase https://www.wow-mania.com/armory/?npc=23418
**What is Happening:**
The boss can still crit and crush hit in phase one which leads to big issues even on icc 25m geared level 80 and making the boss undoable on level 70 (Naxx, twinks)

**What Should happen:**
The boss in the first phase should be capable of critical or crushing hits to outweight the 100% armor reduction and defense reduction by 500.

**Comment by Rushor** [comment]
The melee abilities crit or the spells?

**Comment by Greywolf59** [comment]
In phase one he is not using any abilities except Fixate iirc and I am not sure if that is even visible cast. Other than that he is just meleeing away. So his melee hits do crit.

**Comment by Rushor** [comment]
alright that can be adjusted

**Comment by Rushor** [comment]
Cannot crit or crush
https://wowwiki-archive.fandom.com/wiki/Reliquary_of_Souls

fixed that

**Comment by svijetlo** [comment]
![WoWScrnShot_030722_104603](https://user-images.githubusercontent.com/61908373/157007100-02ae871e-f1f5-4c54-9c4f-d56cdd5874ac.jpg)
no crit hits were done
