### ISSUE TITLE
[NPC] Kael'thas boss fight Weapons not using abilities

### ISSUE THREAD

**Issue by Greywolf59** [WoWManiaUK/Redemption#5721]
**Links:**
https://wowwiki-archive.fandom.com/wiki/Kael%27thas_Sunstrider_(tactics)
Longbow:
https://www.wow-mania.com/armory/?npc=21268
https://tbc.wowhead.com/npc=21268/netherstrand-longbow#abilities;mode:n25
Staff:
https://www.wow-mania.com/armory/?npc=21274
https://tbc.wowhead.com/npc=21274/staff-of-disintegration#abilities;mode:n25
Mace:
https://www.wow-mania.com/armory/?npc=21270
https://tbc.wowhead.com/npc=21270/cosmic-infuser#abilities;mode:n25
Blades:
https://www.wow-mania.com/armory/?npc=21271
https://tbc.wowhead.com/npc=21271/infinity-blades#abilities;mode:n25
Sword:
https://www.wow-mania.com/armory/?npc=21272
https://tbc.wowhead.com/npc=21272/warp-slicer#abilities;mode:n25
Axe:
https://www.wow-mania.com/armory/?npc=21269
https://tbc.wowhead.com/npc=21269/devastation#abilities;mode:n25
Shield:
https://www.wow-mania.com/armory/?npc=21273
https://tbc.wowhead.com/npc=21273/phaseshift-bulwark
(Shield-spike damage on hit)

**What is Happening:**
The summoned weapons in phase two are doing just normal melee attacks and not using their abilities.
Also Kaelthas when activated in phase one follows the the tank or anyone who activated him, is unatackable and stands in fistfight position. I dont know if anything else is not working right in the encounter

**What Should happen:**
They should use their abilities. Kael shouldnt be nonstop following and asking for a boxing match.

**Comment by svijetlo** [comment]
![WoWScrnShot_030722_112234](https://user-images.githubusercontent.com/61908373/157013239-7cdfaf49-e2a5-467c-bd28-1948a1563acb.jpg)
weapons only did melee hits no skills were used

**Comment by WhitephoenixTheBunny** [comment]
I also can confirm the boss issue acting as puppy at the start

**Comment by jeyrella** [comment]
https://gyazo.com/5ccbebb7fa76e554a7ae9f917ceb480f

something very very wrong here.  this is definitely regression; this boss has been working reasonably ok in the past (I myself have farmed it consistently at times for the mount), and has previously been not at all like this

**Comment by svijetlo** [comment]
> https://gyazo.com/5ccbebb7fa76e554a7ae9f917ceb480f
> 
> something very very wrong here. this is definitely regression; this boss has been working reasonably ok in the past (I myself have farmed it consistently at times for the mount), and has previously been not at all like this

yes i remember this fight work properly with skills etc but , Kel was always bit on moving side

**Comment by jeyrella** [comment]
echi has checked and confirmed all issues for Kaelthas

**Comment by Echinaceax** [comment]
- [ ] Bow
https://i.gyazo.com/3c5404c22b8a48b88080d6d096a5feb3.mp4

- [ ] Staff
https://i.gyazo.com/e6b2577867f7e022d9a511996688b646.mp4

- [ ] heal
https://i.gyazo.com/bcedbd42ee84ad1183d28bb277ce6360.mp4

- [ ] blades
https://i.gyazo.com/922a66f2938137135802ca5738e7de6b.mp4

- [ ] sword
https://i.gyazo.com/2d1e97b161835e745f93b8754acb5ba4.mp4

- [ ] Axe
https://i.gyazo.com/a07574aafc2e74a568496b0dcda5a9c5.mp4

- [ ] shield 
https://i.gyazo.com/491a23f9f59e2d6a1f4397df51f85dcc.mp4
