### ISSUE TITLE
Weapon Skills increasing on Mall dummies

### ISSUE THREAD

**Issue by reanimatednerd** [WoWManiaUK/Redemption#5725]
I've tested on dummies in Stormwind and weapon kills don't incease but they appear to be increasing on the mall ones

unsure if this is a bug or intentional

**Comment by jeyrella** [comment]
For discussion elsewhere.  Thanks for the report

**Comment by jeyrella** [comment]
Hi. We can’t replicate this. Can you give me more details on the weapon type, your level, the weapon skill level? 
Also can you confirm you cleared your cache and it’s still the same afterwards?

**Comment by reanimatednerd** [comment]
appears to be fixed, tested across 3 characters
