### ISSUE TITLE
[NPC] Forsaken Bodyguard  ID 2721 formation not scripted

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Redemption#5726]
**Reported by Franca** 

**Links:**
Forsaken Bodyguard https://www.wow-mania.com/armory/?npc=2721
Forsaken Courier https://www.wow-mania.com/armory/?npc=2714

**What is Happening:**
once the courier is dead for the quest, they just stand there unless in range then will attack
They run back to forsaken courier on respawn, because the leader from formation has been respawned and they are regrouping with the leader.

**What Should happen:**

- [ ] Fix despawning of bodyguards when out of combat after 30 seconds to a minute.
- [ ] Fix spawning courier, so courier spawns in new bodyguards at the same time

only the leader (forsaken courier) has waypoint data, therefore bodyguards do not have waypoint data or pathing.
Forsaken bodyguards should be despawning if they "leave combat" (either player runs away or player dies) after 30 seconds to a minute.

When Forsaken Courier respawns, the bodyguards should be respawning at the same time. The Forsaken Courier should most likely spawn the bodyguards himself through Smart Scripts and set formation on spawn if possible.
If it is not do-able through Smart Scripts, C++ script may be better to manually setup formation when Forsaken Bodyguards are spawned in by Forsaken Courier

**Extra info** 
![npc1](https://user-images.githubusercontent.com/39439201/156034294-2097f2ba-b308-44d4-88c2-48ed81bbe77b.jpg)
![npc2](https://user-images.githubusercontent.com/39439201/156034303-56978117-a12f-44a1-9bc0-7838808cad9e.jpg)
![npc3](https://user-images.githubusercontent.com/39439201/156034306-f243abb3-8aa9-40c6-980e-70b3722288ff.jpg)
![npc4](https://user-images.githubusercontent.com/39439201/156034310-5c73bb01-e56e-473f-91c2-202e80b00ea7.jpg)

**Comment by jeyrella** [comment]
Just as an aside.....  lol at that pathing map:
![image](https://user-images.githubusercontent.com/46089380/156035615-1d64356d-901c-4078-8a07-402c4be7e633.png)

**Comment by Echinaceax** [comment]
> Just as an aside..... lol at that pathing map: ![image](https://user-images.githubusercontent.com/46089380/156035615-1d64356d-901c-4078-8a07-402c4be7e633.png)

only visual map bugged on mania Armory tho @jeyrella

**Comment by jeyrella** [comment]
not really a bug.  it's a core limitation really.  not our fault :D

**Comment by Rushor** [comment]
there can be added a single fix for this fomation, else with commits from tc needs to get merged here?

**Comment by wow-mania** [comment]
won't be fixed at this time
