### ISSUE TITLE
[QUEST] Dr. Boom!

### ISSUE THREAD

**Issue by Greywolf59** [WoWManiaUK/Redemption#5728]
**Links:**
https://www.youtube.com/watch?v=YpKyN1QIO9I
https://www.youtube.com/watch?v=PQoVbySBjiQ
QUEST: https://www.wow-mania.com/armory/?quest=10221
Dr. Boom https://www.wow-mania.com/armory/?npc=20284
Boom Bot https://www.wow-mania.com/armory/?npc=19692

**What is Happening:**
1: The Bomb Bots stand around the camp and aggro you when you get too close, chasing you and meleeing you down.
2: Doctor Boom aggroes you and follows you around while tossing dynamites.

**What Should happen:**
https://www.youtube.com/watch?v=YpKyN1QIO9I
https://www.youtube.com/watch?v=PQoVbySBjiQ
1: Bomb Bots should not aggro you. They should just keep spawning at goblin and walking out away from him and exploding.
2: Doctor Boom should not follow you around, he should just throw a dynamite on you time to time when you are close.

Ps. No clue how to do retarded square brakets on my keyboard, feel free to add them

**Comment by svijetlo** [comment]
altgr F make [ and altgr G make ]

**Comment by Rushor** [comment]
will stay on one place and start spawning bombs now which will run around. will also use the dynamite spell now

**Comment by Echinaceax** [comment]
Confirmed main issue fixed in PTR 

However 
something funky happening, there are 2 NPCs one is friendly and one hostile spawned at the same time @Rushor 
https://i.gyazo.com/fb2ba12d4ae0474f5d266f11dd9bb291.mp4
