### ISSUE TITLE
[Dungeon] Grand Warlock Nethekurse does not engage correctly - Shattered Halls

### ISSUE THREAD

**Issue by Greywolf59** [WoWManiaUK/Redemption#5729]
**Links:**
Strategy part here: https://wowpedia.fandom.com/wiki/Grand_Warlock_Nethekurse
BOSS: https://www.wow-mania.com/armory/?npc=16807
Convert mobs: https://www.wow-mania.com/armory/?npc=17083

**What is Happening:**
The boss does not engage in combat directly after killing the 4 converts. His emotes are all over the place too. Long wait time for boss becoming active on normal, usually works better on heroic.

**What Should happen:**
He should aggro or be attackable right after the 4th convert is dead or when hidden timer is up and he kills the remaining ones himself. No waiting for boss to become active after killing the converts. On heroic it is usually faster, it might even work almost as it should on heroic.

**Comment by Echinaceax** [comment]
Confirmed on PTR 
video from 2010 for dialog references https://www.youtube.com/watch?v=q8nmgbzSBUg

- [ ] The boss does not engage in combat directly after killing the 4 converts
- [ ] His emotes are all over the place (Scroll down to quotes https://wowpedia.fandom.com/wiki/Grand_Warlock_Nethekurse)
- [ ] Game trigger objects can be seen by players 

After killing the 4 NPCs Grand Warlock Netherkurse says one line, then a delay till next dialog, still doesnt attack
 
![after killing the 4 npcs](https://user-images.githubusercontent.com/39439201/156571716-7f454fd3-8a3e-452c-a74e-78a8a8c5e2c4.jpg)

game triggers seen 

![game triggers seen](https://user-images.githubusercontent.com/39439201/156571868-caf26cc6-7631-48a8-8395-7d06bd45fe0d.jpg)

**Comment by Greywolf59** [comment]
Now as I am watching the video you posted, don't his "circles of death" look a bit different on our server, more like a spotlight?

**Comment by Echinaceax** [comment]
> Now as I am watching the video you posted, don't his "circles of death" look a bit different on our server, more like a spotlight?

Notice that too @Greywolf59

**Comment by Rushor** [comment]
triggers no longer visible + he will always become attackable now when peons are dead

**Comment by Rushor** [comment]
white ring also removed

**Comment by Echinaceax** [comment]
Confirmed fixed in PTR 

- [ ] Game triggers 
- [ ] boss attackable after 4 mobs die 
- [ ] white beam removed 

https://i.gyazo.com/57886280d651652d3e9df4a3e17f51d3.mp4
https://i.gyazo.com/36ea7d7c0559876b01ccf1b17b02c005.mp4
