### ISSUE TITLE
[Core/Quest] The Decisive Striker 

### ISSUE THREAD

**Issue by Taurii** [WoWManiaUK/Redemption#573]
http://www.wow-mania.com/armory/?npc=7505#starts

All this quests are bugged. When you try to do them simultaniously they bug. When you try to deliver them all together the items simply disappear or simply don't count and you have to start over.

**Comment by fvicaria** [comment]
Please report each quest individually and say what doesn't work on each. If the items disappear the problem would not be in the quest itself but with the core.

**Comment by Taurii** [comment]
The thing is..this only happens when you accept all quests and try to deliver them all simultaniously. If you do 1 and then deliver they don't bug.

**Comment by fvicaria** [comment]
Should be OK now. 
https://github.com/TrinityCore/TrinityCore/commit/3e789bd476ff9f10224c47b12c7e1af1483df189
