### ISSUE TITLE
[NPC] fix promotion code NPCs so they work with existing system to redeem for items

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Redemption#5730]
Reported by Franca

![image](https://user-images.githubusercontent.com/39439201/156587168-0d02b59d-15b8-45f1-bb73-394023e289db.png)

**Links:**
video confirmation https://gyazo.com/3fa6c2a6a6c92078470f86740c20446a
video confirmation  https://gyazo.com/d170e540565c69c26d1f2a51c87f0c93

- [x] Ransin Donner NPC https://www.wow-mania.com/armory/?npc=2943
https://wowpedia.fandom.com/wiki/Ransin_Donner
- [x] Zas- Tysh https://www.wowhead.com/npc=7951/zastysh
https://wowpedia.fandom.com/wiki/Zas%27Tysh
- [x] Tharl Stonebleeder https://www.wow-mania.com/armory/?npc=16076
https://wowpedia.fandom.com/wiki/Tharl_Stonebleeder

**What is Happening:**
Broken dialog 

**What Should happen:**

- [x] Fix broken promotion code NPCs
- [x] Correct NPCs that are not functioning with promotion code system

Zas- Tysh and Kalecgos 
reported by Phoenix

**Comment by Echinaceax** [comment]
up to you @Rushor

**Comment by Echinaceax** [comment]
> yep should all be removed, prolly better removing the whole npc

Just hiding them should be enough for now @Rushor

**Comment by mfranca0009** [comment]
Two more NPCs that operate in the same manner, will also need gossip options hidden:
- [ ] **Ian Drake:** https://www.wowhead.com/npc=29093/ian-drake

- [ ] **Edward Cairn:** https://www.wowhead.com/npc=29095/edward-cairn

**Comment by Echinaceax** [comment]
Confirmed fixed in PTR 

- [ ] Ransin Donner https://i.gyazo.com/3be6c9857f39fbf8f505f702881a0c9f.mp4
- [ ] Zas- Tysh https://i.gyazo.com/c2917b42e554296fbbf2bca9ae97db99.mp4
- [ ] Tharl Stonebleeder https://i.gyazo.com/c2917b42e554296fbbf2bca9ae97db99.mp4
- [ ] Ian Drake https://i.gyazo.com/4c8dcabc8eb9cce091b41fc5eafd1fa3.mp4
- [ ] Edward Cairn https://i.gyazo.com/2fe508aaae3aa1ebae7203bddfa6d118.mp4

**Comment by Echinaceax** [comment]
Confirmed fixed in PTR 

- [ ] Ransin Donner https://i.gyazo.com/3be6c9857f39fbf8f505f702881a0c9f.mp4
- [ ] Zas- Tysh https://i.gyazo.com/c2917b42e554296fbbf2bca9ae97db99.mp4
- [ ] Tharl Stonebleeder https://i.gyazo.com/c2917b42e554296fbbf2bca9ae97db99.mp4
- [ ] Ian Drake https://i.gyazo.com/4c8dcabc8eb9cce091b41fc5eafd1fa3.mp4
- [ ] Edward Cairn https://i.gyazo.com/2fe508aaae3aa1ebae7203bddfa6d118.mp4
