### ISSUE TITLE
[NPC] Old Man Barlo - Should not show on minimap as trainer 

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Redemption#5731]
**Links:**
https://wowpedia.fandom.com/wiki/Fishing_trainer?oldid=1973731
https://www.wow-mania.com/armory/?npc=25580

![image](https://user-images.githubusercontent.com/39439201/156652733-ea7070bb-9304-405f-918f-34c2eb73f37b.png)

**What is Happening:**
After fix #5439 
The "track profession trainers icon on the minimap, Old Man Barlo still shows as a trainer

**What Should happen:**
The connection to the minimap search needs to be removed

**Comment by mfranca0009** [comment]
Old Man Barlo has been removed from the minimap filter of `Profession Trainers`.

[Juno Dufrain](https://www.wow-mania.com/armory/?npc=18911) is a `Master Fishing Trainer` for the Alliance located at `Cenarion Refuge, Zangarmarsh`, he was missing the profession NPC flag which was preventing him from showing up on the minimap filter for `Profession Trainers`.

Both issues have been fixed on PTR 👍

**Comment by Echinaceax** [comment]
Fixed confirmed on PTR 

Old Man Barlo search removed 

![old man barlo](https://user-images.githubusercontent.com/39439201/156824934-16867a74-a7d0-4d53-9fe3-642de55e5411.jpg)

Juno Dufrain seach added 

![juno dufrain](https://user-images.githubusercontent.com/39439201/156825035-59dfd99f-b045-416a-abbe-6bc4641cca37.jpg)
