### ISSUE TITLE
Rogue Quest Klaven's Tower

### ISSUE THREAD

**Issue by MrKC42** [WoWManiaUK/Redemption#5732]
**Links:**

**What is Happening:**
When starting the quest you can go into the tower and loot the "Locked" chest without pick pocketing the key to open it. If you've been a moron like me you'll be stuck with a 7 day debuff that will not allow you to stealth to get the key in which completing the quest. 

**What Should happen:**
Lockbox shouldn't be available to open/use until the key has been pick pocketed...

**Comment by Rushor** [comment]
Not Sure about that

**Comment by jeyrella** [comment]
Quest is working correctly.
