### ISSUE TITLE
[Quest] The Air Strikes Must Continue grants XP for NPC kills

### ISSUE THREAD

**Issue by WhitephoenixTheBunny** [WoWManiaUK/Redemption#5733]
While doing the quest [The Air Strikes Must Continue](https://www.wow-mania.com/armory/?quest=11533) at low level, one of the required NPC will, [Eredar Sorcerer](https://www.wow-mania.com/armory/?npc=25033) give XP. Any of the NPC should **NOT** give XP.

![image](https://user-images.githubusercontent.com/31921098/156733756-eec70a1c-8869-4a80-94f8-9d42d2e6f3d0.png)

**Comment by Rushor** [comment]
fixed, no xp anymore

**Comment by Echinaceax** [comment]
Confirmed fixed in PTR 👍
