### ISSUE TITLE
[Quest] The Scryer's Scryer - Kalecgos moves too slowly

### ISSUE THREAD

**Issue by WhitephoenixTheBunny** [WoWManiaUK/Redemption#5734]
During the quest [The Scryer's Scryer](https://www.wow-mania.com/armory/?quest=11490) after clicking the Orb and watching the "movie" [Kalecgos](https://www.wow-mania.com/armory/?npc=24848) will come down **HYPER SUPER ULTRA SLOW** to turn the quest and pick the follow up quest.
He should come at a normal flying speed as the follow video shows [*here* ](https://www.youtube.com/watch?v=Sc6Yz378_Oo)

**Comment by Rushor** [comment]
should be faster now

**Comment by Echinaceax** [comment]
No, not really @Rushor 
still slow https://i.gyazo.com/ecd567e11f2bd5afe6a7e6e640b05a80.mp4

**Comment by Echinaceax** [comment]
Fixed in PTR 👍 

much better thanks @Rushor 
https://i.gyazo.com/6b46b60074a906d67108bca10f6e25c9.mp4

**Comment by Rushor** [comment]
goody
