### ISSUE TITLE
[Dungeon] Grandmaster Vorpil; teleport and spawns

### ISSUE THREAD

**Issue by Greywolf59** [WoWManiaUK/Redemption#5739]
**Links:**
BOSS:
https://www.wow-mania.com/armory/?npc=18732
https://tbc.wowhead.com/npc=18732/grandmaster-vorpil#abilities;mode:heroic
https://wowwiki-archive.fandom.com/wiki/Grandmaster_Vorpil

Void Travelers:
https://www.wow-mania.com/armory/?npc=19226#summoned-by

Banish:
https://tbc.wowhead.com/spell=38791/banish

VIDEO start at 43:41:
https://www.youtube.com/watch?v=ym9K83HWbhs 

**What is Happening:**
1: Not sure if he indeed opens FIVE Void Rifts.
2: Void Travelers travel too fast.
3: His teleports works badly, it does not teleport both the boss and the party to his starting pedestal
4: Haven't seen him using Banish in Heroic yet
4: Mobs in his room do not have correct pathing

**What Should happen:**
1: He should open 5 rifts
2: Travelers should travel a bit more slowly
3: Each time he uses teleport it should result in both the boss and whole party beign on his pedestal. This should be immediately followed by Rain of Fire.
4: If there is no Banish, he should be using it.
5: Orc mobs should walk around a bit (as in video)

**Comment by Echinaceax** [comment]
note - will be checked with the other Shadow lab issues already reported 
thanks @Greywolf59

**Comment by Echinaceax** [comment]
confirmed bug https://i.gyazo.com/fe856a861b64950740e27228c315500b.mp4

- [ ] 1: He should open 5 rifts (they are just wrongly placed) 
- [ ] 2: Travelers should travel a bit more slowly
- [ ] 3: Each time he uses teleport it should result in both the boss and whole party beign on his pedestal. (teleport issue yes)
This should be immediately followed by Rain of Fire. (rain of fire bugged coz of teleport yes)
- [ ] 4: If there is no Banish, he should be using it. (he banish on himself) 
- [ ] 5: Orc mobs should walk around a bit (as in video) 

https://www.youtube.com/watch?v=1zn538fRQ98

banish on self 

![banish](https://user-images.githubusercontent.com/39439201/158915913-07f074ce-18d4-44c8-ad97-640f63f7113a.jpg)

other abilities
 
![abilities cast](https://user-images.githubusercontent.com/39439201/158915944-c19f8bfd-1d79-4e6f-b639-2b35af3bbea8.jpg)

**Comment by mfranca0009** [comment]
### Fixed the following
- [x] Grandmaster Vorpil now properly teleports players and himself to the pedestal, which he will then properly cast `Rain of Fire` after the teleport.
- [x] Corrected the void portal positions, they should now be in the correct locations based on video evidence of 2007/2008.
- [x] The summoned travelers now have a slower movement speed, as they should.
- [x] Added missing creature text that Grandmaster Vorpil should say when a group fully wipes and when he casts `Draw Shadows`. 

### Remaining issue that will be fixed at a later time
When the waypoint rework is finished, the proper formation and waypoint pathing will be set up for the Cabal NPCs within this room. The Cabal NPCs should have a formation of 4 in a horizontal line all walking together on the main path back and forth, while another formation of 4 should be walking from the summoning circle up the stairs and back. These formations should execute a kneel emote at certain waypoints (at the first waypoint in front of Grandmaster Vorpil and the last waypoint behind Grandmaster Vorpil).

**Comment by Echinaceax** [comment]
Confirmed all franca listed above on PTR 

https://i.gyazo.com/cbb0e19971af3c60937d9eaa13e021bf.mp4
