### ISSUE TITLE
Mage - Problem with Threat - skill - Mirror Image.

### ISSUE THREAD

**Issue by Dredziarz** [WoWManiaUK/Redemption#574]
Hello, 
on the start i want to apologize for my write language because it isn't perfect.

Ok. 
i'm writed this issues because i finded the bug in one of the mage's skill. i'm talk about Mirror Image skill which gives me 18% additional damage for 30sec in time when i use 4 items of mage's set. 

How it work? 
it's a real example. Sindragosa 25hc.
When we start the battle and Main tank pull the boss. i'm always use my macro button with this one of 3 skills inside. In operation of skill buff bonus my threat start be gray on the Omen addon and does not affect the fight but after 30 sec The boss changing her agro on me and Main tank don't has a time for use the taunt skill and my DPS doing uncatchable Threat like 3.800.000mln points sometimes more so we can see 5-10 times higher threat than Main tank threat.

it's one of the most important skill for mage and without it i can't do my best. When i use the mirror image it's my funeral and 100% of death.

Please help me and fix it.

**Comment by Emcitementz** [comment]
A fix will be deployed, i'll need feedback from this one.
Let me know if anything has changed about it once it's applied.

**Comment by Dredziarz** [comment]
Today i will be on RS25n and i'll write here if something change. :) Thanks for help atm.

**Comment by Emcitementz** [comment]
Wait for the update :)

**Comment by Emcitementz** [comment]
Waiting for some feedback.

**Comment by Dredziarz** [comment]
it's still bugged.  We are now on RS25n and after i used the mirror image i'm start do much more threat than before.

**Comment by philoudu16** [comment]
Im not 100% sure if this could have caused it, but something very strange happened in toc 10 on the Valkyr twins this week end. I only attacked Darkbane, and just before their first special ability, Lightbane came to melee me for some reason. I guess my mirror image must have ran out just then, generating massive threat.

**Comment by Emcitementz** [comment]
Alright, the fix has been modified, you'll have to wait for the new one to be applied.
I've tested it and it seems to finally work, i'll wait for your feedback to see if it's also the same render in a raid situation.
