### ISSUE TITLE
[NPC] Ethereum Nulllifier spawning incorrectly

### ISSUE THREAD

**Issue by Greywolf59** [WoWManiaUK/Redemption#5742]
**Links:**
Ethereum avenger
https://tbc.wowhead.com/npc=22821/ethereum-avenger
https://www.wow-mania.com/armory/?npc=22821
Ethereum nullifier
https://tbc.wowhead.com/npc=22822/ethereum-nullifier#comments
https://www.wow-mania.com/armory/?npc=22822
Bonus: comments on Jailors
https://tbc.wowhead.com/npc=23008/ethereum-jailor#comments

**What is Happening:**
This is really a complicated and low prio issue but since I know about it I guess it is worth a mention.
Ethereum Nullifiers are always spawned on spots of Ethereum Avengers beside the Ethereum main camp. They should spawn only after you kill the Avenger spawned on the same spot. They should behave basically as titanium to saronite, icethorn to lichbloom.
Also it is possible the whole area is missing some spawns and is emptier than it should be but I have no proof of that but is somehow implied by the comments on ethereum nullifiers and jailors.

**Comment by jeyrella** [comment]
No proof = no change.

**Comment by Greywolf59** [comment]
Sure, bur the nullifiers thing is described in wowhead comments

**Comment by Rushor** [comment]
>They should spawn only after you kill the Avenger spawned on the same spot.

can you post the comment from wowhead directly there? So on death of the Nullifiers a Avenger should spawn and vise versa?

**Comment by Greywolf59** [comment]
"When farming these, keep in mind that they are not static spawns. They share spawn points with the Ethereum Avengers. So, you should find a spot with both nullifiers and avengers, and keep on killing both of them. If not, you're gonna run out of nullifiers after a short while."
As said. It is like lichbloom and Icethron. They share the spawnpoint but which one spawns is random

**Comment by Rushor** [comment]
ahh so pooling, yes that is easy to be added and totally understandable. It's the way blizz handles spawns almost everywhere

**Comment by Echinaceax** [comment]
If im reading this right the Ethereum Nulllifier are the ones that should be spawned and once they are all dead, then you can pick off the Avenger's



![image](https://user-images.githubusercontent.com/39439201/157019914-621191a1-7fbd-4329-99cd-dbc37805749b.png)
![image](https://user-images.githubusercontent.com/39439201/157019987-696103cb-2e0d-4e25-81fc-8e3c174d00d2.png)

**Comment by Greywolf59** [comment]
Have you tried doing anything with that? Just asking cause I can't find any jailor now on Naxx and I am usually the inly one farming them. But ofc, I will try looking still

**Comment by mfranca0009** [comment]
Ethereum Nullifiers and Ethereum Avengers have been added to multiple pools so they are randomly spawned between each other (e.g., Ethereum Nullifier spawned, Ethereum Avenger will not be spawned. Vice-versa).

No additional Ethereum Nullifiers or Ethereum Avengers have been spawned, will investigate internally to determine if more are needed to be added or not.

**Comment by Echinaceax** [comment]
confirmed both can be randomly spawned 
fixed in PTR 
![image](https://user-images.githubusercontent.com/39439201/159813670-58164ea3-70f3-4774-9acd-8df178593f34.png)
