### ISSUE TITLE
Soundbug 

### ISSUE THREAD

**Issue by Exsolutio87** [WoWManiaUK/Redemption#5745]
**Links:**
testet with a draenei (Galaxina at lvl 12) 

**What is Happening:**
after using manias mall teleporter there is a new sound like in a church or something. sounds good... but if you use the heartstone, the churchsound stays while the charakter is not anymore in the mall. the char is now in the destination of the heartstone. 

**What Should happen:**
after teleporting with the heartstone, the churchsound have to be eliminated.

**Comment by jeyrella** [comment]
Not a bug, as per design.
