### ISSUE TITLE
[NPC] Frostbrood Sentry - NPCs walking in the air 

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Redemption#5746]
**Reported by Franca** 

**Links:**
https://www.wow-mania.com/armory/?npc=31721

video https://gyazo.com/2c6ed4d3b2288b33ac170940f047ca57

**What is Happening:**
NPCs walking in the air 

**What Should happen:**
Should not walk

**Comment by Rushor** [comment]
fly anmation is now enabled for them

**Comment by jeyrella** [comment]
_We're walking in the air
We're floating in the moonlit sky
The people far below are sleeping as we fly_

Sorry...  just had to...

**Comment by Echinaceax** [comment]
> fly anmation is now enabled for them

Not quite :)
https://gyazo.com/f2706e89313ef9a5a232f980586fcd91

**Comment by Rushor** [comment]
Ah there are two senties versions

**Comment by mfranca0009** [comment]
All set 👍 

I've also corrected the other `Frostbrood Sentry [32767]` to use the correct inhabit type value.

**Comment by Echinaceax** [comment]
confirmed fixed on PTR 

https://i.gyazo.com/3d80cd143ce7346be7941d9317c8ff35.mp4

**Comment by Rushor** [comment]
well i fixed thew first part, so my credits aswell
