### ISSUE TITLE
[Quest] The Drakkensryd - wrong PvP flag

### ISSUE THREAD

**Issue by WhitephoenixTheBunny** [WoWManiaUK/Redemption#5747]
When accepting the quest [The Drakkensryd](https://www.wow-mania.com/armory/?quest=12886) a PvP box will popup (see pictures below), reading wowhead comments from patchs "3" all gives the idea of not flagging for pvp (see other pictures) and video from 2010 also show no box popup and no pvp flag on player.
So, this quest **shouldn't** flag player to PvP

![image](https://user-images.githubusercontent.com/31921098/157433291-5f21100d-4d6f-441a-9a36-b174542d6b21.png)

![image](https://user-images.githubusercontent.com/31921098/157433339-4eada52f-b936-47a0-b485-8fe9fdb38142.png)

![image](https://user-images.githubusercontent.com/31921098/157433420-db2acedd-43d8-4a34-a74a-79e589469834.png)

And here's the [VIDEO](https://www.youtube.com/watch?v=c9i4SD9IeeY)

This issue already was "reported" a few times on #703 #907 and #1285

**Comment by fvicaria4drest** [comment]
I don't think this is valid. The comments are not from 3.3.5a

**Comment by Echinaceax** [comment]
> I don't think this is valid. The comments are not from 3.3.5a

the 2010 video is tho https://www.youtube.com/watch?v=c9i4SD9IeeY we checked it

**Comment by mfranca0009** [comment]
This is all set, was forcing a mandatory PvP flagging, which should not happen.

Removed now 👍

**Comment by Echinaceax** [comment]
fixed in PTR 

https://i.gyazo.com/d0e5c76c680676e7be693620f2ec6028.mp4
