### ISSUE TITLE
[NPC] Thorim is not seated correctly - Storm Peaks

### ISSUE THREAD

**Issue by WhitephoenixTheBunny** [WoWManiaUK/Redemption#5748]
He isn't seating correctly

https://www.wow-mania.com/armory/?npc=29445
![image](https://user-images.githubusercontent.com/31921098/157493141-48c99ae4-7c51-46bc-8acf-68adfd85c317.png)

**Comment by mfranca0009** [comment]
Added position and orientation update, should be fixed on next live update 👍

**Comment by Echinaceax** [comment]
Confirmed fixed in PTR 

![image](https://user-images.githubusercontent.com/39439201/158703161-3f760bf4-82cb-4034-b416-788210a77e91.png)

**Comment by Echinaceax** [comment]
Seems this one has broken again @Rushor
Was a fix from the old Dev

**Comment by Lumber-Jack-2** [comment]
shoudl be good now

**Comment by Echinaceax** [comment]
will need to check on live after update

**Comment by GMZinius** [comment]
Update on this @Rushor 
Thorim is off he's seat again, reported by player.

Also noticed that his respawn timer is off and he does'nt have a despawn corpse despawn

Alive says 5mins 
![image](https://github.com/WoWManiaUK/Redemption/assets/108176634/292210ca-88be-45b9-b8c4-db2e7dccb15b)

Reset says 34m 
![image](https://github.com/WoWManiaUK/Redemption/assets/108176634/80a52ba6-a098-4c33-8789-d31e641126e7)

After GM NPC reset of 35 mins 

![image](https://github.com/WoWManiaUK/Redemption/assets/108176634/03b84d0c-4d25-4170-bf50-07dd6a21fe31)
