### ISSUE TITLE
[Spell] Glyph of Hunger For Blood

### ISSUE THREAD

**Issue by fvicaria** [WoWManiaUK/Redemption#575]
Hi, I have a little bug with my rogue assassination. I'm using the glyph of hunger of blood, which increases damage by 3%. Additional to the normal skill that increases by 5%. To give a total of 8%. The problem is that when I use the skill only increases me 5%. The bug is that the account does not take the additional 3% of the glyph. 

http://www.wowhead.com/spell=60177/hunger-for-blood

Reported on behalf of player: Scheise

**Comment by Emcitementz** [comment]
Tests performed on Sinister Strike.
Damages are up when Hunger for Blood is on.
And with the glyph, it's increased once again, so, it works as it should.
