### ISSUE TITLE
Bug with a quest

### ISSUE THREAD

**Issue by Zweketi** [WoWManiaUK/Redemption#5750]
**Links:**
Dun-da-Dun-tah!

**What is Happening:**
Hello. I am in Grizlly Hills, and this quest with Harrison Jones is not working. I took the quest, but nothing is going on. It's not working. I removed it and took it many time, I cleared my cache, still not working, so check that quest.

**What Should happen:**
I should escort him, but nothing is going on.

**Comment by jeyrella** [comment]
Known issue.  See several other reports.  Nothing can be done about this but to ask a GM to complete it for you.
