### ISSUE TITLE
[Spell] [Death Knight] - Anti-magic Shell

### ISSUE THREAD

**Issue by festerhowl** [WoWManiaUK/Redemption#5753]
**Links:** 
https://wotlk.evowow.com/?spell=63529 - Avenger's shield
https://wotlk.evowow.com/?spell=34490 - Silencing Shot
https://wotlk.evowow.com/?spell=48707 - Anti-Magic Shell

**What is Happening:** Debuffs from Silencing Shot & Avenger's Shield (when specced into [Shield of the Templar](https://wotlk.evowow.com/?spell=53711)) are passing through anti-magic shell's immunity effect.
![image](https://user-images.githubusercontent.com/43633844/157944353-657ed50e-d2c1-4133-ae62-edc542daa729.png)
![image](https://user-images.githubusercontent.com/43633844/157944747-4e4d4808-efe9-47c5-96e5-d3fd299bdff0.png)

![image](https://user-images.githubusercontent.com/43633844/157943039-d29482cf-90a8-46a4-be6c-2ba792f68a28.png)

**Comment by festerhowl** [comment]
@svijetlo

**Comment by jeyrella** [comment]
We do not take other server's armories and their spells as references for issues.  Please read https://github.com/WoWManiaUK/Redemption/wiki/How-to-Properly-Report-an-Issue

**Comment by festerhowl** [comment]
https://wow-mania.com/armory/?spell=63529 - Silencing Shot
https://wow-mania.com/armory/?spell=63529 - Shield of the Templar
https://wow-mania.com/armory/?spell=48827 - Avenger's Shield
https://wow-mania.com/armory/?spell=48707 - Anti-Magic Shell

**Comment by svijetlo** [comment]
![image](https://user-images.githubusercontent.com/61908373/158066317-fa883027-2012-4cc2-86ed-9e6bf45f7957.png)
@festerhowl  pls in future use "reliable " source of info not other server link 
also need to test some other silence effects to confirm it fully

**Comment by Keader** [comment]
try now

**Comment by svijetlo** [comment]
![WoWScrnShot_040422_183429](https://user-images.githubusercontent.com/61908373/161590660-11097cdc-b8f7-4e4f-af4b-cb86005a5d32.jpg)
![WoWScrnShot_040422_183540](https://user-images.githubusercontent.com/61908373/161590677-595a53d4-e418-4609-93d8-64e252afef51.jpg)
