### ISSUE TITLE
[QUEST] Battle of the Crimson Watch; event won't start

### ISSUE THREAD

**Issue by Greywolf59** [WoWManiaUK/Redemption#5756]
**Links:**
Videos:
https://www.youtube.com/watch?v=HeknigPBkDc
https://www.youtube.com/watch?v=-QAMe5ft-ZU
Quest: https://www.wow-mania.com/armory/?quest=10781

**What is Happening:** NAXXRAMAS
Problem is that nothing is happening. After acceptign the quest nothing happens, I have tried waiting for over 5 minutes. I have been told that somebody elses started this quest and failed it over three hours before me. If I understood correctly the event started back then for him. Looks like there is some crazy cooldown on the event start.

**What Should happen:**
After accepting the quest the big crystal with eyes should yell emote and event should start. Waves of demons should spawn and attack the players. I have read whole comment section on tbc wowhead for this quest and nobody mentions any cooldown, which would be natural to do if there would be any long one.
P.S: I have done this quest also over more than a year ago and there were some issues with event starting iirc but I have done it somehow one day, one day the demons decided to spawn.

**Comment by Rushor** [comment]
problem here is that the event sometimes get stuck when a previous player simply leaves the area - need to check the code for that

**Comment by Echinaceax** [comment]
@Rushor Was no issue on RED (i checked that) 
cant check Naxx atm lol no toons

**Comment by Echinaceax** [comment]
I think this will also be fixed after server restart @Greywolf59 
can you let us know please?

**Comment by Greywolf59** [comment]
Tested it. It works. 4 Waves came out: lots of 6k HP demons; 2 flying eyeballs with tentacles; 4 blood elfs; the main blod elf.

**Comment by Echinaceax** [comment]
Thanks @Greywolf59 
will close this now 👍

**Comment by Echinaceax** [comment]
Update fixing from here https://github.com/WoWManiaUK/Redemption/issues/5856
