### ISSUE TITLE
[Dungeon] Zereketh the Unbound casts too many Void Zones - Arcatraz

### ISSUE THREAD

**Issue by Greywolf59** [WoWManiaUK/Redemption#5757]
**Links:**
Boss:
https://tbc.wowhead.com/npc=20870/zereketh-the-unbound
https://www.wow-mania.com/armory/?npc=20870
Video:
https://www.youtube.com/watch?v=38en6USRtvI

Shadow Nova: https://www.wow-mania.com/armory/?spell=36127
Void Zone: https://www.wow-mania.com/armory/?spell=36119
Unbound Void Zone: https://www.wow-mania.com/armory/?npc=21101

**What is Happening:** NAXXRAMAS
This guy works properly but is on steroids or on a speed more likely. Based on watching the video on wowhead (link above) I can say
1: He spams his Shadow Nova way too often. 
2: I seen two void zones at the same time only in video. Currectly we can get three or even four.
3: The void zones are meleeing us in addition to their aoe/puddle damage if I have noticed right.

**What Should happen:**
1: Less Shadow Novas
2: Probably less Void Zones
3: No melee hits from void zones.
This post is based on heroic experience but iirc the same goes on in normal too.

**Comment by jeyrella** [comment]
We don't deal with "probably" or guesswork.  If we can prove, we will fix (ofc if there is an obvious code flaw that could explain it too).  Also evidence should be from retail era (either WotLK or TBC in this case) as classic is not actually faithful

**Comment by Greywolf59** [comment]
I had no idea that reatasil and classic means different things (except hat retail is on patch 9.x.y) Well then I will just stop posting videos/providing evidence, cause I have no idea how can I be sure that video is indeed from retail, especially if even classic ones from wowhead are viewed as problematic here. Also I have never played retail.

**Comment by Greywolf59** [comment]
Only evidence I can provide is what I see compared to what is written on wowpedia and wowhead comments. If that is not enough I see nothing else I can do. I can just stop making posts and save everybody work

**Comment by Rushor** [comment]
I think the video evidence it fine enough, if you can watch the video and calculate a timer based on video time it would help a lot already

**Comment by Rushor** [comment]
I would like to take this since issues got swapped from me

**Comment by Rushor** [comment]
void zones will only spawn when you have at least 2 player in combat with him. 
void zone timer will be first after 6-10 sec and then repeat after 19 sec + void zones will stay passive in one spot
shadownova will be first after 16-20 sec and then repeat after 22-24 seconds

That should be the much better timing like on retail.

**Comment by svijetlo** [comment]
looks fine to me made short vid of fight will upload later
