### ISSUE TITLE
[Dungeon] The Mechanar - Nethermancer Sepethrea summoned Raging Flames despawn and should fight with her

### ISSUE THREAD

**Issue by Greywolf59** [WoWManiaUK/Redemption#5758]
**Links:**
Boss:
https://www.wow-mania.com/armory/?npc=19221
https://tbc.wowhead.com/npc=19221/nethermancer-sepethrea#comments
Raging Flames:
https://www.wow-mania.com/armory/?npc=20481
https://tbc.wowhead.com/npc=20481/raging-flames#comments

**What is Happening:**
At the pull the boss summons two Raging Flames but they despawn immediately.

**What Should happen:**
The Raging Flames should stay in fight. They should be immune and invulnerable, following random players and switching target each 15-20s, leaving trail of fires behind them and causing AoE damage from Inferno (probably aura): https://tbc.wowhead.com/spell=35268/inferno

**Comment by Echinaceax** [comment]
Confirmed bug 
https://i.gyazo.com/078438b418b7f9fa03019cdea0d7dbb8.mp4

**Comment by Rushor** [comment]
flames will no longer despawn

**Comment by Echinaceax** [comment]
Confirmed fixed on PTR 

https://i.gyazo.com/4746e3e40114c398b65f5a577d79f573.mp4
