### ISSUE TITLE
[Dungeon]Shadow Labyrinth-Blackheart the Inciter door

### ISSUE THREAD

**Issue by Anomol** [WoWManiaUK/Redemption#5759]
**Links:**
https://www.wow-mania.com/armory/?npc=18667
https://tbc.wowhead.com/npc=18667/blackheart-the-inciter
**What is Happening:**
After i clear him and the room the gate to the next room will not open

**What Should happen:**
After you clear the room the gate to the next room need to open

**Comment by jeyrella** [comment]
We know of issues with Blackheart already and is being rewritten under ticket #5723 so closing this one as is duplicate.
Contact a GM in game by using /gm and raising a ticket, if you need in game help to work around this.
