### ISSUE TITLE
Changed goblin warlock to orc but shadowbolt proc doesnt work

### ISSUE THREAD

**Issue by OphiRuff** [WoWManiaUK/Redemption#5760]
**Links:**

**What is Happening:**
I've changed my race from goblin to orc warlok, but the shadowbolt proc doesn't work at all and yes I have the talent specced.

**What Should happen:**
Should have proc's once in a while during encounters

**Comment by svijetlo** [comment]
try resetting your talents at trainer and reapply them , if it will be same again it will be tested

**Comment by OphiRuff** [comment]
Hello Svijetlo, your suggestion doesn't work,s till no proc.

**Comment by Echinaceax** [comment]
Will check this issue out 
thx @OphiRuff

**Comment by svijetlo** [comment]
@OphiRuff  if you could just pls post screen shoot of your talents also would be nice , thx in advance

**Comment by svijetlo** [comment]
![WoWScrnShot_032122_144324](https://user-images.githubusercontent.com/61908373/159274079-f5dafed0-7912-4df5-a435-39a63334ab31.jpg)
![WoWScrnShot_032122_144428](https://user-images.githubusercontent.com/61908373/159274085-92a7c8a1-4e96-4686-8d9d-610bc9e68787.jpg)
![WoWScrnShot_032122_144439](https://user-images.githubusercontent.com/61908373/159274089-ccc66256-2643-44ad-a2f1-055478b920dc.jpg)
![WoWScrnShot_032122_144520](https://user-images.githubusercontent.com/61908373/159274111-2a83bd0f-513b-4a7f-9a93-6f1635d26c41.jpg)
i just did simple test , i was goblin did test , talent proc, change to orc did test talent proc 
will keep it open for now so you post your talents , if then it is same problem is your side not server

**Comment by jeyrella** [comment]
@OphiRuff also please check you have cleared your cache after the race change.  If not, that may also have a significant impact.

**Comment by jeyrella** [comment]
No further information gathered.  We can't reproduce.  If you have any more info that might help us, please feel free to add and we can take another look.  Thanks!
