### ISSUE TITLE
[Dungeon] Prince Keleseth: Empowered shadow lance disregard shadow protection calculation - Utgarde

### ISSUE THREAD

**Issue by goldfingyr** [WoWManiaUK/Redemption#5761]
**Links:**
![Prince Keleseth](https://user-images.githubusercontent.com/15333552/158049018-675970f4-fd78-4162-b1b3-001fd486e8df.png)
https://www.wowhead.com/spell=71405/shadow-lance
https://www.wowhead.com/spell=71815/empowered-shadow-lance
https://www.wowhead.com/npc=23953/prince-keleseth#comments

**What is Happening:**
Keleseth kills me with 2 [empowered shadow lances](https://www.wowhead.com/spell=71815/empowered-shadow-lance) that totally disregard the substantial shadow protection I have (>400) (see image)

**What Should happen:**
Shadow protection gear offers protection against shadow damage. So the two especially nasty empowered shadow lances of 25k should be subject to that protection as well. All comments from wowhead ([see link](https://www.wowhead.com/npc=23953/prince-keleseth#comments
)) indicates that it should be so.
As you can see in the enclosed screenshot the regular [shadow lances](https://www.wowhead.com/spell=71405/shadow-lance) are resisted correctly while the [empowered shadow lance](https://www.wowhead.com/spell=71405/shadow-lance) incorrectly disregard the protection.

It is a bit disappointing farming Black Temple to get recipies for shadow prot gear and farming for the stuff to make it just to find out that: yes it works perfectly on all shadow lances - except for those two that was the reason for all this work.
Other than that: Thanks for a good experience

**Comment by jeyrella** [comment]
You’re wearing Black Temple gear in ICC???
You need your raid not to aggro the shadow orbs instead. It is those that give the protection you need. Wearing BT shadow protection armour is unnecessary if your raid is following mechanics as designed, and going to overstress your healer for other reasons.

**Comment by jeyrella** [comment]
Thanks for the report. 
Firstly…  you linked the Keleseth in Utgarde, which caused some confusion!
Secondly, Keleseth is better not tanked with BT gear, that is going to overstress your healers in other ways. The mechanic demands instead that you grab the Dark Nucleii which buff your protection against the lances to insane levels. It sounds very much like your raid is aggroing those off you leaving you very exposed to the lances.  Follow the mechanics, don’t wear Black Temple level armour and you will be just fine

**Comment by goldfingyr** [comment]
Sorry to hear that as this used to be a recommended way as shadow protection is supposed to counter shadow damage.
