### ISSUE TITLE
[Raid] LK 25hc throneroom disappearing textures

### ISSUE THREAD

**Issue by Greywolf59** [WoWManiaUK/Redemption#5763]
**Links:**
Sorry I am writing this in middle of the raid after the wipe. I will provide links after if needed.

**What is Happening:**
About 5 or 6 people just fell through the floor in throne room today during one run on separate ocassions. I doubt any of them used any battle shout etc, the stuff that can make this happen. I fell through too and I sid not use any spell at all inside. We followed our usual path inside.
It wasn't the usual out of nowhere fall. First the textures disappeared and juat the unending hole with floating souls was visible. I saw people moving on further our usual path but when I moved I fell down.

**What Should happen:**
I understand that some spell can be problematic but it should not happen even when person does literally nothing and having 3 people fall per one throne room is a bit problematic.

EDIT: next try was completely fine. Not sure what was different the 1st time.

**Comment by Rushor** [comment]
was reported some time ago, but it's a as-is issue, too complicated to get fixed
