### ISSUE TITLE
[NPC]: Windroc Matriarch Showing Several Strange Behaviors

### ISSUE THREAD

**Issue by kamoodle5** [WoWManiaUK/Redemption#5764]
https://tbc.wowhead.com/npc=19055/windroc-matriarch
https://tbc.wowhead.com/quest=10111/bring-me-the-egg

What is happening:
1.) The Matriarch immediately engages the player who stole the egg, regardless of distance. 
Note: Unsure if this is when she focuses strictly on that player and no one else, ignoring whoever has more threat. This may relate to the second problem listed next.
2.) She completely ignores the hunter's pet, even with any form of taunt active. 
3.) If the hunter who's being attacked uses Feign Death, the Matriarch stops engaging entirely and becomes a sitting duck. She doesn't even react after the hunter starts moving again and attacks.

What Should happen:
1.) The Matriarch should only engage when attacked or the player is close enough.
2.) The bird should react to a pet's taunt and attack if the pet has higher threat.
3.) She should continue to attack another player/pet present after the hunter feigns death, instead of doing nothing.

Below are two Youtube clips. The first shows how the quest is done; the relevant point is when the bird doesn't attack right away once it becomes hostile.

Bring Me The Egg!
https://youtu.be/lcbkYoUnsCU?t=48

Then here's my own video clip showing my experience with the bugs listed.
https://youtu.be/jaoLfpXpcZ0

**Comment by Echinaceax** [comment]
From this video at 0:20 https://www.youtube.com/watch?v=jaoLfpXpcZ0 you see the flight part is also a bit odd 

here is mine 
bird movement https://i.gyazo.com/b2bb3fcb6bd1a736a1a00592cb59a001.mp4
after Feign death https://i.gyazo.com/4a553e0e702231bdfb3f49dbbde918fd.mp4



### confirmed to hunter pet behavour 

1, Hunter grab the egg
2, jump down and attack the bird
3, Hunter Feign death 
4, bird does no attacks to hunter pet (no target for bird, only for the pet) 

cant has aggro, bird just doing nothing (after feign death)
![cat aggro](https://user-images.githubusercontent.com/39439201/158359350-603b5d80-7b46-4e1c-a266-bbe1342018e6.jpg)

Pet attacks only 
![cat ](https://user-images.githubusercontent.com/39439201/158359361-e32def34-9084-4f99-a0bf-8db01fe72225.jpg)

**Comment by jeyrella** [comment]
(Not seen on the known NPC with no SAI list)

**Comment by Rushor** [comment]
changed the ai for the Windroc Matriarch so that she will automatic attack the closest enemie in 50 yards range once reached path point 3. before she always attacked a player in 50 yards range.

creatures ignoring feign death is a general issue and not adress of this specific case here.

**Comment by Echinaceax** [comment]
Confirmed fixed in PTR 
movement a lot better 

https://i.gyazo.com/709ba59b00ac83b8d7d13f0980b57210.mp4

**Comment by Echinaceax** [comment]
> creatures ignoring feign death is a general issue and not adress of this specific case here.

Small note @Rushor - Not only for Hunters, Windroc Matriarch Ignores Warlock pets too

**Comment by Echinaceax** [comment]
- [ ] Movement fixed 

Found further issues 

- [ ] after grabbing the egg, Windroc Matriarch has no aggro after she turns hostile 
- [ ] After new egg spawns player can summon an new Windroc Matriarch, if you dont kill that one, whait for the egg to respawn and again you can summon a new Windroc Matriarch 

spawn 3 for this test 
https://i.gyazo.com/88d501c2bcf33e05c87c98af5867d414.mp4

**Comment by Rushor** [comment]
- bird will now despawn 60 seconds after death
- bird will not spawn if another bird in 100 yards range is already summoned
- bird will turn aggressive when reaching the ground

**Comment by Echinaceax** [comment]
Confirmed only can spawn 1 bird now 

https://i.gyazo.com/7f4d7858e4959312be7f8067070c2b49.mp4

**Comment by Rushor** [comment]
the hostile issue should also be fixed now :)

**Comment by Rushor** [comment]
will attack now on it's own when player comes close

**Comment by Echinaceax** [comment]
Confirmed Fixed aggro
