### ISSUE TITLE
[Item] Pumpkin Bag - dropping from mob while Event isnt active 

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Redemption#5765]
https://wowwiki-archive.fandom.com/wiki/Pumpkin_Bag
https://www.wow-mania.com/armory/?item=20400

![bag](https://user-images.githubusercontent.com/39439201/158853197-55a5e639-d35f-42e0-b963-e30ea36d0e39.png)

**Whats happening**
Pumpkin Bag dropped from mob while event wasnt active

**What should happen**
Pumpkin Bag should only be available from the hollows end event

### Notes
Drops in place of [Traveler's Backpack](https://wowwiki-archive.fandom.com/wiki/Traveler%27s_Backpack) during Hallow's End.

![image](https://user-images.githubusercontent.com/39439201/159360733-2af3eaf5-219d-4894-ae2b-5c29ef36379d.png)

**Comment by Rushor** [comment]
can fix that with conditions if you wish

**Comment by mfranca0009** [comment]
All set 👍 All seven NPCs dropping pumpkin bags will no longer drop them if the Hollow's End event is not active.

Also, four of these NPCs dropping the pumpkin bag that should have dropped the Traveler's Backpack was not; I've corrected this issue as well.

**Comment by Echinaceax** [comment]
confirmed fixed in PTR 

Test confirmed with event off

![image](https://user-images.githubusercontent.com/39439201/159363146-49fee69a-0cc5-4da8-80e4-1dba4da85df1.png)

Test comfirmed with event on 

![image](https://user-images.githubusercontent.com/39439201/159363030-57552ac5-75f1-4c09-a8cb-7276daf2a41f.png)
