### ISSUE TITLE
[Item] Coilskar Chest Key - dropping without the quest

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Redemption#5766]
**Links:**
https://wowwiki-archive.fandom.com/wiki/Coilskar_Chest_Key
item https://www.wow-mania.com/armory/?item=30426
quest https://www.wow-mania.com/armory/?quest=10522

0:20 timeline shows player doesnt have a key yet on hover of the chest https://www.youtube.com/watch?v=S5Fe0LrCZYQ

![key drop](https://user-images.githubusercontent.com/39439201/159371891-73841153-6e94-42e5-8f57-7ef672e95fca.jpg)

**What is Happening:**
Item is dropping when player doesnt have quest 

**What Should happen:**
should only drop when player has the quest

**Comment by mfranca0009** [comment]
All set 👍  conditions have been added. Item will drop only when the quest is taken from all 8 NPCs that drop it.

**Comment by Echinaceax** [comment]
confirmed fixed in PTR 
Only dropping now when player has quest
