### ISSUE TITLE
[Dungeon] Remove SM Armory & Cathedral from dungeon queue

### ISSUE THREAD

**Issue by jeyrella** [WoWManiaUK/Redemption#5767]
**Links:**
https://wow-mania.com/forum/viewtopic.php?f=11&t=928&p=2584#p2584

**What is Happening:**
Due to the extreme XP rates at weekends, low level dungeon runs are scarce, so the chances of any player that does queue Scarlet Monastery Armory or Cathedral actually having a key from Monastery is almost zero, making this dungeon uncompletable when in the RDF

**What Should happen:**
As agreed with GMs, remove SM Armory and Cathedral from the RDF queue system.

**Comment by mfranca0009** [comment]
> hm i think that is a dbc thing where it needs to be removed from the menu, but not sure

Correct, currently have a DBC edit pending with Jani to test on PTR.

**Comment by fvicaria4drest** [comment]
This will remain like this and we can run events and give the key to some interested players.
