### ISSUE TITLE
[NPC] Warsong Peon's / Warsong Hold (mage,warrior,shaman) missing dialogs and abilities

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Redemption#5769]
**Links:**
npc https://www.wow-mania.com/armory/?npc=25270
quest https://www.wow-mania.com/armory/?quest=11611
quest reference video 0:33 timestamp https://www.youtube.com/watch?v=-DjOaSg7rFI

Warsong Hold Warrior https://www.wow-mania.com/armory/?npc=25414
Warsong Hold Mage https://www.wow-mania.com/armory/?npc=25420
Warsong Hold shaman https://www.wow-mania.com/armory/?npc=25421

my videos 
https://i.gyazo.com/b2c79142ef5dcbafd251627d430b48a5.mp4
https://i.gyazo.com/7dc241881069e2f1d29578659150da6e.mp4

**What is Happening:**
- [x] once the Warsong Peon have been freed, they just stand there until the spiders web is re-applied 
- [x] no dialog from Warsong Peon when freed
- [x] once the helpers (warsong mage,warrior,shaman) they stand there, they dont fight or react when hit, they use no abilities

**Extra notes**

should use abilities to help player 
![image](https://user-images.githubusercontent.com/39439201/160277811-37f15b85-a03d-4b2f-91c4-aecea4e33e22.png)

should break websack and have a dialog, and run a few steps and despawn
 
![nerub ar victim sack](https://user-images.githubusercontent.com/39439201/160278035-22d0dd58-5ab9-4fa6-99ab-01f4ca01ae0a.jpg)
![image](https://user-images.githubusercontent.com/39439201/160278319-d64f9405-5c59-44a4-92ee-b619ca730e01.png)

**Comment by Rushor** [comment]
added the texts and abilties for them

**Comment by Rushor** [comment]
updated with fresh AI so the abilities will happen now and they should go infight

**Comment by Echinaceax** [comment]
Fixed in PTR 

https://i.gyazo.com/4b5ed148fa0ca5bf39dcd5c9658702be.mp4

**Comment by Echinaceax** [comment]
Extra info 

Also Helpers should be in the 
timestamp 0:35 https://www.youtube.com/watch?v=dm2nIiuUGJw
while player is in that zone doing other quests Eg: quest **Taking Back Mightstone**

**Comment by Rushor** [comment]
added despawn when they leave the intended area

**Comment by Echinaceax** [comment]
confirmed 



> added despawn when they leave the intended area

confirmed 

https://i.gyazo.com/f654b895214fa4edbe19d6d5266e5d85.mp4
