### ISSUE TITLE
[NPC] Stormpeak Wyrm Needs adjustments when near objects / mountains/ground

### ISSUE THREAD

**Issue by jeyrella** [WoWManiaUK/Redemption#5770]
**Links:**
NPC 29753  (and possibly 30055?)

**What is Happening:**
Stormpeak Wyrm has no animation on death.  Goes straight from standing to lying flat on the ground.

**What Should happen:**
Have an animation to transition between alive and dead.

**Comment by jeyrella** [comment]
Yep that's exactly it Echi, good catch.  thanks.
I think 30055 is a spawn specially for the jewelcrafting daily, possibly.

**Comment by Echinaceax** [comment]
> Yep that's exactly it Echi, good catch. thanks.

no probs

**Comment by mfranca0009** [comment]
> I think 30055 is a spawn specially for the jewelcrafting daily, possibly.

No, @jeyrella . These `30055` NPCs should be spawned carrying `Ice Steppe Bulls (30445)` to the `Stormpeak Hatchlings`. They are most likely spawned via a script on a timer that is not implemented. To be honest, that item most likely should not be dropping on the periodically spawned NPCs of `30055` and should only be dropping from `29753` and `29755`; I could be wrong though on the item drop part.

Here is the screenshot at least related to `30055`:
![image](https://user-images.githubusercontent.com/26092980/160464027-5d6154cd-9531-489e-86b8-579378eeb7f6.png)

**Comment by jeyrella** [comment]
due to core limitations, this will not be fixed for now
