### ISSUE TITLE
[Item]: Leaping Hatchling's Special Animation Missing

### ISSUE THREAD

**Issue by kamoodle5** [WoWManiaUK/Redemption#5771]
https://www.wowhead.com/item=48118/leaping-hatchling
https://www.warcraftpets.com/wow-pets/beast/raptors/leaping-hatchling/

What is happening: This pet currently and only has its idle animation; it never performs its unique animation, however.

What Should happen: The special animation should be included. 

Note: How the animation works is the raptor will move away from the player then leap at them. At the very beginning of the video below, you can see the raptor do its leap.
https://youtu.be/WlETzyJlA-4

**Comment by Echinaceax** [comment]
Confirmed bugged 

![image](https://user-images.githubusercontent.com/39439201/160693138-800911e7-ead3-41c1-add3-b23b5970eafa.png)

**Comment by Rushor** [comment]
ID - 67430 - Leaping Hatchling Jump to Master

every 2-4 minutes > 5 seconds move random > jump

**Comment by Rushor** [comment]
added that, it will first move a bit and then leap to the player again and follow him.

important he will not jump if the pet is too close to the player, but that is not important. everything else is added

**Comment by Echinaceax** [comment]
confirmed fixed in PTR 

https://i.gyazo.com/d41e5e4174028503378b94bbf8654576.mp4

**Comment by Rushor** [comment]
@kamoodle5 can you check which other hatchlings should have such animation in general. maybe we can fix more vanity pets like that
