### ISSUE TITLE
[Item]: Darting Hatchling's / mulgore hatchling - Special Animation Missing

### ISSUE THREAD

**Issue by kamoodle5** [WoWManiaUK/Redemption#5772]
https://www.wowhead.com/item=48112/darting-hatchling
https://www.warcraftpets.com/wow-pets/beast/raptors/darting-hatchling/

What is Happening: Like the Leaping Hatchling, this baby raptor also has a unique animation, but it never does it.

What Should happen: Its special animation should be included.

Note: This baby raptor will dash away from the player in a cloud of dust, then run back. Here's a video showing this:
https://youtu.be/dNH3bJifswY

**Comment by Echinaceax** [comment]
Confirmed bugged 

just stands there when summoned 

![image](https://user-images.githubusercontent.com/39439201/160693138-800911e7-ead3-41c1-add3-b23b5970eafa.png)

**Comment by Rushor** [comment]
will try to sniff the spell, quick guide on how to get the pet would be great :)

**Comment by Rushor** [comment]
niice

**Comment by Rushor** [comment]
funny, blizz uses this aura for him 62585 - Mulgore Hatchling

maybe the mulgore hatchling must do this aswell

**Comment by Rushor** [comment]
will apply for https://www.youtube.com/watch?v=K4sL2FBgbe0 aswell then

**Comment by Echinaceax** [comment]
> Mulgore Hatchling

Yes please, it doesnt have any atm 

https://gyazo.com/4db27667921deacd7b0bc7120ec9b404

**Comment by Echinaceax** [comment]
confirmed fixed in PTR 
Dartling https://i.gyazo.com/a61b8c4ef171076b37afc32c302f0e20.mp4

Mulgore Hatchling https://i.gyazo.com/89be9de574f39cc5746316979c57fe47.mp4
