### ISSUE TITLE
[Quest] Free your Mind: quest credit and revival should come at end of item channeling - Icecrown

### ISSUE THREAD

**Issue by jeyrella** [WoWManiaUK/Redemption#5773]
**Links:**
Quest:  https://wow-mania.com/armory/?quest=12893
Item (Sovereign Rod):  https://wow-mania.com/armory/?item=41366

**What is Happening:**
Corpses are revived and credit is given instantly on using the [Sovereign Rod](**https://wow-mania.com/armory/?item=41366**) on the corpses.

**What Should happen:**
the revival and quest credit should come at the end of the channelling of the item, not the start.

**Comment by Echinaceax** [comment]
confirmed bug 

vile https://i.gyazo.com/bd505b2c32bdbda7caf4d957d3e2fb2f.mp4
leper https://i.gyazo.com/45f876ba5509e8d60c5a1c9951ce3287.mp4

and Lady Nightswood too (didnt get video for her 😄

**Comment by Rushor** [comment]
will now only give credit at channel end

**Comment by Echinaceax** [comment]
All 3 fixed in PTR

https://i.gyazo.com/c743a30d7966a0eadf947b07bbd5c53c.mp4
https://i.gyazo.com/2518e57149f737103e6ba91a67ab1b9c.mp4
https://i.gyazo.com/a0e10fd3a93632f2c6b2fd4d7075657e.mp4
