### ISSUE TITLE
[NPC] The Leaper is not leaping, teleports instantly on engage - Icecrown

### ISSUE THREAD

**Issue by jeyrella** [WoWManiaUK/Redemption#5774]
**Links:**
NPC:  https://wow-mania.com/armory/?npc=29847
video:  https://youtu.be/w_ARDRdFMwA?t=89   (pre-2010 vids for this seem not to exist)

**What is Happening:**
The Leaper is static on the parapet.
When engaged at range, teleports instantly to the player, instead of leaping

**What Should happen:**
https://youtu.be/w_ARDRdFMwA?t=89
- [x] Should be leaping in a path from one end of parapet to the other 
- [x] When engaged at range, should leap to the player not instantly teleport

**Comment by Echinaceax** [comment]
Confirmed bugged 
saw it on my last test

**Comment by Rushor** [comment]
npc=29840

**Comment by Rushor** [comment]
path fixed so far, leap i complicated

**Comment by Echinaceax** [comment]
> path fixed so far, leap i complicated

Pathing is a lot better confirmed

**Comment by Rushor** [comment]
okay jump upon aggro fixed now :D

**Comment by Rushor** [comment]
https://gyazo.com/e33d8e11d9ba809b1caa8470a204c0eb

**Comment by Echinaceax** [comment]
confirmed fixed in PTR 

https://i.gyazo.com/0c7c1460a0f779b52481987b4224ecb9.mp4

**Comment by WhitephoenixTheBunny** [comment]
The leaper is teleporting when close to him. Video on dev channel

**Comment by Echinaceax** [comment]
I checked this on PTR for phoenix and its working as it should on there, https://i.gyazo.com/43254095f286c728ab43669898966997.mp4


then i spoke with GM to check Live and GM confirmed bugged on Live @Rushor

**Comment by Rushor** [comment]
I think she means the infight behaviour, when aggro he should jump and not teleport. I applied the sql an agin, and this will be run of live then. It should solve the problem.

**Comment by Echinaceax** [comment]
> I think she means the infight behaviour, when aggro he should jump and not teleport. I applied the sql an agin, and this will be run of live then. It should solve the problem.

can check this when its on live @Rushor (coz it wasnt bugged on PTR)

**Comment by GMZinius** [comment]
Confirmed live server issue fixed
