### ISSUE TITLE
[Spell] Untalented Strength of Earth Totem overwrites Horn of Winter

### ISSUE THREAD

**Issue by Lantanio** [WoWManiaUK/Redemption#5775]
**What is Happening:**
Gaining the Strength of Earth (SoE) buff always overwrites Horn of Winter (HoW), even if none of the shamans in the raid are specced into Enhancing Totems (ET). 

**What should Happen:**
Conversely, SoE should only overwrite HoW when the casting Shaman has (1+/3) points in ET, since untalented SoE grants exactly the same stats as HoW. Upon entering the range of an untalented SoE Totem, the player should instead retain both buffs (but receive stats from only one of the two, of course). The interaction is discussed [here](https://www.mmo-champion.com/threads/638383-Enhancing-Totem-Talent-Question) and, as far as I know, this is the standard of how talented vs untalented buffs interact in WotLK. 

You can find instances with players having both buffs active in [video 1](https://youtu.be/8rwO63F08ys?t=44) and [video 2](https://youtu.be/N5oC5TaoGdI?t=27) in the freeze frames I linked. Conversely, you can see in [video 3](https://youtu.be/4J0P0SEojFk?t=16) that the player loses HoW as soon as SoE is dropped. Heterogeneity is, in all likelihood, due to SoE being buffed by ET in video 3. 

The current state of the SoE/HoW interaction can be particularly annoying on moving fights. When you enter the range of any SoE, you lose your HoW. It often happens that you then quickly exit the range, when resto shamans' SoEs are dropped far from the boss, so that you end up losing both buffs.

**Comment by Keader** [comment]
try now pls

**Comment by svijetlo** [comment]
![WoWScrnShot_040422_182011](https://user-images.githubusercontent.com/61908373/161588152-d59d7d82-a39d-4b54-8560-fa29e143edf1.jpg)
![WoWScrnShot_040422_182006](https://user-images.githubusercontent.com/61908373/161588167-580f5299-8309-49f0-aa4d-e2a414009acb.jpg)
![WoWScrnShot_040422_182026](https://user-images.githubusercontent.com/61908373/161588179-dc299219-2246-4da4-b632-9fe0202f9c8c.jpg)
![WoWScrnShot_040422_182022](https://user-images.githubusercontent.com/61908373/161588194-5615f43e-3ab8-4296-9dc1-16159a03a371.jpg)
it will not overtwrite it and as it should be only one will take efect on player
