### ISSUE TITLE
[NPC] Wintergrasp tower Cannon - respawns have a rotation / position issue + Wintergrasp additional Fixes / Checks

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Redemption#5777]
**Links:**
https://www.wow-mania.com/armory/?npc=28366
https://www.wow-mania.com/armory/?spell=51421

![image](https://user-images.githubusercontent.com/39439201/161232765-eccec97a-8485-49fb-a1e0-a48779f9c18c.png)

**Evidence**
https://i.gyazo.com/4cbff18b9233bdf1bc777add27a1b1aa.mp4
https://i.gyazo.com/b3cbef984baafc7e4c713f0dc4d0f908.mp4
https://i.gyazo.com/7882747f2ded51b5cca8a99411f294ad.mp4
https://i.gyazo.com/f0df384dc52539ad38dc0589838318af.mp4

**What is Happening:**
When fort cannons are killed by the attacking faction for rank up, the respawned cannons have a rotation / possition issue
(that shouldnt happen)

### This is gamebreaking for attacking team and a very unfair advantage for the defending team

**What Should happen:**
Respawned cannons should only have a face frontal and side to side attack range

should be like this 
https://i.gyazo.com/10f2b3164797a354a0bce0141c0d97de.mp4

### Also to check 

- [x] Check if defending team tena buff is giving damage bonus that it shouldnt  (checked)

![image](https://user-images.githubusercontent.com/39439201/161163780-d1c59bd0-c851-4b66-a110-5a0067f070eb.png)

- [x] Checked demolisher today 

![image](https://user-images.githubusercontent.com/39439201/161164474-bad33801-0ab8-4bc8-a256-a8fd140b96e8.png)

- [x] Siege needs checking (checked)
- [x] Cannons need checking (checked)
https://www.wow-mania.com/armory/?spell=51422 cannon is doing 7996 to 8004

### Wintergrasp additional Fixes / Checks
- [x] Added 12 missing Wintergrasp Tower Cannons in total  (FT - ST - WT) 
- [x] Fixed both Alliance and Horde Wintergrasp guard NPCs that were placed incorrectly in the air and looking the wrong way.
- [x] Fixed Alliance and Horde Wintergrasp guard NPCs that were incorrectly placed at a portal outside of the fortress.
- [x] Checked Cannon damage, damage is correct, also cannons scale to player gear (as it should)
- [x] Checked Tenacity only giving HP boost while in vehicles
- [x] Wintergrasp tower cannons will now respawn at their appropriate spawn position; not on their last known location at death.
- [x] Splash damage checked (20 yards radius as stated) 
- [x] Fixed capture range of workshop points, the capture range was way bigger than what it should be for all workshops.
- [x] Added a total of 13 missing guards spread out across all four workshops and corrected existing guard positions.
- [x] Added 2 missing guards within the main fortress by the east fortress vehicle workshop. 
- [x] RPGs handheld weapon and Tena buff / Without Tena buff (checked and correct) dam they pack a punch 😄 💣 
- [x] Tenacity system has been reworked to take into account the max team size of 40; to appropriately balance the stack amounts being given compared to player difference. Also, the updating of tenacity has been adjusted, so it smoothly updates current stack amounts and only clears it when the current team no longer needs it or the other team requires it.
- [x] Guard NPCs at all 4 capturable workshops outside of the fortress will now appropriately switch based on the team that captured it 
- [x] Faction banners and engineers at all four workshops will now instantly swap and update visibility properly when the opposite faction captures it.
- [x] All 4 capturable workshops now have the appropriate faction flag attached to the flagpole based on which team has the workshop captured. 

https://wowwiki-archive.fandom.com/wiki/The_RP-GG
https://www.wow-mania.com/armory/?npc=30560
https://www.wow-mania.com/armory/?search=The+RP-GG#npcs

### General Core Fixes
- [x] Correction of proper respawn position using the creature's home position rather than their last known location on death.

### Video Evidence of Fixes
**Killing cannon and displaying death location:**
 https://i.gyazo.com/42964c2914b23e5da7e5f88fc5ec1e85.mp4
 
**After corpse disappear, proper correction of respawn position occurs:**
https://i.gyazo.com/09008b421baf6e45ca84f21b4f5d2848.mp4

**Smooth Workshop NPC switch** 
https://i.gyazo.com/53fef22dd06e080f53cfbd825d10a583.mp4

**Nice new Capture Flagpole Flags desplayed correctly** 
https://i.gyazo.com/09e1d431c81795057a22f1183bd7af4e.mp4

**Comment by Hajzlopuc** [comment]
Hello, How about checking cannon damage? They do like 10 times more damage than they should.

**Comment by Echinaceax** [comment]
> Hello, How about checking cannon damage? They do like 10 times more damage than they should.

Also being checked

**Comment by Hajzlopuc** [comment]
We have much higher splash than indicator is, much faster bullets as well, also bullets should be doing less damage the further you are from the center point of impact.

**Comment by Echinaceax** [comment]
> We have much higher splash than indicator is, much faster bullets as well, also bullets should be doing less damage the further you are from the center point of impact. In reality you should be taking 1-2k hits if you are not in the center of explosion. Same applies to siege machine cannon https://www.wow-mania.com/armory/?spell=57610

We are working on fix later today, thanks for more info @Hajzlopuc

**Comment by Echinaceax** [comment]
### Fixed so far

- [ ] Added 12 missing Wintergrasp Tower Cannons in total
- [ ] Fixed both Alliance and Horde Wintergrasp guard NPCs that were placed incorrectly in the air and looking the wrong way.
- [ ] Fixed Alliance and Horde Wintergrasp guard NPCs that were incorrectly placed at a portal outside of the fortress.
- [ ] Fixed the Wintergrasp Tower Cannons so they appropriately respawn at their "original home position" and not on their "last death position".

### Still to fix 

- [ ] Splash damage check

**Comment by Echinaceax** [comment]
Found 2 more issues @mfranca0009 😄
