### ISSUE TITLE
[Spell] [Death Knight] Scourge Strike vs Full Absorb

### ISSUE THREAD

**Issue by festerhowl** [WoWManiaUK/Redemption#5778]
**Links:**
https://www.wow-mania.com/armory/?spell=55271
https://www.wow-mania.com/armory/?spell=53601
![image](https://user-images.githubusercontent.com/43633844/161265674-56c570a0-f691-4daa-9241-f767535c7f11.png)

**What is Happening:**
Scourge strike has 2 damage components - physical & shadow. For each of our diseases on the target, we deal an additional 12% of the Physical damage done as Shadow damage. 

The issue is that the shadow damage is missing when the physical damage is getting fully absorbed. Its only hitting when the physical damage is either partially or not absorbed at all.

Scourge Strike when Physical damage is not absorbed:
![Screenshot (280)](https://user-images.githubusercontent.com/43633844/161264008-ee80b93a-d3bf-4db5-9d38-4a7f0f445a26.png)

when Physical damage is absorbed completely:
![Screenshot (281)](https://user-images.githubusercontent.com/43633844/161264146-42daac67-330c-4583-bd33-8ed301d64eec.png)

**What Should happen:**
Scourge strike shadow component should always cast as long as the physical part doesn't miss. I tested this only on Paladin's [Sacred Shield](https://www.wow-mania.com/armory/?spell=53601) so i am unable to confirm if it is behaving the same way on similar abilities from other classes such as mages or priests. Please check
https://www.bluetracker.gg/wow/topic/us-en/20433766548-scourge-strike-on-the-ptr-information/
![image](https://user-images.githubusercontent.com/43633844/161263672-426d41b5-c1d7-4c77-9ff3-ec0ec751e0e5.png)

_Note: I reported this issue earlier at #5692 but didn't give complete details there and it got closed so had to open a new one._

**Comment by Keader** [comment]
i dont think that it's a issue.
In WoW, Miss, Hit and Absorb not means same thing.

"The Shadow part of the damage should never miss if the physical part hits".

Hit means: fully hit or partial absorb
When damage got a full absorb, status change of HIT to ABSORB

Blizzard implement the "never miss" part using SPELL_ATTR3_IGNORE_HIT_RESULT in shadow effect, that means: it will never miss when casted
so everything looks correct here for me

**Comment by festerhowl** [comment]
Even if the physcial part is fully getting absorbed why does that stop the shadow part from casting?
This is behaving as if i do not have any diseases on the target
and Absorb is not equal to miss so i dont see a reason why the shadow part would not cast when the physical part is casting and damaging but getting absorbed

Lets say sacred shield can absorb 5k damage
my physical portion does 1k damage
shadow portion does 500 damage.

Shouldnt my spell then hit for 1.5k and get absorbed completely rather than only hit for 1k?

**Comment by Keader** [comment]
Yeah, we found proof that it should work in full absorb too
working on it

**Comment by festerhowl** [comment]
Found some other issues with the spell. Can you please take a look at the below as well?

In https://github.com/WoWManiaUK/Redemption/issues/3050 Dranah has mentioned how the shadow portion is supposed to work so i am not going to link any other sources.
Currently the shadow portion is not getting modified by all the buffs mentioned in that report.

Issue 1:
Assuming i have 3 diseases on the target, and specced into the below talents, the shadow portion should hit for:

Physical portion x 0.36(Three diseases) x 1.04 (Two-Handed Weapon Specialization) x 1.13 (Ebon Plaguebringer) x [1.0 + 0.15 (Blood presence) + 0.05 (Desolation) + 0.02 (Bone Shield) + 0.1 (Black Ice)]

_Multiplicative: Ebon Plaguebringer (+13%), Two-Handed Weapon Specialization (+4%)
Additive: Blood Presence (15%), Desolation (5%), Black Ice (10%), Bone Shield (2%)_

So if i have all of the above, my shadow portion should do ~55.6% of the physical portion. Currently it is doing only ~51.5% of the physical portion. I am not sure which modifiers are not being considered in the calculation. Can you please check?

Proof:
![image](https://user-images.githubusercontent.com/43633844/161425091-4595ee00-b391-4f98-bb18-ac916378b584.png)

14:23:12> Your Scourge Strike hit Highlord's Nemesis Trainer 632 Physical.
14:23:12> Your Scourge Strike hit Highlord's Nemesis Trainer 326 Shadow.

The shadow portion is only doing 51.5% of the physical. 

Since i tested this with all of the modifiers mentioned above, my shadow portion should have been:
632 x 0.36 x 1.13 x 1.04 x (1.0 + 0.15 + 0.05 + 0.02 + 0.10) = 352 shadow
~55.6% of the physical portion

Issue 2:
As you can see in the above SS, some of my shadow portion also got resisted by the dummy. This should not be happening:
Proof:
![image](https://user-images.githubusercontent.com/43633844/161425634-ae08c4d8-4f40-4e67-87ae-8af93cf61962.png)

Please let me know if you want me to open a new report for this part

**Comment by Keader** [comment]
Damage of shadow part is fixed already (calculation)
fixed absorb proc part
and fixed resistence (check #5782)

**Comment by festerhowl** [comment]
> Damage of shadow part is fixed already (calculation)

@Keader After some more testing i found that Ebon Plaguebringer and Two-Handed Weapon Specialization are being calculated as an additive instead of multiplicative.

For example It is behaving currently as:
Physical portion x 0.36(Three diseases) x [1.0 + 0.04 (Two-Handed Weapon Specialization) + 0.13 (Ebon Plaguebringer) + 0.15 (Blood presence) + 0.05 (Desolation) + 0.02 (Bone Shield) + 0.10 (Black Ice)]

whereas it should behave as:
Physical portion x 0.36(Three diseases) x 1.04 (Two-Handed Weapon Specialization) x 1.13 (Ebon Plaguebringer) x [1.0 + 0.15 (Blood presence) + 0.05 (Desolation) + 0.02 (Bone Shield) + 0.10 (Black Ice)]

Can you please check if the following modifiers are also affecting spells as additive instead of multiplicative, because ebon plaguebringer & two-handed Weapon specialization(DK) are similar to them:

Counterparts of Ebon Plaguebringer:
https://www.wow-mania.com/armory/?spell=48511 - Earth & Moon
https://www.wow-mania.com/armory/?spell=47865 - Curse of the Elements

Counterparts of Two-Handed Weapon Specialization:
https://www.wow-mania.com/armory/?spell=12711 - Warrior
https://www.wow-mania.com/armory/?spell=20112 - Paladin

If they affect spells as additive then there are no changes needed. If they are multiplicative then that would explain why the shadow part is not doing ~55.6% of the physical portion.

**Comment by Keader** [comment]
Missing Two-Handed Weapon Specialization lul

**Comment by festerhowl** [comment]
yeah that makes more sense. Pls add it as multiplicative xd

**Comment by svijetlo** [comment]
![WoWScrnShot_040422_180835](https://user-images.githubusercontent.com/61908373/161586271-0b02f82f-8853-4cd6-ab83-c94bb2817266.jpg)
