### ISSUE TITLE
 3.3.5 Words of Power

### ISSUE THREAD

**Issue by sw19747** [WoWManiaUK/Redemption#5779]
https://www.youtube.com/watch?v=LgTja-MP3AY

0,33 sec this part dont wurk 

https://www.wowhead.com/quest=11942/words-of-power

and pls keep the good wurk up

**Comment by jeyrella** [comment]
I completed this on Redemption last week, and seems to work fine on PTR.  Can you clarify what you mean by "don't wurk" please?

**Comment by svijetlo** [comment]
this one always worked fine , need to check it up

**Comment by sw19747** [comment]
i can not atack the mob

**Comment by jeyrella** [comment]
Did you kill the webs next to him?  He is immune until you do so

**Comment by sw19747** [comment]
Its wurks now trow a way the Quest and acept it again and now it wurks
