### ISSUE TITLE
[Spell] [Death Knight] Raise Dead - Ghoul stats are incorrect

### ISSUE THREAD

**Issue by festerhowl** [WoWManiaUK/Redemption#5780]
**Links:**
[Raise Dead](https://www.wow-mania.com/armory/?spell=46584)

**What is Happening:**
The agility base value of the ghoul is wrong. It should be 856 but the base value here is 247.
I am not exactly sure how the ghoul's AP and armor values are being calculated here but its wrong as well.

Ghoul base attributes at lvl 80 without any player modifiers should be:
Strength: 331
Agility: 856
Stamina: 361
Attack Power: 1167

The AP formula is:
Ghoul ap= Ghoul strength(331+modifiers) - 20 + Ghoul agility(856+modifiers)
1 strength > 1 ap
1 agility > 1 ap

first 20 strength is not calculated in the attack power hence the (-20). The strength part seems to be working fine from what i see in the tooltip(see attached) but i am not sure how/if the agility is or isnt affecting the AP. There seems to be something else as well which is affecting the AP and its incorrect.

Therefore, without any modifiers from the player, the base ap of the ghoul should be 331-20+856 = 1167 ap

From that formula and the stats that you can see on my ghoul in the SS below, my ghoul's AP should have been:
645-20+856= 1481. but its 764 (not sure where this number is coming from)
![image](https://user-images.githubusercontent.com/43633844/161381216-c62e2eff-8751-4889-9108-c7089031601c.png)

**Proof**: https://www.youtube.com/watch?v=phwZkrTnjpA
at 1:10 you can see the DK hovering over his ghoul's attributes. The first number in brackets is the base attribute and  the second value is the modifier
The DK's pet has the following stats:
Strength: 3030 (331+2699)
Agility: 1011 (856+155)

The pet has an Attack Power of 4021 which is being calculated from:
3030-20+1011

Coming to the base armor part:
In mania the base armor of the ghoul is fixed at 5007 which is much less if you consider that even lvl 80 northrend undead creatures have an armor value of 9729.
Even [Army of the Dead](https://www.wow-mania.com/armory/?npc=24207) ghouls have 9729 armor.

in this video https://www.youtube.com/watch?v=phwZkrTnjpA just after the DKs horn of winter runs out at 1:22, you can see that the armor value is 10472.
Since the ghouls armor only scales from direct buffs and not from the player's stats, it is safe to say that the ghoul's base armor here should be 10472 as well instead of 5007.

**What Should happen:**
The following needs to be implemented:

Base agility should be 856
Attack power formula should be: Ghoul strength - 20 + Ghoul Agility
Base Armor should be 10472

**Comment by svijetlo** [comment]
also in vi int of pet is 65  while here we have 103
also spirit of pet in vid is 109 here we have 90

**Comment by jeyrella** [comment]
Cannot be fixed at this time due to other hidden factors (hence the time oustanding), but will keep on the radar if it becomes possible
