### ISSUE TITLE
[Spell/DK] Scourge Strike Shadow vs Resistence

### ISSUE THREAD

**Issue by Keader** [WoWManiaUK/Redemption#5782]
**Links:**

https://github.com/WoWManiaUK/Redemption/issues/5778#issuecomment-1086845775

**What is Happening:**

Spell can be resisted

**What Should happen:**
Spell should ignore resistences

**Comment by svijetlo** [comment]
![WoWScrnShot_040422_175409](https://user-images.githubusercontent.com/61908373/161583490-006acdc6-9bbc-4265-8fdb-196186587b8c.jpg)
SHADOW PART  of scurge strike will pass even if target has effect to block physicals part of spell
