### ISSUE TITLE
[Quest] Messenger to the Feralfen - Generic text talking to Elder Kuruti

### ISSUE THREAD

**Issue by stealer0517** [WoWManiaUK/Redemption#5783]
https://tbc.wowhead.com/quest=9803/messenger-to-the-feralfen
https://www.youtube.com/watch?v=TRl7pNpCc88&t=32s
https://youtu.be/An_cGzmffgg?t=65

Currently when you transform into bird spirit and talk to Elder Kuruti every line of text from him is "Greetins, (name)."
The text you say to him is correct, but he is missing 
![messenger to the feralfen](https://user-images.githubusercontent.com/6968045/161454631-63b8ebd6-d680-47d5-a735-0ef30a172b21.png)

In the linked above you tube videos you can see the text Elder Kuruti says at every step of the conversation instead of having this weird one sided conversation.

**Comment by Echinaceax** [comment]
confirmed bug 

https://i.gyazo.com/c68cda18b8e533b3af77468343881130.mp4

**Comment by Rushor** [comment]
added the npc texts :)

**Comment by Echinaceax** [comment]
Confirmed fixed in PTR 

https://i.gyazo.com/8a2344277c4cf85e2509f2912372a04f.mp4
