### ISSUE TITLE
[Quest] Tirion's Gambit - NPC movement speed too slow & threat too low

### ISSUE THREAD

**Issue by Angryyeti69** [WoWManiaUK/Redemption#5784]
**Links:**
https://www.wow-mania.com/armory/?quest=13364

**What is Happening:**
-Lich King is taking a long time to walk into the RP scene.
-Cultis are surrounding the player, while in disguise, once the main fight starts.
-Heroes do not pull agro from mobs

**What Should happen:**
-Lich King should enter a little quicker
-Disguise should negate Cultists from targeting player
-Heroes should pull agro from player so as to prevent multiple elites from ganging up on them.

**Comment by Echinaceax** [comment]
> can you link a video how it should be

only vid i can fine is 2011 https://www.youtube.com/watch?v=4Efu3fmmvM4

other vid from 2009 was in cat form

**Comment by svijetlo** [comment]
https://www.youtube.com/watch?v=9RFJ9rkZ3S8&ab_channel=RawxorTank

**Comment by svijetlo** [comment]
LK need to be faster , 
having cultist robes on will make you friendly to them 
npc that show up need to nuke down cultists

**Comment by Angryyeti69** [comment]
I don't know if this will help or not, but I noticed, in the video Svijetlo linked, that there were two npc's that knelt and gave a report prior to the LK entering. They were not present in my playthroughs of the quest. 

Sent from Yahoo Mail on Android 
 
  On Tue, Apr 5, 2022 at 13:47, ***@***.***> wrote:   


LK need to be faster ,
having cultist robes on will make you friendly to them
npc that show up need to nuke down cultists

**Comment by svijetlo** [comment]
i just did this quest on PTR it looks 99.9% same as in vid i link. 
i will upload and post video i recorded later
only tiny problem i see is that 3 cultist were following me around but they never attacked me

**Comment by svijetlo** [comment]
https://mega.nz/file/SfpBWQLA#1II3UKMmrfm7Z9vbASaacWX4TAoPGOv9XcY7sSnWMeo

what can be changed, 
3 npc that follow at start of quest need t o be faster
at the end heroes that come to help need to run in not walk in 
P.S. some bits are missing to me as i added quest did not get to it throe questline

**Comment by Rushor** [comment]
alright will handle the 2 points:

- 3 npc that follow at start of quest need t o be faster
- - at the end heroes that come to help need to run in not walk in

**Comment by Rushor** [comment]
added the above things

**Comment by svijetlo** [comment]
looks better to me much better will upload vid later
