### ISSUE TITLE
[NPC] Kael'thas Sunstrider (Magisters Terrace) resetting

### ISSUE THREAD

**Issue by tomaszpalasz** [WoWManiaUK/Redemption#5785]
https://www.wow-mania.com/armory/?npc=24857

**What is Happening:**
Final boss in Magisters Terrace is resetting after Gravity Lapse ability (used at 50% of hp). He is losing aggro, going back to starting position and resetting hp to 100%.

**What Should happen:**
Boss should not reset :-)

**Comment by Greywolf59** [comment]
Last time I was there: 3 or 4 days ago on Naxx realm with full party and everything worked fine, maybe just the arcane aoe bubbles are not moving that much sometimes.

**Comment by tomaszpalasz** [comment]
I was there yesterday and it happened few times on HC. We asked GM for help: he killed and respawned boss for us but it happened again. We DPSed until 50%, boss used Gravity Lapse, party (2 man) went up, bubbles appeared and boss reseted to 100%

**Comment by Rushor** [comment]
fixed https://gyazo.com/5bf9f3c6f76f16f43948b7dbccd09d1f
