### ISSUE TITLE
[Raid] LK invisibility in phase 3 of heroic encounter - ICC

### ISSUE THREAD

**Issue by theonykry** [WoWManiaUK/Redemption#5789]
**Links:**

**What is Happening:**
Summary:
After the raidgroup is teleported out of the Frostmourne room in phase 3 of the HC lk encounter, Lich King himself and the whole raid party is invisible for all raid members for a few seconds.  
LK and raidparty being invisible leades to 4 major things: 0 reaction time on the defile mechanic, untrackable threat table, addon timers bugging out for future defiles, loosing set focus on LK.

This happends at the moment we are teleported inside as a raid, i have noticed that i lose my focus that i put in LK, as we enter FM room. Previously that never happend. 
As you can imagine LK being invisible after we leave FM room is rather inconvienient, since the defile mechanic is taking place on a random raider right afterwards. LK and raiders being invisible gives us like 0 time to react to it and we also cant see in what direction people are spreading, since we can only see the defile and other players, once the defile is dropped on the ground. Also this bug resets/bugs out DBM timers (defile ones) and also the marking of the person (the marking takes place but is not visible till after the defile is dropped making it useless). Another bug that comes along is the Threat table which seems to be untrackable by addon and ingame interface once FM is left (even for the Main Tank on LK). 

This "bug" is similar to Halion encounter, but there atleast the MT can still see it (in phase 2 atleast), whereas in phase 3 of that encounter none can see it, unless somebody gets close to overaggro.

i was not the only one in the raid to experience this, so its not something hard/software related or related to my settings ingame, just wanted to clarify that.

**What Should happen:**

**Comment by svijetlo** [comment]
this need to be high prio i just did raid this is horrible

**Comment by mfranca0009** [comment]
I will be testing this with Svijet and others soon, I already have a solution for the LK visibility issue.

Just need the testing portion to figure out the player visibility problem.

**Comment by svijetlo** [comment]
https://mega.nz/file/bXgHAYgR#4yQRDHhCyfWtRYpWrw8nov24lWyrW-U7E2yp86f2Ye0

big thx to all tester for help =) <3
