### ISSUE TITLE
rogue assassination - glyph of hunger of blood

### ISSUE THREAD

**Issue by Jeanpko** [WoWManiaUK/Redemption#579]
Hi, I have a little bug with my rogue assassination. I'm using the glyph of hunger of blood, which increases damage by 3%. Additional to the normal skill that increases by 5%. To give a total of 8%. 

The problem is that when I use the skill only increases me 5%. The bug is that the account does not take the additional 3% of the glyph. Please, could you check that? 

User: Jeanpko Character: Scheise 

Thanks and regards.

**Comment by wow-mania** [comment]
Can you test again after today's patch.

**Comment by Plege** [comment]
I did extensive testing on target dummy today.
2 settings 
1 no HfB used to get a baseline on my damage with only autohits and poisons
2 with HfB and HfB glyph 

i did exactly 8% more damage on all poisons, abilities and autohits

so if the problem persists it seems to be with your character

Regards

**Comment by fvicaria** [comment]
@Plege Thanks for the feedback . I will close this issue.
