### ISSUE TITLE
VIP XP rate not changeable

### ISSUE THREAD

**Issue by Michael08111997** [WoWManiaUK/Redemption#5790]
**Links:**

**What is Happening:**
I purchased a VIP Token, but I cannot change my XP rate. Everytime I want to change it it says only VIPs can do that. Went to the mall and cant change it there either. 

**What Should happen:**
Please help resolve the issue so I can change the XP. The character name to which the vip account is linked is called Vuurnoster.

**Comment by Echinaceax** [comment]
After opening your mail, relog and its done @Michael08111997
