### ISSUE TITLE
[NPC] NPC's Pets Mis-Balance HP - Thunder Ridge 

### ISSUE THREAD

**Issue by PoliteTim** [WoWManiaUK/Redemption#5791]
**Links:**

Screen Shots: https://imgur.com/a/mCKGLkw

**What is Happening:**

Fizzle Darkstorm's Imp Minion in Thunder Ridge has considerably more health, mana, and I am assuming stats than it should, making it too difficult to fight at the appropriate level.

**What Should happen:**

Resetting of the minion's stats to a more appropriate amount for a level 12 imp.

**Comment by Echinaceax** [comment]
- [ ] Fizzle Darkstorm and his imp https://www.wow-mania.com/armory/?npc=3203 https://i.gyazo.com/c739787c1cdf789090b6f93c0f92555c.mp4
- [ ] Burning Blade Apprentice void walker https://www.wow-mania.com/armory/?npc=3198
https://i.gyazo.com/78d771c8d65ea34d24432cb98b12e6af.mp4

Note
I looked for a video and not one of them showed the HP on their name plate in numbers 😞 

so not sure what the HP should be, but its definately to high for a level 11-12 mob pet when the masters HP is lower

**Comment by Rushor** [comment]
it cannot be reduced more, but it should be much better and normal now

**Comment by Echinaceax** [comment]
confirmed fixed 

![image](https://user-images.githubusercontent.com/39439201/163167601-1492f092-dabe-441d-b59e-14d70c11d8ad.png)
![image](https://user-images.githubusercontent.com/39439201/163167664-49ce4cb5-6b93-4957-83d5-b3cc300a531d.png)
