### ISSUE TITLE
[Dungeon] Razorfen Kraul Wall Break causes falling through texture

### ISSUE THREAD

**Issue by PoliteTim** [WoWManiaUK/Redemption#5792]
**Links:**

Screenshots: https://imgur.com/a/oMjALKU

**What is Happening:**

A section of the wall in Razorfen Kraul can be walked up and over, causing the player to fall into the floor of the instance. This section is just behind Overlord Ramtusk. **This may happen in other areas of the wall, though I was unable to check.**

**What Should happen:**

I am unsure if there should be an invisible wall here or if the geometry should be at a higher angle, but this shouldn't happen.

**Comment by Echinaceax** [comment]
https://i.gyazo.com/d00f9f12e553858542ff22984f344237.mp4

**Comment by Rushor** [comment]
should be better now

**Comment by Echinaceax** [comment]
confirmed fixed

https://i.gyazo.com/571e9f4abf84cb18362cdd15b8aa304f.mp4
