### ISSUE TITLE
[Wintergrasp] Wintergrasp additional Fixes / Checks 2

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Redemption#5793]
- [ ] Both flags visible 

![both flags visible](https://user-images.githubusercontent.com/39439201/163356999-09689612-8873-472c-8621-3f699081e246.jpg)

GPS 
![image](https://user-images.githubusercontent.com/39439201/163357280-f59dc471-8cdb-4916-813b-e316c5cd63c7.png)

- [ ] Flags stacked - one stuck in the wall 
![2 flags stacked - wrong flag ](https://user-images.githubusercontent.com/39439201/163357640-648aacaf-238f-4a02-bcce-0471312000af.jpg)

GPS 
![gps on flag1](https://user-images.githubusercontent.com/39439201/163357950-c1d68e53-6cd2-48d2-96e0-4607dcc2ad0b.jpg)

- [ ] flag stuck in the wall 2
![flag in the wall](https://user-images.githubusercontent.com/39439201/163358299-22ceeb3b-ee57-4018-81df-a851fdf6137f.jpg)

GPS
![gps flag2](https://user-images.githubusercontent.com/39439201/163358343-85a4cd0f-3039-4e0c-83ba-e6d5911683a1.jpg)

- [ ] Flags visible only with gm on
![invisible flags](https://user-images.githubusercontent.com/39439201/163358651-621a73b0-f785-4229-9745-db87edbbf8be.jpg)
![visible only with gm on](https://user-images.githubusercontent.com/39439201/163358666-81e22f73-87e3-426c-805c-a4b9f5766bad.jpg)

GPS
![2b Flags visible only with gm on](https://user-images.githubusercontent.com/39439201/163362510-5269872f-d409-4005-9c97-fb7290b3f9dd.jpg)

- [ ] Pole visible only with gm on
![pole missing](https://user-images.githubusercontent.com/39439201/163358867-037403f0-f71f-4b2e-8132-fa0c2519dd9a.jpg)
![pole visible only with gm on](https://user-images.githubusercontent.com/39439201/163358877-c26f9a06-148d-4e1c-91c3-f32b32189791.jpg)

GPS 
![GPS missing pole ](https://user-images.githubusercontent.com/39439201/163359016-901f939e-2669-43c0-8735-ea600a1427c8.jpg)

- [ ] missing Ally flag1
![missing Ally flag1](https://user-images.githubusercontent.com/39439201/163359180-8dae118c-0343-489a-941a-512bc613b2ff.jpg)

GPS
![gps missing Ally flag1](https://user-images.githubusercontent.com/39439201/163359249-69d7badb-d6b3-487c-9be2-3406e85da257.jpg)

- [ ] missing Ally flag2
![missing Ally flag2](https://user-images.githubusercontent.com/39439201/163359355-e3440f29-0c1b-4386-8ad4-2d5e67e5b2cc.jpg)

GPS
![gps missing Ally flag2](https://user-images.githubusercontent.com/39439201/163359414-d179ea4e-fd8b-45b5-80d1-18b7e8355af0.jpg)

- [ ] visible only with gm on 2
![visible only with gm on 2a](https://user-images.githubusercontent.com/39439201/163362942-073526b5-54b3-4c90-a450-0937726f07d8.jpg)
![visible only with gm on 2](https://user-images.githubusercontent.com/39439201/163362955-d199ba3e-35bb-4f32-adcf-ad07ef84349e.jpg)

GPS
![GPS visible only with gm on 2](https://user-images.githubusercontent.com/39439201/163363002-f9ff6caa-d90c-4780-b096-fde451f8fd89.jpg)

- [ ] wrong horde flag size
![wrong horde flag size](https://user-images.githubusercontent.com/39439201/163363305-7b9976cd-fd05-431c-aeae-3f0a8a94eb68.jpg)

GPS
![GPS wrong horde flag size](https://user-images.githubusercontent.com/39439201/163363400-ceabf1eb-8d1d-4b98-bdfb-2c283b20e78e.jpg)

- [x] The "leave Wintergrasp" Icon on the minimap doesnt work  (fixed) #5875
![leave WG ](https://user-images.githubusercontent.com/39439201/163359804-8aa6eaf3-9f9e-4e27-acb8-630b570d2287.jpg)

- [ ]  Incorrect time for next battle
![TIMER OFF](https://user-images.githubusercontent.com/39439201/163848692-f6e4a975-e324-499a-87a5-713593f97502.jpg)

- [ ] WG time bug (visual bug only)
![image](https://user-images.githubusercontent.com/39439201/163863525-9814376c-6f4c-41b0-b36e-93f609149eb7.png)

- [ ] You have been called to join (window) sticks at 1 sec 
the timer gets to 1 and stays there doesnt kick

![image](https://user-images.githubusercontent.com/39439201/165146969-9ad229b2-a745-4231-9540-473d16464487.png)

**Comment by wow-mania** [comment]
won't be fixed at this time unless it impairs the battle
