### ISSUE TITLE
Died in neitherland

### ISSUE THREAD

**Issue by bigonexeon** [WoWManiaUK/Redemption#5795]
**Links:**

**What is Happening:** im in ghost mode and in the chasm in netherstorm as a ghost and cant get out 

**What Should happen:**
![Screenshot_2](https://user-images.githubusercontent.com/103865302/163695683-5fffd6a5-1365-462d-88fb-d51ab4bc9a8f.png)
![Screenshot_1](https://user-images.githubusercontent.com/103865302/163695690-cd861f7e-a390-45a3-903c-9d6c0c692143.png)

**Comment by Rushor** [comment]
please contact a gamemaster to resolve this via ingame ticket. thank you!
