### ISSUE TITLE
stuck in netherstorm chasm in ghost mode

### ISSUE THREAD

**Issue by bigonexeon** [WoWManiaUK/Redemption#5796]
**Links:**

i am stuck in ghost mode in the chasm at the crumbling chasm 

its not resetting me at the top of the cliff
![Screenshot_2](https://user-images.githubusercontent.com/103865302/163720376-070a33cf-55d7-45af-9441-0edd36bb9fb7.png)
![Screenshot_1](https://user-images.githubusercontent.com/103865302/163720383-387786ff-88be-48b5-b14d-76af40577f4d.png)

**Comment by svijetlo** [comment]
send in game ticket or use stuck option

**Comment by bigonexeon** [comment]
where the game ticket option or use stuck option ?

**Comment by Echinaceax** [comment]
> where the game ticket option or use stuck option ?

Use the ❓ ingame to make a ticket @bigonexeon

**Comment by jeyrella** [comment]
or the command /gm
