### ISSUE TITLE
[CLASS] [WARLOCK] Inferno does not use aura automatically

### ISSUE THREAD

**Issue by Greywolf59** [WoWManiaUK/Redemption#5797]
**Links:**
https://github.com/WoWManiaUK/Redemption/issues/3616

https://www.youtube.com/watch?v=aqvgRj9qJvM
"counter-video" to the post above
TIMESTAMPS: 3:25 (Wotlk proof); 4:00 (Inferno in action on DUMMIES)

https://www.wow-mania.com/armory/?spell=24826

Infernal Aura: https://tbc.wowhead.com/spell=24826/infernal-fire
95% sure it is the right one, sorry for TBC wowhead but wanted to find pre-cata or whatever the patch is that introduced the 15% proc

https://wowwiki-archive.fandom.com/wiki/Summon_Infernal?direction=prev&oldid=2412209
Linekd revision is from 12 June 2010, so near the end of WotlK times and prior to Cata

https://redmine.rising-gods.de/issues/6276
I am not 100% versed in German but DeepL helps to fill in the gaps. Anyway on that server on this particular issue worked Rushor himself apparently.

**What is Happening:**
Infernal should have its aura active. The 15% proc chance form melee hits had to be adden in some later patch without being mentioned in patch changes, at least i haven't found anything.

**What Should happen:**
Infernal should have the aura automatically. Why?
1: I am definitely sure there would be a mention on wowwiki about the fact it has to be procced. (the link to inferno there, is link to the new one, can't find the old versions/revisions)
2: The video shows aura affecting dummies
3: Link from TBC wowhead doesn't mention any proc
4: Rushor himself worked on it elsewhere and it was bug that was fixed at the end (also after some discussion) if I am not wrong.

**Comment by svijetlo** [comment]
https://wowwiki-archive.fandom.com/wiki/Immolation 
from what i found out poet need to have active aura form link form the moment pet is summoned , ID spell for this pet is 1122, 
atm he does not have it only does melee hits on target 
![WoWScrnShot_041822_153306](https://user-images.githubusercontent.com/61908373/163815939-0d2e13bc-5101-4166-85a0-b42882dc404e.jpg)

**Comment by Greywolf59** [comment]
@svijetlo How can you attack your own pet? And no, I don't see it, can you provide more description and the time?

**Comment by svijetlo** [comment]
as i seen and form all web pages it points out spell works as it should , it will only proc if pet get attack ....

**Comment by Greywolf59** [comment]
Well as long as it is procced by ANY AND ALL damage i guess it is fine enough. Cause I read on some other forums ppl used it on valks or on last minute of boss and there is no way there would be using it if it wouldn't be procced by auras, aoes etc, cause boss would never melee the infernal. I don't ahve a way to test that atm, my lock is on Naxx, no lock on Red.

**Comment by svijetlo** [comment]
i had no gear on my toon , toon is basically naked , items on it is just for look 
as it states **When the Infernal takes damage,** it has a 15% chance of bursting into fire doing damage to all who strike it for until cancelled.
so when he take DMG any dmg it will proc not just if you hit it directly

**Comment by Rushor** [comment]
yeah i remember it, but we need to add more research to that. More sources.

currently spells says: spell=4525 When the Infernal takes damage, it has a 15% chance of bursting into fire doing damage to all who strike it for until cancelled.

And indeed the spell only proccs (and handles the Trigger spell (4524) Demonic Immolation)  when the pet:
Taken damage from melee strike hit
or
Taken damage by Spell that use melee weapon

**Comment by Rushor** [comment]
Okay so when watching this: https://youtu.be/aqvgRj9qJvM?t=253 you can see, that the spell also proccs when the creature simply DOES melee hits (and not TAKE hits like in spell description)

But i would like to get more proof on that to be sure

**Comment by svijetlo** [comment]
i search web far and wide and could not find anything that indicates that it should work on its own ,

**Comment by Greywolf59** [comment]
I ask for reopen: found another video visibly showing the aura is automatic: https://www.youtube.com/watch?v=bDYEzGV8-U4&t=396s
Timestamp: 6:34

**Comment by Greywolf59** [comment]
I have asked a person who plays on Naxx realm and also on TBC classic, if he could ask around on classic about infernals. That person who goes under name Ziax on Naxx realm replied to me today that on TBC classic the aura is automatic. I know classic is different but still it makes this post more valid.

"@Ziax Hey man! You are playing on TBC classic, right? Could you please ask around if warlock's infernal aura is automatic or if the infernal needs to be hit by attack to actuvate it? Would help a lot :)

30 April; Ziax: Sure m8 ill ask

2nd May; Ziax: Its automatick as long you are within range you will dmg mobs"

Bump @svijetlo
