### ISSUE TITLE
Having issue with Finding/Tracking Minerals

### ISSUE THREAD

**Issue by Necr0phagist** [WoWManiaUK/Redemption#5798]
**Links:**

**What is Happening:**
By using Find Minerals the tracker is getting stucked into this function. If I want to be able to use Find Herbs I have to manually change the tracker on something random like "Mailbox" then use Find Herbs. The issue is reappearing as soon as I'm using Find Minerals

**What Should happen:**
The tracker should normaly be able to switch between any tracking without being stucked on minerals

**Comment by Echinaceax** [comment]
Confirmed bug
Me and Phoenix found this issue before just got destracted from reporting it 

https://i.gyazo.com/612f582dba2a85a2ab0c581f4d2f1520.mp4

From the mini map player should be able to switch from one tracket to another, At the moment you have to click on mailbox to trigger it to work 

thanks @Necr0phagist

**Comment by jeyrella** [comment]
Hi
Thanks for your report. This is known and actually deliberately left as is - there is no actual need to switch between them as this way both can be sensed at the same time.  This is a deliberate decision as the alternative is one of the most complained about annoyances of WotLK - inability to farm both herbs and minerals at the same time without an addon to force switching.

**Comment by Necr0phagist** [comment]
If I understood well, my english clearly isnt good enough, this bug won't gonna be fixed and my only alternative is to use an add-on forcing the switch ? 
Thx you for your reply.

**Comment by jeyrella** [comment]
No. It will not be fixed, **because** the way it is now means you do not have to use an addon to force switching. It actually senses both ores and herbs on the map at the same time right now, even though it only says one is tracked in the interface. 
We want to leave that functionality in place.

**Comment by Necr0phagist** [comment]
Hooo, well dat's even better this way for me then :D
Thx you for answering !
