### ISSUE TITLE
Quest [The Nightmare Manifests] don't work

### ISSUE THREAD

**Issue by ivobb1** [WoWManiaUK/Redemption#5799]
**Links:** The Nightmare Manifests

**What is Happening:** there are 2 issues when you get the quest. 1st - NPC (Keeper Remulos) just don't move and don't start any conversation, just nothing happen. 2nd - After accept the quest NPC (Keeper Remulos) do exactly what he should do, moving to are named Nighthaven and summoning  dragon named Eranikus then moving back and dragon follow him then dragon summoning some dark shades (Nightmare Phantasm) they attack, at some point dragon also start to attack you. The only thing that you should do it's hold them for like 7-8 min then Tyrande have to came and save the day and quest is done. However when that even start shades spawn, they start to attack you, dragon also start to attack, then at some point dragon just vanish, shades remind till you kill them, Keeper Remulos stay there and do nothing, then suddenly he start running back to his first place at Shrine of Remulos (the location in Moonglade that he inhabits), and quest remind uncompleted.

**What Should happen:**

**Comment by jeyrella** [comment]
@Rushor Has #4520 regressed here?  if so we should reopen that one

**Comment by svijetlo** [comment]
this used to work like month or so i ago we did it for 2 players

**Comment by Rushor** [comment]
It's the General issue that Escort creatures sometimes Simply wont Start. Not specific issue. Most likely fixed after next restart
