### ISSUE TITLE
[Talent] Mage - Missile Barrage

### ISSUE THREAD

**Issue by philoudu16** [WoWManiaUK/Redemption#580]
The mages' talent Missile Barrage doesn't seem to work correctly. The proc rates are fine, but when it does proc, you only fire two missiles (basically the rate of fire doesnt change, only the cast duration). We have tested things out with the gm Ichigo, and every race (horde at least) has the same issue.

**Comment by Shanksalot** [comment]
This is also happening on my Arcane Mage. -Rejuv-

**Comment by Kalasbyxan** [comment]
My understanding is that this is an issue different from the proc of the buff Pushing the Limits. This seem to be the Arcane Missiles spell that should fire 5 bolts of arcane over 5 seconds but only fire 2.

**Comment by Emcitementz** [comment]
Fixed on Wednesday.

**Comment by elagen** [comment]
i can confirm when using arcane missile without Missile Barrage http://wotlk.openwow.com/spell=54490
you can fire 5-6 Missiles from the Arcane Missile

when Missile Barrage http://wotlk.openwow.com/spell=54490 is Proc'd you only fire 2 Missiles from Arcane Missiles

**Comment by fvicaria** [comment]
I am closing this one as we are discussing similar issues on the other bug on Mages.
