### ISSUE TITLE
Hunter pulls agro when pet should be pulling/holding agro

### ISSUE THREAD

**Issue by tgrdrgn19** [WoWManiaUK/Redemption#5801]
**Links:**
None

**What is Happening:**
Pet starts combat, but target comes to eat my face off.  Feign death disengages combat completely, even for pet.  When forced into melee combat, traps aren't set off by the target either.

**What Should happen:**
Tenacity pet should be able to hold agro for the most part, especially when pet talent points are spent correctly and feign death/traps should work properly.

**Comment by tgrdrgn19** [comment]
This is happening in the SE corner of Dragonblight where the ghosts are.

**Comment by Rushor** [comment]
can you tell me the exact name of the creatures that are doing so. Often it is just a AI script issue of a single creature group

**Comment by mfranca0009** [comment]
@Rushor 
In regard to the aggro issue,

This is a known problem that I've faced myself on a play toon. It's a clear issue with hunters, a hunter will send a pet in first so it gains threat and tanks. However, in many circumstances the mob will randomly start aggroing the player; this happens especially when a pathing mob walks by and your pet aggros it.

The second pathing NPC will aggro, but instead of going to the pet, it automatically aggros to the player. This is a generic issue and doesn't pertain to individual NPCs.

**Comment by kamoodle5** [comment]
I've witnessed this similar behavior with a different mob (although this one likes the hunter's pet a tad more), which I can post as a new issue if necessary.

**Comment by jeyrella** [comment]
Hetah please test & document this.

**Comment by Franciss983** [comment]
Will do.

po 25. 4. 2022 v 19:21 odesílatel jeyrella ***@***.***>
napsal:

**Comment by Franciss983** [comment]
I did test it like this using skada details (tiny threath) and (Omen3) addons for threath tracking.
Target used: Hulking Abomination NPC ID: 31140
https://www.wowhead.com/npc=31140/hulking-abomination

1. Ferocity pet 80 level wolf with ACTIVE (Growl rank 9).
Omen3: Pet is generating like 539 threath per second. I was not shooting and NPC did not randomly reset aggro on hunter.
https://gyazo.com/c8e6d8d80c2c31e829468a88b41edf2b

2. Ferocity pet 80 level wolf with INACTIVE (Growl rank 9).
Omen3: Pet is generating like 371 threath per second. I was not shooting and NPC did not randomly reset aggro on hunter.
https://gyazo.com/7f32e133d7b34ae8ddd5cdffea151cc1

3. Tenacity pet 80 level crab with ACTIVE (Growl rank 9). 
Without Guard Dog talent http://www.wow-mania.com/armory?spell=53179
Omen3: Pet is generating like 600-720 threath per second. I was not shooting and NPC did not randomly reset aggro on hunter.
https://gyazo.com/9cd8e783e5e5059cba1c4053afd48f5a

4. Tenacity pet 80 level crab with INACTIVE (Growl rank 9). 
Without Guard Dog talent http://www.wow-mania.com/armory?spell=53179
Omen3: Pet is generating like 440-515 threath per second. I was not shooting and NPC did not randomly reset aggro on hunter.
https://gyazo.com/8e646110ca66c136b0a10c27dffe70e0

5. Other test was walking around npc with pet on follow+defensive. NPC did attack me first then pet started attack and the following NPC didnt reset aggro on me (on hunter). Also I was not shooting.

6. Frost trap triggering test in melee range without feign death (also with feign death used trap is instantly triggering.
https://gyazo.com/f60dca098858b1fd93546e7f450ed59a

8. My hunter for testing has been generating about 5500-7200 TPS and tenacity pet used with ACTIVE (Growl rank 9) + talented Guard Dog (http://www.wow-mania.com/armory?spell=53179) is generating 600-720 TPS. So the pet can hold aggro only like for 1 second after pull.

But If I open with my rotation with Misdirection on the pet (pet with active Growl and talented Guard Dog) and when I am about to overaggro him I did use feign death and again Misdirection on every cooldown I able to maintain his aggro for a bit longer.

If you need additional testing or specific informations tell me.

**Comment by Franciss983** [comment]
**Beastmastery Build**

Tracking aggro with Omen3 on Target Dummy (80)

**Beastmastery build + Tenacity pet Crab**
1. Crab (tenacity pet) - **(Autoshoots only - no hunter spells)** pet doing 1500-1750 TPS - Hunter doing 1600-2500 TPS
https://gyazo.com/91f51f767600d68d9b71ee00f9872913

2. Crab (tenacity pet) - **(Using all spells)**  - pet doing 1700-1900 TPS - Hunter doing 4000-7500 TPS
https://gyazo.com/8fcd9570f67c1b10c6c7f5d3dc81f6f8

3. Same situation like 2. but with MD to pet and Feign Death = I did overaggro the pet.

**Beastmastery build + Ferocity pet Devilsaur**
4. Devilsaur (Ferocity (Exotic)) - **(Autoshoots only - no hunter spells)** pet doing 2000-2300 TPS - Hunter doing 1700-2650 TPS
I wasnt able to overaggro the pet!
https://gyazo.com/05844aeb41b0c7f1d0f349daf4eec108

5. Devilsaur (Ferocity (Exotic)) - **(Using all spells)** pet doing at max 5300 TPS - Hunter doing at max 8500 TPS
https://gyazo.com/05049df7cea028d0fa9e61e272d6d1ac

6. Same situation like 5. but with MD to pet and Feign Death = Pet is able to maintain and hold aggro!
https://gyazo.com/ee0caf7d383957cc369909c9fb0f8201

**Beastmastery build + Cunning pet Chimerae**
7. Chimerae (Cunning (Exotic)) - **(Autoshoots only - no hunter spells)** pet doing 1500-2000 TPS - Hunter doing 1800-2400 TPS
https://gyazo.com/5c466ab27eb0b565ef05ab2984636c86

8 Chimerae (Cunning (Exotic)) - **(Using all spells)** pet doing at max 2600TPS - Hunter doing at max 6000 TPS
https://gyazo.com/8297fbeb6a5d8e2621fd5e521e6c247f

9. Same situation like 8. but with MD to pet and Feign Death = I did overaggro the pet.

My result for this test: 
Hunter has been able to hold more aggro than pet in case 1. 2. 3. 5. 7. 8. 9.
Pet has been able to hold more aggro than hunter in case 4. 6.

If Its needed any specific testing on specific NPCs/with pets/build let me know.

**Comment by Franciss983** [comment]
> **Links:** None
> 
> **What is Happening:** Pet starts combat, but target comes to eat my face off. Feign death disengages combat completely, even for pet. When forced into melee combat, traps aren't set off by the target either.
> 
> **What Should happen:** Tenacity pet should be able to hold agro for the most part, especially when pet talent points are spent correctly and feign death/traps should work properly.

What build and pet are you using?

**Comment by Rushor** [comment]
some aggro issues possible related to the inhabittype as i fixed it in https://github.com/WoWManiaUK/Redemption/issues/5811
