### ISSUE TITLE
[NPC] Underbog Lurker - Text Not Showing Name of Player's Pet

### ISSUE THREAD

**Issue by kamoodle5** [WoWManiaUK/Redemption#5802]
https://tbc.wowhead.com/npc=17725/underbog-lurker

**What is Happening:** When engaging one of these mobs, the text "Underbog Lurker grows in size upon seeing (name)" will appear. If I attack first, my player's name shows as normal; however, if my pet engages, its name shows as "$n". Likely, this is identical for any other class pet/minion.

**What Should happen:** The pet's name should show within this text, not as $n.

![WoWScrnShot_042422_174558](https://user-images.githubusercontent.com/67519835/165018520-f6d290e0-a870-48e1-b8a0-aa64b6471c71.jpg)

**Comment by Rushor** [comment]
Is a creature ai targeting issue, should be solved now

**Comment by Echinaceax** [comment]
NPC sees player and displays name 

![image](https://user-images.githubusercontent.com/39439201/165179930-d80d7c99-1fec-452f-ac91-b6963c5a26c6.png)
