### ISSUE TITLE
[Item] Mall teleportation stone cooldown reset

### ISSUE THREAD

**Issue by Airin258** [WoWManiaUK/Redemption#5804]
**Links:**
https://www.wow-mania.com/armory/?item=90044

**What is Happening:**
After using with specific portals in mall (Ironforge, Darnassus, possibly others) portal stone CD was reseted. I was able to visit 3 capitals in 10 minutes. Also i saw messages about similar issue in in-game chat.

**What Should happen:**
Stone CD shoud be 1 hour and should not reset.

**Comment by mfranca0009** [comment]
@Airin258 
This is not a server-side problem. Please clear your cache when you open the launcher, then launch the game.

This will be corrected once we release our next client update.
