### ISSUE TITLE
[Boss/Enemy/Mechanic] Val'kyr Shadowguard - phase 2 LK heroic encounter

### ISSUE THREAD

**Issue by svijetlo** [WoWManiaUK/Redemption#5805]
**Links:**

http://www.wow-mania.com/armory?npc=36609
http://www.wow-mania.com/armory?npc=39125
https://www.wowhead.com/npc=39125/valkyr-shadowguard-hover-height-20-visual
https://www.wowhead.com/npc=36609/valkyr-shadowguard
https://wowpedia.fandom.com/wiki/Val%27kyr_Shadowguard
http://www.wow-mania.com/armory?spell=73488

**What is Happening:**
During Lk 25hc encounter Val'kyr Shadowguard stay on fight planform after they drop players , making huge mess what can be seen on SS 
![WoWScrnShot_050122_224339](https://user-images.githubusercontent.com/61908373/166170596-54e1a0f7-fccf-4d57-9923-52f166254ad1.jpg)

**What Should happen:**
During Lk HC encounter in phase 2 Val'kyr Shadowguard will grab 3 random ( 1 random in 10HC ) player carry them to edge of platform and try to drop them 
rest of groupd dmg Val'kyr Shadowguard to 50% hp 
at 50% Val'kyr Shadowguard will drop player and fly in to air above middle of platform stay there for rest of phase 2 and cast http://www.wow-mania.com/armory?spell=73488 on players in raid 
https://youtu.be/_QcuB8zCpu4?t=362  this vid shows it perfect

**Comment by Rushor** [comment]
wull inspect

**Comment by mfranca0009** [comment]
All fixed, nice and smooth now it seems (both on 50% health dropping player, and when a player is dropped off edge). 👍

**Comment by Echinaceax** [comment]
Comfirmed fixed in PTR 👍 

https://i.gyazo.com/346667f951e78d8f10433eae03b52ad9.mp4

**Comment by svijetlo** [comment]
> Comfirmed fixed in PTR 👍
> 
> https://i.gyazo.com/346667f951e78d8f10433eae03b52ad9.mp4

looks lovely thx for help =) <3
