### ISSUE TITLE
[NPC] Wintergrasp cannons - Damage impact range to be checked

### ISSUE THREAD

**Issue by Hajzlopuc** [WoWManiaUK/Redemption#5806]
**What is Happening:**

Damage is wrong
Splash radius is wrong
Damage diminishing based on position from the point of impact is non-existant.

You take full damage (10k-also seems high into mail armor) in 20 yard radius. Indicator radius seems like 8 yards (maybe even 5) max to me.
Radius indicator reference - engineering belt which shoots Cobalt Frag Bomb (https://www.wow-mania.com/armory/?item=40771) 3 yard radius VS cannon indicator - https://puu.sh/IY49z/afd5c2237f.jpg https://puu.sh/IY49I/20a9eadbc3.jpg

https://puu.sh/IY3Zu/b16d2071b3.jpg
https://puu.sh/IY3ZD/29270bc1d2.jpg
https://puu.sh/IY3ZQ/a3b21434c7.jpg
https://puu.sh/IY400/cfc10859ce.jpg
https://puu.sh/IY40d/afcd928e61.jpg

Range reference, mage is just 1 step out of scatter range - 21 yards - https://puu.sh/IY43M/8c38e791e0.jpg

**What Should happen:**
https://www.youtube.com/watch?v=9crIb9L3wKo  2.5.2010, Cata dropped in december 2010 so this is still 3.3.5a.
https://www.youtube.com/watch?v=RDBsCn7DBSY 26.1.2010 
https://www.youtube.com/watch?v=IpLFiHiiBHQ 20.9.2008 (this seems like beta, also old indicator)

**Comment by Rushor** [comment]
assigning you because i think you added the mechanic for that if i remember correct

**Comment by mfranca0009** [comment]
@Rushor I did not add anything, but yes, Echi and I are investigating 👍
