### ISSUE TITLE
[ZONE] [NPC] Gjalerbron NPCs do not use spells

### ISSUE THREAD

**Issue by Greywolf59** [WoWManiaUK/Redemption#5807]
**Links:**
Gjalerbron Rune-Caster:
https://wow-mania.com/armory/?npc=23990
https://www.wowhead.com/npc=23990/gjalerbron-rune-caster#abilities
Gjalerbron Sleep-Watcher:
https://wow-mania.com/armory/?npc=23989
https://www.wowhead.com/npc=23989/gjalerbron-sleep-watcher#abilities
Gjalerbron Warrior:
https://wow-mania.com/armory/?npc=23991
https://www.wowhead.com/npc=23991/gjalerbron-warrior#abilities
https://www.wowhead.com/npc=23991/gjalerbron-warrior#comments:id=657419
the felsteed probably: https://wow-mania.com/armory/?npc=24020; https://www.wowhead.com/npc=24020/riding-horse-gjalerbron-felsteed-scale-x2
**What is Happening:**
Neither of the afformentioned NPCs is using their abilites. Comment about warrior mentions they can also ride felsteed and I haven't seen any. I might look into the rest of the NPCs there but for now this should suffice.
Disclaimer: All NPCS died within about 4s from engaging them in battle.

**What Should happen:**
They should use their abilities correctly.

NOTE: I have noticed possible missing mechanics in all around Howling Fjord, whole levelling there is I would say too easy and comfortable and many many NPCs even with mana just use basic melee attacks. But I haven't look into that really, it would need further investigation of the zone. I might try to check some more.

**Comment by Echinaceax** [comment]
close for new full report here #5808
