### ISSUE TITLE
[NPC] Howling Fjord - Missing NPC abilities

### ISSUE THREAD

**Issue by Greywolf59** [WoWManiaUK/Redemption#5808]
Added npcs as I encountered them in Howling Fjord and added them here when they seemed to be missing their abilities.

**Links:**

- [ ] Fanggore Worg:
https://wow-mania.com/armory/?npc=24026
https://www.wowhead.com/npc=24026/fanggore-worg#abilities
→ Missing Maim Flesh: https://www.wowhead.com/spell=50075/maim-flesh; https://wow-mania.com/armory/?spell=50075

- [ ] Gjalerbron Gargoyle:
https://wow-mania.com/armory/?npc=24440
https://www.wowhead.com/npc=24440/gjalerbron-gargoyle#abilities
→ Missing Gargoyle Strike (two kinds on wowhead 0o)
    https://wow-mania.com/armory/?spell=43803; https://wow-mania.com/armory/?spell=43804

- [ ] Gjalerbron Rune-Caster:
https://wow-mania.com/armory/?npc=23990
https://www.wowhead.com/npc=23990/gjalerbron-rune-caster#abilities
→ Missing Freezing Circle https://wow-mania.com/armory/?spell=34787
→ Missing Frostbolt https://wow-mania.com/armory/?spell=9672
→ Missing Rune Ward https://wow-mania.com/armory/?spell=43453 (redirected to tbc wowhead)

- [ ] Gjalerbron Sleep-Watcher:
https://wow-mania.com/armory/?npc=23989
https://www.wowhead.com/npc=23989/gjalerbron-sleep-watcher#abilities
→ Missing Sleep https://www.wowhead.com/spell=66290/sleep; https://wow-mania.com/armory/?spell=66290

- [ ] Gjalerbron Warrior:
https://wow-mania.com/armory/?npc=23991
https://www.wowhead.com/npc=23991/gjalerbron-warrior#abilities
https://www.wowhead.com/npc=23991/gjalerbron-warrior#comments:id=657419
the felsteed probably: https://wow-mania.com/armory/?npc=24020; https://www.wowhead.com/npc=24020/riding-horse-gjalerbron-felsteed-scale-x2
Missing Uppercut: https://www.wowhead.com/spell=10966/uppercut; https://wow-mania.com/armory/?spell=10966
Comment about warrior mentions they can also ride felsteed and I haven't seen any.
→ no felsteeds at all

- [ ] Putrid Wight:
https://wow-mania.com/armory/?npc=23992
https://www.wowhead.com/npc=23992/putrid-wight#abilities
→ Missing both Thunderclap and Plague Blight
→→ Thunderclap: https://wow-mania.com/armory/?spell=8078
→→ Plague Blight: https://wow-mania.com/armory/?spell=43506 (might need further testing, more hits)

- [ ] Fearsome Horror:
https://wow-mania.com/armory/?npc=24073
https://www.wowhead.com/npc=24073/fearsome-horror#abilities
Missing Infected Bite: https://wow-mania.com/armory/?spell=49861

- [ ] Necro Overlord Mezhen:
https://wow-mania.com/armory/?npc=24018
https://www.wowhead.com/npc=24018/necro-overlord-mezhen#abilities
→ Missing Raise Dead (most likely) https://wow-mania.com/armory/?spell=43559
→ Based on: https://www.wowhead.com/npc=24018/necro-overlord-mezhen#comments:id=656866
→→ Missing Drain Soul but I can't find the right ID, clicking the link in comment takes me tow tbc wowhead

- [ ] Glacion (NEEDS TESTING; I killed it from unreachable spot, killed me by pure melee before):
https://wow-mania.com/armory/?npc=24019
https://www.wowhead.com/npc=24019/glacion#abilities
→ might be missing Frost Breath https://wow-mania.com/armory/?spell=43562
→ might be missing Ice Blast https://wow-mania.com/armory/?spell=11264

- [ ] Fjord Crawler:
https://wow-mania.com/armory/?npc=24478
https://www.wowhead.com/npc=24478/fjord-crawler#abilities
→ Missing Claw Grasp https://wow-mania.com/armory/?spell=49978

- [ ] Rotgill:
https://wow-mania.com/armory/?npc=24546
https://www.wowhead.com/npc=24546/rotgill#abilities
→ Missing Enrage https://wow-mania.com/armory/?spell=8599
→ Missing Searing Wound https://wow-mania.com/armory/?spell=49956

- [ ] Mur'ghoul Flesheater:
https://wow-mania.com/armory/?npc=23644
https://www.wowhead.com/npc=23644/murghoul-flesheater#abilities
→ Missing Rend https://wow-mania.com/armory/?spell=13445
→ Missing Consume Flesh https://wow-mania.com/armory/?spell=37933 (hope it is the right one, wowhead redirected to tbc.wowhead here)

- [ ] Chillmere Tidehunter:
https://wow-mania.com/armory/?npc=24460
https://www.wowhead.com/npc=24460/chillmere-tidehunter#abilities
→ Missing Net https://wow-mania.com/armory/?spell=6533
→ Missing Throw (just runs to you and melees you) https://wow-mania.com/armory/?spell=38556 (redirected to tbc)

- [ ] Unstable Mur'ghoul:
https://wow-mania.com/armory/?npc=23643
https://www.wowhead.com/npc=23643/unstable-murghoul#abilities
→ Missing Unstable Explosion https://wow-mania.com/armory/?spell=49948

- [ ] Servitor Shade:
https://wow-mania.com/armory/?npc=24485
https://www.wowhead.com/npc=24485/servitor-shade#abilities
→ Missing Blink Strike https://wow-mania.com/armory/?spell=49961
→ Missing Shadow Shock https://wow-mania.com/armory/?spell=16583

- [ ] Necrotech:
https://wow-mania.com/armory/?npc=24540
https://www.wowhead.com/npc=24540/necrotech#abilities
→ Missing Curse of Weakness https://wow-mania.com/armory/?spell=18267
→ Missing Drain Life https://wow-mania.com/armory/?spell=17173
→ Missing Mind Control (Necrotech specific, might be using it on crystal or other npcs around when not engaged?) 
    https://wow-mania.com/armory/?spell=43871
→ Missing Shadowbolt https://wow-mania.com/armory/?spell=9613

- [ ] Chillmere Oracle:
https://wow-mania.com/armory/?npc=24461
https://www.wowhead.com/npc=24461/chillmere-oracle#abilities
→ Missing Frost Nova https://wow-mania.com/armory/?spell=11831
→ Missing Hex of the Murloc https://wow-mania.com/armory/?spell=49935
→ Missing Ice Lance https://wow-mania.com/armory/?spell=49906

- [ ] Sepulchral Overseer:
https://wow-mania.com/armory/?npc=23993
https://www.wowhead.com/npc=23993/sepulchral-overseer#abilities
→ Missing Frostbolt https://wow-mania.com/armory/?spell=12737
→ Missing Chains of Ice https://wow-mania.com/armory/?spell=22744

- [ ] Frosthorn Ram:
https://wow-mania.com/armory/?npc=23740
https://www.wowhead.com/npc=23740/frosthorn-ram#abilities
→ Missing Hoof Strike https://wow-mania.com/armory/?spell=29577

- [ ] Thornvine Creeper:
https://wow-mania.com/armory/?npc=23874
https://www.wowhead.com/npc=23874/thornvine-creeper#abilities
→ Missing Entangling Roots https://wow-mania.com/armory/?spell=31287

- [ ] Caldemere Snapper:
https://wow-mania.com/armory/?npc=24287
https://www.wowhead.com/npc=24287/caldemere-snapper#abilities
→ Missing Claw Grasp https://wow-mania.com/armory/?spell=49978

- [ ] Ice Elemental:
https://wow-mania.com/armory/?npc=23919
https://www.wowhead.com/npc=23919/ice-elemental#abilities
→ Missing Throw Ice https://wow-mania.com/armory/?spell=43543

- [ ] Perobas the Bloodthirster:
Needs confirmation, my  lvl 71 clothie had to kill him fast, 4 hits almost got me down.
https://wow-mania.com/armory/?npc=32377
https://www.wowhead.com/npc=32377/perobas-the-bloodthirster#abilities
→ Might be missing Gnaw Bone https://wow-mania.com/armory/?spell=50046 leading to (I guess) Broken Bone https://wow-mania.com/armory/?spell=50047
→ Might be missing Killing Rage https://wow-mania.com/armory/?spell=52071

- [ ] Icehollow Behemoth:
https://wow-mania.com/armory/?npc=23744
https://www.wowhead.com/npc=23744/icehollow-behemoth#abilities
→ Missing Ground Smash https://wow-mania.com/armory/?spell=12734

- [ ] Iron Rune Stonecaller:
https://wow-mania.com/armory/?npc=24030
https://www.wowhead.com/npc=24030/iron-rune-stonecaller#abilities
→ Missing Fireball https://wow-mania.com/armory/?spell=9053

- [ ] Iron Rune Guardian:
https://wow-mania.com/armory/?npc=24212
https://www.wowhead.com/npc=24212/iron-rune-guardian#abilities
→ Missing Guardian Rune https://wow-mania.com/armory/?spell=49643
→ Missing Guardian Strike https://wow-mania.com/armory/?spell=49644

- [ ] Iron Rune Binder:
https://wow-mania.com/armory/?npc=23796
https://www.wowhead.com/npc=23796/iron-rune-binder#abilities
→ Might be missing Bind Stone Giant https://wow-mania.com/armory/?spell=43270
→ → Based on this: https://www.wowhead.com/npc=24329/runed-stone-giant#comments:id=356465:reply=368808;40
 it is the rune on the ground into which Stone Giants ( https://wow-mania.com/armory/?npc=23725) are supposed to step in and transform into Runed Stone Giants. Havne't checked for any videos etc for now.
→ Missing Flame Shock https://wow-mania.com/armory/?spell=15039
→ Missing Rune of Binding https://wow-mania.com/armory/?spell=48599; https://wow-mania.com/armory/?spell=48601

- [ ] Iron Rune Sentinel:
https://wow-mania.com/armory/?npc=24316
https://www.wowhead.com/npc=24316/iron-rune-sentinel#abilities
→ Missing Rune Detonation https://wow-mania.com/armory/?spell=48416

- [ ] Runed Stone Giant:
https://wow-mania.com/armory/?npc=24329
https://www.wowhead.com/npc=24329
https://wowpedia.fandom.com/wiki/Stone_Giant
 → Based on https://www.wowhead.com/npc=24329/runed-stone-giant#comments:id=356465:reply=368808;40 they should have a 
→ → missing Bind Stone Giant buff when they step into the rune (which is required for them to count towards certain quest completion; they dont even step into the runes atm of what I have seen) https://wow-mania.com/armory/?spell=43270/
→ Stepping into rune should give them: Rune Fist https://wow-mania.com/armory/?spell=49717 
→ → Rune Fist allows to use them: Dark Rune https://wow-mania.com/armory/?spell=49718
Atm moment these giants are already transformed, wondering around without any buff and they use only basic melee abilities

- [ ] Stone Giant:
https://wow-mania.com/armory/?npc=23725
https://www.wowhead.com/npc=23725/stone-giant#abilities
The Abilities on wowhead "Dark Fist" and "Rune Fist" should concern his runed form by logic and by what I manage to deduce from comments. However other two abilities are missing.
→ Missing Stone Fist https://wow-mania.com/armory/?spell=49676
→ Missing Stone Stomp https://wow-mania.com/armory/?spell=49675

- [ ] Binder Murdis:
https://wow-mania.com/armory/?npc=24334
https://www.wowhead.com/npc=24334/binder-murdis#abilities
→ Missing Flame Shock https://wow-mania.com/armory/?spell=15039
→ Might be missing Rune of Binding (he is channeling something one one caputred Stone Giant, might be it) https://wow-mania.com/armory/?spell=48599; https://wow-mania.com/armory/?spell=48601

- [ ] Frost Nymph:
https://wow-mania.com/armory/?npc=23677
https://www.wowhead.com/npc=23677/frost-nymph#abilities
→ Misssing Frost Shock https://wow-mania.com/armory/?spell=12548
Comment: https://www.wowhead.com/npc=23677/frost-nymph#comments:id=441429 also mentions snowball fight, ahven't seen any nymph throwing a snowball on any other, could be bull ofc

- [ ] Maddened Frosthorn:
https://wow-mania.com/armory/?npc=24901
https://www.wowhead.com/npc=24901/maddened-frosthorn#abilities
→ Missing Gore https://wow-mania.com/armory/?spell=32019#used-by-npc (TBC wowhead redirect)

- [ ] Bjomolf:
https://wow-mania.com/armory/?npc=24516
https://www.wowhead.com/npc=24516/bjomolf#abilities
→ Missing  Gnaw Bone https://wow-mania.com/armory/?spell=50046 leading to (I guess) Broken Bone https://wow-mania.com/armory/?spell=50047

- [ ] Varg:
https://wow-mania.com/armory/?npc=24517
https://www.wowhead.com/npc=24517/varg#abilities
→ Missing Killing Rage https://wow-mania.com/armory/?spell=52071

- [ ] Darkclaw Bat:
https://wow-mania.com/armory/?npc=23959
https://www.wowhead.com/npc=23959/darkclaw-bat#abilities
→ Missing Howling Screech https://wow-mania.com/armory/?spell=32651 (redirected to TBC)
→ Missing Ravenous Pathogen https://wow-mania.com/armory/?spell=49980

- [ ] Winterskorn Hunter:
https://wow-mania.com/armory/?npc=26663
https://www.wowhead.com/npc=26663/winterskorn-hunter#abilities
Runs into melee and is hitting you instead of shooting you
→ Missing Multi-Shot https://wow-mania.com/armory/?spell=18651
→ Missing Rapid Fire https://wow-mania.com/armory/?spell=36828 (redirected to TBC)

- [ ] Proto-Whelp:
https://wow-mania.com/armory/?npc=23688
https://www.wowhead.com/npc=23688/proto-whelp#abilities
→ Missing Flame Breath https://wow-mania.com/armory/?spell=51218

- [ ] Proto-Drake
https://wow-mania.com/armory/?npc=23689
https://www.wowhead.com/npc=23689/proto-drake
All good with these guys ability-wise
→ BUT some of them are on the ground, and the flying ones should be spewing fire on the ground time to time (mostly near the eggs) and summoning the Proto-Whelps according to:
https://www.wowhead.com/npc=23688/proto-whelp#comments:id=442938 + response to it
I suppose the spewn fire should be Flames of Birth (cause the name) https://wow-mania.com/armory/?spell=42362
which are now used solely in combat against the player as fire pool on ground that damages you

_ZONE – SKORN
- [ ] Winterskorn Raider
https://wow-mania.com/armory/?npc=23665
→ if you attack his sparring partner 1st, the raider swims to you throguht the ground instead of running.
EDIT: When I flew around two of them sparring, they just ctivated fly hack and swam/flew after me lol
Sparring
https://www.youtube.com/watch?v=4Z3z_oH2QZw
https://www.wowhead.com/npc=23664/winterskorn-warrior#comments:id=1974113
DISCLAIMER: both proofs are from later patches
Those would suggest that the sparring partners should actually move their weapons against each other, fight. At the moment they just stand facing each other in combat pose._

- [ ] Howling Wolvar Shaman:
https://wow-mania.com/armory/?npc=26825
https://www.wowhead.com/npc=26825/howling-wolvar-shaman#abilities
→ Missing Earth Shock https://wow-mania.com/armory/?spell=13281
→ Missing Earthbind Totem https://wow-mania.com/armory/?spell=15786
→ Missing Lightning Bolt https://wow-mania.com/armory/?spell=26098

- [ ] Howling Wolvar Trainer:
https://wow-mania.com/armory/?npc=26823
https://www.wowhead.com/npc=26823/howling-wolvar-trainer#abilities
→ Missing Pummel https://wow-mania.com/armory/?spell=12555
→ Missing Quick Feet https://wow-mania.com/armory/?spell=50054
→ Missing Net https://wow-mania.com/armory/?spell=31290 (TBC redirect)
→ Missing Wolvar Net https://wow-mania.com/armory/?spell=49453
→ → This is mob-specific spell. Combined with https://www.wowhead.com/npc=26823/howling-wolvar-trainer#comments I am inclined to believe they should be using this net on Wild Shoveltusk but I couldnt find any video or anything actually.

- [ ] Winterskorn Skald:
https://wow-mania.com/armory/?npc=23657
https://www.wowhead.com/npc=23657/winterskorn-skald#abilities
→ Missing Fireball https://wow-mania.com/armory/?spell=9053
→ Missing Flamestrike https://wow-mania.com/armory/?spell=11829

- [ ] Winterskorn Spearman:
https://wow-mania.com/armory/?npc=23653/
https://www.wowhead.com/npc=23653/winterskorn-spearman#abilities
→ Missing Wing Clip https://wow-mania.com/armory/?spell=32908 (TBC redirect)
→ Missing Freezing Trap https://wow-mania.com/armory/?spell=43414 leading to https://wow-mania.com/armory/?spell=43415

- [ ] Winterskorn Bonegrinder:
https://wow-mania.com/armory/?npc=23655
https://www.wowhead.com/npc=23655/winterskorn-bonegrinder#abilities
→ Missing Bonegrinder https://wow-mania.com/armory/?spell=43951 leading to https://wow-mania.com/armory/?spell=43952 debuff

- [ ] Fjord Crow:
https://wow-mania.com/armory/?npc=23945
https://www.wowhead.com/npc=23945/fjord-crow#abilities
→ Missing Eye Peck https://wow-mania.com/armory/?spell=49865

- [ ] Wild Worg:
https://wow-mania.com/armory/?npc=24128
https://www.wowhead.com/npc=24128/wild-worg#abilities;mode:normal
→ Missing Powerful Bite https://wow-mania.com/armory/?spell=48287

- [ ] Iron Rune Destroyer:
https://wow-mania.com/armory/?npc=23676
https://www.wowhead.com/npc=23676/iron-rune-destroyer#abilities
→ Missing Hammer Blow https://wow-mania.com/armory/?spell=48376

- [ ] Iron Rune Sage:
https://wow-mania.com/armory/?npc=23674
https://www.wowhead.com/npc=23674/iron-rune-sage#abilities
→ Missing Fireball https://wow-mania.com/armory/?spell=20823
→ Missing Cone of Cold https://wow-mania.com/armory/?spell=20828

- [ ] Iron Rune Laborer:
https://wow-mania.com/armory/?npc=23711
https://www.wowhead.com/npc=23711/iron-rune-laborer#abilities
→ Missing Puncture Wound https://wow-mania.com/armory/?spell=48374

- [ ] Dragonflayer Warrior:
https://wow-mania.com/armory/?npc=23654
https://www.wowhead.com/npc=23654/dragonflayer-warrior#abilities
→ Missing Whirlwind https://wow-mania.com/armory/?spell=48280 https://wow-mania.com/armory/?spell=48281

- [ ] Dragonflayer Rune-Seer:
https://wow-mania.com/armory/?npc=23656
https://www.wowhead.com/npc=23656/dragonflayer-rune-seer#abilities
→ Missing Rune of Asvior https://wow-mania.com/armory/?spell=48262
→ Missing (most likely) Rune of Ubbi https://wow-mania.com/armory/?spell=48264

- [ ] Harpoon Master Yavus:
https://wow-mania.com/armory/?npc=24644
https://www.wowhead.com/npc=24644/harpoon-master-yavus#abilities
→ Missing Grievious Slash https://wow-mania.com/armory/?spell=48286 (seems a bit OP though)
→ Missing Harpoon Throw https://wow-mania.com/armory/?spell=48283
→ Missing Enrage https://wow-mania.com/armory/?spell=48193

- [ ] Skeld Drakeson:
https://wow-mania.com/armory/?npc=23940
https://www.wowhead.com/npc=23940/skeld-drakeson#abilities
→ Missing Enrage https://wow-mania.com/armory/?spell=8599

- [ ] Dragonflayer Vrykul:
https://wow-mania.com/armory/?npc=23652
https://www.wowhead.com/npc=23652/dragonflayer-vrykul#abilities
→ Missing Chop https://wow-mania.com/armory/?spell=43410

- [ ] Dragonflayer Worg:
https://wow-mania.com/armory/?npc=24063
https://www.wowhead.com/npc=24063/dragonflayer-worg#abilities
→ Missing Infected Bite https://wow-mania.com/armory/?spell=7367

- [ ] Dragonflayer Lieutenant:
https://wow-mania.com/armory/?npc=24169
https://www.wowhead.com/npc=24169/dragonflayer-lieutenant#abilities
→ Missing Head Slash https://wow-mania.com/armory/?spell=48245
→ Missing Risky Feint https://wow-mania.com/armory/?spell=48250

- [ ] Dragonflayer Tribesman:
https://wow-mania.com/armory/?npc=23651
https://www.wowhead.com/npc=23651/dragonflayer-tribesman#abilities
→ Missing Cleave https://wow-mania.com/armory/?spell=15496
→ Missing Enrage https://wow-mania.com/armory/?spell=48193

- [ ] Bloodthirsty Worg:
https://wow-mania.com/armory/?npc=24475
https://www.wowhead.com/npc=24475/bloodthirsty-worg#abilities
→ Missing Infected Bite https://wow-mania.com/armory/?spell=7367

- [ ] Yanis the Mystic:
https://wow-mania.com/armory/?npc=23932
https://www.wowhead.com/npc=23932/yanis-the-mystic#abilities
→ Missing Intercept https://wow-mania.com/armory/?spell=58747
→ Missing Throw Dragonflayer Harpoon https://wow-mania.com/armory/?spell=42870

- [ ] Risen Vrykul Ancestor:
https://wow-mania.com/armory/?npc=24871
https://www.wowhead.com/npc=24871/risen-vrykul-ancestor#abilities;mode:normal
→ Missing Perturbing Strike https://wow-mania.com/armory/?spell=49841

- [ ] Blood Shade:
https://wow-mania.com/armory/?npc=24872
https://www.wowhead.com/npc=24872/blood-shade#abilities
→ Missing Vexed Blood of the Ancestors https://wow-mania.com/armory/?spell=49843

Someone should check Northfleet NPCs since I am Alli and they are friendly to me. ✅ 

**North fleet**

- [ ] North Fleet Marine
https://www.wowhead.com/npc=23866/north-fleet-sailor
https://www.wow-mania.com/armory/?npc=23983
→ Missing Cleave https://www.wowhead.com/spell=15496/cleave
→ Missing Shield Slam https://www.wowhead.com/spell=49863/shield-slam

- [ ] North Fleet Marksman
https://www.wowhead.com/npc=23946/north-fleet-marksman
https://www.wow-mania.com/armory/?npc=23946
→ Missing Aimed Shot https://www.wowhead.com/spell=78841/aimed-shot

- [ ] North Fleet Medic
https://www.wowhead.com/npc=23794/north-fleet-medic
https://www.wow-mania.com/armory/?npc=23794
→ Missing Renew https://www.wowhead.com/spell=11640/renew

- [ ] North Fleet Reservist
https://www.wowhead.com/npc=24120/north-fleet-reservist
https://www.wow-mania.com/armory/?npc=24120
→ Missing Cleave https://www.wowhead.com/spell=15496/cleave
→ Missing Shield Slam https://www.wowhead.com/spell=49863/shield-slam

- [ ] North Fleet Soldier
https://www.wowhead.com/npc=23793/north-fleet-soldier
https://www.wow-mania.com/armory/?npc=23793
→ Missing Rend https://www.wowhead.com/spell=12054/rend

- [ ] "Scoodles":
https://wow-mania.com/armory/?npc=24899
https://www.wowhead.com/npc=24899/scoodles#abilities
→ Missing Powerful Bite https://wow-mania.com/armory/?spell=48287

- [ ] Rabid Brown Bear:
https://wow-mania.com/armory/?npc=24633
https://www.wowhead.com/npc=24633/rabid-brown-bear#abilities
→ Missing Maul https://wow-mania.com/armory/?spell=34298

- [x] Mutinous Sea Dog:
https://wow-mania.com/armory/?npc=25026
https://www.wowhead.com/npc=25026/mutinous-sea-dog#abilities
→ Missing Rip https://wow-mania.com/armory/?spell=33912
https://www.wowhead.com/npc=25026/mutinous-sea-dog#comments:id=442067:reply=57496
https://www.wowhead.com/quest=11527/mutiny-on-the-mercy
→ The mobs are definitely on the wrong ship based on the comment and the fact it does not make sense for the pirates to have ship full of zombies in the port and also basedon the quest concerning them.
(wrong ship - edited by echi)

- [ ] "Crowleg" Dan:
https://wow-mania.com/armory/?npc=24713
https://www.wowhead.com/npc=24713/crowleg-dan#abilities
→ Probably missing https://wow-mania.com/armory/?spell=50306 (died pretty fast)

**Comment by Echinaceax** [comment]
Thanks @Greywolf59  for this report 
let us know when its finished then we can remove the label

**Comment by Echinaceax** [comment]
added info 

- [ ] North Fleet Reservist
https://www.wowhead.com/npc=24120/north-fleet-reservist
https://www.wow-mania.com/armory/?npc=24120

have a laid down position 

North Fleet Reservist
https://www.wowhead.com/npc=24120/north-fleet-reservist
https://www.wow-mania.com/armory/?npc=24120

**Comment by Greywolf59** [comment]
Done, I checked I think like 90%, probably more. I am done.
![done](https://user-images.githubusercontent.com/41387450/166815025-5216519f-c908-4589-bf1e-343bd0e1ceb9.jpg)

**Comment by Franciss983** [comment]
Fanggore Worg:
Confirmed bug.

Gjalerbron Gargoyle:
Confirmed bug.

Gjalerbron Rune-Caster:
Confirmed bug.

Gjalerbron Sleep-Watcher:
Confirmed bug.

Gjalerbron Warrior:
Confirmed bug.

Putrid Wight:
Confirmed bug. Didnt use Plague Blight after 5 minutes.

Fearsome Horror:
Confirmed bug.

Necro Overlord Mezhen:
Confirmed bug.

Glacion:
Didnt found him...??

Fjord Crawler:
Confirmed bug.

Rotgill:
Confirmed bug.

Mur'ghoul Flesheater:
Confirmed bug.

Chillmere Tidehunter:
Confirmed bug.

Unstable Mur'ghoul:
Confirmed bug.

Servitor Shade:
Confirmed bug.

Necrotech:
Confirmed bug.

Chillmere Oracle:
Confirmed bug.

Sepulchral Overseer:
Confirmed bug.

Frosthorn Ram:
Confirmed bug.

Thornvine Creeper:
Confirmed bug.

Caldemere Snapper:
Not spawned on PTR realm. ?? Didnt find them on spot where they should be, nor with go to command.

Ice Elemental:
Confirmed bug.

Perobas the Bloodthirster:
https://www.wowhead.com/spell=50047/broken-bone ---- **Works**
https://www.wowhead.com/spell=50046/gnaw-bone ---- **Works**
https://www.wowhead.com/spell=52071/killing-rage ---- Confirmed bug.

Icehollow Behemoth:
Confirmed bug.

Iron Rune Stonecaller:
Confirmed bug.

Iron Rune Guardian:
Confirmed bug.

Iron Rune Binder:
Confirmed bug. (Was trying every way to get runes or bindings to work, with no result.) Also didnt found videos about it.

Iron Rune Sentinel:
Confirmed bug.

Runed Stone Giant:
Confirmed bug. Uses only melee.

Stone Giant:
Confirmed bug.

Binder Murdis:
Confirmed bug. 
(By visual "Blazier" he is standing next to is channeling some sort of spell onto Captive Stone Giant, cant tell what is it. If you move Binder Murdis, spell is still going on.)

Frost Nymph:
Confirmed bug. 
Also no snowball fights whatsoever.

Maddened Frosthorn:
Confirmed bug. 

Bjomolf:
Confirmed bug. 

Varg:
Confirmed bug. 

Darkclaw Bat:
Confirmed bug. 

Winterskorn Hunter:
Confirmed bug. 

Proto-Whelp:
Confirmed bug. 

Proto-Drake:
**Abilities working but.:**
Flames of Birth (cause the name) https://wow-mania.com/armory/?spell=42362 are used only when encounter not randomly during flying.
Even if you go closer to "Eggs" when the spell is used, they did not blow.


**_ZONE – SKORN**

Winterskorn Raider:
Confirmed bug. 
Raiders on the ground are swimming when pulled, instead of walking.
Sparing partners doesnt fight.

Howling Wolvar Shaman:
Confirmed bug. 

Howling Wolvar Trainer:
Confirmed bug. 

Winterskorn Skald:
Confirmed bug. 

Winterskorn Spearman:
Confirmed bug. 

Winterskorn Bonegrinder:
Confirmed bug. 

Fjord Crow:
Confirmed bug. 

Wild Worg:
Confirmed bug. 

Iron Rune Destroyer:
Confirmed bug. 

Iron Rune Sage:
Confirmed bug. 

Iron Rune Laborer:
Confirmed bug. 

Dragonflayer Warrior:
Confirmed bug. 

Dragonflayer Rune-Seer:
Confirmed bug. 

Harpoon Master Yavus:
Confirmed bug. 

Skeld Drakeson:
Confirmed bug. 

Dragonflayer Vrykul:
Confirmed bug. 

Dragonflayer Worg:
Confirmed bug. 

Dragonflayer Lieutenant:
Confirmed bug. 

Dragonflayer Tribesman:
Confirmed bug. 

Bloodthirsty Worg:
Confirmed bug. 

Yanis the Mystic:
Confirmed bug. 

Risen Vrykul Ancestor:
Confirmed bug. 

Blood Shade:
Confirmed bug. 

**North fleet**

North Fleet Sailor:
https://www.wowhead.com/npc=23866/north-fleet-sailor
**Working.**

North Fleet Marine:
https://www.wow-mania.com/armory/?npc=23983
Confirmed bug. 

North Fleet Marksman:
Confirmed bug. 

North Fleet Medic:
Confirmed bug. Missing Renew spell.

North Fleet Reservist:
Confirmed bug. And laying on the ground. (That has been reported).

North Fleet Soldier:
Confirmed bug. 

"Scoodles":
Confirmed bug. 

Rabid Brown Bear:
Confirmed bug. 

Mutinous Sea Dog:
Confirmed bug. 

"Crowleg" Dan:
Confirmed bug.

**Comment by wow-mania** [comment]
won't be fixed at this time
