### ISSUE TITLE
[NPC] Koltira Deathweaver 28912 - can't retake the quest after quest fail/player dies

### ISSUE THREAD

**Issue by theevildevil29** [WoWManiaUK/Redemption#5809]
Hy! 

I have died in the quest Bloody Breakout ID: 12727. I cannot start the quest again, because the quest giver Koltira Deathweaver has disappeared. I've abandined the quest in the hope I can restart the questline from the quest Brothers In Death ID: 12725. 
Here comes the problem: Thassarian does not gives the quest again, so I've stocked. I don't have any quest to do and I cannot continue the DK qest line. Please help how to fix this issue.

Thank you!

Best Regards,

TheEvilDevil29

**Comment by jeyrella** [comment]
Hi,
Please raise a ticket in-game using /gm or the red ? in the micro menu.

**Comment by GMZinius** [comment]
Reopening this @Rushor 
This needs fixing

- After a player dies, the NPC respawns under the bed. this should'nt happen
- Players cannot retake the quest after abanding it or restart the event
Note: Resetting the NPC does'nt fix this NPC, only a server restart does. 

![image](https://github.com/WoWManiaUK/Redemption/assets/108176634/cd75691f-42c2-45c3-a441-efdc9e0b2042)


- NPC Koltira Deathweaver ID 28912 need to reset home possition after quest fail/player wipe
https://www.youtube.com/watch?v=JEm3TEBBApM

**Comment by Echinaceax** [comment]
not fixed still.

on player death / event failed,  Koltira Deathweaver re-spawns under the bed and cant restart the event

**Comment by Echinaceax** [comment]
- [x] comfirmed fixed for the retaking the quest after quest fail or player dies (main issue fixed)
- [ ] cosmetic issue1 of him respawning under the bed still has an issue (cant be fixed atm)
- [ ] cosmetic issue2 after he goes to the armor chest to get his armor, he doesnt actually switch gear 

little note, if players stand inside the bubble shield like he says, then you wont die :)
https://i.gyazo.com/77d8c2b0f5ce83bd324b037995b71435.mp4

https://wowpedia.fandom.com/wiki/Bloody_Breakout
![image](https://github.com/user-attachments/assets/a4e8c8f7-f726-472d-ab8f-895838c5fa62)
![image](https://github.com/user-attachments/assets/91752eeb-bd1d-43af-bd31-953d1f9480aa)
