### ISSUE TITLE
[Item] Tirisfal Batling: Missing Special Animation and Vocalization

### ISSUE THREAD

**Issue by kamoodle5** [WoWManiaUK/Redemption#5810]
**Links:** https://www.warcraftpets.com/wow-pets/flying/bats/tirisfal-batling/
https://www.wowhead.com/item=44971/tirisfal-batling

**What is Happening:** This sure is one shy little bat. Not only is its special animation missing, but it emits no sounds. In fact, I couldn't hear its wings fluttering.

**What Should happen:** Its special animation and sounds should work.

Here's a video clip of the bat up close and personal:
https://youtu.be/lZgEf2lNnds

**Comment by Franciss983** [comment]
Hello,

1. Mobility Air (flies alongside flying mount) - **Its not flying alongside mounted player but it should.**
2. Animation Flutters about and occasionally produces red "bat sonar" rings. - **Pet is not using "bat sonar" rings**
3. Sound Wing flutter (constant); vocalizations (periodic and on-click) - a) **Can hear its wings fluttering** **b) Does not doing vocalization (not even on click).**

video.: https://www.youtube.com/watch?v=N3y9gWPpiHY

**Comment by Rushor** [comment]
will fly with owner now, will also do the spcial animation every 30 seconds (timer provided by blizzard internal aura spell)

**Comment by Franciss983** [comment]
On PTR working perfectly.
https://www.youtube.com/watch?v=GNEnP_cxa6I
