### ISSUE TITLE
[NPC] Crazed Water Spirit: Certain Mobs Target Hunter Over Pet

### ISSUE THREAD

**Issue by kamoodle5** [WoWManiaUK/Redemption#5811]
**Links:** https://www.wowhead.com/npc=16570/crazed-water-spirit

**What is Happening:** After viewing my video, it seems the only mobs that exhibit this behavior are the patrols and stationary mobs that hang out within the pools; those outside the perimeter behave normally.
1.) When first attacking one of these bugged mobs with the pet, the mob will instead engage the hunter regardless of the pet's threat.
2.) When the hunter FD's, the mob will always evade reset when the pet attempts to attack.
3.) Intimidation does help keep the mob off the hunter.

**What Should happen:** All these mobs should behave like the ones outside the pools and not ignore the pet's threat.

Here's my video clip of the scenario:
https://youtu.be/DokczrhUBYw

**Comment by Franciss983** [comment]
Hello,

Confirmed: That information about aggro reset of the NPCs inside pools when pet attack first it ignores him is correct.
Confirmed: When hunter FD it resets whole fight and NPC is evading when pet attempts to attack.

I have been testing another NPCs that apear inside pools and the are behave normally.

NPC.: NPC: https://www.wowhead.com/npc=16570/crazed-water-spirit
Heres video.: https://www.youtube.com/watch?v=9TOUM0xyYA4

**Comment by Rushor** [comment]
pet will keep aggro now and will not directly attack the owner

**Comment by Rushor** [comment]
yes it's fixed in ptr and will soon be applied on live with the upcoming update

**Comment by Franciss983** [comment]
On PTR working perfectly.
https://www.youtube.com/watch?v=3kLpKWDfUmc
