### ISSUE TITLE
[NPC] Grizzly Hills - Missing NPC abilities

### ISSUE THREAD

**Issue by Greywolf59** [WoWManiaUK/Redemption#5812]
I will do this probably in a bit slower temp but since the very 1st NPC I killed in the zone was most likely missing abilities (wowhead/mania armory confirms), here we go.

- [ ] Arcturis:
https://wow-mania.com/armory/?npc=38453
https://www.wowhead.com/npc=38453/arcturis#abilities
→ Missing Pounce https://wow-mania.com/armory/?spell=61184
→ Most likely missing Frozen Bite https://wow-mania.com/armory/?spell=61185 → https://wow-mania.com/armory/?spell=61186

- [ ] Tallhorn Stag:
https://wow-mania.com/armory/?npc=26363
https://www.wowhead.com/npc=26363/tallhorn-stag#abilities
→ Missing Gore https://wow-mania.com/armory/?spell=32019

- [ ] Wounded Skirmisher:
https://wow-mania.com/armory/?npc=27463
https://www.wowhead.com/npc=27463/wounded-skirmisher#abilities
→ Missing Cleave https://wow-mania.com/armory/?spell=15496
→ Missing Hamstring https://wow-mania.com/armory/?spell=9080
→ Missing Mortal Strike https://wow-mania.com/armory/?spell=32736
→ → For MS wowhead redirected to TBC. On NPC's page it says 25% healing reduction, not 50%

- [ ] Drakkari Shaman:
https://wow-mania.com/armory/?npc=26447
https://www.wowhead.com/npc=26447/drakkari-shaman#abilities
→ Missing Mastered Elements https://wow-mania.com/armory/?spell=52290
→  Shaman at 13.6 58.5 Grizzly Hills (carbonite coords) teleports around

- [ ] Warlord Zim'bo:
https://wow-mania.com/armory/?npc=26544
https://www.wowhead.com/npc=26544/warlord-zimbo#abilities
→ Missing Skull Crack https://wow-mania.com/armory/?spell=3551
→ Missing Warlord Roar https://wow-mania.com/armory/?spell=52283 (empty site on mania)
     https://www.wowhead.com/spell=52283/warlord-roar

- [x] Redfang Hunter:
https://wow-mania.com/armory/?npc=26356
All spells are okay however he exhibits a strange behaviour
→ Shoots 1 time and stops
→ throws net on you when you move from starting position of your attack
→ stands on a spot
→ if you get to melee range he only uses Net and Carnivorous Bite, does not use basic melee hits

- [ ] Iron Rune-Shaper:
https://wow-mania.com/armory/?npc=26270
https://www.wowhead.com/npc=26270/iron-rune-shaper#comments:id=485636
→ No missing abilities on wowhead listed. However the comment mentions a runic circle (aka Mold Rune)
→ → Missing Mold Rune https://wow-mania.com/armory/?spell=52622

- [ ] Harrison Jones:
https://wow-mania.com/armory/?npc=26814
https://wow-mania.com/armory/?quest=12082
→ Looks like he starts walking only once per restart/crash
→→ Does emote, opens the gate, closes the gate, gate disappears in a bit on the 1st quest take
→ →on Abandon and retake no reaction whatsoever)

- [x] Runed Giant:
https://wow-mania.com/armory/?npc=26417
→ Seen one Rune Giant fall into the ground. if you walk to the spot he pops out and attacks. Carbonite coords: 72.6 45.1

- [ ] Wounded Skirmisher:
https://wow-mania.com/armory/?npc=27463
https://www.wowhead.com/npc=27463/wounded-skirmisher
→ Missing Cleave https://wow-mania.com/armory/?spell=15496
→ Missing Hamstring https://wow-mania.com/armory/?spell=9080
→ Missing Mortal Strike https://wow-mania.com/armory/?spell=32736

- [ ] Someone please check Wounded Westfall Infantry:
https://wow-mania.com/armory/?npc=27482
https://www.wowhead.com/npc=27482/wounded-westfall-infantry#comments
→ No abilities on Wowhead but comments mention that they have abilities and there is a mention of Holy Shock and Seal of Command. This would make sense since hey fight Wounded Skirmishers and if Skirmishers would use their abilities they would always kill them easily.

- [ ] Solstice Hunter:
https://wow-mania.com/armory/?npc=26389
https://www.wowhead.com/npc=26389/solstice-hunter#comments
→ Everything works fine except that the NPC keeps using all the ranged abilities after it switches to the worgen form. It can still shoot once or twice after transformation but then it should start using melee only (I suppose). It still uses all shoot abilities even in melee range.

**Comment by Greywolf59** [comment]
All done. I must admit I haven't checked Venture Bay thoroughly but I think it should be fine in there. No quests lead there anyway unless player goes there on his own to do pvp dailies.

**Comment by Rushor** [comment]
Great report man!

**Comment by Greywolf59** [comment]
Thank you! Though I've just noticed I have Skirmisher twice in there heh.

**Comment by Franciss983** [comment]
Arcturis: 
- missing all spells. **Confirmed bug**

Allhorn Stag: 
- missing Gore. **Confirmed bug**

Wounded Skirmisher: 
- missing all spells. **Confirmed bug**

Drakkari Shaman: 
-  missing Mastered Elements. **Confirmed bug**

Warlord Zim'bo: 
- missing all spells. **Confirmed bug**

Redfang Hunter:
- Shoots all the time when I am standing at far range. **(Not bug)**
- Following me for couple yards, but if i get far too fast, he stop and start using ranged abilities. **(Not bug)**
- If i get to melee he uses Melee hits, Net and Carnivorous Bite. **(Not bug)**

Iron Rune-Shaper:
- missing Mold Rune spell. **Confirmed bug**

Harrison Jones:
- on Abandon after completing Harrison Jones is missing. Cant pick the quest again. **Confirmed bug**

Runed Giant:
- Giant is patroling arena from point Carbonite coords: 72.6 45.1 to 72,2 40,0 then teleporting back to his starting position. Seen multiple Giants doing it that way. **(Not bug)**

Wounded Westfall Infantry:
- They arent using Seal of Command nor Holy Shock like we can see in comments on wowhead. **Confirmed bug**

Solstice Hunter:
- Using ranged abilities in melee **Confirmed bug**

**Comment by Echinaceax** [comment]
@Rushor we have checked off the not bugged ones for you ok
so you know

**Comment by Greywolf59** [comment]
Cool thing. Yea other times I been at the coords the giant was fine but 1st time there I saw him fall down to the ground and when I landed on the spot he emerged from the ground and attacked me. I fled and he started his normal path.
Concerning the Redfang Hunter, on my warlock he shot just once, no fear etc used. Started dps from afar (untalented reach of spells) and when I walked in melee range he did not use melee, so dunno.

**Comment by Greywolf59** [comment]
So I came there on my druid.
Redfang Hunter:
Works properly
Redfang Hunters guarding the cave:
→ act as described in OP

**Comment by Greywolf59** [comment]
Proof: https://i.gyazo.com/b099a9f3bd45c9baaf608e25f93bb0c9.mp4

**Comment by wow-mania** [comment]
won't be fixed at this time

**Comment by Greywolf59** [comment]
Well I hope there will be time for it one day. Would feel bad for several hours just go to waste. Not that it would be any big issue, true enough. Thanks for taking interest at least.
