### ISSUE TITLE
[Quest] Betrayal - troll controlling scepter does not work correctly

### ISSUE THREAD

**Issue by Tolkinz** [WoWManiaUK/Redemption#5813]
**Links:**
https://www.wow-mania.com/armory/?quest=12713

**What is Happening:**
When a troll under control is dying, it should be switched a fresh new one but here scepter fails too often.
Can't give the number, feels like under 50% rate, probably 33% or 20%, so mission success depends on RNG.

**What Should happen:**
The sceptor provided is supposed to work 100% all the time.

Sorry no screenshot.  I was too much frustrated.
Play log of [Destrosky] might be helpful.

**Comment by Rushor** [comment]
Well ofc the troll can die, can you may make a video of the error so we can better understand? Thank you

**Comment by Tolkinz** [comment]
It is simple. When 1st troll is dying, player needs to switch to next provided troll.
And scepter fails to CONTROL that troll, it has 5sec cooldown, that's the moment Drakuru runs to me.
There's no 2nd chance. Highway to grave.

So the issue is this : why the scepter fails? is it regarded as weapon and dominated by hit rating? I have never seen a quest-given device fails to work at a very critical moment.  I did this 10+ times due to bad randomness.

**Comment by Rushor** [comment]
Okay now i understand, thanks

**Comment by Tolkinz** [comment]
I see nothing wrong with heal spell cuz Drakuru throws poison crystal and its AoE skill which damages player's HP a lot - I mean really a lot. So player needs heal. Heal skill is correct.

Real issue is the 2nd one.

Lemme explain this a bit.

As soon as Scepter is used and starts channeling, previous troll is already OFF and Drakuru starts to run to player.

Therefore, the trick is to position the boss far from player+next swichable troll, at about 35-40% use the special ability HAMMER shape(stun) to earn a bit extra time, then while he is running, player finish channeling and start attack.

Player is kinda busy when switching cause he needs to click troll, channeling, switch target to drakuru and click attack button, this should be done in less than 3 seconds.

This is a very old quest and wowhead gives tons of tips and tricks, however, among them channeling failure is not an option.
It really means retrial.  I also did this from the retail version of wotlk.
And if retrial continues like 10+ times, we get annoyed.

I DIDN'T say I was being attacked by boss  and channeling was interrupted. That's NOT what happened.
Instead, what happened was just failure after full channeling, and then Drakuru was a few step behind already ready to swallow me.

Hope this helps.

**Comment by Tolkinz** [comment]
Oh and one more information.

Previous sceptors for geist and abominations also fails to enslave them. 
Though it does not give any serious harm, it happens all the time.

**Comment by Tolkinz** [comment]
how come you make such conclusion from this tooltip

**Comment by Echinaceax** [comment]
I am the tester @Tolkinz 
and we know what we are doing

**Comment by Tolkinz** [comment]
that player is troll's controller from the vid, and he got heals. I dont get what you are thinking

**Comment by Echinaceax** [comment]
chatting with team atm so hang fire

**Comment by Tolkinz** [comment]
alrighty

let's not make this overly complicated.
what I see is very simple. if sceptor worked just as it was supposed to, I wouldn't have the need to come here.
I spent 2.5hrs for that q, you feel my anger....

**Comment by Echinaceax** [comment]
correct @Tolkinz 
timestamp 1:19 https://www.youtube.com/watch?v=xDa-GLMf7no yes I see that

thanks

**Comment by Tolkinz** [comment]
finally we got understanding!
thanks!

and from the last vid, I am thinking boss mechanic is different.
ye I was thinking why changing was so busy like this.

1. Drakuru does not chase you, does not hit melee when switching to next troll. Instead he casts shadowbolt(?),, which means we are less busy in retail version (I mean when changing)
2. drakuru throws that poison crystal all the time but here he throws it only at the beginning. quite nerfed, up to you guyz.

My toons are mostly graduated drakuru so would not need the fixed version but hell yea, its better get fixed.

**Comment by Echinaceax** [comment]
@Rushor I found a 2009 video but didnt show us what we needed so im using the 2015 for visual referance only

**Comment by Rushor** [comment]
Can please someone sum up what to fix now, this chat is too huge :D @Echinaceax @Tolkinz

**Comment by Echinaceax** [comment]
was trying to minimize the spam for you @Rushor 😄

**Comment by mfranca0009** [comment]
A lot of problems wrong with this, and it's not just what the OP describes and what Echi has mentioned.

For instance, when you do finish off "Drakuru" to the point where he summons the portal and the lich king walks out:
- Lich king walks too fast and doesn't just walk at normal walk speed; making him look rather awkward.
- Drakuru and Lich King's creature text/voice lines do not have good event timing, they talk over each other, or lich king talks over himself.
- Neither Drakuru nor the Lich King has appropriate emote reactions tied to their creature texts/voice lines.
- There should be geists randomly moving around on the edge of the platform between where the trolls are spawned; those don't even exist.

As such, this whole encounter should be researched and reworked to fix it correctly, and completely.

**Comment by fvicaria** [comment]
If this can be completed just close it.

**Comment by Rushor** [comment]
I will add that the scepter will not fail again, that is the most needed fix here

**Comment by Rushor** [comment]
charm should now always work directly, so the quest can be done a lot better
