### ISSUE TITLE
[Spawns] Cho'War's Cave in Warhaul Hill Has Almost No Mobs

### ISSUE THREAD

**Issue by kamoodle5** [WoWManiaUK/Redemption#5815]
**Links:** https://tbc.wowhead.com/npc=18423/chowar-the-pillager
(Note: this is just to pinpoint where Cho'war's cave is located in Nagrand. He actually has no issues.)

**What is Happening:** 
Starting at the southern entrance into Cho'war's cave (27.2, 19.1 coordinates), there are mobs up until the second Warmaul Brute at 26.0, 16.0. After that, there are no more mobs spawning til Cho'war's spot towards the top.

**What Should happen:** Cho'war's cave should be more populated with mobs. Also, the two Warlocks at the mouth of the southern entrance should not exist there. According to the Wowhead video below, there is one warlock just outside to the right.

Videos:
First up is my video, starting at the southern entrance until Cho'war's spot.
https://youtu.be/bzkqnaUZg6o

Next is a Wowhead video related to the Alliance side of the Cho'war quest. 0:57 to around 3:57 is that player's trip to the elite.
https://youtu.be/nxssax9lEgU?t=57

**Comment by jeyrella** [comment]
Not saying it is untrue, but really could do with finding a video from original content, large amounts were changed for "classic" releases making modern videos unreliable.  (Classic really isn't a true replica of the original at all, like "Indian restaurants", it's more along what we _think_ it should be like :) )

**Comment by mfranca0009** [comment]
Updated positioning of some `Warmaul Brute` NPCs and `Warmaul Warlock` NPCs. Added pathing to one `Warmaul Brute` which paths from the cave's entrance to `Cho'war the Pillager`.
