### ISSUE TITLE
[Boss] Deathbringer Saurfang - Mark of the Fallen Champion

### ISSUE THREAD

**Issue by svijetlo** [WoWManiaUK/Redemption#5816]
**Links:**
http://www.wow-mania.com/armory?npc=37813
http://www.wow-mania.com/armory?spell=72279
http://www.wow-mania.com/armory?spell=72446
**What is Happening:**
During Deathbringer Saurfang if player get mark and dies form boss or his summons , he will ofc heal boss etc 
but ones fight is over and player get ressurected he will still have debuff on 
![image](https://user-images.githubusercontent.com/61908373/167846413-42f3be3a-92e3-448b-ac4f-014e31ccba46.png)

**What Should happen:**
ones fight is over all debuffs form boss need to be gone regardless if player did die or was alive ones fight is over

**Comment by Rushor** [comment]
All Mark of the Fallen Champion should be removed now, active after next build
