### ISSUE TITLE
[Quest] The Drakkensryd - enemy npc not being hit/evade

### ISSUE THREAD

**Issue by Tolkinz** [WoWManiaUK/Redemption#5817]
**Links:**
https://www.wow-mania.com/armory/?quest=12886

**What is Happening:**
- several npcs are not hittable within melee range

**What Should happen:**
- they should get hit

**Play Video
https://www.youtube.com/watch?v=P2AVHz2IkoU

**Comment by Echinaceax** [comment]
Thanks @Tolkinz for reporting

This has been reported many times, and though it does evade sometimes, the quest is completable 

So from the other reports ive read, this wont be worked on unfortunately

**Comment by Tolkinz** [comment]
aha, gotcha!
