### ISSUE TITLE
[NPC] Spirit of Kirith: Too Many Spawns Present

### ISSUE THREAD

**Issue by kamoodle5** [WoWManiaUK/Redemption#5818]
**Links:** https://classic.wowhead.com/npc=7729/spirit-of-kirith
https://classic.wowhead.com/npc=7728/kirith-the-damned
https://classic.wowhead.com/quest=2721/kirith

**What is Happening:** I discovered multiple clones of Spirit of Kirith at the spot where the felhunter is located. Even after I accepted my NPC's follow-up quest upon killing the felhunter, he doesn't want to despawn after awhile.

**What Should happen:** There shouldn't be this many NPCs standing around.

(Yes, I did clear my cache.)

Screenshot:
![WoWScrnShot_051222_175336](https://user-images.githubusercontent.com/67519835/168181300-e1f5dcc6-6065-40ce-8605-12d62b20baf0.jpg)

**Comment by Echinaceax** [comment]
Confirmed bugged 

He is suppose to spawn when youve killed "Kirith the Damned" 
at the moment he has 9 spawns up, 
![image](https://user-images.githubusercontent.com/39439201/168255877-2502d13e-514e-435a-a97f-64a5729806d2.png)

**Comment by kamoodle5** [comment]
I would assume the extra spawns are the result of other players defeating the felhunter and one spirit spawns afterward. However, if they were to see this, they wouldn't even need to kill the quest mob; they can just turn "Kirith" in (especially with the NPC I had spawned). Plus, I'd imagine this can put a strain on the server if dozens more were present at one spot.

**Comment by Rushor** [comment]
I think the quest npc should despawn faster then

**Comment by Rushor** [comment]
Added that the creature will now despawn after 60 seconds after the spawn. That way we resolve all issues.

The check for the active quest state does not work here and is not supported by the scripts it uses atm

**Comment by Echinaceax** [comment]
Confirmed despawn in 60 secs
