### ISSUE TITLE
[Quest] Magic Carpet Ride

### ISSUE THREAD

**Issue by nqk3188** [WoWManiaUK/Redemption#5819]
**Links:**
http://www.wow-mania.com/armory?quest=11636

**What is Happening:**
Can not talk to NPC Gorge the Corpsegrinder and end this quest

**What Should happen:**
Can talk to NPC Gorge the Corpsegrinder and end this quest

**Comment by jeyrella** [comment]
This appears to be working fine on PTR, and I have completed on at least 2 toons on Redemption.
![image](https://user-images.githubusercontent.com/46089380/168421935-cd4a5cb7-f128-4a6d-8c2f-4db80954eda7.png)

Did you actually take the carpet ride, or fly there on your own mount?

**Comment by kamoodle5** [comment]
I recently completed this quest, and I can confirm that you have to talk to Yanni (https://www.wowhead.com/npc=25459/yanni) to start the magic carpet ride and only this will finish the quest. I made the mistake of flying to the site on my own mount at first and the question mark over Gorge was still gray.

**Comment by jeyrella** [comment]
> I recently completed this quest, and I can confirm that you have to talk to Yanni (https://www.wowhead.com/npc=25459/yanni) to start the magic carpet ride and only this will finish the quest. I made the mistake of flying to the site on my own mount at first and the question mark over Gorge was still gray.

Exactly :)  Just trying to make sure the OP understands this :)
