### ISSUE TITLE
I can't see anything with the main character.

### ISSUE THREAD

**Issue by Marabrat1** [WoWManiaUK/Redemption#5820]
**Links:**

**What is Happening:** Hey guys. Sorry to bother you but I have a problem with my main character. I had a quest with Arthas in the past and logged out of the game. When I logged in, I couldn't see anyone or anything. I removed the quest but I still can't see other players, npc's, mailbox, bank and others. I'm sure it's because of the quest, because the game worked properly for years, This has been going on for hours. Other characters work normally, only this one doesn't. I hope he gets back to normal.

**What Should happen:**

If I can do something to fix this write me Thank you for understanding.

**Comment by WhitephoenixTheBunny** [comment]
Hi. 
Open a ticket ingame to get a GM to assist you.

But, if you are on the questline "Battle for the Undercity" you might want pick up the quest (either in OG, either in Undercity, depending on how far you are) and keep following the roleplay.

**Comment by Marabrat1** [comment]
Hey. I just solved the problem. I tried everything, but I just didn't try to die and now I've committed suicide and the game is back to normal.
You were helpful to me. Thank you for all.
