### ISSUE TITLE
[NPC] Mistcaller Yngvar - First Text Not Referring Player's Pet Correctly

### ISSUE THREAD

**Issue by kamoodle5** [WoWManiaUK/Redemption#5823]
**Links:** https://www.wowhead.com/npc=34965/mistcaller-yngvar

What is Happening: When Mistcaller Yngvar appears, his first piece of dialogue will be "Foolish [class], you cannot stop the Kvaldir!" Similar to my previous report about the Underbog Lurker ( #5802), Yngvar's text properly shows the name of the player's class; however, the pet has no class so it shows as "$c". 

What Should happen: Not sure how the pet would be described in this text, but definitely not as "$c".

Screenshots: 
1.) Here's when the mob refers to my toon, dialogue to the bottom-left:
![WoWScrnShot_051722_211247](https://user-images.githubusercontent.com/67519835/168961063-ba229fa4-8b90-4cab-81f9-554dc59ca178.jpg)
2.) Here's how he refers to my pet, also bottom-left of the screenshot:
![WoWScrnShot_050922_232536](https://user-images.githubusercontent.com/67519835/168961110-3bf82418-d5ec-4291-9267-0668b67e112d.jpg)

**Comment by Rushor** [comment]
text should be said to the player now

**Comment by Echinaceax** [comment]
confirmed fixed in PTR

- [ ] hunter per fixed 

![image](https://user-images.githubusercontent.com/39439201/169408663-4c13b25d-3bc5-41ed-9ee9-de7e0f413a92.png)

- [ ] Warlock pet 

![image](https://user-images.githubusercontent.com/39439201/169409105-8dc2cc73-0a03-4ee3-b028-31f1e5f7f2d2.png)
