### ISSUE TITLE
[NPC] The Iron Watcher - Visability issue / Falling loop issue

### ISSUE THREAD

**Issue by Greywolf59** [WoWManiaUK/Redemption#5824]
**Links:**
quest:
https://wow-mania.com/armory/?quest=12874
The Iron Watcher:
https://wow-mania.com/armory/?npc=30142
https://www.wowhead.com/npc=30142/the-iron-watcher

**What is Happening:**
SOMETIMES when you fly to the bridge you see the Iron Watcher falling from the end of the bridge. If you fly down under the bridge you see him standng there on the edge of the abyss. If you get near to him, he disappears and if you fly back to the bridge he is again on the edge of the bridge falling. This is perpetual cycle that sometimes occur making the quest undoable. Tried relogging. So far on all my toons I had like 50% chance of this occuring.

**What Should happen:**
Not sure if he should be spawned only if you pick up the hammer or not https://wow-mania.com/armory/?object=192243 (I never noticed it at all and he was there) but he should be definitely waiting at the opposite end of the bridge for you, not falling down already.

**Comment by jeyrella** [comment]
Hmm, thanks - like you say, "sometimes".  I did this very quest just last week on Redemption and all was good.  Maybe it is only seen after someone else has completed quest.  Will investigate.

**Comment by Echinaceax** [comment]
### Update so far 

From my 6 tests from different positions, I found that the NPC has visablity issues 

1. https://i.gyazo.com/795f3ec6bebe4bae9b868be5a0ef9f80.mp4
2. https://i.gyazo.com/4aa62e6813cd1fb162117636310ffd6b.mp4
3. https://i.gyazo.com/04e5e73a0e9083c0cddaa64c0574c165.mp4
4. https://i.gyazo.com/33a994d2857923c0d90e1be516e51643.mp4
5. https://i.gyazo.com/8345aba9707f8307067fe50d2a309324.mp4
6. https://i.gyazo.com/e87bc1c73b5bb94294845f2e84667a23.mp4

Waiting to continue test after killing NPC and see if he's respawn causes the issue

**Comment by Greywolf59** [comment]
For me he was on the other side of the bridge and falling down

**Comment by Echinaceax** [comment]
> For me he was on the other side of the bridge and falling down even when I flew there for the first time with the NPC on the eagle, before we even landed. And it is still the same now. EDIT: Retook the quest, tested again now. Still the same. There is also another player, Hariette, afking on flying mount near the broken bridge. Maybe (s)he has the same issue. I whisped but as the palyer is afk and I gotta run I am not sure I will get a confirmation.

Very odd, I cant reprodruce 
can you Clear cache and try again ?

**Comment by Greywolf59** [comment]
Cleared, went through launcher, logged at the spot under the bridge, NPC almost fell on my head when falling down.

**Comment by Greywolf59** [comment]
I never done any video. I might try. Any recommendation? Requirements: Free, no registration, no need to upload on any cloud or whatever on the net.

**Comment by Echinaceax** [comment]
> I never done any video. I might try. Any recommendation? Requirements: Free, no registration, no need to upload on any cloud or whatever on the net.

I will PM you

**Comment by Greywolf59** [comment]
https://gyazo.com/4076aa67c54a9e253582868d87dd8fec

**Comment by Tolkinz** [comment]
@Greywolf59 
easy.  in Windows10, there is an app called xbos game bar, short-cut key is windows-G
and there is th monitor capture key.  Free and easy.

**Comment by Rushor** [comment]
should be visible from far more away now, hope this resolves the issue

**Comment by Rushor** [comment]
Jani told me to fix this

**Comment by Echinaceax** [comment]
Visability fixed in PTR  

![image](https://user-images.githubusercontent.com/39439201/169411616-b89747f7-a6bb-45e2-baad-575663bcea67.png)

**Comment by Greywolf59** [comment]
Tested Live. Flew from the right side this time, I have no idea if there was any server restart or crash since my last attempt. The Iron Watcher was on the right spot. I DPSed him down to +- 40% then he charged blindly to the edge where he stayed, standing there. I killed him by the spells, quest is complete. I am not sure however if he shouldn't charge blindly not to the edge but further on, falling to his death.

**Comment by Echinaceax** [comment]
> Tested Live. Flew from the right side this time, I have no idea if there was any server restart or crash since my last attempt. The Iron Watcher was on the right spot. I DPSed him down to +- 40% then he charged blindly to the edge where he stayed, standing there. I killed him by the spells, quest is complete. I am not sure however if he shouldn't charge blindly not to the edge but further on, falling to his death.

Thanks for extra info, yes we can check this out 👍

**Comment by jeyrella** [comment]
> Tested Live. Flew from the right side this time, I have no idea if there was any server restart or crash since my last attempt. The Iron Watcher was on the right spot. I DPSed him down to +- 40% then he charged blindly to the edge where he stayed, standing there. I killed him by the spells, quest is complete. I am not sure however if he shouldn't charge blindly not to the edge but further on, falling to his death.

You're supposed to pick up the hammer and use it on him when he's standing on the edge.

**Comment by Greywolf59** [comment]
Yeah I figured you use hammer in the fight but I also thought it is not mandatory. I noticed it for the first time on this toon. Did it on 3 or 4 others witout even noticing the hammer and it was very easy. Cool then.

**Comment by Echinaceax** [comment]
### Update on the reproduce of this issue 

Me and Smelly (thx for help Smelly) ❤️ 

This can happen a few ways: that we have reproduced,

- [ ] With Cyclone on the edge (that Smelly reproduced earlier today on PTR)
- [ ] Wiping on him/losing combat with a spell then leaving the zone. then the next player that comes in his view will see him loop falling like this 
1. With char that bugged him https://i.gyazo.com/13fa6515b9317c0644455c4d1f557a7e.mp4
2. With new char that came to the zone for him https://i.gyazo.com/b1b420e70248bc48b68d96ea62933a5d.mp4

### People that use the hammer quest item found at the end of the bridge will not bug it by wiping and leaving the zone

**Comment by Lumber-Jack-2** [comment]
there should be actually more scripts for him, texts and a advanced stun event

**Comment by Lumber-Jack-2** [comment]
how it should be done can be seen here https://www.youtube.com/watch?v=b430oKn3n1M

**Comment by Echinaceax** [comment]
yes exactly rushor 😄 

looking good
1, No fall looping  https://i.gyazo.com/dfff8e6a5dec457dd9caa848858fe7cc.mp4
2, Resets nicely if hes left at the edge too long
3. Noticed the new text and advanced stun
