### ISSUE TITLE
[Core]  charge ability issue 

### ISSUE THREAD

**Issue by Tolkinz** [WoWManiaUK/Redemption#5825]
**Links:**
https://www.wow-mania.com/armory/?spell=100

**What is Happening:**
Warrior's charge not available at all under water (from azeroth to northrend)

**What Should happen:**
charge should be possible

** I have found this mentioned several years ago and surprised to know it still is bugged.

**Comment by jeyrella** [comment]
Thanks.  Can you please state your source for your statement “charge should be possible”. Not saying it isn’t, but a skim round wowhead and wowpedia couldn’t immediately confirm it one way or the other. Am sure there must be some era-relevant videos somewhere?

**Comment by Tolkinz** [comment]
This is a quite embarrasing request.
Ever since I played wow for the first time in 2009, I have no memory of charging-not-available under plain water.
So hearing your request to prove my statement is just weird to me. 

Mob is in plain sight, there is no obstacle between two, but there is no path available.
Is it only me that feels this is a bug?

![WoWScrnShot_051922_205528](https://user-images.githubusercontent.com/105026618/169287768-87394cf1-aa0c-457b-9d15-89f6baa6e212.jpg)

**Comment by Echinaceax** [comment]
@jeyrella 
i see from TC they fixed it https://github.com/TrinityCore/TrinityCore/issues/22253

and sort of found a video 2015 only https://www.youtube.com/watch?v=EDLZz1oA8ro

**Comment by Tolkinz** [comment]
Charging anywhere is natural for a warrior, and this is my assumption that feral druid might also have same problem.
The above link discusses the error facing wrong direction AFTER charging, they do not discuss if charging UNDER water is a correct behavior.
So, that's it.

**Comment by Echinaceax** [comment]
> Charging anywhere is natural for a warrior, and this is my assumption that feral druid might also have same problem. The above link discusses the error facing wrong direction AFTER charging, they do not discuss if charging UNDER water is a correct behavior. So, that's it.

Yes i linked for proof of Change expected behavour @Tolkinz 

![image](https://user-images.githubusercontent.com/39439201/169300872-aaba3e15-5ee9-4caf-a5c6-0fa8e81137e7.png)

**Comment by Tolkinz** [comment]
@Echinaceax tnx for your finding, forgot to mention :)

**Comment by Tolkinz** [comment]
another reference from that thread ;

- fixed both charge underwater/while falling(in the air)
https://github.com/TrinityCore/TrinityCore/pull/24010

**Comment by jeyrella** [comment]
@Tolkinz Thanks for including the extra information. Note asking for more details is never embarrassing, your post didn’t include any error message details or screenshots or that it was a pathing problem rather than on-use…., with the extra detail you later put we are instantly able to understand what the exact issue is and where the root of the problem lies.
Thanks for giving us the heads up :)

**Comment by Tolkinz** [comment]
so you all know there is an issue, you may close the issue with a label,
tnx for the attention!!

**Comment by jeyrella** [comment]
> @jeyrella I am really sorry I was a bit nervous. There was a bit of misunderstanding because I thought it is impossible to not notice this transparent issue

It's not a problem.  We're a small team of volunteers, players just like you, so we don't always have full expertise in every single class and situation...  We do try to be flexible and helpful, but every minute testing we do is a minute less we have to actually play, so posting good details really helps us make early decisions :)

By the way - as you've been making great reports (thanks!), https://github.com/WoWManiaUK/Redemption/wiki/How-to-Properly-Report-an-Issue may be useful to understand what we do, screenshots in particular help us massively

> What really surprised me was that you guyz didn't notice this issue up until now. :(

Well, as mentioned - we're small team of volunteer players, we can't possibly know every class/situation or every single inch of every map in the entire game world; we rely heavily on reports that are made by players that specialise in their class or field, and we get enough of those to keep us busy already without going out in the world looking for stuff :)

Keep raising those tickets, we do appreciate it, honest!, just sometimes we need a bit more info or clarity so we don't make wrong assumptions :)

**Comment by Tolkinz** [comment]
I do apologize and appreciate your kind explanation!
I will try keep up with your pace as long as I am here, I promise :)

**Comment by Tolkinz** [comment]
btw, as I do find my fun from questing, this is current progress and all alts are on same course,
so there will come more reports!!!

![WoWScrnShot_052022_012541](https://user-images.githubusercontent.com/105026618/169350711-280bb83b-a1b6-4164-b9fd-c9b5d4f52639.jpg)

**Comment by Franciss983** [comment]
Charge (Bear form for a Druid class)
What is Happening:
Druids charge not available at under water (from azeroth to northrend), only on lower ground underwater.
https://www.wow-mania.com/armory/?spell=61685

**Comment by Echinaceax** [comment]
Update 

also happening with the Felguard charge 

Spell ID 47996

**Comment by Keader** [comment]
it's above me...
core cant calculate a path under water

**Comment by mfranca0009** [comment]
Fixed as far as I can see, if any more improvements can be done in the future then we will do it 👍 

**Test Video 1:** https://i.gyazo.com/d83ac971354c4f6f9ee33f3fa834d9b2.mp4
**Test Video 2:** https://i.gyazo.com/fdd91c483ab5713f2d59f8258c64a266.mp4
**Test Video 3:** https://i.gyazo.com/66c81597ad49413484a1c56c1e6aef03.mp4
**Test Video 4:** https://i.gyazo.com/2b6a5f0bca0c25c828def1987c6aff60.mp4

**Comment by Echinaceax** [comment]
I re-checked in the zone i confirmed it bugged and still has issues 

working from bottom of the water https://i.gyazo.com/5fc3bf6dde0cc16f7f8f13d975c5e81f.mp4
but not on diagnal and fron lower to top 
 
![image](https://user-images.githubusercontent.com/39439201/175766469-ace83757-883b-40c7-b7e9-174c575bef8e.png)
![image](https://user-images.githubusercontent.com/39439201/175766505-ddaed67a-9556-4145-b332-cc622adfbb99.png)
![image](https://user-images.githubusercontent.com/39439201/175766537-62916d92-46f9-4c0d-8954-94e1d8ec7bb0.png)
![image](https://user-images.githubusercontent.com/39439201/175766576-fb90a40f-bbdd-49f0-93d0-91e49709cfd3.png)

**Comment by Echinaceax** [comment]
Spoken to franca - this is the best it can be for now
