### ISSUE TITLE
[NPC] [WIP] Icecrown - NPCs missing abilities

### ISSUE THREAD

**Issue by Greywolf59** [WoWManiaUK/Redemption#5826]
This will be a long project since I do not have that much time anymore but if I meet any NPC with missing abilities I will post it here. BTw I have done most of the Storm Peaks. I haven't really checked the NPCs but nothing seemed noticably wrong.

Forgotten Depth Slayer:
I have no clue why there are four links to it on both mania and wowhead, maybe cause of the phasing.
https://wow-mania.com/armory/?npc=30333
https://www.wowhead.com/npc=30333/forgotten-depths-slayer#abilities
and probably all other phased versions
→ Missing Claw Slash https://wow-mania.com/armory/?spell=54185

Carrion Fleshstripper:
https://wow-mania.com/armory/?npc=30206
https://www.wowhead.com/npc=30206/carrion-fleshstripper#abilities
and probably all other phased versions
→ Missing Paralytic Poison https://wow-mania.com/armory/?spell=35201 (TBC wowhead redirect)

Frostbrood Destroyer:
https://wow-mania.com/armory/?npc=30575
https://www.wowhead.com/npc=30575/frostbrood-destroyer#abilities
NOTE: Normally person should not get in combat with them at all.
→ Missing Freezing Breath https://wow-mania.com/armory/?spell=57477
→ Missing Wing Buffet https://wow-mania.com/armory/?spell=53363

Forgotten Depths Underking:
https://wow-mania.com/armory/?npc=30541
https://www.wowhead.com/npc=30541/forgotten-depths-underking#abilities
and probalby all other phased versions
→ Missing Blinding Swarm (nature) https://wow-mania.com/armory/?spell=50283
→→ (physical) (no clue why divided) https://wow-mania.com/armory/?spell=50284
→ Missing Mandinble Crush https://wow-mania.com/armory/?spell=60802

Wrathstrike Gargoyle:
https://wow-mania.com/armory/?npc=30482 + https://wow-mania.com/armory/?npc=31040
https://www.wowhead.com/npc=30482/wrathstrike-gargoyle#abilities + 31040
→ Missing Gargoyle Strike https://wow-mania.com/armory/?spell=16564

Animated Laborer:
https://wow-mania.com/armory/?npc=32267
https://www.wowhead.com/npc=32267/animated-laborer#abilities
→ Missing Puncture Wound https://wow-mania.com/armory/?spell=48374
→ Looks like missing loot table

Corp'rethar Guardian:
https://wow-mania.com/armory/?npc=32280
https://www.wowhead.com/npc=32280/corprethar-guardian#abilities
→ Missing Infected Bite https://wow-mania.com/armory/?spell=60927
→ Missing Mortal Wound https://wow-mania.com/armory/?spell=54378

Harbinger of Horror:
https://wow-mania.com/armory/?npc=32278
https://www.wowhead.com/npc=32278/harbinger-of-horror#abilities
→ Missing Fear https://wow-mania.com/armory/?spell=12096
→ Missing Frostbolt (unreflectable) https://wow-mania.com/armory/?spell=61747
→ Missing Chill Nova https://wow-mania.com/armory/?spell=18099
→ Missing Chilled effect debuff (source unclear) https://wow-mania.com/armory/?spell=18101
→ → might be from Frost Armor (acc to wowhead) https://wow-mania.com/armory/?spell=18100 but they dont have any, nor does wowhead lists Frost Armor in their spells
→ Might be missing Lich Slap (might need melee with interrupts to test): https://wow-mania.com/armory/?spell=60924

Death Knight Master:
https://wow-mania.com/armory/?npc=29738
https://www.wowhead.com/npc=29738/death-knight-master#abilities
→ Missing Blood Presence https://wow-mania.com/armory/?spell=50689
→ Missing Plague Strike https://wow-mania.com/armory/?spell=50688

Vault Geist:
https://wow-mania.com/armory/?npc=29720
https://www.wowhead.com/npc=29720/vault-geist#abilities
→ Missing Rip https://wow-mania.com/armory/?spell=36590

Morbid Carcass:
https://wow-mania.com/armory/?npc=29719
https://www.wowhead.com/npc=29719/morbid-carcass#abilities
→ Missing Cleave https://wow-mania.com/armory/?spell=40504
→ Missing Scourge Hook https://wow-mania.com/armory/?spell=50335

Rabid Cannibal:
https://wow-mania.com/armory/?npc=29722
https://www.wowhead.com/npc=29722/rabid-cannibal#abilities
→ Missing Carnivorous Bite https://wow-mania.com/armory/?spell=30639

Restless Lookout:
https://wow-mania.com/armory/?npc=30951
https://www.wowhead.com/npc=30951/restless-lookout#abilities
→ Missing Enraged https://wow-mania.com/armory/?spell=59208
→ Missing Pierce Armor https://wow-mania.com/armory/?spell=46202

https://wow-mania.com/armory/?npc=31554
→ Missing Enraged https://wow-mania.com/armory/?spell=59208
https://www.wowhead.com/npc=31554/restless-lookout#abilities

Hungering Plaguehound:
https://wow-mania.com/armory/?npc=30952
https://www.wowhead.com/npc=30952/hungering-plaguehound#abilities
→ Missing Infected Wound https://wow-mania.com/armory/?spell=3427
→ Some of them do not have a name and are not targettable

Shadow Vault Skirmisher:
https://wow-mania.com/armory/?npc=31251
https://www.wowhead.com/npc=31251/shadow-vault-skirmisher#abilities
→ Missing Devour Humanoid https://wow-mania.com/armory/?spell=52207

Shadow Vault Abomination:
https://wow-mania.com/armory/?npc=31438
https://www.wowhead.com/npc=31438/shadow-vault-abomination#abilities
Looks like it is missing...
→ Knockdown https://wow-mania.com/armory/?spell=16790
→ Toppling Tower https://wow-mania.com/armory/?spell=55065
→ Towering Chains https://wow-mania.com/armory/?spell=55240
→ Trample https://wow-mania.com/armory/?spell=5568

Shadow Vault Assaulter:
https://wow-mania.com/armory/?npc=31266
tps://www.wowhead.com/npc=31266/shadow-vault-assaulter
→ Might be missing Assaulter Slam https://wow-mania.com/armory/?spell=58905
→→ Tied to it probably this: https://wow-mania.com/armory/?spell=59145

Ebon Blade Defender (Friendly unit):
https://wow-mania.com/armory/?npc=31250
https://www.wowhead.com/npc=31250/ebon-blade-defender#abilities
→ Might be missing Blood Strike https://wow-mania.com/armory/?spell=59130

Ebon Blade Vindicator (friendly unit)
https://wow-mania.com/armory/?npc=32488
https://www.wowhead.com/npc=32488/ebon-blade-vindicator#abilities
→ Might be missing Blood Strike https://wow-mania.com/armory/?spell=59130

Mjordin Combatant
https://wow-mania.com/armory/?npc=30037
https://www.wowhead.com/npc=30037/mjordin-combatant#abilities
(Timing: https://legacy-wotlk.com/?npc=30037#sai-main)
→ Missing Whirlwind https://wow-mania.com/armory/?spell=49807
→ Missing Jump Attack https://wow-mania.com/armory/?spell=61227
→ Missing Mortal Strike https://wow-mania.com/armory/?spell=32736
→ Missing Sunder Armor https://wow-mania.com/armory/?spell=50370

Valhalas Vargul:
https://wow-mania.com/armory/?npc=30250
https://www.wowhead.com/npc=30250/valhalas-vargul#abilities
→ Missing Diminish Soul https://wow-mania.com/armory/?spell=36789

Brita:
https://wow-mania.com/armory/?npc=30484
https://www.wowhead.com/npc=30484/brita#abilities
→ By comparison of the sites it looks she has all the abilities however if I recall correctly (already done the quest) she shoots and runs to the melee range between the shots. But based on having Freezing Trap and Disengage she should probably try to keep her distance actually. I do not remember her using any of those two abilities. She might have used Wing Clip and Aimed Shot but I do not remember, sorry.

Mjordin Water Magus:
https://wow-mania.com/armory/?npc=30632
https://www.wowhead.com/npc=30632/mjordin-water-magus#abilities
→ Stuck on spamming Summon Water Terror https://wow-mania.com/armory/?spell=7855
→ Uses Frostbolt only if player assumes a form of Water Terror https://wow-mania.com/armory/?npc=30645 during one quest

Chained Abomination:
https://wow-mania.com/armory/?npc=30689
https://www.wowhead.com/npc=30689/chained-abomination#abilities
→ Missing Cleave https://wow-mania.com/armory/?spell=15496
→ Missing Scourge Hook https://wow-mania.com/armory/?spell=50335

Scourgebeak Fleshripper:
https://wow-mania.com/armory/?npc=30988
https://www.wowhead.com/npc=30988/scourgebeak-fleshripper#abilities
→ Missing Swoop https://wow-mania.com/armory/?spell=55079

Onslaught Gryphon Rider:
https://wow-mania.com/armory/?npc=29333
https://www.wowhead.com/npc=29333/onslaught-gryphon-rider#abilities
→ Missing Wing Clip https://wow-mania.com/armory/?spell=40652

Onslaught Harbor Guard:
https://wow-mania.com/armory/?npc=29330
https://www.wowhead.com/npc=29330/onslaught-harbor-guard#abilities
→ Missing Frost Shot (very frequent use) https://wow-mania.com/armory/?spell=18802
→ Mania armory page lists Raven Heal which is not and should be not used by this NPC

**Comment by wow-mania** [comment]
won't be fixed at this time.
