### ISSUE TITLE
[Zone] The Frigid Tomb - Missing Icebound Revenants

### ISSUE THREAD

**Issue by Greywolf59** [WoWManiaUK/Redemption#5828]
**Links:**
Revenant:
https://wow-mania.com/armory/?npc=29844
https://wow-mania.com/armory/?npc=30053
Video (2015): https://www.youtube.com/watch?v=Q27zWmAoEz8

**What is Happening:**
All the Icebound Revenants are outside of the cave. Only one at the start of the cave, otherwise the cave is empty, except the Eternal Watcher at the end.

**What Should happen:**
There should be a few of the revenants inside. Yup video is 2015, but the cave feels really empty nonetheless.
Oh btw I haven't seen the bubble mentioned here: https://www.wowhead.com/npc=29844/icebound-revenant#comments:id=904162 but I wasn't paying attention to it at all. I am phased now. Might check it later.

**Comment by Echinaceax** [comment]
i see some inside the cave, down inside  (Wrong position)

x12 ID 29844 are spawn 

![image](https://user-images.githubusercontent.com/39439201/169586053-e5e608a9-3f61-4010-a27a-53f9f9eb1806.png)

x0 ID 30053 missing

**Comment by Echinaceax** [comment]
fixed in ptr added missing 5 NPCs plus waypathing or one 

https://i.gyazo.com/05d84788a45d5b4f6cf74da0beb63fe0.mp4
