### ISSUE TITLE
[Quest] Fury of the Frostborn King

### ISSUE THREAD

**Issue by Greywolf59** [WoWManiaUK/Redemption#5829]
**Links:**
Video (2015) https://www.youtube.com/watch?v=GNp0RIYR8kU
Wowpedia: https://wowpedia.fandom.com/wiki/Fury_of_the_Frostborn_King
→ Revision 28th September 2008: https://wowpedia.fandom.com/wiki/Fury_of_the_Frostborn_King?oldid=1615322
Quest - Fury of the Frostborn King: https://wow-mania.com/armory/?quest=12879
Prequest - The Hidden Relic: https://wow-mania.com/armory/?quest=12878
Comment confirming spawn of the NPC: https://www.wowhead.com/quest=12879/fury-of-the-frostborn-king#comments:id=461504

After completing the quest The Hidden Relic, Frostborn Axemaster should spawn as player's Guardian…
→ Frostborn Axemaster:
→ → Probably the automatic summon: https://wow-mania.com/armory/?spell=55383
(There is another one with huge range whcih is I think a trigger for the army outside)
→ → NPC itself: https://wow-mania.com/armory/?npc=29729
(There are other NPCs with same name without additional info but this is the one where summon link takes me)

→ In the video there is infighting between Frostborns and Iron Dwarves in the cave. The cave empty at the moment.

→ Outside the cave there are no NPCs, the Iron Dwarves Army is spawning one by one, attacking Frostborns holding the cave, and dying. On Red both armies stand fully spawned at the entrance, standing against each other idly.

→ In the Foot Steppes there are dead bodies, NPCs fighting each other, lot of action. On Red everything is spawned alive in predetermiend positions and they do not fight each other.

I know the video is from 2015 and it is basically the only proof, beside wowpedia and implciations from wowhead comments, that would suggest this quest is wrong but it would be cool of this phase would get some more action.
Also starting description of the Quest states: <As you retrieve the core from the chest, you hear the thumping of heavy footsteps rushing towards you from the corridor. There is the faint sound of battle in the distance.>
Everytime I did this quest I felt it a bit odd that after the footsteps in the corridor nothing happens and I am alone in the cave.
Also the linked comment from 3.0.3 mentions the constant battle outside.

**Comment by Echinaceax** [comment]
confirmed bug

- [ ] no Frostborn Axemaster should spawn as player's Guardian
- [ ] No fighting groups inside cave
- [ ] Fighting npcs outside dont fight until your run in and aggro them 

no npc spawns https://i.gyazo.com/6366f6f848a164a949aa5d81b73e674e.mp4
npc not fighting https://i.gyazo.com/dda710733a1e6d0632b974d4f60545b5.mp4

**Comment by Rushor** [comment]
all points fixed

**Comment by Echinaceax** [comment]
Fixed in PTR 

Guardian spawns https://i.gyazo.com/2fd6e32cdb061d36aba7ae55eb794bce.mp4
npc spawns in cave added https://i.gyazo.com/8ab50435e916bf83f12cf42e05aad692.mp4
npc fighting https://i.gyazo.com/f8b2b6c3c3650d2c37484072453d05d1.mp4
