### ISSUE TITLE
[NPC] Razorgore the Untamed

### ISSUE THREAD

**Issue by philoudu16** [WoWManiaUK/Redemption#583]
Razorgore is the first boss in Blackwing Lair, which you need to control to destroy dragon eggs while adds spawn. However, it seems impossible to cancel the charm on Razorgore once mobs have spawned, which makes the encounter way harder when trying to do it with a small group of people. Also, you seem to be able to put razorgore asleep with the spell "calm dragonkin".

**Comment by Emcitementz** [comment]
![b41e1d4ea88d44fa8c6e03bd0663484b](https://cloud.githubusercontent.com/assets/11377592/21084859/78f1e788-c009-11e6-86dc-95ad225db28d.png)
