### ISSUE TITLE
[NPC] Sholazar Basin zone ID:3711 - NPCs missing abilities (Revision of all NPCs)

### ISSUE THREAD

**Issue by Franciss983** [WoWManiaUK/Redemption#5830]
DONE

Testing "missing abilities" for all the unfriendly (AH) NPCs (53 NPCs in total) for this zone. **Will present only the ones which missing abilities.**
(Frenzyhearth Tribe and The Oracles NPCs gonna be separate).

- [ ] Farunn

https://www.wow-mania.com/armory/?npc=28288
https://www.wowhead.com/npc=28288/farunn#comments

Charge - Does not use Charge (wowhead related spell) 
https://www.wowhead.com/spell=55193/rhino-charge

- [ ] Festering Ghoul - Does not use Rot Armor (wowhead related spell)

https://www.wowhead.com/npc=25660/festering-ghoul
https://www.wow-mania.com/armory/?npc=25660

Rot Armor - Does not use Rot Armor (wowhead related spell)
https://www.wowhead.com/spell=50361/rot-armor

- [ ] Foreman Swindlegrin

https://www.wow-mania.com/armory/?npc=28186
https://www.wowhead.com/npc=28186/foreman-swindlegrin

Chainsaw Blade - not working/missing ability
https://www.wowhead.com/spell=36228/chainsaw-blade

- [ ] Frosthowl Screecher

https://www.wow-mania.com/armory/?npc=28170
https://www.wowhead.com/npc=28170/frosthowl-screecher

Shadow bolt - NPC is visualy casting Shadow bolt but it does not hit player with damage. And also is not shown in combat log.
https://www.wow-mania.com/armory/?spell=52257

- [ ] Magmoth Crusher

https://www.wowhead.com/npc=25434/magmoth-crusher#abilities

Magnataur charge - not working/missing ability
https://www.wowhead.com/spell=50413/magnataur-charge
Tusk Strike - not working/missing ability
https://www.wowhead.com/spell=50410/tusk-strike

- [ ] Primordial Drake

https://www.wow-mania.com/armory/?npc=28378
https://www.wowhead.com/npc=28378/primordial-drake

Flame Spit - working
https://www.wow-mania.com/armory/?spell=55071
Birthing Flame – not working/missing ability
https://www.wow-mania.com/armory/?spell=52791

- [ ] Sapphire Hive Queen

https://www.wow-mania.com/armory/?npc=28087
https://www.wowhead.com/npc=28087/sapphire-hive-queen

Enrage - working
https://www.wow-mania.com/armory/?spell=48193
Poison Stinger – not working/missing ability
https://www.wow-mania.com/armory/?spell=54761

- [ ] Serfex the Reaver

https://www.wow-mania.com/armory/?npc=28083
https://www.wowhead.com/npc=28083/serfex-the-reaver

Poison – not working/missing ability
https://www.wowhead.com/spell=31747/poison

- [ ] Venture Co Ruffian

https://www.wow-mania.com/armory/?npc=28124
https://www.wowhead.com/npc=28124/venture-co-ruffian

Backhand – casting on himself. Should be on enemy.
https://www.wow-mania.com/armory/?spell=52908
Bonk - Working
https://www.wow-mania.com/armory/?spell=51601

**Comment by wow-mania** [comment]
won't be fixed at this time
