### ISSUE TITLE
[Spell] Blink-mage

### ISSUE THREAD

**Issue by svijetlo** [WoWManiaUK/Redemption#5831]
**Links:**
http://www.wow-mania.com/armory?spell=1953

**What is Happening:**
every time mage use blink it turn it towards different direction then mage is looking/moving 
p.S. new bug showed up after today reset

**What Should happen:**
Blink need to always "move" caster in direction he is facing / moving

personal opinion ; this should be High prio

**Comment by jeyrella** [comment]
Player always ends facing east

**Comment by mfranca0009** [comment]
All fixed on PTR 👍

**Comment by Echinaceax** [comment]
confirmed fixed on PTR 

https://i.gyazo.com/f8598b729f0d3d74b9a93750ef1738e6.mp4

**Comment by Echinaceax** [comment]
applied to live 
thanks @svijetlo
