### ISSUE TITLE
[Quest] Change POI and clarify quest description of "Mutiny on the Mercy"

### ISSUE THREAD

**Issue by jeyrella** [WoWManiaUK/Redemption#5836]
**Links:**
https://github.com/WoWManiaUK/Redemption/issues?q=mutiny+on+the+mercy
https://www.wow-mania.com/armory/?quest=11527
https://www.wowhead.com/quest=11527/mutiny-on-the-mercy

**What is Happening:**
Mutiny on the Mercy was an undocumented change by Blizzard, to move the pirates from the moving ship to the land based ship due to NPCs falling through the floor of a moving texture, however the POI was not moved so addons continued to send players to the wrong place.

We receive github tickets and GM tickets almost weekly about this.  Despite this not technically being a bug as this is how it was in retail, compromise agreement reached with GMs to clarify the quest description and change the quest POI so that addons reference the "new" location.

**What Should happen:**
Amend the information in the quest description about the stationary ship, and adjust the POI accordingly.

New Summary:
Captain Ellis aboard the Sister Mercy in the Howling Fjord has asked that you recover 5 Barrels of Blasting Powder from Scuttle Frostprow's ship.

New Description:
"Aye, we got problems, matey. Me gunners have mutinied and abandon'ship with all the blastin' powder! M'n'the crew up top be tryin' to kick Sorlof's keester while dealin' with the mutinous gunners.

Ye're gonna have to go to Scuttle Frostprow's ship and deal with those mutinous sea dogs and take their blastin' powder for the big'un o'er on the poop deck."

With ye mannin' the big'un, Sorlof is sure to die and give up the booty!"

POI to be updated from existing area to the coordiates of Scuttle Frostprow, 37.8, 79.6
Current:
![image](https://user-images.githubusercontent.com/46089380/170017766-a641604d-546a-4bdc-a22e-ab4dd21ceed6.png)
New:
![image](https://user-images.githubusercontent.com/46089380/170014983-45b75c63-396d-40b0-88dc-cb5d065a3525.png)

**Comment by Echinaceax** [comment]
Re-opened this that Janitor close for quick temp fix 
closed this one https://github.com/WoWManiaUK/Redemption/issues/5847

**Comment by Echinaceax** [comment]
Confirmed fixed in PTR 

POI 

![poi fixed](https://user-images.githubusercontent.com/39439201/173920845-31971aa4-ba6b-4144-8d25-5a7bfbe89a64.jpg)


Quest discription changed 

![image](https://user-images.githubusercontent.com/39439201/173920840-f9ddade9-e17b-4d04-80fd-96dabbb72b7c.png)
