### ISSUE TITLE
[item] Sundial of the Exiled

### ISSUE THREAD

**Issue by svijetlo** [WoWManiaUK/Redemption#5838]
**Links:**
http://www.wow-mania.com/armory?item=40682

**What is Happening:**
Sundial of the Exiled can proc form any spells even buff etc 

**What Should happen:**
Sundial of the Exiled should proc only form harmful spells

**Comment by svijetlo** [comment]
![image](https://user-images.githubusercontent.com/61908373/170530900-512f7d37-1ada-4e81-ab78-d800e572c668.png)

**Comment by Echinaceax** [comment]
confirmed bug (procc'd from Buff)

![image](https://user-images.githubusercontent.com/39439201/170689967-f74b3a12-05c1-479e-bb67-3102f047bb71.png)

**Comment by mfranca0009** [comment]
Per @jeyrella discord post in dev channel:
![image](https://user-images.githubusercontent.com/26092980/170781933-6bdfa443-300f-4818-965d-4d5d02d32c55.png)

Need more information, and determine if there is a true issue here.
