### ISSUE TITLE
[Core] LFG not working

### ISSUE THREAD

**Issue by Sexysumo** [WoWManiaUK/Redemption#584]
Hello, I did a dungeon using LFG and we ended the dungeon. Then we wanted to re-queue for a LFG but we could not. It did the same thing with all the dungeon I've went to. We disbanded the group then requeue and it worked. Is it normal that we need to disband just to requeue ? 

THanks for helping out.

**Comment by Rushor** [comment]
no it's a bug.

**Comment by Sexysumo** [comment]
Not to abuse but theres a reward for finding bugs right ?

**Comment by Rushor** [comment]
dunno

**Comment by fvicaria** [comment]
We reward solving them as per https://github.com/WoWManiaUK/Redemption/wiki/Solve-an-Issue-and-get-Paid

@Rushor You are in credit for #576. Let me know if you want to claim it.

**Comment by Kalasbyxan** [comment]
Sexysumo there are no rewards for finding a bug, but there are for finding a fix to a bug. More can be read here: https://github.com/WoWManiaUK/Redemption/wiki/Solve-an-Issue-and-get-Paid
