### ISSUE TITLE
[Item/set] Avatar Regalia itemset=666 - Set bonus 2 pieces: spell=37601/relentlessness - does not proc.

### ISSUE THREAD

**Issue by Chirrpie** [WoWManiaUK/Redemption#5840]
**Links:**
https://www.wow-mania.com/armory/?itemset=666
https://tbc.wowhead.com/item-set=666/avatar-regalia#comments

**What is Happening:**
The 2-set bonus doesn't proc. This issue is currently known to me to appear on the Naxxramas server.

**What Should happen:**
According to WowHead this proc is called Relentlessness and has a 6% proc chance off any harmful cast.

**Comment by WhitephoenixTheBunny** [comment]
Do you have your gear moged? if yes, is just a visual glitch

**Comment by Chirrpie** [comment]
No, I have no mogs active. I also should get a buff, which I'm not getting,
and I even tried to watch my mana cost over time as I cast. It doesn't
appear to proc at all.

Am Mo., 30. Mai 2022 um 09:53 Uhr schrieb Phoenix ***@***.***

**Comment by Franciss983** [comment]
Confirmed bug. The 2-set bonus does not proc. Tested on PTR.

**Comment by mfranca0009** [comment]
All set, it was proc'ing for me after the fix but it may take a couple of spell casts to make it proc cause of the 6% chance.

**Comment by Franciss983** [comment]
It works now on PTR:
https://gyazo.com/2c36456c53213b2868135c83e01c5af1
https://gyazo.com/fa2909ab25e7b69fed25bf4c567f3a74
