### ISSUE TITLE
Im dead and stuck on the mall

### ISSUE THREAD

**Issue by Rafoid-sql** [WoWManiaUK/Redemption#5843]
**Links:**

**What is Happening:**
I died trying to Delroy's Deathrun and I got stuck when I tried to recover my body.

**What Should happen:**
I shouldnt be stuck.

**Comment by Echinaceax** [comment]
Hi @Rafoid-sql 
contact a GM ingame to help you

**Comment by Rafoid-sql** [comment]
How?? I cant message anyone, IM DEAD!
My spirit got stuck
