### ISSUE TITLE
Quest Bug: "It Rolls Downhill"

### ISSUE THREAD

**Issue by lecoo123** [WoWManiaUK/Redemption#5844]
**Links:**

**What is Happening:**
At that quest, we are taming Blight Geist mob. It turns to our pet, we gain a pet skill bar which there is one skill name "Harvest Blight Crystal". 
i press the skill but it didnt worked. So i couldn't do quest.

![WoWScrnShot_060222_002515](https://user-images.githubusercontent.com/106707879/171505215-28417d36-280e-48be-a1a1-7338289cab9e.jpg)
![WoWScrnShot_060222_003026](https://user-images.githubusercontent.com/106707879/171505232-5fad1acd-7dee-47bd-81ad-ffbd1df256d0.jpg)
![WoWScrnShot_060222_002450](https://user-images.githubusercontent.com/106707879/171505250-e782d1bc-8b6a-48f6-b768-d8abf5e7e5b9.jpg)

I am 80 lvl BM Hunter.

**What Should happen:**
when we press that skill pet goes to a closest crystal, dig it, take a piece of crystal and go it to the Voltarus castle.

**Comment by mfranca0009** [comment]
There's a 10-yard search radius to find a crystal from the `Blight Geist`, and from your screenshots, there isn't even a crystal within that distance; therefore he will not do anything.

This is intended and not broken. Feel free to re-open a new issue with more details. We can surely look into it with more information if it's a phasing problem.

**Comment by Echinaceax** [comment]
Found the issue @lecoo123 
with explain in new report for the Dev 

Thank you
