### ISSUE TITLE
[Item] Oozing bags do not always contain silver

### ISSUE THREAD

**Issue by GuppyCaat** [WoWManiaUK/Redemption#5846]
**Links:**

**What is Happening:** Oozing bags disappear from the inventory instead of opening

**What Should happen:** Loot should be added to my inventory before the bag disappears

**Comment by jeyrella** [comment]
Thanks for the ticket :)

Have tested and found that they *do* drop loot, but just not 100% of the time.  I have found an oblique reference that *suggests* this is actually correct but nothing concrete, as the main point of them is that they could contain a very rare pet.

Can you link to the evidence that shows they should always drop at least something?  Meanwhile I will look internally if there is anything obvious missing.

**Comment by jeyrella** [comment]
(item:  20768)

**Comment by GuppyCaat** [comment]
I added up all the possible content drop rates for the bags to 120,24% so them not containing loot makes very little sense to me. I can't find anything on them not containing loot at times while googling. Would you mind showing me the thing you found?

**Comment by GuppyCaat** [comment]
Yeah, it's all I can find for now. All I can say to confirm is that the last time I farmed for it was in retail wotlk and I can't remember them just disappearing like they do now. I'll keep looking

**Comment by Echinaceax** [comment]
yea same 

i found a 2012 https://www.youtube.com/watch?v=NsZ8nvJWYxw

**Comment by jeyrella** [comment]
Huh?  Right here
https://youtu.be/NsZ8nvJWYxw?t=37
Shows clearly a string of 4 bags being opened containing nothing but silver.  So this seems correct?

**Comment by Echinaceax** [comment]
> Huh? Right here https://youtu.be/NsZ8nvJWYxw?t=37 Shows clearly a string of 4 bags being opened containing nothing but silver. So this seems correct?

seems like at least silver is 100 drop

**Comment by GuppyCaat** [comment]
I don't get silver either, not in any of the bags. They just disappear, no loot window or anything.

**Comment by jeyrella** [comment]
> seems like at least silver is 100% drop
Yes, agreed, need to check that.  Not items though, clearly is not a 100% drop for items.

> I added up all the possible content drop rates for the bags to 120,24% so them not containing loot makes very little sense to me
Ah, the gambler's fallacy.  Remember drop chances are not cumulative, they are per item for that bag.

**Comment by GuppyCaat** [comment]
I think they're glitching out though, because they have also moved in the bag instead of opening when I've right clicked to open. Idk, they seem kinda buggy to me over all. If you're a GM, surely you can give yourself a couple of bags to try them out? Idk how that works though.

**Comment by Echinaceax** [comment]
> I think they're glitching out though, because they have also moved in the bag instead of opening when I've right clicked to open. Idk, they seem kinda buggy to me over all. If you're a GM, surely you can give yourself a couple of bags to try them out? Idk how that works though.

we check on the test server and copnfirm soon

**Comment by Echinaceax** [comment]
confirmed bugged 5/10 were empty 
no silver from any of them 
https://i.gyazo.com/dc393d4967e5c39e08f3b359c44b106b.mp4

**Comment by Echinaceax** [comment]
dont close your report when its confirmed @GuppyCaat  😄 

devs fix
janitor closes when its on live server

**Comment by Rushor** [comment]
A lot of items with contains other items have that problem, must be fixed with reference groups in the loot table

**Comment by mfranca0009** [comment]
The loot table is fine, and currently matches a WoTLK DB (https://wotlkdb.com/?item=20768) for drop rates and items dropped. Cavern of Times WotLK shows it drops nothing, which is not correct.

Added the money that was missing for the item, and I based the min-max amount from this video:
https://www.youtube.com/watch?v=INe-Xrus6LU

The minimum received from a bag that I saw was 10 silver 19 copper, whereas the maximum this player received was 23 silver 90 copper. That was the lowest/highest values seen out of the bags opened; if more information comes up we can adjust it accordingly.

**Comment by Echinaceax** [comment]
confirmed fixed in PTR 

![image](https://user-images.githubusercontent.com/39439201/173033751-35d27db1-d3ea-40cd-bc5d-11cad6c274b1.png)
![image](https://user-images.githubusercontent.com/39439201/173033993-41b242b8-211f-446d-bea5-74da038d7a9a.png)
