### ISSUE TITLE
Baelgun Excavation Site Elevator

### ISSUE THREAD

**Issue by jnewinski** [WoWManiaUK/Redemption#5848]
**Links:**

**What is Happening:**
Southern elevator to enter the Baelgun Excavation Site in Howling Fjord is blocked by the gate when the platform reaches the top. The gate opens after the platform has departed.

**What Should happen:**
The gate should open to allow access to the platform when the platform reaches the top

**Comment by Echinaceax** [comment]
hi @jnewinski 
Can you maybe screen shot or video the issue

I didnt have an issue with the doors

https://i.gyazo.com/7d688b48cfc0cfb56d86aed7da781e5d.mp4

**Comment by svijetlo** [comment]
https://mega.nz/file/WHxl2bQR#MdRyz70ow-NF8IYfsJgzf7MQbFLf8jx0lG6J6x2YBng
![WoWScrnShot_060522_150455](https://user-images.githubusercontent.com/61908373/172052045-ae5f2dab-2d77-4937-8574-09a415dec97b.jpg)
while elevator is in position door need to be open all the time , and close ones elevator goes down

**Comment by mfranca0009** [comment]
Just noting this here, I did see this problem. Once the PTR was restarted though, the issue was gone and it was working as it should.

An intermittent issue and I can't seem to find anything that stands out as a problem.

**Comment by mfranca0009** [comment]
**CHECK-UP #2**
Video: https://i.gyazo.com/3c177121fdefc38d5aed1d5e0922978f.mp4

Still functioning normally, BUT the gate is now delayed on opening when the elevator platform reaches the top. This is 7 hours after a rebuild was done on PTR. It seems that the problem progressively gets worse while the server is up for a long period of time. It corrects itself on server restart.

Still unknown what the problem could be at this point. However, it's now confirmed that it starts out fine, but progressively gets worse when the server uptime is high.

**Comment by svijetlo** [comment]
guess they just get out of sinc over time :'D seen it with elevator doors irl XD :'D
