### ISSUE TITLE
[quest] The Delicate Sound of Thunder - Rocket jump

### ISSUE THREAD

**Issue by jnewinski** [WoWManiaUK/Redemption#5849]
**Links:**

**What is Happening:**
While using the Iron Rune Construct during the quest "The Delicate Sound of Thunder" in Howling Fjord, activating the construct's first ability, "rocket jump" from the northernmost jump platform failed to complete the jump and instead granted very high (>300%?) movement speed for 60 seconds.

**What Should happen:**
Activating the iron construct rocket jump ability should transport the construct from one platform to another and not allow free movement until that action is completed.

**Comment by Echinaceax** [comment]
Thanks @jnewinski 
we will check it out

**Comment by svijetlo** [comment]
http://www.wow-mania.com/armory?quest=11495
http://www.wow-mania.com/armory?spell=44608
how to reproduce , take quest, go to area where runes are , stay close to rune but not on it , press rocket jump and it will happen , will upload vid of bug

**Comment by mfranca0009** [comment]
All set.

### Corrections
- [x] Correctly implemented the `Rocket Jump` spell from the vehicle to now trigger the rocket flight path; not just the movement speed  'Rocket Jump' buff.
- [x] The movement speed buff, `Rocket Jump` will now only be triggered when the vehicle has started its rocket flight path.
- [x] Disabled player control during the rocket flight path between two platforms.
- [x] Smoothed out the flight movement during the rocket flight path, it is now not shaky or jumpy.
- [x] Added the appropriate spell condition checks for implicit target requirements of `Rocket Jump` from the vehicle.
- [x] Removed and updated some unused and unnecessary script data related to the platforms, vehicle, and NPC triggers.

**Comment by Echinaceax** [comment]
Confirmed fixed in PTR all above list 

https://i.gyazo.com/64c17c60fd5fc81d4f02c060f94c2e53.mp4

**Comment by Echinaceax** [comment]
On live
