### ISSUE TITLE
[Raid] SSC - Fathom-Lord Karathress permanent encounter in progress

### ISSUE THREAD

**Issue by Greywolf59** [WoWManiaUK/Redemption#5850]
**What is Happening:**
NAXXRAMAS (RED too iirc)

**So what happened** 

after killing Morogrim Tidewalker (the giant) and Fathom-Lord Karathress (the guy with adds) one of our raid members reloged. When he did so, he appeared dead outside, when ressed he came to life outside of the dung and couldn't enter. We have noticed that our potions were on neverending cooldown (but we could eat/drink) although we were not in combat, nor there was a visible combat bug. 

So anyone who died or left the raid couldn't get back, I think if you tried to walk into the raid it tells you "can't enter when encounter is in progress". Warlock summon doesn't work either. Until now I thought this happens only when the raid reaches the room/platform of the last boss, Lady Vashj, that is well-documented occurance of this bug, but now whe had it after killing only those two aformentioned bosses, we skipped the rest.

Sorry for quick and measely report, it is late.

**Comment by Greywolf59** [comment]
What do you mean? Like any mob at all? Well then it is a problem no? Since any person who dies and releases or disconnects can't ever get back, unless maybe the whole raid wipes.

**Comment by Greywolf59** [comment]
Update: we killed the giant boss and there was no combat/boss engage bug. The last time we noticed he bug was after Fathom-Lord Karathress https://tbc.wowhead.com/npc=21214/fathom-lord-karathress or during clearing trash between him and Leothorass after killing Fathom Lord so probably the perpetrator of the bug is Fathom-Lord.

**Comment by Airin258** [comment]
Confirmed on PTR together with Nillibiquito. All the bosses exept for Fathom-Lord Karathress were left untouched, one of us died in fight and was unable to enter ("Encounter in progress"). Bug persisted after both of us died and ressurected, making raid unavailable untill reset.

**Comment by Keader** [comment]
Test now please
