### ISSUE TITLE
No Blight Crystals to harvest

### ISSUE THREAD

**Issue by Pjotr-V** [WoWManiaUK/Redemption#5851]
**Links:**

**What is Happening:**
On "It Rolls Downhill". In Scourge disguise, controlling a Blight Geist. There are no crystals to harvest.

**What Should happen:**
There should be blight crystals around the transport pad to Voltarus. None are available

**Comment by Echinaceax** [comment]
thanks for reporting @Pjotr-V 
Fixed here https://github.com/WoWManiaUK/Redemption/issues/5845 will be on next update
