### ISSUE TITLE
[NPCs] Several More Mobs That Target the Hunter Over the Pet

### ISSUE THREAD

**Issue by kamoodle5** [WoWManiaUK/Redemption#5852]
**Links:**
Forgotten Peasant: https://www.wow-mania.com/armory/?npc=27226
Forgotten Knight: https://www.wow-mania.com/armory/?npc=27224
Forgotten: Rifleman: https://www.wow-mania.com/armory/?npc=27225
Forgotten Footman: https://www.wow-mania.com/armory/?npc=27229
Oil-Stained Worg: https://www.wow-mania.com/armory/?npc=25791

Note: The first four mobs are related to this issue: #5801 

**What is Happening:** 
1.) The mobs will automatically run towards the hunter instead of the pet when engaged, regardless of threat. 
2.) Like with my Water-Crazed Spirit issue, the wolf actually behaves normal and will attack the pet once out of the water. Otherwise, it will still engage the hunter.
3.) When the hunter feigns death, the mobs evade reset and don't ever target the pet.
4.) Intimidation does not work on these mobs.
5.) There's actually a different issue that is shown on the first video regarding the Forgotten Knight. You'll notice how the Knight keeps walking even when he wants to attack me.

**What Should happen:** The mobs should attack the pet if it has more threat, and they should not reset if the hunter FD's.

Here are my video clips showing the issue with these mobs. The first is about the Forgotten mobs, and the second is the wolf.
https://youtu.be/28LMRQ3oGjs
https://youtu.be/cH4P1qeYf5c

**Comment by Echinaceax** [comment]
Thank you for reporting @kamoodle5

**Comment by wow-mania** [comment]
won't be fixed at this time

**Comment by Lumber-Jack-2** [comment]
issue her eis the phasing aura, not same issue like https://github.com/WoWManiaUK/Redemption/issues/5811 actually, so must stay closed

**Comment by Echinaceax** [comment]
> issue her eis the phasing aura, not same issue like #5811 actually, so must stay closed

just tested this one @Rushor these ignore pet (Oil-Stained Worg: fixed here #6102)

and yes it should be fixed for the ones listed above if possible 

https://i.gyazo.com/b5b7b2e5b562a46c1908a0dac90fb153.mp4
https://i.gyazo.com/dc244ca40450ebd4f708938b57d2904b.mp4
https://i.gyazo.com/62b2b29df847317fa21bc6a3988afd22.mp4
https://i.gyazo.com/e6a7482a7edb56b6f0472fafc2c293cc.mp4

**Comment by Lumber-Jack-2** [comment]
Only way to fix this i See would be to remove the phasing aura they have

**Comment by Echinaceax** [comment]
> Only way to fix this i See would be to remove the phasing aura they have

we can chat in dev @Rushor np 

update 
due to the side effects this could cause elsewhere, we are not touching this.
