### ISSUE TITLE
[Currency] stone keepers shards - not given from dungeon bosses in Northrend

### ISSUE THREAD

**Issue by Dmw1981** [WoWManiaUK/Redemption#5853]
![image](https://user-images.githubusercontent.com/64038447/172425429-28fa10b6-747d-4eb6-8ebb-046abe989fd1.png)
when completing lvl 80 dungs you should be awarded stone keepers shards when your faction has control of wintergrasp
(ss is from a HoR hc run)

**What is Happening:**
no shards being awarded

**What Should happen:**
shards should be awarded along with the EOT

**Comment by Echinaceax** [comment]
Thanks for reporting @Dmw1981 

Is this a new issue that has stopped working recently ?

**Comment by Echinaceax** [comment]
> i only noticed it today when i was going to trade my shards in and realised my bag was a lil short

Ok we can check this out, thanks

**Comment by Echinaceax** [comment]
Confirmed bugged on PTR 

![confirmed no stone keeps shards](https://user-images.githubusercontent.com/39439201/172491102-b41faed8-e625-402d-81fd-3778e6886b90.jpg)

**Comment by mfranca0009** [comment]
More information:
![image](https://user-images.githubusercontent.com/26092980/172979490-aaac6fd8-2d7b-471f-a00f-df8c8b8996fa.png)

From those comments, seems it can be random 1-4 per normal/heroic boss kill for WoTLK dungeons. Someone said 1-3 for a normal boss, but then it was invalidated by someone claiming they received 4 on a normal boss; prob best just to put 1-4 for both normal/heroic boss kill.

**Comment by mfranca0009** [comment]
All set, corrected the conditions that determine when `Stone Keeper's Shard` drops from WoTLK dungeon bosses.

This is most likely the primary issue. If a specific boss does not drop it still, then a new report should be made specifying the NPC having the problem.
