### ISSUE TITLE
[Spell] Corpse explosion + Raise Dead

### ISSUE THREAD

**Issue by svijetlo** [WoWManiaUK/Redemption#5854]
**Links:**
http://www.wow-mania.com/armory?spell=49158
http://www.wow-mania.com/armory?spell=52143
http://www.wow-mania.com/armory?spell=46584
**What is Happening:**
ones dethaknight with permanent pet does Corpse explosion on his pet next time he summons pet , pet will appear as pile of flash and bones not doing a thing till moment you move or give him command to attack , 
this will happen only if pet is set on passive mode 
in this time you can not use corpse explosion or anything on pet will post vid of it 
https://mega.nz/file/XHR1EC5I#9XV4fn150r_f5L_asSKajEEhPhLdHXTkE9LNF1TaME4
**What Should happen:**
no matter what stance is pet on aggressive , passive or defensive it should summon back as pet not pile of bones and flash after you use corpse explosion on it

**Comment by Echinaceax** [comment]
I can confirm this, 
i saw this same issue too when i was checking another report

**Comment by Keader** [comment]
try now please

**Comment by Airin258** [comment]
Still present.
Note: it seems to be affected not by pet mode directly. It seem to depend on if ghould makes any sort of action: moving, attacking, using skill, etc. You can clearly see it on 3rd video. Also issue is not affected if pet was summoned or re-summoned in combat or out of combat.

Passive state: https://youtu.be/tCzgyZcCcrs
Defensive state: https://youtu.be/xIGtTO2ib3A - you can see that ghoul is a pile of meat until i start attacking dummy, so ghould starts attacking it too.
Agressive state with instant aggro on dummy: https://youtu.be/I9WC19xCFxI - instantly turned into normal state
Aggresive state out of dummy range: https://youtu.be/Ql_XlSgHZuk

**Comment by Keader** [comment]
try again 👯

**Comment by Airin258** [comment]
Still present, however now ghoul missing cast time and expolsion animation.
https://youtu.be/W2aiSQ396RA

**Comment by Airin258** [comment]
Fixed, animation, explosion cast and propper summon are fine.
https://youtu.be/NHEgyj5n7v4
