### ISSUE TITLE
[ Talent ] Burning Determination getting refreshed forever

### ISSUE THREAD

**Issue by Plecharka** [WoWManiaUK/Redemption#5855]
**Links:**
https://www.wow-mania.com/armory/?spell=54749

**What is Happening:**
When the mage with this specific talent gets interrupted with any silencing effect, it gives him immunity to silence for the next 20 seconds, with each new silencing effect refreshing the buff on him, practically forever if he keeps getting silenced, basically making him immune to silence all the time.

**What Should happen:**
The buff should be applied only for one silence within the next 20 seconds from the first one and then dissapear.

**Comment by Echinaceax** [comment]
Thanks for reporting @Plecharka 
we will take a look

**Comment by Franciss983** [comment]
Hello, 
1) What specific silence spell has been used?

I did reproduce situation with rogues kick and it didnt refresh mages Burning Determination.

[ Talent ] Burning Determination should last whole 20 seconds from the first silence when is applied. The next silence should not cancel the effect or refresh the effect.
wiki: When Interrupted or Silenced you have a X% chance to become immune to the next Interrupt or Silence mechanic. Lasts 20 sec.

Heres video: https://www.youtube.com/watch?v=w33g5CnX1v8

Did not found any proof that about effect that should be removed with next silence/interrupt. So from what can I see it works like it should.

**Comment by Mwollfiez** [comment]
in the spec description it clearly says that you are immune to the "Next" Interrupt/Silence ability used on you which it means for the next one and only that then the effect should disappear from the player, and To regarding what ability was used to refresh the Buff ,test it with a shaman wind shear u will see that the buff will refresh by itself.

**Comment by Franciss983** [comment]
Wind Shear https://www.wow-mania.com/armory/?spell=57994 is refreshing debuff of https://www.wow-mania.com/armory/?spell=54749. Confirmed.

**Comment by Mwollfiez** [comment]
https://www.youtube.com/watch?v=xwO8UiVqbps 
This is a youtube video of a mage dueling in 2015  , I dont know if its an acceptable proof or not 
But you can see yourself at 2:25 in the video The mage was silenced from a Death knight you can see the Buff applied and at 2:38 the effect was still there and it disappeared and thats clearly because of Death knight using an interrupt aka Mind freeze.
otherwise there is no reason for the buff to be dispelled at 8 seconds

**Comment by Franciss983** [comment]
Evet Wolfiez, it clearly says that you are immune to the next spell in description.
And I did found forum topic related to 2008. Here they say.: "Should not to negate the effect of all silences and lockouts."
https://www.mmo-champion.com/threads/612885-burning-determination
So you are right the buff  https://www.wow-mania.com/armory/?spell=54749 does not go off after next interupt like it should.

Also myself was not able to find video of 2008-2009.

Anyway i will test all the interupts and gonna list them here.

Thank you for making it clear :)

**Comment by Franciss983** [comment]
I have been testing  https://www.wow-mania.com/armory/?spell=54749 for each interupt in the game.

There are 3 options as a results for this test. I will check ones that are working like they should, others remain unchecked with explanation about whats hapening.

a) Burning Determination works like it should in that case.
b) Burning Determination refresh duration when next interupt is used, buff does not dissapear on next interupt.
c) Burning Determination _does not_ refresh duration when next interupt is used, buff does not dissapear on next interupt.

Death Knight:

- [ ] https://www.wowhead.com/spell=47476/strangulate 
a) Burning Determination works like it should in that case.

- [ ] https://www.wowhead.com/spell=47528/mind-freeze 
c) Burning Determination _does not_ refresh duration when next interupt is used, buff does not dissapear on next interupt.

Warrior:

- [ ] https://www.wow-mania.com/armory/?spell=72 
c) Burning Determination _does not_ refresh duration when next interupt is used, buff does not dissapear on next interupt.

- [ ] https://www.wow-mania.com/armory/?spell=6552 
c) Burning Determination _does not_ refresh duration when next interupt is used, buff does not dissapear on next interupt.

Paladin:

- [ ] https://www.wow-mania.com/armory/?spell=53711 
c) Burning Determination _does not_ refresh duration when next interupt is used, buff does not dissapear on next interupt.
(when used https://www.wow-mania.com/armory/?spell=31935)

Shaman:

- [ ] https://www.wow-mania.com/armory/?spell=57994 
b) Burning Determination refresh duration when next interupt is used, buff does not dissapear on next interupt.

Hunter:

- [ ] https://www.wow-mania.com/armory/?spell=34490 
b) Burning Determination refresh duration when next interupt is used, buff does not dissapear on next interupt.

- [ ] https://www.wow-mania.com/armory/?pet=34
c) Burning Determination _does not_ refresh duration when next interupt is used, buff does not dissapear on next interupt.

Mage:

- [ ] https://www.wow-mania.com/armory/?spell=2139 
a) Burning Determination works like it should in that case.

Rogue:

- [ ] https://www.wow-mania.com/armory/?spell=1766 
c) Burning Determination _does not_ refresh duration when next interupt is used, buff does not dissapear on next interupt.

- [ ] https://www.wow-mania.com/armory/?spell=48676 
c) Burning Determination _does not_ refresh duration when next interupt is used, buff does not dissapear on next interupt.

Warlock:

- [ ] https://www.wow-mania.com/armory/?spell=19647 
b) Burning Determination refresh duration when next interupt is used, buff does not dissapear on next interupt.

(when active https://www.wow-mania.com/armory/?spell=691)

- [ ] https://www.wow-mania.com/armory/?spell=31117 
c) Burning Determination _does not_ refresh duration when next interupt is used, buff does not dissapear on next interupt.

(when dispelled https://www.wow-mania.com/armory/?spell=47843)

Priest:

- [ ] https://www.wow-mania.com/armory/?spell=15487 
(a) Burning Determination works like it should in that case.

Druid:
none

**Comment by Keader** [comment]
try now please :)

**Comment by Echinaceax** [comment]
> try now please :)

Me and Hatah will check all classes again for you tomorrow

**Comment by svijetlo** [comment]
i did this last night could not sleep it work fine now buff does not get refersh constantly
