### ISSUE TITLE
[Quest] Battle of the Crimson Watch - Quest bugs if another player failed /didnt finish the quest

### ISSUE THREAD

**Issue by lvl4peon** [WoWManiaUK/Redemption#5856]
**Links:**
https://www.wowhead.com/wotlk/quest=10781/battle-of-the-crimson-watch

**What is Happening:**
Mobs despawn during the Gauntlet, once that happens the quest becomes bugged and will not respawn the adds when abandoning the quest to retry when failed when you leave the area  

**What Should happen:**

**Comment by Echinaceax** [comment]
Thanks for reporting @lvl4peon 
Seems this could never be reproduced in the past #5756 #1587 with this one being the most recent one #5756

can you see if your experience was the same as #5756 or different?

**Comment by lvl4peon** [comment]
Yes this was the issue, same as here https://github.com/WoWManiaUK/Redemption/issues/5756 
Greywolf59 summarized it very well on the "what should Happen" paragraph

**Comment by mfranca0009** [comment]
Fix in-progress.

**Comment by Echinaceax** [comment]
confirmed fixed in PTR 
all looking and funtioning as it should 

https://i.gyazo.com/40e4666c7f3f3bcf178ea7139fd4d7b0.mp4

![shadow ](https://user-images.githubusercontent.com/39439201/174443405-184f98b7-f4d6-4f96-b7d2-b8acf60ac287.jpg)
