### ISSUE TITLE
[Spell] Scatter Shot - disorients the target isnt working as it should

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Redemption#5857]
**Links:**

Scatter Shot https://www.wow-mania.com/armory/?spell=19503

timestamp 2:22 https://www.youtube.com/watch?v=jukCkN812Iw

![image](https://user-images.githubusercontent.com/39439201/173443067-74f2ee49-bbf5-4777-b51d-64a79c657744.png)

**What is Happening:**

"Disorients the target" isnt working as it should
1 https://i.gyazo.com/373a3182f9b9167b9e2160749884ead3.mp4
2 https://i.gyazo.com/96d5938ad86780c048c62c6acb72ecb1.mp4
3 https://i.gyazo.com/acebc4ddcae42f17e0041e56c85ee44c.mp4

- [ ] When opening with Scatter Shot, the npcs still come running / or in pvp 

works (hit and miss)
pet attack first https://i.gyazo.com/ea4ae5ba8bbecee2cf829bae572d0950.mp4
me without pet https://i.gyazo.com/7a397c563fe4da5cb5573599794fc95c.mp4

**What Should happen:**

 Scatter Shot should work whether its used as an opening shot or in a rotation 

seems very hit and miss, but reported by ingame player so i thought i would check it out 

**Extra info**
Rhino charge https://www.wow-mania.com/armory/?spell=55193 even though affected by Scatter Shot

https://i.gyazo.com/6fb0375b8f424ab365cb6a64b046e22a.mp4

**UPDATE** 
Found the issue i think
Its the max range issue again same as other report we had about other pet issues https://github.com/WoWManiaUK/Redemption/issues/5814#issuecomment-1121228341
when im melee range is works https://i.gyazo.com/e50de1eee958ee28b4481ed5637b3ace.mp4

**Comment by Keader** [comment]
try now please

**Comment by Airin258** [comment]
Seems to work fine:
Without pet (hit) https://youtu.be/mTKhJ5TzjTs
Without pet (miss) https://youtu.be/0HqAuhL7DaU

With pet on idle (hit) https://youtu.be/xzs45Txht8k
With pet on idle (miss) https://youtu.be/BQeQ53_dE-Q

Pet attacks first (hit) https://youtu.be/PYwaK7-twSI
Pet attacks first (hit) https://youtu.be/aKqLK_aq2xU
