### ISSUE TITLE
[NPC] Wintergrasp Cannons - evade issue 

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Redemption#5858]
### Reported by player and fixed a few months ago

I saw it is still an issue earlier today

![cannons](https://user-images.githubusercontent.com/39439201/173834503-520bda52-e031-4acc-90c9-8258e7c97beb.jpg)

**What is Happening:**
After an old fix a few months ago, these are still an issue 

**What Should happen:**
Cannons should NOT evade 

**info from old fix ....**
couldnt reproduce the evade ...
but did catch some other stuff also happening 

**reproduce:** 

- enter cannon (defender)
- player exits the cannon, it leaves some player stats behind, like evade, block etc...
- i just got block to show up on this test https://i.gyazo.com/0005da8c6789f5feaf63049cadfb60c5.mp4

Screenshot from player that reported to me a few months back 
![image](https://user-images.githubusercontent.com/39439201/173879040-0b5e3854-6285-4513-8d47-f232934d0305.png)

**Comment by mfranca0009** [comment]
Rushor was fixing this I believe.

**Comment by wow-mania** [comment]
either fixed by next milestone or it will be deferred to future time

**Comment by Echinaceax** [comment]
> either fixed by next milestone or it will be deferred to future time

Waiting rushors reply

**Comment by Echinaceax** [comment]
Seems good @wow-mania 
Can hotfix and wait for feedback from players, thanks

**Comment by Echinaceax** [comment]
### had an idea so new test with seige 

test 1 was fine 
https://i.gyazo.com/80f99e43513ee8a68e38401578e1c973.mp4

test 2 new battle (cannon started evading again) 
https://i.gyazo.com/f07d3671e7ad838f28aaa3e7f8aca2ad.mp4

**Comment by Echinaceax** [comment]
cant fully confirm this fix atm, PTR seems good now 
so we are waiting players feedback on this, thanks :)
