### ISSUE TITLE
[Wintergrasp] Vehicle Teleport issue - Player fall through map when exiting the vehicle

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Redemption#5859]
### Vehicle Teleport issue reported by player

![fell through map](https://user-images.githubusercontent.com/39439201/173875879-f4c5e600-fd42-4796-8115-530a01cee0d9.jpg)

**What is Happening:**
`"There's an odd thing that happens when players get into sieges and move from fortress to the outside via the portal and move along the fortress wall and then exit the vehicle, they sometimes fall into an abyss endlessly."`

**What Should happen:**
Player shouldnt fall through map when exiting the vehicle

### Test done 

Reproduced by me in PTR 
https://i.gyazo.com/57831b3ff34788558f77c300b992855b.mp4

GPS when teleported
![image](https://user-images.githubusercontent.com/39439201/163265954-d7073e96-c8f0-46b9-9b80-773720ad3128.png)

GPS while under the map
![image](https://user-images.githubusercontent.com/39439201/163266476-0eba9cfe-7844-45cf-8fb2-2d2f0ac61f07.png)

GPS when i got back up
![image](https://user-images.githubusercontent.com/39439201/163266617-f015e9b1-7844-4fd0-8221-cffbb0f9c353.png)

- [ ] Teleport 2 (confirmed)

GPS when teleported
![image](https://user-images.githubusercontent.com/39439201/163267064-9ed76e0c-01da-4ebf-8b95-485cdd872982.png)

GPS while under the map
![image](https://user-images.githubusercontent.com/39439201/163268058-cb7b4d15-8ac0-4c18-836f-1e367e220547.png)

GPS when i got back up
![image](https://user-images.githubusercontent.com/39439201/163268226-ea7a7a05-132a-4b70-99bf-05e03ce76656.png)

**Comment by mfranca0009** [comment]
All set. It was teleporting the vehicle twice instead of just using the appropriate spell once; causing the siege vehicle to clip through the ground slightly causing the problem.

**Comment by Echinaceax** [comment]
Confirmed fixed in PTR 
10 test complete not fall through map occurred 

https://i.gyazo.com/b10e68552933fb96b249f6a47699ae3b.mp4
