### ISSUE TITLE
[Quest] Convocation at Zol'Heb

### ISSUE THREAD

**Issue by Earthliving** [WoWManiaUK/Redemption#586]
Relevant target Prophet of Akali spawns, can be damaged until 70%. Becomes stunned, after stun wears is immune. Doesn't attack, just follows and despawns.

**Comment by fvicaria** [comment]
![image](https://cloud.githubusercontent.com/assets/9414661/21043787/921043f6-bdf0-11e6-8be9-ad7ada020e91.png)

Also works fine. It will stun you for a while and then Har'koa come to help you and joins the fight.

**Comment by Lemayonaise** [comment]
I tried doing this before on gnome mage, couldnt even spawn the guy it said "you can't do that right now". I tried standing inside circle and outside
