### ISSUE TITLE
[Player] Missing worgen corpse model

### ISSUE THREAD

**Issue by Airin258** [WoWManiaUK/Redemption#5860]
![image](https://user-images.githubusercontent.com/96421124/174165618-78e00a4a-d0c9-42a5-8706-52feead7253b.png)

**What is Happening:**
Worgen skeleton (both genders) model is not present in game, replaced with "missing model" cube. Fresh client, seen by other players as well. This happens only with skeletons that replaces actual corpse after player releases.

**What Should happen:**
Skeleton should be visible after release.

**Comment by Echinaceax** [comment]
confirmed bugged we seen it while testing on PTR

**Comment by jeyrella** [comment]
known and still waiting a client change, see #3392

**Comment by GMZinius** [comment]
For notes: Fixed here #3392
