### ISSUE TITLE
[NPC] Pustulent Horror evades and jumps off cliff due to position misalignment

### ISSUE THREAD

**Issue by jeyrella** [WoWManiaUK/Redemption#5861]
**Links:**
from PTR
ID 31139 
DB GUID: 123529
current GUID: 2761

**What is Happening:**
The Pustulent Horror in the left of this picture is positioned in his parapet a little too much to the south and east (bottom and right as looking at this pic)
Results in falling off the edge of the parapet at the end of one of his pathing to the ground below, upon which he immediately resets and evades
![image](https://user-images.githubusercontent.com/46089380/174431660-7635b567-c2a5-495f-9710-0689aec8f009.png)

```
NPC currently selected by player:
DB GUID: 123529, current GUID: 2761.
Faction: 21.
npcFlags: 16777216.
Entry: 31139.
DisplayID: 27807 (Native: 27807).
Level: 82.
EquipmentId: 0 (Original: 0).
Health (base): 67405. (max): 67405. (current): 67405.
InhabitType: 3
Unit Flags: 64
UNIT_FLAG_UNK_6 (0x40)
Unit Flags 2: 2048.
Dynamic Flags: 0.
Faction Template: 21.
SpawnTime: Full:5m Remaining:0s
Loot: 31139 Pickpocket: 27533 Skinning: 0
InstanceID: 0
Phasemask: 1
Armor: 10356
Position: 6258.754883 1142.242798 327.466583.
AIName: SmartAI ScriptName: 
Flags Extra: 0
* has spell click (16777216)
MechanicImmuneMask: 8388624
MECHANIC_FEAR (0x5)
MECHANIC_HORROR (0x18)
```

**What Should happen:**
Should be repositioned to be in the middle of the parapet c.f. the other horror in the right of the picture above

**Comment by mfranca0009** [comment]
All set.

- [x] Fixed 4 position issues with `Pustulent Horror` NPCs
- [x] Added two missing `Pustulent Horror` NPCs
- [x] Corrected emote states, some were not displaying their throw-ready emote.
