### ISSUE TITLE
[Spell] ID:57722 Hostiles benefit from Totem of Wrath

### ISSUE THREAD

**Issue by Airin258** [WoWManiaUK/Redemption#5862]
**Links:**
https://www.wow-mania.com/armory/?spell=57722

**What is Happening:**
![Screenshot 2022-06-20 225440](https://user-images.githubusercontent.com/96421124/174650072-1843a24d-66f9-4515-9df9-5e7dfd663067.png)
Enemies that can attack you (hostile by default or neutral that can be attack target) get buff from Totem of wraith. Initial screenshot from life is Festergut, others made on PTR.

**What Should happen:**
Enemies should not benefit from any of player totem.

**Comment by Echinaceax** [comment]
No issue as explained via discord

**Comment by Airin258** [comment]
Sorry, got confused by description of totem. Was thinking that it increases player's chance, like draenei racial, not debuffs enemy, like shadow priest's talent.
