### ISSUE TITLE
Midsummer festivals  [Torch Catching] ID 11657 / 11923

### ISSUE THREAD

**Issue by D00MHaMM3R** [WoWManiaUK/Redemption#5863]
quests [Troch Catching] and [More Torch Catching] bugged

**Links:**
https://www.youtube.com/watch?v=Pjnlfb2_PiE
https://www.wowhead.com/quest=11657/torch-catching
https://www.wowhead.com/quest=11924/more-torch-catching

**What is Happening:**
No torches flying

**What Should happen:**
As u see in the clip a torch flyes and it must be catched

**Comment by Echinaceax** [comment]
confirmed bugged on Alliance [Ironforge] [Darnassus] [Stormwind City] [The Exodar]

https://i.gyazo.com/1346b473eac0195ba1aa03346b6fe573.mp4
https://i.gyazo.com/a7ddfadd947f2b6693514b2d48ca6f55.mp4
https://i.gyazo.com/d88866214dcd9eca8364209c38bbff54.mp4
https://i.gyazo.com/19a2c3c080e25413a3036ea7009b8a81.mp4

confirming Horde in a few mins

**Comment by Echinaceax** [comment]
> Tried in Ogrimmar too

i know, i test above

**Comment by jeyrella** [comment]
High priority as time-limited event

**Comment by mfranca0009** [comment]
Should be all set, tested on PTR.

Video: https://www.youtube.com/watch?v=fRmKot1U8fU

**Comment by Echinaceax** [comment]
Confirmed fixed on PTR 

https://i.gyazo.com/4a90470c2a7c4eb4a7a94566f41d592e.mp4
