### ISSUE TITLE
[PvP] Wintergrasp teleport

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#5865]
**Links:**

**What is Happening:** When you run down from the base graveyard in wintergrasp, you hit an unavoidable trigger that teleports you in front of the keep. This allows the attacking team to just spawn camp you since everybody is forced to funnel into this individual spot, completely eliminating the option of running to the side to attack on other flanks or fighting elsewhere.

**What Should happen:** There should be no invisible teleporting trigger?

**Comment by jeyrella** [comment]
This is known. Thanks.

**Comment by Echinaceax** [comment]
Yes we know about it @Oganku 
already noted 

https://i.gyazo.com/e46a5bd88013663189304202c9a6e82f.mp4
