### ISSUE TITLE
Problem with voting

### ISSUE THREAD

**Issue by Elsi89** [WoWManiaUK/Redemption#5866]
**Links:**https://www.wow-mania.com/account/voting

**What is Happening:** I have problem with voting. All day i send voting on my account Elsi89 and i dont take maniacs point. I think problem is this that i have account and my husband and this is the same IP. But when he voting ho dont take too this maniac points. :/ this is not fair i think. what can i do? My husband character name :marmarohn i dont know his login.

**What Should happen:**i think me and husband can voting and get maniacs point for this

**Comment by Echinaceax** [comment]
hi @Elsi89, Github is for ingame bugfixes only

Voting system is done from a 3rd party, 
i would chat with the community in discord for the best way to vote for your situation
