### ISSUE TITLE
[ICC/Boss] Gunship Pet Issues

### ISSUE THREAD

**Issue by liamyloo1** [WoWManiaUK/Redemption#5868]
I have looked for this issue on Github and can not find anything, please forgive me if this is duplicate.

**What is Happening:**

Currently if you have a pet on Gunship, be it Warlock Pet or Hunter Pet, it will lock in position and not damage any adds. You must then re-summon your pet after leaving ship.

You can replicate this on Gunship.

**What Should happen:**

Pet should attack who you command it to, regardless of where on the ships. 

Three links are below, one from the Server that shall not be named, where you can see all pets are available and attacking.

One from the OG Wotlk where again, pets are attacking on both ships.

and finally one from OG Wotlk where you can see the same behaviour with Warlock pets.

https://www.youtube.com/watch?v=R7D9mGmQKfE
https://www.youtube.com/watch?v=JLp9WytoIlo [Timestamp: 2:19 to see pet come to opposing ship]
https://www.youtube.com/watch?v=IX41YhuFTfk [Warlock POV] [Timestamp: 1:35 to see Warlock Pet on opposing ship]

**Comment by svijetlo** [comment]
pet on those fights is known bugs, not sure is it core issue and can it be fixed at the moment

**Comment by Keader** [comment]
It's miss implementation of mmap in gunship
since it's a realy easy fight already, dont belive it's a big issue... since cost of fix it is realy high
