### ISSUE TITLE
Buying some time quest - Lurid not doing anything

### ISSUE THREAD

**Issue by Doxxy0** [WoWManiaUK/Redemption#5869]
**Links:**
https://www.wowhead.com/quest=11938/buying-some-time
https://wotlkdb.com/?quest=11938
**What is Happening:**
Lurid is not doing anything, just follows me silently even when npcs are hitting him
![image](https://user-images.githubusercontent.com/84509345/176976971-62762ed1-edd0-499d-a24d-ae3ee26403ed.png)

**What Should happen:**
Should start beating others, as he is supposed to assist me

**Comment by jeyrella** [comment]
So. Having researched this, While this technically true, this is exactly how he behaved in retail in blizzard’s release.
So while it’s great that you reported this, we appreciate it, we won’t fix it at this time.
