### ISSUE TITLE
[BOSS] Teron Gorefiend has no loot on Naxx

### ISSUE THREAD

**Issue by Greywolf59** [WoWManiaUK/Redemption#5870]
**Links:**
https://www.wow-mania.com/armory/?npc=22871

**What is Happening:**
Today on NAXXRAMMAS reslm we have killed Teron Gorefiend and he had no loot. Was not lootable. I forgot to check if we got BoJ

PS: My personal guess is that it might be a result of player in ghost form landing the deathblow but I am not sure if that happened or not.

**Comment by fvicaria4drest** [comment]
Just checked it has and you can see it on the armoury. The drop rate is low so yes you can get nothing potentially.
Can someone confirm on ptr and close it please

**Comment by Greywolf59** [comment]
How can you get No loot at all from any raid boss? Also he was not lootable, couldn't even get gold, no pouch/loot icon on hover. I don't know if we even got Badge of Justice for the kill.

**Comment by Echinaceax** [comment]
from what i just saw on PTR @Greywolf59 

I could loot him 

![image](https://user-images.githubusercontent.com/39439201/177169551-28ad522c-ed3e-456a-84ee-b74ac4b00591.png)

**Comment by Greywolf59** [comment]
Okay, have you tried to land a killing blow as a ghost? Zhst is the only thing that comes to mind. I also know that on Red there never was an issue. But this is second time we are without loot on Naxx.

**Comment by Echinaceax** [comment]
Strange @Greywolf59 
not yet, this was just a first test, will try and get a full test later

**Comment by Greywolf59** [comment]
Cool. Since we plan to stay on Naxx realm on level 70 until we down the whole BT and longer probably I will let you guys know if this occur again with the loot. But I will mention to the raid for now not to use ghost abilities near Teron when he is at 5% hp and lower.
