### ISSUE TITLE
[BOSS] Reliquary of Souls Phase 1 hits too hard

### ISSUE THREAD

**Issue by Greywolf59** [WoWManiaUK/Redemption#5871]
**Links:**
Essence of Suffering (boss): https://wow-mania.com/armory/?npc=23418
https://wowwiki-archive.fandom.com/wiki/Reliquary_of_Souls#Essence_of_Suffering
Fixed issue: https://github.com/WoWManiaUK/Redemption/issues/5720 

**What is Happening:**
The boss hits for about 4k damage. Since there is no healing possible in this phase it is pretty much undoable for Naxxramass players who have on lvl 70 with full t6 just 18k hp as tanks and 10-12k as melee plate dps

**What Should happen:**
The boss should hit for far less. I will provide the video if/when I find it again. I think I provided one before somewhere where there was much lower hits.

**Comment by Echinaceax** [comment]
thanks @Greywolf59 
if you can find also some documentation on how much damage it should do would be great :)

**Comment by Greywolf59** [comment]
Oh nice, it even says the damage on wowwiki.
Here is the damage on our two tanks.
https://i.gyazo.com/3dec3ac85e78482fb0cb68b63eb9b68b.jpg
https://i.gyazo.com/59a7a758ff49cb203ed9a821ccb2e516.png

**Comment by Echinaceax** [comment]
No @Greywolf59 its not

@fvicaria4drest reopening this, this hasnt been looked into yet 😃

**Comment by fvicaria4drest** [comment]
We should not "fix" things just to make it easier. If it works correctly we should not change it.

**Comment by Greywolf59** [comment]
What? Aren't you a blizzlike server? And it does not work correctly and it is UNDOABLE on Naxx realm.

**Comment by jeyrella** [comment]
Unfortunately due to the extreme amount of work this would take (a complete rewrite!), and priorities vs. resources we have available, it would be the near side of never before this is looked at.
Therefore will close it with the specific label of "not planned for now", so that we can track it such that if in some time in the future we do have a space, we can bring it back to the table.

**Comment by Greywolf59** [comment]
Well as long as if we get to that boss there will be gm to o kill it for us it is fine. But it is problematic cause this boss are 3 seperate npcs which all need to die to open dooor to top of the BT. I know we csn't demand loot in that case either but... It is almost like ICC to tbc (SWP like RS and wing bosses) so idk how is that to be managed...

**Comment by jeyrella** [comment]
Yes, call a GM and reference this.  They should use .damage for each boss phase, rather than .die.

**Comment by Greywolf59** [comment]
*BUMP* since there is only three active issues on this github atm
