### ISSUE TITLE
[Zone] Wintergrasp spirit guides - Graveyard spirit guides arent switching appropriately

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Redemption#5873]
While we were fixing other WG things we noticed

**What is Happening:**
The graveyard spirit guides were never switching appropriately based on graveyard team control.

**What Should happen:**
Graveyard spirit guides should switch to approprate team control

Franca is already on this fix @GMZinius

**Comment by mfranca0009** [comment]
### Issues fixed
- [x] Spirit guides will now correctly switch during alliance, horde, or neutral control conditions for workshop and fortress. Neutral control for workshops means no spirit guide, no guards, and no flag on the workshop poles.
- [x] Spirit guides now default to the defender team during no wartime and battle is not started. (This was referenced within code, but it was never functioning properly).
- [x] Fixed an issue where if you died without the battle active in the Wintergrasp zone, you would release on top of your dead body.

**Comment by Echinaceax** [comment]
Confirmed fixed in PTR
