### ISSUE TITLE
[Zone] Wintergrasp - On server restart WG doesnt save Workshop caps infomation

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Redemption#5874]
**Whats happening** 
I noticed that when the server has a restart the workshops that were capped from the last match are not saved from the DB

This pissed off the Pvper last week coz 3 times the server did a restart to do a hotfix 

![image](https://user-images.githubusercontent.com/39439201/173844603-24769f6e-5183-4b6c-8bf6-683e02e0faf0.png)

**What should happen**
On server restart the workshops should be saved to the DB

**Comment by mfranca0009** [comment]
### Issues Fixed
- [x] Workshop capture information will be appropriately loaded once the server boots up after a restart.
- [x] Actual capture point linked to the workshop will appropriately sync to the loaded workshop capture information.
- [x] Workshop neutral control will now show up on the map, and will appropriately store this state to be loaded when the server starts up (if any workshops were in a neutral state).

**Note:** Workshop capture information will ONLY SAVE if Wintergrasp has ended successfully; this is when workshop capture world states are saved.

**Comment by Echinaceax** [comment]
Confirmed fixed in PTR 

 neutral control

![image](https://user-images.githubusercontent.com/39439201/177655325-ec725bf7-e927-4284-b93b-a7cf3a25aca7.png)


![neutral workshop and graveyard](https://user-images.githubusercontent.com/39439201/177655065-91e0ed83-6f4f-49a9-b38a-21c1ca8bb1e8.jpg)

 neutral control transition

https://i.gyazo.com/ae48da5d39d8abafbb8c7acfc5d824f3.mp4
