### ISSUE TITLE
[Zone / Wintergrasp] 'Leave Wintergrasp' UI button not working

### ISSUE THREAD

**Issue by mfranca0009** [WoWManiaUK/Redemption#5875]
**Links:**
N/A

**What is Happening:**
The `Leave Wintergrasp` UI button does not do anything.

**What Should happen:**
Should teleport the player out of Wintergrasp.

**Comment by mfranca0009** [comment]
Implemented and fixed, tested it myself, and works as expected.

Test Video: https://youtu.be/LpRFkwNrb_s

**Comment by Rushor** [comment]
testable once beeing comfirmed as to be fixed

**Comment by Rushor** [comment]
after next compile now
