### ISSUE TITLE
[Boss - Mechanic] Rotface 

### ISSUE THREAD

**Issue by svijetlo** [WoWManiaUK/Redemption#5876]
**Links:**
http://www.wow-mania.com/armory?npc=36627
http://www.wow-mania.com/armory?spell=69789
**What is Happening:**
During fight Ooze Flood will show as it should , but as soon player step in to puddle on ground it will be gone 

**What Should happen:**
Ooze Flood need to stay out until new one comes out 
P.S. will uplaod vid of bug

**Comment by wow-mania** [comment]
If this is not a regression it will be marked as "won't fix"

**Comment by svijetlo** [comment]
plase leave this for now so  proper fix is done so similar bug never again appear

**Comment by jeyrella** [comment]
This is not fixed, and is an obvious issue.

**Comment by svijetlo** [comment]
makes fight trivially easy if it is left like this ,

**Comment by wow-mania** [comment]
If it is not new it is not going to be fixed as new rules.

**Comment by jeyrella** [comment]
it *IS* new.

**Comment by wow-mania** [comment]
so it's new as it's been there for 7 years?

**Comment by mfranca0009** [comment]
Confirmed back to normal on PTR after reverting of another issue, live on next rebuild.

**Comment by Echinaceax** [comment]
https://i.gyazo.com/a5dbe669e32412b1ee077cfc7fd0828f.mp4
