### ISSUE TITLE
[Boss - Mechanic] Valithria Dreamwalker

### ISSUE THREAD

**Issue by svijetlo** [WoWManiaUK/Redemption#5877]
**Links:**
http://www.wow-mania.com/armory?npc=36789
http://www.wow-mania.com/armory?npc=37863
http://www.wow-mania.com/armory?spell=70588
**What is Happening:**
as it stand now During fight [Suppresser] do now show at all 
**What Should happen:**
During fight right after Gluttonous Abomination comes out there should be Suppresser coming out

**Comment by wow-mania** [comment]
If this is not a regression it will be marked as "won't fix"

**Comment by mfranca0009** [comment]
The issue will be corrected tomorrow morning after the server restart for live.
