### ISSUE TITLE
[Boss - Mechanic] Sindragosa

### ISSUE THREAD

**Issue by svijetlo** [WoWManiaUK/Redemption#5878]
**Links:**
http://www.wow-mania.com/armory?npc=37755
http://www.wow-mania.com/armory?spell=71049
**What is Happening:**
During the fight Blistering cold cast has WAY BIGGER range then it should hitting player that are 30+ yards away form boss (caster) 

**What Should happen:**
Range of Blistering cold should be 25 yards form center of the boss (caster)

**Comment by svijetlo** [comment]
p.s made this Critical prio as it makes fight impossible to do and you need to ask assist form Gm what put needless strain on GMs and not every time players do raid there is fast GM available to help

**Comment by mfranca0009** [comment]
Solution prepped, need assistance testing this tomorrow @svijetlo

**Comment by wow-mania** [comment]
If this is not a regression it will be marked as "won't fix"

**Comment by svijetlo** [comment]
![WoWScrnShot_070822_205556](https://user-images.githubusercontent.com/61908373/178054347-e590bd83-0a6d-4a77-83ee-636d6fb56074.jpg)
![WoWScrnShot_070822_205538](https://user-images.githubusercontent.com/61908373/178054362-43a116cc-ea8c-4e76-b916-7eaf2d600cbc.jpg)
![WoWScrnShot_070822_205557](https://user-images.githubusercontent.com/61908373/178054376-f3e27a20-ad7e-4f98-a2fa-5420cada9e5a.jpg)

**Comment by mfranca0009** [comment]
The issue will be corrected tomorrow morning after the server restart for live.
