### ISSUE TITLE
[Quest] The Emissary

### ISSUE THREAD

**Issue by filly75** [WoWManiaUK/Redemption#5879]
Quest https://www.wowhead.com/wotlk/quest=11626/the-emissary cannot be completed. After using the quest item https://www.wowhead.com/wotlk/item=35850/trident-of-nazjan npc evades and resets. Killing by GM doesnt complete quest either.

**Comment by Greywolf59** [comment]
I can confirm. Here is the video from NAXXRAMAS. https://gyazo.com/841c579da4ef160c2c807a08b6fb03c4
Also proper links for the things:
Quest: The Emissary https://wow-mania.com/armory/?quest=11626
Item: Trident of Naz'jan https://wow-mania.com/armory/?item=35850
NPC: Leviroth https://wow-mania.com/armory/?npc=26452
Tried many angles, many spots, tried attack immediately after using the trident and got evade anw. At the first hit the NPC moved up a bit in the water where it now stays.

**Comment by Echinaceax** [comment]
Confirmed back to normal after revert of another issue, live on next rebuild

![leviroth](https://user-images.githubusercontent.com/39439201/178153221-5ea90a97-a9cd-4aff-9bbc-50797061cc8e.jpg)
