### ISSUE TITLE
[Quest] Cruelty of the Kvaldir

### ISSUE THREAD

**Issue by Greywolf59** [WoWManiaUK/Redemption#5880]
**Links:**
Quest:
https://www.wowhead.com/wotlk/quest=12471/cruelty-of-the-kvaldir#comments
https://wow-mania.com/armory/?quest=12471
Trigger NPC:
Riplash Myrmidon https://wow-mania.com/armory/?npc=24576
Quest Giver:
Captured Tuskarr Prisoner https://wow-mania.com/armory/?npc=25636

**What is Happening:**
There is no Myrmidon, after a long wait he does not spawn either. Thsu the trigger for havign the quest avaialble for the takign is missing and Prisoner has no quest available.

**What Should happen:**
There should be a myrmidon fighting with the Prisoner and if you kill the myrmidon and save the Prisoner he will offer you this quest.

**Comment by jeyrella** [comment]
Has worked fine in the past.

**Comment by Greywolf59** [comment]
Well, this is Naxx realm and there is no spawn of him at all. Or it might be as with some other events that once done it won't start again until restart/crash of the server.

**Comment by jeyrella** [comment]
Appears that this is indeed the case, as it works perfectly in PTR.  Raise a GM ticket in game for help.  Thanks!
