### ISSUE TITLE
Assembling Group... (for specific dungeons) After an Xfaction group entered a blocked Dungeon from RHC que

### ISSUE THREAD

**Issue by robertgf1** [WoWManiaUK/Redemption#5881]
**Links:**

**What is Happening:**
After joining a xfaction group for The Nexus (2 alliance, 3 horde) i am now unable to get any group when queueing alone and for specific dungeons. There is none, not even myself, showing up in "Assembling Group..."
GM Aymelek tried many thing to solve this issue but nothing help

**What Should happen:**
An almost instant showing of atleast myself in Assembling Group.

![WoWScrnShot_070822_110203](https://user-images.githubusercontent.com/25205678/177964855-a48f6f7c-4eee-403c-8de2-8e13d6279251.jpg)
![WoWScrnShot_070822_112913](https://user-images.githubusercontent.com/25205678/177964902-f7d20185-7c6e-4f3c-810c-dc2cafbfa1f7.jpg)

Update: The Issue seems to have fixed itself.
The server restart that happened not long after this ticket was made might have been the thing that fixed my issue.

**Comment by Echinaceax** [comment]
Reproduced this issue for the GM, waiting on Dev feedback 

**Reproduce** 

1. Make Xfraction group (2 ally 3 horde)
2. Join RHC que 
3. When you get one of the blocked dungeons from the blocked list then is bugs
4. Disband group and que specific and you are bugged from the faction that wasnt the leaders faction 

I was Ally leader and the other Ally (no bug)

![image](https://user-images.githubusercontent.com/39439201/178721106-0769c3d2-6bb1-4d06-8cb7-3329f13dd32f.png)
![image](https://user-images.githubusercontent.com/39439201/178721510-c495b5d8-be91-4ad0-91f6-bd2733be7c99.png)



Pheonix 3 hordes all have bug 

![image](https://user-images.githubusercontent.com/39439201/178721325-e3cbe9b0-f22a-4801-90f7-c1b29ed9629d.png)
![image](https://user-images.githubusercontent.com/39439201/178721375-b624eafa-83fc-4e59-b3c9-0405fe54cb9c.png)
![image](https://user-images.githubusercontent.com/39439201/178721413-ce84eb7b-419a-48de-83ca-279f16a56086.png)

**Comment by GMZinius** [comment]
Reopening at Janitor request @Rushor

**Comment by Rushor** [comment]
I think Keader can handle this one better :)
