### ISSUE TITLE
[NPC] Bittertide Hydra evades - Sholazar Basin - 28003

### ISSUE THREAD

**Issue by jeyrella** [WoWManiaUK/Redemption#5882]
**Links:**
NPC ID 28003

**What is Happening:**
Bittertide Hydra evades and reset (all of them that are found in the lake).  This is important since it means Quest 12683 "Burning to Help" cannot be completed.

https://gyazo.com/1852ce22ad904934b27e86ec8853be7c

NPC currently selected by player:
DB GUID: 104757, current GUID: 4073.
Faction: 14.
npcFlags: 0.
Entry: 28003.
DisplayID: 2837 (Native: 2837).
Level: 76.
EquipmentId: 0 (Original: 0).
Health (base): 11001. (max): 11001. (current): 11001.
InhabitType: 3
Unit Flags: 0
Unit Flags 2: 2048.
Dynamic Flags: 0.
Faction Template: 14.
SpawnTime: Full:5m Remaining:0s
Loot: 28003 Pickpocket: 0 Skinning: 70211
InstanceID: 0
Phasemask: 1
Armor: 8503
Position: 6143.648926 5242.813477 -125.096832.
AIName: SmartAI ScriptName: 
Flags Extra: 0
MechanicImmuneMask: 0

**What Should happen:**

The Hydras should not evade.

**Comment by Echinaceax** [comment]
Confirmed back to normal after revert of another issue, live on next rebuild

![hydra](https://user-images.githubusercontent.com/39439201/178153258-eaccca6c-22b2-495f-918b-b19bbbf2d141.jpg)
