### ISSUE TITLE
Evasion.

### ISSUE THREAD

**Issue by Mwollfiez** [WoWManiaUK/Redemption#5884]
Rogue's Evasion ability doesnt work as it should when it comes to the 25% Range hits to be dodged, by ranged hits its physcial range hits which mostly comes from hunters it does not dodge at all as it should, i tested it in duels many times None of all the tests single dodge happend.

**Comment by GMMetaxa** [comment]
https://github.com/WoWManiaUK/Redemption/wiki/How-to-Properly-Report-an-Issue

**Comment by Rushor** [comment]
please more information, recount data, retail sources, else we must close the report due to too less information

**Comment by Rushor** [comment]
reopened once more information is provided by reporter
