### ISSUE TITLE
Judgement of Justice

### ISSUE THREAD

**Issue by Mwollfiez** [WoWManiaUK/Redemption#5885]
Judgement of Justice for paladins is not applying slow affect on the target as it should the judgement be applied but 0 slow effect is applied.

**Comment by jeyrella** [comment]
It says right on the spell that it does not apply a slowing effect.
Please could you expand on exactly what you believe is the issue here.

**Comment by svijetlo** [comment]
spell skill it self need to limit speed  to default, if above 100% running speed, so if speed i grater the run speed of character default in game , spell will set it back , it will not slow down more,

**Comment by GMMetaxa** [comment]
https://github.com/WoWManiaUK/Redemption/wiki/How-to-Properly-Report-an-Issue

**Comment by wow-mania** [comment]
if confirmed assign to Keader please

**Comment by jeyrella** [comment]
No further info received in order to reproduce.
