### ISSUE TITLE
[Item] Awakening Rod not working properly

### ISSUE THREAD

**Issue by Pjotr-V** [WoWManiaUK/Redemption#5886]
Quest: Sleeping Giants
Location: The Waking Halls under Gjalerbron in Howling Fjord

**What is Happening:**
The Awakening Rod starts channeling a green ray towards the targeted Dormant Vrykul, and then finishes without effect.

**What Should happen:**
The Dormant Vrykul should die after channeling.

**Comment by Greywolf59** [comment]
It is not that it does not work at all, but it works only very infrequently and on only some of the mobs. Done this quest about a month ago. Tried multiple times on some and no effect, others died on the 1st try.

**Comment by Rushor** [comment]
can you try to find a reproduce way?

**Comment by Rushor** [comment]
ty!

**Comment by Pjotr-V** [comment]
Partial report on working/not working mobs after retrying the q today:
Inside the Halls, go left. Counterclockwise around the rectangular room, the first 2 mobs worked fine for me, but the 3rd and 4th did not. Then on to the far circular room, 1st and 2nd mob going counterclockwise worked.
In the right branch from the beginning of the Halls, the 1st mob (again going counterclockwise) in the rectangular room  worked, so I got my five targets. :)
So, specifically, this time around I found 2 mobs where it did not work. I don't recall which ones I tried earlier.

**Comment by Echinaceax** [comment]
Quest item https://www.wow-mania.com/armory/?item=34083
Npc https://www.wow-mania.com/armory/?npc=24669

Confirmed bug
Quest item is bugged, sometimes its failing on the first time
you see in my videos i have to use the quest item twice on the same NPC 

1st fail https://i.gyazo.com/5a354d93579daf39518a0a9acbd0da5f.mp4
2nd fail https://i.gyazo.com/0b74d7324cea2a3102c774740e099c88.mp4 you can see on the 3rd NPC i have to use it twice

**Comment by Keader** [comment]
fixed

**Comment by Echinaceax** [comment]
not quiet @Keader 
now its give double quest credit
