### ISSUE TITLE
[Spell] Internal Cooldown on Lightweave Embroidery GCD

### ISSUE THREAD

**Issue by Retartedgoat** [WoWManiaUK/Redemption#5888]
**Links:**

Lightweave Embroidery test
https://user-images.githubusercontent.com/109674349/180001117-4f656620-cda3-4c0e-8eb7-3f2807c29d13.mp4

**What is Happening:**

Lightweave Embroidery tailoring back enchant is activating when its on its internal cooldown.  To test it, I equipped the back from my inventory, the back went on it 30 sec internal cooldown. (I'm tracking internal cooldown with weak aura.) I cast few spell on training dummies and the back enchant Lightweave Embroidery proc'd despite it being on internal cooldown. 

As for Deathbringer's Will (DBW), I was running ICC and noticed that I had 10 sec left on DBW internal cd, I swapped trinket and DBW went on cd for like 1:15 sec. (it should have been 30 sec)
Later, I tried to test DBW on dummy, DBW internal cd seemed fine, it went back to 30 sec internal cd when I swapped trinket from slot 13 to 14. But DBW was still not procing for an additional 1:15 sec. Tested it 8 additional times but DBW just wouldn't proc despite the trinket not being on cooldown. Found it extremely odd that DBW was not procing despite having 53.01% crit and attacking 3 dummies.  

My theory is that when u swap trinket (DBW) and internal cd shows 30 sec, its not accurate. DBW is still on cooldown for additional 1:15 sec after that 30 sec is up. I thought I had extremely bad RNG so I tested it 8 times on dummies and all of those test DBW didn't proc for a bit over 1:15 sec  after its 30 sec internal cooldown was over.  Please double check on this!

As for Global Cooldown Issue 

I'm currently using this macro for my mage 

#showtooltip Mirror Image
/cast Mirror Image
/cast Berserking
/use 10

Berserking and /use 10 which is Engineering glove **does not** use GCD so when I press that macro it should cast all 3 skill in one GCD since Mirror Image is the only skill that has uses a GCD . But what ends up happening when I press the skill is, uses 1 GCD for berserking and gloves despite not having GCD and then I have to press the macro again which finally casts Mirror Image.  For some odd reason using that macro is taking 2 GCD. despite only Mirror Image having a GCD

**Update on GCD on that Macro**

I switch the macro to

#showtooltip Mirror Image
/cast Berserking
/use 10
/cast Mirror Image

and now it only uses 1 GCD for all 3 skill

**What Should happen:**

I believe the internal cooldown when you equip a new trinket or swap is always 30 seconds.
So normally when equip a trinket or  swap Trinket from slot 13 and slot 14 your trinket should go on cooldown for 30 sec. Even if there is 10 sec left on the trinket's internal cd and you happen to swap it, the internal cooldown should go back to 30 sec. But for Deathbringer Will trinket, its setting the internal cd its full duration of 30 sec + 1:15sec

**Comment by svijetlo** [comment]
**Lightweave Embroidery tailoring will proc if it should be on ICD, on equip enchant has no icd of 30 sec**
for DBW it is how it is as, trinket resets back to full ICD if one unequip and equip it back, -this will stay AS IT IS
for GCD to me it works fine how ever i put macro only one gcd is triggered

**Comment by Keader** [comment]
fixed
