### ISSUE TITLE
[NPC] Classic (in the wild) silver elite mobs dont drop green/blue specific gear items.

### ISSUE THREAD

**Issue by Feloxis94** [WoWManiaUK/Redemption#5889]
**Links:**

**What is Happening:*
I have been playing on Wow-Mania (redemption) since 2017 and for some reason everytime i happened to kill in the wild an silver elite mob on either Kalimdor or the Eastern Kingdoms (except in dungeons), they never dropped any gear specific item like armor, weapons etc of any kind. it is always an empty loot or just some random reagents, trash items or coins. It is odd because i have never encounter this problem with Outland and Northrend silver elite mobs, their loot system works fine.
**What Should happen:**
Every Silver elite mobs in classic should be dropping one green/blue specific gear item depending on the mob you kill that + coins and other reagents items depending on the mob. 
  
PS: i have 8 characters both Horde ans Alliance to lvl 80 and i have always encounter this problem with all of them during their progressions.

**Comment by svijetlo** [comment]
any proof form back in days, as in "vanilla" world rare and elite mobs did not have drops unless it was quest related or profession and wo it there is no drop, only for for glory and role play of killing or to get as rare pet on hunter , also to add to all of it even if drop did exist as it was vanilla and drop rate would be 0.01% 
so wo more data sadly it will not be change done to it

**Comment by fvicaria4drest** [comment]
Please add a link to the creatures from the armoury, I doubt that it is a real issue but we can check.
