### ISSUE TITLE
[Core] Skinning in dungeons

### ISSUE THREAD

**Issue by TheSale** [WoWManiaUK/Redemption#589]
Since yesterday I started to experience issue of not be able to skinning any mobs in dungeons
I have noticed that because 3 days ago I had to fight over skinning in The Culling of Stratholme and I got 5 icy dragonscale from 1 run and 1 arctic fur, but yesterday I could not skin any mob in same dungeon so not even today.... I sad alright lets pass that maybe something is wrong but after that I go in Violet hold where is filled with dragonkins and even boss was beast dog... and end boss was dragon.... nothing was skinnable....

Usually I would not care about it, but I had 2 gathering proffesions, and I deleted one so I can learn engineering and I dumped herbalism coz I was lazy to run around to farm, and skinning was free farm in dungeons... now is useless.... now I have to delete skinning to learn herbalism from 0....

**Comment by Brunnr** [comment]
I can confirm that most beasts and dragonkin in Northrend instances are no longer flagged skinnable, but I have seen this for a couple months. Dragonkin in The Nexus, or worgs in UK for example should be skinnable and previously they were, but no longer. On mouseover the popup description no longer shows 'skinnable' like before. Mobs outside instances, or in older instances are tagged skinnable, and can be skinned. For example the dragonkin and wolves in Blackrock Spire can both still be skinned.

**Comment by fvicaria** [comment]
Send me the wowhead.com link for the mobs please so I can test and fix.

**Comment by TheSale** [comment]
I dont know if you want me to link you every mob from every dungeon that should be skinnable, but for start here you go http://www.wowhead.com/the-nexus#npcs:0+7+1
arange NPC by type and every BEAST and DRAGONKIN should be skinnable
same for this one too http://www.wowhead.com/the-violet-hold#npcs:0+7+1
so as here http://www.wowhead.com/the-culling-of-stratholme#npcs:0+7+1
I could keep you linking every dungeon if it will help
because in every dungeon have some mobs should be skinnable, but they are not
there are also some undead beast like NPC that also should be skinnable but for those I cna check and link you each

**Comment by fvicaria** [comment]
I would like to know the exact mobs.

**Comment by Brunnr** [comment]
The Nexus mobs you can skin: http://www.wowhead.com/npcs?filter=6:10;4265:1;0:0
Utgarde Keep: http://www.wowhead.com/npcs?filter=6:10;206:1;0:0
Utgarde Pinnacle is just Bloodthirsty Tundra Wolf: http://www.wowhead.com/npc=26672
The Violet Hold: http://www.wowhead.com/npcs?filter=6:10;4415:1;0:0
Gundrak: http://www.wowhead.com/npcs?filter=6:10;4416:1;0:0
Old Kingdom: http://www.wowhead.com/npcs?filter=6:10;4494:1;0:0
Azjol-Nerub: http://www.wowhead.com/npcs?filter=6:10;4494:1;0:0
The Oculus: http://www.wowhead.com/npcs?filter=6:10;4228:1;0:0

Thanks for looking into it!

**Comment by TheSale** [comment]
gj Brunnr, I would had hard time of linking every mob :D

**Comment by fvicaria** [comment]
Should be fixed by Wednesday after update. Thanks for the help.
