### ISSUE TITLE
[Spell/Debuff] Touch of Zanzil

### ISSUE THREAD

**Issue by lowbg** [WoWManiaUK/Redemption#5890]
**Links:**
https://www.wow-mania.com/armory/?item=6453
https://www.wow-mania.com/armory/?item=8432
https://www.wow-mania.com/armory/?spell=9991

**What is Happening:**
After applying spell 9991(Touch of zanzul) i must be able to cure it with anti-antivenom(6453) from First aid,  or with the item from quest (8432). Which is curing that debuff .Unfortunately only one  working is the quest one ! (first aid one is bugged).Also can be cured with cure posions spells on any classes providing that.

**What Should happen:**
The Debuff should be able to be cured with the first Curing item//Anti-venom(6453).

**Comment by Airin258** [comment]
Confirmed to not be cured with any sort of antivenom provided by First aid skill.
![image](https://user-images.githubusercontent.com/96421124/180659056-ab1d71a3-fc85-4edc-b4a0-cdbeb6183b6c.png)

**Comment by jeyrella** [comment]
This is not a bug. The whole point is you need to use the quest item.

**Comment by Keader** [comment]
it's is a ISSUE, https://www.wow-mania.com/armory/?item=6453 has no effect right now.

**Comment by Airin258** [comment]
I will re-explain it a bit better, to avoid misunderstandings.
On retail this quest includes obtaining debuff with same name (poison, 7 day duration, unable to go stealth for whole duration) that was being able to be dispeled by:
Quest item that you get when you do next quest
Poison dispelling skills (example: cure/abolish poison for dudus)
Anti-venoms, crafted by first aid.

While first 2 work just fine, none of anti-venoms was able to cure it.

**Comment by Keader** [comment]
fixed
