### ISSUE TITLE
Writ of Safe Passage (bug)

### ISSUE THREAD

**Issue by thomocterly** [WoWManiaUK/Redemption#5891]
**Links:**
Hello!

**What is Happening:**
The quest, "Writ of Safe Passage" in the Western Plaguelands seems to be bugged. Myself and another player can't find the NPC, Field Marshal Chambers, necessary to complete it.

**What Should happen:**
I think that what is supposed to happen is, a player accepts the quest, the NPC Field Marshal Chambers spawns, and an escort quest begins. This quest should involve the NPC chambers, a laden mule, and the player(s). However, Chambers isn't spawning, yet multiple mules will. there are 8 mules and no Chambers when I went to Light's Hope Chapel..

**Comment by jeyrella** [comment]
Nope, the even only spawns twice a day.  Infamous quest in "vanilla" :)
https://www.wowhead.com/quest=9165/writ-of-safe-passage

**Comment by jeyrella** [comment]
(If you're used to as it is today in retail, this behaviour was changed in Cataclysm.)
