### ISSUE TITLE
MOBILE BROWSER LOGIN FAILS

### ISSUE THREAD

**Issue by Vortex2922** [WoWManiaUK/Redemption#5893]
**Links:**
https://www.wow-mania.com/login

**What is Happening:**
After writting username and password and proving that you are not a robot, you click login but nothing happens.

Mobile: Apple IPhone 6s Plus
Version: IOS 15.6
BROWSER: Yandex, Safari (both didnt work)
Tried PC version of website but did not solved the problem.

**What Should happen:**
Login to account and redirecting to account.

**Comment by fvicaria4drest** [comment]
Probably some ad-blocker or some other hidden gem from iPhone.
Refresh and the page close browser, the usual thing.
However this repo is only for in-game issues.
