### ISSUE TITLE
[Quest] Plundering the Plunderers - Quest item given from wrong NPC ID

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Redemption#5894]
**Links:**
Quest https://www.wow-mania.com/armory/?quest=2381
NPC https://www.wow-mania.com/armory/?npc=7167 
NPC 2 https://www.wow-mania.com/armory/?npc=7168
Quest item drop https://www.wow-mania.com/armory/?item=7968

video for reference https://www.youtube.com/watch?v=HeJuLVO76Lo have to get your lockpicking up (i did it to 54)

I was asked to check this Rogue quest out 

**What is Happening:**

Test 1
checked the correct way of doing this quest
Opened the box then using the quest item https://www.wow-mania.com/armory/?item=7970 after using the quest item Polly goes small (as it should) `but no loot of the quest item drop and so no quest credit`
https://i.gyazo.com/098ca950fd30bfd52ee6feb1a8c9e6e0.mp4

test 2
Did the same but without using the quest item, `loot and quest complete was given`
https://i.gyazo.com/e32cee133125b117e2bf588cec93e0fe.mp4

Also noticed that the bird can be summoned continuously `coz of the box constantly being clickable`
https://i.gyazo.com/dc66f490deab943894dc1447c3cfdbd3.mp4

**What Should happen:**

- [ ] Quest item loot should be from `npc 7168 not 7167`
- [ ] Box should not allow multiple spawns once NPC 7167 is spawned
- [ ] Box should stop twinkling after NPC is spawned

**Comment by Rushor** [comment]
Will check, all points can be fixed except the sparkeling (core and Client side reason) but i can despawn the Box once used for 5 Minutes. I think that would be fair

**Comment by Rushor** [comment]
- quest item assigned to correct creature
- gossips of creature Wrenix's Gizmotronic Apparatus fixed
- extra pollys will despawn if there is more than one in the room
- box will despawn for 300 sec once beeing opened

**Comment by Echinaceax** [comment]
- [ ] quest item assigned to correct creature
- [ ] gossips of creature Wrenix's Gizmotronic Apparatus fixed
- [ ] extra pollys will despawn if there is more than one in the room
- [ ] box will despawn for 300 sec once beeing opened
