### ISSUE TITLE
[Item] Bauble of True Blood is scaling with spell power.

### ISSUE THREAD

**Issue by Hajzlopuc** [WoWManiaUK/Redemption#5895]
**Links:**

https://www.wow-mania.com/armory/?item=50726
https://www.wow-mania.com/armory/?item=50354

https://www.wow-mania.com/armory/?spell=71607

**What is Happening:**

Bauble heal is scaling with spell power.

https://puu.sh/JdWih/3be26b7f34.mp4
https://puu.sh/JdWie/405ed667e4.mp4

**What Should happen:**

Bauble heal should not scale with anything other than crit chance. Should be able to crit for 150% up to 12900. I've seen some disgusting 17k crits in game. EDIT: finally managed to get crit by myself https://puu.sh/JdWxg/c6faa9ef94.jpg. 
If this one had crit, itd be **19300** - https://puu.sh/JdWDy/8c66e645fe.jpg 

https://www.wowhead.com/wotlk/item=50354/bauble-of-true-blood#comments
https://www.wowhead.com/wotlk/item=50726/bauble-of-true-blood#comments
https://wowwiki-archive.fandom.com/wiki/Bauble_of_True_Blood

**Comment by Rushor** [comment]
// this one is here because we have no SP bonus for dmgclass none spell
// but this one should since it's DBC data, it won't crit because it already has can't crit attr

this is the comment on core for the spell

**Comment by Echinaceax** [comment]
added info https://wowwiki-archive.fandom.com/wiki/Bauble_of_True_Blood

![image](https://user-images.githubusercontent.com/39439201/182609287-9c6ef5b1-55f0-4d87-8715-3f5deb14e945.png)

**Comment by Keader** [comment]
fixed
