### ISSUE TITLE
[Item] Lesser Darkmoon Prize - Sometimes empty

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Redemption#5896]
**Links:**
item https://www.wow-mania.com/armory/?item=19297
12 Tickets - Lesser Darkmoon Prize https://www.wow-mania.com/armory/?quest=7932

![image](https://user-images.githubusercontent.com/39439201/182152858-578d9452-6b4b-406a-a56b-690e46db8938.png)

**What is Happening:**
Lesser Darkmoon Prize when clicked was empty
https://i.gyazo.com/5c7d40918598fdfad3e9510b864f01e6.mp4

**What Should happen:**

"Guaranteed to contain an item of value!"

Should never be empty

**Comment by Rushor** [comment]
should now always contain an item at least.

**Comment by Rushor** [comment]
now fix is applied on ptr

**Comment by Echinaceax** [comment]
Fixed on PTR 
https://i.gyazo.com/b22d580dc58b81604e8789e8491274c5.mp4
