### ISSUE TITLE
Gunship - Simultaneously getting into cannon , one player becomes unmovable

### ISSUE THREAD

**Issue by Retartedgoat** [WoWManiaUK/Redemption#5897]
**Links:**

**What is Happening:**

When two people try  to get on cannon simultaneously 1 person get frozen and unable to move at all. Even if other person get off cannon, the stuck person is unable to get in cannon. Has happened to me about 3 times in the past few weeks.

/reload did not work
Raid member were able to summon me at Deathbringer Saurfang.
I was able to move after summon.
But on one of the summon I was still stuck in place and unable to move freely.
A relog did fix that tho.

Also, Mages are unable to blink during Gunship. Not sure if intentional or not.

**What Should happen:**

**Comment by jeyrella** [comment]
Thanks for the report.  This is a core limitation and as such cannot be fixed at this time.
