### ISSUE TITLE
[Boss] Sindrigosa door bugged after player left raid 

### ISSUE THREAD

**Issue by Bartok14** [WoWManiaUK/Redemption#5899]
**Links:**
I don't have a link unfortunately because I didn't think to take a screen shot.

**What is Happening:**
We made it past the gauntlet to Sindrigosa. Cleared the mobs that were there. Before we finished the two dragons, we had someone leave the raid. We replaced them. Then we killed the two dragons and went through the door back to the gauntlet. I don't know what bugged but as soon as Sindrigosa came down she closed the door but then did not reset. So we were basically stuck on the other side of the door and it would not open. We left the raid to try and reset it but it kept saying encounter in progress. So she bugged out and the door would not open afterwards.

**What Should happen:**
I assume what should happen is that she just resets if no one else is there to kill. I'm assuming there was a bug that caused her to not reset that was caused by the player leaving the raid group. I don't know what to do about this really except maybe having her reset the encounter after her enrage timer + 2 minutes if she hasn't killed anyone after the INITIAL encounter starts. I don't know if you can reproduce this I just thought it was worth reporting since the entire encounter was bugged for over an hour and no GM's were online to fix it.

**Comment by jeyrella** [comment]
Thanks for your report. Very Edge case scenario, very difficult to reproduce. As you did, the way forward on this one is to get assistance from a GM.
