### ISSUE TITLE
[NPC] Prince Keleseth

### ISSUE THREAD

**Issue by Brunnr** [WoWManiaUK/Redemption#590]
Using the WoW-Mania client, with the November 2016 patch on Win10 64 bit machine. Running Utgarde Keep in heroic mode.

Keleseth, the first boss in UK, has 4 mobs sitting in the same room with him. Previously you could a aggro the mobs furthest from the boss as he patrolled, and all 4 would attack without the boss pulling. Now, regardless of the boss location or which mob is tagged, Keleseth also attacks. While it doesn't break the encounter, just makes it tougher, it is a change in mechanics (perhaps intended for challenge?)

http://www.wowhead.com/npc=37972/prince-keleseth

**Comment by fvicaria** [comment]
You still. I have just done it with my Mage and got the 4 mobs without aggroing Keleseth. 
Make sure you aggro the mobs when Keleseth is half-way along its path.
