### ISSUE TITLE
Sons of Hodir, quest to speak to the king jokkum.

### ISSUE THREAD

**Issue by SaurianDraeni** [WoWManiaUK/Redemption#5900]
**Links:**

**What is Happening:**
Quest Krolmir, hammer of storms requires me to speak to the king. The name plates are green of all the Sons of Hodir residents but they are hostile so clicking on any of them starts autoattack.

Also I have quest forging ahead to hand in to Norjmeld but again the NPC is hostile with a green name plate. 
Same with the flight master, hostile with a green nameplate

**What Should happen:**

**Comment by jeyrella** [comment]
Thanks for your report, however this is a player option.  Click on Reputation tab, untick "At War" with Sons of Hodir.
