### ISSUE TITLE
[Item Enchantment] Heirloom items item level.

### ISSUE THREAD

**Issue by amikot** [WoWManiaUK/Redemption#5901]
When trying to enchant Heirloom item with any enchant with required item level I'm getting error: Target is too low level. 

I think this must be error, as Heirlooms are having dynamic item level which is growing according to level of the player.
Of course enchants should be reset when someone with lower level would put that item on.

**Comment by jeyrella** [comment]
No, this is because the enchantment you are using has a minimum item level requirement.  Heirlooms do not qualify for this.
You *can* apply enchants, but **only** enchants that do not specify any minimum level requirements.
