### ISSUE TITLE
AQ40 Twins Keeping players in combat

### ISSUE THREAD

**Issue by womptista** [WoWManiaUK/Redemption#5902]
https://www.wow-mania.com/armory/?quests=3.3428

(I do not have video prof as I did not anticipate getting to the twins.)

The Twins stay in combat with raiders even after raiders death. The twins will keep them in combat even after a manual clear of combat.

Combat should be dropped upon raiders death.

**Comment by Rushor** [comment]
Can you reproduce this always? Please check it with a different toon in a different raid one more time and let me know if you are in combat there after death aswell a second time.

Thank you!

**Comment by Greywolf59** [comment]
I was in that raid and I can confirm. It was on Naxx realm. But iirc it was the issue on Redemption too, I kinda remember the same problem years back. You wipe, twins stay at the spot they were when the raid wiped, they don't return to their platforms. It wqlas wipe after enrage timer hit. I saw one of the twins stayed enraged when I was releasing spirit. You can normally run in back to the raid but as soon as you enter you get into combat and you gotta run whole way back on foot. .cl does not help (I don't remember if it says it can't be used in combat or if it works but you get back to combat right after). When you are nearing the twins' chamber, the Twins come running towards you through the entry corridor.

**Comment by Rushor** [comment]
once ptr is rebuilded, they should stop combat and be at the homeposition on reset

**Comment by GMZinius** [comment]
Fixed on PTR
On wipe twins reset to correct positions
No incombat 

![image](https://user-images.githubusercontent.com/108176634/186269112-80be7db3-77f8-4d43-9ecc-eab043b7f011.png)
![image](https://user-images.githubusercontent.com/108176634/186269190-ada4cfa8-f6d7-469a-95d1-4a4863453e8d.png)
