### ISSUE TITLE
Emergency Protocol: Section 8.2, Paragraph C

### ISSUE THREAD

**Issue by womptista** [WoWManiaUK/Redemption#5903]
**Links:**
(Realm is Naxxarams)
(Link to Quest) https://www.wow-mania.com/armory/?quest=11795
(Link to Video) https://drive.google.com/file/d/1k0-g7ESB7stKyoTJwJb7Fh93rrzxS7u7/view?usp=sharing

**What is Happening:**
Downed Pilot at location 64.1 : 35.83 is targetable but not clickable.

**What Should happen:**
All downed pilots should have an on use dialogue.

**Comment by GMZinius** [comment]
Thank you for reporting @womptista 
We will look into this

**Comment by GMZinius** [comment]
From the quest discription
 `Recover 6 Fizzcrank Pilot Insignia from the bodies of Fizzcrank Recon Pilots and return them to Iggy "Tailspin"` 

Quest npc https://www.wow-mania.com/armory/?npc=25841
Quest item https://www.wow-mania.com/armory/?item=35126


The npc at the coods you gave @womptista is a Crashed recon pilot for a different quest https://www.wow-mania.com/armory/?npc=25984 

Please confirm ?

**Comment by fvicaria** [comment]
Pretty sure this works

**Comment by GMZinius** [comment]
> Pretty sure this works

Correct, checked with no issue
