### ISSUE TITLE
Spawned Mob in Boulder (69.21, 34.86)

### ISSUE THREAD

**Issue by womptista** [WoWManiaUK/Redemption#5904]
**Links:**
(Link to NPC) https://www.wow-mania.com/armory/?npc=1018
![WoWScrnShot_082122_143058](https://user-images.githubusercontent.com/66838614/185805801-b577db20-d471-4d53-a5f7-1d427e68eefc.jpg)

**What is Happening:**
NPC/Mob is spawning inside boulder. (It can still be attacked but it can not attack back)

**What Should happen:**
The NPC/Mob should not spawn inside a boulder

**Comment by GMZinius** [comment]
Not the same issue on PTR 
Can you make and ingame ticket and show a GM @womptista 
thank you

**Comment by Rushor** [comment]
.go c 9981

mobed it a bit to a dofferent place

active after restart

**Comment by GMZinius** [comment]
confirmed fixed, on PTR, fix on live with next live update

![image](https://user-images.githubusercontent.com/108176634/185909692-c4b9d62d-1d00-483e-b948-14d3f9debef3.png)
