### ISSUE TITLE
[NPC] Ymirheim Chosen Warrior - HP issue

### ISSUE THREAD

**Issue by womptista** [WoWManiaUK/Redemption#5905]
**Links:**
[Link to quest in armory] https://www.wow-mania.com/armory/?quest=13336

[Image of location of mobs]
![IceCrown](https://user-images.githubusercontent.com/66838614/186418643-a8ff4d43-ae82-4976-ab19-5c7cc43b4e43.png)

**What is Happening:**
Some mobs are not attackable even after targeting them. They are constant evade. It is random on mobs not always static on mobs.

**What Should happen:**
The mobs should not evade every attack. They should be able to be attacked.

**Comment by Rushor** [comment]
Is this happening always?

**Comment by womptista** [comment]
Not on every Mob.  If that is what you are asking.

**Comment by GMZinius** [comment]
With random issues like this it is hard to replicate 

Tested on over 20 mobs with (Spriest) I didnt get one of them to evade any of my attacks

**Info** 
Spell used to tag the mob that evaded
If it happens again can you screenshot or video so Dev's have a start point 

Will close this for now until it happens again @womptista 

Thank you for reporting

**Comment by Rushor** [comment]
Maybe they got bugged by a different Player that engaged but not killed them before

**Comment by GMZinius** [comment]
> Maybe they got bugged by a different Player that engaged but not killed them before

Might have found the issue for you, Ive PM you my findings

**Comment by Rushor** [comment]
the proc for the heal spell will now be casted less often and the creatures should be killable more easy now.

**Comment by GMZinius** [comment]
Bloodthirst no longer gets continueously applied as it did,  Ymirheim Chosen Warrior can now be killed
Fixed in PTR, fixed on Live with next update
