### ISSUE TITLE
enha  [Shamanistic Rage] 

### ISSUE THREAD

**Issue by alexinhogr** [WoWManiaUK/Redemption#5906]
**Links:**

**What is Happening:**
 Shamanistic Rage spell sometimes i dont take mana back  or i take to little in raids and dugeons

**What Should happen:**

**Comment by GMZinius** [comment]
Thank you for reporting @alexinhogr 
Please read https://github.com/WoWManiaUK/Redemption/wiki/How-to-Properly-Report-an-Issue how to report an issue

with links to spell

**Comment by alexinhogr** [comment]
i dont say need to give me 100% , sometimes give zero (many times give 0)

**Comment by GMZinius** [comment]
> i dont say need to give me 100% , sometimes give zero (many times give 0)

More proof needed please from a reliable source
