### ISSUE TITLE
[ITEM]Magnificent flying Carpet

### ISSUE THREAD

**Issue by womptista** [WoWManiaUK/Redemption#5908]
**Links:**
[Link to Item on Armory]
https://www.wow-mania.com/armory/?item=44558
[Link To Video {Google Drive)]
https://drive.google.com/file/d/1ushVolsy8c6DeaobOsJdtVqqDz9UsYbw/view?usp=sharing
[Link To Video (youtube)]
https://youtu.be/AFxudkrrgrc

**What is Happening:**
This mount can not be used in Northrend. Get error when trying to use it; that the item can not be used.
The mount can be used in Outland

**What Should happen:**
The mount should be able to be used in Northrend as well.

**SIDE NOTE**
I have re-logged 2 times
I have cleared cache
I am using the launcher supplied by wow-mania
I have cold weather flying
I have riding skill 300
I have Tailoring 450

**Comment by GMZinius** [comment]
Thank you for you're report @womptista 

Tested and working fine, both on PTR and Live 
Please make and ingame ticket for a GM to check you have all requirements

update this report if and when you have solved this with a GM

**Comment by GMZinius** [comment]
Update For future reference

Magnificent flying Carpet requires Cold weather flying to use this in Northrend
