### ISSUE TITLE
[NPC] Valhalas Vargul - Some of these should be in Lay down position

### ISSUE THREAD

**Issue by womptista** [WoWManiaUK/Redemption#5909]
**Links:**
Naxx Server
Link to quest on the armor
https://www.wow-mania.com/armory/?quest=13042

**What is Happening:**
There are many undead guards surrounding him and there is not suppose to be
![WoWScrnShot_090722_132341](https://user-images.githubusercontent.com/66838614/188941459-8cc63085-9248-477d-b963-e39c8af80017.jpg)

**What Should happen:**
all The undead guards should not be there.

**Comment by fvicaria** [comment]
Unless you come up with evidence of that this will me marked as-is.

**Comment by Rushor** [comment]
If compared with old retail there are no guards https://youtu.be/WIQmF4YHqoI?t=84 but best would be a video from 2010 - there must be a reason why the npcs where spawned there.

If i see it correct in multiple videos those npcs are spawned as "dead" bodies, just being visual and not attackable. there have been multiple issues like that before already in the past years

**Comment by Rushor** [comment]
okay they should just lay on ground and not be attackable as seen in multiple videos https://youtu.be/bak6KZoPa6U?t=85
