### ISSUE TITLE
[NPC] Ingvar the Plunderer

### ISSUE THREAD

**Issue by Brunnr** [WoWManiaUK/Redemption#591]
Using the WoW-Mania client, with the November 2016 patch on Win10 64 bit machine. Running Utgarde Keep in heroic mode.

When killing Ingvar in phase 1, he will usually reset if the kill is caused by a direct attack, but will spawn in undead mode for phase 2 if the death is caused by damage over time. Just wanted to report that this still occurs using the latest client update, which was noted as fixing the issue.

**Comment by fvicaria** [comment]
http://www.wowhead.com/npc=23954/ingvar-the-plunderer

**Comment by fvicaria** [comment]
Also related with players doing way more damage than originally intended.

**Comment by Brunnr** [comment]
For comparison's sake, the group that normally runs this does pretty average damage, maybe 12000 DPS for the entire party. Next time will go slower to see if that helps. If I can help any in doing test runs and can include recount screen shots of each attempt, just let me know.

**Comment by fvicaria** [comment]
The fix should be in dev today.
