### ISSUE TITLE
[NPC] (Nergeld) Bottom Halls of Horros

### ISSUE THREAD

**Issue by womptista** [WoWManiaUK/Redemption#5910]
**Links:**
Link to NPC on armory
Naxx Server
Nergeld
https://www.wow-mania.com/armory/?npc=30403

**What is Happening:**
The mob can be attacked and puts me into combat but never attacks back
![WoWScrnShot_090722_133142](https://user-images.githubusercontent.com/66838614/188942841-8fb4a3f8-ad1c-4046-9236-6c3bcc86fe36.jpg)

**What Should happen:**
NPC should fight back

**Comment by GMZinius** [comment]
Thank you for the report @womptista 

Yes I also can melee attack him (with check on this part)


I see from your Screenshot that you have looted the quest https://www.wow-mania.com/armory/?item=42772
![image](https://user-images.githubusercontent.com/108176634/188945741-adb6f44f-166c-4219-acc6-deff8a560622.png)

Have you opened the quest in your bag to start the quest yet?
Nergeld becomes a mountable NPC to help you with the quest

**Comment by Rushor** [comment]
changed faction to prevent that issue, while quest is still totally fine doable

**Comment by GMZinius** [comment]
Co

> changed faction to prevent that issue, while quest is still totally fine doable

Perfect Rushor, Thanks 👍
