### ISSUE TITLE
[LOCATION] The Underhalls [NPC's]

### ISSUE THREAD

**Issue by womptista** [WoWManiaUK/Redemption#5911]
Naxx Server
**Links:**
Link to youtube video
https://youtu.be/Iu3XpPYemfQ

**What is Happening:**
The mobs at the bottom of the steps swim to their next position.

**What Should happen:**
They should walk not swim

**Comment by Rushor** [comment]
fixed alongside with https://github.com/WoWManiaUK/Redemption/issues/5909

those npc should not walk at all, only lay static on ground as visual npcs, nothing more,

fixed in the other issue
