### ISSUE TITLE
[MOUNT] Mechacycle

### ISSUE THREAD

**Issue by womptista** [WoWManiaUK/Redemption#5912]
**Links:**
Link to Mount on the armory
https://www.wow-mania.com/armory/?item=158118
Link to youtube video of Mechacycle
https://youtu.be/XO5IU8rB_44

**What is Happening:**
There is no animation sounds associated with the mechacycle besides mounting and dismounting. Moving is just the default walking sound.

**What Should happen:**
There should be actual sounds for the cycle being used.  Below is a link to Retail WoW Mechacycle
https://www.youtube.com/shorts/nkhE98Pm_zY

**Comment by Rushor** [comment]
is not possible to be added in this part of the expansion, since it is only a downport of the mount in a basic script style
