### ISSUE TITLE
[Item] Spinal Dust Not Dropping

### ISSUE THREAD

**Issue by bdavis1515** [WoWManiaUK/Redemption#5913]
**Links:**
https://tbc.wowhead.com/quest=9218/spinal-dust

**What is Happening:**
Spinal Dust is not dropping

**What Should happen:**
Spinal dust should drop from mobs sometimes.

**Comment by GMZinius** [comment]
Thank you @bdavis1515 for reporting
this definately drops 

https://www.wow-mania.com/armory/?item=22642#dropped-by:0-8+1
