### ISSUE TITLE
[Quest]: King of the Foulweald - Mob Wave Issues

### ISSUE THREAD

**Issue by kamoodle5** [WoWManiaUK/Redemption#5914]
**Links:**
https://classic.wowhead.com/quest=6621/king-of-the-foulweald
https://classic.wowhead.com/npc=12921/enraged-foulweald
https://classic.wowhead.com/npc=12918/chief-murgut#drops

**What is Happening:**
1.) After the first two mobs spawn, another three will spawn within a certain time. This wave sequence continues as such until Chief Murgut appears after wave 7 (I've confirmed this after two attempts).
2.) The mobs that appeared during the waves are not always the same type. There are totemics, ursas, and warriors.
3.) Murgut's totem can be found on both him and the basket. 

**What Should happen:**
1.) According to several Wowhead comments, there should always be two mobs present. When one dies, another replaces him. Also, Chief Murgut has his own timer, meaning it's not required to kill mobs before him. A player could simply endure the first two mobs until he shows up.
2.) Only this mob should spawn during the event: https://classic.wowhead.com/npc=12921/enraged-foulweald. 
3.) The totem should only be looted from the basket that Murgut drops, not from Murgut himself.

Here's the oldest video I can find of the quest:
https://youtu.be/qjpqeP9vo5U?t=11

And here's my video clip of my experience:
https://youtu.be/EHCKDM2kqVQ

**Comment by GMZinius** [comment]
Thank you @kamoodle5 for reporting

**Comment by Rushor** [comment]
Best we can do here is spawning a new wave every 40 sec that is the way we can easy fix it without changing too much.

spawn amount and mob type can also be changed

loot can also be adjusted

**Comment by Rushor** [comment]
all above applied

**Comment by GMZinius** [comment]
> all above applied

all confirmed fixed on PTR

Timer of spawns is good 

![image](https://user-images.githubusercontent.com/108176634/189520039-4d1673b2-8b22-417c-8d63-da4d4be6d3b2.png)

![image](https://user-images.githubusercontent.com/108176634/189520077-c04e3948-3c03-4e5d-a409-72d7dd43103c.png)
