### ISSUE TITLE
[NPC]: Warsong Peon - Combat Issues With Alliance Players

### ISSUE THREAD

**Issue by kamoodle5** [WoWManiaUK/Redemption#5915]
**Links:** https://www.wowhead.com/wotlk/npc=11656/warsong-peon

Note: There is another report related to this NPC, but it's for a Horde quest: #5769 

**What is Happening:**
1.) Once this npc enters combat, he/she will attempt to flee as if near death; they engage normal afterwards.
2.) Sometimes after entering combat, they do not move or attack. This leaves them completely vulnerable for alliance players to attack them. I discovered not all peons get "stuck", and those that do are not standing too close to an entity (fallen log or tree trunk). At least they do not go into evasion.

**What Should happen:**
1.) Instead of running around aimlessly, they should try to run off towards the nearest NPC (usually a horde scout (https://www.wowhead.com/wotlk/npc=11680/horde-scout) or a warsong grunt (https://www.wowhead.com/wotlk/npc=11682/warsong-grunt)) after entering combat. Also, according to a few Wowhead comments, if there are no living NPCs around, the peon will run to the nearest corpse and ask for help.
2.) The few peons that get stuck should not be.

Here's my video clip of the peons whenever I engage them with my alliance toon:
https://youtu.be/UmKbExqrzhE

This is the best video I can find for how a peon will flee towards another mob in TBC Classic, which happens at 25:56. I couldn't find an instance of one approaching a corpse though: 
https://youtu.be/hRJkP2CJr5Y?t=1555

**Comment by GMZinius** [comment]
Thank you for reporting @kamoodle5 
Warsong Peon (level 66) from the Horde quest you linked is a different issue and zone and not related 

Warsong Peon (level 26) NPC behaviour in Ashenvale will be looked into soon, thank you

**Comment by kamoodle5** [comment]
Oh, dear, that's right! That's what happens when I make a bug report so late at night.

**Comment by GMZinius** [comment]
> Oh, dear, that's right! That's what happens when I make a bug report so late at night.

No problem, I confirmed this one 👍

**Comment by Rushor** [comment]
They will flee correctly at 15 percent hp now instead upon entering combat :)

**Comment by GMZinius** [comment]
> They will flee correctly at 15 percent hp now instead upon entering combat :)

That part is fixed, Thank you.


but movement is Slow motion, don't run in fear as they should @Rushor

**Comment by GMZinius** [comment]
Confirmed fixed ion PTR
after internal chat about a generic issue found
