### ISSUE TITLE
[NPC] Ymirjar huntress/Warhawk in Frost Hall - Aggro From Afar

### ISSUE THREAD

**Issue by Bartok14** [WoWManiaUK/Redemption#5916]
**What is Happening:**
You can right click the mobs in the frost hall on the way to valithria and it will aggro them without attacking them. This allows them to aggro from outside normal attack range and it results in most of the enemies in the hall being aggroed to the fight at the start. This easily leads to wipes in pug raids. 

**What Should happen:**
I don't think this should happen at all but I have no way to prove it based on retail. I think it's just a bug. Right clicking an enemy shouldn't automatically aggro them.

**Comment by Rushor** [comment]
Is this Happening always?

**Comment by Bartok14** [comment]
> Is this Happening always?

I don't know. It never seemed to be an issue years ago. But now if anyone right clicks the mobs as t the end of the hallway it will agro the entire hall minus a few enemies.

**Comment by Rushor** [comment]
Hm i cannot reproduce this? https://gyazo.com/79e3751ef90486958677dfa295933f21

**Comment by Bartok14** [comment]
> Hm i cannot reproduce this? https://gyazo.com/79e3751ef90486958677dfa295933f21

When it's happened to us it's always while the NPCs are still engaged and fighting in the fight.

**Comment by Rushor** [comment]
okay so while the very first mobs are engaged, the very last far away mobs get pulled aswell?

**Comment by Bartok14** [comment]
> okay so while the very first mobs are engaged, the very last far away mobs get pulled aswell?

Yes if someone right clicks them during the fight. Generally it's the birds that are the ones that agro first.

**Comment by Rushor** [comment]
checking once ptr is up

**Comment by GMZinius** [comment]
Reproduced it I think,  thank you for reporting @Bartok14 

@Rushor 
Once the fight starts, Player can right click on the Warhawk at the back of the room and pull them even when the error message says "Your too far away https://i.gyazo.com/28879f1444fcf05e48e7787236e81203.mp4

**Comment by Rushor** [comment]
should be good now

**Comment by GMZinius** [comment]
> should be good now

All good 👍 
https://i.gyazo.com/baea0126b0d637e7c639423695b6b07f.mp4

**Comment by svijetlo** [comment]
Ymirjar huntress can also use skill like volly etc even if dismantled or disarmed

**Comment by GMZinius** [comment]
> Ymirjar huntress can also use skill like volly etc even if dismantled or disarmed

Fix for abilities is here @Rushor #3459 
could you look into this before this fix goes live please, Thanks

**Comment by Rushor** [comment]
NPC_YMIRJAR_HUNTRESS will no longer be able to excecute it's events if it has UNIT_FLAG_DISARMED (beeing disarmed by the spells)
