### ISSUE TITLE
[NPC]: Compact Harvest Reaper - Max Level at Multiple Areas

### ISSUE THREAD

**Issue by kamoodle5** [WoWManiaUK/Redemption#5917]
**Links:** https://classic.wowhead.com/npc=2676/compact-harvest-reaper

Note: This pet can be summoned by these mobs:
https://classic.wowhead.com/npc=5836/engineer-whirleygig
https://classic.wowhead.com/npc=3993/venture-co-machine-smith
https://classic.wowhead.com/npc=677/venture-co-tinkerer

**What is Happening:** This mob always seems to be at max or close to max level in all the areas it can appear, making it too strong for players at lower-level areas like the Barrens, for example.

**What Should happen:** It shouldn't be max level at lower-level areas; it should scale closer to the mob that summoned it. According to Wowhead, its level ranges from 19 to 41.

Screenshots:
Sludge Fen at the Barrens:
![WoWScrnShot_091822_140820](https://user-images.githubusercontent.com/67519835/190925314-2779a582-2cc1-466e-bbe1-75f818090733.jpg)

Cragpool Lake at Stonetalon Mountains:
![WoWScrnShot_091822_141511](https://user-images.githubusercontent.com/67519835/190925337-b3ed65a0-0755-42df-ad39-abf45fcc77b2.jpg)

Stranglethorn Vale (at least this level seems more accurate here):
![WoWScrnShot_091822_142055](https://user-images.githubusercontent.com/67519835/190925354-9ef19256-093a-4a31-918f-be39672c2976.jpg)

**Comment by GMZinius** [comment]
Thank you @kamoodle5  for reporting

Yes I saw [engineer-whirleygig](https://classic.wowhead.com/npc=5836/engineer-whirleygig) summoned a lvl 41 
then summon a lvl 19 Explosive Sheep ever few seconds

**Comment by GMZinius** [comment]
Thank you for reporting @kamoodle5 

Confirmed bugged 

Yes from what I saw from [engineer-whirleygig](https://classic.wowhead.com/npc=5836/engineer-whirleygig) he summons a lvl 41 [compact-harvest-reaper](https://classic.wowhead.com/npc=2676/compact-harvest-reaper) and then every few seconds summons a lvl 19 Explosive Sheep https://www.wow-mania.com/armory/?npc=2675

at 8:47 you can see that the harvest reaper is lvl 19  https://www.youtube.com/watch?v=dEqRKj04ots

**Comment by Rushor** [comment]
should be fixed liek that, that it takes the level of the owner and applies that range to itself

**Comment by Rushor** [comment]
code applied, fixed after next compile an restart

**Comment by Rushor** [comment]
have a better idea to fix this!

**Comment by Rushor** [comment]
okay the reaper will now take the level of the summoner

**Comment by GMZinius** [comment]
Confirmed fixed

![image](https://user-images.githubusercontent.com/108176634/194776546-6381f378-ce99-419b-a28f-bb80833f3033.png)
![image](https://user-images.githubusercontent.com/108176634/194776474-58baa66c-9822-4f9d-975b-c664fa7c11f8.png)
![image](https://user-images.githubusercontent.com/108176634/194776622-58309719-01f4-45ce-b138-c2aeed8125b9.png)
