### ISSUE TITLE
Warsong Gulch - Line of Sight - shot by opponent through ground

### ISSUE THREAD

**Issue by brieks07** [WoWManiaUK/Redemption#5918]
Hello, 

I spoke with the GM, Fairwinds, in game, and Fairwinds directed me to report this problem via GitHub. Fairwinds believes "that a graphical issue like that exists."
Here is what happened:
I was in the Warsong Gulch battleground on an Alliance character. I believe this was the day before yesterday. I had opened the ticket and spoke to Fairwinds the same day, but I haven't been able to create this GitHub report until now. Here is what happened in game: I was playing my Draenei mage, Liliara, and I had died the Warsong Gulch battleground and had resurrected at the Alliance graveyard in Warsong Gulch. I stood on the edge of the cliff and was targeted by a Horde player character named Nasty. Nasty was a hunter. Because I was being attacked, I moved backward, away from the cliff. I moved far enough backward in the graveyard to lose line of sight. There was no way that there was line of sight for a successful attack between me and Nasty. However, Nasty was able to shoot me through the ground in the graveyard! I saw the shots coming up through the ground and hitting my character! I did not have line of sight on him; he should not have had line of sight on me, and I know his attacks should not have been able to hit me through the ground, as far back as I was from the cliff in the Warsong Gulch graveyard. 
Unfortunately, it all happened so quickly, that I don't have any screenshots or video. I've played WoW for years, and I was very far back in the graveyard. There should have been no way for an enemy on the ground below to be able to shoot me through the ground.

**Comment by GMZinius** [comment]
This issue is a known issue, and was report here https://github.com/WoWManiaUK/Redemption/issues/4345
Thank you for reporting
