### ISSUE TITLE
[Object] Brewfest Wagons -  on Top of Other Entities in Dun Morogh

### ISSUE THREAD

**Issue by kamoodle5** [WoWManiaUK/Redemption#5919]
**What is Happening:** The massive Brewfest wagons found throughout the main Alliance Brewfest site in Dun Morogh are placed over other objects and even NPCs.

**What Should happen:** They just need to be moved a tad. I bet the Gordok ogres will appreciate not having one of these wagons sitting on top of their shop. 

![WoWScrnShot_092022_210732](https://user-images.githubusercontent.com/67519835/191399525-1b5064fc-93bc-4a60-839e-e1715fa0d901.jpg)

![WoWScrnShot_092022_210849](https://user-images.githubusercontent.com/67519835/191399541-1e76a16e-d5af-4867-81f0-68b330c8fc77.jpg)

![WoWScrnShot_092022_210906](https://user-images.githubusercontent.com/67519835/191399553-967297ed-1e16-4d14-b69a-b52da6d07eba.jpg)

**Comment by GMZinius** [comment]
confirmed thank you for reporting @kamoodle5 


for @Rushor 

![image](https://user-images.githubusercontent.com/108176634/191485990-3fadffad-7868-422b-886d-e33be15411e7.png)
![image](https://user-images.githubusercontent.com/108176634/191486174-8810d78c-3ea9-404a-aeee-0f7bbd79dc16.png)
![image](https://user-images.githubusercontent.com/108176634/191486675-f280308a-b891-4e2f-8248-fcb718fc0c26.png)

**Comment by Rushor** [comment]
unneeded wagons removed and some better spawned

**Comment by GMZinius** [comment]
Much cleaner, clearer access to NPCs as seen in video here https://www.youtube.com/watch?v=o8AXBAPRXmU
Spawns much better thank you https://i.gyazo.com/853f4d592599c6609d97937c5d624b08.mp4

![image](https://user-images.githubusercontent.com/108176634/191557668-1f3bc6e2-ed9c-4937-a1fb-e54c696ba913.png)
