### ISSUE TITLE
[Quest] The Ransacked Caravan (11465)

### ISSUE THREAD

**Issue by Brunnr** [WoWManiaUK/Redemption#592]
Using the WoW-Mania client, with the November 2016 patch on Win10 64 bit machine. When using the Trained Rock Falcon object with grubs to capture a Fjord Turkey, an ambusher mob should immediately spawn to attack you, and you should receive credit for the captured turkey. The quest completes after capturing 5. Having just did the quest, I captured 5+ and there was no ambusher spawns and no credit. But waiting 1-2 minutes, perhaps more, at the same area (69,64 in Howling Fjord) the ambushers suddenly started spawning at the same rate as each turky was caught, and I received credit at the same time as each spawn. So it appears the issue is just the spawn timer for the ambusher mobs is too long.

Thanks!

**Comment by fvicaria** [comment]
http://www.wowhead.com/quest=11465/the-ransacked-caravan
