### ISSUE TITLE
[NPC:] Flynn Firebrew Missing

### ISSUE THREAD

**Issue by kamoodle5** [WoWManiaUK/Redemption#5920]
**Links:** https://tbc.wowhead.com/npc=24364/flynn-firebrew

**What is Happening:** He seems to be absent from his supposed spot (NPC you will see at my screenshot is the hunter trainer), thus Alliance players are unable to complete the daily quest "There and Back Again" (https://tbc.wowhead.com/quest=11122/there-and-back-again)

**What Should happen:** He needs to come back, or if he is actually present somewhere, he should be at his normal spot.

Screenshot: 
![WoWScrnShot_092322_210308](https://user-images.githubusercontent.com/67519835/192075695-d9744d23-1953-47b9-b795-366ee1218c29.jpg)

Videos:
https://youtu.be/TiXDOG7Idj8?t=41
https://youtu.be/_ANUW_GSgGA?t=138
Second video is the oldest video found even though it's in Cataclysm, yet Blizzard kept him at the same spot in that expansion.

**Comment by GMZinius** [comment]
From what I can see @kamoodle5 https://tbc.wowhead.com/npc=24364/flynn-firebrew is only visable when you are on the quest 

You only have 3 minutes buff to complete the quest, then you must abandon and do it again 


![image](https://user-images.githubusercontent.com/108176634/192103921-64d19453-34d6-46d3-9ace-903cae90a3cc.png)
