### ISSUE TITLE
[Object:] Brewfest Apple Barrels At Wrong Locations (Alliance)

### ISSUE THREAD

**Issue by kamoodle5** [WoWManiaUK/Redemption#5921]
**Links:** https://tbc.wowhead.com/guides/brewfest-burning-crusade-classic#repeatable-quests
https://tbc.wowhead.com/quest=11122/there-and-back-again

**What is Happening:** The apple barrels used to refresh the ram mount while doing the daily quest "There and Back Again" seem to be at slightly wrong locations.

**What Should happen:** According to the first link above, the barrels should be at these locations:
Barrel 1 should be around 47.5 44.4.
Barrel 2 at around 46.4 48.0.
Barrel 3 at around 46.3 53.8.

Screenshots:
![WoWScrnShot_092322_210155](https://user-images.githubusercontent.com/67519835/192076414-25d79901-a655-4fae-a74c-df6526d30c1b.jpg)
![WoWScrnShot_092322_210227](https://user-images.githubusercontent.com/67519835/192076496-163482b8-3be2-489c-8bb4-b9432552c070.jpg)
![WoWScrnShot_092322_210341](https://user-images.githubusercontent.com/67519835/192076505-f7f06b57-bc07-4c69-afdd-91b2fb87aff7.jpg)

Video:
https://youtu.be/TiXDOG7Idj8?t=14
At 0:45, you can find the third and last barrel near the wagon with the red awning.

**Comment by GMZinius** [comment]
Thank you for reporting @kamoodle5 

@Rushor locations of Apple barrels Map gps https://wotlk.evowow.com/?object=186331#spells

**Comment by Rushor** [comment]
Testable with: .event start 24

Spawnpositions are adjusted according to alliance video above
