### ISSUE TITLE
[NPC] Bok Dropcertain - Goblin Who Tosses Brewfest Kegs is Missing (Horde)

### ISSUE THREAD

**Issue by kamoodle5** [WoWManiaUK/Redemption#5922]
**Links:**https://tbc.wowhead.com/quest=11412/there-and-back-again
https://tbc.wowhead.com/npc=24527/bok-dropcertain (I think this is the guy)

**What is Happening:** This NPC and his entire setup (wagon, flag) have all disappeared, thus Horde players are unable to complete the daily Brewfest quest, There and Back Again.

**What Should happen:** He should be back at his spot with his stuff.

Screenshot:
![WoWScrnShot_092322_220300](https://user-images.githubusercontent.com/67519835/192077496-b1e28c05-4063-4bb6-8d57-77b0c1c37eba.jpg)

Video:
I hope this one is not too new.
https://youtu.be/rTys3VnW2zM?t=43

**Comment by GMZinius** [comment]
From what I can see @kamoodle5 https://tbc.wowhead.com/npc=24527/bok-dropcertain is only visable when you are on the quest (though yes his other objects are missing)

![image](https://user-images.githubusercontent.com/108176634/192103571-08062b35-e1c5-40b5-8e36-8815711a7b85.png)
