### ISSUE TITLE
[Object] Apple Barrel is Missing (Horde)

### ISSUE THREAD

**Issue by kamoodle5** [WoWManiaUK/Redemption#5923]
**Links:** https://tbc.wowhead.com/quest=11412/there-and-back-again
https://tbc.wowhead.com/guides/brewfest-burning-crusade-classic#repeatable-quests

**What is Happening:** One of the apple barrels used for refreshing the ram mount during the Horde daily Brewfest quest, There and Back Again, is missing.

**What Should happen:** It should be present at its normal location, which according to the second link above, is at 48.9, 28.0.

Screenshot:
![WoWScrnShot_092322_224426](https://user-images.githubusercontent.com/67519835/192078795-617cf23b-5f1f-4e1b-a69e-104bac943d17.jpg)

Video:
https://youtu.be/UpHX6Wuqx5M?t=33

**Comment by GMZinius** [comment]
Thank you for reporting @kamoodle5 

@Rushor locations of Apple barrels Map gps https://wotlk.evowow.com/?object=186331#spells

**Comment by Rushor** [comment]
barrel added at that position
