### ISSUE TITLE
[Item] Blue shado-pan riding tiger not roaring

### ISSUE THREAD

**Issue by kossujuki1992** [WoWManiaUK/Redemption#5924]
**Links:**

**What is Happening:**
Hello!

Unfourtunately it is not roaring like a tiger is supposed to. Maybe you can fix this :)

**What Should happen:**
Tiger should roar when it is standing and i hit the space bar. If it is not possible then let me know and we could decide if we stay with the mount or change for another one that works properly. 

Best regards
Juhan - Kustav

**Comment by GMZinius** [comment]
Thank you for reporting @kossujuki1992 
We will look into this

**Comment by GMZinius** [comment]
Please contact support @kossujuki1992
