### ISSUE TITLE
[NPC] Kirgaraak - Knock back issue

### ISSUE THREAD

**Issue by womptista** [WoWManiaUK/Redemption#5925]
**Links:**
{wow-armory Link} https://www.wow-mania.com/armory/?quest=12996

**What is Happening:**
(I HAVE ATTACHED A SCREEN SHOT OF WHERE HE WAS STANDING WHEN THE GLITCH HAPPEND HE WAS STANDING AT THE RED ARROW FACING WHERE HE NORMALLY IS LOCATED)
![Location when smash glitch](https://user-images.githubusercontent.com/66838614/192830926-6e34ea60-8629-4d76-a78a-eea9806ceb9d.jpg)

During the quest you get mounted on "Warbear Matriarch" and have a duel with Kirgaraak. (This is all takes place in Brunnhildar Village) during the battle if you use the skill "SMASH" While Kirgaraak is in the corner (coords to where he was 51.68 67.38 he was facing East) he will not have anywhere to go when using the skill "SMASH" and will start to float around the map. He will not reset his HP and will give the player time to dismount and remount resetting their mounts HP. ( Seem's that Kirgaraak is hitting harder than he should be even on over geared players)

**What Should happen:**
He should not float around the map allowing players to reset their own HP.

**Comment by GMZinius** [comment]
Thank you for reporting @womptista 
We will check on this issue

**Comment by Rushor** [comment]
Needs to add a knockback reset to prevent that issue

**Comment by GMZinius** [comment]
> Needs to add a knockback reset to prevent that issue

Yes, I checked this out a little yesterday Rushor, and can confirm the knock back has a long range compared to most videos i viewed when players move him from where is home possition is

**Comment by Rushor** [comment]
To fix all those possible glitches i made him immune to knockback effects now

**Comment by Rushor** [comment]
Dmg value lowered of Kirgaraak and applied knockback immunity to him

**Comment by GMZinius** [comment]
Confirmed fixed 

- knockback fix the best way is could be thanks Rushor
- Dmg value ajusted to replace the above fix
- Quest complete woeking
