### ISSUE TITLE
[RAID] Icecrown Citadel [NPC] Val'Kyr Shadowguard

### ISSUE THREAD

**Issue by womptista** [WoWManiaUK/Redemption#5926]
**Links:**
wow-mania armory link https://www.wow-mania.com/armory/?npc=36609
Youtube recorded clip https://youtu.be/gh1MSJNRtPQ

**What is Happening:**
The Valk'Kyr starts as it should with picking up a player. But during the defile portion the Val'Kyr will teleport to the edge of the map and drop the player to their death.

**What Should happen:**
The Val'Kyr should not teleport and continue it's path wiht out TELEPORT.

**Comment by GMZinius** [comment]
Thank you for the report @womptista 
The NPCs are working as they should, fixed here a few months ago https://github.com/WoWManiaUK/Redemption/issues/5805

Tested and confimed by Testers
