### ISSUE TITLE
[NPC] Val'kyr Shadowguard - Single Target Stuns Causing Blink

### ISSUE THREAD

**Issue by Bartok14** [WoWManiaUK/Redemption#5928]
**Links:**
https://wowpedia.fandom.com/wiki/Lich_King_(tactics)
https://wowwiki-archive.fandom.com/wiki/Lich_King_(Icecrown_Citadel_tactics)#Phase_2

**What is Happening:**
Single target stuns like Hammer of Justice are occasionally causing the Val'Kyr to blink away from the location that they are stunned at. I'm not sure if this is happening as the stun is used or after the stun wears off and the pathing bugs out and they teleport towards the edge.  

**What Should happen:**
This seems to be a relatively new issues. It was never a problem to single target the Valks before but it seems to be an issue now. From what I understand you have 3 stuns you can use on the Valks before they become immune. Some groups back in the day opted to take improved Hammer of Justice and single target stun the Valks by assigning them a raid mark. Other groups opt to use Holy Wrath 3 times in a row with a short delay in casts between them to reset diminishing returns. Now it seems that the first strategy doesn't work because it's causing an error with the Valks pathing where it blinks towards the edge faster if you single target it. As far as I know this should not happen. I've linked a couple guides that are from back in the day where there is no mention of Valks blinking as part of the fight.

**Comment by womptista** [comment]
Same on Naxx.

**Comment by GMZinius** [comment]
> Same on Naxx.

Reported here for Naxx issue a few days ago @Rushor #5926

Thank you for reporting from Redemption to

**Comment by fvicaria** [comment]
We are not touching these anymore.

**Comment by svijetlo** [comment]
this should be looked in to it is serious issue ...

**Comment by Bartok14** [comment]
> We are not touching these anymore.

Can I ask why? This is a major mechanic to the Lich King fight that causes potential wipes for no reason other than it is bugged.

**Comment by Echinaceax** [comment]
> We are not touching these anymore.

Reopening this one, Jormag also confirms it happens

**Comment by JormagMania** [comment]
Good day,

Indeed, I have seen that blink issue a few times. I was not sure if it was related to Holy Wrath stun or not but it seems it is only on Hammer of Justice. I have not seen this happen in 25, only in 10, I am not sure if Valkyries are immune to HOJ on 25 or that we just have enough paladins to use 3 Holy Wrath and no one ever used HOJ. Therefore that issue does not occur. I will try to test it on a 10 NM ICC whenever I can.

**Comment by svijetlo** [comment]
this is old bug it is here for month now , any single target stun can make them to this , so ANY SINGLE TARGET STUN will make them stay in spot , ones stun time is over valk will "jump/teleport" to place where it would/should be if stun was used on it , instead of continuing form spot where it got stun 
it makes raid stupid and make some mechanics useless

**Comment by Echinaceax** [comment]
thats why i reopened it @svijetlo (i know jani said not doing it, but i believe we have all the info now for Keader

**Comment by Rushor** [comment]
They will now properly be slowed and stunned and should no longer blink once the single stun effect runs out.

It requires 3 people and at least 1 tank at lk to test this change.

**Comment by GMZinius** [comment]
fix reverted

**Comment by Yhato794** [comment]
This is still happening btw should i open a new issue or you wanna re-open this one?

**Comment by GMZinius** [comment]
> This bug is back for some reason should i open a new issue or you wanna re-open this one?

Thank you for commenting @Yhato794 
This fix was reverted in january, this has been like this for the last 2 months

This will stay as-is because causes more issues elsewhere
