### ISSUE TITLE
[NPC] Halion - Tail Swipe Occuring In Middle of Boss

### ISSUE THREAD

**Issue by Bartok14** [WoWManiaUK/Redemption#5929]
**Links:**

**What is Happening:**
As you run through the boss to avoid the meteor some people are getting tail swiped in the middle of the boss.

**What Should happen:**
Tail swipe should occur behind the boss like every other dragon. It shouldn't be an issue when running through the boss to the other side. I think Tail Swipes hit box is somehow occurring from the center of the boss instead of occurring from behind the boss. It might have moved due to a recent change but this didn't used to be an issue.

**Comment by GMZinius** [comment]
Thank you for reporting @Bartok14 

It could not be reproduced from this earlier report #4160

**Comment by GMZinius** [comment]
@Rushor
Testing soon

**Comment by svijetlo** [comment]
it is easy to test during halion fight if boss it self was moved a bit after that even if you run directly under it or more towards head you can get tail swipe stun

**Comment by GMZinius** [comment]
Confirmed @keader that the hitbox is off 

can you check please 

going from this diagram thanks

![image](https://user-images.githubusercontent.com/108176634/199792346-0d7cd0bc-70fc-4dc2-a04e-2f80f2737fe1.png)

**Comment by Keader** [comment]
Is weird say that, but yes it's correct.
Check: youtube.com/watch?v=j-nTNgJSZFM&t=251s
I fixed it years ago to other server and then i need revert, because is blizzlike behavior
