### ISSUE TITLE
[Quest] Springing the trap

### ISSUE THREAD

**Issue by iggapres** [WoWManiaUK/Redemption#593]
Here's the quest http://wotlk.openwow.com/quest=11969

1) Keristrasza does not pop exactly where she should. She burns the corpse almost inside the nexus entrance crystal block. So, you need to move close to her to get mounted at the end of this first phase.
2) The flight takes you to some zone (I don't remember where it took you on retail, but seems ok)
3) Malygos appears, they argue, Malygos freezes Keristrasza, they all depop, no quest validated.

Tried 3 times with same result.

I guess it's bugged :)

**Comment by fvicaria** [comment]
I am sure it works and there is a distance min-max. I will check now.

**Comment by fvicaria** [comment]
![image](https://cloud.githubusercontent.com/assets/9414661/21075104/b81f6a42-bf01-11e6-8535-c21d560a6c86.png)
![image](https://cloud.githubusercontent.com/assets/9414661/21075106/c93cabaa-bf01-11e6-98a9-acc2ec724794.png)

![image](https://cloud.githubusercontent.com/assets/9414661/21075110/da15a490-bf01-11e6-9a5a-4d67a47975b6.png)

![image](https://cloud.githubusercontent.com/assets/9414661/21075112/e4d877cc-bf01-11e6-9175-1c6052c4eb6b.png)

**Comment by Kalasbyxan** [comment]
I tried this three times today and only when standing just like Janitor on the picture, it will work. Might need to fix the trigger point for this as standing in any other position I tried resulted in a fail.

**Comment by fvicaria** [comment]
I will try to increase the area for credit.
