### ISSUE TITLE
[NPC] Flame of Azzinoth - Flames are Bouncing Around the Room at Super Speed

### ISSUE THREAD

**Issue by Bartok14** [WoWManiaUK/Redemption#5930]
**Links:**
https://youtu.be/k8_JbDiALkY?t=466

**What is Happening:**
The two Flames of Azzinoth that spawn from Illidan's Warglaives aren't holding aggro on the thanks. Instead they are bouncing around the room like their heads are cut off and targeting everyone. They are also moving at super speed while they do this so the floor ends up with fire all over the place. 

**What Should happen:**
Adds should be able to get picked up by tanks and held in place. They also should not be moving at the speed they are moving at.

**Comment by GMZinius** [comment]
@Rushor 
Testing soon

**Comment by Rushor** [comment]
Keader is the master for this raid :)

**Comment by GMZinius** [comment]
We need more inforrmation still @Bartok14 
Did you or your raid move around or stay on their assigned spots from the raidleader?

Phase2 
![image](https://user-images.githubusercontent.com/108176634/197772709-4213bbbc-1c89-4131-9ccd-b7ccaba6a5ca.png)

Closing for now until more information is given 
A video of the issue would be really helpful
