### ISSUE TITLE
My Berserker Quest for warrior is not showing please I need Help

### ISSUE THREAD

**Issue by gersonantal** [WoWManiaUK/Redemption#5933]
**Links:**

**What is Happening:**
My Berserker quest is not able for me my char is Madpro a warrior. I did try the quest and I failed I quit the quest but now isn't showing the quest for me to try it again...please help me!

**What Should happen:**
Have acess to the berserker quest

**Comment by GMZinius** [comment]
Please make an ingame ticket by clicking on the ❓ on you bar @gersonantal and they will help you with this
