### ISSUE TITLE
[NPC] Coilfang Striker or [NPC] Lady Vashj

### ISSUE THREAD

**Issue by womptista** [WoWManiaUK/Redemption#5935]
**Links:**
Lady Vashj armory Link https://www.wow-mania.com/armory/?npc=21212
Coilfang Strier Armory Link  https://www.wow-mania.com/armory/?npc=22056
Youtube video evidence https://youtu.be/e_lKBqP9ngE

**What is Happening:**
There is a movement speed increase upon being feared

**What Should happen:**
Movement speed should not be increased

**Little Back Story**
Lady Vashj, when SSC first released had an ability called Persuasion which would increase damage output by 999% increase healing done by 200% and increase movement speed by 200%. This ability was quickly removed before patch 3.3.5. Now the Coilfang Strider is suppose to do a panic as they are doing in the video but the movement speed of around 200% is not part of that skill but we are still getting it so not sure what is happening.

**Comment by GMZinius** [comment]
Thank you for reporting @womptista 

I found this "Revision as of 06:07, 1 November 2010" https://wowpedia.fandom.com/wiki/Coilfang_Strider?oldid=2452812
I clicked on "tactics" then scrolled down to [Coilfang Strider](https://wowpedia.fandom.com/wiki/Coilfang_Strider)

![image](https://user-images.githubusercontent.com/108176634/198156780-4a5c3ae8-4edd-4471-ac57-8ccf9d82004e.png)


From what I can see it seems that the increased movement is meant to be this way until 5.3
I will see what the Dev team think

**Comment by Rushor** [comment]
The retail spell info provides this aswell https://www.wowhead.com/wotlk/spell=38258/panic

I think its correct

**Comment by GMZinius** [comment]
> I think its correct

Yes thought that to @Rushor, thank you for verifying
