### ISSUE TITLE
ICC Professor Putricide healing as disc priest

### ISSUE THREAD

**Issue by TroniiX1337** [WoWManiaUK/Redemption#5936]
**Links:**
Example for 10HC fight retail:
https://www.youtube.com/watch?v=dx80DtZpsQ4&t=22s

**What is Happening:**
So the overall problem that I have with that boss fight,  as a disc priest, is that my shields (Power Word: Shield) isnt working in the way it should work.
So when i compare the fight Professor Putricide with the fight against Bloodqueen you got nearly the same dmg income (some singletarget dmg + raid wide dmg over time, maybe more on bloodqueen).
What is happening when i compare my healing on these two fights is that my spell (Power Word: Shield) is doing way less healing/absorbing in the fight against Professor Putricide. 
In total numbers that mean that when im doing around 1.0mio heal with only Power Word: Shield (in the bloodqueen fight overall) i do only 200k heal (in the professor fight). Compared in HPS that mean i do 10k HPS in bloodqueen fight (10HC) and 3.5-4k HPS (professor fight 10hc). These numbers are createt with the same gear on the same day in the same raid (see photos).

![fight 10 HC professor](https://user-images.githubusercontent.com/117040532/198986655-7ab34478-574b-4f92-aac3-33ce1b9c5fc6.jpg)
![fight 10 HC bloodqueen](https://user-images.githubusercontent.com/117040532/198986663-16b8d27e-adb8-47f0-9fd5-9dd95c3f9229.jpg)

I cant really tell if the problem is that the shields arent working right or that the spell Power Word: Shield is used on a very low rank 
automatically only in this fight. I tried to use a marco where i use Rank 13 Power Word: Shield to see if its the problem with the Rank 14 spell, but it didnt change anything. So its also not a marco problem cause i tryed to use these marcos and all didnt work:

#showtooltip Power Word: Shield(Rank 14)
/cast [@mouseover, help, nodead] Power Word: Shield(Rank 14)

#showtooltip Power Word: Shield(Rank 13)
/cast [@mouseover, help, nodead] Power Word: Shield(Rank 13)

#showtooltip Power Word: Shield
/cast [@mouseover, help, nodead] Power Word: Shield

So to reproduce the problem you only have to do the bossfight on any dif. and play disc priest.

**What Should happen:**
So when you are doing research on disc priest povs on professor fights from old retail you will see that the healing amount of disc priest will be around 8-10k in a 10HC fight. On retail it wasnt a problem to heal this fight as disc. here its a big problem cause i have no HPS at all.

Here is an example:
https://www.youtube.com/watch?v=dx80DtZpsQ4&t=22s

PS:
If you need more material i can screenshot more professor fights in future (next will be 25hc on tuesday (01.11.2022).

**Comment by GMZinius** [comment]
Thank you for reporting @TroniiX1337 
Over the years this has been looked into many times 
some fixes and some closed https://github.com/WoWManiaUK/Redemption/issues?q=Power+Word%3A+Shield
https://github.com/WoWManiaUK/Redemption/issues/2439#issuecomment-385068172

so this is as-is
