### ISSUE TITLE
[NPC] Mishellena <Hippogryph Master> 

### ISSUE THREAD

**Issue by GMZinius** [WoWManiaUK/Redemption#5939]
**Links:**
https://www.wow-mania.com/armory/?npc=12578

**What is Happening:**
- Mishellena respawn timer after she has been killed is to long 

**What Should happen:**
- Reduce respawn timer from 10 mins to 5 mins

**Comment by Rushor** [comment]
adjusted after next ptr startup :)

**Comment by GMZinius** [comment]
Confirmed fixed on PTR 

![image](https://user-images.githubusercontent.com/108176634/201533818-0de22a77-e790-4666-8cf7-58e27606d0f6.png)
