### ISSUE TITLE
[NPC] Attumen the Huntsman

### ISSUE THREAD

**Issue by Brunnr** [WoWManiaUK/Redemption#594]
[http://www.wowhead.com/npc=16152/attumen-the-huntsman](url)
The encounter starts when you attack Midnight, and Attumen spawns when the horse hit 95% health. At 25% of Midnight's health, Attumen should mount Midnight and continue fighting, but does not. Both can reach 1 health and are unkillable.

**Comment by fvicaria** [comment]
This is another example where the players are doing damage faster than it was anticipated and phases are being messed up.

**Comment by Brunnr** [comment]
For comparison's sake, the group that normally runs this does pretty average damage, maybe 12000 DPS for the entire party. Next time will go slower to see if that helps. If I can help any in doing test runs and can include recount screen shots of each attempt, just let me know.
