### ISSUE TITLE
[Mage] Blink Spell

### ISSUE THREAD

**Issue by Th3AnG3L** [WoWManiaUK/Redemption#5941]
Hello, there is an bug with Mage Skill Blink teleport
When you use the blink teleport inside water you go underground and fail and die
When you use blink teleport from water to ground again you go under map and fail and die
When you use blink teleport you go after wall , other side or sometimes die

**Comment by GMZinius** [comment]
Thank you @Th3AnG3L for reporting this issue 

This is a known core issue, and can not be fixed at this time
