### ISSUE TITLE
Rogue quest : Sad Truth. Problem with Chests

### ISSUE THREAD

**Issue by Dolanoth** [WoWManiaUK/Redemption#5942]
**Links:**

**What is Happening:**
i cannot picklock chests in quest : Sad Truth in Amani Catacombs. The writing ,,locked'' is in red colour.

**What Should happen:**
I could open those chests to get head, a quest item to complete the Sad Truth quest

**Comment by GMZinius** [comment]
Thank you for reporting @Dolanoth 
Please follow [the "how to ](https://github.com/WoWManiaUK/Redemption/wiki/How-to-Properly-Report-an-Issue)

Note: The chest with the head quest item will be the one that is sparkling
