### ISSUE TITLE
The Air Strikes Must Continue [Quest Item not work]

### ISSUE THREAD

**Issue by Th3AnG3L** [WoWManiaUK/Redemption#5943]
**Links:**
Quest name: [The Air Strikes Must Continue](https://www.wowhead.com/quest=11533/the-air-strikes-must-continue)
https://www.wowhead.com/npc=25033/eredar-sorcerer
- The quest give you an quest item to slain eradar-sorcerer that are in high positions, but the item not work
- Good that i was mage and with blizzard skill with hard options i kill them

**What is Happening:**
- The quest item not working against them

**What Should happen:**
- the quest item should strike them instant and kill

**Comment by GMZinius** [comment]
Thank you for reporting @Th3AnG3L 
We will get this looked into

**Comment by Greywolf59** [comment]
It works perfectly fine. Tested on PTR, done it countlss times before on live too.
Be sure to talk with Ayren Cloudbreaker https://www.wow-mania.com/armory/?npc=25059 using "Speaking of action, I've been ordered to undertake an airstrike." You ill be provided automated fly mount for the qust.
