### ISSUE TITLE
[NPC] Reanimated Frost Wyrm 26841 / Weakened Reanimated Frost Wyrm 27821

### ISSUE THREAD

**Issue by Th3AnG3L** [WoWManiaUK/Redemption#5944]
**Links:**
https://www.wowhead.com/wotlk/quest=12459/that-which-creates-can-also-destroy

**What is Happening:**
Monster  Weakened Reanimated Frost Wyrm - Is spawned in the sky and i cannot use the quest item to make him weakener.

**What Should happen:**
The quest item should work on him and make him weakener

**Comment by Greywolf59** [comment]
When I click on the wowhead link you have provided here and read throguh the comments, I can see that basically every player mentions that th wyrms are flying. If I look on the screenshots of the wyrm, I can see it flying. One comment specifically mentions it is hard to reach them and that you have to be basically directly under the wyrm so the quest item can reach it. Done this quest many times. You just need patience, try to look for some elevated spot around or above which one of the wyrms flies.

**Comment by GMZinius** [comment]
Thank you for reporting @Th3AnG3L 
This was fixed here https://github.com/WoWManiaUK/Redemption/issues/1674 before

**Comment by Th3AnG3L** [comment]
yes i understand but here is what happened,
the monster was in air - okay, but when i try use the item it says "Invalid target" even i got under him to try much closer and so one nothing happened still invalid target but when i go under him he start attack me and i cannot use the item. GM enter and assist me he use the item to make him weaker like the Fix link you show it was inside the ground but with skill we started fighting and complete, the point is to avoid gm assistance

**Comment by GMZinius** [comment]
Found the issue @Rushor 

there is a bad respawn 
- should'nt be hovering and already weakened

![image](https://user-images.githubusercontent.com/108176634/204412531-b58ed8b3-6a3a-4efe-ab21-7c32d81ab455.png)

![image](https://user-images.githubusercontent.com/108176634/204412697-df0d74da-5eeb-4774-bf8b-9408e18398b0.png)

Notes
only invalid target when a player tries to use the quest item on an already weaken one

![image](https://user-images.githubusercontent.com/108176634/204412799-25638429-9018-47b2-b26b-f5141cca8d39.png)

**Comment by Rushor** [comment]
Incorrect spawn of entry: 27821 removed

**Comment by GMZinius** [comment]
Fix confirmed on PTR 

![image](https://user-images.githubusercontent.com/108176634/206523408-a99edf6c-970e-43b1-a8ec-98e0fcf828d4.png)

**Comment by Lumber-Jack-2** [comment]
2 new issues that have not been addressed yet

- creature should be far visible and active upon entry update
- wyrm should attack from far distance once hit by the quest item. people with no fly mount cannot even engage those creatures

not a regression, its extended issue only

**Comment by Echinaceax** [comment]
Confirmed extra issues fixed in PTR 
They attack
Used quest item on them

Objective complete 
https://i.gyazo.com/513c57be5dda96a24c6e6cf76c241da0.mp4

![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/ee115e39-9ee4-4e4f-b45d-2187fc7490f8)
