### ISSUE TITLE
Vi'el NPC

### ISSUE THREAD

**Issue by Th3AnG3L** [WoWManiaUK/Redemption#5945]
**Links:**
https://www.wowhead.com/classic/npc=16015/viel

**What is Happening:**
- I couldn't find the NPC at the zone

**What Should happen:**
Can you make one NPC in some town or other shops to have option to sell item Felcloth

**Comment by GMZinius** [comment]
The NPC is actually here @Th3AnG3L 
I do believe by reading comments that it is a phasing and timing issue 

![image](https://user-images.githubusercontent.com/108176634/204564393-ea096ddd-7da1-4dc6-8b73-93dbc71d8b50.png)
