### ISSUE TITLE
Chill out mon - Quest item Snow of eternal slumber not working

### ISSUE THREAD

**Issue by Th3AnG3L** [WoWManiaUK/Redemption#5946]
**Links:**
https://www.wowhead.com/wotlk/quest=12137/chill-out-mon

**What is Happening:**
When you become ghost and loot the chest to obtain the Snow of eternal slumber item, then you go back to living and you need to use the item on the ghosts, but nothing happens

**What Should happen:**
when using on the ghost they revive and go to their bodies and finish the quest

**Comment by GMZinius** [comment]
Thank you for reporting @Th3AnG3L 

This issue was confirmed working by the GM 
Please make sure your Mania client is updated

**Comment by Th3AnG3L** [comment]
i was with the GM and we try everything, log out run as admin again clear cache teleport me to other position then back nothing helps the item manual not working for me, for him it was working he sow that, no addons effect also the issue.
That's why i reported it :)

**Comment by GMZinius** [comment]
Yes I just tested this myself to @Th3AnG3L 

I myself could complete it in Living mode only, after clicking the gossip text from NPC Gan'jo
I also found a video showing they also did it on only Living mode https://www.wowhead.com/wotlk/quest=12137/chill-out-mon#videos:id=233594

**Comment by Th3AnG3L** [comment]
i know i need to loot the bodies, but first you need to use the quest item to the ghosts that was the issue it was not happening nothing :)

**Comment by GMZinius** [comment]
> i know i need to loot the bodies, but first you need to use the quest item to the ghosts that was the issue it was not happening nothing :)

Yes, I have recently spoken to the GM that helped you.
