### ISSUE TITLE
Quest "The First and the Last" - speak with NPC not working

### ISSUE THREAD

**Issue by Th3AnG3L** [WoWManiaUK/Redemption#5947]
**Links:**
https://www.youtube.com/watch?v=RYH9_Xrnt7I&ab_channel=Murilo_HM

**What is Happening:**
The NPC doesn't give "?" to click on it to give the quest.. quest also says "Group"
https://ibb.co/60fXLv4

**What Should happen:**
When take the quest "The First and the Last" - you need to speak with NPC

**Comment by Greywolf59** [comment]
I see you are a DK and the NPC is unfriendly. Try to finish the DK quest line fully 1st.

**Comment by Th3AnG3L** [comment]
there is no other quest to do, i follow the quests and this is the next quest

**Comment by Greywolf59** [comment]
If you'd have finished the quest line, the NPC wouldn't be orange but green. Have you checked at the King again? If so I guess try to ask GM for help, I have done the DK quest line plus this one quest a week ago on PTR and it worked fine.
