### ISSUE TITLE
[Spell] [Mage] Molten Armor acts as talented with Molten Shields on default

### ISSUE THREAD

**Issue by Greywolf59** [WoWManiaUK/Redemption#5948]
**Links:**
Molten Armor: https://www.wow-mania.com/armory/?spell=43046
Molten Shields: https://www.wow-mania.com/armory/?spell=13043
Proof:
https://ibb.co/qd516qS
https://ibb.co/QKXmQzw

**What is Happening:**
Molten Armor damages attackers using ranged and spell attacks. Tested on PTR with Echinacea.

**What Should happen:**
Without the talent it should affect only melee ability hits.

Arguments against this post:
Molten Armor tooltip does say: "Causes 170 Fire damage when hit,..." It does not specify what kind of hits.

Arguments for this post:
Molten Shields talent says: "...In addition, your Molten Armor has a 100% chance to affect ranged and spell attacks." That would be redundant if the molten armor was supposed to affect them even without the talent.

Wowwiki patch note https://wowwiki-archive.fandom.com/wiki/Molten_Armor
[Patch 2.1.0](https://wowwiki-archive.fandom.com/wiki/Patch_2.1.0) (22-May-2007): Molten Armor will no longer be triggered erroneously by some non-melee attacks, such as Feral Faerie Fire.

This suggest that at least at TBC it was meant to affect only melee.

mmo-champion discussion: https://www.mmo-champion.com/threads/650415-Molten-Shields
5th comment, Magoman, 2009-05-30: "As said, the damage triggers on all melee attacks.
With molten shields it also triggers on ranged attacks (shots and ranged abilities) and spells. And its only single target spells like shadow bolt and fireball - not dot ticks or aoe dmg*. Therefore - the talent is just useless for PvE."
 *NOTE: other sources claim it procs from the 1st tick of DoT spells

https://www.wowhead.com/wotlk/spell=13043/molten-shields#comments
People in the molten shields comment section discuss what ranged attacks and spells it might affect, which would mean the untalented Mage Armor does not affect those kind of attacks at all.

I can also provide proof that it affects ranged attacks from mobs if needs be. Tested Molten Armor rank 1 and rank 3, with glyph of Molten Armor and without it. Also with minor glyph of Fire Ward and without it. Results are the same, it affects both ranged hits and spells without being specced into Molten Shields.

**Comment by GMZinius** [comment]
Thank you for reporting @Greywolf59 

Molten Armor https://www.wow-mania.com/armory/?spell=43046 (working as it should)
![image](https://user-images.githubusercontent.com/108176634/205664394-e1bae9ed-ef59-4ae2-8c37-34d5bd523419.png)

Molten Shields https://www.wow-mania.com/armory/?spell=11094 
![image](https://user-images.githubusercontent.com/108176634/205665087-157adbd6-c2d8-4332-8b03-ee7a57fa3ba8.png)


**Notice that in your screenshots you are talking about 2 different things** 

I believe that you are mixing up the Molten Armor and the Fire Ward https://www.wow-mania.com/armory/?spell=43010
`Causes your Fire Ward and Frost Ward spells to have a 15% chance to reflect the warded spell while active.`


See screenshot of the combat log you gave it says: "Molten armor" not "Fire Ward" 
So nothing stated about the Molten Shields / Fire Ward

**Comment by Greywolf59** [comment]
I have statet that yes, tooltip does not specify the kind of hit, I have admitted it. You compeltely omitted the second sentence in the Molten Shields talent which is point of my report. "In addition, your Molten Armor has a 50% (or 100%) chance to affect ranged and spell attacks." Why would taht sentence be there if Molten Armor would be supposed to affect those kind of attack from the start? You are the one confusing it. Fire Ward is another spell and it does not causes any damage to the attacker. Fire Ward absorbs the damage taken and if talented and/or glyphed it has a cahnce to reflect the spell back.
Molten Shields talent improves both Molten Armor and Fire ward.

**Comment by Greywolf59** [comment]
Some sauce info after further testing
Molten Armor Reacts with:
Holy school - proven by Exorcism in PvP at OP
Arcane School  - proved in the video
Shadow School - tested on [Malefic Necromancer](https://www.wow-mania.com/armory/?npc=31155) with [Shadow Bolt](https://www.wow-mania.com/armory/?spell=34344)
Physical Ranged - tested on [Shandaral Hunter Spirit](https://www.wow-mania.com/armory/?npc=30864) with [Shoot](https://www.wow-mania.com/armory/?spell=6660) and with [Aimed Shot](https://www.wow-mania.com/armory/?spell=54615)

WIP

**Comment by Keader** [comment]
Try now pls

**Comment by Greywolf59** [comment]
Tested on PTR, Molten Armor does not do damage on ranged hits and basic spell hits (haven't tried all the forms of spells) without the talent. Looks fixed.
