### ISSUE TITLE
[NPC | Raid] Icecrown mini boss dogs getting pulled together

### ISSUE THREAD

**Issue by Airin258** [WoWManiaUK/Redemption#5949]
**Links:**
https://www.wowhead.com/wotlk/npc=37217/precious
https://www.wowhead.com/wotlk/npc=37025/stinky

**What is Happening:**
Whenever any of dogs is pulled, second one aggroed instantly and runs to raid with insane speed. This causes a lot of wipes due to the way their mechanics work.
This happens no matter which dog is pulled (originally saw on Precious pulls, but 10 minutes ago also on Stinky). Happened on every difficulty: today my guild did 10 nm and 25 hc and both raid same thing happened. Issue is present for a while, around week or two, but i was not sure if it is someone else pulling. Someone in raid made suggestion that it can be related to 2 other types of npc close to dogs.

**What Should happen:**
Dogs are should be able to pull indepndently, like all other mobs.

Sadly, i did not record the pulls and i'm not sure if i will be able to in closest week so reporting it without proofs, however i have 9 other ppl who i can point you to.
The way how very last one happened, when i got sure that it is not ninja pull from someone on other side, is when i pulled Stinky (which was farther down the hallway) on hunter talented into additional range in raid where only other ranged was shadow priest. I was spamming shot button to make sure that noone will do any sort of trick and not get us two dogs... Yet, it happened. It would be simply numerically impossible for any player to do so.

**Comment by Rushor** [comment]
On PTR i could not reproduce that https://i.imgur.com/44dYnbp.jpeg

**Comment by fvicaria** [comment]
I don't think this is a big "issue" given ICC has been open for years now and player should be able to cope with it.
If it becomes a common understanding that this should be reviewed I am happy to re-open it.

**Comment by Airin258** [comment]
I will not agree with the fact that it is not a big issue because to be able to manage it ppl in raid should be Heavily overgeared.
But i will try to make a record of how it looks.

**Comment by Airin258** [comment]
Update: sadly i was not able to make record, however both me and main tank saw that Precious got pulled when Plague scientist nearby was aggroed. Dog was far down the hallway and normally out of range.
