### ISSUE TITLE
Recipe Formula Enchant Shield - Major Stamina

### ISSUE THREAD

**Issue by Th3AnG3L** [WoWManiaUK/Redemption#5952]
**Links:**
https://www.wowhead.com/wotlk/item=28282/formula-enchant-shield-major-stamina

**What is Happening:**
i have an issue regarding recipe Formula: Enchant Shield - Major Stamina
It should be sold from Madam Ruby in Shattercity but this recipe is missing in shop, where i can find it?

**What Should happen:**
The NPC should have recipe > Formula: Enchant Shield - Major Stamina for sell

**Comment by Echinaceax** [comment]
hi @Th3AnG3L 
This is a limited item, it has a spawn timer
so just keep visiting her and when it spawns you can buy it

https://wowwiki-archive.fandom.com/wiki/Madame_Ruby
![image](https://user-images.githubusercontent.com/39439201/207874053-15992e10-8a10-422f-8226-515c76b61e0b.png)

**Comment by Th3AnG3L** [comment]
from missing to limited time are 2 different stuff :)

**Comment by GMZinius** [comment]
> from missing to limited time are 2 different stuff :) limited items shows that are (0) cant buy and you need to wait

Hello @Th3AnG3L 
Echinacea is correct, this is a limited item 

It is on the vendor - I see it so it is'nt missing from vendor 
My mistake for not checking in game for you before reporting 

![image](https://user-images.githubusercontent.com/108176634/207891572-c553e6e7-7bda-4d7c-bdb2-8e5fd0e2c142.png)

**Comment by WhitephoenixTheBunny** [comment]
@Th3AnG3L actually, when limited item is sold out you don't see it anymore on the list.
You can see it faded out when you are the one buying, but once you close and reopen the vendor you don't see it anymore.

**Comment by Echinaceax** [comment]
> @Th3AnG3L actually, when limited item is sold out you don't see it anymore on the list. You can see it faded out when you are the one buying, but once you close and reopen the vendor you don't see it anymore.

Correct 😄 

bought 
![image](https://user-images.githubusercontent.com/39439201/207896381-14389e06-db69-4fd2-8fb3-2f893bceb9dd.png)
fade 
![image](https://user-images.githubusercontent.com/39439201/207896505-2a4e101a-a30e-4e7e-881c-bc63db7bc01a.png)
close/reopen vendor window = gone till respawn 
![image](https://user-images.githubusercontent.com/39439201/207896806-9b5eeccc-6bf0-46ac-84b1-6ef2f3d340c2.png)
