### ISSUE TITLE
Vorsha the Lasher

### ISSUE THREAD

**Issue by Granfatto** [WoWManiaUK/Redemption#5953]
[**Links:**]
(https://www.wowhead.com/wotlk/quest=6641/vorsha-the-lasher)

**What is Happening:**

The quest giver Muglash doesn't move as the quest is accepted, he just stays still.

**What Should happen:**

The quest giver should move towards the objective where waves of nagas will spawn till the quest objective mob spawn (Vorsha the Lasher) in the end.
p.s.: the quest worked the first time but when i killed Vorsha the Lasher it didn't count, that's why i had to abandon the quest and try again. Since the 2nd try this new bug occured.

**Comment by Echinaceax** [comment]
hi @Granfatto 
i found an old report that has a lot of discussion here #3781 so i will reopen the other one and close this one 

thanks for reporting
