### ISSUE TITLE
[PVP] Wintergrasp 3 Alliance NPCs spawning with the horde NPCS after Horde wins the battle.

### ISSUE THREAD

**Issue by JormagMania** [WoWManiaUK/Redemption#5954]
**Links:** N/A
 

**What is Happening:** Alliance NPCs are spawning inside the horde controlled fortress after the battle is over. (might be the same with Horde NPCs spawning in Alliance controlled WG?)

**What Should happen:** Only Horde NPC should spawn if battle won by the Horde and vice versa if Alliance wins.

** This happened last week but only 1 was spawning, the commander. Looked like it was fixed, I saw no NPC yesterday but this morning, 3 of them are here. 

![Screenshot (3538)](https://user-images.githubusercontent.com/120397554/208121949-60c5bbcb-9455-47ae-b9b5-47d23e714b06.png)
![Screenshot (3537)](https://user-images.githubusercontent.com/120397554/208121955-62228639-215e-4226-8682-fcc397bcd99b.png)
![Screenshot (3539)](https://user-images.githubusercontent.com/120397554/208121958-639cd120-22d8-472e-9b3d-be8aa2ccc673.png)

Thank you.

Jormag.

**Comment by Echinaceax** [comment]
Ive seen last week the same issue to @JormagMania 

Tested PTR https://i.gyazo.com/7b3cf07076a3917f1869f27be82d9036.mp4 `not bubbed on PTR`

Only bugged on Live `still needs fixing for sure `

We can clearly see they are bugged on Live @Rushor 
Will ask @GMZinius for the npc info for you

**Comment by GMZinius** [comment]
> We can clearly see they are bugged on Live @Rushor Will ask @GMZinius for the npc info for you

Thank you @Echinaceax for the PM 
Confirmed bugged on Live indeed 

@Rushor here are the IDs 

![npc1](https://user-images.githubusercontent.com/108176634/208133952-898371ca-347e-4585-ad0c-3fd356b0884f.jpg)
![npc2](https://user-images.githubusercontent.com/108176634/208133968-16ba1e93-ea76-457d-974a-10ba361789fa.jpg)
![npc3](https://user-images.githubusercontent.com/108176634/208133985-83880f98-6e89-407f-9b9e-5d8ac5ae4abe.jpg)

**Comment by Rushor** [comment]
First fix added so that duplicates will no longer happen.

you can test this by manual spawning like: 

.npc add temp 31052

close to each other.

Only one will stay, the other will despawn. This will make sure we will not get any duplicates here anymore

**Comment by Rushor** [comment]
As far as i can see all the three bugged creatures are the ones with paths (walking around) 

Removed that for now, lets debug it and see if it was the reason for the issue.

**Comment by Echinaceax** [comment]
Ok tested @Rushor 

- [ ] Pathing disabled (for now) 
- [ ] Checked temp spawn (before battle start) https://i.gyazo.com/e21ce94cc1f0e620126f4456c9578ba1.mp4
- [ ] Checked questgivers still hide on battle start https://i.gyazo.com/f5f6f3110313713fa70efa3def4a053c.mp4

Good to go for Live test 
thanks :)
