### ISSUE TITLE
[Achievement] Crashin and trashing - progress doesnt work

### ISSUE THREAD

**Issue by D00MHaMM3R** [WoWManiaUK/Redemption#5956]
**Links:**
https://www.wowhead.com/achievement=1295/crashin-thrashin

**What is Happening:**
No achivement progress after crash, tested with the reward from questa, and with the one from the guides in youtube that you buy from dalaran stormwind and orgrimar vendors. You aim at the other cart, press the only provided button and on hit u get explosion, that must be a progress in the achievement. For some reason it doesnt count.

**What Should happen:**
Achivement progress and at 25 achivment :) 

P.S tested it with friend and with a GM Psygoa

**Comment by Rushor** [comment]
can slso be reproduced on ptr?

**Comment by Echinaceax** [comment]
> can also be reproduced on ptr?

lol speedy, havent got to test PTR yet 
will let you know asap 😄

**Comment by D00MHaMM3R** [comment]
Someone have eaten coffee beans in the morning :D

**Comment by Echinaceax** [comment]
Confirmed bugged on PTR @Rushor 

Crashin' Thrashin' Racer Controller https://www.wow-mania.com/armory/?item=37710
Blue Crashin' Thrashin' Racer Controllerhttps://www.wow-mania.com/armory/?item=54343

Tested in a group 
Summoned Crashin' Thrashin' Racer Controller for each char 
Summoned Crashin' Thrashin' Racer Controller for one and the Blue Crashin' Thrashin' Racer Controller for the other 
both toys spell Racer rocket slam not working, it casts but not affects https://www.wow-mania.com/armory/?spell=49297

same issue for you on live realm @D00MHaMM3R ?
https://i.gyazo.com/a59639329bd22bf8cd5d5678648369b0.mp4

**Comment by D00MHaMM3R** [comment]
You must aim at the other from afar and not stand next to each other, sometimes it works sometimes no. No progress tho in both situations

**Comment by Echinaceax** [comment]
> You must aim at the other from afar and not stand next to each other, sometimes it works sometimes no. No progress tho in both situations

Same as my video above (PTR) 
is there a chance you can pm me in discord @D00MHaMM3R so you can check Live with you?

**Comment by D00MHaMM3R** [comment]
Cannot now, im at work

**Comment by Echinaceax** [comment]
ok got extra info @Rushor 

1. they dont work in cities https://i.gyazo.com/a59639329bd22bf8cd5d5678648369b0.mp4
2. out of cities they work but dont count towards the achv count https://i.gyazo.com/6addfa0abc8e1f3d3fd3c21e7934aede.mp4

**Comment by D00MHaMM3R** [comment]
Acording to guides they work in the cities and outside them.

**Comment by Echinaceax** [comment]
> Acording to guides they work in the cities and outside them.

I know, thats why i added both videos @D00MHaMM3R 
will be fixes as soon as possible. thanks for reporting :)

**Comment by Rushor** [comment]
The spell is fixed now, when one racer is standing 30 yards away and starts racing towards another (in line) he will kill the other racer and player gets the credit

https://gyazo.com/7952d4c9ea3a1e8e27f01042d2c5b3e6

**Comment by Echinaceax** [comment]
confirmed fixed 

Spell fixed 
https://i.gyazo.com/885ffd62749a1aba9db316510322d18a.gif

Achv working 
![image](https://user-images.githubusercontent.com/39439201/208482939-29943726-9ffc-434b-ade0-9fa5e5146b71.png)


nice job :)
