### ISSUE TITLE
Crashin and trashin

### ISSUE THREAD

**Issue by herteg1** [WoWManiaUK/Redemption#5957]
**Links:**

**What is Happening:**Toy for achievement crashin' & thrashin' is not working, please fix it till Christmas event ends, thanks 

**What Should happen:** when you press spell 1 it should crash into each other but nothing is happening.

**Comment by Rushor** [comment]
Duplicate, will be fixed with next update

**Comment by Echinaceax** [comment]
Reported and fixed here @herteg1 https://github.com/WoWManiaUK/Redemption/issues/5956
