### ISSUE TITLE
[Item] Gaily Wrapped Present - giving empty gifts / doubles / triples 

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Redemption#5958]
**Links:**
https://www.wow-mania.com/armory/?item=21310#contains

**What is Happening:**

- I got 3 empty gifts from the Gaily Wrapped Present on 5 toons

![image](https://user-images.githubusercontent.com/39439201/209179519-dbbb5ec2-8839-4959-8765-70faa336f509.png)

**So I asked Phoenix to check her ally toons, we seen this bug ourselves.**

- Phoenix however got a lot of doubles and triples gifts from her Gaily Wrapped Present

![image](https://user-images.githubusercontent.com/39439201/209179323-93da4d1b-a00d-4da2-95e0-f95248c9c724.png)

Will confirm PTR bug soon when PTR is online 

**What Should happen:**

- [ ] The gift should not give empties/doubles or triples
it should give 1 of the 4 options 

![pets](https://user-images.githubusercontent.com/39439201/209190947-3ca4ce6f-0803-4a70-b137-5fe8a2e7d6df.jpg)

Note, once confirmed on PTR this should be hotfixed coz they only spawn today until 2nd january

**Comment by Rushor** [comment]
Confirmed bugged by watching how the loot was handled in db, there was always a high chance to get nothing.

now reference table is added and it will always contain 1 random item out of the 4 :)

**Comment by Echinaceax** [comment]
confirmed fixed on PTR 
https://i.gyazo.com/6397cd885980e6fe24d32e330aaac71a.mp4

![image](https://user-images.githubusercontent.com/39439201/209235128-0df456ec-3f5a-4364-a206-90a455dafa0c.png)
