### ISSUE TITLE
[NPC] Several Feast of Winter Veil missing

### ISSUE THREAD

**Issue by WhitephoenixTheBunny** [WoWManiaUK/Redemption#5959]
While reporting, and searching for another issue (to be posted after this one) I found out we are missing an NPC

**HORDE SIDE**
[Whulwert Copperpinch](https://www.wow-mania.com/armory/?npc=13431) should be in Thunder Bluff as we can see on the wowhead link from WoTLK retail [HERE](https://www.wowhead.com/wotlk/npc=13431/whulwert-copperpinch)
(edit) Also [Seersa Copperpinch](https://www.wow-mania.com/armory/?npc=13432) is missing
[Whulwert Copperpinch](https://www.wow-mania.com/armory/?npc=13431) is a quest giver

**ALLIANCE SIDE**
[Bessbi Jinglepocket](https://www.wow-mania.com/armory/?npc=23009) and [Wolgren Jinglepocket](www.wow-mania.com/armory/?npc=23010) are missing at Exodar.
 [Wolgren Jinglepocket](www.wow-mania.com/armory/?npc=23010) is a quest giver.

EDIT: forgot to take SS, will post later

**Comment by Echinaceax** [comment]
I gotcha @WhitephoenixTheBunny :P

Bug confirmed NPC missing in Thunder Bluff for the quest https://www.wow-mania.com/armory/?npc=13431#starts

![No npc quest pick up TB](https://user-images.githubusercontent.com/39439201/210148766-86b78e49-550e-4f66-a1d4-7bdc2cdad290.jpg)

**Comment by WhitephoenixTheBunny** [comment]
Updated, missing another NPC, good call on that to me check @Echinaceax

**Comment by Rushor** [comment]
Both npcs applied and bound to winter veil event

**Comment by WhitephoenixTheBunny** [comment]
@Rushor sorry, I found more missing

**Comment by Rushor** [comment]
added the missing ones

**Comment by Echinaceax** [comment]
Ally 
Exodar fix confirmed 
and quest tested while i was at it :)

![image](https://user-images.githubusercontent.com/39439201/210152084-cd6aa30c-4523-4f6c-871e-278ae3b3c627.png)
![image](https://user-images.githubusercontent.com/39439201/210152133-305e2c8c-c0df-4de9-834a-6688ce801a5a.png)

Horde 
Thunder bluff fix confirmed 

![image](https://user-images.githubusercontent.com/39439201/210152202-b14d52b5-439d-4ba8-887e-2d2ddbb5af20.png)
