### ISSUE TITLE
[QUEST] Great-father Winter is Here! (ID 7021 & 7024)

### ISSUE THREAD

**Issue by WhitephoenixTheBunny** [WoWManiaUK/Redemption#5960]
Quest [Great-father Winter is Here!](https://www.wow-mania.com/armory/?quest=7021) (that should be) given by [Whulwert Copperpinch](https://www.wow-mania.com/armory/?npc=13431) at Thunder Bluff (previous report) and [Great-father Winter is Here!](https://www.wow-mania.com/armory/?quest=7024) given by [Nardstrum Copperpinch](https://www.wow-mania.com/armory/?npc=13429) at Undercity can't be turned at [Great-father Winter](https://www.wow-mania.com/armory/?npc=13445) at Orgrimmar. 
Checking the WoW Mania Armory link, we can see they both send us to Ironforge, whereas they should send us to Orgrimmar.

EDIT: also missing SS, will post later

**Comment by Echinaceax** [comment]
Bug confirmed 
Picked up from Undercity and cant deliver to ORG like it says to 

![UC to ORG ](https://user-images.githubusercontent.com/39439201/210148923-1924ed5c-4cbb-4267-bbe5-da8d6fe13118.jpg)

**Comment by Rushor** [comment]
issue was that the alliance winter father was assigned for quest reward here instead the horde one, maybe worth a check the alliance quests aswell,

above mentioned are fixed now

**Comment by Echinaceax** [comment]
[Whulwert Copperpinch](https://www.wow-mania.com/armory/?npc=13431) confirmed all good 
![image](https://user-images.githubusercontent.com/39439201/210152441-c4149601-c0d7-4e2d-bf8d-7fd923df2e71.png)

[Nardstrum Copperpinch](https://www.wow-mania.com/armory/?npc=13429) confirmed all good 
![image](https://user-images.githubusercontent.com/39439201/210152488-87836d99-c701-4eac-8ee5-d9b09c768194.png)
