### ISSUE TITLE
[Quest] The Battle For Undercity - Quest is not starting 

### ISSUE THREAD

**Issue by Teemo93** [WoWManiaUK/Redemption#5961]
**Links:**https://www.wow-mania.com/page/armory 

**What is Happening:**   wotlk (h) quest is not starting at all.  Quest name: The Battle For Undercity 

**What Should happen:**
So, I am infront of Undercity where I have to click on Thrall in order to start the quest, but nothing is happening and that is it... 
my wow-mania acc character name is Pyrosflame
This is my first time doing this quest. 
And this is my first time reporting a bug in this website so I may have made some mistakes here and there...
Looking forward for your response

Cheers

**Comment by Echinaceax** [comment]
Thanks for reporting @Teemo93 
We will check this out and see if we can reproduce the issue

Can you give us anymore helpful information please

Did DC or do anything at all after picking up the quest?

**Comment by Teemo93** [comment]
Hello again, 

No dc, or anything just picked up the quest went to undercity from the portal to meet voljin and thrall, I'm clicking to talk to thrall and nothing,  it is suppose to start after talking to him, but it just stands still... thats it

**Comment by Echinaceax** [comment]
Ok, i just finished testing this, i did the whole questline from 

**Step 1: Recruiting the Taunka**

1.) [Into the Fold](https://www.wowhead.com/wotlk/quest=11978)
2.) [Blood Oath of the Horde](https://www.wowhead.com/wotlk/quest=11983)
3.) [Agmar's Hammer](https://www.wowhead.com/wotlk/quest=12008)

**Step 2: Destroy the Nerubians**

1.) [Victory Nears...](https://www.wowhead.com/wotlk/quest=12034)
2.) [From the Depths of Azjol-Nerub](https://www.wowhead.com/wotlk/quest=12036)
3.) [The Might of the Horde](https://www.wowhead.com/wotlk/quest=12053)
4.) [Attack by Air!](https://www.wowhead.com/wotlk/quest=12071)
5.) [Blightbeasts be Damned](https://www.wowhead.com/wotlk/quest=12072)

**Step 3: Annexing the Taunka**

1.) [Strength of Icemist](https://www.wowhead.com/wotlk/quest=12063)
2.) [Chains of the Anub'ar](https://www.wowhead.com/wotlk/quest=12064)
3.) [Return of the High Chief](https://www.wowhead.com/wotlk/quest=12069)
4.) [All Hail Roanauk!](https://www.wowhead.com/wotlk/quest=12140)

**Step 4: The Forsakens New Plague**

1.) [Imbeciles Abound!](https://www.wowhead.com/wotlk/quest=12189)
2.) [The Forsaken Blight and You: How Not to Die](https://www.wowhead.com/wotlk/quest=12188)
3.) [Emerald Dragon Tears](https://www.wowhead.com/wotlk/quest=12200)
4.) [Spread the Good Word](https://www.wowhead.com/wotlk/quest=12218)
5.) [The Forsaken Blight](https://www.wowhead.com/wotlk/quest=12221)

**Step 5: The Red Dragonflight**

1.) [The Kor'kron Vanguard!](https://www.wowhead.com/wotlk/quest=12224)
2.) [Audience With The Dragon Queen](https://www.wowhead.com/wotlk/quest=12496)
3.) [Galakrond and the Scourge](https://www.wowhead.com/wotlk/quest=12497)
4.) [On Ruby Wings](https://www.wowhead.com/wotlk/quest=12498)

**Step 6: Victory Over the Scourge?**

1.) [Return to Angrathar](https://www.wowhead.com/wotlk/quest=12500)
BONUS! [Wrath Gate In-Game Cinematic/Machinima](http://files.filefront.com/WOW+Wrathgate+1024avi/;11881764;/fileinfo.html) outside link to view it
BONUS! [Achievement: Veteran of the Wrath Gate!](https://www.wowhead.com/wotlk/achievement=547)

**Step 7: The Betrayal**

1.) [Darkness Stirs](https://www.wowhead.com/wotlk/quest=13242)
2.) [Herald of War](https://www.wowhead.com/wotlk/quest=13257)
3.) [A Life Without Regret](https://www.wowhead.com/wotlk/quest=13266)
4.) [The Battle for the Undercity](https://www.wowhead.com/wotlk/quest=13267)

https://i.gyazo.com/0da330660c979577399ce5b52f8f7779.mp4

**Comment by Rushor** [comment]
Maybe it is the same issue like the Harrison Jones one back in the days?

**Comment by Teemo93** [comment]
![sylvanas is missing](https://user-images.githubusercontent.com/121767659/210213454-6ae24db0-9a1e-40b1-a3e3-cfd550371819.png)


roflmao
The problem is that he has a Sylvanas on the picture and I don't XDDD

**Comment by Echinaceax** [comment]
> Maybe it is the same issue like the Harrison Jones one back in the days?

Could be a reset issue yes rushor if a player before failed the quest in someway.

what i did notice while testing this is that Sylvanas pathing, she goes through the wall after she's captured by the demon in the hallway https://i.gyazo.com/2158f6ceed48951bbcfd82df42ac90ed.mp4

@Teemo93 
and you are using mania client and your up to date ?

**Comment by Teemo93** [comment]
Yes, a mania client, but I'm not sure if its up to date... hmm


![image](https://user-images.githubusercontent.com/121767659/210217009-6d8b373d-e72e-4908-9757-4a3cce8bec9c.png)

**Comment by Echinaceax** [comment]
Yes ur up to date @Teemo93 good to know thanks :)

![image](https://user-images.githubusercontent.com/39439201/210217638-8c505946-0f98-450c-a8c5-e539e99ff363.png)

**Comment by Echinaceax** [comment]
@Rushor 
will see if i can get it to bug somehow like we did with the others that do simular to this

**Comment by Teemo93** [comment]
You're welcome, good to know.

I really hope that we can fix this problem... xD

**Comment by Echinaceax** [comment]
Yes that happens after server restart @Teemo93

**Comment by Teemo93** [comment]
oh.... I see.
Let's hope that it will be fixed then ^_^

**Comment by Echinaceax** [comment]
@Rushor 
think i got it, but i only could get both to bug and not just Sylv by herself 

**Reproduce** 

1, Take the quest and start event, then logout - no issue
2, Log back in, and wait for event to recomence - no issue

**issues start here**
3, Abandon quest - event still continues even though player doesnt have quest anymore https://i.gyazo.com/79fb2c75018fe486d1602ada2d6b5da0.mp4
4, Dont follow Thrall - still get damage at start even though im not with them https://i.gyazo.com/c5938dbe5d40d3e24a1f81a2cbd98e4d.mp4
5, Wait at the start for event to end 
6, After i didnt follow them, Sylv and Thrall get stuck 
https://i.gyazo.com/deeaa874dae1181c2a9fe50dc8517109.mp4
https://i.gyazo.com/9e32ab57d1d0f8b46b41569ca252797e.mp4
7, .die Thrall to reset him - respawns ok
https://i.gyazo.com/d28a8ef3ad14e5514edfcbc293fbf709.mp4
8, .die Sylv to reset her - 9, She doesnt reset with her horse...
https://i.gyazo.com/f24b98642cae99eed54413eca739e015.mp4

9, logged new char and ran the event, Sylv pathing really messed up
Sylv in midd air https://i.gyazo.com/3c7acb2440dcbe49ba84d1b46fc93737.mp4
Sylv running on the same spot a lot https://i.gyazo.com/3c7acb2440dcbe49ba84d1b46fc93737.mp4
10, This bugged to now, Thrall didnt blow rocks away now, they run through them https://i.gyazo.com/aac770737405d2812aa2d8626669ff4d.mp4
11, the chat gossip, and Sylv position delayed now https://i.gyazo.com/232d5c8bd98e57eb221f3e319da8cd13.mp4
13, Thrall and Sylv are facing the wrong way now https://i.gyazo.com/4a369ad98a2792585ddea34cd67a32fc.mp4
12, Thrall and Sylv bugged and not continuing the event https://i.gyazo.com/090efe0bff295d7d67746191ee6899d6.mp4


Need reset fixing if quest fails - not just respawn for Thrall and Sylv

**Comment by fvicaria** [comment]
I am pretty sure this was working.

**Comment by Echinaceax** [comment]
> I am pretty sure this was working.

Not when it bugs its not, found a lot wrong with it actually

**Comment by Rushor** [comment]
> the timer at the beginning is blizzlike if i remember correct when i added the script
> added that she will mount after respawn
> sadly we cannot add a complete event reset, else there will be more bugs, we will fix the correct respawn for sylvanas here only now

**Comment by Echinaceax** [comment]
> > 1. the timer at the beginning is blizzlike if i remember correct when i added the script
> > 2. added that she will mount after respawn
> > 3. sadly we cannot add a complete event reset, else there will be more bugs, we will fix the correct respawn for sylvanas here only now

- [ ]  sylvanas respawn checked, Respawn is better 

Sad that the other issues cannot be addressed.
Hopfully the event doesnt bug again ...we shall see
