### ISSUE TITLE
Double XP Weekend (One Character)

### ISSUE THREAD

**Issue by x71NKx** [WoWManiaUK/Redemption#5962]
**Links:**

**What is Happening:**
During Double XP Weekend one of my characters, Ballzonchin (Blood Elf Mage), does not receive the Double XP buff. I can hop onto one of my other characters and see the dual wield icon that shows I am receiving the Double XP buff.

**What Should happen:**
My Mage should also get double xp. I think...

**Comment by GMZinius** [comment]
Hello @x71NKx 
This is not the place for this issue, please make an ingame ticket 
Thank you
