### ISSUE TITLE
[NPC] Monstrous Kaliri - Evading and movement

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Redemption#5963]
**Links:**
https://www.wow-mania.com/armory/?npc=23051

Needed for daily cooking quest Revenge is Tasty https://www.wow-mania.com/armory/?quest=11377

**What is Happening:**

- Bird is evading  https://i.gyazo.com/444dbbe28e553e1539e2642ab0206bb4.mp4
- Low numbers spawned (need to check how many are actually spawned)
- jumpy movement  https://i.gyazo.com/f2da23ae6b96eed260461841fb2a2214.mp4    
- leaving player incombat https://i.gyazo.com/f66df65c23e88d01ceebad355351b927.mp4
- loot table, only has the quest item at 33% and no other loot at all
https://www.wowhead.com/npc=23051/monstrous-kaliri

**What Should happen:**

- [x] Birds shouldnt evade
- [x] More spawns (30 spawned)
- [x] Smoother flight movement
- [x] Leaving player incombat after mob is dead
- [x] loot table fixing

![image](https://user-images.githubusercontent.com/39439201/211875980-b6c25369-e92f-48b7-b7c0-f0ed87a3d296.png)

Test on PTR also 
https://i.gyazo.com/6262e9e30039f75b52f1312c344d70ee.mp4
https://i.gyazo.com/b524e3127aef9dc5538be4791fb0e8af.mp4
https://i.gyazo.com/0c06d3d411255d16a81f85b792103e76.mp4

**Comment by Rushor** [comment]
i think it is related to the inhabittype, changed so he can above above the terrains and not evade

**Comment by GMZinius** [comment]
Fix confirmed on PTR 
I see quest item loot % much better
