### ISSUE TITLE
[NPC] Ice Sphere - Missing player target guid

### ISSUE THREAD

**Issue by hammereddann** [WoWManiaUK/Redemption#5964]
**What is Happening:**
Ice Sphere's do not have a target when they are focused to someone

**What Should happen:**
Ice sphere should show its target it is beaming to.

**Comment by GMZinius** [comment]
**Link**
https://www.wow-mania.com/armory/?npc=36633
Timestamp 2:33 https://www.youtube.com/watch?v=8ybTns292Qk

**Comment by Rushor** [comment]
creature should now show the target guid

**Comment by Rushor** [comment]
@hammereddann do you mean a target frame shown in the ui or only the visual beam?

**Comment by hammereddann** [comment]
@Rushor the ice sphere is supposed to show its target. This is not shown. If you click the sphere it should have a player frame who it is beaming to

**Comment by svijetlo** [comment]
> @hammereddann do you mean a target frame shown in the ui or only the visual beam?

if you have option to see target of your target ,  ones you take Frozen orbs as target that LK cast in phase transition you should see who orb is targeting

**Comment by hammereddann** [comment]
![image](https://user-images.githubusercontent.com/122736582/213815324-6183ed5c-8963-4037-b36d-5ab558c57a1e.png)

These Shpere's should show a target like this but they are not showing 1

**Comment by Rushor** [comment]
That function is added to the core, if that is not working then it is related to the reaction behaviour of the orb which we cannot change

**Comment by Echinaceax** [comment]
@hammereddann 
Fixed as far as we can see now (on PTR) 

![image](https://user-images.githubusercontent.com/39439201/213882600-ce246cde-ba02-40e4-a984-aa31f37cb407.png)
