### ISSUE TITLE
[Spell] Deterrence - Not working correctly

### ISSUE THREAD

**Issue by hammereddann** [WoWManiaUK/Redemption#5966]
**Links:**
https://wowwiki-archive.fandom.com/wiki/Deterrence
https://www.wow-mania.com/armory/?spell=19263

**What is Happening:*
 Spells and others getting through Detterence after its popped. E.g - Heroic throw, Ambush, Cheap shot, Aimed shot, Serpent sting and others. 

**What Should happen:**
100% parry chance, 100% chance ranged attacks will hit you and grants 100% chance to deflect spells. Patch update - 3.2.0 - 04/Aug/2009
![image](https://user-images.githubusercontent.com/122736582/213037925-b8f19047-a5a4-4c43-957a-1df49a47e106.png)

**Comment by hammereddann** [comment]
Added another link for your attention :)

**Comment by hammereddann** [comment]
The cooldown on Wow-Mania Armory also states a CD at 1.5 minutes.

**Comment by KyptAMaN** [comment]
What am I reading????? Who did this post???? this is miss information!!!! 
Heroic Throw, ambush and cheap shot are able to go through deterrence!!! 
This just explains how much this devs dont know anything about PvP 3.3.5 . sad

Also, Intercept Stun still bugged since 2020, gj so far on NOT fixing it. 
Also, Heroic Throw damage is bugged, doing no dmg at all... im talkin about PvP . a guy with 0 resi, and HT hitting for 2k or less.

**Comment by hammereddann** [comment]
> What am I reading????? Who did this post???? this is miss information!!!! Heroic Throw, ambush and cheap shot are able to go through deterrence!!! This just explains how much this devs dont know anything about PvP 3.3.5 . sad
> 
> Also, Intercept Stun still bugged since 2020, gj so far on NOT fixing it. Also, Heroic Throw damage is bugged, doing no dmg at all... im talkin about PvP . a guy with 0 resi, and HT hitting for 2k or less.

Read the tooltip on Deterrence and reply please :)

**Comment by Echinaceax** [comment]
> This just explains how much this devs dont know anything about PvP 3.3.5 . sad

No dev has even looked into this yet @KyptAMaN 
I play Hunter also and there is defo something off with Deterrence with the attacks from the back

**Comment by KyptAMaN** [comment]
Overpower, heroic throw, cheap shot, ambush, chaos bolt, all this are spells that go through Deterrence.
Know what you are talkin about. dont talk randomly .

**Comment by hammereddann** [comment]
> Overpower, heroic throw, cheap shot, ambush, chaos bolt, all this are spells that go through Deterrence. Know what you are talkin about. dont talk randomly .

Show proof that they should go through and I'm sure they won't mind reviewing it

**Comment by hammereddann** [comment]
Found info on Trinitycore.
