### ISSUE TITLE
Ice Sphere's 

### ISSUE THREAD

**Issue by hammereddann** [WoWManiaUK/Redemption#5967]
**Links:**
![image](https://user-images.githubusercontent.com/122736582/213813937-94515996-6c33-4185-b49c-898d72756391.png)

**What is Happening:**
Ice Sphere has no target

**What Should happen:**
When anyone targets the Ice Sphere it should show the name of its target!

**Comment by Echinaceax** [comment]
OP reposted to https://github.com/WoWManiaUK/Redemption/issues/5964#issuecomment-1399022378
