### ISSUE TITLE
[Quest/Pala] The Tome of Valor - NPC bug when player dies/quest fails

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Redemption#5968]
**Reported to the dev team by a GM** 

bug confirmed on PTR 

**Links:**
Quest https://www.wow-mania.com/armory/?quest=1651
NPC https://www.wow-mania.com/armory/?npc=6182

**What is Happening:**

- [x] If player dies but leave the failed quest in their questlog, The 3 waves of Defilers continiue, so each time she respawns she spawns with her gun, and gets killed by the new wave of defilers. 
https://i.gyazo.com/0dfdf11cba0bd30284cd86a9554654cb.mp4
- [x] If player abandons the quest, the waves still continues after she respawns (until all 3 waves are done)
- [x] retaking the quest states that her gun and ammo are in the house, and runs to get them 😄 so she is auto in combat when she respawns.
https://i.gyazo.com/e815249f126e9a8d9f9462e20cfae722.mp4

![image](https://user-images.githubusercontent.com/39439201/214891174-01c7a93c-0407-4961-9197-abf2905ce7bd.png)

**What Should happen:**
full reset after quest failed or abandoned quest for defilers and Daphne

this is her when shes not bugged and has reset correctly https://i.gyazo.com/3a11e8b1aacc13e3b1c8677b47640428.mp4

**Comment by Rushor** [comment]
Added the improvement that the quest will reset correctly now once she died, no more (old) spawns after quest accepted, when the previous event was not fully done.

Added that the summons (bandits) will despawn whne the questcreature dies.

Added that the quest will fail when the questcreature dies.

The equip visual issue is as-is for now

Those should all solve the core issue of this quest

**Comment by Echinaceax** [comment]
Confirmed in PTR 

Accept quest good spawn no gun 
https://i.gyazo.com/5de50be72a69f17763d3a4fa24f54aeb.mp4
NPC dies, quest fails, attackers despawn `Fixed`
https://i.gyazo.com/995989a319f0a5a2200f0fb41d9660db.mp4
No attackers spawn when quest fails, and player still has quest in log `Fixed`
https://i.gyazo.com/fb3028f78d46b7b831b336a9cadb67da.mp4
When player dies, npc dies, quest fail, Attacters despawn smoothly `Fixed`
https://i.gyazo.com/03aec472fb452133f1bcfdeff10b06db.mp4 
Abandon failed quest (just for full check)
https://i.gyazo.com/5f41d05abbcec42283730a39664d1c6c.mp4

### noticed something (5 mins respawn timer on quest back) 

![image](https://user-images.githubusercontent.com/39439201/215294213-9875688d-7121-4c37-ab1c-d1972f9f87ae.png)
![image](https://user-images.githubusercontent.com/39439201/215294222-2fa2efe3-6255-4af4-b38f-539a0d555885.png)


here at timestamp 3:15  https://www.youtube.com/watch?v=8AuZuRXlmis
- [ ] Respawn issue after quest complete 
Ours https://i.gyazo.com/9b834b3ec726919237a74a9b0528fc69.mp4

**Comment by Rushor** [comment]
respawns almost instant after quest event has been done now

**Comment by Echinaceax** [comment]
Smooth despawn - respawn after quest fails 
https://i.gyazo.com/f517c882e3288ac0d441ea138284db95.mp4

Despawn - respawn after quest complete 
https://i.gyazo.com/8ab8731a9a9c805a52f8e3e22d048aae.mp4
