### ISSUE TITLE
Binary resistance

### ISSUE THREAD

**Issue by Hajzlopuc** [WoWManiaUK/Redemption#5969]
**Links:**

https://github.com/WoWManiaUK/Redemption/issues/2961

**What is Happening:**

Binary resistance doesn't exist at all. People with 0 spell penetration never miss (get 'Resist') their spells, cc, purges, interrupts or anything magic based against character with 270 or even more resistances.

**What Should happen:**
People with 0 spell pen should sometimes fully miss (get resisted) their spells when they shoot character with resistances.

**Comment by GMZinius** [comment]
Thank you for reporting this @Hajzlopuc 
Keader replied to the other post you linked https://github.com/WoWManiaUK/Redemption/issues/2961
nothing has change via the core side of this issue so I do not think it is fixable still 

I will look into this with Keader and if changes can be made we will reopen the https://github.com/WoWManiaUK/Redemption/issues/2961 report as it has a lot more information on it 

Thank again 
I will close this one
