### ISSUE TITLE
[Quest] Stinky's Escape

### ISSUE THREAD

**Issue by DarkestDuck** [WoWManiaUK/Redemption#597]
http://www.wowhead.com/quest=1270/stinkys-escape

It is supposed that you protect the guy while he is looking for Bogbean Leaves and then escort him to safe place, but he just says "Ok, lets get started" and stands doing nothing.

I tried this quest by several different characters and waited for a reasonable long time, but result is the same.

This is reopen of #572 

P.S. This quest has a distinct version for Alliance and for the Horde. I tried only Horde version, Alliance's quest might be ok.

**Comment by Emcitementz** [comment]
Also fixed forr the Alliance version.
