### ISSUE TITLE
[INSTANCE] Hall Of Reflection Normal, Last wall not breaking.

### ISSUE THREAD

**Issue by JormagMania** [WoWManiaUK/Redemption#5970]
**Links:**
N/A

**What is Happening:** After killing the last wave of adds, Sylvannas does not break the last wall, she keeps hitting the wall with arrows until Lich King catches up and kills us all. I died and started the last past of the dungeon 4 times and it stayed bugged every single time. Seems like the ID was bug, even if I restarted the event. 

** Of Note ** When I started playing on this server and I came to do my first HOR NM run, around November 2022, the first thing I was told in the group was "NO PETS, NO TOTEMS otherwise it will/might bug the event". I had removed my totem macro from my bars and had no totems whatsoever. I usually never do HOR NM, I solo HOR HC with my 5 accounts and never encountered this issue. Today, I was boosting my new paladin and was looking to get a cloak from NM. Even though I did a HOR NM run last night, there was no issues, today, it bugged out. I have no idea what causes this, I opened up a ticket, Psyoga was able to witness the whole thing and asked me to make a report.

![Screenshot (3734)](https://user-images.githubusercontent.com/120397554/215863769-07d43a02-8030-48ce-b19e-9ded6fc9d5e9.png)

Just sitting here, no mobs left to kill as they already dead, yet the dungeon does not proceed to letting us pass as it should.

**What Should happen:** After killing the last wave of adds, Sylvannas should start her RP and break the wall, run to the ledge, which leads into succeeding the dungeon and getting the Captain Chest reward.

Thank you.

Jormag.

**Comment by GMZinius** [comment]
Thank you @JormagMania for reporting this issue
We will take a look at this 👍

**Comment by JormagMania** [comment]
Update: I just noticed that I was still in a "raid" from my ICC rep farm from earlier, it might be why it bugged the event?

**Comment by Echinaceax** [comment]
@Rushor we will check this info out first :)

**Comment by fvicaria** [comment]
hard to believe. more likely some corner case was hit.

**Comment by Rushor** [comment]
i think so aswell, the instance works since years. was this a very fast run ?

**Comment by JormagMania** [comment]
Hard to say, I do have very good DPS for a NM run, either too quick on the kills or it was the raid that bugged the event as there is a quest linked to escaping LK. Even though I did not have the quest, maybe the game won't let you do the quest in a raid and this is what happens. 

Update: I joined RDF from my raid of 5 people to test this theory and the RDF converted me into a group, I just did HOR NM and same result, last wall not breaking. I left my totems behind on purpose this time. Last time I walked there this is why I stayed in a "raid' but this time the raid was cancelled by RDF. SO far, 5 x the last event, 5 x bugged.

**Comment by JormagMania** [comment]
Update: did it again, killed 2 of my toons to go slower, worked.

**Comment by GMZinius** [comment]
> Update: did it again, killed 2 of my toons to go slower, worked.
> 
> Could the gap between LK and Sylvannas or the mobs be an issue? If I kill too fast, then I end up super far away from LK when I kill the last mobs and maybe due to the range, the event does not register the mobs as dead because I am just too far away from LK.

Can confirm while watching, that you were a lot father away that players usually are
Me and Psygoa do agree that the range between you and the LK could be the issue 

I will close this for now and if we get more players with the same issue. we can reopen it @JormagMania 

Thank you again for reporting this

**Comment by Rushor** [comment]
Keep it slower and all will be good :)
