### ISSUE TITLE
[Object] Shipment of Animal Parts - Low spawns

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Redemption#5973]
**Links:**
`Mania spawns`
5 https://www.wow-mania.com/armory/?object=188015
1 https://www.wow-mania.com/armory/?object=188016
4 https://www.wow-mania.com/armory/?object=188017
1 https://www.wow-mania.com/armory/?object=188018

`Wowhead -wotlk`
22 https://www.wowhead.com/wotlk/object=188015/shipment-of-animal-parts
21 https://www.wowhead.com/wotlk/object=188016/shipment-of-animal-parts
23 https://www.wowhead.com/wotlk/object=188017/shipment-of-animal-parts
22 https://www.wowhead.com/wotlk/object=188018/shipment-of-animal-parts

`Quest `
https://www.wowhead.com/wotlk/quest=11871/not-on-our-watch

**What is Happening:**

- [ ] We have only 11 spawns in total from 4 object IDs above 
 

**What Should happen:**
There should be 56 spawns in total, we are trying to find info on how many should be randomly spawned tho

Reported by a player to a GM
Confirmed by Me and Phoenix

**Comment by Rushor** [comment]
I think those objects spawn by killing the creatures aswell so wowhead data may be wrong here

**Comment by Echinaceax** [comment]
> I think those objects spawn by killing the creatures aswell so wowhead data may be wrong here

Yes but they is ID https://www.wowhead.com/wotlk/item=35222/shipment-of-animal-parts from https://www.wowhead.com/wotlk/npc=25843/northsea-thug

**Comment by Rushor** [comment]
added more spawns, not as much as wowheas says, that would be way too much, but it total it's 70 objects now, way better i think

**Comment by Echinaceax** [comment]
Confirmed Fixed on PTR 

![image](https://user-images.githubusercontent.com/39439201/218329843-e2c5bab4-ab93-47dc-bf7a-125c859e2383.png)
![image](https://user-images.githubusercontent.com/39439201/218329865-bdd52013-fcec-428e-b443-37fabf3bada4.png)
![image](https://user-images.githubusercontent.com/39439201/218329890-ab972aec-78ad-4977-8512-11e6f6271155.png)
![image](https://user-images.githubusercontent.com/39439201/218329940-02df0b4e-dbb5-4827-807a-13d941b5d075.png)
