### ISSUE TITLE
[Quests / NPC / loot / event] Crushing the Crown

### ISSUE THREAD

**Issue by WhitephoenixTheBunny** [WoWManiaUK/Redemption#5975]
Event: [Love is in the air](https://www.wow-mania.com/armory/?event=423)

During the Event, we will have a daily called "[Crushing the Crown](https://wow-mania.com/armory/?search=crushing+the+crown#0+3+1+2)", this daily will be adapted to the player level.
The requirements will be similar **Chemical Wagon Destroyed** and killing 5 mobs; those mobs will be diferente on the level ranges.

The issue is, for the mobs levels, the loot isn't correct, for example, for the level +71 quest, mobs are droping loot for the level 5 /14 quests.

Link of mobs with their loot in mania vs wowhead

**_Quest level 5_**

Alliance: [Crushing the Crown](https://wow-mania.com/armory/?quest=24658)
Horde: [Crushing the Crown](https://wow-mania.com/armory/?quest=24638)

Mob Mania: [Crown Lackey](https://wow-mania.com/armory/?npc=37214)
Mob WH: [Crown Lackey](https://www.wowhead.com/npc=37214/crown-lackey)

**_Quest level 14_**

Alliance: [Crushing the Crown](https://wow-mania.com/armory/?quest=24659)
Horde:[ Crushing the Crown](https://wow-mania.com/armory/?quest=24645)

Mob Mania: [Crown Thug](https://wow-mania.com/armory/?npc=37917)
Mob WH: [Crown Thug](https://www.wowhead.com/npc=37917/crown-thug)

**_Quest level 23_**

Alliance: [Crushing the Crown](https://wow-mania.com/armory/?quest=24660)
Horde:[ Crushing the Crown](https://wow-mania.com/armory/?quest=24647)

Mob Mania: [Crown Duster](https://wow-mania.com/armory/?npc=37984)
Mob WH: [Crown Duster](https://www.wowhead.com/npc=37984/crown-duster)

**_Quest level 32_**

Alliance: [Crushing the Crown](https://wow-mania.com/armory/?quest=24662)
Horde: [Crushing the Crown](https://wow-mania.com/armory/?quest=24648)

Mob Mania: [Crown Hoodlum](https://wow-mania.com/armory/?npc=38006)
Mob WH: [Crown Hoodlum](https://www.wowhead.com/npc=38006/crown-hoodlum)

**_Quest level 41_**

Alliance: [Crushing the Crown](https://wow-mania.com/armory/?quest=24663)
Horde: [Crushing the Crown](https://wow-mania.com/armory/?quest=24649)

Mob Mania: [Crown Agent ](https://wow-mania.com/armory/?npc=38016)
Mob WH: [Crown Agent ](https://www.wowhead.com/npc=38016/crown-agent)

**_Quest level 51_**

Alliance: [Crushing the Crown](https://wow-mania.com/armory/?quest=24664)
Horde: [Crushing the Crown](https://wow-mania.com/armory/?quest=24650)

Mob Mania: [Crown Sprinkler](https://wow-mania.com/armory/?npc=38023)
Mob WH: [Crown Sprinkler](https://www.wowhead.com/npc=38023/crown-sprinkler)

**_Quest level 61_**

Alliance: [Crushing the Crown](https://wow-mania.com/armory/?quest=24665)
Horde: [Crushing the Crown](https://wow-mania.com/armory/?quest=24651)

Mob Mania:[ Crown Underling](https://wow-mania.com/armory/?npc=38030)
Mob WH: [Crown Underling](https://www.wowhead.com/npc=38030/crown-underling)

**_Quest level 71_**

Alliance: [Crushing the Crown](https://wow-mania.com/armory/?quest=24666)
Horde: [Crushing the Crown](https://wow-mania.com/armory/?quest=24652)

Mob Mania:[ Crown Sprayer](https://wow-mania.com/armory/?npc=38032)
Mob WH: [Crown Sprayer](https://www.wowhead.com/npc=38032/crown-sprayer)

**Comment by Rushor** [comment]
if someone wanna help, i need a list of all items sorted by npc from wowhead in order to fix this properly

**Comment by WhitephoenixTheBunny** [comment]
[Crown Lackey](https://www.wowhead.com/npc=37214/crown-lackey)

Money: 3silver 66 copper

0.06% https://www.wowhead.com/item=5572/small-green-pouch
0.05% https://www.wowhead.com/item=805/small-red-pouch
0.04% https://www.wowhead.com/item=5571/small-black-pouch
0.11% https://www.wowhead.com/item=3609/plans-copper-chain-vest
0.15% https://www.wowhead.com/item=8180/hunting-bow?bonus=6655
0.09% https://www.wowhead.com/item=3036/heavy-shortbow?bonus=6655
0.3% https://www.wowhead.com/item=2773/cracked-shortbow?bonus=6657
0.14% https://www.wowhead.com/item=6520/pioneer-cloak
0.1% https://www.wowhead.com/item=4662/journeymans-cloak
0.09% https://www.wowhead.com/item=6514/disciples-cloak
0.06% https://www.wowhead.com/item=4658/warriors-cloak
0.05% https://www.wowhead.com/item=4665/burnt-cloak
0.01% https://www.wowhead.com/item=6508/infantry-cloak
0.01% https://www.wowhead.com/item=4677/veteran-cloak
0.3% https://www.wowhead.com/item=1429/patchwork-cloak?bonus=6656
53% (1-3) https://www.wowhead.com/item=2589/linen-cloth
0.17% https://www.wowhead.com/item=2959/journeymans-boots
0.11% https://www.wowhead.com/item=2960/journeymans-gloves
0.09% https://www.wowhead.com/item=4663/journeymans-belt
0.09% https://www.wowhead.com/item=9744/simple-bands
0.05% https://www.wowhead.com/item=3641/journeymans-bracers
0.01% https://www.wowhead.com/item=7350/disciples-bracers
0.3% https://www.wowhead.com/item=1433/patchwork-armor?bonus=6656
0.3% https://www.wowhead.com/item=3370/patchwork-belt?bonus=6656
0.3% https://www.wowhead.com/item=1430/patchwork-gloves?bonus=6656
0.2% https://www.wowhead.com/item=3373/patchwork-bracers?bonus=6656
0.2% https://www.wowhead.com/item=1427/patchwork-shoes?bonus=6656
0.18% https://www.wowhead.com/item=1431/patchwork-pants?bonus=6656
0.05% https://www.wowhead.com/item=21003/unkempt-bracers?bonus=6656
0.09% https://www.wowhead.com/item=2140/carving-knife
0.4% https://www.wowhead.com/item=2138/sharpened-letter-opener?bonus=6657
5% https://www.wowhead.com/item=4604/forest-mushroom-cap
2% https://www.wowhead.com/item=159/refreshing-spring-water
0.01% https://www.wowhead.com/item=8766/morning-glory-dew
0.7% https://www.wowhead.com/item=8181/hunting-rifle
0.18% https://www.wowhead.com/item=8182/pellet-rifle
0.2% https://www.wowhead.com/item=2774/rust-covered-blunderbuss?bonus=6657
1.6% https://www.wowhead.com/item=774/malachite
0.07% https://www.wowhead.com/item=23333/shattered-power-core
0.06% https://www.wowhead.com/item=20812/tattered-pelt
0.18% https://www.wowhead.com/item=3200/burnt-leather-bracers
0.17% https://www.wowhead.com/item=2963/burnt-leather-boots
0.09% https://www.wowhead.com/item=4690/hunting-belt
0.09% https://www.wowhead.com/item=6518/pioneer-boots
0.07% https://www.wowhead.com/item=4666/burnt-leather-belt
0.06% https://www.wowhead.com/item=2964/burnt-leather-gloves
0.04% https://www.wowhead.com/item=9750/nomad-sash
0.02% https://www.wowhead.com/item=6268/pioneer-tunic?bonus=6654
0.3% https://www.wowhead.com/item=1418/worn-leather-belt?bonus=6656
0.3% https://www.wowhead.com/item=1419/worn-leather-boots?bonus=6656
0.3% https://www.wowhead.com/item=1420/worn-leather-bracers?bonus=6656
0.3% https://www.wowhead.com/item=1423/worn-leather-pants?bonus=6656
0.3% https://www.wowhead.com/item=1425/worn-leather-vest?bonus=6656
0.2% https://www.wowhead.com/item=1422/worn-leather-gloves?bonus=6656
0.2% https://www.wowhead.com/item=4659/warriors-girdle
0.15% https://www.wowhead.com/item=3214/warriors-bracers
0.8% https://www.wowhead.com/item=2635/loose-chain-belt?bonus=6656
0.3% https://www.wowhead.com/item=2642/loose-chain-boots?bonus=6656
0.16% https://www.wowhead.com/item=2643/loose-chain-bracers?bonus=6656
0.16% https://www.wowhead.com/item=2646/loose-chain-pants?bonus=6656
0.14% https://www.wowhead.com/item=2648/loose-chain-vest?bonus=6656
0.11% https://www.wowhead.com/item=2645/loose-chain-gloves?bonus=6656
0.05% https://www.wowhead.com/item=5466/scorpid-stinger
0.09% https://www.wowhead.com/item=768/lumberjack-axe
0.2% https://www.wowhead.com/item=1416/rusty-hatchet?bonus=6657
0.01% https://www.wowhead.com/item=1516/worn-hatchet?bonus=6657
0.4% https://www.wowhead.com/item=4563/billy-club
0.04% https://www.wowhead.com/item=766/flanged-mace
0.3% https://www.wowhead.com/item=1415/carpenters-mallet?bonus=6657
0.01% https://www.wowhead.com/item=4560/fine-scimitar
0.01% https://www.wowhead.com/item=727/notched-shortsword
0.2% https://www.wowhead.com/item=1413/feeble-sword?bonus=6657
0.01% https://www.wowhead.com/item=1511/commoners-sword?bonus=6657
1.6% https://www.wowhead.com/item=118/minor-healing-potion
0.07% https://www.wowhead.com/item=9753/nomad-buckler?bonus=6655
0.01% https://www.wowhead.com/item=7109/pioneer-buckler
0.19% https://www.wowhead.com/item=2213/worn-large-shield?bonus=6657
0.14% https://www.wowhead.com/item=2212/cracked-buckler?bonus=6657
0.3% https://www.wowhead.com/item=767/long-bo-staff
0.3% https://www.wowhead.com/item=1411/withered-staff?bonus=6657
0.11% https://www.wowhead.com/item=2598/pattern-red-linen-robe
0.2% https://www.wowhead.com/item=3189/wood-chopper
0.18% https://www.wowhead.com/item=4562/severing-axe?bonus=6655
0.3% https://www.wowhead.com/item=1417/beaten-battle-axe?bonus=6657
0.3% https://www.wowhead.com/item=3190/beatstick
0.5% https://www.wowhead.com/item=1414/cracked-sledge?bonus=6657
0.04% https://www.wowhead.com/item=8178/training-sword?bonus=6655
0.3% https://www.wowhead.com/item=1412/crude-bastard-sword?bonus=6657

**Comment by WhitephoenixTheBunny** [comment]
[Crown Thug](https://www.wowhead.com/npc=37917/crown-thug) 98 drops

Money: 1silver 40copper

0.02% https://www.wowhead.com/item=805/small-red-pouch
0.01% https://www.wowhead.com/item=4496/small-brown-pouch
0.02% https://www.wowhead.com/item=3036/heavy-shortbow?bonus=6655
0.01% https://www.wowhead.com/item=8180/hunting-bow?bonus=6655
0.3% https://www.wowhead.com/item=2780/light-hunting-bow?bonus=6657
0.01% https://www.wowhead.com/item=2777/feeble-shortbow?bonus=6657
0.09% https://www.wowhead.com/item=9786/raiders-cloak?bonus=6654
0.02% https://www.wowhead.com/item=6514/disciples-cloak
0.01% https://www.wowhead.com/item=9779/bandit-cloak
0.01% https://www.wowhead.com/item=14167/buccaneers-cape?bonus=6654
0.01% https://www.wowhead.com/item=4701/inscribed-cloak?bonus=6654
0.2% https://www.wowhead.com/item=1766/canvas-cloak?bonus=6656
34% (1-3) https://www.wowhead.com/item=2589/linen-cloth
32% (1-2) https://www.wowhead.com/item=2592/wool-cloth
0.03% https://www.wowhead.com/item=4306/silk-cloth
0.08% https://www.wowhead.com/item=2970/spellbinder-pants?bonus=6654
0.07% https://www.wowhead.com/item=6528/spellbinder-robe?bonus=6654
0.01% https://www.wowhead.com/item=7350/disciples-bracers
0.01% https://www.wowhead.com/item=6543/willow-bracers?bonus=6654
0.01% https://www.wowhead.com/item=6538/willow-robe?bonus=6654
0.4% https://www.wowhead.com/item=3376/canvas-belt?bonus=6656
0.4% https://www.wowhead.com/item=1767/canvas-gloves?bonus=6656
0.4% https://www.wowhead.com/item=1764/canvas-shoes?bonus=6656
0.3% https://www.wowhead.com/item=1768/canvas-pants?bonus=6656
0.3% https://www.wowhead.com/item=1770/canvas-vest?bonus=6656
0.17% https://www.wowhead.com/item=3377/canvas-bracers?bonus=6656
0.16% https://www.wowhead.com/item=1769/canvas-shoulderpads?bonus=6656
0.01% https://www.wowhead.com/item=2632/curved-dagger
0.01% https://www.wowhead.com/item=4571/war-knife
0.4% https://www.wowhead.com/item=2764/small-dagger?bonus=6657
0.01% https://www.wowhead.com/item=6347/formula-enchant-bracer-minor-strength
11% https://www.wowhead.com/item=4605/red-speckled-mushroom
6% https://www.wowhead.com/item=1179/ice-cold-milk
0.02% https://www.wowhead.com/item=4604/forest-mushroom-cap
0.01% https://www.wowhead.com/item=8766/morning-glory-dew
0.01% https://www.wowhead.com/item=159/refreshing-spring-water
0.4% https://www.wowhead.com/item=2781/dirty-blunderbuss?bonus=6657
0.01% https://www.wowhead.com/item=2778/cheap-blunderbuss?bonus=6657
0.3% https://www.wowhead.com/item=1210/shadowgem
0.1% https://www.wowhead.com/item=6557/bards-boots?bonus=6654
0.07% https://www.wowhead.com/item=3205/inscribed-leather-bracers?bonus=6654
0.02% https://www.wowhead.com/item=9750/nomad-sash
0.01% https://www.wowhead.com/item=3207/hunting-bracers
0.01% https://www.wowhead.com/item=9781/bandit-pants?bonus=6654
0.01% https://www.wowhead.com/item=2961/burnt-leather-vest?bonus=6654
0.01% https://www.wowhead.com/item=6379/inscribed-leather-belt?bonus=6654
0.01% https://www.wowhead.com/item=9757/nomad-tunic?bonus=6654
0.3% https://www.wowhead.com/item=1788/patched-leather-boots?bonus=6656
0.3% https://www.wowhead.com/item=1789/patched-leather-bracers?bonus=6656
0.3% https://www.wowhead.com/item=1791/patched-leather-gloves?bonus=6656
0.3% https://www.wowhead.com/item=1792/patched-leather-pants?bonus=6656
0.3% https://www.wowhead.com/item=1793/patched-leather-shoulderpads?bonus=6656
0.2% https://www.wowhead.com/item=1794/patched-leather-jerkin?bonus=6656
0.18%https://www.wowhead.com/item=1787/patched-leather-belt?bonus=6656
0.01% https://www.wowhead.com/item=2406/pattern-fine-leather-boots
0.08% https://www.wowhead.com/item=9784/raiders-boots?bonus=6654
0.07% https://www.wowhead.com/item=6547/soldiers-gauntlets?bonus=6654
0.02% https://www.wowhead.com/item=9759/cadet-boots
0.01% https://www.wowhead.com/item=2967/warriors-boots
0.01% https://www.wowhead.com/item=2977/veteran-armor?bonus=6654
0.3% https://www.wowhead.com/item=1743/laced-mail-pants?bonus=6656
0.2% https://www.wowhead.com/item=1738/laced-mail-belt?bonus=6656
0.2% https://www.wowhead.com/item=1739/laced-mail-boots?bonus=6656
0.17% https://www.wowhead.com/item=1745/laced-mail-vest?bonus=6656
0.15% https://www.wowhead.com/item=1740/laced-mail-bracers?bonus=6656
0.15% https://www.wowhead.com/item=1742/laced-mail-gloves?bonus=6656
0.15% https://www.wowhead.com/item=1744/laced-mail-shoulderpads?bonus=6656
0.01% https://www.wowhead.com/item=1730/worn-mail-belt?bonus=6656
0.01% https://www.wowhead.com/item=15927/bright-sphere?bonus=6655
0.01% https://www.wowhead.com/item=4568/grunt-axe?bonus=6655
0.5% https://www.wowhead.com/item=1816/unbalanced-axe?bonus=6657
0.07% https://www.wowhead.com/item=2079/sergeants-warhammer?bonus=6655
0.01% https://www.wowhead.com/item=15222/barbed-club?bonus=6655
0.4% https://www.wowhead.com/item=1815/ornamental-mace?bonus=6657
0.08% https://www.wowhead.com/item=2078/northern-shortsword
0.01% https://www.wowhead.com/item=3740/decapitating-sword?bonus=6655
0.5% https://www.wowhead.com/item=1817/stock-shortsword?bonus=6657
0.01% https://www.wowhead.com/item=1511/commoners-sword?bonus=6657
4% https://www.wowhead.com/item=858/lesser-healing-potion
1.6% https://www.wowhead.com/item=2455/minor-mana-potion
0.01% https://www.wowhead.com/item=6572/defender-shield?bonus=6655
0.01% https://www.wowhead.com/item=3651/veteran-shield?bonus=6655
0.13% https://www.wowhead.com/item=2216/simple-buckler?bonus=6657
0.09% https://www.wowhead.com/item=2217/rectangular-shield?bonus=6657
0.01% https://www.wowhead.com/item=2213/worn-large-shield?bonus=6657
0.01% https://www.wowhead.com/item=767/long-bo-staff
0.7% https://www.wowhead.com/item=1813/chipped-quarterstaff?bonus=6657
0.01% https://www.wowhead.com/item=4346/pattern-heavy-woolen-cloak
0.01% wowhead.com/item=4348/pattern-phoenix-gloves
0.4% https://www.wowhead.com/item=1812/short-handled-battle-axe?bonus=6657
0.01% https://www.wowhead.com/item=1417/beaten-battle-axe?bonus=6657
0.02% https://www.wowhead.com/item=4570/birchwood-maul?bonus=6655
0.5% https://www.wowhead.com/item=1814/battered-mallet?bonus=6657
0.01% https://www.wowhead.com/item=1414/cracked-sledge?bonus=6657
0.2% https://www.wowhead.com/item=4567/merc-sword?bonus=6655
0.01% https://www.wowhead.com/item=3196/edged-bastard-sword?bonus=6655
0.01% https://www.wowhead.com/item=3192/short-bastard-sword?bonus=6655
0.3% https://www.wowhead.com/item=1811/blunt-claymore?bonus=6657

**Comment by Rushor** [comment]
Delay for next week, adding the loot groups takes more time than expected, but it will be a solid fix then.

**Comment by Rushor** [comment]
jani informed to apply the fix, active after restart of ptr

The drop chances for all different npcs have been adjusted like it's been presented in wowhead. All have different loot drops now.

**Comment by Echinaceax** [comment]
Fix confirmed in PTR 

[Crown Lackey](https://wow-mania.com/armory/?npc=37214)
![image](https://user-images.githubusercontent.com/39439201/222985122-6b3f38f3-de9a-4fb1-af58-004d9b72cd8d.png)

[Crown Thug](https://wow-mania.com/armory/?npc=37917)
![image](https://user-images.githubusercontent.com/39439201/222985431-fc08267d-2b4e-487d-b625-e34a3f565bde.png)

[Crown Duster](https://wow-mania.com/armory/?npc=37984)

**Comment by Rushor** [comment]
alright  fix applied now, yeah the drop chance for any loot is 1-5 percent now, but it's adjusted to the level range :)

**Comment by Echinaceax** [comment]
> alright fix applied now, yeah the drop chance for any loot is 1-5 percent now, but it's adjusted to the level range :)

much better :)

[Crown Agent](https://wow-mania.com/armory/?npc=38016)

![image](https://user-images.githubusercontent.com/39439201/223081489-724ab3b4-457c-42ed-94ee-8f6785e8053e.png)

**Comment by WhitephoenixTheBunny** [comment]
**_Quest level 71_**

Alliance: [Crushing the Crown](https://wow-mania.com/armory/?quest=24666)
Horde: [Crushing the Crown](https://wow-mania.com/armory/?quest=24652)

Mob Mania:[ Crown Sprayer](https://wow-mania.com/armory/?npc=38032)
Mob WH: [Crown Sprayer](https://www.wowhead.com/npc=38032/crown-sprayer)

those are still giving wrong drop, didn't check yet the others
![image](https://github.com/WoWManiaUK/Redemption/assets/31921098/366bef13-3238-46e5-9705-68f77791fcb9)

**Comment by Echinaceax** [comment]
> those are still giving wrong drop, didn't check yet the others

Its not "still" though @WhitephoenixTheBunny  i did check them remember 

![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/042d644e-f7ff-41b7-8626-82ddf3abaf5d)

something reverted these somehow after the fix went live

**Comment by Lumber-Jack-2** [comment]
reapplied the fix now

**Comment by Echinaceax** [comment]
![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/6bbb85c2-9265-4210-9fb5-fe60607d3580)
![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/cba84c95-6e10-4add-b4e0-a395cf8668b5)
