### ISSUE TITLE
[Quests / NPC ] Crushing the Crown report 2

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Redemption#5976]
**Crown Thug** 
Mania: https://wow-mania.com/armory/?npc=37917
WH: https://www.wowhead.com/npc=37917/crown-thug 
- [x] They have buffs they shouldnt have ID 68946 and 68589 2 shotting an undergeared 80 test toon Silverpine Forest
https://i.gyazo.com/575b7ddb29818bae1cbce3159c60341a.mp4

**Crown Duster** 
Mania: https://wow-mania.com/armory/?npc=37984
WH: https://www.wowhead.com/npc=37984/crown-duster
- [x] Wrong level for the zone

**Crown Hoodlum**
Mania: https://wow-mania.com/armory/?npc=38006
WH: https://www.wowhead.com/npc=38006/crown-hoodlum
- [x] Wrong level for the zone

**Comment by Rushor** [comment]
fixed once jani has restarted ptr :)

**Comment by Echinaceax** [comment]
Fix confirmed on PTR 

![image](https://user-images.githubusercontent.com/39439201/218325048-1e915eee-7f33-4724-9074-fa4856de7ea4.png)
![image](https://user-images.githubusercontent.com/39439201/218325088-77fded03-145b-4006-ba80-ef6c07aa3e10.png)
![image](https://user-images.githubusercontent.com/39439201/218325156-8cbc812b-7a03-4dbb-8c1c-e0f998149766.png)
