### ISSUE TITLE
Herbs respawn rate

### ISSUE THREAD

**Issue by SorfHalas** [WoWManiaUK/Redemption#5978]
**Links:**

**What is Happening:**
In southshore/Tarren mill the river that runs up and down through the area life root doesnt spawn regularly or in abundance with no one else in the area farming i have still yet to see a respawn after 15 mins. with ore its alot faster and in more abondance because no one is farming lower level areas. 

**What Should happen:**
from running from the ocean of southshore to the damn in eastern plaugue lands after running up and down the area 1 or 2 should respawn.

**Comment by Echinaceax** [comment]
Item https://www.wow-mania.com/armory/?item=3357
