### ISSUE TITLE
[World] BT graveyard (Wintergrasp)

### ISSUE THREAD

**Issue by D0gmeat** [WoWManiaUK/Redemption#598]
As i'm sure many of the players know, the graveyard located at BT does no resurrect anyone, end having to fly to the next available grave site, which at the beginning of a game is located all the way to the south, also not sure how many this happens to, but after using the portal to get back to Dalaran the game with crash upon leaving the Karin Tor building.
Hope these can be addressed
Many thanks
Dogmeat x

**Comment by fvicaria** [comment]
The game crash is on you. You need to fix you Texture filtering settings and make sure you have all of our updates.

**Comment by Plege** [comment]
on this note, how can i make sure that i have all of your updates? would that also fix the visual bug i'm having with many items not being displayed?

**Comment by D0gmeat** [comment]
are they not included in the latest client torrent? I only downloaded the game three weeks ago

**Comment by fvicaria** [comment]
Always start the Launcher as admin and wait for the updates.

**Comment by D0gmeat** [comment]
Used the launcher for the first time today, it doesn't so anything, says downloading, but after an hour nothing had happened

**Comment by D0gmeat** [comment]
and texture filtering is turned down to low, per your advice.. still crashes

**Comment by wcslanker** [comment]
How is this still not fixed?

**Comment by wcslanker** [comment]
STILL NOT FIXED. why close it when it hasn't been done??

**Comment by D0gmeat** [comment]
^^

**Comment by fvicaria** [comment]
I have just tested them in Redemption and they work. Send me an image or something showing otherwise and I will look into it.

**Comment by wcslanker** [comment]
how do you expect me to get a screen shot of the spirit resser not ressing?

**Comment by rhadei** [comment]
I have a few images that might show that. Apologies for clunky UI in the images, it's usually a lot more minimal.

In the first image, I am dead at the Alliance fp graveyard, given 6 seconds to rez. My chat is timestamped, and you see the latest post is at 2:00PM.

Second image: The chat timestamp is at 2:01 PM, the Horde has capped SR, which they'd just attacked when I had 6 seconds to rez. I'm still dead in the same GY with no timer counting down. The time remaining in the Wintergrasp session is 26:31.

Last image: The relevant info here is the Time Remaining in WG, which is 25:57. Usually I don't just sit there for half a minute waiting, but I just wanted to show; in working GYs in the zone, the rez timer would start again if I'd missed one.

If one set of images is insufficient, I do a lot of WG as both Horde and Alliance and wouldn't mind collecting more. Thank you.

![firstwowscrnshot_012517_140101](https://cloud.githubusercontent.com/assets/25258454/22306880/f7bcceb6-e30e-11e6-8dca-bfdc265b632d.jpg)
![secondwowscrnshot_012517_140110](https://cloud.githubusercontent.com/assets/25258454/22306882/f7c4654a-e30e-11e6-8173-0287c7647525.jpg)
![thirdwowscrnshot_012517_140143](https://cloud.githubusercontent.com/assets/25258454/22306881/f7c040fa-e30e-11e6-97c8-0aff69694545.jpg)

**Comment by wcslanker** [comment]
WE HAVE PHOTO PROOF HERE^^ AND STILL NOT FIXED

**Comment by fvicaria** [comment]
![image](https://cloud.githubusercontent.com/assets/9414661/22432836/30ae451c-e70e-11e6-8545-c05c946d17e2.png)

**Comment by wcslanker** [comment]
You shouldn't have to click this.. THE COUNTDOWN FOR THE SPIRIT RESSER TO AUTOMATICALLY res you with full hp/mana does not work.

**Comment by wcslanker** [comment]
Just like any Battleground.

**Comment by Plege** [comment]
I think you should get your caps key fixed
