### ISSUE TITLE
[NPC] Brazie Getz - Missing

### ISSUE THREAD

**Issue by hammereddann** [WoWManiaUK/Redemption#5980]
**Links:**
https://wowpedia.fandom.com/wiki/Brazie_Getz
https://www.wow-mania.com/armory/?npc=37904
**What is Happening:**
This NPC is not spawning after Alliance kill Deathbringer Saurfang

**What Should happen:**
Brazie Getz is a [gnome](https://wowpedia.fandom.com/wiki/Gnome) [general goods](https://wowpedia.fandom.com/wiki/General_goods) vendor found at [Deathbringer's Rise](https://wowpedia.fandom.com/wiki/Deathbringer%27s_Rise) in [Icecrown Citadel](https://wowpedia.fandom.com/wiki/Icecrown_Citadel_(instance)) after the Alliance defeats [Deathbringer Saurfang](https://wowpedia.fandom.com/wiki/Deathbringer_Saurfang).

**Comment by GMZinius** [comment]
Thank you for reporting @hammereddann 
After our chat I also saw that other servers also havent scripted him either

 https://wowpedia.fandom.com/wiki/Brazie_Getz
![image](https://user-images.githubusercontent.com/108176634/220948667-8201d762-a17e-4a76-8ada-fc7588458613.png)

Let's see what @rushor thinks about it

**Comment by hammereddann** [comment]
Make wowmania even more great

**Comment by Rushor** [comment]
- spawning can be added
- prices can be changes

**Comment by Rushor** [comment]
- spawns added after death of saurfang (the real normal death, not .die)
- prices adjusted to be normal

**Comment by Echinaceax** [comment]
Fixed so far on PTR 

![image](https://user-images.githubusercontent.com/39439201/221372820-7ac7dfdb-0fc0-446a-96e3-7e94d62a3845.png)


- [ ] Brazie and Shely now spawn after the death of Deathbringer Saurfang
- [ ] Prices adjusted to be normal
- [ ] Gossip still a small issue

**Comment by Rushor** [comment]
unneeded gossip removed

**Comment by Echinaceax** [comment]
> unneeded gossip removed

perfect, all fixed in PTR 
https://i.gyazo.com/d730e70c6d3717e7485e1d0b96d35cde.mp4
