### ISSUE TITLE
[NPC] Auctioneer Stampi - Movement issue

### ISSUE THREAD

**Issue by GMZinius** [WoWManiaUK/Redemption#5981]
**Links:**
https://www.wow-mania.com/armory/?npc=8674

![image](https://user-images.githubusercontent.com/108176634/221362531-1cd2ace7-be93-426f-a67a-bd17ebc01fa4.png)

**What is Happening:**
NPC walking on the same spot 

**What Should happen:**
Should'nt be a moving NPC, other Auctioneers are stationary in Thunderbluff

Reported by player

**Comment by Echinaceax** [comment]
PTR check, hes not moving :)

https://i.gyazo.com/9e57d7891e56938ac1564979b958b502.mp4

**Comment by Rushor** [comment]
should be resolved

**Comment by Echinaceax** [comment]
Have verify it on live after update, thx
