### ISSUE TITLE
Corruption Spell

### ISSUE THREAD

**Issue by Necrosiss** [WoWManiaUK/Redemption#5982]
**Links:**
https://www.wow-mania.com/page/armory - Corruption Skill
https://www.wow-mania.com/page/armory - Trinket

It shows for everybody 1080 shadow damage per 18 sec. But when you're affli specced it stays 1464 to 1470 shadow damage per 18 sec. It is because of affli talents.

**What is Happening:**
Test has been done on a full PVE rogue. My lock has 3.5k sp, 140 spell penetration, tick from corruption on a rogue was 1.7k. Which makes it low already. Then my trinket popped, adding extra 768 spell power. I did refresh corruption to add that extra spell power to the tick and see results. That gave us 2k (so 768 spell power gave only 300 damage more?!?!) and maximum crit we could get on I would like to remind it zero resilience rogue was 4.2k which again make it very low as on spell power I have. Beside that it was 1 or 2 crits that we could only see on 18% crit chance which also make a chance to crit very low.

That means if the person will be full resilliance geared, corruption will hit maybe 1k. 

**What Should happen:**
What should happen is that Corruption damage spell should do more damage. Because of the lower damage, talents that help affli to regen hp are being usless since damage done is not enough to keep healing on the level. I would like to ask for a check of it if possible.

**Comment by WhitephoenixTheBunny** [comment]
Which trinket?

**Comment by Necrosiss** [comment]
Hi,

Sorry for some reason it doesn't show there. Trinket name *Charred Twilight
Scale. *A bit strange that such a boost in SP gives only 300 dmg in normal
tick.

**Comment by Necrosiss** [comment]
Charred Twilight Scale

**Comment by Echinaceax** [comment]
> Which trinket?

https://www.wow-mania.com/armory/?search=Charred+Twilight

**Comment by Hajzlopuc** [comment]
Hello,
I was actually curious so I tested this by myself talent by talent and every single talent worked as it should for me. It was probably bugged before, I know you are used to 8k corruption crits for years but it wasn't right at all. Also about spell power coeff, it's calculater per whole spell, not per 1 tick.

(I don't play this char at all for very long time so UI is a mess here) On screenshots watch damage number on dummy, and compare it to tooltip which considers all your talents, buffs on you and debuffs on target, 0 resil, level 80.

Base damage - https://puu.sh/JAt5D/68a3d584f5.jpg
+ Improved corruption 5/5 - https://puu.sh/JAt5K/9c60bf8f71.jpg
+ Empowered Corruption 3/3 - https://puu.sh/JAt63/8aa863fec3.jpg
+ Siphon Life 1/1 - https://puu.sh/JAt6a/f76efa858a.jpg
+ Shadow Embrace 5/5 and 3 stacks on target - https://puu.sh/JAt6l/fb6c645ad1.jpg
+ Shadow Mastery 5/5 - https://puu.sh/JAt6w/108ce2c788.jpg
+ Contagion 5/5 - https://puu.sh/JAt6U/74263ef169.jpg
+ Malediction 3/3 - https://puu.sh/JAt73/e4c90d97b7.jpg
+ Everlasting Affliction 5/5 - https://puu.sh/JAt8O/211fefc0ac.jpg
+ Haunt 1/1 and its debuff on target - https://puu.sh/JAtbC/5e9aaf1714.jpg + crit damage https://puu.sh/JAtbx/ba413c5e5d.jpg
+ Spell power procs - hit https://puu.sh/JAta8/e0ea63fff6.jpg crit https://puu.sh/JAta6/c19eb359e2.jpg

numbers are off by max like 10 damage which is nothing but rounding errors

Did I miss something?

**Comment by fvicaria** [comment]
As-is.
