### ISSUE TITLE
Wintergrasp Cannon Bug

### ISSUE THREAD

**Issue by tennisvs** [WoWManiaUK/Redemption#5983]
**Links:**

**What is Happening:**
Cannons are respawning way too quickly, like normal mob in wintergrasp during battle.

**What Should happen:**

Once destroyed during the battle, the cannons should not re spawn for the entirety of the match,

**Comment by GMZinius** [comment]
Thank you @tennisvs for the report
However without patch proof for 2008 we are unable to verify this
If you can provide information from a valid source then we can check this out

Screenshots/Video of where also help 
this report is incomplete https://github.com/WoWManiaUK/Redemption/wiki/How-to-Properly-Report-an-Issue
