### ISSUE TITLE
[Quest] Last Rites - Bugged teleporter

### ISSUE THREAD

**Issue by GroeneKnuppel** [WoWManiaUK/Redemption#5984]
**What is Happening:**
When doing the quest Last Rites you get teleported up to a flying UFO and u need to fight a boss on top of it .
Northrend->Borean Tundra

**What Should happen:**
After defeating the boss, normally u step into the teleporter and teleport down but for me the teleporter did nothing.

I am unable to put pictures here so if you need further explanation you can add me on discord
Michel#3217

**Comment by Echinaceax** [comment]
Thanks for reporting @GroeneKnuppel 
we'll check this out

**Comment by Echinaceax** [comment]
Fix confirmed in PTR 
https://i.gyazo.com/7a74ff6d86c94dfbff870a9895f2d9b5.mp4
