### ISSUE TITLE
[Quest] Dawn's Gambit - Bugged encounter

### ISSUE THREAD

**Issue by Darkadira** [WoWManiaUK/Redemption#5985]
What is Happening: When placing the Dawn's Gambit inside the Viewing Room in Scholomance, nothing happens, plus you cannot attack Vectus and Marduk Blackpool.
What Should happen: The special encounter between Vectus and Marduk Blackpool can be aggroed + fighting Scholomance Students.

https://www.youtube.com/watch?v=xwwlLRuUqag - starts at 8:30 (That should behave like that)

**Comment by Rushor** [comment]
most likely has never been scripted yes

**Comment by Rushor** [comment]
fully script added, after 5-10 seconda after summon of the Dawn's Gambit inside the student room all bosses and students will turn agressive

**Comment by Echinaceax** [comment]
Fix confirmed im PTR 

- [ ] scholomance student now turn aggressive
https://i.gyazo.com/5118013c4d702a30fa339857bb88cff9.mp4
- [ ] Marduk Blackpool and Vectus can be attacked 

Attackable
![image](https://user-images.githubusercontent.com/39439201/222957992-b85ac8c9-8978-4705-8f61-8b53072f6ad1.png)
Quest complete
![image](https://user-images.githubusercontent.com/39439201/222958055-0b0b6074-2737-4aa0-af8d-67ba69081e84.png)
![image](https://user-images.githubusercontent.com/39439201/222958070-a6b30f53-dc6d-4d7a-848c-204372efaff3.png)
