### ISSUE TITLE
[Boss] Blood-Queen Lana'thel - Mages losing bite when using blink

### ISSUE THREAD

**Issue by tvshadowz** [WoWManiaUK/Redemption#5986]
**What is Happening:**
During the encounter if a mage receives the bite and the buff (Essence of the Blood Queen) this is lost when the mage uses the spell blink. 

**What Should happen:**
Mages should not lose the buff Essence of the Blood Queen when they use blink. They should only lose it if a spell like invisibility (which brings them out of combat very shortly) is cast.

**Comment by GMZinius** [comment]
Thank you for reporting @tvshadowz 
We will look into this

**Comment by Yhato794** [comment]
It's not only mages it happened on my wlock as well after I got flames the bite was gone

**Comment by Keader** [comment]
i can reproduce it: https://youtu.be/sjXhc4OYw7w

**Comment by Echinaceax** [comment]
> i can reproduce it: https://youtu.be/sjXhc4OYw7w

fixing for both mage blink and Warlock @Keader ?

**Comment by Echinaceax** [comment]
> It's not only mages it happened on my wlock as well after I got flames the bite was gone

Keader maybe need more info to reproduce it for the warlock

**Comment by Keader** [comment]
Fixed (mage, warlock and all other guys xD)

**Comment by Echinaceax** [comment]
Confirmed fixed im PTR 

https://i.gyazo.com/986cc6c032f46e04c89e7d7d17678b3b.mp4
