### ISSUE TITLE
[NPC] Arcanist Braedin/Magister Surdiel -  does not ping que when wintergrasp starts

### ISSUE THREAD

**Issue by tennisvs** [WoWManiaUK/Redemption#5987]
**Links:**

**What is Happening:**
When you que with arcanist Braedin for wintergrasp, he adds you to wintergrasp que, but does not trigger the entrance of wintergrasp when the timer for wintergrasp offically starts. You need to talk to him again to enter wintergrasp.

**What Should happen:**

When wintergrasp starts and you are qued, so create an event to enter wintergrasp.

**Comment by Echinaceax** [comment]
Thanks for reporting this @tennisvs 
this also happened to me today, i was going to check Ally and horde later.

This is a new bug, i am glad it wasnt just me 

Also noticed that the timer was a little off today too, usually its 29mins and it was 32 mins earlier 
Is it still 32 mins when battle starts?

**Comment by Echinaceax** [comment]
For now @tennisvs once you have joined the que, wait for the "Wintergrasp Battle started" announcer
then right click the icon and "enter battle" 

![image](https://user-images.githubusercontent.com/39439201/223721436-8263ed67-5b47-4005-8718-7ad384dfd9b2.png)
![image](https://user-images.githubusercontent.com/39439201/223721337-f77f4c1c-d1ea-4ccf-b433-62548567c53f.png)

**Comment by Echinaceax** [comment]
Fixed in PTR 

Joined que fine, with icon showing 
https://i.gyazo.com/c7a51e5b01fcc36f722739de766e47f6.mp4

Que window popped now 
https://i.gyazo.com/fbc6bcd67e6fa08bd4cba2f53a70de1d.mp4
