### ISSUE TITLE
[Spell/item] soul preserver trinket not working

### ISSUE THREAD

**Issue by rowbs** [WoWManiaUK/Redemption#5988]
**Links:**
https://www.wowhead.com/wotlk/item=37111/soul-preserver

**What is Happening:**
just got trinket and testing the proc. been using heal spells on myself and havent seen the proc activate

**What Should happen:**
healing spells should have a change on next heals withing 15 sec to cost less mana

**Comment by Echinaceax** [comment]
Thanks for reporting @rowbs 
we will take a look at it

**Comment by Keader** [comment]
fixed

**Comment by Echinaceax** [comment]
Confirmed fixed in PTR

![image](https://user-images.githubusercontent.com/39439201/224552546-96a17de4-2bd9-4e01-9f2e-55a437f6c245.png)
![image](https://user-images.githubusercontent.com/39439201/224552682-30ac400d-ce12-44f2-bae0-46800c905e4c.png)

**Comment by rowbs** [comment]
awsome guys you rock!!

**Comment by rowbs** [comment]
been spamming heals on myslef for 15mins and didnt see the proc activate

**Comment by Keader** [comment]
> been spamming heals on myslef for 15mins and didnt see the proc activate

It's fixed in Test Realm. It will be in live servers in some days 👯

**Comment by rowbs** [comment]
awsome cant wait tyty

**Comment by GMZinius** [comment]
> awsome cant wait tyty

Your welcome @rowbs 
please leave the report open until Janitor has updated this fix to the live realm
