### ISSUE TITLE
Achivement for mounts ingame isn't receiving that i have 26 mounts in bag. 

### ISSUE THREAD

**Issue by Hemlagadcolt** [WoWManiaUK/Redemption#5989]
**Links:**

**What is Happening:**

**What Should happen:**

**Comment by Hemlagadcolt** [comment]
I have 26 mounts, but havn't gotten the achiv for 25 mounts "Filling up the Barn"

**Comment by fvicaria** [comment]
I cannot reproduce this. Works for me. Give me your character name and I can check for you.

**Comment by WhitephoenixTheBunny** [comment]
I can give some extra info on this.

If you have any custom mounts, those mounts doesn't count toward the achievement, you need in game mounts (drop mounts, craft mounts, rep mounts, achievements mounts, ...) 

Same happens with the pets btw.
