### ISSUE TITLE
[Quest line - DK] Quest requirements / phase issues

### ISSUE THREAD

**Issue by WhitephoenixTheBunny** [WoWManiaUK/Redemption#5990]
The (side) quest [Grand Theft Palomino](https://wow-mania.com/armory/?quest=12680) isn't, atm, a requirement for [Gothik the Harvester](https://wow-mania.com/armory/?quest=12697), and it should be as the 3 other side quests (as it will phase the DK out, and not be able to continue with the questline, missing the DK mount and 1 talent point) **AND** it should be a requirement also.

![image](https://user-images.githubusercontent.com/31921098/226560184-d3948264-296b-4a35-b48a-1354543865da.png)
![image](https://user-images.githubusercontent.com/31921098/226560452-82031dd6-b727-45bd-a8cc-a0503b57f8b5.png)

**Comment by Rushor** [comment]
added quest 12680 as requirment to enable quest 12697

**Comment by Echinaceax** [comment]
> added quest 12680 as requirment to enable quest 12697

no change rushor 

started new DK and deleted cache and i still can see the [Grand Theft Palomino](https://wow-mania.com/armory/?quest=12680) and [Gothik the Harvester](https://wow-mania.com/armory/?quest=12697) still 
https://i.gyazo.com/30367b100df4f294678a8965956724fd.mp4

**Comment by Rushor** [comment]
One more condition added, only after rewarding [Grand Theft Palomino](https://wow-mania.com/armory/?quest=12680) then quest will be able to see [Gothik the Harvester](https://wow-mania.com/armory/?quest=12697)

**Comment by Echinaceax** [comment]
After completing [If Chaos Drives, Let Suffering Hold The Reins](https://wowwiki-archive.fandom.com/wiki/Quest:If_Chaos_Drives,_Let_Suffering_Hold_The_Reins) 
![image](https://user-images.githubusercontent.com/39439201/229632145-037da657-2b90-4471-8c4e-1b067516af26.png)
now [Gothik the Harvester](https://wow-mania.com/armory/?quest=12697) isnt offered, thats better 

But now [Into the Realm of Shadows](https://wowwiki-archive.fandom.com/wiki/Quest:Into_the_Realm_of_Shadows) isnt offered

**Comment by Echinaceax** [comment]
Much better @Rushor ❤️ 
Fixed in PTR
