### ISSUE TITLE
Warlock Pet Bug

### ISSUE THREAD

**Issue by ZeyTheAzrael** [WoWManiaUK/Redemption#5991]
**Links:**

**What is Happening:**
Hello.Warlocks Inferno pet is buged somehow.U can use it u can cast it but when it apears it doesnt do any dmg it just sits there and watch me how im pewpew.I would like it to be fixed cuz this pet is really huge dps for affliction warlocks and since im the best one in Mania it really matters.Thank you in advance.Keep up the good work with the server.

**What Should happen:**

**Comment by Echinaceax** [comment]
Thanks for reporting @ZeyTheAzrael 

1. I summoned Inferno pet https://i.gyazo.com/a1d38c37a8001126fd3ccd025121a11d.mp4
2. Using the pet bar it gives you to control it is working fine 

temporary guardian for 1 minute

Mania 3.3.5 Inferno https://www.wow-mania.com/armory/?spell=1122  (1 min duration) 
Wowhead Summon Infernal 5.0.4 https://www.wowhead.com/spell=111685/summon-infernal

Pet bar (for controlling) 
![image](https://user-images.githubusercontent.com/39439201/226706280-6c128b4c-fef3-411f-a51f-6750b0810938.png)

Test dmg output 
![image](https://user-images.githubusercontent.com/39439201/226706207-fa2deee4-06b1-4be6-b9eb-83c255785703.png)

Summon Inferno pet AoE and stun working

![image](https://user-images.githubusercontent.com/39439201/226715116-b977b716-e469-4d9e-8d6b-3abc39086cca.png)
![image](https://user-images.githubusercontent.com/39439201/226715274-86849d48-e07c-4296-9a52-2639c500fec6.png)

Gains Demonic immolation

![image](https://user-images.githubusercontent.com/39439201/226719934-4fedcfc4-6c28-4789-816e-974dd2a1f889.png)


### Notes
https://i.gyazo.com/23b177d0bb5b61ce6a708e750272c557.mp4

what i did notice is, you must set your petbar to remember your preferences `Agressive/Defensive/Passive`
(much like a hunters pet bar)

![Settings ](https://user-images.githubusercontent.com/39439201/226723562-dd338e04-2e00-4266-9a64-39a65c4ada9b.jpg)
