### ISSUE TITLE
Player Wilo Killing Self For Bounty

### ISSUE THREAD

**Issue by vandamark** [WoWManiaUK/Redemption#5992]
Wilo is logging dualboxing in pvp grounds to collect the bounty put on himself by another player. This should not be allowed and he admitted to it.

![image](https://user-images.githubusercontent.com/73784106/227994609-444c6c32-ef63-4aff-b4c1-ea4eff1e03e3.png)
![Wilo](https://user-images.githubusercontent.com/73784106/227994775-455a1eed-0ef4-41a3-82b9-ee87d3ddb6d6.jpg)

**Comment by Rushor** [comment]
Report it to an gm, this is for serverside issues only here
