### ISSUE TITLE
[Boss/Spell] Scourgelord Tyrannus isn't affected by Rimefang's Icy Blast patches

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#5994]
**Links:** https://www.wowhead.com/wotlk/npc=36658/scourgelord-tyrannus#article
https://wowpedia.fandom.com/wiki/Scourgelord_Tyrannus#Strategy
https://www.wowhead.com/wotlk/spell=69238/icy-blast
https://www.wow-mania.com/armory/?npc=36658
https://www.wow-mania.com/armory/?spell=69238

**What is Happening:** Tyrannus is currently unaffected by Rimefang's [Icy Blast](https://www.wow-mania.com/armory/?spell=69238) patches.

**What Should happen:** The boss is meant to be kited through the patches during his Unholy Power buff, as his melee damage is not meant to be manageable by a typical 5-man during that time.

_On a side note, white damage from most creatures seems to be undertuned overall, with even bosses hardly dealing any damage other than with their abilities._

**Comment by Echinaceax** [comment]
Confirmed bugged - not working as it should 

![icy patch](https://user-images.githubusercontent.com/39439201/229175972-126896bd-84a7-4e81-a0e8-6b6d852a9c19.jpg)

**Comment by Keader** [comment]
i tried to fix it last year, without success
problem here is 'faction'
Dragon and Tyrannus has "friendly faction" so one cant do damage or cause negative effects in each other
this, i realy have no idea how fix
