### ISSUE TITLE
[Spell] Unbound Plague

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#5995]
**Links:** #2074

**What is Happening:** Wild attempt since I doubt it will get changed, but issue #2074 is still happening and I remember some fairly important systems (i.e. QAston proc) were implemented since 2017. The plague is resetting its tick timer every time it jumps, basically rendering the mechanic non-existant.

**What Should happen:** Its tick-timer should carry on to the new debuff owner.

**Comment by Echinaceax** [comment]
Thanks for reporting @Oganku 
From then old report didnt keader say that he couldnt fix all issues with it?

Dranah also said 2/3 issues fixed
https://github.com/WoWManiaUK/Redemption/issues/2074#issuecomment-367131379

**Comment by Oganku** [comment]
Correct, I'm only referring to the 3rd that could not be fixed back then. Just wondering if the situation changed or not.
