### ISSUE TITLE
[NPC] Mage trainer at Teldrassil for Worgen

### ISSUE THREAD

**Issue by WhitephoenixTheBunny** [WoWManiaUK/Redemption#5997]
_Introduction of "new" mage trainers at Teldrassil, due to the difficulty of Worgens leveling on a low map - at least leveling to level 10 without visiting a trainer, since at level 10 they can use the Mall Stone and go Stormwind._

**Coordination and new skins**
Aldrassil - coor for the new NPC 59.68. 42.14
entry - 198 (human - Northshire Valley) /new skin (nelf) displayID 2057

Dolanaar - coor for the new NPC 59.51. 59.35
entry - 328 (human - Goldshire) /new skin displayID (nelf) 3894

Darnassus - coor for the new NPC 37.24. 9.38 | 37.30. 9.85 | 37.45. 10.05
entry - 5497 | 5498 | 331 (blood elf | human 2 - Stormwind) /new skin (nelf) displayID 4402 | 18184 | 4172

**Quests**
class quest to “Zaldimar Wefhellt”
[Report to Jennea](https://www.wow-mania.com/armory/?quest=1919)
[Speak with Jennea](https://www.wow-mania.com/armory/?quest=1860)

class quest “Elsharin”
[Magecraft](https://www.wow-mania.com/armory/?quest=8250)

_NOTE:
2 of the NPC are quest givers, for some class quests

NPC level are applied to area level_

**_Phase 1_**
- [x]  Copy the NPC and rename

- [x] Rename (do as you did to #5711)

- [x]  apply the new look (open for new suggestions)

- [x]  put them on the new placements

- [x]  test

  - [x]  Aldrassil

  - [x]  Dolanaar

  - [x]  Darnassus 1

  - [ ]  Darnassus 2

  - [ ]  Darnussus 3

**_Phase 2_**
- [x] Add guards the information of the trainer

- [x]  test

**_Phase 3_**
- [x]  add class quests  to “Zaldimar Wefhellt”
[Report to Jennea](https://www.wow-mania.com/armory/?quest=1919)
[Speak with Jennea](https://www.wow-mania.com/armory/?quest=1860)

- [x] Add class quest “Elsharin”
[Magecraft](https://www.wow-mania.com/armory/?quest=8250)

(Those are human questlines, only need the starting one)

- [x]  test
  - [x] [Report to Jennea](https://www.wow-mania.com/armory/?quest=1919)
  - [x] [Speak with Jennea](https://www.wow-mania.com/armory/?quest=1860)
  - [x] [Magecraft](https://www.wow-mania.com/armory/?quest=8250)

**Comment by Echinaceax** [comment]
Aldrassil

- [ ] Myriam Spellwaker + POI 

Dolanaar

- [ ] Sebastian Hayward + POI  + Quests + Guard gossip info

Darnassus

- [ ] Melinda Hammond + POI  + Quest Guard gossip info

Sebastian Hayward

![image](https://user-images.githubusercontent.com/39439201/233354917-965cff54-ca10-4eda-adff-ee9604ac37eb.png)

Melinda Hammond

![image](https://user-images.githubusercontent.com/39439201/233355193-d7418764-b198-4c8c-ba29-829484669f4c.png)
