### ISSUE TITLE
PvP quest broken?

### ISSUE THREAD

**Issue by gianmerl** [WoWManiaUK/Redemption#5998]
Hi, maybe Push the Envelope and Bite them Hard are broken?

Before tonight, i had:
- Push the Envelope: 1/2 RBG win..tonight as horde we won it 2 times.. but still 1/2 RBG win
- Bite them Hard: 00/01 RBG win.. still same after 2 won.

I heared several other players had the same problem, not only me.
TY

**Comment by GMZinius** [comment]
Thank you for letting us know @gianmerl 
We are having it tested in the next BG that pops

In the meantime we suggest you abandon the quest and pick it up again

**Comment by Echinaceax** [comment]
Confirmed fixed in PTR 

![image](https://user-images.githubusercontent.com/39439201/234858223-dd56f335-6cda-460d-ba4c-828b10793c39.png)
![image](https://user-images.githubusercontent.com/39439201/234858272-db74f626-a35c-42e6-a48b-8098ff16df5d.png)

**Comment by Echinaceax** [comment]
Closing this - as it was applied to LIVE  today
