### ISSUE TITLE
ghost mushroom possible spawn discrepancy.

### ISSUE THREAD

**Issue by sirmanyeyes** [WoWManiaUK/Redemption#5999]
**Links:**
https://www.wowhead.com/object=142144/ghost-mushroom
https://www.wow-mania.com/armory/?object=142144
**What is Happening:**
The ghost mushroom node spawns in un'goro crater appear to be missing?

**What Should happen:**
I'm honestly not sure if they would be there during patch 3.5.5a but given the items age it's a fair chance it's just missing.

**Comment by Echinaceax** [comment]
thanks for the report @sirmanyeyes 
will check on this
