### ISSUE TITLE
WOW monsters

### ISSUE THREAD

**Issue by uwsnake** [WoWManiaUK/Redemption#6002]
**Links:**

**What is Happening:**
if you pull a spellcast and move out of sight it just looks at you and if it cast a spell and you interrupt the monster it just look at you

**What Should happen:**
the monster need to run over and start autohiting/casting at you

**Comment by Echinaceax** [comment]
Thanks for reporting @uwsnake 
will need a few NPCs names that you seen this issue on, and what spell you used 
i did a random spellcaster, using counterspell and it was fine 
https://i.gyazo.com/c71692a3c297d28b9266769f5c71896d.mp4

**Comment by fvicaria** [comment]
Cannot reproduce.
