### ISSUE TITLE
Two for One - General Drakkisath, The Seven

### ISSUE THREAD

**Issue by SebastianPop** [WoWManiaUK/Redemption#6003]
**Links:**
https://www.wowhead.com/npc=51446/general-drakkisath (lacks information, maybe use this link for reference instead https://wowpedia.fandom.com/wiki/General_Drakkisath?so=search)

https://www.wowhead.com/npc=9039/doomrel

**What is Happening:**
1. General Drakkisath's Conflagration  inflicts 750 EVERY second for a total of 3750 damage. The panic incapacitation effect also seems to last longer than the 5 seconds it should. With a retpaladin at level 73 and 9000 health, he ganks me from full to zero health before the effect even expires, despite having anti-flame aura on. My gear is none too shabby either.

3. In the Summoner's Tomb in Blackrock Depths, when commencing The Seven trial, Doom'rel and all the other six ghosts attack you all at once.

**What Should happen:**
1. General Drakkisath's conflagration ability should deal 750 over 5 seconds - as in, it should take 5 seconds for 750 damage to be done in TOTAL, not 750 every second for 3750 damage. The panic should only last 5 seconds.

2. Doom'rel's trial in the Summoner's Tomb of Blackrock Depths is supposed to be a gauntlet, where every ghost attacks you alone one after another, with only one of them being hostile at a time, beginning with Anger'rel and Doom'rel only becoming hostile at the very end.

**Comment by GMZinius** [comment]
Thank you for reporting @SebastianPop 

Please report each issue seperately, we don't do 2 different issues in one report 

so if you could edit your report to General Drakkisath only, then report the second issue seperately 

Thank you

**Comment by SebastianPop** [comment]
Ok, I've posted the two reports sepaately.

**Comment by GMZinius** [comment]
> Ok, I've posted the two reports separately.

Thank you @SebastianPop
