### ISSUE TITLE
General Drakkisath

### ISSUE THREAD

**Issue by SebastianPop** [WoWManiaUK/Redemption#6004]
**Links:**
https://www.wowhead.com/npc=51446/general-drakkisath (lacks information, maybe use this link for reference instead https://wowpedia.fandom.com/wiki/General_Drakkisath?so=search)

**What is Happening:**
General Drakkisath's Conflagration inflicts 750 EVERY second for a total of 3750 damage. The panic incapacitation effect also seems to last longer than the 5 seconds it should. With a retpaladin at level 73 and 9000 health, he ganks me from full to zero health before the effect even expires, despite having anti-flame aura on. My gear is none too shabby either.

**What Should happen:**
General Drakkisath's conflagration ability should deal 750 over 5 seconds - as in, it should take 5 seconds for 750 damage to be done in TOTAL, not 750 every second for 3750 damage. The panic should only last 5 seconds.

**Comment by GMZinius** [comment]
Myself and another GM checked on this 

Spell 
Mania https://www.wow-mania.com/armory/?spell=16805
other wotlk source https://wotlk.evowow.com/?spell=16805

Spell dmg is correct for 3.3.5 info 
- But the` the flames periodically scorch its nearby allies for 300 damage as well.` part is not working, so the randomly selected player is taking all the extra dmg also that should be shared to other players

**Comment by fvicaria** [comment]
Victim get 3000 damage spread in 10 seconds.
Also hits nearby players for 300 each. 
This is correct.

**Comment by GMZinius** [comment]
> The victim gets 3000 damage spread in 10 seconds. Also hits nearby players for 300 each. This effect is random so you can be picked multiple times if the number of players nearby is small. This is correct.

Ok, So as it was Myself and Remmy doing this test. Remmy was always the victim then, because i never took any of the extra 300 dmg in over 6 tests

**Comment by fvicaria** [comment]
He is supposed to get the 3000 anyways. Maybe then the second part where you get a random 300 is missing.

**Comment by GMZinius** [comment]
> He is supposed to get the 3000 anyways. Maybe then the second part where you get a random 300 is missing.

Yes We believe so @fvicaria 👍

**Comment by Keader** [comment]
Fixed, it was scaling with attack/spell power.

**Comment by GMZinius** [comment]
Much better now @Keader Thank you

![image](https://github.com/WoWManiaUK/Redemption/assets/108176634/1243c49b-555d-48cd-bd1e-ee13f4adfa86)

**Comment by Keader** [comment]
try now please

**Comment by GMZinius** [comment]
Great
That's much better 👍 
224 per tick on debuff
