### ISSUE TITLE
Random Dungeon Finder Not Working

### ISSUE THREAD

**Issue by Jandj56** [WoWManiaUK/Redemption#6006]
**Links:**

**What is Happening:**

I queue on my 30 lvl toon and dungeon finder doesnt work, all roles are perma grey and nothing happens. But on my other toons its working normally. I dont understand what is the issue?
**What Should happen:**

**Comment by GMZinius** [comment]
Hello @Jandj56 
I spoke to you ingame about this, and as this is only happening on one of your chars then its not a bug that can be fixed by a DEV fix

I did advise you to speak with support about this
