### ISSUE TITLE
Masophet the Black

### ISSUE THREAD

**Issue by K1b0s** [WoWManiaUK/Redemption#6008]
**Links:**

**What is Happening:**

This enemy is bugged and cannot be killed 

**What Should happen:**

The enemy should appear on the surface area 

![241851046-737adda8-c836-416c-8249-55dcbe053382]
https://github.com/WoWManiaUK/Redemption/assets/134994325/a003dd00-fcb5-465a-aaee-41b6400d2354

**Comment by GMZinius** [comment]
Thank you @K1b0s for reporting 
At the moment he has spawned correctly at one of the two spawn points he has, this has been reported before #1804 #1038 
We will keep an eye on this issue 

![image](https://github.com/WoWManiaUK/Redemption/assets/108176634/82dbf55c-c41c-48c4-acf2-c2ef06811d09)
