### ISSUE TITLE
[Quest] Torek's Assualt

### ISSUE THREAD

**Issue by Shanksalot** [WoWManiaUK/Redemption#601]
Quest:  Torek's Assault.      When quest NPC Torek enters the Silverwing Post for the quest, NPC Duriel Moonfire and her 2 guards spawns twice resulting in 6 adds total.  

http://www.wowhead.com/quest=6544/toreks-assault

**Comment by fvicaria** [comment]
by the way 2x2 = 4 :P

**Comment by Shanksalot** [comment]
haha Janitor, it says Duriel and her 2 guards spawn twice. that's 3x2 =P. no more beer for you.
