### ISSUE TITLE
The Mount Highmountain Thunderhoof Jump Issue

### ISSUE THREAD

**Issue by Nocturnaeon** [WoWManiaUK/Redemption#6010]
**Links:**
![fails to vault over](https://github.com/WoWManiaUK/Redemption/assets/137768596/b1f5aafa-14dd-416d-b6d5-3670cb3c0124)
![phasing into the ground 1](https://github.com/WoWManiaUK/Redemption/assets/137768596/618fac49-e3aa-4093-845f-e5f3ce1f6314)
![worse on the stairs](https://github.com/WoWManiaUK/Redemption/assets/137768596/f6394c9c-8983-467c-807b-8e96cde06567)

**What is Happening:**
While I tap the jump key, the mount does not perform the action, instead phases to the ground and does not execute a leap whatsoever. This is an issue because out in the world, it cannot jump above objects and gets stuck. Not only it's a animation and utility problem but when the moutn fails to vault over an object the camera zooms in and that aspect seems broken as well. It's overall very buggy.

**What Should happen:**
The mount should function like any other proper ground mount.

**Comment by Nocturnaeon** [comment]
I'd like to also add, the camera zooming issue comes from the while mounted, camera is zoomed on the mount's legs rather than the character, I don't know if this issue could be adressed but wanted to share.

this is the focus point
![cam1](https://github.com/WoWManiaUK/Redemption/assets/137768596/bb8b8d5d-f64b-46bd-aae9-45076bdda90f)

while for example on this mount it is set to character
![cam2](https://github.com/WoWManiaUK/Redemption/assets/137768596/593cc74a-8f11-4c87-8656-c5e60b31149e)

**Comment by GMZinius** [comment]
Thank you for reporting @Nocturnaeon 
I tested this issue and seems fine for me

Please make an ingame ticket to  We can check the issue with yours. thank you
