### ISSUE TITLE
Cross realm mail BoA items

### ISSUE THREAD

**Issue by Jschramm028** [WoWManiaUK/Redemption#6011]
**Links:**

**What is Happening:**
I cannot mail my bind to account items from one realm to the next. I started on naxx thinking it was more populated but now want to move my heirloom items over to the other server along with my maniac points

**What Should happen:** allow me to move my maniac and heirloom prices thru mail, or give me a realm transfer

**Comment by GMZinius** [comment]
Thank you for reporting your issue @Jschramm028 
But this is not an ingame bug 

Please contact mania support listed on the website. Thank you
