### ISSUE TITLE
[Item ] Creteus's Mobile Databank - Databank Dialog Mixed Up

### ISSUE THREAD

**Issue by SebastianPop** [WoWManiaUK/Redemption#6012]
**Links:**
Quest "Fate of the Titans": https://www.wowhead.com/wotlk/quest=12986/fate-of-the-titans
Creteus's Mobile Databank: https://www.wowhead.com/wotlk/item=42679/creteuss-mobile-databank

**What is Happening:**
Creteus's Mobile Databank talks about the wrong Titan Keepers for each Temple.

Specifically, it mentions Watcher Hodir in the Temple of life "Watcher Hodir verified to be no longer present", when it should be Freya. Conversely, it says "Watcher Freya Verified to no longer be present" at the temple of Order,  and  "Watcher Mimir verified to no longer be present" at the temple of Winter. Finally, there is no "Watcher ... verified to be missing" at the temple of Invention, instead it says "Temple of Invention analysis commencing" twice.

**What Should happen:**
Temple of Invention - Mimir
Temple of Winter - Hodir
Temple of Life - Freya
Temple of Order - Tyr

Interestingly, the databank DOES mention Freya correctly when saying there was a significant battle at the Temple of Life. "Opponent of Watcher Freya estimated to have been of similar size and strength". Actually, all of the final, quest relevant dialog boxes seem to be accurate, and the quest progresses correctly each time.

**Comment by GMZinius** [comment]
Thank you for reporting @SebastianPop

**Comment by Echinaceax** [comment]
confirmed bugged
all gossips are all mixed up 

Eg: temple of winter 1st comment is:

![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/b29061f5-fd2f-47c1-94bd-8cd28b148c3f)


and it should be:

![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/841fb135-f78a-44d8-958f-eb24cdc5174c)

**Comment by Rushor** [comment]
wrong order fixed

**Comment by Echinaceax** [comment]
Temple of Invention - Mimir
![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/c730f9e9-77f8-443c-9c3c-f34bcedcb9c8)
Temple of Winter - Hodir
![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/f0a15fe2-9c7a-4394-8a6f-e12fa490d831)
Temple of Life - Freya
![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/8a7facdf-b4ea-4f00-92ed-a01bb996476e)
![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/1ee2efa1-a7d1-4e4d-89ba-a9ae994b3cc1)
Temple of Order - Tyr
![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/db30341b-fb25-4163-a6df-84f49e7ae48f)
