### ISSUE TITLE
[Spell/Shammy] Totems - Wintergrasp 

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Redemption#6013]
### Reported by player 

all totems really

**Links:**
Totem of Wrath https://www.wow-mania.com/armory/?spell=57722
Wrath of Air Totem https://www.wow-mania.com/armory/?spell=3738

**What is Happening:**
When the winergrasp battle is on and a shammy pops their totems, they stay active even though the totem timer has ended.
They stay active until WG battle ends, then they despawn.

 video 1 https://i.gyazo.com/386631e3fb3e412c1d88915621a25a8b.mp4
video 2 https://i.gyazo.com/dccbcc554604cf23c1ab128d302c1306.mp4

Confirmed its not a visual bug, see stats below (with and without totems)
https://i.gyazo.com/5677b91abc4a72e74ae1ee9226719916.mp4

**What Should happen:**

- [ ] Totems should despawn when the 5 min totem timer has ended

**Comment by Rushor** [comment]
added a despawner for the totems to be save

**Comment by GMZinius** [comment]
Fixed in PTR, Thank you @Rushor 
https://i.gyazo.com/89a2787592dd3198f893e47c8f1e46b2.mp4
