### ISSUE TITLE
[Spell/Warlock] Searing Pain

### ISSUE THREAD

**Issue by Nephylia** [WoWManiaUK/Redemption#6015]
**Links:** 
https://www.wow-mania.com/armory/?spell=47815
https://wowwiki-archive.fandom.com/wiki/Threat

**What is Happening:**
Currently the Searing pain is doing 1x it's damage  as Threat.

**What Should happen:**
Searing  Pain is supposed to do 2x it's Damage  as  threat.
Source: wowwiki-archive from 3.3.5a retail.

**Comment by GMZinius** [comment]
Thank you for reporting this issue @Nephylia 
I have only seen one report that has mentioned Searing Pain and that wasnt about a bug with it 

Can you let us know how you are calculating your findings please

**Comment by Nephylia** [comment]
Simple Threat meter like Omen3 lets you see how much threat you do with each ability.  That is  how i   calculate   the findings.

I have reported  this issue privately  more then  a year ago   to Svjetlonosa, and he  has confirmed it  on PTR, but  was  not able to submit it  because  he  quit he  testing team. Now i    found the  time to report  it myself.

**Comment by GMZinius** [comment]
Thank you for the update information @Nephylia 

Test from us show that if this has been tested via the training dummy it is giving the wrong info at x1, 
but tests so far on actual mobs it shows x2 

```
current test on mob
2236 hit x2 threat amount at 4.5k
```

We will be testing this more over the next few days 
Thank you again

**Comment by Nephylia** [comment]
i have tested it in ICC and the results for me were x1

**Comment by Nephylia** [comment]
ok i just tested it myself again. apparently it has been fixed, even tho i  never saw anything in changelog.
anyways good job! 
closed.

**Comment by GMZinius** [comment]
> ok i just tested it myself again. apparently it has been fixed, even tho i never saw anything in changelog. anyways good job! closed.

No fixes have been done to Searing Pain @Nephylia hence why it is not on the changelog

Iam glad your issue is fixed, thank you for the updated information.
