### ISSUE TITLE
[Joust Mounts / Warhorses] Cooldowns on Argent Peacekeeper in Court of Bones

### ISSUE THREAD

**Issue by SebastianPop** [WoWManiaUK/Redemption#6016]
**Links:**
https://www.wowhead.com/search?q=Argent+Peacekeeper#npcs

**What is Happening:**
Argent Peacekeepr warhorses (lance ones) in the Court of Bones in Icecrown seem to be bugged. The cooldowns on the latest ability used seems to apply to the next one you try as well. The cooldowns LOOK like they are progressing properly, but after I use Defend, its 3 second cooldown applies to the others - if I try to use Shield-Breaker or charge, it keeps failing with 'i can't use that ability yet' for around the same length of time. Charge cooldown seems to cause the same problem, except the cooldown is of 4.5 seconds there.

Interestingly it doesn't always happen the FIRST time I use Shield-breaker in a joust, but it ALWAYS happens if I try Shield-Breaker-Defend-Shieldbreaker, so the issue might be that both or ALL abilities actually have longer cooldowns that they should.

I thought it was lag or just me being bad, but I never run into this problem with the Argent Peacekeeper or any other mount at the Tournament Grounds.

**What Should happen:**
Shield-breaker should be useable every 1.5 seconds, and immediately after the general ability cooldown of any other abilities (as indicated by both the interface and ability description).

**Comment by Keader** [comment]
Do you have any proof that sustain your afirmation?
Because in WOTLK DBC has 3 sec there, only for Defend spell (62552)
so looks correct to me...

**Comment by SebastianPop** [comment]
Yes? DEFEND has 3 seconds. The problem is I can't use any of the abilities even when I haven't used them AT ALL, the cooldown from Defend seems to carry over to the others.

**Comment by Echinaceax** [comment]
hi @SebastianPop 
what quest are you on with this atm?

the very 1st one https://www.wowhead.com/wotlk/quest=13838/mastery-of-the-shield-breaker
or this one https://www.wowhead.com/wotlk/quest=13677/learning-the-reins#comments

**Comment by SebastianPop** [comment]
Neither. As I said before, none of the mounts at the Torunament Grounds have this problem. The ONLY one that has this problem is the one at the Court of Bones, at the base of Icecrown Citadel, that is used for the Daily Quests (i.e. Battle Before the Citadel).

**Comment by Echinaceax** [comment]
Ah this one, still same result tho 
https://www.youtube.com/watch?v=EpxW1WWdVO4

**Comment by SebastianPop** [comment]
Huh. Well, I don't know what to tell you then, it doesn't work like that for me. Oh well.

**Comment by Echinaceax** [comment]
> Huh. Well, I don't know what to tell you then, it doesn't work like that for me. Oh well.

Even the guy in the video you hear "i cant use that ability yet" several times.

If you manage to get some record software and show us, them we can see whats happening to you @SebastianPop

**Comment by Echinaceax** [comment]
i hate that quest myself, coz you have to be faster than then to do 3 things, but it is how its mean to be 

![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/3e1ed008-a85d-4888-ba0e-f2c1880c6436)
