### ISSUE TITLE
Patrolling Enemies

### ISSUE THREAD

**Issue by PoliteTim** [WoWManiaUK/Redemption#6017]
**Links:**
https://www.wow-mania.com/armory/?npc=32259
https://www.wow-mania.com/armory/?npc=27963
https://www.wow-mania.com/armory/?zone=4264

**What is Happening:**
These and most if not all other enemies on patrol routes will forcibly continue their patrols even during combat. Some enemies simply ignore the player all together, others will auto-path back to their route mid combat. I have included the "Halls of Stone" instance because this is a great place to see it in action, pulling the Theurgists causes them to enter combat, but even with LOS they struggle to leave their patrol route. **When testing this for yourself, make sure you take your time killing them.**

**What Should happen:**
Enemies should forsake their patrol routes and not return to them mid combat, nor should they remain on them when combat begins. This is not much of an issue once or twice, as even in official Bliz servers enemies sometimes just Evade away for no reason, but these enemies constantly patrolling really breaks the flow of combat and often pulls other enemies or makes sections of dungeons harder than they need to be.

**Comment by Rushor** [comment]
this does not happen to all, just for specific ones, just post the name/ids of the creatures and it will be fixed

**Comment by Rushor** [comment]
fixed for those 2 guys https://www.wow-mania.com/armory/?npc=32259
https://www.wow-mania.com/armory/?npc=27963

**Comment by GMZinius** [comment]
Confirmed fixed on PTR

**Comment by PoliteTim** [comment]
I can try and track down some of the enemies, but many of them I encountered leveling, and the WoW Mania Armory loads very, very slowly for me (American), and it lacks any data on non-Northrend Dungeons from the old world. I promise this is an issue that affect a large number of mobs in every zone and most dungeons. Ill start a list when I run into some more

**Comment by Rumbleroar** [comment]
I found a bugged out flying patrolling mob in Dragonblight, the Reanimated frost wyrm important to a green dragon mini quest chain, i think it could use a reset. (whenever i try and hit it, it says its out of range)
![image](https://github.com/WoWManiaUK/Redemption/assets/140111208/1295c565-b0bc-41df-b44b-e4a85d6873b4)
