### ISSUE TITLE
Can't create Guild

### ISSUE THREAD

**Issue by Kryztal89** [WoWManiaUK/Redemption#6018]
**Links:**

**What is Happening:** - I purchased a guild charter, have signatures from different accounts. Nothing happens when I try to Register the guild. With signed charter in bag of Character that is to be the GM, I went to the Guild Master in Stormwind (Aldwin Laughlin). I speak with him and choose "How do I forma guild?". Then I choose "Register a guild." - NOTHING happens.  I made the guild Dragons of Fate on Horde side Redemption with no issues (a while back) and have made other guilds as well.

Character - Kryztal - Ally Rogue. Has signed guild charter in bag.

These are steps I have taken:
Logged out - disabled all add-ons. - No change.
Quit game entirely and came back in with add-ons still disabled - No change.
Quite game, rebooted, left add-ons disabled - No change.
Went to IF Guild Master - No change.
Placed charter in first slot of main backpack - No change.
Sat in chair next to the Guild Master and glared angrily - he was not impressed, No change.

I don't have auto join guild recruitment channel or guild member alert checked in interface settings.
I'm not sure if I'm supposed to have anything in my quest log on this, I never looked before. However, I don't have anything there that is related.
On another character that does not have a guild charter in her bags, when she chooses "Register a guild charter." she gets an error stating she doesn't have one. - This appears correct.

**What Should happen:** - Guild should be created.

**Comment by Rushor** [comment]
please ask a gamemaster ingame about that :)

**Comment by Kryztal89** [comment]
I was told by others in game to submit a ticket in game, which I have done.
