### ISSUE TITLE
Equipped items with stats that disappear after a short amount of time.

### ISSUE THREAD

**Issue by Vidrell** [WoWManiaUK/Redemption#6019]
**Links:**
https://ibb.co/kgj8w0y
https://ibb.co/B2QwxfW

https://ibb.co/0GRx6Pq
https://ibb.co/bHvfQLV

**What is Happening:**
I have gotten equipment that has X amount of stats and after a while of it being equipped (hours/a day or so) those stats from such equipment have vanished. I can link the item on chat and I can see their original stats there, but when it is in my possession/equipped on my character, they're gone. I have equipped/unequipped said items and the stats don't move, but in the case of the belt the amount of armor does, confirming that no Agility nor Stamina is reflecting on the character itself. Images below show the issue:

![Belt](https://github.com/WoWManiaUK/Redemption/assets/140113467/407f6133-6ff6-45e5-8251-c177f3f25e17)
![belt on chat](https://github.com/WoWManiaUK/Redemption/assets/140113467/75c2debf-f47a-4012-bcd0-8dc6917c38b4)
![ring](https://github.com/WoWManiaUK/Redemption/assets/140113467/581c84d6-3148-40e5-9b06-87393ff9277a)
![ring on chat](https://github.com/WoWManiaUK/Redemption/assets/140113467/18f4aa29-57ab-44f0-862e-99d8d3dea588)

**What Should happen:**
Hopefully this isn't happening to a lot of players, though on World chat some have confirmed they've also have had this issue. I decided to share this issue/bug at the recommendation of a GM who gave its best in try to aid me in this issue.

**Comment by Echinaceax** [comment]
thanks for reporting @Vidrell 
i will take a look

it seems like a client corrupt file to me 

i will update here if i can reproduce it
