### ISSUE TITLE
[Custom] Summon Hobgoblin 

### ISSUE THREAD

**Issue by Kitzunu** [WoWManiaUK/Redemption#602]
When you read on the "summon Hobgoblin" it says "Summons a Hobgoblin merchant that sells and buys items for 1 min." Asfar as I can see I can only sell this Merchant stuffs and not buy any :)

**Comment by fvicaria** [comment]
There is not really a bug but a lack of appropriated items to add since this is a custom extension. We don't want to add an unfair advantage to Goblins.

If you can come up with some suggestions I will consider them.

**Comment by Kitzunu** [comment]
Maybe like something that does not benefit nobody... just crap if I can say so ^^

**Comment by Emcitementz** [comment]
Well, we could do something like, put the same items as the merchants riding the mammoths mounts.
That's a suggestion and we'll need to get a feedback from it.

**Comment by fvicaria** [comment]
Done and applied.
