### ISSUE TITLE
[NPC] Rare mobs loot tables (Report 1)

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Redemption#6022]
I noticed today in world chat people talking about rare mobs not dropping items as they should, so i thought while github was on 0 reports i would check these out as stated by janitor here on an older report  #5889

### i will wait and see what Rushor thinks about this report before making the other reports

![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/e93e71b5-b3d7-4c29-96bb-6cbf31b464bc)

**Links**
Conflicting info 

Mania 
Wowhead
Classic 

Classic seems to be nearest to what we have at mania atm - 1 - 50+ items missing 

- [ ] Mekthorg the Wild (7 items loot table instead of 16)
mania https://www.wow-mania.com/armory/?npc=18677#drops
https://wowclassicdb.com/wotlk/npc/18677

- [ ] Vorakem Doomspeaker (9 items loot table instead of 10)
mania https://www.wow-mania.com/armory/?npc=18679#drops
classic https://wowclassicdb.com/wotlk/npc/18679

- [ ] Chief Engineer Lorthander (11 items loot table instead of 12)
mania https://www.wow-mania.com/armory/?npc=18697#drops
classic https://wowclassicdb.com/wotlk/npc/18697

- [ ] Coilfang Emissary (6 items loot table instead of 18)
mania https://www.wow-mania.com/armory/?npc=18681#drops
classic https://wowclassicdb.com/wotlk/npc/18681

- [ ] Marticar (3 items loot table instead of 4)
mania https://www.wow-mania.com/armory/?npc=18680#drops
classic https://wowclassicdb.com/wotlk/npc/18681

- [ ] Molok the Crusher (505 items loot table instead of 515)
mania https://www.wow-mania.com/armory/?npc=2604#drops
classic https://wowclassicdb.com/wotlk/npc/2604

- [ ] Nimar the Slayer (397 items loot table instead of 406)
mania https://www.wow-mania.com/armory/?npc=2606
classic https://wowclassicdb.com/wotlk/npc/2606

- [ ] Prince Nazjak (404 items loot table instead of 409)
mania https://www.wow-mania.com/armory/?npc=2779
classic https://wowclassicdb.com/wotlk/npc/2779

- [ ] Ruul Onestone (380 items loot table instead of 390)
mania https://www.wow-mania.com/armory/?npc=2602
classic https://wowclassicdb.com/wotlk/npc/2602

- [ ] Zalas Witherbark (499 items loot table instead of 506)
mania https://www.wow-mania.com/armory/?npc=2605
classic https://wowclassicdb.com/wotlk/npc/2605

- [ ] Akkrilus (310 items loot table instead of 342)
mania https://www.wow-mania.com/armory/?npc=3773
classic https://wowclassicdb.com/wotlk/npc/3773

- [ ] Apothecary Falthis (374 items loot table instead of 435)
mania https://www.wow-mania.com/armory/?npc=3735
classic https://wowclassicdb.com/wotlk/npc/3735

- [ ] Branch Snapper (276 items loot table instead of 327)
mania https://www.wow-mania.com/armory/?npc=10641
classic https://wowclassicdb.com/wotlk/npc/10641

- [ ] Darkslayer Mordenthal (255 items loot table instead of 295)
mania https://www.wow-mania.com/armory/?npc=3736
classic https://wowclassicdb.com/wotlk/npc/3736

- [ ] Eck'alom (265 items loot table instead of 285)
mania https://www.wow-mania.com/armory/?npc=10642
classic https://wowclassicdb.com/wotlk/npc/10642

**Comment by bigchipbag** [comment]
I also had this issue today and thank you for reporting it before me!

**Comment by Echinaceax** [comment]
> I also had this issue today and thank you for reporting it before me!

Been difficult to get the correct evidence info tho lol wowhead is a lot of item ammounts where as classic is 1 or 2 item missing only, so i do think we have to go with the classic links as mania is from 2009

**Comment by Rushor** [comment]
The creatures are assigned with grouped loot, inside those there are only missing a few items - will add the missing ones. Amory for that will be updated in future, will give more infos in discord
