### ISSUE TITLE
[NPC] Rare mobs loot tables (Report 2)

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Redemption#6024]
**Links:**
mania
wowhead
classic

- [ ] Lady Vespia (330 items loot table instead of 386)
mania https://www.wow-mania.com/armory/?npc=10559
classic https://wowclassicdb.com/wotlk/npc/10559

- [ ] Mist Howler (287 items loot table instead of 327)
mania https://www.wow-mania.com/armory/?npc=10644#drops
classic https://wowclassicdb.com/wotlk/npc/10644

- [ ] Oakpaw (307 items loot table instead of 333)
mania https://www.wow-mania.com/armory/?npc=10640#drops
classic https://wowclassicdb.com/wotlk/npc/10640

- [ ] Prince Raze (395 items loot table instead of 407)
mania https://www.wow-mania.com/armory/?npc=10647#drops
classic https://wowclassicdb.com/wotlk/npc/10647

- [ ] Rorgish Jowl (296 items loot table instead of 336)
mania https://www.wow-mania.com/armory/?npc=10639
classic https://wowclassicdb.com/wotlk/npc/10639

- [ ] Ursol'lok (295 items loot table instead of 301)
mania https://www.wow-mania.com/armory/?npc=12037#drops
classic https://wowclassicdb.com/wotlk/npc/12037

- [ ] Antilos(388 items loot table instead of 391)
mania https://www.wow-mania.com/armory/?npc=6648#drops
classic https://wowclassicdb.com/wotlk/npc/6648

- [ ] Gatekeeper Rageroar (370 items loot table instead of 377)
mania https://www.wow-mania.com/armory/?npc=6651#drops
classic https://wowclassicdb.com/wotlk/npc/6651

- [ ] General Fangferror (529 items loot table instead of 535)
mania https://www.wow-mania.com/armory/?npc=6650#drops
classic https://wowclassicdb.com/wotlk/npc/6650

- [ ] Lady Sesspira (424 items loot table instead of 435)
mania https://www.wow-mania.com/armory/?npc=6649#drops
classic https://wowclassicdb.com/wotlk/npc/6649

- [ ] Scalebeard (336 items loot table instead of 337)
mania https://www.wow-mania.com/armory/?npc=13896#drops
classic https://wowclassicdb.com/wotlk/npc/13896

- [ ] Varo'then's Ghost (400 items loot table instead of 404)
mania https://www.wow-mania.com/armory/?npc=6118#drops
classic https://wowclassicdb.com/wotlk/npc/6118

**Comment by Rushor** [comment]
general fix applied that gives more items to the creatures, based on the level and entry
