### ISSUE TITLE
[Profession ] Fishing error "You don't have permission to loot that corpse" / empty loot / missing trash items

### ISSUE THREAD

**Issue by bigchipbag** [WoWManiaUK/Redemption#6025]
**Links:**
N/A

**What is Happening:**
I am fishing with a skill of 277 (+5 from pole) on the east coast of Tanaris at 67.21, 24.96
I didn't realize it at first but I was sometimes clicking my lure and nothing was getting fished. I then noticed I was getting the error at the top of my screen, "You don't have permission to loot that corpse" 

**What Should happen:**
All fishing loot should be owned by the casting player, so this error should never appear.

**Comment by bigchipbag** [comment]
Also sometimes when you click on the bobber, no error shows up, and no item is put into your inventory, like it does nothing.

**Comment by Echinaceax** [comment]
> Happens even when maxed : #5609

I cant reproduce the error message, I can only reproduce the empty loot issue reported on this one @WhitephoenixTheBunny

**Comment by Rushor** [comment]
I think this error happens when you are in a hidden not visual shown raidgroup

can you make sure to do: /script LeaveParty()

and see if it happens again?

**Comment by Echinaceax** [comment]
Then we just do the empty fish loot for now @Rushor ?

**Comment by bigchipbag** [comment]
> Then we just do the empty fish loot for now @Rushor ?
> 
> this shouldnt happen ![image](https://user-images.githubusercontent.com/39439201/261868202-137a8552-73d8-4b7d-9afd-0c0da7678b9d.png)
> 
> Also going to post newly found research here, seems its blizlike
> 
> ![image](https://user-images.githubusercontent.com/39439201/262760410-281735ca-e297-4681-b8e8-2631f5c5cfb2.png)

This applies to mobs, not fishing. I played vanilla wow and you always get something when fishing, even if it's junk.

**Comment by Echinaceax** [comment]
> This applies to mobs, not fishing. I played vanilla wow and you always get something when fishing, even if it's junk.

Ok, thanks, I will speak to Rushor about it

**Comment by Rushor** [comment]
missing items for the tanaris zone is added, but the generic blizzliuke bug from above will still happen

**Comment by Echinaceax** [comment]
> missing items for the tanaris zone is added, but the generic blizzliuke bug from above will still happen

1, Confirmed new trash loot added 
2, Confirmed bug still happens
