### ISSUE TITLE
Quest "The Plains of Nasam" objective not completing

### ISSUE THREAD

**Issue by bigchipbag** [WoWManiaUK/Redemption#6027]
**Links:**
![image](https://github.com/WoWManiaUK/Redemption/assets/2725389/07aca950-c862-41d7-a208-33d256d2a51e)
https://www.wow-mania.com/armory/?quest=11652

**What is Happening:**
Driving the siege tank to the structure where kel thuzad is is not triggering the objective "Scourge Leader identified"

**What Should happen:**
Driving up to the platform he is on should complete the objective.

**Comment by Echinaceax** [comment]
this has been reported before https://github.com/WoWManiaUK/Redemption/issues/3395 and no bug found
