### ISSUE TITLE
Shadowstalker Getry not available to complete quest "Get to Getry" 

### ISSUE THREAD

**Issue by bigchipbag** [WoWManiaUK/Redemption#6028]
**Links:**
![image](https://github.com/WoWManiaUK/Redemption/assets/2725389/ee29c11c-df86-4697-8de7-b2accb3dab81)
https://www.wow-mania.com/armory/?npc=25729#starts
https://www.wow-mania.com/armory/?quest=11703

**What is Happening:**
Questgiver is not present and has not appeared

**What Should happen:**
Shadowstalker Getry should be here

**Comment by Echinaceax** [comment]
NPC is there, he is up on the top of the ramp @bigchipbag

**Comment by Echinaceax** [comment]
NPC is there @bigchipbag 

![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/a560c68c-ec41-412b-85b0-7d689689008d)
