### ISSUE TITLE
Unable to Login on WoW-Mania Forum

### ISSUE THREAD

**Issue by Gabriel-le-Marks** [WoWManiaUK/Redemption#6029]
**Links:**

**What is Happening:**
I want to ask questions in the WoW-Mania Forum and even if I am already logged in, I need to login again but it doesn’t work

**What Should happen:**

I should ask my questions in the WoW-Mania Forum

**Comment by GMZinius** [comment]
Hello @Gabriel-le-Marks this is for in-game bugs only 
please contact a GM in-game or on discord
