### ISSUE TITLE
[Item] Mr. Pinchy's Magical Crawdad Box

### ISSUE THREAD

**Issue by Radolfes** [WoWManiaUK/Redemption#603]
Hello, i am trying from 2 weeks to get this item in Out land,and it say same every time - Your fish is going away............
As i think that is problem of the low skill,i was wrong.........now i am at 450 skill + natpadle fishing pole(+25) + sharped fish hook(+100) which mean that i am with fishing skill over 575 in out land and still nothing........
Thanks for the time,Regards.

**Comment by Brunnr** [comment]
I was fishing in the pools near Alerts yesterday with a total skill of around 400 including gear, and was getting crawdads from the highland pools. Got one crawdad box but no Mr. Punchy inside. Are you not catching anything in the highland pools? Your skill is more than enough, in fact I would try again with no hook so your skill is closer to the 400_450 range.

**Comment by fvicaria** [comment]
There's a 0.2% chance to get Mr Pinchy.
Mr. Pinchy has a 2 day cooldown for each of his 3 wishes that he provides.
You will only have about a 8% chance per wish to get the Magical Crawdad pet.
