### ISSUE TITLE
[Professon/Skinning] Firemane Dragonkin in Dustwallow yeilds empty loot table

### ISSUE THREAD

**Issue by bigchipbag** [WoWManiaUK/Redemption#6032]
**Links:**
https://www.wow-mania.com/armory/?npc=4331#skinning

**What is Happening:**
Skinning these Firemane dragonkin often results in no loot being available 
Skill 264

**What Should happen:**
Loot should be available

**Comment by Echinaceax** [comment]
Confirmed bug 
1st skinning window empty 
![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/82b83d31-c122-45d9-857c-f6f01d52c88b)
2nd not empty 
![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/e577338d-1d26-49c7-93a1-edb9407d3b65)
3rd not emply 
![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/9a3f0222-8fe6-497e-9c85-256f405dc852)

@Rushor 

- [ ] Something missing in the loot table

**Comment by Echinaceax** [comment]
From research loot tables are 5 items same as everywhere else and empty loot are normal from what ive seen

**Comment by bigchipbag** [comment]
They don't re-appear after having been skinned but yes I had auto loot on. I levelled past them and will not be returning, so fine to close for me
