### ISSUE TITLE
Vyragosa/time-lost proto-drake dissappearing from sight, and teleporting into terrain

### ISSUE THREAD

**Issue by Kilveton** [WoWManiaUK/Redemption#6033]
**Links:**

**What is Happening:**
Followed this dragon in storm peaks, earlier in the morning spotted her flying into temple of storms and after getting through the mountain she just dissappeared. Later in the noon she also dissappeared from me and went inside a terrain between brunnhildar village and the area right of engine of the makers. This kind of bugs make it pretty hard to get my time-lost proto when the npc keeps dissappearing into terrains and shit.

**What Should happen:**
The dragon should be visible when it's alive and easy to pull to fight with.

**Comment by Echinaceax** [comment]
Thanks for reporting @Kilveton 
please check this report here https://github.com/WoWManiaUK/Redemption/issues/6009#issuecomment-1640507354

**Comment by Kilveton** [comment]
Managed to kill her now, so we will have to wait for tomorrow. My case is not the same, she dissappeared two times before I even engaged her. Think it's a more general glitch.

**Comment by Echinaceax** [comment]
All new pathing smooth is confirmed in PTR
