### ISSUE TITLE
Client is crashing only with a particular character in Storm Peaks

### ISSUE THREAD

**Issue by SaurianDraeni** [WoWManiaUK/Redemption#6034]
**Links:**

**What is Happening:**

Flying in The Foot Steppes (Storm Peaks) I got to a point where client continued to crash with any movement. I could log back in with character on my flying mount but any movement caused the crash.
I managed to levitate to the ground and HS back to Dalaran.
Screen shot of windows crash 

![Screenshot 2023-08-28 073350 wow crash](https://github.com/WoWManiaUK/Redemption/assets/111466553/57d8a67d-5a11-4ac1-b6f6-8d4abfb1a7db)

**Comment by GMZinius** [comment]
Thank you for reporting this is @SaurianDraeni 
This is a client issue not an in game bug that cannot be fixed from the Dev team.

### "Failed to read file" is a clear indicator.

- It is very important to be using the Mania client
- uncheck the "read-only" from your Mania folder
- Run the launcher as admin

These steps should fix your issue
