### ISSUE TITLE
[Minor]Sons of Hodir stay toggled "At War" even after completing attunement quests

### ISSUE THREAD

**Issue by bigchipbag** [WoWManiaUK/Redemption#6036]
**Links:**

**What is Happening:**
The Sons of Hodir reputation group remains toggled to At War even when completing the chain quest to become friendly with them. 
![image](https://github.com/WoWManiaUK/Redemption/assets/2725389/66e8cf4a-4c19-4f28-9bc5-baa5f1fa798d)

**What Should happen:**
In classic/vanilla, once you completed the attunement through Throrim, you should not remain in-conflict with them once the quests are completed to be friendly.

**Comment by Echinaceax** [comment]
https://github.com/WoWManiaUK/Redemption/issues/5736
If you have done 
[Mending Fences](https://www.wow-mania.com/armory/?quest=12915)
[A Spark of Hope](https://www.wow-mania.com/armory/?quest=12956)
Have you [Forging an Alliance](https://www.wow-mania.com/armory/?quest=12924) in your questlog still or completed that one also @bigchipbag

**Comment by Echinaceax** [comment]
Closing this for now
