### ISSUE TITLE
[NPC] Agitated stratholme citizen - Some are spawned in the wrong building - The Culling of Stratholme

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Redemption#6037]
**Links:**
As stated here by bLeyaa https://github.com/WoWManiaUK/Redemption/issues/4381
https://wowpedia.fandom.com/wiki/Agitated_Stratholme_Citizen

**What is Happening:**

- [ ] Agitated Stratholme Citizen should NOT be in the building 
at timetamp 0:14 you will see Agitated Stratholme Citizen transform into an Infinate agent, and that is not how they are meant to work as stated by bLeyaa in his other report linked above 
https://i.gyazo.com/cf2b4c9e5bb6caac51ecd3ec883e0953.mp4

(they are meant to transform into [Risen Zombies] and therefor not meant to be in that building at all (https://wowpedia.fandom.com/wiki/Risen_Zombie) 

we have 2 in that first room, Arthas kills 1 and 1 transform into an Infinate agent

![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/be9d66f1-12f8-4b06-9ae1-7abfe767bd7d)

![Agitated stratholme citizen](https://github.com/WoWManiaUK/Redemption/assets/39439201/26993863-24fa-4005-b7ac-c1ef7a0f6b27)

**What should happen**
As you can see here at timestamp 14:50 they are 2 Stratholme Citizen's and 1 Stratholme Resident
https://www.youtube.com/watch?v=PvtsLfBOwec

Our Agitated stratholme citizen's shouldnt have this dialog lol ❌ 

![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/02dabe22-3dd3-46c2-a9a3-7c5efcb8bc64)

The dialog should be from a Stratholme Citizen ✔️ 

![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/7293ad80-0401-41d2-bf90-0194ea92ccfa)

![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/0fc9319a-622e-431c-a8e5-b70d4988e032)

**Comment by Lumber-Jack-2** [comment]
creature versions and texts adjusted to fit the video ones

**Comment by Echinaceax** [comment]
Fixed in PTR 
![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/0c96f9c7-8dc5-4195-a87f-edd366db0d33)
![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/d5b346ff-68fb-4c02-986c-52ca1f63f70b)
