### ISSUE TITLE
Ulduar 10 - Razorscale Encounter stuck waiting for Expedition Commander to start the fight

### ISSUE THREAD

**Issue by bigchipbag** [WoWManiaUK/Redemption#6039]
**Links:**

**What is Happening:**
Expedition commander does nothing, everyone including boss just stands around (5 Sept 2023 ID:883)

**What Should happen:**
The enounter should start.

**Comment by GMZinius** [comment]
Thank you for reporting @bigchipbag 
Please use in-game ticket system for help
