### ISSUE TITLE
[Quest] Fires Over Skettis : monstrous kaliri egg issue

### ISSUE THREAD

**Issue by Woofles** [WoWManiaUK/Redemption#6040]
Quest : [Fires Over Skettis](https://www.wowhead.com/wotlk/quest=11008/fires-over-skettis)
Quest objective : [Monstrous Kaliri Egg](https://www.wowhead.com/wotlk/object=185549/monstrous-kaliri-egg) 
Quest item provided : [Skyguard Blasting Charges](https://www.wowhead.com/wotlk/item=32406/skyguard-blasting-charges)

**What is Happening:**
When shot the eggs break, you get quest progress but shooting the same spot even when they disappear after a few seconds still counts and you can just stay in one spot shooting every 5 seconds (item cd)

**What Should happen:**
You should only get credit for shooting them when they are visible and not broken.

Consecutively this bug makes the achievement [Bombs Away](https://www.wowhead.com/wotlk/achievement=1275/bombs-away) easy as 1-2-3.

**Comment by Woofles** [comment]
Quest with same mechanic that doesnt have that issue [Bomb Them Again!](https://www.wowhead.com/wotlk/quest=11023/bomb-them-again)
[Fel Cannonball Stack](https://www.wowhead.com/wotlk/object=185861/fel-cannonball-stack)
[Sqyguard Bombs](https://www.wowhead.com/wotlk/item=32456/skyguard-bombs)

**Comment by GMZinius** [comment]
Thank you for reporting @Woofles

**Comment by Echinaceax** [comment]
Quest cedit Bugged confirmed
https://i.gyazo.com/cdb6fc2e7e948dee25326a592da3e573.mp4

 

> Consecutively this bug makes the achievement [Bombs Away](https://www.wowhead.com/wotlk/achievement=1275/bombs-away) easy as 1-2-3.

@Woofles 
Did you get the achv while doing this?
coz i didnt, and i was using the stop watch 

![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/9bbe6df9-bc3f-4e5a-906c-d7d2746dd0ec)
![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/16b263fd-e3db-47fa-a7c5-c2e30d3ee882)

**Comment by Woofles** [comment]
"I did get it but didnt even know/remember there was one while doing it
Also i just add the achievement to watch list with the quests if i need to track it
It starts a timer automatically once you take the quest
(was only focused on [Bombs Away](https://www.wowhead.com/wotlk/achievement=1275/bombs-away) last couple days apart from loremaster)
Probably was done with around 30 sec left but it wa really just sit and spam
1st shot they visually glitched for a split second to default unbroken state and thought id shoot again"

"But that sort of glitch happens with nearly evrything igame so i didnt include it (be it server lag or ui lag)"

**Comment by Rushor** [comment]
issue was that the trigger for that did not despawned, added that despawn now for the eggs

**Comment by Echinaceax** [comment]
Fixed in PTR

- [ ] Egg triggers despawn correctly
