### ISSUE TITLE
[Spell] Mirror Image

### ISSUE THREAD

**Issue by Dredziarz** [WoWManiaUK/Redemption#605]
Hello,
it's me again. i'm tried contact with you guys during the raid 3 days ago but nobody was online.
Confirm my theory about bugged skill i'm made the screenshot for you.
On this screen you can see our battle on 25hc Sindragosa. We were at 2min of battle and i had 
unimaginable size of threat. i wasn't? Just watch on next for me player with name Necrossis had 1/10 my threat. It's impassible to explain how much i was lucky when Tank had 2 sec on taunt to get himself higher in Omen.
it's a screen >>>https://zapodaj.net/335e58160a28a.jpg.html

Please help me because i can't do the best i can.
Regards Dredziarz.

**Comment by fvicaria** [comment]
When have you tested it? It was fixed on yesterday's update (afternoon). So unless you tested it last night I will ask to test it again.
Comment here and I will re-open.

**Comment by Dredziarz** [comment]
it was  a screenshot from 11.12.2016 at 22:40 Server Time.

2016-12-15 9:15 GMT+01:00 Janitor <notifications@github.com>:

**Comment by fvicaria** [comment]
Exactly so before the fix which was on the 14th. Can you try again please.

**Comment by Dredziarz** [comment]
i have to w8 on next raid 25n/hc  because now i have 3 days i a row in work
per 14-16h every day. probably i will check it in next week.

Thanks for Help.

2016-12-15 13:01 GMT+01:00 Janitor <notifications@github.com>:

**Comment by Dredziarz** [comment]
Hello officers, i have a one question. i need 3 items to totally biss mage.
I don't have any small/little chance for get it. i'm talk about Ring from
Gunship 25hc, 1 x Heroic mark, and Off hand from Blood Counsil 25hc. i'm
from Poland and i'm really poor and i earn 400 GPB per full work's Month.
i'm the best mages on the serwer and i'm the person without conflicts. I;m
sure you can give me little much favorable offer for 1 of these items. i'm
prefer the off hand. i don't anything more to establish records of DPS on
this serwer.
Please answer me for my letter and try understand me <3

2016-12-15 19:41 GMT+01:00 Wojtek Nandzik <piotrekmanunited@gmail.com>:

**Comment by RikRetard** [comment]
Donate money to Janitor 30 gbp per item and they're yours. GG WP

**Comment by RikRetard** [comment]
Donate the money to janitor and get items gg wp

**Comment by Dredziarz** [comment]
Maybe it's a problem when i use all my burst macro, because when i use.
/use Combustion
/use Mirror Image
/use Berserking
/use Hyperspeed Accelerators

and my cast time on Fireball start be close to 1.2sec. Maybe you can check
it out.

2017-01-16 14:10 GMT+01:00 RikRetard <notifications@github.com>:

**Comment by Dredziarz** [comment]
i didn't get a money from Restaurant yet. because atm we don't have too
many clients.

2017-01-16 15:07 GMT+01:00 Wojtek Nandzik <piotrekmanunited@gmail.com>:
