### ISSUE TITLE
Few rogue talents are not working properly

### ISSUE THREAD

**Issue by Rogueplayer1** [WoWManiaUK/Redemption#6050]
Talent Blood Spatter from assassination tree does not give 30% more damage, instead it gives 10% only, same goes for talent Serrated Blades from Subtlety tree, i tested it multiple times. For example i have 3000 damage from rupture and when i put 2/2 into Blood Spatter for 30% more damage i should be getting 30% more of 3000 damage, so that would be 3000x30%= 900 more damage, that means 3000+900=3900 damage, instead i get 3300 damage. Serrated Blades should also give 30% more damage, but it also gives 10% more only. 

Please take a look into the matter

Kind regards

**Comment by hammereddann** [comment]
I have tested this and I can confirm this is working as intended. Here is my calculation and diagrams for your attention
![image](https://github.com/WoWManiaUK/Redemption/assets/122736582/6f95b173-2345-48dc-a8b1-b9ad0128e045)
This is rupture without Blood splatter - 856 damage over 8 seconds on 1 combo. 
![image](https://github.com/WoWManiaUK/Redemption/assets/122736582/45a0b622-e8f0-4376-b8fd-a76c65e03682)
This is rupture damage with Blood Splatter - 1008 damage over 8 seconds on 1 combo. 

This math should actually be 1112.8. Tooltip is slightly off but the numbers from the ticks of rupture do actually amount to the correct number 1112.8

![image](https://github.com/WoWManiaUK/Redemption/assets/122736582/1c286639-05d3-4197-8495-f4bd7f20993c)
 278x4 ticks = 1112
 
 30% of 856 = 256.8
 856 + 256.8 = 1112.8
