### ISSUE TITLE
[Quest] A Crystalforged Darkrune - missing quest text

### ISSUE THREAD

**Issue by Woofles** [WoWManiaUK/Redemption#6051]
[A Crystalforged Darkrune](https://www.wow-mania.com/armory/?quest=11060) - missing all of its description.
Not a big issue since it becomes available at the same time and from same npc as quest that rewards the required item. [Banish the Demons](https://www.wow-mania.com/armory/?quest=11026)
Last related issue didnt seem to have that problem #3133 

![image](https://github.com/WoWManiaUK/Redemption/assets/4690356/1aa7cc43-d18f-4b10-8478-14fef4d316b9)

**Comment by Echinaceax** [comment]
Thanks for reporting @Woofles 

Accept window

![image](https://github.com/WoWManiaUK/Redemption/assets/108176634/4abeafdd-7852-420c-9565-6abff1e30f7e)


Video timetamp 10:01 https://www.youtube.com/watch?v=fVh7EY0Dovo&t=601s


Da demons are making da [Forge Camp: Wrath](https://wowpedia.fandom.com/wiki/Forge_Camp:_Wrath) bigger. Soon, dey be too big and crush us. You crush dem first!

Shartuul's transporter is da key, but it protected by a magic shield and a demon called a degrader. Us powerful [warlock](https://wowpedia.fandom.com/wiki/Warlock), and make special darkrune dat give you control of da degrader. <Race> give [Gahk](https://wowpedia.fandom.com/wiki/Gahk) darkrune, us give <race> crystalforged darkrune back.

Take control of da degrader and possess as many of da demons dat come through da gate as you can ta stop dem!

Inv misc rune 04 [[Darkrune]](https://wowpedia.fandom.com/wiki/Darkrune)

**Comment by Echinaceax** [comment]
Note though after i abandoned the quest and picked it up again, the issue isnt there 

![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/e4a9244c-fe5d-40ba-b618-44ba0701a4ea)

**Comment by Rushor** [comment]
there is no details on the quest info it should have, except the info we already have.
added a similar text, requires cache clear :)

**Comment by Echinaceax** [comment]
Fix in PTR 

![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/a502b3fb-849a-4b07-9348-2efa368265d1)
![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/852151a7-ec2b-4e73-8fbf-15b72c8e42b6)
![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/c514c5a6-a92d-48bd-9121-90d73c099351)
![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/27ce81c1-89d2-404d-863d-836adb04c99b)
