### ISSUE TITLE
[Quest] - Inside the Frozen Citadel - Players not attuned for FoS PoS HoR (RDF) 

### ISSUE THREAD

**Issue by bigchipbag** [WoWManiaUK/Redemption#6052]
**Links:**

**What is Happening:**
Players who have not completed the attunement quest from FoS to PoS to HoR can be randomly queued into PoS (confirmed) and then cannot port in, then are forced to get deserter from random heroic rendering them useless and unable to do queue dungeons for half an hour.

**What Should happen:**
The queue should never assign that dungeon when queued players are not attuned.

**Comment by Echinaceax** [comment]
**Attunement quests order**

Inside the Frozen Citadel https://www.wow-mania.com/armory/?quest=24506
Echoes of Tortured Souls https://www.wow-mania.com/armory/?quest=24511
The Pit of Saron https://www.wow-mania.com/armory/?quest=24682
The Path to the Citadel https://www.wow-mania.com/armory/?quest=24507
Deliverance from the Pit https://www.wow-mania.com/armory/?quest=24712
Frostmourne https://www.wow-mania.com/armory/?quest=24713

**Opens Quests**
Wrath of the Lich King https://www.wow-mania.com/armory/?quest=24802

**Comment by Rushor** [comment]
prev quest conditions are applied

**Comment by Echinaceax** [comment]
Fixed in PTR 

- [ ] Players must have completed each prequest

![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/9326f6f0-4fda-4e1e-ba3b-18e7b0a094fe)
