### ISSUE TITLE
(Quest) Uniting the Shattered Amulet - no Fel Salve option

### ISSUE THREAD

**Issue by efiltsohg** [WoWManiaUK/Redemption#6054]
**Links:** https://www.wowhead.com/wotlk/quest=3627/uniting-the-shattered-amulet
https://www.wowhead.com/wotlk/item=11582/fel-salve

**What is Happening:** For this quest, the quest-giver is supposed to have a dialog option to offer you an item called "Fel Salve" if you have sold or destroyed the weapon earned on the previous step (https://www.wowhead.com/wotlk/quest=3625/enchanted-azsharite-fel-weaponry).  The quest cannot be completed if you no longer have an Enchanted Azsharite Fel Weapon.

**What Should happen:** Fallen Hero of the Horde in Swamp of Sorrows should have a dialog option
<img width="260" alt="249482796-21452691-7a21-4980-9958-362f1222ddb7" src="https://github.com/WoWManiaUK/Redemption/assets/44076655/2f3a8dcb-d304-4fce-b084-11501227bd31">

**Comment by GMZinius** [comment]
Thank you for reporting this issue @efiltsohg 
We will get this checked and confirmed

**Comment by Echinaceax** [comment]
confirmed dialogs are missing

seen here https://www.youtube.com/watch?v=jSoHkn6fohY

wowhead comments 
![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/e9edd546-77b0-4141-a0c2-6e3b6c95b401)
![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/0b3a1339-9903-47ba-9dd6-706c77d2ddf1)


ours 

![Missing dialogs](https://github.com/WoWManiaUK/Redemption/assets/39439201/846cdc40-e55b-4b3c-a289-679bdd845cdd)

**Comment by Rushor** [comment]
when taking the quest, you will now see a gossip option to get that item

**Comment by Echinaceax** [comment]
Fixed in PTR 

![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/a4c61591-ba7c-4ac5-9665-d8547a642c3e)
![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/57d30c64-b42a-4611-a94a-da590713e72d)
