### ISSUE TITLE
[NPC] Orbaz Bloodbane elite - wrong chat quotes

### ISSUE THREAD

**Issue by Woofles** [WoWManiaUK/Redemption#6055]
**Links:**
[Orbaz Bloodbane](https://www.wowhead.com/wotlk/npc=31283/orbaz-bloodbane#comments)

**What is Happening:**
Npc is objective of [The Fate of Bloodbane](https://www.wowhead.com/wotlk/quest=13164/the-fate-of-bloodbane), last in questline.
All the lines he says are the same and from a horde quest npc ([Xarantaur](https://www.wowhead.com/wotlk/npc=30381/xarantaur) ) in Storm Peaks.
![image](https://github.com/WoWManiaUK/Redemption/assets/4690356/20378dda-f064-4c5e-bd3a-51f12dc5cb38)
![image](https://github.com/WoWManiaUK/Redemption/assets/4690356/2880406c-7f7a-4eb9-a60b-43f0ecc8fc88)

**Comment by Echinaceax** [comment]
confirmed bug 
hes on repeat 😄 

![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/ae2b29a9-cb85-4398-8063-f319ab3210ee)

**Comment by Echinaceax** [comment]
Fixed in PTR 

![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/ba7ba0bb-44aa-4723-b964-b5c5e67ee516)
