### ISSUE TITLE
[Zone] Deeprun Tram - Bugs on track 2

### ISSUE THREAD

**Issue by Nightowlamerz** [WoWManiaUK/Redemption#6056]
**Links:**

**What is Happening:** The tram glitches out and I hear it but don't see it.

**What Should happen:**
Both trams should function normal.

**Comment by GMZinius** [comment]
Please make sure you are using the mania client and it is updated

**Comment by Nightowlamerz** [comment]
it is

**Comment by GMZinius** [comment]
> it is

Ok, Thank you @Nightowlamerz 
We will have a tester check this out

**Comment by Echinaceax** [comment]
https://www.wowhead.com/zone=2257/deeprun-tram

Confirmed bug 

Reproduce steps
1. I recorded 7mins 35secs of the two tram tracks in Ironforge
2. 3 right side trams came in that time 0 left side https://i.gyazo.com/738129e3a6f1627bbc9c6666cb49b401.mp4
3. I ran halfway down the broken tram track and it triggered that tram to move on the left side track https://i.gyazo.com/395b2f6f4799ac31e1c8a9858f1acbac.mp4
4. Both tracks  https://i.gyazo.com/70bb49ef6417233131b6094851809e5d.mp4
5. And now the left track has bugged again 

Track GPS @Rushor 

![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/e7d8916a-e637-4056-8b62-d6325e2dacc0)

**Comment by Rushor** [comment]
will try to set it active to prevent that issue

**Comment by Echinaceax** [comment]
> Still bugged

yes we know, its not been fixed yet @Nightowlamerz

**Comment by Echinaceax** [comment]
Still not fixed @Rushor 

Still only one track working until you run up the other track to activate the 2nd tram 

https://i.gyazo.com/6ac23b7d9b6bb039ebde7b9b5bae2b77.mp4

only fixes when i run up the broken track https://i.gyazo.com/095d5b93f9ae0731b7eaa41f30a0dba8.mp4

**Comment by Echinaceax** [comment]
Fix confirmed in PTR 

Monty Ironforge https://i.gyazo.com/a0b2ba4d87e282c035864450dbb9e02e.mp4
Nipsy Stormwind https://i.gyazo.com/a046b8b58dacc21cdba0f9957275e7c0.mp4
