### ISSUE TITLE
Windowed Mode

### ISSUE THREAD

**Issue by Nightowlamerz** [WoWManiaUK/Redemption#6057]
**Links:**

**What is Happening:**When I select windowed mode on wow the screen goes black and does not recover. I hear the wow music still, just id completely black screened until I ESC it.

**What Should happen:**
Screen mode should switch smoothly from full screen to windowed mode with out issues or black screening without no recovery.

**Comment by GMZinius** [comment]
Please read the FAQs on mania discord 
「 ✦ Windowed mode/Black screen issue ✦ 」

**Comment by Nightowlamerz** [comment]
Thanks
