### ISSUE TITLE
infinite debuff :(touch of zanzil) in the quest :klaven's tower

### ISSUE THREAD

**Issue by bramyknocker** [WoWManiaUK/Redemption#6058]
**Links:**

**What is Happening:**
i opent the chest i should not be able to do that before i got the key. 
now i cant finish the quest cuss i dont have the key. but i do have this debuff poison on me now (touch of zanzil)
i cant get the key cuss i cant turn stealth mode on my rogue to pickpocket the key of the guard.
the poison prevents me to turn in to stealth mode. the poison has a count down of 7 days, but its not counting down.
if i reset the quest it does not fix my problem. the poison stays.

conclusion now i m  a rogue who cant turn in to stealth XD 
cant finish quest and cant stop the debuff

**What Should happen:**
my charr name is : (fisherman) and account name: bramyknocker
i hope you can help me to get rid of this infinity debuff.
thanx!

**Comment by Echinaceax** [comment]
might be an idea to check @bramyknocker  here https://github.com/WoWManiaUK/Redemption/issues/5932#issuecomment-1278005341
its not a bug
