### ISSUE TITLE
[NPC/Spell] Muckshell Snapclaw/Poison - stacking

### ISSUE THREAD

**Issue by GMZinius** [WoWManiaUK/Redemption#6060]
**Links:**
NPC https://www.wow-mania.com/armory/?npc=4402
Spell https://www.wow-mania.com/armory/?spell=25645

**What is Happening:**
Was reported by player that the damage is insane, so I checked it.
- The poison spell buff is stacking every 4 secs and increasing damage output each stack. 

![image](https://github.com/WoWManiaUK/Redemption/assets/108176634/6f5345b0-2731-4a6d-8c8f-99b4594bb3c8)

Mania (shows icon 5 stacks)

![image](https://github.com/WoWManiaUK/Redemption/assets/108176634/f02d2717-d4ab-4da6-9d9b-1a967ee80d00)

Wowhead 1 only

![image](https://github.com/WoWManiaUK/Redemption/assets/108176634/b3a2467c-1b7b-43ac-98ae-3d6c5a95428c)

**What Should happen:**
- Should'nt stack 
![image](https://github.com/WoWManiaUK/Redemption/assets/108176634/06e42c4d-f8db-44ec-8a19-e43923dea728)

**Comment by Keader** [comment]
can u test again?

**Comment by Echinaceax** [comment]
Fix confirmed, only 1 stack now
