### ISSUE TITLE
[Vehicle/Cannon] - Ulduar siege engine / ICC cannons / WG cannons

### ISSUE THREAD

**Issue by bigchipbag** [WoWManiaUK/Redemption#6063]
**What is Happening:**
If someone is driving a siege engine in Ulduar with an open second seat, and two people click on the vehicle at the exact same time, one person gets put into the gunner and one person gets stuck inside the siege engine and literally can't do anything - can't logout, can't use spells, can't use /leavevehicle 

**What Should happen:**
I actually don't know. I would hope there isn't an error condition like this but maybe it is blizzlike?

**Comment by bigchipbag** [comment]
Here is a quick video I got before I died. You can see I'm in a siege engine with a gunner already, as the third person, before I die. like I'm just stuck in it. 
https://github.com/WoWManiaUK/Redemption/assets/2725389/d059e847-ee73-49eb-a124-b85fd9b442ee

**Comment by Echinaceax** [comment]
let us know if this happens again @bigchipbag 
could be an addon confliction issue, if you has no leave vehicle button on your vehicle tastbar

**Comment by Maine1** [comment]
This happens with all vehicle types, Cannons on gunship in ICC, cannons on WG, everything. Player needs to full relog if they do get stuck. reloading will not work

https://i.gyazo.com/854bfaffd4cd9a560ed6c7dbfaccfa11.mp4
Me and @Echinaceax seen here testing this and I got stuck and could not move forward or backwards @Keader

**Comment by hammereddann** [comment]
https://i.gyazo.com/854bfaffd4cd9a560ed6c7dbfaccfa11.mp4

**Comment by bigchipbag** [comment]
Good work getting it figured out!

**Comment by Lumber-Jack-2** [comment]
wil move this to private
