### ISSUE TITLE
[Object] Warsong Gulch Door -  Remains visable after battleground starts

### ISSUE THREAD

**Issue by bigchipbag** [WoWManiaUK/Redemption#6065]
**Links:**

**What is Happening:**
![image](https://github.com/WoWManiaUK/Redemption/assets/2725389/3a4de0c1-6da8-495e-b8fb-4f83d195724b)
The visual of the collapsed door letting you in to Warsong sticks around the whole match

**What Should happen:**
They should open up then slowly fade out

**Comment by Echinaceax** [comment]
Confirmed open gates do not despawn on both entrances, https://i.gyazo.com/91c7a1370c7a7e94e1cb0e9cef4026e1.mp4

14 years ago Timestamp 1:36 https://www.youtube.com/watch?v=k5_SjFkz6OM
11 years ago Timestamp 2:05 https://www.youtube.com/watch?v=3CgIEvxR1do
3 years ago Timestamp 2:34 https://www.youtube.com/watch?v=292nBG1qqP8

**Comment by Echinaceax** [comment]
Not quite right @Rushor

**Comment by Lumber-Jack-2** [comment]
new fix:

doors open after 2 minutes - added that after 2minutes and 5 seconds they will switch phase to 4.
Phase 4 cannot be accessed by player. So it will be invisible for them.

So important to test with gm off :>

**Comment by Echinaceax** [comment]
Much better thx 

https://i.gyazo.com/b9b5a17caa6890041cd0e501f77f1734.mp4
