### ISSUE TITLE
(NPC) Masat T'andr not neutral for Horde

### ISSUE THREAD

**Issue by efiltsohg** [WoWManiaUK/Redemption#6066]
**Links:** https://www.wowhead.com/wotlk/npc=11874/masat-tandr

**What is Happening:** the NPC Masat T'andr in Swamp of Sorrows is supposed to sell leatherworking items and recipes, but he appears as hostile to Horde players and they cannot talk to him.  The first screenshot shows how he appears to me.

![Untitled1](https://github.com/WoWManiaUK/Redemption/assets/44076655/de72a404-ba3e-4769-9b52-c6a154aad2d3)

**What Should happen:** Masat T'andr should appear friendly to Horde and be interactable as a salesperson.  The second screenshot shows how he should appear to Horde.

![Untitled2](https://github.com/WoWManiaUK/Redemption/assets/44076655/e3f035d6-5d8a-401c-bf7e-3fb5dced451b)

**Comment by Echinaceax** [comment]
@Rushor from what ive found is that before 4.0 this NPC is meant to be neutral for horde and Alliance 
https://wowpedia.fandom.com/wiki/Masat_T%27andr

**Comment by Lumber-Jack-2** [comment]
alright thank you!

**Comment by Echinaceax** [comment]
fix confirmed in PTR 

![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/0a2f393d-fe2e-42ec-b506-5baa62e39d31)
