### ISSUE TITLE
[Quest] [NPC] Seeds of Chaos – kill credit

### ISSUE THREAD

**Issue by Greywolf59** [WoWManiaUK/Redemption#6067]
Quest: [Seeds of Chaos](https://www.wow-mania.com/armory/?quest=13172)

Video 2015: https://www.youtube.com/watch?v=FmJRsvaRo90&ab_channel=GitGudGuides

Issue: The kill count is awarded only for [Risen Laborer](https://www.wow-mania.com/armory/?npc=31555).

The kill count should be awarded also for [Restless Lookouts](https://www.wow-mania.com/armory/?npc=30951)

Taking in consideration the video is from 2015, it is still worth to point out that on the video it is seems the phase changed. All the Plaguehound are sleeping and Restless Lookouts are running around. This could be in accordance with the fact that all three NPCs have two separate IDs on Mania armory and it would make sense that the standing Lookouts (from earlier phase) do not count towards the kills.

NOTE: Tested on Naxx realm.

**Comment by Echinaceax** [comment]
From looking at wowhead objective for the [Restless Lookouts](https://www.wow-mania.com/armory/?npc=30951) https://www.wowhead.com/wotlk/npc=30951/restless-lookout#objective-of are the same as mania has atm

**Comment by Lumber-Jack-2** [comment]
requires cache clear

**Comment by Lumber-Jack-2** [comment]
alright next try https://gyazo.com/751da3855da4d4979c60aa8d5dd0397d

**Comment by Echinaceax** [comment]
Confirmed fixed in PTR now, thx rushor 😄 

https://i.gyazo.com/3a493bf8381614ece2774406f746e12a.mp4
