### ISSUE TITLE
City of Light - Two players start the quest, only one sees whispers

### ISSUE THREAD

**Issue by bigchipbag** [WoWManiaUK/Redemption#6069]
**Links:**
![image](https://github.com/WoWManiaUK/Redemption/assets/2725389/2e3b9603-42f5-4211-957c-e8239c9e252c)
![image](https://github.com/WoWManiaUK/Redemption/assets/2725389/d1436f97-f1d8-4289-a60b-a09042812420)

https://www.wow-mania.com/armory/?quest=10211
**What is Happening:**
I started the quest within seconds on two characters, and only the first one got any whispers from Khadgar's servant, and received two whispers per dialog, and the other character received no whispers. 

**What Should happen:**
Each player should see the whispers.

**Comment by bigchipbag** [comment]
Additionally, the second player did not receive quest credit

..and I have to waste another 8m30s walking with this stupid elemental again

**Comment by Lumber-Jack-2** [comment]
whisper is only for one player - cannot change that.

but credit should be rewarded for both players. but the ymust be in a group

**Comment by bigchipbag** [comment]
Yeah it was just very strange both whispers went to one character.
Also is it fixed that it awards for completion in a group or was it like that? The two characters I started it on were on a group together and credit was not received

**Comment by Echinaceax** [comment]
Yes group will be rewarded once we have confirmed the fix, then it will go live on the next server update @bigchipbag

**Comment by Echinaceax** [comment]
Fixed in PTR 

Grouping with Maine then Maine shared the quest with me.
2 guardians spawned with us
Both completed the quest 

![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/a2f8e27a-f496-4363-8d60-78b9ac790c51)

**Comment by bigchipbag** [comment]
Exact same issue with Quest "The Caverns of Time" 
![image](https://github.com/WoWManiaUK/Redemption/assets/2725389/f48e117b-9f82-47c6-90c3-ea46fa91bb69)

Credit is not given to both players. 
![image](https://github.com/WoWManiaUK/Redemption/assets/2725389/a830cb72-0c9b-41c6-b764-19902315966d)

Another 8m I'll never get back lol

**Comment by Echinaceax** [comment]
> Exact same issue with Quest "The Caverns of Time" 

Please make separete issue for this one. this report is fix and ready for live update
