### ISSUE TITLE
[Object] SoTa gate bug - Battle Ground 

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Redemption#6070]
**Links:**
Visual render distance bug 1 https://i.gyazo.com/69732c617632e02e0347573afab5635c.mp4
Visual render distance bug 2 https://i.gyazo.com/957dcb4d43c17b89d8282250d1bedf23.mp4
Gate was taken down by Maine and not down for me https://i.gyazo.com/3cf1f80ed39ae4a06d15167e3bd62d21.mp4
Gate was taken down by Maine but not for me, and as you can see i take damage but cant run though the gate myself 
https://i.gyazo.com/8ef6a6ca0c5eeb9d7e449650ecd153cc.mp4

**What is Happening:**
- [ ] Render distance of gates
- [ ] Bugged gates for some players and not for everyone (its a very strange one)

**What Should happen:**
Gates should be visible when players get off the ship/ or when at a certain distance
Broken Gates should be accessable for all players 

Extra info 

Even shows the gates down on the map and says in chat that they are distroyed 
And note it happens to any random gate not just the RED and BLUE ones

![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/40fe21d8-8aa0-4c5b-b5d9-efec2a98b148)
![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/d83608f0-9d7a-45a4-a91d-3a0378d298ab)

![sota map ](https://github.com/WoWManiaUK/Redemption/assets/39439201/f10d4a1d-a3f9-469e-a390-06505257dab8)

**Comment by Lumber-Jack-2** [comment]
Can be fixed with active setting now

**Comment by Echinaceax** [comment]
- [x] Render distance fixed 
- [ ] Bugged doors not fix https://i.gyazo.com/60191d6375cdacd065347434c7327fa8.mp4

We both cleared cache for this test

**Comment by Lumber-Jack-2** [comment]
Next try - needs recheck of render distance aswell - will lt you know in disc once fix is active

**Comment by Echinaceax** [comment]
Same as before, but different gate, not fixed 

![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/54574c9d-6f5c-4d21-9eb8-d8689352e3e7)

Maine cant see gate down and cant go throught it 

![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/1f6a9f48-b8ea-4570-9e0d-a64ed7b78ee9)

**Comment by Echinaceax** [comment]
All good now thx @Rushor 
Fix confirmed in PTR
