### ISSUE TITLE
Shadow Labs - Murmur is casting resonance even when someone is in melee range

### ISSUE THREAD

**Issue by bigchipbag** [WoWManiaUK/Redemption#6071]
**Links:**
https://www.wowhead.com/tbc/npc=18708/murmur#comments

**What is Happening:**
Murmur, final boss of shadow labs, is constantly casting resonance dealing crazy damage to the group, when this should only happen when no one is in melee range

**What Should happen:**
As above, should only be cast when no one is in melee range

**Comment by bigchipbag** [comment]
"Resonance – After Murmur has been agro’ed if no one is in melee range he will debuff the party with Resonance increasing Nature damage taken by 2000. He will renew this debuff every 5 seconds and the party will take damage equal to how much extra Nature damage Resonance adds"

we all stood in melee range to prove this and we were getting nuked

**Comment by Echinaceax** [comment]
This was fully reworked @bigchipbag last year old report here https://github.com/WoWManiaUK/Redemption/issues/5738
Please check this out 

`we all stood in melee range to prove this and we were getting nuked`

When reporting it also helps to have a small video clip of the issue or screenshots of damage numbers etc...

edit
I checked from the old report, and nothing with Resonance was done, so yes that could be still an issue that got overlooked.
![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/bd219ad4-0498-4225-bd58-53ac89e8bd1e)


Notes 
![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/f934f33a-d717-44ca-a74d-d039456dbd0f)

**Comment by bigchipbag** [comment]
We will have to form a group to get to the end of shadowlabs just to expect a wipe so I doubt I'll be able to recreate the exact mechanics but I Wil bring a level 80 and try to get a video.

It was happening consistently, even with five players running in and standing right inside the boss. The druid tank even charged in. I can say with 100% certainty we were doing it correct as we all looked up strategies after the third wipe and run in. 

It makes the boss unkillable at level 70, and heroic will probably be impossible.

**Comment by bigchipbag** [comment]
Okay I ran the dungeon myself with an alt on follow. Here's the youtube link: https://youtu.be/L4w7qrzIlxo

What I noticed: 
Both were getting hammered by resonance
Around 40 sec into video Chipheal dies, and resonance stops being cast and the fight is working as intended at that point (although, I did get hit by that aoe and die when I should have been out of range...)

If I had to guess, it is only correctly handing resonance when there is one person in melee range. Maybe it does a count of people in melee range and if it is greater than 1 it casts resonance - but this is incorrect, he should only cast resonance when people in melee range = 0.

**Comment by Echinaceax** [comment]
Okidoki, will check it out @bigchipbag thanks 

Confirmed bugged @Rushor 
https://wowwiki-archive.fandom.com/wiki/Murmur

ignore numbers (maine and i mod HP for the test)
![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/b461be30-cf56-4a27-872c-8c7fa11958f8)

my buff
![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/a3d05baf-bbe7-4a06-bd46-13bd8e7bb144)


note

![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/8749b7ce-6919-43fe-a48b-fe927f3d97cd)

**Comment by Lumber-Jack-2** [comment]
condition added

**Comment by Echinaceax** [comment]
Not working at all now @Rushor he doesnt do resonance at ranged players when there is no melee in range

**Comment by Lumber-Jack-2** [comment]
next try

**Comment by Maine1** [comment]
Confirmed fix in PTR. If melee don't get back in fast enough 1 stack of resonance is added. If they take too long 2 stacks will come and keep raising. As intended
