### ISSUE TITLE
Scourgelord Tyrannus

### ISSUE THREAD

**Issue by Olgazia** [WoWManiaUK/Redemption#6072]
**Links:**
https://wowwiki-archive.fandom.com/wiki/Scourgelord_Tyrannus

**What is Happening:**
Scourgelord Tyrannus is not getting slowed by ice patches,
and he is not getting slowed by his Unholy Power buff.

**What Should happen:**
Scourgelord Tyrannus should get slowed by ice patches so the tank can kite him around avoiding to get hit when he gets his Unholy Power buff on Heroic (he gets 75% increased damage and also getting slowed by the buff).

**Comment by Echinaceax** [comment]
Thanks for reporting @Olgazia but it was looked into here and couldnt fix , it was labelled "as-is" unfortunately https://github.com/WoWManiaUK/Redemption/issues/5994#issuecomment-1493306285
