### ISSUE TITLE
Thorium spawn rates inhibitvly slow

### ISSUE THREAD

**Issue by mark4th** [WoWManiaUK/Redemption#6073]
**Links:**

**What is Happening:**
**AFTER** ariving in a zone that spawns thorium it takes over 20 minutes before any thorium spawns.  Mine it and it takes over 20 minutes beffore any nodes spawn and they start spawning very slowly after that

**What Should happen:**
Used to go to ungorro crater (for example) and spend 20 minutes mining over 400 ore.   Now takes over an hour and a half to mine 20 or 30 ore.

Yesterday I went to ungorro and rode round the perimiter two and three quater times before I aw a single node.  After that it took two more circuites before I aw anotyer.   I timed it, it takes 8 minutes to do one complete circuit so after 20+ minutes nodes start to sapwn. 

If there were more than one person there this would be even MORE horrendous to mine.   This has never been an issue till recently.  I have leveled countless toons in BS over the years and it never took me more than 20 minutes to go from thorium to fel iron.

I just cheked the searing gorge and again, one complete circuit of the zone and all i found was 2 nodes.

**Comment by Echinaceax** [comment]
Thanks for reporting @mark4th 
Correct they are 15 mins respawn as per wowhead comments to, so working as intended. 

https://www.wowhead.com/wotlk/object=175404/rich-thorium-vein#comments
![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/0323ccc5-310b-4eb5-8ddf-b5ecbc16e482)
