### ISSUE TITLE
Karazhan - Killing Midnight before Attumen makes Attumen despawn 

### ISSUE THREAD

**Issue by bigchipbag** [WoWManiaUK/Redemption#6075]
**Links:**
https://wowpedia.fandom.com/wiki/Attumen_the_Huntsman#Phase_One_-_Midnight

**What is Happening:**
In Kara, if you kill the horse on the first boss before the boss, the boss despawns. There are no mechanics that occur and we were just able to burn midnight down 
We received no loot from Midnight. 

**What Should happen:**
At 25% on boss or midnight they should mount and be killed as one, there should be no opportunity to kill midnight without seeing phase3 as listed on the wiki page

**Comment by Echinaceax** [comment]
We actually saw this last week when we did Kara for a transmog item, we was in voice channel at the time and remember hearing target boss not the horse.

Thanks for reporting (been busy myself) so didnt get to report it yet  
https://www.youtube.com/watch?v=Vw9PHqCZzhA

**Comment by Lumber-Jack-2** [comment]
if burst damage on horse first (i did with enter combat > .damage 100000000) it should no longer be killed, it will stay active instead until merge at 25 percent

**Comment by Echinaceax** [comment]
Confirmed this fix in PTR 
Players need to remember to stop damage on Midnight at 25% or atleast change target to Attuneman at phase 2, then let Attumen mount him for kill for phase 3

**Comment by Echinaceax** [comment]
reopening this one, needs more work

**Comment by Echinaceax** [comment]
Midnight fixed in PTR 

9 tests - each time did correct phases and loot 

https://i.gyazo.com/df9b8edf35fb3e154472113f58d9e05b.mp4

![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/051d2843-6fed-4bee-92b7-53e61cbcda52)
