### ISSUE TITLE
Karazhan - No scenery is displayed for Opera Event

### ISSUE THREAD

**Issue by bigchipbag** [WoWManiaUK/Redemption#6076]
**Links:**
https://www.youtube.com/watch?v=cQ0rdtFZ5-E

**What is Happening:**
Julianne spawns but there is no backdrop it is just empty. Same with romeo. Fight seemed to be fine
![WoWScrnShot_101623_112051](https://github.com/WoWManiaUK/Redemption/assets/2725389/afd674e4-2239-4944-b07a-116b53cd9ca8)

**What Should happen:**
There should be some visual element as seen in the video.

**Comment by bigchipbag** [comment]
It might be worth checking scenery for all the three opera events. This is our first time in and we haven't seen the others.

**Comment by Echinaceax** [comment]
Confirmed missing scenery for OZ from the other night 
Timestamp 1:50 https://www.youtube.com/watch?v=Ye_zk4AYUMw

https://wowwiki-archive.fandom.com/wiki/Opera_event

backdrop scenery are missing

- [x] Hood
- [x] Oz
- [x] Romulo and Julianne

**Comment by Lumber-Jack-2** [comment]
backdrop scenery should nw hapen, when barnes reaches his final waypoint of the intro

**Comment by Echinaceax** [comment]
Needs more work ;)

**Comment by Lumber-Jack-2** [comment]
all added (needs gm off)

**Comment by Maine1** [comment]
Oz event scenery all fixed
![image](https://github.com/WoWManiaUK/Redemption/assets/122736582/102159b8-b5e9-4007-8efa-85204c2334fb)
hood also 
![image](https://github.com/WoWManiaUK/Redemption/assets/122736582/b2f98b8b-3130-4a72-b69a-5e7636500be1)
Romulo & Julianne Fix
![image](https://github.com/WoWManiaUK/Redemption/assets/122736582/455123dd-bdd8-4557-9ca1-81ec8ca931d7)

Really good fixes here. Now it is perfect. Big thanks to @Rushor and @Echinaceax <3
