### ISSUE TITLE
Quest "The Caverns of Time" Does not work correctly in a group

### ISSUE THREAD

**Issue by bigchipbag** [WoWManiaUK/Redemption#6077]
**Links:**

**What is Happening:**
Two players accept quest at the same time
First person to accept gets whispers from two NPCs
Second person gets no whispers
Second person gets no credit when quest competes
Second person has to waste another 8m following an NPC

https://user-images.githubusercontent.com/2725389/275667224-f48e117b-9f82-47c6-90c3-ea46fa91bb69.png
![image](https://github.com/WoWManiaUK/Redemption/assets/2725389/f9b3a795-6527-4d0d-801b-b529c0005261)
Credit is not given to both players.

**What Should happen:**

**Comment by Echinaceax** [comment]
@Rushor 
quest https://www.wow-mania.com/armory/?quest=10277

**Comment by bigchipbag** [comment]
Functionality copy of #6069

**Comment by Lumber-Jack-2** [comment]
will be completed for all player in group now, text will still only go to one player

**Comment by Echinaceax** [comment]
Not quite fixed @Rushor 

- [x] The quest complete part is fixed ✅ 

has problems if you are on the quest when server crashes, the original quest guardians you follow are still spawned when you relog but are inactive. 

When you abandon the quest and retake there are 2 sets of them, they then start spawning chat 

![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/84874a09-523b-454d-a77d-7d5c87a37c43)
![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/a4f7cceb-1217-4af7-a79c-e9d86d378bd2)

- Need them to despawn on server restart/relog/fail etc...

**Comment by Lumber-Jack-2** [comment]
duplicate ones will despawn, path timer more short now

**Comment by Echinaceax** [comment]
looking good
Escort start time also better, thanks @Rushor  

![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/81e99a9c-de96-46a7-b4ce-bb0893b1c07f)

![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/69ec59ae-c931-48a7-b7b8-65689060f493)
