### ISSUE TITLE
Quest "Old Hillsbrad" Flags for PvP

### ISSUE THREAD

**Issue by bigchipbag** [WoWManiaUK/Redemption#6078]
**Links:**
https://www.wowhead.com/wotlk/quest=10282/old-hillsbrad

**What is Happening:**
![image](https://github.com/WoWManiaUK/Redemption/assets/2725389/c9127735-3717-4c91-b2bd-1d81c0c95a85)
Trying to accept the quest gives the warning you will be flagged for PvP For the duration 

**What Should happen:**
I don't believe this should be the case, it's not a pvp quest and no mention of it on wowhead or anywhere.

**Comment by Echinaceax** [comment]
@Rushor same fix as #5747

**Comment by Lumber-Jack-2** [comment]
requires cache clear

**Comment by Echinaceax** [comment]
Fix confirmed in PTR 

https://i.gyazo.com/ee48c8f87db04dd6c270e03f4d937014.mp4
