### ISSUE TITLE
Social/Character Movement Issue - Spinning while Dancing

### ISSUE THREAD

**Issue by bigchipbag** [WoWManiaUK/Redemption#6079]
**Links:**

**What is Happening:**
When you use /dance the player dances as expected, but it doesn't maintain the /dance animation when you spin your character, it moves to the "turn" animation and does not resume the dance animation

**What Should happen:**
The expected "blizzlike" behaviour is to be able to spin your character around while you continue to dance. I can't find a good video of it happening but can confirm it has been like that since vanilla, I did it as a ghost wolf in like 2005

**Comment by Lumber-Jack-2** [comment]
this is as sadly, it cannot be fixed

**Comment by bigchipbag** [comment]
Figured, but wanted to check anyways. Thanks!
