### ISSUE TITLE
[NPC] Custodian of Time - Pathing issue

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Redemption#6080]
**Links:**
NPC https://www.wow-mania.com/armory/?npc=20129
My Video https://i.gyazo.com/8abd562fc73fc13ae1ca471a6d3e30a0.mp4

**What is Happening:**
She shouldnt be falling through objects/or climping on food carts 

timestamp 3:52 https://www.youtube.com/watch?v=ZkHjnNhumQ4 
timestamp 2:50 https://www.youtube.com/watch?v=-O2gL8LJM1g

Cant find a video showing the food cart tho

GPS
![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/2c25ecbf-5dc0-4de2-a42b-66e99eb90fca)

![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/8911c274-0483-4d68-baf1-0136c078157c)

**What Should happen:**
smoother pathing

**Comment by Lumber-Jack-2** [comment]
added more points

**Comment by Echinaceax** [comment]
Fixed confirmed in PTR
Fixed Pathing
