### ISSUE TITLE
Dungeon Finder - Sometimes the teleport on complete queue does not work

### ISSUE THREAD

**Issue by bigchipbag** [WoWManiaUK/Redemption#6081]
**What is Happening:**
When the queue pops and you accept the invite, sometimes the party window appears but you remain where you are and are not teleported to the dungeon. 

This happened today with the horseman event and after teleporting to the dungeon I did not receive credit for the kill/complete of the dungeon. I attempted it a second time by accepting invite while standing on the ground unmounted and received credit.

**What Should happen:**
You should be teleported to the dungeon when you accept the invite. 

I think this might have to do with mounted-state and type of mount you are on. Today I was on the bronze drake in wintergrasp but I have had this happen when I was mounted in dalaran once, maybe because I was mid-air?

**Comment by Echinaceax** [comment]
Thanks for reporting @bigchipbag 
very strange one, we can have a check on it see if we can reproduce this bug

**Comment by Maine1** [comment]
@bigchipbag Usually if you don't get teleported inside it means you were either falling or in combat
Make sure its not that you jumped or was falling at the time you tried to accept. You will see red writing at top of screen if this is the case

**Comment by Echinaceax** [comment]
for info
No issue from a taxi flight 
https://i.gyazo.com/32ff8b456edee70f7c3e36c99e61fd20.mp4

![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/a17a681e-a9ca-41c2-8aa8-7ce45bda08ce)

will check mounted tomorrow
