### ISSUE TITLE
Quest [The Light of Dawn] broken.

### ISSUE THREAD

**Issue by LuciferTheSun** [WoWManiaUK/Redemption#6082]
**Links:**

**What is Happening:**
The quest won't progress past a certain point. The battle between the Lich King's forces and the army of light at Light's Hope chapel doesn't happen. The army charges forward towards the chapel, then they just stand there and nothing further happens.

**What Should happen:**

**Comment by Echinaceax** [comment]
Thanks for reporting @LuciferTheSun this has been reported so many times but here is the advice https://github.com/WoWManiaUK/Redemption/issues/3330#issuecomment-501672209 get a GM to reset the NPC then when the timer starts stay behind the horses tail and not infront of him, then it doesnt bug
