### ISSUE TITLE
Magisters' Terrace Heroic - Kael'thas Gives badge but no loot

### ISSUE THREAD

**Issue by bigchipbag** [WoWManiaUK/Redemption#6083]
**Links:**
https://www.wow-mania.com/armory/?npc=19622

**What is Happening:**
Killing Kael'thas on heroic in Magisters' Terrace dropped a badge of justice but the boss contained no loot.

**What Should happen:**
Boss should be lootable and have items from the loot table. 

Unfortunately missed the screenshot on this one, but there was no loot on the boss after the kill.

**Comment by Echinaceax** [comment]
thanks for reporting @bigchipbag 
we will check on this

**Comment by hammereddann** [comment]
Unable to Reproduce. I believe if they are killed too quickly or not killed within a certain timeframe of each other they bug loot. Also a blizzard forum about this being bugged before.
![image](https://github.com/WoWManiaUK/Redemption/assets/122736582/5763e009-6cab-4e8d-b32c-2d57e16664c7)
If you kill them within a good 20-30 seconds time within each other and not too fast it should always drop loot

**Comment by Maine1** [comment]
This boss gave loot for us. 
![image](https://github.com/WoWManiaUK/Redemption/assets/122736582/1d1755f1-bb05-49e9-a5df-80d61823ddb0)
![image](https://github.com/WoWManiaUK/Redemption/assets/122736582/5c15c959-157e-491b-a9a4-42fd8d0adaff)
Test 2

![image](https://github.com/WoWManiaUK/Redemption/assets/122736582/ec1bdf7d-f85b-424d-adb4-1b7a898ecb7f)
