### ISSUE TITLE
[Quest] Lessons Anew (Aliance) wrong completion text

### ISSUE THREAD

**Issue by stealer0517** [WoWManiaUK/Redemption#6086]
https://www.wow-mania.com/armory/?quest=6121
https://www.wowhead.com/classic/quest=6121/lessons-anew
https://www.wow-mania.com/armory/?quest=6126

When you click continue on the quest text Mathrengyl Bearwalker starts talking about the Crossroads.
The completion text seems to be the same as the completion text of the Horde version of the quest.
The Wowhead link appears to have the correct text.

Also, the horde text appears to be hard coded as druid  and not class. This shouldn't affect anything though since it's a druid only quest.

**Comment by Echinaceax** [comment]
Confirmed bug 

- [ ] Wrong faction text https://i.gyazo.com/2eccb1305c54a272baf4862276ab3f97.mp4

![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/bb57ab88-bdb7-48a3-a6a8-dfc222205f53)

Note: I think it should be this one @Rushor 
https://wowpedia.fandom.com/wiki/Lessons_Anew
![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/bbf441c4-01a4-4a42-bfb8-fb6a00219f5d)

**Comment by Echinaceax** [comment]
Fix confirmed in PTR 

![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/5f622c35-6ebe-4d34-826f-3afd240d267c)
