### ISSUE TITLE
Not getting stated exp on Candy Bucket

### ISSUE THREAD

**Issue by brieks07** [WoWManiaUK/Redemption#6087]
**Links:*
![977457 exp](https://github.com/WoWManiaUK/Redemption/assets/114018917/f96b56e2-1aa4-45e3-9dd6-733db787c644)
*
![25000exp](https://github.com/WoWManiaUK/Redemption/assets/114018917/ffbbbb1f-e759-4e77-b056-01e067c26f07)
![still 977457 exp](https://github.com/WoWManiaUK/Redemption/assets/114018917/0b2bcf4b-7251-47be-8838-5e1ecf8bbc93)

**What is Happening:**
I've been going around to candy buckets (that I haven't visited yet) on my hunter, Nzingha. These are the candy buckets that still have th yellow question mark over them. When I go to complete the "quest" - it tells me that I'm going to get 25000 experience. However, this doesn't always happen. Sometimes, I DO the the experience. Other times, I don't get the experience. The screenshots I've included show that my experience bar was at 977457 before I did the candy bucket. Then it shows the candy bucket window that states how much experience I'm going to get for completing it. Then, I complete it (and you can see that because I received a Handful of candy), but my experience remains the same at 977457.

**What Should happen:**
I should receive the amount of experience that the quests states that I'm going to receive.

**Comment by Echinaceax** [comment]
thanks for reporting @brieks07 

https://www.wow-mania.com/armory/?object=190040

I was given my XP from the same candy bucket as you in Stormwind innkeeper (on my level 16)
i see you are 70+ (so the XP amount will be different) ofc so ignore the amount.

![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/7c91f428-f243-4d2e-8d00-7fb68a468fac)
![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/85ea4df2-9143-4adc-8f75-45342839f58f)

Level 70 at a random location (none x2 weekend) 
![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/165ca457-13bd-4000-adda-5b32a2db8c77)

Level 70 stormwind (no weekend x2 XP boost) 
https://i.gyazo.com/ab100d8effb60fe6bd594a78db14dacb.mp4
![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/1dfe166d-fcbc-479b-9374-b4aa1423133c)

### this seems a random bug and not a particular bucket 

make sure you are using Mania client and launcher is up to date
also try deleting cache

if it happens more frequently let us know
