### ISSUE TITLE
[Object] Isle of Conquest - Gate and render distance bug

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Redemption#6088]
![Conquest gate bug](https://github.com/WoWManiaUK/Redemption/assets/39439201/997f2ed2-5563-41a8-ae6b-39339b737b4a)

**What is Happening:**
same issue as SoTa had, render distance and broken gates not broken for everyone that didnt see the gates break

**What Should happen:**

- [ ] Same fix as https://github.com/WoWManiaUK/Redemption/issues/6070

**Comment by Lumber-Jack-2** [comment]
applied

**Comment by Echinaceax** [comment]
reworking is tomorrow 
thanks Rushor

**Comment by Echinaceax** [comment]
- [x] conquest render is great 🙂 
- [x] conquest gate transition looks good

horde 
https://i.gyazo.com/175c54f58304da9ac0471b0a40ba2913.mp4
https://i.gyazo.com/801fbfa6dec8ffa30028de595407fd37.mp4

Ally 
https://i.gyazo.com/f0554b8fd4d37b85b95130bfbde5b2ad.mp4
https://i.gyazo.com/67ee300e1df7b9593c7c8b2a8589b2a9.mp4
