### ISSUE TITLE
[Quest]  A Lost Master - Quest text incorrect

### ISSUE THREAD

**Issue by stealer0517** [WoWManiaUK/Redemption#6089]
https://www.wow-mania.com/armory/?quest=993
https://youtu.be/BZHu-QS93P8?t=103

This is specifically part 2 of the quest where you travel to the cave, not part 1 where you find the pelts.
Once you find Volcor in the cave both the initial text when you speak to him, and the quest text is blank. Selecting continue gets you to the correct text.

Speaking to him you get the default "Greetings, Name." You can see the correct text in the video above.
Once you select the text it should default immediately to the "complete text" screen with the quest text.

**Comment by Echinaceax** [comment]
confirmed text bug on both pages timestamp 1:42 on the video link above 

![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/6bee3e1f-b4c1-44e2-91f9-721ac1ebad33)
![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/57d5ed50-3f5b-47ef-ab30-a628f0f0b67b)

**Comment by Lumber-Jack-2** [comment]
text quest_request_items 

<HTML>
<BODY>
<TABLE><TR><TD>&lt;Volcor doesn't look at you at all as you get close to him. He seems to be concentrating on keeping his bandages from falling off. After a moment, he looks up at you, a little startled.&gt;$B$BOh, sorry, $c. Now's not a good time. I hope you understand.</TD></TR></TABLE>

</BODY>
</HTML>

added

**Comment by Echinaceax** [comment]
Fix confirmed in PTR 

![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/4e017074-8efb-4a6d-a327-f5cbd51c3343)
