### ISSUE TITLE
Problem with talent+set bonus proc

### ISSUE THREAD

**Issue by k1ll3r** [WoWManiaUK/Redemption#609]
I`m a warr last week it works fine now its bugged. When my instant slam procs 2 times (from the set bonus) i can use only 1 and then the 2 procs disapear ..... can you fix it ? ty

**Comment by fvicaria** [comment]
I can if you tell me which spell. There is not info in your report.
Please read:
https://github.com/WoWManiaUK/Redemption/wiki/How-to-Properly-Report-an-Issue

**Comment by k1ll3r** [comment]
http://wotlk.openwow.com/spell=47475
that spell + t10 set bonus

**Comment by tsuff** [comment]
Hey, it seems that the fix u have applied doesn`t work. Will u maybe have another look into it. I could not find another issue about it, please redirect me if there is.

**Comment by fvicaria** [comment]
I will re-test. Thanks!

**Comment by tsuff** [comment]
Thanks for the instant response first of all. I would greatly appreciate it if you let me know what is the result of the re-test. Looking forward to hearing from you.
