### ISSUE TITLE
[Quest] Escape Through Stealth - NPC doesn't escape through stealth

### ISSUE THREAD

**Issue by stealer0517** [WoWManiaUK/Redemption#6090]
https://www.wow-mania.com/armory/?quest=995
https://www.youtube.com/watch?v=ZQV9tBrnvfE&t=1s stealth
https://www.youtube.com/watch?v=0sm-ThSRF0o force

When you complete the [previous quest](https://www.wow-mania.com/armory/?quest=993) you get the option for the quest escape through stealth or escape through force. Escape through force seems to work as intended. 
Escape through stealth does the exact same NPC path of walking straight out of the cave and into the enemy mobs.

Escape through stealth should have Volcor walk out of the cave, shape shift into a moon stalker, and go into stealth completing the quest. (see video)

**Comment by Echinaceax** [comment]
Confirmed bug https://i.gyazo.com/353431d879577e06e582f232720b2e8d.mp4

- [ ] he doesnt shapeshift 
- [ ] volcor walks the wrong escape path

**Comment by Lumber-Jack-2** [comment]
adjusted path, added the cat form

**Comment by Echinaceax** [comment]
Confirmed fixed in PTR 
https://i.gyazo.com/61ebd56a5c6efce355a69267e77f9d9d.mp4
