### ISSUE TITLE
Headless Horseman - Sometimes the horseman doesn't "die" and spit out the head

### ISSUE THREAD

**Issue by bigchipbag** [WoWManiaUK/Redemption#6092]
**Links:**

https://github.com/WoWManiaUK/Redemption/assets/2725389/4d177955-25dd-4513-a96a-3e38558a2038

**What is Happening:**
The headless horseman sits at low HP and the head never appears. I think this was on the second round in the video, the first time it was fine.

**What Should happen:**
The head should go flying off and become killable

**Comment by Lumber-Jack-2** [comment]
try a new instance run

**Comment by Echinaceax** [comment]
> try a new instance run

I spoke to a few people this has happened to @Rushor it seems to not be a random 1 off incident, 
When this happens the HP of the Headless Horsemen is low but the (head doesnt fly off) as it should, there are a few phases depending how long it takes the group to burn him down in each phase

Head https://www.wow-mania.com/armory/?npc=23775 

https://www.youtube.com/watch?v=fkotAjbrqdE

Can you check if there is anything noticable in the code that could be doing this?
players shouldnt have to regroup a new instance run when it happens 

Phases https://wowpedia.fandom.com/wiki/Headless_Horseman

**Comment by Lumber-Jack-2** [comment]
after next recompile - head should always be summoned at low hp now

**Comment by Echinaceax** [comment]
not fixed but found the issue 

Bugs like this at 0% 
https://i.gyazo.com/8114a2ab9b5a8648c350a35c30a16bf7.mp4

and by accident maine turn GM on and found the head invisible :) 
https://i.gyazo.com/edd0703b5aab9fcbbff06d12b585b2c9.mp4

**Comment by Lumber-Jack-2** [comment]
more adjustments done

for me he was always there now, tested 3 phases https://i.imgur.com/mkRkBk2.jpeg

**Comment by Lumber-Jack-2** [comment]
https://gyazo.com/7570f35cdffcc5ffee288fdf62e73a6c
https://gyazo.com/e80faa9a73b1d2248aecfd318b84c753

**Comment by Rushor** [comment]
okay issue still there sometimes - when it bugs he is still confused in mounted phase

**Comment by Lumber-Jack-2** [comment]
Okay i got the issue, if too much damage is done, the head phase will start duplicated, he will throw 2 heads at once

**Comment by Lumber-Jack-2** [comment]
Duplicate head throw fixed now - he can only throw only 1 head per phase and no longer skip phases now

**Comment by Echinaceax** [comment]
Seems good now, after several tests 

- [x] the invisible head is fixed 
- [x] always throws his head `
- [x] Pumpkin phase working fine
