### ISSUE TITLE
Dying while on quest "An End To All Things..." is bugged

### ISSUE THREAD

**Issue by bigchipbag** [WoWManiaUK/Redemption#6093]
**Links:**

**What is Happening:**
IF you die while flying the frozen drake (which happens WAY too fast, probably also a bug) you fall to your death and when you try to revive you are in combat and die again immediately

**What Should happen:**
The drake part of the quest shouldn't be insta death and be more survivable and I think you are supposed to be rezzed right away without corpserun

**Comment by bigchipbag** [comment]
The ballistas seem to be remaining in combat

https://github.com/WoWManiaUK/Redemption/assets/2725389/c425ff86-84d1-46ba-b4bd-f9db6ebbc462

**Comment by bigchipbag** [comment]
Similar to #1300
It's not 100% clear what you should do when you die, i think in retail there's a Valkyrie that rezzes you, the text does appear but there's no NPC at the graveyard
![image](https://github.com/WoWManiaUK/Redemption/assets/2725389/d9ff898e-ab6d-4bec-945b-9660c091dd90)

**Comment by Lumber-Jack-2** [comment]
need to increase the hp pf the dragon would help maybe?

**Comment by GMZinius** [comment]
> need to increase the hp pf the dragon would help maybe?

This quest has indeed been an issue here for many years, we get revive tickets all the time for this one.
We should try and fix it most definately

As state above it instant death.

From what we have observered is: 

- The first time a DK dies on this quest a Val'kyr Battle maiden does appear to help you reserrect. Not sure if it is meant to be more. 
- The ballistia arrows are way to much all at once or do far too much Damage. Will have to check that.
- Range of ballistia arrows + Scarlet Soldier need to be checked.
- HP check Frostbrood Vanquisher.

Video from 2015 shows that it is not "rapid fire" like it is here.
https://www.youtube.com/watch?v=lHoQaVNXndg

https://www.wowhead.com/wotlk/quest=12779/an-end-to-all-things

![image](https://github.com/WoWManiaUK/Redemption/assets/108176634/bf187d3f-e31d-49c5-be6a-757e407422c2)

 Notes here are interesting to 
Timestamp 1:12 you see him use button 3 https://www.youtube.com/watch?v=jJo0X-oXpTM
I do not think ours even give time to "swoop out of the sky and close to within 15 yards, hit 3 to eat it, and get back into the air" 
https://wowpedia.fandom.com/wiki/An_End_To_All_Things...
![image](https://github.com/WoWManiaUK/Redemption/assets/108176634/274a517d-abf5-4b9a-8282-1ab828524d87)

**Comment by Echinaceax** [comment]
i know this quest to well and yes its the line of fire range of the incoming missiles, you cant get out of line of fire 
(its not meant to be easy, but it does have several issues atm 

this is how i did my quest https://www.wowhead.com/wotlk/quest=12779/an-end-to-all-things

![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/62eed65e-f948-49d2-9cf1-8f2db254950a)


I will do the quest and get a video of how its bugged here

TEST

Death
Paracute and instant death plus  Val'kyr Battle maiden apeared https://i.gyazo.com/0fe05838de41c1f27892281b111a4cb9.mp4
Instant death on res from Val'kyr Battle maiden https://i.gyazo.com/6f40538262b0ca11cd333fb90289b95a.mp4
Spirit healer is only visible from GM mode NOT from dead mode
https://i.gyazo.com/dffccf8ca031361e8457b4f46fd0922f.mp4

REPEATED INSTANT death at the graveyard 
https://i.gyazo.com/84099ed91cda3e71ba6c6be344ec592b.mp4
https://i.gyazo.com/fe1afa616a26670898c71509fd5b243f.mp4

![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/4b1ff4d3-db28-4f42-9143-c3174e2bbc29)

Range attack at graveyard
https://i.gyazo.com/7cef6d15ada08d3290ee315eb3c2a53f.mp4

-----------------------------------

### MAINE FOUND THE ISSUE WITH THE GRAVE YARD INSTA DEATH 

Dead players are ressed at the wrong grave yard lol 

- [x] Fix for the grave yard (res player here)

https://i.gyazo.com/40b246203010ef43a713f97891f319ad.mp4
![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/f2867919-e0b0-48ea-8f5c-f7cb5a22f27e)

**Comment by Rushor** [comment]
The HP for the dragon is hugly increased, this will resolve all issues actually

**Comment by Lumber-Jack-2** [comment]
Graveyard position changed + Spirit healer added

**Comment by Echinaceax** [comment]
Fixed in PTR 

- [x] Graveyard position changed https://i.gyazo.com/34e0205da3a2c78dc43e750da3af0eed.mp4
- [x] Phase 64 new Spirit healer added
- [x] Much better mount control after dying many times lol https://i.gyazo.com/d3900f196a0186aac0211cf707596c43.mp4
- [x] Val'kyr Battle maiden does appear - increased her timer for res notification box (was a little delayed) 
- [x] 3 deaths - 3 Valkyr ressed me https://i.gyazo.com/38bb7a9d5991d914134eaae2fb8b3db5.mp4

![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/8d5efb41-66fb-4d61-ba99-b5576b409f09)
![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/6c7be42d-5982-4e86-882d-c292aaead1b6)
![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/48996635-8346-440c-b045-7c0d6c2daf99)
![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/73c2181e-dbfc-4a3a-b3aa-15eb716e3f82)
