### ISSUE TITLE
[Object] Fuel Tanks - Plains of Nasam quest do not trigger

### ISSUE THREAD

**Issue by bigchipbag** [WoWManiaUK/Redemption#6094]
**Links:**

**What is Happening:**
Driving over the fuel tanks does nothing

**What Should happen:**
The fuel tanks should give mana back to the seige tank

**Comment by bigchipbag** [comment]
https://github.com/WoWManiaUK/Redemption/assets/2725389/835d510c-28cf-4a44-9bfd-b489b1d6d46c

When I shot a catapult at the fuel barrel, it said "Evade"

**Comment by Echinaceax** [comment]
thanks for reporting @bigchipbag 
can you post quest links from mania armory when you report please 

Quest https://www.wow-mania.com/armory/?quest=11652

- [ ] Confirmed bug of the oil barrels inactive and dont explode (dont give mana) 
https://i.gyazo.com/6151f09718e6dd86a9bf54bc8c84461d.mp4

https://wowpedia.fandom.com/wiki/The_Plains_of_Nasam

![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/25412bb4-bed5-4891-b47c-7bab39c86f03)

https://wowpedia.fandom.com/wiki/Horde_Siege_Tank

![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/aaaf2c7f-5364-45a8-a0d0-b358cb9dde9b)


Note: not meant to be shot at ...only run over them then they explode

**Comment by Echinaceax** [comment]
Fixed in PTR 

- [x] Fuel tanks explode when you drive through them and adds mana to vehicle mana pool 

https://i.gyazo.com/b8933523680508447edde6177c4d6521.mp4
