### ISSUE TITLE
[Quest ] Plains of Nasam - Respawn Rate very low

### ISSUE THREAD

**Issue by bigchipbag** [WoWManiaUK/Redemption#6095]
**Links:**

**What is Happening:**
The Scourge take quite a long time to respawn making this quest take 10+ min if more than one person is doing it

**What Should happen:**
In retail there was basically a constant stream of these guys around

**Comment by Echinaceax** [comment]
thanks for reporting @bigchipbag
can you post quest links from mania armory when you report please

https://www.wow-mania.com/armory/?quest=11652

NPCs have a 5 mins respawn 

![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/da2212f9-0956-476f-b91b-a7f7dd34eb98)

**Comment by Lumber-Jack-2** [comment]
respawn should be adjusted there yes, can do that

**Comment by Echinaceax** [comment]
Fixed in PTR 

- [x] Respawn timers reduced
