### ISSUE TITLE
[Spells] Cheap shot / Kidney shot - Rogue Stuns Miss

### ISSUE THREAD

**Issue by Danzan01** [WoWManiaUK/Redemption#6096]
Hello,

Ok, so this issue happened many times now on both of my rogues, both on alliance and horde, i miss with my stun abilities, that should not happen, since i always stun while i am behind my target and players can't dodge from behind, it happened with cheap shot and with kidney shot yesterday. Missed kidney shot on hunter in WSG, and after that i did a duel vs warrior and then i missed cheap shot, all this happened while i was behind my target.
If you have time please take a look into this. 
Here are the links: https://www.wow-mania.com/armory/?spell=1833 and https://www.wow-mania.com/armory/?spell=8643

Thank you

Danzan

**Comment by Echinaceax** [comment]
thanks for reporting @Danzan01 
can you link the spells from mania armory

**Comment by Danzan01** [comment]
I added links in original post
Cheers

**Comment by Echinaceax** [comment]
@Rushor 
Need to check if this could be Diminishing returns https://wowpedia.fandom.com/wiki/Diminishing_returns#:~:text=Diminishing%20returns%20means%20that%20certain,have%20diminishing%20returns%20in%20PvE.

![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/92e3e9f5-b517-4063-8dea-652337510ea6)


![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/62cb15e3-c8a1-46fe-836e-135dae883942)

**Comment by Danzan01** [comment]
ah no Echi, its not DR that you speak of, its first opener on target, that means its first time that stun is used on target so there are no DR's there

**Comment by Echinaceax** [comment]
> ah no Echi, its not DR that you speak of, its first opener on target, that means its first time that stun is used on target so there are no DR's there

thanks Danzan we will take a look at it

**Comment by Lumber-Jack-2** [comment]
comments in code for miss are:

// Check for attack from behind
// Can`t dodge from behind in PvP (but its possible in PvE)
// Can`t parry or block
// Only deterrence as of 3.3.5

**Comment by Danzan01** [comment]
As for hunters deterrence, cheap shot goes through it, as it should, like warlocks death coil, warriors overpower, and the hunter i tried to kideny shot didnt have deterrence on him.
The whole thing is about that i missed my stuns, while i was behind my target.

**Comment by fvicaria** [comment]
Can we have a video for this? Otherwise it is difficult to reproduce and debug it.

**Comment by Echinaceax** [comment]
Waiting on video from player

**Comment by Maine1** [comment]
Testing complete for now. Night elves have racial for chance to hit reduction. 
Tank and anything wearing defence gear have a chance reduction for hit.
Orc have a resistance to stuns.
Retri and Prot paladins talents reduce chance to be hit with ranged attacks and spells 4% Aura mastery also 
Prot warrior talent to reduce chance to be hit by spells by 2% and 4%
DK - Lichborne talent and Frigid dreaplate talent reduction
Priest - Dispersion
Rogue - Hightened Senses
Mage - Improved blink / Arctic winds
all pictures for evidence
![image](https://github.com/WoWManiaUK/Redemption/assets/122736582/3f22e22d-5cc9-495b-99af-e5d6dcdada31)
![image](https://github.com/WoWManiaUK/Redemption/assets/122736582/b6c8f51e-8518-4f22-bd8b-2c94b3e7099f)
![image](https://github.com/WoWManiaUK/Redemption/assets/122736582/241caacf-4715-4a7a-9eb1-304b803ec9e8)
![image](https://github.com/WoWManiaUK/Redemption/assets/122736582/c890b124-1540-474e-86bb-c2c8a52bdfe6)
![image](https://github.com/WoWManiaUK/Redemption/assets/122736582/d24f72de-bc09-452a-8366-391bd2c98dfc)
![image](https://github.com/WoWManiaUK/Redemption/assets/122736582/19b69034-7ac1-4d16-bc9d-c5eca3e3f4e6)
![image](https://github.com/WoWManiaUK/Redemption/assets/122736582/420e67c0-9ad6-4c68-b6fb-d308a2513876)
![image](https://github.com/WoWManiaUK/Redemption/assets/122736582/a7bdce2a-0cbd-46ff-9b1b-8f47840314d6)
![image](https://github.com/WoWManiaUK/Redemption/assets/122736582/452a38b7-3a32-4343-b09c-7621240f1755)
![image](https://github.com/WoWManiaUK/Redemption/assets/122736582/70fc35e1-443d-4e8d-8b68-f7198774cf69)
![image](https://github.com/WoWManiaUK/Redemption/assets/122736582/1056ccc0-c077-4398-a574-066495a023ed)
![image](https://github.com/WoWManiaUK/Redemption/assets/122736582/65d7e666-edd2-4e71-8939-07473e54b24b)

**Comment by Danzan01** [comment]
Ok, done some testing myself too, and yes hit rating is the problem here, since in PvP you don't need more than 5% hit, well i guess that's not accurate anymore :D , as for some the spells in post above, i have to add small correction to some things, for example Death Knight's Lichborne spell does not make you immune to stun, Icebound Fortitude does. Orc racial in Wotlk doesn't make you immune to stun, it gives you 15% stun reduction, also you can cast Priest's Dispersion while stunned yes, but the spell itself does not make Priest immune to stun since you can stun into Dispersion. If i missed something, feel free to add to post.

I want to thank everyone for your time and patience, and thank you for testing!

Kind Regards, cheers!

Danzan

**Comment by Maine1** [comment]
Was a pleasure working on it :) thanks for report
