### ISSUE TITLE
Alliance-Darkshire- Graveyard quest-"Proving your worth"

### ISSUE THREAD

**Issue by savagesara** [WoWManiaUK/Redemption#6098]
**Links:**Quest "Proving your Worth"

**What is Happening:**You have to finish this quest to get the Morbent Fel kill quest. You have to kill three Skeletal Warders. But there are no skeletal warders in or around the house they are supposed to be at. Instead, Morbent Fel is already in that house, but you can't get credit for killing him because you are not on that quest yet.

**What Should happen:**You kill everything in the quest, including the three skeletal warders, and then get the Morbent Fel kill quest.

**Comment by Lumber-Jack-2** [comment]
The creature on server are here: https://www.wow-mania.com/armory/?npc=785

https://i.imgur.com/XQBLkKS.png They are in the ground They have 300 sec respawntime

**Comment by savagesara** [comment]
I went back and spent quite a bit of time around the house where the skeletal warders are supposed to be. There are skeletal RAIDERS and skeletal HEALERS all over that area. I have yet to see one skeletal WARDER. Also, like I said, Morbent Fel is already in that house upstairs and with-out being on that quest yet, I am not sure he should be there at all. 
    On Wednesday, November 1, 2023 at 06:44:53 AM EDT, Rushor ***@***.***> wrote:  
 
 


Closed #6098 as completed.
