### ISSUE TITLE
Alliance-Westfall quest-The Defias Brotherhood-"A Mysterious Message"

### ISSUE THREAD

**Issue by savagesara** [WoWManiaUK/Redemption#6099]
**Links:**Quest- "A Mysterious Message"

**What is Happening:**A Defias messenger is supposed to be randomly moving up and down a road. You are supposed to confront him, kill him, and get his briefcase with the message in it. I patrolled the road he is supposed to be on up and down, over and over again for almost an hour. Never saw the messenger. 

**What Should happen:**You find him, kill him, get his briefcase containing the message and turn it in. Quest over.

**Comment by Lumber-Jack-2** [comment]
he is there, thats his patrol https://www.wow-mania.com/armory/?npc=550

https://i.imgur.com/LA1Wavr.jpeg

Pleae use the side https://www.wow-mania.com/page/armory to get more information before reporting bugs :)
