### ISSUE TITLE
Horde Quest-Deathholme in the Ghostlands-"Dar'khan's Lieutenants"

### ISSUE THREAD

**Issue by savagesara** [WoWManiaUK/Redemption#6100]
**Links:**Deathlome Quest- "Dar'khan's Lieutenants"

**What is Happening:**You are given a quest to kill Dar'khan's Lieutenants to get the Dar'khan kill quest. I killed all except for Masophet the Black because he never appeared where he is supposed to be. I waited almost 45 minutes for him to respawn, if that is what is wrong, but he never did. 

**What Should happen:**You kill all his Lieutenants, including Masophet the Black, and get the Dar'khan kill quest.

**Comment by Lumber-Jack-2** [comment]
he is there https://www.wow-mania.com/armory/?npc=16249 - he has pooling so check one of those 2 spots

https://i.imgur.com/Cx20f6v.png

He has 300 sec respawn time
