### ISSUE TITLE
[NPC] Oil stained wolf - Ignoring Hunter pets

### ISSUE THREAD

**Issue by mark4th** [WoWManiaUK/Redemption#6102]
**Links:**

**What is Happening:**
Send hunter pet in to attack oil stained wolf.  wolf immediately comes for me instead of attacking my pet even if I am some distance away.   if i feign death the wolf loses agro.   

**What Should happen:**

wolf should agro on the pet attacking it (with growl) instead of ignoring the pet and coming for me :)

**Comment by Lumber-Jack-2** [comment]
I think keader added this change to make sure the Master get's Attacked

**Comment by Echinaceax** [comment]
> I think keader added this change to make sure the Master get's Attacked

Found this, no fix was done from what i can see https://github.com/WoWManiaUK/Redemption/issues/5852 and here https://github.com/WoWManiaUK/Redemption/issues/5801

Hetah's detailed test is worth reading Rushor, https://github.com/WoWManiaUK/Redemption/issues/5801
And yes i remember your other fix here https://github.com/WoWManiaUK/Redemption/issues/5811


@Rushor If you are able to fix, i would fix the older report it has links and more detailed info https://github.com/WoWManiaUK/Redemption/issues/5852 and close this one

**Comment by Lumber-Jack-2** [comment]
Ohhhh it's an issue because the npc is in water, okay i know the fix

**Comment by Lumber-Jack-2** [comment]
should be fixed now, maybe it happens to other creatures in that area that are in the water aswell?
