### ISSUE TITLE
[Spell] Glyph of Snake Trap - 90% reduced damage by AoE not working

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Redemption#6103]
Reported to GM by a player

**Links:**
Glyph https://www.wow-mania.com/armory/?item=42913

**What is Happening:**
it is suppose to reduce the AoE damage taken by snakes by 90%

**What Should happen:**
Apparently the glyph does nothing

**Comment by Echinaceax** [comment]
Patch notes 2.0.3 snake 107 hp, is correct

![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/834dc076-948c-4822-a058-a91a1e314fb2)

as tested the glyph doesnt work but who in the right mind would waste a major gyph slot for this?

any way up to u @Rushor if this is worth fixing

**Comment by Maine1** [comment]
my personal vote is that it's useless glyph. 2 ticks of blizzard or arcane explosion etc instead of 1 tick of damage. it means they will last 1 more second which is not effective in my opinion.

**Comment by Lumber-Jack-2** [comment]
can be fixed yes

**Comment by Echinaceax** [comment]
Fixed in PTR 

![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/168538fa-5a5d-4eb2-999c-2c847f5261fa)
