### ISSUE TITLE
[Item] Sandbox Tiger - has 0 charges

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Redemption#6104]
**Links:**
https://wowpedia.fandom.com/wiki/Sandbox_Tiger
Mania https://www.wow-mania.com/armory/?item=45047

**What is Happening:**
Sandbox Tiger has no charges, so is never consummed stacking repeately 
https://i.gyazo.com/61e8b09a9cefcabdff7b5792d76c559f.mp4

**What Should happen:**

- [ ] Should have 1 charge 

![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/39f69b01-0130-4d8a-ac70-61d344f9ef1c)

**Comment by Echinaceax** [comment]
Fixed in PTR 

https://i.gyazo.com/37c89a6964c69dae3f4f3a1d03a8de3b.mp4

**Comment by Echinaceax** [comment]
Something has changed since yesterday
- now we get a "no charges left error" on the stacks of the item we have 

![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/9c00a7ca-5c6a-4c2f-adde-15986f4af86d)

**Comment by Echinaceax** [comment]
And now they are working again lol
whats going on ? 
https://i.gyazo.com/abdc44a9042d84788e174f3534093da8.mp4

bugged char https://i.gyazo.com/cdd00351f9132376a125f504dc4f42bb.mp4
deleted the 3 from the bugged char and added new https://i.gyazo.com/91cd8e93e5fb4c4e6f4405f0a76d2d2b.mp4

so maybe the stacked ones players had in bag before fix could be bugged have to wait for player feedback on that then 
my playtoon on live has 447 i will check after update on live and let you know @Rushor :)

![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/abe08ae7-42c7-4e79-b47e-512061d9865e)

**Comment by Lumber-Jack-2** [comment]
Eh yep old ones bugged for me top, so it works for the new ones, that's the Main goal
