### ISSUE TITLE
[Dungeon] Double Spawns. Azjol-Nerub HC and Ragefire Chasm

### ISSUE THREAD

**Issue by Greywolf59** [WoWManiaUK/Redemption#6107]
Naxxramas realm.

1. There is double spawn of the three groups in front of the first boss in Azjol-Nerub on heroic mode, haven't checked the normal mode.
2. There is double spawn of some thrash in Ragefire Chasm.

There might be more cases. Pretty recent bug, should require further investigation.

**Comment by Echinaceax** [comment]
Thanks for reporting @Greywolf59 
links and screenshots please

**Comment by Lumber-Jack-2** [comment]
The Position for the ones in ragefire chasm would be good to know Yeah. The wotlk one i can check today :)

**Comment by Greywolf59** [comment]
![AN double](https://github.com/WoWManiaUK/Redemption/assets/41387450/be733838-96c1-4c56-9f34-6b8bc4950ecf)
Screenshot from normal, same situation on heroic.


RC tba

**Comment by Greywolf59** [comment]
Ragefire Chasm

1st Trogg room:
![RC11](https://github.com/WoWManiaUK/Redemption/assets/41387450/afd3d7ba-5803-49a8-999b-274a673d0baf)
![RC12](https://github.com/WoWManiaUK/Redemption/assets/41387450/12d16a57-13f5-41f1-810b-26a07fa5a07a)
![RC13](https://github.com/WoWManiaUK/Redemption/assets/41387450/48a5b28f-296d-43af-aa94-034aca1ae886)
![RC14](https://github.com/WoWManiaUK/Redemption/assets/41387450/da7f5b72-4ba2-49d4-9511-f472ae2e4bd1)
![RC15](https://github.com/WoWManiaUK/Redemption/assets/41387450/998c4101-cff3-4c49-b0f2-79fd96fc8235)

**Comment by Greywolf59** [comment]
Taragaman Room and Jergosh/Bazzalan Room:
![RC21](https://github.com/WoWManiaUK/Redemption/assets/41387450/edda48f7-2cd7-49e4-8c82-dca00d52e178)
![RC22](https://github.com/WoWManiaUK/Redemption/assets/41387450/4c105436-519f-4f82-9461-e9e306459e73)
![RC23](https://github.com/WoWManiaUK/Redemption/assets/41387450/d068ba6c-e5ba-458b-8d0b-5fffaef18ea1)
![RC24](https://github.com/WoWManiaUK/Redemption/assets/41387450/ed0354a8-017e-4095-83ee-fbb55d3e82d9)
![RC25](https://github.com/WoWManiaUK/Redemption/assets/41387450/d4acd86b-bd34-4d4c-8fdb-08627c889142)
![RC26](https://github.com/WoWManiaUK/Redemption/assets/41387450/a5e46482-16cd-4a0d-9e1d-4e57051d35d8)
![RC27](https://github.com/WoWManiaUK/Redemption/assets/41387450/1459dd8d-9767-40bf-9fba-aa40354af08d)
![RC28](https://github.com/WoWManiaUK/Redemption/assets/41387450/de82fc30-53af-4e76-b97d-a59775f60c7f)

**Comment by Lumber-Jack-2** [comment]
hm tried the northrend one and it was fine for me in both instance versions https://i.imgur.com/pXagqLp.png

maybe a random bug?

**Comment by Lumber-Jack-2** [comment]
ah the ragefire one is actually because they follow each other - should have better behaviour to not follow each other on random movement

**Comment by Lumber-Jack-2** [comment]
formation is removed, attackig together without following each other is not implemented yet in core, so this is the most valid fix.

**Comment by Greywolf59** [comment]
Just came out from another AN RHC on Naxx realm. Doubled again. 3 times out of 3.

**Comment by Echinaceax** [comment]
> Just came out from another AN RHC on Naxx realm. Doubled again. 3 times out of 3.

the fix isnt on live yet @Greywolf59

**Comment by Greywolf59** [comment]
yes I know, just reacting to Rushor's post that he did not find a double spawn in AN

**Comment by Echinaceax** [comment]
> yes I know, just reacting to Rushor's post that he did not find a double spawn in AN

Same here, i didnt find a double spawns either in AN 

![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/9a9f877a-e16b-4024-9af1-d24926e3995f)

try deleting cache @Greywolf59

**Comment by Echinaceax** [comment]
Ragefire Chasm

![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/7b3b824e-a197-4612-aafb-dcc5ed9af602)
![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/210d6d69-c90a-47d1-b439-6526cdfc6ce0)
![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/282bf574-4ebf-47e4-9d92-a8b0cb273b18)
![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/3590af80-d161-489c-98cf-fb475b96376d)
![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/be7f2eb8-40ff-46ce-9fe6-37f4b14a6570)
![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/6ed7c53f-655f-49d1-a887-540e30ea3392)
![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/aa56c28f-571c-4aeb-815a-6a86d0919fb9)
![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/4bbb0e60-2088-444f-977d-79b7d3bdfc39)

**Comment by Greywolf59** [comment]
Deleting cache solved the AN problem it seems.
