### ISSUE TITLE
Faction quest lines wotlk not working

### ISSUE THREAD

**Issue by zankcou** [WoWManiaUK/Redemption#6110]
**Links:**

**What is Happening:**

the fortunate misunderstanding oracles quest will not start the escort widow opens click lets got nothing window stays open 
next
forging the alliance thor sent me to king i have unlocked and can do daily all but 1 as the king has not given me the quest to move the anvil , hot and cold daily for sons of hodir cant see hot metal but that must be caused by anvil still in same area 
**What Should happen:**
oracle moves
king give a quest to move anvil and then turn in forging the alliance

**Comment by zankcou** [comment]
i have clean fresh game no read only files use launcher,no addons

**Comment by Lumber-Jack-2** [comment]
fortunate misunderstanding > you need the fitting previous quest to start it see https://github.com/WoWManiaUK/Redemption/issues/4741

anvil stormpeaks quest also needs special conditions, check database and guides first

**Comment by Echinaceax** [comment]
fortunate misunderstanding is fully fixed @zankcou 
for forging the alliance make an ingame ticket for help
