### ISSUE TITLE
[NPC] Seething Revenant - Drop % on loot is very low 

### ISSUE THREAD

**Issue by qben61** [WoWManiaUK/Redemption#6111]
**Links:**

**What is Happening:**
I have been and killed a lot of Seeting Revenants under 2 days now and try to get some Crystallized Fire in Stormpeaks/Dun Niffelem. But they do not drop anything for me not even trash, just empty corpses the same for the revenants and mobs in that area.

**What Should happen:**
I expect to get SOME loot "that would be really nice"

**Comment by Echinaceax** [comment]
Thanks for reporting, 
remember to give links in your report 

@Rushor looks like no loottable
Wowhead https://www.wowhead.com/wotlk/npc=30387/seething-revenant
Mania https://www.wow-mania.com/armory/?npc=30120

**Comment by Echinaceax** [comment]
Test shows there are loot on them, not always but do have loot 
https://i.gyazo.com/4382bb571a072bc5ae69c21c1e8fd4f9.mp4

killed quite a few 20+

![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/48cd4351-a00e-4200-a72e-a82f8327bd24)
![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/6d222502-245c-4bd6-8e52-98b30dba4e00)
![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/165f75fa-5a74-4e41-82ce-26f8e694b047)
![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/bc9a441d-c8b7-466d-9ce5-a50d6967bb02)
![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/7d86bbc7-d881-491c-bb5f-d84c40526928)


@Rushor 
drop % needs looking into. seems more 0 loots than actual loots

**Comment by qben61** [comment]
Thanks for looking in to it, and I will apologies for the lacking report "No Links" but it was my first bug report on this system.

Regards

**Comment by Echinaceax** [comment]
> Thanks for looking in to it, and I will apologies for the lacking report "No Links" but it was my first bug report on this system.

thats ok no problem, thanks again for reporting

**Comment by Lumber-Jack-2** [comment]
hey yes, the loot is wrong, will fix :)

**Comment by fvicaria** [comment]
Fixed and deployed on live
