### ISSUE TITLE
Flying mounts

### ISSUE THREAD

**Issue by Stek2Buph** [WoWManiaUK/Redemption#6112]
Hi,

I've found a bug that's not really "dangerous", mostly funny I'd say.
Some flying mounts (Swift Purple Gryphon for me at least) can be used in the old continents of azeroth. The icon doesn't appear grey and you can summon it, and fly as well.

Flying mounts shouldn't work in the Eastern Kindoms nor Kalimdor. I don't know which one do though.

Have a great day (I secretely wish you don't patch it)

Stek2Buph

I invite you to try it, in Stormwind for exemple. The textures are pretty funky.

**Comment by Lumber-Jack-2** [comment]
This is a feature of the server actually

**Comment by Echinaceax** [comment]
there are points where you can mount up in stormwind sure, we know about this issue. 
the funny stuff you mention are because of "low maps" in 3.3.5. not something that can be fixed so easy @Stek2Buph
