### ISSUE TITLE
Still no loot from ALL the the Revenants in Dun Niffelem.

### ISSUE THREAD

**Issue by qben61** [WoWManiaUK/Redemption#6113]
**Links:**
[https://www.wowhead.com/wotlk/npc=30387/seething-revenant](url)
https://www.wowhead.com/wotlk/npc=30160/brittle-revenant

**What is Happening:**
I have cleaned out the area 2 times, that will be about 40 kills and I still get empty corpses not even any trash just unlootable corpses. And since the report I left earlier was closed I will make you aware that I still have problems there and I can't get a loot even though the one testing it got some.

**What Should happen:**
Well I would need some loot..

Regards

**Comment by Lumber-Jack-2** [comment]
yes it needs refernce loot tables, can add it today

**Comment by qben61** [comment]
Well since´I'm not a programmer I had no idea. Looking forward to the adjustment and sorry to bother you all..

Regards

**Comment by fvicaria** [comment]
PLus don't reopen issues. Search first. This has been fixed and requires server restart
