### ISSUE TITLE
[Item] Barov Peasant Caller

### ISSUE THREAD

**Issue by Gribas82** [WoWManiaUK/Redemption#6114]
**Links:**
Trinket barov peasant caller

**What is Happening:**
Not work. The 3 servants not fight by our side

**What Should happen:**
The 3 servants be fight on our side and help us

**Comment by Lumber-Jack-2** [comment]
item=14023

**Comment by Lumber-Jack-2** [comment]
they will attack now when the player attacks

**Comment by Echinaceax** [comment]
https://wowpedia.fandom.com/wiki/Barov_Peasant_Caller
Item fixed but 
Ally and horde same item but should summon different Servants 

Ally - Servant of Weldon Barov
Horde - Servant of Alexi Barov


![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/2cfe70e3-cc48-4e1c-9eb6-888bfc02972e)

**Comment by Lumber-Jack-2** [comment]
there are two different quests one for horde one for alli 5342, 5344

they reward item 14022 or 14023

issue atm is that quest 5342 should have horde only flag, but it has not

**Comment by Lumber-Jack-2** [comment]
fixed that condition, quest 5342is now only for horde, the summoned npcs also fixed

**Comment by Echinaceax** [comment]
Fixed in PTR 

Ally https://i.gyazo.com/02f1d0b0b4ad548cb5096dc250a7a6b8.mp4
Horde https://i.gyazo.com/969e5cd49da3ca423252901b42f145e5.mp4
