### ISSUE TITLE
[Object] Plagued Proto-Drake Egg

### ISSUE THREAD

**Issue by Woofles** [WoWManiaUK/Redemption#6115]
[Plagued Proto-Drake Egg](https://www.wow-mania.com/armory/?object=191840)
[The Aberrations Must Die](http://www.wow-mania.com/armory?quest=13425)
[Vial of Frost Oil](https://www.wow-mania.com/armory/?item=41612)

**What is Happening:**
When the vial is used on the eggs they should disappear.
They don't at the moment.
Same mechanic as #6040

**Comment by Echinaceax** [comment]
Thanks @Woofles for reporting 
we will take a look :)

**Comment by Echinaceax** [comment]
Confirmed bugged 

- [ ] Eggs dont disappear 

https://i.gyazo.com/2ed4ecaa927a7c67ff7a111d1e01df19.mp4

**Comment by Lumber-Jack-2** [comment]
they will be inactive for few minutes now before becoming active again

**Comment by Echinaceax** [comment]
fixed in ptr 
https://i.gyazo.com/4516bf8b3e26034222407f4d41ea1d64.mp4
