### ISSUE TITLE
[Item] Trinket - Talisman of Troll Divinity 

### ISSUE THREAD

**Issue by Woofles** [WoWManiaUK/Redemption#6116]
Item - [Talisman of Troll Divinity](https://www.wow-mania.com/armory/?item=37734)

When used the trinket applies the spell [Talisman of Troll Divinity](https://www.wow-mania.com/armory/?spell=60517) on the caster but when healing a target (tested in party, on both myself and the other member) the target doesnt get the buff [Touched by a Troll](https://www.wow-mania.com/armory/?spell=60518).

**Comment by Echinaceax** [comment]
Thanks @Woofles for reporting
we will take a look :)

**Comment by Echinaceax** [comment]
Confirmed bugged 

- [ ] 60518 - Touched by a troll not proccing 

atm https://i.gyazo.com/23ef4e90fb89b105b20290478c16a493.mp4

how it should be https://i.gyazo.com/be13e7ad043bf5f7a1f07ff245e2b6ed.mp4

**Comment by Lumber-Jack-2** [comment]
spell proc should be enabled now

**Comment by Echinaceax** [comment]
fix confirmed on PTR 

with 2 palas :)

https://i.gyazo.com/2e9c7ce8b9152f77a71f1a0daaf0d639.mp4
