### ISSUE TITLE
[Quest] Return My Remains - missing post-hand in event

### ISSUE THREAD

**Issue by Greywolf59** [WoWManiaUK/Redemption#6118]
!!Whole sections on Quests and on NPCs of Wow-Mania Armory does not work, it is empty, No data to display.!! So I will link wowhead links.

[Return My Remains](https://www.wowhead.com/wotlk/quest=11638/return-my-remains)
So the Completion text on this quest caught my attention:
"Thank you for freeing his spirit from Kaganishu and returning with his remains. We have little to reward you with, but you may take whatever catches your eye.

**And now, I will return him to the living where he belongs.**"

So I googled up and indeed, [Spirit Talker Snarlfang](https://www.wowhead.com/wotlk/npc=25339/spirit-talker-snarlfang) is supposed to ressurect the remains of [Farseer Grimwalker](https://www.wowhead.com/wotlk/npc=25461/farseer-grimwalker) according to the wowhead comments (from years 2008 and 2009) under the quest.

Only video I coudl find showing the ressurection: https://www.youtube.com/watch?v=g6KYzXANZDI&ab_channel=ZaFrostPet
There is also one from wotlk classic that ends abruptly but it is seen that NPC cries nad puts the remains on the ground before the video ends. None of that happens on Mania.

**Comment by Echinaceax** [comment]
confirmed missing ressurection and no bones spawn either https://i.gyazo.com/58a5b90c0e9d2b05545bb344b36bf2f5.mp4


checked also a 2015 video timestamp 1:48 https://www.youtube.com/watch?v=iakK4GQt1Yo

**Comment by Lumber-Jack-2** [comment]
added the spawn effect and the texts, all i saw in the video. all i could do for now

**Comment by Echinaceax** [comment]
Confirmed fixed in PTR 
https://i.gyazo.com/e9f8c04a0633425cc9425810246a5fad.mp4
