### ISSUE TITLE
[Quest] Windseer Grayhorn's Quests in wrong order and missing

### ISSUE THREAD

**Issue by Greywolf59** [WoWManiaUK/Redemption#6119]
When player arrives to Conquest Hold, [Windseer Grayhorn](https://www.wowhead.com/wotlk/npc=27262/windseer-grayhorn) is offering these quests all at once:
[A Possible Link](https://www.wowhead.com/wotlk/quest=12229/a-possible-link)
[Eyes Above](https://www.wowhead.com/wotlk/quest=12453/eyes-above) (separate quest)
[The Bear God's Offspring](https://www.wowhead.com/wotlk/quest=12231/the-bear-gods-offspring)
[Destroy the Sapling](https://www.wowhead.com/wotlk/quest=12241/destroy-the-sapling)
[Vordrassil's Seeds](https://www.wowhead.com/wotlk/quest=12242/vordrassils-seeds)

On the other hand the NPC is missing these quests:
[Vordrassil's Fall](https://www.wowhead.com/wotlk/quest=12207/vordrassils-fall)
[The Darkness Beneath](https://www.wowhead.com/wotlk/quest=12213/the-darkness-beneath)

How it should be:
Grayhorn should offer Vordrassil's Fall and The Darkness Beneath (plus Eyes Above as standalone quest). After completing those two quests Grayhorn should offer A Possible Link and The Bear God's Offspring. After completing these other two quest, the NPC should offer Vordrassil's Seeds and Destroy the Sapling, leading up to [Ursoc, the Bear God](https://www.wowhead.com/wotlk/quest=12236/ursoc-the-bear-god).
Source: https://wowpedia.fandom.com/wiki/Ursoc,_the_Bear_God_(Horde)#Progression

If I remember correctly from my last Horde playthrough a few weeks ago, the Vordrassil's Fall and The Darkness Beneath are never offered. Last time I have done Alliance side (a few months back) the Alliance side worked fine and in same manner as Progression describes for Horde version on wowpedia.

**Comment by Echinaceax** [comment]
confirmed bug

Quest order shouldnt be all at the same time

![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/dfa8abce-acd9-4bc9-b336-5d1fe0c81d39)


- [ ] Should be 2-2-2-1 
timestamp 0:05 https://www.youtube.com/watch?v=CmWoQOnx0ww

![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/ed02ba24-6e62-4feb-9899-f22427eb797f)

**Comment by Greywolf59** [comment]
Came upon further informations about this while researching other quests in form of this comment: https://www.wowhead.com/wotlk/quest=12413/attack-on-silverbrook#comments:id=592880
According to this, quest chain should be open only after completing quest [Attack on Silverbrook](https://www.wowhead.com/wotlk/quest=12413/attack-on-silverbrook).

**Comment by Echinaceax** [comment]
![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/5f402cef-2937-4e22-aa63-3089282375c1)

**Comment by Greywolf59** [comment]
Confirmed. After handing in Attack on Silverbrook, quests Vordrassil's Fall and The Darkness Beneath appeared at the quest giver.

**Comment by Lumber-Jack-2** [comment]
quest order is applied

**Comment by Echinaceax** [comment]
Only offering the [Eyes Above](https://www.wowhead.com/wotlk/quest=12453/eyes-above) (separate quest)

when player is NOT on the correct progression (seems ok for now) 
though we will need to trace full quests later when others are fixed

![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/c32f5095-f147-4b27-980c-f5e471cd4912)
