### ISSUE TITLE
[NPC] Wretched Skulker / Bruiser

### ISSUE THREAD

**Issue by Earthliving** [WoWManiaUK/Redemption#612]
Enemies in Magister's Terrace heroic are consuming a potion that enhances their damage by x2000. It's gotta be off by a few decimals..

**Comment by Igotpooedon** [comment]
this has now been fixed or it's got bugged again because they hit a lvl 80 with 15k armor for 15-30k dmg each melee swing they do. and they attack in a party of 3-6 so it's a fast death

**Comment by tvshadowz** [comment]
Hi there Igotooedon!

If you could fill out a new report on this it would much appreciated as we can work on it again. Sorry about the inconvenience.
