### ISSUE TITLE
Error al mostrar los talentos

### ISSUE THREAD

**Issue by drearySeagull** [WoWManiaUK/Redemption#6122]
**Links:**
![image](https://github.com/WoWManiaUK/Redemption/assets/23643095/358f939e-4cae-4a4a-9d80-0a10c64febd9)

**What is Happening:**
No puedo visualizar los talentos de mi personaje

**What Should happen:**
Entiendo que deberian de mostrarse

**Comment by fvicaria** [comment]
This is only for Worgen for some reason. I will look into this but it will take a few days.
Por alguna razón, esto es sólo para huargen. Lo investigaré pero tardará unos días.

**Comment by fvicaria** [comment]
For now, my suggestion is to log in with the English and assign the talent points then come back to the Spanish client. 
Por ahora, mi sugerencia es iniciar sesión en inglés y asignar los puntos de talento y luego volver al cliente en español.

**Comment by fvicaria** [comment]
Fixed. You will have to download the Spanish Patch for the fix.
Fijado. Tendrás que descargar el parche en español para solucionarlo.

**Comment by drearySeagull** [comment]
thank you so much

**Comment by drearySeagull** [comment]
Hola, me baje nuevamente el cliente de español y no está resuelto.

**Comment by fvicaria** [comment]
We have a new update for the Spanish client. This includes also a new Launcher in Spanish.
Tenemos una nueva actualización para el cliente español. Esto incluye también un nuevo Launcher en español.

Parche mas Lanzador para Cliente español: https://mega.nz/file/0vxQQIpQ#rYOcxd3zxAmUfUQ9lj9Visshsd6cqMDA9nB5OBDXRvM
