### ISSUE TITLE
Shade of Arugal - Has only Phase 1

### ISSUE THREAD

**Issue by Greywolf59** [WoWManiaUK/Redemption#6123]
[Shade of Arugal](https://www.wowhead.com/wotlk/npc=27018/shade-of-arugal) is main target of the quest [Hour of the Worg](https://www.wowhead.com/wotlk/quest=12164/hour-of-the-worg)

According to wowhead comemnts and wiki – https://wowpedia.fandom.com/wiki/Shade_of_Arugal – he should ahve several Phases. I cannot say if he does use mc [Worgen's Command](https://www.wowhead.com/wotlk/spell=53070/worgens-command) if there are more players, however he does not use [Phase Out](https://www.wowhead.com/wotlk/spell=53052/phase-out) and does not summon any help during the encounter. He just keeps casting [Shadow Bolts](https://www.wowhead.com/wotlk/spell=53086/shadow-bolt) the whole time.

[This comment](https://www.wowhead.com/wotlk/quest=12164/hour-of-the-worg#comments:id=392916) also states that "Annoyingly enough, Arugal is not interruptable, but his shadow bolts can be grounded and LOSed. I was forced to just heal through and ground most of them." In my case as DK I could Interrupt his spell casts by Death Grip, Mind Freeze and Strangulate.

And as a side note, [Bloodmoon Cultists](https://www.wowhead.com/wotlk/npc=27024/bloodmoon-cultist) does not seem to change form to worgen, on videos they do.

Wotlk Classic: https://www.youtube.com/watch?v=cCyRi1LIruE&ab_channel=scarything
14 years old video (solo); start at 4:00: https://www.youtube.com/watch?v=F8qsphRUR8M&ab_channel=Vampirez0

**Comment by Maine1** [comment]
The phase out ability was only added for classic patch 3.4.0 onwards. Shade of Arugal doesn't use Phase Out ability in the older video either. As far as the interrupts go there is only an old video of paladin. Until we get evidence that the DK death grip or strangulate etc isn't supposed to interrupt this will remain the same. Only fix is Bloodmoon Cultists not changing into worgens. 
@Rushor up to you to decide if this is a fix worth doing. They died very quick to level 80 damage

**Comment by Greywolf59** [comment]
The Phase Out is definitely there on the video.
4:57 → 80 % HP, Arugal disappears (teleports back to starting position)
5:02 → Arugal visible standing at starting position, 3 new worgens spawned.
5:57 → 40 % HP, teleport again
6:00 → Arugal on starting position, more worgens, Sasha becomes active ( /say, shoots on mobs and joins the fight)

Sasha does not join the fight on Red either. [Phase Out](https://www.wow-mania.com/armory/?spell=53052) spell can be found in wow-mania armory database too, with the same ID as the one from 3.4.0.

**Comment by Echinaceax** [comment]
At the moment Janitor will only fix gamebreaking issues not all this nit-picking ones. 
Closing until further notice.
