### ISSUE TITLE
[Quest] The Damaged Journal – missing post-completion event

### ISSUE THREAD

**Issue by Greywolf59** [WoWManiaUK/Redemption#6124]
[The Damaged Journal](https://www.wowhead.com/wotlk/quest=12026/the-damaged-journal), after handing in this quest, [Sage Paluna](https://www.wowhead.com/wotlk/npc=26584/sage-paluna) and [Scout Vor'takh](https://www.wowhead.com/wotlk/npc=26666/scout-vortakh) should have a small conversation, the text of the next quest, [Deciphering the Journal](https://www.wowhead.com/wotlk/quest=12054/deciphering-the-journal), hints at it:
"Vor'takh is right -- we cannot allow this opportunity to slip through our fingers.

Fortunately, I think I know of a way to translate the journal of this Brann. …"
https://wowpedia.fandom.com/wiki/The_Damaged_Journal#Notes_2 states:
When completing the quest:

Sage Paluna says: This is an intriguing find, (name), but I don't know what to make of it.
Sage Paluna says: The language is unfamiliar and for all we know, it's just some soldier's journal.
[Scout Vor'takh](https://wowpedia.fandom.com/wiki/Scout_Vor%27takh) says: Let me take a look at that.
Scout Vor'takh says: Hmm...
Scout Vor'takh says: This journal is written in dwarven. I can't read this scrawl, but I can make out one thing.
Scout Vor'takh says: 'Brann Bronzebeard.' The brother of [Ironforge's king](https://wowpedia.fandom.com/wiki/Magni_Bronzebeard)? You may have spoken too soon, Paluna.
Sage Paluna says: What do you mean?
Scout Vor'takh says: Think about how valuable a member of the dwarven royal family would be as a hostage.
Scout Vor'takh says: If he's in the area, we must find him. First, though, we'll need a way to decipher this journal.

**Comment by Echinaceax** [comment]
Confirmed, no convo text https://i.gyazo.com/1e87e189c898136082c5b719752cfb25.mp4
Timestamp 1:32 https://www.youtube.com/watch?v=S2-qtrBreCw

**Comment by Lumber-Jack-2** [comment]
endevent added with text, also for the alliance quest quest=11986

**Comment by Echinaceax** [comment]
Almost 
His last text line is double @Rushor 
https://i.gyazo.com/2f49ee6169268257b78b8eaaf1d43843.mp4

- [ ] missing his last line 

"Scout Vor'takh says: If he's in the area, we must find him. First, though, we'll need a way to decipher this journal."

![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/96fed3dd-579b-48aa-9400-d233fe1f7d1f)

**Comment by Lumber-Jack-2** [comment]
fixed next restart

**Comment by Echinaceax** [comment]
confirmed fixed in PTR 

![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/70144365-cc13-4045-93ab-a1e263e94e10)
