### ISSUE TITLE
[Quest] Deciphering the Journal – Missing post-completion event

### ISSUE THREAD

**Issue by Greywolf59** [WoWManiaUK/Redemption#6125]
[Deciphering the Journal](https://www.wowhead.com/wotlk/quest=12054/deciphering-the-journal)

After handing in this quest, a conversation between [Sage Paluna](https://www.wowhead.com/wotlk/npc=26584/sage-paluna) should say,
according to https://wowpedia.fandom.com/wiki/Deciphering_the_Journal#Notes:

Sage Paluna says: Let us see what this journal reveals.
Sage Paluna says: [Scout Vor'takh](https://wowpedia.fandom.com/wiki/Scout_Vor%27takh)'s hunch was correct. Brann Bronzebeard visited [Thor Modan](https://wowpedia.fandom.com/wiki/Thor_Modan) recently and this journal records his findings.
Sage Paluna says: He managed to explore the ruins before the battle began, discovering three runic plates inscribed with prophecies.
Sage Paluna says: Brann doesn't record the translations, but it says he committed them to memory before fleeing the battle.
Sage Paluna says: If you can translate those plates, we can find and capture Brann.

This event does not occur.

At the very end of this 1 year old video here is visible that Sage Paluna is performing some action, putting something down on the ground perhaps. Sadly, the video ends there and I haven't found any other videos concerning the quest.
https://www.youtube.com/watch?v=mD12nOcBL5E&ab_channel=ZaFrostPet

**Comment by Echinaceax** [comment]
Confirmed no chatter https://i.gyazo.com/09e99f9ad300dbc8fa05aa9aec5135a8.mp4
cant find video of it tho, videos end before it shows

**Comment by Lumber-Jack-2** [comment]
chatting added

**Comment by Echinaceax** [comment]
Confirmed fixed in PTR 
https://i.gyazo.com/bb2aaa7ae8c9825e6893b794a8e8abcb.mp4
