### ISSUE TITLE
[Quest] Fuel for the Fire – missing Shalewing and Chieftain interaction; respawn timer

### ISSUE THREAD

**Issue by Greywolf59** [WoWManiaUK/Redemption#6126]
[Fuel for the Fire](https://www.wowhead.com/wotlk/quest=12690/fuel-for-the-fire)
You are suppsoed to use Abom to kill 60 Skullcrsuhers. After every 20 killed, [Drakkari Chieftain](https://www.wowhead.com/wotlk/npc=28873/drakkari-chieftain) spawns. Problem is he just keeps standing there. He should run to the player, say something and then [Shalewing](https://www.wowhead.com/wotlk/npc=28879/shalewing) should take him away.

Check quotes on [Drakkari Chieftain](https://www.wowhead.com/wotlk/npc=28873/drakkari-chieftain) wowhead entry.
[2009 comment mentioning the event](https://www.wowhead.com/wotlk/npc=28873/drakkari-chieftain#comments:id=865570)
https://wowpedia.fandom.com/wiki/Drakkari_Chieftain#Quotes

Classic Beta video: https://www.youtube.com/watch?v=y4uNmuDBwI8&ab_channel=WarcrafterSnorri
14 year old video; 1:40 – 1:50 https://www.youtube.com/watch?v=E9P6ULOutmE&ab_channel=JakeDunigan
 This video shows that player is thrown away by explosion which is also mentioned in some of the wowhead comments. at the 1:50 it is visible that troll cheiftain runs to the player and says something, sadly the video is cut at that moment.

**Comment by Greywolf59** [comment]
There is also a second, more troublesome issue. The respawn timer on [Drakkari Skullcrusher](https://www.wowhead.com/wotlk/npc=28844/drakkari-skullcrusher) seems way too long, at least on most of them. I have found on github of another server that respawn timer should be:
"About the respawn time, it was 5 minutes and the corpse despawned at minute 2. This was tested in Blizzard, Ragnaros-US", entry made on July 29, 2020.
You can DM me on discord for the source link, I wasnt sure if it would be okay to post it here, especially since it would be visible on the other github.

EDIT: used Stopwatch. Killed them normally (quest already handed in). Corpse despawn after 1 minute. Respawn time 6 minutes.

**Comment by Echinaceax** [comment]
- Confirmed the respawn timer is set at 5 mins 
- [Drakkari Chieftain](https://www.wowhead.com/wotlk/npc=28873/drakkari-chieftain) stands there after lured, then despawns

**Comment by Lumber-Jack-2** [comment]
added the event with Shalewing, reduced the respawntimer for 28844 for a better questflow

**Comment by Echinaceax** [comment]
fixed in PTR 

![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/51826ff7-1684-4f75-9326-d5aa76e37608)
