### ISSUE TITLE
[Quest] [NPC] Cocooned! – 4x spawn from cocoons

### ISSUE THREAD

**Issue by Greywolf59** [WoWManiaUK/Redemption#6127]
During the quest [Cocooned!](https://www.wowhead.com/wotlk/quest=12606/cocooned) player breaks the [Nerubian Cocoons](https://www.wowhead.com/wotlk/npc=28413/nerubian-cocoon) to rescue three [Captive Footman](https://www.wowhead.com/wotlk/npc=28415/captive-footman). The cocoon can also [Drakkari Captive](https://www.wowhead.com/wotlk/npc=28414/drakkari-captive) inside.
Problem is that when it contains Drakkari Captive, the troll is spawned four times.

**Comment by Echinaceax** [comment]
Confirmed spawns 4 Trolls in one https://i.gyazo.com/d1cbf62541cf2151803f527175e60dc8.mp4

**Comment by Lumber-Jack-2** [comment]
will only be obne troll now

**Comment by Lumber-Jack-2** [comment]
spell is ID - 51597 Summon Scourged Captive

**Comment by Echinaceax** [comment]
Its the troll ones @Rushor 

test 1 
Still not fixed spawns 2 https://i.gyazo.com/7f84294fa71e20c3feb088952ae50c58.mp4

test 2 
![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/391af9b5-54d9-4f3b-8d69-04a18716b5e4)


Yes I deleted cache :)

**Comment by Lumber-Jack-2** [comment]
hopefully 1 now

**Comment by Echinaceax** [comment]
Fixed in PTR 

![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/71ab6e85-bcba-45d8-987a-835201e55f1c)
