### ISSUE TITLE
[Quest] Breaking Through Jin'Alai – incomplete post-completion event

### ISSUE THREAD

**Issue by Greywolf59** [WoWManiaUK/Redemption#6130]
After completing [Breaking Through Jin'Alai](https://www.wowhead.com/wotlk/quest=12627/breaking-through-jinalai) there is a small event played out. Animal gods will spawn and [Witch Doctor Khufu](https://www.wowhead.com/wotlk/npc=28479/witch-doctor-khufu) whispers. After that the Animal Spirit Gods should talk but they do not.
https://www.wowhead.com/wotlk/quest=12627/breaking-through-jinalai#comments:id=860021
https://wowpedia.fandom.com/wiki/Breaking_Through_Jin%27Alai#Notes

**Comment by Maine1** [comment]
Witch Doctor Khufu whispers: Gods of old, we beseech you. What must we do? How can we save the gods of this land?
[Jan'alai](https://wowpedia.fandom.com/wiki/Jan%27alai) says: The spotted one must be sought. Their fates are entwined.
[Akil'zon](https://wowpedia.fandom.com/wiki/Akil%27zon) says: But she is chained. A way must be found to free her.
[Halazzi](https://wowpedia.fandom.com/wiki/Halazzi) says: To her altar this mortal must travel. What they must do will not be easy. In the end it may prove impossible.
[Nalorakk](https://wowpedia.fandom.com/wiki/Nalorakk) says: But try they must or all will be lost. The [Drakkari](https://wowpedia.fandom.com/wiki/Drakkari) will be the death of both themselves and their gods!

All the gods gossip is missing from NPC's - 
Jan'alai - The spotted one must be sought. Their fates are entwined.
Akil'zon - But she is chained. A way must be found to free her.
Halazzi -  To her altar this mortal must travel. What they must do will not be easy. In the end it may prove impossible.
Nalorakki - But try they must or all will be lost. The [Drakkari](https://wowpedia.fandom.com/wiki/Drakkari) will be the death of both themselves and their gods!

@Rushor this is the only fix needed for this

Witch Doctor Khufu whispers: Gods of old, we beseech you. What must we do? How can we save the gods of this land? 

This gossip for Witch Doctor Khufu is already active

**Comment by Lumber-Jack-2** [comment]
text for the 4 summons are enabled now

**Comment by Maine1** [comment]
![image](https://github.com/WoWManiaUK/Redemption/assets/122736582/6e34be70-8f4e-465f-ae83-c5ca90a2830d)
Confirmed :) thanks Rushor
