### ISSUE TITLE
[Quest] Blessing of Zim'Torga – should be repeatable

### ISSUE THREAD

**Issue by Greywolf59** [WoWManiaUK/Redemption#6131]
After completing quest [The Blessing of Zim'Torga](https://www.wowhead.com/wotlk/quest=12615/the-blessing-of-zimtorga), repeatable quest [Blessing of Zim'Torga](https://www.wowhead.com/wotlk/quest=12618/blessing-of-zimtorga) opens up.
On our server however, Blessing of Zim'Torga is normal quest, accepted, delivered and unrepeatable. It does count towards Loremaster, which it probably should not.

**Comment by Echinaceax** [comment]
Confirmed fixed in PTR https://i.gyazo.com/d935f5c06e55094108fdbcc6429b8da2.mp4
repeatable 
https://i.gyazo.com/1948f99538ce01788fbf160191a6811c.mp4
