### ISSUE TITLE
[Quest] Blessing of Zim'Rhuk – should be repeatable

### ISSUE THREAD

**Issue by Greywolf59** [WoWManiaUK/Redemption#6132]
After completing quest [The Blessing of Zim'Rhuk](https://www.wowhead.com/wotlk/quest=12655/the-blessing-of-zimrhuk), repeatable quest [Blessing of Zim'Rhuk](https://www.wowhead.com/wotlk/quest=12656/blessing-of-zimrhuk) opens up.
On our server however, Blessing of Zim'Rhuk is normal quest, accepted, delivered and unrepeatable. It does count towards Loremaster, which it probably should not.

**Comment by Echinaceax** [comment]
confirmed fixed in PTR 
https://i.gyazo.com/81bff371377a7740bc7ccdd2c5feb260.mp4
Repeatable 
https://i.gyazo.com/890ee3cb99bfab790df3aa9c772f5327.mp4
