### ISSUE TITLE
[Quest] [Vehicle] Wooly Justice – Mammoth stays in combat

### ISSUE THREAD

**Issue by Greywolf59** [WoWManiaUK/Redemption#6133]
In quest [Wooly Justice](https://www.wowhead.com/quest=12707/wooly-justice) player saddles up [Enraged Mammoth](https://www.wowhead.com/wotlk/npc=28851/enraged-mammoth#abilities) and kills [Mam'toth Disciples](https://www.wowhead.com/wotlk/npc=28861/mamtoth-disciple).

Mammoth stays in combat, making [Rushing Charge](https://www.wowhead.com/wotlk/spell=52601/rushing-charge) unusable.
In this video, player does not use the charge, however you can see message "Leaving Combat" pop up and Charge lightening up.
0:17 → https://www.youtube.com/watch?v=YVeEF7yOcTc&ab_channel=Alfdaelf

**Comment by Maine1** [comment]
Confirmed bugged. Mammoth not leaving combat!
@Rushor

**Comment by Lumber-Jack-2** [comment]
behaviour should be better now, but i cannot fix more here on it, general vehicle issue

**Comment by Maine1** [comment]
Confirmed fixed quite a lot from before, not 100% as already mentioned
