### ISSUE TITLE
[Quest] Hexed Caches – no curses

### ISSUE THREAD

**Issue by Greywolf59** [WoWManiaUK/Redemption#6134]
During the quest [Hexed Caches](https://www.wowhead.com/wotlk/quest=12709/hexed-caches), there is random chance that opening the [Zol'Maz Stronghold Cache](https://www.wowhead.com/wotlk/object=190836/zolmaz-stronghold-cache) will affect the player with one of three hexes.
[Hex of Agony](https://www.wowhead.com/wotlk/spell=52647/hex-of-agony), [Hex of Weakness](https://www.wowhead.com/wotlk/spell=52645/hex-of-weakness), [Hex of Tongues](https://www.wowhead.com/wotlk/spell=52652/hex-of-tongues).
I do not recall ever getting hexed doing this quest (over 5 times for sure).
https://wowpedia.fandom.com/wiki/Hexed_Caches#Notes
https://www.wowhead.com/wotlk/object=190836/zolmaz-stronghold-cache#comments:id=486804

**Comment by Maine1** [comment]
@Rushor Checked on PTR and no curses also. No video evidence to show if these were working back on retail 2009. Only 1 video from a year ago after classics release. I'll leave this 1 for you to decide also.

**Comment by Echinaceax** [comment]
At the moment Janitor will only fix gamebreaking issues not all this nit-picking ones.
Closing until further notice.
