### ISSUE TITLE
[Quest] Rampage – death of Akali event

### ISSUE THREAD

**Issue by Greywolf59** [WoWManiaUK/Redemption#6135]
This might be odd one out because I am not sure at all if this did not work properly before, however here goes.
During the quest [Rampage](https://www.wowhead.com/wotlk/quest=12721/rampage) When player frees Akali and [Prophet of Akali](https://www.wowhead.com/wotlk/npc=28996/prophet-of-akali) arrives, he emotes a few times and kills Akali. Full event described here at https://wowpedia.fandom.com/wiki/Rampage_(quest)#Notes:

Akali yells: I'M FREE, LITTLE [DRAKKARI](https://wowpedia.fandom.com/wiki/Drakkari). TIME TO PAY FOR YOUR MANY TRESSPASSES!
Akali kills dozens of Akali Subduers.

[Prophet of Akali](https://wowpedia.fandom.com/wiki/Prophet_of_Akali) yells: ENOUGH!
Prophet of Akali yells: And now, Akali, my master will have your blood and I will take some of your power as well!
The Prophet kills Akali.

Prophet of Akali yells: It is done. Run back to your masters. Run back to [Har'koa](https://wowpedia.fandom.com/wiki/Har%27koa). Tell her that I am coming!

1: Could be noted that he does not kill that many Subduers really, in videos I have checked he indeed kills dozens of them, however basically none of these videos show this in detail.
2: In case of my playthrough the evenet stopped by Prophet of Akali yelling "ENOUGH!" and did not continue further. As to how the event should look, there is no video, no player bothered to stay, watch and record.
3: Missing Har'koa's whisper upon hand in. The rest of hand-in event works fine.
Har'koa whispers: No, not Akali too!

**Comment by Maine1** [comment]
@Rushor I'll also leave this up to you. Once again without video evidence of what should happen vs what doesn't or does happen. Is it right to fix or not? Your decision

**Comment by Echinaceax** [comment]
At the moment Janitor will only fix gamebreaking issues not all this nit-picking ones.
Closing until further notice.
