### ISSUE TITLE
Error con el addon Quartz - ES Client

### ISSUE THREAD

**Issue by drearySeagull** [WoWManiaUK/Redemption#6136]
**Links:**
![image](https://github.com/WoWManiaUK/Redemption/assets/23643095/ec2644e9-fd34-4807-8751-002dd4e35c82)
![image](https://github.com/WoWManiaUK/Redemption/assets/23643095/617c128c-36bf-46eb-8e50-81004d4f823c)
![image](https://github.com/WoWManiaUK/Redemption/assets/23643095/3b5b9358-7b00-4e7c-a70e-79e578cbf066)

**What is Happening:**
Hola, en el cliente de español no funcionan los addons, intento meter el quartz y no funciona. Ademas no aparece en el menu de la interfaz (tercera foto)

**What Should happen:**
Al escribir el comando /quartz deberia de abrirse una ventana y no lo hace. En el ingles he comprobado que si funciona.

**Comment by fvicaria** [comment]
Just delete them. I will release another torrent with no addons.

**Comment by drearySeagull** [comment]
¿y con eso funcionará el addon "quartz" u otros addons?
