### ISSUE TITLE
Stormstrike does not trigger Windfury

### ISSUE THREAD

**Issue by JohnBrinkle** [WoWManiaUK/Redemption#6137]
**Links**
https://www.wowhead.com/wotlk/spell=17364/stormstrike#comments
"1) SS can trigger WF anytime, [...]"

**What is Happening:**
Using Stormstrike with Windfury buff on a weapon hits the target with two Stormstrike hits (for each melee weapon)
marked as special ability hits.
It is never followed by Windfury hits.

**What Should happen:**
It should also hit by 20% with Windfury.
But looking at the combat log, hitting with Stormstrike never procs Windfury, only a normal melee hit does.
That may be because Stromstrike counts as special ability hit.
But the descriptions says "Instantly attack with both weapons".
I know it did trigger on official servers back at wotlk times and comments from 2008 on wowhead say so too.

**Comment by Maine1** [comment]
![image](https://github.com/WoWManiaUK/Redemption/assets/122736582/2f081d5c-51d8-4c39-8940-787a3e27f930)

**Comment by Lumber-Jack-2** [comment]
deep core mechanic, will not be touched. current proc flags are:
  32 (0x20) - Taken damage by Spell that use melee weapon
  512 (0x200) - Taken damage by Spell that use ranged weapon
  8192 (0x2000) - Taken negative spell hit
  131072 (0x20000) - Taken magic spell damage
