### ISSUE TITLE
[Quest] Vahlarriel's Search - Completion text blank

### ISSUE THREAD

**Issue by stealer0517** [WoWManiaUK/Redemption#6138]
https://www.wow-mania.com/armory/?quest=1465

When you return to Vahlarriel Demonsalyer the first page of the quest completion text is blank.
Once you hit continue the correct text is there.

There should only be the complete text screen, and not the blank page.
![vahlarriels quest text blank](https://github.com/WoWManiaUK/Redemption/assets/6968045/46a1b89e-1dc6-45ae-98bc-eee9c19902ea)

**Comment by Maine1** [comment]
@Rushor https://www.youtube.com/watch?v=F3rfghPXSJ8

4 year old video Confirming this quest text is missing and needs adding 

This completion text need adding - 

Infuriating! This entire fiasco!

The two of them were warned about how dangerous coming here would be. Now they're both missing... or worse.

You said you saw tracks heading to a fort nearby? That may be our best bet.

From what the locals have said, that fortress is infested with members of the Burning Blade--orcs who have dedicated themselves to demon causes. They may not represent the majority of the Horde's beliefs, but they are evil and will slay you on sight if you're caught spying.

**Comment by Echinaceax** [comment]
Confirmed fixed in PTR 

![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/3c502553-8e01-4d34-ad4f-df2b7de1f63c)
