### ISSUE TITLE
[K3][Quest] Expression of Gratitude – available too late

### ISSUE THREAD

**Issue by Greywolf59** [WoWManiaUK/Redemption#6140]
[Expression of Gratitude](https://www.wow-mania.com/armory/?quest=12836) should be available right away, as starting quest of the  one of three quest chains opening the quest [Opening the Backdoor](https://www.wow-mania.com/armory/?quest=12821).
[Expression of Gratitude](https://www.wow-mania.com/armory/?quest=12836) + [Reclaimed Rations](https://www.wow-mania.com/armory/?quest=12827) → [Ample Inspiration](https://www.wow-mania.com/armory/?quest=12828) → [Opening the Backdoor](https://www.wow-mania.com/armory/?quest=12821).

This quest is available only after some other quest is done which should not be the case. As to which quest, I will inform you when I actually get this quest.

https://wowwiki-archive.fandom.com/wiki/Quest:Expression_of_Gratitude#Quest_progression
https://wowpedia.fandom.com/wiki/Expression_of_Gratitude?so=search#Progression
https://www.wowhead.com/wotlk/quest=12836/expression-of-gratitude#comments:id=874931

**Comment by Greywolf59** [comment]
This quest is available only after completing [Ample Inspiration](https://www.wow-mania.com/armory/?quest=12828) that is avialable only after completing [Know No Fear](https://www.wow-mania.com/armory/?quest=12822), which is basically the end of the whole quest chain that is supposed to be started by this very quest,[Expression of Gratitude](https://www.wow-mania.com/armory/?quest=12836).

**Comment by Echinaceax** [comment]
this questline has been worked on before here @Greywolf59 https://github.com/WoWManiaUK/Redemption/issues/5736

**Comment by Lumber-Jack-2** [comment]
prevquest is removed, this sounds logic and matches the wowhead comments

In https://github.com/WoWManiaUK/Redemption/issues/5736 the quest Expression of Gratitude is not touched

**Comment by Echinaceax** [comment]
So what have you fixed here @Rushor ?

0:03 timestamp (2015 only tho) 
https://www.youtube.com/watch?v=xeLFLEBuZ8o

I only see [Reclaimed Rations](https://www.wow-mania.com/armory/?quest=12827) not [Expression of Gratitude](https://www.wow-mania.com/armory/?quest=12836) + [Reclaimed Rations](https://www.wow-mania.com/armory/?quest=12827)

![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/5d142d0d-f96a-4387-be39-752b78a8a725)

**Comment by Lumber-Jack-2** [comment]
Hm then there must be a hidden condition will check

**Comment by Lumber-Jack-2** [comment]
okay there were several error with the quests, now it works exactly like this:

[Expression of Gratitude](https://www.wow-mania.com/armory/?quest=12836) + [Reclaimed Rations](https://www.wow-mania.com/armory/?quest=12827) → [Ample Inspiration](https://www.wow-mania.com/armory/?quest=12828) → [Opening the Backdoor](https://www.wow-mania.com/armory/?quest=12821).

**Comment by Lumber-Jack-2** [comment]
Keep in mind Opening the backdoor requires more rewards as said in https://github.com/WoWManiaUK/Redemption/issues/6139

Ample Inspiration + A Delicate Touch + Bitter Departure

once those 3 are rewarded, only then Opening the Backdoor is available.

**Comment by Echinaceax** [comment]
I see the quest now 

Fixed in PTR 
https://gyazo.com/8ac5f33097427f68011f0ef7e97b13d8

**Comment by Maine1** [comment]
[Reclaimed Rations](https://www.wow-mania.com/armory/?quest=12827) Should not be in this quest chain series as this is a side quest! @Rushor
