### ISSUE TITLE
[K3][Quest] Ample Inspiration – Wrong prerequisites

### ISSUE THREAD

**Issue by Greywolf59** [WoWManiaUK/Redemption#6141]
[Ample Inspiration](https://www.wow-mania.com/armory/?quest=12828) becomes available after player completes [Know No Fear](https://www.wow-mania.com/armory/?quest=12822).
I have also completed [Reclaimed Rations](https://www.wow-mania.com/armory/?quest=12827) before, which is also one of the proper prerequisites for this quest. As to whether it opens after doing both these quests or just after Know No Fear I cannot say.

This quest should be available after completing [Expression of Gratitude](https://www.wow-mania.com/armory/?quest=12836), which is still not available at this point of playthrough, and [Reclaimed Rations](https://www.wow-mania.com/armory/?quest=12827). On the other hand Know No Fear should not be accessible at all until Ample Inspiration is complete → https://github.com/WoWManiaUK/Redemption/issues/6139

Completing Ample Inspiration actually opens up [Expression of Gratitude](https://www.wow-mania.com/armory/?quest=12836).

**Comment by Echinaceax** [comment]
this questline has been worked on before here @Greywolf59 https://github.com/WoWManiaUK/Redemption/issues/5736

**Comment by Greywolf59** [comment]
Which means? Cause that issue is closed and clearly still wrong and I see the K3 Garm quest chain was written down how it should be in the first post, that kind of resume of whole zone, but they were not mentioned anywhere later on an probably not worked on.
Also I am sorry, but sometimes when I write to closed issue I am told to open a new one, sometimes when I open a new one, I am shown to the closed one.

**Comment by Echinaceax** [comment]
> Which means? Cause that issue is closed and clearly still wrong and I see the K3 Garm quest chain was written down how it should be in the first post, that kind of resume of whole zone, but they were not mentioned anywhere later on an probably not worked on. Also I am sorry, but sometimes when I write to closed issue I am told to open a new one, sometimes when I open a new one, I am shown to the closed one.

Will add extra info from here you added. thanks @Greywolf59 
https://github.com/WoWManiaUK/Redemption/issues/5736#issuecomment-1854149297
