### ISSUE TITLE
[NPC] Peon Gakra – missing inn option

### ISSUE THREAD

**Issue by Greywolf59** [WoWManiaUK/Redemption#6142]
[Peon Gakra <Innkeeper & Supplies>](https://www.wow-mania.com/armory/?npc=29944) is missing the " Make this inn your home." option.
https://wowpedia.fandom.com/wiki/Peon_Gakra

**Comment by Lumber-Jack-2** [comment]
option is added now

**Comment by Echinaceax** [comment]
Confirmed fixed in PTR 

![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/3094c156-71e9-47a9-8eb0-8dccc98229ef)
