### ISSUE TITLE
[Quest] Emergency Measures – Worg Fur skinning

### ISSUE THREAD

**Issue by Greywolf59** [WoWManiaUK/Redemption#6143]
[Emergency Measures](https://www.wow-mania.com/armory/?quest=13000)
Player has to kill [Cavedweller Worgs](https://www.wow-mania.com/armory/?npc=30164) for [Worg Furs](https://www.wow-mania.com/armory/?item=42510).

Drop rate seems kind of okay, full clear yielded 4/6 of furs. However I happen to be a skinner. The quest item should be also skinned with 100% chance. None of my skins yielded this fur.
Sources:
https://wowpedia.fandom.com/wiki/Worg_Fur
https://www.wowhead.com/wotlk/item=42510/worg-fur#comments:id=507914
https://www.wowhead.com/wotlk/quest=13000/emergency-measures#comments:id=508870 and other comments on same page.

**Comment by Lumber-Jack-2** [comment]
added the item to the skin loot, condition is to have the quest active to see it

**Comment by Echinaceax** [comment]
Skinning loot 100% @Rushor ??
coz ive skinned 9 now and only got 

![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/19ae2794-da4c-48f5-94dc-7bda45c5c2a2)
![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/00dea677-ab91-4459-85c9-3c9ceea1d7a2)
![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/79424193-4582-4258-a304-69c5bbd634b9)
![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/879e5c59-9763-4f3f-b29a-bae486eec6b7)
![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/4f0dbcf6-a9d1-49ed-b75f-e9a67e3ff136)
![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/a559204f-c12a-4057-a1b8-ffa958bdf739)
![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/08eb6d42-ef5c-4d29-a0f1-cbe940f4bb90)
![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/2f130710-61a7-47e4-b2f7-2307a5c18aa6)
![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/406320c7-ac68-4d72-a109-332664d47665)





0 Quest item [Worg Furs](https://www.wow-mania.com/armory/?item=42510) on skinning

**Comment by Lumber-Jack-2** [comment]
if quest [Emergency Measures](https://www.wow-mania.com/armory/?quest=13000) is active it should be 100 percent on skinning now

**Comment by Echinaceax** [comment]
Still not, did check with 2 different chars

**Comment by Lumber-Jack-2** [comment]
okay skinning and quest combination does not work core side here - increased the dropchance to 100 percent instead which will be fine for both sides then

**Comment by Echinaceax** [comment]
Confirmed fixed as rushor states, always get the quest item until player has 6/6, then no longer drops.
