### ISSUE TITLE
[Quest] Cave Medicine – missing mushroom spawns

### ISSUE THREAD

**Issue by Greywolf59** [WoWManiaUK/Redemption#6144]
[Cave Medicine](https://www.wow-mania.com/armory/?quest=13055), as part of this quest you have to gather [Cave Mushroom item](https://www.wow-mania.com/armory/?item=42926) from [Cave Mushroom objects](https://www.wow-mania.com/armory/?object=192556).
There is total of six spawns of the objects and only in the deepest chamber of the cave. The quest itself needs 8. It would be weird if any gathering quest would make you wait for respawn/sent you for more items than there is maximum of.

Sources:
Nobody mentions this problem on wowhead comments, anywhere.
https://www.wowhead.com/wotlk/object=192556/cave-mushroom (count and map)
https://www.youtube.com/results?search_query=cave+medicine+wow&sp=CAI%253D → albeit not wotlk retail, just classic or other expansions, every video here shows mushrooms in other parts of the cave than just the last chamber.

**Comment by Lumber-Jack-2** [comment]
more spawns added, so ots more easy to complete the quest

**Comment by Echinaceax** [comment]
Confirmed fixed inm PTR 
![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/1222b548-f84b-4ca8-95c6-ab831f94c660)
