### ISSUE TITLE
[Quest] Jagged Shards – possibly wrong prerequisite, drop chance

### ISSUE THREAD

**Issue by Greywolf59** [WoWManiaUK/Redemption#6145]
[Jagged Shards](https://www.wow-mania.com/armory/?quest=13136).
This quest is started by getting [Jagged Shard](https://www.wow-mania.com/armory/?item=43242) drop from [Spiked Ghouls](https://www.wow-mania.com/armory/?npc=30597) during quest [Spill Their Blood](https://www.wow-mania.com/armory/?quest=13134). Problem is that quest cannot be accepted until the Spill Their Blood is handed in. That is very uncommon behaviour for this type of quest and I haven't found any evidence that the quest itself should be acceptable only after the player hands in STB quest.
It is also stated that once the first Sahrd drops, the drop chance is 100%, which is not the case on Mania.
https://www.wowhead.com/wotlk/item=43259/jagged-shard#comments:id=397544

https://wowpedia.fandom.com/wiki/Jagged_Shards#Notes: "A Jagged Shard will drop while killing ghouls during N [25-30] [Spill Their Blood](https://wowpedia.fandom.com/wiki/Spill_Their_Blood). Start the quest and keep killing."
https://www.wowhead.com/wotlk/quest=13136/jagged-shards#comments:id=828095 broken English but I would say it suggest likewise
"and you have get Spill Their Blood then the ghoul start drop

DROP IT WITH each time you kill one spike one"

**Comment by Lumber-Jack-2** [comment]
prevquest condition from 13136 is removed
