### ISSUE TITLE
[Quest] That's Abominable! – offered as hand-in

### ISSUE THREAD

**Issue by Greywolf59** [WoWManiaUK/Redemption#6147]
[That's Abominable!](https://www.wow-mania.com/armory/?quest=13264) is offered as hand-in. Aka Player does not need to accept it, does not have to have it in quest log, it jsut pops up completed and ready to hand-in at the quest giver after completing the previous quest [Poke and Prod](https://www.wow-mania.com/armory/?quest=13237).

**Comment by Maine1** [comment]
Confirmed Bugged 
![image](https://github.com/WoWManiaUK/Redemption/assets/122736582/da27707f-b4d9-40c6-b06e-40563bb7ea04)
this was ready to hand in without having to kill anything

**Comment by Lumber-Jack-2** [comment]
quest should work normal now, no auto complete anymore

**Comment by Echinaceax** [comment]
Confirmed fixed in PTR 

![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/4ce55fd5-3da1-4dd7-8e0c-6295a90e1806)
