### ISSUE TITLE
[NPC] Skybreaker Recon Fighter – dropping pilots to the ground

### ISSUE THREAD

**Issue by Greywolf59** [WoWManiaUK/Redemption#6148]
This is a minor bug but I always notice it when I go to The Valley of Fallen Heroes during quest [Raise the Barricades](https://www.wow-mania.com/armory/?quest=13306), so I have decided to finally mention it.
Basically there are untargettable uninteractable gnomes falling from the sky all around the zone where this quest happens. They stay standing on the ground. I am pretty sure its the pilots from [Skybreaker Recon Fighters](https://www.wow-mania.com/armory/?npc=32189)

Update: It might be worthwhile checking how many Figters are spawned. I have found only 4, though I probably missed some and there is 6 needed for [Blinding the Eyes in the Sky](https://www.wow-mania.com/armory/?quest=13313).

**Comment by Greywolf59** [comment]
Update 2: It seems the Fighters I shoot down all have gnomes in them and the gnome corpse stays in the air after destroying the craft. That probably means that the gnomes dropping from the sky are gnomes missing their unspawn Figthers.

**Comment by Lumber-Jack-2** [comment]
its actually because the gnomes die as soon as the machine is killed

it has 17 spawns in total for the flying machine, the website db is just outdated here

**Comment by Lumber-Jack-2** [comment]
a lot of planes were missing their fly option thats fixed now

**Comment by Echinaceax** [comment]
Corpse despawn still a little slow 
https://i.gyazo.com/654a794fcaa9cbd931233253cab4efa2.mp4

I remember another fix that had some npc "Falling to the ground" when you approached them.
It was render distance on that Big NPC you had to use the "hammer on" @Rushor remember ?

Edit, same issue as this was  https://github.com/WoWManiaUK/Redemption/issues/5824#issuecomment-1724164204

I killed the planes, and moved away and came back and dont see the little dudes/ falling to the ground, so i guess its fixed 
https://i.gyazo.com/aa57376af694b385b7d8a1923efe6c8c.mp4
