### ISSUE TITLE
[NPC] Converted Heroes - are linked on pull

### ISSUE THREAD

**Issue by Greywolf59** [WoWManiaUK/Redemption#6149]
[Scourge Banner Aura](https://www.wow-mania.com/armory/?spell=60023) used and provided by [Scourge Banner-Bearer](https://www.wow-mania.com/armory/?npc=31900) does not dissipate from [Converted Heroes](https://www.wow-mania.com/armory/?npc=32255) that already got it once, even after all Banner-Bearers in vicinity are killed.
Other issue is that the Heroes within one group are mostly linked. According to wowhead comments they are not linked and player can pull them one by one.

https://www.wowhead.com/wotlk/quest=13307/bloodspattered-banners#comments:id=464778:reply=363501

https://www.wowhead.com/wotlk/quest=13307/bloodspattered-banners#comments:id=768049
https://www.wowhead.com/wotlk/quest=13307/bloodspattered-banners#comments:id=575644

**Comment by Echinaceax** [comment]
I do see the issue you mean with [Scourge Banner Aura](https://www.wow-mania.com/armory/?spell=60023) not dissipating, but its not all off them, its onl;y some of them (which indicate there is an hidden [Scourge Banner-Bearer](https://www.wow-mania.com/armory/?npc=31900) somewhere within 50 yards 

See here https://i.gyazo.com/3e0bd8dfde46a9ddc377d874f94aa057.mp4
But here I found others in range i had to kill https://i.gyazo.com/96011da72c8030c90a4f0f9efddae78e.mp4

- [ ] Only issue here is that the [Converted Heroes](https://www.wow-mania.com/armory/?npc=32255) are linked on pull @Rushor

**Comment by Greywolf59** [comment]
It is slightly bit more complex.  I watched your video and the group that did not have the buff does not have it even when banner-bearer is around. I haven't cehcked all the NPCs but I do remember clearly that group did not ahve the buff as the only group from those I have checked. The rest still have it even after you kill(ed) all the banner-bearers. But I will check it again tomorrow.

**Comment by Greywolf59** [comment]
Okay my apologies, I came back and the aura is indeed okay. Either I have missed one banner-bearer last time or there was one under texture and got back up after a short dc of server yesterday.

**Comment by Lumber-Jack-2** [comment]
Converted Heroes react defensive now and should no longer aggro together

**Comment by Echinaceax** [comment]
Fixed in PTR 
https://i.gyazo.com/47192640b967550d7c375da68ca2ea6c.mp4
