### ISSUE TITLE
[Spell] Celestial Focus

### ISSUE THREAD

**Issue by axeluss** [WoWManiaUK/Redemption#615]
Hello,
It seems like the talent celestial focus is not working. My resto druid does not gain any effect from the "promised" 3% extra haste.

**Comment by fvicaria** [comment]
Please send me the link to the spell you are talking about. Use OepenWoW or our Armory.

**Comment by Rushor** [comment]
i think he means http://wotlk.openwow.com/spell=16924

**Comment by fvicaria** [comment]
@Rushor Thanks.

**Comment by Emcitementz** [comment]
It already works as it should. 
Haste = casting speed.
It says that the haste is increased for 3%, it doesn't update the haste itself, it stays at the same value but it updates your casting speed directly.
You can already see that when you put points for this talent, the casting speed decreases for all spells.
Therefore, there's nothing to change.
