### ISSUE TITLE
[Quest] Shatter the Shards – Broken Shard of Despair drop

### ISSUE THREAD

**Issue by Greywolf59** [WoWManiaUK/Redemption#6150]
During the quest [Shatter the Shards](https://www.wow-mania.com/armory/?quest=13328) I have looted [Broken Shard of Despair](https://www.wowhead.com/wotlk/item=44320/broken-shard-of-despair) from third [Cultist Shard Watcher](https://www.wow-mania.com/armory/?npc=32349) I have killed. The shards should be looted from destroyed Shard objects only.

https://wowpedia.fandom.com/wiki/Broken_Shard_of_Despair

**Comment by Lumber-Jack-2** [comment]
totally correct, confirmed by wowwiki, removed the item drop form the creature

**Comment by Echinaceax** [comment]
Fix confirmed
