### ISSUE TITLE
Quest - Torek's Assualt

### ISSUE THREAD

**Issue by VZ1003** [WoWManiaUK/Redemption#6152]
**Links:**https://www.wowhead.com/classic/quest=6544/toreks-assault

**What is Happening: I receive quest https://www.wow-mania.com/armory/?quest=6544 but nothing happen, Torek and his brethren just stand there, they dont go to Silverwing Outpost as the quest say

**What Should happen: : Torek and his brethren will move to Silverwing Outpost, when he in the main house of Outpost, we will slay some silverwing Sentinels and Warriors then Duriel Moonfire will appear and we must slay her.

**Comment by Lumber-Jack-2** [comment]
https://i.imgur.com/cQUrWZX.jpeg works, try again after next server restart
