### ISSUE TITLE
[Quest] The Boon of A'dal – Missing post-completion event

### ISSUE THREAD

**Issue by Greywolf59** [WoWManiaUK/Redemption#6153]
After handing in the quest [The Boon of A'dal](https://www.wow-mania.com/armory/?quest=13082) body of [Crusader Bridenbrad](https://www.wow-mania.com/armory/?npc=30562) simply disappears.
After the hand-in [A'dal](https://www.wow-mania.com/armory/?npc=30691) along with [K'uri](https://www.wow-mania.com/armory/?npc=30693) and [M'ori](https://www.wow-mania.com/armory/?npc=30692) should appear and interact with Bridenbrad and his [spirit](https://www.wow-mania.com/armory/?npc=30694).

https://wowpedia.fandom.com/wiki/The_Boon_of_A%27dal#Notes
After completing the quest, [A'dal](https://wowpedia.fandom.com/wiki/A%27dal) along with [K'uri](https://wowpedia.fandom.com/wiki/K%27uri) and [M'ori](https://wowpedia.fandom.com/wiki/M%27ori) appears and liberates the [Spirit of Bridenbrad](https://wowpedia.fandom.com/wiki/Spirit_of_Bridenbrad), so that he will not be raised as a mindless servant of the [Scourge](https://wowpedia.fandom.com/wiki/Scourge).

A'dal says: Fear not, young one, for this crusader shall not taste death.
A'dal says: In life, Bridenbrad was the bearer of great deeds. Now, in passing, he shall taste only paradise.
A'dal says: The light does not abandon its champions.

7y old video, at 3:15 you can see the shadows of naaru appear: https://www.youtube.com/watch?v=B6QeV1JWqCE&ab_channel=DazeWoW
1y ago (not classic) 1:45 onwards: https://www.youtube.com/watch?v=R-ylwLBFUso&ab_channel=TheChroniclesofAzeroth
classic, 2:32 onwards: https://www.youtube.com/watch?v=fVtQ3olGKN8&ab_channel=InGame-Torvalld

2008 comment: https://www.wowhead.com/wotlk/quest=13082/the-boon-of-adal#comments:id=392177
2008 comment: https://www.wowhead.com/wotlk/quest=13082/the-boon-of-adal#comments:id=510209

**Comment by Lumber-Jack-2** [comment]
added the endevent

**Comment by Echinaceax** [comment]
confirmed fixed in PTR 
https://i.gyazo.com/d043ed53bbe5ac08e10cf12df632de68.mp4
