### ISSUE TITLE
[Quest] Where Dragons Fell – wrong prerequisite

### ISSUE THREAD

**Issue by Greywolf59** [WoWManiaUK/Redemption#6154]
[Where Dragons Fell](https://www.wow-mania.com/armory/?quest=13359) currently requires player to complete and hand-in [Cradle of the Frostbrood](https://www.wow-mania.com/armory/?quest=13349), a quest that takes player into the same zone where this quest happens. Same goes for Alliance side most likely.

Requirement for Where Dragons Fell should be only having [Futility](https://www.wow-mania.com/armory/?quest=13348) handed-in.

Logical Reason: Cradle of the Frostbrood sends player to Sindragosa's Fall where also Where Dragons Fell is happening. After player completes Cradle of the Frostbrood and flies back to airship, it seems as abrupt end of the questline. Player can easily miss the ghost of Matthias Lehner in Sindragosa's Fall or never think about returning there, leaving this questchain incomplete.

Sources:
https://wowpedia.fandom.com/wiki/Futility#Progression_2
https://wowpedia.fandom.com/wiki/Where_Dragons_Fell#Notes
https://www.wowhead.com/wotlk/quest=13359/where-dragons-fell#comments:id=449010
https://www.wowhead.com/wotlk/quest=13359/where-dragons-fell#comments:id=974559 (Here Cradle of the Frostbrood is not directly between Futility and Where Dragons Fell, it is positioned more like a sidequest)

**Comment by Lumber-Jack-2** [comment]
[Futility](https://www.wow-mania.com/armory/?quest=13348) is the prevquest now

**Comment by Echinaceax** [comment]
This is incorrect and we havent confirmed the report yet @Rushor 

It clearly states here what is required 
We dont go on "Logical Reason" we go off facts

![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/24d61d53-5b72-413d-bae9-88dab6867167)

Series 

![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/21e1e267-869e-4c40-87de-06a9f5f8372f)

Even shows on the link Greywolf posted 

![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/1b5cf93d-49be-4b06-86d8-876172ad16be)

**Comment by Lumber-Jack-2** [comment]
well in wowwiki it says:
https://i.imgur.com/qkiYPhr.png

also: 
[Cradle of the Frostbrood](https://www.wow-mania.com/armory/?quest=13349) and [Sindragosas Sturz](https://www.wow-mania.com/armory/?quest=13397) are only marked as optional quests in the screenshot above

seems correct to me actually
