### ISSUE TITLE
Allliance Flightmaster in Moonglade not present

### ISSUE THREAD

**Issue by Dopsche** [WoWManiaUK/Redemption#6155]
Links:https://www.wowhead.com/wotlk/npc=10897/sindrayl

What is Happening: Not 100% sure what happened here. The flight master may have been killed or was never present (first char). Whatever the case she is not in her spot and don't respond even with 20 mins waiting time

What Should happen: From what to read on the Internet, the respawn time should be 5 minutes. So the Flight master should have respawned by now and offer her services to Alliance toons

**Comment by Echinaceax** [comment]
correct, that NPC gets killed a lot 
You have to wait from respaws ...usually 10-12 mins 

the respawn timer of 10mins start after the despawn of the corpse

![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/db8d7e83-d013-429f-905f-f12c13549012)
![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/b6b4bab4-42c2-402d-8423-20bb815c819e)
![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/5d295db5-671d-4aec-8965-57ab8f59f53c)
![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/db903e00-fe6f-48d7-ae17-a90e1b472d76)

Note: 
Flight Master are always 10-12 mins https://i.gyazo.com/9c2a758b035910cb5e2386f282b11a58.mp4
Vendors are 5 mins

**Comment by Dopsche** [comment]
Thanks for checking and I can confirm. Apologies for opening a ticket.
