### ISSUE TITLE
[Quest] Proof of Deed - Unable to speak to Curator Thorius

### ISSUE THREAD

**Issue by stealer0517** [WoWManiaUK/Redemption#6156]
https://www.wow-mania.com/armory/?quest=3182 

When you get to Iron Forge you'll find Curator Thorius staring into a corner, and he refuses to speak to you.
There's no Question mark over his head, hovering your mouse over him doesn't give any special icon, and pressing the interact key does nothing. 

When you get to Iron Forge you should see him pacing around The Library's hall, and obviously be able to turn in the quest.

I'm not sure if this is a bug related to Winter Veil since the tree is nearby, a case of seasonal depression, or if he's always depressed like this. But someone should probably double check on him and make sure he's feeling alright. 

![Curator Thorius](https://github.com/WoWManiaUK/Redemption/assets/6968045/3ea4ddd6-7332-4946-90bc-fd971029e1d9)

**Comment by Echinaceax** [comment]
Thanks for reporting @stealer0517 

Testing soon

Start quest drop npc  https://www.wow-mania.com/armory/?npc=5833
Start quest item https://www.wow-mania.com/armory/?item=10000
The Horn of the Beast https://www.wow-mania.com/armory/?quest=3181
Proof of Deed https://www.wow-mania.com/armory/?quest=3182

**Comment by Echinaceax** [comment]
No issue found 


![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/2f53cdd2-8220-4e7b-a67a-243ad0f02642)
![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/436924e8-6617-470b-8e78-5d42f8a0d03b)
![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/318466e4-f1ad-474f-b150-3328673e9049)
![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/311db3c4-e40b-43fc-8c54-1e2b030a2e3d)

**Comment by stealer0517** [comment]
Was this done on a test server or on the production "Redemption" server? 
I just double checked and he's still not wanting to talk to me.

**Comment by Echinaceax** [comment]
> Was this done on a test server or on the production "Redemption" server? I just double checked and he's still not wanting to talk to me.

This was done on the Test realm, But Redemption is a copy of The test realm, so what bugs/fixes are on Red they are on test realm and vice versa 

personally, i would make an ingame ticket and have the GMs check if you meet the requirements
