### ISSUE TITLE
Val’Anyr Hammer of Ancient kings

### ISSUE THREAD

**Issue by Leetpoon** [WoWManiaUK/Redemption#6158]
**Links:**

**What is Happening:**
The weapon won’t proc blessing of the ancient kings

**What Should happen:**
Make it proc plz

**Comment by Maine1** [comment]
This item does proc. I personally use it on my paladin in raids every week @Leetpoon

**Comment by Leetpoon** [comment]
It won’t proc for me, I can show you if you like, I spammed 10 nourishes in a row and it didn’t proc once

**Comment by Maine1** [comment]
it doesn't proc for you solo

**Comment by Maine1** [comment]
it procs from cast on others as "Helpful healing"
