### ISSUE TITLE
Timbermaw hold characters cannot be talked to

### ISSUE THREAD

**Issue by brehven** [WoWManiaUK/Redemption#6159]
**Links:**

**What is Happening:**
After getting friendly rep with Timbermaw Hold, the NPC's cannot be talked to.  A sword icon appears which initiates combat instead.

**What Should happen:**
Icons for different trade NPC's for special items, additional quests.

**Comment by Echinaceax** [comment]
Check your rep tab @brehven and uncheck the "at war" 

https://i.gyazo.com/f981f444b854eaa8c3f15aa44b483327.mp4

![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/7c9e4f79-b37d-47d2-91a5-df25e0caf669)
