### ISSUE TITLE
[NPC] Griftah <Amazing Amulets> Chat text

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Redemption#6160]
**Links:**
NPC https://www.wow-mania.com/armory/?npc=19227

![text error](https://github.com/WoWManiaUK/Redemption/assets/39439201/a5cfd039-efb5-4f33-93cc-85a9288b54e9)

**What is Happening:**
Text says "$G man:sweetheart;!" - its shouldnt say $G man: ;

**What Should happen:**
Griftah says: Ya look lovesick. Special someone be gettin' ya down, eh? No worries, no worries. Ya get this medallion from me, ya wear it when ya see 'em, and they be all over ya, sweetheart!

he has 51 quotes: i only noticed this one, but maybe check all is fine 
https://www.wowhead.com/wotlk/npc=19227/griftah

**Comment by Lumber-Jack-2** [comment]
should be fixed now, will take the gender

**Comment by Echinaceax** [comment]
Quotes fixed in PTR 
![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/180c698f-4dfd-472c-80bc-81d9c1caaecd)
