### ISSUE TITLE
Quest - Ample Inspiration, Not Available For Pick Up

### ISSUE THREAD

**Issue by Bobthereaper** [WoWManiaUK/Redemption#6164]
**Links:**
https://www.wowhead.com/wotlk/quest=12828/ample-inspiration
https://github.com/WoWManiaUK/Redemption/issues/6141
https://github.com/WoWManiaUK/Redemption/issues/6140
https://github.com/WoWManiaUK/Redemption/issues/6139

**What is Happening:**
Quest - Ample Inspiration
K3, Storm Peaks
Quest Giver - Ricket

She is not giving the quest, I have completed quests "Expression of Gratitude" and "Reclaimed Rations" which from searching Wowhead are the prerequisite quests to get it. I believe some of the changes made during the resolution of issues #6141/6140/6139 (Linked Above) might have caused issue with this quest being given out by Ricket after completing the required prerequisite quests. 

**What Should happen:**
Ricket offers you the quest "Ample Inspiration" after completing quests "Expression of Gratitude" and "Reclaimed Rations"

**Comment by Lumber-Jack-2** [comment]
you need quest 12827 and 12836 rewarded in order to take it, and thats was working on ptr, will test with a fresh toon now

**Comment by WhitephoenixTheBunny** [comment]
@Rushor I am going to test this, but would this https://www.wow-mania.com/armory/?quest=12821#conditionsource-quest-accept create a loop where you can't get the quest?
![image](https://github.com/WoWManiaUK/Redemption/assets/31921098/adada02d-e2e4-4208-92fa-0130dfa7a309)

**Comment by Echinaceax** [comment]
the fix could have broken it https://github.com/WoWManiaUK/Redemption/issues/6139 ?

**Comment by Maine1** [comment]
Tested these and you can do the 12827 and 12836 and still no Quest - Ample Inspiration
Also you cannot take Quest - Opening the Backdoor

**Comment by Lumber-Jack-2** [comment]
this had to be reworked, conditions do not work for such quests.

Changed it to be like that:
First player must do quest 12827, then must do quest 12836, and after that must do quest: 12828

**Comment by Lumber-Jack-2** [comment]
and yes apart from that just tested with fresh toon:
-- Opening the Backdoor 12821

is available after all those quests have been rewarded:
-- Ample Inspiration 12828
-- A Delicate Touch 12820
-- Bitter Departure 12832

https://i.imgur.com/OfGllqy.jpeg

**Comment by Maine1** [comment]
![image](https://github.com/WoWManiaUK/Redemption/assets/122736582/1c4cdad7-074f-412a-a3e1-0211e5b88f85)
![image](https://github.com/WoWManiaUK/Redemption/assets/122736582/d94cfc9b-b6a3-4724-b9b6-8c134d7fe07b)
Quest is now available after completion of Reclaimed Rations and Expression of gratitude
