### ISSUE TITLE
[NPC] Jean Pierre Poulain - Flight path issue 

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Redemption#6165]
**Links:**
Npc Jean Pierre Poulain https://www.wow-mania.com/armory/?npc=34244

**GMs asked me to test this coz they are getting tickets about this regularly** 

**What is Happening:**
Stuck on fightpath mount. 
1, when players have saved there Hearthstones at the innkeepers in Dalaran at low level
If they use the NPC **Jean Pierre Poulain <Argent Tournament Valiant>** at dalaran they are restricted, so get ported back to Dalaran, you cant leave Dalaran until after level 68

in my test i used a level 23, and i was ported to stormwind and got stuck on the flight path until eventually i died due to fatigue 😄 
my repro video https://i.gyazo.com/3ec22698d5af4a192200ac1fb11b3744.mp4

**What Should happen:**

- [ ] Set requirements - 68+ only can click on the NPC to take a ride.

![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/89ee97fd-657c-468a-948f-0cce26e62183)

**Comment by Lumber-Jack-2** [comment]
perfect, will add that!

**Comment by Echinaceax** [comment]
Fix confirmed in PTR at level 66 

![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/a15576e3-3c4b-467c-8377-9c46342d2be8)

Checked at 68

![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/932d21aa-2588-4039-957c-9b80f8e40003)
