### ISSUE TITLE
[Item] 2P T10 Resto Druid bonus: wrong calculations

### ISSUE THREAD

**Issue by JohnBrinkle** [WoWManiaUK/Redemption#6166]
**Links:**
Set: T10 Lasherweave Garb
https://www.wowhead.com/wotlk/item-set=887/lasherweave-garb#comments

**What is Happening:**
The P2 Bonus states that 
[The healing granted by your Wild Growth spell reduces 30% less over time.]
(https://www.wowhead.com/wotlk/spell=70658/item-druid-t10-restoration-2p-bonus)

There is an example in the comments, where the heals are displayed and how the degrade over time.
I made a table view over those:
![grafik](https://github.com/WoWManiaUK/Redemption/assets/46407976/9feea446-eb21-4ba6-a136-37a2bf79619b)

The first block is without P2 T10, the second with it.

First column are the stated heals, 
second the % of that heal relative to the first one being 100%,
third is the amount of heal less than the previous
fourth column displays the % that is taken from the previous heal

As you can see, the normal amount taken from the initial heal is around 4.4 or 4.5 %.
With the P2 bonus it is reduces 30% to 3 or 3.2%.

And now, what is happening on Mania-Server:
![grafik](https://github.com/WoWManiaUK/Redemption/assets/46407976/2e6af4cf-5f98-41ba-8ba4-42e3115851ee)
This is made with nearly the same initial heal as in the example from wowhead, 
and the +heal is 2263 (without P2) and 2268 (with P2) for comparison.

Not only is the amount reduction without P2 not 4.5% but nearly 10%,
but with the P2 bonus, it is suddenly not even linear anymore.
It only seem to work, because the initial amount is somehow just more?

Note, that the full amount of heal (sum below the heals) is lower than it is in the example from wowhead.

**What Should happen:**
Wild Groth: The % amount that is taken from the initial heal should be lower, not 10% but more like 4.5%.
P2 bonus: that % reduction should get lowered to around 3.2%.
The % reduction in every step should be linear.
The initial heal is currently higher, it should stay the same as without P2 bonus.

**Comment by Maine1** [comment]
@JohnBrinkle can you find any links that confirm these number that isn't a 3.4.0 (Classic) link. They changed alot of stuff over on classic and this information would be helpful for this report
