### ISSUE TITLE
[Dungeon][Boss] PoS – Garfrost missing Chilling Wave

### ISSUE THREAD

**Issue by Greywolf59** [WoWManiaUK/Redemption#6167]
[Garfrost](https://www.wow-mania.com/armory/?npc=36494) should be using [Chilling Wave](https://www.wow-mania.com/armory/?spell=70333) ([68778](https://www.wow-mania.com/armory/?spell=68778)) after he forges himself new weapon in the first transition.
He stops using it after second transition and uses Deep Freez instead (correct).
https://wowpedia.fandom.com/wiki/Forgemaster_Garfrost (Abilities and Strategy)
https://www.tentonhammer.com/guides/guide-to-the-pit-of-saron (10.12.2009)
1:12-1:15 https://www.youtube.com/watch?v=6RMVe0EFcUc&ab_channel=RawxorTank (14y old video)
Tested today at Naxx, normal version. The spell is missing in both versions to my knowledge.
![7acd2915712055c622bd5ae3b3379a15](https://github.com/WoWManiaUK/Redemption/assets/41387450/62a6d332-e073-4167-96d8-96237634caac)

**Comment by Lumber-Jack-2** [comment]
issue moved tp private github - it takes more time to inspect. The issue will be handled there, thanks for the report!
