### ISSUE TITLE
[Dungeon][NPC] PoS – Wrathbone Coldwraith missing Freezing Circle

### ISSUE THREAD

**Issue by Greywolf59** [WoWManiaUK/Redemption#6168]
[Wrathbone Coldwraiths](https://www.wow-mania.com/armory/?npc=36842) in Pit of Saron are not using [Freezing Circle](https://www.wow-mania.com/armory/?spell=70276) ([69574](https://www.wow-mania.com/armory/?spell=69574))

**Comment by Lumber-Jack-2** [comment]
will need to check his SAI :)

**Comment by Maine1** [comment]
This has been confirmed by testing. Freezing Circle is not being used by these mobs. Only frostbolts are being used at present

**Comment by Lumber-Jack-2** [comment]
try now

**Comment by Maine1** [comment]
NPC - Wrathbone Coldwraith is now casting Freezing Circle
