### ISSUE TITLE
[Dungeon] PoS – Missing event on entry

### ISSUE THREAD

**Issue by Greywolf59** [WoWManiaUK/Redemption#6169]
Once the player enter PoS there should be no NPC, Sylvanas/Jaina and the crew will come out of portal only after player does a few steps into the dungeon.
Currently Jaina/Sylvanas and two named NPCs are already there. The rest of the crew never spawns.
Then the event, interaction between assaulting friendly party and Tyrannus should occur. Nothing as such happens.

IDs of not spawning NPC:
Horde Coliseum Champions: [37588](https://www.wow-mania.com/armory/?npc=37588), [37584](https://www.wow-mania.com/armory/?npc=37584), [37587](https://www.wow-mania.com/armory/?npc=37587)
Alliance Coliseum Champions: [37496](https://www.wow-mania.com/armory/?npc=37496), [37498](https://www.wow-mania.com/armory/?npc=37498), [37497](https://www.wow-mania.com/armory/?npc=37497)

Videos:
14y old Horde version; 0:15-1:23 https://www.youtube.com/watch?v=5E_E-w3KxxY&ab_channel=Rill
14y old Alliance version; 0:14-1:23 https://www.youtube.com/watch?v=dmam_1SvakY&t=8s&ab_channel=Rill
Video from classic: 0:36 - 1:24 (chatbox and noting to have to go further on) https://www.youtube.com/watch?v=NsbILjGXrak&ab_channel=Harldan

Worth to note that as Alliance player in normal I have seen [Gorkun Ironskull](https://www.wow-mania.com/armory/?npc=37592) standing near the entrance of PoS instead of Alli NPC [Martin Victus](https://www.wow-mania.com/armory/?npc=37591)

**Comment by Lumber-Jack-2** [comment]
issue moved tp private github - it takes more time to inspect. The issue will be handled there, thanks for the report!
