### ISSUE TITLE
[Dungeon] PoS – Scourgelord Tyrannus fight events incomplete

### ISSUE THREAD

**Issue by Greywolf59** [WoWManiaUK/Redemption#6170]
1. Starting the fight
As of now we have Tyrannus doing his replicas when players come near and that is all.
14y old Horde video; 6:30 https://www.youtube.com/watch?v=5E_E-w3KxxY&ab_channel=Rill
14y old Alli video; 7:10 https://www.youtube.com/watch?v=dmam_1SvakY&t=8s&ab_channel=Rill (chatbox, lots of npcs)

Video from Classic with great commentary: https://www.youtube.com/watch?v=NsbILjGXrak&ab_channel=Harldan
14:20-15:20: start event + explanation about freed slaves

Missing friendly NPCs:
Freed Horde Slave [37577](https://www.wow-mania.com/armory/?npc=37577), [37578](https://www.wow-mania.com/armory/?npc=37578), [37579](https://www.wow-mania.com/armory/?npc=37579)
Freed Alliance Slave [37572](https://www.wow-mania.com/armory/?npc=37572), [37575](https://www.wow-mania.com/armory/?npc=37575), [37576](https://www.wow-mania.com/armory/?npc=37576)

2. During the fight
The friendly NPCs that should have come out of the tunnel should be fighting undead to stop them from getting to the party. This battle is not occuring at all.
Friendly line of defense can be breached by the undead it is suggested that the strength of the defense is determined by nubmer of freed slaves.
It seems the undead are the same as those that players meet on their way across the tunnel.

https://wowpedia.fandom.com/wiki/Scourgelord_Tyrannus#Adds_From_Behind
Video from Classic with great commentary: https://www.youtube.com/watch?v=NsbILjGXrak&ab_channel=Harldan
14:20-15:20: start event + explanation about freed slaves
15:45-15:55 and elsewhere throughout the video: the battle at the tunnel in HD
14y old Horde video; 7:27-7:59 https://www.youtube.com/watch?v=5E_E-w3KxxY&ab_channel=Rill
14y old Alli video; 8:12-8:16 https://www.youtube.com/watch?v=dmam_1SvakY&t=8s&ab_channel=Rill

3. After the boss dies
Afer the boss is dead another event should occur, where [Sindragosa](https://www.wow-mania.com/armory/?npc=37755) comes and kills most of the friendlies by [Frostbomb](https://www.wow-mania.com/armory/?spell=70521). Players are saved by Jaina/Sylvanas.

https://wowpedia.fandom.com/wiki/Gorkun_Ironskull#Quotes
https://wowpedia.fandom.com/wiki/Martin_Victus?so=search#Quotes
https://wowpedia.fandom.com/wiki/Sindragosa?so=search#Wrath_of_the_Lich_King (2nd paragraph)

 Classic video;17:25 onwards: https://www.youtube.com/watch?v=NsbILjGXrak&ab_channel=Harldan
14y old Horde video; 8:20 onwards: https://www.youtube.com/watch?v=5E_E-w3KxxY&ab_channel=Rill
14y old Alli video; 8:40 onwards: https://www.youtube.com/watch?v=dmam_1SvakY&t=8s&ab_channel=Rill

**Comment by Lumber-Jack-2** [comment]
issue moved tp private github - it takes more time to inspect. The issue will be handled there, thanks for the report!
