### ISSUE TITLE
[Raid] Eye of Eternity – Malygos bugs

### ISSUE THREAD

**Issue by Greywolf59** [WoWManiaUK/Redemption#6171]
There is decent number of bugs and discrepancies during this encounter. Observed in 10m on Naxx realm.

**Number 1: [Vortex](https://www.wow-mania.com/armory/?spell=56105) behaviour**

How it should be: Vortex should pull the players up, swirling them around the arena and damage them in ticks. After the vortex is done, the players should be returned to the position near the center and dropped down for fall damage.

How it is: Vortex spreads the players around but sometimes does not lift them high enough for the falling damage to take place, at least graphically, some players were bascially on/in the ground during the vortex. Vortex does not return the players to the central position. Player toons are not swirling around (to my knowledge).

https://wowwiki-archive.fandom.com/wiki/Malygos_(tactics)#Phase_1 states:
Vortex: Malygos takes off from the ground and spins up a whirling vortex of Arcane energy, tossing the raid around and dealing 2,000 Arcane damage every second for 10 seconds. **When Vortex ends, everyone will be dropped around the center of the platform and take up to 10% of their maximum health in falling damage.**

15y old video; 0:50-1:08; 2:00-2:15 https://www.youtube.com/watch?v=xYqJ-8FiXCI&ab_channel=Ciderhelm
15y old video 3:08 https://www.youtube.com/watch?v=x_PunHW9Kuw&t=189s&ab_channel=TheYogscast

**Number 2: Phase 1 to Phase 2 transition loss of uptime.**

How it should be: Malygos should stay a while in the center, flying above the raid still in reach for some ranged attacks.

How it is: Malygos immediately fly-walks to the edge and out of reach, making raid lose improtant uptime on boss.

https://wowwiki-archive.fandom.com/wiki/Malygos_(tactics)#Phase_One notes:
Note: Once Malygos reaches 50%, he will slowly take off, however he remains targetable throughout, so burn him as best you can while he is taking off, and continue to hit him with instants once he's in the air.

15y old video; 3:45-4:15 https://www.youtube.com/watch?v=xYqJ-8FiXCI&ab_channel=Ciderhelm

**Number 3: Players on flying discs affected by Deep Breath**

How it should be: Players flying on the discs and chasing after scions should not be affected by Malygos' Deep breath ability.

How it is: Players on the discs take full damage from the breath (5k ticks). i can't fidn the link to this ability

https://wowwiki-archive.fandom.com/wiki/Malygos_(tactics)#Phase_2 states:
Deep Breath: Deals 5,000 Arcane damage per second to the whole raid for 5 seconds. Cast at regular intervals. A warning, 'Malygos takes a deep breath,' is given before Malygos uses this. This ability does not effect anyone flying on a disc.

https://wowwiki-archive.fandom.com/wiki/Malygos_(tactics)#Phase_Two states:
As the NPCs die, they drop disks which players can mount. Melee should take disks to DPS Scions. While mounted on a disk, players do not take damage from Malygos.

No video taken from melee PoV found.

**Number 4: [Nexus Lords](https://www.wow-mania.com/armory/?npc=30245) leave their discs on spot where they landed.**

How it should be: They should be on their [Hover discs](https://www.wow-mania.com/armory/?npc=30234) at all times until they die.

How it is: They leave the disc where they get to ground and run to the raid. They become clickable after the Lord dies.

15y old video; 4:15-5:30 https://www.youtube.com/watch?v=xYqJ-8FiXCI&ab_channel=Ciderhelm

**Number 5: [Scions of Eternity](https://www.wow-mania.com/armory/?npc=30249) leave their discs in the air/unusable**

How it should be: After the Scion dies, this disc should drop to the ground and be available for other melees to hop on.

How it is: When Scion dies the disc stops and stays in the air. It might not even be clickable, not sure about this now. This leads to loss of dps as no more than two melee can engage the adds.

15y old video; 4:25-5:00 voice explanaiton https://www.youtube.com/watch?v=xYqJ-8FiXCI&ab_channel=Ciderhelm

https://wowwiki-archive.fandom.com/wiki/Malygos_(tactics)#Scion_of_Eternity states:
Scions of Eternity will spawn at the beginning of phase 2. They fly upon floating discs, which puts them out of the melee range of anyone on the platform. They have no aggro table and will periodically cast Arcane Barrage on random targets. **When one dies, it will drop its disc to the ground, allowing melee classes to fly up and engage them.**

**Number 6: Power Overload apparently does not have any knockback effect.**

How it should be: If the new Power Overload, aka the pink anti-magic bubble that raids hides in to avoid full Deep Breath damage, spawns close to the players, those players get knocked back.

How it is: In this run I have not noticed any knockback whatsoever and I fail to remember it happening ever at all. Needs to be confirmed.

https://wowwiki-archive.fandom.com/wiki/Malygos_(tactics)#Phase_2 states:
Power Overload: Purple anti-magic zones will periodically appear on the platform, reducing all magic damage taken while standing inside by 50%. These zones will shrink as they absorb more and more damage, forcing you to move to a newer one. **They will knock back players nearby when they spawn.**

15y old video; 5:50-6:10 https://www.youtube.com/watch?v=xYqJ-8FiXCI&ab_channel=Ciderhelm

**Number 7: [Revivify](https://www.wow-mania.com/armory/?spell=57090) does not award combo points**

How it should be: using Revivify while on [Wyrmrest Skytalon](https://www.wow-mania.com/armory/?npc=30161) should award a combo point for each use.

How it is: Revivify does not award any combo points.

The spell itself states it should award combo point.

https://wowwiki-archive.fandom.com/wiki/Malygos_(tactics)#Phase_3 states:
Revivify:
A HoT that lasts for 10 seconds healing 500 per second and **awarding 1 combo point at the cost of 10 energy.** This can stack up to 5 times. Each drake has its own stack, so if two drakes are stacking this ability on a single drake, that drake will have two separate stacks.

15y old video; 7:40-8:00 commentary https://www.youtube.com/watch?v=xYqJ-8FiXCI&ab_channel=Ciderhelm

**Comment by Lumber-Jack-2** [comment]
Will Add a new label for such huge reworks to be inspected in future, will reopen the issue then. No worry :)
