### ISSUE TITLE
[ NPC/Event] Luna Festival Elder's - Missing text and locations of elder's info

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Redemption#6173]
**Links:**
https://www.wowhead.com/search?q=elders+of

![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/08663919-e9dc-47c0-a1e1-392006499f13)

as part of the events checks, i saw that a few had missing text, so i decided to check them all. 
there were too many to ignore 😄  

- [x] Elders of Kalimdor - all fine 
- [x] Elders of Eastern Kingdoms - all fine
- [x] Elders of Northrend
- [x] Elders of the Dungeons
- [x] Elders of the Alliance - all fine 
- [x] Elders of the Horde
---

**What is Happening:**
- [x] Elder Skywarden - Missing location clues of other Elder's
- [x] Bluewolf the Elder - Missing quest text 
- [x] Nurgen the Elder - missing quest text 
- [x] Ohanzee the Elder - missing quest text
- [x] Chogan'gada the Elder - missing quest text
- [x] Igasho the Elder - missing quest text
- [x] Kilias the Elder - missing quest text
- [x] Yurauk the Elder - missing quest text
- [x] Elder Darkthorn - missing where is elder Ironbank, elder Wheathoof location info
- [x] Elder Darkcore - double screen gossip when clicking on "where is elder Darkhorn"

**What Should happen:**
All elder's should have quest text and "where is xyz location elder

**Comment by Lumber-Jack-2** [comment]
added all quest texts, for event: .event start 7

all else i will fix later

**Comment by Lumber-Jack-2** [comment]
need cache clear again ofc

**Comment by Maine1** [comment]
All checked. Thanks for fix @Rushor
