### ISSUE TITLE
[Spell/Enchant] Rune of Lichbane only dealing 2% weapon dmg to undead targets instead of 4%

### ISSUE THREAD

**Issue by YggdrasilWotLK** [WoWManiaUK/Redemption#6174]
**Links:** https://wow-mania.com/armory/?spell=56903

**What is Happening:**
The Rune of Lichbane's on-hit effetc "Lichflame"deals the same dmg to all targets. 

**What Should happen:**
"Lichflame" should deal 2% weapon dmg to non-undead targets and 4% weapon dmg (ie. 2% extra dmg) to undead targets as fire dmg. The double dmg on undead targets is missing.

**Comment by Maine1** [comment]
![image](https://github.com/WoWManiaUK/Redemption/assets/122736582/fb6fa61a-2e9f-43c7-9d93-3a4062fef4b3)
![image](https://github.com/WoWManiaUK/Redemption/assets/122736582/563c7178-4836-4b8f-bced-9ffd2d945a12)
![image](https://github.com/WoWManiaUK/Redemption/assets/122736582/9168754c-cc08-4281-8918-5dbf13ef6a22)
![image](https://github.com/WoWManiaUK/Redemption/assets/122736582/e0437c34-df70-4e48-b374-b76a45212a1b)

Ok above are 4 screenshots. First 2 are on humanoids with Lichflame damage doing 10 & 11 damage. 
Second 2 are on different undead targets. Still doing 10 & 11 Lichflame damage

@Rushor 

For information 

![image](https://github.com/WoWManiaUK/Redemption/assets/122736582/08e19fb7-2363-4eec-86ba-09ada11c9663)

This is the bit that is bugged
![image](https://github.com/WoWManiaUK/Redemption/assets/122736582/908c6f79-43fb-4be7-a696-eb9fd6003c88)

**Comment by Lumber-Jack-2** [comment]
dmg against undead should be increased now

**Comment by Echinaceax** [comment]
fixed in PTR 

human 
![human](https://github.com/WoWManiaUK/Redemption/assets/39439201/23784984-2786-4d4c-80d6-0cc44bdc817c)

undead
![undead](https://github.com/WoWManiaUK/Redemption/assets/39439201/90c29731-e47e-4bf1-a598-240cc5f69864)
