### ISSUE TITLE
[Quest] An Alternative Alternative – missing completion event

### ISSUE THREAD

**Issue by Greywolf59** [WoWManiaUK/Redemption#6176]
Completing [An Alternative Alternative](https://www.wow-mania.com/armory/?quest=9473) does not trigger any event.
After completing this quest, [Daedal](https://www.wow-mania.com/armory/?npc=17215) should administer the cure to the [Injured Night Elf Priestess](https://www.wow-mania.com/armory/?npc=17117) and she should react to it.

https://wowpedia.fandom.com/wiki/An_Alternative_Alternative#Notes
2007 comment https://www.wowhead.com/tbc/quest=9473/an-alternative-alternative#comments:id=42834 (comments mentions the need to wait, most likely due to the event playing out)
TBC Classic video, 3:18: https://www.youtube.com/watch?v=C064j4LQshw&ab_channel=StormblazeGaming (incomplete)
Retail 3:05: https://www.youtube.com/watch?v=Ph7X8W3xPO4&ab_channel=MicGamingGuides (full event)

**Comment by Lumber-Jack-2** [comment]
event added

**Comment by Echinaceax** [comment]
Fixed in PTR https://i.gyazo.com/349a4f096cf32690561c23d5c6a5d1bf.mp4
