### ISSUE TITLE
[Spell/Enchant] Hyperspeed Acceleration double-trigger

### ISSUE THREAD

**Issue by Mlaniel** [WoWManiaUK/Redemption#6178]
**Links:**
![grafik](https://github.com/WoWManiaUK/Redemption/assets/22893229/c4a03a71-c7ee-4463-821e-7d22d0808fa1)

Enchant: https://www.wowhead.com/wotlk/spell=54999/hyperspeed-accelerators
Buff: https://www.wowhead.com/wotlk/spell=54758/hyperspeed-acceleration

**What is Happening:**
If you activate your engineering gloves really fast, it may happen that it's activating twice in quick succession.
Maybe it is caused by having a macro with 2x engineering gloves in it, as a human being cannot press a key twice in 0.06 seconds.

Further testing required (but I don't have an engineer character, yet)

**What Should happen:**
After the first trigger it should be on cooldown and not activate again.

I'm concerned that this may happen with other spells and enchants, which I haven't noticed, yet.

**Comment by Mlaniel** [comment]
Possibly related to this #2960

**Comment by Lumber-Jack-2** [comment]
If 2 of them are active you have 2 auras visually active then?

**Comment by Mlaniel** [comment]
As both buffs have the same ID, it simply refreshes the duration, as can be seen in this visual representation of the log.
![grafik](https://github.com/WoWManiaUK/Redemption/assets/22893229/f1a90edb-e334-4b66-9ee3-7787aaacd581)

**Comment by Echinaceax** [comment]
@Rushor 
while checking this, maybe need to check the list that Keader asked for, sames aplayer did report more after the firsr fix  https://github.com/WoWManiaUK/Redemption/issues/2960#issuecomment-452584806

**Comment by Maine1** [comment]
@Rushor after looking into this. On our normal addons using Skada. It shows the correct amount being used. Seems this program is picking up multiple but we can't change it based on 3rd party programs.

**Comment by Mlaniel** [comment]
> Seems this program is picking up multiple but we can't change it based on 3rd party programs.

Skada being the 3rd party program here. The logs I mentioned are the in-game, internal, logging. The 3rd party program is only a visual representation of **client logging**
