### ISSUE TITLE
About "A Pawn on the Eternal Board" quest

### ISSUE THREAD

**Issue by Arkaci** [WoWManiaUK/Redemption#6179]
**What is Happening:**

While doing the quest, npcs suddenly disappear. GM Psygoa watched me while doing the quest and he said "report a bug on Github". Can you check the quest please ?

Best regards.

**Comment by Echinaceax** [comment]
I see you closed your report after you saw mine, we always try and find an old report before making a new one
Thanks for reporting 
https://github.com/WoWManiaUK/Redemption/issues/3207#issuecomment-1928274265
