### ISSUE TITLE
[Crafting] Goblin mortar - spell 12716

### ISSUE THREAD

**Issue by Drogger** [WoWManiaUK/Redemption#618]
http://www.wowhead.com/spell=12716/goblin-mortar is not being offered to some players with http://www.wowhead.com/spell=20222/goblin-engineer as a trainer taught plan.

**Comment by fvicaria** [comment]
It will be available from Nixx Sprocketspring .

http://www.wowhead.com/npc=98838/nixx-sprocketspring
