### ISSUE TITLE
[Spell] Eyes of the Beast - Affected by multiple CC spells

### ISSUE THREAD

**Issue by YggdrasilWotLK** [WoWManiaUK/Redemption#6181]
**Links:**
https://www.wow-mania.com/armory/?spell=1002
https://www.wow-mania.com/armory/?spell=6215

**What is Happening:**
If a hunter is channeling eyes of the beast and gets feared by another player in a duel or Wintergrasp for example, the player becomes unable to control his or her own character. Instead, they control a lookalike that can't interact with the world while their actual character stays stuck in place until they relog. 

**What Should happen:**
Your soul shouldn't leave your body if you are feared while channeling eyes of the beast, the channel should just be interrupted.

This may or may not happen with other CCs, not sure, I try to avoid eyes of the beast in PVP scenarios now...

**Comment by Echinaceax** [comment]
thanks for reporting this @metallinos2 
we will take a look at it

**Comment by Echinaceax** [comment]
Confirmed bugged
bug https://i.gyazo.com/9d867065be9d6a4cfdc9e801c1235c97.mp4
cant attack after bug https://i.gyazo.com/562c7f1fad26f8d5c0d10fad2dfc6fbe.mp4

Eyes of the Beast https://www.wow-mania.com/armory/?spell=1002 checked with multiple classes (CC related spells) 
(Fear, Death Coil, Howl of Terror, Psychic Scream, Polymorph, Dragon's Breath etc...)

Once this bugs the player cannot attack and has to relog to fix their char

**Comment by Lumber-Jack-2** [comment]
should we make the eye immune to cc?

**Comment by Echinaceax** [comment]
> should we make the eye immune to cc?

yes, as there are a lot of cc that bugs the char

**Comment by Echinaceax** [comment]
Not fixed @Rushor
