### ISSUE TITLE
[Item Proc Buff] Last Word has 30-sec ICD on equip

### ISSUE THREAD

**Issue by YggdrasilWotLK** [WoWManiaUK/Redemption#6182]
**Links:**
https://www.wowhead.com/wotlk/item=50179/last-word#dropped-by
https://www.wow-mania.com/armory/?item=50708

**What is Happening:**
Last Word is a mace with a buff proc with a 37% proc rate per 1.80 swing. It will usually proc within five swings, and has an uptime of some 90+%. However, it does not proc for 30 seconds after equipping, similar to how Libram of Defiance and Libram of Divine Purpose acted before their respective fixes (re. https://github.com/WoWManiaUK/Redemption/issues/4952 and https://github.com/WoWManiaUK/Redemption/issues/4673). 

**What Should happen:**
Like other weapon slot items with a proc, Last Word should not have an ICD. Re Trauma, Val'anyr (which I see has a separate fix here: https://github.com/WoWManiaUK/Redemption/issues/2842), paladin librams, etc., to name a few.

**Comment by Maine1** [comment]
Can confirm this is having a 30 second CD on equip which shouldn't be there.

**Comment by Lumber-Jack-2** [comment]
30 sec cd should no longer be there on equip

**Comment by Echinaceax** [comment]
fixed in PTR https://i.gyazo.com/8cfba8291f711effb3666f759a4243d3.mp4

**Comment by Echinaceax** [comment]
@Rushor The fix you did for the normal version has to be done for the HC also 50708 please

**Comment by Lumber-Jack-2** [comment]
Yes will add all Version, Label was wrong yet

**Comment by Lumber-Jack-2** [comment]
fixed for both versions now

**Comment by Maine1** [comment]
@Rushor ICD on item equip is fixed. Last Word Heroic ID 50708 Doesn't say Heroic on the tooltip anymore. 
![image](https://github.com/WoWManiaUK/Redemption/assets/122736582/c6b3f030-dc91-4b2b-89bc-5b38555cb6ad)

**Comment by Lumber-Jack-2** [comment]
that tooltip thing was not changed by me - so not related to this fix. my fix works for the issue above

**Comment by Echinaceax** [comment]
> that tooltip thing was not changed by me - so not related to this fix. my fix works for the issue above

this was showing HC when i checked it here on this report 3 weeks ago, something changed somewhere @Rushor  

> fixed in PTR https://i.gyazo.com/8cfba8291f711effb3666f759a4243d3.mp4

![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/4922623b-a7a4-45ee-96bb-85a09d6f0fdc)

**Comment by Lumber-Jack-2** [comment]
okay fixed with next restart and cache clear

**Comment by Echinaceax** [comment]
> okay fixed with next restart and cache clear

All fixed again, thanks Rushor 
https://i.gyazo.com/66c653bc8f25f22b584c8146182628e2.mp4
