### ISSUE TITLE
Quest: The Drakkensryd

### ISSUE THREAD

**Issue by Nightowlgamerz** [WoWManiaUK/Redemption#6183]
**Links:**

**What is Happening:**
Everytime I start the quest it bugges out and then wont allow me to attack but they can attack me. Another thing that happens is when I do kill the first I cant attack any others after I harpoon to another drake, but they can kill me. I tried abandoning the quest and re taking it but still get the same problem.  I know its bugged because on a few tried I start doing damage the it glitchs out like server lag then resets. Every single time I think it is working it resets and they kill me.

**What Should happen:**

I harpoon to the drake kill the NPC and then move on.

**Comment by Echinaceax** [comment]
thanks for reporting @Nightowlamerz 
however this has been reported and fixed many times, the last fix is the best it will get https://github.com/WoWManiaUK/Redemption/issues?q=The+Drakkensryd

players do say it is do-able its just a pain in the bum. you just have to keep jumping from drake to drake until you complete it 

![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/37ee29d7-2568-414a-bb28-ea85a0676002)

**Comment by Nightowlgamerz** [comment]
Cant you just credit me the quest complete.

**Comment by Echinaceax** [comment]
> Cant you just credit me the quest complete.

testers cant, you'll have to speak with a GM ingame

**Comment by Nightowlgamerz** [comment]
how do I do that?
