### ISSUE TITLE
Flight Path delay on dismount at destination

### ISSUE THREAD

**Issue by womptista** [WoWManiaUK/Redemption#6184]
**Links:**
https://youtu.be/PoewekTLkvQ

**What is Happening:**
Upon landing at your destination there is about a 5-20 second delay in dismounting

**What Should happen:**
should be dismounted at destination instantly.

**Comment by Echinaceax** [comment]
Thanks @womptista this is fixed on live now 

https://i.gyazo.com/f8d5806a4945d745f5d3b0876ad5e634.mp4
