### ISSUE TITLE
Flying Bug in Silvermoon

### ISSUE THREAD

**Issue by Nightowlgamerz** [WoWManiaUK/Redemption#6186]
**Links:**

**What is Happening:**
I don't know if its a visual bug or actual bug but when you fly in Silvermoon area and in Ghostlands the flying mount act like its constantly hitting a wall moving in any direction. It moves but the sound effect of hitting the wall that the mount gives is kinda annoying.

**What Should happen:**

Smooth flying no wall hitting sound effect, except if you do hit the invisible wall.

**Comment by Nightowlgamerz** [comment]
I have a 30 second video of what I am saying but cant upload it for you to see it. Tells me files to long.

**Comment by fvicaria** [comment]
You are not supposed to fly over any of the big cities. The textures were not made for it.
We allow flight on Azeroth outside in the world only.

**Comment by Nightowlgamerz** [comment]
i wasn't flying  at a city it was inopen lands like ghostlands
