### ISSUE TITLE
Moonkins are bugged?

### ISSUE THREAD

**Issue by jurrianvg** [WoWManiaUK/Redemption#619]
Hello all, not many of us play balance, so this went unnoticed. But there are talents what are not working for balance druids. I went to do it for an offspec and i do little damage compaired to other people in Retail and i was wondering why. So i found some talent that might be bugged, first of all: when i shapeshift into moonkin i go from 3245 spellpower to 3442, this is very low(roughtly 6%), we have the talent furor that increases your intelect by 10% this one seems to work but i don't know if Lunar guidiance (12% of your total intelect = spellpower) works with this, we got master shapeshifter which should grant 4% bonus spell damage, and from the talent Earth and Moon we should gain 6% bonus spell damage, and from the improved moonkin form we should get that 30% off our total spirit is spellpower not sure if this one works or not because 3245-3442 = 197 spellpower and the spellpower i gain is roughtly 180 spellpower. So i hope this could get fixed and make moonkins great again! 

xoxo much love

- Lotus

**Comment by calvinidea** [comment]
Following... and BUMP! :)

**Comment by jurrianvg** [comment]
to make it easier to find the spells for you, it's about these : http://wotlk.openwow.com/spell=48511 (earth and moon), http://wotlk.openwow.com/spell=48396 (improved moonkin form), http://wotlk.openwow.com/spell=33591 (lunar guidance), http://wotlk.openwow.com/spell=17061 (furor),
can't find master shapeshifter.

**Comment by jurrianvg** [comment]
Found that too http://wotlk.openwow.com/spell=48421, from what i heard is that  http://wotlk.openwow.com/spell=24858 the 5% crit should not over ride http://wotlk.openwow.com/spell=51470 but not sure about this.

**Comment by elagen** [comment]
Tested Druid Boomkin and not bugged - Found the problem and now is sorted
