### ISSUE TITLE
Gnomish Flame Turret or Oil of Immolation is not getting damage buffs from Flame Buffet.

### ISSUE THREAD

**Issue by L0dos** [WoWManiaUK/Redemption#6190]
**Links:**
https://www.wowhead.com/wotlk/item=23841/gnomish-flame-turret
https://www.wowhead.com/wotlk/item=8956/oil-of-immolation

**What is Happening:**

Gnomish Flame Turret or Oil of Immolation is not getting damage buffs from Flame Buffet.
**What Should happen:**

They should get increased damage by +400 from flame buffet debuff on the target like flame caps or grenades does.

**Comment by Maine1** [comment]
@L0dos we need proof of this working as you say is intended through linking supporting evidence. E.g videos from WotLK 2009 or Screenshots of the evidence from 2009

**Comment by L0dos** [comment]
There are no comments videos this or that about it from 2009 as even in 2024 ppl don't use this strat. Tooltips are self explaning stating the items deals fire damage and if it's not going to work it shouldn't be working with flame caps, grenades, explosive traps, flametongue weapon enchants etc. like it does.

**Comment by Maine1** [comment]
@Rushor can you remember this back then or find anything. We cannot confirm nor deny

**Comment by GMZinius** [comment]
Reported asked for this to be closed
