### ISSUE TITLE
Unable to Loot Corpse

### ISSUE THREAD

**Issue by womptista** [WoWManiaUK/Redemption#6193]
**Links:**
[Video of error](https://youtu.be/HWBk-ezKoSo)

**What is Happening:**
When fishing in Borean more specifically (The Frozen Sea) I will get an message that tells me I am unable to loot that corpse. I am the only one fishing in that area and I have more than enough fishing skill 
(The error message shows up in the bottom left of the video)

**What Should happen:**
Not sure I am unable to find any information on it.

**Comment by Echinaceax** [comment]
hi @womptista thanks for reporting but this is a generic bug that cant be fixed https://github.com/WoWManiaUK/Redemption/issues/6025#issuecomment-1694668830

![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/96b4c352-4955-472d-bd1f-45cbce872b62)

**Comment by womptista** [comment]
Sorry for the double post and thank you for the answer.
