### ISSUE TITLE
[Spell] Romantic Picnic (45123)

### ISSUE THREAD

**Issue by YggdrasilWotLK** [WoWManiaUK/Redemption#6196]
**Links:**
https://www.wow-mania.com/armory/?spell=45102#see-also

**What is Happening:**
Sharing a Romantic Picnic with someone flagged for PVP flags you for PVP too

**What Should happen:**
This shouldn't flag you for PVP

**Comment by Echinaceax** [comment]
confirmed bug https://www.wow-mania.com/armory/?spell=45123
https://i.gyazo.com/103a6d5abefa37e5f1fa4e0e321823b7.mp4

![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/b40b5f92-8baa-464f-949a-1022000fb158)


Echimass flagged pvp  / Echie not flagged pvp

![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/80c5f2c0-7cdd-4b7c-aaa0-ffc2e451f46e)

Echimass  / Echie both flagged pvp 

![flagged](https://github.com/WoWManiaUK/Redemption/assets/39439201/2201637e-33ad-43ba-95cc-063ad83fc4bf)

**Comment by Lumber-Jack-2** [comment]
Romantic Basket can no longer be used if player is in pvp

**Comment by Echinaceax** [comment]
i confirmed this as bugged before any proof was given as to how this is meant to function.
Rushor has however done a few code changes that hasnt worked. 
So we cannot fix this issue.  
as-is
