### ISSUE TITLE
Last Word HC still has ICD on equip

### ISSUE THREAD

**Issue by YggdrasilWotLK** [WoWManiaUK/Redemption#6197]
Hi all, re https://github.com/WoWManiaUK/Redemption/issues/6182#issuecomment-1943870559, I see this is now working as intended for the normal version of Last Word (https://www.wow-mania.com/armory/?item=50179) but not the HC version (https://www.wow-mania.com/armory/?item=50708). Could the fix be implemented for both items perhaps?

**Comment by Echinaceax** [comment]
Thanks @metallinos2 i have reopened the other report
so i will close this one
