### ISSUE TITLE
[Item ] Deadly Poison IX / Rogue offhand poison

### ISSUE THREAD

**Issue by thechillmaster** [WoWManiaUK/Redemption#6198]
hello

on rogue i have the problem the [Deadly Poison IX] not applying to boss after [Deathbringer's Will] proccs 

i see this happening many times now and i want to see if fixable somehow ?

**Comment by Maine1** [comment]
@thechillmaster Please provide links / boss name & evidence (https://github.com/WoWManiaUK/Redemption/wiki/How-to-Properly-Report-an-Issue) of it not applying with DBW proc please. I just checked this with DBW proc on Marrowgar and it still applied deadly poison while proc is active.
![image](https://github.com/WoWManiaUK/Redemption/assets/122736582/be635425-14ec-4338-9b72-38c5e679afe3)
![image](https://github.com/WoWManiaUK/Redemption/assets/122736582/3c5344e8-6618-4555-80f7-00826e4b8fbe)
![image](https://github.com/WoWManiaUK/Redemption/assets/122736582/38503a90-79a2-4350-945c-cd7b8940d8a1)
![image](https://github.com/WoWManiaUK/Redemption/assets/122736582/1286eab1-95bd-4332-93fd-8563221c9a04)

**Comment by Lumber-Jack-2** [comment]
Cannot reproduce aswell on several creatures
