### ISSUE TITLE
[Class] [Spell] [Pet] DK's Army of the Dead – Expertise, Hit, Haste

### ISSUE THREAD

**Issue by Greywolf59** [WoWManiaUK/Redemption#6199]
So I have found some issues with the [Army of the Dead](https://www.wow-mania.com/armory/?spell=42650) and [the ghouls](https://www.wow-mania.com/armory/?npc=24207) it summons.

The ghouls were getting misses and dodges on lvl 70 target.
– My stats: Blood DK two handed, 26 expertise, of which 6 points are given by [Veteran of the Third War talent](https://www.wow-mania.com/armory/?spell=50029). Hit chance: 261 (7.96%). +3% **spell** hit from [Virulence](https://www.wow-mania.com/armory/?spell=49568).
– Lots of dodged and misses registered on targets of level 80 in dungeon and even on lower targets.

Example A: Fight with [King Dred](https://www.wow-mania.com/armory/?npc=27483) on Normal Difficulty (lvl 76 iirc)
![king dread N army](https://github.com/WoWManiaUK/Redemption/assets/41387450/5fc7660e-f63d-495a-af7c-db2bc941c5a7)

Example B: [Level 70 Dummy](https://www.wow-mania.com/armory/?npc=32667) in Dalaran
![lvl 70 dala dummy army](https://github.com/WoWManiaUK/Redemption/assets/41387450/e4c313e6-103d-4e6d-afab-8205b2d8c5dc)

I do also notice the low chance on critical strikes, however I am not versed on how critical strike chance works with uncontrollable pets. Just for information crit chance of my DK is 37.81% (475 Agi for 10.8% and 919 crit rating for 20.02%). Both Army and Bloodworms seem to have about 5% fixed crit chance for Melee. 

https://www.wowhead.com/patchnotes=3.2.0 under "Classes: General"
Note: I did increase my hit rating to 271 for one more quick test run on 70 dummy just in case, the results were the same.

**Comment by Greywolf59** [comment]
Second thing I would like to tackle is Haste. The zombies should snapshot the stats at the time of cast.
For my test I have used lvl 70 Dummy in Dalaran.
1st summon: [Potion of Speed](https://www.wow-mania.com/armory/?item=40211), Troll's [Berserking](https://www.wow-mania.com/armory/?spell=26297), haste from gear: 214
– 153 melee hits, 88 Claws

2nd summon: no buffs, just haste from gear: 214
– 152 hits, 88 Claws

3rd summon: brought shaman for [Bloodlust](https://www.wow-mania.com/armory/?spell=2825), no other buffs, haste from gear: 214
– 152 hits, 88 Claws

4th summon: no buffs, [Unholy Presence](https://www.wow-mania.com/armory/?spell=49772), haste from gear: 214
– 152 hits, 88 Claws

So it seems that Army of the Dead does not snapshot the haste stats on summon. They should benefit from Unholy Presence, Bloodlust/Hero being active when cast is started, haste stat buffs both in form of Haste Rating and Attack/Cast speed, however they do not benefit from any of these. There was one extra attack when Potion of Speed was used and that pretty much seems like absolutely random occurence (400 haste, 8 ghouls and just only 1 extra attack in total). This problem might be shared with other Guardian Pets.

Resources:
https://wowwiki-archive.fandom.com/wiki/Army_of_the_Dead?oldid=1963894
https://wowwiki-archive.fandom.com/wiki/Army_of_the_Dead
https://www.wowhead.com/wotlk/spell=42650/army-of-the-dead#comments:id=989522

SIDE NOTE: Untalented [Risen Ghoul](https://www.wowhead.com/wotlk/npc=26125/risen-ghoul) summoned by [Raise Dead](https://www.wow-mania.com/armory/?spell=46584) benefits from haste snapshotting correctly and also does not get any misses or dodges.

**Comment by Lumber-Jack-2** [comment]
Need to copy the mechanic from the Rosen ghoul then
