### ISSUE TITLE
Dismount Lag on flight path when at destination

### ISSUE THREAD

**Issue by womptista** [WoWManiaUK/Redemption#6200]
**Links:**
Video recorded on 03/06/2024
https://youtu.be/gIUbbJ0Ru5s

**What is Happening:**
When using the flight path, there is a dismount lag when reaching your destination

**What Should happen:**
Should Immediately dismount when you arrive at destination.

**Comment by Echinaceax** [comment]
Thanks @womptista for reporting but as i replied here https://github.com/WoWManiaUK/Redemption/issues/6184 it was fixed, then GM commented in Naxx discord yesterday about this, no need to make duplicate reports 

We know that this was fixed and then bugged again recently. 
Please give the Dev time to refix it. thanks

Note: if you look at your video at timestamp 1:23 you will see that the Flight master isnt there for a few secs, which is what was fixed 3 weeks ago, and as bugged again for some reason

it is being looked into atm.
