### ISSUE TITLE
[Object] Bruiseweed - suspended mid-air

### ISSUE THREAD

**Issue by Chipmunk1999** [WoWManiaUK/Redemption#6201]
![Screenshot 2024-03-07 163557](https://github.com/WoWManiaUK/Redemption/assets/94846928/4c526923-6431-4bd7-9f7f-2e1ee0f5fa2e)
![Screenshot 2024-03-07 163631](https://github.com/WoWManiaUK/Redemption/assets/94846928/3304498d-a6ef-4a07-9874-c9ba3e3e8b28)
**Links:**

**What is Happening:**
There is a Bruiseweed node suspended in mid-air in Stonetalon Mountains at or near coordinates 73.01, 47.67

**What Should happen:**
Bruiseweed should be on the ground and harvestable.

**Comment by Maine1** [comment]
@Chipmunk1999 Must have been a random spawn maybe elevated after a restart. I can't find this node spawned on Redemption or in PTR.

**Comment by Maine1** [comment]
@Rushor Can probably confirm or deny my findings.

**Comment by Lumber-Jack-2** [comment]
[10:18:24]3440 (Entry: 1622) - [Bruiseweed X:1366.000000 Y:-318.000000 Z:17.500000 MapId:1] 
[10:18:24]3714 (Entry: 1622) - [Bruiseweed X:1371.449951 Y:-299.000000 Z:3.965000 MapId:1] 
[10:18:24]44737 (Entry: 1622) - [Bruiseweed X:1389.800049 Y:-360.001007 Z:13.561400 MapId:1]

**Comment by Lumber-Jack-2** [comment]
.go object 3440

position fixed

**Comment by Echinaceax** [comment]
Confirmed fixed in PTR 
https://i.gyazo.com/fb2197671b6dc09c7c43e3744abbe458.mp4
