### ISSUE TITLE
Is That Your Goblin? (BUGGED)

### ISSUE THREAD

**Issue by Nightowlgamerz** [WoWManiaUK/Redemption#6202]
**Links:**

**What is Happening:**
I accept the quest to challenge her but when I go to click on her I get no dialog box to issue the challenge and attack her. I dropped the quest 2 times and still same situation.

**What Should happen:**
Click , dialog box appears and we fight.

**Comment by Echinaceax** [comment]
Thanks @Nightowlamerz for reporting
please add links as stated here https://github.com/WoWManiaUK/Redemption/wiki/How-to-Properly-Report-an-Issue

i do not believe this is bugged
make sure you are using the mania client and is updated
regularly delete cache, this can help with client bugs that no other player is having

**Comment by Nightowlgamerz** [comment]
I just noticed the update and updated will retry again

**Comment by Nightowlgamerz** [comment]
worked , sorry for the mess up.
