### ISSUE TITLE
[Quest] Captives at Deatholme

### ISSUE THREAD

**Issue by theejynx** [WoWManiaUK/Redemption#6203]
**Links:**
https://www.wowhead.com/quest=9164/captives-at-deatholme
https://www.wowhead.com/wotlk/quest=515/elixir-of-agony

**What is Happening:**
I accepted this quest on all four of my toons, however, when completing it, only the main toon received credit for speaking to the NPCs. Does each toon need to go through the motions? The NPCs walk away after being rescued.
![Screenshot 2024-03-06 184123](https://github.com/WoWManiaUK/Redemption/assets/72872218/089bd46e-a6b6-46f6-9515-7e067ab1b93d)

This isn't the only quest like this one. There is another example I encountered shortly after, Elixir of Agony in Tarren Mills. You are tasked with giving the elixir to Umpi, who then dies.

I don't know that it's a bug, as I was told by another GM that when a quest isn't sharable, the completion needs to be executed individually. However, this does make the flow of these types of quests cumbersome and timely. The NPCs take several minutes to respawn.

**What Should happen:**

When any member of the party completes that portion of the quest, everyone in part should have that interaction completed. Or, alternatively, the NPC could respawn faster to allow for better completion of those quests.

**Comment by Maine1** [comment]
@theejynx Can you provide any evidence that shows this was previously completed in a group. Usually we require video or photo evidence or comments to show this is how it used to be.

**Comment by theejynx** [comment]
I cannot. I wasn't going to report it as a bug at all, however was directed to by Zinius via the forum. :/ It's been a long time since OG WotLK and my memory is lacking at best.

**Comment by Lumber-Jack-2** [comment]
https://www.wowhead.com/wotlk/quest=515/elixir-of-agony cannot be changed here.

but group credit for players in range fixed for https://www.wowhead.com/quest=9164/captives-at-deatholme

such issues must be fixed manually - cannot be done in a general fix

**Comment by Echinaceax** [comment]
confirmed fixed in PTR 
https://i.gyazo.com/e806aa0d33ebca614322bda95665a932.mp4
