### ISSUE TITLE
[ICC] - Frost Giant weekly quest missing

### ISSUE THREAD

**Issue by Maine1** [WoWManiaUK/Redemption#6204]
**Links:**
https://www.wowhead.com/wotlk/quest=24871/securing-the-ramparts

**What is Happening:**
NPC [Skybreaker Lieutenant](https://www.wowhead.com/wotlk/npc=38492/skybreaker-lieutenant) Is not at the start of ICC on 25 Nm + HC versions of ICC. Position 
![image](https://github.com/WoWManiaUK/Redemption/assets/122736582/b7744983-74b7-4684-a5ab-97a732091308)
 
 I believe it is on 10 Nm but not sure about 10HC (will need checking inside DB) There should also be the same NPC spawned at the *Rampart of Skulls* in position. This is currently not working for alliance only. Horde seems to work without issues.
![image](https://github.com/WoWManiaUK/Redemption/assets/122736582/4b96d4db-7358-4e1f-848e-c4c43c21c368)

**What Should happen:**
NPC [Skybreaker Lieutenant](https://www.wowhead.com/wotlk/npc=38492/skybreaker-lieutenant) should be at the start of ICC on that weekly rotation and have quest https://www.wowhead.com/wotlk/quest=24871/securing-the-ramparts available 

After help with looking an old report was found. https://github.com/WoWManiaUK/Redemption/issues/5702 

Seems like Securing the ramparts was removed for some difficulties by the looks of this report instead of working as intended. Also looks like testers at the time didn't recheck everything!

**Comment by Lumber-Jack-2** [comment]
thos quest are rotating

they only spawn when the quests are active:

WeeklyQuest const WeeklyQuestData[WeeklyNPCs] =
{
	{NPC_INFILTRATOR_MINCHAR,         {QUEST_DEPROGRAMMING_10,                 QUEST_DEPROGRAMMING_25                }}, // Deprogramming
	{NPC_KOR_KRON_LIEUTENANT,         {QUEST_SECURING_THE_RAMPARTS_10,         QUEST_SECURING_THE_RAMPARTS_25        }}, // Securing the Ramparts
	{NPC_ROTTING_FROST_GIANT_10,      {QUEST_SECURING_THE_RAMPARTS_10,         QUEST_SECURING_THE_RAMPARTS_25        }}, // Securing the Ramparts
	{NPC_ROTTING_FROST_GIANT_25,      {QUEST_SECURING_THE_RAMPARTS_10,         QUEST_SECURING_THE_RAMPARTS_25        }}, // Securing the Ramparts
	{NPC_ALCHEMIST_ADRIANNA,          {QUEST_RESIDUE_RENDEZVOUS_10,            QUEST_RESIDUE_RENDEZVOUS_25           }}, // Residue Rendezvous
	{NPC_ALRIN_THE_AGILE,             {QUEST_BLOOD_QUICKENING_10,              QUEST_BLOOD_QUICKENING_25             }}, // Blood Quickening
	{NPC_INFILTRATOR_MINCHAR_BQ,      {QUEST_BLOOD_QUICKENING_10,              QUEST_BLOOD_QUICKENING_25             }}, // Blood Quickening
	{NPC_MINCHAR_BEAM_STALKER,        {QUEST_BLOOD_QUICKENING_10,              QUEST_BLOOD_QUICKENING_25             }}, // Blood Quickening
	{NPC_VALITHRIA_DREAMWALKER_QUEST, {QUEST_RESPITE_FOR_A_TORNMENTED_SOUL_10, QUEST_RESPITE_FOR_A_TORNMENTED_SOUL_25}}  // Respite for a Tormented Soul
};

**Comment by Lumber-Jack-2** [comment]
for future fix:

SELECT * FROM `pool_quest` WHERE entry IN (
24874,
24869,
24873,
24872,
24870,
24871,
24879,
24875,
24878,
24880,
24876,
24877);

SELECT * FROM `pool_quest` WHERE pool_entry IN (
5682,
5685,
5685,
5684,
5683,
5681,
5687,
5690,
5690,
5688,
5686,
5689);

**Comment by Maine1** [comment]
@Rushor if you didn't change anything in the code then it is still broken. They are rotating for the rest but not the 1 mentioned above. When that quest is on the weekly there is no NPC spawning for it
- [x] Works perfect for horde
- [ ] Broke for alliance

**Comment by Maine1** [comment]
> thos quest are rotating
> 
> they only spawn when the quests are active:
> 
> WeeklyQuest const WeeklyQuestData[WeeklyNPCs] = { {NPC_INFILTRATOR_MINCHAR, {QUEST_DEPROGRAMMING_10, QUEST_DEPROGRAMMING_25 }}, // Deprogramming {NPC_KOR_KRON_LIEUTENANT, {QUEST_SECURING_THE_RAMPARTS_10, QUEST_SECURING_THE_RAMPARTS_25 }}, // Securing the Ramparts {NPC_ROTTING_FROST_GIANT_10, {QUEST_SECURING_THE_RAMPARTS_10, QUEST_SECURING_THE_RAMPARTS_25 }}, // Securing the Ramparts {NPC_ROTTING_FROST_GIANT_25, {QUEST_SECURING_THE_RAMPARTS_10, QUEST_SECURING_THE_RAMPARTS_25 }}, // Securing the Ramparts {NPC_ALCHEMIST_ADRIANNA, {QUEST_RESIDUE_RENDEZVOUS_10, QUEST_RESIDUE_RENDEZVOUS_25 }}, // Residue Rendezvous {NPC_ALRIN_THE_AGILE, {QUEST_BLOOD_QUICKENING_10, QUEST_BLOOD_QUICKENING_25 }}, // Blood Quickening {NPC_INFILTRATOR_MINCHAR_BQ, {QUEST_BLOOD_QUICKENING_10, QUEST_BLOOD_QUICKENING_25 }}, // Blood Quickening {NPC_MINCHAR_BEAM_STALKER, {QUEST_BLOOD_QUICKENING_10, QUEST_BLOOD_QUICKENING_25 }}, // Blood Quickening {NPC_VALITHRIA_DREAMWALKER_QUEST, {QUEST_RESPITE_FOR_A_TORNMENTED_SOUL_10, QUEST_RESPITE_FOR_A_TORNMENTED_SOUL_25}} // Respite for a Tormented Soul };

From Above code - 

- [ ] Skybreaker Lieutenant missing

**Comment by Maine1** [comment]
{NPC_SKYBREAKER_LIEUTENANT, {QUEST_SECURING_THE_RAMPARTS_10, QUEST_SECURING_THE_RAMPARTS_25 }}, // Securing the Ramparts {NPC_ROTTING_FROST_GIANT_10, {QUEST_SECURING_THE_RAMPARTS_10, QUEST_SECURING_THE_RAMPARTS_25 }},

I added this as a section to apply the alliance NPC named - Skybreaker Lieutenant 

Please check code for errors incase its not right before applying
@Rushor

**Comment by Lumber-Jack-2** [comment]
the issue that could be, is that creature NPC_SKYBREAKER_LIEUTENANT has not a spawnpoint. it's basically only NPC_KOR_KRON_LIEUTENANT which gets updated to NPC_SKYBREAKER_LIEUTENANT - but let#s give it a try! good idea

**Comment by Maine1** [comment]
This didn't fix - try 

{
{NPC_INFILTRATOR_MINCHAR, {QUEST_DEPROGRAMMING_10, QUEST_DEPROGRAMMING_25 }}, // Deprogramming
{NPC_KOR_KRON_LIEUTENANT, {QUEST_SECURING_THE_RAMPARTS_10, QUEST_SECURING_THE_RAMPARTS_25 }}, // Securing the Ramparts {NPC_SKYBREAKER_LIEUTENANT, {QUEST_SECURING_THE_RAMPARTS_10, QUEST_SECURING_THE_RAMPARTS_25 }}, // Securing the Ramparts
{NPC_ROTTING_FROST_GIANT_10, {QUEST_SECURING_THE_RAMPARTS_10, QUEST_SECURING_THE_RAMPARTS_25 }}, // Securing the Ramparts
{NPC_ROTTING_FROST_GIANT_25, {QUEST_SECURING_THE_RAMPARTS_10, QUEST_SECURING_THE_RAMPARTS_25 }}, // Securing the Ramparts
{NPC_ALCHEMIST_ADRIANNA, {QUEST_RESIDUE_RENDEZVOUS_10, QUEST_RESIDUE_RENDEZVOUS_25 }}, // Residue Rendezvous
{NPC_ALRIN_THE_AGILE, {QUEST_BLOOD_QUICKENING_10, QUEST_BLOOD_QUICKENING_25 }}, // Blood Quickening
{NPC_INFILTRATOR_MINCHAR_BQ, {QUEST_BLOOD_QUICKENING_10, QUEST_BLOOD_QUICKENING_25 }}, // Blood Quickening
{NPC_MINCHAR_BEAM_STALKER, {QUEST_BLOOD_QUICKENING_10, QUEST_BLOOD_QUICKENING_25 }}, // Blood Quickening
{NPC_VALITHRIA_DREAMWALKER_QUEST, {QUEST_RESPITE_FOR_A_TORNMENTED_SOUL_10, QUEST_RESPITE_FOR_A_TORNMENTED_SOUL_25}} // Respite for a Tormented Soul
};

**Comment by Maine1** [comment]
@Rushor https://github.com/WoWManiaUK/Redemption/issues/5702 Whatever was changed here in this section changed the quest to never show up maybe it was set to 2 instead of 1 because as you previously mentioned Skybreaker Lieutenant is a copy spawn of Kor'kron Lieutenant

https://github.com/WoWManiaUK/Redemption/issues/5702#issuecomment-1033046488 with skybreaker being a copy of Kor-kron maybe this is why it was set to 2 instead of 1!

**Comment by Maine1** [comment]
10 NM Ally - Complete
10 HC Ally - Complete
25 NM Ally - Complete
25 HC Ally - Complete
10 NM Horde - Complete
10 HC Horde - Complete
25 NM Horde - Complete
25 HC Horde - Complete
Frost giant is working perfectly now in all difficulties for both alliance and Horde

@fvicaria Thank you very much for the fix.
