### ISSUE TITLE
[Object] Barrel 182589 - No visual fire for players - Old Hillsbrad Foothills

### ISSUE THREAD

**Issue by Chipmunk1999** [WoWManiaUK/Redemption#6205]
**Links:**
Here is a link to a Youtube video of someone running it and the dungeon working as intended; later than 2.4.3 and looks later than 3.3.5a, but it should function the same regardless.
https://www.youtube.com/watch?v=N6QzpEkS3tU

**What is Happening:**
The lodges are not catching fire after the incendiary charges that are given to us at the entrance are placed in the barrels.  I cleared the enemies, and double checked each lodge.  After the charges are placed, nothing happens; fortunately, Lt. Drake still shows up, but he does not patrol towards the bridge like he is supposed to.  You can see in the screenshots that all charges are placed, and Lt. Drake has spawned.

**What Should happen:**
The lodges should catch on fire with an audible "whooshing" fire noise.  Lt. Drake should start walking from the stairs to the East of the lodging pit, heading West / North West, and he should be saying stuff.

I have a bandicam video, but it is too large to attach.

![Screenshot 2024-03-13 000215](https://github.com/WoWManiaUK/Redemption/assets/94846928/17a89819-fdca-4b49-9bbc-a2beca8ee85d)
![Screenshot 2024-03-13 000146](https://github.com/WoWManiaUK/Redemption/assets/94846928/28aff8de-aada-4b8a-81ca-4a3f02ca7dfe)
![Screenshot 2024-03-13 000134](https://github.com/WoWManiaUK/Redemption/assets/94846928/82ece897-456f-4afe-a194-34b2446e044a)

**Comment by Maine1** [comment]
@Chipmunk1999 I remember doing this quest back then. He is indeed meant to walk to the lodges and they are supposed to catch fire from 5 bombs set

If you have a bandicam video you can go to mega on the internet and upload there and post the link to view here.

**Comment by Chipmunk1999** [comment]
Hi Maine1,

Here is the [Link to the video](https://mega.nz/file/YWUWFDqK#X_L7iz8gZNOZ4rMaouVjRsOjR3zAydLZxolq1J6WQs8).  First time using Mega, cool service!

**Comment by Maine1** [comment]
@Chipmunk1999 thanks for the video. Will look into this.

**Comment by Maine1** [comment]
@Rushor Looked into this quest in detail now. Charges given on quest pick up 
![image](https://github.com/WoWManiaUK/Redemption/assets/122736582/fc973db7-63c8-4481-847b-ef65fd4c65e1)
- [x] Use Pack of incendiary bombs to set charges inside 5/5 barrels (Working)
- [ ] After setting 5/5 All 5 lodges are supposed to set ablaze as stated in the quest on completion
![image](https://github.com/WoWManiaUK/Redemption/assets/122736582/92efc742-82a4-41c8-8219-eb4c5741e672)
![image](https://github.com/WoWManiaUK/Redemption/assets/122736582/62a5ffa6-8835-4a5b-9e95-7ae26b634bec)
- [ ] At this point Lieutenant Drake Spawns and is supposed to walk to the side under the bridge with the 2 lodges and stop at position 
![image](https://github.com/WoWManiaUK/Redemption/assets/122736582/15c8248f-3f51-4eb8-b555-8520a64c15c7)
- [ ] He is supposed to have chat dialog as shown in the video That can be seen on this link. https://www.youtube.com/watch?v=N6QzpEkS3tU
- [ ] Full chat dialog here 
Link for dialog below https://www.wowhead.com/npc=17848/lieutenant-drake#:~:text=Lieutenant%20Drake%20is%20the%20first,Old%20Hillsbrad%20Foothills%20(2).
![image](https://github.com/WoWManiaUK/Redemption/assets/122736582/0b1ff0ad-c936-49a4-af07-1477dee1e852)
Link for Dialog below https://wowpedia.fandom.com/wiki/Lieutenant_Drake
![image](https://github.com/WoWManiaUK/Redemption/assets/122736582/7a4f3e46-29c9-45cc-ab8a-5793ec68eaa8)
- [ ] Lodges have ablaze effect only with GM Mode turned on 
![image](https://github.com/WoWManiaUK/Redemption/assets/122736582/904b52da-11ad-45fa-ba33-2dc7ed4fffbb)
- [ ] I believe this trigger sets them ablaze after placing the all 5/5 Incendiary Bombs. 
![image](https://github.com/WoWManiaUK/Redemption/assets/122736582/f54cf2e2-285f-4ef6-9f01-7f1830969ef4)

Fix is 
- [ ] Set Lodges ablaze after 5/5 bombs set
- [ ] Fix Lieutenant Drake's Pathing
- [ ] Fix Lieutenant Drake's Dialog
