### ISSUE TITLE
[Glyph] Hemorrhage - Glyph not working.

### ISSUE THREAD

**Issue by Maine1** [WoWManiaUK/Redemption#6206]
**Links:**
![image](https://github.com/WoWManiaUK/Redemption/assets/122736582/28149fbd-e12a-406b-9a93-4aeaea574d7b)

**What is Happening:**
Hemorrhage is not applying 40% increase when using Glyph of Hemorrhage.

**What Should happen:**
Glyph of Hemorrhage should apply 40% bonus damage to the already applied 75 damage. = 75x40%=30 - should equate to 105 damage.

Link from my combat logging. 

(WITHOUT GLYPH)
3/13 16:02:39.968  SPELL_CAST_SUCCESS,0x00000000000D75BD,"Peekysneak",0x511,0xF130007F9B001A6E,"Master's Training Dummy",0x10a28,48660,"Hemorrhage",0x1
3/13 16:02:39.968  SPELL_DAMAGE,0x00000000000D75BD,"Peekysneak",0x511,0xF130007F9B001A6E,"Master's Training Dummy",0x10a28,48660,"Hemorrhage",0x1,1543,1541,1,0,0,0,nil,nil,nil
3/13 16:02:40.065  SPELL_AURA_APPLIED,0x00000000000D75BD,"Peekysneak",0x511,0xF130007F9B001A6E,"Master's Training Dummy",0x10a28,48660,"Hemorrhage",0x1,DEBUFF
3/13 16:02:41.048  SPELL_CAST_SUCCESS,0x00000000000D75BD,"Peekysneak",0x511,0xF130007F9B001A6E,"Master's Training Dummy",0x10a28,48660,"Hemorrhage",0x1
3/13 16:02:41.048  SPELL_DAMAGE,0x00000000000D75BD,"Peekysneak",0x511,0xF130007F9B001A6E,"Master's Training Dummy",0x10a28,48660,"Hemorrhage",0x1,1663,1661,1,0,0,0,nil,nil,nil
3/13 16:02:42.164  SPELL_CAST_SUCCESS,0x00000000000D75BD,"Peekysneak",0x511,0xF130007F9B001A6E,"Master's Training Dummy",0x10a28,48660,"Hemorrhage",0x1
3/13 16:02:42.164  SPELL_DAMAGE,0x00000000000D75BD,"Peekysneak",0x511,0xF130007F9B001A6E,"Master's Training Dummy",0x10a28,48660,"Hemorrhage",0x1,1493,1491,1,0,0,0,nil,nil,nil
3/13 16:02:43.233  SPELL_CAST_SUCCESS,0x00000000000D75BD,"Peekysneak",0x511,0xF130007F9B001A6E,"Master's Training Dummy",0x10a28,48660,"Hemorrhage",0x1
3/13 16:02:43.233  SPELL_DAMAGE,0x00000000000D75BD,"Peekysneak",0x511,0xF130007F9B001A6E,"Master's Training Dummy",0x10a28,48660,"Hemorrhage",0x1,3314,3312,1,0,0,0,1,nil,nil
3/13 16:02:43.332  SPELL_AURA_REFRESH,0x00000000000D75BD,"Peekysneak",0x511,0xF130007F9B001A6E,"Master's Training Dummy",0x10a28,48660,"Hemorrhage",0x1,DEBUFF
3/13 16:02:44.317  SPELL_CAST_SUCCESS,0x00000000000D75BD,"Peekysneak",0x511,0xF130007F9B001A6E,"Master's Training Dummy",0x10a28,48660,"Hemorrhage",0x1
3/13 16:02:44.317  SPELL_DAMAGE,0x00000000000D75BD,"Peekysneak",0x511,0xF130007F9B001A6E,"Master's Training Dummy",0x10a28,48660,"Hemorrhage",0x1,1525,1523,1,0,0,0,nil,nil,nil
3/13 16:02:46.201  SPELL_CAST_SUCCESS,0x00000000000D75BD,"Peekysneak",0x511,0xF130007F9B001A6E,"Master's Training Dummy",0x10a28,48660,"Hemorrhage",0x1
3/13 16:02:46.201  SPELL_DAMAGE,0x00000000000D75BD,"Peekysneak",0x511,0xF130007F9B001A6E,"Master's Training Dummy",0x10a28,48660,"Hemorrhage",0x1,3192,3190,1,0,0,0,1,nil,nil
3/13 16:03:01.855  SPELL_AURA_REMOVED,0x00000000000D75BD,"Peekysneak",0x511,0xF130007F9B001A6E,"Master's Training Dummy",0xa28,48660,"Hemorrhage",0x1,DEBUFF

(WITH GLYPH)
3/13 16:03:34.956  SPELL_CAST_START,0x00000000000D75BD,"Peekysneak",0x511,0x0000000000000000,nil,0x80000000,57296,"Glyph of Hemorrhage",0x1
3/13 16:03:53.108  SPELL_CAST_SUCCESS,0x00000000000D75BD,"Peekysneak",0x511,0xF130007F9B001A6E,"Master's Training Dummy",0x10a28,48660,"Hemorrhage",0x1
3/13 16:03:53.108  SPELL_DAMAGE,0x00000000000D75BD,"Peekysneak",0x511,0xF130007F9B001A6E,"Master's Training Dummy",0x10a28,48660,"Hemorrhage",0x1,1587,1585,1,0,0,0,nil,nil,nil
3/13 16:03:53.204  SPELL_AURA_APPLIED,0x00000000000D75BD,"Peekysneak",0x511,0xF130007F9B001A6E,"Master's Training Dummy",0x10a28,48660,"Hemorrhage",0x1,DEBUFF
3/13 16:03:54.206  SPELL_CAST_SUCCESS,0x00000000000D75BD,"Peekysneak",0x511,0xF130007F9B001A6E,"Master's Training Dummy",0x10a28,48660,"Hemorrhage",0x1
3/13 16:03:54.206  SPELL_DAMAGE,0x00000000000D75BD,"Peekysneak",0x511,0xF130007F9B001A6E,"Master's Training Dummy",0x10a28,48660,"Hemorrhage",0x1,1757,1755,1,0,0,0,nil,nil,nil
3/13 16:03:55.405  SPELL_CAST_SUCCESS,0x00000000000D75BD,"Peekysneak",0x511,0xF130007F9B001A6E,"Master's Training Dummy",0x10a28,48660,"Hemorrhage",0x1
3/13 16:03:55.405  SPELL_DAMAGE,0x00000000000D75BD,"Peekysneak",0x511,0xF130007F9B001A6E,"Master's Training Dummy",0x10a28,48660,"Hemorrhage",0x1,1586,1584,1,0,0,0,nil,nil,nil
3/13 16:03:56.607  SPELL_CAST_SUCCESS,0x00000000000D75BD,"Peekysneak",0x511,0xF130007F9B001A6E,"Master's Training Dummy",0x10a28,48660,"Hemorrhage",0x1
3/13 16:03:56.607  SPELL_DAMAGE,0x00000000000D75BD,"Peekysneak",0x511,0xF130007F9B001A6E,"Master's Training Dummy",0x10a28,48660,"Hemorrhage",0x1,3197,3195,1,0,0,0,1,nil,nil
3/13 16:03:56.706  SPELL_AURA_REFRESH,0x00000000000D75BD,"Peekysneak",0x511,0xF130007F9B001A6E,"Master's Training Dummy",0x10a28,48660,"Hemorrhage",0x1,DEBUFF
3/13 16:03:57.693  SPELL_CAST_SUCCESS,0x00000000000D75BD,"Peekysneak",0x511,0xF130007F9B001A6E,"Master's Training Dummy",0x10a28,48660,"Hemorrhage",0x1
3/13 16:03:57.693  SPELL_DAMAGE,0x00000000000D75BD,"Peekysneak",0x511,0xF130007F9B001A6E,"Master's Training Dummy",0x10a28,48660,"Hemorrhage",0x1,3300,3298,1,0,0,0,1,nil,nil
3/13 16:03:59.242  SPELL_CAST_SUCCESS,0x00000000000D75BD,"Peekysneak",0x511,0xF130007F9B001A6E,"Master's Training Dummy",0x10a28,48660,"Hemorrhage",0x1
3/13 16:03:59.242  SPELL_DAMAGE,0x00000000000D75BD,"Peekysneak",0x511,0xF130007F9B001A6E,"Master's Training Dummy",0x10a28,48660,"Hemorrhage",0x1,1683,1681,1,0,0,0,nil,nil,nil
3/13 16:03:59.359  SPELL_AURA_REFRESH,0x00000000000D75BD,"Peekysneak",0x511,0xF130007F9B001A6E,"Master's Training Dummy",0x10a28,48660,"Hemorrhage",0x1,DEBUFF
3/13 16:04:02.496  SPELL_CAST_SUCCESS,0x00000000000D75BD,"Peekysneak",0x511,0xF130007F9B001A6E,"Master's Training Dummy",0x10a28,48660,"Hemorrhage",0x1
3/13 16:04:02.497  SPELL_DAMAGE,0x00000000000D75BD,"Peekysneak",0x511,0xF130007F9B001A6E,"Master's Training Dummy",0x10a28,48660,"Hemorrhage",0x1,1559,1557,1,0,0,0,nil,nil,nil

**Comment by Lumber-Jack-2** [comment]
Effect 0: Id 6 (SPELL_EFFECT_APPLY_AURA)
BasePoints = 40
Targets (1, 0) (TARGET_UNIT_CASTER, NO_TARGET)
Aura Id 108 (SPELL_AURA_ADD_PCT_MODIFIER), value = 40, misc = 23 (SPELLMOD_EFFECT3), miscB = 0, periodic = 0
SpellClassMask = 02000000 00000000 00000000
	+ 16511 - Hemorrhage (Rank 1)
	+ 17347 - Hemorrhage (Rank 2)
	+ 17348 - Hemorrhage (Rank 3)
	+ 26864 - Hemorrhage (Rank 4)
	+ 48660 - Hemorrhage (Rank 5)

the effect is applied to thos spells
