### ISSUE TITLE
Hellfire Ramparts: Vazruden doesn't land when engaged

### ISSUE THREAD

**Issue by Chipmunk1999** [WoWManiaUK/Redemption#6207]
**Links:**
[Here is a link to the video](https://mega.nz/file/4CliDT7S#Jc7XEduJqRQJ5h6vEj6H5ClJqdWO9bZEEvkeHBHVcfM) I took after engaging Vazruden, the last boss in Hellfire Ramparts.  I have also attached some screenshots.

**What is Happening:**
Vazruden the Herald is not landing when engaged.  I had to cast a spell on him to engage, likely due to my level and aggro ranges, but once engaged he did not dismount his dragon.

Edit: I also could not loot the dead boss.

**What Should happen:**
Vazruden(Vaz) should aggro onto the player when entering his arena.  Once aggro'd, Vaz should dismount his dragon, engaging the player on foot as his dragon circles above.  Once circling, Vaz's dragon should begin periodically bombarding the players with an Area of Effect fire attack.
![Screenshot 2024-03-14 235700](https://github.com/WoWManiaUK/Redemption/assets/94846928/2e451a44-c2f1-4e74-8d4b-2b13ac7f34f1)
![Screenshot 2024-03-14 235554](https://github.com/WoWManiaUK/Redemption/assets/94846928/bb4dac59-cd0e-4bc4-a8f5-1bbeaf2e4b6c)
![Screenshot 2024-03-14 235546](https://github.com/WoWManiaUK/Redemption/assets/94846928/08749161-707b-42ee-a559-173e9bc9e288)

**Comment by Maine1** [comment]
Hello @Chipmunk1999 I see from the video you posted you didn't kill the 2 elites right before the boss encounter. These 2 mobs are what trigger this boss encounter. Please make sure to kill those in future to avoid any disruption.
