### ISSUE TITLE
[Spell] Inner Focus - effect consumed from almost any action

### ISSUE THREAD

**Issue by Woofles** [WoWManiaUK/Redemption#6209]
[Inner Focus](https://www.wow-mania.com/armory/?spell=14751)

**What is Happening:**
Currently the spell effect is consumed from almost any action and not just spells that cost mana/ can crit:
- Using items from inventory : Eating, placing fish feast, using heartstone or mall/arena stones, consuming potions/flasks, learning recipes,
- Mounting, summoning companion pets, 
- Using trinket's [Use] effect
- Using a wand [Shoot ](https://www.wow-mania.com/armory/?spell=5019). (Works fine for autoattacks even if a trink like [Mirror of Truth](https://www.wow-mania.com/armory/?item=40684) procs.)
- Tradeskill actions - crafting potions, fishing, campfire, etc.
- Unequiping the icc rep ring. (all worked fine for the rest of the gear I had available be it set pieces, trinks or other)
- Racial skills

**What Should happen:**
The spell effect should only be consumed when using class specific spells idealy those that either have a mana cost or are able to crit.

**Comment by Echinaceax** [comment]
Thanks for reporting @Woofles 

Confirmed bugged 
https://i.gyazo.com/b7c5464cfccbf254d4aa0f02c33aba5d.mp4
https://i.gyazo.com/5797837121f8df2684cb59cedf9e0ce4.mp4

**Comment by Lumber-Jack-2** [comment]
added some proc flags, should be better now

**Comment by Echinaceax** [comment]
Not fixed @Rushor 
still the same
