### ISSUE TITLE
[Item] Scourgebane Infusion - is suppose to stack with flasks but it doesn't.

### ISSUE THREAD

**Issue by L0dos** [WoWManiaUK/Redemption#6210]
**Links:**https://www.wowhead.com/wotlk/item=22778/scourgebane-infusion#comments

**What is Happening:**
Not stacking with flasks.

**What Should happen:**

Should stack with flasks.
![Screenshot_1](https://github.com/WoWManiaUK/Redemption/assets/33573664/dca63ac7-f005-4e6c-944a-7d2d00663edf)
Comment from 2010 patch 3.3.5 under the link saying it stacks.

**Comment by Echinaceax** [comment]
Thanks for reporting 
I remember seeing this while testing the other.

@Rushor 
Exact same fix you did for #6189

**Comment by Echinaceax** [comment]
Fixed in PTR 

Scourgebane Infusion / Scourgebane Draught / Onslaught Elixir
Scourgebane Infusion / Scourgebane Draught / Mighty agility
https://i.gyazo.com/a85e087391feb9eb8c48a63ed391de6e.mp4

**Comment by Echinaceax** [comment]
@Rushor 
this fix has broken again some how 
needs re-fixing again 

checked on Live and on PTR

**Comment by Rushor** [comment]
yes fix was not applied - is refixed now

**Comment by Echinaceax** [comment]
> yes fix was not applied - is refixed now

better thanks @Rushor 

![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/151cfff5-2d98-4bea-97b9-6661f0e2c743)
