### ISSUE TITLE
Design: Infused Twilight Opal

### ISSUE THREAD

**Issue by robertgf1** [WoWManiaUK/Redemption#6212]
https://wowpedia.fandom.com/wiki/Infused_Twilight_Opal**

Anub'arak does not drop the design.

Anub'arak should have a 100% chance of drop since I am a Jewelcrafter (maxed out).

Four runs (yes, they were done on heroic) and he still does not drop the design.

![WoWScrnShot_032524_111504](https://github.com/WoWManiaUK/Redemption/assets/25205678/c6fe34c7-077d-45d0-a9ee-1f69f0e2382c)

**Comment by WhitephoenixTheBunny** [comment]
I haven't found any source telling it _should_ be 100%, but all the other recipes (I think I did check all :D) that drop at 100% , and this one 12%

**Comment by robertgf1** [comment]
5th run, No design
![WoWScrnShot_032624_101413](https://github.com/WoWManiaUK/Redemption/assets/25205678/05b369b3-9e69-4fcb-aa56-5627240dda08)

**Comment by WhitephoenixTheBunny** [comment]
Did you got all the other boss drops?

**Comment by WhitephoenixTheBunny** [comment]
just posting here a link that might be useful  for later: https://www.ownedcore.com/forums/world-of-warcraft/world-of-warcraft-guides/239509-all-bop-jewelcrafting-northrend-recipe-locations.html

**Comment by Lumber-Jack-2** [comment]
should be 100 percent yes, we will make it like the other drops 

for Anub'arak - Heroic

**Comment by Echinaceax** [comment]
fixed in PTR 

![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/43ea5092-f4b3-49f5-b345-f1465de27a0e)
