### ISSUE TITLE
Shy-Rotam - Winterspring

### ISSUE THREAD

**Issue by theejynx** [WoWManiaUK/Redemption#6213]
**Links:**
https://www.wowhead.com/classic/quest=5056/shy-rotam

**What is Happening:**
This is a quest that requires the collection of an item to summon an NPC. Once the NPC is summoned, you kill the NPC and the add (Her mate, Sian-Rotam), then return to Winterspring to speak to "Storm Shadowhoof" to turn in. 

Everything save for the last part went very smoothly. However, now when speaking with Storm Shadowhoof on my alts, it does not allow the quest to be turned in. According to my log, the quest is complete. There was no item to be collected from the NPC once killed.

![Screenshot 2024-03-31 114329](https://github.com/WoWManiaUK/Redemption/assets/72872218/94daaffa-76e3-4dbd-a34b-2c4a73cfd206)
![Screenshot 2024-03-31 114301](https://github.com/WoWManiaUK/Redemption/assets/72872218/e03d8de0-28fe-481f-8ead-0d4d5810b113)

**Comment by GMZinius** [comment]
Thank you for reporting @theejynx 
We will look into the issue

**Comment by Maine1** [comment]
Quest works perfect for me just checked  this on PTR. 
![image](https://github.com/WoWManiaUK/Redemption/assets/122736582/3cfae364-c926-4bf2-a9c7-88d1a3044362)
![image](https://github.com/WoWManiaUK/Redemption/assets/122736582/f6c1cf15-faeb-4317-a760-cb14424e950d)

**Comment by Maine1** [comment]
Special note. There is a hidden objective in this quest which is complete when you place the Sacred Frostsaber Meat on the rock. This will need to be placed for all characters for the quest to be completed. This is a solo quest not a group quest which requires all characters to place the meat on the rock as this is not shareable 
![image](https://github.com/WoWManiaUK/Redemption/assets/122736582/8d993f88-2a95-45aa-a938-3e3aa08eed47)
This is what you end up with if you don't place the meat and complete the hidden objective in this quest
