### ISSUE TITLE
[Object] Iron deposit - Badlands

### ISSUE THREAD

**Issue by kanimestari** [WoWManiaUK/Redemption#6214]
**Links:** https://www.wow-mania.com/armory/?object=1735

**What is Happening:** iron deposit is inside huge stone and cannot gather with mining skill. The spot for minimap is 15.43, 81.36

**What Should happen:** deposit need to spwan other location.

**Comment by Maine1** [comment]
Objects spawned inside rock. 

![image](https://github.com/WoWManiaUK/Redemption/assets/122736582/2624d3c9-850f-4816-b8ce-a40ad56fc432)
![image](https://github.com/WoWManiaUK/Redemption/assets/122736582/24a8c408-f66d-45f7-82fd-25a6752d0319)
![image](https://github.com/WoWManiaUK/Redemption/assets/122736582/c72d9dcc-6787-4af3-b7dd-0d06564c02d2)


ID'S to be removed / position changed are as follows - 

- [x] GUID 71090
- [x] GUID 71091
- [x] GUID 71092
- [x] GUID 71093
- [x] GUID 71094

![image](https://github.com/WoWManiaUK/Redemption/assets/122736582/d9d708fb-7040-4d8b-aca1-323a581088fe)
![image](https://github.com/WoWManiaUK/Redemption/assets/122736582/5b94ba03-776f-4329-b7a0-f9fd74e2c733)

**Comment by Lumber-Jack-2** [comment]
thanks will do!

**Comment by Lumber-Jack-2** [comment]
position moved a bit to better place

**Comment by Echinaceax** [comment]
Fixed in PTR 

Iron deposit, Mithril deposit, Truesilver deposit, Gold vein, Silver vein have been moved from inside the big rock
![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/f535977b-6bcb-4dfa-9034-512277b5885b)
