### ISSUE TITLE
rogue off hand poison dont apply to boss after DBW effect goes off

### ISSUE THREAD

**Issue by thechillmaster** [WoWManiaUK/Redemption#6215]
rogue off hand poison dont appy to boss after DBW effect goes off

here some screenshots
![WoWScrnShot_040224_213342](https://github.com/WoWManiaUK/Redemption/assets/162306260/0195fdc8-baeb-431f-ac55-872dc1d4dbb0)

middle of fight after dbw pop or fell off happens

**Comment by Maine1** [comment]
Hello @thechillmaster is this happening with DBW HC or NM version? I checked before with DBW proc and it still applies with DBW procs. I am now check after the proc with both DBW HC and DBW NM. Videos to follow

**Comment by Maine1** [comment]
https://mega.nz/file/tzJk0YLY#WXdV69FKqWOJOIRLKxOwO8oryrhNrq6VPfwWVcMVD64
https://mega.nz/file/t6xxDK7D#57WkgwU80W16Qh2uNgHg7leBJzBPfYr1m8-KCkZjZtk

2 videos above 1 with DBW HC & other with DBW NM. Both applying poison on proc and after proc. There is a time at rogue that poisons have a chance to not apply and even drop off. I play an almost bis rogue myself. Happened to me many times. I suggest using shiv as a higher apply chance if you fear poisons dropping off.

![image](https://github.com/WoWManiaUK/Redemption/assets/122736582/246d79d7-58ec-4671-87ff-d2bf847a4171)

**Comment by Maine1** [comment]
@thechillmaster If you feel like I have missed something in testing this please reach out to me on this report for specifics of what you want me to check further. From my investigation I see this as working.

**Comment by Maine1** [comment]
Further to what I mentioned above I don't actually see you with poisons buffs on your weapons. 
![image](https://github.com/WoWManiaUK/Redemption/assets/122736582/92898cc3-4e52-4eec-8cab-d03617e5ad09)

My video Has the buff for poisons on. 
![image](https://github.com/WoWManiaUK/Redemption/assets/122736582/89befd7e-e024-461b-ad1c-a7de0ce24819)

This might be a clear indication why they didn't reapply.

**Comment by thechillmaster** [comment]
![Uploading WoWScrnShot_040524_185006.jpg…]()

**Comment by thechillmaster** [comment]
it happens randomly , and i only have dbw normal 
i notice when DBW effect wearoff this happens

yes i uploaded wronge one going to load other one i ssed atm

**Comment by thechillmaster** [comment]
in totall raid time it only happens 3 4 times , and have to either /sit or back off and load range then re engage

**Comment by thechillmaster** [comment]
![Uploading WoWScrnShot_040524_185006.jpg…]()
this one

**Comment by Maine1** [comment]
You still Don't have poisons buff on any of those.

As mentioned also 3-4 times happening this can happen and happens to me more times then that actually in icc hc. I try to use shiv in downtime to make sure it doesn't drop all stacks
