### ISSUE TITLE
same problem with rogue poison

### ISSUE THREAD

**Issue by thechillmaster** [WoWManiaUK/Redemption#6216]
**Links:**
![WoWScrnShot_040524_185006](https://github.com/WoWManiaUK/Redemption/assets/162306260/7ed998c7-49d5-4809-bf1c-7b9db3a81851)

i uploaded wronge ss 

so here the right one, closed my thread before i can answer so 3rd time maybe the charm

the effect happens 4 5 time a raid ,u either /sit or use range to get back weapons

**Comment by Maine1** [comment]
have you watched the videos I provided in the previous report? This is the 3rd report about this. I have tested with DBW nm and DBW HC on those videos and you see the poison still proccing after DBW procs and wears off.

**Comment by thechillmaster** [comment]
i said it happens randomly and not same time and during the fight some times ( doing 12 bosses and happens) . not happening all the time

if you can read what i said that would be great

**Comment by Maine1** [comment]
I'm not here to be moaned at or accused of not reading what you said. I read very clearly what you said. I am stating the facts that poisons are still applying after DBW procs wear off. Which is your initial statement and reason for Reporting. This is not the case and it is still applying after DBW proc wears off. My testing from what I can see has been completed and fully checked for what you are reporting. Is there anything I missed that you would like me to check before closing?

**Comment by Maine1** [comment]
For future reports 
![image](https://github.com/WoWManiaUK/Redemption/assets/122736582/69470b05-41c5-43ee-a014-343c8e377ca8)

46% chance. Although this is high it can still fall. to avoid use deadly poison IX on both weapons or use Shiv before deadly drops off!

**Comment by Maine1** [comment]
Further to initial testing I wanted to be sure I didn't miss anything. So i did a 6:15 fight proccing all DBW buffs to check all the evidence. 
![image](https://github.com/WoWManiaUK/Redemption/assets/122736582/4778755f-a55e-41a2-bd95-8cc25689b703)
![image](https://github.com/WoWManiaUK/Redemption/assets/122736582/4982d185-719d-45f5-b86a-8216f880af01)
