### ISSUE TITLE
Massive FPS Drop on LK25HC harvest Soul, Horde side

### ISSUE THREAD

**Issue by theonykry** [WoWManiaUK/Redemption#6217]
**Links:**

**What is Happening:**
As the whole raid gets sucked in, once everybody is inside the FM room, the FPS drop to 5 for every single member in the raid. Its basically impossible to move, kill spirits and heal.
I have no idea what part of the mechanic causes it, but it makes it unplayable, specially because LK enrages if somebody dies inside killing tanks once we leave the room and if tanks survive, you cant kill LK because to many DPS are lost and you hit enrage timer of LK

**What Should happen:**

**Comment by Maine1** [comment]
I think the GM's know about this and they have already fixed it

**Comment by GMZinius** [comment]
Thank you for reporting this issue @theonykry 
The fix has gone to live this morning.
fps is now at 56-60 

![throne room 56-60 fps on live](https://github.com/WoWManiaUK/Redemption/assets/108176634/80fea7a0-8fc7-43ad-a807-2ca0ecbf4242)
