### ISSUE TITLE
[Spell] Call of the Wild - isn't buffing the pet.

### ISSUE THREAD

**Issue by L0dos** [WoWManiaUK/Redemption#6218]
**Links:**

https://www.wowhead.com/wotlk/spell=53434/call-of-the-wild
**What is Happening:**
Call of the Wild is only buffing the hunter not the pet.

**What Should happen:**

Should buff the pet along side the hunter.
![Screenshot_1](https://github.com/WoWManiaUK/Redemption/assets/33573664/4e35e2ad-76fd-4a28-b8cb-ca3b5791ef5d)
![Screenshot_2](https://github.com/WoWManiaUK/Redemption/assets/33573664/3c4ceaef-4731-4bb3-bc46-aef0fb353e7f)

**Comment by Maine1** [comment]
Only applies the buff to the Hunter.

**Comment by Echinaceax** [comment]
fix confirmed on PTR https://i.gyazo.com/5d926ef45e8cdf41f06d082b71fc6a0d.mp4

Hunter 

![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/c8739223-ce1a-4d49-87be-ae723904fba4)

Pet 

![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/2af48499-2b32-4b4c-a0fb-5194db8d3f6b)
