### ISSUE TITLE
Scourgebane Infusion fix isn't implemented and not working.

### ISSUE THREAD

**Issue by L0dos** [WoWManiaUK/Redemption#6219]
**Links:**
https://www.wowhead.com/wotlk/item=22778/scourgebane-infusion#comments

**What is Happening:**

**What Should happen:**

![Screenshot_3](https://github.com/WoWManiaUK/Redemption/assets/33573664/308d83b9-7df0-4a8c-a724-e8ea37424904)

**Comment by L0dos** [comment]
Are the fixes implemented as batches? Idk how the process works just wanted to know the progress been a couple weeks.

**Comment by Echinaceax** [comment]
> Are the fixes implemented as batches? Idk how the process works just wanted to know the progress as it has been a couple weeks.

this is fixed here https://github.com/WoWManiaUK/Redemption/issues/6210 @L0dos 
as with most fixes it is good the clear game cache once in a while after fixes are made.
the video on the fix shows it working that i did

after clearing your cache,  if your still having issues then list the names of the pots your having issues with
