### ISSUE TITLE
weapon improvement problem

### ISSUE THREAD

**Issue by JeanVernus** [WoWManiaUK/Redemption#6220]
**Links:**

Good evening

**What is Happening:**

I can't apply a lower wizard oil on an heirloom weapon, I tried several different oils and the error message remains the same "the target's level is too low" but it's not not true

**What Should happen:**
Thanks

**Comment by Maine1** [comment]
Can only enchant certain things on heriloom weapons.

**Comment by Echinaceax** [comment]
yes heirlooms only lvl 1 - can use anything that has 0 requirements
![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/c8e4e397-f7c5-4b1f-a295-9f47193c24fa)


https://www.wow-mania.com/armory/?item=20746

![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/755a509a-6e5f-4ece-af48-c517039f2f62)

![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/4c27c25b-08e9-45ca-a677-63a5c3dbafc1)

**Comment by JeanVernus** [comment]
Thanks so much for your response
