### ISSUE TITLE
[Item] Sun Scope -  is not giving +40 ranged haste rating.

### ISSUE THREAD

**Issue by L0dos** [WoWManiaUK/Redemption#6221]
**Links:**
https://www.wowhead.com/wotlk/item=41146/sun-scope

**What is Happening:**
Sun Scope is not giving +40 ranged haste rating.
**What Should happen:**
Once attacted to a 3.00 speed ranged weapon on a hunter attack speed should increase by 0.03 and steady shot cast time should be reduced by 0.02 seconds or multi shot cast time from 0.434 to 0.429. They all stay the same values.

**Comment by Echinaceax** [comment]
thanks for reporting @L0dos 

@Rushor 
no change with/without the scope 

![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/d58497e8-88e0-4414-ac7f-0e6665faf6b4)

**Comment by Rushor** [comment]
as is for now - since dbc value we are not changing anytime soon

**Comment by L0dos** [comment]
What do u mean by that? Is it something that would take a lot of time because it is a DBC value?
