### ISSUE TITLE
[Spell] Special pet attacks consumes 2 stacks of Kill Command instead of 1.

### ISSUE THREAD

**Issue by L0dos** [WoWManiaUK/Redemption#6222]
**Links:**

https://www.wowhead.com/wotlk/spell=64494/furious-howl
**What is Happening:**

Furious Howl consumes 2 stacks of Kill Command instead of 1.
**What Should happen:**

Should consume 1 stack like every other pet's signature move. Nothing in the change logs of Kill Command or Furious Howl suggests furious howl spell specifically consumes 2 stack of it like any information or guide online regarding the two. Toolbox of Kill Command says each special attack done by pet reduces the stacks by 1. I suggest u guys take a look at how Kill Command should work too. Will consume stack on Charge won't on Rapid, will consume stack on Cower won't on Dash. Idk how it should work on counting what is a ''special attack''
![Screenshot_1](https://github.com/WoWManiaUK/Redemption/assets/33573664/574a0f45-e678-472c-abc8-92a97bceab0b)
![Screenshot_2](https://github.com/WoWManiaUK/Redemption/assets/33573664/88a5501c-98f5-48d3-bf88-1b05b3bb0dcf)
![Screenshot_3](https://github.com/WoWManiaUK/Redemption/assets/33573664/edecb0c9-14e7-49da-aae1-a1ca5f990f1f)

**Comment by Maine1** [comment]
Confirmed it takes off 2 stacks instead of only 1. I used only kill command and then furious howl without anything else and it consumed 2 stacks leaving only 1 left. 
![image](https://github.com/WoWManiaUK/Redemption/assets/122736582/1eddbb6b-044b-4626-9b6c-90ab74356f61)

**Comment by Maine1** [comment]
@L0dos Until it is fixed using this macro together allows the use of Furious howl and keeps all 3 stacks on kill command since it uses it last. 
#showtooltip Serpent Sting
/cast Serpent Sting
/cast Rapid Fire
/cast Rabid
/cast Furious Howl
/cast Kill Command
/petattack

**Comment by GMZinius** [comment]
@fvicaria We do believe we are using the wrong ID for kill command 
Noticed in the DB that 34026 only has 3 modifiers

Conclusion is
- The 3 modifiers for 34026 that we are currently using (its an old one)
- The 211 modifiers was for the 34027 (2.5.1)
- The 229 modifiers was a patch hotfix for 60113 (3.4.0)

**Comment by fvicaria** [comment]
We will spend more time in future as it is not clear how to fix it without breaking orther mechanics.
