### ISSUE TITLE
[NPC] Whispering Wind - Bugged under ice 

### ISSUE THREAD

**Issue by GMZinius** [WoWManiaUK/Redemption#6224]
From Player report 

**Links:**
NPC Whispering Wind https://www.wow-mania.com/armory/?npc=30848

**What is Happening:**
NPCs are under the ice 
https://i.gyazo.com/99889963cc6d64ad00585a4411b93ff9.mp4

**What Should happen:**
- NPCs need raising up slightly, this could stop them dropping under the ice 

![image](https://github.com/WoWManiaUK/Redemption/assets/108176634/f84781b4-3d5c-4ed2-88d0-afb4cc7cbd7b)

**Comment by fvicaria** [comment]
Can you add the NPC guid please.
Nevermind I found them,
This is due to the map holes. We need to slight change position and reduce random movement.

**Comment by GMZinius** [comment]
DB GUID: 107618, current GUID 19246
DB GUID: 107619, current GUID 19443
DB GUID: 131557, current GUID 19445
DB GUID: 107620, current GUID 19444

DB GUID: 107614, current GUID 1147
DB GUID: 107617, current GUID 1188
DB GUID: 131547, current GUID 1264
DB GUID: 107618, current GUID 1355

**Comment by GMZinius** [comment]
Fix confirmed in PTR

Much better, thank you @fvicaria 
https://i.gyazo.com/18b743602ecc6c8673a3748724d81578.mp4
