### ISSUE TITLE
[Arena] Ring of Valor - Team rating loss after a win (disabling arena for now)

### ISSUE THREAD

**Issue by gingersdye** [WoWManiaUK/Redemption#6225]
**Links:**

**What is Happening:**
last night while doing arenas we killed a player and he left after he got killed. wewere killing the second person and arena match ended with a win for us and lost rating after a win TWICE. this has already happend before to let and mutticks but they did not report it at the time.

**What Should happen:**

what should happen. if you win you get rating and no loss of rating

**Comment by Echinaceax** [comment]
Confirmed bugged in Ring of valor arena 

**reproduce**
When 1 player dies and insta leave arena. then the win goes to a draw, and give the losing team. team rating and a team win, no personal rating or personal win

The team that is supposed to win loses Rating 

![drawn](https://github.com/WoWManiaUK/Redemption/assets/39439201/6fa51edb-723b-4514-b392-c05736c4bbc5)
![0 wins](https://github.com/WoWManiaUK/Redemption/assets/39439201/dc2ac1de-ddc6-4ccf-bd3d-4447a69193ad)
