### ISSUE TITLE
Felwood - Jadefire run

### ISSUE THREAD

**Issue by Gasnir** [WoWManiaUK/Redemption#6227]
**Links:**
![mania bug felwood](https://github.com/WoWManiaUK/Redemption/assets/36572924/74577bd5-7452-425f-bd94-46793b15bdcc)

**What is Happening:**
Jadrefire trickster casts a spell on me when it is allmost dead. and that turns me friendly to them and stops the fight and the trickster heals up fully and i need to start the fight from scratch.
i have tried this 5 times on 2 diffrent tricksters same story

**What Should happen:**
good question there, well it shouldnt turn me friendly to them, they make me flee right? that should be without it turning me friendly and stopping the fight.
And that mindcontrol should only works when in a party. the party member atacking the other party member/members.
i was on this solo

**Comment by Echinaceax** [comment]
thanks for reporting 
this is a duplicate report and was fixed here https://github.com/WoWManiaUK/Redemption/issues/5749 comments explain the fix
