### ISSUE TITLE
Disrupt the reinforments - demonic runestone/missing PLZ close this report

### ISSUE THREAD

**Issue by Gasnir** [WoWManiaUK/Redemption#6229]
**Links:**
![image](https://github.com/WoWManiaUK/Redemption/assets/36572924/41307c97-b3c1-438a-a8cd-c0f70d2dc12e)

**What is Happening:**
portal says missing demonic runestone see screenshot

**What Should happen:**
it should let me use the demonicrunes

**Comment by Woofles** [comment]
For future readers of this issue:
You need 4 each time (or 5 if I remember it wrong)
