### ISSUE TITLE
Auction house raising prices

### ISSUE THREAD

**Issue by Cinoril** [WoWManiaUK/Redemption#623]
When I place a stack of items in the auction house for 48 hours, after 24 hours the price of the stack goes up (for example, a stack of briarthorn that I posted for 10 gold went up to 100 gold). I have used the auction house NPCs from Silvermoon and Undercity I did try searching for this, but I found nothing. This is the first time I am posting an issue, so I apologize if it was there and I could not locate it.

    Are you using our client?   Yes and running 0 addons
    Are you using the latest Launcher?   Yes
    Did I include the operating system I am using? Windows 10
    Did I include the steps to reproduce the problem?  ^
    Include NPC/Item/Spell names (or IDs) from wowhead.com   N/A
    Be descriptive and precise. <
    DO NOT log multiple issues in one! <

**Comment by fvicaria** [comment]
cannot reproduce.
