### ISSUE TITLE
[Spell] Revenge with Unrelenting Assault – not updated to patch 3.3.5

### ISSUE THREAD

**Issue by Greywolf59** [WoWManiaUK/Redemption#6230]
Arms warrior talent [Unrelenting Assault](https://www.wow-mania.com/armory/?spell=46860) drops cooldown of [Revenge](https://www.wow-mania.com/armory/?spell=57823) to 1 second and Revenge can be spammed after a single dodge for about three times.
However with patch 3.3.5. the change was made that Revenge even with Unrelenting Assault can be used only once per dodge/parry/block.

https://wowwiki-archive.fandom.com/wiki/Unrelenting_Assault
https://wowpedia.fandom.com/wiki/Unrelenting_Assault#Patch_changes

**Comment by Maine1** [comment]
Confirmed with [Unrelenting Assault](https://www.wow-mania.com/armory/?spell=46860) drops CD on revenge to 1 second how it should. Revenge needs to disable itself from being used again after use. At the moment it is available for 4 seconds continuously after a block/dodge/parry
