### ISSUE TITLE
[NPC] Captain Melrache - Under map

### ISSUE THREAD

**Issue by KABALWARRIOR** [WoWManiaUK/Redemption#6232]
**Links:**

**What is Happening We cant see the npc captain merlech, is under the map...

**What Should happen:**

**Comment by GMZinius** [comment]
Please report bugs correctly. thank you 
https://github.com/WoWManiaUK/Redemption/wiki/How-to-Properly-Report-an-Issue

Npc 1665 was under the map, ive reset him for now

**Comment by Lumber-Jack-2** [comment]
Captain Melrache - i know that bug, the map there is wonky

changed the position of him to a better place in front of the tower

**Comment by Echinaceax** [comment]
Fixed in PTR 
Npc moved out of the tower

![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/41f8b9dd-3780-41be-88f7-0de79bbd92f2)
