### ISSUE TITLE
vote points

### ISSUE THREAD

**Issue by Gwynn1** [WoWManiaUK/Redemption#6233]
**Links:**

**What is Happening:** on you website i voted las tnite 7x and today 7xover 12 hour part and got 1 vote point not 14. fixit please. your dead takes too long to get RDF for emblems

**What Should happen:**i should get 7 vote token for each of the 7 votes you can do every 12 hours

**Comment by GMZinius** [comment]
Hello @Gwynn1 please take a look at how to vote from the Mania youtube channel
vote every 24 hours not every 12 hours 

The vote sites are not controlled by Mania, they are a 3rd party site and not managed by us

**Comment by Gwynn1** [comment]
voted in the past with no problems. dont insult me by thinking i cant figure out how to vote

**Comment by Gwynn1** [comment]
here we go. your website you vote every 12 hours just voted over 1 hour ago. here is a screen shot of trying to vote again
![Screenshot 2024-05-30 134753](https://github.com/WoWManiaUK/Redemption/assets/171275330/a77f7b05-44fa-45ff-9c1d-401bc6ef1d8f)

**Comment by Gwynn1** [comment]
im pretty reasonable. ive sunk time into your server. i will give a few hours to fix the problem,. after that i will delete and move to warmane

**Comment by GMZinius** [comment]
Hello @Gwynn1 Voting issue are not to be reported here 
this is for in game quest, Npc bugs
