### ISSUE TITLE
previous ticket  6233

### ISSUE THREAD

**Issue by Gwynn1** [WoWManiaUK/Redemption#6234]
**Links:**

**What is Happening:**please look at all my comments on this ticket

**What Should happen:**

**Comment by GMZinius** [comment]
Hello @Gwynn1 Plese refer to my previous reply #6233

**Comment by Gwynn1** [comment]
you are fucking useless

**Comment by Gwynn1** [comment]
why? you're wrong. you arent lifting a finger to solve my problem this server sucks donkey dick and its 
your fault
