### ISSUE TITLE
Level 80 Boost - "Kanotname"

### ISSUE THREAD

**Issue by Kanotspel** [WoWManiaUK/Redemption#6237]
**Links:**

Level 80 Boost - "Kanotname"
**What is Happening:**
Level 80 Boost - "Kanotname"

**What Should happen:**

Level 80 Boost - "Kanotname"

**Comment by Kanotspel** [comment]
Im not 100% sure how to "submit a ticket". I'm sorry if this was wrong :(

**Comment by GMZinius** [comment]
> Im not 100% sure how to "submit a ticket". I'm sorry if this was wrong :(

You made an in game ticket for this now @Kanotspel , 
Janitor's PROMO usually go through an in game ticket not here on Github
All fixed for you now
