### ISSUE TITLE
[Quest] ID: 12915 Mending Fences, Earthen Ironbane spawn amount incorrect

### ISSUE THREAD

**Issue by hawker357** [WoWManiaUK/Redemption#6238]
**Links:**
https://github.com/WoWManiaUK/Redemption/issues/5821
https://www.wowhead.com/quest=12915/mending-fences
https://www.wowhead.com/item=41506/granite-boulder
https://www.wowhead.com/item=41505/thorims-charm-of-earth
https://www.wowhead.com/spell=55818/hurl-boulder
https://www.wowhead.com/npc=29927/earthen-ironbane

**What is Happening:**
Using the granite boulder on the Stormforged Iron Gaint summons only 1 Earthen Ironbane.

**What Should happen:**
According to old wowhead comments and guides, the boulder should spawn between 2-6 earthen ironbane NPCs. This was discussed in the old issue too, so I would guess this is a regression issue.

**Comment by Echinaceax** [comment]
thanks for reporting @hawker357 
i remember this fix, it was done by Mfranca, who is no longer here.
definately was fixed back on the first report for it, will explain it to @Rushor thanks

**Comment by Echinaceax** [comment]
updated info
i checked this and it does randomly spawn 1-6 as the old report indicates https://github.com/WoWManiaUK/Redemption/issues/5821#issuecomment-1132162745

I got 1 - 3 - 4 on my test just now 
https://i.gyazo.com/19bb2be7c2191770e7c27caca02eed95.mp4

from the old fix, the only thing that Mfranca couldnt fix was the spawning merged together
