### ISSUE TITLE
Magram Clan Centaur reputation issue

### ISSUE THREAD

**Issue by D00MHaMM3R** [WoWManiaUK/Redemption#6239]
**Links:**
https://www.wowhead.com/classic/guide/neutral-faction-reputation-overview-wow-classic#magram-clan-centaur

**What is Happening:**
Gaining reputation up to honored (40/12000 honored), after that i get only negative reputation with the oposing clan.

**What Should happen:**
Gaining reputation up to Revered (11999/12000 honored). 
![WoWScrnShot_061124_201635](https://github.com/WoWManiaUK/Redemption/assets/107924275/1dc0ac5c-b124-440a-b8a4-8f7d5e4d74aa)

**Comment by Echinaceax** [comment]
thanks for reporting @D00MHaMM3R 
wowwiki https://wowwiki-archive.fandom.com/wiki/Magram_clan
wowhead comments https://www.wowhead.com/classic/faction=93/magram-clan-centaur#comments 

_"Sadistic I think, if there was no need to go any
further than friendly why let the rep get to honoured?"_
