### ISSUE TITLE
Nethermancer Sepethrea heroic Elementals

### ISSUE THREAD

**Issue by D00MHaMM3R** [WoWManiaUK/Redemption#6240]
**Links:**
https://www.youtube.com/watch?v=6ig6l5f86MI

**What is Happening:**
The infernals stay at the person atacking and deleting him in like 1.5 seconds (nearly bis tank with fire aura) 

**What Should happen:**
they should run around like in the video and dont delete ppl :D 

P.S You are able to kill it if u run like hell and dont let them catch up

**Comment by Echinaceax** [comment]
thanks for reporting @D00MHaMM3R 

on another fix, they wasnt staying to fight (that part we fixed) https://github.com/WoWManiaUK/Redemption/issues/5758#issuecomment-1086627768

But the function of these is:

Strategy
"She summons two [Raging Flames](https://www.wowhead.com/tbc/npc=20481) when pulled. These Flames are fire elementals that are immune to all forms of crowd control. They move slowly, and will **chase a randomly selected target**, leaving damaging trails of fire behind them. Their targets should flee, kiting them around the room. Every several seconds, the elementals will Hellfire around them, which should be avoided. After the Hellfire, **they will randomly change to a new target**."

So on HC she will spawn 3 

if you are solo in there they cant randomly switch to other players, as you see from the video i did from the other fix, i was alone there to, so yes they only have one target (you) 

on your video the player is a group, so yes they have other targets to go for 
https://www.wowhead.com/tbc/npc=19221/nethermancer-sepethrea
