### ISSUE TITLE
[NPC] Wounded Skirmisher - Gossip text quote missing

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Redemption#6242]
**Links:**
NPC https://www.wowhead.com/wotlk/npc=27463/wounded-skirmisher
Quest https://www.wowhead.com/wotlk/quest=12288/overwhelmed

![image](https://github.com/user-attachments/assets/bca577d2-462f-4a7f-9163-6e7b22767b82)
![image](https://github.com/user-attachments/assets/b705031a-3339-41da-8c41-1caf3266ed6b)

**What is Happening:**
Gossip text missing of player class and race

**What Should happen:**

Class or race should be displayed, not just a $c. or $r.

![image](https://github.com/user-attachments/assets/b7943558-f11c-4bb0-97f4-6441931ce089)

**Comment by fvicaria** [comment]
Was that db only?

**Comment by Echinaceax** [comment]
Fixed in PTR 
Quotes fixed, now say race and class 
![image](https://github.com/user-attachments/assets/9f73b337-eca2-45f0-a154-b51425d14dcb)
![image](https://github.com/user-attachments/assets/01c306ce-3d66-4b0b-b509-5285ed0b8bb9)
