### ISSUE TITLE
Stratholme Arthas Bug - NPC disappearing, extended glitchy roleplay, etc.

### ISSUE THREAD

**Issue by szbalko** [WoWManiaUK/Redemption#6243]
**Links:**

**What is Happening:**

About 99.9% of the time when we get into "The Culling of Stratholme" RHC, Arthas bugs right at the start (occasionally throughout the dungeon as well). There's a variety of different occurences, sometimes he just stands idly and the player is not able to interact with him after starting the dungeon. Other times the dungeon seems to start normally, but then Arthas just disappears into nothingness and in order to be able to *actually start the dungeon* players have to open a GM ticket and the GM has to reset the instance. Very often even when you talk to "Chromie" and tell her you want to skip the roleplay, it'll start as such, but then Arthas appears at his original spot and start his long ass and glitchy roleplay session. Without GM interaction, the dungeon is UNPLAYABLE about 80% of the times.

**What Should happen:**

Please fix whatever causes the bugs mentioned above! These bugs are WELL KNOWN by the community and have been for a long while now. They very often cause impatient players to leave the dungeon group right after noticing that the random dungeon they got thrown into is Stratholme. The culmination of these bugs lead to an AWFUL player experience and very often a 10-15 minute time-wasting session when you have to tap-dance around with a GM asking them to start the dungeon for you. PLEASE. Please do something about this!

**Comment by Echinaceax** [comment]
thanks for reporting this @szbalko i remember the reason why this bugs its been reported a lot for alsorts of reasons.

https://github.com/WoWManiaUK/Redemption/issues/6038

after this fix was done, the only way he bugs on start is if a player tries to start the event when they havent completed the quest.
So as long as a player that has already completed the quest (explained in the other fixed report) then all is fine

**Comment by GMZinius** [comment]
> 
> **What Should happen:**
> 
> The culmination of these bugs lead to an AWFUL player experience and very often a 10-15 minute time-wasting session when you have to tap-dance around with a GM asking them to start the dungeon for you. PLEASE. Please do something about this!

I would like to remind you that GMs never reset dungeons (only reset NPC, when it is possible) let alone to "have players needing to tap-dance around with a GM asking them to start the dungeon for you"

I have been online all day and only received your ticket after the NPC reset himself after 15 mins as you told me. 

As you see above with the tester @Echinaceax, she has stated the reason for the bug. so make sure that the group does the quest needed for the dungeon to work correctly, or at least the person that has completed the quest is the one to start the event.

Thank you

**Comment by fvicaria** [comment]
99.9% of time.
Would close bug again purely for erroneous info.
