### ISSUE TITLE
[Quest] The Exorcism of Colonel Jules - Colonel Jules flies out the side of the building

### ISSUE THREAD

**Issue by stealer0517** [WoWManiaUK/Redemption#6245]
https://www.wow-mania.com/armory/?quest=10935
https://www.youtube.com/watch?v=eoknRTJ2MY0

About half way through the quest Colonel Jules stars floating around on his bed and eventually the room.
Instead he floats right through the side of the wall, and under the ground outside.
Also the Darkness Released creatures should spawn and immediately attack you or Anchorite Barada.

Colonel should float around _inside_ the room, the Darkness should attack you.

**Comment by GMZinius** [comment]
Hello @stealer0517 thank you for reporting this
However please alway search if an issue has already been reported/fixed before making a new report. 
This has been reported and fixed here #5467 if the fix that has been applied did not fix the floating issue then the old report needs to be looked into. 

I will close this new one and re-open the old.
