### ISSUE TITLE
[NPC] Horde Auctioneer missing in the Deathrun room

### ISSUE THREAD

**Issue by GMZinius** [WoWManiaUK/Redemption#6246]
**Links:**
Auctioneer Cain 2 https://www.wow-mania.com/armory/?npc=15682

**What is Happening:**
Recently player suggestion/request states that there is only an Alliance Auctioneer in the Deathrun and no Horde

**What Should happen:**
- There should be an Alliance and a Horde Auctioneer (for fairness) 

Note:
The Alliance Auctioneer is none attackable, so please set Auctioneer Cain that I have spawned on PTR to the same 
none attackable setting same as the Ally NPC Auctioneer Chilton 2 of the Deathrun https://www.wow-mania.com/armory/?npc=8670

![image](https://github.com/user-attachments/assets/5efb938b-7d1d-420c-86d2-89bf51bbb3f7)

PTR GPS 

![image](https://github.com/user-attachments/assets/3a20df5a-9c9a-4d95-9fc9-b14c57c336bf)

**Comment by Echinaceax** [comment]
fixed confirmed on PTR 

Auctioneer Cain tested and working 

![image](https://github.com/user-attachments/assets/c1d5293e-cae2-48a5-9e4d-6d6375b42911)

tested non attackable 
https://i.gyazo.com/0ed865cf848b6f7ea70a138df15914b5.mp4
![image](https://github.com/user-attachments/assets/d151cfd0-1009-47ea-9ece-93ecc8687044)
