### ISSUE TITLE
Vote doesn't work!

### ISSUE THREAD

**Issue by Meowseph12** [WoWManiaUK/Redemption#6247]
**Links:**
https://www.wow-mania.com/account/voting

**What is Happening:**
for 4 days i've tried to vote every 12h,that means 28 vote tokens and on my profile are only 2 vote points please help me recover my voting points

**What Should happen:**
i should recover my points(maybe a little more,a compensation for the inconvenience)

**Comment by GMZinius** [comment]
Hello @Meowseph12 
This is not a bug on the server. the reason this happens is because you are voting every 12 hours, vote every 24 hours. 
So to fix this issue. do NOT vote for a full 24 hours to let the votes sites reset.

**Comment by Meowseph12** [comment]
all sites says that i can vote every 12h,please mention this somewhere. And still from 5 days ago i should have 35 vote points ( 7 sites x 5 days= 35) not 28(sorry i misscalculate)

**Comment by Maine1** [comment]
> all sites says that i can vote every 12h,please mention this somewhere. And still from 5 days ago i should have 35 vote points ( 7 sites x 5 days= 35) not 28(sorry i misscalculate)

If you check on the WoW-Mania discord or youtube there is a video to state to only vote every 24 hours :)
