### ISSUE TITLE
[Item] Fissure Plant - drops from wrong container

### ISSUE THREAD

**Issue by Woofles** [WoWManiaUK/Redemption#6248]
**Links:**
https://www.wow-mania.com/armory/?item=5066
https://www.wow-mania.com/armory/?object=3743

**What is Happening:**
Fissure plant food should only drop from the Fissure plant container and not from the two Captain's Chest in Halls of Reflection.

**Comment by Echinaceax** [comment]
fixed in PTR 

normal mode / heroic

![image](https://github.com/user-attachments/assets/841a9c50-08e9-4f9c-805d-b16a663346b6)

![image](https://github.com/user-attachments/assets/c72534a2-0368-4499-b7bc-1f7a90ab4172)
