### ISSUE TITLE
Voting Points don't come

### ISSUE THREAD

**Issue by dex672** [WoWManiaUK/Redemption#6249]
The voting points in my account named Dex never comes to my inventory. I missed like 2 days of voting and did not get any voting point as of the moment i hope you fixed this

**Comment by GMZinius** [comment]
Hello @dex672 
This is not a bug on the server. the reason this happens is because you are voting every 12 hours, vote every 24 hours.
So to fix this issue. do NOT vote for a full 24 hours to let the votes sites reset.
