### ISSUE TITLE
[Quest] Tremors of the Earth - Pillar Opal and Pillar Amethyst Missing

### ISSUE THREAD

**Issue by eugeniu60** [WoWManiaUK/Redemption#6250]
Missing: Pillar Opal and Pillar Amethyst from the quest Tremors of the Earth part 2

**Comment by Maine1** [comment]
Hello @eugeniu60 I have checked this quest on PTR and the pillars are there. Let me provide you with a screenshot of their locations. 

![image](https://github.com/user-attachments/assets/88914f43-4d55-460a-85ef-b2903b659344)

**Comment by Maine1** [comment]
Confirmed - Opal Pillar and Amethyst pillar missing on live. Active on PTR. 

![image](https://github.com/user-attachments/assets/e43922e4-90e3-46df-b12b-8d8ff4f991a4)

![image](https://github.com/user-attachments/assets/9fef0206-fa50-43bc-a87d-6356f1348b51)

![image](https://github.com/user-attachments/assets/2b2cd83e-2cd3-49dd-ab16-c5f86f4f1931)

![image](https://github.com/user-attachments/assets/0fa9024b-ed2d-46a4-8a1a-3475c21c33b9)

**Comment by Maine1** [comment]
@Rushor this will be something that needs copying from PTR to live. We cannot test on PTR as this is working there.

**Comment by fvicaria** [comment]
PTR and live are exact the same.
This is potentially a despawn issue. I have never heard of this quest being bugged.

Get the guid of the two objects in ptr and try to go to it on live.
Just add the guids here on the report.

**Comment by Echinaceax** [comment]
> This is potentially a despawn issue.

Reproduced on PTR (2 chars)

quest Tremors of the Earth https://www.wow-mania.com/armory/?quest=717
pillar of opal https://www.wowhead.com/classic/object=2848/pillar-of-opal
pillar of amethyst https://www.wowhead.com/classic/object=2858/pillar-of-amethyst

1. for player A, Pillar of Opal and Pillar of Amethyst are there, but despawn after player A has activated and collected them
2. for player B, Pillar of Opal and Pillar of Amethyst do not respawn for player B 

Pillar of Diamond is fine https://www.wowhead.com/classic/object=2842/pillar-of-diamond ✅ 

**What should happen**

- [ ] Pillar of Opal and Pillar of Amethyst, should not fully despawn. they should function same as the Pillar of Diamond.
https://i.gyazo.com/fb4b78c09a1bab925d52d4cfbfbabdaf.mp4

note tho they are here with GM on for player B https://i.gyazo.com/2feb2ef02f6adeacdaedff070259c6b8.mp4

edited
just noticed they have respawned after 1 hour on PTR 😄

**Comment by fvicaria** [comment]
Fixed in ptr.

**Comment by Echinaceax** [comment]
> Fixed in ptr.

confirmed fixed 😄 thanks jani 
https://i.gyazo.com/ef1ec25e712ce5dae7cf4982d855e139.mp4

![image](https://github.com/user-attachments/assets/609b4c9d-c066-496a-809f-c4d02285d148)
