### ISSUE TITLE
Corruption not critting on Demo Lock

### ISSUE THREAD

**Issue by theonykry** [WoWManiaUK/Redemption#6254]
**Links:**
https://www.wow-mania.com/armory/?spell=47813

**What is Happening:**
On my demo lock, my corruption spell is not critting even tho i have +32% spellcrit. the other warlock's corruption (affliction) is critting
If it was only 1 encounter i could have said okay its really, really bad RNG, but it happend on multiple fights. his is clearly a bug. I add the Screenshot of 1 halion 25NM encounter, can provide more if needed.

**What Should happen:**
both corruptions should crit. My guess is that if the first tick doesnt crit, then it doesnt roll the critrate chance again for the whole duration till it is reapplied. A similar bug once existed on shadowpriest's spell "shadowword: Pain"
![boost](https://github.com/user-attachments/assets/42f0005c-71e2-4b23-ba0d-0adb62c78cb0)
![boost2](https://github.com/user-attachments/assets/52aac69c-c9da-4450-b876-648c31c1c022)
![shadows](https://github.com/user-attachments/assets/2e68cf6f-6857-4d80-81d4-d60eaa504392)
![shadows2](https://github.com/user-attachments/assets/fc5bd8d0-8adc-4ad5-92c5-481f3e357c76)
![stats](https://github.com/user-attachments/assets/fcbdff14-cb76-43b8-8148-8d8a4a245f6d)

Im aware that the talent Pandemic is increasing corruption crit dmg by 100%, but corruption should be able to crit either way

**Comment by Maine1** [comment]
I have done loads of testing on PTR and all I can see is that criticals from Corruption are effected by Pendemic 
https://wotlk.evowow.com/?spell=58435
![image](https://github.com/user-attachments/assets/946879c9-ea24-4d44-b631-36ea9aa35b09)
Apply Aura: Allow Periodic Ability to Crit (12)****

Does not crit on demonology or destruction without Pandemic talent
![image](https://github.com/user-attachments/assets/8c4377e6-375b-4ce4-b24a-ebd7733b9d34)

Corruption ticks will not be critical strikes on its periodic damage without Talent - Pandemic.
