### ISSUE TITLE
Felguard pet being affected by crowd control of owner

### ISSUE THREAD

**Issue by theonykry** [WoWManiaUK/Redemption#6256]
**Links:**

**What is Happening:**
The Felguard pet is being affected by status effects the caster/owner is affected by.
Examples:

If the warlock is affected by Hand of Protection of a paladin, the Felguard cant attack.
If the warlock is dazed, the Felguard moves slowly too

Same things happens with roots and stuns.

I dont know if Soul Link has something to do with it

**What Should happen:**
Felguard should not be affected

**Comment by Echinaceax** [comment]
thank you for reporting @theonykry 
we will test this out to confirm

**Comment by Maine1** [comment]
I have checked all this with @Echinaceax, checked the Hand of Protection and my pet was still attacking without any issues with Soul link on. 
![image](https://github.com/user-attachments/assets/47b45d11-0cd9-4eff-ba28-e97f9e4b6118)
Checked entangled roots this also didn't effect pet.
![image](https://github.com/user-attachments/assets/8fc91d09-e70e-4b06-8859-ab45ef6a5e9f)
 We used hammer of justice for a stun and pet was not effected also.
(without soul link)
![image](https://github.com/user-attachments/assets/3453f83c-f617-48df-9463-68730a532992) 

 (with soul link)
 ![image](https://github.com/user-attachments/assets/20fe0c0b-574f-469c-9b40-b6e90d0d3db9)

**Comment by GMZinius** [comment]
Thank you @theonykry for reporting this issue, please make sure you are using the wow-mania client as the testers cannot reproduce the issue that you have discribled.

**Comment by theonykry** [comment]
i updated the game and the issue disappeared
