### ISSUE TITLE
[NPC] Wood mite - Render distance issue stopping them despawning

### ISSUE THREAD

**Issue by Woofles** [WoWManiaUK/Redemption#6257]
**Links:**
Wood mite - https://www.wow-mania.com/armory/?npc=22419
https://www.wowhead.com/wotlk/npc=22419/wood-mite#comments:id=130601
Infested Root-Walker - https://www.wow-mania.com/armory/?npc=22095
Rotting Forest-Rager - https://www.wow-mania.com/armory/?npc=22307
![image](https://github.com/user-attachments/assets/c82a08d1-554f-4202-863c-495975a58903)

**What is Happening:**
The mites stay for at least twice the respawn time of an Infested Root-Walker (one of the npcs that spawns them) or at least too long for them to despawn while the player is nearby.
At one point while farming them (for motes of life) I saw 3 groups still alive at a place where only one tree was spawning.

**What Should happen:**
they should have a very short despawn time , I guess shorter than the respawn time of Infested Root-Walker and Rotting Forest-Rager

**Comment by Echinaceax** [comment]
thanks for reporting @Woofles 
we will take a look at it

**Comment by Echinaceax** [comment]
from my test and research 

the Wood Mite spawn from the  Infested Root-Walker and Rotting Forest-Rager correct
as part of the quest  https://www.wowhead.com/tbc/quest=10896/the-infested-protectors 
Wood Mite spawn in 4-6 each spawn and are a level 1 mob (they do not attack) 

they have a duration timer of 5 mins 
https://i.gyazo.com/df54cbd23c56e100b4d5aea6f22559c9.mp4
mania 5mins https://www.wow-mania.com/armory/?spell=39130
wowhead classic 5mins https://www.wowhead.com/wotlk/spell=39130/summon-wood-mites
wowhead retail 3mins https://www.wowhead.com/spell=39130/summon-wood-mites

![image](https://github.com/user-attachments/assets/49cd26b4-811b-4ad6-bb93-b84eb2bc6278)
![image](https://github.com/user-attachments/assets/036ee48f-3942-40d5-a85b-a24a4fa9275b)


Ive the found the issue 
https://i.gyazo.com/8bbde97b816d209013ad5ed87982edbe.mp4

- [ ] NPC Wood Mite https://www.wow-mania.com/armory/?npc=22419
- [ ] Render distance issue again, if player goes out of render distance the despawn timer doesnt work until player is back in distance 
- [ ] Mania Wood mite's spawn grouped on top of each other, they should have seperate spawn points

![image](https://github.com/user-attachments/assets/5228b742-8ba3-4dda-86dd-901bede15f8c)
![image](https://github.com/user-attachments/assets/0e2eea28-0da2-453e-9938-5430f54ddf6f)
![image](https://github.com/user-attachments/assets/5fb12367-df6c-41ba-bc71-45e93f14a7ed)

Spawns should look like this seen here at timestamp 0:52 https://www.youtube.com/watch?v=GC9tNaAFeeg

![image](https://github.com/user-attachments/assets/2787119f-2571-4384-b0c2-27da3c59d74f)

**Comment by Echinaceax** [comment]
fixed confirmed in PTR 

1. mites spawn separently https://i.gyazo.com/a6e9dbf5ce66313dfc81f6e796058628.mp4
2. Render fix, despawn as they should after 5 mins https://i.gyazo.com/38fda2f8bd96322eb240206fa7bae493.mp4
