### ISSUE TITLE
Quest:  [In Dreams]

### ISSUE THREAD

**Issue by D00MHaMM3R** [WoWManiaUK/Redemption#6258]
![WoWScrnShot_092824_015106](https://github.com/user-attachments/assets/a99c2ae1-2842-473e-811e-0ce268a206c6)
![WoWScrnShot_092824_015104](https://github.com/user-attachments/assets/9ae541bb-79f9-49bc-a1b9-747ff77c5e1b)
**Links:**
https://www.wowhead.com/classic/quest=5944/in-dreams
**What is Happening:**
Starting the quest - its an excort. Acompaniing him for 15 mins till i need to kill few npc`s and after that he freezes. No quest complete or anything, he despawns after 2-3 mins

**What Should happen:**
Award quest complete :)

**Comment by GMZinius** [comment]
Thank you for reporting this @D00MHaMM3R 
For notes, I watched this player doing this quest myself, can confirm it is bugged.
I do see an old report https://github.com/WoWManiaUK/Redemption/issues/22 looks like it wasn't explained where in this role play he bugs.

**Comment by Maine1** [comment]
![image](https://github.com/user-attachments/assets/a7394b2e-83ce-4280-9656-fdd26a1211ff)
Retested this on PTR and did it also on Live to make sure it can be done after others have failed. 

To do this quest you need to remove the disguise when the NPC tells you to at the start and when you get to the Grand inquisitor you need to let him fight Taelan Fordring. after the Grand Inquisitor says Enough! he will attack you. (This part is very important) You need to attack him but don't kill him until Tirion Fordring comes to aid you and Tirion starts attacking the Grand Inquisitor too!  You and tirion can then kill him together and complete the quest!
