### ISSUE TITLE
[Achievement] "It's happy hour somewhere" - bugged tooltips

### ISSUE THREAD

**Issue by Woofles** [WoWManiaUK/Redemption#6259]
**Links:**
https://www.wow-mania.com/armory/?achievement=1833
![image](https://github.com/user-attachments/assets/b492ecd4-9ab0-41f4-8a75-ce59b4848a07)
![image](https://github.com/user-attachments/assets/ea0dfee1-3e56-4283-9890-e67e55d868fc)

**What is Happening:**
The tooltips for the achievement appear either multiple times or in French for some reason. 

**What Should happen:**
Only one bar  should appear and in the case of the default client text should be in English only.
No specific drinks should be listed.

**Comment by Maine1** [comment]
Shows the 0/25 3 times across the achievement in the achievement window. When you click on the achievement to look at it, has some language tooltips that shouldn't be there @Rushor
