### ISSUE TITLE
[Quest] Appeasing the Great Rain Stone

### ISSUE THREAD

**Issue by redhawk816** [WoWManiaUK/Redemption#626]
Moodle doesn't dig up the Shiny Treasures.  Need this quest to build up Oracle Rep. 

http://www.wowhead.com/quest=12704/appeasing-the-great-rain-stone

**Comment by redhawk816** [comment]
Not fixed....  only worked on the first Shiny.

**Comment by fvicaria** [comment]
Read the label. "Fixed in Dev". That means it is not released yet.
