### ISSUE TITLE
[Item] Eaglewatch - transmog rifle

### ISSUE THREAD

**Issue by bvh3d** [WoWManiaUK/Redemption#6260]
**Links:**
http://www.wow-mania.com/armory?item=150203

**What is Happening:**
Eaglewatch - I purchased this transmog item from the Mall some years ago but the visual effect is still broken so I decided to open this post - it is currently displaying a caster item visual instead of a rifle (gun) visual. When you transmog a ranged weapon with Eaglewatch and start shooting - your character start showing a casting animation instead of a rifle shooting animation. Hope the visual effect could be corrected. Thank you.

**What Should happen:**
It should display the correct rifle shooting animation.

**Comment by Echinaceax** [comment]
thanks for reporting @bvh3d 
confirmed https://i.gyazo.com/a99387b37b515419641a69bd4489822e.mp4

**Comment by fvicaria** [comment]
Transmogs are as-is. They are brought from later versions of the game and not always behave the same way as in the new version.
