### ISSUE TITLE
Gamestop100

### ISSUE THREAD

**Issue by savagesara** [WoWManiaUK/Redemption#6261]
**Links:**
I am an avid voter for wow-Mania. The Gamestop100 vote site has not worked for over 3 weeks now. 

**What is Happening:**
It claims that error 522 is happening. Connection issue. Someone should contact Gamestop100 and get them to fix this. We are missing out on a lot of votes.

**What Should happen:**
It takes our votes. We get credit for voting.

**Comment by GMZinius** [comment]
Hello @savagesara 
Github is for in game bugs only.
Voting sites are not controlled by Mania, the votes sites are 3rd party.

Note: even though a vote site hangs, it still rewards you your 7 vote points.

Please take a look at the voting steps on Mania discord #FAQ
