### ISSUE TITLE
Interface error

### ISSUE THREAD

**Issue by DM1983-10** [WoWManiaUK/Redemption#6265]
When trying to select my mage Fruitloop (lvl33) I get the error "Interface\gluexml\glueparent.lua:384:Usage: PlayglueAmbience("sound name", "(optional)fade in time")

edited by Echi

![image](https://github.com/user-attachments/assets/f6ecc690-473c-4587-991a-c19b98c4b018)

**Comment by Echinaceax** [comment]
hi @DM1983-10 
what client are you using?
did you download the wow-mania client?
looks to me like you have a missing file/corrupt file

also, no need to show your account info i cut the error message here for you 

![image](https://github.com/user-attachments/assets/7b16a02f-9148-4083-9398-4fa2ec6b2cef)

advice, maybe try a fresh client (save your Addons/WTF folder) somewhere then you can add them back to the new folder
https://us.forums.blizzard.com/en/wow/t/need-help-with-lua-error/940845

seems like an addon issue
