### ISSUE TITLE
my acount says account closed

### ISSUE THREAD

**Issue by craigy3369** [WoWManiaUK/Redemption#6266]
**Links:**

**What is Happening:**when iried logging in today and igot sign in password wrong 3 times wrong as  withh my illness i shake a lot
my account now  says acc0unt closed

**What Should happen:**

whyis it closedd

**Comment by GMZinius** [comment]
Hello @craigy3369 
Github is for in game bugs, not account issues. Please contact Janitor or a GM in discord.
Thank you.
