### ISSUE TITLE
The Oracles/Frenzyheart tribe quests don't show for me.

### ISSUE THREAD

**Issue by Tiky-horde** [WoWManiaUK/Redemption#6268]
**Links:**

I don't think I can provide links, because I don't have the quests. I can provide the frenzyheart and oracles without the yellow mark for quests, but I thought that has no value. (Sorry, first time reporting a bug, and I've read your rules). I can show a screenshot of the unaccomplished achievements about these tribes, or perhaps my current reputation with them? No idea what exactly would help this specific request, I'm sorry.

**What is Happening:**

I cannot continue the Oracles/Frenzyheart tribe quest chain. I was doing them for Frenzyheart but they stopped all of a sudden. This happened quite some time ago, possibly a month, so I can't remember the specific quest. I am 100% sure that no quests from the tribes exist, as I checked online for their locations and searched for them many times. I am certain it is a bug.

It happened around the switch from Frenzyheart to Oracles quest chain.

This is a problem only with my character [Tiky - Horde Goblin, Death Knight], since I haven't advanced so far with other characters to check if that happens with them too. It doesn't affect my gaming experience with anything else, so I've read the rules and know that's the lowest priority request, that's fine with me.

**What Should happen:**

The Frenzyheart/Oracles questchain should appear. If possible, I could start over the Frenzyheart quests - no problem for me. 

Thank you in advance and let me know if additional information of any kind would help. Again, this is not at all a time-sensitive issue for me.

**Comment by Echinaceax** [comment]
hi @Tiky-horde 
The is no bug with this questline.
please make an ingame ticket to the GMs and they will check where on the questline you are.

**Comment by Tiky-horde** [comment]
Thank you.

But how do I make this ingame ticket? I checked in the search here, and it doesn't show me anything about "ingame ticket".

**Comment by Echinaceax** [comment]
> But how do I make this ingame ticket? I checked in the search here, and it doesn't show me anything about "ingame ticket".

Click on the red question mark ❓ in game and click on "Talk to GM"

**Comment by Tiky-horde** [comment]
Wow, I never even knew this feature existed.

Thank you so much! Found it, will do that.
