### ISSUE TITLE
Heroic Lich King encounter issue.

### ISSUE THREAD

**Issue by Jalonewalker** [WoWManiaUK/Redemption#627]
Hello Janitor,  I have recently started playing again.  I have been leading the guild Bro in raids in both 10m and 25m heroics and have a made considerable progress. However. In the Lich King encounters on Heroic mode there are Noticeble malfunctions pertaining to the Valkyries in the 2nd phase.  Severe enough that it honestly not possible to defeat it as it stands currently.   The Valkyries are supposed to select a target player and come down and pick them up and proceed to drop the player off the platform. The mechanic is designed to Crowd control a valkyrie and dps it until it is at 50% heath at which point it supposed to drop that player back down.  After it drops the player it goes back up into the air and  it begins to cast an ability called "life Siphon" which is a "leeching" ability that does dmg to a player and heals itself. Which is where lies the primary problem, the Valkyries are immediately begining to cast "Life Siphon' even before they are at 50% which makes it literally impossible to get it's health to 50% in order for it to drop the player. We have tried every possible remedy as a group to try to work around this issue, to include single target "marked" focus dmg, with Bloodlust in order to try to force the phase, but even all our best attempts were inadequate to overcome the problem. This issue does exist on both 10 and 25 versions of the Lich King heroic encounters.                                       http://www.wowhead.com/spell=73488/life-siphon.

I hope you guys all have a Great Christmas, Thank you.

**Comment by wasser510** [comment]
Exactly our problem...
A bit disappointing to get that far and then not be able to do the final boss in this great instance.
I hope we experience a fix soon!

**Comment by Hotsome** [comment]
Couldnt agree more with ^^
Having a fix on those valkyrs would be a great Christmas present

Thanks for all your great work :)

**Comment by fvicaria** [comment]
There has been absolutely no change in this area for months and this has been working fine.
I need more details of how, when, any special details or situation during the event etc.

**Comment by wasser510** [comment]
It was allways not working fine, but since noone was at lk25hc to this point there were to changes made.
In 10hc you can push the phase and ignore the valks but that is NOT possible in 25hc (100m hp) and thats why lk on 25hc is NOT possible to kill without a GM assistance or a fix on the valks.

**Comment by Jalonewalker** [comment]
Thank you for the response.   The encounter may not reflect recent changes" according to your recent history or review, but the problem still exists. 

There has been absolutely no change in this area for months and this has been working fine.  
-working Fine according to who exactly?  I assure you that this ticket being generated is not just simply the result of  people whom don't understand the fight mechanics, or who are just "whining" about a fight that is difficult, but rather  honest observations and about the encounter.

We only ask that you re-examine the mechanics pertaining to the Vlkuries and when they use the abiltity mentioned earlier.
The few 25m groups that have encountered the 25m Heroic encounter faces the same issue. 

Concerning the 2nd part of your response:  requesting the following information

**HOW**:  The Valkyries are supposed to select a target player and come down and pick them up and proceed to drop the player off the platform. The mechanic is designed to Crowd control a valkyrie and dps it until it is at 50% heath at which point it supposed to drop that player back down. After it drops the player it goes back up into the air and it begins to cast an ability called "life Siphon" which is a "leeching" ability that does dmg to a player and heals itself. Which is where lies the primary problem, the Valkyries are immediately begining to cast "Life Siphon' even before they are at 50% which makes it literally impossible to get it's health to 50% in order for it to drop the player. 

http://www.wowhead.com/spell=73488/life-siphon.              Here is the wow-head link to the mechanic that in Not working properly when it;s supposed to.

WHEN:  At the beginning of the 2nd phase of the encounter (when the above fight mechanic takes place) And the Valkyries appear.

Thank you very much, Your Freind, Jalone.

If helpful, next attempt that we make, we will make a video of the encounter and be able to provide you with video as well if it would be helpful.

**Comment by Galagus420** [comment]
yes , please fix this, valkyries completely bugged

**Comment by Ganeshaaa** [comment]
please fix it!!!

**Comment by huqboss** [comment]
No changes because no1 reported it. In 10man good group with a lot of luck to picked players can push this phase, 25man encounter no1 did yet (except Synergy, but with GM's assistance, so doesn't count /spit)

**Comment by Skullpoopl** [comment]
Hello there.
I am a raider in BRO guild as Jalonewalker is...
*On WoTLK expansion of retail WoW i was a Main Tank ( Juggernut Orc DK , Twilight's Hammer 12/12 HC ) and never dpsed in ICC raid and i did never give much attention to what percentage of health you must get the Valkyries down so they drop the player and then go up in the sky...
I remembered just 1 day ago ( and to confirm this i re-watched all LK HC 1st kills Paragon and Method on Youtube ) that back then , the Valkyries should get dpsed down to 50% to leave the players down and after they left him they were starting casting Siphon Life always at <=50% health...Also the Siphon life deals about 2k damage and heals the Valkyrie for 10 times that amount...
*What i noticed in WoW-Mania server as a Retri Paladin were these things : 
 1) The Valkyries don't drop the player down if stunned 1-3 times in a row after diminishing returns lower the 2nd and 3rd stuns...instead they take him up in the sky when not even near 50% HP...
 2) Then the Valkyries do go up in the sky while holding that raid member and start immediatelly casting Siphon Life "regardless" of their HP percentage...some times i saw 1-2 even at 100% HP casting it...
 3) The Siphon Life doesnt deal 2k dmg and heals for 10x that amount( About 20k ) *BUT* they do deal about 18k-20k dmg and heal them for ~200k HP...
 4) The Valkyries as long as i can remember are Tauntable...that means that they work like a normal mob reacts to threat meters...What i noticed in the server was that even though they didn't get down to 50% they were casting it...and all the time switching targets around the raid...some times i saw them target 1 shaman healer do 2 siphon lives in a row and kill him...that fast...My question is if they hold the threat of the dpses...why if all stop dpsing them when going up in the air ( while still holding a raid member ) they still circle through random raid members even though they should stick to the 1 with the highest threat?
*Apart all these and believe me in retail we had at least 2 k less HPS and the average DPS was at least 4k lower than the one we do now [Small notice...when we killed LK back then the buff was only 15%] , there is literally no way taking down LK past the 2nd phase if a Valkyria is healing 200k / ~2 sec even with BL active and always at least 3 ppl up in the air being help by them offering nothing...
We tried this over and over and over again...and it took us only 2 hours tries to kill PP in HC ( which is considered more tactical and responsibility seeking boss ) and i wonder why we focus too much on LK who is considered a far less complicated and more Burst race boss...
The Valkyries simply render it impossible to even burst the hell out of LK even with BL and ignoring the Valks completely with this crazy bugged Valks...
Sorry for the long post but i think i cover all the LK 25 HC Fight bugs i could find...

**Comment by Emcitementz** [comment]
> The Siphon Life doesnt deal 2k dmg and heals for 10x that amount( About 20k ) BUT they do deal about 18k-20k dmg and heal them for ~200k HP...

The 25hc version of this spell never did 2k dmg, that's for the 10nm.
It should deal 4k6 to 5k3 dmg, that's not actually the case as the minimum is around 6k3 at the moment. This is going to be adapted.
Fixes are being tested.
