### ISSUE TITLE
Character stuck in the mall.

### ISSUE THREAD

**Issue by c-bowler78** [WoWManiaUK/Redemption#6270]
**Links:**

**What is Happening:**
I have a worgen warlock, character name is Nitewish and my account name is Trinitybob. I have teleported to the mall but now as soon as I load it my client hangs for about 2 minutes then I am kicked off the server back to the login screen. I have logged a ticket with my other character Laida and although I cannot be on discord for reasons beyond my control I was told to update my client which I have done. 

**What Should happen:**
There is no "Unstuck" feature on the web page after login so please change my Worgen location back to Teldrassell if possible. My other characters do not have any issue logging into the world so it is not a client problem. It is most likely a database issue.

**Comment by fvicaria** [comment]
not an issue for here.

**Comment by fvicaria** [comment]
PLayer went to mall without setting home. 
Also may not have latest client.
I have just logged and used portal with the char.
