### ISSUE TITLE
Critical error

### ISSUE THREAD

**Issue by Sakis72** [WoWManiaUK/Redemption#629]
Hello... I got a Draenai char named Gastone and when I try to log in the game a message pops up...
It's in the normal Redemption realm

![wow_critical error](https://cloud.githubusercontent.com/assets/24751925/21466651/57b1978c-c9da-11e6-9089-bed45f3868db.jpg)

**Comment by fvicaria** [comment]
This is a client error.
I am assuming you have our client with ALL patches. If not go get it. If you do, you need to modify your video settings:

![img_23122016_133148](https://cloud.githubusercontent.com/assets/9414661/21467166/60786bc8-c9dc-11e6-8488-d9ce861ebec4.png)

You can also play with the resolution to see what works best for you.

**Comment by Sakis72** [comment]
Issue got solved. I downloaded the enGB patch file , put it in the root Wow directory, & replaced the existing files there. Works ok now. Thank you
