### ISSUE TITLE
[Graphic Issue] Fury Warrior Off-Hand disappearing

### ISSUE THREAD

**Issue by WastedMoment** [WoWManiaUK/Redemption#630]
Not generally a huge issue, or one that effects fury warriors personally. But fury warriors offhand disappears as in the graphic of your weapon just isn't visible anymore. I've spent a good 40 minutes smacking a dummy to see if anything procs it and it seems like Bloodthirst has a small chance too but it primarily happens on death bringers will procs that the graphic of the offhand weapon just disappears. This happens on non transmogged, and transmogged weapons. Its not a big issue as we all have been experiencing this for a while but sometimes makes us feel like our offhand isn't equipped with it really is :D

**Comment by huqboss** [comment]
Very often disappear after death, then need just to switch to ranged and back to melee (with Z) then all back to normal

**Comment by WastedMoment** [comment]
Yes it can be temporarily fixed for a couple seconds with z until you hit combat again, No other server i play/played on has this issue and was seeking out if there was a permanent fix that might be coming?

**Comment by fvicaria** [comment]
This is a model issue and cannot be fixed server-side.
The issue was well know in retail WotLK.
Source: http://www.wowhead.com/item=50362#comments:id=1022691
