### ISSUE TITLE
[Achivement] Blade's Edge Bomberman

### ISSUE THREAD

**Issue by huqboss** [WoWManiaUK/Redemption#631]
Achivement http://www.wow-mania.com/armory/?achievement=1276 almost not doable here.
According to all guides to do this achivement due to long distance and cooldown on provided item (http://www.wow-mania.com/armory/?item=32456) you need to throw 2 bombs on 1 cooldown.
Details in comments on wowhead: http://www.wowhead.com/achievement=1276/blades-edge-bomberman#comments

On wow-mania when you start to cast 2nd bomb on same cooldown 1st is cancelled. High amount of casts ended with "failed" without any reason is also not helping. Even if you are lucky and get no failed casts you are short by 5-6 seconds to do this achivement without casting 2 bombs on 1 cooldown.

**Comment by Joblaisk** [comment]
Still a problem. Multiple casts end with failed or interrupted
