### ISSUE TITLE
[World] aggro range / aggro groups

### ISSUE THREAD

**Issue by iggapres** [WoWManiaUK/Redemption#632]
Hi,

Almost everywhere aggro range is messed up. More than aggro range is groups of mobs that come together when, then obviously shouldn't.

Some in dungeon examples are:
- Utgarde lower part, room with first boss. Even if it's a level 80 pulling on a non heroic version, all mobs come, including boss (including boss is the issue)
- Gundrak, room just before 1st boss, managing to pull only one abomination like we usually did in retail is almost impossible.

This also happens a lot outdoor, when, for example, attacking a non aggressive monster makes other non aggressive monsters come together (example of shoveltusks in Howling Fjord).

**Comment by fvicaria** [comment]
Sorry not an issue at all.

**Comment by tsuff** [comment]
The argro range is amost twice bigger than it was. So please be a dear and if this is the "how its supposed to be" take ur time to explain that its fixed, cuz it is an issue!
