### ISSUE TITLE
Some "Gathering Loot" quests are bugged.

### ISSUE THREAD

**Issue by Zan511** [WoWManiaUK/Redemption#634]
Greetings, I've at least encountered two loot bugs; the looting action is shaped like a double-bag instead of the mouse icon, in which you should get the item once you press it. These two quests are called: "Gluttonous Lurkers" and "Securing the Bait". The first one you have to gather 5 rats and throw at a Basilisk in Zul'drak, in which case the Basilisk becomes docile and when you hover on it you get a "double-bag" mouse icon, and once you press it you should instantly loot crystals, but that's not the case; I didn't get anything.
The second one is mechanically the same regarding the looting process, you hover on the little drake, and you loot it, yet, nothing. 
I tried doing it in and out of party, relogging, various attempts; but alas, with no avail.
Would be helpful if you looked into it for one of those quests are blocking a quest-chain that isn't available until I finish said quest.
Cheers.

**Comment by fvicaria** [comment]
Tested both quests in dev and they work fine.
Catch 5 rats first then throw ALL of them to the Basilisk. Mechanics is correct.
Try again after Wednesday and report if needed.

**Comment by Rushor** [comment]
one question @Zan511 : do you were mounted while clicking on the npc?
