### ISSUE TITLE
[Halion] Breath + Cutter errors

### ISSUE THREAD

**Issue by Earthliving** [WoWManiaUK/Redemption#638]
The breath can hit you even if you're not in front. The cutters can hit you even if you're not in the beams. It seems totally random.

**Comment by Emcitementz** [comment]
There's nothing wrong with the breath, it has 60 yards of radius so even if you're not in front, you'll be hit if you were standing in the cone of his breath.
Concerning the beam, i've tested just now and you really have to stand in it, it works as it should.

**Comment by wasser510** [comment]
It is not working as it should.
We tried Halion 10nm and in the twilight releam he makes ~90° turns to breath sometimes.
(And we did not pull aggro)
