### ISSUE TITLE
Culling the Threat - Missing NPC

### ISSUE THREAD

**Issue by Dragonfly414** [WoWManiaUK/Redemption#641]
The quest: Culling the Threat - http://www.wowhead.com/quest=1054/culling-the-threat
Got to kill NPC: http://www.wowhead.com/npc=3987/dal-bloodclaw
For item: http://www.wowhead.com/item=5544/bloodclaws-collection
But the NPC is not on the location in the cave (Thistlefur Hold)

This is the second time I checked and still no spawn, also waited little time, so I think the NPC is missing??

Thanks for checking!

Lovelace

**Comment by Emcitementz** [comment]
The NPC isn't missing, the location is just not the one that the quest shows.
![screenshot_4](https://cloud.githubusercontent.com/assets/11377592/21506628/e38f863a-cc71-11e6-84e7-2ef758560c7a.png)
It will be updated.
