### ISSUE TITLE
[Quest] What is going on?

### ISSUE THREAD

**Issue by Gutsplatter** [WoWManiaUK/Redemption#643]
[Quest] What is going on? 

Enemys/ambush doesnt trigger so cannot continue the quest.

Also the Dark Keeper didnt seem to trigger once all the coffer chests were opened and could not get Private Rocknot to trigger after giving them the 2x Ale in the bar preventing triggering the door opening.

**Comment by fvicaria** [comment]
http://www.wowhead.com/quest=3982/what-is-going-on

**Comment by Readerlady** [comment]
As of Feb 18, 2017 I was able to trigger the 2x ale in the bar and the fight ensued. The door was open. Seems to be working. Also when I opened all the coffer chests it triggered the Dark Keeper. The quest What's going on? Still does not trigger the ambush so I was not able to continue the quest and complete it.

**Comment by Feryk** [comment]
Confirmed: https://youtu.be/K-AmgXOqpBE
