### ISSUE TITLE
[Spell] Warrior 4 Set Bonus Bug

### ISSUE THREAD

**Issue by WastedMoment** [WoWManiaUK/Redemption#648]
Warrior 4 set slam proc bonus is bugged. Duration is increased as it should, we'll get the 2 slam proc buff but the 2 slam proc is consumed with only one use of slam.

**Comment by fvicaria** [comment]
Can you let me know exactly what proc/spell you are talking about?

**Comment by WastedMoment** [comment]
With fury warrior tier 10 the 4 piece bonus set includes "You have a 20% chance for your Blood Surge and Sudden Death talents to grant 2 charges of their effect instead of 1 and for the duration of the effect to be increased by 100%."

So, Sudden Death is an Instant Proc for Slam, with this 4 set bonus on tier 10 it gives 20% change for Sudden Death to Have 2 Instant Slams... However when it becomes active, it only allows for one slam to be performed and buff disappears even though its suppose to grant 2 instant slams, not one.
