### ISSUE TITLE
[Spell] Combustion

### ISSUE THREAD

**Issue by custos77** [WoWManiaUK/Redemption#650]
It's supposed to have 3 charges, however the buff is consumed after 2 critical strikes.

**Comment by fvicaria** [comment]
Can you link me the spell please. There are multiple spells called Combustion

**Comment by elagen** [comment]
i have tested out combustion on Fire mage and Sometimes it stacked to 5 and Sometimes it stack until 3 
http://wowwiki.wikia.com/wiki/Combustion_(old)

**Comment by custos77** [comment]
http://wotlk.openwow.com/spell=28682
http://www.wow-mania.com/armory/?spell=11129

Elagen, combustion have 3 stacks that does NOT show on the icon as a number nor otherwise. Mages are supposed to hit 3 critical strikes until the combustion is consumed. The amount you don't hit critical strikes increase the stacks you are talking about.

**Comment by vexation47** [comment]
I used combustion several times today and can confirm this.  It seems to work fine with scorch but not fireball or pyro, almost like the value of fireball and pyro are 2 crits, and scorch is 1

**Comment by Emcitementz** [comment]
[#654](https://github.com/WoWManiaUK/Redemption/issues/654)
