### ISSUE TITLE
[Raid] Nightbane from Karazhan

### ISSUE THREAD

**Issue by Readerlady** [WoWManiaUK/Redemption#651]
Nightbane died and his/her corpse landed off the ledge. We had a mage who used his rocket boots to loot but there were six of us on a quest to get a quest item that we could not get. Is there a bug that keeps him/her from dying in the air and his lootable corpse landing on the landing? Or possibly he should not die while in the air but only on his landing phase?

**Comment by fvicaria** [comment]
Well, for now I would advise to wait and kill when it lands or kite to a safer position.
