### ISSUE TITLE
[Texture] Rays and Capes

### ISSUE THREAD

**Issue by philoudu16** [WoWManiaUK/Redemption#653]
I am using the WoW Mania client as well as the launcher, and some textures seem to be missing (same for another player I checked with). These are the textures for:

-Sentinel's Winter Cloak: [http://wotlk.openwow.com/item=50466](url)
-Drape of the Violet Tower: [http://wotlk.openwow.com/item=50468](url)
-Volde's Cloak of the Night Sky: [http://wotlk.openwow.com/item=50469](url)

-the companion Nether Ray Fry: [http://wotlk.openwow.com/item=38628](url)

-the NPCs Aether Ray [http://wotlk.openwow.com/npc=22181](url)

**Comment by fvicaria** [comment]
as is
