### ISSUE TITLE
[Quest] Draconis Gastritis

### ISSUE THREAD

**Issue by Cinoril** [WoWManiaUK/Redemption#656]
The quest requires to drop meat on the ground to lure a proto-drake in the Ember Clutch. However, there are no proto-drakes flying in the area. I tried dropping the meat in multiple spots around the Ember Clutch and got nothing.

Opened a ticket in-game, which was responded by GM Dakoria and assisted me in completed the quest.

Are you using our client? Yes
Are you using the latest Launcher? Yes
Did I include the operating system I am using? Windows 10
Did I include the steps to reproduce the problem? Yes
Include NPC/Item/Spell names (or IDs) from wowhead.com: http://www.wowhead.com/quest=11280/draconis-gastritis

**Comment by Emcitementz** [comment]
It works, you just have to wait for a drake and place it on the ground, the drake will detect it.
