### ISSUE TITLE
#quests_map

### ISSUE THREAD

**Issue by boomfist** [WoWManiaUK/Redemption#658]
My character stuck and my hearthstone was in cooldown so i use the auto-unstuck and go back at the Red Cloud Mesa, but the moment i open the map to see the quest that i have to do and where to go it didnt sow me anything at the map not the coplet quest not the quest in progress not to where area i have to go no nothing.If i log out and go in again its not buged but the moment i press on a quest or open the map its bug again

**Comment by fvicaria** [comment]
This is a client issue. Open a ticket and wait for assistance.
