### ISSUE TITLE
[QUEST] Hell Hath a Fury

### ISSUE THREAD

**Issue by YulEb** [WoWManiaUK/Redemption#660]
Hi,
in the Quest you need to hexe three Highpriest to death.
I hope I dont mix up the names:
High Priest Mu'funu just needs to be hexed (works fine)
High Priest Hawinni needs to be hexed and after that killed, so he freezes to death (works fine)

High Priest Tua-Tua needs to be hexed and becomes a stonestature afterwards. And here is the problem: The High Priest will transform into a stonestature right after you start the channeling. so you cant end the channeling and therefor dont get the progress.

I tried to restart the Quest / leave the Zone. both didnt work. So I finaly had a GM solve the problem for me.

kind regards and a happy new years eve,
LaureenY

**Comment by fvicaria** [comment]
http://www.wowhead.com/quest=12674/hell-hath-a-fury
