### ISSUE TITLE
[Raid] Tempest Keep the Eye

### ISSUE THREAD

**Issue by Readerlady** [WoWManiaUK/Redemption#663]
Last boss (Kael) mind controls **all** members of our raid. There is no opportunity to use the blade that stops mind control so that the encounter can continue.

**Comment by fvicaria** [comment]
Fixed. A max of 3 player can be affected now. If you do it with a group of 3 or less it's your problem.

**Comment by Readerlady** [comment]
Thank you sir. 
Happy new year!
