### ISSUE TITLE
[Raid] Ulduar - Flame Leviathan 

### ISSUE THREAD

**Issue by Earthliving** [WoWManiaUK/Redemption#666]
Activating secondary defense systems, (AKA Hard mode flame levi) gives every creature in the raid the Tower of Frost, Storms, Flames and Life buffs. Giving every creature +120% health... among other things.

**Comment by elagen** [comment]
Can you provide more details of this fight?

**Comment by Kalasbyxan** [comment]
Previously witnessed following:

Hard Mode for first boss, Flame Leviathan (http://wotlk.openwow.com/npc=34003), is activated by leaving the 4 pylons alive before engaging Flame Leviathan. This grants the boss a buff for each pylon alive:
- Tower of Frost (http://wotlk.openwow.com/spell=65077)
- Tower of Storms (http://wotlk.openwow.com/spell=65076)
- Tower of Flames (http://wotlk.openwow.com/spell=65075)
- Tower of Life (http://wotlk.openwow.com/spell=64482)

Once the boss is dead, all other bosses in Ulduar (I don't remember if NPCs) have the same buffs. Once assisting a raid with this matter, I found the buffs still active on the dead Flame Leviathan. I removed the 4 buffs and they were removed from the other bosses in Ulduar too.

**Comment by elagen** [comment]
If all 4 of the towers are up then all the bosses have all the buffs

**Comment by wasser510** [comment]
The problem is after you kill flamelevithan the mobs and bosses after got the buff aswell.
