### ISSUE TITLE
[NPC] Aether Ray

### ISSUE THREAD

**Issue by silver1882** [WoWManiaUK/Redemption#668]
The Aether Ray's at Vortex Pinnacle (Blade Edge) do not have any graphics they appear as blue and white checkered boxes.  I have an add on that shows the location  on of the Aether Ray's is at 29:65 in (Blade Edge).

**Comment by silver1882** [comment]
I know this was closed but The Aether Ray now looks like a Person swimming in the air instead of and Aether Ray.

**Comment by fvicaria** [comment]
Thanks a lot I must have typed something wrong. :)
I will fix now in Redemption.
