### ISSUE TITLE
[Raid] Molten Core

### ISSUE THREAD

**Issue by philoudu16** [WoWManiaUK/Redemption#670]
This raid seems  to work very strangely on this server: two days ago, we started molten core and downed all bosses except Magmadar, and runes didnt seem to deactivate. Yesterday, while we were clearing trash to get to Magmadar, Ragnaros randomly spawned... So we decided to kill him. Then we downed Magmadar and Majordomo Executus  didnt spawn at all.
The way it's supposed to work  is: kill all bosses who protect a rune (all except Lucifron) to deactivate them, then Majordomo Executus spawns and you need to kill him to spawn Ragnaros.
So I'm really not sure how Molten Core works on the server. (I'll try running it again when I can)

**Comment by philoudu16** [comment]
This time, we didnt even reach the first boss that ragnaros was summoned...

**Comment by elagen** [comment]
Majordomo Executus - Will spawn when all Bosses are killed except killing ragnaros - which spawns when  Majordomo Executus dies - the only problem here is Ragnaros spawning before all bosses are dead

**Comment by wcslanker** [comment]
Yes, as soon as I entered MC the other night, Ragnaros would start doing his little speach as if you killed Majordomo. So really you can just zone in and go straight to Ranaros without doing anything.
