### ISSUE TITLE
[ Spell ] Mark Of The WIld

### ISSUE THREAD

**Issue by raduradu87** [WoWManiaUK/Redemption#675]
hy my  [Mark of the Wild] spells says that it will give me 1050 armor, all attributes by 51 and resistance by 75 ... but when i buff myself it gives ( armor 750. all attributes by 37 and all resistance by 54 ) in my bar i got the last rank of the spell ..... and i even have the (  [Improved Mark of the Wild] talent at lvl 2 ) and learned all the spells from the trainer

**Comment by elagen** [comment]
I have Checked the buff on my own druid and someone else the buff has a visual affect - it does increase your stats by 1050 Armor - and all of your attributes are increased by 51 - it is a visual affect that makes it look like it doing what it shouldn't be
