### ISSUE TITLE
[Achievement] Fishing Tournament in Booty Bay

### ISSUE THREAD

**Issue by Antihris** [WoWManiaUK/Redemption#678]
When i try to return fish Riggle Bassbait say that we have a winer but there is no anonse and when i try to return fishs to Jang he say we need to have a winer first and then i will give you money for every 5 fish.

**Comment by philoudu16** [comment]
It indeed seems bugged, I was there from the start (when the npc yells the tournament begins) and at 14:15, when I went back to give in my 40 fish, Riggle Bassbait said that all the winners had been found, but the other NPC Jang, who gives you money every 5 fish, was saying that no winners had been found yet.
