### ISSUE TITLE
[Quest] The Halls Of Reflection (battered Hilt Quest Chain)

### ISSUE THREAD

**Issue by propserer** [WoWManiaUK/Redemption#684]
http://wotlk.openwow.com/quest=24561

For some reason i cant complete the quest after me and a tank success subdued Quel"Delar.

Bring Quel'Delar to Halls of Reflection : 0/1
Subdued Quel'Delar : 1/1 (Complete)

I watch on youtube video yesterday by bring Quel'delar into Halls of Reflection **"Bring Quel'Delar to Halls of Reflection"** should be complete but not for me today (9/1/2017)

This is my first time wrote an issues in github i hope i follow the format :)

**Comment by fvicaria** [comment]
The player itself has to do it. Not the other members of the group.

**Comment by propserer** [comment]
http://www.wowhead.com/quest=24561/the-halls-of-reflection#comments 

people comments that the quest even can be complete with random dungeon finder or 2 person there no mention that the quest must be complete by player itself

this video https://www.youtube.com/watch?v=LFBWI1FQ-6Y show that by being inside HOR the **"Bring Quel'Delar to Halls of Reflection"** should be complete. So please check again

**Comment by fvicaria** [comment]
There is all no mention that anyone can kill it and you will still get credit.. It's an individual quest not group quest. You can have players help you at your own peril but you are the one that needs to give the killing blow or you will not get the credit. This is the way it is scripted and the way it's working at the moment.

**Comment by propserer** [comment]
i already kill the quel'delar

**Comment by propserer** [comment]
[http://imgur.com/8lvO1OP](url) this is my quest log, as it shown i already subdued Quel'Delar
