### ISSUE TITLE
Netherwing faction. Quest line issues.

### ISSUE THREAD

**Issue by jorgeppatron** [WoWManiaUK/Redemption#691]
Hello everyone.
While I'm doing the quests to get more reputation with this faction I found two problems, which I'm gonna list/describe above:
- The first one is from the quest "The soul cannon of Reth'hedron". This quest is very simple, for those who don't know. You only need to pick up some crafting materials and talk to an NPC (Sar'this, it is found at Terokkar Forest 44.7, 42.2) in order to begin the ritual and summon some stuff to get the last needed item. This is actually the problem, the NPC doesn't do the required action when you talk to him, therefore you can't get the item and can't complete the quest.

- The second one is from another quest: "The deadliest trap ever laid" from the same faction aswell, but in another place (Shadowmoon Valley  64.4, 29.4 [This coords may change depending on your Shattrath side <Aldors / Scryers>, mine is from the Aldor.]). You need to hold an invasion from a bunch of Dragonmaw forces, commanded from a boss at the end of it, it's quite easy aswell... you only need to follow Arcus to the located place in the map and wait for the mobs appear from everywhere, killing them and it's done. This quest has the same problem, because you need the NPC Commander Arcus to begin the process of the invasion and get the quest done; he doesn't even move from his place.

I've done this on retail before, and I know the correct process of these quests, so this is my issue. I also know it is not needed to keep farming reputation from this faction to reach exalted since you can just keep look for the Eggs, but I think it would be good if you can fix these bugs for those curious persons who like to do quests (like me and some maybe others).

Thank you!

**Comment by WastedMoment** [comment]
Just farm 130 netherwing eggs, i did this in a total of probably 9 hours. and got exalted in under a day lol screw the quests i say! 

however the only one ive seen bugged still is Deadliest Trap, however its not needed to successfully do netherwing rep.

**Comment by elagen** [comment]
Can you Link the Quest's of what they are next time please - thank you

http://www.wowhead.com/quest=11089/the-soul-cannon-of-rethhedron

http://www.wowhead.com/quest=11101/the-deadliest-trap-ever-laid **Aldor Rep**

http://www.wowhead.com/quest=11097/the-deadliest-trap-ever-laid **Scryer Rep**
