### ISSUE TITLE
[Quest] "It Rolls Downhill"

### ISSUE THREAD

**Issue by respectdat1** [WoWManiaUK/Redemption#693]
http://www.wow-mania.com/armory/?quest=12673
The quest has you mind control blight geists around the area in order to pick up crystallized blight.
When you give them the command to pick up the blight, they simply just stand there.

I see that there are 3 other closed threads about this, but those were back in October, and it is the exact same problem. I contacted GM Dakori, and he/she said it was ok to make a new thread on this.

Here is the first thread that was closed:
https://github.com/WoWManiaUK/Redemption/issues/334

**Comment by fvicaria** [comment]
Then you are doing it wrong.

![Uploading image.png…]()
