### ISSUE TITLE
[Raid] Icecrown Citadel - Sindragosa

### ISSUE THREAD

**Issue by Skullpoopl** [WoWManiaUK/Redemption#694]
Yesterday I went to ICC and I noticed some major bugs on Sindragosa fight : 
1) Apparently Blistering Cold is working as it was intented to do...But when she started casting BC , the cast time started before the ranged people were already pulled and they already lost 1 second of trying to run away from it.Also 2 things on especially Blistering Cold : 
   a) The area where the people were supposed to be pulled would be further away from her exact 0 hitbox position that are pulled now . All were pulled at about the center of Sindragosa's red circle.Melee are pulled faster because they are near but ranged are completely unable to react to the speed of BC is being cast
   b) As of a)'s result she was casting Deep Breath while people were being pulled by BC and because all were at her 0 hitbox position over 7 ranged / healers died from her breath without even being able to react to BC....The thing here is that the DB and BC shouldn't be more than 5 seconds timer close to each other...This makes it literally impossible for our raid to even touch her 3rd air phase without half raid being dead...
2) When 5 people got tombed...i noticed an Ice Tomb like jumping and hovering at a 2-3 yard height from the ground...which made people behind it vulnerable to Ice Bombs....I think a DK Death Gripped the tomb and did that but i am not 100% sure though....even though it shouldn't be moved by any skills unlike the spikes from Marrowgar...
3) I am not 100% sure about that either but at some time 3 people died after 5 seconds of getting Unchained Magic , and the damage they took as of Recount and Combat Log was from Sindragosa and not  from UM debuff or any other mechanism of the fight...As of this all 3 of these people stated instantly on Skype at that time we were raiding that they didn't even cast any spell . they had 0 stacks and they died from nothing...I don't have any other data for this but you should take a look at it as i am sure these 3 people were correct as this happened 2 times in totally 3 Sindragosa tries...

P.S. : I did write a bad thing on World Chat and i got informed for it , but it wasn't intented to be towards the GMs or the developers and the Janitor tries to make the server as good as they can as he is provided free for us to enjoy this great expansion WotLK was. It was more of a desperation flaming from me because some people leaved our raid because of these bugs and i got angry at them and i turned towards the server.... I am never losing votes every day ( even if this doesn't proves that i am a good character ) but i think this might reflect towards the best of the server...because it is the best server i have played since 2012 and i don't want to stop playing here...
Thanks...

**Comment by Skullpoopl** [comment]
Also one thing that i noticed that stopped working and it is as it was intended to be is that now we no longer gain Chilled To The Bone while hitting tombs while older we did and it was a pain while trying to get them down...
Thanks on that...

**Comment by elagen** [comment]
While Testing Sindragosa - the only bug we can find and can confirm is -
when a player in Phase 3 is targeted with Frost Beacon - is pulled into the boss by the icy grip which should not happen

**Comment by Skullpoopl** [comment]
We just did Sindi in heroic....
Everything works perfectly fine now....We met nothing strange....People are pulled into BC as they were supposed to...Dark Breath is no longer timed with BC and tombs are not staying up in the air....
Good work guys and thanks for the response....
