### ISSUE TITLE
[QUEST] Flight of the Wintergarde Defender

### ISSUE THREAD

**Issue by Pralina78** [WoWManiaUK/Redemption#695]
Hello!

I'm using the  latest launcher/client on a MsWin7x32 machine and found a problem with
http://www.wowhead.com/quest=12237/flight-of-the-wintergarde-defender

Rescued the first 8 villagers, but can't finish  the quest because  the second I aproach a villager... it dissapears. If I camp a spot... they appear and dissapear in an instant.

Also , the quest should require 5 villagers, not 10.

**Comment by fvicaria** [comment]
During wotlk this was 10.
The best source of reference is wotlk.openwow.com

You are out of phase for some reason. Open a ticket.

The quest is working fine.

**Comment by Pralina78** [comment]
I did open a ticket first, gm sent me here...
