### ISSUE TITLE
[QUEST] Post-partum Aggression

### ISSUE THREAD

**Issue by tickswarm** [WoWManiaUK/Redemption#696]
Hi there,

For _Post-partum Aggression_, one has to slay Broodmother Slivina in the Savage Thicket, in Sholazar Basin.

When Broodmother Slivina is slain, the quest is not fulfilled. I tried a couple times, but it does not seem to register that the quest has been completed. 

Thanks

**Comment by fvicaria** [comment]
Works fine.
![image](https://cloud.githubusercontent.com/assets/9414661/21965135/82cfa1ec-db51-11e6-99a2-0b26e12a18be.png)
