### ISSUE TITLE
[Zone] Emerald Forest

### ISSUE THREAD

**Issue by philoudu16** [WoWManiaUK/Redemption#697]
Ok, you might want to fix this, or leave it as it is as a kind of easter egg, not sure what you want to do about it :p 
Ever heard of the emerald forest? It's an instance you shouldnt be able to access in any way but you can actually access it on this server.
Basically there are 4 portals in Azeroth (one in Duskwood, one in Ashenvale, one in Feralas, one in the Hinterlands) which are guarded by dragons of green dragonflight that have been corrupted (except the duskwood one which is protected by a satyre).  That's for the lore.
In the game, the portals are all there but should be off, nothing should happen if you go through them, and you're not supposed to be able to interact with them. However, on the server, you can interact with the one in Duskwood and enter the Emerald Dream dimension. However once in, if you go alone, you can move around but you get the usual "You are not in this instance's group... and will be teleported to the nearest graveyard"  message. When the timer runs out you are tped, but inside the instance! However (and this is the problem that may make you want to remove the ability to enter the zone entirely) you can not move at all after being tped, and the hearthstone and mages' teleports do not work (my wow mania stone was on cd so i could not check if that worked). Luckily portals somehow work :) so mages are not really trapped, but if something else gets trapped in there, it may require gm attention to get him out.
If you enter in a raid group, you can freely move around for as long as you want :) and explore this vast world full of pretty cool stuff :) (You will also be able to hs out of that dimension!)

So if you want to keep that zone in the game for the curious people out there, and not annoy the gms with people being stuck in it (even though it probably has not been a problem yet), you could just add some portals to the capitals close to where you get tp'ed at the end of the 1 minute  "you are not in the instance's group" timer.

**Comment by fvicaria** [comment]
We have the portal to Emerald forest working. This is not retail. So not an issue.

**Comment by philoudu16** [comment]
ok, just wanted to make sure in case some ppl get stuck in that dimension :)
