### ISSUE TITLE
[QUEST] Disrupt Their Reinforcements 

### ISSUE THREAD

**Issue by Thelesaan** [WoWManiaUK/Redemption#698]
http://www.wowhead.com/quest=10144/disrupt-their-reinforcements

I am using the wow-mania client and the latest version of the launcher.

In this quest, that takes place in hellfire peninsula, you will have to destroy two demonic portals, but the problem lies in the second one, "Portal Grimh" (http://wotlk.openwow.com/object=184414), there is a Pit Commander (http://wotlk.openwow.com/npc=18945) and a group of fel soldiers (http://wotlk.openwow.com/npc=18944). This mobs are not intended to be there, and there should be only one pit commander in the game, the one that is located near The stair of destiny. You cant do this mission,

The only way to do this is to highly outlevel the mission or to use something that makes you invulnerable.

**Comment by Kalasbyxan** [comment]
Me and Val observed this previously and is most likely a result players attempting to kite Doom-Lord Kazzak. It's not a constant issue, but requires the mobs to be killed for the quest to be done at correct level.

**Comment by fvicaria** [comment]
The mobs are patrolling the area all the way up to the portal.
Just wait for it to be far away.

**Comment by Lhiris** [comment]
Had this issue in the past. The mobs spawn there and sometimes fail to move after. When getting killed and then respawned they'll correctly start moving on their path to the portal.
