### ISSUE TITLE
[Raid] Lich King

### ISSUE THREAD

**Issue by Plege** [WoWManiaUK/Redemption#699]
Hey Guys, tested Lich King today the following buggs are present on dev:

When the Valkyrs spawn they can bug out if stunned too early with Holy Wrath (http://wotlk.openwow.com/spell=48817). The bug is that they will teleport instantly to the edge of the platform and drop the player without having time to damage them. We tried to reproduce this effect with other aoe stunns but as of now we only know of Holy Wrath causing this bug. As of now single target stunns don't cause that bug either.

Further, if the Valkyrs are stunned (and don't bug out) they will not recommence their movement after the stunn wears off. So they are stuck in position holding the player and can be damaged down easily. but they should start moving again after the stunn wears off.

Further, we tested in 10 nm and the Valkyrs casted Syphon Life (http://wotlk.openwow.com/spell=73488) when they are back up in the middle of the platform. This is hard to confirm as a bug because i struggle to find a retail video on people getting dropped and the valks going back up into the middle. Because on nm they have to be killed all the way to release a player. But on most sites and fight tutorials it says siphon life should only be cast in the heroic version.

In general i must admit the devs are doing a good job clearing up ICC!!
LK is still bugged and 1 bug on sindy other than that i think we are almost done :-D

Regards,
Pleger

**Comment by fvicaria** [comment]
Please report issue on redemption only. If needed we can create a separate repository for dev.
