### ISSUE TITLE
[Quest] The Affray

### ISSUE THREAD

**Issue by Earthliving** [WoWManiaUK/Redemption#700]
Warrior zerk stance q.

Enemies don't spawn properly, impossible to complete without GM intervention

**Comment by Zan511** [comment]
Please include more details about this quest, and we'll be on it shortly.

**Comment by elagen** [comment]
The Mobs that need to be killed for the Quest come into action before the last mob is killed and the npc Twiggy Flathead keeps saying You! enter the Fray! which should be after the mob has died you face a new mob

this will need to be adjusted where a new mob comes into action so you can kill after the old mob has died
