### ISSUE TITLE
Fireball stuntime.

### ISSUE THREAD

**Issue by Dredziarz** [WoWManiaUK/Redemption#701]
hello, i'm finded the bug during the battle. When i cast too many times fireball my character start stay in stun or undercontrol, without my control. During this 2-3 secounds i can do nothing. it's something new from my last raid with people from guild.  it happening every boss on ICC25hc and every raid. Are other people finded this same bug? Please help us with do real dps.

**Comment by fvicaria** [comment]
Please try this on a dummy. I cannot reproduce it. It was most likely due to lag.

**Comment by Dredziarz** [comment]
Maybe it's a problem when i use all my burst macro, because when i use.
/use Combustion
/use Mirror Image
/use Berserking
/use Hyperspeed Accelerators

and my cast time on Fireball start be close to 1.2sec. Maybe you can check
it out.
Should i do a video with this bug? maybe it will help you with identivate
the problem.

2017-01-16 11:05 GMT+01:00 Janitor <notifications@github.com>:
