### ISSUE TITLE
[Quest] Destroying the Alters

### ISSUE THREAD

**Issue by fyredawg74** [WoWManiaUK/Redemption#702]
I am using the wow-mania client and the latest version of the launcher.

The quest in overlapped by the quest He's Gone to Pieces.  When I get to close to the alters it phases into the other quest.  This makes the alters disappear and the quest not complete-able.  
I was able to get the staff needed and the 3rd alter by staying on the outskirts of the area, but this plan does not appear to work for the other 3 alters.

**Comment by Lucronick** [comment]
Same thing with me. Toon is Dilligafs.
