### ISSUE TITLE
Dr. Gregory Victor - First Aid Trainer

### ISSUE THREAD

**Issue by Lucronick** [WoWManiaUK/Redemption#705]
Dr. Gregory Victor in Hammerfall - Arathi Highlands is bugged. I am unable to train runecloth bandages. Upon completing the quest "Triage" and I talk to him, he is responding as the alliance NPC, Dr. Gustav VanHowzen.

**Comment by fvicaria** [comment]
What makes you say that? They have not different text to tell.
Can you send screenshot or explain better.

**Comment by elagen** [comment]
From this post http://wowwiki.wikia.com/wiki/Quest:Triage_(Horde)

you dont learn Runecloth bandage - Dr. Gregory Victor is not a first aid trainer

you need First aid 225 and to be Level 35 to do the quest

This quest is located in Hammerfall. As of Patch 3.1.0, this quest is no longer required for Artisan First Aid; you may train it from any First Aid trainer in a capital city.

**Comment by Zan511** [comment]
You also need at least 260 skill in first aid to learn it.
