### ISSUE TITLE
[Quest] Bonechewer Blood (Hellfire Peninsula)

### ISSUE THREAD

**Issue by candycrate** [WoWManiaUK/Redemption#706]
The drop rates on this quest are HORRIBLY low... I cleaned the place 2 times (resto shammy) and all i got was 1 blood out of 12!!! Please fix it. The rewards are too damn nice to drop the quest :/

**Comment by elagen** [comment]
Here is the drop rate for the Quest

http://wow-mania.com/armory/?item=30327

**Comment by candycrate** [comment]
Its DEFINITELY NOT 30%. I just checked the discussion in wowhead and they say similar things

**Comment by fvicaria** [comment]
It is as per database. Nothing to do here. I will raise a bit.
