### ISSUE TITLE
Blowing Hodir's Horn (quest)

### ISSUE THREAD

**Issue by Cinoril** [WoWManiaUK/Redemption#707]
This quest shows that I can get it, but when I click accept, nothing happens and I can't get the quest window to open up again. Quest link: http://www.wowhead.com/quest=12977/blowing-hodirs-horn

I did complete the prerequisite quest A Monument to the Fallen: http://www.wowhead.com/quest=12976/a-monument-to-the-fallen

    Are you using our client? Yes
    Are you using the latest Launcher? Yes
    Did I include the operating system I am using? Windows 10
    Did I include the steps to reproduce the problem? Yes
    Include NPC/Item/Spell names (or IDs) from wowhead.com   See above
    Be descriptive and precise.
    DO NOT log multiple issues in one!

**Comment by elagen** [comment]
i have just done this quest and when i accepted it you get given : Hodir's Horn (Provided)

then you need to kill 5 of the each mobs listed in the quest 

here is the quest
http://wow-mania.com/armory/?quest=12977

i hope this helps

**Comment by Cinoril** [comment]
I am trying to receive the quest right now and it is still not working for me. Now I don't even get a quest window.
