### ISSUE TITLE
Tailoring Recipe Northrend Dungeonmaster

### ISSUE THREAD

**Issue by robertgf1** [WoWManiaUK/Redemption#709]
Upon getting the Northrend Dungeonmaster Achievement, Charles Worth in Dalaran is suppose to teach you Wispcloak, but he offers Deathchill Cloak instead, which is supposed to be taught when you get Loremaster of Northrend.
![wowscrnshot_011817_180636](https://cloud.githubusercontent.com/assets/25205678/22074796/e4f190ec-dda9-11e6-9528-49bc9ea2145b.jpg)
![wowscrnshot_011817_180657](https://cloud.githubusercontent.com/assets/25205678/22074802/ea12e846-dda9-11e6-8daf-59387ceddfaa.jpg)
![wowscrnshot_011817_180703](https://cloud.githubusercontent.com/assets/25205678/22074812/edc5de6c-dda9-11e6-9385-79c5ce3ce543.jpg)

**Comment by elagen** [comment]
The WispCloak - is suppose to be rewarded from Northrend Dungeon Master - NM + HC but it is from Loremaster Instead 

The Deathchill Cloak - Is suppose to be from Loremaster - Instead it is from Northren Dungeon Master

The loot from the Achievement rewards need to be swapped around
