### ISSUE TITLE
Warlock's Pets

### ISSUE THREAD

**Issue by Necrosiss** [WoWManiaUK/Redemption#710]
Hello, 

1. First problem is about Voidwalker and his skill Consume Shadows. As you can read in link below passive stance allow warlock to command pet as he want, also in link for skill take a look in poistion Tips & Tactics. Problem is that whenever you run with your pet and click to use Consume Shadows he dont stop and start to cast, he keep run behind you nothing happens. That skill should be used to find nearby stealth units whenever Warlocks want it. Okey, lets say its channel skill and as players pet need to stop, okey but i tell him to use the skill on passive he should stop and cast no matter what. Another thing about that pet is when you run, pet following you and you decide to put him on "STAY" he stop in a moment however... when you use Consume Shadow, pet start to run somewhere(?) like in fear but he wont stop till die or you call him back.

http://wowwiki.wikia.com/wiki/Consume_Shadows
wowwiki.wikia.com/wiki/Passive

2. Felhunter and his Spellock skill. Sending you again to link above about passive stance. Whenever you use Spellock(manualy clicking the spell or hotkey, auto-cast off), on a player or mobs on a passive stance pet should use the skill (ofcouse if in range) and still FOLLOW you no matter what, but he doesnt. Fel after you use a skill start to go to the target. Below link to a skill, as u can read there it put you to a mele combat but its normal thing. You used something on player/mob so it makes be in combat. It doesnt say AT ALL ANYWHERE that pet will start to attack. Again passive stance, pets should do w/e Warlocks tell them.

2a. Felhunter Devour Magic na Fel Intelligence. Im not sure whats might be wrong exacly maybe nothing but ill describe a situation only. You can put Warlocks pet skills (not all) to be auto-cast, Sometimes when you summon Felhunter and use Felintelligence there is no effect at all, you need to resummon pet to make it work, this is the only one thing i noticed is kinda strange. About Devour Magic situation is different. So lets say you have it OFF (no auto-cast), pet shouldnt remove anything but sometimes the skill is still on even if you see it OFF. Before i made the post i did check it and simply put skill on auto cast and turn it off fixed a thing so no clue if it suppose to be like that.

http://wowwiki.wikia.com/wiki/Spell_Lock

3.Succubus, was testing it also while writing that post. So pet is on Passive mode, when you put Seduction skill on auto-cast and tell to cast on player, Seduce happen, after it ends pet keep attacking a player and use skill again but not instantly after 1st one end or get break. She use it after few seconds which is pretty strange since global CD on the skill finished. Situation change when you remove auto-cast from Seduction. In that state when you tell to seduce, seduce happen, after it breaks or ends pet go invisible again and follow you which is good. Ill compare it to Felhunter spelllock. Why Felhunter on auto-cast off after you use Spell lock keep attacking the target? He shouldnt even touch a target, suppose to do as Succubus. Cast spelllock when a warlock want it and keep following without charing the target.

P.S Sorry for my english, if sometihing isnt clear or need more info or im wrong about something please let me know.

Thanks, Necro.

**Comment by fvicaria** [comment]
Can someone confirm or dismiss this please.

**Comment by Necrosiss** [comment]
Update to Succubus:

So when you enter a combat with succubus and got invisibility on auto-cast, you call Succubus back till u r in fight she will cast Invisibility till combat ends wasting all mana casting only that one thing. Second thing i discover is you CANT seduce feral druid in form it keeps says "Cant target players"(?). Even if this is a cat, seduction since its a players no matter what should work on him. Feral skill Berserk breaks fear and make u immune on it durring the buff time, but there is nothing on dudu that prevents Charm. Everywhere i did play Seduction was working on ferals. 

P.S Its hard to confirm all that pet things if some didnt use warlock class from long time. I was playing on different servers + years on warlock. Please take 1h to take a test on all that things. 

Thanks, Necro.

**Comment by Plege** [comment]
I started to work on this post before but imo it's too long. Necro i suggest you break each issue down into separate posts so it's easier to work with. Its also easier to close threats and fix them and keep track of the separate issues

**Comment by Plege** [comment]
I thank you for taking your time and reporting extensively :-) we'll try and get to it soon

**Comment by Necrosiss** [comment]
No problem at all, im Warlock user from long time its a pleasure to make it works better. You want me to post all pets separatly to let u close this topic? Lemme know here and ill do it asap.

**Comment by Necrosiss** [comment]
I made 3 post about it separtly to different pet, u cant close this topic. Thanks for the respond nice to see some1 will take care of it! :)
