### ISSUE TITLE
[Spell] Fear Ward

### ISSUE THREAD

**Issue by Necrosiss** [WoWManiaUK/Redemption#712]
Hello,

I was making tickets many times all the time got a promise that Developers know about that bug and it will be fixed after next update. Nothing happen, so ill try to post it here. The Priest skill called like in tittle Fear Ward work and make a priest totally immune to fear. AS it stays in skill that first fear will fall and consume Fear Ward, but thats not happening. Skill stay forever on the priest till dispell or priest cancel it.

http://wowwiki.wikia.com/wiki/Fear_Ward

Thanks, Necro.

**Comment by elagen** [comment]
Once the Person has fear ward on them and Fear is casted - the Fear ward buff should disappear and it does not so they are immune to fear for 3 minutes

**Comment by Readerlady** [comment]
Shhh....I like it this way! LOL
