### ISSUE TITLE
Wintergrasp Tower Cannons

### ISSUE THREAD

**Issue by keboid** [WoWManiaUK/Redemption#713]
The Wintergrasp Tower Cannons in the fort are placed wrong and they are facing in the wrong direction. That way man can not shoot in the needed directions. The cannons in the southern towers are placed correctly.

**Comment by keboid** [comment]
Not fixed, towers sometimes facing inside. Placing is also still bad, they need to be at the end of platforms. Otherwise you shoot yourself.

**Comment by fvicaria** [comment]
Fixed. I checked one by one. If it is not send me an image and the coordinates.

**Comment by keboid** [comment]
They are placed still bad if not worse. You can not shoot with them correctly. Inner ones are always missing, the ones not in towers but on walls.

**Comment by keboid** [comment]
Here: Fortress Tower Gun misplacement, you can see the base turned wrong and not placed like on the following picture:
https://s24.postimg.org/rgxrhpmwl/Wo_WScrn_Shot_012617_132833.jpg
Southern Tower Gun placed correctly:
https://s30.postimg.org/e4pxoh2m9/Wo_WScrn_Shot_012617_132932.jpg
