### ISSUE TITLE
Undead toons visual bugs

### ISSUE THREAD

**Issue by Privighecioara** [WoWManiaUK/Redemption#715]
I got a undead DK (Spankenstein). Whatever belt i use it is invisible. Just as it were cut in half at the belt level. Also not all damage numbers show up in combat, and final bug i observed is that during combat one of the weapons becomes invisible aswell. The characted uses 2x1handed weapons since its on frost spec. Made a ticked, but the Gm Dhorlin couldn`t help me. He sugested i put this issue on this site. I tried changing belts, relogging, but still the bugs persist. I talked to other guild members and some had the same problem. Can it be solved somehow?

**Comment by elagen** [comment]
With the weapon that seems like it is missing it is not from your character sheet - it is a visual bug when DBW is proc'd u lose no dps

With the waist missing on the undead race (male) we will see what we can do about it - atmosphere we are fixing raids and class bugs and fixing them

**Comment by elagen** [comment]
Atm  we are fixing raids and class bugs and fixing them

Is what is suppose to be said

**Comment by Privighecioara** [comment]
Ok. Thank you!

**Comment by fvicaria** [comment]
https://github.com/WoWManiaUK/Redemption/wiki/How-to-Properly-Report-an-Issue
