### ISSUE TITLE
WINTERGRASP

### ISSUE THREAD

**Issue by wcslanker** [WoWManiaUK/Redemption#717]
The graveyards are bugged. For instance, the alliance camp GY doesn't auto respawn you, instead you have to click on spirit res and spawn with only half hp/mana... Then as for Broken Temples GY, it doesn't work at all.

**Comment by rhadei** [comment]
I have this problem about 1/3 of the time I do WG, and it happens just as much to my Horde toon when he dies as to my Alliance. When it doesn't work at all, I have to fly on the spirit gryphon back to where I was killed, and possibly wait 2 minutes to rez, and come back at half health.

**Comment by fvicaria** [comment]
Again stop creating bugs without searching for existing ones. You waste your time and ours.

**Comment by wcslanker** [comment]
what? ^^

**Comment by fvicaria** [comment]
https://github.com/WoWManiaUK/Redemption/issues/598

**Comment by wcslanker** [comment]
Are you trying to tell me that I'm wrong and that the GY are fixed?
