### ISSUE TITLE
Threat Range / Pull Range

### ISSUE THREAD

**Issue by Escaflowne777** [WoWManiaUK/Redemption#718]
Hey WoW-Mania Support Team,

I have started playing a Warior Tank on the server about a weak and a half ago. While questing and tanking low and now also Northend normal Dungeons, i noticed the range in wich you get threat is quite high. 

- While going through Dead mines I tryed to pull one group but a over the half or even a  hole dungeon segment was pulled with. Due to the many non elite digger along the wall who got threat from each other.
- Also in Dead mine, when you pull Mr. Smithe it happend alot of times the the lower part of the Boat was pulled with him also geting a secound boss to be pulled with (Cookie)
- During Other Dungeons it is also noticeble that groups that should be pulled seperatly are not able to be pulled separatly. How ever the groups are not so close together like in the Dead mines.
- The bigs problem i had intill now wich made it imposible to play a dungeon was in Azjol Nerub. The 3 groups that should be pulled separatly infront of the first boss are so close together and the threath range is so high that when you pull one not only one group but all are pulled and the boss. As a low level tank with no epic or lvl 80 tank gear (deff cap and over 20k life) it is imposible to survive such a fight.

I am no expert, but i think this is realy a threat range problem, since i had also many pull problems during questing. However it may also be bugs where the groups are combied as one group. Either way it makes some dungeons unplayeble or so challenging that you need to die through, taking all the fun out of the game.

I hope this can help you fix the problem and make the server even better then it already is.
With best regards,
Escaflowne

**Comment by fvicaria** [comment]
This is being fine tuned. Let me know if does not improve.
