### ISSUE TITLE
[Spell] Savage Combat (rogue talent)

### ISSUE THREAD

**Issue by jurrianvg** [WoWManiaUK/Redemption#720]
Hello readers, today I went into Wintergrasp. And i was fighting an Alliance rogue that is specced into combat. So he had the Talent "Savage Combat (spell ID: 58683), after the wintergrasp i went back to Dalaran, stood there for like 15 minutes chatting with some guildies, still the debuff wouldn't get away, logged off, still the debuff was not going away, can we fix this? :) 
![wowscrnshot_012217_124910](https://cloud.githubusercontent.com/assets/23138060/22182285/e3509ff8-e0a1-11e6-9a05-b4dd8b833c8a.jpg)

If the image doesn't work i can link you it in Skype.

- Lotus

**Comment by Emcitementz** [comment]
This is removed when you leave a map for another or when you're teleported. Since you went back to dalaran on your own, you didn't loose it. 
I'll put a 5 minutes duration on it to prevent this situation.
