### ISSUE TITLE
Vilebranch Hooligans

### ISSUE THREAD

**Issue by redhawk816** [WoWManiaUK/Redemption#722]
The tools are not spawning at any of the possible locations.

**Comment by elagen** [comment]
can you give more information?

**Comment by elagen** [comment]
The tools do spawn 

http://db.vanillagaming.org/?quest=7839#wh-comments

there are 5 locations and i have just done the quest

**Comment by fvicaria** [comment]
![image](https://cloud.githubusercontent.com/assets/9414661/22197254/135be886-e149-11e6-8151-9507e03f7cdb.png)
