### ISSUE TITLE
Deathgrip on a bladestorm

### ISSUE THREAD

**Issue by KyptAMaN** [WoWManiaUK/Redemption#724]
So, I found out that dks can deathgrip while a warrior does a bladestorm, on this server.. 
Its a massive issue.. rly bad, fix it fast. thx.

**Comment by fvicaria** [comment]
As is. Not sure where you played before. As long as you don't stop it's correct. You can still be dragged.
https://github.com/WoWManiaUK/Redemption/issues/721

**Comment by KyptAMaN** [comment]
wait whaaat? idk about you but i use to play on a very well known pvp server called arena tournament 3.3.5 and dks NEVER were able to deathgrip a Bladestorm , its obvs a bug!  I search about it and i found a wotlk video from a private server back then... https://www.youtube.com/watch?v=87CLZyUQ85Y

Trust me i played 3.3.5 and its impossible to deathgrip a bs.  At least in wotlk ;)

**Comment by Emcitementz** [comment]
https://us.battle.net/forums/en/wow/topic/3988232856
I'll stop you there, private servers comparison isn't the way you should go.
You've played on a quite famous PvP private server? Guess what? The way bladestorm has acted on this server wasn't blizzlike as showed.
