### ISSUE TITLE
[Quest] Investigate the Blue Recluse

### ISSUE THREAD

**Issue by iggapres** [WoWManiaUK/Redemption#725]
This is a mage class quest that takes place in the Blue Recluse, in Stormwind: http://wotlk.openwow.com/quest=1920

It is impossible to capture the "creatures". The appear using the scroll, the fight is alright, but once stunned, using the crate on them has no effect (an error message appears telling it's not the right time to do it).

Trying to use the crate on the creature at another moment doesn't change anything.

**Comment by fvicaria** [comment]
It works.

**Comment by iggapres** [comment]
no

**Comment by fvicaria** [comment]
I has been fixed in dev server. I will be applied this Wednesday.
