### ISSUE TITLE
Warlock Quest Area for Voidwalker

### ISSUE THREAD

**Issue by Dusticles** [WoWManiaUK/Redemption#727]
The cavern in which you must get a certain item next to ogrimmar on the right hand side goin into the mountain have minion summoners who summon Voidwalkers who are a bit too tough for a low level. Can we scale the voidwalker power down a bit? Hopefully tryin this for yourself will give you the idea of the superiority of the voidwalkers which have handlers

**Comment by fvicaria** [comment]
Send link to the NPC and we will check it.
