### ISSUE TITLE
[NPC] Ice crown Citadel Geist Bug

### ISSUE THREAD

**Issue by Dusticles** [WoWManiaUK/Redemption#728]
The geists on the Tubes goin to Festergut or rotface have Geists on them... There is somethin wrong with them not being able to jump.. perhaps enable them to havea  spell to jump on target aggroed so that they can jump down to the target, rather than being stuck up there puting players in combat before the boss. Can we fix this? :)

**Comment by fvicaria** [comment]
Can you link the npc please?

**Comment by fvicaria** [comment]
http://www.wowhead.com/npc=37038/vengeful-fleshreaper

**Comment by fvicaria** [comment]
Not in Redemption yet.
