### ISSUE TITLE
[Quest] Investigate the Blue Recluse

### ISSUE THREAD

**Issue by Alitoni** [WoWManiaUK/Redemption#729]
After picking up the quest and items, upon entering the Blue Recluse there are "spirits" already spawned inside the pub. After subduing (stunning) the spirit, I am unable to capture it. I don't know if it is because they are already there? I tried abandoning the quest and picking it up again, but still these spirits are there.

**Comment by fvicaria** [comment]
The quest works 100%. Please check with someone else that has done it. You may benefit from watching the video or someone doing it.

**Comment by fvicaria** [comment]
Something broke on this.
