### ISSUE TITLE
Barbershop Game crash

### ISSUE THREAD

**Issue by hellersche** [WoWManiaUK/Redemption#730]
The Barber crashes the Game when you scroll through the hairstyls it crashes everytime when you scroll to the next style after the short hair style.

I'm using a fresh 3.3.5 enGB install from disk and patched your files manually and then i use the latest launcher to start the game.

**Comment by fvicaria** [comment]
This is a known issue. Get our full client and if you don't have it yet. Then you may need to first choose another haircut or customize your character using the Customization NPC.
There will be no work on this area.
Apologies for that.
