### ISSUE TITLE
[Quest]Flight of the Wintergarde Defender

### ISSUE THREAD

**Issue by rhadei** [WoWManiaUK/Redemption#731]
There are supposed to be a number of helpless villagers running around in back of Wintergarde Keep, but there don't seem to be any. Occasionally, I'll see one if I'm using the "Soar" setting on the gryphon, but the villager will vanish as I reach it.

I've tried abandoning and re-taking the quest, logging and relogging, and coming back several times over the period of a week to see if anything would change, but no difference. I'm running with the most recent launcher and client on Windows.

This quest isn't necessary to leveling per se, I know, but is a part of the Alliance chain for the Veteran of the Wrathgate achievement.

**Comment by fvicaria** [comment]
![image](https://cloud.githubusercontent.com/assets/9414661/22284131/ac1f20fc-e2dd-11e6-9da2-adfdc573effb.png)

I will add a few more but this is not a bug.
