### ISSUE TITLE
[Object] Ethereum Prisons

### ISSUE THREAD

**Issue by philoudu16** [WoWManiaUK/Redemption#732]
The Ethereum Prisons (object id from 184418 to 184431) in Netherwind seem to not respawn when consumed (like the eggs in Coldarra used to (#621)) or do not spawn at all. (I believe they do actually spawn on server restarts but do not respawn correctly once they are consumed since they are present on the dev realm but i did not get to see them on redemption.)

**Comment by elagen** [comment]
can you give more information on the quest?

**Comment by philoudu16** [comment]
When you open a prison with a key, a random mob spawns. It can be a friendly mob from one of the Outland factions (you then gain reputation for that faction) or an hostile mob which will drop an Ethereum Prisoner ID Tag (http://wotlk.openwow.com/item=31957).

These tags are needed for two quests : Ethereum Secrets (http://wotlk.openwow.com/quest=10971) and the repeatable version Ethereum Prisoner I.D. Catalogue (http://wotlk.openwow.com/quest=10972).

**Comment by fvicaria** [comment]
They are currently taking 10 minutes to respawn. I will reduce a bit.

**Comment by philoudu16** [comment]
Are you sure about this? On redemption, they were absent every time i checked (i spent quite some time in the area while questing) and they never came back, until there was a server restart. And then i opened them at the rate of 2/3 every hour and only those which i opened were missing when i was coming back, until none were left to open. So it may not be a respawn timer problem (or if so, it was way longer than 10 min ;) )
