### ISSUE TITLE
[Quest] What do you Feed a Yeti, Anyway? Quest #2

### ISSUE THREAD

**Issue by Dusticles** [WoWManiaUK/Redemption#733]
Savinia Loresong gives this quest in the Silver covenant Pavilion
The required items are North Sea Shark Meat to complete quest...However none are obtainable by the description of the quest log

**Comment by fvicaria** [comment]
Please read the instruction on how to log an issue properly. Include links to quest, npc, images if needed.

**Comment by elagen** [comment]
http://www.wowhead.com/quest=14112/what-do-you-feed-a-yeti-anyway

wow head says it will be there and they are
