### ISSUE TITLE
Threat From Above Quest #3

### ISSUE THREAD

**Issue by Dusticles** [WoWManiaUK/Redemption#734]
Defeating Chillmaw and his 3 cultist bombadiers are impossible... why? because they aren;t where they are suppost to be! The quest can;t be done because they are no where to heb found! Quest receieved by Eadric the Pure in Argent Pavilion.

**Comment by elagen** [comment]
i have just done this q -

http://www.wowhead.com/quest=13682/threat-from-above

the Cultist Bombadiers get spawned by Chillmaw - and the quest does say u need 3 people 

i found chillmaw where wow head said he would be
