### ISSUE TITLE
[NPC] Lunar Festival Harbinger

### ISSUE THREAD

**Issue by redhawk816** [WoWManiaUK/Redemption#735]
The Lunar Festival Harbinger does not give a new invitation when asked.

**Comment by Zan511** [comment]
Yes, that's true. We'll look into it.

**Comment by elagen** [comment]
When you have done the first q with the fireworks - and get the invitation its ok

but when you ask Lunar Festival Harbinger for another invitation - the NPC does not give

http://www.wowhead.com/npc=15895/lunar-festival-harbinger

**Comment by jarvik76** [comment]
![image](https://user-images.githubusercontent.com/46089380/73120294-f2709c80-3f63-11ea-95d8-78ed688d03ff.png)

**Comment by jarvik76** [comment]
COnfirmed fixed in dev.
