### ISSUE TITLE
[Quest] Rise, Obsidion

### ISSUE THREAD

**Issue by Dragonfly414** [WoWManiaUK/Redemption#736]
I saw that this quest was noticed earlier: https://github.com/WoWManiaUK/Redemption/issues/154
But still not fixed.

Obsidion can't be killed, he is lying on the ground, non attackable.
The NPC Lathoric the Black isnt there. When you click on the altar and you click the button there is a NPC spawning; Dorius.

But not Lathoric.

Do I something wrong or is the quest still bugged??

Thanks for checking

Flamable

**Comment by GM-Gathios** [comment]
Unfortunately, this issue has returned. 

When interacting with the altar Dorius spawns and says: 'Fools, I knew that if I played upon my brother's feeble emotions, he would send 'rescuers.' Then he despawns and nothing happens.  Obsidion is not attackable and Lathoric is absent.

**Comment by wow-mania** [comment]
Pretty sure it works and it is probably an NPC reset issue. Try it on dev.

**Comment by GM-Gathios** [comment]
Just tried on PTR, samew thing happens
