### ISSUE TITLE
[Quest] The Admiral Revealed

### ISSUE THREAD

**Issue by schwebs** [WoWManiaUK/Redemption#737]
http://www.wowhead.com/quest=12852/the-admiral-revealed
The admiral is dealing 9k+ hits ( on a lvl80 dk ), that makes him impossible to kill.

**Comment by elagen** [comment]
the quest does say it needs 5 people

**Comment by schwebs** [comment]
If i'd do this with 5 79er like recommended, the group would wipe within seconds.
2 hits from that guy and you are dead. Have you even tried it? A gm did and told me this is bugged so i reported it.
