### ISSUE TITLE
[Achievement] Mine Sweeper

### ISSUE THREAD

**Issue by schwebs** [WoWManiaUK/Redemption#738]
http://www.wowhead.com/achievement=1428/mine-sweeper

If i counted correctly, i should have gotten the achievement about 4 times today.
seems bugged.
flew near to a mine and got knocked back on my wind rider, continued 9 more times -> no achievement.

**Comment by elagen** [comment]
the ach isnt bugged - it just takes a while to get the ach - i just got it
