### ISSUE TITLE
Laptop keeps disconnecting from wifi while playing wow 

### ISSUE THREAD

**Issue by Gunscrusader** [WoWManiaUK/Redemption#741]
I have had this problem ever since i downloaded the latest wow mania client. I am running on windows 10, but my brother who runs on windows 7 also gets disconnected from the wifi at the same time as i do. Everything runs normally, until i just randomly disconnect from the wifi. The router doesnt lose connection to the internet, our computers running the game gets disconnected. After it occurs, we can simply just reconnect, but it is very frustrating because we have to constantly close the game with task manager and reopen it, just for it to disconnect later. All of the other devices that are connected to the wifi, including phones, tablets and other computers without wow, doesnt disconnect at all like me and my brothers' laptops. This only happens with the computers running wow. This is a very frustrating problem that i have searched for on the internet several times, but all of those solutions, like updating drivers, resetting router etc. doesnt work. Please help!

**Comment by fvicaria** [comment]
Sorry this repository is for server and game issues. This issue is a client side and local environment. Contact our support on Skype or email for some guidance.
