### ISSUE TITLE
Dalaran Crash

### ISSUE THREAD

**Issue by Ixion73** [WoWManiaUK/Redemption#742]
Hi, I am using your launcher with the most upto date patch on a Windows 10 Machine.

Everytime I go to Dalaran, My game crashes after I walk a short distance, I can stand still for eternity and nothing happens, but the moment I take some steps, it crashes with an Error.

![untitled](https://cloud.githubusercontent.com/assets/25385763/22371189/9d235990-e48d-11e6-8d0a-1570765b72f7.jpg)

**Comment by fvicaria** [comment]
This is a client issue.
Download our client and always use the Launcher to start the game.
If problems continues try reducing the Texture Filtering in Video Settings to the minimum.
I can give you more guidnace over Skype if needed.
