### ISSUE TITLE
Nightfall broken

### ISSUE THREAD

**Issue by zyklonb** [WoWManiaUK/Redemption#744]
If you're getting a procc while casting shadowbolt, that shadowbolt will consume the nightfall procc.
Not how its supposed to work.
https://www.youtube.com/watch?v=m9T1uFof1ms

**Comment by elagen** [comment]
With the Spell Nightfall - it does make the Shadow Bolt a instant cast

but when casting shadowbolt and when nightfall is proc'd - the casting shadow bolt is consuming the proc when it should not

http://wotlk.openwow.com/spell=17941
