### ISSUE TITLE
[Spell] Frost Nova - Mage

### ISSUE THREAD

**Issue by philoudu16** [WoWManiaUK/Redemption#746]
Part of the main Mage post #654 (splitting it to help the devs keep track of what still needs fixing):
Frost Nova is being broken with any damage dealt. Tested with all the dummies and the only one on which it does not break (with a melee attack dealing 2 damage) is the Boss one.

**Comment by elagen** [comment]
not used on a Training dummy - and 2 melee attack - does not break the nove - around 20% of the health breaks the frost nova
