### ISSUE TITLE
PvP Trinkets 

### ISSUE THREAD

**Issue by jurrianvg** [WoWManiaUK/Redemption#749]
Hello readers, I've did some research about PvP, and to be fair the range pvpers have a hard time at the moment because the timetable resets for the stun when you use your trinket so that means, a warlock fears you and after that fears you again, so go got a 8 secs fear and a 4 secs fear, you trinket and he fears you for 8 secs again, it should be that you get a 1 second fear and after that you are immune to fear stuns and that kind of stuff, but now it resets so it makes the use of a trinket kinda useless while it's a mayor fragment for pvp, Also you CANNOT trinket away silences which should be possible in WotLK, you CANNOT trinket away the lock from it, so for instance you are a priest casting flash of light vs a Deathknight, the Deathknight uses Strangulate, here comes not lock from so you should be able to trinket this away, but when you cast mindfreeze on the target while casting flash of light he should get a Holy lock for 5 secs, this should not be able to be trinketed off. So at the moment a DeathKnight uses strangulate, they don't have that much other stuns you can trinket, you are dead as a caster or healer you are unable to do anything for 4 seconds.

**Comment by zyklonb** [comment]
No thats wrong, you werent able to trinket silences until Cataclysm. 
And i have no idea if using pvp trinket resets DR which it obviously should not but i dont think it does, i havent noticed it atleast

**Comment by elagen** [comment]
With the PVP trinket as zyklonb Said : the Trinkets in Wotlk do not do anything against silence

here is what every trinket says 

Removes all movement impairing effects and all effects which cause loss of control of your character.

which is Polymorph - Hex - Fear - Slow - Etc...  - the trinkets do not get rid of silence

and the trinkets have 1min to 2 min CD - that is the way of pvp
