### ISSUE TITLE
[Talent] Nightfall (warlock)

### ISSUE THREAD

**Issue by huqboss** [WoWManiaUK/Redemption#750]
Talent has chance to give to caster a buff "Shadow Trance (ID=17941)" - Your next Shadow Bolt becomes an instant cast spell. Since 2-3 days it doesn't work properly: if this buff happens while casting shadow bolt (ID= 47809) is consumed by currently casted shadow bolt, without giving any profit. Before it was working fine - buff wasn't consumed by currently casted, but next one, which was instant cast.

**Comment by fvicaria** [comment]
Duplicate. Please search before creating new issues.
