### ISSUE TITLE
Lich King Fight Stun Valkyr issues

### ISSUE THREAD

**Issue by Plutoni** [WoWManiaUK/Redemption#751]
I'm a druid and i noticed that Maim in cat form does not stop Valkyr from moving, and im not sure if Bash in bear form works. These two stuns should be working on valkyr.

**Comment by fvicaria** [comment]
This has already been fixed in dev.
Not necessarily as you wish but as per Blizzard on 3.3.5a
Let me know if there is still a problem after Wednesday.
