### ISSUE TITLE
Sheathed weapon

### ISSUE THREAD

**Issue by Dusticles** [WoWManiaUK/Redemption#755]
Hey guys! Dusty here! I was wondering if this was a bug or not where 
Journeyman's Staff http://www.wowhead.com/item=15925/journeymans-stave
is bugged on its sheathed properties such as being on your back or not.. seeing how i sheath and unsheath it i pull it out of my belt the staff even though it is classified as a off hand... and if it isnt a bug that this is what it does.. is there anyway we could have this model on our back? it would bring some more oppurtunities for transmog in the future :)

**Comment by elagen** [comment]
where that is a held-in-offhand weapon - it wont show on your character until you weapons are showing in your hand
