### ISSUE TITLE
[QUEST] Writ of Safe Passage

### ISSUE THREAD

**Issue by Readerlady** [WoWManiaUK/Redemption#756]
This quest originates in Light Hopes Chapel. There is a caravan that is suppose to move so you can save everyone. Once saved a person joins you and signs the writ. You then turn the writ in to complete the quest. The caravan never seems to leave Light Hopes? I do believe that originally the caravan started at one of the pvp towers and then ended up in the northern part of Eastern Plaguelands?

**Comment by elagen** [comment]
From this page i dont know if it is the way it is suppose to be but go to the quest at the times on the page and see if it happens

http://wowwiki.wikia.com/wiki/Quest:Writ_of_Safe_Passage

if not - we will get to tweaking

**Comment by fvicaria** [comment]
Is this not doable at the moment?

**Comment by elagen** [comment]
It's not that it isn't doable it is just the questhing can be done at certain times of the day

**Comment by Readerlady** [comment]
I will check on this between 6 and 8 server time. Thanks for the information.

**Comment by Readerlady** [comment]
I have still had no luck getting him to move his little donkey crew out! I think he is too comfortable in Light Hopes. Possibly you could send a blight or two there to motivate him to move on.... maybe Packmaster Stonebruiser can have a talk bubble that one can use that starts the event?

**Comment by fvicaria** [comment]
OK for the meantime just go to Dispatch Commander Metz and handle the quest.
He will recognize you when you get there.
