### ISSUE TITLE
[Achievement] Ice Crown: The Final Goal

### ISSUE THREAD

**Issue by schwebs** [WoWManiaUK/Redemption#757]
I am missing 2 Quests for this Achievement. 
Looks like i never finished the questchain from the bone witch http://www.wowhead.com/npc=30232/the-bone-witch
I dont know where i stopped and i cant get any more quests from her, the only thing i know is that i have never done: http://www.wowhead.com/quest=13142/banshees-revenge

**Comment by philoudu16** [comment]
I believe if you are interested in this achievement, you may be interested in the other achievements leading to Loremaster. I suggest you get an addon like Everyquest. With it, you can easily ask the server which quests you have completed and you'll be able to check which you are still missing ;)
