### ISSUE TITLE
The sons of Hodir quartermaster

### ISSUE THREAD

**Issue by Jeanpko** [WoWManiaUK/Redemption#758]
Hi, 

user: Jeanpko
Characters: Pko and Scheise

I have a problem with my account, I have 2 character and i did the quests and got the reputation with both in the faction the sons of hodir. 

The problem is that i cant see the quartermaster (NPC ID: 32540) with my druid but with my rogue i can ( please check the pictures).

I think my druid is bugged. 

Please check that and let me know. 

Thank you.
![imag0059](https://cloud.githubusercontent.com/assets/24440942/22437974/924154ee-e700-11e6-8675-58bd7f722750.jpg)
![imag0061](https://cloud.githubusercontent.com/assets/24440942/22437973/92344498-e700-11e6-9275-818bb9248f5a.jpg)

**Comment by fvicaria** [comment]
This is a player issue. Some quest missed and you are out of phase. Open a ticket.
