### ISSUE TITLE
Jagged Shard - quest item not giving quest

### ISSUE THREAD

**Issue by Cinoril** [WoWManiaUK/Redemption#759]
Received the item, but when I right click on it I get the error "You don't meet the requirements for that quest." GM Arawyn spent a long time trying to make this work, but couldn't and advised for me to open a ticket.

Quest drop item: http://www.wowhead.com/item=43242/jagged-shard
Quest: http://www.wowhead.com/quest=13136/jagged-shards

**Comment by Plege** [comment]
you need to do the questline until after you reanimated the guy in the dungeon. After that you will be able to take the quest from the Jagged Shard
