### ISSUE TITLE
[Quest] Test Flight: Ruuan Weald

### ISSUE THREAD

**Issue by Dragonfly414** [WoWManiaUK/Redemption#760]
http://www.wowhead.com/quest=10712/test-flight-ruuan-weald

When I do the last one, the quest said its completed, but I cant end it at the NPC. 
Its telling me I dont have Spinning Nether-Weather Vane. But I have it in my inventory.
Have done the quest again, but same issue.
Also my friend tried it, also same issue.

Think the questender doesnt see the item.
Please check?

Flamable

**Comment by Dragonfly414** [comment]
if its fixed in Dev Server, how long before it comes to the "real"  server?

**Comment by fvicaria** [comment]
This Wednesday morning after scheduled update.

**Comment by Dragonfly414** [comment]
thank you very much!!
