### ISSUE TITLE
[Quest]: If he cannot be turned

### ISSUE THREAD

**Issue by respectdat1** [WoWManiaUK/Redemption#761]
http://www.wowhead.com/quest=12897/if-he-cannot-be-turned

Quest is fine until you have to turn it in. Koltira Deathweaver doesn't show up on Orgrim's Hammer at all.
http://www.wowhead.com/npc=29795/koltira-deathweaver

Only reason I care enough is because I want the Tabard of the Ebon Blade, which I can only get after completing this quest.

**Comment by fvicaria** [comment]
![image](https://cloud.githubusercontent.com/assets/9414661/22462250/73aca1e2-e7a4-11e6-8193-6320eb5cc583.png)

What could have happened is that sometimes the NPC "falls" from the ship. Try again please.
