### ISSUE TITLE
Mutiny on the Mercy

### ISSUE THREAD

**Issue by Marvin023** [WoWManiaUK/Redemption#763]
this quest is not working. no mutinous sea dogs or barrels are spawning.

**Comment by elagen** [comment]
This is the quest

http://www.wowhead.com/quest=11527/mutiny-on-the-mercy

Thelse are the mobs that should spawn on the boat and they do not 

http://www.wowhead.com/npc=25026/mutinous-sea-dog

**Comment by fvicaria** [comment]
![image](https://cloud.githubusercontent.com/assets/9414661/22461835/d3856a9c-e7a2-11e6-8c6b-dd798fabbe5a.png)

You are probably on the wrong boat.

**Comment by Marvin023** [comment]
I know what boat to be on. the one that pats around.
