### ISSUE TITLE
Path of the Adept

### ISSUE THREAD

**Issue by bogey2230** [WoWManiaUK/Redemption#764]
Quest line for paladins - 
 I am ' Crate of Bloodforged Ignots ' which are located in Shadowfang keep and with Landen Stillwell a blacksmith who is locked up. I entered SK, found Landen Stillwell, opened dialogue with him, he said ' take the crate ' , he turned into a worg and attacked me. I killed him, no loot from body, no loot from a crate inside his cell, no Ignots anywhere.

**Comment by elagen** [comment]
The crate of ingots are in the stables in sfk
