### ISSUE TITLE
[Spell] Missile Barrage

### ISSUE THREAD

**Issue by schwebs** [WoWManiaUK/Redemption#765]
Hey, 

seems 'Missile Barrage 
http://wotlk.openwow.com/spell=54490
is broken.
When the spell proccs, i do max. 2 "Arcane Missiles" while channeling, but it should be 5.
1 Missile per 0,5 sec. for 2,5 secs.

**Comment by elagen** [comment]
it is fixed in dev we are waiting to apply the patch
