### ISSUE TITLE
[Quest] Test Flight: Ruuan Weald 

### ISSUE THREAD

**Issue by Dragonfly414** [WoWManiaUK/Redemption#766]
https://github.com/WoWManiaUK/Redemption/issues/760

After server reset, I tested it on my char (after cache clearing and getting the quest new)...
But still at the questender a grey ?

**Comment by Dragonfly414** [comment]
btw.. the quest is doing better than before ;) Now I dont die at the landing :)
Only giving the questender the quest istnt working...
See dont sees the item in my inventory.

In the quest is standing: quest complete

**Comment by fvicaria** [comment]
This is a refresh issue just logout and back in.
The quest works.
