### ISSUE TITLE
[PVP] Wintergrasp Fortress Tower Guns

### ISSUE THREAD

**Issue by keboid** [WoWManiaUK/Redemption#767]
It was told to be fixed but that's not the case. There were simply Tower Guns deleted from the walls, those never appear now. Its nearly impossible to defend since there are only 2 guns/tower. Also, the Tower Guns are still misplaced and turned wrong, you can sometimes shoot inside tower, not outside.

Pictures about the misplacement in the Fortress Towers:
https://s24.postimg.org/rgxrhpmwl/Wo_WScrn_Shot_012617_132833.jpg

Southern Tower Gun placed correctly:
https://s30.postimg.org/e4pxoh2m9/Wo_WScrn_Shot_012617_132932.jpg

As you can see on the southern tower the gun is more near to the end of the platform, like it should be, that way you can shoot correctly. You can not shoot like that with the fortress tower guns like that because its more far from the end of the platform. you can shoot the platform itself not the enemies/sieges nearby.

**Comment by fvicaria** [comment]
Thanks for your persistence. I have fixed all of them now. :)
