### ISSUE TITLE
[Spell] Arcane Mage T10 2 bonus 

### ISSUE THREAD

**Issue by Silva69** [WoWManiaUK/Redemption#770]
T10 2 for arcanes mages is working but is not working a 100%, the way of working is different from arcane to fire mage, because the bonus "pushing the limits" (12% for 5secs) is proc early. we only have to get that proc when you finish cast arcane missiles with the proc missile barrage, not at the begining, check this video from retail and you see what im talking, just see when the bonus proc and compare

https://www.youtube.com/watch?v=jD4Ds6f_6wo

**Comment by fvicaria** [comment]
Please link the actual bonus spell.

**Comment by philoudu16** [comment]
Val knows about this one and is already working on it i believe.

Here is the spell if you still need it ;) 
http://wotlk.openwow.com/spell=70752
