### ISSUE TITLE
ULDUAR

### ISSUE THREAD

**Issue by wcslanker** [WoWManiaUK/Redemption#771]
I've read a few of the previous posts, that were closed for reason I don't know why.... but the bosses are still very bugged in Ulduar. For instance, and this is the biggest bug that makes it impossible to do, the BOSSES do not reset properly if you wipe on them. They evade if you try to attempt them again (if you can even reenter the instance)...... Certain bosses I know what is wrong with them is: 

The siege: 
-Flame Leviathon (everything is wrong with that encounter, next to no mechanics work on it making hard mode impossible to do)... Pyrite cannot be collected, System Shutdowns, cannot launch players to take out turrets, I believe any passengers die almost instantly, etc.
-XT-002 Deconstructor spawns many more adds than should be scripted
-Razorscale is NOT possible as you cannot shoot him down.

Antechamber:
-The Assembly of Iron theres not too much I can say other than the fact that Stormcaller Brundir is just crazy bugged (runs outside of the room, and his lightning whirl is out of whack).. that's all I can tell about that fight since he's the one that stood out the most.
-Kologarn as I saw in another post does NOT reset if you wipe on him

The Keepers: 
-Thorim is the only boss I have done for the keepers, but I know for a fact that the one time I attempted him he did not jump down properly which lead to wipe which lead to him not reset and thus lead to end of the raid.

I do know that fixing these problems will take some time, but I will keep updates on certain mechanics that need fixing. As long as you keep adding comments to what is being fixed or what you have fixed then maybe we can expedite this process... a start to this would be to fix the evading/ only being able to have 1 attempt on each boss. 

 -Vivamyaggro

**Comment by wcslanker** [comment]
Still haven't heard any feedback. Trying to work with you, but cannot if there is no response.

**Comment by Eurycakes** [comment]
These comments are true. even the horde side has issues i thought the goal was to be as close to live experiance as possible? These issues exist, our guild did alot of asking around about them and he isnt the only one complaining, we are trying to help our server grow and expaned so we can have more players, We just want to have a ALL around wonderful wow experiance, and play with others. Please look at these issues and work with us! We have nothing but good intentions.     

-Euryphasea

**Comment by elagen** [comment]
one of the problems that we testers have - is finding the correct tactics with the correct spells - then we have to report with the spells that are working and the spells that are not working - **this takes us longer to do**

then we have to report back with our findings which then takes longer to fix 

if you look how this issue and the notes i have done it will make it a lot easier for us
https://github.com/WoWManiaUK/Redemption/issues/748

https://github.com/WoWManiaUK/Redemption/wiki/How-to-Properly-Report-an-Issue
also read this first - so we can test quicker and do it faster

and report each issue with different boss fights or each area this helps us move quicker and update 1 issue at a time

thank you for your patience - sorry for the late response but we also have more issues to deal with also

**Comment by wcslanker** [comment]
you do realize #748 is for Malygos, NOT, Ulduar... Can you please take your own advice and actually read my report, rather than, telling me I'm wrong.

**Comment by elagen** [comment]
its just an example to do a detailed report of what spell is not working and so on

**Comment by wcslanker** [comment]
Isn't that what they get paid for? I mean come on the server is now 2 years old, and the 2nd highest raid is not at all properly scripted... I would go through all the trouble of posting the spells and what not is wrong with it.. BUT EVERYTHING is wrong with it. I don't get paid to make a long list of abilities that is not working right.

**Comment by elagen** [comment]
Then it takes lonelager to get repaired so if don't have anything constructive to say please don't say anything

**Comment by Plege** [comment]
By the way none of the testers are getting paid. We do our work for the people playing on the server so all have a better experience. And all of us have real jobs and a real live so instead you could say something like "2 jears running and 800 reported issues solved. Great job. And i bet there must be tons of issues that got solved before they ever got posted on github.. How are so few people doing all this.. Respect and thank you guys".

**Comment by wcslanker** [comment]
No ty, this server is two years old now. I know of servers who DO NOT get donations and run with little to no bugs.

**Comment by fvicaria** [comment]
Shouldn't you be playing there then?

**Comment by wcslanker** [comment]
Janitor, you really don't care about your server don't you?
