### ISSUE TITLE
Missing credit for Icecrown: The Final Goal?

### ISSUE THREAD

**Issue by Cinoril** [WoWManiaUK/Redemption#773]
The quests at the Sunreavers pavillion (not the dailies) are said to count toward The Loremaster achievement (http://wotlk.openwow.com/achievement=1682), but they are not going toward the Icecrown quest achievement (http://wotlk.openwow.com/achievement=40). I have completed 5 so far and my count has not changed for any of them:

A Valiant of:
Silvermoon: http://www.wowhead.com/quest=13696/a-valiant-of-silvermoon
Undercity: http://www.wowhead.com/quest=13695/a-valiant-of-undercity
Sen'jin: http://www.wowhead.com/quest=13693/a-valiant-of-senjin

The Valiant's Challenge
Undercity: http://www.wowhead.com/quest=13729/the-valiants-challenge
Silvermoon: http://www.wowhead.com/quest=13731/the-valiants-challenge

**Comment by elagen** [comment]
here is a list of Quest for the Ach http://www.wowhead.com/achievement=40/icecrown-the-final-goal

people have done this before and they have had no problem - is some quest are not do able and they are in the list then report the quest that is not working properly
