### ISSUE TITLE
Shadowmoon Valley-quest-The Soul Cannon of Reth'hedron

### ISSUE THREAD

**Issue by Tiralaral** [WoWManiaUK/Redemption#774]
This is a character quest issue for Tiralaral. Followed Wowhead.com and found Sar'this in Lake Jorune. I clicked the NPC, I then clicked the dialog box, "I am an envoy of Balthas. I need a Flawless Arcane Essence. . .etc. The quest will not advance from this first dialog box. I read the comments section to see that Sar'this calls forth elementals to be killed to get to the final elemental which is the Flawless Arcane Elemental. [http://www.wowhead.com/item=32822/flawless-arcane-essence#comments] This link shows the elemental you must kill to get the Essence.  [http://www.wowhead.com/npc=23100/flawless-arcane-elemental]  I am using your client and your latest launcher. I use Windows 10.

**Comment by fvicaria** [comment]
Duplicate #691
