### ISSUE TITLE
[Spell] Distract

### ISSUE THREAD

**Issue by wookie1577** [WoWManiaUK/Redemption#775]
The ability should be turning mobs toward the center of the green area of effect that displays when using the ability. This does not always work as mobs often will show reaction to the distract, but not turn. For the instances that those mobs do turn, quite often when trying to use an ability which requires the player to be behind the mob, a warning message will pop up stating the player must be behind said mob, despite the display showing the player IS behind the mob. I believe this is because visually, the mob turns but it truly has not and is likely still facing the direction that it was prior to being distracted.

**Comment by Plege** [comment]
http://wotlk.openwow.com/spell=1725

**Comment by wookie1577** [comment]
The description in the link for that ability actually helps to explain what isn't working with Distract-attracting the attention of all nearby monsters for 10 seconds."

I've included 2 screenshots: one showing placement of the area of effect, which should result in both raptors turning to face the center-which was placed slightly to the left of the rear raptor-and then the second screenshot shows both raptors with the reaction indicator over their heads, yet only the rear raptor turns toward the "distraction". 

![wowscrnshot_020517_082109](https://cloud.githubusercontent.com/assets/25553641/22626907/f76b29aa-eb7c-11e6-9705-3875cf272b7e.jpg)
![wowscrnshot_020517_082111](https://cloud.githubusercontent.com/assets/25553641/22626910/fe70b58a-eb7c-11e6-8706-1c7a625b5570.jpg)
