### ISSUE TITLE
[Quest] Ar'tor, Son of Oronok

### ISSUE THREAD

**Issue by agustinmorelle01** [WoWManiaUK/Redemption#776]
It seems that the quest [Ar'tor, Son of Oronok] (Part 1 of 2) is bugged.

**Comment by Plege** [comment]
Please give some additional information. What is the bugg? NPC id's from open wow and stuff

**Comment by fvicaria** [comment]
http://www.wowhead.com/quest=10527/artor-son-of-oronok

**Comment by agustinmorelle01** [comment]
its fixed?

**Comment by Plege** [comment]
It has been fixxed on dev server. It will be applied to redemption with the next patch
