### ISSUE TITLE
PVP randomly activating, Southern Barrens

### ISSUE THREAD

**Issue by wookie1577** [WoWManiaUK/Redemption#779]
With both of my newer Horde-aligned characters, each time they have come near Camp Taurajo, the PVP indicator would activate, yet while the icon was active, the character would show as PVP disabled. Each time, entering Camp Taurajo cleared the flag, but the most recent time it happened, another Horde was traveling near me and their PVP flag also activated .

I've tried attaching a screenshot showing my PVP flag on, yet showing as disabled. 
![wowscrnshot_020517_005023](https://cloud.githubusercontent.com/assets/25553641/22624554/1e40b424-eb45-11e6-86d7-a402f061fccb.jpg)

**Comment by fvicaria** [comment]
As is. This is a Free-4-All area.
