### ISSUE TITLE
Healing/Buffing Yourself while under 5 min PVP flag renews timer????

### ISSUE THREAD

**Issue by wookie1577** [WoWManiaUK/Redemption#781]
Is this intended? In a PVE area, with the temporary PVP flag on (due to me stupidly buffing an NPC in error because of a mistarget), as the 5 minute timer runs down, if, as a priest, I heal, or buff myself, or even eat/drink after combat, the PVP timer is renewed?

**Comment by wookie1577** [comment]
Adding screenshots...note the first shows 2 minutes left on the PVP flag, and I'm casting Lesser Heal on myself. In the second shot, I'm back at full health, after the heal, with the timer back at 5 minutes. 
**Also notice I'm still by the same corpse, with no new messages in the general chat. 

![wowscrnshot_020517_104720](https://cloud.githubusercontent.com/assets/25553641/22627936/06b09620-eb91-11e6-8b35-919187fb4db4.jpg)
![wowscrnshot_020517_104728](https://cloud.githubusercontent.com/assets/25553641/22627938/09bb333e-eb91-11e6-8c61-a127f84c1fd2.jpg)

**Comment by Plege** [comment]
As I understand (and remember) this you will get your pvp flag back up to full duration if you engage battle with any enemy faction player or npc or if you cast any helpful spells on an allied player being flaged for pvp this includes healing yourself

**Comment by Plege** [comment]
http://wowwiki.wikia.com/wiki/PvP_flag

**Comment by fvicaria** [comment]
As-is.
