### ISSUE TITLE
Death Knight "The Light of Dawn" quest bugged

### ISSUE THREAD

**Issue by mdnightwnd** [WoWManiaUK/Redemption#782]
The Light of Dawn appears to be bugged.  I talk to Mograine and choose "I am ready."  He does his speech and the minions rise.  Mograine then rides off at exceptional speed and disappears.  The minions run at normal speed, but when I get to the chapel, they just stand there and none of the enemy NPCs spawn.  If I wait a few minutes and go back, Mograine has popped again but if I talk to him and choose ready, he does the same thing again.  I can't move out of this zone until I complete this quest.  Help!

http://www.wowhead.com/quest=12801/the-light-of-dawn

**Comment by fvicaria** [comment]
Open a ticket and ask it to be completed. Sometimes it bugs and it can't be reset.
