### ISSUE TITLE
[Quest] Crushing the Crown

### ISSUE THREAD

**Issue by Readerlady** [WoWManiaUK/Redemption#783]
The Snagglebolt's Khorium Bomb does nothing. The quest says you have to destroy the Chemical Wagon but you can't because the bomb does not work.

**Comment by Nogrial** [comment]
confirmed myself

**Comment by redhawk816** [comment]
Confirmed. Please fix.

**Comment by fvicaria** [comment]
http://www.wowhead.com/quest=24666/crushing-the-crown

**Comment by Kalasbyxan** [comment]
Report says upon using http://www.wowhead.com/item=50130/snagglebolts-khorium-bomb on http://www.wowhead.com/npc=38035/chemical-wagon the promt "You can not use that yet" appears.

**Comment by redhawk816** [comment]
Standing in front of the Chemical Wagon, click on the Snagglebolt's Khorium Bomb, then get an error still. It says "You can not use that yet".  Tried moving around the wagon, changing distance and even tried on top of it... same error message.

**Comment by Synathy** [comment]
Looking on Kalasbyxan's report and at http://www.wow-mania.com/armory/?npc=38035, they are npc with the name "Chemical Wagon" which shouldn't be game object but invisible npc. They have a 1 min respawn time according to the armory. I am guessing that these npc didn't spawned when the event started out.
