### ISSUE TITLE
[Quest] You've Been Served. 

### ISSUE THREAD

**Issue by Nogrial** [WoWManiaUK/Redemption#785]
Cannot find Apothecary Hummel, doesn't seem to spawn. can't complete quest

**Comment by Readerlady** [comment]
The quest is already marked as complete when you receive the subpoena to give to him. It comes in a box along with two neutralizing potions. You can't turn it in because he can't be found in the dungeon.

**Comment by Nogrial** [comment]
That's my point.

**Comment by elagen** [comment]
Next time can you more details please like : 

http://www.wowhead.com/quest=14488/youve-been-served#comments is the quest for the Holiday instance

and with the http://www.wowhead.com/item=49635/court-subpoena given from the quest you are to give to http://www.wowhead.com/npc=36296/apothecary-hummel **(which are not there)**

http://www.wowhead.com/npc=36296/apothecary-hummel needs to be added / spawned
