### ISSUE TITLE
[Achievement] Lonely?

### ISSUE THREAD

**Issue by Galagus420** [WoWManiaUK/Redemption#787]
Me, Galagus and another player, Odagord, tried doing this achievement, my second to last to finish the whole thing, and i gathered everything needed, the Romantic Picnic Basket and Box of Chocolates which contained the required delight, Buttermilk Delight, however after following all the correct steps, putting down the picnic basket, sitting down(both of us) and then eating the Buttermilk Delight we didn't get the achievement, we tried two times and didn't work, we even were in team. Please fix!

**Comment by fvicaria** [comment]
http://www.wowhead.com/achievement=1291/lonely

**Comment by Galagus420** [comment]
There is no hearts or music appearing
