### ISSUE TITLE
[Achievement] Tough Love from the Love is in the Air World Event

### ISSUE THREAD

**Issue by Readerlady** [WoWManiaUK/Redemption#788]
Tough Love achievement is to kill the trio of Crown Chemical Co. apothecaries in Shadowfang Keep. The event does not allow you to kill the three apothecaries in the dungeon. They are there but they are green and not targetable. This achievement is necessary for the Love is in the Air achievement.

**Comment by redhawk816** [comment]
Confirmed

**Comment by fvicaria** [comment]
Looks like duplicate from your own previous issue. Please fill in details as instructed on the other issue.
