### ISSUE TITLE
[Pet] Succubus

### ISSUE THREAD

**Issue by Necrosiss** [WoWManiaUK/Redemption#795]
Succubus, was testing it also while writing that post. So pet is on Passive mode, when you put Seduction skill on auto-cast and tell to cast on player, Seduce happen, after it ends pet keep attacking a player and use skill again but not instantly after 1st one end or get break. She use it after few seconds which is pretty strange since global CD on the skill finished. Situation change when you remove auto-cast from Seduction. In that state when you tell to seduce, seduce happen, after it breaks or ends pet go invisible again and follow you which is good. Ill compare it to Felhunter spelllock. Why Felhunter on auto-cast off after you use Spell lock keep attacking the target? He shouldnt even touch a target, suppose to do as Succubus. Cast spelllock when a warlock want it and keep following without charing the target.

Update to Succubus:

So when you enter a combat with succubus and got invisibility on auto-cast, you call Succubus back till u r in fight she will cast Invisibility till combat ends wasting all mana casting only that one thing. Second thing i discover is you CANT seduce feral druid in form it keeps says "Cant target players"(?). Even if this is a cat, seduction since its a players no matter what should work on him. Feral skill Berserk breaks fear and make u immune on it durring the buff time, but there is nothing on dudu that prevents Charm. Everywhere i did play Seduction was working on ferals.

P.S Its hard to confirm all that pet things if some didnt use warlock class from long time. I was playing on different servers + years on warlock. Please take 1h to take a test on all that things.

**Comment by elagen** [comment]
the invisibility spell from succubus 

Makes the Succubus invisible for 5 min.  **Not usable in combat**. Any action will break the effect.

and seduction  

Seduces the target, preventing all actions for up to 30 sec. Any damage caused will remove the effect. **Only works against Humanoids.**

any druid **IS NOT** a humoid as Succubus seduce does not work on beasts
