### ISSUE TITLE
[Quest] Glyph Chasing

### ISSUE THREAD

**Issue by Cunera** [WoWManiaUK/Redemption#796]
When I try to get the Glyph rubbing from Hive'Zora and Hive'Ashi in Silithus, by clicking on them and using the 'Geologists transcription kit', the crystal disappears without me getting the Glyph rubbings. 

Is this a glith/bug of some sort or am I doing something wrong here? Thanks in advance! 

Cunera
 http://www.wowhead.com/quest=8309/glyph-chasing

**Comment by elagen** [comment]
while testing http://www.wowhead.com/item=20453/geologists-transcription-kit is provided and it can not be used to get to receive this item 
http://www.wowhead.com/object=180454/hiveashi-glyphed-crystal
