### ISSUE TITLE
[Quest] Collection of Goods

### ISSUE THREAD

**Issue by Eventor** [WoWManiaUK/Redemption#797]
Collection of Goods, Paladin Quest doesnt seem to work, i went to stratholme and tried to get the sparkling boxes but they are not clickable.

**Comment by fvicaria** [comment]
Needs confirming. Please read how to report an issue from the wiki. It will save developers time.


http://www.wowhead.com/quest=7642/collection-of-goods

**Comment by elagen** [comment]
In Stratholme the Creates which contains the Quest items are un-clickable

the Creates == http://www.wowhead.com/object=181085/stratholme-supply-crate

The Item in the Creat == http://www.wowhead.com/item=13180/stratholme-holy-water

**Comment by Emcitementz** [comment]
![screenshot_13](https://cloud.githubusercontent.com/assets/11377592/22867706/3ee01690-f18d-11e6-9829-09e03d07f1c8.png)
Those ones are clickable.
The ones you're talking about are actually have sparkles indeed and aren't clickable but that's not the ones you have to open so that's kinda normal.
