### ISSUE TITLE
Quest: The Earthen Oath

### ISSUE THREAD

**Issue by redhawk816** [WoWManiaUK/Redemption#801]
We are to kill 7 Iron Sentinels and 20 Iron Dwarf Assailants for the quest,  http://wow.gamepedia.com/Quest:The_Earthen_Oath   I was not receiving credit for each kill.  I had to kill about 30 sentinels to get credit for 7 of them,  and about every other Assailant would give me credit.

**Comment by elagen** [comment]
If the mobs are fighting the Npc's there you will not get credit for the kill 

You will need to fight the mobs that are NOT attacking the Npc's to get the credit for the kill and then you can complete the quest
