### ISSUE TITLE
[Raid] Temple of Ahn'Qiraj

### ISSUE THREAD

**Issue by Mitko445** [WoWManiaUK/Redemption#802]
There are suposed to be greater scrab coffer in the instance. I searched in the whole instance and i cant find them. Also the boss Ouro didnt spawn i killed twin emperors and the trash to him then the spawner and he just didnt spawn.

**Comment by fvicaria** [comment]
There is not such a thing as Greater Scarab Coffer. The Greater Scarab Coffer Key opens the Large Scarab Coffer.

I have added the objects. It should be updated by Wednesday at the latest.
