### ISSUE TITLE
[Quest] Convocation at Zol'Heb

### ISSUE THREAD

**Issue by Dragonfly414** [WoWManiaUK/Redemption#804]
http://www.wowhead.com/quest=12730/convocation-at-zolheb

you get an item to call some NPC at the summoning circle.
But I get the notification: You can't do that yes.
Nothing happen

Hear somebody else had same issue at this quest.

Hope you can fix it,

Flamable

**Comment by elagen** [comment]
you have to stand in the middle of the summoning circle and use http://www.wowhead.com/item=39566/prophet-of-akali-convocation

i have tested this and the quest worked fine

**Comment by Dragonfly414** [comment]
I stand everywhere in the circle but still message: cant do that yet ???

**Comment by Dragonfly414** [comment]
![wowscrnshot_021317_090205](https://cloud.githubusercontent.com/assets/24796963/22875361/92164e90-f1cb-11e6-8d5a-b7cd94ff167f.jpg)

this is what I get when I use the item in middle of circle
