### ISSUE TITLE
[NPC] Jangdor Swiftstrider 

### ISSUE THREAD

**Issue by Kalasbyxan** [WoWManiaUK/Redemption#806]
The NPC (http://www.wow-mania.com/armory/?npc=7854) offers leatherworking quests. Four of them can't be handed in even though marked complete in the log with items in the inventory. The continue button upon interacting is greyed out as if items aren't in the inventory.

- Wild Leather Helmet (http://www.wow-mania.com/armory/?quest=2857)
- Wild Leather Vest (http://www.wow-mania.com/armory/?quest=2856)
- Wild Leather Leggings (http://www.wow-mania.com/armory/?quest=2859)
- Wild Leather Boots (http://wow-mania.com/armory/?quest=2858)

**Comment by fvicaria** [comment]
This is a refresh issue. It happens sometimes. Try longing off and back on.

**Comment by Rushor** [comment]
you need to remove and retake the quest, then you can reward it

**Comment by fvicaria** [comment]
This is similar to #818 do you know a way to fix it @Rushor ?
I thought about liking the quests in a chain but that is a hack I wanted to avoid.

**Comment by Rushor** [comment]
i thought the reason for the issue is that after a serverdown, the progress of the quest isn't saved for the player, so if the player has all the items, he still cannot turn the quest in

**Comment by fvicaria** [comment]
On #818 if you get all quests at once and go collecting the material they get completed but the question mark is grayed out and you can't deliver them. You need to get one at a time I think.

**Comment by Rushor** [comment]
kk

**Comment by fvicaria** [comment]
![image](https://cloud.githubusercontent.com/assets/9414661/23018893/b3cf51c6-f437-11e6-9b0c-f8b95093b036.png)

Get one quest at a time.
As Rushor mentioned if the server crashed you probably have to abandon and re-take it.
