### ISSUE TITLE
[Quest] A Race Against Time

### ISSUE THREAD

**Issue by Verice** [WoWManiaUK/Redemption#810]
Location: 41.67, 39.45 Beryl Point, Borean Tundra
Link: http://www.wowhead.com/quest=11671/a-race-against-time
After killing Inquisitor Salrand, the quest key (Saland's Broken Key) spawns in a chest that is only lootable by one group member respawn time for mob is approx 6 minutes

**Comment by fvicaria** [comment]
Not-Shareable.
