### ISSUE TITLE
[Quest] Oh Noes, the Tadpoles!

### ISSUE THREAD

**Issue by Verice** [WoWManiaUK/Redemption#812]
Location: Winterfin Village - Borean Tundra
Link: http://www.wowhead.com/quest=11560/oh-noes-the-tadpoles
Freeing a tadpole only counts for one party member. Each cage only spawns 1 tadpole (the retail server spawns multiples from 1- 4, I believe) needing to find 20 cages for each party member makes this a VERY long quest. Cages at 37.67, 16.29 and 39.25, 18.63 always spawn empty

**Comment by elagen** [comment]
Looking at Videos - on all cages opened there is suppose to be 3 in a cage 

http://www.wowhead.com/npc=25201/winterfin-tadpole
