### ISSUE TITLE
[Quest] Help Those That Cannot Help Themselves

### ISSUE THREAD

**Issue by Verice** [WoWManiaUK/Redemption#813]
Location: Borean Tundra
Link: http://www.wowhead.com/quest=11876/help-those-that-cannot-help-themselves
D.E.H.T.A. Trap Smasher can be used multiple times on one trap to complete the quest

**Comment by elagen** [comment]
i have just done the quest - and only been able to use the tool of 1 trap per time and only on the traps with the trapped mammoth calf
