### ISSUE TITLE
Bug with Feare Fire

### ISSUE THREAD

**Issue by Velzevoul** [WoWManiaUK/Redemption#816]
Hi, i wanted to report a bug for a talent called Improoved Feare Fire in Druid Balance spec. This talent it supposed to makes your Feare Fire gives you +3% critical strike on the target you used it and +3% hit chance on your spell instead of that just decreases the armor of target by 5%. I ve reset many times my talents, check trainer multiple times, even different character but the issue is remaining. Since Redemption is based on Pve and Improoved Feare Fire is a pve talent makes Bal Druids only useable for aoe dps, when they are really strong at single target also, this is happening because you waste 3% on hit rating when you could get it from talent.

**Comment by Plege** [comment]
tested with 100 wrath on target dummy. without feary fire 25% crits with feary fire 28.5% crits seems to be working. or are you arguing the hit is missing?

**Comment by Plege** [comment]
tested another 100 wrath with and without improved ff 2 % miss with ff 5% without. works perfectly,

**Comment by fvicaria** [comment]
Thanks.
