### ISSUE TITLE
[Quest] The Magical Kingdom of Dalaran

### ISSUE THREAD

**Issue by Earthliving** [WoWManiaUK/Redemption#817]
NPC does not teleport you to Dalaran. The crystal on the ground cannot be used by players new to Dalaran without flying, as it requires being used from within Dalaran prior.

**Comment by elagen** [comment]
Please next time you put a post on github - please find the quest or Spell and link it

http://www.wowhead.com/quest=12791/the-magical-kingdom-of-dalaran

and you can see in this page - and the video on wow head if you are in zul drak you can get teleported to dalaran - i will test to see if we can - 

next time find the information and videos before posting

thank you

**Comment by fvicaria** [comment]
It works. You need to complete quest first to be able to use crystal.

**Comment by elagen** [comment]
you can talk to any of the quest givers and they will TP you to dalaran
