### ISSUE TITLE
[Quests] Blasted Lands - Can't turn in

### ISSUE THREAD

**Issue by Dcmsmax** [WoWManiaUK/Redemption#818]
I picked up a few quests in the Blasted Lands at lv 46.

A Boar's Vitality
Snickerfang Jowels
The Basilik's Bite
The Decisive Striker
Vulture's Vigor

Once I got enough items to turn some of them in, I returned to the quest givers. Bloodmage Lynnore and Bloodmage Drazial. I couldn't turn them in. I tried logging out and back in, as well as exiting the game completely. That didn't work, so I went and collected the rest of the items. Still couldn't click complete quest. I tried logging and exiting again, even dividing the items into the required amounts for each quest. Again, couldn't click complete quest.

I've been holding onto the quests and items since then for turn in.

**Comment by fvicaria** [comment]
Known generic issue. Get one quest at a time.

**Comment by fvicaria** [comment]
Let me know if it still doesn't work when getting one at a time.
