### ISSUE TITLE
[Quests]Wetlands - Lifting the Curse.

### ISSUE THREAD

**Issue by ralfs154** [WoWManiaUK/Redemption#819]
When abandoning the quest the npc, disappears and you are unable to restart the quest!

http://www.wowhead.com/quest=25818/lifting-the-curse

I had trouble finding the the chest, so i abandoned the quest thinking ill do it later. When i decided to redo the quest, the npc was gone and didn't respawn, i was at the exact location, waited for around 15 minutes. Checked with yt videos for the exact location and wowhead.
Thanks in advance!

**Comment by elagen** [comment]
The quest giver is in Menethil Harbor - not standing in the marsh in the wetlands

the Chest is in the cargo hold of the north ship so swim in through the cargo hold

https://drive.google.com/open?id=0B_GODmkO59aEZHJ2dUpsRUk4dlU
