### ISSUE TITLE
[Quest] You'll Need A Bear #12972

### ISSUE THREAD

**Issue by Noxxpally** [WoWManiaUK/Redemption#823]
http://www.wowhead.com/quest=12972/youll-need-a-bear
https://www.wow-mania.com/armory/?quest=12972

Loklira The Crone http://www.wowhead.com/npc=29975/loklira-the-crone tell the PC that they need to speak with Brijana http://www.wowhead.com/npc=29592/brijana Outside of Brunnhildar Village to gain access to a ridable bear to compete in the competition.

"You've succeeded in the first rounds of the Hyldsmeet. To advance further, you're going to need a warbear of your own.

Unfortunately, the Hyldnir don't give them out to just anyone. You'll have to emerge victorious from true battle, not just gladiatorial combat.

The Hyldnir of Brunnhildar are currently involved in a feud against the Sons of Hodir, Thorim's former allies. Speak to Brijana just outside the village and see how you can help them and prove yourself in the process." 

When you walk over to Brijana on the eastern side of Brunnhildar Village, there is an area transition from Brunnhildar Village into Valley of Ancient Winters. When this transition happens Brijana and several other NPCs as well as an interactable bear (it has a green arrow when you mouse over it similar to a siege device) disappear, and can no longer be seen or interacted with.

I have though of 2 separate possible fixes, though I don't know if either can be done.  
1. Move the NPC Brijana and the bear 50-70 yards west, placing them inside Brunnhildar Village area so that players can interact with them.
2 Move the area transition 50-75 yards further east so that the NPCs and bear do not disappear as the player approaches them.

![wowscrnshot_021217_072654](https://cloud.githubusercontent.com/assets/25723016/22862906/c9bf158e-f0f4-11e6-85bd-008bf9a62d72.jpg)
![wowscrnshot_021217_072736](https://cloud.githubusercontent.com/assets/25723016/22862912/dfb154ec-f0f4-11e6-8a4b-62a2250dde5d.jpg)
![wowscrnshot_021217_072738](https://cloud.githubusercontent.com/assets/25723016/22862914/e2aef956-f0f4-11e6-8bee-1b763456d979.jpg)

**Comment by fvicaria** [comment]
This is a char issue. You are out of phase for some reason. Open a ticket.

**Comment by Noxxpally** [comment]
i have opened at least 6 tickets the one i opened for this one this morning they told me to post it here.
