### ISSUE TITLE
[Quest] The Purification of Quel'Delar

### ISSUE THREAD

**Issue by Scythre** [WoWManiaUK/Redemption#824]
Quest accepted from NPC :- Haldron Brightwing, once quest acepted ive to talk to npc next ot him :- Warden of the Sunwell, he has a clickable link "im ready to enter the sunwell", this however is what iis not working nothing happens link does not work.

This appears to work when in a Raid group, but the sword has vanished and cannot be looted from thre sunwell, i now have a quest unfinished and no sword.

Zoned out of instance , Abandoned quest, retook quest was given another sword, retried in raid group and this time it worked.

Problem resolved after much ass twitching.

Please help
Regards

Scythre

**Comment by philoudu16** [comment]
A guildie did this quest a few days ago. I believe you have to be in a raid group to be teleported. (i don't know if that is how it should be or not, but it should fix your problem :) )
