### ISSUE TITLE
In wine, Truth

### ISSUE THREAD

**Issue by Lemayonaise** [WoWManiaUK/Redemption#826]
quest item is missing. supposed to be in a chest underwater.

**Comment by elagen** [comment]
More information would be handy - saves tester's time and we can test quicker please read 

https://github.com/WoWManiaUK/Redemption/wiki/How-to-Properly-Report-an-Issue

Before reporting

**Comment by elagen** [comment]
https://drive.google.com/open?id=0B_GODmkO59aEMXVwNDl2Vkt3NG8

quest is there and can be completed
