### ISSUE TITLE
[Quest]: If he cannot be turned (part 1)

### ISSUE THREAD

**Issue by Boobarnes** [WoWManiaUK/Redemption#834]
This quest has 3 NPCs help you kill General Lightsbane, and it's crucial to open up the Ebon Watch faction so you can begin their dailies and get their flight path. About 2 months ago I easily solo'ed it on my shadow priest (as I read you could on retail WOTLK), allowing the 3 NPCs (Vile, Leaper, Lady Nightswood) to take the aggro. But recently (early Feb 2017) I have tried multiple times with both my 80 frost mage and 80 warrior, and every time we are all wiped, with hardly any damage done to the General. Somehow the NPCs aren't doing the damage they should, and he does more than he should--he keeps targeting me and killing me first, even if I only take one shot. Please fix this quest so it works again. 
From wowhead: 
"johne2x on 2010/08/25 (Patch 3.3.5)
He does basically no dmg so he is uber easy"
http://www.wowhead.com/quest=12897/if-he-cannot-be-turned#comments

**Comment by elagen** [comment]
I had done the quest on 5 characters and did not have any problems with the fight

**Comment by Boobarnes** [comment]
**Yes, but have you done it in the last couple of weeks?** I pointed it out it used to work, but it doesn't **now.**
