### ISSUE TITLE
[Quest] A Voice in the Dark

### ISSUE THREAD

**Issue by Boobarnes** [WoWManiaUK/Redemption#835]
Hi, I'm trying to do the Icecrown quest, "A Voice in the Dark," but the ghost kid isn't appearing next to the surface portal. I did this quest on an alt about a week ago and it worked--the kid was there, semi-transparent, with a ? over his head. 
I tried dropping the quest twice and reaccepting it, but the ghost boy still doesn't appear. I also roamed all over the cavern, thinking he might have moved. No luck. Could u please fix this quest? Thank u.

**Comment by elagen** [comment]
next time please to make it easier is to link the quest - this saves testers time and makes it quicker if there is a problem 

https://github.com/WoWManiaUK/Redemption/wiki/How-to-Properly-Report-an-Issue

**Comment by elagen** [comment]
Confirmed that the Npc http://www.wowhead.com/npc=31237/matthias-lehner
should be standing by the portal - while taking the quest in the pools the npc does not appear 
**the Quest**
http://www.wowhead.com/quest=13271/a-voice-in-the-dark#comments

**Comment by Boobarnes** [comment]
Thanks for looking into this one, but I'm not sure what "Fixed In Dev" means. It's not fixed on Redemption--just checked it now. I'm in no hurry, just not sure when it will be fixed for players.
