### ISSUE TITLE
[QUEST] "Riverpaw Gnoll Bounty"

### ISSUE THREAD

**Issue by Feryk** [WoWManiaUK/Redemption#836]
For the quest "Riverpaw Gnoll Bounty" in Forests Edge, south of Goldshire, the Gnoll are not dropping "Painted Gnoll Armband".

**Comment by elagen** [comment]
https://github.com/WoWManiaUK/Redemption/wiki/How-to-Properly-Report-an-Issue

saves us time - thank you
