### ISSUE TITLE
[Quest] The Lost Mistwhisper Treasure

### ISSUE THREAD

**Issue by mainomenos** [WoWManiaUK/Redemption#837]
Character specific issue
I am using your client
I loot the item (Mistwhisper Treasure) I did the kill (Warlord Tatrtek) and the quest marked as complete.
(I am using Carbonite addon)
I am trying to return the quest but in the dialog box (continue) is gray

Ps
I did the same quest with another character yesterday and complete normaly

**Comment by elagen** [comment]
https://github.com/WoWManiaUK/Redemption/wiki/How-to-Properly-Report-an-Issue

this saves us time - thank you
