### ISSUE TITLE
Thassarian on alliance gunship

### ISSUE THREAD

**Issue by TenmanWoW** [WoWManiaUK/Redemption#839]
Normally, the quest line from an NPC is sequential. I expected as much when I first made it to ice crown. Upon talking to Thassarian, it appears his entire line is available all at once, in any order a player would care to choose. One of the quests even allows the player to accept and then turn in immediately, awarding all the experience and gold as if the foot work was already done. It seems that this can be done more than once, as I did this quest properly and it is now showing as completed again.

**Comment by Plege** [comment]
![grafik](https://cloud.githubusercontent.com/assets/24266043/23013705/19930e64-f42c-11e6-8b0b-19387834c435.png)

**Comment by Plege** [comment]
sometimes the daily and the normal quest are available at the same time. honestly i had a hard time to find out what it should really look like and i couldn't find any 2 quests from the same questline in available, but getting the normal and the daily at the same time seems off

**Comment by fvicaria** [comment]
This is "as is". What is the problem with normal and dailies being available together?
If there are multiple quests from the same quest line please list them here and I will check.

**Comment by TenmanWoW** [comment]
I'm not saying that there is a problem dailies being grouped in with normal quests. I'm just saying that every quest that NPC gives is available from the get go and I've been logging out next to him for a few days now. There are quests I've never done that are available to turn in.
