### ISSUE TITLE
[Spell] Glyph of Succubus

### ISSUE THREAD

**Issue by zyklonb** [WoWManiaUK/Redemption#840]
Glyph of Succubus is supposed to remove all DoT's when you cast seduction, but it doesnt

**Comment by fvicaria** [comment]
Please re-test

**Comment by Plege** [comment]
works if the (doted) target is standing still. charm is cast and curses removed.
doesn't work if target is moving. the charm isn't cast (seems something familiar with the voidwalker issue)
