### ISSUE TITLE
Charge error in Splithoof Hold

### ISSUE THREAD

**Issue by deadtuff** [WoWManiaUK/Redemption#842]
Hello, I have encountered two issues in Splithoof Hold while charging as a warrior. I am gonna link two videos showing what the error is when you charge. 

https://www.youtube.com/watch?v=fbW07CtXAsg

https://www.youtube.com/watch?v=4085WSHQ2MI

**Comment by Boobarnes** [comment]
Just FYI--using charge in a cave or even outside on a steep cliff often causes my warrior to fall through the world. The bug is more widespread than just this location--can happen anywhere.

**Comment by deadtuff** [comment]
Alright, I didn't know. I just wanted to report it in case something could be done, but thanks for the heads up!

**Comment by fvicaria** [comment]
This is a core issue. I will look into it separately.
