### ISSUE TITLE
[Achievment] [Glory of the Hero] Incomplete cause [Brann Spankin' New] Is not working..

### ISSUE THREAD

**Issue by Escavaca** [WoWManiaUK/Redemption#843]
Greetings, This is whats going on, me and many players are having a hard time completing the achiev [Glory of the Hero] (http://www.wow-mania.com/armory/?achievement=2136) cause the Achiev [Brann Spankin' New] (http://www.wow-mania.com/armory/?achievement=2154) in Halls of Stone is not working, im pretty sure its bugged cause ive tried multiple times doing different tactics, without letting Brann's loosing HP even with 2 disc priest bubble him all the time since he starts running till the end of the waves (having in count those invisible entities that sometimes spawns and try to dmg Brann and we cant target em' so ive make sure ive tried everything possible to keep him immune all the time).. In the end of the fight the achiev simply does not pop up, he talks all he's speech and then he starts running and fades.  It is the only achiev i miss for [Glory of the Hero] so as i said before me and many other players that tried diff tactics all fail and we know were doing it more then properly.  So i hope you guys can help us soon by fixing it so we can get the Red proto we have been waiting for so long...
Sincerely,
                                                     Escavaca

**Comment by elagen** [comment]
As you can see at the station where Brann stands for the fight - this mobs in the screenshot attacks brann making the achievement not completable

https://drive.google.com/open?id=0B_GODmkO59aERjlaaFYyVWsyRVE - the mob

https://drive.google.com/open?id=0B_GODmkO59aERHdPaWprRVBnNzg - the dmg

http://www.wowhead.com/npc=30899/abedneum the npc at brann station
