### ISSUE TITLE
frost mage bugg

### ISSUE THREAD

**Issue by sirjacob4pe** [WoWManiaUK/Redemption#844]
real prob with frost mage deep freeze is not usable with fingers of frost proc. or deep freeze on works on rooted targets when it should work with proc how do you frost nova a boss ???
links of the spells http://wotlk.openwow.com/spell=44544 fingers of frost. http://wotlk.openwow.com/spell=71757 deep freeze.

**Comment by Plege** [comment]
Duplicate #833
