### ISSUE TITLE
[Quest] If He Cannot Be Turned (part 1)

### ISSUE THREAD

**Issue by Boobarnes** [WoWManiaUK/Redemption#845]
Can someone besides Elagen please handle this one? It doesn't matter that it used to work; it doesn't work now.

This quest has 3 NPCs help you kill General Lightsbane, and it's crucial to open up the Ebon Watch faction so you can begin their dailies and get their flight path. About 2 months ago I easily solo'ed it on my shadow priest (as I read you could on retail WOTLK), allowing the 3 NPCs (Vile, Leaper, Lady Nightswood) to take the aggro. But recently (early Feb 2017) I have tried multiple times with both my 80 frost mage and 80 warrior, and every time we are all wiped, with hardly any damage done to the General. Somehow the NPCs aren't doing the damage they should, and he does more than he should--he keeps targeting me and killing me first, even if I only take one shot. Please fix this quest so it works again.
From wowhead:
"johne2x on 2010/08/25 (Patch 3.3.5)
He does basically no dmg so he is uber easy"
http://www.wowhead.com/quest=12897/if-he-cannot-be-turned#comments

**Comment by elagen** [comment]
the quest is working as intended
https://drive.google.com/open?id=0B_GODmkO59aEV0RpSFdFV0JISE0 - that is with the vile stun and taunt
- as you can see on omen the vile is top and a single ability hit will take aggro from him

Vile can stun the boss and generates alot of threat , and Lady can put a debuff that causes the general to miss 49% of his attacks. After that , lay low on the dps and let Vile tank it , while you slowly dps

any high damage you do will take the threat back - also general-lightsbane does 800 - 2k dmg per hit

**Comment by Boobarnes** [comment]
Cool--thanks for the advice!!! It wasn't easy like wowhead says, but I was able to complete the quest with 1% health left.
