### ISSUE TITLE
[Quest] Do Your Worst 

### ISSUE THREAD

**Issue by Josephinw** [WoWManiaUK/Redemption#847]
After completing the quest Field Repairs (http://www.wowhead.com/quest=13304/field-repairs) a NPC Matthias Lehner (http://www.wowhead.com/npc=32408/matthias-lehner) should spawn next to you with the quest  Do Your Worst (http://www.wowhead.com/quest=13305/do-your-worst) but the NPC doesn't seem to spawn, making it impossible to continue the next quest chain.

**Comment by fvicaria** [comment]
No it does not you have to go back to the same place he was when you got the quest.

**Comment by fvicaria** [comment]
![image](https://cloud.githubusercontent.com/assets/9414661/23067158/dcab4440-f515-11e6-85cd-2be8ce6338b8.png)

**Comment by fvicaria** [comment]
Reopening this for full re-test.

**Comment by fvicaria** [comment]
Can someone retest the quest-chain for Matthias Lehner
it starts here: http://wotlk.openwow.com/quest=13386
only doing from the beginning we can test if the phase is messed up

**Comment by elagen** [comment]
The Quest line is good until you get to http://www.wowhead.com/quest=13271/a-voice-in-the-dark

When you need to turn into http://www.wowhead.com/npc=31237/matthias-lehner (he is missing) ---- ON Dev
