### ISSUE TITLE
[Raid] ToC/TogC 10/25 (Updated)

### ISSUE THREAD

**Issue by Grindall** [WoWManiaUK/Redemption#848]
The beast's pathing for ToC is bugged. It could be all the bosses (minus anub) as well, but as we were not able to get past the beasts it is unknown. 

The northrend beasts will get stuck at the door. Sometimes you are able to attack them. Other times they evade completely. Sometimes, if you move them just right, they will come out of the door. 

The bug varies depending on the fight attempt, but the end result is more than likely death. We were able to kill Gormok once when he finally went through the door; however, when the worms came out there was the same issue. Since we couldn't face them away from the raid the spit killed everyone.

**Comment by elagen** [comment]
i Can confirm that all The bosses that come through the door are stuck on evade unless there is someone who the boss has targeted to stand on the boss by the door then people can DPS the boss

https://drive.google.com/open?id=0B_GODmkO59aEQ2xUa3BwLXY0SUU

and you can see in these 2 videos - all the bosses are stack on evade until i have attacked them at a certain position 

the only boss that seems to fix himself is Icehowl for when he does his smash in the center of the room

**Comment by Emcitementz** [comment]
Also fixed an issue, not reported. If acidmaw was the last worm to kill and somehow, the raid wiped, he was stuck in evade and the raid couldn't go any further.
