### ISSUE TITLE
[Quest] Return of the Friendly Dryskin

### ISSUE THREAD

**Issue by Josephinw** [WoWManiaUK/Redemption#849]
After completing the quest A Hero's Burden (http://www.wowhead.com/quest=12581) and choosing Frenzyheart in that battle you should be able to pick up Return of the Friendly Dryskin (http://www.wowhead.com/quest=12695/return-of-the-friendly-dryskin) from Jaloot but even though he shows he has a quest he doesn't give it to you. 

![wowscrnshot_021717_190307](https://cloud.githubusercontent.com/assets/25821382/23077451/e08b4658-f544-11e6-9370-f8e8ebc1b86b.jpg)

**Comment by elagen** [comment]
http://www.wowhead.com/quest=12582/frenzyheart-champion For Frenzyheart
http://www.wowhead.com/quest=12689/hand-of-the-oracles For Oracles

after reading up about this 
Seems like no one has said who to kill/save for which faction:

If you want Oracles: Kill Zepic

If you want Frenzyheart: Kill Jaloot

i have only done for the oracles - i will test from Frenzyheart when i can

**Comment by Josephinw** [comment]
Yeah sorry I mixed it up when writing, I killed Zepic cause I wanted to have the Oracles but when I tried to move on in the quest chain I got the above issue.

**Comment by fvicaria** [comment]
SOmething on the chain got screwed up, Either something missing or dropped or re-done. I could not reproduce. If you still have an issue with the quest. Open a ticket and get it completed.
