### ISSUE TITLE
Reign of Terror vs. Berserker Rage

### ISSUE THREAD

**Issue by Dusticles** [WoWManiaUK/Redemption#851]
When a warlock *Reign of Terror* the warrior should do *Berserker Rage* Warrior does... *Berserker Rage* goes on cooldown still feared and the buff doesnt show up on buff bar. It's only on *Reign of terror* from a warlock. Also *physic Scream* from priests

**Comment by elagen** [comment]
Berserker rage is working like it should - have tested multiple times on all fears and everytime its working fine
