### ISSUE TITLE
[Quest] In Wine, Truth

### ISSUE THREAD

**Issue by dmtryzhkv** [WoWManiaUK/Redemption#854]
![wowscrnshot_021817_021500](https://cloud.githubusercontent.com/assets/7843712/23086812/7347c35a-f580-11e6-90e0-58416639cf5a.jpg)

After clicking on "Wine Crate" on the [In Wine, Truth](http://wotlk.openwow.com/quest=11603) quest and this blank inventory comes up. but there should be [Kul Tiras Wine](http://wotlk.openwow.com/item=34714)

Not doing this quest prevents doing other 5 quests and also prevents taking [Nothing Boring About Borean](http://wotlk.openwow.com/achievement=33) achievement.

Tried this on a different times thinking maybe someone got this before me but nothing changed. Sadly didn't tried this on different character because I don't have any more high level alliance.

Someone told me they got this way before.

**Comment by dmtryzhkv** [comment]
I don't want to overload and stupidly comment here but does "fixed confirmed in dev" means that it probably will go live in the next maintenance?

**Comment by fvicaria** [comment]
It means it's not in Redemption yet but it has been fixed in the dev server.
