### ISSUE TITLE
[Quest] Death's Gaze

### ISSUE THREAD

**Issue by Josephinw** [WoWManiaUK/Redemption#856]
While doing the quest Death's Gaze (http://www.wowhead.com/quest=13120/deaths-gaze) you are supposed to place the orbs into stands, but the stands seem to be missing or at least aren't in the positions they are supposed to be in.

**Comment by fvicaria** [comment]
![image](https://user-images.githubusercontent.com/9414661/27083773-8a0cb80e-5041-11e7-8505-f9f126e6b8d7.png)
Still works fine.
