### ISSUE TITLE
[Quest] Springing the Trap

### ISSUE THREAD

**Issue by Josephinw** [WoWManiaUK/Redemption#857]
Same [quest](http://www.wowhead.com/quest=11969/springing-the-trap) was mentioned in this report: https://github.com/WoWManiaUK/Redemption/issues/593

I tried doing as described and standing inside her green circle the whole time and the quest was still not marked as complete.

**Comment by fvicaria** [comment]
It works. I will not even look at this. Read my messages.

**Comment by elagen** [comment]
When doing this quest - when the Drake drops u on the floor - do not move that is how it completed for me
