### ISSUE TITLE
Bloodfury - Orc passive is broken

### ISSUE THREAD

**Issue by binne92** [WoWManiaUK/Redemption#860]
It seems like Bloodfury Active ability yields 21 spell damage, and 38 atk power, where it is intended to give 5 spell dmg and 6 atk power.

The tooltip reads correctly, but the activation itself is a bit too OP.

Kind Regards 
Binne92
(IGN: Binne, Binney, Binnie)

**Comment by hotdoggidy** [comment]
The buff works properly at all milestones while lvling an Orc. The tooltip itself is bugged and does not show the correct stat increase. 

Tested on a lvl 80 Orc warrior and a lvl 1 orc warrior. The 80 gained 322 Attack Power while the lvl 1 only gained 6.
