### ISSUE TITLE
[QUEST] What is Going On?

### ISSUE THREAD

**Issue by Readerlady** [WoWManiaUK/Redemption#861]
After speaking to Commander Gor'shak in Blackrock depths in the detention block and turning in the quest that I got form Kargath area he then offers me "What is Going On? I am to now defend him and survive the onslaught. Nothing came...no "onslaught". Wow-head is broken at the moment so I can't link too many details. Sorry about that.

**Comment by fvicaria** [comment]
Duplicate #643 Please search before entering new issues also have a look at this: https://github.com/WoWManiaUK/Redemption/wiki/How-to-Properly-Report-an-Issue
