### ISSUE TITLE
[Core] Dungeon Deserter

### ISSUE THREAD

**Issue by binne92** [WoWManiaUK/Redemption#862]
Location: Scarlet Monestary - Armory

Issue: Requeuing with 3 from the same group. The instance came up with the old ID, and even worse some from our group got flagged deserter for leaving. 

I have come across similar issues in the past, with completed dungeons still flagging you deserter.

**Comment by Plege** [comment]
did you reset your id's before requeueing?

**Comment by Emcitementz** [comment]
> did you reset your id's before requeueing?
Probably caused by this indeed.

**Comment by fvicaria** [comment]
Cannot reproduce.
