### ISSUE TITLE
[Quest] a crystalforged darkrune

### ISSUE THREAD

**Issue by Dragonfly414** [WoWManiaUK/Redemption#863]
http://www.wowhead.com/quest=11060/a-crystalforged-darkrune

The NPC Gahk is having a Yellow ? above his head, but I cant do anything with the quest.
It asks for the http://www.wowhead.com/item=33784/darkrune-fragment#comments, Darkrune
I need darkrune Fragments, wich I could get by doing the quest: http://www.wowhead.com/quest=11051/banish-more-demons
But Kronk isn't giving me this quest, I am Honored with the facion Ogri La, so I should get the quest. But nothing.

Also I think that de ? is not right and that it have to be grey and not yellow to start :)

Thanks for looking at it

**Comment by elagen** [comment]
when completing http://www.wowhead.com/quest=11051/banish-more-demons you might need to wait to the next day so it becomes a daily quest 

You must be honored with Ogri'la to accept the quest "Banish the Demons" //www.wowhead.com/?quest=11026 . Once that has been completed, this quest becomes a daily quest.

check today for the quest if it is available

**Comment by Dragonfly414** [comment]
but this quest I dont get from him like I said in my openings post....


*I need darkrune Fragments, wich I could get by doing the quest: http://www.wowhead.com/quest=11051/banish-more-demons
But Kronk isn't giving me this quest, I am Honored with the facion Ogri La, so I should get the quest. But nothing.*

**Comment by Dragonfly414** [comment]
Today  I became Revered with Ogri'La and than the quest www.wowhead.com/?quest=11026 came... so its fault in the faction :)
