### ISSUE TITLE
[Quest] Mutiny on the Mercy

### ISSUE THREAD

**Issue by Josephinw** [WoWManiaUK/Redemption#865]
The quest [Mutiny on the Mercy](http://www.wowhead.com/quest=11527/mutiny-on-the-mercy) isn't doable as the mobs (http://www.wowhead.com/npc=25026/mutinous-sea-dog) that drop the required quest item aren't spawning.

**Comment by fvicaria** [comment]
They are there. This issue is similar to NPCs on the Skybreaker that "fall" of the boat from time to time.
Not sure if there is a fix possible for this.

**Comment by Josephinw** [comment]
So the best bet would be to swim around underneath the path of the boat and hope you find them?

**Comment by fvicaria** [comment]
It's fixed for now but it may happen again
