### ISSUE TITLE
[Quest] Death Comes From On High

### ISSUE THREAD

**Issue by Izimarit** [WoWManiaUK/Redemption#867]
I can't use Eye of Archerus Control Mechanism for one od dk's quest "Death Comes From On High".
I tried reset interface, delete and create new character, abandon quest. 
[http://www.wowhead.com/quest=12641/death-comes-from-on-high](url)

**Comment by elagen** [comment]
http://www.wowhead.com/object=191609/eye-of-acherus-control-mechanism Can not be used to complete the Quest
