### ISSUE TITLE
[Quest] Samophlange

### ISSUE THREAD

**Issue by efdede** [WoWManiaUK/Redemption#868]
Region : The Barrens
Quest : Samoplanghe
Required : -shut off Main Control Valve
                 - shut off Fuel Control Valve
                 - shut off Regulator Valve
Problem : Cursor changes to cogwheel but valve do not react

**Comment by elagen** [comment]
Confirmed that when Accepting the quest 
http://wowwiki.wikia.com/wiki/Quest:Samophlange_(2)

Trying to turn of the valves is not working
http://wowwiki.wikia.com/wiki/Main_Control_Valve
http://wowwiki.wikia.com/wiki/Fuel_Control_Valve
http://wowwiki.wikia.com/wiki/Regulator_Valve

**Comment by Emcitementz** [comment]
This one is even working on red at the moment.
Tried many quests even with differents characters, it worked all the time.
