### ISSUE TITLE
[Quest] The angry Scyteclaws

### ISSUE THREAD

**Issue by efdede** [WoWManiaUK/Redemption#869]
Region : The Barrens
Quest : The Angry Scytheclaws
Required : - Visit Blue raptor nest
                 - Visit Yellow raptor nest
                 - Visit Red raptor nest
Problem : Cursor changes to cogwheel but nest (eggs) do not react

**Comment by elagen** [comment]
While doing the quest http://wowwiki.wikia.com/wiki/Quest:The_Angry_Scytheclaws

you need to kill the Sunscale Raptor/Screecher to get : 
http://wowwiki.wikia.com/wiki/Sunscale_Feather

then place each 1 on the Nest to say you have visited : 
http://wowwiki.wikia.com/wiki/Blue_Raptor_Nest
http://wowwiki.wikia.com/wiki/Yellow_Raptor_Nest
http://wowwiki.wikia.com/wiki/Red_Raptor_Nest

while at the next you cannot use the Feathers to say that you have visted the nests

**Comment by efdede** [comment]
Tried to activate the feathers and place them on the nest, same result. Sorry

When i right click the feather i get a highlighted pointer but placing it on the nest does norhing.
When i go with normal pointer over the nest it changes to a cogwheel but does nothing.
