### ISSUE TITLE
[Quest] Rescuing the Rescuers

### ISSUE THREAD

**Issue by dmtryzhkv** [WoWManiaUK/Redemption#870]
![wowscrnshot_022117_162647](https://cloud.githubusercontent.com/assets/7843712/23166679/9a29d7f4-f852-11e6-9c90-ac09dac64150.jpg)

Hello.

This is a screenshot of north of Valgarde. There is a quest named [Rescuing the Rescuers](http://www.wow-mania.com/armory/?quest=11244). To complete this quests you simply need to click on those "harpoons" and free "Valgarde Scout"s from them. 

The problem is: harpoons are clickable, they are glowing and everything but when I click on them, nothing happens. I tried relogging, dropping quest and taking it again, not helping. 

Thanks in advance. 

EDIT: After posting this issue I kept trying and managed to complete 3/8 of it. randomly 3 of the harpoons were activatable but only those three. I tried after couple hours and couldn't activate any of them. didn't want to leave and retake the quest in case it wouldn't work.

**Comment by Feryk** [comment]
I was able to reproduce this.
