### ISSUE TITLE
[Quest] "Scoodles"

### ISSUE THREAD

**Issue by Feryk** [WoWManiaUK/Redemption#871]
[+] Using the latest WoW-Mania custom client?
 - Yes

[+] What are the steps to reproduce the problem?
 - Simply take the quest "Scoodles" as an Alliance, level 70 or above from "Silvermoon" Harry in Northrend at 35.09, 80.94 and then search for Scoodles the Orca in the area of 36.68, 84.86.

[+] How should this be working?
 - Scoodles the Orca should be around the general area of Northrend at 36.68, 84.86 and should drop a 'Sin'dorei Scrying Crystal' when slain.

[+] What is broken?
 - "Scoodles" the Orca isn't spawning.

[+] Wowhead links?
 - [Quest] [71] "Scoodles": http://www.wowhead.com/quest=11510/scoodles
 - "Silvermoon" Harry: http://www.wowhead.com/npc=24539/silvermoon-harry
 - "Scoodles" the Orca: http://www.wowhead.com/npc=24899/scoodles
 - Sin'dorei Scrying Crystal: http://www.wowhead.com/item=34235/sindorei-scrying-crystal

[+] Screenshots?
 - http://imgur.com/a/PnYu2

**Comment by elagen** [comment]
Scoodles is spawning  - the quest is working fine - someone might have killed scoodles before you got there thats why he might have been around but he does spawn

just remember in the area u have Oracles and then u have scoodles (they all look the same but scoodles has a different name)
