### ISSUE TITLE
[Refer a Friend] Summoning

### ISSUE THREAD

**Issue by firehawk2k2** [WoWManiaUK/Redemption#877]
Referred accounts not able to summon each other until players are within targetable range. Once this occurs, characters can summon each other for the remainder of the session until either loggs off.
I have verified both characters are friends with eachother.
Both characters are currently in the same party.
My experience on retail does not have this requirement. 
I am not sure if this is a bug or a "working as intended feature"

http://www.wowhead.com/spell=45927/summon-friend

**Comment by fvicaria** [comment]
Please check the guide on RAF.

**Comment by firehawk2k2** [comment]
I assume you are referring to this forum guide
http://www.wow-mania.com/forums/topic/2303

It does not mention anything about the requirement to be within range of the friend before summoning is available.

**Comment by fvicaria** [comment]
You don't have to be in range. You just need to follow all other requirements.
