### ISSUE TITLE
[Quest] The Third Fleet

### ISSUE THREAD

**Issue by Feryk** [WoWManiaUK/Redemption#878]
[+] Using the latest WoW-Mania custom client?
 - Yes

[+] What are the steps to reproduce the problem?
 - Accept the quest [The Third Fleet] from First Mate Fitzsimmons in the Wetlands at 10.98, 59.67.

[+] How should this be working?
 - There should be a Flagon of Mead that you can pick up in the lower part of the Tavern that he stands next to.

[+] What is broken?
 - The Flagon of Mead does not appear to spawn anywhere within the Tavern.

[+] Wowhead links?
 - The Third Fleet: http://www.wowhead.com/quest=25815/the-third-fleet
 - Fitzsimmons' Mead: http://www.wowhead.com/item=56031/fitzsimmons-mead

**Comment by Feryk** [comment]
Not sure why the first Wowhead link for the quest failed.

http://www.wowhead.com/quest=25815/the-third-fleet

**Comment by elagen** [comment]
Confirmed that http://www.wowhead.com/item=2594/flagon-of-dwarven-mead does not spawn for the quest

You can speak to the Innkeeper to buy the drink 

The quest can still not be completed - http://www.wowhead.com/quest=288/the-third-fleet#comments

**Comment by fvicaria** [comment]
This is an item and it drops from:
http://www.wowhead.com/npc=14322/stomper-kreeg
or can be bought straight away from:
http://wotlk.openwow.com/item=2594#sold-by

so I don't understand what you are talking about.

Use wotlk.opewow.com for reference

![image](https://cloud.githubusercontent.com/assets/9414661/23253120/415f8f2e-f9ab-11e6-9441-5827c4d9b890.png)
