### ISSUE TITLE
[Quest] The Thandol Span

### ISSUE THREAD

**Issue by Feryk** [WoWManiaUK/Redemption#879]
[+] What are the steps to reproduce the problem?
 - Work through [The Thandol Span] quest-line which can be taken from Rhag Garmason in Wetlands at about 50.00, 18.34 until you reach the point at which he asks you to destroy the cache of explosives.

[+] How should this be working?
 - When reaching the cache of explosives in Arathi Highlands around 48.77, 88.15, there should be a right-clickable cart of explosives that the player can then 'use'.  Using the cart will light a fuse which then causes the cart to explode, completing the quest.

[+] What is broken?
 - The cart mentioned seems to be flipped upside down.  There is a wheel visible and click-able that is jutting from the ground in that area, but 'using' it does nothing.

[+] Wowhead links?
 - [The Thandol Span]: Unfortunately, I could not find a Wowhead link for this quest.
 - Rhag Garmason: http://www.wowhead.com/npc=1075/rhag-garmason

**Comment by elagen** [comment]
http://wowwiki.wikia.com/wiki/Rhag_Garmason - just testing this quest and it is working fine
