### ISSUE TITLE
[Quest] Leading the Ancestors Home

### ISSUE THREAD

**Issue by sentel-alati** [WoWManiaUK/Redemption#883]
The NPC Elder Kesuk seems to be invisible. He is there apparently as typing /target Elder Kesuk did in fact target him and allow me to use the item on him. However visually he is gone and using his totem doesn't seem to do anything. The two other elders in the quest are visible and don't require me to use their totems in order to be able to complete the objective. Wowhead says you're supposed to be able to use the item just by being near the totem but that just told me that I need a target. I haven't been able to try the quest on another character but two of my friends encountered the same problem a few weeks ago so I assume it's not just me.

**Comment by elagen** [comment]
the quest is working fine - here are some screenshots to help

https://drive.google.com/open?id=0B_GODmkO59aEbWVjc0pNazZoUWc
