### ISSUE TITLE
[General] Mob pull radius seems abnormally large

### ISSUE THREAD

**Issue by Tybot204** [WoWManiaUK/Redemption#884]
Mob pull ranges appear to be abnormally large in all areas of the game. There is not really a specific way to reproduce this, it happens to every mob I have encountered in the game.

More specific examples can be found in this thread: [www.wow-mania.com/forum/viewtopic.php?f=15&t=550](https://www.wow-mania.com/forum/viewtopic.php?f=15&t=550)

EDIT: Thinking about this (and playing more) it appears the pull radius is only a problem for mobs pulling other mobs. i.e. when one mob is pulled, other mobs fairly far away will also pull.

**Comment by Katherwind** [comment]
Just wanted to add that I have been experiencing this issue as well. .  Shortly after I started playing on the server (a little over a month ago) I put in a ticket regarding this issue and spoke to Weeble.  He advised me that the team was aware of the issue and was working to correct it.  Pulling one mob all alone by itself generally ends up with the entire nearby camp being pulled. I have been dealing with it by completing mosts quests only when they are low green, almost to the point of being grey.  I would like to see this made a priority as this is game breaking for a lot of classes.

**Comment by fvicaria** [comment]
This is a local issue on each region. Give me specific cases and the coordinates and I will go check. 
Some work has been done on it for this last update.
Please re-open this issue with the specific locations if it is still a problem.
