### ISSUE TITLE
[Quest] Conversing With the Depths

### ISSUE THREAD

**Issue by stwarlord** [WoWManiaUK/Redemption#887]
http://www.wowhead.com/quest=12032/conversing-with-the-depths

**Comment by fvicaria** [comment]
Please read: https://github.com/WoWManiaUK/Redemption/wiki/How-to-Properly-Report-an-Issue
before creating a new issue.

**Comment by stwarlord** [comment]
answer was yes but a GM told me this morning that i have to report first. he told this is our new policy.

**Comment by fvicaria** [comment]
Read again. The bug info needed is not there. I don't know what happened and what should have happened. There are other issue you can use as an example. Please read the link I posted.
