### ISSUE TITLE
[Quest] Chapter I and Chapter III (Green Hills of Stranglethorn)

### ISSUE THREAD

**Issue by Lutti92** [WoWManiaUK/Redemption#888]
I just bought the last pages for these two quests and have all the pages in my bags, but it doesn't say I can turn in the quest at the NPC. I completed one of the other chapters (chapter 2 I think) in the same manner, which worked just fine :/ I did try relogging already.

**Comment by elagen** [comment]
i have just done all the quest for the main quest http://wowwiki.wikia.com/wiki/Quest:The_Green_Hills_of_Stranglethorn_(old)

**Chapter**  **Pages**
Chapter 1 -     1, 4, 6, 8
Chapter 2 -     10, 11, 14, 16
Chapter 3 -     18, 20, 21, 24
Chapter 4 -     25, 26, 27

The quests are working fine

**Comment by Lutti92** [comment]
I will literally take screenshots when I get home tomorrow and prove it's not working lol.
