### ISSUE TITLE
Glyph of Seal of Vengeance (Paladin)

### ISSUE THREAD

**Issue by theavicenne** [WoWManiaUK/Redemption#889]
1. Equipe the glyph of seal of vengeance
2. Buff your self with seal of vengeance
3. Check your expertise.
4. Relog
5. Check your expertise
and you will see that the glyph is not working even if you have the seal of vengeance on
i don't know if there is more bugs on that glyph.

**Comment by hotdoggidy** [comment]
The glyph works fine. All you have to do is re-buff Seal of Corrpution and you will get the expertise back. Noting too bothersome unless u forget to buff, in which case you wouldnt have the expertise anyway. 

This can be closed.
