### ISSUE TITLE
[Quest] What the Wind Carries

### ISSUE THREAD

**Issue by Readerlady** [WoWManiaUK/Redemption#890]
http://www.wowhead.com/quest=6566/what-the-wind-carries 
The quest requires me to listen to Thrall's tale but Thrall does not talk. There is no bubble to ask him to talk either. This is part of Loremaster and originally part of the Onyxia key quest line. As far as I can tell it should still be available in this patch even though we no longer need a key for Onyxia. I was able to do Warlords Command which was the precursor to this quest.

**Comment by hotdoggidy** [comment]
Initial quest "Warlord's Command" (http://wotlk.openwow.com/quest=4903) picked up in Badlands. Quest if given by "Warlord Goretooth" (5.82 47.51) at the top of a tower. Quest sends player to Lower Blackrock Spire to kill 3 bosses: 
-Overlord Wyrmthalak (http://wotlk.openwow.com/npc=9568)
-Highlord Omokk (http://wotlk.openwow.com/npc=9196)
-War Master Voone (http://wotlk.openwow.com/npc=9237)
and collect "Important Blackrock Documents" (http://wotlk.openwow.com/item=12562) before returning to Goretooth.

Followup quest "Eitrigg's Wisdom" (http://wotlk.openwow.com/quest=4941) sends the player to Orgrimmar to speak with Eitrigg (34.27 39.33). Upon completing conversation the quest is turned in to Thrall, sitting on his throne. This grants access to next quest in chain.

"For The Horde" (http://wotlk.openwow.com/quest=4974) sends the player to Upper Blackrock Spire for the head of "Rend Blackhand" (http://wotlk.openwow.com/npc=17027)(http://wotlk.openwow.com/item=12630). Once this stage is completed OP quest is taken from Thrall.

Accepting "What the Wind Carries" (http://wotlk.openwow.com/quest=6566) should allow the player to interact with Thrall and use RP chat selections to progress Thrall's tale of Blackrock Mountain and the hunt for Onyxia. These RP chat selections are unavailable when interacting with Thrall and no credit is awarded. Dead-end.
