### ISSUE TITLE
[Quest] Twilight of the Dawn Runner 

### ISSUE THREAD

**Issue by redhawk816** [WoWManiaUK/Redemption#891]
This quest still does not have any dialog options with Ithania.  Can not rescue her if I can't talk to her. 

As previously reported in #557 which was "fixed" then closed in Dec 2016: 

"Quest: Twilight of the Dawn Runner http://www.wow-mania.com/armory/?quest=9437

Quest Description: Balandar Brightstar in Brackenwall Village wants you to reclaim the Dawn Runner Cargo and rescue his first mate Ithania from forces of Theramore at North Point Tower.

Problem: Rescuing Ithania (http://www.wow-mania.com/armory/?npc=17119) requires speaking to her. Can't talk to her. Dialogue isn't there. Right clicking her does nothing. Not sure if dialogue option is supposed to become available after killing a number of guards in the vicinity, though have tested wiping tower, to no avail.

Everything else seems to work as intended."

**Comment by hotdoggidy** [comment]
Tested on Redemption. Dialogue with Ithania was available. Everything worked fine. Perhaps it was a UI bugg or similar issue preventing you from seeing the selection. 

Quest completed.

**Comment by redhawk816** [comment]
I've tried several times.  Reload, reboot, nothing.  Ticket gets ignored, Ithania has no dialogue option. Cannot complete quest.

**Comment by redhawk816** [comment]
I disabled all of my addons and cleared my cache.  I was able to talk to her but she still didn't move.

**Comment by Emcitementz** [comment]
> Tested on Redemption. Dialogue with Ithania was available. Everything worked fine. Perhaps it was a UI bugg or similar issue preventing you from seeing the selection.

Quest completed.
Careful with that, it has to be tested multiple times for this kind of quests and not only once. It wasn't working after the first try.
It's now fixed.
