### ISSUE TITLE
[Quest] Alpha Worg

### ISSUE THREAD

**Issue by dmtryzhkv** [WoWManiaUK/Redemption#892]
This will be a short summary of a bug. 

[This is a quest](http://www.wow-mania.com/armory/?quest=11326). You are supposed to get [Eyes of the Eagle buff](http://www.wowhead.com/spell=43060/eyes-of-the-eagle) to see [Garwal](http://www.wowhead.com/npc=24277/garwal). You don't get this buff from ****Ulfang****. So this quest cannot be completed. 

Thank you in advance.

**Comment by elagen** [comment]
Confirmed that when accepting the quest http://www.wowhead.com/quest=11326/alpha-worg#comments

we should get http://www.wowhead.com/spell=43060/eyes-of-the-eagle and we dont - this should be given to us to eat so we get the buff to see 	Garwal

**Comment by Dmw1981** [comment]
this is broken he does not spawn over an hour looking in area with hunter tracking
