### ISSUE TITLE
[Quest] The Last Line of Defense

### ISSUE THREAD

**Issue by cHRISJETWC** [WoWManiaUK/Redemption#893]
[This quest seems to be broken.](http://www.wowhead.com/quest=13086/the-last-line-of-defense) turrets don't seem to be on the guard towers which you are supposed to get in. I have reproduced the bug three times.

Thanks in advance.

I would supply a screenshot but I can't seem to find where they get placed in my files.

**Comment by fvicaria** [comment]
Probably a phase issue. Turrets are there. We need someone to test the quest line.

**Comment by elagen** [comment]
confirmed that after doing the quest line the Turrets are not there

http://www.wowhead.com/npc=30236/argent-cannon
