### ISSUE TITLE
[Quest] Conversing With the Depths

### ISSUE THREAD

**Issue by Dragonfly414** [WoWManiaUK/Redemption#894]
https://github.com/WoWManiaUK/Redemption/issues/887

when I am at the summoning stone, I can click it, I see summoning, but nothing happen.
There is no NPC spawning or a script starting.

Hope it will be fixed. Thanks!

**Comment by elagen** [comment]
when doing http://www.wowhead.com/quest=12032/conversing-with-the-depths

you need to use http://www.wowhead.com/object=188422/the-pearl-of-the-depths to summon http://www.wowhead.com/npc=26648/oachanoa

and while clicking on the Pearl as Dragonfly414 says **oachanoa** can not be summoned

**Comment by Plege** [comment]
the pearl can be clicked but nothing happens. if following the instructions from http://www.wowhead.com/quest=12032/conversing-with-the-depths i should get a debuff and then jump into the water (within 20 seconds) but i get no debuff at all on dev
