### ISSUE TITLE
Death runes bugged?

### ISSUE THREAD

**Issue by Lutti92** [WoWManiaUK/Redemption#895]
So.. My boyfriend and I started death knights a couple of days ago. We have both noticed, after getting the death rune mastery talent, that the death runes don't seem to always work. It displays an available death rune, but my boyfriend has experienced being unable to use heart strike regardless. I have experienced the same, except with 2 available death runes and being unable to use death strike. We haven't seen any pattern to it, but it definitely happens sometimes

**Comment by hotdoggidy** [comment]
I have also experienced the same issue.

All of the following Death Knight talents can proc death runes.
Reaping (http://wotlk.openwow.com/spell=56835)
Blood of the North (http://wotlk.openwow.com/spell=54637)
Death Rune Mastery (http://wotlk.openwow.com/spell=50034)

When using a skill that activates Death Runes, the Death knight should be able to use them for any ability that requires a rune regardless of Frost/Unholy/Blood runes available. Tanking in Icecrown Citadel and Ruby Sanctum ive noticed even with 4 death runes active i could not cast Icy Touch (http://wotlk.openwow.com/spell=49904) which requires 1 frost or death rune. 

When this does happen an error message comes up at center of screen "not enough runes to cast". 

As it cannot be recreated on demand i cannot be sure what the circumstances are to cause the bug.

**Comment by fvicaria** [comment]
Please re-try it this Wednesday.
