### ISSUE TITLE
[Quest] In Wine, Truth

### ISSUE THREAD

**Issue by Lutti92** [WoWManiaUK/Redemption#896]
The quest "In Wine, Truth" is bugged - you can't loot the wine from the crate in the water :( you get the loot animation, but no loot from it.

**Comment by fvicaria** [comment]
------ Canned Message -------
Please follow the correct procedure for logging issue:
https://github.com/WoWManiaUK/Redemption/wiki/How-to-Properly-Report-an-Issue
----------------------------------

**Comment by fvicaria** [comment]
Is is working correctly in dev.
