### ISSUE TITLE
Krolmir, Hammer of Storms (Part 5 of 6)

### ISSUE THREAD

**Issue by drewpybaggins** [WoWManiaUK/Redemption#897]
http://www.wowhead.com/quest=13010/krolmir-hammer-of-storms

It appears you need to be Friendly with Sons of Hodir to complete this quest, however in the quest log it showed Neutral/Friendly as the requirement. Not sure if this is a Wow-Mania bug or how it appears normally.

**Comment by fvicaria** [comment]
This is correct.
