### ISSUE TITLE
[Raid] Naxx-Gothik the harvester

### ISSUE THREAD

**Issue by Grindall1** [WoWManiaUK/Redemption#900]
Gothik resets the fight every time he opens his gate that links the two sides of the room (wave 20), making him unkillable.

**Comment by fvicaria** [comment]
Please follow the procedure described below before creating a new issue:
[How to Properly Report an Issue](https://github.com/wow-mania/Redemption/wiki/How-to-Properly-Report-an-Issue)

This will help developers identify and fix the issue quicker. Incorrectly or unclear reports will simply be deleted.

**Comment by Grindall1** [comment]
Am I using our client? (Note: don't even open issue if not)
    Am I using the latest Launcher? (Note: don't even open issue if not)
yes
    Did I include the steps to reproduce the problem?
you start the fight
    Did I include the description of how it should work?
the fight shouldn't reset
    Did I include the description of what is happening?
the fight resets
    Did I include NPC/Item/Spell names (or IDs) from wowhead.com or Armory?
there is none
    Be descriptive and precise.
the. fight. resets.
    DO NOT log multiple issues in one!
this is the only issue

**Comment by Plege** [comment]
Tested this fight, the fight breaks down and resets at wave 17 even before he should teleport down. 

Further the Knights killed don't respawn on the undead side neither do the knights (the horses respawn but not the riders).

NPC ID's:

Gothik the harvester: 16060
NPC_DEAD_KNIGHT = 16148
NPC_DEAD_RIDER = 16150

**Comment by Emcitementz** [comment]
Ulduar is first on the list.

**Comment by tsuff** [comment]
yey ^^

**Comment by Feryk** [comment]
Fix confirmed in Dev. http://imgur.com/a/q0Tgd
