### ISSUE TITLE
[Raid] Ulduar Freya Hard Mode

### ISSUE THREAD

**Issue by Grindall1** [WoWManiaUK/Redemption#901]
Elder Brightleaf - The essence of Elder Brightleaf increases Magic damage dealt by Freya and her Allies of Nature by 60%. Freya also gains the ability to cast Solar Flare, a nuke that may hit multiple targets. 
http://wowwiki.wikia.com/wiki/Freya_(tactics)

Basically, there should be a big beam of light that spawns on the ground when you leave Elder Brightleaf up during the fight on freya; however, the beam's animation doesn't spawn. As soon as the beam spawns on a player, you are supposed to move out of it asap else you get killed. Since you can't see the beam, people start dropping with no known cause.

**Comment by Plege** [comment]
Hey Grindall,
 
I tried recently to confirm some of your issues posted here on our dev server. But my knowledge of the different encounters is not sufficient to check for buggs and confirm them in Ulduar. It might help a lot if you had the time to go there with me and we can check stuff out together to get a hold of the most obvious buggs. If you want to help me with that endeavour please contact me ingame (send mail to Pleger) so we can arrange something.

Regards,
Pleger

**Comment by Emcitementz** [comment]
Don't test it alone.
