### ISSUE TITLE
[Core] Bounties

### ISSUE THREAD

**Issue by hotdoggidy** [WoWManiaUK/Redemption#905]
Players cannot be healed by friendly party/raid members when they have a bounty on their head. This can be a big issue in raids if the tanks or dps have bounties placed on them during their runs. Not sure if this was intended or a result of the Free-for-all tag placed on the player.

**Comment by DeeJayMyMusic** [comment]
Is this at any moment in time? Or is it only when the bounty is placed when they're inside of the instance?

**Comment by DeeJayMyMusic** [comment]
Bug Confirmed.

**Comment by DeeJayMyMusic** [comment]
When the player is marked with a bounty, the player is put in ffa mode and cannot exit until they are killed and the bounty is collected. In ffa mode, we all know that friendly healers cant help you.
