### ISSUE TITLE
[Dungeon] Diremaul East - Hydrospawn

### ISSUE THREAD

**Issue by hotdoggidy** [WoWManiaUK/Redemption#906]
The water elemental boss "Hydrospawn" (http://wotlk.openwow.com/npc=13280) is clipping through the environment. 
He should be in his fountain/pool in the lower level of Diremaul East before venturing out into "The Conservatory" just pathing back and forth.
I sat for 15 minutes and watched as he clipped through obstacles and climbed straight up onto the balcony above. Once up there he would either clip back through the floor or take the path players use to get to "Zevrim Thornhoof"(http://wotlk.openwow.com/npc=11490), the boss on said balcony. its a small tunnel north of Hydrospawn's fountain/pool

**Comment by TenmanWoW** [comment]
Hi, Hotdoggidy! So, now i remember why I hated Dire Maul SO much on retail. Ugh.

Anyways. it would appear that there is indeed an issue as you described. I watched this guy walk through walls and then path just fine up winding stairs. I'm sure the power thats be giving this due concern. Thanks for reporting (but rawrmadgrowl for making me go to Dire Maul)

![wowscrnshot_030117_143832](https://cloud.githubusercontent.com/assets/25806987/23480437/81972e62-fe8d-11e6-87b7-2b26d514c740.jpg)
![wowscrnshot_030117_143853](https://cloud.githubusercontent.com/assets/25806987/23480439/81983cd0-fe8d-11e6-9505-d697a530e67b.jpg)
![wowscrnshot_030117_143859](https://cloud.githubusercontent.com/assets/25806987/23480438/8197f1ee-fe8d-11e6-90f0-04ca896c045b.jpg)

**Comment by Rushor** [comment]
add unitstate ignore pathfinding for him

**Comment by Rushor** [comment]
or add this path for him:

```sql
-- DB/Creature: Hydrospawn - Pathing
-- Hydrobrut
SET @NPC := 84382;
SET @PATH := @NPC * 10;
UPDATE `creature` SET `spawndist`=0,`MovementType`=2 WHERE `guid`=@NPC;
DELETE FROM `creature_addon` WHERE `guid`=@NPC;
INSERT INTO `creature_addon` (`guid`,`path_id`,`mount`,`bytes1`,`bytes2`,`emote`,`auras`) VALUES (@NPC,@PATH,0,0,1,0, '');
DELETE FROM `waypoint_data` WHERE `id`=@PATH;
INSERT INTO `waypoint_data` (`id`,`point`,`position_x`,`position_y`,`position_z`, `delay`) VALUES
(@PATH, 1, 4.57887, -438.407, -59.954, 0),
(@PATH, 2, -33.6927, -415.93, -59.9502, 0),
(@PATH, 3, -6.58793, -429.432, -59.9504, 0),
(@PATH, 4, 4.98108, -416.84, -59.9505, 0),
(@PATH, 5, -6.58793, -429.432, -59.9504, 0),
(@PATH, 6, -33.6927, -415.93, -59.9502, 0);
```
