### ISSUE TITLE
[Quest] The Drakkensryd

### ISSUE THREAD

**Issue by Dragonfly414** [WoWManiaUK/Redemption#907]
I didn't accepted the quest right away... because I got flagged for PVP...
But now I cant get the quest...

I got the feeling the quest is linked in any way, but the questgiver and questender are not the same.
On this way you get this kind of bugs that the ? is grey at the questgiver.

Please check if this is the issue!
http://www.wowhead.com/quest=12886/the-drakkensryd

**Comment by fvicaria** [comment]
Not a bug. You should not abandon it.

**Comment by Dragonfly414** [comment]
and now I abandon it... I will not get it?? 
I did not abandon it... never got it in my questlog............

**Comment by fvicaria** [comment]
Open a ticket.

**Comment by Dragonfly414** [comment]
like I did, waited long time... now I have to go and no respons...
Pity how there is be reacted on this issue... if you got flaged PVP  you dont need to get the quest right away with many hordes/allies in the same area...
It is easy to fix, something with 1 and 0s in the database... pity...
The quest is just autocompleted, thats why the questender is having a yellow ? and the quest giver a gray ?...
But no, you easy give the responce: you should not abannon it...
Like everybody goes right away in PVP if there is a horde behind him/her...
