### ISSUE TITLE
[Spell] Warlock Death coil

### ISSUE THREAD

**Issue by vregor97** [WoWManiaUK/Redemption#910]
Death coil seems to be healing twice the amount that it should. Atleast from what I've seen at 60-70. It healed for my full hp bar. It could be with all the modifiers etc. that increased healing like Demonic Skin. But in my opinion it looked like it healed too much. If this isn't a bug and it is supposed to be healing this amount just ignore this issue. A gm told me to report it here.

**Comment by hotdoggidy** [comment]
Death Coil - (http://wotlk.openwow.com/spell=47860)
The wording in game says "Caster gains 300% of the damage dealt in health" but the tooltip from Open-wow says it should be "100% of the damage dealt in health" this may be where the difference is coming from.
