### ISSUE TITLE
[Spell] Death Knight - Death Coil

### ISSUE THREAD

**Issue by hotdoggidy** [WoWManiaUK/Redemption#911]
Death Coil (http://wotlk.openwow.com/spell=62904) should deal damage to an enemy target or heal a friendly undead target. 

Death Coil currently CANNOT be cast at a friendly undead target, even in party/raid. However, a Death Knight using the Frost spec talent "Lichborne" (http://wotlk.openwow.com/spell=50397) can be tragetted and healed by another Death knight's Death Coil. 

"Lichborne" allows a Death Knight to "draw on unholy power to become Undead for 10 sec"

There seems to be an issue with how the spell determines a character is undead.

**Comment by Plege** [comment]
i'm at work so i can't check for myself but, the healing of the warlock death coil seems have the same issue. it heals for unexpected amounts (this is from memory can anyone check?) http://wotlk.openwow.com/spell=6789

**Comment by Plege** [comment]
nevermind me i wasn't paying attention. there is already a post about it
