### ISSUE TITLE
RAF perk bugged

### ISSUE THREAD

**Issue by Lutti92** [WoWManiaUK/Redemption#912]
The day before yesterday, my boyfriend and I were leveling our chars (both same level) and decided he'd just run to Ironforge while I stayed in Darnassus or something similar - a long run nontheless - and when he got there, we weren't able to summon. Not through the friendlist, nor through the right-click menu :( Yesterday evening, it was working again, and now today, it's not working again.

**Comment by fvicaria** [comment]
Please read the RAF Guide on the forum and make sure you comply with all conditions.

**Comment by Lutti92** [comment]
We have used the RAF summon since the day my boyfriend invited me to play, and it has been working in between, on the same chars, at the exact same level as when it was not working.

**Comment by Lutti92** [comment]
As example as well - we currently just tried with a level 1 and level 3 character. We were in party together, we had each other on each other's friendlist, and we were still not able to summon. It also happened on our level 27 and 28 characters the other day.

**Comment by fvicaria** [comment]
I will re-check. Take a look at the guide. There are limits on how often you can use the summon.

**Comment by Lutti92** [comment]
The limit has always been said in red text on the screen when we've tried to use it :)

**Comment by Lutti92** [comment]
Update on the problem:
My boyfriend and I just made new characters about an hour ago, in seperate starting zones (draenei for me, human for him) and the XP bonus now didn't work (yes we were in a group with each other of course). It doesn't say anything in the guide about "physical" (in the game obviously :P) distance between players being a barrier and my boyfriend got bonus XP while in Darnassus, while I was in Stormwind on my way to Ironforge (same time we realised the summon wasn't working the day before yesterday, or may have been yesterday morning). Not sure if it was a bug that he got XP while I was in Stormwind, or if it's a bug that we don't get when we're far apart but still in a group together?

**Comment by fvicaria** [comment]
Can you send me both your usernames please via email or skype. Thanks.

**Comment by Lutti92** [comment]
Via e-mail is just the support@wow-mania.com, yeah?

**Comment by fvicaria** [comment]
correct

**Comment by Lutti92** [comment]
Roger that - email has been sent :)
