### ISSUE TITLE
[Dungeon] Utgarde Pinnacle (Heroic)

### ISSUE THREAD

**Issue by Jibb94** [WoWManiaUK/Redemption#913]
When you encounter Skadi the Ruthless he does not fly and gets stuck in the ground preventing the dungeon from continuing. 

http://www.wowhead.com/npc=26693/skadi-the-ruthless

I don't know if this happens in normal.

**Comment by elagen** [comment]
I can comfirm that while in Utgarde Pinnacle the boss
http://www.wowhead.com/npc=26693/skadi-the-ruthless -- jumps onto Grauf http://www.wowhead.com/npc=26893/grauf

starts the boss event where you need to shoot him down and then kill the boss
but the Skadi while jumping onto Grauf gets stuck in the floor 

http://i.imgur.com/P10aGwq.jpg

**Comment by Plege** [comment]
the issue persists.

**Comment by Jibb94** [comment]
I have done this dungeon since this issue was closed and it still has the problem should I submit a new issue?

**Comment by Plege** [comment]
This is interesting indeed. as it was working on dev and then put in a release on redemption. we will have to test again for it.
