### ISSUE TITLE
[Quest] Chasin Icestorm: Thel'zan's Phylactery

### ISSUE THREAD

**Issue by Karlusdark** [WoWManiaUK/Redemption#914]
In the quest [Chasing Icestorm: Thel'zan's Phylactery](http://www.wowhead.com/quest=12467/chasing-icestorm-thelzans-phylactery) when talked to the NPC [Wyrmbait](http://www.wowhead.com/npc=27843/wyrmbait) so he can lead the frost wyrm [Icestorm](http://www.wowhead.com/npc=26287/icestorm), he comes back alone without the wyrm behind him, and when near Icestorm it's rendered as "Invalid target" being unable to be attacked or pulled towards the camp.

**Comment by elagen** [comment]
I can confirm that while doing the quest and when you speak to http://www.wowhead.com/npc=27843/wyrmbait he should bring back Icestorm 

but here you can see him fly back without Icestorm 
http://i.imgur.com/uP2wair.jpg

and when you run forward you then can see Icestorm 
http://i.imgur.com/0Wwp1bs.jpg

As you can see here Icestorm Is phased out and can not be attacked and the Quest cannot be completed
