### ISSUE TITLE
[Spell] Ferocious inspiration removing Retribution aura

### ISSUE THREAD

**Issue by ClavosThePally** [WoWManiaUK/Redemption#915]
I've been leveling together with 2 friends.
We are me as a protection paladin, one friend as holy paladin and one other friend as Beast Mastery hunter.

We did not have this issue before, but recently upon arriving in northrend, the hunter's Ferocious inspiration talent makes retribution aura something I can't have.

I always walk around with Devotion aura, and my other paladin friend used to use Retribution aura to help me.
However recently, we can't even click the aura even more, we don't get the buff, and for some reason it only happens when our hunter's pet is nearby, so when he is mounted retribution aura works as intended.

but the second his pet is out and ferocious inspiration is shared, retribution aura dissapears.
We tried other auras, and all other auras work as intended.

We also tried having the hunter bring different pets, did not change anything.

**Comment by Plege** [comment]
I can confirm that the Ferocious Inspiration overrites the Retribution Aura just as if they were two auras giving the same buff but they are clearly not. 

I also checked if it is a purely visual bugg i.e. the aura not showing as an icon but still in effect. This is also not the case, the retribution aura is basically removed for the duration of Ferocious Inspiration being active.

Further is this effect also present in Kalimdor not just Northrend.

Ferocious Inspiration: http://wotlk.openwow.com/spell=75447
Retribution Aura:        http://wotlk.openwow.com/spell=54043

**Comment by ClavosThePally** [comment]
Sadly nobody is around to test this out now, but I remember it working correctly in outlands, but that could also be a case of me not paying attention

**Comment by fvicaria** [comment]
Will take effect on next restart.
