### ISSUE TITLE
[Quest] The Killing Time

### ISSUE THREAD

**Issue by Karlusdark** [WoWManiaUK/Redemption#916]
As said on issue #721, in the quest [The Killing Time](http://wotlk.openwow.com/quest=13371) after accepting it and talking to [Jaina Proudmoore](http://wotlk.openwow.com/npc=32346) for the opening of the portal for Undercity there is no option for telling her to open the portal, making this quest impossible to finish because if using any other means of getting to the sewers in Tirisfal Glades all the Alliance forces are missing.

PS: although this issue is already open by other person i'm posting it again because on issue #721 there's no one assigned to fix it since 01/26/2017

**Comment by fvicaria** [comment]
Duplicate. Please search before entering a issue.

Please follow the procedure described below before creating a new issue:
[How to Properly Report an Issue](https://github.com/wow-mania/Redemption/wiki/How-to-Properly-Report-an-Issue)

This will help developers identify and fix the issue quicker. Incorrectly or unclear reports will simply be deleted.

**Comment by Karlusdark** [comment]
Then fix the issue that is still present and makes the quest impossible to complete, I myself said it was duplicate because apparently no one is doing anything about the #721

**Comment by fvicaria** [comment]
So maybe if you create it 5 times we may resolve it faster.
Read the rules please.

**Comment by Karlusdark** [comment]
maybe you'll at least assign someone to resolve it, which is not the case for more than a month
