### ISSUE TITLE
[NPC] Narasi Snowdawn

### ISSUE THREAD

**Issue by Dragonfly414** [WoWManiaUK/Redemption#918]
http://www.wowhead.com/npc=34880/narasi-snowdawn#starts

Hello,

NPC in the link above is having a blue ! above her head, but I cant get the quest.
I dont find on the website what rep I have to get or what quest unlocks this one...
Could you tell me when I can get these dailies?

Thanks

**Comment by TenmanWoW** [comment]
I will go look at this, as soon as the servers come back up. Could you let me know your progress with the faction and current player level?

-Tenman

**Comment by TenmanWoW** [comment]
You must be at least level 77, but likely the by time you reach exalted, 80. Also, as I just said, you must be exalted before she offers you the dailies that the blue ! signifies. It's merely a visual bug but once you get Silver Confidant title, it opens up to you.

http://wow.gamepedia.com/Narasi_Snowdawn

Hope this helps!

**Comment by Dragonfly414** [comment]
Thanks for you answer. I am lvl 80 but not exn0

**Comment by Dragonfly414** [comment]
But not extalted yet. Could not find I had to be that. Thanks... now I know what I need to do :)
