### ISSUE TITLE
[Quest] Sweet Amber

### ISSUE THREAD

**Issue by Dragonfly414** [WoWManiaUK/Redemption#920]
http://wotlk.openwow.com/quest=51
You need:
http://wotlk.openwow.com/item=742#dropped-by
dropped by:
http://wotlk.openwow.com/npc=5881

Looked everywhere in the area, but no Cursed Sycamore :)

**Comment by fvicaria** [comment]
![image](https://cloud.githubusercontent.com/assets/9414661/23607630/804c2a16-025d-11e7-96ef-ae660de919af.png)
