### ISSUE TITLE
[Quest] Waterlogged Recipe

### ISSUE THREAD

**Issue by redhawk816** [WoWManiaUK/Redemption#921]
Fished up several Waterlogged Recipes http://wow-mania.com/armory/?item=48679#starts-quest.  This item is not unique and should start a quest that is repeatable.   http://wow-mania.com/armory/?quest=14203.  Currently this quest can only be done once, but you can still fish up the item after completion.

**Comment by fvicaria** [comment]
Quest is repeatable. Just tested in Redemption.
The drop rate is is 0.9%.

**Comment by redhawk816** [comment]
So why when I'm not on the quest it tells me that I'm already on the quest and it won't let me do anything?
