### ISSUE TITLE
[Dungeon] Dire Maul, East

### ISSUE THREAD

**Issue by redhawk816** [WoWManiaUK/Redemption#922]
Seems the same issues from Dungeon: Dire Maul (East Specifically) #84 are back again.  Pusilin runs across the sky then back to his beginning spot.  And Hydrospawn swims up the air out of reach, and if you try to reach him on the 2nd level he resets.

**Comment by fvicaria** [comment]
Not happening. This was probably due to the regress of the server to what it was a week before during the weekend. Seems fine now.
