### ISSUE TITLE
[Quest] Marla's Last Wish

### ISSUE THREAD

**Issue by Readerlady** [WoWManiaUK/Redemption#924]
http://www.wowhead.com/quest=6395/marlas-last-wish

I have Samuel's remains but the grave does not work when I click on the wheel. Relogged...nothing.

**Comment by elagen** [comment]
i have just tested and completed the quest

Here is the npc you need to kill http://wotlk.openwow.com/npc=1919 to get the remains

http://i.imgur.com/Rp2423p.jpg 

here is the grave next to the church on where you get the quest and im standing next to the grave
