### ISSUE TITLE
[Spell] Corpse Explosion

### ISSUE THREAD

**Issue by zyklonb** [WoWManiaUK/Redemption#925]
Corpse explosion is not working properly, when used on pet it sometimes buggs out and does nothing while consuming the 40 runic power and puts the spell on cooldown.
I think its because of the pet being on gcd or something anyways made a vid

https://youtu.be/Ci1YzTaBE90

**Comment by elagen** [comment]
i have tested this out for about 30 mins now 

its works on humoids - undead - beast corpses 

 Will use a nearby corpse if the target is not a corpse. **Does not affect mechanical or elemental corpses.**

i had a pet out aswell and it worked fine all the time

i could not get it to bug out like you say - it is working like it should

**Comment by zyklonb** [comment]
It is not working as it should, watch the video

**Comment by elagen** [comment]
i did do what you have done in the video - had the pet - tried explosion and could not replicate - ill see if someone else can test and see what result they get
