### ISSUE TITLE
[NPC] Nether Ray skin

### ISSUE THREAD

**Issue by Dragonfly414** [WoWManiaUK/Redemption#928]
Hello,

Nether ray fry, my pet, is only a blue/white cubus :)
http://www.wowhead.com/npc=28470/nether-ray-fry
![wowscrnshot_030617_194039](https://cloud.githubusercontent.com/assets/24796963/23675913/2f67e7e2-037b-11e7-8085-638c9beb5027.jpg)
see picture, ist very very small

Also the same ID is for Netherskate; http://www.wowhead.com/npc=21901/netherskate
![wowscrnshot_030617_194008](https://cloud.githubusercontent.com/assets/24796963/23675946/4beb74e2-037b-11e7-8dd8-789ae2658fee.jpg)

Maybe you could connect other dispay ID too these both?
http://www.wowhead.com/npc=22958?

Thanks for looking at it

Flamable

**Comment by hotdoggidy** [comment]
Are you using the WoW-mania launcher and is it up to date?

**Comment by Dragonfly414** [comment]
Yes, 
I am using the launcher from wowmania and is up to date. Everytime when it startsul its checking for updates.

**Comment by hotdoggidy** [comment]
-The Netherskates (npc=21901) Seem to be the only nether rays that have lost their appearance.
-The "Nether rays" (npc=18880) in Netherstorm appear as intended as do the "Skyguard Nether Rays" (npc=22987) in Terrokar Forest and Blade's Edge Mountains.
-Do not have the pet to confirm. (npc=28470)
