### ISSUE TITLE
[Race - Undead] Gutterspeak

### ISSUE THREAD

**Issue by Tykune** [WoWManiaUK/Redemption#931]
So, this seems like a minor issue, but I would like to see it resolved considering it takes away from the immersion of those NPCs in Undercity who do speak Gutterspeak.

The issue is that Undead players do not naturally get Gutterspeak as one of their languages.

**Comment by elagen** [comment]
Confirmed that the Forsaken Race does not Know the Gutterspeak language and they should 

![wowscrnshot_031317_132927](https://cloud.githubusercontent.com/assets/22685042/23856319/2fcc2ad4-07f1-11e7-9d96-b96e6ed867b9.jpg)

http://wotlk.evowow.com/?race=5#languages
