### ISSUE TITLE
[Raid] ICC HC Professor Putridcide

### ISSUE THREAD

**Issue by Plege** [WoWManiaUK/Redemption#932]
Hey guys,
I found another possible icc bug at hc PP (10/25)

During the transitionphases when 2 oozes are up they can both target the same player green will make him immobile and orange will wipe the raid in most cases once he catches up to the player. 

It's hard to definetly prove that this double targeting is a bug as it's hard to prove a negative and it won't very unlikely show up on any video because people only post kill videos and if that specific situation occurs it's higly unlikely to result in a kill.

My argument is that there shouldn't be a rng mechanic that with such high probability wipes the entire raid.

The problem is even worse when in 10 hc as the number of possible targets is so low.

Regards,
Pleger

**Comment by wcslanker** [comment]
I second this, 

this is very buggy as in the fact that the green ooze will make it to the targeted player while the orange is also targeting them, and for some reason causing an explosion, rather than knocking everyone back to at least have a chance for the player to run away from the orange one.

**Comment by GameMasterAlliria** [comment]
It is however possible. Within the rng of the fight. That you CAN have a double target. It's not a bug in its entirety. However double targeting should be extremly rare.
