### ISSUE TITLE
Dark Iron Plans [Blacksmithing Recipe]

### ISSUE THREAD

**Issue by WastedMoment** [WoWManiaUK/Redemption#935]
So, i've been trying to collect all the Dark Iron blacksmithing plans on my warrior, two of the recipes are obtained through "scrolls" located in 5 locations throughout Blackrock Depths. To my knowledge they act almost like the Schematic for the Repair Bot next to Golem Lord Anglemarch. I ran the dungeon a total of 5 times, collected a scroll and i did not obtain either one of the two plans they would give.

Dark Iron Shoulders[http://www.wowhead.com/item=11615/plans-dark-iron-shoulders](url)
Dark Iron Mail [http://www.wowhead.com/item=11614/plans-dark-iron-mail](url)

These are the two plans that are learned from the scroll(s). There is a total of 5 total spawn locations that should appear in BlackRock Depths, however i'm only noticing one spawn in BlackRock Depths which is on a bench outside of Golem Lord's location.

**Comment by fvicaria** [comment]
They are all there.
