### ISSUE TITLE
[Battleground] Wintergrasp - Tower Cannon

### ISSUE THREAD

**Issue by hotdoggidy** [WoWManiaUK/Redemption#940]
At the start of each Wintergrasp battle there are 35 "Tower Cannons" (http://wotlk.openwow.com/npc=28366) on the battle field. 23 are located on walls and towers of the Wintergrasp Fortress. 12 others can be found at each southern tower. Each cannon has a 180deg turn radius in which it can fire.

These Cannons work 99% as intended. Only Alliance can mount/control Alliance cannons and only Horde players can mount/control Horde cannons. Damage is scaling properly with/without tenacity. Damage not being dealt outside of range.

Their only issue is how they spawn. They should spawn facing the same direction whatever wall/tower they are at is facing. I.e. A southern facing wall should have southern facing cannons. These cannons should be able to turn 90deg West and 90deg East. In some cases there are multiple cannons in the same position.

As it stands on Redemption. Cannons can spawn at all sorts of angles. Some are facing 180deg the wrong way, some are 90deg offset and some in between. This can be a big issue when defending a tower or fortress as you wont have the angle to shoot at attacking forces.

**Comment by fvicaria** [comment]
Again please images.
Also the cannons rotate so I do not see the issue.

**Comment by hotdoggidy** [comment]
They turn fine within their 180 degree angles. The center point when they spawn is what is off. The cannons should not be able to aim at the fortress itself. Defenders will lose some edge from the 30+ degrees not covered by some of the turrets when they spawn like this,

Front gate cannon max-left.
![wowscrnshot_031017_025539](https://cloud.githubusercontent.com/assets/23442126/23790740/9c65d19c-053d-11e7-9fd4-db84a76c25be.jpg)

Front gate cannon max-right.
![wowscrnshot_031017_025547](https://cloud.githubusercontent.com/assets/23442126/23790754/abb36c54-053d-11e7-8dfe-a6cab71ca014.jpg)

Tower cannon original position. 
![wowscrnshot_031017_030416](https://cloud.githubusercontent.com/assets/23442126/23790941/677b7dc8-053e-11e7-8bf0-07b08f9cf528.jpg)

Tower cannon max-left.
![wowscrnshot_031017_030419](https://cloud.githubusercontent.com/assets/23442126/23790952/7428b018-053e-11e7-8701-268a08ecfde1.jpg)

Tower cannon max-right.
![wowscrnshot_031017_030423](https://cloud.githubusercontent.com/assets/23442126/23790959/7f07f732-053e-11e7-98ca-dd50d324919d.jpg)

Inner wall cannons original position @ start of battle.
![wowscrnshot_031017_030727](https://cloud.githubusercontent.com/assets/23442126/23791085/f69c0676-053e-11e7-8403-8a1b3c78c056.jpg)

The left cannon is 180 degree offset, facing toward the mine entrance and cannot be used to aim at enemies entering from the gate or front walls. The right cannon is 90 degree offset, facing the East outer wall. Neither of these could be used to defend an attack from the West.

**Comment by keboid** [comment]
I posted it also 2 times both times cinfirmed fixing and its the same all the times. Definitely not fixed. Placing is also still bad like i posted 2 times earlier.

**Comment by fvicaria** [comment]
Read the label please.
