### ISSUE TITLE
[Battleground] Wintergrasp - Southern Towers

### ISSUE THREAD

**Issue by hotdoggidy** [WoWManiaUK/Redemption#941]
There are three southern towers in Wintergrasp: 
Shadowsight Tower (http://wotlk.openwow.com/object=190356)
Winter's Edge Tower (http://wotlk.openwow.com/object=190357)
Flamewatch Tower (http://wotlk.openwow.com/object=190358)

These towers "draw energy from the fortress" to empower the attackers. These towers always belong to the attacking Faction. They each give a 5% damage buff to players of that faction. As each one is destroyed by the defenders it will transfer the 5% buff to the defending faction's players.

The buffs work as intended. As do the towers and their health pools. 

The issue here is there are multiple towers spawning in the same place. i.e 2 shadowsight towers spawned directly on each other will give the illusion it is still there after being destroyed. A player can easily check their map to see if a tower is actually up. However, the second tower(s) do not take damage, do not give buffs and can still be accessed after the first tower is destroyed. 

#940 i mentioned multiple cannons spawning on each other. This is ONLY happening on these southern towers where there are more than one tower in each spot.

**Comment by fvicaria** [comment]
Two things. 
1. Do not confirm your own issues.
2. Attacking an image would help. This sound like a duplicate spawn.

**Comment by hotdoggidy** [comment]
Winter's Edge tower 0%. (destroyed, only bottom half highlighted)
![wowscrnshot_031017_032226](https://cloud.githubusercontent.com/assets/23442126/23791612/e9127aec-0540-11e7-9d55-27b56cd1dc8c.jpg)

Winter's Edge tower 100%. (only top half highlighted)
![wowscrnshot_031017_032228](https://cloud.githubusercontent.com/assets/23442126/23791655/11b7a832-0541-11e7-8c02-167c8ca5fea3.jpg)

Winter's Edge tower before/after battle 100%. (Whole thing highlighted)
![wowscrnshot_031017_032558](https://cloud.githubusercontent.com/assets/23442126/23791719/5f7279da-0541-11e7-97e5-4bb5a2e3c948.jpg)

Destroyed Shadowsight tower image pulled from google,
![shadowsight tower](https://cloud.githubusercontent.com/assets/23442126/23791870/f285e1b2-0541-11e7-9c72-e7664b953859.jpeg)

All the towers should look like this when brought down.
