### ISSUE TITLE
[Spell] Tenacity - Wintergrasp

### ISSUE THREAD

**Issue by hotdoggidy** [WoWManiaUK/Redemption#944]
Wintergrasp is an open, world-pvp zone. It has a limit of 40 players per faction, per battle. Once the 40 man group has been filled no more players can join the group but they can still enter the battlefield. 

Since it does not function like a normal BG queue and can have severly imbalanced teams i.e 5v30 the faction with less players in the fight are given a buff "Tenacity"(http://wotlk.openwow.com/spell=58549). It is applied with varying levels of stacking, with an apparent maximum of 20 stacks.

As long as one team is outnumbered they have some sort of tenacity. 

Here is where it gets tricky. If the battle starts, 4 Alliance and 1 Horde join instantly, that single Horde will get a stack or 2 of Tenacity depending on lvl and power the 4 Alliance. As long as the Alliance continue to outnumber the Horde, Horde players will get more stacks of tenacity to help balance the fight. 

If there is a sudden shift in numbers, be it from Alliance players leaving or many Horde joining at once, the tenacity can bug. Using the example from before 4v1. If 10 horde players joined all at once, making it 4v11, The Alliance will start to build tenacity stacks to balance out the groups once more. However, that single horde that had tenacity at the start will maintain his stacks regardless of how overwhelming his group is. 

Tenacity seems to work as intended unless a big wave of players join that throw off the scales. It seems to ignore the few players with tenacity and treat the whole group as a new batch of players.

i cannot recreate this bug at will on my own but i have seen it happen multiple times in WG. I spend alot of time in WG fishing. When the battle starts i join group as to not get teleported out of the zone. At times ive noticed Horde with 20-30 players more than Alliance yet i still have a stack of tenacity from the start of the fight when there were a couple more Alliance than Horde.

Will need a day to test this with at least 30 players. 15 from each faction.

**Comment by fvicaria** [comment]
Until we have hard evidence that this is not correct I will not spend time on it.
