### ISSUE TITLE
Shadowmeld Bug

### ISSUE THREAD

**Issue by Dusticles** [WoWManiaUK/Redemption#949]
Hey gms! Me again, when raiding shadowmeld is suppost to have you leave combat for about 1. or 2 seconds before you go abck into combat again with some aoe hitting u or breaking stealth because your ina  raid... etc.
http://www.wowhead.com/spell=58984/shadowmeld
So its like the .cl except no stun and just has you leave combat entirely for a breif moment unless ur not hit at all by aoe and dont move at all.

**Comment by elagen** [comment]
i have been trying to find out more about this Racial and from what i have found it does NOT take you out of combat

 **Any threat is restored versus enemies still in combat upon cancellation of this effect.**

Shadowmelding during MOST boss encounters (i.e Nax, Malygos, most heroic bosses) will NOT take you out of combat, therefore you cannot drink, revive, or reset your mana potion CD.

Don't try Shadowmelding while you have a DoT on you, it will bring you out as soon as it ticks.

so during a raid encounter it will not take you out of combat - it will just reduce your threat 
If that is what it doing then it is working properly
