### ISSUE TITLE
Magic Resist Potion Bug

### ISSUE THREAD

**Issue by Dusticles** [WoWManiaUK/Redemption#950]
http://www.wowhead.com/item=9293/recipe-magic-resistance-potion#dropped-by

Seems to not be showing up on the character sheet when applied however it states that it is a potion with a 2 min cooldown which should stack with any resistance buffs the player may have

**Comment by elagen** [comment]
i have just brought the potion on Red and used it - all my Resists went up by 50 

Without potion
![wowscrnshot_031117_081143](https://cloud.githubusercontent.com/assets/22685042/23821691/9f8359da-0632-11e7-8513-c6dad6b59b19.jpg)

With Potion on Buff Bar
![wowscrnshot_031117_081148](https://cloud.githubusercontent.com/assets/22685042/23821696/b39e0c12-0632-11e7-98ab-f6228b9cb5ce.jpg)

As You Can see my Resists gone up by 50
![wowscrnshot_031117_081152](https://cloud.githubusercontent.com/assets/22685042/23821700/c3fa5714-0632-11e7-924d-4ea6f89236ce.jpg)

**Comment by Dusticles** [comment]
I should have made it more clear... it does not show up on the character sheet after similar buffs such as gift of the wild and frost resist aura are on
