### ISSUE TITLE
[Dungeon] Utgarde Pinnacle, Skadi the Ruthless (Heroic)

### ISSUE THREAD

**Issue by Jibb94** [WoWManiaUK/Redemption#951]
I posted this issue before but i just did the dungeon a few min ago and Skadi does still glitch into the ground.  

Skadi: http://www.wowhead.com/npc=26693/skadi-the-ruthless 
Jumps onto Grauf: http://www.wowhead.com/npc=26893/grauf

starts the boss event where you need to shoot him down and then kill the boss
but the Skadi while jumping onto Grauf gets stuck in the floor

http://i.imgur.com/P10aGwq.jpg

I thought it would just be easier to open a new issue.

**Comment by elagen** [comment]
Confirmed that Skadi is still bugged and Still stuck in the floor

![wowscrnshot_031117_082514](https://cloud.githubusercontent.com/assets/22685042/23821762/5c6fc0d2-0634-11e7-813b-04ecb897cf97.jpg)

**Comment by Plege** [comment]
Just a reminder. A week ago Janitor fixxed this issue on dev and i tested it. Skadi was flying and could be shot down by the cannons all mechanics to my knowledge working properly. This means somehow that fix didn't make it to red. On the other hand it indicates that Janitor already found the bugg before and he will again :-)
