### ISSUE TITLE
Omen of Clarity

### ISSUE THREAD

**Issue by Tarmuyi** [WoWManiaUK/Redemption#952]
I'd like to point out that clearcasting is not working as intended for restoration druids. It seems to work perfectly fine for ferals, but I've yet to see it proc once when healing in combat. It seems to work out of combat just fine, when freecasting in Dalaran. 

Kind regards
Tarmuyi

**Comment by wcslanker** [comment]
I'm confirming this does not work in tree form in and out of combat.

On the test server I tried multiple things: *note* I was in fact in tree form throughout all my testing
1 - tried in a duel and it was working for Nourish/Regrowth/Healing Touch and the heals were directed towards myself obviously.

2 - tried it outside while I had aggro on a mob and once again Nourish/Regrowth/Healing touch were working on myself and on another player when they had aggro. 

**3 - the spells that did not work include: Wild Growth/Rejuvination/Lifebloom.** 

-Scroopynuper

**Comment by elagen** [comment]
![wowscrnshot_031317_091347](https://cloud.githubusercontent.com/assets/22685042/23849510/c24fbc7c-07d3-11e7-9a07-42fe75dafb81.jpg)

the buff is working like it should
