### ISSUE TITLE
[Quest Line] It's all fun and games

### ISSUE THREAD

**Issue by wowgamer1980** [WoWManiaUK/Redemption#955]
Hello,

Its the quest line Its All Fun And Games which opens the Knights Of The Ebon Blade Fanction.
You get the item from the Horde ship flying around Icecrown. The quest gives you a quest item Eyesore Blaster to destroy The Ocular. Using the item close to The Ocular channels and hit it.
The problem is the item is not channeling and you can't hit The Ocular.

Please Fix It. It is importand to open the Knights Of The Ebon Blade Fanction.

Thanks

**Comment by elagen** [comment]
While at the ocular http://www.wowhead.com/quest=12892/its-all-fun-and-games

http://www.wowhead.com/item=41265/eyesore-blaster is supposed to be used to damaged the ocular but it is not channeling the spell and Not Damaging the Ocular

**Comment by ingelinge40** [comment]
When attacking ocular it doesnt  do any 
![wowscrnshot_061417_230015](https://user-images.githubusercontent.com/25806660/27154514-9946e582-5155-11e7-9d73-2cf31f44c7c6.jpg)
 damage

**Comment by calvinidea** [comment]
Same problem. Still happening today.

**Comment by tvshadowz** [comment]
Hey there Calvinidea!

Could you please submit this issue again and it will be tested.

Thanks!

**Comment by calvinidea** [comment]
Wait you want me to open a new issue? The GM told me to post it on this issue.

**Comment by GmSaintz** [comment]
I can verify this is happening to multiple people, I have had them try it all different ways and they cannot seem to get it.

**Comment by Proxheimo** [comment]
Yea I had the same issue. Can't kill the Ocular and had issues.

**Comment by tvshadowz** [comment]
Hi Calvinidea!

Yes please! If this issue has been opened, fixed and closed before we'll need another report of the same issue so we know it has to be fixed again. 

Thank you for your patience  and participation in making the server the best it can be! :)
