### ISSUE TITLE
[Quest] The Plains Of Nassam

### ISSUE THREAD

**Issue by wowgamer1980** [WoWManiaUK/Redemption#956]
Hello again,

In Borean Tundra there is a quest called The Plains Of Nassam. While doing it, you must get a tank and do some things. Your action bar also changes. 
- The first skill of the new bar isn't working.
- You must resque some injured soldiers using a skill of the tank. When you press the skill nothing happened. You cant save them so you can't do the quest.

Please fix it.

Thanks a lot for your time.

**Comment by wcslanker** [comment]
![wowscrnshot_031317_193046](https://cloud.githubusercontent.com/assets/25258114/23881878/79211770-081a-11e7-8767-41591e70d2f0.jpg)
![wowscrnshot_031317_193106](https://cloud.githubusercontent.com/assets/25258114/23881880/7a6f70a4-081a-11e7-998f-c7a3e9461b0c.jpg)

**Comment by elagen** [comment]
i have just done this quest and it is working fine - with the pet bar it might be your UI problem - if you have a UI other then the blizzard UI then you probably will have to enable your pet bar 

as for the Rescuing the Injured Soldiers you will have to stand next to them - and you can rescue them

**Comment by wowgamer1980** [comment]
I have tried to do it today with a differend character. The problem persists. i can't save anyone ... the skill works but the soldier doesnt get saved. Im using the original UI.
