### ISSUE TITLE
[Talent / Pet] Wild Hunt 

### ISSUE THREAD

**Issue by Fygarzx** [WoWManiaUK/Redemption#957]
I recently had invested points on the talent skill called Wild Hunt, that makes the pet get more Stamina and Attack power depending the hunter's own Stamina and Attack power. 
But I noticed that after putting the points the stats has no changes at all. Sometimes after my pet leveled up it got the stats of wild hunt until it dismissed and come back, removing the bonus stats of said skill. but on the abilities tab Wild Hunt is still learnt.
![wild hunt bug](https://cloud.githubusercontent.com/assets/26393271/23876460/6249ccfc-081c-11e7-8a1b-d9d4dcb1c125.png)
Here is with no points invested (left) level one (middle) level 2 and max (right)

**Comment by wcslanker** [comment]
![wowscrnshot_031317_193046](https://cloud.githubusercontent.com/assets/25258114/23881908/afd29da2-081a-11e7-9683-a97ee3c869d1.jpg)
![wowscrnshot_031317_193106](https://cloud.githubusercontent.com/assets/25258114/23881909/b1638866-081a-11e7-9193-85b217000e15.jpg)

**Comment by elagen** [comment]
http://wotlk.openwow.com/spell=62762
