### ISSUE TITLE
Prowl re-enabling pvp

### ISSUE THREAD

**Issue by Lutti92** [WoWManiaUK/Redemption#958]
For some reason, pvp became temporarily enabled on my druid. It kept being enabled, then showing the 5 min "cooldown", then enabled etcetc. I just now realised it re-enables every time I go into prowl, if I do it within the 5 min "cooldown". I'm fairly certain it's not supposed to do that :)

**Comment by fvicaria** [comment]
Free-4-all zone.

**Comment by Lutti92** [comment]
It's not free for all zone. Stop being lazy with just closing issues that are actually issues. I was in Sholazar Basin - God knows why it turned pvp on (flying over WG when I went here to quest maybe?) and as soon as I afk'ed for 5 mins, I could prowl without it enabling again. It's still an issue that needs to be dealt with though, even if it's not top priority as it's not crucial.

**Comment by fvicaria** [comment]
Stop being an ass or you will be blocked from here.

**Comment by Lutti92** [comment]
I'm not being an ass dude, stop acting like a butt hurt woman.. but I don't care if you block me as I won't even bother trying to help you optimise the server (or support it financially for that matter) and fix bugs if this is the attitude I'm gonna get for it. 1 time I had a decent response on an issue that was attempted to be dealt with. Rest of the time it just gets closed instantly without even asking further question to help figure out if it 'is' human error, or something in the coding or whatever lol
