### ISSUE TITLE
[RAID] Orbs of Naxxarams

### ISSUE THREAD

**Issue by Anthonhed** [WoWManiaUK/Redemption#959]
The Naxxaram Orbs (Orb of naxxaram) that is located just above the portal in Naxxarams that take you to the two last bosses (Sapphiron etc) does work without doing the other bosses. It should not work before doing the other bosses.

**Comment by Anthonhed** [comment]
Tested in Dev and works now

**Comment by Synathy** [comment]
It is no longer supposed to be like that since the 3.3.0.

> Dungeons & Raids
> -Naxxramas
> --Players no longer need to kill the final bosses in all four wings of this dungeon in order to teleport to Sapphiron. Teleportation orbs have been added to allow players access back and forth from Sapphiron’s lair.

Source: http://us.battle.net/wow/en/game/patch-notes/3-3-0
