### ISSUE TITLE
Transmogging removes tier set bonuses

### ISSUE THREAD

**Issue by ClavosThePally** [WoWManiaUK/Redemption#960]
So I today transmogged my first item, the head of my tier 8.

But when I did so I noticed that one of my 5 items was missing on the tier set bonus.

![wowscrnshot_031417_201044](https://cloud.githubusercontent.com/assets/26167121/23918283/ac6433b4-08f2-11e7-9d75-cce3a082700e.jpg)
out of curiosity I unequiped my shoulders and compared, and yeah, the 4 piece bonus is removed.
![wowscrnshot_031417_201050](https://cloud.githubusercontent.com/assets/26167121/23918286/b0245dd0-08f2-11e7-8538-95077b12f610.jpg)

Out of curiosity I started inspecting transmogged players and they all also had tier piece bonuses disabled.

**Comment by fvicaria** [comment]
This is just visual. You still have the bonus for the item.
