### ISSUE TITLE
[Quest] Deathblow to the Legion

### ISSUE THREAD

**Issue by Dragonfly414** [WoWManiaUK/Redemption#961]
http://www.wowhead.com/quest=10409/deathblow-to-the-legion

I was doing this quest, but after using the teleporter, the NPC who should spawn to start the script, dont spawn.
I tried killing the NPC without, but than it won't complete.

Could you check why the NPC isn't spawning?
Or is there other way to complete the quest?

See movie in questlog :) 

Thanks for checking!

**Comment by elagen** [comment]
i can confirm that while at Socrethar's Seat that the NPC's that should be here are not


Adyen the Lightwarden, Anchorite Karja, and Exarch Orelis approach Socrethar

1) http://www.wowhead.com/npc=18537/adyen-the-lightwarden#starts
2) http://www.wowhead.com/npc=19467/anchorite-karja
3) http://www.wowhead.com/npc=19466/exarch-orelis

![wowscrnshot_031517_083605](https://cloud.githubusercontent.com/assets/22685042/23939874/95fe08d0-095a-11e7-8642-8ff5cbdd59cb.jpg)

These Npc's should be beside the portal when doing the quest so then they can start the quest obbjective

**Comment by fvicaria** [comment]
I have hacked this for now. It will give you quest credit when you kill Socrethar. Full script coming later.

**Comment by Dragonfly414** [comment]
Hi,

Now I cant get the quest at the questgiver ;)
When I talk to her, see is having a grey ? and not autocompleting.
So I cant get the quest now to kill the NPC to end the quest  :)

Hope you will have a check on it :)
