### ISSUE TITLE
[Quest] Do your worst 

### ISSUE THREAD

**Issue by Chibsb** [WoWManiaUK/Redemption#964]
So the problem with this quest is that the npc that im suppose to turn in the quest to , doesnt spawn , well that is what i think ,cause i cant find him , anywhere in The valley of lost hope , ive been looking for him for the past 3 days , and reset the quest 2 times ...

**Comment by elagen** [comment]
i can confirm after doing this quest http://www.wowhead.com/quest=13305/do-your-worst

the npc where you turn the quest in is not there 
http://www.wowhead.com/npc=32404/matthias-lehner

![wowscrnshot_031617_212917](https://cloud.githubusercontent.com/assets/22685042/24019391/afe88b9a-0a8f-11e7-916b-bd8ffdc27d4e.jpg)
