### ISSUE TITLE
[Raid] Anub'Arak. Trial of Crusader(All difficulties)

### ISSUE THREAD

**Issue by GameMasterAlliria** [WoWManiaUK/Redemption#967]
The frozen orbs that are inside the encounter that (typically) ranged dps have to shoot down to provide ice patches are 25~50% of the times bugged and don't drop down and/or do not create the save ice patch.

**Comment by elagen** [comment]
If someone hits the Frost Sphere for any damage above 9K the orb will bug out and stay in the air

If you put a Auto attack on the orb first and then crit 15k the orb will fall

![wowscrnshot_031717_234254](https://cloud.githubusercontent.com/assets/22685042/24066536/811f8a48-0b6b-11e7-8cad-ee489d1d3fd5.jpg)

as you can see in this picture the Sphere on the Floor had an attack of 3k then after that it can be nuked to the floor

the Sphere on the right as you can see is stuck in the air with a damage of over 9k

http://www.wowhead.com/npc=34606/frost-sphere

**Comment by Emcitementz** [comment]
Provide more infos about it, spells used etc ...

**Comment by fvicaria** [comment]
Reopen if it is still an issue.
