### ISSUE TITLE
[Raid] Tenebron, Obsidian Sanctum(All difficulties)

### ISSUE THREAD

**Issue by GameMasterAlliria** [WoWManiaUK/Redemption#968]
While engaging Tenebron prior to pulling Sartharion or after pulling Sartharion. It's debuff (http://www.wowhead.com/spell=61248/power-of-tenebron) Will keep stacking up. Instead of holding down to the max apllication of 1. Which ultimately 1 shots people from the raid. Preventing kills and/or Achievements.

**Comment by Emcitementz** [comment]
Seems like it's not the case anymore.
