### ISSUE TITLE
Mob help call radius too high

### ISSUE THREAD

**Issue by Tykune** [WoWManiaUK/Redemption#969]
I've noticed that something didn't seem quite right with how mobs were being pulled, and during my time in Hillsbrad Farms, I seem to have figured it out. The mob call radius, where mobs are alerted around a singular alerted mob, seems to be obscenely high. It makes areas such as Hillsbrad Foothills a huge, and almost impossible, pain in the backside to deal with. It is even more frustrating when it daisy chains mobs into attacking you from up to 100 yards away (no joke), and it makes certain quests (such as those in Hillsbrad Fields) extremely frustrating.

**Comment by fvicaria** [comment]
Reduced.

**Comment by Tykune** [comment]
Thanks
