### ISSUE TITLE
Soothing Turtle Bisque - Quest Area Misplaced

### ISSUE THREAD

**Issue by Tykune** [WoWManiaUK/Redemption#970]
When you have the quest 'Soothing Turtle Bisque' and you bring up your map to show the areas these snapjaws should be located, these indicated areas do not have Snapjaws located in them, and one of the areas indicated is, oddly enough, on top of an inaccessible mountain. To the northwest and north of the indicated area on the mountains is where the snapjaws are located.

**Comment by Feryk** [comment]
Can you provide a screenshot of what you are seeing on the map?  Are you sure this is not being shown by QuestHelper?

**Comment by fvicaria** [comment]
![image](https://cloud.githubusercontent.com/assets/9414661/24079417/672428a0-0c7f-11e7-920b-b82a37310703.png)

Did you even bother looking? Took me 5 seconds to find the first.

**Comment by Tykune** [comment]
Yes, I did bother looking at the map. The quest took me to Alterac Mountains. I have since completed the quest, so I cannot bring it up.. though I should have tooken a screenshot, which was on me.
