### ISSUE TITLE
Spellcasters wandering off while aggroed?

### ISSUE THREAD

**Issue by Tykune** [WoWManiaUK/Redemption#971]
So I've noticed this rather infrequently with spellcasters around Hillsbrad Foothills, though I do not know if this is a common thing throughout the server. About 30% or so of the time when you aggro them or they aggro on you, they tend to continue down their path while flinging spells at you, even though they shouldn't be able to cast spells while walking and should instead be either stationary or engaging you in combat. I will update with a screenshot when I see it again.

Edit: It seems to occur more frequently when the mage walks into your range.

**Comment by Tykune** [comment]
![wowscrnshot_031817_175417](https://cloud.githubusercontent.com/assets/21979419/24076337/0f8e11f8-0c04-11e7-9616-c8df1703cd22.jpg)
![wowscrnshot_031817_175418](https://cloud.githubusercontent.com/assets/21979419/24076339/12bc1118-0c04-11e7-9a1f-5d5ef6b20c0c.jpg)
![wowscrnshot_031817_175420](https://cloud.githubusercontent.com/assets/21979419/24076340/149fa44a-0c04-11e7-894e-5e2c74b9be60.jpg)

**Comment by elagen** [comment]
I can confirm that after the NPC has finished his/her cast then mobs does move around

here is a short video where you can see the mob move around
https://drive.google.com/open?id=0B_GODmkO59aEZmFIY3lSQ3hMWEE

**Comment by ClavosThePally** [comment]
If I may add to this, this also makes it hard to corner pull, if there's a caster and I pull around a corner, depending on the mob, some shoot through the wall, or others just wait on the other side looking in my general direction
