### ISSUE TITLE
Intimidating Shout not properly working, sometimes.

### ISSUE THREAD

**Issue by Tykune** [WoWManiaUK/Redemption#972]
Intimidating Shout does not seem to work properly sometimes, whereas enemies should be running around for 8 seconds, but there have been some instances where they would not run around and just continue fighting, and sometimes they would just stop fighting and not run around at all. There are other times where I see it work for a split-second, and then they just turn around to continue the fight.

**Comment by elagen** [comment]
i have tested this multiple times and on your action bar it affects up to 5 targets

http://wotlk.openwow.com/spell=5246

if a target has any dot on them or takes a hit it will cancel the fear - but i cant seem to reproduce your issue for where they are running around for a split second - and while they are running around an fighting - i cant reproduce that either

**Comment by Tykune** [comment]
Would rend damage cause the fear to wear off?

**Comment by Tykune** [comment]
Yep, just tested it myself. It is Rend bleed damage that is causing Intimidating Shout to wear off early. I am unsure if this is part of retail, but I will look into it.
