### ISSUE TITLE
Rogue Tier 9 Set Bonus does not proc (Vancleef Conquest Set)

### ISSUE THREAD

**Issue by aelinh** [WoWManiaUK/Redemption#974]
The set bonus for Vancleef's Conquest Set reads "(2) Set: Your Rupture ability has a chance each time it deals damage to reduce the cost of your next ability by 40 energy.", however it does not proc.
Here is the link a piece of the set:
http://wotlk.openwow.com/item=48219

I tested against a training dummy for 10 minutes. Either the proc rate is extremely low or does not trigger.

**Comment by elagen** [comment]
The Proc rate for this Set bonus is Low - most set bonus are around 2-10% with this Proc it is at 2% i believe 
Before **Proc**
![wowscrnshot_032017_073452](https://cloud.githubusercontent.com/assets/22685042/24091423/e8d0e06c-0d3f-11e7-8100-cdd291c43a90.jpg)

**These 2 are with the proc**

![wowscrnshot_032017_073446](https://cloud.githubusercontent.com/assets/22685042/24091439/fc21c9e2-0d3f-11e7-9396-c646b9ce1fd3.jpg)

![wowscrnshot_032017_073422](https://cloud.githubusercontent.com/assets/22685042/24091441/01590146-0d40-11e7-967c-2b7354280661.jpg)
