### ISSUE TITLE
[Spell] Combustion

### ISSUE THREAD

**Issue by GMWeeble** [WoWManiaUK/Redemption#975]
When combustion is used/cast Scorch-Fire Blast-Flamestrike keeps stacking the buff to 10=100% Critt but will not remove the buff. Pyroblast or fireblast will remove  it.

**Comment by Plege** [comment]
I can confirm if Combustion (http://wotlk.openwow.com/spell=28682) is used and only scortch is cast the spell doesn't wear off.

![grafik](https://cloud.githubusercontent.com/assets/24266043/24094146/a0e5726e-0d57-11e7-9b57-5176629fdc2a.png)
here you see 13 scortch (http://wotlk.openwow.com/spell=42859) crits and the buff is still up.

![grafik](https://cloud.githubusercontent.com/assets/24266043/24094176/b7fd1768-0d57-11e7-8057-7f3ec1438122.png)
the same with 5 Fireblast (http://wotlk.openwow.com/spell=42873) crits.

![grafik](https://cloud.githubusercontent.com/assets/24266043/24094226/f325b14c-0d57-11e7-87ba-9aae78480ce4.png)
same with 11 Flamestrike (http://wotlk.openwow.com/spell=46163 please re check that link) crits.

Fireball (http://wotlk.openwow.com/spell=42833), Pyroblast (http://wotlk.openwow.com/spell=42891) adn Frostfire Bolt (http://wotlk.openwow.com/spell=47610) will takedown the buff but only after 3 crits of fireball on it's own. so it's not only that the other spells can't take down the buff, they don't even count towards the 3 crits needed to take down the buff.
