### ISSUE TITLE
[Loot/Quest] Reply-Code Alpha (from Algalon)

### ISSUE THREAD

**Issue by Ford577** [WoWManiaUK/Redemption#976]
One of the drops from algalon is the reply code. This item starts a quest [All is well that ends well] which is to be turned into Rhonin in dalaran. This quest gives a choice of loot then starts an (awesome) rp event in dalaran; however, when the quest item dropped it is unable to be accepted saying "you do not meet the requirements for this quest". There are no requirements to be met to accept this quest.

**Comment by barfmachine** [comment]
its not a bug its only able to be picked up if you have completed the quest  for the key to Algalon 
quest is called "Algalon"  http://www.wowhead.com/quest=13614/algalon . so if you haven't completed you wont be able to start it :)

**Comment by Grindall** [comment]
that quest gives you the key, yes; however, it does not have anything to do with the loot that drops for Algalon himself. I don't see it anywhere in the link you provided unless I'm mistaken.

**Comment by Grindall** [comment]
http://wowwiki.wikia.com/wiki/Quest:All_Is_Well_That_Ends_Well

it is part of the quest chain, but I from my previous private server experience I haven't ever had to do the other quests in order to accept this quest. This could be due to poor scripting, but since the key quest is undoable still due to bugs I suppose you will have to wait to find out.

**Comment by Emcitementz** [comment]
http://fr.wowhead.com/item=46053/code-reponse-alpha#english-comments
It was preventing you to start it because of the previous quest being not completed.
Fixed.

**Comment by Grindall** [comment]
the pic you just linked says anyone who defeated algalon can get the quest? so there are no prerecs? or am i misreading. what you are linking and saying seem to be different

**Comment by Emcitementz** [comment]
Currently, there's a pre-requirement, you need to complete the quest that gives the key for the chamber in order to start the quest from the item. That's wrong, it should be like how it's explained in the pic above.

**Comment by Grindall** [comment]
ahh I understand, thanks for clarifying
