### ISSUE TITLE
[Raid] Ulduar Yogg-saron

### ISSUE THREAD

**Issue by Ford577** [WoWManiaUK/Redemption#980]
The easiest way to explain this issue is via video:
https://www.youtube.com/watch?v=SFyaloBG7SI
@ 00:13
@ 3:44 in the video.
and @ 5:13 in the video.
First off, the adds (faceless ones) in phase one have a bugged timer. They start off just fine, but by the eight and final add you get 3-4 spawn at one time even if you don't step in clouds. The following issue is adds deal too much damage. When adds die they are supposed to be dealing damage to the raid, especially with sara's favor, but at the moment they nearly one shot anyone but a tank. Killing two at once or within close time to eachother isn't possible, and it should be (killing 9 within a few seconds of each other being an achievement).

Stepping in clouds is supposed to be a solid tactic to decrease the time spent in phase one; however, stepping in one for a mere second can cause 3-4 adds to spawn where only one should. Since the adds do too much damage as is, and the timer is too fast toward the end, this makes phase one very difficult.

@3:44/5:13
Specifically, inside yogg's mind there are way too many skulls that spawn. Skulls cause a 2% sanity loss per tick as well as deal a small amount of damage to the player. The npc's/tentacles may also deal too much damage, but that is yet to be confirmed.  A player should be able to enter yogg's mind without a healer, but as of right now it is impossible. This makes achievements such as alone in the dark impossible since too much sanity is lost. 

The throne room at 5:13 is very bugged because the lich king is phased in (and shouldn't be) and likes to go around wrecking players until they nuke all the adds in the room (which he then phases back out as he should always be).

The hit box of yogg's brain inside the brain room is bugged as well. It only allows you to hit it at very specific locations inside the mind.

During phase 3 the hitbox of yogg himself is bugged. It is too small so a melee player can't even hit it since yogg knocks you back if you get too close. This leave all of phase 3 up to ranged players.

**Comment by Emcitementz** [comment]
About the skulls, i've seen tons of videos and there are 6 of them minimum in one room, it all depends of the room, if you can provide us more legit informations about it about the fact there shouldn't be more than 6 skulls per room, we'll do something.

I've tested to stand in one cloud and only one add came out, you probably had other people standing in the other clouds at this moment.

About yogg's brain hitbox, i'm actually struggling with it, seems like there's a special point where players should be able to melee it but it's not the case at the moment here, i'll still try.

**Other bugs are fixed.**
