### ISSUE TITLE
[Quest] The Chain Gun And You

### ISSUE THREAD

**Issue by Wowm** [WoWManiaUK/Redemption#981]
This quest bugged even u kill zombies soldiers do not pop up

**Comment by fvicaria** [comment]
Please follow the procedure described below before creating a new issue:
[How to Properly Report an Issue](https://github.com/wow-mania/Redemption/wiki/How-to-Properly-Report-an-Issue)

This will help developers identify and fix the issue quicker. Incorrectly or unclear reports will simply be deleted.

**Comment by Plege** [comment]
![grafik](https://cloud.githubusercontent.com/assets/24266043/24141463/d0241572-0e23-11e7-8433-1db3f4a2dbc1.png)

The quest is working fine you probably just need to read the quest log that reads you must call the soldiers yourself and then blast a way free for them.
