### ISSUE TITLE
[Quest] Army of the Damned

### ISSUE THREAD

**Issue by Oook8** [WoWManiaUK/Redemption#983]
After taking quest, no Arthas has spawned, so quest can't be completed.

**Comment by fvicaria** [comment]
Please follow the procedure described below before creating a new issue:
[How to Properly Report an Issue](https://github.com/wow-mania/Redemption/wiki/How-to-Properly-Report-an-Issue)

This will help developers identify and fix the issue quicker. Incorrectly or unclear reports will simply be deleted.

**Comment by Oook8** [comment]
Only one i did wrong is I didn't put link to quest. [http://www.wowhead.com/quest=13236/army-of-the-damned#comments](url)

**Comment by fvicaria** [comment]
This quest stopped working and I don't know why.
