### ISSUE TITLE
[Quest] What is Going on?

### ISSUE THREAD

**Issue by redhawk816** [WoWManiaUK/Redemption#984]
http://www.wowhead.com/quest=3982
[What Is Going On?]: In Blackrock Depths. You find Commander Gor'Shak (http://www.wowhead.com/npc=9020) in a cage in the Detention Block. When you accept his quest, you should be attacked by insta-spawned mobs and defend him to complete and open the next quest. Nothing spawns, so the quest is uncompletable.

**Comment by fvicaria** [comment]
duplicate #643 

Please follow the procedure described below before creating a new issue:
[How to Properly Report an Issue](https://github.com/wow-mania/Redemption/wiki/How-to-Properly-Report-an-Issue)

This will help developers identify and fix the issue quicker. Incorrectly or unclear reports will simply be deleted.
