### ISSUE TITLE
Quest: Killing Time (Dragon Blight)(Alliance)

### ISSUE THREAD

**Issue by Wowm** [WoWManiaUK/Redemption#985]
For the Quest: Killing Time when u get quest from Wrynn Jaina should open portal to undercity but she doesnt and even in undercity there is no one to turn in quest 

http://wotlk.openwow.com/quest=13371

**Comment by fvicaria** [comment]
duplicate #721 Please spend 1 minute searching for existing bugs before entering a new one.

Please follow the procedure described below before creating a new issue:
[How to Properly Report an Issue](https://github.com/wow-mania/Redemption/wiki/How-to-Properly-Report-an-Issue)

This will help developers identify and fix the issue quicker. Incorrectly or unclear reports will simply be deleted.
