### ISSUE TITLE
[NPC] Vile Familiar

### ISSUE THREAD

**Issue by idl0r** [WoWManiaUK/Redemption#986]
Hey,

some mobs in the cave (and I guess that affects caves in general) in "Valley of Trials", Kalimdor (Troll/Orc start area) start to bug/jump through the ceiling when being attacked. I had this issue on other servers before already and it also started to make players bug through the ceiling until you're on top of it - it didn't happen here, yet, only mobs until now. Let me know if you need any more information.

**Comment by fvicaria** [comment]
Can you give screenshots, coordinates or npc ids/link.

Please follow the procedure described below before creating a new issue:
[How to Properly Report an Issue](https://github.com/wow-mania/Redemption/wiki/How-to-Properly-Report-an-Issue)

This will help developers identify and fix the issue quicker. Incorrectly or unclear reports will simply be deleted.

**Comment by idl0r** [comment]
"Burning Blade Coven", Kalimdor, 44.75, 54.41. In this case it's a "[Vile Familiar](http://wotlk.openwow.com/npc=3101)" but that should work with other mobs as well I guess.
![wowscrnshot_032117_150052](https://cloud.githubusercontent.com/assets/32827/24151094/0a3ba328-0e48-11e7-8f32-a1ced9cfb59b.jpg)
![wowscrnshot_032117_150053](https://cloud.githubusercontent.com/assets/32827/24151101/0df2dec8-0e48-11e7-885c-13d76e34a2a3.jpg)
![wowscrnshot_032117_150054](https://cloud.githubusercontent.com/assets/32827/24151102/0e1660be-0e48-11e7-9518-a799c360fd3a.jpg)
![wowscrnshot_032117_150104](https://cloud.githubusercontent.com/assets/32827/24151103/0e23c240-0e48-11e7-8c90-98f43e5f2af0.jpg)

**Comment by fvicaria** [comment]
Thank you. This has been fixed and should be live in Redemption tomorrow morning.
