### ISSUE TITLE
Weird "Group Loot" behaviour

### ISSUE THREAD

**Issue by idl0r** [WoWManiaUK/Redemption#987]
Hi,

we were in a group of two and sometimes had the case that someone got e.g. 4 times loot in a row while it actually should be player1, player2, player1, ... The loot indicator also showed the name of the other group member.

~~We also had an issue yesterday (not yet confirmed/reproduced by myself) that a group member had to roll for an item and to wait until others have rolled even though all other party members where far away and by far I mean even on another continent. The others got no roll window at all. I am not sure whether it also happened back then on orig. WoTLK or not but it seemed weird to me.~~

**Comment by elagen** [comment]
If people are in a Party or Raid - No matter where they are and a Common item to Epic drops it will be still be rolled out like normal - so there is no bug there - its the way it was scripted - even back on Retail it had cone that

**Comment by idl0r** [comment]
Ok, that just leaves the other issue.

**Comment by idl0r** [comment]
If a mob has no loot at all then the next one will be again for the same player until there is actual loot. So this is not a bug. Closed. Thanks!
