### ISSUE TITLE
[Quest] Twilight of the Dawn Runner

### ISSUE THREAD

**Issue by jbernady8** [WoWManiaUK/Redemption#988]
It seems that the "rescue Ithania from northpoint tower" part is bugged, no matter what I do i cannot talk to her to complete the objective.  I am able to go to the top of the tower to get the cargo.

**Comment by hotdoggidy** [comment]
Quest (http://wotlk.openwow.com/quest=9437

Upon reaching North Point Tower (46.50, 23.00), Ithania (http://wotlk.openwow.com/npc=17119) should be inside the tower kneeling, arms bound and have a speech interaction that rescues her.

Tested on Redemption. Even before clearing all the hostile npcs i noticed she was not bound or kneeling. Hovering over her with the mouse showed no interaction. 

Looks like she either hasnt reset or never de-spawned.

![wowscrnshot_032117_172100](https://cloud.githubusercontent.com/assets/23442126/24177186/f9f20744-0e5d-11e7-9880-5673e6bc4300.jpg)
