### ISSUE TITLE
[Quest] Army of the Damned

### ISSUE THREAD

**Issue by elagen** [WoWManiaUK/Redemption#991]
with this quest it is working to a certain point 

When trying to use a certain ability from http://www.wowhead.com/npc=31268/the-prodigal-leader

i can not use http://www.wowhead.com/spell=58913/soul-cleave to kill the NPC's http://www.wowhead.com/npc=31254/lordaeron-footsoldier

![wowscrnshot_032317_085647](https://cloud.githubusercontent.com/assets/22685042/24239649/afe44866-0fa6-11e7-8307-2d53bd45a431.jpg)

As you can see it says no target when trying to attack them

**Comment by fvicaria** [comment]
@Rushor Did you get this issue with "No Target" fixed at Dalaran?

**Comment by Emcitementz** [comment]
Should be all good :)
