### ISSUE TITLE
Alpha Worg

### ISSUE THREAD

**Issue by Ebonlox** [WoWManiaUK/Redemption#992]
The quest of this name in Borean Tundra/Rivenwood is not completable. I looked for over an hour for the Garwal who should have been visible via the Eyes of the Eagle buff given by the quest giver. He never appeared. I also repeatedly lost my Worg Costume and Eyes of the Eagle by leaving "Rivenwood" and had to reacquire a costume, abandon the quest, and re accept it to get Eyes of the Eagle back. I finally had a GM complete it for me and ask me to report here.
cheers.

**Comment by Feryk** [comment]
http://www.wowhead.com/quest=11324
http://www.wowhead.com/quest=11326

Since there are two versions of this quest (Horde / Alliance), could you confirm the faction of the toon you did this on?

**Comment by Ebonlox** [comment]
Alliance

**Comment by fvicaria** [comment]
If this works in dev works in red they are identical today.

**Comment by ghostlynx-helios** [comment]
Same issue.  No Garwal even after reacquiring costume, abandoning and then reacquiring buff.
