### ISSUE TITLE
[Hunter] Pet Hp 

### ISSUE THREAD

**Issue by Fygarzx** [WoWManiaUK/Redemption#994]
Seems the pets when dismissed by any metod. The pet's HP is (mostly) cut down to half. I tried dismissing the pet, mounting up, losing it out of sight. and then recalling it, and the pet had it's HP cut down. 
It happens to any Hunter Pet, and only if dismissed alive, if it dies it won't come back alive by doing that. And as well it happens if the pet has more HP that the cut down gives. There's no exact percentage to what it's cut down to. But mostly is to half
Here is two pets of mine (Pink Tallstrider tested with no talents at all. Devilsaur tested with my normal talents including Stamina booster talents)
![another issue](https://cloud.githubusercontent.com/assets/26393271/24280999/f9c1e636-1033-11e7-85d9-710e0a67d837.png)

Recently Tamed to test this, and still happened
![another issue new pet](https://cloud.githubusercontent.com/assets/26393271/24281018/1449b89e-1034-11e7-8c3b-767c17dd00f8.png)

**Comment by elagen** [comment]
i can confirm that when using http://wotlk.openwow.com/spell=883 the pets health is dropped to 50%

when using the spell http://wotlk.openwow.com/spell=883 to call your pet - it should bring the pet to you with full health

**Comment by ClavosThePally** [comment]
I can add to the conversation here, this is because Wild Hunt recently got fixed.
So when you call your pet, it's got it's normal health.

However, after it spawned, the pet talent Wild Hunt kicks in and will add max health, but doesn't do anything with it's normal health.

**Comment by idl0r** [comment]
Well, also related I think:
If you dismount, your pet spawns with ~60-65% HP instead of 100%. That always happens, even if your pet was 100% before. I also asked other hunters. They confirmed that bug.

**Comment by idl0r** [comment]
73% actually.
![wowscrnshot_040117_152822](https://cloud.githubusercontent.com/assets/32827/24579149/f0399c36-16ef-11e7-9e83-c9dfe66c1984.jpg)
![wowscrnshot_040117_152826](https://cloud.githubusercontent.com/assets/32827/24579150/f0532250-16ef-11e7-938f-2a48ed205577.jpg)
![wowscrnshot_040117_152830](https://cloud.githubusercontent.com/assets/32827/24579151/f05f1b64-16ef-11e7-87ff-4b8769083266.jpg)

**Comment by idl0r** [comment]
Hm, just verified that and my pet still spawns with ~73% when I dismount. Hes it been applied to Redemption already or will it be applied soon?
