### ISSUE TITLE
Waterlogged Recipe Quest

### ISSUE THREAD

**Issue by mydnytrose** [WoWManiaUK/Redemption#995]
I put a ticket in yesterday about the waterlogged recipe quest. the item http://wotlk.openwow.com/item=48679 waterlogged recipe is supposed to start a repeatable quest. once you use the item you get http://wotlk.openwow.com/quest=14203 this quest that is supposed to be a repeatable quest. This item is the cooking equivalent of the http://wotlk.openwow.com/item=43297 for jewelcrafting. It's meant to be a non-daily repeatable quest.  As of right now you're only allowed to do the quest 1 time and 1 time only. it cannot be repeated on the server as it states that you're already on the quest despite having already turned it in. My ticket from yesterday was marked "fixed" and closed but the problem is still the same. despite the quest having been turned in yesterday it still states "you are already on this quest". It is not in the quest log yet it cannot be picked up again. An actual fix would be nice instead of saying it is when it still is not working.

**Comment by fvicaria** [comment]
This is fixed in dev please just wait.

**Comment by mydnytrose** [comment]
perhaps don't mark things as done if they aren't then? it implies it's fully completed and implemented hence the annoyance that it still wasn't working. It is extremely misleading to people who see that it's closed because it tells us that it's working. maybe use an in progress option or something to show that it's not 100% done yet but you're working on it?


________________________________

**Comment by Emcitementz** [comment]
> My ticket from yesterday was marked "fixed" and closed but the problem is still the same.
`
> perhaps don't mark things as done if they aren't then?

![screenshot_17](https://cloud.githubusercontent.com/assets/11377592/24311170/44eceb70-10d3-11e7-97b4-ecd61fa9de32.png)

I don't think it needs to be clearer, it doesn't say redemption anyway in any case.
