### ISSUE TITLE
Quest : Army of the Damned

### ISSUE THREAD

**Issue by efdede** [WoWManiaUK/Redemption#996]
I have the above mentioned quest with a problem. When my mana is low because of casting the required spells, i can't use the soul cleave to generate mana.

Please help.

**Comment by fvicaria** [comment]
It's literally two issues below for god sake!

Please follow the procedure described below before creating a new issue:
[How to Properly Report an Issue](https://github.com/wow-mania/Redemption/wiki/How-to-Properly-Report-an-Issue)

This will help developers identify and fix the issue quicker. Incorrectly or unclear reports will simply be deleted.

**Comment by efdede** [comment]
no need to curse or swear. I'm not used to use this forum nor any other forum for that matter.
If you can't respond in a decent way then i dn't need your help.
For help sakes i solved the problem on my own in my own way no thanks your manner of helping.

**Comment by fvicaria** [comment]
If you spent half the time you spent on this lame ass reply to search or read the instructions you would have done way better.
By the way point wear I cursed or swore?
