### ISSUE TITLE
Lockbox respawn timers in Angmar Fortress

### ISSUE THREAD

**Issue by flamingdeath1234** [WoWManiaUK/Redemption#997]
The battered and dented lockbox respawn was around 15 minutes on live and on Redemption they seem to take around 3 hours to respawn. It just seems a bit long to wait for these. Could you please check it out and see if I am just being crazy, or do the lock boxes really just hate  me that much lol. Thank you for your time, it is greatly appreciated.

Angryeyes,
flamingdeath1234

**Comment by fvicaria** [comment]
Please follow the procedure described below before creating a new issue:
[How to Properly Report an Issue](https://github.com/wow-mania/Redemption/wiki/How-to-Properly-Report-an-Issue)

This will help developers identify and fix the issue quicker. Incorrectly or unclear reports will simply be deleted.

**Comment by fvicaria** [comment]
Most of them have a respawn time of 3 minutes however some have a 2-hour spawn time. If you have any 3.3.5a reference that says they should all be 3 minutes let me know. As far as I know this is correct as it is.
