### ISSUE TITLE
No VIP name for toons

### ISSUE THREAD

**Issue by Saltygunner** [WoWManiaUK/Redemption#998]
I have had VIP for a couple of weeks and none of my characters have a title. My account is Saltygunner.

**Comment by Feryk** [comment]
You will need to open a GM ticket for each toon in order for a GM to grant you the title.  Unfortunately, it is not applied automatically.

**Comment by Feryk** [comment]
https://wow-mania.com/forum/viewtopic.php?f=16&t=79&p=120&hilit=maniac+title#p120

2.2 The Maniac Title
Purchasing VIP also gives you the title "Playername The Maniac". This is not automated and you will need to open a ticket. In the ticket, tell us that you bought VIP and want your title. If you have an active subscription, we will give you the title.

**Comment by fvicaria** [comment]
This is not a place for this kind of issue. Please contact support.
