### ISSUE TITLE
[Quest] A Visit to the Doctor

### ISSUE THREAD

**Issue by giorgobacopulos** [WoWManiaUK/Redemption#999]
when i kill the dr i can´t get the quest done....

**Comment by fvicaria** [comment]
Please follow the procedure described below before creating a new issue:
[How to Properly Report an Issue](https://github.com/wow-mania/Redemption/wiki/How-to-Properly-Report-an-Issue)

This will help developers identify and fix the issue quicker. Incorrectly or unclear reports will simply be deleted.

**Comment by fvicaria** [comment]
http://wotlk.openwow.com/quest=13152

**Comment by fvicaria** [comment]
![image](https://cloud.githubusercontent.com/assets/9414661/24320975/0e42d5ba-1139-11e7-8838-bf438b65d30a.png)

It works fine. What could have happened is that the helper NPC did more than 50% of the damage.

**Comment by giorgobacopulos** [comment]
Thank you Janitor I've tryed hit an alt and works perfect
